### PR TITLE
Update blast to 2.9.0

### PR DESCRIPTION
**Pull request by dpryan79**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by dpryan79** [comment]
This is another attempt at #14620. Ping @pmenzel since you asked about this (it's likely to fail at first at least).

**Comment by eggzilla** [comment]
@dpryan79 thanks for giving that a try, I will try to help :-)

**Comment by dpryan79** [comment]
Thanks @eggzilla!

**Comment by dpryan79** [comment]
`ar` is currently being given a wrong parameter somehow.

**Comment by dpryan79** [comment]
Altenatively, it errors on `libncbi_xreader.a`. Either way, it's handling $AR incorrectly.

**Comment by dpryan79** [comment]
Works on Linux at least.

**Comment by dpryan79** [comment]
At the moment I've switched this from using gnutls to openssl. In the meta.yaml something is mentioned about remote queries then not working, which is obviously a problem. That needs to be tested before merging.

**Comment by dpryan79** [comment]
This is a trove of useful information: https://github.com/bioconda/bioconda-recipes/pull/6073

**Comment by dpryan79** [comment]
gnutls is now being used again on both Linux and OSX. It builds for me locally on OSX, we'll see if Linux works still.

**Comment by dpryan79** [comment]
Fingers crossed, I've gotten this to at least compile and pass (non-mulled) testing with gnutls on both linux and OSX.

**Comment by dpryan79** [comment]
OMG it compiled! @eggzilla Can you give this a whirl and see if the `-remote` option works? It'd be best if that were tested before merging.

**Comment by dpryan79** [comment]
@bioconda-bot merge

**Pull request merged**
