### PR TITLE
add EDTA recipe

### PR DESCRIPTION
**Pull request by Juke34**
Extensive de-novo TE Annotator => https://github.com/oushujun/EDTA

----

> Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it.

* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [X] This PR adds a new recipe.
* [X] AFAIK, this recipe **is directly relevant to the biological sciences**
      (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

> Everyone has access to the following BiocondaBot commands, which can be given in a comment:
>
>  * `@BiocondaBot please update` will cause the BiocondaBot to merge the master branch into a PR
>  * `@BiocondaBot please add label` will add the `please review & merge` label.
>  * `@BiocondaBot please fetch artifacts` will post links to packages and docker containers built by the CI system. You can use this to test packages locally before merging.
>
> For members of the Bioconda project, the following command is also available:
>
>  * `@BiocondaBot please merge` will cause packages/containers to be uploaded and a PR merged. Someone must approve a PR first! This has the benefit of not wasting CI build time required by manually merging PRs.
>
> If you have questions, please post them in gitter or ping `@bioconda/core` in a comment (if you are not able to directly ping `@bioconda/core` then the bot will repost your comment and enable pinging).

### CODE REVIEW

**Comment by Juke34** [comment]
@BiocondaBot please fetch artifacts

**Comment by dpryan79** [comment]
It looks like this is distributing precompiled binaries and object files, which won't work very well.

**Comment by oushujun** [comment]
@dpryan79 It does have a number of precompiled binaries: GenericRepeatFinder, genometools-1.5.10, HelitronScanner, and LTR_FINDER. GenericRepeatFinder (#19841) and [genometools-1.5.10](https://anaconda.org/bioconda/genometools) have conda recipes available. HelitronScanner is a java program with precompiled jar files, not sure if it will cause problems. LTR_FINDER does not have a conda recipe at the moment.

**Comment by Juke34** [comment]
You should definitely use the GenericRepeatFinder and genometools recipes instead to hold the code in EDTA. The best would be to have a recipe for LTR_FINDER too.

**Comment by Juke34** [comment]
genometools and tesorter are conflicting

**Comment by oushujun** [comment]
Oh no... 
So what potential troubles it will have to include a precompiled binary? I can remove genometools and let users provide the path instead, or compress it and let users unzip it.

**Comment by Juke34** [comment]
Genometools is working now without conflicts. It is version 1.6.2 while you had version 1.5.something in EDTA bin folder. I hope it is working in the same way.

**Comment by Juke34** [comment]
There is still this warning: 
```
20:01:04 BIOCONDA INFO (OUT) ERROR :: get_rpaths_raw()=[] and patchelf=[''] disagree for /opt/conda/conda-bld/edta_1579723173475/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/share/EDTA/bin/LTR_FINDER_parallel/bin/LTR_FINDER.x86_64-1.0.7/ltr_finder ::
20:01:04 BIOCONDA INFO (OUT) WARNING (edta,share/EDTA/bin/LTR_FINDER_parallel/bin/LTR_FINDER.x86_64-1.0.7/ltr_finder): did not find - or even know where to look for: /lib64/libgcc_s.so.1
20:01:04 BIOCONDA INFO (OUT) WARNING (edta,share/EDTA/bin/LTR_FINDER_parallel/bin/LTR_FINDER.x86_64-1.0.7/ltr_finder): did not find - or even know where to look for: /usr/lib64/libstdc++.so.6
20:01:04 BIOCONDA INFO (OUT) WARNING (edta,share/EDTA/bin/LTR_FINDER_parallel/bin/LTR_FINDER.x86_64-1.0.7/ltr_finder): did not find - or even know where to look for: /lib64/libc.so.6
20:01:04 BIOCONDA INFO (OUT) WARNING (edta,share/EDTA/bin/LTR_FINDER_parallel/bin/LTR_FINDER.x86_64-1.0.7/ltr_finder): did not find - or even know where to look for: /lib64/libm.so.6
```
so I'm not sure LTR_FINDER_parallel works properly

**Comment by Juke34** [comment]
@BiocondaBot please fetch artifacts

**Comment by oushujun** [comment]
@Juke34  LTR_FINDER_parallel uses a precompiled [LTR_FINDER](https://github.com/xzhub/LTR_Finder). This repo is not maintained and there is no clear license nor a license file included in the package. I am not sure if it could be condarized.

**Comment by Juke34** [comment]
This is problematic, without any clear licence we cannot include it. Then you should release a version of EDTA without it. Or find a way to contact the developer to check the license.

**Comment by oushujun** [comment]
I just tested the precompiled LTR_FINDER, it does not work on OSX. I have open an issue in the repo requesting a clear license and hopefully he will reply in the near future... Without a license did you mean we can not make a dedicated conda recipe for it or we cannot even put it in the EDTA conda recipe?

**Comment by Juke34** [comment]
both

**Comment by oushujun** [comment]
OK this is really problematic. I will remove it and put codes to automatically download it upon the initial run. Is this okay?

**Comment by Juke34** [comment]
Something like that should be fine I think, as long it is not fully automated because the user you be prompted for confirmation it is for non-commercial use. And if the user declines EDTA should be able to run skipping the step involving  LTR_FINDER without crashing.

**Comment by oushujun** [comment]
I am contacting the author of LTR_FINDER and see if they can release it as GPLv3.

**Comment by oushujun** [comment]
I tested with the temporary conda repo, installation was successful but the three accessory programs, `EDTA_processI.pl`, `EDTA_raw.pl`, `lib-test.pl`, seem not accessible via `ENV`.

**Comment by dpryan79** [comment]
@bioconda-bot please fetch artifacts

**Comment by dpryan79** [comment]
@oushujun Can you try again with the most recent edits?

**Comment by Juke34** [comment]
@dpryan79 Thank you for the try but like that the scripts are available but will not work as expected because, @oushujun uses `FindBin` to access other utilities, and  `FindBin` does not resolve the links.
@oushujun was trying a version not yet working, I had push to other commit since. So commit 
4706859 should work fine actually.

**Comment by Juke34** [comment]
So, I have reverted the commits to commit 4706859 and added tests for EDTA_processI.pl, EDTA_raw.pl, lib-test.pl.
FYI @oushujun when we call the help of your scripts, it would be better to get an exit code of 0.

**Comment by Juke34** [comment]
@dpryan79 we are now stuck because one dependent tool (currently part of the source code of EDTA) has a licence for  non-commercial use only. 
i.e:[https://github.com/xzhub/LTR_Finder]( https://github.com/xzhub/LTR_Finder)
```
License:  
This software is free for non-commercial use. 
For commercial use, a software agreement is required.
```
We don't really know if that kind of license is compatible with conda usage, could you tell us more?

**Comment by dpryan79** [comment]
It mostly depends on whether they want to allow redistribution or not. Novoalign is commercial but allows redistribution (as far as I know) so we can at least package it. There are other packages that we've had to remove exactly because the authors didn't even want us to allow academics to install the software because then it's possible that non-acedemics could also do so.

**Comment by dpryan79** [comment]
In this particular case I guess you'd have to ask if they want to allow redistribution. We've considered making a "tainted" channel or label for stuff like this but nothing in that regard has happened yet.

**Comment by oushujun** [comment]
The `LTR_FINDER` author has uploaded an MIT license for the repo. I will update and release `LTR_FINDER_parallel` shortly for `conda` construction.

**Comment by Juke34** [comment]
I'm making a LTR_FINDER recipe, maybe it could help for LTR_FINDER_parallel

**Comment by oushujun** [comment]
@Juke34 I have modified `LTR_FINDER_parallel` and get it [released](https://github.com/oushujun/LTR_FINDER_parallel/releases/tag/v1.1). The program now searches for `ltr_finder` in `ENV` first (if installed via conda) and uses the precompiled binary if nothing returned. In this way the original usage was preserved and also adaptable to the upcoming conda version of LTR_FINDER.

**Comment by oushujun** [comment]
I have released EDTA v1.7.6 which should be ready for the conda recipe once the conda version of LTR_FINDER is available.

**Comment by Juke34** [comment]
I wait that [LTR_Finder](https://github.com/bioconda/bioconda-recipes/pull/20006) is merged, then I will update the EDTA recipe to use the lastest release and to include LTR_Finder.

**Comment by Juke34** [comment]
@BiocondaBot please fetch artifacts

**Comment by dpryan79** [comment]
:+1: Go ahead and merge this when you're ready.

**Comment by Juke34** [comment]
@oushujun Can you try again

**Comment by oushujun** [comment]
@Juke34 @dpryan79 Thanks! I will test it today and let you guys know.

**Comment by oushujun** [comment]
I tested and found some small bugs and got them fixed. Please update the recipe to the new release [v1.7.7](https://github.com/oushujun/EDTA/releases/tag/v1.7.7).

There are some warnings from Tensorflow but the results were not affected.

    /home/oushujun/las/bin/miniconda2/envs/test2/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'. _np_qint8 = np.dtype([("qint8", np.int8, 1)])
    /home/oushujun/las/bin/miniconda2/envs/test2/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'._np_quint8 = np.dtype([("quint8", np.uint8, 1)])
    /home/oushujun/las/bin/miniconda2/envs/test2/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.`

 We are getting there!

**Comment by Juke34** [comment]
@BiocondaBot please fetch artifacts

**Comment by Juke34** [comment]
@oushujun another test before merging?

**Comment by oushujun** [comment]
@Juke34 sure!

**Comment by oushujun** [comment]
@Juke34 All tests passed!

**Comment by Juke34** [comment]
@BiocondaBot please merge

**Comment by oushujun** [comment]
One of the dependencies, `mdust`, is only available for Linux64: https://anaconda.org/bioconda/mdust

**Comment by dpryan79** [comment]
That doesn't mean that this package in and of itself is platform dependent.

**Comment by oushujun** [comment]
@dpryan79 There is a user failed to install it on OSX: [EDTA#59](https://github.com/oushujun/EDTA/issues/59)

**Comment by dpryan79** [comment]
Yes, someone will need to get mdust to compile there to make that work.

**Comment by oushujun** [comment]
Looks like someone has tried to add OSX support to the recipe but failed: #3260

**Comment by oushujun** [comment]
There is a user reflecting a channel dependency issue: [EDTA#63](https://github.com/oushujun/EDTA/pull/63). Do users need to specify other channels as some EDTA dependencies are from non-bioconda channels? It seems like a requirement in his situation.

**Comment by dpryan79** [comment]
Yes they need conda-forge as well

**Pull request merged**
