### PR TITLE
Update adapt to 1.3.0

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`adapt`](https://bioconda.github.io/recipes/adapt/README.html): **1.2.0** &rarr; **1.3.0**

[install with bioconda](http://bioconda.github.io/recipes/adapt/README.html) [Conda](https://anaconda.org/bioconda/adapt/files)

Info | Link
-----|-----
Recipe | [`recipes/adapt`](https://github.com//bioconda/bioconda-recipes/tree/bump/adapt/recipes/adapt) (click to view/edit other files)
Releases |[https://github.com/broadinstitute/adapt/tags](https://github.com/broadinstitute/adapt/tags)
Author | `@broadinstitute`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by priyappillai** [comment]
Please merge #28511 with this PR before merging this

**Review by EdHarry — APPROVED** [review]

**Comment by EdHarry** [comment]
@bioconda-bot please merge

**Comment by EdHarry** [comment]
@bioconda-bot please merge

**Comment by EdHarry** [comment]
@BiocondaBot please update

**Pull request closed without merging**
