### PR TITLE
concoct: add linux-aarch64 build

### PR DESCRIPTION
**Pull request by martin-g**
Describe your pull request here

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

### General instructions

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

### Instructions for avoiding API, ABI, and CLI breakage issues
Conda is able to record and lock (a.k.a. pin) dependency versions used at build time of other recipes.
This way, one can avoid that expectations of a downstream recipe with regards to API, ABI, or CLI are violated by later changes in the recipe.
If not already present in the meta.yaml, make sure to specify `run_exports` (see [here](https://bioconda.github.io/contributor/linting.html#missing-run-exports) for the rationale and comprehensive explanation).
Add a `run_exports` section like this:

```yaml
build:
  run_exports:
    - ...

```

with `...` being one of:

| Case                             | run_exports statement                                               |
| -------------------------------- | ------------------------------------------------------------------- |
| semantic versioning              | `{{ pin_subpackage("myrecipe", max_pin="x") }}`     |
| semantic versioning (0.x.x)      | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}`   |
| known breakage in minor versions | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| known breakage in patch versions | `{{ pin_subpackage("myrecipe", max_pin="x.x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| calendar versioning              | `{{ pin_subpackage("myrecipe", max_pin=None) }}`    |

while replacing `"myrecipe"` with either `name` if a `name|lower` variable is defined in your recipe or with the lowercase name of the package in quotes.

### Bot commands for PR management

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

Note that the <code>@BiocondaBot please merge</code> command is now depreciated. Please just squash and merge instead.

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by martin-g** [comment]
@BiocondaBot please fetch artifacts

**Comment by martin-g** [comment]
```
mgrigorov in 🌐 euler-arm-22 in /tmp/concoct via 🅒 test123 took 3s 
❯ tar xvf concoct-1.1.0-py312h4c50a5e_5.tar.bz2                                                                                                                                                            (test123) 
info/test/run_test.sh
info/run_exports.json
info/test/run_test.py
info/hash_input.json
info/recipe/build.sh
info/index.json
info/recipe/meta.yaml.template
info/files
info/has_prefix
info/recipe/meta.yaml
info/recipe/conda_build_config.yaml
info/paths.json
info/about.json
info/git
bin/concoct
bin/concoct_refine
lib/python3.12/site-packages/concoct-1.1.0-py3.12.egg-info/not-zip-safe
lib/python3.12/site-packages/concoct-1.1.0-py3.12.egg-info/PKG-INFO
lib/python3.12/site-packages/concoct/__init__.py
lib/python3.12/site-packages/concoct/utils/dir_utils.py
lib/python3.12/site-packages/concoct/utils/check_dependencies.py
lib/python3.12/site-packages/concoct/transform.py
bin/extract_fasta_bins.py
bin/merge_cutup_clustering.py
bin/cut_up_fasta.py
lib/python3.12/site-packages/concoct/output.py
bin/concoct_coverage_table.py
lib/python3.12/site-packages/concoct/input.py
lib/python3.12/site-packages/concoct/parser.py
lib/python3.12/site-packages/concoct/utils/__init__.py
lib/python3.12/site-packages/concoct/utils/__pycache__/__init__.cpython-312.pyc
lib/python3.12/site-packages/concoct/__pycache__/__init__.cpython-312.pyc
lib/python3.12/site-packages/concoct/utils/__pycache__/dir_utils.cpython-312.pyc
lib/python3.12/site-packages/concoct/utils/__pycache__/check_dependencies.cpython-312.pyc
lib/python3.12/site-packages/concoct/__pycache__/transform.cpython-312.pyc
lib/python3.12/site-packages/concoct/__pycache__/output.cpython-312.pyc
lib/python3.12/site-packages/concoct/__pycache__/parser.cpython-312.pyc
lib/python3.12/site-packages/concoct/__pycache__/input.cpython-312.pyc
lib/python3.12/site-packages/vbgmm.cpython-312-aarch64-linux-gnu.so
lib/python3.12/site-packages/concoct-1.1.0-py3.12.egg-info/dependency_links.txt
lib/python3.12/site-packages/concoct-1.1.0-py3.12.egg-info/top_level.txt
lib/python3.12/site-packages/concoct-1.1.0-py3.12.egg-info/requires.txt
lib/python3.12/site-packages/concoct-1.1.0-py3.12.egg-info/SOURCES.txt

mgrigorov in 🌐 euler-arm-22 in /tmp/concoct via 🅒 test123 
❯ file lib/python3.12/site-packages/vbgmm.cpython-312-aarch64-linux-gnu.so                                                                                                                                 (test123) 
lib/python3.12/site-packages/vbgmm.cpython-312-aarch64-linux-gnu.so: ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, not stripped
```
LGTM!

**Comment by martin-g** [comment]
@BiocondaBot please add label

**Review by aliciaaevans — APPROVED** [review]

**Comment by jlanga** [comment]
This update breaks concoct 1.1.0. I have tried it with sklearn versions 1.2 to 1.5. And it does not work:

```
Up and running. Check /home/jlanga/run_log.txt for progress
Traceback (most recent call last):
  File "/home/jlanga/miniconda3/envs/concoct/bin/concoct", line 90, in <module>
    results = main(args)
              ^^^^^^^^^^
  File "/home/jlanga/miniconda3/envs/concoct/bin/concoct", line 37, in main
    transform_filter, pca = perform_pca(
                            ^^^^^^^^^^^^
  File "/home/jlanga/miniconda3/envs/concoct/lib/python3.12/site-packages/concoct/transform.py", line 5, in perform_pca
    pca_object = PCA(n_components=nc, random_state=seed).fit(d)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jlanga/miniconda3/envs/concoct/lib/python3.12/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jlanga/miniconda3/envs/concoct/lib/python3.12/site-packages/sklearn/decomposition/_pca.py", line 448, in fit
    self._fit(X)
  File "/home/jlanga/miniconda3/envs/concoct/lib/python3.12/site-packages/sklearn/decomposition/_pca.py", line 511, in _fit
    X = self._validate_data(
        ^^^^^^^^^^^^^^^^^^^^
  File "/home/jlanga/miniconda3/envs/concoct/lib/python3.12/site-packages/sklearn/base.py", line 608, in _validate_data
    self._check_feature_names(X, reset=reset)
  File "/home/jlanga/miniconda3/envs/concoct/lib/python3.12/site-packages/sklearn/base.py", line 469, in _check_feature_names
    feature_names_in = _get_feature_names(X)
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jlanga/miniconda3/envs/concoct/lib/python3.12/site-packages/sklearn/utils/validation.py", line 2250, in _get_feature_names
    raise TypeError(
TypeError: Feature names are only supported if all input features have string names, but your input has ['int', 'str'] as feature name / column name types. If you want feature names to be stored and validated, you must convert them all to strings, by using X.columns = X.columns.astype(str) for example. Otherwise you can remove feature / column names from your input data, or convert them all to a non-string data type.
```

Please put it back to `sklearn ==1.1.3`

@martin-g @aliciaevans 

Thanks

**Comment by martin-g** [comment]
Let me open a PR!

**Comment by martin-g** [comment]
How do you test it to make it fail ?

**Comment by martin-g** [comment]
https://github.com/bioconda/bioconda-recipes/pull/48624

**Comment by jlanga** [comment]
I don't know how without sending you a bam and a fasta file

**Comment by jlanga** [comment]
[coverage.tsv.gz](https://github.com/user-attachments/files/15914702/coverage.tsv.gz)
[cut.fa.gz](https://github.com/user-attachments/files/15914704/cut.fa.gz)

Decompress the files above and run concoct like this:

```bash
concoct \
    --threads 8 \
    --composition_file cut.fa \
    --coverage_file coverage.tsv \
    --basename concoct
```

**Comment by jlanga** [comment]
If we could patch `concoct/transform.py` to look like the error message suggests the issue with sklearn would be fixed :

```python
def perform_pca(d, nc, seed):
    d.columns = d.columns.astype(str)  # add this exact line
    pca_object = PCA(n_components=nc, random_state=seed).fit(d)
    return pca_object.transform(d), pca_object
```

I have run the concoct with my old environment and the new one and the important files (*_clustering_*.csv) have the exact md5sums.

**Comment by jlanga** [comment]
#48553 @jfy133

**Comment by martin-g** [comment]
I will update my [PR](https://github.com/bioconda/bioconda-recipes/pull/48624) to use a patch!

**Comment by jfy133** [comment]
That sounds great @jlanga @martin-g !

@alneberg (if you still remember), do you have any objection to the patch?

**Comment by jlanga** [comment]
Glad to see that concoct is getting updates 5 years later! Cheers @jfy133 and @martin-g!!!

**Pull request merged**
