### PR TITLE
Add bioconductor, sleuth, kallisto to osx-whitelist

### PR DESCRIPTION
**Pull request by olgabot**
Our compute cluster is down today and I wanted to play around with some bioconductor packages locally but couldn't install them. I've added all Bioconductor packages to the `osx-whitelist.txt` file. Is there a reason they weren't there before?

### CODE REVIEW

**Comment by chapmanb** [comment]
Olga -- thanks for working on transitioning more packages to OSX. This is definitely welcome. As you say, it takes some local testing and ensuring all dependencies are also in place. I'm a Ubuntu user so can't offer much help other than encouragement but we'd welcome better docs and testing tips from OSX users to have more widespread support in the packages.

**Comment by johanneskoester** [comment]
Hi Olga,
the assertion is caused if all builds of a recipe result in an error. In the case you refer to, if you scroll down in the log you see that r-circlize is not available on osx. r-circlize is part of bioconda, so adding it to the osx-whitelist should solve the problem. In general, building all bioconductor recipes for osx should be as easy as just ensuring that all their dependencies are on the osx whitelist as well (especially the r-* packages).

BTW. great work with seaborn and prettyplotlib, I really like them a lot. Do you want to officially join the bioconda team (no duties involved)?

**Comment by johanneskoester** [comment]
I have just merged pull request #399 which provides a better error message for such cases.

**Comment by daler** [comment]
There was a new bioconductor release after many of the bioconda recipes were built, possibly causing version issues when downloading tarballs. For example, the latest `limma` listed on the bioconductor site is [3.26.3](https://www.bioconductor.org/packages/release/bioc/html/limma.html) while the bioconda recipe here is for 3.26.1, which is likely causing [this error](
https://travis-ci.org/bioconda/bioconda-recipes/jobs/95474277#L574).

So it looks like the tarball URLs I had originally added in these recipes are not stable and will only work if the recipe is for a version that happens to be in the latest bioconductor release. 

Two solutions. One is to update the recipes, which I had started but never finished. The scripts [`bioconductor_scraper.py`](https://github.com/bioconda/bioconda-recipes/blob/master/scripts/bioconductor-scraper.py) and [`update-bioconductor-packages-wrapper.sh`](https://github.com/bioconda/bioconda-recipes/blob/master/scripts/update-bioconductor-packages-wrapper.sh) can help with resolving dependencies for recipe-building. The second solution is to identify a more stable URL for bioconductor packages such that older packages can be found, and edit the recipes accordingly.

Hopefully I'll have time next week to work on this if nobody gets to it before.

**Comment by chapmanb** [comment]
Ryan and Olga;
The Galaxy team has bioaRchive which provides stable URLs for older packages:

http://bioarchive.github.io/
https://bioarchive.galaxyproject.org/

This would still require fixing and updating tarballs to point there but might be worth using for more stable long term tarball URLs. Hope this helps some, thanks so much for helping with the bioconductor install process, these packages are so helpful.

**Comment by daler** [comment]
Thanks Brad, this looks like a great solution. It'll be well worth the effort to update existing recipes and scripts for the gain in long-term stability.

**Comment by daler** [comment]
I don't know what's going on here either. On my local machine I do have that file, and I thought maybe it was created by an older anaconda R installation. So I just tried on a bare Docker image and it worked:

```
docker pull ubuntu
docker run -it ubuntu /bin/bash
apt-get -y install wget
wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
bash Miniconda3-latest-Linux-x86_64.sh -b
~/miniconda3/bin/conda create -y -n tmp -c bioconda -c r r-sleuth
```

So my guess is it has something to do with your local setup. In the past I've had strange conflicts with existing site-wide R installations and the conda version. In some cases if I remember correctly it was due to R-related env vars which I fixed by unsetting them before installing conda R. Later though I took the plunge and removed all non-conda traces of R on my machine. It works well, but I recognize that might not always be an option.

**Comment by daler** [comment]
just reporting back on the original issue of building bioconductor stuff for OSX: I had made some progress in #468 but currently hung up on getting bioconductor-rhdf5 built for OSX (see #476), which is a dependency of r-sleuth.

**Comment by druvus** [comment]
Listed packages in this issue are included in Bioconda since some time back.

**Pull request closed without merging**
