### PR TITLE
Fix NGSCheckMate by setting python 2.7

### PR DESCRIPTION
**Pull request by SPPearce**
NGSCheckMate requires python 2.7, so is not currently building properly.

### CODE REVIEW

**Comment by SPPearce** [comment]
@rpetit3 , as discussed on the nf-core slack.
I don't understand what the zip_keys part is doing - is that needed? Or the python_impl for that matter.

**Comment by rpetit3** [comment]
@biocondabot please fetch artifacts

**Comment by rpetit3** [comment]
@dpryan79 could use some thoughts on this one.

Recently https://github.com/bioconda/bioconda-recipes/pull/42144 was merged for an update to NGSCheckMate, but the tool only works for Python 2.6/2.7, and we no longer build for Python 2. So, a build was never sent of to Anaconda.

This PR from @SPPearce is attempting to add a `custon_build_config.yaml` to get a build from Python 2. We tried bumping the build number to 1, but the linter complained it should be 0. When we set to 0, the CI test never actually happens because I think it recognizes the PR that was merged early.

Do you by chance have any ideas or recommendations we can try? (Thank you!)

**Comment by SPPearce** [comment]
@rpetit3 , this suggests we could turn off the linting check: https://bioconda.github.io/contributor/linting.html#skipping-on-a-per-commit-basis

**Comment by SPPearce** [comment]
The commit message gets round the linting step, now gives [an error](https://dev.azure.com/bioconda/bioconda-recipes/_build/results?buildId=40030&view=logs&j=e14e69ff-a0ae-55c4-b71d-229b239cfb2f&t=4dddc55b-10bc-50fc-ac68-7ff899b7a030) on the keys:

```
ValueError: variant config in /home/vsts/work/1/s/recipes/ngscheckmate/conda_build_config.yaml is ambiguous because it
does not fully implement all zipped keys (To be clear: missing ['numpy'])
or specifies a subspace that is not fully implemented (To be clear:
.. we did not find ['2.7.*'] from {'python': ['2.7.*'], 'python_impl': ['cpython'], 'zip_keys': ['python', 'python_impl']} in python:['3.10.*  *_cpython', '3.9.*  *_cpython', '3.8.*  *_cpython']).
```

**Comment by rpetit3** [comment]
@BiocondaBot please fetch artifacts

**Comment by rpetit3** [comment]
@SPPearce give the artifacts a try. Looks like it atleast built it for 2.7

**Comment by SPPearce** [comment]
@rpetit3 , they appear to be working, in that I can run the docker container and it contains the scripts.

**Comment by SPPearce** [comment]
The main functions are working locally for me. The perl helper script is not, but that is less important (I want that to be able to make a sarscov2 file for testing in nf-core/modules).

**Comment by SPPearce** [comment]
@BiocondaBot please fetch artifacts

**Comment by SPPearce** [comment]
@rpetit3 , the container now has the correct shebang on the perl scripts, it seems to be working, can we merge now?

**Comment by SPPearce** [comment]
@BiocondaBot please add label

**Review by rpetit3 — APPROVED** [review]

**Pull request merged**
