### PR TITLE
Stacks: better tests

### PR DESCRIPTION
**Pull request by abretaud**
* [x] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

Following the discussion in #2367

### CODE REVIEW

**Comment by abretaud** [comment]
@yhoogstrate before merging, does it look good to you like this?

**Comment by yhoogstrate** [comment]
If the light turns green, yes! `command -v` exits with `1` if the tool can not be found or not be invoked (http://pubs.opengroup.org/onlinepubs/009696899/utilities/command.html).

**Comment by abretaud** [comment]
Green! Let's go
@bgruening this 1.42 version will magically appear [there](https://quay.io/repository/mulled/stacks?tab=tags), right? is there a delay for this?

**Comment by bgruening** [comment]
It will be compiled and tested again in travis after merge, if this succeeds it will be pushed. This is the delay.

**Pull request merged**
