### PR TITLE
stringMLST

### PR DESCRIPTION
**Pull request by ar0ch**
* [x] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

This updates @Takadonet's recipe to the latest version of stringMLST, and includes the correct licensing information (previous tag was still under our old license). Also places a hard dependency on samtools/htslib >=1.0, which was relaxed during the initial submission to no-requirement.

 @bioconda/core If you could review, that'd be wonderful

Thanks,
Aroon

### CODE REVIEW

**Comment by tomkinsc** [comment]
Looks good, maybe add a `license_file` key:value pair under `license` to point to one of the license files in the source tarball.

**Comment by druvus** [comment]
@ar0ch @tomkinsc Skip is set to True so the recipe wasn't tested or built.

**Comment by ar0ch** [comment]
@druvus Hmm, the original accepted recipe has that value set.  :-/ 

I'll fix that and submit a new PR

**Comment by ar0ch** [comment]
The output from Travis doesn't appear to change when the [`Skip` flag is unset](https://travis-ci.org/ar0ch/bioconda-recipes/jobs/226489171)

The recipe does build fine when manually run through `conda build`

**Comment by druvus** [comment]
@ar0ch I fixed it in #4586

**Comment by ar0ch** [comment]
Thanks @druvus!

**Pull request merged**
