### PR TITLE
Update pdfkit

### PR DESCRIPTION
**Pull request by Char-Al**
Update pdfkit following guidilenes for pypi project

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by Char-Al** [comment]
@BiocondaBot please add label

**Comment by dpryan79** [comment]
@BiocondaBot please fetch artifacts

**Comment by cbrueffer** [comment]
This seems to be the same as `python-pdfkit` in conda-forge which is already up to date: https://github.com/conda-forge/python-pdfkit-feedstock

**Comment by cbrueffer** [comment]
The conda-forge version is not up to date, but there's a PR that seems ready to go in (just has a permissions issue, may need some admin prodding): https://github.com/conda-forge/python-pdfkit-feedstock/pull/3

**Comment by Char-Al** [comment]
If I understand correctly, if it is in conda-forge, this package can be removed from bioconda ?
Or may be there is a problem with the recipe itself ?

Thank you !

**Comment by cbrueffer** [comment]
Exactly; it can be removed here and the dependencies in consumer recipes in Bioconda should be updated to `python-pdfkit`.

**Comment by Char-Al** [comment]
ok thank you !

**Pull request closed without merging**
