### PR TITLE
added weblogo3

### PR DESCRIPTION
**Pull request by rfarouni**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe. 
* [x] This PR does something else (explain below).

This recipe is for the latest version of WebLogo (WebLogo 3.5.0). It updates the recipe `python-weblogo` for WebLogo 3.4.0. Since there is another recipe for `weblogo` for WebLogo 2, and `python-weblogo` is not a descriptive name for WebLogo3 (it can be easily missed), I am adding a third recipe with the name `weblogo3`

### CODE REVIEW

**Comment by daler** [comment]
weblogo 2 and weblogo 3 seem to be substantially different (perl and python respectively). The separation of `weblogo` and `python-weblogo` bioconda recipes appears to have come from https://github.com/bioconda/bioconda-recipes/issues/976. However, nowadays we would probably resolve this by pinning to `weblogo >3` in a recipe requiring the python version. I believe #976 was also before we had a system for retaining older version, further contributing to the rename.

I would propose the following:

- remove existing recipe for `python-weblogo` from git (the conda package will remain on anaconda.org)
- move existing `weblogo` to `weblogo/2.82`
- track the latest `weblogo 3.x` in the main `weblogo` recipe

@bioconda/core, thoughts on this?

**Comment by rfarouni** [comment]
@daler 

Agree. Also The recipe in  `python-weblogo` doesn't not include the ghostscript in the requirements. Also when I run weblogo I get a numpy error that I don't get when I install WebLogo 3.5 from pip

**Comment by bgruening** [comment]
:+1: for @daler's suggestion!

**Comment by rfarouni** [comment]
@daler The weblogo/2.8.2 recipe keeps on failing. 

```

Here is my latest attempt

**Comment by daler** [comment]
@rfarouni I fixed seqlogo 2.8.2 to use `#!/usr/bin/env perl` instead of the hard-coded `#!/usr/bin/perl`, and added numpy as a build-time dependency to 3.5.0, since its setup.py seemed to need it. Might need an extra test to check for graphviz though.

**Comment by bgruening** [comment]
LGTM! Thanks a lot @rfarouni and @daler!

**Comment by yhoogstrate** [comment]
I think the license is MIT (https://github.com/WebLogo/weblogo/blob/master/LICENSE.txt)

**Pull request merged**
