### PR TITLE
graphclust conda 0.1.8

### PR DESCRIPTION
**Pull request by mmiladi**
* [x] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by mmiladi** [comment]
@bioconda/core PR CI tests do not progress, is something broken?

**Comment by CicoZhang** [comment]
@mmiladi Mine is also in the same doldrums.

**Comment by bgruening** [comment]
Someone deactivated PR testing I think. Let's see if it gets better.

**Comment by mmiladi** [comment]
Thanks, test started. Other PRs are also affected.

**Pull request merged**
