### PR TITLE
PacBio: Remove `isoseq3` dependencies

### PR DESCRIPTION
**Pull request by armintoepfer**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by dpryan79** [comment]
@armintoepfer Was the previous build not working on OSX?

**Comment by armintoepfer** [comment]
Right. We only build static binaries for linux, so far. As mentioned earlier on another PR, at some point recipes were changes such that only skipping linux did not work and we were told to use `noarch: generic` to get them merged. I'm slowly moving recipes back to the state where we only allow installation from linux.

**Comment by dpryan79** [comment]
Ah, gotcha, makes sense then.

**Comment by dpryan79** [comment]
@bioconda-bot merge

**Comment by armintoepfer** [comment]
@dpryan79 Any idea why a fresh `conda install isoseq3` still tries to install all those dependencies that I deleted in this PR?

**Pull request merged**
