### PR TITLE
Add recipe for pIRS 2.0.2

### PR DESCRIPTION
**Pull request by npavlovikj**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by npavlovikj** [comment]
@bgruening , the "test-linux" build was successful this morning, but since few hours ago I keep getting "**[Mar  1 07:03:38] ERRO Task processing failed: Unexpected exit code [1] of container [2a1b9195c4c8 step-6808b9dda5], container preserved**" errors. Are there any changes in the test system since then, or there are some packages I need to maybe update?

**Comment by bgruening** [comment]
@npavlovikj this is a problem with the current conda version in our Docker container. @mbargull is working on this.

**Comment by npavlovikj** [comment]
Thanks for letting me know @bgruening ! I figured it was related to #279. Looking forward to the fix.

**Comment by mbargull** [comment]
Additionally, @bgruening found a nice little workaround we can use for now.

**Comment by npavlovikj** [comment]
Thank you so much @bgruening and @mbargull  - the fix worked perfectly!

**Pull request merged**
