### PR TITLE
Update pantools to v3.4.0

### PR DESCRIPTION
**Pull request by dirkjanvw**
We recently released [PanTools v3.4.0](https://git.wur.nl/bioinformatics/pantools/-/releases/v3.4.0), reorganised the structure of our [git](https://git.wur.nl/bioinformatics/pantools) and sorted out the current dependencies of PanTools. With this merge request, I would like to update the PanTools recipe for v3.4.0 which also takes care of the now known dependencies and release for this version.

### CODE REVIEW

**Comment by rpetit3** [comment]
@dirkjanvw thank you for making the update. Would it be ok if you were added as a maintainer for this recipe? 

(_I realize you are one of the main devs, just wanted to make sure_)

**Comment by dirkjanvw** [comment]
@BiocondaBot please add label

**Review by rpetit3 — APPROVED** [review]

**Comment by rpetit3** [comment]
In this case, maybe not much since will change for you since this recipe needs to be manually updated. But now in the future incase someone else tries to update the recipe they'll have someone they can reach out to for help.

Thank you so much!

**Comment by dirkjanvw** [comment]
Aha that sounds good!

**Comment by dirkjanvw** [comment]
@rpetit3 I finished the changes I wanted and I'm happy with the current merge request! Could you please instruct the bot to merge this if you still approve? (Or should I instruct the bot myself?)

**Comment by rpetit3** [comment]
@BiocondaBot please merge

**Pull request merged**
