### PR TITLE
Add pggb (PanGenome Graph Builder)

### PR DESCRIPTION
**Pull request by AndreaGuarracino**

### CODE REVIEW

**Comment by AndreaGuarracino** [comment]
Hi @rpetit3, here is the fresh `pggb` recipe PR.

Wondering if it could be simplified a bit, as `pggb` is a bash script that uses tools that have a corresponding recipe (that is `wfmash`, `seqwish`, `smoothxg`, `odgi`, `vg`, and `gfaffix`). I hope for some of your magic!

**Comment by rpetit3** [comment]
@AndreaGuarracino Mind testing the artifacts above to see if everything runs as expected?

```
conda create -n temp-pggb -c https://175923-42372094-gh.circle-artifacts.com/0/tmp/artifacts/packages -c conda-forge -c bioconda pggb 
```

**Comment by AndreaGuarracino** [comment]
Thank you @rpetit3, we almost did it. There is a version mismatch with a `pggb`'s component (`smoothxg`) that is too old with respect to the others. Working on it.

**Comment by AndreaGuarracino** [comment]
Here the updated `smoothxg`: https://github.com/bioconda/bioconda-recipes/pull/31593.

**Comment by rpetit3** [comment]
@AndreaGuarracino do you require a specific version of `smoothxg` and `odgi`?

**Comment by AndreaGuarracino** [comment]
Hi @rpetit3, for `pggb` v0.2.0 are required `smoothxg` v0.6.1 and `odgi` >= v0.6.2.

**Comment by rpetit3** [comment]
`smoothxg==v0.6.1` or `smoothxg>=v0.6.1`

**Comment by rpetit3** [comment]
@AndreaGuarracino I think you might be all set, let me know if this looks good to you

**Review by rpetit3 — APPROVED** [review]

**Comment by AndreaGuarracino** [comment]
@rpetit3, `smoothxg` 0.6.1 is the last version available, so it is okay to have it == 0.6.1 as you already did.

I have tested the package and it works! I've just pushed the missing dependencies to have a correct functioning when all options are activated.

I will try the final package again when it is ready.

**Comment by AndreaGuarracino** [comment]
@rpetit3, it works everything but a single instruction, that is the `multiqc` call (requested with the `-m` flag):

`pggb -i data/HLA/DRB1-3123.fa.gz -p 90 -s 3000 -G 2000 -n 8 -t 2 -v -L -U -V 'gi|568815561:#' -o out -C cons,10,100,1000,10000 -Z -m`

```
...
  /// MultiQC 🔍 | v1.11

|           multiqc | Not cleaning sample names
Traceback (most recent call last):
  File "/home/guarracino/miniconda3/envs/temp-pggb/bin/multiqc", line 6, in <module>
    from multiqc.__main__ import multiqc
  File "/home/guarracino/miniconda3/envs/temp-pggb/lib/python3.8/site-packages/multiqc/__main__.py", line 53, in <module>
    multiqc.run_cli(prog_name="multiqc")
  File "/home/guarracino/.local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/guarracino/.local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/guarracino/.local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/guarracino/.local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/guarracino/miniconda3/envs/temp-pggb/lib/python3.8/site-packages/multiqc/multiqc.py", line 239, in run_cli
    multiqc_run = run(
  File "/home/guarracino/miniconda3/envs/temp-pggb/lib/python3.8/site-packages/multiqc/multiqc.py", line 590, in run
    template_mod = config.avail_templates[config.template].load()
  File "/home/guarracino/miniconda3/envs/temp-pggb/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2463, in load
    self.require(*args, **kwargs)
  File "/home/guarracino/miniconda3/envs/temp-pggb/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2486, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/home/guarracino/miniconda3/envs/temp-pggb/lib/python3.8/site-packages/pkg_resources/__init__.py", line 782, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (idna 3.1 (/home/guarracino/miniconda3/envs/temp-pggb/lib/python3.8/site-packages), Requirement.parse('idna<3,>=2.5'), {'requests'})
Command exited with non-zero status 1
multiqc drib1 -s -o drib1 -c drib1/multiqc_config.yaml
```

It seems there is a version conflict. Is it fixable?

**Comment by rpetit3** [comment]
Does it work if you change the `idna` version in that environment?

```
conda install -c conda-forge -c bioconda 'idna=2.8'
```

**Comment by AndreaGuarracino** [comment]
@rpetit3, yes, it worked after changing the `idna` version by executing your command line in the environment!

**Comment by rpetit3** [comment]
I'm going to pin the `idna` version so that you can get this merged, but I think its something that should be followed up downstream (`multiqc` or `requests`)

**Comment by AndreaGuarracino** [comment]
Thank you, I can't wait for `pggb` to be integrated into bioconda, it will make life much easier for many pangenomic users. I confirm the last package works correctly.

**Comment by AndreaGuarracino** [comment]
@BiocondaBot please add label

**Review by rpetit3 — APPROVED** [review]

**Comment by rpetit3** [comment]
@biocondabot please merge

**Pull request merged**
