### PR TITLE
Bump Pynnotator

### PR DESCRIPTION
**Pull request by raonyguimaraes**
This fixes the pynnotator bioconda installation. Before it was detecting the Linux distribution using platform module and this is known to cause error when being called inside a conda environment. We are using distro package now.

Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it. Note that if you are not already a member of the bioconda project (meaning that you can't add this label), please ping `@bioconda/core` so that your PR can be reviewed and merged (please note if you'd like to be added to the bioconda project). Please see https://github.com/bioconda/bioconda-recipes/issues/15332 for more details.

* [X ] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [ ] This PR adds a new recipe.
* [X ] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [X ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by apeltzer** [comment]
Oh that was already autobumped: https://github.com/bioconda/bioconda-recipes/pull/17250

**Comment by raonyguimaraes** [comment]
@dpryan79 

For some reason this bump did not went through. 

I still only get version 1.9.1 using bioconda. What exactly happened?

Also every time I create a pull request there is another one created by Biocondabot. Which one should get merged

**Comment by dpryan79** [comment]
@raonyguimaraes `conda create -n pynnotator python=3.7 pynnotator` gets 1.9.2. The bot runs every hour or so and looks for new versions of packages. You just happen to create your PR at about the same time. It doesn't matter which one gets merged, but since you can't merge your own PRs without someone else approving it it's easier to just use the bot's PR (you can just approve and merge it, or modify first if needed).

BTW, you can type `@bioconda-bot autobump some_recipe` on gitter to have it create a PR for you for a new version of a package.

**Comment by raonyguimaraes** [comment]
Ok Thanks Devon!

**Pull request closed without merging**
