### PR TITLE
Update bioconductor-variantannotation to 1.26.0

### PR DESCRIPTION
**Pull request by vladsaveliev**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by vladsaveliev** [comment]
Hmm, the issue that I was hoping to fix with this (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=897540) just occurred here. Might have to do with some other library.

**Comment by vladsaveliev** [comment]
Trying to see if also updating genomeinfodb, genomicranges, and iranges will address the issue.

**Comment by daler** [comment]
@vladsaveliev it's complicated, see here: https://github.com/bioconda/bioconda-recipes/pull/8925#issuecomment-389660854

**Comment by vladsaveliev** [comment]
Thanks Ryan, I see, I was too optimistic. Will try to address the IRanges issue by downgrading instead

**Comment by daler** [comment]
@vladsaveliev and I should have specified that we didn't want to merge this, it will break a lot!

**Comment by vladsaveliev** [comment]
Got you, I'll revert the commits and make a new PR for that!

**Pull request merged**
