### PR TITLE
Conda recipe for mirfix

### PR DESCRIPTION
**Pull request by jfallmann**
:information_source:
Bioconda has finished the [GCC7 migration](https://github.com/bioconda/bioconda-recipes/issues/13578). If you are dealing with C/C++ or Python package it can be that you need to rebuild other dependent packages. [Bioconda utils - update-pinning](https://bioconda.github.io/updating.html#updating-recipes-for-a-pinning-change) will assist you with that. If you have any questions please use [issue 13578](https://github.com/bioconda/bioconda-recipes/issues/13578).

----------------

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by jfallmann** [comment]
Bootstrap fails with ERROR:conda.core.link:An error occurred while installing package 'defaults::openssl-1.0.1k-1', this is to try CircleCI, no idea how to fix this if this is bootstrap related

**Comment by jfallmann** [comment]
@bioconda/core Anybody seen this before and can help? Same issue on CircleCI and local bootstrap

**Comment by jfallmann** [comment]
@bgruening Sorry for the Spam but I'm completely stuck here

**Comment by jfallmann** [comment]
@bgruening true, whyever it is still there, will fix upstream before merging if this works now, thx!

**Comment by jfallmann** [comment]
@bgruening, looks good now, just RNA import fails, will fix upstream and then reopen, thanks for the assist!

**Comment by bgruening** [comment]
Ah, ok, nice! You are always welcome!

**Pull request closed without merging**
