### PR TITLE
Circle-Map bioconda recipe

### PR DESCRIPTION
**Pull request by iprada**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by PertuyF** [comment]
Hi :)

Did you made or edited this recipe by hand? You should use `conda skeleton pypi Circle-Map` which will create a base `meta.yaml` recipe for you. This will introduce several good practices for new recipes:

- use jinja variables where relevant (name, version, ...)
- use in-recipe build command (no need for build.sh)
- indicate all fields regarding licensing (license, license family, license file) which you will likely have to customize. Using MIT license means you should include your license file in this conda package.

There is also an issue with the structure of the python package itself. Currently Python installs this package as `src`, see the recipe's test `import src`, which is ambiguous and should be fixed upstream. If needed there are several guides regarding packaging of Python projects, [this one](https://the-hitchhikers-guide-to-packaging.readthedocs.io/en/latest/) is quite complete, otherwise see what the Pypa says.

**Comment by iprada** [comment]
Hey, thanks for the info! I will fix the errors you mentioned and resubmit again

**Comment by iprada** [comment]
@bioconda/core all the test have passed

**Comment by iprada** [comment]
@bioconda/core Can I be added to the team?

**Comment by dpryan79** [comment]
I've made some adjustments. When the tests pass this can be merged and you added.

**Comment by iprada** [comment]
> I've made some adjustments. When the tests pass this can be merged and you added.

Great!

**Comment by dpryan79** [comment]
@bioconda-bot recheck

**Comment by dpryan79** [comment]
@bioconda-bot merge

**Pull request merged**
