### PR TITLE
Update spectrum_utils to 0.3.4

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`spectrum_utils`](https://bioconda.github.io/recipes/spectrum_utils/README.html): **0.3.3** &rarr; **0.3.4**

[install with bioconda](http://bioconda.github.io/recipes/spectrum_utils/README.html) [Conda](https://anaconda.org/bioconda/spectrum_utils/files)

Info | Link
-----|-----
Recipe | [`recipes/spectrum_utils`](https://github.com//bioconda/bioconda-recipes/tree/bump/spectrum_utils/recipes/spectrum_utils) (click to view/edit other files)
Releases |[https://pypi.org/pypi/spectrum_utils/json](https://pypi.org/pypi/spectrum_utils/json)

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by bittremieux** [comment]
I'm not sure what the problem is, it should be a simple version update.

@BiocondaBot please add label.

**Comment by bittremieux** [comment]
@BiocondaBot please add label

**Comment by RalfG** [comment]
Apparently it's recommended to have `matplotlib-base` instead of `matplotlib` as dependency, as that avoids adding `pyqt` to the dependency list: https://conda-forge.org/docs/maintainer/knowledge_base.html#matplotlib

**Comment by bittremieux** [comment]
Nice catch, thanks @RalfG. I've changed this and opened a new PR: #23196

I don't understand why the tests failed in this PR though, because it failed at the linting stage while only the version number and the hash were changed. The new PR passes linting though, weird.

**Comment by RalfG** [comment]
Probably the matplotlib check got added to bioconda linting between the previous release of spectrum_utils and this one.

**Pull request closed without merging**
