### PR TITLE
attempting to update `khmer` pinnings

### PR DESCRIPTION
**Pull request by dr-joe-wirth**
trying to update `khmer` recipe so that it is compatible with versions of python up to 3.11.x (<3.12).

### CODE REVIEW

**Comment by dr-joe-wirth** [comment]
@rpetit3 i am attempting to update the `khmer` pinnings to allow this recipe to work with `primerForge` as we discussed in PR #48898

**Comment by dr-joe-wirth** [comment]
@martin-g @rpetit3 looks like this recipe is working with the updated python versions specified.

i have permissions to review pull requests, but I am a bit reluctant since this is not my recipe and I have never updated package pinnings before. I would greatly appreciate if someone else could review my changes before merging.

**Review by lskatz — APPROVED** [review]
LGTM

**Comment by rpetit3** [comment]
@biocondabot please fetch artifacts

**Comment by rpetit3** [comment]
@dr-joe-wirth @lskatz 

Looks like nothing was actually built:

```
14:06:14 BIOCONDA INFO 1 recipes to build and test: 
khmer
14:06:14 BIOCONDA INFO Determining expected packages for recipes/khmer
Adding in variants from internal_defaults
Adding in variants from /opt/mambaforge/envs/bioconda/conda_build_config.yaml
Adding in variants from /opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/bioconda_utils/bioconda_utils-conda_build_config.yaml
Adding in variants from /home/vsts/work/1/s/recipes/khmer/conda_build_config.yaml
14:06:15 BIOCONDA INFO Nothing to be done for recipe recipes/khmer
14:06:15 BIOCONDA INFO BUILD SUMMARY: successfully built 0 of 1 recipes

Finishing: Test

```

**Comment by dr-joe-wirth** [comment]
@rpetit3 maybe because i didn't update the build number?

**Pull request merged**
