### PR TITLE
add smina

### PR DESCRIPTION
**Pull request by dkoes**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by bgruening** [comment]
@dkoes is there any way to compile this from source?

**Comment by dkoes** [comment]
Well, yes, but the static binary will be much more robust considering the number of dependencies.  The autodock-vina recipe is also a binary distribution.

**Comment by mwojcikowski** [comment]
Does it play nice with new OpenBabel (2.4+)? Last time I tried compiling there was a problem with adding hydrogens.

**Comment by bgruening** [comment]
@mwojcikowski are you ok with merging it. 
I'm, but it would be nice to have this build from source at some point.

**Comment by dkoes** [comment]
One of the reasons I prefer to distribute a static executable is I can control what version of OpenBabel is used.  I'm not aware of any problems with hydrogens in this current distribution.

**Comment by mwojcikowski** [comment]
I'm fine with merging it as binary. I'm using smina as a static binary myself.

But ultimately I'd prefer smina with recent OpenBabel, 2.3.2 is over 5 years and has many known and resolved bugs.

**Comment by mwojcikowski** [comment]
@dkoes I see it was in fact fixed a while ago, sorry for misinforming. But the fact that OB 2.3.2 is ancient is valid.

The best way to figure this recipe out would be to make a static build using specific OB version, this way we could require OB during build and not on runtime. I'm afraid that OB package does not contain static libraries you can link against.

**Comment by bgruening** [comment]
@dkoes @mwojcikowski please keep the discussion going. Its great to see the cheminformatic community here more and more!

I will merge this as a first step!
Thanks.

**Comment by dkoes** [comment]
It isn't using 2.3.2, it's using a development version (specifically, github.com:dkoes/openbabel.git).  It has been a while since I've pulled from upstream (about a year) but it isn't ancient.

**Comment by mwojcikowski** [comment]
Ok, fine. But unless it's specified somewhere we do not know that. You can pin to a git commit during a build from source and not use a openbabel package.

I just noticed that te versioning scheme is really bad. `01.30.2018` will be older than `11.09.2017`. Let's reverse the date to `Y-M-D`, as in RDKit if you prefer dates to release versions.

**Comment by dkoes** [comment]
I submitted a pull request (#6925) to fix the versioning.

I don't think there is any particular dependency on the openbabel version in smina - it should build fine with any version.  But the static binary is built with whatever version is installed on my workstation, which happens to be my fork (which I will updated from upstream in the next build).

**Pull request merged**
