### PR TITLE
Update ragtag to 1.0.2

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`ragtag`](https://bioconda.github.io/recipes/ragtag/README.html): **1.0.1** &rarr; **1.0.2**

[install with bioconda](http://bioconda.github.io/recipes/ragtag/README.html) [Conda](https://anaconda.org/bioconda/ragtag/files)

Info | Link
-----|-----
Recipe | [`recipes/ragtag`](https://github.com//bioconda/bioconda-recipes/tree/bump/ragtag/recipes/ragtag) (click to view/edit other files)
Releases |[https://pypi.org/pypi/RagTag/json](https://pypi.org/pypi/RagTag/json)
Recipe Maintainer(s) | @malonge

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by malonge** [comment]
I'm not sure what happened but this auto pull request happened before I was able to update the DOI. Everything is up-to-date on [my branch](https://github.com/malonge/bioconda-recipes/blob/ragtag_v1.0.2/recipes/ragtag/meta.yaml).

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
@malonge feel free to create your PR next time or change this PR. Thanks for your contribution and congrats for the pub!

**Comment by rpetit3** [comment]
@bioconda-bot please merge

**Comment by malonge** [comment]
Thanks!

**Pull request merged**
