### PR TITLE
Update beacon2-import to 1.0.8

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`beacon2-import`](https://bioconda.github.io/recipes/beacon2-import/README.html): **1.0.7** &rarr; **1.0.8**

[install with bioconda](http://bioconda.github.io/recipes/beacon2-import/README.html) [Conda](https://anaconda.org/bioconda/beacon2-import/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/beacon2-import`](https://github.com//bioconda/bioconda-recipes/tree/bump/beacon2_import/recipes/beacon2-import) (click to view/edit other files)
Summary | Seamlessly import and query genomic variant data from a beacon
Home | [https://pypi.org/project/beacon2-import/](https://pypi.org/project/beacon2-import/)
Releases |[https://pypi.org/pypi/beacon2-import/json](https://pypi.org/pypi/beacon2-import/json)
Recipe Maintainer(s) | @khaled196

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by khaled196** [comment]
@BiocondaBot help

**Comment by khaled196** [comment]
@BiocondaBot please fetch artifacts

**Comment by khaled196** [comment]
HI @rpetit3 

Can you please help with this pull request? the error message is about access to Azure. I filled out the form, but I need to update the tool for the Galaxy wrapper.

**Comment by martin-g** [comment]
> I filled out the form

The form should be filled by a member of Bioconda team.
See https://github.com/bioconda/bioconda-recipes/issues/41025#issuecomment-2109155678

**Pull request merged**
