### PR TITLE
New attempt to migrate to bioconda-utils

### PR DESCRIPTION
**Pull request by bgruening**
* [x] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [x] This PR does something else (explain below).

### CODE REVIEW

**Comment by bgruening** [comment]
@johanneskoester @daler new try. This time with our image but with bioconda-utils installed.
If this is working we can try to sync the container with conda-forge.

```
docker run -i -t -v `pwd`:/bioconda-recipes/ bioconda bioconda-utils build /bioconda-recipes/recipes /bioconda-recipes/config.yml --packages osra
```
 Please feel free to push into this branch. I'm not sure when I can finish this.

**Comment by bgruening** [comment]
One error is this one: https://travis-ci.org/bioconda/bioconda-recipes/jobs/152045394#L2407

**Comment by bgruening** [comment]
@daler @johanneskoester Here are a few test against this branch:

* https://github.com/bioconda/bioconda-recipes/pull/2170 python package
* https://github.com/bioconda/bioconda-recipes/pull/2171 compilation
* https://github.com/bioconda/bioconda-recipes/pull/2173 perl
* https://github.com/bioconda/bioconda-recipes/pull/2174 r-*
* https://github.com/bioconda/bioconda-recipes/pull/2175 bioc

**Comment by johanneskoester** [comment]
Thanks @bgruening! I have reviewed the individual PRs.

**Comment by bgruening** [comment]
New r-* PR: https://github.com/bioconda/bioconda-recipes/pull/2191

**Comment by bgruening** [comment]
@johanneskoester  @daler I will be afk for one week. Please feel free to take this over.

**Pull request merged**
