### PR TITLE
mac recipe and added bioperl

### PR DESCRIPTION
**Pull request by mshakya**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by mshakya** [comment]
Hi @bgruening, just updated the bump (not bill) number to 1 for the main phame recipe. Thanks!

**Comment by mshakya** [comment]
Hi, can this be merged now?

**Comment by rvalieris** [comment]
why is there a separate recipe for mac ? can't the existing recipe build for both platforms ?

**Comment by mshakya** [comment]
I separated the recipe to mac and linux because there is no Hyphy (one the dependencies for the tool) recipe for mac in conda yet.

**Comment by rvalieris** [comment]
but it still works without it ?
in that case you can use a selector like this:
```
 - hyphy >=2.3.12 # [not osx]
```

**Comment by rvalieris** [comment]
also, are you the developer of this package ?
I noticed the version of the package on conda is different from the version on the git repo, please try to sync both versions if possible.

**Comment by mshakya** [comment]
I still works, but will not have all the functionality. Thanks for the tip about not using separate recipe. I am the developer and will make sure that the version number matches in my next push. Thanks again.

**Comment by mshakya** [comment]
I addressed all the issues above. I think this can be merged now. Thank you

**Pull request merged**
