### PR TITLE
Bwameth

### PR DESCRIPTION
**Pull request by dpryan79**
* [X] I have read the guidelines above.
* [X] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

@bioconda/core: Can I get a review please? This is bwameth from @brentp

### CODE REVIEW

**Comment by bgruening** [comment]
Super!

**Comment by brentp** [comment]
thanks Devon, you have version as 0.20 in yaml, should be 0.2.0

**Comment by dpryan79** [comment]
@brentp Crap, I've made that mistake everywhere :( I'll fix it up, thanks for catching the error.

**Comment by brentp** [comment]
I think I may have changed it underneath you when I tagged the release. So likely my mistake.

**Comment by dpryan79** [comment]
Either way, it's an easy fix :)

**Pull request merged**
