### PR TITLE
Update wfmash to 0.10.0

### PR DESCRIPTION
**Pull request by AndreaGuarracino**
This replaces #37667.

### CODE REVIEW

**Comment by AndreaGuarracino** [comment]
@BiocondaBot please add label

**Comment by AndreaGuarracino** [comment]
@johanneskoester, I ping you here because you were so in merging smoothxg's update :roll_eyes:

**Comment by dpryan79** [comment]
@BiocondaBot please fetch artifacts

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@BiocondaBot please merge

**Pull request merged**
