### PR TITLE
 add bioconductor-hpar recipe

### PR DESCRIPTION
**Pull request by sebastian-luna-valero**
* [X] I have read the guidelines above.
* [X] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

Please @bioconda/core review this new bioconductor recipe.

### CODE REVIEW

**Comment by bgruening** [comment]
Tests are failing :(

**Comment by sebastian-luna-valero** [comment]
This is strange:
https://travis-ci.org/bioconda/bioconda-recipes/jobs/129932676#L380

as the package can be downloaded. Do you know what's going on?

**Comment by sebastian-luna-valero** [comment]
I created the package with bioconductor_skeleton.py:
https://github.com/bioconda/bioconda-recipes/blob/master/scripts/bioconductor/README.md

The recipe is using http instead of https, could that be the problem?

**Comment by sebastian-luna-valero** [comment]
I must be missing something obvious here...

The recipe builds fine locally either inside and outside the bioconda container.

@bioconda/core do you know why does it fail here?
```
Downloading http://bioconductor.org/packages/release/bioc/src/contrib/hpar_1.14.0.tar.gz

Using Anaconda Cloud api site https://api.anaconda.org

Error: HTTPError: 404 Client Error: Not Found for url: http://bioconductor.org/packages/release/bioc/src/contrib/hpar_1.14.0.tar.gz: http://bioconductor.org/packages/release/bioc/src/contrib/hpar_1.14.0.tar.gz

Error: Could not download hpar_1.14.0.tar.gz
```

And the URL is valid:
http://bioconductor.org/packages/release/bioc/src/contrib/hpar_1.14.0.tar.gz

Many thanks,
Sebastian.

**Comment by daler** [comment]
Looks like they just recently put out 1.14.1 -- that 1.14.0 URL doesn't work for me now, and re-running bioconductor_skeleton.py builds a recipe for 1.14.1.

This is a really annoying aspect of the bioconductor URLs -- there's no archive! When possible we use bioaRchive, but the latest packages are not always available.

To fix this try re-running the skeleton (with `--force`) to update to 1.14.1.

**Comment by bgruening** [comment]
@daler actually I'm working on it to automatically put bioconda tarballs into bioaRchive. This way we do not need to rebuild the bioaRchive but still have all backups. Just need time ....

**Comment by daler** [comment]
Thanks @bgruening, that will be great!

**Comment by sebastian-luna-valero** [comment]
Seem to be ready to go now, thanks for your help!

**Comment by bgruening** [comment]
Nice! Thanks!

**Pull request merged**
