### PR TITLE
Update dxpy dependencies to be in line with requirements.txt

### LINKED ISSUE #36241: Does dxpy have too strict/wrong dependencies?
I was trying to install dxpy from bioconda and had problems combining it with other packages. The given reason was the cryptography dependency:

https://github.com/bioconda/bioconda-recipes/blame/master/recipes/dxpy/meta.yaml#L29
(version <=3.0.0
according to pipdeptree (and an older dxpy version) it is compatible with versions upto 37:

```bash
    - dxpy [required: >=0.313.0,<0.314.0, installed: 0.326.1]
      ....
      - cryptography [required: >=3.4.2,<37, installed: 36.0.2]
      ....
```

The requirement in the mamba file is completely off.

Tagging @notestaff as he is the recipe-maintainer

### PR DESCRIPTION
**Pull request by karl-az**
- Allow newer versions of pandas

Resolves #36241

This updates the dependencies of dxpy to be in line with what is given for the pip package

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by karl-az** [comment]
Had to add a small correction

**Comment by karl-az** [comment]
Added updates to the 10-some last recipes.

**Comment by dpryan79** [comment]
@bioconda-bot please fetch artifacts

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@BiocondaBot please merge

@karl-az I assume we don't need to keep the old recipes around after the packages are available. Otherwise please let me know.

**Comment by karl-az** [comment]
@dpryan79 no, they are just there to patch in changes to the more recent versions.

**Pull request merged**
