### PR TITLE
Update msmetaenhancer to 0.2.4

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`msmetaenhancer`](https://bioconda.github.io/recipes/msmetaenhancer/README.html): **0.2.3** &rarr; **0.2.4**

[install with bioconda](http://bioconda.github.io/recipes/msmetaenhancer/README.html) [Conda](https://anaconda.org/bioconda/msmetaenhancer/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/msmetaenhancer`](https://github.com//bioconda/bioconda-recipes/tree/bump/msmetaenhancer/recipes/msmetaenhancer) (click to view/edit other files)
Summary | MSMetaEnhancer is a Python tool that adds more annotations (e.g. SMILES, InChI, CAS number) to MSP files.
Home | [https://github.com/RECETOX/MSMetaEnhancer](https://github.com/RECETOX/MSMetaEnhancer)
Releases |[https://github.com/RECETOX/MSMetaEnhancer/tags](https://github.com/RECETOX/MSMetaEnhancer/tags)
Recipe Maintainer(s) | @xtrojak, @martenson
Author | `@RECETOX`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by xtrojak** [comment]
This is strange, updating dependencies in #36713 required to change build number to 0. Here the CI says the recipe build number should be incremented.

**Comment by bgruening** [comment]
@xtrojak if you bump the version number you need to reset the build number to 0. If you change the recipe, without bumping the version number, the build number needs to be increased. Please have a look at our documentation for more information.

**Comment by xtrojak** [comment]
@bgruening Yes, this is clear to me.
However, in this case, it is a little confusing for me because there will never exist version `0.2.4` build 0, only build 1, but it's just a detail.

**Comment by bgruening** [comment]
Ok, I'm a bit confused how can a 0.2.4 version exist on https://anaconda.org/bioconda/msmetaenhancer/files if you are just bumping that version here? Also the master branch only contains the 0.2.3 recipe.

This PR was just against the bot branch: https://github.com/bioconda/bioconda-recipes/pull/36713 
And it was never merged into master, afaik.

There is something wrong here, but you are correct, since the package is uploaded your build-number one makes sense.

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
Äh, what? Why bot have you done this.

**Comment by bgruening** [comment]
xref: https://github.com/bioconda/bioconda-recipes/pull/36808

**Comment by xtrojak** [comment]
@bgruening Seems like on anaconda it's okay now, although it is not clear to me how build version 0 got there. However [here](https://bioconda.github.io/recipes/msmetaenhancer/README.html), for version ´0.2.4´, it says build 0 is available but when you actually look in the recipe, there is build number 1.

**Pull request closed without merging**
