### PR TITLE
Stacks 2 0

### PR DESCRIPTION
**Pull request by pbordron**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by mbargull** [comment]
Does anyone (@bioconda/build-system, @bioconda/lib) know whether the old and new `libgcc` package are entirely interchangeable in terms of compatibility? With `{{ compiler("cxx") }}` `conda-build 3.x` adds a minimum requirement to that dependency:
```bash
$ cat >meta.yaml <<EOF
> package:
>   name: pkg
> requirements:
>   build:
>     - {{ compiler("cxx") }}
> EOF
$ conda render .
package:
    name: pkg
requirements:
    build:
        - libstdcxx-ng 7.2.0 h7a57d05_2
        - binutils_linux-64 7.2.0 25
        - gxx_linux-64 7.2.0 25
        - gcc_impl_linux-64 7.2.0 hc5ce805_2
        - gxx_impl_linux-64 7.2.0 hd3faf3d_2
        - binutils_impl_linux-64 2.28.1 h04c84fa_2
        - gcc_linux-64 7.2.0 25
    run:
        - libstdcxx-ng >=7.2.0
        - libgcc-ng >=7.2.0
extra:
    copy_test_source_files: true
    final: true
```
A `libgcc` run requirement (if not otherwise version constraint) would install the new ones anyways:
```bash
$ conda search --info 'libgcc >=7.2.0'
Loading channels: done
libgcc 7.2.0 h69d50b8_2
-----------------------
file name   : libgcc-7.2.0-h69d50b8_2.tar.bz2
name        : libgcc
version     : 7.2.0
build string: h69d50b8_2
build number: 2
size        : 304 KB
constrains  : ()
license     : GNU GPL 3+ with GCC Runtime Library
subdir      : linux-64
url         : https://repo.continuum.io/pkgs/main/linux-64/libgcc-7.2.0-h69d50b8_2.tar.bz2
md5         : 9962126180acc1a4fec0c6aabe7c2459
dependencies: 
  - libgcc-ng >=7.2.0
  - libstdcxx-ng >=7.2.0
```

**Comment by mbargull** [comment]
Ah, thoughts got carried away by the question above. What I originally meant to ask was whether we should (or rather not) add `htslib ==1.3.1` to the build requirements and patch configure/makefile to use that one? That could be done easily but that `libhts.a` would of course been compiled by an older compiler -- so I'm unsure about compatibility.
If no one can confirm that it'd be fine to use an external `htslib`, then this can be merged as is.

**Comment by pbordron** [comment]
@mbargull I get some `ld` errors if I do not patch the included htslib makefile when compiling with conda-build.
```
ld: ./htslib/libhts.a(knetfile.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
ld: final link failed: Nonrepresentable section on output
```
However I do not have this error if I compile stacks 2.0 directly on my system where htslib is compiled with gcc-5.4.0 and stacks with g++-7.1.0. When using conda-build, gcc standard compiler in it is also gcc-5.4.0.

I have open an issue in stacks-user mailing list
https://groups.google.com/d/msg/stacks-users/tcUddMdRuXk/7t5m0BAhBAAJ

**Comment by mbargull** [comment]
I think let's stick to letting Stacks vendor its HTSlib for now and come back to this at some later point.

**Pull request merged**
