### PR TITLE
Add metamorpheus

### PR DESCRIPTION
**Pull request by acesnik**
This pull request aims to add [MetaMorpheus](https://github.com/smith-chem-wisc/MetaMorpheus), software for searching mass spectrometry proteomic data, into `bioconda`. 

MetaMorpheus uses `dotnet` to run on the commandline. 

In this PR, one goal is to have `metamorpheus [options]` run the program, which is usually run by `dotnet CMD.dll [options]`.

----

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by acesnik** [comment]
@ypriverol Do you have any thoughts on this? I'm not sure how to get it to build, and it looks like there's a dependency conflict between `dotnet` and the linux-64 system. :)

**Comment by ypriverol** [comment]
> @ypriverol Do you have any thoughts on this? I'm not sure how to get it to build, and it looks like there's a dependency conflict between `dotnet` and the linux-64 system. :)

I will check with @bgruening

**Comment by bgruening** [comment]
@acesnik yes this is the main problem that we are facing. .net was compiled against a more recent glib version. But we need to compile it against an older glib version since we want to support HPC systems that run those older glib versions.

We put a lot of effort into compiling mono against those supported glib versions. So one way around would be to get metamorpheus working with mono?

**Comment by acesnik** [comment]
Okay, thanks for clarifying. I believe using `mono` would sacrifice performance, but that's a good temporary option.

We may also be interested in allowing users to download this on Windows machines using `conda`, so I'm thinking maybe I should make a similar PR to conda-forge instead. The glib version mismatch likely wouldn't be a problem there, since `dotnet` is housed there. Does that sound like a reasonable thing to do?

Thanks for the time, you two!

**Comment by acesnik** [comment]
Closing this PR in favor of https://github.com/conda-forge/staged-recipes/pull/14252 using `dotnet`.

**Pull request closed without merging**
