### PR TITLE
Add 'DCMAKE_BUILD_TYPE=Release' to octopus cmake options

### PR DESCRIPTION
**Pull request by dancooke**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

Explicitly build octopus in release mode. Without specifying the build, CMake defaults to a debug build. In addition to dramatically improving performance, this will also resolve an [issue](https://github.com/luntergroup/octopus/issues/25) with the debug build.

### CODE REVIEW

**Comment by dancooke** [comment]
@chapmanb Please could you merge this? I'll make `Release` default  in the next octopus version (a few weeks away).

**Comment by chapmanb** [comment]
Thanks so much for the fix here and sorry about having an incorrect build. Much appreciated.

**Comment by colindaven** [comment]
Will this fix the following issue I'm having on Ubuntu 16.04, or is that another issue?
`octopus: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by octopus)
octopus: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by octopus)
`

**Comment by chapmanb** [comment]
Colin;
This seems like you don't have a recent enough libgcc installed in your conda environment. octopus should require this so not sure how it got off but you could do:
```
conda list | grep libgcc
```
to see what you have and:
```
conda install -c conda-forge libgcc
```
to get an updated version like 7.2.0 that should avoid the issue.

**Pull request merged**
