### PR TITLE
Frubino - remove from blacklist

### PR DESCRIPTION
**Pull request by frubino**
* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [X] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [X] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

Removes the mgkit package from the blacklist

### CODE REVIEW

**Comment by frubino** [comment]
@johanneskoester to be honest, I don't understand why the requirement is failing... I added matplotlib to the build requirements as well and it seems too fail. Any idea?

**Comment by frubino** [comment]
I imagine the problem is due to the import of pyplot in one of the modules, one of those that are irrelevant at the moment.

**Comment by frubino** [comment]
Can you try and merge it, now?

**Comment by frubino** [comment]
@bgruening, the reason the exception is raised is most likely the import of `pyplot`. In some cases, like virtual environments, the import gets a backend that is not correct. It's the case I have when building documentation and autodoc in sphinx has problem with that.

Right now I'm changing references to pyplot, but these are changer along more substantial ones in the package (I'm the developer). I'd prefer to get accustomed with the process here and let a user use the command line tools (which don't use any plot function) for now.

**Comment by bgruening** [comment]
Thanks @frubino!

**Pull request merged**
