### PR TITLE
Topic/cutadapt pigz

### PR DESCRIPTION
**Pull request by bernt-matthias**
cutadapt: remove pigz run requirement

currently cutadapt calls pigz (via xopen) without limiting the number of used CPUs (https://github.com/marcelm/cutadapt/issues/290). hence pigz uses the default = all CPUs which is not acceptable on shared compute ressources.

if pigz is not installed single threaded python libraries are used.

alternatively (would be better) a new xopen version should be used once it is available https://github.com/marcelm/xopen/pull/20

Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it. Note that if you are not already a member of the bioconda project (meaning that you can't add this label), please ping `@bioconda/core` so that your PR can be reviewed and merged (please note if you'd like to be added to the bioconda project). Please see https://github.com/bioconda/bioconda-recipes/issues/15332 for more details.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by dpryan79** [comment]
Wow, yeah, that's definitely a problem. Are you hitting this on Galaxy or something where you can't easily just remove pigz from the conda env? If so, I'm happy to just merge this to get things working properly until xopen is tweaked.

**Comment by bernt-matthias** [comment]
Jep. Galaxy. Will remove pigz from all conda envs I guess.

Seems that new xopen and cutadapt releases are in sight. So let's wait with merging

**Comment by dpryan79** [comment]
OK, sounds like a game plan then. I'll reject my PR approval so this doesn't accidentally get merged then. Just ping me if it looks like the changes elsewhere are taking to long and we can just merge this in.

**Comment by dpryan79** [comment]
It looks like there's a new xopen out, I'll update the cutadapt recipe to require it.

**Comment by rhpvorderman** [comment]
This is really a problem of cutadapt and not of pigz.
`pigz` is by far a better implementation of the deflate compression algorithm than `gzip`. It compresses and decompresses faster even when limited to only one thread. 

Delegating the decompression and compression throught a separate pigz process creates more room for the python interpreter to do its actual job (cutadapt) instead of using the python gzip library to compress and decompress threads. This causes a tremendous speedup.

As far as the amount of threads go, that should be solved in cutadapt. But removing pigz from the cutadapt recipe is in my opinion  shooting ourselves in the foot. This will mean that pigz is removed from the biocontainer and that the fastest deflate implementation will simply not be available for users of that container.

**Comment by dpryan79** [comment]
@rhpvorderman I just noticed that you commented on the xopen issue. Am I correct in understanding that updating xopen will not in fact resolve the issue that @bernt-matthias is running into?

**Comment by rhpvorderman** [comment]
Nope. I am working on a fix in cutadapt as we speak.

**Comment by bernt-matthias** [comment]
@dpryan79 @rhpvorderman you are 100% right. its an xopen + cutadapt issue. 

the xopen issue is now already solved: https://github.com/marcelm/xopen/pull/20 and a new release available

unfortunately cutadapt does not pass threads argument to xopen. @rhpvorderman my PR is nearly done ..

**Comment by bernt-matthias** [comment]
https://github.com/marcelm/cutadapt/pull/411

**Comment by dpryan79** [comment]
Thanks to both of you, I'll close #18171 then.

**Comment by rhpvorderman** [comment]
I feel strongly about this. Consider the following benchmark: unzipping a fastq file that has been compressed with gzip. Compression level = 1. Resulting file size: 2.3 gb. 

We are going to decompress this file. We do 3 warmup runs to make sure the file is cached (for fair comparison) and then 10 runs to take the average.

command | wall clock time (average) | total cpu time (average) | comment
---|---|---|---
`pigz -cd very_big.fastq.gz > /dev/null` | 24.4 seconds | 32.7 seconds | Uses more seconds total cpu time because threads cause overhead.
`pigz -cd -p 1 very_big.fastq.gz > /dev/null` | 27.4 seconds | 27.4 seconds | Forces pigz to use ony one thread. As you can see, the cpu overhead for more threads is quite substantial.
`gzip -cd very_big.fastq.gz > /dev/null` | 44.2 seconds| 44.2 seconds | gzip sucks!

**Comment by dpryan79** [comment]
> I feel strongly about this.

I agree. Since changes to cutadapt seem to be moving along quickly I think we can wait for them.

**Comment by bernt-matthias** [comment]
Sure. Lets wait.

My temporary solution for out cutadapt conda envs will be to `conda remove --force pigz`.

Still load might be > 1 since independent threads/processes are used for reading, processing and writing. I guess for the Galaxy wrapper we will need some kind of formula to compute the number of additional threads, i.e. the value of `--cores ` given the number of available cores. I guess for using gzip 

I guess --cores should be `no_available_cpus - no_input_files + no_output_files` (which also means that one needs to request at least 5 cores for processing paired end data).

I think this should also work for the default values suggested in https://github.com/marcelm/cutadapt/pull/412

**Comment by dpryan79** [comment]
Galaxy has supported compressed fastq files natively for a few years now :)

**Comment by rhpvorderman** [comment]
Sorry, my bad! In that case the `-Z` flag will force cutadapt to use a compression level of 1. It will use much less CPU power. Since these files are intermediate anyway and not stored for long periods of time there is no utility for compressing them to very small sizes.

**Comment by marcelm** [comment]
I’m closing this stale PR now. [Since version 2.7, Cutadapt no longer uses pigz for writing gzip files when it’s running single-threaded](https://cutadapt.readthedocs.io/en/latest/changes.html#v2-7-2019-11-22).

Apart from that, the `pigz` dependency should actually be removed from the cutadapt recipe because the `xopen` library already depends on it. I’ll do that when releasing the next version. Please report further problems at marcelm/cutadapt#290 .

**Pull request closed without merging**
