### PR TITLE
fix: freebayes

### PR DESCRIPTION
**Pull request by kilpert**
Fix freebayes-prarallel because of bug in vcflib=1.0.9 (https://github.com/vcflib/vcflib/issues/389).
Also, htslib=1.17 does not work with freebayes-parallel.

### CODE REVIEW

**Comment by bgruening** [comment]
I think vcflib should be fixed. There is an underlying issue which we need to understand, isn't it?

**Comment by johanneskoester** [comment]
I agree, but maybe this here can be done as a temporary workaround, such that freebayes at least works for the people for now. It is a widely used package. If you agree @bguening, this PR should however, definitely also point to the vcflib issue URL in the code of the meta.yaml, not only the PR message. And probably it should also add a back reference to that issue in the vcflib meta.yaml.

**Comment by johanneskoester** [comment]
@kilpert what is the issue with htslib though? What error message appears when only vcflib is pinned?

**Comment by bgruening** [comment]
The linked issue above is from 12.6, so everyone is thinking they do a temporary workaround :)
We are releasing here a new package with changes, that we need to revert once the vcflib is fixed. So more work ;) but feel free to merge. Its not a -1, more a -0 ;)

**Comment by johanneskoester** [comment]
I completely agree with you. If I could name somebody to fix the origin of the issue, I would do it. But I don't know anybody who currently has the capacity (including myself) :-(.

**Comment by johanneskoester** [comment]
Maybe @mencian as the author of the changes that seemingly introduce the issue in 1.0.9 would like to have a look?

**Comment by johanneskoester** [comment]
cross post: https://github.com/bioconda/bioconda-recipes/commit/032977aed9bcf6941284034e443b234e36af62e5

**Comment by johanneskoester** [comment]
The htslib issue actually originates from tabixpp not being pinned in vcflib as a dependency. Fixing that now by adding a run_export to tabixpp.
```
freebayes-parallel test.idk 1 -f resources/genome.dna.homo_sapiens.GRCh37.105.fasta results/recal/pF40.bam
vcfuniq: error while loading shared libraries: libtabixpp.so.0: cannot open shared object file: No such file or directory
vcfstreamsort: error while loading shared libraries: libtabixpp.so.0: cannot open shared object file: No such file or directory
```

**Comment by johanneskoester** [comment]
That one is now fixed in PR https://github.com/bioconda/bioconda-recipes/pull/42667

**Comment by johanneskoester** [comment]
Maybe this change is the issue: 

now:
```
cmake -S . -B build \
	-DZIG=ON -DOPENMP=ON -DWFA_GITMODULE=OFF \
	-DCMAKE_BUILD_TYPE=Release \
	-DBUILD_SHARED_LIBS=ON \
	-DCMAKE_INSTALL_PREFIX="${PREFIX}" \
	-DCMAKE_CXX_COMPILER="${CXX}" \
	-DCMAKE_CXX_FLAGS="${CXXFLAGS}" \
	-DCMAKE_C_COMPILER="${CC}" \
	-DCMAKE_INCLUDE_PATH="${PREFIX}/include" \
	-DCMAKE_LIBRARY_PATH="${PREFIX}/lib"
```

before:
```
cmake --build build/ --target install -j 4 -v

#cmake .. -DCMAKE_INSTALL_PREFIX=$PREFIX -DTABIXPP_LOCAL:STRING=$PREFIX/lib
cmake .. -DCMAKE_INSTALL_PREFIX=$PREFIX 
cmake --build . 
cmake --install .
```

The disabling of WFA seems suspicious to me. I think this causes the symbol to be missing.

**Comment by johanneskoester** [comment]
Ok, I think we are close enough to get this done without merging this PR. If anybody could try to make a separate PR that tries to activate WFA building in vcflib again, that would be awesome. I have to prepare a talk now.

**Comment by johanneskoester** [comment]
Related: https://github.com/bioconda/bioconda-recipes/pull/42671

**Comment by johanneskoester** [comment]
And here we can work on the fix. Hopefully my test new case will show whether the problem remains.
https://github.com/bioconda/bioconda-recipes/pull/42673

**Comment by johanneskoester** [comment]
> And here we can work on the fix. Hopefully my test new case will show whether the problem remains. #42673

It does show it. Great, that will make things easier. Contributions welcome!

**Comment by johanneskoester** [comment]
Seems tha vcflib forgets to link vcfstreamsort against libwfa. I have a fix in the PR and also upstream. Hopefully the fix will solve the issue. Luckily, we will immediately see that in the test case I added to the recipe.

**Comment by johanneskoester** [comment]
@bgruening thanks for forcing me to solve this properly ;-)

**Comment by johanneskoester** [comment]
Fixes are merged. Let us rebuild to get the updated run_exports.

**Review by johanneskoester — APPROVED** [review]

**Pull request merged**
