### PR TITLE
R minionqc recipe

### PR DESCRIPTION
**Pull request by kpalin**
:information_source:
If this is your first pull request to Bioconda please ping `@bioconda/core` so it can be reviewed and to request being added as a member of the Bioconda team. Members of the Bioconda team are able to merge their own pull requests once tests and linting have passed.

----------------

* [x ] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ x] This PR adds a new recipe.
* [ x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by dpryan79** [comment]
We're trying to encourage people to submit pure R packages that don't depend on bioconductor to conda-forge as much as possible. Since all of the dependencies are in conda-forge, could you submit this there?

**Comment by epruesse** [comment]
@dpryan79 - As agreed, making an exception here.

**Comment by dpryan79** [comment]
:+1: Sounds good, it really is a great fit here.

**Comment by epruesse** [comment]
@biocondabot recheck

**Comment by epruesse** [comment]
@biocondabot merge

**Comment by epruesse** [comment]
@BiocondaBot merge

**Comment by epruesse** [comment]
@biocondabot merge

**Pull request merged**
