### PR TITLE
Use quotes when extending PATH.

### PR DESCRIPTION
**Pull request by pkrog**
* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [ ] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [X] This PR does something else (explain below).

Correct PATH definition, when extending it for miniconda.
When extending PATH env var, use quotes in order to handle potential space characters in PATH.

### CODE REVIEW

**Comment by bgruening** [comment]
You need to increase the build number.

**Comment by pkrog** [comment]
Which build number ? This PR does not modify any recipe.
It just fixes an issue in the `setup.sh` script.
Do you mean the checks were not run and I need to force a run ?

**Comment by bgruening** [comment]
Yes, we only build recipes if the version+build number changes. So you need to increase the build/number by one.

**Comment by epruesse** [comment]
What brought this up? Did someone actually use spaces in the path?

**Comment by epruesse** [comment]
(I mean, sure, do that. Might even work with most Linux Desktop software these days. But with bioinf software? I'm guessing at least half of everything that includes a shell script will break. Probably more.)

**Comment by pkrog** [comment]
Yes, I actually have a space in my `PATH` env var, due to some application. Anyway, since space is allowed in file names, it must be handled.

**Pull request merged**
