### PR TITLE
Fix phylotoast

### PR DESCRIPTION
**Pull request by johanneskoester**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by johanneskoester** [comment]
xref: #9404

**Comment by johanneskoester** [comment]
We need to get scikit-bio fixed first, see https://github.com/conda-forge/scikit-bio-feedstock/pull/6.

**Comment by johanneskoester** [comment]
scikit-bio on bioconda needs to be moved to bioconda-legacy, or alternatively scikit-bio needs to be removed from conda-forge. What do you prefer, @ebolyen.

**Comment by johanneskoester** [comment]
Also feel free to discuss this with @bgruening in person since I will soon have to travel home unfortunately.

**Comment by ebolyen** [comment]
@johanneskoester, I think scikit-bio makes sense in conda-forge as it lives in the "scipy" ecosystem, but I'm probably not the one to ask nowadays. Pinging @mortonjt, @wasade, and @RNAer.

I'll coordinate with @bgruening soon.

**Comment by mortonjt** [comment]
Agree with @ebolyen , I think it makes more sense to have skbio on conda-forge

**Comment by johanneskoester** [comment]
As you wish.

**Comment by daler** [comment]
Closing due to inactivity, please re-open if needed.

**Pull request closed without merging**
