### PR TITLE
Update metaSNV to 2.0.0

### PR DESCRIPTION
**Pull request by unode**
metaSNV 2.0.0 is now available updating from 1.0.3

Tagging the dev team: @theavanrossum @LucasPaoli and the initial bioconda recipe maintainer @AlessioMilanese

### CODE REVIEW

**Comment by unode** [comment]
@BiocondaBot please add label

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
LGTM, have the bot merge whenever you like

**Comment by unode** [comment]
Thanks Devon!

@BiocondaBot please merge

**Comment by unode** [comment]
@BiocondaBot please merge

**Pull request merged**
