### PR TITLE
add beaconlab_pscan

### PR DESCRIPTION
**Pull request by MathiasHaudgaard**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by bgruening** [comment]
Hi!

There is an error hidden behind `[Sep 12 11:06:52] STEP Run image [quay.io/biocontainers/pscan:1.5--h266ad14_0] with command [[pscan -h 2>&1 | grep SYNOPSIS]]`. What happens if we remove the grep. Do we then see the error?

**Comment by MathiasHaudgaard** [comment]
@bgruening if you look in circleci for commit 0af5ec6 i tried without grep. I think it has something to do with it can't find the libraries that's required. But i'm not sure

**Comment by bgruening** [comment]
@MathiasHaudgaard try to build it locally and conserve the container. There is a real error message hidden. Some missing deps in the container.

**Comment by daler** [comment]
Closing due to inactivity, please re-open if needed.

**Pull request closed without merging**
