### PR TITLE
put back gdsctools

### PR DESCRIPTION
**Pull request by cokelaer**
* [x] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by cokelaer** [comment]
@bioconda/core 

Following https://github.com/bioconda/bioconda-recipes/issues/4056, I'm trying to put back gdsctools into the built system. I have a recurrent issue and I hope you can help or redirect to someone who may know. Here is the issue. I have a dependencies on xlrd, which I ported to conda-forge last week. https://anaconda.org/conda-forge/xlrd/files and is visible on my system when calling **conda search xlrd**.

Yet, when I do a **conda build recipes/gdsctools** locally on the bioconda travis CI, I get an error
```
RuntimeError: Setuptools downloading is disabled in conda build. Be sure to add all dependencies in the meta.yaml  url=https://pypi.python.org/simple/xlrd/r
Traceback (most recent call last):
  File "/home/cokelaer/anaconda2/bin/conda-build", line 6, in <module>
    sys.exit(conda_build.cli.main_build.main())
```
as if bioconda build searches for the package on the r channel only. 
If I remove xlrd from the PYthon setup (with a patch), then another dependencies (not on conda-forge but bioconda) will appear as well, again telling that the dependencies is not found. 

Would you have any clues, that would be super useful. Thank you in advance

**Comment by daler** [comment]
@cokelaer can't see anything obvious, but it does look like there was already `xlrd` 1.0.0 in defaults which will take priority anyway.

**Comment by daler** [comment]
Ah, right: @cokelaer try copying dependencies to `requirements: build` as well.

**Comment by bgruening** [comment]
Lets restart the build.

**Comment by cokelaer** [comment]
will restart from scratch at a later stage

**Pull request closed without merging**
