### PR TITLE
MentaLiST: Backport libxml2 fix to v0.1.x series

### PR DESCRIPTION
**Pull request by dfornika**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by dfornika** [comment]
Fixes MentaLiST issues [14](https://github.com/WGS-TB/MentaLiST/issues/14) and [15](https://github.com/WGS-TB/MentaLiST/issues/15) (for v0.1.3)

**Comment by cbrueffer** [comment]
Do I understand it correctly that the 0.1.3 package is missing the libxml2 dependency?

Instead of moving the version backwards, I think the better way here is to add a "0.1.3" subdirectory containing the 0.1.3 recipe. You'll also need to bump the build number for the 0.1.3 package.

**Comment by dfornika** [comment]
Yes, that's correct. Thanks, I'll follow your advice.

**Comment by dfornika** [comment]
The build process is failing with the following error message:

```
ERROR: Cannot clone Compat from https://github.com/JuliaLang/Compat.jl.git. The SSL certificate is invalid
```

**Comment by dfornika** [comment]
Is there a reason that the build bot wouldn't be able to access GitHub over `https`?

I think this is out of my control. Could someone trigger a re-build please?

**Comment by dfornika** [comment]
@cbrueffer @johanneskoester This build has failed because the build bot couldn't reach github over `https`. Is that a known problem, or could it be a one-off error? Can we trigger a re-build?

**Comment by mbargull** [comment]
@dfornika, done.
For the record, the error was `The SSL certificate is invalid`:
```
+ julia -e 'Pkg.add("Suppressor")'
INFO: Cloning cache of Compat from https://github.com/JuliaLang/Compat.jl.git
ERROR: Cannot clone Compat from https://github.com/JuliaLang/Compat.jl.git. The SSL certificate is invalid
 in prefetch(::String, ::String, ::Array{String,1}) at ./pkg/cache.jl:56
 in resolve(::Dict{String,Base.Pkg.Types.VersionSet}, ::Dict{String,Dict{VersionNumber,Base.Pkg.Types.Available}}, ::Dict{String,Tuple{VersionNumber,Bool}}, ::Dict{String,Base.Pkg.Types.Fixed}, ::Dict{String,VersionNumber}, ::Set{String}) at ./pkg/entry.jl:511
 in edit(::Function, ::String, ::Base.Pkg.Types.VersionSet, ::Vararg{Base.Pkg.Types.VersionSet,N}) at ./pkg/entry.jl:30
 in (::Base.Pkg.Entry.##2#5{String,Base.Pkg.Types.VersionSet})() at ./task.jl:360
 in sync_end() at ./task.jl:311
 in macro expansion at ./task.jl:327 [inlined]
 in add(::String, ::Base.Pkg.Types.VersionSet) at ./pkg/entry.jl:51
 in (::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#add,Tuple{String}})() at ./pkg/dir.jl:31
 in cd(::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#add,Tuple{String}}, ::String) at ./file.jl:59
 in #cd#1(::Array{Any,1}, ::Function, ::Function, ::String, ::Vararg{Any,N}) at ./pkg/dir.jl:31
 in add(::String) at ./pkg/pkg.jl:100
 in eval(::Module, ::Any) at ./boot.jl:234
 in process_options(::Base.JLOptions) at ./client.jl:242
 in _start() at ./client.jl:321
```
strange...

**Comment by dfornika** [comment]
@mbargull It is strange. Do you know if any other recipes are having similar problems? We were able to build this package on TravisCI. It started failing after the move to CircleCI.

**Comment by mbargull** [comment]
We have some other recipes that have problems after the Travis CI -> CircleCI switch, but those aren't Julia packages and hence show other failures. I did a quick search, and maybe the failure is related to https://github.com/JuliaLang/julia/issues/13399#issuecomment-181739388?
So overall, maybe fixing https://github.com/bioconda/bioconda-utils/issues/260 could take care of it..

**Pull request closed without merging**
