### PR TITLE
add r-ade4

### PR DESCRIPTION
**Pull request by nick-youngblut**
* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [X] This PR adds a new recipe.
* [X] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by daler** [comment]
@nick-youngblut this one should have gone into conda-forge I believe since it's not bio-specific.

In fact, now that I check it's already in conda-forge . . . the linting should have caught this I think.

**Comment by nick-youngblut** [comment]
Sorry about that! I just saw that it was a dependency for another package that wasn't available on bioconda, so I added it. I should have checked conda-forge. Can I remove ade4?

**Comment by daler** [comment]
I will remove the `main` tag from channel (admin has to do that); would you submit a PR that removes the recipe? Thanks.

**Comment by nick-youngblut** [comment]
OK. I'll do that right now. Just as an FYI, the `r-adephylo` recipe will be broken once r-ade4 is removed. I see that conda-forge is lacking the `r-ade4` 1.7_10, which `r-adephylo` recipe lists as a dependency. I'll try to update r-ade4 on conda-forge ASAP. Sorry again for making this an issue

**Pull request merged**
