### PR TITLE
Correct pb-falcon

### PR DESCRIPTION
**Pull request by dpryan79**
:information_source:
If this is your first pull request to Bioconda please ping `@bioconda/core` so it can be reviewed and to request being added as a member of the Bioconda team. Members of the Bioconda team are able to merge their own pull requests once tests and linting have passed.

----------------

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by dpryan79** [comment]
Xref: #15000

**Comment by pb-cdunn** [comment]
Thanks. I wish I knew what changed in Bioconda to make this work. I had tried this and other variations (on a very recent `master`) last week.

... Ah, I spoke too soon. Similar to a failure I saw last week.

```
WARNING:conda_build.build:failed to get install actions, retrying.  exception was: Unsatisfiable dependencies for platform linux-64: {'pb-falcon==0.3.0=py37hc0aa232_0'}
```
How does one debug this? Can we view Conda's opinion of dependency-resolution somehow?

Note: Despite passing both #15000 and #15043, pb-falcon 0.3.0 never showed up at https://conda.anaconda.org/bioconda/linux-64

**Comment by dpryan79** [comment]
python-edlib needs to be rebuilt for python 3.7 in order of this to work on python 3.7

**Comment by pb-cdunn** [comment]
Ok. I've fixed and merged python-edlib-1.2.3. But how did you know that was the problem? I want to learn how to diagnose.

**Comment by pb-cdunn** [comment]
```
python-edlib >= 1.2.4
```
won't parse, but
```
python-edlib>=1.2.4
```
is fine. I've seen this before. I think the version-constraint parser has a problem when the package-name contains a hyphen.

Anyway, that's [in Anaconda now](https://anaconda.org/bioconda/python-edlib), so let's see what happens ...

**Comment by pb-cdunn** [comment]
Still failing. What's the problem now?

**Comment by pb-cdunn** [comment]
It worked for me locally:
```
% bioconda-utils build --loglevel=DEBUG --force --packages pb-falcon -- recipes config.yml
...
12:55:34 BIOCONDA DEBUG command: ['/scratch/cdunn/miniconda/miniconda/bin/conda', 'build', '--no-anaconda-upload', '--channel', 'conda-forge', '--channel', 'bioconda', '--channel', 'defaults', '-e', '/scratch/cdunn/miniconda/miniconda/conda_build_config.yaml', '-m', '/scratch/cdunn/miniconda/miniconda/lib/python3.6/site-packages/bioconda_utils/bioconda_utils-conda_build_config.yaml', 'recipes/pb-falcon/meta.yaml']
..
12:57:41 BIOCONDA INFO BUILD SUCCESS pb-falcon-0.3.0-py36hc0aa232_0.tar.bz2
12:57:42 BIOCONDA INFO BUILD SUMMARY: successfully built 1 of 1 recipes
```

**Comment by dpryan79** [comment]
It failed when running a test, which meant a run-time dependency was missing. It was just a matter of looking for which one it could be. I wish there had been a relevant error message though.

**Comment by pb-cdunn** [comment]
I have found a way to find *some* problems. I create a py37 environment and gradually install one thing at a time. That takes a looooooong time, but I discovered that I also had to fix **python-msgpack**.

Now I am trying to add py37 support to pb-assembly: #15099

**Pull request merged**
