### PR TITLE
Update involucro

### PR DESCRIPTION
**Pull request by Yikun**
Make involucro work with go 1.18

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by Yikun** [comment]
```
03:35:42 BIOCONDA INFO (OUT) source tree in: /opt/conda/conda-bld/involucro_1680147204439/work
03:35:42 BIOCONDA INFO (OUT) export PREFIX=/opt/conda/conda-bld/involucro_1680147204439/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla
03:35:42 BIOCONDA INFO (OUT) export BUILD_PREFIX=/opt/conda/conda-bld/involucro_1680147204439/_build_env
03:35:42 BIOCONDA INFO (OUT) export SRC_DIR=/opt/conda/conda-bld/involucro_1680147204439/work
03:35:44 BIOCONDA INFO (OUT) go: go.mod file not found in current directory or any parent directory.
03:35:44 BIOCONDA INFO (OUT) 	'go get' is no longer supported outside a module.
03:35:44 BIOCONDA INFO (OUT) 	To build and install a command, use 'go install' with a version,
03:35:44 BIOCONDA INFO (OUT) 	like 'go install example.com/cmd@latest'
03:35:44 BIOCONDA INFO (OUT) 	For more information, see https://golang.org/doc/go-get-install-deprecation
03:35:44 BIOCONDA INFO (OUT) 	or run 'go help get' or 'go help install'.
03:35:45 BIOCONDA INFO (OUT) Traceback (most recent call last):
03:35:45 BIOCONDA INFO (OUT)   File "/opt/conda/bin/conda-mambabuild", line 10, in <module>
03:35:45 BIOCONDA INFO (OUT)     sys.exit(main())
03:35:45 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.7/site-packages/boa/cli/mambabuild.py", line 239, in main
03:35:45 BIOCONDA INFO (OUT)     call_conda_build(action, config)
03:35:45 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.7/site-packages/boa/cli/mambabuild.py", line 218, in call_conda_build
03:35:45 BIOCONDA INFO (OUT)     **kwargs,
03:35:45 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.7/site-packages/conda_build/api.py", line 195, in build
03:35:45 BIOCONDA INFO (OUT)     variants=variants
03:35:45 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.7/site-packages/conda_build/build.py", line 3093, in build_tree
03:35:45 BIOCONDA INFO (OUT)     notest=notest,
03:35:45 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.7/site-packages/conda_build/build.py", line 2212, in build
03:35:45 BIOCONDA INFO (OUT)     cwd=src_dir, stats=build_stats)
03:35:45 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.7/site-packages/conda_build/utils.py", line 410, in check_call_env
03:35:45 BIOCONDA INFO (OUT)     return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
03:35:45 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.7/site-packages/conda_build/utils.py", line 390, in _func_defaulting_env_to_os_environ
03:35:45 BIOCONDA INFO (OUT)     raise subprocess.CalledProcessError(proc.returncode, _args)
03:35:45 BIOCONDA INFO (OUT) subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/opt/conda/conda-bld/involucro_1680147204439/work/conda_build.sh']' returned non-zero exit status 1.
03:35:52 BIOCONDA ERROR COMMAND FAILED (exited with 1): docker run -t --net host --rm -v /tmp/tmpdhu01k4p/build_script.bash:/opt/build_script.bash -v /opt/miniconda/envs/bioconda/conda-bld/:/opt/host-conda-bld -v /home/vsts/work/1/s/recipes/involucro:/opt/recipe -e LANG=C.UTF-8 -e HOST_USER_ID=1001 quay.io/bioconda/bioconda-utils-build-env-cos7:1.5.7 /bin/bash /opt/build_script.bash

03:35:52 BIOCONDA ERROR BUILD FAILED recipes/involucro
03:35:52 BIOCONDA INFO (COMMAND) conda build purge
03:35:53 BIOCONDA ERROR BUILD SUMMARY: of 1 recipes, 1 failed and 0 were skipped. Details of recipes and environments follow.
03:35:53 BIOCONDA ERROR BUILD SUMMARY: FAILED recipe recipes/involucro
```

Reproduce the https://github.com/bioconda/bioconda-recipes/issues/40063

**Comment by Yikun** [comment]
I noticed that there were some discussion when introduced the `gather_licenses`: https://github.com/bioconda/bioconda-recipes/pull/25669#discussion_r536657812 , so would you mind give some idea about how to address go deps license with 
 go 1.18+? @mbargull

**Comment by Yikun** [comment]
I think new style license collection work as expected. So it's ready to review now.

**Comment by bgruening** [comment]
@BiocondaBot please fetch artifacts

**Comment by bgruening** [comment]
@Yikun can you please test those artifacts?

**Review by bgruening — APPROVED** [review]
Awesome! Thanks!

**Comment by Yikun** [comment]
@bgruening Hi, as you might noticed that this is a package which bioconda-utils depends on. Due to circular dependency, we have to support `involucro` aarch64 first and to support user `pip install` the biconda-utils . So there are two potential solution:

Solution A: Move this package to conda-forge, just like https://github.com/conda-forge/skopeo-feedstock/pull/34 we can easy to suport Linux aarch64, and then bump the version in bioconda-utils's requirement.txt.

Solution B: We can upload a linux aarch64 package in bioconda channel manually.

Otherwise we have to install `bioconda-utils` (`python setup.py install` or `pip install -e .`) and install involucro locally like [this](https://github.com/bioconda/bioconda-utils/pull/866/files#diff-671cd03f0df8aa9eeb4ab60ebd313d338d1f361e77023e911791f2d1bae67c44R47-R60).

**Comment by bgruening** [comment]
I'm all in favour to move it to conda-forge. Happy to be a maintainer of this recipe.

**Comment by Yikun** [comment]
https://github.com/conda-forge/staged-recipes/pull/22518

**Pull request merged**
