### PR TITLE
Add wrassp package for speech signal processing

### PR DESCRIPTION
**Pull request by stevecassidy**
- [x] I have read the guidelines above.
- [x] This PR adds a new recipe.
- [ ] This PR updates an existing recipe.
- [ ] This PR does something else (explain below).

@bgruening fingers crossed

### CODE REVIEW

**Comment by bgruening** [comment]
@johanneskoester this one is working with a pinned older GCC version: https://travis-ci.org/bioconda/bioconda-recipes/jobs/154373132#L1998 The failure is due to other R packages that gets build. So we need to fix these R packages or put them on the blacklist.

**Comment by bgruening** [comment]
The unpinned version fails with: https://travis-ci.org/bioconda/bioconda-recipes/jobs/154373132#L1998

**Comment by bgruening** [comment]
@stevecassidy we are working on a fix. Do you have some more days to wait for us? :)

**Comment by stevecassidy** [comment]
@bgruening @johanneskoester thanks for your help.  I'm still not convinced it's the gcc version that is at fault, but at least this gives a working build.

**Comment by johanneskoester** [comment]
At least, it is an incompatibility between the gcc build and CentOS 5 containers.

**Comment by bgruening** [comment]
@stevecassidy we now build against CentOS-6 and are currently migrating to R3.3. Maybe you can update this package and rebase against master in a few days.

**Comment by johanneskoester** [comment]
We have migrated our build system from Travis CI to Circle CI. If you would like to continue working on this PR, please update with latest upstream master and reopen this PR.

**Pull request closed without merging**
