### PR TITLE
fix ENV variable to QUARRY_PATH for codingquarry recipe, bump to build 1

### PR DESCRIPTION
**Pull request by nextgenusfs**
----------------

* [ ] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [ ] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

CodingQuarry tool requires an ENV variable to be set -- it is expecting $QUARRY_PATH, however looks like we set $QUARRYFILES in the first build.sh, bumped build number and set QUARRY_PATH.

### CODE REVIEW

**Comment by nextgenusfs** [comment]
Looks like failed on macOS -- note sure we ever got it working due to compiler issues.  I've compiled on macOS using GCC manually.  Shall we list as linux only?

**Comment by kastman** [comment]
Hi @nextgenusfs - We did end up getting OSX to run in #11815, and that was merged into master; what is currently in master built on OSX without problem when we pulled it in in Nov 2018, but it's showing a problem with openmp again now. 

I'm checking it out now; let's not toss it completely just yet.

**Comment by kastman** [comment]
Looks like the main fix here was the `-I` include, right? Nice find! Good to merge?

**Comment by nextgenusfs** [comment]
Yeah I think good to go. Adding llvm to the host seemed to be necessary as well.

**Comment by kastman** [comment]
Yeah, I remember I added `llvm` but it wasn't sufficient; I think it needed both. Merged!

**Pull request merged**
