### PR TITLE
Update rnftools to 0.3.1.3

### PR DESCRIPTION
**Pull request by epruesse**
Update `rnftools`: **0.3.1.2** &rarr; **0.3.1.3**

***

[Package Info](https://bioconda.github.io/recipes/rnftools/README.html) | [Recipe Folder](https://github.com/bioconda/bioconda-recipes/tree/master/recipes/rnftools) | [Upstream Home](http://karel-brinda.github.io/rnftools) | [Upstream Releases](https://github.com/karel-brinda/rnftools/tags)  

***

This pull request was automatically generated by [bioconda-utils](https://github.com/bioconda/bioconda-utils).

### CODE REVIEW

**Comment by epruesse** [comment]
dependencies need to be updated

**Comment by epruesse** [comment]
ping @karel-brinda

**Comment by karel-brinda** [comment]
@epruesse Could you please close this pull request?It's duplicating https://github.com/bioconda/bioconda-recipes/pull/11390.

**Comment by epruesse** [comment]
thx

**Pull request closed without merging**
