### PR TITLE
bioconductor 3.5 

### PR DESCRIPTION
**Pull request by daler**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

This PR is a merge from the `bulk` branch where we have been updating all the bioconductor packages to Bioconductor 3.5. These recipes have also been standardized and templated so that the next round of updates for Bioconductor 3.6, which comes out at the end of Oct, should happen much more quickly.

Thanks @bgruening and @rvalieris for all the help!

@bioconda/osx, we still have some issues building on OSX. Most notably in `bioconductor-rhdf5` and `bioconductor-rgraphviz`, but also others as listed below, which we have skipped on osx for now. Any packages you can convince to build on osx would be very helpful! An example of an error that happens on a few of these packages is here: https://travis-ci.org/bioconda/bioconda-recipes/jobs/292842862#L731

xref #4560 

```
bioconductor-biomformat
bioconductor-bubbletree
bioconductor-chipcomp
bioconductor-flowcl
bioconductor-ipo
bioconductor-mmdiff
bioconductor-monocle
bioconductor-motifbreakr
bioconductor-motifstack
bioconductor-motiv
bioconductor-mzr
bioconductor-oligoclasses
bioconductor-oligo
bioconductor-phyloseq
bioconductor-rgraphviz
bioconductor-rhdf5
bioconductor-scan.upc
bioconductor-scater
bioconductor-synergyfinder
bioconductor-systempiper
```

### CODE REVIEW

**Comment by bgruening** [comment]
Lovely! Thanks a ton!

**Comment by rvalieris** [comment]
hooray ! :tada: :tada:

**Comment by chapmanb** [comment]
Incredible work, thanks Ryan and to everyone for helping keep R up to date.

**Comment by bgruening** [comment]
That makes 3 core team members - lets merge it.

**Comment by acaprez** [comment]
@daler - I have `bioconductor-rhd5` and `bioconductor-rgraphviz` building ok on OS X, so I can open a PR shortly.  But I did have one question:  The compiler specs have been removed/commented out in both recipes.  Are compiler specs no longer supposed to be included for bioconductor recipes, even for packages that build shared libs?

**Comment by daler** [comment]
@acaprez great!

For this bioconductor update, the strategy was to disable/comment out any non-standard parts of recipes and build scripts, and then incrementally add them back in. For example, IIRC there were a few recipes that previously had specified gcc for linux that didn't actually need them. For the problematic osx ones, I tried things like updating the patch and re-enabling llvm or gcc. Which didn't work for me, but only being able to test on travis made it tedious so I didn't exhaustively test. I then commented them back out.

At this point however, feel free to do whatever it takes to get things to build!

**Pull request merged**
