### PR TITLE
MultiQC for py3

### PR DESCRIPTION
**Pull request by ewels**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

Trying to get MultiQC to build for python3 with click. Can't get test builds to work locally or on travis with branch, so trying in a PR instead..

### CODE REVIEW

**Comment by ewels** [comment]
Hmm, not sure why the first three commits there are showing up. They've already been merged.. :\

**Comment by ewels** [comment]
ok, so as expected, getting [an error](https://travis-ci.org/bioconda/bioconda-recipes/jobs/235927260#L677) for py3 on linux due to `click` looking for the `locale` command.

**Comment by ewels** [comment]
Brilliant stuff - you fixed it @bgruening! What was the secret? `libgcc`?

**Comment by bgruening** [comment]
@ewels I didn't fixed it, sorry :(
I just figured out that the command `multiqc --version` is triggering the click error.
After this I saw that `libgcc` was missing, this is due to the fact that conda-forge is not putting this into their run-time dependencies, which they should.

**Comment by bgruening** [comment]
@ewels just for your information: http://click.pocoo.org/5/python3

```
At the moment, it is strongly recommended is to use Python 2 for Click utilities unless Python 3 is a hard requirement.
```
Maybe it is really better to skip python3 for click packages until 3.7 is our with a proper fix.

**Comment by ewels** [comment]
Ah ok, that's a shame. Thanks for the link, I've read it before - I still struggle to agree with it though, as I and many others have been running MultiQC + click on Python3 for over a year now with no problems, including from bioconda with the previous build system. This packaging issue is the first problem I've run into.

**Comment by bgruening** [comment]
@ewels we could patch click, so that it only issues a warning and fails gracefully if local is not present.

**Comment by ewels** [comment]
Yeah, I was just thinking about this.. So now that `skip:false` is there, it is building for Python3 right? So what is it that will be broken? Just the Python 3 docker image on quay.io?

**Comment by ewels** [comment]
(I just tried installing from bioconda into a test py3 environment locally and it seems to work fine)

**Comment by bgruening** [comment]
The python3 docker images is very likely broken and all systems that do not have a utf-8 locale, as far as I understood it.

**Comment by ewels** [comment]
Ok - well at least it's now available for some people I guess, probably better than not being available for any py3 users. Thanks for your work on this!

Phil

**Pull request merged**
