### PR TITLE
Update breakfast to 0.4.1

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`breakfast`](https://bioconda.github.io/recipes/breakfast/README.html): **0.4.0** &rarr; **0.4.1**

[install with bioconda](http://bioconda.github.io/recipes/breakfast/README.html) [Conda](https://anaconda.org/bioconda/breakfast/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/breakfast`](https://github.com//bioconda/bioconda-recipes/tree/bump/breakfast/recipes/breakfast) (click to view/edit other files)
Summary | breakfast: fast putative outbreak cluster and infection chain detection using SNPs
Home | [https://github.com/rki-mf1/breakfast](https://github.com/rki-mf1/breakfast)
Releases |[https://pypi.org/pypi/breakfast/json](https://pypi.org/pypi/breakfast/json)
Recipe Maintainer(s) | @matthuska

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Review by rpetit3 — APPROVED** [review]

**Comment by rpetit3** [comment]
@BiocondaBot please merge

**Comment by daler** [comment]
@rpetit3 see #35426 ([this comment](https://github.com/bioconda/bioconda-recipes/pull/35426#issuecomment-1164374063)) -- looks like upstream requires py3.10, but bioconda is not yet fully supporting 3.10.

**Comment by daler** [comment]
(incidentally, the bot seems to be opening multiple PRs for bumps, so that needs to be fixed)

**Comment by rpetit3** [comment]
Ah, bummer. Is the duplicate PR this one: https://github.com/bioconda/bioconda-recipes/pull/35426? Looks like you opened the original PR and the bot started using it. Then for some reason stopped, and opened this PR?

@matthuska - Looking at the release notes. 0.4.0 seemed fine with 3.9, and 0.4.1 only changed the requirements at setup. Are we ok to keep this at 3.9 for the time being?

**Comment by matthuska** [comment]
Hi @rpetit3 , I introduced some small Python 3.10-only changes into the code in version 0.4.1, not realizing that this isn't supported by conda-forge and bioconda yet (thanks for the info @daler ). The changes are minor, I'll rewrite them to be 3.9-friendly and then do a 0.4.2 release. We can skip the 0.4.1 release in bioconda.

**Comment by rpetit3** [comment]
You know, looking at the CI: https://dev.azure.com/bioconda/bioconda-recipes/_build/results?buildId=17900&view=logs&j=e14e69ff-a0ae-55c4-b71d-229b239cfb2f&t=7df82132-b284-504b-53d6-7d3e63519572&l=149

Python 3.10 was used in build process. All the tests passed, I think we are ok to just pin the recipe here to `python>=3.10`

Unless I'm missing something completely, and you suggest other wise @matthuska

**Comment by matthuska** [comment]
If bioconda and conda-forge are on mostly on <= 3.9 then I'd be nervous to have a >= 3.10 requirement on my package, since I'd expect it'd lead to problems in combined environments. I'm happy to make the change but it might need to wait until Sunday or Monday.

**Comment by rpetit3** [comment]
Sounds good, I'll leave as is. And no real rush. Most of the recipes I've seen are more `python>3` and not so much `python<3.10`, so I think you'll be fine.

**Comment by daler** [comment]
yep we're at that awkward transition stage where some but not all packages are migrated to 3.10 (see https://conda-forge.org/status/#python310 for conda-forge; bioconda hasn't started yet).

I would expect there to be conflicts in shared environments but hopefully not for _too_ long.

**Comment by matthuska** [comment]
I just did the new release which supports Python 3.9 again. Should I do a separate PR to update the meta.yaml file to have python >= 3.9 as a build and/or run dependency? Currently it has python >=3.6,<3.11, which was the version that the grayskull conda skeleton generator put in the meta.yaml file and I didn't think to change it.

**Comment by rpetit3** [comment]
I've updated it here https://github.com/bioconda/bioconda-recipes/pull/35545

**Pull request merged**
