### PR TITLE
Rebuild prophyle (python)

### PR DESCRIPTION
**Pull request by epruesse**
Rebuild [`prophyle`](https://bioconda.github.io/recipes/prophyle/README.html) to update pinnings

[install with bioconda](http://bioconda.github.io/recipes/prophyle/README.html) [Conda](https://anaconda.org/bioconda/prophyle/files)

Info | Link
-----|-----
Recipe | [`recipes/prophyle`](https://github.com//bioconda/bioconda-recipes/tree/bump/prophyle/recipes/prophyle) (click to view/edit other files)
Releases |[https://pypi.org/pypi/prophyle/json](https://pypi.org/pypi/prophyle/json)

***

Rebuild is necessary for the following reasons:
- Pin `python 3.7,3.6` not within `>=3.5,<3.6.0a0`

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/updating.html)).

### CODE REVIEW

**Comment by epruesse** [comment]
(Don't merge - will use this to test bot)

**Comment by dpryan79** [comment]
:+1:

**Comment by epruesse** [comment]
@biocondabot rebuild

**Comment by epruesse** [comment]
@BiocondaBot rebuild

**Comment by epruesse** [comment]
@biocondabot merge

**Comment by epruesse** [comment]
@BiocondaBot merge

**Comment by epruesse** [comment]
@BiocondaBot rebuild

**Comment by epruesse** [comment]
@BiocondaBot merge

**Comment by epruesse** [comment]
@biocondabot merge

**Comment by epruesse** [comment]
@BiocondaBot merge

**Comment by dpryan79** [comment]
Ooooo. Can it delete branches too?

**Comment by epruesse** [comment]
Sure. Can you see a reason why we wouldn't want it to?

**Comment by dpryan79** [comment]
Nope, I see no reason not to.

**Comment by dpryan79** [comment]
Oops, in case you want to use this for testing maybe I should leave it here...

**Comment by epruesse** [comment]
No, it's fine.

Autobump uses the branches to maintain state. It will always try to update from the `bump/PACKAGE` branch, so if the branch exists and has the most recent version, it won't do anything. That's useful if you close a PR because a version didn't work. You can close the PR and leave the branch and it will not try to make a new one until the next release is there.

It also cleans branches out. For this one, when it runs next, it will notice that the files this branch modifies were modified in master since this branch was forked. And so it'll delete it.

**Pull request merged**
