### PR TITLE
sorted nearest 0.0.23

### PR DESCRIPTION
**Pull request by endrebak**
* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [X] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [X] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by npavlovikj** [comment]
Looks like you are missing "-" in the `build` section, therefore the compiler is not found. It should be:
```
requirements:
  build:
    - {{ compiler('c') }}
```
instead.

**Comment by npavlovikj** [comment]
Also, since it is new version, the `build` number should be 0 and not 1.

**Comment by npavlovikj** [comment]
@endrebak , don't forget to set the build number to 0 as well :)

**Comment by endrebak** [comment]
Thanks, I will do that the next time. Did not feel like rerunning the circleci again. Thanks for the help :)

**Pull request merged**
