### PR TITLE
Update localhgt v1.0.1

### PR DESCRIPTION
**Pull request by wshuai294**
Describe your pull request here
Revise a bug in localhgt v1.0.1. 
----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

### General instructions

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

### Instructions for avoiding API, ABI, and CLI breakage issues
Conda is able to record and lock (a.k.a. pin) dependency versions used at build time of other recipes.
This way, one can avoid that expectations of a downstream recipe with regards to API, ABI, or CLI are violated by later changes in the recipe.
If not already present in the meta.yaml, make sure to specify `run_exports` (see [here](https://bioconda.github.io/contributor/linting.html#missing-run-exports) for the rationale and comprehensive explanation).
Add a `run_exports` section like this:

```yaml
build:
  run_exports:
    - ...

```

with `...` being one of:

| Case                             | run_exports statement                                               |
| -------------------------------- | ------------------------------------------------------------------- |
| semantic versioning              | `{{ pin_subpackage("myrecipe", max_pin="x") }}`     |
| semantic versioning (0.x.x)      | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}`   |
| known breakage in minor versions | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| known breakage in patch versions | `{{ pin_subpackage("myrecipe", max_pin="x.x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| calendar versioning              | `{{ pin_subpackage("myrecipe", max_pin=None) }}`    |

while replacing `"myrecipe"` with either `name` if a `name|lower` variable is defined in your recipe or with the lowercase name of the package in quotes.

### Bot commands for PR management

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

Note that the <code>@BiocondaBot please merge</code> command is now depreciated. Please just squash and merge instead.

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by wshuai294** [comment]
@BiocondaBot please add label

**Comment by wshuai294** [comment]
@bioconda/core  Hi, could you please help me review this pull request? Also, I wonder if could you help me to delete the outdated version at Anaconda (the link is https://anaconda.org/bioconda/localhgt/1.0.6/download/osx-64/localhgt-1.0.6-h85dcccf_0.tar.bz2)? Although its version name is v1.0.6, this is an outdated version. It would be appreciated if you could help me to delete this.

**Comment by wshuai294** [comment]
@bioconda/core Hi, also, I revised the package summary and home, but Anaconda only shows the initial one, could you please help me update it? The link is at [https://anaconda.org/bioconda/localhgt](url).

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
Lets see if those problems are solved in 24h. Please ping me on Matrix if not.

**Comment by wshuai294** [comment]
Thanks so much for your help!

**Comment by wshuai294** [comment]
@bioconda/core Hello, Thanks for your help, the outdated version is labeled as broken. But on the description page, it looks like
image
Is there any method to delete the second command which is related to the broken label?
﻿
Also, the description and the home website are not updated. Could you please help me with this?
image

**Comment by bgruening** [comment]
That is unfortunate, we don't have control over the website, its autogenerated. I can move the package away if this helps.

**Comment by bgruening** [comment]
Ok, its removed now.

**Comment by wshuai294** [comment]
Thank you so much!

**Pull request merged**
