### PR TITLE
correct database location for GTDB

### PR DESCRIPTION
**Pull request by SilasK**
**Replace this sentence with a detailed description of your pull request**

----

> Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences**
      (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

> Everyone has access to the following BiocondaBot commands, which can be given in a comment:
>
>  * `@BiocondaBot please update` will cause the BiocondaBot to merge the master branch into a PR
>  * `@BiocondaBot please add label` will add the `please review & merge` label.
>  * `@BiocondaBot please fetch artifacts` will post links to packages and docker containers built by the CI system. You can use this to test packages locally before merging.
>
> For members of the Bioconda project, the following command is also available:
>
>  * `@BiocondaBot please merge` will cause packages/containers to be uploaded and a PR merged. Someone must approve a PR first! This has the benefit of not wasting CI build time required by manually merging PRs.
>
> If you have questions, please post them in gitter or ping `@bioconda/core` in a comment (if you are not able to directly ping `@bioconda/core` then the bot will repost your comment and enable pinging).

### CODE REVIEW

**Comment by SilasK** [comment]
Fixes https://github.com/metagenome-atlas/atlas/issues/277

**Comment by SilasK** [comment]
@bioconda-bot please add label

**Comment by marcelm** [comment]
Since you’re changing the recipe anyway, I took the liberty of changing the `matplotlib` dependency to `matplotlib-base`, see #19996.

**Comment by dpryan79** [comment]
@bioconda-bot please fetch artifacts

**Comment by dpryan79** [comment]
Is there a reason this is marked as not working on OSX, even though it appears to be python only? As is, the installation will likely break many environments since it's a python 3.8 only package, but nothing else in bioconda (except pure python packages) will work with python 3.8 yet.

**Comment by SilasK** [comment]
> Is there a reason this is marked as not working on OSX, even though it appears to be python only? As is, the installation will likely break many environments since it's a python 3.8 only package, but nothing else in bioconda (except pure python packages) will work with python 3.8 yet.

How does it come that it is to python 3.8 only?
Maybe the skip was not removed. I know that at least pplacer >=1.1.alpha17 is not available on osx. 
sometimes it's confusing to have these noarch packages which build only on Linux due to dependencies.

**Comment by dpryan79** [comment]
Ah, yeah, probably pplacer was the culprit. I've changed this to a noarch: python package, which will then build correctly. It still won't install on OSX until someone gets pplacer to work there, but that's a separate issue.

**Comment by dpryan79** [comment]
@bioconda-bot please fetch artifacts

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Pull request merged**
