### PR TITLE
moFF : Enforced python v3.4 or later as pymzml requires it.

### PR DESCRIPTION
**Pull request by CarlosHorro**
* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [X] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [X] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by bgruening** [comment]
@Maux82 is moff still not working under py35? So is the only supported version 36 and 37?

**Comment by Maux82** [comment]
@bgruening moFF should work in py35. If we force to py36 it will be better also moFF and pymzl

**Comment by CarlosHorro** [comment]
Um... documentation here
https://github.com/compomics/moFF

says that moFF requires Python3.6+?

**Comment by CarlosHorro** [comment]
I suppose new pymzml version was going to be 2.0.6.1 but it is 2.0.6-py_1, so I think just referencing to 2.0.6 we will use the last .1 build...

**Comment by bgruening** [comment]
Cool thanks!

**Pull request merged**
