### PR TITLE
Add a bioconda recipe for variant tools 3.0.8

### PR DESCRIPTION
**Pull request by BoPeng**
Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it. Note that if you are not already a member of the bioconda project (meaning that you can't add this label), please ping `@bioconda/core` so that your PR can be reviewed and merged (please note if you'd like to be added to the bioconda project). Please see https://github.com/bioconda/bioconda-recipes/issues/15332 for more details.

* [ ] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [ ] This PR adds a new recipe.
* [ ] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by dpryan79** [comment]
You'll have to let python know that the C compiler isn't called `cc`, but rather `$CC`.

**Comment by BoPeng** [comment]
I use `new_compiler()` in `setup.py` 

https://github.com/vatlab/varianttools/blob/2788397a8a253a1aebdb1fd54b5dce6a44b26b84/setup.py#L273

Not sure how to specify a C++ instead of a C compiler. Let me check.

**Comment by BoPeng** [comment]
The conda-forge way to specify cxx compiler is

```
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
```

Is it the same in bioconda?

**Comment by dpryan79** [comment]
Yes, conda works the same everywhere.

**Comment by BoPeng** [comment]
OK. I am removing the steps to build static libraries for the final modules.... hopefully the more straightforward build method would help.

**Comment by BoPeng** [comment]
@dpryan79 Finally, all checks have passed... please merge. Thanks.

**Pull request merged**
