### PR TITLE
bioconductor-cummerbund bump build to integrate bioconductor-gviz new…

### PR DESCRIPTION
**Pull request by lecorguille**
* [ ] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [X] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

… build

https://github.com/bioconda/bioconda-recipes/pull/2833

### CODE REVIEW

**Comment by lecorguille** [comment]
https://github.com/galaxyproject/tools-devteam/pull/412

**Comment by bgruening** [comment]
Mh, this should not be needed I think :(

**Comment by lecorguille** [comment]
@bgruening Oh! But I still get this error:

`conda install bioconductor-cummerbund`
```
Traceback (most recent call last):
  File "/tmp/mc2/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/tmp/mc2/lib/python2.7/site-packages/conda/cli/main.py", line 173, in main
    args_func(args, p)
  File "/tmp/mc2/lib/python2.7/site-packages/conda/cli/main.py", line 180, in args_func
    args.func(args, p)
  File "/tmp/mc2/lib/python2.7/site-packages/conda/cli/main_install.py", line 45, in execute
    install.install(args, parser, 'install')
  File "/tmp/mc2/lib/python2.7/site-packages/conda/cli/install.py", line 334, in install
    update_deps=args.update_deps)
  File "/tmp/mc2/lib/python2.7/site-packages/conda/plan.py", line 412, in install_actions
    update_deps=update_deps):
  File "/tmp/mc2/lib/python2.7/site-packages/conda/resolve.py", line 793, in solve
    installed, minimal_hint=minimal_hint, update_deps=update_deps)
  File "/tmp/mc2/lib/python2.7/site-packages/conda/resolve.py", line 543, in solve2
    dists = self.get_dists(specs, filtered=True)
  File "/tmp/mc2/lib/python2.7/site-packages/conda/resolve.py", line 440, in get_dists
    filtered = self.prune_packages(specs)
  File "/tmp/mc2/lib/python2.7/site-packages/conda/resolve.py", line 234, in prune_packages
    while sum(filter_group([ms]) for ms in mspecs):
  File "/tmp/mc2/lib/python2.7/site-packages/conda/resolve.py", line 234, in <genexpr>
    while sum(filter_group([ms]) for ms in mspecs):
  File "/tmp/mc2/lib/python2.7/site-packages/conda/resolve.py", line 208, in filter_group
    filter_group(deps)
  File "/tmp/mc2/lib/python2.7/site-packages/conda/resolve.py", line 185, in filter_group
    for ms in self.ms_depends(fn) if ms.name in self.groups)
  File "/tmp/mc2/lib/python2.7/site-packages/conda/resolve.py", line 259, in ms_depends
    res = self.msd_cache[fn] = [MatchSpec(d) for d in depends]
  File "/tmp/mc2/lib/python2.7/site-packages/conda/resolve.py", line 46, in __init__
    self.vspecs = [VersionSpec(s) for s in parts[1].split('|')]
  File "/tmp/mc2/lib/python2.7/site-packages/conda/version.py", line 274, in __new__
    self.cmp = VersionOrder(b)
  File "/tmp/mc2/lib/python2.7/site-packages/conda/version.py", line 140, in __init__
    raise ValueError(message + "invalid character(s).")
ValueError: Malformed version string '0.6-26': invalid character(s).
```

And with a little hack within `conda/resolve.py` I diplayed the package name and that confirm that it's still `bioconductor-gviz`

Hum .. any other ideas?

**Comment by bgruening** [comment]
@lecorguille do not, never, specify build versions in dependencies. `>=0.6` is enough.

**Comment by daler** [comment]
Some bioconductor packages that trailing version, see last section of https://github.com/bioconda/bioconda-recipes/tree/master/scripts/bioconductor

**Comment by lecorguille** [comment]
For my defence, I didn't introduce this `-` 😝 

For me the `_26` was not the build version but was part of the version string

The real r-latticeextra in R is [0.6-28](https://cran.r-project.org/web/packages/latticeExtra/index.html) 
In conda it's version is [`version: "0.6_28"`](https://github.com/conda/conda-recipes/blob/master/r-packages/r-latticeextra/meta.yaml#L8)

In bioconductor-gviz, you're suggesting  to set ` - 'r-latticeextra >=0.6'` instead of [` - 'r-latticeextra >=0.6_26'`](https://github.com/bioconda/bioconda-recipes/blob/e9d413ee8a45baa32b4a79cf56afe7ff14dd6a04/recipes/bioconductor-gviz/meta.yaml#L33) ?

**Comment by bgruening** [comment]
@lecorguille somewhere there is a `ValueError: Malformed version string '0.6-26': invalid character(s).` with a dash :(

**Comment by lecorguille** [comment]
@bgruening That why I fixed bioconductor-gviz https://github.com/bioconda/bioconda-recipes/pull/2833
But bioconductor-cummerbund continues to use the old build

**Comment by bgruening** [comment]
Can you try now? Without this patch?

**Comment by druvus** [comment]
Closing this for now. Please reopen if needed.

**Pull request closed without merging**
