### PR TITLE
Update usher to 0.6.1

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`usher`](https://bioconda.github.io/recipes/usher/README.html): **0.6.0** &rarr; **0.6.1**

[install with bioconda](http://bioconda.github.io/recipes/usher/README.html) [Conda](https://anaconda.org/bioconda/usher/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/usher`](https://github.com//bioconda/bioconda-recipes/tree/bump/usher/recipes/usher) (click to view/edit other files)
Summary | Ultrafast Sample Placement on Existing Trees (UShER)
Home | [https://github.com/yatisht/usher](https://github.com/yatisht/usher)
Releases |[https://github.com/yatisht/usher/tags](https://github.com/yatisht/usher/tags)
Author | `@yatisht`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by AngieHinrichs** [comment]
Bioconda folks, please review this version bump at your earliest convenience -- it will enable a terrific speedup in the pangolin tool, used by public health departments and researchers worldwide to assign Pango lineages to new SARS-CoV-2 sequences.  Thanks!

@pvanheus ?

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
@AngieHinrichs thanks!

**Comment by bgruening** [comment]
@BiocondaBot please merge

**Comment by AngieHinrichs** [comment]
Wonderful, thanks @bgruening!

**Pull request merged**
