### PR TITLE
Bump libsequence to 1.9.4.  Update dependencies, which are build-only!

### PR DESCRIPTION
**Pull request by molpopgen**
Compiler and run unit tests after build.

* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [X] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [X] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

I also fixed the LICENSE bit, which was out of date.

### CODE REVIEW

**Comment by molpopgen** [comment]
@bioconda/core The OS X build failed, but apparently for reasons other than failing to build the package.  There's a message about "issuing a restart could fix this", but there's not a restart button, so I need help...

**Comment by bgruening** [comment]
I restarted it. One question, is zlib needed during build-phase or not. Because currently you have not defined it.

**Comment by molpopgen** [comment]
> I restarted it. One question, is zlib needed during build-phase or not. Because currently you have not defined it.

Thanks!  

No, there are no longer any dependencies at run-time.  The only build dependency is boost, and that is only for compiling/running the unit tests, which I've added to this PR.

Is there a way to trigger a rebuild that I missed?

**Comment by bgruening** [comment]
Try to find this link:

grafik

And rerun the failed step in the circle-ci workflow.

**Comment by molpopgen** [comment]
So, this is ready to merge, with the caveat that we have to skip OS X for a while.  The case-insensitive file system there means that there are some name conflicts to to subdirs that only differ by capitalization.  That'll go away as deprecated features are removed.

**Comment by bgruening** [comment]
Thanks @molpopgen!

**Pull request merged**
