### PR TITLE
Update r-dimsum to 1.2.8

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`r-dimsum`](https://bioconda.github.io/recipes/r-dimsum/README.html): **1.2.7** &rarr; **1.2.8**

[install with bioconda](http://bioconda.github.io/recipes/r-dimsum/README.html) [Conda](https://anaconda.org/bioconda/r-dimsum/files)

Info | Link
-----|-----
Recipe | [`recipes/r-dimsum`](https://github.com//bioconda/bioconda-recipes/tree/bump/r_dimsum/recipes/r-dimsum) (click to view/edit other files)
Releases |[https://github.com/lehner-lab/DiMSum/tags](https://github.com/lehner-lab/DiMSum/tags)
Recipe Maintainer(s) | @andrefaure
Author | `@lehner-lab`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Review by andrefaure — CHANGES_REQUESTED** [review]
Please update vsearch requirement to >=2.17

**Comment by andrefaure** [comment]
@BiocondaBot please add label

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
@bioconda-bot please merge

**Comment by andrefaure** [comment]
@bgruening not sure this is the correct place to comment on this but:

Some of the changes made to the meta.yaml in this update are causing problems, specifically the following packages need to be the following versions:
    - pandoc =1.17.2
    - fastqc =0.11.9
    - cutadapt =2.4
    - starcode =1.3

(I only intended to update the requirements for vsearch i.e. >=2.17)

Is it possible to revert these 4 changes to the meta.yaml without updating the package itself? Thanks

**Pull request merged**
