### PR TITLE
Update dependencies for libmaus2

### PR DESCRIPTION
**Pull request by matthdsm**
Add missing dependencies
Pending merge and build of #27335

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by matthdsm** [comment]
dependecy for #24972

**Comment by matthdsm** [comment]
apparently, adding snappy and staden_io_lib as a dependency breaks something...
last warning is
```
09:54:28 BIOCONDA INFO (OUT) /opt/conda/conda-bld/libmaus2_1615541615872/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/7.5.0/../../../../x86_64-conda-linux-gnu/bin/ld: warning: libcurl.so.4, needed by ./.libs/libmaus2.so, not found (try using -rpath or -rpath-link)
09:54:28 BIOCONDA INFO (OUT) /opt/conda/conda-bld/libmaus2_1615541615872/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/7.5.0/../../../../x86_64-conda-linux-gnu/bin/ld: ./.libs/libmaus2.so: undefined reference to `curl_easy_perform'
09:54:28 BIOCONDA INFO (OUT) /opt/conda/conda-bld/libmaus2_1615541615872/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/7.5.0/../../../../x86_64-conda-linux-gnu/bin/ld: ./.libs/libmaus2.so: undefined reference to `curl_easy_getinfo'
09:54:28 BIOCONDA INFO (OUT) /opt/conda/conda-bld/libmaus2_1615541615872/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/7.5.0/../../../../x86_64-conda-linux-gnu/bin/ld: ./.libs/libmaus2.so: undefined reference to `curl_easy_init'
09:54:28 BIOCONDA INFO (OUT) /opt/conda/conda-bld/libmaus2_1615541615872/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/7.5.0/../../../../x86_64-conda-linux-gnu/bin/ld: ./.libs/libmaus2.so: undefined reference to `curl_easy_strerror'
09:54:28 BIOCONDA INFO (OUT) /opt/conda/conda-bld/libmaus2_1615541615872/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/7.5.0/../../../../x86_64-conda-linux-gnu/bin/ld: ./.libs/libmaus2.so: undefined reference to `curl_easy_cleanup'
09:54:28 BIOCONDA INFO (OUT) /opt/conda/conda-bld/libmaus2_1615541615872/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/7.5.0/../../../../x86_64-conda-linux-gnu/bin/ld: ./.libs/libmaus2.so: undefined reference to `curl_easy_setopt'
09:54:28 BIOCONDA INFO (OUT) /opt/conda/conda-bld/libmaus2_1615541615872/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/7.5.0/../../../../x86_64-conda-linux-gnu/bin/ld: ./.libs/libmaus2.so: undefined reference to `curl_global_init'
09:54:28 BIOCONDA INFO (OUT) /opt/conda/conda-bld/libmaus2_1615541615872/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/7.5.0/../../../../x86_64-conda-linux-gnu/bin/ld: ./.libs/libmaus2.so: undefined reference to `curl_global_cleanup'
09:54:28 BIOCONDA INFO (OUT) collect2: error: ld returned 1 exit status
```

Let's try adding libcurl

**Comment by matthdsm** [comment]
This is going over my head (again)
@bioconda/core, any tips?
Please?

M

**Comment by matthdsm** [comment]
@BiocondaBot please add label

**Review by tomiles — APPROVED** [review]

**Comment by matthdsm** [comment]
@BiocondaBot please merge

**Pull request merged**
