### PR TITLE
Update iphop to 1.3.3

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`iphop`](https://bioconda.github.io/recipes/iphop/README.html): **1.3.2** &rarr; **1.3.3**

[install with bioconda](http://bioconda.github.io/recipes/iphop/README.html) [Conda](https://anaconda.org/bioconda/iphop/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/iphop`](https://github.com//bioconda/bioconda-recipes/tree/bump/iphop/recipes/iphop) (click to view/edit other files)
Summary | Predict host genus from genomes of uncultivated phages.
Home | [https://bitbucket.org/srouxjgi/iphop/](https://bitbucket.org/srouxjgi/iphop/)
Releases |[https://bitbucket.org/srouxjgi/iphop/downloads/?tab=downloads](https://bitbucket.org/srouxjgi/iphop/downloads/?tab=downloads)
Recipe Maintainer(s) | @simroux

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by simroux** [comment]
Recipe needs to be changed to include  a run_export statement, was not done yet for this autobump. I'll create another pull request with the run_export statement, this pull request can be dismissed.

**Review by simroux — CHANGES_REQUESTED** [review]
Need to add run_export statement

**Comment by simroux** [comment]
@mencian - Thanks for fixing the recipe to add the run_exports clause. If I may, two quick (newbie) questions:
- How did you add a change to a BiocondaBot pull request ? I was looking into this but could not figure out so was planning on doing another pull request, but modifying this one is much cleaner.
- I'm fairly confused by the current failure of the test (now that run_exports is not an issue anymore). The error message is "package blast-2.12.0-h3289130_1 requires perl-json, but none of the providers can be installed", but perl-json is available in bioconda, and when I tried to build the package with bioconda locally I was never able to reproduce this error on 3 different machines. As it seems like you have looked at / worked on way more bioconda recipes than me, is it something you have seen in the past ? And any suggestion for how to fix it ? Thanks !

**Comment by mencian** [comment]
Hello, @simroux! I am happy to explain:

1. Members of the Bioconda organization are able to push commits directly to BiocondaBot autobump PRs. You can still push commits to autobump PRs without member privileges by proposing changes from your local branch to the `bump/<package>` branch on bioconda-recipes. See #44335 as an example.
2. This is likely due to the strict pinnings, since `perl-json` is listed as a dependency of `blast`, and therefore should have been pulled in. The `conda-build`, `conda`, and `mamba` versions used by the CI (which uses `conda 23.3.1`, for example) may be different than what is installed on your local machines', which may also contribute to inconsistent solving behavior. In this case, explicitly adding perl-json as a dependency might help `mamba` solve the build environment.

I hope this answers your question(s)! Please let me know if you would like me to clarify anything.

**Comment by simroux** [comment]
Thanks @mencian for the information and for fixing the latest issues with perl-json and perl-bioperl. Looking at why the pipeline needs BioPerl (which is only used in 1 script we imported from another source, unfortunately not available on conda), I think removing the BioPerl version pinning should not cause an issue since we are requiring perl < 6 anyway.

Thanks again !

**Review by simroux — APPROVED** [review]
Moving to version 1.3.3. Had to adjust a few version pinning and add the "run_exports" clause.

**Review by mencian — APPROVED** [review]

**Pull request merged**
