### PR TITLE
Rebuild snap

### PR DESCRIPTION
**Pull request by druvus**
:information_source:
If this is your first pull request to Bioconda please ping `@bioconda/core` so it can be reviewed and to request being added as a member of the Bioconda team. Members of the Bioconda team are able to merge their own pull requests once tests and linting have passed.

----------------

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [x] This PR does something else (explain below).
Rebuilding using new compilers

### CODE REVIEW

**Comment by druvus** [comment]
@bioconda-bot recheck

**Comment by druvus** [comment]
@bioconda-bot recheck

**Comment by dpryan79** [comment]
I wonder what `snap` is printing on OSX.

**Comment by dpryan79** [comment]
Ah, on OSX it errors with:

    snap: line 9: 42106 Abort trap: 6
           ${SNAPDIR}/bin/$NAME $@

**Comment by dpryan79** [comment]
Weird, the actual binary works just fine on OSX, it's just the wrapper in `bin/` that has a problem.

**Comment by dpryan79** [comment]
Oddly, I can build it locally on a mac and it fails, but if I install the broken package then it works fine.

**Comment by druvus** [comment]
thanks, I will take another look at osx.

**Comment by dpryan79** [comment]
I just merged in another rebuild of this that had similar issues on OSX. It looks like snap is just plain segfaulting when compiled with clang for some unknown reason. I've opted to just skip building on OSX for the time being.

**Pull request closed without merging**
