### PR TITLE
Rebuild squid (compiler)

### PR DESCRIPTION
**Pull request by epruesse**
Rebuild [`squid`](https://bioconda.github.io/recipes/squid/README.html) to update pinnings

[install with bioconda](http://bioconda.github.io/recipes/squid/README.html) [Conda](https://anaconda.org/bioconda/squid/files)

Info | Link
-----|-----
Recipe | [`recipes/squid`](https://github.com//bioconda/bioconda-recipes/tree/bump/squid/recipes/squid) (click to view/edit other files)
Releases |[https://github.com/Kingsford-Group/squid/tags](https://github.com/Kingsford-Group/squid/tags)
Author | `@Kingsford-Group`
***

Rebuild is necessary for the following reasons:
- Recompiling with gxx

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/updating.html)).

### CODE REVIEW

**Comment by dpryan79** [comment]
@epruesse Any clue why this is happening when I rebuilt the package 13 hours ago?

**Comment by epruesse** [comment]
Goog question. Will investigate.

**Comment by epruesse** [comment]
Probably because I did not update my pinnings....

**Comment by epruesse** [comment]
Found problem.

**Pull request closed without merging**
