### PR TITLE
anvio 5.3.0

### PR DESCRIPTION
**Pull request by ozcan**
:information_source:
Bioconda has finished the [GCC7 migration](https://github.com/bioconda/bioconda-recipes/issues/13578). If you are dealing with C/C++ or Python package it can be that you need to rebuild other dependent packages. [Bioconda utils - update-pinning](https://bioconda.github.io/updating.html#updating-recipes-for-a-pinning-change) will assist you with that. If you have any questions please use [issue 13578](https://github.com/bioconda/bioconda-recipes/issues/13578).

----------------

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [X] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [X] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by ozcan** [comment]
Thank you for triggering the CI @druvus, is there a way to start `test-macos` too?

**Comment by druvus** [comment]
@bgruening Do you remember the solution to "Please select a macOS plan" issue?

**Comment by druvus** [comment]
@ozcan I added your changes in #13682 so the latest version should soon be available

**Comment by ozcan** [comment]
Thank you very much @druvus!

**Pull request closed without merging**
