### PR TITLE
Update IQ-TREE to v2.1.4-beta

### PR DESCRIPTION
**Pull request by peterk87**
Update IQ-TREE to [version 2.1.4-beta](https://github.com/iqtree/iqtree2/releases/tag/v2.1.4-beta)

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by peterk87** [comment]
@BiocondaBot please add label

**Comment by dpryan79** [comment]
@peterk87 Any idea where `-platform_version` is coming from on OSX? That's breaking the build there.

**Comment by peterk87** [comment]
@dpryan79 I'm not sure and I don't a Mac to try compiling the new version. I noticed that lsd2 was upgraded to v1.9.9. I'll see if that fixes the issue. 

[This StackOverflow issue](https://stackoverflow.com/questions/60934005/clang-10-fails-to-link-c-application-with-cmake-on-macos-10-12) seems relevant. It may be necessary to specify the linker version directly to Clang (e.g. `-DCMAKE_CXX_FLAGS="-mlinker-version=305"`). I'll try that next.

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@bioconda-bot please merge

Thanks @peterk87

**Pull request merged**
