### PR TITLE
Add Virchip

### PR DESCRIPTION
**Pull request by mehrankr**
Added the Virchip recipe containing build.sh and meta.yaml

### CODE REVIEW

**Comment by mehrankr** [comment]
@BiocondaBot please add label

**Comment by dpryan79** [comment]
If you're in the Hoffman lab, can you please consider testing this on a version of python that's still supported? In the not too distant future we will disable python 2 by default, because it should not be used by anyone any more.

**Comment by mehrankr** [comment]
> If you're in the Hoffman lab, can you please consider testing this on a version of python that's still supported? In the not too distant future we will disable python 2 by default, because it should not be used by anyone any more.

Hey Devon. Thanks for reviewing the request. The models trained with Virchip in 2016 used an old verison of scikit-learn and the models are not compatible with newer versions of scikit-learn and python3 unfortunately.
I will try to modify this in the future but would it be possible to have this repository available at the moment?

Thanks a lot
Mehran

**Comment by dpryan79** [comment]
@bioconda-bot please fetch artifacts

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Pull request merged**
