### PR TITLE
Add fanc recipe

### PR DESCRIPTION
**Pull request by kaukrise**
FAN-C is a library for chromosome conformation capture analyses (https://github.com/vaquerizaslab/fanc).

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by kaukrise** [comment]
@BiocondaBot please add label

**Comment by mbargull** [comment]
@kaukrise, could you add the `LICENSE` file to `MANIFEST.in`in the upstream repo so it will be included in future PyPI releases?
When the license file is included in the sdists, we can use the PyPI source again.

**Comment by kaukrise** [comment]
Thanks a lot, I have added the Manifest.in file to the [fanc repo](https://github.com/vaquerizaslab/fanc).

I saw the changes you made to the meta file. First of all, thanks for cleaning it up! Unfortunately, the tests are now failing due to dependency issues. I have spent a lot of time trying to resolve them on my local machine before I submitted the pull request, but even putting no version restrictions on any of the packages FAN-C depends on results in a large number of conflicts. The only way I was able to resolve the issue is by requiring Python version `3.6`. `pip` (`20.2.2`) does not report any conflicts when installing in a clean virtual env. I fear that the bioconda recipe definitions of FAN-C dependencies conflicting among themselves.

If you have any idea how to resolve this, I would be extremely grateful. The sheer number of reported conflicts in the circleci build output makes it very hard for me to approach this. Thanks in advance!

**Comment by dpryan79** [comment]
OK, the issue is that grid-map needs to be added to conda-forge. At the moment it's getting pulled in from the "main" channel, which seems to have incompatible pinnings.

**Comment by kaukrise** [comment]
Thank you for all the detective work, it is much appreciated. I will look into creating a recipe for [gridmap](https://github.com/pygridtools/gridmap) and create a pull request. Thanks again for your help!

**Comment by dpryan79** [comment]
@kaukrise I'm already in the process of adding gridmap

**Comment by kaukrise** [comment]
Oh, that's fantastic, thank you. The authors also have recipe in their repo, in case you want to have a look at that, but I don't think it made it into bioconda.

**Comment by dpryan79** [comment]
OK, gridmap should be available in a couple hours (it takes a while for conda-forge to make the repository and then the package).

**Comment by kaukrise** [comment]
Thank you so much, that sounds great. Thanks for all the effort you put into this!

**Comment by dpryan79** [comment]
Ugh, OK, that wasn't the entire problem it turns out. I'll look into this more tomorrow.

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
OK, I haven't figured out exactly why there's a conflict in python 3.6 and 3.8, but I can see something is there.

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Comment by kaukrise** [comment]
Thanks again, @dpryan79! I'm really glad this is going to be merged. Just for clarification, because I don't quite understand your most recent commit: is the installation of FAN-C using this recipe now blocked on incompatible Python versions, or does it merely skip the dependency checks? Thanks in advance for the clarification!

**Comment by dpryan79** [comment]
It is only possible on python 3.7 at the moment and will produce and error about not being installable under other python versions.

**Comment by kaukrise** [comment]
Alright, thank you for the clarification!

**Pull request merged**
