### PR TITLE
Update isatools to v0.10.0

### PR DESCRIPTION
**Pull request by djcomlab**
* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [X] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [X] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

This updates the recipe to install isatools v0.10.0.

### CODE REVIEW

**Comment by djcomlab** [comment]
Oh that's weird, not sure how the `scripts/travis-run.sh` got removed?

**Comment by djcomlab** [comment]
Not sure why `test-linux` is failing here, as the dependencies haven't changed since the last release (which passed its tests that time).

**Comment by bgruening** [comment]
Seems that pandas depends on numpy in a different version. Do you need the strict pinning?
Please also reset the build-version number to 0 and don't remove the travis file.

Thanks! :)

**Comment by djcomlab** [comment]
There was something annoying in ISA API that fixing to pandas to 0.20 helped with, but it's not essential.

**Comment by bgruening** [comment]
Nice, worked!

**Pull request merged**
