### PR TITLE
Sync Bowtie2 2.2.5 recipe with 2.2.8 one

### PR DESCRIPTION
**Pull request by nsoranzo**
* [x] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

bowtie2 binaries were not found because they were not moved to `bin/` subdirectory.
Remove llvm requirement since OSX zip file contains already compiled binaries.

### CODE REVIEW

**Comment by nsoranzo** [comment]
Ping @bgruening, this is needed for https://github.com/galaxyproject/tools-devteam/pull/367.

**Comment by nsoranzo** [comment]
Travis is failing because of #1491.

**Comment by daler** [comment]
After fixing the build problems (#1487, #1491) re-running the travis test worked. Merging . . .

**Comment by nsoranzo** [comment]
Thanks @daler!

**Comment by bgruening** [comment]
Thanks Nicola and @daler!

**Pull request merged**
