### PR TITLE
hash ucsc-* osx url

### PR DESCRIPTION
**Pull request by corburn**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by bgruening** [comment]
@corburn have you used the ucsc skeleton generator for this? If not could you please update this scrip as well? Thanks a lot.

**Comment by bgruening** [comment]
ping @daler

**Comment by corburn** [comment]
@bgruening I'll look into updating the script it.

**Comment by corburn** [comment]
Defer to #9454

**Pull request closed without merging**
