### PR TITLE
add R package dependencies installation

### PR DESCRIPTION
**Pull request by ginolhac**
Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it. Note that if you are not already a member of the bioconda project (meaning that you can't add this label), please ping `@bioconda/core` so that your PR can be reviewed and merged (please note if you'd like to be added to the bioconda project). Please see https://github.com/bioconda/bioconda-recipes/issues/15332 for more details.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

I tested it with the docker container and `conda-build` and it was successful
```
> library('RcppGSL')
> 
> 
+ exit 0

Resource usage statistics from testing mapdamage2:
   Process count: 1
   CPU time: Sys=0:00:00.0, User=0:00:00.0
   Memory: 2.8M
   Disk usage: 24B
   Time elapsed: 0:00:02.1

TEST END: /opt/conda/conda-bld/noarch/mapdamage2-2.1.1-pyr35_0.tar.bz2
```

this update should help users to get R / R pkgs installed at the same time as the other dependencies for `mapDamage2`

### CODE REVIEW

**Comment by dpryan79** [comment]
@ginolhac Please disable circleci on your fork.

**Comment by ginolhac** [comment]
@dpryan79 done, sorry I wanted to test it since the the bioconda bot didn't do it. I guess it is because this PR is not a new version number.

**Comment by dpryan79** [comment]
Having circleci enabled on your fork prevents all CI from working here.

**Comment by ginolhac** [comment]
ok, I even revoked the link github/circlecli so it should be ok now. I wanted so much to prevent more mistakes by testing the fork before submitting the PR that I created a mess. Sorry for that

**Pull request merged**
