### PR TITLE
Update perl-sanger-cgp-allelecount to 4.2.1

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`perl-sanger-cgp-allelecount`](https://bioconda.github.io/recipes/perl-sanger-cgp-allelecount/README.html): **4.1.0** &rarr; **4.2.1**

[install with bioconda](http://bioconda.github.io/recipes/perl-sanger-cgp-allelecount/README.html) [Conda](https://anaconda.org/bioconda/perl-sanger-cgp-allelecount/files)

Info | Link
-----|-----
Recipe | [`recipes/perl-sanger-cgp-allelecount`](https://github.com//bioconda/bioconda-recipes/tree/bump/perl_sanger_cgp_allelecount/recipes/perl-sanger-cgp-allelecount) (click to view/edit other files)
Releases |[https://github.com/cancerit/alleleCount/tags](https://github.com/cancerit/alleleCount/tags)
Author | `@cancerit`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Review by johanneskoester — APPROVED** [review]

**Comment by rpetit3** [comment]
@BiocondaBot please merge

**Comment by rpetit3** [comment]
@BiocondaBot please fetch artifacts

**Comment by rpetit3** [comment]
Going to try rerunning tests, to refresh artifacts

**Comment by rpetit3** [comment]
@BiocondaBot please merge

**Pull request merged**
