### PR TITLE
Libsequence

### PR DESCRIPTION
**Pull request by molpopgen**
* [X ] I have read the guidelines above.
* [ X] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

@bioconda/core -- please review

I'm using GCC for both Linux and OS X builds.  The Travis/Docker setup uses a clang that doesn't understand much of the C++11 required, and thus fails.  All tests pass on more recent OS X + clang, but there doesn't seem to be a way to conditionally deal with different OS X target versions?

### CODE REVIEW

**Comment by bgruening** [comment]
@molpopgen to be sure, OSX builds are only possible with gcc?

**Comment by molpopgen** [comment]
Technically, no, but Travis + yaml limitations are forcing this.  The Travis OS X installs are so ancient that C++11 is not supported with the built-in clang.  Then, the metal.yml file doesn't seem to allow me to say "use clang if OS X >= 10.9, otherwise GCC", unless I'm missing something.

**Comment by molpopgen** [comment]
PS, I fixed the missing libgcc run-time requirement, and am about to push that...

**Comment by molpopgen** [comment]
any idea why it is testing other recipes???  One of the linux builds "passes", but gives no indication that it is testing the right thing at all:

INFO bioconda_utils.build:build_recipes(257): Building and testing subdag 1 of 2 (1 recipes)
INFO bioconda_utils.build:build(57): BIOCONDA BUILD START recipes/r-argparse, env: CONDA_BOOST=1.60;CONDA_GMP=5.1;CONDA_GSL=1.16;CONDA_NCURSES=5.9;CONDA_NPY=110;CONDA_PERL=5.22.0;CONDA_PY=35;CONDA_R=3.3.1
INFO bioconda_utils.build:build(102): BIOCONDA BUILD SUCCESS /anaconda/conda-bld/linux-64/r-argparse-1.0.1-py35r3.3.1_0.tar.bz2, CONDA_BOOST=1.60;CONDA_GMP=5.1;CONDA_GSL=1.16;CONDA_NCURSES=5.9;CONDA_NPY=110;CONDA_PERL=5.22.0;CONDA_PY=35;CONDA_R=3.3.1
INFO bioconda_utils.build:build(119): BIOCONDA TEST START via mulled-build recipes/r-argparse, CONDA_BOOST=1.60;CONDA_GMP=5.1;CONDA_GSL=1.16;CONDA_NCURSES=5.9;CONDA_NPY=110;CONDA_PERL=5.22.0;CONDA_PY=35;CONDA_R=3.3.1
updating index in: /anaconda/conda-bld/linux-64
INFO bioconda_utils.build:build(124): BIOCONDA TEST SUCCESS recipes/r-argparse, CONDA_BOOST=1.60;CONDA_GMP=5.1;CONDA_GSL=1.16;CONDA_NCURSES=5.9;CONDA_NPY=110;CONDA_PERL=5.22.0;CONDA_PY=35;CONDA_R=3.3.1
INFO bioconda_utils.build:build(57): BIOCONDA BUILD START recipes/r-argparse, env: CONDA_BOOST=1.60;CONDA_GMP=5.1;CONDA_GSL=1.16;CONDA_NCURSES=5.9;CONDA_NPY=110;CONDA_PERL=5.22.0;CONDA_PY=27;CONDA_R=3.3.1
INFO bioconda_utils.build:build(102): BIOCONDA BUILD SUCCESS /anaconda/conda-bld/linux-64/r-argparse-1.0.1-py27r3.3.1_0.tar.bz2, CONDA_BOOST=1.60;CONDA_GMP=5.1;CONDA_GSL=1.16;CONDA_NCURSES=5.9;CONDA_NPY=110;CONDA_PERL=5.22.0;CONDA_PY=27;CONDA_R=3.3.1
INFO bioconda_utils.build:build(119): BIOCONDA TEST START via mulled-build recipes/r-argparse, CONDA_BOOST=1.60;CONDA_GMP=5.1;CONDA_GSL=1.16;CONDA_NCURSES=5.9;CONDA_NPY=110;CONDA_PERL=5.22.0;CONDA_PY=27;CONDA_R=3.3.1
updating index in: /anaconda/conda-bld/linux-64
INFO bioconda_utils.build:build(124): BIOCONDA TEST SUCCESS recipes/r-argparse, CONDA_BOOST=1.60;CONDA_GMP=5.1;CONDA_GSL=1.16;CONDA_NCURSES=5.9;CONDA_NPY=110;CONDA_PERL=5.22.0;CONDA_PY=27;CONDA_R=3.3.1
INFO bioconda_utils.build:build(57): BIOCONDA BUILD START recipes/r-argparse, env: CONDA_BOOST=1.60;CONDA_GMP=5.1;CONDA_GSL=1.16;CONDA_NCURSES=5.9;CONDA_NPY=110;CONDA_PERL=5.22.0;CONDA_PY=34;CONDA_R=3.3.1
INFO bioconda_utils.build:build(102): BIOCONDA BUILD SUCCESS /anaconda/conda-bld/linux-64/r-argparse-1.0.1-py34r3.3.1_0.tar.bz2, CONDA_BOOST=1.60;CONDA_GMP=5.1;CONDA_GSL=1.16;CONDA_NCURSES=5.9;CONDA_NPY=110;CONDA_PERL=5.22.0;CONDA_PY=34;CONDA_R=3.3.1
INFO bioconda_utils.build:build(119): BIOCONDA TEST START via mulled-build recipes/r-argparse, CONDA_BOOST=1.60;CONDA_GMP=5.1;CONDA_GSL=1.16;CONDA_NCURSES=5.9;CONDA_NPY=110;CONDA_PERL=5.22.0;CONDA_PY=34;CONDA_R=3.3.1
updating index in: /anaconda/conda-bld/linux-64
INFO bioconda_utils.build:build(124): BIOCONDA TEST SUCCESS recipes/r-argparse, CONDA_BOOST=1.60;CONDA_GMP=5.1;CONDA_GSL=1.16;CONDA_NCURSES=5.9;CONDA_NPY=110;CONDA_PERL=5.22.0;CONDA_PY=34;CONDA_R=3.3.1
INFO bioconda_utils.build:build_recipes(330): BIOCONDA BUILD SUMMARY: successfully built 1 of 1 recipes

**Comment by daler** [comment]
We split independent sets of recipes (subdags) across different workers on travis-ci to speed up builds. The log you're showing is for subdag 1 where r-argparse is being built. Check [subdag 0](https://travis-ci.org/bioconda/bioconda-recipes/jobs/170787598#L493) -- looks like libsequence [worked](https://travis-ci.org/bioconda/bioconda-recipes/jobs/170787598#L498).

**Comment by molpopgen** [comment]
Thanks. That's a bit confusing to the uninitiated!

**Comment by molpopgen** [comment]
Where is an appropriate place to discuss GCC/OS X?  It looks like GCC is required for C++11 projects to pass on Travis.  That's a lame reason to use it, but current clang on OS X >= 10.10 or so has removed openmp support, again requiring GCC for projects using that.  It may be nice to get a consensus on these issues--once libsequence is in bioconda, I have lots of related packages that'll have similar issues on OS X.

**Comment by daler** [comment]
@molpopgen Sorry about that; it's definitely confusing and docs are on the list of things to work on soon.

As for gcc on osx, I know there was discussion in https://github.com/bioconda/bioconda-recipes/issues/1332 and https://github.com/bioconda/bioconda-recipes/issues/1314 but I don't know if there were any hard conclusions. For the most part we are following what continuumio and conda-forge do since we need to depend on their packages.

**Comment by molpopgen** [comment]
@daler -- thanks.  I'll take a look at those other discussions.

**Comment by molpopgen** [comment]
@bioconda/core -- this is ready for review.  I've made the final changes to this PR from my end.

**Comment by daler** [comment]
Looks good, thanks!

**Pull request merged**
