### PR TITLE
add linux-aarch64 builds for bioconductor delayedarray, s4arrays and sparsearray

### PR DESCRIPTION
**Pull request by martin-g**
Describe your pull request here

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

### General instructions

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

### Instructions for avoiding API, ABI, and CLI breakage issues
Conda is able to record and lock (a.k.a. pin) dependency versions used at build time of other recipes.
This way, one can avoid that expectations of a downstream recipe with regards to API, ABI, or CLI are violated by later changes in the recipe.
If not already present in the meta.yaml, make sure to specify `run_exports` (see [here](https://bioconda.github.io/contributor/linting.html#missing-run-exports) for the rationale and comprehensive explanation).
Add a `run_exports` section like this:

```yaml
build:
  run_exports:
    - ...

```

with `...` being one of:

| Case                             | run_exports statement                                               |
| -------------------------------- | ------------------------------------------------------------------- |
| semantic versioning              | `{{ pin_subpackage("myrecipe", max_pin="x") }}`     |
| semantic versioning (0.x.x)      | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}`   |
| known breakage in minor versions | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| known breakage in patch versions | `{{ pin_subpackage("myrecipe", max_pin="x.x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| calendar versioning              | `{{ pin_subpackage("myrecipe", max_pin=None) }}`    |

while replacing `"myrecipe"` with either `name` if a `name|lower` variable is defined in your recipe or with the lowercase name of the package in quotes.

### Bot commands for PR management

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

Note that the <code>@BiocondaBot please merge</code> command is now depreciated. Please just squash and merge instead.

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by martin-g** [comment]
@BiocondaBot please fetch artifacts

**Comment by martin-g** [comment]
@BiocondaBot please add label

**Comment by martin-g** [comment]
@aliciaaevans It seems there is some kind of a problem with the fetching of CircleCI artifacts:
```
INFO:bioconda_bot.common:the comment is: @BiocondaBot please fetch artifacts
INFO:bioconda_bot.common:contacting azure https://dev.azure.com/bioconda/bioconda-recipes/_apis/build/builds/57762/artifacts?api-version=4.1
INFO:bioconda_bot.common:zip name is LinuxArtifacts url https://artprodsu6weu.artifacts.visualstudio.com/A27bcc0f9-b22c-4418-83d8-514809b37fb2/25074ded-3133-43ca-af80-895ab87b53cb/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL2Jpb2NvbmRhL3Byb2plY3RJZC8yNTA3NGRlZC0zMTMzLTQzY2EtYWY4MC04OTVhYjg3YjUzY2IvYnVpbGRJZC81Nzc2Mi9hcnRpZmFjdE5hbWUvTGludXhBcnRpZmFjdHM1/content?format=zip
INFO:bioconda_bot.common:zip name is OSXArtifacts url https://artprodsu6weu.artifacts.visualstudio.com/A27bcc0f9-b22c-4418-83d8-514809b37fb2/25074ded-3133-43ca-af80-895ab87b53cb/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL2Jpb2NvbmRhL3Byb2plY3RJZC8yNTA3NGRlZC0zMTMzLTQzY2EtYWY4MC04OTVhYjg3YjUzY2IvYnVpbGRJZC81Nzc2Mi9hcnRpZmFjdE5hbWUvT1NYQXJ0aWZhY3Rz0/content?format=zip
Traceback (most recent call last):
  File "/usr/local/bin/bioconda-bot", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/bioconda_bot/cli.py", line 81, in main
    parsed_args.run_command()
  File "/usr/local/lib/python3.8/site-packages/bioconda_bot/cli.py", line 12, in run_command
    run(main_())
  File "/usr/local/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/site-packages/bioconda_bot/comment.py", line 233, in main
    await artifact_checker(session, issue_number)
  File "/usr/local/lib/python3.8/site-packages/bioconda_bot/comment.py", line 150, in artifact_checker
    await make_artifact_comment(session, issue_number, pr_info["head"]["sha"])
  File "/usr/local/lib/python3.8/site-packages/bioconda_bot/comment.py", line 27, in make_artifact_comment
    artifactDict = await fetch_pr_sha_artifacts(session, pr, sha)
  File "/usr/local/lib/python3.8/site-packages/bioconda_bot/common.py", line 247, in fetch_pr_sha_artifacts
    zipFiles = await fetch_circleci_artifacts(session, workflowId)
  File "/usr/local/lib/python3.8/site-packages/bioconda_bot/common.py", line 169, in fetch_circleci_artifacts
    for artifact in res_object["items"]:
KeyError: 'items'
```
https://github.com/bioconda/bioconda-recipes/actions/runs/8940540384/job/24558859545

**Comment by aliciaaevans** [comment]
@martin-g Looks like an authentication issue. I'm checking to see if something changed on CircleCI or a token expired.

**Comment by aliciaaevans** [comment]
Just testing artifact fetching in the comment. Still need to release bioconda-utils to fix merging.

**Comment by aliciaaevans** [comment]
@BiocondaBot please fetch artifacts

**Pull request merged**
