### PR TITLE
add skewer 0.1.126 (stable release)

### PR DESCRIPTION
**Pull request by dakl**
This adds skewer 0.1.126.

### CODE REVIEW

**Comment by dakl** [comment]
@druvus Anything else needed here that I'm missing?

**Comment by johanneskoester** [comment]
Can you enable the test case?

**Comment by dakl** [comment]
The problem is that both `skewer`, `skewer -h` and `skewer -v` have nonzero exit codes so they can't really be used to test the build. I could do something like `skewer 2>&1|grep "skewer (0.1.126)"` which seems to work (i.e. returns 0) locally, but does looks bit strange when `conda build`ing. 

```
Fetching packages ...
skewer-0.1.126 100% |################################| Time: 0:00:00  56.97 MB/s
Extracting packages ...
[      COMPLETE      ]|################################################################################################| 100%
Linking packages ...
[      COMPLETE      ]|################################################################################################| 100%
+ skewer
+ grep 'skewer (0.1.126)'
skewer (0.1.126): No input file specified
TEST END: skewer-0.1.126-0
# If you want to upload this package to anaconda.org later, type:
#
# $ anaconda upload /Users/dankle/miniconda2/conda-bld/osx-64/skewer-0.1.126-0.tar.bz2
#
# To have conda build upload to anaconda.org automatically, use
# $ conda config --set anaconda_upload yes
```

I have a PR in the skewer repo (see relipmoc/skewer#26) to fix this, but it hasn't been merged yet. Perhaps the workaround is OK until then? Let me know what you prefer.

**Comment by johanneskoester** [comment]
Yes, the workaround you propose is good. We did that before for other misbehaving tools. Feel free to hide the output of the test by piping to ``/dev/null``.

**Comment by dakl** [comment]
Updated.

**Pull request merged**
