### PR TITLE
Funannotate update build for some missing dependencies

### PR DESCRIPTION
**Pull request by nextgenusfs**
Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it. Note that if you are not already a member of the bioconda project (meaning that you can't add this label), please ping `@bioconda/core` so that your PR can be reviewed and merged (please note if you'd like to be added to the bioconda project). Please see https://github.com/bioconda/bioconda-recipes/issues/15332 for more details.

* [ ] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [ ] This PR adds a new recipe.
* [ ] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by nextgenusfs** [comment]
Hi @dpryan79, I was able to get the Trinity dependecy pinned properly, apparently this is sufficient:
```
- trinity >=2.8.5=h8b12597_5  # [linux]
```
This looks like working, however, it doesn't seem to be rebuilding the OSX image -- is this because it is `noarch`??  This would explain why our first build "worked" although on install failed on OSX -- ie was not following the `# [linux]` selector.

The linter complains if I don't label it `noarch`, is there a way around this which will make it build linux and OSX packages separately?

Below is from OSX bioconda-test.
```
#!/bin/bash --login -eo pipefail
bioconda-utils build recipes config.yml \
--git-range master HEAD
08:47:50 BIOCONDA INFO Considering total of 6879 recipes.
08:47:51 BIOCONDA INFO Constraining to 1 git modified recipes (funannotate).
08:47:51 BIOCONDA INFO Processing 1 recipes (funannotate).
08:47:51 BIOCONDA INFO Generating DAG
08:47:51 BIOCONDA INFO 1 recipes to build and test: 
funannotate
08:47:51 BIOCONDA INFO Determining expected packages for recipes/funannotate
Setting build platform. This is only useful when pretending to be on another platform, such as for rendering necessary dependencies on a non-native platform. I trust that you know what you're doing.
08:47:51 CONDA_BUILD WARNING Setting build platform. This is only useful when pretending to be on another platform, such as for rendering necessary dependencies on a non-native platform. I trust that you know what you're doing.
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
08:47:51 CONDA_BUILD WARNING No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
Adding in variants from internal_defaults
08:47:51 CONDA_BUILD INFO Adding in variants from internal_defaults
Adding in variants from /Users/distiller/project/miniconda/conda_build_config.yaml
08:47:51 CONDA_BUILD INFO Adding in variants from /Users/distiller/project/miniconda/conda_build_config.yaml
Adding in variants from /Users/distiller/project/miniconda/lib/python3.7/site-packages/bioconda_utils/bioconda_utils-conda_build_config.yaml
08:47:51 CONDA_BUILD INFO Adding in variants from /Users/distiller/project/miniconda/lib/python3.7/site-packages/bioconda_utils/bioconda_utils-conda_build_config.yaml
Attempting to finalize metadata for funannotate
08:48:02 CONDA_BUILD INFO Attempting to finalize metadata for funannotate
Collecting package metadata: ...working... done
Solving environment: ...working... done
Collecting package metadata: ...working... done
Solving environment: ...working... done
08:49:28 BIOCONDA INFO Nothing to be done for recipe recipes/funannotate
08:49:28 BIOCONDA INFO BUILD SUMMARY: successfully built 0 of 1 recipes
```

**Comment by dpryan79** [comment]
@bioconda-bot please fetch artifacts

**Comment by dpryan79** [comment]
Package(s) built on CircleCI are ready for inspection:

Arch | Package | Repodata
-----|---------|---------
noarch | [funannotate-1.7.1-py_1.tar.bz2](https://83323-42372094-gh.circle-artifacts.com/0/tmp/artifacts/packages/noarch/funannotate-1.7.1-py_1.tar.bz2) | [repodata.json](https://83323-42372094-gh.circle-artifacts.com/0/tmp/artifacts/packages/linux-64/repodata.json)
***

You may also use `conda` to install these:

 * For packages on noarch:
```
conda install -c https://83323-42372094-gh.circle-artifacts.com/0/tmp/artifacts/packages <package name>
```
***

Docker image(s) built:

Package | Tag | Install with `docker`
--------|-----|----------------------
[funannotate](https://83323-42372094-gh.circle-artifacts.com/0/tmp/artifacts/images/funannotate%3A1.7.1--py_1.tar.gz) | 1.7.1--py_1 | <details><summary>show</summary>`curl "https://83323-42372094-gh.circle-artifacts.com/0/tmp/artifacts/images/funannotate%3A1.7.1--py_1.tar.gz" \| gzip -dc \| docker load`

**Comment by dpryan79** [comment]
Yes, since it's a noarch package it's not built on OSX. Having said that, the run-time selectors should really still be maintained (that's the case for python selectors, but maybe architecture selectors are ignore...which I would consider a conda bug).

**Comment by dpryan79** [comment]
Yeah, it looks like the architecture selectors are stripped in noarch packages. Can you confirm this on a mac using the `conda install` command posted above by the bot (masquerading as me)?

**Comment by nextgenusfs** [comment]
Yes -- I can try it, won't be until tonight as don't have access to my mac until I get home.  Thefetch artifacts looks like a useful trick!

**Comment by dpryan79** [comment]
Yeah, I just implemented that today using github actions :) It used to be fully automated by an AWS instance, but that's been down for quite a while.

**Comment by nextgenusfs** [comment]
Seems like a great feature -- as I never know how to test the package prior to merging it.  This will give me a chance to test this package on centOS as well.  Funannotate is a beautiful nightmare.... the dependencies are brutal. But that pretty much sums up genome annotation.....

**Comment by nextgenusfs** [comment]
Looks like `noarch` does not work with selectors according to this: https://docs.conda.io/projects/conda/en/latest/user-guide/concepts/packages.html#noarch-python

**Comment by nextgenusfs** [comment]
@bioconda-bot please fetch artifacts

**Comment by dpryan79** [comment]
Package(s) built on CircleCI are ready for inspection:

Arch | Package | Repodata
-----|---------|---------
linux-64 | [funannotate-1.7.1-py27_1.tar.bz2](https://83464-42372094-gh.circle-artifacts.com/0/tmp/artifacts/packages/linux-64/funannotate-1.7.1-py27_1.tar.bz2) | [repodata.json](https://83464-42372094-gh.circle-artifacts.com/0/tmp/artifacts/images/funannotate%3A1.7.1--py27_1.tar.gz)
osx-64 | [funannotate-1.7.1-py27_1.tar.bz2](https://83467-42372094-gh.circle-artifacts.com/0/tmp/artifacts/packages/osx-64/funannotate-1.7.1-py27_1.tar.bz2) | [repodata.json](https://83467-42372094-gh.circle-artifacts.com/0/tmp/artifacts/packages/noarch/repodata.json)
***

You may also use `conda` to install these:

 * For packages on linux-64:
```
conda install -c https://83464-42372094-gh.circle-artifacts.com/0/tmp/artifacts/packages <package name>
```
 * For packages on osx-64:
```
conda install -c https://83467-42372094-gh.circle-artifacts.com/0/tmp/artifacts/packages <package name>
```
***

Docker image(s) built:

Package | Tag | Install with `docker`
--------|-----|----------------------
[funannotate](https://83464-42372094-gh.circle-artifacts.com/0/tmp/artifacts/images/funannotate%3A1.7.1--py27_1.tar.gz) | 1.7.1--py27_1 | <details><summary>show</summary>`curl "https://83464-42372094-gh.circle-artifacts.com/0/tmp/artifacts/images/funannotate%3A1.7.1--py27_1.tar.gz" \| gzip -dc \| docker load`

**Comment by nextgenusfs** [comment]
@bioconda-bot please fetch artifacts

**Comment by dpryan79** [comment]
Package(s) built on CircleCI are ready for inspection:

Arch | Package | Repodata
-----|---------|---------
linux-64 | [funannotate-1.7.1-py27_1.tar.bz2](https://83471-42372094-gh.circle-artifacts.com/0/tmp/artifacts/packages/linux-64/funannotate-1.7.1-py27_1.tar.bz2) | [repodata.json](https://83471-42372094-gh.circle-artifacts.com/0/tmp/artifacts/images/funannotate%3A1.7.1--py27_1.tar.gz)
osx-64 | [funannotate-1.7.1-py27_1.tar.bz2](https://83472-42372094-gh.circle-artifacts.com/0/tmp/artifacts/packages/osx-64/funannotate-1.7.1-py27_1.tar.bz2) | [repodata.json](https://83472-42372094-gh.circle-artifacts.com/0/tmp/artifacts/packages/noarch/repodata.json)
***

You may also use `conda` to install these:

 * For packages on linux-64:
```
conda install -c https://83471-42372094-gh.circle-artifacts.com/0/tmp/artifacts/packages <package name>
```
 * For packages on osx-64:
```
conda install -c https://83472-42372094-gh.circle-artifacts.com/0/tmp/artifacts/packages <package name>
```
***

Docker image(s) built:

Package | Tag | Install with `docker`
--------|-----|----------------------
[funannotate](https://83471-42372094-gh.circle-artifacts.com/0/tmp/artifacts/images/funannotate%3A1.7.1--py27_1.tar.gz) | 1.7.1--py27_1 | <details><summary>show</summary>`curl "https://83471-42372094-gh.circle-artifacts.com/0/tmp/artifacts/images/funannotate%3A1.7.1--py27_1.tar.gz" \| gzip -dc \| docker load`

**Comment by nextgenusfs** [comment]
So not sure why this is happening, the OSX build fails with some placeholder length issue with one (or more?) of the dependencies:
```
21:54:43 BIOCONDA INFO (ERR) Build prefix failed with prefix length 255
21:54:43 BIOCONDA INFO (ERR) WARNING:conda_build.environ:Build prefix failed with prefix length 255
21:54:43 BIOCONDA INFO (ERR) Error was:
21:54:43 BIOCONDA INFO (ERR) WARNING:conda_build.environ:Error was:
21:54:43 BIOCONDA INFO (ERR) Placeholder of length '80' too short in package /Users/distiller/project/miniconda/conda-bld/funannotate_1574401588234/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin/Rscript.
21:54:43 BIOCONDA INFO (ERR) The package must be rebuilt with conda-build > 2.0.
21:54:43 BIOCONDA INFO (ERR) WARNING:conda_build.environ:Placeholder of length '80' too short in package /Users/distiller/project/miniconda/conda-bld/funannotate_1574401588234/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin/Rscript.
21:54:43 BIOCONDA INFO (ERR) The package must be rebuilt with conda-build > 2.0.
21:54:43 BIOCONDA INFO (ERR) One or more of your package dependencies needs to be rebuilt with a longer prefix length.
21:54:43 BIOCONDA INFO (ERR) WARNING:conda_build.environ:One or more of your package dependencies needs to be rebuilt with a longer prefix length.
21:54:43 BIOCONDA INFO (ERR) Falling back to legacy prefix length of 80 characters.
21:54:43 BIOCONDA INFO (ERR) WARNING:conda_build.environ:Falling back to legacy prefix length of 80 characters.
21:54:43 BIOCONDA INFO (ERR) Your package will not install into prefixes > 80 characters.
21:54:43 BIOCONDA INFO (ERR) WARNING:conda_build.environ:Your package will not install into prefixes > 80 characters.
21:54:44 BIOCONDA INFO (ERR) Traceback (most recent call last):
21:54:44 BIOCONDA INFO (ERR)   File "/Users/distiller/project/miniconda/lib/python3.7/site-packages/conda/core/path_actions.py", line 423, in verify
21:54:44 BIOCONDA INFO (ERR)     self.file_mode)
21:54:44 BIOCONDA INFO (ERR)   File "/Users/distiller/project/miniconda/lib/python3.7/site-packages/conda/core/portability.py", line 59, in update_prefix
21:54:44 BIOCONDA INFO (ERR)     update_file_in_place_as_binary(realpath(path), _update_prefix)
21:54:44 BIOCONDA INFO (ERR)   File "/Users/distiller/project/miniconda/lib/python3.7/site-packages/conda/gateways/disk/update.py", line 42, in update_file_in_place_as_binary
21:54:44 BIOCONDA INFO (ERR)     fh.write(callback(data))
21:54:44 BIOCONDA INFO (ERR)   File "/Users/distiller/project/miniconda/lib/python3.7/site-packages/conda/core/portability.py", line 41, in _update_prefix
21:54:44 BIOCONDA INFO (ERR)     data = replace_prefix(mode, original_data, placeholder, new_prefix)
21:54:44 BIOCONDA INFO (ERR)   File "/Users/distiller/project/miniconda/lib/python3.7/site-packages/conda/core/portability.py", line 66, in replace_prefix
21:54:44 BIOCONDA INFO (ERR)     data = binary_replace(data, placeholder.encode('utf-8'), new_prefix.encode('utf-8'))
21:54:44 BIOCONDA INFO (ERR)   File "/Users/distiller/project/miniconda/lib/python3.7/site-packages/conda/core/portability.py", line 95, in binary_replace
21:54:44 BIOCONDA INFO (ERR)     data = pat.sub(replace, data)
21:54:44 BIOCONDA INFO (ERR)   File "/Users/distiller/project/miniconda/lib/python3.7/site-packages/conda/core/portability.py", line 90, in replace
21:54:44 BIOCONDA INFO (ERR)     raise _PaddingError
21:54:44 BIOCONDA INFO (ERR) conda.core.portability._PaddingError
```

**Comment by nextgenusfs** [comment]
Despite the failure, this command actually builds a functional environment?
```
conda create -n test2 -c https://83472-42372094-gh.circle-artifacts.com/0/tmp/artifacts/packages funannotate
```

**Comment by nextgenusfs** [comment]
@bioconda-bot please fetch artifacts

**Comment by dpryan79** [comment]
Package(s) built on CircleCI are ready for inspection:

Arch | Package | Repodata
-----|---------|---------
linux-64 | [funannotate-1.7.1-py27_1.tar.bz2](https://83593-42372094-gh.circle-artifacts.com/0/tmp/artifacts/packages/linux-64/funannotate-1.7.1-py27_1.tar.bz2) | [repodata.json](https://83593-42372094-gh.circle-artifacts.com/0/tmp/artifacts/images/funannotate%3A1.7.1--py27_1.tar.gz)
osx-64 | [funannotate-1.7.1-py27_1.tar.bz2](https://83606-42372094-gh.circle-artifacts.com/0/tmp/artifacts/packages/osx-64/funannotate-1.7.1-py27_1.tar.bz2) | [repodata.json](https://83606-42372094-gh.circle-artifacts.com/0/tmp/artifacts/packages/noarch/repodata.json)
***

You may also use `conda` to install these:

 * For packages on linux-64:
```
conda install -c https://83593-42372094-gh.circle-artifacts.com/0/tmp/artifacts/packages <package name>
```
 * For packages on osx-64:
```
conda install -c https://83606-42372094-gh.circle-artifacts.com/0/tmp/artifacts/packages <package name>
```
***

Docker image(s) built:

Package | Tag | Install with `docker`
--------|-----|----------------------
[funannotate](https://83593-42372094-gh.circle-artifacts.com/0/tmp/artifacts/images/funannotate%3A1.7.1--py27_1.tar.gz) | 1.7.1--py27_1 | <details><summary>show</summary>`curl "https://83593-42372094-gh.circle-artifacts.com/0/tmp/artifacts/images/funannotate%3A1.7.1--py27_1.tar.gz" \| gzip -dc \| docker load`

**Comment by nextgenusfs** [comment]
@dpryan79 I think I've finally managed to get it working.  Thanks for your artifacts trick, that pretty much saved me.  This is now working on both linux and OSX.  Would it be possible to remove the funannotate_build0 as its not functional for OSX and missing some deps for linux as well. 

I appreciate all your help and continued maintenance/improvement of bioconda.

**Comment by dpryan79** [comment]
@nextgenusfs It's been removed. It only had 12 downloads so far, most of which were likely you, so this shouldn't break anyone's environment (especially if the dependencies were wrong). Thanks for fixing this!

**Pull request merged**
