### PR TITLE
Targetfinder

### PR DESCRIPTION
**Pull request by HassanAmr**
* [x] I have read the guidelines above.
* [x] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by bgruening** [comment]
```
opt/conda/conda-bld/test_tmp/run_test.sh: /opt/conda/conda-bld/_t_env/bin/targetfinder.pl: /usr/bin/perl: bad interpreter: No such file or directory
```

You need to change the shebang to `/usr/bin/env perl`.
Also please rebase this PR against master.

**Comment by bgruening** [comment]
nearly, but the rebase went wrong ...

**Comment by HassanAmr** [comment]
Can I delete the branch, and redo it?

**Comment by bgruening** [comment]
Sure!

**Pull request closed without merging**
