### PR TITLE
Bumped VEP subversion

### PR DESCRIPTION
**Pull request by matthdsm**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by matthdsm** [comment]
@bioconda/core 
Can anyone with acces to the travis logs tell me what went wrong? The logs I'm seeing show no relevant info regarding the package, so I think it might be a travis issue. Anyone any idea?

Thanks!
M

**Comment by matthdsm** [comment]
anyone? When I try to build locally it get the message `'CONDA_HTSLIB' is undefined`

M

**Comment by johanneskoester** [comment]
The logs are public. I cannot see more than you. This is indeed weird. You should try locally. You can either run bioconda-utils directly, or use simulate-travis.py. However, here it might be a problem with bioconda-utils. Hence I suggest to try conda-build alone first. You need to specify `CONDA_HTSLIB` at the command line, i.e.:
```
CONDA_HTSLIB=1.4 conda build recipes/ensembl-vep
```

**Comment by matthdsm** [comment]
Hi @johanneskoester 

I've tried building the package locally, but I keep getting issues during the build. Any further ideas?
conda build says the package requirements are in conflict with itself..

M

**Comment by johanneskoester** [comment]
@matthdsm Do you have a new branch or are you giving up on this?

**Comment by matthdsm** [comment]
Hi Johannes, 

There was a newer subrelease of the software available, so I closed and opened a new PR (#5036),
which built cleanly for some reason.

Problem solved as far as I'm concerned. Thanks for following up!

Matthias

**Comment by johanneskoester** [comment]
Great! Maybe it was because of one of the many recent fixes to bioconda-utils.

**Pull request closed without merging**
