### PR TITLE
Update fastq-filter to 0.1.1

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`fastq-filter`](https://bioconda.github.io/recipes/fastq-filter/README.html): **0.1.0** &rarr; **0.1.1**

[install with bioconda](http://bioconda.github.io/recipes/fastq-filter/README.html) [Conda](https://anaconda.org/bioconda/fastq-filter/files)

Info | Link
-----|-----
Recipe | [`recipes/fastq-filter`](https://github.com//bioconda/bioconda-recipes/tree/bump/fastq_filter/recipes/fastq-filter) (click to view/edit other files)
Releases |[https://pypi.org/pypi/fastq-filter/json](https://pypi.org/pypi/fastq-filter/json)
Recipe Maintainer(s) | @rhpvorderman

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Review by rhpvorderman — APPROVED** [review]

**Comment by rhpvorderman** [comment]
@BiocondaBot please merge

**Comment by rhpvorderman** [comment]
@BiocondaBot please merge

**Comment by rhpvorderman** [comment]
@bioconda/build-system 
Can you help me out with this error?

**Comment by dpryan79** [comment]
@rhpvorderman We have yet to update the bot to handle artifacts on azure, so in the interim just hit merge.

**Comment by rhpvorderman** [comment]
@dpryan79 Thanks. But now there is no biocontainer on https://quay.io/biocontainers/fastq-filter. How can I fix that?

**Pull request merged**
