### PR TITLE
isPcr 33 (new recipe)

### PR DESCRIPTION
**Pull request by tseemann**
Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it. Note that if you are not already a member of the bioconda project (meaning that you can't add this label), please ping `@bioconda/core` so that your PR can be reviewed and merged (please note if you'd like to be added to the bioconda project). Please see https://github.com/bioconda/bioconda-recipes/issues/15332 for more details.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by tseemann** [comment]
```
06:50:07 BIOCONDA INFO (OUT) $BUILD_PREFIX/bin/x86_64-conda_cos6-linux-gnu-cc -O -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -I$PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/ispcr-33 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_GNU_SOURCE -DMACHTYPE_unix -DJK_WARN -Wall -Werror -I../inc -I../../inc -I../../../inc -I../../../../inc  -c aliType.c
06:50:07 BIOCONDA INFO (OUT) aliType.c:5:19: error: 'rcsid' defined but not used [-Werror=unused-const-variable=]
06:50:07 BIOCONDA INFO (OUT)  static char const rcsid[] = "$Id: aliType.c,v 1.4 2003/05/06 07:33:41 kate Exp $";
06:50:07 BIOCONDA INFO (OUT)                    ^~~~~
06:50:07 BIOCONDA INFO (OUT) cc1: all warnings being treated as errors
```

I thought I removed the `-Werror` directive in the patch file?

**Comment by dpryan79** [comment]
I've started fixing things.

**Comment by tseemann** [comment]
@dpryan79 the Makefile setup is very convoluted; it involves `$HOME`.

**Comment by dpryan79** [comment]
Kent's tools are always a bit wonky to get to build :(

**Comment by dpryan79** [comment]
@tseemann This should be ready to go now.

**Comment by dpryan79** [comment]
@bioconda-bot merge

**Pull request merged**
