### PR TITLE
rebuild perl-moose

### PR DESCRIPTION
**Pull request by druvus**
:information_source:
If this is your first pull request to Bioconda please ping `@bioconda/core` so it can be reviewed and to request being added as a member of the Bioconda team. Members of the Bioconda team are able to merge their own pull requests once tests and linting have passed.

----------------

* [ ] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [ ] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by druvus** [comment]
@npavlovikj , @jerowe and @acaprez: anyone knows how to fix this compilation error?

```
+GXX=$BUILD_PREFIX/bin/x86_64-conda_cos6-linux-gnu-g++

/opt/conda/conda-bld/perl-moose_1556998221699/_build_env/bin/x86_64-conda_cos6-linux-gnu-ld: unrecognized option '-Wl,-O2'

/opt/conda/conda-bld/perl-moose_1556998221699/_build_env/bin/x86_64-conda_cos6-linux-gnu-ld: use the --help option for usage information

Couldn't execute /opt/conda/conda-bld/perl-moose_1556998221699/_build_env/bin/x86_64-conda_cos6-linux-gnu-ld HASCOMPILER7Unk/TESTYICR.o -o HASCOMPILER7Unk/TESTYICR.so -shared -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-rpath,/opt/conda/conda-bld/perl-moose_1556998221699/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib -Wl,-rpath-link,/opt/conda/conda-bld/perl-moose_1556998221699/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib -L/opt/conda/conda-bld/perl-moose_1556998221699/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib --sysroot /opt/conda/conda-bld/perl-moose_1556998221699/_build_env/bin/..//x86_64-conda_cos6-linux-gnu/sysroot -fstack-protector-strong : Inappropriate ioctl for device at Makefile.PL line 12.

This distribution requires a working compiler at Makefile.PL line 12.

```

**Comment by acaprez** [comment]
It looks like it needs a C compiler so add`{{ compiler('c') }}` to the build requirements, and then add the line `export LD=${CC}` to the start of the `build.sh`.

**Comment by druvus** [comment]
@bioconda-bot recheck

**Comment by druvus** [comment]
thanks @acaprez !!

**Pull request merged**
