### PR TITLE
Update tabix to 1.11 (metapackage)

### LINKED ISSUE #23404: Please retire tabix
The tabix recipe (see https://github.com/bioconda/bioconda-recipes/blob/master/recipes/tabix/0.2.6/meta.yaml) uses legacy copy of tabix / bgzip here: https://github.com/samtools/tabix.  This package hasn't been supported for nearly a decade.  It has been replaced by bgzip and tabix binaries in htslib: https://github.com/samtools/htslib which have since had bug fixes and some major performance improvements.

There are several packages with the tabix recipe as dependencies.   Please consider removing this recipe and encouraging the users to switch to htslib (most of which already do have it as a dependency anyway).

Note this package is installed quite a lot - it's had 80K installs.

### PR DESCRIPTION
**Pull request by kpalin**
Updating tabix to 2020:s

Trying to fix #23404  So updated package 'tabix' to contain nothing but a dependency on htslib. This bumps tabix by 9 years from version 0.2.6 to 1.11.  It would be nice if this would automatically follow htslib version.

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by kpalin** [comment]
@BiocondaBot please add label

**Comment by dpryan79** [comment]
Wow, there are still packages that depend on tabix. That's crazy. Yeah, let's merge this in so they stop using a crazy old version.

**Comment by dpryan79** [comment]
I made a tweak to this. It will now pull in some compatible htslib version. Maybe I'll restrict this to >=1.9 so we can ensure there are no pinnings problems.

**Comment by jmarshall** [comment]
NO, ABSOLUTELY NOT.

The `tabix` executable is provided by the htslib package in bioconda. Packages that depend on tabix should be changed to depend on htslib instead. See also #23404.

**Comment by dpryan79** [comment]
This transparently changes tabix to be htslib. We can fix the incorrect recipes in addition to this.

**Comment by dpryan79** [comment]
I'll delete the old tabix recipes so no one gets any silly ideas in a separate PR. I'll also go through and try and fix the current recipes in a third PR.

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Comment by kpalin** [comment]
Be careful deleting the old tabix:es.  There might be some packages that really depend on them.

**Comment by dpryan79** [comment]
I'm only deleting the recipes, the packages will still be there.

**Comment by jmarshall** [comment]
I confirmed that there are no bioconda packages that list dependencies on both tabix and specific old versions of samtools/bcftools/htslib — that would conflict with the htslib>=1.9 dependency in this new package.

**Pull request merged**
