### PR TITLE
Update star-fusion to 1.10.0-1

### PR DESCRIPTION
**Pull request by jhl667**
Replace STAR dependency with version 2.7.8a, as discussed in release notes here: https://github.com/STAR-Fusion/STAR-Fusion/releases/tag/v1.10.0

Also, upgrade fixes described bug:
https://github.com/alexdobin/STAR/issues/1105

### CODE REVIEW

**Comment by jhl667** [comment]
@BiocondaBot rebuild

**Comment by jhl667** [comment]
@BiocondaBot please add label

**Comment by jhl667** [comment]
@BiocondaBot please update

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
@bioconda-bot please update

**Comment by mbargull** [comment]
@BiocondaBot, please fetch artifacts

**Comment by mbargull** [comment]
@BiocondaBot, please merge

**Pull request merged**
