### PR TITLE
Add gfmix

### PR DESCRIPTION
**Pull request by robert-ervin-jones**
Adds gfmix.

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by rpetit3** [comment]
Hi @robert-ervin-jones 

Happy to help you get this added to Bioconda. I think the first thing we'll need is a license added to `gfmix`.

**Comment by robert-ervin-jones** [comment]
Hi @rpetit3

Thanks so much for the help! I will get the license added as soon as I can.

**Comment by robert-ervin-jones** [comment]
@rpetit3, do you have any suggestions for a proper test?

**Comment by rpetit3** [comment]
We can keep it pretty basic, so something like `--version` and/or `--help` outputs. More so just testing the tool executes successfully

**Comment by robert-ervin-jones** [comment]
@rpetit3, when you get a chance can you assist me in troubleshooting this?

Thanks in advance and thank you for the help thus far!

**Comment by robert-ervin-jones** [comment]
Hi @rpetit3. Thank you again for your help. I now have the license file added to the gfmix GitHub repo, but now am getting a different error that I can't figure out. Again any help would be greatly appreciated.

**Comment by rpetit3** [comment]
Looks like issue with R 
```
21:22:29 BIOCONDA INFO (OUT) Placeholder of length '80' too short in package /opt/conda/conda-bld/gfmix_1655932798915/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin/Rscript.
21:22:29 BIOCONDA INFO (OUT) The package must be rebuilt with conda-build > 2.0.
21:22:29 BIOCONDA INFO (OUT) WARNING:conda_build.environ:Placeholder of length '80' too short in package /opt/conda/conda-bld/gfmix_1655932798915/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin/Rscript.
21:22:29 BIOCONDA INFO (OUT) The package must be rebuilt with conda-build > 2.0.
```

Your run dependencies are pretty strict (e.g. `r-base=3.2.2`)  Is it possible to loosen these a little? That might help

**Comment by robert-ervin-jones** [comment]
Hi @rpetit3. Thanks again for your help so far. Do you have any more suggestions?

**Comment by rpetit3** [comment]
@BiocondaBot please fetch artifacts

**Comment by rpetit3** [comment]
@robert-ervin-jones Think you can test it out and post the results here? Let me know if you need help do that

**Comment by robert-ervin-jones** [comment]
@rpetit3 thank you so much!

Here is the result:
```bash
$ conda install -c packages gfmix-1.0.2-h87f3376_0.tar.bz2 

Downloading and Extracting Packages
############################################################################################################################################################################################################################################ | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
mkdir: cannot create directory ‘/home/conda’: Permission denied
cp: target '/home/conda/.gfmix' is not a directory
```

**Comment by rpetit3** [comment]
OK let's try replacing `$HOME` with `~/`

**Comment by robert-ervin-jones** [comment]
@BiocondaBot please fetch artifacts

**Comment by robert-ervin-jones** [comment]
@rpetit3 It's working! Thank you so, so much for your help on this as well as the other work you do on Bioconda!

**Comment by rpetit3** [comment]
@BiocondaBot please merge

**Pull request merged**
