### PR TITLE
Update pharokka to 1.7.0

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`pharokka`](https://bioconda.github.io/recipes/pharokka/README.html): **1.6.1** &rarr; **1.7.0**

[install with bioconda](http://bioconda.github.io/recipes/pharokka/README.html) [Conda](https://anaconda.org/bioconda/pharokka/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/pharokka`](https://github.com//bioconda/bioconda-recipes/tree/bump/pharokka/recipes/pharokka) (click to view/edit other files)
Summary | Fast Phage Annotation Program
Home | [https://github.com/gbouras13/pharokka](https://github.com/gbouras13/pharokka)
Releases |[https://github.com/gbouras13/pharokka/tags](https://github.com/gbouras13/pharokka/tags)
Recipe Maintainer(s) | @gbouras13
Author | @gbouras13
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by gbouras13** [comment]
I just changed the Biopython versions - v1.7.0 needs 1.80 or later, and the bcbio-gff issue requiring no later than 1.82 has been fixed.

**Comment by kbseah** [comment]
@gbouras13 thanks for the update! The bcbio-gff recipe (last updated in PR #45464) still shows `biopython <=1.81`. Should that recipe be updated too?

**Comment by gbouras13** [comment]
Hi @kbseah ,

Thanks for this - I'll just change pharokka to <=1.81, I'm not sure about bcbio-gff - I am pretty sure it will work with later versions now the issue has been resolved (based on the GitHub) but I don't maintain the recipe so don't want to touch it.

George

**Comment by kbseah** [comment]
hi @gbouras13, actually I don't think you need to put an upper limit on the biopython version, given that bcbio-gff is also a dependency here and the solver should take care of it, also if the bcbio-gff recipe is later updated.

**Comment by gbouras13** [comment]
@kbseah  I agree, but I think it would be best just leave it for now in case later versions cause some problems - I'll relax if bcbio-gff gets updated (also a lower chance of random bugs if I forget!)

George

**Review by kbseah — APPROVED** [review]
looks good to me

**Pull request merged**
