### PR TITLE
Add spectrum_utils recipe

### PR DESCRIPTION
**Pull request by bittremieux**
* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [X] This PR adds a new recipe.
* [X] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

---

New recipe for the [`spectrum_utils`](https://github.com/bittremieux/spectrum_utils) Python package containing utility functions for mass spectrometry proteomics.

Simple recipe based on the corresponding PyPI package.

This is my first recipe, so I'd appreciate a review by @bioconda/core.

### CODE REVIEW

**Comment by stain** [comment]
Thanks for contributing!

See https://bioconda.github.io/cb3.html?highlight=host%20build#the-new-host-section - I think all your dependencies can be under `host` and you should not need `pip`.

**Comment by dpryan79** [comment]
Sorry, I missed this ping. As @stain mentioned, dependencies should normally be in the `host:` section. I've changed that and also removed the `extra:` section, which isn't used by bioconda.

**Comment by bittremieux** [comment]
Thanks @stain and @dpryan79.

Possibly most of the current `host` dependencies, except Python and pip, are actually also only needed under `run` I think?

And as this is a pure Python package should I use `noarch` instead or are the mentioned [technical compatibility issues](https://bioconda.github.io/guidelines.html?highlight=noarch#id3) still present?

**Comment by dpryan79** [comment]
@bittremieux Good catch, I've taken the liberty of adding the `noarch: python` line and also fixed the pinning to python to work with it. I assume I'm correct that this was python 3 only, otherwise please fix that before merging.

**Pull request merged**
