### PR TITLE
Update medaka to 1.1.1

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`medaka`](https://bioconda.github.io/recipes/medaka/README.html): **1.0.3** &rarr; **1.1.1**

[install with bioconda](http://bioconda.github.io/recipes/medaka/README.html) [Conda](https://anaconda.org/bioconda/medaka/files)

Info | Link
-----|-----
Recipe | [`recipes/medaka`](https://github.com//bioconda/bioconda-recipes/tree/bump/medaka/recipes/medaka) (click to view/edit other files)
Releases |[https://pypi.org/pypi/medaka/json](https://pypi.org/pypi/medaka/json)
Recipe Maintainer(s) | @cjw85

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by cjw85** [comment]
This will be blocked until there is a conda package for [pyspoa](https://pypi.org/project/pyspoa/).

**Comment by bgruening** [comment]
> 18:48:06 BIOCONDA INFO (OUT) RuntimeError: `medaka` is unsupported on your version of python, please use python 3.5 or python 3.6.

@cjw85 is that true?

**Comment by cjw85** [comment]
Ahh! This is an error on our part. The main entry point has a check for the python version (I'm not sure why), as well as the `setup.py`. I will need to fix the PyPI sdist and wheels.

**Comment by cjw85** [comment]
Our internal CI is building new packages, the source distribution should appear on PyPI momentarily. I. believe the bioconda bot will pick that up and update this PR?

**Comment by cjw85** [comment]
@bgruening Can I leave this with you? I have no idea why the bot's last commit of updating the version has now made conda throw dependency resolution issues when just before everything had progressed fine all the way to running the package.

**Comment by bgruening** [comment]
@cjw85 hard pins are always tricky. I guess what happened is that the old version of tensorflow or others which you requested have not been available for the newer python version.

**Comment by bgruening** [comment]
I'm really not sure about the openblas addition, this should not be needed and probably hides another bug. I remove it and hope this works for you now without openblas.

**Comment by cjw85** [comment]
That would surely imply that they got deleted between the build that was working at the one which failed?

**Comment by cjw85** [comment]
Doesn't:

```- libopenblas ==0.3.3  # [osx]```

mean only a requirement for macOS? Its the build step in linux that started failing after a commit which wouldn't have changed anything for conda (before that commit things failed at testing of the built package).

**Comment by bgruening** [comment]
@cjw85 it seems tensorflow=2.2.0 is not available on OSX. Oo.

Linux is building now.

**Comment by cjw85** [comment]
@bgruening I don't understand, why does removing mac only dependencies and removing the mac build entirely allow the linux build to run again?

**Comment by bgruening** [comment]
> @bgruening I don't understand, why does removing mac only dependencies and removing the mac build entirely allow the linux build to run again?

No this is unrelated. I also fixed pyspoa ... those had only py38 builds generated.

**Comment by bgruening** [comment]
@BiocondaBot please fetch artifacts

**Comment by bgruening** [comment]
@cjw85 you can test the builds here if you like and merge.

**Review by bgruening — APPROVED** [review]

**Pull request merged**
