### PR TITLE
Upgrade pysam to 0.9.1

### PR DESCRIPTION
**Pull request by kyleabeauchamp**
* [x] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by kyleabeauchamp** [comment]
cc @AndreasHeger

**Comment by kyleabeauchamp** [comment]
cc @tomkinsc @sebastian-luna-valero  @johanneskoester  @bgruening  @daler @champanb @etal

**Comment by kyleabeauchamp** [comment]
oops meant @chapmanb

**Comment by bgruening** [comment]
Fantastic! I was trying to fix https://github.com/bioconda/bioconda-recipes/issues/1744 but never say this error. I think this is now solved :)

**Comment by kyleabeauchamp** [comment]
Just be aware that the pysam build script (setup.py) has changed a bit from 0.8.3 to 0.9 to 0.9.1, so things might not backport to 0.8.3.

**Comment by bgruening** [comment]
Yes, my main problem was that I never saw an error with pysam-8.3. Non-reproducible errors are the worst :)

**Comment by daler** [comment]
Nice! Thanks for figuring this out @kyleabeauchamp.

**Comment by tomkinsc** [comment]
Nice. Thanks, also, for preserving the sub-recipe for 0.8.3!

**Pull request merged**
