### PR TITLE
Update PlasmidFinder for better container support

### PR DESCRIPTION
**Pull request by rpetit3**
The PlasmidFinder database is small (500kb), this PR build the database so that the containers have it.

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by rpetit3** [comment]
@BiocondaBot please fetch artifacts

**Comment by rpetit3** [comment]
@BiocondaBot please fetch artifacts

**Comment by rpetit3** [comment]
@BiocondaBot please fetch artifacts

**Comment by rpetit3** [comment]
@BiocondaBot please fetch artifacts

**Comment by rpetit3** [comment]
We are all set now! Users can use the default database, or they can provide their own with `-p`


### Conda 
```
mamba create -n test-plasmidfinder -c conda-forge -c bioconda 'python>3' kma biopython tabulate cgecore blast
conda activate test-plasmidfinder
conda install LinuxArtifacts/packages/noarch/plasmidfinder-2.1.6-py310hdfd78af_1.tar.bz2
plasmidfinder.py -i ./GCF_000017085.fna -x -q

ls -lha
total 2.9M
drwxr-xr-x 3 robert_petit robert_petit 4.0K Jun 10 21:54 .
drwxr-xr-x 7 robert_petit robert_petit 4.0K Jun 10 21:53 ..
-rw-r--r-- 1 robert_petit robert_petit 2.9M Jun 10 21:53 GCF_000017085.fna
-rw-r--r-- 1 robert_petit robert_petit 4.3K Jun 10 21:54 Hit_in_genome_seq.fsa
-rw-r--r-- 1 robert_petit robert_petit 4.2K Jun 10 21:54 Plasmid_seqs.fsa
-rw-r--r-- 1 robert_petit robert_petit 3.0K Jun 10 21:54 data.json
-rw-r--r-- 1 robert_petit robert_petit  21K Jun 10 21:54 results.txt
-rw-r--r-- 1 robert_petit robert_petit  739 Jun 10 21:54 results_tab.tsv
drwxrwxr-x 2 robert_petit robert_petit 4.0K Jun 10 21:54 tmp
```

### Docker
```
mkdir docker
cd docker
docker run --rm -u $(id -u):$(id -g) -v ${PWD}:/data quay.io/biocontainers/plasmidfinder:2.1.6--py310hdfd78af_1 plasmidfinder.py -i /data/GCF_000017085.fna -tmp /data/ -o /data/ -x -q

ls -lha
total 2.9M
drwxr-xr-x 3 robert_petit robert_petit 4.0K Jun 10 21:48 .
drwxr-xr-x 7 robert_petit robert_petit 4.0K Jun 10 21:53 ..
-rw-r--r-- 1 robert_petit robert_petit 2.9M Jun 10 21:48 GCF_000017085.fna
-rw-r--r-- 1 robert_petit robert_petit 4.3K Jun 10 21:55 Hit_in_genome_seq.fsa
-rw-r--r-- 1 robert_petit robert_petit 4.2K Jun 10 21:55 Plasmid_seqs.fsa
-rw-r--r-- 1 robert_petit robert_petit 3.0K Jun 10 21:55 data.json
-rw-r--r-- 1 robert_petit robert_petit  21K Jun 10 21:55 results.txt
-rw-r--r-- 1 robert_petit robert_petit  739 Jun 10 21:55 results_tab.tsv
drwxrwxr-x 2 robert_petit robert_petit 4.0K Jun 10 21:48 tmp
```

### Docker with `--entrypoint /bin/bash`
```
mkdir entrypoint
cd entrypoint/
docker run --rm -u $(id -u):$(id -g) --entrypoint /bin/bash -v ${PWD}:/data quay.io/biocontainers/plasmidfinder:2.1.6--py310hdfd78af_1 -c "plasmidfinder.py -i /data/GCF_000017085.fna -tmp /d
ata/ -o /data/ -x -q"

ls -lha
total 2.9M
drwxr-xr-x 3 robert_petit robert_petit 4.0K Jun 10 21:56 .
drwxr-xr-x 7 robert_petit robert_petit 4.0K Jun 10 21:56 ..
-rw-r--r-- 1 robert_petit robert_petit 2.9M Jun 10 21:56 GCF_000017085.fna
-rw-r--r-- 1 robert_petit robert_petit 4.3K Jun 10 21:56 Hit_in_genome_seq.fsa
-rw-r--r-- 1 robert_petit robert_petit 4.2K Jun 10 21:56 Plasmid_seqs.fsa
-rw-r--r-- 1 robert_petit robert_petit 3.0K Jun 10 21:56 data.json
-rw-r--r-- 1 robert_petit robert_petit  21K Jun 10 21:56 results.txt
-rw-r--r-- 1 robert_petit robert_petit  739 Jun 10 21:56 results_tab.tsv
drwxrwxr-x 2 robert_petit robert_petit 4.0K Jun 10 21:56 tmp
```

### Check results match
```
md5sum conda/results_tab.tsv docker/results_tab.tsv entrypoint/results_tab.tsv
7aa17dc82d1efd058422d8e0cc45db1a  conda/results_tab.tsv
7aa17dc82d1efd058422d8e0cc45db1a  docker/results_tab.tsv
7aa17dc82d1efd058422d8e0cc45db1a  entrypoint/results_tab.tsv
```

**Comment by rpetit3** [comment]
@BiocondaBot please add label

**Review by bgruening — APPROVED** [review]
Very cool! Thanks @rpetit3

**Comment by bgruening** [comment]
@BiocondaBot please merge

**Comment by rpetit3** [comment]
Thank you! @bgruening

**Comment by rpetit3** [comment]
@BiocondaBot please merge

**Pull request merged**
