### PR TITLE
Update chado-tools to v0.0.5

### PR DESCRIPTION
**Pull request by corburn**
* [ ] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [ ] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by bgruening** [comment]
ping @abretaud

**Comment by corburn** [comment]
@bgruening did I miss something?

**Comment by bgruening** [comment]
Oh no. Everything is perfect. I just though @abretaud might be interested in this :) Sorry.

**Comment by bgruening** [comment]
Thanks a lot as usual!!!

**Pull request merged**
