### PR TITLE
Update ncbimeta to 0.6.6

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`ncbimeta`](https://bioconda.github.io/recipes/ncbimeta/README.html): **0.6.5** &rarr; **0.6.6**

[install with bioconda](http://bioconda.github.io/recipes/ncbimeta/README.html) [Conda](https://anaconda.org/bioconda/ncbimeta/files)

Info | Link
-----|-----
Recipe | [`recipes/ncbimeta`](https://github.com//bioconda/bioconda-recipes/tree/bump/ncbimeta/recipes/ncbimeta) (click to view/edit other files)
Releases |[https://github.com/ktmeaton/NCBImeta/tags](https://github.com/ktmeaton/NCBImeta/tags)
Author | `@ktmeaton`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by ktmeaton** [comment]
Hello! I see the ```test-linux``` check is failing due to docker-related issues with:

```
Error response from daemon: Get https://quay.io/v2/: EOF
```

Is this an issue with my package, or is it a separate error within CircleCI?

Thanks!

**Comment by druvus** [comment]
@bioconda-bot please rebuild

**Comment by druvus** [comment]
Restarted the test. Several packages saw the same error during the day.

**Comment by ktmeaton** [comment]
@BiocondaBot please add label

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Pull request merged**
