### PR TITLE
remove scikit-allel as it is available upstream via conda-forge

### PR DESCRIPTION
**Pull request by alimanfoo**
* [x] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [x] This PR does something else (explain below).

The package scikit-allel is now available upstream via the conda-forge channel. Removing it from bioconda so I don't have to maintain in two places.

### CODE REVIEW

**Comment by alimanfoo** [comment]
@bioconda/core could you review, this PR is intended to remove a package from bioconda.

**Comment by bgruening** [comment]
@alimanfoo is the same exact version also available via conda-forge?

**Comment by alimanfoo** [comment]
No, only versions since 0.21.2 are available via conda-forge.

**Comment by bgruening** [comment]
Ok, in this case we leave them all in bioconda but remove the recipe to redirect people to the newer conda-forge one!

Thanks @alimanfoo!

**Comment by alimanfoo** [comment]
Thank you. Just to check, this means that in future if someone does ``conda install scikit-allel`` then it will install from conda-forge even if bioconda is a higher priority channel?

**Pull request merged**
