### PR TITLE
BWA: Pin zlib and use llvm on osx

### PR DESCRIPTION
**Pull request by jtratner**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

@bgruening - pins zlib to 1.2.8 and uses llvm on osx

### CODE REVIEW

**Comment by kyleabeauchamp** [comment]
If you want the packages to rebuild, you have to increment the build number in each recipe.

**Comment by johanneskoester** [comment]
This might be superseded by my PR #6013. I have also added zlib pinning (via the env matrix).

**Comment by jtratner** [comment]
I think this is superseded by #6013, as long as it updates or deletes these
older recipes. :)

**Comment by johanneskoester** [comment]
We  have made changes to our build system (migrated from Travis CI to  Circle CI). If you would like to continue working on this PR, please  reopen this PR and update with latest upstream/master.

**Pull request closed without merging**
