### PR TITLE
Update nextstrain-cli to 4.2.0

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`nextstrain-cli`](https://bioconda.github.io/recipes/nextstrain-cli/README.html): **4.1.1** &rarr; **4.2.0**

[install with bioconda](http://bioconda.github.io/recipes/nextstrain-cli/README.html) [Conda](https://anaconda.org/bioconda/nextstrain-cli/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/nextstrain-cli`](https://github.com//bioconda/bioconda-recipes/tree/bump/nextstrain_cli/recipes/nextstrain-cli) (click to view/edit other files)
Summary | The Nextstrain command-line interface (CLI)
Home | [https://docs.nextstrain.org/projects/cli/](https://docs.nextstrain.org/projects/cli/)
Releases |[https://pypi.org/pypi/nextstrain-cli/json](https://pypi.org/pypi/nextstrain-cli/json)
Recipe Maintainer(s) | @tsibley, @corneliusroemer

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Review by alienzj — APPROVED** [review]

**Comment by alienzj** [comment]
@BiocondaBot please merge

**Comment by tsibley** [comment]
This is a bad update because it didn't include dep changes from 4.1.1 to 4.2.0, [as noted](https://github.com/bioconda/bioconda-recipes/pull/36136#issuecomment-1200060338) in the first PR that was opened, https://github.com/bioconda/bioconda-recipes/pull/36136, but then closed.

**Comment by tsibley** [comment]
Not clear how tests pass, as after installing 4.2.0 from Conda I get:

```
$ python3 -c 'import nextstrain.cli'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/tom/.conda/envs/tmp/lib/python3.10/site-packages/nextstrain/cli/__init__.py", line 16, in <module>
    from .argparse    import HelpFormatter, register_commands, register_default_command
  File "/home/tom/.conda/envs/tmp/lib/python3.10/site-packages/nextstrain/cli/argparse.py", line 9, in <module>
    from .util import format_usage
  File "/home/tom/.conda/envs/tmp/lib/python3.10/site-packages/nextstrain/cli/util.py", line 15, in <module>
    from packaging.version import parse as parse_version
ModuleNotFoundError: No module named 'packaging'
```

**Comment by tsibley** [comment]
Possibly because `test: requires:` in meta.yaml contains `augur` which has a transitive dep on `packaging`, so the test environment incidentally satisfied the tests.

**Pull request merged**
