### PR TITLE
Update biscuit recipe to include biscuit script

### PR DESCRIPTION
**Pull request by ekushele**
QC.sh script and build_biscuit_QC_assets.pl from the biscuit repository were added to the recipe.

----

@BiocondaBot please review & merge

### CODE REVIEW

**Comment by ekushele** [comment]
@dpryan79  I hope it's OK to ask for your help another time, after you really helped my [last time](https://github.com/bioconda/bioconda-recipes/pull/21615)

How can I know why the "test-linux" failed?

Thanks!

**Comment by dpryan79** [comment]
The error message is:

    build_biscuit_QC_assets.pl: /usr/bin/perl: bad interpreter: No such file or directory

The shebang needs to be patched it seems, since we can't assume that `/usr/bin/perl` exists.

**Comment by ekushele** [comment]
How can I know what the error is? Now I see it's something with macos...
Thank you very much!

**Comment by dpryan79** [comment]
The lack of an error message on OSX suggests that it didn't return with an exit status of 0 there. I'll assume that's some quirk of the platform and will change the test.

**Comment by ekushele** [comment]
So what can I do?

**Comment by dpryan79** [comment]
Find an OSX box, see what return code the problematic command is issuing and see what in the code causes that.

**Comment by ekushele** [comment]
Thanks! So now all check passed...

**Review by dpryan79 — APPROVED** [review]

**Pull request merged**
