### PR TITLE
fineRADstructure

### PR DESCRIPTION
**Pull request by lecorguille**
:information_source:
Bioconda has finished the [GCC7 migration](https://github.com/bioconda/bioconda-recipes/issues/13578). If you are dealing with C/C++ or Python package it can be that you need to rebuild other dependent packages. [Bioconda utils - update-pinning](https://bioconda.github.io/updating.html#updating-recipes-for-a-pinning-change) will assist you with that. If you have any questions please use [issue 13578](https://github.com/bioconda/bioconda-recipes/issues/13578).

----------------

* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [X] This PR adds a new recipe.
* [X] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by dpryan79** [comment]
Thanks @lecorguille!

**Comment by lecorguille** [comment]
Thanks to you for the review!

**Comment by lecorguille** [comment]
@dpryan79 Do you know why the package isn't available:
```
$ conda create -n fineradstructure-0.3.2r109 fineradstructure
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - fineradstructure

Current channels:

  - https://conda.anaconda.org/bioconda/linux-64
  - https://conda.anaconda.org/bioconda/noarch
  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/linux-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch
```

**Comment by dpryan79** [comment]
It probably wasn't through the cache yet. It's appearing now from what I can see: https://anaconda.org/bioconda/fineradstructure/files

**Comment by lecorguille** [comment]
Oki, I saw the files at the moment but didn't manage to install it.
I wasn't enough patient. Now, it's ok. Thanks you for your time.

**Pull request merged**
