### PR TITLE
Update planemo to 0.72.0

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`planemo`](https://bioconda.github.io/recipes/planemo/README.html): **0.70.0** &rarr; **0.72.0**

[install with bioconda](http://bioconda.github.io/recipes/planemo/README.html) [Conda](https://anaconda.org/bioconda/planemo/files)

Info | Link
-----|-----
Recipe | [`recipes/planemo`](https://github.com//bioconda/bioconda-recipes/tree/bump/planemo/recipes/planemo) (click to view/edit other files)
Releases |[https://pypi.org/pypi/planemo/json](https://pypi.org/pypi/planemo/json)

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by nsoranzo** [comment]
Unfortunately we still need `galaxy-tool-util >=20.9.0.dev2` in the run requirements , but that's not on bioconda because it's still a pre-release.

**Comment by fubar2** [comment]
Forgive a silly question but with the 20.09 release will conda and pypi galaxy-tool-util magically update by any chance?

**Comment by nsoranzo** [comment]
@fubar2 It's not something automated at the moment unfortunately, although `galaxy-tool-util` usually is the galaxy-* package which has more regular releases. Ping @jmchilton

**Comment by simonbray** [comment]
@bioconda-bot please fetch artifacts

**Comment by simonbray** [comment]
@bioconda-bot please merge

**Pull request merged**
