### PR TITLE
Update odgi to 0.4.1

### PR DESCRIPTION
**Pull request by tetron**
Update odgi to 0.4.1

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by tetron** [comment]
@BiocondaBot please add label

**Review by epruesse — DISMISSED** [review]
Please 

  - change the recipe to use 

  ```yaml
  source:
    url: https://github.com/vgteam/odgi/archive/v0.4.1.tar.gz
    sha256: "<fill this in>"
  ```

 - remove the `uses_vcs_url` part
 - remove the `{{version}}` and `set version` parts

When upstream pushes the next update, @BiocondaBot will create a PR automatically, updating version and SHA as needed.

**Comment by tetron** [comment]
I've never worked with bioconda recipes before so I hope this is right.

**Comment by tetron** [comment]
@epruesse I tried your suggestions but I had to revert.  It seems that the odgi build relies on a bunch of dependencies that are linked as git submodules.  The plain source package doesn't have the dependencies included, so the build fails:

https://app.circleci.com/pipelines/github/bioconda/bioconda-recipes/30955/workflows/ef79afa4-86a9-41c9-a840-4a3bed75f515/jobs/119589

I'm reverting this PR to the way it was with just the version number bump.  I'm neither an odgi maintainer nor a bioconda maintainer, so I'm not in a position to fix their build system, so you merge this as-is or close it (in which case I'll have to go build my own container image.)

**Comment by tetron** [comment]
Turns out it is being discussed over here https://github.com/vgteam/odgi/issues/109

**Comment by dpryan79** [comment]
@bioconda-bot please update

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Pull request merged**
