### PR TITLE
Update `sina` to build from source

### LINKED ISSUE #5194: listed sina version number is incorrect
The version number of SINA in the bioconda repository is given as 1.3.0.
(recipe: [https://github.com/bioconda/bioconda-recipes/tree/master/recipes/sina](https://github.com/bioconda/bioconda-recipes/tree/master/recipes/sina))
 However according to the [developers page](https://www.arb-silva.de/no_cache/download/archive/SINA/), that version does not exist yet.
The current stable version is 1.2.11
The most recent (unstable) beta version is 1.2.13

After installing the conda-repository version and checking it's version number (`sina --version`), I get:
`SINA v1.2.11 (revision 21227) `

So the version number should be corrected to 1.2.11, (otherwise this version may be incorrectly selected over later versions because v1.3 > e.g. 1.2.13)

### PR DESCRIPTION
**Pull request by epruesse**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).
 
fixes #5194

### CODE REVIEW

**Comment by epruesse** [comment]
@bgruening @mdehollander There you go. SINA from source. ;-)

**Comment by mdehollander** [comment]
Great! Nice job, must have been quite some work.

**Comment by epruesse** [comment]
@mdehollander Learned a lot about conda... ;-)

FYI: SINA 1.4 will have multi-threading.

**Comment by bgruening** [comment]
And we have now @epruesse as BioConda member! :)

**Pull request merged**
