### PR TITLE
Update easypqp to 0.1.7

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`easypqp`](https://bioconda.github.io/recipes/easypqp/README.html): **0.1.6** &rarr; **0.1.7**

[install with bioconda](http://bioconda.github.io/recipes/easypqp/README.html) [Conda](https://anaconda.org/bioconda/easypqp/files)

Info | Link
-----|-----
Recipe | [`recipes/easypqp`](https://github.com//bioconda/bioconda-recipes/tree/bump/easypqp/recipes/easypqp) (click to view/edit other files)
Releases |[https://pypi.org/pypi/easypqp/json](https://pypi.org/pypi/easypqp/json)

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by lkuchenb** [comment]
@bioconda/core can someone re-trigger the mac CI or is there another way to go ahead here?

**Comment by dpryan79** [comment]
OSX jobs have been having a lot of issues lately on circleci, I'm not sure why. Adding a space randomly somewhere in the file will suffice to trigger the CI again :)

**Comment by dpryan79** [comment]
@bioconda-bot please fetch artifacts

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Comment by lkuchenb** [comment]
@dpryan79 Thanks! Yes, I'm aware of the "change something" solution, I just thought there might be a cleaner way. Next time I'll just go straight for that then ;-)

**Pull request merged**
