### PR TITLE
add recipe for collect-columns

### PR DESCRIPTION
**Pull request by DavyCats**
:information_source:
Bioconda has finished the [GCC7 migration](https://github.com/bioconda/bioconda-recipes/issues/13578). If you are dealing with C/C++ or Python package it can be that you need to rebuild other dependent packages. [Bioconda utils - update-pinning](https://bioconda.github.io/updating.html#updating-recipes-for-a-pinning-change) will assist you with that. If you have any questions please use [issue 13578](https://github.com/bioconda/bioconda-recipes/issues/13578).

----------------

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by dpryan79** [comment]
This looks ready for merging, shall I add you to the bioconda team?

**Comment by DavyCats** [comment]
@dpryan79 Sure, this will still need to be merged by someone from the core team though, right? Since it's a new recipe?

**Comment by dpryan79** [comment]
Merged and invite sent, thanks! In the future you won't explicitly need someone from the core team to merge in new recipes, just tag us if you're unsure of things of a recipe has issues :)

**Comment by DavyCats** [comment]
Thanks!

**Comment by DavyCats** [comment]
@dpryan79 It seems this hasn't shown up on biocontainers yet. I'm guessing it still needs to be made visible to the public. Is this something you can do or do I need to contact someone else?

**Comment by dpryan79** [comment]
@bgruening Any clue on this? The regular recipe was uploaded correctly, but the container doesn't seem to be available.

**Comment by bgruening** [comment]
This is my way to know if those containers are used ;)

Seriously, sorry @DavyCats. It's now available.

**Comment by DavyCats** [comment]
Awesome, thank you, @bgruening! :smile:

**Pull request merged**
