### PR TITLE
Update ViennaRNA Package to upstream version 2.6.2

### PR DESCRIPTION
**Pull request by RaumZeit**
Describe your pull request here

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by RaumZeit** [comment]
@BiocondaBot please add label

**Comment by RaumZeit** [comment]
I'm sorry for adding the labels prematurely!
Could someone from the Bioconda team have a look at the error the macosx build gave here. I can't tell what the problem is from reading the log file. Maybe, the test simply has to be re-run? But I don't have privileges to do so.
Thanks in advance!

**Comment by bgruening** [comment]
> subprocess.CalledProcessError: Command '['/opt/mambaforge/envs/bioconda/conda-bld/viennarna_1686404996428/_build_env/bin/llvm-otool', '-l', '/opt/mambaforge/envs/bioconda/conda-bld/viennarna_1686404996428/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/RNAdos']' died with <Signals.SIGABRT: 6>.

This seems to be the error.

**Comment by RaumZeit** [comment]
I saw that too but couldn't make anything out of it.
Now that I checked running RNAdos myself, I found that it contained a double-free corruption problem. I fixed it in our development version and try running the test toolchain again. If everything runs fine, I'll release the patch upstream as well.

**Comment by RaumZeit** [comment]
@BiocondaBot please update

**Comment by bgruening** [comment]
@BiocondaBot please fetch artifacts

**Comment by bgruening** [comment]
@RaumZeit you can try the artifacts above if you like.

**Comment by RaumZeit** [comment]
Everything seems fine now!
But, since we release the sources for 2.6.0 on Friday last week already, the fixes now go into bugfix release 2.6.1 which will be released later today.

Should I simply close this PR and re-open a new for 2.6.1? To me that sounds like the clean way, but then bioconda would not have a 2.6.0 package...

**Pull request closed without merging**
