### PR TITLE
Add recipe for package R DHARMa

### PR DESCRIPTION
**Pull request by ColineRoyaux**
Describe your pull request here

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by bgruening** [comment]
@ColineRoyaux this package already exist in our partner channel: https://anaconda.org/conda-forge/r-dharma 

You are all set and can use it :)

**Comment by ColineRoyaux** [comment]
@bgruening I'm sorry, I don't think I understood well how different Conda channels work... I need this package for a Galaxy tool, I found it in Anaconda but it wasn't working when I tried to use it as a requirement with Planemo. So, I searched in Galaxy documentation which said that Galaxy uses either BioConda Channel or IUC Conda and I didn't find DHARMa in those channels so I thought I had to create a BioConda recipe in order to make it work ... Maybe you can help me with that ? 
Thank you very much !

**Comment by bgruening** [comment]
@ColineRoyaux Bioconda depends on conda-forge, so conda-forge should always be eneabled. And Galaxy enables conda-forge and bioconda for you. Can you point me to the tool that you are developing, I will try to have a look.

**Comment by ColineRoyaux** [comment]
@bgruening I use DHARMa package for both these tools to build the output_rate : 
    - https://github.com/ColineRoyaux/tools-ecology-1/blob/master/tools/PAMPA/PAMPA_GLM.xml 
    - https://github.com/ColineRoyaux/tools-ecology-1/blob/master/tools/PAMPA/PAMPA_GLM_SP.xml

To make it work for now I just pasted the DHARMa source code here : https://github.com/ColineRoyaux/tools-ecology-1/blob/master/tools/PAMPA/FunctPAMPAGalaxy.r 
but it's a really dirty way to do it

**Pull request closed without merging**
