### PR TITLE
Updating mosdepth

### PR DESCRIPTION
**Pull request by wdecoster**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [ ] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

Only the last commit "bumping to v0.2.2" is on mosdepth, the rest are git fuckups.

### CODE REVIEW

**Comment by wdecoster** [comment]
Do you have an idea how to solve it? Test was less successful than I hoped.

**Comment by brentp** [comment]
I did not notice the failure at first. You'll have to change the csources to checkout from the same branch as Nim (0.17.2). I have a newer build setup for this in `scripts/build.sh` in the mosdepth repo. You can probably also adjust the .diff to force it to clone the $NIM_VERSION branch of csources. I'll also get the mosdepth repo in order in this regard.

**Comment by brentp** [comment]
I updated the install.sh in the mosdepth repo so I think if you trigger the CI to run again it should work. Please let me know otherwise.

**Comment by wdecoster** [comment]
I reran the CI but it throws again same/similar error, nim related:

```
lib/system.nim(2903, 17) template/generic instantiation from here
lib/system.nim(2730, 7) Error: raised object of type ref IOError does not inherit from Exception
./scripts/install.sh: line 20: ./koch: No such file or directory
/opt/conda/conda-bld/mosdepth_1521742396671/work/mosdepth-0.2.2/nim-v0.17.2/bin/:nim-v0.17.2/bin/nim/bin::/opt/conda/conda-bld/mosdepth_1521742396671/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin:/opt/conda/conda-bld/mosdepth_1521742396671/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac:/opt/conda/conda-bld/mosdepth_1521742396671/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin:/opt/conda/bin:/opt/rh/devtoolset-2/root/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/bin:/opt/conda/conda-bld/mosdepth_1521742396671/work/mosdepth-0.2.2/nimble/src:nim-v0.17.2/bin/nim/bin::/opt/conda/conda-bld/mosdepth_1521742396671/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin:/opt/conda/conda-bld/mosdepth_1521742396671/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac:/opt/conda/conda-bld/mosdepth_1521742396671/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin:/opt/conda/bin:/opt/rh/devtoolset-2/root/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/bin
Cloning into 'nimble'...
Hint: used config file '/opt/conda/conda-bld/mosdepth_1521742396671/work/mosdepth-0.2.2/nim-v0.17.2/config/nim.cfg' [Conf]
Hint: used config file 'src/nimble.nim.cfg' [Conf]
Hint: system [Processing]
lib/system.nim(2903, 17) template/generic instantiation from here
lib/system.nim(2730, 7) Error: raised object of type ref IOError does not inherit from Exception
./scripts/install.sh: line 38: src/nimble: No such file or directory
+ cd /opt/conda/conda-bld/mosdepth_1521742396671/work/mosdepth-0.2.2
+ nimble refresh
./scripts/install.sh: line 42: nimble: command not found
```

**Comment by brentp** [comment]
I couldn't see how to restart it myself. could you retry again as I force re-tagged v0.2.2 with the update to the build script.

**Comment by wdecoster** [comment]
I believe you can only restart it as a member of the bioconda team. Hoped to save you some work by updating mosdepth, but turns out differently.

**Comment by brentp** [comment]
I used to be able to restart on the travis setup, but I didn't see how here. 

thanks for updating. I build a portable binary using holy-build-box, but I'd like to have it up-to-date in conda as well so would have had to do this at some point anyway.

**Comment by wdecoster** [comment]
For me there is a button in the top right corner:

image

The error from 9 hours ago was about incorrect sha256sum, which I have now updated and rebuilding...

**Comment by wdecoster** [comment]
And it builds ;-)

**Comment by brentp** [comment]
thanks!

**Pull request merged**
