### PR TITLE
Add zol to bioconda

### PR DESCRIPTION
**Pull request by raufs**
Recently developed zol - a set of 3 programs for large-scale targeted detection and evolutionary investigations of gene-clusters.

Based on looking at other bioconda recipes, I have put together a recipe I think should work - however this is my first time trying to contribute to a conda channel. Local testing based on the bioconda guide appeared successful, but advice on whether things could be setup better will be much appreciated! 

Link to GitRepo: https://github.com/Kalan-Lab/zol

Rauf

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by raufs** [comment]
@BiocondaBot please add label

**Comment by dpryan79** [comment]
@BiocondaBot please fetch artifacts

**Comment by raufs** [comment]
Hi, @dpryan79 @rpetit3 , thank you so much for helping maintain bioconda. I saw that in the modified meta.yaml file that the "no-arch: generic" line was removed. I have a build.sh script as well in the recipe which sets env variables and does other functions for downloading/setting up databases, will this still be run during the bioconda setup process without this line?

**Comment by dpryan79** [comment]
FYI, you probably meant "noarch" rather than "no-arch". The build.sh in conda packages is only run when the package is actually being built. It is never used when a package is actually installed by a user. If you need environment variables to be set then then you'll need to do so via an activation script: https://docs.conda.io/projects/conda-build/en/main/resources/activate-scripts.html

**Comment by dpryan79** [comment]
Ah, you have an activate script, that should be fine then. You can inspect the contents of the package here before it's merged and published if you like. That way you can double check that it's working as expected.

**Comment by dpryan79** [comment]
@BiocondaBot please fetch artifacts

**Comment by raufs** [comment]
@BiocondaBot please fetch artifacts

**Comment by raufs** [comment]
@BiocondaBot please fetch artifacts

**Comment by raufs** [comment]
@BiocondaBot please fetch artifacts

**Comment by dpryan79** [comment]
Azure currently has issues, so all testing is down. We've contacted them.

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
From my standpoint this is ready for merging whenever you're happy with things.

**Comment by raufs** [comment]
Thank you Devon! Appreciate the adjustment suggestions and indeed the double install seems unnecessary.

**Comment by dpryan79** [comment]
@raufs Shall I add you to bioconda in case you want to maintain this package more easily?

**Comment by raufs** [comment]
Sure that would be great!

Thanks again!
Rauf

**Comment by dpryan79** [comment]
The OSX build should show up later today. There appears to have been an issue on the github actions OSX worker node. There's a nightly job that uploads missing packages like this.

**Pull request merged**
