### PR TITLE
Rcas

### PR DESCRIPTION
**Pull request by dyusuf**
* [x] I have read the guidelines above.
* [x] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

@bioconda/core

### CODE REVIEW

**Comment by dyusuf** [comment]
@bioconda/core one of submitted package is pandoc built with Haskell. to compile pandoc, cabal needs to be pre-installed in the developing system. for the reference, there is note.md in the pandoc recipe dir. I am wondering if you could help in regards.

**Comment by bgruening** [comment]
@johanneskoester this PR would benefit from an enabled `conda-stage` channel. Are we ready to activate it?

**Comment by johanneskoester** [comment]
I would like to wait a bit until at least the other members of the core had a chance to answer. So, maybe we can activate it tonight if there are no objections.

**Comment by dyusuf** [comment]
@johanneskoester hi, any upodate in regards? thanks :-)

**Comment by johanneskoester** [comment]
Yes, see PR #1388 :-)

**Pull request closed without merging**
