### PR TITLE
loosen matplotlib restriction in multiqc

### PR DESCRIPTION
**Pull request by dpryan79**
Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it. Note that if you are not already a member of the bioconda project (meaning that you can't add this label), please ping `@bioconda/core` so that your PR can be reviewed and merged (please note if you'd like to be added to the bioconda project). Please see https://github.com/bioconda/bioconda-recipes/issues/15332 for more details.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by dpryan79** [comment]
@ewels For whatever reason pkg_resources is ignoring the fact that we're using python 3 (3.8 happens to get used in testing at the moment), so it's throwing an error due to using matplotlib 3.1.1. I'll just patch around that unless you have a better idea.

**Comment by dpryan79** [comment]
Oh, the problem is that we happen to build under python 2 and then reuse that same package in python 3, but pkg_resources can't handle that. I'll simply patch around the upper matplotlib pin.

**Comment by ewels** [comment]
No problem! I see this all as a short term thing anyway. Should hopefully be a lot simpler in the next release when I drop python 2...

**Comment by dpryan79** [comment]
Great, @ewels can you approve this PR then so I can merge it?

**Comment by dpryan79** [comment]
@bioconda-bot please fetch artifacts

**Comment by dpryan79** [comment]
No artifacts found on the most recent CircleCI build. Either the build failed or the recipe was blacklisted/skipped.

**Comment by dpryan79** [comment]
@bioconda-bot please fetch artifacts.

**Comment by dpryan79** [comment]
No artifacts found on the most recent CircleCI build. Either the build failed or the recipe was blacklisted/skipped.

**Comment by dpryan79** [comment]
@bioconda-bot let's try this again: please fetch artifacts

**Comment by dpryan79** [comment]
Package(s) built on CircleCI are ready for inspection:

Arch | Package | Repodata
-----|---------|---------
noarch | [multiqc-1.8-py_1.tar.bz2](https://83211-42372094-gh.circle-artifacts.com/0/tmp/artifacts/packages/noarch/multiqc-1.8-py_1.tar.bz2) | [repodata.json](https://83211-42372094-gh.circle-artifacts.com/0/tmp/artifacts/packages/linux-64/repodata.json)
***

You may also use `conda` to install these:

 * For packages on noarch:
```
conda install -c https://83211-42372094-gh.circle-artifacts.com/0/tmp/artifacts/packages <package name>
```
***

Docker image(s) built:

Package | Tag | Install with `docker`
--------|-----|----------------------
[multiqc](https://83211-42372094-gh.circle-artifacts.com/0/tmp/artifacts/images/multiqc%3A1.8--py_1.tar.gz) | 1.8--py_1 | <details><summary>show</summary>`curl "https://83211-42372094-gh.circle-artifacts.com/0/tmp/artifacts/images/multiqc%3A1.8--py_1.tar.gz" \| gzip -dc \| docker load`

**Comment by dpryan79** [comment]
Package(s) built on CircleCI are ready for inspection:

Arch | Package | Repodata
-----|---------|---------
noarch | [multiqc-1.8-py_1.tar.bz2](https://83211-42372094-gh.circle-artifacts.com/0/tmp/artifacts/packages/noarch/multiqc-1.8-py_1.tar.bz2) | [repodata.json](https://83211-42372094-gh.circle-artifacts.com/0/tmp/artifacts/packages/linux-64/repodata.json)
***

You may also use `conda` to install these:

 * For packages on noarch:
```
conda install -c https://83211-42372094-gh.circle-artifacts.com/0/tmp/artifacts/packages <package name>
```
***

Docker image(s) built:

Package | Tag | Install with `docker`
--------|-----|----------------------
[multiqc](https://83211-42372094-gh.circle-artifacts.com/0/tmp/artifacts/images/multiqc%3A1.8--py_1.tar.gz) | 1.8--py_1 | <details><summary>show</summary>`curl "https://83211-42372094-gh.circle-artifacts.com/0/tmp/artifacts/images/multiqc%3A1.8--py_1.tar.gz" \| gzip -dc \| docker load`

**Comment by dpryan79** [comment]
Thanks!

**Pull request merged**
