### PR TITLE
Snakemake 3.11.1

### PR DESCRIPTION
**Pull request by johanneskoester**
* [x] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

ping @holtgrewe

### CODE REVIEW

**Comment by holtgrewe** [comment]
Teriffic!

**Comment by holtgrewe** [comment]
Merge, merge, merge! :) :bowing_man:

**Comment by bgruening** [comment]
merged ;)

**Comment by johanneskoester** [comment]
Thanks guys!

**Pull request merged**
