### PR TITLE
OpenMS update requirements for thirdparty tools

### PR DESCRIPTION
**Pull request by bernt-matthias**
OpenMS 3.8 does not work with sirius 4.0.1

There are a few other thirdparty tools that might be updated. Here a list of tools used, available, and the version in the `THIRDPARTY` directory .. ping @jpfeuffer  

```
                    current    latest            THIRDPARTY
bumbershoot         3_0_20295  3_0_21142         NA
comet-ms            2019015    2021010           2019.01
crux-toolkit        3.2        4.1               ?
fido                1.0        1.0               ?
luciphor2           2020_04_03 2020_04_03        NA
msgf_plus           2021.03.22 2022.01.07        NA
pepnovo             20101117   20101117          NA
percolator          3.5        3.5               3.05.0
sirius-csifingerid  4.0.1      4.9.8             4.9.0
thermorawfileparser 1.3.4      1.3.4             NA
xtandem             15.12.15.2 15.12.15.2        2015.12.15.2

```

xref https://github.com/OpenMS/OpenMS/issues/5870

I will test this with the Galaxy wrappers...

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by jpfeuffer** [comment]
yes so sirius has to be updated, but I am not sure about the others, since many of the adapters were not tested with new versions and some of them are actually heavily version dependent.

**Comment by jpfeuffer** [comment]
I guess bumbershoot could be updated. But comet and crux are definitely version dependent and need to be updated in OpenMS first (or made version independent, which I wish for a long time already: see [#5149](https://github.com/OpenMS/OpenMS/issues/5149) and [#4152](https://github.com/OpenMS/OpenMS/issues/4152))

**Comment by bernt-matthias** [comment]
@BiocondaBot please fetch artifacts

**Comment by bernt-matthias** [comment]
@BiocondaBot please fetch artifacts

**Comment by bernt-matthias** [comment]
@jpfeuffer I verified the new versions for sirius and bumbershoot by executing the AssayGeneratorMetabo, SiriusAdapter, and MyriMatchAdapter tests.

**Comment by jpfeuffer** [comment]
Cool then I think it is ready to go! Thanks!

**Review by jpfeuffer — APPROVED** [review]

**Comment by bernt-matthias** [comment]
@BiocondaBot please add label

**Review by bgruening — APPROVED** [review]

**Review by dpryan79 — APPROVED** [review]

**Comment by bgruening** [comment]
@BiocondaBot please merge

**Pull request merged**
