### PR TITLE
Move MentaLiST v0.1.3 recipe to separate directory

### PR DESCRIPTION
**Pull request by dfornika**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by mbargull** [comment]
Hi @dfornika, I just added a commit that should hopefully resolve the issue you previously had.
For reference: https://github.com/conda/conda-build/pull/2142 was backported to `conda-build 2.1.18` but https://github.com/conda/conda-build/pull/2259/commits/4c2ecd375cc4cf76c561d9c82553ce9dffe46841 was not. That introduced the bug from https://github.com/conda/conda-build/issues/2255 into `conda-build 2.1.x`.

**Comment by dfornika** [comment]
I can't thank you enough @mbargull. I was really having difficulty troubleshooting that issue. Thanks for tracking it down!

**Comment by mbargull** [comment]
Oh great, the CI also agrees that it's working 😄. Do you we need any other additional changes or should we merge?

**Comment by dfornika** [comment]
I'm ready to merge thanks. I've got some changes to other versions of this recipe but I'll submit separate pull requests for those.

**Pull request merged**
