### PR TITLE
Update dcplib to 3.2.0

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`dcplib`](https://bioconda.github.io/recipes/dcplib/README.html): **3.1.0** &rarr; **3.2.0**

[install with bioconda](http://bioconda.github.io/recipes/dcplib/README.html) [Conda](https://anaconda.org/bioconda/dcplib/files)

Info | Link
-----|-----
Recipe | [`recipes/dcplib`](https://github.com//bioconda/bioconda-recipes/tree/bump/dcplib/recipes/dcplib) (click to view/edit other files)
Releases |[https://pypi.org/pypi/dcplib/json](https://pypi.org/pypi/dcplib/json)
Recipe Maintainer(s) | @pinin4fjords

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/updating.html)).

### CODE REVIEW

**Comment by pinin4fjords** [comment]
Oops, sorry @dpryan79 - just saw your label. Should this really be conda-forge? DCP is fairly bio-specific, no?

**Comment by dpryan79** [comment]
@pinin4fjords Is it? The description makes it sound like a very generic package. If it's really a bio-specific package then go ahead and merge.

**Comment by dpryan79** [comment]
I guess if it's just something used by the human cell atlas then it's fine, the description is just largely useless.

**Comment by pinin4fjords** [comment]
Fair point @dpryan79 , I've improved the description.

**Comment by pinin4fjords** [comment]
Oh, wrong description, hang on...

**Comment by dpryan79** [comment]
Much more useful description :) :+1: on merging this

**Comment by dpryan79** [comment]
The bulk branch is running some stuff at the moment, so the OSX test won't run for another 1-2 hours.

**Comment by pinin4fjords** [comment]
Okay, no worries, thanks for the heads-up, will check in later.

**Pull request merged**
