### PR TITLE
Rebuild roary

### PR DESCRIPTION
**Pull request by druvus**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [x] This PR does something else (explain below).

Rebuilding roary for perl 5.26 by restricting parallel and bioperl to newer version not pulling in perl-threaded.

### CODE REVIEW

**Comment by druvus** [comment]
Build takes still very long time. Locally it seems that build get stuck at following test  `t/Bio/Roary/CommandLine/Roary.t ......................... 5/?`

**Comment by tseemann** [comment]
It just says `Build timedout`

**Comment by druvus** [comment]
yes, circleci just show timeout but running the build locally in docker shows that it hangs at `t/Bio/Roary/CommandLine/Roary.t`. My guess it is that a used conda package is broken but my perl knowledge is a little bit rusty.

**Comment by aemiol** [comment]
My recipe has Roary as a dependency and I am having similar "build timeout" during test. Initially, I couldn't trace the source but from this thread, it appears roary might be the culprit.

**Comment by tseemann** [comment]
You should be able to disable tests some how with an option in `Build.pl` maybe?
@andrewjpage

**Comment by druvus** [comment]
Roary was rebuilt in #11017

**Comment by druvus** [comment]
@tseemann and @aemiol Roary is now rebuilt. Please check if the issues remains.

**Comment by tseemann** [comment]
Thanks @druvus  - I'll inform the people having trouble.

**Pull request closed without merging**
