### PR TITLE
jpeg pinning

### PR DESCRIPTION
**Pull request by bgruening**
* [x] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [x] This PR does something else (explain below).

ping @bioconda/core 
Imho we need to start pinning more packages - let's start with jpeg

I did not changed the build-string, as I don't think this scales. We have many package with a bunch of dependencies that needs to be pinned. Changing the build-string is a manual process and error prone. If we increase the version of a library we should increase the build-number. This we can do step-by-step without the need of a blacklist.

### CODE REVIEW

**Comment by bgruening** [comment]
Maybe related? https://github.com/bioconda/bioconda-recipes/issues/2770

**Comment by johanneskoester** [comment]
Do we need the additional pins right now? I'm asking, because I hope that Mike will soon release a new pinning system that addresses all these issues directly in conda-build, see conda/conda-build#1585. We could think about pushing that effort a bit, by testing or contributing code or ideas.

**Comment by bgruening** [comment]
I had the impression that this PR will take some time until it is finished. I'm fine with postponing our pinning work, but it feels like more and more packages do break here or as soon as conda-forge updates one of these requirements. There is also a new zlib upstream release ... I'm really scared :)

**Comment by johanneskoester** [comment]
That's great news @msarahan! In this case, I'd vote for using that approach. I'm afraid we cannot really test it directly on Bioconda until there is a stable release though. Too many people rely on our build system to work properly. But maybe we can try it locally once merged into the conda-build master.

**Comment by bgruening** [comment]
@msarahan awesome news! 
@johanneskoester we could re-compile some part of the stack locally or on some cluster at least for Linux builds?

**Comment by johanneskoester** [comment]
@bgruening yes, we can do that.

**Pull request closed without merging**
