### PR TITLE
Update peka to 0.1.4

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`peka`](https://bioconda.github.io/recipes/peka/README.html): **0.1.2** &rarr; **0.1.4**

[install with bioconda](http://bioconda.github.io/recipes/peka/README.html) [Conda](https://anaconda.org/bioconda/peka/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/peka`](https://github.com//bioconda/bioconda-recipes/tree/bump/peka/recipes/peka) (click to view/edit other files)
Summary | Analysis of kmers located around locations of interest
Home | [https://github.com/ulelab/peka](https://github.com/ulelab/peka)
Releases |[https://github.com/ulelab/peka/tags](https://github.com/ulelab/peka/tags)
Recipe Maintainer(s) | @marc-jones, @codeprimate123, @kkuret
Author | `@ulelab`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by marc-jones** [comment]
What's the best way of testing these builds? BiocondaBot used to post links to install via Conda or use the Docker image generated during the automated tests, but it looks like you've changed CI provider?

Also, I'd like to add @kkuret as a recipe maintainer. Should I create a separate PR for this, or can it be incorporated into this PR?

**Comment by marc-jones** [comment]
Ah, managed to install and test by downloading the artifacts from Azure and pointing Conda towards it. Seems like the build was successful!

**Comment by dpryan79** [comment]
@marc-jones Currently you have to click the over to azure (click on the "details" link under "all checks have passed" and then "view more details on azure"). For convenience here's the link: https://dev.azure.com/bioconda/bioconda-recipes/_build/results?buildId=9365&view=artifacts&pathAsName=false&type=publishedArtifacts

I haven't had a chance to rewrite the bot to post this stuff yet. We won't have simple installation instructions going forward, unfortunately, since we can only get zip files from Azure.

**Comment by marc-jones** [comment]
@dpryan79 Thanks for that. I downloaded the OSX artifact and it was empty, is this normal for noarch recipes? Is it possible to have the Docker image built as part of the tests also made available from Azure?

**Comment by dpryan79** [comment]
@marc-jones Yes, that's expected. noarch packages are built on Linux since typically we have more build capacity there.

**Comment by kkuret** [comment]
@dpryan79 Hello! could you please explain step-by-step how to test the new package version after downloading the LinuxAritfacts folder? 
Specifically, how can I make a conda environment with the new version of the package (peka==0.1.3) to run testing? I am not familiar with Azure and also new to maintaining the versions on bioconda, so any help would be much appreciated.

**Comment by marc-jones** [comment]
I created a fresh Conda environment, downloaded and extracted the LinuxArtifacts, `cd`-ed into it and ran `conda install -c ./packages/noarch/ peka==0.1.3`.

Unfortunately I discovered that this 0.1.3 release is broken. We'll push a 0.1.4 release which should fix the issue. @dpryan79 Can this PR be closed / deleted please?

**Comment by marc-jones** [comment]
Oh perfect, I didn't think the PR would be renamed! That's fantastic!

**Comment by kkuret** [comment]
@BiocondaBot please add label

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@marc-jones Thanks for confirming that those local installation instructions still work for the azure artifacts. I wasn't entirely sure I coded that bit correctly and hadn't actually tested it :) Now to get the bot to post that info...

**Comment by marc-jones** [comment]
@dpryan79 No worries, thanks for your help!

**Pull request merged**
