### PR TITLE
Update bioconductor-genvisr to 1.14.2

### PR DESCRIPTION
**Pull request by cbrueffer**
:information_source:
If this is your first pull request to Bioconda please ping `@bioconda/core` so it can be reviewed and to request being added as a member of the Bioconda team. Members of the Bioconda team are able to merge their own pull requests once tests and linting have passed.

----------------

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by cbrueffer** [comment]
Not sure what's going wrong here; error message is as follows:

```
Error: package or namespace load failed for 'GenVisR' in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
[Apr 15 13:00:40] SERR there is no package called 'GenomeInfoDbData'
[Apr 15 13:00:40] SERR Execution halted
```

The bioconductor-genomeinfodbdata works fine locally, and is installed during the build process here.

**Comment by PertuyF** [comment]
Re-running `bioconda-test` to see if https://github.com/bioconda/bioconda-common/pull/6 solves this issue with `bioconductor-genomeinfodbdata`.
@dpryan79 @bgruening for follow-up 😃

**Comment by dpryan79** [comment]
Crap, looks like that doesn't solve it.

**Comment by dpryan79** [comment]
Oh, we're still basing things off of the conda 4.5.12 image. @bgruening might that be causing the issue?

**Comment by dpryan79** [comment]
That image is the latest and actually has conda 4.5.11 in it :( I'll try to find where to inject a `conda update -y conda`.

**Comment by bgruening** [comment]
@dpryan79 I will try to get a new release out with new miniconda version. Give me 2 days ...

**Comment by PertuyF** [comment]
@dpryan79 Trying a variation on your first trial, as it seems to fail because `conda`  package was not found in the current active environment.

```
+ conda update -y conda



PackageNotInstalledError: Package is not installed in prefix.

  prefix: /opt/conda/conda-bld/bioconductor-genvisr_1556407256661/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold

  package name: conda
```

In this case, likely there is some `base` environment (if this is a standard miniconda install) which contains the conda install. So trying to update with providing environment's name.

**Comment by PertuyF** [comment]
Oups, wrong button...  🤦‍♂

**Comment by PertuyF** [comment]
Looks like the test commands happened to late to update conda as test env was already created.

**Comment by dpryan79** [comment]
Good news, the new mulled container seems to fix these issues :)

**Pull request merged**
