### PR TITLE
Add Shasta Genome Assembler

### PR DESCRIPTION
**Pull request by NatPRoach**
This adds a recipe for downloading the binary executable file for the de novo genome assembly tool shasta.

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by NatPRoach** [comment]
@BiocondaBot please add label

**Comment by dpryan79** [comment]
Can't we just compile it rather than shipping (likely problematic) binaries from the authors?

**Comment by NatPRoach** [comment]
> Can't we just compile it rather than shipping (likely problematic) binaries from the authors?

We can certainly try, but there was this attempt https://github.com/bioconda/bioconda-recipes/pull/15563 which came upon this issue ( https://github.com/chanzuckerberg/shasta/issues/25 ) which may not be resolved? Not sure.

But the main reason I avoided compiling from source was that according to their official documentation:
> Building from source is currently supported for Ubuntu (20.04 LTS) and macOS (10.15). Porting the build process to other Linux platforms is possible. If you are specifically interested in porting to a different Linux platorm, please file an Issue on GitHub. Even better, submit a Pull Request with the necessary changes.

And when I tried installing from source I got an error
```
CMake Error at dynamicLibrary/CMakeLists.txt:77 (string):
  string sub-command STRIP requires two arguments.
```
in cmake using the install commands that they specified here:
https://chanzuckerberg.github.io/shasta/BuildingFromSource.html

**Comment by dpryan79** [comment]
Ah yes, I remember having issues with this. I suppose we can try this and see how well it works.

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Pull request merged**
