### PR TITLE
enable container push

### PR DESCRIPTION
**Pull request by bgruening**
* [x] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [x] This PR does something else (explain below).

When applied, this PR will push our generated containers automatically to quay.io.
ping @bioconda/core 

I have added INVOLUCRO_AUTH to the travis config to provide the push credentials.

### CODE REVIEW

**Comment by johanneskoester** [comment]
That's great, thank you! We should add the URL to the repsective quay.io page for each package to our autogenerated docs. Do you want to do that in this PR as well? If not, can you post the URL patter? I'll do it in a separate PR.

**Comment by bgruening** [comment]
@johanneskoester bedtools are for example here: https://quay.io/repository/biocontainers/bedtools?tab=tags

So a command would be `docker pull quay.io/biocontainers/bedtools:2.25.0--2`. Please note that `docker pull quay.io/biocontainers/bedtools` will not work as I do not create a `latest` container, you always need to specify the `version--build`. Maybe we need to add a small sentence?

**Comment by johanneskoester** [comment]
I think it should be enough to just link to quay. There, people can look up the pull urls for the desired version.

**Comment by bgruening** [comment]
@johanneskoester what do you think about: https://github.com/bioconda/bioconda-recipes/pull/2925/commits/5868b5ccf92ba5914cdfe979e696c85bc8d1c01a

**Comment by johanneskoester** [comment]
Perfect! Thanks!

**Comment by bgruening** [comment]
@johanneskoester feel free to merge. I think we need to test this on master and fixing/reverting on the weekend is probably better than in the week ;)

**Comment by johanneskoester** [comment]
Oh no, no I have taken responsibility again ;-).

**Comment by acaprez** [comment]
Hmm, the changes in fe72ed7aa9c96771d7e9445992db854626cfe670 to `travis-run.sh` cause an error when running `simulate-travis.py` on my local testing VM:
```
scripts/travis-run.sh: line 5: TRAVIS_BUILD_DIR: unbound variable
Traceback (most recent call last):
  File "./simulate-travis.py", line 150, in <module>
    sp.run(['scripts/travis-run.sh'], env=env, universal_newlines=True, check=True)
  File "/opt/anaconda/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['scripts/travis-run.sh']' returned non-zero exit status 1
```

The `TRAVIS_BUILD_DIR` env variable is unset when running locally, which causes the error.  Probably the easiest fix is to place the `export` and `touch` lines in an if-block, since the `simulate-travis.py` script sets `TRAVIS_BRANCH=false`, i.e.:

```
if [[ $TRAVIS_BRANCH = "master" && "$TRAVIS_PULL_REQUEST" = false ]]
then
   export ONTAINER_PUSH_COMMANDS_PATH=${TRAVIS_BUILD_DIR}/container_push_commands.sh
   touch $CONTAINER_PUSH_COMMANDS_PATH
fi
```

**Comment by bgruening** [comment]
@acaprez thanks for spotting: https://github.com/bioconda/bioconda-recipes/pull/2944

**Pull request merged**
