### PR TITLE
Fix3510

### LINKED ISSUE #3510: Establish working recipe for tophat + bowtie
This references  #2752 

I think we should strictly roll back `tophat` to Python v2.7 AND link it with `bowtie2` v2.2.5. `bowtie2` v2.3.0 was recently released, but does not play nice with `tophat` v2.1.1

I've never built a conda or bioconda recipe before, but I would take a stab at it.

```
balter@server:/home/...users/balter/tophat/test_data$ source activate tophat2
(tophat2) balter@server:/home/...users/balter/tophat/test_data$ tophat -r 20 test_ref reads_1.fq reads_2.fq

[2017-01-17 11:08:04] Beginning TopHat run (v2.1.1)
-----------------------------------------------
[2017-01-17 11:08:04] Checking for Bowtie
		  Bowtie version:	 2.3.0.0
[2017-01-17 11:08:04] Checking for Bowtie index files (genome)..
	Found both Bowtie1 and Bowtie2 indexes.
[2017-01-17 11:08:04] Checking for reference FASTA file
[2017-01-17 11:08:04] Generating SAM header for test_ref
[2017-01-17 11:08:10] Preparing reads
	 left reads: min. length=75, max. length=75, 100 kept reads (0 discarded)
	right reads: min. length=75, max. length=75, 100 kept reads (0 discarded)
[2017-01-17 11:08:10] Mapping left_kept_reads to genome test_ref with Bowtie2
	[FAILED]
Error running:
/home/.../Applications/miniconda3/envs/tophat2/bin/bam2fastx --all ./tophat_out/tmp/left_kept_reads.bam|/home/.../Applications/miniconda3/envs/tophat2/bin/bowtie2 -k 20 -D 15 -R 2 -N 0 -L 20 -i S,1,1.25 --gbar 4 --mp 6,2 --np 1 --rdg 5,3 --rfg 5,3 --score-min C,-14,0 -p 1 --sam-no-hd -x test_ref -|/home/.../Applications/miniconda3/envs/tophat2/bin/fix_map_ordering --bowtie2-min-score 15 --read-mismatches 2 --read-gap-length 2 --read-edit-dist 2 --read-realign-edit-dist 3 --index-outfile ./tophat_out/tmp/left_kept_reads.mapped.bam.index --sam-header ./tophat_out/tmp/test_ref_genome.bwt.samheader.sam - ./tophat_out/tmp/left_kept_reads.mapped.bam ./tophat_out/tmp/left_kept_reads_unmapped.bam
(tophat2) balter@server:/home/...users/balter/tophat/test_data$ source deactivate
```

```
balter@server:/home/...users/balter/tophat/test_data$ source activate tophat
(tophat) balter@server:/home/...users/balter/tophat/test_data$ tophat -r 20 test_ref reads_1.fq reads_2.fq

[2017-01-17 11:08:39] Beginning TopHat run (v2.1.1)
-----------------------------------------------
[2017-01-17 11:08:39] Checking for Bowtie
		  Bowtie version:	 2.2.5.0
[2017-01-17 11:08:39] Checking for Bowtie index files (genome)..
	Found both Bowtie1 and Bowtie2 indexes.
[2017-01-17 11:08:39] Checking for reference FASTA file
[2017-01-17 11:08:39] Generating SAM header for test_ref
[2017-01-17 11:08:39] Preparing reads
	 left reads: min. length=75, max. length=75, 100 kept reads (0 discarded)
	right reads: min. length=75, max. length=75, 100 kept reads (0 discarded)
[2017-01-17 11:08:39] Mapping left_kept_reads to genome test_ref with Bowtie2
[2017-01-17 11:08:39] Mapping left_kept_reads_seg1 to genome test_ref with Bowtie2 (1/3)
[2017-01-17 11:08:40] Mapping left_kept_reads_seg2 to genome test_ref with Bowtie2 (2/3)
[2017-01-17 11:08:43] Mapping left_kept_reads_seg3 to genome test_ref with Bowtie2 (3/3)
[2017-01-17 11:08:43] Mapping right_kept_reads to genome test_ref with Bowtie2
[2017-01-17 11:08:43] Mapping right_kept_reads_seg1 to genome test_ref with Bowtie2 (1/3)
[2017-01-17 11:08:43] Mapping right_kept_reads_seg2 to genome test_ref with Bowtie2 (2/3)
[2017-01-17 11:08:44] Mapping right_kept_reads_seg3 to genome test_ref with Bowtie2 (3/3)
[2017-01-17 11:08:44] Searching for junctions via segment mapping
[2017-01-17 11:08:44] Retrieving sequences for splices
[2017-01-17 11:08:44] Indexing splices
Building a SMALL index
[2017-01-17 11:08:54] Mapping left_kept_reads_seg1 to genome segment_juncs with Bowtie2 (1/3)
[2017-01-17 11:08:54] Mapping left_kept_reads_seg2 to genome segment_juncs with Bowtie2 (2/3)
[2017-01-17 11:08:54] Mapping left_kept_reads_seg3 to genome segment_juncs with Bowtie2 (3/3)
[2017-01-17 11:08:54] Joining segment hits
[2017-01-17 11:08:54] Mapping right_kept_reads_seg1 to genome segment_juncs with Bowtie2 (1/3)
[2017-01-17 11:08:55] Mapping right_kept_reads_seg2 to genome segment_juncs with Bowtie2 (2/3)
[2017-01-17 11:08:55] Mapping right_kept_reads_seg3 to genome segment_juncs with Bowtie2 (3/3)
[2017-01-17 11:08:55] Joining segment hits
[2017-01-17 11:08:55] Reporting output tracks
-----------------------------------------------
[2017-01-17 11:09:03] A summary of the alignment counts can be found in ./tophat_out/align_summary.txt
[2017-01-17 11:09:03] Run complete: 00:00:24 elapsed
```

### PR DESCRIPTION
**Pull request by dpryan79**
* [x] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

@bioconda/core: This should fix #3510, which was also reported [here](https://www.biostars.org/p/232228/). It also appears that the recipe was never compatible with OSX (the test would work, but the binaries wouldn't have). I'm not sure what to do about the existing python3 versions of this package that are already available. They won't work and this update won't fix them. Should they just be removed so people can't inadvertently install them?

### CODE REVIEW

**Comment by dpryan79** [comment]
As an aside, it seems that at least my branches are no longer getting tested on TravisCI. Also, this PR isn't showing up there yet. Perhaps they or github are having issues.

**Comment by bgruening** [comment]
Travis lost it's github connection, I have seen this in other repos as well :(

**Comment by bgruening** [comment]
@dpryan79 I can remove the python3 version of this package as soon as this is merged, ok?

**Comment by dpryan79** [comment]
Great, thanks Björn!

**Comment by dpryan79** [comment]
@bgruening This still isn't available via `conda search` and I can't find it on anaconda.org. Any clue what's up with that?

**Comment by bgruening** [comment]
Mh, I don't understand this. The package is not at: https://anaconda.org/bioconda/tophat/files
Because nothing was build: https://s3.amazonaws.com/archive.travis-ci.org/jobs/192970230/log.txt

@daler can this be a bug in the filter script?
Another thing, I realized that the folder is called tophat2 but the name of the package tophat, is this correct?

**Comment by daler** [comment]
seems to be filtered out, bioconda-utils reports that build `0` is in the bioconda channel.
```
$ ./simulate-travis.py --packages "tophat*" --loglevel=debug
+ bioconda-utils build recipes config.yml --docker --loglevel=info --mulled-test --packages 'tophat*' --loglevel=debug
INFO bioconda_utils.docker_utils:_pull_image(312): BIOCONDA DOCKER: Pulling docker image condaforge/linux-anvil
DEBUG bioconda_utils.docker_utils:_pull_image(314): BIOCONDA DOCKER: stdout+stderr: Using default tag: latest
latest: Pulling from condaforge/linux-anvil
Digest: sha256:4cd6620f0d8b31c712583a9f9d76ccef828596fff91deb97beb56372b21719f3
Status: Image is up to date for condaforge/linux-anvil:latest

INFO bioconda_utils.docker_utils:_pull_image(318): BIOCONDA DOCKER: Done pulling image
DEBUG bioconda_utils.docker_utils:_build_image(329): BIOCONDA DOCKER: Building image "tmp-bioconda-builder" from /tmp/tmpmohawkt9
DEBUG bioconda_utils.docker_utils:_build_image(342): Dockerfile:

FROM condaforge/linux-anvil
COPY requirements.txt /tmp/requirements.txt
RUN /opt/conda/bin/conda config --add channels conda-forge
RUN /opt/conda/bin/conda config --add channels defaults
RUN /opt/conda/bin/conda config --add channels r
RUN /opt/conda/bin/conda config --add channels bioconda
RUN /opt/conda/bin/conda install --file /tmp/requirements.txt

INFO bioconda_utils.docker_utils:_build_image(358): BIOCONDA DOCKER: Built docker image tag=tmp-bioconda-builder
INFO bioconda_utils.build:build_recipes(233): blacklist: bioconductor-bubbletree, bioconductor-cexor, bioconductor-deseq2/1.10.1, bioconductor-diffbind, bioconductor-genelendatabase/1.6.0, bioconductor-iranges/2.4.6, bioconductor-iranges/2.4.7, bioconductor-limma/3.26.7, bioconductor-limma/3.28.2, bioconductor-limma/3.28.6, bioconductor-mmdiff, bioconductor-s4vectors/0.8.7, bioconductor-summarizedexperiment/1.0.2, bioconductor-systempiper, cap-mirseq, ensembl-vep, mysqlclient, r-hdrcde, r-knitr, r-ks, r-mutoss, r-phonr, r-rainbow, r-readr, r-sartools/1.2.0, r-spp, rsem, triform2
DEBUG bioconda_utils.utils:get_recipes(245): get_recipes(recipes, package='['tophat*']'): tophat*
DEBUG bioconda_utils.build:build_recipes(244): recipes/tophat2
DEBUG bioconda_utils.build:build_recipes(244): recipes/tophat-recondition
DEBUG bioconda_utils.build:build_recipes(249): recipes: ['recipes/tophat2', 'recipes/tophat-recondition']
INFO bioconda_utils.build:build_recipes(268): Filtering recipes
DEBUG bioconda_utils.utils:filter_recipes(514): recipes: ['recipes/tophat2', 'recipes/tophat-recondition']

DEBUG bioconda_utils.utils:tobuild(495): BIOCONDA FILTER: not building tophat-recondition-1.4-py27_0.tar.bz2 because it is in channel(s): ['bioconda']
DEBUG bioconda_utils.utils:tobuild(495): BIOCONDA FILTER: not building tophat-recondition-1.4-py34_0.tar.bz2 because it is in channel(s): ['bioconda']
DEBUG bioconda_utils.utils:tobuild(495): BIOCONDA FILTER: not building tophat-recondition-1.4-py35_0.tar.bz2 because it is in channel(s): ['bioconda']
DEBUG bioconda_utils.utils:tobuild(495): BIOCONDA FILTER: not building tophat-2.1.1-py27_0.tar.bz2 because it is in channel(s): ['bioconda']
DEBUG bioconda_utils.utils:tobuild(495): BIOCONDA FILTER: not building tophat-2.1.1-py34_0.tar.bz2 because it is in channel(s): ['bioconda']
DEBUG bioconda_utils.utils:tobuild(495): BIOCONDA FILTER: not building tophat-2.1.1-py35_0.tar.bz2 because it is in channel(s): ['bioconda']

INFO bioconda_utils.build:build_recipes(282): Nothing to be done.
+ set +x
```

**Comment by daler** [comment]
Ah, that's it: there are two `build` sections in the meta, the second overwrites the first so there's never a `build: 1`.

**Comment by bgruening** [comment]
Ha, great detective work, I should look at the entire file and not only the diff more often!
Thanks a bunch!

**Pull request merged**
