### PR TITLE
deprecate the OS-X whitelist

### PR DESCRIPTION
**Pull request by bgruening**
This PR will add `skip: True # [osx]` (or similar) to all repositories that are not on the whitelist already. With this explicit skip step it is now possible to add all repositories to the whitelist.

As a next step we can simply remove the whitelist and change the travis config.

This should fix: https://github.com/bioconda/bioconda-recipes/issues/1012

### CODE REVIEW

**Comment by kyleabeauchamp** [comment]
I spot-checked the first few (by alphabet) meta.yaml files, up until `bioconductor-annotationdbi`.  The changes to skip[osx] herein seem to agree with the whitelist values that were present before the stepwise migration.   Someone else should spot-check a few more entries to be sure.

**Comment by johanneskoester** [comment]
I checked a few more, and it seems correct for them as well.

**Comment by bgruening** [comment]
@johanneskoester ready for merge? :)

**Comment by johanneskoester** [comment]
Did somebody test with @daler's code from [here](https://github.com/bioconda/bioconda-recipes/issues/1012#issuecomment-198761914)?

**Comment by daler** [comment]
Yep, from that code, the set intersection of recipes previously cleared on osx-whitelist and those currently with `skip: True # [osx]` in their meta.yaml gives `picard`, `java-jdk`, and `pybigwig`.

But it's fine -- turns out these are skipped for OSX in older versions (java-jdk 6.0.77, picard 1.97, and pybigwig 0.1.11) but their most recent versions build for OSX.

It's not clear what else to check. I'd say we're good to go!

**Comment by johanneskoester** [comment]
Perfect. I'll merge this now.

**Comment by johanneskoester** [comment]
@bgruening thanks a lot for this, great work!

**Comment by bgruening** [comment]
Wuhu. OK I will now remove the whitelist and adopt the travis config.
Thanks for the careful review and the merge!

**Pull request merged**
