### PR TITLE
scvis module specific for use in Galaxy

### PR DESCRIPTION
**Pull request by astrovsky01**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [x] This PR does something else (explain below).
@bioconda/core @dpryan79 Due to Galaxy's inability to use certain key filetypes and functions in the original SCVIS tool, this package will function as a galaxy-specific version, modified from the other package.

Tests were eliminated due to known tensorflow issues as referenced in https://github.com/bioconda/bioconda-recipes/pull/14499

### CODE REVIEW

**Comment by dpryan79** [comment]
@bgruening Isn't there an IUC conda channel? Should we put this and #15630 there?

**Comment by bgruening** [comment]
The IUC conda channel is not used at the moment and I think this is good. This PR is currently WIP afaik and will maybe end up in a proper fork when the upstream devs do not respond.

**Comment by astrovsky01** [comment]
This pr is also going to fail, intentionally, because of the tests, but it still works, and built on my personal machine.

**Comment by astrovsky01** [comment]
@dpryan79 The setuptools args make the package build fail locally. Any way to get around it?

**Comment by dpryan79** [comment]
@bioconda-bot merge

**Pull request merged**
