### PR TITLE
Gmap update

### PR DESCRIPTION
**Pull request by duxan**
* [x] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by yhoogstrate** [comment]
I have my concerns about this. I think the most elegant solution would be to pin the dependency in defuse's own conda repo: https://anaconda.org/dranew/defuse.

My worry is that when defuse dependends on version y, galaxy depends on version w and tool-x that is currently under development shall depend on version x while if I want to use it straight from the command line I would like to use the latest, version z. I think this PR is more or less fixing a deployment issue of defuse, and downgrades gmap for other use cases. I am curious how you think about this?

**Comment by duxan** [comment]
You are quite right here. I rushed into switching back to original version and only after closely looking how it breaks deFuse found out it misses Perl (or some specific modules) to run with latest GMAP. 

I'll try to fix this and change this PR here, so please don't merge yet.

Thanks!

**Comment by duxan** [comment]
Hi again,

It should be fixed now - latest version is default, 2015 version optional and Perl is added as runtime requirement.

Thanks!

**Comment by bgruening** [comment]
You need to increase the build number, otherwise this will not be build.

**Comment by duxan** [comment]
Tnx Björn, hope it's ok now.

**Comment by bgruening** [comment]
@yhoogstrate @druvus is this one ready to go?

**Comment by druvus** [comment]
gmap is compiling so I guess gcc/llvm/libgcc should be added.

**Comment by yhoogstrate** [comment]
Ouch did i Just merge too quickly?

**Pull request merged**
