### PR TITLE
Add Porechop abi

### PR DESCRIPTION
**Pull request by qbonenfant**
We created Porechop_ABI, an extension the read trimming tool Porechop developed by Ryan Wick, in which we added automatic adapter sequence inference using approximate k-mers.
We wanted to make it easier to install, hence the creation of a conda package (just like the original Porechop).

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by qbonenfant** [comment]
@BiocondaBot please add label

**Comment by qbonenfant** [comment]
@BiocondaBot please fetch artifacts

**Comment by jmarshall** [comment]
The best thing to do for `-shared` would be to write it out in your rules and not override `$(LDFLAGS)` at all:

```diff
diff --git a/Makefile b/Makefile
index ab2cfb7..5d5fe7f 100755
--- a/Makefile
+++ b/Makefile
@@ -17,7 +17,6 @@ CXXFLAGS    ?= -Wall -Wextra -pedantic -mtune=native
 
 # These flags are required for the build to work.
 FLAGS        = -std=c++14 -Iporechop/include -fPIC
-LDFLAGS      = -shared
 
 # Different debug/optimisation levels for debug/release builds.
 DEBUGFLAGS   = -DSEQAN_ENABLE_DEBUG=1 -g
@@ -77,13 +76,13 @@ debug: all
  $(TARGET): $(OBJECTS)
-	$(CXX) $(FLAGS) $(CXXFLAGS) $(LDFLAGS) -Wl,$(SONAME),$(TARGET) -o $(TARGET) $(OBJECTS)
+	$(CXX) -shared $(FLAGS) $(CXXFLAGS) $(LDFLAGS) -Wl,$(SONAME),$(TARGET) -o $(TARGET) $(OBJECTS)
 
 $(APPROXCOUNTER_TGT):
 	$(CXX) $(FLAGS) $(APPROXCOUNTER_FLAG) $(OMP) $(CXXFLAGS)  $(APPROXCOUNTER_SRC) $(LRT) $(LZ) -o $(APPROXCOUNTER_TGT)
 
 $(COMPAT_TGT): $(COMPAT_OBJ)
-	$(CXX) $(FLAGS) $(CXXFLAGS) $(LDFLAGS) -Wl,$(SONAME),$(COMPAT_TGT) -o $(COMPAT_TGT) $(COMPAT_OBJ)
+	$(CXX) -shared $(FLAGS) $(CXXFLAGS) $(LDFLAGS) -Wl,$(SONAME),$(COMPAT_TGT) -o $(COMPAT_TGT) $(COMPAT_OBJ)
```

Then conda's `-L` option will be transmitted via `$(LDFLAGS)` without issue. This is akin to your `$(FLAGS)` variable which doesn't clash with any of the standard names.

I see your makefile uses `-install_name` on Darwin but `-soname` on Linux. MacOS also prefers to call shared libraries _porechop/cpp_functions.dylib_ etc, so you would probably do well to conditionalise that too. Certainly changing it later will cause problems.

**Comment by qbonenfant** [comment]
> LDFLAGS

Thanks for your reply, @dpryan79 suggested to avoid overwritting ldflag too on gitter.
I'm currently testing this fix locally. 
Should i still pass LDFLAG in the makefile to each target, or is it done automatically ? (I'm not exactly an expert in makefile and compilation options).

**Comment by jmarshall** [comment]
> Should i still pass LDFLAG in the makefile to each target

You do still need to list it on the `$(CXX) …` line of any recipe that's doing linking. Then that recipe line will take it from the environment (so the environment as set by conda) if it doesn't appear anywhere else in the _Makefile_.

(If you really wanted to avoid warnings with `--warn-undefined-variables` you could add `LDFLAGS ?=` near the top, but there's not really a pressing need to do so.)

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@BiocondaBot please merge

**Pull request merged**
