### PR TITLE
Adding superintervals v0.2.3

### PR DESCRIPTION
**Pull request by kcleal**
This adds the superintervals library for python v0.2.2

### CODE REVIEW

**Comment by martin-g** [comment]
The ARM64 build fails with `error: 'int32x4_t' was not declared in this scope; did you mean 'int32_t'`
You may use `sse2neon.h` for ARM64 instead of the Intel intrinsics.

**Comment by kcleal** [comment]
Hi @martin-g, I will need to adjust the code as the intrinsics are not being included properly, my bad!

**Comment by kcleal** [comment]
@bioconda-bot please add label

**Comment by kcleal** [comment]
@martin-g I think this should be good now!

**Review by mencian — APPROVED** [review]

**Pull request merged**
