### PR TITLE
Update unifrac-binaries recipe, remove hdf5 dependency

### PR DESCRIPTION
**Pull request by sfiligoi**
HDF5 is fully statically linked in unifrac-binaries 1.2.
Remove runtime dependencies from the recipe.

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by sfiligoi** [comment]
@BiocondaBot please fetch artifacts

**Comment by sfiligoi** [comment]
@BiocondaBot please add label

**Comment by sfiligoi** [comment]
Tested the artifacts locally, and they look good

**Comment by bgruening** [comment]
The readme has mentioned HDF5 everywhere: https://github.com/biocore/unifrac-binaries#install-native

Is this really how it should be done?

**Comment by sfiligoi** [comment]
> The readme has mentioned HDF5 everywhere: https://github.com/biocore/unifrac-binaries#install-native
> 
> Is this really how it should be done?

hdf5 is needed during compile, but not at runtime.
We link against the static hdf5 libraries, so we can co-exist with other HDF5 library versions without any problems.

PS: We could possibly improve the README, yes.

**Comment by ebolyen** [comment]
@sfiligoi, but that wasn't previously the case correct? It looks like that was added/fixed in https://github.com/biocore/unifrac-binaries/pull/15, which is included in this latest release.

(Thanks for updating unifrac by the way! We had just tracked down some incompatibilities between h5py/scikit-bio and unifrac-binaries in our latest pre-release envs, and these changes should fix that)

**Comment by sfiligoi** [comment]
@ebolyen Yes, unifrac-binaries 1.1.x needed hdf5 at runtime.

Note: The hdf5 dependency in 1.1.x was actually a Makefile bug; the dependency was never supposed to be there.
But that was fixed in https://github.com/biocore/unifrac-binaries/pull/15

**Review by ebolyen — APPROVED** [review]

**Comment by ebolyen** [comment]
We've tested this locally as well now and can confirm that the static linking appears to be working.

We succesfully installed these built packages alongside a source install of `unifrac` with the latest version of `hdf5` (`1.12.2`) which differs from what `unifrac-binaries` was statically-linked against (`1.12.1`).

The tests from our downstream packages (`q2-diversity-lib`) also succeed with these new versions.

**Comment by ebolyen** [comment]
(I'm not really sure why bioconda built with `1.12.1` and not `1.12.2`, but it's what appears in the rendered recipe inside the package.)

**Comment by sfiligoi** [comment]
@bgruening Anything blocking this revision?

**Comment by sfiligoi** [comment]
@rpetit3 Any chance you can look at this?

**Comment by sfiligoi** [comment]
@matthdsm Any chance you can review this?

**Review by matthdsm — APPROVED** [review]

**Comment by matthdsm** [comment]
@BiocondaBot please merge

**Pull request merged**
