### PR TITLE
Added mm10 bsgenome package.

### PR DESCRIPTION
**Pull request by jrderuiter**
* [x] I have read the guidelines above.
* [x] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

Adds the mm10 bsgenome package from bioconductor.

### CODE REVIEW

**Comment by jrderuiter** [comment]
Build is failing due to an error when building the blast recipe (see #3535). How to address?

**Comment by druvus** [comment]
I have added the failed blast to `build-fail-blacklist` and merged it to master so it should disturb the builds anymore. 

@bgruening do you any idea why the blast 2.2.21 recipe could slip through the test?

**Comment by daler** [comment]
@druvus @bgruening @rvalieris looks like it was #2872, which had its tests pass in early Nov and therefore was technically allowed to be merged via the github interface. But much has changed since then so it probably needed a rebase.

**Comment by jrderuiter** [comment]
@druvus Great, thanks!

**Pull request merged**
