### PR TITLE
Do not filter by osx-whitelist

### PR DESCRIPTION
**Pull request by bgruening**
by default all packages will be build for OS-X.

This is the second part of https://github.com/bioconda/bioconda-recipes/pull/1105

ping @johanneskoester @daler

### CODE REVIEW

**Comment by bgruening** [comment]
I will try to fix this one recipe that was merged between both PR ... I'm way to slow today.

**Comment by johanneskoester** [comment]
My fault, sorry!

**Comment by johanneskoester** [comment]
Looks good apart from the error.

**Comment by bgruening** [comment]
Hope the best that htseq can be compiled on OS-X :)

**Comment by bgruening** [comment]
Wuhu! All checks pass!

**Pull request merged**
