### PR TITLE
Update busco 4.1.4 recipe

### PR DESCRIPTION
**Pull request by skrakau**
Update busco 4.1.4 recipe to avoid errors when running `generate_plot.py`. 

When running the busco script with the `busco:4.1.4--py_0` container I get the following error:
```
  INFO:	****************** Start plot generation at 02/15/2021 12:13:55 ******************
  INFO:	Load data ...
  INFO:	Loaded ./short_summary.specific.bacteria_odb10.MEGAHIT-minigut1_1_fa.txt successfully
  INFO:	Generate the R code ...
  INFO:	Run the R code ...
  INFO:
  [1] "Plotting the figure ..."

  INFO:	Plot generation done. Total running time: 1.7865371704101562 seconds
  INFO:	Results written in ./

Command error:
  ERROR:

   *** caught segfault ***
  address (nil), cause 'memory not mapped'

  Traceback:
   1: cairoVersion()
   2: grSoftVersion()
   3: symbolType1support()
   4: optionSymbolFont(d$symbolfamily)
   5: grDevices::png(..., res = dpi, units = "in")
   6: dev(filename = filename, width = dim[1], height = dim[2], ...)
   7: ggsave(figure, file = my_output, width = my_width, height = my_height,     unit = my_unit)
  An irrecoverable exception occurred. R is aborting now ...
```

Adding `cairo >= 1.16.0` and `r-rgtk2 >= 2.20.36` fixed this for me.

The `fonts-conda-ecosystem` is added to avoid missing fonts in the resulting plots.

### CODE REVIEW

**Comment by skrakau** [comment]
@BiocondaBot please fetch artifacts

**Comment by skrakau** [comment]
@bioconda/core do you know why there were no artefacts found?

**Comment by dpryan79** [comment]
If I had a nickel for every time I made this mistake... :) It's unfortunate that conda-bld is picky about yaml vs yml as a file extension.

**Comment by skrakau** [comment]
ups :) thank you @dpryan79!

**Comment by skrakau** [comment]
@BiocondaBot please fetch artifacts

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
Go ahead and have the bot merge this when you're happy with it :)

**Comment by skrakau** [comment]
... the built container works for me.

**Comment by skrakau** [comment]
@BiocondaBot please merge

**Pull request merged**
