### PR TITLE
New Recipe for Adapterremovalfixprefix

### PR DESCRIPTION
**Pull request by apeltzer**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

@bioconda/core

### CODE REVIEW

**Comment by daler** [comment]
@apeltzer what's the exit code for `AdapterRemovalFixPrefix` with no args? If it's nonzero then that's the issue, so you might try e.g.  `AdapterRemovalFixPrefix || [[ "$?" == 1 ]]`

**Comment by apeltzer** [comment]
Just added that ;-) Will see if that helps :-)

**Comment by bgruening** [comment]
@apeltzer alternatively you could enhance your tool to not fail with a non zero error message :)
Thanks for the recipe!

**Comment by apeltzer** [comment]
I might even do that soon ;-)

**Pull request merged**
