### PR TITLE
Update mars to 1.2.2

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`mars`](https://bioconda.github.io/recipes/mars/README.html): **1.1** &rarr; **1.2.2**

[install with bioconda](http://bioconda.github.io/recipes/mars/README.html) [Conda](https://anaconda.org/bioconda/mars/files)

Info | Link
-----|-----
Recipe | [`recipes/mars`](https://github.com//bioconda/bioconda-recipes/tree/bump/mars/recipes/mars) (click to view/edit other files)
Releases |[https://github.com/maiziex/MARS/tags](https://github.com/maiziex/MARS/tags)
Recipe Maintainer(s) | @volcano1998
Author | `@maiziex`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by volcano1998** [comment]
@BiocondaBot please add label

**Review by rpetit3 — APPROVED** [review]

**Comment by volcano1998** [comment]
@rpetit3  Hello rpetit3, I was updating this code because some of the executable file included in my package can not be executed after installing. For example, I include k8 package and its executable file in my "bin" folder, and I added those paths into the setup.py. However, when my code tried to run those executable files, it shows " permission denied". I know I can manually change the permission in my terminal, but I wish this can be done when installing. Any thoughts? thank you!

**Comment by rpetit3** [comment]
I wonder if you could try running `chmod 755` on them, then committing them as executable.

**Comment by volcano1998** [comment]
you mean before I upload the package into github, I change the permission locally?

**Comment by volcano1998** [comment]
I see, I found even my local files don't have execution permission. I will try , thank you so much!

**Comment by rpetit3** [comment]
I think that might do it for you! If not we can probably add something to the recipe here to do so

**Comment by volcano1998** [comment]
@rpetit3  Thank you! It indeed worked!  I appreciate your help so much and may you have a good weekend!

**Pull request merged**
