### PR TITLE
Update crispector to 1.0.2b7

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`crispector`](https://bioconda.github.io/recipes/crispector/README.html): **1.0.2b6** &rarr; **1.0.2b7**

[install with bioconda](http://bioconda.github.io/recipes/crispector/README.html) [Conda](https://anaconda.org/bioconda/crispector/files)

Info | Link
-----|-----
Recipe | [`recipes/crispector`](https://github.com//bioconda/bioconda-recipes/tree/bump/crispector/recipes/crispector) (click to view/edit other files)
Releases |[https://github.com/YakhiniGroup/crispector/tags](https://github.com/YakhiniGroup/crispector/tags)
Recipe Maintainer(s) | @iamit87
Author | `@YakhiniGroup`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by iamit87** [comment]
@BiocondaBot please review & merge

**Comment by iamit87** [comment]
@BiocondaBot please merge

**Comment by iamit87** [comment]
@BiocondaBot please add label

**Comment by dfornika** [comment]
@BiocondaBot please fetch artifacts

**Comment by iamit87** [comment]
@BiocondaBot please merge

**Pull request merged**
