### PR TITLE
r-probmetab - fix conda getting stuck on solving environment

### PR DESCRIPTION
**Pull request by Tomnl**
conda getting stuck on solving environment - hopefully specifying camera version will solve this

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by Tomnl** [comment]
Hi @lecorguille, I have been having trouble installing r-probmetab with Galaxy and conda recently and the following command will just hang on the solving environment stage

```
conda install r-probmetab -c bioconda
```

I have made some updates in this pull request that will hopefully fix the problem. 

I just wanted to check if these updates are OK with you and W4M and if you have been experiencing any problems with r-probmetab

Note that the linting is currently failing but the bioconda-test is passing. It is not clear to me why the lint would fail but I have asked on gitter for some help with it.

FYI: @RJMW

**Comment by npavlovikj** [comment]
@BiocondaBot recheck

**Comment by npavlovikj** [comment]
As of now, "Linting Recipes" is not mandatory to be green in order for you to be able to merge your recipe (as long as "bioconda-test" is green). It is work in progress, and sometimes that step gets stuck or disabled. You can try and re-trigger "Linting Recipes" by typing `@BiocondaBot recheck`.

**Comment by Tomnl** [comment]
@BiocondaBot recheck

**Comment by Tomnl** [comment]
Thanks for the information @npavlovikj !

**Pull request merged**
