### PR TITLE
Add seqstats

### PR DESCRIPTION
**Pull request by vinisalazar**
Hi,

**I tried adding this in #21150 but tests failed because of a git subdirectory wasn't included in the tarball. It should be fixed now.** I decided to create a new PR because the repo has been updated since.

if this PR is merged, it will add a recipe for seqstats. The package is really simple so I believe it shouldn't cause any problems. However, it is my first time contributing to Bioconda, so let me know if I missed anything.

Side note: I am not a contributor to this package, I simply forked it and created a release to be able to write the recipe.

Thank you for any assistance you can provide,

V

----

> Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences**
      (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

> Everyone has access to the following BiocondaBot commands, which can be given in a comment:
>
>  * `@BiocondaBot please update` will cause the BiocondaBot to merge the master branch into a PR
>  * `@BiocondaBot please add label` will add the `please review & merge` label.
>  * `@BiocondaBot please fetch artifacts` will post links to packages and docker containers built by the CI system. You can use this to test packages locally before merging.
>
> For members of the Bioconda project, the following command is also available:
>
>  * `@BiocondaBot please merge` will cause packages/containers to be uploaded and a PR merged. Someone must approve a PR first! This has the benefit of not wasting CI build time required by manually merging PRs.
>
> If you have questions, please post them in gitter or ping `@bioconda/core` in a comment (if you are not able to directly ping `@bioconda/core` then the bot will repost your comment and enable pinging).

### CODE REVIEW

**Comment by vinisalazar** [comment]
@bioconda/core , I'm not sure why it does not find the gcc command, as I specified the compiler correctly (so I presume). Any thoughts on this?

Thanks

**Comment by vinisalazar** [comment]
I tried following the instructions [here](https://bioconda.github.io/contributor/troubleshooting.html#g-or-gcc-not-found) but they did not work. Any ideas?

Thank you

**Comment by dpryan79** [comment]
Your Makefile is hard-coding the compiler, which is causing the problem.

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Comment by vinisalazar** [comment]
Thank you @dpryan79 ! Lesson learned. Hope others find this package useful.

**Pull request merged**
