### PR TITLE
Removing export that pollutes conda env PATH

### PR DESCRIPTION
**Pull request by eggzilla**
Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it. Note that if you are not already a member of the bioconda project (meaning that you can't add this label), please ping `@bioconda/core` so that your PR can be reviewed and merged (please note if you'd like to be added to the bioconda project). Please see https://github.com/bioconda/bioconda-recipes/issues/15332 for more details.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by eggzilla** [comment]
Hi, i commented out following export in get_species_taxids.sh
export PATH=/bin:/usr/bin:/am/ncbiapdata/bin:$HOME/edirect:$PATH
After executing the command my environment has the system perl in the PATH with higher precedence than the one in the conda env. The script also works without this export.

**Comment by dpryan79** [comment]
Can you bump the build number?

**Comment by eggzilla** [comment]
I already did, it now strangely fails due to linting problems in other recipes.
Thanks for the quick response :-)

**Comment by dpryan79** [comment]
@christiam Can you have a look at this? I think it's fine but it'd be best if you had a look as well :)

**Comment by dpryan79** [comment]
I don't understand the linter some times, at least we can ignore that.

**Comment by christiam** [comment]
> @christiam Can you have a look at this? I think it's fine but it'd be best if you had a look as well :)

Changes look fine to me, thanks!

**Pull request merged**
