### PR TITLE
upgrade unicycler to 0.3.1

### PR DESCRIPTION
**Pull request by nekrut**
* [x] I have read the guidelines above.
* [x] This PR updates an existing recipe.

### CODE REVIEW

**Comment by bgruening** [comment]
Newer GCC is needed. Nothing we can do here :(
I will try to compile it locally and provide binaries as soon as I get some time.

**Comment by nekrut** [comment]
I can try to produce binaries if you point me to the right direction

**Comment by bgruening** [comment]
@nekrut https://github.com/galaxyproject/starforge

**Comment by nekrut** [comment]
@davebx -> can you see what @bgruening is referring to

**Comment by cbrueffer** [comment]
Unicycler was updated to 0.4.1 in 4903135666a4245f7996b07566050898757b1681, can this PR be closed?

**Comment by johanneskoester** [comment]
We have migrated our build system from Travis CI to Circle CI. If you would like to continue working on this PR, please update with latest upstream master and reopen this PR.

**Pull request closed without merging**
