### PR TITLE
Nanopolish bioconda update

### PR DESCRIPTION
**Pull request by paultsw**
:information_source:
Bioconda has finished the [GCC7 migration](https://github.com/bioconda/bioconda-recipes/issues/13578). If you are dealing with C/C++ or Python package it can be that you need to rebuild other dependent packages. [Bioconda utils - update-pinning](https://bioconda.github.io/updating.html#updating-recipes-for-a-pinning-change) will assist you with that. If you have any questions please use [issue 13578](https://github.com/bioconda/bioconda-recipes/issues/13578).

----------------

* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [X] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [X] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by paultsw** [comment]
@bgruening to be honest I'm actually not sure w/r/t the gcc exception for OS X. I'm updating the recipe primarily because we've just tagged a new release of nanopolish (v0.11.1) and wanted to be sure the bioconda release was as up-to-date as possible. As I only have access to a linux machine, I'm in favour of otherwise keeping the recipe as-is, aside from the sha256 hash and the bumped version. What's your opinion?

**Comment by bgruening** [comment]
Can we just try and if it does not work revert?

**Comment by bgruening** [comment]
In general, I'm fine with that. We should just remember to fix that at some point. Feel free to merge.

**Comment by paultsw** [comment]
Okay, I'll make a note to fix this for another day.

**Comment by PertuyF** [comment]
The exception is because `gcc` is [not supported for OSX](https://github.com/ContinuumIO/anaconda-issues/issues/10081) using the new compilers, and `nanopolish` does not build with `clang`. See #14014 and #14016 for details.

Using a selector on `libgcc` in run dependencies should be fine I guess.

@paultsw merging for you as I pass by

**Comment by PertuyF** [comment]
@bgruening looks like new packages are available in the channel, but CircleCi noticed that upload failed for Linux.
Is it normal?

**Pull request merged**
