### PR TITLE
Update LoomExperiment for R 3.5 to 1.0.4

### PR DESCRIPTION
**Pull request by nsoranzo**
This release contains important fixes for the export of
SingleCellExperiment objects to the Loom format.

xref. https://github.com/bioconda/bioconda-recipes/pull/13639

Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it. Note that if you are not already a member of the bioconda project (meaning that you can't add this label), please ping `@bioconda/core` so that your PR can be reviewed and merged (please note if you'd like to be added to the bioconda project). Please see https://github.com/bioconda/bioconda-recipes/issues/15332 for more details.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by dpryan79** [comment]
You might have to remove loomexperiment from the blacklist so it builds. The 3.9 version will fail, but we can forcibly merge it.

**Comment by nsoranzo** [comment]
@dpryan79 Thanks for the review and suggestion, I've removed it from blacklist and it built fine on R 3.5/BioC 3.8 on Linux, failed as expected on R 3.6/BioC 3.9.

**Comment by dpryan79** [comment]
Thanks @nsoranzo!

**Comment by nsoranzo** [comment]
Shoud I open a PR to revert this one after files are pushed to anaconda.org ?

**Comment by dpryan79** [comment]
Already on it

**Comment by nsoranzo** [comment]
Thanks for the super-fast turnaround!

**Pull request merged**
