### PR TITLE
Update hypercluster to 0.1.8

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`hypercluster`](https://bioconda.github.io/recipes/hypercluster/README.html): **0.1.3** &rarr; **0.1.8**

[install with bioconda](http://bioconda.github.io/recipes/hypercluster/README.html) [Conda](https://anaconda.org/bioconda/hypercluster/files)

Info | Link
-----|-----
Recipe | [`recipes/hypercluster`](https://github.com//bioconda/bioconda-recipes/tree/bump/hypercluster/recipes/hypercluster) (click to view/edit other files)
Releases |[https://pypi.org/pypi/hypercluster/json](https://pypi.org/pypi/hypercluster/json)
Recipe Maintainer(s) | @liliblu, @ruggleslab

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by dpryan79** [comment]
I'm not sure what the real issue is either. Perhaps the lack of an explicit python in the run section is causing issues.

**Comment by liliblu** [comment]
Sorry I messed up my setup.py! I fixed it and added a new release. Should work now.

**Comment by dpryan79** [comment]
Someone will have to add the "community" package to conda-forge.

**Comment by liliblu** [comment]
"community" comes from a package called python-louvain, (https://anaconda.org/conda-forge/python-louvain)
I am building the new skeleton with new dependencies now, that should work i think?

**Comment by liliblu** [comment]
I got it figured out! I still have to include the "requires pytest" but leave the test in the run_test.sh like how you put it. I think it's all good now!

**Pull request merged**
