### PR TITLE
Add recipe for libstatgen-1.0.5

### PR DESCRIPTION
**Pull request by dfornika**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by dfornika** [comment]
Build is failing with this message:

```
SamReferenceInfo.h:21:25: fatal error: StringArray.h: No such file or directory

 #include "StringArray.h"
```

I think the problem is that during the build, symbolic links to `StringArray.h` and other headers are created in the `include` directory of the source repo. But the compiler isn't looking them there while compiling `SamFileHeader.cpp`.

**Comment by npavlovikj** [comment]
@dfornika , is there a reason you are not building the newest 1.0.14 version of libstatgen ?

**Comment by dfornika** [comment]
Thanks @npavlovikj. I'm interested in this pipeline: https://github.com/CPTR-ReSeqTB/UVP, which lists 'Fastqvalidator Version 1.0.5' as a dependency. There is no 1.0.5 release of fastQValidator, but there is a 1.0.5 release of the libStatGen library that fastQValidator uses.

But I guess that isn't really a safe assumption, since fastQValidator pulls in libStatGen with a simple `git clone` of the master branch during its build process.

@mezewudo Could you comment on exactly what you're referring to when you list 'Fastqvalidator Version 1.0.5' as a dependency of https://github.com/CPTR-ReSeqTB/UVP?

**Comment by mezewudo** [comment]
You are right, there is no FastqValidator Version 1.0.5, there is only a
libStatGen library release of 1.0.5. I will update the UVP GitHub readme
document to reflect the accurate version of fastQvalidator implemented ---
Version 0.1.1

**Comment by dfornika** [comment]
This recipe was added in #12348

**Pull request closed without merging**
