### PR TITLE
chainmap: remove recipe (will be added on conda-forge)

### PR DESCRIPTION
**Pull request by astamminger**
* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [ ] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [X] This PR does something else (explain below).

There's a pending pull request for adding the chainmap-package to conda-forge: conda-forge/staged-recipes#8218 that guided me here :)

Is there anyone i should add to the recipe's maintainer list?

### CODE REVIEW

**Comment by dpryan79** [comment]
@bioconda/core Anyone want to be added to the maintainers on that?
@bgruening You want to merge that over on staged-recipes? This is certainly an optimal candidate for getting migrated.

**Comment by dpryan79** [comment]
@astamminger Can you ping me when that gets merged on staged-recipes? I'll merge this here then.

**Comment by astamminger** [comment]
@dpryan79 Sure, will do! :thumbsup:

**Comment by astamminger** [comment]
@dpryan79 Feedstock has been created (https://github.com/conda-forge/chainmap-feedstock) and I also added the missing versions (``1.0.2`` and ``1.0.3``). Should be good to merge, Thank you!

**Comment by dpryan79** [comment]
Great, thanks @astamminger!

**Pull request merged**
