### PR TITLE
MaxBin2 fixes; existing recipe leaves out core functionality

### PR DESCRIPTION
**Pull request by brwnj**
This doesn't build locally and other things fail when using
`simulate_travis.py`. Committing these changes for testing and comments.

* [x] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by colinbrislawn** [comment]
Thanks for the improvements Joe. I appreciate improvements that make it more compatible.

**Comment by brwnj** [comment]
For the OSX/macos build, we're hitting this snag again:

```
#include <thread>
         ^
```

**Comment by colinbrislawn** [comment]
I think this may build on OSX using gcc. That may be an alternative to dropping OSX support altogether.

**Comment by brwnj** [comment]
This is inconsistent. Should be add `ncurses` to linux build?

```
build:
  number: 1
  string: "ncurses{{CONDA_NCURSES}}_{{PKG_BUILDNUM}}"

requirements:
  build:
    - ncurses {{CONDA_NCURSES}}*
  run:
    - ncurses {{CONDA_NCURSES}}*
```

**Comment by brwnj** [comment]
@bioconda/all, any advice for addressing this issue:

```
UnsatisfiableError: The following specifications were found to be in conflict:
  - conda 4.2.15* -> enum34 -> ordereddict -> python 2.6* -> openssl 1.0.1*
  - python 3.6*
```

We're pulling the latest miniconda that is a py36 version and seems to be a problem.

**Comment by dpryan79** [comment]
Pull the latest `master` branch and merge that into this. Also, please note that you're notifying hundreds of people when you @ everyone.

**Pull request merged**
