### PR TITLE
Reinstate clever-toolkit: fix unnecessary python dependency, osx const correctness, clean up recipe

### PR DESCRIPTION
**Pull request by cpalmer718**
This PR addresses issues with the current [clever-toolkit](https://bitbucket.org/tobiasmarschall/clever-toolkit/src) recipe, mentioned in the relevant section of #36884.

- fix(osx): adjust const correctness of struct member function
  - the linux compiler doesn't care either way for whatever reason
- disable python build/host dependency entirely
  - this thing was being built against python versions, but is a C++ program that doesn't build against python at all. so basically CI cycles were just being burnt for no reason :(
- remove run dependency on make, bcftools
  - the other run dependencies are required in various scripts or called in subprocesses, but bcftools isn't anywhere in the repo
- try to pin runtime boost-cpp, zlib
- adjust assorted other dependencies
  - this may break matplotlib if it's actually requiring <3, but the linter seems very dead set on this one
- update source patching for future boost deprecations, include resolutions, etc.
- handle various linting failures
- add missing GPL3 license file

I'm honestly uncertain whether the other existing run dependencies are even really appropriate here. They're not technically required _per se_, but rather some scripts included in the package call them in subprocesses. This feels analogous to the CRAN "Suggests" dependencies, which are requirements only if you want the associated features. It seems like it might be appropriate to leave it up to the user if they want to install them, rather than automatically dragging all those other dependencies along with it. 

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by cpalmer718** [comment]
The patchfile is obviously much expanded. Most of it _could_ be upstream, but the project seems not to have had any changes for the last five years, and it seems unlikely. Some of this could be mitigated by instead pinning compiler version, though I'm very hesitant to do that in general. So either the source needs to be patched on the fly, or the package will not build on either linux or osx at this point.

**Comment by cpalmer718** [comment]
@BiocondaBot please add label addressed-bulk-skip

**Comment by cpalmer718** [comment]
Should be labeled `addressed-bulk-skip` but I don't have the power lol

**Comment by daler** [comment]
Awesome, thank you for this. You don't pick the easy ones!

Agreed on patching happening here just to get it working. And we don't really have a formal policy of how to handle/think about optional dependencies...so this all looks good.

**Review by daler — APPROVED** [review]

**Comment by daler** [comment]
@BiocondaBot please merge

**Pull request merged**
