### PR TITLE
update samtools 1.5 -> 1.6

### PR DESCRIPTION
**Pull request by tomkinsc**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

Release notes: https://github.com/samtools/samtools/releases/tag/1.6

### CODE REVIEW

**Comment by daler** [comment]
Aha! The new linting worked :)

(you'll need to pin bzip2 as well for this)

**Comment by tomkinsc** [comment]
Excellent! (Curious why the linter didn't complain about bzip2 though, is it not in our checks yet?)

**Comment by tomkinsc** [comment]
Nevermind, I answered by own question:
https://github.com/bioconda/bioconda-utils/blob/master/bioconda_utils/lint_functions.py#L328-L329

**Comment by daler** [comment]
You're right it should have, but due to historical baggage, the way bzip2 is pinned in env_matrix.yaml is slightly different and I haven't written the separate linter for it. Specifically, you have to pin them differently:

```yaml
- zlib {{ CONDA_ZLIB }}*
- {{ CONDA_BZIP2 }}
```

**Comment by johanneskoester** [comment]
@bgruening any reason for pinning bzip2 in a different way? It is a very new pin, so if that was an accident, I would be happy to fix it as soon as possible, before it occurs in many recipes.

**Comment by bgruening** [comment]
@johanneskoester mh, no this looks wrong. But I guess the * can be included in the variable.
Sorry if I did this.

**Comment by johanneskoester** [comment]
No problem, I'll fix it.

**Comment by johanneskoester** [comment]
See PR #6310.

**Pull request merged**
