### PR TITLE
Add recipe for tin-score-calculation

### PR DESCRIPTION
**Pull request by fgypas**
Add recipe for tin-score-calculation

### CODE REVIEW

**Comment by fgypas** [comment]
The missing dependency is added in conda-forge, but now I get a weird pip error. The dependency is CPython only so my guess is that it's related to this?

**Comment by dpryan79** [comment]
The error was due to the missing requirements.txt, which pip was looking for.

**Comment by fgypas** [comment]
@BiocondaBot please add label

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Pull request merged**
