### PR TITLE
Bump BioPhi to 1.0.3

### PR DESCRIPTION
**Pull request by prihoda**
Bump BioPhi to 1.0.3

### CODE REVIEW

**Comment by prihoda** [comment]
@BiocondaBot please add label

**Review by telatin — APPROVED** [review]

**Comment by telatin** [comment]
@Biocondabot please merge

**Comment by telatin** [comment]
> Bump BioPhi to 1.0.3

Hi there, are you aware of the autobump feature? Releasing a new version on github, if the appropriate pattern is used, will let biocondabot to open a PR on your behalf :)

**Comment by prihoda** [comment]
Hi @telatin, that's cool, I didn't know it works out-of-the-box. I see that there's already an autobump PR open, but it failed: https://github.com/bioconda/bioconda-recipes/pull/30486

Please let me know if you need anything from me at this point. Next time I'll just wait for the autobump PR 👍

**Pull request merged**
