### PR TITLE
update frogsv2.0.1: Manage rdptools all versions

### PR DESCRIPTION
**Pull request by ValentinMarcon**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

(See also https://github.com/oinizan/FROGS/commit/a3fbce06cf1e021248180aa312d1c098fdd8b679 and https://github.com/oinizan/FROGS/commit/d737609359bc1f433f2155f23739c125871b1287 to understand v2.0.1b of FROGS)

### CODE REVIEW

**Comment by ValentinMarcon** [comment]
I dont think so. 
Because our recipe dont work anymore. 
In fact, their is a new version of rdptools, our old recipe will install it (rdptools >2.1.2 on meta. yaml) and exist

**Comment by bgruening** [comment]
@ValentinMarcon but then we should fix the old recipe and not overwrite it with the new version isn't it?
You can fix the old recipe by pinning rdptools to `<2.1.2`.

**Comment by ValentinMarcon** [comment]
I'm sorry, I'm not sure to understand. 

Is the version 2.0.1b of FROGS archive that is a problem?

We would like to have these corrections (rdptools and FROGS 2.0.1b patch) installed when we choose to install FROGS 2.0.1 on Bioconda. That is to replace the older version (not working anymore) by this one, still 2.0.1.

**Comment by dpryan79** [comment]
No longer needed

**Pull request closed without merging**
