### PR TITLE
Update augur to 11.2.0

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`augur`](https://bioconda.github.io/recipes/augur/README.html): **11.1.2** &rarr; **11.2.0**

[install with bioconda](http://bioconda.github.io/recipes/augur/README.html) [Conda](https://anaconda.org/bioconda/augur/files)

Info | Link
-----|-----
Recipe | [`recipes/augur`](https://github.com//bioconda/bioconda-recipes/tree/bump/augur/recipes/augur) (click to view/edit other files)
Releases |[https://pypi.org/pypi/nextstrain-augur/json](https://pypi.org/pypi/nextstrain-augur/json)
Recipe Maintainer(s) | @huddlej, @tsibley

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by mirand863** [comment]
@bioconda-bot please fetch artifacts

**Review by mirand863 — APPROVED** [review]

**Comment by mirand863** [comment]
@bioconda-bot please merge

**Comment by mirand863** [comment]
@bioconda-bot please merge

**Comment by huddlej** [comment]
@mirand863, do you have any advice about how to proceed after this error? Do we have a way of knowing what the error was?

**Pull request merged**
