### PR TITLE
Correct MinVar version 2.1.1

### PR DESCRIPTION
**Pull request by ozagordi**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.

### CODE REVIEW

**Comment by cbrueffer** [comment]
Could you be more specific what this fixes and how?

Versions generally shouldn't go backwards; if something needs to be fixed in an earlier package I think the better way is to add a 2.1.1 subdirectory with the corrected 2.1.1 recipe.

**Comment by ozagordi** [comment]
2.1.1 was already present, but the meta.yaml pointed to the wrong tarball. As a consequence, the bioconda package 2.1.1 actually contains the wrong version. The reason for this new build is to correct that mistake. This is what I understood from @bgruening, but I might have misunderstood.

**Comment by cbrueffer** [comment]
Makes sense! I still think this should go into a separate subdir though, otherwise this gets very confusing for the next person doing an update.

**Comment by ozagordi** [comment]
I’m not sure I understand how. One subdir for each old version? But how would bioconda build then?

**Comment by cbrueffer** [comment]
Well, one for each old version you want to touch. An example is Picard: https://github.com/bioconda/bioconda-recipes/tree/master/recipes/picard

**Comment by ozagordi** [comment]
I can organise the recipe like this, but I was under the impression that the subdirs are not built, i.e. they are just a way to save the old versions. Am I wrong? Further, I already opened #7355 to update 2.1.1. How should I proceed?

**Comment by cbrueffer** [comment]
Subdirs are built if something in them changes that requires a rebuild (e.g. build number increase). In principle you can fix both versions in this PR and just close the other one (or the other way around).

**Pull request closed without merging**
