### PR TITLE
[BULK] Bulk update 191018b

### PR DESCRIPTION
**Pull request by dpryan79**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [x] This PR does something else (explain below).

This sets more packages to be R 3.5 only (those that otherwise fail in `bulk`). Also attempts to fix some random build issues in bioconductor-flowdensity, bioconductor-pics, and bioconductor-motiv. Also bumps the version of bioconductor-methylkit.

Please don't merge until the current `bulk` build finishes, as I'll update recipes in this PR as they're built on circleci.

### CODE REVIEW

**Comment by dpryan79** [comment]
I'll rebase this real quick and then it's good to go.

**Comment by nsoranzo** [comment]
@dpryan79 Can you add `- rbase >=3.5` also to bioconductor-scater ? I see this in the circleci logs:
```
Attempting to finalize metadata for bioconductor-scater
Solving environment: ...working... done
Solving environment: ...working... failed
Solving environment: ...working... failed
Returning non-final recipe for bioconductor-scater-1.8.4-r341_0; one or more dependencies was unsatisfiable:
Build: None
Host: r-base, r-base
Solving environment: ...working... failed
Solving environment: ...working... failed
```

**Comment by dpryan79** [comment]
Yes! I'll see if there are any other packages using beachmat too.

**Comment by dpryan79** [comment]
bioconductor-scran was another one. Thanks for pointing it out!

**Comment by nsoranzo** [comment]
bioconductor-scater will still need https://github.com/conda-forge/r-vipor-feedstock/pull/1 , https://github.com/conda-forge/r-shinydashboard-feedstock/pull/2 , https://github.com/conda-forge/r-beeswarm-feedstock/pull/1 and then a PR for r-ggbeeswarm , but it's getting closer.

**Comment by nsoranzo** [comment]
Also `bioconductor-mast` needs it, I think:
```
conda.exceptions.UnsatisfiableError: The following specifications were found to be in conflict:

  - bioconductor-singlecellexperiment[version='>=1.2.0,<1.4.0'] -> r-base[version='>=3.5.1,<3.5.2.0a0']

  - r-base=3.4.1
```

**Comment by nsoranzo** [comment]
And `bioconductor-sc3`.

**Comment by dpryan79** [comment]
Sc3 should be updated in that PR. I’m out of the office now, can you check on those and update that branch if needed?

**Comment by nsoranzo** [comment]
For bioconductor-mzr I think we need https://github.com/sneumann/mzR/pull/179, which will probably be available only in the next Bioconductor release. We can try to backport the patch or blacklist the package.

**Comment by nsoranzo** [comment]
@dpryan79 Pushed.

**Comment by dpryan79** [comment]
Thanks Nicola!

**Comment by bgruening** [comment]
Thanks both!

**Pull request merged**
