### PR TITLE
Update TELR dependencies

### PR DESCRIPTION
**Pull request by shunhuahan**
- TELR experienced reproducible `samtools sort: truncated file. Aborting` error using samtools v1.13. The error can be fixed using samtools v1.9.
- This commit updates TELR software dependency list.
----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by shunhuahan** [comment]
- Local testing using artifacts is finished successfully.

**Comment by shunhuahan** [comment]
@BiocondaBot please merge

**Comment by shunhuahan** [comment]
@BiocondaBot please add label

**Comment by jmarshall** [comment]
> TELR experienced reproducible `samtools sort: truncated file. Aborting` error using samtools v1.13. 

Do you have an example of the intermediate file that TELR is passing to `samtools sort` that produces this problem?

**Comment by shunhuahan** [comment]
- @jmarshall The original BAM file is 20GB and is a bit too large for me to share over the internet. I have tried creating the subsampled dataset but the subsampled dataset won't trigger the error message. Could you send me an email so I can share the bam file using iCloud drive? My email address is sh60271@uga.edu. Thanks for helping me with the issue!
- To test which samtools versions have issues on this dataset. I have created conda environment with samtools v1.9, v1.10, v1.11, v1.12, v1.13 and used following command to do `samtools sort`.
```
conda activate samtools_1.x
samtools sort -@ $SLURM_NTASKS -o test.bam 50x_diploid_hom.lr.tmp.bam
```
- The command failed with following error messages using samtools v1.10 to v1.13. It only worked using samtools v1.9.
```
(base) sh60271@ra4-16 intermediate_files$ conda activate samtools_1.13
(samtools_1.13) sh60271@ra4-16 intermediate_files$ samtools sort -@ $SLURM_NTASKS -o test.bam 50x_diploid_hom.lr.tmp.bam
samtools sort: truncated file. Aborting

(samtools_1.13) sh60271@ra4-16 intermediate_files$ conda activate samtools_1.12
(samtools_1.12) sh60271@ra4-16 intermediate_files$ samtools sort -@ $SLURM_NTASKS -o test.bam 50x_diploid_hom.lr.tmp.bam
samtools sort: truncated file. Aborting

(samtools_1.12) sh60271@ra4-16 intermediate_files$ conda activate samtools_1.11
(samtools_1.11) sh60271@ra4-16 intermediate_files$ samtools sort -@ $SLURM_NTASKS -o test.bam 50x_diploid_hom.lr.tmp.bam
[E::sam_parse1] incomplete aux field
[E::sam_parse1] incomplete aux field
samtools sort: truncated file. Aborting
[E::sam_parse1] incomplete aux field

(samtools_1.11) sh60271@ra4-16 intermediate_files$ conda activate samtools_1.10
(samtools_1.10) sh60271@ra4-16 intermediate_files$ samtools sort -@ $SLURM_NTASKS -o test.bam 50x_diploid_hom.lr.tmp.bam
[E::sam_parse1] incomplete aux field
[E::sam_parse1] incomplete aux field
[E::sam_parse1] incomplete aux field
[E::sam_parse1] incomplete aux field
[E::sam_parse1] incomplete aux field
[E::sam_parse1] incomplete aux field
samtools sort: truncated file. Aborting
[E::sam_parse1] incomplete aux field
```
- Note: this is a simulated dataset, but the issue can also be shown on real drosophila long read dataset as well.

**Comment by jmarshall** [comment]
Thanks, I've tried it with the test file and this is all quite interesting :smile:

It turns out that _50x_diploid_hom.lr.tmp.bam_ is in fact a SAM file. The `incomplete aux field` errors you see with 1.10 and 1.11 are a bug in samtools's multi-threaded SAM reader (only; BAM reading was unaffected), which was fixed in 1.12 by samtools/htslib#1149.

The `samtools sort: truncated file. Aborting` message is not a very helpful error message because the multi-threaded reader is not able to report a line number accurately. If you drop the `-@` option you get a more useful message pointing you at a particular line of _50x_diploid_hom.lr.tmp.bam_ that is the first line that has a MAPQ value of -2147483648. This is invalid for MAPQ which must be in the range 0…255, which is enforced by samtools 1.10 and later — while samtools 1.9 probably just incorrectly treated the invalid value as 0.

This invalid MAPQ value is a known ngmlr bug: see philres/ngmlr#75 and its many duplicates, and the proposed fix in philres/ngmlr#96.

I've now proposed #29966 to apply this fix to bioconda's ngmlr package, or we might be able to encourage upstream ngmlr to make a new release with this fixed. So in the near future you would be able to update TELR's dependencies to `ngmlr >= 0.2.8-or-so` and `samtools >= 1.12` to resolve these issues.

Or you might wish to apply this PR now (perhaps adding a comment that it is temporary) with a view to updating TELR's dependencies again when ngmlr has been updated, one way or another.

(I've been meaning to look into this `MAPQ=-2147483648` thing for a while… thanks for the motivation and test file! Incidentally a lot of lines in the SAM data file end with an extra tab, and I am surprised this doesn't cause other parsing errors. This may be another minor ngmlr issue…)

**Comment by shunhuahan** [comment]
- @jmarshall Thanks so much for doing a deep dive on this issue. Your assessment is very informative. Looks like fixing ngmlr MAPQ output bug and using `samtools >= 1.12` is the long term better strategy.
- I have included comments in the current recipe about this being a temporary fix and both samtools and nglmr dependency lines need to be updated in the future.
- I would hope that we can apply this PR now so that people have access to a working version of TELR conda package (since the current version would crash almost definitely). I will pay attention to any future updates on nglmr (whether on bioconda or at the source repo) and update TELR recipe accordingly.

**Review by jmarshall — APPROVED** [review]

**Pull request merged**
