### PR TITLE
Update metaquantome to 2.0.1

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`metaquantome`](https://bioconda.github.io/recipes/metaquantome/README.html): **2.0.0** &rarr; **2.0.1**

[install with bioconda](http://bioconda.github.io/recipes/metaquantome/README.html) [Conda](https://anaconda.org/bioconda/metaquantome/files)

Info | Link
-----|-----
Recipe | [`recipes/metaquantome`](https://github.com//bioconda/bioconda-recipes/tree/bump/metaquantome/recipes/metaquantome) (click to view/edit other files)
Releases |[https://github.com/galaxyproteomics/metaquantome/tags](https://github.com/galaxyproteomics/metaquantome/tags)
Author | `@galaxyproteomics`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by jj-umn** [comment]
Need help with this.    This builds locally.  The bioconda-test is failing in container testing.

**Comment by bgruening** [comment]
14:59:04 BIOCONDA INFO (ERR) [Feb 11 14:59:04] SERR UnicodeEncodeError: 'ascii' codec can't encode character '\u2192' in position 504: ordinal not in range(128)
14:59:04 BIOCONDA INFO (ERR) [Feb 11 14:59:04] ERRO Task processing failed: Unexpected exit code [1] of container [f1febbcb8b04 step-092a678a9b], container preserved
.14:59:37 BIOCONDA INFO (OUT) .......

**Comment by bgruening** [comment]
It's some unicode error :-(

**Comment by jj-umn** [comment]
@bgruening  I saw that unicode error too.   Any idea on how best to debug that?   I've had issues trying to get the circle ci code running locally, and I'm not well versed in container technology.

**Comment by jj-umn** [comment]
The README.md has unicode symbols.   I'll remove those and make a new release.

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
@bioconda-bot please merge

**Pull request merged**
