### PR TITLE
noarch: generic

### PR DESCRIPTION
**Pull request by t-neumann**
Describe your pull request here

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by t-neumann** [comment]
@bioconda-bot please fetch artifacts

**Comment by bgruening** [comment]
You need to wait until its green before you can get the artifacts ...

**Comment by t-neumann** [comment]
@bgruening Yeah I read the readme too late - embarrassing ^^ sorry

**Comment by t-neumann** [comment]
@bgruening changing the `noarch: python` to `noarch: generic` now causes the build to fail, it was the only thing I touched apart from the build number

**Comment by bgruening** [comment]
@bioconda-bot please fetch artifacts

**Comment by t-neumann** [comment]
@bgruening I'm a bit puzzled - I simply moved the build script from the `meta.yml` `script:` section into a separate `build.sh` script. Left everything else as is.

But now the executable rights seem to have been retained:

```
curl "https://103954-42372094-gh.circle-artifacts.com/0/tmp/artifacts/images/slamdunk%3A0.4.2--py_1.tar.gz" | gzip -dc | docker load

docker run -ti e3b8ea97a400 /bin/bash

ls -lah /usr/local/lib/python3.7/site-packages/slamdunk/plot

total 128
drwxr-xr-x    3 root     root        4.0K Apr 15 18:18 .
drwxr-xr-x    8 root     root        4.0K Apr 15 18:18 ..
-rwxrwxr-x    1 root     root        2.9K Apr 15 18:08 PCAPlotter.R
-rwxrwxr-x    1 root     root        5.9K Apr 15 18:08 SNPeval.R
-rw-rw-r--    1 root     root           0 Apr 15 18:08 __init__.py
drwxr-xr-x    2 root     root        4.0K Apr 15 18:18 __pycache__
-rw-rw-r--    1 root     root        1.2K Apr 15 18:08 checkLibraries.R
-rwxrwxr-x    1 root     root        3.8K Apr 15 18:08 compute_context_TC_rates.R
-rwxrwxr-x    1 root     root        5.1K Apr 15 18:08 compute_conversion_rate_mle.R
-rwxrwxr-x    1 root     root        5.9K Apr 15 18:08 compute_halflifes.R
-rwxrwxr-x    1 root     root        4.5K Apr 15 18:08 compute_overall_rates.R
-rwxrwxr-x    1 root     root        4.1K Apr 15 18:08 compute_sample_comparison_statistics.R
-rwxrwxr-x    1 root     root        3.2K Apr 15 18:08 conversion_per_read_position.R
-rwxrwxr-x    1 root     root        8.1K Apr 15 18:08 eval_conversion_rate_plots.R
-rwxrwxr-x    1 root     root       11.2K Apr 15 18:08 eval_halflife_per_gene_plots.R
-rwxrwxr-x    1 root     root        7.3K Apr 15 18:08 eval_halflifes_error_plot.R
-rwxrwxr-x    1 root     root        6.9K Apr 15 18:08 globalRatePlotter.R
-rwxrwxr-x    1 root     root       11.6K Apr 15 18:08 merge_rate_files.R
-rwxrwxr-x    1 root     root        5.4K Apr 15 18:08 splash_eval_count_files.R
```

This behavior does not seem consistent to me at all.

**Comment by t-neumann** [comment]
Anyways now the steps that were broken and are working again.

**Comment by bgruening** [comment]
@t-neumann you can move it into the mata.yml and just bump the version and see if this still fixes it.
Maybe a conda-build version was just "broken"?

**Comment by t-neumann** [comment]
@bioconda-bot please fetch artifacts

**Comment by t-neumann** [comment]
@bgruening Yes indeed I reverted everything and just bumped the build number and now it seems to work.

**Pull request merged**
