### PR TITLE
update SmallGenomeUtilities to 0.3.2

### PR DESCRIPTION
**Pull request by DrYak**
- fix `N` where `-` should be needed
 - new aln2basecnt and gather_coverage experimental tools
 - HACK the openssl version
    - used by older htslib
    - used by older samtools
    - used by older pysam
   isn't pinned correctly.

Describe your pull request here

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by DrYak** [comment]
@BiocondaBot please add label

**Review by dpryan79 — APPROVED** [review]

**Comment by jmarshall** [comment]
```
# HACK currently htslib pins it wrong
- openssl <1.1.0
```

That's an inflexible way to work around a problem.

Which version of htslib are you saying is wrong? Are you saying this is a bug in the htslib package? Why are you getting htslib-1.7? Have you considered alternatives like requiring a more recent version of htslib?

**Comment by DrYak** [comment]
> That's an inflexible way to work around a problem.

Yup, but after trying for a long time pinning stuff around, I didn't manage to find any other way to force _libcrypto.so.1.0.0_ (required by htslib/smatools used by pysam).

We'll be releasing 0.3.3 soon anyway (will include a tool to analyse frameshifting deletions requested to us by GISAID) I hope by then the htslib packeg will be fixed.

**Comment by dpryan79** [comment]
htslib has been fixed for a long time, I'm not sure how you're still getting an old version pulled in. I updated the pysam restriction to ensure you're getting a fixed htslib package.

**Comment by DrYak** [comment]
I tried the htslib >=0.16 yesterday, but it was still crashing my _mulled_ test (not the circleci).

**Comment by dpryan79** [comment]
You wanted pysam >=0.16. Pysam is built against a specific htslib version range and >=0.16 happens to be built against a range where we had fixed the openssl pinning in all of the builds. I look forward to some day having the metadata patched for this stuff.

**Review by bernt-matthias — APPROVED** [review]

**Comment by DrYak** [comment]
I don't know why "pysam >=0.16" kept failing yesterday when I tried that.
(and trying manually to create an environment in "conda create" to analyse why I was getting the wrong version caused multiple version conflict)

**Comment by DrYak** [comment]
@BiocondaBot please merge

**Pull request merged**
