### PR TITLE
trinity: fix for installation paths containing @

### PR DESCRIPTION
**Pull request by bernt-matthias**
https://github.com/bioconda/bioconda-recipes/issues/14466

:information_source:
If this is your first pull request to Bioconda please ping `@bioconda/core` so it can be reviewed and to request being added as a member of the Bioconda team. Members of the Bioconda team are able to merge their own pull requests once tests and linting have passed.

----------------

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by epruesse** [comment]
Just saw that Trinity doesn't even add hard coded paths. It's installed into `/opt` by the package script and the way the paths are fixed isn't good. This should work. $ROOTDIR points to the real location of the `Trinity` perl script. Since that's installed into `$PREFIX/opt/trinity`, `$ROOTDIR/../../` is the env root. From there, Trimmomatic is in `share/trimmomatic`. This will work with any env name, including "Wh@t's thi$s me()[]s?".

**Comment by epruesse** [comment]
It won't compile because it's resetting the compiler internally:
```
Using gnu compiler for Inchworm and Chrysalis
```

That probably needs to be overridden. And then tested. Can you check into it @bernt-matthias?

**Comment by dpryan79** [comment]
I think this was recently done in another PR. Can you confirm whether this is still needed?

**Comment by bernt-matthias** [comment]
Seems that I forgot about my own PR https://github.com/bioconda/bioconda-recipes/pull/16852 :)

**Comment by dpryan79** [comment]
You know you're involved in a lot of things when... :)

**Pull request closed without merging**
