### PR TITLE
[yacrd] add yacrd 0.6.0 version

### PR DESCRIPTION
**Pull request by natir**
Add yacrd 0.6.0 version of yacrd.

I don't know if I made the good thing for not compatible version.

----

> Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it.

* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [ ] This PR adds a new recipe.
* [X] AFAIK, this recipe **is directly relevant to the biological sciences**
      (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [X] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

> Everyone has access to the following BiocondaBot commands, which can be given in a comment:
>
>  * `@BiocondaBot please update` will cause the BiocondaBot to merge the master branch into a PR
>  * `@BiocondaBot please add label` will add the `please review & merge` label.
>  * `@BiocondaBot please fetch artifacts` will post links to packages and docker containers built by the CI system. You can use this to test packages locally before merging.
>
> For members of the Bioconda project, the following command is also available:
>
>  * `@BiocondaBot please merge` will cause packages/containers to be uploaded and a PR merged. Someone must approve a PR first! This has the benefit of not wasting CI build time required by manually merging PRs.
>
> If you have questions, please post them in gitter or ping `@bioconda/core` in a comment (if you are not able to directly ping `@bioconda/core` then the bot will repost your comment and enable pinging).

### CODE REVIEW

**Comment by natir** [comment]
@BiocondaBot please add label

**Comment by dpryan79** [comment]
@bioconda-bot please fetch artefacts

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Comment by natir** [comment]
Thank @dpryan79

**Comment by natir** [comment]
Hi @dpryan79, 

I can't update yacrd to 0.6 via conda.

When I run `conda search yacrd` i get:
```
# Name                       Version           Build  Channel             
yacrd                            0.2               0  bioconda            
yacrd                            0.2      h470a237_1  bioconda            
yacrd                          0.2.1      h470a237_0  bioconda            
yacrd                            0.3      h2c42bab_1  bioconda            
yacrd                            0.4      h2c42bab_1  bioconda            
yacrd                          0.4.1      h2c42bab_1  bioconda            
yacrd                          0.5.1      hd051131_1  bioconda
```

It's maybe because the recipes architecture isn't clean:
```
├── 0.4.1
│   ├── build.sh
│   └── meta.yaml
├── 0.5.1
│   ├── build.sh
│   └── meta.yaml
├── build.sh
└── meta.yaml
```

I want version 0.4.1 and 0.5.1 are still available, can I remove 0.4.1 and 0.5.1 directory, but keep this version available?

**Comment by dpryan79** [comment]
The worldwide cache of conda packages is updated every ~20 minutes, so it can take about that long for things to appear. For what it's worth 0.6.0 now shows up for me.

**Comment by natir** [comment]
Thanks.

I'm sorry I used up your time for nothing.

**Pull request merged**
