### PR TITLE
lint setuptools args: recipes "f"

### PR DESCRIPTION
**Pull request by mbargull**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [x] This PR does something else (explain below).

Lint fixes, cleanup.

### CODE REVIEW

**Comment by mbargull** [comment]
FastaIndex was previously build for Python 3, too. FastaIndex only supports Python 2, though. Can we remove all Python 3 builds of `fastaindex` from the channel? @johanneskoester @bgruening

**Comment by mbargull** [comment]
Looking at the download counts, some people downloaded those `fastaindex` builds...

**Comment by bgruening** [comment]
Is it ok, when we mark these packages as broken on anaconda.org?

**Comment by mbargull** [comment]
Yes, I please. I completely forgot about channel labels.

**Comment by bgruening** [comment]
Done! Thanks @mbargull!

**Pull request merged**
