### PR TITLE
update stream_atac to 0.3.5

### PR DESCRIPTION
**Pull request by huidongchen**
Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it. Note that if you are not already a member of the bioconda project (meaning that you can't add this label), please ping `@bioconda/core` so that your PR can be reviewed and merged (please note if you'd like to be added to the bioconda project). Please see https://github.com/bioconda/bioconda-recipes/issues/15332 for more details.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by huidongchen** [comment]
Hi Devon @dpryan79 ,

Somehow the new version 0.3.5 of stream_atac package is only available in Linux, but in macos.
https://anaconda.org/bioconda/stream_atac
Screen Shot 2019-11-21 at 10 52 48 AM

 Could you help me figure it out? (I do notice another weird thing. The bioconda-test of previous commit [0afc075](https://github.com/bioconda/bioconda-recipes/commit/0afc0757fde06a46c546f7707e0a43c347fc1ef6) seems to be still running https://github.com/bioconda/bioconda-recipes/runs/308867569 . Not sure if this is causing the issue)

Your help will be greatly appreciated.

**Comment by dpryan79** [comment]
You have it skipping OSX, so it should never be built there. I've killed that circleci job, thanks for letting me know.

**Comment by huidongchen** [comment]
Thanks for your prompt reply! Is there anything i need to do to get the new version of stream_atac package available in macos system?

**Comment by dpryan79** [comment]
Make a new PR bumping the build number and removing osx from `skip: True`.

**Comment by huidongchen** [comment]
Thanks for the tips.

I have made a new PR #18823 

But it looks like https://github.com/bioconda/bioconda-recipes/runs/308867569 still doen't get killed yet.

**Comment by dpryan79** [comment]
Circleci doesn't always update github when things are cancelled.

**Comment by huidongchen** [comment]
Good to know! Thanks!

**Pull request merged**
