### PR TITLE
Update ryuto to 1.6.2

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`ryuto`](https://bioconda.github.io/recipes/ryuto/README.html): **1.6.1** &rarr; **1.6.2**

[install with bioconda](http://bioconda.github.io/recipes/ryuto/README.html) [Conda](https://anaconda.org/bioconda/ryuto/files)

Info | Link
-----|-----
Recipe | [`recipes/ryuto`](https://github.com//bioconda/bioconda-recipes/tree/bump/ryuto/recipes/ryuto) (click to view/edit other files)
Releases |[https://github.com/studla/RYUTO/tags](https://github.com/studla/RYUTO/tags)
Author | `@studla`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by TGatter** [comment]
@bioconda-bot please fetch artifacts

**Comment by TGatter** [comment]
@bioconda-bot please fetch artifacts

**Comment by TGatter** [comment]
@BiocondaBot please add label

**Review by rpetit3 — APPROVED** [review]

**Comment by rpetit3** [comment]
@BiocondaBot please merge

**Pull request merged**
