### PR TITLE
Update lofreq to 2.1.3.1 with python 3 support

### PR DESCRIPTION
**Pull request by ozagordi**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by ozagordi** [comment]
Hi @bgruening.
By merging this, I would be able to add lofreq as dependency of MinVar (PR #4955).

Thanks.

**Comment by bgruening** [comment]
@ozagordi the samtools dependency is not needed anymore? In the old recipe was samtools compiled for linux?

**Comment by ozagordi** [comment]
In the old version samtools was not listed as a dependency, but `build.sh` would download, compile and link it (only in the linux version). Same story for htslib.

**Comment by bgruening** [comment]
@ozagordi and this changed? Because you have not defined samtools as dependency, correct?

**Comment by ozagordi** [comment]
This version uses compiled binaries provided by the maintainer for both linux and osx, so there is no need to define samtools as dependency.

**Comment by bgruening** [comment]
@ozagordi ok, just double checking :)

**Pull request merged**
