### PR TITLE
Update gdk-pixbuf/meta.yaml

### PR DESCRIPTION
**Pull request by ThomasWollmann**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by ThomasWollmann** [comment]
Why does it try to compile it with Python 3 on OSX?

**Comment by bgruening** [comment]
Not sure, can you try to skip py3k?

**Comment by ThomasWollmann** [comment]
Now stuck with the good old: GLIB 2.37.6 or better is required.

**Comment by ThomasWollmann** [comment]
I switched to a more recent GLIB version. However in OSX it can't find it. @bgruening is there an additional env variable I have to set for OSX like LD_LIBRARY_PATH during runtime?

**Comment by johanneskoester** [comment]
Maybe there is a dedicated argument in the configure script?
Further, the common style is to add a `# ` in front of the selectors.

A general question: is there a specific reason for the update? I am asking because in the long run this recipe should be moved over to conda-forge, because it is not bio-related.

**Comment by ThomasWollmann** [comment]
@johanneskoester  I'm not aware of a special argument.
I have a coworkers who use mac and analyse whole slide images with openslide. gdk-pixbuf is a dependency of openslide.

**Comment by johanneskoester** [comment]
Ok. If we manage to fix this I'm fine with keeping it for now until it is finally moved over to conda-forge (which will still allow openslide to depend on it of course). @bioconda/osx maybe you can help with the osx problem?

**Comment by acaprez** [comment]
I was able to build it ok on OS X by tweaking a couple of things:
1)  Add `${PREFIX}/lib` to the rpath at link-time by changing `LDFLAGS` to:
`LDFLAGS="-L$PREFIX/lib -Wl,-rpath ${PREFIX}/lib"`
2)  Fix the version of `gettext` used to 0.19.7 for both the build and run requirements, i.e.
`gettext ==0.19.7 # [osx]`
This is needed because `glib` was apparently built against 0.19.7, and they incremented the version in the SONAME for `libintl` from 8 to 9 between 0.19.7 and 0.19.8.

**Pull request merged**
