### PR TITLE
fix fastspar

### PR DESCRIPTION
**Pull request by epruesse**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by epruesse** [comment]
```
configure.ac:21: error: possibly undefined macro: AC_MSG_ERROR
```
ping @scwatts

**Comment by scwatts** [comment]
Hi Elmar, thank you for your ongoing effort in maintaining the fastspar bioconda recipe. You seem to have everything worked out here. Just to note, the `m4/ax_blas.m4` macro is fixed upstream in https://github.com/scwatts/fastspar/commit/7a162ba9bdae27724dcff951834b247f96d5c99c and is now included from the `v0.0.8` release of `FastSpar`.

Also thanks for the advice regarding source distributions - I've made some minor commits to the code base so that `make distcheck` now works and I'll ensure future releases will have a source distribution

**Comment by epruesse** [comment]
@scwatts Yes ... it just took me a while to realize that the ax_blas.m4 just contained the string ax_blas.m4, and that the commit fixing that was past the last release. I guess I could have asked for a 0.0.8, but this was easy enough.

**Comment by dpryan79** [comment]
No longer needed, closing

**Pull request closed without merging**
