### PR TITLE
csvtk 0.18.2

### PR DESCRIPTION
**Pull request by shenwei356**
Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it. Note that if you are not already a member of the bioconda project (meaning that you can't add this label), please ping `@bioconda/core` so that your PR can be reviewed and merged (please note if you'd like to be added to the bioconda project). Please see https://github.com/bioconda/bioconda-recipes/issues/15332 for more details.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by shenwei356** [comment]
I'm confused at the linting reports, should or should not add a noarch section? I can't find a good example similar to my tools which provide binaries for different architectures.

**Comment by shenwei356** [comment]
I'm confused at the linting reports, should or should not add a noarch section? I can't find a good example similar to my tools which provide binaries for different architectures.

**Comment by dpryan79** [comment]
Ah, you can ignore the linting report, I think someone notified @epruesse of this bug on gitter (if not, I just did :) ).

Is it possible to build this from source instead of distributing a binary?

**Comment by dpryan79** [comment]
Ah, it's written in Go, so statically linked to everything then, so I guess binaries aren't really an issue.

**Comment by dpryan79** [comment]
@bioconda-bot merge

**Comment by dpryan79** [comment]
As an aside, we should probably migrate this to conda-forge, since it has a larger audience then just us bio-folks.

**Comment by shenwei356** [comment]
Thanks @dpryan79 !

**Pull request merged**
