### PR TITLE
Update vamb to 3.0.2

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`vamb`](https://bioconda.github.io/recipes/vamb/README.html): **3.0.1** &rarr; **3.0.2**

[install with bioconda](http://bioconda.github.io/recipes/vamb/README.html) [Conda](https://anaconda.org/bioconda/vamb/files)

Info | Link
-----|-----
Recipe | [`recipes/vamb`](https://github.com//bioconda/bioconda-recipes/tree/bump/vamb/recipes/vamb) (click to view/edit other files)
Releases |[https://github.com/RasmussenLab/vamb/tags](https://github.com/RasmussenLab/vamb/tags)
Author | `@RasmussenLab`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by simonrasmu** [comment]
Can requirements in the meta.yaml be changed to: 
numpy>=1.15
torchvision>=0.6
pytorch>=1.4
pysam>=0.14

Ie. also changing from 'pytorch-cpu' to just 'pytorch' ? This allows VAMB to run with GPU support as well.

**Comment by simonrasmu** [comment]
Made a PR with the included changes

**Comment by dpryan79** [comment]
I think switching to pytorch breaks it since it then needs a GPU for the testing to work, or at least that's my recollection. We can try that though.

**Comment by simonrasmu** [comment]
Hi Devon,

Thanks for your reply! I am not familiar with how to test it on bioconda, but I am using pytorch from conda without/with a GPU and it works fine. Is it the build of the conda environment that breaks? I build conda environments on our own HPC that build and can run our package (VAMB) without any problems. Ie for our snakemake pipeline (using snakemake and conda):

cat vamb/workflow/envs/vamb.yaml
name: vamb
channels:
  - bioconda
  - pytorch
dependencies:
  - pytorch
  - torchvision
  - cudatoolkit=10.2
  - vamb=3.0.2

It doesn’t work atm because vamb=3.0.2 doesn’t exist on conda (yet) but the conda environment without builds perfectly fine.

Let me know if there is something I can do to help

Best,

Simon

Simon Rasmussen, Associate Professor, Ph.D.
Novo Nordisk Foundation Center for Protein Research
Faculty of Health and Medical Sciences, University of Copenhagen,
Blegdamsvej 3A, DK-2200 Copenhagen, Denmark
Reception tel: +45-3532500, direct +45-35332159
Email: simon.rasmussen@cpr.ku.dk, web: www.cpr.ku.dk

**Comment by simonrasmu** [comment]
Looks like it is installing python-3.8, can it be enforced to stay with python3.7?

**Comment by dpryan79** [comment]
Sure, is this actually incompatible with python 3.8? The current issue is that torchvision needs to be updated in conda-forge

**Comment by simonrasmu** [comment]
That is strange, if I enforce the environment to be python3.8 from the beginning it works installing:

conda create -n p38 python=3.8
conda activate p38
mamba install -c pytorch pytorch torchvision cudatoolkit=10.2
pip install https://github.com/RasmussenLab/vamb/archive/3.0.2.zip

**Comment by dpryan79** [comment]
We don't support the pytorch channel, so this can't progress further.

**Comment by simonrasmu** [comment]
Ah ok, then we will have to build it using pytorch-cpu!

**Comment by dpryan79** [comment]
Hmm, I wish the pytorch folks would work something out with conda-forge. Having their own channel makes things challenging for no reason.

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Pull request merged**
