### PR TITLE
Update piscem to 0.10.4

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`piscem`](https://bioconda.github.io/recipes/piscem/README.html): **0.10.3** &rarr; **0.10.4**

[install with bioconda](http://bioconda.github.io/recipes/piscem/README.html) [Conda](https://anaconda.org/bioconda/piscem/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/piscem`](https://github.com//bioconda/bioconda-recipes/tree/bump/piscem/recipes/piscem) (click to view/edit other files)
Summary | piscem is a next-generation compacted colored de Bruijn Graph-based indexer and mapper
Home | [https://github.com/COMBINE-lab/piscem](https://github.com/COMBINE-lab/piscem)
Releases |[https://github.com/COMBINE-lab/piscem/releases](https://github.com/COMBINE-lab/piscem/releases)
Author | `@COMBINE-lab`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by rob-p** [comment]
@bgruening : Any idea on why the OSX-64 build alone may be failing? It passes fine on our repo's on CI.  It's strange that aarch-osx passes (and linux x86-64) but not OSX-64.

**Review by rob-p — APPROVED** [review]
Works --- Looking for a better way to address the `::aligned_alloc` issue on OSX-x86. Ideally, we'd just bump the minimum version to OSX 10.15 (which should be old enough).

**Comment by bgruening** [comment]
Thanks @rob-p!

**Comment by rob-p** [comment]
Sure thing!  For the record, the issue seems to be that the `<string>` header includes a definition of `::aligned_alloc` that isn't valid in OSX **pre** 10.15 (but the build seems to use the 10.13 SDK).  A more desirable solution would be to figure out how to ensure that everything is building on 10.15, but I couldn't figure out how to make that work, so my workaround was to set one of the pre-processor macros that would disable this definition of `::aligned_alloc` in favor of the `posix` alternative.

If there is a suggest of how to address this more centrally, let me know (or if there is a way to force a newer version of OSX that I overlooked).

Thanks,
Rob

**Comment by robomics** [comment]
I am not an expert on how cargo orchestrates the compilation process, but from a quick look at the recipe it does not seem like you are passing conda's sysroot to the build system. My guess is that cargo is picking up the runner SDK instead of the one installed by conda.

Bioconda recently switched from Azure to GH Actions, which may have caused a change in the SDK used by the runner. This could possibly explain why the problem started occurring just now.

In the C++/CMake world you can pass the appropriate sysroot like so:

```bash
if [[ ${HOST} =~ .*darwin.* ]]; then
  cmake -DCMAKE_OSX_SYSROOT="${CONDA_BUILD_SYSROOT}" ...
else
  cmake -DCMAKE_TOOLCHAIN_FILE="${RECIPE_DIR}/cross-linux.cmake" ...
fi
```

Where `cross-linux.cmake` contains the following:

```cmake
# this one is important
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_PLATFORM Linux)
#this one not so much
set(CMAKE_SYSTEM_VERSION 1)

# specify the cross compiler
set(CMAKE_C_COMPILER $ENV{CC})
set(CMAKE_CXX_COMPILER $ENV{CXX})

# where is the target environment
set(CMAKE_FIND_ROOT_PATH $ENV{PREFIX} $ENV{BUILD_PREFIX}/$ENV{HOST}/sysroot)

# search for programs in the build host directories
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
# for libraries and headers in the target directories
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

# god-awful hack because it seems to not run correct tests to determine this:
set(__CHAR_UNSIGNED___EXITCODE 1)
```

Note that on macOS x86 this may not be enough if you depend on somewhat modern C/C++ features. See [here](https://conda-forge.org/docs/maintainer/knowledge_base/#requiring-newer-macos-sdks) for some guidance on how to proceed.

I am not sure how these steps can be adapted to fit cargo's way of doing things, but I hope some of this will be useful to you/other people stumbling on this issue.

**Comment by rob-p** [comment]
Thanks @robomics --- the offending code is actually in a C++ submodule (managed with CMake) that is being build by cargo under the hood to produce a statically linked library.  Thus, your CMake solution may very well work if I implement it in the underlying submodule (which is also code that we have developed in the lab / control).  We do rely very heavily on C++17 (at a minimum), and so that is a hard requirement for us for build.  I just wish there was an easier way to tell conda / bioconda to only provide a newer SDK by default at the conda / CI level (rather than having to pass a bunch of specific variables to the individual build systems). Our CMake and `build.rs` files are already laden with special behavior and variables set for bioconda builds in general.

To build C++ code, Rust uses `build.rs` which is arbitrary rust code that can then configure and invoke CMake with whatever appropriate parameters one wants.

I also noticed the switch from Azure to GitHub CI, and it didn't escape me that this coincided with the problem.  However, I also thought it was particularly strange that it didn't affect the aarch64 build for OSX, but only the x86 build.

**Comment by robomics** [comment]
Thanks for the clarifications!

I think it should be possible to deal with all/most of bioconda peculiarities using CMake toolchain files (which does not require modifying the `CMakeLists.txt` of the underlying projects).

You should be able to adapt the toolchain file from my previous post and then pass it down to all CMake invocations by defining the [CMAKE_TOOLCHAIN_FILE](https://cmake.org/cmake/help/latest/envvar/CMAKE_TOOLCHAIN_FILE.html) env variable in the build script.

All of this should not be an issue on macOS arm64 (at least when it comes to C++17 support) because the oldest OS/SDK  with arm support is v11.0.
Still, ensuring the right sysroot is being used is probably a good idea, as it will prevent ABI problems that could happen in the future when the runners are updated.

**Pull request merged**
