### PR TITLE
Update PIRATE recipe

### PR DESCRIPTION
**Pull request by rpetit3**
PIRATE includes many scripts for post-run analysis. This PR adds those scripts and R so that plots can be made (`--rplots`) during the PIRATE run.

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by rpetit3** [comment]
This should make the containers more useful for PIRATE users

```
docker run --rm -u $(id -u):$(id -g) -v ${PWD}:/data quay.io/biocontainers/pirate:1.0.4--hdfd78af_2 PIRATE --help
Usage:
            PIRATE -i /path/to/directory/containing/gffs/

     PIRATE input/output:
     -i|--input     input directory containing gffs [mandatory]
     -o|--output    output directory in which to create PIRATE folder
                    [default: input_dir/PIRATE]

     Global:
     -s|--steps     % identity thresholds to use for pangenome construction
                    [default: 50,60,70,80,90,95,98]
     -f|--features  choose features to use for pangenome construction.
                    Multiple may be entered, seperated by a comma [default: CDS]
     -n|--nucl      CDS are not translated to AA sequence [default: off]
     --pan-opt      additional arguments to pass to pangenome_contruction
     --pan-off      don't run pangenome tool [assumes PIRATE has been previously
                    run and resulting files are present in output folder]

     Paralog classification:
     --para-off     switch off paralog identification [default: on]
     --para-args    options to pass to paralog splitting algorithm
                    [default: none]
     --classify-off do not classify paralogs, assumes this has been
                    run previously [default: on]

     Output:
     -a|--align     align all genes and produce core/pangenome alignments
                    [default: off]
     -r|--rplots    plot summaries using R [requires dependencies]

     Usage:
     -t|--threads   number of threads/cores used by PIRATE [default: 2]
     -q|--quiet     switch off verbose
     -z             retain intermediate files [0 = none, 1 = retain pangenome
                    files (default - re-run using --pan-off), 2 = all]
     -c|--check     check installation and run on example files
     -h|--help      usage information
```

```
docker run --rm -u $(id -u):$(id -g) -v ${PWD}:/data quay.io/biocontainers/pirate:1.0.4--hdfd78af_2 PIRATE_to_roary.pl --help
Usage:
     convert_to_roary.pl -i /path/to/PIRATE.*.tsv/ -o /path/to/output_file.tsv

     Input/Output:
     -i|--input             input PIRATE directory [required]
     -o|--output            output file [required]

     -h|--help              usage information
```

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
@bioconda-bot please merge

**Comment by bgruening** [comment]
thanks @rpetit3!

**Comment by rpetit3** [comment]
Thank you!

**Pull request merged**
