### PR TITLE
Change compiler from c to cxx and bump build number.

### PR DESCRIPTION
**Pull request by molpopgen**
* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [ ] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [X] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by molpopgen** [comment]
@johanneskoester -- This project is failing lint checks and I cannot understand why.

Also, it has been blacklisted by mistake.  Whoever added 'c' as the compiler made an error.  This is a C++ package, and so compiler should be 'cxx'.  How do we un-blacklist?

**Comment by kyleabeauchamp** [comment]
I think those lint failures are from other packages...

**Comment by molpopgen** [comment]
> I think those lint failures are from other packages...

Then why is it reporting a CI failure for this PR?

**Comment by kyleabeauchamp** [comment]
There's a lot of noise from the conda-build3 migration, which involved temporarily disabling linting and blacklisting some packages.

**Comment by kyleabeauchamp** [comment]
```
7:25:57 BIOCONDA DEBUG lint recipes/wgs-assembler
	recipe	check	info	fix	missing_hash	missing_home	should_not_use_fn	should_use_compilers	uses_git_url
0	recipes/flexbar/3.3.0	should_not_use_fn	{'should_not_use_fn': True, 'fix': 'URL should specify path to file, which will be used as the filename'}	URL should specify path to file, which will be used as the filename			True		
1	recipes/flexbar/3.3.0	should_use_compilers	"{'should_use_compilers': True, 'fix': 'use {{ compiler(""c"") }} or other new-style compilers'}"	"use {{ compiler(""c"") }} or other new-style compilers"				True	
2	recipes/icqsol	missing_hash	"{'missing_hash': True, 'fix': 'add md5, sha1, or sha256 hash to ""source"" section'}"	"add md5, sha1, or sha256 hash to ""source"" section"	True				
3	recipes/icqsol	uses_git_url	{'uses_git_url': True, 'fix': 'use tarballs whenever possible'}	use tarballs whenever possible					True
4	recipes/igblast/1.4.0	missing_hash	"{'missing_hash': True, 'fix': 'add md5, sha1, or sha256 hash to ""source"" section'}"	"add md5, sha1, or sha256 hash to ""source"" section"	True				
5	recipes/mapsplice	missing_home	{'missing_home': True, 'fix': 'add about:home'}	add about:home		True			
```

**Comment by kyleabeauchamp** [comment]
I guess one approach would be that you could add those failing packages to the blacklist

**Comment by molpopgen** [comment]
> I guess one approach would be that you could add those failing packages to the blacklist

But should they be blacklisted?  Take a look at #9901.  Some of the failures are being introduced by maintainers during bulk changes to recipies.

**Comment by kyleabeauchamp** [comment]
Lots of the recipes had accumulated recipe problems (e.g., syntax errors, lint issues) that prevented them from building via conda-build 3.  This led to lots of stuff being blacklisted, as they just didn't build properly on the newer build system.  The eventual goal is to fix every recipe so that they all build, but the blacklist is a way to move the ball forward gradually.

**Comment by kyleabeauchamp** [comment]
The overall takeaway is that if you see something wrong, definitely make a PR to fix it.  If it refuses to build, then feel free to blacklist.  But the overall goal is to fix everything.

**Comment by kyleabeauchamp** [comment]
PS I haven't kept up with the latest changes of the past couple of weeks so @bgruening  may have better intel.

**Comment by kyleabeauchamp** [comment]
Actually, it looks like those recipes are *already* blacklisted, but their lint failures are preventing your recipe from building!

**Comment by bgruening** [comment]
@molpopgen in such a case, just merge master back into your branch.

**Comment by bgruening** [comment]
@molpopgen new error :(

```
   ^
../fwdpp/sampling_functions.tcc:102:3: note:   template argument deduction/substitution failed:
../fwdpp/sampling_functions.tcc: In substitution of ‘template<class mcont_t, class gcont_t, class dcont_t> typename std::enable_if<KTfwd::traits::is_diploid_like<typename dcont_t::value_type::value_type>::value, std::vector<std::vector<std::pair<double, std::basic_string<char> > > > >::type KTfwd::ms_sample(const gsl_rng*, const mcont_t&, const gcont_t&, const dcont_t&, const unsigned int&, const bool&) [with mcont_t = std::vector<KTfwd::popgenmut, std::allocator<KTfwd::popgenmut> >; gcont_t = std::vector<KTfwd::gamete_base<void> >; dcont_t = std::vector<std::pair<long unsigned int, long unsigned int>, std::allocator<std::pair<long unsigned int, long unsigned int> > >]’:
diploid_ind.cc:111:140:   required from here
../fwdpp/sampling_functions.tcc:102:3: error: no type named ‘value_type’ in ‘std::vector<std::pair<long unsigned int, long unsigned int>, std::allocator<std::pair<long unsigned int, long unsigned int> > >::value_type {aka struct std::pair<long unsigned int, long unsigned int>}’
make[2]: *** [diploid_ind.o] Error 1
make[2]: Leaving directory `/opt/conda/conda-bld/fwdpp_1531515392127/work/examples'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/opt/conda/conda-bld/fwdpp_1531515392127/work'
make: *** [all] Error 2
```

**Comment by molpopgen** [comment]
> new error :(

ok, this is in fwdpp, not fwdpy11 though.    This PR is for the latter.

**Comment by bgruening** [comment]
@molpopgen true. Sorry I did removed more from your pkgs from the blacklist in this PR.

**Comment by molpopgen** [comment]
> @molpopgen new error :(

Something funny is happening here.  Even the latest fwdpp version is showing this error, but the error is wrong.  The package passes Travis CI on gcc 4, 5, and 6, and I can compile it on my Pop OS machine with GCC7 and many versions of clang.  

I may re-blacklist fwdpp if I can't sort it out quickly.

**Comment by bgruening** [comment]
You can leave this open if you like, no need to re-blacklist it in this PR. I stays blacklisted on master.
Btw. we do not use travis anymore. Where do you test this?

**Comment by molpopgen** [comment]
> You can leave this open if you like, no need to re-blacklist it in this PR. I stays blacklisted on master.
> Btw. we do not use travis anymore. Where do you test this?

I know that bioconda isn't using Travis.  But I do.  The testing is done via the GH repo for fwdpp.  The Circle CI shows failures for fwdpy11, too.  Both failures are suspicious.  This code gets compiled a lot on a lot of different platforms.  

In addition to Travis, I just ran all of these packages through clang 6.0 on a laptop with the latest Pop OS (Ubuntu, basically).  All good.

I also have a user account on the same machine for using conda.  I have the new compilers installed and all tests passed, as expected.

To be clear, something like the following is what the Circle CI setup is using, right?

```
(gcc7) ktconda@pop-os:~/fwdpp$ which $CXX
/home/ktconda/miniconda3/envs/gcc7/bin/x86_64-conda_cos6-linux-gnu-c++
(gcc7) ktconda@pop-os:~/fwdpp$ $CXX -v
Reading specs from /home/ktconda/miniconda3/envs/gcc7/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.2.0/specs
COLLECT_GCC=/home/ktconda/miniconda3/envs/gcc7/bin/x86_64-conda_cos6-linux-gnu-c++
COLLECT_LTO_WRAPPER=/home/ktconda/miniconda3/envs/gcc7/bin/../libexec/gcc/x86_64-conda_cos6-linux-gnu/7.2.0/lto-wrapper
Target: x86_64-conda_cos6-linux-gnu
Configured with: /opt/conda/conda-bld/compilers_linux-64_1520532893746/work/.build/src/gcc-7.2.0/configure --build=x86_64-build_pc-linux-gnu --host=x86_64-build_pc-linux-gnu --target=x86_64-conda_cos6-linux-gnu --prefix=/opt/conda/conda-bld/compilers_linux-64_1520532893746/work/gcc_built --with-sysroot=/opt/conda/conda-bld/compilers_linux-64_1520532893746/work/gcc_built/x86_64-conda_cos6-linux-gnu/sysroot --enable-languages=c,c++,fortran,objc,obj-c++ --with-pkgversion='crosstool-NG fa8859cb' --enable-__cxa_atexit --disable-libmudflap --enable-libgomp --disable-libssp --enable-libquadmath --enable-libquadmath-support --enable-libsanitizer --enable-libmpx --with-gmp=/opt/conda/conda-bld/compilers_linux-64_1520532893746/work/.build/x86_64-conda_cos6-linux-gnu/buildtools --with-mpfr=/opt/conda/conda-bld/compilers_linux-64_1520532893746/work/.build/x86_64-conda_cos6-linux-gnu/buildtools --with-mpc=/opt/conda/conda-bld/compilers_linux-64_1520532893746/work/.build/x86_64-conda_cos6-linux-gnu/buildtools --with-isl=/opt/conda/conda-bld/compilers_linux-64_1520532893746/work/.build/x86_64-conda_cos6-linux-gnu/buildtools --enable-lto --enable-threads=posix --enable-target-optspace --enable-plugin --enable-gold --disable-nls --disable-multilib --with-local-prefix=/opt/conda/conda-bld/compilers_linux-64_1520532893746/work/gcc_built/x86_64-conda_cos6-linux-gnu/sysroot --enable-long-long --enable-default-pie
Thread model: posix
gcc version 7.2.0 (crosstool-NG fa8859cb) 
(gcc7) ktconda@pop-os:~/fwdpp$ which $CC
/home/ktconda/miniconda3/envs/gcc7/bin/x86_64-conda_cos6-linux-gnu-cc
```

**Comment by bgruening** [comment]
No we are still using the old compilers.

**Comment by molpopgen** [comment]
> No we are still using the old compilers.

So you mean the GCC/GXX 4.8.5 that have been in Anaconda "forever"?  If so, then something is indeed amiss.  Both fwdpp and fwdpy11 are tested on Travis where one part of the test matrix installs miniconda and those versions of GCC.  For [example](https://travis-ci.org/molpopgen/fwdpy11).

**Comment by bgruening** [comment]
Yes, this is way I blacklisted them. Here is something strange and I would like to finish the rebuild of the other packages before I can look at those more complicated cases.

Have you seen this? `cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]`

**Comment by molpopgen** [comment]
> Yes, this is way I blacklisted them. Here is something strange and I would like to finish the rebuild of the other packages before I can look at those more complicated cases.

The cases may not be more complicated. Rather,  I'm worried that something is wrong in the setup of the build system.

> 
> Have you seen this? cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]

Yes, that is a warning, and it is totally unrelated to the errors.  Also, that is only happening in fwdpy11, and not fwdpp.  The reason why it happens in fwdpy11 is because of Python's horrid setuptools, etc., and the way it establishes CPPFLAGS.

**Comment by molpopgen** [comment]
@bgruening -- thanks for all the work on rebuilding things!

I pulled the latest master into this PR.  The build still fails, and it is not correct that it fails.  On Travis, I just triggered a rebuild of both master and dev branches of this project, which are still currently equal to the latest release that I am trying to build here.

The Travis setup pulls in dependencies from bioconda and it built fine.  Moreover, I can build everything on my own Linux and OS X machines with conda using both the old GCC (4.8.5) and the new conda GCC (7.something).

Is there a way to test these configurations offline?  I must admit that I find the docs re: Docker tough to follow.  They assume an understanding of how all those parts work, and it isn't clear to me what I'd need to execute locally to get things done.

I'll reiterate that this build failure (and what I'm seeing in the blacklisted fwdpp recipe's logs) is suggesting a config error somewhere.  These are some pretty well-tested code bases.

**Comment by bgruening** [comment]
There is still something wired in your PR. It add things to the blacklist?
Regarding to the compilers, the actual compiler that is currently used is the one from the Docker image. Also try to add `c` and `cxx`.

**Comment by molpopgen** [comment]
Hmmm--shouldn't be changing the blacklist.  I pulled from master immediately before making any changes.  I'll take another look.  I may have to close this one or somehow rebase it vs master.

Regarding the compiler, I am installing gcc, meaning that I want conda/gcc-4.8.5 to be used.  What is the version used in the image, and is it possible that it is over-riding the use of the conda compiler (and how would one stop that)?

**Comment by molpopgen** [comment]
ok, tests finally pass.  it looks like 'c' and 'cxx' are needed for C++ projects.

Shall I merge?

**Comment by bgruening** [comment]
Please go ahead! :)

**Pull request merged**
