### PR TITLE
idemux recipe

### PR DESCRIPTION
**Pull request by entzian**
Adding idemux: A Lexogen tool for demultiplexing and index error correcting fastq files.

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by entzian** [comment]
@BiocondaBot please add label

**Comment by bwlang** [comment]
I'm not sure this license is compatible ... 
https://github.com/Lexogen-Tools/idemux/blob/master/LICENCE

**Comment by entzian** [comment]
> I'm not sure this license is compatible ...
> https://github.com/Lexogen-Tools/idemux/blob/master/LICENCE

This license is compatible with conda, because it allows redistribution: '...grants you a non-exclusive, worldwide, royalty-free copyright license to reproduce its contribution, prepare derivative works of its contribution, and distribute its contribution or any derivative works that you create...'.

**Comment by eggzilla** [comment]
Hi, I think it would be preferable for bioconda if you use an existing software license, instead of a self written one. If I read your license file correctly, I understand that you want to make your software available for non-commercial use? An existing license for such a case would be: https://creativecommons.org/licenses/by-nc/3.0/
However please read the following discussion carefully: https://opensource.stackexchange.com/questions/9805/can-i-license-my-project-with-an-open-source-license-but-disallow-commercial-use
I am not an expert on the topic, so it might also be of advantage to ask the community in the bioconda gitter channel for advice :-)

**Comment by entzian** [comment]
Hi, I understand that work with bioconda would be easier if all people would use standard licenses.
However, there is already other software with proprietary and non-commercial licenses in bioconda (e.g. https://bioconda.github.io/recipes/oligoarrayaux/README.html).
Moreover, in the conda recipe checklist (https://bioconda.github.io/contributor/guidelines.html) it says '...License allows redistribution and license is indicated in meta.yaml...'.
This is clearly fulfilled with this license.
If this is not convincing, please say which are the points in the license where you see conflicts with bioconda.

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@bioconda-bot please merge

FYI, you should have a lawyer rewrite your license in English, since it doesn't actually mean what you likely think (e.g., it absolutely allows usage in companies when they're not using your kits due to being written incorrectly).

**Pull request merged**
