### PR TITLE
Add bioawk

### PR DESCRIPTION
**Pull request by brwnj**
This updates the docker instance!

`byacc` is not likely going to be a requirement for new bioinformatics tools, so I don't know if we really want to merge this branch. I'll leave it up to whomever wishes to review this pull request.

### CODE REVIEW

**Comment by brwnj** [comment]
`yacc` missing is also the reason for failed travis-ci test.

**Comment by johanneskoester** [comment]
Will it be statically compiled into bioawk so that the tool will run also on systems that don't have byacc installed?

**Comment by brwnj** [comment]
I believe that's true, but I'm not very experienced in checking for those requirements/dependencies.

**Comment by johanneskoester** [comment]
I have checked the Makefile and I am pretty sure byacc is only used as a preprocessor. So yes, we can do as you suggest. Only caveat, you need to split out the byacc addition into a separate pull request. Once that is merged and the docker image rebuild, this pull request can be checked and merged.

Sorry for the inconvenience!

**Comment by brwnj** [comment]
Inconvenience? No way! I'm more than happy to do it and make these tools easily installable.

**Comment by bgruening** [comment]
@brwnj I rebased this branch and added checksums. I guess we are ready to merge this.

**Pull request merged**
