### PR TITLE
Specify gsl version

### PR DESCRIPTION
**Pull request by RomainFeron**
PhyloCSF requires libgsl.so.23, which is not available with the last version of gsl. 
I specified gsl version 2.5 to make sure this lib is available.
For some reason it doesn't build on osx anymore and the error is too complex for me to handle at the moment, so I disabled building for osx.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [x] This PR updates an existing recipe.

### CODE REVIEW

**Comment by dpryan79** [comment]
I suspect the issue was that when this was built originally it wasn't pinned to a gsl version. We currently pin to gsl 2.5, so moving gsl to the host section should take care of the issue.

**Comment by RomainFeron** [comment]
Okay, I forgot about build vs host, it's more clear now. Thanks !
The osx-specific bug is different; one component of opam (ocaml package manager) does not build anymore, the error is:

> Fatal error: exception ("Fdecl.get: not set", {})
> 01:00:40 BIOCONDA INFO (ERR) # Raised at file "src/stdune/code_error.ml", line 9, characters 30-62

It used to work 2-3 months ago when I first built the recipe, and I couldn't find anything to help with this error after a quick search. I'm not familiar with ocaml at all, I'm not sure how to fix this at the moment.

**Comment by dpryan79** [comment]
Ah, that explains it, I know nothing of opam, so let's just skip that :)

**Comment by dpryan79** [comment]
@bioconda-bot please fetch

**Comment by dpryan79** [comment]
@bioconda-bot please fetch artifacts

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Pull request merged**
