### PR TITLE
Update refinem to 0.1.0

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`refinem`](https://bioconda.github.io/recipes/refinem/README.html): **0.0.25** &rarr; **0.1.0**

[install with bioconda](http://bioconda.github.io/recipes/refinem/README.html) [Conda](https://anaconda.org/bioconda/refinem/files)

Info | Link
-----|-----
Recipe | [`recipes/refinem`](https://github.com//bioconda/bioconda-recipes/tree/bump/refinem/recipes/refinem) (click to view/edit other files)
Releases |[https://pypi.org/pypi/refinem/json](https://pypi.org/pypi/refinem/json)
Recipe Maintainer(s) | @HadrienG

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by raivivek** [comment]
@bioconda-bot please merge

**Comment by HadrienG** [comment]
I don't think this should have been merged as-is. Starting in version `0.1.0` refinem works with python 3.

@bioconda/core what's the procedure here? Can I revert or should I make a new PR?

**Comment by dpryan79** [comment]
Just make a new PR.

**Comment by raivivek** [comment]
@HadrienG Thanks for pointing that out. Yes, please make a new PR.

**Pull request merged**
