### PR TITLE
Add libdeflate, try building HTSLib with it

### PR DESCRIPTION
**Pull request by kyleabeauchamp**
* [ ] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [ ] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by jtratner** [comment]
would it make sense to create a separate samtools-deflate package for this to allow folks to test it? (otherwise you're opting everyone in to libdeflate)?

Not sure level of robustness that samtools maintainers feel they have.

**Comment by kyleabeauchamp** [comment]
Seems like the HTSLib developers are fairly confident, but that's a good thing to think about.

**Comment by epruesse** [comment]
@jtratner On the htslib/samtools side, the coding would not have been very invasive, so unlikely to contain breakage. Libdeflate itself seems to be stable already judging from the recent releases, and since it produces compatible output, I wouldn't worry too much.

**Comment by jtratner** [comment]
cool - sounds good to me - seems like we don't need a separate package :)

**Comment by epruesse** [comment]
Technically, libdeflate is a candidate for conda-forge though. It's likely to appear there eventually, and then we have the duplication issue again.

**Comment by kyleabeauchamp** [comment]
Any objections?  I tested that I do see substantial speedups when I use the builds from my local bioconda build of the same recipes.

**Comment by kyleabeauchamp** [comment]
FYI: future todos on this story are:

1.  When CB3 / GCC7 is available, upgrade the compiler to see if performance improves
2.  Add additional compiler optimizations / -march targets as appropriate to further improve performance.

**Pull request merged**
