### PR TITLE
add eigen libraries

### PR DESCRIPTION
**Pull request by bgruening**

### CODE REVIEW

**Comment by johanneskoester** [comment]
The install path seems to be non-standard. Libraries should go to $PREFIX/lib, shouldn't they?

**Comment by bgruening** [comment]
@johanneskoester good catch! Thanks. Do you have any hint howto test libraries like this?

**Comment by johanneskoester** [comment]
Not really. A small C snippet that includes a header?

**Comment by johanneskoester** [comment]
Is there a particular reason to have eigen2 and eigen3 as separate recipes? Anaconda doesn't even do that for Python.

**Comment by bgruening** [comment]
Yeah, but I had hoped for a easier solution :)
Afaik we had a few programs in the past that needed eigen2, specifically. Fixed the path in https://github.com/bioconda/bioconda-recipes/pull/580

**Comment by johanneskoester** [comment]
Ok, but it looks like eigen is intended as a static build dependency, right? There is no .so file in the resulting package, only headers and source. Then, why not having only an eigen package with the two versions 2.x and 3.x? It will never be a runtime dependency so you don't need both versions in the same environment.

**Comment by bgruening** [comment]
I can put it under one directory with two sub-folders if you prefer. This is just how other package managers are doing it. 

```
aptitude search eigen
p   libeigen2-dev                       - lightweight C++ template library for linear algebra
p   libeigen2-dev:i386               - lightweight C++ template library for linear algebra
p   libeigen2-doc                       - eigen2 API docmentation
p   libeigen3-dev                       - lightweight C++ template library for linear algebra
```

**Comment by johanneskoester** [comment]
This is because debian package management does not have the possibility to use isolated enviroments like conda. Yes, I would prefer 3.x to be under ``recipes/eigen`` and 2.x under ``recipes/eigen/2.0.7``. Sorry for coming around too late with this.

**Comment by bgruening** [comment]
My argumentation was more like people are used to this name, rather than the versionless name. Will change it and also depended packages.

**Comment by bgruening** [comment]
@johanneskoester https://github.com/bioconda/bioconda-recipes/pull/594

**Comment by johanneskoester** [comment]
Thanks!

**Pull request merged**
