### PR TITLE
add singularity

### PR DESCRIPTION
**Pull request by bgruening**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by bgruening** [comment]
@jmchilton its tricky to surprise you with a cake ;)

**Comment by johanneskoester** [comment]
Wouldn't this be better suited in conda-forge?

**Comment by bgruening** [comment]
Not sure, but we need a container for this as well.

**Comment by johanneskoester** [comment]
Well, it is a general purpose package. So in the spirit of trying to reduce our storage usage, I think this should at least be submitted to conda-forge in parallel, so that we can remove it from bioconda as soon as it has landed there.

**Comment by bgruening** [comment]
Don't worry it is only 1.4 MB. I will prepare a conda-forge one after our presentation at ISMB.

**Comment by johanneskoester** [comment]
Ok! Thanks.

**Comment by jakirkham** [comment]
FWIW we're adding it to conda-forge in PR ( https://github.com/conda-forge/staged-recipes/pull/4838 ). :)

**Pull request merged**
