### PR TITLE
PgSA tool

### PR DESCRIPTION
**Pull request by cmonjeau**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by cmonjeau** [comment]
ping @abretaud

**Comment by cmonjeau** [comment]
Weird, my simulate-travis works great.

**Comment by cmonjeau** [comment]
I took the last revision and it's good combined with your changes @bgruening

**Comment by bgruening** [comment]
Thanks @cmonjeau!

**Comment by cmonjeau** [comment]
Thanks for this review ;)

**Pull request merged**
