### PR TITLE
Py3 lofreq

### PR DESCRIPTION
**Pull request by ozagordi**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [x] This PR does something else (explain below).

The existing recipe for `lofreq` only works with python 2.7. This PR adds a recipe for python 3.5 that can be imported by projects requiring python 3.x support.

### CODE REVIEW

**Comment by kyleabeauchamp** [comment]
This is not an official release of the maintainers, right?  Is this your personal fork?

**Comment by kyleabeauchamp** [comment]
We generally prefer that such fixes be merged into the main projects, rather than supporting them here.

**Comment by ozagordi** [comment]
I see. My idea was that this could be a relatively quick fix before the maintainers fixes the original tool. Let's ask @andreas-wilm what his plans are.

By the way, the [build in my fork](https://travis-ci.org/ozagordi/bioconda-recipes/builds/242051759) runs just fine.

**Comment by andreas-wilm** [comment]
Thanks all. I will need one to two weeks before releasing a version with py3 support and including a few more fixes. Andreas

**Pull request closed without merging**
