### PR TITLE
Add bwa

### PR DESCRIPTION
**Pull request by cagaser**
I added bwa and updated the build number because I get the following message when running mate-clever:

===== Checking dependencies =====
Found executable /usr/local/bin/ctk-version
Found executable /usr/local/bin/laser-core
Found executable /usr/local/bin/laser-recalibrate
Could not locate executable "bwa". It's not in your PATH.

:information_source:
If this is your first pull request to Bioconda please ping `@bioconda/core` so it can be reviewed and to request being added as a member of the Bioconda team. Members of the Bioconda team are able to merge their own pull requests once tests and linting have passed.

----------------

* [ ] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [ ] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by dpryan79** [comment]
Thanks @cagaser !

**Comment by cagaser** [comment]
Thank you!

**Comment by cagaser** [comment]
Hello @bgruening 
The docker image in quay.io hasn't been updated yet (automatically) for clever

**Comment by dpryan79** [comment]
It looks like this wasn't built in the `master` branch for some reason (thus the image was never uploaded). I'll have a look.

**Comment by dpryan79** [comment]
I fixed the issue, everything should be available in ~30 minutes.

**Comment by cagaser** [comment]
@dpryan79 Thank you vey much!

**Pull request merged**
