### PR TITLE
picard adding 1.56

### PR DESCRIPTION
**Pull request by scholtalbers**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by scholtalbers** [comment]
@bioconda/core any comment on this. I'm including a tiny ant build dependency as I was unsure of how stable the url would be: https://mvnrepository.com/artifact/org.apache.ant/ant-apache-bcel/1.8.1

**Comment by bgruening** [comment]
You could make the URL stable by using https://github.com/galaxyproject/cargo-port

**Comment by scholtalbers** [comment]
@bgruening good to merge?

**Comment by bgruening** [comment]
Jupp, looks good! Thanks.

**Pull request merged**
