### PR TITLE
kraken2 2.0.9-beta

### PR DESCRIPTION
**Pull request by tseemann**
Describe your pull request here

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by tseemann** [comment]
Whoops - fixed the sha forgot to bump version.

**Comment by tseemann** [comment]
```
22:09:09 BIOCONDA INFO (OUT) Did not detect hard-coded path in libexec/kraken2 from has_prefix_files
22:09:09 BIOCONDA INFO (OUT) Did not detect hard-coded path in libexec/kraken2-build from has_prefix_files
22:09:09 BIOCONDA INFO (OUT) Did not detect hard-coded path in libexec/kraken2-inspect from has_prefix_files
```

**Comment by tseemann** [comment]
```
22:09:09 BIOCONDA INFO (OUT)    INFO (kraken2,libexec/lookup_accession_numbers): Needed DSO lib/libgcc_s.so.1 found in conda-forge::libgcc-ng-9.2.0-h24d8f2e_2
22:09:09 BIOCONDA INFO (OUT) WARNING (kraken2,libexec/lookup_accession_numbers): Needed DSO lib/libgomp.so.1 found in ['_openmp_mutex']
22:09:09 BIOCONDA INFO (OUT) WARNING (kraken2,libexec/lookup_accession_numbers): .. but ['_openmp_mutex'] not in reqs/run, (i.e. it is overlinking) (likely) or a missing dependency (less likely)
22:09:09 BIOCONDA INFO (OUT)    INFO (kraken2,libexec/build_db): Needed DSO x86_64-conda_cos6-linux-gnu/sysroot/lib/libpthread.so.0 found in CDT/compiler package conda-forge::gcc_impl_linux-64-7.3.0-hd420e75_5
22:09:09 BIOCONDA INFO (OUT)    INFO (kraken2,libexec/build_db): Needed DSO x86_64-conda_cos6-linux-gnu/sysroot/lib/libc.so.6 found in CDT/compiler package conda-forge::gcc_impl_linux-64-7.3.0-hd420e75_5
22:09:09 BIOCONDA INFO (OUT)    INFO (kraken2,libexec/build_db): Needed DSO lib/libstdc++.so.6 found in conda-forge::libstdcxx-ng-9.2.0-hdf63c60_2
22:09:09 BIOCONDA INFO (OUT)    INFO (kraken2,libexec/build_db): Needed DSO lib/libgcc_s.so.1 found in conda-forge::libgcc-ng-9.2.0-h24d8f2e_2
22:09:09 BIOCONDA INFO (OUT) WARNING (kraken2,libexec/build_db): Needed DSO lib/libgomp.so.1 found in ['_openmp_mutex']
22:09:09 BIOCONDA INFO (OUT) WARNING (kraken2,libexec/build_db): .. but ['_openmp_mutex'] not in reqs/run, (i.e. it is overlinking) (likely) or a missing dependency (less likely)
22:09:09 BIOCONDA INFO (OUT)    INFO (kraken2,libexec/classify): Needed DSO x86_64-conda_cos6-linux-gnu/sysroot/lib/libpthread.so.0 found in CDT/compiler package conda-forge::gcc_impl_linux-64-7.3.0-hd420e75_5
```'

**Comment by tseemann** [comment]
https://conda-forge.org/docs/maintainer/knowledge_base.html#openmp

**Comment by apeltzer** [comment]
Its already in by now :-)

**Pull request closed without merging**
