### PR TITLE
Update dDocent

### PR DESCRIPTION
**Pull request by jpuritz**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by bgruening** [comment]
@jpuritz can you explain why this `git clone` is necessary? Can we not update the seqtk recipes as well?

**Comment by jpuritz** [comment]
I thought it was Bioconda policy to not update recipes for master branch
versions of software, and to only use stable releases.

dDocent now requires the latest version of seqtk, so I thought it was
better to update then build this way, so other seqtk users would not be
affected.

I can update seqtk if that is preferred. This version of seqtk is over a
year old, so it’s not exactly unstable.

-- 
Jon Puritz

**Comment by bgruening** [comment]
Oh, so dDocent needs a unreleased version of seqtk? I saw your issue, lets see if we get a new release of seqtk in the next days.

**Comment by jpuritz** [comment]
@bgruening Yes, that is correct.  I put in the issue, and I just submitted a pull request with the new version.  However, it seems like there was a previous request for a new version from January this year, so I am not sure waiting a few days will help.  In the mean time, I moved the download of the unreleased version to the internal `dDocent` install script.  This gives a passing build with only removing `seqtk` from the `meta.yaml`.  Hopefully, this is an acceptable, temporary workaround.  I will update the `dDocent` recipe as soon as a new version of `seqtk` is released.

**Comment by bgruening** [comment]
Thanks!

**Pull request merged**
