### PR TITLE
bbmap - update to 38.22

### PR DESCRIPTION
**Pull request by notestaff**
* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [X] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [X] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by notestaff** [comment]
Note: #12247 is an earlier PR that also updates BBMap to 38.22; it additionally seeks to resolve issues with JNI support, but currently has a build error.  I'm submitting this PR in the interim to just update BBMap to the current version, will look into the JNI issues later.  The use of JNI is off by default in BBMap, so the default operation is not affected by these issues.

**Comment by epruesse** [comment]
@notestaff I had only turned the JNI off because it wasn't compiling. It would be great if you could figure out how to make the recipe work with the current version though! Thanks!

**Comment by notestaff** [comment]
@epruesse it's not compiling for me either, and I can't seem to find the error messages -- do you know what's going on?  For now I've disabled the JNI, as from Brian Bushnell's email it seems his support for JNI is uncertain.  Will eventually try to make it an option again, but need to figure out how to see the compile error logs.

**Comment by epruesse** [comment]
bioconda-utils currently displays the logs only after the build, if it fails. So you could just put an exit 1 there. I had a PR a year ago to change that, might have to look into that.

**Comment by epruesse** [comment]
W/o JNI builds and tests fine in the normal build. It just fails in the mulled tests, IIRC.

**Comment by notestaff** [comment]
Right, but why can't I see the build logs showing the compiler error messages?  The build.sh had the -x flag to echo everything to the console...

**Comment by notestaff** [comment]
I tried doing a local mulled build with the instructions from
https://bioconda.github.io/contribute-a-recipe.html#test-locally
I get what looks like bioconda internal errors (see below).
Also, the local build instructions seem to use bleeding-edge
bioconda-utils, rather than a stable release -- that isn't what circle-ci
actually does, right?

13:46:37 BIOCONDA INFO BUILD START recipes/bbmap
13:47:18 BIOCONDA ERROR COMMAND FAILED: docker run -t --net host --rm -v
/ssd/tmp/tmps6vi9u6p/build_script.bash:/opt/build_script.bash\
 -v /tmp/miniconda/miniconda/conda-bld:/opt/host-conda-bld -v
/data/sw/bioconda-recipes/recipes/bbmap:/opt/recipe -e CONDA_SHLVL=2 -e \
CONDA_PROMPT_MODIFIER=(base)  -e
CONDA_EXE=/data/vngs/viral-ngs-etc/mc3/bin/conda -e
CONDA_PREFIX_1=/data/vngs/viral-ngs-etc/mc3/envs/\
master_env_py27_v28 -e LANG=en_US.UTF-8 -e
CONDA_PYTHON_EXE=/data/vngs/viral-ngs-etc/mc3/bin/python -e
CONDA_DEFAULT_ENV=base -e CONDA\
_ROOT=/tmp/miniconda/miniconda -e CONDA_ALLOW_SOFTLINKS=false -e
HOST_USER_ID=501 tmp-bioconda-builder /bin/bash /opt/build_script.bas\
h
13:47:18 BIOCONDA ERROR STDOUT+STDERR:

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/opt/conda/lib/python3.6/site-packages/conda/cli/main.py", line
98, in main
        return activator_main()
      File "/opt/conda/lib/python3.6/site-packages/conda/activate.py", line
632, in main
        print(activator.execute(), end='')
      File "/opt/conda/lib/python3.6/site-packages/conda/activate.py", line
166, in execute
        return getattr(self, self.command)()
      File "/opt/conda/lib/python3.6/site-packages/conda/activate.py", line
152, in activate
-        return
self._finalize(self._yield_commands(self.build_activate(self.env_name_or_prefix)),
      File "/opt/conda/lib/python3.6/site-packages/conda/activate.py", line
272, in build_activate
        deactivate_scripts = self._get_deactivate_scripts(old_conda_prefix)
      File "/opt/conda/lib/python3.6/site-packages/conda/activate.py", line
518, in _get_deactivate_scripts
        prefix, 'etc', 'conda', 'deactivate.d', '*' + self.script_extension
      File "/opt/conda/lib/python3.6/posixpath.py", line 80, in join
        a = os.fspath(a)
    TypeError: expected str, bytes or os.PathLike object, not NoneType

`$ /opt/conda/bin/conda shell.posix activate`

  environment variables:
                 CIO_TEST=<not set>
    CONDA_ALLOW_SOFTLINKS=false
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/data/vngs/viral-ngs-etc/mc3/bin/conda

 CONDA_PREFIX_1=/data/vngs/viral-ngs-etc/mc3/envs/master_env_py27_v28
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/data/vngs/viral-ngs-etc/mc3/bin/python
               CONDA_ROOT=/tmp/miniconda/miniconda
              CONDA_SHLVL=2
                 INFOPATH=/opt/rh/devtoolset-2/root/usr/share/info

LD_LIBRARY_PATH=/opt/rh/devtoolset-2/root/usr/lib64:/opt/rh/devtoolset-2/root/usr/lib
                  MANPATH=/opt/rh/devtoolset-2/root/usr/share/man:

 PATH=/opt/rh/devtoolset-2/root/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/
                          sbin:/usr/bin:/sbin:/bin:/root/bin

 PYTHONPATH=/opt/rh/devtoolset-2/root/usr/lib64/python2.6/site-

packages:/opt/rh/devtoolset-2/root/usr/lib/python2.6/site-packages
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
            shell level : 2
       user config file : /root/.condarc
  populated config files : /root/.condarc
          conda version : 4.5.11
    conda-build version : 3.15.1
         python version : 3.6.7.final.0
       base environment : /opt/conda  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /opt/conda/pkgs
                          /root/.conda/pkgs
       envs directories : /opt/conda/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.11 requests/2.18.4 CPython/3.6.7
Linux/4.14.77-70.82.amzn1.x86_64 centos/6.10 glibc/2.12
                UID:GID : 0:0
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?
[y/N]:
No report sent. To permanently opt-out, use

**Comment by notestaff** [comment]
@epruesse e.g. the bleeding-edge build-utils has a typo: https://github.com/bioconda/bioconda-utils/commit/96262c97cdde93ee7e28871105ba4009deb57842#diff-3b688d85fb0c75729505ac1a43c8ab74R784

**Comment by notestaff** [comment]
@epruesse sorry correct link is https://github.com/bioconda/bioconda-utils/commit/96262c97cdde93ee7e28871105ba4009deb57842#r31639558

**Comment by epruesse** [comment]
> @epruesse e.g. the bleeding-edge build-utils has a typo: [bioconda/bioconda-utils@96262c9#diff-3b688d85fb0c75729505ac1a43c8ab74R784](https://github.com/bioconda/bioconda-utils/commit/96262c97cdde93ee7e28871105ba4009deb57842#diff-3b688d85fb0c75729505ac1a43c8ab74R784)

Thx. I've fixed that.

**Comment by epruesse** [comment]
> Also, the local build instructions seem to use bleeding-edge
bioconda-utils, rather than a stable release -- that isn't what circle-ci
actually does, right?

No, the CI installs the tag configured here:

https://github.com/bioconda/bioconda-common/blob/master/common.sh

**Comment by epruesse** [comment]
closing in favor of #14560

**Pull request closed without merging**
