### PR TITLE
added knime recipe

### PR DESCRIPTION
**Pull request by ThomasWollmann**
* [x] I have read the guidelines above.
* [x] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by ThomasWollmann** [comment]
"OSError: [Errno 28] No space left on device". Seems like KNIME is too large for bioconda?

**Comment by bgruening** [comment]
Likely but more for Travis and the VM. Please also take care of following the guidelines for java packages.

**Comment by ThomasWollmann** [comment]
What shall we do about the filesize?

**Comment by ThomasWollmann** [comment]
I removed the plugins for now, but I think KNIME is more useful if we ship it with all free plugins.

**Comment by bgruening** [comment]
Is this really needed as Conda package? I mean KNIME should use Conda as resolver, but does this needs to be a Conda package. Or the other way around who would install it this way, especially without plugin?
I don't think there is anything we can do at them moment about the size. Packages should be small - we also don't ship databases inside of packages.

**Comment by ThomasWollmann** [comment]
In my opinion it would make it easier to integrate KNIME as a command line tool into Galaxy.

**Pull request closed without merging**
