### PR TITLE
Update gatk4 to 4.5.0.0

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`gatk4`](https://bioconda.github.io/recipes/gatk4/README.html): **4.4.0.0** &rarr; **4.5.0.0**

[install with bioconda](http://bioconda.github.io/recipes/gatk4/README.html) [Conda](https://anaconda.org/bioconda/gatk4/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/gatk4`](https://github.com//bioconda/bioconda-recipes/tree/bump/gatk4/recipes/gatk4) (click to view/edit other files)
Summary | Genome Analysis Toolkit (GATK4)
Home | [https://www.broadinstitute.org/gatk/](https://www.broadinstitute.org/gatk/)
Releases |[https://github.com/broadinstitute/gatk/releases](https://github.com/broadinstitute/gatk/releases)
Author | `@broadinstitute`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by mjsteinbaugh** [comment]
Build error related to `11:16:23 BIOCONDA INFO (OUT) -   - package r-base-4.3.0-h0fc540b_0 requires libcurl >=8.0.1,<9.0a0, but none of the providers can be installed`

**Comment by mjsteinbaugh** [comment]
There's something about the pinning here that's causing mamba to return `r-base` 4.3.0 instead of current 4.3.2 from conda-forge.

```
Mamba failed to solve:
 - r-gsalib
 - r-base 4.3.*
 - r-reshape
 - gcnvkernel
 - r-gplots
 - r-ggplot2
```

**Comment by mjsteinbaugh** [comment]
See related regarding `gcnvkernel`:
https://github.com/bioconda/bioconda-recipes/pull/41127

**Comment by mjsteinbaugh** [comment]
OK now hitting this build issue related to `gcnvkernel`:

```
The reported errors are:
- Encountered problems while solving:
-   - package gcnvkernel-0.7-py_0 requires pymc3 3.1.*, but none of the providers can be installed
```

**Comment by mjsteinbaugh** [comment]
@jmarshall @dpryan79 @chapmanb Any thoughts on best practice for including `gcnvkernel` in the recipe? I can confirm that it's currently causing the build to error.

**Comment by jmarshall** [comment]
Upstream gcnvkernel is a mess of very specific version dependencies on variously outdated packages. (Also I use gcnv in production and know that the existing bioconda gcnvkernel package doesn't work.)

I think the best way to package gcnvkernel is as a separate gatk-gcnvkernel subpackage, so that most gatk users are insulated from the baroque gcnvkernel dependencies. (So the main gatk package ought IMHO not to require gatk-gcnvkernel, so only users interested in the gCNV commands would install gatk-gcnvkernel. And similarly for the R dependencies IMHO.) This is PR #41127, but I moved on to using a vanilla upstream GATK image for our work purposes instead before I got it working.

IMHO what gcnvkernel really needs is for upstream to validate its use with a set of dependencies that are up-to-date versions of packages that are actually currently maintained (at all, not just in bioconda).

**Pull request closed without merging**
