### PR TITLE
perl gd

### PR DESCRIPTION
**Pull request by daler**

### CODE REVIEW

**Comment by daler** [comment]
It was necessary to call `conda-build` with a more recent Perl version in the `CONDA_PERL=5.22.0` env var in order to get these packages to build.

@johanneskoester, you have a couple of existing Perl recipes (db-file and set-intervaltree). I bumped the build numbers on them in this PR to make sure they're built wiht Perl 5.22.0.

The more general question is, what version of Perl should we use as a target?

**Comment by johanneskoester** [comment]
Hi Ryan. I have not enough perl experience to be sure. I would say let's try to follow the stable releases?

**Comment by daler** [comment]
OK -- 5.22.0 is latest stable (https://www.perl.org/get.html). 5.18.2 is from 2013 but seems to be the latest in the Ubuntu repos.

**Comment by daler** [comment]
FYI @tomkinsc, looks like trinity needs Perl compiled with threads.

Running the following locally or in the Docker container:

```
conda install -c bioconda trinity
Trinity --cite
```

gives the error:

```
This Perl not built to support threads
Compilation failed in require at /anaconda/bin/Trinity line 5.
BEGIN failed--compilation aborted at /anaconda/bin/Trinity line 5.
```

So this PR fixes the issue by creating a separate `perl-threaded` recipe.

**Comment by tomkinsc** [comment]
Great, thank you!

**Pull request merged**
