### PR TITLE
Update sra-tools to 3.0.0

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`sra-tools`](https://bioconda.github.io/recipes/sra-tools/README.html): **2.11.0** &rarr; **3.0.0**

[install with bioconda](http://bioconda.github.io/recipes/sra-tools/README.html) [Conda](https://anaconda.org/bioconda/sra-tools/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/sra-tools`](https://github.com//bioconda/bioconda-recipes/tree/bump/sra_tools/recipes/sra-tools) (click to view/edit other files)
Summary | SRA Toolkit and SDK from NCBI
Home | [https://github.com/ncbi/sra-tools](https://github.com/ncbi/sra-tools)
Releases |[https://github.com/ncbi/sra-tools/tags](https://github.com/ncbi/sra-tools/tags)<br>[https://github.com/ncbi/ncbi-vdb/tags](https://github.com/ncbi/ncbi-vdb/tags)
Author | `@ncbi`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by andersgs** [comment]
Should we be using the precompiled binaries: issue #35972

**Comment by dpryan79** [comment]
Regarding using precompiled binaries, it's hit or miss if they actually work, unfortunately :(

**Comment by dpryan79** [comment]
I hate it when the bot closes these.

**Comment by dpryan79** [comment]
I have this close to finished now, FYI. Mostly just getting the stinking CI to cooperate.

**Pull request closed without merging**
