### PR TITLE
Added TIR-Learner

### PR DESCRIPTION
**Pull request by GallVp**
Added TIR-Learner

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

### General instructions

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

### Instructions for avoiding API, ABI, and CLI breakage issues
Conda is able to record and lock (a.k.a. pin) dependency versions used at build time of other recipes.
This way, one can avoid that expectations of a downstream recipe with regards to API, ABI, or CLI are violated by later changes in the recipe.
If not already present in the meta.yaml, make sure to specify `run_exports` (see [here](https://bioconda.github.io/contributor/linting.html#missing-run-exports) for the rationale and comprehensive explanation).
Add a `run_exports` section like this:

```yaml
build:
  run_exports:
    - ...

```

with `...` being one of:

| Case                             | run_exports statement                                               |
| -------------------------------- | ------------------------------------------------------------------- |
| semantic versioning              | `{{ pin_subpackage("myrecipe", max_pin="x") }}`     |
| semantic versioning (0.x.x)      | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}`   |
| known breakage in minor versions | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| known breakage in patch versions | `{{ pin_subpackage("myrecipe", max_pin="x.x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| calendar versioning              | `{{ pin_subpackage("myrecipe", max_pin=None) }}`    |

while replacing `"myrecipe"` with either `name` if a `name|lower` variable is defined in your recipe or with the lowercase name of the package in quotes.

### Bot commands for PR management

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

Note that the <code>@BiocondaBot please merge</code> command is now depreciated. Please just squash and merge instead.

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by GallVp** [comment]
@BiocondaBot please fetch artifacts

**Comment by GallVp** [comment]
@BiocondaBot please add label

**Comment by GallVp** [comment]
- For visibility, @oushujun

**Comment by oushujun** [comment]
@GallVp Great! Thanks!! With the conda version, I can retire the folder included in EDTA/bin. @lutianyu2001 is the developer for the TIR-Learner v3 version. He just pushed new updates yesterday. Can you please update the source to https://github.com/lutianyu2001/TIR-Learner? Thank you!

**Comment by GallVp** [comment]
Hi @oushujun 

Thanks for the update. Do you have any suggestion for tracking the version of TIR-Learner v3? It looks like the source is changed without adding version info or creating a GitHub release.

**Comment by oushujun** [comment]
Good point! I can ask Tianyu to make releases for versioning.

Thanks,
Shujun

**Comment by GallVp** [comment]
And also add version info here: https://github.com/lutianyu2001/TIR-Learner/blob/c216b07b2a936b378bcb3372a34fa5ba7623f3ab/TIR-Learner3.0/TIR-Learner3.0.py#L51

such as:
```
parser.add_argument('--version', action='version', version='%(prog)s 2.0')
```

from https://stackoverflow.com/questions/15405636/pythons-argparse-to-show-programs-version-with-prog-and-version-string-formatt#15406624

Many Thanks

**Comment by lutianyu2001** [comment]
@GallVp Already created a release of v3.0.0-beta and added the --version argument to the program. Much appreciated!

**Comment by GallVp** [comment]
Hi @lutianyu2001 

The v3.0.0-beta release is failing with segmentation fault. I am trying to diagnose the problem. Is there a small test data set that we can use? I am also keen to setup an automated test workflow on the TIR-Learner repo so that each release gets tested automatically.

**Comment by GallVp** [comment]
I have added a CI action on and it seems to be passing with CONDA (https://github.com/GallVp/TIR-Learner/actions/runs/8608032236/job/23589628911). Please see PR: https://github.com/lutianyu2001/TIR-Learner/pull/1

Not sure why this conda recipe test is failing with segmentation fault.

**Comment by GallVp** [comment]
Now all checks are passing!

**Comment by oushujun** [comment]
@BiocondaBot please fetch artifacts

**Review by oushujun — APPROVED** [review]
looks great!

**Comment by oushujun** [comment]
@BiocondaBot please merge

**Review by mencian — APPROVED** [review]

**Pull request merged**
