### PR TITLE
pysamstats set max_pin to properly fix #12466

### LINKED ISSUE #12466: Install of pysamstats results in ValueError: pysam.libchtslib.HTSFile has the wrong size
`conda create -n pysamstats pysamstats`

```
Traceback (most recent call last):
  File "/Genomics/grid/users/lparsons/miniconda3/envs/pysamstats/bin/pysamstats", line 10, in <module>
    import pysamstats
  File "/Genomics/grid/users/lparsons/miniconda3/envs/pysamstats/lib/python3.6/site-packages/pysamstats/__init__.py", line 8, in <module>
    from .pileup import *
  File "/Genomics/grid/users/lparsons/miniconda3/envs/pysamstats/lib/python3.6/site-packages/pysamstats/pileup.py", line 6, in <module>
    import pysamstats.opt as opt
  File "libchtslib.pxd", line 2590, in init pysamstats.opt
ValueError: pysam.libchtslib.HTSFile has the wrong size, try recompiling. Expected 88, got 80
```

```
# packages in environment at /Genomics/grid/users/lparsons/miniconda3/envs/pysamstats:
#
# Name                    Version                   Build  Channel
bcftools                  1.9                  h4da6232_0    bioconda
blas                      1.1                    openblas    conda-forge
blosc                     1.14.4               hfc679d8_0    conda-forge
bzip2                     1.0.6                h470a237_2    conda-forge
ca-certificates           2018.11.29           ha4d7672_0    conda-forge
certifi                   2018.11.29            py36_1000    conda-forge
curl                      7.62.0               h74213dd_0    conda-forge
hdf5                      1.10.3               hc401514_2    conda-forge
htslib                    1.9                  hc238db4_4    bioconda
krb5                      1.16.2               hbb41f41_0    conda-forge
libcurl                   7.62.0               hbdb9355_0    conda-forge
libdeflate                1.0                  h470a237_0    bioconda
libedit                   3.1.20170329         haf1bffa_1    conda-forge
libffi                    3.2.1                hfc679d8_5    conda-forge
libgcc-ng                 7.2.0                hdf63c60_3    conda-forge
libgfortran               3.0.0                         1    conda-forge
libssh2                   1.8.0                h5b517e9_3    conda-forge
libstdcxx-ng              7.2.0                hdf63c60_3    conda-forge
lzo                       2.10                 h470a237_0    conda-forge
ncurses                   6.1                  hfc679d8_1    conda-forge
numexpr                   2.6.8            py36hf8a1672_0    conda-forge
numpy                     1.15.1          py36_blas_openblashd3ea46f_0    conda-forge
openblas                  0.2.20                        8    conda-forge
openssl                   1.0.2p               h470a237_1    conda-forge
pip                       18.1                  py36_1000    conda-forge
pysam                     0.15.1           py36h0380709_0    bioconda
pysamstats                1.0.1            py36ha92aebf_2    bioconda
pytables                  3.4.4            py36h2392372_1    conda-forge
python                    3.6.7                h5001a0f_1    conda-forge
readline                  7.0                  haf1bffa_1    conda-forge
samtools                  1.9                  h8ee4bcc_1    bioconda
setuptools                40.6.2                   py36_0    conda-forge
six                       1.11.0                py36_1001    conda-forge
sqlite                    3.26.0               hb1c47c0_0    conda-forge
tk                        8.6.9                ha92aebf_0    conda-forge
wheel                     0.32.3                   py36_0    conda-forge
xz                        5.2.4                h470a237_1    conda-forge
zlib                      1.2.11               h470a237_3    conda-forge
```

### PR DESCRIPTION
**Pull request by lparsons**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by epruesse** [comment]
Please test whether this will even work. My guess is, conda will prefer having a newer version of pysam over a newer build of pysamstats. So it won't. :-/

**Comment by lparsons** [comment]
@epruesse Hmm... I'm not really sure how to check to see what the solver chooses in this case.

**Comment by epruesse** [comment]
@biocondabot lint

**Comment by epruesse** [comment]
Well, while I'm not sure it'll take effect with this version of pysam stats, this is the correct way to do it. Probably should add `run_exports` to `pysam`, actually. IIRC pysam isn't ABI compatible at minor versions, which we should keep track of.

**Comment by epruesse** [comment]
@biocondabot merge

**Pull request merged**
