### PR TITLE
Remove htslib/samtools/bcftools dependencies

### PR DESCRIPTION
**Pull request by mvdbeek**
This fixes https://github.com/pysam-developers/pysam/issues/640
which is an issue with the bioconda build of pysam.
Removing those dependencies will make pysam use the bundled
subset of htslib.
A side-effect of this is that pysam and samtools/bcftools/htslib
versions are now independent and can be mixed at will.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [ ] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by mvdbeek** [comment]
> HTSLib built on Bioconda uses a faster ZLIB implementation (libdeflate) and I'm not sure if the vanilla pysam build will grab it.

I think it does, it's unfortunate that we don't get the full build log, but you can see libdeflate being used in the failed previous build: https://circleci.com/gh/bioconda/bioconda-recipes/40770?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by bgruening** [comment]
@mvdbeek is this still needed? Want to update the PR?

**Comment by mvdbeek** [comment]
Not for the bug, which should be fixed, but I don't think it's reasonable to ship samtools with pysam -- the wheels don't come with samtools either.

**Comment by bgruening** [comment]
Then please merge it with master. @kyleabeauchamp ok?

**Comment by kyleabeauchamp** [comment]
Fine with me, but ping @AndreasHeger to confirm,

**Comment by AndreasHeger** [comment]
Yes, removing samtools/bcftools should be fine - they are test requirements only.

I don't fully understand the htslib removal but if you are confident it will work I have no objections.

**Comment by dpryan79** [comment]
If I didn't bork anything while handling the merge conflict then please merge :)

**Comment by kyleabeauchamp** [comment]
Seems good still, as long as the build is green

**Pull request merged**
