### PR TITLE
travis: fix travis-run.sh call

### PR DESCRIPTION
**Pull request by mbargull**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [ ] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [x] This PR does something else (explain below).

@bioconda/core: This is urgent! We didn't actually build on `master`, i.e., no packages for the channel could been built.

### CODE REVIEW

**Comment by mbargull** [comment]
DISCLAIMER: I don't know anything about those Travis stuff, but wanted to put this out quickly

**Comment by daler** [comment]
ah you beat me to it :) I'll close #6803.

**Comment by mbargull** [comment]
Must've only been seconds apart :D.

**Comment by mbargull** [comment]
@daler or anyone else: is it fine to merge?

**Comment by daler** [comment]
Let's hope this works!

**Comment by peterjc** [comment]
Worked for my new package added yesterday but not built at the time, see Gitter discussion - thanks!

**Pull request merged**
