### PR TITLE
add recipe for thapbi-pict v0.1.6 

### PR DESCRIPTION
**Pull request by peterjc**
Based on ``conda skeleton pypi thapbi-pict`` with the additional command line tool dependencies added by hand, and minimum version of Python made explicit. Also set a minimum for Biopython but probably not needed.

:information_source:
If this is your first pull request to Bioconda please ping `@bioconda/core` so it can be reviewed and to request being added as a member of the Bioconda team. Members of the Bioconda team are able to merge their own pull requests once tests and linting have passed.

----------------

* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [X] This PR adds a new recipe.
* [X] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by peterjc** [comment]
Linting failed with:

```
...
Adding in variants from internal_defaults
Adding in variants from /home/circleci/project/miniconda/conda_build_config.yaml
Adding in variants from /home/circleci/project/miniconda/lib/python3.6/site-packages/bioconda_utils/bioconda_utils-conda_build_config.yaml
	recipe	check	info	end_line	fix	output	should_be_noarch	start_line
0	recipes/thapbi-pict	should_be_noarch	"{'should_be_noarch': True, 'fix': 'add ""build: noarch"" section', 'start_line': 12, 'end_line': 16, 'output': 'thapbi-pict'}"	16	"add ""build: noarch"" section"	thapbi-pict	True	12
Exited with code 1
```

Right now this is a pure python package, so yes, ``should_be_noarch`` applies?

**Comment by dpryan79** [comment]
Why not just label it as noarch?

**Comment by peterjc** [comment]
@dpryan79 thanks, labelled as noarch - is there scope for ``conda skeleton pypi XXX`` doing that automatically?

Also, I think I worked out the URL problem - PyPY normalises minus signs to underscores in the URL. Is there an unwritten (Bio)Conda policy here for which character to use in package names?

From a recent checkout, in the recipes directory, the minus sign is clearly more common:

```
$ grep "name = " */meta.yaml  | grep _ -c
38
$ grep "name = " */meta.yaml  | grep "\-" -c
3321
```

Or, looking at directory names:

```
$ ls -1 | grep -c _
99
$ ls -1 | grep -c "\-"
4396
```

**Comment by peterjc** [comment]
Found a good example for doing the substitution in code, ``bio_hansel/meta.yaml``

https://github.com/bioconda/bioconda-recipes/blob/master/recipes/bio_hansel/meta.yaml

**Comment by dpryan79** [comment]
I'm not aware of the skeleton being that clever, since python packages tend to not have a "requires compilation" flag. In general I think the policy is to adhere as closely as possible to whatever the package calls itself, so as to minimize confusion.

**Comment by peterjc** [comment]
I thought the skeleton tool might be able to look at the available wheels to infer ``noarch``, but it sounds like that would be a big change.

Thank you for your advice.

**Pull request merged**
