### PR TITLE
Add compare-reads

### PR DESCRIPTION
**Pull request by mvdbeek**
----------------

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by mvdbeek** [comment]
Hmm, that's a little weird:
```
cp: cannot stat `/opt/conda/conda-bld/linux-64/compare-reads-0.0.1-h14c3975_0.tar.bz2': No such file or directory
```
which seems to be the only error I can spot. It looks like there's a mix of apostrophe and single quote in there, but that may be a red herring.

**Comment by mvdbeek** [comment]
OK, the rerun was more informative.

**Comment by mvdbeek** [comment]
That's rather surprising that you need to explicitly list python in the run requirements if I already list a python package (pysam), but OK, it works.

**Comment by stain** [comment]
Thank you, @mvdbeek!

**Pull request merged**
