### PR TITLE
Add ucsc command line utilities

### PR DESCRIPTION
**Pull request by percyfal**
Add ucsc command line utilities, including blat, bigwigtools etc.
Note that there was a problem in setting up the build in that despite
setting SSLDIR to $PREFIX/include/openssl, the openssl header files
could not be found. A workaround was to copy openssl header files to a
directory that was included in compilation commands, namely
kent/src/inc/.

### CODE REVIEW

**Comment by percyfal** [comment]
Is there a time/memory limit on travis? The docker test passes fine locally. The travis errors (first time it rebooted - memory issue?) indicate some limit on resources. It took quite some time to run locally, say 15 minutes.

**Comment by percyfal** [comment]
Ok, this seems to be the issue:

http://docs.travis-ci.com/user/build-timeouts/#Build-times-out-because-no-output-was-received

I'll see if it's possible to reduce build time or use the suggested solution.

**Comment by johanneskoester** [comment]
You could maybe use 2 threads.

**Comment by daler** [comment]
I thought I wrote a reply earlier today but I don't see it . . . ah well. To recap:

Building all of these utilities results in [600MB of binaries](http://genome-source.cse.ucsc.edu/gitweb/?p=kent.git;a=blob;f=src/userApps/README). 

What about one conda package per binary [downloaded from here](http://hgdownload.cse.ucsc.edu/admin/exe/linux.x86_64/)? We could bundle them together into logical groups (utils for working with wig/bigwig, utils for fasta files) with [`conda metapackage`](http://conda.pydata.org/docs/commands/build/conda-metapackage.html). That will help keep environments more lightweight.

**Comment by percyfal** [comment]
Well there you go, I had unset anaconda upload for another reason, otherwise I would have seen it - it's the uploading 200M that stalls the build. I think your solution is the way to go.

**Comment by percyfal** [comment]
Closing this now as ucsc is built in atomic recipes

**Pull request closed without merging**
