### PR TITLE
R getopt

### PR DESCRIPTION
**Pull request by dereeper**
* [ ] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [ ] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by bgruening** [comment]
@dereeper please look at the conda-forge channel. We are working very closely together with them and bioconda depends on conda-forge. So all this should be available from them already.

**Comment by dereeper** [comment]
Thanks! Sorry I didn't check before. All are in conda-forge channel already, except BGLR. Is it possible to add it in bioconda?

**Comment by bgruening** [comment]
That one should also go to conda-forge imho. I will do this for you with my next conda-forge PR.

**Comment by dereeper** [comment]
Great! Thanks!

**Pull request closed without merging**
