### PR TITLE
Update confindr to 0.7.3

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`confindr`](https://bioconda.github.io/recipes/confindr/README.html): **0.7.2** &rarr; **0.7.3**

[install with bioconda](http://bioconda.github.io/recipes/confindr/README.html) [Conda](https://anaconda.org/bioconda/confindr/files)

Info | Link
-----|-----
Recipe | [`recipes/confindr`](https://github.com//bioconda/bioconda-recipes/tree/bump/confindr/recipes/confindr) (click to view/edit other files)
Releases |[https://pypi.org/pypi/confindr/json](https://pypi.org/pypi/confindr/json)
Recipe Maintainer(s) | @adamkoziol

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by adamkoziol** [comment]
@bioconda/core
Not sure if I needed to leave the comment here for better visibility (sorry for spamming if I didn't need to do this): 
I'm now maintaining this package, and would like to be added to the bioconda team.

**Comment by mbargull** [comment]
@adamkoziol I've sent you an invite!
If you want to, you can add yourself to the `extra: recipe-maintainers` list of this recipe to get a ping whenever the bot issues version update PRs like this on.

**Comment by mbargull** [comment]
@Bioconda-Bot, please fetch artifacts

**Comment by mbargull** [comment]
@adamkoziol, feel free to post a `@BiocondaBot, please merge` to merge this PR.
(I'm leaving this up to you in case you wanted to add yourself to the recipe-maintainers list or not ;).)

**Comment by adamkoziol** [comment]
@mbargull 
Thanks for all you help!

**Comment by mbargull** [comment]
Thanks for getting on board and contributing!!

**Comment by adamkoziol** [comment]
@BiocondaBot, please merge

**Pull request merged**
