### PR TITLE
glimmerHMM bump build to 3; move required perl modules into bin/

### PR DESCRIPTION
**Pull request by nextgenusfs**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

GlimmerHMM training script is a perl script that has modules missing in the current build. Updated build.sh to include those perl module files.

### CODE REVIEW

**Comment by nextgenusfs** [comment]
This failed -- but seems that more is required than just the perl modules.  There are several "binaries" in the train directory that are also required, so not sure what the best way is to move them, i.e. might make more sense to retain the /train/ directory somewhere and then just symlink the trainGlimmerHMM script.

**Comment by zachcp** [comment]
hi @nextgenusfs , are you testing the build independently of the PR? Currently it looks like the build is failing a linting due to 

1. "glimmerHMM" in the recipe folder vs "glimmerhmm" in the meta.yaml.   For tha I would sugges lower-casing the folder name as is the convention on the other folder. 

2. g++ is not found in the machine. This probably hasn't been rebuilt since the bioconda overhaul so we may need to specify the compiler or patch the Makefile.

**Comment by nextgenusfs** [comment]
I haven’t had time to look through all of the changes in the build docs with compilers, etc. I had hoped it would just work... coupled with build problems I’ve had in my Mac more recently I tried to just update it quickly and that obviously failed.

**Comment by dpryan79** [comment]
Was this all taken care of in #15746?

**Comment by nextgenusfs** [comment]
Yes I will close this one.

**Pull request closed without merging**
