### PR TITLE
Update selene-sdk to 0.3.0

### PR DESCRIPTION
**Pull request by kathyxchen**
:information_source:
Bioconda has finished the [GCC7 migration](https://github.com/bioconda/bioconda-recipes/issues/13578). If you are dealing with C/C++ or Python package it can be that you need to rebuild other dependent packages. [Bioconda utils - update-pinning](https://bioconda.github.io/updating.html#updating-recipes-for-a-pinning-change) will assist you with that. If you have any questions please use [issue 13578](https://github.com/bioconda/bioconda-recipes/issues/13578).

----------------

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by epruesse** [comment]
@bioconda-bot lint

**Comment by epruesse** [comment]
@biocondabot lint

**Comment by kathyxchen** [comment]
The build continually fails on `libtorch.so.1: undefined symbol: nvrtcGetProgramLogSize`. I haven't been able to determine how I should fix this.

**Comment by npavlovikj** [comment]
I believe the reason for your error are the cuda libraries. 
The "pytorch" version used in your recipe is built with "cuda92py37h65efead_0" (pytorch 1.0.1 cuda92py37h65efead_0). There is no "cuda" in the build environment, and therefore the error you get. 
I assume you have cuda on you computer, that's why "conda build ." worked for you locally. I don't have cuda on my laptop, and even with "conda build .", I got the same error as here. 
The lower "pytorch" versions are not built with cuda, so if you have `pytorch>=0.4.1,<1` in your recipe, I believe the build should pass.

**Comment by kathyxchen** [comment]
Thank you @npavlovikj for looking into my issue! I really appreciate it. That makes sense. It is a bit unfortunate, because I'd like users to have the option of using anything >= 0.4.1 in PyTorch (since the package does work across diff versions of PyTorch when built locally), but I guess that won't be an option for the conda-installable package.

**Pull request merged**
