### PR TITLE
Try to update to RepeatMasker 4.1.0 using new configure

### PR DESCRIPTION
**Pull request by Juke34**
Update to new version and Simplification of the old recipe

----

> Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [ ] This PR adds a new recipe.
* [ ] AFAIK, this recipe **is directly relevant to the biological sciences**
      (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

> Everyone has access to the following BiocondaBot commands, which can be given in a comment:
>
>  * `@BiocondaBot please update` will cause the BiocondaBot to merge the master branch into a PR
>  * `@BiocondaBot please add label` will add the `please review & merge` label.
>  * `@BiocondaBot please fetch artifacts` will post links to packages and docker containers built by the CI system. You can use this to test packages locally before merging.
>
> For members of the Bioconda project, the following command is also available:
>
>  * `@BiocondaBot please merge` will cause packages/containers to be uploaded and a PR merged. Someone must approve a PR first! This has the benefit of not wasting CI build time required by manually merging PRs.
>
> If you have questions, please post them in gitter or ping `@bioconda/core` in a comment (if you are not able to directly ping `@bioconda/core` then the bot will repost your comment and enable pinging).

### CODE REVIEW

**Comment by Juke34** [comment]
@pvanheus you did work on the recipe in the past. Maybe you have recommendation for the recipe. Apparently you had set a  $REPEATMASKER_LIB_DIR and $REPEATMASKER_LIB_DIR env variables. I have removed them, is it a problem?
Currently as it is in this recipe in order to add a new lib, the user has to put it directly in ${CONDA_PREFIX}/RepeatMasker/Libraries.

**Comment by jebrosen** [comment]
> Currently as it is in this recipe in order to add a new lib, the user has to put it directly in ${CONDA_PREFIX}/RepeatMasker/Libraries.

This changed significantly in 4.1.0 - RepeatMasker now respects the new `-libdir` flag or the `LIBDIR` environment variable at runtime to choose a different Libraries directory, which should be made from a copy of the Libraries directory that ships with RepeatMasker.

**Comment by Juke34** [comment]
OK then we can use `LIBDIR` to select a custom library at runtime, this is good. We should probably add a patch to the recipe to make this env more specific in order to avoid collapsing with a potential LIBDIR from another package. e.g replacing `LIBDIR ` by  `REPEATMASKER_LIB_DIR `

**Comment by abretaud** [comment]
What's up here, can I help?
There's a 4.1.1 out now http://www.repeatmasker.org/

**Comment by nathanweeks** [comment]
I would like to see this one completed as well. Note that 4.1.1 will need at least h5py and pandas. FWIW, the dependency [trf has been updated](https://github.com/bioconda/bioconda-recipes/pull/24296) to use the open source version, and I have an open [PR to update rmblast](https://github.com/bioconda/bioconda-recipes/pull/24295).

**Comment by Juke34** [comment]
Sorry I have lost my fork of this work. I made a new PR here #24385 that take over this one.

**Pull request closed without merging**
