### PR TITLE
Add crispector2 2.0.0

### PR DESCRIPTION
**Pull request by theAguy**
This is an extension of the existence crispector tool that was published 2 years ago.
It has some added abilities and analyses that were lacking in the previous edition.
The additional code is significant, thus it is published as a new tool with the same name.
----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

Note that the <code>@BiocondaBot please merge</code> command is now depreciated. Please just squash and merge instead.

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by rpetit3** [comment]
Looking at CI here: https://dev.azure.com/bioconda/bioconda-recipes/_build/results?buildId=38903&view=logs&jobId=eb1ca712-fec5-5d93-deb0-40983fe61f2f&j=eb1ca712-fec5-5d93-deb0-40983fe61f2f&t=22a463be-d34e-5e0b-a210-c6720f3b9b60

Here's the linters error

```
ERROR: recipes/crispector2/meta.yaml:11: should_not_be_noarch_compiler: The recipe uses a compiler but is marked noarch
```

**Comment by rpetit3** [comment]
Looking at error on CI: https://dev.azure.com/bioconda/bioconda-recipes/_build/results?buildId=39111&view=logs&j=e14e69ff-a0ae-55c4-b71d-229b239cfb2f&s=3ca01b36-9fb6-5d7b-5c39-41ba760ebef3&t=4dddc55b-10bc-50fc-ac68-7ff899b7a030&l=589

```
  Running command python setup.py egg_info
  error in crispector setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected end or semicolon (after version specifier)
      plotly>=4.3.0numpy>=1.12.1
            ~~~~~~~^

```

Looking here: https://github.com/theAguy/crispector2/blob/master/setup.py#L8

Looks like a missing comma at the end of the line

**Comment by rpetit3** [comment]
@theAguy I'd recommend doing a re-release of v2 (or v2.0.1) to capture the latest change to the setup.py

**Comment by rpetit3** [comment]
Do you get the same error if you try to pip install locally?

```
  error: package directory 'crispector' does not exist
  error: subprocess-exited-with-error
```

**Comment by rpetit3** [comment]
@biocondabot please fetch artifacts

**Comment by theAguy** [comment]
Dear Robert,
Thank you for your help!
It seems like it worked.
Can you please guide me what is the next step? I am not quite sure.

Thank you very much!!

Guy

‫בתאריך יום ג׳, 22 באוג׳ 2023 ב-20:08 מאת ‪Robert A. Petit III‬‏ <‪
***@***.***‬‏>:‬

**Comment by theAguy** [comment]
@BiocondaBot please add label

**Comment by theAguy** [comment]
Hi,
I tried to run the package locally.
I downloaded the folder, extracted it and ran
`conda install -c packages crispector2-2.0.4-pyhdfd78af_0.tar.bz2_`

Then it printed the following:
```
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
```

However while running
`crispector --version`
The following error was raised:
```
Traceback (most recent call last):
  File "/opt/miniconda3/envs/crispector2_test2/bin/crispector", line 6, in <module>
    from crispector2.cli import main
  File "/opt/miniconda3/envs/crispector2_test2/lib/python3.7/site-packages/crispector2/cli.py", line 6, in <module>
    import click
ModuleNotFoundError: No module named 'click'
```

It seems like it did not install the packages that were listed in the meta.yaml and the setup.py.

If you have any direction for the solution it would be wonderful.
Thank you!

**Comment by theAguy** [comment]
Thank you Robert!
It worked wonderfully.
2 quick questions:
1. What is more to do in order for it to be in the packages list of Biocondonda?
2. Does Biocondona manage the dependencies when it will be available as a package?

Thank you!

**Review by rpetit3 — APPROVED** [review]

**Pull request merged**
