### PR TITLE
update shigatyper recipe for better container support

### PR DESCRIPTION
**Pull request by rpetit3**
Current container fails with:
```
  [E::fai_build3_core] Failed to open FASTA index /usr/local/lib/python3.10/site-packages/shigatyper/resources/ShigellaRef5.fasta.fai : Read-only file system
```

This PR aims to build the index during the build step so that containers will be useable

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by rpetit3** [comment]
@BiocondaBot please fetch artifacts

**Comment by rpetit3** [comment]
Making progress, being hit with this now:
```
[CRITICAL::ShigaTyper.run.report] Writing hits to ERR6005894SE-hits.tsv
Traceback (most recent call last):
  File "/usr/local/bin/shigatyper", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/shigatyper/shigatyper.py", line 604, in main
    run([args.SE], tempdir=tempdir, ont=args.ont)
  File "/usr/local/lib/python3.10/site-packages/shigatyper/shigatyper.py", line 512, in run
    List2.to_csv(output, sep="\t")
  File "/usr/local/lib/python3.10/site-packages/pandas/core/generic.py", line 3551, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/usr/local/lib/python3.10/site-packages/pandas/io/formats/format.py", line 1180, in to_csv
    csv_formatter.save()
  File "/usr/local/lib/python3.10/site-packages/pandas/io/formats/csvs.py", line 241, in save
    with get_handle(
  File "/usr/local/lib/python3.10/site-packages/pandas/io/common.py", line 789, in get_handle
    handle = open(
PermissionError: [Errno 13] Permission denied: 'ERR6005894SE-hits.tsv'
```

**Comment by rpetit3** [comment]
@BiocondaBot please fetch artifacts

**Comment by rpetit3** [comment]
@BiocondaBot please fetch artifacts

**Comment by rpetit3** [comment]
Looks like we might be in business now: 

```
docker run --entrypoint /bin/bash --rm -u $(id -u):$(id -g) -v ${PWD}:/data quay.io/biocontainers/shigatyper:2.0.1--pyhdfd78af_1 -c "shigatyper --SE /data/ERR6005894SE.fastq.gz --outdir /data/" 2> /dev/null
        Hit     Number of reads Length Covered  reference length        % covered       Number of variants      % accuracy
0       ipaH_c  32      740     780     94.9    0.0     100.0
1       ipaB    22      1015    1743    58.2    0.0     100.0
2       SdProv_wzx      16      1017    1320    77.0    0.0     100.0
3       SdProv_wzy      53      1104    1212    91.1    0.0     100.0
sample  prediction      ipaB    notes
ERR6005894SE    Shigella dysenteriae Provisional serotype 96-265        +       this strain is ipaB+, suggesting that it retains the virulent invasion plasmid.
```

Also working with the conda build:
```
shigatyper --SE ERR6005894SE.fastq.gz --name test 2> /dev/null
        Hit     Number of reads Length Covered  reference length        % covered       Number of variants      % accuracy
0       ipaH_c  32      740     780     94.9    0.0     100.0
1       ipaB    22      1015    1743    58.2    0.0     100.0
2       SdProv_wzx      16      1017    1320    77.0    0.0     100.0
3       SdProv_wzy      53      1104    1212    91.1    0.0     100.0
sample  prediction      ipaB    notes
test    Shigella dysenteriae Provisional serotype 96-265        +       this strain is ipaB+, suggesting that it retains the virulent invasion plasmid.
```

**Comment by rpetit3** [comment]
I'll eventually get these changes into the upstream repo so the patches won't be needed

**Comment by rpetit3** [comment]
@BiocondaBot please add label

**Review by simonbray — APPROVED** [review]

**Comment by simonbray** [comment]
@BiocondaBot please merge

**Pull request merged**
