### PR TITLE
package deepsig

### PR DESCRIPTION
**Pull request by peterjc**
Still need to sort out making the Python code importable.

* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [X] This PR adds a new recipe.
* [X] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

Still a work in progress, includes a set of Python 3 fixes which I have emailed the author and might be included in a future point release.

I am trying to ignore the author provided Python 2.7 virtual environment with dependencies provided in the release tar bar, and instead package this to run with conda provided dependencies.

### CODE REVIEW

**Comment by peterjc** [comment]
Oh yeah, I added a hash-bang line locally. Hmm, might be less surprising to replace the author provided invocation script ``runDeepSig.sh`` over allowing ``deepsig.py`` to be run directly.

**Comment by mbargull** [comment]
> instead package this to run with conda provided dependencies.

I highly respect that! Though, it looks like a ton of effort is need to reverse engineer their packaging 😮.
I gave it a quick look and it looks there is some additional stuff dumped into `deepsig/lib/python2.7/site-packages/external/`.

**Comment by peterjc** [comment]
I've got it to work locally with conda installed dependencies under Python 3, using just the authors ``deepsiglib`` folder of Python code, so I'm optimistic for the bioconda package.

**Comment by peterjc** [comment]
Hmm, locally I get ``Using TensorFlow backend.`` (and some warnings), but here ``Using Theano backend.`` and:

```
RuntimeError: 
Could not import 'mkl'.  Either install mkl-service with conda or set
MKL_THREADING_LAYER=GNU in your environment for MKL 2018.

If you have MKL 2017 install and are not in a conda environment you
can set the Theano flag blas.check_openmp to False.  Be warned that if
you set this flag and don't set the appropriate environment or make
sure you have the right version you *will* get wrong results.
```

**Comment by peterjc** [comment]
The backend selection is via ``keras``, both here and locally we have 2.0.9,
https://github.com/keras-team/keras/blob/2.0.9/keras/backend/__init__.py#L75

**Comment by peterjc** [comment]
OK, it is now using ``tensorflow``, but running into ``GLIBC_2.16`` issues:

```
...
+ runDeepSig.sh -h
Using TensorFlow backend.
Traceback (most recent call last):
  File "/opt/conda/conda-bld/deepsig_1517502082040/_t_env/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/opt/conda/conda-bld/deepsig_1517502082040/_t_env/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/opt/conda/conda-bld/deepsig_1517502082040/_t_env/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/opt/conda/conda-bld/deepsig_1517502082040/_t_env/lib/python3.5/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/opt/conda/conda-bld/deepsig_1517502082040/_t_env/lib/python3.5/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /lib64/libc.so.6: version `GLIBC_2.16' not found (required by /opt/conda/conda-bld/deepsig_1517502082040/_t_env/lib/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/conda-bld/deepsig_1517502082040/_t_env/bin/deepsig.py", line 8, in <module>
    from deepsiglib.helpers import printDate
  File "/opt/conda/conda-bld/deepsig_1517502082040/_t_env/deepsiglib/helpers.py", line 22, in <module>
    from keras.preprocessing.sequence import pad_sequences
  File "/opt/conda/conda-bld/deepsig_1517502082040/_t_env/lib/python3.5/site-packages/keras/__init__.py", line 3, in <module>
    from . import utils
  File "/opt/conda/conda-bld/deepsig_1517502082040/_t_env/lib/python3.5/site-packages/keras/utils/__init__.py", line 6, in <module>
    from . import conv_utils
  File "/opt/conda/conda-bld/deepsig_1517502082040/_t_env/lib/python3.5/site-packages/keras/utils/conv_utils.py", line 3, in <module>
    from .. import backend as K
  File "/opt/conda/conda-bld/deepsig_1517502082040/_t_env/lib/python3.5/site-packages/keras/backend/__init__.py", line 83, in <module>
    from .tensorflow_backend import *
  File "/opt/conda/conda-bld/deepsig_1517502082040/_t_env/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 1, in <module>
    import tensorflow as tf
  File "/opt/conda/conda-bld/deepsig_1517502082040/_t_env/lib/python3.5/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/opt/conda/conda-bld/deepsig_1517502082040/_t_env/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/opt/conda/conda-bld/deepsig_1517502082040/_t_env/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 72, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/opt/conda/conda-bld/deepsig_1517502082040/_t_env/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/opt/conda/conda-bld/deepsig_1517502082040/_t_env/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/opt/conda/conda-bld/deepsig_1517502082040/_t_env/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/opt/conda/conda-bld/deepsig_1517502082040/_t_env/lib/python3.5/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/opt/conda/conda-bld/deepsig_1517502082040/_t_env/lib/python3.5/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /lib64/libc.so.6: version `GLIBC_2.16' not found (required by /opt/conda/conda-bld/deepsig_1517502082040/_t_env/lib/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```

I'm not sure what version of ``libc`` we can expect for the builds/deployment?

(There are various open issues with the ``conda-forge`` package for ``tensorflow`` which is currently using Google's precompiled wheels rather than being build from source; not sure if that is relevant here)

**Comment by peterjc** [comment]
Is it true that BioConda still builds on CentOS 5 which has the quite old ``GLIBC_2.5``?

Locally I have libc 2.17, which being newer than 2.16 presumably just works:

```
$ ldd --version
ldd (GNU libc) 2.17
Copyright (C) 2012 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

**Comment by bgruening** [comment]
@peterjc BioConda is building on CentOS 6 and compatible platforms.

**Comment by peterjc** [comment]
Thanks @bgruening. I believe CentOS6 means GLIBC 2.12, which appears to be too old for the current conda-forge tensorflow 1.4.0 package:

```
    tensorboard:     0.4.0rc3-py35_2       conda-forge
    tensorflow:      1.4.0-py35_0          conda-forge
```

**Comment by peterjc** [comment]
Confirming on a CentOS6 machine, the Google provided wheels on PyPI (which are currently the basis of the ``conda-forge`` packages, fail:

```
$ pip3 install tensorflow
Collecting tensorflow
  Downloading tensorflow-1.5.0-cp35-cp35m-manylinux1_x86_64.whl (44.4MB)
    100% |████████████████████████████████| 44.4MB 22kB/s 
Requirement already satisfied: six>=1.10.0 in ./lib/python3.5/site-packages (from tensorflow)
Collecting wheel>=0.26 (from tensorflow)
  Downloading wheel-0.30.0-py2.py3-none-any.whl (49kB)
    100% |████████████████████████████████| 51kB 1.3MB/s 
Requirement already satisfied: numpy>=1.12.1 in ./lib/python3.5/site-packages (from tensorflow)
Collecting absl-py>=0.1.6 (from tensorflow)
  Downloading absl-py-0.1.10.tar.gz (79kB)
    100% |████████████████████████████████| 81kB 2.5MB/s 
Collecting tensorflow-tensorboard<1.6.0,>=1.5.0 (from tensorflow)
  Downloading tensorflow_tensorboard-1.5.0-py3-none-any.whl (3.0MB)
    100% |████████████████████████████████| 3.0MB 315kB/s 
Collecting protobuf>=3.4.0 (from tensorflow)
  Downloading protobuf-3.5.1-cp35-cp35m-manylinux1_x86_64.whl (6.4MB)
    100% |████████████████████████████████| 6.4MB 164kB/s 
Collecting markdown>=2.6.8 (from tensorflow-tensorboard<1.6.0,>=1.5.0->tensorflow)
  Downloading Markdown-2.6.11-py2.py3-none-any.whl (78kB)
    100% |████████████████████████████████| 81kB 1.3MB/s 
Collecting futures>=3.1.1 (from tensorflow-tensorboard<1.6.0,>=1.5.0->tensorflow)
  Downloading futures-3.1.1.tar.gz
Collecting werkzeug>=0.11.10 (from tensorflow-tensorboard<1.6.0,>=1.5.0->tensorflow)
  Downloading Werkzeug-0.14.1-py2.py3-none-any.whl (322kB)
    100% |████████████████████████████████| 327kB 1.5MB/s 
Collecting bleach==1.5.0 (from tensorflow-tensorboard<1.6.0,>=1.5.0->tensorflow)
  Using cached bleach-1.5.0-py2.py3-none-any.whl
Collecting html5lib==0.9999999 (from tensorflow-tensorboard<1.6.0,>=1.5.0->tensorflow)
  Using cached html5lib-0.9999999.tar.gz
Requirement already satisfied: setuptools in ./lib/python3.5/site-packages (from protobuf>=3.4.0->tensorflow)
Requirement already satisfied: appdirs>=1.4.0 in ./lib/python3.5/site-packages (from setuptools->protobuf>=3.4.0->tensorflow)
Requirement already satisfied: packaging>=16.8 in ./lib/python3.5/site-packages (from setuptools->protobuf>=3.4.0->tensorflow)
Requirement already satisfied: pyparsing in ./lib/python3.5/site-packages (from packaging>=16.8->setuptools->protobuf>=3.4.0->tensorflow)
Installing collected packages: wheel, absl-py, markdown, futures, werkzeug, html5lib, bleach, protobuf, tensorflow-tensorboard, tensorflow
  Running setup.py install for absl-py ... done
  Running setup.py install for futures ... done
  Found existing installation: html5lib 0.999999999
    Uninstalling html5lib-0.999999999:
      Successfully uninstalled html5lib-0.999999999
  Running setup.py install for html5lib ... done
  Found existing installation: bleach 2.0.0
    Uninstalling bleach-2.0.0:
      Successfully uninstalled bleach-2.0.0
Successfully installed absl-py-0.1.10 bleach-1.5.0 futures-3.1.1 html5lib-0.9999999 markdown-2.6.11 protobuf-3.5.1 tensorflow-1.5.0 tensorflow-tensorboard-1.5.0 werkzeug-0.14.1 wheel-0.30.0
```

But when you try to use it:

```
$ python3 -c "import tensorflow; print(tensorflow.__version__)"
Traceback (most recent call last):
  File "/home/xxx/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/xxx/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/xxx/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/xxx/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/xxx/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by /home/xxx/lib/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/xxx/lib/python3.5/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/home/xxx/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/xxx/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/xxx/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/xxx/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/xxx/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/xxx/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/xxx/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by /home/xxx/lib/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```

System details,

```
$ ldd --version
ldd (GNU libc) 2.12
Copyright (C) 2010 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
$ lsb_release -d
Description:	CentOS release 6.9 (Final)
```

**Comment by peterjc** [comment]
Cross reference what I think is the appropriate issue on the conda-forge package for tensorflow,
https://github.com/conda-forge/tensorflow-feedstock/issues/6

**Comment by bernt-matthias** [comment]
Seems to be in bioconda now

**Comment by peterjc** [comment]
Confirmed, deepsig v1.0 was added in https://github.com/bioconda/bioconda-recipes/pull/28278 - and has been updated since. Thanks!

**Pull request closed without merging**
