### PR TITLE
update viral-ngs 1.13.4 -> 1.14.0

### PR DESCRIPTION
**Pull request by tomkinsc**
* [x] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by tomkinsc** [comment]
Looks like this build is encountering a "no space left on device" [error](https://travis-ci.org/bioconda/bioconda-recipes/jobs/193437854#L986). Do we have a way to bypass quay builds yet?

**Comment by tomkinsc** [comment]
@bgruening: Do you have any suggestions for working around the "no space" issue? This is the package for our own software pipeline, with dependencies, so I can distribute in a separate channel if necessary (but I'd prefer to keep it in bioconda).

**Comment by bgruening** [comment]
Mh ... no real solution. I can build it for Linux and push it for you. We skip the build here completely and merge it without building, just adding a large note that this package needs to be build by the core team.
But, I can only build on Linux for you :(

**Comment by tomkinsc** [comment]
Hmm...that's far from ideal. I'd love to move to an automated process to push new builds to bioconda, but a manual build process is a definite block there unless I can have a (secondary) API key for pushes. At last check it _does_ build successfully for OSX. I'll note that this was not an issue before the move to rely on the quay/mulled/conda-forge container system.

This is an issue for metapackages too, right? Otherwise I could repackage dependencies into separate packages and include them all in the top level.

I'm not sure how to move forward here short of abandoning bioconda... :(

**Comment by bgruening** [comment]
The problem is more that your package is too big. There is, and there will be, some limitation on the build-system no matter what you do. Travis has a build-time limit of 45min and some space limit of several GB. We could get the build-time limit up to 2h, but we still have the space limitations for the foreseeable future.

Your last package already used the mulled stuff and it works, it's just that you package is not getting bigger and bigger. I wrote travis and hope we can get more space for a build but no promises.

**Comment by druvus** [comment]
viral-ngs is removed from bioconda so closing.

**Pull request closed without merging**
