### PR TITLE
Update cgat-apps and dependancies

### PR DESCRIPTION
**Pull request by Acribbs**
Describe your pull request here

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by Acribbs** [comment]
@bioconda/core it seems like cgat-apps is a blacklisted package and im not entirely sure why. Looking at build-fail-blacklist https://github.com/bioconda/bioconda-recipes/blob/f97da5b8470b1661ba458c57e2d9ce028204f3a0/build-fail-blacklist#L1549 its due to an UnsatisfiableError. Is there anyway to provide some further advice on how to remove our package from the blacklist. 

Without being able to do local testing it will be difficult for me to identify the precise issue. Is there a way for me to do local circle CI testing for exploring this type of error further? 

Thanks in advance.

**Comment by Acribbs** [comment]
Sorry, should have read documentation further, I see this here for testing locally (https://bioconda.github.io/contributor/building-locally.html), will give it a try

**Comment by dpryan79** [comment]
For whatever reason it doesn't actually install anything, which is what's causing the failure during testing. I've fixed the resolve conflict by allowing a more recent pysam. If an older version is strictly required we'll have to rebuild it with the current pinnings.

**Comment by Acribbs** [comment]
Thanks for all your hard work on this!

Pysam pinning isn't strictly necessary, newer versions of pysam broke our testing, but on closer inspection, it turns out one of our test files was corrupted and for whatever reason, pysam=0.15.2 was still able to parse this file. Not sure why the conflicts were occurring with this pinning though, could be that im using mamba for testing on GitHub actions and may be different to solving for conda on circleCI.

I think im going to close this for now, make changes to the testing in the cgat-apps repo and then use your pysam Conda pinning changes in a new pull request.

**Pull request closed without merging**
