### PR TITLE
w2rap-contiger new-recipes

### PR DESCRIPTION
**Pull request by mictadlo**
* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [X] This PR adds a new recipe.
* [ ] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [X] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by mictadlo** [comment]
Hi @bioconda/core,
Does anyone knows how to fix it? 

Thank you in advance,

Michal

**Comment by rvalieris** [comment]
same error: https://github.com/bioinfologics/w2rap-contigger/issues/28
the gcc being used is 4.8.2

**Comment by mictadlo** [comment]
How is it possible to change it to a newer gcc version?

**Comment by rvalieris** [comment]
conda-forge is currently transitioning to gcc7, but its not ready yet, I think its best to wait.

**Comment by daler** [comment]
Closing due to inactivity, please re-open if needed.

**Pull request closed without merging**
