### PR TITLE
add recipe for EToKi

### PR DESCRIPTION
**Pull request by rpetit3**
This PR adds EToKi, a toolkit used by Enterobase

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by rpetit3** [comment]
@BiocondaBot please fetch artifacts

**Comment by rpetit3** [comment]
@BiocondaBot please fetch artifacts

**Comment by rpetit3** [comment]
@BiocondaBot please update

**Comment by rpetit3** [comment]
@BiocondaBot please fetch artifacts

**Comment by rpetit3** [comment]
# Testing 

## Conda

### Build env
```
mamba clean -ay
mamba create -y -n test-etoki -c conda-forge -c bioconda \
    bbmap blast bowtie2 bwa click curl diamond ete3 fasttree flye \
    gatk kraken2 last megahit mmseqs2 nextpolish numba 'numpy==1.21.6' \
    pandas perl-lyve-set piler-cr pilon psutil 'python>=3.6' rapidnj \
    raxml raxml-ng samtools scikit-learn scipy simbac 'spades>=3.15' trf
conda activate test-etoki
unzip LinuxArtifacts.zip
conda install LinuxArtifacts/packages/noarch/etoki-1.2.2-hdfd78af_0.tar.bz2
```

### Basic Usage

```
EToKi.py
usage: EToKi [-h] {configure,prepare,assemble,MLSTdb,MLSType,MLSTsum,cgMLST,align,phylo,EBEis,uberBlast,clust,isCRISPOL} ...

options:
  -h, --help            show this help message and exit

sub-commands:
  {configure,prepare,assemble,MLSTdb,MLSType,MLSTsum,cgMLST,align,phylo,EBEis,uberBlast,clust,isCRISPOL}
    configure           install and/or configure 3rd party programs
    prepare             trim, collapse, downsize and rename the short reads.
    assemble            de novo or reference-guided assembly for genomic or metagenomic reads
    MLSTdb              Set up exemplar alleles and database for MLST schemes
    MLSType             MLST nomenclature using a local set of references
    MLSTsum             Summarise MLSType results and assign new allele designations
    cgMLST              Select a list of genes for the cgMLST scheme
    align               align multiple queried genomes to a single reference
    phylo               infer phylogeny and ancestral states from genomic alignments
    EBEis               in silico serotype prediction for Escherichia coli and Shigella spp.
    uberBlast           Use Blastn, uBlastp, minimap2 and/or mmseqs to identify similar sequences
    clust               linear-time clustering of short sequences using mmseqs linclust
    isCRISPOL           in silico prediction of CRISPOL array for Salmonella enterica serovar Typhimurium

EToKi.py configure --help
usage: EToKi.py configure [-h] [--install] [--usearch USEARCH] [--download_krakenDB] [--link_krakenDB KRAKEN_DATABASE] [--path PATH]

Install or modify the 3rd party programs.

options:
  -h, --help            show this help message and exit
  --install             install 3rd party programs
  --usearch USEARCH     usearch is required for ortho and MLSType. A 32-bit version of usearch can be downloaded from https://www.drive5.com/usearch/
  --download_krakenDB   When specified, miniKraken2 (8GB) will be downloaded into the EToKi folder. You can also use --link_krakenDB to use a pre-installed kraken2 database.
  --link_krakenDB KRAKEN_DATABASE
                        Kraken is optional in the assemble module. You can specify your own database here
  --path PATH, -p PATH  Specify path to the 3rd party programs manually. Format: <program>=<path>. This parameter can be specified multiple times
```

### Test default `EToKi.py configure`
```
2022-09-26 18:15:12.122535      bbduk ("/home/robert_petit/miniconda3/envs/test-etoki/bin/bbduk.sh") is present.
2022-09-26 18:15:12.130839      bbmerge ("/home/robert_petit/miniconda3/envs/test-etoki/bin/bbmerge.sh") is present.
2022-09-26 18:15:12.181474      blastn ("/home/robert_petit/miniconda3/envs/test-etoki/bin/blastn") is present.
2022-09-26 18:15:12.230572      blastp ("/home/robert_petit/miniconda3/envs/test-etoki/bin/blastp") is present.
2022-09-26 18:15:12.271949      bowtie2 ("/home/robert_petit/miniconda3/envs/test-etoki/bin/bowtie2") is present.
2022-09-26 18:15:12.318620      bowtie2build ("/home/robert_petit/miniconda3/envs/test-etoki/bin/bowtie2-build") is present.
2022-09-26 18:15:12.319847      bwa ("/home/robert_petit/miniconda3/envs/test-etoki/bin/bwa") is present.
2022-09-26 18:15:12.323165      diamond ("/home/robert_petit/miniconda3/envs/test-etoki/bin/diamond") is present.
2022-09-26 18:15:12.324410      fasttree ("/home/robert_petit/miniconda3/envs/test-etoki/bin/FastTreeMP") is present.
2022-09-26 18:15:12.408020      flye ("/home/robert_petit/miniconda3/envs/test-etoki/bin/flye") is present.
2022-09-26 18:15:12.427521      kraken2 ("/home/robert_petit/miniconda3/envs/test-etoki/bin/kraken2") is present.
2022-09-26 18:15:12.429789      lastal ("/home/robert_petit/miniconda3/envs/test-etoki/bin/lastal") is present.
2022-09-26 18:15:12.431609      lastdb ("/home/robert_petit/miniconda3/envs/test-etoki/bin/lastdb") is present.
2022-09-26 18:15:12.468261      makeblastdb ("/home/robert_petit/miniconda3/envs/test-etoki/bin/makeblastdb") is present.
2022-09-26 18:15:12.523270      megahit ("/home/robert_petit/miniconda3/envs/test-etoki/bin/megahit") is present.
2022-09-26 18:15:12.524415      minimap2 ("/home/robert_petit/miniconda3/envs/test-etoki/bin/minimap2") is present.
2022-09-26 18:15:12.527355      mmseqs ("/home/robert_petit/miniconda3/envs/test-etoki/bin/mmseqs") is present.
2022-09-26 18:15:12.588233      nextpolish ("/home/robert_petit/miniconda3/envs/test-etoki/bin/nextPolish") is present.
2022-09-26 18:15:12.590044      pilercr ("/home/robert_petit/miniconda3/envs/test-etoki/bin/pilercr") is present.
2022-09-26 18:15:12.882437      pilon ("/home/robert_petit/miniconda3/envs/test-etoki/share/pilon-1.24-0/pilon.jar") is present.
2022-09-26 18:15:12.884557      rapidnj ("/home/robert_petit/miniconda3/envs/test-etoki/bin/rapidnj") is present.
2022-09-26 18:15:12.886008      raxml ("/home/robert_petit/miniconda3/envs/test-etoki/bin/raxmlHPC") is present.
2022-09-26 18:15:12.888998      raxml_ng ("/home/robert_petit/miniconda3/envs/test-etoki/bin/raxml-ng") is present.
2022-09-26 18:15:12.896088      repair ("/home/robert_petit/miniconda3/envs/test-etoki/bin/repair.sh") is present.
2022-09-26 18:15:12.899773      samtools ("/home/robert_petit/miniconda3/envs/test-etoki/bin/samtools") is present.
2022-09-26 18:15:13.134708      spades ("/home/robert_petit/miniconda3/envs/test-etoki/bin/spades.py") is present.
2022-09-26 18:15:13.135828      trf ("/home/robert_petit/miniconda3/envs/test-etoki/bin/trf") is present.
2022-09-26 18:15:13.184846      usearch ("/home/robert_petit/miniconda3/envs/test-etoki/bin/blastp") is present.
2022-09-26 18:15:13.184928      WARNING - kraken_database is not present.
You can still use EToKi except the parameter "--kraken" in EToKi assemble will not work.
Alternatively you can download minikraken2 database using --download_krakenDB or pass an pre-installed database into EToKi using --link_krakenDB.
2022-09-26 18:15:13.186703      Configuration complete.
```
Looks good! Default paths are set

### Try with examples from dev repo
Only showing outputs from a few commands

```
git clone git@github.com:zheminzhou/EToKi.git
cd EToKi/

EToKi.py prepare --pe examples/S_R1.fastq.gz,examples/S_R2.fastq.gz -p examples/prep_out
2022-09-26 18:22:07.954048      Load in 2 read files from 1 libraries
2022-09-26 18:22:09.839308      Obtained 3850621 bases in 21912 reads after Trimming in Lib 0
2022-09-26 18:22:09.948902      Remove potential barcode bases at the beginning 10 bps of reads in examples/prep_out.1.0.s.fastq.gz
--pe examples/prep_out_L1_R1.fastq.gz,examples/prep_out_L1_R2.fastq.gz --se examples/prep_out_L1_SE.fastq.gz

EToKi.py MLSTdb -i examples/Escherichia.Achtman.alleles.fasta -r examples/Escherichia.Achtman.references.fasta -d examples/Escherichia.Achtman.convert.tab
Invalid database read for database data file=./NS_j03nqo1o/seq.db_h, database index=./NS_j03nqo1o/seq.db_h.index
getData: local id (4294967295) >= db size (972)
2022-09-27 18:34:52.581666      Exemplar sequences in ./NS_srhxkr7h/clsFna.clust.exemplar
2022-09-27 18:34:52.581724      Clusters in ./NS_srhxkr7h/clsFna.clust.tab
2022-09-27 18:34:52.607550      Run BLASTn starts
2022-09-27 18:34:52.915525      Run BLASTn finishes. Got 970 alignments
2022-09-27 18:34:52.915681      Run diamond starts
2022-09-27 18:34:53.843997      Run diamond finishes. Got 967 alignments
2022-09-27 18:34:54.022393      removed 0 paralogous sites.
2022-09-27 18:34:54.022473      obtained 5530 alleles and 38 references alleles
2022-09-27 18:34:54.024636      A file of reference alleles has been generated:  examples/Escherichia.Achtman.references.fasta
2022-09-27 18:34:54.062641      A lookup table of all alleles has been generated:  examples/Escherichia.Achtman.convert.tab

EToKi.py clust -p examples/Escherichia.Achtman.alleles_clust -i examples/Escherichia.Achtman.alleles.fasta -d 0.95 -c 0.95
2022-09-27 18:36:07.622716      Exemplar sequences in examples/Escherichia.Achtman.alleles_clust.clust.exemplar
2022-09-27 18:36:07.622781      Clusters in examples/Escherichia.Achtman.alleles_clust.clust.tab

EToKi.py align -r GCF_000010485:examples/GCF_000010485.1_ASM1048v1_genomic.fna.gz -p examples/phylo_out \
> GCF_000005845:examples/GCF_000005845.2_ASM584v2_genomic.fna.gz \
> GCF_000214765:examples/GCF_000214765.2_ASM21476v3_genomic.fna.gz \
> GCF_001566635:examples/GCF_001566635.1_ASM156663v1_genomic.fna.gz
## Repetitive 99095
## 1 114832
## 2 149633
## 3 631841
# 4 3844282
{
  "low_qual_map": {},
  "mappings": {
    "GCF_000005845": "examples/phylo_out.GCF_000005845.1.gff.gz",
    "GCF_000010485": "examples/phylo_out.GCF_000010485.0.gff.gz",
    "GCF_000214765": "examples/phylo_out.GCF_000214765.2.gff.gz",
    "GCF_001566635": "examples/phylo_out.GCF_001566635.3.gff.gz"
  },
  "matrix": "examples/phylo_out.matrix.gz"
}
```

Everything looks good, now try with Docker

## Docker

```
gzip -dc LinuxArtifacts/images/etoki:1.2.2--hdfd78af_0.tar.gz | docker load
```

### Basic Usage

```
docker run --rm -u $(id -u):$(id -g) -v ${PWD}:/data quay.io/biocontainers/etoki:1.2.2--hdfd78af_0 EToKi.py
usage: EToKi [-h]
             {configure,prepare,assemble,MLSTdb,MLSType,MLSTsum,cgMLST,align,phylo,EBEis,uberBlast,clust,isCRISPOL}
             ...

options:
  -h, --help            show this help message and exit

sub-commands:
  {configure,prepare,assemble,MLSTdb,MLSType,MLSTsum,cgMLST,align,phylo,EBEis,uberBlast,clust,isCRISPOL}
    configure           install and/or configure 3rd party programs
    prepare             trim, collapse, downsize and rename the short reads.
    assemble            de novo or reference-guided assembly for genomic or
                        metagenomic reads
    MLSTdb              Set up exemplar alleles and database for MLST schemes
    MLSType             MLST nomenclature using a local set of references
    MLSTsum             Summarise MLSType results and assign new allele
                        designations
    cgMLST              Select a list of genes for the cgMLST scheme
    align               align multiple queried genomes to a single reference
    phylo               infer phylogeny and ancestral states from genomic
                        alignments
    EBEis               in silico serotype prediction for Escherichia coli and
                        Shigella spp.
    uberBlast           Use Blastn, uBlastp, minimap2 and/or mmseqs to
                        identify similar sequences
    clust               linear-time clustering of short sequences using mmseqs
                        linclust
    isCRISPOL           in silico prediction of CRISPOL array for Salmonella
                        enterica serovar Typhimurium

docker run --rm -u $(id -u):$(id -g) -v ${PWD}:/data quay.io/biocontainers/etoki:1.2.2--hdfd78af_0 EToKi.py configure
2022-09-27 18:40:08.875129      bbduk ("/usr/local/bin/bbduk.sh") is present.
2022-09-27 18:40:08.883779      bbmerge ("/usr/local/bin/bbmerge.sh") is present.
2022-09-27 18:40:08.936761      blastn ("/usr/local/bin/blastn") is present.
2022-09-27 18:40:08.982669      blastp ("/usr/local/bin/blastp") is present.
2022-09-27 18:40:09.029808      bowtie2 ("/usr/local/bin/bowtie2") is present.
2022-09-27 18:40:09.081023      bowtie2build ("/usr/local/bin/bowtie2-build") is present.
2022-09-27 18:40:09.082426      bwa ("/usr/local/bin/bwa") is present.
2022-09-27 18:40:09.086746      diamond ("/usr/local/bin/diamond") is present.
2022-09-27 18:40:09.088070      fasttree ("/usr/local/bin/FastTreeMP") is present.
2022-09-27 18:40:09.176993      flye ("/usr/local/bin/flye") is present.
2022-09-27 18:40:09.197672      kraken2 ("/usr/local/bin/kraken2") is present.
2022-09-27 18:40:09.200008      lastal ("/usr/local/bin/lastal") is present.
2022-09-27 18:40:09.202053      lastdb ("/usr/local/bin/lastdb") is present.
2022-09-27 18:40:09.236770      makeblastdb ("/usr/local/bin/makeblastdb") is present.
2022-09-27 18:40:09.296714      megahit ("/usr/local/bin/megahit") is present.
2022-09-27 18:40:09.298093      minimap2 ("/usr/local/bin/minimap2") is present.
2022-09-27 18:40:09.301458      mmseqs ("/usr/local/bin/mmseqs") is present.
2022-09-27 18:40:09.369408      nextpolish ("/usr/local/bin/nextPolish") is present.
2022-09-27 18:40:09.371536      pilercr ("/usr/local/bin/pilercr") is present.
2022-09-27 18:40:09.375018      ERROR - pilon ("/usr/local/share/pilon-1.24-0/pilon.jar") is not present.
2022-09-27 18:40:09.377006      rapidnj ("/usr/local/bin/rapidnj") is present.
2022-09-27 18:40:09.378588      raxml ("/usr/local/bin/raxmlHPC") is present.
2022-09-27 18:40:09.382549      raxml_ng ("/usr/local/bin/raxml-ng") is present.
2022-09-27 18:40:09.390484      repair ("/usr/local/bin/repair.sh") is present.
2022-09-27 18:40:09.392758      samtools ("/usr/local/bin/samtools") is present.
2022-09-27 18:40:09.665679      spades ("/usr/local/bin/spades.py") is present.
2022-09-27 18:40:09.666908      trf ("/usr/local/bin/trf") is present.
2022-09-27 18:40:09.714822      usearch ("/usr/local/bin/blastp") is present.
2022-09-27 18:40:09.714931      WARNING - kraken_database is not present.
You can still use EToKi except the parameter "--kraken" in EToKi assemble will not work.
Alternatively you can download minikraken2 database using --download_krakenDB or pass an pre-installed database into EToKi using --link_krakenDB.
Traceback (most recent call last):
  File "/usr/local/bin/EToKi.py", line 49, in <module>
    etoki()
  File "/usr/local/bin/EToKi.py", line 43, in etoki
    eval(arg.cmd)(sys.argv[2:])
  File "/usr/local/share/etoki-1.2.2/modules/configure.py", line 424, in configure
    write_configure(configs)
  File "/usr/local/share/etoki-1.2.2/modules/configure.py", line 460, in write_configure
    pd.DataFrame(configs).to_csv(EnConf_file, sep='=', index=False, header=False)
  File "/usr/local/lib/python3.10/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/pandas/core/generic.py", line 3721, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/usr/local/lib/python3.10/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/pandas/io/formats/format.py", line 1189, in to_csv
    csv_formatter.save()
  File "/usr/local/lib/python3.10/site-packages/pandas/io/formats/csvs.py", line 241, in save
    with get_handle(
  File "/usr/local/lib/python3.10/site-packages/pandas/io/common.py", line 857, in get_handle
    handle = open(
PermissionError: [Errno 13] Permission denied: '/usr/local/share/etoki-1.2.2/modules/configure.ini'
```

This error is ok, since the dependencies are already set.

### Try with examples from dev repo
Only showing outputs from a few commands

```
git clone git@github.com:zheminzhou/EToKi.git
cd EToKi/

docker run --rm -u $(id -u):$(id -g) -v ${PWD}:/data quay.io/biocontainers/etoki:1.2.2--hdfd78af_0 EToKi.py prepare --pe /data/examples/S_R1.fastq.gz,/data/examples/S_R2.fastq.gz -p /data/examples/prep_out
2022-09-27 18:50:08.661691      Load in 2 read files from 1 libraries
2022-09-27 18:50:08.874634      Obtained 3868631 bases in 22002 reads after Trimming in Lib 0
--pe /data/examples/prep_out_L1_R1.fastq.gz,/data/examples/prep_out_L1_R2.fastq.gz

docker run --rm -u $(id -u):$(id -g) -v ${PWD}:/data quay.io/biocontainers/etoki:1.2.2--hdfd78af_0 EToKi.py MLSTdb -i /data/examples/Escherichia.Achtman.alleles.fasta -r /data/examples/Escherichia.Achtman.references.fasta -d /data/examples/Escherichia.Achtman.convert.tab
Traceback (most recent call last):
  File "/usr/local/bin/EToKi.py", line 49, in <module>
    etoki()
  File "/usr/local/bin/EToKi.py", line 43, in etoki
    eval(arg.cmd)(sys.argv[2:])
  File "/usr/local/share/etoki-1.2.2/modules/MLSTdb.py", line 177, in MLSTdb
    allele_text, refAlleles = buildReference(alleles, references, max_iden, min_iden, coverage, paralog, relaxEnd)
  File "/usr/local/share/etoki-1.2.2/modules/MLSTdb.py", line 55, in buildReference
    with tempfile.TemporaryDirectory(prefix='NS_', dir='.') as dirPath :
  File "/usr/local/lib/python3.10/tempfile.py", line 819, in __init__
    self.name = mkdtemp(suffix, prefix, dir)
  File "/usr/local/lib/python3.10/tempfile.py", line 368, in mkdtemp
    _os.mkdir(file, 0o700)
PermissionError: [Errno 13] Permission denied: './NS__njmbfw5'
```

So close, will need to patch it.

**Comment by rpetit3** [comment]
@BiocondaBot please fetch artifacts

**Comment by rpetit3** [comment]
@BiocondaBot please fetch artifacts

**Comment by rpetit3** [comment]
```
docker run --rm -u $(id -u):$(id -g) -v ${PWD}:/data quay.io/biocontainers/etoki:1.2.3--hdfd78af_0 EToKi.py MLSTdb -i /data/examples/Escherichia.Achtman.alleles.fasta -r /data/examples/Escherichia.Achtman.references.fasta -d /data/examples/Escherichia.Achtman.convert.tab
Invalid database read for database data file=/tmp/NS_t90lh45n/seq.db_h, database index=/tmp/NS_t90lh45n/seq.db_h.index
getData: local id (4294967295) >= db size (972)
2022-09-27 21:33:29.741924      Exemplar sequences in /tmp/NS_o696dkdz/clsFna.clust.exemplar
2022-09-27 21:33:29.741994      Clusters in /tmp/NS_o696dkdz/clsFna.clust.tab
2022-09-27 21:33:29.773625      Run BLASTn starts
2022-09-27 21:33:30.044658      Run BLASTn finishes. Got 970 alignments
2022-09-27 21:33:30.044811      Run diamond starts
2022-09-27 21:33:30.968038      Run diamond finishes. Got 967 alignments
2022-09-27 21:33:31.149411      removed 0 paralogous sites.
2022-09-27 21:33:31.149483      obtained 5530 alleles and 38 references alleles
2022-09-27 21:33:31.151609      A file of reference alleles has been generated:  /data/examples/Escherichia.Achtman.references.fasta
2022-09-27 21:33:31.190645      A lookup table of all alleles has been generated:  /data/examples/Escherichia.Achtman.convert.tab
```

We are good to go now

**Comment by rpetit3** [comment]
@BiocondaBot please add label

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@BiocondaBot please merge

**Comment by rpetit3** [comment]
Thank you!

**Pull request merged**
