### PR TITLE
Update and correct Recentrifuge's recipe

### PR DESCRIPTION
**Pull request by khyox**
Recentrifuge's recipe: Correct license, update version and requirements for dependencies. Mainly, this PR should solve a [bioconda issue reported to Recentrifuge](https://github.com/khyox/recentrifuge/issues/49) by a user.

### CODE REVIEW

**Comment by khyox** [comment]
Hi @thanhleviet, thanks for creating the recipe for Recentrifuge. Could you please review? It should be quick. Thanks!

**Review by bernt-matthias — APPROVED** [review]

**Comment by bernt-matthias** [comment]
Hi @khyox do you want to add yourself as maintainer?

**Comment by khyox** [comment]
Hi @bernt-matthias and thanks for the review and approval. I think adding myself as maintainer may be a good idea.

**Comment by bernt-matthias** [comment]
Thanks @khyox

**Pull request merged**
