### PR TITLE
Percolator fix for tandem2pin, msgf2pin, add tests to recipe

### PR DESCRIPTION
**Pull request by glormph**
Percolator 3.4 currently builds fine, but at runtime the XML parsing errors (parsing of tsv data is fine). ~I'm at a loss as to why, the error is basically this line in xerces-c:
lhttps://github.com/apache/xerces-c/blob/63f93ef81ab5844cf303823f8b4aa97f9d672fa0/src/xercesc/util/FileManagers/PosixFileMgr.cpp#L160~

~I'm not sure if this is solvable here or that xerces-c should be rebuilt, am suspecting the build/link/run environment but have been running into a wall with this unfortunately.~

This fixes the problem which seems to be caused by conda build's `detect_binary_files_with_prefix`, which does a good job fixing the $PREFIX variable in binaries, but unfortunately seems to add a null somewhere in the process.

(My other option is to use the old percolator 3.1 recipe, but I cant get it to install anymore using conda 4.8.1, lots of conflicting dependencies pop up. Using conda<4.7 it works fine.)

----

> Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it.

* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [ ] This PR adds a new recipe.
* [X] AFAIK, this recipe **is directly relevant to the biological sciences**
      (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [X] This PR does something else (explain below).

> Everyone has access to the following BiocondaBot commands, which can be given in a comment:
>
>  * `@BiocondaBot please update` will cause the BiocondaBot to merge the master branch into a PR
>  * `@BiocondaBot please add label` will add the `please review & merge` label.
>  * `@BiocondaBot please fetch artifacts` will post links to packages and docker containers built by the CI system. You can use this to test packages locally before merging.
>
> For members of the Bioconda project, the following command is also available:
>
>  * `@BiocondaBot please merge` will cause packages/containers to be uploaded and a PR merged. Someone must approve a PR first! This has the benefit of not wasting CI build time required by manually merging PRs.
>
> If you have questions, please post them in gitter or ping `@bioconda/core` in a comment (if you are not able to directly ping `@bioconda/core` then the bot will repost your comment and enable pinging).

### CODE REVIEW

**Comment by glormph** [comment]
On top of the above, percolator 3.1  does not support TMTpro (16plex), making this even more important to me.

**Comment by glormph** [comment]
@BiocondaBot update

**Comment by glormph** [comment]
@BiocondaBot please update

**Comment by glormph** [comment]
So when I try by hand the following seems to work for the msgf2pin converter.
```
docker run -ti bioconda/bioconda-utils-build-env /bin/bash
conda create testenv
conda activate testenv
conda install --file /path/to/envdefinition # see below for contents
curl -Lo perco.tar.gz https://github.com/percolator/percolator/archive/rel-3-04.tar.gz
tar xvfz perco.tar.gz
export PREFIX=/opt/conda/envs/testenv
export SRC_DIR=/percolator-rel-3-04/
cmake -DTARGET_ARCH=x86_64 -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$PREFIX -DXML_SUPPORT=ON -DCMAKE_PREFIX_PATH="$PREFIX;$PREFIX/lib"
make install
msg2pin -o test.pin $SRC_DIR/src/converters/data/converters/msgf2pin/target.mzid $SRC_DIR/src/converters/data/converters/msgf2pin/target.mzid
```
No problems. But when I run the same in circleci, with the env definition in `host` and `run`, and double checked `build` environments, it crashes just like in the test. Is there some difference in building/running I'm missing here? @bgruening would you know who to ask this?

Env definition (from a `conda list` when I finally got it to work)
```
_libgcc_mutex=0.1=conda_forge
_openmp_mutex=4.5=1_llvm
binutils_impl_linux-64=2.33.1=h53a641e_8
binutils_linux-64=2.33.1=h9595d00_16
boost=1.70.0=py37h9de70de_1
boost-cpp=1.70.0=h8e57a91_2
bzip2=1.0.8=h516909a_2
ca-certificates=2019.11.28=hecc5488_0
certifi=2019.11.28=py37_0
cmake=3.16.4=h28c56e5_0
expat=2.2.9=he1b5a44_2
gcc_impl_linux-64=7.3.0=hd420e75_5
gcc_linux-64=7.3.0=h553295d_16
gxx_impl_linux-64=7.3.0=hdf63c60_5
gxx_linux-64=7.3.0=h553295d_16
icu=64.2=he1b5a44_1
krb5=1.16.4=h2fd8d38_0
ld_impl_linux-64=2.33.1=h53a641e_8
libblas=3.8.0=14_openblas
libcblas=3.8.0=14_openblas
libcurl=7.68.0=hda55be3_0
libedit=3.1.20170329=hf8c457e_1001
libffi=3.2.1=he1b5a44_1006
libgcc-ng=9.2.0=h24d8f2e_2
libgfortran-ng=7.3.0=hdf63c60_5
libgomp=9.2.0=h24d8f2e_2
liblapack=3.8.0=14_openblas
libopenblas=0.3.7=h5ec1e0e_6
libssh2=1.8.2=h22169c7_2
libstdcxx-ng=9.2.0=hdf63c60_2
libuv=1.34.0=h516909a_0
llvm-openmp=9.0.1=hc9558a2_2
make=4.3=h516909a_0
ncurses=6.1=hf484d3e_1002
numpy=1.18.1=py37h95a1406_0
openssl=1.1.1d=h516909a_0
pip=20.0.2=py_2
python=3.7.6=h357f687_2
readline=8.0=hf8c457e_0
rhash=1.3.6=h14c3975_1001
setuptools=45.2.0=py37_0
sqlite=3.30.1=hcee41ef_0
tk=8.6.10=hed695b0_0
wheel=0.34.2=py_1
xerces-c=3.2.2=h8412b87_1004
xsd=4.0.0_dep=h6cbd23c_2
xz=5.2.4=h14c3975_1001
zlib=1.2.11=h516909a_1006
```

**Comment by raivivek** [comment]
Thanks @glormph! Looks good.

**Comment by raivivek** [comment]
@bioconda-bot please merge

**Pull request merged**
