### PR TITLE
r-archr: add aarch64/arm64 builds

### PR DESCRIPTION
**Pull request by martin-g**
Describe your pull request here

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

### General instructions

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

### Instructions for avoiding API, ABI, and CLI breakage issues
Conda is able to record and lock (a.k.a. pin) dependency versions used at build time of other recipes.
This way, one can avoid that expectations of a downstream recipe with regards to API, ABI, or CLI are violated by later changes in the recipe.
If not already present in the meta.yaml, make sure to specify `run_exports` (see [here](https://bioconda.github.io/contributor/linting.html#missing-run-exports) for the rationale and comprehensive explanation).
Add a `run_exports` section like this:

```yaml
build:
  run_exports:
    - ...

```

with `...` being one of:

| Case                             | run_exports statement                                               |
| -------------------------------- | ------------------------------------------------------------------- |
| semantic versioning              | `{{ pin_subpackage("myrecipe", max_pin="x") }}`     |
| semantic versioning (0.x.x)      | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}`   |
| known breakage in minor versions | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| known breakage in patch versions | `{{ pin_subpackage("myrecipe", max_pin="x.x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| calendar versioning              | `{{ pin_subpackage("myrecipe", max_pin=None) }}`    |

while replacing `"myrecipe"` with either `name` if a `name|lower` variable is defined in your recipe or with the lowercase name of the package in quotes.

### Bot commands for PR management

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

Note that the <code>@BiocondaBot please merge</code> command is now depreciated. Please just squash and merge instead.

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by mfansler** [comment]
This fails because of old R version. I think if we added some more thorough testing, I'd be okay with newer versions. It's just that upstream has repeatedly declared that this was only stable developed with Bioconductor 3.15 (R 4.1) whenever users hit runtime issues when installing with newer Bioconductor versions.

**Comment by martin-g** [comment]
The ARM64 builds fail because of:
```
Encountered problems while solving:
  - nothing provides requested bioconductor-chromvar
  - package bioconductor-motifmatchr-1.24.0-r43h7d2ed04_1 requires bioconductor-tfbstools >=1.40.0,<1.41.0, but none of the providers can be installed
  - package bioconductor-biostrings-2.70.1-r43h1184a65_2 requires r-base >=4.3,<4.4.0a0, but none of the providers can be installed
```
and the recipe requires `r-base 4.1`

**Comment by martin-g** [comment]
Thanks, @mfansler !
I just noticed that you commented before me.

Are you aware that there is only osx-64 build at https://anaconda.org/bioconda/r-archr ? 
It seems the linux-64 deploy has failed ?!

**Comment by mfansler** [comment]
@martin-g no I didn't catch that - thanks for the heads up! I just hit "Re-run" on [the failing CI](https://github.com/bioconda/bioconda-recipes/runs/31521131196) - hopefully that works this time around.

**Comment by mfansler** [comment]
@martin-g that seems to have done the trick - thanks again! 🤩 

I also saw a similar issue earlier with the `r-chromvarmotifs` post-merge upload (failed to push the BioContainer). Possibly sporadic connection issues.

**Pull request closed without merging**
