### PR TITLE
Add recipe for SKA v1.0

### PR DESCRIPTION
**Pull request by johnlees**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).

Just released variant caller etc for closely related bacterial genomes. Simple compile and install using C++. Should work on both linux and os x

### CODE REVIEW

**Comment by johnlees** [comment]
@bioconda/core Any idea why the variables for `$CXX`, `$CXXFLAGS`, `$LDFLAGS` aren't being exported? They are (and this works) when I try locally on both Linux and OS X

**Comment by johnlees** [comment]
Got it to work on linux using static linking (still not sure why the libstdc++ library in `/usr/lib64/` was being used, rather than the conda installed version) 

@bioconda/core could you please review? Thanks!

**Comment by pvanheus** [comment]
@johnlees static compilation should not be necessary but something seems to be going wrong with the `rpath` setting for the build.

**Comment by pvanheus** [comment]
Further investigation reveals that the `rpath` setting is correct. Please check to see if `libstdc++` is present in `$CONDA_PREFIX/lib` when you create an environment from your (non-static-compiled) build.

**Comment by johnlees** [comment]
@pvanheus I figured out why this is fine locally (`LD_LIBRARY_PATH` contained a directory with the correct `libstdc++` version)

The correct `libstdc++` is in `$CONDA_PREFIX/lib`, but at run time the older one in the system directories `/usr/lib/x86_64-linux-gnu` or `/usr/lib64` is being used instead. I don't understand how conda sets `LD_LIBRARY_PATH` to use the libraries it has installed in `$CONDA_PREFIX/lib`?

During conda build's install step, I get the message:
```
Warning: rpath /nfs/users/jl11/miniconda3/envs/ska/conda-bld/ska_1540822191817/_build_env/lib is outside prefix /nfs/users/jl11/miniconda3/envs/ska/conda-bld/ska_1540822191817/_h_env_placehold_placehold_placehold_p
lacehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place (removing it)
patchelf: file: /nfs/users/jl11/miniconda3/envs/ska/conda-bld/ska_1540822191817/_h_env_placehold_placehold_
placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/ska
    setting rpath to: $ORIGIN/../lib
   INFO (ska,bin/ska): Needed DSO x86_64-conda_cos6-linux-gnu/sysroot/lib/libm.so.6 found in CDT/compiler package defaults::gcc_impl_linux-64-7.3.
0-habb00fd_1
   INFO (ska,bin/ska): Needed DSO lib/libstdc++.so.6 found in defaults::libstdcxx-ng-8.2.0-hdf63c60_1
   INFO (ska,bin/ska): Needed DSO lib/libz.so.1 found in conda-forge::zlib-1.2.11-h470a237_3
   INFO (ska,bin/ska): Needed DSO lib/libgcc_s.so.1 found in defaults::libgcc-ng-8.2.0-hdf63c60_1
   INFO (ska,bin/ska): Needed DSO x86_64-conda_cos6-linux-gnu/sysroot/lib/libc.so.6 found in CDT/compiler package defaults::gcc_impl_linux-64-7.3.
0-habb00fd_1
```

**Comment by johnlees** [comment]
Locally, running `ldd ska` I now get:
```
libstdc++.so.6 => /nfs/jl11/miniconda3/envs/ska/conda-bld/ska_1540825683655/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin/../lib/libstdc++.so.6
```
which is the correct relative `rpath` set by `patchelf`

Why would this not be happening on the CI test?

**Comment by johnlees** [comment]
@pvanheus this seems fine now – I have no idea why this failed before as this is the same as a previous commit ¯\_(ツ)_/¯

@bioconda/core Ok to merge?

**Pull request merged**
