### PR TITLE
Update vcflib 

### PR DESCRIPTION
**Pull request by fplazaonate**
My previous attempt to disable "march=native" by unsetting EXTRA_FLAGS from the command line failed.
I guess this is because variable set via the command line are defined before those in CMakeLists.txt.
https://github.com/bioconda/bioconda-recipes/pull/50531

This new recipe directy remove EXTRA_FLAGS  from the CMakeLists.txt
I have built this recipe and I have I checked that the "march=native" flag does not appear anymore.

### CODE REVIEW

**Comment by fplazaonate** [comment]
@bgruening could you approve this?
Sorry for the waste of time.

**Comment by fplazaonate** [comment]
@BiocondaBot please add label

**Comment by bgruening** [comment]
@BiocondaBot please fetch artifacts

**Comment by bgruening** [comment]
Can you test those binaries please?

**Comment by fplazaonate** [comment]
I have built the library on a machine with a CPU that supports AVX extensions and installed it on a machine without.
Before the installation (i.e using vcflib-1.0.9-hdcf5f25_7 from bioconda), freebayes crashes with "Illegal instruction" error. After the installation (i.e using vcflib-1.0.9-h2bc3f7f_8 built locally), freebayes finishes normally.

objdump confirms that there are no avx instructions:
```
objdump -d  lib/libvcflib.so.1 | grep -Ec '\bv(add|sub|mul|div|mov|shuf|and|or|xor|perm|blend|cmp)'
0
```

**Review by mencian — APPROVED** [review]

**Pull request merged**
