### PR TITLE
add smeg

### PR DESCRIPTION
**Pull request by aemiol**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [ ] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by micknudsen** [comment]
It would be helpful if you modified the PR title to include the package name. If all PR were simple called "add new recipe", navigating PRs would be nearly impossible.

**Comment by aemiol** [comment]
@micknudsen modified PR title

**Comment by martin-mann** [comment]
something I noted (which might not solve the problem): you are explicitely requesting gcc.. needed?

If so, better replace with the recent `{{ compiler('c') }}` directive, which provides the system specific compiler.. afaik, `gcc` is not recommended anymore..

best,
Martin

**Comment by aemiol** [comment]
@martin-mann  still getting same build time error

**Comment by martin-mann** [comment]
jup I've seen.. but no idea why your build.sh goes ot hell... looks like it is eventually just copying things..

reping @bgruening any idea?

**Comment by martin-mann** [comment]
maybe just start uncommenting your build.sh from back to front to see if any specific call/setup in there causes the timeout

**Pull request closed without merging**
