### PR TITLE
added recipe for openslide

### PR DESCRIPTION
**Pull request by ThomasWollmann**
* [x] I have read the guidelines above.
* [x] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by ThomasWollmann** [comment]
Depends on https://github.com/bioconda/bioconda-recipes/pull/3435

**Comment by ThomasWollmann** [comment]
Any ideas for tests?

**Comment by bgruening** [comment]
Soory only on my mobile please look at tests that are using 'test ... .so'

**Comment by ThomasWollmann** [comment]
"If you want to run the test suite, you will need PyYAML, python-requests,
xdelta3, cjpeg and djpeg (from libjpeg), a Git checkout of OpenSlide,
at least one installed font, and > 120 GB of disk space. " ... do we have 120GB disk space?

**Comment by bgruening** [comment]
No we have not. It is also not necessary to run functional tests, we should only test the installation.
So usually if you have a binary, a simepl `my_program --help` is enough. For libraries you can use `test foo/bar/barfoo.so` and so on.
Sometime we only check if expected files are in the correct location with `which` and so on. But then local testing is very much needed and we trust the package author.

**Comment by ThomasWollmann** [comment]
Ok I'll give it a try. However stil waiting for dependencies.

**Comment by bgruening** [comment]
gdk-pixbuf is merged, but this one is also in a bad state.

**Comment by ThomasWollmann** [comment]
continued in https://github.com/bioconda/bioconda-recipes/pull/3737

**Pull request closed without merging**
