### PR TITLE
Update pbipa to 1.0.4

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`pbipa`](https://bioconda.github.io/recipes/pbipa/README.html): **1.0.3** &rarr; **1.0.4**

[install with bioconda](http://bioconda.github.io/recipes/pbipa/README.html) [Conda](https://anaconda.org/bioconda/pbipa/files)

Info | Link
-----|-----
Recipe | [`recipes/pbipa`](https://github.com//bioconda/bioconda-recipes/tree/bump/pbipa/recipes/pbipa) (click to view/edit other files)
Releases |[https://github.com/PacificBiosciences/pbipa/releases](https://github.com/PacificBiosciences/pbipa/releases)
Recipe Maintainer(s) | @pb-cdunn
Author | `@PacificBiosciences`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by pb-cdunn** [comment]
@bioconda-bot please fetch artifacts

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Comment by dpryan79** [comment]
@bioconda-bot please update

**Comment by dpryan79** [comment]
Did someone remove all of the release tags for pbipa?

**Pull request closed without merging**
