### PR TITLE
Update breseq to 0.33.2

### PR DESCRIPTION
**Pull request by epruesse**
Update [`breseq`](https://bioconda.github.io/recipes/breseq/README.html): **0.33.0** &rarr; **0.33.2**

[install with bioconda](http://bioconda.github.io/recipes/breseq/README.html) [Conda](https://anaconda.org/bioconda/breseq/files)

Info | Link
-----|-----
Recipe | [`recipes/breseq`](https://github.com//bioconda/bioconda-recipes/tree/bump/breseq/recipes/breseq) (click to view/edit other files)
Releases |[https://github.com/barricklab/breseq/releases](https://github.com/barricklab/breseq/releases)
Author | `@barricklab`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by epruesse** [comment]
@biocondabot rebuild

**Comment by epruesse** [comment]
@biocondabot lint

**Comment by epruesse** [comment]
@BiocondaBot lint

**Comment by epruesse** [comment]
@biocondabot recheck

**Comment by SheaML** [comment]
Just a +1, would be great to have this version available through bioconda. Thanks.

**Comment by dpryan79** [comment]
@bioconda-bot merge

**Comment by dpryan79** [comment]
@SheaML It'll be available in ~30 minutes :)

**Comment by SheaML** [comment]
thank you!

**Pull request merged**
