### PR TITLE
Update VADR build to better support container

### PR DESCRIPTION
**Pull request by rpetit3**
The container currently doesn't play nicely with `--entrypoint` due to all the ENV variables being lost. This PR offers an alternate script to run on containers to import the ENV variables.

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by rpetit3** [comment]
Looks like we are good now

### Install latest CI artfact
```
curl -L "https://174159-42372094-gh.circle-artifacts.com/0/tmp/artifacts/images/vadr%3A1.3--pl5262hdfd78af_3.tar.gz" | gzip -dc | docker load
```

### `env`
```
docker run --rm -u $(id -u):$(id -g) -v ${PWD}:/data quay.io/biocontainers/vadr:1.3--pl5262hdfd78af_3 env
VADRINFERNALDIR=/usr/local/bin
HOSTNAME=b4f8ad4b29a9
VADRFASTADIR=/usr/local/bin
PWD=/
VADRBLASTDIR=/usr/local/bin
CONDA_PREFIX=/usr/local
VADRINSTALLDIR=/usr/local
VADRHMMERDIR=/usr/local/bin
VADRBIOEASELDIR=/usr/local/bin
HOME=/
LANG=C.UTF-8
CONDA_PROMPT_MODIFIER=
PERL5LIB=/usr/local/share/vadr-1.3/vadr::/usr/local/share/sequip-0.08/lib
VADRMODELDIR=/usr/local/share/vadr-1.3/vadr-models
VADRVERSION=1.3
VADREASELDIR=/usr/local/bin
CONDA_SHLVL=1
SHLVL=0
CONDA_DEFAULT_ENV=/usr/local
BIO_EASEL_SHARE_DIR=/usr/local/share/perl-bio-easel-0.15
PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
VADRSCRIPTSDIR=/usr/local/share/vadr-1.3/vadr
VADRSEQUIPDIR=/usr/local/bin
```


### `env` using `--entrypoint` (via `vadr-run.sh`)
```
docker run --rm -u $(id -u):$(id -g) --entrypoint /bin/bash -v ${PWD}:/data quay.io/biocontainers/vadr:1.3--pl5262hdfd78af_3 -c "vadr-run.sh env"
VADRINFERNALDIR=/usr/local/bin
HOSTNAME=8eea53d70a47
VADRFASTADIR=/usr/local/bin
PWD=/
VADRBLASTDIR=/usr/local/bin
VADRINSTALLDIR=/usr/local
VADRHMMERDIR=/usr/local/bin
VADRBIOEASELDIR=/usr/local/bin
HOME=/
LANG=C.UTF-8
PERL5LIB=/usr/local/share/vadr-1.3/vadr::/usr/local/share/sequip-0.08/lib
VADRMODELDIR=/usr/local/share/vadr-1.3/vadr-models
VADRVERSION=1.3
VADREASELDIR=/usr/local/bin
SHLVL=1
BIO_EASEL_SHARE_DIR=/usr/local/share/perl-bio-easel-0.15
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
VADRSCRIPTSDIR=/usr/local/share/vadr-1.3/vadr
VADRSEQUIPDIR=/usr/local/bin
_=/usr/bin/env
```

### `v-annotate.pl` using  `--entrypoint` (via `vadr-run.sh`)
```
docker run --rm -u $(id -u):$(id -g) --entrypoint /bin/bash -v ${PWD}:/data quay.io/biocontainers/vadr:1.3--pl5262hdfd78af_3 -c  "vadr-run.sh v-annotate.pl -h"
# v-annotate.pl :: classify and annotate sequences using a model library
# VADR 1.3 (Aug 2021)
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# date:    Tue Nov  2 19:41:31 2021
#
Usage: v-annotate.pl [-options] <fasta file to annotate> <output directory to create>

basic options:
  -f             : force; if output dir exists, overwrite it
  -v             : be verbose; output commands to stdout as they're run
  --atgonly      : only consider ATG a valid start codon
  --minpvlen <n> : min CDS/mat_peptide/gene length for feature table output and protein validation is <n> [30]
  --nkb <n>      : number of KB of sequence for each alignment job and/or chunk is <n> [300]
  --keep         : do not remove intermediate files, keep them all on disk
... TRUNCATED ...
```

**Comment by rpetit3** [comment]
@BiocondaBot  please add label

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@BiocondaBot please merge

**Comment by rpetit3** [comment]
Thank you!

**Pull request merged**
