### PR TITLE
Update sccaf to 0.0.7

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`sccaf`](https://bioconda.github.io/recipes/sccaf/README.html): **0.0.6** &rarr; **0.0.7**

[install with bioconda](http://bioconda.github.io/recipes/sccaf/README.html) [Conda](https://anaconda.org/bioconda/sccaf/files)

Info | Link
-----|-----
Recipe | [`recipes/sccaf`](https://github.com//bioconda/bioconda-recipes/tree/bump/sccaf/recipes/sccaf) (click to view/edit other files)
Releases |[https://pypi.org/pypi/SCCAF/json](https://pypi.org/pypi/SCCAF/json)
Recipe Maintainer(s) | @pcm32

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by pcm32** [comment]
Please do not merge yet, I need to add some dependencies on the meta.yml, thanks.

**Comment by pcm32** [comment]
I have added the dependencies.

**Comment by pcm32** [comment]
Linting above is stuck for some reason, but tests have passed.

**Comment by dpryan79** [comment]
@pcm32 The lint is optional and the bot has been flaky lately, so go ahead and approve and merge without it running.

**Pull request merged**
