### PR TITLE
Update freyja to 1.5.2

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`freyja`](https://bioconda.github.io/recipes/freyja/README.html): **1.5.1** &rarr; **1.5.2**

[install with bioconda](http://bioconda.github.io/recipes/freyja/README.html) [Conda](https://anaconda.org/bioconda/freyja/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/freyja`](https://github.com//bioconda/bioconda-recipes/tree/bump/freyja/recipes/freyja) (click to view/edit other files)
Summary | Freyja recovers relative lineage abundances from mixed SARS-CoV-2 samples and provides functionality to analyze lineage dynamics.
Home | [https://github.com/andersen-lab/Freyja](https://github.com/andersen-lab/Freyja)
Releases |[https://github.com/andersen-lab/Freyja/tags](https://github.com/andersen-lab/Freyja/tags)
Author | `@andersen-lab`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by joshuailevy** [comment]
Looks like the testing was cancelled following a disconnection error - how do we re-run the tests? Doesn't look like I've got permission to do so.

**Comment by joshuailevy** [comment]
@martin-g or @mencian any chance you have any insights into how to fix this? 

Any help would be hugely appreciated! In the past I haven't had issues with these updates --but if I can't figure this out soon I'll have to set up some alternate installation approaches for users. Thanks in advance!!

**Comment by martin-g** [comment]
There is some problem with Azure CI ...
Many recipes fail to build with the same issue.
The only workaround I am aware of is to build the recipe in the `bulk` branch, i.e. Github Actions CI.

CC @aliciaaevans

**Comment by aliciaaevans** [comment]
We were hoping the upgrade of conda build might improve things. (Thanks @mencian for updating common.) I am talking with a few core members about next options.

**Comment by aliciaaevans** [comment]
@BiocondaBot please fetch artifacts

**Review by aliciaaevans — APPROVED** [review]

**Pull request merged**
