### PR TITLE
Update pronto to 1.2.0

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`pronto`](https://bioconda.github.io/recipes/pronto/README.html): **0.12.2** &rarr; **1.2.0**

[install with bioconda](http://bioconda.github.io/recipes/pronto/README.html) [Conda](https://anaconda.org/bioconda/pronto/files)

Info | Link
-----|-----
Recipe | [`recipes/pronto`](https://github.com//bioconda/bioconda-recipes/tree/bump/pronto/recipes/pronto) (click to view/edit other files)
Releases |[https://pypi.org/pypi/pronto/json](https://pypi.org/pypi/pronto/json)

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by dpryan79** [comment]
This requires contexter and nanoset

**Comment by althonos** [comment]
@dpryan79 : `v1.2.0` dropped `contexter` requirement, and `nanoset` is an optional dependency, so the dependency situation should be clear now.

**Comment by dpryan79** [comment]
@bioconda-bot please update

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Pull request merged**
