### PR TITLE
Update ampligone to 1.2.1

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`ampligone`](https://bioconda.github.io/recipes/ampligone/README.html): **1.1.0** &rarr; **1.2.1**

[install with bioconda](http://bioconda.github.io/recipes/ampligone/README.html) [Conda](https://anaconda.org/bioconda/ampligone/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/ampligone`](https://github.com//bioconda/bioconda-recipes/tree/bump/ampligone/recipes/ampligone) (click to view/edit other files)
Summary | Ampligone is a tool which accurately removes primer sequences from FastQ NGS reads in an amplicon sequencing experiment
Home | [https://rivm-bioinformatics.github.io/AmpliGone/](https://rivm-bioinformatics.github.io/AmpliGone/)
Releases |[https://pypi.org/pypi/AmpliGone/json](https://pypi.org/pypi/AmpliGone/json)
Recipe Maintainer(s) | @florianzwagemaker, @KHajji, @ids-bioinformatics

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Review by shenwei356 — APPROVED** [review]

**Comment by shenwei356** [comment]
@BiocondaBot please merge

**Comment by rpetit3** [comment]
@BiocondaBot please merge

**Comment by florianzwagemaker** [comment]
Thanks for taking a look at this again!

It seems however that version 1.2.0 was uploaded successfully (https://anaconda.org/bioconda/ampligone/files?version=1.2.0) despite this PR not being merged. I suppose the artifacts coming from https://github.com/bioconda/bioconda-recipes/pull/38508 were uploaded instead of this PR.
The recipe in `main` is now incorrect because of this but the uploaded artifacts are fine.

Maybe it's better to just close this PR and fix the recipe again with a future version?

**Comment by dpryan79** [comment]
@BiocondaBot please fetch artifacts

**Comment by dpryan79** [comment]
@BiocondaBot please merge

**Pull request merged**
