### PR TITLE
FlaiMapper: update to v3.0.0 (+py3)

### PR DESCRIPTION
**Pull request by yhoogstrate**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] ~AFAIK,~ this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by yhoogstrate** [comment]
Thanks @bgruening !

**Comment by bgruening** [comment]
Your are always welcome Youri!

**Comment by yhoogstrate** [comment]
And thanks for merging :+1:

**Comment by yhoogstrate** [comment]
@bgruening conda gives this error:

```
UnsatisfiableError: The following specifications were found to be in conflict:
  - flaimapper ==3.0.0 -> python 3.5*
  - python 2.7*
```

Do I need to pin the python/setuptools/pysam version? I don't understand how there is a link to python2.

**Comment by bgruening** [comment]
Are you using miniconda2? Try the following: `conda create -n flaimapper flaimapper python=3.5`

**Comment by yhoogstrate** [comment]
@bgruening Thanks! It was running conda 3, and after updating to 4.3 it still failed. But running the upgrade to 4.5 did the trick :+1:

**Pull request merged**
