### PR TITLE
Add taxonomy

### PR DESCRIPTION
**Pull request by apcamargo**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences**
      (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by raivivek** [comment]
@apcamargo Please add yourself to the maintainers section.

**Comment by apcamargo** [comment]
@raivivek is bioconda using the maintainers section now? What is it used for?

**Comment by raivivek** [comment]
I'm not sure if it is required. I believe the bot simply tags the
maintainer when any new autobump PR is created. So if you'd like to be
notified then good to have otherwise it's okay too.

**Comment by dpryan79** [comment]
@bioconda-bot please fetch artifacts

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Pull request merged**
