### PR TITLE
[intarna] switch to boost-cpp + docu extended

### PR DESCRIPTION
**Pull request by martin-raden**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by martin-raden** [comment]
replaces #13534

**Comment by bgruening** [comment]
```
checking for VRNA... yes
checking for compilation with Vienna RNA package headers... no
```

**Comment by martin-raden** [comment]
@bgruening success...

**Comment by bgruening** [comment]
Nice! Thanks!

**Comment by martin-raden** [comment]
could you please stop the pre-last CI runs... I have no rights..

**Comment by martin-raden** [comment]
@s-will could you please check whether the runtime problem still persists? many thanks!

**Pull request merged**
