### PR TITLE
mqc update: Plastid needs build number 0 for mQC

### PR DESCRIPTION
**Pull request by StevenVerbruggen**

### CODE REVIEW

**Comment by bgruening** [comment]
can you please include a test that catches this error?

**Comment by StevenVerbruggen** [comment]
You mean a test command like calling the help function of Plastid to see if Plastid works?

**Comment by bgruening** [comment]
Something that triggers a failure you tried to fix here :)

**Comment by StevenVerbruggen** [comment]
The help function of Plastid build 1 already triggered an error message. Build 0 did not, so I will include the help command of Plastid in the meta.yaml file then

**Pull request merged**
