### PR TITLE
unicycler 0.4.7

### PR DESCRIPTION
**Pull request by sjackman**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR updates an existing recipe.

### CODE REVIEW

**Comment by PertuyF** [comment]
Please have a look to #10955

**Comment by sjackman** [comment]
Duplicate of PR 
https://github.com/bioconda/bioconda-recipes/pull/10955.

**Comment by sjackman** [comment]
CircleCI on Linux
```
raise ValueError("invalid width %r (must be > 0)" % self.width)
ValueError: invalid width -6 (must be > 0)
```
https://circleci.com/gh/bioconda/bioconda-recipes/28732

**Comment by sjackman** [comment]
I can reproduce this error if I set the environment variable `COLUMNS` to a small value.
```
❯❯❯ COLUMNS=1 unicycler -h 2>&1 | tail -n3                                  ⏎
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/textwrap.py", line 248, in _wrap_chunks
    raise ValueError("invalid width %r (must be > 0)" % self.width)
ValueError: invalid width -5 (must be > 0)
```
Unicycler thinks the number of columns of the terminal is 0.
cc @rrwick

**Comment by sjackman** [comment]
I've added `COLUMNS=80 unicycler -h` to see if that helps.

**Comment by sjackman** [comment]
Yeah, that fixed it!

**Comment by PertuyF** [comment]
Well done!

**Comment by PertuyF** [comment]
@sjackman Did you get this version working? It looks like [this issue](https://github.com/rrwick/Unicycler/issues/140) is still present in Unicycler v0.4.7 from Bioconda.

**Comment by sjackman** [comment]
I've been using Unicycler 0.4.7 frequently, but for Nanopore-only assemblies. I haven't yet used it for a hybrid Illumina+Nanopore assembly.

**Pull request merged**
