### PR TITLE
Add bioconductor package motifbreakR to bioconda repo

### PR DESCRIPTION
**Pull request by nturaga**

### CODE REVIEW

**Comment by nitesh1989** [comment]
One of the build fails because conda-build is not updated.

**Comment by johanneskoester** [comment]
That's only a warning. The real error is below:
```
Error:  Packages missing in current osx-64 channels: 
  - bioconductor-gviz
  - bioconductor-motifstack
```

**Comment by nitesh1989** [comment]
Thanks @johanneskoester , I made a change, not sure if this is the correct approach, but the link to Gviz_1.14.2 was broken, so I switched it out to the latest one available on Bioc 3.2, Gviz 1.14.6

**Comment by johanneskoester** [comment]
@daler, I thought the bioconductor packages should use [bioarchive](https://bioarchive.galaxyproject.org/#/pkg/Biobase/) as a source. Don't the scripts do that by default already? If not, can we change that behaviour?

**Comment by bgruening** [comment]
@nitesh1989 you should use really your bioarchive links ;)
@johanneskoester: @nitesh1989 is in charge for bioarchive just to let you know ;)

**Comment by nitesh1989** [comment]
@bgruening @johanneskoester  bioarchive, skipped that specific version of it of the package Gviz. It had some missing information in it, so bioarchive skips it.

**Comment by nitesh1989** [comment]
Is there a way, I can just skip OSX build for this? I'm not able to see the same issue on my local machine, with ```conda-build bioconductor-motifbreakr --channel bioconda --channel r```

**Comment by jxtx** [comment]
skip: True [osx]

Under the build section. See
http://conda.pydata.org/docs/building/meta-yaml.html#skipping-builds

**Comment by nitesh1989** [comment]
Cheers @jxtx . Missed that part in the docs.

**Comment by druvus** [comment]
@nturaga Finally added motifbreakR in #3689.

**Pull request closed without merging**
