### PR TITLE
Trying to update samtools build with ncurses

### PR DESCRIPTION
**Pull request by jpuritz**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by kyleabeauchamp** [comment]
AFAIK it we should have ncurses in the meta.yaml if we're going to build with it.  E.g. it's bad to have requirements that are not explicitly annotated.

**Comment by jpuritz** [comment]
Ok, I think I made all the appropriate changes.  This should allow the reactivate the `tview` module of samtools

**Comment by rvalieris** [comment]
>checking for gcc... gcc
checking whether the C compiler works... no
configure: error: C compiler cannot create executables

it doesn't look like this issue was introduced by this patch, but I don't know either. ping @bioconda/osx

**Comment by mbargull** [comment]
Could be that it's because the linker flags have been overridden. Let's see what the logs show in a bit..

**Comment by mbargull** [comment]
```
configure:2449: checking whether the C compiler works
configure:2471: gcc  -arch x86_64 -I/Users/distiller/project/miniconda/conda-bld/samtools_1519762966388/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/include -Wl,--add-needed conftest.c  >&5
ld: unknown option: --add-needed
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
Removed that flag for macOS -- is that fine?

**Comment by jpuritz** [comment]
Awesome.  Thanks for the help.

**Pull request merged**
