### PR TITLE
Reinstate 3seq: cull unnecessary dependencies and update checksum

### PR DESCRIPTION
**Pull request by jmarshall**
This package was recently added to _build-fail-blacklist_ when it failed to build on **bulk** due to a checksum mismatch.

3seq is a C++ program built using CMake. It has no Python and there is no need to build multiple per-Python-version packages. It also does not use autotools or zlib.

PR #36477 by @nickjcroucher contains 771230f69e7d54e2023b72611789a24984d95e5f, which indicates that the source tarball checksum changed sometime up to early September. :shrug: So this PR just updates it too. (3seq is hosted on GitLab, and the new checksum gzipped tarball has its XFL field set to 0, consistent with [this recent report](https://gitlab.alpinelinux.org/alpine/aports/-/issues/12494) of altered GitLab archive checksums. If I had an old checksum gzipped tarball available I could confirm this further; but it is a likely explanation of the checksum change.)

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by jmarshall** [comment]
@BiocondaBot please fetch artifacts

**Comment by nickjcroucher** [comment]
Thanks for your help @jmarshall - I added the unnecessary python packages to the recipe because that was the only way I found to generate artifacts - happy to learn how to do this properly!

**Comment by jmarshall** [comment]
@BiocondaBot please add label

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@BiocondaBot please merge

Thanks @jmarshall!

**Pull request merged**
