### PR TITLE
add recipe for sra-human-scrubber

### PR DESCRIPTION
**Pull request by rpetit3**
This PR adds a recipe for [sra-human-scrubber](https://github.com/ncbi/sra-human-scrubber) a tool for removing human reads from FASTQs.

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by rpetit3** [comment]
Testing
```
mamba create -n test-scrubber -c https://164281-42372094-gh.circle-artifacts.com/0/tmp/artifacts/packages -c conda-forge -c bioconda sra-human-scrubber
...TRUNCATED...
  sra-human-scrubber  1.0.2021_05_05  hdfd78af_0          164286-42372094-gh.circle-artifacts.com/0/tmp/artifacts/packages/noarch       2 MB
...TRUNCATED...
Please run 'init_db.sh' to download the database required to run sra-human-scrubber.
These files will be downloaded to /home/robert_petit/miniconda3/envs/test-scrubber/share/sra-human-scrubber-1.0.2021_05_05/data.



done
#
# To activate this environment, use
#
#     $ conda activate test-scrubber
#
# To deactivate an active environment, use
#
#     $ conda deactivate

conda activate test-scrubber
env | grep SCRUBBER
SCRUBBER_SHARE=/home/robert_petit/miniconda3/envs/test-scrubber/share/sra-human-scrubber-1.0.2021_05_05
SCRUBBER_ROOT=/home/robert_petit/miniconda3/envs/test-scrubber
```
```
which scrub.sh
/home/robert_petit/miniconda3/envs/test-scrubber/bin/scrub.sh

scrub.sh -h
Usage: scrub.sh [OPTIONS] file.fastq
OPTIONS:
        -n ; Replace sequence length of identified spots with 'N'
        -r ; Save identified spots to file.fastq.spots_removed
        -h ; Display this message
```
```
init_db.sh
...TRUNCATED...
<
  0  611M    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0{ [5 bytes data]
100  611M  100  611M    0     0  8570k      0  0:01:13  0:01:13 --:--:-- 5950k
* Connection #0 to host ftp.ncbi.nlm.nih.gov left intact

ls -lh ${SCRUBBER_SHARE}/data
total 612M
-rw-r--r-- 1 robert_petit robert_petit 612M Aug  5 01:08 human_filter.db
-rw-rw-r-- 2 robert_petit robert_petit    0 Aug  5 00:56 sra-human-scrubber-placeholder.txt
```

```
scrub.sh test
2021-08-05 01:58:38     aligns_to version 0.60
2021-08-05 01:58:38     hardware threads: 16, omp threads: 16
2021-08-05 01:58:38     loading time (sec) 0
2021-08-05 01:58:38     /tmp/tmp.GtiE2dtKw4/scrubber_test.fastq.fasta
2021-08-05 01:58:38     100% processed
2021-08-05 01:58:38     total spot count: 2
2021-08-05 01:58:38     total read count: 2
2021-08-05 01:58:38     total time (sec) 0
1  spot(s) removed.

test succeeded

```
```
# own samples
scrub.sh test.fastq
2021-08-05 02:00:12     aligns_to version 0.60
2021-08-05 02:00:12     hardware threads: 16, omp threads: 16
2021-08-05 02:00:12     loading time (sec) 0
2021-08-05 02:00:12     test.fastq.fasta
2021-08-05 02:00:12     77% processed
2021-08-05 02:00:16     100% processed
2021-08-05 02:00:16     total spot count: 42124
2021-08-05 02:00:16     total read count: 42124
2021-08-05 02:00:16     total time (sec) 4
0  spot(s) removed.

scrub.sh test2.fastq
2021-08-05 02:01:59     aligns_to version 0.60
2021-08-05 02:01:59     hardware threads: 16, omp threads: 16
2021-08-05 02:01:59     loading time (sec) 0
2021-08-05 02:01:59     test2.fastq.fasta
2021-08-05 02:01:59     15% processed
2021-08-05 02:02:02     100% processed
2021-08-05 02:02:02     total spot count: 205041
2021-08-05 02:02:02     total read count: 205041
2021-08-05 02:02:02     total time (sec) 2
70  spot(s) removed.
```

Tests look good

**Comment by rpetit3** [comment]
@biocondabot please add label

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Comment by rpetit3** [comment]
Thank you!

**Pull request merged**
