### PR TITLE
Added GATK 4.0.4.0 Updated Recipe

### PR DESCRIPTION
**Pull request by apeltzer**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

Note that GATK team decided to change the name of the wrapper script from "gatk-launch" to gatk, so I also changed it in here. I suppose that should be fine with everyone?

### CODE REVIEW

**Comment by bgruening** [comment]
Thanks @apeltzer!

**Comment by chapmanb** [comment]
Alexander -- thanks for keeping gatk up to date. Swapping over the script name from `gatk-launch` to `gatk` is breaking my usage of gatk4 and I wonder if we could swap it back. The major issue is that `gatk` is already used in bioconda for the `gatk` (gatk3) recipe so it's not possible to support both installs concurrently.

If we're opposed to `gatk-launch`, which I just kept for back compatibility, I'd propose `gatk4` to at least differentiate.

What do y'all think?

**Comment by apeltzer** [comment]
Had a discussion about this recently with @marchoeppner and we were just thinking to follow the recommendation that GATK developers made recently to "go back to just `gatk`" instead of `gatk-launch`. I see your problem though, so maybe its worth thinking about differentiating between `gatk`(legacy, 3.X) and `gatk4` for version 4.X as you suggested?

**Comment by ewels** [comment]
@chapmanb - out of curiosity, why do you want to have both versions loaded at the same time?

**Comment by bgruening** [comment]
I would stick to whatever upstream provides. If GATK developers did not consider changing the name we should also not change it, if not absolutely needed. Please keep in mind that people are using these packages/containers in automatic environments and do not tweak their scripts to be "bioconda" conform.

**Comment by chapmanb** [comment]
Alexander, Phil and Björn;
Thanks so much for the thoughts. I agree that it would be best to stick with what upstream provides, but would like some way to tackle back compatibility and also supporting GATK 3 and 4. In bcbio we support users who want GATK 3 for back compatibility with previous runs, so I see that being a use case for the forseeable future. I also would like some measure of back compatibility: the Broad team were using `gatk-launch` and then swapped over to just `gatk` which created this disconnect with upstream.

Some choices to help resolve this:

- Keep the GATK 4 script as `gatk` and then switch GATK 3 to `gatk3`. The downside is that might create confusion from users who expected `gatk` to be GATK 3 and disrupts users of both packages.
- Rename the GATK4 script to `gatk4`. This creates a new naming scheme in bioconda only and requires a transition for gatk4 users using gatk-launch.
- Keep GATK4 as `gatk-launch`. The downside is that this does not match upstream and is the previous naming scheme.

I favored the last in trying to create less disruption (I like back compatibility) but understand coordination with upstream as well. What do you think about the first suggestion if we want to stay consistent with script naming?

**Comment by kyleabeauchamp** [comment]
We could also make a metapackage that just builds a renamed version for dual-GATK environments, so that the "primary" packages use the upstream naming.

**Comment by apeltzer** [comment]
I like @kyleabeauchamp s suggestion for the extreme case of having both gatk versions installed. However, I dislike having a separate scheme for bioconda only, as this would enforce people to use exactly this scheme and does not line up with upstream. So I also tend to your option 1, although that requires changes for both GATK3 and GATK4 users - however its not as bad, as some might even switch to GATK4 anyways (and don't really care about that) or can willingly change to call gatk3 in case they definitely need to be compatible with GATK3 (which was anyways very difficult to package with bioconda if I'm not wrong?).

**Comment by johanneskoester** [comment]
I think it would be preferable to use `gatk` for the new launcher and `gatk3` for the old launcher. THis way people can use both without problems in one environment (this will be rare), but it is straightforward to just use the latest.

**Comment by johanneskoester** [comment]
At some point, we should also consider to rename the old recipe to `gatk3` and the new to `gatk`.

**Pull request merged**
