### PR TITLE
Add openblas

### PR DESCRIPTION
**Pull request by drramki-chop**
- [ ] I have read the guidelines above.
- [ ] This PR adds a new recipe.
- [ ] This PR updates an existing recipe.
- [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by bgruening** [comment]
@drramki-chop I think this should be included/updated in https://github.com/conda-forge.

**Comment by drramki-chop** [comment]
I got the recipe from https://github.com/conda/conda-recipes.

Is there a way to add a requirement from this channel to bioconda? (in my
meta file). I need blas to compile a tool.

**Comment by bgruening** [comment]
Yeah we are working on it. @johanneskoester did some awesome work on getting everything ready for it.

**Comment by bgruening** [comment]
We now depend on conda-forge, so I will close this now.

**Pull request closed without merging**
