### PR TITLE
Remove first user notice from PR template

### PR DESCRIPTION
**Pull request by epruesse**
:information_source:
If this is your first pull request to Bioconda please ping `@bioconda/core` so it can be reviewed and to request being added as a member of the Bioconda team. Members of the Bioconda team are able to merge their own pull requests once tests and linting have passed.

----------------

* [ ] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [ ] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [x] This PR does something else (explain below).

### CODE REVIEW

**Comment by dpryan79** [comment]
Should we add something about using the `Please review and merge` label if they're not members of bioconda or pinging use if there are issues?

**Comment by epruesse** [comment]
Non-members can't add labels.

**Comment by dpryan79** [comment]
Hmm, we should still leave something in about pinging us then. It's really unfortunate that they can't add labels. Maybe we can add that to the bot?

**Comment by epruesse** [comment]
Well, first timers will get the welcome message. It contains all the pinging stuff.

**Pull request merged**
