### PR TITLE
Update omero-py to 5.10.1

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`omero-py`](https://bioconda.github.io/recipes/omero-py/README.html): **5.9.1** &rarr; **5.10.1**

[install with bioconda](http://bioconda.github.io/recipes/omero-py/README.html) [Conda](https://anaconda.org/bioconda/omero-py/files)

Info | Link
-----|-----
Recipe | [`recipes/omero-py`](https://github.com//bioconda/bioconda-recipes/tree/bump/omero_py/recipes/omero-py) (click to view/edit other files)
Releases |[https://pypi.org/pypi/omero-py/json](https://pypi.org/pypi/omero-py/json)

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by bgruening** [comment]
@BiocondaBot update

**Comment by bgruening** [comment]
@BiocondaBot please update

**Comment by lldelisle** [comment]
The error is:
```
ModuleNotFoundError: No module named 'yaml'
```
I am sorry I don't manage to checkout to this PR to change it myself...

**Comment by lldelisle** [comment]
I managed #31650

**Comment by lldelisle** [comment]
I don't see any error...
Do you know what is the meaning/goal of:
https://github.com/bioconda/bioconda-recipes/blob/c6ff644ecea2c7c9cb1372b49074b945945a8fb1/recipes/omero-py/meta.yaml#L34-L35

**Comment by lldelisle** [comment]
`15:25:18 BIOCONDA INFO (ERR) [Nov 22 15:25:18] SOUT FATAL: Running /usr/local/bin/omero as root can corrupt your directory permissions.`
This goes above my skills.

**Comment by lldelisle** [comment]
Still
```
16:03:48 BIOCONDA INFO (ERR) [Nov 22 16:03:48] SOUT FATAL: Running /usr/local/bin/omero as root can corrupt your directory permissions.
```
https://app.circleci.com/pipelines/github/bioconda/bioconda-recipes/56206/workflows/13b6f41f-3699-4a31-8916-fe426205a94c/jobs/176361?invite=true#step-106-2465

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
@bioconda-bot please merge

**Pull request merged**
