### PR TITLE
Update pronto to 1.0.0

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`pronto`](https://bioconda.github.io/recipes/pronto/README.html): **0.12.2** &rarr; **1.0.0**

[install with bioconda](http://bioconda.github.io/recipes/pronto/README.html) [Conda](https://anaconda.org/bioconda/pronto/files)

Info | Link
-----|-----
Recipe | [`recipes/pronto`](https://github.com//bioconda/bioconda-recipes/tree/bump/pronto/recipes/pronto) (click to view/edit other files)
Releases |[https://pypi.org/pypi/pronto/json](https://pypi.org/pypi/pronto/json)

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by dpryan79** [comment]
Needs:

 - nanoset=0.1.2
 - fastobo=0.6

**Comment by dpryan79** [comment]
fastobo is now available on Linux

**Comment by althonos** [comment]
@dpryan79 : `nanoset` is an optional dependency (where `fastobo` is a hard one) so, now the recipe can probably be updated safely.

**Comment by dpryan79** [comment]
We need to add contexter to conda-forge

**Pull request closed without merging**
