### PR TITLE
Update graphmap to v0.5.1

### PR DESCRIPTION
**Pull request by kyleabeauchamp**
* [ ] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

FYI: the version release info was inferred from the README.md and changelog (https://github.com/isovic/graphmap), consistent with the previous author of this recipe (i.e., downloading from a github tarball from a commit ID).

### CODE REVIEW

**Comment by druvus** [comment]
@kyleabeauchamp Graphmap is bumped to latest version 0.5.2 in #4691 so I am closing this PR.

**Comment by kyleabeauchamp** [comment]
Are you sure that's the latest?  Seems like there's 0.5.2 now:

https://github.com/isovic/graphmap

**Comment by kyleabeauchamp** [comment]
Looks like it was release while we were getting the last version working ;)

**Comment by druvus** [comment]
Bumped the version in my PR and it worked for 0.5.2 so it is in bioconda now. Just need to remove or rename the old 0.22 version. 

@bgruening could you remove graphmap 0.22 version? We could add it back later as 0.2.2 if someone needs it.

**Pull request closed without merging**
