### PR TITLE
Fix vcftools

### PR DESCRIPTION
**Pull request by kyleabeauchamp**
Sorry about that, previous recipe uploaded an *empty* tarball...

### CODE REVIEW

**Comment by kyleabeauchamp** [comment]
This is working for the C++ executables, but there are still some issues with PERL5LIB that will need to be sorted out for the perl scripts.  Sorry for the headache on this one.

**Comment by kyleabeauchamp** [comment]
@chapmanb  I'll let you help decide how we manage this.  All we really need to do is copy the 3 perl modules into the PERL path.  I suppose we could do it manually, or we could pull in some of the stuff from your recipe.  Longer term, I suppose that means we ought to merge the two recipes.

**Comment by chapmanb** [comment]
Kyle;
Can you depend on `perl-vcftools-vcf` from this install? That would prevent having to mess around with PERL5LIB, which was my intent with having a separate clean Perl install of the modules. Sorry I don't really understand all the vcfutils install headaches in depth since we swapped over to bcftools a while back.

**Comment by kyleabeauchamp** [comment]
I would be happy to do that but IMHO we ought to fix a few things in your upstream perl-vcftools-vcf github repo:

1.  Upgrade to latest version of vcftools
2.  Figure out a way to use the vcftools release tarballs rather copying in the perl modules directly in the source tree.

In particular, I think 2 will help us both in terms of maintainability.

**Comment by kyleabeauchamp** [comment]
We might even be able to copy the perl installer from https://github.com/chapmanb/vcftools-cpan/blob/master/Build.PL into the conda recipe directory, making it so you don't need a separate repo.

**Comment by chapmanb** [comment]
Kyle -- sounds good, I'll update the formula to work directly off the latest release download. It doesn't look like anything changed in the perl modules but I agree it's a cleaner way to go moving forward.

**Comment by chapmanb** [comment]
Thanks again, this should be good to go now. I didn't bump versioning of the perl libraries since that's separately versioned and didn't change between the releases, but we now have a more clean process in place for any future changes.

**Pull request merged**
