### PR TITLE
Update medaka to 1.2.5

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`medaka`](https://bioconda.github.io/recipes/medaka/README.html): **1.2.3** &rarr; **1.2.5**

[install with bioconda](http://bioconda.github.io/recipes/medaka/README.html) [Conda](https://anaconda.org/bioconda/medaka/files)

Info | Link
-----|-----
Recipe | [`recipes/medaka`](https://github.com//bioconda/bioconda-recipes/tree/bump/medaka/recipes/medaka) (click to view/edit other files)
Releases |[https://pypi.org/pypi/medaka/json](https://pypi.org/pypi/medaka/json)
Recipe Maintainer(s) | @cjw85

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by cjw85** [comment]
@bgruening Same question as before....can you offer any insight into why capping numpy to <1.20 would cause this chain of dependencies fails?

**Comment by cjw85** [comment]
https://github.com/bioconda/bioconda-recipes/issues/26684

**Comment by cjw85** [comment]
@bioconda/core Does anyone understand why this build is failing?

**Comment by dpryan79** [comment]
My presumption is that one of the run-time dependencies is linked against numpy >=1.20 for some reason (it's surprisingly easy to accidentally do this for C-based python programs).

**Comment by cjw85** [comment]
I can create the environment on my development machine if python is restricted to 3.8, both 3.7 and 3.9 give a mess of dependency conflicts.

**Comment by dpryan79** [comment]
That might be the issue then, hopefully your changes just now will fix things.

**Review by cjw85 — APPROVED** [review]

**Comment by cjw85** [comment]
@bioconda-bot please fetch artifacts

**Pull request merged**
