### PR TITLE
add umitools

### PR DESCRIPTION
**Pull request by kepbod**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by bgruening** [comment]
@kepbod do you know this one? https://github.com/bioconda/bioconda-recipes/blob/master/recipes/umi_tools/meta.yaml

I foresee confused users for both packages :(

**Comment by kepbod** [comment]
I don't know umi_tools. umitools is a different one. Do I need to rename it?

**Comment by yfu** [comment]
Hi Björn,

I am the owner of umitools and I can confirm that my umitools is different from umi_tools.

Thanks!

**Comment by bgruening** [comment]
@kepbod @yfu I know. I'm just wondering if we should choose a prefix or something to distinguish both tools better. I fear that people easily install the wrong tool.

**Comment by kepbod** [comment]
@bgruening Do you have some suggestions? In PyPI, [umitools](https://pypi.python.org/pypi/umitools/0.3.0) and [umi_tools](https://pypi.python.org/pypi/umi_tools/0.5.3) both exist. It would make people more confusing if we rename them with a new name inconsistent with the name in PyPI.

**Comment by bgruening** [comment]
No good idea here, sorry. Both projects are just too similar with the (nearly) same name. @yfu any change you rename the entire project? I have seen it is quite young? This is also just a recommendation, we don't have a strict guideline for this. My feeling is just, that also your users could be confused if they install the wrong version.

**Comment by cbrueffer** [comment]
I agree the naming similarity is very unfortunate, but both projects seem to be well established by now (and both were started quite a while ago)...

**Comment by cbrueffer** [comment]
I'd like to get this in, If no one sees a striking reason not to. The naming issue is unfortunate, but I think that's something for the upstream projects to sort out.

**Comment by bgruening** [comment]
Ok :)

**Pull request merged**
