### PR TITLE
[ci skip] Added biotools identifiers

### PR DESCRIPTION
**Pull request by ArneKr**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [ ] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

This pull request adds annotations for almost all packages that are both on bioconda and bio.tools

### CODE REVIEW

**Comment by ArneKr** [comment]
@bgruening Can you see what's wrong here?

**Comment by bgruening** [comment]
@ArneKr from my side this is ready. The linting still fails because of stricter linting on our site that is unrelated to this PR. I have ask in gitter for more reviewers, let keep it open for a day or so.

**Comment by bgruening** [comment]
@bioconda/core can we merge this?

**Comment by daler** [comment]
I'm good with merging this. It's been on my list for a while now to go back and fix all those recipes failing lint checks. Thanks @bgruening and @ArneKr!

**Comment by bgruening** [comment]
Thanks all! Thats an amazing process :)

**Comment by epruesse** [comment]
Thank you all! :)

**Pull request merged**
