### PR TITLE
Update cyvcf2 to 0.20.3

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`cyvcf2`](https://bioconda.github.io/recipes/cyvcf2/README.html): **0.20.1** &rarr; **0.20.3**

[install with bioconda](http://bioconda.github.io/recipes/cyvcf2/README.html) [Conda](https://anaconda.org/bioconda/cyvcf2/files)

Info | Link
-----|-----
Recipe | [`recipes/cyvcf2`](https://github.com//bioconda/bioconda-recipes/tree/bump/cyvcf2/recipes/cyvcf2) (click to view/edit other files)
Releases |[https://github.com/brentp/cyvcf2/tags](https://github.com/brentp/cyvcf2/tags)
Author | @brentp
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by simonbray** [comment]
failing because of https://github.com/brentp/cyvcf2/commit/d752b3429a702d854f4bf84666af5a60f8095153#r41200560

**Comment by brentp** [comment]
yeah. working on 0.20.3 now.

**Comment by brentp** [comment]
I killed 0.20.2 and pushed 0.20.3

**Comment by simonbray** [comment]
@BiocondaBot please merge

**Pull request merged**
