### PR TITLE
picard: add linux-aarch64 build

### PR DESCRIPTION
**Pull request by martin-g**
Describe your pull request here

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

### General instructions

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

### Instructions for avoiding API, ABI, and CLI breakage issues
Conda is able to record and lock (a.k.a. pin) dependency versions used at build time of other recipes.
This way, one can avoid that expectations of a downstream recipe with regards to API, ABI, or CLI are violated by later changes in the recipe.
If not already present in the meta.yaml, make sure to specify `run_exports` (see [here](https://bioconda.github.io/contributor/linting.html#missing-run-exports) for the rationale and comprehensive explanation).
Add a `run_exports` section like this:

```yaml
build:
  run_exports:
    - ...

```

with `...` being one of:

| Case                             | run_exports statement                                               |
| -------------------------------- | ------------------------------------------------------------------- |
| semantic versioning              | `{{ pin_subpackage("myrecipe", max_pin="x") }}`     |
| semantic versioning (0.x.x)      | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}`   |
| known breakage in minor versions | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| known breakage in patch versions | `{{ pin_subpackage("myrecipe", max_pin="x.x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| calendar versioning              | `{{ pin_subpackage("myrecipe", max_pin=None) }}`    |

while replacing `"myrecipe"` with either `name` if a `name|lower` variable is defined in your recipe or with the lowercase name of the package in quotes.

### Bot commands for PR management

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

Note that the <code>@BiocondaBot please merge</code> command is now depreciated. Please just squash and merge instead.

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by jmarshall** [comment]
Picard is `noarch`.

**Comment by martin-g** [comment]
I also thought there is no point in building `noarch` recipes for `linux-aarch64` until I reviewed https://github.com/bioconda/bioconda-recipes/pull/46337
It shows that a `noarch` may fail to build or run because of issue with dependencies.

@daler What do you think ?

**Comment by jmarshall** [comment]
@martin-g: You'll need to explain what problem you have in mind. If you mean that a noarch package may fail due to a dependency that is non-noarch and not yet built for linux-aarch64, then that would surely be a problem with that dependency — and indeed there is surely nothing that the noarch package can do about it.

In the case of picard, the package depends on openjdk and r-base, both of which are available for linux-aarch64 from conda-forge. Installing the existing noarch picard-3.1.1 package works fine for me on an ARM64 Debian VM, as expected.

**Comment by martin-g** [comment]
@jmarshall I see `noarch + extra>additional-platforms>linux-aarch64` as a CI only! It still builds a `noarch` package as before! It just validates that everything is as expected (by building and testing it at CircleCI).
Most of the recipes will just pass successfully and we can work on the ones that fail due to a dependency.

**Comment by jmarshall** [comment]
So you mean this would be a way of detecting such problems (for noarch packages).

:shrug: Bioconda's build infrastructure has not done this to date. For example here is the log from this PR's test_osx CI job:

```
12:22:47 BIOCONDA INFO FILTER: only building recipes/picard on linux because it defines noarch.
12:22:47 BIOCONDA INFO Nothing to be done for recipe recipes/picard
```

Personally I would just see this as a waste of cycles and source of confusion. I would expect in the fullness of time only one platform would attempt to build a noarch package file (as was the case before linux-aarch64 was added); if both linux-x86_64 and linux-aarch64 do at present, I would call that a bug.

----

As an alternative to editing a recipe, committing it, raising a PR, and waiting for CI, I suppose one could just try `conda install picard` on a linux-aarch64 host…

**Comment by martin-g** [comment]
> editing a recipe, committing it, raising a PR, and waiting for CI

Agreed! But this is one time only. The benefit is that new versions will be tested in the future.

I am not strong on my opinion! 
Actually I commented on several linux-aarch64 PRs that there is no need of them for `noarch` packages! Until I checked the problem for https://github.com/bioconda/bioconda-recipes/pull/46337 and then I changed my mind.

**Pull request closed without merging**
