### PR TITLE
Software from ISMB 2016

### PR DESCRIPTION
**Pull request by johanneskoester**
* [x] I have read the guidelines above.
* [x] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

Greetings from the ISMB-2016 @bioconda/all.
Today, I went through all open access papers in the proceedings of the ISMB 2016 and determined if they provide mature, installable software packages. If that was the case, I have created a bioconda package. I have to say that the results are rather disappointing. From 47 publications, only 4 can go directly into Bioconda. For the rest:

status | count
-------- | --------
pubs without software implementation | 7
based on the non-free MATLAB | 4
either unclear, no, or errorneous installation instructions | 3
invalid links | 4
without any download link | 1
collections of scripts without proper installer | 12
R packages that are not yet in CRAN or Bioc | 3
docker container | 1
demo only although the README promises a release before the ISMB | 1
available only upon request | 2
already available in bioconda | 2
web service | 4
build error | 1

Of course, R packages that are not yet in Bioconductor or CRAN could still be packaged (and will eventually). Also, the scripts can be packaged, although I would like to see people think about the user and provide installable software right away. Also, web services or docker images are not criticized here. The disappointment rather stems from the rest.
And here the details:

publication	|	status	|	bioconda
------------- | ----------------- | -----------------
Agostinelli et al.	|	web service	|	-
Yuan et al.	|	web service	|	-
Brougard et al.	|	no software	|	-
He et al.	|	no software	|	-
Deng et al.	|	scripts	|	-
Kraus et al.	|	available upon request	|	-
Haydarlou et al.	|	scripts	|	-
Peng et al.	|	available upon request	|	-
Schissler et al.	|	scripts	|	-
Zitnik et al.	|	ok	|	medusa-data-fusion
Glicksberg et al.	|	no software	|	-
Hu et al.	|	scripts	|	-
Zeng et al.	|	docker	|	-
Jo et al.	|	scripts	|	-
Sun et al.	|	not yet in CRAN or Bioc	|	-
Topa et al.	|	scripts	|	-
Duong et al.	|	no software	|	-
Lee et al.	|	software not available	|	-
Liu et al.	|	ok	|	debwt
Liu et al.	|	matlab	|	-
Srivastava et al.	|	already available	|	rapmap
Chikhi et al.	|	[build error](https://s3.amazonaws.com/archive.travis-ci.org/jobs/144154593/log.txt)	|	bcalm
Schaeffer et al.	|	no installation instructions	|	-
Kuleshov et al.	|	demo only	|	-
Wu	|	page not found	|	-
Garg et al.	|	already available	|	whatshap
Mohammadi et al.	|	no download found	|	-
Jain et al.	|	wrong installation instructions	|	-
Basu et al.	|	page not found	|	-
Mazza et al.	|	page not found	|	-
Tabei et al.	|	no software	|	-
Intosalmi	|	matlab	|	-
Szczurek et al.	|	not yet in CRAN or Bioc	|	-
Farrel et al.	|	no software	|	-
Jamroz et al.	|	scripts	|	-
Wang et al.	|	no software	|	-
Cui et al.	|	page not found	|	-
Meng et al.	|	web service	|	-
Orenstein et al.	|	unclear installation instructions	|	-
Garcia-Martin et al.	|	web service	|	-
Tsuchiya et al.	|	no proper installer	|	-
Cui et al.	|	not yet in CRAN or Bioc	|	-
Kahles et al.	|	scripts	|	-
Jain et al.	|	scripts	|	-
Wagner et al.	|	no proper installer	|	-
Wang et al.	|	no proper installer	|	-
Droop	|	ok	|	fqtools
Jostins et al.	|	ok	|	trinculo

### CODE REVIEW

**Comment by marcelm** [comment]
I’m impressed; thanks for doing this! (Not so impressed by the tools that are not made to be used, of course.)

**Comment by bgruening** [comment]
Thanks for collecting these and kudos to those 5!
I will call this the hall of shame of ISMB16. ISMB should learn from BOSC and only accept proceedings that are Open Source and accessible.

We as bioconda project should think about dropping packages like GATK and not give them a stage, imho.

**Comment by jerowe** [comment]
I'm really enjoying this conversation. I deal with this nonsense all. the. time. How does software get published that doesn't even make?

In defense of the ones that are just a collection of scripts, if they are perl or python its fairly easy to just throw them into the package convention and have conda build them that way. That's what I've been doing for these sorts of software.

I think webservers should have to have a configuration available through a service like saltstack, IMO, and there's no reason why the backend software shouldn't be released.

@bgruening , whats BOSC?

**Comment by bgruening** [comment]
@jerowe https://www.open-bio.org/wiki/BOSC one of the best conference ever.
Totally agree about webservers, they also should be open sourced.

**Comment by ewels** [comment]
https://www.open-bio.org/wiki/BOSC

> The **B**ioinformatics **O**pen **S**ource **C**onference is held annually as a Special Interest Group (SIG) of the ISCB's annual ISMB conference). BOSC promotes and facilitates the open source development of bioinformatics tools and open science. The aims of the conferences are to:
>
> - Provide developers with a forum for displaying the results of their development efforts to the wider research community;
> - Provide a focused environment for developers and users to interact and share ideas about software development, open science, and practical techniques in bioinformatics;
> - Promote Open Science, with its focus on sharing data and tools, transparency, reproducibility, and data provenance;
> - Inform the research community of important developments occurring within the Open Source Bioinformatics Developer community.

**Comment by jerowe** [comment]
Yay! Reproducible Research!!!!

**Comment by daler** [comment]
Wow, thanks for going through all of those.  Sadly, those ratios sound about right for published-in-a-journal software as well.

**Comment by kyleabeauchamp** [comment]
Thanks Johannes for putting together the list!

**Comment by tomkinsc** [comment]
Nice initiative, @johanneskoester; thanks for doing this. This PR is a good example for us all—since bioconda members attend various conferences, perhaps we can form an ad hoc group for each conference and add recipes for what we can. 

For the packages dependent on Matlab, is there a chance they would work out of the box with [GNU Octave](https://www.gnu.org/software/octave/), or do they depend on proprietary MathWorks libraries?

Maybe we should have a logo available similar to the GitHub badge ( [bioconda-badge](http://bioconda.github.io) ) for groups to add to conference posters. Something like:

```
┌ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ┐                                         
                                                                    
│                         │ Reproducible research.                  
       Bioconda logo        Install the software from bioconda:     
│                         │ conda install ____________________      
                            See: bioconda.github.io                 
└ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ┘                                         
```

**Comment by johanneskoester** [comment]
@jerowe, @bgruening, I have added some clarifying sentences above. My disappointment does not stem from the scripts and the web services.

**Comment by johanneskoester** [comment]
@tomkinsc nice idea. I don't know if the matlab stuff would work with octave. I just tried to package those stuff that was straightforward, and matlab scripts are at least not straightforward. My feeling is that it is worth the effort for established software that is already widely used, but for stuff that is very new and just has appeared at a conference, it has to be really easy to install in order to justify us doing the packaging work for the authors, right?

**Comment by johanneskoester** [comment]
@tomkisc how should we provide that technically? As an SVG?

**Comment by xguse** [comment]
I think and SVG and/or EPS makes sense for the poster logos.

**Comment by tomkinsc** [comment]
A vector format like SVG would make the most sense. SVG files can even be manipulated with JavaScript, so we could have a badge generator GitHub page to fill in the package name (or leave that as an exercise to the user).

**Comment by johanneskoester** [comment]
That's great, it should be as easy as possible.

**Comment by tillea** [comment]
Thanks for the software review.  I wonder whether the Debian Med team that has assembled a lot of biological software into main Debian (see our [task biology page](https://blends.debian.org/med/tasks/bio)) would be able to help in your effort.  We can either take packaging requests via our [mailing list](https://lists.debian.org/debian-med/) or even offer training for Debian packaging in a so called [Mentoring of the Month](https://wiki.debian.org/DebianMed/MoM).  Having official Debian packages might be helpful for users of Debian, Ubuntu and other derivatives.

**Comment by ewels** [comment]
@johanneskoester @tomkinsc @xguse How's this? http://phil.ewels.co.uk/bioconda-badge/

[Source here](https://github.com/bioconda/bioconda-recipes/files/360845/poster_badge.zip). Shout if you can think of any improvements.

**Comment by tillea** [comment]
@bgruening : Could you please be more verbose about the issue of GATK?  I was about to package the free part for Debian.  Are refering to the "protected" part?  In this case I agree and we should really try to put some pressure.

In Debian Med we try to convince some upstreams about freeing their source code.  We had some interesting success in the past but we are sometimes fighting with beeing ignored by the authors who simply do not reply or if they reply it shows that some parties would like to free the source but do not seem to have the power to do so.  One example is [Tandem Repeat Finder](https://lists.debian.org/debian-med/2016/06/msg00093.html).  Any common effort between bioconda and Debian Med would be interesting.

**Comment by jerowe** [comment]
I don't think anyone should ever encourage users to install system packages as software. It ALWAYS ends in tears, and it defeats the whole point of conda environments.

Get your users to use something like [Easybuild](https://easybuild.readthedocs.io/en/latest/). Its extremely user friendly and I've been able to get users with very little computational experience comfortable with it in a very short time. I'm working on a PR for anaconda and conda environment modules. I'm told they will release around Sept 2016.

Please, for the love all that is good in the world, don't have your users install R/Perl/Python/GATK/whatever as system packages.

**Comment by tillea** [comment]
@jerowe:  There are examples where people were very happy about having packaged software (even upstreams who explicitly ask us to package their code).  So your "ALWAYS ends in tears" has at least one (definitely more) counter examples and thus is proven wrong.
Could you please at least give a single example where users ended up in tears to enable us to do things better.
Thanks, Andreas.

**Comment by bgruening** [comment]
@ewels love it! Can you add a "-c bioconda" otherwise it will not work out of the box.

**Comment by jerowe** [comment]
@tillea, apologies, I think I came off to strong. If the users you're interacting with are happy, then I really think that's great. 

Personally, I haven't seen it happen, but it may be due to the computational experience of the users. At some point someone ends up messing with their system perl/python/java, and it ends up breaking their system, or they have lots of  broken dependencies. I have never personally interacted with DebianMed, and it may have a way of making sure things don't break, or be better maintained than some of the other ones I've interacted with. The joy of modules is that you just delete the folder of the broken software and we can all move on with their lives.

Also, some of it comes down to personal preference. I spend a lot of time getting users ready to run their analyses on HPC systems, and they have trouble moving from an 'apt-get install'  to a 'modules' mode of thinking. Of course if you're in an environment where users are running things from a server or from their own workstations, this could be very very different. 

I will certainly look into DebianMed. I'm sure its an interesting project! And really, apologies for the way I came across, it was too stong. I do that sometimes. ;-)

**Comment by bgruening** [comment]
@tillea;
Hi Andreas! Nice to see you here! I'm definitely open to improve things and push upstream to Open Source things. We did that several times, even with success :) In case of GATK it is different (and yes I'm only talking about the non-free part). I tried it over several month and also made friends inside of Broad, but it failed for political reasons.

Do you think it is possible to write an automatic conda-dpkg conversion script? I guess the package-name mapping is the crucial part but if this is solved we should at least have a nice scaffold.

Another idea would be to integrate a conda-bridge in apt-get. Let's say if the package is not available via debian-med you are automatically ask if you would like to install a conda package in user-space.

Thanks!
Bjoern

**Comment by ewels** [comment]
@bgruening - good thinking! I've made a new issue (#1971) to avoid mixing up different conversations in this thread.

**Comment by tillea** [comment]
@jerowe: No need to apologize - I did not took it personally. :-)  I'm aware that there are limits in packaging when users might require certain versions and so modules is a better solution.  However, if it comes to package dependencies and testing the packaging has heavy advantages.  Please think of BioPython (we are working closely together with upstream): Since I've provided automatic testing to the package which involves a lot of other tools we found incompatibilities and problems which were very helpful to upstream and in the end to our users.  We have currently a GSoC project for continuous integration support of biological packages.  So every day our packages are installed on a clean box, run with some test data and need to proof that they are working.  I doubt these kind of things are happening on manual installations.
But its good that we brought up this topic here. :-)

**Comment by tillea** [comment]
@bgruening:  Sad to hear about political problems.  If there are some public records of your try we might step in from another angle.
Regarding the automatic conda-dpkg conversion script:  I need to admit that I know to less about conda currently (I just became aware about it since Michael Crusoe posted a link to this discussion) to give a final answer.  In general I doubt that automatic packaging is a sensible solution.  The point is that each package needs some manual crafting to get the full power (like for instance the automatic testing feature I mentioned above).  Having something named xyz.deb and having a real package from the Debian mirror that gets the full QA support is something different.  So I think it is better to decide what are the important pieces and start with these correctly in a manual way and move on with the not so important things.
So you later suggestion of a "conda-bridge" sounds more feasible to me.
Kind regards
     Andreas.

**Comment by bgruening** [comment]
@tillea no private email conversation with the community manager of GATK.
I don't see this conversation idea so pessimistic as you do. Conda packages also include testing and can be very elaborated, so this should not be a show-stopper. Happy to tell you more about conda packaging if you are interested.

**Comment by tillea** [comment]
@bgruening: Would you mind to give an introduction about conda packaging to debian-med@lists.debian.org ?

**Comment by bgruening** [comment]
@tillea you mean a written introduction? Not sure if this can be better than the official documentation: http://conda.pydata.org/docs/building/build.html
But if you have concrete ideas I can work on this.

**Pull request merged**
