### PR TITLE
bump salmon to v0.13.1

### PR DESCRIPTION
**Pull request by rob-p**
:information_source:
Bioconda has finished the [GCC7 migration](https://github.com/bioconda/bioconda-recipes/issues/13578). If you are dealing with C/C++ or Python package it can be that you need to rebuild other dependent packages. [Bioconda utils - update-pinning](https://bioconda.github.io/updating.html#updating-recipes-for-a-pinning-change) will assist you with that. If you have any questions please use [issue 13578](https://github.com/bioconda/bioconda-recipes/issues/13578).

----------------

* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [X] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [X] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by rob-p** [comment]
Hi, @bioconda/core --- any idea why the bioconda-tests all seem to pass (including macos), but it sitting here hanging on "ci/circleci:test-macos" ?  Are these different tests?  Under bioconda-test the build passed linux, macos, and lint.

**Comment by dpryan79** [comment]
That's quite odd, I'm retriggering the tests.

**Comment by dpryan79** [comment]
It seems like the webhooks are somehow messed up. I'm not sure if that's because something needs to be updated on your fork (you can instead create branches here) or if somehow a setting got changed on our side. Either way, I'm temporarily enabling myself to merge this, since obviously the CI tests all actually passed. We'll have to keep an eye on up-coming PRs to see if this is a fluke or whether we need to look more into the CI settings.

**Comment by rob-p** [comment]
Thanks @dpryan79.  Unfortunately, the compiled binaries (that passed all tests on circle ci) seem borked on a local install.  Any idea why?

**Comment by dpryan79** [comment]
@rob-p Can you give an example of the borked behavior?

**Comment by rob-p** [comment]
Yup, straight up segfault on the same dataset that runs on the ci-server.  Tagging @k3yavi who can provide the gdb backtrace.

**Comment by k3yavi** [comment]
Not sure how helpful it's gonna be but I get the following backtrace on gdb with the conda installed binary:

```
Thread 1 "salmon" received signal SIGSEGV, Segmentation fault.
0x0000555555a5690a in tcache_dalloc_large (slow_path=false, binind=0, ptr=0x7ffff514bfc0, tcache=<optimized out>, tsd=<optimized out>)
    at include/jemalloc/internal/tcache_inlines.h:203
203     include/jemalloc/internal/tcache_inlines.h: No such file or directory.
```

**Comment by dpryan79** [comment]
Have you run things in valgrind? What version of jemalloc are you using in your CI testing?

**Comment by rob-p** [comment]
I've checked with address and undefined behavior sanatizer, and it's clean. We use jemalloc 5.1.0 in our CI.  Our bioconda build doesn't pin, so not sure what it is using.

**Comment by dpryan79** [comment]
It's using 5.1.0 as well (it's the only version that's been rebuilt for the new compilers). If you can provide a command to reproduce this (I can use files in the salmon github repo) then I can more easily have a look.

**Comment by rob-p** [comment]
Sure!  @k3yavi, can you give the command that segfaults on the sample data?  Also, @dpryan79, you can find our precompiled linux executable in our repo as well, that's built on an old centOS.

**Comment by k3yavi** [comment]
Yes, thanks @dpryan79 for looking into it. You might have to use the sample_data from [here](https://github.com/COMBINE-lab/salmon/blob/develop/sample_data.tgz). It seems both indexing and quant commands of salmon are segfaulting.

Indexing:
```
<SALMON_BIN> index -t sample_data/transcripts.fasta -i <INDEX_FOLDER>
```

Quant:
```
<SALMON_BIN> -la -1 sample_data/reads_1.fastq -2 sample_data/reads_2.fastq -i <INDEX_FOLDER> -o <OUTPUT_FOLDER>
```

**Comment by dpryan79** [comment]
Hmm, it doesn't segfault for me when I try that (I assume the last command is should use `quant`). Can you create a clean env (`conda create -n borkborkbork salmon`) and confirm that the segfault still happens?

**Comment by k3yavi** [comment]
You are right about adding the `quant`, sorry i missed that.
I can confirm I still have the issue:
My log with the new environment were
```
## Package Plan ##

  environment location: /home/avi/miniconda3/envs/borkborkbork

  added / updated specs:
    - salmon


The following NEW packages will be INSTALLED:

  bzip2              conda-forge/linux-64::bzip2-1.0.6-h14c3975_1002
  icu                conda-forge/linux-64::icu-58.2-hf484d3e_1000
  jemalloc           conda-forge/linux-64::jemalloc-5.1.0-hf484d3e_1000
  libboost           pkgs/main/linux-64::libboost-1.67.0-h46d08c1_4
  libgcc-ng          conda-forge/linux-64::libgcc-ng-7.3.0-hdf63c60_0
  libstdcxx-ng       conda-forge/linux-64::libstdcxx-ng-7.3.0-hdf63c60_0                                                                                                               salmon             bioconda/linux-64::salmon-0.13.1-h86b0361_0
  tbb                conda-forge/linux-64::tbb-2019.4-h6bb024c_0
  xz                 conda-forge/linux-64::xz-5.2.4-h14c3975_1001
  zlib               conda-forge/linux-64::zlib-1.2.11-h14c3975_1004

Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate borkborkbork
#
# To deactivate an active environment, use
#
#     $ conda deactivate
```

**Comment by dpryan79** [comment]
Not sure why it's segfaulting for you, it's not for me using the same data.

**Comment by rob-p** [comment]
Hrmm ... very strange (exactly the kind of thing conda should avoid ;P).  Are we sure we are all getting the latest version (0.13.1)?

**Comment by dpryan79** [comment]
$ salmon -v
    salmon 0.13.1

**Comment by dpryan79** [comment]
Can you make a PR where these commands are added to the tests? That'd conveniently test in a clean environment.

**Comment by rob-p** [comment]
Hi @dpryan79,

  The tests on install already do this.  Specifically, we run `make test` (https://github.com/rob-p/bioconda-recipes/blob/71aa9b20fa2ecb78612046c95fe9cabe6ef5dd7d/recipes/salmon/build.sh#L58).  That, in turn, runs this (https://github.com/COMBINE-lab/salmon/blob/master/cmake/TestSalmonQuasi.cmake) --- exactly the commands in question.  The mystery deepens ...

**Comment by dpryan79** [comment]
Is this happening for both of you?

**Comment by rob-p** [comment]
Yes, but we are on the same server ... so not completely independent validation.

**Comment by bgruening** [comment]
@rob-p can you make sure that no global jemalloc is leaking into the env?

**Comment by dpryan79** [comment]
Can you try on a desktop or laptop? Obviously it shouldn't matter, but there may be some odd environment variable set that's causing the wrong libraries to get pulled in.

**Comment by rob-p** [comment]
Hi @bgruening and @dpryan79 --- thanks for the advice so far!  So it works on @k3yavi's laptop (OSX) and on our other (older) linux server.  Any way to check the environment for suspicious leakage?

**Comment by k3yavi** [comment]
Thanks @dpryan79 for all your help. I tried the commands on my personal Mac and one another linux box, as you said, it seems to work. Although I am still curious what's wrong with the one we were testing on, we will update you if we get down to the problem. Thanks again.

**Comment by dpryan79** [comment]
Do you have an LD_PRELOAD set or something? What does `ldd -r salmon` (you'll have to give the full path) say?

**Comment by k3yavi** [comment]
`LD_PRELOAD` seems to be empty and 
```
╰─$ ldd -r /home/avi/miniconda3/envs/borkborkbork/bin/salmon
        linux-vdso.so.1 =>  (0x00007ffec8b81000)
        libtbbmalloc_proxy.so.2 => /home/avi/miniconda3/envs/borkborkbork/bin/../lib/libtbbmalloc_proxy.so.2 (0x00007f3858a12000)
        libtbb.so.2 => /home/avi/miniconda3/envs/borkborkbork/bin/../lib/libtbb.so.2 (0x00007f38589d0000)
        libgomp.so.1 => /home/avi/miniconda3/envs/borkborkbork/bin/../lib/libgomp.so.1 (0x00007f38589ab000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f3858794000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f385858e000)
        libstdc++.so.6 => /home/avi/miniconda3/envs/borkborkbork/bin/../lib/libstdc++.so.6 (0x00007f385844c000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f3858143000)
        libgcc_s.so.1 => /home/avi/miniconda3/envs/borkborkbork/bin/../lib/libgcc_s.so.1 (0x00007f385812f000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f3857f11000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f3857b4a000)
        /lib64/ld-linux-x86-64.so.2 (0x0000556cde4bc000)
        libtbbmalloc.so.2 => /home/avi/miniconda3/envs/borkborkbork/bin/../lib/./libtbbmalloc.so.2 (0x00007f3857b07000)
```

**Comment by rob-p** [comment]
I get this:

```
(base) rob@newton:~/salmon$ ldd -r `which salmon`
        linux-vdso.so.1 =>  (0x00007ffe63465000)
        libtbbmalloc_proxy.so.2 => /home/rob/miniconda3/bin/../lib/libtbbmalloc_proxy.so.2 (0x00007f27784cc000)
        libtbb.so.2 => /home/rob/miniconda3/bin/../lib/libtbb.so.2 (0x00007f277848a000)
        libgomp.so.1 => /home/rob/miniconda3/bin/../lib/libgomp.so.1 (0x00007f2778464000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f277824d000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f2778047000)
        libstdc++.so.6 => /home/rob/miniconda3/bin/../lib/libstdc++.so.6 (0x00007f2777f06000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f2777bfd000)
        libgcc_s.so.1 => /home/rob/miniconda3/bin/../lib/libgcc_s.so.1 (0x00007f2777be8000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f27779ca000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f2777603000)
        /lib64/ld-linux-x86-64.so.2 (0x000055f9f7366000)
        libtbbmalloc.so.2 => /home/rob/miniconda3/bin/../lib/./libtbbmalloc.so.2 (0x00007f27775c0000)
```

I don't have any `LD_PRELOAD` set either.

**Comment by dpryan79** [comment]
No clue then :(

**Comment by epruesse** [comment]
Tried it locally on my box - no segfault.

**Comment by epruesse** [comment]
Why is salmon using jemalloc while linked to tbbmalloc?

**Comment by bgruening** [comment]
No segfault for me as well :(

**Comment by rob-p** [comment]
It's funny to see `No segfault` paired with a :(.  Thanks to you all for checking it out on your boxes.  I have no idea what could cause it to be failing on our server.

**Comment by epruesse** [comment]
Note on the side - `lib/libsalmon_core.a` can probably be removed from the package - or should be moved to `salmon-dev` - it's not necessary for the binary use case.

**Comment by epruesse** [comment]
But you can still reproduce this? And only with the bioconda build, but not with a local build?

**Comment by epruesse** [comment]
Ok, so jemalloc is linked into salmon statically. That means it doesn't need to depend on jemalloc at run time. I still don't get why it would use both jemalloc and tbbmalloc - that doesn't sound like it's going to improve performance.

**Comment by rob-p** [comment]
Yes, we can reproduce this on _one_ of our servers (not the other), and only using the biconda build.  Both the native build from source and the build using our CI infrastructure run to completion on this data without issue.

**Comment by epruesse** [comment]
What is different between the boxes? What happens if you run it on the servers inside of a docker?

**Comment by epruesse** [comment]
Can you provide full `bt`? The fact that it *appears* to segfault in `tcache_dalloc_large` doesn't help much. It's compiled with optimization, so the location will be off by a few instructions at least. Plus, it's going to call that function a great many times (like every time it allocates stuff).

If I had to hazard a guess, I'd say you've got too little memory in that machine. Segfaults in the vicinity of an allocation are most often caused by client code just assuming it will get more memory. You could also run `strace salmon ...` on a linux box, and check for suspicious system calls just before the segfault - if there was an attempt to `mmap` resulting in `ENOMEM` we know what's causing it...

**Comment by rob-p** [comment]
@k3yavi --- is there any more backtrace here?

**Comment by k3yavi** [comment]
Nope that was the full backtrace.

**Comment by epruesse** [comment]
Run 
```
gdb --args salmon index -t sample_data/transcripts.fasta -i index
```

Then 
```
run
```

Upon crash, call
```
bt
```

**Comment by rob-p** [comment]
I am afk for a little bit but will try within docker on the offending box if @k3yavi doesn't get to it first.

**Comment by k3yavi** [comment]
I get the following backtrace.

```
(gdb) bt
#0  0x0000555555a5690a in tcache_dalloc_large (slow_path=false, binind=0,
    ptr=0x7ffff514bfc0, tcache=<optimized out>, tsd=<optimized out>)
    at include/jemalloc/internal/tcache_inlines.h:203
#1  arena_dalloc (slow_path=false, alloc_ctx=<synthetic pointer>,
    tcache=<optimized out>, ptr=0x7ffff514bfc0, tsdn=<optimized out>)
    at include/jemalloc/internal/arena_inlines_b.h:232
#2  idalloctm (slow_path=false, is_internal=false, alloc_ctx=<synthetic pointer>,
    tcache=<optimized out>, ptr=0x7ffff514bfc0, tsdn=<optimized out>)
    at include/jemalloc/internal/jemalloc_internal_inlines_c.h:118
#3  ifree (slow_path=false, tcache=<optimized out>, ptr=0x7ffff514bfc0,
    tsd=0x7ffff7e197b0) at src/jemalloc.c:2222
#4  free (ptr=0x7ffff514bfc0) at src/jemalloc.c:2393
#5  0x00007ffff74abccb in get_cached_stack (memp=<synthetic pointer>,
    sizep=<synthetic pointer>) at allocatestack.c:250
#6  allocate_stack (stack=<synthetic pointer>, pdp=<synthetic pointer>,
    attr=0x7fffffffc480) at allocatestack.c:499
#7  __pthread_create_2_1 (newthread=0x7ffff6c080f8, attr=0x0,
    start_routine=0x7ffff7eed438 <std::execute_native_thread_routine(void*)>,
    arg=0x7ffff6c09cc0) at pthread_create.c:539
#8  0x00007ffff7eed5eb in __gthread_create (__args=<optimized out>,
---Type <return> to continue, or q <return> to quit---
    <std::execute_native_thread_routine(void*)>, __threadid=<optimized out>)
    at /home/rdonnelly/mc/conda-bld/compilers_linux-64_1534627447954/work/.build/x86_64-conda_cos6-linux-gnu/build/build-cc-gcc-final/x86_64-conda_cos6-linux-gnu/libstdc++-v3/include/x86_64-conda_cos6-linux-gnu/bits/gthr-default.h:675
#9  std::thread::_M_start_thread (this=<optimized out>, state=...)
    at /home/rdonnelly/mc/conda-bld/compilers_linux-64_1534627447954/work/.build/x86_64-conda_cos6-linux-gnu/src/gcc/libstdc++-v3/src/c++11/thread.cc:163
#10 0x00005555558c8971 in fastx_parser::FastxParser<fastx_parser::ReadSeq>::start() ()
#11 0x000055555559c831 in rapMapSAIndex(int, char**) ()
#12 0x0000555555691ae6 in SalmonIndex::buildQuasiIndex_(boost::filesystem::path, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, unsigned int) ()
#13 0x000055555568cc65 in salmonIndex(int, char const**) ()
#14 0x000055555558ecb5 in main ()
```

**Comment by k3yavi** [comment]
I can confirm in the same machine, using the miniconda image and pulling salmon from conda works without segfault.

**Comment by rob-p** [comment]
What if the docker image is the same ubuntu as on the server?

**Comment by epruesse** [comment]
@rob-p - So why *do* you guys link statically to jemalloc and dynamically to tbbmalloc? Curious as to what benefit that has.

FYI - salmon does segfault for me if I run it within `valgrind`, and somewhere similar (trace isn't really helpful though). Did you try running valgrind on a build with `-ggdb3 -Og` instead of `-O2` to see if there is some kind of memory corruption going on?

In my experience, if you get segfaults in standard library (malloc etc) code, you have a bug elsewhere that clobbered memory. Throw all the linters and checkers you can find at it and hope you don't find too much else besides this issue.

**Comment by rob-p** [comment]
Thanks for the info, @epruesse.  I'll try this and report back here.  To be clear, you are suggesting running under valgrind when not using jemalloc?  I agree that if we see this behavior with system malloc, its probably our bug somewhere.  I wonder why address sanatizer thinks all is clean here (granted, that has to be run without jemalloc, so maybe that is at fault). Will also give the reason for dual linking when i am at my computer.

**Comment by rob-p** [comment]
So, the reason for linking against both libraries is that we found jemalloc to be the best general performance multithreaded allocator (accounting for both runtime and memory overhead).  However, because we make use of some TBB parallel algorithms, we *must* link against tbbmalloc.  Furthermore, I'd love to have everything link statically, but TBB does not support static linking, so we have to link against that dynamically.

**Comment by rob-p** [comment]
Hi @epruesse, 

  So, @k3yavi  and I have made some progress.  First, everything works under valgrind with system malloc, but we are able to reproduce this segfault using jemalloc.  Even more interesting, it _only_ seems to happen when the version check occurs.  That is, on the offending binary (either compiled locally with `-ggdb` and `-Og`, using jemalloc and running under valgrind, or the bioconda binary), the command:

`salmon index -t sample_data/transcripts.fasta -i sample_data/index`

fails (segfaults) but the command

`salmon --no-version-check index -t sample_data/transcripts.fasta -i sample_data/index`

works.

**Comment by epruesse** [comment]
@rob-p Re `jemalloc` - Interesting. I'll have to benchmark that with [SINA](https://github.com/epruesse/sina). Why the drive to link statically? Performance again? I've not seen much difference in SINA, but I never tested it thoroughly.

Re valgrind - exactly, just run the thing as you did. It's way slower than the various `-fsanitize` tools but I think its more thorough. Plus, it doesn't change the code. I've had a bug at some point that was actually hidden by `-fsanitize=asan`.

Sounds like the version check does something it shouldn't... Happy Hunting! :)

**Comment by epruesse** [comment]
BTW: You might want to try the `MALLOC_CONF=tcache:false` & friends options to debug with jemalloc. Also, try `--malloc-fill` and `--free-fill`, perhaps they can trigger things.

**Comment by rob-p** [comment]
@epruesse : *very* interesting.  With `MALLOC_CONF=tcache:false`, the location of the segfault (again, only happens with jemalloc) is completely different.  And, it actually happens before it enters any of the client (i.e. salmon-specific) code.

```
(base) rob@newton:~/salmon/build$ MALLOC_CONF=tcache:false valgrind --malloc-fill=0 --leak-check=full ./src/salmon index -t ../sample_data/transcripts.fasta -i ../sample_data/sample_salmon_quasi_index
==45528== Memcheck, a memory error detector
==45528== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==45528== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==45528== Command: ./src/salmon index -t ../sample_data/transcripts.fasta -i ../sample_data/sample_salmon_quasi_index
==45528==
==45528== Invalid read of size 8
==45528==    at 0x8BBCFA: atomic_load_p (atomic.h:55)
==45528==    by 0x8BBCFA: rtree_leaf_elm_bits_read (rtree.h:175)
==45528==    by 0x8BBCFA: rtree_leaf_elm_extent_read (rtree.h:214)
==45528==    by 0x8BBCFA: rtree_extent_read (rtree.h:423)
==45528==    by 0x8BBCFA: iealloc (jemalloc_internal_inlines_b.h:82)
==45528==    by 0x8BBCFA: je_arena_dalloc_small (arena.c:1574)
==45528==    by 0x51404E: boost::any::holder<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::~holder() (any.hpp:169)
==45528==    by 0x50F4DB: ~any (any.hpp:79)
==45528==    by 0x50F4DB: void boost::program_options::validate<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char>(boost::any&, std::vector<std::__cxx11::basic_string<char, s
td::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<std::__cxx11::basic_string<char, std::char_t
raits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >*, int) (value_semantic.hpp:146)
==45528==    by 0x50F764: boost::program_options::typed_value<std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::ch
ar_traits<char>, std::allocator<char> > > >, char>::xparse(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<cha
r, std::char_traits<char>, std::allocator<char> > > > const&) const (value_semantic.hpp:184)
==45528==    by 0x7EF053: boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::alloca
tor<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, bool) const (in /home/rob/salmon/build/src/salmon)
==45528==    by 0x7EAE82: boost::program_options::store(boost::program_options::basic_parsed_options<char> const&, boost::program_options::variables_map&, bool) (in /home/rob/salmon/build/src/salmon)
==45528==    by 0x503279: main (Salmon.cpp:193)
==45528==  Address 0x33ea0 is not stack'd, malloc'd or (recently) free'd
==45528==
==45528==
==45528== Process terminating with default action of signal 11 (SIGSEGV)
==45528==  Access not within mapped region at address 0x33EA0
==45528==    at 0x8BBCFA: atomic_load_p (atomic.h:55)
==45528==    by 0x8BBCFA: rtree_leaf_elm_bits_read (rtree.h:175)
==45528==    by 0x8BBCFA: rtree_leaf_elm_extent_read (rtree.h:214)
==45528==    by 0x8BBCFA: rtree_extent_read (rtree.h:423)
==45528==    by 0x8BBCFA: iealloc (jemalloc_internal_inlines_b.h:82)
==45528==    by 0x8BBCFA: je_arena_dalloc_small (arena.c:1574)
==45528==    by 0x51404E: boost::any::holder<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::~holder() (any.hpp:169)
==45528==    by 0x50F4DB: ~any (any.hpp:79)
==45528==    by 0x50F4DB: void boost::program_options::validate<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char>(boost::any&, std::vector<std::__cxx11::basic_string<char, s
td::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<std::__cxx11::basic_string<char, std::char_t
raits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >*, int) (value_semantic.hpp:146)
==45528==    by 0x50F764: boost::program_options::typed_value<std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::ch
ar_traits<char>, std::allocator<char> > > >, char>::xparse(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<cha
r, std::char_traits<char>, std::allocator<char> > > > const&) const (value_semantic.hpp:184)
==45528==    by 0x7EF053: boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::alloca
tor<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, bool) const (in /home/rob/salmon/build/src/salmon)
==45528==    by 0x7EAE82: boost::program_options::store(boost::program_options::basic_parsed_options<char> const&, boost::program_options::variables_map&, bool) (in /home/rob/salmon/build/src/salmon)
==45528==    by 0x503279: main (Salmon.cpp:193)
==45528==  If you believe this happened as a result of a stack
==45528==  overflow in your program's main thread (unlikely but
==45528==  possible), you can try to increase the size of the
==45528==  main thread stack using the --main-stacksize= flag.
==45528==  The main thread stack size used in this run was 8388608.
==45528==
==45528== HEAP SUMMARY:
==45528==     in use at exit: 88,224 bytes in 128 blocks
==45528==   total heap usage: 243 allocs, 115 frees, 130,971 bytes allocated
==45528==
==45528== LEAK SUMMARY:
==45528==    definitely lost: 0 bytes in 0 blocks
==45528==    indirectly lost: 0 bytes in 0 blocks
==45528==      possibly lost: 0 bytes in 0 blocks
==45528==    still reachable: 88,224 bytes in 128 blocks
==45528==         suppressed: 0 bytes in 0 blocks
==45528== Reachable blocks (those to which a pointer was found) are not shown.
==45528== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==45528==
==45528== For counts of detected and suppressed errors, rerun with: -v
==45528== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
Segmentation fault (core dumped)
```

So it's coming from the destructor of `boost::any`, it seems?!?

**Comment by epruesse** [comment]
We really should move this to an issue on the salmon repo. It might be that you are doing something you should't with boost program options, it might be that using both jemalloc and tbbmalloc in the same program leads to crazyness. W.r.t. the boost any / program_options part - at least it's small and right at the start, so you should be able to tinker with it until you've isolated the cause. It might be unrelated to the segfault in actual use though. Hard to tell from here.

**Comment by rob-p** [comment]
Hi @epruesse,

So, further investigation suggests that this is not actually something salmon specific.  I made a minimum working example [here](https://gist.github.com/rob-p/b32db22dfc186b30f07cd49073430424).  The build command (since I didn't put together a proper makefile yet) is:

```
g++ -std=c++14 -pthread -static-libstdc++ -ftree-vectorize -funroll-loops -fPIC -fomit-frame-pointer -Og -ggdb -I /home/linuxbrew/.linuxbrew/Cellar/boost/1.67.0_1/include -L /home/linuxbrew/.linuxbrew/Cellar/boost/1.67.0_1/lib -o test main.cpp -lboost_system-mt -lboost_thread-mt -lboost_program_options-mt -L ~/salmon/external/install/lib -ltbbmalloc ~/salmon/external/install/lib/libjemalloc.a -ldl -lrt
```

Interestingly, two things have to co-occur for the issue to happen.  First, `librt` must be linked `-lrt`.  Second, the static jemalloc must be used.  If either `-lrt` is not included or the shared jemalloc is used, then the segfault doesn't occur.

**Comment by epruesse** [comment]
I can't reproduce this - do you have an MWE for Linux using a conda-env to build?

- The linking is order dependent, symbols are resolved left to right. If you put the libs providing symbols to the left of the object that needs them, they won't be found and the linker will yield symbol not found.
- `libtbbmalloc` does not provide a `malloc` of its own, but a `scalable_malloc`, which is used by `scalable_alloator<T>` - IIRC only if present. You should actually be able to link without.
- The `malloc` etc overrides are provided by `libtbbmalloc_proxy` I believe.
- You might want to try with `-fno-builtin-malloc` (+ free, calloc, etc)
- Technically, you should not have more than one `malloc` in your final binary. But if there is inline going on, or you link a static lib and then link that into your final binary, you might mix two allocators, which might cause problems.
- There is also the `new` allocator to consider.

There are also some differences between Linux and macOS. Can you reproduce the segfault on both?

Anyway - open an issue in your own repo and ping me if you need my help. We keep sending mail to everyone else who contributed to this thread by continuing the discussion here.

**Pull request merged**
