### PR TITLE
add gcc and llvm to salmon

### PR DESCRIPTION
**Pull request by bgruening**
- [x] I have read the guidelines above.
- [ ] This PR adds a new recipe.
- [x] This PR updates an existing recipe.
- [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by bgruening** [comment]
```
/opt/conda/conda-bld/salmon_1475432655526/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/autoconf: /opt/conda/conda-bld/salmon_1475432655526/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/autom4te: /usr/bin/perl: bad interpreter: No such file or directory
```

@roryk @chapmanb any idea how we can fix this?

**Comment by roryk** [comment]
Hi Björn,

Hm-- is the perl dependency necessary?

**Comment by bgruening** [comment]
The error is complaining about `/usr/bin/perl: bad interpreter: No such file or directory` - so I think it is needed. But the real problem is that the interpreter is wrong it needs to be `/usr/bin/env perl`. Not sure where to change this.

**Comment by bgruening** [comment]
xref: https://github.com/bioconda/bioconda-recipes/issues/2166

**Comment by bgruening** [comment]
@roryk yes perl is necessary at build time for autoconf. The autoconf package should be fixed, but for the time being this should work.
Unfortunately, I got a new error which I do not understand. Maybe you can look at it :(

**Comment by acaprez** [comment]
@bgruening - I think this should essentially be done now in #3752.

**Comment by bgruening** [comment]
@acaprez thanks a bunch!!

**Pull request closed without merging**
