### PR TITLE
package PARalyzer on macOS

### PR DESCRIPTION
**Pull request by croth1**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [x] This PR does something else (explain below).

@dyusuf do you see a problem with packaging PARalyzer on macOS as well? since it's java only, it should be fine - what do you think?

### CODE REVIEW

**Comment by dyusuf** [comment]
to build a MAC pkg is always more tricky. 

I can not recall the exact issue of the OS failure while sometimes it relates to the configuration and OS infrastructure of bioconda itself.

however, the current failure of your build is not due to OS but because the recipe failed at linting which is a new controlling method introduced some time ago. for reference, https://bioconda.github.io/linting.html

**Comment by croth1** [comment]
Let's see if I can make the linter happy :)

**Comment by croth1** [comment]
Linter seems to be happy now! What do you think - can we merge this?

**Comment by bgruening** [comment]
Thanks @croth1!

**Comment by dyusuf** [comment]
@croth1 beautiful :-)

**Pull request merged**
