### PR TITLE
Update nopilesum to 1.1.2

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`nopilesum`](https://bioconda.github.io/recipes/nopilesum/README.html): **1.0.0** &rarr; **1.1.2**

[install with bioconda](http://bioconda.github.io/recipes/nopilesum/README.html) [Conda](https://anaconda.org/bioconda/nopilesum/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/nopilesum`](https://github.com//bioconda/bioconda-recipes/tree/bump/nopilesum/recipes/nopilesum) (click to view/edit other files)
Summary | nopilesum is a D program that functions as an alternative to GATK4's GetPileupSummaries.
Home | [https://github.com/blachlylab/nopilesum](https://github.com/blachlylab/nopilesum)
Releases |[https://github.com/blachlylab/nopilesum/tags](https://github.com/blachlylab/nopilesum/tags)
Author | `@blachlylab`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by dpryan79** [comment]
@BiocondaBot please fetch artifacts

**Comment by dpryan79** [comment]
@BiocondaBot please fetch artifacts

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@BiocondaBot please merge

**Comment by charlesgregory** [comment]
Not to bump an accepted PR, but thanks @dpryan79 for getting this updated!

**Pull request merged**
