### PR TITLE
Update seqfu to 1.20.2

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`seqfu`](https://bioconda.github.io/recipes/seqfu/README.html): **1.20.0** &rarr; **1.20.2**

[install with bioconda](http://bioconda.github.io/recipes/seqfu/README.html) [Conda](https://anaconda.org/bioconda/seqfu/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/seqfu`](https://github.com//bioconda/bioconda-recipes/tree/bump/seqfu/recipes/seqfu) (click to view/edit other files)
Summary | DNA sequence utilities
Home | [https://github.com/telatin/seqfu2/](https://github.com/telatin/seqfu2/)
Releases |[https://github.com/telatin/seqfu2/tags](https://github.com/telatin/seqfu2/tags)
Recipe Maintainer(s) | @telatin
Author | @telatin
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by telatin** [comment]
SeqFu now targets the last 1.x version (1.6.6) which is not available. 
Putting this on hold

**Comment by telatin** [comment]
@thanhleviet could you please add `gcc` to the recipe? thanks a million

**Comment by telatin** [comment]
There is some progress.

😄 Now Linux works

😢 But macOS doesn't yet `git hash: couldn't determine git hash`

**Comment by thanhleviet** [comment]
Looks like `nim` related issue https://github.com/nim-lang/nimble/issues/696

**Review by telatin — APPROVED** [review]

**Pull request merged**
