### PR TITLE
Update hitea to 0.1.5

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`hitea`](https://bioconda.github.io/recipes/hitea/README.html): **0.1.4** &rarr; **0.1.5**

[install with bioconda](http://bioconda.github.io/recipes/hitea/README.html) [Conda](https://anaconda.org/bioconda/hitea/files)

Info | Link
-----|-----
Recipe | [`recipes/hitea`](https://github.com//bioconda/bioconda-recipes/tree/bump/hitea/recipes/hitea) (click to view/edit other files)
Releases |[https://github.com/parklab/HiTea/tags](https://github.com/parklab/HiTea/tags)
Author | `@parklab`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by epruesse** [comment]
@dhawalsjain Are the dependencies ok?

**Comment by dhawalsjain** [comment]
@epruesse Yes. The dependencies did not change between the current and last version. Only an issue related to read-length calculation was fixed. Is there any issue?

**Comment by epruesse** [comment]
No, all fine, I was just wanting to confirm.

If you add yourself as maintainer to the recipe and join Bioconda, you would get pinged when we detect new package releases.

@BiocondaBot please merge

**Comment by bgruening** [comment]
@bioconda-bot please merge

**Pull request merged**
