### PR TITLE
Vcf sample compare version update

### PR DESCRIPTION
**Pull request by hepcat72**
Fixed a somewhat small bug in the underlying package, significant enough for a recipe update.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by hepcat72** [comment]
Oh geez. Ok. I’ll have a look. I probably submitted the wrong branch.

**Comment by hepcat72** [comment]
@bgruening Ah.  Sheesh.  It's forgotten to push my changes!  It's pushed now.

**Comment by hepcat72** [comment]
What more do I need to do for this?

**Comment by hepcat72** [comment]
Don't know why this was stuck before, but I just rebased and everything passes/completes.

**Comment by hepcat72** [comment]
Hey @bgruening, do you know if this is still on track to be merged?  Is there anything else I need to do?

**Comment by bgruening** [comment]
Sorry, just slipped through my cracks.

**Pull request merged**
