### PR TITLE
updated for new package version

### PR DESCRIPTION
**Pull request by oena**
* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [X] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [X] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by oena** [comment]
Hi @bgruening (or others)-- it seems like there's some issue with my CircleCI configuration, but I'm having trouble finding information on how to fix it (I am working on a Mac, but did not see the "stop building" button as described in the bioconda FAQs. Can you help and/or point me to more information on how I can fix this? Thanks.

**Comment by bgruening** [comment]
@oena you need to merge the upstream master branch into your branch here.
Something like `git pull upstream master` from your `cmappy_update` branch.

**Comment by oena** [comment]
Thanks @bgruening. Sorry to keep bugging you, but I now seem to be having a docker issue for the linux tests; thoughts on this? I'm not super familiar with docker so am not sure if it actually is docker-related, but from what I can tell about the error message that seems to be the case: 

`BIOCONDA ERROR COMMAND FAILED: docker run --net host --rm -v /tmp/tmpw8vg8oe5/build_script.bash:/opt/build_script.bash -v /home/circleci/project/miniconda/conda-bld:/opt/host-conda-bld -v /home/circleci/project/recipes/cmappy:/opt/recipe -e LANG=en_US.UTF-8 -e CONDA_ROOT=/home/circleci/project/miniconda -e CONDA_ALLOW_SOFTLINKS=false -e CONDA_PY=27 -e CONDA_HTSLIB=1.7 -e CONDA_BOOST=1.64 -e CONDA_R=3.4.1 -e CONDA_PERL=5.22.0 -e CONDA_NPY=112 -e CONDA_NCURSES=5.9 -e CONDA_GSL=1.16 -e CONDA_GMP=5.1 -e CONDA_HDF5=1.8.17 -e MACOSX_DEPLOYMENT_TARGET=10.9 -e CONDA_ZLIB=1.2.11 -e CONDA_BZIP2=1.0 -e CONDA_XZ=5.2 -e CONDA_BAMTOOLS=2.4.1 -e HOST_USER_ID=1001 tmp-bioconda-builder /bin/bash /opt/build_script.bash
17:35:00 BIOCONDA ERROR STDOUT+STDERR:
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell`

**Comment by bgruening** [comment]
That was just a warning the error was below this message. I guess one of your tests returned a non-zero error code because of a deprecation warning.

**Comment by oena** [comment]
Ah, gotcha. Thank you!

**Pull request merged**
