### PR TITLE
Remove r-kinship2 and r-msm and r-mess (now in CF)

### PR DESCRIPTION
**Pull request by npavlovikj**
:information_source:
If this is your first pull request to Bioconda please ping `@bioconda/core` so it can be reviewed and to request being added as a member of the Bioconda team. Members of the Bioconda team are able to merge their own pull requests once tests and linting have passed.

----------------

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [ ] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [x] This PR does something else (explain below).

Migrated r-msm and r-kinship2 to conda-forge, so the recipes are not needed here anymore.

### CODE REVIEW

**Comment by npavlovikj** [comment]
Based on the conversation in https://github.com/bioconda/bioconda-recipes/pull/14280, looks like the migrated recipes to CF are deleted from the repo, so I hope this is the right way. If not, please let me know.

**Comment by epruesse** [comment]
Yes, those can go. Thanks @npavlovikj!

The recipes at CF were created with too low build numbers though. I'm not positive that they will be preferred reliably.

@bioconda/core Do we need to bump the below in CF to ensure that the newest version is on their side?


```
r-kinship2                     1.6.4  r351h6115d3f_0  conda-forge         
r-kinship2                     1.6.4  r351h6115d3f_3  bioconda   

r-msm                          1.6.7  r351h96ca727_0  bioconda            
r-msm                          1.6.7  r351hcdcec82_0  conda-forge   

r-mess                         0.5.5  r351h0357c0b_0  conda-forge         
r-mess                         0.5.5  r351h29659fb_0  bioconda   
```

**Comment by npavlovikj** [comment]
Ah, that's a good point @epruesse ! If you decide to keep the current packages in the "bioconda" channel, I can bump up the build number in the feedstocks - just let me know.

**Comment by epruesse** [comment]
No - we had discussed this at our last meeting and decided that  there isn't really a reason to keep them. They will remain in the git history anyway, so no loss, just less clutter.

**Comment by epruesse** [comment]
I don't actually know whether they need to be bumped to be above the latest bioconda build. Let's wait a little and give people time to respond.

**Comment by npavlovikj** [comment]
Since `conda-forge` has a priority over `bioconda`, the package from `conda-forge` will be installed first, regardless of the build number:

[fedora@npavlovikj-conda defiant]$ **conda create -n r-msm r-msm**
The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    _r-mutex-1.0.0             |      anacondar_1           2 KB
    libblas-3.8.0              |       7_openblas           6 KB  conda-forge
    libcblas-3.8.0             |       7_openblas           6 KB  conda-forge
    pthread-stubs-0.4          |    h14c3975_1001           5 KB  conda-forge
    **r-msm-1.6.7                |   r351hcdcec82_0         1.4 MB  conda-forge**
    r-mvtnorm-1.0_10           |   r351h9bbef5b_0         244 KB  conda-forge
    ------------------------------------------------------------

[fedora@npavlovikj-conda defiant]$ **conda create -n r-kinship2 r-kinship2**
The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    _r-mutex-1.0.0             |      anacondar_1           2 KB
    libblas-3.8.0              |       7_openblas           6 KB  conda-forge
    libcblas-3.8.0             |       7_openblas           6 KB  conda-forge
    pthread-stubs-0.4          |    h14c3975_1001           5 KB  conda-forge
    **r-kinship2-1.6.4           |   r351h6115d3f_0         597 KB  conda-forge**
    r-quadprog-1.5_5           |r351ha65eedd_1002          49 KB  conda-forge
    ------------------------------------------------------------

Unless the channel's order is mixed or a lower version is requested, afaik the current approach should be ok.

**Comment by bgruening** [comment]
Thanks a lot, @npavlovikj for taking care of these! Cleanups are so much appreciated!!!

**Comment by npavlovikj** [comment]
I am glad to be able to help @bgruening . After you all work hard to have `bioconda` running, this is the least I can do :)

**Comment by epruesse** [comment]
Thanks a LOT for pitching in!

**Pull request merged**
