### PR TITLE
Perl: more unblacklisting

### PR DESCRIPTION
**Pull request by abretaud**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by druvus** [comment]
@abretaud perl-json currently depends on perl-json-xs <3 so I am rebuilding an older perl-json-xs here: #10313

**Comment by abretaud** [comment]
@druvus ah ok, thanks! I'll wait your PR to be merged!
By the way, I'm also working on perl-soap-lite and bioperl packages, is it ok for you?

**Comment by druvus** [comment]
Sounds good! I will not do more for some hours.

**Comment by druvus** [comment]
Seems to be osx permission issues in my PR. I have no computer access until this evening so you are welcome to take over the PR and fix it if you want.

**Pull request merged**
