### PR TITLE
Build seqkit for osx-arm64

### PR DESCRIPTION
**Pull request by corneliusroemer**

### CODE REVIEW

**Comment by corneliusroemer** [comment]
@BiocondaBot please fetch artifacts

**Comment by corneliusroemer** [comment]
@BiocondaBot please add label

**Review by martin-g — APPROVED** [review]

**Comment by shenwei356** [comment]
bioconda supports osx-arm64 now? That's cool.

**Comment by corneliusroemer** [comment]
Yep, since yesterday! I'm trying to make the whole nextstrain tool chain and tools used by it osx-arm64 ready and seqkit is part of it so I went ahead 😀

**Pull request merged**
