### PR TITLE
Update sina build

### PR DESCRIPTION
**Pull request by mdehollander**
* [x] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by mdehollander** [comment]
How to have libboost_program_options.so.1.54.0 included during runtime?

**Comment by acaprez** [comment]
Hmm, it looks like the tarball is a binary build for Ubuntu 14.04?  The boost linking issues aside, that won't work in the EL6-based condaforge image.  The glibc version there is older and will cause a version error at runtime.  You might be able to some some rpath manipulation magic to get it to find the boost libs, but that's iffy IMHO and it still wouldn't run because of the glibc issue.  The only reasonable option here really is to build from source IMO.

**Comment by mdehollander** [comment]
@acaprez, I think you are right, thanks for the explanation. I will see if I can work with the developer @epruesse to make a package from source.

**Comment by epruesse** [comment]
I agree, building from source is preferable. There are some issues to be fixed first though.

For the time being: there are centos5 and centos6 builds at the same location, maybe those will help.

@acaprez How would you satisfy a dependency on openmotif within conda? SINA depends on ARB which in turn requires openmotif to build fully. Even if openmotif is present on the build hosts (I would be surprised if it is), it won't be available on many client installations.

**Comment by acaprez** [comment]
Ideally both those would be added as conda packages first; then it wouldn't be an issue.  Unfortunately, getting packages which require GUI libraries to work in conda can be quite challenging.  Conda-forge did add a lot of X11 packages fairly recently though, so it might not be too bad at this point.

**Comment by mdehollander** [comment]
It seems ARB and its dependencies (https://github.com/epruesse/SINA/issues/8) are now in conda, so it should be possible to build a package from source

**Comment by epruesse** [comment]
@mdehollander Not quite, epruesse/SINA#8 isn't done yet. `openmotif` is just now complete for linux, hopefully osx will build soon. After that I can work on getting ARB into bioconda, and then I can start messing with SINA...

**Pull request closed without merging**
