### PR TITLE
Update sra tools 2 8 0

### PR DESCRIPTION
**Pull request by mvdbeek**
* [x] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

This is a continuation of #2577 by @croth1.
The current sratools package doesn't work anymore for many people due to NCBI's switch to HTTPS, so this should get in ASAP.

### CODE REVIEW

**Comment by croth1** [comment]
Hi @mvdbeek, thanks for taking this over. I don't understand the problem on macOS yet. Maybe linking against conda-forge/anaconda's version of libiconv and libxml, this will already be fixed.

**Comment by mvdbeek** [comment]
Hmmm:
```
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: changing install names or rpaths can't be redone for: /anaconda/conda-bld/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib64/libncbi-vdb.2.8.0.dylib (for architecture x86_64) because larger updated load commands do not fit (the program must be relinked, and you may need to use -headerpad or -headerpad_max_install_names)
```
Even though I did set
```
if [[ $OSTYPE == darwin* ]]; then
     export CFLAGS="-headerpad_max_install_names"
     export CXXFLAGS=$CFLAGS
fi
```
I guess I'll need to dive into the Makefile and see if CFLAGS gets overriden somewhere.

**Comment by mvdbeek** [comment]
Seems like
```
export LDFLAGS="${LDFLAGS} -headerpad_max_install_names"
```
did the trick for OSX. I'm trying if I can remove the CFLAGS export stuff, and I guess then we can merge!

**Comment by croth1** [comment]
Thanks for the great work. Unfortunately, the linking on macOS does not seem to be completely fine yet. The binaries are linked against the system's libraries, instead of conda's versions:

`otool -L $(which sra-pileup)`
```
/Users/ch/miniconda/envs/sci35/bin/sra-pileup:
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
	/usr/lib/libxml2.2.dylib (compatibility version 10.0.0, current version 10.9.0)
	/usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
```

It's not perfect, but it will certainly work 👍

**Pull request merged**
