### PR TITLE
Update perbase to 0.6.3

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`perbase`](https://bioconda.github.io/recipes/perbase/README.html): **0.4.2** &rarr; **0.6.3**

[install with bioconda](http://bioconda.github.io/recipes/perbase/README.html) [Conda](https://anaconda.org/bioconda/perbase/files)

Info | Link
-----|-----
Recipe | [`recipes/perbase`](https://github.com//bioconda/bioconda-recipes/tree/bump/perbase/recipes/perbase) (click to view/edit other files)
Releases |[https://github.com/sstadick/perbase/tags](https://github.com/sstadick/perbase/tags)
Author | `@sstadick`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by dpryan79** [comment]
Seems to be missing a header:

    18:54:40 BIOCONDA INFO (ERR)   cargo:warning=/Users/distiller/project/miniconda/conda-bld/perbase_1604976477758/work/target/release/build/hts-sys-73d509c7ea6cd389/out/htslib/hts.c:3693:13: warning: implicit declaration of function 'access' is invalid in C99 [-Wimplicit-function-declaration]
    18:54:40 BIOCONDA INFO (ERR)   cargo:warning=        if (access(s.s, R_OK) == 0)
    18:54:40 BIOCONDA INFO (ERR)   cargo:warning=            ^
    18:54:40 BIOCONDA INFO (ERR)   cargo:warning=/Users/distiller/project/miniconda/conda-bld/perbase_1604976477758/work/target/release/build/hts-sys-73d509c7ea6cd389/out/htslib/hts.c:3693:25: error: use of undeclared identifier 'R_OK'
    18:54:40 BIOCONDA INFO (ERR)   cargo:warning=        if (access(s.s, R_OK) == 0)
    18:54:40 BIOCONDA INFO (ERR)   cargo:warning=                        ^
    18:54:40 BIOCONDA INFO (ERR)   cargo:warning=/Users/distiller/project/miniconda/conda-bld/perbase_1604976477758/work/target/release/build/hts-sys-73d509c7ea6cd389/out/htslib/hts.c:3780:21: warning: implicit declaration of function 'unlink' is invalid in C99 [-Wimplicit-function-declaration]
    18:54:40 BIOCONDA INFO (ERR)   cargo:warning=    if (tmps.l > 0) unlink(tmps.s);
    18:54:40 BIOCONDA INFO (ERR)   cargo:warning=                    ^

**Comment by sstadick** [comment]
Just to add more info, something seems to be deeply broken in the Rust OSX / htslib build chain in github actions right now: https://github.com/rust-bio/rust-htslib/pull/275

**Comment by brainstorm** [comment]
@sstadick It's just the MUSL build that seems to be "deeply broken", but the native x86_64 build (sans docker) is passing ;)

**Comment by sstadick** [comment]
@brainstorm, your PR seems to have fixed things! Once there is an official release of rust-htslib v0.34.1, I will close my set of tickets, including this one. 

The issues seemed deep to me! Thank you for fixing things!

**Comment by sstadick** [comment]
This can be closed. Once the bot picks up the v0.6.3 release everything should work again. https://github.com/sstadick/perbase/releases/tag/v0.6.3

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Pull request merged**
