### PR TITLE
Add cvlr

### PR DESCRIPTION
**Pull request by marcDabad**
ADD recipe to CVLR software 

Paper: https://www.biorxiv.org/content/10.1101/2022.04.19.488395v2
Github: https://github.com/EmanueleRaineri/cvlr
----

### CODE REVIEW

**Comment by marcDabad** [comment]
@BiocondaBot please add label

**Comment by dpryan79** [comment]
@BiocondaBot please fetch artifacts

**Comment by dpryan79** [comment]
@BiocondaBot please fetch artifacts

**Comment by dpryan79** [comment]
@marcDabad Can you request that a release be tagged in the original repository?

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@BiocondaBot please merge

**Pull request merged**
