### PR TITLE
Update sourmash to 4.4.1

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`sourmash`](https://bioconda.github.io/recipes/sourmash/README.html): **4.4.0** &rarr; **4.4.1**

[install with bioconda](http://bioconda.github.io/recipes/sourmash/README.html) [Conda](https://anaconda.org/bioconda/sourmash/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/sourmash`](https://github.com//bioconda/bioconda-recipes/tree/bump/sourmash/recipes/sourmash) (click to view/edit other files)
Summary | Compute and compare MinHash signatures for DNA data sets.
Home | [https://github.com/dib-lab/sourmash](https://github.com/dib-lab/sourmash)
Releases |[https://pypi.org/pypi/sourmash/json](https://pypi.org/pypi/sourmash/json)
Recipe Maintainer(s) | @luizirber, @ctb, @bluegenes

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by daler** [comment]
Needs update of `sourmash-minimal` on conda-forge.

**Comment by luizirber** [comment]
> Needs update of `sourmash-minimal` on conda-forge.

Working on it! https://github.com/conda-forge/sourmash-minimal-feedstock/pull/30

**Comment by luizirber** [comment]
@BiocondaBot rebuild

**Comment by luizirber** [comment]
@BiocondaBot please update

**Review by luizirber — APPROVED** [review]

**Pull request closed without merging**
