### PR TITLE
Lordec 0.9

### PR DESCRIPTION
**Pull request by abretaud**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

Added a recipe for gatb and prevent lordec from compiling its own boost and gatb versions

### CODE REVIEW

**Comment by abretaud** [comment]
@bioconda/core do you see why the linux test is failing for lordec? It works fine on my laptop, and I see nothing wrong in the log

**Comment by martin-mann** [comment]
seems your `-lrt` linker flag fails since the RT library is not found... Maybe the `compiler-rt` package will help, I will add and give it a try..

**Comment by abretaud** [comment]
ah thanks @martin-mann, I missed this lib!

**Comment by martin-mann** [comment]
seems this package doesnt do the trick.. :cry: maybe `-lrt` is not needed for osx?!

**Comment by martin-mann** [comment]
@abretaud you might want to change your makefile.patch to something like this
```
ifeq ($(UNAME_S),Darwin)
LDFLAGS = -L$(GATB)/lib/ -lgatbcore -lhdf5$(HDFSUFFIX) -ldl -lz -lpthread -std=c++0x -O3 $(EXTRALDFLAGS)
else
# on NON-MacOS, we need to add RT library
LDFLAGS = -L$(GATB)/lib/ -lgatbcore -lhdf5$(HDFSUFFIX) -lrt -ldl -lz -lpthread -std=c++0x -O3 $(EXTRALDFLAGS)
endif
```
hope this helps

final solution: skip OSX build for this package....

**Comment by abretaud** [comment]
and it... works! thanks @martin-mann!

**Pull request merged**
