### PR TITLE
Rust and cargo packages.

### PR DESCRIPTION
**Pull request by johanneskoester**

### CODE REVIEW

**Comment by johanneskoester** [comment]
@bioconda/members does anybody have an idea how to fix the osx build. It seems to have trouble fixing the libraries.

**Comment by daler** [comment]
Don't know of a fix, but possibly similar to #476?

**Comment by johanneskoester** [comment]
Maybe. Well, I will merge the non-osx-version for now.

**Comment by kyleabeauchamp** [comment]
Can someone remind me why we have rust installed both as a conda package as well as hardcoded in the environment setup?  

https://github.com/bioconda/bioconda-recipes/blob/master/scripts/travis-setup.sh#L9

**Comment by kyleabeauchamp** [comment]
Also https://github.com/bioconda/bioconda-recipes/blob/master/scripts/Dockerfile#L21

**Comment by johanneskoester** [comment]
Yes, initially I thought having rust in Docker is a good idea. Now we are in the process of removing build dependencies from the docker container (and e.g. use the gcc and llvm from conda). Hence, it is reasonable to also provide the rust compiler via conda.

**Comment by kyleabeauchamp** [comment]
See #852

**Pull request merged**
