### PR TITLE
wrassp - speech signal processing

### PR DESCRIPTION
**Pull request by stevecassidy**
- [x] I have read the guidelines above.
- [x] This PR adds a new recipe.
- [ ] This PR updates an existing recipe.
- [ ] This PR does something else (explain below).

@bioconda/core - a new recipe for a C based signal processing package. Not sure about this, it builds ok for me on OSX but not via the docker build image where it complains about duplicate symbols while linking.  Can't see what the issue might be since the R build is clean on linux. I thought I would submit for your evaluation in case it just works for you :-) Happy to have it sent back if not.

### CODE REVIEW

**Comment by bgruening** [comment]
Steve we saw this error recently in a few packages:

```
assp/acf.o:acf.c:(.text+0x45): first defined here
wrassp.o: In function `gnu_dev_major':
wrassp.c:(.text+0x0): multiple definition of `gnu_dev_major'
assp/acf.o:acf.c:(.text+0x0): first defined here
wrassp.o: In function `gnu_dev_minor':
wrassp.c:(.text+0x28): multiple definition of `gnu_dev_minor'
assp/acf.o:acf.c:(.text+0x28): first defined here
wrassp.o: In function `gnu_dev_makedev':
wrassp.c:(.text+0x45): multiple definition of `gnu_dev_makedev'
assp/acf.o:acf.c:(.text+0x45): first defined here
collect2: error: ld returned 1 exit status
make: *** [wrassp.so] Error 1
```

Need to figure out what is going on here, it seems to be an issue with the GCC version?
ping @kyleabeauchamp @johanneskoester

**Comment by stevecassidy** [comment]
Yes, this went away when I upgraded conda including the new gcc version.

Steve

—
Department of Computing, Macquarie University
http://web.science.mq.edu.au/~cassidy

On 21 Aug 2016, at 8:28 AM, Björn Grüning <notifications@github.com<mailto:notifications@github.com>> wrote:


Steve we saw this error recently in a few packages:

assp/acf.o:acf.c:(.text+0x45): first defined here
wrassp.o: In function `gnu_dev_major':
wrassp.c:(.text+0x0): multiple definition of `gnu_dev_major'
assp/acf.o:acf.c:(.text+0x0): first defined here
wrassp.o: In function `gnu_dev_minor':
wrassp.c:(.text+0x28): multiple definition of `gnu_dev_minor'
assp/acf.o:acf.c:(.text+0x28): first defined here
wrassp.o: In function `gnu_dev_makedev':
wrassp.c:(.text+0x45): multiple definition of `gnu_dev_makedev'
assp/acf.o:acf.c:(.text+0x45): first defined here
collect2: error: ld returned 1 exit status
make: *** [wrassp.so] Error 1


Need to figure out what is going on here, it seems to be an issue with the GCC version?
ping @kyleabeauchamp<https://github.com/kyleabeauchamp> @johanneskoester<https://github.com/johanneskoester>

**Comment by johanneskoester** [comment]
@stevecassidy can you clarify? To which conda and gcc version (and on which platform) did you upgrade to make this go away?

**Comment by stevecassidy** [comment]
@johanneskoester<https://github.com/johanneskoester> - I upgraded to the latest conda (4.1.11) and the build worked.  I’m not 100% sure it was because of gcc/libc but these were both upgraded in the process.

Steve
—
Department of Computing, Macquarie University
http://web.science.mq.edu.au/~cassidy

On 22 Aug 2016, at 11:46 PM, Johannes Köster <notifications@github.com<mailto:notifications@github.com>> wrote:


@stevecassidy<https://github.com/stevecassidy> can you clarify? To which conda and gcc version (and on which platform) did you upgrade to make this go away?

**Comment by bgruening** [comment]
@stevecassidy we are talking about compiling on your host system, not inside of the bioconda docker image, isn't it?

**Comment by bgruening** [comment]
Could you try to apply your changes to this branch: https://github.com/bioconda/bioconda-recipes/tree/bioconda-utils-soft

It has a new GCC and a new conda-build.
Thanks.

**Comment by stevecassidy** [comment]
Yes, but I also shelled into the docker image and upgraded before running the build script and it worked as well.

Steve



—
Department of Computing, Macquarie University
http://web.science.mq.edu.au/~cassidy

On 23 Aug 2016, at 6:51 AM, Björn Grüning <notifications@github.com<mailto:notifications@github.com>> wrote:


@stevecassidy<https://github.com/stevecassidy> we are talking about compiling on your host system, not inside of the bioconda docker image, isn't it?

**Comment by johanneskoester** [comment]
@stevecassidy you have a libc package in your conda?

**Comment by johanneskoester** [comment]
I tried to reproduce your success. Unfortunately, I can't. In the docker container, I first upgraded conda with `conda update conda`. Same error. Then I tried `conda update --all`. Same error. In both cases, it used gcc 4.8.5. Am I missing a step?

**Comment by stevecassidy** [comment]
@johanneskoester I only succeeded when I used gcc 4.8.2 which is the gcc version installed in the container (outside of conda).  I did:

`conda create -n testbuild2 gcc=4.8.2`
`source activate testbuild2`

then I could build wrassp (manually, from the tgz file).

Pinning to 4.8.2 in the meta.yaml file for the package seems to allow it to build in the docker container. 

Steve

**Comment by johanneskoester** [comment]
Ok, this confirms what we see as well. There is an incompatibility between the gcc 4.8.5 build and CentOS 5 containers.

**Comment by bgruening** [comment]
@stevecassidy this can be closed isn't it?

**Comment by stevecassidy** [comment]
Yes, all good now.

Steve

—
Department of Computing, Macquarie University
http://web.science.mq.edu.au/~cassidy

On 2 Nov. 2016, at 7:05 pm, Björn Grüning <notifications@github.com<mailto:notifications@github.com>> wrote:


@stevecassidy<https://github.com/stevecassidy> this can be closed isn't it?

**Pull request closed without merging**
