### PR TITLE
Update pbcoretools to 0.8.1

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`pbcoretools`](https://bioconda.github.io/recipes/pbcoretools/README.html): **0.2.4** &rarr; **0.8.1**

[install with bioconda](http://bioconda.github.io/recipes/pbcoretools/README.html) [Conda](https://anaconda.org/bioconda/pbcoretools/files)

Info | Link
-----|-----
Recipe | [`recipes/pbcoretools`](https://github.com//bioconda/bioconda-recipes/tree/bump/pbcoretools/recipes/pbcoretools) (click to view/edit other files)
Releases |[https://github.com/PacificBiosciences/pbcoretools/releases](https://github.com/PacificBiosciences/pbcoretools/releases)
Recipe Maintainer(s) | @pb-dseifert, @mhsieh
Author | `@PacificBiosciences`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by pb-dseifert** [comment]
@dpryan79 why did Bioconda build `pbcommand` for py3.8?

**Comment by pb-dseifert** [comment]
@bioconda-bot please fetch artifacts

**Comment by pb-dseifert** [comment]
@bioconda-bot please merge

**Comment by armintoepfer** [comment]
@bioconda-bot please merge

**Comment by pb-dseifert** [comment]
@bioconda-bot please merge

**Pull request merged**
