### PR TITLE
Update guidelines link in PR template

### PR DESCRIPTION
**Pull request by astaric**
Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it. Note that if you are not already a member of the bioconda project (meaning that you can't add this label), please ping `@bioconda/core` so that your PR can be reviewed and merged (please note if you'd like to be added to the bioconda project). Please see https://github.com/bioconda/bioconda-recipes/issues/15332 for more details.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [ ] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [x] This PR does something else (explain below).

This PR updates the outdated link to the Guidelines in the PR template.

### CODE REVIEW

**Comment by astaric** [comment]
@bioconda/core

**Comment by dpryan79** [comment]
Nice catch!

**Comment by astaric** [comment]
@dpryan79, the link in the biocondabot's Welcome message is also outdated, not sure where to fix that one.

**Comment by dpryan79** [comment]
@astaric Ah, good to know, that's probably in bioconda-utils. I'll have a look.

**Comment by dpryan79** [comment]
Oh, it's in the same directory. I'll fix that real quick, thanks again!

**Pull request merged**
