### PR TITLE
[WIP] Dependencies for r-dartr update

### PR DESCRIPTION
**Pull request by jenzopr**
:information_source:
If this is your first pull request to Bioconda please ping `@bioconda/core` so it can be reviewed and to request being added as a member of the Bioconda team. Members of the Bioconda team are able to merge their own pull requests once tests and linting have passed.

----------------

* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [X] This PR adds a new recipe.
* [X] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

This is work-in-progress to add dependencies for r-dartr (#14917) - please do not merge yet :-)

### CODE REVIEW

**Comment by dpryan79** [comment]
Can you move at least the `r-rrblup` recipe to conda-forge? At some point we'll migrate as much as we can that depends on `r-adegenet` to conda-forge too.

**Comment by jenzopr** [comment]
Sure!

**Comment by dpryan79** [comment]
OK, the problem is simply that r-rgdal needs to be pinned to proj4. I'll make a PR real quick.

**Comment by jenzopr** [comment]
Thanks for trying hard! :tada:

**Comment by dpryan79** [comment]
LGTM, thanks!

**Pull request merged**
