### PR TITLE
Update srnapipe.

### PR DESCRIPTION
**Pull request by ppouchin**
Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

 * `@BiocondaBot please update` will cause the BiocondaBot to merge the master branch into a PR
 * `@BiocondaBot please add label` will add the `please review & merge` label.
 * `@BiocondaBot please fetch artifacts` will post links to packages and docker containers built by the CI system. You can use this to test packages locally before merging.

For members of the Bioconda project, the following command is also available:

 * `@BiocondaBot please merge` will cause packages/containers to be uploaded and a PR merged. Someone must approve a PR first! This has the benefit of not wasting CI build time required by manually merging PRs.

If you have questions, please post them in gitter or ping `@bioconda/core` in a comment (if you are not able to directly ping `@bioconda/core` then the bot will repost your comment and enable pinging).

### CODE REVIEW

**Comment by ppouchin** [comment]
Apparently, r-ggplot2 doesn't include fonts, so if the OS doesn't provide any, graphs will have empty boxes instead of characters. 
Including "fonts-conda-ecosystem" normally solves this.

@BiocondaBot please update

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Comment by ppouchin** [comment]
Will this effectively update the package that gets installed through `conda install srnapipe`?
Apparently, it has already been [modified a month ago](https://github.com/bioconda/bioconda-recipes/blame/master/recipes/srnapipe/meta.yaml), but the [files on anaconda are still from January](https://anaconda.org/bioconda/srnapipe/files)...

**Comment by dpryan79** [comment]
Ah, apparently this was blacklisted, which would explain why the bot had an error (I shouldn't have ignored that).

**Comment by dpryan79** [comment]
Can you make a new PR removing this from `build-fail-blacklist`? Then it will actually get built.

**Comment by ppouchin** [comment]
Ok. Thank you for your help.
Apparently, the pinning for perl was dropped with the last commit and the version it tries to set up is 5.26. However, the tool requires 5.22. 
I'll go back to the tests and make a PR for removing this from the blacklist when I get it to work properly.

**Pull request merged**
