### PR TITLE
Update motus to version 2.1.0

### PR DESCRIPTION
**Pull request by AlessioMilanese**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [ ] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

Update to version 2.1.0

### CODE REVIEW

**Comment by unode** [comment]
Looks good to me.

**Comment by unode** [comment]
@bioconda/build-system what is the procedure when a build passes all tests (local and here) but fails on the final build after merge? (and could we get this answer into the [guidelines](https://bioconda.github.io/guidelines.html) or [troubleshooting](https://bioconda.github.io/troubleshooting.html) pages?)

**Comment by bgruening** [comment]
@AlessioMilanese was this just a transient build error?

**Comment by unode** [comment]
@bgruening I got the CI links from https://github.com/bioconda/bioconda-recipes/commits/master.
Tests passed both here and #13886 but in both cases failed after squash merge. CI reports are [this pull request](https://circleci.com/gh/bioconda/bioconda-recipes/46291) and [#13886](https://circleci.com/gh/bioconda/bioconda-recipes/46302).

Oddly enough, the last link actually succeeded to upload but somehow still failed afterwards.

**Pull request merged**
