### PR TITLE
Update pp-sketchlib to v1.2.0

### PR DESCRIPTION
**Pull request by johnlees**
Requires CUDA to compile on host, and armadillo to run. Using openblas and lapack rather than intel libraries on linux, as they seem less likely to cause version conflicts.

----

> Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences**
      (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

> Everyone has access to the following BiocondaBot commands, which can be given in a comment:
>
>  * `@BiocondaBot please update` will cause the BiocondaBot to merge the master branch into a PR
>  * `@BiocondaBot please add label` will add the `please review & merge` label.
>  * `@BiocondaBot please fetch artifacts` will post links to packages and docker containers built by the CI system. You can use this to test packages locally before merging.
>
> For members of the Bioconda project, the following command is also available:
>
>  * `@BiocondaBot please merge` will cause packages/containers to be uploaded and a PR merged. Someone must approve a PR first! This has the benefit of not wasting CI build time required by manually merging PRs.
>
> If you have questions, please post them in gitter or ping `@bioconda/core` in a comment (if you are not able to directly ping `@bioconda/core` then the bot will repost your comment and enable pinging).

### CODE REVIEW

**Comment by johnlees** [comment]
@bioconda/core I am having trouble to get the CUDA part of this package to compile. There is one .cu file which uses `nvcc` to compile:
- Using the `nvcc_linux-64` and `cudatoolkit` packages gave me an error about `CUDA_HOME` not being set, and the compiler not being found. Not sure is a post link script setting this variable might help?
- Using the `cudatoolkit-dev` package fails when running [this post install script](https://github.com/conda-forge/cudatoolkit-dev-feedstock/blob/master/recipe/post-link.sh) on the bioconda CI. I can't replicate this locally

Do you know of any other bioconda packages that have successfully compiled CUDA code, and if so how they achieved this?

**Comment by dpryan79** [comment]
I don't think we have any GPUs available on circleci.

Last I heard, the tensorflow package from conda-forge was being compiled and uploaded outside the normal CI workflow, do you know if that's still the case @bgruening?

**Comment by johnlees** [comment]
I think it should be possible to compile on (CI) systems without a GPU as long as the nvcc tools are installed?

**Comment by dpryan79** [comment]
I would also have presumed so, but I have no experience with nvcc :(

**Comment by johnlees** [comment]
Do you think it's worth trying to put this on conda-forge, as they have a package with `nvcc` (I think)? Or I can drop the dependency and it will compile CPU code only, and I can leave it up to users with CUDA installs to compile the GPU code themselves

**Comment by dpryan79** [comment]
Before trying it on conda-forge let's just try explicitly adding nvcc.

**Comment by dpryan79** [comment]
Yeah, maybe try this in conda-forge and see if you can get it to work there. I have a feeling we'd need to update the pinnings to get this working easily.

**Comment by mbargull** [comment]
conda-forge uses a different container image that provides the CUDA toolchain. This is not something we currently support.
We'll probably support it at some point, but AFAICT it's not high priority. So, I would guess it'll take at least months (late this year, maybe?) before we do. Though, I know @johanneskoester expressed interest in this.

**Comment by johnlees** [comment]
Hi both,
Thanks for the input, that's good to know. For now I'll see if I can get it to work on conda-forge, and if I fail will revive this as CPU code only. 
I would also be interested in this functionality in bioconda, but appreciate that it's not high priority at the moment. Perhaps in a year or two there will be more demand, now that some CUDA genomics applications have been released

**Comment by johnlees** [comment]
This is now on conda-forge instead - I'll close this, but presumably it makes sense to leave the older versions on bioconda?

**Pull request closed without merging**
