### PR TITLE
bump mason2 to 2.0.9

### PR DESCRIPTION
**Pull request by dpryan79**
* [ ] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [ ] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by dpryan79** [comment]
@epruesse The bot correctly found the linting error (should be noarch) whereas the tagged bioconda-utils release did not, so well done :)

**Comment by dpryan79** [comment]
@bioconda-bot merge

**Comment by epruesse** [comment]
Hmm. Not sure. It should have detected that you have `# [osx]` things in there I think, and decided that you can't have noarch.

**Comment by dpryan79** [comment]
Hmm, I suppose so, though I think the current behavior is nice given the lack of a `build:` section.

**Pull request merged**
