### PR TITLE
Updated blast+ to 2.10.1 please merge soon

### PR DESCRIPTION
**Pull request by ialbert**
updated blast version to 2.10.0 

the change is urgent as blast 2.9.0 remote access is broken. See:

https://www.biostars.org/p/400841/

> *Date: Thu, 10 Oct 2019 07:40:48 ... Thank you for the report. There is a bug in 2.9.0 when using the '-remote' option. It should work in 2.8.1, and it has been fixed for the upcoming 2.10.0 release, which should be out in 2 or 3 weeks."*

No blast search can be run remotely on the current blast version.

**Replace this sentence with a detailed description of your pull request**

----

> Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [ ] This PR adds a new recipe.
* [ ] AFAIK, this recipe **is directly relevant to the biological sciences**
      (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

> Everyone has access to the following BiocondaBot commands, which can be given in a comment:
>
>  * `@BiocondaBot please update` will cause the BiocondaBot to merge the master branch into a PR
>  * `@BiocondaBot please add label` will add the `please review & merge` label.
>  * `@BiocondaBot please fetch artifacts` will post links to packages and docker containers built by the CI system. You can use this to test packages locally before merging.
>
> For members of the Bioconda project, the following command is also available:
>
>  * `@BiocondaBot please merge` will cause packages/containers to be uploaded and a PR merged. Someone must approve a PR first! This has the benefit of not wasting CI build time required by manually merging PRs.
>
> If you have questions, please post them in gitter or ping `@bioconda/core` in a comment (if you are not able to directly ping `@bioconda/core` then the bot will repost your comment and enable pinging).

### CODE REVIEW

**Comment by dpryan79** [comment]
I wish blast were easier to build :(

**Comment by dpryan79** [comment]
I get the feeling that the memory available on circleci has decreased recently, which may have caused the test to fail. We can try to disable that and test locally once the package is otherwise buildable.

**Comment by ialbert** [comment]
why does this need to be built from source? Or tested for that matter.

NCBI offers prebuilt versions for all platforms, no tests need to be run for these in my opinion. 

ftp://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/2.10.0/

NCBI has an entire dedicated software team working on blast.

**Comment by yesimon** [comment]
This has been debated in the past but the main reason is conserving space and preferring building from source across all packages. See #6290

**Comment by ialbert** [comment]
@yesimon that reasoning may have made more sense in 2017, right now the package cannot be built, people are spending time on things that should not need to. 

Instead of looking back to that discussion for validation and rationalization, you should look back at it as the time when the mistake was made, and how to avoid making the same in the future

today updating blast to the latest version leads to a 77 minute build time before failing, and it is not clear what the failure is, yet in principle all conda would need to do is unpack and copy the blast binaries to bin and it's would be done,  

instead it does this, what the heck is this anyway:

`et_rpaths_raw()=['/opt/conda/conda-bld/blast_1584141217920/_build_env/lib:/opt/conda/conda-bld/blast_1584141217920/_build_env/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/lib/../lib:/opt/conda/conda-bld/blast_1584141217920/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib:/opt/conda/conda-bld/blast_1584141217920/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/ncbi-blast+'] and patchelf=[['/opt/conda/conda-bld/blast_1584141217920/_build_env/lib', '/opt/conda/conda-bld/blast_1584141217920/_build_env/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/lib/../lib', '/opt/conda/conda-bld/blast_1584141217920/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib', '/opt/conda/conda-bld/blast_1584141217920/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/ncbi-blast+']] disagree for /opt/conda/conda-bld/blast_1584141217920/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/ncbi-blast+/libncbi_xreader_id2.so ::
`

**Comment by yesimon** [comment]
I don't have a side but I think it's important to understand the historical context of why the decision was made, especially considering we previously packaged the static binaries. My personal opinion is to keep it if the original build-from-source authors @epruesse @sachalau are willing to maintain the recipe, otherwise go with statically built.

As far as the `_placeholder_` spam goes, it's actually intentional conda-build behavior to build binaries in a very long path so that patchelf can rewrite the dynamic library load path in the end-user's installation of the binary. Therefore it has to be longer than any conceivable path an end-user might install it into.

For the CI failure: it seems like compilation/conda-build succeeded, creating the db succeeded, but checking the db failed in the test.

```
00:26:01 BIOCONDA INFO (OUT) Creating Database... PASS
00:26:02 BIOCONDA INFO (OUT) Error: [blastdbcmd] DB contains no accession info.
```

**Comment by dpryan79** [comment]
Precompiled binaries often break on people's computers, which is why we try not to distribute them. Sometimes we can't build things otherwise, so we end up just shipping these precompiled binaries.

**Comment by dpryan79** [comment]
@bioconda-bot please fetch artifacts

**Comment by dpryan79** [comment]
I'll test the linux build locally, specifically the two tests that I commented out.

**Comment by sachalau** [comment]
Hello, regarding support of the original recipe I can't say I've been an active contributors of bioconda in the past months/years so I feel a bit out of the loop. I'll try to have a look at the recipe in the few days if that helps, before you revert to static.

**Comment by dpryan79** [comment]
It's still unclear why the linux tests failed, they pass when I install the package locally, so I'll declare that as "works fine".

**Comment by dpryan79** [comment]
The OSX build is failing with the following, which I won't pretend to be able to diagnose:

    /Users/distiller/project/miniconda/conda-bld/blast_1584176457182/work/c++/scripts/common/impl/create_flat_makefile.sh: line 201: 17819 Segmentation fault: 11  $ptb -version > /dev/null 2>&1

**Comment by ialbert** [comment]
Any chance that this would move forward?  In this particular case the files in this directory need to be copied/linked over to bin depending on the platform:

ftp://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/2.10.0/

I would do it myself if I had a little better understanding of the conventions, I'll be here linting and rejecting for weeks until I got everything just right.

**Comment by dpryan79** [comment]
I guess we can test whether the precompiled binaries actually work. That's not always the case for things from NCBI.

**Comment by ialbert** [comment]
on the Mac they do work as I have been using them, in general I would be surprised if they didn't, I would imagine their software practices improved a lot

**Comment by dpryan79** [comment]
I've tried the binaries. The Linux one won't work on all systems. The OSX one can't have its linking fixed to ensure that it will actually work everywhere.

**Comment by ialbert** [comment]
Thanks for taking a look Devon, I guess we will have to recommend that people download the latest binary version and see if that works for them.

**Comment by mbargull** [comment]
Needs macOS SDK `>=10.10`, blocked by gh-21180.

**Comment by Juke34** [comment]
Please wait for merge of #21497

**Comment by Juke34** [comment]
#22777 merged, we can fix and merge this recipe.

**Comment by abretaud** [comment]
So what's the status here?

**Comment by abretaud** [comment]
@BiocondaBot update

**Comment by abretaud** [comment]
@BiocondaBot please update

**Comment by abretaud** [comment]
@bioconda-bot please fetch artifacts

**Comment by abretaud** [comment]
@BiocondaBot please add label

**Comment by bgruening** [comment]
The test issue looks Indeed wired. But I guess we should get this out and seek for broader testing. Thanks everyone!

**Comment by abretaud** [comment]
Yep, "BLAST Database error: Error pre-fetching sequence data" is strange... It passes locally though, maybe something to do with the circleci env?

**Comment by abretaud** [comment]
@BiocondaBot please merge

**Comment by Juke34** [comment]
`RpsbProc` did not compile on OSX:
```
05:35:21 BIOCONDA INFO (OUT) FAILED: src/app/RpsbProc/Makefile.rpsbproc.app
05:35:21 BIOCONDA INFO (OUT) /bin/rm -f rpsbproc .rpsbproc.stamp
```

**Comment by epruesse** [comment]
@Juke34 - can you try to fix in PR?

**Comment by Juke34** [comment]
Yes I tried to start something here #24392 but I do not know how to fix it

**Pull request merged**
