### PR TITLE
Added "suggested" packages (required for Galaxy) for msPurity

### PR DESCRIPTION
**Pull request by Tomnl**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by dpryan79** [comment]
@bioconda-bot recheck

**Comment by dpryan79** [comment]
The version you're modify is for bioconductor 3.9 and can't be built until after R 3.6.1 is released? If you really need this changed for Galaxy let me know and we can make a versioned subdirectory for the 3.8 release version.

**Comment by Tomnl** [comment]
@dpryan79 - do you know when R 3.6.1 will be released?

**Comment by dpryan79** [comment]
My guess would be sometime in July, but there's no release date posted.

**Comment by Tomnl** [comment]
OK thanks - I would need the update package before July.  So hopefully it is possible to make a sub directory for 3.8 release.

How would that work? would I need to use the updated recipe and build into a sub directory with the folder name "1.10.0" or would the version number need to be different?

**Comment by dpryan79** [comment]
Does the July deadline correspond to GCC? :)

**Comment by dpryan79** [comment]
Xref https://github.com/bioconda/bioconda-recipes/pull/15509

**Comment by dpryan79** [comment]
I'll make sure this gets added in the PR I linked to. Are you OK with version 1.8.1 or do you need 1.8.0 for the Galaxy wrapper?

**Comment by Tomnl** [comment]
Just checking - the #15509 will add the msPurity v1.8.1 (from bioconductor 3.8 release) into bioconda (but with the additional packages). 

However, it still won't be possible to add the msPurity v1.10.0 into bioconda until R 3.6.1 is added?

In the mean time though, if I need the functionality of v1.10.0,  I could use my own conda channel that builds the msPurity v1.10.0 against an older version of R

**Comment by dpryan79** [comment]
If you actually need the functionality from 1.10.0 then you have no choice but to wait. You can't build the package on an older version of R, because it ends up depending on BiocGenerics (via mzr), which is not compatible with anything before R 3.6.

**Comment by Tomnl** [comment]
If we could get 1.8.1 on Bioconda as per  #15509 - that will be very useful for the current Galaxy tools I have developed

I have been using bit of a bodged build for testing new functionality & tools in Galaxy before the Bioconductor 3.9 release was made stable (see [link](https://anaconda.org/tomnl/bioconductor-mspurity/1.9.10/download/linux-64/bioconductor-mspurity-1.9.10-r341hf484d3e_0.tar.bz2)) that used r-base 3.4.1 and seemed to work OK. 

However, I am happy to wait for the R 3.6 msPurity v1.10.0 before more officially releasing the Galaxy tools that require any additional functionality provided in msPurity v1.10.0

Thanks for all the help

**Comment by dpryan79** [comment]
OK, I'll merge in 1.8.1 then.

**Comment by Tomnl** [comment]
thanks

**Comment by dpryan79** [comment]
1.8.1 will be available within 20 minutes.

**Comment by Tomnl** [comment]
Great! thanks for the help

**Pull request closed without merging**
