### PR TITLE
Cgat core

### PR DESCRIPTION
**Pull request by sebastian-luna-valero**
* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [X] This PR adds a new recipe.
* [ ] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

`cgat-core` is a workflow management system based on `ruffus`, which is already in `bioconda`. I first tried adding `cgat-core` to `conda-forge` (xref: https://github.com/conda-forge/staged-recipes/pull/6672) but it does not work because `ruffus` was packaged in `bioconda`.

Although `cgat-core` could be used as a general workflow managment system (like `snakemake` or `nextflow`) we have only used in Computational Genomics. Should we add it here as well or should we move `ruffus` to `conda-forge` instead?

### CODE REVIEW

**Comment by bgruening** [comment]
@sebastian-luna-valero please ask the ruffus developers. Whatever is more convenient for you I would say.

**Comment by sebastian-luna-valero** [comment]
Many thanks @bgruening

**Comment by sebastian-luna-valero** [comment]
ping @bunbun @AndreasHeger please let me know your thoughts.

**Comment by sebastian-luna-valero** [comment]
@bgruening just to confirm @AndreasHeger is happy for the package to be hosted by bioconda.

I would be grateful if you could have a quick look at the recipe to confirm is in good shape before merging.

**Comment by sebastian-luna-valero** [comment]
I will merge it now since it is a bit urgent. Please feel free to comment here any issues.

**Pull request merged**
