### PR TITLE
Update ViennaRNA to v2.5.0

### PR DESCRIPTION
**Pull request by RaumZeit**
Describe your pull request here

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by RaumZeit** [comment]
`test-linux` check timed out after 59min. Please re-run the checks as the package builds fine.  It only requires too much time on  CircleCI while building for all the different conda versions.

btw. last version required more than an hour for `test-linux` and still didn't bail out with a timeout error

**Comment by RaumZeit** [comment]
@bioconda/core Please let me know what can be done to re-run the checks (possibly with larger timeout interval). Build and internal tests run fine, it just takes too long to build for all bioconda variants

**Comment by dpryan79** [comment]
@RaumZeit I contacted circleci to try and find out what the heck is going on with the sudden spate of jobs getting killed at 1 hour. It turns out they changed their maximum run time for the open source plan to 1 hour. So we get to move all of our CI off of circleci and onto Azure. This will unfortunately take a little time :(

**Comment by RaumZeit** [comment]
@dpryan79 Ok, that's unfortunate!
Do you have any vague estimate on how long this will take? Is this more a matter of days or weeks?
I'm just asking because we planned to use the latest ViennaRNA Package in one of our upcoming online teaching courses within a JupyterLab instance...
If this is more of a matter of sevral weeks, we would than think of a solution that involves compilation from source or something similar...

**Comment by RaumZeit** [comment]
@BiocondaBot rebuild

**Comment by RaumZeit** [comment]
@BiocondaBot please add label

**Review by dpryan79 — APPROVED** [review]

**Pull request merged**
