### PR TITLE
Update phyloacc to 2.1.1

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`phyloacc`](https://bioconda.github.io/recipes/phyloacc/README.html): **2.1.0** &rarr; **2.1.1**

[install with bioconda](http://bioconda.github.io/recipes/phyloacc/README.html) [Conda](https://anaconda.org/bioconda/phyloacc/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/phyloacc`](https://github.com//bioconda/bioconda-recipes/tree/bump/phyloacc/recipes/phyloacc) (click to view/edit other files)
Summary | Bayesian estimation of substitution rate shifts in non-coding regions
Home | [https://phyloacc.github.io/](https://phyloacc.github.io/)
Releases |[https://github.com/phyloacc/PhyloAcc/tags](https://github.com/phyloacc/PhyloAcc/tags)
Recipe Maintainer(s) | @gwct
Author | `@phyloacc`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by gwct** [comment]
@BiocondaBot please add label

**Comment by gwct** [comment]
Is there any action I can take other than adding the label to facilitate the merging of this PR? Should I go ahead and review the changes even though I am not on the Bioconda team? Sorry if this is all laid out somewhere and I just missed it, but I haven't been able to find docs that outline the protocols/etiquette for PRs here.
Thanks!

**Comment by gwct** [comment]
@bioconda/core PR ready for review.

**Review by holtgrewe — APPROVED** [review]

**Comment by holtgrewe** [comment]
@BiocondaBot please merge

**Pull request merged**
