### PR TITLE
Add recipes for pdfkit and wkhtmltopdf

### PR DESCRIPTION
**Pull request by kyleabeauchamp**

### CODE REVIEW

**Comment by kyleabeauchamp** [comment]
This approach won't work.  The existing binaries require glibc 2.10 and hence centos 6.

**Comment by kyleabeauchamp** [comment]
So I did a big hack here.  The wkhtmltopdf binaries require Centos 6 or greater due to the glibc requirement.  However, AFAIK we could still build the package on our VM, we just can't run the executable on the VM.  

What do you think @johanneskoester ?

**Comment by kyleabeauchamp** [comment]
There's no way to specify a MIN_GLIBC version via conda recipe at this point, correct?

**Comment by kyleabeauchamp** [comment]
IMHO this is not going to be a major problem.  The binaries will run on any linux of the past 8 years.

**Comment by johanneskoester** [comment]
I agree. We should think about switching...

**Pull request merged**
