### PR TITLE
Tadarida c for Galaxy

### PR DESCRIPTION
**Pull request by ThimotheeV**
* [X ] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [X ] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

Hello again, new part of the TADDARIDA tool suite.

### CODE REVIEW

**Comment by bgruening** [comment]
@ThimotheeV was the renaming from -d to -c intentional?

**Comment by ThimotheeV** [comment]
@bgruening This is not the same tool.

**Comment by bgruening** [comment]
But you remove the one tool in this PR.

**Comment by ThimotheeV** [comment]
Sorry my mistake i will correct it !

**Pull request closed without merging**
