### PR TITLE
tiny update to garnet

### PR DESCRIPTION
**Pull request by zfrenchee**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by zfrenchee** [comment]
The error is 
```
	File "/usr/local/lib/python3.6/site-packages/GarNet-0.4.0-py3.6.egg/GarNet/__init__.py", line 3, in <module>
	File "/usr/local/lib/python3.6/site-packages/GarNet-0.4.0-py3.6.egg/GarNet/garnet.py", line 13, in <module>
	File "/usr/local/lib/python3.6/site-packages/pandas/__init__.py", line 58, in <module>
	from pandas.io.api import *
	File "/usr/local/lib/python3.6/site-packages/pandas/io/api.py", line 18, in <module>
	from pandas.io.packers import read_msgpack, to_msgpack
	File "/usr/local/lib/python3.6/site-packages/pandas/io/packers.py", line 68, in <module>
	from pandas.io.msgpack import Unpacker as _Unpacker, Packer as _Packer, ExtType
	File "/usr/local/lib/python3.6/site-packages/pandas/io/msgpack/__init__.py", line 22, in <module>
	from pandas.io.msgpack._packer import Packer  # noqa
	ImportError: libstdc++.so.6: cannot open shared object file: No such file or directory
	Task processing failed: Unexpected exit code [1] of container [d8b689b55311 step-30682ea550], container preserved
	involucro -v=2 -f /anaconda/lib/python3.5/site-packages/galaxy_lib-17.5.9-py3.5.egg/galaxy/tools/deps/mulled/invfile.lua -set CHANNELS='bioconda,file://anaconda/conda-bld,conda-forge,defaults' -set TEST='python -c "import GarNet"' -set TARGETS='garnet=0.4.0=py36_0' -set REPO='quay.io/biocontainers/garnet:0.4.0--py36_0' -set BINDS='build/dist:/usr/local/,/anaconda/conda-bld:/anaconda/conda-bld' build-and-test
```

**Comment by daler** [comment]
Can you try adding `libgcc` as a run dependency?

**Comment by daler** [comment]
E.g. as described here: https://bioconda.github.io/guidelines.html#c-c

**Comment by zfrenchee** [comment]
Thanks @daler. Would you like me to edit again to follow those recommendations exactly? Right now I've only added
```
  run:
    - libgcc
```
but the docs recommend
```
  build:
    - gcc   # [not osx]
    - llvm  # [osx]

  run:
    - libgcc    # [not osx]
```

**Comment by daler** [comment]
@zfrenchee I think there is ongoing discussion about how best to handle libgcc on osx. The tests are passing though, so I think it's good to go. If there are any issues reported with osx we can revisit then.

**Comment by daler** [comment]
Thanks!

**Pull request merged**
