### PR TITLE
Add bioconductor-variancepartition.

### PR DESCRIPTION
**Pull request by jdblischak**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

https://bioconductor.org/packages/release/bioc/html/variancePartition.html

### CODE REVIEW

**Comment by jdblischak** [comment]
osx build failed because r-nloptr was pulled from defaults:

https://travis-ci.org/bioconda/bioconda-recipes/jobs/305497807#L477

which leads to the error:

https://travis-ci.org/bioconda/bioconda-recipes/jobs/305497807#L409

For background on why r-nloptr is pulled from defaults:

https://github.com/conda-forge/r-bradleyterry2-feedstock/pull/1#issuecomment-343837774

**Comment by cbrueffer** [comment]
Nice! This should solve #6775 as well.

**Comment by bgruening** [comment]
@jdblischak this PR needs an update because the tarball was removed from BioC.

**Comment by jdblischak** [comment]
@bgruening I just rebased my commit on top of the current master branch and did a force push. Now that https://github.com/conda-forge/r-nloptr-feedstock/pull/4 has been merged, this should be able to pass.

> this PR needs an update because the tarball was removed from BioC.

Took me a second to understand what this meant. Looking into this now.

**Comment by bgruening** [comment]
Rerunning the skeleton generator with `--force` should be enough.

**Comment by jdblischak** [comment]
I see what happened. They bumped the version in the 3.6 release from 1.8.0 to 1.8.1.

> Rerunning the skeleton generator with --force should be enough.

@bgruening Thanks for your help! I bumped the version number and sha256, but not the build number (since this is the first time this recipe is being added).

**Comment by jdblischak** [comment]
@bgruening Tests have passed!

**Pull request merged**
