### PR TITLE
Revert "Update advntr to 1.4.0"

### PR DESCRIPTION
**Pull request by iquasere**
Reverts bioconda/bioconda-recipes#23682

### CODE REVIEW

**Comment by Jong-hun-Park** [comment]
@iquasere Hi, PR #23682 (advntr 1.4.0) failed in building artifacts or merging the PR step. Is there something that I should fix?

**Comment by iquasere** [comment]
Could it be the python restrictions? I am not able to install it with ```docker run --rm -it  continuumio/miniconda3 /bin/bash -c "conda install -y python=3.6; conda install -y -c https://118807-42372094-gh.circle-artifacts.com/0/tmp/artifacts/packages advntr"```

**Comment by Jong-hun-Park** [comment]
No, apparently it doesn't work with Python 3.7. It works with Python 3.6, though.
https://github.com/bioconda/bioconda-recipes/pull/16048#issuecomment-504689746

**Comment by iquasere** [comment]
As @dpryan79 pointed out, [the update was successfull](https://anaconda.org/bioconda/advntr), but some network issue made BiocondaBot report as an error. I will just close this pull request.

**Pull request closed without merging**
