### PR TITLE
Update vcf2variants to 1.2

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`vcf2variants`](https://bioconda.github.io/recipes/vcf2variants/README.html): **0.3** &rarr; **1.2**

[install with bioconda](http://bioconda.github.io/recipes/vcf2variants/README.html) [Conda](https://anaconda.org/bioconda/vcf2variants/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/vcf2variants`](https://github.com//bioconda/bioconda-recipes/tree/bump/vcf2variants/recipes/vcf2variants) (click to view/edit other files)
Summary | Convert vcf files to varda variant files.
Home | [https://github.com/varda/varda2_preprocessing](https://github.com/varda/varda2_preprocessing)
Releases |[https://pypi.org/pypi/vcf2variants/json](https://pypi.org/pypi/vcf2variants/json)
Recipe Maintainer(s) | @marksantcroos

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by marksantcroos** [comment]
Hi @cbrueffer, you had added the LICENSE entry. Apparently that points to a non-existing file now. Where is that supposed to live? Thanks!

**Comment by cbrueffer** [comment]
@marksantcroos my bad; I had a quick look at the repository and saw LICENSE in the root; didn't realize it's not included in the package.

**Comment by cbrueffer** [comment]
Anyway, always good to see familiar names here from other places ;-)

**Comment by marksantcroos** [comment]
FreeBSD recipe will follow shortly ;-)

**Comment by marksantcroos** [comment]
Btw, I'm a bit confused now. The state of this repo is now out of sync with my fork. Is that because of this bump mechanism?

**Comment by cbrueffer** [comment]
Which fork do you mean? The bot picked up the 1.1 update from PyPI.

**Comment by marksantcroos** [comment]
It doesn't have all the commits from my fork, it picked up the version bumps, but not the changes to the requirements.

**Comment by marksantcroos** [comment]
I manually created PR #45083, so this one can be closed I guess.

**Comment by mencian** [comment]
Closing in favor of #45083.

**Comment by marksantcroos** [comment]
Thanks @mencian!

**Comment by marksantcroos** [comment]
@mencian Out of curiosity, you actually understand what happened here?

**Pull request closed without merging**
