### PR TITLE
nudup seems to be broken

### PR DESCRIPTION
**Pull request by bgruening**
* [x] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [x] This PR does something else (explain below).

@lparsons not sure why but nudup seems to be broken

https://travis-ci.org/bioconda/bioconda-recipes/jobs/179697505

### CODE REVIEW

**Comment by lparsons** [comment]
@bgruening Hmmm... Seems like some sort of download error? Perhaps an issue with Github at the time the test was run? Will take a closer look when I get to a computer.

**Comment by lparsons** [comment]
I don't see why this would fail, except that perhaps it was due to the change in the way the file is retrieved? Doesn't seem like this should be in the blacklist though, since it does seem to build in at least some cases. Can you trigger the travis build again to test?

**Comment by daler** [comment]
#3080 fixed, I'll trigger a rebuild to see if that helps.

**Comment by bgruening** [comment]
It should not be needed. This was the first time I saw the error and thought the package is broken on master. I will close this. nudup is now online @lparsons! biocontainer as well.

**Comment by lparsons** [comment]
No problem, thanks.

**Pull request closed without merging**
