### PR TITLE
zeroc-ice: add build 2 of 3.6.3 to fix openssl issue

### PR DESCRIPTION
**Pull request by joshmoore**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [x] This PR does something else (explain below).

----------------

openssl in conda has been bumped from 1.0.2 to 1.1.1. Packages such as
zeroc-ice need to be recompiled against the new openssl version,
otherwise there is a linking error:

```
docker run -i -t continuumio/miniconda /bin/bash

conda install -c bioconda python-omero
python -c 'import omero'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/lib/python2.7/site-packages/omero/__init__.py", line 17, in <module>
    import Ice
  File "/opt/conda/lib/python2.7/site-packages/Ice.py", line 47, in <module>
    import IcePy
ImportError: libssl.so.1.0.0: cannot open shared object file: No such file or directory
```

### CODE REVIEW

**Comment by joshmoore** [comment]
openssl issue seems to have gone away without this PR. Closing.

**Comment by joshmoore** [comment]
Sorry, I was mistaken. Likely I was testing in an environment that _did_ have openssl=1.0. Without this PR, this is the workaround that's required to use Ice 3.6:

```
conda create -n omero -c bioconda -y python-omero openssl=1.0
```



see: https://trello.com/c/jdMhNkYq/84-python-omero-bioconda-package-is-broken

**Comment by joshmoore** [comment]
Currently failing with:

```
src/Operation.cpp:3733:60: error: ordered comparison between pointer and zero ('PyObject *' (aka '_object *') and 'int')
        if(PyTuple_SET_ITEM(args.get(), 0, (PyObject*)obj) < 0) // PyTuple_SET_ITEM steals a reference.
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^ ~
15 errors generated.
```

**Comment by joshmoore** [comment]
@bioconda/build-system : if anyone has a moment to help, what is the appropriate way to pin a build to the version of GCC which came before the GCC7 migration?

**Comment by dpryan79** [comment]
Theoretically you can add a `conda_build_config.yaml` with the old compilers specified. However this is generally a very bad thing to do and will prevent the package from being incorporated into conda environments with any new packages.

**Comment by dpryan79** [comment]
Closing as this should be migrated to conda-forge.

**Pull request closed without merging**
