### PR TITLE
[WIP] bioconductor update

### PR DESCRIPTION
**Pull request by daler**
* [x] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [x] This PR does something else (explain below).

This PR is to update the bioconductor packages in preparation for the May 4 bioconductor release. Three major classes of updates: 

- packages that now have entries in bioaRchive
- packages that have incremental version updates
- packages that may work on OSX but were not on the osx-whitelist when they were originally added

### CODE REVIEW

**Comment by bgruening** [comment]
Awesome! @daler do you know when 3.3 will be available?

**Comment by daler** [comment]
Hah, I was just this moment trying to figure that out. I can't find where the channel is maintained.

I've locally updated all the bioconductor packages, but bioconductor-s4vectors needs 3.3 and of course that's such a depended-upon package that lots of other things fail to build.

A tangential question for you: how are packages added to bioaRchive? A bunch of the updated packages aren't available there and so fall back to the more brittle bioconductor.org url.

**Comment by daler** [comment]
(by the way, I'm planning on creating a separate branch once 3.3 is out rather than add to this one)

**Comment by bgruening** [comment]
@daler funny, I just requested a rebuild for bioarchive :)
So this will hopefully happend today. Good to know you are working on s4vectors, I need this as well!

**Comment by bgruening** [comment]
ping @nturaga :)

**Comment by bgruening** [comment]
@daler why a separate branch? Do you plan to merge it at some point?

**Comment by nturaga** [comment]
@daler @bgruening Triggered a new build.

**Comment by daler** [comment]
@bgruening this branch has been merged and deleted already; I can restore this one if you prefer but figured I'd start fresh.

**Comment by daler** [comment]
Thanks @nturaga. Would you ping back here when the build is done?

**Comment by bgruening** [comment]
@nturaga thanks a lot!
@daler this can now take a few hours.
Now I got it. Sure you are not using this branch. I was thinking you are planning to create a complete new fort/branch for 3.3 for some reason.
Please ping me if you need help I'm interested in DESeq2 and CRISPRseek.

Thanks!

**Comment by daler** [comment]
@bgruening do you know where the conda `r` channel is maintained so we can ask about bumping to `r ==3.3`? That needs to happen first.

**Comment by bgruening** [comment]
I once tried to find it and failed, I had hoped you have some secret insights :)

**Pull request merged**
