### PR TITLE
Update seqchromloader to 0.2.4

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`seqchromloader`](https://bioconda.github.io/recipes/seqchromloader/README.html): **0.2.1** &rarr; **0.2.4**

[install with bioconda](http://bioconda.github.io/recipes/seqchromloader/README.html) [Conda](https://anaconda.org/bioconda/seqchromloader/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/seqchromloader`](https://github.com//bioconda/bioconda-recipes/tree/bump/seqchromloader/recipes/seqchromloader) (click to view/edit other files)
Summary | Sequence and chromatin dataloader for deep learning
Home | [https://github.com/yztxwd/seqchromloader](https://github.com/yztxwd/seqchromloader)
Releases |[https://pypi.org/pypi/seqchromloader/json](https://pypi.org/pypi/seqchromloader/json)
Recipe Maintainer(s) | @yztxwd

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by yztxwd** [comment]
bioconda-utils installation failed during check, seems due to it was requesting a non-existent version 1.1.2?

**Review by yztxwd — APPROVED** [review]

**Review by yztxwd — APPROVED** [review]

**Comment by yztxwd** [comment]
@BiocondaBot please merge

**Comment by dpryan79** [comment]
@BiocondaBot please fetch artifacts

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@BiocondaBot please merge

**Pull request merged**
