### PR TITLE
Add qiime to os-whitelist

### PR DESCRIPTION
**Pull request by bgruening**

### CODE REVIEW

**Comment by colinbrislawn** [comment]
Awesome! Thanks for addressing this for me.

**Comment by bgruening** [comment]
@colinbrislawn lets see if it works :)

**Comment by bgruening** [comment]
@colinbrislawn not sure this will be possible, seems that cogent is depending on `mysql-python` which is in the main channel and does not have a OS-X port.

**Comment by colinbrislawn** [comment]
So qiime can be easily built on OSX using pip and github, but not enough of its dependencies are on conda? 
:cry: Super disappointing.

**Comment by bgruening** [comment]
We will see ... I also changed the cogent dependencies as soon as it turns green we are ready to go :)

**Comment by johanneskoester** [comment]
We can have our own copy of the mysql-python recipe and in parallel vote for an osx build in the main channel.

**Comment by colinbrislawn** [comment]
:+1: Thanks for helping us out.
Qiime has heaps of dependencies, so I really appreciate your support with this.

**Comment by bgruening** [comment]
@johanneskoester any idea what is causing this error? `ValueError: numpy.dtype has the wrong size, try recompiling`. It's working on Linux :(
Do we need/want to use `numpy x.x` everywhere?

**Comment by johanneskoester** [comment]
We should use numpy x.x whenever a package depends on the ABI of numpy. When just using the numpy Python interface, this is not necessary. However, the error you mention really suggests some ABI incompatibility. For me, the only explanation is that qiime compiles something agains numpy and comes with pre-build binary modules, that are build against a particular numpy version.

**Comment by bgruening** [comment]
But this would not explain why it runs under Linux, isn't it? Or does anaconda use different versions of numpy on OS-X and Linux by default?

**Comment by johanneskoester** [comment]
I don't think so, but it could be that the osx version of the binaries delivered with the package require a different numpy version than the linux version of the binaries.

**Comment by colinbrislawn** [comment]
I have deployed the qiime pipeline on OSX using conda for most packages and pipe for qiime itself. When installing qiime with pip, you get
```
                  NumPy version:	1.10.4
...
                Emperor version:	0.9.51
```
This should (hopefully) address the current built failure.

**Comment by colinbrislawn** [comment]
It's annoying that qiime 1.9.1 is a bit behind the current builds of these packages. Here is the dependances which work on my system:

```
          QIIME library version:	1.9.1
           QIIME script version:	1.9.1
qiime-default-reference version:	0.1.3
                  NumPy version:	1.10.4
                  SciPy version:	0.16.1
                 pandas version:	0.17.1
             matplotlib version:	1.5.1
            biom-format version:	2.1.5
                   h5py version:	2.5.0 (HDF5 version: 1.8.15)
                   qcli version:	0.1.1
                   pyqi version:	0.3.2
             scikit-bio version:	0.2.3
                 PyNAST version:	1.2.2
                Emperor version:	0.9.51
                burrito version:	0.9.1
       burrito-fillings version:	0.1.1
              sortmerna version:	SortMeRNA version 2.0, 29/11/2014
              sumaclust version:	SUMACLUST Version 1.0.00
                  swarm version:	Swarm 1.2.19 [Jan 19 2016 11:13:30]
                          gdata:	Installed.
```

**Comment by bgruening** [comment]
I guess I have it!
@johanneskoester can you please look at it. I needed to change many things, not sure about all of them. Also I can not merge it because there is an additional travis test (for win?) that is failing?

**Comment by johanneskoester** [comment]
That appveyor stuff was a test of mine. Yes, it is about win builds, but I did not set it up properly so far. I have deactivated it for now. The recipes look good, but there seems to be a merge conflict.

**Comment by bgruening** [comment]
@johanneskoester rebased and merged! Thanks hopefully this is now working.

**Comment by bgruening** [comment]
@colinbrislawn can you please test the OS-X build?

**Comment by colinbrislawn** [comment]
Thanks for this @bgruening! 

Build works well!

Some of the programs and dependences are slightly different from pip+github. Here are the relevant differences from a `git diff` of their log files:

```
--- a/qiime-conda-log.txt
+++ b/qiime-git-log.txt

-                  SciPy version:       0.17.0
+                  SciPy version:       0.16.1
-                   h5py version:       Not installed.
+                   h5py version:       2.5.0 (HDF5 version: 1.8.15)
-              sumaclust version:       Not installed.
+              sumaclust version:       SUMACLUST Version 1.0.00
```

- SciPy is probably OK. We could ask @gregcaporaso
- We probably don't need sumaclust (it's not a default and superseded by vsearch and SortMeRNA)
- **We totally need h5py for biom v2.1 support!** (But it's already on conda :wink:)

**Comment by bgruening** [comment]
@colinbrislawn h5py should then be a dependency of biom package, correct?

**Comment by gregcaporaso** [comment]
h5py is an optional dependency of biom. Everything will function ok in a closed environment without it, but if users try to bring in hdf5-formatted biom files from elsewhere, they won't be able to work with them unless h5py is installed. I think it's probably ok to not include, but have users install if they want to work with these files (as @colinbrislawn notes, it's really easy to install with conda). 

The SciPy version should be fine.

**Comment by bgruening** [comment]
@gregcaporaso: How does look for you: https://github.com/bioconda/bioconda-recipes/pull/992

**Comment by gregcaporaso** [comment]
That looks right, but I haven't written a lot of these recipes.

**Comment by bgruening** [comment]
@gregcaporaso merged!

**Comment by gregcaporaso** [comment]
Excellent, thanks again for the work on this. I'll try it out today.

**Comment by colinbrislawn** [comment]
Looks great! Thanks for building this!

**Pull request merged**
