### PR TITLE
fix blast 2.2.21 recipe

### PR DESCRIPTION
**Pull request by rvalieris**
* [x] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

try to fix the blast error from #3537

### CODE REVIEW

**Comment by druvus** [comment]
Maybe it is easier to copy latest recipe (2.6.0) to 2.2.21 folder?

**Comment by rvalieris** [comment]
the build is now failing because libbz2.so.1 is missing, the problem is that the bzip2 package does not ship the shared version of the library.

I wonder if ./configure is smart enough to avoid needing bzip2.. I will try that.

**Comment by rvalieris** [comment]
now I got a unrelated compilation error, I guess its best to just wait for the bzip2 package to land on conda-forge: https://github.com/conda-forge/staged-recipes/pull/1977

**Comment by marcelm** [comment]
Please also see the discussion at #3020

**Comment by johanneskoester** [comment]
We have migrated our build system from Travis CI to Circle CI. If you would like to continue working on this PR, please update with latest upstream master and reopen this PR.

**Pull request closed without merging**
