### PR TITLE
Update medaka to 1.10.0

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`medaka`](https://bioconda.github.io/recipes/medaka/README.html): **1.8.0** &rarr; **1.10.0**

[install with bioconda](http://bioconda.github.io/recipes/medaka/README.html) [Conda](https://anaconda.org/bioconda/medaka/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/medaka`](https://github.com//bioconda/bioconda-recipes/tree/bump/medaka/recipes/medaka) (click to view/edit other files)
Summary | Neural network sequence error correction.
Home | [https://github.com/nanoporetech/medaka](https://github.com/nanoporetech/medaka)
Releases |[https://pypi.org/pypi/medaka/json](https://pypi.org/pypi/medaka/json)
Recipe Maintainer(s) | @cjw85

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Review by cjw85 — APPROVED** [review]

**Comment by cjw85** [comment]
Before anyone asks, I have little idea what is the problem here. I would hazard a guess that its some shenanigans with conda-forge packages.

**Comment by BioWilko** [comment]
@cjw85 I'm running into the same issue trying to bump the medaka version to >= 1.8.0 in the bioconda artic fieldbioinformatics version weirdly...

**Comment by cjw85** [comment]
The build error is:

```
The reported errors are:
- Encountered problems while solving:
-   - nothing provides __cuda needed by tensorflow-2.8.0-cuda102py310hcf4adbc_0
-
```

I'm not up to date on how packages that require tensorflow can be built sucessfully under conda. One of the core maintainers will have to advise.

Oxford Nanopore Technologies provides various flavours of manylinux wheels on PyPI:
https://pypi.org/project/medaka/#files
https://pypi.org/project/medaka-cpu/#files

**Comment by cjw85** [comment]
I've bumped the TF package version, only to match the PyPI package not because I know that it will help. If it doesn't help I have no idea what to try to get a successful build. I also do not have the time to debug the situation. 

Users wishing to use the latest versions of medaka should install from PyPI.

**Comment by BioWilko** [comment]
I've done a bunch of searching and still have no real clue, apparently setting `CONDA_OVERRIDE_CUDA` as an env var can override the __cuda virtual package and allow GPU packages to be built on a CPU only machine but it doesn't seem to work in this case....

I may have to consider speccing out distributing fieldbioinformatics in the same way you guys are distributing medaka since this is starting to feel unsustainable

**Comment by cjw85** [comment]
Things even go awry when explicitely requesting `tensorflow-cpu`:

```The reported errors are:
- Encountered problems while solving:
-   - package tensorflow-cpu-2.10.0-cpu_py310h718b53a_0 requires tensorflow 2.10.0 cpu_py310hd1aba9c_0, but none of the providers can be installed
-
```

**Comment by BioWilko** [comment]
> package tensorflow-cpu-2.10.0-cpu_py310h718b53a_0 requires tensorflow 2.10.0 cpu_py310hd1aba9c_0

oh dear

**Comment by cjw85** [comment]
@incoherentian
Contrary to what you suggested in https://github.com/bactopia/bactopia/issues/432#issuecomment-1714658921, the issue here is not simply the update to tensorflow. The same symptom occurred when I simply tried to rebuild with the previously working build requirements. The updates to tensorflow were (in part) an attempt to get things working more smoothly here.

Good luck!

**Comment by incoherentian** [comment]
Hi Chris! Thanks for the mention RE:
> the issue here is not simply the update to tensorflow

I had meant to present a different angle than I clearly did with this:
> medaka v1.9.1 (or any v1.8.2+) saw some tensorflow changes which might™️(?) impact keras-relevant dependency conflicts.

I wasn't supposing that tensorflow changes were the issue, but that updates to tensorflow from 1.8.2+ _may_ help resolve conflicts when building environments with medaka - if only 1.9.1 would pass muster. Getting there is something I don't envy as anyone's task, as the results of your efforts e.g. 
> package tensorflow-cpu-2.10.0-cpu_py310h718b53a_0 requires tensorflow 2.10.0 cpu_py310hd1aba9c_0, but none of the providers can be installed

seeems pretty nonsensical and a not-terribly-useful starting (or mid-) point for resolving build failures. Fortunately better men than I are about and planning to take a look!

**Comment by rpetit3** [comment]
Playing around some on my end, looks like the failure is happening while testing within docker container. outside of the docker container it works fine.

Will look into this further

**Comment by rpetit3** [comment]
Ok, looks related to boa in some way. I'm abe to build this successfully with `conda build` and `mamba build`, but not using boa via `conda mambabuild` , which is how the packages are build using the CI.

Will update soon

**Comment by BioWilko** [comment]
Thanks for getting in on this @rpetit3! It's also preventing fieldbioinformatics from building and I couldn't figure it out for the life of me....

**Comment by incoherentian** [comment]
Awe https://dev.azure.com/bioconda/bioconda-recipes/_build/results?buildId=41629&view=logs&j=e14e69ff-a0ae-55c4-b71d-229b239cfb2f&t=4dddc55b-10bc-50fc-ac68-7ff899b7a030&l=1212

Amateur hour ("my") thoughts on this:

Medaka guys love pypi + AFAIK telling everyone that all paths lead to running medaka (a polisher!) in its own env.

I'm assuming an air gap server isn't specified because there's no air on the dark side of the moon :p 

tensorflow~=2.10.0 specified (https://github.com/nanoporetech/medaka/blob/938167e2ff804899d578d04388ba5c15ab339316/requirements.txt) 
which would probably equate to 2.10.1 in pypi https://pypi.org/project/tensorflow-cpu/2.10.1/ &/or https://pypi.org/project/tensorflow/2.10.1/ 

If using 2.10.1 (or 2.10.0) I'm not sure if it is OK to pin (or allow) one instead of the other despite just being a bunch of vulnerability fixes (https://github.com/tensorflow/tensorflow/releases/tag/v2.10.1); it wouldn't be unheard of for such changes to unexpectedly throw models off because... tensorflow voodoo? Meanwhile I don't know that 2.10.1 exists anywhere on conda... 
<details>

  <summary>conda search</summary>

```
[user@cl2(hawk) dragonflye_m180]$ conda search tensorflow-cpu=2.10.0 --info
Loading channels: done
tensorflow-cpu 2.10.0 cpu_py310h718b53a_0
-----------------------------------------
file name   : tensorflow-cpu-2.10.0-cpu_py310h718b53a_0.tar.bz2
name        : tensorflow-cpu
version     : 2.10.0
build       : cpu_py310h718b53a_0
build number: 0
size        : 28 KB
license     : Apache-2.0
subdir      : linux-64
url         : https://conda.anaconda.org/conda-forge/linux-64/tensorflow-cpu-2.10.0-cpu_py310h718b53a_0.tar.bz2
md5         : 738e59b0d76e25092d7090b9c0106ad3
timestamp   : 2022-09-23 18:26:47 UTC
dependencies:
  - tensorflow 2.10.0 cpu_py310hd1aba9c_0


tensorflow-cpu 2.10.0 cpu_py37h718b53a_0
----------------------------------------
file name   : tensorflow-cpu-2.10.0-cpu_py37h718b53a_0.tar.bz2
name        : tensorflow-cpu
version     : 2.10.0
build       : cpu_py37h718b53a_0
build number: 0
size        : 28 KB
license     : Apache-2.0
subdir      : linux-64
url         : https://conda.anaconda.org/conda-forge/linux-64/tensorflow-cpu-2.10.0-cpu_py37h718b53a_0.tar.bz2
md5         : 1a11b6b03417ef77870574817e652aa1
timestamp   : 2022-09-23 17:59:59 UTC
dependencies:
  - tensorflow 2.10.0 cpu_py37h08536eb_0


tensorflow-cpu 2.10.0 cpu_py38h718b53a_0
----------------------------------------
file name   : tensorflow-cpu-2.10.0-cpu_py38h718b53a_0.tar.bz2
name        : tensorflow-cpu
version     : 2.10.0
build       : cpu_py38h718b53a_0
build number: 0
size        : 28 KB
license     : Apache-2.0
subdir      : linux-64
url         : https://conda.anaconda.org/conda-forge/linux-64/tensorflow-cpu-2.10.0-cpu_py38h718b53a_0.tar.bz2
md5         : 0efd50521fa69e41958f4f0b9db0cd2e
timestamp   : 2022-09-23 18:53:58 UTC
dependencies:
  - tensorflow 2.10.0 cpu_py38h66f0ec1_0


tensorflow-cpu 2.10.0 cpu_py39h718b53a_0
----------------------------------------
file name   : tensorflow-cpu-2.10.0-cpu_py39h718b53a_0.tar.bz2
name        : tensorflow-cpu
version     : 2.10.0
build       : cpu_py39h718b53a_0
build number: 0
size        : 28 KB
license     : Apache-2.0
subdir      : linux-64
url         : https://conda.anaconda.org/conda-forge/linux-64/tensorflow-cpu-2.10.0-cpu_py39h718b53a_0.tar.bz2
md5         : e2dace1c22535c3d95e395519b01e78e
timestamp   : 2022-09-23 17:33:03 UTC
dependencies:
  - tensorflow 2.10.0 cpu_py39h4655687_0


[user@cl2(hawk) dragonflye_m180]$ conda search tensorflow-cpu=2.10.1 --info
Loading channels: done
No match found for: tensorflow-cpu=2.10.1. Search: *tensorflow-cpu*=2.10.1

PackagesNotFoundError: The following packages are not available from current channels:

  - tensorflow-cpu=2.10.1

Current channels:

  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

&/or

```
[user@cl2(hawk) dragonflye_m180]$ conda search tensorflow=2.10.0 --info
Loading channels: done
tensorflow 2.10.0 cpu_py310hd1aba9c_0
-------------------------------------
file name   : tensorflow-2.10.0-cpu_py310hd1aba9c_0.tar.bz2
name        : tensorflow
version     : 2.10.0
build       : cpu_py310hd1aba9c_0
build number: 0
size        : 29 KB
license     : Apache-2.0
subdir      : linux-64
url         : https://conda.anaconda.org/conda-forge/linux-64/tensorflow-2.10.0-cpu_py310hd1aba9c_0.tar.bz2
md5         : aa4fc26a778ea22a7d3369ed98449cd0
timestamp   : 2022-09-23 18:26:43 UTC
track_features:
  - tensorflow-cpu
dependencies:
  - python >=3.10,<3.11.0a0
  - python_abi 3.10.* *_cp310
  - tensorflow-base 2.10.0 cpu_py310hc537a0e_0
  - tensorflow-estimator 2.10.0 cpu_py310had6d012_0


tensorflow 2.10.0 cpu_py37h08536eb_0
------------------------------------
file name   : tensorflow-2.10.0-cpu_py37h08536eb_0.tar.bz2
name        : tensorflow
version     : 2.10.0
build       : cpu_py37h08536eb_0
build number: 0
size        : 29 KB
license     : Apache-2.0
subdir      : linux-64
url         : https://conda.anaconda.org/conda-forge/linux-64/tensorflow-2.10.0-cpu_py37h08536eb_0.tar.bz2
md5         : 9be2dabf5749dba82e637c84e882d554
timestamp   : 2022-09-23 17:59:54 UTC
track_features:
  - tensorflow-cpu
dependencies:
  - python >=3.7,<3.8.0a0
  - python_abi 3.7.* *_cp37m
  - tensorflow-base 2.10.0 cpu_py37h50bd216_0
  - tensorflow-estimator 2.10.0 cpu_py37h813ee39_0


tensorflow 2.10.0 cpu_py38h66f0ec1_0
------------------------------------
file name   : tensorflow-2.10.0-cpu_py38h66f0ec1_0.tar.bz2
name        : tensorflow
version     : 2.10.0
build       : cpu_py38h66f0ec1_0
build number: 0
size        : 29 KB
license     : Apache-2.0
subdir      : linux-64
url         : https://conda.anaconda.org/conda-forge/linux-64/tensorflow-2.10.0-cpu_py38h66f0ec1_0.tar.bz2
md5         : 54db9306df4a2890fb0577d87a3c8086
timestamp   : 2022-09-23 18:53:54 UTC
track_features:
  - tensorflow-cpu
dependencies:
  - python >=3.8,<3.9.0a0
  - python_abi 3.8.* *_cp38
  - tensorflow-base 2.10.0 cpu_py38h67fe383_0
  - tensorflow-estimator 2.10.0 cpu_py38h4e23bc6_0


tensorflow 2.10.0 cpu_py39h4655687_0
------------------------------------
file name   : tensorflow-2.10.0-cpu_py39h4655687_0.tar.bz2
name        : tensorflow
version     : 2.10.0
build       : cpu_py39h4655687_0
build number: 0
size        : 29 KB
license     : Apache-2.0
subdir      : linux-64
url         : https://conda.anaconda.org/conda-forge/linux-64/tensorflow-2.10.0-cpu_py39h4655687_0.tar.bz2
md5         : 0ae82ffb2534dc2b6cddd751e0f6355c
timestamp   : 2022-09-23 17:32:58 UTC
track_features:
  - tensorflow-cpu
dependencies:
  - python >=3.9,<3.10.0a0
  - python_abi 3.9.* *_cp39
  - tensorflow-base 2.10.0 cpu_py39h16601f7_0
  - tensorflow-estimator 2.10.0 cpu_py39heaff504_0


tensorflow 2.10.0 cuda112py310he87a039_0
----------------------------------------
file name   : tensorflow-2.10.0-cuda112py310he87a039_0.tar.bz2
name        : tensorflow
version     : 2.10.0
build       : cuda112py310he87a039_0
build number: 0
size        : 29 KB
license     : Apache-2.0
subdir      : linux-64
url         : https://conda.anaconda.org/conda-forge/linux-64/tensorflow-2.10.0-cuda112py310he87a039_0.tar.bz2
md5         : c667ef0245f219cecd96ec508bfbf0bf
timestamp   : 2022-09-15 02:49:31 UTC
dependencies:
  - __cuda
  - python >=3.10,<3.11.0a0
  - python_abi 3.10.* *_cp310
  - tensorflow-base 2.10.0 cuda112py310hf679b68_0
  - tensorflow-estimator 2.10.0 cuda112py310h2fa73eb_0


tensorflow 2.10.0 cuda112py37h01c6645_0
---------------------------------------
file name   : tensorflow-2.10.0-cuda112py37h01c6645_0.tar.bz2
name        : tensorflow
version     : 2.10.0
build       : cuda112py37h01c6645_0
build number: 0
size        : 29 KB
license     : Apache-2.0
subdir      : linux-64
url         : https://conda.anaconda.org/conda-forge/linux-64/tensorflow-2.10.0-cuda112py37h01c6645_0.tar.bz2
md5         : 2fe3b50e2f257b5ff0b30de3644d7c0b
timestamp   : 2022-09-23 20:43:16 UTC
dependencies:
  - __cuda
  - python >=3.7,<3.8.0a0
  - python_abi 3.7.* *_cp37m
  - tensorflow-base 2.10.0 cuda112py37ha0c8746_0
  - tensorflow-estimator 2.10.0 cuda112py37h25bb9bc_0


tensorflow 2.10.0 cuda112py38hded6998_0
---------------------------------------
file name   : tensorflow-2.10.0-cuda112py38hded6998_0.tar.bz2
name        : tensorflow
version     : 2.10.0
build       : cuda112py38hded6998_0
build number: 0
size        : 29 KB
license     : Apache-2.0
subdir      : linux-64
url         : https://conda.anaconda.org/conda-forge/linux-64/tensorflow-2.10.0-cuda112py38hded6998_0.tar.bz2
md5         : 551c41fd592795ac10898e79859133ad
timestamp   : 2022-09-23 21:38:31 UTC
dependencies:
  - __cuda
  - python >=3.8,<3.9.0a0
  - python_abi 3.8.* *_cp38
  - tensorflow-base 2.10.0 cuda112py38h6b2b66c_0
  - tensorflow-estimator 2.10.0 cuda112py38hf5dcc89_0


tensorflow 2.10.0 cuda112py39h01bd6f0_0
---------------------------------------
file name   : tensorflow-2.10.0-cuda112py39h01bd6f0_0.tar.bz2
name        : tensorflow
version     : 2.10.0
build       : cuda112py39h01bd6f0_0
build number: 0
size        : 29 KB
license     : Apache-2.0
subdir      : linux-64
url         : https://conda.anaconda.org/conda-forge/linux-64/tensorflow-2.10.0-cuda112py39h01bd6f0_0.tar.bz2
md5         : 8db1a1484a251d78a3dc8ebb718f6fd5
timestamp   : 2022-09-23 19:47:35 UTC
dependencies:
  - __cuda
  - python >=3.9,<3.10.0a0
  - python_abi 3.9.* *_cp39
  - tensorflow-base 2.10.0 cuda112py39h2957820_0
  - tensorflow-estimator 2.10.0 cuda112py39hd320b7a_0


[user@cl2(hawk) dragonflye_m180]$ conda search tensorflow=2.10.1 --info
Loading channels: done
No match found for: tensorflow=2.10.1. Search: *tensorflow*=2.10.1

PackagesNotFoundError: The following packages are not available from current channels:

  - tensorflow=2.10.1

Current channels:

  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

</details>

Is it possible that one missing secret sauce ingredient is a conversion of tensorflow 2.10.1 pypi to conda?

**Comment by rpetit3** [comment]
@cjw85 how critical is tensorflow 2.10.*? 

I tried to build with 2.11.*, and it builds successfully. If its critical, I can look into @incoherentian suggestion of getting 2.10.1 onto conda-forge.

Here are release notes for 2.11. I did notice as of 2.11, `tensorflow-cpu` will likely be necessary

https://github.com/tensorflow/tensorflow/releases/tag/v2.11.1
https://github.com/tensorflow/tensorflow/releases/tag/v2.11.0

**Comment by rpetit3** [comment]
@BiocondaBot please fetch artifacts

**Comment by cjw85** [comment]
Medaka is untested with TF 2.11

**Comment by rpetit3** [comment]
I'm aware. Should I assume this to mean, no to 2.11, and yes to pursuing getting 2.10.1 onto conda-forge?

**Comment by rpetit3** [comment]
@BiocondaBot please fetch artifacts

**Comment by rpetit3** [comment]
@BiocondaBot please fetch artifacts

**Comment by rpetit3** [comment]
@BiocondaBot please fetch artifacts

**Comment by rpetit3** [comment]
Hi all, especially @cjw85,

I reached out to the Tensorflow feedstock about getting a v2.10.1 built, but it's likely not worth the effort. Instead I decided to use the tests built into Medaka to test alternative versions of Tensorflow. 

To address this I submitted a PR (https://github.com/nanoporetech/medaka/pull/461) to the main Medaka repo which adds a Github Action to easily test Medaka on multiple versions of Python (3.8-3.10) and Tensorflow (2.8-2.12). This GHA uses the tests available from Medaka's `make test` and assumes they are sufficient enough to test Medaka is working as expected. Here is an example run of the GHA: https://github.com/rpetit3/medaka/actions/runs/6398866670/job/17369898556

Based on the passing of Medaka's tests, I would like to loosen the pinning for Tensorflow for the time being. Once Medaka officially supports Tensorflow 2.11+, we can likely re-pin to match the upstream `requirements.txt`.

If anyone has an issue with this plan, please go ahead and voice it.

Cheers,
Robert

**Comment by rpetit3** [comment]
@biocondabot please fetch artifacts

**Comment by rpetit3** [comment]
Hi all, 

The Github Action tests utilized in previous comment were not sufficient in the context of differing Python and Tensorflow versions. See the PR comment for more details, but in short ONT does internal testing before code is made available on Github. Since suitable testing is not publicly available, I decided to test differing versions of Tensorflow (TF) in my use case, Dragonflye, which includes an optional polishing step with Medaka. 

I assembled a multiple genomes, and saw no significant difference between Medaka 1.8.0 and Medaka 1.9.1 (pip or conda). The differences seen were likely do to random subsampling of reads, assembly sizes were all within base pairs of one another. For Medaka 1.9.1, I compared the Pip install with TF 2.10 (supported) against a Conda install with TF 2.11 (unsupported).

```
# Test currently Dragonflye, using Medaka 1.8.1
mamba create -n test-dragonflye-m180 -c conda-forge -c bioconda dragonflye

dragonflye --version
dragonflye 1.1.1

medaka --version
medaka 1.8.0

python -c 'import tensorflow as tf; print(tf.__version__)'
2.8.1

# Test Dragonflye using Medaka 1.9.1 (conda)
mamba create -n test-dragonflye-m191 -c rpetit3 -c conda-forge -c bioconda dragonflye 'medaka==1.9.1'
conda activate test-dragonflye-m191
dragonflye --version
dragonflye 1.1.1

medaka --version
medaka 1.9.1

python -c 'import tensorflow as tf; print(tf.__version__)'
2.11.1

# Test Dragonflye using Medaka 1.9.1 (pip)
mamba create -n test-dragonflye-m191pip -c conda-forge -c bioconda dragonflye pip setuptools
conda activate test-dragonflye-m191pip
pip install medaka==1.9.1

dragonflye --version
dragonflye 1.1.1

medaka --version
Cannot import pyabpoa, some features may not be available.
medaka 1.9.1

python -c 'import tensorflow as tf; print(tf.__version__)'
2.10.1
```

@BioWilko - if you would like to test the conda build of v1.9.1, I have made it available on my personal channel (`-c rpetit3`). Otherwise, feel free to build the artifacts for Conda or Docker.

@cjw85 - I have added a post-link message to relay to users that ONT does not support the bioconda package, and related issues should be reported to bioconda-recipes (I suspect they won't). Otherwise to see your docs for supported installation methods. Please feel free to adjust the language in the post-link.

In the future, if Medaka adds support for TF 2.11, this likely will not be an issue and the recipe can go back minor release pinning of TF.

Thank you everyone,
Robert

**Comment by mbargull** [comment]
You could add a `conda_build_config.yaml` to the recipe to override the default pinning with
```yaml
# <comment saying this is not ideal, will cause installation of outdated packages and introduce compatibility issues later>
curl:
  - 7
openssl:
  - 1.1.1
```
. That way the build can pull in the outdated `tensorflow` package and those dependency conflicts will be resolved.
Expect this to fail/conflict with other pinnings in the future (but maybe upstream will support newer TensorFlow by then...).

**Comment by rpetit3** [comment]
Thank you very much for the suggestion @mbargull ! Linux is passing, just doing some testing with htslib now on osx

**Comment by mbargull** [comment]
AFAICT, the first `htslib>=1.17` for `osx-64` was already built against `libcurl=7.88.1` which was actually the first version after conda-forge switched to building against OpenSSL 3-only.
Meaning, for the recipe's custom pinning to work, the options here are
1. Loosen the `samtools`/`bcftools` requirements to `>=1.16` (at least for `osx`).
2. Skip `osx-64` builds.
3. Issue a new `htslib>=1.17` against OpenSSL 1.1.1 (in addition to the OpenSSL 3 one, of course).

If the first option is possible, that on is preferable, of course.

**Comment by rpetit3** [comment]
based on docs, I think we can loosen to >=1.14 

> samtools/bgzip/tabix version 1.14 and minimap2 version 2.17 are recommended as these are those used in development of medaka. (Newer versions are almost certainly fine).

https://github.com/nanoporetech/medaka#installation

**Comment by rpetit3** [comment]
@BiocondaBot please fetch artifacts

**Comment by rpetit3** [comment]
Hi all, 

Thanks to the wizardry of @mbargull I think we are all set here. All versions in spec to Medaka. 

If there are no complaints, this can be merged

Cheers, and thanks again @mbargull!

**Comment by rpetit3** [comment]
No complaints, merging

**Pull request merged**
