### PR TITLE
Update LINKS meta.yaml recipe

### PR DESCRIPTION
**Pull request by warrenlr**
**Replace this sentence with a detailed description of your pull request**

----

> Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences**
      (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

> Everyone has access to the following BiocondaBot commands, which can be given in a comment:
>
>  * `@BiocondaBot please update` will cause the BiocondaBot to merge the master branch into a PR
>  * `@BiocondaBot please add label` will add the `please review & merge` label.
>  * `@BiocondaBot please fetch artifacts` will post links to packages and docker containers built by the CI system. You can use this to test packages locally before merging.
>
> For members of the Bioconda project, the following command is also available:
>
>  * `@BiocondaBot please merge` will cause packages/containers to be uploaded and a PR merged. Someone must approve a PR first! This has the benefit of not wasting CI build time required by manually merging PRs.
>
> If you have questions, please post them in gitter or ping `@bioconda/core` in a comment (if you are not able to directly ping `@bioconda/core` then the bot will repost your comment and enable pinging).

### CODE REVIEW

**Comment by warrenlr** [comment]
hmm not too sure how to do that.  the ```links.patch``` has nothing that is version specific.. please advise

**Comment by acaprez** [comment]
Ah, ok.  It looks like you need to use the [this tarball](https://github.com/bcgsc/LINKS/releases/download/v1.8.7/links_v1-8-7.tar.gz) instead.  The other one doesn't seem to include everything the previous version's tarball did, and the `LINKS` script is in a different location (which is why `patch` failed).

**Comment by acaprez** [comment]
After playing a little more with this, there are a couple other changes needed for it to build.  It actually needs a C++ compiler (not a C one) so change `{{ compiler('c') }}` to `{{ compiler('cxx') }}` in `meta.yaml`.  The compiler lines in `build.sh` need a bit of tweaking for the newer compilers as well.  Change the two `g++` lines to instead read

```
${CXX} -c BloomFilter_wrap.cxx -I$PERL5DIR/CORE -fPIC -O3
${CXX} -Wall -shared BloomFilter_wrap.o -o BloomFilter.so -O3
```
It built ok for me then with those changes and the other tarball.

**Comment by warrenlr** [comment]
ok I made edits to build.sh under PR #19892

**Comment by acaprez** [comment]
You'll need to make all the changes in this branch.  The `meta.yaml` and `build.sh` files need to be updated simultaneously in this case.

**Comment by warrenlr** [comment]
Great, thank you @acaprez !!

**Comment by acaprez** [comment]
@BiocondaBot please merge

**Pull request merged**
