### PR TITLE
Bumped GATK4 version

### PR DESCRIPTION
**Pull request by micknudsen**
* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [X] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [X] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by micknudsen** [comment]
Does anybody know what to make of this error? To me it looks more Docker related than GATK4 related.

```
07:21:38 BIOCONDA INFO BUILD START recipes/gatk4, env: CONDA_ALLOW_SOFTLINKS=false;CONDA_BOOST=1.64;CONDA_BZIP2=1.0;CONDA_GMP=5.1;CONDA_GSL=1.16;CONDA_HDF5=1.8.17;CONDA_HTSLIB=1.6;CONDA_NCURSES=5.9;CONDA_NPY=112;CONDA_PERL=5.22.0;CONDA_PY=35;CONDA_R=3.4.1;CONDA_ROOT=/anaconda;CONDA_XZ=5.2;CONDA_ZLIB=1.2.8;LANG=en_US.UTF-8;LC_ALL=en_US.UTF-8;LC_CTYPE=en_US.UTF-8;MACOSX_DEPLOYMENT_TARGET=10.9
..07:23:03 BIOCONDA ERROR COMMAND FAILED: docker run --net host --rm -v /tmp/tmpgbr8dgzs/build_script.bash:/opt/build_script.bash -v /anaconda/conda-bld:/opt/host-conda-bld -v /home/travis/build/bioconda/bioconda-recipes/recipes/gatk4:/opt/recipe -e CONDA_BZIP2=1.0 -e CONDA_PY=35 -e CONDA_ZLIB=1.2.8 -e LC_ALL=en_US.UTF-8 -e CONDA_GSL=1.16 -e CONDA_HDF5=1.8.17 -e CONDA_NPY=112 -e LANG=en_US.UTF-8 -e CONDA_HTSLIB=1.6 -e CONDA_ROOT=/anaconda -e CONDA_PERL=5.22.0 -e MACOSX_DEPLOYMENT_TARGET=10.9 -e CONDA_ALLOW_SOFTLINKS=false -e CONDA_NCURSES=5.9 -e CONDA_R=3.4.1 -e LC_CTYPE=en_US.UTF-8 -e CONDA_XZ=5.2 -e CONDA_BOOST=1.64 -e CONDA_GMP=5.1 tmp-bioconda-builder /bin/bash /opt/build_script.bash
07:23:03 BIOCONDA ERROR STDOUT+STDERR:
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
mkdir: cannot create directory `/opt/host-conda-bld/noarch': Permission denied
```

**Comment by druvus** [comment]
It is an unrelated to you PR. See @daler answer at #7237

**Comment by chapmanb** [comment]
FYI, in addition to the current bioconda build issue, this will need a fix as the `gatk-launch` script got renamed in the release, to just `gatk`. The problem with this is that our `gatk` package for GATK3 uses a `gatk` named script so they'd conflict. I'd suggest copying over the `gatk` script in 4.0.0.0 to `gatk-launch` and using the back compatible name for now and we can decide if we want to do something like rename `gatk` to `gatk3` and keep the default package script naming.

Do you want to make use of the spark Jar for gatk? It adds another 150Mb to the package size which is why I'd left it out. Local spark execution works with just the local jar, and the spark one is only required for a spark cluster. At this point I assumed most users would want just the local one and folks using spark might have a custom solution.

**Comment by micknudsen** [comment]
@chapmanb Thanks for your input. I must admit that I know very little about Spark. Just thought that it was was needed in order to run GATK in multi-core mode (something about a new implementation of how the `-nct` and `-nt` options work). I will remove Spark again, and I will also implement your suggestion about `gatk-launch`.

**Comment by chapmanb** [comment]
Nice one, thanks. The spark jar is only needed for running distributed on a Spark cluster, and the local jar includes everything needed to run multicore on a single machine. We've been using this during the betas for multicore processing and it's a nice replacement for the nct/nt options.

**Comment by bgruening** [comment]
Restarted the tests.

**Comment by chapmanb** [comment]
Nice work, thanks Michael for updating and Bjorn for rebooting this after the fixes.

**Comment by micknudsen** [comment]
Hi @chapmanb. I have now had time to play around with GATK 4.0.0.0 (the bioconda-version without Spark), and I am confused by your comment:

> The spark jar is only needed for running distributed on a Spark cluster, and the local jar includes everything needed to run multicore on a single machine.

It looks like multicore support is gone. Just as an example,`gatk-launch BaseRecalibrator --help` shows nothing related to multicore support. Now that the `-nct` and `-nt` options are gone, how do you run on multiple cores without Spark?

**Comment by chapmanb** [comment]
Michael;
Sorry for the confusion. Local multicore does use Spark but has everything is needs in the local jar. You need to use the Spark enabled versions of programs and pass `--spark-master local` with the cores to use. For your example, to run with 16 cores you'd do:
```
gatk-launch BaseRecalibratorSpark --spark-master local[16]
```
Hope this helps.

**Comment by micknudsen** [comment]
Thank you so much, @chapmanb. Works like a charm! I spent a considerable amount of time browsing the GATK documentation for information about this functionality. Maybe I was just looking the wrong place.

**Pull request merged**
