### PR TITLE
Issues with ale bioconda package /Add ale-core as alternative if it can be fixed

### PR DESCRIPTION
**Pull request by gbouras13**
Describe your pull request here

The bioconda installation of ALE (https://github.com/sc932/ALE) is broken

When you try and install ALE as follows:

`conda install -c bioconda ale`

v0.9.1 is downloaded but nothing is actually installed (i.e. ALE isn't actually executable).

If you try and specifically install the last update, it requires a deprecated version of matplotlib.:

```
conda install -c bioconda ale==20180904
```

```
The following package could not be installed
└─ ale 20180904  is uninstallable because it requires
   └─ pymix  , which requires
      └─ matplotlib >=1.1.0,!=1.4.2,<1.5.0 , which does not exist (perhaps a missing channel).
```

I don't know enough about the conda ecosystem to know how easy it is easier to fix this error.

However, for my own (and I imagine others') purpose, the core C scoring program is what is needed, not the 10+ year old plotting  scripts.

Hence I propose adding `ale-core` which just includes the ALE and synthReadGen executables implemented in C.

If this is  suboptimal or potentially confusing, then it would be great to find a way to make ALE work with bioconda in the existing implementation. I don't know the ecosystem well enough to do it myself so reaching out for some help.

George

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

### General instructions

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

### Instructions for avoiding API, ABI, and CLI breakage issues
Conda is able to record and lock (a.k.a. pin) dependency versions used at build time of other recipes.
This way, one can avoid that expectations of a downstream recipe with regards to API, ABI, or CLI are violated by later changes in the recipe.
If not already present in the meta.yaml, make sure to specify `run_exports` (see [here](https://bioconda.github.io/contributor/linting.html#missing-run-exports) for the rationale and comprehensive explanation).
Add a `run_exports` section like this:

```yaml
build:
  run_exports:
    - ...

```

with `...` being one of:

| Case                             | run_exports statement                                               |
| -------------------------------- | ------------------------------------------------------------------- |
| semantic versioning              | `{{ pin_subpackage("myrecipe", max_pin="x") }}`     |
| semantic versioning (0.x.x)      | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}`   |
| known breakage in minor versions | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| known breakage in patch versions | `{{ pin_subpackage("myrecipe", max_pin="x.x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| calendar versioning              | `{{ pin_subpackage("myrecipe", max_pin=None) }}`    |

while replacing `"myrecipe"` with either `name` if a `name|lower` variable is defined in your recipe or with the lowercase name of the package in quotes.

### Bot commands for PR management

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

Note that the <code>@BiocondaBot please merge</code> command is now depreciated. Please just squash and merge instead.

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by gbouras13** [comment]
Just linking to the author's comments here https://github.com/sc932/ALE/issues/22.

**Comment by rpetit3** [comment]
was hoping it was a simple "conda-forge" not in the channels, but was able to replicate

```
mamba create -n test-ale -c conda-forge -c bioconda ale==20180904

Looking for: ['ale==20180904']

pkgs/main/linux-64                                   5.3MB @  27.3MB/s  0.3s
pkgs/r/noarch                                                 No change
pkgs/main/noarch                                   697.2kB @   1.2MB/s  0.1s
pkgs/r/linux-64                                               No change
conda-forge/noarch                                  12.4MB @  16.2MB/s  0.9s
conda-forge/linux-64                                30.2MB @  24.7MB/s  1.5s
bioconda/linux-64                                    5.1MB @   3.5MB/s  1.6s
bioconda/noarch                                      4.7MB @   3.1MB/s  1.6s
Could not solve for environment specs
The following package could not be installed
└─ ale 20180904  is not installable because it requires
   └─ pymix, which requires
      └─ matplotlib >=1.1.0,!=1.4.2,<1.5.0 , which does not exist (perhaps a missing channel).
```

**Comment by rpetit3** [comment]
@BiocondaBot please fetch artifacts

**Comment by rpetit3** [comment]
@gbouras13 I had to tell make to use the `gcc` that is availlable in the `$CC` environmental variable. Due to these (`$CXX` is the other) not being in the PATH.

I think you are all good now, if you don't mind testing the artifacts that would be awesome!

**Comment by gbouras13** [comment]
```
conda install -c ./packages packages/osx-64/ale-core-20220503-h45fc8d7_0.tar.bz2
```

```
ALE -h 

Welcome to the Assembly Likelihood Estimator!
(C) 2010 Scott Clark

Usage: ALE [-options] alignments.[s|b]am assembly.fasta[.gz] ALEoutput.txt

Options: <i>nt <f>loat <s>tring [default]
-h or --help    : print out this help
--kmer <f>      : Kmer depth for kmer stats [4]
--qOff <i>      : Quality ascii offset (illumina) [33] or 64 (or 0)
--pl <s>        : placementOutputBAM
--pm <s>        : library parameter file (auto outputs .param)
--nout          : only output meta information (no per base) [off]
--minLL         : the minimum log Likelihood (-120)
--metagenome    : Evaluate each contig independently for depth & kmer metrics
--realign[=matchScore,misMatchPenalty,gapOpenPenalty,gapExtPenalty,minimumSoftClip (default: 1,3,11,4,8) ]
                   Realign reads with Striped-Smith-Waterman honoring ambiguous reference bases
                   and stacking homo-polymer indels
                   for PacBio, try --realign=1,5,2,1,20 (similar to BWA-SW recommendations)
--SNPreport <s> : Creates a new text file reporting all SNP phasing 
                   observed by a read against ambiguous bases in the reference
--minQual <i>   : Minimum quality score to use in Z-normalization (default 3).
                   Illumina quality scores can be unreliable below this threshold

```

# Test Run

## Install with bwa

```
create -n ALE_test bwa
conda activate ALE_test
conda install -c ./packages packages/osx-64/ale-core-20220503-h45fc8d7_0.tar.bz2
```

## Run on Test Data

```
        bwa index C11.fasta
        bwa mem -t 8 -a C11.fasta  C11_R1.fastq.gz > C11_R1.sam
        ALE C11_R1.sam C11.fasta C11.out.ale 
        grep "# ALE_score: " C11.out.ale  | sed 's/# ALE_score: //'
```


(Skipping most of the output) 

```
Total ALE Score: -195528988.434177
Output is in file: C11.out.ale
Closing input file
# From the grep command
-195528988.434177
```

@rpetit3 all works and looks brilliant to me - thanks for your help here :)

**Review by rpetit3 — APPROVED** [review]

**Comment by rpetit3** [comment]
Thanks for testing

**Pull request merged**
