### PR TITLE
updated to v360 and pointed to github instead of hgdownload. 

### PR DESCRIPTION
**Pull request by karl616**
… if osx will build as it is

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by daler** [comment]
Thanks @karl616! Great to see it's building now on macOS, and thanks for changing to github versions. This looks good. I'm not sure we need the old version subdirectory in this case.

To update all the `ucsc-*` tools, we regenerate recipes with https://github.com/bioconda/bioconda-recipes/tree/master/scripts/ucsc, and then we use the [bulk branch](https://bioconda.github.io/build-system.html#the-bulk-branch) since the building generally takes a while.

Would you please take a look at those UCSC scripts and templates to update them with your changes? You can put them in this PR or in another one (or wait till this weekend and I'll work on it). Then I'll start a run on the bulk branch to update everything.

**Comment by daler** [comment]
By the way, gcc on macOS in conda is kind of in flux . . . for now, can you please modify to use `llvm` on osx as indicated here: https://github.com/bioconda/bioconda-recipes/pull/7568#issuecomment-364389661

**Comment by karl616** [comment]
Hi @daler, I missed the script folder and went on with sed/awk. It is passing through circleci build locally at the moment.

The templating is much neater. I will have a look. It might be that I don't have time to finish today, but I could continue on Tuesday (Monday is holiday). I'll make a new PR of the template changes.

With regard to macOS, my only proof that it works is the circleci tests.... Is that enough?

**Comment by daler** [comment]
@karl616 thanks. My only proof for macOS is circleci tests as well, I don't have access to a dev mac machine.

**Comment by karl616** [comment]
Replaced by new PR:

https://github.com/bioconda/bioconda-recipes/pull/7592

@daler Thanks for the feedback!

**Pull request closed without merging**
