### PR TITLE
add recipe for pasty

### PR DESCRIPTION
**Pull request by rpetit3**
This PR adds a recipe for `pasty` a tool to serogroup Pseudomonas aeruginosa isolates

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by rpetit3** [comment]
@BiocondaBot please update

**Comment by rpetit3** [comment]
@biocondabot please fetch artifacts

**Comment by rpetit3** [comment]
Testing

### Conda
```
mamba create -n test-pasty -c conda-forge -c bioconda rich-click executor 'python>=3.7' blast
conda activate test-pasty

# Artifacts
unzip LinuxArtifacts.zip
conda install LinuxArtifacts/packages/noarch/pasty-1.0.0-hdfd78af_0.tar.bz2

# Testing
which pasty
/home/robert_petit/miniconda3/envs/test-pasty/bin/pasty

pasty --version
pasty, version 1.0.0

pasty --help

 Usage: pasty [OPTIONS]

 A tool easily taken advantage of for in silico serogrouping of Pseudomonas aeruginosa isolates

╭─ Options ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│    --version                  Show the version and exit.                                                                                                                                                                                                                   │
│ *  --assembly        TEXT     Input assembly in FASTA format (gzip is OK) [required]                                                                                                                                                                                       │
│    --db              TEXT     Input database in uncompressed FASTA format [default: /home/robert_petit/miniconda3/envs/test-pasty/share/pasty-1.0.0/OSAdb.fasta]                                                                                                           │
│    --prefix          TEXT     Prefix to use for output files [default: basename of input]                                                                                                                                                                                  │
│    --outdir          TEXT     Directory to save output files [default: ./]                                                                                                                                                                                                 │
│    --min_pident      INTEGER  Minimum percent identity to count a hit [default: 95]                                                                                                                                                                                        │
│    --min_coverage    INTEGER  Minimum percent coverage to count a hit [default: 95]                                                                                                                                                                                        │
│    --help                     Show this message and exit.                                                                                                                                                                                                                  │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯


# With  test data
pasty --assembly ~/repos/pasty/test/O2-GCF_000006765.fna.gz
Running BLASTN...
Writing outputs...
BLASTN results written to ./O2-GCF_000006765.fna.blastn.tsv

                     Serogroup Results
┏━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━┓
┃ sample               ┃ serogroup ┃ coverage ┃ fragments ┃
┡━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━┩
│ O2-GCF_000006765.fna │ O1        │ 12.52    │ 2         │
│ O2-GCF_000006765.fna │ O2        │ 100.00   │ 1         │
│ O2-GCF_000006765.fna │ O3        │ 1.43     │ 1         │
│ O2-GCF_000006765.fna │ O4        │ 13.86    │ 2         │
│ O2-GCF_000006765.fna │ O5        │ 0        │ 0         │
│ O2-GCF_000006765.fna │ O6        │ 14.78    │ 2         │
│ O2-GCF_000006765.fna │ O7        │ 11.82    │ 2         │
│ O2-GCF_000006765.fna │ O9        │ 11.42    │ 1         │
│ O2-GCF_000006765.fna │ O10       │ 12.97    │ 2         │
│ O2-GCF_000006765.fna │ O11       │ 15.87    │ 2         │
│ O2-GCF_000006765.fna │ O12       │ 0.00     │ 0         │
│ O2-GCF_000006765.fna │ O13       │ 16.22    │ 2         │
│ O2-GCF_000006765.fna │ WyzB      │ 0        │ 0         │
└──────────────────────┴───────────┴──────────┴───────────┘
Serogroup Results written to ./O2-GCF_000006765.fna.details.tsv

                    Predicted Serogroup
┏━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━┓
┃ sample               ┃ serogroup ┃ coverage ┃ fragments ┃
┡━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━┩
│ O2-GCF_000006765.fna │ O2        │ 100.00   │ 1         │
└──────────────────────┴───────────┴──────────┴───────────┘
Predicted serogroup result written to ./O2-GCF_000006765.fna.tsv

```

Conda looks good

### Docker
```
gzip -dc LinuxArtifacts/images/pasty:1.0.0--hdfd78af_0.tar.gz | docker load

docker run --rm -u $(id -u):$(id -g) -v ${PWD}:/data quay.io/biocontainers/pasty:1.0.0--hdfd78af_0 pasty --version
pasty, version 1.0.0

docker run --rm -u $(id -u):$(id -g) -v ${PWD}:/data quay.io/biocontainers/pasty:1.0.0--hdfd78af_0 pasty --help

 Usage: pasty [OPTIONS]

 A tool easily taken advantage of for in silico serogrouping of Pseudomonas
 aeruginosa isolates

╭─ Options ────────────────────────────────────────────────────────────────────╮
│    --version                  Show the version and exit.                     │
│ *  --assembly        TEXT     Input assembly in FASTA format (gzip is OK)    │
│                               [required]                                     │
│    --db              TEXT     Input database in uncompressed FASTA format    │
│                               [default:                                      │
│                               /usr/local/share/pasty-1.0.0/OSAdb.fasta]      │
│    --prefix          TEXT     Prefix to use for output files                 │
│                               [default: basename of input]                   │
│    --outdir          TEXT     Directory to save output files [default: ./]   │
│    --min_pident      INTEGER  Minimum percent identity to count a hit        │
│                               [default: 95]                                  │
│    --min_coverage    INTEGER  Minimum percent coverage to count a hit        │
│                               [default: 95]                                  │
│    --help                     Show this message and exit.                    │
╰──────────────────────────────────────────────────────────────────────────────╯

# Test with genome
cp ~/repos/pasty/test/O2-GCF_000006765.fna.gz  ./
docker run --rm -u $(id -u):$(id -g) -v ${PWD}:/data quay.io/biocontainers/pasty:1.0.0--hdfd78af_0 pasty --assembly /data/O2-GCF_000006765.fna.gz --outdir /data/
Running BLASTN...
Writing outputs...
BLASTN results written to /data/O2-GCF_000006765.fna.blastn.tsv

                     Serogroup Results
┏━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━┓
┃ sample               ┃ serogroup ┃ coverage ┃ fragments ┃
┡━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━┩
│ O2-GCF_000006765.fna │ O1        │ 12.52    │ 2         │
│ O2-GCF_000006765.fna │ O2        │ 100.00   │ 1         │
│ O2-GCF_000006765.fna │ O3        │ 1.43     │ 1         │
│ O2-GCF_000006765.fna │ O4        │ 13.86    │ 2         │
│ O2-GCF_000006765.fna │ O5        │ 0        │ 0         │
│ O2-GCF_000006765.fna │ O6        │ 14.78    │ 2         │
│ O2-GCF_000006765.fna │ O7        │ 11.82    │ 2         │
│ O2-GCF_000006765.fna │ O9        │ 11.42    │ 1         │
│ O2-GCF_000006765.fna │ O10       │ 12.97    │ 2         │
│ O2-GCF_000006765.fna │ O11       │ 15.87    │ 2         │
│ O2-GCF_000006765.fna │ O12       │ 0.00     │ 0         │
│ O2-GCF_000006765.fna │ O13       │ 16.22    │ 2         │
│ O2-GCF_000006765.fna │ WyzB      │ 0        │ 0         │
└──────────────────────┴───────────┴──────────┴───────────┘
Serogroup Results written to /data/O2-GCF_000006765.fna.details.tsv

                    Predicted Serogroup
┏━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━┓
┃ sample               ┃ serogroup ┃ coverage ┃ fragments ┃
┡━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━┩
│ O2-GCF_000006765.fna │ O2        │ 100.00   │ 1         │
└──────────────────────┴───────────┴──────────┴───────────┘
Predicted serogroup result written to /data/O2-GCF_000006765.fna.tsv

```

Docker looks good as well

**Comment by rpetit3** [comment]
@BiocondaBot please add label

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@BiocondaBot please merge

**Comment by rpetit3** [comment]
Thank you!

**Pull request merged**
