### PR TITLE
Update ena-upload-cli to 0.1.4

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`ena-upload-cli`](https://bioconda.github.io/recipes/ena-upload-cli/README.html): **0.1.3** &rarr; **0.1.4**

[install with bioconda](http://bioconda.github.io/recipes/ena-upload-cli/README.html) [Conda](https://anaconda.org/bioconda/ena-upload-cli/files)

Info | Link
-----|-----
Recipe | [`recipes/ena-upload-cli`](https://github.com//bioconda/bioconda-recipes/tree/bump/ena_upload_cli/recipes/ena-upload-cli) (click to view/edit other files)
Releases |[https://pypi.org/pypi/ena-upload-cli/json](https://pypi.org/pypi/ena-upload-cli/json)
Recipe Maintainer(s) | @bedroesb, @bgruening, @dyusuf

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by bedroesb** [comment]
@bgruening This update solves the template issue, I forgot to add them to the package

**Comment by bgruening** [comment]
> 16:23:01 BIOCONDA INFO (OUT) ImportError: cannot import name 'main' from 'ena_upload' (/opt/conda/conda-bld/ena-upload-cli_1596730757200/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.8/site-packages/ena_upload/__init__.py)


:(

**Comment by bedroesb** [comment]
fixed it in this PR :) https://github.com/bioconda/bioconda-recipes/pull/23803

**Comment by bedroesb** [comment]
@bgruening I pushed a fix to this PR ... Could you reopen this one, and merge it, or is there another reason ? Because the new PR that is opened by the bot does not contain my fix

**Comment by bgruening** [comment]
Upps, sorry. Closed the wrong one. Sorry I can not reopen, can you apply the fixx to the other, sorry.

**Pull request closed without merging**
