### PR TITLE
perl-bio-db-hts update

### PR DESCRIPTION
**Pull request by matthdsm**
version bump 2.4 > 2.7

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by matthdsm** [comment]
@bioconda/perl 
Any idea what went wrong here? I'm not able to see the travis logs.

Thanks for the help
M

**Comment by bgruening** [comment]
@matthdsm the error is this one `cc: error: unrecognized command line option ‘-fstack-protector-strong’`

**Comment by matthdsm** [comment]
Hi @bgruening 
I've had this error before, but this according to StackOverflow, this could be caused by using an old gcc version. The current version in de default conda channel is already a bit outdated, and doesn't support this flag. How do you suppose this could be fixed?

Thanks
M

**Comment by matthdsm** [comment]
@bioconda/core 
Anyone any idea?

Thanks
M

**Comment by johanneskoester** [comment]
Soon, conda will receive a new and updated gcc package, that hopefully solves this. This will come along with conda-build 3, which also introduces much improved pinning mechanisms.

**Pull request closed without merging**
