### PR TITLE
Update freebayes to 1.3.8

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`freebayes`](https://bioconda.github.io/recipes/freebayes/README.html): **1.3.7** &rarr; **1.3.8**

[install with bioconda](http://bioconda.github.io/recipes/freebayes/README.html) [Conda](https://anaconda.org/bioconda/freebayes/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/freebayes`](https://github.com//bioconda/bioconda-recipes/tree/bump/freebayes/recipes/freebayes) (click to view/edit other files)
Summary | Bayesian haplotype-based polymorphism discovery and genotyping
Home | [https://github.com/freebayes/freebayes](https://github.com/freebayes/freebayes)
Releases |[https://github.com/freebayes/freebayes/tags](https://github.com/freebayes/freebayes/tags)
Recipe Maintainer(s) | @jpuritz
Author | `@freebayes`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by maxibor** [comment]
Hmm @jpuritz ,
Seems like there was an issue with the build of this version.

**Comment by maxibor** [comment]
Hey @jpuritz @mencian ,
Is there any way I can help to fix this version of Freebayes ? The current version (1.3.7) is actually plagued by a bug that makes it unusable https://github.com/freebayes/freebayes/issues/776

**Comment by martin-g** [comment]
@maxibor You could open a PR that updates the version and fixes the build.
Looking at the logs you will need to update one of the patches because it does not apply clearly anymore:
```
Applying patch: /opt/recipe/0001-make-meson-build-conda-friendly.patch with args:[0m
03:05:15 [32mBIOCONDA INFO[0m (OUT) ['-Np1', '-i', '/tmp/tmpd0mjsatq/0001-make-meson-build-conda-friendly.patch.native', '--binary'][0m
03:05:15 [32mBIOCONDA INFO[0m (OUT) checking file meson.build[0m
03:05:15 [32mBIOCONDA INFO[0m (OUT) Hunk #1 FAILED at 15.[0m
03:05:15 [32mBIOCONDA INFO[0m (OUT) Hunk #2 FAILED at 24.[0m
03:05:15 [32mBIOCONDA INFO[0m (OUT) Hunk #3 FAILED at 99.[0m
03:05:15 [32mBIOCONDA INFO[0m (OUT) Hunk #4 succeeded at 248 (offset 21 lines).[0m
03:05:15 [32mBIOCONDA INFO[0m (OUT) 3 out of 4 hunks FAILED[0m
```

**Comment by fplazaonate** [comment]
Hi @lightning-auriga @maxibor 
Do you have any idea how to fix the build?

**Comment by aghozlane** [comment]
In my case, bioconda version of freebayes 1.3.6 and 1.3.7 gives seg fault errors on debian 12 and redhat 8.8... While the apt version of freebayes for instance, is fine...

**Comment by lightning-auriga** [comment]
Just seeing this. Is there a MRE for the AVX instruction situation in any of these related issues? I wasn't seeing that with my local build before, but my arch may support it locally. 

Separately, it looks like the current bioconda build is failing because it can't find vcflib. It seems like upstream has made a bunch of changes with its dependency handling. I don't have an appropriate build device available for the next few hours but once I have one, I'll look into making the meson build instructions compatible.

**Comment by lightning-auriga** [comment]
The 1.3.8 build works now, with respect to the azure build failures. 

Regarding the instruction errors, I built the 1.3.8 recipe on a local system with `conda mambabuild` and exported it to a different linux system, and that executable called variants with no issue. However, I just tried installing the live 1.3.7 on the same remote system and it segfaulted. Very mysterious. I'm going to mess around with the 1.3.7 recipe and see if I can figure out what's going on here, whether this is something to do with the build env in bioconda or if something was patched upstream in 1.3.8.

**Comment by lightning-auriga** [comment]
Followed up. Apparently the crash I was getting was related to something that was patched between 1.3.7 and 1.3.8, it's mentioned in one of upstream's commits. So I'm back to: I can't replicate the illegal instruction issue due to likely having no appropriate test platform.

It's tough but, from where I am currently, there's nothing wrong with the recipe _per se_ that I can identify. So I guess it's good to go from my perspective. If anyone can post a debug log or MRE or anything from the illegal instruction error, I'd love to revisit.

**Comment by aghozlane** [comment]
Great thanks for the effort ! I hope to see this new version soon in bioconda !

**Review by mencian — APPROVED** [review]
Thanks for looking into this @lightning-auriga!

**Comment by fplazaonate** [comment]
@lightning-auriga 
freebayes crashes on machines embedding a CPU that does not support AVX2 instructions.
Indeed, vcflib available on bioconda was built with 'march=native' optimizations.
https://github.com/vcflib/vcflib/blob/master/CMakeLists.txt#L73
I will update vcfib recipe to disable these EXTRA_FLAGS

```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGILL, Illegal instruction.
0x00007ffff7f17406 in bool convert<int>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int&) () from /export/mgps/home/fplazaonate/miniconda3/envs/freebayes_test/bin/../lib/libvcflib.so.1
(gdb) bt
#0  0x00007ffff7f17406 in bool convert<int>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int&) () from /export/mgps/home/fplazaonate/miniconda3/envs/freebayes_test/bin/../lib/libvcflib.so.1
#1  0x00007ffff7f311d8 in vcflib::VariantCallFile::parseHeader(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) ()
   from /export/mgps/home/fplazaonate/miniconda3/envs/freebayes_test/bin/../lib/libvcflib.so.1
#2  0x000055555559e378 in ?? ()
#3  0x00005555555a82ba in ?? ()
#4  0x00005555555632f6 in ?? ()
#5  0x00007ffff794824a in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#6  0x00007ffff7948305 in __libc_start_main () from /lib/x86_64-linux-gnu/libc.so.6
#7  0x0000555555568752 in ?? ()
```

**Pull request merged**
