### PR TITLE
Add Seed-Jellyfish

### PR DESCRIPTION
**Pull request by karel-brinda**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by karel-brinda** [comment]
@bgruening Hi Björn, do you please have any idea about what could be going wrong here?

```
configure: creating ./config.status
config.status: creating Makefile
config.status: creating tests/compat.sh
config.status: creating jellyfish-2.0.pc
config.status: creating config.h
config.status: executing depfiles commands
config.status: executing libtool commands
+ make
  YAGGO  sub_commands/count_main_cmdline.hpp
ruby: error while loading shared libraries: libjemalloc.so.1: cannot open shared object file: No such file or directory
make: *** [sub_commands/count_main_cmdline.hpp] Error 127
```

**Comment by bgruening** [comment]
Try to include `jemalloc` as build and probably as runtime dependency.

**Comment by karel-brinda** [comment]
I tried it but it seems that this doesn't help.

**Comment by daler** [comment]
Closing due to inactivity, please re-open if needed.

**Pull request closed without merging**
