### PR TITLE
Add vvv2_display bioconda recipe

### PR DESCRIPTION
**Pull request by FTouzain**
Add vvv2_display bioconda recipe to bioconda channel

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

### General instructions

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

### Instructions for avoiding API, ABI, and CLI breakage issues
Conda is able to record and lock (a.k.a. pin) dependency versions used at build time of other recipes.
This way, one can avoid that expectations of a downstream recipe with regards to API, ABI, or CLI are violated by later changes in the recipe.
If not already present in the meta.yaml, make sure to specify `run_exports` (see [here](https://bioconda.github.io/contributor/linting.html#missing-run-exports) for the rationale and comprehensive explanation).
Add a `run_exports` section like this:

```yaml
build:
  run_exports:
    - ...

```

with `...` being one of:

| Case                             | run_exports statement                                               |
| -------------------------------- | ------------------------------------------------------------------- |
| semantic versioning              | `{{ pin_subpackage("myrecipe", max_pin="x") }}`     |
| semantic versioning (0.x.x)      | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}`   |
| known breakage in minor versions | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| known breakage in patch versions | `{{ pin_subpackage("myrecipe", max_pin="x.x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| calendar versioning              | `{{ pin_subpackage("myrecipe", max_pin=None) }}`    |

while replacing `"myrecipe"` with either `name` if a `name|lower` variable is defined in your recipe or with the lowercase name of the package in quotes.

### Bot commands for PR management

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

Note that the <code>@BiocondaBot please merge</code> command is now depreciated. Please just squash and merge instead.

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by rpetit3** [comment]
@biocondabot please fetch artifacts

**Comment by rpetit3** [comment]
@FTouzain for some reason I'm not able to see the changes you are making

**Comment by FTouzain** [comment]
I believe this is because I made a pull that remove my files (to merge with current branch). I copied them again and made a push. It is not possible for me to see the content of my repo because of the number of folders to display. Nevertheless, when doing a lint locally, I get warnings because lint search for meta.yaml files in each directory provided in the directory, while these folders are 'src' (the sources of the package with python and R scripts) test-data (used for galaxy testing, light files) and test_vvv2_display for usual tests. Do I have a way to tell to lint not to search for packages in these directories please ? Sorry, I am a newbie and the recipe for anaconda was working using an absolute path to sources locally. Thank you in advance

**Comment by FTouzain** [comment]
Come back to absolute path. Local build ok:
```
bioconda-utils build --docker --mulled-test  --git-range vvv2_display-0.1.10
16:23:04 BIOCONDA INFO Considering total of 8950 recipes.
16:23:04 BIOCONDA INFO Constraining to 0 git modified recipes.
16:23:04 BIOCONDA INFO Processing 0 recipes.
16:23:04 BIOCONDA INFO Using docker image quay.io/bioconda/bioconda-utils-build-env-cos7:2.4.0 for building.
16:23:04 BIOCONDA INFO Nothing to be done.
```
, does not complain with subdirectories now... (why, mistery). Why "0 recipes" ? (recipes/vvv2_display-0.1.10 always there with all its files)

**Comment by vinisalazar** [comment]
@FTouzain any particular reason as to why you are adding this as a git submodule? That makes reviewing the PR more difficult (at least for me). Would you consider adding this without having it as a submodule?

Thank you,
Vini

**Comment by FTouzain** [comment]
@vinisalazar . By "submodule", do you mean in a distinct directory (src) ? Originally, I had a R directory, a python script directory, I changed it to better fit a kind of python package structure (as supposed by a description found on the web). After MANY tries, I finally succeed to make it working both in Galaxy (using the wrapper I developped for it) and in conda packaging on my personal channel (quite complicated to understand to make a "real test" working). I have other developments depending on it. If I could avoid to modify the data structure, it may be great (galaxy wrappers, galaxy workflows, and several instances using it). I believe the directories make it easier to read the repo. vvv2_display.py script calls all other .py and .R scripts in src (except visualize_coverage_depth.R that may be used for futur updates). test-data directory is mandatory for Galaxy. If by git "submodule", you mean something else, please explain it to me because it is a little bit obscur for me, I apologize. Thank you for your feedback

**Comment by vinisalazar** [comment]
Hi @FTouzain,

I pulled your branch locally and it seems that the only change you are making is adding an empty folder `recipes/vvv2_display`. Your PR must contain a `meta.yaml` file and, optionally, build scripts. Could you please post a link to your recipe code? Do you have a `meta.yaml` file?

I recommend reading through the [Bioconda Contributor Guide](https://bioconda.github.io/contributor/index.html) before making a PR.

Best,
Vini

**Comment by vinisalazar** [comment]
Hi @FTouzain, a few pointers:

- Your PR to Bioconda Recipes should contain only the `meta.yaml`, and no other files or source code.
- In your `meta.yaml` file, the `source` directive must have the `url` and `sha256` keys (they are commented in the file you sent).
- While these files may appear for you locally, they haven't either haven't been recorded in the Git history, or the changes haven't been pushed, hence they don't appear in your remote. If you check your fork of `bioconda-recipes` on the GitHub Web interface, you'll notice that the `recipes/vvv2_display` directory is empty, i.e. you should actually see something when you open this link: https://github.com/FTouzain/bioconda-recipes/tree/vvv2_display-0.1.10/recipes/vvv2_display/
- I would suggest that the easiest way of fixing this is doing the following:
   - Delete your fork and local copy of bioconda-recipes
   - Fork and clone again
   - Create the directory `recipes/vvv2_display` in your local clone and copy **only** your `meta.yaml` file into it.
   - Add the `meta.yaml` file to Git with Git add
   - Push the changes to your fork and open a new PR.

You could do all of these steps with your current fork and local clone, but starting from scratch is probably easier.

I hope this helps you.

Best,
Vini

**Comment by FTouzain** [comment]
Thank you very much for this clear guideline. I will follow. 

Just 2 few things: it is impossible to see in github what is in my vvv2_display directory because the display is cut to 1000 lines. And the link you provided me infortunately display 404 error.  

Thank you again.
Best regards.
Fabrice

**Comment by FTouzain** [comment]
Instructions followed in the PR: [43608](https://github.com/bioconda/bioconda-recipes/pull/43608)

**Pull request closed without merging**
