### PR TITLE
Update mosca to 1.2.0

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`mosca`](https://bioconda.github.io/recipes/mosca/README.html): **1.1.1** &rarr; **1.2.0**

[install with bioconda](http://bioconda.github.io/recipes/mosca/README.html) [Conda](https://anaconda.org/bioconda/mosca/files)

Info | Link
-----|-----
Recipe | [`recipes/mosca`](https://github.com//bioconda/bioconda-recipes/tree/bump/mosca/recipes/mosca) (click to view/edit other files)
Releases |[https://github.com/iquasere/MOSCA/tags](https://github.com/iquasere/MOSCA/tags)
Recipe Maintainer(s) | @iquasere
Author | @iquasere
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by iquasere** [comment]
@bioconda-bot please add label

**Comment by iquasere** [comment]
I requested the review because the build.sh doesn't seem to be run at installation. Is it in the right folder, and will it automatically be run at installation?

**Comment by daler** [comment]
@iquasere looks like the `scripts` dir is missing in this version, so the build script may need to be adjusted (see in the build log, "cp: cannot stat `scripts/*': No such file or directory", and [this line](https://github.com/bioconda/bioconda-recipes/blob/bump/mosca/recipes/mosca/build.sh#L3) in the build script)

**Comment by iquasere** [comment]
> @iquasere looks like the `scripts` dir is missing in this version, so the build script may need to be adjusted (see in the build log, "cp: cannot stat `scripts/*': No such file or directory", and [this line](https://github.com/bioconda/bioconda-recipes/blob/bump/mosca/recipes/mosca/build.sh#L3) in the build script)

Where does the build script store the logs?

**Comment by iquasere** [comment]
@daler thank you for the attention to the pull request. I am not finding the problem building locally, because it fails to build but gives no information on why (even with ```debug``` log level). The build.sh script seems fine, where is the problem there?

**Comment by daler** [comment]
@iquasere what if you use `bioconda-utils build --packages mosca`?

When comparing [v1.2.0 to v1.1.1](https://github.com/iquasere/MOSCA/compare/1.1.1...1.2.0), it looks like the `Databases` and `scripts` directories are no longer present in the repo. These are expected by the current `build.sh` in this recipe. It is trying to copy over files from those directories but they do not exist, which is what causes the failure.

**Comment by iquasere** [comment]
Do I have to remove this pull request to make a new automatic? Version 1.2.0 was again released

**Comment by iquasere** [comment]
> @iquasere what if you use `bioconda-utils build --packages mosca`?
> 
> When comparing [v1.2.0 to v1.1.1](https://github.com/iquasere/MOSCA/compare/1.1.1...1.2.0), it looks like the `Databases` and `scripts` directories are no longer present in the repo. These are expected by the current `build.sh` in this recipe. It is trying to copy over files from those directories but they do not exist, which is what causes the failure.

Gives the same result. Only informs that ```COMMAND FAILED (exited with 1): /tmp/miniconda/miniconda/bin/conda build --override-channels --no-anaconda-upload -c conda-forge -c bioconda -c defaults -e /tmp/miniconda/miniconda/conda_build_config.yaml -e /tmp/miniconda/miniconda/lib/python3.7/site-packages/bioconda_utils/bioconda_utils-conda_build_config.yaml recipes/mosca/meta.yaml```

**Comment by iquasere** [comment]
Ok, I finally understand, the automated pull request doesn't automatically update neither build.sh nor meta.yaml. Only tries to reinstall with the same two files. I should manually create a new pull request then, and close this one?

**Comment by dpryan79** [comment]
@iquasere The automated PR updates the version and checksum in meta.yaml and hopes that that's sufficient, since that tends to be the case. You can edit this PR and then approve and merge it if further changes are needed. That ends up being a bit more efficient than making a new PR since you would need someone else to approve the PR if you started a new one.

**Comment by iquasere** [comment]
> @iquasere The automated PR updates the version and checksum in meta.yaml and hopes that that's sufficient, since that tends to be the case. You can edit this PR and then approve and merge it if further changes are needed. That ends up being a bit more efficient than making a new PR since you would need someone else to approve the PR if you started a new one.

This makes all sense, I hadn't yet understood that workflow :)

**Comment by iquasere** [comment]
Now with these modified files, it builds locally, but circleCI is still failling, and I can't find the details of why it fails. Should I up the build number to 1?

**Comment by dpryan79** [comment]
I think the build issue is due to this requiring almost 2 year old dependencies while using the current pinnings. That causes a lot of issues for the solver. Can this use more recent versions of DESeq2/edgeR?

**Comment by iquasere** [comment]
It takes 2 hours for it to build locally with the old versions - confortably passing the 1 hour limit. I'm now trying to install it with the newest versions of DESeq2 and edgeR, since they work with the present version of MOSCA

**Comment by iquasere** [comment]
At least he server tried for 3h this time. What could possibly be taking so long to finish? Now it manages to finish the first two ```Collecting package metadata (repodata.json): ...working... done``` steps, but it times out on the third!

**Comment by dpryan79** [comment]
I honestly have no idea, this is evoking some incredibly odd behavior in the solver.

**Comment by iquasere** [comment]
Thank you very much for the effort, @dpryan79 ! I could gather all the tools' versions currently installed locally with MOSCA, and set those as the minimums, to take work off you!

**Comment by dpryan79** [comment]
I'm trying adding versions for everything. Go ahead and fill in the rest and change any I messed up.

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
Well that made a huge difference :)

**Comment by iquasere** [comment]
Yes! Lesson learned! ^^

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Comment by iquasere** [comment]
Thank you very much @dpryan79 @daler !

**Pull request merged**
