### PR TITLE
Update dnaweaver_synbiocad to 1.0.2

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`dnaweaver_synbiocad`](https://bioconda.github.io/recipes/dnaweaver_synbiocad/README.html): **1.0.1** &rarr; **1.0.2**

[install with bioconda](http://bioconda.github.io/recipes/dnaweaver_synbiocad/README.html) [Conda](https://anaconda.org/bioconda/dnaweaver_synbiocad/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/dnaweaver_synbiocad`](https://github.com//bioconda/bioconda-recipes/tree/bump/dnaweaver_synbiocad/recipes/dnaweaver_synbiocad) (click to view/edit other files)
Summary | Build the genetic designs generated by the SynBioCAD project using either Golden Gate or Gibson assembly
Home | [https://github.com/brsynth/DNAWeaver_SynBioCAD/](https://github.com/brsynth/DNAWeaver_SynBioCAD/)
Releases |[https://github.com/brsynth/DNAWeaver_SynBioCAD/tags](https://github.com/brsynth/DNAWeaver_SynBioCAD/tags)
Recipe Maintainer(s) | @breakthewall, @kenza12
Author | `@brsynth`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Review by breakthewall — CHANGES_REQUESTED** [review]
Update dependencies

**Comment by breakthewall** [comment]
Please close this PR, I made another that passed tests.

**Comment by standage** [comment]
@breakthewall That PR was merged into this branch, not the master branch. So this PR still needs to be merged. Please confirm.

**Comment by breakthewall** [comment]
@standage Yes I confirm. Thank you!

**Review by standage — APPROVED** [review]

**Pull request merged**
