### PR TITLE
Add libvips recipe

### PR DESCRIPTION
**Pull request by sebastian-luna-valero**
* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [X] This PR adds a new recipe.
* [X] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

For reference, see discussions here:
* https://github.com/jcupitt/libvips/issues/673
* https://github.com/bioconda/bioconda-utils/issues/132#issuecomment-309807210

### CODE REVIEW

**Comment by jcupitt** [comment]
Hello, a possible change would be to use the new pyvips Python binding:

https://github.com/jcupitt/pyvips

This is a API-compatible replacement for the Python binding that comes with libvips. It's built with cffi rather than gobject-introspection, so it's much, much simpler to install, just `pip install pyvips`. It's tested on Windows, macOS and Linux with Python 2.7 - 3.6, and with CPython, pypy2 and pypy3. It has proper docs as well:

https://jcupitt.github.io/pyvips/

And a page on pypi:

https://pypi.python.org/pypi/pyvips

And it's even a bit quicker. 

You could remove all of the gobject-introspection packages from the recipie and just have a note pointing people to pyvips.

**Comment by sebastian-luna-valero** [comment]
Thanks @jcupitt 

I am sorry, I might have got that wrong. I understood that `pyvips` is a python wrapper for `libvips`, is this right? If so, we first need to build `libvips`?

**Comment by jcupitt** [comment]
That's correct, you need to get the libvips shared library on to your system somehow (eg. via this recipie), then pyvips will let you call directly into that library.

**Comment by sebastian-luna-valero** [comment]
Thanks for confirming. We can then add `pyvips` afterwards. 

Meanwhile, do we still need `gobject-introspection` as a dependency for `libvips-8.5.8`?

**Comment by jcupitt** [comment]
Yes, I would remove `gobject-introspection`, `pygobject`, `python` form run and build

I'd remove `test-python.sh` from test. `pyvips` has the same test-suite and it'd be better to run it there. 

What is `xorg-libxrender` for? I'd try without that as well.

**Comment by sebastian-luna-valero** [comment]
Great! I will update the recipe accordingly.

Also, I am getting the following error [here](https://travis-ci.org/bioconda/bioconda-recipes/jobs/269936012#L4562):
```
/usr/bin/env: perl: No such file or directory
```

Do you know why?

**Comment by sebastian-luna-valero** [comment]
Also, should we build `libvips` for OS X as well? So far the recipe is Linux only.

**Comment by jcupitt** [comment]
Hi, I think I might have found the cause of the perl dependency. Could you test with this?

http://www.rollthepotato.net/~john/vips-8.5.9.tar.gz

It might build without perl. It should fail somewhere else anyway.

**Comment by sebastian-luna-valero** [comment]
Thanks. Will build for Linux only for the time being. Other users might try building for OS X, or use alternatives like homebrew or containers.

I have just pushed a new recipe, and will let you know how it goes.

**Comment by sebastian-luna-valero** [comment]
`make` output a lot of text to stdout, and I think we need this output to troubleshoot building problems. However, on Travis I get `The log length has exceeded the limit of 4 MB`.

@bioconda/core could you please suggest a way forward?

**Comment by jcupitt** [comment]
It's puzzling, the first error seems to be:

```
-I/opt/conda/conda-bld/libvips_1504104436068/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/glib-2.0/include
```

That's a `-I` generated by `pkg-config`, it's part of the output of:

```
$ pkg-config glib-2.0 --cflags
-I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include
```

But why would `pkg-config` be making bad output? And this bit seems to have worked on the previous travis run.

**Comment by sebastian-luna-valero** [comment]
In the `build.sh` script, I am using:
```
#!/usr/bin/env bash

export CPPFLAGS="-I${PREFIX}/include ${CPPFLAGS}"
export LDFLAGS="-L${PREFIX}/lib ${LDFLAGS}"
export LD_LIBRARY_PATH="${PREFIX}/lib:${LD_LIBRARY_PATH}"
export CFLAGS="-O3 -g ${CFLAGS}"
export CXXFLAGS="-O3 -g ${CXXFLAGS}"

./configure --prefix="${PREFIX}"
make
make check || ( cat test/test-suite.log && exit 1 )
make install
```

Is that wrong?

**Comment by sebastian-luna-valero** [comment]
Hi @jcupitt 

I am less busy these days and was wondering whether you'll find some spare time to have a look at the error above and let me know your thoughts so I can continue troubleshooting the conda recipe for `libvips`?

Many thanks,
Sebastian

**Comment by jcupitt** [comment]
Hello Sebastian, 

I think we should change direction slightly on this package. I think we should switch to pyvips, the new Python binding for libvips. 

I've downloaded anaconda, I'll see if I can get it to build and install with your recipie.

**Comment by jcupitt** [comment]
Hi again, I think we just need to remove the test section. I would change meta.yaml to be:

```
test:
  commands:
    - vips --version
```

The test dir is inside the build area, which is removed by conda after build.sh has run, so we can't run it.

`pyvips` has a huge test suite, so I would add a pyvips recipie (it's just `pip install pyvips`, it's very easy to package), make it depend on `libvips`, and run those tests instead.

**Comment by jcupitt** [comment]
I meant to say, if I remove the extra test stuff your recipie seems to work well in `./simulate-travis.py`.

**Comment by sebastian-luna-valero** [comment]
Hi @jcupitt 

Thanks for your feedback. Indeed, happy to help with `pyvips` after `vips` has been packaged.

I have just updated the recipe as suggested. Let's wait for the results of the tests.

On the other hand, the current recipe downloads `vips-8.5.9` from:
http://www.rollthepotato.net/~john/vips-8.5.9.tar.gz

Will you be releasing version 8.5.9 also in github, please?

Best regards,
Sebastian

**Comment by sebastian-luna-valero** [comment]
Also, after having a look at:
https://github.com/jcupitt/libvips/releases

Should we be packaging `vips-8.6` instead?

**Comment by jcupitt** [comment]
8.6 is supposed to be coming out in the next week or so, so yes, we should probably try for that.

**Comment by sebastian-luna-valero** [comment]
Re:
> What is `xorg-libxrender` for?

[FYI](https://travis-ci.org/bioconda/bioconda-recipes/jobs/279503304#L1949):
```
/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/libXrender.la: No such file or directory
```

**Comment by sebastian-luna-valero** [comment]
Hi @jcupitt 

Getting this error now:
```
+ make

/opt/rh/devtoolset-2/root/usr/bin/ld: warning: libjpeg.so.9, needed by /opt/conda/conda-bld/libvips_1506346712351/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/libtiff.so, may conflict with libjpeg.so.8

Traceback (most recent call last):

  File "/opt/conda/conda-bld/libvips_1506346712351/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/g-ir-scanner", line 65, in <module>

    from giscanner.scannermain import scanner_main

  File "/opt/conda/conda-bld/libvips_1506346712351/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/gobject-introspection/giscanner/scannermain.py", line 41, in <module>

    from giscanner.dumper import compile_introspection_binary

  File "/opt/conda/conda-bld/libvips_1506346712351/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/gobject-introspection/giscanner/dumper.py", line 34, in <module>

    from .gdumpparser import IntrospectionBinary

  File "/opt/conda/conda-bld/libvips_1506346712351/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/gobject-introspection/giscanner/gdumpparser.py", line 36, in <module>

    from .transformer import TransformerException

  File "/opt/conda/conda-bld/libvips_1506346712351/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/gobject-introspection/giscanner/transformer.py", line 34, in <module>

    from .girparser import GIRParser

  File "/opt/conda/conda-bld/libvips_1506346712351/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/gobject-introspection/giscanner/girparser.py", line 31, in <module>

    from .girwriter import COMPATIBLE_GIR_VERSION

  File "/opt/conda/conda-bld/libvips_1506346712351/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/gobject-introspection/giscanner/girwriter.py", line 29, in <module>

    from .xmlwriter import XMLWriter

  File "/opt/conda/conda-bld/libvips_1506346712351/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/gobject-introspection/giscanner/xmlwriter.py", line 46, in <module>

    from giscanner._giscanner import collect_attributes

ImportError: /opt/conda/conda-bld/libvips_1506346712351/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/gobject-introspection/giscanner/_giscanner.so: undefined symbol: PyUnicodeUCS4_DecodeUTF8

make[3]: *** [/opt/conda/conda-bld/libvips_1506346712351/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/share/gobject-introspection-1.0/Makefile.introspection:156: Vips-8.0.gir] Error 1

make[2]: *** [Makefile:855: all-recursive] Error 1

make[1]: *** [Makefile:637: all-recursive] Error 1

make: *** [Makefile:542: all] Error 2
```

Could you please let me know your thoughts?

Best regards,
Sebastian

**Comment by sebastian-luna-valero** [comment]
Hi @jcupitt 

I was re-trying to build this recipe, but `make check` reported a few errors:
https://travis-ci.org/bioconda/bioconda-recipes/jobs/299646892

Could you please have time to have a look and advice how to proceed?

Best regards,
Sebastian

**Comment by sebastian-luna-valero** [comment]
Summarising, here is the error I get:
```
======================================================================

ERROR: test_webp (test_foreign.TestForeign)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/opt/conda/conda-bld/libvips_1510237913137/work/vips-8.5.9/test/test_foreign.py", line 454, in test_webp

    self.assertEqual(y.get_value("orientation"), 6)

  File "../python/packages/gi/overrides/Vips.py", line 848, in get_value

    value = self.get(field)

TypeError: unknown type (null)

======================================================================

FAIL: test_icc (test_colour.TestColour)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/opt/conda/conda-bld/libvips_1510237913137/work/vips-8.5.9/test/test_colour.py", line 225, in test_icc

    self.assertLess(im.dE76(test).max(), 6)

AssertionError: 7.812778472900391 not less than 6

----------------------------------------------------------------------

Ran 177 tests in 147.747s

FAILED (failures=1, errors=1)

no dzsave support in this vips, skipping test

no magick support in this vips, skipping test

no openexr support in this vips, skipping test

no svg support in this vips, skipping test

memory: high-water mark 87.55 MB

error buffer: vips_image_get: field "orientation" not found

FAIL test_python.sh (exit status: 1)
```

Any ideas?

**Comment by johanneskoester** [comment]
We  have made changes to our build system (migrated from Travis CI to  Circle CI). If you would like to continue working on this PR, please  reopen this PR and update with latest upstream/master.

**Pull request closed without merging**
