### PR TITLE
Add vg 1.4.0

### PR DESCRIPTION
**Pull request by johanneskoester**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by johanneskoester** [comment]
@bgruening this fails because the build requires some git submodules. What is our recommended strategy for such a case?

**Comment by druvus** [comment]
@bgruening @johanneskoester I wanted to add vg some time ago but put it on hold due to dependancy of +20 submodules. Maybe we can do an exception here and use git_url so it could be added?

**Comment by johanneskoester** [comment]
Yes.

**Comment by bgruening** [comment]
I think the recommended way is to ask for a release tarball if this is not possible use git_url.

**Comment by johanneskoester** [comment]
The remaining bug seems to be a problem with the compiler version: vgteam/vg#751

**Comment by johanneskoester** [comment]
We  have made changes to our build system (migrated from Travis CI to  Circle CI). If you would like to continue working on this PR, please  reopen this PR and update with latest upstream/master.

**Comment by mbargull** [comment]
The error shows they use `std::regex`, thus `gcc >=4.9` would be needed..

**Comment by johanneskoester** [comment]
Yeah, I had the hope that those patches in devtoolset-2 gcc would help here :-(.

**Comment by mbargull** [comment]
Note that with the new compiler packages you have to make sure `CC` & co are used. The actual binaries are called, e.g, `x86_64-conda_cos6-linux-gnu-gcc` instead of just `gcc`. The activation scripts of the compiler packages take care of setting `CC` etc. accordingly. https://www.anaconda.com/blog/developer-blog/utilizing-the-new-compilers-in-anaconda-distribution-5/

**Comment by mbargull** [comment]
And you have to use the `gxx_*` packages as `gcc_*` doesn't contain `CXX`/`*-g++`

**Comment by johanneskoester** [comment]
Seems like protobuf still wants to use gcc...

**Comment by mbargull** [comment]
`source_me.sh` is still run by `Makefile`, e.g., https://github.com/vgteam/vg/blob/1f8d1fa24521243546fa12d060b1876cfbf692ab/Makefile#L189.
Hey, but you could patch everything so that `vg` doesn't vendor "all the things".
... Okay, since that sounds to be no fun potentially/time consuming, you could first try to just remove https://github.com/vgteam/vg/blob/1f8d1fa24521243546fa12d060b1876cfbf692ab/source_me.sh#L8-L9 with a patch.

**Comment by johanneskoester** [comment]
Yes, that is what I will do. Yeah removing the dependencies would be nice indeed...

**Comment by johanneskoester** [comment]
@mbargull I think I am stuck here. Seems like the error is caused by protobuf still not finding g++: google/protobuf#492. Since you have already familiarized with the new compilers, any idea?

**Comment by mbargull** [comment]
protobuf's `config.log` shows a lot of
```
$PREFIX/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.2.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: cannot find -lgomp
```
errors -- let's see if adding `openmp` helps..

**Comment by mbargull** [comment]
Hm, conda-forge's recipe for the same version doesn't mention OpenMP, though: https://github.com/conda-forge/protobuf-feedstock/tree/4a47177307485d1ce97cd1af7fb35ccdf6297468/recipe
¯\\\_(ツ)\_/¯

**Comment by mbargull** [comment]
conda-forge's recipe made me curious: looks like they just use the system `gcc`:
https://github.com/conda-forge/protobuf-feedstock/blob/4a47177307485d1ce97cd1af7fb35ccdf6297468/recipe/build.sh#L15-L16
https://github.com/conda-forge/protobuf-feedstock/blob/4a47177307485d1ce97cd1af7fb35ccdf6297468/recipe/meta.yaml#L24-L36
(double-checked with the built package's `info/recipe/meta.yaml`: no `gcc` was included in the rendered `build` section). So maybe this means with the Docker image's `devtoolset-2`/`gcc` we always have OpenMP?

----
Why would this be interesting? => If were to change some recipes to explicitly use `gcc` or `{{ compiler("c") }}`/`{{ compiler("cxx") }}`, we now know we have to be on the lookout for `ld: cannot find -lgomp` errors!

**Comment by mbargull** [comment]
Yay, that worked perfectly.
Well, but unsurprisingly another of the plethora of vendored libraries failed to compile:
```
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/gperftools/tcmalloc.h
config.status: creating src/windows/gperftools/tcmalloc.h
config.status: creating src/config.h
config.status: executing depfiles commands
config.status: executing libtool commands
configure: WARNING: No frame pointers and no libunwind. Using experimental backtrace capturing via libgcc
make[1]: Entering directory `/opt/conda/conda-bld/vg_1519120737998/work/deps/gperftools'
/bin/sh ./libtool  --tag=CXX   --mode=compile /opt/conda/conda-bld/vg_1519120737998/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/x86_64-conda_cos6-linux-gnu-c++ -DHAVE_CONFIG_H -I. -I./src  -I./src  -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -DNO_TCMALLOC_SAMPLES -pthread -DNDEBUG -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -fno-builtin-malloc -fno-builtin-free -fno-builtin-realloc -fno-builtin-calloc -fno-builtin-cfree -fno-builtin-memalign -fno-builtin-posix_memalign -fno-builtin-valloc -fno-builtin-pvalloc  -Wno-unused-result -fsized-deallocation  -DNO_FRAME_POINTER -O3 -fopenmp -std=c++11 -ggdb -g -MMD -MP -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -I/opt/conda/conda-bld/vg_1519120737998/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/include -fdebug-prefix-map=src=/usr/local/src/conda/vg-1.6.0 -fdebug-prefix-map=/opt/conda/conda-bld/vg_1519120737998/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_=/usr/local/src/conda-prefix -MT src/libtcmalloc_minimal_la-tcmalloc.lo -MD -MP -MF src/.deps/libtcmalloc_minimal_la-tcmalloc.Tpo -c -o src/libtcmalloc_minimal_la-tcmalloc.lo `test -f 'src/tcmalloc.cc' || echo './'`src/tcmalloc.cc
libtool: compile:  /opt/conda/conda-bld/vg_1519120737998/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/x86_64-conda_cos6-linux-gnu-c++ -DHAVE_CONFIG_H -I. -I./src -I./src -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -DNO_TCMALLOC_SAMPLES -pthread -DNDEBUG -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -fno-builtin-malloc -fno-builtin-free -fno-builtin-realloc -fno-builtin-calloc -fno-builtin-cfree -fno-builtin-memalign -fno-builtin-posix_memalign -fno-builtin-valloc -fno-builtin-pvalloc -Wno-unused-result -fsized-deallocation -DNO_FRAME_POINTER -O3 -fopenmp -std=c++11 -ggdb -g -MMD -MP -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -I/opt/conda/conda-bld/vg_1519120737998/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/include -fdebug-prefix-map=src=/usr/local/src/conda/vg-1.6.0 -fdebug-prefix-map=/opt/conda/conda-bld/vg_1519120737998/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_=/usr/local/src/conda-prefix -MT src/libtcmalloc_minimal_la-tcmalloc.lo -MD -MP -MF src/.deps/libtcmalloc_minimal_la-tcmalloc.Tpo -c src/tcmalloc.cc  -fPIC -DPIC -o src/.libs/libtcmalloc_minimal_la-tcmalloc.o
In file included from src/libc_override_glibc.h:62:0,
                 from src/libc_override.h:79,
                 from src/tcmalloc.cc:156:
src/libc_override_gcc_and_weak.h:60:33: error: ISO C++1z does not allow dynamic exception specifications
 void* operator new(size_t size) throw (std::bad_alloc)
                                 ^~~~~
src/libc_override_gcc_and_weak.h:64:35: error: ISO C++1z does not allow dynamic exception specifications
 void* operator new[](size_t size) throw (std::bad_alloc)
                                   ^~~~~
make[1]: *** [src/libtcmalloc_minimal_la-tcmalloc.lo] Error 1
make[1]: Leaving directory `/opt/conda/conda-bld/vg_1519120737998/work/deps/gperftools'
make: *** [lib/libtcmalloc_minimal.a] Error 2
```
See https://github.com/yandex/ClickHouse/issues/1002#issuecomment-320652680 for fixes.

**Comment by mbargull** [comment]
So regarding that `gperftools` compile error, I guess your options are
* "de-vendor" `gperftools`,
* make sure `-std=c++11` or `-std=c++14` (whatever is applicable) but not `-std=c++17` is used,
* try to replace the vendored one with `gperftools >=2.6.1`,
* patch the vendored one.

**Comment by tseemann** [comment]
Any suggestions @ekg ?

**Comment by bgruening** [comment]
Debian package is now available here:

https://salsa.debian.org/med-team/vg/-/blob/master/debian/rules
https://salsa.debian.org/med-team/vg/-/tree/master/debian/patches
https://salsa.debian.org/med-team/vg/-/tree/master/debian/include

**Comment by druvus** [comment]
Added in another PR

**Pull request closed without merging**
