### PR TITLE
removed dependency on configureHomer after install

### PR DESCRIPTION
**Pull request by simonvh**
* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [X] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

@cokelaer @BioNinja Please have a look. As far as I've tested this should remove the need to run configureHomer after the install. The hard-coded paths are now automatically fixed by conda-build.

### CODE REVIEW

**Comment by cokelaer** [comment]
I did not start this recipes so @BioNinja may be more knowledgeable but looks good to me. At least this is an improvment. This is not related to your change but on linux, the final executable were partly missing and we will need to check that at some point.

**Comment by BioNinja** [comment]
it looks nice. @simonvh , does it works on macs

**Comment by cokelaer** [comment]
@simonvh @bioninja let us squash and merge. I do not know the policy / good practice: I'm guessing that simon can squash and merge the changes. We then need to check if the executable are properly installed both for mac and linux.

**Comment by simonvh** [comment]
Yes, I'll merge. I can't test osx as I don't have access to a mac. Let me know if you encounter (or hear of) any issues.

**Comment by cokelaer** [comment]
Okay, so FYI, your changes improve the recipes since we do not need to call another script but the previous problem persists: executables in ./share/homer/bin are all empty. I'll open an issue.

**Pull request merged**
