### PR TITLE
update pantools to v4.2.2

### PR DESCRIPTION
**Pull request by dirkjanvw**
Update PanTools to v4.2.2

### CODE REVIEW

**Comment by dirkjanvw** [comment]
@BiocondaBot please add label

**Comment by dirkjanvw** [comment]
@bioconda/core question: can I simply self-approve these kinds of version updates and merge them myself? (as a member of bioconda I can, I'm just wondering whether I should)

**Comment by cbrueffer** [comment]
@dirkjanvw if you are the PR creator your own approval is not enough. However, if you review a bot-created PR, you can approve and merge it.

Regarding this recipe, is the conflict for busco / bcftools on OSX still an issue?

**Comment by dirkjanvw** [comment]
@cbrueffer aha, thanks!

And yes, both busco and bcftools still conflict on OSX specifically with the other dependencies we have. My best guess it has something to do with conflicting versions needed for zlib and llvm-openmp, but I am unable to solve that. But as they are not necessary for the core functionalities of PanTools, we chose to not include them as long as they are conflicting with the other dependencies.

**Comment by cbrueffer** [comment]
Thanks for confirming!

**Review by cbrueffer — APPROVED** [review]

**Pull request merged**
