### PR TITLE
new recipe R.4Cker

### PR DESCRIPTION
**Pull request by matthdsm**
:information_source:
If this is your first pull request to Bioconda please ping `@bioconda/core` so it can be reviewed and to request being added as a member of the Bioconda team. Members of the Bioconda team are able to merge their own pull requests once tests and linting have passed.

----------------

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

ping @bioconda/r for a review, as my r experience isn't that up to date.
remark:
 - There's no fixed release or license available

Thanks
M

### CODE REVIEW

**Comment by dpryan79** [comment]
This is breaking due to https://github.com/bioconda/bioconda-recipes/issues/13846

**Comment by matthdsm** [comment]
Hi Devon,

Thanks for pointing me to the issue. Is there any way to fix the circle-ci tests that you know of?

Thanks
M

**Comment by dpryan79** [comment]
Not at the moment, we're really not sure what's causing this to break, since it tends to work locally (except when it doesn't).

**Comment by matthdsm** [comment]
Bummer ☹️ Is there any way to work around this?

**Comment by dpryan79** [comment]
We're working on a fix now. I expect it to get deployed in the next 2 days, so hopefully this will get fixed soon :)

**Comment by matthdsm** [comment]
Great to hear! Thanks!
Anything I could do to help, apart from stop whining?
M

**Comment by dpryan79** [comment]
No, but thanks for the offer. The fix for this is for us to make a new minimal docker container for "mulled" testing that uses a newer version of conda. We'd been using a container from anaconda, but that hasn't been updated recently and is apparently unlikely to be updated in the near-term future. So we're just making our own and then will switch bioconda-utils to it. It seems likely that that will solve the problem.

**Pull request closed without merging**
