### PR TITLE
Update gfastats tool version

### PR DESCRIPTION
**Pull request by SaimMomin12**
This PR concerns with version update of gfastats tool from 1.3.7 to 1.3.8

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

### General instructions

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

### Instructions for avoiding API, ABI, and CLI breakage issues
Conda is able to record and lock (a.k.a. pin) dependency versions used at build time of other recipes.
This way, one can avoid that expectations of a downstream recipe with regards to API, ABI, or CLI are violated by later changes in the recipe.
If not already present in the meta.yaml, make sure to specify `run_exports` (see [here](https://bioconda.github.io/contributor/linting.html#missing-run-exports) for the rationale and comprehensive explanation).
Add a `run_exports` section like this:

```yaml
build:
  run_exports:
    - ...

```

with `...` being one of:

| Case                             | run_exports statement                                               |
| -------------------------------- | ------------------------------------------------------------------- |
| semantic versioning              | `{{ pin_subpackage("myrecipe", max_pin="x") }}`     |
| semantic versioning (0.x.x)      | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}`   |
| known breakage in minor versions | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| known breakage in patch versions | `{{ pin_subpackage("myrecipe", max_pin="x.x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| calendar versioning              | `{{ pin_subpackage("myrecipe", max_pin=None) }}`    |

while replacing `"myrecipe"` with either `name` if a `name|lower` variable is defined in your recipe or with the lowercase name of the package in quotes.

### Bot commands for PR management

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

Note that the <code>@BiocondaBot please merge</code> command is now depreciated. Please just squash and merge instead.

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by SaimMomin12** [comment]
@BiocondaBot please add label

**Comment by bgruening** [comment]
```
14:48:54 BIOCONDA INFO (OUT) ./include/main.h:31:10: fatal error: log.h: No such file or directory
14:48:54 BIOCONDA INFO (OUT)    31 | #include "log.h"
14:48:54 BIOCONDA INFO (OUT)       |          ^~~~~~~
14:48:54 BIOCONDA INFO (OUT) compilation terminated.

```
@gf777 seems that the tarball is still missing something.

@SaimMomin12 sorry for the wrong advice I was hoping the tarball works now, please revert to the git checkout.

**Review by bgruening — APPROVED** [review]

**Comment by SaimMomin12** [comment]
Thanks @bgruening

**Comment by gf777** [comment]
I am not sure what you want to do. This version that I recently added: wget https://github.com/vgl-hub/gfastats/releases/download/v1.3.8/gfastats.v1.3.8-with_submodules.zip compiles fine as it contains the submodule as well. Looks like it may be using the wrong version?
Note that afaik there is no way to have the standard tarball include more than the source code from the repo (without the subomodules). This is created by github by default

**Comment by martin-g** [comment]
The update looks good to me!

A recipe could get the Git submodules by using 'git_url' with a Git tag

**Comment by bgruening** [comment]
@SaimMomin12 I think what happend is that you used the wrong URL, see https://github.com/bioconda/bioconda-recipes/pull/51246/commits/22425145ded8e96af90675f45c807a4d28c3b979 and https://github.com/vgl-hub/gfastats/releases/download/v1.3.8/gfastats.v1.3.8-with_submodules.zip from @gf777 ....

**Comment by SaimMomin12** [comment]
@bgruening Oh no, my bad! Would it be a good idea to edit the recipe now and create a PR to correct this?

**Pull request merged**
