### PR TITLE
Add Mummer4 recipe

### PR DESCRIPTION
**Pull request by ar0ch**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

This PR adds [mummer4](https://mummer4.github.io), which is partially backwards compatible with mummer3 syntax but includes niceties like multithreaded nucmer, out of the box 64bit support (any sized genome), read-based analysis and SAM output.

This does conflict with the `mummer` recipe that exists, in that the binaries have the same name.  I'm adding a new, `mummer4` recipe instead of updating the existing mummer recipe since the build process has changed and requires newer libgcc, which may not be compatible with existing environments.

### CODE REVIEW

**Comment by bgruening** [comment]
Looks good to me! ping @peterjc 

> This does conflict with the mummer recipe that exists, in that the binaries have the same name. I'm adding a new, mummer4 recipe instead of updating the existing mummer recipe since the build process has changed and requires newer libgcc, which may not be compatible with existing environments.

The binaries still have the same name, right? So you can still not mix both versions in one environment.

**Comment by ar0ch** [comment]
Yes, the binaries have the same names as mummer3

**Comment by peterjc** [comment]
What does "partially backwards compatible" mean? Adding new stuff is fine, but do they remove anything?

It is likely that anyone would need mummer3 and mummer4 installed at the same time (as does happen sometimes with hmmer2 and hmmer3), in which case disambiguated binary names might helpful?

**Comment by ar0ch** [comment]
It doesn't appear all the old mummer3 options have been ported over yet.  At least, the help text for the `mummer` binary: 

> Implemented MUMmer v3 options...

makes it seem like its not 100% backwards compatible?

**Comment by peterjc** [comment]
We can come back and add an extra renamed-binary package (as done for hmmer2) later if there is demand. I have no objection to merging this.

**Comment by bgruening** [comment]
Thanks @peterjc for the quick response. Thanks @ar0ch for the recipe!

**Pull request merged**
