### PR TITLE
Add biscuit recipe file, after testing lint and build

### PR DESCRIPTION
**Pull request by ekushele**
This is a recipe bioconda file for biscuit utility, which is described as follows:
BISulfite-seq CUI Toolkit (BISCUIT) is a utility for analyzing sodium bisulfite conversion-based DNA methylation/modification data. It was written to perform alignment, DNA methylation and mutation calling, and allele specific methylation from bisulfite sequencing data.

@BiocondaBot please add label
--

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by dpryan79** [comment]
All of the Makefiles need to be patched :(

**Comment by ekushele** [comment]
@dpryan79  What does that mean?

**Comment by dpryan79** [comment]
Biscuit doesn't seem to tell the other Makefiles what compiler to use, so they may all need to get changed.

**Comment by ekushele** [comment]
Thanks @dpryan79 !
So how do I actually patch a makefile? And how can I test locally that it's working? because it seemed to pass my lint and built test successfully

**Comment by dpryan79** [comment]
You can put patches under `source:`. For local testing you want to use `bioconda-utils build --docker` to run in a minimal docker container.

**Comment by ekushele** [comment]
I can't use docker in my cluster so I tested it with `--no-docker`  and it was fine.. so I'm trying to understand how could I have possibly foresee that there is a problem.

**Comment by dpryan79** [comment]
If you can't use docker then you can't really test for issues. Many systems will have a binary called gcc on them, but that doesn't exist in conda so we can ensure packages are built with the correct compiler.

**Comment by ekushele** [comment]
hmmm...
Do you have any suggestion for me what can I do..?
Sorry for asking many questions, I'm just confused...

**Comment by dpryan79** [comment]
You'll have to go through the Makefiles in the various subfolders and see which are hard-coding gcc or another compiler in.

**Comment by ekushele** [comment]
The makefile is [here](https://github.com/huishenlab/biscuit/blob/master/Makefile)
and I wrote inside the meta.yaml:
```
requirements:
  build:
    - {{ compiler('cxx') }}

```
Isn't it enough?

**Comment by dpryan79** [comment]
I think most of the code is C rather than C++, but some of the Makefiles are hard-coding the compiler they're using. I can probably work on this tonight if you're not in a rush to get it merged in during the day today.

**Comment by ekushele** [comment]
I would really appreciate that, if you have time and patient.
I'm working from home, rather than my university, due to the COVID19, so I don't have an access to docker.
If it's fine with you, I would really be happy if you will be able to let me know that it's working..

**Comment by dpryan79** [comment]
Not an issue, I'll work on this on my private laptop tonight. If I don't get back to you by tomorrow morning please ping me :)

**Comment by ekushele** [comment]
It's so nice of you.
Thank you!

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Comment by ekushele** [comment]
Hi again @dpryan79 , 

The biscuit program has a script [https://github.com/huishenlab/biscuit/blob/master/scripts/QC.sh](https://github.com/huishenlab/biscuit/blob/master/scripts/QC.sh), which is used along with the program, but is not a part of the executable file itself.

Saying I want the build.sh recipe file to download the script, and add it to the recipe, how can I do that?

**Pull request merged**
