### PR TITLE
Update unifrac-binaries to 1.2.1

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`unifrac-binaries`](https://bioconda.github.io/recipes/unifrac-binaries/README.html): **1.2** &rarr; **1.2.1**

[install with bioconda](http://bioconda.github.io/recipes/unifrac-binaries/README.html) [Conda](https://anaconda.org/bioconda/unifrac-binaries/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/unifrac-binaries`](https://github.com//bioconda/bioconda-recipes/tree/bump/unifrac_binaries/recipes/unifrac-binaries) (click to view/edit other files)
Summary | Fast phylogenetic diversity calculations
Home | [https://github.com/biocore/unifrac-binaries](https://github.com/biocore/unifrac-binaries)
Releases |[https://github.com/biocore/unifrac-binaries/tags](https://github.com/biocore/unifrac-binaries/tags)
Recipe Maintainer(s) | @sfiligoi, @wasade
Author | `@biocore`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by sfiligoi** [comment]
@BiocondaBot please fetch artifacts

**Review by sfiligoi — APPROVED** [review]
Legitimate

**Comment by sfiligoi** [comment]
@BiocondaBot please add label

**Comment by sfiligoi** [comment]
Tested locally and works as expected.

**Review by priesgo — APPROVED** [review]
CPP is not my thing, but I wonder if defining dependency versions would have the bioconda package more robust.

**Comment by priesgo** [comment]
@BiocondaBot please merge

**Pull request merged**
