### PR TITLE
update debreak_1.0.2 -> debreak_v1.3

### PR DESCRIPTION
**Pull request by czc**
modified:   recipes/debreak/build.sh	
modified:   recipes/debreak/meta.yaml

Describe your pull request here

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by czc** [comment]
Dear Admin,

Could you help review and merge to bioconda? Thank you so much.

**Comment by cbrueffer** [comment]
Sorry for the delay; does it make sense to test the newly added bsalign binary as well?

**Comment by czc** [comment]
> 

Sure. Bsalign was developed by Dr. Jue Ruan: https://github.com/ruanjue/bsalign. It's an excellent tool for performing pairwise or multiple sequence alignment.

**Comment by cbrueffer** [comment]
It just occurred to me, the addition of the bsalign Linux binary means the recipe is not `noarch` anymore. Possible solutions:

1. mark the recipe Linux-only
2. add a bsalign recipe that compiles Linux and macOS binaries. and include it as dependency here

**Comment by czc** [comment]
> It just occurred to me, the addition of the bsalign Linux binary means the recipe is not `noarch` anymore. Possible solutions:
> 
> 1. mark the recipe Linux-only
> 2. add a bsalign recipe that compiles Linux and macOS binaries. and include it as dependency here

What is Linux-only recipe? Any link or examples? 

If bsalign were added, then it would be great. We were trying to add it as a dependency, but could not find it. 

Thank you so much for the help.

**Comment by czc** [comment]
> 

Thank you very much! I saw it was approved. Do I need to change it now or leave it as it would be fine?

**Comment by cbrueffer** [comment]
I approved before noticing the noarch issue. I'll change it to Linux-only for now, then it can always be changed back once bsalign is noarch.

**Comment by czc** [comment]
> I approved before noticing the noarch issue. I'll change it to Linux-only for now, then it can always be changed back once bsalign is noarch.

Awesome! Thank you so much for the help.

**Comment by cbrueffer** [comment]
@bioconda-bot please merge

**Pull request merged**
