### PR TITLE
update sra

### PR DESCRIPTION
**Pull request by sachalau**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by sachalau** [comment]
Hello @bioconda/team !

I want to update the fastq-dump version from NCBI but I see that this recipe is a bit unusual : it builds other recipes from the NCBI at the same time (in build.sh).

I don't want to mess up everything but shouldn't we build separate recipes for NGS_SDK and NCBI_VDB ? Does someone know why the recipe was built like that ? 

Thanks a lot for your help !

**Comment by sachalau** [comment]
No I think it will be better to build them in another recipes right ? I don't know why it was built like this before.

**Comment by bgruening** [comment]
In another recipe?

**Comment by sachalau** [comment]
Yes, starting now  https://github.com/bioconda/bioconda-recipes/pull/8467

**Comment by rvalieris** [comment]
hello, I made a commit fixing some stuff, it should be alright now.

**Comment by sachalau** [comment]
@rvalieris thanks a lot for your help !

**Pull request merged**
