### PR TITLE
Update dunovo to 2.16

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`dunovo`](https://bioconda.github.io/recipes/dunovo/README.html): **2.15** &rarr; **2.16**

[install with bioconda](http://bioconda.github.io/recipes/dunovo/README.html) [Conda](https://anaconda.org/bioconda/dunovo/files)

Info | Link
-----|-----
Recipe | [`recipes/dunovo`](https://github.com//bioconda/bioconda-recipes/tree/bump/dunovo/recipes/dunovo) (click to view/edit other files)
Releases |[https://github.com/galaxyproject/dunovo/tags](https://github.com/galaxyproject/dunovo/tags)
Author | `@galaxyproject`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by dpryan79** [comment]
We can't reasonably support 5 year old versions of mafft unless someone adds back a recipe for that.

**Comment by dpryan79** [comment]
Looks like bowtie needs to be updated to handle python3.

**Comment by davebx** [comment]
@dpryan79 I'll ping the author of dunovo, he'll likely have an interest in updating the tool.

**Comment by NickSto** [comment]
This is actually a pre-release version (probably should be called a beta) and has some bugs. It definitely shouldn't be released yet. Thanks for the feedback, though!

**Comment by dpryan79** [comment]
Oh, thanks for the heads up on that!

**Pull request closed without merging**
