### PR TITLE
Update PanTools to v4.2.0

### PR DESCRIPTION
**Pull request by dirkjanvw**
Update PanTools recipe from 4.1.1 to 4.2.0 (manual bump since PanTools source code is hosted on git.wur.nl instead of github.com).

### CODE REVIEW

**Comment by dirkjanvw** [comment]
@BiocondaBot please add label

**Comment by dirkjanvw** [comment]
I'll do a bit more testing to see if the dependencies are correct now, I'll ask the bot to put the label up there once everything works as expected

**Comment by dirkjanvw** [comment]
@BiocondaBot please add label

**Comment by dirkjanvw** [comment]
@bioconda/core the current recipe looks good for pantools v4.2.0 and works as expected in my opinion; could you please review and merge?

**Comment by dpryan79** [comment]
@BiocondaBot please fetch artifacts

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
Thanks @dirkjanvw !

**Pull request merged**
