### PR TITLE
Update pixelator to 0.18.1

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`pixelator`](https://bioconda.github.io/recipes/pixelator/README.html): **0.17.1** &rarr; **0.18.1**

[install with bioconda](http://bioconda.github.io/recipes/pixelator/README.html) [Conda](https://anaconda.org/bioconda/pixelator/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/pixelator`](https://github.com//bioconda/bioconda-recipes/tree/bump/pixelator/recipes/pixelator) (click to view/edit other files)
Summary | A command-line tool and library to process and analyze sequencing data from Molecular Pixelation (MPX) assays.
Home | [https://github.com/PixelgenTechnologies/pixelator](https://github.com/PixelgenTechnologies/pixelator)
Releases |[https://pypi.org/pypi/pixelgen_pixelator/json](https://pypi.org/pypi/pixelgen_pixelator/json)
Recipe Maintainer(s) | @johandahlberg, @ambarrio, @fbdtemme

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by johandahlberg** [comment]
The will need to be closed since the `umi_tools` version pixelator 0.18.0 wants (i.e. 1.1.4) is not available for python 3.11. We will shortly be releasing pixelator 0.18.1 to fix this. And then that can be brought into bioconda.

**Comment by martin-g** [comment]
Closing the PR will lead to a new one opened very soon by the bot ...
I will change it to `Draft` state and the bot will update it once the new version is released!

**Comment by johandahlberg** [comment]
Ok. Thanks @martin-g.

**Comment by mencian** [comment]
Closing in favor of #49193.

**Pull request closed without merging**
