### PR TITLE
Update rnaquast to 2.2.4

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`rnaquast`](https://bioconda.github.io/recipes/rnaquast/README.html): **2.2.3** &rarr; **2.2.4**

[install with bioconda](http://bioconda.github.io/recipes/rnaquast/README.html) [Conda](https://anaconda.org/bioconda/rnaquast/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/rnaquast`](https://github.com//bioconda/bioconda-recipes/tree/bump/rnaquast/recipes/rnaquast) (click to view/edit other files)
Summary | rnaQUAST is a tool for evaluating RNA-Seq assemblies using reference genome and gene database. In addition, rnaQUAST is also capable of estimating gene database coverage by raw reads and de novo quality assessment using third-party software.
Home | [http://cab.spbu.ru/software/rnaquast/](http://cab.spbu.ru/software/rnaquast/)
Releases |

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by dpryan79** [comment]
Needs an augustus rebuild

**Comment by yodeng** [comment]
https://github.com/bioconda/bioconda-recipes/issues/42660

**Comment by yodeng** [comment]
https://github.com/bioconda/bioconda-recipes/issues/42660

**Comment by yodeng** [comment]
missing run_exports error #42660(https://github.com/bioconda/bioconda-recipes/issues/42660)

**Comment by mencian** [comment]
Closing in favor of #48714.

**Pull request closed without merging**
