### PR TITLE
Update usher: don't skip on Mac OSX

### PR DESCRIPTION
**Pull request by AngieHinrichs**
Don't skip Mac build for usher; instead, omit ripples-fast if architecture is not x86_64.

Describe your pull request here

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by AngieHinrichs** [comment]
@BiocondaBot please add label

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
It's a bit confusing for users I guess. That the same package with same versions has different binaries. It might be confusing for users and hard to debug. Can we maybe add a pseudo binary that prints a meaningful error message?

**Comment by AngieHinrichs** [comment]
> It's a bit confusing for users I guess. That the same package with same versions has different binaries. It might be confusing for users and hard to debug. Can we maybe add a pseudo binary that prints a meaningful error message?

Yes, it's not a very satisfying solution and is just a short-term measure to get usher v0.6.1 to build on Mac so that Mac users can have the amazing new usher-sampled program, which will make pangolin run a lot faster.  So far there has been some interest in ripples and ripples-fast, but nobody has complained yet about ripples-fast not being available on Mac.  🙂  But pangolin has a lot of users and is a very high priority for us.

Hopefully soon we'll find out how to include the right headers in the bioconda Mac build environment so we can use Intel SIMD instructions like `__builtin_ia32_pminsw128` that is breaking ripples-fast, and then we can re-enable ripples-fast instead of this ugly workaround.

Thanks @bgruening!

**Comment by AngieHinrichs** [comment]
@bgruening I updated build.sh to make a placeholder script version of ripples-fast when skipping it in the build, that prints out this message:
```
Sorry, ripples-fast is temporarily unavailable from bioconda for Mac.
Please chime in on https://github.com/yatisht/usher/issues/310 if this inconveniences you.
```

**Review by rpetit3 — APPROVED** [review]

**Comment by AngieHinrichs** [comment]
Thanks @rpetit3!  Is anything else needed for a merge?

**Comment by AngieHinrichs** [comment]
Happy New Year Bioconda team!  Can this be merged, so that pangolin can use the new faster usher-sampled on Mac as well as linux?  Thanks!

**Comment by rpetit3** [comment]
@BiocondaBot please merge

**Comment by rpetit3** [comment]
@BiocondaBot please update

**Comment by rpetit3** [comment]
@BiocondaBot please merge

**Pull request merged**
