### PR TITLE
gvcftools 0.17.0 recipe

### PR DESCRIPTION
**Pull request by pvanheus**
* [*] I have read the guidelines above.
* [*] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by bgruening** [comment]
The description says its also a bunch of perl scripts? I guess you need perl as runtime dep?

**Comment by pvanheus** [comment]
I fixed the description and added the perl dependency - there is a single perl script.

**Comment by daler** [comment]
@pvanheus looks like the linux package does not build (can't find zlib), and has not been uploaded to anaconda despite being merged in.

@bgruening, any idea why this wasn't picked up as an error by the build system?

**Comment by bgruening** [comment]
My only idea is that for 1-2 days Travis was unreliable because of migrations of the Travis build system. I don't think this was our fault.

**Comment by pvanheus** [comment]
It has zlib as a build and runtime dependency, not sure why it should give a build error?

**Comment by daler** [comment]
True, but the same thing goes for, e.g., samtools where the [`build.sh` has a bunch of fixes](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/samtools/build.sh) to allow it to find zlib.

**Pull request merged**
