### PR TITLE
Update recipe for chanjo

### PR DESCRIPTION
**Pull request by souravsingh**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [ ] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by mbargull** [comment]
Hi @souravsingh, I pushed some changes to your branch, initially to only fix the download URL, hope you don't mind.
Then I tried to make the recipe build again. Sadly, as it stands, there is a dependency, `alchy`, missing.
As `alchy` is not bioinformatics-specific, it should be added to conda-forge (alongside `pydash` [from the same author] on which `alchy` depends).

**Comment by souravsingh** [comment]
Thanks a lot @mbargull for helping. As for the dependencies, I can handle creating recipes for them on conda-forge

**Comment by mbargull** [comment]
That would be awesome! Thanks, @souravsingh!

**Comment by johanneskoester** [comment]
We  have made changes to our build system (migrated from Travis CI to  Circle CI). If you would like to continue working on this PR, please  reopen this PR and update with latest upstream/master.

**Pull request closed without merging**
