### PR TITLE
FlowSorted.Blood.450k

### PR DESCRIPTION
**Pull request by mrlmachado**
* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [X] This PR adds a new recipe.
* [X] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by mrlmachado** [comment]
Hello admins! I'm guessing you are too busy, but wondering when can I get my pull request analysed and merged. Thanks in advance!

**Comment by epruesse** [comment]
@mrlmachado To get the attention of the core or review teams, use the @ notation to ping them - e.g. `ping @bioconda/review`

**Comment by epruesse** [comment]
@mrlmachado Please have a look at the skeleton generator bgruening linked to above. We depend on free-of-charge content hosting on Anaconda Cloud which is meant for software distribution but not data distribution.

**Comment by mrlmachado** [comment]
Sorry for the delay, I created a new PR with the bioconductor skeleton using bioconda-utils. I'm closing this one. Thanks guys

**Comment by mrlmachado** [comment]
https://github.com/bioconda/bioconda-recipes/pull/8957

**Pull request closed without merging**
