### PR TITLE
Add recipe for SCExecute and SCReadCounts 

### PR DESCRIPTION
**Pull request by edwardsnj**
Recipes to add SCExecute and SCReadCounts (python programs) to bioconda. 

These programs are used to analyze NGS single-cell reads.

### CODE REVIEW

**Comment by daler** [comment]
@edwardsnj looks like you're the author. These packages look rather large. Any way to exclude the data either from the releases or by removing the data directories during conda package creation?

**Comment by edwardsnj** [comment]
Sure, I’ll remove the demo data from the build recipe in the morning. The other thing which is making it large is the use of wxpython, which pulls in a lot of other stuff. Wxpython is not needed for command-line use - which is a more common conda use case. Do you have a position on that?

**Comment by daler** [comment]
re: wxpython, the scexecute and screadcounts packages (as hosted on anaconda) don't contain dependencies. Dependencies are only installed on the users machine at install time. The data, on the other hand, was included in the package and therefore consuming hosting space.

Also, looking more closely at the original code, there's a lot going on here -- have you tested that the conda package correctly runs the snakefile?

**Comment by edwardsnj** [comment]
The snakefile is part of the data-demo directory, which I've now deleted from the package. Yes, I hope to *use* these conda packages with snakemake ultimately (but not the other way around).

**Comment by daler** [comment]
Ah. Have you considered separating these and turning them into proper Python packages? Would make updating and maintaining much easier over the long term.

**Comment by edwardsnj** [comment]
> 



> Ah. Have you considered separating these and turning them into proper Python packages? Would make updating and maintaining much easier over the long term.

Do you mean the snakemake workflow (yes, that is the next step, into its own repository), or the two programs themselves? The short answer is that the projects grew up organically and are distributed as binary packages as well as Python source. Whether the projects could be re-structured into a number of python packages is another question, but its not on my critical path right now. 

Is the size of the built packages more reasonable now?

**Comment by daler** [comment]
Yep, I meant making them [Python packages](https://packaging.python.org/en/latest/), likely with scripts provided as [entry points](https://packaging.python.org/en/latest/specifications/entry-points/).

Understandable if that's not a priority, but it makes it easier for people to use and simplifies the maintenance burden in bioconda since the files would be in standard locations and easier to understand. For example, the unconventional build script and any possible interaction of the wrapper script and `LD_LIBRARY_PATH` within conda environments.

I *think* it should be good, but are you able to locally test the artifacts above with your test data?

Size looks good now.

**Comment by edwardsnj** [comment]
I have just checked that these run correctly in docker containers built from the artifact images. No problems!

**Comment by daler** [comment]
@BiocondaBot please merge

**Pull request merged**
