### PR TITLE
Hard-code pysam 0.8.4 in cnvkit recipe

### PR DESCRIPTION
**Pull request by kyleabeauchamp**
cc @etal this will prevent others from running into this via the conda download.

### CODE REVIEW

**Comment by johanneskoester** [comment]
Is this intended as a temporal fix, or is cnvkit really relying on this specific version for some reason?

**Comment by kyleabeauchamp** [comment]
There is a regression pysam 0.9 that breaks some features that are required for cnvkit.  

See https://github.com/pysam-developers/pysam/issues/254

and 

https://github.com/etal/cnvkit/issues/86

**Comment by johanneskoester** [comment]
I see. What about allowing differences in the minor version or using <=? Only if you have the time, it is not a big deal, and you might need to change it again once the issue is fixed, right?

**Comment by kyleabeauchamp** [comment]
Yeah, this is a temporary solution.  I expect the cnvkit author will make a new release in the next day or two.  Hopefully a fix for pysam will happen in 5 or so days.

**Comment by etal** [comment]
I've just rolled a new release of CNVkit that uses the requirement spec `"pysam>=0.8,<0.9"`. Is there anything else I need to do?

**Comment by kyleabeauchamp** [comment]
Nope: see https://github.com/bioconda/bioconda-recipes/pull/1043

**Pull request merged**
