### PR TITLE
New recipe Ninja (ninja_np)

### PR DESCRIPTION
**Pull request by Juke34**
from https://github.com/TravisWheelerLab/NINJA/releases/tag/0.95-cluster_only
used by RepeatModeler2

----

> Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it.

* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [X] This PR adds a new recipe.
* [X] AFAIK, this recipe **is directly relevant to the biological sciences**
      (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

> Everyone has access to the following BiocondaBot commands, which can be given in a comment:
>
>  * `@BiocondaBot please update` will cause the BiocondaBot to merge the master branch into a PR
>  * `@BiocondaBot please add label` will add the `please review & merge` label.
>  * `@BiocondaBot please fetch artifacts` will post links to packages and docker containers built by the CI system. You can use this to test packages locally before merging.
>
> For members of the Bioconda project, the following command is also available:
>
>  * `@BiocondaBot please merge` will cause packages/containers to be uploaded and a PR merged. Someone must approve a PR first! This has the benefit of not wasting CI build time required by manually merging PRs.
>
> If you have questions, please post them in gitter or ping `@bioconda/core` in a comment (if you are not able to directly ping `@bioconda/core` then the bot will repost your comment and enable pinging).

### CODE REVIEW

**Comment by dpryan79** [comment]
The source code likely needs some changes to compile on non-GNU systems like OSX. See https://stackoverflow.com/questions/40515557/compilation-error-on-clock-gettime-and-clock-monotonic/40515669

**Comment by jebrosen** [comment]
Unfortunately it is working fine for me, so I can't troubleshoot so easily. I do see that we don't actually `#include <time.h>` - can you try including and applying this patch?

```diff
diff --git a/NINJA/ClusterManager.hpp b/NINJA/ClusterManager.hpp
index 724fdc3..f37eb88 100644
--- a/NINJA/ClusterManager.hpp
+++ b/NINJA/ClusterManager.hpp
@@ -9,6 +9,7 @@
 #include "DistanceReader.hpp"
 #include "SequenceFileReader.hpp"
 #include <stdlib.h>
+#include <time.h>
 //#include "DistanceReaderExtMem.hpp"
 
 class ClusterManager {
diff --git a/NINJA/TreeBuilderManager.hpp b/NINJA/TreeBuilderManager.hpp
index 6670b31..c8f2767 100644
--- a/NINJA/TreeBuilderManager.hpp
+++ b/NINJA/TreeBuilderManager.hpp
@@ -11,6 +11,7 @@
 #include "SequenceFileReader.hpp"
 #include "TreeBuilderBinHeap.hpp"
 #include <stdlib.h>
+#include <time.h>
 #include "TreeBuilderExtMem.hpp"
 #include "DistanceReaderExtMem.hpp"
 ```

**Comment by Juke34** [comment]
CircleCI runs the test only on linux image on my computer. I don't know how to do to test on OSX image too. @dpryan79 Is there an easy way to activate the osx test too?

**Comment by dpryan79** [comment]
I'll jump on an OSX box tomorrow and look into what's needed to get the constants defined there.

**Comment by jebrosen** [comment]
Does bioconda compile directly on macOS or via a cross-compiler? I have been trying unsuccessfully to figure out how to get the same clang package that is being used on the builder.

**Comment by dpryan79** [comment]
It compiles directly on OSX with a clang copy from conda-forge.

**Comment by jebrosen** [comment]
My guess is it has something to do with [clock_gettime being a relatively recent addition](https://stackoverflow.com/a/5167506) to macOS. The builder seems to set a macOS version of 10.9, but it was not introduced until 10.12. I am running 10.14, which would explain why it works for me.

I will work with NINJA to change/remove the use of these functions, because it appears to be unessential and is even disabled by default at runtime. That could take some time to coordinate, so if it's acceptable it may be appropriate to make this a Linux-only package until a new release can be made.

**Comment by loraine-gueguen** [comment]
@Juke34 Thanks for the repeatmodeler version 2 and ninja recipes!
One of my users would like to use repeatmodeler with the LTR pipeline option, with NINJA, option still not available in the current repeatmodeler conda package (xref: https://github.com/bioconda/bioconda-recipes/blob/master/recipes/repeatmodeler/build.sh#L15, https://github.com/Dfam-consortium/RepeatModeler/issues/62)

Since the NINJA recipe is functional for linux, what do you think about adding `skip: True  # [osx]` in the build section of the recipe until the error with osx is solved? This would make this recipe available in bioconda. And this would then allow to add it in the repeatmodeler recipe ?

**Comment by Juke34** [comment]
Right we can in the same time try a more recent NINJA release

**Comment by loraine-gueguen** [comment]
> we can in the same time try a more recent NINJA release

Yes, but for repeatmodeler, it seems that we need release `0.95-cluster_only`: https://github.com/Dfam-consortium/RepeatModeler#source-distribution-installation

**Comment by loraine-gueguen** [comment]
moved to https://github.com/bioconda/bioconda-recipes/pull/33626

**Pull request closed without merging**
