### PR TITLE
Add bioconductor-ffpe.

### PR DESCRIPTION
**Pull request by cbrueffer**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

New PR since #6792 can't be re-opened.

### CODE REVIEW

**Comment by bgruening** [comment]
@bioconda/os @bioconda/core it seems that the new build system, or more concrete the new OSX image has some problems. It seems that llvm does not work anymore. I think if we remove llvm and use GCC this PR will pass.

Any idea what is going on here? Was our old llvm never used and instead some compile on the travis image? In conda-forge we don't use llvm, so maybe we should migrate the GCC for all recipes?

**Comment by daler** [comment]
@bgruening I don't know about whether llvm was actually used in the past, but I'm in favor of following conda-forge moving forward. Sounds like another `bulk` run though, for which we'll have to work out details on CCI.

**Comment by cbrueffer** [comment]
Seems strange though, other packages that need compiler support worked fine. LLVM can't be completely unused then.

**Comment by rvalieris** [comment]
i am not really familiar with osx, but this has been discussed before, here: https://github.com/bioconda/bioconda-recipes/issues/1332

I think the important part is that llvm package does **not** contain clang.

**Comment by mbargull** [comment]
> In conda-forge we don't use llvm

Are you sure? `toolchain`/`toolchain3` use `clang`:
- https://github.com/conda-forge/toolchain-feedstock/blob/f6661f3766f27bb36157ca2efaafc4f77ba9573a/recipe/activate.sh
- https://github.com/conda-forge/toolchain3-feedstock/blob/fc8244974e5df85fd11cb9c0fb031f840f86e547/recipe/activate.sh

**Comment by mbargull** [comment]
(Also, I think this discussion was mean to address the other PR, i.e., https://github.com/bioconda/bioconda-recipes/pull/6726. This one might just work with `conda 4.3.33` and only fails due to an R package coming from `defaults`, I think.)

**Comment by bgruening** [comment]
@mbargull see here: https://github.com/conda-forge/r-nloptr-feedstock/blob/master/recipe/meta.yaml#L33 & https://github.com/conda-forge/r-sp-feedstock/blob/master/recipe/meta.yaml as an example. toolchain is not always used.

**Comment by mbargull** [comment]
It's not always used, yes. I was just a bit confused about the "we don't use llvm" -- did you mean that more in reference to R packages? (Sorry for going into it that much, I just want to make sure to get the right mindset for this issue.)

**Comment by bgruening** [comment]
Yeah, just talking here about R and non-windows stuff :)

**Comment by johanneskoester** [comment]
@rvalieris is right about the clang thing. I think on travis, the clang command was a symlink to gcc. So, I guess all those packages used the system gcc on travis macos. At least it was like that when we discussed this some months ago.

**Comment by mbargull** [comment]
The package's configure script added `-lgfortran` but not the required RPATH linker flags, see: https://github.com/bioconda/bioconda-recipes/pull/6726#issuecomment-366690571.

**Pull request merged**
