### PR TITLE
Trinity v2.8.6 -- trying to get OSX build to work... 

### PR DESCRIPTION
**Pull request by nextgenusfs**
Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it. Note that if you are not already a member of the bioconda project (meaning that you can't add this label), please ping `@bioconda/core` so that your PR can be reviewed and merged (please note if you'd like to be added to the bioconda project). Please see https://github.com/bioconda/bioconda-recipes/issues/15332 for more details.

* [ ] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [ ] This PR adds a new recipe.
* [ ] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

My local builds are all failing immediately for OSX -- trying on here....

### CODE REVIEW

**Comment by nextgenusfs** [comment]
@dpryan79 I know you've tried to get OSX Trinity to build previously.  Here it seems to actually build -- at least the Trinity checks all say passed and then it dies.  I can't quite figure out why it died?  My local bootstrap testing is not building any OSX recipes right now (don't know why yet). Anyway, thought I'd ask and see if you ran into this before.

**Comment by dpryan79** [comment]
The actual error is:

```
sed -i 's/my $TRIMMOMATIC = "\([^"]\+\)"/my $TRIMMOMATIC = '\''\1'\''/' /Users/distiller/project/miniconda/conda-bld/trinity_1574102056658/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/opt/trinity-2.8.6/Trinity
sed: 1: "/Users/distiller/projec ...": extra characters at the end of d command
```

So it would seem that something isn't escaped properly in the `sed` command for OSX's taste. I have to say that the BSD sed used on OSX is quite picky.

**Comment by nextgenusfs** [comment]
Okay, now looks like back to error you got previously, https://github.com/bioconda/bioconda-recipes/issues/15631?

**Comment by dpryan79** [comment]
Yeah :( I wish I knew why this was happening.

**Comment by mencian** [comment]
Managed to build Trinity (v2.15.1) on OSX in PR [#41767](https://github.com/bioconda/bioconda-recipes/pull/41767). Fair to close this PR?

**Comment by mencian** [comment]
Closing in favor of #41767.

**Pull request closed without merging**
