### PR TITLE
Bump picopore to 1.2.0

### PR DESCRIPTION
**Pull request by scottgigante**
* [Y] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [N] This PR adds a new recipe.
* [Y] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [Y] This PR updates an existing recipe.
* [N] This PR does something else (explain below).

### CODE REVIEW

**Comment by scottgigante** [comment]
@druvus excuse my ignorance, but do you understand what is failing here?
```
$ scripts/travis-run.sh
+bioconda-utils lint recipes config.yml --git-range master HEAD
02:26:11 BIOCONDA INFO Recipes newly unblacklisted:
02:26:11 BIOCONDA INFO Recipes to consider according to git: 
recipes/picopore
02:26:12 BIOCONDA INFO Recipes to lint:
recipes/picopore
02:26:12 BIOCONDA ERROR 
```

**Comment by daler** [comment]
Hi @scottgigante, further down in the log it shows what the issue is, along with a link that will provide more info on what and how to fix: https://travis-ci.org/bioconda/bioconda-recipes/jobs/270665933#L788

**Comment by scottgigante** [comment]
@daler thank you for the advice. Unfortunately, I have implemented the fix recommended under `setup_py_install_args` and the same test continues to fail. Do you have any suggestions? Thanks!

**Comment by daler** [comment]
@scottgigante sorry for the late reply -- .looks like the recipe already has a build script (`build.sh`). It is redundant with the `script:` line you added in `meta.yaml`, so deleting the build script should get you past this linting error.

**Comment by scottgigante** [comment]
Thanks for your help @daler!

**Pull request merged**
