### PR TITLE
remove samtools version restrictions for MetaPhlAn2

### PR DESCRIPTION
**Pull request by alienzj**
Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it. Note that if you are not already a member of the bioconda project (meaning that you can't add this label), please ping `@bioconda/core` so that your PR can be reviewed and merged (please note if you'd like to be added to the bioconda project). Please see https://github.com/bioconda/bioconda-recipes/issues/15332 for more details.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by alienzj** [comment]
@bioconda/core Hi, please add me to bioconda team, thanks very much :+1:

**Comment by alienzj** [comment]
@fbeghini Hello, for fixing this: https://github.com/bioconda/bioconda-recipes/issues/18793

**Comment by fbeghini** [comment]
Hi @alienzj, unfortunately StrainPhlAn (inside MetaPhlAn2) works only with that specific version of samtools

**Comment by alienzj** [comment]
After I read the [documention](https://bitbucket.org/biobakery/metaphlan2/src/dev/), I found the **bcftools** was missing in the **metaphlan2** recipe.

**Comment by alienzj** [comment]
MetaPhlAn2 can run on python3, but StrainPhlAn need python2, if this recipe just supply MetaPhlAn2, so we don't need samtools.

**Comment by fbeghini** [comment]
No, StrainPhlAn works also with Python3, we maintained retro-compatibility with also python2. However, we cannot just provide MetaPhlAn2 since they are not two separate software.

**Pull request closed without merging**
