### PR TITLE
added receipe for bdgenomics.mango

### PR DESCRIPTION
**Pull request by akmorrow13**
Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it. Note that if you are not already a member of the bioconda project (meaning that you can't add this label), please ping `@bioconda/core` so that your PR can be reviewed and merged (please note if you'd like to be added to the bioconda project). Please see https://github.com/bioconda/bioconda-recipes/issues/15332 for more details.

* [ ] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by dpryan79** [comment]
You'll need to add the various bdgenomics dependencies.

**Comment by npavlovikj** [comment]
The current error message is:
```
19:18:14 BIOCONDA INFO (OUT) /opt/conda/conda-bld/mango_1571252876304/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin/mango-submit: line 64: /opt/conda/conda-bld/mango_1571252876304/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin/find-mango-assembly.sh: No such file or directory
```

Looks like "mango-submit" is using "find-mango-assembly.sh" which is not symlinked to `$BINARY_HOME` and thus not found. I would suggest you to symlink the other scripts in "/bin" in "build.sh" as well (or the whole "/bin" directory all together), or change the location of SCRIPT_DIR.

**Comment by dpryan79** [comment]
I've fixed the initial set of problems, though this points out some real oddities in how the software is structured.

**Comment by heuermh** [comment]
@dpryan79
> ...though this points out some real oddities in how the software is structured.

We ran into similar issues with how conda breaks apart our tarballs with symlinks in the Bioconda recipe for [adam](https://github.com/bioconda/bioconda-recipes/tree/master/recipes/adam). The workarounds and patches there are still not entirely satisfactory, see e.g. https://github.com/bigdatagenomics/adam/issues/2225.  Do you have any suggestions as to how to better structure our release artifacts?

**Comment by akmorrow13** [comment]
@dpryan79 would you know why $SP_DIR is set correctly during the initial test phase but is no longer set correctly during the mulled-build build-and-test phase? [This description of conda variables](https://docs.conda.io/projects/conda-build/en/latest/user-guide/environment-variables.html) says that SP_DIR should also be set during test.

**Comment by dpryan79** [comment]
There's no `conda activate` run inside the container, since the base environment contains the package. Given that, no environment variables will be set.

**Comment by dpryan79** [comment]
@heuermh The occasional symlink shouldn't be an issue. The structure problem with the packages seems to be that the jar files aren't being properly installed with pip. They should be treated as data files (to use python lingo).

**Pull request merged**
