### PR TITLE
Snakemake 3.11.1-1 fixes small bug in snakemake/conda.py

### PR DESCRIPTION
**Pull request by holtgrewe**
* [x] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by holtgrewe** [comment]
@johanneskoester may I merge this?

I hope it would take the urgency of another hotfix upstream from you.

**Comment by holtgrewe** [comment]
Hm, I'll just merge, I really need this fix. I hope that's OK.

**Comment by holtgrewe** [comment]
@johanneskoester yarg, my dependency comes from pypi and not here. So, can we have a 3.11.2 from upstream?

**Comment by johanneskoester** [comment]
I'll release a version within the next hour. Sorry for the bug in 3.11.1. please note that you can always fork snakemake, patch it and install via pip git+https://...

**Pull request merged**
