### PR TITLE
Update planemo to 0.62.1

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`planemo`](https://bioconda.github.io/recipes/planemo/README.html): **0.61.0** &rarr; **0.62.1**

[install with bioconda](http://bioconda.github.io/recipes/planemo/README.html) [Conda](https://anaconda.org/bioconda/planemo/files)

Info | Link
-----|-----
Recipe | [`recipes/planemo`](https://github.com//bioconda/bioconda-recipes/tree/bump/planemo/recipes/planemo) (click to view/edit other files)
Releases |[https://pypi.org/pypi/planemo/json](https://pypi.org/pypi/planemo/json)

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by dfornika** [comment]
Build error is:

```
error: package directory 'planemo/cwl/cwl2script' does not exist
```

`cwl2script` is included in planemo as a submodule:

https://github.com/galaxyproject/planemo/tree/0.62.0/planemo/cwl

**Comment by dpryan79** [comment]
While we can change this to using a git_url, I think they should just fix the uploaded file on pypi. Can you create an issue upstream?

**Comment by nsoranzo** [comment]
New Planemo 0.62.1 coming, I've pulled 0.62.0 from PyPI.

**Comment by bgruening** [comment]
Thanks @nsoranzo

**Pull request merged**
