### PR TITLE
rm r-spp from blacklist

### PR DESCRIPTION
**Pull request by daler**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

Attempting rebuild of r-spp on osx. xref #5108 and #6122

### CODE REVIEW

**Comment by daler** [comment]
@yesimon you had helped on the last `r-spp` in #5108, any suggestions for this one?

**Comment by daler** [comment]
(upstream issue is https://github.com/hms-dbmi/spp/issues/12)

**Comment by yesimon** [comment]
My guess is that the failure is linking to boost libraries using `libc++` which is incompatible with compiling spp with `libstdc++`. However, `r-spp` is only using `boost/tokenizer` which is a header only library, so I think the trick is to get autotools to compile with boost header only instead of linking the shared library.

**Comment by johanneskoester** [comment]
We  have made changes to our build system (migrated from Travis CI to  Circle CI). If you would like to continue working on this PR, please  reopen this PR and update with latest upstream/master.

**Pull request closed without merging**
