### PR TITLE
Update bcftools to 1.12

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`bcftools`](https://bioconda.github.io/recipes/bcftools/README.html): **1.11** &rarr; **1.12**

[install with bioconda](http://bioconda.github.io/recipes/bcftools/README.html) [Conda](https://anaconda.org/bioconda/bcftools/files)

Info | Link
-----|-----
Recipe | [`recipes/bcftools`](https://github.com//bioconda/bioconda-recipes/tree/bump/bcftools/recipes/bcftools) (click to view/edit other files)
Releases |[https://github.com/samtools/bcftools/releases](https://github.com/samtools/bcftools/releases)
Author | `@samtools`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by dpryan79** [comment]
We need to merge in the accompanying htslib release first.

**Comment by jmarshall** [comment]
I'm slightly surprised this built against htslib 1.11 at all :smile: but — like samtools — this will need htslib bumped in _recipes/bcftools/conda_build_config.yaml_ first too.

**Comment by dpryan79** [comment]
This depends on blas? Is that new?

**Comment by jmarshall** [comment]
It's not new — that came along with gsl in #16989, and presumably that warning has been in the build logs since then. That library will always be installed as it's a prerequisite of gsl (assuming you picked the right flavour of gsl :shrug: — cf pysam-developers/pysam@07169eac87ec60958bc48508e83fe0063fa219ee), but depending on policy it could probably be added to bcftools's prereqs too — especially if that would force the right GSL flavour.

But I'm very much not an expert in these aspects :smile:

**Comment by dpryan79** [comment]
I'd feel a bit safer if we add it to the dependencies here. I don't want to have the case where gsl starts linking against an incompatible cblas and that causes problems.

**Comment by jmarshall** [comment]
Yep, I ran into something like that in the pysam script linked above. But I'll defer to leaving this one in your capable hands :smile:

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Pull request merged**
