### PR TITLE
MultiQC: Version 1.0 release.

### PR DESCRIPTION
**Pull request by ewels**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by dpryan79** [comment]
@ewels: I have PRs open now on conda-forge to add the two missing dependencies.

**Comment by bgruening** [comment]
@dpryan79 please also look at: conda-forge/staged-recipes#2988, conda-forge/staged-recipes#2990 and conda-forge/staged-recipes#2989

**Comment by dpryan79** [comment]
@bgruening Thanks, I hadn't noticed those!

**Comment by ewels** [comment]
I also finally sat down and managed to get the bioconda environment to work on my machine and went through all of the docs properly. So this code has now moved into a branch (hence this PR closed). I'll reopen from the branch when the conda-forge PRs are done. Let me know if you'd like me to open it before then.

Phil

**Comment by ewels** [comment]
..and thanks @dpryan79! Good to see that the contents of your PRs looked similar to mine 😉

**Pull request closed without merging**
