### PR TITLE
Update quatradis

### PR DESCRIPTION
**Pull request by maplesond**
Attempting to fix dependencies based on feedback by BioConda devs  (closed old PRs)

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by maplesond** [comment]
@marcelm, it looks like I'm missing Biopython, despite having it included in the dependencies.  Is there something I'm doing wrong here?

**Comment by marcelm** [comment]
In short, you need to fix your `requirements.txt` to list `biopython` instead of `Bio`.

Unfortunately, the name that you use when you `import` a package can be different from the name under which the package is registered on PyPI. (You run `pip install biopython`, but you need to `import Bio`, for example.) In Python-packaging terminology, the thing that you upload to PyPI is called a "distribution" and the thing that you import is the "package". So in short: The package name can be different from the distribution name.

There’s a difference between the Python distributions [bio](https://pypi.org/project/bio/) and [biopython](https://pypi.org/project/biopython/). The `bio` in your `requirements.txt` pulls in the former, but because `bio` happens to depend on `biopython`, you also get that, so `import Bio` works and you never notice it.

You need to change your `requirements.txt` so that it lists `biopython` instead of `Bio`.

Also, you still list `bgzip` in `requirements.txt`, but you need to remove that as well. If you don’t, that will be the error message next time.

**Comment by marcelm** [comment]
Since you need to make another release, you may be tempted to open another pull request, but can you please do me a favor and not do that this time? It’s difficult to keep track of things. Even if you close the old PRs that no longer apply, the discussion is scattered over multiple places.

Instead, let’s continue over at #33535, which is the bot-generated PR that updates quatradis to 0.6.0. As soon as you make a new release, the bot will see that you have done so and update the PR (within an hour or so). Since you are a member of the bioconda organization, you (and I) can then edit the PR to get the recipe to work.

**Comment by marcelm** [comment]
By the way, are you actually using PyQt5 anywhere in QuaTradis? It’s also listed in `requirements.txt`, but I cannot find any code that actually imports it. It’s a heavy depenency and you should remove it if you don’t actually need it.

**Comment by marcelm** [comment]
And it appears that you are not using Cython either. Are you?

**Comment by maplesond** [comment]
Hi @marcelm, no not directly, although I think pyqt was required for some other complementary tools: snakeviz.  Can't remember why cython was there.  At one point it was required but maybe it's not necessary any longer, I'll take it out and see if it all still hangs together.

**Comment by marcelm** [comment]
I needed to add `setuptools` to the runtime dependencies because quatradis imports `pkg_resources`. This seems to work now. Note that [using pkg_resources is deprecated](https://setuptools.pypa.io/en/latest/pkg_resources.html) and you may want to consider replacing its use with `importlib.resources`.

I’ll approve this now and you can merge this yourself if you’re happy with the changes.

**Review by marcelm — APPROVED** [review]

**Comment by maplesond** [comment]
Fantastic!  Thanks for all your help @marcelm!  I'll take a look at importlib next time.

**Comment by marcelm** [comment]
You’re welcome!

**Pull request merged**
