### PR TITLE
hera: fix CONDA_HTSLIB typo

### PR DESCRIPTION
**Pull request by mbargull**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

followup fix for #7385

### CODE REVIEW

**Comment by bgruening** [comment]
Upps.

**Comment by bgruening** [comment]
Feel free to commit directly to bulk, you should be able to do so.

**Comment by mbargull** [comment]
Yeah, at least the reviewer should've seen that XD

**Comment by mbargull** [comment]
kk

**Pull request merged**
