### PR TITLE
Add correct license info

### PR DESCRIPTION
**Pull request by bebatut**
* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [X] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by peterjc** [comment]
I see that a licence file was only added to the upstream repository today:
https://bitbucket.org/nsegata/hclust2/src/516f299f3c7b1cd2876c66fecacb7014fe44d6ae/license.txt?at=default&fileviewer=file-view-default

Technically the older releases have no stated license - unless you have a statement from the author making this retrospective?

Once the recipe is updated to the next release we can include ``license_file`` in ``meta.yaml`` as well.

**Comment by bgruening** [comment]
@peterjc any suggestions?
@bebatut do you have an author statement?

**Comment by peterjc** [comment]
I'm not familiar with the tool - was there a statement on a public mailing list or something about the license change/choice, and if it was retrospective?

**Comment by johanneskoester** [comment]
We  have made changes to our build system (migrated from Travis CI to  Circle CI). If you would like to continue working on this PR, please  reopen this PR and update with latest upstream/master.

**Pull request closed without merging**
