### PR TITLE
add msisensor v0.2

### PR DESCRIPTION
**Pull request by lovelyzhang**
- [x]  I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
- [x]  This PR adds a new recipe.

### CODE REVIEW

**Comment by lovelyzhang** [comment]
```
#!/bin/bash -eo pipefail
bioconda-utils lint recipes config.yml \
--loglevel debug --full-report \
--git-range master HEAD
Traceback (most recent call last):
  File "/home/circleci/project/miniconda/bin/bioconda-utils", line 11, in <module>
    load_entry_point('bioconda-utils==0.13.0', 'console_scripts', 'bioconda-utils')()
  File "/home/circleci/project/miniconda/lib/python3.6/site-packages/bioconda_utils/cli.py", line 638, in main
    bioconductor_skeleton, pypi_check, clean_cran_skeleton,
  File "/home/circleci/project/miniconda/lib/python3.6/site-packages/argh/dispatching.py", line 328, in dispatch_commands
    dispatch(parser, *args, **kwargs)
  File "/home/circleci/project/miniconda/lib/python3.6/site-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/home/circleci/project/miniconda/lib/python3.6/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/home/circleci/project/miniconda/lib/python3.6/site-packages/argh/dispatching.py", line 260, in _call
    result = function(*positional, **keywords)
  File "/home/circleci/project/miniconda/lib/python3.6/site-packages/bioconda_utils/cli.py", line 227, in lint
    df = linting.channel_dataframe(cache=cache)
  File "/home/circleci/project/miniconda/lib/python3.6/site-packages/bioconda_utils/linting.py", line 122, in channel_dataframe
    repo, noarch = utils.get_channel_repodata(channel, platform)
  File "/home/circleci/project/miniconda/lib/python3.6/site-packages/bioconda_utils/utils.py", line 630, in get_channel_repodata
    .format(noarch_repodata, noarch_url))
requests.exceptions.HTTPError: 530  for https://conda.anaconda.org/defaults/noarch/repodata.json
Exited with code 1
```
What's wrong? How can I retry circleci test?

**Comment by micknudsen** [comment]
The run requirement `samtools ==0.1.19` is rather annoying in that it prevents `msisensor` from being installed in a conda environment alongside many other bioinformatics tools (unless, of course, you are OK with running a very old version of `samtools`).

Is it somehow possible to compile `samtools` _into_ `msisensor` and eliminate this restriction?

**Comment by Beifang** [comment]
we prefer to use samtools-0.1.19 or low version because high versions (>0.1.20) are htslib samtools, which require users to set LD-LIBRARY_PATH for .so DLL. Although we have released a standalone version v0.4 based on htslib samtools.

**Comment by lovelyzhang** [comment]
https://github.com/niu-lab/msisensor has include samtools 0.1.19 and release v0.5

**Pull request closed without merging**
