### PR TITLE
Super distance

### PR DESCRIPTION
**Pull request by leomrtns**
- [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
- [x] This PR adds a new recipe.
- [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).

### CODE REVIEW

**Comment by dpryan79** [comment]
@bioconda-bot recheck

**Comment by dpryan79** [comment]
@leomrtns Do you have circleci enabled on your fork?

**Comment by leomrtns** [comment]
tks for the help. I may have activated it yesterday after my fail here, sorry about that. I will try to remove it and let you know (as you may see this is my first attempt :)

**Comment by dpryan79** [comment]
No worries, thanks for the PR!

**Comment by leomrtns** [comment]
@dpryan79 ok I removed it from circleCI. BTW it worked locally (bioconda-utils build and conda-build), but maybe because I have 'check' installed?

**Comment by dpryan79** [comment]
The normal CI testing is running now :) Shall I add you to bioconda once this is merged?

**Comment by leomrtns** [comment]
awesome! yes please, I plan to keep updating this software regularly. 
thank you!

**Comment by dpryan79** [comment]
You'll want to install bioconda-utils and docker and work on this a bit locally.

**Comment by leomrtns** [comment]
No problem, I'll do that. thanks for the help.

**Pull request closed without merging**
