### PR TITLE
Add ms2pip recipe

### PR DESCRIPTION
**Pull request by RalfG**
Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

 * `@BiocondaBot please update` will cause the BiocondaBot to merge the master branch into a PR
 * `@BiocondaBot please add label` will add the `please review & merge` label.
 * `@BiocondaBot please fetch artifacts` will post links to packages and docker containers built by the CI system. You can use this to test packages locally before merging.

For members of the Bioconda project, the following command is also available:

 * `@BiocondaBot please merge` will cause packages/containers to be uploaded and a PR merged. Someone must approve a PR first! This has the benefit of not wasting CI build time required by manually merging PRs.

If you have questions, please post them in gitter or ping `@bioconda/core` in a comment (if you are not able to directly ping `@bioconda/core` then the bot will repost your comment and enable pinging).

### CODE REVIEW

**Comment by RalfG** [comment]
Linting failed, says noarch python needs to be added. But the package has Cython modules that need to be compiled. Can I circumvent this check by adding a compiler to the build requirements?

**Comment by RalfG** [comment]
@bioconda/core
During compilation of a Cython module (with imported .c code) the build crashes with the following errors:
```
13:57:26 BIOCONDA INFO (OUT)     {standard input}: Assembler messages:
13:57:26 BIOCONDA INFO (OUT)     {standard input}:985822: Warning: end of file not at end of a line; newline inserted
13:57:26 BIOCONDA INFO (OUT)     {standard input}:987416: Error: unknown pseudo-op: `.l1112'
13:57:26 BIOCONDA INFO (OUT)     {standard input}: Error: open CFI at the end of file; missing .cfi_endproc directive
13:57:26 BIOCONDA INFO (OUT)     x86_64-conda_cos6-linux-gnu-cc: internal compiler error: Killed (program cc1)
```
Locally the recipe builds without errors (as well as building setup.py wheels in the manylinux1 container).  Could this have to do something with incompatible compiler/assembler versions? Should I try to specify gcc and binutils versions in the recipe?

**Comment by dpryan79** [comment]
I don't know that specifying a gcc version will do anything, the same version is used for all recipes. Is there some assembly language code in the source code?

**Comment by dpryan79** [comment]
A bit of googling suggests that the compiler ran out of memory and that removing `-pipe` from the CFLAGS may free up enough.

**Comment by RalfG** [comment]
@dpryan79 Thanks for the input!
There's no assembly in the source code.

Out of memory could very well be the problem! Compiling the decision tree models (that are big if-else structures in c) takes some time and memory. Where do I remove `-pipe` from the CFLAGS? Should I add a makefile patch (as described [here](https://bioconda.github.io/contributor/troubleshooting.html#id8)) or can I do this in the recipe?

**Comment by dpryan79** [comment]
You might need a patch, since I'm not sure if this is getting the pipe from the `CFLAGS` environment variable or if it's hardcoded internally. In the former case you can just change `$CFLAGS` in `build.sh`, which is certainly easier and something to try first.

**Comment by RalfG** [comment]
@BiocondaBot update

**Comment by RalfG** [comment]
@BiocondaBot please add label

**Pull request closed without merging**
