### PR TITLE
Patch wrong version dwgsim-v1.1.11 to dwgsim-v0.1.11

### PR DESCRIPTION
**Pull request by clintval**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [x] This PR does something else (explain below).

First task in solving #12904.

### CODE REVIEW

**Comment by bgruening** [comment]
Mh, sorry this seems to fail because of zlib could not found.

**Comment by clintval** [comment]
I actually know how to fix this. I'll un-assign you for review while I debug. Thanks!

**Comment by epruesse** [comment]
@bgruening I take it this requires labelling the 1.1.11 as broken?

**Comment by bgruening** [comment]
Yes :)

**Comment by clintval** [comment]
I never figured out how to fix this. Closing this PR since it's quite stale... the underlying issue is still open!

**Pull request closed without merging**
