### PR TITLE
Add run dependencies for Quast

### PR DESCRIPTION
**Pull request by bebatut**
* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [ ] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [X] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by druvus** [comment]
@bebatut @bgruening @alexeigurevich I just realized that quast is included in `build-fail-blacklist` so those updates were never built. Currently on my mobile so I can't fix it right now.

**Comment by alexeigurevich** [comment]
@druvus Do you know whether quast was removed from the black list? It looks like currently available last version is still 4.5 (see https://bioconda.github.io/recipes.html#recipes)

**Comment by druvus** [comment]
It seems it was not removed so I suggest to make a new PR where you remove it from the black list. I can try to do it during the weekend if you don't have time.

**Comment by alexeigurevich** [comment]
Thanks, I've just do this here: https://github.com/bioconda/bioconda-recipes/pull/6591

**Pull request merged**
