### PR TITLE
Update Dependencies for scanpy-scripts

### PR DESCRIPTION
**Pull request by LustigePerson**
The dependencies in the receipt were not up-to-date with the dependencies in the Git repo ([setup.py](https://github.com/ebi-gene-expression-group/scanpy-scripts/blob/v1.0.0/setup.py)).

## Changed:
  - `scanpy>=1.6.0`              --> `scanpy>=1.8.0`
  - `bbknn>=1.3.12,<1.5.0`  -->  `bbknn>=1.5.0`

## Added:
  - `scrublet`

## Removed:
  - `fa2`
  - `numpy<1.19.5`

### CODE REVIEW

**Comment by LustigePerson** [comment]
@BiocondaBot please add label

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Comment by pcm32** [comment]
Hi, this merge is a bit problematic for us as it will change the underlying package version without changing scanpy-script version, which has a good potential to wreck things in a number of galaxy tools and others that we have. We were going to make a new release where we would be adding some fixes to 1.8.0 so that data tests on scanpy-scripts, not run here, would pass. Would it possible to unmerge this and delete the new container @dpryan79 ?

**Comment by pcm32** [comment]
We were planning with @pinin4fjords to make a release 0.5.0 of this conda package very soon, and we could incorporate those changes there, but I'm troubled by the build bump only on the containers without the scanpy-script version change, as it means that Galaxy modules requesting for the 0.4.1 or so version that this had will now be getting a container (or conda package) with a scanpy version for which they haven't been tested.

**Comment by pcm32** [comment]
Ok, my bad, the move to 1.8.0 had already happened, I thought that we hadn't done it yet. So all good here, don't mind me @dpryan79 .

**Pull request merged**
