### PR TITLE
ont-fast5-api: Add dependency progressbar33

### PR DESCRIPTION
**Pull request by dfornika**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by dfornika** [comment]
The `ont-fast5-api` recipe was missing a dependency (`progressbar33`)

**Comment by epruesse** [comment]
Thank you @dfornika!

Can you think of a simple test case to add to the recipe to make sure the issue stays fixed?

**Comment by dfornika** [comment]
@epruesse I ran into this issue when trying to run the `multi_to_single-fast5` utility. I've added a test command that fails without `progressbar33`.

**Comment by epruesse** [comment]
@dfornika - great, thanks!

**Comment by epruesse** [comment]
Thanks @dfornika

**Pull request merged**
