### PR TITLE
remove fwdpy11 from blacklist

### PR DESCRIPTION
**Pull request by molpopgen**
:information_source:
Bioconda has finished the [GCC7 migration](https://github.com/bioconda/bioconda-recipes/issues/13578). If you are dealing with C/C++ or Python package it can be that you need to rebuild other dependent packages. [Bioconda utils - update-pinning](https://bioconda.github.io/updating.html#updating-recipes-for-a-pinning-change) will assist you with that. If you have any questions please use [issue 13578](https://github.com/bioconda/bioconda-recipes/issues/13578).

----------------

* [ ] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [ ] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [X] This PR does something else (explain below).

I am removing fwdpy11 from the blacklist.  I recently update the recipe to 0.2.1, but noticed that it never became available for download b/c it was blacklisted.

Related: should the linting be checking for updates to blacklisted packages and issuing a warning?

### CODE REVIEW

**Comment by molpopgen** [comment]
@bgruening -- the CI is reporting an error, yet I believe it to be incorrect:

```
RuntimeError: Setuptools downloading is disabled in conda build. Be sure to add all dependencies in the meta.yaml  url=https://pypi.org/simple/svgwrite/
```

That package is not mentioned anywhere in fwdpy11's setup.py.  All dependencies from setup.py are listed in the meta.yaml, too, and one can see that they are installed.

**Comment by molpopgen** [comment]
@bioconda/core -- need some help here.

See above re: setuptools comment.  I have added svgwrite as a host and run dependency, and the issue is not fixed.  That package is not required by mine.  I seem unable to move forward due to this.  What is going on?

**Comment by dpryan79** [comment]
I can get it to build on Linux, but it's having a hard time finding gsl on OSX: https://github.com/bioconda/bioconda-recipes/pull/14160

**Comment by molpopgen** [comment]
Ok, but what does that mean for the failing Linux build?  I build it on
Linux routinely for work.  The failure is here, and with this svgwrite
business (see earlier comments).

**Comment by dpryan79** [comment]
That error seems to have something to do with the `--gcc` flag. If you're happy with just having a linux build, then you can add `or osx` to the list of skips in my PR and merge it.

**Comment by molpopgen** [comment]
Sorry, that doesn't make sense to me.  The linjx build is failing, not os
ox.  Please take a look at the CI report.  The GCC flag cannot affect
setuptools attempting to import svgwrite.

**Comment by dpryan79** [comment]
I know, my PR passes on Linux but not yet on OSX.

**Comment by molpopgen** [comment]
Got it--I had missed that you had a separate PR.

I'll try to update mine--the GSL issue is likely due to the fragility of
the various cmake macros, which have trouble finding GSL in conda envs.
__
Kevin Thornton
Associate Professor
Ecology and Evolutionary Biology
UC Irvine
www.molpopgen.org
github.com/molpopgen
github.com/ThorntonLab

**Comment by molpopgen** [comment]
ok, here's a new one.  My meta.yaml differs from the one in your PR only by
the pybind11 version.  Mine fails CI on Linux while yours does not.
__
Kevin Thornton
Associate Professor
Ecology and Evolutionary Biology
UC Irvine
www.molpopgen.org
github.com/molpopgen
github.com/ThorntonLab

**Comment by molpopgen** [comment]
@dpryan79 --thanks for the help.  This is all sorted now.

**Comment by dpryan79** [comment]
Awesome!

**Pull request merged**
