### PR TITLE
Update cyvcf2 to 0.10.2

### PR DESCRIPTION
**Pull request by epruesse**
Update `cyvcf2`: **0.10.0** &rarr; **0.10.2**

***

[Package Info](https://bioconda.github.io/recipes/cyvcf2/README.html) | [Recipe Folder](https://github.com/bioconda/bioconda-recipes/tree/master/recipes/cyvcf2) | [Upstream Home](https://github.com/brentp/cyvcf2) | [Upstream Releases](https://github.com/vladsaveliev/cyvcf2/releases)  

***

This pull request was automatically generated by [bioconda-utils](https://github.com/bioconda/bioconda-utils).

### CODE REVIEW

**Comment by epruesse** [comment]
MacOS fails with

```
clang: error: linker command failed with exit code 1 (use -v to see invocation)
warning: cyvcf2/cyvcf2.pxd:26:16: Declarations should not be declared inline.
warning: cyvcf2/cyvcf2.pxd:188:14: 'BCF_HT_FLAG' redeclared 
warning: cyvcf2/cyvcf2.pxd:276:30: Declarations should not be declared inline.
error: command 'clang' failed with exit status 1
```

ping @vladsaveliev  - can you take a look at this?

**Comment by vladsaveliev** [comment]
Hi @epruesse,

Looks like the `crypt` is not available on macos. Removing it helps on my mac and I don't see any other problems with the installation. Following up on the cyvcf2 issue: https://github.com/brentp/cyvcf2/issues/91

Vlad

**Comment by brentp** [comment]
I just tagged v0.10.2 which makes the change suggested by @vladsaveliev please give that a try.
thanks for updating the recipe!

**Comment by brentp** [comment]
cyvcf2 recently changed to include htslib as a submodule. 
not sure how to add that to the recipe: 
` git submodule update --init` should do it, but I thnk it downloads a tag...

**Comment by vladsaveliev** [comment]
Right, `git submodule update --init` should help, but should we try to add `htslib` as a conda dependency? Will try

**Comment by vladsaveliev** [comment]
Nope, `htslib` as a dependency errors:

```
ImportError: dlopen(/Users/vsaveliev/tmp/cyvcf2/miniconda/envs/cyvcf2_0102/lib/python3.6/site-packages/cyvcf2/cyvcf2.cpython-36m-darwin.so, 2): Symbol not found: _bcf_float_missing
```

By the way @brentp, the recipe downloads the release tarball from https://github.com/brentp/cyvcf2/releases which doesn't contain htslib source. Can switch to pulling a tag here, but you might want to add htslib source into the tarball anyway?

**Comment by brentp** [comment]
> By the way @brentp, the recipe downloads the release tarball from https://github.com/brentp/cyvcf2/releases which doesn't contain htslib source. Can switch to pulling a tag here, but you might want to add htslib source into the tarball anyway?

that is automtically generated by github. is there a way to adjust it?

**Comment by vladsaveliev** [comment]
Can't figure out a way to make GitHub clone recursively in releases... I think the only way is to generate a tarball with:

```
python setup.py sdist
```

which will go into `dist/cyvcf2-0.10.2.tar.gz`, and upload it instead

**Comment by epruesse** [comment]
@brentp You can build and upload artifacts from Travis using the releases deployment provider. See e.g. https://github.com/epruesse/SINA/blob/master/.travis.yml

I’m not sure about htslib as part of your sources. It seems common, but not really pretty.  Can’t we pull that in as a package?

**Comment by brentp** [comment]
I include htslib to ease installation outside of conda, so it would probably be best to use the bioconda version of conda if possible. I'm happy to help facilitate that if I can, but haven't had time to dig into improving the packaging on my end.

**Comment by vladsaveliev** [comment]
Hmm, wondering why CI has stopped running after new commits.

**Comment by bgruening** [comment]
This can happen once in a while. Hope it works now. Thanks!

**Comment by epruesse** [comment]
It’s been happening a lot lately. In particular when I auto bump. I can’t find anything in the circle API clearly meant to trigger a build. Technically, I could have something check whether the lint is pending and automate the close-reopen. Not very pretty though.

**Comment by vladsaveliev** [comment]
My version that's because we are kind of installing htslib twice: first explicitly with configure/make, then implicitly when linking cyvcf2 source together with htslib within `setup.py`. But if I drop htslib installation from build.sh, it'll still fail at some point.

**Comment by ccwang002** [comment]
I tried a different approach in PR #13726 by patching the `setup.py` to link to the conda htslib instead of compiling one inside cyvcf2. All the tests passed for 0.10.8 and lets see if this approach can work for the future releases as well.

**Pull request closed without merging**
