### PR TITLE
Updating dependency to htslib from libdeflate

### PR DESCRIPTION
**Pull request by jpuritz**
This should help with issues identified in #17212

Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it. Note that if you are not already a member of the bioconda project (meaning that you can't add this label), please ping `@bioconda/core` so that your PR can be reviewed and merged (please note if you'd like to be added to the bioconda project). Please see https://github.com/bioconda/bioconda-recipes/issues/15332 for more details.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by dpryan79** [comment]
This was already pinned properly, so I don't think this will have any effect. The issue is with older builds sometimes being installed if someone uses `conda install` in an existing environment.

**Comment by jpuritz** [comment]
OK.  I wasn't 100% sure this would fix my original issue, but this also made sense to me because (as I read it) `bedtools` depends on `htslib` and not `libdeflate` directly.

My original issue is that when I am creating a new OS X environment for `ddocent` (https://github.com/bioconda/bioconda-recipes/tree/master/recipes/ddocent), the pinning is not working properly and I get:

```
bioconda/osx-64::bedtools-2.26.0-0
bioconda/osx-64::htslib-1.8-h57f8fdf_2
bioconda/osx-64::samtools-1.4.1-0
```

Within the environment `conda update bedtools` gives me this:

```
The following packages will be UPDATED:

  bedtools                                         2.26.0-0 --> 2.29.0-hbf07bdc_0
  htslib                                     1.8-h57f8fdf_2 --> 1.9-h3a161e8_7
  samtools                                          1.4.1-0 --> 1.9-h8aa4d43_12

The following packages will be SUPERSEDED by a higher-priority channel:

  libdeflate         conda-forge::libdeflate-1.3-h01d97ff_0 --> bioconda::libdeflate-1.0-h1de35cc_1
```

I was following the recent updates to `samtools` that fixed a similar issue.  Though, it's entirely possible that this has nothing to do with these issues.

**Comment by dpryan79** [comment]
Ah, yeah, this would be fixed by adding libdeflate in as a runtime dependency of ddocent. It's obviously not really a runtime dependency, but it'd get around the conda solver doing the wrong thing. Running `conda update` seems to be fixing the env, for what little that's worth :(

The original libdeflate dependency here is due to bedtools vendoring htslib, so thereby needing libdeflate to compile it. It actually doesn't need either of them during run time, though maybe that could be changed (it'd certainly make the binary smaller).

**Comment by dpryan79** [comment]
curl could be removed too it seems. Mind changing your PR to remove those? That'd certainly clean the bedtools recipe up, which would be nice :) Also, libdeflate could be moved to the build section, since if it's used it's statically compiled in.

**Comment by jpuritz** [comment]
I think that will work.  Thanks for your help.

**Comment by dpryan79** [comment]
Great, that certainly cleans the recipe up :)

**Comment by dpryan79** [comment]
@bioconda-bot merge

**Pull request merged**
