### PR TITLE
SIRIUS: fix LD_LIBRARY_PATH 

### PR DESCRIPTION
**Pull request by bernt-matthias**
which should reveal `error while loading shared libraries: libz.so.1`

Describe your pull request here

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
Thanks for adding tests, let me know if you need help fixing the build.

**Comment by dpryan79** [comment]
I suspect we'll need some bash magic to update LD_LIBRARY_PATH. Something like the following should work:

```
dname=`dirname "$0"`
export LD_LIBRARY_PATH="${dname}/../lib"
```

**Comment by bernt-matthias** [comment]
Thanks @dpryan79 .. lets try

**Comment by dpryan79** [comment]
Ah, exec ignore the environment. This will be needed: https://stackoverflow.com/questions/22869637/setting-variables-with-executing-a-command-with-exec

**Comment by bernt-matthias** [comment]
> Ah, exec ignores the environment.

Seems like a reasonable explanation. But I rather think that the specification of the patches is still not correct. You can see this because the test for Linux was successful for my first commit (https://github.com/bioconda/bioconda-recipes/pull/34220/commits/baf44fb7dab7a7a211e3ee2c8a544b16ee886eb1) applying the patch for Linux. And tests failed again after I added the patch for OSx

**Comment by bernt-matthias** [comment]
So, this should be it. Not sure why the patch is not needed for OSx. 

Should we keep the additional test in `meta.yaml`? The ones in `run_test.sh` should be sufficient.

**Comment by bernt-matthias** [comment]
Once the tests are successful I would like to add a commit that reverts everything... Just to check if the conda based test and the container based test are both failing.

**Comment by bernt-matthias** [comment]
@dpryan79 it seems that the containerized test (`run_test.sh`) is not running if there is no test command in `meta.yaml`. Can you verify this?

**Comment by bernt-matthias** [comment]
I added the single test command to meta.yml again.

**Comment by bernt-matthias** [comment]
@BiocondaBot please add label

**Comment by dpryan79** [comment]
@bernt-matthias yup, run_test.sh isn't in the container so the mulled test skips it. Anyway, merge at your leisure.

**Comment by bernt-matthias** [comment]
@BiocondaBot please merge

**Pull request merged**
