### PR TITLE
Update recipe for libstatgen 1.0.5

### PR DESCRIPTION
**Pull request by npavlovikj**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by dfornika** [comment]
The macos build doesn't seem to like this line: https://github.com/statgen/libStatGen/blob/d81bef3f3d6d5fb9adcc323664880d2b01668ba3/general/StringHash.h#L55

**Comment by npavlovikj** [comment]
Thanks @dfornika ! It looks like adding "using namespace std;" fixed the Linux build, but broke the OSX one :/ I will have some time this afternoon to play with this, but if you have a fix, please feel free to add the changes.

**Comment by npavlovikj** [comment]
@dfornika , everything built fine now. Can you please check the recipe and let me know if it looks ok to you?

**Comment by dfornika** [comment]
Looks good to me. Thanks @npavlovikj !

**Pull request merged**
