### PR TITLE
Add igphyml

### PR DESCRIPTION
**Pull request by dpryan79**
Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it. Note that if you are not already a member of the bioconda project (meaning that you can't add this label), please ping `@bioconda/core` so that your PR can be reviewed and merged (please note if you'd like to be added to the bioconda project). Please see https://github.com/bioconda/bioconda-recipes/issues/15332 for more details.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by dpryan79** [comment]
Xref: https://github.com/bioconda/bioconda-recipes/pull/18930

**Comment by dpryan79** [comment]
@bioconda-bot please fetch artifacts

**Comment by dpryan79** [comment]
@PertuyF Can you see if this works? I'm not entirely sure how this program will work since it really does hardcode the exact path to the motifs in the source code. I've tried making that relative to where the binary is, but I'm suspecting that that won't work and that the source code will have to get modified. That's probably also the only way to make relocatable binaries like would be needed for a conda install.

**Comment by PertuyF** [comment]
@dpryan79 binary works OK, but we're missing the `IGPHYML_PATH` variable that should point to `$PREFIX/share/igphyml/motifs/` to pass the tests.

And for Linux version I get a warning when setting `--threads` that binary was not compiled with OpenMP. And I can confirm the behavior is different with a locally built omp-enabled version.

Unfortunately I can't access a machine to test OSX version.

**Comment by dpryan79** [comment]
I'm amazed that works at all. I guess this needs an activation script. The OMP thing just needs a new `-D` flag I suspect.

**Comment by PertuyF** [comment]
For some reason my test file wasn't included for final test phase. Although I think I followed the doc.
Anyway, it is likely better to include the original `examples` dir (268KB) for users to follow the doc examples.

Can be OK to use these files to run tests, but I can also include my `test.fasta` in `${PREFIX}/share/igphyml/test/` and save us a few minutes of computation...

**Comment by PertuyF** [comment]
There is something wrong with tests during mulled-build. Do you have a clue @dpryan79 ?

**Comment by dpryan79** [comment]
Test files don't make it into the container for testing, since they're not part of the end package (just the recipe). For the mulled tests there's just a binary being called, so the activation scripts are never run.

**Comment by PertuyF** [comment]
Good job, this looks cleaner!
Just noticed I missed last version, so I'll bump to `1.1.0`
After that we can close my initial PR and merge this one.

Next step will be Blas support :)

**Comment by dpryan79** [comment]
@PertuyF Go ahead and approve this PR and then merge it with `@bioconda-bot please merge` whenever you're ready.

**Comment by PertuyF** [comment]
@bioconda-bot please merge

**Comment by dpryan79** [comment]
Meh, normal merge it is then.

**Comment by dpryan79** [comment]
It seems there are some networking issues that borked the bot's upload. We'll just use the regular CI then to upload things.

**Comment by PertuyF** [comment]
Good for me, as long as the package is released!

**Pull request merged**
