### PR TITLE
Stacks update to 2.0Beta8c

### PR DESCRIPTION
**Pull request by pbordron**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by mbargull** [comment]
Hope you don't mind. I added a commit which should fix the macOS build.
I'm just curious whether you have any means to test if the OpenMP functionality works under macOS. Would be helpful to know if we can use `llvm-openmp` for other packages in the future :wink:

**Comment by pbordron** [comment]
@mbargull I kown I have forget it but I was stuck with a `checking for functional regular expressions... needed gcc>4.9+` error

I do not have access to osx to investigate it, however, I do not get this error with clang-4.0 on my ubuntu 16.04.

**Comment by mbargull** [comment]
That error was just because of the missing `-std=c++11`, so should be fixed now.

**Comment by pbordron** [comment]
Good to know. Thx

**Comment by mbargull** [comment]
Do you have any small example command for which you are sure it uses OpenMP? We could let that run on the CI system to verify the macOS build is fine.

**Comment by pbordron** [comment]
Unfortunatly, I have no example :(
Maybe in the manual?

**Comment by mbargull** [comment]
Let's just merge and see how things go.
@bioconda/osx: Does anybody have the possibility to test OpenMP on macOS for this one? (I have no idea what you have to do to run OpenMP-specific code, though..)

**Comment by epruesse** [comment]
IIRC the default clang we compile with is too old for OpenMP support. You'd have to build with `llvm-devel` I think, but I don't know what that's do to ABI compatibility.

**Pull request merged**
