### PR TITLE
Prokka

### PR DESCRIPTION
**Pull request by Slugger70**
* [x] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

Something goes wrong with bioperl during docker build in Travis.

### CODE REVIEW

**Comment by bgruening** [comment]
@jerowe do you have any idea what is going on here? Do we need finally a bioperl 1.7?

**Comment by jerowe** [comment]
Let me take a look.

**Comment by jerowe** [comment]
The new logs ar eso pretty!

**Comment by jerowe** [comment]
It looks like it wants a particular version of makeblastdb

https://travis-ci.org/bioconda/bioconda-recipes/jobs/210862803#L409

I don't know if you can hold off on perl things, but I am working a lot on the perl conda skeleton creator. My goal is to be able to build Moose and BioPerl in one go from the skeletons. I'm nearly there, but it will take some more time.

**Comment by jerowe** [comment]
That reminds me, are we using the gcc available on the conda-forge docker image, or do we need to explicitly add gcc in the build deps?

If we are not using the conda-forge gcc any perl modules that require cpanm to install a perl module that has a Makefile will not work.

**Comment by bgruening** [comment]
For perl is was ok to use the conda-forge GCC in the hope that we get a new packaged GCC soon.

**Comment by bgruening** [comment]
@jerowe the makeblast error is indeed a OSX problem. The Linux problem is here: https://travis-ci.org/bioconda/bioconda-recipes/jobs/210862802#L1254

**Pull request merged**
