### PR TITLE
Update Maxquant

### PR DESCRIPTION
**Pull request by veitveit**
Describe your pull request here
This is an update of MaxQuant to 2.0.3.0 and also of the dotnet library
----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>
@BiocndaBot 
For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by veitveit** [comment]
@BiocondaBot please fetch artifacts

**Comment by veitveit** [comment]
@BiocondaBot please add label

**Comment by veitveit** [comment]
@BiocondaBot please fetch artifacts

**Comment by veitveit** [comment]
Should be ready now. I had to change to mono as dotnet brings too many issues

**Review by wen-chen — APPROVED** [review]

**Comment by bgruening** [comment]
This is not good :( dotnet is recommended for this tool and mono 5 which you are using with the follow-up PR is very very old.
The performance is probably much worse. What is the problem with dotnet? Can this not be fixed at the dotnet level?

**Comment by bgruening** [comment]
Did you fill an issue somewhere?

**Comment by veitveit** [comment]
The error happens after starting MaxQuant. Not sure how to simplify this, as it is closed source and they do not care too much about linux.
```
Configuring 

Unhandled Exception: System.ComponentModel.Win32Exception: No such file or directory
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at QueueingSystem.WorkDispatcher.ProcessSingleRunExternalProcess(Int32 taskIndex, Int32 threadIndex)
   at QueueingSystem.WorkDispatcher.DoWork(Int32 taskIndex, Int32 threadIndex)
   at QueueingSystem.WorkDispatcher.Work(Object threadIndex)
   at System.Threading.Thread.ThreadMain_ParameterizedThreadStart(Object parameter)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
/data/anaconda/envs/nf-core-maxquant/bin/maxquant: line 4: 260816 Aborted                 (core dumped) dotnet $DIR/MaxQuantCmd.exe $@
```

**Comment by veitveit** [comment]
Or do you think this can be reported there? Nailed it down to the following commands:
```
maxquant -c t.xml # create example parameter file
maxquant t.xml # running it. It fails before looking for data files other than the parameter file
```


```

**Comment by bgruening** [comment]
They do not care much about Mono, that is one reason why we have been using dotnet - next to the reason that mono is dead end. Does the old version of MQ works for you with dotnet?

**Comment by veitveit** [comment]
This error was with dotnet

**Comment by veitveit** [comment]
Failing (with dotnet): 1.6.17.0
Failing (with mono) due to symbolic links: 1.6.10.43
The older version most likely are also based on mono

**Comment by bgruening** [comment]
Maxquant (Version 1.6.17.0) with dotnet is working, we are using this for months with hundreds of executions. Maybe it is your input file?

All I'm saying is that with an open dotnet runtime, mono has most likely no future. Mono is also not supported by the MQ people, so reverting here to mono is not a good way forward. 

(The dotnet package is also available on Windows, so if you think this is a unix problem you could try it on Windows as well.)

**Comment by veitveit** [comment]
Is it possible that you have additional libraries installed when running MQ (I assume in galaxy)? 

I get an error also with the default file after adding fasta+raw file as input. 

Actually, I get MaxQuantCmd 1.6.5.0 after installing conda maxquant=1.6.17.0
Same happens for the Bioncontainer.

So you guys actually are running a much older version of MQ

**Comment by bgruening** [comment]
This is known, they screwed up the version ID afaik. Can you get this version working with dotnet runtime, or do you see the same error? If you see a similar error, its probably your test file/env and not the package.

Anyway, can you maybe get a test in this package so we see the error here with the dotnet runtime?

**Comment by veitveit** [comment]
I now managed to run my test case with 1.6.17.0 (sorry, my fault). Had to change to an older parameter file.

Will try this now: build with dotnet 3.1 and if that does not work, then add a larger test case (takes a while to run though). 

This taking way too much time, but giving up is not an option :-)

**Comment by bgruening** [comment]
:heart: 

I just don't want to end up here with a dead runtime. Thanks @veitveit

**Comment by veitveit** [comment]
OK, we are making progress:
MQ 2.0.3.0 seems to work with dotnet 3.1 (previously 2.1). Lower and higher versions of dotnet are not accepted by MQ.

__Issue No.1__: This breaks the built as "noarch" appears to require dotnet 5.0.404:
```
failed to get install actions, retrying.  exception was: Unsatisfiable dependencies for platform noarch: {"__glibc[version='>=2.17|>=2.17,<3.0.a0']", "libgcc-ng[version='>=4.9|>=7.3.0|>=7.5.0|>=9.3.0|>=9.4.0|>=7.2.0']", 'dotnet=5.0.404', 'feature:|@/linux-64::__glibc==2.31=0', 'python', 'feature:/linux-64::__glibc==2.31=0', "libgcc-ng[version='>=7.5.0|>=9.3.0|>=9.4.0']"}
WARNING:conda_build.build:failed to get install actions, retrying.  exception was: Unsatisfiable dependencies for platform noarch: {"__glibc[version='>=2.17|>=2.17,<3.0.a0']", "libgcc-ng[version='>=4.9|>=7.3.0|>=7.5.0|>=9.3.0|>=9.4.0|>=7.2.0']", 'dotnet=5.0.404', 'feature:|@/linux-64::__glibc==2.31=0', 'python', 'feature:/linux-64::__glibc==2.31=0', "libgcc-ng[version='>=7.5.0|>=9.3.0|>=9.4.0']"}
```

__Issue No. 2:__  then the symbolic links do not work anymore as this breaks the Thermo library. I found comments about the same issue with mono in some prior commits of the meta.xml file where they downgraded from mono version 6 to mono version 5. 

Do we have any further options?

**Comment by bgruening** [comment]
Try this here: https://github.com/conda-forge/dotnet-feedstock/blob/master/recipe/meta.yaml#L60

And take inspiration from metamorpheus: https://github.com/conda-forge/metamorpheus-feedstock/blob/master/recipe/meta.yaml

**Comment by veitveit** [comment]
Can you clarify that a  bit? I do not know even where to start when comparing e.g. quite different metamorpheus recipe to the current MQ one.

**Comment by veitveit** [comment]
MQ does not work with any version of dotnet than 3.1.. And with 3.1, MQ cannot read symlinks.

**Pull request merged**
