### PR TITLE
Update tb-profiler to 2.6.1

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`tb-profiler`](https://bioconda.github.io/recipes/tb-profiler/README.html): **2.6** &rarr; **2.6.1**

[install with bioconda](http://bioconda.github.io/recipes/tb-profiler/README.html) [Conda](https://anaconda.org/bioconda/tb-profiler/files)

Info | Link
-----|-----
Recipe | [`recipes/tb-profiler`](https://github.com//bioconda/bioconda-recipes/tree/bump/tb_profiler/recipes/tb-profiler) (click to view/edit other files)
Releases |[https://github.com/jodyphelan/TBProfiler/tags](https://github.com/jodyphelan/TBProfiler/tags)
Author | @jodyphelan
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by jodyphelan** [comment]
@bioconda-bot merge

**Comment by dpryan79** [comment]
Looks like the bot isn't fully functional again :(

**Comment by jodyphelan** [comment]
Is it anything to do with that I requested the review from myself?

**Comment by dpryan79** [comment]
No, the bot has been down recently (the aws node keeps running out of hard drive space for some reason).

**Pull request merged**
