### PR TITLE
new recipe: ensembl-xs

### PR DESCRIPTION
**Pull request by matthdsm**
Adds ensembl-xs recipe

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by matthdsm** [comment]
@bioconda/build-system, any idea how to fix the test? Do I need to add the extra dependencies the CI 'warns' about? Or do I need to patch something?

**Comment by pinin4fjords** [comment]
> @bioconda/build-system, any idea how to fix the test? Do I need to add the extra dependencies the CI 'warns' about? Or do I need to patch something?

I guess the choice is to add that module as an upstream recipe, or else just do a CPAN install as part of the build.sh (I did [something similar](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/perl-atlas-modules/build.sh) previously).

**Comment by matthdsm** [comment]
> or else just do a CPAN install as part of the build.sh 

Is that allowed 😅

**Comment by pinin4fjords** [comment]
> > or else just do a CPAN install as part of the build.sh
> 
> Is that allowed 😅

If it's just the one bio-centric upstream thing you need, and it's easy to add, it's definitely nicer to add the recipe.

In the above example I wasn't going to make a recipe in conda forge for every single missing Perl module I needed, and it was approved, so I assume I wasn't being excessively naughty ;-).

**Comment by matthdsm** [comment]
@bioconda/perl 
I've got somewhat of an issue. This module needs to have some parts compiled and then a perl module needs to be installed. The issue is that the tests seem to depend on some modules from a non-cpan-installable repo (https://github.com/Ensembl/ensembl). What would be the approved way of getting all dependecies in order and/or fixing this recipe so it's usable?

**Comment by matthdsm** [comment]
Not worth the effort

**Pull request closed without merging**
