### PR TITLE
rtg-tools: update to 3.10.1

### PR DESCRIPTION
**Pull request by Lenbok**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by Lenbok** [comment]
@bgruening Help please? I don't understand why with a minor version bump I get CI failing.

I tried running the bootstrap method to build and run tests locally. linting is fine, basic test (no docker, no mulled) is fine, but the mulled test fails for me with what looks like an unrelated error (at least nothing like what the CI errors looked like):

````
len@noir:bioconda-recipes [base] rtg-tools-3.10.1? ± bioconda-utils build recipes config.yml --docker --mulled-test --git-range master                                                                                          
09:37:49 BIOCONDA INFO Recipes newly unblacklisted:

09:37:49 BIOCONDA INFO Recipes modified according to git: rtg-tools
09:38:15 BIOCONDA INFO DOCKER: Building image "tmp-bioconda-builder" from /tmp/tmpzkaljyi3
..
09:40:49 BIOCONDA INFO DOCKER: Built docker image tag=tmp-bioconda-builder
09:40:49 BIOCONDA INFO blacklist: abyss/1.5.2, abyss/1.9.0, aenum, amos, amptk, ant, antarna, antismash, arvados-cli, azure-cli, bcbio-rnaseq, bellmans-gapc, bio-vcf, bioconductor-atlasrdf, bioconductor-camera, bioconductor-cosmiq, bioconductor-edger/3.12.1, bioconductor-faahko, bioconductor-flagme, bioconductor-ggbio/1.22.0, bioconductor-ipo, bioconductor-jaspar2018, bioconductor-jmosaics, bioconductor-lobstahs, bioconductor-masigpro/1.49.4, bioconductor-meshsim, bioconductor-metab, bioconductor-metams, bioconductor-mmdiff, bioconductor-mmnet, bioconductor-msmseda, bioconductor-msnbase, bioconductor-msnid, bioconductor-mspurity, bioconductor-mvgst, bioconductor-mzr, bioconductor-org.dm.eg.db/3.3.0, bioconductor-pbase, bioconductor-profia, bioconductor-proloc, bioconductor-prolocgui, bioconductor-proteomicsannotationhubdata, bioconductor-rcytoscape, bioconductor-risa, bioconductor-simat, bioconductor-synapter, bioconductor-xcms, bioconductor-yamss, biomaj, blast-legacy/2.2.22, blast/2.2.21, bowtie/1.0.0, bpipe, brass, bucketcache, bumbershoot, bwa/0.6.2, c-ares, cansnper, canvas, cap-mirseq, carna, cas-offinder, cassiopee, cgat-scripts, check-sort-order, circos-tools, cmfinder, cmfinder/0.2, cmv, cortex_con, cosi2, cufflinks, customprodb, denovogear, desman, dialign-tx, dimspy, dimspy/1.0.0, dimspy/1.1.0, dimspy/1.2.0, disco/1.2, discovar-denovo, domclust, dreamtools, dsk, e-pcr, edlib, effectivet3, emperor, erds, esimsa, expansionhunter, export2graphlan, fastme, fastuniq, fermikit, fgap, fiji/20151222, flexbar/3.3.0, flock, footprint, frc, frogs, fseq, funcannot, fwdpp, fwdpp/0.5.3, fwdpp/0.5.4, fwdpy11, gap2seq, garnet, gclib, genblasta, genepender, genepop, genomebaser, genometester4, genometools, genometools-genometools/1.5.10-nocairo, gffcompare, gfinisher, gfold, ghc/6.8.3, ghmm, ghostx, ghostz, gnu-getopt, guidescan, hap.py, hivtrace, hubward, hurry.filesize, icqsol, idba, ig-checkfcs, igblast/1.4.0, igvtools, illuminate, imfusion/0.3.0, imfusion/0.3.2, infernal/1.0.2, intarna/2.1.0, intemap, intervalstats, intervaltree, jali, java-jdk/7.0.91, jemalloc, jq, k-slam, kat/2.3.1, kat/2.3.4, kmerinshort, knot, koeken, kraken, kraken-ea, krona/2.5, krona/2.6, lapack, libbambamc/0.5.00, libdb, libmuscle, lightning, locarna, locarna/1.8.10, locarna/1.8.11, locarna/1.8.12, locarna/1.8.7, locarna/1.8.9, locarna/1.9.0, locarna/1.9.1, lofreq, lorma, ls-gkm, mapsembler2, mapsplice, megahit, meneco/1.5.2, meryl, metagene_annotator, metaprob, metavelvet, metavelvet-sl, metavelvet-sl-feature-extraction, metavelvet-sl-pipeline, metavelvet/1.1.01, metilene, microbecensus, mimodd, minialign, mirdeep2/2.0.0.8, moreutils, mosaik, mothur/1.36.1, mrbayes, mreps, ms, music, mustang, mysql-connector-c, nanonet, nanosplit, nasm, netifaces, ngmerge, ngseqbasic, nlstradamus, novoplasty, np-likeness-scorer, nspdk, ntcard, nucleoatac/0.3.1, oases, ocrad/0.21, odose, oligotyping, oligotyping/2.0, onto2nx, openbabel/2.3.2, openslide, osra/2.0.1, osra/2.1.0, panoct, pantools, parafly, pash, pbdagcon, percolator, perl-bio-db-sam, perl-biox-workflow-command, perl-btlib/0.19, perl-dbm-deep, perl-estscan1/1.3, perl-estscan2/2.1, perl-file-homedir, perl-hpc-runner-command-plugin-logger-sqlite/0.0.3, perl-hpc-runner-command/3.2.13, perl-locale-maketext-simple/0.21, perl-mixin-linewise, perl-mldbm-sync, perl-module-fromperlver/0.008002, perl-moosex-app/1.39, perl-pcap, perl-pod-checker/1.60, perl-pod-coverage-trustpod/0.100003, perl-pod-elemental, perl-set-intervaltree, perl-sql-statement, perl-statistics-ttest, perl-symbol-util/0.0203, perl-text-ansitable/0.48, phipack, phylotoast, picard/1.97, piler, pkiss, plastid, plink2, polymutt, popt, poretools/0.5.1, portcullis/1.1.0, portcullis/1.1.1, pout2mzid, primerprospector, prinseq, proot, prophyle/0.2.1, prosic, pycoqc, pyfasta, pygresql, pysftp, pytest-marks, pytest-timeout, python-levenshtein, pyvcf, pyvcf/0.6.7, qcumber, qiime/1.9.1, r-DGEclustering, r-ampvis, r-annotables, r-argumentcheck, r-asics, r-basejump, r-bcbiobase, r-bcbiornaseq, r-bio3d, r-biom, r-biomark, r-boutroslabplottinggeneral, r-chbutils, r-cimpl, r-cnogpro, r-data.table/1.10.4, r-dbchip, r-deoptimr, r-diptest, r-diptest/0.75_7, r-dpeak, r-drc, r-dynamictreecut, r-gam, r-gbm, r-genabel, r-genabel.data, r-genenet, r-genometricorr, r-george, r-giant, r-gprofiler, r-gpseq, r-grimport, r-gsalib, r-gsmoothr, r-haplo.stats, r-histonehmm, r-ic10trainingdata, r-ichorcna, r-icluster, r-idr, r-inlinedocs, r-intego, r-km.ci, r-kmsurv, r-kriging, r-lme4qtl, r-lsd, r-maldiquant, r-matrixeqtl, r-metarnaseq, r-microseq, r-mixomics, r-mlgt, r-mmgenome, r-mqtl, r-msqrob, r-nastiseq, r-ncbit, r-ngsplot, r-ngsplot-hg19, r-ngsplot-hg38, r-ngsplot-mm10, r-pamr, r-patpro, r-peer, r-phangorn, r-phewas, r-pinfsc50, r-plasmidprofiler, r-pore, r-precrec, r-prestor, r-probmetab, r-propcis, r-pscbs/0.61.0, r-purbayes, r-qiimer, r-qorts, r-qtl, r-quorts, r-rBLAST, r-raceid3, r-rcircos, r-readbrukerflexdata, r-readmzxmldata, r-rematch2, r-rentrez, r-robustrankaggreg, r-rphylip, r-rubic, r-scimpute, r-seqinr, r-smvar, r-snpassoc, r-soap-nmr, r-solarius, r-spieceasi, r-tfmpvalue, r-wasabi, r-workflowscriptscommon, r-xmlrpc, r-xnomial, r-zerone, ra-integrate, rdflib-jsonld, rdkit/2015.09.2, rdkit/2016.03.3, rdock, reago, real, regex, relocate2, relocate2/2.0.1, remurna, rmap, rnabob, rnaclust, rnashapes/3.3.0, saffrontree, sam, samtools/0.1.19, samtools/1.1, scikit-bio, searchgui/3.2.20, secimtools, semeta, sff2fastq, shiver, shorah, short-read-connector, sistr_cmd, slclust, sloika, smalt, smashbenchmarking, smina, smoove, snap, snippy/3.0, snpomatic, snvphyl-tools, soapaligner, soapcoverage, soapdenovo2, soapdenovo2-gapcloser, somatic-sniper, spanki, spectral_hk, spingo, sprai, sprinkles, sqlitebrowser, swiftlink, tablet, talloc, tedna, tpp, transcomb, transtermhp, trimmomatic/0.35, vcftools/0.1.10, vcftools/0.1.11, visceral-evaluatesegmentation, vnl, wgs-assembler, xcftools, xdg
09:40:49 BIOCONDA INFO Generating DAG
09:40:49 BIOCONDA INFO Inspected 0 of 1 recipes
09:40:49 BIOCONDA INFO Building and testing 1 recipes in total
09:40:49 BIOCONDA INFO Recipes to build: 
rtg-tools
09:40:49 BIOCONDA INFO Building and testing subdag 1 of 1 (1 recipes)
09:40:49 BIOCONDA INFO Determining expected packages
Setting build platform. This is only useful when pretending to be on another platform, such as for rendering necessary dependencies on a non-native platform. I trust that you know what you're doing.
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
Adding in variants from internal_defaults
Adding in variants from /tmp/miniconda/miniconda/conda_build_config.yaml
Adding in variants from /tmp/miniconda/miniconda/lib/python3.6/site-packages/bioconda_utils/bioconda_utils-conda_build_config.yaml
Downloading: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 12/12 [00:09<00:00,  1.02files/s]
Attempting to finalize metadata for rtg-tools01, 17.5MB/s]
Downloading: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 12/12 [00:11<00:00,  1.28s/files]
09:41:17 BIOCONDA INFO BUILD START recipes/rtg-tools.5MB/s]
09:41:38 BIOCONDA ERROR COMMAND FAILED: docker run -t --net host --rm -v /tmp/tmpgehlyk11/build_script.bash:/opt/build_script.bash -v /tmp/miniconda/miniconda/conda-bld:/opt/host-conda-bld -v /home/len/dev/bioconda-recipes/recipes/rtg-tools:/opt/recipe -e CONDA_SHLVL=1 -e CONDA_PROMPT_MODIFIER=(base)  -e CONDA_EXE=/tmp/miniconda/miniconda/bin/conda -e LANG=en_NZ.utf8 -e CONDA_PYTHON_EXE=/tmp/miniconda/miniconda/bin/python -e CONDA_DEFAULT_ENV=base -e CONDA_ROOT=/tmp/miniconda/miniconda -e CONDA_ALLOW_SOFTLINKS=false -e HOST_USER_ID=1672 tmp-bioconda-builder /bin/bash /opt/build_script.bash
09:41:38 BIOCONDA ERROR STDOUT+STDERR:5MB/s]
/opt/build_script.bash: /opt/build_script.bash: is a directory


09:41:38 BIOCONDA ERROR BUILD FAILED recipes/rtg-tools
09:41:39 BIOCONDA ERROR BUILD SUMMARY: of 1 recipes, 1 failed and 0 were skipped. Details of recipes and environments follow.
09:41:39 BIOCONDA ERROR BUILD SUMMARY: FAILED recipe recipes/rtg-tools
````

**Comment by bgruening** [comment]
Just a guess but can it be that this version does not work well with Java 11?

**Comment by Lenbok** [comment]
Support for Java 11 was already added in 3.10, so that's unlikely to be the problem.

**Comment by Lenbok** [comment]
@bgruening I managed to reproduce the mulled-test failure locally (my docker was old), and the error is:

````
/ # rtg vcfeval --help
/usr/local/bin/java: error while loading shared libraries: libz.so.1: cannot open shared object file: No such file or directory
Could not automatically choose percentage based memory allocation, check configuration. Using Java default.
/usr/local/bin/java: error while loading shared libraries: libz.so.1: cannot open shared object file: No such file or directory
````

So it looks like the openjdk-11 is not including zlib. However this is probably a problem with the openjdk-11 package in general rather than with rtg-tools, as even the java provided jar command fails in this environment:

````
/ # jar -help
jar: error while loading shared libraries: libz.so.1: cannot open shared object file: No such file or directory
````

Is fixing that something that you know how to do?

**Comment by Lenbok** [comment]
@bgruening Indeed, java itself is not working either:
````
/ # java -version
java: error while loading shared libraries: libz.so.1: cannot open shared object file: No such file or directory
````
So presumably this will affect any package depending on java that hasn't explicitly restricted its java to a working version?

The package plan printed out during the mulled test build indicated that java was indeed coming from conda-forge:
````
[Jan 22 14:43:27] STEP Run image [continuumio/miniconda3:4.3.27] with command [[/bin/sh -c conda install  -c conda-forge -c file:///tmp/miniconda/miniconda/conda-bld -c bioconda -c defaults  rtg-tools=3.10.1=0 -p /usr/local --co
py --yes --quiet]]
[Jan 22 14:43:27] DEBU Creating container [step-98a7dee19d]
[Jan 22 14:43:27] DEBU Created container [fe641db30be0 step-98a7dee19d], starting it
[Jan 22 14:43:27] DEBU Container [fe641db30be0 step-98a7dee19d] started, waiting for completion
.[Jan 22 14:44:05] SOUT 
.[Jan 22 14:45:10] SOUT 
[Jan 22 14:45:10] SOUT Package plan for installation in environment /usr/local:
[Jan 22 14:45:10] SOUT 
[Jan 22 14:45:10] SOUT The following NEW packages will be INSTALLED:
[Jan 22 14:45:10] SOUT 
[Jan 22 14:45:10] SOUT openjdk:   11.0.1-h14c3975_1014 conda-forge
[Jan 22 14:45:10] SOUT rtg-tools: 3.10.1-0             file:///tmp/miniconda/miniconda/conda-bld
[Jan 22 14:45:10] SOUT 
````

Would you please be able to file the issue? I started to, but realized my understanding of how this all fits together is so incomplete I don't really know how to clearly express the issue other than saying to look over here at this issue :-). (e.g.: they want the output of `conda list` and `conda info`, but the docker container doesn't have conda inside it)

**Comment by Lenbok** [comment]
@bgruening Adding explicit zlib requirement allows the mulled tests to pass. It's not ideal, but are you OK if this is merged, or do you have another suggestion?

(I also fixed a separate issue unrelated to the test failure)

**Pull request merged**
