### PR TITLE
Update shigatyper to 2.0.2

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`shigatyper`](https://bioconda.github.io/recipes/shigatyper/README.html): **2.0.1** &rarr; **2.0.2**

[install with bioconda](http://bioconda.github.io/recipes/shigatyper/README.html) [Conda](https://anaconda.org/bioconda/shigatyper/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/shigatyper`](https://github.com//bioconda/bioconda-recipes/tree/bump/shigatyper/recipes/shigatyper) (click to view/edit other files)
Summary | Typing tool for Shigella spp. from WGS Illumina sequencing
Home | [https://github.com/CFSAN-Biostatistics/shigatyper](https://github.com/CFSAN-Biostatistics/shigatyper)
Releases |[https://github.com/CFSAN-Biostatistics/shigatyper/tags](https://github.com/CFSAN-Biostatistics/shigatyper/tags)
Author | `@CFSAN-Biostatistics`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by crashfrog** [comment]
Build is failing on the basis of `patch`, but I don't understand the error:

'''
2022-10-26T01:30:50.7264909Z 01:30:50 BIOCONDA INFO (OUT) ## Package Plan ##
2022-10-26T01:30:50.7265384Z 01:30:50 BIOCONDA INFO (OUT) 
2022-10-26T01:30:50.7266357Z 01:30:50 BIOCONDA INFO (OUT)   environment location: /opt/conda/conda-bld/shigatyper_1666747703048/_build_env
2022-10-26T01:30:50.7266999Z 01:30:50 BIOCONDA INFO (OUT) 
2022-10-26T01:30:50.7267283Z 01:30:50 BIOCONDA INFO (OUT) 
2022-10-26T01:30:50.7480686Z 01:30:50 BIOCONDA INFO (OUT) Source cache directory is: /opt/conda/conda-bld/src_cache
2022-10-26T01:30:50.7481564Z 01:30:50 BIOCONDA INFO (OUT) INFO:conda_build.source:Source cache directory is: /opt/conda/conda-bld/src_cache
2022-10-26T01:30:50.7482310Z 01:30:50 BIOCONDA INFO (OUT) Downloading source to cache: conda-package-2.0.2_08df10fdcf.tar.gz
2022-10-26T01:30:50.7483118Z 01:30:50 BIOCONDA INFO (OUT) INFO:conda_build.source:Downloading source to cache: conda-package-2.0.2_08df10fdcf.tar.gz
2022-10-26T01:30:50.7483991Z 01:30:50 BIOCONDA INFO (OUT) Downloading https://github.com/CFSAN-Biostatistics/shigatyper/archive/refs/tags/conda-package-2.0.2.tar.gz
2022-10-26T01:30:50.7484899Z 01:30:50 BIOCONDA INFO (OUT) INFO:conda_build.source:Downloading https://github.com/CFSAN-Biostatistics/shigatyper/archive/refs/tags/conda-package-2.0.2.tar.gz
2022-10-26T01:30:50.7506697Z 01:30:50 BIOCONDA INFO (OUT) DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): github.com:443
2022-10-26T01:30:50.9455609Z 01:30:50 BIOCONDA INFO (OUT) DEBUG:urllib3.connectionpool:https://github.com:443 "GET /CFSAN-Biostatistics/shigatyper/archive/refs/tags/conda-package-2.0.2.tar.gz HTTP/1.1" 302 0
2022-10-26T01:30:50.9480620Z 01:30:50 BIOCONDA INFO (OUT) DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): codeload.github.com:443
2022-10-26T01:30:51.1582341Z 01:30:51 BIOCONDA INFO (OUT) DEBUG:urllib3.connectionpool:https://codeload.github.com:443 "GET /CFSAN-Biostatistics/shigatyper/tar.gz/refs/tags/conda-package-2.0.2 HTTP/1.1" 200 None
2022-10-26T01:30:51.1774655Z 01:30:51 BIOCONDA INFO (OUT) Success
2022-10-26T01:30:51.1775417Z 01:30:51 BIOCONDA INFO (OUT) INFO:conda_build.source:Success
2022-10-26T01:30:51.1775864Z 01:30:51 BIOCONDA INFO (OUT) Extracting download
2022-10-26T01:30:51.1926644Z 01:30:51 BIOCONDA INFO (OUT) Applying patch: /opt/recipe/add-index.patch
2022-10-26T01:30:51.3613819Z 01:30:51 BIOCONDA INFO (OUT) Applying patch: /opt/recipe/add-index.patch with args:
2022-10-26T01:30:51.3614591Z 01:30:51 BIOCONDA INFO (OUT) ['-Np1', '-i', '/tmp/tmp2pl7za3s/add-index.patch.native', '--binary']
2022-10-26T01:30:51.4153879Z 01:30:51 BIOCONDA INFO (OUT) checking file setup.py
2022-10-26T01:30:51.4154429Z 01:30:51 BIOCONDA INFO (OUT) Hunk #1 succeeded at 14 (offset 2 lines).
2022-10-26T01:30:51.4696316Z 01:30:51 BIOCONDA INFO (OUT) patching file setup.py
2022-10-26T01:30:51.4710867Z 01:30:51 BIOCONDA INFO (OUT) Hunk #1 succeeded at 14 (offset 2 lines).
2022-10-26T01:30:51.4712015Z 01:30:51 BIOCONDA INFO (OUT) Applying patch: /opt/recipe/add-outdir.patch
2022-10-26T01:30:51.6389218Z 01:30:51 BIOCONDA INFO (OUT) Applying patch: /opt/recipe/add-outdir.patch with args:
2022-10-26T01:30:51.6390262Z 01:30:51 BIOCONDA INFO (OUT) ['-Np1', '-i', '/tmp/tmpfgkobx86/add-outdir.patch.native', '--binary']
2022-10-26T01:30:51.6941234Z 01:30:51 BIOCONDA INFO (OUT) checking file shigatyper/shigatyper.py
2022-10-26T01:30:51.6953363Z 01:30:51 BIOCONDA INFO (OUT) Hunk #1 FAILED at 1.
2022-10-26T01:30:51.6953844Z 01:30:51 BIOCONDA INFO (OUT) Hunk #2 succeeded at 88 with fuzz 2 (offset 3 lines).
2022-10-26T01:30:51.6954279Z 01:30:51 BIOCONDA INFO (OUT) Hunk #3 succeeded at 509 (offset 3 lines).
2022-10-26T01:30:51.6954828Z 01:30:51 BIOCONDA INFO (OUT) Hunk #4 succeeded at 518 (offset 3 lines).
2022-10-26T01:30:51.6955322Z 01:30:51 BIOCONDA INFO (OUT) Hunk #5 succeeded at 559 with fuzz 2 (offset 3 lines).
2022-10-26T01:30:51.6955722Z 01:30:51 BIOCONDA INFO (OUT) Hunk #6 FAILED at 600.
2022-10-26T01:30:51.6956116Z 01:30:51 BIOCONDA INFO (OUT) 2 out of 6 hunks FAILED
2022-10-26T01:30:51.6985476Z 01:30:51 BIOCONDA INFO (OUT) Warning: failed to download source.  If building, will try again after downloading recipe dependencies.
2022-10-26T01:30:51.6986037Z 01:30:51 BIOCONDA INFO (OUT) Error was:
2022-10-26T01:30:51.6987311Z 01:30:51 BIOCONDA INFO (OUT) Command '['/opt/conda/bin/patch', '--no-backup-if-mismatch', '--batch', '-Np1', '-i', '/tmp/tmpfgkobx86/add-outdir.patch.native', '--binary', '--dry-run']' returned non-zero exit status 1.
2022-10-26T01:30:51.6988013Z 01:30:51 BIOCONDA INFO (OUT) Traceback (most recent call last):
2022-10-26T01:30:51.6988619Z 01:30:51 BIOCONDA INFO (OUT)   File "/opt/conda/bin/conda-mambabuild", line 10, in <module>
2022-10-26T01:30:51.6989072Z 01:30:51 BIOCONDA INFO (OUT)     sys.exit(main())
2022-10-26T01:30:51.6990001Z 01:30:51 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.7/site-packages/boa/cli/mambabuild.py", line 239, in main
2022-10-26T01:30:51.7001716Z 01:30:51 BIOCONDA INFO (OUT)     call_conda_build(action, config)
2022-10-26T01:30:51.7002607Z 01:30:51 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.7/site-packages/boa/cli/mambabuild.py", line 218, in call_conda_build
2022-10-26T01:30:51.7003135Z 01:30:51 BIOCONDA INFO (OUT)     **kwargs,
2022-10-26T01:30:51.7003810Z 01:30:51 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.7/site-packages/conda_build/api.py", line 195, in build
2022-10-26T01:30:51.7013732Z 01:30:51 BIOCONDA INFO (OUT)     variants=variants
2022-10-26T01:30:51.7014757Z 01:30:51 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.7/site-packages/conda_build/build.py", line 3093, in build_tree
2022-10-26T01:30:51.7027277Z 01:30:51 BIOCONDA INFO (OUT)     notest=notest,
2022-10-26T01:30:51.7030310Z 01:30:51 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.7/site-packages/conda_build/build.py", line 2138, in build
2022-10-26T01:30:51.7034962Z 01:30:51 BIOCONDA INFO (OUT)     try_download(m, no_download_source=False, raise_error=True)
2022-10-26T01:30:51.7036018Z 01:30:51 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.7/site-packages/conda_build/render.py", line 662, in try_download
2022-10-26T01:30:51.7043239Z 01:30:51 BIOCONDA INFO (OUT)     raise RuntimeError("Failed to download or patch source. Please see build log for info.")
2022-10-26T01:30:51.7045429Z 01:30:51 BIOCONDA INFO (OUT) RuntimeError: Failed to download or patch source. Please see build log for info.
'''

@rpetit3  any idea?

**Comment by rpetit3** [comment]
Would you be interested in me pushing these patches to the main repo? One was adding an option for `--outdir` and the other is including the index files.

Otherwise I can keep them here and just update the patch

**Comment by crashfrog** [comment]
Sure, I'm happy to accept a patch or PR to the shigatyper repo. Thanks!

**Comment by rpetit3** [comment]
Want a submission now and rerelease or save it for v2.0.3?

**Comment by rpetit3** [comment]
These patches stemmed from me improving docker container that's generated: https://github.com/bioconda/bioconda-recipes/pull/35161

**Comment by crashfrog** [comment]
I’d like to keep it on 2.0.2 if we can, just to avoid a skipped patch version. Does that work?

**Comment by rpetit3** [comment]
No problem, I'll take it from here and get those PRs submitted your way

**Comment by crashfrog** [comment]
Awesome, thanks so much

**Comment by rpetit3** [comment]
@BiocondaBot please fetch artifacts

**Comment by rpetit3** [comment]
### Conda
```
shigatyper --version
ShigaTyper 2.0.2

mkdir test_conda

shigatyper --SE ERR6005894SE.fastq.gz --name test_srr --outdir test_conda
... TRUNCATTED ...
sample  prediction      ipaB    notes
test_srr        Shigella dysenteriae Provisional serotype 96-265        +       this strain is ipaB+, suggesting that it retains the virulent invasion plasmid.

tree test_conda/
test_conda/
├── test_srr-hits.tsv
└── test_srr.tsv

cat test_conda/test_srr.tsv
sample  prediction      ipaB    notes
test_srr        Shigella dysenteriae Provisional serotype 96-265        +       this strain is ipaB+, suggesting that it retains the virulent invasion plasmid.
```

### Docker
```
docker run --entrypoint /bin/bash --rm -u $(id -u):$(id -g) -v ${PWD}:/data quay.io/biocontainers/shigatyper:2.0.2--pyhdfd78af_0 -c "sh
igatyper --version" 2> /dev/null
ShigaTyper 2.0.2

docker run --entrypoint /bin/bash --rm -u $(id -u):$(id -g) -v ${PWD}:/data quay.io/biocontainers/shigatyper:2.0.2--pyhdfd78af_0 -c "sh
igatyper --SE /data/ERR6005894SE.fastq.gz --outdir /data/test_docker" 2> /dev/null
        Hit     Number of reads Length Covered  reference length        % covered       Number of variants      % accuracy
0       ipaH_c  32      740     780     94.9    0.0     100.0
1       ipaB    22      1015    1743    58.2    0.0     100.0
2       SdProv_wzx      16      1017    1320    77.0    0.0     100.0
3       SdProv_wzy      53      1104    1212    91.1    0.0     100.0
sample  prediction      ipaB    notes
ERR6005894SE    Shigella dysenteriae Provisional serotype 96-265        +       this strain is ipaB+, suggesting that it retains the virulent invasion plasmid

tree test_docker/
test_docker/
├── ERR6005894SE-hits.tsv
└── ERR6005894SE.tsv

cat test_docker/ERR6005894SE.tsv
sample  prediction      ipaB    notes
ERR6005894SE    Shigella dysenteriae Provisional serotype 96-265        +       this strain is ipaB+, suggesting that it retains the virulent invasion plasmid.
```

Everything looks good

**Review by rpetit3 — APPROVED** [review]

**Comment by rpetit3** [comment]
@BiocondaBot please merge

**Pull request merged**
