### PR TITLE
Add SCALOP package

### PR DESCRIPTION
**Pull request by prihoda**
Adding SCALOP for canonical antibody loop structure annotation, which is now only available on GitHub: https://github.com/oxpig/SCALOP

Similar to ANARCI package which is already packaged in Bioconda the same way: https://anaconda.org/bioconda/anarci

### CODE REVIEW

**Comment by prihoda** [comment]
@BiocondaBot please add label

**Comment by dpryan79** [comment]
@prihoda Can you ask the package author if they can tag a release on github?

**Comment by dpryan79** [comment]
Fair enough, I'll go ahead and approve this once the CI testing has finished. We can merge it then, since it may never get official releases.

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Pull request merged**
