### PR TITLE
sentieon: update to 201711.04

### PR DESCRIPTION
**Pull request by Lenbok**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by Lenbok** [comment]
@bioconda/core Relatively new here - I simply did minimal changes to get the new version so things shouldn't be worse than they were previously. I don't understand the linting failures though (source already has a md5 section, and compiler seems irrelevant).

**Comment by chapmanb** [comment]
Len -- thanks so much for working on this. It looks like there is some trickiness with the current bioconda change to conda build 3. I couldn't figure out how to use Git to push to your PR branch so created a new PR here I hope will work: #9686 If that passes and merges we could close this one and enjoy the brand new fancy sentieon package.

**Comment by Lenbok** [comment]
Awesome, thanks Brad! (We've got a project that's crashing with the build currently in bioconda so this will help us move forward rather than having to roll back to an earlier version)

**Comment by chapmanb** [comment]
Sweet, I'm glad it passed. Björn, thanks for the super fast merge. Hopefully the new version will be everything you dreamed of.

**Pull request closed without merging**
