### PR TITLE
InterProScan: add missing path in config

### PR DESCRIPTION
**Pull request by abretaud**
I have this error when trying to run InterProScan with all applications:

```
Deactivated analyses:
                      PANTHER (15.0) : Analysis Panther is deactivated, because the following parameters are not set in the interproscan.properties file: binary.hmmer3.hmmsearch.path
```

For some reason (java beans stuff), the error message is wrong, the missing config value is `binary.hmmer3.path`, which is supposed to be the directory where hmmer is installed.
With this patch, we set this value to the dir where hmmer is installed by conda, and the error message goes away.

ping @Juke34 in case you have an opinion about this change :)
@bgruening this should fix the usegalaxy.eu error :crossed_fingers: 

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by bgruening** [comment]
Interesting! Try it on EU please, I have patched the current config file.

**Comment by abretaud** [comment]
It works :)

**Comment by Juke34** [comment]
I did not think having seen this error with version 5.52_86.0
Originally I made a patch (https://github.com/bioconda/bioconda-recipes/blob/master/recipes/interproscan/initial_setup.py.patch) to avoid to set any path for `binary.hmmer3.path` and `binary.hmmer33.path`. Interproscan was supposed to call directly `hmmsearch` without appending any path.
The modification here sounds good. I think we can remove the patch then.

**Comment by abretaud** [comment]
> I did not think having seen this error with version 5.52_86.0

Yep, I don't remember precisely having it before, but I've made so many tests with various exotic error messages that I don't trust my memory on this anymore :)

> Originally I made a patch (https://github.com/bioconda/bioconda-recipes/blob/master/recipes/interproscan/initial_setup.py.patch) to avoid to set any path for `binary.hmmer3.path` and `binary.hmmer33.path`. Interproscan was supposed to call directly `hmmsearch` without appending any path. The modification here sounds good. I think we can remove the patch then.

Ok your patch fixed it for the initial_setup step while mine should work for initial_setup + normal usage.. Still the java code is a bit confusing, it complains about this value being empty, but I'm not even sure it is actually used... anyway, I'll remove your patch and see how it goes

Thanks for reviewing!

**Comment by abretaud** [comment]
@BiocondaBot please add label

**Comment by dpryan79** [comment]
@abretaud Yes, but it's not obvious. If you click over to Azure (via "Details" and then "View more details") you'll get to a page with links to the artifacts (e.g., https://dev.azure.com/bioconda/bioconda-recipes/_build/results?buildId=10959&view=results was for the build for the previous commit). You can download the zip file over everything then.

**Comment by abretaud** [comment]
Ok, I've tested the latest artifact, and I had to make one more change to interproscan.properties, to make sure we always use conda's pftools instead of the bundled one.
I think https://github.com/ebi-pf-team/interproscan/issues/215 doesn't occur on every linux distro, but it happened on the one I used (centos7).
I think we did not have to do it for the usegalaxy.eu install, maybe we were lucky to not encounter this error on the linux flavor that's running there

**Comment by abretaud** [comment]
@BiocondaBot please add label

**Review by bgruening — APPROVED** [review]

**Pull request merged**
