### PR TITLE
Updated entrez-direct to 15.6

### PR DESCRIPTION
**Pull request by ialbert**
The officially supported entrez direct install attempts to connect to the internet to download platform-specific precompiled binaries. 

The choice of connecting to internet during install seems to be incompatible with bioconda.

Discussions with the developer indicate that they prefer the current installation. 

To solve the conundrum we have created a prepackaged version of entrez-direct that is bioconda ready. 

Our tar.gz file already contains the binaries for all platforms and the install chooses the correct binary at install times. The download URL for the source has been changed to

https://github.com/biostars/conda-ready-entrez-direct

A new install script has been written.

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Review by rpetit3 — APPROVED** [review]

**Comment by dpryan79** [comment]
@ialbert Can you clean up the resulting `bin` directory? For example, there are install scripts and an `eutils` directory with source code that presumably shouldn't be there.

**Comment by rpetit3** [comment]
@ialbert I'm totally cool with it, but do you think you could get an NCBI dev to sign off on the change?

**Comment by ialbert** [comment]
@rpetit3 the dev is onboard, has contributed with advice and code to the repackaging effort

**Comment by ialbert** [comment]
thanks everyone for the assistance in getting this resolved @dpryan79 @rpetit3

**Comment by rpetit3** [comment]
No problem!

**Pull request merged**
