### PR TITLE
Update CNVkit to version 0.8.1

### PR DESCRIPTION
**Pull request by etal**
* [x] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

Specifies the latest version of CNVkit, and also a minimum version for the 'futures' package dependency.

### CODE REVIEW

**Comment by kyleabeauchamp** [comment]
LGTM.  Totally missed the release :)

**Comment by etal** [comment]
Just a heads-up, the OS X builds have been failing on Travis lately:
https://travis-ci.org/etal/cnvkit/builds/166864903

I assumed this was due to the R 3.3 transition which appeared to be a very deep rabbit hole to go down alone.

**Comment by etal** [comment]
It looks like only the build for Python 3 on OS X failed, apparently due to a timeout during one step of the installation. Any suggestions as to how I can fix this?

**Comment by kyleabeauchamp** [comment]
I've restarted the build.

**Comment by bgruening** [comment]
Thanks!

**Pull request merged**
