### PR TITLE
Fixing bioconductor datapackages: subdag 1 of 10

### PR DESCRIPTION
**Pull request by johanneskoester**
:information_source:
Bioconda has finished the [GCC7 migration](https://github.com/bioconda/bioconda-recipes/issues/13578). If you are dealing with C/C++ or Python package it can be that you need to rebuild other dependent packages. [Bioconda utils - update-pinning](https://bioconda.github.io/updating.html#updating-recipes-for-a-pinning-change) will assist you with that. If you have any questions please use [issue 13578](https://github.com/bioconda/bioconda-recipes/issues/13578).

----------------

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [ ] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by bgruening** [comment]
@johanneskoester can you explain why we need to rebuild those recipes? It will create a lot of containers and will waste a lot of space down the road ...

Can it be that the openssl rebuild will fix the data packages?

**Comment by johanneskoester** [comment]
Wget is coming from the defaults channel, so I don't think this will be fixed with the openssl migration. My rationale for migrating to curl was that it is in conda-forge, so it is easier to fix if something breaks in the future.  I thought that it is not a good idea to have about 1000 data packages dependent on a wget at runtime that we cannot quickly fix. And many R packages depend on these data packages.

**Comment by johanneskoester** [comment]
But indeed, the containers are not affected by the current issue, as they already contain the downloaded datapackage, right?

**Comment by johanneskoester** [comment]
Maybe we could find a way to temporarily disable the container upload for these?

**Comment by johanneskoester** [comment]
A container-upload blacklist?

**Comment by bgruening** [comment]
Mh, so the issue is wget/curl for the data packages. I'm all in for using curl for the next rebuild but now? Is there no way to get wget from conda-forge? Have you tried rebuilding wget on conda-forge?

**Comment by johanneskoester** [comment]
No, haven't tried that. That would indeed be another reasonable solution.

**Comment by johanneskoester** [comment]
Good idea :-)!

**Comment by bgruening** [comment]
I just figured that there is no wget feedstock in conda-forge ... and I found that wget from anaconda is build against `openssl >=1.1.1,<1.1.2.0a0`. So this might be the underlying problem ... Maybe a conda-forge wget for old and then for new openssl will fix it?

**Comment by bgruening** [comment]
Which version do you get when a data packages crashes?

**Comment by johanneskoester** [comment]
Working on that now.

**Comment by johanneskoester** [comment]
The latest wget causes the problem, earlier versions worked fine. openssl should be pinned, so I am not sure if that is the issue though.

**Comment by dpryan79** [comment]
Can we change the pinnings post hoc after moving to the CDN?

**Comment by bgruening** [comment]
I think we are working on fixing the defaults wget package or/and creating a conda-forge wget package.

**Comment by johanneskoester** [comment]
Exactly. Thanks for pointing me to this much faster solution (hopefully at least ;-)).

**Comment by johanneskoester** [comment]
At least this forced me to work on the subdag-commit solution, which might be handy in other cases.

**Pull request closed without merging**
