### PR TITLE
Add nextstrain meta-package

### PR DESCRIPTION
**Pull request by tsibley**
Relies on the `auspice` package added by #27188.

### CODE REVIEW

**Comment by tsibley** [comment]
@BiocondaBot please rebuild

**Comment by tsibley** [comment]
@BiocondaBot get artifacts please

**Comment by tsibley** [comment]
@BiocondaBot fetch artifacts please

**Comment by tsibley** [comment]
@BiocondaBot fetch artifacts

**Comment by tsibley** [comment]
@BiocondaBot please add label

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Pull request merged**
