### PR TITLE
Update version of kallisto to 0.44.0 meta.yaml

### PR DESCRIPTION
**Pull request by huzuner**
Executing `arcasHLA genotype` does not result in intermediate quantification files to be produced by kallisto which is a dependency package of arcasHLA. The log of arcasHLA gives the following message:
```
Deprecated: `kallisto pseudo` is deprecated. See `kallisto bus`.
```
The latest version of Kallisto deprecates the usage of `kallisto pseudo`. To fix this problem the version of kallisto should be fixed to `v0.44.0` in this recipe.

-------

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by dlaehnemann** [comment]
I guess this `kallisto pseudo` call originates in the `arcasHLA genotype` call, right? So you are not in control over updating to `kallisto bus` over there? It is probably worth checking if such an update to `arcasHLA` is already open in the `arcasHLA` repository or if there is maybe even a pull request present or merged for a newer version? If not, I would suggest also filing an issue in the `arcasHLA` repository.

Otherwise, I think the latest version of kallisto that you can use for `kallisto pseudo` is `0.48.0`. See the last heading in the [release notes for version `0.50.0`](https://github.com/pachterlab/kallisto/releases/tag/v0.50.0), which describes the deprecation under **End of support for existing bulk RNAseq features**.

So I would suggest to:

* [ ] follow up with `arcasHLA`, to make sure they are aware of this coming problem
* [ ] fix kallisto to `<= 0.48.0` here in the bioconda recipe for the current version of arcasHLA

**Comment by huzuner** [comment]
I didn't see any issues or comments, presumably because of the very recent release of the latest version of `kallisto ==0.50.0` 3 weeks ago and there kallisto pseudo is completely removed. I created an issue in arcasHLA: [https://github.com/RabadanLab/arcasHLA/issues/109]. In the previous release (v0.48.0), it is deprecated and I suppose we should be setting the version to the release before that one, which is `v0.46.2`.

**Comment by huzuner** [comment]
And in the requirements for [arcasHLA](https://github.com/RabadanLab/arcasHLA), kallisto `v0.44.0` is said to be the working version. Would setting the dependency in the conda recipe to `<= 0.46.2` ever lead to installing a version below `v0.44.0`?

**Comment by dlaehnemann** [comment]
Generally, I would always try to be as flexible as possible with defining dependencies. This has the advantage that different tools can more easily be installed into the same environment without dependency conflicts. But if arcasHLA explicitly asks for `v0.44.0` it probably is safest to pin the dependency to that version with `==0.44.0`. Otherwise, a lower version could be pulled in, if another tool that someone might want to install into the same environment required a lower version. But there's no perfect solution, I guess...

Also, looking at the requirements of arcasHLA that you linked, it might makes sense to pin `biopython <=1.77`, see:
https://github.com/RabadanLab/arcasHLA/blob/04aab717b66fdf2dd6d96dd1f5ced36fc29e91a1/README.md?plain=1#L18

**Comment by huzuner** [comment]
I also think that having `v0.44.0` is the most optimal solution.
I also updated the version of biopython.

**Review by dlaehnemann — APPROVED** [review]
Looks good to me. Thanks for thoroughly following up on such issues!

**Pull request merged**
