### PR TITLE
Update PopPUNK to v1.1.4

### PR DESCRIPTION
**Pull request by johnlees**
:information_source:
Bioconda has finished the [GCC7 migration](https://github.com/bioconda/bioconda-recipes/issues/13578). If you are dealing with C/C++ or Python package it can be that you need to rebuild other dependent packages. [Bioconda utils - update-pinning](https://bioconda.github.io/updating.html#updating-recipes-for-a-pinning-change) will assist you with that. If you have any questions please use [issue 13578](https://github.com/bioconda/bioconda-recipes/issues/13578).

----------------

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR updates an existing recipe.

### CODE REVIEW

**Comment by johnlees** [comment]
@bioconda/core 
Could you advise as to why this is failing? It looks like a problem with a py36 -> py37 update, which I guess is related to #13578? But I haven't been able to follow the details there, and I have not been able to successfully install bioconda-utils

**Comment by dpryan79** [comment]
Am I correct in understanding that this should be python 2 only?

**Comment by johnlees** [comment]
It should be python3 only

**Comment by johnlees** [comment]
The tests all work, but then:
```
Solving environment: ...working... failed

failed to get install actions, retrying.  exception was: Unsatisfiable dependencies for platform linux-64: {'poppunk==1.1.4=py37_0'}

WARNING:conda_build.build:failed to get install actions, retrying.  exception was: Unsatisfiable dependencies for platform linux-64: {'poppunk==1.1.4=py37_0'}

Tests failed for poppunk-1.1.4-py37_0.tar.bz2 - moving package to /opt/conda/conda-bld/broken
```

**Comment by dpryan79** [comment]
Please increase the build number in the following dependencies (or run `bioconda-utils update-pinning recipes/ config.yml --packages poppunk`): mash, rapidnj, and sharedmem. Those are the ones that need to be rebuilt for the new compilers.

**Comment by dpryan79** [comment]
BTW, you can make this `noarch: python` and set python3 as a host and run time dependency (`python >=3`).

**Comment by johnlees** [comment]
@dpryan79 Thanks (as usual) for the quick and helpful responses!
It seemed like it would be most useful to both make this package `noarch` as well as updating the other builds, so I did both.
Ok to merge now?

**Comment by dpryan79** [comment]
@johnlees Looks great, merge it!

**Pull request merged**
