### PR TITLE
perl-io-prompt a new recipe

### PR DESCRIPTION
**Pull request by mictadlo**
* [x] I have read the guidelines above.
* [x] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by mictadlo** [comment]
@jerowe @bgruening @daler @druvus  any idea why Linux failed, but MacOS was successful?

**Comment by bgruening** [comment]
```
/opt/conda/conda-bld/work/IO-Prompt-0.997004/conda_build.sh: ./Build: /opt/conda/conda-bld/_b_env_placehold_placehold_placehold_placehold_placehold: bad interpreter: No such file or directory
```
There is again a `/usr/bin/perl` somewhere :(

**Comment by mictadlo** [comment]
it seems only the `example` folder contains `/usr/bin/perl`. Do I have to modify all examples?

**Comment by bgruening** [comment]
If you want to include them in the package, yes :(

**Comment by mictadlo** [comment]
I patched 11 files and still, Linux failed, but MacOS has no problems.

**Comment by mictadlo** [comment]
@sjackman Any idea where `/usr/bin/perl/` could cause this problem `bad interpreter: No such file or directory` or where linuxbrew has its recipe for IO-Prompt?

**Comment by bgruening** [comment]
@mictadlo in conda we do not assume anything from the run-time system. So perl is not available in `/usr/bin/perl` use `/usr/bin/env perl` instead.

**Comment by mictadlo** [comment]
@bgruening, I patched 11 files to contain `/usr/bin/env perl`, but I still get bad interpreter: No such file or directory. Any idea which one I could have forgotten?

**Comment by bgruening** [comment]
No idea which one, but there is still at least one ;). You can grep for `/usr/bin/perl`

**Comment by sjackman** [comment]
Linuxbrew doesn't package Perl packages. Sorry. I use `cpanm IO::Prompt`

**Comment by mictadlo** [comment]
@bgruening I think I found it but is Travis CI working?

**Comment by bgruening** [comment]
Yes it is, it just takes some time.

**Comment by mictadlo** [comment]
@bgruening Why do I get to  [`2 recipes, 1 failed`](https://travis-ci.org/bioconda/bioconda-recipes/jobs/199781586#L678)?

**Comment by bgruening** [comment]
One was probably merged into master, at the time you started your run. Nothing to worry about.

**Comment by mictadlo** [comment]
@bgruening I did grep shown below and all files I patched which contained `/usr/bin/perl`:
```
$ cd IO-Prompt-0.997004
SEF-EEB-123137:IO-Prompt-0.997004 lorencm$ ls
Build.PL	Changes		MANIFEST	META.json	META.yml	Makefile.PL	README		examples	lib		t
SEF-EEB-123137:IO-Prompt-0.997004 lorencm$ grep "/usr/bin/perl" *
grep: examples: Is a directory
grep: lib: Is a directory
grep: t: Is a directory
SEF-EEB-123137:IO-Prompt-0.997004 lorencm$ cd t
SEF-EEB-123137:t lorencm$ grep "/usr/bin/perl" *
SEF-EEB-123137:t lorencm$ cd ../lib/
.DS_Store  IO/        
SEF-EEB-123137:t lorencm$ cd ../lib/IO/
SEF-EEB-123137:IO lorencm$ grep "/usr/bin/perl" *
SEF-EEB-123137:IO lorencm$ cd ../../examples/
SEF-EEB-123137:examples lorencm$ grep "/usr/bin/perl" *
clear.pl:#! /usr/bin/perl -w
cmdline.pl:#! /usr/bin/perl -w
default.pl:#! /usr/bin/perl -w
hand.pl:#! /usr/bin/perl -w
interactive.pl:#! /usr/bin/perl -w
lingua.pl:#!/usr/bin/perl
nonl.pl:#! /usr/bin/perl -w
passwd.pl:#! /usr/bin/perl -w
to.pl:#! /usr/bin/perl -w
tty.pl:#! /usr/bin/perl -w
while_until.pl:#! /usr/bin/perl -w
yesno.pl:#! /usr/bin/perl -w
```
I still can't find the problem.

**Comment by bgruening** [comment]
Just a stupid guess, can it be that `./Build` that is generated has this shebang?

**Comment by mictadlo** [comment]
@bgruening You were right and I added [here](https://travis-ci.org/bioconda/bioconda-recipes/jobs/199831538#L611) 
`sed -i.bak 's| /usr/bin/perl|/usr/bin/env perl|'`, but it did not helped.

**Comment by mictadlo** [comment]
merging?

**Comment by bgruening** [comment]
Cool beans! Thanks!

**Comment by mictadlo** [comment]
Thank you very much for you all help.

**Pull request merged**
