### PR TITLE
Update nextstrain-cli: add zika build test

### PR DESCRIPTION
**Pull request by victorlin**
This test was removed in #33520 due to memory issues with the test server preventing tests from running. It can be added back if #33415 is resolved.

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by corneliusroemer** [comment]
What's the status of this @victorlin :)

**Comment by victorlin** [comment]
@corneliusroemer I don't think this should be opened for review/merge until checks are passing, but I'm not sure what's going on with checks in this repo. It didn't seem to run on your merge commit, looks like it's running on mine now. Waiting to see if it succeeds.

**Comment by victorlin** [comment]
@BiocondaBot please add label

**Comment by pvanheus** [comment]
This sounds great. How long does the test take though?

**Comment by dpryan79** [comment]
@BiocondaBot please fetch artifacts

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@BiocondaBot please merge

**Comment by victorlin** [comment]
@pvanheus

Looking at [the `test_linux` run logs](https://dev.azure.com/bioconda/bioconda-recipes/_build/results?buildId=19392&view=logs&j=e14e69ff-a0ae-55c4-b71d-229b239cfb2f&t=7df82132-b284-504b-53d6-7d3e63519572&l=1799), it took an additional 43s:

```
21:45:52 BIOCONDA INFO (OUT) + nextstrain build --native --cpus 1 zika-tutorial
...
21:46:32 BIOCONDA INFO (OUT) 10 of 10 steps (100%) done
21:46:32 BIOCONDA INFO (OUT) Complete log: .snakemake/log/2022-07-29T214553.182346.snakemake.log
21:46:33 BIOCONDA INFO (OUT) 
21:46:33 BIOCONDA INFO (OUT) Resource usage statistics from testing nextstrain-cli:
21:46:33 BIOCONDA INFO (OUT)    Process count: 7
21:46:33 BIOCONDA INFO (OUT)    CPU time: Sys=0:00:00.6, User=0:00:30.3
21:46:33 BIOCONDA INFO (OUT)    Memory: 214.4M
21:46:33 BIOCONDA INFO (OUT)    Disk usage: 2.4K
21:46:33 BIOCONDA INFO (OUT)    Time elapsed: 0:00:43.4
```

**Pull request merged**
