### PR TITLE
updated star-fusion version to 1.10.1

### PR DESCRIPTION
**Pull request by praveenraj2018**
Updated the version of STAR-Fusion to 1.10.1 (Latest)

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by praveenraj2018** [comment]
Can anyone see why this check returns build timeout?

**Comment by praveenraj2018** [comment]
@BiocondaBot @bgruening could you please see why the build is getting timeout?

**Comment by bgruening** [comment]
Is the lower pin to openssl and the other pins for samtools really needed?

**Comment by praveenraj2018** [comment]
> Is the lower pin to openssl and the other pins for samtools really needed?

Samtools is required. I just made it as samtools <1.14 and openssl <1.1.1.

**Comment by praveenraj2018** [comment]
Ah! It looks fine now @bgruening

**Comment by raivivek** [comment]
@praveenraj2018 Does it mean the package doesn't build with samtools = 1.14 (the latest version)? If the version of samtools is not relevant, you can remove the version string. Similarly for openssl.

**Comment by bgruening** [comment]
@praveenraj2018 if the samtools pin is not necessary, please remove the pinning as @raivivek said.

**Comment by mjsteinbaugh** [comment]
This recipe update is out of date, please resubmit if changes are necessary

**Pull request closed without merging**
