### PR TITLE
quast 4.6.3

### PR DESCRIPTION
**Pull request by alexeigurevich**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by mbargull** [comment]
Can we include the request from https://github.com/bioconda/bioconda-recipes/issues/7349 in this one?
I think what we need is
* add `blast` dependency (something I missed in the previous PR, sorry)
* add script `quast-download-blastdb`:
```python
#!/usr/bin/env python

from quast_libs.search_references_meta import download_blastdb
download_blastdb()
```
* add script `quast-download-manta` (replace `_SOME_SUBMODULE_` with an appropriate one):
```python
#!/usr/bin/env python

from quast_libs.ra_utils.misc import download_manta
from quast_libs._SOME_SUBMODULE_ import logger
download_manta(logger)
```
* make `build.sh` copy those two scripts, making sure they are executable:
```bash
cp $RECIPE_DIR/quast-download-* $PREFIX/bin
chmod +x $PREFIX/bin/quast-download-*
```
* add a `post-link.sh` (feel free to change the text as you see fit):
```bash
#!/bin/bash

echo 'The quast package does not bundle Manta as well as the BLAST database from SILVA.'
echo 'To be able to use those, please run'
echo '    quast-download-manta'
echo '    quast-download-blastdb'
exit 0
```
* What about Gage? `compile_gage()` is only run for `install_full`. Do we need to do something about this, or does QUAST call that function on the fly if needed?

(Note that I wrote the above quickly without testing and all.)

**Comment by alexeigurevich** [comment]
> Can we include the request from #7349 in this one?

Ok, makes sense, will add.

> add a post-link.sh (feel free to change the text as you see fit):
> ...
> echo '    quast-download-manta'

Should it be `./quast-download-manta` ? Should we also add `.py` extension for these scripts?

> What about Gage? compile_gage() is only run for install_full. Do we need to do something about this, or does QUAST call that function on the fly if needed?

Quast call this function on the fly, but (1) java compiler is needed (we have `openjdk` in `meta.yaml`, so this is fine) and (2) Quast should have write permissions under `quast_libs` (to save `.class` files compiled from `.java`). Does it always have such permissions in runtime?

**Comment by mbargull** [comment]
> Should it be ./quast-download-manta ?

No, that way the user would try to run a `quast-download-manta` from their current working directory. Since we copy `quast-download-manta` to `$PREFIX/bin`, it will be on `$PATH` when the environment is activated.
> Should we also add .py extension for these scripts?

If you are more comfortable with naming them `quast-download-*.py`, you can do that. It isn't needed though, as the shebang `#!/usr/bin/env python` is what instructs the system to run them with `python`.

> Does it always have such permissions in runtime?

Good question! Maybe not always, e.g., in a multi-user environment. So, I think it would be best to just patch `setup.py` to also run `compile_gage()` when doing a "normal" `install`. Then we can also remove its special handling from `pre-unlink.sh` as `conda` will do its job, i.e., in https://github.com/bioconda/bioconda-recipes/blob/3303e73516844f3ff703561109bf41f94e4c85ee/recipes/quast/pre-unlink.sh#L17-L20
```diff
-from quast_libs.gage import gage_dirpath
-for dirpath in (manta_dirpath, gage_dirpath):
-    if isdir(dirpath):
-        rmtree(dirpath, ignore_errors=True)
+if isdir(manta_dirpath):
+    rmtree(manta_dirpath, ignore_errors=True)
```

**Comment by alexeigurevich** [comment]
All done, please check!

**Comment by mbargull** [comment]
Thanks for the "fix fix" ;). Tested the scripts and now everything works as expected! (Well apart from that I didn't see the message from `post-link.sh`, but I believe there was something else amiss, unrelated to the package and script themselves.)

**Comment by mbargull** [comment]
Thanks @alexeigurevich! Once it's build and available on the channel, I'll try it out again locally and see whether `conda` shows the `post-link.sh` message -- if not I'll debug why that's the case.

**Comment by alexeigurevich** [comment]
Great, thanks!

**Comment by mbargull** [comment]
I think #7567 should fix the `post-link.sh`/`pre-unlink.sh` scripts' output.

**Pull request merged**
