### PR TITLE
add recipe for pbptyper

### PR DESCRIPTION
**Pull request by rpetit3**
This PR adds pbptyper, a tool for in silico PBP typing of S. pneumoniae assemblies

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by rpetit3** [comment]
@biocondabot please fetch artifacts

**Comment by rpetit3** [comment]
# Testing 

### Conda 
```
conda install LinuxArtifacts/packages/noarch/pbptyper-1.0.0-hdfd78af_0.tar.bz2

which pbptyper
/home/robert_petit/miniconda3/envs/test-pbptyper/bin/pbptyper

pbptyper --version
pbptyper, version 1.0.0

pbptyper --help

 Usage: pbptyper [OPTIONS]

 In silico Penicillin Binding Protein (PBP) typer for Streptococcus pneumoniae assemblies

╭─ Options ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│    --version                  Show the version and exit.                                                                                                      │
│ *  --assembly        TEXT     Input assembly in FASTA format (gzip is OK) [required]                                                                          │
│    --db              TEXT     Path to the input database [default: /home/robert_petit/miniconda3/envs/test-pbptyper/share/pbptyper-1.0.0]                        │
│    --prefix          TEXT     Prefix to use for output files [default: basename of input]                                                                     │
│    --outdir          TEXT     Directory to save output files [default: ./]                                                                                    │
│    --min_pident      INTEGER  Minimum percent identity to count a hit [default: 95]                                                                           │
│    --min_coverage    INTEGER  Minimum percent coverage to count a hit [default: 95]                                                                           │
│    --help                     Show this message and exit.                                                                                                     │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯


# Testing 
pbptyper --assembly test/SRR2912551.fna.gz
Running TBLASTN for 1A...
TBLASTN results written to ./SRR2912551.fna-1A.tblastn.tsv

Running TBLASTN for 2B...
TBLASTN results written to ./SRR2912551.fna-2B.tblastn.tsv

Running TBLASTN for 2X...
TBLASTN results written to ./SRR2912551.fna-2X.tblastn.tsv

                                            Predicted PBP Type
┏━━━━━━━━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━━━┓
┃ sample         ┃ pbptype ┃ 1A_coverage ┃ 1A_pident ┃ 2B_coverage ┃ 2B_pident ┃ 2X_coverage ┃ 2X_pident ┃
┡━━━━━━━━━━━━━━━━╇━━━━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━━━━┩
│ SRR2912551.fna │ 23:0:2  │ 100         │ 100.000   │ 100         │ 100.000   │ 100         │ 100.000   │
└────────────────┴─────────┴─────────────┴───────────┴─────────────┴───────────┴─────────────┴───────────┘
Predicted pbp type result written to ./SRR2912551.fna.tsv

ls -lh *.tsv
-rw-r--r-- 1 robert_petit robert_petit 160K Aug  3 18:47 SRR2912551.fna-1A.tblastn.tsv
-rw-r--r-- 1 robert_petit robert_petit 210K Aug  3 18:47 SRR2912551.fna-2B.tblastn.tsv
-rw-r--r-- 1 robert_petit robert_petit 420K Aug  3 18:47 SRR2912551.fna-2X.tblastn.tsv
-rw-r--r-- 1 robert_petit robert_petit  139 Aug  3 18:47 SRR2912551.fna.tsv
```

### Docker 
```
gzip -dc LinuxArtifacts/images/pbptyper:1.0.0--hdfd78af_0.tar.gz | docker load
docker run --rm -u $(id -u):$(id -g) -v ${PWD}:/data quay.io/biocontainers/pbptyper:1.0.0--hdfd78af_0 pbptyper --assembly /data/test/SRR8654742.fna --outdir /data/
Running TBLASTN for 1A...
TBLASTN results written to /data/SRR8654742-1A.tblastn.tsv

Running TBLASTN for 2B...
TBLASTN results written to /data/SRR8654742-2B.tblastn.tsv

Running TBLASTN for 2X...
TBLASTN results written to /data/SRR8654742-2X.tblastn.tsv

                               Predicted PBP Type
┏━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━┓
┃ sample  ┃ pbptype ┃ 1A_cov… ┃ 1A_pid… ┃ 2B_cov… ┃ 2B_pid… ┃ 2X_cov… ┃ 2X_pi… ┃
┡━━━━━━━━━╇━━━━━━━━━╇━━━━━━━━━╇━━━━━━━━━╇━━━━━━━━━╇━━━━━━━━━╇━━━━━━━━━╇━━━━━━━━┩
│ SRR865… │ NEW:53… │ 100     │ 99.275  │ 100     │ 100.000 │ 100     │ 100.0… │
└─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴────────┘
Predicted pbp type result written to /data/SRR8654742.tsv


ls -lh *.tsv
-rw-r--r-- 1 robert_petit robert_petit 161K Aug  3 18:49 SRR8654742-1A.tblastn.tsv
-rw-r--r-- 1 robert_petit robert_petit 237K Aug  3 18:49 SRR8654742-2B.tblastn.tsv
-rw-r--r-- 1 robert_petit robert_petit 430K Aug  3 18:49 SRR8654742-2X.tblastn.tsv
-rw-r--r-- 1 robert_petit robert_petit  137 Aug  3 18:49 SRR8654742.tsv
```

Everything looks good

**Comment by rpetit3** [comment]
@biocondabot please add label

**Comment by dpryan79** [comment]
@BiocondaBot please merge

**Comment by rpetit3** [comment]
Thank you!

**Pull request merged**
