### PR TITLE
Flexbar 3.3

### PR DESCRIPTION
**Pull request by bwlang**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by bwlang** [comment]
Is it a correct practice to add an explicit version as I've done here? or better to just maintain a single meta.yaml files (like cutadapt)?

**Comment by bgruening** [comment]
Up to the maintainer. Keep in mind that if we rebuild the package, e.g bumping zlib, we will rebuild also all sub-packages.

**Comment by bwlang** [comment]
given the api changes to the API, I see value in keeping the old version alive - so I think this is the right path and is ready to merge.

**Comment by bgruening** [comment]
Feel free to merge with your new powers.

**Comment by bwlang** [comment]
hah - thought that might be poor form to merge one's own PR

**Pull request merged**
