### PR TITLE
Add 

### PR DESCRIPTION
**Pull request by zhaoxiaofei**
Describe your pull request here

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by zhaoxiaofei** [comment]
@bioconda/core
@BiocondaBot please add label
 
We are in the process of publishing a paper about the SafeSim bioinformatics package, and we got really positive feedback from our reviewers. 
One of the reviewers asked us to post our software package on bioconda so that other people have a easier time installing our software package. 
Therefore, we would kindly ask you to accept our pull request.  

Our software package is available at: https://github.com/zhaoxiaofei/safesim (originally from https://github.com/genetronhealth/safesim)

Thank you!

**Comment by dpryan79** [comment]
@bioconda-bot please fetch artifacts

**Comment by dpryan79** [comment]
Is there a reason you statically link to htslib? We can put it in as a dependency. What is bcftools doing being pulled in during the build process?

**Comment by zhaoxiaofei** [comment]
@dpryan79 

> Is there a reason you statically link to htslib? We can put it in as a dependency. What is bcftools doing being pulled in during the build process?

I statically linked to hstlib because we installed a similar tool in system where htslib cannot be made available (sort of like embedded system bundled with the sequencing machines), but I guess it is extremely unlikely to encounter this situation on a system with conda, so putting it as a dependency should be no problem.  

Thank you for pointing this out, actually bcftools is not required for this package.  

A question about bioconda best-practice: should I modify the code and commit again? Or should I leave this to you? (I know it involves very little code change)

**Comment by dpryan79** [comment]
As a general software best-practice it's best to modify the code and (ideally) tag a new release.

**Comment by dpryan79** [comment]
@BiocondaBot please fetch artifacts

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
This seems to work fine now. If you're happy then start a comment with "@BiocondaBot please merge" and this will be uploaded and merged.

**Comment by zhaoxiaofei** [comment]
@BiocondaBot please merge

**Pull request merged**
