### PR TITLE
SIRIUS 4.9.8 patch2: replaced conda lib path with link independent alternative

### PR DESCRIPTION
**Pull request by mfleisch**
Fixes https://github.com/bioconda/bioconda-recipes/pull/33830#issuecomment-1098354493 for v4.9.8 (version currently needed by openMS)
----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by mfleisch** [comment]
related to: https://github.com/bioconda/bioconda-recipes/pull/33830#issuecomment-1098475063

**Comment by mfleisch** [comment]
@bernt-matthias can you confirm that this solution works with OpenMS SIRIUS  Adapter

**Comment by bernt-matthias** [comment]
I can try.

**Comment by bernt-matthias** [comment]
@BiocondaBot please fetch artifacts

**Comment by bernt-matthias** [comment]
Can you modify the PR such that the package for 4.9.8 is created? Problem is that openms pins SIRIUS to this exact version.

https://github.com/bioconda/bioconda-recipes/blob/7a2fe69f1fb7b11078309ae1381158f2b5e743de/recipes/openms-meta/meta.yaml#L147

**Comment by bernt-matthias** [comment]
@BiocondaBot please fetch artifacts

**Comment by bernt-matthias** [comment]
Still trying, but I was also thinking if a test like:

```
$(readlink -f $(which sirius)) --version
```

might help. But unure if nested `$(...)` works

**Comment by mfleisch** [comment]
> Still trying, but I was also thinking if a test like:
> 
> ```
> $(readlink -f $(which sirius)) --version
> ```
> 
> might help. But unure if nested `$(...)` works
Added it and it seems to work.

I also moved the more comprehensive test to the meta.yaml because it checks whether the native libs for the ILP solver can be loaded correctly.

I will then create another PR to apply the same changes for 4.9.15

**Comment by mfleisch** [comment]
@BiocondaBot please add label

**Comment by bernt-matthias** [comment]
Cool. I can test finish my test with openms next week. Could not finish it today.

If we want to keep both versions you have to put one of them in an extra subdirectory. But we can also ask the openms developers if the newer is supported. Is there a changelog?

**Comment by mfleisch** [comment]
Of course let's wait with the merge until you tests are done. I just misread your previous comment with the "readlink test" suggestion.
 
Regarding different versions: Maybe I have not fully understood conda versioning but why can we not just create a new build of artifact v4.9.15 and a new build of artifact v4.9.8, so that both versions will be fixed?
 
Regarding OpenMS, I have already talked with @oliveralka. In principle updating to v4.9.15 should not be a problem for the conda package. However, the v4.9.15 multiOS build of SIRIUS which is shipped with the non-conda versions of OpenMS is buggy but I hope I can fix this in the next Week.
 
 Could we specify a dependency to  SIRIUS in OpenMS conda package that is not tied to a patch version number?
 We do not  include any breaking changes in patch updates, so this should be a valid strategy to stay up-to-date.

**Comment by dpryan79** [comment]
If you need to make new builds of both then make a subdirectory called 4.9.8 and put the updated recipe for that version in there.

**Review by dpryan79 — APPROVED** [review]

**Comment by bernt-matthias** [comment]
@BiocondaBot please fetch artifacts

**Comment by bernt-matthias** [comment]
Hi @mfleisch . Get some mixed results in my tests. If I start a `SiriusAdapter` test then the adapter and sirius itself are stalling (ie `docker top` shows me both tools). The command line executed from the adapter itself is: 

`/usr/local/share/sirius-csifingerid-4.9.8-3/lib/runtime/bin/java -Xms1G -XX:MaxRAMPercentage=85 -XX:+UseG1GC -XX:+UseStringDeduplication -Djava.library.path=/lib:/bin/x86-64_linux:/usr/local/share/sirius-csifingerid-4.9.8-3/lib/native:/usr/local/share/sirius-csifingerid-4.9.8-3/lib/runtime/lib -classpath /usr/local/share/sirius-csifingerid-4.9.8-3/lib/app/*:/lib/gurobi.jar:/lib/cplex.jar de.unijena.bioinf.ms.frontend.SiriusGUIApplication --processors=1 --input /tmp/20220418_184222_c5d73a778fb1_18_2.ms --project /tmp/20220418_184222_c5d73a778fb1_18_1/sirius_out sirius --db=all --ppm-max=10.0 --ppm-max-ms2=10.0 --compound-timeout=100 --tree-timeout=0 --profile=qtof --candidates=5`

The good news is that if I execute this command line separately then it terminates successfully. 

No idea what's going on and how to debug this.

**Comment by bernt-matthias** [comment]
> Regarding different versions: Maybe I have not fully understood conda versioning but why can we not just create a new build of artifact v4.9.15 and a new build of artifact v4.9.8, so that both versions will be fixed?

As @dpryan79 noted, in order to get a package for older version one needs to create a subfolder with the meta.yml for that version.
 
> Regarding OpenMS, I have already talked with @oliveralka. In principle updating to v4.9.15 should not be a problem for the conda package. However, the v4.9.15 multiOS build of SIRIUS which is shipped with the non-conda versions of OpenMS is buggy but I hope I can fix this in the next Week.
> 
> Could we specify a dependency to SIRIUS in OpenMS conda package that is not tied to a patch version number? We do not include any breaking changes in patch updates, so this should be a valid strategy to stay up-to-date.

Yes, we could just use `- sirius-csifingerid =4.9` in the OpenMS requirements (also more complex possibilities of specifying versions are possible https://docs.conda.io/projects/conda-build/en/latest/resources/package-spec.html#build-version-spec). In the end this might be better then providing 4.9.8 and 4.9.15 ... but still I would like to understand the problem first .. but I could also test an "unpinned" openms package (maybe the problem disappears :)

**Comment by bernt-matthias** [comment]
@mfleisch .. I'm still struggling with OpenMS' SiriusAdapter in the container. What happens is that the adapter is calling Sirius and after a few moments Sirius is going into state interruptible sleep (`Sl` according to the output of `ps aux`). So it seems to wait for something. The odd thing is that if I start the Sirius command line that is executed by the Adapter separately the Sirius is finishing without problems. 

Do you have any ideas how I could debug this further (e.g. how to increase the log level of Sirius without the possibility to change the called command line, e.g. an environment variable)?

For reference, this is how the adapter calls sirius: https://github.com/OpenMS/OpenMS/blob/cacde2a4dc6d34ef44ab36e2c0df6691f39a4222/src/openms/source/ANALYSIS/ID/SiriusAdapterAlgorithm.cpp#L571

**Comment by bernt-matthias** [comment]
Hi @mfleisch I might have found the reason for the stalling SIRIUS. I have written it down in [a separate issue for OpenMS](https://github.com/OpenMS/OpenMS/issues/6068#issuecomment-1111464105). Would appreciate your feedback.

**Comment by bernt-matthias** [comment]
Just trying to test with https://github.com/OpenMS/OpenMS/pull/6122 and https://github.com/bioconda/bioconda-recipes/pull/34937 .. 

will need a bit

**Comment by bernt-matthias** [comment]
@mfleisch 

Will try to go with https://github.com/bioconda/bioconda-recipes/pull/34447, i.e. unpin the SIRIUS requirement in the OpenMS recipe (+patch the SiriusAdapter). 

So we can close this here, I guess.

Wondering if this might be an option for the upstream SIRIUS repo: https://github.com/bioconda/bioconda-recipes/pull/34482 ...

**Comment by mfleisch** [comment]
Sound, good. Thanks a lot, for the effort you put in debugging this.

**Pull request closed without merging**
