### PR TITLE
Update hificnv to 0.1.7

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`hificnv`](https://bioconda.github.io/recipes/hificnv/README.html): **0.1.6b** &rarr; **0.1.7**

[install with bioconda](http://bioconda.github.io/recipes/hificnv/README.html) [Conda](https://anaconda.org/bioconda/hificnv/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/hificnv`](https://github.com//bioconda/bioconda-recipes/tree/bump/hificnv/recipes/hificnv) (click to view/edit other files)
Summary | Copy number variant caller and depth visualization utility for PacBio HiFi reads
Home | [https://github.com/PacificBiosciences/HiFiCNV](https://github.com/PacificBiosciences/HiFiCNV)
Releases |
Recipe Maintainer(s) | @holtjma, @ctsa

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by holtjma** [comment]
This looks correct to me, although I'm not sure how this happened when https://github.com/bioconda/bioconda-utils/pull/913 has not been merged in yet.  I would expect it to still be throwing autobump errors like hiphase is?

I'm not sure why the tests are failing though.

@mencian What does that run_export change do?

**Comment by mencian** [comment]
@holtjma The linter now enforces `run_exports`, which pins dependency versions during build time to avoid CLI breakages. If a package follows semantic versioning and does not have known breakages in minor versions, `max_pin="x"` is used, and `max_pin="x.x"` if there is.

**Comment by holtjma** [comment]
I figured out this is an issue with the hificnv release md5sum.  Will correct it on our end and then fix the changes I made.

**Review by holtjma — APPROVED** [review]
Everything looks good now!

**Pull request merged**
