### PR TITLE
New: theta2, bcbio-variation-recall. Fix: java shell scripts

### PR DESCRIPTION
**Pull request by chapmanb**
- Fixes closing bracket spacing typo in java wrappers for
  cramtools, picard, snpeff and varscan
- Adds new recipes for THetA2 and bcbio.variation.recall, migrated
  from homebrew recipes.

### CODE REVIEW

**Comment by kyleabeauchamp** [comment]
I think theta2 has an academic license, not MIT.

**Comment by chapmanb** [comment]
I guess I'm not sure exactly how best to classify this one. It's mostly MIT, except they don't allow you to sell it:

https://github.com/raphael-group/THetA/blob/master/doc/LICENSE.txt

so there are no restrictions on usage for standard scientific use. Happy to adjust this to whatever you think is best.

**Comment by kyleabeauchamp** [comment]
I would call it either noncommercial or academic.  

IMHO the non-commercial clause means their license is no longer open source: https://opensource.org/faq#commercial

**Comment by chapmanb** [comment]
Kyle -- thanks much. I adjusted the description to include the restriction on re-selling. Thanks again for being on top of these.

**Pull request merged**
