### PR TITLE
Update beav to 0.5.1

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`beav`](https://bioconda.github.io/recipes/beav/README.html): **0.4.5** &rarr; **0.5.1**

[install with bioconda](http://bioconda.github.io/recipes/beav/README.html) [Conda](https://anaconda.org/bioconda/beav/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/beav`](https://github.com//bioconda/bioconda-recipes/tree/bump/beav/recipes/beav) (click to view/edit other files)
Summary | beav: Bacterial genome and mobile element annotation pipeline
Home | [https://github.com/weisberglab/beav](https://github.com/weisberglab/beav)
Releases |[https://github.com/weisberglab/beav/tags](https://github.com/weisberglab/beav/tags)
Author | `@weisberglab`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by kbseah** [comment]
The build script `git clone`s [PaperBLAST](https://github.com/morgannprice/PaperBLAST) and a fork of [DBSCAN-SWA](https://github.com/weisberglab/DBSCAN-SWA) from their master branches, probably not ideal for package management. The latter repository also lacks a license.

**Comment by alexweisberg** [comment]
Thanks. These are modified versions of those software tools so that they can run in the command line (rather than a web/cgi system) and bug fixes. In future beav versions I will make releases for those tools in those repositories and use that.

**Comment by kbseah** [comment]
Hello @alexweisberg , thanks for the clarification! Would it be possible to specify the download URLs to these additional, customized dependencies directly in the meta.yaml, preferably as a archive for a specific commit/version? In that way the required code is listed in one place for maintainers, and the versioning is stable and documented for the dependencies too. Some examples of this pattern in the recipes for `pb-dazzler`, `circminer`, `latch`.

**Review by shenwei356 — APPROVED** [review]

**Comment by shenwei356** [comment]
Oops, sorry, I missed the comments here.

**Comment by alexweisberg** [comment]
I am updating the build script for this to make the suggested changes at #42568. Please ignore this version. Thanks!

**Comment by mencian** [comment]
Closing in favor of #42568.

**Pull request closed without merging**
