### PR TITLE
Add nf-core

### PR DESCRIPTION
**Pull request by dfornika**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by dfornika** [comment]
Here's the relevant info from the current build error log:

```
[Sep 27 16:41:23] SERR File "/usr/local/lib/python3.6/site-packages/git/__init__.py", line 85, in <module>
[Sep 27 16:41:23] SERR raise ImportError('Failed to initialize: {0}'.format(exc))
[Sep 27 16:41:23] SERR ImportError: Failed to initialize: Bad git executable.
[Sep 27 16:41:23] SERR The git executable must be specified in one of the following ways:
[Sep 27 16:41:23] SERR - be included in your $PATH
[Sep 27 16:41:23] SERR - be set via $GIT_PYTHON_GIT_EXECUTABLE
[Sep 27 16:41:23] SERR - explicitly set via git.refresh()
[Sep 27 16:41:23] SERR 
[Sep 27 16:41:23] SERR All git commands will error until this is rectified.
```

Is there another dependency that I need to add in order for the build to access git? I would have expected it to be available by default?

**Comment by dfornika** [comment]
...I should really read the docs before asking...

https://bioconda.github.io/cb3.html#the-new-host-section

> The new build section should have things like compilers, git, automake, make, cmake, and other build tools.

**Comment by dfornika** [comment]
@ewels @bgruening @druvus @sven1103

Do any of you have insights on this error message about ASCII, UTF-8 and locales from the 'Click' library?

https://click.palletsprojects.com/en/7.x/python3/

```
[Sep 28 21:07:49] SERR 
[Sep 28 21:07:49] SERR ,--./,-.
[Sep 28 21:07:49] SERR ___     __   __   __   ___     /,-._.--~\
[Sep 28 21:07:49] SERR |\ | |__  __ /  ` /  \ |__) |__         }  {
[Sep 28 21:07:49] SERR | \| |       \__, \__/ |  \ |___     \`-._,-`-,
[Sep 28 21:07:49] SERR `._,._,'
[Sep 28 21:07:49] SERR 
[Sep 28 21:07:49] SERR Traceback (most recent call last):
[Sep 28 21:07:49] SERR File "/usr/local/bin/nf-core", line 159, in <module>
[Sep 28 21:07:49] SERR nf_core_cli()
[Sep 28 21:07:49] SERR File "/usr/local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
[Sep 28 21:07:49] SERR return self.main(*args, **kwargs)
[Sep 28 21:07:49] SERR File "/usr/local/lib/python3.6/site-packages/click/core.py", line 696, in main
[Sep 28 21:07:49] SERR _verify_python3_env()
[Sep 28 21:07:49] SERR File "/usr/local/lib/python3.6/site-packages/click/_unicodefun.py", line 124, in _verify_python3_env
[Sep 28 21:07:49] SERR ' mitigation steps.' + extra
[Sep 28 21:07:49] SERR RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment. Consult https://click.palletsprojects.com/en/7.x/python3/ for mitigation steps.
[Sep 28 21:07:49] SERR 
[Sep 28 21:07:49] SERR Additional information: on this system no suitable UTF-8
[Sep 28 21:07:49] SERR locales were discovered.  This most likely requires resolving
[Sep 28 21:07:49] SERR by reconfiguring the locale system.
```
Would the solution be as simple as setting a locale environment variable in the testing environment?

**Comment by sven1103** [comment]
@dfornika Python 3.x uses UTF-8 by default ([PEP3120](https://www.python.org/dev/peps/pep-3120/)), so my guess is, that it falls back to ASCII, because the system locale is not UTF-8-based. But hard to tell without a look on the host system :)

**Comment by dfornika** [comment]
That's what I'm mulling over right now...
- Is there a way to set the system locale on the testing environment in CircleCI?
- If we just did that, is it ok to just rely on the user having an appropriate environment on their system, or is there something we can do in the conda environment that will guarantee that the Click library will work when a user installs nf-core?

**Comment by ewels** [comment]
Awesome stuff - thanks for this @dfornika!

The click locale problems are sadly all too familiar. Click is a bit stupid (or at least, stubborn) about Python 3 and locales especially. I've had nightmares with this on other bioconda packages that use it, namely MultiQC.

In short, the end result of a whole tonne of testing and frustration and awesome work by the bioconda team is this:
https://github.com/bioconda/bioconda-recipes/blob/72463d2313337255cc89955dc3234c26f3617303/recipes/multiqc/meta.yaml#L137-L140

I _think_ I'm now right in saying that if you use the extended container then everything _should_ work. Hopefully.

Phil

**Comment by ewels** [comment]
tests_pass

**Comment by dfornika** [comment]
@ewels I didn't think to ask before submitting this pull request. Is it ok to call this bioconda package `nf-core`? Would it be better to call it `nf-core-tools` or something similar?

**Comment by ewels** [comment]
Yes, it should be called `nf-core`. That's the name of the command and it's also the name of the distribution on PyPI. We don't intend to have any other Python nf-core command line tools.

**Pull request merged**
