### PR TITLE
THAPBI PICT v0.2.1

### PR DESCRIPTION
**Pull request by peterjc**
* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [X] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [X] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by peterjc** [comment]
So hosts is just enough to run the install? Thanks Bjoern.

**Comment by bgruening** [comment]
@peterjc noarch python package hardly needs anything else then pip and python.

Thanks for the update!

**Comment by druvus** [comment]
@bioconda-bot recheck

**Comment by druvus** [comment]
@bioconda-bot merge

**Comment by peterjc** [comment]
Thanks all, with hindsight the narrower build requirements makes perfect sense.

**Pull request merged**
