### PR TITLE
Update pyani to 0.2.13.1

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`pyani`](https://bioconda.github.io/recipes/pyani/README.html): **0.2.13** &rarr; **0.2.13.1**

[install with bioconda](http://bioconda.github.io/recipes/pyani/README.html) [Conda](https://anaconda.org/bioconda/pyani/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/pyani`](https://github.com//bioconda/bioconda-recipes/tree/bump/pyani/recipes/pyani) (click to view/edit other files)
Summary | pyani provides a package and script for calculation of genome-scale average nucleotide identity.
Home | [https://github.com/widdowquinn/pyani](https://github.com/widdowquinn/pyani)
Releases |[https://github.com/widdowquinn/pyani/tags](https://github.com/widdowquinn/pyani/tags)
Author | @widdowquinn
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by peterjc** [comment]
From the CI log:

```
08:26:39 BIOCONDA INFO (OUT) + average_nucleotide_identity.py -h
08:26:40 BIOCONDA INFO (OUT) Traceback (most recent call last):
08:26:40 BIOCONDA INFO (OUT)   File "/opt/conda/conda-bld/pyani_1723191765527/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin/average_nucleotide_identity.py", line 7, in <module>
08:26:40 BIOCONDA INFO (OUT)     from pyani.scripts.average_nucleotide_identity import run_main
08:26:40 BIOCONDA INFO (OUT)   File "/opt/conda/conda-bld/pyani_1723191765527/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib/python3.12/site-packages/pyani/scripts/average_nucleotide_identity.py", line 143, in <module>
08:26:40 BIOCONDA INFO (OUT)     from pyani import (
08:26:40 BIOCONDA INFO (OUT)   File "/opt/conda/conda-bld/pyani_1723191765527/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib/python3.12/site-packages/pyani/anim.py", line 62, in <module>
08:26:40 BIOCONDA INFO (OUT)     import intervaltree
08:26:40 BIOCONDA INFO (OUT) ModuleNotFoundError: No module named 'intervaltree'
08:26:41 BIOCONDA INFO (OUT) WARNING: Tests failed for pyani-0.2.13.1-pyhdfd78af_0.tar.bz2 - moving package to /opt/conda/conda-bld/broken
08:26:41 BIOCONDA INFO (OUT) TESTS FAILED: pyani-0.2.13.1-pyhdfd78af_0.tar.bz2
```

**Comment by peterjc** [comment]
Looking at https://github.com/widdowquinn/pyani/blob/v0.2.13.1/setup.py#L104 bioconda is still missing ``namedlist`` but it is only used for type annotation and https://pypi.org/project/namedlist/ suggests it is obsolete with an alternative.

**Comment by peterjc** [comment]
We do need to declare that too:

```
15:32:50 BIOCONDA INFO (OUT) + genbank_get_genomes_by_taxon.py -h
15:32:50 BIOCONDA INFO (OUT) Traceback (most recent call last):
15:32:50 BIOCONDA INFO (OUT)   File "/opt/conda/conda-bld/pyani_1723217326456/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin/genbank_get_genomes_by_taxon.py", line 7, in <module>
15:32:50 BIOCONDA INFO (OUT)     from pyani.scripts.genbank_get_genomes_by_taxon import run_main
15:32:50 BIOCONDA INFO (OUT)   File "/opt/conda/conda-bld/pyani_1723217326456/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib/python3.12/site-packages/pyani/scripts/genbank_get_genomes_by_taxon.py", line 66, in <module>
15:32:50 BIOCONDA INFO (OUT)     from pyani.download import create_hash
15:32:50 BIOCONDA INFO (OUT)   File "/opt/conda/conda-bld/pyani_1723217326456/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib/python3.12/site-packages/pyani/download.py", line 51, in <module>
15:32:50 BIOCONDA INFO (OUT)     from namedlist import namedlist
15:32:50 BIOCONDA INFO (OUT) ModuleNotFoundError: No module named 'namedlist'
15:32:51 BIOCONDA INFO (OUT) WARNING: Tests failed for pyani-0.2.13.1-pyhdfd78af_0.tar.bz2 - moving package to /opt/conda/conda-bld/broken
15:32:51 BIOCONDA INFO (OUT) TESTS FAILED: pyani-0.2.13.1-pyhdfd78af_0.tar.bz2
```

**Review by peterjc — APPROVED** [review]

**Comment by widdowquinn** [comment]
> Looking at https://github.com/widdowquinn/pyani/blob/v0.2.13.1/setup.py#L104 bioconda is still missing `namedlist` but it is only used for type annotation and https://pypi.org/project/namedlist/ suggests it is obsolete with an alternative.

Equivalent functionality eventually came into the PSL, IIRC.

**Comment by widdowquinn** [comment]
Thank you for sorting this out, @peterjc !

**Pull request merged**
