### PR TITLE
update stream_atac to 0.3.3a

### PR DESCRIPTION
**Pull request by huidongchen**
Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it. Note that if you are not already a member of the bioconda project (meaning that you can't add this label), please ping `@bioconda/core` so that your PR can be reviewed and merged (please note if you'd like to be added to the bioconda project). Please see https://github.com/bioconda/bioconda-recipes/issues/15332 for more details.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by bgruening** [comment]
@bioconda-bot recheck

**Comment by bgruening** [comment]
Do you know why conda is a dependency?

**Comment by dpryan79** [comment]
@bgruening It loads the conda module internally to run things like `conda install`.

@huidongchen Can you change this in subsequent release to just use `subprocess` to run `conda install`? `conda` is already in the path, so that should succeed.

**Comment by dpryan79** [comment]
@bioconda-bot merge

**Comment by huidongchen** [comment]
> @bgruening It loads the conda module internally to run things like `conda install`.
> 
> @huidongchen Can you change this in subsequent release to just use `subprocess` to run `conda install`? `conda` is already in the path, so that should succeed.

@dpryan79 @bgruening Sorry about the delay. Thanks a lot for helping review my PR! I will make sure that `subprocess` and `AGPL-3`  are used in the future release. Thanks again!

**Comment by huidongchen** [comment]
> @bgruening It loads the conda module internally to run things like `conda install`.
> 
> @huidongchen Can you change this in subsequent release to just use `subprocess` to run `conda install`? `conda` is already in the path, so that should succeed.

I noticed that with subprocess, there seems no easy way to output the pkg installation process in realtime as using `conda.cli.main`. Or do you have any recommended way to achieve it (i.e. outputing the real-time installation)?

**Comment by dpryan79** [comment]
Try setting `bufsize` to some small value in `subprocess.check_call()`

**Comment by huidongchen** [comment]
> Try setting `bufsize` to some small value in `subprocess.check_call()`

This command prints the stdout live in terminal but unfortunately not in Jupyter notebook. Since our package is mainly illustrated in Jupyter notebook, using subprocess doesn't seem to work as well as `conda.cli.main`

**Pull request merged**
