### PR TITLE
Update isescan meta.yaml to remove the pathes

### PR DESCRIPTION
**Pull request by xiezhq**
Update isescan meta.yaml to remove the pathes

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by xiezhq** [comment]
Update isescan meta.yaml to remove the pathes

**Comment by xiezhq** [comment]
@BiocondaBot please add label

**Comment by dpryan79** [comment]
Please disable circleci on your fork, it's blocking the checks here.

**Comment by xiezhq** [comment]
How to disable circleci on my fork?

**Comment by dpryan79** [comment]
You'll need to login to circleci with your github credentials and find where the list of repositories it's connected to is. I can't give you much in the way of guidance there, it's not something I've had to do in a while.

**Comment by xiezhq** [comment]
Thank you. Your the suggestion is already very helpful. I just removed authorization for OAuth application (CircleCI) in my github account.

**Comment by xiezhq** [comment]
I also removed the recipe API Tokens from my circleci account. Everything related to circleci have been removed from my github and circleci accounts.

**Comment by xiezhq** [comment]
How or when can I know the test/check has completed and returns either 'failed' or 'success'? Just wait for a few days?

**Comment by dpryan79** [comment]
Normally there would be an indicator of that, it's unclear to my why it's still not running.

**Comment by dpryan79** [comment]
Regardless, I can correct this in a different branch, since I'm rebuilding most of the packages at the moment anyway.

**Comment by dpryan79** [comment]
Oh, actually the patch should stay. It removes hard-coded paths that were in the original source code.

**Comment by xiezhq** [comment]
Your are right. The patch should stay for the curent version 1.7.2.1. I removed the hard-coded paths in the newer version and I want to update meta.yaml to remove the patches for the newer version. I update version number and source code file name and sha256 code accordingly.

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Pull request merged**
