### PR TITLE
Pepr update

### PR DESCRIPTION
**Pull request by shawnzhangyx**
* [x] I have read the guidelines above.
* [x] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by daler** [comment]
@shawnzhangyx we're having some build system issues which causes new recipes not to be built, so I canceled the remaining OSX build. I'll re-run this once things settle down.

**Comment by shawnzhangyx** [comment]
@daler Sure thanks. The Travis CI currently has a maximum load on OSX builds, maybe that is the reason?

**Comment by daler** [comment]
The build issues are actually something else; I'm trying to make sure those fixes get merged into the master branch. Since travis-ci typically is limited by OSX builds, I'm cancelling jobs that I know will fail (more specifically, pass with a false positive) that are still waiting for OSX. Hopefully that'll free up resources to get the fixes in more quickly.

**Comment by shawnzhangyx** [comment]
The builds of my fork finished and passed 30 min ago. Here is the info: https://travis-ci.org/shawnzhangyx/bioconda-recipes/builds/208351526

**Comment by daler** [comment]
Yep, but notice that nothing was actually built -- that's the issue that is getting fixed (see #4042).

Can you try merging in master and trying again please?

**Comment by shawnzhangyx** [comment]
I tried to merge master and build again. It says: 'The package failed to build because of the missing package "sharedmem" '. sharedmem is a pypi package and a dependence.  Is there a way to fix it?

**Comment by daler** [comment]
Add it as a dependency to your recipe. If it does not exist in the defaults, r, or conda-forge channels then you can add it as another recipe. See the bioconda docs https://bioconda.github.io/guidelines.html and https://bioconda.github.io/contribute-a-recipe.html for more info.

**Comment by shawnzhangyx** [comment]
I already added it as a dependency. I tried to add 'sharedmem' as another recipe and pushed the changes in this PR, but it still has the same error that 'sharedmem' is missing so 'pepr' could not be built. Should I add sharedmem and submit a separate PR first?

**Comment by daler** [comment]
Sorry, we're still having build issues unrelated to this recipe :(. Unlucky timing.

Though I don't see the additional sharedmem recipe in this PR, can you try pushing again?

**Comment by shawnzhangyx** [comment]
Oops sorry, I forgot to commit the changes. It is in now.

**Comment by shawnzhangyx** [comment]
@daler I've merged the changes in the master after your mentioned in #4055. Is this what you requested?

**Comment by daler** [comment]
Looks good, thanks

**Pull request merged**
