### PR TITLE
Move r-seurat-scripts to seurat-scripts and bump version.

### PR DESCRIPTION
**Pull request by pcm32**
:information_source:
Bioconda has finished the [GCC7 migration](https://github.com/bioconda/bioconda-recipes/issues/13578). If you are dealing with C/C++ or Python package it can be that you need to rebuild other dependent packages. [Bioconda utils - update-pinning](https://bioconda.github.io/updating.html#updating-recipes-for-a-pinning-change) will assist you with that. If you have any questions please use [issue 13578](https://github.com/bioconda/bioconda-recipes/issues/13578).

----------------

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

Besides updating the recipe, it also changes its name, deleting the previous recipe.

### CODE REVIEW

**Comment by pcm32** [comment]
It was originally pinned I understand due to this: https://github.com/bioconda/bioconda-recipes/issues/11298

I guess we would need to see if seurat has been pinned to another version, although I used the package like it is with actual data and it works. Does it produce an issue to leave it pinned?

**Comment by pcm32** [comment]
if I unpin it I get errors on build:

```
failed to get install actions, retrying.  exception was: Unsatisfiable dependencies for platform noarch: {'seurat-scripts==0.0.5=r351_0'}
WARNING:conda_build.build:failed to get install actions, retrying.  exception was: Unsatisfiable dependencies for platform noarch: {'seurat-scripts==0.0.5=r351_0'}
```

I unpinned R both on the host and run.

**Comment by pcm32** [comment]
Let me know what should I do @bgruening

**Comment by bgruening** [comment]
@pcm32 we are not building against 3.4 anymore. All new packages, including the entire bioconductor stack is 3.5. only. So I'm actually surprised that you get the latest packages.

I think we should figure out why this is throwing an error. Otherwise, we will be stuck in the past.

See here: https://anaconda.org/bioconda/r-seurat/files
The latest build is only for 3.5.1.

**Comment by pcm32** [comment]
I'll push the change and see whether it works, maybe it is an artifact of my local machine.

**Comment by pcm32** [comment]
Fails with the same error I get locally :-( 

```
failed to get install actions, retrying.  exception was: Unsatisfiable dependencies for platform noarch: {'seurat-scripts==0.0.5=r351_0'}

WARNING:conda_build.build:failed to get install actions, retrying.  exception was: Unsatisfiable dependencies for platform noarch: {'seurat-scripts==0.0.5=r351_0'}

Tests failed for seurat-scripts-0.0.5-r351_0.tar.bz2 - moving package to /opt/conda/conda-bld/broken
```

**Comment by pcm32** [comment]
Yes, I was going to do that, but I first wanted to check that test suite of seurat-scripts passed with 2.3.4... will do in the meantime.

**Comment by pcm32** [comment]
Couldn't we have seurat 2.3.1 available on r351?

**Comment by bgruening** [comment]
Yes, you would need to rebuild the older recipe.

**Comment by pcm32** [comment]
Pinning to 2.3.4 for seurat makes the solving environment eternal (~15 minutes now) on my mac :-(, so I cannot yet run the tests...

**Comment by bgruening** [comment]
It finished here in 1.21m. Please check your channel priorities. I'm fine with this PR.

**Comment by pcm32** [comment]
It breaks our data drive tests to move to 2.3.4

**Comment by pcm32** [comment]
This cannot be merged as it is.

**Comment by pcm32** [comment]
I would prefer if we keep this one pinned to R 3.4.1 and then I make a subsequent version that is compatible with seurat 2.3.4 on R 3.5.1. Would that be acceptable @bgruening ?

**Comment by pcm32** [comment]
Building against seurat 2.3.1 / R 3.4.1 works both locally and on the CI.

**Comment by bgruening** [comment]
Sure. You are the maintainer. All I'm saying it that you are not getting the latest seurat package. So if this package gets fixed, extended you will not get it anymore as you restrict yourself to R 3.4.1.

**Comment by pcm32** [comment]
Thanks for your help @bgruening!

**Pull request merged**
