### PR TITLE
Update cityhash to 0.1.7

### PR DESCRIPTION
**Pull request by mvdbeek**
* [x] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by bgruening** [comment]
My guess is that gcc, and libgcc is missing. We need to fix the missing output. I will be back next week and look at it if @daler did not beat me on that.

**Comment by mvdbeek** [comment]
yup, I'll have a go at the simulate-travis.py script, last week it didn't work for me, but I saw there were some changes.

**Comment by daler** [comment]
@bgruening I can reproduce this one locally, so I have something to debug.

**Comment by bgruening** [comment]
@daler great! I suspect something wired is happening with the output of the mulled container, but I do not have a real computer around for one week.
Thanks for looking into it.

**Comment by daler** [comment]
Yep, running in debug mode shows that mulled-build is erroring, but exiting with exit code 0. You have the check for the string "Unexpected exit code" [here](https://github.com/bioconda/bioconda-utils/blob/master/bioconda_utils/build.py#L132) but it's after "TEST SUCCESS" is logged.

```
[Nov 16 17:07:53] DEBU Run file [/home/ryan/miniconda3/lib/python3.5/site-packages/galaxy/tools/deps/mulled/invfile.lua]
[Nov 16 17:07:53] INFO Invoke Task [build]
[Nov 16 17:07:53] STEP Run image [continuumio/miniconda:latest] with command [[rm -rf /data/dist]]
[Nov 16 17:07:53] DEBU Creating container [step-0e2dc444c6]
[Nov 16 17:07:53] DEBU Created container [d481483e1854 step-0e2dc444c6], starting it
[Nov 16 17:07:53] DEBU Container [d481483e1854 step-0e2dc444c6] started, waiting for completion
[Nov 16 17:07:54] DEBU Container [d481483e1854 step-0e2dc444c6] completed with exit code [0] as expected
[Nov 16 17:07:54] DEBU Container [d481483e1854 step-0e2dc444c6] removed
[Nov 16 17:07:54] STEP Run image [continuumio/miniconda:latest] with command [[/bin/sh -c conda install  -c bioconda -c file://home/ryan/miniconda3/conda-bld -c r -c defaults -c conda-forge  cityhash=0.1.7=py27_0 -p /usr/local --copy --yes]]
[Nov 16 17:07:54] DEBU Creating container [step-48ade80689]
[Nov 16 17:07:54] DEBU Created container [977e2e839c8d step-48ade80689], starting it
[Nov 16 17:07:54] DEBU Container [977e2e839c8d step-48ade80689] started, waiting for completion
[Nov 16 17:08:08] SOUT Fetching package metadata ...............
[Nov 16 17:08:08] SOUT Solving package specifications: ..........
[Nov 16 17:08:08] SOUT 
[Nov 16 17:08:08] SOUT Package plan for installation in environment /usr/local:
[Nov 16 17:08:08] SOUT 
[Nov 16 17:08:08] SOUT The following packages will be downloaded:
[Nov 16 17:08:08] SOUT 
[Nov 16 17:08:08] SOUT package                    |            build
[Nov 16 17:08:08] SOUT ---------------------------|-----------------
[Nov 16 17:08:08] SOUT openssl-1.0.2j             |                0         3.2 MB
[Nov 16 17:08:08] SOUT cityhash-0.1.7             |           py27_0          77 KB  file://home/ryan/miniconda3/conda-bld
[Nov 16 17:08:08] SOUT setuptools-27.2.0          |           py27_0         521 KB
[Nov 16 17:08:08] SOUT pip-9.0.1                  |           py27_0         1.6 MB
[Nov 16 17:08:08] SOUT ------------------------------------------------------------
[Nov 16 17:08:08] SOUT Total:         5.3 MB
[Nov 16 17:08:08] SOUT 
[Nov 16 17:08:08] SOUT The following NEW packages will be INSTALLED:
[Nov 16 17:08:08] SOUT 
[Nov 16 17:08:08] SOUT cityhash:   0.1.7-py27_0  file://home/ryan/miniconda3/conda-bld (copy)
[Nov 16 17:08:08] SOUT openssl:    1.0.2j-0                                            (copy)
[Nov 16 17:08:08] SOUT pip:        9.0.1-py27_0                                        (copy)
[Nov 16 17:08:08] SOUT python:     2.7.12-1                                            (copy)
[Nov 16 17:08:08] SOUT readline:   6.2-2                                               (copy)
[Nov 16 17:08:08] SOUT setuptools: 27.2.0-py27_0                                       (copy)
[Nov 16 17:08:08] SOUT sqlite:     3.13.0-0                                            (copy)
[Nov 16 17:08:08] SOUT tk:         8.5.18-0                                            (copy)
[Nov 16 17:08:08] SOUT wheel:      0.29.0-py27_0                                       (copy)
[Nov 16 17:08:08] SOUT zlib:       1.2.8-3                                             (copy)
[Nov 16 17:08:08] SOUT 
[Nov 16 17:08:08] SOUT Fetching packages ...
openssl-1.0.2j 100% |###############################| Time: 0:00:00  35.12 MB/s:  --:--:--   0.00  B/s
cityhash-0.1.7 100% |###############################| Time: 0:00:00  60.80 MB/s:  --:--:--   0.00  B/s
setuptools-27. 100% |###############################| Time: 0:00:00  24.72 MB/s:  --:--:--   0.00  B/s
pip-9.0.1-py27 100% |###############################| Time: 0:00:00  29.37 MB/s:  --:--:--   0.00  B/s
[Nov 16 17:08:11] SOUT Extracting packages ...
[      COMPLETE      ]|##################################################| 100%                 |   0%
[Nov 16 17:08:11] SOUT Linking packages ...
[      COMPLETE      ]|##################################################| 100%                 |   0%
[Nov 16 17:08:11] DEBU Container [977e2e839c8d step-48ade80689] completed with exit code [0] as expected
[Nov 16 17:08:11] DEBU Container [977e2e839c8d step-48ade80689] removed
[Nov 16 17:08:11] STEP Wrap [build/dist] as [quay.io/biocontainers/cityhash:0.1.7--py27_0]
[Nov 16 17:08:11] DEBU Creating container [step-c72cc19cd7]
[Nov 16 17:08:12] DEBU Packing succeeded
[Nov 16 17:08:14] INFO Invoke Task [test]
[Nov 16 17:08:14] STEP Run image [quay.io/biocontainers/cityhash:0.1.7--py27_0] with command [[python -c "import cityhash"]]
[Nov 16 17:08:14] DEBU Creating container [step-3d37083b28]
[Nov 16 17:08:15] DEBU Created container [86f4f1686353 step-3d37083b28], starting it
[Nov 16 17:08:15] DEBU Container [86f4f1686353 step-3d37083b28] started, waiting for completion
[Nov 16 17:08:15] SERR Traceback (most recent call last):
[Nov 16 17:08:15] SERR File "<string>", line 1, in <module>
[Nov 16 17:08:15] SERR File "build/bdist.linux-x86_64/egg/cityhash.py", line 7, in <module>
[Nov 16 17:08:15] SERR File "build/bdist.linux-x86_64/egg/cityhash.py", line 6, in __bootstrap__
[Nov 16 17:08:15] SERR ImportError: libstdc++.so.6: cannot open shared object file: No such file or directory
[Nov 16 17:08:15] ERRO Task processing failed: Unexpected exit code [1] of container [86f4f1686353 step-3d37083b28], container preserved
./involucro -v=3 -f /home/ryan/miniconda3/lib/python3.5/site-packages/galaxy/tools/deps/mulled/invfile.lua -set CHANNELS='bioconda,file://home/ryan/miniconda3/conda-bld,r,defaults,conda-forge' -set TEST='python -c "import cityhash"' -set TARGETS='cityhash=0.1.7=py27_0' -set REPO='quay.io/biocontainers/cityhash:0.1.7--py27_0' -set BINDS='build/dist:/usr/local/,/home/ryan/miniconda3/conda-bld:/home/ryan/miniconda3/conda-bld' build-and-test

DEBUG bioconda_utils.build:build(131): STDERR:
None
ERROR bioconda_utils.build:build_recipes(356): BIOCONDA BUILD SUMMARY: of 1 recipes, 1 failed and 0 were skipped. Details of recipes and environments follow.
ERROR bioconda_utils.build:build_recipes(367): BIOCONDA BUILD SUMMARY: FAILED recipe cityhash-0.1.7-py27_0.tar.bz2, environment CONDA_PY=27;CONDA_R=3.3.1;CONDA_PERL=5.22.0;CONDA_BOOST=1.60;CONDA_GSL=1.16;CONDA_NCURSES=5.9;CONDA_NPY=110;CONDA_GMP=5.1

```

I'd like to write a test for this. Do you know of a good (minimal) way of getting mulled-build to exit that way?

**Comment by daler** [comment]
@bgruening @mvdbeek hopefully this will fix it: https://github.com/bioconda/bioconda-utils/pull/34

**Comment by daler** [comment]
@mvdbeek until this is merged into bioconda-utils master, you can try changing the `BIOCONDA_UTILS_TAG` in `.travis.yml` to `exit-code-check` which will use that fixed branch.

**Comment by bgruening** [comment]
Ok, let's merge this and see what master is saying! :)
Thanks @mvdbeek and @daler!

**Pull request merged**
