### PR TITLE
Bumped cnvkit version

### PR DESCRIPTION
**Pull request by micknudsen**
Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it. Note that if you are not already a member of the bioconda project (meaning that you can't add this label), please ping `@bioconda/core` so that your PR can be reviewed and merged (please note if you'd like to be added to the bioconda project). Please see https://github.com/bioconda/bioconda-recipes/issues/15332 for more details.

* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [X] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [X] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by micknudsen** [comment]
For some reason, the linter checks several other recipes than the one I updated. I pulled upstream master and made my changes. Any clues on how to prevent this excessive linting?

**Comment by micknudsen** [comment]
@biocondabot rebuild

**Comment by micknudsen** [comment]
@chapmanb Apparently there has only been generated a Python 2.7 build. I suspect this is caused by the linter told requiring `noarch: generic` (not sure what that actually means). Do you know anything about this?

**Comment by chapmanb** [comment]
Michael;
You're right, maybe leaving out `noarch` here is the right thing to do to get it built everywhere. I don't really understand all the different implications of `noarch: generic` versus `noarch: python` versus leaving it out. In this case, it's a small package so I'd revert back to not having it and hopefully it'll build all the python versions. Sorry about missing this earlier.

**Pull request merged**
