### PR TITLE
[BULK] Don't use r-base >=3.5, use a conda_build_config.yaml instead

### PR DESCRIPTION
**Pull request by dpryan79**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

This has been breaking `bulk`. Ideally whatever is broken in the conda-build API will get fixed instead.

Alternatively, we could globally set an R 3.5.1 pinning.

### CODE REVIEW

**Comment by dpryan79** [comment]
It at least gets past bioconductor-scnorm.

**Comment by dpryan79** [comment]
@bgruening If you have a second today, please merge.

**Comment by bgruening** [comment]
Mh, my fear is a little bit that we do not remember to clean up this hack for the next version.

**Comment by bgruening** [comment]
Can we create an issue to track this? Not that we are good in tracking issues, but at least we have a chance :)

**Comment by dpryan79** [comment]
Yeah, for the next release maybe we just change the pinning for the whole project...

Anyway, I'll create an issue.

**Comment by msarahan** [comment]
@bgruening The problem here is basically the same as people see with python.  Specifying any kind of constraint for python or R breaks conda-build's handling of it.  The core languages are very special cases.  It is best to use

```
build:
  skip: True  # [some r version limit]
```

instead.  PRs to improve this part of conda-build would be most welcome.

**Pull request merged**
