### PR TITLE
Put stable versions for all dependent packages.

### PR DESCRIPTION
**Pull request by lucventurini**
Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it. Note that if you are not already a member of the bioconda project (meaning that you can't add this label), please ping `@bioconda/core` so that your PR can be reviewed and merged (please note if you'd like to be added to the bioconda project). Please see https://github.com/bioconda/bioconda-recipes/issues/15332 for more details.

* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [ ] This PR adds a new recipe.
* [X] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [X] This PR updates an existing recipe.
* [X] This PR does something else (explain below).

Currently, installation of maker through bioconda fails due to conflicts in the environment resolution.
To solve this, I have modified the recipe so to pin all versions of packages to those I got by creating the environment with all dependent packages manually.

This should hopefully fix the installation issue.

### CODE REVIEW

**Comment by abretaud** [comment]
What exactly is your problem when trying to install maker?
Pinning everything with exact versions and hashes like this would bring other problems (when installing maker with other packages for example)

**Comment by lucventurini** [comment]
The problem I am encountering is one of unsatisfiable dependencies. I attach the log from a failed installation.

The problem disappears when creating the environment manually (using the packages contained within the `meta.yaml`), activate it, then install maker.

**Comment by dpryan79** [comment]
`conda create -n maker -d maker` doesn't report any issues, so it's likely that whatever you have in that environment isn't directly compatible according to conda. This is one of the regions we suggest people make new environments rather than installing packages into old ones.

**Comment by lucventurini** [comment]
> `conda create -n maker -d maker` doesn't report any issues, so it's likely that whatever you have in that environment isn't directly compatible according to conda. This is one of the regions we suggest people make new environments rather than installing packages into old ones.

Mmm, that is strange. The log from before comes from the following command:

`conda create -p /software/stable/maker/2.31.10/x86_64/ -c bioconda -- maker`

I have updated Conda to the latest version, and I also had deactivated all environments. **The errors from above still persist**.

**Comment by dpryan79** [comment]
Please use `-c conda-forge -c bioconda`.

**Comment by lucventurini** [comment]
Hi @dpryan79 , indeed this functions. Many thanks for pointing to the correct solution.

At this point, I agree with you that probably pinning the package versions is not the right solution.
However, the current state of affairs is not good either - users would not necessarily know to add conda-forge to channels (or, like me, would expect the conda package to bring in those dependencies automatically).

Is there anything that can be done in this sense?

**Comment by dpryan79** [comment]
Conda-forge is pretty much always required by bioconda packages, there will never be a different solution for this.

**Pull request closed without merging**
