### PR TITLE
Bump up DeepBGC to 0.1.26

### PR DESCRIPTION
**Pull request by prihoda**
Bump up DeepBGC to 0.1.26

### CODE REVIEW

**Comment by prihoda** [comment]
@bioconda-bot please review and merge

**Comment by prihoda** [comment]
@BiocondaBot please add label

**Comment by druvus** [comment]
@BiocondaBot please fetch artifacts

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Pull request merged**
