### PR TITLE
Ariba v2.14.0 release

### PR DESCRIPTION
**Pull request by kpepper**
I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
AFAIK, this recipe is directly relevant to the biological sciences
This PR updates an existing recipe.

### CODE REVIEW

**Comment by kpepper** [comment]
Hi **@druvus**. Thanks for the review. As can be seen from my commit comments, I spotted the license file property was missing from the meta.yml, added it in, and then got a Bioconda build failure as the actual file is missing from the PyPI distribution (it is in GitHub). I would need to do another Ariba release to fix it which I just don't have time for at the moment. I have already implemented/tested the change required (see https://github.com/sanger-pathogens/ariba/pull/272) and it will be in the next Ariba release so the issue is resolved, but can you allow it through for this one please?

**Comment by epruesse** [comment]
@biocondabot merge

**Comment by epruesse** [comment]
@BiocondaBot merge

**Comment by epruesse** [comment]
Hmm. That's a bug in the bot. Sigh.

**Pull request merged**
