### PR TITLE
vep: bumped major version

### PR DESCRIPTION
**Pull request by matthdsm**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by chapmanb** [comment]
Matthias;
Thanks for working on this. Right now ensembl-vep is in the `build-fail-blacklist` so isn't being built and the new version won't show up. I believe the blocker is bioperl which is being actively worked on after the conda build 3 migration. @bioconda/perl can likely confirm or deny the current status.

**Comment by matthdsm** [comment]
Damn, missed that during build.
Anyway, both this PR and the the one for cloudbiolinux can be merged as soon as the new vep is available.

Cheers
M

**Comment by chapmanb** [comment]
perl-bioperl is updated now (thank you Perl team) so I unblacklisted this and pinned to the recent version and all appears to be good so the latest VEP 93 should now be available in the bioconda channels (as soon as it builds). Thanks again.

**Comment by chapmanb** [comment]
Ugh sorry, it looks like I spoke too soon. Although `ensembl-vep` is out of the blacklist and it looks to have built in the PR:

https://circleci.com/gh/bioconda/bioconda-recipes/22201?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

93.2 isn't getting built and pushed:

https://anaconda.org/bioconda/ensembl-vep/files

Does anyone from @bioconda/core know what is going wrong here? I'm clueless about how to track and dig into what is going wrong. Thanks much.

**Comment by rvalieris** [comment]
looks like the build had failed because of a intermittent error from anaconda side, I rerun the job and the new version is up now !

**Comment by chapmanb** [comment]
Renan -- brilliant, thanks so much for re-pushing this. Much appreciated.

**Pull request merged**
