### PR TITLE
Add geNomad

### PR DESCRIPTION
**Pull request by apcamargo**
This PR adds the [geNomad](https://pypi.org/project/genomad/) tool for mobile genetic element identification.

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by apcamargo** [comment]
@BiocondaBot please update

**Comment by apcamargo** [comment]
@bioconda/core for some reason the test hangs and times out. The test command executed just fine, so I'm not sure what is causing this to happen.

**Comment by apcamargo** [comment]
@BiocondaBot please update

**Comment by apcamargo** [comment]
@bioconda/core The recipe is still hanging after `SOUT Solving environment: ...working... done`. Maybe this is happening because the package builds with [flit](https://flit.pypa.io/en/latest/)? Do you guys know other recipes here that don't use `setup.py`?

**Comment by apcamargo** [comment]
Now I think this might be related to TensorFlow, as another recipe that also depends on it is failing in the same step: https://github.com/bioconda/bioconda-recipes/pull/35868

**Comment by alienzj** [comment]
@apcamargo Seems to be constantly testing.

**Comment by apcamargo** [comment]
@alienzj do you know any way to fix this? The recipe looks fine. I have no idea why this is hapening

**Comment by alienzj** [comment]
@dpryan79 Dear guys, sorry ping you here. Need help please.

**Comment by dpryan79** [comment]
There's one step where the conda solver is still used and I suspect this is just choking (it's why I switched things to use mamba when possible instead for all of the other build steps). Usually restricting the run-time requirements gets around this.

**Comment by apcamargo** [comment]
@dpryan79 Still stuck after 3h. If this times out again do you think it could help if I restrict versions of more packages? I suspect TensorFlow is the main culprit here as I found another recipe that depends on it and has the same issue.

**Comment by dpryan79** [comment]
@apcamargo Yeah, give that a try, hopefully it will help :(

**Comment by apcamargo** [comment]
Testing it now. In case this doesn't solve, is there any way of requesting more build time?

**Comment by apcamargo** [comment]
No progress :(

Any other ideas @alienzj @dpryan79?

**Comment by alienzj** [comment]
```
2022-07-27T22:42:37.0043365Z 22:42:37 BIOCONDA INFO (ERR) [Jul 27 22:42:37] DEBU Creating container [step-957a0a23cd]
2022-07-27T22:42:37.0218864Z 22:42:37 BIOCONDA INFO (ERR) [Jul 27 22:42:37] DEBU Created container [50faa5d08a2e step-957a0a23cd], starting it
2022-07-27T22:42:37.2666008Z 22:42:37 BIOCONDA INFO (ERR) [Jul 27 22:42:37] DEBU Container [50faa5d08a2e step-957a0a23cd] started, waiting for completion
2022-07-27T22:43:28.1385787Z 22:43:28 BIOCONDA INFO (ERR) [Jul 27 22:43:28] SOUT Collecting package metadata (repodata.json): ...working... done
2022-07-28T04:32:53.2621341Z ##[error]The operation was canceled.
2022-07-28T04:32:53.2723610Z ##[section]Finishing: Test
```

Seems it stuck at `Collecting package metadata`

**Comment by alienzj** [comment]
Is it taking too long to generate a docker image?

**Comment by apcamargo** [comment]
Apparently it fails during this step, but I couldn't find the CI script that describes what is going on. If it's using conda maybe it would be faster to change it to mamba (although I'm sure the core team already did this everywhere where the change could be done).

Aside from that, I'm out of ideas

**Comment by apcamargo** [comment]
@alienzj @dpryan79 Finally worked! Thanks for your help!

**Review by alienzj — APPROVED** [review]

**Comment by alienzj** [comment]
Great!

**Comment by apcamargo** [comment]
@BiocondaBot please merge

**Pull request merged**
