### PR TITLE
Metagene annotator 1.0 patch

### PR DESCRIPTION
**Pull request by wclose**
Updating source locations for binaries.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by dpryan79** [comment]
metagene_annotator will need to be removed from the blacklist.

**Comment by dpryan79** [comment]
@bioconda-bot merge

**Comment by dpryan79** [comment]
Thanks @wclose!

**Comment by wclose** [comment]
Thanks for your help @dpryan79!

**Pull request merged**
