### PR TITLE
added mkl-dnn recipe

### PR DESCRIPTION
**Pull request by ThomasWollmann**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by cbrueffer** [comment]
This seems more appropriate for conda-forge due to its general nature?

**Comment by ThomasWollmann** [comment]
@cbrueffer feel free to move it to conda-forge.

**Comment by johanneskoester** [comment]
We have made changes to our build system (migrated from Travis CI to Circle CI). Please update your fork with the latest upstream/master. Further, please target the master branch with your PR.

**Comment by johanneskoester** [comment]
Wait, this should indeed be conda-forge. Please issue a PR there.

**Pull request closed without merging**
