### PR TITLE
update sequana recipe

### PR DESCRIPTION
**Pull request by cokelaer**
Update sequana recipes to latest version ( 0.13.2)

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by cokelaer** [comment]
@BiocondaBot please review & merge

**Comment by cokelaer** [comment]
@BiocondaBot please review & merge

**Comment by cokelaer** [comment]
@bgruening I see that sequana package is black listed and was not built for a while. I have now built a new valid recipes 
Would it be possible to remove the sequana package from the black list please ? thanks in advance

**Comment by raivivek** [comment]
@cokelaer You can remove the package from the blacklist in a new commit and add that to this pull request.

**Comment by cokelaer** [comment]
@raivivek after a couple of trials/errors it looks like I reached a memory issues on the bioconda-test. 

There are quite a few dependencies in Sequana but all standard (numpy/pandas/statsmodels/etc). Do you have any clues on how to fix this memory issue ? thanks

**Comment by raivivek** [comment]
The error seems to be coming from `conda` where it's reporting `MemoryError` when trying to solve the environment. I found a bunch of issues online with similar error but none that seems to consistently reproduce or fix this issue. Maybe @dpryan79 might have some input.

**Comment by dpryan79** [comment]
You can remove cython from the host section, since this is pure python (from what I can tell). The memory errors were probably due to exhausting resources on the CI nodes. I have a PR that I'm working on to update bioconda-utils to use boa for building. Hopefully that will help avoid this sort of thing once it's ready. Xref: https://github.com/bioconda/bioconda-utils/pull/755

**Comment by cokelaer** [comment]
@dpryan79 thanks for the feedback. I'll remove cython from the host.

I have updated sequana today and I'm trying to fix this recipe again. Looks like the memory issue is gone, which is great. I add back the 

  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"

Not sure what it does really but I thought it might fix the current issue I am facing. 

and I patched 2 dependencies (removed xml2dict which is not present on conda and for  pykwalify, I removed the pinned version). I will see how it goes tomorrow. cheers

**Comment by cokelaer** [comment]
@dpryan79 alomost there. 
I got an error on the built system. I have the same exact pbl locally with 

    bioconda-utils build  --packages sequana --loglevel debug

But no precise information about the underlying issue.

The conda built is successful but I get the error does not give any clues.

**Comment by cokelaer** [comment]
@dpryan79 looks like I managed to find a way to build the recipe. However, I had to remove the section commands/tests:


    #  commands:
    #    - {{ name }} --version > /dev/null
    #    - {{ name }} --version | grep {{ version }}
    #    - {{ name }} --help

there is an error with the call to the commands. I tried to redirect the error/output  to files, but it also failed without useful messages. Not sure whether it will work at the end. What do you think ? thanks. Sorry for the spam

**Comment by cokelaer** [comment]
@dpryan79 any chance to merge the PR. I've tried the commands in many different ways. Not sure this is a real pbl. There was no specific error. I paste here below my last local trial using:

    commands:
        - sequana 2>&1 > /dev/null

and I got this kind of message 

    11:12:59 BIOCONDA INFO (OUT) Executing transaction: ...working...
    11:12:59 BIOCONDA INFO (OUT) 
    11:12:59 BIOCONDA INFO (OUT) done
    11:13:03 BIOCONDA INFO (ERR) + sequana
    11:13:06 BIOCONDA INFO (ERR) Tests failed for sequana-0.13.2-pyh5e36f6f_0.tar.bz2 - moving package to 

Here you can see the command 'sequana' followed by "Test failed"  and then:

    /home/cokelaer/miniconda3/envs/sequana/envs/bioconda/conda-bld/broken
    11:13:06 BIOCONDA INFO (ERR) WARNING:conda_build.build:Tests failed for sequana-0.13.2-pyh5e36f6f_0.tar.bz2 - 
    moving package to /home/cokelaer/miniconda3/envs/sequana/envs/bioconda/conda-bld/broken
    11:13:06 BIOCONDA INFO (ERR) WARNING conda_build.build:tests_failed(2976):
    Tests failed for sequana-0.13.2-pyh5e36f6f_0.tar.bz2 - moving package to /home/cokelaer/miniconda3/envs/sequana/envs/bioconda/conda-bld/broken
    11:13:06 BIOCONDA INFO (OUT) export PREFIX=/home/cokelaer/miniconda3/envs/sequana/envs/bioconda/conda-bld/sequana_1647857118247/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol11:13:06 BIOCONDA INFO (OUT) 
    export SRC_DIR=/home/cokelaer/miniconda3/envs/sequana/envs/bioconda/conda-bld/sequana_1647857118247/test_tmp
    11:13:06 BIOCONDA INFO (OUT) import: 'sequana'
    11:13:06 BIOCONDA INFO (OUT) Creating directory UNKNOWN/.config/sequana
    11:13:06 BIOCONDA INFO (OUT) Creating directory UNKNOWN/.config/bioservices
    11:13:06 BIOCONDA INFO (OUT) import: 'sequana.enrichment'

Here I can see that the import worked since it has created files in ~/.config and then:

    11:13:06 BIOCONDA INFO (OUT) import: 'sequana.kraken'
    11:13:06 BIOCONDA INFO (OUT) import: 'sequana.modules_report'
    .....
    11:13:06 BIOCONDA INFO (OUT) import: 'sequana.enrichment'
    11:13:06 BIOCONDA INFO (ERR) TESTS FAILED: sequana-0.13.2-pyh5e36f6f_0.tar.bz2
    11:13:06 BIOCONDA INFO (OUT) import: 'sequana.kraken'
    11:13:06 BIOCONDA INFO (OUT) import: 'sequana.modules_report'
    11:13:06 BIOCONDA INFO (OUT) import: 'sequana.multiqc'
    ...
    11:13:06 BIOCONDA INFO (OUT) import: 'sequana.utils'
    11:13:06 BIOCONDA INFO (OUT) import: 'sequana.viz'
    11:13:06 BIOCONDA INFO (OUT) Traceback (most recent call last):
    11:13:06 BIOCONDA INFO (OUT)   File "$PREFIX/bin/sequana", line 10, in <module>
    11:13:06 BIOCONDA INFO (OUT)     sys.exit(main())
    11:13:06 BIOCONDA INFO (OUT) TypeError: 'module' object is not callable
    11:13:11 BIOCONDA ERROR COMMAND FAILED (exited with 1): 
    /home/cokelaer/miniconda3/envs/sequana/envs/bioconda/bin/conda build --override-channels --no-anaconda-upload -c conda-forge -c bioconda -c defaults -e /home/cokelaer/miniconda3/envs/sequana/envs/bioconda/conda_build_config.yaml -e /home/cokelaer/miniconda3/envs/sequana/envs/bioconda/lib/python3.7/site-packages/bioconda_utils/bioconda_utils- conda_build_config.yaml recipes/sequana/meta.yaml
    11:13:11 BIOCONDA ERROR BUILD FAILED recipes/sequana
    11:13:11 BIOCONDA INFO (COMMAND) conda build purge
    11:13:12 BIOCONDA ERROR BUILD SUMMARY: of 1 recipes, 1 failed and 0 were skipped. Details of recipes and 
    environments follow.
    11:13:12 BIOCONDA ERROR BUILD SUMMARY: FAILED recipe recipes/sequana
    (bioconda) [cokelaer@localhost bioconda-recipes]$ ls /home/cokelaer/miniconda3/envs/sequana/envs/bioconda/conda- 
   bld/brokensequana-0.13.2-pyh5e36f6f_0.tar.bz2


Any ideas ? thanks

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@BiocondaBot please merge

**Pull request merged**
