### PR TITLE
Update to pyani v0.2.3

### PR DESCRIPTION
**Pull request by peterjc**
* [X] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [X] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

I'm hoping that the nosetests do not time out... [*no longer include pyani's own tests, see below*]

### CODE REVIEW

**Comment by peterjc** [comment]
(Is there any reason this pulls the tagged release from GitHub, rather than from PyPI?)

**Comment by druvus** [comment]
@peterjc no specific reason.

The latest version seems to have dropped the R dependency.

**Comment by peterjc** [comment]
OK, my attempt to run the tests fails:

```
/opt/conda/conda-bld/test_tmp/run_test.sh: line 5: cd: tests: No such file or directory
```

Clearly the working directory is not where I expected it to be...

**Comment by daler** [comment]
@peterjc due to build system constraints we don't generally run unit tests. For this recipe, just the import and checking the installed scripts should be fine.

https://bioconda.github.io/guidelines.html#tests

**Comment by peterjc** [comment]
@daler Understood.

**Comment by peterjc** [comment]
For my own notes, I think I would have needed https://conda.io/docs/building/meta-yaml.html#source-files to run the tool's own tests.

**Comment by peterjc** [comment]
TravisCI failed with ``Can't write the history file [Errno 28] No space left on device``, can one of the team try restarting that build please?

**Comment by daler** [comment]
@peterjc restarted. Nothing obvious in the recipe that would cause this; let's see if it passes this time.

**Comment by daler** [comment]
BTW @peterjc, see #1 if you'd like to be on the team.

**Comment by bgruening** [comment]
Thanks to all and happy Easter!

**Comment by peterjc** [comment]
Thanks everyone.

@druvus Good catch on rpy also not being needed anymore.

@daler I'd be happy to join the bioconda-recipes team once I've got a better feel for how Conda, BioConda, etc work. Right now it seems a little premature.

**Pull request merged**
