### PR TITLE
multiphate update

### PR DESCRIPTION
**Pull request by bgruening**
:information_source:
Bioconda has finished the [GCC7 migration](https://github.com/bioconda/bioconda-recipes/issues/13578). If you are dealing with C/C++ or Python package it can be that you need to rebuild other dependent packages. [Bioconda utils - update-pinning](https://bioconda.github.io/updating.html#updating-recipes-for-a-pinning-change) will assist you with that. If you have any questions please use [issue 13578](https://github.com/bioconda/bioconda-recipes/issues/13578).

----------------

* [ ] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [ ] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by bgruening** [comment]
@carolzhou let's see if this one is also getting green.

**Comment by carolzhou** [comment]
I am really not sure how this works.

**Comment by carolzhou** [comment]
Please won't you instruct me how to proceed from here. I created a new meta.yaml modeled after the example you provided. I removed the build.sh file and included the line for pip install ({{ PYTHON }} -m pip install . --no-deps -vv), which I suppose installs standing code without a requirements.txt file. It appears that changes to my fork are auto-conveyed to bioconda-recipes. Thus, it seems to me that the current state of my fork is ready for processing, since all tests have passed. However, it is not clear to me that the passed tests reflect the most recently modified meta.yaml. As a novice in this process, there is much that is unclear, as well as non-obvious.  I appreciate your kind assistance.

**Comment by bgruening** [comment]
@carolzhou I haven't seen any of these changes here in bioconda.

What I have done so far is I fixed your recipe and updated it see this one here: https://github.com/bioconda/bioconda-recipes/pull/13901

You were also missing tests in your initial version, so I added some. But as you see if I add `- multiPhate.py` as a test the tests are failing so probably this package will not work. Or is this not how people should run your tool.

We have some documentation of how to create a recipe here that might help to get you started: https://bioconda.github.io/contributing.html

**Comment by carolzhou** [comment]
Ok, so the changes I make on my fork are not transferred to bioconda.  How do I transfer my newest meta.yaml to bioconda without opening a new PR, which I believe I am not supposed to do.  My latest meta.yaml has a list of tests, to which could be added:  "python multiPhate.py usage", which is how the tool is run (or, actually the user passes a config file).

**Comment by bgruening** [comment]
Hi @carolzhou,

I added your test to https://github.com/bioconda/bioconda-recipes/pull/13901 and it fails with `multiPhate.py: command not found`.

**Comment by carolzhou** [comment]
Please can you explain how you did this:    url: https://github.com/carolzhou/multiPhATEb/archive/a706cac23339588fe9fa4a34d607fcdcabccfe5a.tar.gz
  sha256: ef2b7206a32a6ee41cac266f99f2dc5986e2b1a93d10fbe66f9526e45b5b6e13

**Comment by carolzhou** [comment]
I am just now submitting a new PR.  The meta.yaml is updated with new tests, and I have modified it to the best of my ability to more or less match your edits, but with specifics regarding dependent code versions. However, you have placed a multiphate.tar.gz in an archive directory, with a checksum. I don't know how to do this. My attempts at local conda-build testing fail because the checksum keeps changing when conda-build tries to download the tarball. I am at a loss here.

**Comment by carolzhou** [comment]
Why does it not let me do a pull request?

**Comment by carolzhou** [comment]
There is a copy of the intended meta.yaml in my multiPhATEb.git repository.

**Comment by dpryan79** [comment]
This recipe ended up in the wrong directory, I'm trying to fix it in #14148

**Pull request merged**
