### PR TITLE
update ganon to 0.3.4

### PR DESCRIPTION
**Pull request by pirovc**
update ganon to 0.3.4

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by pirovc** [comment]
@BiocondaBot please fetch artifacts

**Comment by pirovc** [comment]
@BiocondaBot please add label

**Comment by telatin** [comment]
Hi @pirovc , I noticed you didn't require Python 3 and the installation will work on miniconda2 (but the program won't start). Did you have a reason for this or can you update the requirements?

**Comment by pirovc** [comment]
@telatin I did have the requirements before (https://github.com/bioconda/bioconda-recipes/commit/6d311074a467dca3999303c5a9c88980b3b13dbf#diff-1902b2113301545fee3fe776426b6871de181f4cd49763edec5ee605b96f7f8f) however it was always forcing the installation of python 3.8 which is undesirable. I changed the requirement for the build section and it seem to work fine so far. I didn't know about the miniconda2 issue. Not sure what is the recommended action in this case.

**Comment by telatin** [comment]
> @telatin I did have the requirements before ([6d31107#diff-1902b2113301545fee3fe776426b6871de181f4cd49763edec5ee605b96f7f8f](https://github.com/bioconda/bioconda-recipes/commit/6d311074a467dca3999303c5a9c88980b3b13dbf#diff-1902b2113301545fee3fe776426b6871de181f4cd49763edec5ee605b96f7f8f)) however it was always forcing the installation of python 3.8 which is undesirable. I changed the requirement for the build section and it seem to work fine so far. I didn't know about the miniconda2 issue. Not sure what is the recommended action in this case.

I asked the community for suggestions. Meanwhile, I think we need to specify version requirements in any case, to allow for a correct installation. 
So, if you want to revert that, I will test on different systems and containers to check if I notice the problem you encountered. Thanks!

**Comment by dpryan79** [comment]
Putting the required version in the host/run section will break things, since this needs to build packages specifically for individual python versions (thus, the `skip:` entry). You can restrict python versions in the normal way only if the package is `noarch: python` or `noarch: generic`.

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Pull request merged**
