### PR TITLE
Update shovill recipe and dependencies

### PR DESCRIPTION
**Pull request by andersgs**
## Bump build version number

- bwa
- flash
- libdeflate
- lighter
- perl-findbin
- pilon
- samtools
- seqtk
- skesa
- trimmomatic
- velvet

## Add license_file parameter

- bwa
- flash
- lighter
- seqtk
- velvet

## Fix perl-findbin recipe

 - Made sure a test is present and that `noarch: generic` is specified

## Fix shovill megahit dependency issue

- Currently, shovill will only work with versions of megahit larger than
or equal to 1.2.7.

- This addresses issues tseemann/shovill#112 and voutcn/megahit#226 and #16545

## Fix velvet build recipe to use conda CC and CFLAGS env var

- Also changed the recipe to use Conda zlib

## Add patch to work with compiler envvars

- Patches Makefiles to allow for the correct compilation under
Bioconda for bwa/0.7.2, bwa/0.78, seqtk, and lighter

- seqtk patch has been submitted as a PR upstream: lh3/seqtk#142
- bwa patch has been submitted as a PR upstream: lh3/bwa#247
- lighter patch has been submitted as a PR upstream: mourisl/Lighter#22

Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it. Note that if you are not already a member of the bioconda project (meaning that you can't add this label), please ping `@bioconda/core` so that your PR can be reviewed and merged (please note if you'd like to be added to the bioconda project). Please see https://github.com/bioconda/bioconda-recipes/issues/15332 for more details.

* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [ ] This PR adds a new recipe.
* [X] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [X] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by andersgs** [comment]
@bioconda/core please review and merge. I would like to be added to the project, if possible.

**Comment by voutcn** [comment]
@andersgs the version of megahit should be set to >=1.2.7

**Comment by andersgs** [comment]
Thank you @voutcn. I checked last night and hadn’t seen the latest release. I’ll have no power for the next 8 hours. But will address that once the power comes back.

**Comment by bgruening** [comment]
@andersgs the PR title does not really match what is included here? Can you please elaborate a little bit.

**Comment by andersgs** [comment]
Hi @bgruening. 

Yes, it snowballed a little. 

It started off with me trying to fix an issue with the shovill recipe where the compatible versions of megahit needed to be updated. I thought I could update the pinning of shovill and dependencies in the process. I used bioconda-utils for this. 

That is when things got a bit out of control. Many recipes generated linting warnings and errors. So, I cleaned those up. Then several recipes failed to build. The errors were related to not finding gcc or g++. So, I cleaned those up and patched Makefilles as appropriate. I pushed those patches upstream. 

I realise the PR has gotten quite big. But that is partially because of the long list of shovill dependencies. I think the end result is positive. Happy to make any changes to improve the PR. 

Cheers.  A.

**Comment by andersgs** [comment]
I have now updated the shovill recipe to use megahit versions 1.2.7 @voutcn. A local build seemed to work --- now waiting for CircleCI to finish.

**Comment by andersgs** [comment]
@bgruening, I have cleaned up the submission comments above to make what I have done more transparent.

**Comment by dpryan79** [comment]
Thanks @andersgs, nicely done. Your bioconda invite should arrive shortly.

**Comment by andersgs** [comment]
Thank you @dpryan79. Glad I could help. The invitation has been received and accepted. :)

Cheers. A.

**Pull request merged**
