### PR TITLE
Update seurat-scripts to 0.3.0

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`seurat-scripts`](https://bioconda.github.io/recipes/seurat-scripts/README.html): **0.0.9** &rarr; **0.3.0**

[install with bioconda](http://bioconda.github.io/recipes/seurat-scripts/README.html) [Conda](https://anaconda.org/bioconda/seurat-scripts/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/seurat-scripts`](https://github.com//bioconda/bioconda-recipes/tree/bump/seurat_scripts/recipes/seurat-scripts) (click to view/edit other files)
Summary | A set of wrappers for individual components of the Seurat package.
Home | [https://github.com/ebi-gene-expression-group/r-seurat-scripts](https://github.com/ebi-gene-expression-group/r-seurat-scripts)
Releases |[https://github.com/ebi-gene-expression-group/r-seurat-scripts/tags](https://github.com/ebi-gene-expression-group/r-seurat-scripts/tags)
Recipe Maintainer(s) | @pcm32, @pinin4fjords, @nh3
Author | `@ebi-gene-expression-group`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by pcm32** [comment]
This should be ready now.

**Comment by pcm32** [comment]
@BiocondaBot please add label

**Comment by dpryan79** [comment]
@pcm32 You only want R 4.0 and not 4.0 and 4.1?

**Comment by pcm32** [comment]
The issue is that Seurat 3.2.3 format converters don't work with the libraries that r-base 4.1 restricts to. This is only an intermediate release for a Seurat 3 converter module for Galaxy. Then I will move to Seurat 4 and that will be be using newer R. But I need a legacy format converters for older versions of single cell formats :-(.

**Comment by pcm32** [comment]
But for a straight answer, yes, I only want R 4.0 for this. Thanks for taking a look @dpryan79 !

**Comment by dpryan79** [comment]
Can't argue with that, thanks @pcm32 !

**Pull request merged**
