### PR TITLE
Detonate bump

### PR DESCRIPTION
**Pull request by caseywdunn**
* [ X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [X ] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [X ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by caseywdunn** [comment]
I am attempting to fix the detonate recipe. There are a few things to take care of, including:

- The url points to a tarball on a lab website that was down for a while (it just came back up). I am pointing it to the git repo.
- It requires an old beta version of samtools that is incompatible with other recipes.

The Travis build indicates, though, that detonate is on a blacklist:

https://travis-ci.org/bioconda/bioconda-recipes/jobs/329629802

This is due to a boost issue:

https://github.com/bioconda/bioconda-recipes/blob/master/boost-1.61-migration-blacklist

@bioconda/core - is it possible to remove this recipe from the blacklist so that I can work on fixing it and use the travis tests to check progress?'

Thanks again.

**Comment by daler** [comment]
@caseywdunn go ahead and remove it from the blacklist, which should allow travis-ci to build and test it. If you can get it to build successfully that would be fantastic!

**Comment by caseywdunn** [comment]
Thanks @daler . Should I do that in master, or the feature branch where I am working? I am not sure which branch the blacklist is read from for a travis build, and don't want to much things up.

**Comment by daler** [comment]
We treat the blacklists like a branch-specific filter, so removing it from just the feature branch should do the trick and allow it to try building on this branch.

**Pull request merged**
