### PR TITLE
Add recipe for fastQValidator

### PR DESCRIPTION
**Pull request by dfornika**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by dfornika** [comment]
Build is complaining:

```
/opt/rh/devtoolset-2/root/usr/libexec/gcc/x86_64-redhat-linux/4.8.2/ld: cannot find -lz
```
although I do include `zlib` as a host and run dependency. Also followed these directions:

https://bioconda.github.io/troubleshooting.html#zlib-errors

**Comment by dfornika** [comment]
@bioconda/core I'm having a bit of trouble getting the linker to find `zlib`.

Is there something I can add to the `build.sh` to help?

**Comment by npavlovikj** [comment]
@dfornika , is it possible to make a different conda recipe for "libStatGen"? The makefile for "libStatGen" as part of ""fastqvalidator" clones the git repo and builds some of the libraries for bam/samtools, and that is where the "zlib" error occurs. If you create a separate recipe it will be easier to debug and set the proper flags I think.

**Comment by dfornika** [comment]
Ok thanks @npavlovikj, I'll do that.

**Comment by dfornika** [comment]
I've submitted a pull request here:

https://github.com/bioconda/bioconda-recipes/pull/12342

**Comment by npavlovikj** [comment]
@dfornika , looks like there are some hard-coded paths to "libstatgen"'s Makefile in fastqvalidator, so the pushed change didn't work for me. I will have some time tonight to play with it if the recipe is still failing.

**Comment by dfornika** [comment]
Ok @npavlovikj thanks for all your help.

**Comment by daler** [comment]
Closing due to inactivity, please re-open if needed.

**Pull request closed without merging**
