### PR TITLE
update to  rebuild samtools to match with htslib 1.15

### PR DESCRIPTION
**Pull request by maarten-k**
See #33361

### CODE REVIEW

**Comment by maarten-k** [comment]
Did not work out as planned:
htslib is still limited until 1.15
   "htslib >=1.14,<1.15.0a0",

**Comment by maarten-k** [comment]
Check the artifacts and now depends on htslib 1.15

**Comment by jmarshall** [comment]
The right way to fix this is to bump bioconda's pinning to htslib-1.15 and remove the _conda_build_config.yaml_ files from the samtools and bcftools recipes. That way everything that depends on htslib will remain compatible with each other, and samtools/bcftools won't be incompatible with everything else (cf #30296).

**Comment by maarten-k** [comment]
So updating https://github.com/bioconda/bioconda-utils/blob/45a9c7216c7b739bbf5a39dcaa8b4402d35d801f/bioconda_utils/bioconda_utils-conda_build_config.yaml#L25 to 1.15 would do the trick? I do not feel too confident to play around with this after a long day. Can someone with more experience pick this up?

**Comment by jmarshall** [comment]
This is #33366 and its companion bioconda-utils PR.

**Comment by maarten-k** [comment]
@jmarshall  Thanks for the  PR (and all your great work on htslib and samtools !)

**Pull request closed without merging**
