### PR TITLE
CodingQuarry: new recipe

### PR DESCRIPTION
**Pull request by nextgenusfs**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by nextgenusfs** [comment]
This tool requires `openmp` for compilation, seems to be erring during the Mac OS build. After looking at https://github.com/bioconda/bioconda-recipes/issues/8869, I tried to do the following in the `build.sh`:
```
if [ "$(uname)" == Darwin ] ; then
  CXXFLAGS="-Wl,-rpath ${PREFIX}/lib -L${PREFIX}/lib -fopenmp"
else
  CXXFLAGS="-fopenmp -g -O3"
fi

#now build
make CXX="${CXX}" CXXFLAGS="${CXXFLAGS}"
```
Anybody know what I'm doing wrong?  Or suggest a work around to get it to build on Mac?  Locally I can build it with `g++-7` on my Mac and it works fine, but I'm not sure how to do that with the new anaconda compilers? Thus I tried the suggestion in the linked post.

**Comment by nextgenusfs** [comment]
@kastman would you be able to check this recipe for me?  I wrote this awhile ago -- but seems to have not been merged. I was having problems with Mac compilation (per usual).

**Comment by kastman** [comment]
Hey @nextgenusfs - A quick look seems alright to me for the linux compilation, but I haven't looked at recipes in a few months so maybe a 3rd opinion would be good. I can try to look at the Mac compilation over the weekend, or we can do that in a separate PR to the feedstock once it's built. Whichever sounds better to you?

**Comment by kastman** [comment]
Sorry @nextgenusfs , but I didn't get a chance to check the mac recipe today; hopefully tomorrow? Also, happy to merge the linux recipe, or maybe ask for a review on the bioconda gitter?

**Comment by kastman** [comment]
Hi @nextgenusfs  - Finally got a chance to look at this. I think that you were too fancy in the build file by overriding the compiler var and setting it with `CXX=clang++`. I have it working for a local `conda build .` (though I can't test it locally with `circleci build` because it tries to compile half the recipes in bioconda and I'm done shaving **that** yak).

I think you can cherry pick [this commit](https://github.com/bioconda/bioconda-recipes/commit/344f8f035f03591852310726e094c8a35d9faa04) into your branch, or just make the changes yourself (note that I reverted from `c++` to `c` and then didn't have to patch the makefile). Take a look and see if it works for you?

Note that this does get rid of adding `-fopenmp` to the regular CXX flags for the linux build - not sure if that will be necessary again or if it's set correctly, but you may want to re-jigger it if you remember.

**Comment by kastman** [comment]
@nextgenusfs I'm giving up for the night; the local `circleci build` seems now to not see `g++` when it's compiling inside the linux vm, so I'm flumoxed; the commit you had which passed in July now fails for me so I'm clearly missing something.

A related note that you might want to look at: I saw in the [conda doc]( https://conda.io/docs/user-guide/tasks/build-packages/compiler-tools.html#rpaths-specifically-rpath-link ) that the rpath may belong in `LDFLAGS` instead of `CXXFLAGS`.  E.g. for the darwin part of the conditional add rpath: `LDFLAGS="$LDFLAGS -Wl,-rpath-link,$PREFIX/lib" and then `make CXX="$CXX" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS"`

**Comment by nextgenusfs** [comment]
I don't remember all the steps that I took in troubleshooting -- probably we can make a simplified linux only recipe?  But you said that that is now failing as well.  To build locally it required c++ but the variables were for c, and thats why I made those makefile adjustments. I can check again tomorrow at work where I have linux.

**Comment by kastman** [comment]
Fixed for OSX and PR accepted in https://github.com/bioconda/bioconda-recipes/pull/11815 - closed #10097

**Pull request closed without merging**
