### PR TITLE
tidk v0.2.62

### PR DESCRIPTION
**Pull request by Euphrasiologist**
Update tidk to v 0.2.62.

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

### General instructions

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

### Instructions for avoiding API, ABI, and CLI breakage issues
Conda is able to record and lock (a.k.a. pin) dependency versions used at build time of other recipes.
This way, one can avoid that expectations of a downstream recipe with regards to API, ABI, or CLI are violated by later changes in the recipe.
If not already present in the meta.yaml, make sure to specify `run_exports` (see [here](https://bioconda.github.io/contributor/linting.html#missing-run-exports) for the rationale and comprehensive explanation).
Add a `run_exports` section like this:

```yaml
build:
  run_exports:
    - ...

```

with `...` being one of:

| Case                             | run_exports statement                                               |
| -------------------------------- | ------------------------------------------------------------------- |
| semantic versioning              | `{{ pin_subpackage("myrecipe", max_pin="x") }}`     |
| semantic versioning (0.x.x)      | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}`   |
| known breakage in minor versions | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| known breakage in patch versions | `{{ pin_subpackage("myrecipe", max_pin="x.x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| calendar versioning              | `{{ pin_subpackage("myrecipe", max_pin=None) }}`    |

while replacing `"myrecipe"` with either `name` if a `name|lower` variable is defined in your recipe or with the lowercase name of the package in quotes.

### Bot commands for PR management

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

Note that the <code>@BiocondaBot please merge</code> command is now depreciated. Please just squash and merge instead.

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

## Summary by CodeRabbit

- **New Features**
	- Updated `tidk` package to version 0.2.63 with improved installation commands.
	- Added support for the Rust compiler and OpenSSL in build requirements.

- **Bug Fixes**
	- Enhanced installation output with the `--verbose` flag for better diagnostics.

- **Documentation**
	- Simplified test commands for easier usage.

### CODE REVIEW

**Review by bgruening — APPROVED** [review]
Nice cleanup, thanks

**Comment by mbhall88** [comment]
@Euphrasiologist the build seems to be failing because when the test command runs, `tidk -h` it can't find the database file in `~/.local/share/tidk/tidk_database.csv`. This seems to be because you try and get clades **before** actually building the CLI https://github.com/tolkit/telomeric-identifier/blob/e62799336e6580dbb2b4fe455eb1a7f2eee2399b/src/main.rs#L7

So `tidk -h` will check for the existence of the database and get clades *and then* return the help menu. I assume this is not what you want and maybe the call to `get_clades` should be moved after building the CLI?

**Comment by Euphrasiologist** [comment]
@BiocondaBot please add label

**Comment by mbhall88** [comment]
Ps you can remove the OpenSSL dependency by switching to the rustls-tls feature in reqwests e.g. I did this recently and made it a lot easier to build for multiple targets https://github.com/mbhall88/nohuman/blob/6578dfc5743e5d85902ff83f554dd446cc9670c6/Cargo.toml#L25

**Pull request merged**
