### PR TITLE
Update fwdpy11 to 0.19.1

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`fwdpy11`](https://bioconda.github.io/recipes/fwdpy11/README.html): **0.18.3** &rarr; **0.19.1**

[install with bioconda](http://bioconda.github.io/recipes/fwdpy11/README.html) [Conda](https://anaconda.org/bioconda/fwdpy11/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/fwdpy11`](https://github.com//bioconda/bioconda-recipes/tree/bump/fwdpy11/recipes/fwdpy11) (click to view/edit other files)
Summary | Forward-time population genetic simulation in Python.
Home | [http://pypi.python.org/pypi/fwdpy11](http://pypi.python.org/pypi/fwdpy11)
Releases |[https://pypi.org/pypi/fwdpy11/json](https://pypi.org/pypi/fwdpy11/json)

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by therealgenna** [comment]
Hi @molpopgen, I'm trying to fix this automatic PR issues and I had to make a couple of changes for it to work in my local env first. I had to change `build.sh` to install `cbindgen` and put it in the non-default path (it's not found when default is used, or at least I will still need to export the default `$HOME/.cargo/bin:$PATH`):
```
cargo install --root ${PATH%%:*}/../.cargo/ cbindgen
export PATH=${PATH%%:*}/../.cargo/bin:$PATH
GSL_ROOT_DIR=$PREFIX python -m pip install --no-deps --ignore-installed -vv .
```
(Had to replace `$PYTHON` by the hard-coded `python` because I saw an error about unrecognized `-m` command, meaning that `$PYTHON` was not set. Maybe it was a one-off - don't know.

But then the main issue is that I get errors like
```
/opt/conda/conda-bld/fwdpy11_1668717450556/work/fwdpy11/headers/fwdpy11/types/Population.hpp:11:10: fatal error: fwdpp/poptypes/popbase.hpp: No such file or directory
```
and similar with `bioconda-build` and in my local conda env when I issue `python -m pip install --no-deps --ignore-installed -vv .` in the unpacked directory `fwdpy11-0.19.0` from the recipe `meta.yaml`:
```
url: https://files.pythonhosted.org/packages/81/25/c7abd5cd81512e3cf543ce969e2730c30254460c30d0e1bba2dc6705497f/fwdpy11-0.19.0.tar.gz
```
To fix that I had to
```
cp -rp ../..//env-fwdpy11/lib/python3.10/site-packages/fwdpy11/headers/fwdpp/ fwdpy11-0.19.0/fwdpy11/headers
```
because the `fwdpp` is missing from the downloaded `fwdpy11-0.19.0.tar.gz`. I took the `fwdpp` directory from the package that was installed manually with `pip install fwdpy11`.

So I guess you might be able to modify the `fwdpy11-0.19.0.tar.gz`, or please correct me if I am dong something wrong.

I've also changed the `requirements/host` section of `meta.yaml` to
```
     - intervaltree
     - pybind11 ==2.10.0
     - numpy
     - scipy
     - attrs >=0.19.2
     - black
     - tskit
     - msprime
     - gsl
     - boost
     - pytest
     - pytest-xdist
     - setuptools_scm
     - demes ==0.2.0
     - rust >=1.62.1
     - hypothesis
     - fwdpp
```
(I've put `rust >=1.62.1` instead of `rust ==1.62.1` from https://github.com/molpopgen/fwdpy11/blob/main/requirements/conda_minimal_deps.txt
because while trying to build with `bioconda-utils` there was some error ... in my local manually made conda env `v1.62.1` worked.

Also, is there a way to use already available compiled packages from `PyPI` instead of building from source in `bioconda-build`?

Thanks!

**Comment by molpopgen** [comment]
It looks like there is a packaging bug.  I'll do a bug fix release after the Thanksgiving holiday and fix that.

Using the pre-built package from pypi is idea: `python -m pip install fwdpy11`.  But I am not aware of a way to use those to generate a bioconda package.  There is also, technically, a potential issue with ABI incompatibility, but hopefully my use of manylinux_2_28 for the Linux wheels mitigates that.  No guarantees for macOS, though.

**Comment by molpopgen** [comment]
Tracking issue for upstream is molpopgen/fwdpy11#1049

**Comment by therealgenna** [comment]
Sounds good, thanks!

**Comment by molpopgen** [comment]
The problem is partially due to basing the wheel building work flow on Python 3.8.  I can read the logs when I base the image on a github actions work flow setting up Python 3.10 and see that the headers are copied.  There is more work to do, though.  I need to test that each supported version yields a valid sdist.

**Comment by molpopgen** [comment]
I finally worked out a fix for this.  bioconda will have to skip 0.19.0.  Unless something unforeseen happens, I will release 0.19.1 sometime after the (US) holiday weekend.

**Comment by molpopgen** [comment]
@therealgenna No idea why things are failing now.  The upstream CI now validates that we can build from the sdist and I am currently building from it on my laptop running Fedora 37.

**Comment by therealgenna** [comment]
I could compile it on linux (locally with `--docker`) after adding `- rust >=1.62.1` to requirements/host and installing `cbindgen` (the way I posted above). But currently it fails during testing:
```
ImportError: libfwdpy11core.so: cannot open shared object file: No such file or directory
```
and I think it's probably because of the warning during the build step:
```
Warning: rpath /opt/conda/conda-bld/fwdpy11_1669847098929/_build_env/lib is outside prefix /opt/conda/conda-bld/fwdpy11_1669847098929/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place (removing it)
```
and subsequent
```
WARNING (fwdpy11,lib/python3.9/site-packages/fwdpy11/_fwdpy11.cpython-39-x86_64-linux-gnu.so): $RPATH/libfwdpy11core.so not found in packages, sysroot(s) nor the missing_dso_whitelist.
```
The first warning seems to remove this `$RPATH` so then `libfwdpy11core.so` is not found, if I get it right. BUt I don't know how to fix it at this point ...

**Comment by molpopgen** [comment]
Do you know what cmake version is being used?

**Comment by molpopgen** [comment]
> cmake 3.25.0 or 3.25.1

That is fine -- the minimum is 3.15.

**Comment by therealgenna** [comment]
I am not totally clear about your comment that "changing build.sh to install cbindgen is not a stable solution. Conda builds should not be changing files that are part of the upstream repo -- doing so is inherently fragile." Are you saying that bioconda's `build.sh` comes from some other repo? I am only aware of https://github.com/bioconda/bioconda-recipes/blob/master/recipes/fwdpy11/build.sh which seems to have been created by you years ago.

I see [here](https://github.com/molpopgen/fwdpy11/blob/main/requirements/conda_minimal_deps.txt) that `rust==1.62.1` is listed; but it's not in bioconda's `meta.yaml`. Also [here](https://molpopgen.github.io/fwdpy11/misc/developersguide.html) it is stated that one needs `cbindgen` and can install it via `cargo install cbindgen`. That's basically what I did, as I don't know how else bioconda will know to do it.

I don't think bioconda's `meta.yaml` and `build.sh` can generally be generated correctly automatically.

**Comment by molpopgen** [comment]
> I am not totally clear about your comment that "changing build.sh to install cbindgen is not a stable solution. Conda builds should not be changing files that are part of the upstream repo -- doing so is inherently fragile." Are you saying that bioconda's `build.sh` comes from some other repo? I am only aware of https://github.com/bioconda/bioconda-recipes/blob/master/recipes/fwdpy11/build.sh which seems to have been created by you years ago.
> 
> I see [here](https://github.com/molpopgen/fwdpy11/blob/main/requirements/conda_minimal_deps.txt) that `rust==1.62.1` is listed; but it's not in bioconda's `meta.yaml`. Also [here](https://molpopgen.github.io/fwdpy11/misc/developersguide.html) it is stated that one needs `cbindgen` and can install it via `cargo install cbindgen`. That's basically what I did, as I don't know how else bioconda will know to do it.
> 
> I don't think bioconda's `meta.yaml` and `build.sh` can generally be generated correctly automatically.

My bad -- my brain is in rust land and I read `build.sh` as `build.rs`.

**Comment by therealgenna** [comment]
> My bad -- my brain is in rust land and I read `build.sh` as `build.rs`.
Ah, ok, no problem!

**Comment by molpopgen** [comment]
> I see [here](https://github.com/molpopgen/fwdpy11/blob/main/requirements/conda_minimal_deps.txt) that `rust==1.62.1` is listed; but it's not in bioconda's `meta.yaml`. Also [here](https://molpopgen.github.io/fwdpy11/misc/developersguide.html) it is stated that one needs `cbindgen` and can install it via `cargo install cbindgen`. That's basically what I did, as I don't know how else bioconda will know to do it.

These should be the required changes.  The offloading of a lot of code to `fwdpy11core` and using some rust code in that library are both new in the 0.19 series. It seems that bioconda is doing something like copying all the build files to "elsewhere".   That should be okay, as it is what `python -m build` does and that generates a valid wheel.

**Comment by molpopgen** [comment]
@therealgenna  -- this can be closed?

**Comment by therealgenna** [comment]
Someone with permissions has to take a look. I think @dpryan79 merged my fix into here, so I guess it needs a last push.

**Review by molpopgen — APPROVED** [review]

**Comment by molpopgen** [comment]
I happen to have those permissions! Let's give it a whirl?  Thanks for this!  I definitely didn't have the bandwidth for it right now.

**Comment by molpopgen** [comment]
Yep.  I think the next trick is for my to find time to test-drive it in a Linux VM.  I don't have access to macOS machines these days, but I can ask a few users.

**Pull request merged**
