### PR TITLE
Add Connor recipe

### PR DESCRIPTION
**Pull request by sebastian-luna-valero**
* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [X] This PR adds a new recipe.
* [X] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

See discussion in https://github.com/umich-brcf-bioinf/Connor/issues/3

### CODE REVIEW

**Comment by sebastian-luna-valero** [comment]
@cgates 

Could you please confirm whether `connor` will be able to work with `pysam > 0.9.0`? Are you planning a new release soon?

For our reference, please see:
https://travis-ci.org/bioconda/bioconda-recipes/jobs/272803591#L827

i.e., `connor=0.5` depends on `pysam=0.9.0` which is not available for `python=3.6`

I can just pin `connor=0.5` to `python=3.5` for the time being and then update the conda package for a future release of `connor` working with the latest versions of `pysam` and `python`.

Please let me know your thoughts.

Best regards,
Sebastian

**Comment by cgates** [comment]
I understand.  I don't anticipate a problem with pysam>0.9.0; I will try to relax those pins and let you know Friday.
Thanks!
cg

**Comment by cgates** [comment]
Hi Sebastian,

I've relaxed the pins and released a new master. This version supports all combinations of py2.7 - py3.6 * pysam 0.8.4-0.12. Please feel free to try again and let me know if there are problems.

Best,
cg

**Comment by sebastian-luna-valero** [comment]
Many thanks @cgates 

I have just updated the recipe to reflect the changes so let's wait for the test results.

Would you like to be listed as a maintainer for this recipe? It should not involve much effort but please let me know your preferences.

Best regards,
Sebastian

**Comment by sebastian-luna-valero** [comment]
@cgates 

Currently, I only call `connor --help` to test the recipe:
```
test:
  commands:
    - connor --help

```

and that's working fine. Do you want me to add any other test to the this recipe to make sure `connor` is working as expected?

Best regards,
Sebastian

**Comment by cgates** [comment]
Calling --help is diligent and probably sufficient for this purpose.

**Comment by sebastian-luna-valero** [comment]
Thanks @bgruening

**Pull request merged**
