### PR TITLE
[Dont merge] test intarna rebuild

### PR DESCRIPTION
**Pull request by martin-raden**
* [ ] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [ ] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [x] This PR does something else (explain below).

this PR tests why the intarna (re)build is broken...

### CODE REVIEW

**Comment by martin-raden** [comment]
Uaks.. should it be that easy??

**Comment by martin-raden** [comment]
Was about to ask what has changed in the build system, since this is not working anymore... we will see!
Thanks for joining @bgruening !

**Comment by bgruening** [comment]
We are using GCC7 now and are about to drop the GCC from the container.

**Comment by martin-raden** [comment]
So do i need to rebuild viennarna again?

**Comment by martin-raden** [comment]
Mhh..
```
checking whether the C++ compiler works... no

configure: error: in `/opt/conda/conda-bld/intarna_1549658229757/work':

configure: error: C++ compiler cannot create executables

See `config.log' for more details
```

**Comment by bgruening** [comment]
Jetzt wo du es sagst, ich könnte Hilfe hier gebrauchen ;)

https://github.com/bioconda/bioconda-recipes/pull/13465

also see here: https://bioconda.github.io/updating.html#updating-recipes-for-a-pinning-change

**Comment by martin-raden** [comment]
Seems this goes deeper.. i will stop here for tonight.. bed is calling 😊

**Comment by martin-raden** [comment]
Aber ich pack mit an.. nächtle!

**Comment by bgruening** [comment]
Still the same error even with a new viennarna version :(

**Comment by martin-raden** [comment]
HI @bgruening 
thanks for joining, was a mix of new cxx compiler and hard coded gxx in build.sh
👍

**Pull request closed without merging**
