### PR TITLE
Bioconductor tximeta Bump

### PR DESCRIPTION
**Pull request by apeltzer**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

Needs this for the nf-core/scrnaseq workflow :-) And therfore removed it from blacklist :-)

### CODE REVIEW

**Comment by apeltzer** [comment]
Hey @bioconda/core - I initially only wanted to get `bioconductor-tximeta` to be R3.6 compatible but had to (piece by piece) add in more recipes to get it built properly. 

Not sure it will suceed, but at the moment the build looks fine and okay and the recipes have been on the blacklist marked as "maybe too old and nobody needs them" (which isn't the case - at least I need them for the pipeline linked above ;-)).

**Comment by apeltzer** [comment]
These are a hell of other R packages as dependencies...

**Comment by dpryan79** [comment]
This is why I just do them all at once in bulk :) Anyway, it's in the queue, everything will get rebuilt in a week or so I expect.

**Comment by apeltzer** [comment]
So I can basically close this then @dpryan79 ?

**Comment by dpryan79** [comment]
Yeah, it's not needed. For the November bioconductor release I need to modify bulk and bioconda-utils to run multiple jobs in parallel. Then this won't take so painfully long.

**Pull request closed without merging**
