### PR TITLE
add python-bioformats recipe

### PR DESCRIPTION
**Pull request by ThomasWollmann**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by ThomasWollmann** [comment]
@bgruening is there a common fix for libjvm.so in Bioconda?

**Comment by ThomasWollmann** [comment]
@joshmoore Do you have an idea how to fix bioformats with OpenJDK?

**Comment by ThomasWollmann** [comment]
The code for https://github.com/bioconda/bioconda-recipes/blob/master/recipes/bioformats/meta.yaml does not exist anymore.

**Comment by bgruening** [comment]
Just testing, this is aweful :)

**Comment by bgruening** [comment]
uha, green ...

**Comment by bgruening** [comment]
No its your task :)

**Pull request merged**
