### PR TITLE
seqkit 0.10.2

### PR DESCRIPTION
**Pull request by shenwei356**
Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it. Note that if you are not already a member of the bioconda project (meaning that you can't add this label), please ping `@bioconda/core` so that your PR can be reviewed and merged (please note if you'd like to be added to the bioconda project). Please see https://github.com/bioconda/bioconda-recipes/issues/15332 for more details.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by shenwei356** [comment]
The [lint check failed](https://circleci.com/gh/bioconda/bioconda-recipes/66811?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link) occurred before when I updated [taxonkit v0.5.0](https://github.com/bioconda/bioconda-recipes/pull/16234). I don't know what magic @johanneskoester and @druvus used to correct this. I think the recipe is OK.

**Comment by npavlovikj** [comment]
@shenwei356 , that is a known bug in the Linting. I believe adding:
```
extra:
  skip-lints:
    - should_be_noarch_generic
    - should_not_be_noarch_source
```
should suppress those messages. 

While modifying your recipe, can you please make sure you follow the section structure in `meta.yaml`:
(vars), package, source, build, test, about, extra ?
Not having the proper order may cause some issues with the autobump in future.

**Comment by shenwei356** [comment]
yes @npavlovikj it works! Wait, a test was blocked, it's weird.

```
lint - Success
test-linux - Success
test-macos - Blocked
```

**Comment by npavlovikj** [comment]
The OSX build systems is currently busy with building all bioconductor packages, so just give it some time - Blocked means it is just waiting for resources.

**Pull request merged**
