### PR TITLE
pin java-jdk of trimmomatic 0.35 to >=8

### PR DESCRIPTION
**Pull request by tomkinsc**

### CODE REVIEW

**Comment by bgruening** [comment]
@tomkinsc maybe you also want to update the wrapper to use the new python-wrapper to call the JAR file?
xref: https://github.com/bioconda/bioconda-recipes/issues/1519

**Comment by tomkinsc** [comment]
Is [this](https://github.com/bioconda/bioconda-recipes/issues/1519#issuecomment-225106463) considered the final version of that wrapper?

**Comment by tomkinsc** [comment]
I'm going to merge this in for now. There are several other java packages (trimmomatic, trinity, snpeff, gatk, etc.) relying on the bash wrapper, and updating them all can be a common PR for easier tracking in the commit logs.

**Comment by bgruening** [comment]
@tomkinsc this is the final version: https://github.com/bioconda/bioconda-recipes/pull/1731
Sorry for my late answer.

**Pull request merged**
