### PR TITLE
update stream to 0.3.1

### PR DESCRIPTION
**Pull request by huidongchen**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by johanneskoester** [comment]
Is compilation of source code involved? Locally, for testing the build time try to just build using `conda build` directly. No need to apply the whole bioconda-utils machinery.

**Comment by huidongchen** [comment]
> Your build simply seems to take too long. CircleCI waits 6 hours for it to complete. How long does it take on a local machine?

It was taking more than one hour. So I killed it before it finished. But I did the local testing by `bioconda-utils build recipes config.yml --git-range master`. But I will try it again using conda build directly

**Comment by johanneskoester** [comment]
Is that pure compilation time? Seems really long to me. We have over 5000 packages on bioconda, some of them quite complex, and they all build within 5 hours, mostly within minutes. Does stream involve recompilation of external libraries?

**Comment by huidongchen** [comment]
> Is that pure compilation time? Seems really long to me. We have over 5000 packages on bioconda, some of them quite complex, and they all build within 5 hours, mostly within minutes. Does stream involve recompilation of external libraries?

Hi Johannes, 'stream' package doesn't require the recompilation of external libraries but it relies on a few R packages, especially a heavy one 'chromvar' (available in bioconductor). I wrote a bioconda recipe for it before (https://bioconda.github.io/recipes/bioconductor-chromvar/README.html) but I suspect the package is somehow broken. (I tried to install it `conda install bioconductor-chromvar` but it gets stuck).

I'm not sure why it happens and how I should fix that dependency package 'bioconductor-chromvar'. Any suggestions would be really appreciated.

**Comment by huidongchen** [comment]
> > Is that pure compilation time? Seems really long to me. We have over 5000 packages on bioconda, some of them quite complex, and they all build within 5 hours, mostly within minutes. Does stream involve recompilation of external libraries?
> 
> Hi Johannes, 'stream' package doesn't require the recompilation of external libraries but it relies on a few R packages, especially a heavy one 'chromvar' (available in bioconductor). I wrote a bioconda recipe for it before (https://bioconda.github.io/recipes/bioconductor-chromvar/README.html) but I suspect the package is somehow broken. (I tried to install it `conda install bioconductor-chromvar` but it gets stuck). So I guess if we fix the dependency package 'bioconductor-chromvar' we should be able to build 'stream'.
> 
> I'm not sure why it happens and how I should fix that dependency package 'bioconductor-chromvar'. Any suggestions would be really appreciated.

@johanneskoester I updated bioconductor-chromvar (There was indeed an issue installing it)  but it doesn't seem to help. The same build timeout error happened again.. #12931

**Comment by huidongchen** [comment]
> When you do a conda build locally, where does it spend so much time? Please post the build logs (STDOUT and STDERR) of that local build.

Hi Johannes, thanks for your reply. The issues is solved by specifying the version of chromvar package (setting it to the latest one). #12941 Thanks for  your help.

**Pull request closed without merging**
