### PR TITLE
Update BioConda pypeFLOW package to v1.0.0

### PR DESCRIPTION
**Pull request by peterjc**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

This follows on from pull request #9016 for v0.1.1

In the absence of an official tag on the upstream repository,
this is the commit which bumped the version number to 1.0.0

See PacificBiosciences/pypeFLOW#51

Note that the dependencies declared in the setup.py changed,
which is reflected in the meta.yaml dependencies. It now
requires networkx.

Also, the updated setup.py declares additional python libraries
which we now test can be imported.

### CODE REVIEW

**Comment by peterjc** [comment]
Their ``setup.py`` requests networkx version between 1.7 and 1.10 inclusive:

https://github.com/PacificBiosciences/pypeFLOW/blob/79c77235eb10e7b36a98ada891e1e6ef454aed58/setup.py#L16

```python
    install_requires=[
        'networkx >=1.7, <=1.10',
    ],
```

I therefore put that in the ``meta.yaml`` file. However, the build failed:

```
Can't build /opt/recipe due to unsatisfiable dependencies:

  - networkx >=1.7, <=1.10
```

Currently conda-forge has networkx 1.11 as its oldest version:
https://anaconda.org/conda-forge/networkx/

However, the default channel has networkx 1.7, 1.8, 1.8.1, 1.9, 1.9.1 and 1.10 packages:
https://anaconda.org/anaconda/networkx/

**Comment by rvalieris** [comment]
the commit you are referencing is part of a [PR](https://github.com/PacificBiosciences/pypeFLOW/pull/39) that also changes the dependency of networkx to 1.11, I think its better to use this: https://github.com/PacificBiosciences/pypeFLOW/commit/e331fad50be98d83e95a4a354bed2c81a8351392

**Comment by peterjc** [comment]
Thanks @rvalieris - I'll give that a go later this week

**Comment by peterjc** [comment]
Failed linting in anther recipe, rebasing to latest master...

**Pull request merged**
