### PR TITLE
Package Effective T3 v1.0.1 for BioConda

### PR DESCRIPTION
**Pull request by peterjc**
* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [X] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

Based on the install recipe https://github.com/peterjc/pico_galaxy/blob/master/tools/effectiveT3/tool_dependencies.xml used in my Galaxy wrapper http://toolshed.g2.bx.psu.edu/view/peterjc/effectivet3 which was not setup as a separate package.

As per #4772 the main JAR file is in the ``meta.yaml`` file, and the child files are fetched and verified from ``build.sh``.

Note: It appears to be BioConda convention to use all lower case names (I was using ``effectiveT3`` in Galaxy).

### CODE REVIEW

**Comment by peterjc** [comment]
Have I got something silly wrong in my test block, because this does not look like a sensible command line to be run:

```
15:48:40 BIOCONDA ERROR COMMAND FAILED: mulled-build build-and-test effectivet3=1.0.1--0 -n biocontainers --test effectivet3 -f empty.fasta -m TTSS_ANIMAL-1.0.1.jar -t selective -q && effectivet3 -f empty.fasta -m TTSS_PLANT-1.0.1.jar -t selective -q && effectivet3 -f empty.fasta -m TTSS_STD-1.0.1.jar -t selective -q && effectivet3 -f empty.fasta -m TTSS_STD-2.0.2.jar -t selective -q --extra-channels file://anaconda/conda-bld,r,defaults,conda-forge
```

Note this looks like this:

```
mulled-build build-and-test effectivet3=1.0.1--0 -n biocontainers --test $TEST --extra-channels file://anaconda/conda-bld,r,defaults,conda-forge
```

Should the test commands not be wrapped in quotes or something to separate them from the trailing `` --extra-channels`` option

**Comment by peterjc** [comment]
CC @bgruening: Thank you for your explanation about not using single quotes in the test command over on #4799. Could you comment on this related puzzle?

Under Linux, https://travis-ci.org/bioconda/bioconda-recipes/jobs/236008966 says:

Line 545, this is probably bad logging of a list of strings - if run exactly as written this would fail:

```
13:16:18 BIOCONDA ERROR COMMAND FAILED: mulled-build build-and-test effectivet3=1.0.1--0 -n biocontainers --test effectivet3 -f empty.fasta -m TTSS_ANIMAL-1.0.1.jar -t selective -q && effectivet3 -f empty.fasta -m TTSS_PLANT-1.0.1.jar -t selective -q && effectivet3 -f empty.fasta -m TTSS_STD-1.0.1.jar -t selective -q && effectivet3 -f empty.fasta -m TTSS_STD-2.0.2.jar -t selective -q --extra-channels file://anaconda/conda-bld,r,defaults,conda-forge
13:16:18 BIOCONDA ERROR STDOUT+STDERR:
```

Line 598, the ``&&`` combined test command seems sensible:

```
[May 25 13:16:18] STEP Run image [quay.io/biocontainers/effectivet3:1.0.1--0] with command [[effectivet3 -f empty.fasta -m TTSS_ANIMAL-1.0.1.jar -t selective -q && effectivet3 -f empty.fasta -m TTSS_PLANT-1.0.1.jar -t selective -q && effectivet3 -f empty.fasta -m TTSS_STD-1.0.1.jar -t selective -q && effectivet3 -f empty.fasta -m TTSS_STD-2.0.2.jar -t selective -q]]
```

Line 604, provided the test commands do not contain any single quotes, the mulled command looks sensible:

```
involucro -v=2 -f /anaconda/lib/python3.5/site-packages/galaxy_lib-17.5.9-py3.5.egg/galaxy/tools/deps/mulled/invfile.lua -set CHANNELS='bioconda,file://anaconda/conda-bld,r,defaults,conda-forge' -set TEST='effectivet3 -f empty.fasta -m TTSS_ANIMAL-1.0.1.jar -t selective -q && effectivet3 -f empty.fasta -m TTSS_PLANT-1.0.1.jar -t selective -q && effectivet3 -f empty.fasta -m TTSS_STD-1.0.1.jar -t selective -q && effectivet3 -f empty.fasta -m TTSS_STD-2.0.2.jar -t selective -q' -set TARGETS='effectivet3=1.0.1=0' -set REPO='quay.io/biocontainers/effectivet3:1.0.1--0' -set BINDS='build/dist:/usr/local/,/anaconda/conda-bld:/anaconda/conda-bld' build-and-test
```

Can you tell where line 545 comes from, so we can check and if need be fix that logging?

(Separately I think I can now see why the recipe fails - the BioConda Java wrapper script template requires Python as a run-time dependencies)

**Comment by peterjc** [comment]
Progress - works on Linux, but ``sha256sum`` is not on the Mac image.

**Comment by peterjc** [comment]
I'm trying this approach in my ``build.sh`` file:

```
# Expect ``sha256sum $FILE`` on Linux, or ``shasum -a 256 $FILE`` on macOS
SHA256CMD="$(command -v sha256sum || echo shasum -a 256)"
```

**Comment by bgruening** [comment]
@peterjc I think sha256sum is part of gnu coreutils, right? Can you add this to your build dependencies? As Linux is green your tests are now working I suppose :)

**Comment by peterjc** [comment]
The alias trick didn't work:

```bash
# Expect ``sha256sum $FILE`` on Linux, or ``shasum -a 256 $FILE`` on macOS
command -v sha256sum || alias sha256sum="shasum -a 256"
```

So I'll try adding https://anaconda.org/bioconda/coreutils as a build dependency as you suggest.

**Comment by peterjc** [comment]
And yes, the Linux tests are working, but some of the logging around the test command is currently very confusing - so I'd like to report it as a bug but I'm still unclear where in the stack that line was coming from.

**Comment by bgruening** [comment]
@peterjc still WIP?

**Comment by peterjc** [comment]
Finally passed the tests - then its no longer a WIP. I'd remove the label now, but the interface is very fiddly on a phone and won't have internet on a computer till tomorrow. Thanks!

**Comment by bgruening** [comment]
Then let's merge it and get you a package when you arrive at work :)

**Comment by peterjc** [comment]
Lovely, thank you :)

**Comment by liaochenlanruo** [comment]
Does effectivet3 support Python 3.7？

**Comment by peterjc** [comment]
The tool itself is written in Java, so should be fine on Python 3.7

The recipe uses a Python wrapper to invoke it, and looking at that quickly just now I see nothing obvious in terms of Python 2 vs 3. I would expect it to work.

**Comment by liaochenlanruo** [comment]
@peterjc Thanks! I had submitted a pull request #33235 to allow effectivet3 to support python 3. however, something wrong happened, and would you have a check? Thanks a lot!

**Pull request merged**
