### PR TITLE
ENH add chardet version specification to argnorm

### PR DESCRIPTION
**Pull request by Vedanth-Ramji**
Specify chardet as requirement due to error during installation with pronto.

### CODE REVIEW

**Comment by Vedanth-Ramji** [comment]
@BiocondaBot rebuild

**Comment by luispedro** [comment]
Does `argNorm` even depend on `chardet`? It's not listed in its requirement (https://github.com/BigDataBiology/argNorm/blob/main/requirements.txt)

**Comment by Vedanth-Ramji** [comment]
pronto 2.5.6 is dependent on chardet. When I try to install the latest argNorm version I get this error:
image

I am just trying to fix this now.

**Comment by luispedro** [comment]
This is probably best fixed in the pronto recipe (or maybe even upstream)

**Comment by Vedanth-Ramji** [comment]
Just opened a new issue here: https://github.com/althonos/pronto/issues/224

**Comment by Vedanth-Ramji** [comment]
The problem should be with the channels. `conda install -c bioconda argnorm` didn't work, but `conda install -c bioconda -c conda-forge argnorm` did. This makes sense as `chardet` uses the `conda-forge` channel. I think the channels weren't loaded properly from my end.

**Pull request closed without merging**
