### PR TITLE
Update pangolin to 3.1.11

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`pangolin`](https://bioconda.github.io/recipes/pangolin/README.html): **3.1.10** &rarr; **3.1.11**

[install with bioconda](http://bioconda.github.io/recipes/pangolin/README.html) [Conda](https://anaconda.org/bioconda/pangolin/files)

Info | Link
-----|-----
Recipe | [`recipes/pangolin`](https://github.com//bioconda/bioconda-recipes/tree/bump/pangolin/recipes/pangolin) (click to view/edit other files)
Releases |[https://github.com/cov-lineages/pangolin/tags](https://github.com/cov-lineages/pangolin/tags)
Author | `@cov-lineages`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Review by rpetit3 — CHANGES_REQUESTED** [review]
going to get these updated

**Comment by rpetit3** [comment]
Needs https://github.com/bioconda/bioconda-recipes/pull/30040 to be merged

**Comment by pvanheus** [comment]
> Needs #30040 to be merged

done but I'm also working on a PR here: https://github.com/bioconda/bioconda-recipes/pull/30050 - I added an extra test.

**Comment by rpetit3** [comment]
closing in favor of https://github.com/bioconda/bioconda-recipes/pull/30050

**Pull request closed without merging**
