### PR TITLE
Add perl-bio-bigfile

### PR DESCRIPTION
**Pull request by vladsaveliev**
[Bio::DB::BigFile](https://metacpan.org/pod/release/LDS/Bio-BigFile-1.07/lib/Bio/DB/BigFile.pm) provides a low-level interface to BigWig & BigBed files. 

Installation requires a compiled version of Jim Kent's source tree, including the main library, jkweb.a, so BigFile conda package should first properly compile that library, and then build perl modules making sure they link to compiled files.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by vladsaveliev** [comment]
Stumbling upon the problem that building requires source of kent library:

From https://metacpan.org/pod/release/LDS/Bio-BigFile-1.07/lib/Bio/DB/BigFile.pm :
> Installation requires a compiled version of Jim Kent's source tree, including the main library, jkweb.a. Please see the README in the Bio::DB::BigFile distribution directory for instructions.

In README:

```
Step 1) COMPILE JIM KENT SOURCE TREE

To compile this module, you must first download, unpack and compile
the Jim Kent source tree, located at
http://hgdownload.cse.ucsc.edu/admin/jksrc.zip. The commands needed to
get, unpack and compile the necessary file are:

 wget http://hgdownload.cse.ucsc.edu/admin/jksrc.zip
 unzip jksrc.zip
 cd kent/src/lib
 export    MACHTYPE=i686    # for a 64-bit system
 # export  MACHTYPE=i386    # for a 32-bit system
 make
 cd ..
 export KENT_SRC=`pwd`
```

Couldn't find the kent library on bioconda. Only found [some ucsc packages](https://github.com/bioconda/bioconda-recipes/search?utf8=%E2%9C%93&q=kent&type=) that also build kent source, however they seem to already include it in the source tarball, however this bioperl package doesn't come with kent and requires to wget it manually. Since I can't use `wget` in build.sh, I tried a conda-3 [trick to include multiple sources](https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#source-from-multiple-sources) in the recipe, however bioconda linter doesn't seem to like it (`The recipe meta.yaml contains a duplicate key`).

Help needed :)

**Comment by vladsaveliev** [comment]
Having a problem with gcc not seeing openssl library. Tried to add `export CPPFLAGS="-I$PREFIX/include"`, but no luck.

```
03:18:01 BIOCONDA INFO (OUT) hmac.c:11:10: fatal error: openssl/hmac.h: No such file or directory
03:18:01 BIOCONDA INFO (OUT)  #include "openssl/hmac.h"
```

**Comment by vladsaveliev** [comment]
All good with compiling of kent library. However getting an error when building the Perl module itself

```
 Building Bio-BigFile                                                                                                                                                                                                                     Parser.c: loadable library and perl binaries are mismatched (got handshake key 0xdb00080, needed 0xde00080)
```

Played with adding/removing perl to/from `build` and `host` sections locally, no luck. Though it might have to do with the discrepancy in `perl` executable and where `PERL5LIB` points, but it's not that.

**Comment by vladsaveliev** [comment]
Actually, not having that error locally, and it builds - however the quick test doesn't pass.

**Comment by vladsaveliev** [comment]
@bioconda/perl, would you be able to help with this package please?

**Comment by abretaud** [comment]
@vladsaveliev green now! :)

**Comment by dpryan79** [comment]
@bioconda-bot please fetch artifacts

**Comment by abretaud** [comment]
@bioconda-bot please fetch artifacts

**Comment by abretaud** [comment]
Is it normal that the bot ignores me? I didn't mean to be rude, I said "please"

**Comment by dpryan79** [comment]
Odd, not sure why that happened.

**Comment by dpryan79** [comment]
Ah, that was a github hiccup. Github never triggered the bot. Can you try asking for artifacts again?

**Comment by abretaud** [comment]
@bioconda-bot please fetch artifacts

**Comment by abretaud** [comment]
@bioconda-bot please merge

**Comment by vladsaveliev** [comment]
@abretaud, @dpryan79 - thanks you so much for making it work!

**Pull request merged**
