### PR TITLE
Newer Ansible with support for OpenStack clouds

### PR DESCRIPTION
**Pull request by brainstorm**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

This adds `shade`, a python library to manage OpenStack clouds that usually run in some academic HPC clusters, i.e:

http://nci.org.au/systems-services/cloud-computing/tenjin/

Shipping support for OpenStack in bioconda/ansible greatly eases automation on those platforms.

Superseeds PR #5293 from @souravsingh.

EDIT: I just saw that this is supposed to move to conda-forge over here, as pointed by @bgruening: https://github.com/conda-forge/staged-recipes/pull/3353/files

### CODE REVIEW

**Comment by brainstorm** [comment]
In order to avoid future confusion, ansible should be **removed** from bioconda and favor conda-forge, right?

**Comment by bgruening** [comment]
Yes please also see: https://github.com/bioconda/bioconda-recipes/pull/5293

**Comment by brainstorm** [comment]
@souravsingh Could you please incorporate my changes/dependencies to your PR over conda-forge? Don't want to step further in your good work ;)

**Comment by brainstorm** [comment]
Closing this in favour of conda-forge's https://github.com/conda-forge/staged-recipes/pull/3353. @bgruening, IMHO #5293 should be closed as well?

**Pull request closed without merging**
