### PR TITLE
pinning java as in #15407

### PR DESCRIPTION
**Pull request by aschuerch**
In addition to #15407, adding the java dependency is needed to firx the prokka recipe (see   #14975). Not sure if it is necessary to pin version. 

Please  `@bioconda/core` review my PR and add me to the bioconda project. 

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by bgruening** [comment]
ping @tseemann

**Comment by tseemann** [comment]
@aschuerch thanks for looking into this. Prokka itselfv doesn't depend on Java, but it uses `minced` which does. I think minced recently updated, and the author built the .jar file with a more modern version of Java, so old Java can't execute it.  This happened previously, and I asked them to rebuild the .jar with Java 1.8 for compatibility.

So I think this should be moved to `minced` recipe?
https://bioconda.github.io/recipes/minced/README.html

**Comment by aschuerch** [comment]
thank you @tseemann, I agree that the problem is minced not prokka itself. In the minced recipe, java is already a dependency, and the version was recently pinned (see  #15407 and  #14975) but this did not fix the problem, while adding java to a fresh prokka env does. If there is a better way, I'll be happy to learn about it.

**Comment by dpryan79** [comment]
@tseemann Is this maybe related to the JAVA_HOME issue in minced 0.4.0?

@aschuerch A new version of minced was just pushed out, can you see if that fixes things?

**Comment by aschuerch** [comment]
@dpryan79 @tseemann yes, the new version of minced does the trick! This pull request can be closed then.

**Comment by dpryan79** [comment]
Great, thanks @aschuerch!

**Comment by tseemann** [comment]
@aschuerch yes i think i've fixed minced, prokka, snippy, etc now so things should all work with Java now!

**Pull request closed without merging**
