### PR TITLE
Update kallisto to 0.50.0

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`kallisto`](https://bioconda.github.io/recipes/kallisto/README.html): **0.48.0** &rarr; **0.50.0**

[install with bioconda](http://bioconda.github.io/recipes/kallisto/README.html) [Conda](https://anaconda.org/bioconda/kallisto/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/kallisto`](https://github.com//bioconda/bioconda-recipes/tree/bump/kallisto/recipes/kallisto) (click to view/edit other files)
Summary | Quantifying abundances of transcripts from RNA-Seq data, or more generally of target sequences using high-throughput sequencing reads.
Home | [http://pachterlab.github.io/kallisto](http://pachterlab.github.io/kallisto)
Releases |[https://github.com/pachterlab/kallisto/tags](https://github.com/pachterlab/kallisto/tags)
Recipe Maintainer(s) | @mjsteinbaugh
Author | `@pachterlab`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by mjsteinbaugh** [comment]
This is currently a pre-release version, do not merge yet

**Comment by mjsteinbaugh** [comment]
We may need to adjust the build script for bifrost:
https://github.com/pachterlab/kallisto/issues/385

**Comment by mjsteinbaugh** [comment]
Now hitting this autoconf issue:

```
configure.ac: error: required file 'config.sub' not found
configure.ac: error: required file 'config.guess' not found
configure.ac: error: required file 'install-sh' not found
configure.ac:   try running autoreconf --install
```

**Comment by mjsteinbaugh** [comment]
Adding in support for bzip2 and xz compression

**Comment by mjsteinbaugh** [comment]
Another victim of https://github.com/bioconda/bioconda-recipes/issues/41526 on macOS

**Comment by cbrueffer** [comment]
Looks officially released to me, so surely OK to merge?

**Comment by mjsteinbaugh** [comment]
@cbrueffer Thanks you're right, the tag changed from prerelease to release. Safe to merge.

**Review by mjsteinbaugh — APPROVED** [review]

**Comment by cbrueffer** [comment]
Ah, now I understand the initial question! :-)

**Pull request merged**
