### PR TITLE
Updated minimap2 and mappy to v2.7

### PR DESCRIPTION
**Pull request by lh3**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by lh3** [comment]
Travis is complaining the following towards the end of the log file:
```txt
$ scripts/travis-run.sh
+bioconda-utils lint recipes config.yml --git-range master HEAD
18:56:45 BIOCONDA INFO Recipes newly unblacklisted:

18:56:45 BIOCONDA INFO Recipes to consider according to git: 
recipes/mappy
 recipes/minimap2
18:56:45 BIOCONDA INFO Recipes to lint:
recipes/minimap2
19:00:17 BIOCONDA ERROR STDOUT+STDERR:
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
mkdir: cannot create directory `/opt/host-conda-bld/noarch': Permission denied


19:00:50 BIOCONDA ERROR BUILD FAILED recipes/minimap2, CONDA_ALLOW_SOFTLINKS=false;CONDA_BOOST=1.64;CONDA_BZIP2=1.0;CONDA_GMP=5.1;CONDA_GSL=1.16;CONDA_HDF5=1.8.17;CONDA_HTSLIB=1.6;CONDA_NCURSES=5.9;CONDA_NPY=112;CONDA_PERL=5.22.0;CONDA_PY=27;CONDA_R=3.4.1;CONDA_ROOT=/anaconda;CONDA_XZ=5.2;CONDA_ZLIB=1.2.8;LANG=en_US.UTF-8;LC_ALL=en_US.UTF-8;LC_CTYPE=en_US.UTF-8;MACOSX_DEPLOYMENT_TARGET=10.9
19:00:52 BIOCONDA INFO BUILD START recipes/mappy, env: CONDA_ALLOW_SOFTLINKS=false;CONDA_BOOST=1.64;CONDA_BZIP2=1.0;CONDA_GMP=5.1;CONDA_GSL=1.16;CONDA_HDF5=1.8.17;CONDA_HTSLIB=1.6;CONDA_NCURSES=5.9;CONDA_NPY=112;CONDA_PERL=5.22.0;CONDA_PY=27;CONDA_R=3.4.1;CONDA_ROOT=/anaconda;CONDA_XZ=5.2;CONDA_ZLIB=1.2.8;LANG=en_US.UTF-8;LC_ALL=en_US.UTF-8;LC_CTYPE=en_US.UTF-8;MACOSX_DEPLOYMENT_TARGET=10.9
..19:02:19 BIOCONDA ERROR COMMAND FAILED: docker run --net host --rm -v /tmp/tmperyrqao8/build_script.bash:/opt/build_script.bash -v /anaconda/conda-bld:/opt/host-conda-bld -v /home/travis/build/bioconda/bioconda-recipes/recipes/mappy:/opt/recipe -e CONDA_PY=27 -e CONDA_NCURSES=5.9 -e CONDA_GSL=1.16 -e CONDA_NPY=112 -e LANG=en_US.UTF-8 -e LC_ALL=en_US.UTF-8 -e CONDA_GMP=5.1 -e CONDA_ROOT=/anaconda -e CONDA_ALLOW_SOFTLINKS=false -e CONDA_ZLIB=1.2.8 -e CONDA_R=3.4.1 -e CONDA_HTSLIB=1.6 -e CONDA_HDF5=1.8.17 -e CONDA_PERL=5.22.0 -e LC_CTYPE=en_US.UTF-8 -e CONDA_BZIP2=1.0 -e MACOSX_DEPLOYMENT_TARGET=10.9 -e CONDA_XZ=5.2 -e CONDA_BOOST=1.64 tmp-bioconda-builder /bin/bash /opt/build_script.bash
19:02:19 BIOCONDA ERROR STDOUT+STDERR:
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
mkdir: cannot create directory `/opt/host-conda-bld/noarch': Permission denied
```
Not sure if this is a travis/bioconda error or my error. Will restart the building some time later.

**Comment by daler** [comment]
@lh3 it's an unrelated problem (see https://github.com/bioconda/bioconda-utils/issues/246) and we're working on a fix. I'll restart the test for this when we have a solution.

**Comment by bgruening** [comment]
Restarted the runs.

**Comment by lh3** [comment]
Thanks! I appreciate.

**Pull request merged**
