### PR TITLE
Add Illumina's isaac4 aligner.

### PR DESCRIPTION
**Pull request by cbrueffer**
Add Illumina's isaac4 aligner.

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by cbrueffer** [comment]
@BiocondaBot update

**Comment by cbrueffer** [comment]
@bioconda-bot update

**Comment by mbargull** [comment]
It built locally (in our build container, ofc) for me with the latest Boost. Do you mind if I commit changes for that?
(Using the older Boost means creating maintenance burden in the future, so I'd like to avoid that ;).)

**Comment by cbrueffer** [comment]
Please go ahead! I think it I tested it with the latest boost (now perhaps one version back), but had problems with it.

**Comment by mbargull** [comment]
Essentially, I had the same patch as you, just with all `0`s replaced by `nullptr` :).
(The `CXXFLAGS` change is unrelated.)

**Comment by cbrueffer** [comment]
Cool, progress indeed! Unless anyone objects I'd skip macOS for now; I'm not interested in it and I doubt there's big demand for a macOS package of this software.

**Comment by mbargull** [comment]
```
05:59:00 BIOCONDA INFO (ERR) CMake Error at cmake/macros.cmake:91 (message):
05:59:00 BIOCONDA INFO (ERR)   Required header malloc.h not found.
05:59:00 BIOCONDA INFO (ERR) Call Stack (most recent call first):
05:59:00 BIOCONDA INFO (ERR)   cmake/cxxConfigure.cmake:50 (isaac_find_header_or_die)
05:59:00 BIOCONDA INFO (ERR)   c++/CMakeLists.txt:35 (include)
```
*Unless* subsequent errors pop up, then replacing `malloc.h` with `stdlib.h` could be all that's needed for OSX.
If someone wants to try that, be my guest. But skipping OSX is also fine by me.

**Comment by mbargull** [comment]
@BiocondaBot, please fetch artifacts

**Comment by mbargull** [comment]
Maybe we want to `strip` the bloated binary that is created:
```
$ curl -sL https://117260-42372094-gh.circle-artifacts.com/0/tmp/artifacts/packages/linux-64/isaac4-04.18.11.09-h07bff40_0.tar.bz2 | tar -tvf isaac4-04.18.11.09-h07bff40_0.tar.bz2 | sort -rnk3 | head
-rwxrwxr-x 0/0       166689432 2020-07-24 14:34 bin/isaac-align
-rwxrwxr-x 0/0        12980840 2020-07-24 14:34 bin/isaac-reorder-reference
-rwxrwxr-x 0/0        12032920 2020-07-24 14:34 libexec/Isaac-04.18.11.09/printContigs
-rwxrwxr-x 0/0        12001600 2020-07-24 14:34 libexec/Isaac-04.18.11.09/mergeReferences
-rw-rw-r-- 0/0          881230 2020-07-24 14:33 share/Isaac-04.18.11.09/data/examples/PhiX/Fastq/lane1_read1.fastq
-rw-rw-r-- 0/0          879252 2020-07-24 14:33 share/Isaac-04.18.11.09/data/examples/PhiX/Fastq/lane1_read2.fastq
-rw-rw-r-- 0/0           68700 2018-11-09 14:22 share/Isaac-04.18.11.09/Changes
-rw-rw-r-- 0/0           19119 2020-07-24 14:33 share/Isaac-04.18.11.09/xsl/alignment/TileMismatchPages.xsl
-rw-rw-r-- 0/0           13018 2020-07-24 14:33 share/Isaac-04.18.11.09/xsl/alignment/GenerateReport.xsl
-rw-rw-r-- 0/0           12483 2020-07-24 14:33 share/Isaac-04.18.11.09/xsl/alignment/PathUtils.xsl
```
\~160M seems a bit excessive for a single binary :O.
Or rather check if there's a `configure`/`make` flag to create a smaller release build?

**Comment by mbargull** [comment]
I changed the default `RelWithDebInfo` from https://github.com/Illumina/Isaac4/blob/Isaac-04.18.11.09/src/configure#L161 to `Release`.

**Comment by mbargull** [comment]
@BiocondaBot, please fetch artifacts

**Comment by mbargull** [comment]
Better :)
```
$ curl -sL https://117417-42372094-gh.circle-artifacts.com/0/tmp/artifacts/packages/linux-64/isaac4-04.18.11.09-h07bff40_0.tar.bz2 | tar -tvj | sort -rnk3 | head
-rwxrwxr-x 0/0         7881408 2020-07-25 11:51 bin/isaac-align
-rwxrwxr-x 0/0         1573472 2020-07-25 11:51 bin/isaac-reorder-reference
-rwxrwxr-x 0/0         1371392 2020-07-25 11:51 libexec/Isaac-04.18.11.09/mergeReferences
-rwxrwxr-x 0/0         1360008 2020-07-25 11:51 libexec/Isaac-04.18.11.09/printContigs
-rw-rw-r-- 0/0          881230 2020-07-25 11:51 share/Isaac-04.18.11.09/data/examples/PhiX/Fastq/lane1_read1.fastq
-rw-rw-r-- 0/0          879252 2020-07-25 11:51 share/Isaac-04.18.11.09/data/examples/PhiX/Fastq/lane1_read2.fastq
-rw-rw-r-- 0/0           68700 2018-11-09 14:22 share/Isaac-04.18.11.09/Changes
-rw-rw-r-- 0/0           19119 2020-07-25 11:51 share/Isaac-04.18.11.09/xsl/alignment/TileMismatchPages.xsl
-rw-rw-r-- 0/0           13018 2020-07-25 11:51 share/Isaac-04.18.11.09/xsl/alignment/GenerateReport.xsl
-rw-rw-r-- 0/0           12483 2020-07-25 11:51 share/Isaac-04.18.11.09/xsl/alignment/PathUtils.xsl
```

**Comment by mbargull** [comment]
I'm letting a job run at gh-23375 to see if a simple patch works with macOS.
If you are in a hurry, you can `@BiocondaBot, please merge` this PR. If not, I'll let the other PR run and see if it works.

**Comment by cbrueffer** [comment]
Good catch, thanks! Yes, building on macOS shouldn't be too hard, but it looks like not even upstream has given this a though, and there are no macOS-related PRs/issues there, probably not worth it for now.

**Comment by cbrueffer** [comment]
@bioconda-bot please merge

**Comment by cbrueffer** [comment]
Ah, overlapping message writing, sorry. Anyway, easy to merge in after this.

**Comment by mbargull** [comment]
> Ah, overlapping message writing, sorry. Anyway, easy to merge in after this.

All good :).

**Pull request merged**
