### PR TITLE
add glpk to osx whitelist

### PR DESCRIPTION
**Pull request by aebrahim**

### CODE REVIEW

**Comment by johanneskoester** [comment]
Why did you remove the gcc dependency?

**Comment by aebrahim** [comment]
Any compiler can be used. It doesn't have to be gcc.

Also libgcc is not a runtime requirement for packages (even when compiled
with gcc) so it is also removed.

**Comment by johanneskoester** [comment]
That's right, but we build with either the conda gcc or the conda llvm to ensure ABI compatibility. Hence, all recipes need to add the respective packages.

**Comment by johanneskoester** [comment]
Regarding libgcc I always thought that it depends on the actual code whether it is needed. If you are sure that this package won't need it, we can remove it.

**Comment by aebrahim** [comment]
I'm trying to update the recipe to use conda/conda-recipes#595 which will also run tests. I've changed the title to WIP in the meantime

**Comment by aebrahim** [comment]
For some reason, it wouldn't let me use python when testing on mac, so I disabled that test. This should all work now.

**Comment by johanneskoester** [comment]
So, there is a recipe in conda-recipes already? Then, what's the point of this one?

**Comment by aebrahim** [comment]
The recipes in conda-recipes are not built into installable packages.

**Comment by johanneskoester** [comment]
Ok, so this is about having an automatic build in bioconda.

**Comment by johanneskoester** [comment]
Still, gcc and libgcc are missing though.

**Comment by aebrahim** [comment]
Why would libgcc be required? AFAIK program doesn't link against libgcc
(libgcc != libc).

Also, it doesn't require gcc in particular to build, just any c compiler
(gcc, clang, or visual studio all work). Is there a metapackage to specify
requiring a c compiler in anaconda, or is one assumed to already have been
installed?

**Comment by aebrahim** [comment]
And yes, it is for automatic builds in bioconda, because other packages
depend on it.

**Comment by johanneskoester** [comment]
If no compiler is specified, I think it will use the old gcc from the Centos container. We decided at some point that it would be better to explicitly state the compiler in the recipe (@yesimon, I think this decision was based on one of your PRs?). I thought, libgcc is a runtime library of gcc which contains some low-level functions the compiler might delegate to. However I am not a C expert, and would greatly appreciate comments from @bioconda/all about this issue. There are examples for both explicitly stating and not stating gcc and libgcc in conda-recipes. I would always say that explicit is better than implicit.

**Comment by kyleabeauchamp** [comment]
So I don't know what the "right" answer is, but it looks like we're not the only ones adding gcc tags for some things built with GCC.  I imagine at some point we can get some 

https://github.com/conda/conda-recipes/search?p=4&q=gcc&utf8=✓

**Comment by aebrahim** [comment]
I believe that glibc is the runtime library you are referring to, not libgcc, and libgcc is explicitly not required.

For example, I just compiled gcc, and these are the libraries it links against are listed below:

```
$ ldd libglpk.so
        linux-vdso.so.1 =>  (0x00007ffea69a3000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f39dc7b8000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f39dc3f3000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f39dcdac000)
```

While I am certainly not an expert here, the problem with explicitly requiring gcc IMHO is that it doesn't make sense for other OS's, as Mac and Windows will not always use gcc. Instead, I think the default compiler should be used, because that will work on all 3 OS's.

I noticed a package specifying ```gcc [linux]``` which I guess could work. But what if someone wants to build all the packages with clang, like done here: http://clang.debian.net/? Because this package works with all 3 packages, I think it's best to explicitly require gcc only if the package will only build with gcc.

**Comment by yesimon** [comment]
I think the decision was to standardize on conda GCC 4.x if the package is a library. Obviously for non-library packages compiler choice doesn't really matter, but if somebody in the future adds a package that links to your library, it needs to have a compatible ABI as far down the stack as can go (including anaconda channel packages).

**Comment by aebrahim** [comment]
Is this also enforced for mac as well, or just for linux?

(As in should I make this ```gcc [linux]``` or ```gcc[unix]```)

**Comment by yesimon** [comment]
Regarding `libgcc`, it looks like it's still a mess on the condo side as well: conda/conda-recipes#558. Although it would probably make sense to pin on libgcc if we're pinning on gcc and the package relies on functions from it, it might be simpler now to not depend on it.

**Comment by yesimon** [comment]
I think the anaconda channel is using clang builds, so please do `gcc [linux]`! :+1:

**Comment by johanneskoester** [comment]
So the analog for mac would be ``llvm [osx]`` I guess, right?

**Comment by johanneskoester** [comment]
Apart from that, I was definitiely referring to libgcc (see [here](https://gcc.gnu.org/onlinedocs/gccint/Libgcc.html)). I guess in most cases it will be statically linked, so it won't be a runtime dependency. However, it is clearly possible that libgcc is needed (e.g. [here](http://meta-virtualization.yoctoproject.narkive.com/rkXmSYS5/patch-xen-add-libgcc-as-runtime-dependency-of-xen-xl-package). I guess we just have to inspect the Makefiles or the resulting binaries to see if it is statically linked or not.

**Comment by aebrahim** [comment]
I checked like this for glpk to determine it's not linked.
```
$ ldd libglpk.so
        linux-vdso.so.1 =>  (0x00007ffea69a3000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f39dc7b8000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f39dc3f3000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f39dcdac000)
```

Also, I have added ```gcc [linux]```

Thanks so much to both of you for patiently helping me with this :)

**Comment by johanneskoester** [comment]
Great! What about adding ``llvm [osx]``? If that works here, we should make it consistent in all recipes.

**Comment by johanneskoester** [comment]
Also, @druvus you often specify CC and CXX in build.sh in order to ensure that the anaconda gcc is used. Is this really needed, because gcc from anaconda should be always preferred because it comes first in the path definition. Otherwise, if there is a good reason to do this, we should follow this practice in every recipe as well.

**Comment by druvus** [comment]
You're right it might not be needed. I could go through and remove those lines from my added recipes to make it consistent for all recipes.

**Pull request closed without merging**
