### PR TITLE
Move MiModD package recipe to recipes folder

### PR DESCRIPTION
**Pull request by wm75**
* [x] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [x] This PR does something else (explain below).

fixes #2668 which added the recipe to the root folder by mistake

### CODE REVIEW

**Comment by wm75** [comment]
@johanneskoester ok, took me a few attempts to have zlib.h discovered at build time, but this seems to work now. You may want to investigate the test results though because two workers report bioconda_utils.utils:Nothing to be done and I don't know what the difference to the other two is.

**Comment by johanneskoester** [comment]
That's fine. We have 2 workers per architecture to speed up builds of multiple packages. In your case, those workers don't have anything to build.

**Comment by johanneskoester** [comment]
Thanks!

**Comment by wm75** [comment]
@johanneskoester I see. Thanks for the explanation and sorry again for the trouble with the original PR.

**Comment by johanneskoester** [comment]
No problem. You are not the first ;-). We should have automatic lints about that.

**Pull request merged**
