### PR TITLE
Update chewbbaca to 3.1.1

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`chewbbaca`](https://bioconda.github.io/recipes/chewbbaca/README.html): **3.1.0** &rarr; **3.1.1**

[install with bioconda](http://bioconda.github.io/recipes/chewbbaca/README.html) [Conda](https://anaconda.org/bioconda/chewbbaca/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/chewbbaca`](https://github.com//bioconda/bioconda-recipes/tree/bump/chewbbaca/recipes/chewbbaca) (click to view/edit other files)
Summary | A complete suite for gene-by-gene schema creation and strain identification.
Home | [https://github.com/B-UMMI/chewBBACA](https://github.com/B-UMMI/chewBBACA)
Releases |[https://pypi.org/pypi/chewBBACA/json](https://pypi.org/pypi/chewBBACA/json)
Recipe Maintainer(s) | @rfm-targa

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by rfm-targa** [comment]
@BiocondaBot please fetch artifacts

**Comment by rfm-targa** [comment]
@BiocondaBot please update

**Comment by rfm-targa** [comment]
@BiocondaBot please add label

**Review by cbrueffer — APPROVED** [review]

**Comment by cbrueffer** [comment]
@BiocondaBot please merge

**Pull request merged**
