### PR TITLE
Add legacy biopython version 1.67

### PR DESCRIPTION
**Pull request by mvdbeek**
* [x] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by peterjc** [comment]
It should be ``LICENSE`` (no extension) on the older versions of Biopython - but that metadata is not essential

**Comment by peterjc** [comment]
Yes, mmtf support was new in Biopython 1.68

**Comment by mvdbeek** [comment]
Thanks Peter, I've rebased this with the correct LICENSE file.

**Comment by peterjc** [comment]
Green light 👍

**Comment by bgruening** [comment]
Thanks all! Looks great!

**Pull request merged**
