### PR TITLE
Update gatk4 to 4.1.3.0

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`gatk4`](https://bioconda.github.io/recipes/gatk4/README.html): **4.1.2.0** &rarr; **4.1.3.0**

[install with bioconda](http://bioconda.github.io/recipes/gatk4/README.html) [Conda](https://anaconda.org/bioconda/gatk4/files)

Info | Link
-----|-----
Recipe | [`recipes/gatk4`](https://github.com//bioconda/bioconda-recipes/tree/bump/gatk4/recipes/gatk4) (click to view/edit other files)
Releases |[https://github.com/broadinstitute/gatk/releases](https://github.com/broadinstitute/gatk/releases)
Author | `@broadinstitute`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/updating.html)).

### CODE REVIEW

**Comment by micknudsen** [comment]
Duplicate of https://github.com/bioconda/bioconda-recipes/pull/16817 which is ready to review and merge.

**Comment by martin-raden** [comment]
@micknudsen please close if obsolete

I merged #16817 already ...

best,
Martin

**Comment by martin-raden** [comment]
will do myself.. :)

**Comment by micknudsen** [comment]
@martin-raden Thanks!

**Pull request closed without merging**
