### PR TITLE
Update - another attempt at SPAdes 3.15.5 osx build

### PR DESCRIPTION
**Pull request by chrisjackson-pellicle**
Yet another attempt to get osx builds working for SPAdes 3.15.5 (see [here](https://github.com/bioconda/bioconda-recipes/pull/37758))

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

### General instructions

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

### Instructions for avoiding API, ABI, and CLI breakage issues
Conda is able to record and lock (a.k.a. pin) dependency versions used at build time of other recipes.
This way, one can avoid that expectations of a downstream recipe with regards to API, ABI, or CLI are violated by later changes in the recipe.
If not already present in the meta.yaml, make sure to specify `run_exports` (see [here](https://bioconda.github.io/contributor/linting.html#missing-run-exports) for the rationale and comprehensive explanation).
Add a `run_exports` section like this:

```yaml
build:
  run_exports:
    - ...

```

with `...` being one of:

| Case                             | run_exports statement                                               |
| -------------------------------- | ------------------------------------------------------------------- |
| semantic versioning              | `{{ pin_subpackage("myrecipe", max_pin="x") }}`     |
| semantic versioning (0.x.x)      | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}`   |
| known breakage in minor versions | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| known breakage in patch versions | `{{ pin_subpackage("myrecipe", max_pin="x.x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| calendar versioning              | `{{ pin_subpackage("myrecipe", max_pin=None) }}`    |

while replacing `"myrecipe"` with either `name` if a `name|lower` variable is defined in your recipe or with the lowercase name of the package in quotes.

### Bot commands for PR management

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

Note that the <code>@BiocondaBot please merge</code> command is now depreciated. Please just squash and merge instead.

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by chrisjackson-pellicle** [comment]
Related: https://github.com/bioconda/bioconda-recipes/pull/47860#issuecomment-2132725128

**Comment by chrisjackson-pellicle** [comment]
test_osx fails. The raw log has the error:

```
CMake Error at /opt/mambaforge/envs/bioconda/conda-bld/spades_1716806771783/_build_env/share/cmake-3.29/Modules/CMakeTestCCompiler.cmake:67 (message):
The C compiler "/opt/mambaforge/envs/bioconda/conda-bld/spades_1716806771783/_build_env/bin/x86_64-apple-darwin13.4.0-clang" is not able to compile a simple test program. It fails with the following output:

...
...

ld: unsupported tapi file type '!tapi-tbd' in YAML file '/Applications/Xcode_14.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib/libSystem.tbd' for architecture x86_64
clang-9: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [CMakeFiles/cmTC_1e4f7.dir/build.make:100: cmTC_1e4f7] Error 1
```

This is beyond my knowledge level, but:

1) Attempts to build the OSX package on my local Mac using `conda build` (i.e. not using `bioconda-utils build`) resulted in a similar "unsupported tapi file type '!tapi-tbd' in YAML file" error.

2) Following the advice [here](https://github.com/ContinuumIO/anaconda-issues/issues/9096#issuecomment-378655517) and [here](https://github.com/ContinuumIO/anaconda-issues/issues/9096#issuecomment-466092775), I downloaded MacOSX10.10.sdk and set the `CONDA_BUILD_SYSROOT` environment variable to point towards it. Running `conda build` no longer resulted in the "unsupported tapi file type '!tapi-tbd' in YAML file" error; the build continued past this previous error point, although it still failed downstream with errors such as `error: no member named 'ldiv' in the global namespace`.

From the raw log, it looks like the Bioconda OSX build is using Xcode 14.2 with MacOSX13.1.sdk (`CONDA_BUILD_SYSROOT=/Applications/Xcode_14.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk` and `-isysroot /Applications/Xcode_14.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk`). 

I'm wondering if the Xcode / SDK version is the issue, or whether one of the issues outlined in the accepted answer [here](https://forums.developer.apple.com/forums/thread/720326) could be relevant. @bgruening, any thoughts?

**Comment by chrisjackson-pellicle** [comment]
...and, after all that, it seems to build fine after removing the conda_build_config.yaml with version constraints on the compilers.

**Comment by chrisjackson-pellicle** [comment]
@BiocondaBot please add label

**Review by martin-g — APPROVED** [review]

**Pull request merged**
