### PR TITLE
Intarna 2.2.1

### PR DESCRIPTION
**Pull request by martin-mann**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by martin-mann** [comment]
will only work after #10796

**Comment by s-will** [comment]
You could merge in #10796, though. Or wait.

**Comment by martin-mann** [comment]
mhh... might be an idea to save some time.. thanks

**Comment by martin-mann** [comment]
will wait ages for the macos test anyway.. ;)

**Comment by martin-mann** [comment]
while thinking about it.. not sure this will work, since the bump of vrna is a requirement (package to be installed) for this recipe... any experiences that way?

**Comment by s-will** [comment]
I would expect this to work (but I can not 100% guarantee). Anyway, rather wait until the viennarna bump passed the tests (just to avoid the mess)

**Comment by martin-mann** [comment]
dachtschmer.. :smile:

**Comment by bgruening** [comment]
Danke.

**Pull request merged**
