### PR TITLE
Update `ciriquant` patch file

### PR DESCRIPTION
**Pull request by BarryDigby**
`CIRIquant` biocontainer will fail during runtime due to the following error:

```console
Command error:
  Traceback (most recent call last):
    File "/usr/local/bin/CIRIquant", line 10, in <module>
      sys.exit(main())
    File "/usr/local/lib/python2.7/site-packages/CIRIquant/main.py", line 126, in main
      os.chmod(lib_path + '/CIRI2.pl', 0o755)
  OSError: [Errno 1] Operation not permitted: '/usr/local/lib/python2.7/site-packages/libs/CIRI2.pl'
```

The solution is to comment line 126 in `CIRIquant/main.py`:

```console
os.chmod(lib_path + '/CIRI2.pl', 0o755)
```
The patch file has been updated to include this fix. 

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by BarryDigby** [comment]
@BiocondaBot please add label

**Comment by pinin4fjords** [comment]
@BarryDigby have you made efforts to report the issue or submit a fix upstream per [the guidelines](https://bioconda.github.io/contributor/guidelines.html#patching)? Could you link to the issue/ PR?

**Comment by BarryDigby** [comment]
@pinin4fjords Ok I can open a PR against their code base, but this error is only observed when using containers. I have no idea when they will respond - they may never - is it okay to add this in the interim?

**Comment by pinin4fjords** [comment]
> @pinin4fjords Ok I can open a PR against their code base, but this error is only observed when using containers. I have no idea when they will respond - they may never - is it okay to add this in the interim?
> 
> edit - sorry I see that it is. That's a relief!

Yep, looks like they're responsive.

FWIW the reason for this is that every patch is a potential maintenance headache. I use them when e.g. upstream releases only happen every few months and I can't wait, but I feel bad every time I do ;-)

**Review by apeltzer — APPROVED** [review]
Looks fine & next release of ciriquant would be a while ahead, so lets get this in.

**Comment by apeltzer** [comment]
@bioconda-bot please merge

**Comment by apeltzer** [comment]
@BiocondaBot please merge

**Comment by BarryDigby** [comment]
@BiocondaBot please fetch artifacts

**Comment by BarryDigby** [comment]
@apeltzer not sure how to proceed here - all checks are passing but it's not finding the artifacts. Close and reopen a fresh PR?

**Comment by dpryan79** [comment]
@BiocondaBot please fetch artifacts

**Comment by dpryan79** [comment]
Just needed a build number bump. In this case the linter didn't catch this because a file was only being added and none modified (it's looking for modification of existing files, which is perhaps a bit of an oversight).

**Comment by BarryDigby** [comment]
@dpryan79 my bad 🤦🏻‍♂️. Thanks Devon

**Comment by dpryan79** [comment]
@BiocondaBot please merge

**Pull request merged**
