### PR TITLE
Update recognizer to 1.2.3

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`recognizer`](https://bioconda.github.io/recipes/recognizer/README.html): **1.2.2** &rarr; **1.2.3**

[install with bioconda](http://bioconda.github.io/recipes/recognizer/README.html) [Conda](https://anaconda.org/bioconda/recognizer/files)

Info | Link
-----|-----
Recipe | [`recipes/recognizer`](https://github.com//bioconda/bioconda-recipes/tree/bump/recognizer/recipes/recognizer) (click to view/edit other files)
Releases |[https://github.com/iquasere/reCOGnizer/tags](https://github.com/iquasere/reCOGnizer/tags)
Recipe Maintainer(s) | @iquasere
Author | @iquasere
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by standage** [comment]
While testing the package, I'm getting the following error when trying to install.

```
CondaVerificationError: The package for krona located at /Users/daniel.standage/anaconda3/pkgs/krona-2.7.1-pl526_2
appears to be corrupted. The path 'opt/krona/lib/._KronaTools.pm'
specified in the package manifest cannot be found.
```

**Comment by iquasere** [comment]
That is very strange, no alterations were made to Krona Tools handling from last version. KronaTools does have a strange implementation here, where after you install it with Conda you have to run their install script to use the tools with alias. Maybe that is what is causing the problem?

**Comment by iquasere** [comment]
How can I reproduce the error locally, so I can debug it?

**Comment by iquasere** [comment]
All I get from running
```
docker run --rm -t continuumio/miniconda3 sh -c "conda config --set unsatisfiable_hints True; conda install -v -c https://110864-423720
94-gh.circle-artifacts.com/0/tmp/artifacts/packages recognizer"
```
is that there is a conflicting package.
```
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Solving environment: ...working...
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/conda/cli/install.py", line 265, in install
    should_retry_solve=(_should_retry_unfrozen or repodata_fn != repodata_fns[-1]),
  File "/opt/conda/lib/python3.7/site-packages/conda/core/solve.py", line 117, in solve_for_transaction
    should_retry_solve)
  File "/opt/conda/lib/python3.7/site-packages/conda/core/solve.py", line 158, in solve_for_diff
    force_remove, should_retry_solve)
  File "/opt/conda/lib/python3.7/site-packages/conda/core/solve.py", line 281, in solve_final_state
    ssc = self._run_sat(ssc)
  File "/opt/conda/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
    return f(*args, **kwds)
  File "/opt/conda/lib/python3.7/site-packages/conda/core/solve.py", line 808, in _run_sat
    should_retry_solve=ssc.should_retry_solve
  File "/opt/conda/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
    return f(*args, **kwds)
  File "/opt/conda/lib/python3.7/site-packages/conda/resolve.py", line 1316, in solve
    raise UnsatisfiableError({})
conda.exceptions.UnsatisfiableError:
Did not find conflicting dependencies. If you would like to know which
packages conflict ensure that you have enabled unsatisfiable hints.

conda config --set unsatisfiable_hints True


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/conda/exceptions.py", line 1079, in __call__
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/conda/cli/main.py", line 84, in _main
    exit_code = do_call(args, p)
  File "/opt/conda/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 82, in do_call
    return getattr(module, func_name)(args, parser)
  File "/opt/conda/lib/python3.7/site-packages/conda/cli/main_install.py", line 20, in execute
    install(args, parser, 'install')
  File "/opt/conda/lib/python3.7/site-packages/conda/cli/install.py", line 308, in install
    raise e
  File "/opt/conda/lib/python3.7/site-packages/conda/cli/install.py", line 299, in install
    should_retry_solve=(repodata_fn != repodata_fns[-1]),
  File "/opt/conda/lib/python3.7/site-packages/conda/core/solve.py", line 117, in solve_for_transaction
    should_retry_solve)
  File "/opt/conda/lib/python3.7/site-packages/conda/core/solve.py", line 158, in solve_for_diff
    force_remove, should_retry_solve)
  File "/opt/conda/lib/python3.7/site-packages/conda/core/solve.py", line 275, in solve_final_state
    ssc = self._add_specs(ssc)
  File "/opt/conda/lib/python3.7/site-packages/conda/core/solve.py", line 694, in _add_specs
    ssc.r.find_conflicts(spec_set)
  File "/opt/conda/lib/python3.7/site-packages/conda/resolve.py", line 351, in find_conflicts
    raise UnsatisfiableError(bad_deps, strict=strict_channel_priority)
conda.exceptions.UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions
```
How can I see which packages and why are causing this conflict?

**Comment by dpryan79** [comment]
@iquasere you're missing all of the other channels, that command assumes the were setup already.

**Comment by iquasere** [comment]
So reCOGnizer has to be installed with ```conda install -c bioconda -c anaconda recognizer```?
Or is there anyway of specifying this in the YAML?

**Comment by dpryan79** [comment]
conda install -v -c https://110864-42372094-gh.circle-artifacts.com/0/tmp/artifacts/packages -c conda-forge -c bioconda recognizer

**Comment by dpryan79** [comment]
@BiocondaBot please merge

**Comment by iquasere** [comment]
Ok, so it has to be installed with ```-c conda-forge -c bioconda```. Will update instructions in the GitHub, thank you Devon!

**Pull request merged**
