### PR TITLE
Netcdf metadata info

### PR DESCRIPTION
**Pull request by Alanamosse**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

In France we say "Jamais deux sans trois"

The recipe for netcdf-metadata-info is designed to extract and summarize metadata informations about a netcdf file. This tool is for Galaxy use.
Source code : https://github.com/Alanamosse/Netcdf-Metadata-Info/
Galaxy tool preliminary version : https://github.com/65MO/Galaxy-E/tree/master/tools/read_netcdf

### CODE REVIEW

**Comment by mbargull** [comment]
Great, now the last thing is that we need to transfer @bgruening's commit, e.g., with
```bash
git pull git@github.com:Alanamosse/bioconda-recipes.git netcdf-metadata-info
git push
```

**Comment by Alanamosse** [comment]
Thank you @mbargull  to be such helpful and patient.
Shall I "Squash and merge" ? :)

**Comment by mbargull** [comment]
All tests passed! It doesn't really matter who pushes "Squash and merge", but since there were a couple of new things you learned, I'll give you the honor 😉. (And be sure to hit the "Delete branch" button that pops up afterwards -- that way we cleanup and don't have the merged branched lingering around.)

**Comment by Alanamosse** [comment]
Great ! Thank again for the support, hope I didn't waste too much of your time !  :D

**Comment by mbargull** [comment]
Happy to help!

**Pull request merged**
