### PR TITLE
pinn macsyfinder version in defense-finder

### PR DESCRIPTION
**Pull request by rpetit3**
```
    File "/usr/local/lib/python3.10/site-packages/macsypy/scripts/macsyfinder.py", line 1193, in main
      all_systems, rejected_candidates = search_systems(config, model_registry, models_def_to_detect, logger)
    File "/usr/local/lib/python3.10/site-packages/macsypy/scripts/macsyfinder.py", line 529, in search_systems
      parser.parse(models_def_to_detect)
    File "/usr/local/lib/python3.10/site-packages/macsypy/definition_parser.py", line 85, in parse
      self._fill_gene_bank(model_node, model_location, def_loc)
    File "/usr/local/lib/python3.10/site-packages/macsypy/definition_parser.py", line 287, in _fill_gene_bank
      self.gene_bank.add_new_gene(model_location, gene_name, self.profile_factory)
    File "/usr/local/lib/python3.10/site-packages/macsypy/gene.py", line 102, in add_new_gene
      gene = CoreGene(model_location, name, profile_factory)
    File "/usr/local/lib/python3.10/site-packages/macsypy/gene.py", line 114, in __init__
      self._profile = profile_factory.get_profile(self, model_location)
    File "/usr/local/lib/python3.10/site-packages/macsypy/profile.py", line 72, in get_profile
      raise MacsypyError(f"'{model_location.name}/{gene.name}': No such profile")
  macsypy.error.MacsypyError: 'defense-finder-models/Rst_Hydrolase-Tm__Hydrolase-Tm': No such profile
```

Based on the release notes the solution is to pin mascyfinder to a previous version without this issue

Release notes: https://github.com/mdmparis/defense-finder/releases/tag/v1.2.2

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

### General instructions

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

### Instructions for avoiding API, ABI, and CLI breakage issues
Conda is able to record and lock (a.k.a. pin) dependency versions used at build time of other recipes.
This way, one can avoid that expectations of a downstream recipe with regards to API, ABI, or CLI are violated by later changes in the recipe.
If not already present in the meta.yaml, make sure to specify `run_exports` (see [here](https://bioconda.github.io/contributor/linting.html#missing-run-exports) for the rationale and comprehensive explanation).
Add a `run_exports` section like this:

```yaml
build:
  run_exports:
    - ...

```

with `...` being one of:

| Case                             | run_exports statement                                               |
| -------------------------------- | ------------------------------------------------------------------- |
| semantic versioning              | `{{ pin_subpackage("myrecipe", max_pin="x") }}`     |
| semantic versioning (0.x.x)      | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}`   |
| known breakage in minor versions | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| known breakage in patch versions | `{{ pin_subpackage("myrecipe", max_pin="x.x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| calendar versioning              | `{{ pin_subpackage("myrecipe", max_pin=None) }}`    |

while replacing `"myrecipe"` with either `name` if a `name|lower` variable is defined in your recipe or with the lowercase name of the package in quotes.

### Bot commands for PR management

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

Note that the <code>@BiocondaBot please merge</code> command is now depreciated. Please just squash and merge instead.

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by rpetit3** [comment]
@BiocondaBot please fetch artifacts

**Comment by rpetit3** [comment]
Tested on Docker, seems to be working

```
 2024-03-27 20:00:36 | INFO     | Received file SRR2838702.fna.gz
 2024-03-27 20:00:36 | INFO     | SRR2838702.fna.gz is a nucleotide fasta file. Prodigal will annotate the CDS
 2024-03-27 20:00:36 | INFO     | Prodigal annotated 80 replicons
 2024-03-27 20:00:36 | INFO     | Protein files written in /home/robert_petit/temp/bactopia/work/b6/e3f39821c95c23dc7f3061e12c3de9/results/SRR2838702.fna.prt
 2024-03-27 20:00:36 | INFO     | 154 CDS were annotated
 2024-03-27 20:00:36 | INFO     | Running DefenseFinder
```

Output files

```
-rw-r--r-- 1 robert_petit robert_petit  57K Mar 27 20:00 SRR2838702.fna.prt
-rw-r--r-- 1 robert_petit robert_petit 4.4K Mar 27 20:00 SRR2838702.fna.prt.idx
-rw-r--r-- 1 robert_petit robert_petit  238 Mar 27 20:00 SRR2838702.fna_defense_finder_genes.tsv
-rw-r--r-- 1 robert_petit robert_petit  227 Mar 27 20:00 SRR2838702.fna_defense_finder_hmmer.tsv
-rw-r--r-- 1 robert_petit robert_petit   89 Mar 27 20:00 SRR2838702.fna_defense_finder_systems.tsv
```

```
cat SRR2838702.fna_defense_finder_hmmer.tsv
hit_id  replicon        hit_pos hit_sequence_length     gene_name       i_eval  hit_score       hit_profile_cov hit_seq_cov     hit_begin_match hit_end_match
SRR2838702_00033_1      SRR2838702_00033        102     544     Gao_Iet__IetA   1.800e-31       102.700 0.548   0.403   170     388
```

**Comment by rpetit3** [comment]
@BiocondaBot please add label

**Comment by lskatz** [comment]
@BiocondaBot please fetch artifacts

**Review by lskatz — APPROVED** [review]
It installs and the test passes on Azure!

**Pull request merged**
