### PR TITLE
Add goldrush

### PR DESCRIPTION
**Pull request by lcoombe**
Add GoldRush long read genome assembler
----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by rpetit3** [comment]
@lcoombe  I wonder if using `/usr/bin/env make` would help you.

Something like:

```
sed -i '' 's=/usr/bin/make=/usr/bin/env make=' goldrush
```

**Comment by lcoombe** [comment]
Thanks @rpetit3 ! I think you were totally right that the issue was that shebang line. We'll definitely fix that in the next release

**Comment by rpetit3** [comment]
Progress! New error
```
04:14:32 BIOCONDA INFO (OUT) + goldrush-path --help
04:14:32 BIOCONDA INFO (OUT) goldrush-path: error while loading shared libraries: libtcmalloc.so.4: cannot open shared object file: No such file or directory
```

Ring any bells for you @lcoombe ?

**Comment by jowong4** [comment]
Hi @rpetit3  I am one of the devs of GoldRush. From what I can tell ```04:12:30 BIOCONDA INFO (OUT) Library tcmalloc found: YES``` , the library should have been installed.  We have, however, in the past needed to deactivate and reactivate the conda environment that we installed GoldRush dependencies to fully set up the CXX env variables so maybe we need to do something like that here too.

**Comment by lcoombe** [comment]
@rpetit3 - Thanks for your help with figuring this out!

@jowong4 - Do you think any of the dependencies that we have in `host` should also be in `run` as runtime dependencies? The library was present during compilation fine (no errors on that stage), but for whatever reason we're only seeing this when we're testing the compiled code

**Comment by lcoombe** [comment]
@BiocondaBot please add label

**Comment by rpetit3** [comment]
@BiocondaBot please fetch artifacts

**Comment by rpetit3** [comment]
@lcoombe  or @jowong4  if you have time, mind testing locally before merging?

**Comment by lcoombe** [comment]
@BiocondaBot please fetch artifacts

**Comment by lcoombe** [comment]
@BiocondaBot please fetch artifacts

**Comment by lcoombe** [comment]
@rpetit3 - I tested the formula on linux and it's working as expected!

**Review by rpetit3 — APPROVED** [review]

**Comment by rpetit3** [comment]
@BiocondaBot please merge

**Comment by rpetit3** [comment]
@lcoombe glad we got it in! Thank you for all your effort!

Now whenever you submit a new release, @BiocondaBot will automatically create a pull request. A docker container will be available shortly on quay, and Singularity image from the galaxy project in a day or two 

Thanks again for adding Goldrush to bioconda!

**Pull request merged**
