### PR TITLE
bump lumpy to latest git version and expose cnv-to-bedpe script.

### PR DESCRIPTION
**Pull request by brentp**
* [X] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [X] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by kyleabeauchamp** [comment]
Does this mean you are endorsing the current `git` as something like a "release"?

**Comment by brentp** [comment]
no, this isn't yet an official release. but it contains changes to helper scripts.

do you have a suggestion?

**Comment by kyleabeauchamp** [comment]
I forget: will `conda install` prefer the `-git` version over the previous 2.12?  I'm just curious what this means in terms of versioning.

**Comment by brentp** [comment]
I'm not sure.

**Comment by chapmanb** [comment]
Brent -- thanks for tackling this. If this only contains changes to helper scripts I'd bump the build number from 1 to 2 instead of adding in the extra `git` string. I also don't know what that does but doesn't seem necessary since we were already using a git hash tied to the version.

**Comment by brentp** [comment]
ok. I removed the git string and bumped the version.

**Pull request merged**
