### PR TITLE
Feature/perl file temp

### PR DESCRIPTION
**Pull request by jerowe**
* [ ] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

More low level perl recipes.

### CODE REVIEW

**Comment by jerowe** [comment]
Travis is erroring:

```
Traceback (most recent call last):
  File "/home/travis/build/bioconda/bioconda-recipes/scripts/../simulate-travis.py", line 115, in <module>
    ], check=True)
  File "/anaconda/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['conda', 'install', '-y', '--file', 'https://raw.githubusercontent.com/bioconda/bioconda-utils/master/bioconda_utils/bioconda_utils-requirements.txt']' returned non-zero exit status 1
```

**Comment by jerowe** [comment]
ping @bioconda/core 

First of all, I'm loving the new and improved build system. I think that there is no user, and so any package managers that stick things in ~/ are going to fail. I was able to check it on a local image, and doing `echo $USER` gets me nothing.

```
+ source /anaconda/bin/activate /anaconda/conda-bld/7.24_1495778780092/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold
+ cpanm --installdeps .
Can't write to cpanm home 'UNKNOWN/.cpanm': You should fix it with chown/chmod first.
```

**Comment by daler** [comment]
Hmm. Does it work if you fake it in the build script? E.g.

```bash
export USER=test
mkdir -p /home/$USER
```

or even

```bash
HOME=/tmp cpanminus --installdeps .
```

**Comment by jerowe** [comment]
I think that will probably work. I just wanted to flag it since this didn't happen previously, and its actually only happening on the OSX builds anyways.

**Pull request merged**
