### PR TITLE
Update secapr to 1.1.4.

### PR DESCRIPTION
**Pull request by cbrueffer**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

Cleaned up version of the pull request in #7364 to ensure it gets in quickly while not reverting the recipe to a messy state.

### CODE REVIEW

**Comment by tobiashofmann88** [comment]
thanks a lot for taking care of this!!! I'm sorry I didn't have time to check on this this weekend. Is there anything left for me to do?

**Comment by tobiashofmann88** [comment]
except the conda install does not work anymore for secapr, it now says the following:

UnsatisfiableError: The following specifications were found to be in conflict:
  - click
  - secapr

the pipeline is wroteen in python2.7, how can I specify that in the yaml file?

**Comment by cbrueffer** [comment]
Installing secapr in a fresh environment works without problem here: ```conda create -n test secapr```

The issue your seeing seems to be an interaction with your already installed packages. Normally conda should figure out which packages to up/downgrade to satisfy those dependencies, but I've seen a few cases where that hasn't worked reliably in the last few months...

**Comment by tobiashofmann88** [comment]
Thanks, you are right, that command works fine.

I had been using the `conda install secapr` command, which returns those errors. I’m still not 100% sure what that command does (it seems that it tries to instlal secapr within my standard environment, correct?)

Thank you for all your help with this, you have been very helpful.
Best,
Tobi

**Pull request merged**
