### PR TITLE
r-monocle3

### PR DESCRIPTION
**Pull request by mjsteinbaugh**
Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it. Note that if you are not already a member of the bioconda project (meaning that you can't add this label), please ping `@bioconda/core` so that your PR can be reviewed and merged (please note if you'd like to be added to the bioconda project). Please see https://github.com/bioconda/bioconda-recipes/issues/15332 for more details.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

https://cole-trapnell-lab.github.io/monocle3/

monocle3 is currently difficult to compile on many Linux distros, so having this recipe up on bioconda will be useful for single-cell RNA-seq analysis.

### CODE REVIEW

**Comment by mjsteinbaugh** [comment]
monocle3 is a complete rewrite of monocole (v2; the version on Bioconductor). The Trapnell lab is releasing it with a new name to denote the change, and it's currently only available from GitHub.

**Comment by dpryan79** [comment]
@mjsteinbaugh OK, I thought they were going to replace the current bioconductor package with it, but given the difficulty everyone has in installing that perhaps that won't happen. I'm a strong :+1: on packaging this then!

**Comment by dpryan79** [comment]
@bioconda-bot merge

**Comment by mjsteinbaugh** [comment]
Perfect thanks @dpryan79! When monocle3 gets released on Bioconductor, we can change this recipe, but it will be helpful in the meantime to have it up on bioconda.

**Pull request merged**
