### PR TITLE
Add pegs 0.6.1

### PR DESCRIPTION
**Pull request by pjbriggs**
This PR adds pegs, a bioinformatics utility for calculating enrichments of gene cluster enrichments from peak data at different genomic distances.

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by pjbriggs** [comment]
Hello @bioconda/core checks don't seem to have been run after nearly a week on this recipe, but I'm not sure what the issue is. Any suggestions about what might be wrong here? Thanks!

**Comment by dpryan79** [comment]
@pjbriggs Can you disable circleci on your fork? That's normally the cause of this.

**Comment by dpryan79** [comment]
Yeah, seems to be the "circleci is enabled on a fork" issue. I wonder if we can have the bot warn about that.

**Comment by pjbriggs** [comment]
Hello @dpryan79 thanks for taking a look. The only information I could find about disabling circlci on my fork was under https://bioconda.github.io/contributor/faqs.html#circleci-macos-plans

I managed to locate the "Stop building" button and also unfollowed `pjbriggs / bioconda-recipes` under "Project settings" for the fork but it's not clear to me whether this has been sufficient to disable circleci.

Do I need to push another commit to try and trigger the checks here? Thanks!

**Comment by pjbriggs** [comment]
Thanks @dpryan79!

**Review by dpryan79 — APPROVED** [review]

**Comment by pjbriggs** [comment]
@BiocondaBot please merge

**Pull request merged**
