### PR TITLE
Update r-dimsum to 1.2.9

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`r-dimsum`](https://bioconda.github.io/recipes/r-dimsum/README.html): **1.2.8** &rarr; **1.2.9**

[install with bioconda](http://bioconda.github.io/recipes/r-dimsum/README.html) [Conda](https://anaconda.org/bioconda/r-dimsum/files)

Info | Link
-----|-----
Recipe | [`recipes/r-dimsum`](https://github.com//bioconda/bioconda-recipes/tree/bump/r_dimsum/recipes/r-dimsum) (click to view/edit other files)
Releases |[https://github.com/lehner-lab/DiMSum/tags](https://github.com/lehner-lab/DiMSum/tags)
Recipe Maintainer(s) | @andrefaure
Author | `@lehner-lab`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by andrefaure** [comment]
Please update the cutadapt requirement to version 2.4:
- cutadapt =2.4

Please also include the following packages requirements:
- pandoc >=1.17.2
- fastqc >=0.11.3
- starcode >=1.3

**Comment by andrefaure** [comment]
@BiocondaBot please add label

**Comment by andrefaure** [comment]
Before merging please see comment above about requested updates to the meta.yaml file…

**Comment by rpetit3** [comment]
hi @andrefaure I updated the dependencies, if you have a moment please take a look

**Review by dpryan79 — APPROVED** [review]

**Comment by andrefaure** [comment]
> hi @andrefaure I updated the dependencies, if you have a moment please take a look

Yes looks good thanks!

**Pull request merged**
