### PR TITLE
Update arriba to 1.2.0

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`arriba`](https://bioconda.github.io/recipes/arriba/README.html): **1.1.0** &rarr; **1.2.0**

[install with bioconda](http://bioconda.github.io/recipes/arriba/README.html) [Conda](https://anaconda.org/bioconda/arriba/files)

Info | Link
-----|-----
Recipe | [`recipes/arriba`](https://github.com//bioconda/bioconda-recipes/tree/bump/arriba/recipes/arriba) (click to view/edit other files)
Releases |[https://github.com/suhrig/arriba/releases](https://github.com/suhrig/arriba/releases)
Author | @suhrig
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Comment by dpryan79** [comment]
Well that was unfortunate timing.

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Comment by suhrig** [comment]
Thanks a lot for your help, Devon!

**Pull request merged**
