### PR TITLE
pypgatk version 0.0.22

### PR DESCRIPTION
**Pull request by ypriverol**
Describe your pull request here

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by ypriverol** [comment]
@bgruening probably you can help me with this and it can help others. In this package we add the configuration files to the package using: 

https://github.com/bigbio/py-pgatk/blob/6ce6e05b7dd1eeec09d19b079ea1e92d6a2a9fb1/setup.py#L42

```python
package_data={'pypgatk': ['config/*.yaml', 'config/*.json']}, zip_safe=False)
```

When I install the package using `pip` all configuration files are there and can be loaded using the following code:

https://github.com/bigbio/py-pgatk/blob/6ce6e05b7dd1eeec09d19b079ea1e92d6a2a9fb1/pypgatk/commands/ensembl_downloader.py#L10

```python
try:
  default_config_text = pkgutil.get_data(__name__, "../config/ensembl_downloader_config.yaml").decode()
```

However, tests are failing in bioconda build because the configuration files can't be found. Any suggestions!!!!

**Comment by mfansler** [comment]
The files aren't in [the PyPI tarball](https://files.pythonhosted.org/packages/6b/cc/cbd3dfce54b37ad54f97629e9d42cd6e60e370265b3b45d654b024e1ff6d/pypgatk-0.0.21.tar.gz).

**Comment by nfahlgren** [comment]
Adding them to a MANIFEST.in file will include them in the source: https://packaging.python.org/en/latest/guides/using-manifest-in/

**Comment by innovate-invent** [comment]
@ypriverol Please don't tag bioconda/all, there are over 600 members of that list and it creates unnecessary spam.

**Comment by ypriverol** [comment]
Sorry 🙏🏿.

**Comment by martin-raden** [comment]
I edited your initial post to decouple your PR from the bioconda/all mailing list...

**Comment by bgruening** [comment]
@bioconda-bot please merge

**Pull request merged**
