### PR TITLE
Updated ToulligQc to v2.5.4

### PR DESCRIPTION
**Pull request by Salome-Brunon**
There is a v2.6 but due to some package dependencies (pod5), conda build fails.
We have published a new pypi package for v2.5.4 but there was no update to v2.5.4 in bioconda.

### CODE REVIEW

**Comment by Salome-Brunon** [comment]
@BiocondaBot please fetch artifacts

**Comment by Salome-Brunon** [comment]
@BiocondaBot please add label

**Comment by Salome-Brunon** [comment]
Hi, could I get a quick review on this? @bioconda/core
Thank you!

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
Thanks @Salome-Brunon

**Pull request merged**
