### PR TITLE
add some util scripts to bin dir

### PR DESCRIPTION
**Pull request by abretaud**
For a galaxy tool ([602](https://github.com/galaxyproject/tools-iuc/pull/602)), we need some trinity util scripts to be available in the PATH.
Here is a patch to allow this.

I'm not sure this is the best way to do it: I didn't find any way to add other directories than $PREFIX/bin to the PATH, so I made some symlinks in $PREFIX/bin pointing to these scripts.

The problem is that those scripts are looking for other files with relative path => they fail when launched using a symlink.

So I was forced to make a find/sed to fix those scripts and allow to be launched from a symlink.
If it's the only way to do it, I will make a PR upstream (to Trinity) to make this find/sed stuff useless in future Trinity versions

### CODE REVIEW

**Comment by bgruening** [comment]
@abretaud can you please increase the `number: 3`.

**Comment by bgruening** [comment]
@abretaud this fails on OS-X because of your sed command if I'm not misleading. Can you try something like `sed -i.bak ...`. Afaik `sed -i` on OS-X interprets the next thing after the `-i` as file extension for the backup.

**Comment by johanneskoester** [comment]
I would say this is a valid approach. And yes, fixing upstream would be most welcome!

**Comment by bgruening** [comment]
And again: `LC_ALL=C sed -i.bak ...`. Sorry, I do not have OS-X here to test.

**Comment by abretaud** [comment]
As I said in IUC, this has already been [fixed upstream](https://github.com/abretaud/trinityrnaseq/commit/f29615b4b4db30fa8fb7fc6ee1e21e12d7e86a90)

**Comment by abretaud** [comment]
Tests pass on mac osx now \o/

**Comment by bgruening** [comment]
Awesome! Thanks a lot!

**Comment by abretaud** [comment]
Just to know, is it automatically deployed to bioconda channel or not?

**Comment by johanneskoester** [comment]
Yes it is. The travis build on master uploads the packages after successful execution.

**Pull request merged**
