### PR TITLE
Fix deprecated Perl syntax in ESTScan and fix dependencies and tests

### PR DESCRIPTION
**Pull request by gregvonkuster**
* [x] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by bgruening** [comment]
Can you please add 'perl' as dependency as well?

**Comment by gregvonkuster** [comment]
Sure, but I thought since the perl-btlib dependency requires perl that it would be "passed through" to this recipe.  Is this not correct?

**Comment by bgruening** [comment]
This is true, but we might build packages for multiple perl versions in the future.

**Comment by gregvonkuster** [comment]
Thanks @bgruening ;)

**Pull request merged**
