### PR TITLE
Update ncbimeta to 0.7.0

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`ncbimeta`](https://bioconda.github.io/recipes/ncbimeta/README.html): **0.6.6** &rarr; **0.7.0**

[install with bioconda](http://bioconda.github.io/recipes/ncbimeta/README.html) [Conda](https://anaconda.org/bioconda/ncbimeta/files)

Info | Link
-----|-----
Recipe | [`recipes/ncbimeta`](https://github.com//bioconda/bioconda-recipes/tree/bump/ncbimeta/recipes/ncbimeta) (click to view/edit other files)
Releases |[https://github.com/ktmeaton/NCBImeta/tags](https://github.com/ktmeaton/NCBImeta/tags)
Author | `@ktmeaton`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by ktmeaton** [comment]
@BiocondaBot please add label

**Comment by ktmeaton** [comment]
Uh oh, hold on, I noticed an error in the CircleCI build log. I updated dependencies in my repository, but not in the bioconda recipe. I will need to investigate that first...

**Comment by cbrueffer** [comment]
Oops, missed the comments here; I won't make any more changes for now.

**Comment by ktmeaton** [comment]
@cbrueffer Thank you for updating the recipe! That was indeed the exact change I wanted to fix to restrict the biopython dependency. I'm still learning the conda/autobump contribution workflow, thanks for showing me how it's done with the 'bump' branches.

It is ready for review now!

**Review by cbrueffer — APPROVED** [review]

**Comment by cbrueffer** [comment]
@bioconda-bot please merge

**Comment by cbrueffer** [comment]
Excellent, thanks for confirming @ktmeaton !

**Pull request merged**
