### PR TITLE
Update dimet to 0.1.4

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`dimet`](https://bioconda.github.io/recipes/dimet/README.html): **0.1.3** &rarr; **0.1.4**

[install with bioconda](http://bioconda.github.io/recipes/dimet/README.html) [Conda](https://anaconda.org/bioconda/dimet/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/dimet`](https://github.com//bioconda/bioconda-recipes/tree/bump/dimet/recipes/dimet) (click to view/edit other files)
Summary | A tool for Differential Isotope-labeled targeted Metabolomics
Home | [https://github.com/cbib/DIMet.git](https://github.com/cbib/DIMet.git)
Releases |[https://pypi.org/pypi/dimet/json](https://pypi.org/pypi/dimet/json)
Recipe Maintainer(s) | @hechth, @bdartigues

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Review by johaGL — APPROVED** [review]

**Comment by johaGL** [comment]
Help needed (@hechth, who should I to address to?)  :  error in test_linux -> azure-pipelines -> https://dev.azure.com/bioconda/bioconda-recipes/_build/results?buildId=43129&view=logs&j=e14e69ff-a0ae-55c4-b71d-229b239cfb2f&t=4dddc55b-10bc-50fc-ac68-7ff899b7a030 . Build failed. Here the last lines:     
```
  File "/opt/conda/conda-bld/dimet_1696606191031/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.12/site-packages/poetry/core/masonry/__init__.py", line 10, in <module>
    from .builder import Builder
  File "/opt/conda/conda-bld/dimet_1696606191031/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.12/site-packages/poetry/core/masonry/builder.py", line 5, in <module>
    from poetry.core.utils._compat import Path
  File "/opt/conda/conda-bld/dimet_1696606191031/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.12/site-packages/poetry/core/utils/_compat.py", line 8, in <module>
    import six.moves.urllib.parse as urllib_parse
ModuleNotFoundError: No module named 'six.moves'

Removed file://$SRC_DIR from build tracker '/tmp/pip-build-tracker-djq1vx7i'
Removed build tracker: '/tmp/pip-build-tracker-djq1vx7i'
Traceback (most recent call last):
  File "/opt/conda/bin/conda-mambabuild", line 10, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.8/site-packages/boa/cli/mambabuild.py", line 256, in main
    call_conda_build(action, config)
  File "/opt/conda/lib/python3.8/site-packages/boa/cli/mambabuild.py", line 228, in call_conda_build
    result = api.build(
  File "/opt/conda/lib/python3.8/site-packages/conda_build/api.py", line 180, in build
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/opt/conda/conda-bld/dimet_1696606191031/work/conda_build.sh']' returned non-zero exit status 2.

15:33:53 BIOCONDA ERROR BUILD FAILED recipes/dimet
 
```

**Comment by bgruening** [comment]
Are you still using the six pyhton module? If so you need to add it as dependency under run. But it should not be needed anymore.

**Comment by johaGL** [comment]
> Are you still using the six pyhton module? If so you need to add it as dependency under run. But it should not be needed anymore.

Dear Bjorn, no we are not using that library. I am surprised it is asking for it, the build

**Comment by johaGL** [comment]
dear @bgruening thank you, the add of `six` has solved the problem of build_test, thank you very much for your guidance.   I have created the PR  from my fork to the`bump/dimet` branch (see:  https://github.com/bioconda/bioconda-recipes/pull/43546 ). Once the merge done, this PR #43526 should work :)

**Comment by bdartigues** [comment]
dear @bgruening, even after adding six, the problem is the same. Perhaps this is due to the version of python 3.12 which is very recent, I suspect a bug in this version, perhaps change in the meta.yaml file python >=3.9,<4.0 with python >=3.9,<3.12

**Comment by bdartigues** [comment]
six is installed as a secondary dependency I think so @johaGL  no need to add it under run but the conflict probably comes as I said above from the version of python installed for dimet under run

**Comment by johaGL** [comment]
dear @bdartigues , thank you for instructions, I have changed as you said the python >=3.9,<3.12 the new PR https://github.com/bioconda/bioconda-recipes/pull/43549  I think this autobump wont work, so the new PR is  fork --> master

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
That one looks better to me.

**Pull request merged**
