### PR TITLE
Add quota_anchor recipe

### PR DESCRIPTION
**Pull request by xiaodli**
Describe your pull request here

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

### General instructions

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

### Instructions for avoiding API, ABI, and CLI breakage issues
Conda is able to record and lock (a.k.a. pin) dependency versions used at build time of other recipes.
This way, one can avoid that expectations of a downstream recipe with regards to API, ABI, or CLI are violated by later changes in the recipe.
If not already present in the meta.yaml, make sure to specify `run_exports` (see [here](https://bioconda.github.io/contributor/linting.html#missing-run-exports) for the rationale and comprehensive explanation).
Add a `run_exports` section like this:

```yaml
build:
  run_exports:
    - ...

```

with `...` being one of:

| Case                             | run_exports statement                                               |
| -------------------------------- | ------------------------------------------------------------------- |
| semantic versioning              | `{{ pin_subpackage("myrecipe", max_pin="x") }}`     |
| semantic versioning (0.x.x)      | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}`   |
| known breakage in minor versions | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| known breakage in patch versions | `{{ pin_subpackage("myrecipe", max_pin="x.x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| calendar versioning              | `{{ pin_subpackage("myrecipe", max_pin=None) }}`    |

while replacing `"myrecipe"` with either `name` if a `name|lower` variable is defined in your recipe or with the lowercase name of the package in quotes.

### Bot commands for PR management

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

Note that the <code>@BiocondaBot please merge</code> command is now depreciated. Please just squash and merge instead.

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by xiaodli** [comment]
@aliciaaevans Hi, I have some confusion. I modified the meta.yaml file and build.sh file many times, but the test_linux check always fails. I tried it on my local computer by ```conda build .``` command(include defaults channel or remove defaults channel). I think the reason for the failure may be that there is no defaults channel in conda channels during the test linux check. I added this command ```conda config --add channels defaults ``` in build.sh, but it doesn't seem to add the defaults channel. Is there any problem with adding the defaults channel? Do you have any suggestions for me? Thank you very much.
The following is test_linux Configure conda content.
```
Starting: Configure conda
==============================================================================
Task         : Command line
Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
Version      : 2.244.3
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
==============================================================================
Generating script.
Script contents:
bash configure-conda.sh
========================== Starting Command Output ===========================
/usr/bin/bash --noprofile --norc /home/vsts/work/_temp/b781a4ad-9f82-4ad1-8c61-15eedcbc6b64.sh
Warning: 'bioconda' already in 'channels' list, moving to the top
Warning: 'conda-forge' already in 'channels' list, moving to the top

CondaKeyError: 'channels': 'defaults' is not in the 'channels' key of the config file

Warning: 'file:///opt/mambaforge/conda-bld' already in 'channels' list, moving to the top

Finishing: Configure conda

```

test linux check failure seems to often occur before ```Solving environment (_test_env): ...working...done```
The following is ```conda build .``` 's log in my computer
```
Packaging quota_anchor
Packaging quota_anchor-0.0.1a0-py_0
number of files: 43
Fixing permissions
INFO :: Time taken to mark (prefix)
        0 replacements in 0 files was 0.00 seconds
Files containing CONDA_PREFIX
-----------------------------
python-scripts/quota_Anchor (text): Patching
site-packages/quota_anchor/config_file/software_path.ini (text): Patching
WARNING: Importing conda-verify failed.  Please be sure to test your packages.  conda install conda-verify to make this message go away.
TEST START: /home/dell/miniconda3/conda-bld/noarch/quota_anchor-0.0.1a0-py_0.tar.bz2
Renaming /home/dell/miniconda3/conda-bld/quota_anchor_1725617789897/_build_env prefix directory '/home/dell/miniconda3/conda-bld/quota_anchor_1725617789897/_build_env' to '/home/dell/miniconda3/conda-bld/quota_anchor_1725617789897/build_prefix_moved_quota_anchor-0.0.1a0-py_0_linux-64'
shutil.move(/home/dell/miniconda3/conda-bld/quota_anchor_1725617789897/_build_env prefix)=/home/dell/miniconda3/conda-bld/quota_anchor_1725617789897/_build_env, dest=/home/dell/miniconda3/conda-bld/quota_anchor_1725617789897/build_prefix_moved_quota_anchor-0.0.1a0-py_0_linux-64)
Renaming work directory '/home/dell/miniconda3/conda-bld/quota_anchor_1725617789897/work' to '/home/dell/miniconda3/conda-bld/quota_anchor_1725617789897/work_moved_quota_anchor-0.0.1a0-py_0_noarch'
shutil.move(work)=/home/dell/miniconda3/conda-bld/quota_anchor_1725617789897/work, dest=/home/dell/miniconda3/conda-bld/quota_anchor_1725617789897/work_moved_quota_anchor-0.0.1a0-py_0_noarch)
Reloading output folder (local): ...working... done
Solving environment (_test_env): ...working... done

## Package Plan ##

  environment location: /home/dell/miniconda3/conda-bld/quota_anchor_1725617789897/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac


The following NEW packages will be INSTALLED:

    _libgcc_mutex:           0.1-conda_forge                        conda-forge
    _openmp_mutex:           4.5-2_gnu                              conda-forge
    anchorwave:              1.2.5-hdcf5f25_0                       bioconda   
    biopython:               1.70-np112py36_1                       bioconda   
    blas:                    1.1-openblas                           conda-forge
    blast:                   2.16.0-hc155240_2                      bioconda   
    bzip2:                   1.0.8-h4bc722e_7                       conda-forge
    c-ares:                  1.33.1-heb4867d_0                      conda-forge
    ca-certificates:         2024.8.30-hbcca054_0                   conda-forge
    curl:                    7.87.0-h6312ad2_0                      conda-forge
    cycler:                  0.11.0-pyhd8ed1ab_0                    conda-forge
    dbus:                    1.13.6-h5008d03_3                      conda-forge
    descartes:               1.1.0-py_4                             conda-forge
    diamond:                 2.1.8-h43eeafb_0                       bioconda   
    entrez-direct:           22.4-he881be0_0                        bioconda   
    expat:                   2.6.3-h5888daf_0                       conda-forge
    fontconfig:              2.14.2-h14ed4e7_0                      conda-forge
    freetype:                2.12.1-h267a509_2                      conda-forge
    gawk:                    5.3.0-ha916aea_0                       conda-forge
    gettext:                 0.22.5-he02047a_3                      conda-forge
    gettext-tools:           0.22.5-he02047a_3                      conda-forge
    gffread:                 0.12.7-hdcf5f25_4                      bioconda   
    glib:                    2.80.2-hf974151_0                      conda-forge
    glib-tools:              2.80.2-hb6ce0ca_0                      conda-forge
    gmap:                    2024.08.14-pl5321h9d449c0_0            bioconda   
    gmp:                     6.3.0-hac33072_2                       conda-forge
    gst-plugins-base:        1.14.1-h6a678d5_1                      defaults   
    gstreamer:               1.14.1-h5eee18b_1                      defaults  
```
Some packages appear to be installed from the defaults channel. Therefore, I suspect the reason for the failure is that the defaults channel does not exist.

**Comment by aliciaaevans** [comment]
Bioconda only supports dependencies from `bioconda` and `conda-forge` channels. The `defaults` channel is part of Anaconda which is not free for all users.

Do you have an idea of which of this recipe's dependencies is trying to include those two packages from `defaults`? Steps forward would be to identify where those dependencies are coming from and then see if there's some way to remove or replace with something from `bioconda` and `conda-forge`.

**Comment by xiaodli** [comment]
> Bioconda only supports dependencies from `bioconda` and `conda-forge` channels. The `defaults` channel is part of Anaconda which is not free for all users.
> 
> Do you have an idea of which of this recipe's dependencies is trying to include those two packages from `defaults`? Steps forward would be to identify where those dependencies are coming from and then see if there's some way to remove or replace with something from `bioconda` and `conda-forge`.

Thank you for your reply.

**Comment by aliciaaevans** [comment]
This message is expected, so it can be ignored (though I see why it's confusing): `CondaKeyError: 'channels': 'defaults' is not in the 'channels' key of the config file`

I was able to build this locally without `defaults` channel, using `bioconda-utils build --packages quota_anchor`, with muscle in the dependency list but without the four you just added. Did you add those because you know they are needed or because you saw them locally from defaults?

 When you build locally, it's best to use `bioconda-utils` instead of conda build directly. Also, check your conda channels `conda config --show channels`. If `defaults` is at the top it will have priority and that might cause some of the local issues.

**Comment by aliciaaevans** [comment]
I was able to build it locally without them. I'm wondering if they were included because of your local channel setup.

For some reason the Azure jobs didn't trigger on that last build, so ignore the green checkmark. (It's some issue between GitHub and Azure I've seen before.)

My suggestion is to remove those 4 again and let the whole job run without pushing anything else. I can then look at the logs. It could be it's actually failing because of memory or something, but it's difficult to tell what's actually happening when there are a lot of commits because the previous one gets cancelled.

**Comment by xiaodli** [comment]
> bioconda-utils build --packages quota_anchor

ok，Thanks

**Comment by xiaodli** [comment]
> I was able to build it locally without them. I'm wondering if they were included because of your local channel setup.
> 
> For some reason the Azure jobs didn't trigger on that last build, so ignore the green checkmark. (It's some issue between GitHub and Azure I've seen before.)
> 
> My suggestion is to remove those 4 again and let the whole job run without pushing anything else. I can then look at the logs. It could be it's actually failing because of memory or something, but it's difficult to tell what's actually happening when there are a lot of commits because the previous one gets cancelled.

I also can use ``` ``` 

> I was able to build it locally without them. I'm wondering if they were included because of your local channel setup.
> 
> For some reason the Azure jobs didn't trigger on that last build, so ignore the green checkmark. (It's some issue between GitHub and Azure I've seen before.)
> 
> My suggestion is to remove those 4 again and let the whole job run without pushing anything else. I can then look at the logs. It could be it's actually failing because of memory or something, but it's difficult to tell what's actually happening when there are a lot of commits because the previous one gets cancelled.

I can also use ```bioconda-utils build --packages quota_anchor ```to build successfully without the defaults channel
```
auto_activate_base: false
channels:
  - bioconda
  - conda-forge
show_channel_urls: true
default_channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2
custom_channels:
  conda-forge: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  msys2: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  bioconda: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  menpo: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  pytorch: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  pytorch-lts: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  simpleitk: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  deepmodeling: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/

```

**Comment by xiaodli** [comment]
> I was able to build it locally without them. I'm wondering if they were included because of your local channel setup.
> 
> For some reason the Azure jobs didn't trigger on that last build, so ignore the green checkmark. (It's some issue between GitHub and Azure I've seen before.)
> 
> My suggestion is to remove those 4 again and let the whole job run without pushing anything else. I can then look at the logs. It could be it's actually failing because of memory or something, but it's difficult to tell what's actually happening when there are a lot of commits because the previous one gets cancelled.

I can also use ``` bioconda-utils build --packages quota_anchor``` to build successfully without the defaults channel
The following is ```.condarc``` file content
```
auto_activate_base: false
channels:
  - bioconda
  - conda-forge
show_channel_urls: true
default_channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2
custom_channels:
  conda-forge: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  msys2: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  bioconda: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  menpo: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  pytorch: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  pytorch-lts: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  simpleitk: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  deepmodeling: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/
```

**Comment by aliciaaevans** [comment]
Hmm, I suspect it is running out of memory.

**Comment by xiaodli** [comment]
> I was able to build it locally without them. I'm wondering if they were included because of your local channel setup.
> 
> For some reason the Azure jobs didn't trigger on that last build, so ignore the green checkmark. (It's some issue between GitHub and Azure I've seen before.)
> 
> My suggestion is to remove those 4 again and let the whole job run without pushing anything else. I can then look at the logs. It could be it's actually failing because of memory or something, but it's difficult to tell what's actually happening when there are a lot of commits because the previous one gets cancelled.

```
14:46:11 BIOCONDA INFO (OUT)   adding 'quota_Anchor-0.0.1a0.dist-info/RECORD'
14:46:11 BIOCONDA INFO (OUT)   removing build/bdist.linux-x86_64/wheel
14:46:11 BIOCONDA INFO (OUT)   Building wheel for quota_Anchor (setup.py): finished with status 'done'
14:46:11 BIOCONDA INFO (OUT)   Created wheel for quota_Anchor: filename=quota_Anchor-0.0.1a0-py3-none-any.whl size=5234673 sha256=9ebc191d320d3e6b50262fd43a9565bfb682aa288393197ffb0394e1ad92d6cd
14:46:11 BIOCONDA INFO (OUT)   Stored in directory: /tmp/pip-ephem-wheel-cache-3vyiu136/wheels/63/1c/4b/4b894348415c4424a5748c76beeba61a5b847f2ca0bb0f1656
14:46:11 BIOCONDA INFO (OUT) Successfully built quota_Anchor
14:46:11 BIOCONDA INFO (OUT) Installing collected packages: quota_Anchor
14:46:11 BIOCONDA INFO (OUT) 
14:46:11 BIOCONDA INFO (OUT)   changing mode of $PREFIX/bin/quota_Anchor to 755
14:46:11 BIOCONDA INFO (OUT) Successfully installed quota_Anchor-0.0.1a0
14:46:11 BIOCONDA INFO (OUT) Removed build tracker: '/tmp/pip-build-tracker-p0glfck8'
```

```
Nothing to show. Final logs are missing. This can happen when the job is cancelled or times out.
```

> Hmm, I suspect it is running out of memory.嗯，我怀疑它的内存不足了。

So, do I need a larger runner?

**Comment by aliciaaevans** [comment]
There have been several of these PRs recently that have this disconnect issue. I'm going to try building them on our bulk branch that uses GitHub Actions for CI. Can you please undo any unwanted changes that you made to experiment on this branch and let me know if/when the recipe is ready?

**Comment by aliciaaevans** [comment]
I went ahead and built this as is on the `bulk` branch. It has been successfully uploaded to the channel. (I haven't merged `bulk` back to `master` yet, waiting on another recipe.)

**Pull request closed without merging**
