### PR TITLE
Update mtsv to 1.0.4

### PR DESCRIPTION
**Pull request by tfursten**
Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it. Note that if you are not already a member of the bioconda project (meaning that you can't add this label), please ping `@bioconda/core` so that your PR can be reviewed and merged (please note if you'd like to be added to the bioconda project). Please see https://github.com/bioconda/bioconda-recipes/issues/15332 for more details.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by dpryan79** [comment]
@tfursten Does this really only work under python 3.6 and not 3.7?

**Comment by tfursten** [comment]
@dpryan79 Last I checked there was a problem resolving some packages using 3.7.

**Comment by dpryan79** [comment]
OK, I'll see if that's something we can resolved real quick then.

**Comment by dpryan79** [comment]
Indeed, there are conflicts between python 3.7 and a few other dependencies that won't be easy to resolve. I've reverted my change and approved the PR. Go ahead and merge once the tests turn green (otherwise I'll go ahead and merge it).

**Comment by dpryan79** [comment]
@bioconda-bot merge

**Comment by dpryan79** [comment]
Thanks @tfursten!

**Comment by tfursten** [comment]
Thanks for your help, @dpryan79

**Pull request merged**
