### PR TITLE
Adding new recipe (ncbi/TPMcalculator) and bumping igvtools and sra-tools to latest versions

### PR DESCRIPTION
**Pull request by r78v10a07**
Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it. Note that if you are not already a member of the bioconda project (meaning that you can't add this label), please ping `@bioconda/core` so that your PR can be reviewed and merged (please note if you'd like to be added to the bioconda project). Please see https://github.com/bioconda/bioconda-recipes/issues/15332 for more details.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by r78v10a07** [comment]
In this PR there are two software that needs g++ for its compilation. The meta file include the compiler macros:

```
requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
```

However, the test failed with error:

```
/bin/sh: g++: command not found
```

Both recipes are build correctly in my local `miniconda` create with the `bootstrap.py` script

```
18:01:31 BIOCONDA INFO (OUT) Version: 0.0.3
18:01:31 BIOCONDA INFO (OUT)
18:01:31 BIOCONDA INFO (OUT) Resource usage statistics from testing tpmcalculator:
18:01:31 BIOCONDA INFO (OUT)    Process count: 1
18:01:31 BIOCONDA INFO (OUT)    CPU time: unavailable
18:01:31 BIOCONDA INFO (OUT)    Memory: 3.1M
18:01:31 BIOCONDA INFO (OUT)    Disk usage: 12B
18:01:31 BIOCONDA INFO (OUT)    Time elapsed: 0:00:02.1
18:01:31 BIOCONDA INFO (OUT)
18:01:31 BIOCONDA INFO (OUT) TEST END: /home/veraalva/workplace/miniconda/conda-bld/linux-64/tpmcalculator-0.0.3-hdbb99b9_0.tar.bz2
18:01:31 BIOCONDA INFO (OUT) Renaming work directory,  /home/veraalva/workplace/miniconda/conda-bld/tpmcalculator_1559858409935/work  to  /home/veraalva/workplace/miniconda/conda-bld/tpmcalculator_1559858409935/work_moved_tpmcalculator-0.0.3-hdbb99b9_0_linux-64_main_build_loop
18:01:31 BIOCONDA INFO (OUT) # Automatic uploading is disabled
18:01:31 BIOCONDA INFO (OUT) # If you want to upload package(s) to anaconda.org later, type:
18:01:31 BIOCONDA INFO (OUT)
18:01:31 BIOCONDA INFO (OUT) anaconda upload /home/veraalva/workplace/miniconda/conda-bld/linux-64/tpmcalculator-0.0.3-hdbb99b9_0.tar.bz2
18:01:31 BIOCONDA INFO (OUT)
18:01:31 BIOCONDA INFO (OUT) # To have conda build upload to anaconda.org automatically, use
18:01:31 BIOCONDA INFO (OUT) # $ conda config --set anaconda_upload yes
18:01:31 BIOCONDA INFO (OUT)
18:01:31 BIOCONDA INFO (OUT) anaconda_upload is not set.  Not uploading wheels: []
18:01:31 BIOCONDA INFO (OUT) ####################################################################################
18:01:31 BIOCONDA INFO (OUT) Resource usage summary:
18:01:31 BIOCONDA INFO (OUT)
18:01:31 BIOCONDA INFO (OUT) Total time: 0:01:21.3
18:01:31 BIOCONDA INFO (OUT) CPU usage: sys=0:00:00.3, user=0:00:08.1
18:01:31 BIOCONDA INFO (OUT) Maximum memory usage observed: 328.9M
18:01:31 BIOCONDA INFO (OUT) Total disk usage observed (not including envs): 17.7K

18:01:32 BIOCONDA INFO BUILD SUCCESS tpmcalculator-0.0.3-hdbb99b9_0.tar.bz2
18:01:32 BIOCONDA INFO Executing: 'conda build purge'
18:01:33 BIOCONDA INFO (ERR) read filter "zstd" is not supported
18:01:33 BIOCONDA INFO (ERR) write filter "zstd" is not supported
18:01:33 BIOCONDA INFO BUILD SUMMARY: successfully built 1 of 1 recipes
```

Could anyone from @bioconda/lib help, please?

**Comment by dpryan79** [comment]
@r78v10a07 The compilers aren't actually named `gcc` or `g++`, but have rather unusual names. The general idea is to ensure that the packages respect the `$CC` and `$CXX` environment variables, or to inject them into the build system if not. I've made an initial attempt at that, though often this takes a fair bit of trial and error since I'm not familiar with how these particular packages are built.

**Comment by epruesse** [comment]
@biocondabot lint

**Comment by dpryan79** [comment]
@r78v10a07 As far as I can tell this is good to go (I recall you confirming that remote blast should still work). If that's correct, I'll approve the PR and merge it. BTW, shall I add you to bioconda?

**Comment by r78v10a07** [comment]
@dpryan79 , I agree that everything is working fine. I tested the packages in OS and Linux and all work fine.
It will be great if you can add me to bioconda as I'm planning the update insertion of other packages.

**Pull request merged**
