### PR TITLE
change perl build to support OSX

### PR DESCRIPTION
**Pull request by bgruening**

### CODE REVIEW

**Comment by bgruening** [comment]
ping @jxtx, @acaprez, @chapmanb does this look ok for you? I would like to get all perl builds into OSX.

**Comment by chapmanb** [comment]
Wow, thank you. I'm so happy to be building more packages for OSX.

**Comment by acaprez** [comment]
Looks fine to me.  I'm curious now - has there been a consensus reached on using `gcc` vs `clang` for OS X builds?

**Comment by jxtx** [comment]
Is 

> +        - gcc   # [linux]
> +        - llvm  # [osx]

In the canu recipe necessary? Won't that be the default?

**Comment by bgruening** [comment]
Oh great randomly failing tests, I like it ...
@acaprez sorry I don't know about this discussion. Would it be ok if I increase all versions of perl-* and remove the skip osx in a next PR?
@jxtx I guess explicit is better than implicit.

**Comment by jxtx** [comment]
> I guess explicit is better than implicit.

But that argument would suggest these lines should be in _every_ recipe that compiles or uses anything compiled?

**Comment by bgruening** [comment]
Yes. But @johanneskoester knows better.

**Comment by bgruening** [comment]
@chapmanb @johanneskoester feel free to merge this if you think it's ready to go. I will try to find time to fix the other perl-* packages.

**Comment by johanneskoester** [comment]
@jxtx, indeed, they should be. They just aren't because the decision wasn't made initially.

**Pull request merged**
