### PR TITLE
Build bump to hopefully handle runtime issues due to openblas.

### PR DESCRIPTION
**Pull request by molpopgen**
Build bump.  The current build is failing to work properly if conda is updated to pull in new openblas from forge.

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Review by molpopgen — COMMENTED** [review]
@BiocondaBot please add label

**Comment by molpopgen** [comment]
@bioconda/core -- ready for review.

**Comment by dpryan79** [comment]
FYI, you are strongly encouraged to not run `conda update` on an environment you care about, it is somewhat likely to mess things up (as you're noticing).

**Comment by dpryan79** [comment]
@bioconda-bot please fetch artifacts

**Comment by dpryan79** [comment]
This has the same pinnings as what's already uploaded, so it won't have the desired effect. Just don't run `conda update`.

**Comment by molpopgen** [comment]
> This has the same pinnings as what's already uploaded, so it won't have the desired effect. Just don't run `conda update`.

That's what I was thinking would happen.  But the problem isn't conda update.  Users with existing environments are having issues installing this.  Certain other packages from forge also behave strangely at the moment.  Issues with the openlas linked to numpy seem to be part of the problem.

I tried to update this recipe to use forge's recommended approach to pin numpy, but that failed CI here.  In any case, the way they do it only pins numpy itself, I think, and not the blas dependency, which changes quite a bit.

**Comment by molpopgen** [comment]
In any case, even with the same pinnings, this should be merged.  The previous auto-bump resulted in a recipe with the minimum dependencies for things like tskit being incorrect.  This bump fixes that.

**Comment by dpryan79** [comment]
Ah, in that case let's merge it :)

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Pull request merged**
