### PR TITLE
enable perl for vrna

### PR DESCRIPTION
**Pull request by mmiladi**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by mmiladi** [comment]
According to https://github.com/bioconda/bioconda-recipes/issues/7415 there is an incompatibility issue between Docker gcc and conda gcc.

**Comment by mtw** [comment]
@mmiladi maybe you need the ``check`` dependency for building?

**Comment by mtw** [comment]
maybe adding  ``-fPIC`` to CFLAGS helps?

**Comment by mmiladi** [comment]
@mtw What's the best way to add `-fPIC`? I assumed --enabled-shared would do this?

**Comment by mtw** [comment]
you should be able to pass CFLAGS right after the configure call, like ``./configure --foo --bar CFLAGS="-fPIC -O3 -g" ``

**Comment by RaumZeit** [comment]
May I ask why you use the `--enable-shared` as configure option? As far as I understand, thsi will break libtool, and therefore you'll see the `-fPIC` suggestion. Please try removing both, `-fPIC` and the `--enable-shared` but add a `V=1` to the `make` command. This will at least show us the actuall parameters that are passed to the compiler and linker in the CI

**Comment by RaumZeit** [comment]
Another note: To circumvent running the entire autotools toolchain, I suggest creating a distribution tarball where all the patches are already applied, e.g. as ViennaRNA-2.4.3.1 or something else...

**Comment by mmiladi** [comment]
@RaumZeit `--enable-shared` was a try and error to fix the complain about `-fPIC`
Preparing a patched tarball is really nice idea! I am working on that.

**Comment by mmiladi** [comment]
Can this be due to having both `shared` and `static` enabled? Hint from the second answer here: https://stackoverflow.com/questions/19364969/compilation-fails-with-relocation-r-x86-64-32-against-rodata-str1-8-can-not/42388145

**Comment by mtw** [comment]
I guess now we should get rid of the entire CFLAGS statement again :-/

**Comment by mmiladi** [comment]
True! Another try :)

**Comment by RaumZeit** [comment]
This persistent linker error is odd... For some reasons that I do not understand yet the linker tries to link against a static libperl library in the final step of making the Perl interface. Therefore the linker complains about adding `-fPIC` during compilation, not for anything from ViennaRNA but for libperl!
Could you somehow try to find out whether there is any libperl.so in the build environment?

**Comment by RaumZeit** [comment]
Hi again!
Sorry that I couldn't be much of help yet, I just figured that bioconda only provides `libperl.a` to link the ViennaRNA perl interface to. I'm still in the process of finding out how and why linking should be done if a static version of libperl is available...Probably, the `Makefile.am` in `interfaces/Perl` needs to be adjusted...
Any insights and help is appreciated!

**Comment by RaumZeit** [comment]
Unfortunately, I'm out of ideas on how to solve the linker problem.
Probably, we should wait for any progress made here: https://github.com/conda-forge/perl-feedstock/issues/19

**Comment by martin-raden** [comment]
@mmiladi think this is outdated!?! recent version supports perl, so I am closing this..

**Pull request closed without merging**
