### PR TITLE
make linux-aarch64 build for age_metasv

### PR DESCRIPTION
**Pull request by sunqian2116**
Describe your pull request here

It can be build in the ARM64 machine, but it could not work originally
8fa83dbddcda260930f018ff4e00dac
 
After adding  “libstdcxx-ng >=12” in the meta file，it looks good for me.

31157986ac077826be4af04485df56f

But I want to add the command of "LD_PRELOAD" into the build.sh, what should I do?

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

### General instructions

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

### Instructions for avoiding API, ABI, and CLI breakage issues
Conda is able to record and lock (a.k.a. pin) dependency versions used at build time of other recipes.
This way, one can avoid that expectations of a downstream recipe with regards to API, ABI, or CLI are violated by later changes in the recipe.
If not already present in the meta.yaml, make sure to specify `run_exports` (see [here](https://bioconda.github.io/contributor/linting.html#missing-run-exports) for the rationale and comprehensive explanation).
Add a `run_exports` section like this:

```yaml
build:
  run_exports:
    - ...

```

with `...` being one of:

| Case                             | run_exports statement                                               |
| -------------------------------- | ------------------------------------------------------------------- |
| semantic versioning              | `{{ pin_subpackage("myrecipe", max_pin="x") }}`     |
| semantic versioning (0.x.x)      | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}`   |
| known breakage in minor versions | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| known breakage in patch versions | `{{ pin_subpackage("myrecipe", max_pin="x.x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| calendar versioning              | `{{ pin_subpackage("myrecipe", max_pin=None) }}`    |

while replacing `"myrecipe"` with either `name` if a `name|lower` variable is defined in your recipe or with the lowercase name of the package in quotes.

### Bot commands for PR management

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

Note that the <code>@BiocondaBot please merge</code> command is now depreciated. Please just squash and merge instead.

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by sunqian2116** [comment]
@BiocondaBot please add label

**Comment by sunqian2116** [comment]
@BiocondaBot please fetch artifacts

**Comment by martin-g** [comment]
```
mgrigorov in 🌐 euler-arm-22 in /tmp/age_metasv via 🅒 font-ubuntu took 2s 
❯ conda install ./age-metasv-2015.01.29.3-h78569d1_8.tar.bz2                                                                                                                                           (font-ubuntu) 

Downloading and Extracting Packages
                                                                                                                                                                                                                     

Downloading and Extracting Packages

Preparing transaction: done
Verifying transaction: done
Executing transaction: done

mgrigorov in 🌐 euler-arm-22 in /tmp/age_metasv via 🅒 font-ubuntu took 3s 
❯ tar jxvf age-metasv-2015.01.29.3-h78569d1_8.tar.bz2                                                                                                                                                  (font-ubuntu) 
info/files
info/test/run_test.sh
info/run_exports.json
info/recipe/build.sh
info/hash_input.json
info/paths.json
info/index.json
info/recipe/flags.patch
info/recipe/meta.yaml.template
info/recipe/meta.yaml
info/recipe/conda_build_config.yaml
info/about.json
info/git
bin/age_align

mgrigorov in 🌐 euler-arm-22 in /tmp/age_metasv via 🅒 font-ubuntu 
❯ file bin/age_align                                                                                                                                                                                   (font-ubuntu) 
bin/age_align: ELF 64-bit LSB pie executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, not stripped

mgrigorov in 🌐 euler-arm-22 in /tmp/age_metasv via 🅒 font-ubuntu 
❯ age_align --help                                                                                                                                                                                     (font-ubuntu) 
Usage:
	age_align
		[-version]
		[-indel|-tdup|-inv|-invl|-invr]
		[-match=value:1] [-mismatch=value:-2]
		[-go=value:-2] [-ge=value:-1]
		[-both] [-revcom1] [-revcom2]
		[-coor1=start-end] [-coor2=start-end] file1.fa file2.fa
```

Looks good to me!

**Comment by martin-g** [comment]
@BiocondaBot please add label

**Review by daler — APPROVED** [review]

**Pull request merged**
