### PR TITLE
Fix KmerGenie

### PR DESCRIPTION
**Pull request by bebatut**
* [X] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [X] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

I fixed the recipe: the tool was failing when I launched it. I remove the installation using the `setup` and I tested it afterwards with local installation. 

@jerowe @bgruening What do you think?

### CODE REVIEW

**Comment by bebatut** [comment]
Can I merge it?

**Comment by rchikhi** [comment]
thanks for fixing kmergenie!

**Comment by rchikhi** [comment]
did it work for you on a small test file?

**Comment by bebatut** [comment]
I launched it on a FastQ file and it worked (at least there is no error :))
Is it not working for you?

**Comment by jerowe** [comment]
Thanks, everyone. ;-)

**Comment by rchikhi** [comment]
Maybe this is me mis-using conda, but when I install kmergenie using the `conda install kmergenie` command, there's still an error. I actually don't know how that works, when a new recipe is pushed, does it immediately affect users who type `conda install [recipe]`?

Here's my log


```
$ conda update --prefix /home/rayan/miniconda3 anaconda
[..]
anaconda                  4.3.1               np111py35_0
$ conda uninstall kmergenie
[..]
$ conda install kmergenie
The following NEW packages will be INSTALLED:
    kmergenie: 1.7016-py35r3.3.1_0 bioconda
[..]
$ kmergenie ~/data/test_reads.fq
[rayan@blok-bok tmp]$ kmergenie ~/data/reads3.fa.gz
running histogram estimation
Traceback (most recent call last):
  File "/home/rayan/miniconda3/lib/python3.5/site-packages/kmergenie-0.0.1-py3.5.egg/EGG-INFO/scripts/kmergenie", line 79, in execute_once
  File "/home/rayan/miniconda3/lib/python3.5/subprocess.py", line 557, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/home/rayan/miniconda3/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/home/rayan/miniconda3/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
NotADirectoryError: [Errno 20] Not a directory
[..]
```

**Comment by bebatut** [comment]
Yes, it is installing the previous version.
It is because you are using the miniconda3 with Python 3.5 as default. And in the last PR, I limit the conda package to Python 2.7. 
Can you try in a conda environment?

**Comment by rchikhi** [comment]
I tested it on a python2.7 environment and it worked fine, thank you :+1: :)

**Pull request merged**
