### PR TITLE
Update pyranges to 0.0.64

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`pyranges`](https://bioconda.github.io/recipes/pyranges/README.html): **0.0.63** &rarr; **0.0.64**

[install with bioconda](http://bioconda.github.io/recipes/pyranges/README.html) [Conda](https://anaconda.org/bioconda/pyranges/files)

Info | Link
-----|-----
Recipe | [`recipes/pyranges`](https://github.com//bioconda/bioconda-recipes/tree/bump/pyranges/recipes/pyranges) (click to view/edit other files)
Releases |[https://pypi.org/pypi/pyranges/json](https://pypi.org/pypi/pyranges/json)

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by johanneskoester** [comment]
@BiocondaBot please merge

**Comment by johanneskoester** [comment]
@dpryan79 mhm, did I do something wrong? The action has run through, but nothing happens here.

**Comment by dpryan79** [comment]
Wrong bot

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Comment by dpryan79** [comment]
Hmm, I'll change it to respond to both since it is in fact replying as @BiocondaBot

**Comment by johanneskoester** [comment]
Thanks!

**Pull request merged**
