### PR TITLE
Mspurity recipe

### PR DESCRIPTION
**Pull request by Tomnl**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by bgruening** [comment]
@Tomnl do you mind submitting the r-* packages to conda-forge? This might take longer until it gets merged but we think it is the right thing to do long term.

**Comment by Tomnl** [comment]
Hi @bgruening, 

Yeah sure, I can submit the r-* packages to conda-forge

Just to check, I should still add the bioconductor packages in bioconda though right?

**Comment by bgruening** [comment]
Yes. Everything what is vaguely bioinformatics related can stay here. All general purpose libraries should go into conda-forge.

**Comment by bgruening** [comment]
Thanks!

**Comment by bgruening** [comment]
Thanks @Tomnl!

**Pull request merged**
