### PR TITLE
[seqfu] add conda forge channel

### PR DESCRIPTION
**Pull request by telatin**
Specified conda-forge channel for C libraries
----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by telatin** [comment]
@BiocondaBot please add label

**Review by dpryan79 — APPROVED** [review]

**Comment by telatin** [comment]
Hi @dpryan79 thanks for checking on this.
The issue I found is that automatic workflow managers might attempt:
```
conda create --mkdir --yes --quiet --prefix TMP bioconda::seqfu=1.9.3
```
and this would fail
```

PackagesNotFoundError: The following packages are not available from current channels:

  - libzlib[version='>=1.2.11,<1.3.0a0']
```

Adding "-c conda-forge" fixes it, is there any way to specify this at the recipe level?
Thanks a million

**Comment by rpetit3** [comment]
For recipe, not that I'm aware of. Easiest is probably going to be for users to make use of `.condarc` or add the channels to the command:

```
conda create --mkdir --yes --quiet --prefix TMP -c conda-forge -c bioconda seqfu=1.9.3
```

**Comment by dpryan79** [comment]
@BiocondaBot please merge

@telatin As @rpetit3 mentioned there's unfortunately no way to specify that in a recipe. We would actually like to be able to specify that somehow for the entire channel, but that's also not possible at the moment with conda. If people correctly setup their channels as we suggest in the documentation, though, then they won't need to specify any channels at all.

**Comment by telatin** [comment]
> For recipe, not that I'm aware of. Easiest is probably going to be for users to make use of `.condarc` or add the channels to the command:
> 
> ```
> conda create --mkdir --yes --quiet --prefix TMP -c conda-forge -c bioconda seqfu=1.9.3
> ```

So for a nextflow DSL2 module, I have to either specify all the dependencies
```
 conda (params.enable_conda ? "bioconda::seqfu=1.9.3 conda-forge::libzlib..." : null)
```
or probably simpler at this point to make a small YAML file
```
 conda (params.enable_conda ? "$baseDir/deps/sequtils.yaml" : null)
```

**Comment by dpryan79** [comment]
For reproducible pipelines always give a full YAML file listing everything.

**Pull request merged**
