### PR TITLE
Update dada2

### PR DESCRIPTION
**Pull request by valscherz**
Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it. Note that if you are not already a member of the bioconda project (meaning that you can't add this label), please ping `@bioconda/core` so that your PR can be reviewed and merged (please note if you'd like to be added to the bioconda project). Please see https://github.com/bioconda/bioconda-recipes/issues/15332 for more details.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

I could observe that : 
- this package was blacklisted
- that no build were offered for the previous version (1.12.0) for linux, only for MacOS

I guess both were due to unavailable dependencies. This could be fixed (only for R 3.5.1) setting back in the meta the dependencies to the ones stated on bioconductor instead of strict, "one version only" dependencies standing previously (I couldn't find why?!) 

I hope you would still consider to update this package...

### CODE REVIEW

**Comment by dpryan79** [comment]
What's your goal? The dependency pinning in bioconductor packages is very purposeful, so that can't be changed.

**Comment by valscherz** [comment]
> What's your goal? 

Have this package version conda

>The dependency pinning in bioconductor packages is very purposeful, so that can't be changed.

OK. But my changes are reverting back to what was the depenencies on bioconductor (https://bioconductor.org/packages/3.9/bioc/html/dada2.html)

**Comment by dpryan79** [comment]
The dependency versions listed on the bioconductor website aren't actually correct, packages are only compatible with dependencies from the exact same bioconductor release. Anyway, this package is already being built in the bulk branch and should be available within the next week or so (the OSX build for it is already available).

**Comment by valscherz** [comment]
> The dependency versions listed on the bioconductor website aren't actually correct, packages are only compatible with dependencies from the exact same bioconductor release. Anyway, this package is already being built in the bulk branch and should be available within the next week or so (the OSX build for it is already available).

Great, good to know and thanks for your help!

**Pull request closed without merging**
