### PR TITLE
R goalie

### PR DESCRIPTION
**Pull request by pinin4fjords**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

Similarly to https://github.com/bioconda/bioconda-recipes/pull/13592, this is a PR to provide dependencies for an updated r-basejump. See also https://github.com/steinbaugh/basejump/issues/141. 

@mjsteinbaugh - I have removed R 3.4 pinning as the above PR. If you think this recipe needs it let me know. Also, do you want the 'suggests' dependencies added to meta.yaml?

### CODE REVIEW

**Comment by mjsteinbaugh** [comment]
I updated goalie to better support R 3.4 using backports in the v0.2.8 release here:
https://github.com/steinbaugh/goalie/releases/tag/v0.2.8

I don't think we need to include the suggested packages in the recipe currently, since those packages are only used for documentation examples and unit testing.

**Comment by pinin4fjords** [comment]
Thanks @mjsteinbaugh , I will update the recipe for the new build. So this recipe does need the 3.4 pinning?

**Comment by mjsteinbaugh** [comment]
No it should be fine without pinning to 3.4

**Comment by pinin4fjords** [comment]
Good- thanks. Still the CI issues, hope it gets sorted soon.

**Comment by pinin4fjords** [comment]
ping @bioconda/core for new recipe. Okay to merge?

**Comment by pinin4fjords** [comment]
Thanks @dpryan79 !

**Pull request merged**
