### PR TITLE
add recipe for dragonflye

### PR DESCRIPTION
**Pull request by rpetit3**
Dragonflye is a pipeline that aims to make assembling Oxford Nanopore reads quick and easy. At it's core its a fork of [Shovill](https://github.com/tseemann/shovill) that supports Nanopore reads instead of Illumina reads.

Dragonflye includes multiple assemblers and polishing steps. It *is not* a replacement for Trycycler, in my opinion they solve two different problems (Trycycler - produce high quality assemblies, Dragonflye - make the assembly process quick and easy)

To learn more about Dragonfly please see https://github.com/rpetit3/dragonflye

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by rpetit3** [comment]
@BiocondaBot please add label

**Comment by rpetit3** [comment]
Testing
```
mamba create -y -n dragonflye-test -c https://162640-42372094-gh.circle-artifacts.com/0/tmp/artifacts/packages -c conda-forge -c bioconda dragonflye
conda activate dragonflye-test

which dragonflye
/home/robert_petit/miniconda3/envs/dragonflye-test/bin/dragonflye

dragonflye --version
dragonflye 1.0.0

dragonflye --check
[dragonflye] Using any2fasta - /home/robert_petit/miniconda3/envs/dragonflye-test/bin/any2fasta | any2fasta 0.4.2
[dragonflye] Using assembly-scan - /home/robert_petit/miniconda3/envs/dragonflye-test/bin/assembly-scan | assembly-summary.py 0.4.0
[dragonflye] Using filtlong - /home/robert_petit/miniconda3/envs/dragonflye-test/bin/filtlong | Filtlong v0.2.1
[dragonflye] Using flye - /home/robert_petit/miniconda3/envs/dragonflye-test/bin/flye | 2.8.3-b1695
[dragonflye] Using kmc - /home/robert_petit/miniconda3/envs/dragonflye-test/bin/kmc | K-Mer Counter (KMC) ver. 3.1.1 (2019-05-19)
[dragonflye] Using medaka - /home/robert_petit/miniconda3/envs/dragonflye-test/bin/medaka | medaka 1.4.3
[dragonflye] Using miniasm - /home/robert_petit/miniconda3/envs/dragonflye-test/bin/miniasm | 0.3-r179
[dragonflye] Using minimap2 - /home/robert_petit/miniconda3/envs/dragonflye-test/bin/minimap2 | 2.21-r1071
[dragonflye] Using pigz - /home/robert_petit/miniconda3/envs/dragonflye-test/bin/pigz | pigz 2.6
[dragonflye] Using racon - /home/robert_petit/miniconda3/envs/dragonflye-test/bin/racon | v1.4.20
[dragonflye] Using rasusa - /home/robert_petit/miniconda3/envs/dragonflye-test/bin/rasusa | rasusa 0.3.0
[dragonflye] Using raven - /home/robert_petit/miniconda3/envs/dragonflye-test/bin/raven | 1.5.1
[dragonflye] Using seqtk - /home/robert_petit/miniconda3/envs/dragonflye-test/bin/seqtk | Version: 1.3-r106

dragonflye --list_models
[dragonflye] Hello robert_petit
[dragonflye] You ran: /home/robert_petit/miniconda3/envs/dragonflye-test/bin/dragonflye --list_models
[dragonflye] This is dragonflye 1.0.0
... TRUNCATED ...
[dragonflye] Generating a list of available Medaka models:
[dragonflye]    r103_fast_g507
[dragonflye]    r103_fast_snp_g507
... TRUNCATED ...
[dragonflye]    r941_prom_variant_g322
[dragonflye]    r941_prom_variant_g360

dragonflye --reads ont.fastq.gz --cpus 8 --nopolish --assembler raven --outdir test-quick --depth 10
[dragonflye] Hello robert_petit
[dragonflye] You ran: /home/robert_petit/miniconda3/envs/dragonflye-test/bin/dragonflye --reads ont.fastq.gz --cpus 8 --nopolish --assembler raven --outdir test-quick --depth 10  --gsize 5000000 --force
[dragonflye] This is dragonflye 1.0.0
... TRUNCATED ...
[dragonflye] Using genome graph file 'raven/assembly_graph.gfa' => 'raven.gfa'
[dragonflye] Walltime used: 0 min 28 sec
[dragonflye] Results in: /home/robert_petit/repos/dragonflye/temp/test-quick
[dragonflye] Final assembly graph: /home/robert_petit/repos/dragonflye/temp/test-quick/raven.gfa
[dragonflye] Final assembly contigs: /home/robert_petit/repos/dragonflye/temp/test-quick/contigs.fa
[dragonflye] Dragonfly fossils have been found with wingspans up to two feet (61cm)!
[dragonflye] Done.
```

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Comment by rpetit3** [comment]
Thank you!

**Pull request merged**
