### PR TITLE
Tepid and Danpos dependencies

### PR DESCRIPTION
**Pull request by richjstark**
The current dependencies for the TEPID package do not allow functions "tepid-map" and "tepid-discover" to work. They require samtools version >1.4 and samblaster to work.

### CODE REVIEW

**Comment by richjstark** [comment]
Build number set to 2 and added noarch: python.

**Comment by dpryan79** [comment]
I made a few changes to expedite this

**Comment by richjstark** [comment]
Thanks @dpryan79. You've saved me a lot of head-scratching.

**Comment by dpryan79** [comment]
No problem, happy to help. I quickly fixed something I messed up in the samtools versioning and then this should be good to go.

**Pull request merged**
