### PR TITLE
Update locarna to 2.0.0RC10

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`locarna`](https://bioconda.github.io/recipes/locarna/README.html): **2.0.0RC8** &rarr; **2.0.0RC10**

[install with bioconda](http://bioconda.github.io/recipes/locarna/README.html) [Conda](https://anaconda.org/bioconda/locarna/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/locarna`](https://github.com//bioconda/bioconda-recipes/tree/bump/locarna/recipes/locarna) (click to view/edit other files)
Summary | Multiple alignment of RNAs
Home | [https://s-will.github.io/LocARNA](https://s-will.github.io/LocARNA)
Releases |[https://github.com/s-will/LocARNA/releases](https://github.com/s-will/LocARNA/releases)
Author | @s-will
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by dpryan79** [comment]
@s-will Is the -lto stuff coming from libRNA or something like that?

**Comment by s-will** [comment]
Hi @dpryan79 , many thanks for your help! 
Yes, -lto is used because of libRNA. So, I think we can't easily get rid of it

**Comment by s-will** [comment]
The problem is in the pkg-config of Vienna, which add the options -fno-lto -Wl,-no-lto; this is not (anymore?) understood by clang. However, simply patching configure.ac to remove the faulty flags fails, since it introduces an additional autoconf requirement.

I will either introduce this dependency (probably the easiest quick fix), find an easier solution or already have another locarna release (in the longer run, either vrna will be fixed or locarna will already ship with the patch).

**Comment by s-will** [comment]
Patching configure.ac seems complicated and I didn't get this to work - instead, I decided to patch the distributed file configure directly

**Review by jfallmann — APPROVED** [review]
You could add yourself as maintainer maybe?

**Pull request merged**
