### PR TITLE
Update GToTree recipe

### PR DESCRIPTION
**Pull request by AstrobioMike**
hiya :) 

For the reason explained in my comment here (https://github.com/bioconda/bioconda-recipes/pull/37682#issuecomment-1297286070), i'm trying to figure out how to get bioconda to build the GToTree package specifically just for linux-64 and osx-64 (not one single noarch build, which makes it accessible through windows conda installations, which will never work with this package). 

Right now, the change in meta.yaml of putting `{{ compiler('c') }}` in the build section is just a guess based on a twitter suggestion (assumine bioconda won't build a windows version). Please help with telling me the appropriate way to do this if that isn't it

I know in general we don't want to remove packages, but i also need the noarch version to be removed from the [bioconda channel](https://anaconda.org/bioconda/gtotree), otherwise there will always be a gtotree available through a windows conda that will not work.

Thank you for any help!

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by AstrobioMike** [comment]
@BiocondaBot please add label

**Comment by dpryan79** [comment]
So what exactly is the issue with this being `noarch`. I understand that people could theoretically try to install it directly under windows, but presumably that wouldn't ever work since I imagine that there are dependencies that aren't available in Windows. Or is the issue instead that this assumes unix-like tools and syntax are available? Are people actually trying to install things under windows still? I kind of assumed that most of us that need to use Windows are using WSL(2) (i.e., virtualized Linux) these days.

**Comment by AstrobioMike** [comment]
Thanks for your help, @dpryan79 

Sorry for the added complication here. 

> Or is the issue instead that this assumes unix-like tools and syntax are available?

Yes, this. The actual GToTree package needs to be run in a unix-like environment. 

> Are people actually trying to install things under windows still?

Yea, I assume because a windows conda still handles many things just fine. I agree the best way when unix is needed is through WSL, and that's what I would do and what I recommend to people, but not everyone does that. And when a package is findable on a windows conda, like if it's listed as noarch, i don't know how they would know the problem is that it just won't work with a windows conda and that they need to be in a unix-like environment with a different conda version. I've actually already had someone message me since this went up saying they're having trouble with the windows conda installation. Whereas previously, it just wouldn't have even shown up there. To me it seems like giving people access to a broken package the way it currently is.

**Comment by AstrobioMike** [comment]
@vinisalazar, any ideas on troubleshooting the test problem? (I added you as a collab on the fork, so i _think_ maybe you can modify things now)

**Comment by dpryan79** [comment]
@BiocondaBot please fetch artifacts

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@BiocondaBot please merge

**Comment by AstrobioMike** [comment]
thank you, @dpryan79!

Last annoying request, so that there isn't forever a non-working gtotree package that will come up on windows condas, can we please remove the noarch file ("noarch/gtotree-1.7.05-hdfd78af_0.tar.bz2") from the bioconda/packages/gtotree (https://anaconda.org/bioconda/gtotree/files) anaconda channel that was put up a few days ago?

**Comment by vinisalazar** [comment]
@AstrobioMike I may be wrong but I think there are only Linux and OS X installers? This is what shows in this page: https://anaconda.org/bioconda/gtotree

**Comment by AstrobioMike** [comment]
Thanks @vinisalazar, I think that changed since last time I looked. Looks like a "broken" label was added to the noarch file, instead of deleting it, explaining why there are two install instructions listed there now.

**Comment by dpryan79** [comment]
Yes, this way any environments that already have GoToTree installed can be salvaged (if you actually delete package that are in peoples environments it makes it so they can't modify them without a LOT of issues).

**Pull request merged**
