### PR TITLE
minor version bump

### PR DESCRIPTION
**Pull request by zachcp**
* [X] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [X] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

Version bump of vsearch

### CODE REVIEW

**Comment by mdehollander** [comment]
@zachcp @bgruening 
I am not able to install this version using conda. When I do `conda install vsearch` i get version 2.0.3 and not 2.3.2. Can you confirm this?

**Comment by zachcp** [comment]
I can confirm this as well: https://anaconda.org/bioconda/vsearch/files

2.3.2 builds fine locally and passed all of the tests so I suspect an issue in the build/upload system.

**Comment by bgruening** [comment]
Let's try this one: https://github.com/bioconda/bioconda-recipes/pull/3116

**Comment by mdehollander** [comment]
Thanks @bgruening, your https://github.com/bioconda/bioconda-recipes/pull/3116 pull request just created an package for osx and linux and I am able to get it installed.

**Comment by bgruening** [comment]
Finally ... I had it blacklisted and did not remember, I'm getting old.

**Comment by bgruening** [comment]
Btw. here is the container: https://quay.io/repository/biocontainers/vsearch?tab=tags

**Comment by zachcp** [comment]
thanks @bgruening !

**Pull request merged**
