### PR TITLE
Mob suite 1.4.8

### PR DESCRIPTION
**Pull request by corburn**
* [ ] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [ ] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by tseemann** [comment]
@corburn will you include the database download step in a `build.sh` or a post-install section?

this will be needed if bioconda is installed by a system user, as individual users on the shared system don't have write access to the mob-suite folders.

**Comment by corburn** [comment]
@tseemann thanks, I'll look into it.

**Comment by corburn** [comment]
Update by e06aab9ff

**Comment by corburn** [comment]
@tseemann the merged pull request did not include a post-link script.

**Pull request closed without merging**
