### PR TITLE
PASA build to support OSX

### PR DESCRIPTION
**Pull request by nextgenusfs**
Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it. Note that if you are not already a member of the bioconda project (meaning that you can't add this label), please ping `@bioconda/core` so that your PR can be reviewed and merged (please note if you'd like to be added to the bioconda project). Please see https://github.com/bioconda/bioconda-recipes/issues/15332 for more details.

* [ ] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [ ] This PR adds a new recipe.
* [ ] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

Updated to try to support OSX -- still running into some problems locally, but I haven't been able to get anything to build OSX locally, so trying here.

### CODE REVIEW

**Comment by nextgenusfs** [comment]
Hi @dpryan79 -- looks like there was nested dependency that also doesn't support OSX `lighttpd`. 

```
$ conda create -n pasa pasa
Collecting package metadata (current_repodata.json): done
Solving environment: failed with current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - lighttpd

Current channels:

  - https://conda.anaconda.org/conda-forge/osx-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://conda.anaconda.org/bioconda/osx-64
  - https://conda.anaconda.org/bioconda/noarch
  - https://conda.anaconda.org/etetoolkit/osx-64
  - https://conda.anaconda.org/etetoolkit/noarch
  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://conda.anaconda.org/r/osx-64
  - https://conda.anaconda.org/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

```

**Comment by dpryan79** [comment]
There's one in the default channel, it was used on circleci: https://circleci.com/gh/bioconda/bioconda-recipes/80772?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link

**Comment by nextgenusfs** [comment]
Hmm, any ideas as to look at why its not picking up this on my Mac? I've tried channel_priorty: flexible and strict with same behavior. 
```
$ cat .condarc 
channels:
  - conda-forge
  - bioconda
  - etetoolkit
  - defaults
  - r
channel_priority: strict
```
```
$ conda info

     active environment : base
    active env location : /Users/jon/miniconda3
            shell level : 1
       user config file : /Users/jon/.condarc
 populated config files : /Users/jon/.condarc
          conda version : 4.7.12
    conda-build version : not installed
         python version : 3.7.3.final.0
       virtual packages : 
       base environment : /Users/jon/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/osx-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://conda.anaconda.org/etetoolkit/osx-64
                          https://conda.anaconda.org/etetoolkit/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://conda.anaconda.org/r/osx-64
                          https://conda.anaconda.org/r/noarch
          package cache : /Users/jon/miniconda3/pkgs
                          /Users/jon/.conda/pkgs
       envs directories : /Users/jon/miniconda3/envs
                          /Users/jon/.conda/envs
               platform : osx-64
             user-agent : conda/4.7.12 requests/2.22.0 CPython/3.7.3 Darwin/18.7.0 OSX/10.14.6
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

**Comment by nextgenusfs** [comment]
I was able to get it to work by adding the `anaconda` channel.  I guess I'm confused that the `anaconda` channel is different than the `defaults` channel.
```
conda config --append channels anaconda
```

**Pull request merged**
