### PR TITLE
Update macs2 to 2.2.4

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`macs2`](https://bioconda.github.io/recipes/macs2/README.html): **2.1.4** &rarr; **2.2.4**

[install with bioconda](http://bioconda.github.io/recipes/macs2/README.html) [Conda](https://anaconda.org/bioconda/macs2/files)

Info | Link
-----|-----
Recipe | [`recipes/macs2`](https://github.com//bioconda/bioconda-recipes/tree/bump/macs2/recipes/macs2) (click to view/edit other files)
Releases |[https://pypi.org/pypi/MACS2/json](https://pypi.org/pypi/MACS2/json)

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by tseemann** [comment]
@taoliu can you advise what deps have changed in 2.2.4  ?

**Comment by taoliu** [comment]
@tseemann To build it, you need setuptools (>=41)+Python 3(>=3.5)+Numpy(>=1.17), previously Python2+setup tools+Numpy+Cython. To run it, it needs Python 3(>=3.5)+Numpy(>=1.17).

**Comment by dpryan79** [comment]
@taoliu Does any of the C/Cython code compile against numpy, or is that purely used by python?

**Comment by taoliu** [comment]
@dpryan79 C codes in MACS2 should be compiled against Numpy -- they need header files from numpy.

**Comment by dpryan79** [comment]
Thanks @taoliu, I think the current recipe should work then, since it uses the headers but doesn't otherwise require strict linking against numpy. Please do let us know if any users start reporting issues though!

**Comment by taoliu** [comment]
@dpryan79 No problem!

**Pull request merged**
