### PR TITLE
Update fuc to 0.8.0

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`fuc`](https://bioconda.github.io/recipes/fuc/README.html): **0.7.0** &rarr; **0.8.0**

[install with bioconda](http://bioconda.github.io/recipes/fuc/README.html) [Conda](https://anaconda.org/bioconda/fuc/files)

Info | Link
-----|-----
Recipe | [`recipes/fuc`](https://github.com//bioconda/bioconda-recipes/tree/bump/fuc/recipes/fuc) (click to view/edit other files)
Releases |[https://pypi.org/pypi/fuc/json](https://pypi.org/pypi/fuc/json)
Recipe Maintainer(s) | @sbslee

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by sbslee** [comment]
@bioconda/core,

A new dependency (`pysam`) has been added in the 0.8.0 version, so the `recipes/fuc/meta.yaml` file must be updated to:

```
requirements:
  host:
    - pip
    - python
  run:
    - biopython
    - lxml
    - matplotlib-base
    - numpy
    - pandas
    - pyranges
    - pysam
    - python
    - seaborn
```

I think that's why the `bioconda-test` command failed. Please correct me if I'm wrong (the error message from CircleCI wasn't too clear on this):

```
06:22:44 BIOCONDA ERROR COMMAND FAILED (exited with 1): docker run -t --net host --rm -v /tmp/tmp7mxvs057/build_script.bash:/opt/build_script.bash -v /home/circleci/project/miniconda/conda-bld/:/opt/host-conda-bld -v /home/circleci/project/recipes/fuc:/opt/recipe -e LANG=en_US.UTF-8 -e HOST_USER_ID=1001 quay.io/bioconda/bioconda-utils-build-env-cos7:0.17.5 /bin/bash /opt/build_script.bash

06:22:44 BIOCONDA ERROR BUILD FAILED recipes/fuc
06:22:44 BIOCONDA INFO (COMMAND) conda build purge
06:22:45 BIOCONDA ERROR BUILD SUMMARY: of 1 recipes, 1 failed and 0 were skipped. Details of recipes and environments follow.
06:22:45 BIOCONDA ERROR BUILD SUMMARY: FAILED recipe recipes/fuc
```

Anyways, could you please guide me on how I can make the necessary change (i.e. add `pysam` to `meta.yaml`) for this pull request? Or should I create my own separate pull request, just like when I first added the recipe?

**Comment by dpryan79** [comment]
@sbslee I've sent you an invite to join the Bioconda project. Once you accept it you'll be able to edit these PRs :)

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@sbslee Would you like to perform the merge? The procedure is to start a comment with "@bioconda-bot please merge".

**Comment by sbslee** [comment]
@dpryan79, I'd be honored to do it myself :)

**Comment by sbslee** [comment]
@bioconda-bot please merge

**Pull request merged**
