### PR TITLE
WIP: tssar

### PR DESCRIPTION
**Pull request by HassanAmr**
* [x] I have read the guidelines above.
* [x] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by HassanAmr** [comment]
Hi @bgruening,
I need some help with this error:
```
+ ./install.sh
/Users/Hassan/miniconda2/conda-bld/tssar_1488507694794/work/TSSAR_1.0.1/conda_build.sh: line 4: ./install.sh: Permission denied
Traceback (most recent call last):
  File "/Users/Hassan/miniconda2/bin/conda-build", line 6, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "/Users/Hassan/miniconda2/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 322, in main
    execute(sys.argv[1:])
  File "/Users/Hassan/miniconda2/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 313, in execute
    noverify=args.no_verify)
  File "/Users/Hassan/miniconda2/lib/python2.7/site-packages/conda_build/api.py", line 97, in build
    need_source_download=need_source_download, config=config)
  File "/Users/Hassan/miniconda2/lib/python2.7/site-packages/conda_build/build.py", line 1493, in build_tree
    config=config)
  File "/Users/Hassan/miniconda2/lib/python2.7/site-packages/conda_build/build.py", line 1132, in build
    utils.check_call_env(cmd, env=env, cwd=src_dir)
  File "/Users/Hassan/miniconda2/lib/python2.7/site-packages/conda_build/utils.py", line 611, in check_call_env
    return _func_defaulting_env_to_os_environ(subprocess.check_call, *popenargs, **kwargs)
  File "/Users/Hassan/miniconda2/lib/python2.7/site-packages/conda_build/utils.py", line 607, in _func_defaulting_env_to_os_environ
    return func(_args, **kwargs)
  File "/Users/Hassan/miniconda2/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/bin/bash', '-x', '-e', '/Users/Hassan/miniconda2/conda-bld/tssar_1488507694794/work/TSSAR_1.0.1/conda_build.sh']' returned non-zero exit status 1
```

**Comment by bgruening** [comment]
The error is here: https://travis-ci.org/bioconda/bioconda-recipes/jobs/207230697#L528

**Comment by bgruening** [comment]
Some wired `cp` or `mv` commands: mv: cannot stat `/opt/conda/conda-bld/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/libcrypto.so.1.0.0-tmp': No such file or directory

**Comment by HassanAmr** [comment]
@bgruening,
I can't use the install script :( I keep getting the error. 
So, should I do a package for skellam? or try to install it some other way?
Also, the test will always fail because the binary returns 1 when checking help.

**Comment by bgruening** [comment]
Separate package seems to be ok, no?
Test you can solve with some bash magic. For example `foo --help | grep "something that is in the help text"`. This will give you the return code of the grep back.

**Comment by bgruening** [comment]
I think creating a new package for skellam with the r skeleton generator is way more easy :)

**Comment by HassanAmr** [comment]
Sorry, I thought since it worked locally, it will also work on travis.
I'm creating a package for skellam now.

**Comment by HassanAmr** [comment]
@bgruening,
I can't make sense of this error:
`/opt/conda/conda-bld/test_tmp/run_test.sh: /opt/conda/conda-bld/_t_env/bin/TSSAR: /usr/bin/perl: bad interpreter: No such file or directory`

**Comment by bgruening** [comment]
This means that some perl script has a sheabng that looks like `#!/usr/bin/perl` instead of `#!/usr/bin/env perl`

**Comment by HassanAmr** [comment]
Thanks!
I was completely lost in a very different solution thread, and yet it is so simple :)

**Pull request merged**
