### PR TITLE
Adding RNA-SeQC v1.1.8

### PR DESCRIPTION
**Pull request by holtgrewe**
* [x] I have read the guidelines above.
* [x] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by holtgrewe** [comment]
@bioconda/core The software is published by Getz et al. from Broad but has no license but is freely available online. How do we deal with this?

**Comment by bgruening** [comment]
@holtgrewe no procedure yet. Can you ask upstream. No license means in theory that we are not allowed to use and redistribute it.

**Comment by holtgrewe** [comment]
I'm trying to ask the author but he has moved labs. The last author is Gad Getz and I guess we will not get a reply from him...

**Comment by bgruening** [comment]
Thanks for trying!

**Comment by dsdeluca** [comment]
Hi Folks,

I am the author of RNA-SeQC. I think it is a great idea to put RNA-SeQC into bioconda. Thanks for the contribution. 

Best,

David DeLuca

_BREATH - Biomedical Research in Endstage and Obstructive Lung Disease Hannover
German Center for Lung Research
Hannover Medical School
Carl-Neuberg-Str. 1
30625 Hannover, Germany_

**Comment by holtgrewe** [comment]
@dsdeluca Thanks!

**Pull request merged**
