### PR TITLE
Add plassembler recipe

### PR DESCRIPTION
**Pull request by gbouras13**
I would like to add my program plassembler, which is a program that is designed to assemble bacterial plasmids from hybrid sequencing data (Oxford Nanopore and short read).

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by gbouras13** [comment]
@BiocondaBot please add label

**Comment by gbouras13** [comment]
Made some minor changes to the release after it passed checks, should be good to go now.

**Review by priesgo — APPROVED** [review]
I would recommend specifying the versions of the dependencies, at least the lower boundary, ideally lower and upper boundaries. But this is not a requirement for bioconda, so I'm approving it.

**Comment by shenwei356** [comment]
Could you please merge all the commits into one?

**Comment by gbouras13** [comment]
@shenwei356 I have done this in this commit [45cc97a53a2acad11764eed9680fd319abfe6e88](https://github.com/bioconda/bioconda-recipes/pull/38523/commits/45cc97a53a2acad11764eed9680fd319abfe6e88)  - I'm a pretty novice git user & have never done this before so please let me know if that does not suffice

**Comment by shenwei356** [comment]
Hi George, it would be easy if you just [recreated a new branch](https://bioconda.github.io/contributor/workflow.html#id2) with the final version of the plassembler recipe files, and also open another pull request. 

I also notice the  `recipes/unifrac-binaries/meta.yaml` is changed unexpectedly in the updated PR.

**Pull request closed without merging**
