### PR TITLE
RSEM Bump for R3.6.1

### PR DESCRIPTION
**Pull request by apeltzer**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [ ] This PR adds a new recipe.
* [ ] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by dpryan79** [comment]
I don't think this actually needs to be pinned against any R version, since it appears to be a purely run-time dependency.

**Comment by apeltzer** [comment]
Yeah I just tried installing it alongside some R packages and got an incompatibility notice so thought to get this off the blacklist and make it work with R3.6.1 would be good :+1:

**Comment by apeltzer** [comment]
`ValueError: License file given in about/license_file (/opt/recipe/LICENSE) does not exist in source root dir or in recipe root dir (with meta.yaml)`

**Comment by dpryan79** [comment]
We should make sure that the R scripts are picked up as having a prefix in them before merging this.

**Comment by dpryan79** [comment]
They're listed in the `has_prefix` file, so this should work and never again need to be rebuilt for R :)

**Pull request merged**
