### PR TITLE
Prune msisensor-pro requirements and fix macOS build

### PR DESCRIPTION
**Pull request by jmarshall**
The existing recipe has `‑L$PREFIX/lib` in `LDFLAGS` prior to _cpp/makefile_'s addition of `‑L$SRC_DIR/vendor/htslib-1.11`. Hence despite appearances and contrary to the discussion in PR #29518, the existing package in fact uses bioconda's htslib package, not the bundled 1.11.

Clarify this by patching _cpp/makefile_ not to add `vendor/htslib-1.11` paths; in particular, remove the `‑Wl,-rpath=...` that caused the macOS build to fail (`=` should have been `,`). Simplify _build.sh_ accordingly.

Work around samtools/htslib#1464 by patching _cpp/bamreader.cpp_ to ignore `register` _in htslib/ksort.h_, as this is not compatible with C++17.

Remove now-spurious `build` requirements. Remove `host`/`run` requirements that are really htslib requirements. In particular, this package does not depend directly on libdeflate.

----

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by jmarshall** [comment]
@BiocondaBot please fetch artifacts

**Comment by jmarshall** [comment]
@BiocondaBot please add label

**Review by daler — APPROVED** [review]

**Comment by daler** [comment]
Thanks @jmarshall

**Comment by daler** [comment]
@BiocondaBot please merge

**Pull request merged**
