### PR TITLE
Update subread to 1.6.0

### PR DESCRIPTION
**Pull request by lparsons**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by daler** [comment]
@lparsons I don't think we need to keep the subdirectory here, just updating the existing recipe is fine. The older version of the package remains in the channel.

**Comment by daler** [comment]
And thanks for updating this so soon after the release!

**Comment by lparsons** [comment]
@daler Removed the subdir. I ran into a segfault on the old version of `featureCounts`, which appears to be resolved in 1.6.0, thus the quick upgrade. :wink:

Are we good to merge this?

**Comment by daler** [comment]
Looks good, merge when green!

**Pull request merged**
