### PR TITLE
Update gneiss to 0.4.5

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`gneiss`](https://bioconda.github.io/recipes/gneiss/README.html): **0.4.4** &rarr; **0.4.5**

[install with bioconda](http://bioconda.github.io/recipes/gneiss/README.html) [Conda](https://anaconda.org/bioconda/gneiss/files)

Info | Link
-----|-----
Recipe | [`recipes/gneiss`](https://github.com//bioconda/bioconda-recipes/tree/bump/gneiss/recipes/gneiss) (click to view/edit other files)
Releases |[https://pypi.org/pypi/gneiss/json](https://pypi.org/pypi/gneiss/json)

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/updating.html)).

### CODE REVIEW

**Comment by mortonjt** [comment]
Looks like the recipe is out of date.   The following line should't be there

https://github.com/bioconda/bioconda-recipes/blob/bump/gneiss/recipes/gneiss/meta.yaml#L56

**Comment by mortonjt** [comment]
Just added another PR here to remove gneiss.sim tests. #16252

I think this should be ready for review.

**Comment by dpryan79** [comment]
No longer needed

**Comment by mortonjt** [comment]
Thanks!

**Pull request closed without merging**
