### PR TITLE
Patch mummerplot to work with gnuplot 5

### PR DESCRIPTION
**Pull request by peterjc**
Patch is based on changes in mummerplot v4 to cope with being run on gnuplot 5, with a tweak to still work on older versions of gnuplot. See also: https://github.com/mummer4/mummer/pull/64

* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [X] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [X] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by peterjc** [comment]
OK, some linting required?

```
                        failed_tests
recipe                              
recipes/mummer  [uses_perl_threaded]
```

**Comment by peterjc** [comment]
I've not used patches much with BioConda before, this may be something silly on my part:

```
Source cache directory is: /opt/conda/conda-bld/src_cache
Downloading source to cache: MUMmer3.23.tar.gz
Downloading https://downloads.sourceforge.net/project/mummer/mummer/3.23/MUMmer3.23.tar.gz
Success
Extracting download
Applying patch: '/opt/recipe/patches/gnuplot_mouse_clipboardformat.patch'
Warning: failed to download source.  If building, will try again after downloading recipe dependencies.
Error was: 
Command '['/usr/bin/patch', '-p0', '-i', '/opt/recipe/patches/gnuplot_mouse_clipboardformat.patch']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/opt/conda/bin/conda-build", line 6, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "/opt/conda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 342, in main
    execute(sys.argv[1:])
  File "/opt/conda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 333, in execute
    noverify=args.no_verify)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/api.py", line 97, in build
    need_source_download=need_source_download, config=config)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/build.py", line 1524, in build_tree
    config=config)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/build.py", line 1064, in build
    assert not need_source_download, "Source download failed.  Please investigate."
AssertionError: Source download failed.  Please investigate.
```

**Comment by peterjc** [comment]
Progress,

```
Source cache directory is: /opt/conda/conda-bld/src_cache
Downloading source to cache: MUMmer3.23.tar.gz
Downloading https://downloads.sourceforge.net/project/mummer/mummer/3.23/MUMmer3.23.tar.gz
Success
Extracting download
Applying patch: '/opt/recipe/patches/gnuplot_mouse_clipboardformat.patch'
Patch level ambiguous, selecting least deep
Warning: failed to download source.  If building, will try again after downloading recipe dependencies.
Error was: 
Command '['/usr/bin/patch', '-p0', '-i', '/opt/recipe/patches/gnuplot_mouse_clipboardformat.patch']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/opt/conda/bin/conda-build", line 6, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "/opt/conda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 342, in main
    execute(sys.argv[1:])
  File "/opt/conda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 333, in execute
    noverify=args.no_verify)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/api.py", line 97, in build
    need_source_download=need_source_download, config=config)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/build.py", line 1524, in build_tree
    config=config)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/build.py", line 1064, in build
    assert not need_source_download, "Source download failed.  Please investigate."
AssertionError: Source download failed.  Please investigate.
```

**Comment by peterjc** [comment]
Simple once I could see my error, I was missing the file extension in the patch header.

New error:

```
13:38:51 BIOCONDA ERROR COMMAND FAILED: mulled-build build-and-test mummer=3.23--pl5.22.0_5 -n biocontainers --test mummer -h &> /dev/null && mummerplot -h &> /dev/null && nucmer -h &> /dev/null && promer -h &> /dev/null && show-aligns -h &> /dev/null --extra-channels file:///home/circleci/project/miniconda/conda-bld,conda-forge,defaults
13:38:51 BIOCONDA ERROR STDOUT+STDERR:
involucro -v=2 -f /home/circleci/project/miniconda/lib/python3.6/site-packages/galaxy/tools/deps/mulled/invfile.lua -set CHANNELS='bioconda,file:///home/circleci/project/miniconda/conda-bld,conda-forge,defaults' -set TEST='mummer -h &> /dev/null && mummerplot -h &> /dev/null && nucmer -h &> /dev/null && promer -h &> /dev/null && show-aligns -h &> /dev/null' -set TARGETS='mummer=3.23=pl5.22.0_5' -set REPO='quay.io/biocontainers/mummer:3.23--pl5.22.0_5' -set BINDS='build/dist:/usr/local/,/home/circleci/project/miniconda/conda-bld:/home/circleci/project/miniconda/conda-bld' build-and-test
.[May 23 13:37:51] DEBU Run file [/home/circleci/project/miniconda/lib/python3.6/site-packages/galaxy/tools/deps/mulled/invfile.lua]
[May 23 13:37:51] INFO Invoke Task [build]
[May 23 13:37:51] STEP Run image [continuumio/miniconda3:latest] with command [[rm -rf /data/dist]]
[May 23 13:37:51] DEBU Creating container [step-1414b437f3]
[May 23 13:37:51] DEBU Created container [8e7962b57314 step-1414b437f3], starting it
[May 23 13:37:51] DEBU Container [8e7962b57314 step-1414b437f3] started, waiting for completion
[May 23 13:37:51] DEBU Container [8e7962b57314 step-1414b437f3] completed with exit code [0] as expected
[May 23 13:37:51] DEBU Container [8e7962b57314 step-1414b437f3] removed
[May 23 13:37:51] STEP Run image [continuumio/miniconda3:latest] with command [[/bin/sh -c conda install  -c bioconda -c file:///home/circleci/project/miniconda/conda-bld -c conda-forge -c defaults  mummer=3.23=pl5.22.0_5 -p /usr/local --copy --yes --quiet]]
[May 23 13:37:51] DEBU Creating container [step-01933559d5]
[May 23 13:37:51] DEBU Created container [2d8451ef4c8a step-01933559d5], starting it
[May 23 13:37:51] DEBU Container [2d8451ef4c8a step-01933559d5] started, waiting for completion
[May 23 13:38:14] SOUT 
[May 23 13:38:21] SOUT 
[May 23 13:38:21] SOUT Package plan for installation in environment /usr/local:
[May 23 13:38:21] SOUT 
[May 23 13:38:21] SOUT The following NEW packages will be INSTALLED:
[May 23 13:38:21] SOUT 
[May 23 13:38:21] SOUT mummer: 3.23-pl5.22.0_5 file:///home/circleci/project/miniconda/conda-bld
[May 23 13:38:21] SOUT perl:   5.22.0.1-0      conda-forge
[May 23 13:38:21] SOUT 
[May 23 13:38:21] DEBU Container [2d8451ef4c8a step-01933559d5] completed with exit code [0] as expected
[May 23 13:38:21] DEBU Container [2d8451ef4c8a step-01933559d5] removed
[May 23 13:38:21] STEP Wrap [build/dist] as [quay.io/biocontainers/mummer:3.23--pl5.22.0_5]
[May 23 13:38:21] DEBU Creating container [step-a22bd4682d]
[May 23 13:38:21] DEBU Image [bgruening/busybox-bash:0.1] not present, pulling it
[May 23 13:38:21] DEBU Pull Image [bgruening/busybox-bash:0.1]
[May 23 13:38:24] DEBU Packing succeeded
[May 23 13:38:25] INFO Invoke Task [singularity]
[May 23 13:38:25] WARN Invoked Stepless Task [singularity]
[May 23 13:38:25] INFO Invoke Task [cleanup]
[May 23 13:38:25] STEP Run image [continuumio/miniconda3:latest] with command [[rm -rf /data/dist]]
[May 23 13:38:25] DEBU Creating container [step-11c63e7024]
[May 23 13:38:26] DEBU Created container [d0cfe62d9524 step-11c63e7024], starting it
[May 23 13:38:26] DEBU Container [d0cfe62d9524 step-11c63e7024] started, waiting for completion
[May 23 13:38:26] DEBU Container [d0cfe62d9524 step-11c63e7024] completed with exit code [0] as expected
[May 23 13:38:26] DEBU Container [d0cfe62d9524 step-11c63e7024] removed
[May 23 13:38:26] INFO Invoke Task [test]
[May 23 13:38:26] STEP Run image [quay.io/biocontainers/mummer:3.23--pl5.22.0_5] with command [[mummer -h &> /dev/null && mummerplot -h &> /dev/null && nucmer -h &> /dev/null && promer -h &> /dev/null && show-aligns -h &> /dev/null]]
[May 23 13:38:26] DEBU Creating container [step-775185a7e4]
[May 23 13:38:26] DEBU Created container [344e3721de39 step-775185a7e4], starting it
[May 23 13:38:26] DEBU Container [344e3721de39 step-775185a7e4] started, waiting for completion
[May 23 13:38:26] ERRO Task processing failed: Unexpected exit code [127] of container [344e3721de39 step-775185a7e4], container preserved



13:39:48 BIOCONDA ERROR TEST FAILED: recipes/mummer, CONDA_ALLOW_SOFTLINKS=false;CONDA_BAMTOOLS=2.4.1;CONDA_BOOST=1.64;CONDA_BZIP2=1.0;CONDA_GMP=5.1;CONDA_GSL=1.16;CONDA_HDF5=1.8.17;CONDA_HTSLIB=1.7;CONDA_NCURSES=5.9;CONDA_NPY=112;CONDA_PERL=5.22.0;CONDA_PY=27;CONDA_R=3.4.1;CONDA_ROOT=/home/circleci/project/miniconda;CONDA_XZ=5.2;CONDA_ZLIB=1.2.11;LANG=en_US.UTF-8;MACOSX_DEPLOYMENT_TARGET=10.9
13:39:49 BIOCONDA ERROR BUILD SUMMARY: of 1 recipes, 1 failed and 0 were skipped. Details of recipes and environments follow.
13:39:49 BIOCONDA ERROR BUILD SUMMARY: FAILED recipe mummer-3.23-pl5.22.0_5.tar.bz2, environment CONDA_PY=27;CONDA_HTSLIB=1.7;CONDA_BOOST=1.64;CONDA_R=3.4.1;CONDA_PERL=5.22.0;CONDA_NPY=112;CONDA_NCURSES=5.9;CONDA_GSL=1.16;CONDA_GMP=5.1;CONDA_HDF5=1.8.17;MACOSX_DEPLOYMENT_TARGET=10.9;CONDA_ZLIB=1.2.11;CONDA_BZIP2=1.0;CONDA_XZ=5.2;CONDA_BAMTOOLS=2.4.1
Exited with code 1
```

**Comment by peterjc** [comment]
Bingo, the final test command ``show-aligns -h`` is failing as follows:

```
SERR show-aligns: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory
```

**Comment by bgruening** [comment]
This usually indicates that you are missing libgcc somewhere.

**Comment by peterjc** [comment]
OK, this should be ready to review now - should I clean up the commit history, or leave it be?

**Pull request merged**
