### PR TITLE
Update Fiji build

### PR DESCRIPTION
**Pull request by lldelisle**
I realized that the preferences of Fiji are stored globally for the user. Therefore they are not isolated in the conda environment. To prevent this. I propose to set a new directory for preferences within the CONDA_PREFIX directory to not interefere with other java/Fiji.

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by lldelisle** [comment]
@BiocondaBot please add label

**Comment by k-dominik** [comment]
just a comment: I think it's super awesome that bioconda fiji will not pollute "global" user settings anymore!!!

**Review by bgruening — APPROVED** [review]

**Comment by lldelisle** [comment]
@bgruening what should I do with the test?

**Comment by lldelisle** [comment]
Oups this is not working... Please do not merge.

**Comment by bgruening** [comment]
@BiocondaBot please fetch artifacts

**Comment by lldelisle** [comment]
I don't know how to do...
The issue is that when I set in the config file:
`-Djava.util.prefs.userRoot=${CONDA_PREFIX}/uprefs/`, it does not evaluate `${CONDA_PREFIX}` therefore it creates a folder `${CONDA_PREFIX}/uprefs`...
Is there any java/ImageJ expert that could help me?

**Comment by bgruening** [comment]
You can try to use "`which fiji`../uprefs/" to get the path instead of using CONDA_PREFIX (which will not exist in a container )

**Comment by lldelisle** [comment]
It is not interpreted:
```
java -Djava.util.prefs.userRoot=`which\ ImageJ`/../../uprefs/
```

**Comment by bgruening** [comment]
Do it in a bash wrapper around the java call, this might work.

**Comment by lldelisle** [comment]
I can try.

**Comment by lldelisle** [comment]
I think this works.

**Comment by lldelisle** [comment]
@bgruening can you check it is 'container-compatible'?

**Comment by lldelisle** [comment]
Is it better to copy the bash file to `$outdir` and then create a symlink like bunwarpj?

**Comment by lldelisle** [comment]
@BiocondaBot please fetch artifacts

**Comment by lldelisle** [comment]
I will have a fresh look at it tomorrow.
I think now it works. I still have 3 questions before the merge:
1. Is it container compatible?
2. > Is it better to copy the bash file to $outdir and then create a symlink like bunwarpj?
3. What do I do with the test on memory which for the moment is useless as it does not do what we were expecting but still pass...

**Comment by lldelisle** [comment]
For me it is good.
Just the 2 questions regarding tests and symlink or copy.

**Comment by bgruening** [comment]
> Is it better to copy the bash file to $outdir and then create a symlink like bunwarpj?

I guess this is some Java recommendation. Not strictly needed, but maybe nice to have.

If the test is not working, let's remove it.

**Comment by lldelisle** [comment]
Where can we see if the run_test.sh is running? I only see the other tests: https://dev.azure.com/bioconda/bioconda-recipes/_build/results?buildId=19319&view=logs&j=e14e69ff-a0ae-55c4-b71d-229b239cfb2f&t=7df82132-b284-504b-53d6-7d3e63519572&l=1962

**Comment by lldelisle** [comment]
For me it is fine. You can merge.

**Comment by simonbray** [comment]
@BiocondaBot please merge

**Comment by lldelisle** [comment]
Thank you very much

**Comment by lldelisle** [comment]
I need to use fiji for another recipe and I want only from this built. Is there a way to specify as dependency:
fiji>=20220414 but not built [h527b516_0](https://anaconda.org/bioconda/fiji/20220414/download/osx-64/fiji-20220414-h527b516_0.tar.bz2) nor [h9ee0642_0](https://anaconda.org/bioconda/fiji/20220414/download/linux-64/fiji-20220414-h9ee0642_0.tar.bz2)
?
Thanks

**Pull request merged**
