### PR TITLE
add recipe for spaTyper

### PR DESCRIPTION
**Pull request by rpetit3**
Add new recipe for spaTyper (https://github.com/HCGB-IGTP/spaTyper) a tool for finding spa types.

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by rpetit3** [comment]
@BiocondaBot please fetch artifacts

**Comment by rpetit3** [comment]
Testing:
```
conda create -y -n spatyper -c conda-forge -c bioconda  -c https://136024-42372094-gh.circle-artifacts.com/0/tmp/artifacts/packages spatyper
conda activate spatyper
spaTyper --help
usage: spaTyper [-h] [-r REPEAT_FILE] [-o REPEAT_ORDER_FILE] [-d FOLDER] [-f FASTA [FASTA ...]] [-g GLOB] [-e] [--version] [--debug] [--info]

spaTyper.py: Get spa types

Version: 0.3
License: GPLv3

USAGE: python spaTyper.py -f fasta_file.fasta
Prints spa type to stdout
..truncated...

spaTyper --version
spaTyper 0.2.1

spaTyper -f contgs.fasta
Start the identification of repeats in Spa protein:
+ Check or download repeats fasta file in folder:  /home/rpetit/miniconda3/envs/spatyper/bin
+ Check or download repeats types file in folder:  /home/rpetit/miniconda3/envs/spatyper/bin

-----------------
Results:
-----------------
Sequence name:  NODE_9_length_139906_cov_50.416415 Repeats: 07-23-12-21-12-17-20-17-12-12-17 Repeat Type: t148

Sequence name:  NODE_21_length_36657_cov_56.067510 Repeats: 17 Repeat Type: 17


spaTyper -f NRS408.fna
Start the identification of repeats in Spa protein:
+ Check or download repeats fasta file in folder:  /home/rpetit/miniconda3/envs/spatyper/bin
        A previous download created sparepeats.fasta on: 2021-01-05 00:10:44
+ Check or download repeats types file in folder:  /home/rpetit/miniconda3/envs/spatyper/bin
        A previous download created spatypes.txt on: 2021-01-05 00:12:01

-----------------
Results:
-----------------
Sequence name:  gnl|contig00002|NRS408 len=283631 cov=73.6 corr=0 origname=Contig_19_73.5651_pilon sw=shovill-skesa/1.0.7 date=20191101 Repeats: 26-23-17-12-17-16 Repeat Type: t062
```

looks like everything worked fine

**Comment by rpetit3** [comment]
@BiocondaBot please add label

**Review by evolarjun — APPROVED** [review]
Tried it and it seems to be working for me as well.

**Pull request merged**
