### PR TITLE
[MRG] bowtie: added osx compatibility

### PR DESCRIPTION
**Pull request by croth1**
Building bowtie from the source makes it possible to offer osx compatibility.

### CODE REVIEW

**Comment by johanneskoester** [comment]
Very nice! Do you mind adding a ``gcc`` build dependency as well?

**Comment by croth1** [comment]
Uh, this does not seem to work. Conda is pulling in  `gcc-4.8.5-3` and `libgcc: 4.8.5-1` but then fails due to missing header files.

```
/Users/ch/miniconda/envs/_build/gcc/include/c++/cwchar:44:19: fatal error: wchar.h: No such file or directory
 #include <wchar.h>
                   ^
compilation terminated.
In file included from tinythread.cpp:25:0:
tinythread.h:80:23: fatal error: pthread.h: No such file or directory
   #include <pthread.h>
```

Building with my homebrew gcc-5 works however. That's weird. Any idea why conda does not ship those header files? Am i missing something obvious?

**Comment by johanneskoester** [comment]
That's strange. Does it help to set the include path to
$PREFIX/include?
See here how to do this:
http://www.network-theory.co.uk/docs/gccintro/gccintro_23.html

**Comment by croth1** [comment]
I think the problem lies much deeper, but I am not understanding it yet. If I run `gcc -v` on conda's gcc I get:
```
+ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/Users/ch/miniconda/envs/_build/gcc/libexec/gcc/x86_64-apple-darwin11.4.2/4.8.5/lto-wrapper
Target: x86_64-apple-darwin11.4.2
Configured with: ./configure --prefix=/Users/ch/miniconda/envs/_build/gcc --with-gxx-include-dir=/Users/ch/miniconda/envs/_build/gcc/include/c++ --bindir=/Users/ch/miniconda/envs/_build/bin --datarootdir=/Users/ch/miniconda/envs/_build/share --libdir=/Users/ch/miniconda/envs/_build/lib --with-gmp=/Users/ch/miniconda/envs/_build --with-mpfr=/Users/ch/miniconda/envs/_build --with-mpc=/Users/ch/miniconda/envs/_build --with-isl=/Users/ch/miniconda/envs/_build --with-cloog=/Users/ch/miniconda/envs/_build --with-boot-ldflags='-Wl,-headerpad_max_install_names -Wl,-L/Users/ch/miniconda/envs/_build/lib -Wl,-L/usr/lib' --with-stage1-ldflags='-Wl,-headerpad_max_install_names -Wl,-L/Users/ch/miniconda/envs/_build/lib -Wl,-L/usr/lib' --enable-checking=release --with-tune=generic --disable-multilib
Thread model: posix
gcc version 4.8.5 (GCC)
```

If I do the same on my gcc-5 I get:
```
Using built-in specs.
COLLECT_GCC=gcc-5
COLLECT_LTO_WRAPPER=/usr/local/Cellar/gcc/5.3.0/libexec/gcc/x86_64-apple-darwin15.2.0/5.3.0/lto-wrapper
Target: x86_64-apple-darwin15.2.0
Configured with: ../configure --build=x86_64-apple-darwin15.2.0 --prefix=/usr/local/Cellar/gcc/5.3.0 --libdir=/usr/local/Cellar/gcc/5.3.0/lib/gcc/5 --enable-languages=c,c++,objc,obj-c++,fortran --program-suffix=-5 --with-gmp=/usr/local/opt/gmp --with-mpfr=/usr/local/opt/mpfr --with-mpc=/usr/local/opt/libmpc --with-isl=/usr/local/opt/isl --with-system-zlib --enable-libstdcxx-time=yes --enable-stage1-checking --enable-checking=release --enable-lto --with-build-config=bootstrap-debug --disable-werror --with-pkgversion='Homebrew gcc 5.3.0' --with-bugurl=https://github.com/Homebrew/homebrew/issues --enable-plugin --disable-nls --enable-multilib --with-native-system-header-dir=/usr/include --with-sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk
Thread model: posix
gcc version 5.3.0 (Homebrew gcc 5.3.0)
```

These are the important bits: `--with-native-system-header-dir=/usr/include --with-sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk`

Homebrew grants gcc access to the native headers of xcode, conda does not. I am not sure why, though.

**Comment by johanneskoester** [comment]
Maybe to ensure portability. Conda binaries should depend on as little system libraries as possible. But I'm only guessing here. Can bowtie be build with llvm? I believe most osx packages in the anaconda channel are build with llvm/clang.

**Comment by johanneskoester** [comment]
@bioconda/core do you have any ideas on this?

**Comment by chapmanb** [comment]
I don't know anything about the gcc issues, but maybe we could use the binary on Linux and build on OSX using selectors. The UCSC recipes do this (well, in reverse -- building on Linux and binary on OSX -- but it has useful clues):

https://github.com/bioconda/bioconda-recipes/blob/master/recipes/ucsc-twobittofa/meta.yaml

**Comment by croth1** [comment]
If I understand this problem correctly, building on linux is not the problem. Since linux headers are in `/usr/include`, they will be picked up either way. It's just macos that does not ship any header files in `/usr/include` - I suppose that's why homebrew sets the native header dir explicitly.

Basically, I think this is a misconfiguration on conda's side. It makes little sense to allow linux to use system headers, but do not allow them on macos.

Not specifying gcc as a dependency should use clang on macos and native gcc on linux. We could use selectors to only specify gcc as a dependency on linux. This way clang will be the compiler of choice for OS X and everything should work.

But this is really a very dirty hack and does not target the key problem.

**Comment by johanneskoester** [comment]
What about depending on ``llvm`` for osx (which should contain clang)?

**Comment by croth1** [comment]
Updated the formula. I don't think adding `llvm` has any influence on the build. Conda seems to use native clang in this case. I guess the best we can do is to use conda's gcc for linux and fall back to the native compiler in OS X.

**Comment by johanneskoester** [comment]
I had a look at the Makefile. In fact, on osx, it will do [this](https://github.com/BenLangmead/bowtie/blob/master/Makefile#L44), which means that it shouldn't even use gcc, even if we put it in the dependencies. Instead, it will just use whatever clang is in path. Hence, putting llvm as a build dependency should ensure that the anaconda clang is used. What makes you think that the system clang is used instead?

**Comment by croth1** [comment]
Nevermind. Should be fine.

**Comment by johanneskoester** [comment]
Great!

**Comment by johanneskoester** [comment]
Can you sync the branch with master before merging?

**Comment by croth1** [comment]
Should be ready for a final review.

**Pull request merged**
