### PR TITLE
Add meskit recipe

### PR DESCRIPTION
**Pull request by Wangxin555**
Create a recipe for R Bioconductor package MesKit

### CODE REVIEW

**Comment by Wangxin555** [comment]
@BiocondaBot please add label

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
Thanks @Wangxin555!

**Comment by Wangxin555** [comment]
Hello, when can we download the MesKit package through conda?

**Comment by bkille** [comment]
> Hello, when can we download the MesKit package through conda?

@Wangxin555 Once your PR has been approved, you can merge yourself with "@BiocondaBot please merge"

**Comment by bkille** [comment]
@BiocondaBot please merge

**Pull request merged**
