### PR TITLE
Update mosdepth v0.3.4 -> v0.3.5

### PR DESCRIPTION
**Pull request by pdiakumis**
Update mosdepth from v0.3.4 to v0.3.5

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

### General instructions

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

### Instructions for avoiding API, ABI, and CLI breakage issues
Conda is able to record and lock (a.k.a. pin) dependency versions used at build time of other recipes.
This way, one can avoid that expectations of a downstream recipe with regards to API, ABI, or CLI are violated by later changes in the recipe.
If not already present in the meta.yaml, make sure to specify `run_exports` (see [here](https://bioconda.github.io/contributor/linting.html#missing-run-exports) for the rationale and comprehensive explanation).
Add a `run_exports` section like this:

```yaml
build:
  run_exports:
    - ...

```

with `...` being one of:

| Case                             | run_exports statement                                               |
| -------------------------------- | ------------------------------------------------------------------- |
| semantic versioning              | `{{ pin_subpackage("myrecipe", max_pin="x") }}`     |
| semantic versioning (0.x.x)      | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}`   |
| known breakage in minor versions | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| known breakage in patch versions | `{{ pin_subpackage("myrecipe", max_pin="x.x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| calendar versioning              | `{{ pin_subpackage("myrecipe", max_pin=None) }}`    |

while replacing `"myrecipe"` with either `name` if a `name|lower` variable is defined in your recipe or with the lowercase name of the package in quotes.

### Bot commands for PR management

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

Note that the <code>@BiocondaBot please merge</code> command is now depreciated. Please just squash and merge instead.

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by robsyme** [comment]
Thanks Peter, really appreciate the version bump and for the insight into the bioconda mechanism.

**Comment by brentp** [comment]
I would try: `nim <= 1.6.2` that's an older version of docopt (but can't be updated without changes to code) so maybe other versions of nim < 2 were also broken.

**Comment by pdiakumis** [comment]
Hm, no luck unfortunately, any other suggestions?

**Comment by brentp** [comment]
in the build.sh, can you add:
```
nimble install -y "docopt@0.7.0"
```

right before nimble build? I'll pin that version for future releases, but that will get it building here.

**Comment by pdiakumis** [comment]
Thanks Brent, I'll check if it has built tomorrow morning and hopefully we'll get a release out by Monday Robert.

**Comment by brentp** [comment]
Thank you! Looks like you need to bump the build number?

**Comment by pdiakumis** [comment]
Weird since that `build_number_needs_reset` means to take it back to 0. I tried bumping it to 1 and gave me the same. Then I reset it back to 0 and now I'm getting the same docopt error with OSX. Any idea if we need to release a new mosdepth tag to pull in your latest docopt pinning in the `mosdepth.nimble` file?

**Comment by pdiakumis** [comment]
I have no idea, I think it's still pulling in docopt v0.7.1 which is the problem here right?
https://dev.azure.com/bioconda/25074ded-3133-43ca-af80-895ab87b53cb/_apis/build/builds/43194/logs/42

**Comment by brentp** [comment]
is there a cache somewhere? that's running very early.

**Comment by brentp** [comment]
It still has, e.g.:
```
Installing docopt@>= 0.6.8
```
I don't know where that would be coming from.

**Comment by brentp** [comment]
can you try removing --localdeps ? If that doesn't work or give insight, I'll just tag a new mosdepth version.

**Comment by brentp** [comment]
here is the caching: https://dev.azure.com/bioconda/bioconda-recipes/_build/results?buildId=43326&view=logs&j=e14e69ff-a0ae-55c4-b71d-229b239cfb2f&t=eaabb8b3-c0e3-5e4f-7282-e06fccfa1d61

**Comment by pdiakumis** [comment]
Do you know if there's a way to empty the cache? Should I close this and open a different PR?

**Review by brentp — APPROVED** [review]

**Comment by brentp** [comment]
Looks like it is good to go. Thanks @pdiakumis

**Pull request merged**
