### PR TITLE
WIP: set packages to noarch: generic where linter has indicated they should be

### PR DESCRIPTION
**Pull request by pinin4fjords**
As part of collaboration fest, this PR attempts to add noarch: generic to build sections where a lint over all recipes suggested that line should be present.

### CODE REVIEW

**Comment by dpryan79** [comment]
@pinin4fjords Can you grant us access to modify this? There should be a tick-box to allow that somewhere to the right of this comment.

**Comment by dpryan79** [comment]
@bgruening We'll have to think about how best to do this. We need to bump build numbers, but I expect half of these haven't been changed to noarch (or otherwise fixed) because they're just not used/updated.

**Comment by pinin4fjords** [comment]
'Allow edits from maintainers' is checked @dpryan79 - you really can't edit?

**Comment by dpryan79** [comment]
@pinin4fjords Not from the command line. I presumably can via the web interface, but if I'm going to clean up the recipes more I might as well do it all the way. Can you push it instead to a branch instead of your fork?

**Comment by dpryan79** [comment]
I've made a new branch on this repo with your changes and some of my own.

**Comment by dpryan79** [comment]
Xref: https://github.com/bioconda/bioconda-recipes/pull/17783

**Comment by pinin4fjords** [comment]
Okay @dpryan79 - I also pushed the branch to upstream

**Comment by dpryan79** [comment]
Closed by #17783, thanks!

**Pull request closed without merging**
