### PR TITLE
FSA recipe

### PR DESCRIPTION
**Pull request by edgano**
:information_source:
If this is your first pull request to Bioconda please ping `@bioconda/core` so it can be reviewed and to request being added as a member of the Bioconda team. Members of the Bioconda team are able to merge their own pull requests once tests and linting have passed.

----------------

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by epruesse** [comment]
@edgano - Do you want me to merge this?

**Comment by edgano** [comment]
@epruesse yes! It's ready to merge :smile:

**Comment by npavlovikj** [comment]
@BiocondaBot recheck

**Comment by epruesse** [comment]
@biocondabot merge

**Pull request merged**
