### PR TITLE
Update metabat2 to 2.14

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`metabat2`](https://bioconda.github.io/recipes/metabat2/README.html): **2.13** &rarr; **2.14**

[install with bioconda](http://bioconda.github.io/recipes/metabat2/README.html) [Conda](https://anaconda.org/bioconda/metabat2/files)

Info | Link
-----|-----
Recipe | [`recipes/metabat2`](https://github.com//bioconda/bioconda-recipes/tree/bump/metabat2/recipes/metabat2) (click to view/edit other files)
Releases |[https://bitbucket.org/berkeleylab/metabat/downloads/?tab=tags](https://bitbucket.org/berkeleylab/metabat/downloads/?tab=tags)

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by mdehollander** [comment]
Adding autoconf to the build requirements still gives an error on CI, but it is at least the same as I get locally:

```
14:21:21 BIOCONDA INFO (OUT) /opt/conda/conda-bld/metabat2_1569853062548/_build_env/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: ../contrib/htslib-install/lib/libhts.a(cram_io.o):cram_io.c:(.text.itf8_decode_crc+0x303): more undefined references to `libdeflate_crc32' follow
14:21:21 BIOCONDA INFO (OUT) collect2: error: ld returned 1 exit status
14:21:21 BIOCONDA INFO (OUT) make[2]: *** [src/jgi_summarize_bam_contig_depths] Error 1
14:21:21 BIOCONDA INFO (OUT) make[2]: Leaving directory `$SRC_DIR/build'
14:21:21 BIOCONDA INFO (OUT) make[1]: *** [src/CMakeFiles/jgi_summarize_bam_contig_depths.dir/all] Error 2
14:21:21 BIOCONDA INFO (OUT) make[1]: Leaving directory `$SRC_DIR/build'
14:21:21 BIOCONDA INFO (OUT) make: *** [all] Error 2
```

**Comment by mdehollander** [comment]
Adding `export CXXFLAGS=-ldeflate` to `build.sh` fixes the linux build

**Comment by druvus** [comment]
@bioconda-bot recheck

**Comment by dpryan79** [comment]
Can you delete the unneeded patches and remove all references to them from meta.yaml?

**Comment by mdehollander** [comment]
> Can you delete the unneeded patches and remove all references to them from meta.yaml?

I removed them. But I am not sure if they were not longer needed. Maybe @epruesse can take a look?

**Comment by mdehollander** [comment]
Well, let's merge it. If the patches are needed, we can also put them back later.

**Comment by mdehollander** [comment]
This update is part of the bioconda collaboration fest (#16858)

**Pull request merged**
