### PR TITLE
Nextclade: add run_test.sh

### PR DESCRIPTION
**Pull request by corneliusroemer**
Add run_test.sh to catch more bugs before pushing out new version

@pvanheus do you have experience with tests and bioconda?

It appears as though our release 1.8.0 is broken for macOS and this wasn't noticed because the test is currently too simple

Hence, I'm trying to add a more sophisticated test than `nextclade --help` through `run_test.sh` but I've never added such a test to a bioconda recipe so I'm not sure I'm doing it right.

### CODE REVIEW

**Comment by corneliusroemer** [comment]
It should fail not pass, weird.
https://dev.azure.com/bioconda/bioconda-recipes/_build/results?buildId=9388&view=logs&j=1b052f1d-4456-52f0-9d43-71c4c5bd734d&t=edc48dcd-1fc2-5e3b-7036-7be9cea00123&l=127

**Comment by corneliusroemer** [comment]
`set -e` didn't help.

This is weird. Can someone help me? `run_test.sh` fails but check passes?

https://dev.azure.com/bioconda/bioconda-recipes/_build/results?buildId=9390&view=logs&j=1b052f1d-4456-52f0-9d43-71c4c5bd734d&t=edc48dcd-1fc2-5e3b-7036-7be9cea00123&l=126

**Comment by dpryan79** [comment]
@corneliusroemer Is it still returning 0 as the exit status? That's the most likely explanation.

**Comment by corneliusroemer** [comment]
Thanks for figuring this out @dpryan79, that seems to be the reasons indeed as reported here: https://github.com/nextstrain/nextclade/issues/679

**Pull request closed without merging**
