### PR TITLE
Fiji recipe fixes

### PR DESCRIPTION
**Pull request by gregvonkuster**
* [x] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

1. The fiji.sh script is not needed since the ImageJ2 executable encapsulates Java calls.
2. The bunwarpjj.sh executable is still needed because bUnwarpJ provides an API, allowing tools to execute it using Java calls from the command line.  The command line built for these tools will be updated to call the bunwarpj.sh script instead of invoking Java.

### CODE REVIEW

**Comment by bgruening** [comment]
Ping @gregvonkuster

**Comment by gregvonkuster** [comment]
@bgruening Sorry, I looked at this a few days back, and just not quite sure why the test failed for this.  Should I just delete this PR for now?

**Comment by croth1** [comment]
@gregvonkuster, the recipe installs a binary named `ImageJ-macosx` instead of `ImageJ` on macOS, but the test script explicitly tries to call `ImageJ` which is doomed to fail. You could try symlinking `$PREFIX/bin/ImageJ-macosx` to `$PREFIX/bin/ImageJ` for the macOS build.

**Comment by gregvonkuster** [comment]
@croth1 Thanks for pointing this out - I'm not quite sure how I missed this.  I'll close this PR and open a new one with a recipe that works in the way I intended as soon as I get a chance.

**Pull request closed without merging**
