### PR TITLE
Update for Genepop 4.6, works on Mac

### PR DESCRIPTION
**Pull request by peterjc**
* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [X] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

Original recipe by @tiagoantao 

It looks like @bgruening restricted this to exclude Mac, not sure why - it compiles for me locally and my tests passed.

I have also made the compilation requirements explicit in line with evolving BioConda best practises, and added a minimal test.

Note the authors seem to reuse their filenames and URL, meaning older releases are not cached. I have added a checksum, but this is a concern as sources for the old releases are no longer available.

### CODE REVIEW

**Comment by bgruening** [comment]
@peterjc at this time we wasn't building for OSX by deafult, we had a whitelist of package to build or was it a black-list? Either way I removed it and included the skip: True in all packages that was on this list. The idea was and still is to get them onto OSX if people care, as you do :) So plan worked out :)

**Comment by peterjc** [comment]
@bgruening that makes sense, safer to assume the recipes at that point would be Linux only by default.

**Comment by peterjc** [comment]
It looks like some magic may be needed for the test command,

```
subprocess.CalledProcessError: Command '['mulled-build', 'build-and-test', 'genepop=4.6--0', '-n', 'biocontainers', '--test', "echo -e '\\n' | Genepop", '--extra-channels', 'file://anaconda/conda-bld,r,defaults,conda-forge']' returned non-zero exit status 1
```

In place of:

```
echo -e '\n' | Genepop
```

I am trying:

```
bash -c "echo -e '\n' | Genepop"
```

**Comment by peterjc** [comment]
@bgruening @tiagoantao is this OK now?

I tried but failed to get a new test to pass - e.g. https://travis-ci.org/bioconda/bioconda-recipes/jobs/235594244

**Comment by tiagoantao** [comment]
As long as it works on Linux (the only thing that I was supporting anyways) its fine by me.

**Comment by peterjc** [comment]
Thanks @tiagoantao I've tested GenePop 4.6 compiled by hand this way on the Mac and Linux (via your Biopython wrapper tests), so the basics are OK.

Can a BioConda guru (@bgruening, @daler?) explain why the test fails and/or approve this as is without the attempted test?

**Comment by bgruening** [comment]
@peterjc can you try this: `echo 'random_test.txt' | Genepop | grep 'Genepop version'`

**Comment by peterjc** [comment]
That's clever - the exact output on screen seems to depend on the terminal state, sometimes on the Mac I get:

```
Genepop version 4.6
From set_eof_check_EOLtype(): Cannot open file!
Check input file name random_test.txt
From parseFile(): Cannot open random_test.txt although it could previously be opened.
I exit.
```

Sometimes:

```
Genepop version 4.6
From parseFile(): Cannot open random_test.txt although it could previously be opened.
I exit.
```

I will try this in the recipe now...

**Comment by peterjc** [comment]
Mac passed :)

Linux failed - in a way which seems very similar to some of my other open pull requests where unless the logging it misleading it seems the test command framework itself is broken?

```
...
11:24:56 BIOCONDA ERROR COMMAND FAILED: mulled-build build-and-test genepop=4.6--0 -n biocontainers --test echo 'does_not_exist.txt' | Genepop | grep 'Genepop version' --extra-channels file://anaconda/conda-bld,r,defaults,conda-forge
...
[May 29 11:24:56] ERRO Task processing failed: Invalid bind specification [], has to be of the form: source:dest
involucro -v=2 -f /anaconda/lib/python3.5/site-packages/galaxy_lib-17.5.9-py3.5.egg/galaxy/tools/deps/mulled/invfile.lua -set CHANNELS='bioconda,file://anaconda/conda-bld,r,defaults,conda-forge' -set TEST='echo 'does_not_exist.txt' | Genepop | grep 'Genepop version'' -set TARGETS='genepop=4.6=0' -set REPO='quay.io/biocontainers/genepop:4.6--0' -set BINDS='build/dist:/usr/local/,/anaconda/conda-bld:/anaconda/conda-bld' build-and-test
11:24:56 BIOCONDA ERROR TEST FAILED: recipes/genepop, ...
```

Note the first and second lines quoted above do not show the test command in any way - if run exactly as written it would clearly fail:

```
$ mulled-build build-and-test genepop=4.6--0 -n biocontainers --test $TESTCMD --extra-channels file://anaconda/conda-bld,r,defaults,conda-forge
```

Cross reference https://github.com/bioconda/bioconda-recipes/pull/4790#issuecomment-303776317

**Comment by bgruening** [comment]
Thanks Peter!

**Comment by peterjc** [comment]
Thanks @bgruening - Could you explain why that particular combination of quotes worked under Linux (and Mac) as I don't understand and it would likely help me with other recipes?

**Comment by bgruening** [comment]
Sure! It's a little bit more complicated. On Linux we run very advanced tests to ensure that packages run in most-if-not-all environments. To do so, we use a tool called mulled/involucro that converts a conda package into a Docker container (https://github.com/galaxyproject/galaxy-lib/tree/master/galaxy/tools/deps/mulled).

Taking as Docker container busybox, we can really make sure that the packages works everywhere, as we don't have conda, or any library installed. The code is constructed here: https://github.com/bioconda/bioconda-utils/blob/master/bioconda_utils/pkg_test.py#L128

The disadvantages is that we can not use any advanced testing feature from conda, like the test-depends etc ... as we don't have conda in this test environment. An other disadvantage is that we need to pass all tests via a commandline call to mulled/involucor ... and here we need to quote tests as well ...

Does this make sense?

**Comment by peterjc** [comment]
Thanks @bgruening - those details are useful, especially https://github.com/bioconda/bioconda-utils/blob/master/bioconda_utils/pkg_test.py#L128 which shows exactly where that command is built up.

I still don't understand which style of quoting is necessary for this to work though - should I in general avoid single quotes as part of the sample test commands in favour of double quotes?

**Comment by bgruening** [comment]
I think what happens here: https://github.com/bioconda/bioconda-utils/blob/master/bioconda_utils/pkg_test.py#L133 and later in sp.run() is that the string is single-quoted so you need to use double-quotes in your tests.

**Comment by peterjc** [comment]
It does seem that using single-quotes within a test command is problematic for the test framework (under Linux at least). That is helpful to know - should we lint for this?

**Pull request merged**
