### PR TITLE
Update parsnp to 1.6.1

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`parsnp`](https://bioconda.github.io/recipes/parsnp/README.html): **1.6.0** &rarr; **1.6.1**

[install with bioconda](http://bioconda.github.io/recipes/parsnp/README.html) [Conda](https://anaconda.org/bioconda/parsnp/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/parsnp`](https://github.com//bioconda/bioconda-recipes/tree/bump/parsnp/recipes/parsnp) (click to view/edit other files)
Summary | Parsnp is a command-line-tool for efficient microbial core genome alignment and SNP detection.
Home | [https://github.com/marbl/parsnp](https://github.com/marbl/parsnp)
Releases |[https://github.com/marbl/parsnp/tags](https://github.com/marbl/parsnp/tags)
Author | `@marbl`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Review by bkille — APPROVED** [review]

**Comment by bkille** [comment]
@BiocondaBot fetch artifacts

**Comment by bkille** [comment]
@BiocondaBot please fetch artifacts

**Comment by dpryan79** [comment]
@bkille At the moment you have to click over to Azure (click on "show all checks" -> "details" -> "view more details on azure pipelines" and then the "1 artifact produced" link in the main window). Here's the direct link for convenience: https://dev.azure.com/bioconda/bioconda-recipes/_build/results?buildId=9790&view=artifacts&pathAsName=false&type=publishedArtifacts

Eventually I'll get the bot rewritten to post either a link or at least the contents of these.

**Comment by bkille** [comment]
@BiocondaBot please merge

**Pull request merged**
