### PR TITLE
Updated ECTyper v1.0.0 build #1 recipe with database init routine implemented at conda install stage

### PR DESCRIPTION
**Pull request by kbessonov1984**
Updated the ECTyper release 1.0.0 to now do database initialization during conda install that avoids race condition during first launch by multiple processes.
Also made ECTyper friendly to read-only file systems. Now there is not check for recency of RefSeq NCBI Assembly metadata file (little gains for any if at all outputs). Before those checks were done every 6 months making software not usable in read-only environments as update routine was not able to be completed to do failed write access.
This is re-release of the ECTyper 1.0.0 to complement coming publication that is about to be submitted to MGEN journal

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by kbessonov1984** [comment]
@bgruening finally this is an updated conda recipe that will be Galaxy Europe read-only file system friendly with species database automatic initialization at package install time. No more pain of manual initialization and database update (before it was trying to download NCBI RefSeq assemblies stats metadata every 6 months).  Was not possible to include database in conda package as this resulted in 330 MB package otherwise.

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
What happens now every 6 months?

**Comment by kbessonov1984** [comment]
@bgruening  Before every 6 months the ECTyper was checking if the age of the NCBI RefSeq Assembly metadata file and RefSeq MASH sketch. If the age was > 6 months, it was trying to re-download the fresh version from NCBI. When we've installed ECTyper before on Galaxy Europe, we needed to do `touch Data/assembly_summary_refseq.txt` and `touch Data/refseq.genomes.k21s1000.msh` so that date was recent (< 6 months). Now that would not be necessary anymore at all

**Comment by bgruening** [comment]
@bioconda-bot please merge

**Comment by bgruening** [comment]
Cool thanks!

**Pull request merged**
