### PR TITLE
OpenMS updated for new version of Comet. 

### PR DESCRIPTION
**Pull request by ypriverol**
Describe your pull request here

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by ypriverol** [comment]
@bgruening @timosachsenberg this is really strange, the error says that comet-ms can't be found, but the package is clearly in bioconda

```
08:09:49 BIOCONDA INFO (OUT) - Encountered problems while solving:
08:09:49 BIOCONDA INFO (OUT) -   - nothing provides comet-ms 2023010 needed by openms-thirdparty-2.9.1-h9ee0642_1
08:09:49 BIOCONDA INFO (OUT) -   - nothing provides requested comet-ms 2023010.*
08:09:49 BIOCONDA INFO (OUT) -
08:09:49 BIOCONDA INFO (OUT) failed to get install actions, retrying.  exception was: Unsatisfiable dependencies for platform linux-64: {MatchSpec("openms-thirdparty==2.9.1=h9ee0642_1"), MatchSpec("comet-ms=2023010")}
```

**Comment by ypriverol** [comment]
Something was wrong with the comet build because, I can't installed in linux either: 
```
mamba create -n comet-2023 comet-ms=2023010

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (0.15.3) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


Looking for: ['comet-ms=2023010']

pkgs/r/linux-64          [====================] (00m:00s) No change
pkgs/r/noarch            [====================] (00m:00s) No change
pkgs/main/noarch         [====================] (00m:00s) Done
pkgs/main/linux-64       [====================] (00m:01s) Done
bioconda/linux-64        [====================] (00m:01s) Done
bioconda/noarch          [====================] (00m:02s) Done
conda-forge/noarch       [====================] (00m:05s) Done
conda-forge/linux-64     [====================] (00m:08s) Done
Encountered problems while solving:
  - nothing provides requested comet-ms 2023010**
 ```

**Comment by ypriverol** [comment]
Morning @bgruening do you know when this will be done? How can I check if the CDN is updated.

**Comment by lldelisle** [comment]
Hi there,
I just checked with `conda search [package-name]` and I cannot see the new packages (fiji-omero_ij, varfish-server-worker 0.5.1, comet-ms 2023010, ...) so I guess it is not solved yet...

**Comment by ypriverol** [comment]
Thanks @lldelisle for the update.

**Comment by lldelisle** [comment]
@BiocondaBot please add label

**Comment by ypriverol** [comment]
@bgruening can you help me with this?

**Comment by bgruening** [comment]
@BiocondaBot please merge

**Pull request merged**
