### PR TITLE
SIRIUS: bump to v4.9.15

### PR DESCRIPTION
**Pull request by mfleisch**
Describe your pull request here
* bump version to 4.9.15
----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by mfleisch** [comment]
> Guess this may be closed in favor of [conda-forge/staged-recipes#16235](https://github.com/conda-forge/staged-recipes/pull/16235)

Since https://github.com/conda-forge/staged-recipes/pull/16235 has not been accepted for quite a while now, I think we should fully support SIRIUS 4 in bioconda until its end of life.

If the SIRIUS feedstock for conda-forge gets accepted I will update it to SIRIUS 5, so that upgrading from SIRIUS 4 to SIRIUS 5 would also correspond to the transition from the bioconda package to the conda-forge package.

**Comment by mfleisch** [comment]
@BiocondaBot please add label

**Comment by dpryan79** [comment]
@BiocondaBot please fetch artifacts

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@BiocondaBot please merge

**Comment by bernt-matthias** [comment]
Hi @mfleisch and @dpryan79 unfortunately my patch implemented in https://github.com/bioconda/bioconda-recipes/pull/34220 does not work if the OpenMS SiriusAdapter since it resolves the symlink to the executable, i.e. it does not exec `/usr/local/bin/sirius` but `/usr/local/share/sirius-csifingerid-4.9.8-2/bin/sirius`, i.e. the relative path used in the `LD_LIBRARY_PATH` does not work. 

Do you have an idea how this could be fixed, i.e. a better way to get the path where conda installs the libraries?

**Comment by bernt-matthias** [comment]
Maybe we can create a symlink from `/usr/local/share/sirius-csifingerid-4.9.8-2/lib` to `$PREFIX/lib`.. Given that the former does not exist..

**Comment by mfleisch** [comment]
How about just using  `$APP_HOME/../../lib` as relative path to the conda library dir in the patch file (instead of `$dname/../lib`)?
For the `$APP_HOME` variable we ensure in the  SIRIUS start script that it points to the correct location no matter whether it
is called via a link or from an arbitrary working directory.

```bash
# Attempt to set APP_HOME
# Resolve links: $0 may be a link
PRG="$0"
# Need this for relative symlinks.
while [ -h "$PRG" ] ; do
    ls=`ls -ld "$PRG"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    if expr "$link" : '/.*' > /dev/null; then
        PRG="$link"
    else
        PRG=`dirname "$PRG"`"/$link"
    fi
done
SAVED="`pwd`"
cd "`dirname \"$PRG\"`/.." >/dev/null
APP_HOME="`pwd -P`"
```

**Pull request merged**
