### PR TITLE
Trinity: rebuild 2.15.1

### PR DESCRIPTION
**Pull request by abretaud**
Trying to trigger a new build of trinity, as I'm getting this error while trying to install it:

```
  - package trinity-2.15.1-hff880f7_0 requires r-base >=4.1, but none of the providers can be installed
```

Not sure it's the right thin to do, let's see

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by bernt-matthias** [comment]
Do you get the error with `conda`, `conda --solver libmamba`, or `mamba`?

**Comment by abretaud** [comment]
mamba

**Comment by abretaud** [comment]
:thinking: I fear this PR would not change anything... I'm getting this detailed output with `conda --solver libmamba`, not sure how to interpret it:

```
The following packages are incompatible
└─ trinity 2.15.1**  is uninstallable because there are no viable options
   ├─ trinity 2.15.1 would require
   │  ├─ htslib >=1.17,<1.18.0a0 , which requires
   │  │  ├─ libcurl >=7.87.0,<8.0a0  with the potential options
   │  │  │  ├─ libcurl 7.87.0 would require
   │  │  │  │  └─ krb5 >=1.20.1,<1.21.0a0  with the potential options
   │  │  │  │     ├─ krb5 1.20.1, which can be installed;
   │  │  │  │     └─ krb5 1.20.1 would require
   │  │  │  │        └─ openssl >=3.0.7,<4.0a0 , which can be installed;
   │  │  │  ├─ libcurl 7.87.0 would require
   │  │  │  │  └─ openssl >=3.0.7,<4.0a0 , which can be installed;
   │  │  │  ├─ libcurl [7.88.0|7.88.1] would require
   │  │  │  │  └─ openssl >=3.0.8,<4.0a0 , which can be installed;
   │  │  │  ├─ libcurl [7.88.1|8.0.0|8.0.1] would require
   │  │  │  │  └─ openssl >=3.1.0,<4.0a0 , which can be installed;
   │  │  │  ├─ libcurl 7.87.0 conflicts with any installable versions previously reported;
   │  │  │  └─ libcurl 7.88.1 conflicts with any installable versions previously reported;
   │  │  ├─ openssl >=1.1.1t,<1.1.2a , which conflicts with any installable versions previously reported;
   │  │  └─ xz >=5.2.6,<5.3.0a0 , which can be installed;
   │  ├─ r-base >=4.1  with the potential options
   │  │  ├─ r-base [3.6.3|4.0.5|4.1.0] would require
   │  │  │  └─ krb5 >=1.19.1,<1.20.0a0  with the potential options
   │  │  │     ├─ krb5 1.19.1 conflicts with any installable versions previously reported;
   │  │  │     ├─ krb5 [1.19.2|1.19.3] would require
   │  │  │     │  └─ openssl >=3.0.0,<4.0a0 , which can be installed;
   │  │  │     ├─ krb5 1.19.2 conflicts with any installable versions previously reported;
   │  │  │     └─ krb5 [1.19.3|1.19.4] conflicts with any installable versions previously reported;
   │  │  ├─ r-base [4.0.5|4.1.1|4.1.2] would require
   │  │  │  └─ krb5 >=1.19.2,<1.20.0a0  with the potential options
   │  │  │     ├─ krb5 [1.19.2|1.19.3], which can be installed (as previously explained);
   │  │  │     ├─ krb5 1.19.2 conflicts with any installable versions previously reported;
   │  │  │     └─ krb5 [1.19.3|1.19.4] conflicts with any installable versions previously reported;
   │  │  ├─ r-base [4.0.5|4.1.3|4.2.0|4.2.1|4.2.2] would require
   │  │  │  └─ krb5 >=1.19.3,<1.20.0a0  with the potential options
   │  │  │     ├─ krb5 [1.19.2|1.19.3], which can be installed (as previously explained);
   │  │  │     └─ krb5 [1.19.3|1.19.4] conflicts with any installable versions previously reported;
   │  │  ├─ r-base 4.2.2 would require
   │  │  │  └─ icu >=70.1,<71.0a0 , which can be installed;
   │  │  ├─ r-base 4.2.3 would require
   │  │  │  └─ libcurl >=7.88.1,<9.0a0  with the potential options
   │  │  │     ├─ libcurl [7.88.0|7.88.1], which can be installed (as previously explained);
   │  │  │     ├─ libcurl [7.88.1|8.0.0|8.0.1], which can be installed (as previously explained);
   │  │  │     └─ libcurl 7.88.1 conflicts with any installable versions previously reported;
   │  │  ├─ r-base 4.3.0 would require
   │  │  │  └─ libcurl >=8.0.1,<9.0a0 , which can be installed (as previously explained);
   │  │  └─ r-base 4.2.0 conflicts with any installable versions previously reported;
   │  └─ salmon >=1.0  but there are no viable options
   │     ├─ salmon [1.0.0|1.1.0|...|1.4.0] would require
   │     │  └─ icu >=64.2,<65.0a0 , which conflicts with any installable versions previously reported;
   │     ├─ salmon [1.10.0|1.10.1|1.7.0|1.8.0|1.9.0] would require
   │     │  └─ icu >=69.1,<70.0a0 , which conflicts with any installable versions previously reported;
   │     ├─ salmon [1.4.0|1.5.0|1.5.1|1.5.2] would require
   │     │  └─ icu >=68.1,<69.0a0 , which conflicts with any installable versions previously reported;
   │     └─ salmon [1.6.0|1.7.0] would require
   │        └─ icu >=68.2,<69.0a0 , which conflicts with any installable versions previously reported;
   └─ trinity 2.15.1 would require
      ├─ bioconductor-dexseq   with the potential options
      │  ├─ bioconductor-dexseq 1.44.0 would require
      │  │  └─ bioconductor-biomart >=2.54.0,<2.55.0 , which requires
      │  │     └─ r-progress   with the potential options
      │  │        ├─ r-progress 1.2.2 would require
      │  │        │  └─ r-prettyunits   with the potential options
      │  │        │     ├─ r-prettyunits 1.1.1 would require
      │  │        │     │  └─ r-magrittr   with the potential options
      │  │        │     │     ├─ r-magrittr 2.0.3 would require
      │  │        │     │     │  └─ r-base >=4.2,<4.3.0a0  with the potential options
      │  │        │     │     │     ├─ r-base [4.0.5|4.1.3|4.2.0|4.2.1|4.2.2], which can be installed (as previously explained);
      │  │        │     │     │     ├─ r-base 4.2.2, which can be installed (as previously explained);
      │  │        │     │     │     ├─ r-base 4.2.3, which can be installed (as previously explained);
      │  │        │     │     │     └─ r-base 4.2.0 conflicts with any installable versions previously reported;
      │  │        │     │     ├─ r-magrittr 1.5 would require
      │  │        │     │     │  └─ r-base 3.3.2*  with the potential options
      │  │        │     │     │     ├─ r-base [3.3.2|3.4.1] would require
      │  │        │     │     │     │  └─ zlib 1.2.8 , which can be installed;
      │  │        │     │     │     └─ r-base [3.3.1|3.3.2|3.4.1] would require
      │  │        │     │     │        └─ icu 54.* , which does not exist (perhaps a missing channel);
      │  │        │     │     ├─ r-magrittr 1.5 would require
      │  │        │     │     │  └─ r-base [3.4.1* |>=3.4.1,<3.4.2.0a0 ] with the potential options
      │  │        │     │     │     ├─ r-base [3.3.2|3.4.1], which can be installed (as previously explained);
      │  │        │     │     │     ├─ r-base 3.4.1 would require
      │  │        │     │     │     │  └─ zlib 1.2.11 , which can be installed;
      │  │        │     │     │     ├─ r-base 3.4.1 would require
      │  │        │     │     │     │  └─ openssl >=1.0.2o,<1.0.3a , which can be installed;
      │  │        │     │     │     └─ r-base [3.3.1|3.3.2|3.4.1], which cannot be installed (as previously explained);
      │  │        │     │     ├─ r-magrittr 1.5 would require
      │  │        │     │     │  └─ r-base >=3.5.1,<3.5.2.0a0  with the potential options
      │  │        │     │     │     ├─ r-base [3.5.1|3.6.1|3.6.2] would require
      │  │        │     │     │     │  └─ krb5 [>=1.16.2,<1.17.0a0 |>=1.16.3,<1.17.0a0 ] with the potential options
      │  │        │     │     │     │     ├─ krb5 1.16.3 conflicts with any installable versions previously reported;
      │  │        │     │     │     │     ├─ krb5 [1.16.2|1.16.3] would require
      │  │        │     │     │     │     │  └─ openssl >=1.0.2p,<1.0.3a , which can be installed;
      │  │        │     │     │     │     └─ krb5 1.16.4 conflicts with any installable versions previously reported;
      │  │        │     │     │     ├─ r-base [3.5.1|3.6.2|3.6.3] would require
      │  │        │     │     │     │  └─ krb5 >=1.16.4,<1.17.0a0 , which conflicts with any installable versions previously reported;
      │  │        │     │     │     └─ r-base 3.5.1 conflicts with any installable versions previously reported;
      │  │        │     │     ├─ r-magrittr [1.5|2.0.1] would require
      │  │        │     │     │  └─ r-base >=3.6,<3.7.0a0  with the potential options
      │  │        │     │     │     ├─ r-base [3.6.3|4.0.5|4.1.0], which can be installed (as previously explained);
      │  │        │     │     │     ├─ r-base [3.5.1|3.6.1|3.6.2], which can be installed (as previously explained);
      │  │        │     │     │     ├─ r-base [3.5.1|3.6.2|3.6.3], which cannot be installed (as previously explained);
      │  │        │     │     │     ├─ r-base [3.6.3|4.0.0|...|4.0.5] would require
      │  │        │     │     │     │  └─ krb5 >=1.17.1,<1.18.0a0 , which conflicts with any installable versions previously reported;
      │  │        │     │     │     └─ r-base [3.6.0|3.6.1] conflicts with any installable versions previously reported;
      │  │        │     │     ├─ r-magrittr [1.5|2.0.1|2.0.2|2.0.3] would require
      │  │        │     │     │  └─ r-base >=4.0,<4.1.0a0  with the potential options
      │  │        │     │     │     ├─ r-base [3.6.3|4.0.5|4.1.0], which can be installed (as previously explained);
      │  │        │     │     │     ├─ r-base [4.0.5|4.1.1|4.1.2], which can be installed (as previously explained);
      │  │        │     │     │     ├─ r-base [4.0.5|4.1.3|4.2.0|4.2.1|4.2.2], which can be installed (as previously explained);
      │  │        │     │     │     └─ r-base [3.6.3|4.0.0|...|4.0.5], which cannot be installed (as previously explained);
      │  │        │     │     ├─ r-magrittr [2.0.1|2.0.2|2.0.3] would require
      │  │        │     │     │  └─ r-base >=4.1,<4.2.0a0 , which can be installed (as previously explained);
      │  │        │     │     ├─ r-magrittr 1.5 would require
      │  │        │     │     │  └─ r-base >=3.5,<3.6.0a0  with the potential options
      │  │        │     │     │     ├─ r-base [3.5.1|3.6.1|3.6.2], which can be installed (as previously explained);
      │  │        │     │     │     ├─ r-base [3.5.1|3.6.2|3.6.3], which cannot be installed (as previously explained);
      │  │        │     │     │     ├─ r-base 3.5.1 conflicts with any installable versions previously reported;
      │  │        │     │     │     └─ r-base [3.5.0|3.5.3] conflicts with any installable versions previously reported;
      │  │        │     │     ├─ r-magrittr 1.5 would require
      │  │        │     │     │  └─ r 3.2.2* , which does not exist (perhaps a missing channel);
      │  │        │     │     ├─ r-magrittr [1.5|2.0.3] conflicts with any installable versions previously reported;
      │  │        │     │     ├─ r-magrittr 1.5 would require
      │  │        │     │     │  └─ r-base 3.2.0* , which does not exist (perhaps a missing channel);
      │  │        │     │     ├─ r-magrittr 1.5 would require
      │  │        │     │     │  └─ r-base 3.2.1* , which does not exist (perhaps a missing channel);
      │  │        │     │     └─ r-magrittr 1.5 would require
      │  │        │     │        └─ r-base 3.2.2* , which does not exist (perhaps a missing channel);
      │  │        │     ├─ r-prettyunits 1.0.2 would require
      │  │        │     │  └─ r-base 3.3.2*  with the potential options
      │  │        │     │     ├─ r-base [3.3.2|3.4.1], which can be installed (as previously explained);
      │  │        │     │     └─ r-base [3.3.1|3.3.2|3.4.1], which cannot be installed (as previously explained);
      │  │        │     ├─ r-prettyunits 1.0.2 would require
      │  │        │     │  └─ r-base [3.4.1* |>=3.4.1,<3.4.2.0a0 ] with the potential options
      │  │        │     │     ├─ r-base [3.3.2|3.4.1], which can be installed (as previously explained);
      │  │        │     │     ├─ r-base 3.4.1, which can be installed (as previously explained);
      │  │        │     │     ├─ r-base 3.4.1, which can be installed (as previously explained);
      │  │        │     │     └─ r-base [3.3.1|3.3.2|3.4.1], which cannot be installed (as previously explained);
      │  │        │     ├─ r-prettyunits 1.0.2 would require
      │  │        │     │  └─ r-base >=3.5.1,<3.5.2.0a0  with the potential options
      │  │        │     │     ├─ r-base [3.5.1|3.6.1|3.6.2], which can be installed (as previously explained);
      │  │        │     │     ├─ r-base [3.5.1|3.6.2|3.6.3], which cannot be installed (as previously explained);
      │  │        │     │     └─ r-base 3.5.1 conflicts with any installable versions previously reported;
      │  │        │     ├─ r-prettyunits [1.0.2|1.1.0|1.1.1] would require
      │  │        │     │  └─ r-base >=3.5,<3.6.0a0  with the potential options
      │  │        │     │     ├─ r-base [3.5.1|3.6.1|3.6.2], which can be installed (as previously explained);
      │  │        │     │     ├─ r-base [3.5.1|3.6.2|3.6.3], which cannot be installed (as previously explained);
      │  │        │     │     ├─ r-base 3.5.1 conflicts with any installable versions previously reported;
      │  │        │     │     └─ r-base [3.5.0|3.5.3] conflicts with any installable versions previously reported;
      │  │        │     ├─ r-prettyunits [1.0.2|1.1.0|1.1.1] would require
      │  │        │     │  └─ r-base >=3.6,<3.7.0a0  with the potential options
      │  │        │     │     ├─ r-base [3.6.3|4.0.5|4.1.0], which can be installed (as previously explained);
      │  │        │     │     ├─ r-base [3.5.1|3.6.1|3.6.2], which can be installed (as previously explained);
      │  │        │     │     ├─ r-base [3.5.1|3.6.2|3.6.3], which cannot be installed (as previously explained);
      │  │        │     │     ├─ r-base [3.6.3|4.0.0|...|4.0.5], which cannot be installed (as previously explained);
      │  │        │     │     └─ r-base [3.6.0|3.6.1] conflicts with any installable versions previously reported;
      │  │        │     ├─ r-prettyunits 1.1.1 would require
      │  │        │     │  └─ r-base >=4.0,<4.1.0a0  with the potential options
      │  │        │     │     ├─ r-base [3.6.3|4.0.5|4.1.0], which can be installed (as previously explained);
      │  │        │     │     ├─ r-base [4.0.5|4.1.1|4.1.2], which can be installed (as previously explained);
      │  │        │     │     ├─ r-base [4.0.5|4.1.3|4.2.0|4.2.1|4.2.2], which can be installed (as previously explained);
      │  │        │     │     └─ r-base [3.6.3|4.0.0|...|4.0.5], which cannot be installed (as previously explained);
      │  │        │     ├─ r-prettyunits 1.1.1 would require
      │  │        │     │  └─ r-base >=4.1,<4.2.0a0 , which can be installed (as previously explained);
      │  │        │     └─ r-prettyunits [1.0.2|1.1.1] conflicts with any installable versions previously reported;
      │  │        ├─ r-progress 1.1.2 would require
      │  │        │  └─ r-base 3.3.2*  with the potential options
      │  │        │     ├─ r-base [3.3.2|3.4.1], which can be installed (as previously explained);
      │  │        │     └─ r-base [3.3.1|3.3.2|3.4.1], which cannot be installed (as previously explained);
      │  │        ├─ r-progress [1.1.2|1.2.0] would require
      │  │        │  └─ r-base [3.4.1* |>=3.4.1,<3.4.2.0a0 ] with the potential options
      │  │        │     ├─ r-base [3.3.2|3.4.1], which can be installed (as previously explained);
      │  │        │     ├─ r-base 3.4.1, which can be installed (as previously explained);
      │  │        │     ├─ r-base 3.4.1, which can be installed (as previously explained);
      │  │        │     └─ r-base [3.3.1|3.3.2|3.4.1], which cannot be installed (as previously explained);
      │  │        ├─ r-progress [1.2.0|1.2.1|1.2.2] would require
      │  │        │  └─ r-base >=3.5.1,<3.5.2.0a0  with the potential options
      │  │        │     ├─ r-base [3.5.1|3.6.1|3.6.2], which can be installed (as previously explained);
      │  │        │     ├─ r-base [3.5.1|3.6.2|3.6.3], which cannot be installed (as previously explained);
      │  │        │     └─ r-base 3.5.1 conflicts with any installable versions previously reported;
      │  │        ├─ r-progress 1.2.2 would require
      │  │        │  └─ r-base >=3.5,<3.6.0a0  with the potential options
      │  │        │     ├─ r-base [3.5.1|3.6.1|3.6.2], which can be installed (as previously explained);
      │  │        │     ├─ r-base [3.5.1|3.6.2|3.6.3], which cannot be installed (as previously explained);
      │  │        │     ├─ r-base 3.5.1 conflicts with any installable versions previously reported;
      │  │        │     └─ r-base [3.5.0|3.5.3] conflicts with any installable versions previously reported;
      │  │        ├─ r-progress 1.2.2 would require
      │  │        │  └─ r-base >=3.6,<3.7.0a0  with the potential options
      │  │        │     ├─ r-base [3.6.3|4.0.5|4.1.0], which can be installed (as previously explained);
      │  │        │     ├─ r-base [3.5.1|3.6.1|3.6.2], which can be installed (as previously explained);
      │  │        │     ├─ r-base [3.5.1|3.6.2|3.6.3], which cannot be installed (as previously explained);
      │  │        │     ├─ r-base [3.6.3|4.0.0|...|4.0.5], which cannot be installed (as previously explained);
      │  │        │     └─ r-base [3.6.0|3.6.1] conflicts with any installable versions previously reported;
      │  │        ├─ r-progress 1.2.2 would require
      │  │        │  └─ r-base >=4.0,<4.1.0a0  with the potential options
      │  │        │     ├─ r-base [3.6.3|4.0.5|4.1.0], which can be installed (as previously explained);
      │  │        │     ├─ r-base [4.0.5|4.1.1|4.1.2], which can be installed (as previously explained);
      │  │        │     ├─ r-base [4.0.5|4.1.3|4.2.0|4.2.1|4.2.2], which can be installed (as previously explained);
      │  │        │     └─ r-base [3.6.3|4.0.0|...|4.0.5], which cannot be installed (as previously explained);
      │  │        ├─ r-progress 1.2.2 would require
      │  │        │  └─ r-base >=4.1,<4.2.0a0 , which can be installed (as previously explained);
      │  │        └─ r-progress [1.0.2|1.2.0|1.2.2] conflicts with any installable versions previously reported;
      │  ├─ bioconductor-dexseq 1.16.6 would require
      │  │  └─ r 3.2.2* , which does not exist (perhaps a missing channel);
      │  ├─ bioconductor-dexseq [1.18.4|1.20.1] would require
      │  │  └─ r 3.3.1* , which conflicts with any installable versions previously reported;
      │  ├─ bioconductor-dexseq [1.18.4|1.20.1|1.22.0] would require
      │  │  └─ r-base 3.3.2*  with the potential options
      │  │     ├─ r-base [3.3.2|3.4.1], which can be installed (as previously explained);
      │  │     └─ r-base [3.3.1|3.3.2|3.4.1], which cannot be installed (as previously explained);
      │  ├─ bioconductor-dexseq 1.20.1 would require
      │  │  └─ r-base 3.3.1* , which cannot be installed (as previously explained);
      │  ├─ bioconductor-dexseq [1.22.0|1.24.0|1.26.0] would require
      │  │  └─ r-base [3.4.1* |>=3.4.1,<3.4.2.0a0 ] with the potential options
      │  │     ├─ r-base [3.3.2|3.4.1], which can be installed (as previously explained);
      │  │     ├─ r-base 3.4.1, which can be installed (as previously explained);
      │  │     ├─ r-base 3.4.1, which can be installed (as previously explained);
      │  │     └─ r-base [3.3.1|3.3.2|3.4.1], which cannot be installed (as previously explained);
      │  ├─ bioconductor-dexseq [1.22.0|1.24.0] would require
      │  │  └─ python 3.5*  with the potential options
      │  │     ├─ python [3.5.1|3.5.2] would require
      │  │     │  └─ xz 5.0.* , which conflicts with any installable versions previously reported;
      │  │     ├─ python [3.5.2|3.5.3|3.5.4] would require
      │  │     │  └─ openssl 1.0.* , which can be installed;
      │  │     ├─ python [3.5.4|3.5.5] would require
      │  │     │  └─ zlib 1.2.11 , which can be installed;
      │  │     ├─ python 3.5.5 would require
      │  │     │  └─ openssl >=1.0.2o,<1.0.3a , which can be installed;
      │  │     └─ python [3.5.4|3.5.5|3.5.6] conflicts with any installable versions previously reported;
      │  ├─ bioconductor-dexseq [1.24.0|1.26.0|1.28.0|1.28.1] would require
      │  │  └─ r-base >=3.5.1,<3.5.2.0a0  with the potential options
      │  │     ├─ r-base [3.5.1|3.6.1|3.6.2], which can be installed (as previously explained);
      │  │     ├─ r-base [3.5.1|3.6.2|3.6.3], which cannot be installed (as previously explained);
      │  │     └─ r-base 3.5.1 conflicts with any installable versions previously reported;
      │  ├─ bioconductor-dexseq [1.30.0|1.32.0] would require
      │  │  └─ r-base >=3.6,<3.7.0a0  with the potential options
      │  │     ├─ r-base [3.6.3|4.0.5|4.1.0], which can be installed (as previously explained);
      │  │     ├─ r-base [3.5.1|3.6.1|3.6.2], which can be installed (as previously explained);
      │  │     ├─ r-base [3.5.1|3.6.2|3.6.3], which cannot be installed (as previously explained);
      │  │     ├─ r-base [3.6.3|4.0.0|...|4.0.5], which cannot be installed (as previously explained);
      │  │     └─ r-base [3.6.0|3.6.1] conflicts with any installable versions previously reported;
      │  ├─ bioconductor-dexseq [1.34.0|1.36.0] would require
      │  │  └─ r-base >=4.0,<4.1.0a0  with the potential options
      │  │     ├─ r-base [3.6.3|4.0.5|4.1.0], which can be installed (as previously explained);
      │  │     ├─ r-base [4.0.5|4.1.1|4.1.2], which can be installed (as previously explained);
      │  │     ├─ r-base [4.0.5|4.1.3|4.2.0|4.2.1|4.2.2], which can be installed (as previously explained);
      │  │     └─ r-base [3.6.3|4.0.0|...|4.0.5], which cannot be installed (as previously explained);
      │  └─ bioconductor-dexseq [1.38.0|1.40.0] would require
      │     └─ r-base >=4.1,<4.2.0a0 , which can be installed (as previously explained);
      ├─ htslib >=1.17,<1.18.0a0 , which cannot be installed (as previously explained);
      ├─ libzlib >=1.2.13,<1.3.0a0 , which requires
      │  └─ zlib 1.2.13 *_4, which conflicts with any installable versions previously reported;
      └─ salmon >=1.0 , which cannot be installed (as previously explained).
```

**Comment by jmarshall** [comment]
```
   ├─ trinity 2.15.1 would require
   │  ├─ htslib >=1.17,<1.18.0a0 , which requires
   │  │  ├─ libcurl >=7.87.0,<8.0a0  with the potential options
   │  │  │  ├─ libcurl 7.87.0 would require
   │  │  │  │  └─ krb5 >=1.20.1,<1.21.0a0  with the potential options
   │  │  │  │     ├─ krb5 1.20.1, which can be installed;
   │  │  │  │     └─ krb5 1.20.1 would require
   │  │  │  │        └─ openssl >=3.0.7,<4.0a0 , which can be installed;
  […]
   │  │  ├─ openssl >=1.1.1t,<1.1.2a , which conflicts with any installable versions previously reported;
```

Your problem, or at least part of it, would appear to be #39356.

**Comment by abretaud** [comment]
Ah, thanks for the xref @jmarshall! Seems quite complicated, is there a simple workaround for this trinity problem, or we'll have to wait for the pinning update?

**Comment by abretaud** [comment]
install works now

**Pull request closed without merging**
