### PR TITLE
Update rnastructure and add mac OS build

### PR DESCRIPTION
**Pull request by janstrauss1**
Update rnastructure to version 6.3 and include build for mac OS

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by janstrauss1** [comment]
Trying to deal with to deal with `error: 'omp.h' file not found` for OSX build, I found this [https://github.com/bioconda/bioconda-recipes/issues/8869#issuecomment-475572099](https://github.com/bioconda/bioconda-recipes/issues/8869#issuecomment-475572099) and added `llvm-openmp` to both, the `build:` and `run:` sections.

**Comment by rpetit3** [comment]
Hi @janstrauss1 do you think this might be useful? https://stackoverflow.com/a/33401294

**Comment by janstrauss1** [comment]
Many thanks for your feedback @rpetit3! 
Yes, [https://stackoverflow.com/a/33401294](https://stackoverflow.com/a/33401294) is certainly useful and appears to be related to what is discussed at #8869.

I've alse looked at the PR: #15012 that seems highly relevant to what I'm trying to fix and have updated the `build.sh` for `rnastructure` accordingly. 

Yet, I'm an absolute beginner so any comments and help on my suggested file changes will be highly appreciated!

**Comment by janstrauss1** [comment]
Tagging @kastman, who has been able to fix a similar issue for PR: #15012 and may be able to help.
Many thanks in advance for any feedback!

**Comment by rpetit3** [comment]
Hi @janstrauss1,

I noticed in the `comiler.h` file `CPP_FLAGS can be specified by the user (make ... CPP_FLAGS=-DBANANA)`

```
  CXXFLAGS    = -DNDEBUG ${ARCHITECTURE} -std=c++11 $(CPP_FLAGS) # C++11 requirement added for log_double.  CPP_FLAGS can be specified by the user (make ... CPP_FLAGS=-DBANANA)
  CXXFLAGS    +=  ${??DEBUG_FLAGS} ${??OPTIMIZE_FLAGS} ${??WARNINGS_FLAGS} #  '??' macros are calculated based on configuration settings described in Section 1.
```

I'm going to try passing the CXXFLAGS that you created. We'll see how it goes!

**Comment by janstrauss1** [comment]
@BiocondaBot please add label

**Review by dpryan79 — APPROVED** [review]

**Comment by rpetit3** [comment]
@dpryan79 Will this only build for OSX now, and not Linux? (mostly curious for future reference)

**Comment by rpetit3** [comment]
Ignore me, I see what you did! You skipped the Linux step to debug the OSX bit quick. Very nice!

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Pull request merged**
