### PR TITLE
Update phyloflash v3.4.2 dependencies pinned versions

### PR DESCRIPTION
**Pull request by kbseah**
Current recipe fails without defaults channel, as reported here: https://github.com/HRGV/phyloFlash/issues/179

Previously pinned versions `r-base >=4.1.0` and `samtools >=1.13` cause dependency conflicts with `-c nodefaults` option (e.g. miniforge). Although Bioconda setup instructions state that defaults channel should be included, there are users who may wish to avoid defaults channel because of [licensing issues](https://conda-forge.org/blog/posts/2020-11-20-anaconda-tos/).

Updated recipe lowers these dependencies to highest versions that produced viable solution; pinned another dependency; and bumped build number.

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by kbseah** [comment]
@bioconda/core : Check results appear to be out of sync between GitHub and Azure. Is this a temporary issue or should the checks be restarted?

Details: On GitHub, the test_linux check above appears to be still in progress after >17 h, but [the summary on Azure](https://dev.azure.com/bioconda/bioconda-recipes/_build/results?buildId=32805&view=results) shows that the check finished in about 16 min and that all jobs are complete.

Thanks for your help

**Review by rpetit3 — APPROVED** [review]

**Comment by rpetit3** [comment]
@biocondabot please update

**Comment by rpetit3** [comment]
Let's try a rerun

**Comment by kbseah** [comment]
@BiocondaBot please rebuild

**Comment by rpetit3** [comment]
@kbseah ended up manually updating, seems there's an issue with the bot command

**Comment by kbseah** [comment]
thanks for this!

**Pull request merged**
