### PR TITLE
Bulk - update ucsc tools

### PR DESCRIPTION
**Pull request by karl616**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [x] This PR does something else (explain below).

### CODE REVIEW

**Comment by karl616** [comment]
replaces #7592 
updating the ucsc utility scripts:
- building for osx based on that it works for bedgraphtobigwig

**Comment by bgruening** [comment]
@karl616 sorry it took me longer then expected. Can you rebase once more. Thanks.

**Comment by karl616** [comment]
@bgruening understandable, I saw the list of failing recipes. Thanks for doing it. 

I added the changes on top of the most recent version of bulk. I'm curious to see if it the mac-build works.

**Comment by mbargull** [comment]
Are the UCSC packages all C packages or are there also some C++ ones? If the latter is true, would it make sense to add `- libcxx  # [osx]` to the run requirements? If they only use C, just disregard this comment.

**Comment by karl616** [comment]
I double checked and as I understood the documentation it is pure C, but that doesn't stop it from not being so

**Comment by bgruening** [comment]
Ok, lets keep bulk busy over the weekend.
Thanks a bunch @karl616!

**Comment by karl616** [comment]
I should have ran the script as well, shouldn't I?

**Pull request merged**
