### PR TITLE
required for dammit

### PR DESCRIPTION
**Pull request by mictadlo**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by mictadlo** [comment]
Hi @bioconda/core  ,
What did I miss?
Thank you in advance,
Michal

**Comment by johanneskoester** [comment]
You have to check the failed lints in the travis log, see here: https://travis-ci.org/bioconda/bioconda-recipes/jobs/324449120#L707

If you enter the docs (mentioned above that line), you will find an explanation.

**Comment by mictadlo** [comment]
Unfortunately, I am still not sure how to fix it or disable lint. Could you please explain a little more?

**Comment by daler** [comment]
@mictadlo this is a general sphinx package that is not bioinformatics-specific and so should be submitted to conda-forge. I believe recent versions of sphinx already come with napoleon though, so you might not even need this dep?

---

More info on your original question: the travis logs at https://travis-ci.org/bioconda/bioconda-recipes/jobs/324449120#L707 say:
```
The following recipes failed linting. See https://bioconda.github.io/linting.html for details:
                                                                 failed_tests
recipe                                                                       
recipes/sphinxcontrib-napoleon  [has_windows_bat_file, setup_py_install_args]
```

This is saying that `recipes/sphinxcontrib-napoleon` failed tests for "has_windows_bat_file" and "setup_py_install_args". If you visit https://bioconda.github.io/linting.html it describes what these issues are and how to fix them (hint: look at the table of contents on the left side of that page). However as I mentioned, it will be better to submit this to conda-forge.

**Comment by daler** [comment]
closed via #7187

**Pull request closed without merging**
