### PR TITLE
[MRG] fastx_toolkit: added osx compatibility

### PR DESCRIPTION
**Pull request by croth1**
Making fastx_toolkit osx compatible seems rather tricky since linkage against the c++ standard lib is required.

Using `libc++` makes it possible to go down to 10.7 for `fastx_toolkit`. I did not manage to get libgtextutils below 10.9 without losing the implementation of `basic_stringbuf` during linkage. Not sure if there's a trick to get lower. Ideally, 10.6 would be nice for both packages, but I doubt that this is possible.

### CODE REVIEW

**Comment by croth1** [comment]
This should be ready for the first round of reviews. fastx_toolkit was missing a dependency on gnuplot with png support which is rather tricky to get. I updated gnuplot because the build system of the 4.6 version seemed to be buggy.

**Comment by kyleabeauchamp** [comment]
Fastx changes LGTM

**Comment by johanneskoester** [comment]
Looks like this needs gcc/llvm as build dependencies?

**Comment by kyleabeauchamp** [comment]
Yeah, I made the recipe before we started tracking those.

**Comment by croth1** [comment]
okay, added gcc + llvm dependencies

**Comment by croth1** [comment]
@johanneskoester, unfortunately, this is still broken. The problem is that the libgd version in conda's repositories is currently buggy. See https://github.com/conda/conda-recipes/issues/625 for a quick description. I assumed that my libgd version here in the bioconda repo would shadow the one from the defaults channel. But this does not seem to be the case. Is there a way to use the libgd here in bioconda instead when building the package?

**Comment by johanneskoester** [comment]
The right way might be to use a ".bioconda" suffix to the version number (which sorts before the version from the main channel), as indicated by [this](https://github.com/conda/conda/blob/2ba04a6b2617227de578f4af54ff11115f97ca5c/conda/version.py#L81) comment in the conda source.

**Comment by croth1** [comment]
Okay, this should work: https://github.com/bioconda/bioconda-recipes/pull/981

**Pull request merged**
