### PR TITLE
Ngs bits 2018 08

### PR DESCRIPTION
**Pull request by marc-sturm**
Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it. Note that if you are not already a member of the bioconda project (meaning that you can't add this label), please ping `@bioconda/core` so that your PR can be reviewed and merged (please note if you'd like to be added to the bioconda project). Please see https://github.com/bioconda/bioconda-recipes/issues/15332 for more details.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by marc-sturm** [comment]
@bioconda/core Help would be appreciated.

I bumped the version and now I get these errors with exactly the same setup as last time:

	.../ld: warning: libQt5Gui.so.5, needed by .../work/bin/libcppXML.so, not found (try using -rpath or -rpath-link)
	.../ld: warning: libQt5Xml.so.5, needed by .../work/bin/libcppXML.so, not found (try using -rpath or -rpath-link)
	.../ld: warning: libQt5XmlPatterns.so.5, needed by .../work/bin/libcppXML.so, not found (try using -rpath or -rpath-link)
	.../ld: warning: libQt5Network.so.5, needed by .../work/bin/libcppXML.so, not found (try using -rpath or -rpath-link)
	.../ld: warning: libXext.so.6, needed by .../x86_64-conda_cos6-linux-gnu/sysroot/usr/lib64/libGL.so.1, not found
	.../ld: warning: libxcb-glx.so.0, needed by .../x86_64-conda_cos6-linux-gnu/sysroot/usr/lib64/libGL.so.1, not found
	.../ld: warning: libxcb-dri2.so.0, needed by .../x86_64-conda_cos6-linux-gnu/sysroot/usr/lib64/libGL.so.1, not found
	.../ld: warning: libxcb.so.1, needed by .../x86_64-conda_cos6-linux-gnu/sysroot/usr/lib64/libGL.so.1, not found
	.../ld: warning: libexpat.so.1, needed by .../x86_64-conda_cos6-linux-gnu/sysroot/usr/lib64/libGL.so.1, not found

Any ideas what's wrong with Qt?

**Comment by marc-sturm** [comment]
@dpryan79 Thanks for the update. However it still fails with the same error.

**Comment by dpryan79** [comment]
@marc-sturm The missing libraries should all be under `${PREFIX}/lib`, presumably the compiler isn't being told to look there.

**Comment by marc-sturm** [comment]
@dpryan79 Thanks for the hint. I was sure linking should work since it did last time, but after adding QMAKE_RPATHLINKDIR it runs through now! Can you merge?

**Pull request merged**
