### PR TITLE
Add recipe for ncbi-datasets-pylib

### PR DESCRIPTION
**Pull request by misialq**
This PR adds a recipe for the _ncbi-datasets-pylib_ package that can be used to interact with the NCBI Datasets API.

### CODE REVIEW

**Comment by misialq** [comment]
@BiocondaBot please add label

**Comment by misialq** [comment]
@BiocondaBot please update

**Comment by misialq** [comment]
@BiocondaBot please fetch artifacts

**Review by daler — APPROVED** [review]

**Comment by daler** [comment]
@BiocondaBot please merge

**Comment by daler** [comment]
@BiocondaBot please update

**Comment by daler** [comment]
@BiocondaBot please merge

**Pull request merged**
