### PR TITLE
Update wfa2-lib to 2.3.4

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`wfa2-lib`](https://bioconda.github.io/recipes/wfa2-lib/README.html): **2.3.3** &rarr; **2.3.4**

[install with bioconda](http://bioconda.github.io/recipes/wfa2-lib/README.html) [Conda](https://anaconda.org/bioconda/wfa2-lib/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/wfa2-lib`](https://github.com//bioconda/bioconda-recipes/tree/bump/wfa2_lib/recipes/wfa2-lib) (click to view/edit other files)
Summary | Wavefront alignment algorithm library v2
Home | [https://github.com/smarco/WFA2-lib](https://github.com/smarco/WFA2-lib)
Releases |[https://github.com/smarco/WFA2-lib/tags](https://github.com/smarco/WFA2-lib/tags)
Author | `@smarco`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by twrightsman** [comment]
@mencian Thanks for dropping those patches. Though I think we should just delete them and start the new patch at number 1? Could you submit the patch upstream?

**Comment by twrightsman** [comment]
Also, upstream has promised (https://github.com/smarco/WFA2-lib/issues/82) to follow semantic versioning starting with 2.3.4, so maybe we can relax the `max_pin` back to `x` in `pin_subpackage`? Or maybe wait until 2.4 or 3.0 is released, not sure what best practice is here.

**Comment by twrightsman** [comment]
@BiocondaBot please add label

**Comment by twrightsman** [comment]
I reverted the pinning relaxation after re-reading uptream's SemVer plans, which will start with the next major or minor version, not sure.

**Comment by mencian** [comment]
Thanks @twrightsman for taking the time to tidy up the patches and sorry for the delay. I have also submitted the patch upstream (see [smarco/WFA2-lib#85](https://github.com/smarco/WFA2-lib/pull/85)).

**Review by mencian — APPROVED** [review]

**Pull request merged**
