### PR TITLE
UPDATE migrate-n to migrate-3x

### PR DESCRIPTION
**Pull request by pbeerli**
I updated the migrate-n recipe, the source of the software and its description was adapted to the newest version available. To make clear that this is recipe is about the migrate 3x series I also changed the recipe name (in anticipation for another addition of migrate-4x in the future.

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by pbeerli** [comment]
I updated, and tested using local circleli, it fails at the very end, I do not understand the error message, it seems to compile and link.

**Comment by pbeerli** [comment]
@BiocondaBot please add label

**Comment by lecorguille** [comment]
Hi @pbeerli,
Are migrate-3x and migrate-4x 2 forks that are maintained separately?
Because, we usually provide different versions per package, not one package per version.

You will see here : [recipes/bamtools/](https://github.com/bioconda/bioconda-recipes/tree/master/recipes/bamtools), that you can have a "lastest" version of a package and still create an old one on the same folder.

**Comment by pbeerli** [comment]
> Hi @pbeerli,
> Are migrate-3x and migrate-4x 2 forks that are maintained separately?
> Because, we usually provide different versions per package, not one package per version.
> 
> You will see here : [recipes/bamtools/](https://github.com/bioconda/bioconda-recipes/tree/master/recipes/bamtools), that you can have a "lastest" version of a package and still create an old one on the same folder.

Oh, I see, I thought that using migrate-3x and migrate-4x is along the line of python2.7 and python3, but I have no problem to specify the recipe the same way as bamtools is set up; we should move back to call the recipe migrate-n (btw I never figured out how to checkout _your_ changes, I am happy work on that and also include the 3.7 changes there, but I would need some help to checkout  the basic recipe folder (and I guess, reset the stuff I did with migrate-3x)

**Pull request closed without merging**
