### PR TITLE
Update scar recipe with new repo name

### PR DESCRIPTION
**Pull request by fgypas**
Update scar recipe with new repo name

### CODE REVIEW

**Comment by fgypas** [comment]
@BiocondaBot please add label

**Review by CaibinSh — APPROVED** [review]

**Comment by fgypas** [comment]
@BiocondaBot please merge

**Comment by fgypas** [comment]
@BiocondaBot please add label

**Review by alienzj — APPROVED** [review]

**Comment by alienzj** [comment]
@BiocondaBot please merge

**Pull request merged**
