### PR TITLE
quast: Add Python 3

### PR DESCRIPTION
**Pull request by sjackman**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR updates an existing recipe.

### CODE REVIEW

**Comment by sjackman** [comment]
```
  File "/opt/conda/conda-bld/quast_1539451807470/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.5/site-packages/quast-5.0.0-py3.5.egg/quast_libs/site_packages/joblib2/disk.py", line 55

    except OSError, e:

                  ^

SyntaxError: invalid syntax
```
https://circleci.com/gh/bioconda/bioconda-recipes/29550

@alexeigurevich Is QUAST 5 is expected to working with Python 3?

**Comment by PertuyF** [comment]
@sjackman Looks like python2 libs included in `quast_libs/site_packages/` get byte compiled at install, causing the error.
Moreover, a number of libraries are compiled by Quast that are available as conda packages. Maybe some cleaning would be required when building the conda package for Quast?

**Comment by PertuyF** [comment]
@alexeigurevich That's a great news, looking forward version 5.1.0 then.
@sjackman If you want to go through this PR, it looks like it is possible to [skip compiling some .pyc](https://conda.io/docs/user-guide/tasks/build-packages/define-metadata.html#skip-compiling-some-py-files-into-pyc-files) within the recipe. together with patching `quast_libs/site_packages/simplejson/tool.py
`  this could be a temporary temporary solution to most of these python 2/3 errors.

**Comment by PertuyF** [comment]
@sjackman Testing what I suggested earlier. Feel free to revert the commits if there is any problem.

**Comment by sjackman** [comment]
@PertuyF I have limited time to troubleshoot this particular issue. Would you like to adopt this PR?

**Comment by dpryan79** [comment]
This has since been handled

**Pull request closed without merging**
