### PR TITLE
Test new zlib less Docker

### PR DESCRIPTION
**Pull request by bgruening**
* [x] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by bgruening** [comment]
This one actually should fail with the new zlib less Docker image.

**Comment by kyleabeauchamp** [comment]
Maybe because we don't have a test on this one?  AFAIK just running `bwa` should print the help string...

**Comment by bgruening** [comment]
lol @kyleabeauchamp you are absolutely right. Why does this one have no test? I just picked it by chance :)
Thanks for the pointer! We should implement a linting of yaml files. At lest one test, if cmake as dependency, gcc/llvm as well and so on.

**Comment by kyleabeauchamp** [comment]
It also seems to be non-compliant w.r.t. our GCC / LLVM annotation conventions as well?  Not sure.

**Comment by kyleabeauchamp** [comment]
It might be because of stdout versus stderr printing stuff, which can be tricky to handle for some executables.  Someone probably knows how to do it though :)

**Comment by bgruening** [comment]
Give me a sec I will work on this.

**Comment by bgruening** [comment]
Ok let's see if this is finally failing :)

**Comment by bgruening** [comment]
@kyleabeauchamp still not failing. But we have enhanced it :)

**Comment by kyleabeauchamp** [comment]
Agreed.

**Comment by bgruening** [comment]
@kyleabeauchamp isn't it nice - it's failing! :)

**Pull request merged**
