### PR TITLE
Adds Rdkit to bioconda

### PR DESCRIPTION
**Pull request by bgruening**
This is taken from the official rdkit conda channel https://github.com/rdkit/conda-rdkit with a fix for OS-X builds.

### CODE REVIEW

**Comment by kyleabeauchamp** [comment]
If they already have a channel, does it make more sense to just install
their package?  Also, is cheminformatics a bit outside the scope of
bioconda?

**Comment by bgruening** [comment]
There channel does not compile against an old centos build as far as I can see.
@kyleabeauchamp does bioconda has a scope? I see this more like a universal package repository.

**Comment by kyleabeauchamp** [comment]
Scope is a question for @johaneskoster

There channel does not compile against an old centos build as far as I can
see.
@kyleabeauchamp <https://github.com/kyleabeauchamp> does bioconda has a
scope? I see this more like a universal package repository.

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/bioconda/bioconda-recipes/pull/1101#issuecomment-198957053>

**Comment by kyleabeauchamp** [comment]
Ooops meant @johanneskoester

**Comment by kyleabeauchamp** [comment]
For example, here are some conda builds of rdkit that are done with a similar Centos VM:

https://anaconda.org/omnia/rdkit/files

**Comment by johanneskoester** [comment]
Well, the scope of bioconda is bioinformatics. If rdkit is needed also in bioinformatics context, it makes sense to include it here, so I'm fine with that. @bgruening, if the rdkit guys are already aware of conda, it might be reasonable to ask them if they are interested to move their conda-related distribution to bioconda entirely. I think it is desirable to have as many upstream devs active on bioconda as possible, because it will reduce the maintenance effort for the rest of us.

**Comment by kyleabeauchamp** [comment]
So right now there are rdkit recipes provided by the authors themselves and by omnia (https://github.com/omnia-md/conda-recipes), which is a computational chemistry analog to bioconda.  I'm just saying that we shouldn't over-extend ourselves.

**Comment by bgruening** [comment]
@kyleabeauchamp if there is any reason not to put it here I'm happy to move to an other repository.
One reason I would like to have something centralised is to have the ability to mirror tarballs like described here: https://github.com/bioconda/bioconda-recipes/issues/1015

@johanneskoester already ask but no respond yet: https://github.com/rdkit/conda-rdkit/issues/13

Bioinformatics has such a big scope nowadays if we want to restrict this repo, we should be more clear about this. What about literature mining? Molecular dynamics? Imaging? All of this is possible in Galaxy and is actively developed, I would rather have one giant repo with shared maintenance than several distributed.

@kyleabeauchamp what do you mean with `over-extend ourselves`. Wouldn’t it be desirable to join forces with the omnia-md guys?

**Comment by johanneskoester** [comment]
That's right as well. If there is a recipe that depends on rdkit, we could also add omnia to the list of channels we are depending on (which now only contains the r channel).

To generalize, we could think about the following rule. Anything that goes into bioconda, has to be

* relevant in bioinformatics
* not provided in an organized channel that appears to be of equal sustainability as bioconda

While the former is ok for rdkit, the latter is somehow violated, because omnia appears to be reliable and well maintained as well.

@bioconda/core any opinions?

**Comment by kyleabeauchamp** [comment]
Regarding joining forces, I don't think there's enough overlap in scope (bioinformatics versus computational chemistry) for that to make sense.  There are also some niche requirements for building computational chemistry software (MPI, GPU, boatloads of legacy fortran) that are not as relevant for most bioinformatics software.  The place where joining forces would make the most sense is sharing the build system, scripts, and virtual machines to ensure compatibiltiy. 

But I don't want to be a showstopper here--I'm not strictly opposed to placing the recipe here.  I'm just hoping that it will be put in the place where it is most likely to be maintained and used by as many eyes as possible.

**Comment by bgruening** [comment]
@kyleabeauchamp what is the disadvantage of having everything in one channel? Even if we *only* overlap in sharing build systems and scripts, what do we gain from separate conda-repositories and channels.

Have you seen https://conda-forge.github.io ... I guess the idea is really to put everything together and not pulling it apart.

For example I have an osra package in development, this is cheminformatics image recognition and depends on GraphicsMagick. Does this all belong into a image-recognition repo, a cheminformatics repo. Where do I store GraphicsMagick? Do we need to connect all repos because the omnia-md wants to use the GraphicsMagick from bioconda and vice versa?
If we do so, why not having one giant repo like https://conda-forge.github.io?

**Comment by kyleabeauchamp** [comment]
I think the down side is maintenance.  It takes effort to maintain
packages, and i think a curated list of domain specific packages is easiest
to maintain.  But again, i dont want to stop you here so im flexible.  We
can always refactor later.

**Comment by johanneskoester** [comment]
You both have good points. So far, the policy has been, if one of us needs a package and it is not in the main channel, he adds it to bioconda. Let's stick to that for now. As Kyle says, we can always refine that strategy later.

I think it is good to separate between conda-forge and bioconda, because we as a scientific community have different needs and goals than general purpose packaging. Asking the omnia guys if they want to join us is another story and would actually make sense.

**Pull request merged**
