### PR TITLE
Unicycler 0.4.0

### PR DESCRIPTION
**Pull request by karel-brinda**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by bgruening** [comment]
This PR is blocked by a new GCC version, which should be released soon hopefully.
Thanks @karel-brinda!

**Comment by cbrueffer** [comment]
Unicycler was updated to 0.4.1 in 4903135666a4245f7996b07566050898757b1681, can this PR be closed?

**Comment by bgruening** [comment]
Not yet, we don't have a recent compiler and I try to build it locally with a recent GCC for the meantime.

**Comment by bgruening** [comment]
Yes, I think we can close this PR. We either need to wait for a new GCC version, or I can push it from local as soon as I get it compiled.

**Pull request closed without merging**
