### PR TITLE
Update gembs to 3.5.0

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`gembs`](https://bioconda.github.io/recipes/gembs/README.html): **3.2.0** &rarr; **3.5.0**

[install with bioconda](http://bioconda.github.io/recipes/gembs/README.html) [Conda](https://anaconda.org/bioconda/gembs/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/gembs`](https://github.com//bioconda/bioconda-recipes/tree/bump/gembs/recipes/gembs) (click to view/edit other files)
Summary | gemBS is a bioinformatics pipeline designed for high throughput analysis of DNA methylation from Whole Genome Bisulfite Sequencing data (WGBS).
Home | [https://github.com/heathsc/gemBS](https://github.com/heathsc/gemBS)
Releases |[https://github.com/heathsc/gemBS/tags](https://github.com/heathsc/gemBS/tags)
Author | `@heathsc`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by JakeLehle** [comment]
I made a little bit more progress on this pull request got but stuck again. 
The lint_linux install test is erroring out saying that there are missing dependencies
image

But I made sure all of them should be available in the meta.yaml file.
image
The build section has make listed, and conda v3 compiler c should bring in gcc.
The host section has python and bzip2 which should take care of the library dependencies it's requesting i thought.

Could anyone from @bioconda/core take a look at this and see if I made a simple mistake or let me know if I have to implicitly list those two libraries in the host section. I can make the change and finish the pull request from there.

Thanks,
Jake

**Comment by dpryan79** [comment]
I think we need to just patch the hell out of this. I had previously tries to get around this by doing a minimal install and telling setup.py to no compile gem3 et al., but that seems to not have worked.

**Comment by JakeLehle** [comment]
Thanks for helping out @dpryan79 . Yeah, the previous version had a patch with bcftools that I tried to take out and start fresh cause I thought it was causing more issues than helping but the build is probably gonna need a bunch of workarounds. Also thanks for adding the build.sh I didn't know if I could get around having one of those or not.

**Comment by JakeLehle** [comment]
Hey @dpryan79 looks like it's still having some problems with mextr from htslib. Is there anything I can work on to help you out with this? Let me know and I can dig around and teach myself most of whatever I'll need to try and get this thing finished off.

**Comment by dpryan79** [comment]
Finally patched the damn thing enough.

**Comment by dpryan79** [comment]
I really dislike how this is installed though, the tools should be their own package that are a dependency of the pure-python package. As is, we're building 8 packages for each version when there's really no need for that. I guess we need some sort of arch-python concept rather than `noarch: python` in conda.

**Review by dpryan79 — APPROVED** [review]

**Comment by JakeLehle** [comment]
Well, it's better than what I could put together right now. There is an entire re-write to the gembs package that replaces the C compiler with rust that might be easier to package in the future, but I haven't seen anyone really forking the repository or using it yet. I'm still playing around with getting it set up for my own use to compare it. I've been poking through pull requests to see what other packages have started using rust to teach myself and start preparing now haha. 

Thank you for all your help with this man. I owe you a drink if you are ever in Texas or I'm at a conference in Germany or  Switzerland.

**Pull request merged**
