### PR TITLE
kraken2: Add dependencies rsync & wget

### PR DESCRIPTION
**Pull request by dfornika**
:information_source:
Bioconda has finished the [GCC7 migration](https://github.com/bioconda/bioconda-recipes/issues/13578). If you are dealing with C/C++ or Python package it can be that you need to rebuild other dependent packages. [Bioconda utils - update-pinning](https://bioconda.github.io/updating.html#updating-recipes-for-a-pinning-change) will assist you with that. If you have any questions please use [issue 13578](https://github.com/bioconda/bioconda-recipes/issues/13578).

----------------

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by dfornika** [comment]
Rsync is required when downloading database files.

**Comment by druvus** [comment]
@dfornika you also need to bump build number to get a new build

**Comment by dfornika** [comment]
It seems to be failing to find `omp.h` on macOS:

```
x86_64-apple-darwin13.4.0-clang++ -fopenmp -Wall -std=c++11 -O3 -DLINEAR_PROBING -D_FORTIFY_SOURCE=2 -mmacosx-version-min=10.9  -c -o seqreader.o seqreader.cc
In file included from seqreader.cc:7:
In file included from ./seqreader.h:10:
In file included from ./kraken2_headers.h:30:
./omp_hack.h:11:10: fatal error: 'omp.h' file not found
#include <omp.h>
         ^~~~~~~
1 error generated.
make: *** [seqreader.o] Error 1
```

**Comment by dfornika** [comment]
Thanks @bgruening !

**Comment by bgruening** [comment]
Ha, this actually helped :) Nice!

**Comment by mdehollander** [comment]
We are getting this error when building/downloading the kraken2 database:
```
Step 1/2: Performing rsync file transfer of requested files

rsync: error while loading shared libraries: libiconv.so.2: cannot open shared object file: No such file or directory

rsync_from_ncbi.pl: rsync error, exiting: 32512
```
If we install libiconv with conda the building process works. I think this package needs to be added to the `meta.yaml` file at the run section.

**Comment by dfornika** [comment]
@mdehollander Your issue sounds similar to the ones reported [here](https://github.com/bioconda/bioconda-recipes/issues/14076) and [here](https://github.com/conda-forge/rsync-feedstock/issues/1).

I think the solution is to add `libiconv` as a dependency to the `rsync` recipe. I'll submit a pull request to https://github.com/conda-forge/rsync-feedstock

**Pull request merged**
