### PR TITLE
Update dysgu to 1.4.0

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`dysgu`](https://bioconda.github.io/recipes/dysgu/README.html): **1.3.16** &rarr; **1.4.0**

[install with bioconda](http://bioconda.github.io/recipes/dysgu/README.html) [Conda](https://anaconda.org/bioconda/dysgu/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/dysgu`](https://github.com//bioconda/bioconda-recipes/tree/bump/dysgu/recipes/dysgu) (click to view/edit other files)
Summary | A collection of tools for calling structural variants using short or long reads
Home | [https://github.com/kcleal/dysgu](https://github.com/kcleal/dysgu)
Releases |[https://github.com/kcleal/dysgu/tags](https://github.com/kcleal/dysgu/tags)
Recipe Maintainer(s) | @kcleal
Author | `@kcleal`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by kcleal** [comment]
@BiocondaBot rebuild

**Comment by kcleal** [comment]
@BiocondaBot hello

**Comment by kcleal** [comment]
@BiocondaBot rebuild

**Comment by kbseah** [comment]
triggering new checks, osx problem should be resolved with #41526

**Review by kbseah — APPROVED** [review]

**Pull request merged**
