### PR TITLE
Update comet-ms recipe

### PR DESCRIPTION
**Pull request by wfondrie**
This PR updates the comet-ms recipe to v2021010 and re-enables MacOS support.

### CODE REVIEW

**Comment by wfondrie** [comment]
@BiocondaBot please add label

**Comment by wfondrie** [comment]
Actually there seems to be a problem: the tests say that this recipe is blacklisted. 

Any idea how to fix this so that the tests can actually run (and also remove the review & merge label for now)?

**Comment by wfondrie** [comment]
@BiocondaBot rebuild

**Comment by wfondrie** [comment]
It's finally working 🎉

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
@wfondrie great work!

**Comment by bgruening** [comment]
@bioconda-bot please merge

**Pull request merged**
