### PR TITLE
Update kleborate recipe

### PR DESCRIPTION
**Pull request by rpetit3**
Currently kleborate includes reference data but after the first run blast databases are created.

For the contianers this leads to permissions errors. This PR runs kleborate once to build the databases and make the containers usable

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by rpetit3** [comment]
Here's the error using the current docker container  (BLAST databases not built already)
```
docker run --rm -u $(id -u):$(id -g) -v ${PWD}:/data quay.io/biocontainers/kleborate:2.1.0--pyhdfd78af_0 kleborate -a /data/reference.fasta --all -o /data/kleborate.txt
Error: NCBI C++ Exception:
    T0 "/opt/conda/conda-bld/blast_1626166529662/work/blast/c++/src/objtools/blast/seqdb_writer/build_db.cpp", line 1053: Error: (CMultisourceException::eInvalid) BLASTDB::ncbi::CBuildDatabase::CreateDirectories() - You do not have write permissions on 'data'

strain  species ST      virulence_score resistance_score        Yersiniabactin  YbST    Colibactin      CbST    Aerobactin      AbST    Salmochelin     SmST    RmpADC  RmST    rmpA2   wzi     K_locus K_locus_confidence      O_locus O_locus_confidence      AGly_acquired   Col_acquired    Fcyn_acquired   Flq_acquired    Gly_acquired    MLS_acquired    Phe_acquired    Rif_acquired    Sul_acquired    Tet_acquired    Tgc_acquired    Tmt_acquired    Bla_acquired    Bla_inhR_acquired       Bla_ESBL_acquired       Bla_ESBL_inhR_acquired  Bla_Carb_acquired      Bla_chr  SHV_mutations   Omp_mutations   Col_mutations   Flq_mutations   truncated_resistance_hits       spurious_resistance_hits
Traceback (most recent call last):
  File "/usr/local/bin/kleborate", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/kleborate/__main__.py", line 61, in main
    results.update(get_all_virulence_results(data_folder, contigs, args))
  File "/usr/local/lib/python3.8/site-packages/kleborate/__main__.py", line 477, in get_all_virulence_results
    virulence_results = [get_ybt_mlst_results(data_folder, contigs, args),
  File "/usr/local/lib/python3.8/site-packages/kleborate/__main__.py", line 504, in get_ybt_mlst_results
    return get_virulence_cluster_results(data_folder, contigs, 'ybt_alleles.fasta',
  File "/usr/local/lib/python3.8/site-packages/kleborate/__main__.py", line 460, in get_virulence_cluster_results
    mlst_blast(seqs, database, 'yes', [contigs], min_cov=args.min_coverage,
  File "/usr/local/lib/python3.8/site-packages/kleborate/mlstBLAST.py", line 46, in mlst_blast
    hits = run_blastn(seqs, contigs, min_spurious_cov, min_spurious_ident)
  File "/usr/local/lib/python3.8/site-packages/kleborate/blastn.py", line 22, in run_blastn
    build_blast_database_if_needed(db)
  File "/usr/local/lib/python3.8/site-packages/kleborate/blastn.py", line 138, in build_blast_database_if_needed
    subprocess.check_call('makeblastdb -dbtype nucl -in ' + seqs, stdout=devnull,
  File "/usr/local/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'makeblastdb -dbtype nucl -in /usr/local/lib/python3.8/site-packages/kleborate/data/ybt_alleles.fasta' returned non-zero exit status 255.
```

Here's the output using docker container from this PR (BLAST databases built already)
```
curl -L "https://168931-42372094-gh.circle-artifacts.com/0/tmp/artifacts/images/kleborate%3A2.1.0--pyhdfd78af_1.tar.gz" | gzip -dc | docker load

docker run --rm -u $(id -u):$(id -g) -v ${PWD}:/data quay.io/biocontainers/kleborate:2.1.0--pyhdfd78af_1 kleborate -a /data/reference.fasta --all -o /data/kleborate.txt
strain  species ST      virulence_score resistance_score        Yersiniabactin  YbST    Colibactin      CbST    Aerobactin      AbST    Salmochelin     SmST    RmpADC  RmST    rmpA2   wzi     K_locus K_locus_confidence      O_locus O_locus_confidence      AGly_acquired   Col_acquired    Fcyn_acquired   Flq_acquired    Gly_acquired    MLS_acquired    Phe_acquired    Rif_acquired    Sul_acquired    Tet_acquired    Tgc_acquired    Tmt_acquired    Bla_acquired    Bla_inhR_acquired       Bla_ESBL_acquired       Bla_ESBL_inhR_acquired  Bla_Carb_acquired      Bla_chr  SHV_mutations   Omp_mutations   Col_mutations   Flq_mutations   truncated_resistance_hits       spurious_resistance_hits
reference       unknown NA      0       0       -       0       -       0       -       0       -       0       -       0       -       -       unknown (best match = KL125)    None    unknown (best match = OL102)    None    -       -       -       -       -       -       -      -
(

```

**Comment by rpetit3** [comment]
@biocondabot please add label

**Review by grst — APPROVED** [review]
LGTM!

**Comment by grst** [comment]
@bioconda-bot, please merge

**Pull request merged**
