### PR TITLE
[BULK] Many R 3.5 only packages

### PR DESCRIPTION
**Pull request by dpryan79**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [x] This PR does something else (explain below).

There are a bunch of additional packages that will need to be made R 3.5 only, due to dependencies that are only built for 3.5. Next time we should probably just do this with all bioconductor packages just to make life easier.

Follow up to #11406 from @nsoranzo

### CODE REVIEW

**Comment by bgruening** [comment]
> Next time we should probably just do this with all bioconductor packages just to make life easier.

:+1: I have a Déjà-vu. We started to discuss this somewhere isn't it?

**Comment by bgruening** [comment]
imho it should be part of the bioconductor skeleton script.

**Comment by dpryan79** [comment]
Agreed all around. I think I dismissed the suggestion :P Hindsight is 20 20 as the saying goes.

**Comment by nsoranzo** [comment]
Isn't this something that conda should do automatically? E.g.: `bioconductor-affy` depends on `'bioconductor-biocinstaller >=1.30.0,<1.32.0'`, which in turn specifies `r-base >=3.5.0` ?

**Comment by nsoranzo** [comment]
@dpryan79 Do you have some logs at hand? I cannot find an example of this in the logs on circleci.

**Comment by dpryan79** [comment]
Not at hand, no. When/if I see one of these I'll post it.

**Comment by dpryan79** [comment]
The current build has an example of this https://circleci.com/gh/bioconda/bioconda-recipes/30048

I'll copy it below:

```
Traceback (most recent call last):

  File "/opt/conda/lib/python3.6/site-packages/conda_build/environ.py", line 748, in get_install_actions

    actions = install_actions(prefix, index, specs, force=True)

  File "/opt/conda/lib/python3.6/site-packages/conda/common/io.py", line 46, in decorated

    return f(*args, **kwds)

  File "/opt/conda/lib/python3.6/site-packages/conda/plan.py", line 541, in install_actions

    txn = solver.solve_for_transaction(prune=prune, ignore_pinned=not pinned)

  File "/opt/conda/lib/python3.6/site-packages/conda/core/solve.py", line 518, in solve_for_transaction

    force_remove, force_reinstall)

  File "/opt/conda/lib/python3.6/site-packages/conda/core/solve.py", line 451, in solve_for_diff

    final_precs = self.solve_final_state(deps_modifier, prune, ignore_pinned, force_remove)

  File "/opt/conda/lib/python3.6/site-packages/conda/core/solve.py", line 344, in solve_final_state

    solution = r.solve(tuple(final_environment_specs))  # return value is List[dist]

  File "/opt/conda/lib/python3.6/site-packages/conda/common/io.py", line 46, in decorated

    return f(*args, **kwds)

  File "/opt/conda/lib/python3.6/site-packages/conda/resolve.py", line 857, in solve

    self.find_conflicts(specs)

  File "/opt/conda/lib/python3.6/site-packages/conda/resolve.py", line 244, in find_conflicts

    raise UnsatisfiableError(bad_deps)

conda.exceptions.UnsatisfiableError: The following specifications were found to be in conflict:

  - bioconductor-multiassayexperiment[version='>=1.6.0,<1.8.0'] -> r-base[version='>=3.5.1,<3.5.2.0a0']

  - r-base=3.4.1

Use "conda info <package>" to see the dependencies for each package.



During handling of the above exception, another exception occurred:



Traceback (most recent call last):

  File "/opt/conda/bin/conda-build", line 11, in <module>

    sys.exit(main())

  File "/opt/conda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 438, in main

    execute(sys.argv[1:])

  File "/opt/conda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 429, in execute

    verify=args.verify)

  File "/opt/conda/lib/python3.6/site-packages/conda_build/api.py", line 201, in build

    notest=notest, need_source_download=need_source_download, variants=variants)

  File "/opt/conda/lib/python3.6/site-packages/conda_build/build.py", line 2204, in build_tree

    notest=notest,

  File "/opt/conda/lib/python3.6/site-packages/conda_build/build.py", line 1210, in build

    output_metas = expand_outputs([(m, need_source_download, need_reparse_in_env)])

  File "/opt/conda/lib/python3.6/site-packages/conda_build/render.py", line 689, in expand_outputs

    for (output_dict, m) in _m.get_output_metadata_set(permit_unsatisfiable_variants=False):

  File "/opt/conda/lib/python3.6/site-packages/conda_build/metadata.py", line 1990, in get_output_metadata_set

    bypass_env_check=bypass_env_check)

  File "/opt/conda/lib/python3.6/site-packages/conda_build/metadata.py", line 714, in finalize_outputs_pass

    permit_unsatisfiable_variants=permit_unsatisfiable_variants)

  File "/opt/conda/lib/python3.6/site-packages/conda_build/render.py", line 478, in finalize_metadata

    exclude_pattern)

  File "/opt/conda/lib/python3.6/site-packages/conda_build/render.py", line 373, in add_upstream_pins

    permit_unsatisfiable_variants, exclude_pattern)

  File "/opt/conda/lib/python3.6/site-packages/conda_build/render.py", line 339, in _read_upstream_pin_files

    permit_unsatisfiable_variants=permit_unsatisfiable_variants)

  File "/opt/conda/lib/python3.6/site-packages/conda_build/render.py", line 125, in get_env_dependencies

    channel_urls=tuple(m.config.channel_urls))

  File "/opt/conda/lib/python3.6/site-packages/conda_build/environ.py", line 750, in get_install_actions

    raise DependencyNeedsBuildingError(exc, subdir=subdir)

conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-64: {'r-base=3.4.1', "r-base[version='>=3.5.1,<3.5.2.0a0']"}

[0m

09:57:05 [31mBIOCONDA ERROR[0m BUILD FAILED recipes/bioconductor-classifyr
```

**Comment by bgruening** [comment]
Afaik a specific bioc version is also bound to a specific R version, so its just saver to overrule the conda-forge pinning (at least 2 different R versions) and pin all bioc packages to only one specific R version.

**Comment by nsoranzo** [comment]
Right, thanks!

**Pull request merged**
