### PR TITLE
Add tttrlib

### PR DESCRIPTION
**Pull request by tpeulen**
Please add tttrlib to bioconda.

tttrlib is a library to read and process time-resolved photon counting data widely used
in fluorescence spectroscopy and microscopy.

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

### General instructions

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

### Instructions for avoiding API, ABI, and CLI breakage issues
Conda is able to record and lock (a.k.a. pin) dependency versions used at build time of other recipes.
This way, one can avoid that expectations of a downstream recipe with regards to API, ABI, or CLI are violated by later changes in the recipe.
If not already present in the meta.yaml, make sure to specify `run_exports` (see [here](https://bioconda.github.io/contributor/linting.html#missing-run-exports) for the rationale and comprehensive explanation).
Add a `run_exports` section like this:

```yaml
build:
  run_exports:
    - ...

```

with `...` being one of:

| Case                             | run_exports statement                                               |
| -------------------------------- | ------------------------------------------------------------------- |
| semantic versioning              | `{{ pin_subpackage("myrecipe", max_pin="x") }}`     |
| semantic versioning (0.x.x)      | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}`   |
| known breakage in minor versions | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| known breakage in patch versions | `{{ pin_subpackage("myrecipe", max_pin="x.x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| calendar versioning              | `{{ pin_subpackage("myrecipe", max_pin=None) }}`    |

while replacing `"myrecipe"` with either `name` if a `name|lower` variable is defined in your recipe or with the lowercase name of the package in quotes.

### Bot commands for PR management

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

Note that the <code>@BiocondaBot please merge</code> command is now depreciated. Please just squash and merge instead.

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by mencian** [comment]
The error seems to be isolated in `osx` with python `3.12`.

**Comment by tpeulen** [comment]
On my local Apple M1 setup (x86_64 Conda), the `tttrlib` recipe builds successfully across multiple Python versions, including 3.12, with the command:

```shell
bioconda-utils build --git-range master --package tttrlib
```

For example, here’s the output from the build with Python 3.12:

```plaintext
17:17:15 BIOCONDA INFO (OUT) "tttrlib-0.25.0-py312h3d580cb_0.tar.bz2": {
17:17:15 BIOCONDA INFO (OUT)   "recipe": {
17:17:15 BIOCONDA INFO (OUT)     "c_compiler": "clang",
17:17:15 BIOCONDA INFO (OUT)     "cxx_compiler": "clangxx",
17:17:15 BIOCONDA INFO (OUT)     "hdf5": "1.14.3",
17:17:15 BIOCONDA INFO (OUT)     "numpy": "1.26",
17:17:15 BIOCONDA INFO (OUT)     "python": "3.12.* *_cpython",
17:17:15 BIOCONDA INFO (OUT)     "target_platform": "osx-64"
17:17:15 BIOCONDA INFO (OUT)   }
17:17:15 BIOCONDA INFO (OUT) },
```

However, on the Bioconda build machine, CMake fails to locate `Python_NumPy_INCLUDE_DIRS`, even though it recognizes the Python version (3.12.7). I reviewed the project’s `CMakeLists.txt` to identify any unusual configurations but found that it follows a standard setup for Python discovery:

```cmake
MESSAGE(STATUS "Python version: '${PYTHON_VERSION}'")
cmake_policy(SET CMP0094 NEW)

FIND_PACKAGE(Python ${PYTHON_VERSION} EXACT COMPONENTS Interpreter Development.Module NumPy)
INCLUDE_DIRECTORIES(BEFORE ${Python_NumPy_PATH} ${Python_INCLUDE_DIRS})
LINK_LIBRARIES(${Python_LIBRARY} Python::NumPy)
```

In the builds, `Python_ROOT_DIR` cmake hint is set to `$ENV{CONDA_PREFIX}/bin`, resolving to `$BUILD_PREFIX/bin` during builds. This usually directs CMake correctly, but in the Bioconda environment (only Python 3.12), the issue persists.

The root cause is challenging to identify, possibly related to `NumPy` discovery in the Bioconda build machine, despite using standard `FIND_PACKAGE` logic.

**Comment by mencian** [comment]
@BiocondaBot please fetch artifacts

**Comment by mencian** [comment]
I'll push this PR out in the mean time to make this tool available for other users. Still not sure why `numpy` can't be found _only_ on `osx` `python >3.10`.

**Review by mencian — APPROVED** [review]

**Comment by tpeulen** [comment]
@mencian thank you so much. That was really helpful.

**Pull request merged**
