### PR TITLE
Update picrust2 to 2.4.2

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`picrust2`](https://bioconda.github.io/recipes/picrust2/README.html): **2.4.1** &rarr; **2.4.2**

[install with bioconda](http://bioconda.github.io/recipes/picrust2/README.html) [Conda](https://anaconda.org/bioconda/picrust2/files)

Info | Link
-----|-----
Recipe | [`recipes/picrust2`](https://github.com//bioconda/bioconda-recipes/tree/bump/picrust2/recipes/picrust2) (click to view/edit other files)
Releases |[https://github.com/picrust/picrust2/tags](https://github.com/picrust/picrust2/tags)
Author | `@picrust`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by gavinmdouglas** [comment]
Note that I made a separate PR for this version: https://github.com/bioconda/bioconda-recipes/pull/32085 . I'm not sure why the tests didn't pass there but did here.

Also this file also needs to be changed if this PR is used: recipes/picrust2/post-link.sh

**Comment by dpryan79** [comment]
@BiocondaBot please update

**Comment by dpryan79** [comment]
@BiocondaBot please update

**Comment by dpryan79** [comment]
@BiocondaBot please update

**Comment by dpryan79** [comment]
@BiocondaBot please update

**Pull request closed without merging**
