### PR TITLE
Update zol to v1.3.1 (try 2)

### PR DESCRIPTION
**Pull request by raufs**
Pull request to re-initialize zol update to v1.3.1 because BiocondaBot autobump didn't generate new builds.

In this pull-request - I have rescinded updates to specify `>=3` for python in the host subsection of the requirements in the meta.yaml. I have also updated build from `0` to `1`.

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by raufs** [comment]
Reverted build number back to `0` because technically there was never a build for the prior recipe and because the lint check fails otherwise. Now back to being stuck at the test_osx step similar to before.

**Comment by raufs** [comment]
@BiocondaBot please fetch artifacts

**Comment by raufs** [comment]
@BiocondaBot please fetch artifacts

**Comment by raufs** [comment]
@BiocondaBot please fetch artifacts

**Comment by raufs** [comment]
Thank you for fixing the issue with OSx builds! 

Artifact testing on macOS was successful: 

Please someone approve the commits - as I cannot accept my own PR.

```
(/Users/raufs/Downloads/OSXArtifacts/packages/osx-64/conda_env) Raufs-Mac-mini:osx-64 raufs$ zol -h | head -n 50
usage: zol [-h] [-i INPUT_DIR] -o OUTPUT_DIR [-it IDENTITY_THRESHOLD]
           [-ct COVERAGE_THRESHOLD] [-et EVALUE_THRESHOLD] [-fl] [-fd] [-r]
           [-d] [-ri] [-dt DEREP_IDENTITY] [-dc DEREP_COVERAGE]
           [-di DEREP_INFLATION] [-ibc] [-ces] [-aec] [-q] [-s] [-sg]
           [-cd CUSTOM_DATABASE] [-rgc] [-l LENGTH] [-w WIDTH] [-fgl]
           [-f FOCAL_GENBANKS] [-fc COMPARATOR_GENBANKS] [-c CPUS]
           [-mm MAX_MEMORY] [-v]

	Program: zol
	Author: Rauf Salamzade
	Affiliation: Kalan Lab, UW Madison, Department of Medical Microbiology and Immunology

	**************************************************************************************

                      oooooooooooo           ooooo
                     d'''''''d888'           `888'
                           .888P    .ooooo.   888
                          d888'    d88' `88b  888
                        .888P      888   888  888
                       d888'    .P 888   888  888       o
                     .8888888888P  `Y8bod8P' o888ooooood8

	**************************************************************************************

	zol is a lightweight software that can generate reports on conservation, annotation,
	and evolutionary statistics for defined orthologous/homologous loci (e.g. BGCs, phages,
	MGEs, or any genomic island / operon!).

	CONSIDERATIONS:
	---------------
	* It is advised that multiple GenBanks from the same genome/sample be concatenated into
	  a multi-record GenBank to account for fragmentation of gene-clusters and properly
	  calculate copy count of ortholog groups.
	* Locus tags cannot contain commas, if they do however, you can use the --rename_lt flag
	  to request new locus tags!
	* Ortholog group and homolog group are/were used inter-changeably in the code/comments. We
	  recommend using the term ortholog group which is more commonly used in literature for
	  the type of protein clustering we perform in zol. Since v1.28 - result files and logging
	  messages should largely use "ortholog group" or "OG".


options:
  -h, --help            show this help message and exit
  -i INPUT_DIR, --input_dir INPUT_DIR
                        Directory with orthologous/homologous locus-specific GenBanks.
                        Files must end with ".gbk", ".gbff", or ".genbank".
  -o OUTPUT_DIR, --output_dir OUTPUT_DIR
                        Parent output/workspace directory.
  -it IDENTITY_THRESHOLD, --identity_threshold IDENTITY_THRESHOLD
                        Minimum identity coverage for an alignment between protein

**Review by kbseah — APPROVED** [review]

**Pull request merged**
