### PR TITLE
a clean pgcgap branch

### PR DESCRIPTION
**Pull request by dpryan79**
:information_source:
If this is your first pull request to Bioconda please ping `@bioconda/core` so it can be reviewed and to request being added as a member of the Bioconda team. Members of the Bioconda team are able to merge their own pull requests once tests and linting have passed.

----------------

* [ ] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [ ] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by dpryan79** [comment]
This is a clean version of https://github.com/bioconda/bioconda-recipes/pull/15412

**Comment by dpryan79** [comment]
@bioconda-bot merge

**Comment by liaochenlanruo** [comment]
Hi @dpryan79, 
When I run "conda install pgcgap", errors occured as following:、
Can you tell me how to fix it?
Thanks!
```
lhl@liaochenlanruo:~$ conda install pgcgap
Collecting package metadata: done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - pgcgap

Current channels:

  - https://conda.anaconda.org/bioconda/linux-64
  - https://conda.anaconda.org/bioconda/noarch
  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/linux-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://conda.anaconda.org/r/linux-64
  - https://conda.anaconda.org/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

**Comment by dpryan79** [comment]
Whatever anaconda does on the backend to migrate packages across cloudflare seems to be broken. It doesn't look like anything that's been uploaded in the last ~16 hours is actually available. We've notified anaconda about this, but they may not get around to fixing this until Monday US time.

**Comment by dpryan79** [comment]
This is available now.

**Comment by liaochenlanruo** [comment]
> This is available now.

@dpryan79 Thank you very much for your help during this period of time！

**Pull request merged**
