### PR TITLE
Update pysam to 0.14

### PR DESCRIPTION
**Pull request by kyleabeauchamp**
* [ ] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [ ] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

cc @AndreasHeger

### CODE REVIEW

**Comment by kyleabeauchamp** [comment]
So pysam 0.14 wraps HTSLib 1.7, samtools 1.7, and BCFtools 1.6 (bcftools 1.7 has yet to be released).  Thus, I've rolled back the use of the global `CONDA_HTSLIB` variable in the pysam recipe.

**Comment by bgruening** [comment]
@kyleabeauchamp please look at the bulk branch. We have increased the HTSLIB env var there already. If you target the bulk I can merge it.

**Comment by kyleabeauchamp** [comment]
I think I want to avoid using the HTSLIB env variable because this recipe (v0.14) depends on a heterogenous mixture of versions (1.6 and 1.7).

**Comment by kyleabeauchamp** [comment]
See, e.g., https://github.com/pysam-developers/pysam/pull/609, for more reading.

**Comment by dpryan79** [comment]
Anyone object to this getting merged in? It certainly looks good to go.

**Comment by bgruening** [comment]
My only concern is that this will not make it into many environments because of the strict pinning.
@kyleabeauchamp please put the ENV vars back in as soon as bcftools are released. 

Thanks for the update!

**Comment by AndreasHeger** [comment]
Thanks @kyleabeauchamp . Apologies for the version mix, but I thought it would be important to get a htslib 1.7 version out despite bcftools not at the same version.

**Comment by kyleabeauchamp** [comment]
I totally agree.  Thanks!

**Pull request merged**
