### PR TITLE
Gd jpeg

### PR DESCRIPTION
**Pull request by bgruening**
* [x] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by bgruening** [comment]
@johanneskoester here is the perl bug again with the old buildsystem :(

**Comment by johanneskoester** [comment]
The bug is gone when using conda 2.0.0, I'm working on it in that test branch. However, it points to another problem that we need to solve soon: since we use perl-threaded, the automatic pinning does not work for us. We either need to do that manually for all perl packages or rename our threaded perl build to "perl". This would still work with the new channel priorities. Also, we could encode the threaded feature as a proper "feature", similar to how continuum is doing it with e.g. MKL.

**Comment by bgruening** [comment]
@johanneskoester has anyone tried to get the threaded feature upstream?
I can imagine the conda-forge people would like to have this in the main perl package. I think this would be much more preferable.

**Comment by johanneskoester** [comment]
Indeed. I never really bothered with perl, but @tomkinsc might know.

**Comment by tomkinsc** [comment]
There's a minor performance penalty to using single-threaded perl scripts on `perl-threaded`, but IMHO the benefits for performance and compatibility justify renaming `perl-threaded` to `perl`. (Maybe making a `perl-singlethreaded`) I haven't contacted anyone upstream about this.

**Comment by bgruening** [comment]
Oh this is great! Than lets do sed 's/perl-threaded/perl/' as soon as we rebuild everything and @johanneskoester merges the build infrastructure.

@tomkinsc do you mind to submit a PR against https://github.com/conda-forge/perl-feedstock

**Comment by tomkinsc** [comment]
@bgruening: [Submitted](https://github.com/conda-forge/perl-feedstock/pull/6).

**Comment by tomkinsc** [comment]
Update: The build of perl with threads on conda-forge [is failing](https://circleci.com/gh/conda-forge/perl-feedstock/8), and I'm not sure of the fix (especially in their build environment). Any ideas, @bioconda/core?
https://github.com/conda-forge/perl-feedstock/pull/6#issuecomment-245012337

**Comment by johanneskoester** [comment]
Sorry, I have no experience with Perl unfortunately (or maybe fortunately ;-)).

**Pull request closed without merging**
