### PR TITLE
add recipe for pHierCC

### PR DESCRIPTION
**Pull request by rpetit3**
This PR adds a recipe for https://github.com/zheminzhou/pHierCC

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by rpetit3** [comment]
@biocondabot please fetch artifacts

**Comment by rpetit3** [comment]
# Test 1

## Conda 

### Setup environment
```
mamba create -y -n testphiercc -c conda-forge -c bioconda \
    'click>=7.0' 'matplotlib-base>=3.2.1' 'numba>=0.38.0' 'numpy>=1.18.1' \
    'pandas>=0.24.2' 'python>=3.6,<3.9' 'scikit-learn>=0.23.1' 'scipy>=1.3.2' \
    'sharedarray>=3.2.1'
conda activate testphiercc
```

### Test usage
```bash
pHierCC --help
Usage: pHierCC [OPTIONS]

  pHierCC takes a file containing allelic profiles (as in
  https://pubmlst.org/data/) and works out hierarchical clusters of the full
  dataset based on a minimum-spanning tree.

Options:
  -p, --profile TEXT           [INPUT] name of a profile file consisting of a
                               table of columns of the ST numbers and the
                               allelic numbers, separated by tabs. Can be
                               GZIPped.  [required]
  -o, --output TEXT            [OUTPUT] Prefix for the output files consisting
                               of a  NUMPY and a TEXT version of the
                               clustering result.   [required]
  -a, --append TEXT            [INPUT; optional] The NPZ output of a previous
                               pHierCC run (Default: None).
  -m, --allowed_missing FLOAT  [INPUT; optional] Allowed proportion of missing
                               genes in pairwise comparisons (Default: 0.03).
  -n, --n_proc INTEGER         [INPUT; optional] Number of processes (CPUs) to
                               use (Default: 4).
  --help                       Show this message and exit.

HCCeval --help
Usage: HCCeval [OPTIONS]

  evalHCC evaluates a HierCC scheme using varied statistic summaries.

Options:
  -p, --profile TEXT      [INPUT] Name of a profile file consisting of a table
                          of columns of the ST numbers and the allelic
                          numbers, separated by tabs. Can be GZIPped.
                          [required]
  -c, --cluster TEXT      [INPUT] Name of the pHierCC text output. Can be
                          GZIPped.  [required]
  -o, --output TEXT       [OUTPUT] Prefix for the two output files.
                          [required]
  -s, --stepwise INTEGER  [INPUT; optional] Evaluate every <stepwise> levels
                          (Default: 10).
  -n, --n_proc INTEGER    [INPUT; optional] Number of processes (CPUs) to use
                          (Default: 4).
  --help                  Show this message and exit.
```

### Test imports
```bash
python
Python 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:04:18)
[GCC 10.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pHierCC
>>> dir(pHierCC)
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__']
```

### Test Examples
Examples are available from https://github.com/zheminzhou/pHierCC

```bash 
git clone git@github.com:zheminzhou/pHierCC.git
cd pHierCC

pHierCC -p examples/YERwgMLST.cgMLSTv1.profile0.gz -o examples/YERwgMLST.cgMLSTv1.HierCC0
2022-09-22 01:16:09,301 | Loaded in allelic profiles with dimension: 2999 and 1554. The first column is assumed to be type id.
2022-09-22 01:16:09,302 | Start HierCC assignments
2022-09-22 01:16:09,353 | Calculate distance matrix
2022-09-22 01:16:14,819 | Start Single linkage clustering
2022-09-22 01:16:14,981 | Attach genomes onto the tree.
2022-09-22 01:16:17,572 | NPZ  clustering result (for production mode): examples/YERwgMLST.cgMLSTv1.HierCC0.npz
2022-09-22 01:16:17,573 | TEXT clustering result (for visual inspection and HCCeval): examples/YERwgMLST.cgMLSTv1.HierCC0.HierCC.gz

HCCeval -p examples/YERwgMLST.cgMLSTv1.profile0.gz -c examples/YERwgMLST.cgMLSTv1.HierCC0.HierCC.gz -o examples/YERwgMLST.cgMLSTv1.HierCC.eval
2022-09-22 01:23:38,493 | Calculating NMIs...
2022-09-22 01:23:38,494 |     NMIs between level 0 and greater levels
2022-09-22 01:23:39,460 |     NMIs between level 100 and greater levels
2022-09-22 01:23:40,296 |     NMIs between level 200 and greater levels
2022-09-22 01:23:41,076 |     NMIs between level 300 and greater levels
... TRUNCATED 
2022-09-22 01:23:45,346 |     NMIs between level 1200 and greater levels
2022-09-22 01:23:45,508 |     NMIs between level 1300 and greater levels
2022-09-22 01:23:45,617 |     NMIs between level 1400 and greater levels
2022-09-22 01:23:45,677 |     NMIs between level 1500 and greater levels
2022-09-22 01:23:45,690 | Calculating pairwise distance ...
2022-09-22 01:23:50,924 | Calculating Silhouette score ...
2022-09-22 01:23:54,968 | Tab-delimited evaluation is saved in examples/YERwgMLST.cgMLSTv1.HierCC.eval.tsv
2022-09-22 01:23:54,968 | Visualisation is saved in examples/YERwgMLST.cgMLSTv1.HierCC.eval.pdf
```

Conda looks good

## Docker

### Pull Container
```
gzip -dc LinuxArtifacts/images/phiercc:1.24--pyhdfd78af_0.tar.gz | docker load
855c185876aa: Loading layer  623.2MB/623.2MB
Loaded image: quay.io/biocontainers/phiercc:1.24--pyhdfd78af_0
```

### Check usage
```
docker run --rm -u $(id -u):$(id -g) -v ${PWD}:/data quay.io/biocontainers/phiercc:1.24--pyhdfd78af_0 pHierCC --help
Usage: pHierCC [OPTIONS]

  pHierCC takes a file containing allelic profiles (as in
  https://pubmlst.org/data/) and works out hierarchical clusters of the full
  dataset based on a minimum-spanning tree.

Options:
  -p, --profile TEXT           [INPUT] name of a profile file consisting of a
                               table of columns of the ST numbers and the
                               allelic numbers, separated by tabs. Can be
                               GZIPped.  [required]
  -o, --output TEXT            [OUTPUT] Prefix for the output files consisting
                               of a  NUMPY and a TEXT version of the
                               clustering result.   [required]
  -a, --append TEXT            [INPUT; optional] The NPZ output of a previous
                               pHierCC run (Default: None).
  -m, --allowed_missing FLOAT  [INPUT; optional] Allowed proportion of missing
                               genes in pairwise comparisons (Default: 0.03).
  -n, --n_proc INTEGER         [INPUT; optional] Number of processes (CPUs) to
                               use (Default: 4).
  --help                       Show this message and exit

docker run --rm -u $(id -u):$(id -g) -v ${PWD}:/data quay.io/biocontainers/phiercc:1.24--pyhdfd78af_0 HCCeval --help
Usage: HCCeval [OPTIONS]

  evalHCC evaluates a HierCC scheme using varied statistic summaries.

Options:
  -p, --profile TEXT      [INPUT] Name of a profile file consisting of a table
                          of columns of the ST numbers and the allelic
                          numbers, separated by tabs. Can be GZIPped.
                          [required]
  -c, --cluster TEXT      [INPUT] Name of the pHierCC text output. Can be
                          GZIPped.  [required]
  -o, --output TEXT       [OUTPUT] Prefix for the two output files.
                          [required]
  -s, --stepwise INTEGER  [INPUT; optional] Evaluate every <stepwise> levels
                          (Default: 10).
  -n, --n_proc INTEGER    [INPUT; optional] Number of processes (CPUs) to use
                          (Default: 4).
  --help                  Show this message and exit.
```

### Run examples
```
git clone git@github.com:zheminzhou/pHierCC.git
cd pHierCC
docker run --rm -u $(id -u):$(id -g) -v ${PWD}:/data quay.io/biocontainers/phiercc:1.24--pyhdfd78af_0 pHierCC -p /data/examples/YERwgMLST.cgMLSTv1.profile0.gz -o /data/examples/YERwgMLST.cgMLSTv1.HierCC0
2022-09-22 01:28:12,621 | Loaded in allelic profiles with dimension: 2999 and 1554. The first column is assumed to be type id.
2022-09-22 01:28:12,621 | Start HierCC assignments
2022-09-22 01:28:12,674 | Calculate distance matrix
Traceback (most recent call last):
  File "/usr/local/bin/pHierCC", line 10, in <module>
    sys.exit(phierCC())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pHierCC/pHierCC.py", line 85, in phierCC
    dist = getDistance(mat, 'dual_dist', pool, start, allowed_missing)
  File "/usr/local/lib/python3.8/site-packages/pHierCC/getDistance.py", line 6, in getDistance
    with NamedTemporaryFile(dir='.', prefix='HCC_') as file :
  File "/usr/local/lib/python3.8/tempfile.py", line 540, in NamedTemporaryFile
    (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/usr/local/lib/python3.8/tempfile.py", line 250, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
PermissionError: [Errno 13] Permission denied: './HCC_5gxrc_uq'
```

Not letting `tempfile` figure out where to put tempfiles. Let me fix this issue real quick

**Comment by rpetit3** [comment]
@BiocondaBot please fetch artifacts

**Comment by rpetit3** [comment]
@BiocondaBot please fetch artifacts

**Comment by rpetit3** [comment]
# Test2 with Docker 

```
docker run --rm -u $(id -u):$(id -g) -v ${PWD}:/data quay.io/biocontainers/phiercc:1.24--pyhdfd78af_0 pHierCC -p /data/examples/YERwgMLST.cgMLSTv1.profile0.gz -o /data/examples/YERwgMLST.cgMLSTv1.HierCC0
2022-09-22 03:07:18,479 | Loaded in allelic profiles with dimension: 2999 and 1554. The first column is assumed to be type id.
2022-09-22 03:07:18,480 | Start HierCC assignments
2022-09-22 03:07:18,533 | Calculate distance matrix
2022-09-22 03:07:24,002 | Start Single linkage clustering
2022-09-22 03:07:24,160 | Attach genomes onto the tree.
2022-09-22 03:07:26,900 | NPZ  clustering result (for production mode): /data/examples/YERwgMLST.cgMLSTv1.HierCC0.npz
2022-09-22 03:07:26,901 | TEXT clustering result (for visual inspection and HCCeval): /data/examples/YERwgMLST.cgMLSTv1.HierCC0.HierCC.gz

docker run --rm -u $(id -u):$(id -g) -v ${PWD}:/data quay.io/biocontainers/phiercc:1.24--pyhdfd78af_0 HCCeval -p /data/examples/YERwgMLST.cgMLSTv1.profile0.gz -c /data/examples/YERwgMLST.cgMLSTv1.HierCC0.HierCC
.gz -o /data/examples/YERwgMLST.cgMLSTv1.HierCC.eval
2022-09-22 03:08:15,297 | Calculating NMIs...
2022-09-22 03:08:15,298 |     NMIs between level 0 and greater levels
2022-09-22 03:08:16,352 |     NMIs between level 100 and greater levels
2022-09-22 03:08:17,264 |     NMIs between level 200 and greater levels
2022-09-22 03:08:18,110 |     NMIs between level 300 and greater levels
2022-09-22 03:08:18,875 |     NMIs between level 400 and greater levels
2022-09-22 03:08:19,573 |     NMIs between level 500 and greater levels
2022-09-22 03:08:20,223 |     NMIs between level 600 and greater levels
2022-09-22 03:08:20,786 |     NMIs between level 700 and greater levels
2022-09-22 03:08:21,291 |     NMIs between level 800 and greater levels
2022-09-22 03:08:21,741 |     NMIs between level 900 and greater levels
2022-09-22 03:08:22,119 |     NMIs between level 1000 and greater levels
2022-09-22 03:08:22,436 |     NMIs between level 1100 and greater levels
2022-09-22 03:08:22,666 |     NMIs between level 1200 and greater levels
2022-09-22 03:08:22,834 |     NMIs between level 1300 and greater levels
2022-09-22 03:08:22,948 |     NMIs between level 1400 and greater levels
2022-09-22 03:08:23,012 |     NMIs between level 1500 and greater levels
2022-09-22 03:08:23,026 | Calculating pairwise distance ...
2022-09-22 03:08:28,342 | Calculating Silhouette score ...
2022-09-22 03:08:32,967 | Tab-delimited evaluation is saved in /data/examples/YERwgMLST.cgMLSTv1.HierCC.eval.tsv
2022-09-22 03:08:32,968 | Visualisation is saved in /data/examples/YERwgMLST.cgMLSTv1.HierCC.eval.pdf
```

Good to go now

**Comment by rpetit3** [comment]
@BiocondaBot please add label

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@BiocondaBot please merge

**Pull request merged**
