### PR TITLE
update pinning for bwa and paml

### PR DESCRIPTION
**Pull request by dpryan79**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by kyleabeauchamp** [comment]
@dpryan79  do we expect this pin upgrade to move BWA to the new compilers?  I think we might need to patch the makefiles to ensure that the docker image GCC isn't leaking in.  WDYT?  

```
strings -a bwa |grep gcc
```

Gives some stuff that includes 4.8.2.  Not sure if that's definitive or not.

**Comment by kyleabeauchamp** [comment]
See, for example, https://github.com/bioconda/bioconda-recipes/pull/13594

**Comment by dpryan79** [comment]
It does use gcc, it's just named differently on the command line. For C programs it doesn't actually matter, they're binary compatible, it's only an issue for C++ (from what I understand at least). We do often have to patch makefiles or explicitly inject the compilers, but those are caught during mulled testing at least.

**Comment by kyleabeauchamp** [comment]
I'm more concerned about which version of GCC got used---how can we tell that the new versions got used?

**Comment by bgruening** [comment]
@dpryan79 should we try to use the latest Docker image and conda 4.6.3 again?

**Comment by dpryan79** [comment]
@bgruening It's worth a shot, that should lack a system gcc.

**Comment by kyleabeauchamp** [comment]
I think my PR #13594  is definitely using the GCC 7, as it's now failing due to lack of ability to link to zlib.

**Pull request merged**
