### PR TITLE
graphmap bump version

### PR DESCRIPTION
**Pull request by mictadlo**
* [x] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by mictadlo** [comment]
HI @bgruening and @druvus,
During update graphmap I got 
[tar: argparser: Cannot chdir: No such file or directory](https://travis-ci.org/bioconda/bioconda-recipes/jobs/228951904#L2862). Any Idea why?

Thank you in advance.

Michal

**Comment by druvus** [comment]
@mictadlo @bgruening We need to fix the version for graphmap. The original `0.22.1`is ranked higher than the later `0.4.0`. Should we change to suggested date variant or fix it in some other way?

**Comment by druvus** [comment]
@bgruening Do you have any suggestion how to fix it? The issue is that the author of the package changed version naming 0.22 vs 0.3.0.

**Comment by bgruening** [comment]
Puh, I just invent here something ... maybe `0.22.1.4`, so we can switch easily back if the maintainer fixes this problem?
Either way, we need to add a big comment :( and fill an upstream bug report.

**Comment by druvus** [comment]
The version that is causing the problem is ancient. They have released the following versions since then: `0.22->0.3.0->0.3.1->0.3.2->0.4.0->0.4.1->0.5.0->0.5.1`

@bgruening is it possible to move a single version to bioconda-legacy? I know it is not good to remove a version but the fast changes for nanopore sequencing probably make it hard to use tho old 0.22 version.  So it would be better to keep the current version naming of the authors
. 
@mictadlo I checked your graphmap commit you are using and it is actually a downgrade.

**Comment by bgruening** [comment]
@druvus we can not move a single version, sorry. But we can remove it ...

**Comment by druvus** [comment]
I would vote to close this PR as it is an older version than the newest present in Bioconda, i.e. not a bump. We should instead try to get the latest 0.5.2 version into Bioconda.

I also think it would be best to remove the 0.22 version as it confuse most people that want the latest version.

**Comment by kyleabeauchamp** [comment]
I have a PR open for the latest but it needs additional fixes to get working

**Comment by druvus** [comment]
Graphmap is bumped to latest version 0.5.2 in #4691 so I am closing this PR.

**Pull request closed without merging**
