### PR TITLE
updated dxpy to 0.273.0

### PR DESCRIPTION
**Pull request by notestaff**
* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [X] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [X] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by chapmanb** [comment]
Ilya;
Thanks much for modernizing this recipe. All of the updates look great but I'm not sure why the linux test is failing. It looks to be hanging indefinitely; I've tried re-starting it but it's still failing. Are you successfully building the updates locally? Thanks again.

**Comment by notestaff** [comment]
@chapmanb locally, the circleci build succeeds.  i'm now running the bootstrap-based mulled build locally.  what is it doing as it's printing the dots?  is there a way to get it to print more details?

**Comment by chapmanb** [comment]
I'm not sure what is making it take so long here if it builds fine locally. Pinging @bioconda/core to see if anyone else has an idea of how best to debug this.

**Comment by dpryan79** [comment]
The trick is to run `top` when the mulled test is running locally. Sometimes the lack of a normal environment (no proper terminal, etc.) mucks up programs and they wait forever for input.

**Comment by notestaff** [comment]
changing install from pip to setuptools seems to help, at least on linux...

**Pull request merged**
