### PR TITLE
Patch Kleborate's method for discovering Kaptive

### PR DESCRIPTION
**Pull request by rpetit3**
This PR fixes Kleborate's `get_kaptive_paths` function to find the Kaptive conda install.

```
# Without Patch
kleborate -a Kleborate-2.0.4/test/test_genomes/ERR2835900.fna.gz
Error: could not find Kaptive directory. Did you git clone with --recursive?

# With Patch
kleborate -a Kleborate-2.0.4/test/test_genomes/ERR2835900.fna.gz
strain  species ST      virulence_score Yersiniabactin  YbST    Colibactin      CbST    Aerobactin      AbST    Salmochelin     SmST    RmpADC  RmST    rmpA2   wzi     K_locus
ERR2835900      Klebsiella africana     ST3291  0       -       0       -       0       -       0       -       0       -       0       -       -       -
```

I added a test for an actual assembly to make sure Kaptive is found in the path. 
```
kleborate -a $(which kleborate | sed 's=bin/kleborate=opt/kaptive_reference_database/exact_match.fasta=')
strain  species ST      virulence_score Yersiniabactin  YbST    Colibactin      CbST    Aerobactin      AbST    Salmochelin     SmST    RmpADC  RmST    rmpA2   wzi     K_locus
exact_match     Klebsiella pneumoniae   ST36    0       -       0       -       0       -       0       -       0       -       0       -       wzi27   KL27
```
----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by rpetit3** [comment]
@BiocondaBot please fetch artifacts

**Comment by rpetit3** [comment]
Testing artifacts
```
conda create -y -n test-kleborate-patch -c https://162129-42372094-gh.circle-artifacts.com/0/tmp/artifacts/packages -c conda-forge -c bioconda kleborate
...
kleborate-2.0.4            |     pyhdfd78af_1         7.0 MB  https://162129-42372094-gh.circle-artifacts.com/0/tmp/artifacts/packages
...

conda activate test-kleborate-patch
conda env export | grep kleborate
  - kleborate=2.0.4=pyhdfd78af_1
 
kleborate -a Kleborate-2.0.4/test/test_genomes/ERR2835900.fna.gz
strain  species ST      virulence_score Yersiniabactin  YbST    Colibactin      CbST    Aerobactin      AbST    Salmochelin     SmST    RmpADC  RmST    rmpA2   wzi     K_locus
ERR2835900      Klebsiella africana     ST3291  0       -       0       -       0       -       0       -       0       -       0       -       -       -

kleborate -a Kleborate-2.0.4/test/test_genomes/AS7.fna.gz
strain  species ST      virulence_score Yersiniabactin  YbST    Colibactin      CbST    Aerobactin      AbST    Salmochelin     SmST    RmpADC  RmST    rmpA2   wzi     K_locus
AS7     Klebsiella pneumoniae   ST23    4       ybt 9; ICEKp3   201     -       0       iuc 1   1       iro 1   2       rmp 1; KpVP-1   26-1LV  -       wzi1    KL1
```

I think it might be all set now

**Comment by rpetit3** [comment]
@bioconda-bot  please add label

**Review by thanhleviet — APPROVED** [review]

**Comment by thanhleviet** [comment]
@bioconda-bot please merge

**Comment by rpetit3** [comment]
Thank you!

**Pull request merged**
