### PR TITLE
mummer4: add linux-aarch64 build

### PR DESCRIPTION
**Pull request by martin-g**
Describe your pull request here

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

### General instructions

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

### Instructions for avoiding API, ABI, and CLI breakage issues
Conda is able to record and lock (a.k.a. pin) dependency versions used at build time of other recipes.
This way, one can avoid that expectations of a downstream recipe with regards to API, ABI, or CLI are violated by later changes in the recipe.
If not already present in the meta.yaml, make sure to specify `run_exports` (see [here](https://bioconda.github.io/contributor/linting.html#missing-run-exports) for the rationale and comprehensive explanation).
Add a `run_exports` section like this:

```yaml
build:
  run_exports:
    - ...

```

with `...` being one of:

| Case                             | run_exports statement                                               |
| -------------------------------- | ------------------------------------------------------------------- |
| semantic versioning              | `{{ pin_subpackage("myrecipe", max_pin="x") }}`     |
| semantic versioning (0.x.x)      | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}`   |
| known breakage in minor versions | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| known breakage in patch versions | `{{ pin_subpackage("myrecipe", max_pin="x.x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| calendar versioning              | `{{ pin_subpackage("myrecipe", max_pin=None) }}`    |

while replacing `"myrecipe"` with either `name` if a `name|lower` variable is defined in your recipe or with the lowercase name of the package in quotes.

### Bot commands for PR management

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

Note that the <code>@BiocondaBot please merge</code> command is now depreciated. Please just squash and merge instead.

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by martin-g** [comment]
@BiocondaBot please fetch artifacts

**Comment by martin-g** [comment]
```
mgrigorov in 🌐 euler-arm-22 in /tmp/mummer4 via 🅒 test123 took 2s 
❯ tar xvf mummer4-4.0.0rc1-pl5321h7021222_7.tar.bz2                                                                                                                                                        (test123) 
info/run_exports.json
info/recipe/build.sh
info/hash_input.json
info/test/run_test.sh
info/index.json
info/recipe/meta.yaml.template
info/recipe/Makefile.in.patch
info/recipe/Makefile.am.patch
info/has_prefix
info/recipe/mummerplot.pl.patch
info/recipe/meta.yaml
info/recipe/0001-sort-mgaps-file-before-postpro.-on-behalf-of-jervied.patch
info/files
info/recipe/conda_build_config.yaml
info/about.json
info/paths.json
info/git
lib/pkgconfig/mummer.pc
lib/mummer/tandem-repeat.awk
lib/mummer/Foundation.pm
libexec/mummer/prepro
libexec/mummer/mgaps
libexec/mummer/postpro
libexec/mummer/postnuc
lib/libumdmummer.a
lib/libumdmummer.so
include/mummer-4.0.0rc1/include/mummer/fasta.hpp
include/mummer-4.0.0rc1/include/compactsufsort/const_iterator_traits.hpp
include/mummer-4.0.0rc1/include/mummer/const_iterator_traits.hpp
include/mummer-4.0.0rc1/include/compactsufsort/said_traits.hpp
include/mummer-4.0.0rc1/include/mummer/redirect_to_pager.hpp
include/mummer-4.0.0rc1/include/mummer/48bit_index.hpp
include/mummer-4.0.0rc1/include/mummer/sparseSA_imp.hpp
include/mummer-4.0.0rc1/include/mummer/openmp_qsort.hpp
include/mummer-4.0.0rc1/include/thread_pipe.hpp
include/mummer-4.0.0rc1/include/thread_pipe/divisor.hpp
include/mummer-4.0.0rc1/include/mummer/timer.hpp
include/mummer-4.0.0rc1/include/compactsufsort/compactsufsort.hpp
include/mummer-4.0.0rc1/include/jellyfish/divisor.hpp
include/mummer-4.0.0rc1/include/mt_skip_list/common.hpp
include/mummer-4.0.0rc1/include/jellyfish/cpp_array.hpp
include/mummer-4.0.0rc1/include/jellyfish/stream_manager.hpp
include/mummer-4.0.0rc1/include/mummer/dset.hpp
include/mummer-4.0.0rc1/include/thread_pipe/circular_buffer.hpp
include/mummer-4.0.0rc1/include/jellyfish/whole_sequence_parser.hpp
include/mummer-4.0.0rc1/include/jellyfish/circular_buffer.hpp
include/mummer-4.0.0rc1/include/mummer/48bit_iterator.hpp
include/mummer-4.0.0rc1/include/jellyfish/cooperative_pool2.hpp
include/mummer-4.0.0rc1/include/thread_pipe/traits.hpp
include/mummer-4.0.0rc1/include/mt_skip_list/set.hpp
include/mummer-4.0.0rc1/include/compactsufsort/compactsufsort_imp.hpp
include/mummer-4.0.0rc1/include/compactsufsort/trsort_imp.hpp
include/mummer-4.0.0rc1/include/thread_pipe/cooperative_pool2.hpp
include/mummer-4.0.0rc1/include/compactsufsort/sssort_imp.hpp
include/mummer-4.0.0rc1/include/mummer/nucmer.hpp
include/mummer-4.0.0rc1/include/mummer/sparseSA.hpp
include/mummer-4.0.0rc1/include/mummer/tigrinc.hh
include/mummer-4.0.0rc1/include/mummer/mgaps.hh
include/mummer-4.0.0rc1/include/mummer/sw_alignscore.hh
include/mummer-4.0.0rc1/include/mummer/delta.hh
include/mummer-4.0.0rc1/include/mummer/sw_align.hh
include/mummer-4.0.0rc1/include/mummer/postnuc.hh
include/mummer-4.0.0rc1/include/mummer/translate.hh
bin/exact-tandems
bin/delta2vcf
bin/promer
bin/dnadiff
bin/mummerplot
bin/repeat-match
bin/annotate
bin/combineMUMs
bin/delta-filter
bin/show-diff
bin/show-coords
bin/show-snps
bin/show-tiling
bin/mummer
bin/show-aligns
bin/nucmer
include/mummer-4.0.0rc1/include/compactsufsort/divsufsort_private.h
lib/libumdmummer.so.0
lib/libumdmummer.so.0.0.0

mgrigorov in 🌐 euler-arm-22 in /tmp/mummer4 via 🅒 test123 
❯ file bin/*                                                                                                                                                                                               (test123) 
bin/annotate:      ELF 64-bit LSB pie executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, not stripped
bin/combineMUMs:   ELF 64-bit LSB pie executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, not stripped
bin/delta-filter:  ELF 64-bit LSB pie executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, not stripped
bin/delta2vcf:     Perl script text executable
bin/dnadiff:       Perl script text executable
bin/exact-tandems: POSIX shell script, ASCII text executable
bin/mummer:        ELF 64-bit LSB pie executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, with debug_info, not stripped
bin/mummerplot:    Perl script text executable
bin/nucmer:        ELF 64-bit LSB pie executable, ARM aarch64, version 1 (GNU/Linux), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, with debug_info, not stripped
bin/promer:        Perl script text executable
bin/repeat-match:  ELF 64-bit LSB pie executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, not stripped
bin/show-aligns:   ELF 64-bit LSB pie executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, with debug_info, not stripped
bin/show-coords:   ELF 64-bit LSB pie executable, ARM aarch64, version 1 (GNU/Linux), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, not stripped
bin/show-diff:     ELF 64-bit LSB pie executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, not stripped
bin/show-snps:     ELF 64-bit LSB pie executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, not stripped
bin/show-tiling:   ELF 64-bit LSB pie executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, not stripped

mgrigorov in 🌐 euler-arm-22 in /tmp/mummer4 via 🅒 test123 
❯ ./bin/mummer                                                                                                                                                                                             (test123) 
Usage: ./bin/mummer [options] <reference-file> <query file1> . . . [query file32]
Implemented MUMmer v3 options:
-mum           compute maximal matches that are unique in both sequences
-mumreference  compute maximal matches that are unique in the reference-
               sequence but not necessarily in the query-sequence (default)
-mumcand       same as -mumreference
-maxmatch      compute all maximal matches regardless of their uniqueness
-l             set the minimum length of a match
               if not set, the default value is 20
-b             compute forward and reverse complement matches
-F             force 4 column output format regardless of the number of
               reference sequence inputs
-n             match only the characters a, c, g, or t
-L             print length of query sequence in header of matches
-r             compute only reverse complement matches
-s             print first 53 characters of the matching substring
-c             Report the query position of a reverse complement match relative to the forward strand of the query sequence

Additional options:
-k             sampled suffix positions (one by default)
-threads       number of threads to use for -maxmatch, only valid k > 1 
-qthreads      number of threads to use for queries 
-suflink       use suffix links (1=yes or 0=no) in the index and during search [auto]
-child         use child table (1=yes or 0=no) in the index and during search [auto]
-skip          sparsify the MEM-finding algorithm even more, performing jumps of skip*k [auto (l-10)/k]
               this is a performance parameter that trade-offs SA traversal with checking of right-maximal MEMs
-kmer          use kmer table containing sa-intervals (speeds up searching first k characters) in the index and during search [int value, auto]
-save (string) save index to file to use again later (string)
-load (string) load index from file

Example usage:

./mummer -maxmatch -l 20 -b -n -k 3 -threads 3 ref.fa query.fa
Find all maximal matches on forward and reverse strands
of length 20 or greater, matching only a, c, t, or g.
Index every 3rd position in the ref.fa and use 3 threads to find MEMs.
Fastest method for one long query sequence.

./mummer -maxmatch -l 20 -b -n -k 3 -qthreads 3 ref.fa query.fa
Same as above, but now use a single thread for every query sequence in
query.fa. Fastest for many small query sequences.
```
LGTM!

**Comment by martin-g** [comment]
@BiocondaBot please add label

**Review by peterpru — APPROVED** [review]
nice 💯

**Pull request merged**
