### PR TITLE
Update dadi to 2.0.5

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`dadi`](https://bioconda.github.io/recipes/dadi/README.html): **2.0.4** &rarr; **2.0.5**

[install with bioconda](http://bioconda.github.io/recipes/dadi/README.html) [Conda](https://anaconda.org/bioconda/dadi/files)

Info | Link
-----|-----
Recipe | [`recipes/dadi`](https://github.com//bioconda/bioconda-recipes/tree/bump/dadi/recipes/dadi) (click to view/edit other files)
Releases |[https://pypi.org/pypi/dadi/json](https://pypi.org/pypi/dadi/json)
Recipe Maintainer(s) | @RyanGutenkunst

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by RyanGutenkunst** [comment]
After over 24 hours, the automated tests haven't begun. Is there something I should do?

**Comment by druvus** [comment]
@BiocondaBot please update

**Comment by druvus** [comment]
@RyanGutenkunst I triggered the tests to run using biocondabot command `please update`.

**Comment by RyanGutenkunst** [comment]
@druvus Thank you for moving this forward, and for the eduction on how I can do it myself next time.

**Pull request closed without merging**
