### PR TITLE
bump CONDA_GSL to 2.4

### PR DESCRIPTION
**Pull request by molpopgen**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [ ] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [x] This PR does something else (explain below).

In reference to #8613, this PR bumps CONDA_GSL from 1.16 to 2.4, which is the current version found in conda-forge.

There will be side-effects:

1. The 2.x series changes the library soname due to a bug fix in 2.0 that necessitated and API change, leading to the ABI change of a new soname.  This *will* mean runtime errors that will be fixable only by rebuilding/relinking packages depending on GSL.

I think this is worth it, though--there's good stuff in the GSL 2.x series, and 1.16 has some bugs in the linear algebra stuff that have since been squashed.

### CODE REVIEW

**Comment by bgruening** [comment]
Can you please target the bulk branch. And we need to bump the version number of every recipe that depends on GSL. 

Thanks for working on this.

**Comment by molpopgen** [comment]
> Can you please target the bulk branch. 

Done.

**Comment by molpopgen** [comment]
@bgruening -- CI checks pass.  What's the next step?

**Comment by bgruening** [comment]
@molpopgen you now need to bump the version number of all recipes that have the CONDA_GSL macro.

**Comment by molpopgen** [comment]
How?

**Comment by bgruening** [comment]
Manually or with sed/grep...

**Comment by molpopgen** [comment]
Test builds failing b/c conda-forge's GSL depends on openblas.  Have to make that a build AND run dependency for all packages.  TODO: this should probably be documented somewhere b/c openblas is not getting installed, even though conda-forge lists it as a run dependency...

**Comment by molpopgen** [comment]
The eqtlbma package is failing to compile because it is using the ONE function whose API changes from 1.16 to 2.0.  Need to file a ticket with them on that.

**Comment by molpopgen** [comment]
> The eqtlbma package is failing to compile because it is using the ONE function whose API changes from 1.16 to 2.0. Need to file a ticket with them on that.

This is already an issue there, and it is getting stale.  timflutre/eqtlbma#22

There is a new release, but I can confirm that it fails to compile on GSL 2.1/Ubuntu.

@bgruening -- is there a way to ignore this and move on?  There are upstream issues getting to be a year old or older.

**Comment by molpopgen** [comment]
The merfishtools failure is a wacky one.  The author appears to be @johanneskoester, so he may have some insight??

**Comment by bgruening** [comment]
@molpopgen thanks for you work here!
For eqtlbma and similar once, can you remove CONDA_GSL and specify the `1.16` the hard way, with a small comment?

What is the story about openblas, are you really sure all the recipes need openblas / can make use of it?

**Comment by molpopgen** [comment]
@bgruening --

eqtlbma will make a new release, meaning I can get that working.  Several of the other packages have deeper issues, like URL failures when trying to download, etc.  I may or may not be able to resolve them.

The openblas issue is a result of [this](https://github.com/conda-forge/gsl-feedstock/blob/master/recipe/build.sh), where the recipe deletes `gslsblas` and symlinks to to `openblas`.  IMO, this is an error, and I may file a ticket with them about it.  If one wants to use GSL with a different blas lib, the docs on how to do that are at the GSL web page.

If I do get conda-forge to change things, then this PR may need some work.  Some of the packages already required openblas, but most did not, so I'd have to figure that out and revert.

**Comment by molpopgen** [comment]
@bgruening -- a few of the failed builds have the following messages that I don't understand:

bash: cannot set terminal process group (-1): Inappropriate ioctl for device

Any ideas?

**Comment by bgruening** [comment]
>  like URL failures when trying to download, etc. I may or may not be able to resolve them.

If it is a newer package, so 1-2 years old you might find the tarball as a backup here: https://depot.galaxyproject.org/software/

@ openblas issue, please ask @isuruf. He is a really nice guy and will help you I'm sure.

> bash: cannot set terminal process group (-1): Inappropriate ioctl for device

This is a warning and not an error. So the error needs to be somewhere else.

If you can figure out the openblas issue or revert, so that we make sure we do not do any harm to package, I'm fine with merging it to `bulk` which means packages are build that are fine and packages that fail will fail and we can fix iteratively.

Thanks again!

**Comment by isuruf** [comment]
> The openblas issue is a result of this, where the recipe deletes gslsblas and symlinks to to openblas. IMO, this is an error, and I may file a ticket with them about it. If one wants to use GSL with a different blas lib, the docs on how to do that are at the GSL web page.

I know that this a hack, but couldn't find another way. Problem is that most downstream packages would use `pkg-config` files from `gsl` and that will link to `gslcblas` which is a slow BLAS implementation in C. If you have other ideas on how to fix this, please let me know.

**Comment by molpopgen** [comment]
@isuruf 

Thanks for the reply.  This is a tricky issue, perhaps.  A slow blas implementation may not matter for a majority of GSL users.  For example, many packages may only use the RNG portion of the library.  

The surprise for me was that the GSL recipe lists openblas as a run dependency, but it was not installed into the CI environment along with GSL, resulting in link failures.  If that hadn't happened, I would not have known about the swap of gslcblas for openblas.  

(I just tested a fresh env on my os x laptop, though, and it does indeed attempt to install openblas along with GSL 2.4.)

Overall, I think I'd prefer to leave it up to other packages to have their build environments properly configured.  It may be slower, but it is less prone to surprises.

**Comment by isuruf** [comment]
It's a defaults/openblas thing. Defaults' gsl is not compiled with openblas, while conda-forge's is. The solver uses defaults' gsl because it's "simpler".

**Comment by molpopgen** [comment]
> It's a defaults/openblas thing. Defaults' gsl is not compiled with openblas, while conda-forge's is. The solver uses defaults' gsl because it's "simpler".

I'm not sure I understand what you're getting at? Bioconda's channels put conda-forge at higher priority than defaults.   The specific link problem was due to attempting to link to gslcblas and getting an error back that openblas is not found.

**Comment by molpopgen** [comment]
I've just realized that conda-forge pins their GSL at 2.2.  It seems that we should do the same.

@bgruening -- I am fine with the openblas requirement, unless there's some way to pull GSL from defaults to avoid this?  Ideally, I'd prefer not to silently substitute libraries in this way, but it should do little harm.

Sticking to 2.2 means we'll have to bump one of the packages I've modded back down to 1.16, and some other quirky will probably arise.

**Comment by johanneskoester** [comment]
@molpopgen to fir merfishtools you need to insert the following snippet in the build.sh:
```
# circumvent a bug in conda-build >=2.1.18,<3.0.10
# https://github.com/conda/conda-build/issues/2255
# TODO: remove once CI uses conda-build >=3.0.10
[[ -z $REQUESTS_CA_BUNDLE && ${REQUESTS_CA_BUNDLE+x} ]] && unset REQUESTS_CA_BUNDLE
[[ -z $SSL_CERT_FILE && ${SSL_CERT_FILE+x} ]] && unset SSL_CERT_FILE
```

Thanks for working on this!

**Comment by molpopgen** [comment]
@johanneskoester -- any idea if other packages need this, too?  I doubt I can figure it out for all the build failures here, but several packages are having failure messages that I cannot parse.

**Comment by johanneskoester** [comment]
Nope, the other failing recipes have different problems. An unreachable URL, incompatibility with the new version, ...

**Comment by molpopgen** [comment]
> Nope, the other failing recipes have different problems. An unreachable URL, incompatibility with the new version, ...

Thanks.  I have no idea what your block of code is addressing, so I figured I'd ask...

**Comment by molpopgen** [comment]
There's a [new lcfit](https://github.com/matsengrp/lcfit/releases) that adds GSL2 support.

**Comment by bgruening** [comment]
@molpopgen great!

> eqtlbma. This only supports GSL < 1.17 and > 2.2. It miraculously manages to use the only function to change from 1.16 to 2.0 and also a new function introduced in 2.3.

You can pin it to <1.17

> eigensoft -- not sure why this one failed.
ea-utils -- dead download URL. It appears that it is on github now, though.

You can put both on the blacklist with a comment why this one is currently blacklisted.

**Comment by molpopgen** [comment]
@bgruening I've added those two packages to the blacklist, but the linting fails if one attempts to use GSL versions != CONDA_GSL.  See the last commit, though--perhaps I've done it wrong?

**Comment by bgruening** [comment]
Ok, this looks much better. Let's get it into bulk. 

Thanks a lot @molpopgen! Please follow the bulk branch and see if everything looks ok for you.

**Comment by molpopgen** [comment]
Looks good, but lcfit failed to build this time??

**Pull request merged**
