### PR TITLE
bcftools polysomy

### PR DESCRIPTION
**Pull request by dpryan79**
Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it. Note that if you are not already a member of the bioconda project (meaning that you can't add this label), please ping `@bioconda/core` so that your PR can be reviewed and merged (please note if you'd like to be added to the bioconda project). Please see https://github.com/bioconda/bioconda-recipes/issues/15332 for more details.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

This adds the `bcftools polysomy` command.

### CODE REVIEW

**Comment by bgruening** [comment]
Can we add a test that triggers that? I wonder if we need the extended base image.

**Comment by dpryan79** [comment]
A test would be easy, yes (I'll add one). I presume we don't need the extended image.

**Comment by dpryan79** [comment]
Grr, I should have tested my test. The change does work (tested locally) :P I'll fix that.

**Comment by dpryan79** [comment]
That made it happier.

**Comment by jmarshall** [comment]
GSL is distributed under the GNU General Public License (GPL). When `--enable-libgsl` is used to compile bcftools, the resulting program will also be GPL licensed.

So possibly this PR should also have updated _meta.yaml_ to say `license: GPL`.

**Comment by dpryan79** [comment]
@jmarshall Thanks for the heads up on that :) https://github.com/bioconda/bioconda-recipes/pull/18723

**Pull request merged**
