### PR TITLE
abyss:  Add test for ABYSS-P, add openmpi where it was missing

### PR DESCRIPTION
**Pull request by pvanheus**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by mbargull** [comment]
Hi @pvanheus, can you try including the `ABYSS-P` tests and add the following?
```yaml
extra:
  container:
    # openmpi needs ssh/rsh
    extended-base: true
```

See:
> this is our first recipe with openmpi. Openmpi needs openssh installed,

from https://github.com/bioconda/bioconda-recipes/pull/6649#issuecomment-342794693.

**Comment by bgruening** [comment]
@pvanheus @mbargull https://github.com/bioconda/bioconda-recipes/blob/eac862cc446a5e961d09f13cf649cab8a91385ec/recipes/nest/meta.yaml

I added openssh to the build and the test container for this purpose. Its good to see more openmpi packages coming.

**Comment by mbargull** [comment]
@bgruening: That's were I stole the `# openmpi needs ssh/rsh` from :wink:

@pvanheus: Can you bump the build numbers to trigger new builds?

**Comment by mbargull** [comment]
I suppose we need an additional `--with-mpi=$PREFIX/include` for `configure` as in
https://github.com/bioconda/bioconda-recipes/blob/a68c206258b88ce1054030ef90ba86c462a58abb/recipes/abyss/build.sh#L12

**Comment by pvanheus** [comment]
For some reason openmpi on MacOS X is not detected by configure:

```
checking mpi.h usability... yes
checking mpi.h presence... yes
checking for mpi.h... yes
checking for MPI_Init in -lmpi... no
```
(from the [Travis build log](https://travis-ci.org/bioconda/bioconda-recipes/builds/303103584?utm_source=github_status&utm_medium=notification)). I have thus disabled MacOS X builds. This is not a great solution though.

**Comment by mbargull** [comment]
There is something really fishy going on... Looks like `build.sh` is run when the build environment is activated but before the required packages get installed.

**Comment by mbargull** [comment]
Merged this so that the Linux builds don't have to be repeated over and over.

**Comment by mbargull** [comment]
@bioconda/osx : Can anyone who has macOS available test this locally?
Relevant parts of the Travis log:
* `build.sh` run right after build environment activation:
  https://travis-ci.org/bioconda/bioconda-recipes/jobs/303103586#L411
* `checking for MPI_Init in -lmpi... no`:
  https://travis-ci.org/bioconda/bioconda-recipes/jobs/303103586#L534
* `boost_1_56_0` being used:
  https://travis-ci.org/bioconda/bioconda-recipes/jobs/303103586#L626

**Pull request merged**
