### PR TITLE
Update bowtie: remove osx platform build preclusion

### PR DESCRIPTION
**Pull request by AlexTate**
This commit removes osx platform build preclusion. It is my intention to re-enable builds for osx-64 for new versions of Bowtie. Currently, v1.2.3 is nearly 3 years old but is the latest version available via Bioconda, despite newer release packages offered on the Bowtie repo. This change was originally introduced by bulk commit f1f14b214f3896e8d01df15084cda260d4651fd9 but I have been unable to find any information that explains why the change was made.

The latest version of Bowtie available for osx is also pinned at Python 3.7 which imposes a fairly low ceiling on Conda environments that depend on it.

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by AlexTate** [comment]
@BiocondaBot please add label

**Comment by AlexTate** [comment]
This PR changes the recipe's behavior for osx; builds on linux are unchanged.

Bowtie requires a GNU-like environment, with GNU's `make` and `gcc`, in order to correctly compile on macOS. XCode Developer Tools is not enough to cover these dependencies. 

Bioconda's osx builds take place on a VM with the following SDK installed: https://github.com/phracker/MacOSX-SDKs, per the Azure pipeline config: https://github.com/bioconda/bioconda-recipes/blob/master/azure-pipeline.yml#L155. You will see there is no mention of additional GNU utility setup (typically performed via Homebrew) on the MacOSX-SDKs repo.

Therefore, it is not possible to build Bowtie from source with the current Azure pipeline config. As an alternative, I have proposed a recipe which retrieves the precompiled binaries from the Bowtie repo's releases section, and simply copies them into place rather than compiling them from source. It isn't ideal, but it will at least bring things up to date for Bowtie until there is a better solution for using GNU utilities for osx builds.

**Comment by daler** [comment]
@bioconda/core any advice on this? I'm not up to speed enough on macOS to know the feasibility of getting this working on Azure. If not feasible, then we'd need to make a policy call on whether the prebuilt binary is OK and would not cause downstream problems.

**Comment by AlexTate** [comment]
@BiocondaBot please fetch artifacts

**Comment by AlexTate** [comment]
@daler and @bgruening motivated me to look into the compiler issues further. It turns out the solution was nowhere near as complex as I had assumed. The VERSION file in bowtie's root directory (where the project's C++ source files are stored...) was being mistakenly included as a version header file (introduced in C++20). This caused a cascade of misleading compiler errors. Simply renaming the file to VERSION.txt fixes the issue.

**Comment by daler** [comment]
🎉 @AlexTate if you're moving the file anyway in `build.sh` do you still need it in the patch?

**Comment by AlexTate** [comment]
Toggling PR because it looks like the Azure pipeline had a hiccup while pulling the osx image

**Comment by AlexTate** [comment]
@daler that's a good point. My justification was that leaving it in the patch would make it complete and its purpose obvious. Running the patch on its own (with new enough GNU patch) would solve the non-conda-related compiler issue even if someone skipped using the conda-specific build.sh. For example, if someone found this and just wanted to compile on macOS/clang without using the conda recipe.

[GNU's patch utility has supported renames since 2012 with version 2.7.](https://savannah.gnu.org/forum/forum.php?forum_id=7361) However macOS ships with version 2.5, which is why the addition to `build.sh` this was necessary in the first place.

I've removed the "rename" line from build.sh and instead made Anaconda's patch package (v2.7.6) a build requirement for osx.

**Review by daler — APPROVED** [review]

**Comment by daler** [comment]
@AlexTate the rationale to keep it all in the patch is a good one, and your update to keep it all in the patch makes it a lot cleaner for working on macOS.

Thanks so much for getting to the bottom of this! As you know, it was a long time coming and just needed someone with sufficient motivation to figure it out :)

**Comment by daler** [comment]
@BiocondaBot please merge

**Pull request merged**
