### PR TITLE
Update hypercluster to 0.1.2

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`hypercluster`](https://bioconda.github.io/recipes/hypercluster/README.html): **0.0.2** &rarr; **0.1.2**

[install with bioconda](http://bioconda.github.io/recipes/hypercluster/README.html) [Conda](https://anaconda.org/bioconda/hypercluster/files)

Info | Link
-----|-----
Recipe | [`recipes/hypercluster`](https://github.com//bioconda/bioconda-recipes/tree/bump/hypercluster/recipes/hypercluster) (click to view/edit other files)
Releases |[https://pypi.org/pypi/hypercluster/json](https://pypi.org/pypi/hypercluster/json)
Recipe Maintainer(s) | @liliblu, @ruggleslab

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by liliblu** [comment]
@BiocondaBot update

**Comment by liliblu** [comment]
@dpryan79  Hey Devon, I'm not sure if you are the right person to tag here, but could I get some help? 
The error i'm getting is below. I'm not sure if or what is wrong with my new release?
Thank you!
```
.circleci/setup.sh
From ssh://github.com/bioconda/bioconda-recipes
 * [new branch]          master     -> __upstream__c8ppt8QDVf/master
Your bioconda-recipes CI configuration is out of date.
Please update it to the latest version of the upstream master branch.

Have @BiocondaBot attempt to fix this by creating a comment on your PR:

   @BiocondaBot update

Once the update commit has been created, update your local copy of
your branch:

  git pull


You can also fix this manually, e.g., by running:
  git fetch https://github.com/bioconda/bioconda-recipes.git master
  git merge FETCH_HEAD


Exited with code exit status 1
```

**Comment by dpryan79** [comment]
@BiocondaBot please update

**Comment by dpryan79** [comment]
Oh, I forgot the "please" in the message you got, which is why the bot didn't respond. Sorry about that!

**Comment by dpryan79** [comment]
Grr, I hate when the bot closes its own PRs. This is redone in #19634

**Pull request closed without merging**
