### PR TITLE
Add recipe for bindash

### PR DESCRIPTION
**Pull request by johnlees**
Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it. Note that if you are not already a member of the bioconda project (meaning that you can't add this label), please ping `@bioconda/core` so that your PR can be reviewed and merged (please note if you'd like to be added to the bioconda project). Please see https://github.com/bioconda/bioconda-recipes/issues/15332 for more details.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by johnlees** [comment]
This seems to build and test ok, but then there is a problem with the test at the container stage. I can't see the error message given however (just exit code 1). Any tips?

My only guess is that I might need to add `zlib` to `run:`?

**Comment by johnlees** [comment]
That was the problem.
Unfortunately it won't compile with clang, from the README:

> For MacOS, the native clang compiler cannot compile without compiling error. It is recommended to install gcc first as follows.
> ```
> # install homebrew if not already done
> brew update
> brew install gcc@8
> GCCPATH=$(ls /usr/local/Cellar/gcc/*/bin/)
> export PATH="${GCCPATH}:${PATH}"
> # Set CC CXX to /usr/local/Cellar/gcc/*/bin/* as necessary
> # Then run cmake as above (a GUI for cmake may also be available for MacOS)
> ```

I will disable OS X, unfortunately

**Comment by dpryan79** [comment]
Approved so this can be merged by someone once the CI finishes.

**Comment by dpryan79** [comment]
@bioconda-bot please fetch artifacts

**Pull request merged**
