### PR TITLE
Update odgi to 0.6.3

### PR DESCRIPTION
**Pull request by AndreaGuarracino**

### CODE REVIEW

**Comment by raivivek** [comment]
@AndreaGuarracino Looks like the build is timing out due to 1hr limitation on the CircleCI build. Could you check if the build.sh is using all CPU cores to build the package? Perhaps that could speed it enough to work. Setting `-j $CPU_COUNT` or `-j 2` for example to the `conda --build` command should help.

**Comment by AndreaGuarracino** [comment]
@raivivek, thank you for your suggestion. I tried and failed. It looks like it was near the end T_T

**Comment by raivivek** [comment]
Yeah. Looks like it helped but not enough. I'm not sure if we can do anything except to wait for new build system. Perhaps someone else can help.

**Comment by AndreaGuarracino** [comment]
@BiocondaBot please add label

**Review by dpryan79 — APPROVED** [review]

**Pull request merged**
