### PR TITLE
add recipe for staphopia-sccmec

### PR DESCRIPTION
**Pull request by rpetit3**
This PR adds a recipe for [staphopia-sccmec](https://github.com/staphopia/staphopia-sccmec), a tool for SCCmec typing S. aureus assemblies.

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by rpetit3** [comment]
Tested locally and everything looks good:

```
(base) rpetit@staphopia:~$ conda create -n staphopia-sccmec -y -c conda-forge -c bioconda -c https://151846-42372094-gh.circle-artifacts.com/0/tmp/artifacts/packages staphopia-sccmec

(base) rpetit@staphopia:~$ conda activate staphopia-sccmec

(staphopia-sccmec) rpetit@staphopia:~$ staphopia-sccmec
usage: staphopia-sccmec [-h] [--assembly ASSEMBLY|ASSEMBLY_DIR|STAPHOPIA_DIR] [--staphopia STAPHOPIA_DIR] [--sccmec SCCMEC_DATA] [--ext STR] [--hamming] [--json] [--debug]
                        [--depends] [--test] [--citation] [--version]

Determine SCCmec Type/SubType

optional arguments:
  -h, --help            show this help message and exit

Options:

  --assembly ASSEMBLY|ASSEMBLY_DIR|STAPHOPIA_DIR
                        Input assembly (FASTA format), directory of assemblies to predict SCCmec. (Cannot be used with --staphopia)
  --staphopia STAPHOPIA_DIR
                        Input directory of samples processed by Staphopia. (Cannot be used with --assembly)
  --sccmec SCCMEC_DATA  Directory where SCCmec reference data is stored (Default: /local/home/rpetit/miniconda3/envs/staphopia-sccmec/share/staphopia-sccmec/data).
  --ext STR             Extension used by assemblies. (Default: fna)
  --hamming             Report the hamming distance of each type.
  --json                Report the output as JSON (Default: tab-delimited)
  --debug               Print debug related text.
  --depends             Verify dependencies are installed/found.
  --test                Run with example test data.
  --citation            Print citation information for using Staphopia SCCmec
  --version             show program's version number and exit

(staphopia-sccmec) rpetit@staphopia:~$ staphopia-sccmec --version
staphopia-sccmec 1.0.0

(staphopia-sccmec) rpetit@staphopia:~$ staphopia-sccmec --test
sample	I	II	III	IV	V	VI	VII	VIII	IX	meca	Ia	IIa	IIb	IIIa	IVa	IVb	IVc	IVd	IVg	IVh
GCF_001580515	False	False	False	True	False	False	False	False	False	True	False	False	False	False	True	False	False	False	False	False

(staphopia-sccmec) rpetit@staphopia:~$ staphopia-sccmec --assembly /data/storage/staphopia-v2/runs/complete/SRX2478925/assembly/SRX2478925.fna --json
[
    {
        "sample": "SRX2478925",
        "I": false,
        "II": false,
        "III": false,
        "IV": true,
        "V": false,
        "VI": false,
        "VII": false,
        "VIII": false,
        "IX": false,
        "meca": true,
        "Ia": false,
        "IIa": false,
        "IIb": false,
        "IIIa": false,
        "IVa": true,
        "IVb": false,
        "IVc": false,
        "IVd": false,
        "IVg": false,
        "IVh": false
    }
]

(staphopia-sccmec) rpetit@staphopia:~$ ls test/
SRX2478920.fna  SRX2478921.fna  SRX2478922.fna  SRX2478923.fna  SRX2478924.fna  SRX2478925.fna  SRX2478926.fna  SRX2478927.fna  SRX2478928.fna  SRX2478929.fna  SRX2478930.fna
(staphopia-sccmec) rpetit@staphopia:~$ staphopia-sccmec --assembly test/
sample	I	II	III	IV	V	VI	VII	VIII	IX	meca	Ia	IIa	IIb	IIIa	IVa	IVb	IVc	IVd	IVg	IVh
SRX2478929	False	False	False	True	False	False	False	False	False	True	False	False	False	False	True	False	False	False	False	False
SRX2478921	False	False	False	True	False	False	False	False	False	True	False	False	False	False	True	False	False	False	False	False
SRX2478928	False	False	False	True	False	False	False	False	False	True	False	False	False	False	True	False	False	False	False	False
SRX2478927	False	False	False	True	False	False	False	False	False	True	False	False	False	False	True	False	False	False	False	False
SRX2478930	False	False	False	True	False	False	False	False	False	True	False	False	False	False	True	False	False	False	False	False
SRX2478926	False	False	False	True	False	False	False	False	False	True	False	False	False	False	True	False	False	False	False	False
SRX2478925	False	False	False	True	False	False	False	False	False	True	False	False	False	False	True	False	False	False	False	False
SRX2478920	False	False	False	True	False	False	False	False	False	True	False	False	False	False	True	False	False	False	False	False
SRX2478924	False	False	False	True	False	False	False	False	False	True	False	False	False	False	True	False	False	False	False	False
SRX2478923	False	False	False	True	False	False	False	False	False	True	False	False	False	False	True	False	False	False	False	False
SRX2478922	False	False	False	True	False	False	False	False	False	True	False	False	False	False	True	False	False	False	False	False
```

**Comment by rpetit3** [comment]
@BiocondaBot please add label

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Comment by rpetit3** [comment]
Thank you!

**Pull request merged**
