### PR TITLE
Update: maxbin2, remove myself as a maintainer

### PR DESCRIPTION
**Pull request by colinbrislawn**

### CODE REVIEW

**Comment by bernt-matthias** [comment]
Seems that the original download source is unavailable. Someone made (see comments in https://sourceforge.net/projects/maxbin2/) a copy available: https://zenodo.org/record/4247277/files/MaxBin-2.2.7.tar.gz

**Comment by bernt-matthias** [comment]
Is there a specific reason that you want to remove yourself from the maintainer list?

**Comment by colinbrislawn** [comment]
I'm not in contact with the primary software developers, and I no longer work within the National Lab system, so I'm not sure I'm the best person for the job. I opened this PR partly because I was not sure how the fix this build.

**Comment by bernt-matthias** [comment]
Do you have more information on what is wrong with the build?

**Comment by colinbrislawn** [comment]
The current build is breaking because the National Lab website hosting it has changed. [This PR](https://github.com/bioconda/bioconda-recipes/pull/25064) switches the build to sourceforge, where the code was also released. Well done finding the source code on Zenodo, btw

**Comment by bernt-matthias** [comment]
Then I suggest to switch the URL to the zenodo link, since download links generated for sourceforge are not stable. Alternatively we could put it into the depot of the galaxy project.

**Comment by bgruening** [comment]
This seems to be fixed on master.

**Pull request closed without merging**
