### PR TITLE
updated recipe for nextflow 0.23.4

### PR DESCRIPTION
**Pull request by odoublewen**
* [x] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

This PR replaces PR #2657

### CODE REVIEW

**Comment by bgruening** [comment]
@odoublewen do you know what this is?
https://travis-ci.org/bioconda/bioconda-recipes/jobs/211616089#L1627

Is wget a requirement?

**Comment by odoublewen** [comment]
Yes, good point, this looks like an undocumented requirement (either curl or wget, see below).

However, this isn't the direct cause of the error.  The docker container actually does have wget -- see the error message is providing usage help page for wget.  The actual cause of the error is the line above, where it say `mktemp: invalid argument`

Here are the relevant lines from the installer script:

```
function install() {
    local tmpfile=$(make_temp)
    get "http://www.nextflow.io/releases/latest/nextflow" "$tmpfile" "$1" || exit $?
...
```
and:
```
function make_temp() {
    local base=${NXF_TEMP:=$PWD}
    if [ "$(uname)" = 'Darwin' ]; then mktemp ${base}/nxf-tmp.XXXXX || exit $?
    else mktemp -t nxf-tmp.XXXXX -p ${base} || exit $?
    fi
}
```
and:
```
function get() {
    if command -v wget &>/dev/null; then
        GET="wget -q $1 -O $2"
    elif command -v curl &>/dev/null; then
        GET="curl -fsSL $1 -o $2"
    else
        echo_red "Error: cannot find 'curl' nor 'wget' utility --  please install one of them"
        exit 1
    fi
...
```

I'll ask the author, @pditommaso

**Comment by odoublewen** [comment]
Fundamentally, this is because the busybox container has a mktemp that doesn't have the -p option (it is more like the darwin mktemp)

**Comment by odoublewen** [comment]
The author [says](https://github.com/nextflow-io/nextflow/issues/305#issuecomment-287092648) that the package requires Bash (this was undocumented) and GNU mktemp.

Easiest solution would be if we could run the CI tests with a fatter docker image, like debian jessie.

**Comment by bgruening** [comment]
@odoublewen but this is exactly the error we want to catch. You can depend on `coreutils` to satisfy the dependencies.

**Comment by odoublewen** [comment]
Of course.  Makes total sense.  Thanks for reminding me of `coreutils`

I think this recipe PR is ready to be merged.

**Comment by bgruening** [comment]
Nice one! Thanks @odoublewen!

**Pull request merged**
