### PR TITLE
IQTree: new version

### PR DESCRIPTION
**Pull request by tiagoantao**
* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [X] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by tiagoantao** [comment]
I would appreciate a review here. Maybe from @druvus ?

**Comment by druvus** [comment]
Not sure why it is failing. I have seen it previously that it fails when you have an older version in a sub folder. I suggest that you try to skip the older recipe for now to see it it would fix the issue.

**Comment by johanneskoester** [comment]
The error is here: https://travis-ci.org/bioconda/bioconda-recipes/jobs/245071249#L1203

Apart from that, conda erroneously also tries to build the old recipe recursively. I'll have a look at that.

**Comment by johanneskoester** [comment]
I have restarted the build because the fixed bioconda-utils has been merged.

**Comment by druvus** [comment]
thanks @johanneskoester

**Comment by tiagoantao** [comment]
thanks @johanneskoester  and @druvus

**Pull request merged**
