### PR TITLE
Add Whokaryote

### PR DESCRIPTION
**Pull request by dirkjanvw**
Adding Whokaryote v1.0.0 to bioconda-recipes on behalf of @LottePronk.

Please don't merge yet, because even though this is a working recipe (according to `bioconda-utils build --packages whokaryote`), we are still discussing whether we want to add this recipe manually (as is now) or via a skeleton based on PyPI.

### CODE REVIEW

**Comment by dirkjanvw** [comment]
@bioconda-bot please fetch artefacts

**Comment by dirkjanvw** [comment]
@bioconda-bot please fetch artifacts

**Comment by dirkjanvw** [comment]
@BiocondaBot please fetch artifacts

**Comment by dirkjanvw** [comment]
@BiocondaBot please fetch artifacts

**Comment by dirkjanvw** [comment]
@bioconda/core I would like to get the artifacts from the pipeline for some testing with Whokaryote, but I can't seem to figure out how to get the bot to spit out these files. Can you help?

**Comment by rpetit3** [comment]
@BiocondaBot please fetch artifacts

**Comment by dirkjanvw** [comment]
Thanks for the help, it works as expected! And we decided that we would like to add the recipe as it is now.

**Comment by dirkjanvw** [comment]
@BiocondaBot please add label

**Review by rpetit3 — APPROVED** [review]

**Comment by rpetit3** [comment]
@BiocondaBot please merge

**Comment by rpetit3** [comment]
@BiocondaBot please merge

**Pull request merged**
