### PR TITLE
Bulk: Add quota_anchor recipe

### PR DESCRIPTION
**Pull request by aliciaaevans**
Merge to bulk to build on GHA.

Original PR: https://github.com/bioconda/bioconda-recipes/pull/50528

### CODE REVIEW

**Comment by xiaodli** [comment]
> Merge to bulk to build on GHA.
> 
> Original PR: #50528

I apologize for the delayed response. ```Bulk branch 's recipe is ok .```
Thank you for your continued contributions to the open-source community.

**Comment by xiaodli** [comment]
> Merge to bulk to build on GHA.
> 
> Original PR: #50528

Hi, If I have a new version of a recipe to update. Should I make a pull request to the master or bulk branch? The current quota_anchor recipe in the bulk branch is correct, please merge this recipe into the master branch.

**Comment by aliciaaevans** [comment]
> Hi, If I have a new version of a recipe to update. Should I make a pull request to the master or bulk branch? The current quota_anchor recipe in the bulk branch is correct, please merge this recipe into the master branch.

@xiaodli I just merged the version from bulk to master. If you want to make changes you can branch from master now. Thanks for your patience.

**Comment by xiaodli** [comment]
> > Hi, If I have a new version of a recipe to update. Should I make a pull request to the master or bulk branch? The current quota_anchor recipe in the bulk branch is correct, please merge this recipe into the master branch.
> 
> @xiaodli I just merged the version from bulk to master. If you want to make changes you can branch from master now. Thanks for your patience.

Thank you for merging the changes. Best of luck with your ongoing work

**Pull request merged**
