### PR TITLE
update csvtk to v0.31.1

### PR DESCRIPTION
**Pull request by shenwei356**
Describe your pull request here

### Changes

- [csvtk v0.31.1](https://github.com/shenwei356/csvtk/releases/tag/v0.31.1) [Github Releases (by Release)](https://github.com/shenwei356/csvtk/releases/tag/v0.31.1)
    - `csvtk filter2/mutate2/mutate3`:
        - fix the slow speed, I was stupid before. [#172](https://github.com/shenwei356/csvtk/issues/172)
    - `csvtk csv2json`:
        - further fix values with double quotes and new line symbols. [#291](https://github.com/shenwei356/csvtk/issues/291)
----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

### General instructions

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

### Instructions for avoiding API, ABI, and CLI breakage issues
Conda is able to record and lock (a.k.a. pin) dependency versions used at build time of other recipes.
This way, one can avoid that expectations of a downstream recipe with regards to API, ABI, or CLI are violated by later changes in the recipe.
If not already present in the meta.yaml, make sure to specify `run_exports` (see [here](https://bioconda.github.io/contributor/linting.html#missing-run-exports) for the rationale and comprehensive explanation).
Add a `run_exports` section like this:

```yaml
build:
  run_exports:
    - ...

```

with `...` being one of:

| Case                             | run_exports statement                                               |
| -------------------------------- | ------------------------------------------------------------------- |
| semantic versioning              | `{{ pin_subpackage("myrecipe", max_pin="x") }}`     |
| semantic versioning (0.x.x)      | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}`   |
| known breakage in minor versions | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| known breakage in patch versions | `{{ pin_subpackage("myrecipe", max_pin="x.x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| calendar versioning              | `{{ pin_subpackage("myrecipe", max_pin=None) }}`    |

while replacing `"myrecipe"` with either `name` if a `name|lower` variable is defined in your recipe or with the lowercase name of the package in quotes.

### Bot commands for PR management

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

Note that the <code>@BiocondaBot please merge</code> command is now depreciated. Please just squash and merge instead.

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by shenwei356** [comment]
> Bioconda and Conda-Forge occupy the same name space and have agreed not to add packages if a package of the same name is\nalready present in the respective other channel

It seems that someone has added it to conda-forge channel today: https://anaconda.org/conda-forge/csvtk.

**Comment by apcamargo** [comment]
I didn’t check if `csvtk` was already in Bioconda before creating the recipe, as I thought it suited a general-purpose tool better and added it to conda-forge. I’m not sure how to handle cases like this. I can add @shenwei356 as a maintainer to the conda-forge feedstock (if he's interested), but if he prefers it in Bioconda, is there a way to address that since he’s the developer?

**Comment by shenwei356** [comment]
I think it's better staying here, as some packages depend on it (maybe old versions).

**Comment by aliciaaevans** [comment]
Conda-forge does have a [linter](https://github.com/conda-forge/staged-recipes/pull/27841#issuecomment-2405991315) that notifies that something exists in bioconda already, but it is admittedly easy to overlook among several auto-generated comments. 

Because of strict channel priority, it's difficult to move recipes back to bioconda once they exist in conda-forge. I'm not sure what the process is for removing something from conda-forge. I suspect you'd have to request some manual intervention from their core team.

If you'd like to remove the recipe from bioconda, open a PR deleting meta.yaml and any other files from the recipe folder. The older versions will remain in the bioconda channel and those versions should be able to be installable if specified by users.

**Comment by shenwei356** [comment]
@aliciaaevans Thanks for your message. As @apcamargo said, csvtk is a more general-purpose tool, so I think conda-forge should be the right place. I'll submit a PR to remove it from bioconda.

> The older versions will remain in the bioconda channel and those versions should be able to be installable if specified by users.

It's great!

**Comment by shenwei356** [comment]
> If you'd like to remove the recipe from bioconda, open a PR deleting meta.yaml and any other files from the recipe folder.

Do you mean the directory should be kept?

    $ tree recipes/csvtk/
    recipes/csvtk/
    ├── build.sh
    └── meta.yaml

**Comment by martin-g** [comment]
> Do you mean the directory should be kept?

Remove the whole folder with its contents.

**Comment by shenwei356** [comment]
OK, thanks @martin-g

**Pull request closed without merging**
