### PR TITLE
Update sistr_cmd to 1.1.1

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`sistr_cmd`](https://bioconda.github.io/recipes/sistr_cmd/README.html): **1.1.0** &rarr; **1.1.1**

[install with bioconda](http://bioconda.github.io/recipes/sistr_cmd/README.html) [Conda](https://anaconda.org/bioconda/sistr_cmd/files)

Info | Link
-----|-----
Recipe | [`recipes/sistr_cmd`](https://github.com//bioconda/bioconda-recipes/tree/bump/sistr_cmd/recipes/sistr_cmd) (click to view/edit other files)
Releases |[https://pypi.org/pypi/sistr_cmd/json](https://pypi.org/pypi/sistr_cmd/json)

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by apetkau** [comment]
One of the dependencies has changed so I'll see if I can update this branch before merge (or should it be done in another branch?)

**Comment by apetkau** [comment]
Okay, got the dependencies updated. It simply removed a requirement of a specific version of BLAST (since we fixed an issue).

**Comment by npavlovikj** [comment]
@BiocondaBot please fetch artifacts

**Comment by npavlovikj** [comment]
@BiocondaBot please fetch artifacts

**Comment by npavlovikj** [comment]
@BiocondaBot please merge

**Comment by npavlovikj** [comment]
@apetkau , thank you so much for modifying the recipe, as well as adding a new release so fast :)

**Comment by apetkau** [comment]
@npavlovikj no problem.

**Pull request merged**
