### PR TITLE
Update sambamba to 1.0.1

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`sambamba`](https://bioconda.github.io/recipes/sambamba/README.html): **1.0** &rarr; **1.0.1**

[install with bioconda](http://bioconda.github.io/recipes/sambamba/README.html) [Conda](https://anaconda.org/bioconda/sambamba/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/sambamba`](https://github.com//bioconda/bioconda-recipes/tree/bump/sambamba/recipes/sambamba) (click to view/edit other files)
Summary | Tools for working with SAM/BAM data
Home | [https://github.com/biod/sambamba](https://github.com/biod/sambamba)
Releases |[https://github.com/biod/sambamba/tags](https://github.com/biod/sambamba/tags)
Recipe Maintainer(s) | @mjsteinbaugh
Author | `@biod`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by mjsteinbaugh** [comment]
Blarg, the Mac check is failing -- I'll take a look

**Comment by mjsteinbaugh** [comment]
Build failure is here:
https://dev.azure.com/bioconda/bioconda-recipes/_build/results?buildId=38831&view=logs&jobId=1b052f1d-4456-52f0-9d43-71c4c5bd734d&j=1b052f1d-4456-52f0-9d43-71c4c5bd734d&t=edc48dcd-1fc2-5e3b-7036-7be9cea00123

@pjotrp sambamba is failing to build on macOS -- any ideas on how to fix? I'll see if I can build from source on my machine locally.

**Comment by mjsteinbaugh** [comment]
Install instructions are here for reference: https://github.com/biod/sambamba/blob/master/INSTALL.md

**Comment by pjotrp** [comment]
I have not tried building with clang, mind. Could try later.

**Comment by pjotrp** [comment]
If you can get a different linker to work you can send me a patch.

**Comment by mjsteinbaugh** [comment]
@pjotrp OK I'm getting closer but am now hitting this error on my Mac:

```
ld: unknown option: -flto=full
```

My build script is here for reference:
https://github.com/acidgenomics/koopa/blob/develop/lang/bash/include/install/common/shared/sambamba.sh

**Comment by mjsteinbaugh** [comment]
OK got it working on my Mac. Need to call `export CC=gcc` rather than chaining it in the `make` command. Then that will use gcc correctly instead of clang. Should be able to take a look into fixing this for conda soon.

**Comment by mjsteinbaugh** [comment]
I dunno, giving up on this due to the placeholder weirdness

**Comment by pjotrp** [comment]
Sorry it is so complicated. I guess mixing in the gcc toolchain is confusing things. We can try use the gold linker instead...

**Comment by mjsteinbaugh** [comment]
Here's some other build recipes that work on macOS clang, for reference:

- https://github.com/Homebrew/homebrew-core/blob/master/Formula/s/sambamba.rb
- https://github.com/acidgenomics/koopa/blob/main/lang/bash/include/install/common/shared/sambamba.sh

Seems like conda is just getting tripped up at the binary copy step, and I'm not sure how to fix it.

**Pull request closed without merging**
