### PR TITLE
Add perl-bio-searchio-hmmer

### PR DESCRIPTION
**Pull request by 0xaf1f**
Bio::SearchIO::hmmer was formerly part of the core bioperl distribution [until version 1.7.3](https://metacpan.org/dist/BioPerl/changes) when it and a bunch of other components were split out into separate development repositories (thanks @rpetit3 for digging this up), so later bioperl packages here caused problems for the prokka package (#33356), which uses this component.

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by 0xaf1f** [comment]
@bioconda/core, when a PR touches multiple packages, why doesn't the package builder use the newly built ones when building the remaining packages? It's not reasonable to have to wait for each change to hit the archive before submitting the next one.

There's an issue with a missing dependency in `perl-bioperl-core`. That package gets built first, then thrown away. Then, when `perl-bio-searchio-hmmer` is being built, the broken package from the archive is being pulled in and the package build has no chance. It should use the `perl-bioperl-core` that was just built...

**Comment by 0xaf1f** [comment]
Due to inadequacies of the builder here, I'm forced to make this 3 PRs instead of 1.

**Comment by 0xaf1f** [comment]
@dpryan79 I added the missing dependency on `perl-test-most` for `perl-bio-searchio-hmmer` to get rid of a bunch of the noise in the log (speaking of noise, the container doesn't seem to like `C.UTF-8`) and hopefully what I was saying before on gitter is more clear. I get what you said about the package build order being problematic, but this is an issue too:


When `perl-bio-searchio-hmmer` is being built, it's getting
```
01:10:42 BIOCONDA INFO (OUT)     perl-bioperl-core:           1.7.8-pl5321h9ee0642_0  bioconda
```
instead of the freshly built
```
01:04:09 BIOCONDA INFO (ERR) [Mar 21 01:04:09] SOUT perl-bioperl-core  conda-bld/noarch::perl-bioperl-core-1.7.8-pl5321hdfd78af_1
```

which results in this subtle test failure:

```
01:11:45 BIOCONDA INFO (OUT) Test Summary Report
01:11:45 BIOCONDA INFO (OUT) -------------------
01:11:45 BIOCONDA INFO (OUT) t/LocalDB-Index.t      (Wstat: 256 Tests: 4 Failed: 1)
01:11:45 BIOCONDA INFO (OUT)   Failed test:  3
01:11:45 BIOCONDA INFO (OUT)   Non-zero exit status: 1
01:11:45 BIOCONDA INFO (OUT) Files=7, Tests=1166,  4 wallclock secs ( 0.10 usr  0.00 sys +  2.98 cusr  0.33 csys =  3.41 CPU)
01:11:45 BIOCONDA INFO (OUT) Result: FAIL
01:11:45 BIOCONDA INFO (OUT) Failed 1/7 test programs. 1/1166 subtests failed.
```

**Comment by dpryan79** [comment]
@BiocondaBot please update

**Comment by 0xaf1f** [comment]
so this it's a general conda solver problem to not pull in the latest build of a package? Or is it channel priority not preferring local over bioconda/conda-forge?

**Comment by 0xaf1f** [comment]
It looks like the mulled-build correctly picks up the new local packages, but the original build doesn't. Do you know why that is?

**Comment by 0xaf1f** [comment]
@BiocondaBot please add label.

I'm still curious about why the regular build and mulled build don't resolve dependencies the same way.

**Comment by dpryan79** [comment]
@0xaf1f The classic conda solver doesn't prioritize the most recent build, or even the most recent version. This has caused a LOT of headaches. Starting in conda 4.12 there's the option to use the mamba solver instead, which will try to use the highest build number and version, which should generally do more what people expect.

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@BiocondaBot please merge

**Comment by 0xaf1f** [comment]
> The classic conda solver doesn't prioritize the most recent build, or even the most recent version. This has caused a LOT of headaches. Starting in conda 4.12 there's the option to use the mamba solver instead, which will try to use the highest build number and version, which should generally do more what people expect.

Ah, got it. Many thanks for getting this working!

**Pull request merged**
