### PR TITLE
pinning VRNA version and add to release tag

### PR DESCRIPTION
**Pull request by martin-mann**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

this PR is needed to know what viennarna version was used for the build, eg to track bugfixes in the viennarna package

### CODE REVIEW

**Comment by martin-mann** [comment]
@bgruening any idea why the [final build failed](https://circleci.com/gh/bioconda/bioconda-recipes/6449?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) after uploading the package?

**Comment by martin-mann** [comment]
error is 
```[bash]

18:58:56 BIOCONDA INFO UPLOAD uploading package /home/circleci/project/miniconda/conda-bld/linux-64/intarna-2.2.0-vrna2.4.4_boost1.64_2.tar.bz2
18:59:07 BIOCONDA INFO UPLOAD SUCCESS: uploaded package /home/circleci/project/miniconda/conda-bld/linux-64/intarna-2.2.0-vrna2.4.4_boost1.64_2.tar.bz2
18:59:08 BIOCONDA ERROR COMMAND FAILED: mulled-build push intarna=2.2.0--vrna2.4.4_boost1.64_2 -n biocontainers --oauth-token <hidden>
18:59:08 BIOCONDA ERROR STDOUT+STDERR:
Traceback (most recent call last):
  File "/home/circleci/project/miniconda/bin/mulled-build", line 6, in <module>
    sys.exit(galaxy.tools.deps.mulled.mulled_build.main())
  File "/home/circleci/project/miniconda/lib/python3.6/site-packages/galaxy/tools/deps/mulled/mulled_build.py", line 419, in main
    sys.exit(mull_targets(targets, **args_to_mull_targets_kwds(args)))
  File "/home/circleci/project/miniconda/lib/python3.6/site-packages/galaxy/tools/deps/mulled/mulled_build.py", line 178, in mull_targets
    repo_data = quay_repository(repo_template_kwds["namespace"], repo_name)
  File "/home/circleci/project/miniconda/lib/python3.6/site-packages/galaxy/tools/deps/mulled/util.py", line 51, in quay_repository
    data = response.json()
  File "/home/circleci/project/miniconda/lib/python3.6/site-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/circleci/project/miniconda/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/home/circleci/project/miniconda/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/circleci/project/miniconda/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Traceback (most recent call last):
  File "/home/circleci/project/miniconda/bin/bioconda-utils", line 11, in <module>
    load_entry_point('bioconda-utils==0.12.2', 'console_scripts', 'bioconda-utils')()
  File "/home/circleci/project/miniconda/lib/python3.6/site-packages/bioconda_utils/cli.py", line 606, in main
    argh.dispatch_commands([build, dag, dependent, lint, duplicates, bioconductor_skeleton, pypi_check, clean_cran_skeleton])
  File "/home/circleci/project/miniconda/lib/python3.6/site-packages/argh/dispatching.py", line 328, in dispatch_commands
    dispatch(parser, *args, **kwargs)
  File "/home/circleci/project/miniconda/lib/python3.6/site-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/home/circleci/project/miniconda/lib/python3.6/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/home/circleci/project/miniconda/lib/python3.6/site-packages/argh/dispatching.py", line 260, in _call
    result = function(*positional, **keywords)
  File "/home/circleci/project/miniconda/lib/python3.6/site-packages/bioconda_utils/cli.py", line 386, in build
    mulled_upload_target=mulled_upload_target,
  File "/home/circleci/project/miniconda/lib/python3.6/site-packages/bioconda_utils/build.py", line 392, in build_recipes
    upload.mulled_upload(res.mulled_image, mulled_upload_target)
  File "/home/circleci/project/miniconda/lib/python3.6/site-packages/bioconda_utils/upload.py", line 71, in mulled_upload
    return utils.run(cmd, mask=mask)
  File "/home/circleci/project/miniconda/lib/python3.6/site-packages/bioconda_utils/utils.py", line 239, in run
    raise e
  File "/home/circleci/project/miniconda/lib/python3.6/site-packages/bioconda_utils/utils.py", line 220, in run
    **kwargs)
  File "/home/circleci/project/miniconda/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['mulled-build', 'push', 'intarna=2.2.0--vrna2.4.4_boost1.64_2', '-n', 'biocontainers', '--oauth-token', '<hidden>']' returned non-zero exit status 1.
Exited with code 1
```

**Comment by martin-mann** [comment]
there is (strangly) a double '--' between '2.2.0' and the build string 'vrna2.4.4_boost...'

shouldnt it be a single dash?

**Comment by bgruening** [comment]
@martin-mann the conda package was actually uploaded. The CI crashed during upload of the Docker image.
And the Docker image contains a `--` to separate build string from version number, as versions can also contain a `-`. Your Docker images is here: https://quay.io/repository/biocontainers/intarna?tab=tags

A simple restart fixed it.
Thanks for the catch and the report.

**Pull request merged**
