### PR TITLE
add LJA genome assembler recipe

### PR DESCRIPTION
**Pull request by zilov**
Describe your pull request here

Add LJA genome assembler recipe
----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by daler** [comment]
@zilov try adding a `host:` section with `zlib`?

**Comment by daler** [comment]
the particular error is [here](https://dev.azure.com/bioconda/bioconda-recipes/_build/results?buildId=29388&view=logs&j=e14e69ff-a0ae-55c4-b71d-229b239cfb2f&t=7df82132-b284-504b-53d6-7d3e63519572&l=1024), perhaps there is a missing dependency? I am not that familiar with C/C++, but does adding the C compiler (as well as `cxx` compiler) to build dependencies help?

**Comment by zilov** [comment]
The last error is connected with this issue (https://github.com/AntonBankevich/LJA/issues/12), I've added regexp to fix it, hope it will help

**Comment by daler** [comment]
There are some changes in the build system being worked on currently; I don't think this is on your side (ping @johanneskoester, is this the quay.io issue you had mentioned?)

**Comment by daler** [comment]
@bioconda-bot please update

**Comment by zilov** [comment]
@daler it seems to be working! could you please approve?

**Pull request merged**
