### PR TITLE
Add spdlog recipe

### PR DESCRIPTION
**Pull request by druvus**
- [x] I have read the guidelines above.
- [x] This PR adds a new recipe.
- [ ] This PR updates an existing recipe.
- [ ] This PR does something else (explain below).

This recipe installs only header files. I included a quite ugly test to check if a specific header file exist in the correct location. @bioconda/core do you have some recommendations for testing header only recipes?

### CODE REVIEW

**Comment by bgruening** [comment]
You could compile a dummy program with these headers, isn't it?

**Comment by druvus** [comment]
True, that is a better solution.

**Comment by bgruening** [comment]
ping @druvus

**Comment by bgruening** [comment]
ping @druvus

**Comment by druvus** [comment]
I am finally adding it to conda-forge so closing this PR.

**Pull request closed without merging**
