### PR TITLE
add trinotate 3.0.1 ... the good version

### PR DESCRIPTION
**Pull request by lecorguille**
* [ ] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [X] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

The conda package version was not good. See: https://github.com/Trinotate/Trinotate/releases 
@bioconda/core can you remove the version 3.2.2

### CODE REVIEW

**Comment by johanneskoester** [comment]
You mean there was a wrong version number in the recipe before?

**Comment by lecorguille** [comment]
@johanneskoester I think so!
The previous recipes set the version at 3.2.2 but download the release 3.0.1

**Comment by johanneskoester** [comment]
Ok, I removed the packages with the wrong version.

**Comment by lecorguille** [comment]
Thanks

**Pull request merged**
