### PR TITLE
Update liftoff to 1.6.0

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`liftoff`](https://bioconda.github.io/recipes/liftoff/README.html): **1.5.2** &rarr; **1.6.0**

[install with bioconda](http://bioconda.github.io/recipes/liftoff/README.html) [Conda](https://anaconda.org/bioconda/liftoff/files)

Info | Link
-----|-----
Recipe | [`recipes/liftoff`](https://github.com//bioconda/bioconda-recipes/tree/bump/liftoff/recipes/liftoff) (click to view/edit other files)
Releases |[https://github.com/agshumate/Liftoff/tags](https://github.com/agshumate/Liftoff/tags)
Recipe Maintainer(s) | @agshumate, @standage
Author | `@agshumate`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by agshumate** [comment]
@BiocondaBot add label

**Comment by agshumate** [comment]
@BiocondaBot please add label

**Comment by standage** [comment]
The CI build wasn't run since `[ci skip]` in the latest commit message. I don't think we'll be able to merge until we have a successful CI build.

**Comment by agshumate** [comment]
@BiocondaBot rebuild

**Comment by standage** [comment]
Editing the meta.yaml file will trigger a new CI build, looks like @dpryan79 beat me to it!

**Comment by standage** [comment]
Ruh roh, looks like it failed.

```
The following problems have been found:

WARNING: recipes/liftoff/meta.yaml:44: gpl_requires_license_distributed: The recipe packages GPL software but is missing copy of license.
ERROR: recipes/liftoff/meta.yaml:17: build_number_needs_bump: The recipe build number should be incremented
```

The first error is clear: the CI build can't locate and verify the GPL license.

I'm not sure why it's saying the build number needs to be incremented though.

**Comment by dpryan79** [comment]
liftoff was merged in via a different PR an hour ago, thus the need to bump the build number

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Comment by agshumate** [comment]
@dpryan79 and @standage thank you for the help!

**Pull request merged**
