### PR TITLE
update_kma

### PR DESCRIPTION
**Pull request by ptlcc**
Update kma

### CODE REVIEW

**Comment by ptlcc** [comment]
@BiocondaBot please add label

**Comment by holtgrewe** [comment]
@ptlcc I think you only intended to update kma here

**Review by holtgrewe — CHANGES_REQUESTED** [review]
remove ccphylo update?

**Comment by ptlcc** [comment]
@holtgrewe I intended to update both. CCPhylo was accepted yesterday but somehow it ended up here too, so this was just intended for kma.

**Comment by bgruening** [comment]
@ptlcc please remove the other package then from the PR

**Comment by dpryan79** [comment]
@BiocondaBot please update

**Comment by dpryan79** [comment]
Can you resolve the merge conflict?

**Comment by ptlcc** [comment]
Not without going against bgruening's request.

**Pull request closed without merging**
