### PR TITLE
nanopolish: loosen hdf5 version for compatibility with medaka

### PR DESCRIPTION
**Pull request by jts**
Nanopolish and medaka currently cannot be installed in the same environment. This PR attempts to reconcile this

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by jts** [comment]
@BiocondaBot please fetch artifacts

**Comment by jts** [comment]
@BiocondaBot please fetch artifacts

**Comment by jts** [comment]
@nickloman this version can co-exist with medaka. it hasn't been tested with the other packages in medaka's artic environment yet

**Comment by cjw85** [comment]
@nickloman @jts 
Adding the conda channel listed by the bot above to the ARTIC environment.yml allows things to build and execute successfully.

**Comment by will-rowe** [comment]
Pinging @druvus who is currently working on conda recipe for the ARTIC pipeline over in https://github.com/bioconda/bioconda-recipes/pull/21350 !

**Comment by druvus** [comment]
Seems to work for me locally Fixing the other PR once this change is merged and uploaded.

**Comment by bgruening** [comment]
Mh, I don' think its good to pin hdf5 to an older version. Any strict pinning is a problem.

Why can we not fix the medaka recipe and work with a more recent version of hdf5? I guess the problem is here: https://github.com/bioconda/bioconda-recipes/blob/master/recipes/medaka/meta.yaml#L36

**Comment by jts** [comment]
IIRC medaka requires that version of h5py for its model training method. @cjw85 would know more. Pinning the hdf5 version in the nanopolish recipe is the only way to include nanopolish and medaka in the same environment, which is highly desirable for ARTIC so we've had to make this concession.

**Comment by bgruening** [comment]
@jts but this is a medaka problem. Imho we can not sacrifice other environments, just because of medaka has some restrictions. You can always use two envs, isn't it?

One big downside of this pinning as it is currently is that it seems that nanopolish lost its multithreading ability.

**Comment by jts** [comment]
@mmiladi has determined the loss of multithreading is due to the upgrade from 0.11.3 to 0.12.0, which changed the build substantially. This is before I pinned hdf5 in this PR.

I agree that its not ideal but given the importance of ARTIC for coronavirus genome sequencing I think this is the best option for now. Having two environments complicates the pipeline/user experience

**Comment by bgruening** [comment]
> I agree that its not ideal but given the importance of ARTIC for coronavirus genome sequencing I think this is the best option for now. Having two environments complicates the pipeline/user experience

Just saying you are forcing everyone else with an hdf5 dependency to use an older nanopolish version or even worse to break environments.

**Pull request merged**
