### PR TITLE
Plascope

### PR DESCRIPTION
**Pull request by duboism**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by duboism** [comment]
@bioconda/core: this is my first recipe, can you review it ?

**Comment by bgruening** [comment]
There went something wrong with your merge. Can you please rebase?

**Comment by bgruening** [comment]
@duboism there are still many commit in this PR that do not belong into it :(

**Comment by duboism** [comment]
@bgruening Sorry for this. This appeared during the rebase (probably my mistake). I'm a bit lost here. Do you know what can I do ?

**Comment by bgruening** [comment]
I fixed it for you, can you please review it and make sure I have not made it worse?

**Comment by duboism** [comment]
@bgruening  Thanks. The files are OK (it's a very simple recipe).

**Comment by bgruening** [comment]
Awesome! Thanks!

**Pull request merged**
