### PR TITLE
fix error code in travis-run.sh; blacklist failing package

### PR DESCRIPTION
**Pull request by daler**
* [ ] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [x] This PR does something else (explain below).

@bioconda/all if you have submitted a PR since Oct 11, you may have to re-submit. The build system has been giving false positives. Builds would fail, but at the end the exit code would be 0 so travis-ci would incorrectly report the build as passing.

The problem was [this change](https://github.com/bioconda/bioconda-recipes/commit/6411abd8bb8c1cac1a32b4e9e5a30f816fcb4f63#diff-a666270151818014dbda5ced5b3bc54eR8). While `set -euo pipefail` is set at the script level, it is not set in the call to the docker container. This means that the final reported exit code from docker was from the `set +x` call, which was always zero even if the build failed.

This PR adds `set -euo pipefail` to the docker command to fix the issue.

I'm sorry to say this was my change that caused the error, so I'll be going through all the commits since then to make sure they build correctly now. It may take some time, so if you want to make sure your package is available in the bioconda channel then you may want to re-submit.

Sorry for the inconvenience, and please watch this PR for updates.

### CODE REVIEW

**Comment by dpryan79** [comment]
Is there a recommended way to test if the build worked properly? Perhaps just `conda install foo` and run the test from the yaml file?

**Comment by daler** [comment]
If the tarball was uploaded to anaconda, then you should be fine. A merge to the master branch does the build, tests the build, and uploads it only if that test passes.

If the build or the test failed then it wouldn't be uploaded . . . but the travis-ci result would still be green, which was the problem.

**Comment by daler** [comment]
### Update

To double-check the effects of this bug, I went through all of the commits for new and updated recipes over the past couple of weeks. For each one I confirmed that the package was in fact uploaded to Anaconda, indicating that the build was truly successful.

Results below. I've included the PR number cross-references so we'll have a record of which commits would have been affected by this. Almost everything was fine. There were two cases, `gvcftools` and `autoconf`, that were failing. They are now on the `build-fail-blacklist`. Autoconf I think @druvus is going to follow up with conda-forge for fixing, and gvcftools I think just needs some patching (cc @pvanheus).

So we should be good now.

### Package review

The following table lists commits affecting meta.yaml files in such a way that would trigger a re-build and upload, since 6411abd8bb8c1.

package    |version|contributor |PR       | status
-----------|-------|------------|---------|-------
`sixgill`  | 0.2.4 | @jj-umn    | #2596   | OK
`r-ggalt`  |0.1.1 r3.2.2 | @bgruening | #2575   | OK
`goleft`   | 0.1.6 | @brentp    | #2597   | OK
`flaimapper`| 2.0.0| @yhoogstrate| #2594| OK
`cutadapt`  | 1.11|@marcelm| #2598 | OK
`gvcftools` | 0.17.0| @pvanheus | #2601, #2627 | **NOT UPLOADED**
`pyalveo`   | 0.7   | @stevecassidy | #2603 | OK
`spectra-cluster-cli` | 1.0.1 | @ypriverol | #2602 | OK
`bedtools` | 2.26.0gx | @mvdbeek | #2605 | OK
`bioconductor-rots` | 1.0.0-r3.3.1| @lecorguille | #2611 | OK
`wdltool` | 0.6 | @tomkinsc | #2615 | OK
`goatools` | 0.6.10 | @saketc | #2616 | OK
`epic` | 0.1.20 | @dpryan79 | #2617 | OK
`bcftools` | 1.3.1_1 | @rvalieris | #2619 | OK
`bcbio-nextgen-vm` | 0.1.0a build 86 | @chapmanb | #2621 |OK
`bcbio-nextgen` | 1.0.0a0 build 8 | @chapmanb | #2621 | OK
`biogridpy` | 0.1.1 | @arkevi | #2524 | OK
`cromwell` | 0.22 | @tomkinsc | #2625 | OK
`pandaseq` | 2.10 | @druvus | #2630 | OK for OSX, no Linux
`bioconductor-xcms` | 1.44.0, 1.46.0 r3.3.1 | @lecorguille | #2631 | OK for linux (OSX skipped on purpose)
`fgbio` | 0.1.2a | @chapmanb | #2633 | OK
`drive` | 0.3.8 | @chapmanb | #2633 | OK
`bioconductor-camera` | 1.22.0, 1.26.0, 1.28.0 r3.3.1 build 1 | @lecorguille | #2634 |
`bioconductor-s4vectors` | 0.8.11 r3.3.1 | @lecorguille | #2634 | OK
`metaphlan2` | 2.5.0 build 1 | @jerowe | # 2636 | OK
`deeptools` | 2.3.6 | @dpryan79 | #2638 | OK
`baitfisher` | 1.0 | @druvus | #2639 | OK
`deltabs` | 0.1 | @druvus | #2640 | OK
`yass` | 1.14 | @dmaticzka | #2642 | OK
`ghostscript` | 9.18 for OSX | @mvdbeek | #2643 | OK
`autoconf` | 2.69 | @druvus | #2646 | **NOT UPLOADED**
`gseapy` | 0.7.2 | @BioNinja | #2651 | OK

**Comment by colinbrislawn** [comment]
Thanks for posting this update! I wonder if the issue with `autoconf` is causing #2548... 

Thank you for your updates!

**Comment by daler** [comment]
@colinbrislawn #2548 that looks to be a different issue with a hard-coded path to perl in autoconf

**Pull request merged**
