### PR TITLE
samtools openssl>1.1

### PR DESCRIPTION
**Pull request by pb-cdunn**
See #13909

:information_source:
Bioconda has finished the [GCC7 migration](https://github.com/bioconda/bioconda-recipes/issues/13578). If you are dealing with C/C++ or Python package it can be that you need to rebuild other dependent packages. [Bioconda utils - update-pinning](https://bioconda.github.io/updating.html#updating-recipes-for-a-pinning-change) will assist you with that. If you have any questions please use [issue 13578](https://github.com/bioconda/bioconda-recipes/issues/13578).

----------------

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by unode** [comment]
So `<` is ok but `>` isn't. The fun never ends! :)

**Comment by pb-cdunn** [comment]
No, I tried `>=` in another PR somewhere.

I don't understand why `>` does not work.

* https://docs.conda.io/projects/conda-build/en/latest/source/resources/package-spec.html#package-match-specifications
* https://docs.conda.io/projects/conda-build/en/latest/source/resources/define-metadata.html#requirements-section

**Comment by pb-cdunn** [comment]
Nope.
```py
  File "/home/circleci/project/miniconda/lib/python3.6/site-packages/conda_build/render.py", line 162, in get_pin_from_build
    pin = utils.apply_pin_expressions(version.split()[0], **pin_cfg)
  File "/home/circleci/project/miniconda/lib/python3.6/site-packages/conda_build/utils.py", line 1208, in apply_pin_expressions
    parsed_version = VersionOrder(version).version[1:]
  File "/home/circleci/project/miniconda/lib/python3.6/site-packages/conda/models/version.py", line 163, in __new__
    raise CondaValueError(message + "invalid character(s).")
conda.exceptions.CondaValueError: Malformed version string '>=1.1.1': invalid character(s).
Exited with code 1
```

**Comment by pb-cdunn** [comment]
https://github.com/conda/conda/blob/master/conda/models/version.py#L46

I think it needs a space. (I don't know why `<` works without a space.)

**Comment by pb-cdunn** [comment]
```
Error: bad character '>=' in package version dependency 'openssl'
Perhaps you meant 'openssl >=1.1.1'
```
Ugh! There seems to be inconsistency between `conda` and `conda-build lint`.

**Comment by unode** [comment]
@bioconda/core any suggestions how to proceed here?

**Comment by dpryan79** [comment]
I'm going to start migrating packages to the new OpenSSL pinning this week. Samtools and related packages will be the first to be migrated.

**Comment by pb-cdunn** [comment]
What about the problem with `>=`? Build wants a space; lint does not. I think there is a bug in the spec parser.

**Comment by dpryan79** [comment]
I wonder if `conda-build` is throwing an error due to the mismatch in `meta.yaml` and `conda_build_config.yaml`. The pinning in the yaml file will get ignored, I think, since there's a `conda_build_config.yaml`. The `>=1.1.1` syntax is actually correct and is used in many recipes (e.g., deepTools).

**Comment by pb-cdunn** [comment]
```
% ls recipes/samtools/
0.1.19  1.1  1.6  build.sh  meta.yaml
```
Hmmm. `<` worked fine. `>` and `>=` both failed.

**Pull request closed without merging**
