### PR TITLE
Update capc-map

### PR DESCRIPTION
**Pull request by cbrackley**
* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [X] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [X] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by cbrackley** [comment]
All tests passed. @bioconda/core please merge.

**Comment by npavlovikj** [comment]
@cbrackley , since this is a new version, the build number should be set to 0 instead of 1. If you are modifying the recipe of an already existing version, then you should increment the build number, https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#build-number-and-string.

Next, GPL packages require the license file to be added in `meta.yaml` as well. Since that file is already in the tarball, please just add:
`license_file: LICENSE`
in `meta.yaml`.

**Comment by cbrackley** [comment]
@npavlovikj Thanks for pointing out the problems in meta.yaml, now fixed.

**Comment by dpryan79** [comment]
Thanks @cbrackley and @npavlovikj! I've made a few small changes to parts that predated the update, once that passes it's good to go.

**Comment by dpryan79** [comment]
I'll bump bowtie1 so it has a build for python 3.7, then this will probably pass testing.

**Comment by dpryan79** [comment]
This is good to go now. Note that since it's using bowtie1, it won't get built for python 3.7 (this is due to bowtie1 not being compliant with newer C++ versions, so it's not compilable any more).

**Comment by dpryan79** [comment]
@bioconda-bot recheck

**Comment by dpryan79** [comment]
@bioconda-bot merge

**Pull request merged**
