### PR TITLE
Update liquorice to 0.5.6

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`liquorice`](https://bioconda.github.io/recipes/liquorice/README.html): **0.5.5** &rarr; **0.5.6**

[install with bioconda](http://bioconda.github.io/recipes/liquorice/README.html) [Conda](https://anaconda.org/bioconda/liquorice/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/liquorice`](https://github.com//bioconda/bioconda-recipes/tree/bump/liquorice/recipes/liquorice) (click to view/edit other files)
Summary | A tool for bias correction and quantification of changes in coverage around regions of interest in cfDNA WGS datasets
Home | [https://github.com/epigen/LIQUORICE](https://github.com/epigen/LIQUORICE)
Releases |[https://github.com/epigen/LIQUORICE/tags](https://github.com/epigen/LIQUORICE/tags)
Author | `@epigen`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by daler** [comment]
Ping @tomazou-lab, looks like you're maintaining a [meta.yaml](https://github.com/epigen/LIQUORICE/blob/676381ab5b632b7f23cb86074f76a53cbe119130/conda-recipe/meta.yaml) separately in the package. Is that meta.yaml intended to make its way over here?

**Comment by peneder** [comment]
Hi! Thanks for looking into this. Not really, I keep the meta.yaml under epigen/liquorice only for completeness/archival - I know that it is not used by bioconda. Should I remove or rename it to avoid confusion?

Also, the tests failed with error code 137 (out of memory) - I will try to re-build:

**Comment by peneder** [comment]
@BiocondaBot rebuild

**Comment by peneder** [comment]
Hmm, I cannot trigger a rebuild for some reason, could you try that please @daler ?

**Pull request closed without merging**
