### PR TITLE
Add ORFfinder

### PR DESCRIPTION
**Pull request by apcamargo**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by apcamargo** [comment]
@bioconda/core NCBI doesn't seem to provide a license to ORFfinder. Can we distribute it?

https://www.ncbi.nlm.nih.gov/orffinder/

**Comment by dpryan79** [comment]
@apcamargo As it's a US government product it's innately public domain. So yes, we can certainly redistribute it.

**Comment by dpryan79** [comment]
We'll have to find the source code for this, since the binary won't work on all systems.

**Comment by apcamargo** [comment]
I couldn't find it. I don't think it is publicly available.

**Comment by apcamargo** [comment]
@BiocondaBot update

**Pull request closed without merging**
