### PR TITLE
Update to 2.6.0

### PR DESCRIPTION
**Pull request by AlessioMilanese**
Describe your pull request here

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [ ] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

In this update we have a new database (version 2.6.0) and we solve minor bugs in the code.
Note: this is the second test to try to add version 2.6.0. Now we print the error of why samtools fails.

### CODE REVIEW

**Comment by AlessioMilanese** [comment]
When I test the samtools installation I have:
```
18:07:17 BIOCONDA INFO (OUT) samtools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
```

This comes from running `samtools --version` in test.py ([line 112](https://github.com/motu-tool/mOTUs_v2/blob/master/test.py#L112)) in the section `test` of the meta.yaml ([line 31](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/motus/meta.yaml#L31)) for mOTUs.

I read about this error, but I cannot find any solution. Also, in my understanding it was solved (https://github.com/bioconda/bioconda-recipes/issues/13958).

@cbrueffer, any idea?

**Review by unode — APPROVED** [review]
The failure seems unrelated to the change.
Looks like a combination of dependencies somehow breaks `samtools`.

I'm not up to speed with any pending issues affecting samtools but I don't think the library failure should be fixed here.

**Comment by unode** [comment]
Perhaps what you could force here is a minimum version of `samtools` and `bwa`.
`metasnv` also has flexible dependencies and it's possible that the dependency resolver is picking an incompatible combination.

**Comment by AlessioMilanese** [comment]
@unode, can you merge?

**Comment by unode** [comment]
Looks like this fixed it.

**Pull request merged**
