### PR TITLE
Update ccsmeth to 0.4.0

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`ccsmeth`](https://bioconda.github.io/recipes/ccsmeth/README.html): **0.3.4** &rarr; **0.4.0**

[install with bioconda](http://bioconda.github.io/recipes/ccsmeth/README.html) [Conda](https://anaconda.org/bioconda/ccsmeth/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/ccsmeth`](https://github.com//bioconda/bioconda-recipes/tree/bump/ccsmeth/recipes/ccsmeth) (click to view/edit other files)
Summary | Detecting DNA methylation from PacBio CCS read
Home | [https://github.com/PengNi/ccsmeth](https://github.com/PengNi/ccsmeth)
Releases |[https://github.com/PengNi/ccsmeth/tags](https://github.com/PengNi/ccsmeth/tags)
Recipe Maintainer(s) | @PengNi
Author | `@PengNi`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Review by cbrueffer — APPROVED** [review]

**Comment by PengNi** [comment]
@BiocondaBot please merge

**Comment by cbrueffer** [comment]
Hi @PengNi, the merge bot does not exist anymore, use the merge button instead.

**Comment by cbrueffer** [comment]
Sure; I can also invite you to the organization so you have an easier time maintaining/merging yourself?

**Comment by PengNi** [comment]
> Sure; I can also invite you to the organization so you have an easier time maintaining/merging yourself?

Thank you very much! I would be honored to join this organization!

**Comment by PengNi** [comment]
Thank you very much!

**Pull request merged**
