### PR TITLE
Added SvABA recipe

### PR DESCRIPTION
**Pull request by micknudsen**
Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it. Note that if you are not already a member of the bioconda project (meaning that you can't add this label), please ping `@bioconda/core` so that your PR can be reviewed and merged (please note if you'd like to be added to the bioconda project). Please see https://github.com/bioconda/bioconda-recipes/issues/15332 for more details.

* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [X] This PR adds a new recipe.
* [X] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by micknudsen** [comment]
@bioconda-bot rebuild

**Comment by micknudsen** [comment]
I am getting an `ld: cannot find -lz` error which I suspect is due to submodules not being able to see `zlib`. Does anybody know if it possible to somehow "propagate" `zlib` to submodules?

**Comment by npavlovikj** [comment]
1.
The error can be fixed if `-lz` is replaced with `-lm ${PREFIX}/lib/libz.a`. Maybe try adding:
```
export LIBS="-lm ${PREFIX}/lib/libz.a"
```
?

2.
Also, it is recommended practice to create separate conda packages for the needed submodules, instead of recursively installing them. I would suggest you to look into that if possible.

3.
Please make sure the order of sections in `meta.yaml` is: Package, Source, Build, Requirements, Test, About, Extra.

**Comment by micknudsen** [comment]
@npavlovikj Thanks for your suggestion. I would really prefer to have the submodules as separate packages, but I am not sure whether that is possible. I suppose that the reason for having them as submodules here is that the source code is needed and not just the builds. For example, simply adding `htslib` as a dependency is not enough. Maybe I am missing something here.

**Comment by micknudsen** [comment]
@npavlovikj Didn't manage to solve the problem using your first suggesting. Now going with the second (https://github.com/bioconda/bioconda-recipes/pull/16785).

**Comment by micknudsen** [comment]
@bioconda-bot rebuild

**Comment by micknudsen** [comment]
As this PR clearly shows, I have no experience with C++ at all. However, I am still puzzled why it doesn't just work. When I do this locally (on a Linux machine), it works right away:

```
git clone --recursive git@github.com:walaj/svaba.git
cd svaba
git checkout 1.1.0
./configure
make
make install
```

How is bioconda + CI any different?

**Comment by dpryan79** [comment]
Without looking, I would guess that it's because the compiler you're using is named "gcc" and everything is in the default location on your system. Compiling things in that way will result in packages that won't work on systems where any of those default things is either a different version or place/name. I'll have a look and see if I can get this to compile.

**Comment by micknudsen** [comment]
@dpryan79 Thanks! I am really eager to get a recipe for SvABA. It is an excellent tool, and I would like to use it in a production pipeline. So far all software versions are managed with conda, and I would do (almost) everything to avoid having to have a custom installation.

**Comment by dpryan79** [comment]
Should work now, go ahead and merge if you're happy with it.

**Comment by micknudsen** [comment]
Thanks! That is really amazing!

**Comment by micknudsen** [comment]
Unfortunately, there is something not quite right about this recipe (https://github.com/walaj/svaba/issues/73).

**Pull request merged**
