### PR TITLE
Add tombo

### PR DESCRIPTION
**Pull request by druvus**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by kyleabeauchamp** [comment]
You were quite fast in building this recipe :), only 1 day since public release...

**Comment by bgruening** [comment]
@druvus it seems you have forgotten to `git add` the build.sh file?

**Comment by druvus** [comment]
@bgruening You're right... did it too late.

**Comment by marcus1487** [comment]
Wow incredibly fast indeed! I did not see this before adding my version of tombo recipe (#7007). One difference with the recipe I have added it to name the recipe ont-tombo in order to indicate that this should be an Oxford Nanopore Technologies supported recipe (as with ont-fast5-api). I would like to request that the ont-tombo be used before much larger distribution is adopted. Let me know if there are any issues with this request at this point. Thanks!

**Comment by druvus** [comment]
I added this when ONT made the tombo repo public at github. Later ONT also released it at pypi were they added the prefix. I am fine to remove this and instead use ont-tombo. Any opinions @bioconda/core

**Pull request merged**
