### PR TITLE
Update GFAffix

### PR DESCRIPTION
**Pull request by danydoerr**
Minor version update of GFAffix addressing a critical but rare bug. 

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

### General instructions

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

### Instructions for avoiding API, ABI, and CLI breakage issues
Conda is able to record and lock (a.k.a. pin) dependency versions used at build time of other recipes.
This way, one can avoid that expectations of a downstream recipe with regards to API, ABI, or CLI are violated by later changes in the recipe.
If not already present in the meta.yaml, make sure to specify `run_exports` (see [here](https://bioconda.github.io/contributor/linting.html#missing-run-exports) for the rationale and comprehensive explanation).
Add a `run_exports` section like this:

```yaml
build:
  run_exports:
    - ...

```

with `...` being one of:

| Case                             | run_exports statement                                               |
| -------------------------------- | ------------------------------------------------------------------- |
| semantic versioning              | `{{ pin_subpackage("myrecipe", max_pin="x") }}`     |
| semantic versioning (0.x.x)      | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}`   |
| known breakage in minor versions | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| known breakage in patch versions | `{{ pin_subpackage("myrecipe", max_pin="x.x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| calendar versioning              | `{{ pin_subpackage("myrecipe", max_pin=None) }}`    |

while replacing `"myrecipe"` with either `name` if a `name|lower` variable is defined in your recipe or with the lowercase name of the package in quotes.

### Bot commands for PR management

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

Note that the <code>@BiocondaBot please merge</code> command is now depreciated. Please just squash and merge instead.

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by subwaystation** [comment]
I am trying to look at the error, but Azure always claims `build not found`. Could you please post the error?

**Comment by subwaystation** [comment]
I suspect you may have to increase or reset the `build number` in `meta.yaml`. @danydoerr

**Comment by danydoerr** [comment]
That's exactly what I try to avoid

**Comment by subwaystation** [comment]
Not sure you can, but @AndreaGuarracino knows more I would guess.

**Comment by AndreaGuarracino** [comment]
What's the error? I can't re-trigger the checks.

**Comment by danydoerr** [comment]
@AndreaGuarracino the bioconda pipeline does not like the version naming "0.1.5b". In the meantime, I have changed it to "1.5.1.1" in the [meta.yaml](https://github.com/bioconda/bioconda-recipes/blob/11337cca4dda384726bb3a2b3fb9a3d05ade0499/recipes/gfaffix/meta.yaml) file, but it keeps complaining. I think it has something to do with the "pin_subpackage" call, but it could also be something else.

**Comment by danydoerr** [comment]
@AndreaGuarracino I've now triggered another round of checks....

**Comment by danydoerr** [comment]
I have no idea what happened. I remember the error that I got last week was different. 

> 14:13:35 GIT DEBUG Popen(['git', 'remote', 'get-url', '--all', 'origin'], cwd=/home/runner/work/bioconda-recipes/bioconda-recipes, universal_newlines=False, shell=None, istream=None)
14:13:35 BIOCONDA ERROR Dropping into debugger
Traceback (most recent call last):
  File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/bioconda_utils/cli.py", line 78, in wrapper
    func(*args, **kwargs)
  File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/bioconda_utils/cli.py", line 350, in do_lint
    recipes = get_recipes(config, recipe_folder, packages, git_range, include_blacklisted=True)
  File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/bioconda_utils/cli.py", line 175, in get_recipes
    changed_recipes = get_recipes_to_build(git_range, recipe_folder)
  File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/bioconda_utils/cli.py", line 158, in get_recipes_to_build
    repo = BiocondaRepo(recipe_folder)
  File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/bioconda_utils/githandler.py", line 505, in __init__
    super().__init__(repo, dry_run, home, fork, allow_dirty)
  File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/bioconda_utils/githandler.py", line 83, in __init__
    self.home_remote = self.get_remote(home)
  File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/bioconda_utils/githandler.py", line 143, in get_remote
    raise KeyError(f"No remote matching '{desc}' found")
KeyError: "No remote matching 'bioconda/bioconda-recipes' found"
Traceback (most recent call last):
  File "/opt/mambaforge/envs/bioconda/bin/bioconda-utils", line 8, in <module>
    sys.exit(main())
  File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/bioconda_utils/cli.py", line 1111, in main
    argh.dispatch_commands([
  File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/argh/dispatching.py", line 328, in dispatch_commands
    dispatch(parser, *args, **kwargs)
  File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/argh/dispatching.py", line 260, in _call
    result = function(*positional, **keywords)
  File "<boltons.funcutils.FunctionBuilder-3>", line 2, in do_lint
  File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/bioconda_utils/cli.py", line 137, in wrapper
    func(*args, **kwargs)
  File "<boltons.funcutils.FunctionBuilder-2>", line 2, in do_lint
  File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/bioconda_utils/cli.py", line 66, in wrapper
    func(*args, **kwargs)
  File "<boltons.funcutils.FunctionBuilder-1>", line 2, in do_lint
  File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/bioconda_utils/cli.py", line 78, in wrapper
    func(*args, **kwargs)
  File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/bioconda_utils/cli.py", line 350, in do_lint
    recipes = get_recipes(config, recipe_folder, packages, git_range, include_blacklisted=True)
  File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/bioconda_utils/cli.py", line 175, in get_recipes
    changed_recipes = get_recipes_to_build(git_range, recipe_folder)
  File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/bioconda_utils/cli.py", line 158, in get_recipes_to_build
    repo = BiocondaRepo(recipe_folder)
  File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/bioconda_utils/githandler.py", line 505, in __init__
    super().__init__(repo, dry_run, home, fork, allow_dirty)
  File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/bioconda_utils/githandler.py", line 83, in __init__
    self.home_remote = self.get_remote(home)
  File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/bioconda_utils/githandler.py", line 143, in get_remote
    raise KeyError(f"No remote matching '{desc}' found")
KeyError: "No remote matching 'bioconda/bioconda-recipes' found"
Error: Process completed with exit code [1](https://github.com/danydoerr/bioconda-recipes/actions/runs/6694018842/job/18186414441#step:16:1).

**Comment by danydoerr** [comment]
@AndreaGuarracino here's the error message

> Attempting to finalize metadata for gfaffix
14:19:35 CONDA_BUILD INFO Attempting to finalize metadata for gfaffix
Traceback (most recent call last):
  File "/opt/mambaforge/envs/bioconda/bin/bioconda-utils", line 8, in <module>
    sys.exit(main())
  File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/bioconda_utils/cli.py", line 1111, in main
    argh.dispatch_commands([
  File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/argh/dispatching.py", line 328, in dispatch_commands
    dispatch(parser, *args, **kwargs)
  File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/argh/dispatching.py", line 260, in _call
    result = function(*positional, **keywords)
  File "<boltons.funcutils.FunctionBuilder-5>", line 2, in build
  File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/bioconda_utils/cli.py", line 137, in wrapper
    func(*args, **kwargs)
  File "<boltons.funcutils.FunctionBuilder-4>", line 2, in build
  File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/bioconda_utils/cli.py", line 66, in wrapper
    func(*args, **kwargs)
  File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/bioconda_utils/cli.py", line 490, in build
    success = build_recipes(recipe_folder, config, recipes,
  File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/bioconda_utils/build.py", line 394, in build_recipes
    pkg_paths = utils.get_package_paths(recipe, check_channels, force=force)
  File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/bioconda_utils/utils.py", line 1126, in get_package_paths
    platform, metas = _load_platform_metas(recipe, finalize=True)
  File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/bioconda_utils/utils.py", line 1026, in _load_platform_metas
    return platform, load_all_meta(recipe, config=config, finalize=finalize)
  File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/bioconda_utils/utils.py", line 460, in load_all_meta
    metas = [
  File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/bioconda_utils/utils.py", line 463, in <listcomp>
    for (meta, _, _) in api.render(
  File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/conda_build/api.py", line 45, in render
    for od, om in meta.get_output_metadata_set(
  File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/conda_build/metadata.py", line 2524, in get_output_metadata_set
    conda_packages = finalize_outputs_pass(
  File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/conda_build/metadata.py", line 879, in finalize_outputs_pass
    parent_metadata.parse_until_resolved()
  File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/conda_build/metadata.py", line 1270, in parse_until_resolved
    self.parse_again(
  File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/conda_build/metadata.py", line 1167, in parse_again
    self._get_contents(
  File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/conda_build/metadata.py", line 1872, in _get_contents
    rendered = template.render(environment=env)
  File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/vsts/work/1/s/recipes/gfaffix/meta.yaml", line 17, in top-level template code
    run_exports:
  File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/conda_build/jinja_context.py", line 335, in pin_subpackage
    raise ValueError("Didn't find subpackage version info for '{}', which is used in a"
ValueError: Didn't find subpackage version info for 'GFAffix', which is used in a pin_subpackage expression.  Is it actually a subpackage?  If not, you want pin_compatible instead.
##[error]Bash exited with code '1'.
Finishing: Test

**Comment by AndreaGuarracino** [comment]
I've never seen such an error. What I would do is try the dumb route of releasing version 0.1.6 (if you like an easy life), to be sure it is something related or not to the 4-value version you've specified

**Comment by danydoerr** [comment]
I know that this would be a fix. But that would cause version inconsistencies, and that's what I am trying to avoid.

**Comment by danydoerr** [comment]
Apparently, Versions must be numeric only, so I can't do 0.1.5b.

**Comment by AndreaGuarracino** [comment]
Sure, version mix leads to a hard life. What I meant was to make a new GitHub release 0.1.6 (or something without letters in it) and then a new Bioconda release with such a new version.

**Comment by danydoerr** [comment]
@BiocondaBot please add label

**Comment by AndreaGuarracino** [comment]
@BiocondaBot please merge

**Review by AndreaGuarracino — APPROVED** [review]

**Comment by danydoerr** [comment]
Thanks, @AndreaGuarracino

**Pull request merged**
