### PR TITLE
Add back a separate pyopenms package (v2.8)

### PR DESCRIPTION
**Pull request by jpfeuffer**
Previously was inside the openms-meta recipe. Now it can be cleanly separated given exactly the same version of libopenms is available on bioconda.

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by jpfeuffer** [comment]
@timosachsenberg as discussed

**Comment by jpfeuffer** [comment]
TODO we should probably remove the conda_build_config to build all supported python versions. Or limit to all py3 versions, in case bioconda still supports py2.

**Review by timosachsenberg — APPROVED** [review]

**Review by timosachsenberg — APPROVED** [review]

**Review by timosachsenberg — APPROVED** [review]

**Review by timosachsenberg — APPROVED** [review]
looks good

**Review by timosachsenberg — APPROVED** [review]

**Comment by timosachsenberg** [comment]
@BiocondaBot please add label

**Comment by dpryan79** [comment]
@BiocondaBot please fetch artifacts

**Comment by dpryan79** [comment]
...and there's a github actions outage, so this might have to wait an hour until they get that fixed.

**Comment by timosachsenberg** [comment]
pinging @dpryan79

**Comment by jpfeuffer** [comment]
@BiocondaBot please fetch artifacts

**Comment by jpfeuffer** [comment]
Ah stop.

**Comment by jpfeuffer** [comment]
We have to remove the Conda config to build all/more python versions.

**Comment by jpfeuffer** [comment]
@dpryan79 what is the best way to build for all py3 versions supported by bioconda?

**Comment by jpfeuffer** [comment]
And how many are there? 'cause or build time.

**Comment by dpryan79** [comment]
There are 4 python 3s. Let's just give it a go and see what happens. At least we're using mambabuild now, the env resolution should be quicker.

**Review by dpryan79 — APPROVED** [review]

**Comment by jpfeuffer** [comment]
Interesting, suddenly the symbols are hidden on macos. Not sure what changed but we need another patch now, that enables visibility in the pyopenms CMakelists, also for macos.

**Comment by timosachsenberg** [comment]
@BiocondaBot please fetch artifacts

**Comment by dpryan79** [comment]
@timosachsenberg Looks good, you want to tell the bot to merge this or does it need more work?

**Pull request merged**
