### PR TITLE
omero 5.5.0: bump version and build number

### PR DESCRIPTION
**Pull request by jburel**
* This PR updates an existing recipe.

### CODE REVIEW

**Comment by bgruening** [comment]
We should move omera over to conda-forge I think.

**Comment by joshmoore** [comment]
@bgruening : in general, :+1: for that but the zeroc-ice dependency will be an issue there as it is here, no? https://github.com/bioconda/bioconda-recipes/pull/13588

**Comment by joshmoore** [comment]
The process has begun to migrate all the repos to an `ome` channel: https://anaconda.org/ome

If anyone is particularly interested in a move to conda-forge, please get in touch.

**Comment by bgruening** [comment]
Yes, for complexity reasons we are interested in keeping the number of channels as low as possible and would be interested to put omero into conda-forge.

**Comment by joshmoore** [comment]
:+1: @bgruening. Do you have any suggestion on next steps? (e.g. shall we open a PR for removing this recipe?)

**Comment by manics** [comment]
@bgruening I looked at using https://github.com/conda-forge/conda-smithy a few months ago to setup multi-platform builds, but ran into problems with CI services not being connected. Is this what you'd recommend for creating a conda-forge compatible recipe before opening a PR? A Windows build of zeroc-ice 3.6 is where most of the effort will go, omero-py is pure Python.

**Comment by bgruening** [comment]
@joshmoore I think removing the recipe is fine as soon as there is a conda-forge recipe.

@manics conda-smithy is only a utility to render feedstocks and such, you are not forced to use it.
It is totally fine to create your PR and test your package as you go on staged-recipes.
For more information please see https://conda-forge.org/#add_recipe

Thanks a lot for looking at it!

**Comment by manics** [comment]
I've opened a PR for zeroc-ice36-python: https://github.com/conda-forge/staged-recipes/pull/10324
Windows turned out to be fine, OS X is proving to be a problem.

**Pull request closed without merging**
