### PR TITLE
Update motus to 3.0.0

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`motus`](https://bioconda.github.io/recipes/motus/README.html): **2.6.1** &rarr; **3.0.0**

[install with bioconda](http://bioconda.github.io/recipes/motus/README.html) [Conda](https://anaconda.org/bioconda/motus/files)

Info | Link
-----|-----
Recipe | [`recipes/motus`](https://github.com//bioconda/bioconda-recipes/tree/bump/motus/recipes/motus) (click to view/edit other files)
Releases |[https://github.com/motu-tool/mOTUs/tags](https://github.com/motu-tool/mOTUs/tags)
Recipe Maintainer(s) | @AlessioMilanese
Author | `@motu-tool`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by AlessioMilanese** [comment]
The "Copying packages" step timed out.
Info:
```
#!/bin/bash -eo pipefail
(
# Run in subshell just to be safe. Don't want workflows to fail because of this.
mkdir -p /tmp/artifacts/packages
cd miniconda/conda-bld || exit 0
find -name .cache | xargs rm -rf || true
for n in rss.xml index.html channeldata.json linux-64 osx-64 noarch broken; do
  cp -rv $n /tmp/artifacts/packages || true
done
if command -V docker >/dev/null; then
  mkdir -p /tmp/artifacts/images
  cd /tmp/artifacts/images
  docker image ls --format='{{.Repository}}:{{.Tag}}' | \
    { grep biocontainers || true ; } | \
    xargs -n1 -P4 bash -c '
      test -n "${1+x}" || exit 0
      echo "Start compressing docker image ${1} ..."
      docker save "${1}" | gzip -c > "${1##*/}.tar.gz"
      echo "Finished compressing docker image ${1} ."
      ' --
fi
) || true
```

Message:
```
cp: cannot stat ‘rss.xml’: No such file or directory
‘index.html’ -> ‘/tmp/artifacts/packages/index.html’
‘channeldata.json’ -> ‘/tmp/artifacts/packages/channeldata.json’
‘linux-64’ -> ‘/tmp/artifacts/packages/linux-64’
‘linux-64/current_repodata.json’ -> ‘/tmp/artifacts/packages/linux-64/current_repodata.json’
‘linux-64/repodata.json’ -> ‘/tmp/artifacts/packages/linux-64/repodata.json’
‘linux-64/index.html’ -> ‘/tmp/artifacts/packages/linux-64/index.html’
‘linux-64/repodata.json.bz2’ -> ‘/tmp/artifacts/packages/linux-64/repodata.json.bz2’
‘linux-64/current_repodata.json.bz2’ -> ‘/tmp/artifacts/packages/linux-64/current_repodata.json.bz2’
‘linux-64/repodata_from_packages.json’ -> ‘/tmp/artifacts/packages/linux-64/repodata_from_packages.json’
‘linux-64/repodata_from_packages.json.bz2’ -> ‘/tmp/artifacts/packages/linux-64/repodata_from_packages.json.bz2’
‘osx-64’ -> ‘/tmp/artifacts/packages/osx-64’
‘osx-64/current_repodata.json’ -> ‘/tmp/artifacts/packages/osx-64/current_repodata.json’
‘osx-64/repodata.json’ -> ‘/tmp/artifacts/packages/osx-64/repodata.json’
‘osx-64/index.html’ -> ‘/tmp/artifacts/packages/osx-64/index.html’
‘osx-64/repodata.json.bz2’ -> ‘/tmp/artifacts/packages/osx-64/repodata.json.bz2’
‘osx-64/current_repodata.json.bz2’ -> ‘/tmp/artifacts/packages/osx-64/current_repodata.json.bz2’
‘osx-64/repodata_from_packages.json’ -> ‘/tmp/artifacts/packages/osx-64/repodata_from_packages.json’
‘osx-64/repodata_from_packages.json.bz2’ -> ‘/tmp/artifacts/packages/osx-64/repodata_from_packages.json.bz2’
‘noarch’ -> ‘/tmp/artifacts/packages/noarch’
‘noarch/current_repodata.json’ -> ‘/tmp/artifacts/packages/noarch/current_repodata.json’
‘noarch/motus-3.0.0-pyhdfd78af_0.tar.bz2’ -> ‘/tmp/artifacts/packages/noarch/motus-3.0.0-pyhdfd78af_0.tar.bz2’
‘noarch/repodata.json’ -> ‘/tmp/artifacts/packages/noarch/repodata.json’
‘noarch/index.html’ -> ‘/tmp/artifacts/packages/noarch/index.html’
‘noarch/repodata.json.bz2’ -> ‘/tmp/artifacts/packages/noarch/repodata.json.bz2’
‘noarch/current_repodata.json.bz2’ -> ‘/tmp/artifacts/packages/noarch/current_repodata.json.bz2’
‘noarch/repodata_from_packages.json’ -> ‘/tmp/artifacts/packages/noarch/repodata_from_packages.json’
‘noarch/repodata_from_packages.json.bz2’ -> ‘/tmp/artifacts/packages/noarch/repodata_from_packages.json.bz2’
cp: cannot stat ‘broken’: No such file or directory
Start compressing docker image quay.io/biocontainers/motus:3.0.0--pyhdfd78af_0 ...

Too long with no output (exceeded 20m0s): context deadline exceeded
```

**Comment by AlessioMilanese** [comment]
@hjruscheweyh

**Comment by fanninpm** [comment]
@BiocondaBot please update

**Comment by AlessioMilanese** [comment]
During "Building and testing", executing:
```
#!/bin/bash -eo pipefail
docker pull quay.io/dpryan79/mulled_container:latest
bioconda-utils build recipes config.yml \
  --docker --mulled-test \
  --git-range master HEAD
docker rmi quay.io/dpryan79/mulled_container:latest
```
there was this error:
```
 91%, 3054 MB, 18829 KB/s, 166 seconds passed.
17:35:30 BIOCONDA INFO (OUT) stderr:  ------------------------------------------------------------------------------
17:35:30 BIOCONDA INFO (OUT) |                              SETUP MOTUS TOOL                                |
17:35:30 BIOCONDA INFO (OUT)  ------------------------------------------------------------------------------
17:35:30 BIOCONDA INFO (OUT) Download the compressed motus database (~3.5Gb)
17:35:30 BIOCONDA INFO (OUT) Traceback (most recent call last):
17:35:30 BIOCONDA INFO (OUT)   File "/opt/conda/conda-bld/motus_1624468948898/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/share/motus-3.0.0//setup.py", line 199, in <module>
17:35:30 BIOCONDA INFO (OUT)     status = main()
17:35:30 BIOCONDA INFO (OUT)   File "/opt/conda/conda-bld/motus_1624468948898/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/share/motus-3.0.0//setup.py", line 121, in main
17:35:30 BIOCONDA INFO (OUT)     save_f(link_db, db_name)
17:35:30 BIOCONDA INFO (OUT)   File "/opt/conda/conda-bld/motus_1624468948898/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/share/motus-3.0.0//setup.py", line 61, in save_f
17:35:30 BIOCONDA INFO (OUT)     urllib.request.urlretrieve(url, filename, reporthook)
17:35:30 BIOCONDA INFO (OUT)   File "/opt/conda/conda-bld/motus_1624468948898/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib/python3.9/urllib/request.py", line 278, in urlretrieve
17:35:30 BIOCONDA INFO (OUT)     raise ContentTooShortError(
17:35:30 BIOCONDA INFO (OUT) urllib.error.ContentTooShortError: <urlopen error retrieval incomplete: got only 3202603047 out of 3505139004 bytes>
17:35:30 BIOCONDA INFO (OUT) 
17:35:30 BIOCONDA INFO (OUT) return code: 1
17:35:30 BIOCONDA INFO (OUT) 
17:35:30 BIOCONDA INFO (OUT) kwargs:
17:35:30 BIOCONDA INFO (OUT) {}
17:35:30 BIOCONDA INFO (OUT) 
17:35:30 BIOCONDA INFO (OUT) : <exception str() failed>
17:35:30 BIOCONDA INFO (OUT) 
17:35:30 BIOCONDA INFO (OUT) During handling of the above exception, another exception occurred:
17:35:30 BIOCONDA INFO (OUT) 
17:35:30 BIOCONDA INFO (OUT) Traceback (most recent call last):
17:35:30 BIOCONDA INFO (OUT)   File "/opt/conda/bin/conda-build", line 11, in <module>
17:35:30 BIOCONDA INFO (OUT)     sys.exit(main())
17:35:30 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 481, in main
17:35:30 BIOCONDA INFO (OUT)     execute(sys.argv[1:])
17:35:30 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 472, in execute
17:35:30 BIOCONDA INFO (OUT)     verify=args.verify, variants=args.variants, cache_dir=args.cache_dir)
17:35:30 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.7/site-packages/conda_build/api.py", line 195, in build
17:35:30 BIOCONDA INFO (OUT)     variants=variants
17:35:30 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.7/site-packages/conda_build/build.py", line 3079, in build_tree
17:35:30 BIOCONDA INFO (OUT)     test(pkg, config=metadata.config.copy(), stats=stats)
17:35:30 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.7/site-packages/conda_build/build.py", line 2871, in test
17:35:30 BIOCONDA INFO (OUT)     is_conda=metadata.name() == 'conda')
17:35:30 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.7/site-packages/conda_build/environ.py", line 916, in create_env
17:35:30 BIOCONDA INFO (OUT)     if (("too short in" in str(exc) or
17:35:30 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.7/site-packages/conda/__init__.py", line 148, in __str__
17:35:30 BIOCONDA INFO (OUT)     return str('\n').join(str(e) for e in self.errors) + str('\n')
17:35:30 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.7/site-packages/conda/__init__.py", line 148, in <genexpr>
17:35:30 BIOCONDA INFO (OUT)     return str('\n').join(str(e) for e in self.errors) + str('\n')
17:35:30 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.7/site-packages/conda/__init__.py", line 84, in __str__
17:35:30 BIOCONDA INFO (OUT)     return text_type(self.message % self._kwargs)
17:35:30 BIOCONDA INFO (OUT) ValueError: unsupported format character ',' (0x2c) at index 521
17:35:30 BIOCONDA ERROR COMMAND FAILED (exited with 1): docker run -t --net host --rm -v /tmp/tmp5t0v2l8o/build_script.bash:/opt/build_script.bash -v /home/circleci/project/miniconda/conda-bld/:/opt/host-conda-bld -v /home/circleci/project/recipes/motus:/opt/recipe -e LANG=en_US.UTF-8 -e HOST_USER_ID=1001 quay.io/bioconda/bioconda-utils-build-env-cos7:0.17.8 /bin/bash /opt/build_script.bash

17:35:30 BIOCONDA ERROR BUILD FAILED recipes/motus
17:35:30 BIOCONDA INFO (COMMAND) conda build purge
17:35:35 BIOCONDA ERROR BUILD SUMMARY: of 1 recipes, 1 failed and 0 were skipped. Details of recipes and environments follow.
17:35:35 BIOCONDA ERROR BUILD SUMMARY: FAILED recipe recipes/motus

Exited with code exit status 1

CircleCI received exit code 1
```

Try to re-run now.

**Pull request closed without merging**
