### PR TITLE
Snoscan a new recipe

### PR DESCRIPTION
**Pull request by mictadlo**
* [x] I have read the guidelines above.
* [x] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by mictadlo** [comment]
@jerowe by any chance, do you know what could cause that the [command is not found](https://travis-ci.org/bioconda/bioconda-recipes/jobs/195758609#L801)

**Comment by mictadlo** [comment]
Why MacOS finished successfully, but Linux failed?

**Comment by tomkinsc** [comment]
What is the return code of `sort-snos`? It may be failing [here](https://github.com/bioconda/bioconda-recipes/pull/3608/files#diff-7c39fcc618335d074a1ef7e1319de7a2R37) for the same reason as [this PR](https://github.com/bioconda/bioconda-recipes/pull/3416) (i.e. `set -o pipefail` may be to blame; with pipefail, the script may exit before grep can run if `sort-snos` returns a non-zero exit code.)

**Comment by mictadlo** [comment]
@tomkinsc thank you.

**Comment by mictadlo** [comment]
@bgruening merging?

**Comment by bgruening** [comment]
Sure! Looks good to me! Can you try to get your changes upstream?

**Comment by mictadlo** [comment]
How to I get them upstream?

**Comment by bgruening** [comment]
Contacting the main author or searching for the main git repo and creating a PR.

**Pull request merged**
