### PR TITLE
Update kb-python to 0.26.0

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`kb-python`](https://bioconda.github.io/recipes/kb-python/README.html): **0.25.1** &rarr; **0.26.0**

[install with bioconda](http://bioconda.github.io/recipes/kb-python/README.html) [Conda](https://anaconda.org/bioconda/kb-python/files)

Info | Link
-----|-----
Recipe | [`recipes/kb-python`](https://github.com//bioconda/bioconda-recipes/tree/bump/kb_python/recipes/kb-python) (click to view/edit other files)
Releases |[https://github.com/pachterlab/kb_python/tags](https://github.com/pachterlab/kb_python/tags)
Recipe Maintainer(s) | @Maarten-vd-Sande
Author | `@pachterlab`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by Maarten-vd-Sande** [comment]
@dpryan79 @apeltzer how do we continue on this? A makefile.patch to use the conda one in the path? Then it will be independent of the one thats shipped with it.

**Comment by dpryan79** [comment]
@Maarten-vd-Sande Yeah, I think the following lines would need to be patched: https://github.com/pachterlab/kb_python/blob/master/kb_python/config.py#L49-L50

Those could be changed to:

```
KALLISTO_PATH = 'kallisto'
BUSTOOLS_PATH = 'bustools'
```

**Comment by Maarten-vd-Sande** [comment]
Ok great! Thanks for already doing the heavy work here :smile: 

I'll add the patch somewhere today

**Comment by apeltzer** [comment]
Thanks @Maarten-vd-Sande & @dpryan79

**Comment by dpryan79** [comment]
The heavy work is testing that this actually works :)

**Comment by dpryan79** [comment]
@bioconda-bot please fetch artifacts

Anyone want to test that?

**Comment by Maarten-vd-Sande** [comment]
Yes I was/am working on it! 

I did not know that building/testing could be done so easily with the help of biocondabot!

**Comment by apeltzer** [comment]
@FloWuenne - you want to give this a try too?

**Comment by apeltzer** [comment]
@Maarten-vd-Sande and I were having the same thought in the very same minute 🥇

**Comment by Maarten-vd-Sande** [comment]
Yeah I saw your comment, and realized I did not add those yet. So I thought I quickly push it before someone starts testing and wasting their time :smile:

**Comment by FloWuenne** [comment]
Thanks for the quick update! My main issue with the previous version happened when running via a singularity container. How can I pull/build a singularity for this specific test build?

**Comment by apeltzer** [comment]
You'd need to have docker installed locally to import the container build above using this command:

`curl -L "https://150194-42372094-gh.circle-artifacts.com/0/tmp/artifacts/images/kb-python%3A0.26.0--pyhdfd78af_0.tar.gz" | gzip -dc | docker load` 

One could try this approach here to build a local singularity image once:

`singularity build lolcow_tar.sif docker-archive://lolcow.tar`

and use the URL from above to download first and then do the same, e.g.

```
curl -L "https://150194-42372094-gh.circle-artifacts.com/0/tmp/artifacts/images/kb-python%3A0.26.0--pyhdfd78af_0.tar.gz"
singularity build kb-python-test-singularity.sif docker-archive://kb-python0.26.0--pyhdfd78af_0.tar.gz
```

(or similar, didn't try this myself now)

**Comment by apeltzer** [comment]
Found out about the docker-archive stuff here - https://sylabs.io/guides/3.1/user-guide/singularity_and_docker.html#locally-available-images-stored-archives 

Didn't know this is even existing, wasn't back in the old days ™️

**Comment by FloWuenne** [comment]
Thanks, @apeltzer! I had tried the docker-archive way of building the container before but it seems that you really need a newer version of singularity to do this. After updating to singularity version 3.7.3, building a sif image from the local docker container worked! 

```
sudo docker save 699b7a88c131 -o kb_python_0.26.tar
sudo singularity build kb_python_0.26.sif docker-archive://kb_python_0.26.tar
```
 
 From within the Docker container, kb shows the correct updated version:
 
```
docker run -it 699b7a88c131 kb --help
usage: kb [-h] [--list] <CMD> ...

kb_python 0.26.0
```

but from withing the singularity container, this returns my current local version. Adding the --no-home flag fixes this!

```
singularity exec kb_python_0.26.sif kb
usage: kb [-h] [--list] <CMD> ...

kb_python 0.25.1

singularity exec --no-home kb_python_0.26.sif kb
usage: kb [-h] [--list] <CMD> ...

kb_python 0.26.0
```

**Comment by Maarten-vd-Sande** [comment]
@bioconda-bot please fetch artifacts

I don't work with containers, and I am definitely not sure how bioconda works with artifacts internally. When using that link, is it updated for our pushes @apeltzer? I re-fetch artifacts so I can check if the url changes

**Comment by Maarten-vd-Sande** [comment]
The sha256 sum changed between the urls, perhaps @FloWuenne tried the "old" version in the end anyways, because we didnt update the "artifacts"?

**Comment by apeltzer** [comment]
I'm a bit confused here too whether this really updated in the way as mentioned above - can you try once with the link that Maarten fetched once more @FloWuenne ? 

I think this is all correct, so we can merge & try afterwards though ... - worst case, we can still increase the build number by 1 and adjust if things are not working nicely.

**Comment by Maarten-vd-Sande** [comment]
I still have to try the normal conda thing, yada yada yada I was busy. I hope to get it done today :)

**Review by Maarten-vd-Sande — APPROVED** [review]
It seems to work with the normal installation for making an index. It finds the `kallisto` binary, green light from me :) I'm assuming it works for `bustools` as well then (I can easily test this, I will see if I can find some data)

**Comment by apeltzer** [comment]
I guess its fine then and works as intended - can simply bump this / fix it with a new build if it doesn't which I doubt is neccessary ;-)

**Comment by Maarten-vd-Sande** [comment]
@bioconda-bot please merge

Bustools is also detected for me, and indeed, we can always bump it (although it's nice if it works in one go)

**Comment by FloWuenne** [comment]
I tested with the new artifacts link and still have the singularity container use my local binaries from my HOME folder. I guess I will test again once the [kb-python biocontainer](https://biocontainers.pro/tools/kb-python) has been updated and see whether this persists with the biocontainer that we use in nf-core?!

```
curl -L "https://150255-42372094-gh.circle-artifacts.com/0/tmp/artifacts/images/kb-python%3A0.26.0--pyhdfd78af_0.tar.gz" | gzip -dc | docker load

docker run -it d6fdc3da5d9b kb --help
kb_python 0.26.0

sudo docker save d6fdc3da5d9b -o kb_python_0.26.tar

sudo singularity build kb_python_0.26.sif docker-archive://kb_python_0.26.tar

singularity exec kb_python_0.26.sif kb
kb_python 0.25.1

singularity exec --no-home kb_python_0.26.sif kb
kb_python 0.26.0
```

**Pull request merged**
