### PR TITLE
index noarch

### PR DESCRIPTION
**Pull request by daler**
* [ ] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [x] This PR does something else (explain below).

try fixing #4976; this also incorporates #4975 to test the fix

cc @zachcp

### CODE REVIEW

**Comment by zachcp** [comment]
thank you @daler !

I still dont know my way around some of the new checks!

**Comment by daler** [comment]
@johanneskoester @bgruening, have we successfully built a noarch package with our current conda & conda-build versions? I don't see any recipes in master with `noarch` set.

**Comment by bgruening** [comment]
@daler I don't think so. This is pretty new.

**Comment by zachcp** [comment]
@daler is this good to go? I notice some earlier commits in this branch.

**Comment by daler** [comment]
@zachcp sorry this was just for a quick test -- but it looks like a problem with building noarch packages. Back in your PR you can remove the `noarch` section and add a commit message that includes the string `[lint skip should_be_noarch for recipes/schema]`. 

In the meantime I will temporarily disable the linting for `noarch` until we figure out what's going on.

**Pull request closed without merging**
