### PR TITLE
Update nextstrain/auspice to 2.38.0

### PR DESCRIPTION
**Pull request by jameshadfield**
GitHub release notes: https://github.com/nextstrain/auspice/releases/tag/v2.38.0

Describe your pull request here

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Review by corneliusroemer — APPROVED** [review]

**Comment by corneliusroemer** [comment]
@BiocondaBot please merge

**Comment by corneliusroemer** [comment]
@BiocondaBot please merge

**Comment by corneliusroemer** [comment]
@BiocondaBot please fetch artifacts

**Comment by corneliusroemer** [comment]
@rpetit3 @dpryan79 any idea what's going on here?

**Comment by corneliusroemer** [comment]
@BiocondaBot please update

**Comment by corneliusroemer** [comment]
@BiocondaBot please fetch artifacts

**Comment by corneliusroemer** [comment]
@BiocondaBot please merge

**Comment by dpryan79** [comment]
Looks like it got blacklisted during the last migration. I've removed it so we can debug that here. nextstrain itself also appears to be in there, so we'll want to get that removed quickly too (different PR though).

**Comment by dpryan79** [comment]
There are thousands of packages, so no changelog other than with git. The last migration was for python 3.10.

**Comment by corneliusroemer** [comment]
I didn't mean put blacklist in changelog, but infra changes, and big
changes like adding subchannels.

Git is too much with the many packages. A brief note when major things
change, once a week or month would be great.

Did Auspice get blacklisted during the Python 3.10 migration - what did
that migration entail? Simply adding Python 3.10? Would it then be enough
to pin python to <3.10 for now? Or do I misunderstand?

**Comment by dpryan79** [comment]
Most likely there were other pinning changes that came along with python 3.10, I unfortunately don't have the full list (we share those with conda-forge, which is doing almost daily updates to their pinnings...so I don't think they even bother keeping track).

**Comment by corneliusroemer** [comment]
I see, sounds complicated - so the best would maybe be to ping maintainers
if their package gets blacklisted.

It was quite confusing to get the build to succeed but merge to fail.

Is it possible to fail the build instead to be more transparent to
maintainers?

**Comment by dpryan79** [comment]
Yeah, I think there's an issue open on bioconda-utils to have the linting step fail in such cases. It'd be much nicer that way.

**Comment by dpryan79** [comment]
Ah https://github.com/nodejs/node-gyp/issues/2713

**Comment by dpryan79** [comment]
Looks like we can put in a `for f in $PREFIX/lib/auspice/node_modules/watchpack-chokidar2/node_modules/fsevents/build/node_gyp_bins/python3 ; do unlink $f; done` in the build script since this isn't needed after installation.

**Comment by dpryan79** [comment]
@BiocondaBot please merge

**Comment by corneliusroemer** [comment]
Thanks a lot for debugging!

**Pull request merged**
