### PR TITLE
update to v0.9.1

### PR DESCRIPTION
**Pull request by rob-p**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by rob-p** [comment]
Blocked on #6950 --- tagging it here so I get pinged when it's fixed.

**Comment by rob-p** [comment]
@bioconda/osx any idea what is up with the OSX builds on TravisCI?

**Comment by mbargull** [comment]
Can you merge or rebase on `master`? That way you'll at least get the correct `xcode7.3` OSX image. But I don't know what's going on there -- the latest commit on `master` is already 4 hours in the queue...

**Comment by rob-p** [comment]
@mbargull ,  yup; I just rebased.  Hopefully the build will succeed now.

**Pull request merged**
