### PR TITLE
Add chips v2.3

### PR DESCRIPTION
**Pull request by Pandaman-Ryan**
ChIPs is a tool for simulating ChIP-sequencing experiments.
This source code can be found here: https://github.com/gymreklab/chips

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by Pandaman-Ryan** [comment]
Hi @bioconda/core

I have this bioinformatics tool named ChIPS (https://github.com/gymreklab/chips). I have been trying to incorporate it into bioconda platform. But I bumped into this error and could not solve it:
/opt/conda/conda-bld/chips_1613070499175/work/ChIPs/pulldown.h:16:84: error: 'std::mt19937' has not been declared

I have double-checked the installation process and the Makefile script on my local machine but did not run into this error. If possible, could you please give me some advice on how to correct my build.sh and meta.yaml?

Thanks a lot!

**Comment by Pandaman-Ryan** [comment]
@BiocondaBot please add label help wanted

**Comment by Pandaman-Ryan** [comment]
Hi @bioconda/core

I have this bioinformatics tool named ChIPS (https://github.com/gymreklab/chips). I have been trying to incorporate it into bioconda platform. But I bumped into this error and could not solve it:
/opt/conda/conda-bld/chips_1613070499175/work/ChIPs/pulldown.h:16:84: error: 'std::mt19937' has not been declared

This mt19937 is a class in std introduced in c++11. I have double-checked the installation process and the Makefile script on my local machine but did not run into this error. If possible, could you please help me and give me some advice on how to correct my build.sh and meta.yaml?

Thank you for your help!

**Comment by Pandaman-Ryan** [comment]
Any help would be appreciated!

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@bioconda-bot please merge

@Pandaman-Ryan Guess you figured out whatever the issue was with getting the compiler to use C++11.

**Comment by Pandaman-Ryan** [comment]
Thank you for approving the merge!

**Pull request merged**
