### PR TITLE
Update odgi to 0.5.1

### PR DESCRIPTION
**Pull request by AndreaGuarracino**
Update odgi to 0.5.1

The last release has a [buildable source tarball](https://github.com/vgteam/odgi/releases/download/v0.5.1/odgi-v0.5.1.tar.gz). https://github.com/vgteam/odgi/issues/109 https://github.com/vgteam/odgi/issues/112

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by subwaystation** [comment]
`14:11:57 BIOCONDA INFO (OUT) OSError: [Errno 12] Cannot allocate memory`

@dpryan79 @apeltzer Seems like the CI went out of memory? 
I was not able to find out how many threads it uses for the builds, but I would recommend scaling down to 1. 
Any help appreciated :)

**Comment by dpryan79** [comment]
I would have presumed it would be using 1 thread by default, since there's nothing specified in that regard in the build script.

**Comment by subwaystation** [comment]
I see.
So what options do we have to get this to run?

**Comment by subwaystation** [comment]
If I understand correctly, we have to adjust the `.circleci/config.yml` by adding a [RAM disk](https://circleci.com/docs/2.0/executor-types/#ram-disks).
Or we give the CI more resources https://circleci.com/docs/2.0/executor-types/#available-docker-resource-classes https://circleci.com/docs/2.0/executor-types/#using-machine.
@dpryan79 Do you have an idea where exactly in the `config.yml` we would have to add this? Or somewhere else?

**Comment by subwaystation** [comment]
Same error again @AndreaGuarracino

**Comment by subwaystation** [comment]
@apeltzer @dpryan79 How can we find out which `gcc` version is used to build `odgi`?
`gcc --version` in the script leads to `13:35:18 BIOCONDA INFO (OUT) /opt/conda/conda-bld/odgi_1611149437808/work/conda_build.sh: line 17: gcc: command not found`

**Comment by dpryan79** [comment]
There's no program called gcc, it's `$CC` for C and `$CXX` for the C++ compiler. On linux this is gcc 7.something (or maybe 8.something, I forget).

**Comment by subwaystation** [comment]
We have GCC 7.5.0.
image
I checked https://conda.io/projects/conda-build/en/latest/resources/compiler-tools.html, but I don't understand how to force GCC 10.
Any ideas?

**Comment by dpryan79** [comment]
You can't (easily) force a different GCC version, since we need to ensure packages are compatible with each other.

**Comment by subwaystation** [comment]
That's not optimal for us....

The only way we will be able to bring https://github.com/vgteam/odgi, https://github.com/pangenome/smoothxg, and therefore https://github.com/pangenome/pggb to Bioconda is to have GCC 10. These tools won't even compile without GCC 10.

So what would we have to do to go the dirty way and what issues might that bring in detail?

**Comment by dpryan79** [comment]
If you absolutely need a newer GCC then you'd have to add your own conda_build_config.yaml into the recipe directory to override the default versions of the compilers. If these are pure C projects that shouldn't have any downstream issues, but if it's C++ it may be that the resulting packages can't be in the same environment with anything else.

**Comment by subwaystation** [comment]
Got it, thanks.
As we want to install all kinds of packages using the same conda environment, I would not be surprised if conflicts would arise.
We decided to go directly for a Biocontainer.

Thanks for all your feedback :)

**Comment by subwaystation** [comment]
Hi @dpryan79 ,
after some intensive discussion, we would like to try the unusual way.
Assuming, we would bring GCC10.2 to conda-forge (most recent version is GCC9.3), then we could build our tool using this specific GCC10.2 version from conda-forge, right?

**Comment by dpryan79** [comment]
@subwaystation Yes, that should be possible then

**Pull request closed without merging**
