### PR TITLE
Me de com recipe

### PR DESCRIPTION
**Pull request by schmic05**
* [ x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ x] This PR adds a new recipe.
* [ x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by schmic05** [comment]
Hey @bioconda/core !
I'd like to add MeDeCom as an R package to bioconda. MeDeCom is not yet on bioconductor and is only available as a GitHub package [(github.com/lutsik/MeDeCom](https://github.com/lutsik/MeDeCom)). When building MeDeCom, the system needs around 6GB of memory, since major preprocessing steps and object are conducted during package building. I noticed that circleci only provides up to 4GB of memory. Therefore, the build fails due to running out of memory. Is there an easy way to work around that? Would appreciate any help here.

**Comment by bgruening** [comment]
@schmic05 wow, why are 6GB needed? We build Qt and stuff like that and it uses less :)
There is no good way to build such a package. The only way I can imagine is that an admin is building it locally and pushes it. But ideally the build procedure should be optimized :(

**Comment by schmic05** [comment]
@bgruening Thanks for the fast reply. MeDeCom builds an index-like structure during the build process to improve running time. We will further work on reducing this, but this won't be easily possible. Just wanted to know, if there is an easy solution. We'll let you know as soon as we found a solution.

**Comment by bgruening** [comment]
@schmic05 I haven't looked at the tool but the index-like structure needs to be rebuild everytime? Why not building it offline and ship it externally?

**Comment by schmic05** [comment]
@bgruening I'm still pretty new to the tool and don't know everything about it, so I'll need some time to figure it out. But I guess you're right, it should be possible to build it only once.

**Comment by daler** [comment]
Closing due to inactivity, please re-open if needed.

**Pull request closed without merging**
