### PR TITLE
Removing wrong download URLs for bioconductor-genomeinfodbdata

### PR DESCRIPTION
**Pull request by visze**
fix in bioconductor-genomeinfodbdata

Two URLs for data download were wrong. Download was a 404 page resulting in a wrong checksum.

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by visze** [comment]
@BiocondaBot please add label

**Comment by visze** [comment]
@BiocondaBot please add label

**Comment by dpryan79** [comment]
Were those causing an error? They're only used if the Bioconductor URL fails (bioconductor deletes packages frequently).

**Comment by visze** [comment]
> 
> 
> Were those causing an error? They're only used if the Bioconductor URL fails (bioconductor deletes packages frequently).

Yes! Because the webserver returns a proper html page. This webpage is then downloaded (containing html with some 404 error) and it used to check the checksum.

**Comment by dpryan79** [comment]
Again, those URLs are only used if the bioconductor URL fails for some reason. What I expect happened is that you ran into a network hiccup causing the original Bioconductor URL to fail. Since the package hasn't been mirrored by the Galaxy folks yet (it hasn't been removed from Bioconductor, so there's no need yet), the script then tried those URLs and failed. That's fine, the root cause is a networking hiccup. Just rerun the process.

**Comment by visze** [comment]
Sorry but this is not the issue. The bioconductor package is available and I can download it! but running the script `post-link.sh ` I get an error too.

**Comment by visze** [comment]
In addition there seems to be an issue with the ssl certifcate

**Comment by visze** [comment]
hang on. maybe it is the ssl thing. because i tested it on two different nodes

**Comment by dpryan79** [comment]
Sorry, but I can't reproduce any of that.

**Comment by dpryan79** [comment]
In addition, the fact that the CI test worked here means that the URLs you removed aren't used.

**Comment by visze** [comment]
thanks @dpryan79 I think is uses a wrong/not existing `cacert.pem` location. I have no idea why. maybe the cluster guys moved the homes... 👎

**Pull request closed without merging**
