### PR TITLE
Update bioconductor-ivas to 2.2.1

### PR DESCRIPTION
**Pull request by epruesse**
Update `bioconductor-ivas`: **2.2.0** &rarr; **2.2.1**

***

[Package Info](https://bioconda.github.io/recipes/bioconductor-ivas/README.html) | [Recipe Folder](https://github.com//bioconda/bioconda-recipes/tree/bump/bioconductor_ivas/recipes/bioconductor-ivas) | [Upstream Home](https://bioconductor.org/packages/3.8/bioc/html/IVAS.html) | [Upstream Releases](https://bioconductor.org/packages/3.8/bioc/html/IVAS.html)

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/updating.html)).

### CODE REVIEW

**Comment by bgruening** [comment]
@epruesse this is dangerous. As those updated potentially do not compile with GCC7. Please let us at first switch the GCC version and then merge those updates.

ping @dpryan79

**Comment by dpryan79** [comment]
Yeah, we should hold off on updating R packages until we switch compilers.

**Comment by epruesse** [comment]
I ran autobump last night not expecting it to go off on all the bioconductor packages - thought they had just been updated?

When do we switch compilers?

**Comment by dpryan79** [comment]
We were hoping that the bot would be ready by the 4th, so we'd switch over then. Bioconductor bumps patch numbers all the time, it's just the major/minor versions that are pegged to a bioconductor-wide release.

**Pull request closed without merging**
