### PR TITLE
DEXSeq - resolve HTSeq/numpy depenency version mismatch

### PR DESCRIPTION
**Pull request by lparsons**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

I've pinned the version of numpy used for HTSeq in https://github.com/bioconda/bioconda-recipes/pull/12467. However, since this requires an older htseq recipe that doesn't have numpy properly pinned, I'm forcing it here. These can be removed when we get various fixes from DEXSeq upstream https://github.com/areyesq89/DEXSeq/pull/1.

### CODE REVIEW

**Comment by lparsons** [comment]
Just wondering if this approach is kosher, or if there is a better way to fix this (fixing old HTSeq version(s)?). Ping @bgruening and @dpryan79 since you guys seem like gurus... :wink:

**Comment by dpryan79** [comment]
I never get the numpy pinning stuff right, so I'll defer to Björn :)

**Comment by lparsons** [comment]
Well @epruesse merged the HTSeq fix in https://github.com/bioconda/bioconda-recipes/pull/12467. However:
1. I don't really have a way to test that it works
2. At best, it applied to the latest HTSeq (0.11), but that won't help for DEXSeq since it requires an older version (<0.10).

**Comment by bgruening** [comment]
@lparsons can we not fix the old htseq-count recipe for 0.9.1 and pin it strictly to htseq-count but not here to numpy.

**Comment by lparsons** [comment]
@bgruening I don't think I follow you. Are you saying we cannot fix the old HTSeq? Can you tell me:

1. Is requiring a specific numpy version *and* specific HTSeq version for DEXSeq the best way to make DEXSeq actually work? Since DEXSeq requires an old HTSeq version, this was the best way found to (hopefully) fix it.

2. Is the way I pinned numpy for HTSeq sufficient to fix the current version of HTSeq

**Comment by bgruening** [comment]
@lparsons I think we should fix the old htseq-count recipe.

>  Is requiring a specific numpy version and specific HTSeq version for DEXSeq the best way to make DEXSeq actually work? Since DEXSeq requires an old HTSeq version, this was the best way found to (hopefully) fix it.

It has a good chance to fix it. But I would prefer to fix htseq-count 0.9.1 instead.

>  Is the way I pinned numpy for HTSeq sufficient to fix the current version of HTSeq

I don't know, probably. We should use `- {{ pin_compatible('numpy') }}` in run dependencies if we can, but this is only working when you have host dependencies as well.

**Comment by lparsons** [comment]
I agree, a d rather fix the old HTSeq recipes, but I'm not clear on how to do that. Create a subdir under HTSeq for the version perhaps? And pick a build number higher than the historic build number used for that version?

--
Lance Parsons - Scientific Programmer
Carl C. Icahn Laboratory - Room 136
Lewis-Sigler Institute for Integrative Genomics
Princeton University




On Tue, Dec 4, 2018 at 3:52 PM -0500, "Björn Grüning" <notifications@github.com<mailto:notifications@github.com>> wrote:


@lparsons<https://github.com/lparsons> I think we should fix the old htseq-count recipe.

Is requiring a specific numpy version and specific HTSeq version for DEXSeq the best way to make DEXSeq actually work? Since DEXSeq requires an old HTSeq version, this was the best way found to (hopefully) fix it.

It has a good chance to fix it. But I would prefer to fix htseq-count 0.9.1 instead.

Is the way I pinned numpy for HTSeq sufficient to fix the current version of HTSeq

I don't know, probably. We should use - {{ pin_compatible('numpy') }} in run dependencies if we can, but this is only working when you have host dependencies as well.

**Comment by lparsons** [comment]
OK, submitted #12490 which should hopefully resolve this. Once tested I'll update/delete this as needed.

**Comment by lparsons** [comment]
I believe that #12490 has eliminated the need for this PR, closing.

**Pull request closed without merging**
