### PR TITLE
new build with conda-forge added to conda_build_config.yaml

### PR DESCRIPTION
**Pull request by sgsokol**
try to add conda-forge to conda_build_config.yaml so that `conda install -c bioconda` work without adding `-c conda-forge`

----

> Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it.

* [ ] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [ ] This PR adds a new recipe.
* [ ] AFAIK, this recipe **is directly relevant to the biological sciences**
      (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

> Everyone has access to the following BiocondaBot commands, which can be given in a comment:
>
>  * `@BiocondaBot please update` will cause the BiocondaBot to merge the master branch into a PR
>  * `@BiocondaBot please add label` will add the `please review & merge` label.
>  * `@BiocondaBot please fetch artifacts` will post links to packages and docker containers built by the CI system. You can use this to test packages locally before merging.
>
> For members of the Bioconda project, the following command is also available:
>
>  * `@BiocondaBot please merge` will cause packages/containers to be uploaded and a PR merged. Someone must approve a PR first! This has the benefit of not wasting CI build time required by manually merging PRs.
>
> If you have questions, please post them in gitter or ping `@bioconda/core` in a comment (if you are not able to directly ping `@bioconda/core` then the bot will repost your comment and enable pinging).

### CODE REVIEW

**Comment by sgsokol** [comment]
@BiocondaBot please add label

**Comment by dpryan79** [comment]
The conda-forge channels is always a dependency of bioconda and users just need to [set up their channels appropriately](https://bioconda.github.io/user/install.html#set-up-channels).

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Comment by sgsokol** [comment]
> The conda-forge channel is always a dependency of bioconda and users just need to [set up their channels appropriately](https://bioconda.github.io/user/install.html#set-up-channels).

"just need" can be not so obvious. I had a user that read in the page https://anaconda.org/bioconda/influx_si : 
To install this package with conda run:
conda install -c bioconda influx_si
He did as written and it failed because he had not conda-forge in his channels.
Do you know how this instruction can be modified to `conda install -c bioconda -c conda-forge influx_si`? Or may be how to indicate somewhere in the recept that dependencies must be looked for in conda-forge?
Thanks.

**Comment by dpryan79** [comment]
Those pages are autogenerated, though you're correct that we should definitely explicitly add `-c conda-forge` on there. I'll make a PR to change that globally in the documentation.

**Comment by dpryan79** [comment]
Hmm, actually we may have to contact anaconda to see if there's a good way of changing that, since they're the ones generating that page.

**Pull request merged**
