### PR TITLE
Update mindthegap recipe to build also for osx

### PR DESCRIPTION
**Pull request by clemaitre**
Update the recipe of mindthegap, so that it builds also for osx system.
MindTheGap requires clang compiler version > 4.5

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title
* New recipes not directly relevant to the biological sciences need to be submitted to [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please add the `please review & merge` label.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>BiocondaBot commands</summary>
      
Everyone has access to the following BiocondaBot commands, which can be given in a comment:

  * `@BiocondaBot please update` will cause the BiocondaBot to merge the master branch into a PR
  * `@BiocondaBot please add label` will add the `please review & merge` label.
  * `@BiocondaBot please fetch artifacts` will post links to packages and docker containers built by the CI system. You can use this to test packages locally before merging.

For members of the Bioconda project, the following command is also available:

 * `@BiocondaBot please merge` will cause packages/containers to be uploaded and a PR merged. Someone must approve a PR first! This has the benefit of not wasting CI build time required by manually merging PRs.
</details>

### CODE REVIEW

**Comment by marcelm** [comment]
Hi, may I point out:
> If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title

:-)

**Comment by clemaitre** [comment]
@marcelm  : thank you for the comment, I thought it had to be the first word of the PR comment.

@bioconda/osx : Is it possible to build a package for osx with clang >4.5. The clang version used here was 4.0.1. I saw on anaconda, that clang was available as a conda package for newer versions (8 or 9) :
https://anaconda.org/conda-forge/clang
Do I have to specify in the meta.yaml file the minimal version of clang ?

Claire

**Comment by abretaud** [comment]
Hi!
I've look at it: it seems like clang is pinned to v4 due to https://github.com/bioconda/bioconda-recipes/blob/master/recipes/bioconda-utils/meta.yaml#L38 = `conda-forge-pinning` in version `2019.09.27`

An update to clang 9 was merged in `conda-forge-pinning` on 2019.09.30 : https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/284

I can make a PR to update `conda-forge-pinning` to the latest version (`2020.03.30` for now), *but* I'm nervous to touch this dependency, it feels like it could break the whole universe

What do you think @bioconda/core ?

**Comment by dpryan79** [comment]
That would require us to rebuild many many packages, we try to update that no more than once or twice a year. I think you can add a custom `conda_build_config.yaml`, though, and just add the newer clang version in there. My understanding is that the different clang versions are compatible, but don't quote me on that.

We'll be updating the global pinnings after the next R release, so you won't have to deal with this issue with clang for terribly much longer.

**Comment by acaprez** [comment]
Right - you can add a per-recipe build config file to use a newer clang version.  Remove the `- clang >=4.5` line from the `meta.yaml` and create a file named `conda_build_config.yaml` with the following contents:

```
cxx_compiler_version:          # [unix]
  - 9                          # [osx]
```

**Comment by abretaud** [comment]
Cool, thanks @dpryan79 @acaprez !
@clemaitre ping me if you need help to make the change

**Comment by abretaud** [comment]
Green!
@BiocondaBot please fetch artifacts

**Comment by abretaud** [comment]
@BiocondaBot please fetch artifacts

**Comment by abretaud** [comment]
@BiocondaBot please merge

**Pull request merged**
