### PR TITLE
easypqp recipe

### PR DESCRIPTION
**Pull request by Leon-Bichmann**
Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it. Note that if you are not already a member of the bioconda project (meaning that you can't add this label), please ping `@bioconda/core` so that your PR can be reviewed and merged (please note if you'd like to be added to the bioconda project). Please see https://github.com/bioconda/bioconda-recipes/issues/15332 for more details.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by Leon-Bichmann** [comment]
In this PR I am trying to add easypqp a new python packaged tool to generate spectral libraries for biological mass spectrometry - proteomics .

**Comment by Leon-Bichmann** [comment]
@dpryan79 I think the problem is the current pyopenms depencency on python2. Do you agree?

**Comment by dpryan79** [comment]
Yeah, for some reason I thought pyopenms needed python 2.

**Comment by Leon-Bichmann** [comment]
yeah I hope it passes, autowrap apparently has been causing some problems for python3. Thats why I fixed the version 0.19.0 now.

**Comment by dpryan79** [comment]
autowrap 0.19.0 doesn't seem to be available in conda yet

**Comment by Leon-Bichmann** [comment]
Is it possible to add it? I don't see an autowrap recipe in bioconda

**Comment by Leon-Bichmann** [comment]
We just figured, it should work with the 0.18.1 version of autowrap as well.

**Comment by dpryan79** [comment]
autowrap 0.20.0 just got merged in on conda-forge, so if you do end up needing a newer version it's there now.

**Comment by Leon-Bichmann** [comment]
for some reason openms 2.4 is still depending on python2 ...

**Comment by dpryan79** [comment]
Should it need python at all?

**Comment by jpfeuffer** [comment]
I don't think OpenMS should need python. Maybe someone had pyopenms in mind while designing the OpenMS recipe.

It seems like Qt is trying to find OpenGL but does not succeed. I am not sure why it is looking for the QtGui target at all when -WITH_GUI=Off is set.. hmm..

In general, @Leon-Bichmann I guess you have to sync your commit with the changes in the openms PR. Otherwise you get into trouble with Xerces and Boost.

**Comment by Leon-Bichmann** [comment]
@BiocondaBot update

**Comment by dpryan79** [comment]
@bioconda-bot please update

You have to say "please" :)

**Comment by Leon-Bichmann** [comment]
@dpryan79 is this ready for a merge?

**Comment by dpryan79** [comment]
@bioconda-bot please fetch artifacts

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Comment by Leon-Bichmann** [comment]
awesome thx!

**Pull request merged**
