### PR TITLE
Update recipe for PathoScope 2.0.7

### PR DESCRIPTION
**Pull request by davebx**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.

### CODE REVIEW

**Comment by epruesse** [comment]
@biocondabot recheck

**Comment by epruesse** [comment]
LGTM. Thanks for doing a bit of cleanup on the recipe.

Would you like to adopt this one as maintainer?

**Comment by davebx** [comment]
I can do that.

**Comment by epruesse** [comment]
Thanks! Feel free to merge once the rebuild is done.

**Comment by davebx** [comment]
@BiocondaBot recheck

**Pull request merged**
