### PR TITLE
Update bioconductor-genomeinfodbdata to 1.0.0.

### PR DESCRIPTION
**Pull request by cbrueffer**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by cbrueffer** [comment]
@jdblischak indeed; one of the packages I added today depends on it so I went ahead with the update. I saw the changes to the bioconductor recipes you added recently, I suppose that alone wouldn't have been enough to fix 0.99.1?

**Comment by jdblischak** [comment]
> I suppose that alone wouldn't have been enough to fix 0.99.1

It's complicated. The MD5 issue presumably will be fixed in due time (once the Bioconductor mirrors update). I wanted to fix the other issues listed in #235.

> To answer your question, if you think your changes would fix the 0.99.1 we could try that. Otherwise marking it broken seems fine to me.

I think it'd be worth trying to fix. Can I submit a PR that makes 0.99.1 a subdirectory, i.e. `recipes/bioconductor-genomeinfodbdata/0.99.1`, similar to `bioconductor-org.mm.eg.db/3.3.0/`? Once the updated version is built and uploaded to Anaconda Cloud, I can send a follow-up PR to remove it. Do you think this is a good plan?

**Comment by cbrueffer** [comment]
As far as I'm concerned that sounds good. Might as well even leave the 0.99.1 subdirectory in place, I don't see a reason to remove it once it's there.

**Comment by jdblischak** [comment]
It seems that the Bioconductor team has removed the 0.99.1 tarball (at the very least the canonical URL for data packages has been removed):

```
$ wget https://bioconductor.org/packages/3.6/data/annotation/src/contrib/GenomeInfoDbData_0.99.1.tar.gz 
--2017-12-21 22:27:48--  https://bioconductor.org/packages/3.6/data/annotation/src/contrib/GenomeInfoDbData_0.99.1.tar.gz
Resolving bioconductor.org... 13.33.164.217, 13.33.164.103, 13.33.164.218, ...
Connecting to bioconductor.org|13.33.164.217|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-12-21 22:27:49 ERROR 404: Not Found.
```

@daler Could you please label the 0.99.1 versions of GenomeInfoDbData as broken? They aren't going to work because the URL has been removed.

https://anaconda.org/bioconda/bioconductor-genomeinfodbdata/files?version=0.99.1

Also, could the 0.99.1 tarball on Cargo Port be deleted? The version uploaded to the Cargo Port was likely the wrong tarball anyways. See https://github.com/bioconda/bioconda-utils/issues/236 and https://github.com/Bioconductor/GenomeInfoDbData/issues/1 for more details.

https://depot.galaxyproject.org/software/bioconductor-genomeinfodbdata/

**Comment by daler** [comment]
@jdblischak just marked `bioconductor-genomeinfodb==0.99.1` as broken in anaconda; we'll need @bgruening to help with the cargo-port package.

**Comment by jdblischak** [comment]
Following up on this:

> just marked bioconductor-genomeinfodb==0.99.1 as broken in anaconda;

@daler Thanks! And just for the record, it is bioconductor-genomeinfodb**data** 0.99.1 that is labeled as broken: https://anaconda.org/bioconda/bioconductor-genomeinfodbdata/files?version=0.99.1

> we'll need @bgruening to help with the cargo-port package.

@bgruening Could you please delete the corresponding cargo-port tarball?

https://depot.galaxyproject.org/software/bioconductor-genomeinfodbdata/bioconductor-genomeinfodbdata_0.99.1_src_all.tar.gz

**Comment by daler** [comment]
@jdblischak right, sorry, that was my typo in the comment.

**Pull request merged**
