### PR TITLE
Add recipe for merge_kallisto

### PR DESCRIPTION
**Pull request by fgypas**
Add recipe for merge_kallisto

### CODE REVIEW

**Comment by fgypas** [comment]
@BiocondaBot add label

**Comment by fgypas** [comment]
@BiocondaBot please add label

**Comment by fgypas** [comment]
There is still an issue with the current meta.yaml that is described in #28464.
What is missing is to add the script `merge_kallisto.R` from the github repo in the PATH.

**Comment by dpryan79** [comment]
@fgypas You're missing a build.sh

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Comment by fgypas** [comment]
Thanks a lot @dpryan79 for your help!

**Pull request merged**
