### PR TITLE
fix numpy dependency to 1.23

### PR DESCRIPTION
**Pull request by oschwengers**
Numpy dependency of Deepsig was pinned to version 1.23 since Tensorflow 2.2.0 uses `numpy.object` which was deprecated in version `1.24`.

np.object attribute is deprecated since Numpy 1.24 resulting in the following error:
```
File ".../lib/python3.8/site-packages/tensorflow/python/framework/dtypes.py", line 513, in <module>
    np.object,
  File ".../lib/python3.8/site-packages/numpy/__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'object'
```

### CODE REVIEW

**Review by rpetit3 — APPROVED** [review]

**Comment by rpetit3** [comment]
@BiocondaBot please merge

**Comment by rpetit3** [comment]
@BiocondaBot please fetch artifacts

**Comment by rpetit3** [comment]
@BiocondaBot please merge

**Comment by rpetit3** [comment]
@BiocondaBot please merge

**Comment by rpetit3** [comment]
💯 good bot

**Comment by oschwengers** [comment]
I don't understand the bot warning, but this PR is merged into `master`: https://github.com/bioconda/bioconda-recipes/blob/29b2197ecf54d17a908d171a10d87c5462edfbf3/recipes/deepsig/meta.yaml#L24

Thanks @rpetit3 !

**Comment by bgruening** [comment]
Conda package and Docker container is uploaded, so I think we are fine.

**Pull request merged**
