### PR TITLE
Fixing build extensions and tests [scikit-allel]

### PR DESCRIPTION
**Pull request by hardingnj**
* [X] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [X] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

re: scikit-allel
Cython extensions were not built due to missing numpy/cython from build requirements
Also, added test

### CODE REVIEW

**Comment by bgruening** [comment]
@hardingnj glad to see you here! Please increase the build version number in your recipe.

**Comment by hardingnj** [comment]
Thanks for the welcome. That should be done now?

**Comment by bgruening** [comment]
Feel free to merge this by yourself as soon as test passes. You should be able to this now! :)
One thing you could try it to enable OSX builds as well :)

**Comment by bgruening** [comment]
:100:

**Pull request merged**
