### PR TITLE
Add recipe for RATT

### PR DESCRIPTION
**Pull request by 0xaf1f**
https://github.com/ThomasDOtto/ratt
http://ratt.sourceforge.net/
https://academic.oup.com/nar/article/39/9/e57/1236534

It depends on mummer, but I don't understand why mummer4 is a separate package. Anyway, I tested with both, but declared the dependency just on mummer so that if that package gets updated, nothing needs to change.

* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [X] This PR adds a new recipe.
* [X] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by 0xaf1f** [comment]
I don't understand the last build failure. The package was built and the test completed successfully, but then it looks like circleci itself crashed. See:

```
18:12:32 BIOCONDA INFO (ERR) [Oct  1 18:12:32] DEBU Container [b72fdfd63c55 step-5c3c5a51d2] completed with exit code [0] as expected
18:12:32 BIOCONDA INFO (ERR) [Oct  1 18:12:32] DEBU Container [b72fdfd63c55 step-5c3c5a51d2] removed
.18:13:12 BIOCONDA INFO (OUT) ...

Traceback (most recent call last):
  File "/home/circleci/project/miniconda/bin/bioconda-utils", line 10, in <module>
    sys.exit(main())
  File "/home/circleci/project/miniconda/lib/python3.6/site-packages/bioconda_utils/cli.py", line 924, in main
    bioconductor_skeleton, clean_cran_skeleton, autobump, bot
  File "/home/circleci/project/miniconda/lib/python3.6/site-packages/argh/dispatching.py", line 328, in dispatch_commands
    dispatch(parser, *args, **kwargs)
  File "/home/circleci/project/miniconda/lib/python3.6/site-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/home/circleci/project/miniconda/lib/python3.6/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/home/circleci/project/miniconda/lib/python3.6/site-packages/argh/dispatching.py", line 260, in _call
    result = function(*positional, **keywords)
  File "<boltons.funcutils.FunctionBuilder-5>", line 2, in build
  File "/home/circleci/project/miniconda/lib/python3.6/site-packages/bioconda_utils/cli.py", line 130, in wrapper
    func(*args, **kwargs)
  File "<boltons.funcutils.FunctionBuilder-4>", line 2, in build
  File "/home/circleci/project/miniconda/lib/python3.6/site-packages/bioconda_utils/cli.py", line 59, in wrapper
    func(*args, **kwargs)
  File "/home/circleci/project/miniconda/lib/python3.6/site-packages/bioconda_utils/cli.py", line 454, in build
    label=label)
  File "/home/circleci/project/miniconda/lib/python3.6/site-packages/bioconda_utils/build.py", line 349, in build_recipes
    linter=linter)
  File "/home/circleci/project/miniconda/lib/python3.6/site-packages/bioconda_utils/build.py", line 156, in build
    pkg_test.test_package(pkg_path, base_image=base_image)
  File "/home/circleci/project/miniconda/lib/python3.6/site-packages/bioconda_utils/pkg_test.py", line 169, in test_package
    p = utils.run(cmd, env=env, cwd=d, mask=False)
  File "/home/circleci/project/miniconda/lib/python3.6/tempfile.py", line 809, in __exit__
    self.cleanup()
  File "/home/circleci/project/miniconda/lib/python3.6/tempfile.py", line 813, in cleanup
    _shutil.rmtree(self.name)
  File "/home/circleci/project/miniconda/lib/python3.6/shutil.py", line 480, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/home/circleci/project/miniconda/lib/python3.6/shutil.py", line 418, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/home/circleci/project/miniconda/lib/python3.6/shutil.py", line 438, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/home/circleci/project/miniconda/lib/python3.6/shutil.py", line 436, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
PermissionError: [Errno 13] Permission denied: 'Tb_H37Rv.embl'
Exited with code 1
```

It looks to me like circleci had trouble cleaning up.

**Comment by 0xaf1f** [comment]
@bioconda/core

**Comment by dpryan79** [comment]
@0xaf1f There's a disconnect between the user id used inside the container and that used by the build system, so the latter can't delete files created by the former when cleaning up after docker tests. I just had it delete the output and intermediate files to bypass that.

**Comment by 0xaf1f** [comment]
Hm. That's a weird problem. Thanks for looking into it and making the appropriate tweak!

**Pull request merged**
