### PR TITLE
Fix Genomedata recipe to use updated PyTables and fix dependency conflicts

### PR DESCRIPTION
**Pull request by EricR86**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

Genomedata relies on a fix to the issue found here:
https://github.com/conda-forge/pytables-feedstock/issues/29
Fixed in this PR:
https://github.com/conda-forge/pytables-feedstock/pull/30

### CODE REVIEW

**Comment by EricR86** [comment]
Not sure what is happening with the build machine in this case. The link that build says it cannot download from works for me when I copy it.

**Comment by daler** [comment]
@EricR86 PyPI is having network issues today https://status.python.org; this failure it's likely an intermittent issue outside our control.

**Comment by daler** [comment]
@EricR86 I restarted the tests, they now pass. Looks like you needed to exclude the hdf5 from this recipe to avoid conflicting with the [pinned version in conda-forge](https://github.com/tomkooij/pytables-feedstock/blob/ad09360603e9ae9db3bdf9d5bc045acef60f9ead/recipe/meta.yaml#L32), is that right?

**Comment by EricR86** [comment]
I believe so.

More accurately I essentially need to keep up to date with the version PyTables uses since older conda builds (and releases) will cause Genomedata to segfault. The reason for that is in the issues I linked originally.

**Comment by daler** [comment]
Got it, thanks!

**Pull request merged**
