### PR TITLE
Update bwakit 0.7.15 to de-vendor binaries and add missing dependencies

### PR DESCRIPTION
**Pull request by stekaz**
Hi, this PR de-vendors the binaries that ship with [bwakit](https://github.com/bioconda/bioconda-recipes/tree/master/recipes/bwakit) and ensures that the versions used here are the same as the ones it was released with (similar to the [fermikit](https://github.com/bioconda/bioconda-recipes/tree/master/recipes/fermikit) recipe).

The only exception is the version of the K8 interpreter, which is required to run the provided Javascripts. Newer versions (0.2.4 and later) can parse a script's shebang line, which makes running these scripts much more convenient.

Also for convenience, I've included a list of the versions of the binaries included in the bwakit 0.7.15 release:

```
$ wget https://downloads.sourceforge.net/project/bio-bwa/bwakit/bwakit-0.7.15_x64-linux.tar.bz2
$ tar xf bwakit-0.7.15_x64-linux.tar.bz2 && cd bwa.kit
$ ./bwa 2>&1 | grep "^Usage" # Version: 0.7.15-r1140
$ ./fermi2 2>&1 | grep "^Version" # Version: r170
$ ./htsbox 2>&1 | grep "^Version" # Version: htslib lite-r308, htsbox r315
$ ./k8 -v # V8: 3.16.14 K8: 0.2.1-r57
$ ./ropebwt2 2>&1 | grep "^Usage" # Usage:   ropebwt2-r187 [options] <in.fq.gz>
$ ./samblaster --version # samblaster: Version 0.1.20
$ ./samtools --version # samtools 1.3 Using htslib 1.3 Copyright (C) 2015 Genome Research Ltd.
$ ./seqtk 2>&1 | grep "^Version" # Version: 1.0-r82-dirty
$ ./trimadap 2>&1 | grep "^Usage" # Usage:   trimadap [options] <in.fq>
```

_Some notes about some of the dependencies:_

**Samtools 1.3 recipe:**
* This recipe is basically the same as the (re-added) 1.3.1 recipe.
* This recipe was re-added to force a rebuild because using `samtools ==1.3` (currently) fails with:
```
samtools: error while loading shared libraries: libncurses.so.5: cannot open shared object file: No such file or directory
```

**Trimadap r2 recipe:**
* Since no version number was provided with the version shipped, I've had to assume version r2 was the version shipped. I think this is a fair assumption: this is the last version that makes the 'trimadap' binary. Later versions make a multithreaded version called 'trimadapt-mt'.
* I've included a patch that:
 1. Fixes a small issue when opening stdin, and
 2. Ensures the output stats are written to stderr (i.e. not erroneously included on stdout).

**The bwakit 0.7.15 recipe:**
* I've included a couple of patches that:
1. Ensures that 'run-bwamem' with the '-s' (sort) option calls 'samtools sort' correctly, and
2. Updates the 'run-gen-ref' (run generate reference) script to set the updated GRCh38 url.

Please let me know if there any issues or if some clarification is needed, thanks!

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by stekaz** [comment]
@BiocondaBot please fetch artifacts

**Comment by stekaz** [comment]
@BiocondaBot please fetch artifacts

**Comment by stekaz** [comment]
@BiocondaBot please fetch artifacts

**Comment by stekaz** [comment]
@BiocondaBot please add label

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Comment by stekaz** [comment]
Thanks very much @dpryan79 !

**Pull request merged**
