### PR TITLE
added openslide recipe

### PR DESCRIPTION
**Pull request by ThomasWollmann**
* [x] I have read the guidelines above.
* [x] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by ThomasWollmann** [comment]
continues https://github.com/bioconda/bioconda-recipes/pull/3436

**Comment by ThomasWollmann** [comment]
ping @bgruening do you know what goes wrong during the build?

**Comment by ThomasWollmann** [comment]
@bgruening awesome it passes!

**Comment by bgruening** [comment]
Jupp! Damn dependencies...

**Pull request merged**
