### PR TITLE
Remove urllib3

### PR DESCRIPTION
**Pull request by kain88-de**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [x] This PR does something else (explain below).

The urllib3 package is removed since it is available on conda-forge. All recipes requiring urllib3 are changed to require minimum a version larger then available on the bioconda channel.

### CODE REVIEW

**Comment by bgruening** [comment]
Nice! Thanks a bunch!

**Comment by kain88-de** [comment]
Any idea why the linter failed?

**Comment by bgruening** [comment]
@kain88-de if you look at the travis output travis tells you the reson(s).
```
recipes/arvados-python-client  [uses_setuptools, setup_py_install_args]
recipes/dropbox                                 [setup_py_install_args]
recipes/httpretty                               [setup_py_install_args]
```
You can get more informations here: https://bioconda.github.io/linting.html
For example we would like to have `$PYTHON setup.py install --single-version-externally-managed --record=record.txt` in the build.sh instead of `setup.py install`.
The use_setuptools looks like there is setuptools as a runtime environment, which is most likely also false. This is not your fault, but we improve our build infrastructure to prevent errors and these recipes are not following our latest recommendations.

**Comment by kain88-de** [comment]
Ah I understand that is easy to fix. Updating your recipes to follow the same standard is a good idea anyway.

**Comment by bgruening** [comment]
Thanks Max!

**Comment by kain88-de** [comment]
@bgruening I don't see how I can fix the last error. The package depends on setuptools in the setup.py

**Comment by bgruening** [comment]
@kain88-de thats fine! Thanks a lot!

**Pull request merged**
