### PR TITLE
Update scanpy to 1.4.5.post2

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`scanpy`](https://bioconda.github.io/recipes/scanpy/README.html): **1.4.4.post1** &rarr; **1.4.5.post2**

[install with bioconda](http://bioconda.github.io/recipes/scanpy/README.html) [Conda](https://anaconda.org/bioconda/scanpy/files)

Info | Link
-----|-----
Recipe | [`recipes/scanpy`](https://github.com//bioconda/bioconda-recipes/tree/bump/scanpy/recipes/scanpy) (click to view/edit other files)
Releases |[https://github.com/theislab/scanpy/tags](https://github.com/theislab/scanpy/tags)
Author | `@theislab`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by dpryan79** [comment]
`anndata` needs to be updated

**Comment by bgruening** [comment]
mh 0.7rc1 does not sound encouraging ...

**Comment by dpryan79** [comment]
@bioconda-bot please update

**Comment by npavlovikj** [comment]
`anndata` was just updated to 0.7.1, https://anaconda.org/conda-forge/anndata, so we can give this PR another try.

**Pull request closed without merging**
