### PR TITLE
Update MS2PIP version to 4.0.0

### PR DESCRIPTION
**Pull request by jonasscheid**
Somehow the PyPI release did not sync with BioConda

Doing it manually know

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

### General instructions

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

### Instructions for avoiding API, ABI, and CLI breakage issues
Conda is able to record and lock (a.k.a. pin) dependency versions used at build time of other recipes.
This way, one can avoid that expectations of a downstream recipe with regards to API, ABI, or CLI are violated by later changes in the recipe.
If not already present in the meta.yaml, make sure to specify `run_exports` (see [here](https://bioconda.github.io/contributor/linting.html#missing-run-exports) for the rationale and comprehensive explanation).
Add a `run_exports` section like this:

```yaml
build:
  run_exports:
    - ...

```

with `...` being one of:

| Case                             | run_exports statement                                               |
| -------------------------------- | ------------------------------------------------------------------- |
| semantic versioning              | `{{ pin_subpackage("myrecipe", max_pin="x") }}`     |
| semantic versioning (0.x.x)      | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}`   |
| known breakage in minor versions | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| known breakage in patch versions | `{{ pin_subpackage("myrecipe", max_pin="x.x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| calendar versioning              | `{{ pin_subpackage("myrecipe", max_pin=None) }}`    |

while replacing `"myrecipe"` with either `name` if a `name|lower` variable is defined in your recipe or with the lowercase name of the package in quotes.

### Bot commands for PR management

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

Note that the <code>@BiocondaBot please merge</code> command is now depreciated. Please just squash and merge instead.

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by aliciaaevans** [comment]
I'm not sure why that disconnect happened, but I've been watching the logs on the current build (if you watch them live it you can see some of it versus trying to load logs after the fact, which fails if the runner stops responding).

`ms2rescore_rs` is not found, it should be `ms2rescore-rs`. Pandas 1.* doesn't support Python 3.12, so either allow Pandas 2 or add `skip: true # [py >= 312]` to the `build` section.

**Comment by jonasscheid** [comment]
Thanks for your help! I followed the logs as well and at some point it disconnects when building the conda environment as far as I could see. I have the feeling that this is the issue though:
Screenshot 2024-09-04 at 14 57 12

Are we at memory capacity here with Azure?

**Comment by aliciaaevans** [comment]
That definitely could be. I see that warning on quite a few other jobs that succeeded, but maybe they finished just under the limit. Usually there's a different error message when it runs out of resources, something like "stopped responding" vs "disconnected", but that could be a difference between running out of CPU vs RAM or something like that. I'm doing a local build to see if there's anything obvious.

Here are the runner specs for Azure.
> 2 core CPU, 7 GB of RAM, and 14 GB of SSD disk space

**Comment by aliciaaevans** [comment]
Profiling a local build of ms2pip peaked at ~10.9 GB memory.

**Comment by jonasscheid** [comment]
Huh, thats a lot. Thanks for testing!
Sorry, I am not experienced with advanced bioconda recipes. How could I limit the memory? Creating a `build.sh` and just add

```
#!/bin/bash

# Limit virtual memory (in kilobytes)
ulimit -v <memory_in_kilobytes>
```
?

**Comment by jonasscheid** [comment]
@bioconda/core can someone help me out here? I cannot find docs regarding limiting memory or disk space during building on Azure

**Comment by martin-g** [comment]
The memory is already limited - your recipe seems to use all of the available space. If you limit it (somehow) even further then it will reach it sooner!
You need to find a way to reduce the number of the dependencies of your recipe or their sizes.

**Comment by aliciaaevans** [comment]
There have been several of these PRs recently that have this disconnect issue. I'm going to try building them on our bulk branch that uses GitHub Actions for CI. Can you please undo any unwanted changes that you made to experiment on this branch and let me know if/when the recipe is ready?

**Comment by jonasscheid** [comment]
Thanks @aliciaaevans! Recipe ready 👍🏼

**Comment by aliciaaevans** [comment]
This has been successfully uploaded to the channel. (I haven't merged `bulk` back to `master` yet, waiting on another recipe.)

**Comment by jonasscheid** [comment]
Thank you! 🙏

**Pull request closed without merging**
