### PR TITLE
update AMPtk to version 1.2.5

### PR DESCRIPTION
**Pull request by nextgenusfs**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by nextgenusfs** [comment]
@druvus was wondering if you would be able to help me out -- I'm trying to update AMPtk recipe to v1.2.5 -- I had to fix a problem with a dependency version check that was causing scripts to die.  But when I went to update the recipe, I noticed it was on the blacklist with a note saying "taking forever".  I'm not sure what is wrong.  I was able to get the `circleci build` locally to work, but in order to do that I needed to remove it from blacklist.  The checks seem to be stuck (i.e. the blacklisted "taking forever" comment).  One error I got during linting was a `should_be_noarch`, however, when I looked at the docs it says specifically to not add this if your program is a command line tool (which is what AMPtk is).

**Comment by nextgenusfs** [comment]
Okay, so looks like if I use the skip no_arch method then it passes linting.  However, looks like the first build failed, although I don't see why -- the logs seem to indicate it built successfully but that the tar.bz2 was missing??
```
cp: cannot stat `/opt/conda/conda-bld/linux-64/amptk-1.2.5-0.tar.bz2': No such file or directory
```

**Comment by druvus** [comment]
@nextgenusfs I am now back after some travelling so I will look into this issue.

**Comment by druvus** [comment]
Previous attempt to get it working #11133

**Comment by nextgenusfs** [comment]
Here is what is happening to me locally with bootstrap.py, not sure if this helps or not..... https://github.com/bioconda/bioconda-recipes/issues/12290

**Comment by nextgenusfs** [comment]
I reorganized code and pushed a new recipe https://github.com/bioconda/bioconda-recipes/pull/13553

**Pull request closed without merging**
