### PR TITLE
Add kraken tool.

### PR DESCRIPTION
**Pull request by lpantano**

### CODE REVIEW

**Comment by kyleabeauchamp** [comment]
Are you sure this is academically licensed?  See, e.g., https://github.com/DerrickWood/kraken/blob/master/LICENSE

**Comment by lpantano** [comment]
thanks @kyleabeauchamp

**Comment by tomkinsc** [comment]
Just an FYI, in case anyone is wondering why tests are taking so long: Travis is in the middle of a migration, and has reduced capacity/issues as a result. https://www.traviscistatus.com

**Comment by lpantano** [comment]
thanks @tomkinsc, good to know! I created the pull request twice because I started to use branches from this repo instead of from my fork.

**Comment by yesimon** [comment]
Hi just saw this on my radar. I was actually working on exactly the same thing, which is why i put forth the jellyfish1 recipe that is a proper dependency of kraken. I'll have my PR up in a minute.

**Comment by yesimon** [comment]
Please see #390. Only real differences are git version and only installing to `PATH` non libexec binaries.

**Comment by lpantano** [comment]
@yesimon sounds good. we can close this pull request. Just a comment. jellyish is only a requirement if you want to use build command. Using pre-build databases doesn't require it.

**Comment by yesimon** [comment]
@lpantano That's a good point. I'll split this into two pkgs and a metapackage. One to not include `kraken-build` and add a separate package to include it as well as a meta containing both.

**Comment by lpantano** [comment]
@yesimon perfect! feel free to close this and continue with your plan!

**Pull request closed without merging**
