### PR TITLE
bump luciphor to 2.1

### PR DESCRIPTION
**Pull request by bernt-matthias**
Describe your pull request here

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by bernt-matthias** [comment]
ping @oliveralka 

do you think we java requirements are OK this way? 

just realized how bad the versioning is now. somehow I chose the date as version. seems impossible to switch to the correct version (2.1) since this is smaller (?) than the date 2019

**Comment by oliveralka** [comment]
I think the java requirements are alright - tested with java8 and java13 on MacOS 10.15.13.

Version wise, the only difference is that the 2.1 is using maven, which allows the use of luciphor2 in higher java versions. It seems that the base version of LuciPhor does not have changed directly... (Version: 1.2014Oct10)

**Comment by bernt-matthias** [comment]
@BiocondaBot please fetch artifacts

**Comment by bernt-matthias** [comment]
OK. Maybe we should have a round of testing: 

`conda create --override-channels -c https://102620-42372094-gh.circle-artifacts.com/0/tmp/artifacts/packages -c conda-forge -c bioconda -n luciphor2.1 luciphor2`

I can test on Linux. Do you have a command / test data in mind?

**Comment by oliveralka** [comment]
I uploaded some data here:

https://drive.google.com/drive/folders/1Po15DJpuzZVXcHx7VIPNWJC3LvyiJ3hi?usp=sharing

Unfortunately, we do not have anything smaller, since there might be a bug when we reindex the attributes in the mzML, which might clash with the java mzML parser used in luciphor2. We are not sure yet.

**Comment by oliveralka** [comment]
Works for me (LuciPhor2.1 - using the environment above):  
```
MacOS 10.15.4
conda 4.8.2
openjdk 11.0.1 2018-10-16 LTS 
```

**Comment by bernt-matthias** [comment]
Work. But I get a few warnings in the beginning: 

```
JarClassLoader: Warning: module-info.class in lib/jaxb-runtime-2.3.1.jar is hidden by lib/jaxb-api-2.3.1.jar (with different bytecode)
JarClassLoader: Warning: module-info.class in lib/txw2-2.3.1.jar is hidden by lib/jaxb-api-2.3.1.jar (with different bytecode)
JarClassLoader: Warning: module-info.class in lib/istack-commons-runtime-3.0.7.jar is hidden by lib/jaxb-api-2.3.1.jar (with different bytecode)
JarClassLoader: Warning: module-info.class in lib/stax-ex-1.8.jar is hidden by lib/jaxb-api-2.3.1.jar (with different bytecode)
JarClassLoader: Warning: module-info.class in lib/FastInfoset-1.2.15.jar is hidden by lib/jaxb-api-2.3.1.jar (with different bytecode)
```

**Comment by oliveralka** [comment]
Yes, I saw them as well, but that is probably due to the maven fix  - not sure.
@chhh Is that ok?

**Comment by chhh** [comment]
@oliveralka This is ok, what this says is one dependency library is "shadowed" by another. That would only be a problem in case someone was consuming this as a library from Java JDK 9+. But this is just an application, not a library, so it's ok. As long as you don't mind the warnings.

**Comment by bernt-matthias** [comment]
Wonderful, then lets go ahead

**Comment by bernt-matthias** [comment]
@BiocondaBot please add label

**Comment by bernt-matthias** [comment]
@BiocondaBot please merge

**Pull request merged**
