### PR TITLE
Re-add ucsc-liftover, updated to 332

### PR DESCRIPTION
**Pull request by nsoranzo**
Double-quote env variables in Bash scripts.

* [x] I have read the guidelines above.
* [x] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by nsoranzo** [comment]
@bioconda/core Any clue why the build https://travis-ci.org/bioconda/bioconda-recipes/jobs/223113639#L611 is failing with:
```
/bin/sh: libpng-config: command not found
/bin/sh: libpng-config: command not found
/bin/sh: mysql_config: command not found
/bin/sh: mysql_config: command not found
```

**Comment by johanneskoester** [comment]
No idea, it should be there because of your dependencies. Does it work locally with plain conda build?

**Comment by bgruening** [comment]
Just a guess. Are these scripts with a invalid shebang?

**Comment by nsoranzo** [comment]
@johanneskoester Yes, it works locally with `conda build`, but fails with `./simulate-travis.py` with the same error.
@bgruening They both have `#!/bin/sh` as shebang.

**Comment by nsoranzo** [comment]
@johanneskoester @bgruening I suspect this is due to the conda build environment being created twice, first with the correct build requirements, then with others, see https://travis-ci.org/bioconda/bioconda-recipes/jobs/223113639#L832 

I have absolutely no idea why that's happening.

**Comment by bgruening** [comment]
have you seen this one? `pngwrite.c:7:87: fatal error: png.h: No such file or directory`

**Comment by johanneskoester** [comment]
If it cannot find the libpng header, maybe try adding `CPP_INCLUDE_PATH=$PREFIX/inlcude` or `C_INCLUDE_PATH=$PREFIX/include`?

**Comment by nsoranzo** [comment]
That's not the issue unfortunately, libpng-config is not found, which in turn creates the error. I have been debugging locally and it looks like that all requirements are not in the Conda environment.

**Comment by bgruening** [comment]
@nsoranzo it looks like that the build.sh script is executed, even if the `build` section exists. If you look at the OSX build, which just downloads a pre-compiled binary, this tries also to use the build.sh script as it seems.
This can be a conda bug. If we move the section into the build.sh script maybe this will work?

**Comment by nsoranzo** [comment]
@bgruening Thanks for the tip, that fixed the OS X build, but not the Linux one (as I expected). I added a few debugging commands to clarify my previous comments, you should now clearly see that the correct Conda build environment is overwritten but one containing readline, sqlite, python, mercurial, setuptools,wheel and pip.

**Comment by nsoranzo** [comment]
After another rebase, this is finally green thanks to some upstream Conda  bugfix.

**Pull request merged**
