### PR TITLE
Update samtools to 1.17

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`samtools`](https://bioconda.github.io/recipes/samtools/README.html): **1.16.1** &rarr; **1.17**

[install with bioconda](http://bioconda.github.io/recipes/samtools/README.html) [Conda](https://anaconda.org/bioconda/samtools/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/samtools`](https://github.com//bioconda/bioconda-recipes/tree/bump/samtools/recipes/samtools) (click to view/edit other files)
Summary | Tools for dealing with SAM, BAM and CRAM files
Home | [https://github.com/samtools/samtools](https://github.com/samtools/samtools)
Releases |[https://github.com/samtools/samtools/releases](https://github.com/samtools/samtools/releases)
Author | `@samtools`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by jmarshall** [comment]
As usual, this will need to wait for a **bioconda-utils** update that pins htslib at 1.17.

**Comment by daler** [comment]
@BiocondaBot please update

**Comment by daler** [comment]
`htslib=1.17` [is in the channel](https://anaconda.org/bioconda/htslib/files), the test here is [properly pulling it in](https://dev.azure.com/bioconda/bioconda-recipes/_build/results?buildId=29384&view=logs&j=e14e69ff-a0ae-55c4-b71d-229b239cfb2f&t=7df82132-b284-504b-53d6-7d3e63519572&l=887).

**Comment by daler** [comment]
@BiocondaBot please merge

**Comment by daler** [comment]
@mjsteinbaugh you had self-requested the review, do you want to approve+merge?

**Review by mjsteinbaugh — APPROVED** [review]
htslib 1.17 is ready to rock and roll, looks good to me

**Comment by mjsteinbaugh** [comment]
Let's wait to merge until this pull request is addressed https://github.com/bioconda/bioconda-recipes/pull/39500

**Comment by mjsteinbaugh** [comment]
@BiocondaBot please merge

**Comment by mjsteinbaugh** [comment]
@BiocondaBot please merge

**Comment by mjsteinbaugh** [comment]
@bioconda/core OK to merge samtools 1.17?

**Comment by mjsteinbaugh** [comment]
@BiocondaBot please merge

**Pull request merged**
