### PR TITLE
rebuild percolator

### PR DESCRIPTION
**Pull request by bgruening**
Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it. Note that if you are not already a member of the bioconda project (meaning that you can't add this label), please ping `@bioconda/core` so that your PR can be reviewed and merged (please note if you'd like to be added to the bioconda project). Please see https://github.com/bioconda/bioconda-recipes/issues/15332 for more details.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by bgruening** [comment]
> 20:12:41 BIOCONDA INFO (OUT) /opt/conda/conda-bld/xsd_1563999075833/work/libcutl/cutl/shared-ptr/base.hxx:34:41: error: ISO C++1z does not allow dynamic exception specifications

OO, ok this needs for time or help.

**Comment by bernt-matthias** [comment]
Just discovered this one. Would be nice for OpenMS. According to https://stackoverflow.com/questions/47284705/c1z-dynamic-exception-specification-error#47286842 we should need to fix to  C++14.

`Maybe CXXFLAGS=" -std=c++14"`?

**Comment by bernt-matthias** [comment]
Odd that https://anaconda.org/bioconda/percolator lists 3.1 already?

**Comment by glormph** [comment]
> Odd that https://anaconda.org/bioconda/percolator lists 3.1 already?
IIRC 3.1 was built before bioconda moved to a new c++ build procedure (details of which I do not know enough of).

**Comment by bernt-matthias** [comment]
Any idea how to continue? I could not make it build with tokyo cabinet but with boost it works, see also 
https://github.com/percolator/percolator/issues/250

**Comment by glormph** [comment]
Is it enough to have it done with boost? I guess fewer other packages depend on TC so any future boost upgrades will be more possible trouble?

**Comment by bernt-matthias** [comment]
ping @bgruening

**Comment by bernt-matthias** [comment]
Still unclear to me why 3.1 is online. We should bump after this is merged.

**Comment by dpryan79** [comment]
@bioconda-bot please fetch artifacts

**Comment by dpryan79** [comment]
Looks like this can get bumped to 3.40. Should we rebuild the old version first or just start on the newer version (it's all the same to me)?

**Comment by bernt-matthias** [comment]
Lets see what happens. 

I just realized that 3.03 was actually 3.3 ... which totally confused me.

See https://github.com/percolator/percolator/releases They list 3.4 as v3.04. Don't know how condas version comparison deals with this. I would suggest to stick with 3.4 since 3.0 and 3.1 are already out.

**Comment by dpryan79** [comment]
OMFG, that's a mess, I foresee the bot getting confused. You're totally correct that we should stick with 3.4 then.

**Comment by bernt-matthias** [comment]
Seems to work. So lets got with 3.4.

**Comment by dpryan79** [comment]
Merge whenever you're happy :)

**Comment by bernt-matthias** [comment]
@BiocondaBot please merge

**Pull request merged**
