### PR TITLE
[msgf_plus] fix jdk reqs

### PR DESCRIPTION
**Pull request by jpfeuffer**
@bernt-matthias [AFAIK](https://docs.conda.io/projects/conda-build/en/latest/resources/package-spec.html#:~:text=%3C%2C%20%3E%2C%20%3C%3D%2C%20%3E%3D%2C%20%3D%3D%2C%20and%20!%3D%20are%20relational%20operators%20on%20versions%2C%20which%20are%20compared%20using%20PEP%2D440.%20For%20example%2C%20%3C%3D1.0%20matches%200.9%2C%200.9.1%2C%20and%201.0%2C%20but%20not%201.0.1.%20%3D%3D%20and%20!%3D%20are%20exact%20equality.) "<= 17" means 16.8, 16.9, up to 17.0 but not 17.0.3 (Which is the only 17 version on conda-forge)

Also, the README says: Releases after April 2019 support Java 11 and newer; older releases will not work with Java 11 or newer (at least for reading mzML files) due to the deprecation and removal of some built-in libraries.

So why not put ">=11" which I propose here?

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

Note that the <code>@BiocondaBot please merge</code> command is now depreciated. Please just squash and merge instead.

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Review by ypriverol — APPROVED** [review]

**Review by bernt-matthias — APPROVED** [review]
Sounds reasonable to me. The reason for 17 was: https://github.com/bioconda/bioconda-recipes/pull/38855#issuecomment-1384480287

**Comment by ypriverol** [comment]
@bgruening is BiocondaBot broken?

**Comment by bgruening** [comment]
The bot is gone. Happy merging.

**Comment by ypriverol** [comment]
Noted. Thanks @bgruening

**Pull request merged**
