### PR TITLE
Netcdf metadata info

### PR DESCRIPTION
**Pull request by Alanamosse**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

The recipe for netcdf-metadata-info is designed to extract and summarize metadata informations about a netcdf file. This tool is for Galaxy use.
Source code : https://github.com/Alanamosse/Netcdf-Metadata-Info/
Galaxy tool preliminary version : https://github.com/65MO/Galaxy-E/tree/master/tools/read_netcdf

### CODE REVIEW

**Comment by bgruening** [comment]
@Alanamosse https://abi-laboratory.pro/tracker/timeline/netcdf/ indicates that it is save to use it like we do now.
OSX testing does not start because it is not activated in your account :( This should normally not matter, but for some reason the CI system is using your account and not the bioconda one. We are investigating this at the moment.

Either you activate OSX on your account or we need to wait to fix the underlying problem. Sorry.

**Comment by Alanamosse** [comment]
Do not apologize I probably did something wrong with the CI configuration, first time I use it and I probably don't fully get it.. I won't activate macos test as it seems there is no free option :/

**Comment by mbargull** [comment]
@Alanamosse I sent you an invite to join Bioconda. If you want to join, you'd have the ability to open a, e.g., `netcdf-metadata-info` branch from which macOS test can be run.

**Comment by Alanamosse** [comment]
Thank you @mbargull . 
This mean I need to : -delete my fork -clone the bioconda/bio-recipe repository -create the branch and open a new pool request ?

**Comment by mbargull** [comment]
No need to delete your fork, just push to a new branch on this repository:
```bash
git remote add upstream git@github.com:bioconda/bioconda-recipes.git
git push -u upstream HEAD:netcdf-metadata-info
```
The above will add this repository as a remote named `upstream` and with the `-u` parameter of `git push` should make your local branch track the new remote one. (At bare minimum
```bash
git push git@github.com:bioconda/bioconda-recipes.git HEAD:netcdf-metadata-info
```
should work, but I'd advice to use the former and add the main repo as `upstream` plus the tracking.)

**Comment by mbargull** [comment]
Ah, and for this new branch you'll have to open a new pull request, yes.

**Pull request closed without merging**
