### PR TITLE
Biotradis: pin samtools to 1.9

### PR DESCRIPTION
**Pull request by sbastkowski**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by epruesse** [comment]
@bioconda/core We need a fix for this.

@sbastkowski The sad thing is, while it should work, Conda will choose a lower build number of this package over a lower version of samtools. :-/

**Comment by dpryan79** [comment]
What was the original problem, was installing this downgrading the samtools in an environment?

**Comment by epruesse** [comment]
I understood the PR to be pinning samtools to 1.9 to keep it lower. Maybe I was wrong.

**Comment by dpryan79** [comment]
1.9 is the most recent release of samtools

**Comment by epruesse** [comment]
Ah. Then this should work I think.

**Comment by epruesse** [comment]
@sbastkowski - Can you fix the missing `license_file`?

**Comment by dpryan79** [comment]
> Ah. Then this should work I think.

I'm still not sure what was broken, we should wait for feedback from @sbastkowski

**Comment by epruesse** [comment]
Also, if this is about "at least 1.9", then it should be `>=1.9`. If biotradis works with any samtools version, this PR should be closed. You can force 1.9 or higher into your env by just adding `'samtools>=1.9'` to your `conda install` or `env.yaml'.

**Comment by sbastkowski** [comment]
Hi,
thanks for your help. It seems like for macOS installation the samtools version needs to be very specific (conda install -c bioconda samtools=1.9=h8ee4bcc_1). I think we leave it as it is for now as it seems to work. Potentially needs an additional run of specific samtools installation.

**Comment by dpryan79** [comment]
Do the newer build not work for some reason?

**Comment by sbastkowski** [comment]
As far as I understand, this is a samtools macOS issue. There seems to be some incompatibility.

**Comment by dpryan79** [comment]
Hmm, OK, if you get any details about that then please let us know.

**Pull request closed without merging**
