### PR TITLE
update bedtools 2.31

### PR DESCRIPTION
**Pull request by bgruening**
Describe your pull request here

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by mjsteinbaugh** [comment]
Erroring at this step:

```
2023-04-30T07:11:40.4468524Z 07:11:40 BIOCONDA INFO (OUT) make: *** No rule to make target 'install'.  Stop.
```

**Comment by mjsteinbaugh** [comment]
Aha I think the problem is we need to `cd` to nested `bedtools2` subdirectory before running `make`.

**Review by mjsteinbaugh — APPROVED** [review]
Cool yeah that fixed it -- looks good to merge

**Comment by bgruening** [comment]
Looks like osx is failing. Thanks @mjsteinbaugh for looking at it!

**Comment by mjsteinbaugh** [comment]
Ah you're right, I'll try building locally to see if I can fix this

**Comment by mjsteinbaugh** [comment]
Hmm yeah my recipe in koopa builds bedtools on macOS but conda is failing:
https://github.com/acidgenomics/koopa/blob/main/lang/shell/bash/include/install/common/shared/bedtools.sh

Not sure what difference is causing the issue

**Comment by jmarshall** [comment]
The need to add `cd bedtools2` is because the upstream tarball contains _.DS_Store_ files and the top-level one of those has prevented conda-build's usual “[move the contents up](https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#source-from-tarball-or-zip-archive)” behaviour.

I was not able to reproduce the macOS failure locally. There are other problems with the upstream tarball that may have caused this failure, and I think the upstream tarball may be going to be re-released soon (which will also correct the _.DS_Store_ problem).

So I would suggest holding off with this until upstream have corrected or superseded their release.

**Comment by jmarshall** [comment]
The upstream tarball has now been re-released, and this PR is probably superseded by #40802. We shall see whether the macOS failure has cured itself…

**Comment by jmarshall** [comment]
For the record: the reason why the macOS build continued to fail is that on macOS `.DS_Store` was ignored and did not cause the ‘usual ”move the contents up” behaviour’ to be suppressed. Hence `cd bedtools2` was counterproductive on macOS:

```
2023-05-01T12:16:08.3334030Z 12:16:08 BIOCONDA INFO (ERR) /…/conda_build.sh: line 7: cd: bedtools2: No such file or directory
```

The replacement PR now does this conditionally.

**Pull request closed without merging**
