### PR TITLE
snp-pileup

### PR DESCRIPTION
**Pull request by dariober**
Dummy update of recipe to test libcrypto.so.1.0.0 

Try to rebuild the package to see if we can reproduce/fix the issue with
libcrypto.so.1.0.0 described at
dariober/cnv_facets#14 and also appearing at https://circleci.com/gh/bioconda/bioconda-recipes/92111?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link

----

> Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences**
      (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

> Everyone has access to the following BiocondaBot commands, which can be given in a comment:
>
>  * `@BiocondaBot please update` will cause the BiocondaBot to merge the master branch into a PR
>  * `@BiocondaBot please add label` will add the `please review & merge` label.
>  * `@BiocondaBot please fetch artifacts` will post links to packages and docker containers built by the CI system. You can use this to test packages locally before merging.
>
> For members of the Bioconda project, the following command is also available:
>
>  * `@BiocondaBot please merge` will cause packages/containers to be uploaded and a PR merged. Someone must approve a PR first! This has the benefit of not wasting CI build time required by manually merging PRs.
>
> If you have questions, please post them in gitter or ping `@bioconda/core` in a comment (if you are not able to directly ping `@bioconda/core` then the bot will repost your comment and enable pinging).

### CODE REVIEW

**Comment by dpryan79** [comment]
I think the solver is just doing the wrong thing here.

**Comment by dpryan79** [comment]
Adding htslib as a dependency prevents the solver from screwing things up, though it's really annoying that that's needed.

**Comment by dpryan79** [comment]
I suspect python is just a run-time dependency, so it can just be added there (that will also cut the build time by 67%).

**Comment by dpryan79** [comment]
@bioconda-bot please fetch artifacts

Jumping the gun, but this will allow me to check if this needs to have python-specific builds

**Comment by dpryan79** [comment]
@bioconda-bot please fetch artifacts

**Comment by dpryan79** [comment]
@dariober This should fix the issues people have reported.

**Comment by dariober** [comment]
Thanks Devon! I see you have done a lot of stuff here - much appreciated all you help on bioconda and a million other things! I see the solution was to add htslib on the dependent recipe. If you get a chance, could you comment on why/what it has happened?

**Comment by dpryan79** [comment]
The solution is basically a hack around the conda solver doing the wrong thing. Basically the older build of snp-pipelup wasn't pinning the version of openssl it was compiled against because it was made before that was done on any package. For some terrible reason, the solver really likes to minimize dependency restrictions rather than maximize version and build numbers. Within bioconda all packages are pinned to specific versions of htslib, which then pinned to a specific version of openssl. By specifying htslib explicitly we ensure that the conda solver cannot prefer older builds with looser restrictions.

Long-term we need to update the meta information on old builds like this so they're properly pinned to openssl, but that will be a huge amount of work for which I don't think anyone has time.

**Pull request merged**
