### PR TITLE
New perl-sort-key recipe

### PR DESCRIPTION
**Pull request by jamesabbott**
Add recipe for perl Sort::Key module

This is not a bio-module itself, but is a prerequisite for a bio-module which has other dependancies in bioconda

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by mbargull** [comment]
I fixed the build by putting up a rebuild of the `conda-forge::perl=5.26.2` package.
Now only the test fail with
```
too few keys at /opt/conda/conda-bld/perl-sort-key_1603908582588/test_tmp/run_test.pl line 14.
```
which is an error from the `Sort::Key` package itself.

**Comment by jamesabbott** [comment]
Ah – that’s fantastic. Many thanks…

I’ll get on with making the rest of it work now it builds.

**Comment by jamesabbott** [comment]
@mbargull 
Tests are fixed on linux now, but the perl build looks a bit broken on MacOS:
```
(perl-build) M-000582:Sort-Key-1.33 jabbott $ conda list|grep perl
# packages in environment at /tmp/miniconda/miniconda/envs/perl-build:
perl                      5.26.2            hbcb3906_1007    conda-forge

(perl-build) M-000582:Sort-Key-1.33 jabbott $ perl -V
Possible unintended interpolation of @mac in string at /private/tmp/miniconda/miniconda/envs/perl-build/lib/5.26.2/darwin-thread-multi-2level/Config_heavy.pl line 250.
Possible unintended interpolation of @mac in string at /private/tmp/miniconda/miniconda/envs/perl-build/lib/5.26.2/darwin-thread-multi-2level/Config_heavy.pl line 1181.
Global symbol "@mac" requires explicit package name (did you forget to declare "my @mac"?) at /private/tmp/miniconda/miniconda/envs/perl-build/lib/5.26.2/darwin-thread-multi-2level/Config_heavy.pl line 250.
Global symbol "@mac" requires explicit package name (did you forget to declare "my @mac"?) at /private/tmp/miniconda/miniconda/envs/perl-build/lib/5.26.2/darwin-thread-multi-2level/Config_heavy.pl line 1181.
Compilation failed in require at /private/tmp/miniconda/miniconda/envs/perl-build/lib/5.26.2/darwin-thread-multi-2level/Config.pm line 105.
```

The same errors appear in the circleci macos build outputs. It looks like the '@' charachters in the email addresses in Config_heavy.pl are being interepreted as being arrays...

```
(perl-build) M-000582:Sort-Key-1.33 jabbott $ grep '@mac' vim /private/tmp/miniconda/miniconda /private/tmp/miniconda/miniconda/envs/perl-build/lib/5.26.2/darwin-thread-multi-2level/Config_heavy.pl
cf_email='root@mac-1603903100757.local'
perladmin='root@mac-1603903100757.local'
```

**Comment by mbargull** [comment]
*sigh*, yep, I've forgotten to backport a fix for that version. I'll report back when another build of Perl is up.

**Comment by mbargull** [comment]
I restarted the build -- should run through now (hopefully ^^).

**Comment by jamesabbott** [comment]
Looks good - many thanks

**Comment by jamesabbott** [comment]
@BiocondaBot please add label

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Pull request merged**
