### PR TITLE
add imseq

### PR DESCRIPTION
**Pull request by dkoppstein**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by bgruening** [comment]
@dkoppstein can you compile this package from source? Or do you need a new GCC compiler?

**Comment by dkoppstein** [comment]
@bgruening is it preferable to compile from source rather than using the precompiled binary? If so, perhaps we should update the guidelines. I just took the lazy approach ;-)

**Comment by bgruening** [comment]
@dkoppstein yes it is, but I saw you need seqan so it can be it is not possible atm with our old compiler. But please try.

**Comment by dkoppstein** [comment]
@bgruening oddly, I am able to build this using `conda build` and `simulate-travis.py` on my local machine using the updated commit in the PR, but it is failing on travis for some reason. Do you have any thoughts why this might be? Imseq ships with a minimal seqan so that shouldn't be the issue here.

**Comment by dkoppstein** [comment]
Thanks @bgruening for the helping hand!

**Comment by bgruening** [comment]
@dkoppstein sure thing sorry could't check if it went green.

**Pull request merged**
