### PR TITLE
pyranges 0.0.44

### PR DESCRIPTION
**Pull request by endrebak**
Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it. Note that if you are not already a member of the bioconda project (meaning that you can't add this label), please ping `@bioconda/core` so that your PR can be reviewed and merged (please note if you'd like to be added to the bioconda project). Please see https://github.com/bioconda/bioconda-recipes/issues/15332 for more details.

* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [X] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [X] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by endrebak** [comment]
Should I add the LICENSE file to the tar?

**Comment by dpryan79** [comment]
That's not really needed, I just sort of assumed it would be in there since it was in the github repository. Do you know which of the dependencies isn't available for python 3.6?

**Comment by endrebak** [comment]
All dependencies are there. IIRC, the only update I did from 0.0.43 to 0.0.44 was removing Cython from the non-build section, which the linter told me to do.

**Comment by endrebak** [comment]
The linter errors are in unrelated packages:


Screenshot 2019-06-04 at 14 53 05

**Comment by dpryan79** [comment]
Hmm, yeah the linting errors can be ignored.

@epruesse This is an example to the linting part of the bot getting the wrong files to lint for some reason.

**Comment by dpryan79** [comment]
Ah, pyrle isn't available for python 3.6 for some reason.

**Comment by endrebak** [comment]
Thanks! I'll fix when I get back from vacation.

**Comment by dpryan79** [comment]
In the interim, if you'd like to at least get the py37 build out there then this can be merged. Have a good vacation!

**Pull request merged**
