### PR TITLE
Update htslib to 1.10

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`htslib`](https://bioconda.github.io/recipes/htslib/README.html): **1.9** &rarr; **1.10**

[install with bioconda](http://bioconda.github.io/recipes/htslib/README.html) [Conda](https://anaconda.org/bioconda/htslib/files)

Info | Link
-----|-----
Recipe | [`recipes/htslib`](https://github.com//bioconda/bioconda-recipes/tree/bump/htslib/recipes/htslib) (click to view/edit other files)
Releases |[https://github.com/samtools/htslib/releases](https://github.com/samtools/htslib/releases)
Author | `@samtools`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by jmarshall** [comment]
Note that this bumps htslib to _libhts.so.3_, so other packages depending on htslib's dynamic library will need rebuilding.

**Comment by dpryan79** [comment]
@jmarshall Thanks for the heads up!

@bioconda/core Should we update the htslib pinning when we do the clang and python 3.8 transition? Obviously samtools/bcftools/pysam will need to get their pinnings changed sooner.

**Comment by dpryan79** [comment]
@BiocondaBot please fetch artifacts

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Pull request merged**
