### PR TITLE
update wfmash to v0.6.1

### PR DESCRIPTION
**Pull request by AndreaGuarracino**
To allow users to install more easily wfmash (https://github.com/ekg/wfmash/issues/87, https://github.com/pangenome/pggb/issues/112).

### CODE REVIEW

**Comment by subwaystation** [comment]
Ping @apeltzer ;)

**Comment by subwaystation** [comment]
Seems like https://anaconda.org/conda-forge/gsl/ is missing as a build dependency. I have a fix https://github.com/subwaystation/bioconda-recipes/tree/wfmash_recipe, but I can't push to @AndreaGuarracino's branch.

**Comment by subwaystation** [comment]
@rpetit3 Thanks for helping us out!
Do you have any idea, what's wrong now?

**Comment by rpetit3** [comment]
Ah, that makes total sense. Thank you very much

**Review by dpryan79 — APPROVED** [review]

**Comment by AndreaGuarracino** [comment]
Thank you guys for your help, and also for the explanation. Really appreciated.

**Pull request merged**
