### PR TITLE
Ammended syntax for setting permission as "+mode" is now deprecated.

### PR DESCRIPTION
**Pull request by slacalle**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by daler** [comment]
@slacalle thanks, can you clarify the issue? Is this a change to how `find` works? What version is the change in? Does the previous syntax return an error?

By the way, you'll have to bump the build number to get trigger a new build.

**Comment by slacalle** [comment]
Hi @daler , I was attempting to build the canu package with the default template and was not able to. This was due to the tests failing as it could not find the "canu" executable. Upon further investigation, it looks like the last command in the build script did not run correctly. When running manually, the following message appears:

"find: warning: you are using `-perm +MODE'.  The interpretation of `-perm +omode' changed in findutils-4.5.11.  The syntax `-perm +omode' was removed in findutils-4.5.12, in favour of `-perm /omode'."

more on this on the find manpages.

This is with findutils.x86_64 version 4.5.11-5.el7

**Comment by daler** [comment]
@slacalle thanks. The docker container we're using, `bioconda/bioconda-utils-build-env`, has `find 4.4.2` in it. If you test locally using the "bootstrap" method (https://bioconda.github.io/contribute-a-recipe.html#test-locally) it works -- so I don't think there's a need for this PR.

Of course, once we migrate the build system to something later than CentOS 6 we'll need to apply this fix. But that likely won't be for quite some time.

**Comment by slacalle** [comment]
@daler, ah now I understand. That makes sense. I will close this pull request for now then.

Thanks,

**Pull request closed without merging**
