### PR TITLE
gsalign: add linux-aarch64 build

### PR DESCRIPTION
**Pull request by martin-g**
Describe your pull request here

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

### General instructions

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

### Instructions for avoiding API, ABI, and CLI breakage issues
Conda is able to record and lock (a.k.a. pin) dependency versions used at build time of other recipes.
This way, one can avoid that expectations of a downstream recipe with regards to API, ABI, or CLI are violated by later changes in the recipe.
If not already present in the meta.yaml, make sure to specify `run_exports` (see [here](https://bioconda.github.io/contributor/linting.html#missing-run-exports) for the rationale and comprehensive explanation).
Add a `run_exports` section like this:

```yaml
build:
  run_exports:
    - ...

```

with `...` being one of:

| Case                             | run_exports statement                                               |
| -------------------------------- | ------------------------------------------------------------------- |
| semantic versioning              | `{{ pin_subpackage("myrecipe", max_pin="x") }}`     |
| semantic versioning (0.x.x)      | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}`   |
| known breakage in minor versions | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| known breakage in patch versions | `{{ pin_subpackage("myrecipe", max_pin="x.x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| calendar versioning              | `{{ pin_subpackage("myrecipe", max_pin=None) }}`    |

while replacing `"myrecipe"` with either `name` if a `name|lower` variable is defined in your recipe or with the lowercase name of the package in quotes.

### Bot commands for PR management

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

Note that the <code>@BiocondaBot please merge</code> command is now depreciated. Please just squash and merge instead.

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by martin-g** [comment]
Depends on:
- https://github.com/hsinnan75/GSAlign/pull/24

**Comment by martin-g** [comment]
The Mac OSX build fails due to:
```
 (ERR) dyld[17579]: Library not loaded: '@rpath/libclang-cpp.15.dylib'[0m
2024-04-24T14:37:25.4894410Z 14:37:19 [32mBIOCONDA INFO[0m (ERR)   Referenced from: '/opt/mambaforge/envs/bioconda/pkgs/clang-15-15.0.7-default_h7151d67_5/bin/clang-15'[0m
2024-04-24T14:37:25.4896810Z 14:37:19 [32mBIOCONDA INFO[0m (ERR)   Reason: tried: '/opt/mambaforge/envs/bioconda/pkgs/clang-15-15.0.7-default_h7151d67_5/bin/../lib/libclang-cpp.15.dylib' (no such file), '/opt/mambaforge/envs/bioconda/pkgs/clang-15-15.0.7-default_h7151d67_5/bin/../lib/libclang-cpp.15.dylib' (no such file), '/opt/mambaforge/envs/bioconda/pkgs/clang-15-15.0.7-default_h7151d67_5/bin/../lib/libclang-cpp.15.dylib' (no such file), '/opt/mambaforge/envs/bioconda/pkgs/clang-15-15.0.7-default_h7151d67_5/bin/../lib/libclang-cpp.15.dylib' (no such file), '/usr/local/lib/libclang-cpp.15.dylib' (no such file), '/usr/lib/libclang-cpp.15.dylib' (no such file)[0m
2024-04-24T14:37:25.4898590Z 14:37:19 [32mBIOCONDA INFO[0m (ERR) dyld[17580]: Library not loaded: '@rpath/libclang-cpp.15.dylib'[0m
2024-04-24T14:37:25.4899160Z 14:37:19 [32mBIOCONDA INFO[0m (ERR)   Referenced from: '/opt/mambaforge/envs/bioconda/pkgs/clang-15-15.0.7-default_h7151d67_5/bin/clang-15'[0m
2024-04-24T14:37:33.1340360Z 14:37:19 [32mBIOCONDA INFO[0m (ERR)   Reason: tried: '/opt/mambaforge/envs/bioconda/pkgs/clang-15-15.0.7-default_h7151d67_5/bin/../lib/libclang-cpp.15.dylib' (no such file), '/opt/mambaforge/envs/bioconda/pkgs/clang-15-15.0.7-default_h7151d67_5/bin/../lib/libclang-cpp.15.dylib' (no such file), '/opt/mambaforge/envs/bioconda/pkgs/clang-15-15.0.7-default_h7151d67_5/bin/../lib/libclang-cpp.15.dylib' (no such file), '/opt/mambaforge/envs/bioconda/pkgs/clang-15-15.0.7-default_h7151d67_5/bin/../lib/libclang-cpp.15.dylib' (no such file), '/usr/local/lib/libclang-cpp.15.dylib' (no such file), '/usr/lib/libclang-cpp.15.dylib' (no such file)[0m
2024-04-24T14:37:33.1343110Z 14:37:19 [32mBIOCONDA INFO[0m (ERR) make: *** [makefile:9: bwt.o] Abort trap: 6[0m
2024-04-24T14:37:33.1343540Z 14:37:19 [32mBIOCONDA INFO[0m (ERR) make: *** Waiting for unfinished jobs....[0m
2024-04-24T14:37:33.1344110Z 14:37:19 [32mBIOCONDA INFO[0m (ERR) make: *** [makefile:9: utils.o] Abort trap: 6[0m
```

Any ideas ?

**Comment by martin-g** [comment]
@BiocondaBot please fetch artifacts

**Comment by martin-g** [comment]
The Linux ARM64 artifacts look good:

```
mgrigorov in 🌐 euler-arm-22 in /tmp/gsalign via 🅒 test123 took 4s 
❯ tar jxvf gsalign-1.0.22-h7f8aa1e_5.tar.bz2                                                                                                                                                               (test123) 
info/files
info/run_exports.json
info/test/run_test.sh
info/hash_input.json
info/index.json
info/paths.json
info/recipe/build.sh
info/recipe/meta.yaml.template
info/licenses/LICENSE
info/recipe/meta.yaml
info/recipe/conda_build_config.yaml
info/about.json
info/git
info/recipe/support-linux-aarch64.patch
bin/bwt_index
bin/GSAlign

mgrigorov in 🌐 euler-arm-22 in /tmp/gsalign via 🅒 test123 
❯ file ./bin/*                                                                                                                                                                                             (test123) 
./bin/bwt_index: ELF 64-bit LSB pie executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, not stripped
./bin/GSAlign:   ELF 64-bit LSB pie executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, not stripped

mgrigorov in 🌐 euler-arm-22 in /tmp/gsalign via 🅒 test123 
❯ ./bin/GSAlign                                                                                                                                                                                            (test123) 

GenAlign v1.0.22
Usage: ./bin/GSAlign [-i IndexFile Prefix / -r Reference file] -q QueryFile[Fasta]

Options: -t     INT     number of threads [8]
         -o     STR     Set the prefix of the output files [output]
         -fmt   INT     Set the output format 1:maf, 2:aln [1]
         -idy   INT     Set the minimal sequence identity (0-100) of a local alignment [70]
         -slen  INT     Set the minimal seed length [15]
         -alen  INT     Set the minimal alignment length [200]
         -ind   INT     Set the maximal indel size [25]
         -clr   INT     Set the minimal cluster size [200]
         -unique        Output unique alignment only [false]
         -sen           Sensitive mode [False]
         -dp            Output Dot-plots
         -one           set one on one aligment mode[false]
         -gp    STR     Specify the path of gnuplot

```

**Comment by martin-g** [comment]
@BiocondaBot please add label

**Review by rpetit3 — APPROVED** [review]

**Pull request merged**
