### PR TITLE
Add some common exclusions to the .gitignore

### PR DESCRIPTION
**Pull request by peterjc**
* [ ] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [X] This PR does something else (explain below).

Having accidentally committed a ``meta.yaml~`` file created using emacs, I realised that the BioConda ``.gitignore`` could be expanded a little.

### CODE REVIEW

**Comment by peterjc** [comment]
@bgruening is one approval enough for me to merge this (assuming the automated tests pass)?

**Comment by bgruening** [comment]
Yes. For packages you can even merge it on your own if it is green. For those changes please wait for an approval.

**Comment by bgruening** [comment]
Thanks Peter!

**Comment by acaprez** [comment]
Hmm, one of the extensions added here was `.patch`.  There are many existing recipes with patch files named that way.  Given that, I think it would be better to not ignore it.

**Comment by peterjc** [comment]
Good point - BioConda is unusual in that respect, and I hadn't noticed this usage.

(This doesn't stop you adding a patch file, it means you have to do so a little more explicitly)

**Pull request merged**
