### PR TITLE
Add recipe for jgoslin 1.1.2

### PR DESCRIPTION
**Pull request by nilshoffmann**
This PR adds a recipe for jgoslin:

jgoslin project is a parser, validator and normalizer implementation for shorthand lipid nomenclatures, base on the Grammar of Succinct Lipid Nomenclatures project.

Goslin defines multiple grammers compatible with ANTLRv4 for different sources of shorthand lipid nomenclature. This allows to generate parsers based on the defined grammars, which provide immediate feedback whether a processed lipid shorthand notation string is compliant with a particular grammar, or not.

jGoslin uses the Goslin grammars and the generated parser to support the following general tasks:

    Facilitate the parsing of shorthand lipid names dialects.

    Provide a structural representation of the shorthand lipid after parsing.

    Use the structural representation to generate normalized names.

See https://github.com/lifs-tools/jgoslin for the project page of jgoslin and https://github.com/lifs-tools/goslin for the suite of grammars, tools and other implementations.

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by nilshoffmann** [comment]
@BiocondaBot please add label

**Comment by nilshoffmann** [comment]
@BiocondaBot please fetch artifacts

**Comment by mbargull** [comment]
@nilshoffmann, sorry for the delay. Looks good!
Could you add/`git cherry-pick` https://github.com/bioconda/bioconda-recipes/commit/01a4c6efe77576f1137eea2fe59e09e3836ee139 as well? Apart from the `license_file` addition, that is just a convenience change such that you'd not have to change the wrapper script for future updates :).
(I couldn't push to this PR's branch. Probably because of that GitHub shortcoming that you can't check "Allow edit from maintainers" if you open a PR from an organization and not your personal repo. I've tripped myself multiple times on that one, kinda annoying..)

**Comment by mbargull** [comment]
> Could you add/`git cherry-pick` [01a4c6e](https://github.com/bioconda/bioconda-recipes/commit/01a4c6efe77576f1137eea2fe59e09e3836ee139)

...and https://github.com/bioconda/bioconda-recipes/commit/63f69b70328d8efb6e33aff328bdac0653c7afa0 (I made a typo...).

**Comment by mbargull** [comment]
Sorry, the typos are strong with this one today...
Just https://github.com/bioconda/bioconda-recipes/commit/15b027a2a746487647cb2d4d2336558d03380470 should do it (unless I messed up again...).

**Comment by nilshoffmann** [comment]
@mbargull Applied your changes as a patch. Please check. Tests are all green.

**Comment by nilshoffmann** [comment]
@BiocondaBot please fetch artifacts

**Comment by mbargull** [comment]
@BiocondaBot, please merge

**Comment by mbargull** [comment]
Thanks!

**Comment by nilshoffmann** [comment]
> Thanks!

Thanks for your help!

**Pull request merged**
