### PR TITLE
Update htslib to 1.16

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`htslib`](https://bioconda.github.io/recipes/htslib/README.html): **1.15.1** &rarr; **1.16**

[install with bioconda](http://bioconda.github.io/recipes/htslib/README.html) [Conda](https://anaconda.org/bioconda/htslib/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/htslib`](https://github.com//bioconda/bioconda-recipes/tree/bump/htslib/recipes/htslib) (click to view/edit other files)
Summary | C library for high-throughput sequencing data formats.
Home | [https://github.com/samtools/htslib](https://github.com/samtools/htslib)
Releases |[https://github.com/samtools/htslib/releases](https://github.com/samtools/htslib/releases)
Author | `@samtools`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by jmarshall** [comment]
This should wait for a **bioconda-utils** update that pins htslib at 1.16 and libdeflate at 1.13.

**Comment by jmarshall** [comment]
I've pushed another commit to this branch, proposing automatically generating htslib's run requirements.
    
The htslib package depends only on library packages, which are dependencies that can be automatically derived. In particular, since the zlib/libzlib split (conda-forge/zlib-feedstock#52) this avoids a spurious run requirement for zlib (in favour of the libzlib subpackage, which is all that is actually required).

**Review by bwlang — APPROVED** [review]
looks fine to me - might unblock samtools 1.16 too

**Comment by bwlang** [comment]
@BiocondaBot merge

**Comment by jmarshall** [comment]
@bwlang: Samtools and bcftools 1.16 **cannot** be merged on **master** until the common infrastructure (on its **master**) has had htslib 1.16 pinning deployed to it, as described in https://github.com/bioconda/bioconda-recipes/pull/36524#issuecomment-1248641982. I believe this has not yet happened, as the current incarnation of **bulk** is still being worked on.

As described above, htslib 1.16 should not be merged on **master** until the common infrastructure has had libdeflate 1.13 pinning deployed to it. I believe this also has not yet happened. So please don't.

**Comment by bwlang** [comment]
@jmarshall : Looks like it will need a build version bump too...

**Pull request closed without merging**
