### PR TITLE
Update gget to 0.28.5

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`gget`](https://bioconda.github.io/recipes/gget/README.html): **0.28.4** &rarr; **0.28.5**

[install with bioconda](http://bioconda.github.io/recipes/gget/README.html) [Conda](https://anaconda.org/bioconda/gget/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/gget`](https://github.com//bioconda/bioconda-recipes/tree/bump/gget/recipes/gget) (click to view/edit other files)
Summary | gget enables efficient querying of genomic databases
Home | [https://github.com/pachterlab/gget](https://github.com/pachterlab/gget)
Releases |[https://github.com/pachterlab/gget/tags](https://github.com/pachterlab/gget/tags)
Recipe Maintainer(s) | @nh13, @lauraluebbert
Author | `@pachterlab`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by lauraluebbert** [comment]
Please also note the issue mentioned [here](https://github.com/bioconda/bioconda-recipes/pull/45356):

Error when installing gget using bioconda on OSX
```
Output in format: Requested package -> Available versionsThe following specifications were 
found to be incompatible with your system:
 - feature:/osx-64::__osx==10.16=0
 - feature:|@/osx-64::__osx==10.16=0
 - gget -> matplotlib-base -> __osx[version='>=10.11|>=10.12']
 ```

This error still occurs when trying to install gget from bioconda on OSX. Any suggested fixes are appreciated.

**Comment by martin-g** [comment]
@lauraluebbert  How to reproduce the error ?  How do you install it ? 
I ask because the installation and the tests pass successfully at Azure CI Mac OSX (Intel).

**Review by martin-g — APPROVED** [review]

**Comment by martin-g** [comment]
I've merged the PR because it does not introduce a regression with the new version.
@lauraluebbert Feel free to comment here or in a new issue/PR !

**Comment by lauraluebbert** [comment]
Hi @martin-g, the problem occurs when running `conda install bioconda::gget`. I tried Mac OSX Big Sur (v11.7.10) Intel (conda version 22.11.1) and MacOS Ventura 13.5.2 (22G91), ARM (M2 chip) (conda version 23.5.2) - the former resulting in the same error; the latter not being able to solve the environment. This error was pointed out to us by several other users encountering the same problem. 

According to one of our users: 
"we have encountered difficulties installing the package using Anaconda on macOS 14.1.1 even though every package is up-to-date in the conda environment.
```
Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your system:
 - feature:/osx-64::__osx==10.16=0
 - feature:|@/osx-64::__osx==10.16=0
 - gget -> matplotlib-base -> __osx[version='>=10.11|>=10.12']’
 ```
Installing the package with pip solved the issue but I suggest checking the conda environment."

Thank you!

On a side note: There will be another gget release today or tomorrow (and I will yank version 0.28.5 on pipy) because I accidentally introduced a breaking bug in one of the modules in this version that was not caught by our unit tests; sorry about that.

**Comment by lauraluebbert** [comment]
@martin-g No problem, do you have any idea what the error might be caused by?

**Pull request merged**
