### PR TITLE
New recipe: cgat-daisy - benchmarking system and combinatorial workflows

### PR DESCRIPTION
**Pull request by AndreasHeger**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

This recipe adds a benchmarking system to bioconda that has been used for variant caller benchmarking, but is generic to any problem where you need combinatorial workflows (data x tool x metric).

Documentation is here:
https://cgat-bench.readthedocs.io/en/latest/

Many thanks,
Andreas

### CODE REVIEW

**Comment by AndreasHeger** [comment]
Hi @npavlovikj , apologies for pinging you, but you kindly upgraded ruffus recently.
This PR has been sitting around for a while - is there a chance of it getting merged?

**Comment by AndreasHeger** [comment]
Hmm, there is a failure now, but this does not seem related to this package:

**Comment by AndreasHeger** [comment]
Hi @npavlovikj , many thanks for getting back. I merged with master and also based on a different tar-ball to add the missing LICENCE file. Thanks!

**Comment by npavlovikj** [comment]
Many thanks @AndreasHeger - I think the rebase did the magic :)

**Comment by AndreasHeger** [comment]
Many thanks, @npavlovikj

**Pull request merged**
