### PR TITLE
linux-aarch64 build for ac

### PR DESCRIPTION
**Pull request by huazhong28**
Describe your pull request here

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

### General instructions

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

### Instructions for avoiding API, ABI, and CLI breakage issues
Conda is able to record and lock (a.k.a. pin) dependency versions used at build time of other recipes.
This way, one can avoid that expectations of a downstream recipe with regards to API, ABI, or CLI are violated by later changes in the recipe.
If not already present in the meta.yaml, make sure to specify `run_exports` (see [here](https://bioconda.github.io/contributor/linting.html#missing-run-exports) for the rationale and comprehensive explanation).
Add a `run_exports` section like this:

```yaml
build:
  run_exports:
    - ...

```

with `...` being one of:

| Case                             | run_exports statement                                               |
| -------------------------------- | ------------------------------------------------------------------- |
| semantic versioning              | `{{ pin_subpackage("myrecipe", max_pin="x") }}`     |
| semantic versioning (0.x.x)      | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}`   |
| known breakage in minor versions | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| known breakage in patch versions | `{{ pin_subpackage("myrecipe", max_pin="x.x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| calendar versioning              | `{{ pin_subpackage("myrecipe", max_pin=None) }}`    |

while replacing `"myrecipe"` with either `name` if a `name|lower` variable is defined in your recipe or with the lowercase name of the package in quotes.

### Bot commands for PR management

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

Note that the <code>@BiocondaBot please merge</code> command is now depreciated. Please just squash and merge instead.

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by rpetit3** [comment]
@biocondabot please fetch artifacts

**Comment by rpetit3** [comment]
@huazhong28 do you have the ability to test on ARM machine?

**Comment by huazhong28** [comment]
> @huazhong28 do you have the ability to test on ARM machine?

yes, I have tested that.

**Review by martin-g — APPROVED** [review]

**Comment by martin-g** [comment]
```
 file bin/AC 
bin/AC: ELF 64-bit LSB pie executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, not stripped

mgrigorov in 🌐 euler-arm-22 in /tmp/ac 
❯ ./bin/AC 
Usage: AC [OPTION]... -r [FILE]  [FILE]:[...]                          
Compression of amino acid sequences.                                   
                                                                       
Non-mandatory arguments:                                               
                                                                       
  -h                     give this help,                               
  -s                     show AC compression levels,                   
  -v                     verbose mode (more information),              
  -V                     display version number,                       
  -f                     force overwrite of output,                    
  -l <level>             level of compression [1;7] (lazy -tm setup),  
  -t <threshold>         threshold frequency to discard from alphabet,
  -e                     it creates a file with the extension ".iae" 
                         with the respective information content.      
                                                                       
  -rm <c>:<d>:<g>/<m>:<e>:<a>  reference model (-rm 1:10:0.9/0:0:0),   
  -rm <c>:<d>:<g>/<m>:<e>:<a>  reference model (-rm 5:90:0.9/1:50:0.8),
  ...                                                                  
  -tm <c>:<d>:<g>/<m>:<e>:<a>  target model (-tm 1:1:0.8/0:0:0),       
  -tm <c>:<d>:<g>/<m>:<e>:<a>  target model (-tm 7:100:0.9/2:10:0.85), 
  ...                                                                  
                         target and reference templates use <c> for    
                         context-order size, <d> for alpha (1/<d>), <g>
                         for gamma (decayment forgetting factor) [0;1),
                         <m> to the maximum sets the allowed mutations,
                         on the context without being discarded (for   
                         deep contexts), under the estimator <e>, using
                         <a> for gamma (decayment forgetting factor)   
                         [0;1) (tolerant model),                       
                                                                       
  -r <FILE>              reference file ("-rm" are loaded here),     
                                                                       
Mandatory arguments:                                                   
                                                                       
  <FILE>:<...>:<...>     file to compress (last argument). For more    
                         files use splitting ":" characters.         
                                                                       
Example:                                                               
                                                                       
  [Compress]   ./AC -v -tm 1:1:0.8/0:0:0 -tm 5:20:0.9/3:20:0.9 seq.txt 
  [Decompress] ./AD -v seq.txt.co                                      
                                                                       
Report bugs to <{pratas,seyedmorteza,ap}@ua.pt>.               
```
LGTM!

**Comment by huazhong28** [comment]
@BiocondaBot please add label

**Pull request merged**
