### PR TITLE
Expansionhunter 2.5.5 (unblacklist)

### PR DESCRIPTION
**Pull request by apeltzer**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [x] This PR does something else (explain below).

Apparently expansionhunter was on the blacklist thus the 2.5.5 update yesterday didn't get uploaded. Since its both testing and building just fine, I just removed it from the blacklist and created this PR again, bumping build version too.

### CODE REVIEW

**Comment by dpryan79** [comment]
I have a feeling that the system gcc is getting used instead of the one that gets installed by conda. Likely this is incorrectly hard-coded some where in the build script.

**Comment by apeltzer** [comment]
> I have a feeling that the system gcc is getting used instead of the one that gets installed by conda. Likely this is incorrectly hard-coded some where in the build script.

Maybe in the imported JSON library? I'll have a look

**Comment by apeltzer** [comment]
Looks like they added JSON output in versions > 2.5, thus the library they use for this wasn't there in the (functional) 2.0.8 recipe. I'll have a look at the `json.hpp` file I found, this looks like it could be the reason for the breaking build.

**Comment by apeltzer** [comment]
Its this probably causing the error:
```
// exclude unsupported compilers
#if defined(__clang__)
    #if (__clang_major__ * 10000 + __clang_minor__ * 100 + __clang_patchlevel__) < 30400
        #error "unsupported Clang version - see https://github.com/nlohmann/json#supported-compilers"
    #endif
#elif defined(__GNUC__)
    #if (__GNUC__ * 10000 + __GNUC_MINOR__ * 100 + __GNUC_PATCHLEVEL__) < 40900
        #error "unsupported GCC version - see https://github.com/nlohmann/json#supported-compilers"
    #endif
#endif
```
I couldn't find a simple way to add this to the `Cmakelists.txt` unfortunately - any idea @dpryan79 ?

**Comment by dpryan79** [comment]
Don't know, cmake issues are always a pain :(

**Comment by apeltzer** [comment]
Ok, I'll try setting up the circleci local client and will figure something out hopefully :-/

**Pull request closed without merging**
