### PR TITLE
Compile FastTree with double precision

### PR DESCRIPTION
**Pull request by wasade**
* [x] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

Use double precision with FastTree. It defaults to single precision which can result in numerical stability issues. See concerns [here](http://darlinglab.org/blog/2015/03/23/not-so-fast-fasttree.html)

### CODE REVIEW

**Comment by bgruening** [comment]
@wasade can you please increase the build number as well. Thanks.

**Comment by bgruening** [comment]
Urgs. Now we have a real problem here. The checksum does not match anymore. Probably due to changes in the .c file which is not versioned. Can you please use cargo-port https://github.com/galaxyproject/cargo-port/ to backup this file. Include the new link here, increase the probably new version number and set the build number back to 0. Thanks.

**Comment by wasade** [comment]
Don't know what that is, so I just made the URL version specific. Same MD5. Sound good?

**Comment by bgruening** [comment]
If you find the old file that fits the checksum even better. The crucial part is to make the downloaded file sustainable. Cargo-port can help with this.

**Comment by wasade** [comment]
Right:

```bash
$ md5 FastTree-2.1.8.c
MD5 (FastTree-2.1.8.c) = c7e85689a26cabba241378d4f633c2fa
```

**Comment by bgruening** [comment]
Thanks @wasade!

**Pull request merged**
