### PR TITLE
Use `curl -L` for all bioconductor-org.*

### PR DESCRIPTION
**Pull request by bernt-matthias**
packages. Without one gets

```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>
<h1>Found</h1>
<p>The document has moved <a href="https://mghp.osn.xsede.org/bir190004-bucket01/archive.bioconductor.org/packages/3.14/data/annotation/src/contrib/org.At.tair.db_3.14.0.tar.gz">here</a>.</p>
<hr>
<address>Apache/2.4.18 (Ubuntu) Server at master.bioconductor.org Port 443</address>
</body></html>
```

and therefore a md5sum mismatch

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by bernt-matthias** [comment]
@bgruening .. seems that the depot links also do not work

**Comment by bernt-matthias** [comment]
@BiocondaBot please add label

**Comment by daler** [comment]
@bernt-matthias thanks. This has been mostly completed over in https://github.com/bioconda/bioconda-recipes/actions/runs/2867974566 using the `bulk` mechanism, which needs to be merged back in to master.

**Comment by bernt-matthias** [comment]
Thanks for the info @daler . Then I'm cling this one.

**Pull request closed without merging**
