### PR TITLE
Segmentation fold

### PR DESCRIPTION
**Pull request by yhoogstrate**
* [x] I have read the guidelines above.
* [x] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by yhoogstrate** [comment]
@johanneskoester do you why the check doesn't complete? Do I need to rebase with master?

**Comment by bgruening** [comment]
Seems like travis has problems.

**Comment by yhoogstrate** [comment]
@bgruening Travis is doing weird things. In the job that corresponds to `f03c76e` (https://travis-ci.org/bioconda/bioconda-recipes/jobs/203751037), it first runs a test for segmentation-fold as expected.

At line 257 it says:
```
INFO bioconda_utils.build:build_recipes(285): Building and testing 5 recipes in total
INFO bioconda_utils.build:build_recipes(286): Recipes to build: 
bioconductor-edaseq
abyss
picopore
segmentation-fold
lemon
```
Followed by a build for lemon at line 264:
```
INFO bioconda_utils.build:build_recipes(323): Building and testing subdag 0 of 1 (4 recipes)
INFO bioconda_utils.build:build(64): BIOCONDA BUILD START recipes/lemon, env: CONDA_BOOST=1.61;CONDA_GMP=5.1;CONDA_GSL=1.16;CONDA_HDF5=1.8.17;CONDA_NCURSES=5.9;CONDA_NPY=110;CONDA_PERL=5.22.0;CONDA_PY=27;CONDA_R=3.3.1
INFO bioconda_utils.build:build(122): BIOCONDA BUILD SUCCESS /anaconda/conda-bld/osx-64/lemon-1.3.1-0.tar.bz2, CONDA_BOOST=1.61;CONDA_GMP=5.1;CONDA_GSL=1.16;CONDA_HDF5=1.8.17;CONDA_NCURSES=5.9;CONDA_NPY=110;CONDA_PERL=5.22.0;CONDA_PY=27;CONDA_R=3.3.1
INFO bioconda_utils.build:build(139): BIOCONDA TEST START via mulled-build recipes/lemon, CONDA_BOOST=1.61;CONDA_GMP=5.1;CONDA_GSL=1.16;CONDA_HDF5=1.8.17;CONDA_NCURSES=5.9;CONDA_NPY=110;CONDA_PERL=5.22.0;CONDA_PY=27;CONDA_R=3.3.1
updating index in: /anaconda/conda-bld/osx-64
INFO bioconda_utils.build:build(145): BIOCONDA TEST SUCCESS recipes/lemon, CONDA_BOOST=1.61;CONDA_GMP=5.1;CONDA_GSL=1.16;CONDA_HDF5=1.8.17;CONDA_NCURSES=5.9;CONDA_NPY=110;CONDA_PERL=5.22.0;CONDA_PY=27;CONDA_R=3.3.1
INFO bioconda_utils.build:build(64): BIOCONDA BUILD START recipes/segmentation-fold, env: CONDA_BOOST=1.61;CONDA_GMP=5.1;CONDA_GSL=1.16;CONDA_HDF5=1.8.17;CONDA_NCURSES=5.9;CONDA_NPY=110;CONDA_PERL=5.22.0;CONDA_PY=27;CONDA_R=3.3.1
ERROR bioconda_utils.build:build(127): BIOCONDA BUILD FAILED recipes/segmentation-fold, 
```

Then later in the log file at line 723 it starts:
```
INFO bioconda_utils.build:build(64): BIOCONDA BUILD START recipes/picopore, env: CONDA_BOOST=1.61;CONDA_GMP=5.1;CONDA_GSL=1.16;CONDA_HDF5=1.8.17;CONDA_NCURSES=5.9;CONDA_NPY=110;CONDA_PERL=5.22.0;CONDA_PY=27;CONDA_R=3.3.1
ERROR bioconda_utils.build:build(127): BIOCONDA BUILD FAILED recipes/picopore, CONDA_BOOST=1.61;CONDA_GMP=5.1;CONDA_GSL=1.16;CONDA_HDF5=1.8.17;CONDA_NCURSES=5.9;CONDA_NPY=110;CONDA_PERL=5.22.0;CONDA_PY=27;CONDA_R=3.3.1
ERROR bioconda_utils.build:build(128): COMMAND: conda build --no-build-id --no-anaconda-upload --channel bioconda --channel r --channel defaults --channel conda-forge recipes/picopore
...
```
at line 781:
```
INFO bioconda_utils.build:build(64): BIOCONDA BUILD START recipes/bioconductor-edaseq, env: CONDA_BOOST=1.61;CONDA_GMP=5.1;CONDA_GSL=1.16;CONDA_HDF5=1.8.17;CONDA_NCURSES=5.9;CONDA_NPY=110;CONDA_PERL=5.22.0;CONDA_PY=27;CONDA_R=3.3.1
ERROR bioconda_utils.build:build(127): BIOCONDA BUILD FAILED recipes/bioconductor-edaseq, CONDA_BOOST=1.61;CONDA_GMP=5.1;CONDA_GSL=1.16;CONDA_HDF5=1.8.17;CONDA_NCURSES=5.9;CONDA_NPY=110;CONDA_PERL=5.22.0;CONDA_PY=27;CONDA_R=3.3.1
ERROR bioconda_utils.build:build(128): COMMAND: conda build --no-build-id --no-anaconda-upload --channel bioconda --channel r --channel defaults --channel conda-forge recipes/bioconductor-edaseq
ERROR bioconda_utils.build:build(129): STDOUT+STDERR: + source /anaconda/bin/activate /anaconda/conda-bld/_b_env_placehold_placehold_placehold_placehold_placehold_pla
+ mv DESCRIPTION DESCRIPTION.old
mv: rename DESCRIPTION to DESCRIPTION.old: No such file or directory
```

and it line 1045:
```
ERROR bioconda_utils.build:build_recipes(375): BIOCONDA BUILD SUMMARY: of 4 recipes, 3 failed and 0 were skipped. Details of recipes and environments follow.
ERROR bioconda_utils.build:build_recipes(381): BIOCONDA BUILD SUMMARY: while the entire build failed, the following recipes were built successfully:
recipes/lemon
```
Because these are PRs that are currently open, it looks like travis somehow merges open branches before testing?

**Comment by bgruening** [comment]
I think these PR are merged recently, are not yet on anaconda.org and ends up to be tested again. I discussed this with @johanneskoester recently and I think we should change that. It is confusing and wastes a lot of time.
However, if you rerun your test everything should be fine as most of the master brauch was build already and is not available on anaconda.org.

**Comment by yhoogstrate** [comment]
Thanks you for your assitance @bgruening

**Comment by bgruening** [comment]
puh ... cool!

**Comment by johanneskoester** [comment]
@bgruening I have thought about a solution in the last days. I think I have a good strategy now. I hope to be able to implement it tomorrow.

**Pull request merged**
