### PR TITLE
OGDF: 201207

### PR DESCRIPTION
**Pull request by CicoZhang**
* [x] I have read the guidelines above.
* [x] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

[OGDF](http://www.ogdf.net/doku.php) is a self-contained C++ class library for the automatic layout of diagrams. OGDF offers sophisticated algorithms and data structures to use within your own applications or scientific projects. The library is available under the GNU General Public License.

### CODE REVIEW

**Comment by CicoZhang** [comment]
@daler I have changed the style of version number, but it still fails to pass the linux platform. Conda-build works well locally (I am using Ubuntu 16.10) #3889

**Comment by acaprez** [comment]
I've run into this issue as well.  I'm fairly sure it's a bug in the way `conda-build` handles the `patches:` section of the `meta.yaml`.  Basically, if there's a single entry in the list that only applies to either Linux or OS X via preprocessing selectors, `conda-build` doesn't parse the "empty" list for the other OS properly and looks for a nonexistent patch file.  The workaround I found was to use the preprocessing selector for both the patch file line and the `patches:` line itself.  See for example the `meta.yaml` for [bioconductor-rhdf5](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/bioconductor-rhdf5/meta.yaml).

**Comment by CicoZhang** [comment]
@acaprez Cool. Thank you for the workaround for this naughty bug. :)  

@daler @bgruening  My problem is solved. It has passed.

**Comment by bgruening** [comment]
Cool! Then let's merge it.

**Pull request merged**
