### PR TITLE
Gimmemotifs build

### PR DESCRIPTION
**Pull request by simonvh**
* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [X] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [X] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by dpryan79** [comment]
I've had an initial go at thinning out the `host:` section, since I expect most of what was there isn't really needed for installation (you just need, python, setuptools and whatever C needs to link against). Please have a look at that and correct as needed.

**Comment by dpryan79** [comment]
`sklearn-contrib-lightning` hasn't been rebuilt for python 3.7 https://github.com/conda-forge/sklearn-contrib-lightning-feedstock/pull/7

Once that's done this can be built for python 3.7

**Comment by simonvh** [comment]
Thanks for looking at this @dpryan79!

**Comment by dpryan79** [comment]
Thanks @simonvh

**Pull request merged**
