### PR TITLE
Update simka to 1.5.3

### PR DESCRIPTION
**Pull request by cdeltel**
Fixes minor bugs and implements SonarQube diagnostics

### CODE REVIEW

**Comment by clemaitre** [comment]
@Bioconda/core could you Review and merge this PR ?
Thanks !

**Review by bgruening — COMMENTED** [review]
Could you please also fix the `license` field? Using https://spdx.org identifiers?

**Comment by cdeltel** [comment]
I updated the licence file.

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Pull request merged**
