### PR TITLE
Add skani 

### PR DESCRIPTION
**Pull request by bluenote-1577**
Adding the "skani" software, a fast ANI calculation method for metagenomic sequences, version 0.0.1.

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by bluenote-1577** [comment]
@BiocondaBot please add label

**Comment by aaronmussig** [comment]
@BiocondaBot please fetch artifacts

**Comment by aaronmussig** [comment]
@bluenote-1577 would you consider adding skani to crates.io? It would be a preferred way of installing it

**Comment by bluenote-1577** [comment]
@aaronmussig is there a reason to prefer cartes.io over conda? would adding to both work? I haven't personally used crates.io a lot but I know that having even a rust package of conda is helpful for folks who may want to have everything in their conda environment. 

I know that I've installed other rust packages on conda before and had a good experience, hence requesting adding skani to bioconda. Let me know if there's some context I'm missing.

**Comment by aaronmussig** [comment]
Sorry that was a bit of a rushed comment, I really needed to elaborate before hitting send.

I mean that instead of building from source, it could be preferred for some users to install the binary from crates.io (outside of conda). It's not a requirement for the bioconda recipe, and I'll be looking at reviewing the package shortly and getting it merged.

Thanks for writing this tool by the way, I'm keen to give it a go!

**Review by aaronmussig — APPROVED** [review]

**Comment by aaronmussig** [comment]
@BiocondaBot please merge

**Comment by bluenote-1577** [comment]
> Sorry that was a bit of a rushed comment, I really needed to elaborate before hitting send.
> 
> I mean that instead of building from source, it could be preferred for some users to install the binary from crates.io (outside of conda). It's not a requirement for the bioconda recipe, and I'll be looking at reviewing the package shortly and getting it merged.
> 
> Thanks for writing this tool by the way, I'm keen to give it a go!

Ah I see. I totally agree. I'l get it on crates io in the near future :).

**Pull request merged**
