### PR TITLE
Update CellRank numba version requirement

### PR DESCRIPTION
**Pull request by WeilerP**
Require `numba<0.53.0` due to theislab/scanpy#1756.

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by WeilerP** [comment]
@BiocondaBot please add label

**Comment by dlaehnemann** [comment]
Thanks for tracking this down. From the issue you reference (and the issues that references), it seems like this is a problem with `scanpy` and `scvelo`. So I would think it makes more sense to limit the version numbers there, because otherwise their respective installation won't work either when they pull in newer numba, right? And once they have this fixed, it should in turn be unnecessary, here. Or am I missing something important?

**Comment by WeilerP** [comment]
> Thanks for tracking this down. From the issue you reference (and the issues that references), it seems like this is a problem with `scanpy` and `scvelo`. So I would think it makes more sense to limit the version numbers there, because otherwise their respective installation won't work either when they pull in newer numba, right? And once they have this fixed, it should in turn be unnecessary, here. Or am I missing something important?

Yes, you are right, it should be fixed in `scanpy` as well, I guess. Will open a PR there as well. Thanks for pointing it out.
The reason I opened this PR is that the `numba` version is pinned [here](https://github.com/theislab/cellrank/blob/f4a08e62f9edb4d3e97f82c6129ad083d43cfd04/requirements.txt#L9) to the correct one in the CellRank repo as well. Using `pip install cellrank`, the correct version of `numba` is installed, `conda install -c conda-forge -c bioconda cellrank` installs `numba>=0.53.0`.
Any thoughts/preferences on this @michalk8?

**Comment by dlaehnemann** [comment]
Ah, I see. But I guess the same logic applies there. If it is properly pinned in the respective packages where the problem actually arises, a further pinning in cellrank should not be necessary?

Actually, from a quick look at scvelo, it seems that it also only indirectly uses numba through its scanpy dependency. So pinning it in scanpy in the following place and here on bioconda should do the trick, I think:
https://github.com/theislab/scanpy/blob/bcfa925f6941ab30395e56ef6d2aedef8e16a563/pyproject.toml#L61

**Comment by michalk8** [comment]
@WeilerP
In general, this is `umap-learn` issue. I've played around the versions, seems to have been fixed in `umap==0.5.1`:
```python
import numba as nb
import umap
print(nb.__version__)  # 0.53.{0,1}
print(umap.__version__)  # 0.5.1
```
I'm fine with pinning`numba` in `scanpy` only. While we're at the topic of `umap-learn`, I'd also consider unpinning the upper bound on `umap-learn` in `scVelo`, see [here](https://github.com/theislab/scvelo/commit/b5d8063dda94192616d19236c38dfa8acfb40b24#diff-4d7c51b1efe9043e44439a949dfd92e5827321b34082903477fd04876edb7552) (should no longer be needed).

**Comment by WeilerP** [comment]
Sounds good to me. The reason I opened this PR was that `pip install cellrank` and `conda install -c conda-forge -c bioconda cellrank` behave the same way.

I'll close this then and discuss it further in the scanpy issue. Thanks for pointing out the `umap-learn` version used in `scvelo`! I actually already removed the upper bound - it's only on `develop` for now and hasn't been merged into `master` yet.

**Pull request closed without merging**
