### PR TITLE
Added dependency for LOFTEE from github repo

### PR DESCRIPTION
**Pull request by matthdsm**
* [x] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by bgruening** [comment]
Please increase the build number.
Thanks!

**Comment by matthdsm** [comment]
Updated VEP version to v84

**Comment by bgruening** [comment]
Looks like `File/Copy/Recursive.pm` is missing :(

**Comment by matthdsm** [comment]
Hi Björn,

I'm going to need some advice now. Since there's a missing perl module, I'm going to have to add this to the dependecies in meta.yaml file. the package perl-file-copy-recursive is available in the `dan_blanchard`channel. I probably can't just add the package to meta.yaml can I?

Do I add the channel (and how?) or do I create a conda recipe for the perl package and submit it to bioconda? I've already generated a recipe by doing `conda skeleton cpan File::Copy::Recursive `, so submitting shouldn't be an issue I guess?

I realize my way of working is less than ideal, but I can't set up a test environment right now.

Cheers,
Matthias

**Comment by bgruening** [comment]
@matthdsm you need to add this recipe to bioconda as we only have dependency to `r` and `default`. The package generated from skeleton should be correct. You just need to replace `perl` with `perl-threaded` and maybe clean up the meta.yaml file a little bit.

A complete test environment you can find in the bioconda Docker container but for this package a `conda build` is probably enough for a first local test.

Hope this helps!
Bjoern

**Comment by matthdsm** [comment]
I made a new pull request with the perl dependency (#1517). once that one gets accepted, I'll further adjust this one.

**Comment by bgruening** [comment]
@matthdsm for the future you can add all this into one PR. Bioconda is smart enough to figure the dependency out.

**Pull request closed without merging**
