### PR TITLE
cutadapt: add linux-aarch64 build

### PR DESCRIPTION
**Pull request by martin-g**
Describe your pull request here

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

### General instructions

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

### Instructions for avoiding API, ABI, and CLI breakage issues
Conda is able to record and lock (a.k.a. pin) dependency versions used at build time of other recipes.
This way, one can avoid that expectations of a downstream recipe with regards to API, ABI, or CLI are violated by later changes in the recipe.
If not already present in the meta.yaml, make sure to specify `run_exports` (see [here](https://bioconda.github.io/contributor/linting.html#missing-run-exports) for the rationale and comprehensive explanation).
Add a `run_exports` section like this:

```yaml
build:
  run_exports:
    - ...

```

with `...` being one of:

| Case                             | run_exports statement                                               |
| -------------------------------- | ------------------------------------------------------------------- |
| semantic versioning              | `{{ pin_subpackage("myrecipe", max_pin="x") }}`     |
| semantic versioning (0.x.x)      | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}`   |
| known breakage in minor versions | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| known breakage in patch versions | `{{ pin_subpackage("myrecipe", max_pin="x.x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| calendar versioning              | `{{ pin_subpackage("myrecipe", max_pin=None) }}`    |

while replacing `"myrecipe"` with either `name` if a `name|lower` variable is defined in your recipe or with the lowercase name of the package in quotes.

### Bot commands for PR management

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

Note that the <code>@BiocondaBot please merge</code> command is now depreciated. Please just squash and merge instead.

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by martin-g** [comment]
@BiocondaBot please fetch artifacts

**Comment by martin-g** [comment]
```

mgrigorov in 🌐 euler-arm-22 in /tmp/cutadapt took 4s 
❯ tar jxvf cutadapt-4.7-py39h898dc92_1.tar.bz2 
info/run_exports.json
info/test/run_test.sh
info/test/run_test.py
info/hash_input.json
info/has_prefix
info/index.json
info/licenses/LICENSE
info/recipe/meta.yaml.template
info/recipe/meta.yaml
info/files
info/recipe/conda_build_config.yaml
info/about.json
info/paths.json
info/git
lib/python3.9/site-packages/cutadapt/__init__.py
lib/python3.9/site-packages/cutadapt/__main__.py
lib/python3.9/site-packages/cutadapt/_version.py
lib/python3.9/site-packages/cutadapt/tokenizer.py
lib/python3.9/site-packages/cutadapt/statistics.py
lib/python3.9/site-packages/cutadapt/json.py
lib/python3.9/site-packages/cutadapt/log.py
lib/python3.9/site-packages/cutadapt/_match_tables.py
lib/python3.9/site-packages/cutadapt/utils.py
lib/python3.9/site-packages/cutadapt/pipeline.py
lib/python3.9/site-packages/cutadapt/predicates.py
lib/python3.9/site-packages/cutadapt/align.py
lib/python3.9/site-packages/cutadapt/kmer_heuristic.py
lib/python3.9/site-packages/cutadapt/files.py
lib/python3.9/site-packages/cutadapt/runners.py
lib/python3.9/site-packages/cutadapt/steps.py
lib/python3.9/site-packages/cutadapt/parser.py
lib/python3.9/site-packages/cutadapt/modifiers.py
lib/python3.9/site-packages/cutadapt/report.py
lib/python3.9/site-packages/cutadapt/adapters.py
lib/python3.9/site-packages/cutadapt/cli.py
bin/cutadapt
lib/python3.9/site-packages/cutadapt/info.pyi
lib/python3.9/site-packages/cutadapt/_kmer_finder.pyi
lib/python3.9/site-packages/cutadapt/qualtrim.pyi
lib/python3.9/site-packages/cutadapt/_align.pyi
lib/python3.9/site-packages/cutadapt/_kmer_finder.cpython-39-aarch64-linux-gnu.so
lib/python3.9/site-packages/cutadapt/info.cpython-39-aarch64-linux-gnu.so
lib/python3.9/site-packages/cutadapt/qualtrim.cpython-39-aarch64-linux-gnu.so
lib/python3.9/site-packages/cutadapt/_align.cpython-39-aarch64-linux-gnu.so
lib/python3.9/site-packages/cutadapt-4.7.dist-info/top_level.txt
lib/python3.9/site-packages/cutadapt-4.7.dist-info/entry_points.txt
lib/python3.9/site-packages/cutadapt-4.7.dist-info/INSTALLER
lib/python3.9/site-packages/cutadapt-4.7.dist-info/WHEEL
lib/python3.9/site-packages/cutadapt-4.7.dist-info/LICENSE
lib/python3.9/site-packages/cutadapt-4.7.dist-info/METADATA
lib/python3.9/site-packages/cutadapt-4.7.dist-info/RECORD
lib/python3.9/site-packages/cutadapt-4.7.dist-info/REQUESTED
lib/python3.9/site-packages/cutadapt/__pycache__/__init__.cpython-39.pyc
lib/python3.9/site-packages/cutadapt/__pycache__/__main__.cpython-39.pyc
lib/python3.9/site-packages/cutadapt/__pycache__/_version.cpython-39.pyc
lib/python3.9/site-packages/cutadapt/__pycache__/tokenizer.cpython-39.pyc
lib/python3.9/site-packages/cutadapt/__pycache__/log.cpython-39.pyc
lib/python3.9/site-packages/cutadapt/__pycache__/json.cpython-39.pyc
lib/python3.9/site-packages/cutadapt/__pycache__/statistics.cpython-39.pyc
lib/python3.9/site-packages/cutadapt/__pycache__/_match_tables.cpython-39.pyc
lib/python3.9/site-packages/cutadapt/__pycache__/utils.cpython-39.pyc
lib/python3.9/site-packages/cutadapt/__pycache__/pipeline.cpython-39.pyc
lib/python3.9/site-packages/cutadapt/__pycache__/align.cpython-39.pyc
lib/python3.9/site-packages/cutadapt/__pycache__/kmer_heuristic.cpython-39.pyc
lib/python3.9/site-packages/cutadapt/__pycache__/predicates.cpython-39.pyc
lib/python3.9/site-packages/cutadapt/__pycache__/files.cpython-39.pyc
lib/python3.9/site-packages/cutadapt/__pycache__/parser.cpython-39.pyc
lib/python3.9/site-packages/cutadapt/__pycache__/runners.cpython-39.pyc
lib/python3.9/site-packages/cutadapt/__pycache__/steps.cpython-39.pyc
lib/python3.9/site-packages/cutadapt/__pycache__/report.cpython-39.pyc
lib/python3.9/site-packages/cutadapt/__pycache__/modifiers.cpython-39.pyc
lib/python3.9/site-packages/cutadapt/__pycache__/cli.cpython-39.pyc
lib/python3.9/site-packages/cutadapt/__pycache__/adapters.cpython-39.pyc
lib/python3.9/site-packages/cutadapt-4.7.dist-info/direct_url.json

mgrigorov in 🌐 euler-arm-22 in /tmp/cutadapt 
❯ file bin/cutadapt 
bin/cutadapt: POSIX shell script, ASCII text executable

mgrigorov in 🌐 euler-arm-22 in /tmp/cutadapt 
❯ file bin/cutadapt lib/python3.9/site-packages/cutadapt/*.so
bin/cutadapt:                                                                      POSIX shell script, ASCII text executable
lib/python3.9/site-packages/cutadapt/_align.cpython-39-aarch64-linux-gnu.so:       ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, not stripped
lib/python3.9/site-packages/cutadapt/_kmer_finder.cpython-39-aarch64-linux-gnu.so: ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, not stripped
lib/python3.9/site-packages/cutadapt/info.cpython-39-aarch64-linux-gnu.so:         ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, not stripped
lib/python3.9/site-packages/cutadapt/qualtrim.cpython-39-aarch64-linux-gnu.so:     ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, not stripped

mgrigorov in 🌐 euler-arm-22 in /tmp/cutadapt 
❯ ./bin/cutadapt --help
./bin/cutadapt: line 2: /opt/conda/conda-bld/cutadapt_1710765669259/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python: No such file or directory
```

The binaries look OK!
But I am not sure about the shebang in the script.

**Comment by martin-g** [comment]
@BiocondaBot please add label

**Comment by bernt-matthias** [comment]
The placeholders should be fixed during installation. You could test this by installing the package locally from the artifacts.

**Comment by martin-g** [comment]
```
mgrigorov in 🌐 euler-arm-22 in /tmp/cutadapt via 🅒 font-ubuntu 
❯ conda install ./cutadapt-4.7-py39h898dc92_1.tar.bz2                                                                                                                                                  (font-ubuntu) 
Retrieving notices: ...working... done

Downloading and Extracting Packages
                                                                                                                                                                                                                     

Downloading and Extracting Packages

Preparing transaction: done
Verifying transaction: done
Executing transaction: done

mgrigorov in 🌐 euler-arm-22 in /tmp/cutadapt via 🅒 font-ubuntu took 5s 
❯ which cutadapt                                                                                                                                                                                       (font-ubuntu) 
/home/mgrigorov/miniconda3/envs/font-ubuntu/bin/cutadapt

mgrigorov in 🌐 euler-arm-22 in /tmp/cutadapt via 🅒 font-ubuntu 
❯ head /home/mgrigorov/miniconda3/envs/font-ubuntu/bin/cutadapt                                                                                                                                        (font-ubuntu) 
#!/bin/sh
'''exec' /home/mgrigorov/miniconda3/envs/font-ubuntu/bin/python "$0" "$@"
' '''
# -*- coding: utf-8 -*-
import re
import sys
from cutadapt.cli import main_cli
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main_cli())
```

Thanks, @bernt-matthias !

**Review by bernt-matthias — APPROVED** [review]

**Pull request merged**
