### PR TITLE
Add CPAN module Text::LevenshteinXS

### PR DESCRIPTION
**Pull request by AlexanderDilthey**
* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [X] This PR adds a new recipe.
* [X] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by AlexanderDilthey** [comment]
Hi @bioconda/core,
Any advice on why the tests for this recipe are failing? Error message is `/home/conda/feedstock_root/build_artifacts/perl_1548813468557/_build_env/bin/x86_64-conda_cos6-linux-gnu-gcc: No such file or directory`?

**Comment by bgruening** [comment]
It seems that perl is looning into the wrong directory `/home/conda/feedstock_root/build_artifacts/perl_1548813468557/_build_env/bin/x86_64-conda_cos6-linux-gnu-gcc`.

@bioconda/perl any idea?

**Comment by abretaud** [comment]
The error comes from this issue in the perl package: https://github.com/conda-forge/perl-feedstock/issues/29

**Comment by abretaud** [comment]
Copied this into https://github.com/bioconda/bioconda-recipes/pull/14506 as the branch is no longer available

**Pull request closed without merging**
