### PR TITLE
Add smeg

### PR DESCRIPTION
**Pull request by aemiol**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by mbargull** [comment]
I cancelled the build since it's taking way too long. Please check locally which test command is taking so long to finish. Also, please note that it is highly preferred that the test commands in `meta.yaml` check as much as possible but in as few time as possible, too. Ideally, those tests should be finished in seconds, and at most they should take few minutes.

**Comment by mbargull** [comment]
I just now saw that this has a few R dependencies, which could also mean that `conda` is just slow in creating the environment here. If that is the case, then maybe after we implement https://github.com/bioconda/bioconda-utils/pull/334 thing will be faster.

**Comment by mbargull** [comment]
> Does the conda-forge channel now have a higher priority than bioconda?

Not quite yet, but soon. We need to (in that order)
1. merge https://github.com/bioconda/bioconda-utils/pull/334
2. tag a new `bioconda-utils` release
3. merge https://github.com/bioconda/bioconda-recipes/pull/10924

Your PR is currently blocked by that process, sorry for the inconvenience.

**Comment by aemiol** [comment]
Ok. Thanks

**Comment by aemiol** [comment]
@mbargull I traced the problem to a single package (r-wgcna) which is in the bioconda channel so I dont think the new changes should matter to my recipe. The build-test was completed in about 30 min

**Pull request closed without merging**
