### PR TITLE
bioconductor-methylumi

### PR DESCRIPTION
**Pull request by tina-r**
* [x ] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ x] This PR adds a new recipe.
* [x ] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

Work in progress

### CODE REVIEW

**Comment by jenzopr** [comment]
The `bioconductor-fdb.infiniummethylation.hg19` run requirement is missing in bioconda. Although, it's present in other channels (e.g. see [here](https://anaconda.org/search?q=infiniummethylation)). Can we rely on those or bring it into bioconda? If so, I would like to assist here.
Best - J.

**Comment by bgruening** [comment]
Bring it into bioconda :) The skeleton generator for bioconductor should create packages with a post-link script to download the data.

**Comment by jenzopr** [comment]
@bgruening - this is ready for merging now. If nothing speaks against it from your side, I'll merge it?

**Comment by bgruening** [comment]
Nice, thanks a lot!

**Pull request merged**
