### PR TITLE
Add sainsc recipe

### PR DESCRIPTION
**Pull request by niklasmueboe**
add a recipe for sainsc to bioconda

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

### General instructions

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

### Instructions for avoiding API, ABI, and CLI breakage issues
Conda is able to record and lock (a.k.a. pin) dependency versions used at build time of other recipes.
This way, one can avoid that expectations of a downstream recipe with regards to API, ABI, or CLI are violated by later changes in the recipe.
If not already present in the meta.yaml, make sure to specify `run_exports` (see [here](https://bioconda.github.io/contributor/linting.html#missing-run-exports) for the rationale and comprehensive explanation).
Add a `run_exports` section like this:

```yaml
build:
  run_exports:
    - ...

```

with `...` being one of:

| Case                             | run_exports statement                                               |
| -------------------------------- | ------------------------------------------------------------------- |
| semantic versioning              | `{{ pin_subpackage("myrecipe", max_pin="x") }}`     |
| semantic versioning (0.x.x)      | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}`   |
| known breakage in minor versions | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| known breakage in patch versions | `{{ pin_subpackage("myrecipe", max_pin="x.x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| calendar versioning              | `{{ pin_subpackage("myrecipe", max_pin=None) }}`    |

while replacing `"myrecipe"` with either `name` if a `name|lower` variable is defined in your recipe or with the lowercase name of the package in quotes.

### Bot commands for PR management

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

Note that the <code>@BiocondaBot please merge</code> command is now depreciated. Please just squash and merge instead.

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by niklasmueboe** [comment]
@bioconda/core 
I might need some hep with this. I am not quite sure why the build on osx fails. Is it build on the native platform? For pypi I do precompile it for macosx_13 and macosx_14 and that works fine.

**Comment by martin-g** [comment]
```
2024-08-06T14:31:48.3844660Z 14:31:47 [32mBIOCONDA INFO[0m (ERR)   Copying rust artifact from target/x86_64-apple-darwin/release/lib_utils_rust.dylib to build/lib.macosx-10.13-x86_64-cpython-312/sainsc/_utils_rust.cpython-312-darwin.so
```
This looks suspicious! 
`.dylib` (OSX library) is renamed to `.so` (Linux dynamic library)

**Comment by niklasmueboe** [comment]
Hmm, to be honest I don't have much experience with this.

I am using [PyO3](https://github.com/PyO3/pyo3) to build a rust extension and the installation is done using the [setuptools-rust](https://github.com/PyO3/setuptools-rust) plugin for setuptools.

In the PyO3 documentation this behaviour is documented under manual builds (s. [here](https://pyo3.rs/v0.22.2/building-and-distribution#manual-builds)), so I assume setuptools-rust is doing that automatically and it is likely not the issue here.

**Comment by niklasmueboe** [comment]
@bioconda/core

Are there any other hints what the issue might be?

**Comment by niklasmueboe** [comment]
Would it be an option to skip osx builds for now with `skip: True  # [osx]`? 

I can't really seem to figure out what the issue is there.

**Comment by martin-g** [comment]
Sure!

**Review by martin-g — APPROVED** [review]

**Pull request merged**
