### PR TITLE
Add twobitreader

### PR DESCRIPTION
**Pull request by dpryan79**
* [X] I have read the guidelines above.
* [X] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

This is useful for accessing .2bit files and, unlike bx-python, works under python3.

@bioconda/core: Can someone have a look and give a :+1:?

### CODE REVIEW

**Comment by bgruening** [comment]
:+1: but not bioconda core.
@johanneskoester I'm allowed to merge this?

**Comment by johanneskoester** [comment]
@bgruening, in fact you are in the core for some weeks already. Maybe I forgot to tell you :-). I thought I'd honor the enourmous amounts of work you put into this.

**Comment by dpryan79** [comment]
Thanks @johanneskoester (also for making @bgruening part of core)!

**Comment by bgruening** [comment]
@johanneskoester Uh, I didn't know :) Thanks a lot!

**Pull request merged**
