### PR TITLE
Add missing dependency (missing from gensim 4.3.0)

### PR DESCRIPTION
**Pull request by florian-huber**
Seems like `FuzzyTM` is part of gensim's dependencies but still not installed (maybe missing from the conda recipe?).
So I added it to the spec2vec dependencies to pass the tests.

### CODE REVIEW

**Comment by bgruening** [comment]
Florian if you need a new build you need to bump the build number.

**Comment by florian-huber** [comment]
@bgruening I thought that because https://github.com/bioconda/bioconda-recipes/pull/38683 wasn't merged the build for 0.7.0 would still be `0`?
(if not I will of course bump the number)

**Comment by hechth** [comment]
@florian-huber I'm working on getting the new gensim dependencies into conda (https://github.com/conda-forge/staged-recipes/pull/21712) and (https://github.com/conda-forge/staged-recipes/pull/21711) + 3 more packages until we have everything it seems for FuzzyTM. If spec2vec still works with the lower versions that is good for now, but it would be good to have the option to update in the future anyway.

Maybe we have to bump the build number since only the PR got renamed?

**Comment by bgruening** [comment]
@florian-huber but then you need to take the changes from https://github.com/bioconda/bioconda-recipes/pull/38683 over here.

**Comment by bgruening** [comment]
See also https://github.com/conda-forge/staged-recipes/pull/21824

**Comment by bgruening** [comment]
We need to wait for conda-forge and then we will start here again. Thanks @florian-huber

**Pull request closed without merging**
