### PR TITLE
Update `pyhmmer` recipe to `v0.10.7` and run integrated unit tests

### PR DESCRIPTION
**Pull request by althonos**
This PR updates the recipe for `pyhmmer` to:

- execute the integrated unit tests. 
- set the run export to `max_pin="x.x"` since the package follows semantic versioning but is in `0.x.x` phase.

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

### General instructions

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

### Instructions for avoiding API, ABI, and CLI breakage issues
Conda is able to record and lock (a.k.a. pin) dependency versions used at build time of other recipes.
This way, one can avoid that expectations of a downstream recipe with regards to API, ABI, or CLI are violated by later changes in the recipe.
If not already present in the meta.yaml, make sure to specify `run_exports` (see [here](https://bioconda.github.io/contributor/linting.html#missing-run-exports) for the rationale and comprehensive explanation).
Add a `run_exports` section like this:

```yaml
build:
  run_exports:
    - ...

```

with `...` being one of:

| Case                             | run_exports statement                                               |
| -------------------------------- | ------------------------------------------------------------------- |
| semantic versioning              | `{{ pin_subpackage("myrecipe", max_pin="x") }}`     |
| semantic versioning (0.x.x)      | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}`   |
| known breakage in minor versions | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| known breakage in patch versions | `{{ pin_subpackage("myrecipe", max_pin="x.x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| calendar versioning              | `{{ pin_subpackage("myrecipe", max_pin=None) }}`    |

while replacing `"myrecipe"` with either `name` if a `name|lower` variable is defined in your recipe or with the lowercase name of the package in quotes.

### Bot commands for PR management

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

Note that the <code>@BiocondaBot please merge</code> command is now depreciated. Please just squash and merge instead.

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by daler** [comment]
@althonos in general we do not have resources to run unit tests (see [here](https://bioconda.github.io/contributor/guidelines.html#tests)). In addition, the goal of running tests in the isolated container (mulled-test) is to ensure no leakage from system libraries. This means that anything used in tests must come from the package itself or its formal dependencies -- so the test-specific dependency `importlib_resources` wouldn't make it into the container. That's probably what's happening [at this line](https://dev.azure.com/bioconda/bioconda-recipes/_build/results?buildId=51551&view=logs&j=e14e69ff-a0ae-55c4-b71d-229b239cfb2f&t=4dddc55b-10bc-50fc-ac68-7ff899b7a030&l=4819).

**Comment by althonos** [comment]
@daler the reason I wanted to have the unit tests is because the package being Cython with some hacks here and there for platform specific support, so I would be more confident with running the tests before shipping.

I changed the tests internally to avoid running those which need `importlib.resources` when it's not available, but I forgot two of them, that's why the build still fails. Removing the `importlib-resources` backport from the test dependencies should be fine and I expect the CI to pass with the next release, but I have yet to make one 👍

**Comment by daler** [comment]
That makes sense. I guess you are planning on holding off on this recipe until the next release then?

**Comment by althonos** [comment]
Yes that was the plan, but I can make a small patch release if that's better 👍

**Comment by daler** [comment]
Makes no difference; I was just passing through trying to debug failing tests, but sounds like this is a known issue and you have a plan so I'll move on ;)

**Comment by althonos** [comment]
@BiocondaBot please add label

**Comment by mencian** [comment]
LGTM, thanks @althonos!

**Review by mencian — APPROVED** [review]

**Pull request merged**
