### PR TITLE
Update GeneRax to v2.0.4

### PR DESCRIPTION
**Pull request by BenoitMorel**
Update GeneRax to v2.0.4 (includes several bug fixes)

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by BenoitMorel** [comment]
@BiocondaBot please add label

**Comment by rpetit3** [comment]
Hi @BenoitMorel, just curious is there a reason this recipe doesn't use the releases? If no reason, would you be ok if we updated it to use the releases so that it will be automatically updated in the future?

**Comment by BenoitMorel** [comment]
Hi @rpetit3,
What do you mean by using the releases? Is it possible to automatically update the package every time I add a new release, without going through the update process?
Thanks,
Benoit

**Comment by rpetit3** [comment]
If we were able to use https://github.com/BenoitMorel/GeneRax/archive/refs/tags/2.0.4.tar.gz, the BiocondaBot would recognize new releases and create a PR.

For GeneRax, are the submodules required for the Conda build? (I think yes, but wanted to check)

I'm going to go ahead and approve this one, but would you want to work together to see if we can get this to a point it's automatically updated for you?

**Review by rpetit3 — APPROVED** [review]

**Comment by rpetit3** [comment]
@biocondabot please merge

**Comment by BenoitMorel** [comment]
@rpetit3 yes the submodules are required.

 If I remember correctly, I have two problems to create a proper release (with binaries)
- github does not properly handle submodules when building releases
- GeneRax depends on MPI, and if I build a binary with a given MPI installation, users then need to have the same installation on their system.

I will discuss this with my colleagues because they have very similar issues with their projects.

**Pull request merged**
