### PR TITLE
Update ucsc-cell-browser to 1.0.0

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`ucsc-cell-browser`](https://bioconda.github.io/recipes/ucsc-cell-browser/README.html): **0.7.15** &rarr; **1.0.0**

[install with bioconda](http://bioconda.github.io/recipes/ucsc-cell-browser/README.html) [Conda](https://anaconda.org/bioconda/ucsc-cell-browser/files)

Info | Link
-----|-----
Recipe | [`recipes/ucsc-cell-browser`](https://github.com//bioconda/bioconda-recipes/tree/bump/ucsc_cell_browser/recipes/ucsc-cell-browser) (click to view/edit other files)
Releases |[https://pypi.org/pypi/cellbrowser/json](https://pypi.org/pypi/cellbrowser/json)

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Review by mbargull — COMMENTED** [review]
test comment

**Review by mbargull — CHANGES_REQUESTED** [review]
test request changes

**Review by mbargull — APPROVED** [review]

**Review by mbargull — DISMISSED** [review]
test request changes 2

**Review by mbargull — COMMENTED** [review]
test approve

**Review by mbargull — DISMISSED** [review]
test approve 2

**Comment by pcm32** [comment]
Please let me test locally the conda artifact.

**Comment by mbargull** [comment]
@pcm32, yes, gladly, thank you! Is it possible to run some of those tests (reasonably) fast during our CI jobs, i.e., adding them to `test/commands` in `meta.yaml` or `run_test.py`?

(and sorry, never mind the review things here -- just needed a random PR to test things out ;).)

**Comment by pcm32** [comment]
UCSC Cell Browser can use pandas to improve execution and scanpy for certain optional tasks. I think we can add them safely here. I didn't want to do this in the past to drag additional dependencies, but that was back then when I wasn't aware that it would try to use pandas if available. Since we are already adding AnnData and Numpy, we might as well install Scanpy to get all these deps and satisfy as well the optional scanpy calls.

**Comment by pcm32** [comment]
@mbargull it would be great to add those tests (and then I don't need to run them!). I normally struggle here with getting reasonably small file sizes for the anndata/seurat files to run the conversions to CellBrowser.

**Comment by pcm32** [comment]
...mmm.. while the build is using scanpy 1.7.2 (what I would expect), this is using scanpy 1.4.2 when installing locally through mamba:

```
mamba create -n __ucsc-cell-browser@1.0.0 -c https://150733-42372094-gh.circle-artifacts.com/0/tmp/artifacts/packages ucsc-cell-browser
```

```
scanpy                    1.4.2  py_0                    bioconda/noarch                                                               2 MB
```

should I pin scanpy to >1.7.0

**Comment by pcm32** [comment]
Having pandas and Scanpy triggers this issue for us https://github.com/maximilianh/cellBrowser/pull/217 so I will revert and only use Scanpy/Pandas once this is sorted. But I need this to be merged / released with out Scanpy/Pandas as we have a training next week using this.

**Comment by mbargull** [comment]
> should I pin scanpy to >1.7.0?

If this needs a certain minimum version, then yes, definitely add it. If not, then no.
The solver just chose to install `python=3.9` but a `scanpy` dependency had not been rebuild for Python 3.9 yet: https://github.com/conda-forge/umap-learn-feedstock/pull/28

**Review by pcm32 — APPROVED** [review]
I have checked this and it working to satisfaction.

**Comment by mbargull** [comment]
@BiocondaBot, please merge

**Pull request merged**
