### PR TITLE
Add ONCOCNV

### PR DESCRIPTION
**Pull request by marrip**
Add [ONCOCNV](https://github.com/BoevaLab/ONCOCNV/) to bioconda.

* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by marrip** [comment]
@bioconda/r 

Hey, I get this error for the action `test_linux test_linux` and wondering what it means:

```bash
Mamba failed to solve:
 - r-pscbs
 - r-cwhmisc
 - perl 5.32.1.*
 - r-base 4.1.*
 - r-scales
 - r-fastica
 - bioconductor-dnacopy
 - r-mclust
 - r-cghseg
 - r-mass
 - r-digest

with channels:

The reported errors are:
- Encountered problems while solving:
-   - package r-cghseg-1.0.5-r41h3121a25_0 requires r-base >=4.1,<4.2.0a0, but none of the providers can be installed
```

I build the `r-cghseg` package and it does not require this specific r-base version so I am a bit confused where this dependency is coming from. Thank you for any advice or pointers 🙂

**Comment by marrip** [comment]
@bioconda/core

**Comment by marrip** [comment]
I think I figured it out. Somehow, the package `r-cghseg` required a higher version of `r-base` because none was specified. I changed that which hopefully will fix the issue with this PR.

**Comment by dpryan79** [comment]
The issue appears to be that r-cwhmisc is missing from here and conda-forge. It was removed from CRAN earlier in the year, so adding it to conda-forge would be...difficult. Maybe you can find the original repository on github somewhere?

**Comment by marrip** [comment]
I found the package [here](https://anaconda.org/r/r-cwhmisc) as part of the `r`-channel. Could I use that instead? I also experienced problems with `r-cghseg` but I am trying to fix that atm.

**Comment by dpryan79** [comment]
Unfortunately the "r" channel is pretty old and deprecated by Anaconda, so it won't end up being compatible.

**Comment by dpryan79** [comment]
Let's see if the update to R 4.2 fixes this, since I rebuilt r-cghseg as part of that (didn't even know we packaged it...)

**Comment by dpryan79** [comment]
Ah, sorry, it's `r-cwhmisc` that needs to be added.

**Comment by marrip** [comment]
@BiocondaBot please add label

**Comment by marrip** [comment]
@BiocondaBot please fetch artifacts

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@BiocondaBot please merge

**Comment by marrip** [comment]
@dpryan79 Thank you for all your help ☺️

**Pull request merged**
