### PR TITLE
Add Taco-0.7.0 recipe

### PR DESCRIPTION
**Pull request by upendrak**
* [x] I have read the guidelines above.
* [x] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by upendrak** [comment]
@bgruening can you please let me where the problem is with the build? Thanks

**Comment by bgruening** [comment]
It seems to be a precompiled binary, isn't it? T his binary is not able to run on old systems and complains about missing libraries. Can you compile it?

**Comment by upendrak** [comment]
Yes it is a precompiled binary and i tested it thoroughly on linux and it worked great. Can we install the missing libraries and then rebuild it. I am getting all sorts of errors when i compile it.

**Comment by bgruening** [comment]
Solved in https://github.com/bioconda/bioconda-recipes/pull/3851

**Pull request closed without merging**
