### PR TITLE
Add recipe for scAR

### PR DESCRIPTION
**Pull request by fgypas**
Add recipe for [scAR](https://github.com/Novartis/scAR). It has two build versions. One for cpu and one for gpu, based on the pytorch-mutex metapackage.

### CODE REVIEW

**Comment by fgypas** [comment]
I am having some issue with the current recipe. Locally I can install the package based on the following meta.yaml files.

In case of CPUs
```
name: scAR
channels:
- nvidia
- pytorch
- conda-forge
dependencies:
- conda-forge::python>=3.8.6
- nvidia::cudatoolkit>=11.1
- pytorch::pytorch>=1.10.0
- pytorch::torchvision>=0.9.0
- pytorch::torchaudio>=0.8.0
- pytorch-mutex=*=cpu
- conda-forge::tqdm>=4.62.3
- conda-forge::pandas>=1.3.4
- conda-forge::seaborn>=0.11.2
- conda-forge::tensorboard>=2.2.1
- conda-forge::scikit-learn>=1.0.1
- conda-forge::anndata
- conda-forge::scanpy
- conda-forge::pyro-ppl>=1.8.0
- conda-forge::pip
- pip:
  - .
```

In case of GPU:
```
name: scAR
channels:
- nvidia
- pytorch
- conda-forge
dependencies:
- conda-forge::python>=3.8.6
- nvidia::cudatoolkit>=11.1
- pytorch::pytorch>=1.10.0
- pytorch::torchvision>=0.9.0
- pytorch::torchaudio>=0.8.0
- pytorch-mutex=*=cuda
- conda-forge::tqdm>=4.62.3
- conda-forge::pandas>=1.3.4
- conda-forge::seaborn>=0.11.2
- conda-forge::tensorboard>=2.2.1
- conda-forge::scikit-learn>=1.0.1
- conda-forge::anndata
- conda-forge::scanpy
- conda-forge::pyro-ppl>=1.8.0
- conda-forge::pip
- pip:
  - .
```

As you can see everything depends on the package `pytorch-mutex`. How can I incororate this in the current recipe. It seems that versions are not identified.

**Comment by fgypas** [comment]
@BiocondaBot please add label

**Comment by dpryan79** [comment]
@fgypas We only source dependencies from conda-forge, so you'll need to depend on pytorch from there. They do provide CUDA versions of that, so maybe that will more or less work here too. I've never played around with CUDA support, since so little supports CUDA. This may fail in the docker container tests, I'm not sure, but it's worth a go either way.

**Comment by fgypas** [comment]
Thanks a lot @dpryan79 It's my first attempt with cuda so I am not sure if I follow the right approach.

**Comment by dpryan79** [comment]
@fgypas That makes two of us. Does this absolutely require pytorch-audio? Someone would need to add that to conda-forge.

**Comment by fgypas** [comment]
@dpryan79 I don't think that we need it, but I have to test it. I will get back to you. In case we need it I will open a PR to conda-forge.

**Comment by fgypas** [comment]
@dpryan79 Can you please have a look at the error message. I think that this has to do with some network issue and not with the recipe per se.

**Comment by dpryan79** [comment]
@BiocondaBot please fetch artifacts

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
This seems ready to be merged. Let me know if there's anything else, otherwise you can tell the bot to merge it.

**Comment by fgypas** [comment]
Thanks @dpryan79 I have a machine locally with cuda and one without. I will test the artifacts on both of them.
How can I specify the artifacts as a channel? What is the correct URL?

**Comment by fgypas** [comment]
@BiocondaBot please merge

**Pull request merged**
