### PR TITLE
Remove multicore-tsne from dependencies, bump python version to 3.7

### PR DESCRIPTION
**Pull request by nh3**
…o accommodate click.

Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it. Note that if you are not already a member of the bioconda project (meaning that you can't add this label), please ping `@bioconda/core` so that your PR can be reviewed and merged (please note if you'd like to be added to the bioconda project). Please see https://github.com/bioconda/bioconda-recipes/issues/15332 for more details.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by nh3** [comment]
This somehow didn't build after merging (https://github.com/bioconda/bioconda-recipes/commit/d1ec7869e09b68eb0658658e3f4d3cffa93f9271) and https://circleci.com/gh/bioconda/bioconda-recipes/77746?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link shows error message "Blocked due to free-plan-executor-unavailable". The next commit in master (https://github.com/bioconda/bioconda-recipes/commit/3000215f285943126546e05dd5f23652bce11021) also failed for the same reason.
@dpryan79 any idea?

**Comment by bgruening** [comment]
We are investigating ... we don't know more than what is written there :(

**Comment by dpryan79** [comment]
There was a bug on circleci's side that seems to have since been resolved. This will be picked up during the next nightly cron job run (or I'll just push things into bulk).

**Comment by nh3** [comment]
Yep, the new commits in master are building correctly again. Thanks @bgruening and @dpryan79.

**Pull request merged**
