### PR TITLE
Add recipe for paml version 4.9

### PR DESCRIPTION
**Pull request by gregvonkuster**
* [x] I have read the guidelines above.
* [x] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by gregvonkuster** [comment]
@bgruening Thanks for the help on this.  Is this latest failure a timeout or something else?  Where can I find /home/travis/build.sh?
```
ERROR bioconda_utils.build:build_recipes(356): BIOCONDA BUILD SUMMARY: of 1 recipes, 1 failed and 0 were skipped. Details of recipes and environments follow.
ERROR bioconda_utils.build:build_recipes(367): BIOCONDA BUILD SUMMARY: FAILED recipe paml-4.9-0.tar.bz2, environment CONDA_R=3.3.1;CONDA_BOOST=1.60;CONDA_NCURSES=5.9;CONDA_PERL=5.22.0;CONDA_GMP=5.1;CONDA_NPY=110;CONDA_GSL=1.16;CONDA_PY=27
/home/travis/build.sh: line 151:  3136 Terminated              travis_jigger $! $timeout $cmd
```

**Comment by bgruening** [comment]
@gregvonkuster do you have a linux box and can you run `simulate-travis.py` on this recipe - I'm not in front of a real PC for a week.

**Comment by gregvonkuster** [comment]
@bgruening - throws an exception,  so looks like this script require Python 3.5.  I'm running 2.7.12 and would rather not upgrade right now.  Is there an easier way?
```
$ pwd
/home/greg/work/bioconda-recipes/paml2/bioconda-recipes
$ python simulate-travis.py --packages paml bioconductor-* --loglevel=debug
Traceback (most recent call last):
  File "simulate-travis.py", line 150, in <module>
    sp.run(['scripts/travis-run.sh'], env=env, universal_newlines=True, check=True)
AttributeError: 'module' object has no attribute 'run'
```

**Comment by bgruening** [comment]
@gregvonkuster rebase against master will show you where the error is.

**Comment by gregvonkuster** [comment]
I'm using my own channel for this recipe, so closing.

**Comment by bgruening** [comment]
Greg, this will not work and you will have more problems in the long run, especially if Nate should run your tools on HPC :(

Can you send me all your recipes via mail, I will work on this over the weekend.

**Comment by gregvonkuster** [comment]
@bgruening I'm hoping to get all of the package recipes working in my channel which should allow me to get the tools working, and then I'll move the recipes into the bioconda channel.  Thanks for all of the help.  ;)

**Pull request closed without merging**
