### PR TITLE
Update cgat-apps to v0.5.4

### PR DESCRIPTION
**Pull request by sebastian-luna-valero**
* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [X] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [X] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by sebastian-luna-valero** [comment]
Hi @bioconda/core

I am getting:
```
16:39:29 BIOCONDA INFO (OUT) Solving environment: ...working... failed
16:39:29 BIOCONDA INFO (OUT) failed to get install actions, retrying.  exception was: Unsatisfiable dependencies for platform linux-64: {'cgat-apps==0.5.4=py37h84d0fb7_0'}
16:39:29 BIOCONDA INFO (OUT) WARNING:conda_build.build:failed to get install actions, retrying.  exception was: Unsatisfiable dependencies for platform linux-64: {'cgat-apps==0.5.4=py37h84d0fb7_0'}
```
but I can't find why the dependencies are unsatisfiable, am I missing something basic here?

Best regards,
Sebastian

**Comment by dpryan79** [comment]
More often than not that means there's a dependency missing for that python version, but I'll take a look.

**Comment by sebastian-luna-valero** [comment]
Thanks @dpryan79 !

I guess it is tricky to have a more explicity output to print out those missing dependencies?

**Comment by dpryan79** [comment]
Oh, the issue is quicksect, which I don't think is compatible with python 3.7.

**Comment by sebastian-luna-valero** [comment]
Many thanks!

Will try to re-build quicksect for Python 3.7

**Comment by dpryan79** [comment]
@sebastian-luna-valero This should be ready to go.

**Comment by sebastian-luna-valero** [comment]
That's brilliant, thank you very much!

I had a look at your comments about Cython and Python 3.7. I wasn't aware of that, is it documented somewhere?

**Comment by dpryan79** [comment]
No clue, I hope python has documented its C API changes, though I wonder if Cython is just using parts that just aren't stable between releases.

**Comment by sebastian-luna-valero** [comment]
Well, many thanks!

**Pull request merged**
