### PR TITLE
Update medaka to 1.2.3

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`medaka`](https://bioconda.github.io/recipes/medaka/README.html): **1.2.2** &rarr; **1.2.3**

[install with bioconda](http://bioconda.github.io/recipes/medaka/README.html) [Conda](https://anaconda.org/bioconda/medaka/files)

Info | Link
-----|-----
Recipe | [`recipes/medaka`](https://github.com//bioconda/bioconda-recipes/tree/bump/medaka/recipes/medaka) (click to view/edit other files)
Releases |[https://pypi.org/pypi/medaka/json](https://pypi.org/pypi/medaka/json)
Recipe Maintainer(s) | @cjw85

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by druvus** [comment]
@bioconda-bot please fetch artifacts

**Comment by cjw85** [comment]
The build needs racon adding.

There's also some issues with tensorflow. The only configurations know to work are tensorflow 2.4, for which there's no conda package, and python 3.6 with TF2.2.

**Comment by cjw85** [comment]
@bioconda-bot please fetch artifacts

**Review by cjw85 — APPROVED** [review]

**Comment by cjw85** [comment]
@bioconda-bot please merge

**Pull request merged**
