### PR TITLE
Stacks support

### PR DESCRIPTION
**Pull request by tiagoantao**
Support for stacks.

### CODE REVIEW

**Comment by tiagoantao** [comment]
ping @bgruening

**Comment by bgruening** [comment]
@tiagoantao looking at the other perl recipes I guess you should depend on perl-threaded in both build and run. 

Moreover, try to use some imports to test you lib.

Like this one:
```
test:
  # Perl 'use' tests
  imports:
    - Sub::Uplevel
```

Thanks for working on this!

**Comment by johanneskoester** [comment]
Further, if the makefile is compiling something with gcc or llvm, please depend on anacondas ``gcc`` or ``llvm`` packages.

**Comment by tiagoantao** [comment]
I am having a problem with the perl test:
I have copied @bgruening suggestion and checked it against other examples (e.g https://github.com/bioconda/bioconda-recipes/blob/master/recipes/perl-sub-uplevel/meta.yaml), but for some reason its not working.

I have the feeling that I am missing something obvious here... :(

**Comment by bgruening** [comment]
@tiagoantao sorry for the confusion. I though you stacks ships it's own perl modules, but it isn't.

I guess the build section should look like this:
```
  build:
    - gcc
    - perl-threaded
  run:
    - libgcc
    - perl-threaded
```

Skip the perl import test, this was my mistake.

**Comment by tiagoantao** [comment]
I was having a look at the travis output and it seems that it is a timeout error, not a real problem. Other PRs seem to have the same thing...

**Comment by bgruening** [comment]
@tiagoantao it's not a timeout it's a failing test: `TESTS FAILED: stacks-1.37-0`. The installation succeeded.

**Comment by bgruening** [comment]
My guess is that `cstacks 2> /dev/null` return an error level of 1.
You could try something like this `cstacks 2>&1 | grep INSERT_HERE > /dev/null` and replace the INSERT_HERE with a string that appears in your cstacks output.

**Pull request merged**
