### PR TITLE
R argparse 1.0.1

### PR DESCRIPTION
**Pull request by acaprez**
* [X] I have read the guidelines above.
* [X] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

Also includes needed package r-findpython.

### CODE REVIEW

**Comment by acaprez** [comment]
@bioconda/core - look ok to you?

**Comment by bgruening** [comment]
@acaprez looks good to me. However I would prefer to cleanup the recipes a little bit, but this is up to you.

**Comment by acaprez** [comment]
@bgruening sure, that's fine.  You mean just remove the extraneous commented sections at the end?

**Comment by bgruening** [comment]
Yeah, this would be nice.

**Pull request merged**
