### PR TITLE
sentieon: Fix bwa symlinks patch so that it also updates the shebang

### PR DESCRIPTION
**Pull request by Lenbok**
The current patches to sentieon and bwa wrappers introduce bash-ism, however the shebang had only been updated on the sentieon wrapper, as discovered in #9686 . This updates the bwa wrapper also.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by bgruening** [comment]
@Lenbok any idea why this was not catched during the tests? Can we include a test for this?

**Comment by Lenbok** [comment]
@bgruening I wondered that too and had started to add a test. sentieon-bwa returns non-zero exit so I thought to add something like:
````
sentieon-bwa 2>&1 | grep "Program: bwa"
````
But then saw in the `meta.yml` that there was already a similar test for `sentieon-licsrv` commented out with a note:
````
# Tests have issues with on quay/mulled when combined, non-zero exit code
````
I don't understand that, so I didn't add an extra test.

**Comment by Lenbok** [comment]
@bgruening I guess that means the exit codes are still a problem. Do you have any suggestions, or should I drop that last commit?

**Comment by bgruening** [comment]
This seems to be a real error. I get this locally with more debug informations:
```
/usr/local/share/sentieon-201711.04-3/libexec/bwa: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory
```

The wired thing is that libstdc is actually installed. So maybe the bwa binary is broken?

```
bash-4.2# ls -l /usr/local/lib/libstdc++.so.6
lrwxrwxrwx    1 root     root            19 Jul  7 21:10 /usr/local/lib/libstdc++.so.6 -> libstdc++.so.6.0.24
```

**Comment by Lenbok** [comment]
What does ldd report for both the `libexec/bwa` and `libexec/driver` binaries?

**Comment by chapmanb** [comment]
Björn -- sentieon-bwa definitely works with the standard package on conda installs, but for some reason has issues inside of the mulled container tests. I'm not sure how to debug them so in the past have commented out the problematic tests to work around them and get it built. If you have any idea how to resolve happy to have it better setup.

**Comment by bgruening** [comment]
@Lenbok output from ldd is:
```
bash-4.2# ldd  /usr/local/share/sentieon-201711.04-3/libexec/bwa                                                                                                                                                  
	/lib64/ld-linux-x86-64.so.2 (0x7f7e3a736000)
	libstdc++.so.6 => /usr/local/lib/libstdc++.so.6 (0x7f7e3a3fc000)
	libz.so.1 => /usr/local/lib/libz.so.1 (0x7f7e3a1df000)
	libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x7f7e3a736000)
	libdl.so.2 => /lib64/ld-linux-x86-64.so.2 (0x7f7e3a736000)
	librt.so.1 => /lib64/ld-linux-x86-64.so.2 (0x7f7e3a736000)
	libm.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7f7e3a736000)
	libgcc_s.so.1 => /lib/libgcc_s.so.1 (0x7f7e39fce000)
	libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7f7e3a736000)
	ld-linux-x86-64.so.2 => /lib/ld-linux-x86-64.so.2 (0x7f7e39dac000)
Error relocating /usr/local/share/sentieon-201711.04-3/libexec/bwa: __fprintf_chk: symbol not found
Error relocating /usr/local/share/sentieon-201711.04-3/libexec/bwa: __printf_chk: symbol not found
Error relocating /usr/local/share/sentieon-201711.04-3/libexec/bwa: __memcpy_chk: symbol not found
Error relocating /usr/local/share/sentieon-201711.04-3/libexec/bwa: __strcat_chk: symbol not found
Error relocating /usr/local/share/sentieon-201711.04-3/libexec/bwa: __vfprintf_chk: symbol not found
Error relocating /usr/local/share/sentieon-201711.04-3/libexec/bwa: __isnan: symbol not found
Error relocating /usr/local/share/sentieon-201711.04-3/libexec/bwa: __memset_chk: symbol not found
Error relocating /usr/local/share/sentieon-201711.04-3/libexec/bwa: __sprintf_chk: symbol not found
bash-4.2# bwa                                                   
bash: bwa: command not found
bash-4.2# ldd  /usr/local/share/sentieon-201711.04-3/libexec/driver 
	/lib64/ld-linux-x86-64.so.2 (0x7fd373c03000)
Error loading shared library liblapack.so.3: No such file or directory (needed by /usr/local/share/sentieon-201711.04-3/libexec/driver)
Error loading shared library libblas.so.3: No such file or directory (needed by /usr/local/share/sentieon-201711.04-3/libexec/driver)
Error loading shared library libhdf5_cpp.so.6: No such file or directory (needed by /usr/local/share/sentieon-201711.04-3/libexec/driver)
Error loading shared library libhdf5.so.6: No such file or directory (needed by /usr/local/share/sentieon-201711.04-3/libexec/driver)
	libpython2.7.so.1.0 => /usr/local/lib/libpython2.7.so.1.0 (0x7fd3737de000)
	libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x7fd373c03000)
Error loading shared library liblzma.so.0: No such file or directory (needed by /usr/local/share/sentieon-201711.04-3/libexec/driver)
Error loading shared library libbz2.so.1: No such file or directory (needed by /usr/local/share/sentieon-201711.04-3/libexec/driver)
	libz.so.1 => /usr/local/lib/libz.so.1 (0x7fd3735c1000)
	librt.so.1 => /lib64/ld-linux-x86-64.so.2 (0x7fd373c03000)
	libdl.so.2 => /lib64/ld-linux-x86-64.so.2 (0x7fd373c03000)
	libstdc++.so.6 => /usr/local/lib/libstdc++.so.6 (0x7fd373287000)
	libm.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7fd373c03000)
	libgcc_s.so.1 => /lib/libgcc_s.so.1 (0x7fd373076000)
	libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7fd373c03000)
	libutil.so.1 => /lib64/ld-linux-x86-64.so.2 (0x7fd373c03000)
	ld-linux-x86-64.so.2 => /lib/ld-linux-x86-64.so.2 (0x7fd372e54000)
Error relocating /usr/local/lib/libpython2.7.so.1.0: __isnan: symbol not found
Error relocating /usr/local/lib/libpython2.7.so.1.0: __finite: symbol not found
Error relocating /usr/local/lib/libpython2.7.so.1.0: __isinf: symbol not found
Error relocating /usr/local/lib/libpython2.7.so.1.0: __isinff: symbol not found
Error relocating /usr/local/lib/libpython2.7.so.1.0: __rawmemchr: symbol not found
Error relocating /usr/local/lib/libpython2.7.so.1.0: tmpnam_r: symbol not found
Error relocating /usr/local/share/sentieon-201711.04-3/libexec/driver: __printf_chk: symbol not found
Error relocating /usr/local/share/sentieon-201711.04-3/libexec/driver: lzma_stream_decoder: symbol not found
Error relocating /usr/local/share/sentieon-201711.04-3/libexec/driver: _ZN2H56H5FileD1Ev: symbol not found
Error relocating /usr/local/share/sentieon-201711.04-3/libexec/driver: lzma_stream_buffer_bound: symbol not found
Error relocating /usr/local/share/sentieon-201711.04-3/libexec/driver: _ZNK2H57DataSet8getSpaceEv: symbol not found
Error relocating /usr/local/share/sentieon-201711.04-3/libexec/driver: H5check_version: symbol not found
Error relocating /usr/local/share/sentieon-201711.04-3/libexec/driver: __vfprintf_chk: symbol not found
Error relocating /usr/local/share/sentieon-201711.04-3/libexec/driver: dpotrf_: symbol not found
Error relocating /usr/local/share/sentieon-201711.04-3/libexec/driver: _ZN2H59Exception9dontPrintEv: symbol not found
Error relocating /usr/local/share/sentieon-201711.04-3/libexec/driver: _ZN2H56H5File5closeEv: symbol not found
Error relocating /usr/local/share/sentieon-201711.04-3/libexec/driver: _ZN2H59ExceptionC1ERKS0_: symbol not found
Error relocating /usr/local/share/sentieon-201711.04-3/libexec/driver: lzma_easy_buffer_encode: symbol not found
Error relocating /usr/local/share/sentieon-201711.04-3/libexec/driver: _ZN2H57DataSetD1Ev: symbol not found
Error relocating /usr/local/share/sentieon-201711.04-3/libexec/driver: dgetri_: symbol not found
Error relocating /usr/local/share/sentieon-201711.04-3/libexec/driver: BZ2_bzBuffToBuffCompress: symbol not found
Error relocating /usr/local/share/sentieon-201711.04-3/libexec/driver: __sprintf_chk: symbol not found
Error relocating /usr/local/share/sentieon-201711.04-3/libexec/driver: lzma_memusage: symbol not found
Error relocating /usr/local/share/sentieon-201711.04-3/libexec/driver: H5Gget_objinfo: symbol not found
Error relocating /usr/local/share/sentieon-201711.04-3/libexec/driver: _ZNK2H56H5File5getIdEv: symbol not found
Error relocating /usr/local/share/sentieon-201711.04-3/libexec/driver: _ZNK2H58AtomType7setSizeEm: symbol not found
Error relocating /usr/local/share/sentieon-201711.04-3/libexec/driver: _ZNK2H58CommonFG11openDataSetERKSs: symbol not found
Error relocating /usr/local/share/sentieon-201711.04-3/libexec/driver: _ZN2H514FileIExceptionD1Ev: symbol not found
Error relocating /usr/local/share/sentieon-201711.04-3/libexec/driver: _ZN2H57StrTypeD1Ev: symbol not found
Error relocating /usr/local/share/sentieon-201711.04-3/libexec/driver: _ZN2H511IdComponentaSERKS0_: symbol not found
Error relocating /usr/local/share/sentieon-201711.04-3/libexec/driver: _ZN2H57DataSet5closeEv: symbol not found
Error relocating /usr/local/share/sentieon-201711.04-3/libexec/driver: __strcat_chk: symbol not found
Error relocating /usr/local/share/sentieon-201711.04-3/libexec/driver: _ZN2H59ExceptionC2ERKS0_: symbol not found
Error relocating /usr/local/share/sentieon-201711.04-3/libexec/driver: _ZN2H55GroupD1Ev: symbol not found
Error relocating /usr/local/share/sentieon-201711.04-3/libexec/driver: _ZNK2H59Exception12getDetailMsgEv: symbol not found
Error relocating /usr/local/share/sentieon-201711.04-3/libexec/driver: _ZNK2H57DataSet5writeEPKvRKNS_8DataTypeERKNS_9DataSpaceES8_RKNS_19DSetMemXferPropListE: symbol not found
Error relocating /usr/local/share/sentieon-201711.04-3/libexec/driver: _ZNK2H59DataSpace19getSimpleExtentDimsEPyS1_: symbol not found
Error relocating /usr/local/share/sentieon-201711.04-3/libexec/driver: dgetrf_: symbol not found
Error relocating /usr/local/share/sentieon-201711.04-3/libexec/driver: BZ2_bzBuffToBuffDecompress: symbol not found
Error relocating /usr/local/share/sentieon-201711.04-3/libexec/driver: _ZN2H56H5FileC1ERKSsjRKNS_17FileCreatPropListERKNS_15FileAccPropListE: symbol not found
Error relocating /usr/local/share/sentieon-201711.04-3/libexec/driver: _ZNK2H57DataSet4readEPvRKNS_8DataTypeERKNS_9DataSpaceES7_RKNS_19DSetMemXferPropListE: symbol not found
Error relocating /usr/local/share/sentieon-201711.04-3/libexec/driver: _ZN2H59DataSpaceD1Ev: symbol not found
Error relocating /usr/local/share/sentieon-201711.04-3/libexec/driver: _ZN2H57DataSetC1Ev: symbol not found
Error relocating /usr/local/share/sentieon-201711.04-3/libexec/driver: __memset_chk: symbol not found
Error relocating /usr/local/share/sentieon-201711.04-3/libexec/driver: backtrace: symbol not found
Error relocating /usr/local/share/sentieon-201711.04-3/libexec/driver: _ZN2H59DataSpaceC1EiPKyS2_: symbol not found
Error relocating /usr/local/share/sentieon-201711.04-3/libexec/driver: _ZN2H56H5FileC1Ev: symbol not found
Error relocating /usr/local/share/sentieon-201711.04-3/libexec/driver: dgesvd_: symbol not found
Error relocating /usr/local/share/sentieon-201711.04-3/libexec/driver: lzma_code: symbol not found
Error relocating /usr/local/share/sentieon-201711.04-3/libexec/driver: backtrace_symbols_fd: symbol not found
Error relocating /usr/local/share/sentieon-201711.04-3/libexec/driver: _ZN2H59DataSpace5closeEv: symbol not found
Error relocating /usr/local/share/sentieon-201711.04-3/libexec/driver: __fprintf_chk: symbol not found
Error relocating /usr/local/share/sentieon-201711.04-3/libexec/driver: fopencookie: symbol not found
Error relocating /usr/local/share/sentieon-201711.04-3/libexec/driver: _ZN2H59FloatTypeD1Ev: symbol not found
Error relocating /usr/local/share/sentieon-201711.04-3/libexec/driver: _ZNK2H58CommonFG13createDataSetERKSsRKNS_8DataTypeERKNS_9DataSpaceERKNS_17DSetCreatPropListE: symbol not found
Error relocating /usr/local/share/sentieon-201711.04-3/libexec/driver: __memcpy_chk: symbol not found
Error relocating /usr/local/share/sentieon-201711.04-3/libexec/driver: _ZN2H519DSetMemXferPropListC1Ei: symbol not found
Error relocating /usr/local/share/sentieon-201711.04-3/libexec/driver: _ZN2H58DataType5closeEv: symbol not found
Error relocating /usr/local/share/sentieon-201711.04-3/libexec/driver: _ZN2H57DataSet11vlenReclaimERKNS_8DataTypeERKNS_9DataSpaceERKNS_19DSetMemXferPropListEPv: symbol not found
Error relocating /usr/local/share/sentieon-201711.04-3/libexec/driver: _ZN2H519DSetMemXferPropListD1Ev: symbol not found
Error relocating /usr/local/share/sentieon-201711.04-3/libexec/driver: _ZNK2H58CommonFG11createGroupERKSsm: symbol not found
Error relocating /usr/local/share/sentieon-201711.04-3/libexec/driver: _ZN2H57StrTypeC1ERKNS_8PredTypeE: symbol not found
Error relocating /usr/local/share/sentieon-201711.04-3/libexec/driver: lzma_end: symbol not found
Error relocating /usr/local/share/sentieon-201711.04-3/libexec/driver: _ZN2H59FloatTypeC1ERKNS_8PredTypeE: symbol not found
Error relocating /usr/local/share/sentieon-201711.04-3/libexec/driver: _ZN2H59DataSpaceC1E11H5S_class_t: symbol not found
Error relocating /usr/local/share/sentieon-201711.04-3/libexec/driver: _ZN2H59ExceptionD1Ev: symbol not found
Error relocating /usr/local/share/sentieon-201711.04-3/libexec/driver: _ZN2H517DataSetIExceptionD1Ev: symbol not found
Error relocating /usr/local/share/sentieon-201711.04-3/libexec/driver: _ZTVN2H514FileIExceptionE: symbol not found
Error relocating /usr/local/share/sentieon-201711.04-3/libexec/driver: _ZN2H59DataSpace3ALLE: symbol not found
Error relocating /usr/local/share/sentieon-201711.04-3/libexec/driver: _ZN2H58PredType13NATIVE_DOUBLEE: symbol not found
Error relocating /usr/local/share/sentieon-201711.04-3/libexec/driver: _ZTIN2H514FileIExceptionE: symbol not found
Error relocating /usr/local/share/sentieon-201711.04-3/libexec/driver: _ZN2H515FileAccPropList7DEFAULTE: symbol not found
Error relocating /usr/local/share/sentieon-201711.04-3/libexec/driver: _ZN2H517DSetCreatPropList7DEFAULTE: symbol not found
Error relocating /usr/local/share/sentieon-201711.04-3/libexec/driver: _ZN2H58PredType4C_S1E: symbol not found
Error relocating /usr/local/share/sentieon-201711.04-3/libexec/driver: _ZN2H517FileCreatPropList7DEFAULTE: symbol not found
Error relocating /usr/local/share/sentieon-201711.04-3/libexec/driver: _ZTVN2H517DataSetIExceptionE: symbol not found
Error relocating /usr/local/share/sentieon-201711.04-3/libexec/driver: _ZN2H519DSetMemXferPropList7DEFAULTE: symbol not found
Error relocating /usr/local/share/sentieon-201711.04-3/libexec/driver: _ZTIN2H59ExceptionE: symbol not found
Error relocating /usr/local/share/sentieon-201711.04-3/libexec/driver: _ZTIN2H517DataSetIExceptionE: symbol not found
```

**Comment by bgruening** [comment]
@chapmanb;

> definitely works with the standard package on conda installs

On most systems this might be true, the container seems to be broken. If you don't care about the container feel free to remove the test.

**Comment by Lenbok** [comment]
Let's comment the tests for now. I plan on trying to run this in a docker container, so that will at least give us one more data point.

**Comment by Lenbok** [comment]
@bgruening the current failure `failed to map segment from shared object: Cannot allocate memory` looks to be something due to the CI runner itself? (I must admit to feeling a little frustrated at this point)

**Comment by chapmanb** [comment]
Len -- sorry about all the trouble with this. I think the current issue is due to the change in having `binary_relocation: false` commented out. I believe that happened during Björn's testing. If you stick that back in and leave the problematic tests commented, I hope it will work. Thanks for all the patience debugging this.

**Comment by Lenbok** [comment]
@bgruening or @chapmanb Do you want to merge this? (or is it OK for me to merge, and if so, do you usually squash into a single commit when you merge?)

**Comment by bgruening** [comment]
You can also merge it if you like.

**Comment by Lenbok** [comment]
Thanks for the help on this guys!

**Pull request merged**
