### PR TITLE
Add jccirc

### PR DESCRIPTION
**Pull request by nictru**
This adds the [JCcirc](https://github.com/cbbzhang/JCcirc) package. Will soon be used in nf-core/circrna

### CODE REVIEW

**Comment by nictru** [comment]
@BiocondaBot please add label

**Comment by aliciaaevans** [comment]
soapdenovo-trans and trinity aren't built for linux-aarch64. You can open a PR for each of those to add the `additional-platforms` section for linux-aarch64 (assuming they don't have their own missing dependencies).

**Comment by nictru** [comment]
Ah thanks - I am pretty new to Bioconda so I am still learning :)

**Comment by nictru** [comment]
So basically three of the dependencies (`spades`, `trinity`, `soapdenovo-trans`) were not really necessary for the tool itself, rather optional dependencies for preprocessing. This should also fix the compatibility problems

**Comment by nictru** [comment]
@BiocondaBot please fetch artifacts

**Review by mencian — APPROVED** [review]

**Pull request merged**
