### PR TITLE
Update quantms-utils to 0.0.12

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`quantms-utils`](https://bioconda.github.io/recipes/quantms-utils/README.html): **0.0.11** &rarr; **0.0.12**

[install with bioconda](http://bioconda.github.io/recipes/quantms-utils/README.html) [Conda](https://anaconda.org/bioconda/quantms-utils/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/quantms-utils`](https://github.com//bioconda/bioconda-recipes/tree/bump/quantms_utils/recipes/quantms-utils) (click to view/edit other files)
Summary | Python package with scripts and helpers for the quantms workflow.
Home | [https://www.github.com/bigbio/quantms-utils](https://www.github.com/bigbio/quantms-utils)
Releases |[https://pypi.org/pypi/quantms_utils/json](https://pypi.org/pypi/quantms_utils/json)
Recipe Maintainer(s) | @ypriverol

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by ypriverol** [comment]
@bgruening, For some reason, the `bioconda.bioconda-recipes` is cancelled but without a clear reason. Have you seen this before?

**Comment by ypriverol** [comment]
@mencian can you check why the building of the package is taking so long? but in arm is really quick.

**Comment by mencian** [comment]
@ypriverol this seems to be happening with other PRs as well; not exactly sure of the cause. See #51354, #51373, #51378. I'll look into this some more~

**Comment by ypriverol** [comment]
@bgruening can you help us here ?

**Comment by mencian** [comment]
@ypriverol Sorry for the late response - there's no obvious way to workaround the limited resources on the Azure machines, which are capped at 2 cores and 7GB memory. One way is to build this recipe on the `bulk` branch, which has machines with 16GB memory, though I haven't tinkered with anything on the `bulk` branch before.

**Comment by ypriverol** [comment]
Thanks @mencian we managed to build the recipe in GitHub actions https://github.com/bigbio/quantms-utils/actions/runs/11313535585/job/31462424827 from this recipe: https://github.com/bigbio/quantms-utils/blob/main/recipe/meta.yaml But I don't see differences major here. 

Let's wait until @bgruening gives us here a suggestion.

**Comment by bgruening** [comment]
Please stop wasting CI time and resources. We are working on it.

**Comment by ypriverol** [comment]
@bgruening sorry. I normally update the fork in my side in case there are conflicts to be solved so as not to get to unsync. My apologies.

**Review by bgruening — APPROVED** [review]

**Pull request merged**
