### PR TITLE
Rebuild molpopgen-analysis (gsl, openblas)

### PR DESCRIPTION
**Pull request by epruesse**
Rebuild [`molpopgen-analysis`](https://bioconda.github.io/recipes/molpopgen-analysis/README.html) to update pinnings

[install with bioconda](http://bioconda.github.io/recipes/molpopgen-analysis/README.html) [Conda](https://anaconda.org/bioconda/molpopgen-analysis/files)

Info | Link
-----|-----
Recipe | [`recipes/molpopgen-analysis`](https://github.com//bioconda/bioconda-recipes/tree/bump/molpopgen_analysis/recipes/molpopgen-analysis) (click to view/edit other files)
Releases |[https://github.com/molpopgen/analysis/tags](https://github.com/molpopgen/analysis/tags)
Author | @molpopgen
***

Rebuild is necessary for the following reasons:
- Pin `gsl 2.4` not within `>=2.2.1,<2.3.0a0`
- Pin `openblas 0.3.3` not within `>=0.2.20,<0.2.21.0a0`

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/updating.html)).

### CODE REVIEW

**Comment by dpryan79** [comment]
I wonder if we should continue trying to support this package, it was archived by the authors 4 years ago.

**Comment by epruesse** [comment]
Add-to-blacklist or add-disable-autobump? (`extra: autobump: enable: false`)

**Comment by dpryan79** [comment]
Ooo, we can just disable the autobump. I forgot about that option, much nicer :)

**Comment by molpopgen** [comment]
This is a good idea.  This package is archived for a reason, and I did
object to it being added initially, but someone apparently needed it for
something

**Comment by dpryan79** [comment]
Can't argue with that reasoning, thanks for weighing in @molpopgen!

**Comment by dpryan79** [comment]
OK, this should (assuming I didn't muck it up) no longer get autobumped, thanks everyone!

**Pull request merged**
