### PR TITLE
R 15 or so

### PR DESCRIPTION
**Pull request by daler**
* [ ] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

more r packages

### CODE REVIEW

**Comment by bgruening** [comment]
The title is great ... it indeed should be something like 17 or so ;)

**Comment by daler** [comment]
@bgruening looks like we have another looper?

**Comment by bgruening** [comment]
@daler yes, this is really annoying. I commented out the OSX build in an other PR to get at least the Linux builds done :(

**Comment by bgruening** [comment]
This is so sad :(

**Comment by daler** [comment]
It seems that building packages for osx takes about an order of magnitude more time to debug than linux. Pretty frustrating.

**Comment by bgruening** [comment]
@daler https://github.com/conda/conda-build/issues/1449 maybe this one?

**Comment by daler** [comment]
@bgruening I saw that, but wasn't convinced it was the issue. I just opened this one: https://github.com/conda/conda-build/issues/1454.

**Comment by daler** [comment]
@bgruening one difficulty here is that the build does not immediately fail.

For example, [this error](https://travis-ci.org/bioconda/bioconda-recipes/jobs/167058058#L1585) is not, in fact, because `bioconductor-annotate` doesn't exist. Rather, it's because `bioconductor-category` failed (mismatching md5sum -- seems bioarchive md5s don't match bioconductor?) and the build didn't stop at that point.

 I'm updating bioconda-utils to stop the build at first failure which should make debugging a lot easier.

**Comment by bgruening** [comment]
@daler yeah md5sum are different. bioarchive will create tarballs out of svn, so the used zlib version or whatever can be different and the tarball is not the same.

**Comment by daler** [comment]
@bgruening https://github.com/conda/conda-build/issues/1432, fixed in conda-build 2.0.5.

I'm re-writing parts of bioconda-utils to use conda_build.api (it's working now with 2.0.4), and will now test with 2.0.5.

then I'll include the new bioconda-utils tag in the `.travis.yml` file in this PR and see how it goes . . .

**Comment by bgruening** [comment]
Nice, let me know if you need help or a review!

**Comment by bgruening** [comment]
@daler even the linux builds seem to have problems finding dependencies that should be available.

**Comment by daler** [comment]
You're right, and those tests should not be passing on linux.

**Comment by daler** [comment]
@bgruening the only thing untested is the uploading to anaconda. I'm currently factoring out the upload code to a new module for better testing, and I created a new testing token for anaconda. Once uploading is tested, we should be ready to start using bioconda-utils + mulled-build.

**Comment by bgruening** [comment]
I fixed the tests and released a new galaxy-lib version.

**Comment by daler** [comment]
closing in favor of #2694

**Pull request closed without merging**
