### PR TITLE
All builds must pass

### PR DESCRIPTION
**Pull request by daler**
As discussed in #498, this is a simple change to build-packages.py to require all non-skipped recipes to successfully build. I added a fix to google-api-python-client to only build on py27 so that it passes. 

I updated the readme to reflect these changes. While I was there, added more info about the build system, more details on prerequisites, examples of skipping Python versions, and some cosmetic tweaks.

### CODE REVIEW

**Comment by daler** [comment]
@chapmanb, looks like seqcluster was never built for OSX -- at least [no packages](https://anaconda.org/bioconda/seqcluster/files) have been uploaded to Anaconda.

The build error was [here](https://travis-ci.org/bioconda/bioconda-recipes/builds/99103857) and was only reported after requiring all configured builds to pass. I couldn't see a quick solution so I removed it from `osx-whitelist` for now.

**Comment by chapmanb** [comment]
Ryan;
Awesome, thanks for this (and sorry for letting another python package slip through). Removing seqcluster on OSX for now is great. @lpantano -- maybe we can figure out what is wrong and re-enable it when you're back from your trip, but no rush.

**Comment by daler** [comment]
@johanneskoester, thoughts on this? I'd like to get your feedback before merging since it changes how things are classified as a failure on travis-ci.

**Comment by kyleabeauchamp** [comment]
The new logic---all enabled builds for a package are required to pass before upload---sounds reasonable to me.

**Comment by johanneskoester** [comment]
This is awesome! I totally support the changes. Please feel free to merge.

**Pull request merged**
