### PR TITLE
VirMet

### PR DESCRIPTION
**Pull request by ozagordi**
* [x] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by bgruening** [comment]
You need to increase the build number if you want to have a new package.

**Comment by ozagordi** [comment]
Thanks. I had forgotten a dependency in the previous meta file, so it's not a different version of the tool, just of the recipe. Do I have to change it also in this case?

**Comment by bgruening** [comment]
Yes, for changes like this and to ensure reproducibility we enforce a build number increase. Otherwise we do not build the package and not push it to anaconda.org.

**Comment by ozagordi** [comment]
I see, but then the package will not be in sync with the releases on GitHub. Will v1.1.1 be enough?

**Comment by bgruening** [comment]
I'm talking about the https://conda.io/docs/building/meta-yaml.html#build-number-and-string.
So the version number is still in sync with the github release, but we increase the build-number.

**Comment by ozagordi** [comment]
Ok, thanks. I had missed that.

**Comment by bgruening** [comment]
Great! Thanks!

**Pull request merged**
