### PR TITLE
Add recipe for cBioPortalData from Bioconductor

### PR DESCRIPTION
**Pull request by inodb**
Add cBioPortalData recipe https://www.bioconductor.org/packages/release/bioc/html/cBioPortalData.html

### CODE REVIEW

**Comment by LiNk-NY** [comment]
I'm happy to see that it can now be added to bioconda. Thanks Ino!

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Comment by dpryan79** [comment]
@inodb Thanks for the PR! Sorry this didn't get included with all of the other Bioconductor recipes, it must have been missing from the text file list on the Bioconductor site (there are a few errors in those every release :( ).

**Comment by inodb** [comment]
No worries @dpryan79 - thanks so much for the quick merge!

**Pull request merged**
