### PR TITLE
Update StringTie to 1.3.6

### PR DESCRIPTION
**Pull request by nsoranzo**
Remove ancient 1.0.3 and 1.0.4 subdirectories.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by epruesse** [comment]
@biocondabot recheck

**Comment by epruesse** [comment]
Hopefully, we can leave conda's CFLAGS intact

**Comment by nsoranzo** [comment]
Green!

**Comment by epruesse** [comment]
@biocondabot merge

**Comment by epruesse** [comment]
@BiocondaBot merge

**Comment by epruesse** [comment]
Looks like Anaconda isn't doing well. Timeouts...
@biocondabot merge darnit

**Comment by epruesse** [comment]
@BiocondaBot merge

**Comment by epruesse** [comment]
@biocondabot merge

**Pull request merged**
