### PR TITLE
R ROCR Survival

### PR DESCRIPTION
**Pull request by kmurat1**
I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
 This PR adds a new recipe.
 AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).

### CODE REVIEW

**Comment by daler** [comment]
Would you please add r-survival and r-rocr to conda-forge rather than bioconda, as these packages are not biology-specific? More info here: https://conda-forge.org/docs/

**Comment by kmurat1** [comment]
@daler apologize for that, I've add them to staged-recipes now is it right place for them?

**Comment by daler** [comment]
Perfect, thanks.

Would you also add a link here to that staged-recipes PR so we can easily keep track of it? Once that is merged into conda-forge we can pick back up here again.

**Comment by kmurat1** [comment]
Hi Ryan,
My PR is https://github.com/conda-forge/staged-recipes/pull/3947 I've just don't understand why all checks have failed because I did everything like with my previous packages. I was thinking that maybe they already exists in conda-forge (conda-forge-linter comment). I was searching for them on bioconda site before so it is possible issue with beginner like me.
 Thank you, Kate

**Comment by daler** [comment]
@kmurat1 sorry about that, I should have checked to see if they were in conda-forge before sending you there. You're right, both those packages already exist in conda-forge. You can close https://github.com/conda-forge/staged-recipes/pull/3947, and then you can remove the r-rocr and r-survival from this PR.

`r-entrez` looks good. For `r-illuminahumanmethylation450kanno.ilmn12.hg19`, can you please use the `bioconda-utils bioconductor-skeleton` script as documented here: https://bioconda.github.io/guidelines.html#r-bioconductor. The reason is that this is a data package, and that script will build the recipe in such a way to conserve limited space on the bioconda channel.

**Comment by johanneskoester** [comment]
We  have made changes to our build system (migrated from Travis CI to  Circle CI). If you would like to continue working on this PR, please  reopen this PR and update with latest upstream/master.

**Pull request closed without merging**
