### PR TITLE
Update igblast

### PR DESCRIPTION
**Pull request by aerijman**
Update igblast to it's latest release 1.17.1

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by dpryan79** [comment]
It looks like you're trying to merge the bioconda-utils source code in as well as a tweak to the igblast recipe for osx. Can you clean that up?

**Comment by aerijman** [comment]
> It looks like you're trying to merge the bioconda-utils source code in as well as a tweak to the igblast recipe for osx. Can you clean that up?

Oh

**Comment by aerijman** [comment]
Hi @dpryan79, I don't think that I understand the issue with osx. I just changed the version and the shasums in  meta.yml.
Should I remove the macOs related files from the recipe?

**Comment by mbargull** [comment]
@aerijman, could you go to https://app.circleci.com/pipelines/github/aerijman/bioconda-recipes , there to "Project Settings" (top right), then hit "Stop Building"? I don't know why but, CircleCI is just a little strange when it builds on a fork.

**Comment by aerijman** [comment]
Sha256 of linux was old. Probably my mistake. It should be fixed now.
Is there any particular problem with this PR that I should be aware (or avoid)? 
Thanks!

**Comment by mbargull** [comment]
> Is there any particular problem with this PR that I should be aware (or avoid)?

Hi @aerijman,
yes, as Devon mentioned, you somehow merged commits from an entirely different repository, i.e., https://github.com/bioconda/bioconda-utils , into this one. No idea how this happened :smile:

Easiest thing would be to
```sh
git reset --hard 1c73b90b8808b16263412ee8b8eaa52b9c8a439e
git cherry-pick ee253ab7c19909435a8ce2a98daf81d04e31f071
git push --force
```
locally on your `update_igblast` branch.

**Comment by aerijman** [comment]
@mbargull and @dpryan79, I apologized for that. I don't know what was I thinking of... my .git/config was:
```
[core]
        repositoryformatversion = 0
        filemode = true
        bare = false
        logallrefupdates = true
        ignorecase = true
        precomposeunicode = true
[remote "origin"]
        url = git@github.com:aerijman/bioconda-recipes.git
        fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
        remote = origin
        merge = refs/heads/master
[remote "upstream"]
        url = https://github.com/bioconda/bioconda-utils.git
        fetch = +refs/heads/*:refs/remotes/upstream/*
[branch "update_igblast"]
        remote = origin
        merge = refs/heads/update_igblast
```

I fixed it now and I apologize for not having understood Devon in his email.

**Comment by aerijman** [comment]
Is it ready to merge?

**Comment by mbargull** [comment]
>  \[...\] my .git/config was: \[...\]

Aha, that explains it ^^.

**Review by mbargull — APPROVED** [review]

**Comment by mbargull** [comment]
@BiocondaBot, please merge

**Pull request merged**
