### PR TITLE
Fred2 update

### PR DESCRIPTION
**Pull request by apeltzer**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

Pinging @bioconda/core for review :-)

### CODE REVIEW

**Comment by apeltzer** [comment]
Merging in master after @dpryan79 s suggestion. If this doesn't work, I'll put `r-maldiquant` on the blacklist!

**Comment by dpryan79** [comment]
I suspect my last tweak will solve things.

**Comment by apeltzer** [comment]
Not on osx :-(

**Comment by dpryan79** [comment]
That's likely fixed now. `sed` is different on OSX and shouldn't be needed to begin with.

**Pull request merged**
