### PR TITLE
Update lace to 1.13

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`lace`](https://bioconda.github.io/recipes/lace/README.html): **1.00** &rarr; **1.13**

[install with bioconda](http://bioconda.github.io/recipes/lace/README.html) [Conda](https://anaconda.org/bioconda/lace/files)

Info | Link
-----|-----
Recipe | [`recipes/lace`](https://github.com//bioconda/bioconda-recipes/tree/bump/lace/recipes/lace) (click to view/edit other files)
Releases |[https://github.com/Oshlack/Lace/tags](https://github.com/Oshlack/Lace/tags)
Author | `@Oshlack`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/updating.html)).

### CODE REVIEW

**Comment by dpryan79** [comment]
This says it needs libGl.so, but I'm not sure that's really true.

**Comment by dpryan79** [comment]
Need to add a shebang to the python script.

**Comment by dpryan79** [comment]
I'll make a PR to convert lace to a proper python package.

**Comment by dpryan79** [comment]
PR made. Once that's merged and a new release tagged this can be updated to use that and then merged.

**Comment by raivivek** [comment]
@bioconda-bot autobump

**Pull request closed without merging**
