### PR TITLE
gsort 0.0.3

### PR DESCRIPTION
**Pull request by brentp**
* [X] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [X] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by brentp** [comment]
anyone have an idea on this? it's downloading a linux 64 bit binary and seg-faulting on that machine. it's a golang binary...

**Comment by johanneskoester** [comment]
Looks like a bug in the software. Maybe it would be good to report this to upstream?

**Comment by brentp** [comment]
I am the author of gsort, but I'm using go's machinery to build a static binary so I'm not sure how to debug further, thought there might be something with travis...

**Comment by johanneskoester** [comment]
You could run the build process during packaging instead of using pre-built binaries. Maybe the error becomes more obvious then.

**Comment by bgruening** [comment]
Oh yes a GO-compiler would be nice to have ;)

**Pull request closed without merging**
