### PR TITLE
Update treeqmc to 3.0.1

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`treeqmc`](https://bioconda.github.io/recipes/treeqmc/README.html): **2.0.0** &rarr; **3.0.1**

[install with bioconda](http://bioconda.github.io/recipes/treeqmc/README.html) [Conda](https://anaconda.org/bioconda/treeqmc/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/treeqmc`](https://github.com//bioconda/bioconda-recipes/tree/bump/treeqmc/recipes/treeqmc) (click to view/edit other files)
Summary | TREE-QMC is a quartet-based method for estimating species trees from gene trees.
Home | [https://github.com/molloy-lab/TREE-QMC](https://github.com/molloy-lab/TREE-QMC)
Releases |[https://github.com/molloy-lab/TREE-QMC/tags](https://github.com/molloy-lab/TREE-QMC/tags)
Author | `@molloy-lab`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by rpetit3** [comment]
based on dev feedback (https://github.com/molloy-lab/TREE-QMC/issues/4) we are going to add this one to the blacklist so that only the `tree-qmc` version receives future updates

**Comment by mencian** [comment]
Thanks for chiming in @rpetit3!

**Comment by rpetit3** [comment]
No problem! haha I meant to catch the other PRs, glad we got it here

**Comment by rpetit3** [comment]
oh, I had a typo `recipes/treemqc` should have been `recipes/treeqmc`

will submit a quick pr

**Pull request merged**
