### PR TITLE
added bioconductor-brain

### PR DESCRIPTION
**Pull request by MathiasHaudgaard**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by mbargull** [comment]
Thanks @MathiasHaudgaard.
Note for reviewers: This waits on https://github.com/conda-forge/staged-recipes/pull/4867 to be merged.

**Comment by bgruening** [comment]
Merged the conda-forge one.

**Comment by mbargull** [comment]
@bgruening: Looks like that "Rerun job with SSH" only runs that single job but not subsequent one which required the previous one. So you have to click on the "workflow" (`bioconda-test` for PRs) and then select to rerun failed jobs. Well, new system, still learning 😄

**Comment by mbargull** [comment]
Thanks or the recipe @MathiasHaudgaard !

**Comment by bgruening** [comment]
Meh, good to know. How counter intuitive :)

**Pull request merged**
