### PR TITLE
Updated dinopy to 2.0.0, removed old clutter from meta.yaml.

### PR DESCRIPTION
**Pull request by HenningTimm**
* [x] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by HenningTimm** [comment]
@bioconda/core I am a little stumped with this update. The PR tests (which are import tests only) fail:

```
10:22:01 BIOCONDA INFO TEST START via mulled-build recipes/dinopy, CONDA_BOOST=1.61;CONDA_GMP=5.1;CONDA_GSL=1.16;CONDA_HDF5=1.8.17;CONDA_HTSLIB=1.4;CONDA_NCURSES=5.9;CONDA_NPY=110;CONDA_PERL=5.22.0;CONDA_PY=35;CONDA_R=3.3.1
updating index in: /anaconda/conda-bld/linux-64
10:24:21 BIOCONDA ERROR TEST FAILED: recipes/dinopy, CONDA_BOOST=1.61;CONDA_GMP=5.1;CONDA_GSL=1.16;CONDA_HDF5=1.8.17;CONDA_HTSLIB=1.4;CONDA_NCURSES=5.9;CONDA_NPY=110;CONDA_PERL=5.22.0;CONDA_PY=35;CONDA_R=3.3.1
```

However, both running `conda build recipes/dinopy` (with different python versions) works and installation from PyPI into a python 3.4/ 3.5 conda environment with numpy 1.10.0 works as well. I also did not change anything but the file (to the new .tar.gz on PyPI), version number and md5.

What (kind of) error am I overlooking here?

**Comment by johanneskoester** [comment]
The error message have not been displayed due to a bug that I recently introduced in bioconda-utils. I have restarted the tests with a fix. I hope this will give you some insight.

**Comment by johanneskoester** [comment]
Here is the error: https://travis-ci.org/bioconda/bioconda-recipes/jobs/224292496#L1695

You need to include libgcc into your runtime dependencies. Also, please add gcc as a build dependency (if I am not mistaken you compile stuff using cython here).

**Comment by m00am** [comment]
Ah thanks :) I removed Cython as a (build and run) dependency. So that's how this did not show up in older versions.

**Comment by HenningTimm** [comment]
Ah thanks :) I removed Cython as a (build and run) dependency. So that's how this did not show up in older versions.

**Pull request merged**
