### PR TITLE
Update recipe for SpydrPick v1.2.0

### PR DESCRIPTION
**Pull request by santeripuranen**
Update the recipe for SpydrPick v1.2.0. These changes update build dependencies to Apegrunt v0.4.2 and simplifies the recipe by using the boost-cpp package instead of cloning+building the required Boost dependencies from scratch. We also remove patches that were required in the previous versions of this recipe, since the patched code has been merged to the upstream repositories.

----

* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [X] AFAIK, this recipe **is directly relevant to the biological sciences**
      (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [X] This PR updates an existing recipe.

### CODE REVIEW

**Comment by santeripuranen** [comment]
@BiocondaBot please add label

**Comment by bgruening** [comment]
@santeripuranen could you also package the other dependency which you currently git clone?

**Comment by santeripuranen** [comment]
@bgruening Thanks for your comment! Apegrunt is currently only a support library that doesn't do anything by itself. It's included as a submodule in the SpydrPick github project, but bioconda doesn't support submodules. I guess I could package Apegrunt at some point as well, once it has matured a bit more, but I'd rather not do that at this time.

**Comment by dpryan79** [comment]
@bioconda-bot please fetch artifacts

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Pull request merged**
