### PR TITLE
EDTA - fix and clean recipe

### PR DESCRIPTION
**Pull request by Juke34**
Remove dependencies used by annosine2:
 - bedtools
  - hmmer
  - irfinder
  - matplotlib-base
  - minimap2
  - nodejs
  - seqtk

Add dependencies: 
- pyarrow 
- r-base 
- r-dplyr 
- r-ggplot2 
- r-here 
- r-tidyr
- grep

Pin packages for TIR-Learner3 to make it work properly:
- h5py==3.9 
- keras==2.11 
- tensorflow==2.11

 change `EDTA_processI.pl` which must be superseded by `EDTA_processK.pl` in version 2.2

To test locally that the artifact is working properly this command must be successful (thread number to be adapted to what is available):

nohup perl ../EDTA.pl --genome genome.fa --cds genome.cds.fa --curatedlib ../database/rice7.0.0.liban --exclude genome.exclude.bed --overwrite 1 --sensitive 1 --anno 1 --evaluate 1 --threads 20 > EDTA.test

We may add this shortest test in the recipe:
`EDTA_raw.pl --genome genome.fa --type tir --threads 2`

### CODE REVIEW

**Comment by linnabrown** [comment]
@Juke34 Hi Juke, I also met the CircleCI issue. Do you have some idea how to resolve it? Thank you!
https://github.com/bioconda/bioconda-recipes/pull/45374

**Comment by oushujun** [comment]
@BiocondaBot please fetch artifacts

**Comment by Juke34** [comment]
> @Juke34 Hi Juke, I also met the CircleCI issue. Do you have some idea how to resolve it? Thank you! #45374

Sorry no idea

**Comment by oushujun** [comment]
@BiocondaBot please fetch artifacts

**Comment by oushujun** [comment]
It shows a conflict with `blast` and `rmblast` being the same version `2.14.1`. I submitted the feedback here: https://github.com/bioconda/bioconda-recipes/pull/43583. If this is not solved from the recipe, we will need to pin the blast version to `2.10.1`.

**Comment by oushujun** [comment]
@Juke34 we will need to pin `blast=2.10.1` as the `rmblast` couldn't solve this issue from the recipe.

**Comment by Juke34** [comment]
I hop this time it will be fine 🤞

**Comment by oushujun** [comment]
@BiocondaBot please fetch artifacts

**Comment by Juke34** [comment]
Sorry I. made a mistake when pinning blast

**Comment by Juke34** [comment]
should be better now

**Comment by oushujun** [comment]
samtools and bedtools are the only difference between [220ed3c](https://github.com/bioconda/bioconda-recipes/pull/45370/commits/220ed3c3c0a60dfe2bfd968958d0c0d9b94b05d0) (passed) and [499fef0](https://github.com/bioconda/bioconda-recipes/pull/45370/commits/499fef005bee528619e50d7a1910695fe9f8a00c) (failed)

```
14c14
<   number: 1
---
>   number: 2
21a22
>     - bedtools
23c24
<     - blast ==2.10.1
---
>     - blast 2.10.1 pl526he19e7b1_3
40a42
>     - perl-json
50a53
>     - samtools
62a66
>     - LTR_FINDER_parallel -check_dependencies > /dev/null
67c71
<   license_family: GPL
---
>   license_family: GPL3
70a75,82
>   doc_url: https://github.com/oushujun/EDTA/wiki
> 
> extra:
>   identifiers:
>     - doi:10.1186/s13059-019-1905-y
>     - doi:10.1101/2022.10.09.511471
>     - biotools:EDTA
>     - usegalaxy-eu:edta
```

Would it be these two dependencies conflicting `blast = 2.10.1`?

**Comment by oushujun** [comment]
@Juke34 

We are close to having everything ready for the recipe!

Please add ltr_harvest_parallel (https://github.com/bioconda/bioconda-recipes/pull/46623) and ltr_finder_parallel (https://github.com/bioconda/bioconda-recipes/pull/46624) to the EDTA recipe. 

Please remove the blast dependency to avoid the conflict with rmblast. The `blastn` program needed by EDTA can be provided by the rmblast package.

Thank you!
Shujun

**Comment by Juke34** [comment]
We get this error: `PermissionError: [Errno 13] Permission denied: 'gdb'` during the tests any idea what it could be and how to fix it? @oushujun ?

**Comment by Juke34** [comment]
There is a `No space left on device` also. I see that the Dfam DB is downloaded ` wget -O Dfam_curatedonly.h5.gz https://www.dfam.org/releases/Dfam_3.7/families/Dfam_curatedonly.h5.gz` how big is the DB once unzipped?
How much space is available to test the package, size max of a container in bioconda (@bgruening ?)?

**Comment by bgruening** [comment]
I don't know how much space is available in total, adding r-base is also an additional few 100MB. Does the DB need to be part of the package/container?

**Comment by oushujun** [comment]
Dfam_curatedonly.h5.gz is required by RepeatMasker/RepeatModeler and is 835M. Can you not include it in the recipe but download it while compiling it? I saw `qianjiangzhao::tetrimmer` is doing this trick. I am not sure if this applies here.

**Comment by Juke34** [comment]
> Dfam_curatedonly.h5.gz is required by RepeatMasker/RepeatModeler and is 835M. Can you not include it in the recipe but download it while compiling it? I saw `qianjiangzhao::tetrimmer` is doing this trick. I am not sure if this applies here.

I do not find any information about it. Could you point me to some resources?

For now I will deactivate the test that make the db downloaded

**Comment by oushujun** [comment]
@Juke34 it's in a private channel: https://anaconda.org/search?q=tetrimmer. I am asking the author to share more information if you cannot access it.

**Comment by oushujun** [comment]
Same problem for the RepeatMasker 4.1.6 recipe update: https://github.com/bioconda/bioconda-recipes/pull/45513

**Comment by TobyBaril** [comment]
Jumping on this after noticing the tag of RepeatMasker. There were some issues with permissions in the Azure DevOps environment which led to containers being pulled that were particularly large. Now this is fixed you should be able to configure with Dfam 3.7 curated elements, as we also had success doing this with Earl Grey + RepeatMasker 4.1.5 + RepeatModeler2. Hope this helps!

**Comment by martin-g** [comment]
It appears that the problem with the Linux x86_64 build of this recipe is with the memory usage:
```
...11:15:39 [32mBIOCONDA INFO[0m (ERR) [May  6 11:15:39] SOUT Collecting package metadata (repodata.json): ...working... done[0m
##[warning]Free memory is lower than 5%; Currently used: 95.38%
```
not the disk space as with EarlGrey.

**Comment by Juke34** [comment]
@martin-g Thank you for pointing it is the memory usage the problem and not the disk space.

**Comment by lutianyu2001** [comment]
Hi. I've updated the code in [EDTA/EDTA2](https://github.com/oushujun/EDTA/tree/EDTA2) branch, which support the conda package of tir-learner, ltr_finder_parallel, ltr_harvest_parallel and helitronscanner. These changes will be review and merged into the master branch by @oushujun in the future. Since current recipe are outdated after these updates, I've written an instruction for you to revise current EDTA recipe. 😉

---

## I. Instruction

1. Principle: Remove packages that are only used by TIR-Learner in "edta" recipe, as these are covered by "tir-learner" recipe

2. Remove TIR-Learner Dependencies:
    - biopython
    - genericrepeatfinder
    - glob2 (No longer needed by TIR-Learner)
    - h5py (No longer needed by TIR-Learner)
    - keras
    - multiprocess
    - regex
    - scikit-learn
    - swifter
    - tensorflow (No longer needed by TIR-Learner)

3. Keep Packages
    - bedtools: Altough no longer needed by TIR-Learner, still needed by **util/density_table.py**
    - genometools-genometools: Apart from TIR-Learner, also needed and widely used by EDTA
    - pandas: Apart from TIR-Learner, also needed by **util/paf2blast6_chunking2_parallel3_ordered_parts.py**

4. Add Package: 
    - helitronscanner

## II. Sample Result Recipe

This sample result recipe is produce by revising the newest recipe in the edta branch following the instructions above, and it can be used directly.

```
annosine2
bedtools
cd-hit
coreutils
genometools-genometools
grep
helitronscanner
ltr_finder_parallel
ltr_harvest_parallel
ltr_retriever
mdust
muscle
openjdk
pandas
perl
perl-json
perl-text-soundex
python >=3.8
pyarrow
r-base 
r-dplyr 
r-ggplot2 
r-here
r-tidyr
repeatmodeler
samtools
tesorter
tir-learner
```

**Comment by oushujun** [comment]
@Juke34 Please help to incorporate the change and test if it can pass. Thanks!

**Comment by Juke34** [comment]
Sure I will have a look at it

**Comment by Juke34** [comment]
Everything sounds fine excepted I need to point the recipe to the proper EDTA2 release that contain the mentioned updates which does not exist yet. Could you update or create a new pre-release @oushujun ?

**Comment by oushujun** [comment]
Hi @Juke34, I made a new release of EDTA, which should simplify the dependencies due to the update of TIR-Learner and blast. Can you please make a new recipe for this version? The manual installation command is:
`mamba create -n EDTA2.2 -c conda-forge -c bioconda -c r annosine2 biopython cd-hit coreutils genericrepeatfinder genometools-genometools glob2 tir-learner ltr_finder_parallel ltr_retriever mdust multiprocess muscle openjdk perl perl-text-soundex r-base r-dplyr regex repeatmodeler r-ggplot2 r-here r-tidyr tesorter samtools bedtools LTR_HARVEST_parallel HelitronScanner`

Thanks!
Shujun

**Comment by Juke34** [comment]
Yes sure I will look at that. 
Do you know what are the packages that use the r channel? Would be nice to avoid this channel...

**Comment by oushujun** [comment]
It seems that the r channel is avoidable. Please remove it from the dependency.

**Comment by Juke34** [comment]
@bioconda-bot please review

**Comment by Juke34** [comment]
@BiocondaBot please review & merge

**Review by bgruening — APPROVED** [review]
Thanks @Juke34

**Comment by oushujun** [comment]
Thank you all!!!

Shujun

**Comment by oushujun** [comment]
Hi @Juke34, I found some issues with this new recipe:
1. The `ltr_retriever` needs to be ≥3.0.0 to avoid a fatal bug in the earlier version.
2. The `LTR_FINDER_parallel` path is not correctly linked in conda env.
The correct path is `~/bin/miniconda3/envs/EDTA_conda/share/LTR_FINDER_parallel/LTR_FINDER_parallel`, which exists in the conda env, but the $ENV accessible version points to `~/bin/miniconda3/envs/EDTA_conda/share/EDTA/bin/LTR_FINDER_parallel/LTR_FINDER_parallel`. I actually don't know what is the cause of this issue. I used `mamba create -n EDTA_conda "bioconda::edta=2.2.2" -c conda-forge -c bioconda` for installation. Previously I used `EDTA_2.2.x.yml` to install and no such issue.

**Comment by Juke34** [comment]
The first point is easily fixable.
But I'm not sure to understand the second issue. The path differ but the tool is where the path point to? I will give a try using the container

**Comment by Juke34** [comment]
Right we where installing LTR_FINDER_parallel from EDTA repository in previous releases but now LTR_FINDER_parallel comes from the LTR_FINDER_parallel conda recipe and should be available in home by default...

**Comment by oushujun** [comment]
@Juke34 Since we make LTR_HARVEST_parallel an independent package similar to LTR_FINDER_parallel, the EDTA recipe should also do something similar for LTR_HARVEST_parallel:

```
LTR_FINDER_PARALLEL_DIR=${EDTA_DIR}/bin/LTR_FINDER_parallel

cat <<END >>${PREFIX}/bin/LTR_FINDER_parallel
#!/bin/bash
perl ${LTR_FINDER_PARALLEL_DIR}/LTR_FINDER_parallel \$@
END

chmod a+x ${PREFIX}/bin/LTR_FINDER_parallel
```

Right now LTR_HARVEST_parallel exit due to not finding the expected /bin/cut.pl script in it's own folder.

```
Can't open perl script "/home/ext29446/.conda/envs/EDTA/bin/bin/cut.pl": No such file or directory
No such file or directory at /home/ext29446/.conda/envs/EDTA/bin/LTR_HARVEST_parallel line 183.
```

Can you please help to fix this?

Thanks!
Shujun

**Pull request merged**
