### PR TITLE
Jalview 2.10.3 build 1 - patch for java 9 args

### PR DESCRIPTION
**Pull request by foreveremain**
* [*] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [ ] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [*] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by foreveremain** [comment]
@martin-mann forgot to include a minor tweak to the pesky java 9 args

**Comment by martin-mann** [comment]
there is always a build-number-1 .. *grin*

**Comment by martin-mann** [comment]
@foreveremain it seems there is a problem with the merging, since I squash/merged your halsview-2_10_3 branch already..

could you please move the change to a new branch and trigger a new pull request? think that will solve the issue (didnt we trigger similar stuff last time too? hehe..)

**Comment by foreveremain** [comment]
looking forward to a git version clever enough to unsquash the squashed commits :)

**Pull request closed without merging**
