### PR TITLE
Update duplex-tools to 0.2.17

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`duplex-tools`](https://bioconda.github.io/recipes/duplex-tools/README.html): **0.2.15** &rarr; **0.2.17**

[install with bioconda](http://bioconda.github.io/recipes/duplex-tools/README.html) [Conda](https://anaconda.org/bioconda/duplex-tools/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/duplex-tools`](https://github.com//bioconda/bioconda-recipes/tree/bump/duplex_tools/recipes/duplex-tools) (click to view/edit other files)
Summary | Duplex Tools contains a set of utilities for dealing with ONT Duplex sequencing data
Home | [https://github.com/nanoporetech/duplex-tools](https://github.com/nanoporetech/duplex-tools)
Releases |[https://pypi.org/pypi/duplex_tools/json](https://pypi.org/pypi/duplex_tools/json)

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Review by rpetit3 — APPROVED** [review]

**Comment by rpetit3** [comment]
@ollenordesjo I didn't see any dependency changes. Also, would you like to be added as a maintainer for this recipe?

**Comment by onordesjo** [comment]
Hi @rpetit3, correct, no dependency changes. Happy do be added as a maintainer yes. Please use @ollenordesjo rather than this user, thanks!

**Comment by rpetit3** [comment]
Great thank you, got you added. I'll get this merged after CI repasses.

**Comment by onordesjo** [comment]
Much appreciated, thanks!

**Comment by rpetit3** [comment]
@BiocondaBot please merge

**Pull request merged**
