### PR TITLE
Add recipe for mzml2isa, including dependencies

### PR DESCRIPTION
**Pull request by RJMW**
* [x] I have read the guidelines above.
* [x] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

@bioconda/core

### CODE REVIEW

**Comment by RJMW** [comment]
@bgruening - Please, can you have a look at the Travis CI build. It seems that the order in which the packages/dependencies are build is incorrect. The builds inside the (local) docker container run without any issues. Any suggestions?

**Comment by bgruening** [comment]
Super Ralf!

**Comment by RJMW** [comment]
Thanks for the quick reply! Indeed skipping the py3k works. It would be great if we can fix the DAG generator at some point. Shall we open an issue for this?

**Comment by bgruening** [comment]
Please do so and attach the yaml please. It's kind of unusal how you pined your version.

**Pull request merged**
