### PR TITLE
add crumble

### PR DESCRIPTION
**Pull request by maarten-k**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by maarten-k** [comment]
@bioconda-bot rebuild

**Comment by npavlovikj** [comment]
@maarten-k , since this is the first build of the package, the build number should be 0 instead, e.g. `number: 0`.
Regarding the license, "open source" should be fine, but you may want to open an issue upstream requesting for a license type and/or file. Then, in your yaml file, you can add comment with the link to issue.

**Comment by maarten-k** [comment]
@npavlovikj thanks for the feedback. I made the suggested changes.

**Comment by npavlovikj** [comment]
@BiocondaBot rebuild

**Comment by npavlovikj** [comment]
@maarten-k , can you please rebase with master?

**Comment by npavlovikj** [comment]
The changes look good to me. Since you are adding this recipe, you can also consder adding your GitHub id to the recipe maaintainer list, e.g.:
extra: 
recipe-maintainers
- maarten-k

**Comment by maarten-k** [comment]
I did not know about the recipe-maintainers option. Thanks!  (could not find info on https://bioconda.github.io/)

**Comment by npavlovikj** [comment]
@BiocondaBot rebuild

**Comment by npavlovikj** [comment]
@BiocondaBot merge

**Comment by npavlovikj** [comment]
Many thanks for adding and updating the recipe @maarten-k !

**Comment by epruesse** [comment]
We didn't use the `recipe-maintainer` much. Still don't. Right now it only means that you get pinged if autobump finds a new version for one of your packages. But it's good to start having data in there. I hope I'll get around to more mechanics that use it.

**Comment by maarten-k** [comment]
Nice! Thanks for the help and explanation

**Pull request merged**
