### PR TITLE
Update tobias to 0.9.0

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`tobias`](https://bioconda.github.io/recipes/tobias/README.html): **0.8.0** &rarr; **0.9.0**

[install with bioconda](http://bioconda.github.io/recipes/tobias/README.html) [Conda](https://anaconda.org/bioconda/tobias/files)

Info | Link
-----|-----
Recipe | [`recipes/tobias`](https://github.com//bioconda/bioconda-recipes/tree/bump/tobias/recipes/tobias) (click to view/edit other files)
Releases |[https://pypi.org/pypi/tobias/json](https://pypi.org/pypi/tobias/json)
Recipe Maintainer(s) | @msbentsen, @jenzopr

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by dpryan79** [comment]
@bioconda-bot please update

**Comment by dpryan79** [comment]
I encountered an error updating your PR branch. You can report this to bioconda/core if you'd like.
-The Bot

**Comment by dpryan79** [comment]
@bioconda-bot please update

**Comment by dpryan79** [comment]
I encountered an error updating your PR branch. You can report this to bioconda/core if you'd like.
-The Bot

**Comment by dpryan79** [comment]
@bioconda-bot hello

**Comment by dpryan79** [comment]
Is it me you're looking for?
> I can see it in your eyes.

**Comment by dpryan79** [comment]
@bioconda-bot please update

**Comment by dpryan79** [comment]
I encountered an error updating your PR branch. You can report this to bioconda/core if you'd like.
-The Bot

**Comment by dpryan79** [comment]
@bioconda-bot please update

**Comment by dpryan79** [comment]
I encountered an error updating your PR branch. You can report this to bioconda/core if you'd like.
-The Bot

**Comment by dpryan79** [comment]
I encountered an error updating your PR branch. You can report this to bioconda/core if you'd like.
-The Bot

**Comment by dpryan79** [comment]
@bioconda-bot please update

**Comment by dpryan79** [comment]
I encountered an error updating your PR branch. You can report this to bioconda/core if you'd like.
-The Bot

**Comment by dpryan79** [comment]
I encountered an error updating your PR branch. You can report this to bioconda/core if you'd like.
-The Bot

**Comment by msbentsen** [comment]
There are some problems with the dependencies for this package at the moment hence the failing build. I have been trying to resolve them in #18805 but have not managed completely yet - sorry for the mess!

**Comment by dpryan79** [comment]
No worries, this gives me a PR to use to test out my reimplementation of the bot.

**Comment by dpryan79** [comment]
@bioconda-bot please update

**Comment by dpryan79** [comment]
I encountered an error updating your PR branch. You can report this to bioconda/core if you'd like.
-The Bot

**Comment by dpryan79** [comment]
I encountered an error updating your PR branch. You can report this to bioconda/core if you'd like.
-The Bot

**Comment by dpryan79** [comment]
Ooooo, the update command works now :)

**Pull request closed without merging**
