### PR TITLE
Stuttgart Neural Network Simulator (SNNS)

### PR DESCRIPTION
**Pull request by peterjc**
* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [X] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

The licensing for SNNS is unclear (*update - that's been fixed*), but I would like to package it for clinod - see #4675 / #4774

### CODE REVIEW

**Comment by peterjc** [comment]
Oh, good news http://www.ra.cs.uni-tuebingen.de/SNNS/licence.html says "The Licensing Terms for SNNS have significantly changed from Verion 4.2 to Version 4.3. SNNS is now available under the LGPL Version 2." even though the tar-bar seems not to mention this 👍

**Comment by peterjc** [comment]
The provided configure script does not like macOS,

```
checking build system type... configure: error: cannot guess build type; you must specify one
```

How can I flag the recipe as Linux only?

**Comment by peterjc** [comment]
Finally, this recipe is working.

As discussed on #4774 in line with @johanneskoester's suggestion this uses the provided 64-bit Linux binaries (since I was unable to get their code to compile, something wrong with finding the flex libraries).

They do not provide macOS binaries, and their configuration scripts do not support it.

Note I have not included a test for the provided GUI tool.

**Comment by peterjc** [comment]
I'm not 100% sure from reading their documentation if the flex and/or bison tools are needed at runtime. There are references to using these tools if rebuilding a model. I've never used their tools directly myself though.

**Comment by bgruening** [comment]
Thanks for checking!

**Comment by peterjc** [comment]
Cheers.

**Pull request merged**
