### PR TITLE
delly: pin boost-cpp

### LINKED ISSUE #48755: tb-profiler installation broken due to transitive dependency on boost-cpp
When running tb-profiler v6.2.1, installed in a fresh conda env using this command:

```
conda create -n tb-profiler-6.2.1-test tb-profiler=6.2.1
```

...we see this error when running `tb-profiler profile`

```
[09:54:04] INFO     Running delly
bam.py:88           
ERROR    delly: error while loading shared libraries: libboost_iostreams.so.1.85.0: cannot open shared object file: No such file or directory
utils.py:485 
                                                                                                                                                                                                                                           Traceback (most recent call last):
  File "envs/tb-profiler-6.2.1-test/bin/tb-profiler", line 587, in <module>
    args.func(args)
  File "envs/tb-profiler-6.2.1-test/bin/tb-profiler", line 101, in main_profile
    variants_profile = pp.run_profiler(args)                                                                                                                    ^^^^^^^^^^^^^^^^^^^^^
File "envs/tb-profiler-6.2.1-test/lib/python3.12/site-packages/pathogenprofiler/cli.py", line 192, in run_profiler 
    get_vcf_file(args)
  File "envs/tb-profiler-6.2.1-test/lib/python3.12/site-packages/pathogenprofiler/cli.py", line 174, in get_vcf_file
    args.vcf = get_vcf_from_bam(args)                                                                                                            ^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                                                         File "envs/tb-profiler-6.2.1-test/lib/python3.12/site-packages/pathogenprofiler/cli.py", line 154, in get_vcf_from_bam                                                                                                  delly_vcf_obj = bam.run_delly(conf['bed'])                                                                                                                                                                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                                                File "envs/tb-profiler-6.2.1-test/lib/python3.12/site-packages/pathogenprofiler/bam.py", line 91, in run_delly                                                                                                          run_cmd("delly call -t DEL -g %(ref_file)s %(bam_file)s -o %(prefix)s.delly.bcf" % vars(self))                                                                                                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                            File "envs/tb-profiler-6.2.1-test/lib/python3.12/site-packages/pathogenprofiler/utils.py", line 486, in run_cmd                                                                                                         raise ValueError("Command Failed:\n%s\nstderr:\n%s" % (cmd,result.stderr.decode()))
ValueError: Command Failed:
/bin/bash -c set -o pipefail; delly call -t DEL -g envs/tb-profiler-6.2.1-test/share/tbprofiler/tbdb.fasta test_output/9b599f3e-e9e4-422f-bf43-5175a38a0ddc.bam -o test_output/9b599f3e-e9e4-422f-bf43-5175a38a0ddc.delly.bcf
stderr:
delly: error while loading shared libraries: libboost_iostreams.so.1.85.0: cannot open shared object file: No such file or directory
```
(forgive the formatting... I had to manually re-format that message)


I can see that `boost-cpp` is included in the test env, but we `boost-cpp 1.78.0`:

```
conda list                                                                                                                                                                                                                                # packages in environment at envs/tb-profiler-6.2.1-test:                                                                                  # 
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
alsa-lib                  1.2.11               hd590300_1    conda-forge
annotated-types           0.7.0              pyhd8ed1ab_0    conda-forge
attr                      2.5.1                h166bdaf_1    conda-forge
bcftools                  1.20                 h8b25389_0    bioconda
bedtools                  2.31.1               hf5e1c6e_1    bioconda
bitstring                 3.1.9              pyhd8ed1ab_0    conda-forge
boost-cpp                 1.78.0               h2c5509c_4    conda-forge
brotli                    1.1.0                hd590300_1    conda-forge
```

...so if I'm interpreting this right, we should pin boost-cpp to v1.85.0 on the delly recipe. I'm not sure if there's a more permissive way to define that pin that would still ensure compatibility.

### PR DESCRIPTION
**Pull request by dfornika**
Describe your pull request here

Fixes #48755 

tb-profiler has a transitive dependency: tb-profiler ->pathogen-profiler -> delly -> boost-cpp.

delly (an optional part of the `tb-profiler profile` workflow) is failing because it expects a different version of boost-cpp from what is installed within the context of a tb-profiler conda env.

If we pin boost-cpp in the delly recipe, that should ensure that the correct version of boost-cpp is installed.

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

### General instructions

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

### Instructions for avoiding API, ABI, and CLI breakage issues
Conda is able to record and lock (a.k.a. pin) dependency versions used at build time of other recipes.
This way, one can avoid that expectations of a downstream recipe with regards to API, ABI, or CLI are violated by later changes in the recipe.
If not already present in the meta.yaml, make sure to specify `run_exports` (see [here](https://bioconda.github.io/contributor/linting.html#missing-run-exports) for the rationale and comprehensive explanation).
Add a `run_exports` section like this:

```yaml
build:
  run_exports:
    - ...

```

with `...` being one of:

| Case                             | run_exports statement                                               |
| -------------------------------- | ------------------------------------------------------------------- |
| semantic versioning              | `{{ pin_subpackage("myrecipe", max_pin="x") }}`     |
| semantic versioning (0.x.x)      | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}`   |
| known breakage in minor versions | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| known breakage in patch versions | `{{ pin_subpackage("myrecipe", max_pin="x.x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| calendar versioning              | `{{ pin_subpackage("myrecipe", max_pin=None) }}`    |

while replacing `"myrecipe"` with either `name` if a `name|lower` variable is defined in your recipe or with the lowercase name of the package in quotes.

### Bot commands for PR management

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

Note that the <code>@BiocondaBot please merge</code> command is now depreciated. Please just squash and merge instead.

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by aliciaaevans** [comment]
The OSX failure is related to `std::binary_function` which apparently was removed in c++17. It would be best if it can be fixed upstream in delly. 

I'm guessing there are probably some updates to the build.sh that could work around the error, but I'll leave that to someone that has more c++ experience than I have.

**Comment by jmarshall** [comment]
It is trivially easy to fix the `std::binary_function` thing (just remove it!), so could be patched locally if it has not yet been fixed upstream.

Does the recipe set any `‑std=c++NN` options? Is there a reason not to work around this just by adding `‑std=c++14` or so to the recipe?

**Comment by jmarshall** [comment]
@BiocondaBot please fetch artifacts

**Comment by jmarshall** [comment]
@BiocondaBot please fetch artifacts

**Comment by jmarshall** [comment]
Build failure resolved by fixing _build.sh_ so it doesn't remove delly's `-std=c++11`.

I have no opinion on whether pinning libboost is the best approach here. It's a little unfortunate that the `libboost >=1.85.0` dependency doesn't have an upper bound like the others and as would probably be provided if boost's run_exports were working to provide the requirement here, but basically this is now good to go IMHO.

**Comment by dfornika** [comment]
Thanks for swooping in @aliciaaevans and @jmarshall !!! I was reaching the limits of my bioconda expertise there.

If either of you are able to approve & merge this that would be appreciated, otherwise I'll wait until @pvanheus has a chance to look at it.

**Review by pvanheus — APPROVED** [review]

**Pull request merged**
