### PR TITLE
add new recipe for bwa-meme modes

### PR DESCRIPTION
**Pull request by quito418**
Describe your pull request here

Add BWA-MEME, faster BWA-MEM2 with learned-index. 
There are total of 3 modes available, trying to support the package for each mode.
- [paper link](https://academic.oup.com/bioinformatics/advance-article/doi/10.1093/bioinformatics/btac137/6543607?login=true) 
- [github link](https://github.com/kaist-ina/BWA-MEME)
----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by quito418** [comment]
@BiocondaBot please add label

**Comment by dpryan79** [comment]
@BiocondaBot please fetch artifacts

**Comment by dpryan79** [comment]
What's the difference between these modes?

**Comment by quito418** [comment]
> What's the difference between these modes?

Hello, 

Each mode of BWA-MEME uses different runtime memory and internal algorithms.
(Mode 1: 38 GB, Mode 2: 88GB, BWA-MEME: 118GB)

We wanted to minimize the change in the command line for users who use BWA-MEM2.

Therefore, we thought dividing the package with respect to modes was a better option.

Thank you

**Comment by dpryan79** [comment]
So the binaries themselves have different modes? As an end user it'd be preferable to either have a single front-end executable with a `--mode 2` option or to have a single package with appropriately named executables for each mode rather than 3 different packages.

**Comment by quito418** [comment]
You might be right, thank you for the suggestion.

I will integrate the modes in a single executable.

**Pull request closed without merging**
