### PR TITLE
megahit: add linux-aarch64 build

### PR DESCRIPTION
**Pull request by martin-g**
Describe your pull request here

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

### General instructions

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

### Instructions for avoiding API, ABI, and CLI breakage issues
Conda is able to record and lock (a.k.a. pin) dependency versions used at build time of other recipes.
This way, one can avoid that expectations of a downstream recipe with regards to API, ABI, or CLI are violated by later changes in the recipe.
If not already present in the meta.yaml, make sure to specify `run_exports` (see [here](https://bioconda.github.io/contributor/linting.html#missing-run-exports) for the rationale and comprehensive explanation).
Add a `run_exports` section like this:

```yaml
build:
  run_exports:
    - ...

```

with `...` being one of:

| Case                             | run_exports statement                                               |
| -------------------------------- | ------------------------------------------------------------------- |
| semantic versioning              | `{{ pin_subpackage("myrecipe", max_pin="x") }}`     |
| semantic versioning (0.x.x)      | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}`   |
| known breakage in minor versions | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| known breakage in patch versions | `{{ pin_subpackage("myrecipe", max_pin="x.x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| calendar versioning              | `{{ pin_subpackage("myrecipe", max_pin=None) }}`    |

while replacing `"myrecipe"` with either `name` if a `name|lower` variable is defined in your recipe or with the lowercase name of the package in quotes.

### Bot commands for PR management

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

Note that the <code>@BiocondaBot please merge</code> command is now depreciated. Please just squash and merge instead.

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by martin-g** [comment]
depends on https://github.com/voutcn/megahit/pull/368

**Comment by martin-g** [comment]
@BiocondaBot please fetch artifacts

**Comment by martin-g** [comment]
```

mgrigorov in 🌐 euler-arm-22 in /tmp/megahit took 10s 
❯ tar jxvf megahit-1.2.9-hf1d9491_5.tar.bz2 
info/run_exports.json
info/test/run_test.sh
info/recipe/build.sh
info/hash_input.json
info/index.json
info/files
info/recipe/meta.yaml.template
info/recipe/linux-aarch64-support-pr-368.patch
info/recipe/meta.yaml
info/paths.json
info/recipe/conda_build_config.yaml
info/about.json
info/licenses/LICENSE
info/git
bin/megahit_toolkit
bin/megahit
bin/megahit_core
bin/megahit_core_no_hw_accel
bin/megahit_core_popcnt
share/megahit/test_data/generate_random_fasta.py
share/megahit/test_data/r1.il.fa.gz
share/megahit/test_data/r4.fa
share/megahit/test_data/loop.fa
share/megahit/test_data/ref.fa
share/megahit/test_data/r3_1.fa
share/megahit/test_data/r3_2.fa
share/megahit/test_data/empty.fa
share/megahit/test_data/r2.il.fa.bz2

mgrigorov in 🌐 euler-arm-22 in /tmp/megahit 
❯ file bin/*
bin/megahit:                  Python script, ASCII text executable
bin/megahit_core:             ELF 64-bit LSB pie executable, ARM aarch64, version 1 (GNU/Linux), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, with debug_info, not stripped
bin/megahit_core_no_hw_accel: ELF 64-bit LSB pie executable, ARM aarch64, version 1 (GNU/Linux), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, with debug_info, not stripped
bin/megahit_core_popcnt:      ELF 64-bit LSB pie executable, ARM aarch64, version 1 (GNU/Linux), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, with debug_info, not stripped
bin/megahit_toolkit:          symbolic link to megahit_core_no_hw_accel

mgrigorov in 🌐 euler-arm-22 in /tmp/megahit 
❯ ./bin/megahit_core
Usage: ./bin/megahit_core <sub_program> [sub options]
    sub-programs:
       assemble       assemble from SdBG
       local          local asssembly
       iterate        extract iterative edges
       buildlib       build read library
       count          kmer counting
       read2sdbg      build sdbg from reads
       seq2sdbg       build sdbg from megahit contigs + edges
       contig2fastg   convert MEGAHIT's k*.contigs.fa to fastg format
       readstat       calculate read stats (# of reads, bases, longest, shortest, average)
       filterbylen    filter contigs by length
       checkcpu       check whether the run-time CPU supports POPCNT and BMI2
       checkpopcnt    check whether the run-time CPU supports POPCNT
       checkbmi2      check whether the run-time CPU supports BMI2
       dumpversion    dump version
       kmax           the largest k value supported
```

LGTM!

**Comment by martin-g** [comment]
@BiocondaBot please add label

**Comment by mencian** [comment]
Thanks @martin-g!

**Pull request merged**
