### PR TITLE
Bump and fix blast legacy

### PR DESCRIPTION
**Pull request by druvus**
- [x] I have read the guidelines above.
- [ ] This PR adds a new recipe.
- [x] This PR updates an existing recipe.
- [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by druvus** [comment]
NCBI provide as-is pre-compiled binaries but they doesn't work for linux. Seems to be some compiler incompatibility both for the previous included and the newest version.  

A better option would be to compile blast from source using the NCBI toolkit (ftp://ftp.ncbi.nlm.nih.gov/blast/executables/legacy/2.2.26/ncbi.tar.gz). The build scripts are quite extensive so does anyone have experience of build blast from source with a minimal build script? 

This is also valid for other ncbi tools included in the ncbi toolkit, such as tbl2asn. 
@bioconda/core

**Comment by tomkinsc** [comment]
It would be great to have tbl2asn built from source.

**Comment by martin-mann** [comment]
I will have a look if there is some magic going on when building the NCBI toolkit from source..

**Comment by martin-mann** [comment]
@druvus : have send a pull request to your branch, which compiles ncbi tools from source. It is not thoroughly tested yet and was not checked by travis. please have a look!

**Comment by druvus** [comment]
The build fails due to that we don't have csh installed on the image. I am not using that shell so often so I don't know if we can get it installed by conda.

**Comment by druvus** [comment]
Closing this PR as it seems to be a solution in #2795 .

**Comment by jlanga** [comment]
#2795 refers to `blast+`, not `blast-legacy`. For a while NCBI developed both at the same time and they even share version numbers.

**Comment by acaprez** [comment]
Sorry to bump an old thread, but I was looking into adding `blast-legacy` 2.2.26 using the pre-built binaries just now.  @druvus - what's the issue you mentioned with using the NCBI provided binaries on linux?  They seem to work on EL6 and EL7 - or does the problem only show up when running with real input?

**Pull request closed without merging**
