### PR TITLE
various fixes for bulk

### PR DESCRIPTION
**Pull request by dpryan79**
* [ ] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [ ] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [x] This PR does something else (explain below).

### CODE REVIEW

**Comment by dpryan79** [comment]
@bgruening When you have a chance, please merge.

**Comment by dpryan79** [comment]
I also need to figure out how to add `conda-forge/noarch` to the list of channels, since the noarch R packages don't get the gcc7 label on conda-forge.

**Comment by bgruening** [comment]
> I also need to figure out how to add conda-forge/noarch to the list of channels, since the noarch R packages don't get the gcc7 label on conda-forge. 

This is a bug on conda-forge. Please give me a list of packages that you found and add the label for the time being.

**Comment by dpryan79** [comment]
@bgruening r-catnet and r-smoother for starters. I actually got the feeling that that was intentional on the side of conda-forge.

**Comment by bgruening** [comment]
Done. r-catnet is not a noarch. So this is really a bug on there end.

**Pull request merged**
