### PR TITLE
Update el_gato to 1.20.1

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`el_gato`](https://bioconda.github.io/recipes/el_gato/README.html): **1.19.0** &rarr; **1.20.1**

[install with bioconda](http://bioconda.github.io/recipes/el_gato/README.html) [Conda](https://anaconda.org/bioconda/el_gato/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/el_gato`](https://github.com//bioconda/bioconda-recipes/tree/bump/el_gato/recipes/el_gato) (click to view/edit other files)
Summary | Perform Legionella pneumophila Sequence Based Typing (SBT) from short reads or assemblies.
Home | [https://github.com/appliedbinf/el_gato](https://github.com/appliedbinf/el_gato)
Releases |[https://github.com/appliedbinf/el_gato/tags](https://github.com/appliedbinf/el_gato/tags)
Author | `@appliedbinf`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by Alan-Collins** [comment]
@mencian Thanks for tidying up the recipe. The build is now failing because the database files that were being copied in the build.sh script aren't found. Are you able to offer any guidance here on how to fix this issue? Is the `$PREFIX` environment variable the correct way to refer to the conda environment prefix in the meta.yaml or does that need to be changed as well?

**Comment by martin-g** [comment]
It looks to me that the DB files were created by https://github.com/bioconda/bioconda-recipes/pull/51051/files#diff-23e0b91a3b7cd25eeb68639a967975077fa68686b822522cc35970d2fed9b2dcL3
Now `pip install` is called after trying to copy the DB files.

**Comment by Alan-Collins** [comment]
Yes, I saw the changes you made. However, the build now fails saying it is unable to find one of the files which should have been copied. It seems to be looking in the wrong location now:

`FileNotFoundError: [Errno 2] No such file or directory: '/opt/conda/conda-bld/el_gato_1727712929695/_h_env_placehold_.../bin/all_loci.fasta.ndb'`

That file should be in /opt/conda/conda-bld/el_gato.../bin/db/

Before your changes, the build failed with `importlib.metadata.PackageNotFoundError: elgato`, but passed the steps that are now failing.

**Comment by mencian** [comment]
Closing in favor of #51484.

**Pull request closed without merging**
