### PR TITLE
kraken 0.10.5-beta

### PR DESCRIPTION
**Pull request by yesimon**
This is based on latest git.

### CODE REVIEW

**Comment by yesimon** [comment]
#390 was pointing to the wrong base branch.

**Comment by johanneskoester** [comment]
Is there a good reason for including unreleased software into Bioconda? In other words, is there no stable release of kraken?

**Comment by yesimon** [comment]
The maintainer doesn't seem to look at pull requests and it looked like it wouldn't be updated much anymore, however there was an update today to fix the refseq ftp directory move. The old I would recommend sitting on this for a little bit.

That being said the version number is especially weird as all releases are called v0.1x.x-beta. I assume the beta actually means that the major version number is less than 1.

**Comment by johanneskoester** [comment]
I see. If you know the software, you can certainly judge, so I'm fine with whatever decision you make.

**Comment by lpantano** [comment]
@yesimon thanks to do this. we are waiting for this tool to be in bioconda so we can move completely to depend only on bioconda!.thanks!

**Comment by yesimon** [comment]
@lpantano I repushed the pr based on the released version v0.10.5-beta tags so we can get it included for now.

**Comment by chapmanb** [comment]
Thanks so much for the recipe. I'm not sure about the current status: are there any blockers/objections to merging this?

**Comment by yesimon** [comment]
I don't think so.

**Pull request merged**
