### PR TITLE
Entrez direct

### PR DESCRIPTION
**Pull request by jfear**
* [x] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

Updates to the latest version of Entrez direct to work with new https requirements.

### CODE REVIEW

**Comment by daler** [comment]
@bgruening do we have a date set for when all new perl-dependent recipes should use conda-forge's perl instead of bioconda's perl-threaded?

**Comment by daler** [comment]
So should this one have `perl-threaded` or `perl`?

**Comment by bgruening** [comment]
It's find as it is :)

**Comment by bgruening** [comment]
Thanks @jfear!

**Pull request merged**
