### PR TITLE
Add r-circrnafull recipe

### PR DESCRIPTION
**Pull request by nictru**
This adds the [circrnafull](https://github.com/tofazzalh/circRNAFull) R package

### CODE REVIEW

**Comment by nictru** [comment]
@BiocondaBot please add label

**Comment by nictru** [comment]
@BiocondaBot please fetch artifacts

**Comment by nictru** [comment]
Still have a question: When would I set the `max_pin` to `x.x` instead of `x`? I saw `x.x` with most R packages but I am a bit unsure as [last time I was corrected](https://github.com/bioconda/bioconda-recipes/pull/48519/commits/86a26663320228f5b15e501107e6fbb882a0eb9c) to `x` (although not an R package there)

**Comment by martin-g** [comment]
> Still have a question: When would I set the `max_pin` to `x.x` instead of `x`? I saw `x.x` with most R packages but I am a bit unsure as [last time I was corrected](https://github.com/bioconda/bioconda-recipes/pull/48519/commits/86a26663320228f5b15e501107e6fbb882a0eb9c) to `x` (although not an R package there)

Please read the [Pull Request template](https://github.com/bioconda/bioconda-recipes/blob/master/.github/PULL_REQUEST_TEMPLATE.md#instructions-for-avoiding-api-abi-and-cli-breakage-issues).
It explains when to use `"x"`, `"x.x"` or `None`

**Comment by nictru** [comment]
Okay thanks (sorry for not reading the docs)
The `x` option should be sufficient here.

**Review by aliciaaevans — APPROVED** [review]
Thanks!

**Pull request merged**
