### PR TITLE
add fastqz

### PR DESCRIPTION
**Pull request by MathiasHaudgaard**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by MathiasHaudgaard** [comment]
@bgruening I'm getting an error in the test. I've tried several approaches but none of them seem to work. I get the error message: .Passing program arguments as a string may be a security hazard if combined with untrusted input.

**Comment by micknudsen** [comment]
@MathiasHaudgaard Are you sure the test fails due to "Passing program arguments as a string may be a security hazard if combined with untrusted input"? It looks a like a warning (and not something that would fail). Have you tried printing the output of your test commands and see if it really is as expected?

**Comment by MathiasHaudgaard** [comment]
@micknudsen yes I have. It seems like when i'm using _2>&1 | grep_  the error occurs. I'm not sure what causes this problem.

**Comment by MathiasHaudgaard** [comment]
@bgruening maybe it's a bit of a hack, but i'm downloading libzpaq with wget and the use it for compilation. You can see it in build.sh
@micknudsen the problem is that the -h flag returns 1 which causes the error. That's why i'm using **2>&1**. It used to work but i've experienced this error several times now.

**Comment by daler** [comment]
Closing due to inactivity, please re-open if needed.

**Pull request closed without merging**
