### PR TITLE
Update sdeper to 1.1.0

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`sdeper`](https://bioconda.github.io/recipes/sdeper/README.html): **1.0.0** &rarr; **1.1.0**

[install with bioconda](http://bioconda.github.io/recipes/sdeper/README.html) [Conda](https://anaconda.org/bioconda/sdeper/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/sdeper`](https://github.com//bioconda/bioconda-recipes/tree/bump/sdeper/recipes/sdeper) (click to view/edit other files)
Summary | Spatial Deconvolution method with Platform Effect Removal
Home | [https://az7jh2.github.io/SDePER/](https://az7jh2.github.io/SDePER/)
Releases |[https://pypi.org/pypi/sdeper/json](https://pypi.org/pypi/sdeper/json)
Recipe Maintainer(s) | @az7jh2

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by az7jh2** [comment]
We have chosen to omit version 1.0.1 from Bioconda, even though the corresponding PyPI package operates correctly. This decision stems from the fact that we import custom modules from the `src` folder within the `setup.py` file. While this works seamlessly on PyPI, it leads to the `src` module not being recognized in Bioconda. We intend to address this in a subsequent release.

**Comment by az7jh2** [comment]
please close this PR. Thanks!

**Comment by dpryan79** [comment]
We need to leave this open for now as otherwise it'll just be created again automatically.

**Comment by az7jh2** [comment]
@dpryan79 thank you for the comment. Just a quick question, when we have released new version higher than this version 1.0.1, let's say 1.1.0, and the bioconda package has been updated to that version 1.1.0. Can this PR be closed at that time?

**Pull request closed without merging**
