### PR TITLE
Update rnashapes

### PR DESCRIPTION
**Pull request by sjanssen2**
This is bumping the version to 3.3.2
Changes:
* patch should be obsolete due to changes in upstream
* using latest version of bellmans-gapc to account for energy parameter fixes (as in ViennaRNA)
* minor changes in Perl wrapper:
  * trigger warnings for macrostate energy computation
  * warn for alignment + window energy discrepancies

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Review by dlaehnemann — CHANGES_REQUESTED** [review]
Thanks for updating this.

Could we move the newest version to the main folder of this recipe (i.e. `recipes/rnashapes/` instead of `recipes/rnashapes/3.3.0`). The alternative would be to put it into a `/3.3.2/` folder, but generally a proper versioning in the main folder will reduce the accumulation of archival package versions in the current folder structure for the future. So making this move while dropping the patch seems like a good idea.

Apart from this, all the updates look good to me!

**Comment by sjanssen2** [comment]
Thanks @dlaehnemann. I like your idea and thus moved both files into the base dir.

**Comment by dlaehnemann** [comment]
Great!

I would keep the old version 3.3.0 folder around for documentation, though. At least that's how this was done elsewhere, for example see the samtools recipe:
https://github.com/bioconda/bioconda-recipes/tree/master/recipes/samtools

**Comment by sjanssen2** [comment]
sorry, I got you wrong. Old files should be back now

**Review by dlaehnemann — APPROVED** [review]
Perfect!

**Comment by dlaehnemann** [comment]
@BiocondaBot please merge

**Pull request merged**
