### PR TITLE
Rebuild quorum (compiler)

### PR DESCRIPTION
**Pull request by epruesse**
Rebuild [`quorum`](https://bioconda.github.io/recipes/quorum/README.html) to update pinnings

[install with bioconda](http://bioconda.github.io/recipes/quorum/README.html) [Conda](https://anaconda.org/bioconda/quorum/files)

Info | Link
-----|-----
Recipe | [`recipes/quorum`](https://github.com//bioconda/bioconda-recipes/tree/bump/quorum/recipes/quorum) (click to view/edit other files)
Releases |[https://github.com/gmarcais/Quorum/releases](https://github.com/gmarcais/Quorum/releases)
Author | `@gmarcais`
***

Rebuild is necessary for the following reasons:
- Recompiling with gxx

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/updating.html)).

### CODE REVIEW

**Comment by dpryan79** [comment]
jellyfish should really get updated first.

**Comment by epruesse** [comment]
Did that have a pending update? Curious. Autobump shouldn't have filed this if there was a possible upgrade on jellyfish.

**Comment by epruesse** [comment]
Ahhh ... https://github.com/bioconda/bioconda-recipes/issues/6107

**Comment by dpryan79** [comment]
That jellyfish name collision is unfortunate, they have similarish download metrics.

**Comment by dpryan79** [comment]
Xref: https://github.com/conda-forge/jellyfish-feedstock/issues/10

**Comment by epruesse** [comment]
Our package is 11 months older....

**Comment by dpryan79** [comment]
Sure, the one here is older, has more downloads, and has a less obvious rename. I'll suggest renaming the other one `python-jellyfish`.

**Pull request merged**
