### PR TITLE
copied gobject-introspection recipe from ostrokach

### PR DESCRIPTION
**Pull request by ThomasWollmann**
* [x] I have read the guidelines above.
* [x] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by ThomasWollmann** [comment]
Any ideas for tests?

**Comment by bgruening** [comment]
Sorry Thomas, but you need to adjust the recipes a little bit to stick to our guidelines.
https://bioconda.github.io/guidelines.html

For example the build number should start with 0. You should use gcc/llvm explicitly and so on.
For libraries you can for example use this as test: https://github.com/conda-forge/libglu-feedstock/blob/master/recipe/meta.yaml#L20

**Comment by bgruening** [comment]
@ThomasWollmann the merge seem odd again :)
@ostrokach would you be interested to join bioconda and contribute your great packages to bioconda and those basic packages maybe to conda-forge?

**Comment by bgruening** [comment]
This is now in conda-forge.

**Pull request closed without merging**
