### PR TITLE
update mantis 1.4.9

### PR DESCRIPTION
**Pull request by PedroMTQ**
Describe your pull request here

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by bgruening** [comment]
@PedroMTQ there is nothing in this PR :)

**Comment by PedroMTQ** [comment]
@bgruening sorry my bad. forgot to push the changes 
should be fine now

**Comment by PedroMTQ** [comment]
@bgruening 
`10:53:41 BIOCONDA INFO (ERR) [Mar  2 10:53:41] DEBU Run file [/usr/share/miniconda/envs/bioconda/lib/python3.7/site-packages/galaxy/tools/deps/mulled/invfile.lua]
10:53:41 BIOCONDA INFO (ERR) [Mar  2 10:53:41] INFO Invoke Task [build]
10:53:41 BIOCONDA INFO (ERR) [Mar  2 10:53:41] STEP Run image [quay.io/bioconda/create-env:2.1.0] with command [[rm -rf /data/dist]]
10:53:41 BIOCONDA INFO (ERR) [Mar  2 10:53:41] DEBU Creating container [step-186e04a68d]
10:53:41 BIOCONDA INFO (ERR) [Mar  2 10:53:41] DEBU Image [quay.io/bioconda/create-env:2.1.0] not present, pulling it
10:53:41 BIOCONDA INFO (ERR) [Mar  2 10:53:41] DEBU Pull Image [quay.io/bioconda/create-env:2.1.0]
10:54:03 BIOCONDA INFO (ERR) [Mar  2 10:54:03] WARN Pull may have failed due to missing authentication information in ~/.involucro
10:54:03 BIOCONDA INFO (ERR) [Mar  2 10:54:03] ERRO Task processing failed: API error (500): {"message":"Head \"[https://quay.io/v2/bioconda/create-env/manifests/2.1.0\"](https://quay.io/v2/bioconda/create-env/manifests/2.1.0/%22): Get \"[https://quay.io/v2/auth?scope=repository%3Abioconda%2Fcreate-env%3Apull&service=quay.io\"](https://quay.io/v2/auth?scope=repository%3Abioconda%2Fcreate-env%3Apull&service=quay.io\%22): net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"}
10:54:03 BIOCONDA INFO (ERR) 
.10:54:41 BIOCONDA INFO (OUT) .
10:54:41 BIOCONDA ERROR COMMAND FAILED (e`

I'm getting this error. I'm not sure why?

**Comment by PedroMTQ** [comment]
@BiocondaBot please add label

**Pull request merged**
