### PR TITLE
Update mummer4 to fix mummerplot

### PR DESCRIPTION
**Pull request by apigatto**
Implements https://github.com/mummer4/mummer/issues/36#issuecomment-420684643 to fix mummerplot.

### CODE REVIEW

**Comment by apigatto** [comment]
@BiocondaBot please add label

**Comment by dpryan79** [comment]
@BiocondaBot please fetch artifacts

**Comment by dpryan79** [comment]
Please increment the build number.

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@BiocondaBot please merge

**Pull request merged**
