### PR TITLE
Update bioconductor annotate - bioconda_uilts bioc-test

### PR DESCRIPTION
**Pull request by bgruening**
* [x] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by johanneskoester** [comment]
Nothing was built because bioconductor-annotate is in the r-blacklist.

**Comment by bgruening** [comment]
ping @johanneskoester!

**Comment by johanneskoester** [comment]
Seems to work. Nice!

**Comment by bgruening** [comment]
:)
How do we want to proceed from here on?

**Comment by johanneskoester** [comment]
Once the R recipe PR also passes (maybe with another R recipe), you can merge the bioconda-utils-soft branch into master. I'll then rebuild our docker container, and we can switch to the bioconda docker image again.
If everything works ok, we should reduce the verbosity of bioconda-utils.

And then, I would say we should wait with rebuilding R and bioconductor until the prefix fix (conda build 2.0?) is out in the next few weeks. It makes no sense to rebuild all those packages twice, right?

**Comment by johanneskoester** [comment]
Rebased to #2274.

**Pull request merged**
