### PR TITLE
knotinframe & bellmans-gapc: add linux-aarch64 build

### PR DESCRIPTION
**Pull request by martin-g**
Describe your pull request here

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

### General instructions

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

### Instructions for avoiding API, ABI, and CLI breakage issues
Conda is able to record and lock (a.k.a. pin) dependency versions used at build time of other recipes.
This way, one can avoid that expectations of a downstream recipe with regards to API, ABI, or CLI are violated by later changes in the recipe.
If not already present in the meta.yaml, make sure to specify `run_exports` (see [here](https://bioconda.github.io/contributor/linting.html#missing-run-exports) for the rationale and comprehensive explanation).
Add a `run_exports` section like this:

```yaml
build:
  run_exports:
    - ...

```

with `...` being one of:

| Case                             | run_exports statement                                               |
| -------------------------------- | ------------------------------------------------------------------- |
| semantic versioning              | `{{ pin_subpackage("myrecipe", max_pin="x") }}`     |
| semantic versioning (0.x.x)      | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}`   |
| known breakage in minor versions | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| known breakage in patch versions | `{{ pin_subpackage("myrecipe", max_pin="x.x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| calendar versioning              | `{{ pin_subpackage("myrecipe", max_pin=None) }}`    |

while replacing `"myrecipe"` with either `name` if a `name|lower` variable is defined in your recipe or with the lowercase name of the package in quotes.

### Bot commands for PR management

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

Note that the <code>@BiocondaBot please merge</code> command is now depreciated. Please just squash and merge instead.

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by martin-g** [comment]
The ARM64 builds depend on:
- https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/6166

**Comment by martin-g** [comment]
@BiocondaBot please fetch artifacts

**Comment by martin-g** [comment]
```
mgrigorov in 🌐 euler-arm-22 in /tmp/bellmans-gapc via 🅒 test123 took 3s 
❯ tar xvf bellmans-gapc-2024.01.12-h9419716_2.tar.bz2                                                                                                                                                      (test123) 
info/test/run_test.sh
info/run_exports.json
info/hash_input.json
info/index.json
info/has_prefix
info/recipe/build.sh
info/recipe/meta.yaml.template
info/files
info/recipe/meta.yaml
info/recipe/conda_build_config.yaml
info/about.json
info/paths.json
info/licenses/LICENSE
info/git
share/gapc/librna/rnalib.c
include/rtlib/cstr.h
include/librna/rnalib.h
include/rtlib/string.cc
include/rtlib/generic_main.cc
share/gapc/librna/rna_misc_special_hairpins.par
share/gapc/librna/rna_langdon2018.par
share/gapc/librna/rna_andronescu2007.par
share/gapc/librna/rna_turner1999.par
share/gapc/librna/dna_mathews1999.par
share/gapc/librna/dna_mathews2004.par
share/gapc/librna/rna_turner2004.par
lib/librna.so
lib/librnafast.so
share/gapc/examples/adpf_filter.hh
include/rtlib/hash.hh
include/rtlib/bigint.hh
include/rtlib/asymptotics.hh
include/rtlib/output.hh
include/rtlib/move.hh
include/rtlib/singleton.hh
include/rtlib/rational.hh
include/rtlib/erase.hh
include/rtlib/adp.hh
include/rtlib/pool.hh
include/rtlib/float_accuracy_operators.hh
include/rtlib/ref.hh
include/rtlib/multipool.hh
include/rtlib/shape_alph.hh
include/rtlib/cm_alph.hh
include/rtlib/fair_mutex.hh
include/rtlib/bench.hh
include/rtlib/sample.hh
share/gapc/examples/nonamb_answer.hh
include/rtlib/hashlist.hh
include/rtlib/bitops.hh
include/rtlib/hash_stats.hh
include/rtlib/empty.hh
include/rtlib/filter.hh
include/rtlib/subopt.hh
include/rtlib/pareto_dom_sort.hh
include/rtlib/subsequence.hh
include/rtlib/adp_specialization/pareto_0_nosort_step.hh
include/rtlib/range.hh
include/rtlib/adp_specialization/pareto_0_nosort_block.hh
include/rtlib/map_pool.hh
share/gapc/examples/pf_filter.hh
include/rtlib/push_back.hh
include/rtlib/list.hh
include/rtlib/rules.hh
include/rtlib/terminal.hh
include/rtlib/vector_sparse.hh
include/rtlib/sequence.hh
include/rtlib/algebra.hh
include/rtlib/adp_specialization/pareto_1_sorted_step.hh
include/rtlib/hashtng.hh
include/rtlib/fair_shared_mutex.hh
include/rtlib/backtrack.hh
include/rtlib/generic_opts.hh
include/rtlib/string.hh
include/rtlib/table.hh
include/rtlib/pareto_yukish.hh
include/rtlib/adp_specialization/pareto_1_sorted_block.hh
include/rtlib/pareto_yukish_ref.hh
include/rtlib/shape.hh
include/rtlib/rope.hh
include/rtlib/adp_specialization/pareto_3_yukish_step.hh
include/rtlib/adp_specialization/pareto_3_yukish_block.hh
include/rtlib/rna.hh
include/rtlib/adp_specialization/sort_block.hh
bin/gapc
share/gapc/examples/nussinov2.gap
share/gapc/examples/affinelocsim2.gap
share/gapc/examples/elm.gap
share/gapc/examples/adpf.gap
share/gapc/examples/adpf_nonamb.gap
share/gapc/config_linux-gnu.mf

mgrigorov in 🌐 euler-arm-22 in /tmp/bellmans-gapc via 🅒 test123 
❯ file bin/*                                                                                                                                                                                               (test123) 
bin/gapc: ELF 64-bit LSB pie executable, ARM aarch64, version 1 (GNU/Linux), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, with debug_info, not stripped

mgrigorov in 🌐 euler-arm-22 in /tmp/bellmans-gapc via 🅒 test123 
❯ ./bin/gapc                                                                                                                                                                                               (test123) 
No filename specified.
```

```
mgrigorov in 🌐 euler-arm-22 in /tmp/bellmans-gapc/fff via 🅒 test123 took 2s 
❯ tar xvf knotinframe-2.3.1-h78569d1_1.tar.bz2                                                                                                                                                             (test123) 
info/run_exports.json
info/test/run_test.sh
info/hash_input.json
info/has_prefix
info/recipe/build.sh
info/index.json
info/files
info/recipe/meta.yaml.template
info/recipe/meta.yaml
info/paths.json
info/recipe/conda_build_config.yaml
info/about.json
info/licenses/LICENSE
info/git
bin/addRNAoptions.pl
bin/knotinframe
bin/knotinframe_nested
bin/knotinframe_knotted
lib/foldGrammars/ClusterSettings.pm
lib/foldGrammars/CMs.pm
lib/foldGrammars/NewCollection.pm
lib/foldGrammars/Settings.pm
lib/foldGrammars/RNAcast.pm
lib/foldGrammars/References.pm
lib/foldGrammars/RapidShapes.pm
lib/foldGrammars/Structure.pm
lib/foldGrammars/Testing.pm
lib/foldGrammars/Utils.pm
lib/foldGrammars/IO.pm

mgrigorov in 🌐 euler-arm-22 in /tmp/bellmans-gapc/fff via 🅒 test123 
❯ file bin/*                                                                                                                                                                                               (test123) 
bin/addRNAoptions.pl:    Perl script text executable
bin/knotinframe:         Perl script text executable
bin/knotinframe_knotted: ELF 64-bit LSB pie executable, ARM aarch64, version 1 (GNU/Linux), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, with debug_info, not stripped
bin/knotinframe_nested:  ELF 64-bit LSB pie executable, ARM aarch64, version 1 (GNU/Linux), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, with debug_info, not stripped

mgrigorov in 🌐 euler-arm-22 in /tmp/bellmans-gapc/fff via 🅒 test123 took 29s 
❯ ./bin/knotinframe_knotted                                                                                                                                                                                (test123) 
Exception: Missing input sequence or no -f.
```
LGTM!

**Comment by martin-g** [comment]
@BiocondaBot please add label

**Review by aliciaaevans — APPROVED** [review]

**Pull request merged**
