### PR TITLE
Add recipe for trimmomatic 0.38

### PR DESCRIPTION
**Pull request by dansondergaard**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by dansondergaard** [comment]
Tested this locally, but I don't have write access to the repo, so CircleCI won't run the build.

**Comment by dansondergaard** [comment]
Rebased current branch and fixed various errors. Should be good to go now :-)

**Comment by bgruening** [comment]
Thanks Dan!

**Comment by dansondergaard** [comment]
Thank *you*, @bgruening ;-)

**Pull request merged**
