### PR TITLE
plastid - fix using incompatible numpy

### PR DESCRIPTION
**Pull request by lparsons**
* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [X] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [X] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by dpryan79** [comment]
The repodata indicates that the pinning should work properly this time, so :+1: and I'll merge this once the CI testing finishes.

**Comment by dpryan79** [comment]
Is this linking against pysam too? In that case it needs the same max_pin change.

**Comment by lparsons** [comment]
It is linking against pysam, but I thought the pin compatible would handle that? The reason for the bumpy issue is an API change in bumpy that broke things. Happy to update if it does indeed need that. I still don't think I understand what pin_compatible is doing...

--
Lance Parsons - Scientific Programmer
Carl C. Icahn Laboratory - Room 136
Lewis-Sigler Institute for Integrative Genomics
Princeton University

________________________________

**Comment by dpryan79** [comment]
There's no pinning done for pysam normally, so as is this ends up pinning it to `pysam >=0.15.2,<1.0a0`, which won't work. So yes, please add `max_pin='x.x'` or maybe `max_pin='x.x.x'` (the latter may be overkill, but since I don't use cython with pysam I'm not sure).

**Comment by lparsons** [comment]
Thanks @epruesse. I think this is ready to go, perhaps one quick check on the repo.json when the bioconda bot produces it.

**Comment by lparsons** [comment]
Hmmm... Not sure I understand what happened here, but the max_pin on pysam is now gone...

**Comment by epruesse** [comment]
you force pushed ... overwriting the part where I had added it.

**Comment by lparsons** [comment]
OK, put the `max_pin` back.

**Comment by dpryan79** [comment]
I made the pysam pinning a bit stricter, hopefully that will future-proof things.

**Pull request merged**
