### PR TITLE
Update macrel to 0.5.0

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`macrel`](https://bioconda.github.io/recipes/macrel/README.html): **0.4.0** &rarr; **0.5.0**

[install with bioconda](http://bioconda.github.io/recipes/macrel/README.html) [Conda](https://anaconda.org/bioconda/macrel/files)

Info | Link
-----|-----
Recipe | [`recipes/macrel`](https://github.com//bioconda/bioconda-recipes/tree/bump/macrel/recipes/macrel) (click to view/edit other files)
Releases |[https://github.com/BigDataBiology/macrel/tags](https://github.com/BigDataBiology/macrel/tags)
Recipe Maintainer(s) | @luispedro
Author | `@BigDataBiology`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by luispedro** [comment]
@BiocondaBot please fetch artifacts

**Comment by dpryan79** [comment]
@bioconda-bot please fetch artifacts

**Comment by dpryan79** [comment]
@luispedro This is building now. You might try building on OSX again and see if that works.

**Comment by luispedro** [comment]
Thanks! The mac os x is due to another dependency, so that's still waiting for a deeper fix (https://github.com/bioconda/bioconda-recipes/pull/21697/)

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Pull request merged**
