### PR TITLE
Allow GTDB-Tk database download with container

### PR DESCRIPTION
**Pull request by rpetit3**
I'm using the GTDB-Tk container to download the database, but am running into `conda` missing. Here's the error message:

```
  [INFO] - Downloading the GTDB-Tk database to: ./results
  [INFO] - Extracting archive...
  [INFO] - The GTDB-Tk database has been successfully downloaded and extracted.

... TRUNCATED ...

  100%|█████████▉| 139815/139919 [16:49<00:07, 14.58file/s]
  100%|█████████▉| 139886/139919 [16:56<00:02, 14.01file/s]
  139920file [16:56, 137.69file/s]
  /usr/local/bin/download-db.sh: line 39: conda: command not found
```

This runs conda, and if missing notifies the user conda is missing and to manually set the env variable

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by rpetit3** [comment]
@biocondabot please fetch artifacts

**Review by aaronmussig — APPROVED** [review]

**Comment by aaronmussig** [comment]
Cheers!

**Comment by aaronmussig** [comment]
@BiocondaBot please merge

**Comment by rpetit3** [comment]
Looks like we should be set on the container
```
docker run --rm -u $(id -u):$(id -g) -v ${PWD}:/data quay.io/biocontainers/gtdbtk:2.1.0--pyhdfd78af_5 download-db.sh /data/gtdb-download
[INFO] - Downloading the GTDB-Tk database to: /data/gtdb-download
Connecting to data.gtdb.ecogenomic.org (203.101.230.53:443)
saving to '/data/gtdb-download/gtdbtk_r207_v2_data.tar.gz'
gtdbtk_r207_v2_data.   0% |                                |  431k 47:35:18 ETA
gtdbtk_r207_v2_data.   0% |                                | 9695k  3:46:52 ETA
gtdbtk_r207_v2_data.   0% |                                | 24.1M  2:13:26 ETA

... TRUNCATED ...

gtdbtk_r207_v2_data.  99% |******************************* | 62.6G  0:00:06 ETA
gtdbtk_r207_v2_data.  99% |******************************* | 62.6G  0:00:05 ETA
gtdbtk_r207_v2_data.  99% |******************************* | 62.6G  0:00:03 ETA
gtdbtk_r207_v2_data.  99% |******************************* | 62.7G  0:00:02 ETA
gtdbtk_r207_v2_data.  99% |******************************* | 62.7G  0:00:01 ETA
gtdbtk_r207_v2_data.  99% |******************************* | 62.7G  0:00:00 ETA
gtdbtk_r207_v2_data. 100% |********************************| 62.7G  0:00:00 ETA
'/data/gtdb-download/gtdbtk_r207_v2_data.tar.gz' saved
[INFO] - Extracting archive...
139920file [14:47, 157.66file/s]
[INFO] - The GTDB-Tk database has been successfully downloaded and extracted.
/usr/local/bin/download-db.sh: line 39: conda: command not found
[INFO] - Conda not found in PATH, please be sure to set the TARGET_DIR envrionment variable

echo $?
0
```

**Pull request merged**
