### PR TITLE
Update HairSplitter

### PR DESCRIPTION
**Pull request by RolandFaure**
Update HairSplitter version to 1.8.0

### CODE REVIEW

**Comment by RolandFaure** [comment]
@BiocondaBot hello

**Comment by RolandFaure** [comment]
@BiocondaBot merge

**Comment by martin-g** [comment]
@BiocondaBot please add label

**Review by rpetit3 — APPROVED** [review]

**Comment by rpetit3** [comment]
@BiocondaBot please fetch artifacts

**Pull request merged**
