### PR TITLE
Update nextstrain-cli to 3.11, add dependencies, remove test step

### PR DESCRIPTION
**Pull request by victorlin**
Update nextstrain-cli, including:

- Version bump to 3.11 (supersedes #33446)
- Add dependency `docutils` (supersedes #32628)
- Add dependency `wcmatch`
- Remove a test step that requires additional package install

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by victorlin** [comment]
@bioconda/core could you advise on the failing test here?

I ran locally and compared the outputs.

[Azure pipeline run](https://dev.azure.com/bioconda/bioconda-recipes/_build/results?buildId=12906&view=logs&j=e14e69ff-a0ae-55c4-b71d-229b239cfb2f&t=7df82132-b284-504b-53d6-7d3e63519572&l=137):

```
20:36:24 BIOCONDA INFO (OUT) Preparing transaction: ...working... done
20:36:27 BIOCONDA INFO (OUT) Verifying transaction: ...working... done
20:36:35 BIOCONDA INFO (OUT) Executing transaction: ...working... done
.20:36:56 BIOCONDA INFO (OUT) Collecting package metadata (repodata.json): ...working... done
...20:40:33 BIOCONDA INFO (OUT) Solving environment: ...working... /opt/build_script.bash: line 22:    57 Killed                  conda build --override-channels --no-anaconda-upload -c conda-forge -c bioconda -c defaults -e /opt/host-conda-bld/conda_build_config_0_-e_conda_build_config.yaml -e /opt/host-conda-bld/conda_build_config_1_-e_bioconda_utils-conda_build_config.yaml /opt/recipe/meta.yaml 2>&1
20:40:35 BIOCONDA ERROR COMMAND FAILED (exited with 137): docker run -t --net host --rm -v /tmp/tmpydm03ay8/build_script.bash:/opt/build_script.bash -v /usr/share/miniconda/envs/bioconda/conda-bld/:/opt/host-conda-bld -v /home/vsts/work/1/s/recipes/nextstrain-cli:/opt/recipe -e LANG=C.UTF-8 -e HOST_USER_ID=1001 quay.io/bioconda/bioconda-utils-build-env-cos7:0.18.5 /bin/bash /opt/build_script.bash

20:40:35 BIOCONDA ERROR BUILD FAILED recipes/nextstrain-cli
20:40:35 BIOCONDA INFO (COMMAND) conda build purge
20:40:37 BIOCONDA ERROR BUILD SUMMARY: of 1 recipes, 1 failed and 0 were skipped. Details of recipes and environments follow.
20:40:37 BIOCONDA ERROR BUILD SUMMARY: FAILED recipe recipes/nextstrain-cli
##[error]Bash exited with code '1'.
##[section]Finishing: Test
```

Local run:

```
19:53:13 BIOCONDA INFO (OUT) Preparing transaction: ...working... done
19:53:15 BIOCONDA INFO (OUT) Verifying transaction: ...working... done
19:53:20 BIOCONDA INFO (OUT) Executing transaction: ...working... done
19:53:31 BIOCONDA INFO (OUT) Collecting package metadata (repodata.json): ...working... done
...19:56:41 BIOCONDA INFO (OUT) Solving environment: ...working... done
19:56:41 BIOCONDA INFO (OUT) Source cache directory is: /opt/homebrew/Caskroom/miniconda/base/envs/bioconda/conda-bld/src_cache
19:56:41 BIOCONDA INFO (ERR) INFO:conda_build.source:Source cache directory is: /opt/homebrew/Caskroom/miniconda/base/envs/bioconda/conda-bld/src_cache
19:56:41 BIOCONDA INFO (ERR) INFO conda_build.source:download_to_cache(41): Source cache directory is: /opt/homebrew/Caskroom/miniconda/base/envs/bioconda/conda-bld/src_cache
19:56:41 BIOCONDA INFO (OUT) Found source in cache: nextstrain-cli-3.1.0_7484b4965b.tar.gz
19:56:41 BIOCONDA INFO (ERR) INFO:conda_build.source:Found source in cache: nextstrain-cli-3.1.0_7484b4965b.tar.gz
19:56:41 BIOCONDA INFO (ERR) INFO conda_build.source:download_to_cache(63): Found source in cache: nextstrain-cli-3.1.0_7484b4965b.tar.gz
...
```

It looks like the pipeline is failing on solving the environment (`Killed`). Could this be related to conda/conda#7614?

**Comment by victorlin** [comment]
Actually does seem like a memory issue, similar to #32487. It's true that we have lots of testing (probably not necessary to run on bioconda), but I'm confused since it looks like the error happens before running any tests.

**Comment by victorlin** [comment]
@tsibley I had to remove the zika build from `run-test.sh` to get bioconda CI to pass. My hunch is that `augur`'s [long list of dependencies](https://github.com/bioconda/bioconda-recipes/blob/498d0eb50d308a1e4c5199ccd4615fb8df3bf192/recipes/augur/meta.yaml#L23-L38) is too much for the CI server to handle when resolving the conda dependency tree.

This should be fine since we only have bioconda updates once it gets bumped on PyPI, which is after our own CI tests pass right?

**Comment by tsibley** [comment]
@victorlin I concur that the issue appears to be an OOM condition in this repo's CI. That's unfortunate and could likely be addressed (not by us).

"Should be fine", yes… but this means we won't catch a packaging error in this recipe that impacts an actual `nextstrain build` invocation if it doesn't impact the other tests. We've accidentally introduced such packaging (for PyPI) errors in the past, which is why we now include an actual build in our CI tests by default.

**Comment by victorlin** [comment]
> That's unfortunate and could likely be addressed (not by us)

Yeah, we're effectively blocked from making any changes to this recipe due to the OOM issue which [has been observed by others](https://github.com/bioconda/bioconda-recipes/search?q=exited+with+137&type=issues).

I'm going to open this PR to unblock nextstrain/cli#150 and also have latest version available through bioconda, since I've tested locally and it works. If this gets merged, I'll open another PR to add the tests back and that can be merged whenever OOM issues are resolved.

**Comment by victorlin** [comment]
@BiocondaBot please add label

**Comment by dpryan79** [comment]
For full tests we encourage you to fetch the artifacts and run full tests locally.

**Comment by tsibley** [comment]
> For full tests we encourage you to fetch the artifacts and run full tests locally.

:-/ That's unfortunate. Local testing doesn't address running on a variety of platforms and introduces yet another manual step to maintaining Bioconda packages.

**Comment by huddlej** [comment]
@victorlin @tsibley I encountered a similar error last year with [an Augur autobump PR for a patch release](https://github.com/bioconda/bioconda-recipes/pull/30047#issuecomment-899240707). I traced the issue to Snakemake's increased dependency complexity (testing locally on my own memory-limited machine) and fixed the issue by [removing Snakemake as a dependency](https://github.com/bioconda/bioconda-recipes/pull/30081).

I'm surprised that even `snakemake-minimal` isn't "minimal" enough to work, here, but the Snakemake/Conda issues are many and complicated...

**Pull request merged**
