### PR TITLE
Add CTAT-SPLICING

### PR DESCRIPTION
**Pull request by micknudsen**
Recipe for [CTAT-SPLICING](https://github.com/ncip/ctat-splicing). Includes the following commands:

* `STAR_to_cancer_introns`
* `ctat-splicing-lib-integration`

The `STAR_to_cancer_introns` script has an optional `--bam_file` option requiring the embedded `bamsifter` tool which must first be compiled. I've failed doing that and I would appreciate any help I can get.

Everything else works. I have fetched artifacts and tested locally on data.

### CODE REVIEW

**Comment by micknudsen** [comment]
@bioconda-bot please fetch artifacts

**Comment by micknudsen** [comment]
@bioconda-bot please fetch artifacts

**Comment by micknudsen** [comment]
@bioconda-bot please fetch artifacts

**Comment by micknudsen** [comment]
@bioconda-bot please fetch artifacts

**Comment by micknudsen** [comment]
@bioconda-bot please fetch artifacts

**Comment by micknudsen** [comment]
@bioconda-bot please fetch artifacts

**Comment by micknudsen** [comment]
@bioconda-bot please fetch artifacts

**Comment by micknudsen** [comment]
@bioconda-bot please fetch artifacts

**Comment by micknudsen** [comment]
> Hi @micknudsen - I've done a PR against this branch in your fork with some patches that (at least locally) make the build work for me.

Thanks. I would never have figured this out myself! 👍

**Comment by micknudsen** [comment]
@pvanheus Thanks for assisting. After merging your changes, I had to add some additional build requirements, but after that I still get the same `g++: No such file or directory` error. Do you have any ideas how to proceed?

**Comment by pvanheus** [comment]
How I got around that error in a local build was using autoconf 2.69. Apparently this error happens with later versions. Then yes, you need those bzip2, etc dependencies. The htslib build needs them.

I'll check later with a build in Docker to isolate it from my machine environment.

**Comment by pvanheus** [comment]
@micknudsen I think that the problem is that the bamsifter Makefile hardcodes the call the `g++` - I have sent you another PR with a patch that works around this - give it a go.

**Comment by pvanheus** [comment]
@micknudsen I think that the problem is that the bamsifter Makefile hardcodes the call the `g++` - I have sent you another PR with a patch that works around this - give it a go.

**Comment by micknudsen** [comment]
> @micknudsen I think that the problem is that the bamsifter Makefile hardcodes the call the `g++` - I have sent you another PR with a patch that works around this - give it a go.

@pvanheus Thanks. Unfortunately, it still fails. Now for a different reason, though. I'm not sure how much time it is worth spending on this, as it seems to be a rather tricky issue. I have made a package without the BAM support and uploaded it to my own anaconda channel, and that is all I need for my own production workflow. Whenever I encounter bioinformatics software that I need which is not on bioconda, I always first try to contribute a recipe to help others in the same situation, but this exceeds my abilities 😓

**Comment by pvanheus** [comment]
Glad that you got enough of it working for your needs @micknudsen. My impression of the upstream package is that it is not well packaged and is beyond a typical C/C++ package in difficulty of packaging. Pity.

**Pull request closed without merging**
