### PR TITLE
Set trinity java version

### PR DESCRIPTION
**Pull request by tomkinsc**
* [x] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

java version specified as minimum version, and trinity patched to allow java or openjdk

### CODE REVIEW

**Comment by yesimon** [comment]
Thank you!

**Comment by yesimon** [comment]
Just a question: why did you specify java >= 7? Shouldn't it be <= 8 because that's what we know it works with?

**Comment by tomkinsc** [comment]
We actually know it works with java >=6, up to I believe 8. I've make it a range [6,8].

**Comment by yesimon** [comment]
Don't forget to increment the build number

**Comment by tomkinsc** [comment]
I did forget! Thanks. Serves me right for trying to work while home sick.

**Pull request merged**
