### PR TITLE
Downgrade networkx dependency

### PR DESCRIPTION
**Pull request by vladsaveliev**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

Networkx has recently been updated to 2.0, which is incompatible with `colormath` `spectra` dependency (see https://github.com/ewels/MultiQC/pull/561 and 
https://github.com/ewels/MultiQC/issues/592). Until a new `colormath` version is released, we have to downgrade `networkx` dependency for MultiQC.

cc @ewels

### CODE REVIEW

**Comment by vladsaveliev** [comment]
@ewels, travis still fails because of that Click error here https://github.com/bioconda/bioconda-recipes/pull/5541 and here https://github.com/bioconda/bioconda-recipes/pull/5888, but as far as I understand it's just Travis related issue and the recipe looks good. Do you have any suggestions how we proceed and get this and #5888 merged?

**Comment by ewels** [comment]
Umm, hope that someone from @bioconda/core can help and come up with a long term solution where the locale is set in the busybox..? ;)

But otherwise I guess our only option is to go back to skipping the python 3 build:

```yaml
build:
  skip: true  # [py3k]
```

**Comment by ewels** [comment]
ps.. Other option could possibly be to just remove all tests? Then at least it should build for people using conda versions on their systems, even if the docker containers are broken. Thoughts @bioconda/core ?

**Comment by bgruening** [comment]
@ewels I will have finished the R3.4 migration soon and will have a look at it.
Sorry that it takes so long.

**Comment by daler** [comment]
@bgruening @vladsaveliev @ewels I think the issue is that we have 3 docker containers in play which have mutually incompatible locale settings.

`conda build` is run on `condaforge/linux-anvil`. This has `en_US.UTF-8` but does not have `C.UTF-8`:
```
docker run -it condaforge/linux-anvil
(root) [root@25975080fb60 /]# export LC_ALL=C.UTF-8
bash: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8): No such file or directory
bash: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)

(root) [root@123012ab5f3d /]# export LC_ALL="en_US.UTF-8"  # works fine

```

`mulled-build` by default uses busybox, which has no locale installed.

The extended-base container has `C.UTF-8` but not `en_US.UTF-8`:

```
docker run -it bitnami/minideb:jessie
root@cf34d7a492d4:/# LC_ALL=C.UTF-8 # works fine
root@cf34d7a492d4:/# export LC_ALL=en_US.UTF-8 
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8): No such file or directory
```

I think this should fix it: https://github.com/bioconda/bioconda-extended-base-image/pull/3

xrefs #5842, #5541, #5369, #5249, #4811

**Comment by daler** [comment]
Whoo!

**Comment by vladsaveliev** [comment]
That's awesome. Thanks for sorting it out!

**Comment by ewels** [comment]
Fantastic! Python3 conda builds again! 🎉  Awesome stuff @daler, thanks!

**Pull request merged**
