### PR TITLE
Update post-link.sh

### PR DESCRIPTION
**Pull request by pwwang**
Fix https://github.com/bioconda/bioconda-recipes/issues/31349

### CODE REVIEW

**Review by daler — APPROVED** [review]

**Comment by daler** [comment]
@bioconda-bot please fetch artifacts

**Comment by kstangline** [comment]
@daler @pwwang This issue may be related. https://github.com/bioconda/bioconda-recipes/issues/36436

**Comment by pwwang** [comment]
> @daler @pwwang This issue may be related. https://github.com/bioconda/bioconda-recipes/issues/36436

I believe so. Better solution is to use wget instead of curl.

**Comment by daler** [comment]
I think this is now an issue with all bioconductor data packages, which have now been moved to using XSEDE mirrors, seems to be originally discussed [prior to March](https://bioconductor.org/about/technical-advisory-board/2022-03-03-minutes.pdf). The `-L` appears to fix it.

**Comment by daler** [comment]
Merging this; will update all others subsequently.

**Comment by daler** [comment]
@BiocondaBot please merge

**Comment by zwhitfield** [comment]
@daler Like the others here, I just recently this same issue with the genomeinfodbdata package. Thank you for working to get the fix from pwwang merged in.
I've now encountered a similar issue with the go.db package, where the post-link.sh script fails in the same way. When you mentioned earlier "will update all others subsequently", does that mean you're working on updating all packages where this would be an issue? Or is it better to open a new GitHub Issue. Thank you.

**Comment by shufanzhang** [comment]
I also have this problem when install ”monocle“ with conda，post-link script failed to download "GenomeInfoDbData_1.2.7.tar.gz" and "HSMMSingleCell_1.14.0.tar.gz". I agree with @pwwang , better solution is to use wget instead of curl.
For reference: https://stackoverflow.com/questions/20986395/why-does-curl-not-work-but-wget-works

**Comment by hermidalc** [comment]
> @daler Like the others here, I just recently this same issue with the genomeinfodbdata package. Thank you for working to get the fix from pwwang merged in. I've now encountered a similar issue with the go.db package, where the post-link.sh script fails in the same way. When you mentioned earlier "will update all others subsequently", does that mean you're working on updating all packages where this would be an issue? Or is it better to open a new GitHub Issue. Thank you.

@daler ditto for me, since need to also use `bioconductor-go.db` package for an analysis

**Comment by hermidalc** [comment]
Sorry this is worse than I thought, I cannot install any conda environment where somewhere in the dep tree it needs `bioconductor-go.db` even if my project isn't explcitly using it.

**Comment by shufanzhang** [comment]
@hermidalc @zwhitfield 
I solve my problem with mamba. The problem is conda can not download some packages, so I turn to "mamba" for help. Fortunately, it worked. I think mamba may help you slove this problem.
` conda create -n monocle2`
`conda activate monocle2`
`mamba install -c bioconda -c conda-forge bioconductor-monocle glib r-seurat`

**Comment by hermidalc** [comment]
@shufanzhang I only ever use mamba and still had the error I reported. I believe the bioconda devs fix made it to monocle now when you tried it again

**Comment by hermidalc** [comment]
As of now this morning if I do
```
mamba create -n bioconductor-go
mamba activate bioconductor-go
mamba install -c bioconda -c conda-forge bioconductor-go.db
```
it still fails with postlink.sh download URL md5sum mismatch errors

**Comment by JakeLehle** [comment]
I would like to echo what @hermidalc said I am also having this issue with the poslink.sh still having mismatched md5sums

Here is the error I got.
image

The MD5's for the three URLs don't match.

The MD5 for the first URL https://bioconductor.org/packages/3.14/data/annotation/src/contrib/GenomeInfoDbData_1.2.7.tar.gz is 74c82f26111062a9ceb3c5331088cd56 as indicated in the meta.yaml file.
However, the MD5 for https://bioarchive.galaxyproject.org/GenomeInfoDbData_1.2.7.tar.gz is f0696c1d7060c62b7bfcd32eea0cfe53 and
the MD5 for is https://depot.galaxyproject.org/software/bioconductor-genomeinfodbdata/bioconductor-genomeinfodbdata_1.2.7_src_all.tar.gz is also f0696c1d7060c62b7bfcd32eea0cfe53.

Please take a look at this @pwwang when you get a chance and try to unify the MD5's.

Maybe switching curl with wget?
Thanks!

**Comment by shufanzhang** [comment]
@hermidalc You are right. The problem is still not completely resolved. When I install other packages, GenomeInfoDbData_1.2.7.tar.gz still has the problem of not being able to download, even if I use mamba.

**Comment by pwwang** [comment]
@shufanzhang @JakeLehle @hermidalc Could you guys confirm which version you were installing? `bioconductor-genomeinfodbdata-1.2.7-r41hdfd78af_2` works for me. Note the build number is `2`.

**Comment by JakeLehle** [comment]
Thanks for getting back to everyone on the weekend.

Looks Like I have build number 2 version 1.2.7

image

**Comment by kstangline** [comment]
Hello, as others have posted, this issue has not been fixed.

related post above: #36436

**Comment by pwwang** [comment]
Let's see what happens with these commands:

1. Create an separate env with the package only:

```bash
# remove the cached tarballs if necessary
conda clean -t
# and then
conda create \
  -n genomeinfodbdata \
  -c bioconda \
  -c conda-forge \
  r-base=4.1.3 \
  bioconductor-genomeinfodbdata=1.2.7=r41hdfd78af_2
```

2. Check the md5sum for the URLs manually:

```bash
curl -sL https://bioconductor.org/packages/3.14/data/annotation/src/contrib/GenomeInfoDbData_1.2.7.tar.gz | md5sum
curl -sL https://bioarchive.galaxyproject.org/GenomeInfoDbData_1.2.7.tar.gz | md5sum
curl -sL https://depot.galaxyproject.org/software/bioconductor-genomeinfodbdata/bioconductor-genomeinfodbdata_1.2.7_src_all.tar.gz | md5sum
```

See if any of them yields the expected md5: `74c82f26111062a9ceb3c5331088cd56`

**Comment by austintwang** [comment]
It looks like the in-progress [`bulk-bioconductor-data`](https://github.com/bioconda/bioconda-recipes/tree/bulk-bioconductor-data) branch has fixes for all the problematic bioconductor packages.

@daler When should we expect these changes to be merged into master? Greatly appreciate all the work and assistance!

**Comment by JakeLehle** [comment]
Hi @pwwang yeah, I tired out what you just recommended and I'm still having some issues with the MD5s not matching after cleaning the tarball cache.

 The MD5 for the first URL https://bioconductor.org/packages/3.14/data/annotation/src/contrib/GenomeInfoDbData_1.2.7.tar.gz is 74c82f26111062a9ceb3c5331088cd56.
However, the MD5 for https://bioarchive.galaxyproject.org/GenomeInfoDbData_1.2.7.tar.gz is f0696c1d7060c62b7bfcd32eea0cfe53 and
the MD5 for is https://depot.galaxyproject.org/software/bioconductor-genomeinfodbdata/bioconductor-genomeinfodbdata_1.2.7_src_all.tar.gz is also f0696c1d7060c62b7bfcd32eea0cfe53.

Hopefully merging the bulk-bioconductor-data banch as indicated by @austintwang will be a stable fix.

**Comment by pwwang** [comment]
@JakeLehle It should work if one of the URLs matches the MD5. Your first one looks matched. Then it must be something wrong with the recipe. Hopefully the `bulk-bioconductor-data` banch will fix it.

**Comment by pwwang** [comment]
@shufanzhang @JakeLehle @hermidalc If you need a fix urgently, you can try the package I built with my channel, temporarily:

```shell
conda install -c pwwang bioconductor-genomeinfodbdata
```

**Comment by jdblischak** [comment]
Thanks to Ryan and everyone else working hard to fix the Bioconductor data packages. I've been monitoring the [commits to the bulk-bioconductor-data branch](https://github.com/bioconda/bioconda-recipes/commits/bulk-bioconductor-data) and watching as [updated packages are uploaded to anaconda.org](https://anaconda.org/bioconda/repo).

As others have reported above though, even packages that have already been updated to use `curl -L` are still failing to install. [bioconductor-genomeinfodbdata](https://anaconda.org/bioconda/bioconductor-genomeinfodbdata/files) was updated 18 days ago post merging of this PR. In other words, I'm pretty sure it's not going to get rebuilt in the jobs running on the bulk-bioconductor-data branch. I can't install it:

```
$ conda clean --all
$ mamba create --yes -n test-bioc-data  bioconductor-genomeinfodbdata=1.2.7=r41hdfd78af_2

==> script output <==
stdout: ERROR: post-link.sh was unable to download any of the following URLs with the md5sum 74c82f26111062a9ceb3c5331088cd56:
https://bioconductor.org/packages/3.14/data/annotation/src/contrib/GenomeInfoDbData_1.2.7.tar.gz
https://bioarchive.galaxyproject.org/GenomeInfoDbData_1.2.7.tar.gz
https://depot.galaxyproject.org/software/bioconductor-genomeinfodbdata/bioconductor-genomeinfodbdata_1.2.7_src_all.tar.gz

$ curl -sL https://bioconductor.org/packages/3.14/data/annotation/src/contrib/GenomeInfoDbData_1.2.7.tar.gz | md5sum
74c82f26111062a9ceb3c5331088cd56  -
```

Another example: the md5 sum for [bioconductor-ritandata](https://anaconda.org/bioconda/bioconductor-ritandata/files) was updated in commit e1ee48dc92d0dcbf7fabf7bdb32fd1c3538e6c46 and uploaded only 18 hours ago. It is also failing even though the first listed tarball URL matches the expected md5 sum.

```
$ mamba create --yes -n test-bioc-data bioconductor-ritandata=1.18.1=r41hdfd78af_0

==> script output <==
stdout: ERROR: post-link.sh was unable to download any of the following URLs with the md5sum b9784dab6f6e57ffaa02b95e17c3fa8a:
https://bioconductor.org/packages/3.14/data/experiment/src/contrib/RITANdata_1.18.1.tar.gz
https://bioarchive.galaxyproject.org/RITANdata_1.18.1.tar.gz
https://depot.galaxyproject.org/software/bioconductor-ritandata/bioconductor-ritandata_1.18.1_src_all.tar.gz

$ curl -sL https://bioconductor.org/packages/3.14/data/experiment/src/contrib/RITANdata_1.18.1.tar.gz | md5sum
b9784dab6f6e57ffaa02b95e17c3fa8a  -
```

Am I missing something? As far as I can tell, the updated data packages are still uninstallable.

**Comment by pwwang** [comment]
@jdblischak How about:

```
conda create --yes \
  -n test-bioc-data \
  -c bioconda \
  -c conda-forge \
  r-base=4.1.3 \
  bioconductor-genomeinfodbdata=1.2.7=r41hdfd78af_2
```
and use `mamba`?

**Comment by jdblischak** [comment]
@pwwang Does your suggested command work for you? I don't see how the extra arguments you supplied would change the fact that the data package tarball couldn't be downloaded.

I tried it anyways. Note that I had to switch the order of the channels since I have set `channel_priority: strict` in my `~/.condarc`. Same result.

```
conda create --yes \
  -n test-bioc-data \
  -c conda-forge \
  -c bioconda \
  r-base=4.1.3 \
  bioconductor-genomeinfodbdata=1.2.7=r41hdfd78af_2

==> script output <==
stdout: ERROR: post-link.sh was unable to download any of the following URLs with the md5sum 74c82f26111062a9ceb3c5331088cd56:
https://bioconductor.org/packages/3.14/data/annotation/src/contrib/GenomeInfoDbData_1.2.7.tar.gz
https://bioarchive.galaxyproject.org/GenomeInfoDbData_1.2.7.tar.gz
https://depot.galaxyproject.org/software/bioconductor-genomeinfodbdata/bioconductor-genomeinfodbdata_1.2.7_src_all.tar.gz

mamba create --yes \
  -n test-bioc-data \
  -c conda-forge \
  -c bioconda \
  r-base=4.1.3 \
  bioconductor-genomeinfodbdata=1.2.7=r41hdfd78af_2

==> script output <==
stdout: ERROR: post-link.sh was unable to download any of the following URLs with the md5sum 74c82f26111062a9ceb3c5331088cd56:
https://bioconductor.org/packages/3.14/data/annotation/src/contrib/GenomeInfoDbData_1.2.7.tar.gz
https://bioarchive.galaxyproject.org/GenomeInfoDbData_1.2.7.tar.gz
https://depot.galaxyproject.org/software/bioconductor-genomeinfodbdata/bioconductor-genomeinfodbdata_1.2.7_src_all.tar.gz
```

**Comment by pwwang** [comment]
@jdblischak It works for me. Mind attaching the full log?

**Comment by jdblischak** [comment]
Good idea. Here's the full log: [genomeinfodbdata.txt](https://github.com/bioconda/bioconda-recipes/files/9481592/genomeinfodbdata.txt)

Glad to hear it's working for others. After taking a closer look at the full log, I suspect the issue is this SSL error:

```
curl: (35) error:0A000152:SSL routines::unsafe legacy renegotiation disabled
```

And I confirmed that the `curl` installed in the conda env is the problem:

```sh
$ mamba create -y -n curl curl=7.83.1=h2283fc2_0 libcurl=7.83.1=h2283fc2_0

$ mamba activate curl

$ curl --version
curl 7.83.1 (x86_64-conda-linux-gnu) libcurl/7.83.1 OpenSSL/3.0.5 zlib/1.2.12 libssh2/1.10.0 nghttp2/1.47.0
Release-Date: 2022-05-11
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS GSS-API HSTS HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz NTLM NTLM_WB SPNEGO SSL TLS-SRP UnixSockets

$ curl -sL https://bioconductor.org/packages/3.14/data/annotation/src/contrib/GenomeInfoDbData_1.2.7.tar.gz | md5sum
d41d8cd98f00b204e9800998ecf8427e  -

$ curl -L https://bioconductor.org/packages/3.14/data/annotation/src/contrib/GenomeInfoDbData_1.2.7.tar.gz
curl: (35) error:0A000152:SSL routines::unsafe legacy renegotiation disabled

$ mamba deactivate

$ /usr/bin/curl -sL https://bioconductor.org/packages/3.14/data/annotation/src/contrib/GenomeInfoDbData_1.2.7.tar.gz | md5sum
74c82f26111062a9ceb3c5331088cd56  -

$ /usr/bin/curl --version
curl 7.29.0 (x86_64-redhat-linux-gnu) libcurl/7.59.0 OpenSSL/1.1.0k zlib/1.2.11
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile NTLM NTLM_WB SPNEGO SSL libz TLS-SRP unix-sockets
```

**Comment by JakeLehle** [comment]
Just following up on this last comment to better understand what you mean that the curl version is the problem.

So here is a screenshot of my curl version from inside of the conda container. 
image

You can see the version is 7.83.1 but the md5sum is 74c82f26111062a9ceb3c5331088cd56 

Are you saying that despite that I should try to switch the version to 7.29.0?
Thanks.
Jake Lehle

**Comment by jdblischak** [comment]
> Just following up on this last comment to better understand what you mean that the curl version is the problem.

I identified that the conda-installed `curl` was the source of the problem on my HPC cluster. It doesn't seem to be causing a problem for anyone else though, which is concerning. While I isolated the problem, I haven't identified a valid workaround yet.

> You can see the version is 7.83.1 but the md5sum is 74c82f26111062a9ceb3c5331088cd56
>
> Are you saying that despite that I should try to switch the version to 7.29.0?

You are getting the correct md5sum, so you don't need to change anything. I assume that `mamba install bioconductor-genomeinfodbdata=1.2.7=r41hdfd78af_2` is working for you then.

**Comment by JakeLehle** [comment]
@jdblischak No, I'm not used to using mamba.
 Guess today is a good day to learn. Give me a bit and I'll let you know if this workaround works for me.

**Comment by jdblischak** [comment]
@JakeLehle You don't need to use mamba. I think I am confusing you with the problems that I am having on my system.

Try running the below. If it installs, then you should be fine:

```
conda create --yes \
  -n test-bioc-data \
  -c conda-forge \
  -c bioconda \
  r-base=4.1.3 \
  bioconductor-genomeinfodbdata=1.2.7=r41hdfd78af_2

conda activate test-bioc-data

Rscript -e "library(GenomeInfoDbData)"
```

**Comment by hermidalc** [comment]
> @jdblischak No, I'm not used to using mamba. Guess today is a good day to learn. Give me a bit and I'll let you know if this workaround works for me.

Mamba will take you not time to learn. It's seriously a drop-in replacement, so for almost every `conda` command available you just sub `mamba`, that's it, and for the few conda commands that don't yet have a mamba native impl, mamba comes with conda too so you just run `conda` like you have been doing.

Mamba is CRAZY FAST for dep solving, I couldn't use conda anymore for many of my complex environments it wouldn't solve or take FOREVER to solve. All that is a distant memory now that I've been using mamba for so long.

**Comment by jdblischak** [comment]
I made another discovery. The problem isn't specific to my HPC cluster. The problem is the VPN (which I am always connected to when using the HPC). By using my local macOS, I determined that the system curl works both with and without the VPN, but the conda-forge curl only works with the VPN off.

```sh
# macOS

# system curl
% /usr/bin/curl --version
curl 7.79.1 (x86_64-apple-darwin21.0) libcurl/7.79.1 (SecureTransport) LibreSSL/3.3.6 zlib/1.2.11 nghttp2/1.45.1
Release-Date: 2021-09-22
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS GSS-API HSTS HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz MultiSSL NTLM NTLM_WB SPNEGO SSL UnixSockets

# system curl w/o VPN
% /usr/bin/curl -sL https://bioconductor.org/packages/3.14/data/annotation/src/contrib/GenomeInfoDbData_1.2.7.tar.gz | md5
74c82f26111062a9ceb3c5331088cd56

# system curl w/ VPN
% /usr/bin/curl -sL https://bioconductor.org/packages/3.14/data/annotation/src/contrib/GenomeInfoDbData_1.2.7.tar.gz | md5
74c82f26111062a9ceb3c5331088cd56

# conda-forge curl
% $CONDA_PREFIX/bin/curl --version
curl 7.83.1 (arm64-apple-darwin20.0.0) libcurl/7.83.1 OpenSSL/3.0.5 zlib/1.2.12 libssh2/1.10.0 nghttp2/1.47.0
Release-Date: 2022-05-11
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS GSS-API HSTS HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz NTLM NTLM_WB SPNEGO SSL TLS-SRP UnixSockets

# conda-forge curl w/o VPN
% $CONDA_PREFIX/bin/curl -sL https://bioconductor.org/packages/3.14/data/annotation/src/contrib/GenomeInfoDbData_1.2.7.tar.gz | md5
74c82f26111062a9ceb3c5331088cd56

# conda-forge curl w/ VPN
% $CONDA_PREFIX/bin/curl -sL https://bioconductor.org/packages/3.14/data/annotation/src/contrib/GenomeInfoDbData_1.2.7.tar.gz | md5
d41d8cd98f00b204e9800998ecf8427e

% $CONDA_PREFIX/bin/curl -L https://bioconductor.org/packages/3.14/data/annotation/src/contrib/GenomeInfoDbData_1.2.7.tar.gz
curl: (35) error:0A000152:SSL routines::unsafe legacy renegotiation disabled

**Comment by jdblischak** [comment]
Alright, I finally determined the exact issue and a valid workaround. The problem was the SSL certificates required by my company's VPN. For whatever reason, this new redirect to download the Bioconductor data packages triggered the error (in other words, the generic SSL certificates were sufficient to download the data packages with `curl` prior to the recent change).

Below is my workaround. Note that this is only required if you are getting SSL errors. If you were getting other errors last week, these should have been fixed.

```sh
# Set env vars to point to company SSL certificates
export SSL_CERT_FILE=/path/to/file.pem
export CURL_CA_BUNDLE=/path/to/file.pem
export REQUESTS_CA_BUNDLE=/path/to/file.pem

# Require PpenSSL v1 b/c the company SSL certificates above were generated with v1
mamba create --yes -n bioc-test-data openssl=1 bioconductor-genomeinfodbdata=1.2.7=r41hdfd78af_2
mamba activate bioc-test-data
Rscript -e "library(GenomeInfoDbData)"
```

**Comment by daler** [comment]
Sorry, this thread got lost in the thousands of other GH notifications.

If I understand correctly, @jdblischak with the changes you recommend, everything works as expected now?

I will have to use your troubleshooting advice -- I'm hitting SSL errors over VPN as well and my solution was to pop off VPN but it will be nice to be able to stay on.

**Comment by jdblischak** [comment]
@daler Yes, the mix of setting the env vars and pinning openssl to v1 is working for me. Please let me know if a similar workaround fixes your VPN issue as well.

**Comment by mailmrcai** [comment]
This method works for me. When installing Monocle 3, specifying the version of genomeinfodbdata at the same time allows me to bypass the errors.  `mamba install r-monocle3 bioconductor-genomeinfodbdata=1.2.7=r41hdfd78af_2`

**Pull request merged**
