### PR TITLE
Update pysam to 0.16.0

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`pysam`](https://bioconda.github.io/recipes/pysam/README.html): **0.15.4** &rarr; **0.16.0**

[install with bioconda](http://bioconda.github.io/recipes/pysam/README.html) [Conda](https://anaconda.org/bioconda/pysam/files)

Info | Link
-----|-----
Recipe | [`recipes/pysam`](https://github.com//bioconda/bioconda-recipes/tree/bump/pysam/recipes/pysam) (click to view/edit other files)
Releases |[https://github.com/pysam-developers/pysam/tags](https://github.com/pysam-developers/pysam/tags)
Author | `@pysam-developers`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by jmarshall** [comment]
Before merging this update, please also add this commit: jmarshall/bioconda-recipes@6ed8b711cd25accedf9a3d7837ae69445e63e7da. This fixes pysam-developers/pysam#920 (which was a bioconda packaging bug that should have been filed against bioconda-recipes) and tidies up the recipe a bit.

**Comment by apeltzer** [comment]
Hi @jmarshall ! I tried applying your fix locally, but including the pre-bundled htslib library broke other tools relying on the bioconda htslib :-( Maybe open a new PR just including your fix / commit to get 0.16.0-1 then done?

**Comment by apeltzer** [comment]
@BiocondaBot please merge

**Comment by jmarshall** [comment]
Which tools? The current bioconda pysam already includes a pre-bundled htslib since PR #13093.

I would appreciate it if you would give us an opportunity to fix this properly without bioconda uploading a broken 0.16.0-0 first.

**Comment by apeltzer** [comment]
Multiple that use e.g. libdeflate and/or samtools/htslib -> libdeflate , e.g. sequencetools, pmdtools. We've been running into multiple issues with this recently, which wasn't the case a while ago unfortunately. 

Whenever these are in a single environment, the pre-bundled version seems to break that they can be installed alongside each other ...? 

The 0.16 recipe is working fine for I suppose the majority of use cases, _except_ the one you specified in your commit ...

**Pull request merged**
