### PR TITLE
Use extended base for quast

### PR DESCRIPTION
**Pull request by mvdbeek**
Otherwise fails with
```
Traceback (most recent call last):
  File "/usr/local/bin/quast", line 307, in <module>
    return_code = main(sys.argv[1:])
  File "/usr/local/bin/quast", line 149, in main
    icarus_gc_fpath, circos_gc_fpath = basic_stats.do(ref_fpath, contigs_fpaths, os.path.join(output_dirpath, 'basic_stats'), output_dirpath)
  File "/usr/local/opt/quast-5.0.2/quast_libs/basic_stats.py", line 263, in do
    html_saver.save_contigs_lengths(results_dir, contigs_fpaths, corr_lists_of_lengths)
  File "/usr/local/opt/quast-5.0.2/quast_libs/html_saver/html_saver.py", line 475, in save_contigs_lengths
    append(results_dirpath, json_fpath, 'contigsLengths')
  File "/usr/local/opt/quast-5.0.2/quast_libs/html_saver/html_saver.py", line 220, in append
    init(html_fpath)
  File "/usr/local/opt/quast-5.0.2/quast_libs/html_saver/html_saver.py", line 115, in init
    script_texts.append(js_html(aux_f_rel_path))
  File "/usr/local/opt/quast-5.0.2/quast_libs/html_saver/html_saver.py", line 95, in js_html
    return '<script type="text/javascript">\n' + open(get_real_path(script_rel_path)).read() + '\n</script>\n'
  File "/usr/local/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 14588: ordinal not in range(128)
```

Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [ ] This PR adds a new recipe.
* [ ] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

 * `@BiocondaBot please update` will cause the BiocondaBot to merge the master branch into a PR
 * `@BiocondaBot please add label` will add the `please review & merge` label.
 * `@BiocondaBot please fetch artifacts` will post links to packages and docker containers built by the CI system. You can use this to test packages locally before merging.

For members of the Bioconda project, the following command is also available:

 * `@BiocondaBot please merge` will cause packages/containers to be uploaded and a PR merged. Someone must approve a PR first! This has the benefit of not wasting CI build time required by manually merging PRs.

If you have questions, please post them in gitter or ping `@bioconda/core` in a comment (if you are not able to directly ping `@bioconda/core` then the bot will repost your comment and enable pinging).

### CODE REVIEW

**Comment by mvdbeek** [comment]
@BiocondaBot please add label

**Comment by mvdbeek** [comment]
Hmm, looks like no new biocontainer was published, any idea what's up with that ?

**Comment by bgruening** [comment]
Looks like the bioconda package was also not updated: https://anaconda.org/bioconda/quast/files

If this happens, this is usually because the package is blacklisted. Remove this line in a new PR and please make some whitespace changes in the recipe: https://github.com/bioconda/bioconda-recipes/blob/master/build-fail-blacklist#L81

**Comment by mbargull** [comment]
fixed in gh-23218

**Pull request merged**
