### PR TITLE
r-sartools. New version 1.3.2.

### PR DESCRIPTION
**Pull request by loraine-gueguen**
* [x] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

Recipe for last r-sartools version.

### CODE REVIEW

**Comment by loraine-gueguen** [comment]
The test on osx failed. It seems to be a problem of library version: readline 6.3 loaded in conda-forge but looking for 6.2
`dyld: Library not loaded: @rpath/libreadline.6.2.dylib`
We don't have the problem on linux (why?)

**Comment by druvus** [comment]
I also see this error in my R build using travis. I have tried your recipe locally on my mac in a clean environment and it finds readline 6.2 to successfully build the tool. 

The number of software that are taken from conda-forge is suspicious. Software like zlib, ncurses and curl are not downloaded from conda-forge in my local test. 

My local .condarc file looks this:
<pre>
channels:
  - bioconda
  - r
  - defaults
  - conda-forge
</pre>   

Could it be a problem with the channel order for the mac builds? @bioconda/core

**Comment by johanneskoester** [comment]
The preferred channel order is the following now:
```
    - conda-forge
    - defaults
    - r
    - bioconda
```
This should mean lowest priority for conda-forge, highest for bioconda. The reason is that we want to avoid that conda-forge packages are pulled as dependencies of r-channel packages, because the r channel has been built only against defaults.
But apparently, this does not work here...

So, you mean that your order does not pull conda-forge packages? Can you post the output of `conda config --get`?

**Comment by druvus** [comment]
This is the output from the command using my mac: 

```
(test-osx) Andreas-MBP-6:Downloads andreassjodin$ conda config --get
--add channels 'conda-forge'   # lowest priority
--add channels 'defaults'
--add channels 'r'
--add channels 'bioconda'   # highest priority
```

I think the problem is this line in the travis output: 

```
ERROR bioconda_utils.build:build(112): COMMAND: ['conda', 'build', '--no-build-id', '--no-anaconda-upload', '--channel', 'conda-forge', '--channel', 'defaults', '--channel', 'r', '--channel', 'bioconda', 'recipes/r-sartools/1.3.2'] 
```


so the bioconda_utils build.py use the reverse order of the channels. When I run the command manually I get the same error as travis. 

``` 
(test-osx) Andreas-MBP-6:Downloads andreassjodin$ conda build  --channel conda-forge --channel defaults --channel r --channel bioconda r-sartools/
BUILD START: r-sartools-1.3.2-r3.3.1_0
updating index in: /Users/andreassjodin/anaconda/conda-bld/osx-64
updating index in: /Users/andreassjodin/anaconda/conda-bld/noarch

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    libgcc-4.8.5               |                1         785 KB
    xz-5.2.2                   |                0         288 KB  conda-forge
    r-ggplot2-2.1.0            |         r3.3.1_0         2.0 MB  r
    ------------------------------------------------------------
                                           Total:         3.0 MB

The following NEW packages will be INSTALLED:

    bioconductor-annotate:             1.50.0-r3.3.1_1      bioconda
    bioconductor-annotationdbi:        1.36.0-r3.3.1_1      bioconda
    bioconductor-biobase:              2.32.0-r3.3.1_0      bioconda
    bioconductor-biocgenerics:         0.20.0-r3.3.1_0      bioconda
    bioconductor-biocparallel:         1.6.6-r3.3.1_0       bioconda
    bioconductor-biomart:              2.28.0-r3.3.1_0      bioconda
    bioconductor-biostrings:           2.40.0-r3.3.1_0      bioconda
    bioconductor-deseq2:               1.12.4-r3.3.1_3      bioconda
    bioconductor-edger:                3.14.0-r3.3.1_1      bioconda
    bioconductor-genefilter:           1.54.2-r3.3.1_0      bioconda
    bioconductor-geneplotter:          1.50.0-r3.3.1_0      bioconda
    bioconductor-genomeinfodb:         1.8.7-r3.3.1_0       bioconda
    bioconductor-genomicalignments:    1.10.0-r3.3.1_0      bioconda
    bioconductor-genomicfeatures:      1.26.0-r3.3.1_2      bioconda
    bioconductor-genomicranges:        1.26.1-r3.3.1_1      bioconda
    bioconductor-iranges:              2.8.0-r3.3.1_0       bioconda
    bioconductor-limma:                3.29.0-r3.3.1_0      bioconda
    bioconductor-rsamtools:            1.26.1-r3.3.1_0      bioconda
    bioconductor-rtracklayer:          1.34.1-r3.3.1_0      bioconda
    bioconductor-s4vectors:            0.12.0-r3.3.1_0      bioconda
    bioconductor-summarizedexperiment: 1.4.0-r3.3.1_0       bioconda
    bioconductor-tximport:             1.0.3-r3.3.1_0       bioconda
    bioconductor-xvector:              0.12.1-r3.3.1_0      bioconda
    bioconductor-zlibbioc:             1.18.0-r3.3.1_0      bioconda
    ca-certificates:                   2016.9.26-0          conda-forge
    curl:                              7.49.1-1             conda-forge
    gsl:                               2.1-2                conda-forge
    icu:                               56.1-4               conda-forge
    jpeg:                              9b-0                 conda-forge
    libgcc:                            4.8.5-1
    libiconv:                          1.14-3               conda-forge
    libpng:                            1.6.26-0             conda-forge
    libtiff:                           4.0.6-7              conda-forge
    libxml2:                           2.9.4-3              conda-forge
    ncurses:                           5.9-9                conda-forge
    openssl:                           1.0.2h-2             conda-forge
    pcre:                              8.38-1               conda-forge
    r:                                 3.3.1-r3.3.1_0       r
    r-acepack:                         1.3_3.3-r3.3.1_2     r
    r-base:                            3.3.1-0              r
    r-bitops:                          1.0_6-r3.3.1_2       r
    r-boot:                            1.3_18-r3.3.1_0      r
    r-catools:                         1.17.1-r3.3.1_2      r
    r-chron:                           2.3_47-r3.3.1_0      r
    r-class:                           7.3_14-r3.3.1_0      r
    r-cluster:                         2.0.4-r3.3.1_0       r
    r-codetools:                       0.2_14-r3.3.1_0      r
    r-colorspace:                      1.2_6-r3.3.1_0       r
    r-data.table:                      1.9.6-r3.3.1_0       r
    r-dbi:                             0.4_1-r3.3.1_0       r
    r-dichromat:                       2.0_0-r3.3.1_2       r
    r-digest:                          0.6.9-r3.3.1_0       r
    r-evaluate:                        0.9-r3.3.1_0         r
    r-foreign:                         0.8_66-r3.3.1_0      r
    r-formatr:                         1.4-r3.3.1_0         r
    r-formula:                         1.2_1-r3.3.1_0       r
    r-futile.logger:                   1.4.1-r3.3.1_0       bioconda
    r-futile.options:                  1.0.0-r3.3.1_0       bioconda
    r-gdata:                           2.17.0-r3.3.1_0      r
    r-getopt:                          1.20.0-r3.3.1_0      bioconda
    r-ggplot2:                         2.1.0-r3.3.1_0       r
    r-gplots:                          3.0.1-r3.3.1_0       r
    r-gridextra:                       2.2.1-r3.3.1_0       r
    r-gtable:                          0.2.0-r3.3.1_0       r
    r-gtools:                          3.5.0-r3.3.1_0       r
    r-highr:                           0.6-r3.3.1_0         r
    r-hmisc:                           3.17_4-r3.3.1_0      r
    r-kernsmooth:                      2.23_15-r3.3.1_0     r
    r-knitr:                           1.13-r3.3.1_0        r
    r-labeling:                        0.3-r3.3.1_2         r
    r-lambda.r:                        1.1.7-r3.3.1_0       bioconda
    r-lattice:                         0.20_33-r3.3.1_0     r
    r-latticeextra:                    0.6_28-r3.3.1_0      r
    r-locfit:                          1.5_9.1-r3.3.1_0     bioconda
    r-magrittr:                        1.5-r3.3.1_2         r
    r-markdown:                        0.7.7-r3.3.1_2       r
    r-mass:                            7.3_45-r3.3.1_0      r
    r-matrix:                          1.2_6-r3.3.1_0       r
    r-mgcv:                            1.8_12-r3.3.1_0      r
    r-mime:                            0.4-r3.3.1_0         r
    r-munsell:                         0.4.3-r3.3.1_0       r
    r-nlme:                            3.1_128-r3.3.1_0     r
    r-nnet:                            7.3_12-r3.3.1_0      r
    r-plyr:                            1.8.4-r3.3.1_0       r
    r-rcolorbrewer:                    1.1_2-2a             r
    r-rcpp:                            0.12.5-r3.3.1_0      r
    r-rcpparmadillo:                   0.7.100.3.1-r3.3.1_0 r
    r-rcurl:                           1.95_4.8-r3.3.1_0    r
    r-recommended:                     3.3.1-r3.3.1_0       r
    r-reshape2:                        1.4.1-r3.3.1_2       r
    r-rjson:                           0.2.15-r3.3.1_0      r
    r-rpart:                           4.1_10-r3.3.1_0      r
    r-rsqlite:                         1.0.0-r3.3.1_2       r
    r-scales:                          0.4.0-r3.3.1_0       r
    r-snow:                            0.4_1-r3.3.1_0       bioconda
    r-spatial:                         7.3_11-r3.3.1_0      r
    r-stringi:                         1.1.1-r3.3.1_0       r
    r-stringr:                         1.0.0-r3.3.1_0       r
    r-survival:                        2.39_4-r3.3.1_0      r
    r-xml:                             3.98_1.4-r3.3.1_0    r
    r-xtable:                          1.8_2-r3.3.1_0       r
    r-yaml:                            2.1.13-r3.3.1_2      r
    readline:                          6.3-1                conda-forge
    tk:                                8.6.6-3              conda-forge
    xz:                                5.2.2-0              conda-forge
    zlib:                              1.2.8-3              conda-forge

updating index in: /Users/andreassjodin/anaconda/conda-bld/osx-64
updating index in: /Users/andreassjodin/anaconda/conda-bld/noarch


[...] REMOVED OUTPUT


Source cache directory is: /Users/andreassjodin/anaconda/conda-bld/src_cache
Found source in cache: v1.3.2.tar.gz
Extracting download
Package: r-sartools-1.3.2-r3.3.1_0
source tree in: /Users/andreassjodin/anaconda/conda-bld/r-sartools_1478885768066/work/SARTools-1.3.2
+ source /Users/andreassjodin/anaconda/bin/activate /Users/andreassjodin/anaconda/conda-bld/r-sartools_1478885768066/_b_env_placehol
+ mv DESCRIPTION DESCRIPTION.old
+ grep -v '^Priority: ' DESCRIPTION.old
+ /Users/andreassjodin/anaconda/conda-bld/r-sartools_1478885768066/_b_env_placehol/bin/R CMD INSTALL --build .
dyld: Library not loaded: @rpath/libreadline.6.2.dylib
  Referenced from: /Users/andreassjodin/anaconda/conda-bld/r-sartools_1478885768066/_b_env_placehol/lib/R/lib/libR.dylib
  Reason: image not found
/Users/andreassjodin/anaconda/conda-bld/r-sartools_1478885768066/_b_env_placehol/lib/R/bin/INSTALL: line 34: 76937 Done                    echo 'tools:::.install_packages()'
     76938 Abort trap: 6           | R_DEFAULT_PACKAGES= LC_COLLATE=C "${R_HOME}/bin/R" $myArgs --slave --args ${args}
Command failed: /bin/bash -x -e /Users/andreassjodin/anaconda/conda-bld/r-sartools_1478885768066/work/SARTools-1.3.2/conda_build.sh
```

but it instead use the order in my condarc file. 

```
(test-osx) Andreas-MBP-6:Downloads andreassjodin$ conda build r-sartools/
BUILD START: r-sartools-1.3.2-r3.3.1_0
updating index in: /Users/andreassjodin/anaconda/conda-bld/osx-64
updating index in: /Users/andreassjodin/anaconda/conda-bld/noarch

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    libgcc-4.8.5               |                1         785 KB  r
    xz-5.2.2                   |                0         186 KB
    r-knitr-1.12.3             |         r3.3.1_0         677 KB  bioconda
    r-ggplot2-2.1.0            |         r3.3.1_0         2.0 MB  bioconda
    ------------------------------------------------------------
                                           Total:         3.6 MB

The following NEW packages will be INSTALLED:

    bioconductor-annotate:             1.50.0-r3.3.1_1      bioconda
    bioconductor-annotationdbi:        1.36.0-r3.3.1_1      bioconda
    bioconductor-biobase:              2.32.0-r3.3.1_0      bioconda
    bioconductor-biocgenerics:         0.20.0-r3.3.1_0      bioconda
    bioconductor-biocparallel:         1.6.6-r3.3.1_0       bioconda
    bioconductor-biomart:              2.28.0-r3.3.1_0      bioconda
    bioconductor-biostrings:           2.40.0-r3.3.1_0      bioconda
    bioconductor-deseq2:               1.12.4-r3.3.1_3      bioconda
    bioconductor-edger:                3.14.0-r3.3.1_1      bioconda
    bioconductor-genefilter:           1.54.2-r3.3.1_0      bioconda
    bioconductor-geneplotter:          1.50.0-r3.3.1_0      bioconda
    bioconductor-genomeinfodb:         1.8.7-r3.3.1_0       bioconda
    bioconductor-genomicalignments:    1.10.0-r3.3.1_0      bioconda
    bioconductor-genomicfeatures:      1.26.0-r3.3.1_2      bioconda
    bioconductor-genomicranges:        1.26.1-r3.3.1_1      bioconda
    bioconductor-iranges:              2.8.0-r3.3.1_0       bioconda
    bioconductor-limma:                3.29.0-r3.3.1_0      bioconda
    bioconductor-rsamtools:            1.26.1-r3.3.1_0      bioconda
    bioconductor-rtracklayer:          1.34.1-r3.3.1_0      bioconda
    bioconductor-s4vectors:            0.12.0-r3.3.1_0      bioconda
    bioconductor-summarizedexperiment: 1.4.0-r3.3.1_0       bioconda
    bioconductor-tximport:             1.0.3-r3.3.1_0       bioconda
    bioconductor-xvector:              0.12.1-r3.3.1_0      bioconda
    bioconductor-zlibbioc:             1.18.0-r3.3.1_0      bioconda
    curl:                              7.45.0-2             bioconda
    gsl:                               1.16-2               r
    icu:                               54.1-0
    jbig:                              2.1-0
    jpeg:                              8d-2                 r
    libgcc:                            4.8.5-1              r
    libpng:                            1.6.17-0             r
    libtiff:                           4.0.6-2
    libxml2:                           2.9.2-1              r
    ncurses:                           5.9-8                r
    openssl:                           1.0.2j-0
    pcre:                              8.39-0
    r:                                 3.3.1-r3.3.1_0       r
    r-acepack:                         1.3_3.3-r3.3.1_2     r
    r-base:                            3.3.1-0              r
    r-bitops:                          1.0_6-r3.3.1_2       r
    r-boot:                            1.3_18-r3.3.1_0      r
    r-catools:                         1.17.1-r3.3.1_0      bioconda
    r-chron:                           2.3_47-r3.3.1_0      r
    r-class:                           7.3_14-r3.3.1_0      r
    r-cluster:                         2.0.4-r3.3.1_0       r
    r-codetools:                       0.2_14-r3.3.1_0      r
    r-colorspace:                      1.2_6-r3.3.1_0       r
    r-data.table:                      1.9.6-r3.3.1_0       r
    r-dbi:                             0.4_1-r3.3.1_0       r
    r-dichromat:                       2.0_0-r3.3.1_2       r
    r-digest:                          0.6.9-r3.3.1_0       r
    r-evaluate:                        0.9-r3.3.1_0         r
    r-foreign:                         0.8_66-r3.3.1_0      r
    r-formatr:                         1.4-r3.3.1_0         r
    r-formula:                         1.2_1-r3.3.1_0       r
    r-futile.logger:                   1.4.1-r3.3.1_0       bioconda
    r-futile.options:                  1.0.0-r3.3.1_0       bioconda
    r-gdata:                           2.17.0-r3.3.1_0      r
    r-getopt:                          1.20.0-r3.3.1_0      bioconda
    r-ggplot2:                         2.1.0-r3.3.1_0       bioconda
    r-gplots:                          3.0.1-r3.3.1_0       r
    r-gridextra:                       2.2.1-r3.3.1_0       r
    r-gtable:                          0.2.0-r3.3.1_0       r
    r-gtools:                          3.5.0-r3.3.1_0       r
    r-highr:                           0.6-r3.3.1_0         r
    r-hmisc:                           3.17_4-r3.3.1_0      r
    r-kernsmooth:                      2.23_15-r3.3.1_0     r
    r-knitr:                           1.12.3-r3.3.1_0      bioconda
    r-labeling:                        0.3-r3.3.1_2         r
    r-lambda.r:                        1.1.7-r3.3.1_0       bioconda
    r-lattice:                         0.20_33-r3.3.1_0     r
    r-latticeextra:                    0.6_28-r3.3.1_0      r
    r-locfit:                          1.5_9.1-r3.3.1_0     bioconda
    r-magrittr:                        1.5-r3.3.1_2         r
    r-markdown:                        0.7.7-r3.3.1_2       r
    r-mass:                            7.3_45-r3.3.1_0      r
    r-matrix:                          1.2_6-r3.3.1_0       r
    r-mgcv:                            1.8_12-r3.3.1_0      r
    r-mime:                            0.4-r3.3.1_0         r
    r-munsell:                         0.4.3-r3.3.1_0       r
    r-nlme:                            3.1_128-r3.3.1_0     r
    r-nnet:                            7.3_12-r3.3.1_0      r
    r-plyr:                            1.8.4-r3.3.1_0       r
    r-rcolorbrewer:                    1.1_2-r3.3.1_3       r
    r-rcpp:                            0.12.5-r3.3.1_0      r
    r-rcpparmadillo:                   0.7.100.3.1-r3.3.1_0 r
    r-rcurl:                           1.95_4.8-r3.3.1_0    r
    r-recommended:                     3.3.1-r3.3.1_0       r
    r-reshape2:                        1.4.1-1a             r
    r-rjson:                           0.2.15-r3.3.1_0      r
    r-rpart:                           4.1_10-r3.3.1_0      r
    r-rsqlite:                         1.0.0-r3.3.1_2       r
    r-scales:                          0.4.0-r3.3.1_0       r
    r-snow:                            0.4_1-r3.3.1_0       bioconda
    r-spatial:                         7.3_11-r3.3.1_0      r
    r-stringi:                         1.1.1-r3.3.1_0       r
    r-stringr:                         1.0.0-r3.3.1_0       r
    r-survival:                        2.39_4-r3.3.1_0      r
    r-xml:                             3.98_1.4-r3.3.1_0    r
    r-xtable:                          1.8_2-r3.3.1_0       r
    r-yaml:                            2.1.13-r3.3.1_2      r
    readline:                          6.2-2
    tk:                                8.5.18-0
    xz:                                5.2.2-0
    zlib:                              1.2.8-1              r



[...] REMOVED OUTPUT



> library('SARTools')
Loading required package: DESeq2
Loading required package: S4Vectors
Loading required package: stats4
Loading required package: BiocGenerics
Loading required package: parallel

Attaching package: 'BiocGenerics'

The following objects are masked from 'package:parallel':

    clusterApply, clusterApplyLB, clusterCall, clusterEvalQ,
    clusterExport, clusterMap, parApply, parCapply, parLapply,
    parLapplyLB, parRapply, parSapply, parSapplyLB

The following objects are masked from 'package:stats':

    IQR, mad, xtabs

The following objects are masked from 'package:base':

    anyDuplicated, append, as.data.frame, cbind, colnames, do.call,
    duplicated, eval, evalq, Filter, Find, get, grep, grepl, intersect,
    is.unsorted, lapply, lengths, Map, mapply, match, mget, order,
    paste, pmax, pmax.int, pmin, pmin.int, Position, rank, rbind,
    Reduce, rownames, sapply, setdiff, sort, table, tapply, union,
    unique, unsplit, which, which.max, which.min


Attaching package: 'S4Vectors'

The following objects are masked from 'package:base':

    colMeans, colSums, expand.grid, rowMeans, rowSums

Loading required package: IRanges
Loading required package: GenomicRanges
Loading required package: GenomeInfoDb
Loading required package: SummarizedExperiment
Loading required package: Biobase
Welcome to Bioconductor

    Vignettes contain introductory material; view with
    'browseVignettes()'. To cite Bioconductor, see
    'citation("Biobase")', and for packages 'citation("pkgname")'.

Loading required package: edgeR
Loading required package: limma

Attaching package: 'limma'

The following object is masked from 'package:DESeq2':

    plotMA

The following object is masked from 'package:BiocGenerics':

    plotMA

Loading required package: xtable
    ----------------------------------------------
    Welcome to SARTools version 1.3.2.
    R template scripts are available on GitHub.
    ----------------------------------------------
>
>
TEST END: r-sartools-1.3.2-r3.3.1_0
``` 

Swapping the order to `conda build  --channel bioconda --channel r --channel defaults --channel conda-forge r-sartools/` also gives a successful result and it is identical to using my .condarc settings. So I think the bug here is that bioconda_utils put the channels in revered order at the command prompt. @bioconda/core

**Comment by daler** [comment]
Thanks @druvus for working this out.

if a .condarc looks like

```
channels:
  - bioconda
  - r
  - defaults
  - conda-forge
```

then a `conda config --get` looks like:

```
--add channels 'conda-forge'   # lowest priority
--add channels 'defaults'
--add channels 'r'
--add channels 'bioconda'   # highest priority
```

That is, in `.condarc` the highest priority channels are at the top.  But in order to get them that way, you have to add the channels in the order shown by `conda config --get`. So bioconda-utils assumes that adding channels acts like `conda config --add channels` when in fact it should follow the order of `.condarc`. And when I look at the help for `conda build` it clearly says the channels are searched in the order provided.

I'll fix this now.

**Comment by bgruening** [comment]
I triggered a rebuild with @daler latest changes and it turns green.

**Comment by loraine-gueguen** [comment]
@druvus @daler Thanks for the fix !

**Pull request merged**
