### PR TITLE
Add Marge

### PR DESCRIPTION
**Pull request by sebastian-luna-valero**
* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [X] This PR adds a new recipe.
* [X] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by sebastian-luna-valero** [comment]
@bioconda/core please review

**Comment by daler** [comment]
@sebastian-luna-valero looks good.

That's a lot of templating going on, is that from conda-skeleton?

**Comment by sebastian-luna-valero** [comment]
Thanks @daler 

I have used the `conda-forge` template:
https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml

Is there a better way to do this?

**Comment by daler** [comment]
No, this is great -- I just hadn't seen the extension and hash type templated before and was curious if we'll be seeing more of that in the future in other recipes.

**Comment by sebastian-luna-valero** [comment]
Thanks!

**Pull request merged**
