### PR TITLE
Update plantcv to 3.9.0

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`plantcv`](https://bioconda.github.io/recipes/plantcv/README.html): **3.8.0** &rarr; **3.9.0**

[install with bioconda](http://bioconda.github.io/recipes/plantcv/README.html) [Conda](https://anaconda.org/bioconda/plantcv/files)

Info | Link
-----|-----
Recipe | [`recipes/plantcv`](https://github.com//bioconda/bioconda-recipes/tree/bump/plantcv/recipes/plantcv) (click to view/edit other files)
Releases |[https://pypi.org/pypi/plantcv/json](https://pypi.org/pypi/plantcv/json)
Recipe Maintainer(s) | @nfahlgren, @maliagehan, @HaleySchuhl

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by nfahlgren** [comment]
@bioconda/core is the extended-base container still working? This new build does not seem to be using it, unlike previous builds, as far as I can tell. Possibly why we are getting a libGL not found error when it was working previously?

**Comment by nfahlgren** [comment]
Maybe this package should be moved to conda-forge. The libGL requirement for OpenCV seems to be unstable here and not many other packages seem to require that library.

**Comment by bgruening** [comment]
> Maybe this package should be moved to conda-forge. The libGL requirement for OpenCV seems to be unstable here and not many other packages seem to require that library.

Is there any reason why you think that libGL works with a conda-forge package and not with a BioConda package? What will get installed is actually the same packages.

**Comment by nfahlgren** [comment]
As far as I can tell, in conda-forge the ability to install RPM packages with `yum_requirements.txt` seems to make libGL available to OpenCV when we run import tests. Here the extended-base image should do the trick but it stopped working between our last release and this one.

**Pull request closed without merging**
