### PR TITLE
Update pegasuspy to 1.3.0

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`pegasuspy`](https://bioconda.github.io/recipes/pegasuspy/README.html): **1.2.0** &rarr; **1.3.0**

[install with bioconda](http://bioconda.github.io/recipes/pegasuspy/README.html) [Conda](https://anaconda.org/bioconda/pegasuspy/files)

Info | Link
-----|-----
Recipe | [`recipes/pegasuspy`](https://github.com//bioconda/bioconda-recipes/tree/bump/pegasuspy/recipes/pegasuspy) (click to view/edit other files)
Releases |[https://pypi.org/pypi/pegasuspy/json](https://pypi.org/pypi/pegasuspy/json)
Recipe Maintainer(s) | @yihming

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by jdblischak** [comment]
I was curious why this PR hadn't been fixed and merged. Below I document what I found. Looks like the issue is a tricky dependency.

The [build is failing](https://app.circleci.com/pipelines/github/bioconda/bioconda-recipes/39841/workflows/68a07cc1-3e54-4832-9ba3-bc98649e2e93/jobs/139449?invite=true#step-106-831) because it is missing the dependency psutil:

```
21:28:32 BIOCONDA INFO (OUT) ModuleNotFoundError: No module named 'psutil'
```

That would be easy enough to fix, but apparently there are bigger issues with compiling the dependency hnswlib to work on all CPU architectures, discussed in the issues below:

https://github.com/klarman-cell-observatory/pegasus/issues/184
https://github.com/conda-forge/hnswlib-feedstock/pull/11
https://github.com/nmslib/hnswlib/issues/17

Which is presumably why it is no longer automatically built for bioconda:

https://github.com/bioconda/bioconda-recipes/blob/b79f4758c7f24ad02b17345a314b4fa4111f0324/build-fail-blacklist#L222

**Comment by yihming** [comment]
@jdblischak Thank you for taking time to check our issue. The main obstacle is on the hnswlib side. After it's resolved, we'll work on updating the recipe for the new dependencies.

For the hnswlib conda issue, we have someone willing to help, and hopefully could get it done by this year.

**Comment by yihming** [comment]
Hi @jdblischak ,

Here are the updates regarding Pegasuspy:

* We have resolved the issue on hnswlib conda package, and updated its `meta.yml` to version 0.6.2. 
* However, it seems that on conda-forge channel, hnswlib's version is still v0.5.1. I'm reaching out to people to look at this issue and fix it.
* In the meantime, we've decided to move on with upgrading Pegasuspy on bioconda. I've create PR #33769 , which upgraded to version 1.5.0 and has been merged.

Therefore, you may close this PR. 


Sincerely,
Yiming

**Comment by jdblischak** [comment]
@yihming Great work! Thanks for following up

I'm planning on doing a test installation of pegasuspy 1.5.0 once it is uploaded to Anaconda Cloud

https://anaconda.org/bioconda/pegasuspy/files

**Comment by yihming** [comment]
@jdblischak I have one update, and one question that I need your help:

* I've resolved the issue on hnswlib conda-forge package, and now it's synchronized to v0.6.2.
* However, when I did a local test on Pegasuspy last night, I got a notice saying that its building was skipped because the package was on the blacklist. Should it be moved out of the blacklist before I push a update PR to bioconda?

Sincerely,
Yiming

**Comment by jdblischak** [comment]
Ah, yes! That explains why 1.5.0 hasn't been uploaded after 10 hours. Please submit a PR to remove pegasuspy from `build-fail-blacklist`:

https://github.com/bioconda/bioconda-recipes/blob/9661069e080837baceb8e047474b93d58d7ff6d8/build-fail-blacklist#L201

Once that change is merged, then 1.5.0 should be built and uploaded

**Comment by yihming** [comment]
@jdblischak Thanks for the direction. I've made PR #33783 .

**Pull request closed without merging**
