### PR TITLE
Update GATK4 recipe to allow Java 11 (Proposal)

### PR DESCRIPTION
**Pull request by jfy133**
GATK4 has had 'beta' support for Java 11 for almost a year now (since [4.1.4](https://github.com/broadinstitute/gatk/releases/tag/4.1.4.0)). 

I'm dealing with a pipeline that includes tools do not support Java 8 anymore, and being able to run it on Java 11 would be really useful, and GATK is the only package 'holding' this back. I did a search on the GATK github repo issues for bug reports for Java 11 and didn't really see anything recent  which suggest to me this should (hopefully) be pretty stable.

The only issue here is that that the Spark compatibility _might_ be affected (See GATK [#6671](https://github.com/broadinstitute/gatk/issues/6671) and [#6053](https://github.com/broadinstitute/gatk/issues/6053)), but again I don't see any major incompatibility reports with Java 11.

I don't know what bioconda's approach to 'beta' stuff like this, so I make this as a proposal, and updating the build as it is not a new version of the tool.

Note that I've changed the requirement pinning structure to remove the more than operator, based on following the conda documentation [here](https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#requirements-section) and [here](https://conda.io/projects/conda/en/latest/user-guide/concepts/pkg-specs.html#package-match-specifications). 

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by jfy133** [comment]
Neither `,` not `|` worked for some reason to separate different possible versions.

Despite 9 and 10 versions of java were never released for production use, unfortunately the recipe picks up the conda-forge version of openjdk which includes these version (which are _not_ supported by GATK AFAIK), so using less than/more than doesn't work here.

**Comment by jfy133** [comment]
@BiocondaBot please add label

**Comment by apeltzer** [comment]
@bioconda/core any thoughts on this one?

**Comment by bgruening** [comment]
I am hesitant to include something that is not supported upstream. @jfy133 why are you not using separate environments? You can not support a one-fits-all environment for eternity. So I guess it's better to decompose your pipeline into separate envs.

**Comment by jfy133** [comment]
> I am hesitant to include something that is not supported upstream. @jfy133 why are you not using separate environments? You can not support a one-fits-all environment for eternity. So I guess it's better to decompose your pipeline into separate envs.

@bgruening thanks for your input, and is what I expected.

You have a good point about that and I just conferred with @apeltzer and actually it is a misunderstanding on my part - apparently nextflow/nf-core pipelines do support separate containers per process (I thought that was only in a cutting edge version). So I will investigate that instead. Thanks anyway!

**Pull request closed without merging**
