### PR TITLE
Update SearchGUI: Fixing metamorpheus execution problems

### PR DESCRIPTION
**Pull request by CarlosHorro**
Bugfixes: 
- previous release seemed to give problems executing metamorpheus.
- one user reported myrimatch issue with locales was still happening. This should fix it definitely.

Bugfix pending on feedback:
- ms amanda execution problem after building the Conda package 
----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by CarlosHorro** [comment]
Althought the metamorpheus issue is being solved, I have realised that I am having problems executing MS Amanda. They recently moved to .NET Core and we updated our code accordingly. Chacking galaxy tests using these Conda packages, MSAmanda seem to work, but when I install SG Conda package into our server, it gives me this error (Ubuntu 64bits, with .NET core runtime installed):

```
Failure processing application bundle.
Bundle header version compatibility check failed
A fatal error was encountered. Could not extract contents of the bundle
```

And, checking the size of the executable, it has changed from the source.

in the conda package: 82905640
in the source package: 82901544

So I guess it is a problem related with the binary relocalization... is there a way to avoid it to execute for a specific file?

**Comment by CarlosHorro** [comment]
Althought the metamorpheus issue is solved, I have realised that I am having problems executing MS Amanda. They recently moved to .NET Core and we updated our code accordingly, but when I install SG Conda package into our server, it gives me this error (Ubuntu 64bits, with .NET core runtime installed):
```

Failure processing application bundle.
Bundle header version compatibility check failed
A fatal error was encountered. Could not extract contents of the bundle
```

And, checking the size of the executable, it has changed from the source.

in the conda package: 82905640
in the source package: 82901544

So I guess it is a problem related with the binary relocalization... is there a way to avoid it to execute for a specific file?

**Comment by CarlosHorro** [comment]
@BiocondaBot please add label

**Comment by CarlosHorro** [comment]
@bioconda/core : Althought the metamorpheus issue is solved, I have realised that I am having problems executing MS Amanda. They recently moved to .NET Core and we updated our code accordingly, but when I install SG Conda package into our server, it gives me this error (Ubuntu 64bits, with .NET core runtime installed):

```

Failure processing application bundle.
Bundle header version compatibility check failed
A fatal error was encountered. Could not extract contents of the bundle
```

And, checking the size of the executable, it has changed from the source.

in the conda package: 82905640
in the source package: 82901544

So I guess it is a problem related with the binary relocalization... is there a way to avoid it to execute for a specific file?

**Comment by bgruening** [comment]
@CarlosHorro you can try https://github.com/conda-forge/cpptango-feedstock/blob/99dcfc9e0fd723aff82b89bfcfea650a1addd3ff/recipe/meta.yaml#L17

**Comment by bgruening** [comment]
Some documentation is here: https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#relocation

**Comment by CarlosHorro** [comment]
> Some documentation is here: https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#relocation

Thank you very much @bgruening , I will check that all.

**Comment by CarlosHorro** [comment]
Hi @bgruening ,

This is indeed the path to follow, because if I use :

`binary_relocation: False
`

MSAmanda binary executes correctly. But I am afraid of doing it because I am not sure of the consequences for the other executables in the package...

But, If I do this:

```
binary_relocation: 
    - share/searchgui-4.0.41-1/resources/MS Amanda/linux/MSAmanda
```
MSAmanda does not work. I have been doing many tests with this type of routes, based on the ones I find into the SG Conda package, and they do not seem to work...

Greetings,
Carlos

**Comment by CarlosHorro** [comment]
Hi @bgruening ,

This is indeed the path to follow, because if I use :

`binary_relocation: False
`

MSAmanda binary executes correctly. But I am afraid of doing it because I am not sure of the consequences for the other executables in the package...

But, If I do this:

```
binary_relocation: 
    - share/searchgui-4.0.41-1/resources/MS Amanda/linux/MSAmanda
```
MSAmanda does not work. I have been doing many tests with this type of routes, based on the ones I find into the SG Conda package, and they do not seem to work...

Greetings,
Carlos

**Comment by bgruening** [comment]
The Space in the path looks super suspicious ... try with quotes but also with globs ala: https://github.com/conda-forge/ctng-compilers-feedstock/blob/3d8d78f5c2c8a62764ad55450e1d8700cbb30b3e/recipe/meta.yaml#L71

**Comment by CarlosHorro** [comment]
> The Space in the path looks super suspicious ... try with quotes but also with globs ala: https://github.com/conda-forge/ctng-compilers-feedstock/blob/3d8d78f5c2c8a62764ad55450e1d8700cbb30b3e/recipe/meta.yaml#L71

As always, you are right  :-)   I was doing more tests and, using quotes and also globes it worked :-)  I jave already uploaded the fix.
Thank you very much!

**Review by dpryan79 — APPROVED** [review]

**Comment by CarlosHorro** [comment]
One second... I will recover the osx "fix" before merging...

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
@bioconda-bot please merge

**Pull request merged**
