### PR TITLE
Update pangolin to 3.1.17

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`pangolin`](https://bioconda.github.io/recipes/pangolin/README.html): **3.1.16** &rarr; **3.1.17**

[install with bioconda](http://bioconda.github.io/recipes/pangolin/README.html) [Conda](https://anaconda.org/bioconda/pangolin/files)

Info | Link
-----|-----
Recipe | [`recipes/pangolin`](https://github.com//bioconda/bioconda-recipes/tree/bump/pangolin/recipes/pangolin) (click to view/edit other files)
Releases |[https://github.com/cov-lineages/pangolin/tags](https://github.com/cov-lineages/pangolin/tags)
Author | `@cov-lineages`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by rpetit3** [comment]
Would like to get https://github.com/bioconda/bioconda-recipes/pull/31901 https://github.com/bioconda/bioconda-recipes/pull/31900 https://github.com/bioconda/bioconda-recipes/pull/31898 in first

**Comment by simonbray** [comment]
@BiocondaBot please merge

**Comment by simonbray** [comment]
Sorry @rpetit3 - I missed your comment.

**Comment by rpetit3** [comment]
No worries @simonbray!

**Pull request merged**
