### PR TITLE
update midas pinnings to match docs

### PR DESCRIPTION
**Pull request by rpetit3**
Updating the pinnings to match the docs: https://github.com/snayfach/MIDAS/blob/master/docs/install.md

I'm doing testing with build 6 docker container and its not liking samtools v1.12

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by rpetit3** [comment]
@biocondabot please fetch artifacts

**Comment by rpetit3** [comment]
@BiocondaBot please fetch artifacts

**Comment by rpetit3** [comment]
@BiocondaBot please fetch artifacts

**Comment by rpetit3** [comment]
@BiocondaBot please fetch artifacts

**Comment by rpetit3** [comment]
@BiocondaBot please fetch artifacts

**Comment by rpetit3** [comment]
I think its better now. On build 6 I was getting this error:

```
Error: could not execute samtools binary: samtools
(exited with error code 1)
To solve this issue, follow these steps:
  1) Download samtools v1.4: https://github.com/samtools/samtools/releases/download/1.4/samtools-1.4.tar.bz2
  2) Unpack and compile the software on your system
  3) Copy the new samtools binary to:
```

With the updated patch file It executes now:
```
MIDAS: Metagenomic Intra-species Diversity Analysis System
version 1.3.0; github.com/snayfach/MIDAS
Copyright (C) 2015-2016 Stephen Nayfach
Freely distributed under the GNU General Public License (GPLv3)

===========Parameters===========
Command: /usr/local/bin/run_midas.py species results -1 SRR2838702_R1.fastq.gz -2 SRR2838702_R2.fastq.gz -d midas/midas/ -t 4
Script: run_midas.py species
Database: midas/midas/
Output directory: results
Input reads (1st mate): SRR2838702_R1.fastq.gz
Input reads (2nd mate): SRR2838702_R2.fastq.gz
Remove temporary files: False
Word size for database search: 28
Minimum mapping alignment coverage: 0.75
Number of reads to use from input: use all
Number of threads for database search: 4
================================

Aligning reads to marker-genes database
  0.04 minutes
  0.77 Gb maximum memory

Classifying reads
  total alignments: 2
  uniquely mapped reads: 0
  ambiguously mapped reads: 0
  0.0 minutes
  0.78 Gb maximum memory

Estimating species abundance
  total marker-gene coverage: 0.0
  0.0 minutes
  0.78 Gb maximum memory
```

**Comment by rpetit3** [comment]
@BiocondaBot please add label

**Review by matthdsm — APPROVED** [review]

**Comment by rpetit3** [comment]
@BiocondaBot please merge

**Pull request merged**
