### PR TITLE
Update SnpEff

### PR DESCRIPTION
**Pull request by Dantistnfs**
PR Updates SnpEff version to 5.1f->5.2

### CODE REVIEW

**Comment by Dantistnfs** [comment]
@BiocondaBot please add label

**Comment by thanhleviet** [comment]
@Dantistnfs the updates look good to me but please keep the recipes separated as a PR each

**Comment by Dantistnfs** [comment]
@thanhleviet done

**Review by thanhleviet — APPROVED** [review]

**Comment by thanhleviet** [comment]
> @thanhleviet done, snpsift spearated to #43710

Great! Thanks for that 👍

**Pull request merged**
