### PR TITLE
Sequencetools 1.4.0

### PR DESCRIPTION
**Pull request by apeltzer**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by apeltzer** [comment]
@bioconda/core No idea how I can fix this here:

```bash
No setup information found for ghc-8.6.5 on your platform.
20:15:26 BIOCONDA INFO (OUT) This probably means a GHC bindist has not yet been added for OS key 'linux64-gmp4'.
20:15:26 BIOCONDA INFO (OUT) Supported versions: ghc-7.8.4, ghc-7.10.2, ghc-7.10.3, ghc-8.0.1, ghc-8.0.2, ghc-8.2.1, ghc-8.2.2, ghc-8.4.2
20:15:27 BIOCONDA INFO (OUT) Traceback (most recent call last):
```

The sourcecode doesn't specify that it needs ghc-8.6.5 anywhere I can see -

**Comment by dpryan79** [comment]
As I mentioned in the bot-generated PR (https://github.com/bioconda/bioconda-recipes/pull/14853), I think this will need someone familiar with Haskell to get working.

**Comment by apeltzer** [comment]
Mhm, seems to be rather tricky to get this going again: 

https://github.com/commercialhaskell/stack/issues/4161

**Comment by mfansler** [comment]
Looks like it's been switched over to precompiled executables, e.g., #33229

**Pull request closed without merging**
