### PR TITLE
Added in python-bioext 0.17.4

### PR DESCRIPTION
**Pull request by ericenns**
* [x] I have read the guidelines above.
* [x] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by ericenns** [comment]
I am at a loss for why this is failing any idea @bioconda/core

**Comment by ericenns** [comment]
Looks like it was due to python-consensuscore not having python version in the build string

**Comment by ericenns** [comment]
Not sure why osx build is failing, I don't have a Mac to test on. I might just set it to not build for osx on Monday if that is ok.

**Comment by bgruening** [comment]
Me neither, but can you try to add `export DYLD_FALLBACK_LIBRARY_PATH="${PREFIX}/lib"` maybe this will help.

**Comment by ericenns** [comment]
Ok trying the flag, I guess we will see if that works.

**Comment by ericenns** [comment]
Thanks for the advice @bgruening it ended up just needing a patch to look for osx specific library file so .dylib instead of .so.6

**Comment by bgruening** [comment]
Awesome! Thanks!

**Pull request merged**
