### PR TITLE
Update salmon to 1.10.3

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`salmon`](https://bioconda.github.io/recipes/salmon/README.html): **1.10.2** &rarr; **1.10.3**

[install with bioconda](http://bioconda.github.io/recipes/salmon/README.html) [Conda](https://anaconda.org/bioconda/salmon/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/salmon`](https://github.com//bioconda/bioconda-recipes/tree/bump/salmon/recipes/salmon) (click to view/edit other files)
Summary | Highly-accurate & wicked fast transcript-level quantification from RNA-seq reads using selective alignment
Home | [https://github.com/COMBINE-lab/salmon](https://github.com/COMBINE-lab/salmon)
Releases |[https://github.com/COMBINE-lab/salmon/tags](https://github.com/COMBINE-lab/salmon/tags)
Recipe Maintainer(s) | @rob-p, @k3yavi
Author | `@COMBINE-lab`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Review by rpetit3 — APPROVED** [review]

**Review by rob-p — APPROVED** [review]
It all looks good now!

**Comment by rob-p** [comment]
Thanks @rpetit3, @ewels, and @pabloaledo! This is great :).  BTW, we have arm-linux builds now, do you guys know if we have aarch for OSX (and if not, when that might land)?

**Comment by ewels** [comment]
@rob-p I was under the impression that we have OSX now as well. See the [anaconda page](https://anaconda.org/bioconda/salmon):

IMG_0652
IMG_0651

**Comment by rob-p** [comment]
Yea, so it lists OSX64 but not OSX-aarch, right?

**Comment by ewels** [comment]
Ohh right! On the bioconda PR / issues for ARM support I thought that there was a fair bit of discussion about OSX runners so was a bit quick to jump there sorry, as I was expecting it.

@rpetit3 / @dpryan79 - any idea?

**Pull request merged**
