### PR TITLE
Busco update

### PR DESCRIPTION
**Pull request by pvanheus**
:information_source:
If this is your first pull request to Bioconda please ping `@bioconda/core` so it can be reviewed and to request being added as a member of the Bioconda team. Members of the Bioconda team are able to merge their own pull requests once tests and linting have passed.

----------------

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by pvanheus** [comment]
with Augustus 3.3 I experienced core dumps from Augustus in BUSCO, so this recipe shifts the Augustus dependency to 3.3.2, which does not dump core.

**Comment by druvus** [comment]
Does the BLAST version needs to be pinned to an old version? I can not find any info about it in the BUSCO repo. It seems they are running latest BLAST version in their docker.

**Comment by druvus** [comment]
I also did some limited test of BUSCO using BLAST 2.2.31 vs. 2.7.1 and got identical results.  Would it be possible to relax the BLAST pinning?

**Comment by pvanheus** [comment]
@druvus there was a problem previously with multithreaded BLAST. See [this](https://github.com/nextgenusfs/funannotate/issues/236) discussion where it is mentioned as existing up to at least BLAST+ 2.7.

**Comment by druvus** [comment]
Thanks for the explanation!

**Comment by beroe** [comment]
Is it clear that v 2.9 still has this error? 
https://www.ncbi.nlm.nih.gov/books/NBK131777/

**Pull request merged**
