### PR TITLE
added bioconductor-mbamethyl

### PR DESCRIPTION
**Pull request by MathiasHaudgaard**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [ ] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by bgruening** [comment]
@MathiasHaudgaard do you see know this `sqash and merge` button?

**Comment by MathiasHaudgaard** [comment]
no I don't. I would like to merge my PR myself so you don't have to deal with them but I can't see this merge button anywhere.

**Comment by bgruening** [comment]
I invited you to this organisation, you should have a mail. If you accept you can merge your PRs yourself if you stick to the guideline. Please also tell this the other bio.tools hackers I can grant you access after a view reviews. Thanks a lot for working on this.

Please also note that you might be faster by committing 10 recipes at once.

**Comment by MathiasHaudgaard** [comment]
Sorry for the confusion but I'm still not sure how to merge my own PRs. Maybe I have forgotten to accept the invite or something. Could you send me a link on the guidelines? Right now I'm using this link https://bioconda.github.io/contribute-a-recipe.html and I don't see anything about merging my own PRs.

**Comment by bgruening** [comment]
Did you get a mail from github with an invitation to bioconda?

**Comment by MathiasHaudgaard** [comment]
I think so. Not sure if I accepted anything. It's been a while. Could you send another invitation?

**Comment by MathiasHaudgaard** [comment]
Or is there somewhere I can see if I'm a member of bioconda?

**Comment by bgruening** [comment]
I just did this and you never accepted :)

**Comment by MathiasHaudgaard** [comment]
I didn't receive any mail :-)

**Comment by bgruening** [comment]
Check your github account and the mail address which you provided during registration.
You can also check your pending invitations: https://help.github.com/articles/canceling-or-editing-an-invitation-to-join-your-organization/

**Comment by MathiasHaudgaard** [comment]
Now I found something! It seems like Ryan Dale invited me the 9th of july. Just forgot to accept the invite. Anyway thanks for the help. :-)

**Comment by bgruening** [comment]
Now you see under your PRs a green button that states you can merge the PR if all tests pass.

**Comment by MathiasHaudgaard** [comment]
Yes I see it. Thanks! :-)

**Pull request merged**
