### PR TITLE
Update proteinortho to 6.0

### PR DESCRIPTION
**Pull request by epruesse**
Update [`proteinortho`](https://bioconda.github.io/recipes/proteinortho/README.html): **6.0b** &rarr; **6.0**

[install with bioconda](http://bioconda.github.io/recipes/proteinortho/README.html) [Conda](https://anaconda.org/bioconda/proteinortho/files)

Info | Link
-----|-----
Recipe | [`recipes/proteinortho`](https://github.com//bioconda/bioconda-recipes/tree/bump/proteinortho/recipes/proteinortho) (click to view/edit other files)
Releases |[https://gitlab.com/paulklemm_PHD/proteinortho/tags](https://gitlab.com/paulklemm_PHD/proteinortho/tags)

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/updating.html)).

### CODE REVIEW

**Comment by npavlovikj** [comment]
@epruesse , sorry for the bother, but I have a really basic question. If I want to update this recipe, do I need to clone the main bioconda repo (not my fork), checkout the branch `bump/proteinortho`, and add the changes there? And if that is the case, would me updating this recipe be ok with you?

**Comment by epruesse** [comment]
@npavlovikj Yes, to update this one you have to push to the `bump/proteinortho` branch on `git@github.com/bioconda/bioconda-recipes`. You can either clone that repo to a different folder, or you can add a second remote to your existing local bioconda-recipes clone. So basically:

```
git remote add upstream git@git.github.com/bioconda/bioconda-recipes.git
git fetch --all
git checkout bump/proteinortho
...
git push upstream
```

(out of memory, might need to fix the url if I got it wrong)

**Comment by npavlovikj** [comment]
Many thanks @epruesse  - the second remote is working perfectly. And thanks for fixing the duplicate key, I mistyped that.

**Comment by epruesse** [comment]
LGTM. Do you want to tell the bot to `@biocondabot merge`? You should have permission now.

**Comment by npavlovikj** [comment]
Yes, I would like to try that :)

**Comment by npavlovikj** [comment]
@BiocondaBot merge

**Pull request merged**
