### PR TITLE
molpopgen-analysis : add a warning following PR7563

### PR DESCRIPTION
**Pull request by pbordron**
Add a warning following https://github.com/bioconda/bioconda-recipes/pull/7563#issuecomment-367736770

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by rvalieris** [comment]
in this case I think we should add a post-link warning, so that the deprecated message will appear after the package is installed.

see here for information: https://conda.io/docs/user-guide/tasks/build-packages/link-scripts.html
example: https://github.com/bioconda/bioconda-recipes/blob/master/recipes/variant-effect-predictor/post-link.sh

**Comment by pbordron** [comment]
Maybe for cluster users having a warning when the user loads the environment is a good idea.

**Comment by rvalieris** [comment]
could be, I never tried but you can create `$PREFIX/etc/conda/activate.d/warning.sh`
see: https://conda.io/docs/user-guide/tasks/manage-environments.html#saving-environment-variables

**Comment by rvalieris** [comment]
looks good just 2 more things:
1. include the name of the package in the warnings, so that the user know where its coming from
2. I think the activate script should also contain the name of the package because the file will be installed in a common place, it could conflict with other packages.

**Comment by rvalieris** [comment]
perfect ! thanks a lot !

**Pull request merged**
