### PR TITLE
Update Maxbin2

### LINKED ISSUE #24707: maxbin2.2.7 has missing package
```
Can't locate LWP/Simple.pm in @INC (you may need to install the LWP::Simple module) (@INC contains: /Workindir/databases/conda_envs/40f36dfb/lib/site_perl/5.30.3/x86_64-linux-thread-multi /Workindir/databases/conda_envs/40f36dfb/lib/site_perl/5.30.3 /Workindir/databases/conda_envs/40f36dfb/lib/5.30.3/x86_64-linux-thread-multi /Workindir/databases/conda_envs/40f36dfb/lib/5.30.3 .) at /Workindir/databases/conda_envs/40f36dfb/bin/run_MaxBin.pl line 4.
```

related to #18267

@bgruening Can this pearl package be added? 

I use python 3.6 in a miniconda docker container

### PR DESCRIPTION
**Pull request by SilasK**
Describe your pull request here

should Fix #24707

Fix https://github.com/metagenome-atlas/atlas/issues/328

Apparently metabat works with perl=5.26 and no longer with perl 5.30

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by SilasK** [comment]
@BiocondaBot please add label

**Comment by dpryan79** [comment]
Looks like their server is down. We'll either have to wait until it's back up or find another URL for the source code.

**Comment by SilasK** [comment]
You can get it from https://sourceforge.net/projects/maxbin2/ but I fear there is no way to get a downloadable url

**Review by colinbrislawn — COMMENTED** [review]
I have not worked with Maxbin2 in ages and am not in contact with the authors.
Sorry I can't help more. 😿
Would you be will to remove me as a reviewer?

**Comment by colinbrislawn** [comment]
Looks like the code is still online here, but I'm not sure if it's a build-friendly direct download. https://sourceforge.net/projects/maxbin2/files/

**Comment by SilasK** [comment]
@colinbrislawn Thank you for the tip your URL worked. I hope the checks pass. Would you mind to still approve this PR. I can remove you as recipe maintainer, if you want.

**Review by colinbrislawn — APPROVED** [review]
Looks good. Let's see if it builds!

**Comment by SilasK** [comment]
@bioconda-bot please merge

**Pull request merged**
