### PR TITLE
Update strangepg to 0.8.14

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`strangepg`](https://bioconda.github.io/recipes/strangepg/README.html): **0.8.13** &rarr; **0.8.14**

[install with bioconda](http://bioconda.github.io/recipes/strangepg/README.html) [Conda](https://anaconda.org/bioconda/strangepg/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/strangepg`](https://github.com//bioconda/bioconda-recipes/tree/bump/strangepg/recipes/strangepg) (click to view/edit other files)
Summary | Strange pangenome-scale interactive graph visualizer
Home | [https://github.com/qwx9/strangepg](https://github.com/qwx9/strangepg)
Releases |[https://github.com/qwx9/strangepg/tags](https://github.com/qwx9/strangepg/tags)
Recipe Maintainer(s) | @qwx9
Author | `@qwx9`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by qwx9** [comment]
@coderabbitai pause

**Comment by qwx9** [comment]
Please close this PR -- I had to make changes and submit an update manually, making some significant changes. PR #52066 replaces this one and passes tests locally. I don't know if it is possible to actually update this one or delete it myself, or to prevent an autobump temporarily, it didn't work the last time I tried.
Sorry for the noise and inconvenience.

**Comment by qwx9** [comment]
@mencian Thanks for the fixes you made. I took the liberty of merging some of them in the other PR (#52066), which should replace this one.
You made some changes to the build.sh script which I merged differently, based on what I found in documentation for gcc, clang and make:
- INCLUDE_PATH should be C_INCLUDE_PATH or CPATH
- bioconda's CFLAGS and CPPFLAGS use -O2 and CPPFLAGS appears last on the compilation command line, superceding anything we add to CFLAGS here, so I figure just leave it at -O2
- my Makefile honors build variables and never overrides their contents, but it *does* append to them; specifying them on the command line disables any assignment to these variables and breaks the build. Exported environment variables are automatically pulled in as variables with GNU make, so I only put CC and PREFIX which should never be touched inside the Makefile.
Thanks again!

**Comment by mencian** [comment]
Closing in favor of #52066.

**Pull request closed without merging**
