### PR TITLE
clean samtools recipe

### PR DESCRIPTION
**Pull request by rvalieris**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [x] This PR does something else (explain below).

xref: https://github.com/bioconda/bioconda-recipes/issues/9056

* added https protocol test
* removed redundant  configure/make on htslib directory
* removed enable-plugins flags

still pending linking against the htslib package, but since conda-build 3 is close, I think we can wait for that to avoid pinning htslib.

the enable-plugins flag was removed, but note that since the plugins where never built no functionally was removed, if the plugins are desired we will have to include them on htslib recipe first and link here later.

### CODE REVIEW

**Comment by kyleabeauchamp** [comment]
I think we should make the same parallel changes to bcftools.  WDYT?

**Comment by rvalieris** [comment]
osx build failed with 
> bgzf.c:39:10: fatal error: 'libdeflate.h' file not found

did I do something wrong ?

**Comment by kyleabeauchamp** [comment]
Hmm, I *thought* I had libdeflate support working in both bcftools and samtools.  Perhaps there needs to be some additional compiler flags set.  ("-I" ?).  Not sure what the problem is.  If you need to disable the lib-deflate in bcftools, that's not the end of the world (we can always re-visit when we have CB3 + separate HTSLib package).

**Comment by rvalieris** [comment]
cool, thanks for the help @kyleabeauchamp.

**Pull request merged**
