### PR TITLE
enum34 was missing as a dependency for MultiQC

### PR DESCRIPTION
**Pull request by dpryan79**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by dpryan79** [comment]
@aschuerch: I'll merge once this passes testing, thanks for finding the issue!

**Comment by aschuerch** [comment]
Thanks for the swift action!

**Comment by dpryan79** [comment]
Looks like I have to update conda-forge to use python-3.6 first. Just a heads up that this might take a bit of time.

**Comment by dpryan79** [comment]
Nevermind, it's built into them.

**Comment by dpryan79** [comment]
Apparently this was needed in python3 too, so I will in fact update conda-forge and then make yet another PR.

**Pull request merged**
