### PR TITLE
Update mimseq to 1.2

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`mimseq`](https://bioconda.github.io/recipes/mimseq/README.html): **1.1.7** &rarr; **1.2**

[install with bioconda](http://bioconda.github.io/recipes/mimseq/README.html) [Conda](https://anaconda.org/bioconda/mimseq/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/mimseq`](https://github.com//bioconda/bioconda-recipes/tree/bump/mimseq/recipes/mimseq) (click to view/edit other files)
Summary | Modification-induced misincorporation tRNA sequencing.
Home | [https://github.com/nedialkova-lab/mim-tRNAseq](https://github.com/nedialkova-lab/mim-tRNAseq)
Releases |[https://pypi.org/pypi/mimseq/json](https://pypi.org/pypi/mimseq/json)

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by drewjbeh** [comment]
@dpryan79 perhaps you can help here. This is the second time I am getting this error code 137 during the linux test. Not sure what to do about it. conda-utils builds the package fine locally, and my guess is that this has something to do with resources allocated by Azure?

**Comment by dpryan79** [comment]
@drewjbeh I'll take a look

**Comment by dpryan79** [comment]
You're correct that this is a resource issue on azure. Testing in a minimal docker container sometimes requires more RAM than that has available, so we have to make the conda-solver's job a bit easier. With the gradual transition to mamba for that it will hopefully become less of an issue over time.

**Comment by dpryan79** [comment]
@BiocondaBot please fetch artifacts

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@BiocondaBot please merge

**Comment by drewjbeh** [comment]
@dpryan79, awesome thanks a lot!

**Pull request merged**
