### PR TITLE
Prosolo fresh

### PR DESCRIPTION
**Pull request by dlaehnemann**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

I'm creating this pull request even though the Travis CI test for osx still fails. However, I don't seem to get anywhere with debugging the error it produces:

```
thread 'main' panicked at 'assertion failed: src_path.is_absolute()', cargo/src/cargo/core/manifest.rs:305
```

Maybe @johanneskoester or someone else from @core has some quick (Rust on osx) insight here, otherwise I'll probably take this to Stackoverflow. Or is it OK to provide a recipe for linux64 only?

### CODE REVIEW

**Comment by bgruening** [comment]
@dlaehnemann it is ok to skip OSX builds.

**Comment by johanneskoester** [comment]
Looks like a bug in cargo...

**Comment by dlaehnemann** [comment]
So I'll skip the OSX build and mention it in the notes.

Thanks for the lightning fast responses @bgruening and @johanneskoester !

**Comment by johanneskoester** [comment]
Which version of rust causes the error? We should actually have Rust 1.19 now (I have put it into conda-forge), but it might be hidden by own own one here in bioconda...

**Comment by johanneskoester** [comment]
Nope, I'm wrong, I have 1.18 in conda-forge. I can do an update of the feedstock and we can see if the error disappears.

**Comment by dlaehnemann** [comment]
Sure, that would be worth a try. And if it doesn't work I can still skip the OSX build.

**Comment by johanneskoester** [comment]
xref: conda-forge/rust-feedstock#5

**Comment by johanneskoester** [comment]
It is merged. You should be able to do a rebuild in an hour or so.

**Comment by johanneskoester** [comment]
Oh well, looks like conda-forge has some infrastructure problems: https://circleci.com/gh/conda-forge/rust-feedstock/11

If it is urgent, feel free to skip osx with a note for now.

**Comment by dlaehnemann** [comment]
Only slightly urgent and enough stuff to do, so I'll just wait it out. Or do you think the infrastructure problems could take days to get sorted?

**Comment by bgruening** [comment]
I'm working on this ... one PR away to get this solved. Hopefully in 12h.

**Comment by bgruening** [comment]
New rust release should be available!

**Comment by dlaehnemann** [comment]
OSX build with the rust 1.19 still fails, so I'd opt for linux64 only, for now. Any objections?

**Comment by bgruening** [comment]
Not from my side.

**Comment by bgruening** [comment]
Thanks @dlaehnemann

**Comment by dlaehnemann** [comment]
Thanks @bgruening

**Pull request merged**
