### PR TITLE
Add EnrichM

### PR DESCRIPTION
**Pull request by apcamargo**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences**
      (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by apcamargo** [comment]
Hey @bioconda/core. I'm getting a `conda.exceptions.InvalidVersionSpec: Invalid version '>=3.0.1': invalid character(s)` error in the OSX build. Any ideas what may be going on here?

Thanks!

**Comment by dpryan79** [comment]
Remove the version specifier on r-base, since all builds are pinned to a single version of it.

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Comment by apcamargo** [comment]
Thank you @dpryan79 and @mbargull!

**Pull request merged**
