### PR TITLE
Bumping varfish-annotator-cli version to v0.9

### PR DESCRIPTION
**Pull request by holtgrewe**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by holtgrewe** [comment]
@bioconda/core This is just a simple version bump and ready for review.

**Comment by holtgrewe** [comment]
@mbargull thanks, could you help me out here and give me a concrete example? I'll add this to all of my recipes in the future.

**Comment by mbargull** [comment]
> give me a concrete example?

Not really ;P. I never used that myself hence only remembered it existed but not how it works in detail.
Plus, it is not too common since you usually get one release archive that contains the entire source and license information (which is usually preferable). Since I don't know much more, I can only provide the list of Bioconda recipes with that feature:
```
> grep -l '^ *-\? *folder:' recipes/*/meta.yaml
recipes/admixture/meta.yaml
recipes/anise_basil/meta.yaml
recipes/bcftools-snvphyl-plugin/meta.yaml
recipes/cfm/meta.yaml
recipes/demuxlet/meta.yaml
recipes/frogs/meta.yaml
recipes/ganon/meta.yaml
recipes/gembs/meta.yaml
recipes/gffcompare/meta.yaml
recipes/ncbi-util-legacy/meta.yaml
recipes/orfm/meta.yaml
recipes/pb-dazzler/meta.yaml
recipes/pb-falcon/meta.yaml
recipes/plasflow/meta.yaml
recipes/rgi/meta.yaml
recipes/sra-tools/meta.yaml
```

**Comment by mbargull** [comment]
> I'll add this to all of my recipes in the future.

Oh, or did you mean `about/license_file` in general? If you have a release archive that includes a file named `LICENSE`, everything is much simpler, of course:
```yaml
about:
  license: MIT
  license_file: LICENSE
```

**Pull request merged**
