### PR TITLE
platypus update

### PR DESCRIPTION
**Pull request by mictadlo**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by mictadlo** [comment]
Hi @bioconda/core ,
By any chance, does anyone know why the recipes failed?

Thank you in advance,

Michal

**Comment by bgruening** [comment]
The error is: `Platypus.py': [Errno 2] No such file or directory`

**Comment by mictadlo** [comment]
Thank you, by any chance, do you have any idea how to fix it?

**Comment by chapmanb** [comment]
Thanks for working on this. Is the goal of updating to get the refcall fix in the latest Platypus development? The install requires a release tarball that has the buildPlatypus.sh script, this isn't present in a clone of the bare GitHub repo in the right place. I could try and update my repo and get this in place; it's been a while since I've looked at this and I don't remember all the details. Thanks for looking into this.

**Comment by chapmanb** [comment]
Michal;
Thanks for the push to get this in sync. I made a tarball of a new point release with the additional fix in master as 0.8.1.2:

https://github.com/chapmanb/Platypus/releases/download/v0.8.1.2/Platypus_0.8.1.2.tgz

If you change the recipe to point at this hopefully it'll build cleanly now. Thanks again.

**Comment by mictadlo** [comment]
What did I miss?

**Comment by dpryan79** [comment]
Either rebase or merge master into your branch.

**Comment by mictadlo** [comment]
I did `git push -u origin platypus`. What else do I have to do?

**Comment by dpryan79** [comment]
git checkout master
    git pull
    git checkout platypus
    git merge master
    git push

**Comment by mictadlo** [comment]
Thank you for all your help.

**Pull request merged**
