### PR TITLE
bioconductor-ideal (my package) and its dependency r-rintrojs

### PR DESCRIPTION
**Pull request by federicomarini**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

@bgruening : I finally made it to come up with the two recipes for my package. They both work on my system but could not have the full run on the TravisCI machines. Any hints on this? Probably because I need one as dependency to the other?

If anything needs to be clarified, I am happy to comply. And happy to learn ;)
Federico

### CODE REVIEW

**Comment by daler** [comment]
Thanks @federicomarini. Including all new dependencies in a pull request does work in general. However the past couple of days travis-ci has been having a lot of technical difficulties. Those issues appear to be resolved and so theoretically it should work now. 

However, the `r-introjs` package is not biology-specific. Would you please submit this package to conda-forge? https://conda-forge.org/docs/ has details.

We have a helper script for cleaning R recipes for conda-forge. It gets rid of comments and adds maintainers, and you can use it like this:

```bash
bioconda-utils clean-cran-skeleton recipes/r-rintrojs
```
Then move `r-introjs` to a new clone of `conda-forge/staged-recipes`. After `r-introjs` has been added to the conda-forge channel it will be available for installation and you can remove it from this PR. The remaining `bioconductor-ideal` recipes looks good as-is.

**Comment by federicomarini** [comment]
Thanks for chiming in so quickly, @daler.

I'll wait for the travisCI check to be finished, and then read up how to go the conda-forge way.
I am already quite happy it worked out nicely for the 2-recipes-set on a linux machine.

I guess I will contact you again once `r-rintrojs` is available over there?
F

**Comment by federicomarini** [comment]
As a reference to this, here's the link to my PR in conda-forge:
https://github.com/conda-forge/staged-recipes/pull/4809

**Comment by bgruening** [comment]
@federicomarini so cool to see you here finally! Rock on and see you in March! :)

**Comment by federicomarini** [comment]
A promise is a promise, @bgruening. Which also reminds me I'll owe you at least one beer. March is a good point to settle the issue!

**Comment by daler** [comment]
@federicomarini no need contact -- once it's available you can remove `r-rintrojs` from your PR here. That will trigger a re-build on travis-ci. Hopefully that alone with do the trick, and once the tests turn green here we will merge.

**Comment by federicomarini** [comment]
Ok I will sit tight for the whole CIs to be passed + build on conda-forge!

**Comment by federicomarini** [comment]
Update here: `r-rintrojs` is happily ready at https://anaconda.org/conda-forge/r-rintrojs/files, so I pushed the changes with only `ideal` in the PR. The MacOS builds seem to be encountering delays on the CI side, so I'll hang tight 😃

**Comment by daler** [comment]
@federicomarini great! And yeah, unfortunately MacOS may take a while to catch up.

**Comment by bgruening** [comment]
OSX is crashing because of the missing OSX package from conda-forge. We still need to wait.

**Comment by bgruening** [comment]
I restarted it already ;) But lets wait now :)

**Comment by bgruening** [comment]
Cool thanks!

**Comment by federicomarini** [comment]
Yay :)

**Pull request merged**
