### PR TITLE
[WIP] Upgrade freebayes recipe

### PR DESCRIPTION
**Pull request by kyleabeauchamp**
* [ ] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by kyleabeauchamp** [comment]
Tried, but I can't use the release tarball.  The build depends on a recursive clone and the github release drops those symlinks.

**Comment by kyleabeauchamp** [comment]
OK this is almost working, modulo C++11 nonsense on OSX:

https://travis-ci.org/bioconda/bioconda-recipes/jobs/173309131#L1486

**Comment by kyleabeauchamp** [comment]
@bioconda/core  I'm getting backend at capacity errors on my latest build.  Anyone noticed this?

**Comment by kyleabeauchamp** [comment]
I'm happy to click the "restart build" button but I don't want to clog the pipeline until things clear up.

**Comment by kyleabeauchamp** [comment]
*edit I restarted the build.

**Comment by bgruening** [comment]
@kyleabeauchamp does this help: https://github.com/conda-forge/boost-feedstock/blob/master/recipe/build.sh

They deal with the same mess as far as I can see.

**Comment by bgruening** [comment]
@kyleabeauchamp it turned green!!!!

**Comment by kyleabeauchamp** [comment]
Don't merge.  I'm currently pointed to a fork, which is bad form...

**Comment by chapmanb** [comment]
Kyle -- is this still pending any updates? I'd love to work on validating 1.1.0 and start moving to it, and happy to help with getting the build into bioconda.

**Comment by kyleabeauchamp** [comment]
So this works but uses walaj's fork of freebayes with many changes to the
makefile.  We can either merge as is or try to get his changes into
master.  You could even take walajs fork and open a pr to freebayes master.

**Comment by chapmanb** [comment]
Kyle -- thanks for bumping the thread suggesting merging these into the main branch. I agree that makes the most sense for improving FreeBayes. Practically for bioconda, it would be helpful to merge this as is so folks can use FreeBayes 1.1.0 and then update it to point to the main FreeBayes branch once the Makefile makes it there. I finished 1.1.0 validations and am excited about it -- it gives nearly identical results to 1.0.2 and is much quicker. Thanks for all the work making this happen.

**Comment by kyleabeauchamp** [comment]
If you're happy with this approach, +1 to merge.

**Comment by kyleabeauchamp** [comment]
Looks like the wheels are moving on the Freebayes change, so I suppose it makes sense to update my PR to work with those changes.  If you need to proceed immediately, you can open a new PR off of  commit 0cce311 from this PR.

**Comment by kyleabeauchamp** [comment]
See https://github.com/ekg/freebayes/pull/338

**Comment by chapmanb** [comment]
Kyle -- thanks for all your work on this. Brilliant job. I'll merge this now pointing at Jeremiah's branch since it hasn't yet gotten into master and we can point back to the main branch once all the Makefile updates are there. Thanks again.

**Pull request merged**
