### PR TITLE
Bump IgBLAST to 1.7.0

### PR DESCRIPTION
**Pull request by marcelm**
* [ ] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

Keep IgBLAST 1.4.0 in a subdirectory

### CODE REVIEW

**Comment by marcelm** [comment]
@bioconda/core This recipe fails and I don’t know why. The log contains a lot of stuff, but nothing helpful. A local `simulate-travis.py` run finishes successfully.

**Comment by daler** [comment]
Looks like a mulled-build test fail. @bgruening any ideas? Can we get more debug info from mulled-build?

**Comment by bgruening** [comment]
@marcelm I think if you remove the /dev/null from your test you will get an error message: `igblastn -h > /dev/null 2>&1`
Also please note that you have not specified the gcc/llvm compiler in your updated recipe.

**Comment by bgruening** [comment]
`[Nov 21 20:51:20] SERR /usr/local/bin/../share/igblast/bin/igblastn: error while loading shared libraries: libbz2.so.1: cannot open shared object file: No such file or directory`

**Comment by marcelm** [comment]
This did not work because the conda bzip2 package does not include `libbz2.so`, only `libbz2.a` (for static linking).

This recipe packages the binary version of IgBLAST, so changing compile-time options is not possible.

Any ideas?

**Comment by jlanga** [comment]
HI @marcelm. I had the same issue some days ago with `blast+`. There is a [PR at conda-forge](https://github.com/conda-forge/staged-recipes/pull/1977) that should will fix this.

**Comment by marcelm** [comment]
Ah, this is great, then I’ll just have to wait! :-)

**Comment by marcelm** [comment]
Current status: The conda-forge PR with the bzip2 recipe at conda-forge/staged-recipes#1977 was closed without being merged. Instead, conda-forge/staged-recipes#2467 has been merged, which includes a bzip2 recipe, but without Linux shared libs.

**Comment by johanneskoester** [comment]
Can the work from the first PR be easily included into the new bzip2 feedstock?

**Comment by marcelm** [comment]
I hope so, I’ll make a PR.

**Comment by johanneskoester** [comment]
Thanks!

**Comment by marcelm** [comment]
I opened [a PR](https://github.com/conda-forge/bzip2-feedstock/pull/1). However, there is another problem: The channel order [recommended in the bioconda manual](https://bioconda.github.io/#set-up-channels) lists conda-forge *after* defaults, so actually the version from conda-forge isn’t used (defaults has 1.0.6-3 and conda-forge has 1.0.6-0). Any suggestions of how best to solve this?

**Comment by johanneskoester** [comment]
The only way to solve this is to finally get rid of the R channel. Then, we can have conda-forge with a higher priority than defaults. I hope to be able to make some more progress on that soon. Any help would be appreciated.

**Comment by marcelm** [comment]
A workaround would be to increase the build number to 4 and have this recipe depend on 1.0.6-4 or later. Not the preferred solution of course.

**Comment by johanneskoester** [comment]
Yes, that would work. I don't know if the conda-forge people would object against this.

**Comment by marcelm** [comment]
Hi @bioconda/core I have finally fixed this recipe by not using the prebuilt binaries on Linux, but instead compiling from sources. This circumvents the issue with `libbz2.so` not being available in the `bzip2` package from the defaults channel. Since the changes are larger than for a normal version bump, I’d like to get a review.

**Pull request merged**
