### PR TITLE
Update glimmerhmm 3.0.4 build 5

### PR DESCRIPTION
**Pull request by hyphaltip**
Describe your pull request here

This should fix the glimmerhmm install -- not sure if tests are totally working, but this version should update to make sure the perl loading is working properly.
----
<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by hyphaltip** [comment]
So the tests were failing for this because the help mode (eg `glimmerhmm -h` or `trainGlimmerHMM` were returning error code 255 even just a programs spitting out cmdline warning (the perl prog is exiting with `die` so I suppose this is expected).  
```bash
$ glimmerhmm -h > /dev/null
$ echo $?
255
$ trainGlimmerHMM > /dev/null
$ echo $?
255
```

So I rigged testing a bit to spit out messages but to essentially guarantee true test.  not sure if another approach would be better but I don't see how else this could be overcome unless we just tested for existence of the tools (echo `which glimmerhmm` ?)

**Comment by hyphaltip** [comment]
I think these fixes now allow tests to pass, please check I did this okay because I removed this package from the blacklist , updated the URL to http origin, and did some small workaround so the tests would pass. fixing this package is needed as build 2 doesn't properly load the perl library and set the shebang correctly. 

@BiocondaBot please add label

**Comment by hyphaltip** [comment]
@BiocondaBot please fetch artifacts

**Review by AlWa1 — APPROVED** [review]

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
@BiocondaBot please merge

**Pull request merged**
