### PR TITLE
bump vsearch to 2.10.4

### PR DESCRIPTION
**Pull request by colinbrislawn**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by nextgenusfs** [comment]
Any idea why `vsearch` not working on osx since v2.7.0? Anything we can do about this?

**Comment by epruesse** [comment]
Can you elaborate on “not working”?

**Comment by nextgenusfs** [comment]
Its specifically not building for osx: https://github.com/bioconda/bioconda-recipes/blob/f789635969a66b4738c69b222b0c8ea1f1b71d08/recipes/vsearch/meta.yaml#L14

**Comment by colinbrislawn** [comment]
Yep, this is an issue with compilers. I tried to fix it over in #11702, but couldn't.

I hope you can fix it as I would like to use modern vsearch on OSX.

**Pull request merged**
