### PR TITLE
samtools w/ openssl-1.1.1 (but not pinned)

### PR DESCRIPTION
**Pull request by pb-cdunn**
Another attempt to deal with python2.7.15/openssl issues. E.g.
https://github.com/PacificBiosciences/pbbioconda/issues/85

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by kyleabeauchamp** [comment]
Could this be fixed by bumping the build number and leaving the version unchanged?

**Comment by pb-cdunn** [comment]
@kyleabeauchamp , Actually, I just realized something. The current build needs to specify the current openssl, to catch the problem earlier. I will do what you suggest first, but with the old `openssl` specified, since that's what people were actually using.

Then, we can talk about how to *fix* the problem...

**Comment by pb-cdunn** [comment]
`Malformed version string '>=1.0.2,<1.1.1'`

I'll try simply rebuilding, without specify the openssl version. That's not quite right, but it might be most likely to let current users keep what they have.

**Comment by kyleabeauchamp** [comment]
Cool.  We'll be rebuilding with GCC7 soon (https://github.com/bioconda/bioconda-recipes/issues/13155), which might be another opportunity for further cleanup.

**Comment by pb-cdunn** [comment]
That didn't work. `conda update samtools` updated to that build, but it still dynamically links with openssl-1.0.2. I will require openssl >= 1.1.1. Since we don't want a version bump of samtools, I think some people will break, but I don't see a better set of options. Things are already pretty broken.

**Comment by bgruening** [comment]
@kyleabeauchamp we are ready. Everything is in place.

**Comment by pb-cdunn** [comment]
Maybe related: https://github.com/conda-forge/conda-forge.github.io/issues/701

I hope the GCC7 update fixes everything. I'm out of ideas.

**Pull request merged**
