### PR TITLE
Update bcftools-gtc2vcf-plugin to 1.16

### PR DESCRIPTION
**Pull request by cpalmer718**
This PR bumps the existing `bcftools-gtc2vcf-plugin` package to 1.16 to match bcftools/htslib. The recipe is fairly heavily modified from the existing version, in an attempt to streamline the update process and remove a large number of patches that address standard C syntax idiosyncrasies. The recipe passes `bioconda-utils lint/build` on linux-64. Content and style suggestions are all very welcome.

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by daler** [comment]
I see on the upstream repo there's a [line in the readme on 1.9 in conda being out of date](https://github.com/freeseek/gtc2vcf/blob/master/README.md?plain=1#L6), so thanks for updating this.

Generally bioconda recipes are updated in-place, and the history can be found in git as well as the recipe included in each package. In this case, not quite sure why we have a versioned subdirectory for 1.9 in the existing repo. Can you move the files in this PR from `bcftools-gtc2vcf-plugin/1.16` to `bcftools-gtc-vcf-plugin/`? Then future versions can update in place.

To make sure I understand the build.sh, the process is to download bcftools source, copy over the plugin .c and .h to the plugins dir, compile bcftools, and then only copy over the freshly-compiled plugins back over to the *existing*, conda-installed bcftools plugin dir. Is that right? bcftools itself doesn't need to be replaced?

Anyway, tricky recipe, and looks a lot cleaner now, thanks!

**Comment by cpalmer718** [comment]
@daler Fancy meeting you here :)

Yes, I spoke with the plugin developer some time ago and he expressed some frustration about the recipe being so out of sync. I don't think he has personal interest in maintaining it though. I've been using a local channel build of this plugin for a few years now, but the recipe more closely matched the existing 1.9 recipe, and so was a beast to maintain. Bumping to the cxx toolchain fixes an assortment of problems, and I think more closely matches the plugin's native build process.

So yes, the bcftools standard plugin structure is that they live in the `plugins/` directory of the [bcftools repo](https://github.com/samtools/bcftools) (I know you know this but I'm adding it here for posterity), and are built in place when bcftools proper is built. This plugin isn't one of the bundled ones, but it needs the bcftools source present. So, build.sh dumps the relevant plugin sources into the local bcftools source directory, configures and builds the project in the standard autotools way, and then only installs the plugin shared objects into the actual package. It's quite awkward, and obviously very strictly requires a matching bcftools build; but this is standard for bcftools/htslib already, which update versions together.

**Comment by cpalmer718** [comment]
I *think* this should correctly enforce version matching between this package and bcftools, but I've been screwed by this in the past (usually with boost-cpp), so if you (@daler ) notice anything about the bcftools dependency specification here that would ever allow conda to incidentally install, e.g., bcftools 1.17 when it arrives in conda, please flag it!

**Comment by daler** [comment]
Lucky you caught me on the 20 mins I'm able to spend on bioconda a month :)

Agreed, I think this theoretically keeps bcftools 1.16 pinned. It's a complicated recipe though, so always a chance that 1.17 could find its way in somehow. But I don't see anything obvious here that would let it. And thanks for the info and clarification.

**Review by daler — APPROVED** [review]

**Comment by daler** [comment]
@bioconda-bot please merge

**Comment by daler** [comment]
@bioconda-bot please fetch artifacts

**Comment by daler** [comment]
Currently hitting a rate limit on the bot...will try merging again tomorrow

**Comment by cpalmer718** [comment]
Ah, I see. Poor bot buddy. No worries. Thanks for checking on this. Feels like old times! Though I'm less scared of git now than I was... mostly lol

**Comment by daler** [comment]
@bioconda-bot please merge

**Comment by daler** [comment]
So it looks like it went through, https://anaconda.org/bioconda/bcftools-gtc2vcf-plugin, even though the upload was reported to fail in the PR comments here. I'll merge this manually, but you should try installing the package to make sure it's OK. In the meantime, looks like the bot will need some therapy sessions...

I just noticed the little tag thingy on the PR description, didn't realize it was your first bioconda contribution, hopefully the first of many!

**Comment by cpalmer718** [comment]
I'm able to download it successfully. I'll test it again when 1.17 percolates its way into the channel, to be sure the pinning is working correctly. Thank you for your help. I've been writing recipes for local channels for some years now, but have been hesitant to PR them for various reasons. I hope to change that in the future.

**Pull request merged**
