### PR TITLE
Update htslib to 1.16

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`htslib`](https://bioconda.github.io/recipes/htslib/README.html): **1.15.1** &rarr; **1.16**

[install with bioconda](http://bioconda.github.io/recipes/htslib/README.html) [Conda](https://anaconda.org/bioconda/htslib/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/htslib`](https://github.com//bioconda/bioconda-recipes/tree/bump/htslib/recipes/htslib) (click to view/edit other files)
Summary | C library for high-throughput sequencing data formats.
Home | [https://github.com/samtools/htslib](https://github.com/samtools/htslib)
Releases |[https://github.com/samtools/htslib/releases](https://github.com/samtools/htslib/releases)
Author | `@samtools`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Review by jmarshall — CHANGES_REQUESTED** [review]
This should wait until it can be built against a currently pinned conda-forge version of libdeflate.

**Comment by jmarshall** [comment]
Please do not merge this without agreement from @dpryan79 and those working on the **bulk** branch to update htslib-related pinnings.

See also previous discussion on #36526.

**Comment by jmarshall** [comment]
Oh, I remember now: in fact, [htslib-1.16 **has** been packaged](https://anaconda.org/bioconda/htslib/files) from the **bulk** branch already. So updating it on **master** is mostly currently unnecessary, so this PR is superfluous anyway.

**Comment by dpryan79** [comment]
The migration should now been done and I've updated both master and bioconda-commons so the new htslib pinning should be in effect :)

**Pull request closed without merging**
