### PR TITLE
Tango

### PR DESCRIPTION
**Pull request by johnne**
:information_source:
If this is your first pull request to Bioconda please ping `@bioconda/core` so it can be reviewed and to request being added as a member of the Bioconda team. Members of the Bioconda team are able to merge their own pull requests once tests and linting have passed.

----------------

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

Bug fix in tango version 0.5.2. Build number changed to 1.

### CODE REVIEW

**Comment by dpryan79** [comment]
Is there a reason the build number needs to get bumped? It doesn't really seem to change the resulting packge.

**Comment by johnne** [comment]
@dpryan79, I updated the 0.5.2 release on Github to include a bugfix so I bumped the build number,

**Comment by dpryan79** [comment]
Ah you retagged the release, that'll do it. Shall I merge this and add you to bioconda?

**Comment by johnne** [comment]
Hmm, I can't seem to update the github release to include the changes.

**Comment by dpryan79** [comment]
Just tag a new release then.

**Pull request merged**
