### PR TITLE
Add kraken2

### PR DESCRIPTION
**Pull request by dfornika**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by tseemann** [comment]
```
Extracting download
source tree in: /Users/distiller/project/miniconda/conda-bld/kraken2_1534554015114/work
Traceback (most recent call last):
  File "/Users/distiller/project/miniconda/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/Users/distiller/project/miniconda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 424, in main
    execute(sys.argv[1:])
  File "/Users/distiller/project/miniconda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 415, in execute
    verify=args.verify)
  File "/Users/distiller/project/miniconda/lib/python3.6/site-packages/conda_build/api.py", line 200, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/Users/distiller/project/miniconda/lib/python3.6/site-packages/conda_build/build.py", line 2206, in build_tree
    notest=notest,
  File "/Users/distiller/project/miniconda/lib/python3.6/site-packages/conda_build/build.py", line 1446, in build
    utils.check_call_env(cmd, env=env, cwd=src_dir, stats=build_stats)
  File "/Users/distiller/project/miniconda/lib/python3.6/site-packages/conda_build/utils.py", line 310, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "/Users/distiller/project/miniconda/lib/python3.6/site-packages/conda_build/utils.py", line 290, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-e', '/Users/distiller/project/miniconda/conda-bld/kraken2_1534554015114/work/conda_build.sh']' returned non-zero exit status 2.
```

**Comment by dfornika** [comment]
It seems like macOS `gcc` doesn't support `-fopenmp`. Does anyone know a work-around?

**Comment by tseemann** [comment]
@dfornika that's correct `clang` does not support OpenMP, but `gcc` on MacOS will support it. 

@bgruening is there a way to build MacOS binaries using `gcc` in Conda ?

**Comment by yesimon** [comment]
Try using `gcc` in the build deps and `libgcc` in the run requirements just like in the original kraken recipe. You can suffix with `[osx]` as well.

**Comment by dfornika** [comment]
I don't understand how to use gcc on macOS under the new Conda build v3 syntax:

https://bioconda.github.io/cb3.html#compiler-tools

**Comment by yesimon** [comment]
I advise not using the `{{ compiler('cxx') }}` directive because that templates out to `clang` on osx. Instead just put `gcc`. You might not need `libgcc` in the run requirements anymore.

**Comment by dfornika** [comment]
Doesn't that fail the linter?

**Comment by dfornika** [comment]
The build log says:

```
conda.exceptions.ResolvePackageNotFound: 
  - gcc_osx-64
```

Is it not able to use this package?: https://anaconda.org/anaconda/gcc

**Comment by dfornika** [comment]
I'm not sure how to solve this. We could skip the macOS build for now?

**Comment by apcamargo** [comment]
This worked for me in the [IQ-TREE recipe](https://github.com/bioconda/bioconda-recipes/pull/10583)

**Comment by yesimon** [comment]
Give it a shot, make sure to add `clangdev`, `openmp`, and `libcxx`.

**Comment by dfornika** [comment]
Do I need a build requirement `- {{ compiler('cxx') }}`?

**Comment by dfornika** [comment]
I'm still getting `clang: error: unsupported option '-fopenmp'`

**Comment by dfornika** [comment]
I'd like to skip the macos build, since the Kraken2 docs state that macOS is not supported (see 'MacOS NOTE'): https://github.com/DerrickWood/kraken2/blob/master/docs/MANUAL.markdown

**Comment by druvus** [comment]
I support to skip osx for now.

**Pull request merged**
