### PR TITLE
GimmeMotifs 0.11.0b0

### PR DESCRIPTION
**Pull request by simonvh**
* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [X] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by simonvh** [comment]
@bioconda/core  I'm not sure what to do about this travis issue. The build runs fine locally with `simulate-travis.py --docker`. Any ideas?

See failed build [here](https://travis-ci.org/bioconda/bioconda-recipes/jobs/251165580). This is the last part of the output:

```
13:58:55 BIOCONDA INFO TEST START via mulled-build recipes/gimmemotifs, CONDA_ALLOW_SOFTLINKS=false;CONDA_BOOST=1.61;CONDA_GMP=5.1;CONDA_GSL=1.16;CONDA_HDF5=1.8.17;CONDA_HTSLIB=1.5;CONDA_NCURSES=5.9;CONDA_NPY=112;CONDA_PERL=5.22.0;CONDA_PY=27;CONDA_R=3.3.2;CONDA_ROOT=/anaconda;LANG=en_US.UTF-8;LC_ALL=en_US.UTF-8;LC_CTYPE=en_US.UTF-8;MACOSX_DEPLOYMENT_TARGET=10.9;PATH=/anaconda/bin:/home/travis/bin:/home/travis/.local/bin:/home/travis/.rvm/gems/ruby-2.4.0/bin:/home/travis/.rvm/gems/ruby-2.4.0@global/bin:/home/travis/.rvm/rubies/ruby-2.4.0/bin:/home/travis/.pyenv/shims:/home/travis/.phpenv/shims:/home/travis/gopath/bin:/home/travis/.gimme/versions/go1.7.4.linux.amd64/bin:/home/travis/.local/bin:/home/travis/.nvm/versions/node/v7.4.0/bin:/opt/pyenv/bin:/opt/python/2.7.13/bin:/opt/python/3.6.0/bin:/opt/python/3.3.6/bin:/opt/python/3.4.5/bin:/opt/python/3.5.2/bin:/opt/python/pypy2-5.6.0/bin:/usr/local/phantomjs/bin:/usr/local/phantomjs:/home/travis/perl5/perlbrew/bin:/home/travis/.kiex/elixirs/elixir-1.0.4/bin:/home/travis/.kiex/bin:/usr/local/clang-3.5.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/travis/.phpenv/bin:/opt/ghc/bin:/home/travis/.rvm/bin

updating index in: /anaconda/conda-bld/linux-64

No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.

Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

The build has been terminated
```

**Comment by tomkinsc** [comment]
It looks like some of the connections timed out. I restarted the build to see if it was a transient issue.

**Comment by simonvh** [comment]
It seems to consistently time out... :(  (in addition there's still an issue on osx, but that is unrelated).

**Comment by simonvh** [comment]
I checked, and on my local system it takes ~11 minutes, which is longer than the 10 minute time-out reported here. Any way to increase this? Or to have some output during the build?

**Comment by johanneskoester** [comment]
Bioconda-utils already prints a dot every minute. However, this could be slowed down due to swapping...

**Comment by simonvh** [comment]
I'm trying to get the build time down, to see if that helps. What are the options otherwise?

**Comment by simonvh** [comment]
So, I didn't look that carefully. It's the mulled test that causes the problem. The installation of this package does require quite a lot of other packages and apparently this takes a while (~7 minutes on my local system). @bgruening is there anything that I can do about this?

**Comment by simonvh** [comment]
From the test output on my local machine:

``` 
[Jul 10 16:36:28] SERR File "/usr/local/lib/python2.7/site-packages/pysam/__init__.py", line 5, in <module>
[Jul 10 16:36:28] SERR from pysam.libchtslib import *
[Jul 10 16:36:28] SERR ImportError: libbz2.so.1.0: cannot open shared object file: No such file or directory
```

@chapmanb could this be related to #5049 ? Do you have any tips?

**Comment by chapmanb** [comment]
You need `bzip2` from conda-forge (which uses shared libraries and has `libbz2.so.1.0`) not from the default channel (which uses static libraries, and does not). Maybe something is not right on your local setup with regards to loading conda-forge. Sorry to not have a better clue. Your dependency list on this is pretty large and I've moved to using recent htslib/pysam so am not as sure about older versions.

**Comment by simonvh** [comment]
Thanks for looking at this @chapmanb! Your comment did help me to locate the problem. I had forgotten to update to the latest bioconda-utils version (which is clearly outlined in the documentation...), and therefore the build was indeed using the old channel order. Sorry for overlooking this.

So, `simulate_travis.py` is all green on my local build, however, the TEST takes about 10-13 minutes. Apparently, this is too long for travis...

**Comment by druvus** [comment]
@simonvh I added gimmemotifs 0.11.1 in PR #6394 so I will close thisPR. Could as the gimmemotifs author please take a look at the newly added version to make sure it works as expected.

**Pull request closed without merging**
