### PR TITLE
change shebang

### PR DESCRIPTION
**Pull request by bgruening**
* [x] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by yesimon** [comment]
Is this a normal practice where we replace shebang lines even when it works fine when `install.pl` is run and the conda bin path is in `$PATH`? Changing the shebang lines should not be necessary.

**Comment by bgruening** [comment]
@yesimon how does it work if `/usr/bin/perl` does not exist?

**Comment by yesimon** [comment]
@bgruening Ok, it looks like some other packages do change the shebang, but it seems like patches are preferred to sed to be cautious. Otherwise, you can also send up a PR to the KronaTools repo which is active.

**Comment by bgruening** [comment]
@yesimon sure! This was a quick and dirty hack and it did not even work ;)
I need more time to work on this :(

**Comment by odoublewen** [comment]
I think the quick and dirty hack failed b/c Krona has a space after the shebang, so your regex misses.

Anyway, I made a PR on the Krona repo.
https://github.com/marbl/Krona/pull/13

**Comment by bgruening** [comment]
@odoublewen you rock! Thanks! I haven't looked at the error yet.

**Comment by jerowe** [comment]
I think the proper way to do this is to use Module::Build. That way the perl scripts point to the perl they were installed with.

https://gist.github.com/jerowe/c08dd31e83380b7dc14621139979c11a - Is a quick and dirty example, but I want to make it more robust.

This will more fix things like distributions (PFAM, trinotate, miravelvet-sl) having a mix of perl shebang lines. Sometimes they're '#!/usr/bin/perl', which is very, very wrong, sometimes they're '#!/usr/bin/env perl', which is better but still not perfect. I saw '#/usr/bin/perl' yesterday, and that just made me mad. ;-)

In general I'm also moving towards a direction where I go through each package, see if it has perl distros, and install the *pm-s to the perl lib folder, using Module::Build. 

I feel like this makes things much more user friendly. Conda is already built for isolated environments, so we don't need to worry about cluttering up spaces. A fully bundled pfam/trinotate/metavelvet/etc should be sitting off in its own corner with its own perl and @INC. Part of the point of conda installs is that we shouldn't have a long list of instructions. It shouldn't be 'install this, change your perl @INC to this, make sure your perls are pointing in the right place and/or that your modules are loaded in a particular order'. 

I think Module::Build has it right. On systems where you might have many perls installed you want to make sure your script is calling to its own perl and @INC.

Think of all the tickets it will save admins and rejoice!

**Pull request closed without merging**
