### PR TITLE
add genomicassertions

### PR DESCRIPTION
**Pull request by dakl**
* [X] I have read the guidelines above.
* [X] This PR adds a new recipe. 
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

I wrote a package to make assertions in VCF and BAM files which is useful for integration tests of workflows. I'm sure it could be useful to a larger audience. 

https://github.com/dakl/genomicassertions

@bioconda/core, opinions?

### CODE REVIEW

**Comment by dakl** [comment]
Bump

**Comment by croth1** [comment]
@dakl, you are mixing tabs and spaces for indentation in the setup.py file. Python forces you to be consistent - either choose tabs or spaces.  Usually python code is indented by 4 spaces per level.

You can also check travis' report:

```
+ /anaconda/envs/_build/bin/python setup.py install
   File "setup.py", line 16
     lines = (line.strip() for line in handle
                                            ^
 TabError: inconsistent use of tabs and spaces in indentation
```

**Comment by dakl** [comment]
Argh - I'm having these issues where the whitespace is perfectly correct, and then Sourcetree mangles it when I commit. Usually it doesn't actually cause a problem which is a bit strange, but I'm guessing that different versions of python have a different strategy on enforcing consistent whitespaceing since the installation worked on some versions.

Anyway, I've updated now and I guess we'll see if travis is happier this time. That said, some builds errored, ie crashed before `script` the previous time, unrelated the the actual module being installed.

**Comment by bgruening** [comment]
LGTM! Thanks @dakl and @croth1!

**Pull request merged**
