### PR TITLE
Readseq

### PR DESCRIPTION
**Pull request by ValentinMarcon**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by druvus** [comment]
Please take a look at the[ Bioconda guidelines for java software](https://bioconda.github.io/guidelines.html#java). It is recommended to use a wrapper to call the jar file.

**Comment by ValentinMarcon** [comment]
I saw that, but I don't really know how to make the Wrapper (Even with the example). 
I'am not very familiar with jar file, and no more of this Readseq. 
The tool is no longer in development so I can not have help from developers.
([http://iubio.bio.indiana.edu/soft/molbio/readseq/java/](http://iubio.bio.indiana.edu/soft/molbio/readseq/java/))

**Comment by ValentinMarcon** [comment]
So after taking the  time to take a look at some jar wrappers, I saw that it was pretty easy to reproduce for any tool. 
I used the shell wrapper created for the [snpEff package](https://github.com/bioconda/bioconda-recipes/blob/ae06cb3132243975abc1929057b477726d240638/recipes/snpeff/snpeff.sh). 
Thank you for your advise.

**Comment by ValentinMarcon** [comment]
Travis MacOS builds had problems so the job will never go the queue. Now they look stabilized. I close an restart.

**Pull request closed without merging**
