### PR TITLE
r-nanopore package for analysis of nanopore data

### PR DESCRIPTION
**Pull request by sagrudd**
Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it. Note that if you are not already a member of the bioconda project (meaning that you can't add this label), please ping `@bioconda/core` so that your PR can be reviewed and merged (please note if you'd like to be added to the bioconda project). Please see https://github.com/bioconda/bioconda-recipes/issues/15332 for more details.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by sagrudd** [comment]
This is getting blocked due to the r-emojifont dependency - at the beginning I tried to include the dependency as two concurrent packages - this worked as test build locally but failed tests here - I have moved r-emojifont to conda-forge and the r-nanopore build seems happy locally ...

**Comment by sagrudd** [comment]
Hi @bioconda/core folks - can I kindly ask for a review for this hopeful bioconda submission? Thanks!

**Comment by dpryan79** [comment]
Actually, are you considering submitting this to either CRAN or bioconductor?

**Comment by sagrudd** [comment]
yes, I have submitted this package to CRAN - it's in review there at the moment - I appreciate that this could have made life a little easier if it was managed first!

**Comment by dpryan79** [comment]
Are you going to keep the version number the same once it's on CRAN? I'm not familiar with CRAN, so I'm concerned that they may force versioning to start at 0.1.0 or something like that, which would cause problems given that this has a much later version. Given that, I wonder if it's better to hold-off until it's out of review there.

**Comment by sagrudd** [comment]
I would prefer to get this into bioconda as soon as possible - bioconda supports a more agile and continuous development cycle than CRAN. All of our workflows are (bio)conda based - would be very grateful if we can release here first

**Comment by dpryan79** [comment]
Fair enough, shall I add you to bioconda then? You can merge this once the CI testing is done then.

**Comment by sagrudd** [comment]
Yes - please add me to bioconda, I would be delighted to be a member! Thanks for the assistance and greetings from Saxony-Anhalt

**Comment by dpryan79** [comment]
Will do and greetings from sunny Freiburg.

**Pull request merged**
