### PR TITLE
Update deeplc to 0.1.29

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`deeplc`](https://bioconda.github.io/recipes/deeplc/README.html): **0.1.16** &rarr; **0.1.29**

[install with bioconda](http://bioconda.github.io/recipes/deeplc/README.html) [Conda](https://anaconda.org/bioconda/deeplc/files)

Info | Link
-----|-----
Recipe | [`recipes/deeplc`](https://github.com//bioconda/bioconda-recipes/tree/bump/deeplc/recipes/deeplc) (click to view/edit other files)
Releases |[https://pypi.org/pypi/deeplc/json](https://pypi.org/pypi/deeplc/json)
Recipe Maintainer(s) | @compomics

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by dpryan79** [comment]
Blocked by https://github.com/conda-forge/tensorflow-feedstock/pull/104

**Comment by dpryan79** [comment]
Needs https://github.com/conda-forge/keras-preprocessing-feedstock/pull/12

**Comment by RalfG** [comment]
@BiocondaBot recheck

**Comment by RalfG** [comment]
@dpryan79, not sure if I called biocondabot correctly... As conda-forge/keras-preprocessing-feedstock#12 has been merged, can the checks be run again? Thanks!

**Comment by RobbinBouwmeester** [comment]
> 
> 
> @dpryan79, not sure if I called biocondabot correctly... As [conda-forge/keras-preprocessing-feedstock#12](https://github.com/conda-forge/keras-preprocessing-feedstock/pull/12) has been merged, can the checks be run again? Thanks!

@bgruening, could you otherwise help us?

**Comment by dpryan79** [comment]
I'll retrigger the CI

**Comment by dpryan79** [comment]
Looks like there are a few missing dependencies (or maybe a dependency version). Go ahead and ping me here or on gitter if the CI doesn't run when you update the PR. For some reason that's been super glitchy for people this week.

**Comment by RalfG** [comment]
Can be closed in favor of #26906

**Pull request closed without merging**
