### PR TITLE
Update ppanggolin to 1.1.131

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`ppanggolin`](https://bioconda.github.io/recipes/ppanggolin/README.html): **1.1.96** &rarr; **1.1.131**

[install with bioconda](http://bioconda.github.io/recipes/ppanggolin/README.html) [Conda](https://anaconda.org/bioconda/ppanggolin/files)

Info | Link
-----|-----
Recipe | [`recipes/ppanggolin`](https://github.com//bioconda/bioconda-recipes/tree/bump/ppanggolin/recipes/ppanggolin) (click to view/edit other files)
Releases |[https://github.com/labgem/PPanGGOLiN/tags](https://github.com/labgem/PPanGGOLiN/tags)
Recipe Maintainer(s) | @axbazin
Author | `@labgem`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by axbazin** [comment]
#26785 updates the requirements along with the version update.

**Comment by druvus** [comment]
@bioconda-bot please fetch artifacts

**Comment by axbazin** [comment]
@BiocondaBot please add label

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Pull request merged**
