### PR TITLE
Update quatradis 0.4.5

### PR DESCRIPTION
**Pull request by maplesond**
Attempting to fix python depenency issue by installing via pip

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by maplesond** [comment]
Hi @bioconda/core, I'm struggling to get the dependencies to install correctly for this software.  The dependencies are simple enough to install via other systems, docker, etc, but I can't figure out how to do it via conda.  I need the following python libraries installed (ideally with fairly recent versions):

**Comment by dpryan79** [comment]
Regarding getting old versions, if there's no minimal version installed the conda solver is free to do what it wants. It currently doesn't try to use the most recent version of dependencies (though that will optionally change in the new conda release).

**Comment by maplesond** [comment]
Hi @dpryan79, thanks for the update.  Just to expand on the issue I'm seeing, the bioconda test seems to pass, although when I try to run "tradis --help" after a conda install I get an error saying that some to the effect that a specific file in pysam is not available.  This is why previously (in a separate PR) I tried to force the version >0.18.0 but it didn't seem to make a difference.

**Comment by marcelm** [comment]
@maplesond, again, as [I pointed out before](https://github.com/bioconda/bioconda-recipes/pull/33225#issuecomment-1048192371), you should avoid opening multiple PRs that do very similar things or, if for whatever reason you need to open multiple PRs touching the same recipe, you should cross-reference the respective other PR so people don’t do unnecessary work. See #33385, which is still open.

Also, the Bioconda bot has just created #33531.

**Pull request closed without merging**
