### PR TITLE
add solexaqa

### PR DESCRIPTION
**Pull request by sschmeier**
SolexaQA++ recipe. NGS  read assessment and dynamic trimming.

I encounter some failed test ("cannot find section .dynamic"), however program installs. Any help appreciated. Thanks a lot.

### CODE REVIEW

**Comment by johanneskoester** [comment]
Can you copy the binaries explicitly?

**Comment by sschmeier** [comment]
No quite sure what you mean exactly. I changed the command in the build.sh from "mv Linux_x64/* $PREFIX/bin"  to "mv Linux_x64/SolexaQA++ $PREFIX/bin", nothing changes, same error:

"""
++ uname
+ '[' Linux == Darwin ']'
+ echo 'Installing SolexaQA++ for UNIX/Linux.'
+ mkdir -p /home/seb/miniconda2/envs/_build/bin
+ mv Linux_x64/SolexaQA++ /home/seb/miniconda2/envs/_build/bin
cannot find section .dynamic
+ SolexaQA++

Usage: SolexaQA++ <command> [options]

Command: analysis       quality analysis and graphs generation
         dynamictrim    trim reads using a chosen threshold
         lengthsort     sort reads by a chosen length

TESTS FAILED: solexaqa-3.1.4-0
"""


The stdout gives some permission problems:
"""
...
Package: solexaqa-3.1.4-0
source tree in: /home/seb/miniconda2/conda-bld/work
number of files: 1
Fixing permissions
patchelf: file: /home/seb/miniconda2/envs/_build/bin/SolexaQA++
    setting rpath to: $ORIGIN/../lib
Fixing permissions
...


Sorry for the inconvenience, still a bit new to the conda thing.
Thanks, Seb

**Comment by johanneskoester** [comment]
Yes, that's what I meant. Better to explicitly copy to bin. We don't want it to be crowded by accidentally copied files. Regarding your test case, can it be the the command displays a help message and returns with exit code != 0? In that case, the usual recipe is to grep for some unambiguous text in the help message to check if it works properly.

**Comment by sschmeier** [comment]
Runs now locally without error. However still does not pass the travis build.

**Comment by johanneskoester** [comment]
You can omit the piping to dev null and see what it the output of that
command.

**Comment by sschmeier** [comment]
$ SolexaQA++ 2>&1 | grep Released
Released under GNU General Public License version 3

Here the builds stderr without piping to /dev/null:
++ uname
+ '[' Linux == Darwin ']'
+ echo 'Installing SolexaQA++ for UNIX/Linux.'
+ mkdir -p /home/seb/miniconda2/envs/_build/bin
+ mv Linux_x64/SolexaQA++ /home/seb/miniconda2/envs/_build/bin
cannot find section .dynamic
+ SolexaQA++
+ grep Released

**Comment by johanneskoester** [comment]
What do you see when removing the grep Released?

**Comment by sschmeier** [comment]
Then I am getting the help message: Half of it is stdout the other half stderr, see below

---------
[seb@IT060309]:apps$ Linux_x64/SolexaQA++ 2>&1

SolexaQA++ v3.1.4
Released under GNU General Public License version 3
C++ version developed by Mauro Truglio (M.Truglio@massey.ac.nz)

Usage: Linux_x64/SolexaQA++ <command> [options]

Command: analysis       quality analysis and graphs generation
         dynamictrim    trim reads using a chosen threshold
         lengthsort     sort reads by a chosen length

[seb@IT060309]:apps$ Linux_x64/SolexaQA++

SolexaQA++ v3.1.4
Released under GNU General Public License version 3
C++ version developed by Mauro Truglio (M.Truglio@massey.ac.nz)

Usage: Linux_x64/SolexaQA++ <command> [options]

Command: analysis       quality analysis and graphs generation
         dynamictrim    trim reads using a chosen threshold
         lengthsort     sort reads by a chosen length

[seb@IT060309]:apps$ Linux_x64/SolexaQA++ > blah

Usage: Linux_x64/SolexaQA++ <command> [options]

Command: analysis       quality analysis and graphs generation
         dynamictrim    trim reads using a chosen threshold
         lengthsort     sort reads by a chosen length

[seb@IT060309]:apps$ Linux_x64/SolexaQA++ 2> blah

SolexaQA++ v3.1.4
Released under GNU General Public License version 3
C++ version developed by Mauro Truglio (M.Truglio@massey.ac.nz)
[seb@IT060309]:apps$

----------

So the first part of the message is stdout:
"""

SolexaQA++ v3.1.4
Released under GNU General Public License version 3
C++ version developed by Mauro Truglio (M.Truglio@massey.ac.nz)
"""

the second part to stderr:
"""

Usage: Linux_x64/SolexaQA++ <command> [options]

Command: analysis       quality analysis and graphs generation
         dynamictrim    trim reads using a chosen threshold
         lengthsort     sort reads by a chosen length

"""

**Comment by johanneskoester** [comment]
Ok, but how does that output look on travis?

**Comment by johanneskoester** [comment]
We have migrated our build system from Travis CI to Circle CI. If you would like to continue working on this PR, please update with latest upstream master and reopen this PR.

**Pull request closed without merging**
