### PR TITLE
add peptide shaker

### PR DESCRIPTION
**Pull request by bgruening**

### CODE REVIEW

**Comment by bgruening** [comment]
ping @hbarsnes, @mvaudel
xref: https://github.com/galaxyproteomics/tools-galaxyp/issues/57 and https://github.com/galaxyproject/tools-iuc/issues/700

**Comment by mvaudel** [comment]
ACK!
How can we help you?

**Comment by bgruening** [comment]
It's done! :)
PeptideShaker is available even for OS X. With searchgui I had some problems with `omssacl`: https://travis-ci.org/bioconda/bioconda-recipes/jobs/120687709#L1145

**Comment by mvaudel** [comment]
Fantastic!

Yes OMSSA and its dependencies are not easy to integrate and actually not maintained. It is not really used anymore so maybe we could skip it?

**Comment by bgruening** [comment]
@mvaudel how to do so. I you look at travis this is kind of a strange error. I could remove this binary? But than user-experience is effected as this is not working but it is with other installations.

**Comment by mvaudel** [comment]
Yes, temporarily you would need to disable it, ie force `-omssa` to _0_, and inform the user why in the documentation. Even if you take the extra effort of making it work, it will crash on most modern datasets and leave you with a cryptic stack trace. 

On the long term, say by the end of the year, we plan on removing the distribution and OMSSA support altogether because it has become impossible to maintain and when users report errors the only thing we can do is recommend to disable it...

Just let me talk to Harald about it and we will come back to you :)

**Comment by bgruening** [comment]
No problem, for now both packages are working under Linux :)

**Pull request merged**
