### PR TITLE
Update CESM recipe with MPI support

### PR DESCRIPTION
**Pull request by annefou**
Describe your pull request here

- add configuration files in the recipe as it is easier for users for running it
- add support for MPI as it significantly improve performance
- make it possible to run fully coupled CESM (with ocean component)
- Add addition tests to check compilation

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by bgruening** [comment]
@BiocondaBot please fetch artifacts

**Comment by annefou** [comment]
@BiocondaBot please fetch artifacts

**Comment by j34ni** [comment]
@annefou: the new extended image (at least python 3.8) seems to work with singularity
This is what I did:
```
export USER=ubuntu
export NETCDF_DIR=$(nc-config --prefix)
export CIME_MODEL=cesm
export CESM_DATA_ROOT=/usr/local/
export CESM_WORK_ROOT=/usr/local

export FC=x86_64-conda-linux-gnu-gfortran
export CC=x86_64-conda-linux-gnu-gcc
export AR=x86_64-conda-linux-gnu-ar

create_newcase --case $CESM_WORK_ROOT/archive/cases/singularity-F2000climo_f19_f19_mg17 --compset F2000climo --res f19_f19_mg17 --machine espresso --run-unsupported

cd $CESM_WORK_ROOT/archive/cases//singularity-F2000climo_f19_f19_mg17
NUMNODES=-1
./xmlchange --file env_mach_pes.xml --id NTASKS --val ${NUMNODES}
./xmlchange --file env_mach_pes.xml --id NTASKS_ESP --val 1
./xmlchange --file env_mach_pes.xml --id ROOTPE --val 0
./xmlchange STOP_N=1
./xmlchange STOP_OPTION=nmonths
./case.setup 
./case.build 
./case.submit
```

**Comment by annefou** [comment]
please review & merge

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
@bioconda-bot please merge

**Comment by bgruening** [comment]
@bioconda-bot please merge

**Pull request merged**
