### PR TITLE
Add braid mrf

### PR DESCRIPTION
**Pull request by wasineer-dev**
Dear @bioconda/cores,

@BiocondaBot please add add_braid_mrf

Thank you. 

wasinee

### CODE REVIEW

**Comment by alienzj** [comment]
@BiocondaBot please merge

**Comment by wasineer-dev** [comment]
@alienzj Hello,

Thank you for approving the project. However, the merge failed and I do not know exactly where the error is.
Can you provide me with the merge errors?

wasineer-dev

**Comment by alienzj** [comment]
@wasineer-dev Hello,
I also have no idea for that. Let's try to update brach and rebuild it.

**Comment by alienzj** [comment]
@BiocondaBot please fetch artifacts

**Comment by alienzj** [comment]
@BiocondaBot please merge

**Pull request merged**
