### PR TITLE
Update semibin to 2.1.0

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`semibin`](https://bioconda.github.io/recipes/semibin/README.html): **2.0.2** &rarr; **2.1.0**

[install with bioconda](http://bioconda.github.io/recipes/semibin/README.html) [Conda](https://anaconda.org/bioconda/semibin/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/semibin`](https://github.com//bioconda/bioconda-recipes/tree/bump/semibin/recipes/semibin) (click to view/edit other files)
Summary | Metagenomic binning with semi-supervised siamese neural networks
Home | [https://github.com/BigDataBiology/SemiBin](https://github.com/BigDataBiology/SemiBin)
Releases |[https://pypi.org/pypi/SemiBin/json](https://pypi.org/pypi/SemiBin/json)
Recipe Maintainer(s) | @luispedro, @psj1997

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by luispedro** [comment]
Please do not merge _as is_

**Comment by luispedro** [comment]
@BiocondaBot please fetch artifacts

**Comment by luispedro** [comment]
@BiocondaBot please add label

**Comment by luispedro** [comment]
I tested artifacts locally and build worked well

**Review by thanhleviet — APPROVED** [review]

**Pull request merged**
