### PR TITLE
Add initial recipe for r-sew-1.0.0

### PR DESCRIPTION
**Pull request by rwdavies**
:information_source:
If this is your first pull request to Bioconda please ping `@bioconda/core` so it can be reviewed and to request being added as a member of the Bioconda team. Members of the Bioconda team are able to merge their own pull requests once tests and linting have passed.

----------------

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by rwdavies** [comment]
I think this is going to pass (but hasn't yet - the linting recipe is still queued). 

For this package, I basically copied the meta.yaml from r-stitch (https://github.com/bioconda/bioconda-recipes/blob/master/recipes/r-stitch/meta.yaml), and made a series of small adjustments.

Of note, this package is specifically tied to r-stitch 1.5.5, as there is a bug in r-sew that is exposed with later versions of r-stitch. Once this goes through I'll patch the bug the bug in r-sew and push a new version that removes this specific dependency

**Comment by dpryan79** [comment]
This looks ready to merge, shall I do so? Would you like to be added to bioconda?

**Comment by rwdavies** [comment]
That'd be great! Not sure why it's queued. Sure, would be great to be added, thanks

**Comment by dpryan79** [comment]
The bot that updates that isn't running 100% of the time.

**Pull request merged**
