### PR TITLE
pb-falcon=0.3.0

### PR DESCRIPTION
**Pull request by pb-cdunn**
:information_source:
If this is your first pull request to Bioconda please ping `@bioconda/core` so it can be reviewed and to request being added as a member of the Bioconda team. Members of the Bioconda team are able to merge their own pull requests once tests and linting have passed.

----------------

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [ ] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by pb-cdunn** [comment]
@bioconda/core

Can anyone tell me why this failed?
```
TEST START: /opt/conda/conda-bld/linux-64/pb-falcon-0.3.0-py37hc0aa232_1.tar.bz2

Renaming work directory,  /opt/conda/conda-bld/pb-falcon_1556723185530/work  to  /opt/conda/conda-bld/pb-falcon_1556723185530/work_moved_pb-falcon-0.3.0-py37hc0aa232_1_linux-64

Collecting package metadata: ...working... done

Solving environment: ...working... failed

failed to get install actions, retrying.  exception was: Unsatisfiable dependencies for platform linux-64: {'pb-falcon==0.3.0=py37hc0aa232_1'}
```
We're simply trying to switch to python3. We have no added any dependencies.

**Comment by epruesse** [comment]
Not sure that I like the way this recipe puts so many different things into one package.

**Comment by pb-cdunn** [comment]
https://bioconda.github.io/contribute-a-recipe.html#bootstrap-method

`./bootstrap.py /tmp/miniconda` uses python3.6 instead of 3.7. That might be part of the problem.

**Comment by pb-cdunn** [comment]
I restricted python to `>=3`, and now it's even strangers. "lint" passes separately, but it fails as part of bioconda-test:
```
Workflow: bioconda-test
lint - Failed
test-linux - Blocked
test-macos - Blocked
```
...
Ok. I am able to run `bioconda-utils` locally now. (I needed to move `set completion-ignore-case on` from my `~/.bashrc` to `~/.inputrc`.) But with `python>=3` nothing happens, oddly. So I've gone back to `host: - python` and am waiting ... This is what I see locally:
```
TEST START: /scratch/cdunn/miniconda/miniconda/conda-bld/linux-64/pb-falcon-0.3.0-py37hc0aa232_1.tar.bz2
Renaming work directory,  /scratch/cdunn/miniconda/miniconda/conda-bld/pb-falcon_1556810188340/work  to  /scratch/cdunn/miniconda/miniconda/conda-bld/pb-falcon_1556810188340/work_moved_pb-falcon-0.3.0-py37hc0aa232_1_linux-64
Collecting package metadata: ...working... done
Solving environment: ...working... failed
failed to get install actions, retrying.  exception was: Unsatisfiable dependencies for platform linux-64:
{"python[version='>=3.7,<3.8.0a0']", "python[version='>=3.6,<3.7.0a0']"}
WARNING:conda_build.build:failed to get install actions, retrying.  exception was: Unsatisfiable dependencies for platform linux-64:
{"python[version='>=3.7,<3.8.0a0']", "python[version='>=3.6,<3.7.0a0']"}
Tests failed for pb-falcon-0.3.0-py37hc0aa232_1.tar.bz2 - moving package to /scratch/cdunn/miniconda/miniconda/conda-bld/broken
WARNING:conda_build.build:Tests failed for pb-falcon-0.3.0-py37hc0aa232_1.tar.bz2 - moving package to /scratch/cdunn/miniconda/miniconda/conda-bld/broken
TESTS FAILED: pb-falcon-0.3.0-py37hc0aa232_1.tar.bz2


08:20:50 BIOCONDA ERROR BUILD FAILED recipes/pb-falcon
```

**Comment by pb-cdunn** [comment]
Something uses only 3.6, but the dependency-checker does not tell us what. I thought it might be `meson`, but [Meson's feedstock looks fine](https://github.com/conda-forge/meson-feedstock/blob/master/recipe/meta.yaml). Maybe the problem is `bioconda-utils`, which is strictly py3.6, but then why has no-one else encountered this problem?

**Comment by pb-cdunn** [comment]
I tried skipping the build for py37:

    skip: True # [py27 or osx or py37]

But something happens anyway:
```
Compressing to /tmp/tmpucqbi9g_/pb-falcon-0.3.0-py37hc0aa232_1.tar.bz2
TEST START: /scratch/cdunn/miniconda/miniconda/conda-bld/linux-64/pb-falcon-0.3.0-py37hc0aa232_1.tar.bz2
Renaming work directory,  /scratch/cdunn/miniconda/miniconda/conda-bld/pb-falcon_1556811364401/work  to  /scratch/cdunn/miniconda/miniconda/conda-bld/pb-falcon_1556811364401/work_moved_pb-falcon-0.3.0-py37hc0aa232_1_linux-64
Collecting package metadata: ...working... done
Solving environment: ...working... failed
WARNING: symlink_conda() is deprecated.
WARNING: symlink_conda() is deprecated.
WARNING: symlink_conda() is deprecated.
failed to get install actions, retrying.  exception was: Unsatisfiable dependencies for platform linux-64: {'pb-falcon==0.3.0=py37hc0aa232_1'}
WARNING:conda_build.build:failed to get install actions, retrying.  exception was: Unsatisfiable dependencies for platform linux-64: {'pb-falcon==0.3.0=py37hc0aa232_1'}
Tests failed for pb-falcon-0.3.0-py37hc0aa232_1.tar.bz2 - moving package to /scratch/cdunn/miniconda/miniconda/conda-bld/broken
WARNING:conda_build.build:Tests failed for pb-falcon-0.3.0-py37hc0aa232_1.tar.bz2 - moving package to /scratch/cdunn/miniconda/miniconda/conda-bld/broken
TESTS FAILED: pb-falcon-0.3.0-py37hc0aa232_1.tar.bz2
```
So now I am trying to skip py37 is *2* ways at once ...

**Comment by pb-cdunn** [comment]
Again, lint passes, but build-lint fails:
```
15:50:50 BIOCONDA DEBUG Linting: recipes/pb-falcon
Setting build platform. This is only useful when pretending to be on another platform, such as for rendering necessary dependencies on a non-native platform. I trust that you know what you're doing.
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
Adding in variants from internal_defaults
Adding in variants from /home/circleci/project/miniconda/conda_build_config.yaml
Adding in variants from /home/circleci/project/miniconda/lib/python3.6/site-packages/bioconda_utils/bioconda_utils-conda_build_config.yaml
15:50:58 BIOCONDA DEBUG Linting: recipes/smeg
	recipe	check	info	already_in_bioconda	end_line	fix	output	start_line
0	recipes/smeg	already_in_bioconda	{'already_in_bioconda': True, 'fix': 'bump version or build number', 'start_line': 6, 'end_line': 7, 'output': 'smeg'}	True	7	bump version or build number	smeg	6
Exited with code 1
```

**Comment by dpryan79** [comment]
Merge in master

**Comment by pb-cdunn** [comment]
@dpryan79 , what do you mean by "merge in master"?

**Comment by dpryan79** [comment]
`git pull upstream master`, which might fail since you're using the master branch on your fork. In the future try to use a branch of either this repository or your fork, it will make life a bit easier.

**Comment by pb-cdunn** [comment]
I don't understand what's going on here. This was merged, using py3.6, and so was #15043, which added py3.7. But I am not able to install this on Linux in a py3.6 or 3.7 environment. When I run `conda install pb-falcon`, conda always decides to *downgrade* to py2.6. Can anyone here confirm?

I've also tried

    conda create -n pb37t python=3.7 pb-falcon=0.3.0

No joy. And I do not see `pbfalcon-0.3.0` listed at https://anaconda.org/search?q=pb-falcon , only the older `0.2.7`. But this was **MERGED**!

How do I debug this? Is there a way to list the tree of dependencies as Conda sees it, or to learn the conflicts?

**Comment by dpryan79** [comment]
See https://github.com/bioconda/bioconda-recipes/pull/15067

**Pull request merged**
