### PR TITLE
rebuild stream_atac 0.3.5

### PR DESCRIPTION
**Pull request by huidongchen**
Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it. Note that if you are not already a member of the bioconda project (meaning that you can't add this label), please ping `@bioconda/core` so that your PR can be reviewed and merged (please note if you'd like to be added to the bioconda project). Please see https://github.com/bioconda/bioconda-recipes/issues/15332 for more details.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by huidongchen** [comment]
@dpryan79 hi, Devon I'm not sure why bioconda test blocked mac os test. Could you help take a look? Thanks!

**Comment by dpryan79** [comment]
There was a long backlog of jobs yesterday, so they were blocking things. That appears to have been cleared for now (until I clog it again by merging 20 PRs).

**Comment by huidongchen** [comment]
For macos test, its using libgfortran v4 instead of libgfortran v3 as on Linux. But this is in conflict with rpy2 v2. So i had to specify the libgfortran version in ‘build.sh’ . I saw you commented it. Is there any other way to specify the version of libgfortran so that it will be compatible with rpy2 in MacOS

**Comment by dpryan79** [comment]
If you can use either rpy2 >3 or 2.8.* then it won't need a special gfortran. As is you're vendoring libgfortran, which will likely cause a conflict at some point in time.

**Comment by huidongchen** [comment]
Thanks for the tips. I will try to set rpy2 to 2.8.* in the next update.

**Pull request merged**
