### PR TITLE
Update dnaio to 0.8.0

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`dnaio`](https://bioconda.github.io/recipes/dnaio/README.html): **0.7.1** &rarr; **0.8.0**

[install with bioconda](http://bioconda.github.io/recipes/dnaio/README.html) [Conda](https://anaconda.org/bioconda/dnaio/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/dnaio`](https://github.com//bioconda/bioconda-recipes/tree/bump/dnaio/recipes/dnaio) (click to view/edit other files)
Summary | Read and write FASTA and FASTQ files efficiently
Home | [https://github.com/marcelm/dnaio/](https://github.com/marcelm/dnaio/)
Releases |[https://pypi.org/pypi/dnaio/json](https://pypi.org/pypi/dnaio/json)
Recipe Maintainer(s) | @marcelm

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by marcelm** [comment]
What’s going on now?

**Comment by marcelm** [comment]
@shenwei365 Since I don’t know why you closed this, I’m re-opening.

**Review by marcelm — APPROVED** [review]

**Comment by shenwei356** [comment]
I forgot to update some important help messages in the command-line interface. Please wait a few minutes.

**Comment by marcelm** [comment]
Are you referring to a different package? I'm one of the dnaio authors and we don't have a command line interface.

**Comment by shenwei356** [comment]
@marcelm I'm very sorry, I closed the wrong PR. :(

**Comment by marcelm** [comment]
No problem!

**Comment by marcelm** [comment]
@BiocondaBot please merge

**Pull request merged**
