### PR TITLE
Rebuild bioconda-utils

### PR DESCRIPTION
**Pull request by mbargull**
Rebuild [`bioconda-utils`](https://bioconda.github.io/recipes/bioconda-utils/README.html) to update pinnings

[install with bioconda](http://bioconda.github.io/recipes/bioconda-utils/README.html) [Conda](https://anaconda.org/bioconda/bioconda-utils/files)

Info | Link
-----|-----
Recipe | [`recipes/bioconda-utils`](https://github.com//bioconda/bioconda-recipes/tree/bump/bioconda_utils/recipes/bioconda-utils) (click to view/edit other files)
Releases |[https://github.com/bioconda/bioconda-utils/tags](https://github.com/bioconda/bioconda-utils/tags)
Author | `@bioconda`
***

(Unable to detect reason for pinning rebuild. Predicted hash has changed, however.)

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/updating.html)).

### CODE REVIEW

**Comment by mbargull** [comment]
@BiocondaBot lint

**Comment by mbargull** [comment]
Interesting:
> biocondabot / Linting Recipe(s)
> 
> The recipe build number should be reset to 0
> 
> No previous build of a package of this name and this version exists,
> the build number should therefore be 0.

Doesn't look like a CDN-sync issue:
```sh
|> docker run --rm continuumio/miniconda3 conda search bioconda::bioconda-utils=0.16.7 | tail -n1
bioconda-utils                0.16.7            py_0  bioconda            
```

So, maybe something wrong with the linter or a repodata caching thing with the bot...

**Comment by mbargull** [comment]
Probably bot cache, which looks like is set to 5 minutes:
https://github.com/bioconda/bioconda-utils/blob/v0.16.7/bioconda_utils/utils.py#L1375
https://github.com/bioconda/bioconda-utils/blob/v0.16.7/bioconda_utils/bot/worker.py#L208
https://github.com/bioconda/bioconda-utils/blob/v0.16.7/bioconda_utils/bot/config.py#L82

@BiocondaBot lint

**Comment by mbargull** [comment]
@BiocondaBot lint

**Comment by mbargull** [comment]
yeah, whatever..
@BiocondaBot merge

**Comment by mbargull** [comment]
@BiocondaBot Respect my authoritah!

**Comment by mbargull** [comment]
@dpryan79 pretty please :)

**Comment by dpryan79** [comment]
@bioconda-bot merge

**Comment by dpryan79** [comment]
I am thoroughly amused by your choice of gif :P

**Comment by mbargull** [comment]
Haha, thanks!

**Pull request merged**
