### PR TITLE
Hmmer2

### PR DESCRIPTION
**Pull request by zachcp**
* [X] I have read the guidelines above.
* [X] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [X] This PR does something else (explain below).

This pull request installs hmmer2 by appending a "2" to all executables. This allows the simultaneous installation of hmmer2 and hmmer3.  This change is desirable because the API/ABI of hmmer2/3 is not identical. Currently there is no way to use both HMMER2 and HMMER3 at the same time. The impetus to include this package in this manner is to facilitate the packaging of the Antismash program that utilizes this convention. Because it will not clash with the HMMMER program I believe it will be okay to use in this way but I will file an issue asking for suggestions/criticism.

Thanks,
zach cp

### CODE REVIEW

**Comment by peterjc** [comment]
This looks good in principle - I have a Galaxy tool where I'd explicitly like to use HMMER2 and assume the binary is available as ``hmmsearch2``, so ought to be able to use your BioConda package 👍

**Comment by johanneskoester** [comment]
I must say that I am not entirely convinced. Since conda supports isolated environments, there is not really a point of doing this in order to be able to use both versions. It is also very unusual in the conda ecosystem. E.g. we don't do that for the different python versions and so on.

**Comment by peterjc** [comment]
I'm not sure Python is a good counter example given Python 3 introduced the convention ``python3``, ``pip3`` etc for the default version of Python 3, rather than Python 2.

**Comment by johanneskoester** [comment]
Yes, it did, but not in Conda. This was done to have both versions on systems that don't have a package system that is able to install multiple versions into isolated environments. In conda, this is not needed. And hence, the conda python package also provides python 3 simply as `python`.

**Comment by zachcp** [comment]
my primary use case was to support Antismash which uses both hmmer2 and hmmer (hmmer3) at the same time.  Basically if both binaries are required on the same system they are essentially two different programs. Its a fundamental problem. Maybe a better comparison would be bowtie vs bowtie2.

**Comment by johanneskoester** [comment]
Indeed, that's a different story, sorry I should've read your post more carefully. So, if antismash will depend on both, we indeed would have to do something like this. In that case however, this new package has to be named hmmer2. Otherwise conda will refuse to install both.

**Comment by zachcp** [comment]
thanks for your  time/review @johanneskoester . I changed the name to hmmer2 and will pull if/when the builds pass.

**Pull request merged**
