### PR TITLE
add probamconvert

### PR DESCRIPTION
**Pull request by bgruening**
* [x] I have read the guidelines above.
* [x] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by bgruening** [comment]
Labelling as WIP and waiting for upstream to merge my patches.

**Comment by jj-umn** [comment]
I had to use: pysam ==0.9.0  to satisfy import pysam.ctabixproxies in proBAM.py

**Comment by vladie0** [comment]
I currently use pysam version 0.8.4., the reason being is that later versions cause problems in OSX operating systems. I'm waiting for a fix from pysam themselves. I'll check whether the issues has been resolved

**Comment by vladie0** [comment]
I've updated proBAMconvert which is now compatible with PySAM 0.10.0. Also works for OSX now

**Comment by bgruening** [comment]
Thanks for working on it.

**Pull request merged**
