### PR TITLE
Bioc quick test

### PR DESCRIPTION
**Pull request by dpryan79**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [x] This PR does something else (explain below).

@bgruening As discussed, here's a test of a single package.

### CODE REVIEW

**Comment by dpryan79** [comment]
You can't tell from the commit log, but this just updates bioconductor-roc, config.yml and .circleci/config.yml.

**Comment by bgruening** [comment]
@dpryan79 great. I just added a `noarch: generic` test case. Let's see if this works. 

I think you need to retarget this PR to the bulk branch, isn't it? Maybe I misunderstood my own plan ;)

**Comment by dpryan79** [comment]
Gah, I missed that, I'll redirect.

**Comment by dpryan79** [comment]
Your noarch test case is going to be tough, since it depends on other bioc packages that won't exist.

**Comment by dpryan79** [comment]
I'll copy in biocgenerics instead.

**Comment by dpryan79** [comment]
a4base should be skipped when it's merged into `bulk`.

**Comment by bgruening** [comment]
Upps, you are right biocgenerics is a much better choice. From the logs it looks ok - ready for bulk?

**Comment by dpryan79** [comment]
Yup, merged.

**Comment by dpryan79** [comment]
Fancy that, the skeleton was supposed to do that, but I never actually tested it :)

**Comment by dpryan79** [comment]
And it's online too :)

**Comment by bgruening** [comment]
https://quay.io/repository/biocontainers/bioconductor-biocgenerics?tag=latest&tab=tags

Looks all good. @nturaga will be happy :)

**Comment by bgruening** [comment]
Thanks a bunch @dpryan79!

**Pull request merged**
