### PR TITLE
add metav recipes

### PR DESCRIPTION
**Pull request by ZhijianZhou01**
Describe your pull request here

----

add a new recipe named metav.
metav: rapid detection and classification of viruses in metagenomics sequencing.

### CODE REVIEW

**Comment by ZhijianZhou01** [comment]
@BiocondaBot please add label

**Comment by ZhijianZhou01** [comment]
@bioconda/core please review & merge

**Comment by ZhijianZhou01** [comment]
@mencian Hi, could you help me merged my commit? Thank you very much.

**Review by bgruening — APPROVED** [review]

**Comment by ZhijianZhou01** [comment]
Thanks.

**Pull request merged**
