### PR TITLE
Update medaka - create conda_build_config.yaml

### PR DESCRIPTION
**Pull request by RaverJay**
use htslib 1.11 to resolve a pinning conflict in the recipe for medaka 1.2.1:
https://github.com/bioconda/bioconda-recipes/issues/26307#issuecomment-764661478

### CODE REVIEW

**Comment by jmarshall** [comment]
Nothing has actually been built in the CI checks — I suspect you will have to also bump `build: number` in _meta.yaml_ to make this effective.

**Comment by RaverJay** [comment]
Seems the build died due to connection problems?

```
06:59:32 BIOCONDA INFO (ERR) [Jan 22 06:59:32] SERR CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/conda-forge/linux-64/libiconv-1.16-h516909a_0.tar.bz2>
06:59:32 BIOCONDA INFO (ERR) [Jan 22 06:59:32] SERR Elapsed: -
06:59:32 BIOCONDA INFO (ERR) [Jan 22 06:59:32] SERR
06:59:32 BIOCONDA INFO (ERR) [Jan 22 06:59:32] SERR An HTTP error occurred when trying to retrieve this URL.
06:59:32 BIOCONDA INFO (ERR) [Jan 22 06:59:32] SERR HTTP errors are often intermittent, and a simple retry will get you on your way.
```
etc

@BiocondaBot please rebuild

**Comment by RaverJay** [comment]
@BiocondaBot rebuild

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Pull request merged**
