### PR TITLE
Update ntjoin to 1.0.5

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`ntjoin`](https://bioconda.github.io/recipes/ntjoin/README.html): **1.0.3** &rarr; **1.0.5**

[install with bioconda](http://bioconda.github.io/recipes/ntjoin/README.html) [Conda](https://anaconda.org/bioconda/ntjoin/files)

Info | Link
-----|-----
Recipe | [`recipes/ntjoin`](https://github.com//bioconda/bioconda-recipes/tree/bump/ntjoin/recipes/ntjoin) (click to view/edit other files)
Releases |[https://github.com/bcgsc/ntJoin/releases](https://github.com/bcgsc/ntJoin/releases)
Author | `@bcgsc`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by dpryan79** [comment]
For some reason this is using `-Werror`, which is breaking the build.

**Comment by lcoombe** [comment]
Thanks for the upstream fix, @dpryan79  - Can the recipe be patched here, or would it be better if I made a new release?

**Comment by dpryan79** [comment]
@lcoombe Whichever you prefer. It'd be ideal for us if you tagged a new release, but we can be flexible if you want to accrue more changes before doing so.

**Comment by lcoombe** [comment]
@dpryan79 - I just did a new release, and everything seems to be building fine now!

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Pull request merged**
