### PR TITLE
Fix bioconductor-cytolib by reapplying existing patch

### PR DESCRIPTION
**Pull request by jmarshall**
Commit c7b052d8526dcbea89241ad8f9999fce8920b3bd from bulk PR #27784 removed the _dyextension.patch_ from bioconductor-cytolib (previously added by PR #25292), which has rebroken bioconda's cytolib package on macOS, as noted by @FerranC96 in https://github.com/RGLab/cytolib/issues/44#issuecomment-830034579 and confirmed by me attempting `library(cytolib)` in a fresh conda environment just now.

@dpryan79: Was there a reason for removing applying this patch from _meta.yaml_? If there was a maintenance script involved (I don't know how you do these epic bulk PRs…), could it have inadvertently removed the patch lines from _meta.yaml_?

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by jmarshall** [comment]
I was going to say perhaps there should be a test that checks that the library is loadable. However in fact there already is, and it [failed on macOS in the bulk PR](https://github.com/bioconda/bioconda-recipes/runs/2207759104#step:7:7781), but apparently it was only a warning so did not fail the build:

```
10:03:55 BIOCONDA INFO (ERR) Warning message:
10:03:55 BIOCONDA INFO (ERR) In fun(libname, pkgname) : cytolib library  not found.
10:03:55 BIOCONDA INFO (ERR) + exit 0
```

**Comment by dpryan79** [comment]
@bioconda-bot please merge

Yikes, thanks for the quick fix. This patch must have gotten disabled in the last migration.

**Comment by dpryan79** [comment]
What happened was during the migration all packages requiring a rebuild received a version bump. This would have failed for cytolib, because Bioconductor deletes all but the most recent version's tarball (we originally built 2.2.0 back in November, so 2.2.1 must have come out in the interim). That of course caused build failures, so the recipe was regenerated. This removes the patch from the meta.yaml, since that file is regenerated from scratch. I would have expected the build to then fail, but I guess it didn't, which is...not great. I normally keep track of problematic Bioconductor packages [here](https://github.com/dpryan79/bioconda_bioconductor_interface). I guess I should keep my eye on cytolib, since the next Bioconductor release will be soon.

**Comment by jmarshall** [comment]
Thank for merging; the package is fixed now.

There are circumstances under which _meta.yaml_ is regenerated from scratch…? …ooookaaaay…

Anyway, assuming the next Bioconductor release will come from what is currently their **devel** branch, this problem will take care of itself as cytolib in **devel** no longer uses a shared library, so there is no so/dylib filename to worry about.

**Comment by FerranC96** [comment]
I can also confirm the newest version works flawlessly now.
Thank you for approving the merge and thanks specially to @jmarshall  for implementing the fix!

**Pull request merged**
