### PR TITLE
Update bioconductor-epialleler to 1.8.1

### PR DESCRIPTION
**Pull request by oleksii-nikolaienko**
There was an error in the upstream, which prevented packaging it. Error has now been fixed, therefore patch was deleted and meta.yaml updated to version 1.8.1

### CODE REVIEW

**Comment by oleksii-nikolaienko** [comment]
@BiocondaBot please add label

**Comment by oleksii-nikolaienko** [comment]
Hi @dpryan79, if you got a minute I'd appreciate if you read this message. You posted this issue https://github.com/BBCG/epialleleR/issues/1 a while ago, but I resolved it only now. Compilation failed because `__STDC_FORMAT_MACROS` was not defined (fixed by https://github.com/BBCG/epialleleR/commit/f7f71c2ec60651bdd14f2af2bfb29bf2fae3ae9d). I wonder if it was my fault (although all Bioc checks were always fine) or something important is missing in bioconda build parameters?

**Comment by dpryan79** [comment]
@BiocondaBot please fetch artifacts

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
Thanks @oleksii-nikolaienko!

**Pull request merged**
