### PR TITLE
Update nanovar to 1.2.5

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`nanovar`](https://bioconda.github.io/recipes/nanovar/README.html): **1.2.3** &rarr; **1.2.5**

[install with bioconda](http://bioconda.github.io/recipes/nanovar/README.html) [Conda](https://anaconda.org/bioconda/nanovar/files)

Info | Link
-----|-----
Recipe | [`recipes/nanovar`](https://github.com//bioconda/bioconda-recipes/tree/bump/nanovar/recipes/nanovar) (click to view/edit other files)
Releases |[https://pypi.org/pypi/nanovar/json](https://pypi.org/pypi/nanovar/json)
Recipe Maintainer(s) | @cytham

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by dpryan79** [comment]
@cytham Thanks! I'll make those changes to this PR.

**Comment by dpryan79** [comment]
@cytham Shall I add you to the bioconda project? You can edit and merge PRs then :)

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Comment by cytham** [comment]
> @cytham Shall I add you to the bioconda project? You can edit and merge PRs then :)

Sure, if it's not too troublesome.
Thanks for your help!

**Pull request merged**
