### PR TITLE
Add demuxEM

### PR DESCRIPTION
**Pull request by yihming**
This is a demultiplexing package which works on cell-hashing and nucleus-hashing genomics data. It also serves as the demultiplexing module of Pegasus package.

The recipe has been locally tested using the "Bootstrap" method. And I've moved my forked Bioconda-recipes repo to an organization which I have the full permission, hoping in this way you could directly edit my pull request if needed.

**PS:** I have a general question, not sure if this is the right place to ask. We want to add our scRNA-seq data analysis package `pegasus` to Bioconda. However, it has some dependency packages not posted on conda. Do we have to first add all of them before adding `pegasus`? These dependencies are all `pypi` packages. 

If we have to add them to conda first, then for those not created and hosted by us, do we have to ask the authors to add their packages to conda, or there is a way of doing it ourselves (e.g. we maintain the recipes and reference to the authors)?

I'd really appreciate it if you could give us a hand on this matter. Thank you!

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
@yihming you don't need to change your github account to get help from us. So please do not change that to an organisation if it is not an organization.

If you depend on packages that are not in `conda-forge` __or__ `bioconda` please add them. All non `bio` related dependencies please to conda-forge and than you can add pegasus.

Hope that helps,
Bjoern

**Comment by yihming** [comment]
@bgruening Thank you so much for your immediate response!

I feel like that I need to change my forked repo's organization because in [this pull request](https://github.com/bioconda/bioconda-recipes/pull/25845) the reviewer said that my organization at that time prevented him from editing my pull request directly. So I switch to the current organization in this pull request, which is indeed an organization.

Just to follow up your answer. If we would like to add some packages to `conda` (either `conda-forge` or `bioconda`), but we are not the authors of those packages, do we legally allowed to add them ourselves? Thanks!

**Comment by bgruening** [comment]
> I feel like that I need to change my forked repo's organization because in PR #25845 the reviewer said that my organization at that time prevented him from editing my pull request directly. So I switch to the current organization in this pull request, which is indeed an organization.

You can do this per PR. In every PR you create you can grant those permissions.

> Just to follow up your answer. If we would like to add some packages to conda (either conda-forge or bioconda), but we are not the authors of those packages, would it be appropriate to add them by ourselves? Thanks!

Yes you are :)

**Comment by yihming** [comment]
@BiocondaBot please add label

**Comment by bgruening** [comment]
@bioconda-bot please merge

**Pull request merged**
