### PR TITLE
added perl-bio-eutilities

### PR DESCRIPTION
**Pull request by PatrickRWright**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by jerowe** [comment]
@PatrickRWright , do the versions need to be hard coded?

**Comment by PatrickRWright** [comment]
Hi, since I am new I am also not exactly sure if the answer is "yes", but  for now my plan was to build something that stably runs for a long time even if other dependencies change. What would you suggestion be?

**Comment by jerowe** [comment]
The suggestion is not unless it has to be. ;-) BioPerl can be problematic. Could you try with just hard coding the bioperl version, and leave the others blank?

**Comment by PatrickRWright** [comment]
Ok. I will do that. I will comment out the versions and leave them as comments as a reminder what definately worked. I hope such comments are fine. Thank you for the suggestions.

**Comment by jerowe** [comment]
One can never have too many comments. ;-)

**Comment by jerowe** [comment]
FYI - if you are relying on particular versions for a major project you could build conda env with your hard requirements. It is what my department does projects in order to maintain reproducibility. All it requires is a anaconda cloud account.

**Comment by PatrickRWright** [comment]
Ok, thanks. It all appears to be working. Can you merge this?

**Pull request merged**
