### PR TITLE
Update Picard to 2.18.25.

### PR DESCRIPTION
**Pull request by cbrueffer**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by epruesse** [comment]
Does anything inside of Bioconda depend on the old version that won't build anymore?

**Comment by epruesse** [comment]
Looking at the depends:
- ctat-mutations is hard pinned to 2.18.14
- cap-mirseq needs >=1.97

The others all just require picard. So IMHO, all subfolders but 2.18.14 can go. And even for that one I have the feeling that ctat-mutations is overpinned.

**Comment by epruesse** [comment]
Do you know how upstream keeps their versions? I vote for removing all sub recipes and making ctat-mutations depend on >=2.18.14,<2.19 - unless upstream has a history of changing API at will, which I sort of doubt.

**Comment by cbrueffer** [comment]
No idea, but the packages themselves remain available, so the 2.18.14 dependency will be satisfied. Thanks for having a look!

**Pull request merged**
