### PR TITLE
add neusomatic

### PR DESCRIPTION
**Pull request by johanneskoester**
Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

 * `@BiocondaBot please update` will cause the BiocondaBot to merge the master branch into a PR
 * `@BiocondaBot please add label` will add the `please review & merge` label.
 * `@BiocondaBot please fetch artifacts` will post links to packages and docker containers built by the CI system. You can use this to test packages locally before merging.

For members of the Bioconda project, the following command is also available:

 * `@BiocondaBot please merge` will cause packages/containers to be uploaded and a PR merged. Someone must approve a PR first! This has the benefit of not wasting CI build time required by manually merging PRs.

If you have questions, please post them in gitter or ping `@bioconda/core` in a comment (if you are not able to directly ping `@bioconda/core` then the bot will repost your comment and enable pinging).

### CODE REVIEW

**Comment by johanneskoester** [comment]
@BiocondaBot update

**Comment by mbargull** [comment]
This downloads and builds an extra library which then itself builds some other addtional libs.
I think we should
- Patch https://github.com/bioinform/neusomatic/blob/v0.2.1/third_party/seqlib.cmake#L14-L15
  to stop that download.
- Let `conda-build` download the above.
  (Either by using `git_url` or downloading archives for the submodules separately.)
- Patch https://github.com/bioinform/neusomatic/blob/v0.2.1/third_party/seqlib.cmake#L17-L18
  to pass on `CC`, `CFLAGS`, ...
- Also need to patch https://github.com/walaj/bwa/blob/c02766e3c34ac3f4af9842e20a54b7f9f4b36d0b/Makefile#L16
  since it does not honor `LDFLAGS`. (This might apply to `fermi-lite` and `htslib` -- haven't checked that.)

`bwa` and `fermi-lite` come from patched forks, meaning it probably does not make sense to try to use existing ones from Bioconda.

**Comment by mbargull** [comment]
It also downloads SeqAn without specifing a specific tag/version: https://github.com/bioinform/neusomatic/blob/v0.2.1/third_party/seqan.cmake
which is odd..

**Comment by johanneskoester** [comment]
Ok, since this is not a high priority for me currently, I am closing this PR. Thanks @mbargull for the detailed inspection of the involved tasks!

**Pull request closed without merging**
