### PR TITLE
rpy2: bump version to 2.8.2

### PR DESCRIPTION
**Pull request by croth1**
- [x] I have read the guidelines above.
- [ ] This PR adds a new recipe.
- [x] This PR updates an existing recipe.
- [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by croth1** [comment]
Hmh, apparently `testRpyMemory` segfaults in our build environment. 

```
def testRpyMemory(self):
        x = rinterface.SexpVector(range(10), rinterface.INTSXP)
        y = rinterface.SexpVector(range(10), rinterface.INTSXP)
        x_rid = x.rid
        self.assertTrue(x_rid in set(z[0] for z in rinterface.protected_rids()))
        del(x)
        gc.collect(); gc.collect()
        self.assertFalse(x_rid in set(z[0] for z in rinterface.protected_rids()))
```

Can anyone test if the failure only pops up in bioconda's build environment on linux? I only have arch linux here, and unfortunately Continuum's r package does not work on arch.

@lgautier any idea what could trigger the segfault here? It's very suspicious that macOS apparently works and only linux segfaults, though.

**Comment by dmaticzka** [comment]
Looks like the old error was replaced by new ones: Now complains about missing R_X11.so and libXt.so.6 libraries during testing. Can't see why, though. At least R_X11.so should be there because of the r dependencies...

**Comment by lgautier** [comment]
@croth1 The segfault could be anything from hardware issues with the RAM to mismatching shared libraries (different at build time and at run time). rpy2 is developed on Linux, and there is a Docker container (see http://rpy2.bitbucket.org/) to try out whether the error is local to your install/conda or more generally observered.

**Comment by croth1** [comment]
@dmaticzka, yes. I didn't follow up here, because I think it would be better to prepare moving general r-stuff to conda-forge. This will take some time, though.

**Comment by dmaticzka** [comment]
@croth1 nice, no hurry. Just wanted to mention this since I stumbled over it.

**Pull request closed without merging**
