### PR TITLE
Update bioconductor-diffcyt to v. 1.2.23

### PR DESCRIPTION
**Pull request by PertuyF**
:information_source:
If this is your first pull request to Bioconda please ping `@bioconda/core` so it can be reviewed and to request being added as a member of the Bioconda team. Members of the Bioconda team are able to merge their own pull requests once tests and linting have passed.

----------------

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

Update to lastest version.

### CODE REVIEW

**Comment by PertuyF** [comment]
Quite strange, installing this package in a new environment and running the test command works fine for me, but test fails during the build.
Any idea why @bioconda/r ?

**Comment by cbrueffer** [comment]
Same problem (GenomeInfoDbData can't be loaded) in https://github.com/bioconda/bioconda-recipes/pull/14472

**Comment by PertuyF** [comment]
Thanks for linking these problems @cbrueffer 👍
May be related to #13846?

**Comment by PertuyF** [comment]
@bioconda/core this package works when install from the bot link. And build works locally. Can we ignore this issue with `GenomeInfoDbData`?

**Comment by dpryan79** [comment]
Yeah, we can merge this anyway. The GenomeInfoDbData thing is weird. I had a colleague run into it but then it didn't happen to me on the exact same server (but different conda installation).

**Comment by PertuyF** [comment]
Thanks @dpryan79

**Comment by dpryan79** [comment]
Right, so unfortunately this didn't and won't get uploaded for linux because the mulled container is throwing the genomeinfodbdata error. It's working of OSX, which is something I guess, but largely defeats the purpose of this actually getting merged in.

**Pull request merged**
