### PR TITLE
Add recipe for bigsi

### PR DESCRIPTION
**Pull request by johnlees**
:information_source:
Bioconda has finished the [GCC7 migration](https://github.com/bioconda/bioconda-recipes/issues/13578). If you are dealing with C/C++ or Python package it can be that you need to rebuild other dependent packages. [Bioconda utils - update-pinning](https://bioconda.github.io/updating.html#updating-recipes-for-a-pinning-change) will assist you with that. If you have any questions please use [issue 13578](https://github.com/bioconda/bioconda-recipes/issues/13578).

----------------

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).

### CODE REVIEW

**Comment by johnlees** [comment]
Added package for BIGSI: https://github.com/Phelimb/BIGSI
(http://dx.doi.org/10.1038/s41587-018-0010-1)

Could I get a review from @bioconda/core please? Thanks!

**Comment by dpryan79** [comment]
@johnlees Looks great! Shall I add you to the bioconda team, or have we already done that?

**Comment by dpryan79** [comment]
Oh, guess you've already been added. Go ahead and merge then :)

**Comment by johnlees** [comment]
Yep, I've already been added. Thanks for the review!

**Pull request merged**
