### PR TITLE
Add Emvc 2

### PR DESCRIPTION
**Pull request by guilledufort**
Describe your pull request here

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by guilledufort** [comment]
@BiocondaBot please add label

**Comment by guilledufort** [comment]
I had to skip osx build due to an error reported in issues. It appears that we are multiple people with the same error. I would be very grateful if you could help me with that problem. Thank you!!

**Comment by guilledufort** [comment]
@BiocondaBot please fetch artifacts

**Comment by guilledufort** [comment]
@BiocondaBot please merge

**Comment by kbseah** [comment]
hello there, i've mostly been merging straightforward recipe updates to help clear the backlog and get some experience. don't have much experience with building C software, so i can't comment on the build script. for the `meta.yaml`, one question: why did you comment out the dependency versions? was there a problem with solving the dependencies?

**Comment by guilledufort** [comment]
> hello there, i've mostly been merging straightforward recipe updates to help clear the backlog and get some experience. don't have much experience with building C software, so i can't comment on the build script. for the `meta.yaml`, one question: why did you comment out the dependency versions? was there a problem with solving the dependencies?

First of all, thank you for your quick response. The python restrictions are basically the ones I found that worked together in the different systems I had available to test. The only hard restrictions I have is python 3 (needed for the main file) and scikit-learn (which loads a pickle file). The other restrictions are needed to make every python package compatible between each other.

However, I commented out the dependencies because apparently when I left them on and executed the conda tests for Linux , the system downloaded a package version of argparse for python 2.6 incompatible with the python version 3.8 requested. For that reason I tried without the restrictions except for scikit-learn and  it worked correctly.

**Comment by kbseah** [comment]
ok, i played around with the solver and found the following:

 * `argparse` on conda-forge is very out-of-date and no longer maintained. oddly enough there is only one version (1.4.0) on conda-forge. since argparse is part of the python standard library since python 3.2 i think it is not necessary to specify it in the recipe at all
 * `samtools==1.9.0` conflicts with `python ==3.9` because of the `ncurses` library. the environment can be solved if python is dropped to `>=3.8.1,>=3.8.5` like in the readme of the emvc-2 repo.

the following run requirements worked for me in local test:
```
  run:
    - python ==3.8.1,<=3.8.5
    - samtools ==1.9
    - numpy >=1.16.6,<=1.20.3
    - scipy >=1.1.0,<1.5.4
    - tqdm >=4.46.0
    - scikit-learn >=0.22.2,<=0.24.2
```

**Review by kbseah — APPROVED** [review]

**Pull request merged**
