### PR TITLE
freebayes: add linux-aarch64 build

### PR DESCRIPTION
**Pull request by martin-g**
Describe your pull request here

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

### General instructions

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

### Instructions for avoiding API, ABI, and CLI breakage issues
Conda is able to record and lock (a.k.a. pin) dependency versions used at build time of other recipes.
This way, one can avoid that expectations of a downstream recipe with regards to API, ABI, or CLI are violated by later changes in the recipe.
If not already present in the meta.yaml, make sure to specify `run_exports` (see [here](https://bioconda.github.io/contributor/linting.html#missing-run-exports) for the rationale and comprehensive explanation).
Add a `run_exports` section like this:

```yaml
build:
  run_exports:
    - ...

```

with `...` being one of:

| Case                             | run_exports statement                                               |
| -------------------------------- | ------------------------------------------------------------------- |
| semantic versioning              | `{{ pin_subpackage("myrecipe", max_pin="x") }}`     |
| semantic versioning (0.x.x)      | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}`   |
| known breakage in minor versions | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| known breakage in patch versions | `{{ pin_subpackage("myrecipe", max_pin="x.x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| calendar versioning              | `{{ pin_subpackage("myrecipe", max_pin=None) }}`    |

while replacing `"myrecipe"` with either `name` if a `name|lower` variable is defined in your recipe or with the lowercase name of the package in quotes.

### Bot commands for PR management

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

Note that the <code>@BiocondaBot please merge</code> command is now depreciated. Please just squash and merge instead.

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by martin-g** [comment]
Waiting for linux-aarch64 packages of [tabixpp](https://github.com/bioconda/bioconda-recipes/pull/46754) and [wfa2-lib](https://github.com/bioconda/bioconda-recipes/pull/46753) to appear at https://anaconda.org/bioconda/tabixpp and https://anaconda.org/bioconda/wfa2-lib

**Comment by martin-g** [comment]
Depends on conda-forge/parallel:
- https://github.com/conda-forge/parallel-feedstock/pull/41 
- https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/5693

**Comment by martin-g** [comment]
It still fails with:
```
19:47:47 [32mBIOCONDA INFO[0m (OUT) The reported errors are:[0m
19:47:47 [32mBIOCONDA INFO[0m (OUT) - Encountered problems while solving:[0m
19:47:47 [32mBIOCONDA INFO[0m (OUT) -   - nothing provides requested parallel[0m
```
although I can see the new https://anaconda.org/conda-forge/parallel/20240122/download/linux-aarch64/parallel-20240122-h8af1aa0_0.conda

**Comment by martin-g** [comment]
@BiocondaBot please fetch artifacts

**Comment by mencian** [comment]
@martin-g Perhaps I merged a little too quickly 😅

**Comment by martin-g** [comment]
```
mgrigorov in 🌐 euler-arm-22 in /tmp/freebayes via 🅒 font-ubuntu took 7m19s 
❯ vcfld                                                                                                                                                                                                (font-ubuntu) 
vcfld: symbol lookup error: /home/mgrigorov/miniconda3/envs/font-ubuntu/bin/../lib/libvcflib.so.1: undefined symbol: wavefront_align

mgrigorov in 🌐 euler-arm-22 in /tmp/freebayes via 🅒 font-ubuntu 
❯ conda install vcflib-1.0.9-h7f4e536_5.tar.bz2                                                                                                                                                        (font-ubuntu) 

Downloading and Extracting Packages

Preparing transaction: done
Verifying transaction: done
Executing transaction: done

mgrigorov in 🌐 euler-arm-22 in /tmp/freebayes via 🅒 font-ubuntu took 4s 
❯ vcfld                                                                                                                                                                                                (font-ubuntu) 
vcfld: symbol lookup error: /home/mgrigorov/miniconda3/envs/font-ubuntu/bin/../lib/libvcflib.so.1: undefined symbol: wavefront_align

mgrigorov in 🌐 euler-arm-22 in /tmp/freebayes via 🅒 font-ubuntu 
❯ conda list | grep wfa2                                                                                                                                                                               (font-ubuntu) 
wfa2-lib                  2.3.4                h78569d1_1    bioconda
```

I got this error while testing the binaries of `vcflib` ...

**Comment by martin-g** [comment]
freebayes looks OK though:
```

mgrigorov in 🌐 euler-arm-22 in /tmp/freebayes via 🅒 font-ubuntu 
❯ file bin/*                                                                                                                                                                                           (font-ubuntu) 
bin/bamleftalign:                         ELF 64-bit LSB pie executable, ARM aarch64, version 1 (GNU/Linux), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, with debug_info, not stripped
bin/coverage_to_regions.py:               Python script, ASCII text executable
bin/fasta_generate_regions.py:            Python script, ASCII text executable
bin/freebayes:                            ELF 64-bit LSB pie executable, ARM aarch64, version 1 (GNU/Linux), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, with debug_info, not stripped
bin/freebayes-parallel:                   Bourne-Again shell script, ASCII text executable
bin/generate_freebayes_region_scripts.sh: Bourne-Again shell script, ASCII text executable
bin/sam_add_rg.pl:                        Perl script text executable
bin/split_ref_by_bai_datasize.py:         Python script, ASCII text executable
bin/update_version.sh:                    POSIX shell script, ASCII text executable

mgrigorov in 🌐 euler-arm-22 in /tmp/freebayes via 🅒 font-ubuntu 
❯ freebayes                                                                                                                                                                                            (font-ubuntu) 
usage: freebayes -f [REFERENCE] [OPTIONS] [BAM FILES] >[OUTPUT]

Bayesian haplotype-based polymorphism discovery.

parameters:

   -h --help       For a complete description of options.

freebayes is maintained by Erik Garrison and Pjotr Prins.

citation: Erik Garrison, Gabor Marth
          "Haplotype-based variant detection from short-read sequencing"
          arXiv:1207.3907 (http://arxiv.org/abs/1207.3907)

author:   Erik Garrison <erik.garrison@gmail.com>
version:  v1.3.7
```

**Pull request merged**
