### PR TITLE
rebuild smoove container

### PR DESCRIPTION
**Pull request by rpetit3**
The container for smoove currently is not working (related issue https://github.com/brentp/smoove/issues/193). Let's see if a rebuild solves it for us

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by rpetit3** [comment]
@biocondabot please fetch artifacts

**Comment by rpetit3** [comment]
Still an issue, will play with pinnings
```
docker run quay.io/biocontainers/smoove:0.2.8--h9ee0642_1 lumpy_filter
lumpy_filter: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
```

**Comment by rpetit3** [comment]
@BiocondaBot please fetch artifacts

**Comment by rpetit3** [comment]
I think we are good now
```
docker run quay.io/biocontainers/lumpy-sv:0.3.1--hdfd78af_3 lumpy_filter
lumpy_filter: usage     :lumpy_filter -f <optional-reference> <bam> <split out> <discord out> (optional #threads)
```

**Review by apeltzer — APPROVED** [review]

**Comment by rpetit3** [comment]
@BiocondaBot please merge

**Comment by scorreard** [comment]
I think 'lumpy_filter' is missing in the container, and it is not working. 

- Pytest-workflow / smoove conda crashes : https://github.com/nf-core/modules/pull/2222

To check the issue, I installed smoove on my local using this conda image.
`smoove
smoove version: 0.2.8

smoove calls several programs. Those with 'Y' are found on your $PATH. Only those with '*' are required.

 *[Y] bgzip [ sort   -> (compress) ->   index ]
 *[Y] gsort [(sort)  ->  compress   ->  index ]
 *[Y] tabix [ sort   ->  compress   -> (index)]
 *[Y] lumpy
 *[ ] lumpy_filter
 *[Y] samtools
 *[Y] svtyper
 *[Y] mosdepth [extra filtering of split and discordant files for better scaling]`

When I try to run it

`smoove call -n test -f /ssembly.fa sr.sorted.bam
[smoove] 2022/11/07 15:08:54 starting with version 0.2.8
[smoove] 2022/11/07 15:08:54 calculating bam stats for 1 bams
[smoove]: ([E]lumpy-filter) 2022/11/07 15:08:55 /bin/bash: lumpy_filter: command not found
[smoove]:2022/11/07 15:08:55 finished process: lumpy-filter (set -eu; lumpy_filter -f assembly.fa scratch) in user-time:3.015ms system-time:3.379ms
[smoove]:2022/11/07 15:08:55 error running command: set -eu; lumpy_filter -f assembly.fa sr.sorted.bam .//sr-sorted.split.bam.tmp.bam .//sr-sorted.disc.bam.tmp.bam 2 && mv .//sr-sorted.split.bam.tmp.bam .//sr-sorted.split.bam && mv .//sr-sorted.disc.bam.tmp.bam .//sr-sorted.disc.bam && cp .//sr-sorted.split.bam .//sr-sorted.split.bam.orig.bam && cp .//sr-sorted.disc.bam .//sr-sorted.disc.bam.orig.bam -> exit status 127`

I don't know what to do to resolve the issue

**Pull request merged**
