### PR TITLE
Add libgab, this is a small C++ library of bioinformatics functions to add other software.

### PR DESCRIPTION
**Pull request by grenaud**
Describe your pull request here

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by grenaud** [comment]
fixed checks

**Review by apeltzer — APPROVED** [review]
Looks good to me :-) Should make building schmutzi easy now ;-)

**Comment by apeltzer** [comment]
@BiocondaBot please add label

**Comment by apeltzer** [comment]
Not so 100% sure about the tests, maybe @bioconda/core can have a comment on that one?

**Comment by grenaud** [comment]
For the test, I added ls && pwd which is so wrong. I added a script called "test.sh" I tried:
`test:
commands:
   - test.sh
`   
or
`test:
commands:
   - ./test.sh
`   

In both cases, I get "test.sh not found". This is puzzling because other meta.yaml refer to their programs in the base directory. It seems $PREFIX is the prefix for bioconda. Can we just use:
`commands:
ls utils.o`

**Comment by dpryan79** [comment]
For libraries we tend to just test for present of the .so file. I'll update it to do that.

**Comment by dpryan79** [comment]
@bioconda-bot please fetch artifacts

**Comment by dpryan79** [comment]
A couple issues:

 - Nothing is currently getting installed
 - There appear to be no actual libraries built in the Makefile other than gzsteam...which is a dependency.

**Review by dpryan79 — CHANGES_REQUESTED** [review]
This needs to install any relevant headers a .a and/or a .so (on OSX maybe .dylib) file so downstream packages can actually use it.

**Comment by grenaud** [comment]
@dpryan79  thank you for the feedback! I have since changed libgab to create a libgab.a file. The build.sh now copies this to $PREFIX/lib and I have added in the test to check if this libgab.a is in $PREFIX/lib/

Let me know if that solves it.

**Comment by grenaud** [comment]
I forgot the version and sha256. now it is fixed.

**Comment by apeltzer** [comment]
@bioconda-bot please fetch artifacts

**Comment by apeltzer** [comment]
@bioconda-bot please merge

**Comment by dpryan79** [comment]
Are any header files needed (I presume so). Please install them under `$PREFIX/include` (possibly in a gab subdirectory, or whatever is best to match your documentation).

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
I'll go ahead and approve this so you can have the bot merge this, presuming either that no headers are needed or that you update the build script to make them available.

**Comment by grenaud** [comment]
@dpryan79  I have now modified the package to copy the header file to $PREFIX/include. I have renamed the header file to libgab.h to provide it with a meaningful name.

**Comment by apeltzer** [comment]
Guess this is fine then 👍🏼

**Comment by apeltzer** [comment]
@bioconda-bot please merge

**Pull request merged**
