### PR TITLE
Add b2btools

### PR DESCRIPTION
**Pull request by agdiaz**
The new package b2btools refers to bio2Byte software suite to predict protein biophysical properties from their amino-acid sequences. This package provides to the bioinformatics community structural predictions for protein sequences.

* More details are available on https://pypi.org/project/b2bTools/ and https://bio2byte.be
* Co-authors: @agdiaz & @GavaldaGarcia

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by agdiaz** [comment]
@BiocondaBot please update

**Comment by agdiaz** [comment]
@BiocondaBot please add label

**Comment by agdiaz** [comment]
please review & merge

**Comment by agdiaz** [comment]
Hi @bioconda/core, hope you are doing well! Could I ask for a review of this new recipe? It contains several biophysical-property predictors for proteins developed by the research team Bio2Byte (https://www.bio2byte.be/). This is our first time collaborating with Bioconda, we are very excited to be part of this project. The PR has the labels required and the CI checks are all green. If we have to do something extra from our side, please let me know. Thanks in advance for your reviews :)

**Review by GavaldaGarcia — APPROVED** [review]

**Review by GavaldaGarcia — APPROVED** [review]

**Review by daler — APPROVED** [review]

**Comment by daler** [comment]
@BiocondaBot please merge.

Looks good, thanks!

**Comment by agdiaz** [comment]
@daler Thank you very much for your review! Have a nice day 👋

**Pull request merged**
