### PR TITLE
iucn_sim update

### PR DESCRIPTION
**Pull request by tobiashofmann88**
Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it. Note that if you are not already a member of the bioconda project (meaning that you can't add this label), please ping `@bioconda/core` so that your PR can be reviewed and merged (please note if you'd like to be added to the bioconda project). Please see https://github.com/bioconda/bioconda-recipes/issues/15332 for more details.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by tobiashofmann88** [comment]
@dpryan79 thanks a ton for fixing my initial iucn_sim recipe earlier today. I updated the software and made some changes to the recipe and it fails now. I can't quite make sense of the error report as to what went wrong. The only changes I made to the recipe now are adding `r-base` and `r-rredlist` as dependencies and it fails. I also added `r-base` under `requirements -> host` but I'm not sure if that's correct/necessary and if it may cause any problems.

**Comment by dpryan79** [comment]
The problem isn't with the recipe, your python code is invalid (at least in python 3.8).

**Comment by dpryan79** [comment]
I've patched the source code to make it valid and will now merge this. You might want to use continuous integration testing to find things like this before tagging releases.

**Comment by tobiashofmann88** [comment]
thanks a lot, @dpryan79, I will look into continuous integration testing. Am I seeing this correclty that the way you fixed it was changing `import .functions as cust_func` to `import iucn_sim.functions as cust_func` in the `run_sim.py` function? Just so I know for future releases...

**Comment by dpryan79** [comment]
Correct, that's all that's needed.

**Comment by tobiashofmann88** [comment]
@dpryan79, alright, I'll fix it in the source code. Btw even though this seems to be merged now, I cannot find the new `iucn_sim` version 1.3 on bioconda, e.g. `conda search iucn_sim` only displays the previous version 1.2. Any idea why this is the case?

**Comment by dpryan79** [comment]
Looks like the CDN sync is down. Someone from Anaconda Inc will have to look into it.

**Pull request merged**
