### PR TITLE
intarna v2.0.1

### PR DESCRIPTION
**Pull request by martin-mann**
* [x] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by druvus** [comment]
Thanks @martin-mann

**Comment by martin-mann** [comment]
@druvus thanks for merging.. 

but are you sure the package built correctly? I pinged already @bgruening since the [linux travis build log](https://travis-ci.org/bioconda/bioconda-recipes/jobs/204575750) seems to be unnaturally short and doesnt report any build! neither in my PR nor in the (linked) merge travis build...

**Comment by druvus** [comment]
@martin-mann @bgruening you are right. Something weird with the travis log.

**Comment by druvus** [comment]
@martin-mann intarna is listed in the `boost-1.61-migration-blacklist`file so it must be removed from that file be tested and built.

**Comment by bgruening** [comment]
It looks good, but says it was not build ... I think it is part of the boost blacklist as part of rebuilding all boost tools.

**Pull request merged**
