### PR TITLE
MultiQC: Extended container base for py3 with click.

### PR DESCRIPTION
**Pull request by ewels**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

Suggestion by @bgruening to get python 3 builds to work with click. See discussion in #5249.

### CODE REVIEW

**Comment by ewels** [comment]
Hmm - getting close to working! From the last couple of builds it looks like the linux environment wants `C.UTF-8` or `en_US.utf8` as the locale string but OSX wants `en_US.UTF-8` 😠 .

@bgruening - any ideas how to set this in a system-specific manner?

Phil

**Comment by bgruening** [comment]
@ewels you could try something like.
```
    - export LC_ALL=$(locale -a | grep en_US | grep UTF) && export LANG=$(locale -a | grep en_US | grep UTF) && multiqc --version  # [linux]
   -  multiqc --version  # [osx]
```

Sorry, for all the pain!

**Comment by daler** [comment]
@ewels not sure if this will cause more or less pain in the long run, but [`argh`](http://argh.readthedocs.io/en/latest/) is quite similar to click and I've used it a lot. And has no complaints with py3. Looking at the main multiqc script, I think it's almost a drop-in replacement.

**Comment by ewels** [comment]
Thanks both! @bgruening - I take it that it's the `# [linux]` and `# [osx]` that do the system specific stuff? The `$(locale` stuff was my attempt at pulling the correct string manually. Using the comments should be better, will try that now instead.

@daler - yes I have wondered about switching before, even back to argparse which I used in the early days of MultiQC. I use quite a bit of the fancy click stuff though - eg. using setuptools to allow external plugin tools to add their own command line options for example, and even simple stuff like adding a progress bar whilst looping through file searches. So I can imagine that it would still end up taking quite a bit of time...

**Comment by daler** [comment]
@ewels ah, I didn't know it was click that handled the plugin command-line additions and progress bar stuff. That would be an awful lot of work to replicate. 

Also, the `# [linux]` and `# [osx]`  are [preprocessing selectors](https://conda.io/docs/building/meta-yaml.html#preprocessing-selectors) for conda recipes.

**Comment by ewels** [comment]
Aha, nice - thanks! I've seen them around before but was never sure if they were literally just comments or whether they were doing something actively.. Good to see the docs!

**Comment by ewels** [comment]
Linux is being difficult - it's really struggling to set a locale properly (see [here](https://travis-ci.org/bioconda/bioconda-recipes/jobs/258581057#L2039-L2040) and different approach [here](https://travis-ci.org/bioconda/bioconda-recipes/jobs/258584133#L928-L929)).

Final trial-and-error attempt in the latest commit, but going on holiday for a week now. Will come back to it after that.

Phil

**Comment by ewels** [comment]
Ah, oops - sorry, didn't realise that this PR was still open and just pushed the v1.2 release..

**Comment by ewels** [comment]
ok awesome - the Travis build seems to be passing too 🎉

**Comment by bgruening** [comment]
Cool! Great @ewels - hope you had some great holidays.

**Comment by ewels** [comment]
Great stuff - thanks @bgruening! Yup, very chilled holidays thanks ☺️

**Comment by ewels** [comment]
So annoyingly I accidentally overwrote whatever changes we were trying in this PR when I pushed the v1.2 release. Meaning that the v1.1 and v1.2 releases are both still only Python 2.7.

I'll open a new PR and try again with various strategies for getting py 3 to work (I was kind of surprised when the tests passed here so easily!)

Phil

**Pull request merged**
