### PR TITLE
package pfam_scan.pl (searching Pfam with HMMER 3)

### PR DESCRIPTION
**Pull request by peterjc**
* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [X] This PR adds a new recipe.
* [X] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by peterjc** [comment]
This is also similar to the ``build.sh`` used for the ``mugsy`` package by @acaprez

**Comment by simonvh** [comment]
Hi @peterjc, I'm not a Perl expert, but to me the package looks fine. Any specific issues with the build?

**Comment by peterjc** [comment]
(Turns out it was breaking on the multi-line bash syntax to create the wrapper script, copy-paste had gone funny)

**Comment by peterjc** [comment]
Green lights :)

The only thing I am unsure of is how I have used ``$PREFIX/bin`` for the wrapper (which sets ``$PERL5LBI``), and  ``$PREFIX/share/$PKG_NAME-$PKG_VERSION-$PKG_BUILDNUM`` for the actual tool and its Perl bits.

Would it be enough to just stick the unzipped files directly under ``$PREFIX`` instead?

**Comment by simonvh** [comment]
Don't know how other packages approach this, but I like it this way. More tidy IMO.

**Comment by peterjc** [comment]
Yep, I didn't say here in the PR comments, but in the commit notes stated this was based on (your) ``trawler`` recipe - which is why I put you down as a reviewer.

Merging now, thank you!

**Pull request merged**
