### PR TITLE
Bioconda_curl + pyBigWig-0.2.1b

### PR DESCRIPTION
**Pull request by dpryan79**
Update pyBigWig to version 0.2.1. Additionally, add "bioconda_curl", which replaces the problematic version of curl that comes with anaconda (as best as I can tell, this fixes https://github.com/ContinuumIO/anaconda-issues/issues/72, at least under Ubuntu).

### CODE REVIEW

**Comment by johanneskoester** [comment]
Wait, I think the package should be called ``curl`` not ``bioconda_curl`` if it is only a fix. This way, other packages that depend on curl can profit from the fix as well. Also, I would prefer to (at least in parallel), provide a pull request for the official conda-recipes. Further, the recipe lacks a test case.

**Comment by dpryan79** [comment]
If it's called `curl` then the creation of the CA certificates needs to be moved to a separate package and added as a requirement (otherwise the package would require itself). 

My only concern with naming this `curl` is that I'm not sure that (A) it'd be installed if there's already a curl installed with anaconda and (B) if so whether it'd then get overwritten if someone installed something requiring curl from another channel. If neither of those are real issues (I'm not terribly familiar with how conda deals with this) then whatever name you prefer would work :)

I'll add a minimal test case in curl. The actual tests that come with curl take forever and a day to run and would make the rather length travis-ci build time for bioconda absurdly longer.

**Comment by johanneskoester** [comment]
A test like ``curl --help`` is sufficient. I am not sure about your points either, but I think version strings can handle this. Feel free to test it. You can get the CA certificates with wget, can't you?

**Comment by dpryan79** [comment]
Yup, wget would work too. I only used curl since I know it's already there.

**Comment by johanneskoester** [comment]
Great, then I would say let's try with wget and name the package curl.

**Comment by dpryan79** [comment]
I've tested naming the package `curl` and it only works if one explicitly installs it before other packages (i.e., putting it as a requirement doesn't suffice). So the only way to allow packages to have a curl as a requirement that would autoinstall a functional one is to give it a different name. Having said that, since I've reported this to continuum they'll hopefully just release a fixed update, making the whole thing moot.

**Comment by johanneskoester** [comment]
Ok. What happens when you add a suffix to the version, e.g. by adding a [build string](http://conda.pydata.org/docs/building/meta-yaml.html#build-number-and-string) "bioconda"?

**Comment by dpryan79** [comment]
That doesn't seem to have any effect, other than modifying the tarball name. The only thing I suspect would work would be to create a feature and metapackage to track it...but at that point it's probably simpler to just continue using a different name.

**Comment by johanneskoester** [comment]
We could use a higher build number than the anaconda channel. That should definetly work.

**Comment by dpryan79** [comment]
I'll give that a whirl.

**Comment by bgruening** [comment]
@johanneskoester how do we guarantee that this version is not installed anymore as soon as the main channel has integrated the patch?

**Comment by johanneskoester** [comment]
By removing it from the bioconda channel. Since it should be identical to the version that will appear in anaconda, that shouldn't be a problem.

**Pull request merged**
