### PR TITLE
augustus: add boost1.57 build for maker

### PR DESCRIPTION
**Pull request by mbargull**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [x] This PR does something else (explain below).

Re: #7396.
`rmblast`'s dependency on `boost` was constrained in https://github.com/bioconda/bioconda-recipes/pull/4355. Some time after that the older, unconstrained builds of `rmblast` were labelled as `broken`. The package `maker` used those builds and now has a missing dependency.
This PR adds a build of `augustus` that uses ~`boost 1.58*`~ `boost 1.57*` which should make `maker` installable again.

Note that it is very uncommon for a recipe to have a subdirectory that is not intended for builds of older/other versions but due to downstream dependency needs.
Also note that with `conda-build 3.x` this could be accomplished with [build variants](https://conda.io/docs/user-guide/tasks/build-packages/variants.html#creating-conda-build-variant-config-files).
Instead of adding a new recipe, we could also make `augustus`'s main recipe use ~`boost 1.58*`~ `boost 1.57*` as `augustus` is only used for two packages, i.e., `maker` and `busco`. But then again this would constrain user installations/environments and it also feels awkward to constrain a package's run requirements for some downstream dependency combinations.

### CODE REVIEW

**Comment by mbargull** [comment]
Also note, any `boost <1.60` comes from `defaults` and doesn't have a build on `conda-forge`.

**Comment by johanneskoester** [comment]
That is indeed a bad situation. Time for conda-build 3 I think :-)! Nevertheless, shouldn't it be boost 1.58 in the added recipe? Apart from that, LGTM.

**Comment by mbargull** [comment]
Yes, I had it at `boost 1.58*` but there are no builds for those versions available, so I used `boost 1.57*`.

**Comment by mbargull** [comment]
Hold on a sec, let me add a change to `maker` to test this out.

**Comment by mbargull** [comment]
(BTW:
Not directly related to this PR, but I just saw the `LICENSE` file from `maker` stating:
> MAKER is available for academic use under either the Artistic Lscense
2.0 developed by the Perl Foundation or the GNU General Public License
developed by the Free Software Foundation. MAKER is NOT available for
commercial use without a license. Those wishing to license MAKER for
commercial use should contact Moj Eram <moj@tco.utah.edu> to
discuss your needs. 

which is... contradictory 😒. If they license it under the GPL, they [cannot apply those other restrictions](https://www.gnu.org/licenses/gpl-faq.html#NoMilitary).
So, I think it's up to interpretation whether
- the software can only be licensed as academic-only and under Artistic License 2.0 (\*) since there cannot exist a GPL+restrictions license agreement, or
- the software can be licensed under the GPL and those restrictions are just void and can be ignored.

IANAL, so who knows.. IMO: We should just continue to distribute under GPL 3.0 and take it as it is
¯\\\_(ツ)\_/¯
)

**Comment by mbargull** [comment]
Compile error looks like the same as in #7415.

**Comment by mbargull** [comment]
I decided to remove the rebuild of `maker` from this PR. That one [failed](https://circleci.com/gh/bioconda/bioconda-recipes/1184) with
```
+ /bin/bash -x -e /opt/conda/conda-bld/maker_1517478279155/test_tmp/run_test.sh
+ maker --version
Undefined value assigned to typeglob at /opt/conda/conda-bld/maker_1517478279155/_t_env/lib/perl5/site_perl/5.22.0/x86_64-linux-thread-multi/List/MoreUtils.pm line 94.
Undefined value assigned to typeglob at /opt/conda/conda-bld/maker_1517478279155/_t_env/lib/perl5/site_perl/5.22.0/x86_64-linux-thread-multi/List/MoreUtils.pm line 94.
Undefined value assigned to typeglob at /opt/conda/conda-bld/maker_1517478279155/_t_env/lib/perl5/site_perl/5.22.0/x86_64-linux-thread-multi/List/MoreUtils.pm line 94.
Undefined value assigned to typeglob at /opt/conda/conda-bld/maker_1517478279155/_t_env/lib/perl5/site_perl/5.22.0/x86_64-linux-thread-multi/List/MoreUtils.pm line 94.
Undefined value assigned to typeglob at /opt/conda/conda-bld/maker_1517478279155/_t_env/lib/perl5/site_perl/5.22.0/x86_64-linux-thread-multi/List/MoreUtils.pm line 94.
Undefined value assigned to typeglob at /opt/conda/conda-bld/maker_1517478279155/_t_env/lib/perl5/site_perl/5.22.0/x86_64-linux-thread-multi/List/MoreUtils.pm line 94.
Undefined value assigned to typeglob at /opt/conda/conda-bld/maker_1517478279155/_t_env/lib/perl5/site_perl/5.22.0/x86_64-linux-thread-multi/List/MoreUtils.pm line 94.
Undefined value assigned to typeglob at /opt/conda/conda-bld/maker_1517478279155/_t_env/lib/perl5/site_perl/5.22.0/x86_64-linux-thread-multi/List/MoreUtils.pm line 94.
Undefined value assigned to typeglob at /opt/conda/conda-bld/maker_1517478279155/_t_env/lib/perl5/site_perl/5.22.0/x86_64-linux-thread-multi/List/MoreUtils.pm line 94.
Undefined value assigned to typeglob at /opt/conda/conda-bld/maker_1517478279155/_t_env/lib/perl5/site_perl/5.22.0/x86_64-linux-thread-multi/List/MoreUtils.pm line 94.
Undefined value assigned to typeglob at /opt/conda/conda-bld/maker_1517478279155/_t_env/lib/perl5/site_perl/5.22.0/x86_64-linux-thread-multi/List/MoreUtils.pm line 94.
Undefined value assigned to typeglob at /opt/conda/conda-bld/maker_1517478279155/_t_env/lib/perl5/site_perl/5.22.0/x86_64-linux-thread-multi/List/MoreUtils.pm line 94.
Undefined subroutine &List::MoreUtils::firstidx called at /opt/conda/conda-bld/maker_1517478279155/_t_env/lib/perl5/site_perl/5.22.0/x86_64-linux-thread-multi/forks/signals.pm line 33.
Compilation failed in require at /opt/conda/conda-bld/maker_1517478279155/_t_env/bin/maker line 42.
BEGIN failed--compilation aborted at /opt/conda/conda-bld/maker_1517478279155/_t_env/bin/maker line 42.
Undefined subroutine &List::MoreUtils::minmax called at /opt/conda/conda-bld/maker_1517478279155/_t_env/lib/perl5/site_perl/5.22.0/x86_64-linux-thread-multi/forks.pm line 1593.
Compilation failed in require at /opt/conda/conda-bld/maker_1517478279155/_t_env/bin/maker line 42.
BEGIN failed--compilation aborted at /opt/conda/conda-bld/maker_1517478279155/_t_env/bin/maker line 42.
/opt/conda/conda-bld/maker_1517478279155/test_tmp/run_test.sh: line 3:   312 Aborted                 (core dumped) maker --version
```
. Let's rebuild `maker` in a separate PR.

**Comment by mbargull** [comment]
I'm a bit concerned that the `perl`-related builds that happened during the last few days before https://github.com/bioconda/bioconda-utils/pull/262 was merged need to be rebuild.
I am aware of https://github.com/bioconda/bioconda-recipes/pull/7328 and https://github.com/bioconda/bioconda-recipes/pull/7395 but haven't checked if there are other ones.
I'll submit a new PR for `maker` in which I also bump `perl-list-moreutils` to test out whether the failure is due to the previous `perl-list-moreutils` build or not.

**Comment by mbargull** [comment]
Meaning I'll submit the `maker` PR after this `augustus` one is merged and build on `master`.

**Pull request merged**
