### PR TITLE
Removed julia (available in conda-forge)

### PR DESCRIPTION
**Pull request by dfornika**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [ ] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [x] This PR does something else (explain below).

Julia is now [available on conda-forge](https://github.com/conda-forge/julia-feedstock), which is a more appropriate channel for it.

### CODE REVIEW

**Comment by bgruening** [comment]
Awesome, thanks again for your migration effort!

**Comment by dfornika** [comment]
Is there any way to remove the existing julia-0.5.2 build from the bioconda channel on anaconda.org? I'd like to package a julia application and it's pulling the bioconda version of julia, but I need it to depend on the conda-forge version.

**Comment by bgruening** [comment]
@dfornika done!

**Comment by bgruening** [comment]
To provide a little bit background. I just changes the label so they are still in the channel but not available until to specify a label during installation. I tend to really remove this package as it was kind of broken in old releases. Opinions?

**Comment by dfornika** [comment]
I don't know anything about the state of the older builds. It seems reasonable to leave them marked as 'deprecated' for a while (a few months?) and then drop them once the conda-forge build(s) take over.

**Pull request merged**
