### PR TITLE
Update gubbins to v3.1.4

### PR DESCRIPTION
**Pull request by nickjcroucher**
Update gubbins recipe to v3.1.4 (includes changes in dependencies)

### CODE REVIEW

**Comment by nickjcroucher** [comment]
@dpryan79 Thanks very much for correcting the meta.yaml file - it appears there is a problem with the AutoMerge.yml for bioconda at the moment? Just let me know if there's anything else I should do on the package side.

**Review by druvus — APPROVED** [review]

**Comment by druvus** [comment]
@BiocondaBot please merge

**Comment by druvus** [comment]
@BiocondaBot please update

**Comment by druvus** [comment]
@BiocondaBot please update

**Pull request merged**
