### PR TITLE
fix gnuplot version

### PR DESCRIPTION
**Pull request by mmiladi**
* [ ] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [ ] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by bgruening** [comment]
@mmiladi we should use this one here: https://github.com/conda-forge/gnuplot-feedstock
Can you check if you got the conda-forge version? If you depend on `>=5.2.0` will it work?

**Comment by mmiladi** [comment]
@bgruening The tool breaks by using gnuplot version 5.2. Since the gnuplot conda was upgraded from last build 5.0 to 5.2, the new builds were failing. So we have to stick to the 5.0.4.

**Comment by mmiladi** [comment]
cond-forge oldest version is 5.0.5. Is there a problem with using the bioconda package?

**Comment by mbargull** [comment]
Reversing the question: Is there a problem with using the `conda-forge` package (`5.0.5`, `5.0.6`) :wink:? Would a `<5.2` or `<5.1` work?

**Comment by mmiladi** [comment]
@mbargull this is also one way to look at it ;-) I'll check.

**Comment by mmiladi** [comment]
Opened a new PR https://github.com/bioconda/bioconda-recipes/pull/6853

**Pull request merged**
