### PR TITLE
Bump/scanpy scripts

### PR DESCRIPTION
**Pull request by nh3**
Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it. Note that if you are not already a member of the bioconda project (meaning that you can't add this label), please ping `@bioconda/core` so that your PR can be reviewed and merged (please note if you'd like to be added to the bioconda project). Please see https://github.com/bioconda/bioconda-recipes/issues/15332 for more details.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by nh3** [comment]
The bump since v0.2.1 is to make sure it passes test when being buildt on systems not setting UTF-8 encoding or not having UTF-8 locale at all.

Click won't run in python3 without UTF-8 encoding. v0.2.1 set environment variable $LANG to UTF-8, which is sufficient to pass test during PR, but not when being built after merged to master which seems to be in an environment without available UTF-8 locale at all. The solution in v0.2.2 is to have scanpy-scripts exit cleanly with a warning when it detects $LANG is unset or not in UTF-8 rather than throw out an exception that fails test.

**Comment by nh3** [comment]
Thanks @pinin4fjords! Just noticed that bioconda now has pypi package recipes monitored and auto-bumped (#16245). I am thinking of just approving that one.

**Comment by pinin4fjords** [comment]
Ahh- was wondering if you'd spotted the autobumps. Thought you were just keen ;-)

**Comment by nh3** [comment]
I didn't at first until the bot sent me a notification. It's quite a neat feature. Seems there's some extra benefit now of putting our python wrappers on pypi.

**Comment by nh3** [comment]
Thanks all the same @pinin4fjords! I've merged the other PR and I am closing this one.

**Comment by pinin4fjords** [comment]
It's not just PyPi- lots of autobumping going on :-)

**Pull request closed without merging**
