### PR TITLE
Update pathogen-profiler to 2.0.1

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`pathogen-profiler`](https://bioconda.github.io/recipes/pathogen-profiler/README.html): **2.0.0** &rarr; **2.0.1**

[install with bioconda](http://bioconda.github.io/recipes/pathogen-profiler/README.html) [Conda](https://anaconda.org/bioconda/pathogen-profiler/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/pathogen-profiler`](https://github.com//bioconda/bioconda-recipes/tree/bump/pathogen_profiler/recipes/pathogen-profiler) (click to view/edit other files)
Summary | Library giving access to classes and functions to create a profiling tool to look for mutations from NGS data.
Home | [https://github.com/jodyphelan/pathogen-profiler](https://github.com/jodyphelan/pathogen-profiler)
Releases |[https://github.com/jodyphelan/pathogen-profiler/tags](https://github.com/jodyphelan/pathogen-profiler/tags)
Author | @jodyphelan
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Review by jodyphelan — APPROVED** [review]

**Comment by jodyphelan** [comment]
@BiocondaBot please merge

**Comment by abhi18av** [comment]
@jodyphelan , I'm trying to follow up the error trail thrown in https://github.com/bioconda/bioconda-recipes/pull/36053/checks?check_run_id=7576540995  and it seems that the root cause is `v2.0.1` of `pathogen-profiler` hasn't been released yet on the main channel.

Is there a way to confirm whether the status of the artifacts? Or perhaps we need to re-trigger this build by updating the build number?

- Root cause for failure in https://github.com/bioconda/bioconda-recipes/pull/36053


```

2022-07-29T09:46:14.6090006Z 09:46:14 BIOCONDA INFO (OUT) The reported errors are:
2022-07-29T09:46:14.6090744Z 09:46:14 BIOCONDA INFO (OUT) - Encountered problems while solving:
2022-07-29T09:46:14.6095266Z 09:46:14 BIOCONDA INFO (OUT) -   - nothing provides requested pathogen-profiler 2.0.1.*
2022-07-29T09:46:14.6095819Z 09:46:14 BIOCONDA INFO (OUT) -
2022-07-29T09:46:14.7108659Z 09:46:14 BIOCONDA INFO (OUT) 
```

- Despite this PR being merged successfully, for some reason the artifacts aren't available yet 

```
(base) bash-5.0$ mamba search pathogen-profiler

Loading channels: done
# Name                       Version           Build  Channel             
pathogen-profiler                0.1            py_0  bioconda            
pathogen-profiler                0.1            py_1  bioconda            
pathogen-profiler                0.1            py_2  bioconda            
pathogen-profiler                0.1            py_3  bioconda            
pathogen-profiler                1.0            py_0  bioconda            
pathogen-profiler                1.1            py_0  bioconda            
pathogen-profiler                1.1            py_1  bioconda            
pathogen-profiler                1.1            py_2  bioconda            
pathogen-profiler                1.2            py_0  bioconda            
pathogen-profiler                1.3            py_0  bioconda            
pathogen-profiler                1.5            py_0  bioconda            
pathogen-profiler                1.6            py_0  bioconda            
pathogen-profiler              1.6.1            py_0  bioconda            
pathogen-profiler                1.7            py_0  bioconda            
pathogen-profiler              1.7.1            py_0  bioconda            
pathogen-profiler              1.7.1            py_1  bioconda            
pathogen-profiler              1.7.2            py_0  bioconda            
pathogen-profiler              1.7.3            py_0  bioconda            
pathogen-profiler              1.7.3    pyh864c0ab_1  bioconda            
pathogen-profiler              2.0.0  pypyh5e36f6f_0  bioconda            
pathogen-profiler              2.0.0  pypyh5e36f6f_1  bioconda            
```

**Comment by jodyphelan** [comment]
Yeah I'm not too sure why this is happening. It works when installing like this in a fresh env:
```
mamba install https://anaconda.org/bioconda/pathogen-profiler/2.0.1/download/noarch/pathogen-profiler-2.0.1-pypyh5e36f6f_0.tar.bz2
```

I'm not too much of an expert on the intricacies of the conda/bioconda system. Do you think updating the build number would work?

I've tried installing other packages that were recently updated and they didn't work either. So maybe it is a bioconda-wide issue?
E.g. busco which was updated 25h before the writing of this comment:
```
$ mamba install busco=5.4.2
....
Encountered problems while solving:
  - nothing provides requested busco 5.4.2**

```

**Comment by abhi18av** [comment]
> I've tried installing other packages that were recently updated and they didn't work either. So maybe it is a bioconda-wide issue?
E.g. busco which was updated 25h before the writing of this comment:

Thanks for the quick response Jodi!

Hmm, this is interesting and I must confess I haven't seen this happen earlier. Pinging @bioconda/core wizards 🪄  for further guidance on these issues 🙏 

Are these temporary/random issues or is this something systematic?

**Comment by abhi18av** [comment]
Good news - the artifacts came back from vacation 😄

**Pull request merged**
