### PR TITLE
Update pmmrcalculator to 1.0.3

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`pmmrcalculator`](https://bioconda.github.io/recipes/pmmrcalculator/README.html): **1.0.1** &rarr; **1.0.3**

[install with bioconda](http://bioconda.github.io/recipes/pmmrcalculator/README.html) [Conda](https://anaconda.org/bioconda/pmmrcalculator/files)

Info | Link
-----|-----
Recipe | [`recipes/pmmrcalculator`](https://github.com//bioconda/bioconda-recipes/tree/bump/pmmrcalculator/recipes/pmmrcalculator) (click to view/edit other files)
Releases |[https://github.com/TCLamnidis/pMMRCalculator/tags](https://github.com/TCLamnidis/pMMRCalculator/tags)
Author | `@TCLamnidis`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by bgruening** [comment]
you can now use the power of the bot, please read the doc linked above, to merge this.

**Comment by TCLamnidis** [comment]
@BiocondaBot please merge

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Comment by dpryan79** [comment]
@TCLamnidis If you're interested in joining the bioconda project I can add you. You can then use the bot to merge things.

**Comment by TCLamnidis** [comment]
@dpryan79 I'd love to, if the offer is still up :)

**Pull request merged**
