### PR TITLE
Coinfinder recipe

### PR DESCRIPTION
**Pull request by fwhelan**
Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

 * `@BiocondaBot please update` will cause the BiocondaBot to merge the master branch into a PR
 * `@BiocondaBot please add label` will add the `please review & merge` label.
 * `@BiocondaBot please fetch artifacts` will post links to packages and docker containers built by the CI system. You can use this to test packages locally before merging.

For members of the Bioconda project, the following command is also available:

 * `@BiocondaBot please merge` will cause packages/containers to be uploaded and a PR merged. Someone must approve a PR first! This has the benefit of not wasting CI build time required by manually merging PRs.

If you have questions, please post them in gitter or ping `@bioconda/core` in a comment (if you are not able to directly ping `@bioconda/core` then the bot will repost your comment and enable pinging).

### CODE REVIEW

**Comment by fwhelan** [comment]
@BiocondaBot please fetch artifacts

**Comment by fwhelan** [comment]
@BiocondaBot please fetch artifacts

**Comment by fwhelan** [comment]
@BiocondaBot please fetch artifacts

**Comment by fwhelan** [comment]
@BiocondaBot please fetch artifacts

**Comment by fwhelan** [comment]
@bioconda-bot please fetch artifacts

**Comment by fwhelan** [comment]
@dpryan79 sorry to bother you again. I’m having trouble getting a bioconductor package to load correctly. There doesn’t seem to be any errors associated with it in the meta.yml but `library(ggtree)` fails in my code. Would you know of any good recipe examples for other tools I could follow? Or know of any good guide websites/documents? I’m a bit lost here! Thanks!

**Comment by dpryan79** [comment]
Is this a package dependency or are you seeing this if you just create an env with `bioconductor-ggtree` in it? We make the bioconductor packages in an automated way, so it's possible that there's some system dependency that ggtree has that perhaps we're skipping.

**Comment by fwhelan** [comment]
@bioconda-bot please fetch artifacts

**Comment by fwhelan** [comment]
I've added `Rscript -e "library(ggtree)"` as a test in my `meta.yml` which the last commit passes.

But on the commandline, if I try:
```
$conda create -n coinfinder -c https://85879-42372094-gh.circle-artifacts.com/0/tmp/artifacts/packages coinfinder
$conda activate coinfinder
$Rscript -e "library(ggtree)"
Error: package or namespace load failed for ‘ggtree’:
 object ‘as_data_frame’ is not exported by 'namespace:tidytree'
Execution halted
$conda install bioconductor-ggtree
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.
```

But if I create an environment and install just bioconductor-ggtree, it works:
```
$conda create -n test -c bioconda bioconductor-ggtree
$conda activate test
$Rscript -e "library(ggtree)"
Registered S3 method overwritten by 'treeio':
  method     from
  root.phylo ape 
ggtree v2.0.0  For help: https://yulab-smu.github.io/treedata-book/

If you use ggtree in published research, please cite the most appropriate paper(s):

- Guangchuang Yu, Tommy Tsan-Yuk Lam, Huachen Zhu, Yi Guan. Two methods for mapping and visualizing associated data on phylogeny using ggtree. Molecular Biology and Evolution 2018, 35(12):3041-3043. doi: 10.1093/molbev/msy194
- Guangchuang Yu, David Smith, Huachen Zhu, Yi Guan, Tommy Tsan-Yuk Lam. ggtree: an R package for visualization and annotation of phylogenetic trees with their covariates and other associated data. Methods in Ecology and Evolution 2017, 8(1):28-36, doi:10.1111/2041-210X.12628
```

But because my build passes, I wonder if this might just be my conda environment?

**Comment by dpryan79** [comment]
Sounds like there's something in your env preventing you from getting the version of tidytree that ggtree needs.

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Pull request merged**
