### PR TITLE
update cgat-scripts-nosetests to version 0.0.4

### PR DESCRIPTION
**Pull request by sebastian-luna-valero**
* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [X] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by sebastian-luna-valero** [comment]
We would like to build this meta-package for Python 3.6, so I have asked `ggplot` package maintainers over at `conda-forge` whether it can be rebuilt:
https://github.com/conda-forge/ggplot-feedstock/issues/11

For reference:
https://travis-ci.org/bioconda/bioconda-recipes/jobs/233311091#L713

**Comment by sebastian-luna-valero** [comment]
Hi @bioconda/core 

Could you please have a look at why this update to the recipe is failing?
https://travis-ci.org/bioconda/bioconda-recipes/jobs/234768023

Many thanks,
Sebastian

**Comment by johanneskoester** [comment]
Aparently the space on the travis VM is full. We could be a bit more careful with the package cache, and let bioconda-utils clean up after each build. @daler @bgruening: opinions?

**Comment by johanneskoester** [comment]
In the future, please call such PRs e.g. "cgat-scripts-nosetests 4.5", such that one can see about which recipe this is.

**Comment by daler** [comment]
@johanneskoester I had assumed it was docker images taking up space but wasn't able to find anything obvious (e.g., we're using `docker run --rm`; `docker image ls` shows 1MB mulled-build images and a single `tmp-bioconda-builder` image). 

I wasn't thinking package cache, we should definitely clean up afterwards.

xref #4739, #4777

**Comment by bgruening** [comment]
Cleaning up after every build means the build takes longer  as you might need download python etc twice. This here is only one recipe right? I think the problems arise lately because we still have a bug and rebuild one package 3 times :(

**Comment by chapmanb** [comment]
Ooops sorry, I referenced the wrote PR. Reopening

**Comment by sebastian-luna-valero** [comment]
Thanks everyone!

**Pull request merged**
