### PR TITLE
Haystack bio update

### PR DESCRIPTION
**Pull request by rfarouni**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x ] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by rfarouni** [comment]
@bgruening Hi Bjoern,  what you happen to know what this [error]((#6114)) means ? Also I am still unable to conda install the package. When I run 

```conda install haystack_bio```

I am prompted to install an earlier version 'v0.5.0-0', not the latest '0.5.2'
```
haystack_bio:              v0.5.0-0              bioconda
```

By the way, the PR for 0.5.1 passed a week ago and I am still unable to install it through bioconda.

Thanks!

**Comment by bgruening** [comment]
This is not the error. Sorry on my mobile can you give me the link to Travis?

**Comment by rfarouni** [comment]
Sorry here is the [link](https://travis-ci.org/bioconda/bioconda-recipes/builds/278902766?utm_source=email&utm_medium=notification)

**Comment by bgruening** [comment]
@rfarouni you have skip the build completely here: https://github.com/bioconda/bioconda-recipes/blob/86572a55e3227485ada7c2a3a4cbe03677433cb6/recipes/haystack_bio/meta.yaml#L20

**Comment by rfarouni** [comment]
@bgruening since the package is for Linux and macOS, should I set to

`  skip: true  # [not win]`

or just leave the whole line out?

**Comment by bgruening** [comment]
just remove this line ... :)

**Comment by rfarouni** [comment]
@bgruening Thanks!

**Comment by rfarouni** [comment]
@bgruening but what build-number should I put now since I actually skipped the previous builds by mistake?

**Comment by bgruening** [comment]
should be 0 I think

**Pull request merged**
