### PR TITLE
Add fastText 0.1.0

### PR DESCRIPTION
**Pull request by JungeAlexander**
* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [X] This PR adds a new recipe.
* [X] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by bgruening** [comment]
The recipes looks good to me. But I'm not sure if this is directly relevant to biological science. Maybe it fits better to conda-forge?

**Comment by JungeAlexander** [comment]
Thanks for the comment, Björn!

You are right, it's not a bioinformatics tool per se but I'm using fastText
in my own projects related to biomedical text mining and so do several
others in our group. Let me know if that doesn't merit adding the recipe to
bioconda and I will look into pushing to conda-forge instead.


On Oct 28, 2017 10:58, "Björn Grüning" <notifications@github.com> wrote:

The recipes looks good to me. But I'm not sure if this is directly relevant
to biological science. Maybe it fits better to conda-forge?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/bioconda/bioconda-recipes/pull/6521#issuecomment-340161602>,
or mute the thread

**Comment by bgruening** [comment]
The current guidelines state "is directly relevant to the biological sciences". I think it would be better in conda-forge, if you don't mind.

**Comment by JungeAlexander** [comment]
Sure, no problem.

**Pull request closed without merging**
