### PR TITLE
Add recipe for MultiGPS version 0.72

### PR DESCRIPTION
**Pull request by gregvonkuster**
* [x] I have read the guidelines above.
* [x] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by gregvonkuster** [comment]
@bgruening Hmm....no idea why this time out.  :(

**Comment by gregvonkuster** [comment]
@bgruening Do you know why the travis test keeps timing ouyt on this recipe?  The build takes < 1 minute locally for me.  Here is the log when I build locally - do you see some issue that may be causing the travis timouts?
```
$ date
Mon Dec  5 10:54:57 EST 2016
$ conda build .
BUILD START: multigps-0.72-0
Source cache directory is: /home/greg/miniconda2/conda-bld/src_cache
Found source in cache: multigps_v0.72.jar
Extracting download
Warning: Unrecognized source format. Source file will be copied to the SRC_DIR
Package: multigps-0.72-0
source tree in: /home/greg/miniconda2/conda-bld/0.72_1480953303401/work
+ source /home/greg/miniconda2/bin/activate /home/greg/miniconda2/conda-bld/0.72_1480953303401/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho
+ set -eu -o pipefail
+ outdir=/home/greg/miniconda2/conda-bld/0.72_1480953303401/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/share/multigps-0.72-0
+ mkdir -p /home/greg/miniconda2/conda-bld/0.72_1480953303401/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/share/multigps-0.72-0
+ mkdir -p /home/greg/miniconda2/conda-bld/0.72_1480953303401/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/bin
+ cp ./multigps_v0.72.jar /home/greg/miniconda2/conda-bld/0.72_1480953303401/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/share/multigps-0.72-0
+ cp /home/greg/work/bioconda-recipes/multigps2/bioconda-recipes/recipes/multigps/0.72/multigps.sh /home/greg/miniconda2/conda-bld/0.72_1480953303401/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/share/multigps-0.72-0/multigps
+ chmod +x /home/greg/miniconda2/conda-bld/0.72_1480953303401/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/share/multigps-0.72-0/multigps
+ ln -s /home/greg/miniconda2/conda-bld/0.72_1480953303401/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/share/multigps-0.72-0/multigps /home/greg/miniconda2/conda-bld/0.72_1480953303401/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/bin
number of files: 3
Fixing permissions
Making absolute symlink bin/multigps -> /home/greg/miniconda2/conda-bld/0.72_1480953303401/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/share/multigps-0.72-0/multigps relative
Fixing permissions
updating index in: /home/greg/miniconda2/conda-bld/linux-64
updating: multigps-0.72-0.tar.bz2
TEST START: multigps-0.72-0
updating index in: /home/greg/miniconda2/conda-bld/linux-64
updating index in: /home/greg/miniconda2/conda-bld/noarch

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    multigps-0.72              |                0        57.9 MB  local

The following NEW packages will be INSTALLED:

    bioconductor-edger:  3.14.0-r3.3.1_1       bioconda
    bioconductor-limma:  3.29.0-r3.3.1_0       bioconda
    bzip2:               1.0.6-3                       
    cairo:               1.12.18-6                     
    cloog:               0.18.0-0                      
    curl:                7.49.0-1                      
    expat:               2.1.0-0                       
    fontconfig:          2.11.1-6                      
    freetype:            2.5.5-1                       
    gcc:                 4.8.5-7                       
    ghostscript:         9.18-0                bioconda
    glib:                2.43.0-1                      
    gmp:                 6.1.0-0                       
    graphicsmagick:      1.3.23-0              bioconda
    gsl:                 2.2.1-0                       
    harfbuzz:            0.9.39-1                      
    icu:                 54.1-0                        
    isl:                 0.12.2-0                      
    java-jdk:            8.0.92-1              bioconda
    jbig:                2.1-0                         
    jpeg:                8d-2                          
    libffi:              3.2.1-0                       
    libgcc:              5.2.0-0                       
    libpng:              1.6.22-0                      
    libtiff:             4.0.6-2                       
    libxml2:             2.9.2-0                       
    libxslt:             1.1.28-0                      
    meme:                4.11.1-py27pl5.18.2_0 local   
    mpc:                 1.0.3-0                       
    mpfr:                3.1.5-0                       
    multigps:            0.72-0                local   
    ncurses:             5.9-10                        
    openssl:             1.0.2j-0                      
    pango:               1.39.0-1                      
    pcre:                8.39-0                        
    perl:                5.18.2-8              bioconda
    perl-digest-hmac:    1.03-0                bioconda
    perl-encode-locale:  1.05-3                bioconda
    perl-file-listing:   6.04-0                bioconda
    perl-html-parser:    3.72-0                bioconda
    perl-html-tagset:    3.20-0                bioconda
    perl-http-cookies:   6.01-0                bioconda
    perl-http-daemon:    6.01-0                bioconda
    perl-http-date:      6.02-0                bioconda
    perl-http-message:   6.11-0                bioconda
    perl-http-negotiate: 6.01-0                bioconda
    perl-io-html:        1.001-0               bioconda
    perl-io-socket-ssl:  2.024-0               bioconda
    perl-libwww-perl:    6.15-0                bioconda
    perl-lwp-mediatypes: 6.02-0                bioconda
    perl-net-http:       6.09-0                bioconda
    perl-net-ssleay:     1.74-0                bioconda
    perl-ntlm:           1.09-1                bioconda
    perl-threaded:       5.22.0-10             bioconda
    perl-uri:            1.71-0                bioconda
    perl-www-robotrules: 6.02-0                bioconda
    perl-xml-parser:     2.44-4                bioconda
    pip:                 9.0.1-py27_0                  
    pixman:              0.32.6-0                      
    python:              2.7.12-1                      
    r:                   3.3.1-r3.3.1_0        r       
    r-base:              3.3.1-5               r       
    r-boot:              1.3_18-r3.3.1_0       r       
    r-class:             7.3_14-r3.3.1_0       r       
    r-cluster:           2.0.4-r3.3.1_0        r       
    r-codetools:         0.2_14-r3.3.1_0       r       
    r-foreign:           0.8_66-r3.3.1_0       r       
    r-kernsmooth:        2.23_15-r3.3.1_0      r       
    r-lattice:           0.20_33-r3.3.1_0      r       
    r-mass:              7.3_45-r3.3.1_0       r       
    r-matrix:            1.2_6-r3.3.1_0        r       
    r-mgcv:              1.8_12-r3.3.1_0       r       
    r-nlme:              3.1_128-r3.3.1_0      r       
    r-nnet:              7.3_12-r3.3.1_0       r       
    r-recommended:       3.3.1-r3.3.1_0        r       
    r-rpart:             4.1_10-r3.3.1_0       r       
    r-spatial:           7.3_11-r3.3.1_0       r       
    r-survival:          2.39_4-r3.3.1_0       r       
    readline:            6.2-2                         
    setuptools:          27.2.0-py27_0                 
    sqlite:              3.13.0-0                      
    tk:                  8.5.18-0                      
    wheel:               0.29.0-py27_0                 
    xz:                  5.2.2-0                       
    yaml:                0.1.6-0                       
    zlib:                1.2.8-3                       

/home/greg/miniconda2/conda-bld/0.72_1480953303401/_t_env/bin/.gcc-post-link.sh: line 10: lsb_release: command not found
+ source /home/greg/miniconda2/bin/activate /home/greg/miniconda2/conda-bld/0.72_1480953303401/_t_env
+ /bin/bash -x -e /home/greg/miniconda2/conda-bld/0.72_1480953303401/test_tmp/run_test.sh
+ multigps --version
+ grep MultiGPS
MultiGPS version 0.72
WARNING: please provide chromosome length information in a genome info file (option --geninfo). MultiGPS will attempt to estimate chromosome lengths from data, but this may not work or may not be accurate.
TEST END: multigps-0.72-0
# If you want to upload this package to anaconda.org later, type:
#
# $ anaconda upload /home/greg/miniconda2/conda-bld/linux-64/multigps-0.72-0.tar.bz2
#
# To have conda build upload to anaconda.org automatically, use
# $ conda config --set anaconda_upload yes




####################################################################################
Source and build intermediates have been left in /home/greg/miniconda2/conda-bld.
There are currently 4 accumulated.
To remove them, you can run the ```conda build purge``` command
$ date
Mon Dec  5 10:55:37 EST 2016
``

**Comment by gregvonkuster** [comment]
@bgruening is there anything I can do to get this one working?  I cannot understand why it is timing out.  :(

**Comment by bgruening** [comment]
You are not using the travis_simulate isn't it? My guess is a different channel order. I need more time to look into it more closely, but my guess is that conda-forge or `r` is producing a dead-lock or unsolvable dependency graph. Please make sure that you use the same channel order than bioconda-travis.

@bioconda/core any other idea?

**Comment by johanneskoester** [comment]
Can you try locally, with bioconda-utils and the containerized build (e.g. by using simulated-travis.py)? Could be channel order, or conda version, ...

**Comment by gregvonkuster** [comment]
My build takes just seconds locally, and I believe my channel order is what is required.
```
$ date
Tue Dec  6 07:53:15 EST 2016
$ conda build recipes/multigps/0.72 --channel conda-forge --channel defaults --channel r --channel bioconda
BUILD START: multigps-0.72-0
Source cache directory is: /home/greg/miniconda2/conda-bld/src_cache
Found source in cache: multigps_v0.72.jar
Extracting download
Warning: Unrecognized source format. Source file will be copied to the SRC_DIR
Package: multigps-0.72-0
source tree in: /home/greg/miniconda2/conda-bld/0.72_1481028798286/work
+ source /home/greg/miniconda2/bin/activate /home/greg/miniconda2/conda-bld/0.72_1481028798286/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho
+ set -eu -o pipefail
+ outdir=/home/greg/miniconda2/conda-bld/0.72_1481028798286/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/share/multigps-0.72-0
+ mkdir -p /home/greg/miniconda2/conda-bld/0.72_1481028798286/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/share/multigps-0.72-0
+ mkdir -p /home/greg/miniconda2/conda-bld/0.72_1481028798286/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/bin
+ cp ./multigps_v0.72.jar /home/greg/miniconda2/conda-bld/0.72_1481028798286/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/share/multigps-0.72-0
+ cp /home/greg/work/bioconda-recipes/multigps2/bioconda-recipes/recipes/multigps/0.72/multigps.sh /home/greg/miniconda2/conda-bld/0.72_1481028798286/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/share/multigps-0.72-0/multigps
+ chmod +x /home/greg/miniconda2/conda-bld/0.72_1481028798286/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/share/multigps-0.72-0/multigps
+ ln -s /home/greg/miniconda2/conda-bld/0.72_1481028798286/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/share/multigps-0.72-0/multigps /home/greg/miniconda2/conda-bld/0.72_1481028798286/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/bin
number of files: 3
Fixing permissions
Making absolute symlink bin/multigps -> /home/greg/miniconda2/conda-bld/0.72_1481028798286/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/share/multigps-0.72-0/multigps relative
Fixing permissions
updating index in: /home/greg/miniconda2/conda-bld/linux-64
updating: multigps-0.72-0.tar.bz2
TEST START: multigps-0.72-0
updating index in: /home/greg/miniconda2/conda-bld/linux-64
updating index in: /home/greg/miniconda2/conda-bld/noarch

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    multigps-0.72              |                0        57.9 MB  local

The following NEW packages will be INSTALLED:

    bioconductor-edger:  3.14.0-r3.3.1_1       bioconda   
    bioconductor-limma:  3.29.0-r3.3.1_0       bioconda   
    bzip2:               1.0.6-3                          
    ca-certificates:     2016.9.26-0           conda-forge
    cairo:               1.12.18-6                        
    certifi:             2016.9.26-py27_0      conda-forge
    cloog:               0.18.0-0                         
    curl:                7.49.1-1              conda-forge
    expat:               2.1.0-2               conda-forge
    fontconfig:          2.11.1-6                         
    freetype:            2.5.5-1                          
    gcc:                 4.8.5-7                          
    gettext:             0.19.7-1              conda-forge
    ghostscript:         9.18-0                bioconda   
    glib:                2.48.0-4              conda-forge
    gmp:                 6.1.1-1               conda-forge
    graphicsmagick:      1.3.23-0              bioconda   
    gsl:                 2.2.1-0               conda-forge
    harfbuzz:            0.9.39-1                         
    icu:                 54.1-0                           
    isl:                 0.12.2-0                         
    java-jdk:            8.0.92-1              bioconda   
    jpeg:                9b-0                  conda-forge
    libffi:              3.2.1-2               conda-forge
    libgcc:              5.2.0-0                          
    libiconv:            1.14-3                conda-forge
    libpng:              1.6.26-0              conda-forge
    libtiff:             4.0.6-7               conda-forge
    libxml2:             2.9.2-0                          
    libxslt:             1.1.29-1              conda-forge
    meme:                4.11.1-py27pl5.18.2_0 local      
    mpc:                 1.0.3-3               conda-forge
    mpfr:                3.1.4-3               conda-forge
    multigps:            0.72-0                local      
    ncurses:             5.9-10                conda-forge
    openssl:             1.0.2h-3              conda-forge
    pango:               1.39.0-0                         
    pcre:                8.38-1                conda-forge
    perl:                5.18.2-8              bioconda   
    perl-digest-hmac:    1.03-0                bioconda   
    perl-encode-locale:  1.05-3                bioconda   
    perl-file-listing:   6.04-0                bioconda   
    perl-html-parser:    3.72-0                bioconda   
    perl-html-tagset:    3.20-0                bioconda   
    perl-http-cookies:   6.01-0                bioconda   
    perl-http-daemon:    6.01-0                bioconda   
    perl-http-date:      6.02-0                bioconda   
    perl-http-message:   6.11-0                bioconda   
    perl-http-negotiate: 6.01-0                bioconda   
    perl-io-html:        1.001-0               bioconda   
    perl-io-socket-ssl:  2.024-0               bioconda   
    perl-libwww-perl:    6.15-0                bioconda   
    perl-lwp-mediatypes: 6.02-0                bioconda   
    perl-net-http:       6.09-0                bioconda   
    perl-net-ssleay:     1.74-0                bioconda   
    perl-ntlm:           1.09-1                bioconda   
    perl-threaded:       5.22.0-10             bioconda   
    perl-uri:            1.71-0                bioconda   
    perl-www-robotrules: 6.02-0                bioconda   
    perl-xml-parser:     2.44-4                bioconda   
    pip:                 9.0.1-py27_0          conda-forge
    pixman:              0.32.6-0              conda-forge
    python:              2.7.12-1              conda-forge
    r:                   3.3.1-r3.3.1_0        r          
    r-base:              3.3.1-3               r          
    r-boot:              1.3_18-r3.3.1_0       r          
    r-class:             7.3_14-r3.3.1_0       r          
    r-cluster:           2.0.4-r3.3.1_0        r          
    r-codetools:         0.2_14-r3.3.1_0       r          
    r-foreign:           0.8_66-r3.3.1_0       r          
    r-kernsmooth:        2.23_15-r3.3.1_0      r          
    r-lattice:           0.20_33-r3.3.1_0      r          
    r-mass:              7.3_45-r3.3.1_0       r          
    r-matrix:            1.2_6-r3.3.1_0        r          
    r-mgcv:              1.8_12-r3.3.1_0       r          
    r-nlme:              3.1_128-r3.3.1_0      r          
    r-nnet:              7.3_12-r3.3.1_0       r          
    r-recommended:       3.3.1-r3.3.1_0        r          
    r-rpart:             4.1_10-r3.3.1_0       r          
    r-spatial:           7.3_11-r3.3.1_0       r          
    r-survival:          2.39_4-r3.3.1_0       r          
    readline:            6.2-0                 conda-forge
    setuptools:          29.0.1-py27_1         conda-forge
    sqlite:              3.13.0-1              conda-forge
    tk:                  8.5.19-1              conda-forge
    wheel:               0.29.0-py27_0         conda-forge
    xz:                  5.2.2-0               conda-forge
    yaml:                0.1.6-0               conda-forge
    zlib:                1.2.8-3               conda-forge

/home/greg/miniconda2/conda-bld/0.72_1481028798286/_t_env/bin/.gcc-post-link.sh: line 10: lsb_release: command not found
+ source /home/greg/miniconda2/bin/activate /home/greg/miniconda2/conda-bld/0.72_1481028798286/_t_env
+ /bin/bash -x -e /home/greg/miniconda2/conda-bld/0.72_1481028798286/test_tmp/run_test.sh
+ multigps --version
+ grep MultiGPS
MultiGPS version 0.72
WARNING: please provide chromosome length information in a genome info file (option --geninfo). MultiGPS will attempt to estimate chromosome lengths from data, but this may not work or may not be accurate.
TEST END: multigps-0.72-0
# If you want to upload this package to anaconda.org later, type:
#
# $ anaconda upload /home/greg/miniconda2/conda-bld/linux-64/multigps-0.72-0.tar.bz2
#
# To have conda build upload to anaconda.org automatically, use
# $ conda config --set anaconda_upload yes




####################################################################################
Source and build intermediates have been left in /home/greg/miniconda2/conda-bld.
There are currently 4 accumulated.
To remove them, you can run the ```conda build purge``` command
$ date
Tue Dec  6 07:53:50 EST 2016
```
Here is what I get when I attempt to use simulate_travis.py.  I'll take a look at why it is failing.
```
$ ./simulate-travis.py --packages multigps --loglevel=debug
Traceback (most recent call last):
  File "./simulate-travis.py", line 150, in <module>
    sp.run(['scripts/travis-run.sh'], env=env, universal_newlines=True, check=True)
AttributeError: 'module' object has no attribute 'run'
```

**Comment by gregvonkuster** [comment]
My conda versions is:
```$ conda --version
conda 4.2.13
```

**Comment by gregvonkuster** [comment]
I'm using my own channel for this recipe, so closing.

**Pull request closed without merging**
