### PR TITLE
Update scanpy-scripts to 1.1.1

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`scanpy-scripts`](https://bioconda.github.io/recipes/scanpy-scripts/README.html): **1.1.0** &rarr; **1.1.1**

[install with bioconda](http://bioconda.github.io/recipes/scanpy-scripts/README.html) [Conda](https://anaconda.org/bioconda/scanpy-scripts/files)

Info | Link
-----|-----
Recipe | [`recipes/scanpy-scripts`](https://github.com//bioconda/bioconda-recipes/tree/bump/scanpy_scripts/recipes/scanpy-scripts) (click to view/edit other files)
Releases |[https://pypi.org/pypi/scanpy-scripts/json](https://pypi.org/pypi/scanpy-scripts/json)
Recipe Maintainer(s) | @nh3, @pinin4fjords

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Review by rpetit3 — APPROVED** [review]

**Comment by rpetit3** [comment]
@biocondabot please merge

**Comment by rpetit3** [comment]
@biocondabot please merge

**Comment by pinin4fjords** [comment]
Thanks for fixing this up over the weekend @rpetit3 !

**Comment by pinin4fjords** [comment]
Actually @rpetit3 this hasn't worked quite as I was trying to do (why I had this set as draft)- the installed scanpy version is unpatched. Will submit a PR with a new build when I figure things out...

**Comment by rpetit3** [comment]
Apologies, I totally missed it being set as draft, its pretty subtle.

I wonder if next time, also adding the "do-not-close" or "WIP" label would be helpful. Especially for the folks like myself.

**Pull request merged**
