### PR TITLE
Move additional packages to use perl-threaded

### PR DESCRIPTION
**Pull request by chapmanb**

### CODE REVIEW

**Comment by johanneskoester** [comment]
Can we have one big PR that converts all perl recipes to perl-threaded? This way we could ensure that nothing breaks immediately.

**Comment by chapmanb** [comment]
I'm trying to do the baseline dependencies first then have one more batch to put in that requires some of these to be built. So one more batch, probably tomorrow morning after testing, and we'll be good to go. Does that work?

**Comment by johanneskoester** [comment]
The only problem is: when we see an unsolvable incompatibility in the second batch, do we revert everything?

**Comment by chapmanb** [comment]
I don't expect anything especially problematic. Using perl-threaded only puts compiled shared libraries in a different place (x86_64-linux-thread-multi) instead of (x86_64-linux).  They just need to be in the right place for anything that depends on them to recognize them. No issues so far but definitely can revert if it causes major problems.

**Comment by johanneskoester** [comment]
ok!

**Pull request merged**
