### PR TITLE
Bioconductor deps mirna

### PR DESCRIPTION
**Pull request by daler**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

This bundles together @fabio-cumbo's #5401, #5402, #5403, and #5404 so that we can let the bioconda build system build and test the interdependent packages in the correct order. Hopefully it will save on testing time, and we don't have to worry about merging separate PRs in the correct order.

### CODE REVIEW

**Comment by fabio-cumbo** [comment]
Thanks @daler!

**Comment by daler** [comment]
@fabio-cumbo did you end up submitting a PR to conda-forge for `r-survminer`? Looks like that's what is currently holding up these builds.

**Comment by johanneskoester** [comment]
Why should survminer be on conda-forge? Isn't it bio-related?

**Comment by fabio-cumbo** [comment]
@daler these builds require some packages that I have submitted as PRs on conda-forge: [#3394](https://github.com/conda-forge/staged-recipes/pull/3394), [#3396](https://github.com/conda-forge/staged-recipes/pull/3396), [#3397](https://github.com/conda-forge/staged-recipes/pull/3397), [#3398](https://github.com/conda-forge/staged-recipes/pull/3398), [#3399](https://github.com/conda-forge/staged-recipes/pull/3399), [#3400](https://github.com/conda-forge/staged-recipes/pull/3400), [#3401](https://github.com/conda-forge/staged-recipes/pull/3401), [#3402](https://github.com/conda-forge/staged-recipes/pull/3402), [#3403](https://github.com/conda-forge/staged-recipes/pull/3403), and [#3404](https://github.com/conda-forge/staged-recipes/pull/3404). The last three packages need some of the other packages as dependencies.

**Comment by daler** [comment]
Thanks @fabio-cumbo. @johanneskoester, I think `survminer` is one of those on-the-fence packages. Survival analysis is used in engineering and finance, for example. But of course also used for biology.

**Comment by johanneskoester** [comment]
Good point @daler, I wasn't aware of that!

**Comment by johanneskoester** [comment]
We  have made changes to our build system (migrated from Travis CI to  Circle CI). If you would like to continue working on this PR, please  reopen this PR and update with latest upstream/master.

**Pull request closed without merging**
