### PR TITLE
Update unifrac to 1.3

### PR DESCRIPTION
**Pull request by sfiligoi**
Update unifrac to 1.3.
Adds the python wrappers for the functionality introduced in unifrac-binaries v1.3.

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by sfiligoi** [comment]
@bioconda/core The build if failing because it fails to load the dependencies.
Looks like something changed recently, and there is now strict-channel-priority and bioconda has higher priority than conda-forge.

I can reproduce on the command line the problem with this:
```
conda create --strict-channel-priority --name tst1 -c bioconda -c conda-forge pip 'python 3.8.* *_cpython' 'scipy >=1.9.0' 'numpy >=1.21' 'cython >=0.26' 'h5py <3.0.0|>3.3.0' 'biom-format' 'iow' 'unifrac-binaries >=1.3' 'scikit-bio >=0.5.8' 'python'
```

The following two instead work:
```
conda create --strict-channel-priority --name tst1 -c conda-forge -c bioconda pip 'python 3.8.* *_cpython' 'scipy >=1.9.0' 'numpy >=1.21' 'cython >=0.26' 'h5py <3.03.3.0' 'biom-format' 'iow' 'unifrac-binaries >=1.3' 'scikit-bio >=0.5.8' 'python'
conda create --name tst1 -c bioconda -c conda-forge pip 'python 3.8.* *_cpython' 'scipy >=1.9.0' 'numpy >=1.21' 'cython >=0.26' 'h5py <3.0.0|>3.3.0' 'biom-format' 'iow' 'unifrac-binaries >=1.3' 'scikit-bio >=0.5.8' 'python'
```

I tried to work around it, but cannot find anything that would work.

Note that the same recipe worked in the past.

**Comment by dpryan79** [comment]
The current error is unrelated and being worked on in parallel.

**Comment by dpryan79** [comment]
For what it's worth, we used this in our core-team meeting today, so you've had at least 4 core team members helping to debug things :)

**Comment by sfiligoi** [comment]
@dpryan79 Why was the dependency of h5py changed?

**Comment by sfiligoi** [comment]
@dpryan79 I see the tests have finally passed :)
What is the procedure now?

**Comment by johanneskoester** [comment]
I'll take care of persisting these changes in the build system this morning.

**Comment by dpryan79** [comment]
@johanneskoester Thanks, do you want to clean up this PR when that's finished or shall I?

@sfiligoi We need to give our infrastructure a bit of TLC and then this can get merged.

**Comment by johanneskoester** [comment]
I will do!

**Review by dpryan79 — APPROVED** [review]

**Pull request merged**
