### PR TITLE
Add libsbml recipe

### PR DESCRIPTION
**Pull request by vivekiitkgp**
Wonder how it wasn't there already.

Signed-off-by: Vivek Rai <vivekraiiitkgp@gmail.com>

### CODE REVIEW

**Comment by vivekiitkgp** [comment]
@johanneskoester I included libxml2 as a build requirement. Why should it fail for a libxml error now? Can you please have a look?

**Comment by johanneskoester** [comment]
Gcc does not see the headers because it does not look inside miniconda by default. You need to add the conda gcc and libgcc as requirements and point to these in the build.sh. See [this recipe](https://github.com/bioconda/bioconda-recipes/tree/6466d74e35358bce1a77e9e11724cb23252d9a0d/recipes/daligner).

**Comment by vivekiitkgp** [comment]
@johanneskoester I have a feeling that the issue is much deeper. The build fails because the `setup.py` script hard codes the `include` and `lib` file locations, making it difficult to distribute and configure the compilation. This seems like an upstream problem. What should I do?

**Comment by johanneskoester** [comment]
If the include and lib locations are hardcoded, I would fork the project and fix the setup.py. You can then create a pull request for upstream. If you need the package urgently, you can in the meantime use the git url of the fork in the recipe. Alternatively, you can just crate a patch for the setup.py and add the patch to the meta.yaml such that conda applies it before compilation.

**Comment by vivekiitkgp** [comment]
@johanneskoester Fixed. Ready to go.

**Pull request merged**
