### PR TITLE
Quote filenames in curesim, use openjdk

### PR DESCRIPTION
**Pull request by peterjc**
* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [X] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [X] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

The quote change is extracted from #8222, with the Java changed suggested by the linting checks run on that pull request.

### CODE REVIEW

**Comment by karel-brinda** [comment]
@peterjc Thank you for the patch!

**Comment by peterjc** [comment]
Thanks @karel-brinda - I wasn't sure if the Java change would break things or not.

Still, we should get the CircleCI checks to pass before merging this...

**Comment by karel-brinda** [comment]
@peterjc I did some preliminary testing on my laptop and it seemed to work. I will finish testing, once the package is built.

**Comment by dpryan79** [comment]
@bioconda-bot update

**Comment by dpryan79** [comment]
@bioconda-bot merge

**Comment by dpryan79** [comment]
Thanks @peterjc!

**Comment by peterjc** [comment]
Good work- I’d forgotten about this PR, thanks

**Pull request merged**
