### PR TITLE
updates bwakit to 0.7.15

### PR DESCRIPTION
**Pull request by bwlang**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by bwlang** [comment]
thought this would be a simple update... seems to have downloaded ok - not sure how to interpret this failure.

**Comment by bgruening** [comment]
Nothing obvious that I can see, maybe the test is really failing because the binary changed?

**Comment by bwlang** [comment]
@bgruening 
This test is trivial... just checks that the tools produces a Usage statement when run with no options.

run-bwamem 2>&1 | grep 'Usage:   run-bwamem'

this produces 
```
Usage:   run-bwamem [options] <idxbase> <file1> [file2]
```
on my system for the old and the tar.bz2 file
could this be related to the circleci update?

**Comment by bgruening** [comment]
Have you tested the new output of the binary? Maybe the text has changed, more white spaces?

**Comment by bwlang** [comment]
@bgruening  I can't see any difference in the output, whitespace or otherwise 
```
langhorst@seq-himem01-i:/tmp/bwa.kit.0715$ ./run-bwamem 2>&1 | grep 'Usage:   run-bwamem' && echo 'pass'
Usage:   run-bwamem [options] <idxbase> <file1> [file2]
pass
langhorst@seq-himem01-i:/tmp/bwa.kit.0715$ /home/NEB/langhorst/miniconda3/bin/run-bwamem 2>&1 | grep 'Usage:   run-bwamem' && echo 'pass'
Usage:   run-bwamem [options] <idxbase> <file1> [file2]
pass
```

**Comment by mbargull** [comment]
`run-bwamem` is a Perl script, hence you need to add `perl` to `requirements/run`. Also, maybe change the test like
```diff
-     - "run-bwamem 2>&1 | grep 'Usage:   run-bwamem'"
+     - 'run-bwamem 2>&1 | grep "Usage:   run-bwamem"'
```
to avoid a failure in a subsequent test run that isn't fully compatible with single quote-containing strings.

**Comment by cbrueffer** [comment]
Merged, thanks!

**Pull request merged**
