### PR TITLE
linux-aarch64 build for pybedtools

### PR DESCRIPTION
**Pull request by huazhong28**
Describe your pull request here

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

### General instructions

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

### Instructions for avoiding API, ABI, and CLI breakage issues
Conda is able to record and lock (a.k.a. pin) dependency versions used at build time of other recipes.
This way, one can avoid that expectations of a downstream recipe with regards to API, ABI, or CLI are violated by later changes in the recipe.
If not already present in the meta.yaml, make sure to specify `run_exports` (see [here](https://bioconda.github.io/contributor/linting.html#missing-run-exports) for the rationale and comprehensive explanation).
Add a `run_exports` section like this:

```yaml
build:
  run_exports:
    - ...

```

with `...` being one of:

| Case                             | run_exports statement                                               |
| -------------------------------- | ------------------------------------------------------------------- |
| semantic versioning              | `{{ pin_subpackage("myrecipe", max_pin="x") }}`     |
| semantic versioning (0.x.x)      | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}`   |
| known breakage in minor versions | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| known breakage in patch versions | `{{ pin_subpackage("myrecipe", max_pin="x.x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| calendar versioning              | `{{ pin_subpackage("myrecipe", max_pin=None) }}`    |

while replacing `"myrecipe"` with either `name` if a `name|lower` variable is defined in your recipe or with the lowercase name of the package in quotes.

### Bot commands for PR management

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

Note that the <code>@BiocondaBot please merge</code> command is now depreciated. Please just squash and merge instead.

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Review by thanhleviet — APPROVED** [review]

**Comment by martin-g** [comment]
@BiocondaBot please fetch artifacts

**Comment by martin-g** [comment]
```
❯ tar jxvf pybedtools-0.9.1-py39h848f94e_1.tar.bz2                                                                                                                                                     (font-ubuntu) 
info/run_exports.json
info/test/run_test.py
info/test/run_test.sh
info/recipe/0.6.9/build.sh
info/hash_input.json
info/recipe/build.sh
info/index.json
info/recipe/0.6.9/meta.yaml
info/recipe/meta.yaml.template
info/recipe/meta.yaml
info/recipe/conda_build_config.yaml
info/files
info/about.json
info/paths.json
info/git
lib/python3.9/site-packages/pybedtools/test/data/exons.gff
lib/python3.9/site-packages/pybedtools/test/data/d.gff
lib/python3.9/site-packages/pybedtools/test/data/gdc.gff
lib/python3.9/site-packages/pybedtools/test/data/c.gff
lib/python3.9/site-packages/pybedtools/test/data/hg19.gff
lib/python3.9/site-packages/pybedtools/test/data/democonfig.yaml
lib/python3.9/site-packages/pybedtools/version.py
lib/python3.9/site-packages/pybedtools/contrib/__init__.py
lib/python3.9/site-packages/pybedtools/logger.py
lib/python3.9/site-packages/pybedtools/test/__init__.py
lib/python3.9/site-packages/pybedtools/test/tfuncs.py
lib/python3.9/site-packages/pybedtools/paths.py
lib/python3.9/site-packages/pybedtools/stats.py
lib/python3.9/site-packages/pybedtools/test/test_pathlib.py
lib/python3.9/site-packages/pybedtools/test/regression_tests.py
lib/python3.9/site-packages/pybedtools/filenames.py
lib/python3.9/site-packages/pybedtools/test/test_len_leak.py
lib/python3.9/site-packages/pybedtools/test/genomepy_integration.py
lib/python3.9/site-packages/pybedtools/contrib/bigbed.py
lib/python3.9/site-packages/pybedtools/settings.py
lib/python3.9/site-packages/pybedtools/test/test_gzip_support.py
lib/python3.9/site-packages/pybedtools/__init__.py
lib/python3.9/site-packages/pybedtools/test/test_helpers.py
lib/python3.9/site-packages/pybedtools/test/test_contrib.py
lib/python3.9/site-packages/pybedtools/contrib/bigwig.py
lib/python3.9/site-packages/pybedtools/test/test_iter.py
lib/python3.9/site-packages/pybedtools/contrib/intersection_matrix.py
lib/python3.9/site-packages/pybedtools/contrib/venn_maker.py
lib/python3.9/site-packages/pybedtools/parallel.py
lib/python3.9/site-packages/pybedtools/test/test_cbedtools.py
lib/python3.9/site-packages/pybedtools/contrib/long_range_interaction.py
lib/python3.9/site-packages/pybedtools/contrib/plotting.py
lib/python3.9/site-packages/pybedtools/helpers.py
lib/python3.9/site-packages/pybedtools/test/test_issues.py
lib/python3.9/site-packages/pybedtools/test/test_1.py
lib/python3.9/site-packages/pybedtools/test/data/__init__.py
lib/python3.9/site-packages/pybedtools/genome_registry.py
lib/python3.9/site-packages/pybedtools/bedtool.py
lib/python3.9/site-packages/pybedtools/test/data/genome.fa
lib/python3.9/site-packages/pybedtools/test/data/test.fa
lib/python3.9/site-packages/pybedtools/test/data/example.narrowPeak
lib/python3.9/site-packages/pybedtools/test/data/1000genomes-example.vcf
lib/python3.9/site-packages/pybedtools/test/data/v.vcf
lib/python3.9/site-packages/pybedtools/test/data/vcf-stderr-test.vcf
lib/python3.9/site-packages/pybedtools/test/data/mm9.bed12
lib/python3.9/site-packages/pybedtools/test/data/small.fastq
lib/python3.9/site-packages/pybedtools/test/data/164.gtf
lib/python3.9/site-packages/pybedtools/test/data/gdc.1.100.bam
lib/python3.9/site-packages/pybedtools/test/data/gdc.50.200.bam
lib/python3.9/site-packages/pybedtools/test/data/gdc.sorted.bam
lib/python3.9/site-packages/pybedtools/test/data/gdc.bam
lib/python3.9/site-packages/pybedtools/test/data/gdc.othersort.bam
lib/python3.9/site-packages/pybedtools/test/data/reads.bam
lib/python3.9/site-packages/pybedtools/test/data/issue_121.bam
lib/python3.9/site-packages/pybedtools/test/data/small.bam
lib/python3.9/site-packages/pybedtools/test/data/y.bam
lib/python3.9/site-packages/pybedtools/test/data/x.bam
lib/python3.9/site-packages/pybedtools/featurefuncs.cpython-39-aarch64-linux-gnu.so
lib/python3.9/site-packages/pybedtools/cbedtools.cpython-39-aarch64-linux-gnu.so
lib/python3.9/site-packages/pybedtools-0.9.1-py3.9.egg-info/not-zip-safe
lib/python3.9/site-packages/pybedtools-0.9.1-py3.9.egg-info/PKG-INFO
lib/python3.9/site-packages/pybedtools/test/data/hg38-base.bed
lib/python3.9/site-packages/pybedtools/test/data/tag_test1.bed
lib/python3.9/site-packages/pybedtools/test/data/tag_test2.bed
lib/python3.9/site-packages/pybedtools/test/data/test_peaks.bed
lib/python3.9/site-packages/pybedtools/test/data/multibamcov_test.bed
lib/python3.9/site-packages/pybedtools/test/data/hg38-problem.bed
lib/python3.9/site-packages/pybedtools/test/data/m1.bed
lib/python3.9/site-packages/pybedtools/test/data/test_tsses.bed
lib/python3.9/site-packages/pybedtools/test/data/b.bed
lib/python3.9/site-packages/pybedtools/test/data/expand_test.bed
lib/python3.9/site-packages/pybedtools/test/data/test_bedpe.bed
lib/python3.9/site-packages/pybedtools/test/data/vcf-stderr-test.bed
lib/python3.9/site-packages/pybedtools/test/data/a.bed
lib/python3.9/site-packages/pybedtools/test/data/bedpe2.bed
lib/python3.9/site-packages/pybedtools/test/data/bedpe.bed
lib/python3.9/site-packages/pybedtools/test/data/issue319.bed
lib/python3.9/site-packages/pybedtools/test/data/gdc.bed
lib/python3.9/site-packages/pybedtools/test/data/venn.b.bed
lib/python3.9/site-packages/pybedtools/test/data/venn.c.bed
lib/python3.9/site-packages/pybedtools/test/data/rmsk.hg18.chr21.small.bed
lib/python3.9/site-packages/pybedtools/test/data/CTCF_Kc_Bushey_2009.bed
lib/python3.9/site-packages/pybedtools/test/data/CTCF_Mbn2_Bushey_2009.bed
lib/python3.9/site-packages/pybedtools/test/data/BEAF_Kc_Bushey_2009.bed
lib/python3.9/site-packages/pybedtools/test/data/BEAF_Mbn2_Bushey_2009.bed
lib/python3.9/site-packages/pybedtools/test/data/SuHw_Mbn2_Bushey_2009.bed
lib/python3.9/site-packages/pybedtools/test/data/SuHw_Kc_Bushey_2009.bed
lib/python3.9/site-packages/pybedtools/test/data/Cp190_Mbn2_Bushey_2009.bed
lib/python3.9/site-packages/pybedtools/test/data/Cp190_Kc_Bushey_2009.bed
lib/python3.9/site-packages/pybedtools/test/data/issue319.out.bed
lib/python3.9/site-packages/pybedtools/test/data/x.bed
lib/python3.9/site-packages/pybedtools/include/fileType.cpp
lib/python3.9/site-packages/pybedtools/include/gzstream.cpp
lib/python3.9/site-packages/pybedtools/include/bedFile.cpp
lib/python3.9/site-packages/pybedtools/featurefuncs.cpp
lib/python3.9/site-packages/pybedtools/cbedtools.cpp
lib/python3.9/site-packages/pybedtools/test/data/a.bed.gz.tbi
lib/python3.9/site-packages/pybedtools/cbedtools.pxd
lib/python3.9/site-packages/pybedtools/test/data/a.links.html
lib/python3.9/site-packages/pybedtools/test/data/a.bed.gz
lib/python3.9/site-packages/pybedtools/test/data/gdc.gff.gz
lib/python3.9/site-packages/pybedtools/test/data/1000genomes-example.vcf.gz
lib/python3.9/site-packages/pybedtools/test/data/rmsk.hg18.chr21.small.bed.gz
lib/python3.9/site-packages/pybedtools/test/data/issue319.vcf.gz
lib/python3.9/site-packages/pybedtools/test/data/dm3-chr2L-5M.gff.gz
lib/python3.9/site-packages/pybedtools/test/data/dm3-chr2L-5M-invalid.gff.gz
lib/python3.9/site-packages/pybedtools/test/data/snps.bed.gz
lib/python3.9/site-packages/pybedtools/test/data/test.fa.fai
lib/python3.9/site-packages/pybedtools/_Window.pyx
lib/python3.9/site-packages/pybedtools/featurefuncs.pyx
lib/python3.9/site-packages/pybedtools/cbedtools.pyx
lib/python3.9/site-packages/pybedtools/test/data/gdc.sorted.bam.bai
lib/python3.9/site-packages/pybedtools/test/data/gdc.1.100.bam.bai
lib/python3.9/site-packages/pybedtools/test/data/gdc.50.200.bam.bai
lib/python3.9/site-packages/pybedtools/test/data/gdc.cram
lib/python3.9/site-packages/pybedtools/test/data/a.igv_script
lib/python3.9/site-packages/pybedtools-0.9.1-py3.9.egg-info/dependency_links.txt
lib/python3.9/site-packages/pybedtools-0.9.1-py3.9.egg-info/top_level.txt
lib/python3.9/site-packages/pybedtools-0.9.1-py3.9.egg-info/requires.txt
lib/python3.9/site-packages/pybedtools-0.9.1-py3.9.egg-info/SOURCES.txt
lib/python3.9/site-packages/pybedtools/test/data/__pycache__/__init__.cpython-39.pyc
lib/python3.9/site-packages/pybedtools/__pycache__/version.cpython-39.pyc
lib/python3.9/site-packages/pybedtools/contrib/__pycache__/__init__.cpython-39.pyc
lib/python3.9/site-packages/pybedtools/__pycache__/logger.cpython-39.pyc
lib/python3.9/site-packages/pybedtools/test/__pycache__/__init__.cpython-39.pyc
lib/python3.9/site-packages/pybedtools/test/__pycache__/tfuncs.cpython-39.pyc
lib/python3.9/site-packages/pybedtools/__pycache__/paths.cpython-39.pyc
lib/python3.9/site-packages/pybedtools/test/__pycache__/regression_tests.cpython-39.pyc
lib/python3.9/site-packages/pybedtools/test/__pycache__/test_pathlib.cpython-39.pyc
lib/python3.9/site-packages/pybedtools/__pycache__/stats.cpython-39.pyc
lib/python3.9/site-packages/pybedtools/__pycache__/settings.cpython-39.pyc
lib/python3.9/site-packages/pybedtools/test/__pycache__/test_len_leak.cpython-39.pyc
lib/python3.9/site-packages/pybedtools/__pycache__/filenames.cpython-39.pyc
lib/python3.9/site-packages/pybedtools/test/__pycache__/genomepy_integration.cpython-39.pyc
lib/python3.9/site-packages/pybedtools/contrib/__pycache__/bigbed.cpython-39.pyc
lib/python3.9/site-packages/pybedtools/test/__pycache__/test_contrib.cpython-39.pyc
lib/python3.9/site-packages/pybedtools/test/__pycache__/test_gzip_support.cpython-39.pyc
lib/python3.9/site-packages/pybedtools/__pycache__/__init__.cpython-39.pyc
lib/python3.9/site-packages/pybedtools/contrib/__pycache__/bigwig.cpython-39.pyc
lib/python3.9/site-packages/pybedtools/test/__pycache__/test_helpers.cpython-39.pyc
lib/python3.9/site-packages/pybedtools/test/__pycache__/test_iter.cpython-39.pyc
lib/python3.9/site-packages/pybedtools/contrib/__pycache__/venn_maker.cpython-39.pyc
lib/python3.9/site-packages/pybedtools/__pycache__/parallel.cpython-39.pyc
lib/python3.9/site-packages/pybedtools/contrib/__pycache__/intersection_matrix.cpython-39.pyc
lib/python3.9/site-packages/pybedtools/test/__pycache__/test_cbedtools.cpython-39.pyc
lib/python3.9/site-packages/pybedtools/contrib/__pycache__/long_range_interaction.cpython-39.pyc
lib/python3.9/site-packages/pybedtools/contrib/__pycache__/plotting.cpython-39.pyc
lib/python3.9/site-packages/pybedtools/__pycache__/helpers.cpython-39.pyc
lib/python3.9/site-packages/pybedtools/test/__pycache__/test_issues.cpython-39.pyc
lib/python3.9/site-packages/pybedtools/test/__pycache__/test_1.cpython-39.pyc
lib/python3.9/site-packages/pybedtools/__pycache__/genome_registry.cpython-39.pyc
lib/python3.9/site-packages/pybedtools/__pycache__/bedtool.cpython-39.pyc

 file lib/python3.9/site-packages/pybedtools/*.so                                                                                                                                                     (font-ubuntu) 
lib/python3.9/site-packages/pybedtools/cbedtools.cpython-39-aarch64-linux-gnu.so:    ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, not stripped
lib/python3.9/site-packages/pybedtools/featurefuncs.cpython-39-aarch64-linux-gnu.so: ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, not stripped
```

Looks good to me!

**Comment by martin-g** [comment]
@BiocondaBot please add label

**Comment by bgruening** [comment]
Cool, thanks!

**Pull request merged**
