### PR TITLE
Bump/gembs to 3.5.0

### PR DESCRIPTION
**Pull request by JakeLehle**
Bump gembs version to 3.5.0

### CODE REVIEW

**Comment by JakeLehle** [comment]
Lint is throwing an error message that the version improvements should be incremental when they are not. This pull is to update the gembs branch to 3.5.0 from 3.2.2 and the build number in the meta.yaml on line 17 is set to 0 so I don't know why this error is getting thrown. 

image


Can someone check this and push it through if possible 
@bioconda/core 
I'm the one who created the pull request but Azure is not letting me rerun the test even though I have the same email address.

Thank you,
Jake

**Comment by druvus** [comment]
@BiocondaBot please update

**Comment by JakeLehle** [comment]
@druvus @bioconda/core

Looks like lint stopped this update at the same part again. Should I try and modify the file and update the pull request? 
I still can't figure out why the base being set to 0 isn't working, It should go through.

Thanks,
Jake

**Comment by dpryan79** [comment]
Hmm, looks like the branch update got a bit weird here. I've made the needed change in the original branch so this should presumably be resolved now. @JakeLehle shall I add you to bioconda so you can directly make changes on PRs in the future?

**Comment by JakeLehle** [comment]
Hey @dpryan79 thank you so much!
Yes, please add me to bioconda. I'd be happy to help researchers/users maintain and update packages for community use going forward.

Best,
Jake

**Comment by dpryan79** [comment]
Invite sent!

**Pull request merged**
