### PR TITLE
update vsearch to 2.2.0

### PR DESCRIPTION
**Pull request by colinbrislawn**
- [x] I have read the guidelines above.
- [ ] This PR adds a new recipe.
- [x] This PR updates an existing recipe.
- [ ] This PR does something else (explain below).

I understand that the structure of bioconda is being updated, and I'm willing to improve this recipe to meet the new and improved standards for PRs.

Thanks!!

### CODE REVIEW

**Comment by bgruening** [comment]
@tomkinsc @colinbrislawn I have tried to update the last version as well and got to a point were I needed to add perl as build dependency. Now I'm stuck here: https://travis-ci.org/bioconda/bioconda-recipes/jobs/166058650#L491

**Comment by tomkinsc** [comment]
@bgruening: autoreconf should not need perl, or am I wrong? This appears similar to the [issue](https://travis-ci.org/bioconda/bioconda-recipes/jobs/163859124#L506) I was having with fastqc, which does not explicitly have perl as a dependency. I closed [that PR](https://github.com/bioconda/bioconda-recipes/pull/2460) until I had time to address it, but perhaps it is indicative of a more pressing issue. Is this a placeholder/prefix issue somehow?

**Comment by bgruening** [comment]
@tomkinsc I don't know. I can not imagine that this is a placeholder issue and something seems to need perl here :( I would not be surprised it autoreconf needs perl.

**Comment by bgruening** [comment]
@tomkinsc here is another one: https://github.com/bioconda/bioconda-recipes/pull/2472 :(

**Comment by colinbrislawn** [comment]
I don't know if I am enough of a git master to get this merged. I may just close this, then submit a new PR based on the current master branch... 

Thanks for all your feedback folks! This really helps me.

**Comment by zachcp** [comment]
Hi @colinbrislawn ,

 I've updated vsearch to 2.3.1 in #2978. Saw this after the pull; didn't mean to 'cut your lunch'!

zcp

**Comment by colinbrislawn** [comment]
@zachcp No worries. Glad we got this fixed!

**Pull request closed without merging**
