### PR TITLE
Add the EGA v2 client

### PR DESCRIPTION
**Pull request by pinin4fjords**
Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it. Note that if you are not already a member of the bioconda project (meaning that you can't add this label), please ping `@bioconda/core` so that your PR can be reviewed and merged (please note if you'd like to be added to the bioconda project). Please see https://github.com/bioconda/bioconda-recipes/issues/15332 for more details.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

The European Genome/ Phenome archive seems to have two clients right now, the v3 (available via @AlexanderVi 's pyega3 recipe), and the v2, which is a less friendly .jar. The v2 is still required for downloading files in some datasets which the v3 client does not, but the jar file makes things fiddly. and difficult to integrate into workflows. This package just provides the .jar and adds a wrapper script to make command-line usage easier. It borrows heavily from the peptideshaker recipe in way it wraps the .jar. Seem sensible to you @AlexanderVi ?

Issues:

-  absence of proper tests. I haven't been able to identify a good test command that can be run without providing credentials and logging in. 
- licensing: I haven't been able to find a license associated with the v2 client download

### CODE REVIEW

**Comment by dpryan79** [comment]
Maybe there's a way to have the jar file print out some help? That's probably the best the test could be.

**Comment by pinin4fjords** [comment]
@dpryan79 I don't think so. The standard help at least seems to require username and password.

**Comment by pinin4fjords** [comment]
Ahh- 'unknown' for license- didn't know that one. Thanks!

**Comment by pinin4fjords** [comment]
Thanks for another fix @dpryan79 - you're so quick!

**Comment by dpryan79** [comment]
It seems to be a purely interactive client, is there actually a way to script with it?

**Comment by pinin4fjords** [comment]
yep, you can do everything non-interactively as well (see 'command line' vs 'interactive client' tabs here: https://ega-archive.org/download/downloader-quickguide-v2)

**Comment by dpryan79** [comment]
Something like that test should work. Once the bot is back up it'd be good to test that the wrapper actually works in a coherent way.

**Comment by pinin4fjords** [comment]
I did try that when I was composing the tests in the first place, but couldn't find a way to make it work without a valid login. 

So while this works to print the help:

```
ega2 -p <user> <password> -help
```

... these do not:

```
ega2 -p foo@bar.com 123456 -help
```

```
ega2 -p -help
```

... and produce null pointer exceptions.

The wrapper does work with my login to do actual things. e.g. 

```
 ega2 -p <user> <password> -lfd  EGAD00001003145
```

... lists the files of an experiment.

**Comment by dpryan79** [comment]
That's good enough for me then, let's merge this.

**Comment by pinin4fjords** [comment]
great- thanks @dpryan79

**Pull request merged**
