### PR TITLE
updated jellyfish to 2.2.6

### PR DESCRIPTION
**Pull request by fretn**
* [X] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [X] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by bgruening** [comment]
Travis seems to hang I will close and reopen to trigger a test.
Thanks for your contribution.

**Comment by fretn** [comment]
okay it works :)

can you merge this ?

**Comment by bgruening** [comment]
Sure! If you want to become part of the team let us know :)
https://github.com/bioconda/bioconda-recipes/issues/1

**Comment by fretn** [comment]
Thanks. I Will let you know. It was a test to see how it works, if we switch to conda for our bioinformatics environment I'll definiatly become a member. 

Cheers

**Pull request merged**
