### PR TITLE
trnanalysis

### PR DESCRIPTION
**Pull request by Acribbs**
Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it. Note that if you are not already a member of the bioconda project (meaning that you can't add this label), please ping `@bioconda/core` so that your PR can be reviewed and merged (please note if you'd like to be added to the bioconda project). Please see https://github.com/bioconda/bioconda-recipes/issues/15332 for more details.

* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [X] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [X] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by npavlovikj** [comment]
@Acribbs , I was wondering why the recipe requires compiliers? It looks like a pure Python package to me... If the compilers are not needed, then the package can be "noarch".

**Comment by npavlovikj** [comment]
In this case, please make the recipe "noarch", e.g.:
```
build:
  number: 1
  noarch: python
```

And then you will have `python >=3` in both `host` and `run` sections.

**Comment by npavlovikj** [comment]
Since no compilers are used, I don't think exporting the flags in `build.sh` is needed either, but I will let you decide that :)

**Comment by npavlovikj** [comment]
@BiocondaBot merge

**Comment by npavlovikj** [comment]
@Acribbs , next time you modify the recipe, you can consider adding yourself as a maintainer and add a doi tag for the paper if one exists.

**Comment by Acribbs** [comment]
Thanks @npavlovikj! Will add both maintainer and doi next time.

**Pull request merged**
