### PR TITLE
Update zga to 0.1.0

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`zga`](https://bioconda.github.io/recipes/zga/README.html): **0.0.9.post2** &rarr; **0.1.0**

[install with bioconda](http://bioconda.github.io/recipes/zga/README.html) [Conda](https://anaconda.org/bioconda/zga/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/zga`](https://github.com//bioconda/bioconda-recipes/tree/bump/zga/recipes/zga) (click to view/edit other files)
Summary | Prokaryotic genome assembly and annotation pipeline
Home | [https://github.com/laxeye/zga](https://github.com/laxeye/zga)
Releases |[https://pypi.org/pypi/zga/json](https://pypi.org/pypi/zga/json)
Recipe Maintainer(s) | @laxeye

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Review by matthdsm — APPROVED** [review]
@BiocondaBot please merge

**Comment by laxeye** [comment]
@mjsteinbaugh Michael, are there any problems with the new version? Should I do anything now?

**Review by mjsteinbaugh — APPROVED** [review]

**Comment by mjsteinbaugh** [comment]
@BiocondaBot please merge

**Comment by mjsteinbaugh** [comment]
@laxeye Not sure why this isn't merging -- I'll take a look later today

**Comment by laxeye** [comment]
@mjsteinbaugh Thank You!

**Comment by mjsteinbaugh** [comment]
@BiocondaBot please merge

**Pull request merged**
