### PR TITLE
biopython: 1.69

### PR DESCRIPTION
**Pull request by saketkc**
* [x] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by bgruening** [comment]
Mh, we got a segmentation fault :(

**Comment by daler** [comment]
@saketkc @peterjc after some debugging it looks like `Bio.SVDSuperImposer` is causing the segfault, likely because of missing dependencies.

**Comment by peterjc** [comment]
OK, that's interesting. The recipe does list ``numpy`` as a build requirement so that puzzles me. Any more details?

**Comment by daler** [comment]
The conda-build command runs fine, but it was the mulled-build test that was segfaulting. That runs in a minimal docker container. I ran that container interactively and tried running every `import` test. Turns out `python -c "import Bio.SVDSuperimposer"` triggered the segfault.

I just looked at the source for that module, it's not doing anything crazy. So in that same container I tried `python -c "import numpy"` and that segfaulted. Numpy is the culprit.

@dpryan79 I think I remember you fighting with numpy segfaults a while ago, do you have any suggestions to try?

**Comment by daler** [comment]
@dpryan79 never mind, I found that PR: https://github.com/bioconda/bioconda-recipes/pull/3048#issuecomment-262927140

**Comment by peterjc** [comment]
@saketkc that license change will likely fail, under Biopython 1.69 the ``LICENSE`` file is just a symlink to ``LICENSE.rst``

See more detailed explanation in my pull request #4404 which would fix Biopython 1.68 first.

**Comment by saketkc** [comment]
@peterjc Just fixed!

**Comment by saketkc** [comment]
I have skipped building on `python 3.4` for now. I will go ahead and merge this for now if there are no objections.

**Comment by daler** [comment]
@saketkc go for it. I don't know of a clear path for fixing the 3.4 issue so it could be a while if we wait for that to be resolved.

**Comment by saketkc** [comment]
@peterjc Are you happy with the `license` related changes?

**Comment by dpryan79** [comment]
@daler: My only "fix" has been to skip testing on python3.4.

**Comment by peterjc** [comment]
No. If this is going to be a release for Biopython 1.69, then we need:

```
license_file: LICENSE.rst
```

(We renamed the file, it was ``LICENSE`` up to and including Biopython 1.68, but from Biopython 1.69 onwards it is ``LICENSE.rst`` instead).

However, separate from this, my preference is to fix the Biopython 1.68 recipe first (otherwise the old recipe with the incorrect license will persist in the bioconda archive), i.e. merge #4404 and release it, then apply this pull request.

**Pull request merged**
