### PR TITLE
HUMAnN2 requires diamond<0.9.0

### PR DESCRIPTION
**Pull request by richardjdavies**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

See requirements section at http://huttenhower.sph.harvard.edu/humann2

### CODE REVIEW

**Comment by richardjdavies** [comment]
See requirements section at http://huttenhower.sph.harvard.edu/humann2

With diamond >=0.9.0, I get `Error: Database was built with a different version of diamond as is incompatible.`

**Comment by bgruening** [comment]
@richardjdavies you need to increase the build/number by one. So that we get a new package.

**Comment by richardjdavies** [comment]
Good point - additional commit coming now...

**Comment by daler** [comment]
Thanks @richardjdavies!

**Pull request merged**
