### PR TITLE
fwdpy11 bump to 0.4.5

### PR DESCRIPTION
**Pull request by molpopgen**
Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it. Note that if you are not already a member of the bioconda project (meaning that you can't add this label), please ping `@bioconda/core` so that your PR can be reviewed and merged (please note if you'd like to be added to the bioconda project). Please see https://github.com/bioconda/bioconda-recipes/issues/15332 for more details.

* [ ] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [ ] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by molpopgen** [comment]
> Can you please add the citation to the recipe? This will give us some more power to spread the news :)

To the bioconda paper?  Sure.

**Comment by molpopgen** [comment]
> Can you please add the citation to the recipe? This will give us some more power to spread the news :)

@bgruening  -- is there an example anywhere?  I'm googling for "conda metadata citation field" and coming up empty.  Likewise, grepping through existing recipes in the current master isn't turning up examples.

**Comment by bgruening** [comment]
Oh no I mean your paper :)
As seen here: https://github.com/bioconda/bioconda-recipes/blob/d5df34272d13941db5b19a890b510422ec08bc59/recipes/intarna/meta.yaml#L39

**Comment by molpopgen** [comment]
Ah, gotcha.  There's not a fwdpy11-specific paper yet, but I can add the fwdpp paper.

**Pull request merged**
