### PR TITLE
proposal to add bcalm software

### PR DESCRIPTION
**Pull request by rchikhi**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

Attempts to re-vive bcalm from https://github.com/bioconda/bioconda-recipes/pull/1951

### CODE REVIEW

**Comment by bgruening** [comment]
@rchikhi why is this a re-add?
Looks good to me, do you think we should create a new package for the subpackage which you are cloning here?

**Comment by rchikhi** [comment]
"re-add" because it was previously attempted to be added then removed in this PR https://github.com/bioconda/bioconda-recipes/pull/1951

what do you mean by "subpackage that your are cloning"? I'm not familiar with conda terminology

**Comment by bgruening** [comment]
This one here: https://github.com/bioconda/bioconda-recipes/pull/8750/files#diff-a324caac488461278b34a2d28d3d3123R9 do we need a extra package for it?

**Comment by rchikhi** [comment]
oh I see, thanks for the clarification.

Due to ancien design choices, bcalm and its build system expects that `gatb-core` is precisely at the directory where it is cloned. I'm afraid that many non-trivial things in the CMakeFile would need to be changed in gatb-core was moved as an independent package,

**Comment by rchikhi** [comment]
changed title

**Comment by rchikhi** [comment]
Hmm I wanted to update bioconda-recipes with most recent commits, probably did mess up the merge since the PR included all those commits. Will close the pull request and open another one

**Pull request closed without merging**
