### PR TITLE
Add meta.yaml for new recipe aligncov

### PR DESCRIPTION
**Pull request by pcrxn**
Add meta.yaml for new recipe aligncov

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

Note that the <code>@BiocondaBot please merge</code> command is now depreciated. Please just squash and merge instead.

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by pcrxn** [comment]
@bioconda/core Could you please help me with debugging this build log ([aligncov-build.log](https://github.com/bioconda/bioconda-recipes/files/12336434/aligncov-build.log))?

When I run `bioconda-utils build --docker --mulled-test --packages aligncov` locally, I receive the following error:

```
10:36:40 BIOCONDA INFO BUILD START recipes/aligncov
Updating build index: /home/liam/miniconda3/envs/bioconda/conda-bld

10:36:40 BIOCONDA INFO (COMMAND) docker run -t --net host --rm -v /tmp/tmp7otrfn06/build_script.bash:/opt/build_script.bash -v /home/liam/miniconda3/envs/bioconda/conda-bld/:/opt/host-conda-bld -v /home/liam/Desktop/bioconda-recipes/recipes/aligncov:/opt/recipe -e LANG=en_CA.UTF-8 -e HOST_USER_ID=1000 quay.io/bioconda/bioconda-utils-build-env-cos7:2.3.4 /bin/bash /opt/build_script.bash
10:36:40 BIOCONDA ERROR COMMAND FAILED (exited with 125): docker run -t --net host --rm -v /tmp/tmp7otrfn06/build_script.bash:/opt/build_script.bash -v /home/liam/miniconda3/envs/bioconda/conda-bld/:/opt/host-conda-bld -v /home/liam/Desktop/bioconda-recipes/recipes/aligncov:/opt/recipe -e LANG=en_CA.UTF-8 -e HOST_USER_ID=1000 quay.io/bioconda/bioconda-utils-build-env-cos7:2.3.4 /bin/bash /opt/build_script.bash
10:36:40 BIOCONDA ERROR STDOUT+STDERR:
docker: Error response from daemon: Mounts denied:
The path /tmp/tmp7otrfn06/build_script.bash is not shared from the host and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> Resources -> File Sharing.
See https://docs.docker.com/ for more info.
time="2023-08-14T10:36:40-04:00" level=error msg="error waiting for container: "

10:36:40 BIOCONDA ERROR BUILD FAILED recipes/aligncov
10:36:40 BIOCONDA INFO (COMMAND) conda build purge
10:36:41 BIOCONDA ERROR BUILD SUMMARY: of 1 recipes, 1 failed and 0 were skipped. Details of recipes and environments follow.
10:36:41 BIOCONDA ERROR BUILD SUMMARY: FAILED recipe recipes/aligncov
```

I'm unsure if these are two separate issues... Any assistance would be greatly appreciated!

**Comment by pcrxn** [comment]
For testing the recipe locally, I added `/tmp` as a path which can be bind mounted into Docker containers on my machine.  A different error occurs now:

```
10:14:39 BIOCONDA INFO BUILD START recipes/aligncov
Updating build index: /home/liam/miniconda3/envs/bioconda/conda-bld

10:14:39 BIOCONDA INFO (COMMAND) docker run -t --net host --rm -v /tmp/tmpomf9cjm7/build_script.bash:/opt/build_script.bash -v /home/liam/miniconda3/envs/bioconda/conda-bld/:/opt/host-conda-bld -v /home/liam/Desktop/bioconda-recipes/recipes/aligncov:/opt/recipe -e LANG=en_CA.UTF-8 -e HOST_USER_ID=1000 quay.io/bioconda/bioconda-utils-build-env-cos7:2.3.4 /bin/bash /opt/build_script.bash
10:14:39 BIOCONDA ERROR COMMAND FAILED (exited with 1): docker run -t --net host --rm -v /tmp/tmpomf9cjm7/build_script.bash:/opt/build_script.bash -v /home/liam/miniconda3/envs/bioconda/conda-bld/:/opt/host-conda-bld -v /home/liam/Desktop/bioconda-recipes/recipes/aligncov:/opt/recipe -e LANG=en_CA.UTF-8 -e HOST_USER_ID=1000 quay.io/bioconda/bioconda-utils-build-env-cos7:2.3.4 /bin/bash /opt/build_script.bash
10:14:39 BIOCONDA ERROR STDOUT+STDERR:
mkdir: cannot create directory '/opt/host-conda-bld/linux-aarch64': Permission denied

10:14:39 BIOCONDA ERROR BUILD FAILED recipes/aligncov
10:14:39 BIOCONDA INFO (COMMAND) conda build purge
10:14:40 BIOCONDA ERROR BUILD SUMMARY: of 1 recipes, 1 failed and 0 were skipped. Details of recipes and environments follow.
10:14:40 BIOCONDA ERROR BUILD SUMMARY: FAILED recipe recipes/aligncov
```

**Comment by pcrxn** [comment]
@BiocondaBot please add label

**Review by adamkoziol — APPROVED** [review]
Approved

**Pull request merged**
