### PR TITLE
Update kipoi to 0.6.3

### PR DESCRIPTION
**Pull request by epruesse**
Update `kipoi`: **0.6.0** &rarr; **0.6.3**

***

[Package Info](https://bioconda.github.io/recipes/kipoi/README.html) | [Recipe Folder](https://github.com/bioconda/bioconda-recipes/tree/master/recipes/kipoi) | [Upstream Home](https://github.com/kipoi/kipoi) | [Upstream Releases](https://pypi.org/pypi/kipoi/json)  

@visze @Avsecz 
***

This pull request was automatically generated by [bioconda-utils](https://github.com/bioconda/bioconda-utils).

### CODE REVIEW

**Comment by Avsecz** [comment]
Hey! What is cb3?

**Comment by epruesse** [comment]
@bgruening Sorry - overlooked the comments.

@Avsecz bgruening meant CF = CondaForge

**Comment by epruesse** [comment]
I'm not sure what you mean by CB3 migration here - it's pure python as far as I can tell?

The recipe has some issues though (the `pip install` is pretty severe I think - we shouldn't be doing that anywhere).

**Comment by Avsecz** [comment]
referencing the previous discussion on `pip install`: https://github.com/bioconda/bioconda-recipes/pull/11678

**Comment by Avsecz** [comment]
- `enum34` is available on conda-forge https://anaconda.org/conda-forge/enum34
- `epc` we don't need I think
- for `related` I can ask the author to put it to conda forge

**Comment by epruesse** [comment]
> all packages should be provided by conda-forge or bioconda and none from pip even though the pip-ones are pure pyhon?

Yes. 

What you are doing is making enum34, epc and related part of the kipoi package.

Technically conda could integrate with PyPi on the fly:

```
requirements:
  run:
    - pip:
       - enum34
```

which would (IIRC) install from pip on the fly when a user installs kipoi from conda.

We don't like that either though. Pip and coda are different, and the feature above is legacy - don't use it.

Anyone can package anything at both Conda-Forge and Bioconda. So you can just use the skeleton tool to package "related" for conda-forge and create a PR there. It may take a bit though.

**Pull request merged**
