### PR TITLE
Bump salmon version to v0.14.1 [WIP Please don't merge]

### PR DESCRIPTION
**Pull request by k3yavi**
Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it. Note that if you are not already a member of the bioconda project (meaning that you can't add this label), please ping `@bioconda/core` so that your PR can be reviewed and merged (please note if you'd like to be added to the bioconda project). Please see https://github.com/bioconda/bioconda-recipes/issues/15332 for more details.

* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [X] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [X] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by dpryan79** [comment]
Start from a clean branch next time and you won't have to deal with merge conflicts :)

**Comment by k3yavi** [comment]
Thanks for the heads up @dpryan79 , I'll update my fork before making the push next time.

**Comment by k3yavi** [comment]
@dpryan79  I was wondering we never merged 14.1 build number 0, why would it complaint to increase the build version with the error the version already exist ?

**Comment by k3yavi** [comment]
oh 14.1 was released like 19 hours ago .

**Comment by dpryan79** [comment]
@k3yavi Yeah, the bot probably noticed the new release and bumped the version automatically. I've changed the PR to add you and @rob-p as maintainers so you'll at least get a github notification when the bot updates the recipe.

**Comment by dpryan79** [comment]
This can be merged whenever you're ready.

**Comment by k3yavi** [comment]
Thanks @dpryan79 for the help !

**Pull request merged**
