### PR TITLE
Update metawrap-mg recipe to allow checkm to run

### PR DESCRIPTION
**Pull request by TomHarrop**
We need to set the CHECKM_DATA_PATH to run MetaWRAP on Galaxy Australia.

The version of checkm pinned by this recipe has the path `/srv/whitlam/bio/db/checkm_data/1.0.0` configured in `/usr/local/lib/python2.7/site-packages/checkm/DATA_CONFIG`.

The mechanism to set the data path for this version of checkm is to run `checkm data setRoot`, but that fails because the file `/usr/local/lib/python2.7/site-packages/checkm/DATA_CONFIG` is read-only.

The ability to set the environment variable CHECKM_DATA_PATH was added in CheckM v1.1.6. I've tried changing the dependencies in the recipe but I couldn't find a combination that works.

My workaround is allow writing to `/usr/local/lib/python2.7/site-packages/checkm/DATA_CONFIG`, which means we can run `checkm data setRoot` before running MetaWRAP.

Obviously this is a hack, and it would be better if the dependencies could be updated to allow CheckM v1.1.6 or later. Failing that, merging this PR would at least allow us to install the software.

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by TomHarrop** [comment]
@BiocondaBot please fetch artifacts

**Comment by TomHarrop** [comment]
@BiocondaBot please add label

**Review by priesgo — APPROVED** [review]

**Comment by priesgo** [comment]
@BiocondaBot please merge

**Comment by TomHarrop** [comment]
@bioconda/core Is there anything I can do to help get this merged?

@priesgo approved the PR but there was an error uploading the artifacts.

Thanks!

**Comment by priesgo** [comment]
Let's try again...

**Comment by priesgo** [comment]
@BiocondaBot please merge

**Comment by TomHarrop** [comment]
@priesgo thanks for the help.

Could it be because I issued `please fetch artifacts` and you issued `please merge`? Would it be worth you trying them both in succession?

I'm not certain where to find the logs but it might be this run: https://github.com/bioconda/bioconda-recipes/actions/runs/3823146879/jobs/6504006478.

**Comment by TomHarrop** [comment]
@BiocondaBot please fetch artifacts

**Comment by TomHarrop** [comment]
@BiocondaBot please fetch artifacts

**Comment by TomHarrop** [comment]
@BiocondaBot please fetch artifacts

**Comment by TomHarrop** [comment]
After seeing [this comment](https://github.com/galaxyproject/tools-iuc/pull/2775#issuecomment-575878067) from @bgruening I am hoping it's acceptable to add the database to the package. This will make it much easier for me to wrap the tool for Galaxy.

I've tested the biocontainer from my latest commit so if you're happy with that change it should be good to go. Thanks again!

**Pull request merged**
