### PR TITLE
upgrade rscape

### PR DESCRIPTION
**Pull request by mmiladi**
* [ ] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [ ] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by bgruening** [comment]
Hi  @mmiladi1 Why glib? I saw this error: `/opt/conda/conda-bld/rscape_1533224184936/test_tmp/run_test.sh: line 7:  6942 Segmentation fault      (core dumped) R-scape --cyk --nofigures tmp.sto`. A classical segmentation fault.

**Comment by mmiladi** [comment]
An attempt to resolve these warnings at the end of compilation: `WARNING (rscape,bin/r2r): did not find - or even know where to look for: /lib64/libc.so.6`

**Comment by bgruening** [comment]
Still a classical segfault: ` /opt/conda/conda-bld/rscape_1533330411923/test_tmp/run_test.sh: line 7:  7012 Segmentation fault      (core dumped) R-scape --cyk --nofigures tmp.sto`

**Comment by mmiladi** [comment]
Thanks for the help @bgruening . There are differences between configurations of local and CI builds. E.g.
On local gcc in installed first:
```
The following NEW packages will be INSTALLED:

    binutils_impl_linux-64: 2.28.1-had2808c_3
    binutils_linux-64:      7.2.0-had2808c_27
    gcc_impl_linux-64:      7.2.0-habb00fd_3 
    gcc_linux-64:           7.2.0-h550dcbe_27
    gxx_impl_linux-64:      7.2.0-hdf63c60_3 
    gxx_linux-64:           7.2.0-h550dcbe_27
    libstdcxx-ng:           7.2.0-hdf63c60_3 

```
And in the configured report build specific gcc bins are used:
```
R-scape configuration:

     compiler:    /home/milad/miniconda3/conda-bld/rscape_1533493444386/_build_env/bin/x86_64-conda_cos6-linux-gnu-cc -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -I/home/milad/miniconda3/conda-bld/rscape_1533493444386/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/include -fdebug-prefix-map=${SRC_DIR}=/usr/local/src/conda/${PKG_NAME}-${PKG_VERSION} -fdebug-prefix-map=${PREFIX}=/usr/local/src/conda-prefix  -pthread -fPIC
     host:        x86_64-unknown-linux-gnu
     libraries:      -lrt 

```
while on ci, the one from the path:
```
R-scape configuration:

     compiler:    gcc -std=gnu99  -m64 -fPIC  -pthread -fPIC
     host:        x86_64-unknown-linux-gnu
     libraries:      -lrt 

```

Could these be the reasons for failing?

**Comment by bgruening** [comment]
Mh are you not using `cirlceci build` locally? Bioconda is still using the older GCC from the Docker Container while you are using the newer pkgs. This can be a reason, but a unlikely one? It seems that the new version is crashing under an old compiler? You can use the new compilers.

**Pull request merged**
