### PR TITLE
Add stringtie version 1.3.3b

### PR DESCRIPTION
**Pull request by nh13**
Adding a previous version of stringtie (1.3.3b) that I need to use to reproduce a previous analysis.  Related to https://github.com/bioconda/bioconda-recipes/issues/21982

I copied the `1.3.3` directory, modified the URL and SHA256 checksum.  That's it!

### CODE REVIEW

**Comment by nh13** [comment]
@BiocondaBot please add label

**Comment by dpryan79** [comment]
Do you really need this old version for some reason? I'd prefer to get rid of 1.3.3 then at the same time unless it's needed for something.

**Comment by nh13** [comment]
@dpryan79 yes I really do need this version for a clinical pipeline that I am moving to a reproducible build (wanting to use bioconda).  Thanks!

**Comment by dpryan79** [comment]
@bioconda-bot please fetch artifacts

**Comment by nh13** [comment]
@dpryan79 any reason why Python 3 isn’t supported, if I interpret Python<3 correctly? The 1.3.3 recipe doesn’t require that I don’t think.

**Comment by nh13** [comment]
And thank you for pushing this!

**Comment by dpryan79** [comment]
@nh13 Your original PR had it as python 2 only, I just changed it so it would build. If I recall, the python wrappers may not have been updated for python 3 (someone would have to look).

**Comment by dpryan79** [comment]
Looks like you'll have to try putting $CXX into a few make files

**Comment by nh13** [comment]
I can try to take a look tomorrow. I wonder if the 1.34d build could help us out in terms of what’s needed.

**Comment by nh13** [comment]
@dpryan79 I got a little farther, but I am having trouble [finding exactly where to inject CXX](https://bioconda.github.io/contributor/troubleshooting.html#g-or-gcc-not-found) where I haven't already.  Do you have time to take a look?

**Comment by nh13** [comment]
I think the latest commit will work because the stringtie Makefile uses `CC` variable for the `CXX` compiler.  Bioinformatics...

**Comment by nh13** [comment]
@dpryan79 Look at the 1.3.3 sub-directory, which my original commit 5226f27 modified in this directory.  I just tested this on my local machine and both worked:
```
conda create -n stringtie -c bioconda stringtie=1.3.3 python=3
conda create -n stringtie -c bioconda stringtie=1.3.3 python=2
```
So it looks like that recipe built both python 2 & 3.  So I am not sure how 1.3.3 is working with python 3, but then [you said](https://github.com/bioconda/bioconda-recipes/pull/22010#issuecomment-626345276) this one doesn't?

**Comment by nh13** [comment]
I stand by that this PR should go just with 5226f27 as it is the minimal modification of what's there in the 1.3.3 build.  The makefiles in 1.3.3 and 1.3.3b are the same FYI.

**Comment by dpryan79** [comment]
@bioconda-bot please fetch artifacts

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Pull request merged**
