### PR TITLE
Patch spatyper for better container support

### PR DESCRIPTION
**Pull request by rpetit3**
This PR patches spatyper to have better support for containers (docker/singularity)

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by rpetit3** [comment]
### Current Container
```
docker run --rm -u $(id -u):$(id -g) -v ${PWD}:/data quay.io/biocontainers/spatyper:0.3.3--py_1 spaTyper -f /data/GCF_000009645.1_ASM964v1_genomic.fna
Start the identification of repeats in Spa protein:
+ Check or download repeats fasta file in folder:  /usr/local/bin
Traceback (most recent call last):
  File "/usr/local/bin/spaTyper", line 92, in <module>
    args.repeat_file = spaTyper.utils.download_file_repeats(args.folder, args.debug)
  File "/usr/local/lib/python3.9/site-packages/spaTyper/utils.py", line 134, in download_file_repeats
    print_time_stamp(filename_stamp)
  File "/usr/local/lib/python3.9/site-packages/spaTyper/utils.py", line 192, in print_time_stamp
    timefile = open(out, 'w')
PermissionError: [Errno 13] Permission denied: '/usr/local/bin/.success'
```

### Container in this PR
```
docker run --rm -u $(id -u):$(id -g) -v ${PWD}:/data quay.io/biocontainers/spatyper:0.3.3--pyhdfd78af_2 spaTyper -f /data/GCF_000009645.1_ASM964v1_genomic.fna
Start the identification of repeats in Spa protein:
+ Repeats fasta file provided:  /usr/local/share/spatyper-0.3.3/sparepeats.fasta
+ Repeat types file provided:  /usr/local/share/spatyper-0.3.3/spatypes.txt

-----------------
Results:
Sequence name   Repeats Type
NC_002745.2 Staphylococcus aureus subsp. aureus N315, complete sequence 26-23-17-34-17-20-17-12-17-16   t002
-----------------
```

### Demonstrating Downloads 
Fails to download to default location (this is expected)
```
docker run --rm -u $(id -u):$(id -g) -v ${PWD}:/data quay.io/biocontainers/spatyper:0.3.3--pyhdfd78af_2 download-spatypes.sh
Downloading spa types to /usr/local/share/spatyper-0.3.3
/usr/local/share/spatyper-0.3.3/sparepeats.fasta: Permission denied
/usr/local/share/spatyper-0.3.3/spatypes.txt: Permission denied
```

Can download to mounted volume
```
docker run --rm -u $(id -u):$(id -g) -v ${PWD}:/data quay.io/biocontainers/spatyper:0.3.3--pyhdfd78af_2 download-spatypes.sh /data
Downloading spa types to /data
--2021-09-22 16:30:15--  http://spa.ridom.de/dynamic/sparepeats.fasta
Resolving spa.ridom.de (spa.ridom.de)... 116.203.143.178
Connecting to spa.ridom.de (spa.ridom.de)|116.203.143.178|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 28803 (28K)
Saving to: ‘/data/sparepeats.fasta’

     0K .......... .......... ........                        100%  260K=0.1s

2021-09-22 16:30:15 (260 KB/s) - ‘/data/sparepeats.fasta’ saved [28803/28803]

--2021-09-22 16:30:15--  http://spa.ridom.de/dynamic/spatypes.txt
Resolving spa.ridom.de (spa.ridom.de)... 116.203.143.178
Connecting to spa.ridom.de (spa.ridom.de)|116.203.143.178|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 728390 (711K) [text/plain]
Saving to: ‘/data/spatypes.txt’

     0K .......... .......... .......... .......... ..........  7%  230K 3s
    50K .......... .......... .......... .......... .......... 14%  461K 2s
   100K .......... .......... .......... .......... .......... 21% 43.1M 1s
   150K .......... .......... .......... .......... .......... 28% 74.3M 1s
   200K .......... .......... .......... .......... .......... 35%  465K 1s
   250K .......... .......... .......... .......... .......... 42% 34.5M 1s
   300K .......... .......... .......... .......... .......... 49%  210M 0s
   350K .......... .......... .......... .......... .......... 56% 38.4M 0s
   400K .......... .......... .......... .......... .......... 63%  475K 0s
   450K .......... .......... .......... .......... .......... 70%  106M 0s
   500K .......... .......... .......... .......... .......... 77%  116M 0s
   550K .......... .......... .......... .......... .......... 84%  171M 0s
   600K .......... .......... .......... .......... .......... 91% 76.5M 0s
   650K .......... .......... .......... .......... .......... 98%  107M 0s
   700K .......... .                                          100%  156M=0.5s

2021-09-22 16:30:16 (1.27 MB/s) - ‘/data/spatypes.txt’ saved [728390/728390]

(base) robert_petit@wphlngs:~/test/spatyper$ ls
GCF_000009645.1_ASM964v1_genomic.fna  sparepeats.fasta  spatypes.txt  staphylococcus-aureus
```


Container looks good to me, going to test conda install to make sure its still good

**Comment by rpetit3** [comment]
### Testing Conda install
```
 mamba create -n test-spatyper -c https://169360-42372094-gh.circle-artifacts.com/0/tmp/artifacts/packages -c conda-forge -c bioconda spatyper

...TRUNCATED...

  spatyper             0.3.3  pyhdfd78af_2        169360-42372094-gh.circle-artifacts.com/0/tmp/artifacts/packages/noarch     247 KB

...TRUNCATED...

Preparing transaction: done
Verifying transaction: done
Executing transaction: /
Please run 'download-spatypes.sh' to download the files required to run spaTyper. These files will be downloaded to
/home/robert_petit/miniconda3/envs/test-spatyper/share/spatyper-0.3.3 by defualt, unless a path is given (e.g. download-spatypes.sh ./). Please use the '-d' parameter
in spaTyper to change the location of database files.



done
#
# To activate this environment, use
#
#     $ conda activate test-spatyper
#
# To deactivate an active environment, use
#
#     $ conda deactivate
```

### Running spaTyper
```
spaTyper -f GCF_000009645.1_ASM964v1_genomic.fna
Start the identification of repeats in Spa protein:
+ Repeats fasta file provided:  /home/robert_petit/miniconda3/envs/test-spatyper/share/spatyper-0.3.3/sparepeats.fasta
+ Repeat types file provided:  /home/robert_petit/miniconda3/envs/test-spatyper/share/spatyper-0.3.3/spatypes.txt

-----------------
Results:
Sequence name   Repeats Type
NC_002745.2 Staphylococcus aureus subsp. aureus N315, complete sequence 26-23-17-34-17-20-17-12-17-16   t002
-----------------
```

### Downloading files
Default directory
```
download-spatypes.sh
Downloading spa types to /home/robert_petit/miniconda3/envs/test-spatyper/share/spatyper-0.3.3
--2021-09-22 16:39:17--  http://spa.ridom.de/dynamic/sparepeats.fasta
Resolving spa.ridom.de (spa.ridom.de)... 116.203.143.178
Connecting to spa.ridom.de (spa.ridom.de)|116.203.143.178|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 28803 (28K)
Saving to: ‘/home/robert_petit/miniconda3/envs/test-spatyper/share/spatyper-0.3.3/sparepeats.fasta’

/home/robert_petit/miniconda3/envs/test-spatyper/share/spatyper-0.3.3 100%[=========================================================================================================================================================================>]  28.13K  --.-KB/s    in 0.1s

2021-09-22 16:39:17 (262 KB/s) - ‘/home/robert_petit/miniconda3/envs/test-spatyper/share/spatyper-0.3.3/sparepeats.fasta’ saved [28803/28803]

--2021-09-22 16:39:17--  http://spa.ridom.de/dynamic/spatypes.txt
Resolving spa.ridom.de (spa.ridom.de)... 116.203.143.178
Connecting to spa.ridom.de (spa.ridom.de)|116.203.143.178|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 728390 (711K) [text/plain]
Saving to: ‘/home/robert_petit/miniconda3/envs/test-spatyper/share/spatyper-0.3.3/spatypes.txt’

/home/robert_petit/miniconda3/envs/test-spatyper/share/spatyper-0.3.3 100%[=========================================================================================================================================================================>] 711.32K  1.28MB/s    in 0.5s

2021-09-22 16:39:18 (1.28 MB/s) - ‘/home/robert_petit/miniconda3/envs/test-spatyper/share/spatyper-0.3.3/spatypes.txt’ saved [728390/728390]
```

Custom directory
```
download-spatypes.sh test-spatyper/
Downloading spa types to test-spatyper/
--2021-09-22 16:39:46--  http://spa.ridom.de/dynamic/sparepeats.fasta
Resolving spa.ridom.de (spa.ridom.de)... 116.203.143.178
Connecting to spa.ridom.de (spa.ridom.de)|116.203.143.178|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 28803 (28K)
Saving to: ‘test-spatyper//sparepeats.fasta’

test-spatyper//sparepeats.fasta                                       100%[=========================================================================================================================================================================>]  28.13K  --.-KB/s    in 0.1s

2021-09-22 16:39:47 (259 KB/s) - ‘test-spatyper//sparepeats.fasta’ saved [28803/28803]

--2021-09-22 16:39:47--  http://spa.ridom.de/dynamic/spatypes.txt
Resolving spa.ridom.de (spa.ridom.de)... 116.203.143.178
Connecting to spa.ridom.de (spa.ridom.de)|116.203.143.178|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 728390 (711K) [text/plain]
Saving to: ‘test-spatyper//spatypes.txt’

test-spatyper//spatypes.txt                                           100%[=========================================================================================================================================================================>] 711.32K  1.28MB/s    in 0.5s

2021-09-22 16:39:48 (1.28 MB/s) - ‘test-spatyper//spatypes.txt’ saved [728390/728390]

ls test-spatyper/
sparepeats.fasta  spatypes.txt
```

Everything looks good to me

**Comment by rpetit3** [comment]
It wasn't pretty getting there, but I think this PR should make spaTyper much more useable for those users limited to Docker/Singularity

**Comment by rpetit3** [comment]
@biocondabot please add label

**Review by thanhleviet — APPROVED** [review]
LGTM

**Comment by thanhleviet** [comment]
@BiocondaBot please merge

**Comment by rpetit3** [comment]
Thank you!

**Pull request merged**
