### PR TITLE
Update ivar to 1.3.2

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`ivar`](https://bioconda.github.io/recipes/ivar/README.html): **1.3.1** &rarr; **1.3.2**

[install with bioconda](http://bioconda.github.io/recipes/ivar/README.html) [Conda](https://anaconda.org/bioconda/ivar/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/ivar`](https://github.com//bioconda/bioconda-recipes/tree/bump/ivar/recipes/ivar) (click to view/edit other files)
Summary | iVar is a computational package that contains functions broadly useful for viral amplicon-based sequencing.
Home | [https://andersen-lab.github.io/ivar/html/](https://andersen-lab.github.io/ivar/html/)
Releases |[https://github.com/andersen-lab/ivar/tags](https://github.com/andersen-lab/ivar/tags)
Author | `@andersen-lab`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by cmaceves** [comment]
hi - I'm the developer for this package, and I'm actively working to get these issues fixed!

**Comment by cmaceves** [comment]
Is it possible to delete this PR so that I can re-release, and address the issues with the recipe?

**Comment by cmaceves** [comment]
please review and merge!

**Review by cbrueffer — APPROVED** [review]

**Comment by cbrueffer** [comment]
@BiocondaBot please merge

**Comment by cbrueffer** [comment]
Thanks @cmaceves !

**Pull request merged**
