### PR TITLE
Update prophyle to 0.3.3.1

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`prophyle`](https://bioconda.github.io/recipes/prophyle/README.html): **0.3.2.0** &rarr; **0.3.3.1**

[install with bioconda](http://bioconda.github.io/recipes/prophyle/README.html) [Conda](https://anaconda.org/bioconda/prophyle/files)

Info | Link
-----|-----
Recipe | [`recipes/prophyle`](https://github.com//bioconda/bioconda-recipes/tree/bump/prophyle/recipes/prophyle) (click to view/edit other files)
Releases |[https://pypi.org/pypi/prophyle/json](https://pypi.org/pypi/prophyle/json)

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Review by karel-brinda — APPROVED** [review]

**Comment by karel-brinda** [comment]
Would it be possible to copy&paste the error message? I can't access the CircleCI logs.

**Comment by karel-brinda** [comment]
@dpryan79, @samuelecancellieri Do you please have access to the CircleCI  logs?

**Comment by dpryan79** [comment]
Sorry for the delay, the error is:

```
20:36:17 BIOCONDA INFO (OUT) + prophyle_otu_table.py --help
20:36:17 BIOCONDA INFO (OUT) Traceback (most recent call last):
20:36:17 BIOCONDA INFO (OUT)   File "/opt/conda/conda-bld/prophyle_1629750506359/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/prophyle_otu_table.py", line 7, in <module>
20:36:17 BIOCONDA INFO (OUT)     from prophyle.prophyle_otu_table import main
20:36:17 BIOCONDA INFO (OUT) ModuleNotFoundError: No module named 'prophyle.prophyle_otu_table'
```

**Comment by karel-brinda** [comment]
@dpryan79 Thank you so much!

**Comment by raivivek** [comment]
@BiocondaBot please update

**Pull request closed without merging**
