### PR TITLE
Update to mOTUs version 2.5.0

### PR DESCRIPTION
**Pull request by AlessioMilanese**
Update mOTUs tool to version 2.5.0:
- update version (and .gz file)
- update sha256
- Change build number back to 1

Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it. Note that if you are not already a member of the bioconda project (meaning that you can't add this label), please ping `@bioconda/core` so that your PR can be reviewed and merged (please note if you'd like to be added to the bioconda project). Please see https://github.com/bioconda/bioconda-recipes/issues/15332 for more details.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by AlessioMilanese** [comment]
There are the following errors during linting:
```
ERROR: recipes/motus/meta.yaml:15: should_be_noarch_generic: The recipe should be build as `noarch`
ERROR: recipes/motus/meta.yaml:15: should_not_use_skip_python: The recipe should be noarch and not use python based skipping
WARNING: recipes/motus/meta.yaml:32: gpl_requires_license_distributed: The recipe packages GPL software but is missing copy of license.
ERROR: recipes/motus/meta.yaml:14: build_number_needs_reset: The recipe build number should be reset to 0
Errors were found
Exited with code 1
```

**Comment by AlessioMilanese** [comment]
Changed:
```
build:
  number: 1
```
To:
```
build:
  number: 0
```

**Comment by unode** [comment]
About the errors:

```
# Noarch or not checks:
#
# - Python packages that use no compiler should be
#   a) Marked ``noarch: python``
#   b) Not use ``skip: True  # [...]`` except for osx/linux,
#      but use ``- python [<>]3``
```
so this is now missing:
```
- python 3
```

and for the license error, we have the `LICENSE` file so the recipe just needs:
```
about:
    license_file: LICENSE
```

**Comment by unode** [comment]
Seems like `noarch: python` is indeed necessary. That's the only lint error remaining.

**Comment by AlessioMilanese** [comment]
Updated as suggested by @unode, but there is still one error:
```
ERROR: recipes/motus/meta.yaml:15: should_be_noarch_python: The recipe should be build as `noarch`
```

Will update following https://bioconda.github.io/contributor/linting.html#should-be-noarch-python

**Comment by AlessioMilanese** [comment]
Thanks @unode for the suggestions.
Can you approve and merge?

**Comment by unode** [comment]
Looks good to me

**Pull request merged**
