### PR TITLE
Add TraMineR

### PR DESCRIPTION
**Pull request by cmonjeau**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by cmonjeau** [comment]
An idea @abretaud for macos test?

**Comment by abretaud** [comment]
No idea, macos and r are a mystery for me
Ping @bioconda/osx @bioconda/r maybe ? (or just skip macos)

**Comment by rvalieris** [comment]
try removing the llvm package, and the `#[linux]` selectors for gcc/libgcc.

**Comment by cmonjeau** [comment]
Oooo thanks @rvalieris ( and @abretaud of courses)

**Comment by cmonjeau** [comment]
Thanks @bgruening

**Pull request merged**
