### PR TITLE
Trigger a build of tbl2asn to pick up the updated ZLIB.

### PR DESCRIPTION
**Pull request by ysu20**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by ysu20** [comment]
I am not entirely sure why, but NCBI seems to update tbl2asm's binary distributions without changing their version number.  Hence, I had to update the checksums in the recipe.

**Comment by bgruening** [comment]
Can you also check the version number manually. I think its now changed as well.

**Comment by ysu20** [comment]
Hi @bgruening Just checked it and it is still showing 25.6.

**Comment by tesujimath** [comment]
Sorry, the close was a mistake, caused by me resetting the master branch on our fork.  New PR coming soon I hope ...

**Pull request closed without merging**
