### PR TITLE
ver 2.0.8

### PR DESCRIPTION
**Pull request by theAguy**
Describe your pull request here

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

### General instructions

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

### Instructions for avoiding API, ABI, and CLI breakage issues
Conda is able to record and lock (a.k.a. pin) dependency versions used at build time of other recipes.
This way, one can avoid that expectations of a downstream recipe with regards to API, ABI, or CLI are violated by later changes in the recipe.
If not already present in the meta.yaml, make sure to specify `run_exports` (see [here](https://bioconda.github.io/contributor/linting.html#missing-run-exports) for the rationale and comprehensive explanation).
Add a `run_exports` section like this:

```yaml
build:
  run_exports:
    - ...

```

with `...` being one of:

| Case                             | run_exports statement                                               |
| -------------------------------- | ------------------------------------------------------------------- |
| semantic versioning              | `{{ pin_subpackage("myrecipe", max_pin="x") }}`     |
| semantic versioning (0.x.x)      | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}`   |
| known breakage in minor versions | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| known breakage in patch versions | `{{ pin_subpackage("myrecipe", max_pin="x.x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| calendar versioning              | `{{ pin_subpackage("myrecipe", max_pin=None) }}`    |

while replacing `"myrecipe"` with either `name` if a `name|lower` variable is defined in your recipe or with the lowercase name of the package in quotes.

### Bot commands for PR management

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

Note that the <code>@BiocondaBot please merge</code> command is now depreciated. Please just squash and merge instead.

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by theAguy** [comment]
@kbseah The problem still persist, but I succeed to create new pull request through the GitHub website. However the request fails and I don't understand why.

Any help would be appreciated.

**Comment by kbseah** [comment]
I'm not sure which problem you're referring to, so I'll respond to both here:

Problem with pushing to GitHub: The error message you posted in the other thread suggested that there are conflicts between your branch and with the remote branch you are trying to push to. I'm afraid I can't help with the specifics, but fetch/merge from the remote might help, [see](https://docs.github.com/en/get-started/using-git/dealing-with-non-fast-forward-errors). The proposed changes to this recipe are small, so in the worst case you could just make a new branch from the upstream/master and start over.

Failed build of the recipe: From the log messages, it looks like some dependencies have to be pinned more strictly. I've opened a pull request to your branch with changes that worked for me when testing locally. If you merge and/or make further commits to your branch it should trigger a new round of tests in this PR.

**Comment by theAguy** [comment]
Thank you so much!

Problem with pushing to GitHub:
Is there any comprehensive guide to uploading Conda package? I followed some article instructions.
I'll try to do as you say however my knowledge in Git in general is not that strong.

Failed build of the recipe:
What kind of changes have you made? Is there any place I can see it?

**Comment by kbseah** [comment]
Conda packages: For the Bioconda channel specifically, have a look [here](https://bioconda.github.io/contributor/index.html), if you haven't already

Git: I find the [Pro Git](https://git-scm.com/book/en/v2) book useful

Changes to the recipe: I've opened a pull request on your fork https://github.com/theAguy/bioconda-recipes/pull/1

**Comment by theAguy** [comment]
Hey! Can you please review and merge the changes?
I am not familiar with how to tag the pull request with 

> please review & merge

 (:

**Review by kbseah — APPROVED** [review]

**Comment by theAguy** [comment]
Thank you so much.
Why is the version not updated in Bioconda packages?
I still see v2.0.7

Many thanks.

**Comment by kbseah** [comment]
as i understand it, each PR is usually reviewed by two people, so although i've approved it, it's still waiting for someone else to merge.

it may help if you edit the name of the pull request to something like 'Update [name of package] to [version]', so that someone looking over the list of PRs knows what it is about.

**Comment by mencian** [comment]
LGTM! Thanks @theAguy and @kbseah!

**Pull request merged**
