### PR TITLE
Update verkko to v2.1

### PR DESCRIPTION
**Pull request by skoren**
Updating to v2.1 for verkko

### CODE REVIEW

**Comment by skoren** [comment]
@BiocondaBot please fetch artifacts

**Comment by skoren** [comment]
@BiocondaBot please add label

**Comment by skoren** [comment]
The auto-pull (#47887) can be closed, I reduced the test runtime in this release and also had to keep the explicit rust version as compiler rust wasn't working (it put the binary in a different build location) so maybe we can update the makefile for that in v2.2 release.

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
Thanks @skoren

**Pull request merged**
