### PR TITLE
WIP: notes about OSX building by default

### PR DESCRIPTION
**Pull request by daler**

### CODE REVIEW

**Comment by daler** [comment]
Note: just a draft, do not merge. The changes described here will not be implemented until we completely remove the osx-whitelist.

**Comment by bgruening** [comment]
Great idea @daler!

**Comment by bgruening** [comment]
@daler This is ready to go. Please note that there are some comments about the whitelist in `toposort_recipes.py`.

**Comment by daler** [comment]
Thanks for the reminder, I fixed those comments too.

**Pull request merged**
