### PR TITLE
Add `pyhmmsearch`

### PR DESCRIPTION
**Pull request by apcamargo**
This PR adds [`pyhmmsearch`](https://github.com/jolespin/pyhmmsearch), by @jolespin.

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

### General instructions

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

### Instructions for avoiding API, ABI, and CLI breakage issues
Conda is able to record and lock (a.k.a. pin) dependency versions used at build time of other recipes.
This way, one can avoid that expectations of a downstream recipe with regards to API, ABI, or CLI are violated by later changes in the recipe.
If not already present in the meta.yaml, make sure to specify `run_exports` (see [here](https://bioconda.github.io/contributor/linting.html#missing-run-exports) for the rationale and comprehensive explanation).
Add a `run_exports` section like this:

```yaml
build:
  run_exports:
    - ...

```

with `...` being one of:

| Case                             | run_exports statement                                               |
| -------------------------------- | ------------------------------------------------------------------- |
| semantic versioning              | `{{ pin_subpackage("myrecipe", max_pin="x") }}`     |
| semantic versioning (0.x.x)      | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}`   |
| known breakage in minor versions | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| known breakage in patch versions | `{{ pin_subpackage("myrecipe", max_pin="x.x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| calendar versioning              | `{{ pin_subpackage("myrecipe", max_pin=None) }}`    |

while replacing `"myrecipe"` with either `name` if a `name|lower` variable is defined in your recipe or with the lowercase name of the package in quotes.

### Bot commands for PR management

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

Note that the <code>@BiocondaBot please merge</code> command is now depreciated. Please just squash and merge instead.

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by apcamargo** [comment]
@jolespin it seems that the `Icon` file is causing an error. Is it necessary for the package?

**Comment by jolespin** [comment]
> @jolespin it seems that the `Icon` file is causing an error. Is it necessary for the package?

Definitely not. I’ve been trying to remove these in my .gitignore but I think they are being copied over from my Google Drive sync where I do most of my devel.  I can push a new update that removes them if they snuck into the tar.gz build.

**Comment by apcamargo** [comment]
Thanks, @jolespin! Let me know when you push the release so I can update the recipe

**Comment by jolespin** [comment]
> Thanks, @jolespin! Let me know when you push the release so I can update the recipe

I just updated it now. Let me know if any other changes are needed.  New version is v2024.10.20

**Comment by apcamargo** [comment]
Thanks, @jolespin! It worked.

I saw that the other two repos also have an `Icon` file. I can create a PR with the recipes when you update them.

**Comment by apcamargo** [comment]
@BiocondaBot please add label

**Comment by jolespin** [comment]
> Thanks, @jolespin! It worked.
> 
> I saw that the other two repos also have an `Icon` file. I can create a PR with the recipes when you update them.

Excellent! I'll fix it for pykofamsearch but I'm having trouble using entry points correctly with kegg_pathway_profiler.  I currently have my executables in [package-directory]/bin/ which can't be accessed by entry points so I moved them into [package-directory]/kegg_pathway_profiler/cli/ but had trouble importing them into __init__.py properly.  I wonder if it's because they have "-" characters instead of "_"? Regardless, I'll get the pykofamsearch fixed right now.

**Review by mencian — APPROVED** [review]

**Pull request merged**
