### PR TITLE
Update skani to 0.1.0

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`skani`](https://bioconda.github.io/recipes/skani/README.html): **0.0.1** &rarr; **0.1.0**

[install with bioconda](http://bioconda.github.io/recipes/skani/README.html) [Conda](https://anaconda.org/bioconda/skani/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/skani`](https://github.com//bioconda/bioconda-recipes/tree/bump/skani/recipes/skani) (click to view/edit other files)
Summary | skani is a fast and robust tool for calculating ANI between metagenome assembled genomes and contigs.
Home | [https://github.com/bluenote-1577/skani](https://github.com/bluenote-1577/skani)
Releases |[https://github.com/bluenote-1577/skani/tags](https://github.com/bluenote-1577/skani/tags)
Author | `@bluenote-1577`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Review by bluenote-1577 — APPROVED** [review]
please merge

**Review by rpetit3 — APPROVED** [review]

**Comment by rpetit3** [comment]
@BiocondaBot please merge

**Comment by rpetit3** [comment]
@BiocondaBot please fetch artifacts

**Comment by rpetit3** [comment]
@BiocondaBot please merge

**Pull request merged**
