### PR TITLE
Update varlociraptor to 2.4.0

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`varlociraptor`](https://bioconda.github.io/recipes/varlociraptor/README.html): **2.3.0** &rarr; **2.4.0**

[install with bioconda](http://bioconda.github.io/recipes/varlociraptor/README.html) [Conda](https://anaconda.org/bioconda/varlociraptor/files)

Info | Link
-----|-----
Recipe | [`recipes/varlociraptor`](https://github.com//bioconda/bioconda-recipes/tree/bump/varlociraptor/recipes/varlociraptor) (click to view/edit other files)
Releases |[https://github.com/varlociraptor/varlociraptor/tags](https://github.com/varlociraptor/varlociraptor/tags)
Author | `@varlociraptor`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by mbargull** [comment]
```
09:04:36 BIOCONDA INFO (ERR)   cargo:warning=/Users/distiller/project/miniconda/conda-bld/varlociraptor_1604595427806/work/target/release/build/hts-sys-add2d79fbb52a50d/out/htslib/hts.c:3693:13: warning: implicit declaration of function 'access' is invalid in C99 [-Wimplicit-function-declaration]
09:04:36 BIOCONDA INFO (ERR)   cargo:warning=        if (access(s.s, R_OK) == 0)
09:04:36 BIOCONDA INFO (ERR)   cargo:warning=            ^
09:04:36 BIOCONDA INFO (ERR)   cargo:warning=/Users/distiller/project/miniconda/conda-bld/varlociraptor_1604595427806/work/target/release/build/hts-sys-add2d79fbb52a50d/out/htslib/hts.c:3693:25: error: use of undeclared identifier 'R_OK'
09:04:36 BIOCONDA INFO (ERR)   cargo:warning=        if (access(s.s, R_OK) == 0)
09:04:36 BIOCONDA INFO (ERR)   cargo:warning=                        ^
```
refs:
- https://github.com/samtools/htslib/pull/1143
- https://github.com/rust-bio/rust-htslib/pull/275

Seems like `rust-htslib` has to be changed to include a small fix (missing header) that was only added to HTSlib after the 1.11 release.

**Comment by johanneskoester** [comment]
> ```
> 09:04:36 BIOCONDA INFO (ERR)   cargo:warning=/Users/distiller/project/miniconda/conda-bld/varlociraptor_1604595427806/work/target/release/build/hts-sys-add2d79fbb52a50d/out/htslib/hts.c:3693:13: warning: implicit declaration of function 'access' is invalid in C99 [-Wimplicit-function-declaration]
> 09:04:36 BIOCONDA INFO (ERR)   cargo:warning=        if (access(s.s, R_OK) == 0)
> 09:04:36 BIOCONDA INFO (ERR)   cargo:warning=            ^
> 09:04:36 BIOCONDA INFO (ERR)   cargo:warning=/Users/distiller/project/miniconda/conda-bld/varlociraptor_1604595427806/work/target/release/build/hts-sys-add2d79fbb52a50d/out/htslib/hts.c:3693:25: error: use of undeclared identifier 'R_OK'
> 09:04:36 BIOCONDA INFO (ERR)   cargo:warning=        if (access(s.s, R_OK) == 0)
> 09:04:36 BIOCONDA INFO (ERR)   cargo:warning=                        ^
> ```
> 
> refs:
> 
>     * [samtools/htslib#1143](https://github.com/samtools/htslib/pull/1143)
> 
>     * [rust-bio/rust-htslib#275](https://github.com/rust-bio/rust-htslib/pull/275)
> 
> 
> Seems like `rust-htslib` has to be changed to include a small fix (missing header) that was only added to HTSlib after the 1.11 release.

thanks a lot @mbargull! We'll skip macos for this release, and reactivate it again with the next one.

**Comment by johanneskoester** [comment]
@bioconda-bot please merge

**Review by johanneskoester — APPROVED** [review]

**Comment by johanneskoester** [comment]
@bioconda-bot please merge

**Pull request merged**
