### PR TITLE
bedtk: Add new package, version 0.0r25dirty

### PR DESCRIPTION
**Pull request by mbargull**
Add new package `bedtk`.
Upstream version is "`0.0-r25-dirty`". Since we don't want `-` in the version string, this is contracted to `0.0r25dirty` (i.e., it'll be interpreted as a pre-release version of `0.0`).

When starting with the recipe I didn't notice there is already an upstream issue concerning the versioning from @bwlang : https://github.com/lh3/bedtk/issues/2 .
Adding this as a "pre-release of version `0.0` here means any subsequent update to a release version can take precedence over this initial addition, so we should be future proof here.
If `upstream_version | replace("-", "")`, i.e., `0.0r25dirty` looks too terse, we can also go for `upstream_version | replace("-", ".")`, i.e., `0.0.r25.dirty`.

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by mbargull** [comment]
> If `upstream_version | replace("-", "")`, i.e., `0.0r25dirty` looks too terse, we can also go for `upstream_version | replace("-", ".")`, i.e., `0.0.r25.dirty`.

I added a commit with this change (because I find it easier to read and for us it is -- if applied consistently -- equally fine to use either for pre-releases). Once a `0.1`/`1.0` or similar is released upstream, we can remove the revision suffix part.

**Comment by mbargull** [comment]
@BiocondaBot, please fetch artifacts

**Comment by mbargull** [comment]
@BiocondaBot, please add label

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Comment by mbargull** [comment]
Thanks for all the reviews!

**Pull request merged**
