### PR TITLE
Add tar to Clark

### PR DESCRIPTION
**Pull request by aaguinal**
When using Clark Biocontainer (`quay.io/biocontainers/clark:1.2.5.1--h6bb024c_0`), the following error is thrown:

```
Connecting to ftp.ncbi.nlm.nih.gov (130.14.250.11:21)
nucl_gb.accession2ta 100% |*******************************|  1809M  0:00:00 ETA
Connecting to ftp.ncbi.nlm.nih.gov (130.14.250.11:21)
nucl_wgs.accession2t 100% |*******************************|  3285M  0:00:00 ETA
Connecting to ftp.ncbi.nih.gov (130.14.250.12:21)
taxdump.tar.gz       100% |*******************************| 49740k  0:00:00 ETA
Uncompressing files...
Failed to uncompress taxonomy data.
tar: invalid option -- 'z'
BusyBox v1.22.1 (2014-05-23 01:24:27 UTC) multi-call binary.

Usage: tar -[cxthvO] [-X FILE] [-T FILE] [-f TARFILE] [-C DIR] [FILE]...

Create, extract, or list files from a tar file

Operation:
 c  Create
 x  Extract
 t  List
 f  Name of TARFILE ('-' for stdin/out)
 C  Change to DIR before operation
 v  Verbose O  Extract to stdout
 h  Follow symlinks
 exclude        File to exclude
 X  File with names to exclude
 T  File with names to include

Failed to find taxonomy files.
The program must abort.
```

after running `docker run quay.io/biocontainers/clark:1.2.5.1--h6bb024c_0 /usr/local/opt/clark/set_targets.sh clark_db bacteria viruses fungi`

**Replace this sentence with a detailed description of your pull request**

----

> Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [ ] This PR adds a new recipe.
* [ ] AFAIK, this recipe **is directly relevant to the biological sciences**
      (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

> Everyone has access to the following BiocondaBot commands, which can be given in a comment:
>
>  * `@BiocondaBot please update` will cause the BiocondaBot to merge the master branch into a PR
>  * `@BiocondaBot please add label` will add the `please review & merge` label.
>  * `@BiocondaBot please fetch artifacts` will post links to packages and docker containers built by the CI system. You can use this to test packages locally before merging.
>
> For members of the Bioconda project, the following command is also available:
>
>  * `@BiocondaBot please merge` will cause packages/containers to be uploaded and a PR merged. Someone must approve a PR first! This has the benefit of not wasting CI build time required by manually merging PRs.
>
> If you have questions, please post them in gitter or ping `@bioconda/core` in a comment (if you are not able to directly ping `@bioconda/core` then the bot will repost your comment and enable pinging).

### CODE REVIEW

**Comment by aaguinal** [comment]
@BiocondaBot please update

**Comment by aaguinal** [comment]
@BiocondaBot please update

**Comment by aaguinal** [comment]
@BiocondaBot please add label

**Comment by dpryan79** [comment]
@bioconda-bot please fetch artifacts

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Pull request merged**
