### PR TITLE
Updating runtime dependency of vcfpy v0.11

### PR DESCRIPTION
**Pull request by holtgrewe**
`python` is missing

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by holtgrewe** [comment]
@bioconda/python Hm, could someone help me here? I have a problem with my package (I maintain `vcfpy` itself) and I thought I could fix this by adding the runtime dependency of `python`...

So (1) this build fails now. What am I doing wrong?

Also (2) with a fresh Miniconda install and Python 3.6, it fails as well:

```
# conda install vcfpy
# python --version
Python 3.6.4
# python -m vcfpy
/tmp/miniconda3/bin/python: No module named vcfpy
# conda install python=3.5
# python --version
Python 3.5.5
# python -c 'import vcfpy'
-> works
```

**Comment by mbargull** [comment]
@bgruening: The build failure is due to `mulled` pulling `continuumio/miniconda3:latest` which, unfortunately, has been updated to `4.4.10` a couple of hours ago: https://hub.docker.com/r/continuumio/miniconda/tags/. That caused the `mulled` build to run into https://github.com/conda/conda/issues/6811

**Comment by holtgrewe** [comment]
Ah, at least it's good to see that it's not my fault and software packaging is painful everywhere.

yikes! Thanks, I'll sit this one out then, I guess.

**Comment by mbargull** [comment]
I don't understand 
> Also (2) with a fresh Miniconda install and Python 3.6, it fails as well:

yet, though..

**Comment by mbargull** [comment]
Which version of `conda` did you use when you ran the update `python` update in (2)?

**Comment by mbargull** [comment]
Ah, sorry, misread
```bash
# conda install vcfpy
# python --version
Python 3.6.4
# python -m vcfpy
/tmp/miniconda3/bin/python: No module named vcfpy
```
So, instead of the previous question: What version of `vcfpy` was installed by `conda install vcfpy`?

**Comment by holtgrewe** [comment]
@mbargull The one in channel `bioconda`: `0.11.0-0`

**Comment by mbargull** [comment]
(Urgh, brain is slipping... should go to sleep...)
Right, that `vcfpy` package is broken since it is compiled with `python 3.5` but not pinned to that version. Your changes in this PR will fix this. We'll need to label the previous build as `broken` once this is merged and built.

**Comment by holtgrewe** [comment]
@bgruening @mbargull Can I do anything to speed up the resolution?

**Comment by bgruening** [comment]
@mbargull that would be bad. But this container is only used to install a package, this would mean that we can not install bioconda packages 4.4.10? Also I'm wondering why other PR pass if the container is broken. I will try to look into it at the evening.

**Comment by mbargull** [comment]
That bug is in `conda >4.4.7,<4.4.11` and is only hit with installing certain packages (and with Docker/overlay2 fs). See the comments from https://github.com/conda/conda/issues/6811#issuecomment-364894274 onward.
I don't know if it reliably fails or not. I'll just restart the build here one or two times.

**Comment by mbargull** [comment]
@holtgrewe: There is nothing I can currently do to resolve this faster. For now, we need changes from upstream project for this...

**Comment by holtgrewe** [comment]
Yay software development!

Thanks for the info. Let's wait.

**Comment by holtgrewe** [comment]
@mbargull How do I find out if it is fixed upstream?

**Comment by mbargull** [comment]
Hi Manuel, sorry for not informing you earlier, but @bgruening found a nice little workaround in https://github.com/bioconda/bioconda-recipes/pull/8056. Please just merge `master` and you should be good to go.

**Comment by holtgrewe** [comment]
Yay! @mbargull should we review regardlessly?

**Comment by holtgrewe** [comment]
I guess I'll just merge.

**Comment by mbargull** [comment]
Yes, totally fine, thanks!

**Pull request merged**
