### PR TITLE
Add ima3-1.12

### PR DESCRIPTION
**Pull request by lecorguille**
This PR is adding [IMa3](https://github.com/jodyhey/IMa3/)

But it still a licence. I requested one https://github.com/jodyhey/IMa3/issues/6#issuecomment-920694623

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by lecorguille** [comment]
Ping @bioconda/core, sorry but I need help to understand the issue here!

**Comment by dpryan79** [comment]
Hmm, MPI stuff can be quite tricky, can this be compiled with it?

**Comment by lecorguille** [comment]
@jodyhey  (author of Ima3) can you help us here?

**Comment by jodyhey** [comment]
sorry, what is being requested?    On Tuesday, September 28, 2021, 09:24:39 AM EDT, Gildas Le Corguillé ***@***.***> wrote:  
 
 


@jodyhey (author of Ima3) can you help us here?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lecorguille** [comment]
@jodyhey thanks for coming.
The building of the package succeed but the functional test failed.
You can have a look at the log [here](https://app.circleci.com/pipelines/github/bioconda/bioconda-recipes/53278/workflows/5fb227ef-7ad3-4502-9a0b-a5cb9869ce34/jobs/169748?invite=true#step-106-496)

Thanks by advance

**Comment by jodyhey** [comment]
That's too bad.  I took a quick look  but not much made sense to me.   some interaction between container and mpi 
    On Thursday, September 30, 2021, 04:08:29 AM EDT, Gildas Le Corguillé ***@***.***> wrote:  
 
 


@jodyhey thanks for coming.
The building of the package succeed but the functional test failed.
You can have a look at the log here

Thanks by advance

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lecorguille** [comment]
Cool, I picked this trick from mrbayes : https://github.com/bioconda/bioconda-recipes/blob/master/recipes/mrbayes/meta.yaml#L38

**Comment by lecorguille** [comment]
@BiocondaBot please add label

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
Looks good @lecorguille, merge when you like!

**Pull request merged**
