### PR TITLE
Bump octopus version to 0.6.3-beta

### PR DESCRIPTION
**Pull request by rspreafico-vir**
Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it. Note that if you are not already a member of the bioconda project (meaning that you can't add this label), please ping `@bioconda/core` so that your PR can be reviewed and merged (please note if you'd like to be added to the bioconda project). Please see https://github.com/bioconda/bioconda-recipes/issues/15332 for more details.

* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [ ] This PR adds a new recipe.
* [X] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [X] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by rspreafico-vir** [comment]
@dancooke @bgruening @dpryan79 Do you have any ideas why building fails just on Mac with HTSlib?

```
21:55:56 BIOCONDA INFO (ERR) -- Installation prefix: /Users/distiller/project/miniconda/conda-bld/octopus_1574833993285/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin
21:55:58 BIOCONDA INFO (ERR) HTSlib_INCLUDE_DIR=HTSlib_INCLUDE_DIR-NOTFOUND
21:55:58 BIOCONDA INFO (ERR) HTSlib_LIBRARY=/Users/distiller/project/miniconda/conda-bld/octopus_1574833993285/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/libhts.dylib
21:55:58 BIOCONDA INFO (ERR) CMake Error at build/cmake/modules/FindHTSlib.cmake:67 (message):
21:55:58 BIOCONDA INFO (ERR)   Required library HTSlib NOT FOUND.
21:55:58 BIOCONDA INFO (ERR) 
21:55:58 BIOCONDA INFO (ERR)   Install the library (dev version) and try again.  If the library is already
21:55:58 BIOCONDA INFO (ERR)   installed, use ccmake to set the missing variables manually.
21:55:58 BIOCONDA INFO (ERR) Call Stack (most recent call first):
21:55:58 BIOCONDA INFO (ERR)   build/cmake/modules/FindHTSlib.cmake:144 (libfind_process)
21:55:58 BIOCONDA INFO (ERR)   src/CMakeLists.txt:692 (find_package)
```

Also referencing here previous PR attempt for this recipe:

https://github.com/bioconda/bioconda-recipes/pull/13583

`boost` seems no longer an issue.

**Comment by dpryan79** [comment]
I hate cmake, I really do. I'll try something, but this may be one of those things where cmake needs to be told to find dylibs instead of .so files.

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Comment by rspreafico-vir** [comment]
Thank you @dpryan79 for the quick fix!

**Pull request merged**
