### PR TITLE
Increment build number on diamond.

### PR DESCRIPTION
**Pull request by yesimon**
Hopefully this will trigger a rebuild. The previous #393  didn't update the bioconda channel.

### CODE REVIEW

**Comment by bgruening** [comment]
@yesimon I see this version in bioconda. Can you recheck?

**Comment by yesimon** [comment]
The version in bioconda is improperly built where the diamond executable is in `$PREFIX`, not `$PREFIX/bin`.

**Comment by bgruening** [comment]
@yesimon now I see. You created a new files without updating the old ones. Can you please merge both file sets and increase the version number?

**Comment by yesimon** [comment]
I'm not sure I understand - I updated the version number in this commit, and previously updated the file set in #393.

**Comment by yesimon** [comment]
I see, there's another folder for 0.7.10. I've deleted that and updated the PR.

**Comment by bgruening** [comment]
Thanks!

**Pull request merged**
