### PR TITLE
Bracken 2.2

### PR DESCRIPTION
**Pull request by dfornika**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by dfornika** [comment]
Hmm... I'm a bit confused. Linting is failing with this error message:

```
15:57:08 BIOCONDA DEBUG lint recipes/bracken
	recipe	check	info	fix	should_be_noarch
0	recipes/bracken	should_be_noarch	"{'should_be_noarch': True, 'fix': 'add ""build: noarch"" section'}"	"add ""build: noarch"" section"	True
Exited with code 1
```

...but the Bioconda guidelines say not to use `noarch`:

http://bioconda.github.io/guidelines.html#id3

**Comment by druvus** [comment]
The documentation seems to be outdated even if changes were merged in bioconda/bioconda.github.io#21. 

@bgruening do you know why the documentation is not rerendered?

**Comment by dfornika** [comment]
I'm still a little confused because this isn't a pure python application, and does require compilation. So why is it failing linting?

**Comment by druvus** [comment]
kraken & kraken2 are still not rebuilt for osx so bracken needs to skip osx until they are ready.

**Pull request merged**
