### PR TITLE
Removed noarch python

### PR DESCRIPTION
**Pull request by micknudsen**
* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [X] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [X] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by micknudsen** [comment]
An attempt to fix the issue in https://github.com/bioconda/bioconda-recipes/pull/10811#event-1846139729.

**Comment by micknudsen** [comment]
@johanneskoester I think this will solve the problem in #10811

**Comment by micknudsen** [comment]
@johanneskoester Do you think this can be merged?

**Comment by johanneskoester** [comment]
Thanks!

**Pull request merged**
