### PR TITLE
Update savage to v0.4.0

### PR DESCRIPTION
**Pull request by jbaaijens**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by jbaaijens** [comment]
Finally we're done @johanneskoester! Could you also merge this one? Then I'll stop bothering you :)

**Comment by bgruening** [comment]
Thanks @jbaaijens!

**Comment by johanneskoester** [comment]
Thanks @bgruening. @jbaaijens no worries, I am always happy to help. Btw. are you already part of the bioconda team? For simple updates it is fine to merge yourself.

**Comment by jbaaijens** [comment]
Thank you both! @johanneskoester no I'm not part of the team yet, that would be great. Could you add me?

**Pull request merged**
