### PR TITLE
linux-aarch64 build for entrez-direct

### PR DESCRIPTION
**Pull request by rpetit3**
add linux-aarch64 build for entrez direct, looks like it might already have static binaries for linux arm (https://github.com/biostars/conda-ready-entrez-direct/blob/main/install.sh)

required for at least blast: https://github.com/bioconda/bioconda-recipes/pull/46237
----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

### General instructions

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

### Instructions for avoiding API, ABI, and CLI breakage issues
Conda is able to record and lock (a.k.a. pin) dependency versions used at build time of other recipes.
This way, one can avoid that expectations of a downstream recipe with regards to API, ABI, or CLI are violated by later changes in the recipe.
If not already present in the meta.yaml, make sure to specify `run_exports` (see [here](https://bioconda.github.io/contributor/linting.html#missing-run-exports) for the rationale and comprehensive explanation).
Add a `run_exports` section like this:

```yaml
build:
  run_exports:
    - ...

```

with `...` being one of:

| Case                             | run_exports statement                                               |
| -------------------------------- | ------------------------------------------------------------------- |
| semantic versioning              | `{{ pin_subpackage("myrecipe", max_pin="x") }}`     |
| semantic versioning (0.x.x)      | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}`   |
| known breakage in minor versions | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| known breakage in patch versions | `{{ pin_subpackage("myrecipe", max_pin="x.x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| calendar versioning              | `{{ pin_subpackage("myrecipe", max_pin=None) }}`    |

while replacing `"myrecipe"` with either `name` if a `name|lower` variable is defined in your recipe or with the lowercase name of the package in quotes.

### Bot commands for PR management

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

Note that the <code>@BiocondaBot please merge</code> command is now depreciated. Please just squash and merge instead.

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by rpetit3** [comment]
nice catch, tyvm

**Comment by rpetit3** [comment]
only hting that sticks out is `xtract` missing on ARM build, didn't see same error on linux side, waiting on mac build

```
21:26:18 BIOCONDA INFO (ERR) [Mar  6 21:26:18] SOUT Unable to locate xtract executable. Please execute the following:
21:26:18 BIOCONDA INFO (ERR) [Mar  6 21:26:18] SOUT
21:26:18 BIOCONDA INFO (ERR) [Mar  6 21:26:18] SOUT nquire -dwn ftp.ncbi.nlm.nih.gov entrez/entrezdirect xtract.UNSUPPORTED.gz
21:26:18 BIOCONDA INFO (ERR) [Mar  6 21:26:18] SOUT gunzip -f xtract.UNSUPPORTED.gz
21:26:18 BIOCONDA INFO (ERR) [Mar  6 21:26:18] SOUT chmod +x xtract.UNSUPPORTED
21:26:18 BIOCONDA INFO (ERR) [Mar  6 21:26:18] SOUT
```

**Comment by rpetit3** [comment]
OK, there are multiple wrapper scripts that we would need to patch similar to the install patch.

```
install.sh:  Linux-*arm* )            plt=ARM ;;
rchive:  Linux-*arm* )            platform=ARM ;;
transmute:  Linux-*arm* )            platform=ARM ;;
xtract:  Linux-*arm* )            platform=ARM ;;
```

I think given it is only 3 additional files, and it hasn't been touched in 3 years, I will just add patches for now with a note to review in the future if updates become more regular

**Comment by rpetit3** [comment]
Test results are now matching betweem x86 and arm

**Comment by aliciaaevans** [comment]
@BiocondaBot please fetch artifacts

**Comment by aliciaaevans** [comment]
@rpetit3 I wanted to test out the fetch artifacts comment bot updates that were just merged. Let me know if anything seems amiss with that comment.

**Comment by rpetit3** [comment]
So awesome @aliciaaevans thank you for adding that! Haha now I need to get a setup to test local ARM builds

**Comment by jmarshall** [comment]
> Test results are now matching betweem x86 and arm

What test results were those? In my smoke-testing on my bookworm VM I'm afraid I couldn't get the executables to work at all:

```
$ uname -a
Linux bookworm 6.1.0-13-arm64 #1 SMP Debian 6.1.55-1 (2023-09-29) aarch64 GNU/Linux
$ file *|grep -v script
build_env_setup.sh:       ASCII text, with very long lines (523)
conda_build.sh:           ASCII text
help:                     directory
rchive.ARM:               ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), statically linked, Go BuildID=YsSkROZAiTnp0l5oVxN5/s-PmAzwDBhUfRcgVQchf/SaMo-leVNaAaC6zGrnnm/6dTAgbefrxy8_HDGiYw_, not stripped
README:                   ASCII text, with very long lines (452)
transmute.ARM:            ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), statically linked, Go BuildID=BdCKTQ76ESUMCqoI9dOz/RWBCFGiDXSxgqxpYvA4_/wjc8ocF7z7i85jIk3a5q/38fmOr4Yt20peLP6Rn0H, not stripped
xtract.ARM:               ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), statically linked, Go BuildID=HonDWKs4-LLUi9jXwHZp/htTawLrs0VqUyU53JJS9/4gyGXV3SJX8-6TRWVHOJ/eaOWZWx5B_ZoBawB0aoT, not stripped
$ ./rchive.ARM 
-bash: ./rchive.ARM: cannot execute binary file: Exec format error
$ ./transmute.ARM 
-bash: ./transmute.ARM: cannot execute binary file: Exec format error
$ ./xtract.ARM 
-bash: ./xtract.ARM: cannot execute binary file: Exec format error
```

So it would appear that our patching has been in vain, and the supplied 32-bit ARM executables are insufficient for an aarch64 environment (or at least, one without a 32-bit runtime installed, which I'm guessing conda doesn't require?).

So we would need NCBI to provide either source code that we could compile ourselves or another set of pre-built executables for Linux-aarch64.

I also tried with the executables from https://ftp.ncbi.nlm.nih.gov/entrez/entrezdirect/ with the same results.

**Comment by jmarshall** [comment]
@aliciaaevans: I think it would be easier to find the artefacts you're looking for if there was just one table with linux-64 / osx-64 / linux-aarch64 / others-in-future in it. The (currently) two flavours of CI host have slightly different links and data, so the other columns would need a bit of reworking, but it seems manageable. This would also make the comment shorter.

**Comment by jmarshall** [comment]
There is one test in _meta.yaml_ that exercises one of the compiled executables (`- xtract -version`) and you're right, it did run and work on the CI host:

```
841    22:10:50 BIOCONDA INFO (OUT) 16.2
```

I've tried to install a 32-bit runtime on my VM but without luck so far… 🤷

**Comment by jmarshall** [comment]
Okay, it appears that [NCBI's edirect.tar.gz](https://ftp.ncbi.nlm.nih.gov/entrez/entrezdirect/versions/21.6.20240305/edirect.tar.gz) does contain sufficient Go source code that I've been able to compile what looks like a functional aarch64 `xtract` executable. So we should be able to rework this recipe to do a proper build from source that'll work on all three of our platforms — I'll have a look at that over the weekend.

**Comment by aliciaaevans** [comment]
> @aliciaaevans: I think it would be easier to find the artefacts you're looking for if there was just one table with linux-64 / osx-64 / linux-aarch64 / others-in-future in it. The (currently) two flavours of CI host have slightly different links and data, so the other columns would need a bit of reworking, but it seems manageable. This would also make the comment shorter.

@jmarshall Thanks for the input. I did consider something like that but left it broken out for now because the instructions were getting confusing. In the next PR to handle the images, I (or someone else if they beat me to it) can try to consolidate it into one table. Maybe putting the instructions in a collapsible section would help since more advanced users just want to get the links.

**Comment by rpetit3** [comment]
closing in favor of https://github.com/bioconda/bioconda-recipes/pull/46258

**Pull request closed without merging**
