### PR TITLE
Added recipe for SeqLib

### PR DESCRIPTION
**Pull request by micknudsen**
Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it. Note that if you are not already a member of the bioconda project (meaning that you can't add this label), please ping `@bioconda/core` so that your PR can be reviewed and merged (please note if you'd like to be added to the bioconda project). Please see https://github.com/bioconda/bioconda-recipes/issues/15332 for more details.

* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [X] This PR adds a new recipe.
* [X] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by micknudsen** [comment]
This is related to https://github.com/bioconda/bioconda-recipes/pull/16764. An attempt to avoid compiling submodules in SvABA.

**Comment by dpryan79** [comment]
Seems this needs the bwa source code

**Comment by micknudsen** [comment]
@dpryan79 Is there a recommended way of achieving this? Should I obtain the bwa code using `git clone` in `build.sh`?

**Comment by dpryan79** [comment]
You can actually put it in the meta.yaml, something like:

    source:
        - url: https://github.com/walaj/SeqLib/archive/{{ version }}.tar.gz
          sha256: d4679171b6c537f208a54cf4f4343f8068b35f401fa2170efffc74d7bd297892
        - url: where bwa is
          sha256: you get the idea
          folder: bwa

Then the bwa source code should get unpacked into the `bwa` subdirectory.

**Comment by micknudsen** [comment]
@dpryan79 Thanks. I run into problems, though, since the `bwa` folder already exists (but is empty). Maybe there is a force option, but I think the easiest solution will be to just clone the `v1.1.2` revision of `SeqLib` directly. However, this rather strange thing happens:

```
06:53:00 BIOCONDA INFO (ERR) Submodule 'bwa' (https://github.com/jwalabroad/bwa) registered for path 'bwa'
06:53:00 BIOCONDA INFO (ERR) Submodule 'fermi-lite' (https://github.com/jwalabroad/fermi-lite) registered for path 'fermi-lite'
06:53:00 BIOCONDA INFO (ERR) Submodule 'htslib' (https://github.com/samtools/htslib) registered for path 'htslib'
06:53:00 BIOCONDA INFO (ERR) Cloning into '/opt/conda/conda-bld/seqlib_1565592694990/work/bwa'...
06:53:01 BIOCONDA INFO (ERR) Cloning into '/opt/conda/conda-bld/seqlib_1565592694990/work/fermi-lite'...
06:53:03 BIOCONDA INFO (ERR) Cloning into '/opt/conda/conda-bld/seqlib_1565592694990/work/htslib'...
06:53:06 BIOCONDA INFO (OUT) Submodule path 'bwa': checked out 'c02766e3c34ac3f4af9842e20a54b7f9f4b36d0b'
06:53:06 BIOCONDA INFO (OUT) Submodule path 'fermi-lite': checked out '5bc90f8d70e2b66184eccbd223a3be714c914365'
06:53:08 BIOCONDA INFO (ERR) error: Server does not allow request for unadvertised object 5163833ede355f8c2a6788780c55d7598279e767
06:53:08 BIOCONDA INFO (ERR) Fetched in submodule path 'htslib', but it did not contain 5163833ede355f8c2a6788780c55d7598279e767. Direct fetching of that commit failed.
06:53:08 BIOCONDA INFO (OUT) checkout: 'c53bd037292b2e2dbfac05d13f1b5b57381dfece'
```

The `SeqLib` [revision](https://github.com/walaj/SeqLib/tree/c53bd037292b2e2dbfac05d13f1b5b57381dfece) points to `htslib@5163833`, but it apparently tries to check out a different revision? Everything looks fine for `fermi-lite` and `bwa`.

Do you have any clue what could be going on here?

**Comment by dpryan79** [comment]
I wonder if that commit in htslib was on a deleted branch.

**Comment by micknudsen** [comment]
Giving up. Will focus on making #16764 work instead.

**Pull request closed without merging**
