### PR TITLE
Update coinfinder to v1.2.0

### PR DESCRIPTION
**Pull request by fwhelan**
Update version of coinfinder from 1.0.9 to 1.2.0

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by fwhelan** [comment]
@BiocondaBot please add label

**Comment by cbrueffer** [comment]
I've merged the bot-raised update PR (https://github.com/bioconda/bioconda-recipes/pull/34907) instead of this, since that used a clean branch. The Bioconda bot usually opens an update PR itself which you can review and merge yourself; typically there's no need to open a separate PR (which someone else has to review/merge then).

**Comment by fwhelan** [comment]
Thanks @cbrueffer; apologies, still new to this! I'll keep that in mind for the next version, cheers.

**Comment by cbrueffer** [comment]
No problem at all! Always great to see tool authors maintaining their own software in Bioconda.

**Comment by fwhelan** [comment]
Hi @cbrueffer. The last version of coinfinder that I released doesn't seem to have a bot-raised PR for it https://github.com/fwhelan/coinfinder/releases/tag/1.2.1. Should I raise one manually? (is there something I missed when pushing the release that caused the bot to miss raising a PR?). Thanks!

**Comment by cbrueffer** [comment]
Hi @fwhelan , not sure why the bot didn't trigger, but yes, please raise one manually!

**Pull request closed without merging**
