### PR TITLE
Adding mea recipe

### PR DESCRIPTION
**Pull request by jfallmann**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by jfallmann** [comment]
@bgruening Hi, just starting, have to test this way, in meeting, will clean up code later, do not merge yet

**Comment by jfallmann** [comment]
@bgruening linux test works, mac osx is skipped, feel free to merge from my side

**Comment by johanneskoester** [comment]
Thanks!

**Comment by bgruening** [comment]
Gracias!

**Pull request merged**
