### PR TITLE
Autoconf

### PR DESCRIPTION
**Pull request by dyusuf**
* [x] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by dyusuf** [comment]
atuconf passed travis test on both GNU and BSD

while, then unexpectedly
OSError: [Errno 28] No space left on device :)

**Comment by dyusuf** [comment]
restarted the build, the problem is gone.

**Comment by druvus** [comment]
Thanks for the work around to fix this issue.

You should just use perl-threaded instead of perl as indicated in the guidelines.

**Comment by dyusuf** [comment]
@druvus welcome. regarding perl vs per-threaded, I referenced the conda-forge recipe. but probably both are ok.

**Comment by dyusuf** [comment]
@daler @bgruening while merging, "OSError: [Errno 28] No space left on device" appears again for the Linux build. are we running out of the space? https://travis-ci.org/bioconda/bioconda-recipes/builds/173783720

**Comment by johanneskoester** [comment]
We still haven't even reached 50% of our anaconda space. But it looks like a no space left error on the travis machine. Does any of the new changes to bioconda-utils cause a lot of stuff to be written to disk? Maybe the on-the-fly container building?

**Comment by bgruening** [comment]
@johanneskoester the containers roughly double the amount of space that is needed. It can be the issue but I see this happen very infrequently and non-predictable. The OSX images do not have this problem and often the build fails during upload to anaconda.org or during website generation.

**Comment by johanneskoester** [comment]
Website generation is also creating lots of files. Can we clean up in between?

**Comment by daler** [comment]
I bet the issue is bioconda-utils' docker usage. Docker-py defaults to `remove=True`. When I switched over to subprocess I copied the commands verbatim and forgot to add the `--rm`, so every recipe built has a container still sticking around. I'll fix that.

The docs might be contributing too. We might want to consider something different than sphinx for the autogenerated recipe docs.

**Pull request merged**
