### PR TITLE
pirate 1.0.2

### PR DESCRIPTION
**Pull request by tseemann**
Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it. Note that if you are not already a member of the bioconda project (meaning that you can't add this label), please ping `@bioconda/core` so that your PR can be reviewed and merged (please note if you'd like to be added to the bioconda project). Please see https://github.com/bioconda/bioconda-recipes/issues/15332 for more details.

* [ ] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [ ] This PR adds a new recipe.
* [ ] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by tseemann** [comment]
@SionBayliss Seems it succeeds (exit 0) when --check fails?

```
01:46:59 BIOCONDA INFO (ERR) [Oct  2 01:46:59] SOUT Running PIRATE on test files:
01:47:01 BIOCONDA INFO (ERR) [Oct  2 01:47:01] SERR xargs: invalid option -- 'I'
01:47:01 BIOCONDA INFO (ERR) [Oct  2 01:47:01] SERR BusyBox v1.22.1 (2014-05-23 01:24:27 UTC) multi-call binary.
01:47:01 BIOCONDA INFO (ERR) [Oct  2 01:47:01] SERR
01:47:01 BIOCONDA INFO (ERR) [Oct  2 01:47:01] SERR Usage: xargs [OPTIONS] [PROG ARGS]
01:47:01 BIOCONDA INFO (ERR) [Oct  2 01:47:01] SERR
01:47:01 BIOCONDA INFO (ERR) [Oct  2 01:47:01] SERR Run PROG on every item given by stdin
01:47:01 BIOCONDA INFO (ERR) [Oct  2 01:47:01] SERR
01:47:01 BIOCONDA INFO (ERR) [Oct  2 01:47:01] SERR -r	Don't run command if input is empty
01:47:01 BIOCONDA INFO (ERR) [Oct  2 01:47:01] SERR -0	Input is separated by NUL characters
01:47:01 BIOCONDA INFO (ERR) [Oct  2 01:47:01] SERR -t	Print the command on stderr before execution
01:47:01 BIOCONDA INFO (ERR) [Oct  2 01:47:01] SERR -e[STR]	STR stops input processing
01:47:01 BIOCONDA INFO (ERR) [Oct  2 01:47:01] SERR -n N	Pass no more than N args to PROG
01:47:01 BIOCONDA INFO (ERR) [Oct  2 01:47:01] SERR -s N	Pass command line of no more than N bytes
01:47:01 BIOCONDA INFO (ERR) [Oct  2 01:47:01] SERR -x	Exit if size is exceeded
01:47:01 BIOCONDA INFO (ERR) [Oct  2 01:47:01] SERR
01:47:02 BIOCONDA INFO (ERR) [Oct  2 01:47:01] SERR - ERROR: pangenome_construction.pl failed - error logged at /tmp/opxPot57Fa/fail_test.txt
01:47:02 BIOCONDA INFO (ERR) [Oct  2 01:47:02] SOUT - ERROR: PIRATE did not run correctly:
01:47:02 BIOCONDA INFO (ERR) [Oct  2 01:47:02] SOUT - ERROR: PIRATE was not able to construct pangenome
01:47:02 BIOCONDA INFO (ERR) [Oct  2 01:47:02] SOUT - ERROR: PIRATE was not able to classify paralogs
01:47:02 BIOCONDA INFO (ERR) [Oct  2 01:47:02] SOUT - ERROR: PIRATE could not make summary files
01:47:02 BIOCONDA INFO (ERR) [Oct  2 01:47:02] SOUT
01:47:02 BIOCONDA INFO (ERR) [Oct  2 01:47:02] SOUT - WARNING: PIRATE could not make binary tree (is fasttree installed)
01:47:02 BIOCONDA INFO (ERR) [Oct  2 01:47:02] SOUT - WARNING: PIRATE could not make R plots (are dependencies installed)
```

**Comment by bgruening** [comment]
Gracias!

**Comment by tseemann** [comment]
@npavlovikj @tseemann why was this PR merged?
i clearly commented that it was failing its internal tests (despite them returning 0).

**Comment by npavlovikj** [comment]
Sorry about the confusion @tseemann  - I saw your comment about the failing, and just approved the PR so you can merge it after those tests pass (since the recipe looks ok and the failing is not because of the recipe itself)... Looks like Bjorn was faster and merged the recipe in the meantime.

**Comment by tseemann** [comment]
@npavlovikj Ah ok. Well there is an issue of the `xargs` in the test environment not supporting the `-I` option in GNU xargs. I'm assuming busybox has a cut-down version of xargs. I could not find a conda package with a modern xargs. Do you know which one it is in?

**Comment by npavlovikj** [comment]
@tseemann , I would suggest you to use the extended base:
```
extra:
  container:
    extended-base: true
```

I just tried the mulled tests locally with that change, and I believe the tests finished fine:
```
01:31:57 BIOCONDA INFO (ERR) [Oct  3 01:31:57] SOUT Running PIRATE on test files:
.01:32:06 BIOCONDA INFO (ERR) [Oct  3 01:32:06] SOUT
01:32:06 BIOCONDA INFO (ERR) [Oct  3 01:32:06] SOUT - PIRATE completed with no errors
01:32:06 BIOCONDA INFO (ERR) [Oct  3 01:32:06] SOUT - WARNING: PIRATE could not make R plots (are dependencies installed?)
01:32:06 BIOCONDA INFO (ERR) [Oct  3 01:32:06] SOUT
01:32:06 BIOCONDA INFO (ERR) [Oct  3 01:32:06] SOUT - tests completed
01:32:06 BIOCONDA INFO (ERR) [Oct  3 01:32:06] SOUT
01:32:06 BIOCONDA INFO (ERR) [Oct  3 01:32:06] SOUT - temporary files saved to /tmp/q8x5G99_4h
01:32:06 BIOCONDA INFO (ERR) [Oct  3 01:32:06] SOUT
01:32:06 BIOCONDA INFO (ERR) [Oct  3 01:32:06] DEBU Container [3a9bd8ad17b8 step-c242dee52a] completed with exit code [0] as expected
01:32:07 BIOCONDA INFO (ERR) [Oct  3 01:32:07] DEBU Container [3a9bd8ad17b8 step-c242dee52a] removed
```

**Comment by tseemann** [comment]
@npavlovikj  thank you! for enlightening me and for checking it works. this is good news for @sionBayliss

**Comment by SionBayliss** [comment]
@tseemann @npavlovikj Thanks for your help on this. I just checked the package and it installs correctly and runs on an example dataset. The plotting script doesn't work due to a newer version of some of the packages not installing their own dependencies. @npavlovikj should I prepare a pull request with the fixed version of the r-packages? I have checked them and they function correctly.

**Comment by npavlovikj** [comment]
I couldn't check out this branch, so opened a new PR with adding the extended-base, https://github.com/bioconda/bioconda-recipes/pull/17831.
@tseemann , @SionBayliss  - please feel free to review/comment on that PR.
@SionBayliss , do you have a new release, or additional requirements of R packages? If so, we can add them in the new PR if that works.

**Comment by SionBayliss** [comment]
@npavlovikj - the R dependencies work fine when fixed to specific versions. Would you recommend this as part of the main package? Alternatively, the R dependencies could be removed as I have included these as optional dependencies to the main package in the README. In either case the R dependencies are:

```
r==3.5.1 
r-ggplot2==3.1.0 
r-dplyr==0.7.6 
bioconductor-ggtree==1.14.4 
r-phangorn==2.4.0 
r-gridextra
```
I have made a new release (v1.0.3) which contains some very minor changes. 
Sorry for my ignorance, how easy is it to update the bioconda recipe to include a new release in the future? Also, do we need to build a new recipe for Mac or will this work? I had a user query this recently and I works fine after installing the deps individually but did not work from conda install -c mychannel pirate.

**Comment by npavlovikj** [comment]
@SionBayliss , what error the pinning solves? `WARNING: PIRATE could not make R plots`? In general, it is not recommended to pin a specific version - that may cause compatibility errors between packages.

The update of the recipe is really easy - beside humans, there is a bot that checks for new releases and opens new PR (actually, looks like there is already a new PR for pirate, https://github.com/bioconda/bioconda-recipes/pull/17948).

This Bioconda recipe is defined as "noarch:generic", which means it will work on both Linux and OSX platforms. I don't know how the one on your channel is built, but I would suggest you to use `conda install -c bioconda pirate` and try on Mac.

**Comment by SionBayliss** [comment]
@npavlovikj I wasn't aware that bioconda was so efficient :). If that is the case could we remove the R dependencies from the recipe altogether? The warning ```WARNING: PIRATE could not make R plots``` doesn't produce an error and installation options for the R dependencies are detailed in the README. I will test the current release on Mac and see how it goes.

**Comment by npavlovikj** [comment]
@SionBayliss , sorry for my delay - I got busy with work.

If you already have a ready branch, please go ahead and open PR in bioconda, and feel free to tag me for review. In case you are not sure for the steps, please check https://bioconda.github.io/contributor/workflow.html. 
Personally, I think it is better if the optional R dependencies stay in the recipe. I haven't checked why the newer versions don't work though, maybe those packages need to be updated?

Regarding the older versions - you can find all versions in the channel itself, https://anaconda.org/bioconda/pirate/files. It is only in the recipe directory that the newest release is kept.

**Comment by SionBayliss** [comment]
@npavlovikj I know how that feels :). I did a little debugging of the Rscripts and there are some dependency issues with the most recent versions of the R libs. One of the libraries, I think phangorn, has a dependency on phytools which is not installing correctly due to a library that isn't being correctly identified, even when it is present. I am open to including the optional dependencies if they are fixed or if they will install correctly via conda. I would currently prefer to remove them as I don't want users to be given the wrong impression that PIRATE includes a broken script when the dependencies for the script can be easily installed via the README. I am happy to update the recipe or script with later releases. I have posted a pull request but I am not a member of the project so I couldn't tag it ( #18128 ).

**Pull request merged**
