### PR TITLE
sourmash 3.0.0

### PR DESCRIPTION
**Pull request by luizirber**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [x] This PR does something else (explain below).

Updates recipe to account for build system changes (it uses Rust now)

### CODE REVIEW

**Comment by npavlovikj** [comment]
@luizirber , I believe the reason for not building is because you have removed the "build" part, which comes with `script: "{{ PYTHON }} -m pip install --no-deps --ignore-installed -vv ."`. In your current recipe, there is nothing to be built. Please add the missing line, and re-try again.

**Comment by npavlovikj** [comment]
@luizirber , can you also rebase your branch with master?

**Comment by luizirber** [comment]
@ npavlovikj thanks for checking this!

Do I need the `script:` part when there is a `build.sh` file? Seems like all Rust recipes need to have to set the HOME dir for macOS?

I also noticed I had CircleCI set up in my fork, so I disabled that and seems like the checks are working now.

**Comment by luizirber** [comment]
From the output logs, seems like I should also add dependencies to `libgcc-ng` and `gcc_impl_linux-64` (on the Linux build), are those set up by `{{ compiler('c') }}`?

<details>
19:01:17 BIOCONDA INFO (OUT)    INFO (sourmash,lib/python2.7/site-packages/sourmash/_lowlevel__lib.so): Needed DSO x86_64-conda_cos6-linux-gnu/sysroot/lib/libc.so.6 found in CDT/compiler package conda-forge::gcc_impl_linux-64-7.3.0-habb00fd_2
19:01:17 BIOCONDA INFO (OUT)    INFO (sourmash,lib/python2.7/site-packages/sourmash/_lowlevel__lib.so): Needed DSO x86_64-conda_cos6-linux-gnu/sysroot/lib/libpthread.so.0 found in CDT/compiler package conda-forge::gcc_impl_linux-64-7.3.0-habb00fd_2
19:01:17 BIOCONDA INFO (OUT)    INFO (sourmash,lib/python2.7/site-packages/sourmash/_lowlevel__lib.so): Needed DSO x86_64-conda_cos6-linux-gnu/sysroot/lib/ld-linux-x86-64.so.2 found in CDT/compiler package conda-forge::gcc_impl_linux-64-7.3.0-habb00fd_2
19:01:17 BIOCONDA INFO (OUT)    INFO (sourmash,lib/python2.7/site-packages/sourmash/_lowlevel__lib.so): Needed DSO x86_64-conda_cos6-linux-gnu/sysroot/lib/libm.so.6 found in CDT/compiler package conda-forge::gcc_impl_linux-64-7.3.0-habb00fd_2
19:01:17 BIOCONDA INFO (OUT)    INFO (sourmash,lib/python2.7/site-packages/sourmash/_lowlevel__lib.so): Needed DSO x86_64-conda_cos6-linux-gnu/sysroot/lib/libdl.so.2 found in CDT/compiler package conda-forge::gcc_impl_linux-64-7.3.0-habb00fd_2
19:01:17 BIOCONDA INFO (OUT)    INFO (sourmash,lib/python2.7/site-packages/sourmash/_lowlevel__lib.so): Needed DSO x86_64-conda_cos6-linux-gnu/sysroot/lib/librt.so.1 found in CDT/compiler package conda-forge::gcc_impl_linux-64-7.3.0-habb00fd_2
19:01:17 BIOCONDA INFO (OUT) WARNING (sourmash,lib/python2.7/site-packages/sourmash/_lowlevel__lib.so): Needed DSO lib/libgcc_s.so.1 found in ['libgcc-ng']
19:01:17 BIOCONDA INFO (OUT) WARNING (sourmash,lib/python2.7/site-packages/sourmash/_lowlevel__lib.so): .. but ['libgcc-ng'] not in reqs/run, (i.e. it is overlinking) (likely) or a missing dependency (less likely)
19:01:17 BIOCONDA INFO (OUT)    INFO (sourmash): plugin library package conda-forge::cffi-1.13.2-py27h8022711_0 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
</details>

If so... I have a question about the `lint` step: The Rust extension is using `cffi` for interfacing with Python, and one advantage is that the Python package can be universal: only one package is needed per platform (linux/osx), instead of one per platform and Python version combination. But if I leave the `{{ compiler('c')` and try to set `python: noarch` in the build, it complaing because I'm setting a compiler. What should I change to make it possible to be an universal package?

**Comment by luizirber** [comment]
@BiocondaBot please fetch artifacts

**Comment by luizirber** [comment]
> If so... I have a question about the `lint` step: The Rust extension is using `cffi` for interfacing with Python, and one advantage is that the Python package can be universal: only one package is needed per platform (linux/osx), instead of one per platform and Python version combination. But if I leave the `{{ compiler('c') }}` and try to set `python: noarch` in the build, it complaing because I'm setting a compiler. What should I change to make it possible to be an universal package?

Answering my own question: [`noarch: python`][0] is not for packages with extensions, only for pure Python packages... Is there an equivalent of the "one wheel per platform" in conda?
[0]: https://docs.conda.io/projects/conda/en/latest/user-guide/concepts/packages.html#noarch-packages

**Comment by luizirber** [comment]
> Do I need the `script:` part when there is a `build.sh` file? Seems like all Rust recipes need to have to set the HOME dir for macOS?

Just hit this problem with macOS, copying the `build.sh` from `varlociraptor` (which was in turn copied from `yacrd`) and checking if it works.

**Comment by luizirber** [comment]
Hmm, not sure why the macOS build failed in https://app.circleci.com/jobs/github/bioconda/bioconda-recipes/88681. py27 was built, but then it failed when trying to compile py36?

**Comment by luizirber** [comment]
> Hmm, not sure why the macOS build failed in https://app.circleci.com/jobs/github/bioconda/bioconda-recipes/88681. py27 was built, but then it failed when trying to compile py36?

Found it. There is a `git config` command in build.sh that fails if it was already unset (which happened in the py27 build), so I added a `|| true` to avoid erroring out. Although... this is copied from varlociraptor/yacrd, not even sure if it's needed for this recipe.

**Comment by luizirber** [comment]
@BiocondaBot please fetch artifacts

**Comment by luizirber** [comment]
Now that recipe is working... It's probably easier to wait a bit and update directly to `3.0.0` instead of merging the `rc1`, so.. please don't merge =]

**Comment by luizirber** [comment]
OK, good for merging now!

**Comment by luizirber** [comment]
@BiocondaBot please merge

**Comment by luizirber** [comment]
Fixed in #19533

**Pull request closed without merging**
