### PR TITLE
epic2: 0.0.36 create-bigwigs

### PR DESCRIPTION
**Pull request by endrebak**
Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it. Note that if you are not already a member of the bioconda project (meaning that you can't add this label), please ping `@bioconda/core` so that your PR can be reviewed and merged (please note if you'd like to be added to the bioconda project). Please see https://github.com/bioconda/bioconda-recipes/issues/15332 for more details.

* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [X] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [X] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by endrebak** [comment]
I just pointed to the MIT license. Did not mean to be flippant.

**Comment by epruesse** [comment]
Well, technically you should just add it to your `MANIFEST.in` so it gets distributed and then can be included here. For MIT license, this isn't mandatory, but since licenses often get modified, it's just better to have the exact file that you put into your repo distributed with the package. It the thing that you use to give us and others license to use your tool, so good practice to keep it with the code.

**Comment by epruesse** [comment]
@biocondabot lint

**Comment by epruesse** [comment]
Ah, thanks @dpryan79.

@endrebak - Best would be to do as I mentioned above, add the file `LICENSE` to your Python package.

**Comment by dpryan79** [comment]
@endrebak The license you use (MIT) requires that a copy of the license be distributed with the package. In practice this is rarely done, but it really should be to maintain compliance. I've added a copy to the recipe.

**Comment by dpryan79** [comment]
@bioconda-bot merge

**Pull request merged**
