### PR TITLE
Rebuild nullarbor container

### PR DESCRIPTION
**Pull request by rpetit3**
Current container is not working, attempting to rebuild

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by rpetit3** [comment]
@biocondabot please fetch artifacts

**Comment by rpetit3** [comment]
Busy Box version of grep is missing parameters used by Nullarbor

```
grep: invalid option -- 'P'
BusyBox v1.32.1 (2021-04-13 11:15:36 UTC) multi-call binary.

Usage: grep [-HhnlLoqvsrRiwFE] [-m N] [-A/B/C N] PATTERN/-e PATTERN.../-f FILE [FILE]...

Search for PATTERN in FILEs (or stdin)

        -H      Add 'filename:' prefix
        -h      Do not add 'filename:' prefix
        -n      Add 'line_no:' prefix
        -l      Show only names of files that match
        -L      Show only names of files that don't match
        -c      Show only count of matching lines
        -o      Show only the matching part of line
        -q      Quiet. Return 0 if PATTERN is found, 1 otherwise
        -v      Select non-matching lines
        -s      Suppress open and read errors
        -r      Recurse
        -R      Recurse and dereference symlinks
        -i      Ignore case
        -w      Match whole words only
        -x      Match whole lines only
        -F      PATTERN is a literal (not regexp)
        -E      PATTERN is an extended regexp
        -m N    Match up to N times per file
        -A N    Print N lines of trailing context
        -B N    Print N lines of leading context
        -C N    Same as '-A N -B N'
        -e PTRN Pattern to match
        -f FILE Read pattern from file
[17:21:33] ERROR: Could not determine shovill version using '--version':
```

**Comment by rpetit3** [comment]
@BiocondaBot please fetch artifacts

**Comment by rpetit3** [comment]
@BiocondaBot please fetch artifacts

**Comment by rpetit3** [comment]
### Testing Docker container

Using S. aureus genomes
```
cat inputs.txt
SRX4563686      /data/fastqs/SRX4563686_R1.fastq.gz     /data/fastqs/SRX4563686_R2.fastq.gz
SRX4563687      /data/fastqs/SRX4563687_R1.fastq.gz     /data/fastqs/SRX4563687_R2.fastq.gz
SRX4563688      /data/fastqs/SRX4563688_R1.fastq.gz     /data/fastqs/SRX4563688_R2.fastq.gz
SRX4563689      /data/fastqs/SRX4563689_R1.fastq.gz     /data/fastqs/SRX4563689_R2.fastq.gz
SRX4563690      /data/fastqs/SRX4563690_R1.fastq.gz     /data/fastqs/SRX4563690_R2.fastq.gz
```

### Run nullarbor

```
docker run --rm -u $(id -u):$(id -g) -v ${PWD}:/data quay.io/biocontainers/nullarbor:2.0.20191013--hdfd78af_3 bash -c 'KRAKEN_DEFAULT_DB=/data/kraken_db KRAKEN2_DEFAULT_DB=/data/kraken2_db CENTRIFUGE_DEFAULT_DB=/data/centrifuge/p_compressed+h+v nullarbor.pl --name test-bioconda --ref /data/GCF_000013425.gbff --input /data/inputs.txt --outdir /data/nullarbor-test --mlst saureus --taxoner kraken2 --run'
[00:05:01] Hello stranger
[00:05:01] This is nullarbor.pl 2.0.20191013
[00:05:01] Send complaints to Torsten Seemann
[00:05:01] Scanning --ref for problematic sequence IDs...
[00:05:01] Using reference genome: /data/GCF_000013425.gbff
[00:05:01] Loaded 5 isolates: SRX4563686 SRX4563687 SRX4563688 SRX4563689 SRX4563690
[00:05:01] Found 'mlst' => /usr/local/bin/mlst
[00:05:01] This is mlst 2.22.0 running on linux with Perl 5.026002
[00:05:01] Checking mlst dependencies:
[00:05:01] Found 'blastn' => /usr/local/bin/blastn
[00:05:01] Found 'any2fasta' => /usr/local/bin/any2fasta
[00:05:02] Found blastn: 2.12.0+ (002012)
[00:05:02] Found 144 MLST schemes
[00:05:02] Using scheme: saureus
[00:05:02] Making output folder: /data/nullarbor-test
[00:05:02] Found Perl module: Bio::SeqIO
... TRUNCATED ...
[00:59:03] Generating: virulome
[00:59:03] Generating: assembly
[00:59:03] Generating: reference
[00:59:03] Generating: core
[00:59:03] Generating: phylotree
[00:59:03] Generating: snpdist
[00:59:03] Generating: snpdensity
[00:59:03] Generating: pan
[00:59:03] Generating: tools
Use of uninitialized value $ver in scalar chomp at /usr/local/bin/../perl5/Nullarbor/Module/tools.pm line 51.
Use of uninitialized value $ver in substitution (s///) at /usr/local/bin/../perl5/Nullarbor/Module/tools.pm line 53.
Use of uninitialized value $ver in substitution (s///) at /usr/local/bin/../perl5/Nullarbor/Module/tools.pm line 53.
[00:59:06] Generating: databases
[00:59:06] Generating: about
[00:59:06] Results in: /data/nullarbor-test/report/index.html
[00:59:06] Done.
```

Log file is attached with `.txt` extension to make Github Happy

[index.html.txt](https://github.com/bioconda/bioconda-recipes/files/9075609/index.html.txt)
[nullarbor.log.txt](https://github.com/bioconda/bioconda-recipes/files/9075610/nullarbor.log.txt)

**Comment by rpetit3** [comment]
@BiocondaBot please add label

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
Great work @rpetit3

**Comment by bgruening** [comment]
@BiocondaBot please merge

**Comment by rpetit3** [comment]
Thank you!

**Pull request merged**
