### PR TITLE
bump camera to take xcms 3.0.x ; unblacklist camera

### PR DESCRIPTION
**Pull request by lecorguille**
* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [X] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [X] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by lecorguille** [comment]
Is anyone have an idea how to get more information?
I can't reproduce this locally.

**Comment by bgruening** [comment]
Narf, now bioconda-utils is broken on master. No luck today.

**Comment by bgruening** [comment]
The pkg is now available.

**Comment by lecorguille** [comment]
It doesn't use the last bioconductor-xcms 3.0.0


```
conda create -n bioconductor-camera-build2 bioconductor-camera
```

```
The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    r-irlba-2.3.2              |         r3.4.1_0         263 KB  conda-forge
    r-pkgconfig-2.0.1          |         r3.4.1_0          20 KB  conda-forge
    wheel-0.31.0               |           py36_0          62 KB  conda-forge
    r-acepack-1.4.1            |         r3.4.1_0          59 KB  conda-forge
    r-reshape2-1.4.3           |         r3.4.1_0         120 KB  conda-forge
    r-r6-2.2.2                 |         r3.4.1_0         255 KB  conda-forge
    cairo-1.14.12              |       he56eebe_0         1.3 MB  conda-forge
    r-yaml-2.1.18              |         r3.4.1_0          92 KB  conda-forge
    libxml2-2.9.8              |       h422b904_1         1.8 MB  conda-forge
    r-rpart-4.1_13             |         r3.4.1_0         912 KB  conda-forge
    libgfortran-ng-7.2.0       |       hdf63c60_3         1.2 MB
    python-3.6.5               |                1        21.0 MB  conda-forge
    r-iterators-1.0.9          |         r3.4.1_0         314 KB  conda-forge
    bioconductor-mzr-2.10.0    |      boost1.64_0         4.1 MB  bioconda
    r-gridextra-2.3            |         r3.4.1_0         1.0 MB  conda-forge
    r-hmisc-4.0_3              |         r3.4.1_0         1.7 MB  conda-forge
    hdf5-1.10.2                |                0         4.8 MB  conda-forge
    libtiff-4.0.9              |       he6b73bb_1         521 KB  conda-forge
    r-checkmate-1.8.5          |         r3.4.1_0         551 KB  conda-forge
    r-htmltable-1.9            |         r3.4.1_0         208 KB  conda-forge
    bioconductor-camera-1.34.0 |   r341ha44fe06_2         2.5 MB  bioconda
    r-rlang-0.2.1              |           r341_0         792 KB  conda-forge
    pixman-0.34.0              |                2         1.2 MB  conda-forge
    r-glue-1.2.0               |         r3.4.1_0          62 KB  conda-forge
    bioconductor-xcms-1.48.0   |         r3.4.1_1         887 KB  bioconda
    r-nnet-7.3_12              |         r3.4.1_0         116 KB  conda-forge
    pip-9.0.3                  |           py36_0         1.7 MB  conda-forge
    ca-certificates-2018.4.16  |                0         139 KB  conda-forge
    bioconductor-rbgl-1.54.0   |         r3.4.1_0         3.6 MB  bioconda
    r-viridislite-0.3.0        |         r3.4.1_0          59 KB  conda-forge
    r-matrix-1.2_14            |         r3.4.1_0         2.4 MB  conda-forge
    r-base-3.4.1               |                4        23.0 MB  conda-forge
    openssl-1.0.2o             |                0         3.5 MB  conda-forge
    xorg-kbproto-1.0.7         |       h470a237_2          25 KB  conda-forge
    pango-1.40.14              |       hd50be51_1         527 KB  conda-forge
    r-stringi-1.2.3            |           r341_0         704 KB  conda-forge
    libiconv-1.15              |       h470a237_1         2.0 MB  conda-forge
    r-viridis-0.5.1            |         r3.4.1_0         1.8 MB  conda-forge
    libssh2-1.8.0              |       h5b517e9_2         240 KB  conda-forge
    mkl_random-1.0.1           |           py36_0         1.3 MB  conda-forge
    certifi-2018.4.16          |           py36_0         142 KB  conda-forge
    r-xtable-1.8_2             |         r3.4.1_0         693 KB  conda-forge
    jpeg-9c                    |       h470a237_0         230 KB  conda-forge
    graphite2-1.3.11           |       hfc679d8_0         119 KB  conda-forge
    r-htmltools-0.3.6          |         r3.4.1_0         144 KB  conda-forge
    r-doparallel-1.0.11        |         r3.4.1_0         184 KB  conda-forge
    r-data.table-1.10.4        |         r3.4.1_0         1.2 MB  bioconda
    r-digest-0.6.15            |         r3.4.1_0         122 KB  conda-forge
    r-assertthat-0.2.0         |         r3.4.1_0          58 KB  conda-forge
    r-htmlwidgets-1.0          |         r3.4.1_0         748 KB  conda-forge
    xorg-renderproto-0.11.1    |       h470a237_2           8 KB  conda-forge
    xorg-libxau-1.0.8          |       h470a237_4          14 KB  conda-forge
    r-lazyeval-0.2.1           |         r3.4.1_0         120 KB  conda-forge
    r-rngtools-1.3.1           |           r341_0          58 KB  conda-forge
    r-backports-1.1.2          |         r3.4.1_0          54 KB  conda-forge
    xorg-xproto-7.0.31         |       h470a237_7          72 KB  conda-forge
    r-registry-0.5             |         r3.4.1_0         191 KB  conda-forge
    numpy-1.14.2               |   py36hdbf6ddf_1         4.1 MB
    r-foreign-0.8_67           |         r3.4.1_0         243 KB  conda-forge
    curl-7.60.0                |                0         855 KB  conda-forge
    r-gridbase-0.4_7           |         r3.4.1_0         164 KB  conda-forge
    r-foreach-1.4.4            |         r3.4.1_0         373 KB  conda-forge
    r-nmf-0.21.0               |         r3.4.1_0         2.4 MB  conda-forge
    fontconfig-2.13.0          |                1         966 KB  conda-forge
    libnetcdf-4.6.1            |       h5e45101_3         1.3 MB  conda-forge
    xorg-libxdmcp-1.1.2        |       h470a237_4          22 KB  conda-forge
    r-latticeextra-0.6_28      |         r3.4.1_0         2.0 MB  conda-forge
    r-highr-0.7                |           r341_0          34 KB  conda-forge
    r-pillar-1.2.2             |   r341h6115d3f_1          98 KB  conda-forge
    r-evaluate-0.10.1          |         r3.4.1_0          50 KB  conda-forge
    mkl_fft-1.0.2              |           py36_0         505 KB  conda-forge
    zlib-1.2.11                |       h470a237_3          93 KB  conda-forge
    r-munsell-0.5.0            |           r341_0         219 KB  conda-forge
    krb5-1.14.6                |                0         4.0 MB  conda-forge
    xorg-libx11-1.6.5          |                0         1.6 MB  conda-forge
    r-knitr-1.20               |         r3.4.1_0         812 KB  conda-forge
    intel-openmp-2018.0.3      |                0         705 KB
    r-formula-1.2_1            |         r3.4.1_0         163 KB  conda-forge
    mkl-2018.0.3               |                1       198.7 MB
    bioconductor-graph-1.56.0  |         r3.4.1_0         1.3 MB  bioconda
    r-igraph-1.2.1             |         r3.4.1_0         2.9 MB  conda-forge
    libpng-1.6.34              |       ha92aebf_1         304 KB  conda-forge
    libxcb-1.13                |       h470a237_0         539 KB  conda-forge
    setuptools-39.2.0          |           py36_0         550 KB  conda-forge
    r-stringr-1.3.0            |         r3.4.1_0         163 KB  conda-forge
    r-base64enc-0.1_3          |         r3.4.1_0          28 KB  conda-forge
    r-pkgmaker-0.22            |         r3.4.1_0         611 KB  conda-forge
    r-cluster-2.0.6            |         r3.4.1_0         511 KB  conda-forge
    harfbuzz-1.7.6             |                0         5.6 MB  conda-forge
    gmp-6.1.2                  |       hfc679d8_0         676 KB  conda-forge
    icu-58.2                   |       hfc679d8_0        22.8 MB  conda-forge
    r-markdown-0.8             |         r3.4.1_1         111 KB  conda-forge
    ------------------------------------------------------------
                                           Total:       346.4 MB
```

**Comment by bgruening** [comment]
What does `conda create -n bioconductor-camera-build2 bioconductor-camera bioconductor-xcms=3.0.0` give you?

**Comment by lecorguille** [comment]
It's works
I can deal with that in Galaxy
Thanks

**Comment by bgruening** [comment]
Cool, sorry it took so long.

**Pull request merged**
