### PR TITLE
Update mosdepth to 0.2.6.

### PR DESCRIPTION
**Pull request by cbrueffer**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by dpryan79** [comment]
Xref: https://github.com/bioconda/bioconda-recipes/pull/15495

**Comment by pmenzel** [comment]
The error message from bioconda-test is `/bin/sh: gcc: command not found`.

I also noticed that the [new blast 2.9.0 recipe fails](https://github.com/bioconda/bioconda-recipes/pull/14620/checks?check_run_id=110867192) with `no acceptable C compiler found in $PATH`.

Maybe it's the same underlying issue..

**Comment by dpryan79** [comment]
The only issue is the makefile or similar not respecting the `$CC` variable. We've patched around this in most of our recipes by now, but not all of them. For mosdepth, there are other issues (#15495 ).

**Comment by pmenzel** [comment]
Ok, do you think you could have a look at the blastn 2.9.0 issue, it would be very nice to have it in bioconda, since it has some nice new features and a new database format compared with 2.7

**Comment by dpryan79** [comment]
Sure, is there a PR I can look at?

**Comment by pmenzel** [comment]
Great, it is this one: https://github.com/bioconda/bioconda-recipes/pull/14620

**Comment by dpryan79** [comment]
I've updated this now.

**Pull request closed without merging**
