### PR TITLE
Updating DIAMOND to 0.9.31

### PR DESCRIPTION
**Pull request by lucventurini**
Updating DIAMOND ((https://github.com/bbuchfink/diamond)[https://github.com/bbuchfink/diamond]) to the latest version, 0.9.31.

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by raivivek** [comment]
@lucventurini The build is failing on macOS. Should be good to go after a quick fix, unless DIAMOND is not supported on macOS.

**Comment by lucventurini** [comment]
@raivivek

I'm not an expert on how to solve the issue on macosx build. Would you please be able to help with that?

**Comment by oschwengers** [comment]
Hi @lucventurini @raivivek I also tried to update Diamond but closed my PR when I saw this one. Unfortunately, also do not have any MacOS experience. I asked in the bioconda gitter channel if someone could maybe have a look at this.

**Comment by sjanssen2** [comment]
To me, it looks like an upstream issue: https://github.com/bbuchfink/diamond/issues/343
Let's hope for a new release of the current master - this should fix our problem here.

**Comment by lucventurini** [comment]
@sjanssen2 

Many thanks for having a look into this!

**Comment by oschwengers** [comment]
@lucventurini There is a new Diamond release [v0.9.32](https://github.com/bbuchfink/diamond/releases/tag/v0.9.32) which should fix the MacOS related bug. I guess we should all switch to the new release so this PR could be closed?
Best regards and thanks to everyone involved.

**Comment by lucventurini** [comment]
@oschwengers yes definitely!

**Pull request closed without merging**
