### PR TITLE
add plink_1.9beta5 recipe

### PR DESCRIPTION
**Pull request by ericaenjoy3**
Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it. Note that if you are not already a member of the bioconda project (meaning that you can't add this label), please ping `@bioconda/core` so that your PR can be reviewed and merged (please note if you'd like to be added to the bioconda project). Please see https://github.com/bioconda/bioconda-recipes/issues/15332 for more details.

* [X ] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [ X] This PR adds a new recipe.
* [X ] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by ericaenjoy3** [comment]
Thanks for your review and comments! The change has been made as suggested. Would you please be so kind to review the change? Many thanks.

**Comment by dpryan79** [comment]
Please overwrite the files in `recipes/plink` with yours. The previous recipe should no longer exist after your PR is merged. Please also disable circleci on your fork.

**Comment by dpryan79** [comment]
Once circleci has been disabled on your fork this can be tested.

**Comment by ericaenjoy3** [comment]
> Once circleci has been disabled on your fork this can be tested.

Thanks for your suggestions! Circle CI has been disabled on my fork.

**Comment by ericaenjoy3** [comment]
> > Once circleci has been disabled on your fork this can be tested.
> 
> Thanks for your suggestions! Circle CI has been disabled on my fork.

A check failed through Circleci. Do you happen to know how to fix this? Many thanks!

**Comment by dpryan79** [comment]
It's a compilation error in plink, I'd have to look into the Makefile to see how to get it to pass `-lpthread` to the compiler.

**Comment by dpryan79** [comment]
@bioconda-bot update

**Pull request merged**
