### PR TITLE
Update pbgcpp to 0.3.0

### PR DESCRIPTION
**Pull request by epruesse**
Update [`pbgcpp`](https://bioconda.github.io/recipes/pbgcpp/README.html): **0.0.1** &rarr; **0.3.0**

[install with bioconda](http://bioconda.github.io/recipes/pbgcpp/README.html) [Conda](https://anaconda.org/bioconda/pbgcpp/files)

Info | Link
-----|-----
Recipe | [`recipes/pbgcpp`](https://github.com//bioconda/bioconda-recipes/tree/bump/pbgcpp/recipes/pbgcpp) (click to view/edit other files)
Releases |[https://github.com/PacificBiosciences/pypeFLOW/releases](https://github.com/PacificBiosciences/pypeFLOW/releases)
Recipe Maintainer(s) | @armintoepfer, @pb-dseifert, @pb-cdunn, @mhsieh
Author | `@PacificBiosciences`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/updating.html)).

### CODE REVIEW

**Comment by pb-cdunn** [comment]
`0.2.7` is the version number for pb-falcon, not for gcpp. And the url is for a prebuilt binary.

@epruesse, Is there a specific problem you're tying to solve.

**Comment by epruesse** [comment]
@pb-cdunn This PR was generated by `bioconda-utils autobump`. 

It is getting confused by the source for this package. To be honest, I am, too.

The version numbers should be from the github tags since the package is on github, and since the most recent tag is 0.2.7, `autobump` is trying to update. Since it expects an archive from which `pbgcpp` should be build, it is discarding the raw binary and picking the best archive it can get.

Where is pbgcpp hosted? Can't we build that directly? The license doesn't seem to be a problem. I'm not sure I understand this setup....

**Comment by pb-cdunn** [comment]
I don't think autobump will work with this package. We have constraints from my management at the moment.

**Comment by epruesse** [comment]
You can disable it by adding

```yaml
extra:
  autobump:
    enable: False
```

to the recipe in question.

**Comment by epruesse** [comment]
You can disable it by adding

```yaml
extra:
  autobump:
    enable: False
```

to the recipe in question.

**Comment by pb-cdunn** [comment]
Thanks. We will add that after we get our other packages upgrade to py37, which is challenging.

**Pull request closed without merging**
