### PR TITLE
Add pyhmmsearch

### PR DESCRIPTION
**Pull request by apcamargo**
This PR adds [`pyhmmsearch`](https://github.com/jolespin/pyhmmsearch), by @jolespin.

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

### General instructions

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

### Instructions for avoiding API, ABI, and CLI breakage issues
Conda is able to record and lock (a.k.a. pin) dependency versions used at build time of other recipes.
This way, one can avoid that expectations of a downstream recipe with regards to API, ABI, or CLI are violated by later changes in the recipe.
If not already present in the meta.yaml, make sure to specify `run_exports` (see [here](https://bioconda.github.io/contributor/linting.html#missing-run-exports) for the rationale and comprehensive explanation).
Add a `run_exports` section like this:

```yaml
build:
  run_exports:
    - ...

```

with `...` being one of:

| Case                             | run_exports statement                                               |
| -------------------------------- | ------------------------------------------------------------------- |
| semantic versioning              | `{{ pin_subpackage("myrecipe", max_pin="x") }}`     |
| semantic versioning (0.x.x)      | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}`   |
| known breakage in minor versions | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| known breakage in patch versions | `{{ pin_subpackage("myrecipe", max_pin="x.x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| calendar versioning              | `{{ pin_subpackage("myrecipe", max_pin=None) }}`    |

while replacing `"myrecipe"` with either `name` if a `name|lower` variable is defined in your recipe or with the lowercase name of the package in quotes.

### Bot commands for PR management

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

Note that the <code>@BiocondaBot please merge</code> command is now depreciated. Please just squash and merge instead.

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by apcamargo** [comment]
@jolespin do you think you can use entrypoints to expose `pyhmmsearch` as an executable (see example [here](https://github.com/apcamargo/RNAsamba/blob/052c0835c51e06aff4ac0b7a158c6368f0245a60/setup.py#L46))? This is obviously a suggestion, but I wanted to put `pyhmmsearch`, `pykofamsearch`, `kegg_pathway_profiler` in BioConda and the way the executables are being exposed is not playing nicely.

**Comment by jolespin** [comment]
Yea definitely! I'll look into these tomorrow morning and try to implement them by the end of the week. Thanks for getting the ball rolling on the bioconda push.

**Comment by apcamargo** [comment]
Thanks!!

**Comment by jolespin** [comment]
@apcamargo I had never heard of entry points.  Thanks for introducing me to this best practice.  I just updated PyHMMSearch to v2024.10.18 which uses this.  Can you try to build again? I'll update pykofamsearch and kegg_pathway_profiler next.

**Comment by jolespin** [comment]
@apcamargo do you have any suggestions on how I can get this to work? The structure is a little different.  I tried bringing the executables into the python package directory.  Here's my error: 

```
(test_env) Joshs-MBP:kegg_pathway_profiler jolespin$ profile-pathway-coverage -h
Traceback (most recent call last):
  File "/Users/jolespin/miniconda3/envs/test_env/bin/profile-pathway-coverage", line 5, in <module>
    from kegg_pathway_profiler.cli.profile_pathway_coverage import main
  File "/Users/jolespin/miniconda3/envs/test_env/lib/python3.10/site-packages/kegg_pathway_profiler/cli/__init__.py", line 2, in <module>
    from .build_pathway_database import *
ModuleNotFoundError: No module named 'kegg_pathway_profiler.cli.build_pathway_database'
```

[Archive.zip](https://github.com/user-attachments/files/17441131/Archive.zip)

**Comment by apcamargo** [comment]
I think that's because the `__init__.py` in the base directory is not importing `cli`.

**Pull request closed without merging**
