### PR TITLE
QUAST Bump to Python3.7

### PR DESCRIPTION
**Pull request by apeltzer**
Trying to bump to Python3.7 to get my unicycler bump to be installable with Quast in the same environment. I got warned by @dpryan79 but will nevertheless try my best ;-) 

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by apeltzer** [comment]
Had this error:
```
conda.exceptions.UnsatisfiableError: The following specifications were found to be in conflict:
  - circos
  - perl=5.26.0
```

So I'm bumping the circos build first of all: https://github.com/bioconda/bioconda-recipes/pull/15701

**Comment by apeltzer** [comment]
```
Compiling Minimap2 (details are in $SRC_DIR/quast_libs/minimap2/make.log and make.err)
20:44:19 BIOCONDA INFO (OUT) make -C quast_libs/minimap2 >> quast_libs/minimap2/make.log 2>> quast_libs/minimap2/make.err
20:44:29 BIOCONDA INFO (OUT) The tool returned non-zero. See quast_libs/minimap2/make.err for stderr.
20:44:29 BIOCONDA INFO (OUT) WARNING: Failed to compile Minimap2 ($SRC_DIR/quast_libs/minimap2)! Try to compile it manually. You can restart Quast with the --debug flag to see the compilation command.
20:44:29 BIOCONDA INFO (OUT) 
20:44:29 BIOCONDA INFO (OUT) ERROR! Compilation of contig aligner software was unsuccessful! QUAST functionality will be limited.
20:44:29 BIOCONDA INFO (OUT) * Compiling Glimmer *
20:44:29 BIOCONDA INFO (OUT) * Compiling read analysis tools *
20:44:29 BIOCONDA INFO (OUT) Compiling BWA (details are in $SRC_DIR/quast_libs/bwa/make.log and make.err)
20:44:29 BIOCONDA INFO (OUT) make -C quast_libs/bwa >> quast_libs/bwa/make.log 2>> quast_libs/bwa/make.err
20:44:29 BIOCONDA INFO (OUT) The tool returned non-zero. See quast_libs/bwa/make.err for stderr.
20:44:29 BIOCONDA INFO (OUT) WARNING: Failed to compile BWA ($SRC_DIR/quast_libs/bwa)! Try to compile it manually. You can restart Quast with the --debug flag to see the compilation command.
20:44:29 BIOCONDA INFO (OUT) 
```

Amazing.

**Comment by dpryan79** [comment]
OMFG, it vendors %!$#ing EVERYTHING! That package needs to be killed with fire.

**Comment by apeltzer** [comment]
Honestly, if there is an alternative that can be used I'd be happy to use it.

**Comment by mbargull** [comment]
fixed in gh-23218

**Comment by apeltzer** [comment]
Thanks - still ugly that vendoring but seems to work now

**Comment by mbargull** [comment]
Yep, we still need to find a lackey who's willing to fix that :D.

**Comment by mbargull** [comment]
If you could see just how much I'm grinning right now! X'D

**Pull request closed without merging**
