### PR TITLE
remuRNA

### PR DESCRIPTION
**Pull request by zwanli**
* [x] I have read the guidelines above.
* [x] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by zwanli** [comment]
Skipped the build for osx. Because I was getting the [error](https://travis-ci.org/zwanli/bioconda-recipes/jobs/181964972#L296) 
> clang: error: unsupported option '-fopenmp'

**Comment by bgruening** [comment]
You need to rebase this PR against master.

**Comment by bgruening** [comment]
Any idea why the test was passing before the last commit? Is the ENV really needed?

**Comment by zwanli** [comment]
I guess it was only building and testing remuRNA. 
The ENV var was for RNAsnp, which has been merged yesterday.

**Pull request merged**
