### PR TITLE
Update dbcan to 4.1.0

### PR DESCRIPTION
**Pull request by linnabrown**
Update dbcan to 4.1.0

### CODE REVIEW

**Comment by mencian** [comment]
@BiocondaBot please fetch artifacts

**Comment by mencian** [comment]
@linnabrown I have made a few edits to the recipe and that seems to have done the trick. Could you please download the package locally to see if everything runs as expected?

**Review by linnabrown — COMMENTED** [review]
@mencian Could you help me to change the sha256 into this:

cb0907eb10eb916bcf676c58f54e67a67dd4ed559152e5547bb44d071f063b8f

I just updated the package. Thanks!

**Comment by HaidYi** [comment]
@BiocondaBot please add badge.

**Comment by linnabrown** [comment]
@BiocondaBot please add label

**Review by mencian — APPROVED** [review]

**Pull request merged**
