### PR TITLE
Canu 1.6

### PR DESCRIPTION
**Pull request by druvus**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by druvus** [comment]
@bgruening Could you please take a look at the second canu test? It is failing with the new version due to the mockup read gets filtered away.

**Comment by zachcp** [comment]
any idea of how to push this one over the line?  Canu 1.6 would be great.

**Comment by bgruening** [comment]
Sorry missed this one. Please remove the test if it is not needed anymore. I think I added it because otherwise we hit a lazy loading issue.

**Comment by lecorguille** [comment]
Sorry @druvus for that but it seems that [mine](https://github.com/bioconda/bioconda-recipes/pull/6216) won :P  
The good news is that canu-1.6 is now available.

**Comment by druvus** [comment]
thanks @lecorguille and @bgruening for fixing canu!

**Comment by zachcp** [comment]
thank you all!

**Pull request closed without merging**
