### PR TITLE
Update tiddit to 2.8.1

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`tiddit`](https://bioconda.github.io/recipes/tiddit/README.html): **2.8.0** &rarr; **2.8.1**

[install with bioconda](http://bioconda.github.io/recipes/tiddit/README.html) [Conda](https://anaconda.org/bioconda/tiddit/files)

Info | Link
-----|-----
Recipe | [`recipes/tiddit`](https://github.com//bioconda/bioconda-recipes/tree/bump/tiddit/recipes/tiddit) (click to view/edit other files)
Releases |[https://github.com/SciLifeLab/TIDDIT/tags](https://github.com/SciLifeLab/TIDDIT/tags)
Author | `@SciLifeLab`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by dpryan79** [comment]
This appears to be packaging the entire build output, including intermediate files!

**Comment by MaxUlysse** [comment]
@dpryan79 I tried tiddit 2.8.1, and it's not working anymore, I think your clean up might have been to efficient.

I can run `tiddit -v`, but an actual tiddit command is failing with:
```
error,  could not find the TIDDIT executable file, try rerun the INSTALL.sh script
```

**Comment by dpryan79** [comment]
Oh no! Can you give me a (relatively) simple command so I can reproduce this (I'm not familiar with TIDDIT)? Maybe we can update the test in the recipe.

**Comment by MaxUlysse** [comment]
I'm using the SV module from TIDDIT, but I do think the COV module would need a smaller bam file.
So this command should be working:
```
tiddit --cov --bam [BAMFILE]
```

**Comment by dpryan79** [comment]
So I guess any BAM file should work then. I'll have a look.

**Comment by dpryan79** [comment]
I'll work on this here: https://github.com/bioconda/bioconda-recipes/pull/18971

**Pull request merged**
