### PR TITLE
Update ultra_bioinformatics to 0.0.4.2

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`ultra_bioinformatics`](https://bioconda.github.io/recipes/ultra_bioinformatics/README.html): **0.0.4.1** &rarr; **0.0.4.2**

[install with bioconda](http://bioconda.github.io/recipes/ultra_bioinformatics/README.html) [Conda](https://anaconda.org/bioconda/ultra_bioinformatics/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/ultra_bioinformatics`](https://github.com//bioconda/bioconda-recipes/tree/bump/ultra_bioinformatics/recipes/ultra_bioinformatics) (click to view/edit other files)
Summary | Splice aligner of long transcriptomic reads to genome.
Home | [https://github.com/ksahlin/uLTRA](https://github.com/ksahlin/uLTRA)
Releases |[https://pypi.org/pypi/ultra_bioinformatics/json](https://pypi.org/pypi/ultra_bioinformatics/json)
Recipe Maintainer(s) | @sguizard

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by mfansler** [comment]
There is a `ClobberWarning` in the checks between `edlib` and `python-edlib`. It appears these were historically both **bioconda** packages (C++ and Python, resp.), but Conda Forge recently added the Python package `edlib` as [`edlib`](https://github.com/conda-forge/edlib-feedstock). This leads to the following solution:

```bash
edlib                      1.3.9  py310hbf28c38_2      conda-forge/linux-64      77kB
python-edlib               1.3.9  py310h30d9df9_1      bioconda/linux-64         78kB
```

which are really the same package but from two channels. 😬

**Comment by mfansler** [comment]
Issue: https://github.com/bioconda/bioconda-recipes/issues/37646

**Comment by sguizard** [comment]
Thanks for reviewing, I'll take a look asap.

**Comment by mfansler** [comment]
@sguizard is `bioconda::edlib` (the C/C++ library) even a legitimate dependency this recipe? If not, removing the `edlib` would remove the ambiguity, and just let `bioconda::python-edlib` be the Python package provider (as opposed to `conda-forge::edlib`).

**Comment by sguizard** [comment]
Removing `edlib` from recipe is OK. 
Should I create a PR to update the recipe or it could be done directly here?

**Comment by dpryan79** [comment]
@BiocondaBot please fetch artifacts

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@BiocondaBot please merge

**Pull request merged**
