### PR TITLE
discosnp

### PR DESCRIPTION
**Pull request by cmonjeau**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by bgruening** [comment]
Nice! Thanks a lot!

**Comment by abretaud** [comment]
Strange, we can't find the package on anaconda.org, but it is on [biocontainers](https://biocontainers.pro/registry/#/showImages?domain=quay&repository=discosnp&starred=false&modified=28%2F09%2F2017) and the log says it [was uploaded](https://travis-ci.org/bioconda/bioconda-recipes/jobs/280624310#L787)
Any idea?

**Comment by bgruening** [comment]
> cp: ext/gatb-core/bin/dbgh5: No such file or directory

master branch failed.

https://travis-ci.org/bioconda/bioconda-recipes/jobs/281210688

**Comment by abretaud** [comment]
Hum, no, this error is for another PR (#6182) where @cmonjeau is trying to fix a bug in the discosnp recipe
If #6182 gets uploaded there's no problem because the original recipe here was broken. It's just that's it's strange that it didn't get uploaded without any error

**Comment by cmonjeau** [comment]
I fix this error in a new PR ([#6183](https://github.com/bioconda/bioconda-recipes/pull/6185)).

Thank you @bgruening (and @abretaud but not much).

**Pull request merged**
