### PR TITLE
Update DeepVariant v1.0

### PR DESCRIPTION
**Pull request by nikostr**
The DeepVariant recipe is broken, as explained in #27665 and https://github.com/snakemake/snakemake-wrappers/pull/130. This pull request aims to fix that. This pull request also adds wrapper options for gVCF output, as necessary for multi-sample variant calling: https://github.com/google/deepvariant/blob/r1.1/docs/trio-merge-case-study.md. A separate PR for GPU support is hopefully also coming.

A note: when building this locally, the prefix placeholder `/opt/anaconda1anaconda2anaconda3` does not get replaced outside of the hashbangs. I don't understand why this is, as I don't think that updated parts of the recipe should affect this. I've attempted to check this using CircleCI locally, but I'm not able to get CircleCI to run using the proposed `snap` install.

### CODE REVIEW

**Comment by nikostr** [comment]
I'm getting `build_number_needs_bump` error, but I've updated the build number, and I can't see that a newer PR has replaced it. Could someone explain what the problem is?

**Comment by druvus** [comment]
@BiocondaBot please update

**Comment by druvus** [comment]
@BiocondaBot please update

**Comment by druvus** [comment]
@nikostr the reason you saw the build number issue is because a migration to a newer gcc version were ongoing in the bulk-branch. It is now merged back to master and I bumped the build number.

**Comment by nikostr** [comment]
@druvus, excellent! Do I need to do anything else for this to get merged?

**Comment by druvus** [comment]
@BiocondaBot please fetch artifacts

**Review by druvus — APPROVED** [review]

**Comment by druvus** [comment]
@BiocondaBot please merge

**Pull request merged**
