### PR TITLE
checkm-genome - fix broken pinning by older pysam version

### PR DESCRIPTION
**Pull request by rpetit3**
Installed checkm-genome to a new environment and got this erre:
```
(checkm) rpetit@staphopia:~$ checkm data setRoot /local/home/rpetit/miniconda3/envs/checkm/checkm_data
Traceback (most recent call last):
  File "/local/home/rpetit/miniconda3/envs/checkm/bin/checkm", line 36, in <module>
    from checkm import main
  File "/local/home/rpetit/miniconda3/envs/checkm/lib/python3.6/site-packages/checkm/main.py", line 28, in <module>
    from checkm.resultsParser import ResultsParser
  File "/local/home/rpetit/miniconda3/envs/checkm/lib/python3.6/site-packages/checkm/resultsParser.py", line 34, in <module>
    from checkm.coverage import Coverage
  File "/local/home/rpetit/miniconda3/envs/checkm/lib/python3.6/site-packages/checkm/coverage.py", line 30, in <module>
    import pysam
  File "/local/home/rpetit/miniconda3/envs/checkm/lib/python3.6/site-packages/pysam/__init__.py", line 5, in <module>
    from pysam.libchtslib import *
ImportError: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
```

This error is due to a broken pinning (see https://github.com/bioconda/bioconda-recipes/issues/17212), in checkm's case a more up to date version of pysam is needed.

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by rpetit3** [comment]
@BiocondaBot please add label

**Comment by rpetit3** [comment]
@BiocondaBot please fetch artifacts

**Comment by rpetit3** [comment]
Testing artifacts:

```
conda create -n test-checkm -c https://134462-42372094-gh.circle-artifacts.com/0/tmp/artifacts/packages -c conda-forge -c bioconda checkm-genome
conda activate test-checkm
checkm data setRoot /local/home/rpetit/miniconda3/envs/test-checkm/checkm_data
[2020-12-17 17:24:56] INFO: CheckM v1.1.3
[2020-12-17 17:24:56] INFO: checkm data setRoot /local/home/rpetit/miniconda3/envs/test-checkm/checkm_data
[2020-12-17 17:24:56] INFO: [CheckM - data] Check for database updates. [setRoot]

Path [/local/home/rpetit/miniconda3/envs/test-checkm/checkm_data] exists and you have permission to write to this folder.
(re) creating manifest file (please be patient).

Path [/local/home/rpetit/miniconda3/envs/test-checkm/checkm_data] exists and you have permission to write to this folder.
(re) creating manifest file (please be patient).
```

Seems ok now

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@bioconda-bot please merge

Gotta love it when the conda solver prefers old dependency versions :(

**Pull request merged**
