### PR TITLE
Clairvoyante minor update

### PR DESCRIPTION
**Pull request by aquaskyline**
:information_source:
If this is your first pull request to Bioconda please ping `@bioconda/core` so it can be reviewed and to request being added as a member of the Bioconda team. Members of the Bioconda team are able to merge their own pull requests once tests and linting have passed.

----------------

- [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
- [ ] This PR adds a new recipe.
- [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
- [x] This PR updates an existing recipe.
- [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by aquaskyline** [comment]
@corburn please check and merge. Thank you.

**Comment by corburn** [comment]
The program version is incremented when the program is changed.
The build number is incremented when the conda recipe is changed, but not program.

If the hash changed, that means the program changed. You are welcome to ask someone else to merge this, but I think you're supposed to release a new version instead of modifying an existing version.

**Comment by aquaskyline** [comment]
@corburn that makes sense. I've updated the version number to 1.02 and reset the build to 0.

**Comment by aquaskyline** [comment]
@corburn Please help to check the Linting. It has been running for 3 days.

**Comment by corburn** [comment]
@bioconda/build-system any tips for debugging the linter?

**Comment by epruesse** [comment]
@biocondabot recheck

**Comment by epruesse** [comment]
Basically- if the bot didn’t respond back, just issue the recheck command. The checks it does are optional anyway.

**Pull request merged**
