### PR TITLE
Update unifrac-binaries to 1.1.3

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`unifrac-binaries`](https://bioconda.github.io/recipes/unifrac-binaries/README.html): **1.1.2** &rarr; **1.1.3**

[install with bioconda](http://bioconda.github.io/recipes/unifrac-binaries/README.html) [Conda](https://anaconda.org/bioconda/unifrac-binaries/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/unifrac-binaries`](https://github.com//bioconda/bioconda-recipes/tree/bump/unifrac_binaries/recipes/unifrac-binaries) (click to view/edit other files)
Summary | Fast phylogenetic diversity calculations
Home | [https://github.com/biocore/unifrac-binaries](https://github.com/biocore/unifrac-binaries)
Releases |[https://github.com/biocore/unifrac-binaries/tags](https://github.com/biocore/unifrac-binaries/tags)
Recipe Maintainer(s) | @sfiligoi, @wasade
Author | `@biocore`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by sfiligoi** [comment]
Confirm the new version.

**Review by sfiligoi — APPROVED** [review]
Looks good.

**Comment by sfiligoi** [comment]
@BiocondaBot please fetch artifacts

**Comment by sfiligoi** [comment]
Looks good locally.

**Comment by sfiligoi** [comment]
@matthdsm @dpryan79 Could one of you please review this? It has been more than 2 days since it was opened.

**Review by matthdsm — APPROVED** [review]

**Comment by matthdsm** [comment]
@BiocondaBot please merge

**Pull request merged**
