### PR TITLE
Update sccaller to 1.21

### PR DESCRIPTION
**Pull request by epruesse**
Update `sccaller`: **1.2** &rarr; **1.21**

***

[Package Info](https://bioconda.github.io/recipes/sccaller/README.html) | [Recipe Folder](https://github.com/bioconda/bioconda-recipes/tree/master/recipes/sccaller) | [Upstream Home](https://github.com/biosinodx/SCcaller) | [Upstream Releases](https://github.com/biosinodx/SCcaller/tags)  

***

This pull request was automatically generated by [bioconda-utils](https://github.com/bioconda/bioconda-utils).

### CODE REVIEW

**Comment by druvus** [comment]
Fails because upstream file is still called sccaller_v1.2.py

**Comment by epruesse** [comment]
Yes. I don’t know about this one. I’m afraid upstream meant “1.2.1” not “1.21”.

**Comment by epruesse** [comment]
@dlaehnemann @biosinodx

The way the build.sh assumes scaller_$VERSION.py and reasoning_$VERSION.py is broken. I think this may need some TLC to be packaged.

**Comment by epruesse** [comment]
@dlaehnemann That's completely up to you. I've got way to many recipes to check into after running the updater to invest time into the more complex cases. I'd appreciate greatly if you could take over from here.

**Comment by biosinodx** [comment]
Hi David,

 

Shall I simply rename the current version to 1.2.1 to avoid the confusion?

 

Thank you,

Xiao

**Comment by dlaehnemann** [comment]
Hey @epruesse ,

after the conversation with @biosinodx over at the source repo, I'll [go with the current version number](https://github.com/biosinodx/SCcaller/issues/5#issuecomment-436659293) and patching in `build.sh`. Just commited that to your fork's branch that you used for this PR -- but it doesn't seem to re-trigger circleci and I haven't found a way of doing it. Could you?

cheers,
david

**Comment by epruesse** [comment]
@dlaehnemann Just close and re-open the PR...

**Comment by epruesse** [comment]
I had to rebase this to get the bioconda-utils mechanics to accept that we aren't unblacklisting a ton of stuff...

**Comment by dlaehnemann** [comment]
Thanks @epruesse !

**Pull request merged**
