### PR TITLE
Update post-link.sh script for RepeatMasker

### PR DESCRIPTION
**Pull request by dirkjanvw**
On macOS, the current RepeatMasker installation is non-functional because the Dfam database is not correctly downloaded. This is because `zcat` works differently on linux compared to osx. Therefore, I propose in this PR to use `gunzip -c` instead of `zcat`.

### CODE REVIEW

**Comment by dirkjanvw** [comment]
@abretaud @bgruening since you were involved in the addition of the `post-link.sh` script to this recipe earlier (#40484), could you please let me know what you think of the change I propose here before I add the label for review and merge?

**Comment by abretaud** [comment]
Ah, no objection if it works the same, but you need to bump the build number too

**Comment by dirkjanvw** [comment]
Ah yes, indeed. I also added the run_exports as it is required now too.

I'll still test this recipe on both macOS and Linux to make sure it works!

**Comment by dirkjanvw** [comment]
Hmm it seems the pipeline can no longer extract the source tarball for repeatmasker (`wget https://www.repeatmasker.org/RepeatMasker/RepeatMasker-4.1.5.tar.gz`), whereas it could previously. Do you know a way around this?

**Comment by dirkjanvw** [comment]
@bioconda/core could you please help out here? how can I let the pipeline succeed (no space left on device error)? it did work out for the previous build of the same version (so same unpacking the same tarball)

**Comment by dirkjanvw** [comment]
@BiocondaBot please add label

**Comment by mencian** [comment]
LGTM! Thanks, @dirkjanvw, for looking into this!

**Review by mencian — APPROVED** [review]

**Comment by abretaud** [comment]
@dirkjanvw what's the reason to no longer include the db in the container image in https://github.com/bioconda/bioconda-recipes/pull/43288/commits/013fa23b460a66b98f257061462c96eb4f4f52ca ?
It breaks a galaxy tool that expect the db to be there

**Comment by mvdbeek** [comment]
Can we delete the docker and singularity images in the meantime ?

**Comment by dirkjanvw** [comment]
Ah sorry, I didn't know. The reason that I removed the database as well (next to fixing the post link script) is that the pipeline ran out of space when building the container (see messages above): someone on Gitter suggested to follow the example of lotus to solve this issue but if you know of another way of downloading the full database without breaking the pipeline I see no issue with putting it back.

**Comment by mvdbeek** [comment]
If by pipeline you mean the CI, yes, use of zcat as before should prevent running out of space.

**Comment by dirkjanvw** [comment]
Hmm but that doesn't work for OSX as `zcat` works differently there.

**Comment by bgruening** [comment]
zcat is in the gzip package. Maybe it helps to put this as host dependency for osx.

```
host:
  - gzip # [osx]

**Comment by abretaud** [comment]
Opened https://github.com/bioconda/bioconda-recipes/pull/43994 to fix this

**Pull request merged**
