### PR TITLE
Add bioconductor-zinbwave

### PR DESCRIPTION
**Pull request by apcamargo**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

This PR adds recipes to bioconductor-zinbwave and it's dependency, r-softimpute.

### CODE REVIEW

**Comment by apcamargo** [comment]
I'm having some problems during the build of r-softimpute:

```
20:37:21 BIOCONDA INFO BUILD START recipes/r-softimpute
....20:41:38 BIOCONDA ERROR COMMAND FAILED: /opt/conda/bin/conda build --no-anaconda-upload --channel bioconda --channel conda-forge --channel defaults -e /opt/conda/conda_build_config.yaml -m /opt/conda/lib/python3.6/site-packages/bioconda_utils/bioconda_utils-conda_build_config.yaml recipes/r-softimpute/meta.yaml
20:41:38 BIOCONDA ERROR STDOUT+STDERR:
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Adding in variants from /opt/conda/conda_build_config.yaml
INFO:conda_build.variants:Adding in variants from /opt/conda/conda_build_config.yaml
Adding in variants from /opt/conda/lib/python3.6/site-packages/bioconda_utils/bioconda_utils-conda_build_config.yaml
INFO:conda_build.variants:Adding in variants from /opt/conda/lib/python3.6/site-packages/bioconda_utils/bioconda_utils-conda_build_config.yaml
Attempting to finalize metadata for r-softimpute
INFO:conda_build.metadata:Attempting to finalize metadata for r-softimpute
Solving environment: ...working... done
Solving environment: ...working... done
Solving environment: ...working... done
BUILD START: ['r-softimpute-1.4-r341h364d78e_0.tar.bz2']
Solving environment: ...working... done
```
```
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Source cache directory is: /opt/conda/conda-bld/src_cache
Traceback (most recent call last):
  File "/opt/conda/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 420, in main
    execute(sys.argv[1:])
  File "/opt/conda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 411, in execute
    verify=args.verify)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/api.py", line 200, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/build.py", line 2177, in build_tree
    notest=notest,
  File "/opt/conda/lib/python3.6/site-packages/conda_build/build.py", line 1350, in build
    try_download(m, no_download_source=False, raise_error=True)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/render.py", line 549, in try_download
    source.provide(metadata)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/source.py", line 623, in provide
    timeout=metadata.config.timeout, locking=metadata.config.locking)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/source.py", line 133, in unpack
    src_path, unhashed_fn = download_to_cache(cache_folder, recipe_path, source_dict)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/source.py", line 45, in download_to_cache
    unhashed_fn = fn = source_dict['fn'] if 'fn' in source_dict else basename(source_dict['url'])
  File "/opt/conda/lib/python3.6/posixpath.py", line 146, in basename
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not list
```
Does anyone know what I'm doing wrong here? I couln't find any solution.

**Comment by rvalieris** [comment]
you need to merge master into your branch, metaprob was added to the blacklist a while ago.

**Comment by apcamargo** [comment]
Thanks @rvalieris . metaprob is not being built anymore, but I'm still getting the error with r-zinbwave. Can you help me with this?

**Comment by rvalieris** [comment]
thats a conda-build issue, it was already solved upstream but the version used by bioconda is [pinned here](https://github.com/bioconda/bioconda-utils/blob/master/bioconda_utils/bioconda_utils-requirements.txt#L5) and needs to be updated.

**Comment by apcamargo** [comment]
Ok. I'll wait for the update then.

Thanks!

**Comment by rvalieris** [comment]
try triggering a new build now.

**Comment by apcamargo** [comment]
@rvalieris I'm getting the same error.

**Comment by rvalieris** [comment]
`
unable to load shared object '/opt/conda/conda-bld/bioconductor-zinbwave_1533908070019/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/R/library/gsl/libs/gsl.so':  libgsl.so.23: cannot open shared object file: No such file or directory
`

no thats a different error.

try adding a gsl >= 3.4 requirement.

**Comment by apcamargo** [comment]
The error in macOS seems to be with `copula`, but `r-copula` is already a requirement. I'll try to figure out what is happening.

**Comment by rvalieris** [comment]
yea, looks like r-copula builds are failing for osx. for now I guess you can skip osx builds here.

**Comment by apcamargo** [comment]
That's unfortunate. Any idea why this is happening?

In any case, I skipped the macOS build for now and the PR has passed all the tests.

**Comment by rvalieris** [comment]
I am not really sure, here is the xref: https://github.com/conda-forge/r-copula-feedstock/pull/3

**Pull request merged**
