### PR TITLE
Update R MutationalPatterns

### PR DESCRIPTION
**Pull request by vladsaveliev**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.

Updating [MutationalPatterns](http://bioconductor.org/packages/release/bioc/html/MutationalPatterns.html) R package.

`r-mutationalpatterns` recipe points to a [GitHub release](https://github.com/UMCUGenetics/MutationalPatterns/releases), however it looks like the authors are releasing new versions only in [Bioconductor](http://bioconductor.org/packages/release/bioc/html/MutationalPatterns.html): the latest GitHub version is 1.1.0, the latest bioconductor one is 1.4.1. So it makes sense to re-point recipe to bioconductor.

However it seems that bioconductor packages in bioconda are named using a `bioconductor-` prefix instead of `r-`, so I'm submitting here a new package `bioconductor-mutationalpatterns`. But I'm also updating and keeping `r-mutationalpatterns` for back-compatibility. Let me know if that's a bad decision and we should stick with only one recipe, either `r-` or `bioconductor-`.

### CODE REVIEW

**Comment by bgruening** [comment]
@vladsaveliev I think it would be better to remove the r-* package altogether.

**Comment by vladsaveliev** [comment]
@bgruening, thanks for the suggestion! Removed the r- one.

**Comment by druvus** [comment]
Pinging @chapmanb who added the initial version to inform about swapping from r- to bioconductor- prefix

**Comment by chapmanb** [comment]
+1 for swapping over. Thanks for taking this on Vlad. Merging now.

**Pull request merged**
