### PR TITLE
Fix sra-tools “std::exception” error

### LINKED ISSUE #28596: sra-tools 2.11.0 built invalid
Hi there,

I installed the most recent SRA toolkit using `conda install sra-tools`.
Yet, I keep getting the following error:
```
An error occured: std::exception
If this continues to happen, please contact the SRA Toolkit at https://trace.ncbi.nlm.nih.gov/Traces/sra/
```
Searching for similar issues at [sra](https://github.com/ncbi/sra-tools), I can read at [https://github.com/ncbi/sra-tools/issues/497#issuecomment-831906642](https://github.com/ncbi/sra-tools/issues/497#issuecomment-831906642) that the conda built may be invalid.

Many thanks in advance for any help!

### LINKED ISSUE #31396: sra-tools produces an invalid install, important tools like fastq-dump will crash with errors
After a  new install on MacOS

```
conda create -y -n test python=3.8
conda activate test
conda install sra-tools -y
```

running `fastq-dump` produces:

```
$ fastq-dump
An error occured: std::exception
If this continues to happen, please contact the SRA Toolkit at https://trace.ncbi.nlm.nih.gov/Traces/sra/
```

Notably, the package also installs a program called `fastq-dump-orig` that works as expected:

```
$ fastq-dump-orig

Usage:
  fastq-dump-orig [options] <path> [<path>...]
  fastq-dump-orig [options] <accession>

Use option --help for more information

fastq-dump-orig : 2.11.0
```

Since sra-tools are also distributed as statically linked binary packages it would perhaps be simpler and less trouble to include those packages rather than installing from source.

### PR DESCRIPTION
**Pull request by jmarshall**
Fixes #28596 and fixes #31396.

The problem is the `sratools.2.11.0` wrapper's inability to determine the full path to the real `.../fastq-dump-orig.2.11.0` executable. This may have something to do with Conda's prefix rewriting, but the wrapper worked fine when I built it locally. So let's make some infrastructure-based builds of some debugging versions…

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by jmarshall** [comment]
The issue here is that on macOS _sratools.cpp_ determines the path to the executable by manually parsing the Darwin-specific 4th argument to `main()`. It expects it to be of the form

```
executable_path=/path/to/fastq-dump
…
```

whereas it seems that building via Conda causes an older format of this list to be used, of the form

```
/path/to/fastq-dump
…
```

_sratools.cpp_ searches for `executable_path=` and does not accept the older format. We fix this by using `_NSGetExecutablePath()` instead, which understands both formats.

**Comment by jmarshall** [comment]
@BiocondaBot please add label

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@BiocondaBot please merge

**Comment by ialbert** [comment]
@jmarshall Thanks a lot for the fix! It affected everyone using MacOS and immediately benefits the entire community!

**Pull request merged**
