### PR TITLE
Update Mikado to 2.2.4

### PR DESCRIPTION
**Pull request by lucventurini**
Describe your pull request here

Updating Mikado recipe, also changing the minimum Python version to 3.7.

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Review by ljyanesm — APPROVED** [review]

**Comment by lucventurini** [comment]
Dear @dpryan79 

We see that Mikado is currently blocked due to some unspecified bug, in the blacklist. May we have some details on this? We would like to help.

One possibility (but without being able to see the logs it is unclear) is that Mikado was failing the build in `bulk` with Python 3.6. Our automated tests on GitHub actions were masking the fact that since introducing `asyncio` in the codebase Mikado has to be Python 3.7+.

Kind regards,

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Comment by dpryan79** [comment]
@lucventurini I don't recall why it got blacklisted, I was working on 5000 recipes at once. Remove it from the blacklist and see what error there is.

**Comment by lucventurini** [comment]
@dpryan very fair, I should have thought it myself ... we will have a look.
Thank you for your support!

Il giorno mer 7 apr 2021 alle ore 13:27 Devon Ryan ***@***.***>
ha scritto:

**Comment by dpryan79** [comment]
Why portcullis insists on recompiling boost is beyond me. A lot of C++ package that use cmake seem to want to do that for some horrible reason.

**Comment by lucventurini** [comment]
> Why portcullis insists on recompiling boost is beyond me. A lot of C++ package that use cmake seem to want to do that for some horrible reason.

This is explicitly in the codebase. The original developer (@maplesond ) wanted to avoid problems in compilation as Boost can change very quickly. 

In any case portcullis can be dropped from the dependencies. I will do so now.

**Comment by lucventurini** [comment]
@dpryan79 

The `pin_compatible` keyword was making conda failing the package compatibility resolution. I have removed it (fixing `numpy` to be at least 1.17.2, as specified in the `requirements.txt` file) and the building seems to be proceeding.

**Is the `pin_compatible` keyword essential? If yes, how can we resolve the issue?**

Many thanks,

**Review by ljyanesm — APPROVED** [review]

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@bioconda-bot please fetch artifacts

**Comment by dpryan79** [comment]
The pin_compatible macro results in setting the version of numpy compiled against to be the minimum compatible version. Previously, mikado was set to be compiled against numpy 1.17 (or 1.19 with python 3.9) and then run with at least that version. Currently it's compiled against numpy 1.20 and then run on any version >=1.17.2. It's unclear to me whether compiling against a newer version of numpy than one later uses is likely to work long-term.

**Comment by lucventurini** [comment]
Thank you for the explanation, very clear.

Numpy is used at compilation time for some cython functions that use or receive as input arrays. So you are right that it might create incompatibilities.

Do you think that pinning the numpy at compilation time to be greater than 1.17.2, then subsequently reintroducing the `pin_compatible` instruction, could work?

**Comment by dpryan79** [comment]
That's worth a shot, it will basically pin it to >=1.20, since that's what will end up getting used during compilation at the moment.

**Comment by lucventurini** [comment]
> That's worth a shot, it will basically pin it to >=1.20, since that's what will end up getting used during compilation at the moment.

Let's try! I have also pinned `scipy`. Hopefully this will solve the issue for good.

**Comment by lucventurini** [comment]
Hi @dpryan79 

For some reason when pinning versions Conda is trying to find something compatible even in the python 2.7 domain. I am not really sure of what is going on here, to be completely honest ...

Best,

**Comment by dpryan79** [comment]
I'll play around with this a bit to see if I can get it working properly.

**Comment by dpryan79** [comment]
OK, this was just a case of the conda solver being annoying when you need to use `pin_compatible()`, which is the appropriate thing to use. When you use that in conjunction with `>=x.y.z it insists on using x.y.z for some weird reason instead of taking it as a minimal acceptable version. The versions that get pulled in (and then pinned against correctly) fulfill the minimum version restrictions already, thankfully.

**Comment by lucventurini** [comment]
> OK, this was just a case of the conda solver being annoying when you need to use pin_compatible(), which is the appropriate thing to use. When you use that in conjunction with `>=x.y.z it insists on using x.y.z for some weird reason instead of taking it as a minimal acceptable version. The versions that get pulled in (and then pinned against correctly) fulfill the minimum version restrictions already, thankfully.

@dpryan79 

This would have eluded me and @ljyanesm for a long time, I am pretty sure. Thank you so much for the amazing work and for all the effort you are making to keep bioconda functional, it is really appreciated.

**Comment by lucventurini** [comment]
Hi @dpryan79 

For some reason the Conda builder failed when it should have created the packages .. it said it could not remove the README.md due to "permission denied".

No idea of why it would fail this time.

**Comment by lucventurini** [comment]
@bioconda-bot please fetch artifacts

**Comment by dpryan79** [comment]
Should be good to go now, go ahead and tell the bot to merge it whenever you're ready.

**Comment by lucventurini** [comment]
@dpryan79 

Many thanks for your hard work!

@BiocondaBot please merge

**Comment by lucventurini** [comment]
@BiocondaBot please merge

**Pull request merged**
