### PR TITLE
WIP: Add nanoOK

### PR DESCRIPTION
**Pull request by druvus**
* [x] I have read the guidelines above.
* [x] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by nsoranzo** [comment]
Maybe @richardmleggett can help here.

**Comment by richardmleggett** [comment]
Hi both, I'm afraid I don't know anything about bioconda, but I'd be very happy to help with queries about the NanoOK build/installation process if you get in contact with me by email. Also NanoOK now up to release 1.22. Thanks!

**Comment by druvus** [comment]
@nsoranzo @richardmleggett the build is basically working but I was waiting for the R migration to be finished so bioconda and conda-forge R versions would be in sync. I will add the missing R dependencies to bioconda right now.

**Comment by druvus** [comment]
@bgruening @johanneskoester how should we do with new R packages? I have added the R dependencies to conda-forge but I not totally updated on the R migrate status so would you recommend me to wait until conda_R is pinned to 3.4 or build them in bioconda while waiting (#4677).

**Comment by johanneskoester** [comment]
I would prefer to wait until the migration strategy has been decided. I am currently trying to build r-base 3.4 on conda-forge and we are discussing the future pinning schema (see [here](https://github.com/conda-forge/r-base-feedstock/pull/16)). But if it is really urgent for you, you can also add the packages to bioconda for now.

**Comment by druvus** [comment]
Then I stick to my original idea to wait until it is ready.

**Comment by richardmleggett** [comment]
Thanks, Andreas! Clearly I need to find out more about bioconda!

**Comment by johanneskoester** [comment]
We have migrated our build system from Travis CI to Circle CI. If you would like to continue working on this PR, please update with latest upstream master and reopen this PR.

**Pull request closed without merging**
