### PR TITLE
Update viennarna

### PR DESCRIPTION
**Pull request by zachcp**
Bump the build for `viennarna` to allow building for py311 and py312

@BiocondaBot please update

### CODE REVIEW

**Comment by zachcp** [comment]
Hoping to build this for py311 and py312 now that there is an updated  [bioconda-utils](https://github.com/bioconda/bioconda-utils/pull/991)

**Comment by martin-g** [comment]
@BiocondaBot please fetch artifacts

**Comment by martin-g** [comment]
> Hoping to build this for py311 and py312 now that there is an updated [bioconda-utils](https://github.com/bioconda/bioconda-utils/pull/991)

The new bioconda-utils (ver. 3.x) is used only in the `bulk` branch for now).
This PR does not bring Python 3.11/3.12 packages, so I think it should be closed.

**Comment by zachcp** [comment]
Ah. I see. I didn't realize that 3.11 and 3.12 are still bilk-branch-only. Thank you @martin-g

**Pull request closed without merging**
