### PR TITLE
updated bioconductor-masigpro

### PR DESCRIPTION
**Pull request by asntech**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by daler** [comment]
@asntech, @bgruening should we do a big bulk update of moving everything to Bioc 3.6?

**Comment by bgruening** [comment]
If there is no hurry, I would wait one or two weeks and let the dust settle down a little bit. But the bulk branch is free now, right?

**Comment by daler** [comment]
This is the first time we're ready for it when there's a new release! Is there generally a settling-down time for BioC? I may do some local tests to see what we're up against but not push anything. And yep, bulk branch is free as far as I know.

**Comment by bgruening** [comment]
It's just my personal preference to wait a little bit and see .1 releases popping up. Its true we are in a good shape to build it - if you want please lets start it, I will help you.

**Pull request merged**
