### PR TITLE
Bump sqt to v0.8.0

### PR DESCRIPTION
**Pull request by marcelm**
* [ ] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by daler** [comment]
@marcelm see #3080, we're working out build issues. I cancelled the OSX builds here since the linux already failed. That way hopefully we can free up osx resources to speed up the fixes..

**Comment by marcelm** [comment]
Sure! I noticed #3080 after submitting this PR. Thanks for working on it.

**Comment by daler** [comment]
@marcelm should be fixed now, can you give it a shot?

**Comment by marcelm** [comment]
@daler I cancelled the build after 45 minutes. Normal would be less than 2 minutes.

**Pull request merged**
