### PR TITLE
Add ProteomIQon.ProteinInference

### PR DESCRIPTION
**Pull request by ZimmerA**
This PR adds ProteomIQon.ProteinInference.

MS-based shotgun proteomics estimates protein abundances using a proxy: peptides. The process of 'Protein Inference' is concerned with the mapping of identified peptides to the proteins they putatively originated from.

### CODE REVIEW

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
@bioconda-bot please merge

**Comment by ZimmerA** [comment]
@bgruening Did something hang up here? Same for https://github.com/bioconda/bioconda-recipes/pull/28500

**Comment by bgruening** [comment]
@bioconda-bot please merge

**Comment by bgruening** [comment]
Probably let's try again :)

**Pull request merged**
