### PR TITLE
portcullis 1.1.0

### PR DESCRIPTION
**Pull request by maplesond**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by maplesond** [comment]
Migrated from PR #8306

**Comment by daler** [comment]
Hmm what if you disable circle-ci from your fork?

**Comment by maplesond** [comment]
Hmm, deleting the webhook from my fork didn't seem to trigger anything itself.  Should I try recreating the PR on a branch on the main fork instead (if that's possible)?

**Comment by daler** [comment]
@maplesond you'll have to click the big red "Stop Building" button through the CircleCI interface for your fork. Based on my testing this morning that should do the trick.

You'll have to push another change to this PR to trigger the re-build. xref https://github.com/bioconda/bioconda-utils/pull/286

**Comment by maplesond** [comment]
Hi @Daler, I went into circleCI for my account "maplesond", then to "settings" -> "projects" -> "bioconda_recipes", then clicked on the red button.  Then I amended the previous commit and force pushed.  Not sure this worked though as for macos it says "Waiting for status to be reported".

**Comment by daler** [comment]
@maplesond yep, that's normal. We have it set up so that macOS will only run if the linux build is successful. I see that the linux test is running on the bioconda account, so we should be good now!

**Pull request merged**
