### PR TITLE
Updated GRIDSS recipe to reflect GRIDSS API

### PR DESCRIPTION
**Pull request by d-cameron**
- Switched to using the gridss wrapper script instead of the java entry point directly
- Added driver scripts for all GRIDSS programs

----

> Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it.

* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences**
      (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [X] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

@BiocondaBot please fetch artifacts

@BiocondaBot please add label

### CODE REVIEW

**Comment by d-cameron** [comment]
So this has been a bit of a mess to build a recipe for.

- I can't seem to test locally (see gitter)
- The main GRIDSS program is a java program with a bash wrapper
- The gridss jar also has ~15 other entry points, each of which are a stand-alone program
- There are 2 command line R scripts

All programs need to know the install path to find either the jar, or the `libgridss.R` common script.

Any advise as to the best approach to handle this is welcome.

**Comment by d-cameron** [comment]
@BiocondaBot please add label

**Comment by dpryan79** [comment]
@bioconda-bot please fetch artifacts

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Pull request merged**
