### PR TITLE
Update maker to version 2.31.11

### PR DESCRIPTION
**Pull request by nathanweeks**
Patch-level update; per RELEASE file:

> *maker_functional_fasta and maker_functional_gff handle newer UniProt/Swiss-Prot
 format. Also fix for newer genemark command line structure.

Also an attempt to fix https://github.com/bioconda/bioconda-recipes/issues/25559

### CODE REVIEW

**Comment by nathanweeks** [comment]
Hmm, probably an HTTP server hiccup:
```
22:38:02 BIOCONDA INFO (OUT) conda.CondaError: Downloaded bytes did not match Content-Length
22:38:02 BIOCONDA INFO (OUT)   url: http://yandell.topaz.genetics.utah.edu/maker_downloads/static/maker-2.31.11.tgz
22:38:02 BIOCONDA INFO (OUT)   target_path: /opt/conda/conda-bld/src_cache/maker-2.31.11_129ce1d33d.tgz
22:38:02 BIOCONDA INFO (OUT)   Content-Length: 13608220
22:38:02 BIOCONDA INFO (OUT)   downloaded bytes: 9614547
```
Trying again (after updating dependencies blast & rmblast to 2.10.0).

**Comment by nathanweeks** [comment]
OK, there was no bioconda blast=2.10.0 package---it jumped from 2.9.0 to 2.10.1. However, there is no rmblast 2.10.1...

**Comment by nathanweeks** [comment]
@bioconda-bot please fetch artifacts

**Comment by abretaud** [comment]
Thanks for updating this recipe!
I think you're right, no problem to omit mir-prefer for the non -P flavor of maker
Is it still needed to pin trnascan-se? If not it would be better to unpin it

**Comment by nathanweeks** [comment]
Thanks for the confirmation; I'll do some cursory testing. AFAIK, MAKER [still requires trnascan-se 1.3.1](https://groups.google.com/g/maker-devel/c/br-49e1SbL4/m/n72ZEUsqAwAJ).

**Comment by bernt-matthias** [comment]
@BiocondaBot please fetch artifacts

**Comment by bernt-matthias** [comment]
Seems that the last artifact is no longer available. I will test this with the Galaxy tool .. which currently fails CI.

**Comment by nathanweeks** [comment]
OK, also, I noticed that there's an issue with repeat masking enabled, thanks to the new FamDB (HDF5) format used by RepeatMasker 4.1.1. Looking into a workaround...

**Comment by bernt-matthias** [comment]
The problem I mentioned in https://github.com/bioconda/bioconda-recipes/issues/25559#issuecomment-737414939 persists :( 

There are also the following messages:

```
Possible unintended interpolation of @2 in string at /home/berntm/miniconda3/envs/__maker@2.31.10/bin/../lib/5.26.2/x86_64-linux-thread-multi/Config_heavy.pl line 260.
Possible precedence issue with control flow operator at /home/berntm/perl5/lib/perl5/Bio/DB/IndexedBase.pm line 845.
Possible unintended interpolation of @2 in string at /home/berntm/miniconda3/envs/__maker@2.31.10/bin/../lib/5.26.2/x86_64-linux-thread-multi/Config_heavy.pl line 260.
Possible precedence issue with control flow operator at /home/berntm/perl5/lib/perl5/Bio/DB/IndexedBase.pm line 845.
```

But I guess this is not the main problem.

**Comment by nathanweeks** [comment]
I haven't observed the `Possible unintended interpolation of @2...` warning, but the `Possible precedence issue with control flow operator...` warning is harmless (see https://github.com/bioconda/bioconda-recipes/issues/16501#issuecomment-537098270)

**Comment by bernt-matthias** [comment]
> I haven't observed the `Possible unintended interpolation of @2...` warning, but the `Possible precedence issue with control flow operator...` warning is harmless (see [#16501 (comment)](https://github.com/bioconda/bioconda-recipes/issues/16501#issuecomment-537098270))

This happens because Galaxy installs conda envs in a path containing an `@` (separating the tool name and the version) which often creates problems. But its good to know that this is not the problem.

**Comment by nathanweeks** [comment]
The bioconda RepeatMasker package doesn't support a custom REPEATMASKER_LIB_DIR environment variable anymore, and the upstream RepeatMasker has apparently supported an equivalent [LIBDIR environment variable](https://github.com/rmhubley/RepeatMasker/commit/61934193eb74b9fd0f27192342aeb4b0d39866f3) since 4.1.x or so. Replacing REPEATMASKER_LIB_DIR with LIBDIR in repeatmasker_check.patch allows the previous [symlink trick](https://github.com/rmhubley/RepeatMasker/issues/19#issuecomment-491344400) to use RepeatMasker installed in a Singularity image, where the libraries are in a read-only directory.

**Comment by nathanweeks** [comment]
@BiocondaBot please fetch artifacts

**Comment by nathanweeks** [comment]
@bernt-matthias : I'm not familiar with using MAKER in Galaxy, but glancing at the tool, it appears that [this line](https://github.com/galaxyproject/tools-iuc/blob/master/tools/maker/maker.xml#L11) would need to be updated to reflect the REPEATMASKER_LIB_DIR -> LIBDIR  environment variable rename.

**Comment by bernt-matthias** [comment]
> @bernt-matthias : I'm not familiar with using MAKER in Galaxy, but glancing at the tool, it appears that [this line](https://github.com/galaxyproject/tools-iuc/blob/master/tools/maker/maker.xml#L11) would need to be updated to reflect the REPEATMASKER_LIB_DIR -> LIBDIR environment variable rename.

Seems not to work (I just added bot variables). Tried the latest in bioconda and the last artifact from this PR.

**Comment by nathanweeks** [comment]
> > @bernt-matthias : I'm not familiar with using MAKER in Galaxy, but glancing at the tool, it appears that [this line](https://github.com/galaxyproject/tools-iuc/blob/master/tools/maker/maker.xml#L11) would need to be updated to reflect the REPEATMASKER_LIB_DIR -> LIBDIR environment variable rename.
> 
> Seems not to work (I just added bot variables). Tried the latest in bioconda and the last artifact from this PR.

What was the error?

**Comment by bernt-matthias** [comment]
The same error as described in https://github.com/bioconda/bioconda-recipes/issues/25559#issuecomment-737414939 .. `Species "anopheles" is not known to RepeatMasker. ....`

**Comment by abretaud** [comment]
Hey!
So I propose a modification of the maker patch in https://github.com/harvardinformatics/bioconda-recipes/pull/1
And I've made a draft PR to test the package with galaxy : https://github.com/galaxyproject/tools-iuc/pull/3383

**Comment by nathanweeks** [comment]
@BiocondaBot please fetch artifacts

**Comment by nathanweeks** [comment]
@abretaud: Thanks! Your modifications LGTM (at least, the Singularity-container-with-LIBDIR-symlinks trick still seemed to work in my cursory testing).

**Review by abretaud — APPROVED** [review]

**Comment by abretaud** [comment]
@bioconda-bot please merge

**Pull request merged**
