### PR TITLE
Add Linux aarch64 build for more Bioconductor packages

### PR DESCRIPTION
**Pull request by martin-g**
- bdmmacorrect
- biocsingular
- buscorrect
- exomecopy
- genomicalignments
- interactionset

Describe your pull request here

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

### General instructions

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

### Instructions for avoiding API, ABI, and CLI breakage issues
Conda is able to record and lock (a.k.a. pin) dependency versions used at build time of other recipes.
This way, one can avoid that expectations of a downstream recipe with regards to API, ABI, or CLI are violated by later changes in the recipe.
If not already present in the meta.yaml, make sure to specify `run_exports` (see [here](https://bioconda.github.io/contributor/linting.html#missing-run-exports) for the rationale and comprehensive explanation).
Add a `run_exports` section like this:

```yaml
build:
  run_exports:
    - ...

```

with `...` being one of:

| Case                             | run_exports statement                                               |
| -------------------------------- | ------------------------------------------------------------------- |
| semantic versioning              | `{{ pin_subpackage("myrecipe", max_pin="x") }}`     |
| semantic versioning (0.x.x)      | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}`   |
| known breakage in minor versions | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| known breakage in patch versions | `{{ pin_subpackage("myrecipe", max_pin="x.x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| calendar versioning              | `{{ pin_subpackage("myrecipe", max_pin=None) }}`    |

while replacing `"myrecipe"` with either `name` if a `name|lower` variable is defined in your recipe or with the lowercase name of the package in quotes.

### Bot commands for PR management

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

Note that the <code>@BiocondaBot please merge</code> command is now depreciated. Please just squash and merge instead.

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by martin-g** [comment]
Depends on:
- https://github.com/bioconda/bioconda-recipes/pull/47861

**Comment by martin-g** [comment]
@BiocondaBot please add label

**Comment by martin-g** [comment]
@BiocondaBot please fetch artifacts

**Comment by martin-g** [comment]
```

mgrigorov in 🌐 euler-arm-22 in /tmp/chipseqr via 🅒 test123 took 7s 
❯ tar xvf bioconductor-buscorrect-1.20.0-r43h1184a65_1.tar.bz2                                                                                                                                             (test123) 
info/test/run_test.sh
info/run_exports.json
info/recipe/build.sh
info/hash_input.json
info/index.json
info/files
info/recipe/meta.yaml.template
info/recipe/conda_build_config.yaml
info/paths.json
info/recipe/meta.yaml
info/about.json
info/licenses/LICENSE0.txt
info/git
lib/R/library/BUScorrect/data/datalist
lib/R/library/BUScorrect/data/BUSexample_data.RData
lib/R/library/BUScorrect/help/AnIndex
lib/R/library/BUScorrect/help/BUScorrect.rdb
lib/R/library/BUScorrect/R/BUScorrect.rdb
lib/R/library/BUScorrect/CITATION
lib/R/library/BUScorrect/NAMESPACE
lib/R/library/BUScorrect/DESCRIPTION
lib/R/library/BUScorrect/INDEX
lib/R/library/BUScorrect/libs/BUScorrect.so
lib/R/library/BUScorrect/Meta/data.rds
lib/R/library/BUScorrect/Meta/features.rds
lib/R/library/BUScorrect/Meta/vignette.rds
lib/R/library/BUScorrect/help/aliases.rds
lib/R/library/BUScorrect/help/paths.rds
lib/R/library/BUScorrect/Meta/links.rds
lib/R/library/BUScorrect/Meta/nsInfo.rds
lib/R/library/BUScorrect/Meta/hsearch.rds
lib/R/library/BUScorrect/Meta/Rd.rds
lib/R/library/BUScorrect/Meta/package.rds
lib/R/library/BUScorrect/R/BUScorrect
lib/R/library/BUScorrect/doc/BUScorrect_user_guide.pdf
lib/R/library/BUScorrect/help/BUScorrect.rdx
lib/R/library/BUScorrect/R/BUScorrect.rdx
lib/R/library/BUScorrect/doc/index.html
lib/R/library/BUScorrect/html/00Index.html
lib/R/library/BUScorrect/unitTests/test_BUSgibbs.R
lib/R/library/BUScorrect/doc/BUScorrect_user_guide.R
lib/R/library/BUScorrect/NEWS.Rd
lib/R/library/BUScorrect/doc/BUScorrect_user_guide.Rnw
lib/R/library/BUScorrect/html/R.css

mgrigorov in 🌐 euler-arm-22 in /tmp/chipseqr via 🅒 test123 
❯ conda install ./bioconductor-buscorrect-1.20.0-r43h1184a65_1.tar.bz2                                                                                                                                     (test123) 

Downloading and Extracting Packages:
                                                                                                                                                                                                                     

Downloading and Extracting Packages:

Preparing transaction: done
Verifying transaction: done
Executing transaction: done

mgrigorov in 🌐 euler-arm-22 in /tmp/chipseqr via 🅒 test123 took 7s 
❯ ~/miniconda3/envs/test123/bin/R                                                                                                                                                                          (test123) 

R version 4.3.1 (2023-06-16) -- "Beagle Scouts"
Copyright (C) 2023 The R Foundation for Statistical Computing
Platform: aarch64-conda-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

[Previously saved workspace restored]

> library(BUScorrect)
Error: package or namespace load failed for ‘BUScorrect’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called ‘gplots’
In addition: Warning message:
package ‘BUScorrect’ was built under R version 4.3.3 
> 
Save workspace image? [y/n/c]: y

mgrigorov in 🌐 euler-arm-22 in /tmp/chipseqr via 🅒 test123 took 52s 
❯ conda install  r-gplots                                                                                                                                                                                  (test123) 
Channels:
 - bioconda
 - conda-forge
 - martin-g
 - Kunpeng_conda
 - defaults
Platform: linux-aarch64
Collecting package metadata (repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
    current version: 24.3.0
    latest version: 24.5.0

Please update conda by running

    $ conda update -n base -c conda-forge conda



## Package Plan ##

  environment location: /home/mgrigorov/miniconda3/envs/test123

  added / updated specs:
    - r-gplots


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    r-catools-1.18.2           |    r43h93f32a7_2         217 KB  conda-forge
    r-gplots-3.1.3.1           |    r43hc72bb7e_0         590 KB  conda-forge
    r-gtools-3.9.5             |    r43h25e906a_0         360 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         1.1 MB

The following NEW packages will be INSTALLED:

  r-catools          conda-forge/linux-aarch64::r-catools-1.18.2-r43h93f32a7_2 
  r-gplots           conda-forge/noarch::r-gplots-3.1.3.1-r43hc72bb7e_0 
  r-gtools           conda-forge/linux-aarch64::r-gtools-3.9.5-r43h25e906a_0 


Proceed ([y]/n)? 


Downloading and Extracting Packages:
                                                                                                                                                                                                                     
Preparing transaction: done                                                                                                                                                                                          
Verifying transaction: done                                                                                                                                                                                          
Executing transaction: done

mgrigorov in 🌐 euler-arm-22 in /tmp/chipseqr via 🅒 test123 took 53s 
❯ ~/miniconda3/envs/test123/bin/R                                                                                                                                                                          (test123) 

R version 4.3.1 (2023-06-16) -- "Beagle Scouts"
Copyright (C) 2023 The R Foundation for Statistical Computing
Platform: aarch64-conda-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

[Previously saved workspace restored]

> library(BUScorrect)
Warning message:
package ‘BUScorrect’ was built under R version 4.3.3 

```
LGTM!

**Review by mencian — APPROVED** [review]

**Pull request merged**
