### PR TITLE
Bump meraculous

### PR DESCRIPTION
**Pull request by mictadlo**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by mictadlo** [comment]
Should I close this pull request and resubmit it again?

**Comment by dpryan79** [comment]
No, just remove it from the blacklist in your fork.

**Comment by mictadlo** [comment]
I removed it from `build-fail-blacklist` and did
```
git checkout master
git pull upstream master
git push origin master
```

**Comment by dpryan79** [comment]
It's not present in the PR, so you need to push that still.

**Comment by corburn** [comment]
`{{ version }}` is undefined in the license_file and the build number should be reset to zero

**Comment by mictadlo** [comment]
I removed {{ version }} because it did not support `-`.

**Comment by corburn** [comment]
@mictadlo just pointing out `{{ version }}` on [line 43](https://github.com/mictadlo/bioconda-recipes/blob/9730ad2f1651909bdea90e5998d681c0777ca6cc/recipes/meraculous/meta.yaml#L43) will trigger an undefined error:

```
license_file: Meraculous-v{{ version }}/license.txt
```

If you want to include `{{ version }}`, you could use the replace filter:

```
{% set version = "2.2.5.1-1" %}

version: '{{ version | replace("-", ".") }}'
```

**Comment by mictadlo** [comment]
I changed all suggestions and resubmitted in the following way:
```
$ git push -u origin meraculous 
Username for 'https://github.com': mictadlo
Password for 'https://mictadlo@github.com': 
Enumerating objects: 9, done.
Counting objects: 100% (9/9), done.
Delta compression using up to 2 threads.
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 605 bytes | 605.00 KiB/s, done.
Total 5 (delta 3), reused 0 (delta 0)
remote: Resolving deltas: 100% (3/3), completed with 3 local objects.
To https://github.com/mictadlo/bioconda-recipes.git
   9730ad2f1..8d8dc3e79  meraculous -> meraculous
Branch 'meraculous' set up to track remote branch 'meraculous' from 'origin'.
```

**Comment by dpryan79** [comment]
LGTM!

**Comment by mictadlo** [comment]
Did it work because I can only see 2.2.5  rather than  2.2.5.1.1

**Comment by dpryan79** [comment]
It seems that meraculous was still blacklisted in `master`. Let me make a quick PR and see if I can fix that.

**Comment by dpryan79** [comment]
This should be building on `master` shortly, it took a bit more fighting than I care to admit.

**Pull request merged**
