### PR TITLE
Update influx_si to 7.0.4

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`influx_si`](https://bioconda.github.io/recipes/influx_si/README.html): **7.0.3** &rarr; **7.0.4**

[install with bioconda](http://bioconda.github.io/recipes/influx_si/README.html) [Conda](https://anaconda.org/bioconda/influx_si/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/influx_si`](https://github.com//bioconda/bioconda-recipes/tree/bump/influx_si/recipes/influx_si) (click to view/edit other files)
Summary | Metabolic flux and concentration estimation based on stable isotope labeling
Home | [https://metasys.insa-toulouse.fr/software/influx/](https://metasys.insa-toulouse.fr/software/influx/)
Releases |[https://pypi.org/pypi/influx_si/json](https://pypi.org/pypi/influx_si/json)
Recipe Maintainer(s) | @sgsokol

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by sgsokol** [comment]
Hi I would like to bring some modifications to this meta.yaml (add r-bitops to dependencies and modify home and doc entries). If I remember well, it was possible to do it directly in the PR but now the pencil icon (for editing) is greyed. I can only see the new file. How can I modify it?
Thanks.

**Comment by martin-g** [comment]
You could checkout the PR branch with `gh pr checkout 47934` (using Github [command line client](https://cli.github.com/)) and edit it locally.
If this does not work for some reason then you could open a new PR and (ask to) close this one.

**Comment by sgsokol** [comment]
Please close this PR (#47934) and consider to approve #47958.
 Thanks

**Comment by sgsokol** [comment]
> You could checkout the PR branch with `gh pr checkout 47934` (using Github [command line client](https://cli.github.com/)) and edit it locally. 

I get an error 
```
gh pr checkout 47934
GraphQL: Could not resolve to a PullRequest with the number of 47934. (repository.pullRequest)
```
When I try to set a repository, it does not recognise the name or formats
```
gh repo set-default bump/influx_si
bump/influx_si does not correspond to any git remotes
repo set-default bioconda/bioconda-recipes
bioconda/bioconda-recipes does not correspond to any git remotes
gh repo set-default https://github.com/bioconda/bioconda-recipes/tree/bump/influx_si
invalid path: /bioconda/bioconda-recipes/tree/bump/influx_si
```
What is the repository that I should to set to?
Thanks.

**Pull request merged**
