### PR TITLE
 update sbpipe recipe from 4.20.0 to 4.21.0

### PR DESCRIPTION
**Pull request by pdp10**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by pdp10** [comment]
**NOTE:** 
This PR depends on PR #9619 .

**Comment by pdp10** [comment]
The circleci tests should be restarted once r-sbpiper 1.9.0 is available on anaconda :bioconda.

**Comment by pdp10** [comment]
@bgruening  
Would it be possible to restart the ci/circleci tests now that r-sbpiper 1.9.0 is available on bioconda, please?

**Comment by bgruening** [comment]
You might want to merge master into this branch :)

**Comment by bgruening** [comment]
We are still rebuilding all pkgs ... this will still take some time. It might help if you check if this pkg is on the blacklist and if so remove it and trigger a rebuild.

**Comment by pdp10** [comment]
Do you mean this file: https://github.com/bioconda/bioconda-recipes/blob/master/sorted-r-blacklist  ? 

If so, r-sbpiper is not on the blacklist.

**Comment by dpryan79** [comment]
Closing as this has since been updated

**Pull request closed without merging**
