### PR TITLE
Added recipe for UMI-tools

### PR DESCRIPTION
**Pull request by matthdsm**
* [x] I have read the guidelines above.
* [x] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

Added recipe for UMI tools (https://github.com/CGATOxford/UMI-tools) to use as Galaxy tool dependency

### CODE REVIEW

**Comment by matthdsm** [comment]
@bgruening  @roryk  or any other commiter, can you guys merge this? I'd like to use it as a dependency for a tool in Galaxy

**Comment by matthdsm** [comment]
Thanks @bgruening !

**Comment by bgruening** [comment]
@matthdsm sorry for being so late. You can merge your own PR if they are compliant to our Guidelines and if travis is happy. Want to join the club?

**Comment by bgruening** [comment]
Thanks to you @matthdsm!

**Comment by matthdsm** [comment]
Oh, wow, that's a nice offer, I feel honored 😊 
Sure, I'll join!

Thanks!

**Comment by bgruening** [comment]
@matthdsm nothing to special, sorry ;)
https://github.com/bioconda/bioconda-recipes/issues/1

I invited you already.
Thanks for your contributions, very valuable? Do I see you on IUC again? :)

**Comment by matthdsm** [comment]
It'll make life a bit easier anyway. I'll be going on a vacation next week, but the tool should be coming shortly thereafter!

see you at IUC indeed!
M

**Comment by bgruening** [comment]
Amazing! Enjoy!

**Pull request merged**
