### PR TITLE
abyss-k128: remove recipe in favor of abyss-2.0.2-boost1.64_3

### PR DESCRIPTION
**Pull request by mbargull**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [x] This PR does something else (explain below).

Followup on https://github.com/bioconda/bioconda-recipes/pull/6867#issuecomment-346438576
@jerowe: I suppose this one is for you to decide. From build `abyss-2.0.2-boost1.64_3` onward the default value of `maxk=128` from `abyss 2.0` is used. That makes `abyss-k128` redundant so that we could remove its recipe.

### CODE REVIEW

**Comment by jerowe** [comment]
@mbargull , if 128 is the new default this is redundant. Would you happen to know about the other compilations? I mainly build things for researchers at my job, and I know my boss very particularly wanted the other compilation options. Removing the recipe doesn't remove the package from conda.

**Comment by jerowe** [comment]
Thanks!

**Comment by jerowe** [comment]
Yes, the 96 kmer size.

**Comment by mbargull** [comment]
Three options come to mind:
* explicitly depend on an older build `abyss-2.0.2-boost1.64_1` -- But I wouldn't like to depend on that implicit assumption, "builds `<2` => 96, `>=2` => 128" if I were you.
* use `1.9.0` which has a default of 96 -- of course only applicable if `1.9` and `2.0` are otherwise identical for your use case.
* create a `abyss-k96` package

**Pull request merged**
