### PR TITLE
MA 1.1.4 & python 3.6

### PR DESCRIPTION
**Pull request by ITBE-Lab**
I tried updating MA via the autobump but checks failed with python<3.9 (https://github.com/bioconda/bioconda-recipes/pull/26601).
As far as I can tell, the checks failed because python 3.9 and 3.7 were mixed during building and testing.

This pull request exists because I'd like to have a python>=3.6 requirement.

### CODE REVIEW

**Comment by ITBE-Lab** [comment]
@BiocondaBot please add label

**Comment by ITBE-Lab** [comment]
It would be really appreciated if someone could explain to me why it worked this way but not via the autobump even though recipe & program are the same.

Sorry to cause another review...

**Comment by dpryan79** [comment]
@bioconda-bot please fetch artifacts

**Comment by dpryan79** [comment]
Right, so this is an annoying conda thing wherein you can only restrict python to >3.6 like this if your package is "noarch: python". This trips people up constantly and I really wish the conda builder would handle this better :(

I'll update the PR to do what you intend.

**Comment by ITBE-Lab** [comment]
Okay, thank you!

I guess I'll know that from now on...

**Comment by dpryan79** [comment]
@bioconda-bot please fetch artifacts

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Pull request merged**
