### PR TITLE
Update galaxyxml to 0.4.13

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`galaxyxml`](https://bioconda.github.io/recipes/galaxyxml/README.html): **0.4.12** &rarr; **0.4.13**

[install with bioconda](http://bioconda.github.io/recipes/galaxyxml/README.html) [Conda](https://anaconda.org/bioconda/galaxyxml/files)

Info | Link
-----|-----
Recipe | [`recipes/galaxyxml`](https://github.com//bioconda/bioconda-recipes/tree/bump/galaxyxml/recipes/galaxyxml) (click to view/edit other files)
Releases |[https://pypi.org/pypi/galaxyxml/json](https://pypi.org/pypi/galaxyxml/json)
Recipe Maintainer(s) | @bernt-matthias, @hexylena

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Review by hexylena — APPROVED** [review]

**Review by fubar2 — APPROVED** [review]
Version bump is ok by me for whatever that's worth

**Comment by bgruening** [comment]
ModuleNotFoundError: No module named 'galaxy'

Looks like you need to add a dependency on galaxy tool until?

**Comment by hexylena** [comment]
Eek, thanks @bgruening. That wasn't in the release notes so I missed that.

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
@bioconda-bot please merge

**Comment by bgruening** [comment]
No problem @hexylena!

**Pull request merged**
