### PR TITLE
update IsoQuant to 3.1.1

### PR DESCRIPTION
**Pull request by andrewprzh**
Updates IsoQuant to the latest 3.1.1, several bug-fixes made compared to 3.1.0

### CODE REVIEW

**Comment by andrewprzh** [comment]
@BiocondaBot please add label

**Comment by andrewprzh** [comment]
@bioconda-bot please add label

**Review by mjsteinbaugh — APPROVED** [review]

**Comment by mjsteinbaugh** [comment]
@BiocondaBot please merge

**Comment by andrewprzh** [comment]
@BiocondaBot please merge

**Pull request merged**
