### PR TITLE
Hap312

### PR DESCRIPTION
**Pull request by bwlang**
This makes hap.py compile again

----

> Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it.

* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [ ] This PR adds a new recipe.
* [X] AFAIK, this recipe **is directly relevant to the biological sciences**
      (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [X] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

> Everyone has access to the following BiocondaBot commands, which can be given in a comment:
>
>  * `@BiocondaBot please update` will cause the BiocondaBot to merge the master branch into a PR
>  * `@BiocondaBot please add label` will add the `please review & merge` label.
>  * `@BiocondaBot please fetch artifacts` will post links to packages and docker containers built by the CI system. You can use this to test packages locally before merging.
>
> For members of the Bioconda project, the following command is also available:
>
>  * `@BiocondaBot please merge` will cause packages/containers to be uploaded and a PR merged. Someone must approve a PR first! This has the benefit of not wasting CI build time required by manually merging PRs.
>
> If you have questions, please post them in gitter or ping `@bioconda/core` in a comment (if you are not able to directly ping `@bioconda/core` then the bot will repost your comment and enable pinging).

### CODE REVIEW

**Comment by bwlang** [comment]
@BiocondaBot please add label

**Comment by bwlang** [comment]
@BiocondaBot please fetch artifact

**Comment by bwlang** [comment]
@BiocondaBot please fetch artifacts

**Comment by bwlang** [comment]
@BiocondaBot please fetch artifacts

**Comment by druvus** [comment]
@bwlang hap.py is blacklisted so you need to remove it from `build-fail-blacklist` to test and build it.

**Comment by bwlang** [comment]
@BiocondaBot please fetch artifacts

**Comment by bwlang** [comment]
@BiocondaBot please fetch artifacts

**Comment by bwlang** [comment]
I've just run this on real data files... seems to be working properly :
```
 Type Filter  TRUTH.TOTAL  TRUTH.TP  TRUTH.FN  QUERY.TOTAL  QUERY.FP  QUERY.UNK   FP.gt  FP.al  METRIC.Recall  METRIC.Precision  METRIC.Frac_NA  METRIC.F1_Score  TRUTH.TOTAL.TiTv_ratio  QUERY.TOTAL.TiTv_ratio  TRUTH.TOTAL.het_hom_ratio  QUERY.TOTAL.het_hom_ratio
 INDEL    ALL       533855     29123    504732       173230    144012          0   19984  22716       0.054552          0.168666             0.0         0.082440                     NaN                     NaN                   1.680307                   1.466483
 INDEL   PASS       533855     29123    504732       173230    144012          0   19984  22716       0.054552          0.168666             0.0         0.082440                     NaN                     NaN                   1.680307                   1.466483
   SNP    ALL      3085616    264139   2821477       803609    539381          0  180024  15882       0.085603          0.328802             0.0         0.135841                 2.09939                1.358591                   1.548133                   0.286279
   SNP   PASS      3085616    264139   2821477       803609    539381          0  180024  15882       0.085603          0.328802             0.0         0.135841                 2.09939                1.358591                   1.548133                   0.286279
```

**Comment by dpryan79** [comment]
@bioconda-bot please merge

Well done @bwlang!

**Pull request merged**
