### PR TITLE
Feature/abyss rebuild

### PR DESCRIPTION
**Pull request by jerowe**
* [ ] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

Rebuilding abyss with openmpi support so abyss-p works.

### CODE REVIEW

**Comment by jerowe** [comment]
@bgruening , are we not subscribed to anaconda recipes?

**Comment by bgruening** [comment]
What do you mean?

**Comment by jerowe** [comment]
@bgruening , nevermind. I wanted the openmpi package, but it was only listed for osx. Does this mean its included in the base anaconda for linux?

**Comment by jerowe** [comment]
@bgruening , I answered my own question. I coopted the mpi4py's channel openmpi and added it to bioconda.

**Pull request merged**
