### PR TITLE
Add oligomap software package

### PR DESCRIPTION
**Pull request by deliaBlue**
Add `oligomap` software package to Bioconda.
`Oligomap` is a program for fast identification of nearly-perfect matches of small RNAs in sequence databases. It allows to exhaustively identify all the perfect and 1-error (where an error is defined to be a mismatch, insertion or deletion) matches of large sets of small RNAs to target sequences. 

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by deliaBlue** [comment]
Hey @bgruening, 

I've been working on the recipe for the Zavolanlab `oligomap` software package and, even if it passes the lint and Linux tests, it does not pass the OS X one. I am not a Mac user and I do not have the experience enough to find the correct lines to fix the problem. 
From the output error (see below) I cannot infer what could be the problem. I'm not sure if it is a problem with the dependencies or the commands to build the package or even the commands in the `CMakeLists.txt` (which can be found in the [oligomap repository](https://github.com/zavolanlab/oligomap)). 
I would much appreciate if you could give me some advice or guidance on this issue. If you need any extra data, list it and I will provide it.

Error log:

```
16:06:46 BIOCONDA ERROR COMMAND FAILED (exited with 1): /opt/mambaforge/envs/bioconda/bin/conda mambabuild --override-channels --no-anaconda-upload -c conda-forge -c bioconda -c defaults -e /opt/mambaforge/envs/bioconda/conda_build_config.yaml -e /opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/bioconda_utils/bioconda_utils-conda_build_config.yaml recipes/oligomap/meta.yaml
16:06:46 BIOCONDA ERROR STDOUT+STDERR:
/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/conda_build/cli/main_build.py:390: UserWarning: RECIPE_PATH received is a file (recipes/oligomap/meta.yaml).
It should be a path to a folder.
Forcing conda-build to use the recipe file.
  warnings.warn(
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.21
WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.21
Updating build index: /opt/mambaforge/envs/bioconda/conda-bld

INFO:conda_build.variants:Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from /opt/mambaforge/envs/bioconda/conda_build_config.yaml
Adding in variants from internal_defaults
Adding in variants from /opt/mambaforge/envs/bioconda/conda_build_config.yaml
INFO:conda_build.variants:Adding in variants from /opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/bioconda_utils/bioconda_utils-conda_build_config.yaml
Adding in variants from /opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/bioconda_utils/bioconda_utils-conda_build_config.yaml
    entry = lookup_dict[get_url_from_channel(c)]
KeyError: 'https://conda.anaconda.org/conda-forge'

16:06:46 BIOCONDA ERROR BUILD FAILED recipes/oligomap
```

Many thanks!

**Comment by kbseah** [comment]
this was an issue affecting many PRs (#41526), should be fixed now, let's see if all the tests pass

**Comment by kbseah** [comment]
@deliaBlue, looks good to me. if ready for a review please ask BiocondaBot to add the label. thanks for your contribution!

**Comment by deliaBlue** [comment]
@bioconda-bot please add label

**Review by kbseah — APPROVED** [review]

**Comment by bgruening** [comment]
@deliaBlue you are already shipping the LICENSE files with your tarball. It should work without including the file in this repo.

**Comment by bgruening** [comment]
Thanks a lot for your contribution!

**Pull request merged**
