### PR TITLE
Update decifer to 2.1.0

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`decifer`](https://bioconda.github.io/recipes/decifer/README.html): **2.0.5** &rarr; **2.1.0**

[install with bioconda](http://bioconda.github.io/recipes/decifer/README.html) [Conda](https://anaconda.org/bioconda/decifer/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/decifer`](https://github.com//bioconda/bioconda-recipes/tree/bump/decifer/recipes/decifer) (click to view/edit other files)
Summary | DeCiFer simultaneously selects mutation multiplicities and clusters SNVs by their corresponding descendant cell fractions (DCF)
Home | [https://github.com/raphael-group/decifer](https://github.com/raphael-group/decifer)
Releases |[https://github.com/raphael-group/decifer/tags](https://github.com/raphael-group/decifer/tags)
Author | `@raphael-group`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Review by brian-arnold — APPROVED** [review]
@bioconda/core may I join the bioconda team so that I may approve my PRs? Thanks!

**Comment by brian-arnold** [comment]
@BiocondaBot merge

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@BiocondaBot please merge

**Comment by dpryan79** [comment]
@brian-arnold I've sent you an invite

**Pull request merged**
