### PR TITLE
Bump sqt to 0.7.0

### PR DESCRIPTION
**Pull request by marcelm**
* [x] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by bgruening** [comment]
Thanks a lot!

**Comment by marcelm** [comment]
Thanks for merging, but I could have done it as well! Some of the fun in contributing comes from clicking the 'merge' button ...

**Comment by bgruening** [comment]
Upps, sorry.

**Comment by marcelm** [comment]
No worries.

**Pull request merged**
