### PR TITLE
File does not exists if there is no package in a PR

### PR DESCRIPTION
**Pull request by bgruening**
* [x] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [x] This PR does something else (explain below).

### CODE REVIEW

**Comment by bgruening** [comment]
@johanneskoester here we go. If there is no package and bioconda-utils was not running there is no such file.

**Comment by bgruening** [comment]
@daler @johanneskoester I see this now: https://travis-ci.org/bioconda/bioconda-recipes/jobs/175473800#L494

The wired thing is that all tests end with SUCCESS, but the summary has an error. I will study this and try a little bit more before reverting. Let me know if you have ideas.

**Comment by johanneskoester** [comment]
And it says it is filtering 100% but still wants to build recipes...

**Comment by bgruening** [comment]
@johanneskoester it's working now!!!!
However, it does take longer than expected. I would argue that it is worth it but we should watch it over the next days and maybe revert the push.
The testing with busybox is also working now.

**Comment by johanneskoester** [comment]
Great. Is the upload speed the problem?

**Comment by bgruening** [comment]
I assume it is download of all R dependencies, but actually after seeing some PR I think it is actually generating the website ... haven't noticed this yet, but this seems to take a fair amount of time.

**Comment by johanneskoester** [comment]
Indeed, I also noticed that recently. It does a lot of unnecessary stuff, since most packages don't change...

**Pull request merged**
