### PR TITLE
Update revbayes to v1.1.0

### PR DESCRIPTION
**Pull request by peterjc**
Note that while the current recipe pointed to git tag v1.0.13, ~~that is no longer in the upstream repository.~~ that is in the archive repository https://github.com/revbayes/revbayes.archive

While there are references to v1.0.14 in the git history, again this has no tag, so identifying the exact commit is non trivial.

Note also that the v1.1 tag was premature and the code at that point still reported version v1.0.14, which was rectified a few days later with the v1.1.0 tag which is used here.

If this works, we can next do v1.1.1 (which had changes to the random number seed behaviour), v1.2.0 and v1.2.1 (which all have git tags).

See https://github.com/revbayes/revbayes/blob/master/NEWS.md

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by peterjc** [comment]
Hmm, failing here:

```
2022-12-22T10:22:53.7771724Z 10:22:53 BIOCONDA INFO (OUT) Generating version numbers in GitVersion.cpp
2022-12-22T10:22:53.7884361Z 10:22:53 BIOCONDA INFO (OUT) fatal: not a git repository (or any of the parent directories): .git
2022-12-22T10:22:53.7922777Z 10:22:53 BIOCONDA INFO (OUT) fatal: not a git repository (or any of the parent directories): .git
```

This is in the cmake based build script, which calls https://github.com/revbayes/revbayes/blob/master/projects/cmake/generate_version_number.sh or previously https://github.com/revbayes/revbayes/blob/master/projects/cmake/generate_version_number.sh

**Comment by peterjc** [comment]
The git version thing may not be critical, next the build script does this:

```
# MPI version
./regenerate.sh -mpi true

cd build

# If cmake finds a boost version compiled with cmake, it always links to it unless both
# Boost_NO_SYSTEM_PATHS=ON and Boost_NO_BOOST_CMAKE=ON (probably a bug in cmake)
cmake -DCMAKE_PREFIX_PATH=$PREFIX \
	-DBOOST_ROOT=$PREFIX \
	-DBoost_NO_SYSTEM_PATHS=ON \
	-DBoost_NO_BOOST_CMAKE=ON \
	.

make

cd ..
```

That seems to fail, and the ``.`` path warning is odd:

```
2022-12-22T10:22:53.7987681Z 10:22:53 BIOCONDA INFO (OUT) Making build directory 'build'
2022-12-22T10:22:53.7993269Z 10:22:53 BIOCONDA INFO (OUT) Generating src/generated_include_dirs.cmake
2022-12-22T10:22:53.8073876Z 10:22:53 BIOCONDA INFO (OUT) Generating src/libs/CMakeLists.txt
2022-12-22T10:22:53.8112151Z 10:22:53 BIOCONDA INFO (OUT) Generating src/core/CMakeLists.txt
2022-12-22T10:22:53.8183631Z 10:22:53 BIOCONDA INFO (OUT) Generating src/revlanguage/CMakeLists.txt
2022-12-22T10:22:53.8234933Z 10:22:53 BIOCONDA INFO (OUT) Generating src/help2yml/CMakeLists.txt
2022-12-22T10:22:53.8271631Z 10:22:53 BIOCONDA INFO (OUT) Generating src/cmd/CMakeLists.txt
2022-12-22T10:22:53.8617755Z 10:22:53 BIOCONDA INFO (OUT) CMake Warning:
2022-12-22T10:22:53.8618128Z 10:22:53 BIOCONDA INFO (OUT)   Ignoring extra path from command line:
2022-12-22T10:22:53.8622692Z 10:22:53 BIOCONDA INFO (OUT) 
2022-12-22T10:22:53.8622959Z 10:22:53 BIOCONDA INFO (OUT)    "."
2022-12-22T10:22:53.8630998Z 10:22:53 BIOCONDA INFO (OUT) 
2022-12-22T10:22:53.8631268Z 10:22:53 BIOCONDA INFO (OUT) 
2022-12-22T10:22:53.8633862Z 10:22:53 BIOCONDA INFO (OUT) CMake Error: The source directory "/opt/conda/conda-bld/revbayes_1671704396636/work/projects/cmake/build" does not appear to contain CMakeLists.txt.
2022-12-22T10:22:53.8636865Z 10:22:53 BIOCONDA INFO (OUT) Specify --help for usage, or press the help button on the CMake GUI.
```

**Comment by peterjc** [comment]
Any thoughts @brisk022 on what needs changing since your original revbayes recipe?

**Comment by kdm9** [comment]
@peterjc maybe try the following:
```
commit 2a2bc7d039854722045d0dc11701d1955d8ea646 (HEAD -> revbayes_1_1_0)
Author: Dr. K. D. Murray <1560490+kdm9@users.noreply.github.com>
Date:   Tue Dec 27 20:50:53 2022 +0000

    revbayes: cmake expects src dir, not ./build/ ??

diff --git a/recipes/revbayes/build.sh b/recipes/revbayes/build.sh
index 7f0287067d..5e1873a282 100644
--- a/recipes/revbayes/build.sh
+++ b/recipes/revbayes/build.sh
@@ -20,7 +20,7 @@ cmake -DCMAKE_PREFIX_PATH=$PREFIX \
        -DBOOST_ROOT=$PREFIX \
        -DBoost_NO_SYSTEM_PATHS=ON \
        -DBoost_NO_BOOST_CMAKE=ON \
-       .
+       ..
 
 make
 
@@ -43,7 +43,7 @@ cmake -DCMAKE_PREFIX_PATH=$PREFIX \
        -DBOOST_ROOT=$PREFIX \
        -DBoost_NO_SYSTEM_PATHS=ON \
        -DBoost_NO_BOOST_CMAKE=ON \
-       .
+       ..
 
 make

```

(and yes, I tried to push this before realising the branch is in your fork, not the upstream repo. sorry if you got any strange mail/pr there!)

**Comment by peterjc** [comment]
Worth a try, thanks.

**Comment by peterjc** [comment]
Same cmake message:

```
19:29:49 BIOCONDA INFO (OUT) Making build directory 'build'
19:29:49 BIOCONDA INFO (OUT) Generating src/generated_include_dirs.cmake
19:29:49 BIOCONDA INFO (OUT) Generating src/libs/CMakeLists.txt
19:29:49 BIOCONDA INFO (OUT) Generating src/core/CMakeLists.txt
19:29:49 BIOCONDA INFO (OUT) Generating src/revlanguage/CMakeLists.txt
19:29:49 BIOCONDA INFO (OUT) Generating src/help2yml/CMakeLists.txt
19:29:49 BIOCONDA INFO (OUT) Generating src/cmd/CMakeLists.txt
19:29:49 BIOCONDA INFO (OUT) CMake Warning:
19:29:49 BIOCONDA INFO (OUT)   Ignoring extra path from command line:
19:29:49 BIOCONDA INFO (OUT) 
19:29:49 BIOCONDA INFO (OUT)    ".."
19:29:49 BIOCONDA INFO (OUT) 
19:29:49 BIOCONDA INFO (OUT) 
19:29:49 BIOCONDA INFO (OUT) CMake Error: The source directory "/opt/conda/conda-bld/revbayes_1672255542268/work/projects/cmake" does not appear to contain CMakeLists.txt.
19:29:49 BIOCONDA INFO (OUT) Specify --help for usage, or press the help button on the CMake GUI.
```

I wonder if ``regenerate.sh`` is not making a top level ``CMakeLists.txt`` and should be?

**Comment by mencian** [comment]
Closing in favor of #52069; `revbayes` has been updated to `v1.2.4`.

**Pull request closed without merging**
