### PR TITLE
t-coffee-12.00.7fb08c2 (build 1)

### PR DESCRIPTION
**Pull request by pditommaso**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by SchwarzMarek** [comment]
Hi, 
may I ask why to fix viennarna to 2.1.9 ?

Also tmalign should now be in bioconda, and kalign was merged today and should be in bioconda after successful nightly build. So you can add them as deps.

**Comment by pditommaso** [comment]
> may I ask why to fix viennarna to 2.1.9 ?

because it's the version used by tcoffeee (see [here](https://github.com/cbcrg/tcoffee/blob/f5a3274df02cdbac8b6cd50bcb03d872a56e4a53/lib/data_headers/tclinkdb.txt#L318))

> Also tmalign should now be in bioconda, and kalign was merged today and should be in bioconda after successful nightly build. So you can add them as deps.


Excellent! If you add tmaling remove the one compiled in the [build script](https://github.com/bioconda/bioconda-recipes/blob/05597890ee1948cac3a7dd5f59002e816ea077f6/recipes/t-coffee/build.sh#L20-L21) and the deps on the fortran compiler.

**Comment by SchwarzMarek** [comment]
Well I don't exactly know how the t-coffee access RNAplfold, but there are at least 2 bug-fixes in RNAplfold (2.2.9 and 2.3.2). And the behavior seems to be consistent up to 2.3.4 (which introduced colored output). [here](https://www.tbi.univie.ac.at/RNA/changelog.html#v232)

**Comment by pditommaso** [comment]
> Well I don't exactly know how the t-coffee access RNAplfold, but there are at least 2 bug-fixes in RNAplfold (2.2.9 and 2.3.2)

Yes, but this recipe should use the same package versions used in the upstream tcoffee build for the sake of reproducibility.

**Comment by druvus** [comment]
@pditommaso I restarted testing after the rebuilding of problematic dependencies and it seems to work now.

**Comment by pditommaso** [comment]
Not sure to understand why linting is failing

```
From ssh://github.com/bioconda/bioconda-recipes
 * [new branch]          master     -> __upstream__rZ0o3h9oMI/master
Your bioconda-recipes CI configuration is out of date.
Please update it to the latest version of the upstream master branch.
You can do this, e.g., by running:
  git fetch https://github.com/bioconda/bioconda-recipes.git master
  git merge FETCH_HEAD
Exited with code 1
```

**Comment by druvus** [comment]
A modification of circleci config got merged in #12662. So you need to merge master into your branch to restart the testing.

**Comment by pditommaso** [comment]
Oops, it should better now.

**Comment by pditommaso** [comment]
No way, now it's failing the pre-link 

```
Command '['bash', '-x', '/opt/conda/pkgs/t-coffee-12.00.7fb08c2-h26a2512_1/bin/.t-coffee-pre-link.sh']' returned non-zero exit status 1.
```

**Comment by pditommaso** [comment]
Nice, all green! Please merge at your convenience.

**Pull request merged**
