### PR TITLE
Cesm bugfix lapack

### PR DESCRIPTION
**Pull request by annefou**
Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it. Note that if you are not already a member of the bioconda project (meaning that you can't add this label), please ping `@bioconda/core` so that your PR can be reviewed and merged (please note if you'd like to be added to the bioconda project). Please see https://github.com/bioconda/bioconda-recipes/issues/15332 for more details.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [ ] This PR adds a new recipe.
* [ ] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by annefou** [comment]
I don't know if it is the best way to solve this problem but the current cesm recipe does not work when running CESM simulation because of lapack. If I install lapack=3.6.0 it fixes this problem (maybe because it is taken from bioconda?).

**Comment by bgruening** [comment]
@annefou lapack should really come from conda-forge. Please make sure your channel order is correct.

**Comment by annefou** [comment]
I haven't changed the channel order.  The change suggested allows cesm to work out of the box (without having to re-install lapack 3.6.0). I agree that there is something weird; it had nothing to do with the lapack version as CESM works well with newer versions of lapack.
If I recompiled lapack (latest 3.8.0) manually (after installing cesm with conda) and CESM also works too (I changed LD_LIBRARY_PATH to use the new lapack libraries before creating a new CESM simulation).

Could it be related to the Fortran compiler version? 

Any suggestion?

**Comment by bgruening** [comment]
@bioconda-bot recheck

**Comment by dpryan79** [comment]
@bgruening Any thoughts on the mkl change?

**Comment by annefou** [comment]
Just to let you know that I have tested it and it works well.

**Comment by bgruening** [comment]
Jupp!

**Comment by dpryan79** [comment]
@bioconda-bot merge

**Pull request merged**
