### PR TITLE
 Add python-bioformats from pypi

### PR DESCRIPTION
**Pull request by drpatelh**
* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [X] This PR adds a new recipe.
* [X] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

Added `python-bioformats` package required by CellProfiler. Recipe file was built using:
```
conda skeleton pypi python-bioformats
```

### CODE REVIEW

**Comment by drpatelh** [comment]
Added in `setuptools_scm` because build was failing, and `java-jdk` because tests were failing.

**Comment by drpatelh** [comment]
@bioconda/core 

I generated the recipe using `conda skeleton` and I fixed this error:
```
RuntimeError: Setuptools downloading is disabled in conda build. Be sure to add all dependencies in the meta.yaml  url=https://pypi.org/simple/setuptools_scm/
```
by um adding `setuptools_scm` to the recipe.

I then started getting `java` errors where the tests were failing because java was required. I added `java-jdk` but realised thats now been deprecated so replaced it with `openjdk`. The build is now failing with:

```
ImportError: libjvm.so: cannot open shared object file: No such file or directory
``` 

Any ideas?

**Comment by dpryan79** [comment]
It looks like conda's javabridge recipe is old enough that it wasn't built against a particular version of java, but instead uses various tricks to try and find any installed version. Those tricks seem to not always work, such as in this case. A better solution would be to put javabridge in conda-forge and have it build against a given range of openjdk versions (or at least 8.0).

**Comment by drpatelh** [comment]
@dpryan79 It looks like `anaconda/ javabridge` contains the latest release i.e. `1.0.14`. This itself contains a patch called `0001-Dynamically-load-libjvm.so-before-importing-_javabri.patch`, and the recipe doesnt explicitly `build` or `run` `openjdk` as you suggested.
https://github.com/LeeKamentsky/python-javabridge

Installing CellProfiler will be the bain of my existence...

**Comment by drpatelh** [comment]
Adding `javabridge` to `conda-forge` is currently failing on OSX without an obvious solution.
https://github.com/conda-forge/staged-recipes/pull/7701

I am closing this PR with the hope of revisiting in the near future.

**Pull request closed without merging**
