### PR TITLE
sumaclust breaks nightly builds

### PR DESCRIPTION
**Pull request by bgruening**
* [ ] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [ ] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by bgruening** [comment]
ok, lets see what going on here and on the nightly builds

ping @dpryan79

**Comment by dpryan79** [comment]
@bgruening What was the trick for clang with -fopenmp? Was it adding `llvm-openmp` on OSX?

**Comment by bgruening** [comment]
Yes as run- and host-dependency afaik.

**Comment by bgruening** [comment]
From the Makefile:

```

########
#
# sumaclust compilation
#
########

# executable compilation and link

ifeq ($(CC),gcc)
        LFLAGS = -fopenmp 
else
        LFLAGS = 
endif
```

**Comment by dpryan79** [comment]
I look forward to being able to update the docker container. That `gcc` and such are still in the current one is probably going to cause some headaches.

**Comment by dpryan79** [comment]
Success, we'll see what nightly does tonight (granted, it needs 10 hours to go through all of the packages, so...).

**Pull request merged**
