### PR TITLE
[WIP] dependencies for SuperLearner

### PR DESCRIPTION
**Pull request by daler**
* [ ] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by daler** [comment]
It probably does. I have these and another 18 deps. I was originally thinking it would take a while to push everything through conda-forge.

**Comment by daler** [comment]
Since I spent the time on the bioconda versions, I just pushed them to verify they build on our system, then will close this and start the conda-forge ones.

**Comment by bgruening** [comment]
I would estimate approximately a week. I have used this script: https://github.com/bgruening/conda_r_skeleton_helper to create a lot of r-packages and it worked quite well. One PR is enough for all of those, but windows can be an issue. They want at least that we try to compile them for windows as well and comment into the recipe if we skip it.

**Comment by daler** [comment]
Nice, thanks for the script! Doesn't seem to be anything too crazy for windows in this batch. A bunch need compiling, but none with additional external libs. I was hoping for collaborators to use these this week, but we have workarounds. This will be a good exercise for me for working with conda-forge and will avoid duplication and migration in the future.

**Pull request closed without merging**
