### PR TITLE
Update fgbio to 2.1.0

### PR DESCRIPTION
**Pull request by tfenne**
Not sure why the auto-updater didn't catch this one, so submitting manually.  Updates fgbio and fgbio-minimal to 2.1.0 released late last week.

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

### CODE REVIEW

**Comment by tfenne** [comment]
@BiocondaBot please add label

**Review by linzhi2013 — APPROVED** [review]

**Comment by linzhi2013** [comment]
Hi @tfenne , I have got the same problem, the automatic update method does not work. Could you please help me to review my recipe (https://github.com/bioconda/bioconda-recipes/pull/38676) and merge the commit? thanks!

**Comment by tfenne** [comment]
@BiocondaBot please fetch artifacts

**Comment by tfenne** [comment]
@BiocondaBot please merge

**Pull request merged**
