### PR TITLE
Add Bioconductor package flowClust

### PR DESCRIPTION
**Pull request by jdblischak**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

https://www.bioconductor.org/packages/release/bioc/html/flowClust.html

Notes:
* I created the recipe using bioconductor-skeleton
* I added Make as a dependency because it was listed in SystemRequirements. I added it to both build and run requirements since I'm not sure when it is needed.
* I added GSL since this is mentioned in the package description, and pinned it according to the [relevant FAQ](https://bioconda.github.io/faqs.html#how-are-environmental-variables-defined-and-used)
* I tested it locally on a linux-64 machine with `./simulate-travis.py --disable-docker --packages bioconductor-flowclust`

### CODE REVIEW

**Comment by jdblischak** [comment]
Strange. The [build failed on osx](https://travis-ci.org/bioconda/bioconda-recipes/jobs/309216415#L319):

```
23:54:09 BIOCONDA INFO BUILD START recipes/bioconductor-flowclust, env: CONDA_ALLOW_SOFTLINKS=false;CONDA_BOOST=1.64;CONDA_BZIP2=1.0;CONDA_GMP=5.1;CONDA_GSL=1.16;CONDA_HDF5=1.8.17;CONDA_HTSLIB=1.6;CONDA_NCURSES=5.9;CONDA_NPY=112;CONDA_PERL=5.22.0;CONDA_PY=27;CONDA_R=3.4.1;CONDA_ROOT=/anaconda;CONDA_XZ=5.2;CONDA_ZLIB=1.2.8;LANG=en_US.UTF-8;LC_ALL=en_US.UTF-8;MACOSX_DEPLOYMENT_TARGET=10.9;PATH=/anaconda/bin:/Users/travis/.rvm/gems/ruby-2.0.0-p648/bin:/Users/travis/.rvm/gems/ruby-2.0.0-p648@global/bin:/Users/travis/.rvm/rubies/ruby-2.0.0-p648/bin:/Users/travis/.rvm/bin:/Users/travis/bin:/Users/travis/.local/bin:/Users/travis/.nvm/versions/node/v6.0.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin

....23:57:45 BIOCONDA ERROR COMMAND FAILED: /anaconda/bin/conda build --no-anaconda-upload --channel bioconda --channel conda-forge --channel defaults recipes/bioconductor-flowclust/meta.yaml

23:57:45 BIOCONDA ERROR STDOUT+STDERR:
```

I built the package on my local osx-64 machine, and it passed:

```
$ ./simulate-travis.py --disable-docker --packages bioconductor-flowclust/
Using config file /Users/jdblischak/.config/bioconda/conf.yml, which has the following contents:
{'CONDARC': '/Users/jdblischak/miniconda-bioconda/condarc', 'CONDA_ROOT': '/Users/jdblischak/miniconda-bioconda'}
+ bioconda-utils lint recipes config.yml --git-range master HEAD
19:12:14 BIOCONDA INFO Recipes newly unblacklisted:

19:12:14 BIOCONDA INFO Recipes to consider according to git: 
recipes/bioconductor-flowclust
 recipes/bioconductor-flowclust
19:12:14 BIOCONDA INFO Recipes to lint:
recipes/bioconductor-flowclust
+ set +x
+ bioconda-utils build recipes config.yml --loglevel=info --packages bioconductor-flowclust/ --git-range master HEAD
19:12:15 BIOCONDA INFO Recipes newly unblacklisted:

19:12:15 BIOCONDA INFO Recipes modified according to git: bioconductor-flowclust
19:12:15 BIOCONDA INFO blacklist: blasr_libcpp, blast/2.2.21, cap-mirseq, cgat-scripts-devel, clever-toolkit, denovogear, detonate, frc, metaprob, mgkit, mothur/1.36.1, perl-font-afm, quast, r-histonehmm, r-pscbs/0.61.0, r-spp, rsem, transcomb
19:12:15 BIOCONDA INFO Filtering recipes

Filtering 1 of 1 (100.0%) recipes/bioconductor-flowclust
19:12:17 BIOCONDA INFO Building and testing 1 recipes in total
19:12:17 BIOCONDA INFO Recipes to build: 
bioconductor-flowclust
19:12:17 BIOCONDA INFO Building and testing subdag 1 of 1 (1 recipes)
19:12:17 BIOCONDA INFO BUILD START recipes/bioconductor-flowclust, env: CONDA_ALLOW_SOFTLINKS=false;CONDA_BOOST=1.64;CONDA_BZIP2=1.0;CONDA_GMP=5.1;CONDA_GSL=1.16;CONDA_HDF5=1.8.17;CONDA_HTSLIB=1.6;CONDA_NCURSES=5.9;CONDA_NPY=112;CONDA_PERL=5.22.0;CONDA_PY=27;CONDA_R=3.4.1;CONDA_ROOT=/Users/jdblischak/miniconda-bioconda;CONDA_XZ=5.2;CONDA_ZLIB=1.2.8;LANG=en_US.UTF-8;MACOSX_DEPLOYMENT_TARGET=10.9;PATH=/anaconda/bin:/Users/jdblischak/miniconda-bioconda/bin:/Users/jdblischak/anaconda3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
......
19:18:17 BIOCONDA INFO BUILD SUCCESS /Users/jdblischak/miniconda-bioconda/conda-bld/osx-64/bioconductor-flowclust-3.16.0-gsl1.16_0.tar.bz2, CONDA_ALLOW_SOFTLINKS=false;CONDA_BOOST=1.64;CONDA_BZIP2=1.0;CONDA_GMP=5.1;CONDA_GSL=1.16;CONDA_HDF5=1.8.17;CONDA_HTSLIB=1.6;CONDA_NCURSES=5.9;CONDA_NPY=112;CONDA_PERL=5.22.0;CONDA_PY=27;CONDA_R=3.4.1;CONDA_ROOT=/Users/jdblischak/miniconda-bioconda;CONDA_XZ=5.2;CONDA_ZLIB=1.2.8;LANG=en_US.UTF-8;MACOSX_DEPLOYMENT_TARGET=10.9;PATH=/anaconda/bin:/Users/jdblischak/miniconda-bioconda/bin:/Users/jdblischak/anaconda3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
19:18:19 BIOCONDA INFO BUILD SUMMARY: successfully built 1 of 1 recipes
+ set +x
```

I restarted the job in case it was a sporadic error.

**Comment by jdblischak** [comment]
Failed again, The error is the same as described in https://github.com/bioconda/bioconda-recipes/issues/476. I'd appreciate any advice.

**Comment by jdblischak** [comment]
I just rebased against master and did a force push. If this still fails, maybe the tricks in #3670 will help.

**Comment by dpryan79** [comment]
@jdblischak Do you still need this PR? bioconductor-flowclust is part of bioconda these days.

**Comment by jdblischak** [comment]
> Do you still need this PR? bioconductor-flowclust is part of bioconda these days.

@dpryan79 That's great! I installed it and was able to successfully run the [example script](https://www.bioconductor.org/packages/release/bioc/vignettes/flowClust/inst/doc/flowClust.R).

I noticed that the merged recipe does not specify GSL:

https://github.com/bioconda/bioconda-recipes/blob/master/recipes/bioconductor-flowclust/meta.yaml

I assume that is not an issue since GSL is a dependency of r-base and it is pinned in conda-forge

https://github.com/conda-forge/r-base-feedstock/blob/9934a07a64d4115c9e2bbc50129c4b6eb6bd0bb6/recipe/meta.yaml#L125
https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/b1a3bc90dc2a044e15330a7324e936524421a495/recipe/conda_build_config.yaml#L388

**Pull request closed without merging**
