### PR TITLE
Update rmblast to 2.14.1

### PR DESCRIPTION
**Pull request by mencian**
Describe your pull request here

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

### General instructions

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

### Instructions for avoiding API, ABI, and CLI breakage issues
Conda is able to record and lock (a.k.a. pin) dependency versions used at build time of other recipes.
This way, one can avoid that expectations of a downstream recipe with regards to API, ABI, or CLI are violated by later changes in the recipe.
If not already present in the meta.yaml, make sure to specify `run_exports` (see [here](https://bioconda.github.io/contributor/linting.html#missing-run-exports) for the rationale and comprehensive explanation).
Add a `run_exports` section like this:

```yaml
build:
  run_exports:
    - ...

```

with `...` being one of:

| Case                             | run_exports statement                                               |
| -------------------------------- | ------------------------------------------------------------------- |
| semantic versioning              | `{{ pin_subpackage("myrecipe", max_pin="x") }}`     |
| semantic versioning (0.x.x)      | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}`   |
| known breakage in minor versions | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| known breakage in patch versions | `{{ pin_subpackage("myrecipe", max_pin="x.x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| calendar versioning              | `{{ pin_subpackage("myrecipe", max_pin=None) }}`    |

while replacing `"myrecipe"` with either `name` if a `name|lower` variable is defined in your recipe or with the lowercase name of the package in quotes.

### Bot commands for PR management

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

Note that the <code>@BiocondaBot please merge</code> command is now depreciated. Please just squash and merge instead.

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by mencian** [comment]
@BiocondaBot please add label

**Comment by oushujun** [comment]
Hello Joshua @mencian 

The below conflict has been there and not fixed. To avoid such conflict, the blast version needs to be pinned at 2.10.1. Is that something you can do to fix it from the conda recipe?

Thanks!
Shujun


Preparing transaction: done
Verifying transaction: \ 
SafetyError: The package for repeatmasker located at /home/shujun/bin/miniconda3/pkgs/repeatmasker-4.1.5-pl5321hdfd78af_1
appears to be corrupted. The path 'share/RepeatMasker/Libraries/Dfam.h5'
has an incorrect size.
  reported size: 68 bytes
  actual size: 5861387976 bytes

ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.14.1-pl5321h6f7f691_0, bioconda/linux-64::rmblast-2.14.1-h4565617_0
  path: 'bin/blast_formatter'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.14.1-pl5321h6f7f691_0, bioconda/linux-64::rmblast-2.14.1-h4565617_0
  path: 'bin/blastdb_aliastool'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.14.1-pl5321h6f7f691_0, bioconda/linux-64::rmblast-2.14.1-h4565617_0
  path: 'bin/blastdbcheck'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.14.1-pl5321h6f7f691_0, bioconda/linux-64::rmblast-2.14.1-h4565617_0
  path: 'bin/blastdbcmd'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.14.1-pl5321h6f7f691_0, bioconda/linux-64::rmblast-2.14.1-h4565617_0
  path: 'bin/blastn'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.14.1-pl5321h6f7f691_0, bioconda/linux-64::rmblast-2.14.1-h4565617_0
  path: 'bin/blastp'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.14.1-pl5321h6f7f691_0, bioconda/linux-64::rmblast-2.14.1-h4565617_0
  path: 'bin/blastx'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.14.1-pl5321h6f7f691_0, bioconda/linux-64::rmblast-2.14.1-h4565617_0
  path: 'bin/cleanup-blastdb-volumes.py'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.14.1-pl5321h6f7f691_0, bioconda/linux-64::rmblast-2.14.1-h4565617_0
  path: 'bin/convert2blastmask'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.14.1-pl5321h6f7f691_0, bioconda/linux-64::rmblast-2.14.1-h4565617_0
  path: 'bin/datatool'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.14.1-pl5321h6f7f691_0, bioconda/linux-64::rmblast-2.14.1-h4565617_0
  path: 'bin/deltablast'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.14.1-pl5321h6f7f691_0, bioconda/linux-64::rmblast-2.14.1-h4565617_0
  path: 'bin/dustmasker'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.14.1-pl5321h6f7f691_0, bioconda/linux-64::rmblast-2.14.1-h4565617_0
  path: 'bin/get_species_taxids.sh'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.14.1-pl5321h6f7f691_0, bioconda/linux-64::rmblast-2.14.1-h4565617_0
  path: 'bin/get_species_taxids.sh.bak'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.14.1-pl5321h6f7f691_0, bioconda/linux-64::rmblast-2.14.1-h4565617_0
  path: 'bin/legacy_blast.pl'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.14.1-pl5321h6f7f691_0, bioconda/linux-64::rmblast-2.14.1-h4565617_0
  path: 'bin/makeblastdb'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.14.1-pl5321h6f7f691_0, bioconda/linux-64::rmblast-2.14.1-h4565617_0
  path: 'bin/makembindex'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.14.1-pl5321h6f7f691_0, bioconda/linux-64::rmblast-2.14.1-h4565617_0
  path: 'bin/makeprofiledb'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.14.1-pl5321h6f7f691_0, bioconda/linux-64::rmblast-2.14.1-h4565617_0
  path: 'bin/project_tree_builder'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.14.1-pl5321h6f7f691_0, bioconda/linux-64::rmblast-2.14.1-h4565617_0
  path: 'bin/psiblast'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.14.1-pl5321h6f7f691_0, bioconda/linux-64::rmblast-2.14.1-h4565617_0
  path: 'bin/rpsblast'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.14.1-pl5321h6f7f691_0, bioconda/linux-64::rmblast-2.14.1-h4565617_0
  path: 'bin/rpstblastn'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.14.1-pl5321h6f7f691_0, bioconda/linux-64::rmblast-2.14.1-h4565617_0
  path: 'bin/run_with_lock'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.14.1-pl5321h6f7f691_0, bioconda/linux-64::rmblast-2.14.1-h4565617_0
  path: 'bin/segmasker'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.14.1-pl5321h6f7f691_0, bioconda/linux-64::rmblast-2.14.1-h4565617_0
  path: 'bin/tblastn'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.14.1-pl5321h6f7f691_0, bioconda/linux-64::rmblast-2.14.1-h4565617_0
  path: 'bin/tblastx'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.14.1-pl5321h6f7f691_0, bioconda/linux-64::rmblast-2.14.1-h4565617_0
  path: 'bin/test_pcre'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.14.1-pl5321h6f7f691_0, bioconda/linux-64::rmblast-2.14.1-h4565617_0
  path: 'bin/update_blastdb.pl'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.14.1-pl5321h6f7f691_0, bioconda/linux-64::rmblast-2.14.1-h4565617_0
  path: 'bin/update_blastdb.pl.bak'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.14.1-pl5321h6f7f691_0, bioconda/linux-64::rmblast-2.14.1-h4565617_0
  path: 'bin/windowmasker'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.14.1-pl5321h6f7f691_0, bioconda/linux-64::rmblast-2.14.1-h4565617_0
  path: 'bin/windowmasker_2.2.22_adapter.py'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.14.1-pl5321h6f7f691_0, bioconda/linux-64::rmblast-2.14.1-h4565617_0
  path: 'lib/ncbi-blast+/libblast_app_util-static.a'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.14.1-pl5321h6f7f691_0, bioconda/linux-64::rmblast-2.14.1-h4565617_0
  path: 'lib/ncbi-blast+/libblast_app_util.a'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.14.1-pl5321h6f7f691_0, bioconda/linux-64::rmblast-2.14.1-h4565617_0
  path: 'lib/ncbi-blast+/libdbapi_driver-static.a'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.14.1-pl5321h6f7f691_0, bioconda/linux-64::rmblast-2.14.1-h4565617_0
  path: 'lib/ncbi-blast+/libdbapi_driver.a'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.14.1-pl5321h6f7f691_0, bioconda/linux-64::rmblast-2.14.1-h4565617_0
  path: 'lib/ncbi-blast+/libncbi_xloader_genbank-static.a'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.14.1-pl5321h6f7f691_0, bioconda/linux-64::rmblast-2.14.1-h4565617_0
  path: 'lib/ncbi-blast+/libncbi_xloader_genbank.a'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.14.1-pl5321h6f7f691_0, bioconda/linux-64::rmblast-2.14.1-h4565617_0
  path: 'lib/ncbi-blast+/libncbi_xreader-static.a'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.14.1-pl5321h6f7f691_0, bioconda/linux-64::rmblast-2.14.1-h4565617_0
  path: 'lib/ncbi-blast+/libncbi_xreader.a'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.14.1-pl5321h6f7f691_0, bioconda/linux-64::rmblast-2.14.1-h4565617_0
  path: 'lib/ncbi-blast+/libncbi_xreader_cache-static.a'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.14.1-pl5321h6f7f691_0, bioconda/linux-64::rmblast-2.14.1-h4565617_0
  path: 'lib/ncbi-blast+/libncbi_xreader_cache.a'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.14.1-pl5321h6f7f691_0, bioconda/linux-64::rmblast-2.14.1-h4565617_0
  path: 'lib/ncbi-blast+/libncbi_xreader_id1-static.a'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.14.1-pl5321h6f7f691_0, bioconda/linux-64::rmblast-2.14.1-h4565617_0
  path: 'lib/ncbi-blast+/libncbi_xreader_id1.a'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.14.1-pl5321h6f7f691_0, bioconda/linux-64::rmblast-2.14.1-h4565617_0
  path: 'lib/ncbi-blast+/libncbi_xreader_id2-static.a'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.14.1-pl5321h6f7f691_0, bioconda/linux-64::rmblast-2.14.1-h4565617_0
  path: 'lib/ncbi-blast+/libncbi_xreader_id2.a'

**Comment by oushujun** [comment]
@mencian Is the above issue fixable on this end? Otherwise, we will need to pin `blast` to different versions to avoid such conflict.

**Comment by mencian** [comment]
@oushujun Are the `ClobberError`s preventing you from solving the environment? If so, please pin `blast` if you feel it is necessary. I also don't see an obvious way to resolve the `ClobberError`s and I'll need more time to look into it.

**Comment by oushujun** [comment]
If such error occurs while env solving, RepeatMasker won’t
function properly. Would it possible set the recipe to store it in a
different directory? Seems like both attempts to write in the same
directory and cause error

Shujun

**Comment by mencian** [comment]
> Would it possible set the recipe to store it in a different directory? Seems like both attempts to write in the same directory and cause error

`rmblast` is essentially the same as the `blast` package but with a hefty patch applied so these `CloberError`s are not surprising; do you absolutely need both `rmblast` and `blast` as run dependencies?

**Comment by oushujun** [comment]
RepeatMasker needs rmblast, and I used blast in the pipeline.

Shujun

**Pull request merged**
