### PR TITLE
Upgrade HTSLib suite

### PR DESCRIPTION
**Pull request by kyleabeauchamp**
* [ ] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [ ] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by kyleabeauchamp** [comment]
The latest versions of HTSLib support a new compression backend (libdeflate) that offers improved performance.  If these benchmarks prove to be true, does anyone here have any objections to adding lib-deflate to the build for these libraries (and pysam, eventually)?

**Comment by kyleabeauchamp** [comment]
PS: I will do the lib-deflate in a separate PR (with an incremented build number), just wanted to chat about it first.  I should probably open a separate issue.

**Comment by kyleabeauchamp** [comment]
FYI I haven't updated the HTSLIB environment matrix yet

**Comment by epruesse** [comment]
Is there any reason not to enable libdeflate right away? Why did they chose to just make it a compile time flag, rather than the new default?

Is the htslib so backwards compatible, or would we need to recompile?

**Comment by kyleabeauchamp** [comment]
So for me, I want to make sure that downstream applications are not impacted.  I also want to wait until pysam supports libdeflate as well.

**Comment by dpryan79** [comment]
Won't bumping the build number for libdeflate support obviate the need for a non-libdeflate build? Since the API is unchanged, I presume pysam will be able to use libdeflate by simply compiling against a libdeflate-enabled htslib.

**Comment by kyleabeauchamp** [comment]
FWIW, I have preliminary evidence (below) that libdeflate-based gzip is faster for both compression and decompression, so I think this might be worthwhile:

```
$ time gzip -c ~/dat/genomes/hg19/bwa_ref/hg19.bwa_mem.fa > out.fa.gz

real	8m17.887s
user	8m12.304s
sys	0m3.715s
$ time ./gzip -c ~/dat/genomes/hg19/bwa_ref/hg19.bwa_mem.fa > out2.fa.gz

real	1m38.979s
user	1m32.337s
sys	0m3.826s

$ time gunzip -c out2.fa.gz  > /dev/null 

real	0m8.089s
user	0m7.719s
sys	0m0.338s
$ time ./gunzip -c out2.fa.gz  > /dev/null 

real	0m6.580s
user	0m5.096s
sys	0m1.452s
```

**Comment by dpryan79** [comment]
This seems to jive with what was reported on the htslib repository :)

**Comment by epruesse** [comment]
Wow. That's quite the difference. Who would have thought that zlib has that much room for improvement. How does the compression ratio hold up?

**Pull request merged**
