### PR TITLE
viennarna bump 2.4.14 + enable openmp for osx

### PR DESCRIPTION
**Pull request by martin-raden**
Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it. Note that if you are not already a member of the bioconda project (meaning that you can't add this label), please ping `@bioconda/core` so that your PR can be reviewed and merged (please note if you'd like to be added to the bioconda project). Please see https://github.com/bioconda/bioconda-recipes/issues/15332 for more details.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [ ] This PR adds a new recipe.
* [ ] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by martin-raden** [comment]
@s-will not sure if the osx build will work. if not, I will undo and only bump to 2.4.14

**Comment by martin-raden** [comment]
@Raumzeit any idea why openmp was disabled in osx build?

**Comment by RaumZeit** [comment]
> @RaumZeit any idea why openmp was disabled in osx build?

As far as I remember, LLVM/clang in OS X pretended to provide full OpenMP support, but compilation failed for some of the features we required. Thus, we always deactivated OpenMP support on OS X... Maybe the situation changed, but I didn't find the time to find out yet.

**Comment by martin-raden** [comment]
@RaumZeit thanks, will see whether it compiles in conda or not and handle respectively..

**Comment by martin-raden** [comment]
@RaumZeit seems the openmp-osx  build went fine, so I enabled within the osx-bioconda package.
Best,
Martin

**Comment by martin-raden** [comment]
@dpryan79 thanks!

**Pull request merged**
