### PR TITLE
Update samblaster to 0.1.25

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`samblaster`](https://bioconda.github.io/recipes/samblaster/README.html): **0.1.24** &rarr; **0.1.25**

[install with bioconda](http://bioconda.github.io/recipes/samblaster/README.html) [Conda](https://anaconda.org/bioconda/samblaster/files)

Info | Link
-----|-----
Recipe | [`recipes/samblaster`](https://github.com//bioconda/bioconda-recipes/tree/bump/samblaster/recipes/samblaster) (click to view/edit other files)
Releases |[https://github.com/GregoryFaust/samblaster/releases](https://github.com/GregoryFaust/samblaster/releases)
Author | `@GregoryFaust`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by dfornika** [comment]
Looks like the [patch](https://github.com/bioconda/bioconda-recipes/blob/5e3c123ee779f255bf6dd39b6a93a71d6ea6aa59/recipes/samblaster/spaces_around_identifier.patch) isn't being applied correctly. Needs to be updated for this release?

**Comment by marcelm** [comment]
I created the patch originally. Let me see whether it’s still necessary.

**Comment by marcelm** [comment]
PR submitted upstream at GregoryFaust/samblaster#44. In the meantime, I’ve updated the patch.

**Comment by marcelm** [comment]
@BiocondaBot please merge

**Comment by GregoryFaust** [comment]
This issue should now be resolved in https://github.com/GregoryFaust/samblaster/releases/tag/v.0.1.26

**Comment by marcelm** [comment]
Thanks! The BiocondaBot has already seen that you made a new release and opened #22509. I have updated that PR to remove the now unneeded patch.

**Pull request merged**
