### PR TITLE
checksum changed

### PR DESCRIPTION
**Pull request by bgruening**
* [ ] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [ ] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by bgruening** [comment]
ping @dpryan79 this was failing on master ...

**Comment by dpryan79** [comment]
Xref https://github.com/bioconda/bioconda-recipes/pull/13555 :)

**Comment by dpryan79** [comment]
You can close this then, I hadn't noticed that they weren't using a tag when I merged their PR. I'm updating that in mine.

**Comment by bgruening** [comment]
merci

**Pull request closed without merging**
