### PR TITLE
clairvoyante imporve recipe to install conda native intervaltree and …

### PR DESCRIPTION
**Pull request by aquaskyline**
[ * ] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
[ ] This PR adds a new recipe.
[ * ] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
[ * ] This PR updates an existing recipe.
[ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by aquaskyline** [comment]
@bioconda/core Please review, thanls!

**Comment by aquaskyline** [comment]
@bioconda/core Please review, thanks!

**Comment by corburn** [comment]
@aquaskyline sure I'll check it out.

**Comment by aquaskyline** [comment]
@corburn done.

**Comment by aquaskyline** [comment]
The CircleCI test failure on the new recipe seems to have nothing to do with the changes. conda-build has succeed on my side.

**Comment by corburn** [comment]
@aquaskyline I applied the merge instructions from the CircleCI test failure to the pull request. The button to merge the pull request will not appear unless the test passes.

**Comment by corburn** [comment]
@aquaskyline conda-bld/ is the directory where the `conda-build` program writes its output.

Based on the error, it looks like there's been a recent change to `conda-build`:
https://github.com/conda/conda-build/issues/3114#issuecomment-419148975

**Comment by aquaskyline** [comment]
@corburn Thanks for help from @mbargull  All checks have passed.

**Pull request merged**
