### PR TITLE
Bump sc3 scripts

### PR DESCRIPTION
**Pull request by pinin4fjords**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

This PR bumps the source package version for bioconductor-sc3-scripts, and also renames to avoid clashes with mechanisms recognising actual bioconductor packages (see https://github.com/bioconda/bioconda-recipes/issues/13589).

### CODE REVIEW

**Comment by nh3** [comment]
Thanks @bgruening, that would be great.

BTW, as for https://github.com/bioconda/bioconda-recipes/pull/13157#issuecomment-463721408, do you recommend us just making new commits to revert the reversion? Thanks.

**Comment by bgruening** [comment]
> BTW, as for [#13157 (comment)](https://github.com/bioconda/bioconda-recipes/pull/13157#issuecomment-463721408), do you recommend us just making new commits to revert the reversion? 

Urgs, looks like this was a bad merge. Yes, please create a new commit if you have time. Otherwise, I will try to look at it over the weekend. Sorry, this was a huge rebuild of all R packages and the merge is master was complicated.

**Comment by nh3** [comment]
No problem. It's just a couple of recipes. We will make new commits. Thank you.

**Comment by pinin4fjords** [comment]
@nh3 I already reverted the reversions for sc3-scripts and scater-scripts- are there more?

**Comment by nh3** [comment]
So you mean we pin the version of sc3-scripts to the version of the bioconductor-sc3 and if there's change to sc3-scripts we just change the build number instead of the version number? Our script layer gets changes at times while pinning to a same version of the bioconductor package.

**Comment by pinin4fjords** [comment]
@bgruening thanks for the tidy-up reminder and the help

**Comment by nh3** [comment]
> @nh3 I already reverted the reversions for sc3-scripts and scater-scripts- are there more?

There's scater-scripts as well.

**Comment by pinin4fjords** [comment]
> > @nh3 I already reverted the reversions for sc3-scripts and scater-scripts- are there more?
> 
> There's scater-scripts as well.

https://github.com/bioconda/bioconda-recipes/pull/13743

**Comment by bgruening** [comment]
> So you mean we pin the version of sc3-scripts to the version of bioconductor-sc3 and if there's change to sc3-scripts we just change the build number instead of the version number? Our script layer gets changes at times while pinning to a same version of the bioconductor package.

Just an idea. You could version it like: {{ sc3_version }}-a or something like that.

**Comment by pinin4fjords** [comment]
Thanks @bgruening. I'll merge this PR for now, but we'll talk about adjusting the versioning strategy.

**Comment by nh3** [comment]
Hi @bgruening, could you make the container (https://quay.io/biocontainers/sc3-scripts) public please so that we can start using it? Many thanks!

**Comment by nh3** [comment]
It appears available now. Thanks!

**Comment by bgruening** [comment]
Jupp, done :)

**Comment by nh3** [comment]
Thank you @bgruening! You do have wifi built into your head :)

**Pull request merged**
