### PR TITLE
added perl-data-visitor and perl-tie-toobject

### PR DESCRIPTION
**Pull request by mtw**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by mtw** [comment]
@bgruening do you know whether the test-macos is not triggered automatically?

**Comment by bgruening** [comment]
@mtw it is, its just slow. We added yesterday a few hundred packages and they are still in the OSX backlog.

**Comment by bgruening** [comment]
@mtw urgs you are right. This is running on your account and not the bioconda CCI account :(
@mbargull this is another case I guess.

**Comment by mtw** [comment]
@bgruening thanks ;)

**Pull request merged**
