### PR TITLE
Fix to tobias 0.10.1 update

### PR DESCRIPTION
**Pull request by msbentsen**
Trying to resolve the xgboost dependency issues of #19767.

----

> Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences**
      (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

> Everyone has access to the following BiocondaBot commands, which can be given in a comment:
>
>  * `@BiocondaBot please update` will cause the BiocondaBot to merge the master branch into a PR
>  * `@BiocondaBot please add label` will add the `please review & merge` label.
>  * `@BiocondaBot please fetch artifacts` will post links to packages and docker containers built by the CI system. You can use this to test packages locally before merging.
>
> For members of the Bioconda project, the following command is also available:
>
>  * `@BiocondaBot please merge` will cause packages/containers to be uploaded and a PR merged. Someone must approve a PR first! This has the benefit of not wasting CI build time required by manually merging PRs.
>
> If you have questions, please post them in gitter or ping `@bioconda/core` in a comment (if you are not able to directly ping `@bioconda/core` then the bot will repost your comment and enable pinging).

### CODE REVIEW

**Comment by msbentsen** [comment]
This is odd... xgboost is pulled as a dependency (0.90-py37he1b5a44_4, conda-forge), but afterwards it is not known to python, which then states `'xgboost>=0.71' distribution was not found`.

I see a similar issue raised by #19299, but it was never solved (or was solved by removing xgboost as dependency). I can't tell at which end the issue is. Help is much appreciated! @jenzopr?

**Comment by marcelm** [comment]
Hi, while you’re updating this recipe anyway, could you please change the `matplotlib` dependency to `matplotlib-base`? See #19996 .

I also looked at your build problem, but I don’t have a clue at the moment.

**Comment by marcelm** [comment]
One idea for debugging: You could temporarily add `python -c "import xdgboost"` to the test commands and see whether that works.

**Comment by marcelm** [comment]
First, I think now that the correct dependency to use is `py-xdgboost`. If you specify `xdgboost`, that will pull in `py-xdgboost` as well and it’ll work, but since you only need the Python module, `py-xdgboost` should be enough. (Both pull in `libxdgboost`.)

I can reproduce the problem locally: Creating a new environment with `conda create -n xdgboost py-xdgboost` and then running `pip freeze` in that environment will not list `xdgboost`. The problem appears to be that the `py-xdgboost` package does not contain the `.dist-info` directory that contains the meta information that pip uses to find out about installed packages. This should probably be reported at https://github.com/conda-forge/xgboost-feedstock .

**Comment by msbentsen** [comment]
Thank you so much, @marcelm! I hope we can get it solved through an update of the xgboost conda-forge package as you suggested. I am still wondering how the 'gimmemotif' bioconda package managed to build without errors though (since it has the same dependency on xgboost). Maybe the this is a special case since it is a dependency of a dependency? Anyway, thanks :-)

**Comment by marcelm** [comment]
> I am still wondering how the 'gimmemotif' bioconda package managed to build without errors

I think the difference is the way the command-line scripts are installed.

gimmemotifs [uses the `scripts` argument in its `setup.py` file](https://github.com/vanheeringen-lab/gimmemotifs/blob/3f76ea95220c32f8cb126553ef2ccd16e17cc7dd/setup.py#L102). This will just copy over the file during installation almost unmodified (except for adjusting the shebang).

TOBIAS [uses the setuptoos `entry_points` feature in its `setup.py`](https://github.com/loosolab/TOBIAS/blob/61ad7418483b2ba1c67ca4f49490da93081fd712/setup.py#L61). With this, `setuptools` generates the entire script automatically, and this generated script contains a version check.

**Comment by msbentsen** [comment]
Note: Temporarily "fixed" by removing 'gimmemotifs' as a dependency for TOBIAS with #20643. Ideally though, I would like to bring it back in once the dependency issues are solved.

**Pull request closed without merging**
