### PR TITLE
Update pypgatk to 0.0.8

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`pypgatk`](https://bioconda.github.io/recipes/pypgatk/README.html): **0.0.4** &rarr; **0.0.8**

[install with bioconda](http://bioconda.github.io/recipes/pypgatk/README.html) [Conda](https://anaconda.org/bioconda/pypgatk/files)

Info | Link
-----|-----
Recipe | [`recipes/pypgatk`](https://github.com//bioconda/bioconda-recipes/tree/bump/pypgatk/recipes/pypgatk) (click to view/edit other files)
Releases |[https://pypi.org/pypi/pypgatk/json](https://pypi.org/pypi/pypgatk/json)
Recipe Maintainer(s) | @ypriverol

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by ypriverol** [comment]
@bgruening the package is failing because it can't find the dependency `ratelimit`

**Comment by bgruening** [comment]
It seems you need to add https://pypi.org/project/ratelimit/ as dependency. And `ratelimit` is not yet in conda-forge, so this needs to be addeed before.

**Comment by ypriverol** [comment]
can I help with that?

**Comment by bgruening** [comment]
@bioconda-bot please update

**Review by ypriverol — APPROVED** [review]

**Comment by bgruening** [comment]
@bioconda-bot please merge

**Pull request merged**
