### PR TITLE
Add bandage

### PR DESCRIPTION
**Pull request by druvus**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by druvus** [comment]
Running into issues with qt: `This application failed to start because it could not find or load the Qt platform plugin "minimal"`

Not sure how to fix it so any help is welcome.

**Comment by bgruening** [comment]
Just a guess maybe this works:
```
- pkg-config  # [unix]
- qt 5.6.*
```
Also maybe this helps? `export QT_SELECT=5`

**Comment by bgruening** [comment]
Does not seem to help :(
I found this one: https://github.com/ContinuumIO/anaconda-issues/issues/1182

**Comment by epruesse** [comment]
@rrwick Can you help?

**Comment by johanneskoester** [comment]
We  have made changes to our build system (migrated from Travis CI to  Circle CI). If you would like to continue working on this PR, please  reopen this PR and update with latest upstream/master.

**Pull request closed without merging**
