### PR TITLE
Bump build number

### PR DESCRIPTION
**Pull request by chambm**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by chambm** [comment]
@bioconda/core 
Can one of you delete bioconductor-1.34.2_0? The dashes prevent conda from parsing build# 1 where I removed the dashes. This seems like a conda bug, though.

**Comment by chambm** [comment]
Is pinging @bioconda/core the right thing to do here? @bgruening @johanneskoester ?

**Comment by johanneskoester** [comment]
@chambm, sorry, can you point me to the file I shall delete on anaconda? I cannot see it... Maybe somebody else has already deleted it?

**Comment by chambm** [comment]
Sorry I left out the build string:
osx-64/bioconductor-rtracklayer-1.34.2-r3.3.1_0.tar.bz2
linux-64/bioconductor-rtracklayer-1.34.2-r3.3.1_0.tar.bz2

**Comment by bgruening** [comment]
removed.

**Pull request merged**
