### PR TITLE
Fix gseapy-0.12.0: Fix Python version for the rust compiler

### PR DESCRIPTION
**Pull request by zqfang**
Fix Python version for rust compiler.

The current conda build version caused "No module named gseapy.gse" error, because the python version should not be noarch anymore.

Update [`gseapy`](https://bioconda.github.io/recipes/gseapy/README.html): **0.12.0** &rarr; **0.12.0**

[install with bioconda](http://bioconda.github.io/recipes/gseapy/README.html) [Conda](https://anaconda.org/bioconda/gseapy/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/gseapy`](https://github.com//bioconda/bioconda-recipes/tree/bump/gseapy/recipes/gseapy) (click to view/edit other files)
Summary | Gene Set Enrichment Analysis in Python
Home | [https://github.com/zqfang/gseapy](https://github.com/zqfang/gseapy)
Releases |[https://pypi.org/pypi/gseapy/json](https://pypi.org/pypi/gseapy/json)

***

### CODE REVIEW

**Comment by zqfang** [comment]
@bioconda-bot-helper , Please help. 

While I've test the updated recipe in locally MacOS (v12.4) sucessfully, this updated recipe alway failed on bioconda build for OSX. I could not figure out what the error message means.

**Comment by zqfang** [comment]
@marcelm , it looks like this gseapy recipe works. would you mind help me re-trigger the CI build.? Thanks

**Review by marcelm — APPROVED** [review]

**Comment by marcelm** [comment]
Good that it worked! Please remember to use the `BiocondaBot please merge` command instead of merging directly. That avoids re-running the CI tests.

**Comment by zqfang** [comment]
Woo, that's good to know. Thank you very much for your help @marcelm

**Pull request merged**
