### PR TITLE
Update sina to 1.7.0

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`sina`](https://bioconda.github.io/recipes/sina/README.html): **1.6.1** &rarr; **1.7.0**

[install with bioconda](http://bioconda.github.io/recipes/sina/README.html) [Conda](https://anaconda.org/bioconda/sina/files)

Info | Link
-----|-----
Recipe | [`recipes/sina`](https://github.com//bioconda/bioconda-recipes/tree/bump/sina/recipes/sina) (click to view/edit other files)
Releases |[https://github.com/epruesse/SINA/releases](https://github.com/epruesse/SINA/releases)
Recipe Maintainer(s) | @epruesse
Author | @epruesse
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by epruesse** [comment]
Failed with this:

```
Fixing permissions
01:26:30 BIOCONDA INFO (OUT) Traceback (most recent call last):
01:26:30 BIOCONDA INFO (OUT)   File "/opt/conda/bin/conda-build", line 11, in <module>
01:26:30 BIOCONDA INFO (OUT)     sys.exit(main())
01:26:30 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 474, in main
01:26:30 BIOCONDA INFO (OUT)     execute(sys.argv[1:])
01:26:30 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 465, in execute
01:26:30 BIOCONDA INFO (OUT)     verify=args.verify, variants=args.variants)
01:26:30 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.7/site-packages/conda_build/api.py", line 209, in build
01:26:30 BIOCONDA INFO (OUT)     notest=notest, need_source_download=need_source_download, variants=variants)
01:26:30 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.7/site-packages/conda_build/build.py", line 2864, in build_tree
01:26:30 BIOCONDA INFO (OUT)     notest=notest,
01:26:30 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.7/site-packages/conda_build/build.py", line 2151, in build
01:26:30 BIOCONDA INFO (OUT)     newly_built_packages = bundlers[pkg_type](output_d, m, env, stats)
01:26:30 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.7/site-packages/conda_build/build.py", line 1518, in bundle_conda
01:26:30 BIOCONDA INFO (OUT)     output['checksums'] = create_info_files(metadata, files, prefix=metadata.config.host_prefix)
01:26:30 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.7/site-packages/conda_build/build.py", line 1195, in create_info_files
01:26:30 BIOCONDA INFO (OUT)     write_info_files_file(m, files)
01:26:30 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.7/site-packages/conda_build/build.py", line 1040, in write_info_files_file
01:26:30 BIOCONDA INFO (OUT)     fo.write(f + '\n')
01:26:30 BIOCONDA INFO (OUT) UnicodeEncodeError: 'utf-8' codec can't encode characters in position 4-5: surrogates not allowed
01:26:36 BIOCONDA ERROR COMMAND FAILED (exited with 1): docker run -t --net host --rm -v /tmp/tmp4uqyigqp/build_script.bash:/opt/build_script.bash -v /home/circleci/project/miniconda/conda-bld/:/opt/host-conda-bld -v /home/circleci/project/recipes/sina:/opt/recipe -e LANG=en_US.UTF-8 -e HOST_USER_ID=1001 bioconda/bioconda-utils-build-env:latest /bin/bash /opt/build_script.bash
```

**Comment by epruesse** [comment]
@BiocondaBot rebuild

**Comment by epruesse** [comment]
Don't merge - even if this will look alright. Messing with it by hand. There is something weird going on.

**Comment by epruesse** [comment]
```
-rwxr-xr-x   1 root root    1656768 Aug  1 21:03 libsina.so.0.0.0
lrwxrwxrwx   1 root root         16 Aug  1 21:03 libsina.so.0 -> libsina.so.0.0.0
lrwxrwxrwx   1 root root         16 Aug  1 21:03 libsina.so -> libsina.so.0.0.0
-rwxr-xr-x   1 root root       1852 Aug  1 21:03 libsina.la
-rw-r--r--   1 root root    8186628 Aug  1 21:03 libsina.a
lrwxrwxrwx   1 root root         21 Aug  1 21:03 ??? -> libxkbcommon.so.0.0.0
```

**Comment by epruesse** [comment]
Ok, so apparently `ldconfig` is run as part of the automake build script. This is what creates the symlink to `libxkbcommon.so.0.0.0` with a name that can't be parsed. It's so bad it just crashed my tilix console...

**Comment by epruesse** [comment]
To reproduce:
```
wget https://anaconda.org/conda-forge/libxkbcommon/0.10.0/download/linux-64/libxkbcommon-0.10.0-he1b5a44_0.tar.bz2
tar xf libxkb*bz2
cd lib
ldconfig -vn .
ls -l
```

**Comment by rpetit3** [comment]
@bioconda-bot please merge

**Pull request merged**
