### PR TITLE
update khmer

### PR DESCRIPTION
**Pull request by lskatz**
khmer does not play well with python 3.12 and so I have updated the requirement. More information: <https://github.com/dib-lab/khmer/issues/1927>

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

### General instructions

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

### Instructions for avoiding API, ABI, and CLI breakage issues
Conda is able to record and lock (a.k.a. pin) dependency versions used at build time of other recipes.
This way, one can avoid that expectations of a downstream recipe with regards to API, ABI, or CLI are violated by later changes in the recipe.
If not already present in the meta.yaml, make sure to specify `run_exports` (see [here](https://bioconda.github.io/contributor/linting.html#missing-run-exports) for the rationale and comprehensive explanation).
Add a `run_exports` section like this:

```yaml
build:
  run_exports:
    - ...

```

with `...` being one of:

| Case                             | run_exports statement                                               |
| -------------------------------- | ------------------------------------------------------------------- |
| semantic versioning              | `{{ pin_subpackage("myrecipe", max_pin="x") }}`     |
| semantic versioning (0.x.x)      | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}`   |
| known breakage in minor versions | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| known breakage in patch versions | `{{ pin_subpackage("myrecipe", max_pin="x.x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| calendar versioning              | `{{ pin_subpackage("myrecipe", max_pin=None) }}`    |

while replacing `"myrecipe"` with either `name` if a `name|lower` variable is defined in your recipe or with the lowercase name of the package in quotes.

### Bot commands for PR management

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

Note that the <code>@BiocondaBot please merge</code> command is now depreciated. Please just squash and merge instead.

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by dr-joe-wirth** [comment]
oops. looks like i duplicated this in PR #49350. maybe this PR should be closed?

**Comment by rpetit3** [comment]
closing in fanvor of the merged https://github.com/bioconda/bioconda-recipes/pull/49350

**Comment by rpetit3** [comment]
reopening, since it looks like we'll need it

**Comment by dr-joe-wirth** [comment]
tests passed, but it didn't actually build anything.

**Comment by dr-joe-wirth** [comment]
i have a hunch that the problem is with the patch. the highest release that the khmer github page lists is 2.1.2. i'm not sure where the 3.0+ versions are coming from other than the patch.

**Comment by aliciaaevans** [comment]
I made PR https://github.com/bioconda/bioconda-recipes/pull/49494 just to update the build failure file (recipes/khmer/build_failure.linux-64.yaml) on master so it doesn't try to build it on the nightly in the current broken state, but that build_failure file can be removed on this branch once my PR is merged to master and then this branch updated from master.

**Comment by dr-joe-wirth** [comment]
not sure why this is failing, but it looks like a certain folder isn't being found. here is the relevant output from the bioconda test.


```text
.18:54:44 BIOCONDA INFO (OUT)   /opt/conda/conda-bld/khmer_1722279080981/_build_env/bin/x86_64-conda-linux-gnu-c++ -shared -Wl,--allow-shlib-undefined -Wl,-rpath,/opt/conda/conda-bld/khmer_1722279080981/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib -Wl,-rpath-link,/opt/conda/conda-bld/khmer_1722279080981/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib -L/opt/conda/conda-bld/khmer_1722279080981/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib -Wl,--allow-shlib-undefined -Wl,-rpath,/opt/conda/conda-bld/khmer_1722279080981/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib -Wl,-rpath-link,/opt/conda/conda-bld/khmer_1722279080981/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib -L/opt/conda/conda-bld/khmer_1722279080981/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,--allow-shlib-undefined -Wl,-rpath,/opt/conda/conda-bld/khmer_1722279080981/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib -Wl,-rpath-link,/opt/conda/conda-bld/khmer_1722279080981/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib -L/opt/conda/conda-bld/khmer_1722279080981/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /opt/conda/conda-bld/khmer_1722279080981/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/include -fdebug-prefix-map=/opt/conda/conda-bld/khmer_1722279080981/work=/usr/local/src/conda/khmer-3.0.0a3 -fdebug-prefix-map=/opt/conda/conda-bld/khmer_1722279080981/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho=/usr/local/src/conda-prefix -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /opt/conda/conda-bld/khmer_1722279080981/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/include build/temp.linux-x86_64-cpython-38/khmer/_oxli/oxli_exception_convert.o build/temp.linux-x86_64-cpython-38/khmer/_oxli/utils.o build/temp.linux-x86_64-3.8/src/khmer/_cpy_khmer.o build/temp.linux-x86_64-3.8/src/khmer/_cpy_utils.o build/temp.linux-x86_64-3.8/src/khmer/_cpy_readparsers.o build/temp.linux-x86_64-3.8/src/oxli/read_parsers.o build/temp.linux-x86_64-3.8/src/oxli/kmer_hash.o build/temp.linux-x86_64-3.8/src/oxli/hashtable.o build/temp.linux-x86_64-3.8/src/oxli/hashgraph.o build/temp.linux-x86_64-3.8/src/oxli/labelhash.o build/temp.linux-x86_64-3.8/src/oxli/subset.o build/temp.linux-x86_64-3.8/src/oxli/read_aligner.o build/temp.linux-x86_64-3.8/src/oxli/hllcounter.o build/temp.linux-x86_64-3.8/src/oxli/traversal.o build/temp.linux-x86_64-3.8/src/oxli/kmer_filters.o build/temp.linux-x86_64-3.8/src/oxli/assembler.o build/temp.linux-x86_64-3.8/src/oxli/alphabets.o build/temp.linux-x86_64-3.8/src/oxli/storage.o build/temp.linux-x86_64-3.8/third-party/smhasher/MurmurHash3.o third-party/cqf/gqf.o -lz -lbz2 -o build/lib.linux-x86_64-cpython-38/khmer/_oxli/utils.cpython-38-x86_64-linux-gnu.so -fopenmp
18:54:44 BIOCONDA INFO (OUT)   x86_64-conda-linux-gnu-c++: error: build/temp.linux-x86_64-3.8/src/khmer/_cpy_khmer.o: No such file or directory
18:54:44 BIOCONDA INFO (OUT)   x86_64-conda-linux-gnu-c++: error: build/temp.linux-x86_64-3.8/src/khmer/_cpy_utils.o: No such file or directory
18:54:44 BIOCONDA INFO (OUT)   x86_64-conda-linux-gnu-c++: error: build/temp.linux-x86_64-3.8/src/khmer/_cpy_readparsers.o: No such file or directory
18:54:44 BIOCONDA INFO (OUT)   x86_64-conda-linux-gnu-c++: error: build/temp.linux-x86_64-3.8/src/oxli/read_parsers.o: No such file or directory
18:54:44 BIOCONDA INFO (OUT)   x86_64-conda-linux-gnu-c++: error: build/temp.linux-x86_64-3.8/src/oxli/kmer_hash.o: No such file or directory
18:54:44 BIOCONDA INFO (OUT)   x86_64-conda-linux-gnu-c++: error: build/temp.linux-x86_64-3.8/src/oxli/hashtable.o: No such file or directory
18:54:44 BIOCONDA INFO (OUT)   x86_64-conda-linux-gnu-c++: error: build/temp.linux-x86_64-3.8/src/oxli/hashgraph.o: No such file or directory
18:54:44 BIOCONDA INFO (OUT)   x86_64-conda-linux-gnu-c++: error: build/temp.linux-x86_64-3.8/src/oxli/labelhash.o: No such file or directory
18:54:44 BIOCONDA INFO (OUT)   x86_64-conda-linux-gnu-c++: error: build/temp.linux-x86_64-3.8/src/oxli/subset.o: No such file or directory
18:54:44 BIOCONDA INFO (OUT)   x86_64-conda-linux-gnu-c++: error: build/temp.linux-x86_64-3.8/src/oxli/read_aligner.o: No such file or directory
18:54:44 BIOCONDA INFO (OUT)   x86_64-conda-linux-gnu-c++: error: build/temp.linux-x86_64-3.8/src/oxli/hllcounter.o: No such file or directory
18:54:44 BIOCONDA INFO (OUT)   x86_64-conda-linux-gnu-c++: error: build/temp.linux-x86_64-3.8/src/oxli/traversal.o: No such file or directory
18:54:44 BIOCONDA INFO (OUT)   x86_64-conda-linux-gnu-c++: error: build/temp.linux-x86_64-3.8/src/oxli/kmer_filters.o: No such file or directory
18:54:44 BIOCONDA INFO (OUT)   x86_64-conda-linux-gnu-c++: error: build/temp.linux-x86_64-3.8/src/oxli/assembler.o: No such file or directory
18:54:44 BIOCONDA INFO (OUT)   x86_64-conda-linux-gnu-c++: error: build/temp.linux-x86_64-3.8/src/oxli/alphabets.o: No such file or directory
18:54:44 BIOCONDA INFO (OUT)   x86_64-conda-linux-gnu-c++: error: build/temp.linux-x86_64-3.8/src/oxli/storage.o: No such file or directory
18:54:44 BIOCONDA INFO (OUT)   x86_64-conda-linux-gnu-c++: error: build/temp.linux-x86_64-3.8/third-party/smhasher/MurmurHash3.o: No such file or directory
18:54:44 BIOCONDA INFO (OUT)   error: command '/opt/conda/conda-bld/khmer_1722279080981/_build_env/bin/x86_64-conda-linux-gnu-c++' failed with exit code 1
18:54:44 BIOCONDA INFO (OUT)   error: subprocess-exited-with-error
```

**Comment by dr-joe-wirth** [comment]
this recipe builds locally, but is not passing checks. [the error](https://dev.azure.com/bioconda/bioconda-recipes/_build/results?buildId=65959&view=logs&j=e14e69ff-a0ae-55c4-b71d-229b239cfb2f&t=7df82132-b284-504b-53d6-7d3e63519572&l=633) seems to indicate that `gcc` could not be found?

lines 631-636:

```text
21:11:16 BIOCONDA INFO (OUT)   bash -c "cd third-party/bzip2 && make -f Makefile-libbz2_so all"
21:11:16 BIOCONDA INFO (OUT)   gcc -fpic -fPIC -Wall -Winline -O2 -g -D_FILE_OFFSET_BITS=64 -c blocksort.c
21:11:16 BIOCONDA INFO (OUT)   make: gcc: No such file or directory
21:11:16 BIOCONDA INFO (OUT)   make: *** [Makefile-libbz2_so:47: blocksort.o] Error 127
21:11:16 BIOCONDA INFO (OUT)   error: command '/usr/bin/bash' failed with exit code 2
21:11:16 BIOCONDA INFO (OUT)   error: subprocess-exited-with-error
```
when i built locally I ran this:

```bash
conda build --python 3.11 ./bioconda-recipes/recipes/khmer/
```

after building and testing, i got this message:

```text
INFO :: The inputs making up the hashes for the built packages are as follows:
{
  "khmer-2.1.1-py311h93a0a19_0.tar.bz2": {
    "recipe": {
      "c_compiler": "gcc",
      "c_compiler_version": "10",
      "cxx_compiler": "gxx",
      "cxx_compiler_version": "10",
      "target_platform": "linux-64"
    }
  }
}
```

**Comment by dr-joe-wirth** [comment]
@lskatz @rpetit3 @aliciaaevans @mencian 

i feel like i'm very close to getting this recipe to work. do you have any insight as to how i can fix the error with `gcc` being absent from the build environment? i can build the recipe locally without issues.

**Comment by ctb** [comment]
(I suspect `compiler` is needed - see https://github.com/conda-forge/sourmash_plugin_branchwater-feedstock/blob/main/recipe/meta.yaml)

**Comment by dr-joe-wirth** [comment]
> (I suspect `compiler` is needed - see https://github.com/conda-forge/sourmash_plugin_branchwater-feedstock/blob/main/recipe/meta.yaml)

The recipe already has:

```text
requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - make
```

should I be including something else? is it not specified appropriately?

**Comment by ctb** [comment]
Sorry, didn't look at the recipe - that should include relevant compilers! I'll look at this over the weekend and see if I can provide some more relevant suggestions 😆 😭

**Comment by lskatz** [comment]
gcc should be present but yet it isn't. Is it because we need to add `compiler` to `host:`? It wouldn't need it in `run:`, would it?

**Comment by dr-joe-wirth** [comment]
> gcc should be present yet it cannot be found. Is it because we need to add `compiler` to `host:`? It wouldn't need it in `run:`, would it?

the linter hates you if you try this

**Comment by lskatz** [comment]
Well that didn't work and so I guess the issue is really in the build step? 

Maybe the patch file. It has this patch having to do with make and a compiler 

```patch
-        cqfcmd = ['bash', '-c', 'cd third-party/cqf && make']
+        cqfcmd = ['bash', '-c', 'cd third-party/cqf && cxx="${CXX} ${CXXFLAGS} ${LDFLAGS} -std=c++11" && make CC="${cxx} -fPIC" CXX="${cxx} -fPIC" LD="${cxx}"']
```

**Comment by lskatz** [comment]
The patch refers to lines that aren't even there in `setup.py` anymore. But I guess from there I see that khmer packages up its own dependencies which I am going to try to add to the build step. Fortunately, `setup.py` checks to see if these things exist first and so I hope that I can just obviate this step.

```python
        if "z" not in self.libraries:
            zcmd = ['bash', '-c', 'cd ' + ZLIBDIR + ' && ( test Makefile -nt'
                    ' configure || bash ./configure --static ) && make -f '
                    'Makefile.pic PIC']
            spawn(cmd=zcmd, dry_run=self.dry_run)
            self.extensions[0].extra_objects.extend(
                path_join("third-party", "zlib", bn + ".lo") for bn in [
                    "adler32", "compress", "crc32", "deflate", "gzclose",
                    "gzlib", "gzread", "gzwrite", "infback", "inffast",
                    "inflate", "inftrees", "trees", "uncompr", "zutil"])
        if "bz2" not in self.libraries:
            bz2cmd = ['bash', '-c', 'cd ' + BZIP2DIR + ' && make -f '
                      'Makefile-libbz2_so all']
            spawn(cmd=bz2cmd, dry_run=self.dry_run)
            self.extensions[0].extra_objects.extend(
                path_join("third-party", "bzip2", bn + ".o") for bn in [
                    "blocksort", "huffman", "crctable", "randtable",
                    "compress", "decompress", "bzlib"])
        _build_ext.run(self)
```

**Comment by lskatz** [comment]
I made a patch that hopefully sidesteps the dependency installations but I do not know enough about khmer's inner workings or python to go much further. I just used `if false`.

```python
    def run(self):
        """Run extension builder."""
        if "%x" % sys.maxsize != '7fffffffffffffff':
            raise DistutilsPlatformError("%s require 64-bit operating system" %
                                         SETUP_METADATA["packages"])

        if sys.platform == 'darwin' and 'gcov' in self.libraries:
            self.libraries.remove('gcov')

        if false:
            zcmd = ['bash', '-c', 'cd ' + ZLIBDIR + ' && ( test Makefile -nt'
                    ' configure || bash ./configure --static ) && make -f '
                    'Makefile.pic PIC']
            spawn(cmd=zcmd, dry_run=self.dry_run)
            self.extensions[0].extra_objects.extend(
                path_join("third-party", "zlib", bn + ".lo") for bn in [
                    "adler32", "compress", "crc32", "deflate", "gzclose",
                    "gzlib", "gzread", "gzwrite", "infback", "inffast",
                    "inflate", "inftrees", "trees", "uncompr", "zutil"])
        if false:
            bz2cmd = ['bash', '-c', 'cd ' + BZIP2DIR + ' && make -f '
                      'Makefile-libbz2_so all']
            spawn(cmd=bz2cmd, dry_run=self.dry_run)
            self.extensions[0].extra_objects.extend(
                path_join("third-party", "bzip2", bn + ".o") for bn in [
                    "blocksort", "huffman", "crctable", "randtable",
                    "compress", "decompress", "bzlib"])
        _build_ext.run(self)
```

**Comment by lskatz** [comment]
Ok I have advanced it but I need python help now. How do I let it import that library?

https://dev.azure.com/bioconda/bioconda-recipes/_build/results?buildId=66047&view=logs&j=e14e69ff-a0ae-55c4-b71d-229b239cfb2f&t=7df82132-b284-504b-53d6-7d3e63519572&l=4408

image

**Comment by dr-joe-wirth** [comment]
> Ok I have advanced it but I need python help now. How do I let it import that library?

```
22:13:29 BIOCONDA INFO (OUT) ImportError: /opt/conda/conda-bld/khmer_1723068489757/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib/python3.11/site-packages/khmer/_khmer.cpython-311-x86_64-linux-gnu.so: undefined symbol: gzerror
```

The error is happening inside the cython file. `undefined symbol: gzerror`

**Comment by dr-joe-wirth** [comment]
@lskatz I have a hunch. In the block you bypassed with your patch, it references these string constants:

```python
ZLIBDIR = 'third-party/zlib'
BZIP2DIR = 'third-party/bzip2'
```

But I suspect that our more proper install of `zlib` is putting it someplace else. So that means it is not being linked or something like that in the `.so` file.

**Comment by lskatz** [comment]
> @lskatz I have a hunch. In the block you bypassed with your patch, it references these string constants:
> 
> ```python
> ZLIBDIR = 'third-party/zlib'
> BZIP2DIR = 'third-party/bzip2'
> ```
> 
> But I suspect that our more proper install of `zlib` is putting it someplace else. So that means it is not being linked or something like that in the `.so` file.

Sure, let's try it. I added onto the patch.

**Comment by dr-joe-wirth** [comment]
> > @lskatz I have a hunch. In the block you bypassed with your patch, it references these string constants:
> > ```python
> > ZLIBDIR = 'third-party/zlib'
> > BZIP2DIR = 'third-party/bzip2'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > But I suspect that our more proper install of `zlib` is putting it someplace else. So that means it is not being linked or something like that in the `.so` file.
> 
> Sure, let's try it. I added onto the patch.

See the file I added to my edited comment. Here is the relevant part that stood out to me:

```
[build_ext]
define = SEQAN_HAS_BZIP2,SEQAN_HAS_ZLIB
undef = NO_UNIQUE_RC
# libraries = z,bz2
## if using system libraries
include-dirs = lib:third-party/zlib:third-party/bzip2:third-party/seqan/core/include:third-party/smhasher
# include-dirs = lib
## if using system libraries (broken)
```

**Comment by dr-joe-wirth** [comment]
> Sure, let's try it. I added onto the patch.

Also, I don't think commenting them out will do much since they are only accessed in your silenced block.

I'm thinking we need to somehow tell the compile where the these libraries live so it can link them in the shared object file that gets created. But at this point I'm reaching the boundaries of my c++ knowledge.

**Comment by lskatz** [comment]
@ctb we might have found what we need to change but we're at our limits. How do we change khmer so that it does not depend on its repackaged dependencies and instead depends on conda dependencies? Is it in setup.cfg?

**Comment by lskatz** [comment]
> [build_ext]
> define = SEQAN_HAS_BZIP2,SEQAN_HAS_ZLIB
> undef = NO_UNIQUE_RC
> # libraries = z,bz2
> ## if using system libraries
> include-dirs = lib:third-party/zlib:third-party/bzip2:third-party/seqan/core/include:third-party/smhasher
> # include-dirs = lib
> ## if using system libraries (broken)

I'm attempting to comment that out and try it

**Comment by lskatz** [comment]
image

`MurmurHash3.h: No such file or directory` and so this goes more to the dependencies that are needed during runtime. [That might just be `python-dev`](https://github.com/explosion/spaCy/issues/1395#issuecomment-338487122)? I'll try it.

**Comment by dr-joe-wirth** [comment]
> image
> 
> `MurmurHash3.h: No such file or directory` and so this goes more to the dependencies that are needed during runtime. [That might just be `python-dev`](https://github.com/explosion/spaCy/issues/1395#issuecomment-338487122)? I'll try it.

Murmurhash3 is from smhasher. I think I've seen that as a dependency somewhere.

**Comment by dr-joe-wirth** [comment]
For whatever reason, it cannot find the directory where the included header files for `seqan` live. When I install `seqan` using an environment file locally, the header files are in the directory `<env name>/include/seqan`. I thought this might be euivalent to `lib` because that is also where `zlib.h` and `bzlib.h` live.

**Comment by dr-joe-wirth** [comment]
giving up for now. `khmer` compiles but does not run. `gzerror` is an undefined symbol at runtime...prob has something to do with the fact that `third-party/zlib` appears to be static linked in the `setup.py` file, but we want it to link to conda-installed `zlib` instead of relying on the `third-party` directory as this would be more stable.

**Pull request closed without merging**
