### PR TITLE
add recipe for SerotypeFinder

### PR DESCRIPTION
**Pull request by rpetit3**
The PR adds a recipe for [SerotypeFinder](https://bitbucket.org/genomicepidemiology/serotypefinder/src/master/), a tool that  identifies the serotype in total or partial sequenced isolates of E. coli.

One thing about SerotypeFinder, is the database is in a separate repo and not tagged. The database repo is not updated very often (7 times in 5 years), so I don't expect it to be updated very often. I decided to build the most recent commit (explicitly) in the `build.sh` and added a script that would pull the latest updates (if any). 

Throughout this the current commit of the database that is being used is saved to a file in the database folder called `serotypefinder-db-commit.txt'. This at least allows the user to know which commit of the database is being used.

Definitely open to feedback here. The database is only ~160kb so I would prefer there not be a need for the user to manually create the database after install.

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by rpetit3** [comment]
Testing 
```
conda create -y -n serotypefinder-test -c https://162760-42372094-gh.circle-artifacts.com/0/tmp/artifacts/packages -c conda-forge -c bioconda serotypefinder

conda activate serotypefinder-test
```

# Test SerotypeFinder
```
which serotypefinder
/home/robert_petit/miniconda3/envs/serotypefinder-test/bin/serotypefinder
```
```
serotypefinder --help
usage: serotypefinder [-h] -i INFILE [INFILE ...] [-o OUTDIR] [-tmp TMP_DIR]
                      [-mp METHOD_PATH] [-p DB_PATH] [-d DATABASES]
                      [-l MIN_COV] [-t THRESHOLD] [-x] [-q]
... TRUNCATED ...
  -q, --quiet
```
```
# Test serotypefinder's test file
serotypefinder -i test.fsa
Found: fliC_307_AY249994_H9
Saving: fliC_307_AY249994_H9:1..2013:fliC_307_AY249994_H9:100.000000
Found: fliC_13_AY250020_H41
Same contig: fliC_307_AY249994_H9 == fliC_307_AY249994_H9
        fliC_13_AY250020_H41 vs fliC_307_AY249994_H9
        overlap found (594): fliC_13_AY250020_H41
        2012 <= 2606
                Scores: 32.28728698837394 cmp 100.0
... TRUNCATED ...
{'serotypefinder': {'results': {'H_type': {'fliC_307_AY249994_H9': {'HSP_length': 2013,
                                                                    'accession': 'AY249994',
                                                                    'contig_name': 'fliC_307_AY249994_H9',
                                                                    'coverage': 100.0,
                                                                    'gene': 'fliC',
                                                                    'hit_id': 'fliC_307_AY249994_H9:1..2013:fliC_307_AY249994_H9:100.000000',
                                                                    'identity': 100.0,
                                                                    'position_in_ref': '1..2013',
                                                                    'positions_in_contig': '1..2013',
                                                                    'serotype': 'H9',
                                                                    'template_length': 2013}},
                                'O_type': {'wzx_1_GU299791_O1': {'HSP_length': 1227,
                                                                 'accession': 'GU299791',
                                                                 'contig_name': 'wzx_1_GU299791_O1',
                                                                 'coverage': 100.0,
                                                                 'gene': 'wzx',
                                                                 'hit_id': 'wzx_1_GU299791_O1:1..1227:wzx_1_GU299791_O1:100.000000',
                                                                 'identity': 100.0,
                                                                 'position_in_ref': '1..1227',
                                                                 'positions_in_contig': '1..1227',
                                                                 'serotype': 'O1',
                                                                 'template_length': 1227}}},
                    'run_info': {'date': '22.07.2021', 'time': '20:30:38'},
                    'user_input': {'file_format': 'fasta',
                                   'filename(s)': ['test.fsa'],
                                   'method': 'blast'}}}
```

```
# Test own sample
mkdir test-sample
serotypefinder -i assembly.fasta -o test-sample/ -x
... TRUNCATED ...
{'serotypefinder': {'results': {'H_type': {'fliC_56_AJ884569_H8': {'HSP_length': 1479,
                                                                   'accession': 'AJ884569',
                                                                   'contig_name': 'contig_1',
                                                                   'coverage': 100.0,
                                                                   'gene': 'fliC',
                                                                   'hit_id': 'contig_1:2230554..2232032:fliC_56_AJ884569_H8:100.000000',
                                                                   'identity': 100.0,
                                                                   'position_in_ref': '1..1479',
                                                                   'positions_in_contig': '2230554..2232032',
                                                                   'serotype': 'H8',
                                                                   'template_length': 1479}},
                                'O_type': {'wzx_156_EU294168_O150': {'HSP_length': 1503,
                                                                     'accession': 'EU294168',
                                                                     'contig_name': 'contig_1',
                                                                     'coverage': 99.93,
                                                                     'gene': 'wzx',
                                                                     'hit_id': 'contig_1:2114035..2115536:wzx_156_EU294168_O150:99.268573',
                                                                     'identity': 99.33,
                                                                     'position_in_ref': '1..1503',
                                                                     'positions_in_contig': '2114035..2115536',
                                                                     'serotype': 'O150',
                                                                     'template_length': 1503},
                                           'wzy_119_EU294168_O150': {'HSP_length': 1098,
                                                                     'accession': 'EU294168',
                                                                     'contig_name': 'contig_1',
                                                                     'coverage': 100.0,
                                                                     'gene': 'wzy',
                                                                     'hit_id': 'contig_1:2119412..2120509:wzy_119_EU294168_O150:99.635701',
                                                                     'identity': 99.64,
                                                                     'position_in_ref': '1..1098',
                                                                     'positions_in_contig': '2119412..2120509',
                                                                     'serotype': 'O150',
                                                                     'template_length': 1098}}},
                    'run_info': {'date': '22.07.2021', 'time': '20:33:46'},
                    'user_input': {'file_format': 'fasta',
                                   'filename(s)': ['assembly.fasta'],
                                   'method': 'blast'}}}
                                   
tree test-sample/
test-sample/
├── Hit_in_genome_seq.fsa
├── Serotype_allele_seq.fsa
├── data.json
├── results.txt
├── results_tab.tsv
└── tmp
    ├── out_H_type.xml
    └── out_O_type.xml
```

# Test update database
```
which update-serotypefinder-db
/home/robert_petit/miniconda3/envs/serotypefinder-test/bin/update-serotypefinder-db
```

```
update-serotypefinder-db
Current SerotypeFinder database is already up to date
```

```
bash -x /home/robert_petit/miniconda3/envs/serotypefinder-test/bin/update-serotypefinder-db
+ cd /home/robert_petit/miniconda3/envs/serotypefinder-test/share/serotypefinder-2.0.1-0/database/
+ CURENTCOMMIT=
+ '[' -s serotypefinder-db-commit.txt ']'
++ head -n1 serotypefinder-db-commit.txt
+ CURENTCOMMIT=25ddd141d245db6382ca5876f7c7ddd0288aeb30
++ git ls-remote https://bitbucket.org/genomicepidemiology/serotypefinder_db.git
++ grep master
++ awk '{print $1}'
+ LATESTCOMMIT=25ddd141d245db6382ca5876f7c7ddd0288aeb30
+ '[' 25ddd141d245db6382ca5876f7c7ddd0288aeb30 == 25ddd141d245db6382ca5876f7c7ddd0288aeb30 ']'
+ echo 'Current SerotypeFinder database is already up to date'
Current SerotypeFinder database is already up to date
+ exit 0
```

**Comment by rpetit3** [comment]
@biocondabot please add label

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Comment by dpryan79** [comment]
@rpetit3 Thanks a ton for showing that you've tested things, it makes merging your PRs extremely straight forward :)

**Comment by rpetit3** [comment]
Thank you @dpryan79!  (anything to make your life easier, thank you very much for everything you do for Bioconda!)

**Pull request merged**
