### PR TITLE
Move screed to conda-forge, sourmash now depends on sourmash-minimal

### PR DESCRIPTION
**Pull request by luizirber**
(Sister PR: https://github.com/conda-forge/staged-recipes/pull/11735)

Moves screed to conda-forge, and split sourmash into `sourmash-minimal` (in conda-forge) and `sourmash` (here). Trying to follow a similar approach to `snakemake-minimal` and `snakemake`, where the latter brings all the extra dependencies.

Supersedes https://github.com/bioconda/bioconda-recipes/pull/22361

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by luizirber** [comment]
@BiocondaBot please update

**Comment by dpryan79** [comment]
@bioconda-bot please fetch artifacts

**Comment by luizirber** [comment]
Thanks @dpryan79! (and sorry for messing with your commits, I didn't see them before pushing :see_no_evil: )

**Comment by luizirber** [comment]
@bioconda-bot please merge

**Pull request merged**
