### PR TITLE
Unblacklist2 lecorguille

### PR DESCRIPTION
**Pull request by lecorguille**
* [ ] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [X] This PR does something else (explain below).

### CODE REVIEW

**Comment by daler** [comment]
@lecorguille, #2742 works on the same packages. Can you please see if you can make any progress on the too-long prefix for OSX in that PR?

**Comment by lecorguille** [comment]
Arg! I should have just commit bioconductor-genomicfeatures I need for -gviz and -cummerbund
I just add the other to be a nice guy :)

**Comment by daler** [comment]
bsgenome should be OK, as long as you don't need any of the bsgenome data packages.

**Comment by bgruening** [comment]
I will merge this to save travis time #2742 needs more love either way and a rebase :(
I'm a little bit puzzled with the OSX failure.

**Comment by bgruening** [comment]
@lecorguille thanks for being a nice guy!

**Comment by lecorguille** [comment]
I must be a little annoying to not follow the sorted list.
But I still have a couple of target. But after that I promise I will be more ordered

Cheers

**Pull request merged**
