### PR TITLE
Update seqfu to 1.22.0

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`seqfu`](https://bioconda.github.io/recipes/seqfu/README.html): **1.20.3** &rarr; **1.22.0**

[install with bioconda](http://bioconda.github.io/recipes/seqfu/README.html) [Conda](https://anaconda.org/bioconda/seqfu/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/seqfu`](https://github.com//bioconda/bioconda-recipes/tree/bump/seqfu/recipes/seqfu) (click to view/edit other files)
Summary | DNA sequence utilities
Home | [https://github.com/telatin/seqfu2/](https://github.com/telatin/seqfu2/)
Releases |[https://github.com/telatin/seqfu2/tags](https://github.com/telatin/seqfu2/tags)
Recipe Maintainer(s) | @telatin
Author | @telatin
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by martin-g** [comment]
@telatin About 
```
Setting environment variables
08:50:03 BIOCONDA INFO (OUT) GXX: 'not set'
08:50:03 BIOCONDA INFO (OUT) GCC: 'not set'
```

Those are exposed as `$CXX` for c++ and `CC` for c compiler. Maybe build.sh should export the missing as aliases ?!

**Comment by martin-g** [comment]
@BiocondaBot please fetch artifacts

**Comment by telatin** [comment]
> @telatin About 
> 
> ```
> 
> Setting environment variables
> 
> 08:50:03 BIOCONDA INFO (OUT) GXX: 'not set'
> 
> 08:50:03 BIOCONDA INFO (OUT) GCC: 'not set'
> 
> ```
> 
> 
> 
> Those are exposed as `$CXX` for c++ and `CC` for c compiler. Maybe build.sh should export the missing as aliases ?!

That was to fix Linux build and apparently is still not required on macOS. Do you have thoughts or suggestions?

**Comment by telatin** [comment]
I will add this to build:

```bash
# Export CC and CXX as aliases for GCC and GXX if they're not set
export CC="${CC:-${GCC}}"
export CXX="${CXX:-${GXX}}"
```
to implement the aliases in the next release

**Pull request merged**
