### PR TITLE
update dxpy to 0.274.0

### PR DESCRIPTION
**Pull request by notestaff**
* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [X] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [X] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by notestaff** [comment]
@bioconda/build-system can someone please help me understand, why the macos build is complaining about a problem with python 3.7, after building for python 3.6?

**Comment by notestaff** [comment]
@bioconda/core can someone please help me understand, why the macos build is complaining about a problem with python 3.7, after building for python 3.6?

**Comment by kyleabeauchamp** [comment]
I wonder if we need just add a # skip flag for py37 while the py37 rollout happens?

**Comment by dpryan79** [comment]
Xref: https://github.com/conda-forge/python-magic-feedstock/pull/7

**Comment by dpryan79** [comment]
No longer needed, closing

**Pull request closed without merging**
