### PR TITLE
minced: Pin openjdk 11

### LINKED ISSUE #14975: minced recipe update breaks prokka?
With prokka=1.13.3, I get the error
[14:42:16] Looking for 'minced' - found /home/travis/build/aschuerch/bactofidia/.snakemake/conda/27a7b7f2/bin/minced
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: minced has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

The bioconda prokka=1.13.3 package worked fine until recently. I think it might be due to an update of the minced recipe. Is this possible @epruesse ?

### PR DESCRIPTION
**Pull request by dfornika**
:information_source:
If this is your first pull request to Bioconda please ping `@bioconda/core` so it can be reviewed and to request being added as a member of the Bioconda team. Members of the Bioconda team are able to merge their own pull requests once tests and linting have passed.

----------------

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

Fixes #14975

### CODE REVIEW

**Comment by epruesse** [comment]
See also https://github.com/ctSkennerton/minced/issues/18

@bioconda/core: need a @bioconda/java - any of you experts that know whether this is the right pin?

**Comment by epruesse** [comment]
Thanks @dfornika for figuring out how to make this work. Can you explain what's going on? It would be good to have that in the `meta.yaml` as comments, something saying why the java version is pinned, so that it's clear in the future...

**Comment by dfornika** [comment]
I don't really have a deep understanding, I was getting this error when running `prokka-1.13`, which includes `minced` as a dependency:

```
Fatal error: Exit code 2 ()
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: minced has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
...
```

I checked the conda environment and it showed that `openjdk-8` was included.  I did a bit of googling and found this table of 'class file version' to 'Java version' 

https://stackoverflow.com/questions/9170832/list-of-java-class-file-format-major-version-numbers

**Comment by epruesse** [comment]
So it should be `>=11` then? Do we have a 12 or 13 to test with?

**Comment by dpryan79** [comment]
I recall that some of the libraries have gotten moved around between versions. Over on conda-forge, we had to pin r-rjava to modify the rpath stuff for this reason: https://github.com/conda-forge/r-rjava-feedstock/blob/master/recipe/meta.yaml#L22-L31

I haven't a clue which versions have moved libraries around were though :(

**Comment by epruesse** [comment]
I'm merging this. We can loosen the pins when we need to.

@biocondabot merge

**Pull request merged**
