### PR TITLE
Add bcbio-gff

### PR DESCRIPTION
**Pull request by dfornika**
:information_source:
Bioconda has finished the [GCC7 migration](https://github.com/bioconda/bioconda-recipes/issues/13578). If you are dealing with C/C++ or Python package it can be that you need to rebuild other dependent packages. [Bioconda utils - update-pinning](https://bioconda.github.io/updating.html#updating-recipes-for-a-pinning-change) will assist you with that. If you have any questions please use [issue 13578](https://github.com/bioconda/bioconda-recipes/issues/13578).

----------------

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by dfornika** [comment]
Build is failing because there is no `LICENSE` file in the pypi package. I've posted a pull-request to the `bcbio-gff` repo: https://github.com/chapmanb/bcbb/pull/122

**Comment by bgruening** [comment]
ping @chapmanb

**Comment by dfornika** [comment]
Thanks @bgruening . @chapmanb accepted my PR to make sure the `LICENSE` file would be included in the next release, but he also mentioned that it should be possible to merge into bioconda without the `LICENSE` file.

Looking at the build log it looks like I might just need to merge `master` into this branch because the linter is complaining about another package (`biom-format`).

**Comment by chapmanb** [comment]
Dan;
Thanks again for doing this and apologies about the issue. Sorry, I got it wrong in the other thread and looking back through the build history here did need to push a new version with the LICENSE fix. I just made 0.6.6 available:

https://pypi.org/project/bcbio-gff/#files

If you update to that and can avoid the anaconda.org download errors that are causing issues in recent builds, I hope that it will not install correctly for you. Please let me know if hit any other problems and thanks again.

**Comment by dfornika** [comment]
@chapmanb @bgruening I think this is ready to merge. Thanks to both of you for your help.

**Comment by chapmanb** [comment]
Dan -- awesome, thanks again for making this happen.

**Pull request merged**
