### PR TITLE
beast + beagle-lib

### PR DESCRIPTION
**Pull request by necrolyte2**

### CODE REVIEW

**Comment by JudoWill** [comment]
@necrolyte2 If you can rebase this onto the current master I can get it into the build queue.

**Comment by johanneskoester** [comment]
Let me do some admin magic :-).

**Comment by johanneskoester** [comment]
Unfortunately our branch protections prevents these merges, although they are clearly harmless. I try to do that from time to time to speed things up.

**Comment by necrolyte2** [comment]
Thanks! There are so many new additions that the pull requests get out of sync quite quickly. Thanks for merging.

**Pull request merged**
