### PR TITLE
Update egglib to 3.1.0.

### PR DESCRIPTION
**Pull request by ranwez**
Update egglib to 3.1.0
==========

the bioconda egglib recipe for egglib is currently out of date and using on a broken link. 
This recipe is for the latest release of egglib (3.1.0) which has been recently published in molecular ecology resources.

### CODE REVIEW

**Comment by ranwez** [comment]
@BiocondaBot please add label

**Comment by ranwez** [comment]
@BiocondaBot please add label

**Review by daler — APPROVED** [review]

**Comment by daler** [comment]
thanks @ranwez

**Comment by daler** [comment]
@BiocondaBot please merge

**Comment by daler** [comment]
@BiocondaBot please merge

**Comment by ranwez** [comment]
@daler 

thanks for helping with this update.

The URL provided by "conda skeleton pypi egglib" (  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/EggLib-{{ version }}.zip) is invalid, so I manually replaced it by the correct one in the recipe:
  url: "https://files.pythonhosted.org/packages/8e/f1/4eacf0858c363251c21dffd01804a66343f3a02e0d2adfafbe08bed58a0e/EggLib-3.1.0.zip"

I see that you changed the URL back to the cannonical form, but this broke the recipe. Could you please change back to the ugly but functionnal zip URL?

I pinpointed the problem to one of the main egglib developper so that he could try to get the canonical URL for the next egglib release.

thanks for your help

**Comment by JohGi** [comment]
Hi, I would like to use this egglib version, do you think it will be available soon?

**Comment by ranwez** [comment]
@BiocondaBot please add label help wanted

**Comment by ranwez** [comment]
Hi, I would really like to use this bioconda package, can someone help finilizing the package creation process?
I'm sorry if I missed something, it is my first time trying to contribute to bioconda ...

**Comment by sdemita** [comment]
Is it trying to run the test on Python 2.7?

**Comment by dpryan79** [comment]
Yeah, it'll try to build for 2.7 and 3.6-3.10.

**Comment by dpryan79** [comment]
@BiocondaBot please fetch artifacts

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@BiocondaBot please merge

**Comment by ranwez** [comment]
thanks so much all for your help with this recipe

**Pull request merged**
