### PR TITLE
Add SUPER-FOCUS

### PR DESCRIPTION
**Pull request by boulund**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

This PR aims to add a recipe for [SUPER-FOCUS](https://edwards.sdsu.edu/SUPERFOCUS), a tool for functional analysis of shotgun metagenomic data. I'm opening this PR despite tests not passing because I need some help figuring out what's wrong. I don't understand what's going on from the error messages.

Firstly, I couldn't get circleci to work locally, it just gives me the following error:

```
====>> Spin up Environment
Build-agent version 0.0.5895-01cdb92 (2018-05-29T20:07:10+0000)
Starting container bioconda/bioconda-utils-build-env
  using image bioconda/bioconda-utils-build-env@sha256:969aad03c0b5661ed55d2eadb938295706a4cf45191dc47e2dfe4c57f4d2d436

Using build environment variables:
  BASH_ENV=/tmp/.bash_env-localbuild-1527843713
  CI=true
  CIRCLECI=true
  CIRCLE_BRANCH=super-focus
  CIRCLE_BUILD_NUM=
  CIRCLE_JOB=build
  CIRCLE_NODE_INDEX=0
  CIRCLE_NODE_TOTAL=1
  CIRCLE_REPOSITORY_URL=git@github.com:bioconda/bioconda-recipes.git
  CIRCLE_SHA1=050ed5c3673b383aafecc81f25b894e6d1b37e6e
  CIRCLE_SHELL_ENV=/tmp/.bash_env-localbuild-1527843713
  CIRCLE_WORKING_DIRECTORY=~/project

====>> Checkout code
  #!/bin/sh
mkdir -p /root/project && cp -r /tmp/_circleci_local_build_repo/. /root/project
====>> Setup ssh
  #!/bin/bash -eo pipefail
mkdir -p ~/.ssh
ssh-keyscan -H github.com >> ~/.ssh/known_hosts

getaddrinfo github.com: Temporary failure in name resolution
Error: Exited with code 255
Step failed
Task failed
```
Looks to me like some kind of network issue, perhaps from within the docker container?

Since that didn't work I went on to use `bioconda-utils` as [described here](https://bioconda.github.io/contribute-a-recipe.html#bootstrap-method). That gives me the following errors (the same as are shown in the circleCI reports for the commits):

```
[...] some lines removed for brevity
11:10:24 BIOCONDA INFO BUILD START recipes/super-focus, env: CONDA_ALLOW_SOFTLINKS=false;CONDA_BAMTOOLS=2.4.1;CONDA_BOOST=1.64;CONDA_BZIP2=1.
0;CONDA_DEFAULT_ENV=root;CONDA_EXE=/home/ctmr/anaconda3/bin/conda;CONDA_GMP=5.1;CONDA_GSL=2.2;CONDA_HDF5=1.8.17;CONDA_HTSLIB=1.7;CONDA_NCURSE
S=5.9;CONDA_NPY=112;CONDA_PATH_BACKUP=/home/ctmr/anaconda3/envs/py2.7/bin:/home/fredrik.boulund/code/scripts:/home/fredrik.boulund/bin:/home/
ctmr/bin:/usr/local/bin:/home/fredrik.boulund/code/scripts:/home/fredrik.boulund/bin:/home/ctmr/anaconda3/bin:/home/ctmr/bin:/usr/local/bin:/
usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/puppetlabs/bin:/opt/dell/srvadmin/bin;CONDA_PERL=5.22.0;CONDA_PREFIX_1=/home/ctmr/anaco
nda3;CONDA_PROMPT_MODIFIER=(py2.7) ;CONDA_PS1_BACKUP=(py2.7) [\u@\h \W]\$ ;CONDA_PY=27;CONDA_PYTHON_EXE=/home/ctmr/anaconda3/bin/python;CONDA
_R=3.4.1;CONDA_ROOT=/tmp/miniconda/miniconda;CONDA_SHLVL=2;CONDA_XZ=5.2;CONDA_ZLIB=1.2.11;LANG=en_US.UTF-8;MACOSX_DEPLOYMENT_TARGET=10.9
11:10:40 BIOCONDA ERROR COMMAND FAILED: docker run --net host --rm -v /tmp/tmp00st_ps4/build_script.bash:/opt/build_script.bash -v /tmp/minic
onda/miniconda/conda-bld:/opt/host-conda-bld -v /home/fredrik.boulund/code/bioconda-recipes/recipes/super-focus:/opt/recipe -e CONDA_SHLVL=2
-e CONDA_PROMPT_MODIFIER=(py2.7)  -e CONDA_EXE=/home/ctmr/anaconda3/bin/conda -e CONDA_PREFIX_1=/home/ctmr/anaconda3 -e CONDA_PATH_BACKUP=/ho
me/ctmr/anaconda3/envs/py2.7/bin:/home/fredrik.boulund/code/scripts:/home/fredrik.boulund/bin:/home/ctmr/bin:/usr/local/bin:/home/fredrik.bou
lund/code/scripts:/home/fredrik.boulund/bin:/home/ctmr/anaconda3/bin:/home/ctmr/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/u
sr/sbin:/opt/puppetlabs/bin:/opt/dell/srvadmin/bin -e LANG=en_US.UTF-8 -e CONDA_PS1_BACKUP=(py2.7) [\u@\h \W]\$  -e CONDA_PYTHON_EXE=/home/ct
mr/anaconda3/bin/python -e CONDA_DEFAULT_ENV=root -e CONDA_ROOT=/tmp/miniconda/miniconda -e CONDA_ALLOW_SOFTLINKS=false -e CONDA_PY=27 -e CON
DA_HTSLIB=1.7 -e CONDA_BOOST=1.64 -e CONDA_R=3.4.1 -e CONDA_PERL=5.22.0 -e CONDA_NPY=112 -e CONDA_NCURSES=5.9 -e CONDA_GSL=2.2 -e CONDA_GMP=5
.1 -e CONDA_HDF5=1.8.17 -e MACOSX_DEPLOYMENT_TARGET=10.9 -e CONDA_ZLIB=1.2.11 -e CONDA_BZIP2=1.0 -e CONDA_XZ=5.2 -e CONDA_BAMTOOLS=2.4.1 -e H
OST_USER_ID=3215 tmp-bioconda-builder /bin/bash /opt/build_script.bash
11:10:40 BIOCONDA ERROR STDOUT+STDERR:
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
+ source /opt/conda/bin/activate /opt/conda/conda-bld/super-focus_1527844230679/_b_env_placehold_placehold_placehold_placehold_placehold_plac
ehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place
hold_p
+ superfocus_dir=/opt/conda/conda-bld/super-focus_1527844230679/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_
placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/share/sup
er-focus-0.28-0
+ mkdir -p /opt/conda/conda-bld/super-focus_1527844230679/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh
old_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/share/super-foc
us-0.28-0
+ cp -r ./ChangeLog ./conda_build.sh ./COPYING ./db ./focus ./plotting_output ./README.md ./STAMP_input_example ./superfocus__downloadDB.py .
/superfocus.py /opt/conda/conda-bld/super-focus_1527844230679/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl
acehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/share/super
-focus-0.28-0
+ mkdir -p /opt/conda/conda-bld/super-focus_1527844230679/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh
old_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin
+ ln -s /opt/conda/conda-bld/super-focus_1527844230679/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold
_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/share/super-focus-
0.28-0/superfocus.py /opt/conda/conda-bld/super-focus_1527844230679/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placeh
old_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/s
uperfocus.py
+ ln -s /opt/conda/conda-bld/super-focus_1527844230679/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold
_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/share/super-focus-
0.28-0/superfocus_downloadDB.py /opt/conda/conda-bld/super-focus_1527844230679/_b_env_placehold_placehold_placehold_placehold_placehold_place
hold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh
old_p/bin/superfocus_downloadDB.py
+ ln -s /opt/conda/conda-bld/super-focus_1527844230679/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold
_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/share/super-focus-
0.28-0/focus/focus.py /opt/conda/conda-bld/super-focus_1527844230679/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_place
hold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/
focus.py
INFO:conda_build.build:Packaging super-focus-0.28-py27_0
INFO:filelock:Lock 140463344540584 acquired on /opt/conda/locks/L29wdC9yZWNpcGU=
INFO:filelock:Lock 140463344540584 released on /opt/conda/locks/L29wdC9yZWNpcGU=
INFO:filelock:Lock 140463344540584 acquired on /opt/conda/locks/L29wdC9yZWNpcGU=
INFO:filelock:Lock 140463344540584 released on /opt/conda/locks/L29wdC9yZWNpcGU=
INFO:filelock:Lock 140463344540584 acquired on /opt/conda/locks/L29wdC9yZWNpcGU=
INFO:filelock:Lock 140463344540584 released on /opt/conda/locks/L29wdC9yZWNpcGU=
INFO:filelock:Lock 140463344540584 acquired on /opt/conda/locks/L29wdC9yZWNpcGU=
INFO:filelock:Lock 140463344540584 released on /opt/conda/locks/L29wdC9yZWNpcGU=
INFO:filelock:Lock 140463344540584 acquired on /opt/conda/locks/L29wdC9yZWNpcGU=
INFO:filelock:Lock 140463344540584 released on /opt/conda/locks/L29wdC9yZWNpcGU=
INFO:filelock:Lock 140463344539408 acquired on /opt/conda/locks/L29wdC9jb25kYS9jb25k
INFO:filelock:Lock 140463344539408 released on /opt/conda/locks/L29wdC9jb25kYS9jb25k
BUILD START: super-focus-0.28-py27_0
    (actual version deferred until further download or env creation)
Source cache directory is: /opt/conda/conda-bld/src_cache
Downloading source to cache: 0.28.tar.gz
Downloading https://github.com/metageni/SUPER-FOCUS/archive/0.28.tar.gz
Success
Extracting download
BUILD START (revised): super-focus-0.28-py27_0
Package: super-focus-0.28-py27_0
source tree in: /opt/conda/conda-bld/super-focus_1527844230679/work/SUPER-FOCUS-0.28
number of files: 32
Fixing permissions
Making absolute symlink bin/focus.py -> /opt/conda/conda-bld/super-focus_1527844230679/_b_env_placehold_placehold_placehold_placehold_placeho
ld_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol
d_placehold_p/share/super-focus-0.28-0/focus/focus.py relative
Making absolute symlink bin/superfocus.py -> /opt/conda/conda-bld/super-focus_1527844230679/_b_env_placehold_placehold_placehold_placehold_pl
acehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla
cehold_placehold_p/share/super-focus-0.28-0/superfocus.py relative
Making absolute symlink bin/superfocus_downloadDB.py -> /opt/conda/conda-bld/super-focus_1527844230679/_b_env_placehold_placehold_placehold_p
lacehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl
acehold_placehold_placehold_p/share/super-focus-0.28-0/superfocus_downloadDB.py relative
Fixing permissions
Traceback (most recent call last):
  File "/opt/conda/bin/conda-build", line 6, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "/opt/conda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 342, in main
    execute(sys.argv[1:])
  File "/opt/conda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 333, in execute
    noverify=args.no_verify)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/api.py", line 97, in build
    need_source_download=need_source_download, config=config)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/build.py", line 1524, in build_tree
    config=config)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/build.py", line 1159, in build
    built_package = bundlers[output_dict.get('type', 'conda')](output_dict, m, config, env)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/build.py", line 896, in bundle_conda
    create_info_files(metadata, files, config=config, prefix=config.build_prefix)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/build.py", line 503, in create_info_files
    create_info_files_json_v1(m, config.info_dir, prefix, files, files_with_prefix)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/build.py", line 602, in create_info_files_json_v1
    files_json_files = build_info_files_json_v1(m, prefix, files, files_with_prefix)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/build.py", line 582, in build_info_files_json_v1
    "size_in_bytes": os.path.getsize(path),
  File "/opt/conda/lib/python3.6/genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
FileNotFoundError: [Errno 2] No such file or directory: '/opt/conda/conda-bld/super-focus_1527844230679/_b_env_placehold_placehold_placehold_
placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p
lacehold_placehold_placehold_p/bin/superfocus_downloadDB.py'


11:10:40 BIOCONDA ERROR BUILD FAILED recipes/super-focus, CONDA_ALLOW_SOFTLINKS=false;CONDA_BAMTOOLS=2.4.1;CONDA_BOOST=1.64;CONDA_BZIP2=1.0;C
ONDA_DEFAULT_ENV=root;CONDA_EXE=/home/ctmr/anaconda3/bin/conda;CONDA_GMP=5.1;CONDA_GSL=2.2;CONDA_HDF5=1.8.17;CONDA_HTSLIB=1.7;CONDA_NCURSES=5
.9;CONDA_NPY=112;CONDA_PATH_BACKUP=/home/ctmr/anaconda3/envs/py2.7/bin:/home/fredrik.boulund/code/scripts:/home/fredrik.boulund/bin:/home/ctm
r/bin:/usr/local/bin:/home/fredrik.boulund/code/scripts:/home/fredrik.boulund/bin:/home/ctmr/anaconda3/bin:/home/ctmr/bin:/usr/local/bin:/usr
/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/puppetlabs/bin:/opt/dell/srvadmin/bin;CONDA_PERL=5.22.0;CONDA_PREFIX_1=/home/ctmr/anaconda
3;CONDA_PROMPT_MODIFIER=(py2.7) ;CONDA_PS1_BACKUP=(py2.7) [\u@\h \W]\$ ;CONDA_PY=27;CONDA_PYTHON_EXE=/home/ctmr/anaconda3/bin/python;CONDA_R=
3.4.1;CONDA_ROOT=/tmp/miniconda/miniconda;CONDA_SHLVL=2;CONDA_XZ=5.2;CONDA_ZLIB=1.2.11;LANG=en_US.UTF-8;MACOSX_DEPLOYMENT_TARGET=10.9
11:10:42 BIOCONDA ERROR BUILD SUMMARY: of 1 recipes, 1 failed and 0 were skipped. Details of recipes and environments follow.
11:10:42 BIOCONDA ERROR BUILD SUMMARY: FAILED recipe super-focus-0.28-py27_0.tar.bz2, environment CONDA_PY=27;CONDA_HTSLIB=1.7;CONDA_BOOST=1.
64;CONDA_R=3.4.1;CONDA_PERL=5.22.0;CONDA_NPY=112;CONDA_NCURSES=5.9;CONDA_GSL=2.2;CONDA_GMP=5.1;CONDA_HDF5=1.8.17;MACOSX_DEPLOYMENT_TARGET=10.
9;CONDA_ZLIB=1.2.11;CONDA_BZIP2=1.0;CONDA_XZ=5.2;CONDA_BAMTOOLS=2.4.1
```

I don't know what's wrong, but I'm guessing I made something wrong in my `build.sh` script? Not sure how to proceed, would really appreciate a nudge in the right direction :) 
@bioconda/core

### CODE REVIEW

**Comment by daler** [comment]
@boulund I think the issue is that in the source tarball, the script name is `superfocus__downloadDB.py` with *two* underscores.

**Comment by boulund** [comment]
@daler, aha! Of course! I modelled my `build.sh` after changes in a PR that hadn't been merged yet. Thanks for pointing that out to me! I'll fix it first thing tomorrow morning!

**Comment by boulund** [comment]
@bioconda/core 
This is my first recipe, ready for review. Let me know how you want me to proceed!

**Comment by bgruening** [comment]
Looks good thanks @boulund!

**Pull request merged**
