### PR TITLE
Add OSX build for bioconductor-rhtslib.

### PR DESCRIPTION
**Pull request by acaprez**
* [X] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [X] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

Add OS X build for bioconductor-rhtslib.  xref: #3373

### CODE REVIEW

**Comment by bgruening** [comment]
@acaprez I think the problem is here: https://travis-ci.org/bioconda/bioconda-recipes/jobs/189332788#L517
Maybe libgfortran can help, or simply gcc on OSX?

**Comment by acaprez** [comment]
@bgruening - it's actually an issue caused by the OS X SIP they added in El Capitan.  The `libgcc` package is getting pulled in as an R dependency, so `libgfortran` is there.  As part of SIP though, the `DYLD_LIBRARY_PATH` variable gets ignored/purged.  I disabled SIP on my dev VM a while back; that's why it build ok for me there.  The Travis CI VM's apparently still have it enabled though.

I was able to work around it by patching the `Makevars` file to pass an `rpath` option to the linker.  But in testing, I ran into an issue where `conda build` seems to ignore patch files if the `--dirty` flag is used.  Building on my local VM (with SIP re-enabled) failed using `simulate-travis.py` since it uses `--dirty`.  The same `conda build` command worked without it.  I went ahead and pushed the patch just now, but it's likely it still won't build since `--dirty` is used.

**Comment by bgruening** [comment]
@acaprez sorry what is SIP? :)
Thanks for the detective work!

**Comment by acaprez** [comment]
Sorry, System Integrity Protection: https://support.apple.com/en-us/HT204899.  Basically, root is no longer root - there are certain locations not even root can change.  It also includes other protections, one of which is to ignore `DYLD_LIBRARY_PATH` (Mac equivalent of `LD_LIBRARY_PATH`).  It's caused headaches with a lot of OS X packages, including Conda:  https://github.com/ContinuumIO/anaconda-issues/issues/498.

As I mentioned, I was able to get around it by patching initially, but it appears to be a bug in `conda build` to ignore patch files when `--no-build-id` is used.  Haven't had a chance to dig through open issues for `conda` to see if anyone else has reported it.

**Comment by bgruening** [comment]
Uh is this what we have to fight from now on regularly? If so maybe we should use an older OSX image on Travis?

**Comment by acaprez** [comment]
That might be a viable option, yeah.  The concern would obviously be that packages would build and test ok on Travis, but then not work on OS X 10.11+.  Basically any package that uses `DYLD_LIBRARY_PATH` at runtime would break.  Since `conda` does the relative rpath conversion at build time normally they shouldn't be, unless it's via custom `activate.d/deactivate.d` scripts or the like.

It should be possible in theory to patch packages to build using the current OS X image and not rely on `DYLD_LIBRARY_PATH`, but it is more effort.  In any event, I'd be interested in getting input from others familiar with OS X before any changes are made.

**Pull request merged**
