### PR TITLE
Bump build number b/c we are rebuilding against libseq 1.9.3.  Also

### PR DESCRIPTION
**Pull request by molpopgen**
change to use cxx as the compiler.

* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [ ] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [X] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by molpopgen** [comment]
@johanneskoester -- Requesting help/review here.  Linting tests are failing for most/all open PRs.  Unable to parse out the issue from the Circle CI output.

**Comment by kyleabeauchamp** [comment]
@bgruening  did someone un-blacklist a bunch of recipes that fail linting?  

Do we just need to re-add those recipes to https://github.com/bioconda/bioconda-recipes/blob/master/build-fail-blacklist ?

**Comment by molpopgen** [comment]
> Do we just need to re-add those recipes to https://github.com/bioconda/bioconda-recipes/blob/master/build-fail-blacklist ?

That may be the case.  However, I don't think this package was blacklisted.  If it was, I want to fix it!

My other open PR did end up on the blacklist, but I was never contacted about that, and the issue is almost certainly that the compiler was mis-specified as 'c' (when it should be 'cxx') by whomever made those updates.

**Comment by bgruening** [comment]
You just need to merge master into your branch this will fix the linting problem.

**Comment by bgruening** [comment]
> My other open PR did end up on the blacklist, but I was never contacted about that, and the issue is almost certainly that the compiler was mis-specified as 'c' (when it should be 'cxx') by whomever made those updates.

That was most likely me - as I try to update all recipes to new cb3 syntax. Bare with me that I'm not trying to read all 4000 recipes and do this semi-automatic and fix packages on bulk when I see errors.

**Pull request merged**
