### PR TITLE
update to new version

### PR DESCRIPTION
**Pull request by macmanes**
the old version had a bug whereby some reads were dropped. See https://github.com/mourisl/Rcorrector/issues/12

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by jpuritz** [comment]
Might have to update `build.sh` with some of the flags noted [here](https://bioconda.github.io/troubleshooting.html#zlib-errors)

**Comment by macmanes** [comment]
Hi @jpuritz I don't see errors related to `zlib`, so not sure if adding stuff in that link are going to help. In general, this is a very minor bump in version, but a critically important one. 1.0.2 has a bug which drops reads from R2. This bug is fixed in `1.0.3`. I'm not sure why `build.sh` should change, but then again, I know literally *nothing* about this.

**Comment by macmanes** [comment]
OK, I'm stumped. Reading the CircleCI log does not help me understand what is wrong here. Again, a minor fix, should not require substantial changes to the build process.

**Comment by jpuritz** [comment]
I’ll take a look again today. Even though this is a minor code update,
Bioconda has begun switching to the new Conda build system which requires
some setting of environmental variable for proper compilation.

-- 
Jon Puritz

**Comment by jpuritz** [comment]
So, the makefile had some non-standard flags, so I had to modify it to add the `-L$PREFIX/lib` to the compiler.

**Pull request merged**
