### PR TITLE
ngs-bits 2019_05

### PR DESCRIPTION
**Pull request by marc-sturm**
:information_source:
If this is your first pull request to Bioconda please ping `@bioconda/core` so it can be reviewed and to request being added as a member of the Bioconda team. Members of the Bioconda team are able to merge their own pull requests once tests and linting have passed.

----------------

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by marc-sturm** [comment]
@bioconda/core Any idea why qmake cannot find g++? It worked with the same setup  on 9th of April when I built the last version. Any hints are appreciated...

**Comment by dpryan79** [comment]
There is no `g++`, but there's a `${CXX}`.

**Comment by marc-sturm** [comment]
@dpryan79 Thanks for the hint.

I already tried to use the environment variable in the build.sh:
qmake ../src/tools.pro CONFIG-=debug CONFIG+=release DEFINES+=QT_NO_DEBUG_OUTPUT QMAKE_CXX=${CXX}
It seems to have no effect.

Now I added debug output, perhaps then it becomes clear why it fails...

**Comment by marc-sturm** [comment]
@dpryan79 Hi Ryan, any idea what's wrong with the Qt version string? Thanks, Marc

**Comment by dpryan79** [comment]
Maybe this has something to do with recipes being pinned to `qt` 5.9 already, so you should be able to just omit `>=5.9` entirely.

**Comment by marc-sturm** [comment]
@dpryan79 Thanks a lot for your help! Everything works now. Is the recipe ok like this? If so, can you merge it?

**Comment by dpryan79** [comment]
:+1: from me!

**Comment by dpryan79** [comment]
Merged, thanks @marc-sturm!

**Pull request merged**
