### PR TITLE
Bumped perl-set-intervaltree version

### PR DESCRIPTION
**Pull request by micknudsen**
* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [X] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [X] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by rvalieris** [comment]
ah looks like a dependency is missing, ExtUtils::CppGuess.

you should be able to use "conda skeleton cpan  ExtUtils::CppGuess" to include it.

**Comment by micknudsen** [comment]
Does ExtUtils::CppGuess belong in bioconda? Maybe conda-forge would be more appropriate?

**Comment by rvalieris** [comment]
yes it would, but that would require migrating all the dependencies as well, we do have plans to migrate these packages at some point but no timeline yet.
I think its ok to include this package now so that star-fusion can be used.

**Comment by rvalieris** [comment]
you can now add the dependency `perl-extutils-cppguess` on build and run requirements.

**Pull request merged**
