### PR TITLE
update build instructions in readme

### PR DESCRIPTION
**Pull request by daler**
* [ ] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [x] This PR does something else (explain below).

update readme to reflect recent build changes

### CODE REVIEW

**Comment by acaprez** [comment]
Hmm, so how do you specify to just build a single package inside the container now with the new system?

**Comment by bgruening** [comment]
@acaprez this will all be very easy as soon as we merge this https://github.com/bioconda/bioconda-utils/pull/18
We are currently busy with doing the R-rebuild, but I think the PR from @daler is the next thing we would love to get done + mulled based testing.

**Comment by daler** [comment]
@acaprez you "just" need to pass `--packages` to `bioconda-utils build`.

 `travis-run.sh` should ideally accept optional args and pass them to `--packages`, but for now you can do this ugly thing:

```bash
#!/bin/bash
export SUBDAGS=1
export TRAVIS_OS_NAME=linux
export TRAVIS_BRANCH=0
export TRAVIS_PULL_REQUEST=false
export SUBDAG=0
# set this to match .travis.yml
export BIOCONDA_UTILS_TAG=2f8fa70

# can be a glob
PACKAGES="pkg-name"

docker run -e SUBDAG -e SUBDAGS -e TRAVIS_BRANCH -e TRAVIS_PULL_REQUEST -e ANACONDA_TOKEN \
    -v `pwd`:/bioconda-recipes condaforge/linux-anvil /bin/bash -c \
    "cd /bioconda-recipes; \
    conda install --file scripts/requirements.txt; \
    pip install git+https://github.com/bioconda/bioconda-utils.git@$BIOCONDA_UTILS_TAG; \
    pip install git+https://github.com/bioconda/conda-build.git@fix-build-skip-existing; \
    bioconda-utils build recipes config.yml --loglevel=info --packages $PACKAGES"
```

**Comment by acaprez** [comment]
@daler yeah, that's essentially what I ended up doing to get it to work.  As you mentioned, it would be nice if the `travis-run.sh` script accepts args to pass along, but this will work for now anyway.

**Pull request merged**
