### PR TITLE
MicroHapDB 0.2 -> 0.3

### PR DESCRIPTION
**Pull request by standage**
Update MicroHapDB from 0.2 to 0.3

----------------

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by standage** [comment]
I would love to be added to @bioconda/core so I can manage this recipe.

**Comment by standage** [comment]
@bioconda/core I forgot to increment the build number on this update, and thus MicroHapDB 0.3 isn't available from bioconda. Will opening a PR to fix this be sufficient to fix the problem, or will it require manual intervention?

**Comment by dpryan79** [comment]
You shouldn't need to increment the build bumber, new versions should have build numbers starting at 0.

**Comment by dpryan79** [comment]
Oh, well that's weird. It looks like this was uploaded, but for some reason it's not showing up. I'll have to dig into the nightly upload job to see why this isn't getting uploaded then.

**Comment by standage** [comment]
> You shouldn't need to increment the build bumber, new versions should have build numbers starting at 0.

Sorry, n00b mistake. I misinterpreted the purpose of the build number, and assumed it was the problem since the package hadn't showed up.

**Comment by epruesse** [comment]
> I would love to be added to @bioconda/core so I can manage his recipe.

/core privileges are really only for dealing with the infrastructure, you don't need that to become a package maintainer. You are welcome to add yourself to `extra: recipe-maintainers:` for MicroHapDB.

**Comment by standage** [comment]
Thanks @epruesse. I misinterpreted the message at the end of https://github.com/bioconda/bioconda-recipes/blob/master/.github/welcome_new_contributor.md.

**Comment by dpryan79** [comment]
I'll try to clarify that a bit https://github.com/bioconda/bioconda-recipes/pull/15167 :)

**Pull request merged**
