### PR TITLE
add nucleosome prediction tool

### PR DESCRIPTION
**Pull request by bgruening**
- [x] I have read the guidelines above.
- [x] This PR adds a new recipe.
- [ ] This PR updates an existing recipe.
- [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by bgruening** [comment]
@johanneskoester @daler any idea about: https://travis-ci.org/bioconda/bioconda-recipes/jobs/162440037#L492

Unfortunately, I could not find the source for the included binary so I need to ship it. But the error looks strange, I though that a binary compiled on an old system will always run on a new one? 
Including libgcc as run time dependency will include libstdc++.so.6 - not libstdc++.so.5. Symlinking libstdc++.so.6 to libstdc++.so.5 also does not work. Any idea how to fix this? Where do I get libstdc++.so.5?

**Comment by kyleabeauchamp** [comment]
Have you been able to run the binary manually on your machine or manually in the container?

**Comment by bgruening** [comment]
On my machine yes, but only after install `libstdc++5`.

**Comment by johanneskoester** [comment]
We have migrated our build system from Travis CI to Circle CI. If you would like to continue working on this PR, please update with latest upstream master and reopen this PR.

**Pull request closed without merging**
