### PR TITLE
Update seq-to-first-iso to 1.0.0

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`seq-to-first-iso`](https://bioconda.github.io/recipes/seq-to-first-iso/README.html): **0.5.1** &rarr; **1.0.0**

[install with bioconda](http://bioconda.github.io/recipes/seq-to-first-iso/README.html) [Conda](https://anaconda.org/bioconda/seq-to-first-iso/files)

Info | Link
-----|-----
Recipe | [`recipes/seq-to-first-iso`](https://github.com//bioconda/bioconda-recipes/tree/bump/seq_to_first_iso/recipes/seq-to-first-iso) (click to view/edit other files)
Releases |[https://github.com/pierrepo/seq-to-first-iso/tags](https://github.com/pierrepo/seq-to-first-iso/tags)
Author | @pierrepo
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by pierrepo** [comment]
Dear Bioconda mainteners,

If I understand correctly, this pull request has been created automatically upon the creation of a new release on GitHub.
That is fine. Thank you.
However could you please tell me how I can update the `meta.yml` of this recipe?  I'd like to slightly improve  the description of the package. I tried to follow this guideline:
https://bioconda.github.io/contributor/updating.html
but if failed (`bioconda-utils: error: invalid choice: 'update'`).

**Comment by dpryan79** [comment]
I can add you to the bioconda team if you'd like to maintain the recipe for that package :)

**Comment by dpryan79** [comment]
Regarding the `update` command, it was renamed to `autobump` and apparently we still need to fix the documentation.

**Comment by pierrepo** [comment]
@dpryan79 yes sure, you can add me to the bioconda team so that I can maintain this recipe.
But do not give me too much rights, I'm quite a newbie with bioconda :stuck_out_tongue_winking_eye:

**Comment by pierrepo** [comment]
Thanks @dpryan79  
Do you have guidelines/recommendations/tips for bioconda team members?

**Comment by dpryan79** [comment]
@pierrepo Please have a look at the guidelines here :)  https://bioconda.github.io/contributor/guidelines.html

**Comment by dpryan79** [comment]
@BiocondaBot please merge

**Comment by pierrepo** [comment]
@bioconda-bot please merge

**Pull request merged**
