### PR TITLE
Added recipe for igv-reports

### PR DESCRIPTION
**Pull request by micknudsen**
:information_source:
If this is your first pull request to Bioconda please ping `@bioconda/core` so it can be reviewed and to request being added as a member of the Bioconda team. Members of the Bioconda team are able to merge their own pull requests once tests and linting have passed.

----------------

* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [X] This PR adds a new recipe.
* [X] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by micknudsen** [comment]
I added this recipe, because `igv-reports` is needed by `star-fusion` when run with certain options. However, it turns out that v0.9.0 is incompatible with `star-fusion`. The older version v0.2.1 (the only other version on PyPi) is needed. Is it possible to add this older version to bioconda, too?

**Comment by dpryan79** [comment]
@micknudsen Yes, you can create a `0.2.1` subdirectory and put a recipe for that version there.

**Comment by epruesse** [comment]
@biocondabot recheck

Do you want to add the 0.2.1 here or add it in another PR? I think this is ready to merge.

**Comment by micknudsen** [comment]
@epruesse Oh, I didn't realize that I could do it all in one go, so I was waiting for the merge. I have now added a recipe for the older version.

**Comment by dpryan79** [comment]
Thanks @micknudsen, shall we add you to bioconda too?

**Comment by micknudsen** [comment]
@dpryan79 That would be awesome! I promise to be careful before I merge something 😄

**Pull request merged**
