### PR TITLE
update blast osx build

### PR DESCRIPTION
**Pull request by rpetit3**
Trying to enable OSX build on mac to see what happens

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by boratyng** [comment]
Hi @rpetit3, I cannot find your error messages for the Mac build, but I suspect that the problem may be the OpenMP library. There have been problems with BLAST and OpenMP on a Mac. Also, Magic-BLAST is using most of the same code as BLAST and it seems to be building on a Mac, so you may find something useful there: https://github.com/bioconda/bioconda-recipes/tree/master/recipes/magicblast.

**Comment by rpetit3** [comment]
Thank you @boratyng I'll try removing open-mp

**Comment by rpetit3** [comment]
Some progress bu failling here: https://dev.azure.com/bioconda/bioconda-recipes/_build/results?buildId=31973&view=logs&j=1b052f1d-4456-52f0-9d43-71c4c5bd734d&t=edc48dcd-1fc2-5e3b-7036-7be9cea00123&l=1579

Only thing I really have to work with is this:

```
ERROR: ./build-system/project_tree_builder/project_tree_builder does not work
```

**Comment by boratyng** [comment]
This is am NCBI build system utility. I talked to NCBI build team and they suggested to use cmake. I would like to try a few things. Should I push changes to your PR or open a new one?

**Comment by rpetit3** [comment]
If you are able to push by all means go for it, but also if its easier to just create a new PR, do it and feel free to request me as a reviewer

**Pull request closed without merging**
