### PR TITLE
Update anvio-minimal to v6.2

### PR DESCRIPTION
**Pull request by meren**
Updates the anvio-minimal recipe to match the latest release of anvi'o, a software platform directly relevant to the biological sciences.

### CODE REVIEW

**Comment by druvus** [comment]
@dpryan79 Do you why we are running into the pypy dependency issue when python is specified to 3.6? Similar issue as was also seen in #21215

**Comment by dpryan79** [comment]
I think the combination of the skip with a package that should have been noarch confused conda-build. The pypy stuff should be mostly fixed now, but if conda-build gets confused I think that still pops up. In general, the "skip" syntax should only be used in the case that there are compilers getting used.

**Comment by meren** [comment]
Thank you both very much for your help with this, @druvus and @dpryan79. I will now try to relax the dependency requirement for one package (`illumina-utils`, which has been failing due to `pypy`) and see if the recipe continues to pass the checks.

I really appreciate the help. Thank you.

**Comment by meren** [comment]
@BiocondaBot please fetch artifacts

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Comment by meren** [comment]
Hi @dpryan79, 

Thank you for merging this. Although, I was still testing the CircleCI built image to see if there are any libraries that require specific versions :)

I just realized that it is indeed the case for `cherrypy` and `snakemake`, and they must be set to the following two versions:

```
cherrypy ==8.0.0
snakemake ==5.10.0
```

I guess I need to send another PR with correct versions after increasing the build number, is it correct?

Thank you for your help,

**Comment by dpryan79** [comment]
Yes, please just open a new PR and we can update that.

**Comment by meren** [comment]
Thank you, @dpryan79. The updated PR is at #21281.

**Pull request merged**
