### PR TITLE
Update bigscape to 1.1.4

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`bigscape`](https://bioconda.github.io/recipes/bigscape/README.html): **1.1.3** &rarr; **1.1.4**

[install with bioconda](http://bioconda.github.io/recipes/bigscape/README.html) [Conda](https://anaconda.org/bioconda/bigscape/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/bigscape`](https://github.com//bioconda/bioconda-recipes/tree/bump/bigscape/recipes/bigscape) (click to view/edit other files)
Summary | Biosynthetic Genes Similarity Clustering and Prospecting Engine.
Home | [https://github.com/medema-group/BiG-SCAPE](https://github.com/medema-group/BiG-SCAPE)
Releases |[https://github.com/medema-group/BiG-SCAPE/tags](https://github.com/medema-group/BiG-SCAPE/tags)
Author | `@medema-group`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by dpryan79** [comment]
Xref: https://github.com/bioconda/bioconda-recipes/pull/34326

**Comment by loraine-gueguen** [comment]
>Was there anything else that you saw that needed fixing?
No thanks. It can be merged now :-)

**Comment by loraine-gueguen** [comment]
@BiocondaBot please add label

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@BiocondaBot please merge

**Comment by dpryan79** [comment]
@BiocondaBot please merge

**Comment by dpryan79** [comment]
@BiocondaBot please fetch artifacts

**Comment by dpryan79** [comment]
@BiocondaBot please merge

**Pull request merged**
