### PR TITLE
Add recipe for Augustus 3.3.2

### PR DESCRIPTION
**Pull request by npavlovikj**
:information_source:
Bioconda has finished the [GCC7 migration](https://github.com/bioconda/bioconda-recipes/issues/13578). If you are dealing with C/C++ or Python package it can be that you need to rebuild other dependent packages. [Bioconda utils - update-pinning](https://bioconda.github.io/updating.html#updating-recipes-for-a-pinning-change) will assist you with that. If you have any questions please use [issue 13578](https://github.com/bioconda/bioconda-recipes/issues/13578).

----------------

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by npavlovikj** [comment]
@bioconda/osx , I would appreciate any help with the OSX recipe. The current error message is:
_clang-4.0: warning: argument unused during compilation: '-p' [-Wunused-command-line-argument]
ld: library not found for -lcrt0.o
clang-4.0: error: linker command failed with exit code 1 (use -v to see invocation)_
when "_filterBam_" is being compiled (the Makefiles for it are patched to work on Linux).

I am not an OSX user and will probably need some time to figure this out on my own, so if there is something that is obviously wrong and stands out to you, please let me know.

**Comment by acaprez** [comment]
Remove the `-static` argument from the `CFLAGS` line in your `filterBam.src.makefile.patch`.  That is, change
`+CFLAGS += -std=c++11 -Wall -O2 -static # -g -p -g -ggdb`
to
`+CFLAGS += -std=c++11 -Wall -O2 # -g -p -g -ggdb`

**Comment by npavlovikj** [comment]
Thanks @acaprez ! 

I added `-static` to fix the Linux error that is now showing (adding `-fPIC` or `-fno-pie` didn't fix it):
_/opt/conda/conda-bld/augustus_1553886792730/_build_env/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: /opt/conda/conda-bld/augustus_1553886792730/_build_env/bin/../x86_64-conda_cos6-linux-gnu/sysroot/usr/lib/../lib/gcrt1.o: relocation R_X86_64_32S against symbol `__libc_csu_fini' can not be used when making a PIE object; recompile with -fPIC_

If removing `-static` fixes the OSX error, should I have 2 different patches then?

**Comment by acaprez** [comment]
Sorry, yes.  I should've explained that better.  You should remove `-static` on OS X only.

**Comment by npavlovikj** [comment]
Many thanks for the help Adam - that did the trick! Does the recipe look ok to you for merging now?

**Comment by acaprez** [comment]
You might want to include the license file at `src/LICENCE.TXT`, otherwise it looks ok to me.

**Pull request merged**
