### PR TITLE
Update agat to 0.0.3

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`agat`](https://bioconda.github.io/recipes/agat/README.html): **0.0.1** &rarr; **0.0.3**

[install with bioconda](http://bioconda.github.io/recipes/agat/README.html) [Conda](https://anaconda.org/bioconda/agat/files)

Info | Link
-----|-----
Recipe | [`recipes/agat`](https://github.com//bioconda/bioconda-recipes/tree/bump/agat/recipes/agat) (click to view/edit other files)
Releases |[https://github.com/NBISweden/AGAT/tags](https://github.com/NBISweden/AGAT/tags)
Recipe Maintainer(s) | @juke34
Author | `@NBISweden`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by Juke34** [comment]
I don't see why one check has failed. I don't succeed to reproduce the problem, could we just rerun the test?

**Comment by HadrienG** [comment]
@BiocondaBot rebuild

**Comment by dpryan79** [comment]
I never implemented a "rebuild" command in the current implementation of the bot (I just hacked it together last week). I've rerun this at least once and it fails the same way each time. One possibility would be to remove `make test` from the build script so it will presumably build through and then test locally why there's one test failing.

**Comment by Juke34** [comment]
I found the problem, (related to Bioperl bug that return codon table 1 when 0 is asked... it has been fixed recently) I have added a fix to avoid this trap. I will make a new release 0.0.3

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Pull request merged**
