### PR TITLE
Add arm build for Salmon

### PR DESCRIPTION
**Pull request by ewels**
Trying this out.. Did I do it right @rpetit3?

This is the first (and simplest) from our arm tests over at [seqeralabs/conda-recipes](https://github.com/seqeralabs/conda-recipes/blob/master/recipes/salmon/meta.yaml). This one worked without modification, so hoping that no other changes are required here.

Tagging @pabloaledo

<details>

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

### General instructions

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

### Instructions for avoiding API, ABI, and CLI breakage issues
Conda is able to record and lock (a.k.a. pin) dependency versions used at build time of other recipes.
This way, one can avoid that expectations of a downstream recipe with regards to API, ABI, or CLI are violated by later changes in the recipe.
If not already present in the meta.yaml, make sure to specify `run_exports` (see [here](https://bioconda.github.io/contributor/linting.html#missing-run-exports) for the rationale and comprehensive explanation).
Add a `run_exports` section like this:

```yaml
build:
  run_exports:
    - ...

```

with `...` being one of:

| Case                             | run_exports statement                                               |
| -------------------------------- | ------------------------------------------------------------------- |
| semantic versioning              | `{{ pin_subpackage("myrecipe", max_pin="x") }}`     |
| semantic versioning (0.x.x)      | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}`   |
| known breakage in minor versions | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| known breakage in patch versions | `{{ pin_subpackage("myrecipe", max_pin="x.x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| calendar versioning              | `{{ pin_subpackage("myrecipe", max_pin=None) }}`    |

while replacing `"myrecipe"` with either `name` if a `name|lower` variable is defined in your recipe or with the lowercase name of the package in quotes.

### Bot commands for PR management

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

Note that the <code>@BiocondaBot please merge</code> command is now depreciated. Please just squash and merge instead.

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>
</details>

### CODE REVIEW

**Comment by rpetit3** [comment]
On phone, add run exports and increment build number

**Comment by rpetit3** [comment]
From CI

```
15:17:23 BIOCONDA INFO (OUT) configure: error: libbzip2 development files not found.
15:17:23 BIOCONDA INFO (OUT) 
15:17:23 BIOCONDA INFO (OUT) This is used within CRAM.  If you wish to compile io_lib without bzip2
15:17:23 BIOCONDA INFO (OUT) support, rerun configure with the --disable-bz2 option.
15:17:23 BIOCONDA INFO (OUT) 
15:17:23 BIOCONDA INFO (OUT) make[2]: *** [CMakeFiles/libstadenio.dir/build.make:92: libstadenio-prefix/src/libstadenio-stamp/libstadenio-configure] Error 1
15:17:23 BIOCONDA INFO (OUT) make[1]: *** [CMakeFiles/Makefile2:275: CMakeFiles/libstadenio.dir/all] Error 2
15:17:23 BIOCONDA INFO (OUT) make: *** [Makefile:166: all] Error 2
15:17:23 BIOCONDA INFO (OUT) make[2]: Leaving directory '$SRC_DIR/build'
15:17:23 BIOCONDA INFO (OUT) make[1]: Leaving directory '$SRC_DIR/build'
```

**Comment by pabloaledo** [comment]
```
diff --git a/recipes/salmon/build.sh b/recipes/salmon/build.sh
index 027cadd..54b2587 100644
--- a/recipes/salmon/build.sh
+++ b/recipes/salmon/build.sh
@@ -12,6 +12,7 @@ cmake -DCMAKE_BUILD_TYPE=RELEASE \
       -DCMAKE_OSX_DEPLOYMENT_TARGET=10.11 \
       -DCMAKE_INSTALL_PREFIX:PATH=$PREFIX \
       -DBoost_NO_SYSTEM_PATHS=ON \
+      -DLIBSTADEN_LDFLAGS=-L$PREFIX/lib \
       -DNO_IPO=TRUE \
       ..
 make VERBOSE=1
diff --git a/recipes/salmon/fixhtscodecs.patch b/recipes/salmon/fixhtscodecs.patch
new file mode 100644
index 0000000..c6d2e2a
--- /dev/null
+++ b/recipes/salmon/fixhtscodecs.patch
@@ -0,0 +1,27 @@
+diff --git a/CMakeLists.txt b/CMakeLists.txt
+index aa9257b..7e03857 100644
+--- a/CMakeLists.txt
++++ b/CMakeLists.txt
+@@ -793,12 +793,17 @@ if (NOT LIBSTADENIO_FOUND)
+   message("==================================================================")
+   externalproject_add(libstadenio
+     DOWNLOAD_DIR ${CMAKE_CURRENT_SOURCE_DIR}/external
+-    DOWNLOAD_COMMAND curl -k -L https://github.com/jkbonfield/io_lib/releases/download/io_lib-1-14-15/io_lib-1.14.15.tar.gz -o staden-io_lib-v1.14.15.tar.gz &&
+-      ${SHASUM} 20814c4365e1e2fe6630fb11d0df370dec4c5688af3871de7f1cb0129671401e staden-io_lib-v1.14.15.tar.gz &&
+-      mkdir -p staden-io_lib-1.14.15 &&
+-      tar -xzf staden-io_lib-v1.14.15.tar.gz --strip-components=1 -C staden-io_lib-1.14.15 &&
++    DOWNLOAD_COMMAND curl -k -L https://github.com/jkbonfield/io_lib/releases/download/io_lib-1-15-0/io_lib-1.15.0.tar.gz -o staden-io_lib-v1.15.0.tar.gz &&
++      ${SHASUM} ad343dac7c77086db1b54585c5887b26eda6430d1639d111dd3304c3b749494f staden-io_lib-v1.15.0.tar.gz &&
++      mkdir -p staden-io_lib-1.15.0 &&
++      tar -xzf staden-io_lib-v1.15.0.tar.gz --strip-components=1 -C staden-io_lib-1.15.0 &&
+       rm -fr staden-io_lib &&
+-      mv -f staden-io_lib-1.14.15 staden-io_lib
++      mv -f staden-io_lib-1.15.0 staden-io_lib &&
++      curl -k -L https://github.com/samtools/htscodecs/releases/download/v1.6.0/htscodecs-1.6.0.tar.gz -o htscodecs-1.6.0.tar.gz &&
++      mkdir -p htscodecs-1.6.0 &&
++      tar -xzf htscodecs-1.6.0.tar.gz --strip-components=1 -C htscodecs-1.6.0 &&
++      rm -fr staden-io_lib/htscodecs &&
++      mv -f htscodecs-1.6.0 staden-io_lib/htscodecs
+     SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/external/staden-io_lib
+     INSTALL_DIR ${CMAKE_CURRENT_SOURCE_DIR}/external/install
+     CONFIGURE_COMMAND ./configure --enable-shared=no --without-libcurl --prefix=<INSTALL_DIR> LDFLAGS=${LIBSTADEN_LDFLAGS} CFLAGS=${LIBSTADEN_CFLAGS} CC=${CMAKE_C_COMPILER} CXX=${CMAKE_CXX_COMPILER}
diff --git a/recipes/salmon/meta.yaml b/recipes/salmon/meta.yaml
index 1605c79..1365303 100644
--- a/recipes/salmon/meta.yaml
+++ b/recipes/salmon/meta.yaml
@@ -10,7 +10,8 @@ build:
 source:
   url: https://github.com/COMBINE-lab/salmon/archive/v{{ version }}.tar.gz
   sha256: 450d953a5c43fe63fd745733f478d3fbaf24d926cb52731fd38ee21c4990d613
-
+  patches:
+    - fixhtscodecs.patch
 
 requirements:
   build:

```

**Comment by ewels** [comment]
Thanks @pabloaledo! I asked ChatGPT to explain the diff to me 😆 

> This patch updates the build script for the Salmon project to link against the LIBSTADEN library in a specific location, upgrades the libstadenio version from 1.14.15 to 1.15.0, and incorporates the htscodecs library version 1.6.0 by applying a new patch file, aiming to improve the software's compatibility and functionality with these external libraries.

@rpetit3 / @rob-p / @jkbonfield - any opinions on where this patch from  should live? It's somewhere in the no-man's land between salmon, samtools and htscodecs. Not sure whether it's best placed here in bioconda, or better to go upstream.

**Comment by jkbonfield** [comment]
I think it's a confusingly named patch as it's not fixing htscodecs, nor the staden io-lib library.  It just seems to be a modification to Salmon's build system by downloading and libraries and modifying the link locations.  This surely goes against the philosophy of using tracked dependencies.  Tools shouldn't need to have their own separate copies of things.

**Comment by jkbonfield** [comment]
Io_lib may not have the htscodecs submodule updated in git, but this is largely irrelevant.  It's something I update when I make a release, but just how say samtools doesn't make a new release just because libdeflate has updated, nor should io_lib automatically get a new release just because a library it depends on has updated.  The use of git submodules doesn't detract from it being an external dependency.  It's simply a nicety for ease given htscodecs is rarely installed (unlike zlib, libbz2, etc).  It can work fine with other directories or system locations.

So... io_lib has a dependency on htscodecs, meaning conda should add that as a dependency (and I think does), but it doesn't depend on a specific version as given semantic versioning rules it's maintaining API compatibility given the lack of major version bumps.

**Comment by ewels** [comment]
Closing in favour of https://github.com/bioconda/bioconda-recipes/pull/46499 (see also https://github.com/COMBINE-lab/salmon/pull/916 )

**Pull request closed without merging**
