### PR TITLE
WIP: Add primerclip

### PR DESCRIPTION
**Pull request by willemdek11**
Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it. Note that if you are not already a member of the bioconda project (meaning that you can't add this label), please ping `@bioconda/core` so that your PR can be reviewed and merged (please note if you'd like to be added to the bioconda project). Please see https://github.com/bioconda/bioconda-recipes/issues/15332 for more details.

* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [X] This PR adds a new recipe.
* [X] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by dpryan79** [comment]
This is marked as beta and the upstream source has yet to tag a release. Please ask them to address both of these in order for us to be able to redistribute primerclip.

**Comment by willemdek11** [comment]
Release v0.3.8 created.

@Smeds @irishjonathan

**Comment by dpryan79** [comment]
@bioconda-bot update

**Comment by willemdek11** [comment]
> Will you do a pull-request for this soon?

@Smeds I tried to fix the conda package before, but couldn't make it work. So'll need some help. The pull request is already open though. So as soon as it works it can be merged.

**Comment by dpryan79** [comment]
@bioconda-bot merge

**Pull request merged**
