### PR TITLE
Phast

### PR DESCRIPTION
**Pull request by RomainFeron**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.

PHAST was not compiling with lapack, most commands were not working.
I could not get it to work with the clapack package from conda-forge, because PHAST relies on the directory structure of clapack to compile. It was easier to download and compile clapack in the recipe.

I've also cleaned up the recipe a bit (added a license file)

### CODE REVIEW

**Comment by RomainFeron** [comment]
Sorry for PRing before making sure this build passes tests, I thought macOS was blocked for some reason.
@dpryan79  I have a question about the license file: in a previous PR from another recipe, someone added the license file during review. But here you removed it; should it be included or not?
Thanks!

**Comment by dpryan79** [comment]
There's a copy in the source tarball, so the `license_file:` entry can just use that.

**Comment by RomainFeron** [comment]
Looks like it's now compiling on macOS, is it good to merge @dpryan79 ?

**Comment by dpryan79** [comment]
@bioconda-bot please fetch artifacts

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Pull request merged**
