### PR TITLE
Update ont-fast5-api to 3.1.3

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`ont-fast5-api`](https://bioconda.github.io/recipes/ont-fast5-api/README.html): **3.0.1** &rarr; **3.1.3**

[install with bioconda](http://bioconda.github.io/recipes/ont-fast5-api/README.html) [Conda](https://anaconda.org/bioconda/ont-fast5-api/files)

Info | Link
-----|-----
Recipe | [`recipes/ont-fast5-api`](https://github.com//bioconda/bioconda-recipes/tree/bump/ont_fast5_api/recipes/ont-fast5-api) (click to view/edit other files)
Releases |[https://pypi.org/pypi/ont-fast5-api/json](https://pypi.org/pypi/ont-fast5-api/json)

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by dpryan79** [comment]
Grr, this same error is affecting bbmap and phyloflash and I have no idea why it's happening.

**Comment by kbseah** [comment]
> Grr, this same error is affecting bbmap and phyloflash and I have no idea why it's happening.

I've come here via the phyloflash recipe.

@dpryan79 the `assert sys.platform == 'darwin'` statement in the conda-build code appears to be causing the problem because the function is being called even though the test is run on Linux. That line has been changed at conda/conda-build@1730ad2360d1933867f051ed36fc72d3f5772e51

Perhaps the conda-build used for the test should be updated?

**Comment by bgruening** [comment]
@BiocondaBot please update

**Comment by bgruening** [comment]
Fix was merged here: https://github.com/conda/conda-build/pull/3925  3.19.3 should have the fix.

**Comment by bgruening** [comment]
@BiocondaBot please merge

**Pull request merged**
