### PR TITLE
Update discosnp++ to 2.3.0

### PR DESCRIPTION
**Pull request by cmonjeau**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by cbrueffer** [comment]
Thanks!

**Comment by cmonjeau** [comment]
Hi,

the 2.3.0 release is not in https://bioconda.github.io after the merge. Is it normal?

**Comment by cbrueffer** [comment]
I don't think so, I see the same issue with more recipes. Any idea @daler or @bgruening ?

**Comment by daler** [comment]
While the website only gets updated nightly, packages should be available immediately after building on travis-ci. The fact that they're not is definitely not normal, but it looks like it's due to a change in our build config. There's a fix in #6802. Once that fix is merged, the build system should detect that discosnp is missing and will build it (along with any other packages that haven't built on master in the past 19 hrs).

**Comment by cbrueffer** [comment]
:+1:

**Comment by mbargull** [comment]
`scripts/travis-run.sh` will only build packages if their recipes changed acc. to Git.
See: https://github.com/bioconda/bioconda-recipes/blob/c28499039a8dc6d1480863f741a3bc1f86c4b28b/scripts/travis-run.sh#L27-L70
So we'll explicitly need to trigger their builds again.

**Comment by daler** [comment]
I merged master into bulk branch and it's picking them up: https://travis-ci.org/bioconda/bioconda-recipes/builds/302580513. However, it doesn't look like an OSX build is being triggered. I suspect the `os:` list is only seeing linux, but from the travis-ci docs at https://docs.travis-ci.com/user/conditional-builds-stages-jobs/ it's not clear how to fix this. @johanneskoester any ideas?

**Comment by mbargull** [comment]
Ah, I just opened #6808 to trigger those builds again. Should I just close this in favor of your `bulk` changes?

**Comment by daler** [comment]
I think you can close it, that way we don't have that trailing whitespace in the recipes.

**Comment by daler** [comment]
From https://docs.travis-ci.com/user/build-stages/#Build-Stages-and-Build-Matrix-Expansion:

> Each job included in jobs.include inherits the first value of the array that defines a matrix dimension. In the example above, without explicitly setting rvm: 2.4, the included job inherits rvm: 2.3.

and from https://docs.travis-ci.com/user/conditional-builds-stages-jobs/#Conditional-Jobs:

> Jobs need to be listed explicitely, i.e., using jobs.include (or its alias matrix.include), in order to specify conditions for them. Jobs created via matrix expansion currently cannot have conditions.

I can't quite work out what the syntax should be in order to get this to work. @johanneskoester would it be OK to revert #6758 until we work this out?

**Comment by mbargull** [comment]
This affects `master` too, of course: https://travis-ci.org/bioconda/bioconda-recipes/builds/302575014

**Comment by daler** [comment]
@mbargull I want to get #6810 in so we don't accumulate more unbuilt packages. I'll use the bulk branch to do the rebuilds.

**Pull request merged**
