### PR TITLE
fix include.patch, xref #1606

### PR DESCRIPTION
**Pull request by daler**
* [ ] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [x] This PR does something else (explain below).

Fixes the include.patch generated by ucsc utils helper script, see #1606

### CODE REVIEW

**Comment by daler** [comment]
@johanneskoester, pretty much all the existing ucsc utils built for linux still have anaconda instead of $PREFIX in the include patch. I also noticed that a bunch of the utils have been removed for linux for previous timeout issues. And it looks like ucsc utils are now up to v332. Taken together I propose a version bump for all ucsc utils that uses this fixed include patch. If you think that's reasonable, I'll do it in batches to avoid ci timeouts.

**Comment by bgruening** [comment]
ping @yhoogstrate as he was working a lot on these packages lately.

**Comment by johanneskoester** [comment]
Sounds good. Feel free to do that, @daler!  
  
Dr. rer. nat. Johannes Köster

Centrum Wiskunde &amp; Informatica, Amsterdam

Harvard Medical School, Boston

http://johanneskoester.bitbucket.org

  

On May 23 2016, at 10:00 am, Björn Grüning &lt;notifications@github.com&gt;
wrote:  

> ping [@yhoogstrate](https://github.com/yhoogstrate) as he was working a lot
on these packages lately.

>

> —  
You are receiving this because you were mentioned.  
Reply to this email directly or [view it on
GitHub](https://github.com/bioconda/bioconda-recipes/pull/1617#issuecomment-22
0911919)

**Comment by remimarenco** [comment]
@daler I am updating ucsc-psltobigpsl as the 332 version is buggy (Wrong exception about negative values). But the `HG_INC` has changed:

```
HG_INC+=-I../inc -I../../inc -I../../../inc -I../../../../inc -I../../../../../inc -I$(kentSrc)/htslib
```

They have added the `-I$(kentSrc)/htslib` and I was wondering how you would advise to manage this?

Let me know if you want me to open an issue somewhere else to avoid mixing different topics.

Thanks!

**Comment by daler** [comment]
In that case the templates and scripts in https://github.com/bioconda/bioconda-recipes/tree/master/scripts/ucsc should be updated, and a similar round of updates (in batches, because it takes a while to compile each tool) needs to be done.

**Pull request merged**
