### PR TITLE
rebuild xsd

### PR DESCRIPTION
**Pull request by bernt-matthias**
In https://github.com/bioconda/bioconda-recipes/pull/16532 it was tried to build percolator and xsd against newer libraries, e.g. xerces. The former depends on the later.

This does not work (at least I do not know how) in one PR. Even if the xsd build is successful building percolator will use the old xsd package which resulted in a mismatch of the versions. 

So I just cherry picked the commits form the PR and will remove them there as soon as this is merged. 

Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [ ] This PR adds a new recipe.
* [ ] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

 * `@BiocondaBot please update` will cause the BiocondaBot to merge the master branch into a PR
 * `@BiocondaBot please add label` will add the `please review & merge` label.
 * `@BiocondaBot please fetch artifacts` will post links to packages and docker containers built by the CI system. You can use this to test packages locally before merging.

For members of the Bioconda project, the following command is also available:

 * `@BiocondaBot please merge` will cause packages/containers to be uploaded and a PR merged. Someone must approve a PR first! This has the benefit of not wasting CI build time required by manually merging PRs.

If you have questions, please post them in gitter or ping `@bioconda/core` in a comment (if you are not able to directly ping `@bioconda/core` then the bot will repost your comment and enable pinging).

### CODE REVIEW

**Comment by bernt-matthias** [comment]
@BiocondaBot please add label

**Comment by bgruening** [comment]
@bioconda-bot please merge

**Comment by glormph** [comment]
Has anyone actually tried running percolator 3.4 from this package? I'm getting XML reading errors running `msgf2pin` and am suspecting a xerces version issue. It seems to run fine in a native install, see https://github.com/percolator/percolator/issues/251. A bit unsure if it actually is that though.

**Comment by bernt-matthias** [comment]
Yep, I'm running it via OpenMS PercolatorAdapter

**Comment by glormph** [comment]
Oh, now I'm puzzled! Just to be sure, are you running `msgf2pin` specifically?

**Comment by bernt-matthias** [comment]
Sorry, OpenMS uses just `percolator` as far as I know.

**Pull request merged**
