### PR TITLE
Initial commit for package tango

### PR DESCRIPTION
**Pull request by johnne**
[TANGO](https://github.com/johnne/tango) (**T**axonomic cl**A**ssificatio**N** of meta**G**enomic c**O**ntigs) is a tool that assigns taxonomy to (metagenomic) contigs.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by johnne** [comment]
@bgruening I thought that listing `diamond` as a dependency meant it can't be noarch. But I must admit that I get confused by the documentation on noarch packages.

**Comment by bgruening** [comment]
Hi @johnne. That should be fine. numpy is also a compiled package but if your package is Python but depends on numpy only everything is fine and it can be noarch. As far as I understood it if your host/build dependencies are python only you can make it a noarch package.

**Comment by bgruening** [comment]
@johnne let me know if this works for you.

**Comment by johnne** [comment]
@bgruening Thank you!

**Pull request merged**
