### PR TITLE
bwa meth fix

### PR DESCRIPTION
**Pull request by bernt-matthias**
Got strange error: 

```
/miniconda3/envs/__bwameth@0.2.2/lib/python2.7/site-packages/bwameth-0.2.2-py2.7.egg/EGG-INFO/scripts/bwameth.py
/miniconda3/envs/__bwameth@0.2.2/bin/python: can't find '__main__' module in '/miniconda3/envs/__bwameth@0.2.2/lib/python2.7/site-packages/bwameth-0.2.2-py2.7.egg/EGG-INFO/scripts/bwameth.py'
```

Tested successfully, but no idea why my change helps. 

Also odd that I needed to bump to build 3! Where is build 2 coming from?

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by bernt-matthias** [comment]
@BiocondaBot please fetch artifacts

**Comment by bernt-matthias** [comment]
@BiocondaBot please fetch artifacts

**Comment by bernt-matthias** [comment]
@BiocondaBot please fetch artifacts

**Comment by bernt-matthias** [comment]
@BiocondaBot please add label

**Comment by nsoranzo** [comment]
> Got strange error:
> 
> ```
> /miniconda3/envs/__bwameth@0.2.2/lib/python2.7/site-packages/bwameth-0.2.2-py2.7.egg/EGG-INFO/scripts/bwameth.py
> /miniconda3/envs/__bwameth@0.2.2/bin/python: can't find '__main__' module in '/miniconda3/envs/__bwameth@0.2.2/lib/python2.7/site-packages/bwameth-0.2.2-py2.7.egg/EGG-INFO/scripts/bwameth.py'
> ```
> 
> Tested successfully, but no idea why my change helps.
> 
> Also odd that I needed to bump to build 3! Where is build 2 coming from?

Build 2 comes from commit 64363ebddb4eba3d9c82dd8d815b1853dd9406a1 in the bulk branch, which will be merged back in #23381 .

**Comment by nsoranzo** [comment]
@BiocondaBot please merge

**Comment by mbargull** [comment]
> Also odd that I needed to bump to build 3! Where is build 2 coming from?

Doing a lot of rebuilds on `bulk` for Py3.8 prep. (Hopefully I can merge back into `master` later today to stop confusion people with +1 build numbers ;).)

**Pull request merged**
