### PR TITLE
Add Kalamari

### PR DESCRIPTION
**Pull request by lskatz**
Describe your pull request here

This adds the Kalamari reference database. It is a collection of genome accessions,
taxonomy accessions, and methods to download and compile a local database.
This is my first conda package and I think I followed the rules. 
Please let me know if I need to revise it at all.

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by lskatz** [comment]
Tagging @rpetit3

**Comment by rpetit3** [comment]
@biocondabot please fetch artifacts

**Comment by rpetit3** [comment]
@BiocondaBot please fetch artifacts

**Comment by rpetit3** [comment]
@BiocondaBot please fetch artifacts

**Comment by rpetit3** [comment]
@lskatz you can now test to make sure it all works as you expect, feel free to reach out with questions

**Comment by dr-joe-wirth** [comment]
@lskatz have you tested this? if not, can you send me some instructions for testing?

**Comment by lskatz** [comment]
> @lskatz have you tested this? if not, can you send me some instructions for testing?

I haven't tested it, sorry. But I appreciate getting it over the line! I see @rpetit3 has done some work since your comment.

**Comment by lskatz** [comment]
@BiocondaBot please fetch artifacts

**Comment by lskatz** [comment]
Adding `perl-bioperl` to hopefully fix this error

image

**Comment by dr-joe-wirth** [comment]
@lskatz i encountered something similar with phantasm when I was building a docker image. R also raised that "locales" complaint. I used the following commands to resolve it:

```bash
# install and update locales (required for R to function properly)
apt-get -y install locales
LC_ALL=C.UTF-8
dpkg-reconfigure locales
echo 'export LC_ALL=C.UTF-8' >> ~/.bashrc
```
maybe if you do something similar in a `build.sh` file? or maybe @rpetit3 has additional insight into this problem.

**Comment by lskatz** [comment]
lol I can try it

**Comment by lskatz** [comment]
@BiocondaBot please fetch artifacts

**Comment by lskatz** [comment]
@BiocondaBot please fetch artifacts

**Comment by lskatz** [comment]
@dr-joe-wirth the local test worked! Can you please review?

**Pull request merged**
