### PR TITLE
Add RNAsamba

### PR DESCRIPTION
**Pull request by apcamargo**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by apcamargo** [comment]
@bioconda/core Can anyone help me with this? Why is `tensorflow` depending on `numpy-base`? In it's [recipe](https://github.com/conda-forge/tensorflow-feedstock/blob/master/recipe/meta.yaml) it ony depends on `numpy >=1.16.1`.

```
23:02:42 BIOCONDA INFO (OUT) conda.exceptions.UnsatisfiableError: The following specifications were found to be in conflict:
23:02:42 BIOCONDA INFO (OUT)   - numpy=1.9
23:02:42 BIOCONDA INFO (OUT)   - tensorflow[version='>=1.5.0,<2.0'] -> numpy[version='>=1.16.1'] -> numpy-base==1.16.3=py36hde5b4d6_0
```

**Comment by epruesse** [comment]
@biocondabot recheck

**Comment by epruesse** [comment]
Ok, I hope this will now yield packages that you can download, install and test. Tensorflow needs a newer GLIBC and won't work in our containers. (And we can't upgrade it there, because then everything we build would need the newer glibc....).

Please don't merge when this goes green. Do test the package and ping me when all is ok.

Thanks!

**Comment by epruesse** [comment]
@biocondabot recheck

**Comment by apcamargo** [comment]
Thanks @epruesse 

My local test failed. It seems like `GLIBC_2.16` was a problem locally too.

Here's the output:

```
12:40:13 BIOCONDA INFO (OUT) ## Package Plan ##
12:40:13 BIOCONDA INFO (OUT) 
12:40:13 BIOCONDA INFO (OUT)   environment location: /opt/conda/conda-bld/rnasamba_1558020932797/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p
12:40:13 BIOCONDA INFO (OUT) 
12:40:13 BIOCONDA INFO (OUT) 
12:40:13 BIOCONDA INFO (OUT) The following NEW packages will be INSTALLED:
12:40:13 BIOCONDA INFO (OUT) 
12:40:13 BIOCONDA INFO (OUT)     absl-py:                0.7.1-py37_0                  conda-forge
12:40:13 BIOCONDA INFO (OUT)     astor:                  0.7.1-py_0                    conda-forge
12:40:13 BIOCONDA INFO (OUT)     binutils_impl_linux-64: 2.31.1-h6176602_1             defaults
12:40:13 BIOCONDA INFO (OUT)     binutils_linux-64:      2.31.1-h6176602_7             defaults
12:40:13 BIOCONDA INFO (OUT)     biopython:              1.73-py37h14c3975_0           conda-forge
12:40:13 BIOCONDA INFO (OUT)     bzip2:                  1.0.6-h14c3975_1002           conda-forge
12:40:13 BIOCONDA INFO (OUT)     c-ares:                 1.15.0-h14c3975_1001          conda-forge
12:40:13 BIOCONDA INFO (OUT)     ca-certificates:        2019.3.9-hecc5488_0           conda-forge
12:40:13 BIOCONDA INFO (OUT)     certifi:                2019.3.9-py37_0               conda-forge
12:40:13 BIOCONDA INFO (OUT)     gast:                   0.2.2-py_0                    conda-forge
12:40:13 BIOCONDA INFO (OUT)     gcc_impl_linux-64:      7.3.0-habb00fd_1              conda-forge
12:40:13 BIOCONDA INFO (OUT)     gcc_linux-64:           7.3.0-h553295d_7              conda-forge
12:40:13 BIOCONDA INFO (OUT)     grpcio:                 1.16.1-py37hf8bcb03_1         defaults
12:40:13 BIOCONDA INFO (OUT)     gxx_impl_linux-64:      7.3.0-hdf63c60_1              conda-forge
12:40:13 BIOCONDA INFO (OUT)     gxx_linux-64:           7.3.0-h553295d_7              conda-forge
12:40:13 BIOCONDA INFO (OUT)     h5py:                   2.9.0-nompi_py37hf008753_1102 conda-forge
12:40:13 BIOCONDA INFO (OUT)     hdf5:                   1.10.4-nompi_h3c11f04_1106    conda-forge
12:40:13 BIOCONDA INFO (OUT)     keras:                  2.2.4-py37_1                  conda-forge
12:40:13 BIOCONDA INFO (OUT)     keras-applications:     1.0.7-py_1                    conda-forge
12:40:13 BIOCONDA INFO (OUT)     keras-preprocessing:    1.0.9-py_1                    conda-forge
12:40:13 BIOCONDA INFO (OUT)     libblas:                3.8.0-9_openblas              conda-forge
12:40:13 BIOCONDA INFO (OUT)     libcblas:               3.8.0-9_openblas              conda-forge
12:40:13 BIOCONDA INFO (OUT)     libffi:                 3.2.1-he1b5a44_1006           conda-forge
12:40:13 BIOCONDA INFO (OUT)     libgcc-ng:              8.2.0-hdf63c60_1              defaults
12:40:13 BIOCONDA INFO (OUT)     libgfortran-ng:         7.3.0-hdf63c60_0              defaults
12:40:13 BIOCONDA INFO (OUT)     libgpuarray:            0.7.6-h14c3975_1003           conda-forge
12:40:13 BIOCONDA INFO (OUT)     liblapack:              3.8.0-9_openblas              conda-forge
12:40:13 BIOCONDA INFO (OUT)     libprotobuf:            3.7.1-h8b12597_0              conda-forge
12:40:13 BIOCONDA INFO (OUT)     libstdcxx-ng:           8.2.0-hdf63c60_1              defaults
12:40:13 BIOCONDA INFO (OUT)     mako:                   1.0.7-py_1                    conda-forge
12:40:13 BIOCONDA INFO (OUT)     markdown:               2.6.11-py_0                   conda-forge
12:40:13 BIOCONDA INFO (OUT)     markupsafe:             1.1.1-py37h14c3975_0          conda-forge
12:40:13 BIOCONDA INFO (OUT)     mock:                   3.0.5-py37_0                  conda-forge
12:40:13 BIOCONDA INFO (OUT)     ncurses:                6.1-hf484d3e_1002             conda-forge
12:40:13 BIOCONDA INFO (OUT)     numpy:                  1.16.3-py37he5ce36f_0         conda-forge
12:40:13 BIOCONDA INFO (OUT)     openblas:               0.3.6-h6e990d7_2              conda-forge
12:40:13 BIOCONDA INFO (OUT)     openssl:                1.1.1b-h14c3975_1             conda-forge
12:40:13 BIOCONDA INFO (OUT)     pip:                    19.1-py37_0                   conda-forge
12:40:13 BIOCONDA INFO (OUT)     protobuf:               3.7.1-py37he1b5a44_0          conda-forge
12:40:13 BIOCONDA INFO (OUT)     pygpu:                  0.7.6-py37h3010b51_1000       conda-forge
12:40:13 BIOCONDA INFO (OUT)     python:                 3.7.3-h5b0a415_0              conda-forge
12:40:13 BIOCONDA INFO (OUT)     pyyaml:                 5.1-py37h14c3975_0            conda-forge
12:40:13 BIOCONDA INFO (OUT)     readline:               7.0-hf8c457e_1001             conda-forge
12:40:13 BIOCONDA INFO (OUT)     rnasamba:               0.1.0-py_0                    local
12:40:13 BIOCONDA INFO (OUT)     scipy:                  1.2.1-py37h09a28d5_1          conda-forge
12:40:13 BIOCONDA INFO (OUT)     setuptools:             41.0.1-py37_0                 conda-forge
12:40:13 BIOCONDA INFO (OUT)     six:                    1.12.0-py37_1000              conda-forge
12:40:13 BIOCONDA INFO (OUT)     sqlite:                 3.26.0-h67949de_1001          conda-forge
12:40:13 BIOCONDA INFO (OUT)     tensorboard:            1.13.1-py37_0                 conda-forge
12:40:13 BIOCONDA INFO (OUT)     tensorflow:             1.13.1-py37_0                 conda-forge
12:40:13 BIOCONDA INFO (OUT)     tensorflow-estimator:   1.13.0-py_0                   defaults
12:40:13 BIOCONDA INFO (OUT)     termcolor:              1.1.0-py_2                    conda-forge
12:40:13 BIOCONDA INFO (OUT)     theano:                 1.0.4-py37hf484d3e_1000       conda-forge
12:40:13 BIOCONDA INFO (OUT)     tk:                     8.6.9-h84994c4_1001           conda-forge
12:40:13 BIOCONDA INFO (OUT)     werkzeug:               0.15.4-py_0                   conda-forge
12:40:13 BIOCONDA INFO (OUT)     wheel:                  0.33.4-py37_0                 conda-forge
12:40:13 BIOCONDA INFO (OUT)     xz:                     5.2.4-h14c3975_1001           conda-forge
12:40:13 BIOCONDA INFO (OUT)     yaml:                   0.1.7-h14c3975_1001           conda-forge
12:40:13 BIOCONDA INFO (OUT)     zlib:                   1.2.11-h14c3975_1004          conda-forge
12:40:13 BIOCONDA INFO (OUT) 
12:40:14 BIOCONDA INFO (OUT) Preparing transaction: ...working... done
12:40:17 BIOCONDA INFO (OUT) Verifying transaction: ...working... ERROR:conda.stderr:
12:40:17 BIOCONDA INFO (OUT) ClobberWarning: This transaction has incompatible packages due to a shared path.
12:40:17 BIOCONDA INFO (OUT)   packages: conda-forge::tensorboard-1.13.1-py37_0, conda-forge::tensorflow-1.13.1-py37_0
12:40:17 BIOCONDA INFO (OUT)   path: 'bin/tensorboard'
12:40:17 BIOCONDA INFO (OUT) 
12:40:17 BIOCONDA INFO (OUT) 
12:40:17 BIOCONDA INFO (OUT) 
12:40:17 BIOCONDA INFO (OUT) done
12:40:23 BIOCONDA INFO (OUT) Executing transaction: ...working... ERROR:conda.stderr:
12:40:23 BIOCONDA INFO (OUT) ClobberWarning: Conda was asked to clobber an existing path.
12:40:23 BIOCONDA INFO (OUT)   source path: /opt/conda/conda-bld/rnasamba_1558020932797/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/.condatmp/607b448b-df2a-4f04-82f2-b90c8626f7c8
12:40:23 BIOCONDA INFO (OUT)   target path: /opt/conda/conda-bld/rnasamba_1558020932797/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/tensorboard
12:40:23 BIOCONDA INFO (OUT) 
12:40:23 BIOCONDA INFO (OUT) 
12:40:23 BIOCONDA INFO (OUT) 
12:40:25 BIOCONDA INFO (OUT) done
12:40:25 BIOCONDA INFO (OUT) WARNING: symlink_conda() is deprecated.
12:40:25 BIOCONDA INFO (OUT) export PREFIX=/opt/conda/conda-bld/rnasamba_1558020932797/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p
12:40:25 BIOCONDA INFO (OUT) export SRC_DIR=/opt/conda/conda-bld/rnasamba_1558020932797/test_tmp
12:40:25 BIOCONDA INFO (OUT) INFO: activate-binutils_linux-64.sh made the following environmental changes:
12:40:25 BIOCONDA INFO (OUT) +ADDR2LINE=$PREFIX/bin/x86_64-conda_cos6-linux-gnu-addr2line
12:40:25 BIOCONDA INFO (OUT) +AR=$PREFIX/bin/x86_64-conda_cos6-linux-gnu-ar
12:40:25 BIOCONDA INFO (OUT) +AS=$PREFIX/bin/x86_64-conda_cos6-linux-gnu-as
12:40:25 BIOCONDA INFO (OUT) +CXXFILT=$PREFIX/bin/x86_64-conda_cos6-linux-gnu-c++filt
12:40:25 BIOCONDA INFO (OUT) +ELFEDIT=$PREFIX/bin/x86_64-conda_cos6-linux-gnu-elfedit
12:40:25 BIOCONDA INFO (OUT) +GPROF=$PREFIX/bin/x86_64-conda_cos6-linux-gnu-gprof
12:40:25 BIOCONDA INFO (OUT) +HOST=x86_64-conda_cos6-linux-gnu
12:40:25 BIOCONDA INFO (OUT) +LD_GOLD=$PREFIX/bin/x86_64-conda_cos6-linux-gnu-ld.gold
12:40:25 BIOCONDA INFO (OUT) +LD=$PREFIX/bin/x86_64-conda_cos6-linux-gnu-ld
12:40:25 BIOCONDA INFO (OUT) +NM=$PREFIX/bin/x86_64-conda_cos6-linux-gnu-nm
12:40:25 BIOCONDA INFO (OUT) +OBJCOPY=$PREFIX/bin/x86_64-conda_cos6-linux-gnu-objcopy
12:40:25 BIOCONDA INFO (OUT) +OBJDUMP=$PREFIX/bin/x86_64-conda_cos6-linux-gnu-objdump
12:40:25 BIOCONDA INFO (OUT) +RANLIB=$PREFIX/bin/x86_64-conda_cos6-linux-gnu-ranlib
12:40:25 BIOCONDA INFO (OUT) +READELF=$PREFIX/bin/x86_64-conda_cos6-linux-gnu-readelf
12:40:25 BIOCONDA INFO (OUT) +SIZE=$PREFIX/bin/x86_64-conda_cos6-linux-gnu-size
12:40:25 BIOCONDA INFO (OUT) +STRINGS=$PREFIX/bin/x86_64-conda_cos6-linux-gnu-strings
12:40:25 BIOCONDA INFO (OUT) +STRIP=$PREFIX/bin/x86_64-conda_cos6-linux-gnu-strip
12:40:25 BIOCONDA INFO (OUT) INFO: activate-gcc_linux-64.sh made the following environmental changes:
12:40:25 BIOCONDA INFO (OUT) +CC=$PREFIX/bin/x86_64-conda_cos6-linux-gnu-cc
12:40:25 BIOCONDA INFO (OUT) +CFLAGS=-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -I$PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/rnasamba-0.1.0 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
12:40:25 BIOCONDA INFO (OUT) +CMAKE_PREFIX_PATH=:$PREFIX:/opt/conda/conda-bld/rnasamba_1558020932797/_build_env/x86_64-conda_cos6-linux-gnu/sysroot/usr
12:40:25 BIOCONDA INFO (OUT) +_CONDA_PYTHON_SYSCONFIGDATA_NAME=_sysconfigdata_x86_64_conda_cos6_linux_gnu
12:40:25 BIOCONDA INFO (OUT) +CPPFLAGS=-DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -I$PREFIX
12:40:25 BIOCONDA INFO (OUT) +CPP=$PREFIX/bin/x86_64-conda_cos6-linux-gnu-cpp
12:40:25 BIOCONDA INFO (OUT) +DEBUG_CFLAGS=-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -ffunction-sections -pipe -I$PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/rnasamba-0.1.0 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
12:40:25 BIOCONDA INFO (OUT) +DEBUG_CPPFLAGS=-D_DEBUG -D_FORTIFY_SOURCE=2 -Og -I$PREFIX
12:40:25 BIOCONDA INFO (OUT) +GCC_AR=$PREFIX/bin/x86_64-conda_cos6-linux-gnu-gcc-ar
12:40:25 BIOCONDA INFO (OUT) +GCC_NM=$PREFIX/bin/x86_64-conda_cos6-linux-gnu-gcc-nm
12:40:25 BIOCONDA INFO (OUT) +GCC=$PREFIX/bin/x86_64-conda_cos6-linux-gnu-gcc
12:40:25 BIOCONDA INFO (OUT) +GCC_RANLIB=$PREFIX/bin/x86_64-conda_cos6-linux-gnu-gcc-ranlib
12:40:25 BIOCONDA INFO (OUT) +LDFLAGS=-Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-rpath,$PREFIX/lib -Wl,-rpath-link,$PREFIX/lib -L$PREFIX/lib
12:40:25 BIOCONDA INFO (OUT) INFO: activate-gxx_linux-64.sh made the following environmental changes:
12:40:25 BIOCONDA INFO (OUT) +CXXFLAGS=-fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -I$PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/rnasamba-0.1.0 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
12:40:25 BIOCONDA INFO (OUT) +CXX=$PREFIX/bin/x86_64-conda_cos6-linux-gnu-c++
12:40:25 BIOCONDA INFO (OUT) +DEBUG_CXXFLAGS=-fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -ffunction-sections -pipe -I$PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/rnasamba-0.1.0 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
12:40:25 BIOCONDA INFO (OUT) +GXX=$PREFIX/bin/x86_64-conda_cos6-linux-gnu-g++
12:40:26 BIOCONDA INFO (OUT) + rnasamba-classify --help
12:40:26 BIOCONDA INFO (OUT) Traceback (most recent call last):
12:40:26 BIOCONDA INFO (OUT)   File "/opt/conda/conda-bld/rnasamba_1558020932797/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
12:40:26 BIOCONDA INFO (OUT)     from tensorflow.python.pywrap_tensorflow_internal import *
12:40:26 BIOCONDA INFO (OUT)   File "/opt/conda/conda-bld/rnasamba_1558020932797/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
12:40:26 BIOCONDA INFO (OUT)     _pywrap_tensorflow_internal = swig_import_helper()
12:40:26 BIOCONDA INFO (OUT)   File "/opt/conda/conda-bld/rnasamba_1558020932797/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
12:40:26 BIOCONDA INFO (OUT)     _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
12:40:26 BIOCONDA INFO (OUT)   File "/opt/conda/conda-bld/rnasamba_1558020932797/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.7/imp.py", line 242, in load_module
12:40:26 BIOCONDA INFO (OUT)     return load_dynamic(name, filename, file)
12:40:26 BIOCONDA INFO (OUT)   File "/opt/conda/conda-bld/rnasamba_1558020932797/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.7/imp.py", line 342, in load_dynamic
12:40:26 BIOCONDA INFO (OUT)     return _load(spec)
12:40:26 BIOCONDA INFO (OUT) ImportError: /lib64/libc.so.6: version `GLIBC_2.16' not found (required by /opt/conda/conda-bld/rnasamba_1558020932797/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)
12:40:26 BIOCONDA INFO (OUT) 
12:40:26 BIOCONDA INFO (OUT) During handling of the above exception, another exception occurred:
12:40:26 BIOCONDA INFO (OUT) 
12:40:26 BIOCONDA INFO (OUT) Traceback (most recent call last):
12:40:26 BIOCONDA INFO (OUT)   File "/opt/conda/conda-bld/rnasamba_1558020932797/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/rnasamba-classify", line 6, in <module>
12:40:26 BIOCONDA INFO (OUT)     from rnasamba.cli import classify_cli
12:40:26 BIOCONDA INFO (OUT)   File "/opt/conda/conda-bld/rnasamba_1558020932797/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.7/site-packages/rnasamba/__init__.py", line 21, in <module>
12:40:26 BIOCONDA INFO (OUT)     from rnasamba.core.model import RNAsambaClassificationModel, RNAsambaTrainModel
12:40:26 BIOCONDA INFO (OUT)   File "/opt/conda/conda-bld/rnasamba_1558020932797/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.7/site-packages/rnasamba/core/model.py", line 24, in <module>
12:40:26 BIOCONDA INFO (OUT)     import tensorflow as tf
12:40:26 BIOCONDA INFO (OUT)   File "/opt/conda/conda-bld/rnasamba_1558020932797/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.7/site-packages/tensorflow/__init__.py", line 24, in <module>
12:40:26 BIOCONDA INFO (OUT)     from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
12:40:26 BIOCONDA INFO (OUT)   File "/opt/conda/conda-bld/rnasamba_1558020932797/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.7/site-packages/tensorflow/python/__init__.py", line 49, in <module>
12:40:26 BIOCONDA INFO (OUT)     from tensorflow.python import pywrap_tensorflow
12:40:26 BIOCONDA INFO (OUT)   File "/opt/conda/conda-bld/rnasamba_1558020932797/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
12:40:26 BIOCONDA INFO (OUT)     raise ImportError(msg)
12:40:26 BIOCONDA INFO (OUT) ImportError: Traceback (most recent call last):
12:40:26 BIOCONDA INFO (OUT)   File "/opt/conda/conda-bld/rnasamba_1558020932797/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
12:40:26 BIOCONDA INFO (OUT)     from tensorflow.python.pywrap_tensorflow_internal import *
12:40:26 BIOCONDA INFO (OUT)   File "/opt/conda/conda-bld/rnasamba_1558020932797/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
12:40:26 BIOCONDA INFO (OUT)     _pywrap_tensorflow_internal = swig_import_helper()
12:40:26 BIOCONDA INFO (OUT)   File "/opt/conda/conda-bld/rnasamba_1558020932797/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
12:40:26 BIOCONDA INFO (OUT)     _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
12:40:26 BIOCONDA INFO (OUT)   File "/opt/conda/conda-bld/rnasamba_1558020932797/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.7/imp.py", line 242, in load_module
12:40:26 BIOCONDA INFO (OUT)     return load_dynamic(name, filename, file)
12:40:26 BIOCONDA INFO (OUT)   File "/opt/conda/conda-bld/rnasamba_1558020932797/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.7/imp.py", line 342, in load_dynamic
12:40:26 BIOCONDA INFO (OUT)     return _load(spec)
12:40:26 BIOCONDA INFO (OUT) ImportError: /lib64/libc.so.6: version `GLIBC_2.16' not found (required by /opt/conda/conda-bld/rnasamba_1558020932797/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)
12:40:26 BIOCONDA INFO (OUT) 
12:40:26 BIOCONDA INFO (OUT) 
12:40:26 BIOCONDA INFO (OUT) Failed to load the native TensorFlow runtime.
12:40:26 BIOCONDA INFO (OUT) 
12:40:26 BIOCONDA INFO (OUT) See https://www.tensorflow.org/install/errors
12:40:26 BIOCONDA INFO (OUT) 
12:40:26 BIOCONDA INFO (OUT) for some common reasons and solutions.  Include the entire stack trace
12:40:26 BIOCONDA INFO (OUT) above this error message when asking for help.
12:40:27 BIOCONDA INFO (OUT) Tests failed for rnasamba-0.1.0-py_0.tar.bz2 - moving package to /opt/conda/conda-bld/broken
12:40:27 BIOCONDA INFO (OUT) WARNING:conda_build.build:Tests failed for rnasamba-0.1.0-py_0.tar.bz2 - moving package to /opt/conda/conda-bld/broken
12:40:27 BIOCONDA INFO (OUT) TESTS FAILED: rnasamba-0.1.0-py_0.tar.bz2
.12:40:32 BIOCONDA ERROR COMMAND FAILED: docker run -t --net host --rm -v /tmp/tmpfsxuy7yc/build_script.bash:/opt/build_script.bash -v /tmp/miniconda/miniconda/conda-bld:/opt/host-conda-bld -v /home/apcamargo/bioconda-recipes/recipes/rnasamba:/opt/recipe -e LC_MEASUREMENT=pt_BR.UTF-8 -e LC_PAPER=pt_BR.UTF-8 -e LC_MONETARY=pt_BR.UTF-8 -e LANG=en_US.UTF-8 -e LC_NAME=pt_BR.UTF-8 -e LC_CTYPE=pt_BR.UTF-8 -e LC_ADDRESS=pt_BR.UTF-8 -e LC_NUMERIC=pt_BR.UTF-8 -e LC_TELEPHONE=pt_BR.UTF-8 -e LC_IDENTIFICATION=pt_BR.UTF-8 -e LC_TIME=pt_BR.UTF-8 -e HOST_USER_ID=1000 bioconda/bioconda-utils-build-env:latest /bin/bash /opt/build_script.bash

12:40:32 BIOCONDA ERROR BUILD FAILED recipes/rnasamba
12:40:33 BIOCONDA ERROR BUILD SUMMARY: of 1 recipes, 1 failed and 0 were skipped. Details of recipes and environments follow.
12:40:33 BIOCONDA ERROR BUILD SUMMARY: FAILED recipe recipes/rnasamba
```

**Comment by epruesse** [comment]
Did you run it with `--docker`? I meant, just do this:

```
conda env create  -c https://57489-42372094-gh.circle-artifacts.com/0/tmp/artifacts/packages -n rnasamba rnasamba
conda activate rnasamba
# now see it if works
```

**Comment by apcamargo** [comment]
I'm sorry, I didn't understand it.

I can't run the this command:
```
conda env create -c https://57489-42372094-gh.circle-artifacts.com/0/tmp/artifacts/packages -n rnasamba rnasamba
usage: conda-env [-h] {create,export,list,remove,update} ...
conda-env: error: unrecognized arguments: -c rnasamba
```

When I click the link, it says that the artifact was not found.

**Comment by epruesse** [comment]
@biocondabot recheck

**Comment by epruesse** [comment]
That's weird. You can't download the package? I can... can you try this again, just by clicking on the link? Perhaps you need to log in at CircleCI with your user account to make it work? (Don't think so ... I've been able to conda install, and I doubt conda uses creds for that).

**Comment by epruesse** [comment]
Sorry, no "env". Conda can be weird.

```
conda create -c https://57489-42372094-gh.circle-artifacts.com/0/tmp/artifacts/packages -n rnasamba rnasamba
```

**Comment by apcamargo** [comment]
I tested the build here and everything is fine. Thank you for your help!

**Comment by epruesse** [comment]
Ok. We really need a way to test these. But for the time being, this has to suffice. Thanks @apcamargo!

@biocondabot merge

**Pull request merged**
