### PR TITLE
gembs: update matplotlib dependency to matplotlib-base

### PR DESCRIPTION
**Pull request by JakeLehle**
Whoops, I just saw that I can make changes to this file myself and make a pull request.
Hope this helps push this though.

### CODE REVIEW

**Comment by simonbray** [comment]
@BiocondaBot please update

**Comment by simonbray** [comment]
@JakeLehle could you update the branch please?

**Comment by JakeLehle** [comment]
Hi @simonbray I'm new to bioconda but excited to learn. Could you send me a link or info for how I should merge this branch with the vioconda:bump/gembs branch from this page or do I need to do this from the command line?
I keep trying to merge it from here and getting turned around and rerouted to opening a whole new branch on the CircleCI pipeline page.

**Comment by JakeLehle** [comment]
Okay, I think I figured it out.

I ran 
```
git fetch origin
git merge origin/patch-1
git push --set-upstream origin bump/gembs
```

Let me know if this was correct and if I need to do anything else to push this forward.

**Comment by simonbray** [comment]
Ah, I see you are trying to edit an existing PR, I assumed you wanted to merge this straight into master. I just made the change for you here: https://github.com/bioconda/bioconda-recipes/pull/27790/commits/f3047995a7bfac2537dab3ef29c4985cbc7cfef4, so I will close this on.

Re merging: it looks mostly good, but you should have merged from `upstream` rather than `origin`. But GitHub also allows you to update a branch directly through the web interface, see: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork

**Comment by JakeLehle** [comment]
Awesome thanks @simonbray. Yes, I'm an unrelated researcher to the gemBS development team who wanted to use the newer 3.5.0 of gemBS and I saw that this update was stuck here so I was trying to push through the errors so that I could use the newer version.

Thanks for pushing that through and giving me some tips for using bioconda in the future.
Best,
Jake

**Pull request closed without merging**
