### PR TITLE
Bump up deepbgc to 0.1.29

### PR DESCRIPTION
**Pull request by prihoda**
Bump up deepbgc to 0.1.29

### CODE REVIEW

**Comment by prihoda** [comment]
@BiocondaBot please add label

**Comment by rpetit3** [comment]
This one was captured by the auto-update bot https://github.com/bioconda/bioconda-recipes/pull/30794, going to close

@prihoda please feel free to reopen if necessary

**Comment by prihoda** [comment]
Thanks @rpetit3, got it. About the auto-update bot: How does it handle changed dependencies? Because in the previous release `0.1.28` https://github.com/bioconda/bioconda-recipes/pull/30602, an autoupdate was merged even though the dependencies in setup.py have changed, which caused a broken release on conda, because it kept the old conda dependencies.

**Comment by rpetit3** [comment]
When there are new dependencies, we have to manually add them. Usually the tests fail due to the missing dependency and we can get them added it. But as you know personally that's not always the case.

**Comment by prihoda** [comment]
Right, that makes sense. I should probably set up better tests :)

**Pull request closed without merging**
