### PR TITLE
Proteinortho

### PR DESCRIPTION
**Pull request by pmjklemm**
:information_source:
If this is your first pull request to Bioconda please ping `@bioconda/core` so it can be reviewed and to request being added as a member of the Bioconda team. Members of the Bioconda team are able to merge their own pull requests once tests and linting have passed.

----------------

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by pmjklemm** [comment]
why does it throw:
```
/bin/sh: Zeile 2: g++: Kommando nicht gefunden.
```
although i included {{ compiler('cxx') }} in the meta.yaml ?

i also tried to manipulate the build.sh, so that it can find the g++
```
ln -s $BUILD_PREFIX/bin/x86_64-conda_cos6-linux-gnu-g++ g++
export PATH=$PWD:$PATH
```
but then it does not find the libraries e.g. lapack (-llapack) ...

What am i doing wrong?

**Comment by pmjklemm** [comment]
ping @bioconda/core

Hello,
This is proteinortho (https://gitlab.com/paulklemm_PHD/proteinortho) a tool to detect orthologous genes within different species and I would like to add this to bioconda.
The macOSX build wont work so it is skipped for now (i will update this as soon as i figure out what is wrong with yaml,docker,circleci,osx ...).
Greetings

**Comment by dpryan79** [comment]
@pmjklemm This looks good to go, shall I merge it? Would you like to be added to bioconda?

**Comment by pmjklemm** [comment]
Yes and yes, that would be nice. Thank you

**Pull request merged**
