### PR TITLE
Add PGR-TK

### PR DESCRIPTION
**Pull request by cschin**
Background: this recipe will build the bioconda package for the PanGenome Research Tool Kit ( [PGR-TK](https://github.com/Sema4-Research/pgr-tk#readme), [Multiscale Analysis of Pangenome Enables Improved Representation of Genomic Diversity For Repetitive And Clinically Relevant Genes](https://www.biorxiv.org/content/10.1101/2022.08.05.502980v2) )

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by cschin** [comment]
@BiocondaBot please add label

**Comment by cschin** [comment]
@rpetit3 can you help? do you mind take some quick look into this PR? thanks a lot.

**Comment by rpetit3** [comment]
What are your thoughts on adding agc and WFA to Bioconda?

**Comment by cschin** [comment]
The AGC as a command line tool has already a receipt. I am using both AGC/libWFA as libraries. To use them as libraries for RUST, it needs some special building process. I think it is easier to keep them as non-bioconda dependences and build along with PGR-TK.

**Comment by rpetit3** [comment]
Understood, should they always use the latest commit, or do you think it would be better to use a release for each?

**Comment by cschin** [comment]
As I have no control for the upstream and those gcc/ clang / code with hardware acceleration specific API are hard to sync, that is why I fork them and make sure every thing works in a set. When the upstream changes, it needs to be tested again. With the limit resource, I prefer to have some frozen upstream until necessary to update.

**Comment by cschin** [comment]
@rpetit3 let me know if you have other concern?

**Comment by rpetit3** [comment]
Meant to respond on my phone last night. What are your thoughts on specifying the commit when you `git pull`, unless you are ok with rebuilds and future releases always using the latest commits from those repos

**Comment by rpetit3** [comment]
@biocondabot please fetch artifacts

**Comment by cschin** [comment]
@rpetit3  the artifact works (using the docker from the artifact and another docker based on the current continuumio/miniconda3:latest image) as long as the dependence is correct. There are two `libstdcxxx-ng` in the `repodata.json`, is that problematic?

```
"packages": {
    "pgr-tk-0.3.4-py38h87f3376_0.tar.bz2": {
      "build": "py38h87f3376_0",
      "build_number": 0,
      "depends": [
        "libclang13 >=14.0.6",
        "libgcc-ng >=12",
        "libstdcxx-ng >=11.2",
        "libstdcxx-ng >=12",
        "numpy",
        "python >=3.8,<3.9.0a0",
        "python_abi 3.8.* *_cp38"
      ],
      
```

**Comment by rpetit3** [comment]
@cschin if you are good, I'm good

**Comment by cschin** [comment]
@BiocondaBot please fetch artifacts

**Comment by cschin** [comment]
@rpetit3 the latest build is good. I fix the `libstdcxx-ng` issue as well. please merge. thanks a lot.

**Review by rpetit3 — APPROVED** [review]

**Comment by rpetit3** [comment]
@BiocondaBot please merge

**Comment by cschin** [comment]
This works from the build artifact

```
(base) root@caf4a528b623:/LinuxArtifacts/LinuxArtifacts/packages# conda install -c package linux-64/pgr-tk-0.3.4-py38h87f3376_0.tar.bz2
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Retrieving notices: ...working... /opt/conda/lib/python3.8/site-packages/urllib3/connectionpool.py:997: InsecureRequestWarning: Unverified HTTPS request is being made to host 'repo.anaconda.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
/opt/conda/lib/python3.8/site-packages/urllib3/connectionpool.py:997: InsecureRequestWarning: Unverified HTTPS request is being made to host 'repo.anaconda.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
done
(base) root@caf4a528b623:/LinuxArtifacts/LinuxArtifacts/packages# python
Python 3.8.13 (default, Mar 28 2022, 11:38:47)
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pgrtk
>>> pgrtk.__version__
'pgrtk 0.3.4 (bioconda release build, linux [x86_64] [rustc 1.63.0 (4b91a6ea7 2022-08-08)])'
```
but install from conda still encounter dependence conflict,

```
(base) root@8557c9b14bbe:/# conda install -c biocond pgr-tk
Collecting package metadata (current_repodata.json): - failed

UnavailableInvalidChannel: HTTP 404 NOT FOUND for channel biocond <https://conda.anaconda.org/biocond>

The channel is not accessible or is invalid.

You will need to adjust your conda configuration to proceed.
Use `conda config --show channels` to view your configuration's current state,
and use `conda config --show-sources` to view config file locations.


(base) root@8557c9b14bbe:/# conda install -c bioconda pgr-tk
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: -
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.31=0
  - python=3.8 -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']

Your installed version is: 2.31

(base) root@8557c9b14bbe:/# conda --version
conda 4.14.0
```

I will leave another day to solve this madness (nota  bioconda' team's issue, this seems common in many other computation focused libraries as well.)

**Comment by cschin** [comment]
The tar ball download directly from `https://anaconda.org/bioconda/` works.... 
```
(base) root@d01739a84da8:~# wget https://anaconda.org/bioconda/pgr-tk/0.3.4/download/linux-64/pgr-tk-0.3.4-py38h87f3376_0.tar.bz2
--2022-08-25 05:20:35--  https://anaconda.org/bioconda/pgr-tk/0.3.4/download/linux-64/pgr-tk-0.3.4-py38h87f3376_0.tar.bz2
...
HTTP request sent, awaiting response... 200 OK
Length: 9387340 (9.0M) [application/x-tar]
Saving to: ‘pgr-tk-0.3.4-py38h87f3376_0.tar.bz2’

pgr-tk-0.3.4-py38h87f3376_0.tar.bz2 100%[===================================================================>]   8.95M  2.74MB/s    in 3.3s

2022-08-25 05:20:39 (2.74 MB/s) - ‘pgr-tk-0.3.4-py38h87f3376_0.tar.bz2’ saved [9387340/9387340]

(base) root@d01739a84da8:~# conda install -c package ./pgr-tk-0.3.4-py38h87f3376_0.tar.bz2

Downloading and Extracting Packages
######################################################################################################################################## | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Retrieving notices: ...working... /opt/conda/lib/python3.8/site-packages/urllib3/connectionpool.py:997: InsecureRequestWarning: Unverified HTTPS request is being made to host 'repo.anaconda.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
/opt/conda/lib/python3.8/site-packages/urllib3/connectionpool.py:997: InsecureRequestWarning: Unverified HTTPS request is being made to host 'repo.anaconda.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
/opt/conda/lib/python3.8/site-packages/urllib3/connectionpool.py:997: InsecureRequestWarning: Unverified HTTPS request is being made to host 'conda.anaconda.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
done
(base) root@d01739a84da8:~# python
Python 3.8.13 (default, Mar 28 2022, 11:38:47)
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pgrtk
>>> pgrtk.__version__
'pgrtk 0.3.4 (bioconda release build, linux [x86_64] [rustc 1.63.0 (4b91a6ea7 2022-08-08)])'
>>>
(base) root@d01739a84da8:~# s.warn(
/opt/conda/lib/python3.8/site-packages/urllib3/connectionpool.py:997: InsecureRequestWarning: Unverified HTTPS request is being made to host 'conda.anaconda.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
done
(base) root@d01739a84da8:~# python
Python 3.8.13 (default, Mar 28 2022, 11:38:47)
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pgrtk
>>> pgrtk.__version__
'pgrtk 0.3.4 (bioconda release build, linux [x86_64] [rustc 1.63.0 (4b91a6ea7 2022-08-08)])'
>>>
(base) root@d01739a84da8:~#
```

**Pull request merged**
