### PR TITLE
Rebuild centrifuge

### PR DESCRIPTION
**Pull request by epruesse**
Rebuild [`centrifuge`](https://bioconda.github.io/recipes/centrifuge/README.html) to update pinnings

[install with bioconda](http://bioconda.github.io/recipes/centrifuge/README.html) [Conda](https://anaconda.org/bioconda/centrifuge/files)

Info | Link
-----|-----
Recipe | [`recipes/centrifuge`](https://github.com//bioconda/bioconda-recipes/tree/bump/centrifuge/recipes/centrifuge) (click to view/edit other files)
Releases |

***

(Unable to detect reason for pinning rebuild. Predicted hash has changed, however.)

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/updating.html)).

### CODE REVIEW

**Comment by druvus** [comment]
@epruesse any reason you removed centrifuge-kreport?

**Comment by epruesse** [comment]
I removed the `cp` line because everything but the python scripts gets installed via `make install` anyway. Should be in the archive. Did you check?

**Comment by epruesse** [comment]
```
$ curl -s $LINK | tar -tj | grep bin
bin/centrifuge-inspect
bin/centrifuge-build
bin/centrifuge-kreport
bin/centrifuge-download
bin/centrifuge
bin/centrifuge-inspect-bin
bin/centrifuge-build-bin
bin/centrifuge-class
bin/centrifuge-RemoveEmptySequence.pl
bin/centrifuge-RemoveN.pl
bin/centrifuge-sort-nt.pl
bin/centrifuge-BuildSharedSequence.pl
bin/centrifuge-compress.pl
bin/centrifuge_evaluate.py
bin/centrifuge_simulate_reads.py

```

**Comment by epruesse** [comment]
This thinks it's python version dependent. I don't think it actually is.

**Comment by epruesse** [comment]
The scripts  have  `<py3` requirement

**Comment by dpryan79** [comment]
Is this ready for merging? It looks like it.

**Comment by epruesse** [comment]
Yeah. Think so, probably just got sidetracked.

@biocondabot merge

**Pull request merged**
