### PR TITLE
Add simpleaf

### PR DESCRIPTION
**Pull request by rob-p**
This PR adds a [simpleaf](https://github.com/COMBINE-lab/simpleaf) recipe to bioconda. Simpleaf is a rust framework to simplify the running and operation of `alevin-fry` (a single-cell processing tool that is already in bioconda).

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by nh13** [comment]
Recipe should be in a folder called `simpleaf`

**Comment by bkille** [comment]
@rob-p The tests are working for Linux now, however [compilation fails on MacOS](https://dev.azure.com/bioconda/bioconda-recipes/_build/results?buildId=19406&view=logs&j=1b052f1d-4456-52f0-9d43-71c4c5bd734d&t=edc48dcd-1fc2-5e3b-7036-7be9cea00123&l=277) with the following error message:
```rust
thread 'main' panicked at '`UNKNOWN/.cargo/registry/src/github.com-1ecc6299db9ec823/heck-0.4.0/UNKNOWN/.cargo/registry/src/github.com-1ecc6299db9ec823/heck-0.4.0/src/lib.rs` is not absolute', src/tools/cargo/src/cargo/core/manifest.rs:261:9
```

Unfortunately, I do not have access to MacOS and am unfamiliar w/ Rust compilation, so I'm of no further use here. Let me know if there's anything else I can do to help.

**Comment by rob-p** [comment]
Hi @bkille,

  Thanks for all the fixes up to this point.  The issue seems not to be OSX so much as the specific conda build env. It build on my OSX machines (including my M1).  The error seems to arise from a panic:

```
18:04:08 BIOCONDA INFO (ERR) thread 'main' panicked at '`UNKNOWN/.cargo/registry/src/github.com-1ecc6299db9ec823/heck-0.4.0/UNKNOWN/.cargo/registry/src/github.com-1ecc6299db9ec823/heck-0.4.0/src/lib.rs` is not absolute', src/tools/cargo/src/cargo/core/manifest.rs:261:9
```

which I think is looking for resolving an absolute path and is unable to do so.  I'll see what I can dig up.

**Comment by rob-p** [comment]
Got it!  It seems that to build on OSX, rust recipes currently have to have a [build.sh](https://github.com/bioconda/bioconda-recipes/blob/d54dec137842af67b367699beb08f105e59dbd18/recipes/simpleaf/build.sh) that does some magic.

**Review by bkille — APPROVED** [review]

**Comment by bkille** [comment]
@bioconda-bot please merge

**Pull request merged**
