### PR TITLE
Update treesapp meta.yml

### PR DESCRIPTION
**Pull request by cmorganl**
Two changes:

1. Decrement setuptools version to newest version available on conda.
2. Add MMSeqs2 to recipe.

### CODE REVIEW

**Comment by cmorganl** [comment]
@dpryan79 could I please get a hand assessing what happened during the Mac-OS build stage? Thanks!

**Comment by dpryan79** [comment]
@cmorganl Hmm, seems to be a dependency missing on OSX in conda-forge. I'll look into it.

**Comment by dpryan79** [comment]
The latest version of setuptools in conda-forge is 50.0.0. There are newer versions in the defaults channel, but those likely have dependencies that are causing the issues on OSX.

**Comment by dpryan79** [comment]
Interesting, mmseqs2 has a dependency conflict on OSX. Maybe we can just rebuild it

**Comment by cmorganl** [comment]
Ah, yeah. I didn't see realize the latest version of setuptools was 50.0.0. I referenced the defaults channel but maybe I shouldn't in the future? Thanks for figuring that out and fixing it!

I hope fixing mmseqs2's dependency conflict is easy to do.

**Comment by dpryan79** [comment]
I'll give the new mmseqs2 an hour or so to get built and copied across the Anaconda CDN then try adding it back into the recipe.

**Comment by dpryan79** [comment]
Hmm, looks like the issue is how mmseqs2 is linking to openmp. It ends up pulling in an older version of llvm-openmp on OSX that conflicts with what the python programs are using. I'll see if I can get around that.

**Comment by dpryan79** [comment]
Success! That was a tricky one.

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@bioconda-bot please fetch artifacts

**Comment by dpryan79** [comment]
I keep forgetting to approve PRs before having the bot merge them today...

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Comment by cmorganl** [comment]
I can't thank you enough @dpryan79!

**Pull request merged**
