### PR TITLE
Bump bioconductor-zlibbioc to 1.20.0

### PR DESCRIPTION
**Pull request by ccwang002**
* [x] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by daler** [comment]
@ccwang002 we're having build issues and we're waiting for the fixes to be merged. You will likely have to update with master and update this PR when those fixes are complete. Sorry for the inconvenience.

**Comment by ccwang002** [comment]
I passed all the checks here could I merge the pull request?

**Comment by bgruening** [comment]
@ccwang002 if you can please wait a little bit more. We will merge this as soon as the build infrastructure is stable again.

**Comment by ccwang002** [comment]
Got it. I will wait. Thanks!

**Pull request merged**
