### PR TITLE
Update ITSxpress - Vsearch version specification

### PR DESCRIPTION
**Pull request by arivers**
Updated  version specification on Vsearch to fix a braking change in API for V2.20
@BiocondaBot please update

### CODE REVIEW

**Comment by arivers** [comment]
@BiocondaBot please update

**Comment by arivers** [comment]
@BiocondaBot please update

**Comment by arivers** [comment]
@bioconda/core please review & merge

**Comment by dpryan79** [comment]
@BiocondaBot please fetch artifacts

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@BiocondaBot please merge

**Pull request merged**
