### PR TITLE
fix naming schema for eigen

### PR DESCRIPTION
**Pull request by bgruening**

### CODE REVIEW

**Comment by johanneskoester** [comment]
I think the package names in the meta.yaml also have to be renamed to eigen instead of eigen3 and eigen2.

**Comment by bgruening** [comment]
@johanneskoester I guess the strict version dependencies in the openbabel packge is also not best practice?

**Comment by johanneskoester** [comment]
Exactly ;-). I'm really sorry for requiring all these changes. But I think they are really necessary to keep Bioconda as flexible as it is now.

**Comment by bgruening** [comment]
Yeah, I have thought so :). Flexible here means for me not reproducible. I start to wonder if it's worth to join as Galaxy project if we make so much trouble.

**Comment by johanneskoester** [comment]
It's really not like that. I am the author of a workflow management system myself (Snakemake), and I have to deal with the same reproducibility considerations as you guys. Having technically motivated dependencies does not defeat reproducibility. You just use a different mechanism to define the exact versions. It is not even more code. The version numbers just appear in a different place than in the dependencies of the acutal package (where they would be artificial anyway). This way, you can update version definitions without changing recipe definitions. You can also update version of dependencies without breaking your entire setup.

**Comment by bgruening** [comment]
You are right. If you keep your version numbers separately somewhere than you can work around this with a meta package. I was referring to this package here, as it is. So what we probably need to do is to maintain a separate repository with these version numbers / definitions.
Out of curiosity where do you store your strict versioning and pre-compiled binaries?

**Comment by johanneskoester** [comment]
With Snakemake, best practice is to store workflows git repositories. These contain a requirements.txt in the root directory, where the workflow designer can set fixed versions for all tools and dependencies. Before execution, the user can create a conda environment with 

```
conda env create --file requirements.txt
```

And every package will be exactly the version defined by the developer of the workflow.
In the future, Snakemake will incorporate the possibility to define versions into its workflow definition language (per rule). Snakemake will then handle the automatic creation of conda enviroments for each job.

Regarding your plans, it depends a lot on how you intend Galaxy to interact with Conda. One way of such definitions are flat lists stored in a git repo as I outlined above. Another way would be to upload environment definitions to a separate anaconda channel (see [here](http://docs.anaconda.org/using.html#Environments)). A third way would be the meta-packages we discussed before.

**Comment by johanneskoester** [comment]
I think I have another good argument against strict dependencies. Image you have a package A that depends on B==3.1 (for reproducibility reasons), a package C that depends on B==3.1 as well because of reproducibility etc.. Now, you add a package D that depends on B==3.2 because of technical reasons. In order to be able to install D into the same environment without a conflict, you need to update all packages depending on B! But technically, there would be no reason, because A and C would work with B==3.2 as well, we have just artificially constrained them. Even worse, changing the dependency could have side effects on other packages as well.

If instead you have whatever environment definition or a meta package, you just need to decide: do I want to update the required version of B? If so, you only need to change it at that place, without needing to change any other recipe and avoiding side effects that cause further conflicts.

**Comment by bgruening** [comment]
@johanneskoester thanks for you time, I really appreciate!

```
conda env create --file requirements.txt
```
This can only work for runtime deps, right? Let's assume I have this file

```
boost=1.56.0
salmon=0.6.0
```
What is the expected environment? salmon compiled against boost 1.56 or 1.57 (latest and only version)?
If this works magically I'm sold and this will probably solve our problem, I still can not imagine how this will work, without recompiling on demand.

> But technically, there would be no reason, because A and C would work with B==3.2 as well

Technically no problem, but you don't know if the expected results will change.

> Even worse, changing the dependency could have side effects on other packages as well.

That's the reason we have fixed bundles and create new versions as soon as a dependency changed. Conda does this as well with the build-counter.

> If instead you have whatever environment definition or a meta package, you just need to decide: do I want to update the required version of B? If so, you only need to change it at that place, without needing to change any other recipe and avoiding side effects that cause further conflicts.

See above, does this also work for build dependencies? We are taking about C/C++ programs here like eigen, aren't we?

**Comment by daler** [comment]
For the `salmon` example, would [conda `features`](http://conda.pydata.org/docs/building/meta-yaml.html#id1) help?

**Comment by johanneskoester** [comment]
I am not a C/C++ expert, but often, build dependencies are upwards compatible (e.g. libc). So salmon should work both with the boost it was compiled against and a newer boost, unless the API/ABI changed.
Conda has build in support for such hard dependencies when it comes to packages that depend on e.g. Python, Perl and R. You will notice that although the version was not set in the dependencies of a recipe, the version used for the build is added to the filename of the package archive. E.g. a Python package build on Python 3.5 will refuse to work in a Python 2.7 environment although the Python version is not specified in the dependency.

Features are a way to generalize such a mechanisms for other dependencies as well. I think this is not done automatically because of what I stated in the beginning of my post: often, such dependencies are upwards compatible.

**Comment by johanneskoester** [comment]
I think its time to merge.

**Pull request merged**
