### PR TITLE
Update drop to 1.3.4

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`drop`](https://bioconda.github.io/recipes/drop/README.html): **1.3.3** &rarr; **1.3.4**

[install with bioconda](http://bioconda.github.io/recipes/drop/README.html) [Conda](https://anaconda.org/bioconda/drop/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/drop`](https://github.com//bioconda/bioconda-recipes/tree/bump/drop/recipes/drop) (click to view/edit other files)
Summary | Detection of RNA Outlier Pipeline
Home | [https://github.com/gagneurlab/drop](https://github.com/gagneurlab/drop)
Releases |[https://github.com/gagneurlab/drop/tags](https://github.com/gagneurlab/drop/tags)
Recipe Maintainer(s) | @c-mertes, @nickhsmith, @vyepez88
Author | `@gagneurlab`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by c-mertes** [comment]
@BiocondaBot please add label

**Comment by c-mertes** [comment]
Before merging, we first have to update the pinned versions of wbuild, FRASER and OUTRIDER. For this we have to wait to get #47892 merged and build. Then we have to add wbuild according to this one here https://stackoverflow.com/questions/48128029/installing-specific-build-of-an-anaconda-package to get the build number pinned as we need to ensure that snakemake<8 will be installed.

**Comment by c-mertes** [comment]
@AtaJadidAhari can you please keep track of this and implement it when the #47892 merged and build? I assume we have to wait till #41025 is solved.

**Comment by AtaJadidAhari** [comment]
> Before merging, we first have to update the pinned versions of wbuild, FRASER and OUTRIDER. For this we have to wait to get #47892 merged and build.
We don't need to wait for new FRASER in this version. There will be another DROP release i.e. 1.4.0 soon after #47892 gets merged.

**Comment by AtaJadidAhari** [comment]
@BiocondaBot rebuild

**Comment by AtaJadidAhari** [comment]
FRASER and wBuild are bumped to new versions: #48006 #47659
OUTRIDER is ready to be merged now: #47659

**Pull request closed without merging**
