### PR TITLE
Bump unicycler to 0.3.0

### PR DESCRIPTION
**Pull request by rrwick**
* [x] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by druvus** [comment]
@rrwick bioconda is using an older gcc version so I think you would need to patch the makefile to use `-std=c++1y`instead of `-std=c++14`.

**Comment by druvus** [comment]
@bioconda/core any ideas of workaround how build the latest version of unicycler? Seems that seqan library doesn't support gcc  <4.9. This is a little bit outside my C knowledge.

**Comment by bgruening** [comment]
@druvus I don't think there is a solution yet. We need to have a new compiler and there are various attempts in conda-forge, e.g. this one: https://github.com/conda-forge/staged-recipes/pull/873

I could imagine to put such a package in bioconda for a very limited time to enable such compilations, under a different namespace, maybe `gcc5`. But we should also help conda-forge to get this done sooner than later.

**Comment by rrwick** [comment]
I've been poking around with this stuff today and came to the same conclusion. I can't make Unicycler build with anything less than GCC 4.9. 😦 

Until it can use GCC 5+, should Unicycler be removed from bioconda? I'd rather users not use bioconda to install Unicycler if that means they'll be stuck on an old version.

**Comment by johanneskoester** [comment]
We have migrated our build system from Travis CI to Circle CI. If you would like to continue working on this PR, please update with latest upstream master and reopen this PR.

**Pull request closed without merging**
