### PR TITLE
Added recipe for pybio-utils

### PR DESCRIPTION
**Pull request by RickGelhausen**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by bgruening** [comment]
@RickGelhausen you are missing dependencies according to `RuntimeError: Setuptools downloading is disabled in conda build. Be sure to add all dependencies in the meta.yaml  url=https://pypi.org/simple/misc/`

**Comment by bgruening** [comment]
It seems to be this dependency https://github.com/dieterich-lab/pybio-utils/blob/master/setup.py#L71

**Comment by RickGelhausen** [comment]
@bgruening Hi Björn, thank you for your help.
I am currently working on a "workaround" as the creators of this package seem to have messed up their naming conventions. Egg and I were able to find the problem and will fix it as soon as possible. I just wanted to check whether my local circleci does its job.

**Comment by bgruening** [comment]
You could include a patch and fix the setup.py file for example.

**Comment by bgruening** [comment]
@RickGelhausen do you need any help here?

**Comment by RickGelhausen** [comment]
yes, I am currently waiting for Florian to return, as this package is currently not that important for our work. But I want to get it up and running as soon as possible. I think, the problem lies with the pymisc-utils package though.
The thing is that the creators of these packages, created the pymisc-utils package as "misc" and import it like this in python. So what I tried is to replace these imports by:
```
pymisc_utils = __import__("pymisc-utils") 
import pymisc_utils.<module>
```
but I get:

```
ImportError: No module named 'pymisc-utils'
```
which seems to be installed now:

```
The following NEW packages will be INSTALLED:
...
    pymisc-utils:         0.2.10-py35h37e70f2_0                 bioconda   
...
```
That makes me think that the "pymisc-utils" package needs some extra attention. But its just as likely, that I made a mistake somewhere. I will push it again, so you can see the full error message.

**Pull request closed without merging**
