### PR TITLE
Update scallop-umi to 1.1.0

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`scallop-umi`](https://bioconda.github.io/recipes/scallop-umi/README.html): **1.0.0** &rarr; **1.1.0**

[install with bioconda](http://bioconda.github.io/recipes/scallop-umi/README.html) [Conda](https://anaconda.org/bioconda/scallop-umi/files)

Info | Link
-----|-----
Recipe | [`recipes/scallop-umi`](https://github.com//bioconda/bioconda-recipes/tree/bump/scallop_umi/recipes/scallop-umi) (click to view/edit other files)
Releases |[https://github.com/Shao-Group/scallop-umi/releases](https://github.com/Shao-Group/scallop-umi/releases)
Recipe Maintainer(s) | @shaogroup
Author | `@Shao-Group`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by shaomingfu** [comment]
@BiocondaBot please add label

**Comment by shaomingfu** [comment]
@bioconda/core please help review and merge. Thanks!

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Comment by shaomingfu** [comment]
Thanks @dpryan79 !

**Pull request merged**
