### PR TITLE
updated secapr

### PR DESCRIPTION
**Pull request by tobiashofmann88**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by tobiashofmann88** [comment]
there was an error in the Travis CI check, I think what caused it is this:
Package missing in current linux-64 channels: 
  - pickle
How can I add the pickle python package to the linux-64 channel?

**Comment by daler** [comment]
@tobiashofmann88 `pickle` is a built-in module, you shouldn't need to add it as a dependency.

**Comment by tobiashofmann88** [comment]
so what is the issue then?

**Comment by daler** [comment]
@tobiashofmann88 the issue is that `pickle` is currently listed as a build and run dependency in the recipe. Things listed as dependencies are expected to be conda packages, but there are no conda packages for built-in modules, hence the error.

Hopefully all you need to do is remove the lines that say:

```
    - pickle
```
from `meta.yaml`.

**Comment by johanneskoester** [comment]
We have made changes to our build system. Please update your fork with the latest upstream/master

**Pull request closed without merging**
