### PR TITLE
Update bowtie2 to 2.4.5

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`bowtie2`](https://bioconda.github.io/recipes/bowtie2/README.html): **2.4.4** &rarr; **2.4.5**

[install with bioconda](http://bioconda.github.io/recipes/bowtie2/README.html) [Conda](https://anaconda.org/bioconda/bowtie2/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/bowtie2`](https://github.com//bioconda/bioconda-recipes/tree/bump/bowtie2/recipes/bowtie2) (click to view/edit other files)
Summary | Fast and sensitive gapped read alignment
Home | [http://bowtie-bio.sourceforge.net/bowtie2/index.shtml](http://bowtie-bio.sourceforge.net/bowtie2/index.shtml)
Releases |[https://github.com/BenLangmead/bowtie2/tags](https://github.com/BenLangmead/bowtie2/tags)
Author | `@BenLangmead`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by matthdsm** [comment]
Hi @bioconda/build-system 

Looking at the logs I think the build process for osx went OK, but it seems it finished with the wrong exit code. What should I do about this?

Thanks
M

**Comment by bgruening** [comment]
Can it be that one of the help commands returns an error code of 1?

**Comment by matthdsm** [comment]
Hi @bgruening 
A quick test shows exit code `0` for all the help commands so I think something else went wrong.
Do we just disable osx? Can you make more sense of the logs?

thanks
M

**Comment by matthdsm** [comment]
Tests throw the following error
```
08:07:03 BIOCONDA INFO (OUT) /usr/bin/env: python3: No such file or directory
```

Is this something we fix in the build or with a patch?

Matthias

**Comment by dpryan79** [comment]
Ah, they finally made the wrappers python 3. We can turn off python 2 builds for this now :)

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
Thanks

**Pull request merged**
