### PR TITLE
Update metacoag to 1.1.1

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`metacoag`](https://bioconda.github.io/recipes/metacoag/README.html): **1.1** &rarr; **1.1.1**

[install with bioconda](http://bioconda.github.io/recipes/metacoag/README.html) [Conda](https://anaconda.org/bioconda/metacoag/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/metacoag`](https://github.com//bioconda/bioconda-recipes/tree/bump/metacoag/recipes/metacoag) (click to view/edit other files)
Summary | MetaCoAG: Binning Metagenomic Contigs via Composition, Coverage and Assembly Graphs
Home | [https://github.com/metagentools/MetaCoAG](https://github.com/metagentools/MetaCoAG)
Releases |[https://github.com/metagentools/MetaCoAG/tags](https://github.com/metagentools/MetaCoAG/tags)
Recipe Maintainer(s) | @Vini2
Author | `@metagentools`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by Vini2** [comment]
@BiocondaBot please fetch artifacts

**Comment by Vini2** [comment]
## Testing

```
conda install -c ./packages metacoag-1.1.1-pyh7cba7a3_0.tar.bz2

which metacoag
~/miniconda3/envs/metacoag/bin/metacoag

metacoag -v
metacoag 1.1.1

metacoag -h 
usage: metacoag [-h] --assembler ASSEMBLER --graph GRAPH --contigs CONTIGS --abundance ABUNDANCE [--paths PATHS] --output OUTPUT [--hmm HMM] [--prefix PREFIX]
                [--min_length MIN_LENGTH] [--p_intra P_INTRA] [--p_inter P_INTER] [--d_limit D_LIMIT] [--depth DEPTH] [--mg_threshold MG_THRESHOLD]
                [--bin_mg_threshold BIN_MG_THRESHOLD] [--min_bin_size MIN_BIN_SIZE] [--delimiter DELIMITER] [--nthreads NTHREADS] [-v]

MetaCoAG is a metagenomic contig binning tool that makes use of the connectivity information found in assembly graphs, apart from the composition and coverage information.
MetaCoAG makes use of single-copy marker genes along with a graph matching technique and a label propagation technique to bin contigs.

options:
  -h, --help            show this help message and exit
  --assembler ASSEMBLER
                        name of the assembler used. (Supports SPAdes, MEGAHIT and Flye)
  --graph GRAPH         path to the assembly graph file
  --contigs CONTIGS     path to the contigs file
  --abundance ABUNDANCE
                        path to the abundance file
  --paths PATHS         path to the contigs.paths (metaSPAdes) or assembly.info (metaFlye) file
  --output OUTPUT       path to the output folder
  --hmm HMM             path to marker.hmm file. [default: auxiliary/marker.hmm]
  --prefix PREFIX       prefix for the output file
  --min_length MIN_LENGTH
                        minimum length of contigs to consider for binning. [default: 1000]
  --p_intra P_INTRA     minimum probability of an edge matching to assign to the same bin. [default: 0.1]
  --p_inter P_INTER     maximum probability of an edge matching to create a new bin. [default: 0.01]
  --d_limit D_LIMIT     distance limit for contig matching. [default: 20]
  --depth DEPTH         depth to consider for label propagation. [default: 10]
  --mg_threshold MG_THRESHOLD
                        length threshold to consider marker genes. [default: 0.5]
  --bin_mg_threshold BIN_MG_THRESHOLD
                        minimum fraction of marker genes that should be present in a bin. [default: 0.33333]
  --min_bin_size MIN_BIN_SIZE
                        minimum size of a bin to output in base pairs. [default: 200000]
  --delimiter DELIMITER
                        delimiter for output results. Supports a comma (,), a semicolon (;), a tab ($'\t'), a space (" ") and a pipe (|) [default: , (comma)]
  --nthreads NTHREADS   number of threads to use. [default: 8]
  -v, --version         show program's version number and exit

combine_cov -h
usage: combine_cov [-h] --covpath COVPATH --output OUTPUT

options:
  -h, --help         show this help message and exit
  --covpath COVPATH  path to the .tsv files from CoverM
  --output OUTPUT    path to the output folder
```

Everything looks good!

**Comment by Vini2** [comment]
@BiocondaBot please add label

**Review by beardymcjohnface — APPROVED** [review]

**Comment by Vini2** [comment]
@BiocondaBot please merge

**Pull request merged**
