### PR TITLE
 add r-leaps recipe

### PR DESCRIPTION
**Pull request by sebastian-luna-valero**
* [X] I have read the guidelines above.
* [X] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

Add recipe for:
https://cran.r-project.org/web/packages/leaps/index.html

@bioconda/core please review

### CODE REVIEW

**Comment by bgruening** [comment]
Thanks @sebastian-luna-valero!

**Comment by sebastian-luna-valero** [comment]
Thanks @bgruening!

However, when I do `conda search leaps` the `r-leaps` package does not come up. 

I must be missing something here, do you know what?

**Comment by bgruening** [comment]
@sebastian-luna-valero we currently have some build-infrastructure problems and are working on it. For some reason the OSX version was build, but the Linux version wasn't.

**Comment by sebastian-luna-valero** [comment]
Thanks @bgruening 

I will keep an eye on Travis.

**Pull request merged**
