### PR TITLE
Update viennarna (2.2.10); enable kinwalker

### PR DESCRIPTION
**Pull request by s-will**
* [x] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by s-will** [comment]
Hi @bgruening, could you please help? This seems to fail for reasons inside the conda build system. (See the several errors in the OSX build output)

**Comment by s-will** [comment]
Interestingly, it newly complains about missing perl. Let's see:)

**Comment by bgruening** [comment]
Perl is also a run dependency? Thanks @s-will for looking into it.

**Comment by s-will** [comment]
I can't imagine that perl is required to run all the main tools. There are some Utils written in perl, which are written to some extra bin dir: share/ViennaRNA/bin/, which is usually not even in the path. 
Do you think this justifies to include perl for run-time?

The whole wining about perl dependencies is new to me (and maybe 2.2.10) anyway.

**Comment by bgruening** [comment]
I don't know how often the utils are used. No opinion here sorry.

**Comment by bgruening** [comment]
Wow, this is a nice one: https://travis-ci.org/bioconda/bioconda-recipes/jobs/161312111#L1670
What is `chmod 644 "/anaconda/conda-bld/vienna_rna/share/doc/ViennaRNA/html"/*` doing?

**Comment by s-will** [comment]
I would say it makes sense to omit the perl run-time dependency to keep this lean. (Maybe Ronny @raumzeit can get rid of the compile time dependency if possible? Why is this even there?).

The chmod is in the documenation Makefile.am of the package. Then, this is rather a bug in the Vienna package; I can try to patch this (but Ronny, please fix in 2.2.11!). However, I wonder, why this happens only in the OSX build -- must be other length limits

**Comment by RaumZeit** [comment]
Thanks for pointing out that the number of files in the HTML documentation might exceed the maximum number of arguments. This will be fixed in the next release of ViennaRNA.
@s-will Your patch for Makefile.in won't do what you expect. A ```chmod -R 644 dir/``` will certainly fail since the execution bit for ```dir/``` will be removed first. Consequently, the files within ```dir/``` won't be accessible anymore for processing by ```chmod```. The only portable way to do this is to loop over the content of ```dir```, as in your first patch:
```
{ for i in "$(DESTDIR)$(htmldir)"/*; do test -f "$$i" && chmod 644 "$$i"; done }
chmod 755 "$(DESTDIR)$(htmldir)"
{ for i in "$(DESTDIR)$(htmldir)"/search/*; do test -f "$$i" && chmod 644 "$$i"; done }
chmod 755 "$(DESTDIR)$(htmldir)"/search
```
And btw, @bgruening , The chmod'ing in the install rule of ViennaRNAs documentation is a crude fix for wrong file attributes generated by some doxygen versions.

**Comment by s-will** [comment]
Thanks @raumzeit; I realized too late that there is a general problem with this. Now, I switched to the loop again.

**Comment by bgruening** [comment]
@RaumZeit thanks for the explanation, this explains a lot.
Seems to work, thanks again @s-will!

**Pull request merged**
