### PR TITLE
bump viennarna

### PR DESCRIPTION
**Pull request by mmiladi**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by mmiladi** [comment]
Hi @s-will , would you have any idea what causes this error? 
https://travis-ci.org/bioconda/bioconda-recipes/jobs/274279776#L4184

**Comment by mmiladi** [comment]
Created an issue here: https://github.com/ViennaRNA/ViennaRNA/issues/13

**Comment by martin-mann** [comment]
think you have to increase the build number to 1

**Comment by mmiladi** [comment]
Thanks @martin-mann . Sorry merging made it messy, since this PR was opened  before yours. 
What about  --without-tutorial  --without-tutorial-pdf ?

**Comment by martin-mann** [comment]
IMO the tutorials are not needed and only another optional source of compilation problems, that's why I disabled them.

**Comment by s-will** [comment]
Hey @martin-mann and @mmiladi, thanks a lot!

**Pull request merged**
