### PR TITLE
add recipe for NextPolish

### PR DESCRIPTION
**Pull request by rpetit3**
This PR adds a recipe for [NextPolish](https://github.com/Nextomics/NextPolish) a long read polisher. 

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by rpetit3** [comment]
@biocondabot please update

**Comment by rpetit3** [comment]
@BiocondaBot please update

**Comment by rpetit3** [comment]
@BiocondaBot please fetch artifacts

**Comment by rpetit3** [comment]
Testing

```
# Create env and install artifact
mamba create -n test-nextpolish -y -c conda-forge -c bioconda 'python>=3.6' bwa minimap2 paralleltask samtools
conda activate test-nextpolish
conda install LinuxArtifacts/packages/linux-64/nextpolish-1.4.1-py310h7132678_0.tar.bz2

Downloading and Extracting Packages
nextpolish-1.4.1     | ############################################################################################################################################################################################################################# | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Retrieving notices: ...working... done

# Check Usage
nextPolish
usage: nextPolish [-l FILE] [-v] [-h]

nextDenovo:
         Fast and accurately polish the genome generated by long reads

exmples:
        nextPolish run.cfg

For more information about NextPolish, see https://github.com/Nextomics/NextPolish

options:
  -l FILE, --log FILE  log file (default: pidXXX.log.info)
  -v, --version        show program's version number and exit
  -h, --help           please use the config file to pass parameters

# Check version 
nextPolish --version
nextPolish 1.4.1

# run test data
wget https://github.com/Nextomics/NextPolish/releases/download/v1.4.1/NextPolish.tgz
tar -vxzf NextPolish.tgz
cd NextPolish
nextPolish test_data/run.cfg
...working...
Polish.sh: /seq_split: not found
```

Looks like a typo in the patch file

**Comment by rpetit3** [comment]
@BiocondaBot please fetch artifacts

**Comment by rpetit3** [comment]
# Test 2 

### Jump straight into the test
```
nextPolish test_data/run.cfg
[22328 INFO] 2022-09-20 21:24:24 NextPolish start...
[22328 INFO] 2022-09-20 21:24:24 version:1.4.1 logfile:pid22328.log.info
[22328 WARNING] 2022-09-20 21:24:24 Re-write workdir
[22328 WARNING] 2022-09-20 21:24:24 Delete task: 6 due to missing hifi_fofn.
[22328 INFO] 2022-09-20 21:24:24 scheduled tasks:
[5, 1, 2]
[22328 INFO] 2022-09-20 21:24:24 options:
[22328 INFO] 2022-09-20 21:24:24
rerun:                        3
rewrite:                      1
kill:                         None
cleantmp:                     0
use_drmaa:                    0
deltmp:                       True
submit:                       None
job_type:                     local
task:                         [5, 1, 2]
...TRUNCATED...
[22328 INFO] 2022-09-20 21:24:58 remove temporary result: /home/robert_petit/temp/test-nextpolish/NextPolish/test_data/01_rundir/00.lgs_polish/04.polish.ref.sh.work/polish_genome1/genome.nextpolish.part000.fasta
[22328 INFO] 2022-09-20 21:24:58 remove temporary result: /home/robert_petit/temp/test-nextpolish/NextPolish/test_data/01_rundir/00.lgs_polish/04.polish.ref.sh.work/polish_genome2/genome.nextpolish.part001.fasta
[22328 INFO] 2022-09-20 21:25:03 Total jobs: 2
[22328 INFO] 2022-09-20 21:25:09 Submitted jobID:[22709] jobCmd:[/home/robert_petit/temp/test-nextpolish/NextPolish/test_data/01_rundir/01.score_chain/03.map.ref.sh.work/map_genome1/nextPolish.sh] in the local_cycle.
[22328 INFO] 2022-09-20 21:25:10 Submitted jobID:[22722] jobCmd:[/home/robert_petit/temp/test-nextpolish/NextPolish/test_data/01_rundir/01.score_chain/03.map.ref.sh.work/map_genome2/nextPolish.sh] in the local_cycle.
[22328 INFO] 2022-09-20 21:25:12 align_genome done
...TRUNCATED...
[22328 INFO] 2022-09-20 21:25:57 nextPolish has finished
[22328 INFO] 2022-09-20 21:25:57 final polished genome files:
[22328 INFO] 2022-09-20 21:25:57  /home/robert_petit/temp/test-nextpolish/NextPolish/test_data/./01_rundir/genome.nextpolish.fasta
[22328 INFO] 2022-09-20 21:25:57 final stat file:
[22328 INFO] 2022-09-20 21:25:57  /home/robert_petit/temp/test-nextpolish/NextPolish/test_data/./01_rundir/genome.nextpolish.fasta.stat
[22328 INFO] 2022-09-20 21:25:57 asm stat:
[22328 INFO] 2022-09-20 21:25:57
Type           Length (bp)            Count (#)
N10                60498                   1
N20                60498                   1
N30                60498                   1
N40                60498                   1
N50                60498                   1
N60                51048                   2
N70                51048                   2
N80                51048                   2
N90                51048                   2

Min.               51048                   -
Max.               60498                   -
Ave.               55773                   -
Total             111546                   2
```

Looks like it finished!

# Trying with docker

```
gzip -dc LinuxArtifacts/images/nextpolish:1.4.1--py310h7132678_0.tar.gz | docker load
1c2fc3319730: Loading layer [==================================================>]  283.1MB/283.1MB
Loaded image: quay.io/biocontainers/nextpolish:1.4.1--py310h7132678_0
```

### Usage
```
docker run --rm -u $(id -u):$(id -g) -v ${PWD}:/data quay.io/biocontainers/nextpolish:1.4.1--py310h7132678_0 nextPolish
usage: nextPolish [-l FILE] [-v] [-h]

nextDenovo:
         Fast and accurately polish the genome generated by long reads

exmples:
        nextPolish run.cfg

For more information about NextPolish, see https://github.com/Nextomics/NextPolish

options:
  -l FILE, --log FILE  log file (default: pidXXX.log.info)
  -v, --version        show program's version number and exit
  -h, --help           please use the config file to pass parameters


docker run --rm -u $(id -u):$(id -g) -v ${PWD}:/data quay.io/biocontainers/nextpolish:1.4.1--py310h7132678_0 nextPolish --version
nextPolish 1.4.1
```

### Running test data
```
docker run --rm -u $(id -u):$(id -g) -v ${PWD}:/data quay.io/biocontainers/nextpolish:1.4.1--py310h7132678_0 nextPolish /data/test_data/run.cfg
Traceback (most recent call last):
  File "/usr/local/bin/nextPolish", line 553, in <module>
    main(args)
  File "/usr/local/bin/nextPolish", line 372, in main
    log = plog(log_file)
  File "/usr/local/share/nextpolish-1.4.1/lib/kit.py", line 89, in plog
    fileHandler = logging.FileHandler(path, mode='w')
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1169, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1201, in _open
    return open_func(self.baseFilename, self.mode,
PermissionError: [Errno 13] Permission denied: '/pid1.log.info'
```


Looks like a few more changes in the patch file

**Comment by rpetit3** [comment]
@BiocondaBot please fetch artifacts

**Comment by rpetit3** [comment]
# Test 3 

### Conda 
jumping straight to the test data
```
nextPolish test_data/run.cfg
[3514 INFO] 2022-09-20 23:39:09 NextPolish start...
[3514 INFO] 2022-09-20 23:39:09 version:1.4.1 logfile:pid3514.log.info
[3514 WARNING] 2022-09-20 23:39:09 Re-write workdir
[3514 WARNING] 2022-09-20 23:39:09 Delete task: 6 due to missing hifi_fofn.
[3514 INFO] 2022-09-20 23:39:09 scheduled tasks:
[5, 1, 2]
[3514 INFO] 2022-09-20 23:39:09 options:
[3514 INFO] 2022-09-20 23:39:09
... TRUNCATED ...
[3514 INFO] 2022-09-20 23:40:41 nextPolish has finished
[3514 INFO] 2022-09-20 23:40:41 final polished genome files:
[3514 INFO] 2022-09-20 23:40:41  /home/robert_petit/temp/test-nextpolish/NextPolish/test_data/./01_rundir/genome.nextpolish.fasta
[3514 INFO] 2022-09-20 23:40:41 final stat file:
[3514 INFO] 2022-09-20 23:40:41  /home/robert_petit/temp/test-nextpolish/NextPolish/test_data/./01_rundir/genome.nextpolish.fasta.stat
[3514 INFO] 2022-09-20 23:40:41 asm stat:
[3514 INFO] 2022-09-20 23:40:41
Type           Length (bp)            Count (#)
N10                60498                   1
N20                60498                   1
N30                60498                   1
N40                60498                   1
N50                60498                   1
N60                51048                   2
N70                51048                   2
N80                51048                   2
N90                51048                   2

Min.               51048                   -
Max.               60498                   -
Ave.               55773                   -
Total             111546                   2
```

Also works with `--log`
```
nextPolish test_data/run.cfg --log test_data/thislog.txt
[4715 INFO] 2022-09-20 23:41:24 NextPolish start...
[4715 INFO] 2022-09-20 23:41:24 version:1.4.1 logfile:test_data/thislog.txt
... TRUNCATED ...
[4715 INFO] 2022-09-20 23:42:56 nextPolish has finished
[4715 INFO] 2022-09-20 23:42:56 final polished genome files:
[4715 INFO] 2022-09-20 23:42:56  /home/robert_petit/temp/test-nextpolish/NextPolish/test_data/./01_rundir/genome.nextpolish.fasta
[4715 INFO] 2022-09-20 23:42:56 final stat file:
[4715 INFO] 2022-09-20 23:42:56  /home/robert_petit/temp/test-nextpolish/NextPolish/test_data/./01_rundir/genome.nextpolish.fasta.stat
[4715 INFO] 2022-09-20 23:42:56 asm stat:
[4715 INFO] 2022-09-20 23:42:56
Type           Length (bp)            Count (#)
N10                60498                   1
N20                60498                   1
N30                60498                   1
N40                60498                   1
N50                60498                   1
N60                51048                   2
N70                51048                   2
N80                51048                   2
N90                51048                   2

Min.               51048                   -
Max.               60498                   -
Ave.               55773                   -
Total             111546                   2
```

## Now with Docker
```
docker run --rm -u $(id -u):$(id -g) -v ${PWD}:/data quay.io/biocontainers/nextpolish:1.4.1--py310h7132678_0 nextPolish /data/test_data/run.cfg --log /data/test-docker.log
[1 INFO] 2022-09-20 23:45:52 NextPolish start...
[1 INFO] 2022-09-20 23:45:52 version:1.4.1 logfile:/data/test-docker.log
[1 WARNING] 2022-09-20 23:45:52 Re-write workdir
[1 WARNING] 2022-09-20 23:45:52 Delete task: 6 due to missing hifi_fofn.
[1 INFO] 2022-09-20 23:45:52 scheduled tasks:
... TRUNCATED ...
Traceback (most recent call last):
  File "/usr/local/share/nextpolish-1.4.1/lib/nextpolish2.py", line 54, in <module>
    P = CDLL(os.path.dirname(os.path.realpath(__file__)) + '/' + "nextpolish2.so")
  File "/usr/local/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libbz2.so.1: cannot open shared object file: No such file or directory
```

So close!

**Comment by rpetit3** [comment]
@BiocondaBot please fetch artifacts

**Comment by rpetit3** [comment]
@BiocondaBot please fetch artifacts

**Comment by rpetit3** [comment]
# Test 4

Just jumping straight to Docker here
```
docker run --rm -u $(id -u):$(id -g) -v ${PWD}:/data quay.io/biocontainers/nextpolish:1.4.1--py310h7132678_0 nextPolish /data/test_data/run.cfg --log /data/test-docker.log
[1 INFO] 2022-09-21 01:16:33 NextPolish start...
[1 INFO] 2022-09-21 01:16:33 version:1.4.1 logfile:/data/test-docker.log
[1 WARNING] 2022-09-21 01:16:33 Re-write workdir
[1 WARNING] 2022-09-21 01:16:33 Delete task: 6 due to missing hifi_fofn.
[1 INFO] 2022-09-21 01:16:33 scheduled tasks:
[5, 1, 2]
[1 INFO] 2022-09-21 01:16:33 options:
[1 INFO] 2022-09-21 01:16:33
rerun:                        3
rewrite:                      1
... TRUNCATED ...
[1 INFO] 2022-09-21 01:17:44 nextPolish has finished
[1 INFO] 2022-09-21 01:17:44 final polished genome files:
[1 INFO] 2022-09-21 01:17:44  /data/01_rundir/genome.nextpolish.fasta
[1 INFO] 2022-09-21 01:17:44 final stat file:
[1 INFO] 2022-09-21 01:17:44  /data/01_rundir/genome.nextpolish.fasta.stat
[1 INFO] 2022-09-21 01:17:44 asm stat:
[1 INFO] 2022-09-21 01:17:44
Type           Length (bp)            Count (#)
N10                60498                   1
N20                60498                   1
N30                60498                   1
N40                60498                   1
N50                60498                   1
N60                51048                   2
N70                51048                   2
N80                51048                   2
N90                51048                   2

Min.               51048                   -
Max.               60498                   -
Ave.               55773                   -
Total             111546                   2
```

WE ARE GOOD TO GO!

**Comment by rpetit3** [comment]
@BiocondaBot please add label

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@BiocondaBot please merge

**Pull request merged**
