### PR TITLE
Add recipe for KaKsAnalysis version 1.0.0

### PR DESCRIPTION
**Pull request by gregvonkuster**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by gregvonkuster** [comment]
@bgruening I'm not able to determine why this is failing from the Travis logs.  When you get a chance, can you take a look?

**Comment by gregvonkuster** [comment]
I have no idea why the travis test fails on this.  I cannot reproduce this locally, and I'm installing all of the same dependencies:
```
Deleting work directory, /home/greg/miniconda3/conda-bld/plant_tribes_kaks_analysis_1496849755200/work/PlantTribes-1.0.0

The following NEW packages will be INSTALLED:

    blast:                      2.6.0-boost1.61_0 bioconda
    boost:                      1.61.0-py36_0             
    emmix:                      1.3-1             bioconda
    icu:                        54.1-0                    
    libgcc:                     5.2.0-0                   
    mafft:                      7.310-0           bioconda
    openssl:                    1.0.2l-0                  
    paml:                       4.9-1             bioconda
    pip:                        9.0.1-py36_1              
    plant_tribes_kaks_analysis: 1.0.0-0           local   
    python:                     3.6.1-2                   
    readline:                   6.2-2                     
    setuptools:                 27.2.0-py36_0             
    sqlite:                     3.13.0-0                  
    tk:                         8.5.18-0                  
    wheel:                      0.29.0-py36_0             
    xz:                         5.2.2-1                   
    zlib:                       1.2.8-3                   
```
@bgruening Can you take a look when you get a chance?

**Comment by daler** [comment]
@gregvonkuster the build seems OK but the test is failing -- maybe you could temporarily be more verbose with the test on travis to troubleshoot.

**Comment by gregvonkuster** [comment]
Thanks @daler I've eliminated the stderr redirect, so hopefully it will show something.  It is very confusing because tests pass just fine locally, and this recipe is very similar to all the other recipes I committed today which pass both locally and on travis.  Fingers crossed!

**Comment by gregvonkuster** [comment]
Finally success!  @bgruening can this be merged?

**Pull request merged**
