### PR TITLE
Weka

### PR DESCRIPTION
**Pull request by visze**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

Hi bioconda team. I added the famous machine learning library weka to bioconda. I spit weka up into weka-stable and weka-dev because the weka-dev add a lot of ne features (this is similar to the uploaded maven repository).

### CODE REVIEW

**Comment by bgruening** [comment]
Hi @visze! Welcome to Bioconda.
We don't have currently a rule for development packages, but I would not name them `stable` and `dev`. Weka should be `weka` if possible. This makes it easier to user to find it. You could think about a version prefix that indicates the dev version for example.

**Comment by kyleabeauchamp** [comment]
Presumably this should go upstream on conda-forge as it's a general purpose ML library?

**Comment by visze** [comment]
Yes conda-forge might be better. I just wanted to add a software on top of
it later for variant prioritization. So that's why I went to bioconda.

But maybe (or for sure) weka is not only used in the bioinformatics field
(even if I use it exclusive there).



Am 18.11.2017 21:33 schrieb "Kyle Beauchamp" <notifications@github.com>:

**Comment by johanneskoester** [comment]
We  have made changes to our build system (migrated from Travis CI to  Circle CI). If you would like to continue working on this PR, please  reopen this PR and update with latest upstream/master.

**Pull request closed without merging**
