### PR TITLE
restore bioconductor-preprocesscore fix

### PR DESCRIPTION
**Pull request by pinin4fjords**
I've been wrestling with bioconductor-affy due to problems similar to those described in https://support.bioconductor.org/p/122925/.

I'd just worked out the solution, only to discover that it had been [applied previously](https://github.com/bioconda/bioconda-recipes/pull/34970) but lost during a bulk update. Re-applying it now.

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Review by Midnighter — COMMENTED** [review]
According to the link this seems like a good fix. I'm just wondering because the linked discussion mentions that this is a problem specific to openblas and should **not** apply to blas.

I'm not too familiar with R compiled packages. Is the default a static compilation or how come libblas is not also a run time requirement?

**Comment by pinin4fjords** [comment]
@Midnighter to be honest I'm a little out of my depth and I'm guessing a bit. 

But my logic is this. This package is needed by the affy package, as is openblas. `justRMA()` from the affy package works fine locally on my Mac, but in the nf-core CI or locally in a container I'm getting the `ERROR; return code from pthread_create() is 22` error.

The linked post (and other googling suggested either pinning back openblas or the compilation fix here. The former is not practical (things have moved on too much in the package ecosystem to be using <0.3.4). The latter seemed a sensible solution, and since had already been applied (it was only removed due to a new BioC rather than an intentional removal), reinstating it seemed likely to be at worst harmless and at best may solve my problem.

**Review by Midnighter — APPROVED** [review]

**Comment by pinin4fjords** [comment]
Thanks @Midnighter

**Comment by pinin4fjords** [comment]
@BiocondaBot please merge

**Comment by pinin4fjords** [comment]
@BiocondaBot please merge

**Comment by pinin4fjords** [comment]
@BiocondaBot please merge

**Comment by rpetit3** [comment]
@BiocondaBot please fetch artifacts

**Review by rpetit3 — APPROVED** [review]

**Comment by rpetit3** [comment]
@BiocondaBot please merge

**Comment by pinin4fjords** [comment]
For anyone who comes across this, it did indeed address the `ERROR; return code from pthread_create() is 22` error in affy, [once incorporated into the affy recipe](https://github.com/bioconda/bioconda-recipes/pull/39047).

**Pull request merged**
