### PR TITLE
Add recipe for alfa

### PR DESCRIPTION
**Pull request by fgypas**
Add recipe for ALFA (https://pypi.org/project/alfa/)

### CODE REVIEW

**Comment by fgypas** [comment]
I don't get why this fails. The test was running for 5 and 1/2 hours...

**Comment by dpryan79** [comment]
@fgypas I fixed the resolve conflict but (A) the license file is missing (not a problem, we can ignore that) and (B) I of course don't know how strictly we need to follow the version restrictions you had originally specified.

**Comment by fgypas** [comment]
Hi @dpryan79 Thanks a lot. 
The version restrictions are based on this: https://github.com/biocompibens/ALFA/blob/master/setup.py I am also not sure, but I could test locally.
For the LICENCE I think that they are using MIT, so that should be fine as well I think. Please let me know, of you think we should process.

**Comment by dpryan79** [comment]
@fgypas Can you contact the package author and ask for advise? That'd be the ideal path forward.

**Comment by fgypas** [comment]
Hi @dpryan79 Done. 
Please see here: https://github.com/biocompibens/ALFA/issues/8

**Comment by fgypas** [comment]
Hi @dpryan79 
The conclusion is that we can be more lenient with the versions, but we do not have a specific recommendation (you can see the comments here: https://github.com/biocompibens/ALFA/issues/8
How do you think we should proceed?

**Comment by dpryan79** [comment]
@fgypas I've made an edit that I suspect will pass testing and match common package restrictions. Numpy and pybedtools should be pretty stable and I rather doubt a progress bar library is going to have frequent API-breaking changes. If you want to be a bit more conservative, perhaps set restrictions such that only a single major release version of dependencies is allowed (e.g., `numpy >=0115,<2`). That'd also be a perfectly acceptable way to proceed.

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
Anyway, I've gone ahead and approved this PR so you can have it merged whenever you'd like :)

**Comment by fgypas** [comment]
@BiocondaBot please merge

**Pull request merged**
