### PR TITLE
Update gatk(3) to fix resolving of old R version

### PR DESCRIPTION
**Pull request by jfy133**
This PR pins the version of R used in the 'old' GATK versions (GATK 3.5, 3.6, and 3.8).

When trying to install GATK3 versions alone will by default resolve to _old_ builds (build 6) of the versions that required the old `gatk-register` trick. Furthermore, when I tried to install GATK 3.5 myself, `conda` would get stuck on resolving (presumably due to the whole R package(s) issue).

I have here pinned the version of R to fix this.

I selected version r-base 3.2, as :

1. this is first R version that will automatically resolves to the _latest_ gatk bioconda build (i.e., without gatk-register), and 
2. is closest to the one used in the Broad institute's docker container(s) for GATK 3.5-3.8 (which is R version 3.1.1).

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by matthdsm** [comment]
This will break gatk3 in environments where both R and gatk3 is installed. Doesn't seem like a good idea to me...

**Comment by jfy133** [comment]
Good point... :\ do you have any suggestions how to get around the 'old-build' issue though (e.g. `r-base>=3.5`)?

It seems bad that one can't even get it to run if you install it 'alone'?

**Comment by matthdsm** [comment]
Personally, I'd drop the pin, because any pin will break environments. As for your other issue, I haven't encountered this yet. I suppose this is something @bioconda/core would be more suited to answer.

Matthias

**Comment by jfy133** [comment]
Thanks Matthias, I'll also ask on the gitter as well for suggestions.

**Comment by jfy133** [comment]
I played around a bit more and it seems that (unfortunately) the issue is that myself and another person have the same configuration issue (I think), but in other contexts the recipe works. Closing this anyway.

Thanks again for the advice @matthdsm

**Pull request closed without merging**
