### PR TITLE
Adapterremoval (v2) 

### PR DESCRIPTION
**Pull request by apeltzer**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by apeltzer** [comment]
Builds fine :-) https://circleci.com/gh/apeltzer/bioconda-recipes/22

**Comment by rizkg** [comment]
Hello, I encountered the same problem on my pull request. It turns out it is an issue (see  #8235 for details) when using a fork and circle-ci. 
To solve the issue, you have to disable circle-ci on your fork, and make a new commit. That will launch circle-ci on the bioconda repo with the mac os plan enabled.

**Comment by apeltzer** [comment]
HI @rizkg ! Thanks for the comment - I will just modify the documentation a bit and then recommit.

**Comment by apeltzer** [comment]
Seems to work fine :-)

**Comment by apeltzer** [comment]
Hi @johanneskoester  - after chatting with you right now, I thought I'll just ask you for a review ;-)

**Comment by apeltzer** [comment]
:tada:

**Pull request merged**
