### PR TITLE
fix strainGE

### PR DESCRIPTION
**Pull request by siebrenf**
- using a more generic `script`
- removing some `host` requirements (this might be too much)

### CODE REVIEW

**Comment by lrvdijk** [comment]
Thanks! I think I would add numpy and zlib as host requirements because we need the headers for our C++ extension. Can I push to this branch directly?

**Comment by siebrenf** [comment]
go for it!

**Comment by lrvdijk** [comment]
I get a permission denied error when trying to push to this branch, unfortunately. I can make a PR though.

**Comment by lrvdijk** [comment]
Pull request here #37433

**Comment by siebrenf** [comment]
@BiocondaBot please fetch artifacts

**Comment by siebrenf** [comment]
@BiocondaBot please fetch artifacts

**Comment by lrvdijk** [comment]
All seems to work fine!

Screen Shot 2023-01-18 at 10 25 38 AM

**Review by lrvdijk — APPROVED** [review]

**Comment by siebrenf** [comment]
Dear @bioconda/review, it took a while but this package recipe is fixed again.

**Review by mbhall88 — APPROVED** [review]

**Comment by mbhall88** [comment]
@BiocondaBot please merge

**Comment by mbhall88** [comment]
@BiocondaBot please update

**Comment by mbhall88** [comment]
@BiocondaBot please merge

**Comment by mbhall88** [comment]
Hmmm, not quite sure what's happening here? @bioconda/core

**Comment by mbhall88** [comment]
@BiocondaBot please fetch artifacts

**Comment by mbhall88** [comment]
@BiocondaBot please merge

**Pull request merged**
