### PR TITLE
rmblast 2.9.0

### PR DESCRIPTION
**Pull request by tseemann**
Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it. Note that if you are not already a member of the bioconda project (meaning that you can't add this label), please ping `@bioconda/core` so that your PR can be reviewed and merged (please note if you'd like to be added to the bioconda project). Please see https://github.com/bioconda/bioconda-recipes/issues/15332 for more details.

* [ ] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [ ] This PR adds a new recipe.
* [ ] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by tseemann** [comment]
```
01:51:09 BIOCONDA INFO Constraining to 1 git modified recipes (rmblast).
01:51:09 BIOCONDA INFO Ignoring 1 blacklisted recipes (rmblast).
```

I'm guessing there was a reason this is blacklisted?

**Comment by bgruening** [comment]
Usually, when it is not compiling anymore.

**Comment by tseemann** [comment]
Failing after 362m !!!!

**Comment by bgruening** [comment]
@tseemann have you seen:

```
07:31:31 BIOCONDA INFO (OUT) can't find file to patch at input line 231
07:31:31 BIOCONDA INFO (OUT) Perhaps you used the wrong -p or --strip option?
```

**Comment by nathanweeks** [comment]
I think `conda build` is guessing the wrong patch level (`patch -pLEVEL`) in this routine:
https://github.com/conda/conda-build/blob/master/conda_build/source.py#L506
I ran this manually with `bioconda-utils build --keep-old-work --git-range master`, and from the contents of the work directory, it appears that `-p0` is being guessed instead of `-p1`. It doesn't look like there's a way to manually specify the patch level?

I manually patched ncbi-blast-2.9.0+-src & did a more conda-build-friendly diff (patch attached), which `conda build` appears to accept. But then there are subsequent build issues. 

I've attempted to make the build.sh & meta.yaml as close to identical as the blast 2.9.0 recipe as possible:
https://github.com/bioconda/bioconda-recipes/blob/14431b17a502c9b811efc6a2d8f1b67469893079/recipes/blast/build.sh 
https://github.com/bioconda/bioconda-recipes/blob/14431b17a502c9b811efc6a2d8f1b67469893079/recipes/blast/meta.yaml
but have not had luck getting this to build so far.

[isb-2.9.0+-rmblast-p2.patch.txt](https://github.com/bioconda/bioconda-recipes/files/3691975/isb-2.9.0%2B-rmblast-p2.patch.txt)

**Comment by abretaud** [comment]
We'll need this for https://github.com/galaxyproject/tools-iuc/pull/2592, so trying something...

**Comment by tseemann** [comment]
Thanks @nathanweeks - i was unsure which `patch` options to use here. Please feel free to take over this PR attempt, I don't have time, it was a favour for @philippbayer

**Comment by abretaud** [comment]
@BiocondaBot recheck

**Comment by dpryan79** [comment]
Great job everyone!

**Comment by tseemann** [comment]
@abretaud this is _amazing_ effort!!!!

**Comment by philippbayer** [comment]
Wow, this is amazing, thank you so much!!

**Comment by nathanweeks** [comment]
@abretaud : +1 for the maker update!

**Pull request merged**
