### PR TITLE
Fix a couple snap issues

### PR DESCRIPTION
**Pull request by nathanweeks**
* [X ] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [ ] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ X] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

maker uses hmm-align.pl from snap, and was failing due to hard-coded "#!/usr/bin/perl". This patch:

- replaces the hard-coded "#!/usr/bin/perl" paths with "#!/usr/bin/env perl" in all included perl scripts
- fixes an issue in the generated snap driver script that could cause problems if any arguments were quoted strings containing spaces
- updates the meta.yaml to add some additional regression tests for the perl scripts, add a sha256, and correct the license

Note that cds-trainer.pl and noncoding-trainer.pl fail due to missing Perl libraries that are not currently available in bioconda, but can be obtained from:
https://github.com/KorfLab/Perl_utils

### CODE REVIEW

**Comment by druvus** [comment]
I would recommend to package the missing perl_utils in a separate package. I will see if I could assist in doing it later this week.

**Comment by bgruening** [comment]
@druvus what do you mean here? Anything that you would like to before merging?

**Comment by nathanweeks** [comment]
@dpryan79 : It looks like the only change that was made since this PR was submitted was the addition of a sha256 to the meta.yaml (and to clarify, this PR was for *snap*, not *snap-aligner*)

**Comment by dpryan79** [comment]
OK, I'll try to make this mergeable then.

**Comment by dpryan79** [comment]
@bioconda-bot update

**Comment by dpryan79** [comment]
If someone with a mac could look into the test failures on OSX (just run the conda install commands mentioned by the bot for it) then I'd appreciate it. I won't have a chance for a couple days.

**Comment by nathanweeks** [comment]
@dpryan79 : it looks like the osx test passed?

**Comment by dpryan79** [comment]
@nathanweeks I had it skip testing on OSX. Someone with a mac needs to install the binaries the bot posted and see why they fail testing.

**Comment by dpryan79** [comment]
It's completely unclear why the testing fails on OSX. I can install the package on a mac and the tests pass when I manually run them.

**Comment by nathanweeks** [comment]
OK, I'll try to debug next week.

**Comment by dpryan79** [comment]
The OSX failure appears to be due to a segfault in snap itself rather than an issue with something else. Perhaps this is caused by a clang issue, since it's not being thrown on Linux. Given that, it may be best to simply skip building on OSX.

**Comment by dpryan79** [comment]
Let's just skip Linux for now then.

**Comment by nathanweeks** [comment]
OK, strange that snap would segfault on OS X just displaying the usage message---could indicate a latent (on Linux/gcc) bug in the code? Anyway, thanks for tracking that down!

**Pull request merged**
