### PR TITLE
FastK is not officially versioned, so fall back to git checkouts

### PR DESCRIPTION
**Pull request by muffato**
The [FastK recipe](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/fastk/meta.yaml) is for a certain version 1.0 of FastK, but the version comes from a [fork](https://github.com/abueg/FASTK/releases/tag/v1.0) of the [original](https://github.com/thegenemyers/FASTK/releases) repository.
The original repository is constantly being updated (it's already ahead of the fork's version 1.0) but is unfortunately *not* versioned 😱 . The author has been [notified](https://github.com/thegenemyers/FASTK/issues/19#issuecomment-1328220851) but has not responded.

I think it's misleading to label this recipe as 1.0 and propose to use a commit SHA instead, like in https://github.com/bioconda/bioconda-recipes/blob/master/recipes/bamaddrg/meta.yaml

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by muffato** [comment]
I don't understand the error "make: gcc: No such file or directory". I didn't change the actual build steps and requirements, only how the software is being checked out

**Comment by matthdsm** [comment]
I'm not really sure the `build.sh` is entirely correct though.
We shouldn't compile htslib in place, but link to an existing one from the dependencies. Same for the other libs

**Comment by rpetit3** [comment]
I agree with @matthdsm let's try and move htlib and libdeflate to the meta.yaml

**Comment by rpetit3** [comment]
Let's see what happens, the makefile from fastk makes me think it might not work

**Comment by muffato** [comment]
I can try, but htslib (and libdeflate) are shipped together with Fastk. Are we allowed to modify a software like this ?
Also, I can't tell which versions precisely are embedded, and there's a risk that the version Conda would pick is incompatible.

**Comment by rpetit3** [comment]
@muffato I noticed that, I think for this case leave the htslib and libdeflate that comes with fastk. we might have to tweak the flags now.

latest issue is missing `zlib.h` which should be there

**Comment by muffato** [comment]
Hi @rpetit3 . I did some experiments in #38324.
I've got the feeling I could bypass the embedded htslib and libdeflate, by fooling the Makefile into thinking the rules are up-to-date, but then yes, it complains about `zlib.h` missing. The file is actually there (`find / -name zlib.h`) but it's somehow not found by the compiler. I tried setting and unsetting `CFLAGS` & co but couldn't make it work :/

**Pull request closed without merging**
