### PR TITLE
smalt-0.7.6 (new recipe)

### PR DESCRIPTION
**Pull request by moskalenko**
- [x] I have read the guidelines above.
- [x] This PR adds a new recipe.
- [ ] This PR updates an existing recipe.
- [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by moskalenko** [comment]
GCC 2016 hackathon

**Comment by bgruening** [comment]
Mh ...
```
+ ./configure --prefix=/anaconda/envs/_build

configure: WARNING: library not found

+ make

sequence.c:194:10: error: unknown type name ‘gzFile’

          gzFile fp,
```

**Comment by apetkau** [comment]
Hey, I was looking at integrating some tools we use including smalt.  We use smalt complied against bambamc https://github.com/gt1/bambamc which allows for direct read/write of sam/bam files.  I have added to conda https://github.com/bioconda/bioconda-recipes/pull/1839.  I can add this as a dependency afterwards if you want?

**Comment by druvus** [comment]
Smalt 0.7.6 is now included in bioconda.

**Pull request closed without merging**
