### PR TITLE
Update fwdpy11 to 0.5.4

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`fwdpy11`](https://bioconda.github.io/recipes/fwdpy11/README.html): **0.5.3** &rarr; **0.5.4**

[install with bioconda](http://bioconda.github.io/recipes/fwdpy11/README.html) [Conda](https://anaconda.org/bioconda/fwdpy11/files)

Info | Link
-----|-----
Recipe | [`recipes/fwdpy11`](https://github.com//bioconda/bioconda-recipes/tree/bump/fwdpy11/recipes/fwdpy11) (click to view/edit other files)
Releases |[https://pypi.org/pypi/fwdpy11/json](https://pypi.org/pypi/fwdpy11/json)

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by molpopgen** [comment]
The Mac OS build is failing.  Any way to see a detailed error message?  The CI doesn't show exactly what failed.

**Comment by molpopgen** [comment]
The macOS build failure is not reproducible on my MBPro with Catalina and the conda clang compilers installed.  Hard to diagnose what the CI is having an issue with.

**Comment by dpryan79** [comment]
The OSX error was "no module named pip".

**Comment by dpryan79** [comment]
@bioconda-bot please fetch artifacts

**Comment by dpryan79** [comment]
@bioconda-bot please merge

Guess that fixed it.

**Pull request merged**
