### PR TITLE
Update phylofisher to 1.2.10

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`phylofisher`](https://bioconda.github.io/recipes/phylofisher/README.html): **1.2.9** &rarr; **1.2.10**

[install with bioconda](http://bioconda.github.io/recipes/phylofisher/README.html) [Conda](https://anaconda.org/bioconda/phylofisher/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/phylofisher`](https://github.com//bioconda/bioconda-recipes/tree/bump/phylofisher/recipes/phylofisher) (click to view/edit other files)
Summary | A package for the creation, analysis, and visualization of eukaryotic phylogenomic datasets.
Home | [https://github.com/TheBrownLab/PhyloFisher](https://github.com/TheBrownLab/PhyloFisher)
Releases |[https://github.com/TheBrownLab/PhyloFisher/tags](https://github.com/TheBrownLab/PhyloFisher/tags)
Author | `@TheBrownLab`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by robert-ervin-jones** [comment]
Hey @rpetit3. Can you or someone else help me troubleshoot this when you get a chance? Thanks in advance!

**Comment by rpetit3** [comment]
Is it possible to loosen the dependencies a little, specifically blast?

**Comment by robert-ervin-jones** [comment]
Yes, I can try. Will I need to open another PR or is there a way to update it in this one?

**Comment by robert-ervin-jones** [comment]
I don't have permission to push here.

**Pull request closed without merging**
