### PR TITLE
Add recipe for taxidTools

### PR DESCRIPTION
**Pull request by gregdenay**
Adds a recipe for the TaxidTools python package.
This is a package to handle taxonomy definitions as hierarchical trees in native Python, allowing common operations such as lineage analysis, last common ancestor or consensus determination, branch filtering, pruning, normalization, import and export as JSON, etc...

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

### General instructions

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

### Instructions for avoiding API, ABI, and CLI breakage issues
Conda is able to record and lock (a.k.a. pin) dependency versions used at build time of other recipes.
This way, one can avoid that expectations of a downstream recipe with regards to API, ABI, or CLI are violated by later changes in the recipe.
If not already present in the meta.yaml, make sure to specify `run_exports` (see [here](https://bioconda.github.io/contributor/linting.html#missing-run-exports) for the rationale and comprehensive explanation).
Add a `run_exports` section like this:

```yaml
build:
  run_exports:
    - ...

```

with `...` being one of:

| Case                             | run_exports statement                                               |
| -------------------------------- | ------------------------------------------------------------------- |
| semantic versioning              | `{{ pin_subpackage("myrecipe", max_pin="x") }}`     |
| semantic versioning (0.x.x)      | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}`   |
| known breakage in minor versions | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| known breakage in patch versions | `{{ pin_subpackage("myrecipe", max_pin="x.x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| calendar versioning              | `{{ pin_subpackage("myrecipe", max_pin=None) }}`    |

while replacing `"myrecipe"` with either `name` if a `name|lower` variable is defined in your recipe or with the lowercase name of the package in quotes.

### Bot commands for PR management

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

Note that the <code>@BiocondaBot please merge</code> command is now depreciated. Please just squash and merge instead.

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by gregdenay** [comment]
@BiocondaBot please add label

**Comment by gregdenay** [comment]
@BiocondaBot please update

**Comment by rpetit3** [comment]
@BiocondaBot please fetch artifacts

**Comment by martin-g** [comment]
The build has failed. Please investigate!

**Comment by gregdenay** [comment]
Need to wait for Azure problems to be fixed

**Comment by gregdenay** [comment]
Build fails locally with (only relevant part of the log):
```{bash}
$ bioconda-utils build --docker --mulled-test --packages taxidtools
14:02:06 BIOCONDA INFO (COMMAND) mulled-build build-and-test taxidtools=2.3.0--pyhdfd78af_0 -n biocontainers --test bash -c '/usr/local/env-execute true && . /usr/lo             cal/env-activate.sh && pip check' --channels conda-forge,file:///home/debian/anaconda3/envs/bioconda/conda-bld,bioconda,defaults --involucro-path /home/debian/anacon             da3/envs/bioconda/lib/python3.10/site-packages/bioconda_utils/involucro
14:02:06 BIOCONDA INFO (OUT) Executing: /home/debian/anaconda3/envs/bioconda/lib/python3.10/site-packages/bioconda_utils/involucro -v=2 -f /home/debian/anaconda3/env             s/bioconda/lib/python3.10/site-packages/galaxy/tool_util/deps/mulled/invfile.lua -set CHANNELS=conda-forge,file:///home/debian/anaconda3/envs/bioconda/conda-bld,bioc             onda,defaults -set TARGETS=taxidtools=2.3.0=pyhdfd78af_0 -set REPO=quay.io/biocontainers/taxidtools:2.3.0--pyhdfd78af_0 -set BINDS=build/dist:/usr/local/,/home/debia             n/anaconda3/envs/bioconda/conda-bld:/home/debian/anaconda3/envs/bioconda/conda-bld -set DEST_BASE_IMAGE=quay.io/bioconda/base-glibc-busybox-bash:3.0 -set CONDA_IMAGE             =quay.io/bioconda/create-env:latest -set 'TEST=bash -c '"'"'/usr/local/env-execute true && . /usr/local/env-activate.sh && pip check'"'"'' -set CONDA_BIN=conda build             -and-test
14:02:06 BIOCONDA INFO (ERR) [May 13 14:02:06] DEBU Run file [/home/debian/anaconda3/envs/bioconda/lib/python3.10/site-packages/galaxy/tool_util/deps/mulled/invfile.             lua]
14:02:06 BIOCONDA INFO (ERR) [May 13 14:02:06] INFO Invoke Task [build]
14:02:06 BIOCONDA INFO (ERR) [May 13 14:02:06] STEP Run image [quay.io/bioconda/create-env:latest] with command [[rm -rf /data/dist]]
14:02:06 BIOCONDA INFO (ERR) [May 13 14:02:06] DEBU Creating container [step-2c43582175]
14:02:06 BIOCONDA INFO (ERR) [May 13 14:02:06] DEBU Created container [bfb3a8e02bea step-2c43582175], starting it
14:02:07 BIOCONDA INFO (ERR) [May 13 14:02:07] DEBU Container [bfb3a8e02bea step-2c43582175] started, waiting for completion
14:02:07 BIOCONDA INFO (ERR) [May 13 14:02:07] DEBU Container [bfb3a8e02bea step-2c43582175] completed with exit code [0] as expected
14:02:07 BIOCONDA INFO (ERR) [May 13 14:02:07] DEBU Container [bfb3a8e02bea step-2c43582175] removed
14:02:07 BIOCONDA INFO (ERR) [May 13 14:02:07] STEP Run image [quay.io/bioconda/create-env:latest] with command [[/bin/sh -c conda install  -c 'conda-forge' -c 'file             :///home/debian/anaconda3/envs/bioconda/conda-bld' -c 'bioconda' -c 'defaults'  'taxidtools=2.3.0=pyhdfd78af_0' --strict-channel-priority -p /usr/local --copy --yes              --quiet&&create-env --conda=: /usr/local]]
14:02:07 BIOCONDA INFO (ERR) [May 13 14:02:07] DEBU Creating container [step-e5a68a9ac4]
14:02:07 BIOCONDA INFO (ERR) [May 13 14:02:07] DEBU Created container [1dac623c30df step-e5a68a9ac4], starting it
14:02:07 BIOCONDA INFO (ERR) [May 13 14:02:07] DEBU Container [1dac623c30df step-e5a68a9ac4] started, waiting for completion
..14:04:22 BIOCONDA INFO (ERR) [May 13 14:04:22] SOUT Collecting package metadata (repodata.json): ...working... done
14:04:25 BIOCONDA INFO (ERR) [May 13 14:04:25] SOUT Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
14:04:36 BIOCONDA INFO (ERR) [May 13 14:04:36] SOUT Solving environment: ...working...
14:04:36 BIOCONDA INFO (ERR) [May 13 14:04:36] SOUT Found conflicts! Looking for incompatible packages.
14:04:36 BIOCONDA INFO (ERR) [May 13 14:04:36] SOUT This can take several minutes.  Press CTRL-C to abort.
14:04:38 BIOCONDA INFO (ERR) [May 13 14:04:38] SOUT failed
Examining conflict for python __glibc:   0%|          | 0/5 [00:00<?, ?it/s]                 0/5 [00:00<?, ?it/s]
14:04:38 BIOCONDA INFO (ERR) [May 13 14:04:38] SERR UnsatisfiableError: The following specifications were found to be incompatible with your system:
14:04:38 BIOCONDA INFO (ERR) [May 13 14:04:38] SERR
14:04:38 BIOCONDA INFO (ERR) [May 13 14:04:38] SERR - feature:/linux-64::__glibc==2.36=0
14:04:38 BIOCONDA INFO (ERR) [May 13 14:04:38] SERR - python[version='>=3.9'] -> libgcc-ng[version='>=10.3.0'] -> __glibc[version='>=2.17']
14:04:38 BIOCONDA INFO (ERR) [May 13 14:04:38] SERR
14:04:38 BIOCONDA INFO (ERR) [May 13 14:04:38] SERR Your installed version is: 2.36
14:04:38 BIOCONDA INFO (ERR) [May 13 14:04:38] SERR
14:04:38 BIOCONDA INFO (ERR) [May 13 14:04:38] SERR Note that strict channel priority may have removed packages required for satisfiability.
14:04:38 BIOCONDA INFO (ERR) [May 13 14:04:38] SERR
14:04:46 BIOCONDA INFO (ERR) [May 13 14:04:46] ERRO Task processing failed: Unexpected exit code [1] of container [1dac623c30df step-e5a68a9ac4], container preserved
14:04:46 BIOCONDA INFO (OUT) ...
14:04:46 BIOCONDA ERROR COMMAND FAILED (exited with 1): mulled-build build-and-test taxidtools=2.3.0--pyhdfd78af_0 -n biocontainers --test bash -c '/usr/local/env-execute true && /usr/local/env-activate.sh && pip check' --channels conda-forge,file:///home/debian/anaconda3/envs/bioconda/conda-bld,bioconda,defaults --involucro-path /home/debian/anaconda3/es/bioconda/lib/python3.10/site-packages/bioconda_utils/involucro

14:04:46 BIOCONDA ERROR TEST FAILED: recipes/taxidtools
14:04:46 BIOCONDA INFO (COMMAND) conda build purge
14:04:46 BIOCONDA ERROR BUILD SUMMARY: of 1 recipes, 1 failed and 0 were skipped. Details of recipes and environments follow.
14:04:46 BIOCONDA ERROR BUILD SUMMARY: FAILED recipe recipes/taxidtools
```

Points to a weird version problem of __glibc

**Comment by gregdenay** [comment]
@martin-g any clue what is happening here?

**Comment by martin-g** [comment]
I am not sure but I think the problem is that the mulled test uses Docker containers with old Glibc (ver. 2.17, I think) while the software requires newer.

**Comment by gregdenay** [comment]
Weird that it was still working with bioconda-utils 2.14.
Should I move the issue there?

**Comment by martin-g** [comment]
> Should I move the issue there?

Please do! It might be some kind of a regression.

**Pull request closed without merging**
