### PR TITLE
r23

### PR DESCRIPTION
**Pull request by bgruening**
- [x] I have read the guidelines above.
- [ ] This PR adds a new recipe.
- [x] This PR updates an existing recipe.
- [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by bgruening** [comment]
@daler do you have any idea why OSX is failing here? https://travis-ci.org/bioconda/bioconda-recipes/jobs/171764189

The only error I can spot is the 80 character limit.

**Comment by daler** [comment]
Yep, looks like it. I guess that package name is too long since others seem ok?

**Comment by bgruening** [comment]
It's building for Linux ...

**Comment by daler** [comment]
True, and everything should be installing into /anaconda on either OS. Maybe there's something osx-specific in conda code? Does artificially shrinking the package name help?

**Comment by bgruening** [comment]
It still fails even with a short package-name.

**Comment by bgruening** [comment]
xref: https://github.com/conda/conda-build/issues/1484

**Comment by bgruening** [comment]
@daler we are currently not building packages in parallel, we should at some point but for now do you think we can add `--no-build-id` into the build process until the rebuilding in conda-forge and Co is done?

**Comment by daler** [comment]
I didn't even know parallel builds were an option, this solution seems worth a shot.

**Comment by bgruening** [comment]
Since conda-build-2 we can build packages in parallel, thinking about building dags in parallel ....
Should I go ahead and hardcode `--no-build-id` in bioconda-utils?

**Comment by bgruening** [comment]
@daler https://github.com/bioconda/bioconda-utils/pull/25

**Comment by daler** [comment]
Go for it. I think we might be limited to a single travis-ci processor, so parallel might not help us.

**Pull request merged**
