### PR TITLE
Add pstools recipe.

### PR DESCRIPTION
**Pull request by junaruga**
Describe your pull request here

This PR is to enable the bio tool [pstools](https://github.com/shilpagarg/pstools). I am working with the author of the tool in a same team.

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by bgruening** [comment]
> 20:32:30 BIOCONDA INFO (OUT) make: g++: No such file or directory

I assume g++ is hardcoded?

**Comment by junaruga** [comment]
> I assume g++ is hardcoded?

Yes the `g++` is hardcored in `Makefile`. I will modify the `Makefile` to see the `CXX` environment variable.

Seeing the log of the CI, I see the `CXX` is set like this.

> 20:32:30 BIOCONDA INFO (OUT) +CXX=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-c++

**Comment by junaruga** [comment]
> I will modify the Makefile to see the CXX environment variable.

I rebased the PR modifying the `Makefile` to check the `CXX`.

**Comment by junaruga** [comment]
@bgruening Could you review again? Thanks.

**Comment by junaruga** [comment]
Now we cannot see the zlib header. Let me fix it.

```
(OUT) graph.h:6:10: fatal error: zlib.h: No such file or directory
10:53:37 BIOCONDA INFO (OUT)     6 | #include <zlib.h>
10:53:37 BIOCONDA INFO (OUT)       |          ^~~~~~~
```

**Comment by junaruga** [comment]
In case of Debian based Linux the the zlib devel package `zlib1g-dev` should be installed. But how to set the package in `meta.yaml`?

**Comment by bgruening** [comment]
The Makefie is probably off and does not respect the env variables. Have a look here: https://bioconda.github.io/contributor/troubleshooting.html?highlight=zlib#zlib-errors

**Comment by junaruga** [comment]
Ah you are right. In the process of the CI, I see zlib "conda pacakge" is installed. On my local the zlib conda package's `zlib.h` is installed at `~/miniconda3/include/zlib.h`. I will modify to refer `CXXFLAGS` and `LDFLAGS`.

```
11:24:54 BIOCONDA INFO (OUT)     zlib:          1.2.11-h36c2ea0_1013 conda-forge
```

I see that the `LDFLAGS` and `CXXFLAGS` are set in the process.

```
11:26:09 BIOCONDA INFO (OUT) +LDFLAGS=-Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-rpath,$PREFIX/lib -Wl,-rpath-link,$PREFIX/lib -L$PREFIX/lib
11:26:09 BIOCONDA INFO (OUT) INFO: activate-gxx_linux-64.sh made the following environmental changes:
11:26:09 BIOCONDA INFO (OUT) +CXXFLAGS=-fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/pstools-0.2a2 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
```

**Comment by junaruga** [comment]
I rebaesd again.

Seeing a list of the testing tasks. Is there a way to avoid the test `test-macos`, as it seems the build doesn't work on it.
https://github.com/bioconda/bioconda-recipes/pull/31472/checks?check_run_id=4165642116

```
    lint - Success
    test-linux - Running
    test-macos - Blocked
```

**Comment by bgruening** [comment]
You can skip a build on certain architectures ... `skip: True # [osx]`

**Comment by junaruga** [comment]
OK. Now I added the skip logic to skip the osx. On the latest build, I see the Linux build is success on the CI.
https://app.circleci.com/pipelines/github/bioconda/bioconda-recipes/55683/workflows/03586347-6da8-4e23-b1b3-7e099cb775a2/jobs/175191

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
@bioconda-bot please merge

**Pull request merged**
