### PR TITLE
Update phyloacc

### PR DESCRIPTION
**Pull request by gwct**
This updates the phyloacc build script to add a post-processing script (phyloacc_post.py) to the environment path.

----

### CODE REVIEW

**Comment by gwct** [comment]
@BiocondaBot please add label

**Comment by mfansler** [comment]
@gwct it's preferable to test all entry points. Is there a reasonable test that could be run against this additional script? e.g., would it accept a `--help` argument?

**Comment by gwct** [comment]
> @gwct it's preferable to test all entry points. Is there a reasonable test that could be run against this additional script? e.g., would it accept a `--help` argument?

@mfansler sure, I added the test. I was/am wary because the source might need to be updated for the test to pass and I wanted to update the recipe first. But maybe I should've done it the other way around. Guess we'll see.

**Comment by dpryan79** [comment]
@BiocondaBot please fetch artifacts

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@BiocondaBot please merge

**Pull request merged**
