### PR TITLE
Update chisel to 1.1.4

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`chisel`](https://bioconda.github.io/recipes/chisel/README.html): **1.1.3** &rarr; **1.1.4**

[install with bioconda](http://bioconda.github.io/recipes/chisel/README.html) [Conda](https://anaconda.org/bioconda/chisel/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/chisel`](https://github.com//bioconda/bioconda-recipes/tree/bump/chisel/recipes/chisel) (click to view/edit other files)
Summary | Copy-number Haplotype Inference in Single-cell by Evolutionary Links
Home | [https://github.com/raphael-group/chisel](https://github.com/raphael-group/chisel)
Releases |[https://github.com/raphael-group/chisel/tags](https://github.com/raphael-group/chisel/tags)
Author | `@raphael-group`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Review by simozacca — APPROVED** [review]

**Comment by simozacca** [comment]
@bioconda/core Hi everyone, could you please help me to figure out why these checks above are failing? This is an update of an already existing package, which did not introduce any build or setup update. Thank you!

**Comment by rpetit3** [comment]
@simozacca looks like the linter didn't like the lack of whitespace between the program and version. Lets see if this gets it going for you

**Comment by dpryan79** [comment]
@BiocondaBot please merge

**Comment by simozacca** [comment]
> @simozacca looks like the linter didn't like the lack of whitespace between the program and version. Lets see if this gets it going for you

Thank you so much!

**Pull request merged**
