### PR TITLE
Update pypgx to 0.14.0

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`pypgx`](https://bioconda.github.io/recipes/pypgx/README.html): **0.13.0** &rarr; **0.14.0**

[install with bioconda](http://bioconda.github.io/recipes/pypgx/README.html) [Conda](https://anaconda.org/bioconda/pypgx/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/pypgx`](https://github.com//bioconda/bioconda-recipes/tree/bump/pypgx/recipes/pypgx) (click to view/edit other files)
Summary | A Python package for pharmacogenomics research
Home | [https://github.com/sbslee/pypgx](https://github.com/sbslee/pypgx)
Releases |[https://pypi.org/pypi/pypgx/json](https://pypi.org/pypi/pypgx/json)
Recipe Maintainer(s) | @sbslee

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Review by sbslee — APPROVED** [review]
No dependencies changed. Approving the commit.

**Comment by sbslee** [comment]
Dear @bioconda/core,

Could anyone from bioconda team please take a look at why pypgx 0.14.0 build is failing at test_linnux? I've already re-ran three times without luck. This has never happened to me before, and the output message doesn't seem to help. I'd greatly appreciate if someone can give me guidance.

**Comment by dpryan79** [comment]
@BiocondaBot please fetch artifacts

**Comment by dpryan79** [comment]
@BiocondaBot please merge

**Pull request merged**
