### PR TITLE
Update pangolin-data to 1.13

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`pangolin-data`](https://bioconda.github.io/recipes/pangolin-data/README.html): **1.12** &rarr; **1.13**

[install with bioconda](http://bioconda.github.io/recipes/pangolin-data/README.html) [Conda](https://anaconda.org/bioconda/pangolin-data/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/pangolin-data`](https://github.com//bioconda/bioconda-recipes/tree/bump/pangolin_data/recipes/pangolin-data) (click to view/edit other files)
Summary | Repository for storing latest model, protobuf, designation hash and alias files for pangolin assignments
Home | [https://github.com/cov-lineages/pangolin-data](https://github.com/cov-lineages/pangolin-data)
Releases |[https://github.com/cov-lineages/pangolin-data/tags](https://github.com/cov-lineages/pangolin-data/tags)
Author | `@cov-lineages`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Review by cbrueffer — APPROVED** [review]

**Comment by cbrueffer** [comment]
@bioconda-bot please merge

**Comment by mg14** [comment]
It seems as if this build was triggered prematurely from a prerelease which bumped the version, but led to a bioconda package versioned 1.13 which however provides pangolin-data 1.12, see https://github.com/cov-lineages/pangolin-data/issues/22

I'm not sure what the exact bioconda build process is, but I think it could be rectified by another PR as above that updates `recipes/pangolin-data/meta.yml` with the correct source SHA `c70f871aa9b7736292a220bbc692c6ed3ae55c49718e7a411ede5c3d0a60df5d` for the package archive.

Happy to do this if this was the way to go and apologies if this doesn't make any sense.

**Comment by cbrueffer** [comment]
Thanks for the notice, looks like I didn't pay enough attention. What you propose is exactly right, please bump the build number as well.

**Comment by mg14** [comment]
Great, thanks for the swift reply. Will do.

**Comment by corneliusroemer** [comment]
@cbrueffer how can we avoid this scenario in the future? It's apparently normal for pangolin to make pre-releases so we may end up in a similar bind in the future - having something out which says v1.14 on the tin but isn't actually v1.14 inside, still v1.13.

**Comment by cbrueffer** [comment]
The main issue to me is that the distribution tarball get rerolled without changing the tag, so the same file will have different content depending on when you download it; from a packaging point of view, not only for Bioconda, that's not good. Prereleases are fine, but there are widely used ways to mark those, e.g. by adding a `-rc`, `-prerelease` or similar suffix.

I think from a Bioconda perspective the only thing we can do is paying extra attention.

**Comment by cbrueffer** [comment]
Just to add, if you're interested and invested in this package, please feel free to mark yourself as maintainer.

**Pull request merged**
