### PR TITLE
Add bcftools to the ngscheckmate recipe

### PR DESCRIPTION
**Pull request by SPPearce**
The ngscheckmate recipe is missing bcftools, which is required for the bam mode.

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by SPPearce** [comment]
@BiocondaBot please add label

**Review by rpetit3 — APPROVED** [review]

**Comment by rpetit3** [comment]
Thank you @SPPearce

**Comment by jmarshall** [comment]
What is the reason for pinning this to bcftools 1.3.1?

The recipe requires the exact version `samtools 1.14`, and the conversation on PR #32558 suggests that that pinning was simply over-constraining to speed up environment solving rather than necessary in any way.

The only relevant use of bcftools in NGSCheckMate is the `bcftools call -c` invocation in _ncm.py_. This will work just as well in current bcftools as in 1.3.1. So I suspect that the only samtools & bcftools version requirements ngscheckmate might really need are:

```
     - samtools >=1.14
     - bcftools >=1.14
```

**Comment by SPPearce** [comment]
@jmarshall , yes, that is probably true. To be honest, I checked the bcftools recipe for what versions exist, and saw 1.3 and 1.3.1 in subfolders and so used 1.3.1. But now I see I missed the most up-to-date version 1.15 in the base folder.

I'm very new to bioconda, basically using it to make biocontainers for tools to use in nextflow, so don't really know what the knock-on effects of pinning it to a specific version is.

**Comment by jmarshall** [comment]
The knock on effect is that NGSCheckMate users get buggier less capable software, and bioconda is required to maintain legacy versions of software unnecessarily.

The slow environment solving will be primarily due to python and especially R. So probably there is no need to specify samtools/bcftools versions at all, and you might consider making a further PR that (bumps the build number again and) just uses nonspecific dependencies on samtools/bcftools:

```
  - samtools
  - bcftools
```

**Comment by SPPearce** [comment]
@jmarshall , I have made a PR to remove the dependencies: #33443 .

**Pull request merged**
