### PR TITLE
Update cutadapt to 2.9

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`cutadapt`](https://bioconda.github.io/recipes/cutadapt/README.html): **2.8** &rarr; **2.9**

[install with bioconda](http://bioconda.github.io/recipes/cutadapt/README.html) [Conda](https://anaconda.org/bioconda/cutadapt/files)

Info | Link
-----|-----
Recipe | [`recipes/cutadapt`](https://github.com//bioconda/bioconda-recipes/tree/bump/cutadapt/recipes/cutadapt) (click to view/edit other files)
Releases |[https://pypi.org/pypi/cutadapt/json](https://pypi.org/pypi/cutadapt/json)

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by marcelm** [comment]
@BioCondaBot please merge

**Comment by bgruening** [comment]
@BiocondaBot please merge

**Comment by marcelm** [comment]
@bgruening Why was my approval not sufficient?

**Comment by bgruening** [comment]
The approval was probably correct, maybe the bot was sleeping?

**Comment by marcelm** [comment]
Ok, assuming it’s a hickup. Was just worried that the rules have changed.

**Pull request merged**
