### PR TITLE
pysamstats: pin pysam version

### PR DESCRIPTION
**Pull request by lparsons**
* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [X] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [X] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by lparsons** [comment]
@alimanfoo While I think the recent update (and hence rebuild) of pysamstats resolved the issue for now, this should prevent errors like https://github.com/alimanfoo/pysamstats/issues/94 in the future.

**Comment by lparsons** [comment]
Should also fix #12466.

**Comment by dpryan79** [comment]
@bioconda-bot merge

**Comment by dpryan79** [comment]
Thanks @lparsons!

**Comment by alimanfoo** [comment]
Thanks @lparsons, much appreciated :+1:

**Comment by alimanfoo** [comment]
Just learning about [how pin_compatible works](https://docs.conda.io/projects/conda-build/en/latest/resources/variants.html#pinning-at-the-recipe-level) and wondering if this should be ``{{ pin_compatible('pysam', max_pin='x.x') }}``. Pysam does not follow semver and regularly changes it's cython/C API between minor versions.

**Comment by alimanfoo** [comment]
Advice appreciated, I'm still a novice about how (bio)conda builds work.

**Comment by dpryan79** [comment]
Looking at the repodata you're correct. Can you make a PR?

**Comment by alimanfoo** [comment]
> Looking at the repodata you're correct. Can you make a PR?

Happy to. I'm still a bit murky on what exactly `pin_compatible` is doing, I'd be grateful if you could confirm whether it should be:

``pin_compatible('pysam', max_pin='x.x')``

...or whether it should be an explicit version number, e.g.:

``pin_compatible('pysam', max_pin='0.16')``

**Comment by dpryan79** [comment]
The `x.x` version is what's needed, then when new pysam releases come out that doesn't need to be changed. For pysam this might actually need to be `x.x.x` to match the htslib pinning.

**Comment by epruesse** [comment]
What do you mean by matching the htslib pinning?

**Comment by dpryan79** [comment]
Just that we pin to exact versions of htslib (I think at least).

**Comment by epruesse** [comment]
Hmm. I don't know. We need to somehow parse `pin_compatible` for update_pinnings...

**Pull request merged**
