### PR TITLE
Pbsuite

### PR DESCRIPTION
**Pull request by mictadlo**
* [x] I have read the guidelines above.
* [X] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

continue from https://github.com/bioconda/bioconda-recipes/pull/4223

### CODE REVIEW

**Comment by johanneskoester** [comment]
I guess pbsuite contains more python modules than what you copy to bin. I would recommend to look up the installation instructions they provide. Unfortunately, it does not seem to be a proper Python package...

**Comment by mictadlo** [comment]
== III. Installation(https://sourceforge.net/p/pb-jelly/wiki/Home/) ==

1. Edit setup.sh and change $SWEETPATH to the full directory where 
you've placed the package.

2. To automatically place the package into your environment, add
> source /setup.sh
to your .bash_profile.
Be sure to source your .bash_profile (or just setup.sh) before 
using Jelly

```
ls pbsuite/
honey  __init__.py  __init__.pyc  jelly  utils
```
Should I copy the `pbsuite` folder to the `bin` folder?

**Comment by johanneskoester** [comment]
No, bin may not be contaminated with non-executables. You can put the whole stuff in `$PREFIX/opt/pbsuite` and then have a wrapper that calls the executables from within the folder. See the [savage recipe](https://github.com/bioconda/bioconda-recipes/tree/master/recipes/savage) for an example.

**Comment by mictadlo** [comment]
@johanneskoester I added to build.sh the following lines:

```
#!/bin/bash

PACKAGE_HOME=$PREFIX/opt/$PKG_NAME-$PKG_VERSION

mkdir -p $PACKAGE_HOME
mkdir -p $PREFIX/bin

cp -R $SRC_DIR/pbsuite $PACKAGE_HOME
cp bin/*.py $PREFIX/bin/
```

After `conda build recipe/pbsuite` I added `sys.path.append('/anaconda/conda-bld/pbsuite_1490823990330/_t_env/opt/pbsuite-15.8.24')`  to `bin/Jelly.py` and it worked. 

How could I modify the above `build.sh`, because I did not quite understand the savage wrapper?

Thank you in advance

Michal

**Comment by mictadlo** [comment]
I also asked [here](http://unix.stackexchange.com/questions/354715/inserting-text-between-two-lines) how to get sed command running for Linux and Mac.

**Comment by johanneskoester** [comment]
The savage wrapper is just a shell script that calls the python script in the `$PACKAGE_HOME` and forwards all arguments via `$@`. Might be easier than patching sys path, especially because I am not sure if that will be portable (conda would have to update that on each installation).

**Comment by mictadlo** [comment]
Wrapper did not work out or did I do anything wrong?

**Comment by johanneskoester** [comment]
The wrapper is fine, but you have to also consider those other (admittedly weird) steps they require in their installation instructions.

**Comment by johanneskoester** [comment]
To be honest, I am really becoming tired of people using Python but *not* making use of the build in packaging facilities of Python. It is really easy. Why do I keep seing all these hand crafted, often broken solutions.

**Comment by johanneskoester** [comment]
So, after looking at the setup.sh, I think all you need to do is adding prepending a proper definition of PYTHONPATH to the command invocation in your wrapper script. Replacing the command with `"PYTHONPATH=$PACKAGE_HOME:\$PYTHONPATH $PACKAGE_HOME/bin/Jelly.py \$@"` should work.

**Comment by jerowe** [comment]
Admittedly I don't know much about python packaging, but how difficult is it to bootstrap it as a proper python package with a setup.py ?

**Comment by mictadlo** [comment]
Hi, I failed to find all Python files and automatically to create a wrapper for them in the following way:
```
for f in bin/*.py
do
  echo "Processing $f file..."
  fn=basename $f

  WRAPPER=$PREFIX/bin/$fn
  echo "#!/bin/sh" > $WRAPPER
  echo "PYTHONPATH=$PACKAGE_HOME:\$PYTHONPATH $PACKAGE_HOME/bin/$fn \$@" >> $WRAPPER
  chmod +x $WRAPPER
done
```
What did I miss?

Thank you in advance.

Michal

**Comment by johanneskoester** [comment]
Looks like it should work. Maybe you should debug it outside of travis.

**Comment by mictadlo** [comment]
On my Mac I got:
```
$ conda build recipes/pbsuite
BUILD START: pbsuite-15.8.24-py27_0
    (actual version deferred until further download or env creation)
updating index in: /anaconda/conda-bld/osx-64
updating index in: /anaconda/conda-bld/noarch

The following NEW packages will be INSTALLED:

    openssl:    1.0.2k-1     
    pip:        9.0.1-py27_1 
    python:     2.7.13-0     
    readline:   6.2-2        
    setuptools: 27.2.0-py27_0
    sqlite:     3.13.0-0     
    tk:         8.5.18-0     
    wheel:      0.29.0-py27_0
    zlib:       1.2.8-3      


WARNING: conda-build appears to be out of date. You have version 2.1.1 but the
latest version is 2.1.10. Run

conda update -n root conda-build

to get the latest version.

Source cache directory is: /anaconda/conda-bld/src_cache
Found source in cache: pbsuite_15.8.24.tar.gz
Extracting download
BUILD START (revised): pbsuite-15.8.24-py27_0
Package: pbsuite-15.8.24-py27_0
source tree in: /anaconda/conda-bld/pbsuite_1492749726366/work/PBSuite_15.8.24
+ source /anaconda/bin/activate /anaconda/conda-bld/pbsuite_1492749726366/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh
+ PACKAGE_HOME=/anaconda/conda-bld/pbsuite_1492749726366/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/opt/pbsuite-15.8.24
+ mkdir -p /anaconda/conda-bld/pbsuite_1492749726366/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/opt/pbsuite-15.8.24
+ mkdir -p /anaconda/conda-bld/pbsuite_1492749726366/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin
+ cp -r CHANGELOG.txt LICENSE.txt bin conda_build.sh docs pbsuite setup.sh /anaconda/conda-bld/pbsuite_1492749726366/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/opt/pbsuite-15.8.24
+ for f in 'bin/*.py'
+ echo 'Processing bin/Assembly.py file...'
Processing bin/Assembly.py file...
+ fn=basename
+ bin/Assembly.py
Traceback (most recent call last):
  File "bin/Assembly.py", line 7, in <module>
    from pbsuite.utils.setupLogging import setupLogging
ImportError: No module named pbsuite.utils.setupLogging
Traceback (most recent call last):
  File "/anaconda/bin/conda-build", line 6, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "/anaconda/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 321, in main
    execute(sys.argv[1:])
  File "/anaconda/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 312, in execute
    noverify=args.no_verify)
  File "/anaconda/lib/python2.7/site-packages/conda_build/api.py", line 89, in build
    need_source_download=need_source_download, config=config)
  File "/anaconda/lib/python2.7/site-packages/conda_build/build.py", line 1460, in build_tree
    config=config)
  File "/anaconda/lib/python2.7/site-packages/conda_build/build.py", line 1043, in build
    utils.check_call_env(cmd, env=env, cwd=src_dir)
  File "/anaconda/lib/python2.7/site-packages/conda_build/utils.py", line 590, in check_call_env
    return _func_defaulting_env_to_os_environ(subprocess.check_call, *popenargs, **kwargs)
  File "/anaconda/lib/python2.7/site-packages/conda_build/utils.py", line 586, in _func_defaulting_env_to_os_environ
    return func(_args, **kwargs)
  File "/anaconda/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/bin/bash', '-x', '-e', '/anaconda/conda-bld/pbsuite_1492749726366/work/PBSuite_15.8.24/conda_build.sh']' returned non-zero exit status 1
```
What did I miss?

Thank you in advance.

Michal

**Comment by johanneskoester** [comment]
Hard to say without actually debugging it. You will have to go into the code and investigate `sys.path`...
Or try to convince the authors to create a proper Python package.

**Comment by johanneskoester** [comment]
We have migrated our build system from Travis CI to Circle CI. If you would like to continue working on this PR, please update with latest upstream master and reopen this PR.

**Pull request closed without merging**
