### PR TITLE
Update cnvpytor to 1.2.1

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`cnvpytor`](https://bioconda.github.io/recipes/cnvpytor/README.html): **1.0** &rarr; **1.2.1**

[install with bioconda](http://bioconda.github.io/recipes/cnvpytor/README.html) [Conda](https://anaconda.org/bioconda/cnvpytor/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/cnvpytor`](https://github.com//bioconda/bioconda-recipes/tree/bump/cnvpytor/recipes/cnvpytor) (click to view/edit other files)
Summary | Python extension of CNVnator
Home | [https://github.com/abyzovlab/CNVpytor](https://github.com/abyzovlab/CNVpytor)
Releases |[https://pypi.org/pypi/CNVpytor/json](https://pypi.org/pypi/CNVpytor/json)

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by druvus** [comment]
The software includes `cnvpytor -download` to download missing reference data. At the moment the data is bundled in the conda package but I vote it shouldn't to minimize file size.

**Comment by druvus** [comment]
@BiocondaBot please fetch artifacts

**Comment by ramprasadn** [comment]
Good point @druvus. I will create an issue about this in the cnvpytor repo. Hopefully, the authors will address it in the next release. 😄

**Comment by ramprasadn** [comment]
@druvus I just took a look at this, and I think I understand the issue now. I suppose you are talking about these files [here](https://github.com/abyzovlab/CNVpytor/tree/master/cnvpytor/data) that are part of repo, right?

**Comment by ramprasadn** [comment]
@BiocondaBot please add label

**Comment by dpryan79** [comment]
It looks like the solution is to use pypi as the source and then put `cnvpytor -download` in a post install script. Then it will be present in the container, but not the package.

**Pull request closed without merging**
