### PR TITLE
Add phables 0.1.0b7

### PR DESCRIPTION
**Pull request by Vini2**
Describe your pull request here

This PR adds [phables](https://github.com/Vini2/phables) (Phables: Phage bubbles resolve bacteriophage genomes in viral metagenomic samples) to bioconda. Phables is a tool developed to resolve bacteriophage genomes using phage bubbles in viral metagenomic data.

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by Vini2** [comment]
@BiocondaBot please add label

**Comment by Vini2** [comment]
@BiocondaBot please fetch artifacts

**Comment by Vini2** [comment]
# Testing

## Conda

```
conda install -c ./packages phables-0.1.0b7-pyh7cba7a3_0.tar.bz2

which phables
~/miniconda3/bin/phables

phables -v   
phables, version 0.1.0b7

phables -h   
Usage: phables [OPTIONS] COMMAND [ARGS]...

  Phables: Phage bubbles resolve bacteriophage genomes in viral metagenomic
  samples. Please refer the full documentation available on Read the Docs at
  https://phables.readthedocs.io/

Options:
  -v, --version  Show the version and exit.
  -h, --help     Show this message and exit.

Commands:
  run         Run Phables
  install     Install databases
  preprocess  Preprocess data
  test        Test Phables
  config      Copy the system default config file
  citation    Print the citation(s) for this tool
```

## Test run

Testing on test data.

Command:

```
phables test
```

Output:

```
[2023:01:13 14:37:02] Copying system default config to phables.out/config.yaml
[2023:01:13 14:37:02] Updating config file with new values
[2023:01:13 14:37:02] Writing config file to phables.out/config.yaml
[2023:01:13 14:37:02] ------------------
[2023:01:13 14:37:02] | Runtime config |
[2023:01:13 14:37:02] ------------------

alignscore: 90
compcount: 200
databases: null
dir: /home/mall0133/miniconda3/lib/python3.9/site-packages/phables/test_data
input: null
log: phables/phables.log
maxpaths: 10
mgfrac: 0.2
mincov: 10
minlength: 2000
output: phables.out/
seqidentity: 0.3

[2023:01:13 14:37:02] ---------------------
[2023:01:13 14:37:02] | Snakemake command |
[2023:01:13 14:37:02] ---------------------

snakemake -s /home/mall0133/miniconda3/lib/python3.9/site-packages/phables/workflow/test_phables.smk --configfile phables.out/config.yaml --jobs 1 --use-conda --conda-prefix /home/mall0133/miniconda3/lib/python3.9/site-packages/phables/workflow/conda --rerun-incomplete --printshellcmds --nolock --show-failed-logs
Set parameter Username
Academic license - for non-commercial use only - expires 2023-11-21
No parameters matching '_test' found
Config file /home/mall0133/miniconda3/lib/python3.9/site-packages/phables/workflow/../config/config.yaml is extended by additional config specified via the command line.
Config file /home/mall0133/miniconda3/lib/python3.9/site-packages/phables/workflow/../config/databases.yaml is extended by additional config specified via the command line.
Config file /home/mall0133/miniconda3/lib/python3.9/site-packages/phables/workflow/../config/config.yaml is extended by additional config specified via the command line.
Config file /home/mall0133/miniconda3/lib/python3.9/site-packages/phables/workflow/../config/databases.yaml is extended by additional config specified via the command line.
Building DAG of jobs...
Your conda installation is not configured to use strict channel priorities. This is however crucial for having robust and correct environments (for details, see https://conda-forge.org/docs/user/tipsandtricks.html). Please consider to configure strict priorities by executing 'conda config --set channel_priority strict'.
Using shell: /usr/bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job stats:
job             count    min threads    max threads
------------  -------  -------------  -------------
all                 1              1              1
test_phables        1              1              1
total               2              1              1

Select jobs to execute...

[Fri Jan 13 14:37:06 2023]
rule test_phables:
    input: /home/mall0133/miniconda3/lib/python3.9/site-packages/phables/test_data/assembly_graph.gfa, /home/mall0133/miniconda3/lib/python3.9/site-packages/phables/test_data/assembly_info.txt, /home/mall0133/miniconda3/lib/python3.9/site-packages/phables/test_data/edge_coverages.tsv, /home/mall0133/miniconda3/lib/python3.9/site-packages/phables/test_data, /home/mall0133/miniconda3/lib/python3.9/site-packages/phables/test_data/phrogs_annotations.tsv, /home/mall0133/miniconda3/lib/python3.9/site-packages/phables/test_data/edges.fasta.hmmout
    output: /home/mall0133/miniconda3/lib/python3.9/site-packages/phables/test_data/resolved_paths.fasta, /home/mall0133/miniconda3/lib/python3.9/site-packages/phables/test_data/resolved_phages, /home/mall0133/miniconda3/lib/python3.9/site-packages/phables/test_data/resolved_genome_info.txt, /home/mall0133/miniconda3/lib/python3.9/site-packages/phables/test_data/phage_like_edges.fasta, /home/mall0133/miniconda3/lib/python3.9/site-packages/phables/test_data/resolved_edges.fasta, /home/mall0133/miniconda3/lib/python3.9/site-packages/phables/test_data/resolved_component_info.txt, /home/mall0133/miniconda3/lib/python3.9/site-packages/phables/test_data/results_MFD.txt, /home/mall0133/miniconda3/lib/python3.9/site-packages/phables/test_data/results_MFD_details.txt, /home/mall0133/miniconda3/lib/python3.9/site-packages/phables/test_data/phables_output.log
    log: /home/mall0133/miniconda3/lib/python3.9/site-packages/phables/test_data/phables_output.log
    jobid: 1
    reason: Missing output files: /home/mall0133/miniconda3/lib/python3.9/site-packages/phables/test_data/resolved_edges.fasta, /home/mall0133/miniconda3/lib/python3.9/site-packages/phables/test_data/resolved_component_info.txt, /home/mall0133/miniconda3/lib/python3.9/site-packages/phables/test_data/resolved_paths.fasta, /home/mall0133/miniconda3/lib/python3.9/site-packages/phables/test_data/resolved_genome_info.txt, /home/mall0133/miniconda3/lib/python3.9/site-packages/phables/test_data/phage_like_edges.fasta
    resources: tmpdir=/tmp

python -c "import sys; print('.'.join(map(str, sys.version_info[:2])))"
Activating conda environment: miniconda3/lib/python3.9/site-packages/phables/workflow/conda/9fdf2451975bc9595ccf10886e64403d_
python /home/mall0133/.snakemake/scripts/tmp26d3v0al.phables.py
Activating conda environment: miniconda3/lib/python3.9/site-packages/phables/workflow/conda/9fdf2451975bc9595ccf10886e64403d_
2023-01-13 14:37:08,484 - INFO - Welcome to Phables: Phage bubbles resolve bacteriophage genomes in viral metagenomic samples.
2023-01-13 14:37:08,484 - INFO - Input arguments: 
2023-01-13 14:37:08,485 - INFO - Assembly graph file: /home/mall0133/miniconda3/lib/python3.9/site-packages/phables/test_data/assembly_graph.gfa
2023-01-13 14:37:08,485 - INFO - Assembly paths info file: /home/mall0133/miniconda3/lib/python3.9/site-packages/phables/test_data/assembly_info.txt
2023-01-13 14:37:08,485 - INFO - Unitig coverage file: /home/mall0133/miniconda3/lib/python3.9/site-packages/phables/test_data/edge_coverages.tsv
2023-01-13 14:37:08,485 - INFO - BAM files path: /home/mall0133/miniconda3/lib/python3.9/site-packages/phables/test_data
2023-01-13 14:37:08,485 - INFO - Unitig .hmmout file: /home/mall0133/miniconda3/lib/python3.9/site-packages/phables/test_data/edges.fasta.hmmout
2023-01-13 14:37:08,485 - INFO - Unitig phrog annotations file: /home/mall0133/miniconda3/lib/python3.9/site-packages/phables/test_data/phrogs_annotations.tsv
2023-01-13 14:37:08,485 - INFO - Minimum length of unitigs to consider: 2000
2023-01-13 14:37:08,485 - INFO - Minimum coverage of paths to output: 10
2023-01-13 14:37:08,485 - INFO - Minimum unitig count to consider a component: 200
2023-01-13 14:37:08,485 - INFO - Maximum number of paths to resolve for a component: 10
2023-01-13 14:37:08,485 - INFO - Length threshold to consider single copy marker genes: 0.2
2023-01-13 14:37:08,485 - INFO - Minimum alignment score for phrog annotations: 90
2023-01-13 14:37:08,485 - INFO - Minimum sequence identity for phrog annotations: 0.3
2023-01-13 14:37:08,485 - INFO - Output folder: /home/mall0133/miniconda3/lib/python3.9/site-packages/phables/test_data
2023-01-13 14:37:08,486 - INFO - Total number of vertices in the assembly graph: 6
2023-01-13 14:37:08,486 - INFO - Total number of links in the assembly graph: 3
2023-01-13 14:37:08,578 - INFO - Total number of components found: 3
Resolving components:   0%|                                                                                                    | 0/3 [00:00<?, ?it/s]Set parameter Username
Academic license - for non-commercial use only - expires 2023-11-21
Resolving components: 100%|████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 30.80it/s]
2023-01-13 14:37:08,680 - INFO - Total number of cyclic components found: 2
2023-01-13 14:37:08,680 - INFO - Total number of cyclic components resolved: 2
2023-01-13 14:37:08,680 - INFO - Circular unitigs identified: 1
2023-01-13 14:37:08,680 - INFO - Total number of cyclic components found including circular unitigs: 3
2023-01-13 14:37:08,680 - INFO - Total number of components resolved: 3
2023-01-13 14:37:08,680 - INFO - Total number of genomes resolved: 4
2023-01-13 14:37:08,680 - INFO - Resolved genomes can be found in /home/mall0133/miniconda3/lib/python3.9/site-packages/phables/test_data/resolved_paths.fasta
2023-01-13 14:37:08,693 - INFO - Resolved genome information can be found in /home/mall0133/miniconda3/lib/python3.9/site-packages/phables/test_data/resolved_genome_info.txt
2023-01-13 14:37:08,696 - INFO - Resolved component information can be found in /home/mall0133/miniconda3/lib/python3.9/site-packages/phables/test_data/resolved_component_info.txt
2023-01-13 14:37:08,697 - INFO - Elapsed time: 0.21129584312438965 seconds
2023-01-13 14:37:08,697 - INFO - Thank you for using Phables!
[Fri Jan 13 14:37:08 2023]
Finished job 1.
1 of 2 steps (50%) done
Removing temporary output /home/mall0133/miniconda3/lib/python3.9/site-packages/phables/test_data/resolved_phages.
Removing temporary output /home/mall0133/miniconda3/lib/python3.9/site-packages/phables/test_data/results_MFD.txt.
Removing temporary output /home/mall0133/miniconda3/lib/python3.9/site-packages/phables/test_data/results_MFD_details.txt.
Removing temporary output /home/mall0133/miniconda3/lib/python3.9/site-packages/phables/test_data/phables_output.log.
Select jobs to execute...

[Fri Jan 13 14:37:08 2023]
localrule all:
    input: /home/mall0133/miniconda3/lib/python3.9/site-packages/phables/test_data/resolved_paths.fasta, /home/mall0133/miniconda3/lib/python3.9/site-packages/phables/test_data/resolved_genome_info.txt, /home/mall0133/miniconda3/lib/python3.9/site-packages/phables/test_data/resolved_edges.fasta, /home/mall0133/miniconda3/lib/python3.9/site-packages/phables/test_data/resolved_component_info.txt, /home/mall0133/miniconda3/lib/python3.9/site-packages/phables/test_data/phage_like_edges.fasta
    jobid: 0
    reason: Input files updated by another job: /home/mall0133/miniconda3/lib/python3.9/site-packages/phables/test_data/resolved_edges.fasta, /home/mall0133/miniconda3/lib/python3.9/site-packages/phables/test_data/resolved_component_info.txt, /home/mall0133/miniconda3/lib/python3.9/site-packages/phables/test_data/resolved_paths.fasta, /home/mall0133/miniconda3/lib/python3.9/site-packages/phables/test_data/resolved_genome_info.txt, /home/mall0133/miniconda3/lib/python3.9/site-packages/phables/test_data/phage_like_edges.fasta
    resources: tmpdir=/tmp

[Fri Jan 13 14:37:08 2023]
Finished job 0.
2 of 2 steps (100%) done
Removing temporary output /home/mall0133/miniconda3/lib/python3.9/site-packages/phables/test_data/resolved_edges.fasta.
Removing temporary output /home/mall0133/miniconda3/lib/python3.9/site-packages/phables/test_data/resolved_component_info.txt.
Removing temporary output /home/mall0133/miniconda3/lib/python3.9/site-packages/phables/test_data/resolved_paths.fasta.
Removing temporary output /home/mall0133/miniconda3/lib/python3.9/site-packages/phables/test_data/resolved_genome_info.txt.
Removing temporary output /home/mall0133/miniconda3/lib/python3.9/site-packages/phables/test_data/phage_like_edges.fasta.
Complete log: .snakemake/log/2023-01-13T143703.029657.snakemake.log


Phables test run success!

[2023:01:13 14:37:09] Snakemake finished successfully
```

Everything looks good!

**Comment by Vini2** [comment]
@BiocondaBot please fetch artifacts

**Comment by Vini2** [comment]
# Testing

## Conda

```
conda install -c ./packages phables-0.1.0b7-pyh7cba7a3_0.tar.bz2

which phables
~/miniconda3/envs/phables/bin/phables

phables -v   
phables, version 0.1.0b7

phables -h   
Usage: phables [OPTIONS] COMMAND [ARGS]...

  Phables: Phage bubbles resolve bacteriophage genomes in viral metagenomic
  samples. Please refer the full documentation available on Read the Docs at
  https://phables.readthedocs.io/

Options:
  -v, --version  Show the version and exit.
  -h, --help     Show this message and exit.

Commands:
  run         Run Phables
  install     Install databases
  preprocess  Preprocess data
  test        Test Phables
  config      Copy the system default config file
  citation    Print the citation(s) for this tool
```

## Test run

Testing on test data.

Command:

```
phables test
```

Output:

```
[2023:01:13 16:27:11] Copying system default config to phables.out/config.yaml
[2023:01:13 16:27:11] Updating config file with new values
[2023:01:13 16:27:11] Writing config file to phables.out/config.yaml
[2023:01:13 16:27:11] ------------------
[2023:01:13 16:27:11] | Runtime config |
[2023:01:13 16:27:11] ------------------

alignscore: 90
compcount: 200
databases: null
dir: /home/mall0133/miniconda3/envs/phables/lib/python3.10/site-packages/phables/test_data
input: null
log: phables/phables.log
maxpaths: 10
mgfrac: 0.2
mincov: 10
minlength: 2000
output: phables.out/
seqidentity: 0.3

[2023:01:13 16:27:11] ---------------------
[2023:01:13 16:27:11] | Snakemake command |
[2023:01:13 16:27:12] ---------------------

snakemake -s /home/mall0133/miniconda3/envs/phables/lib/python3.10/site-packages/phables/workflow/test_phables.smk --configfile phables.out/config.yaml --jobs 1 --use-conda --conda-prefix /home/mall0133/miniconda3/envs/phables/lib/python3.10/site-packages/phables/workflow/conda --rerun-incomplete --printshellcmds --nolock --show-failed-logs
Config file /home/mall0133/miniconda3/envs/phables/lib/python3.10/site-packages/phables/workflow/../config/config.yaml is extended by additional config specified via the command line.
Config file /home/mall0133/miniconda3/envs/phables/lib/python3.10/site-packages/phables/workflow/../config/databases.yaml is extended by additional config specified via the command line.
Config file /home/mall0133/miniconda3/envs/phables/lib/python3.10/site-packages/phables/workflow/../config/config.yaml is extended by additional config specified via the command line.
Config file /home/mall0133/miniconda3/envs/phables/lib/python3.10/site-packages/phables/workflow/../config/databases.yaml is extended by additional config specified via the command line.
Building DAG of jobs...
Your conda installation is not configured to use strict channel priorities. This is however crucial for having robust and correct environments (for details, see https://conda-forge.org/docs/user/tipsandtricks.html). Please consider to configure strict priorities by executing 'conda config --set channel_priority strict'.
Creating conda environment miniconda3/envs/phables/lib/python3.10/site-packages/phables/workflow/envs/phables.yaml...
Downloading and installing remote packages.
Environment for /home/mall0133/miniconda3/envs/phables/lib/python3.10/site-packages/phables/workflow/./envs/phables.yaml created (location: miniconda3/envs/phables/lib/python3.10/site-packages/phables/workflow/conda/8b40d5934647137d4ebac1e8cde13762_)
Using shell: /usr/bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job stats:
job             count    min threads    max threads
------------  -------  -------------  -------------
all                 1              1              1
test_phables        1              1              1
total               2              1              1

Select jobs to execute...

[Fri Jan 13 16:30:10 2023]
rule test_phables:
    input: /home/mall0133/miniconda3/envs/phables/lib/python3.10/site-packages/phables/test_data/assembly_graph.gfa, /home/mall0133/miniconda3/envs/phables/lib/python3.10/site-packages/phables/test_data/assembly_info.txt, /home/mall0133/miniconda3/envs/phables/lib/python3.10/site-packages/phables/test_data/edge_coverages.tsv, /home/mall0133/miniconda3/envs/phables/lib/python3.10/site-packages/phables/test_data, /home/mall0133/miniconda3/envs/phables/lib/python3.10/site-packages/phables/test_data/phrogs_annotations.tsv, /home/mall0133/miniconda3/envs/phables/lib/python3.10/site-packages/phables/test_data/edges.fasta.hmmout
    output: /home/mall0133/miniconda3/envs/phables/lib/python3.10/site-packages/phables/test_data/resolved_paths.fasta, /home/mall0133/miniconda3/envs/phables/lib/python3.10/site-packages/phables/test_data/resolved_phages, /home/mall0133/miniconda3/envs/phables/lib/python3.10/site-packages/phables/test_data/resolved_genome_info.txt, /home/mall0133/miniconda3/envs/phables/lib/python3.10/site-packages/phables/test_data/phage_like_edges.fasta, /home/mall0133/miniconda3/envs/phables/lib/python3.10/site-packages/phables/test_data/resolved_edges.fasta, /home/mall0133/miniconda3/envs/phables/lib/python3.10/site-packages/phables/test_data/resolved_component_info.txt, /home/mall0133/miniconda3/envs/phables/lib/python3.10/site-packages/phables/test_data/results_MFD.txt, /home/mall0133/miniconda3/envs/phables/lib/python3.10/site-packages/phables/test_data/results_MFD_details.txt, /home/mall0133/miniconda3/envs/phables/lib/python3.10/site-packages/phables/test_data/phables_output.log
    log: /home/mall0133/miniconda3/envs/phables/lib/python3.10/site-packages/phables/test_data/phables_output.log
    jobid: 1
    reason: Missing output files: /home/mall0133/miniconda3/envs/phables/lib/python3.10/site-packages/phables/test_data/phage_like_edges.fasta, /home/mall0133/miniconda3/envs/phables/lib/python3.10/site-packages/phables/test_data/resolved_genome_info.txt, /home/mall0133/miniconda3/envs/phables/lib/python3.10/site-packages/phables/test_data/resolved_paths.fasta, /home/mall0133/miniconda3/envs/phables/lib/python3.10/site-packages/phables/test_data/resolved_edges.fasta, /home/mall0133/miniconda3/envs/phables/lib/python3.10/site-packages/phables/test_data/resolved_component_info.txt
    resources: tmpdir=/tmp

python -c "import sys; print('.'.join(map(str, sys.version_info[:2])))"
Activating conda environment: miniconda3/envs/phables/lib/python3.10/site-packages/phables/workflow/conda/8b40d5934647137d4ebac1e8cde13762_
python /home/mall0133/.snakemake/scripts/tmplhng52x3.phables.py
Activating conda environment: miniconda3/envs/phables/lib/python3.10/site-packages/phables/workflow/conda/8b40d5934647137d4ebac1e8cde13762_
2023-01-13 16:30:13,613 - INFO - Welcome to Phables: Phage bubbles resolve bacteriophage genomes in viral metagenomic samples.
2023-01-13 16:30:13,614 - INFO - Input arguments: 
2023-01-13 16:30:13,614 - INFO - Assembly graph file: /home/mall0133/miniconda3/envs/phables/lib/python3.10/site-packages/phables/test_data/assembly_graph.gfa
2023-01-13 16:30:13,614 - INFO - Assembly paths info file: /home/mall0133/miniconda3/envs/phables/lib/python3.10/site-packages/phables/test_data/assembly_info.txt
2023-01-13 16:30:13,614 - INFO - Unitig coverage file: /home/mall0133/miniconda3/envs/phables/lib/python3.10/site-packages/phables/test_data/edge_coverages.tsv
2023-01-13 16:30:13,614 - INFO - BAM files path: /home/mall0133/miniconda3/envs/phables/lib/python3.10/site-packages/phables/test_data
2023-01-13 16:30:13,614 - INFO - Unitig .hmmout file: /home/mall0133/miniconda3/envs/phables/lib/python3.10/site-packages/phables/test_data/edges.fasta.hmmout
2023-01-13 16:30:13,614 - INFO - Unitig phrog annotations file: /home/mall0133/miniconda3/envs/phables/lib/python3.10/site-packages/phables/test_data/phrogs_annotations.tsv
2023-01-13 16:30:13,614 - INFO - Minimum length of unitigs to consider: 2000
2023-01-13 16:30:13,614 - INFO - Minimum coverage of paths to output: 10
2023-01-13 16:30:13,614 - INFO - Minimum unitig count to consider a component: 200
2023-01-13 16:30:13,614 - INFO - Maximum number of paths to resolve for a component: 10
2023-01-13 16:30:13,614 - INFO - Length threshold to consider single copy marker genes: 0.2
2023-01-13 16:30:13,614 - INFO - Minimum alignment score for phrog annotations: 90
2023-01-13 16:30:13,614 - INFO - Minimum sequence identity for phrog annotations: 0.3
2023-01-13 16:30:13,614 - INFO - Output folder: /home/mall0133/miniconda3/envs/phables/lib/python3.10/site-packages/phables/test_data
2023-01-13 16:30:13,617 - INFO - Total number of vertices in the assembly graph: 6
2023-01-13 16:30:13,618 - INFO - Total number of links in the assembly graph: 3
2023-01-13 16:30:13,726 - INFO - Total number of components found: 3
Resolving components:   0%|                                                                                                          | 0/3 [00:00<?, ?it/s]Set parameter Username
Academic license - for non-commercial use only - expires 2023-11-21
Resolving components: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 16.91it/s]
2023-01-13 16:30:13,910 - INFO - Total number of cyclic components found: 2
2023-01-13 16:30:13,910 - INFO - Total number of cyclic components resolved: 2
2023-01-13 16:30:13,910 - INFO - Circular unitigs identified: 1
2023-01-13 16:30:13,910 - INFO - Total number of cyclic components found including circular unitigs: 3
2023-01-13 16:30:13,911 - INFO - Total number of components resolved: 3
2023-01-13 16:30:13,911 - INFO - Total number of genomes resolved: 4
2023-01-13 16:30:13,911 - INFO - Resolved genomes can be found in /home/mall0133/miniconda3/envs/phables/lib/python3.10/site-packages/phables/test_data/resolved_paths.fasta
2023-01-13 16:30:13,924 - INFO - Resolved genome information can be found in /home/mall0133/miniconda3/envs/phables/lib/python3.10/site-packages/phables/test_data/resolved_genome_info.txt
2023-01-13 16:30:13,928 - INFO - Resolved component information can be found in /home/mall0133/miniconda3/envs/phables/lib/python3.10/site-packages/phables/test_data/resolved_component_info.txt
2023-01-13 16:30:13,929 - INFO - Elapsed time: 0.314486026763916 seconds
2023-01-13 16:30:13,929 - INFO - Thank you for using Phables!
[Fri Jan 13 16:30:14 2023]
Finished job 1.
1 of 2 steps (50%) done
Removing temporary output /home/mall0133/miniconda3/envs/phables/lib/python3.10/site-packages/phables/test_data/resolved_phages.
Removing temporary output /home/mall0133/miniconda3/envs/phables/lib/python3.10/site-packages/phables/test_data/results_MFD.txt.
Removing temporary output /home/mall0133/miniconda3/envs/phables/lib/python3.10/site-packages/phables/test_data/results_MFD_details.txt.
Removing temporary output /home/mall0133/miniconda3/envs/phables/lib/python3.10/site-packages/phables/test_data/phables_output.log.
Select jobs to execute...

[Fri Jan 13 16:30:14 2023]
localrule all:
    input: /home/mall0133/miniconda3/envs/phables/lib/python3.10/site-packages/phables/test_data/resolved_paths.fasta, /home/mall0133/miniconda3/envs/phables/lib/python3.10/site-packages/phables/test_data/resolved_genome_info.txt, /home/mall0133/miniconda3/envs/phables/lib/python3.10/site-packages/phables/test_data/resolved_edges.fasta, /home/mall0133/miniconda3/envs/phables/lib/python3.10/site-packages/phables/test_data/resolved_component_info.txt, /home/mall0133/miniconda3/envs/phables/lib/python3.10/site-packages/phables/test_data/phage_like_edges.fasta
    jobid: 0
    reason: Input files updated by another job: /home/mall0133/miniconda3/envs/phables/lib/python3.10/site-packages/phables/test_data/phage_like_edges.fasta, /home/mall0133/miniconda3/envs/phables/lib/python3.10/site-packages/phables/test_data/resolved_genome_info.txt, /home/mall0133/miniconda3/envs/phables/lib/python3.10/site-packages/phables/test_data/resolved_paths.fasta, /home/mall0133/miniconda3/envs/phables/lib/python3.10/site-packages/phables/test_data/resolved_edges.fasta, /home/mall0133/miniconda3/envs/phables/lib/python3.10/site-packages/phables/test_data/resolved_component_info.txt
    resources: tmpdir=/tmp

[Fri Jan 13 16:30:14 2023]
Finished job 0.
2 of 2 steps (100%) done
Removing temporary output /home/mall0133/miniconda3/envs/phables/lib/python3.10/site-packages/phables/test_data/phage_like_edges.fasta.
Removing temporary output /home/mall0133/miniconda3/envs/phables/lib/python3.10/site-packages/phables/test_data/resolved_genome_info.txt.
Removing temporary output /home/mall0133/miniconda3/envs/phables/lib/python3.10/site-packages/phables/test_data/resolved_paths.fasta.
Removing temporary output /home/mall0133/miniconda3/envs/phables/lib/python3.10/site-packages/phables/test_data/resolved_edges.fasta.
Removing temporary output /home/mall0133/miniconda3/envs/phables/lib/python3.10/site-packages/phables/test_data/resolved_component_info.txt.
Complete log: .snakemake/log/2023-01-13T162713.022102.snakemake.log


Phables test run success!

[2023:01:13 16:30:14] Snakemake finished successfully
```

Everything looks good!

**Review by rpetit3 — APPROVED** [review]

**Comment by rpetit3** [comment]
@Vini2 thank you very much for taking the time to test the artifacts! Makes reviews super easy

**Comment by rpetit3** [comment]
@BiocondaBot please merge

**Comment by Vini2** [comment]
@rpetit3 thank you very much!

**Pull request merged**
