### PR TITLE
Fail early

### PR DESCRIPTION
**Pull request by bgruening**
* [x] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [x] This PR does something else (explain below).

This script will kill PR that are superseded by others and reduces hopefully the overall travis load.

We found this script on conda-forge and credits goes to @jakirkham and @tkelman! Thanks!

### CODE REVIEW

**Comment by bgruening** [comment]
ping @bioconda/core

**Comment by daler** [comment]
This a great idea and will be nice to have.  Will we use their master branch once https://github.com/conda-forge/conda-forge-build-setup-feedstock/pull/52 is merged?

**Comment by bgruening** [comment]
I guess this is not urgent and we can wait until it is merged.

**Comment by jakirkham** [comment]
Glad you like it. :smile:

**Comment by johanneskoester** [comment]
Very nice! Thanks!

**Comment by bgruening** [comment]
@bioconda/core final review please :)
Please also note that travis is developing a similar build in feature that is currently in beta testing. We could use this as well if we apply for testing.

**Comment by johanneskoester** [comment]
Let us wait until that feature becomes stable and use this until then.

**Comment by daler** [comment]
@bgruening @johanneskoester the settings page on travis has an "auto cancellation settings" section that I haven't noticed before. There's no beta label, but I don't see an announcement or docs on it. Should we try it?

**Comment by johanneskoester** [comment]
It is a beta feature that I have told them to activate for us. I already activated it on bioconda-recipes. With the new filtering, it is important that it is only activated for pull requests. Seems to work fine.

**Comment by johanneskoester** [comment]
We now use the autocancellation feature.

**Pull request closed without merging**
