### PR TITLE
Add IGV recipe

### PR DESCRIPTION
**Pull request by mvdbeek**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by mvdbeek** [comment]
I guess we'd need the full X11 stack to make the test pass ... or I can disable the test.

**Comment by bgruening** [comment]
Could you try to add the X11 stack? Otherwise, relaying the test would be fine with me.

**Comment by mvdbeek** [comment]
I don't think we have a complete X11 stack, see https://github.com/conda-forge/staged-recipes/issues/2587.

Another issue with including X11 would be that in most instances people installing IGV already have an Xserver running, so that would lead to conflicts, I believe. Do you know if there is mechanism in conda that would selectively decide whether or not dependencies such as X11 are needed ?

I guess I can disable the test for now ...

**Comment by bgruening** [comment]
Is this package meant to run IGV on a Desktop not in a headless mode?

**Comment by mvdbeek** [comment]
> Is this package meant to run IGV on a Desktop not in a headless mode?

I suppose that would be the most common use ... while ultimately I am going to use it in headless mode. so ...

**Comment by bgruening** [comment]
Thanks!

**Pull request merged**
