### PR TITLE
Update eden to v.3.0

### PR DESCRIPTION
**Pull request by corburn**
* [ ] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [ ] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by corburn** [comment]
@martin-mann thanks for the updates. You are welcome to take over updating this recipe.

**Comment by martin-mann** [comment]
not sure I want to...

**Comment by martin-mann** [comment]
@dmaticzka @fabriziocosta : could you please check and extended the test accordingly?! thanks!

**Comment by martin-mann** [comment]
it might also be necessary to package `eden_rna` etc... since this functionality is lost with v3.0 as far as I can see..

**Comment by martin-mann** [comment]
before releasing this version bump, I strongly recommend to set an upper bound to all tools that have eden as a dependency, otherwise, their rebuilds will dramatically crash...

**Comment by martin-mann** [comment]
@corburn why interested in a version update?

**Comment by martin-mann** [comment]
given the comments from above and a discussion with @bgruening I would say we skip this update...

best,
Martin

**Pull request closed without merging**
