### PR TITLE
arborator v1.0.0

### PR DESCRIPTION
**Pull request by kbessonov1984**
This is a new Arborator tool release on conda from https://github.com/phac-nml/arborator

### CODE REVIEW

**Comment by kbessonov1984** [comment]
All checks passed, please review and merge this PR so that we could release the tool and follow up with another tool release

**Comment by rpetit3** [comment]
@biocondabot please fetch artifacts

**Comment by rpetit3** [comment]
@kbessonov1984 you will need to move your `arborator` folder into the `recipes` folder

**Comment by kbessonov1984** [comment]
Moved recipe to the right folder. Previous location of the recipe was an error indeed. Now it is at `bioconda-recipes/recipes/arborator`

**Comment by rpetit3** [comment]
@BiocondaBot please fetch artifacts

**Comment by kbessonov1984** [comment]
Thank you, for some reason the merge did not occur and I do not see this package at anaconda.org registry yet. Maybe need to resync with master?

**Review by rpetit3 — APPROVED** [review]

**Pull request merged**
