### PR TITLE
PICRUSt2 install fix

### PR DESCRIPTION
**Pull request by gavinmdouglas**
* [ x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x ] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by gavinmdouglas** [comment]
@apcamargo quick note that I've added a PR that should address the issue we were discussing in PR https://github.com/bioconda/bioconda-recipes/pull/13098

**Comment by apcamargo** [comment]
Hey @gavinmdouglas , I see that you're working in the installation fix. Thanks!

I think we should also submit a recipe of an older version of `epa-ng`, to avoid the segmentation fault issue.

**Comment by gavinmdouglas** [comment]
Hi @apcamargo, yes I think I'm close to getting it working now.

That would be difficult to add an older version of EPA-NG to bioconda since several code fixes (added in later versions) were required for it to build correctly on macos (see https://github.com/Pbdas/epa-ng/issues/22).  I think it will be better to simply bump the version of EPA-NG (or PICRUSt2) once the cause of the segmentation fault is identified and fixed.

**Comment by gavinmdouglas** [comment]
Thanks for the help @dpryan79 !

**Pull request merged**
