### PR TITLE
Hops: fix package not installing any more

### PR DESCRIPTION
**Pull request by rhuebler**
**Replace this sentence with a detailed description of your pull request**

----

> Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it.

* [ x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [ ] This PR adds a new recipe.
* [ x] AFAIK, this recipe **is directly relevant to the biological sciences**
      (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

> Everyone has access to the following BiocondaBot commands, which can be given in a comment:
>
>  * `@BiocondaBot please update` will cause the BiocondaBot to merge the master branch into a PR
>  * `@BiocondaBot please add label` will add the `please review & merge` label.
>  * `@BiocondaBot please fetch artifacts` will post links to packages and docker containers built by the CI system. You can use this to test packages locally before merging.
>
> For members of the Bioconda project, the following command is also available:
>
>  * `@BiocondaBot please merge` will cause packages/containers to be uploaded and a PR merged. Someone must approve a PR first! This has the benefit of not wasting CI build time required by manually merging PRs.
>
> If you have questions, please post them in gitter or ping `@bioconda/core` in a comment (if you are not able to directly ping `@bioconda/core` then the bot will repost your comment and enable pinging).

### CODE REVIEW

**Comment by rhuebler** [comment]
@bioconda/core please review that is bugfix to the meta.yaml, which suddenly started to fail. One or more of the dependencies have updated and a stable environment could not be created any longer.

**Comment by bgruening** [comment]
@BiocondaBot please fetch artifacts

**Comment by bgruening** [comment]
What was failing @rhuebler? You can test the new package from the links provided by the bot.

**Comment by rhuebler** [comment]
Well on our ubuntu server it seems to work but the previous meta.yaml produced this error:

Package openjdk conflicts for:
hops -> openjdk=8.0.144
Package zlib conflicts for:
python=3.7 -> zlib[version='>=1.2.11,<1.3.0a0']
Package xz conflicts for:
python=3.7 -> xz[version='>=5.2.4,<6.0a0']
Package r-doparallel conflicts for:
hops -> r-doparallel
Package r-getopt conflicts for:
hops -> r-getopt
Package r-base conflicts for:
hops -> r-base[version='>=3.5']
Package r-gridbase conflicts for:
hops -> r-gridbase
Package tk conflicts for:
python=3.7 -> tk[version='>=8.6.7,<8.7.0a0|>=8.6.8,<8.7.0a0']
Package libcxx conflicts for:
python=3.7 -> libcxx[version='>=4.0.1']
Package openssl conflicts for:
python=3.7 -> openssl[version='>=1.0.2o,<1.0.3a|>=1.1.1a,<1.1.2a|>=1.1.1b,<1.1.2a|>=1.1.1c,<1.1.2a|>=1.1.1d,<1.1.2a']
Package r-gridextra conflicts for:
hops -> r-gridextra
Package sqlite conflicts for:
python=3.7 -> sqlite[version='>=3.24.0,<4.0a0|>=3.25.2,<4.0a0|>=3.25.3,<4.0a0|>=3.26.0,<4.0a0|>=3.27.2,<4.0a0|>=3.29.0,<4.0a0|>=3.30.1,<4.0a0']
Package readline conflicts for:
python=3.7 -> readline[version='>=7.0,<8.0a0']
Package ncurses conflicts for:
python=3.7 -> ncurses[version='>=6.1,<7.0a0']
Package malt conflicts for:
hops -> malt
Package pip conflicts for:
python=3.7 -> pip
Package libffi conflicts for:
python=3.7 -> libffi[version='>=3.2.1,<4.0a0']

On my mac I still got
he following packages are causing the inconsistency:

  - defaults/osx-64::anaconda==2019.07=py37_0
  - defaults/osx-64::numba==0.44.1=py37h6440ff4_0

But that might be on me

**Comment by rhuebler** [comment]
Anyway I removed the version restrictions of the R version and openjdk that were in place in the previous meta.yaml. That seems to have fixed it for now

**Comment by epruesse** [comment]
Do you know why the restrictions were in there?  Can you try to figure out what the least restrictive still functioning constraints are?

Conda will silently pick an older build number if that makes it easier/possible to install a package. So if we publish this, we cannot take it back later should it turn out that some combinations are not working.

**Comment by epruesse** [comment]
BTW: I've had the same issue with ARB. The builds 5, 6, 7 and 8 are all not installing any more due to dependencies missing. I assume conda-forge deleted things.

One thing you might want to try to get things going again is just bumping the build number without altering anything else in the recipe. That might re-pin some things that are now missing.

**Comment by rhuebler** [comment]
Hmm, well the restriction for the openjdk version was in place as malt one of the dependencies needs a specific version. But technically that restriction is also in place in the malt recipe.So I think that can be dropped. I think I restricted the R version as the hops contains a post processing script that was written in R 3.5.. But I assume as long as the dependencies for the package are in place it should also work with more current versions. When you mean bumb the version you mean move from 0.33 to 0.34?

**Comment by epruesse** [comment]
If it doesn't install, sometimes just increasing `build:` will help (i.e. "bump build number"). The new package will have never automatic pins, which might allow it to install again, depending on what was the cause for failing to resolve the dependencies.

You can't just increase the version number - that's to identify the version of the software and decided on by the upstream author. As package maintainer, you have the build number (and sometimes the epoch, depending on which package manager is used) to indicate that you changed packaging related things.

The caveat with `conda` is that unlike other package managers it will consider all available package versions, including older build numbers. It will also try to minimize changes to environments. The result is that we cannot effectively make new builds more restrictive in their dependencies. Conda will just use the old package build. It can be exasperating, because the alternative of deleting old package builds also has massive caveats (like dependent packages not installing anymore).

Ideally, you'd figure out what the real requirements are. It's a bit of a bummer with future versions - we don't know yet whether a future R will break any of this packages code. But that can't be helped, so either just put `R >x.y.z` or expect that you will have to make new builds allowing for the newest R every time a new R comes out.

**Comment by epruesse** [comment]
Does hops need JDK itself, or does just malt need JDK? If the latter, just remove JDK dependency. The deps here should just indicate what hops needs.

**Comment by epruesse** [comment]
Looking at the conflict above - try changing nothing but the build number. The versions for zlib, python, xz, etc all are automatic pins.

**Comment by rhuebler** [comment]
Well you were correct, the increase in the build number was sufficient for the package to work again. So I put the restriction back in, as hops in deed does need the same java version as malt. And the restriction on the R- base is only a minimum version requirement

**Pull request closed without merging**
