### PR TITLE
Update pgx-variant-tools to 0.0.5

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`pgx-variant-tools`](https://bioconda.github.io/recipes/pgx-variant-tools/README.html): **0.0.4** &rarr; **0.0.5**

[install with bioconda](http://bioconda.github.io/recipes/pgx-variant-tools/README.html) [Conda](https://anaconda.org/bioconda/pgx-variant-tools/files)

Info | Link
-----|-----
Recipe | [`recipes/pgx-variant-tools`](https://github.com//bioconda/bioconda-recipes/tree/bump/pgx_variant_tools/recipes/pgx-variant-tools) (click to view/edit other files)
Releases |[https://pypi.org/pypi/pgx-variant-tools/json](https://pypi.org/pypi/pgx-variant-tools/json)

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by marksantcroos** [comment]
@BiocondaBot please add label

**Comment by marksantcroos** [comment]
@BiocondaBot please fetch artifacts

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Comment by marksantcroos** [comment]
Thanks @dpryan79!

Btw, would it make any difference if I would register myself as the maintainer of the recipe?

**Comment by dpryan79** [comment]
Yeah, the next time there's an update please do that. At some point we should have the bot ping the maintainers.

**Pull request merged**
