### PR TITLE
add cellprofiler analyst recipe

### PR DESCRIPTION
**Pull request by ThomasWollmann**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by bgruening** [comment]
@ThomasWollmann I get now this here:
```
conda.exceptions.ResolvePackageNotFound: 
  - python-bioformats
  - verlib
```

**Comment by ThomasWollmann** [comment]
> @ThomasWollmann I get now this here:
> 
> ```
> conda.exceptions.ResolvePackageNotFound: 
>   - python-bioformats
>   - verlib
> ```

Seems like I have to package those first :/

**Comment by ThomasWollmann** [comment]
ping @jkh1

**Comment by ThomasWollmann** [comment]
Old PR

**Pull request closed without merging**
