### PR TITLE
Update CNVkit to 0.8.2

### PR DESCRIPTION
**Pull request by etal**
* [x] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

The PyVCF dependency is dropped in favor of a newer pysam.

### CODE REVIEW

**Comment by bgruening** [comment]
@etal please see https://github.com/bioconda/bioconda-recipes/pull/3208 :)

**Comment by kyleabeauchamp** [comment]
No worries, I closed mine and cancelled the build in favor of this one.

**Comment by kyleabeauchamp** [comment]
Better to have this come from the source...

**Comment by bgruening** [comment]
Thank you both!!!

**Pull request merged**
