### PR TITLE
Update cgat-scripts

### PR DESCRIPTION
**Pull request by sebastian-luna-valero**
* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [X] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by sebastian-luna-valero** [comment]
Hi @bgruening @daler 

I was wondering whether I could ask for your help into this issue. I am getting `OSError: [Errno 39] Directory not empty: './build'` here:
https://travis-ci.org/bioconda/bioconda-recipes/jobs/259814536#L1132

As discussed in https://github.com/bioconda/bioconda-recipes/pull/5345, I made sure `gcc` is not a run dependency. I have also merged with the latest master.

Could you please let me know what could be wrong?

Many thanks,
Sebastian

**Comment by bgruening** [comment]
@sebastian-luna-valero the error is above: https://travis-ci.org/bioconda/bioconda-recipes/jobs/259814536#L1119

You are running out of disc-space :(

**Comment by sebastian-luna-valero** [comment]
Thanks @bgruening 

Has something recently changed that could explain it? This is just an update of https://github.com/bioconda/bioconda-recipes/pull/5345 which was recently built and uploaded to bioconda, so the disk usage should not be that different.

Is there any workaround?

**Comment by sebastian-luna-valero** [comment]
Moreover, the py35 tests pass.

**Comment by bgruening** [comment]
You have a lot of dependencies I think this is the problem ... can you give me a few days to try to reduce the travis build system a little bit?

**Comment by sebastian-luna-valero** [comment]
Indeed, the amount of dependencies is huge... sorry about that.

Many thanks for looking into the issue. I will also look at decreasing the number of dependencies.

**Comment by sebastian-luna-valero** [comment]
On second thoughts, @bgruening if you think accommodating a huge number of dependencies is a big problem to overcome with the existing build system, I am happy to use conda environment files and provide a wrapper installation script instead of a conda package.

I guess this issue is part of a broader discussion about what is a good bioconda package in terms of maximum number of dependencies allowed.

**Comment by sebastian-luna-valero** [comment]
Hi @bgruening 

FYI: it looks like I am also running out of disk space in https://github.com/bioconda/bioconda-recipes/pull/5428

This time is not a recipe but a set of R and Bioconductor recipes.

Please let me know your thoughts.

**Comment by bgruening** [comment]
@sebastian-luna-valero the last one is fine, you just need to split the giant PR into multiple small ones.
I look at it and we can mabye save 500MB on travis, but it will not solve the problem in gerneral. I think the ideal solution for you problem is indeed using a environemt.yaml file and deploy this to anaconda.

Do you know that you can deploy environments into anaconda.org https://anaconda.org/bgruening/environments for example.

**Comment by bgruening** [comment]
@sebastian-luna-valero please have a look at: https://github.com/bioconda/bioconda-recipes/pull/5534

**Pull request merged**
