### PR TITLE
Update umis to 1.0.7

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`umis`](https://bioconda.github.io/recipes/umis/README.html): **1.0.6** &rarr; **1.0.7**

[install with bioconda](http://bioconda.github.io/recipes/umis/README.html) [Conda](https://anaconda.org/bioconda/umis/files)

Info | Link
-----|-----
Recipe | [`recipes/umis`](https://github.com//bioconda/bioconda-recipes/tree/bump/umis/recipes/umis) (click to view/edit other files)
Releases |[https://github.com/vals/umis/tags](https://github.com/vals/umis/tags)
Author | `@vals`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by roryk** [comment]
AFAIK this should work, it builds fine locally with circleci build. Retriggering.

**Comment by dpryan79** [comment]
Looks like this got a bum build of something or other last time, rerunning worked.

**Comment by roryk** [comment]
Thanks, for some reason the OSX build suddenly needs setuptools as part of the runtime environment, or it fails. I added it, but it feels dirty to do that. Let me know if that is a problem.

**Comment by dpryan79** [comment]
I have a feeling that conda-forge just released a broken python 3.6 build.

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Pull request merged**
