### PR TITLE
Update ViennaRNA: build Python 2 and 3 bindings

### PR DESCRIPTION
**Pull request by s-will**
* [x] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by s-will** [comment]
Building interfaces for Python 2 and 3 seems to require a hack, since conda does not allow to cleanly define two different versions of the same package as build dependencies. (Other solutions like defining packages python27 and python35 are ruled out here, since they look too invasive)

Vienna requires Python 2 and 3 at run time to generate Swig bindings for both. Since conda does not allow installation of both python versions in the same environment, we perform this workaround: in the build script(!), install Python 2 in a different environment and set the path accordingly.

**Comment by s-will** [comment]
I had to navigate around a few more unexpected obstacles, but finally this worked (i.e. not only in principle.)
@bgruening, are there immediate improvements that I missed? Who could help/would be interested to find a cleaner solution in the long run?
@dmaticzka, could this fully replace your version or should we merge anything?
@raumzeit, I could not include the gsl dependency (only tested locally yet); let's look at this offline.
@RobertKleinkauf, I hope this will solve your problem with packaging antarna.

**Comment by dmaticzka** [comment]
Thanx alot for that solution! This fully replaces my variant, I just closed the PR.

**Comment by s-will** [comment]
Hi @bgruening, I wonder why there is no new package (2.3.1, build 1) on the channel by now, although the PR was merged >4h ago. Is the system confused? -- maybe by the parallel pull requests for build 1? At least I am confused;)

**Comment by bgruening** [comment]
The tarball was not reachable for some time. It is back now, but we have a huge backlog in Travis now :(

**Comment by bgruening** [comment]
@s-will https://quay.io/repository/biocontainers/viennarna?tab=tags
Everything should be online.

**Pull request merged**
