### PR TITLE
pb-assembly allow py37 also

### PR DESCRIPTION
**Pull request by pb-cdunn**
:information_source:
If this is your first pull request to Bioconda please ping `@bioconda/core` so it can be reviewed and to request being added as a member of the Bioconda team. Members of the Bioconda team are able to merge their own pull requests once tests and linting have passed.

----------------

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by pb-cdunn** [comment]
Using py37 required #15097 and #15070, which needed newer gcc.

**Comment by pb-cdunn** [comment]
@bioconda/core , I fixed both **python-edlib** and **python-msgpack**. (I had to use the cxx compiler because the Python3.7 Extension module wants `execvp()`, which is missing in the older c compiler.) I managed to build **pb-assembly** for py36. But now I have no idea why I cannot add py37 support to **pb-assembly**.

**Comment by npavlovikj** [comment]
Can you please try adding space between the pinning, e.g.:
    - python >=3.6
    - pb-falcon >=0.3.0

**Comment by pb-cdunn** [comment]
I've learned elsewhere that packages with hyphens cannot have a space between the pinning. I have no idea why. Must be a bug in the conda meta-yaml parser.

**Comment by pb-cdunn** [comment]
Locally, I create a py37 environment, add some packages, and then:
```
% conda install pb-falcon=0.3.0

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    python-msgpack-0.6.1       |   py36h6bb024c_0          90 KB  bioconda
    ------------------------------------------------------------

The following NEW packages will be INSTALLED:

  curl               conda-forge/linux-64::curl-7.64.1-hf8cf82a_0
  htslib             bioconda/linux-64::htslib-1.9-h4da6232_3
  krb5               conda-forge/linux-64::krb5-1.16.3-h05b26f9_1001
  libcurl            conda-forge/linux-64::libcurl-7.64.1-hda55be3_0
  libdeflate         bioconda/linux-64::libdeflate-1.2-h14c3975_0
  libedit            conda-forge/linux-64::libedit-3.1.20170329-hf8c457e_1001
  libssh2            conda-forge/linux-64::libssh2-1.8.2-h22169c7_2
  pb-falcon          bioconda/linux-64::pb-falcon-0.3.0-py36hc0aa232_0

The following packages will be DOWNGRADED:

  certifi                                   2019.3.9-py37_0 --> 2019.3.9-py36_0
  future                                   0.17.1-py37_1000 --> 0.17.1-py36_1000
  numpy                               1.16.3-py37he5ce36f_0 --> 1.16.3-py36he5ce36f_0
  pip                                           19.1-py37_0 --> 19.1-py36_0
  python                                   3.7.3-h5b0a415_0 --> 3.6.7-h381d211_1004
  python-edlib                         1.2.4-py37h6bb024c_0 --> 1.2.4-py36h6bb024c_0
  python-msgpack                       0.6.1-py37h6bb024c_0 --> 0.6.1-py36h6bb024c_0
  setuptools                                  41.0.1-py37_0 --> 41.0.1-py36_0
  wheel                                       0.33.1-py37_0 --> 0.33.1-py36_0
```
... Oh, I see. A core-team member added this to the **pb-falcon** PR:
```
skip: True # [py27 or osx or py == 37]
```
I hadn't noticed that before. I think now that I have fixed edlib and msgpack, I should be able to add py37 support to **pb-falcon**. Trying that next ...

**Comment by npavlovikj** [comment]
I tried building "pb-assembly" locally and got:
**failed to get install actions, retrying.  exception was: Unsatisfiable dependencies for platform linux-64: {"python[version='>=3.7,<3.8.0a0']", "python[version='>=3.6,<3.7.0a0']"}**
which verifies your finding, so I guess just make sure all the dependencies work with python 3.7.

**Comment by pb-cdunn** [comment]
Hmmm. Locally, in a py37 env:
```
% conda install pb-falcon==0.3.0

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    pb-falcon-0.3.0            |   py37hc0aa232_1         537 KB  bioconda
    ------------------------------------------------------------
                                           Total:         537 KB

The following NEW packages will be INSTALLED:

  curl               conda-forge/linux-64::curl-7.64.1-hf8cf82a_0
  htslib             bioconda/linux-64::htslib-1.9-h4da6232_3
  krb5               conda-forge/linux-64::krb5-1.16.3-h05b26f9_1001
  libcurl            conda-forge/linux-64::libcurl-7.64.1-hda55be3_0
  libdeflate         bioconda/linux-64::libdeflate-1.2-h14c3975_0
  libedit            conda-forge/linux-64::libedit-3.1.20170329-hf8c457e_1001
  libssh2            conda-forge/linux-64::libssh2-1.8.2-h22169c7_2
  pb-falcon          bioconda/linux-64::pb-falcon-0.3.0-py37hc0aa232_1
```
So I don't understand the problem with **pb-assembly** here.

**Comment by pb-cdunn** [comment]
```
07:25:21 BIOCONDA INFO BUILD START recipes/pb-assembly
07:25:24 BIOCONDA ERROR COMMAND FAILED: docker run -t --net host --rm -v /tmp/tmplbgpuuxd/build_script.bash:/opt/build_script.bash -v /home/circleci/project/miniconda/conda-bld:/opt/host-conda-bld -v /home/circleci/project/recipes/pb-assembly:/opt/recipe -e LANG=en_US.UTF-8 -e HOST_USER_ID=1001 tmp-bioconda-builder /bin/bash /opt/build_script.bash
07:25:24 BIOCONDA ERROR STDOUT+STDERR:
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11

WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11

Adding in variants from internal_defaults

INFO:conda_build.variants:Adding in variants from internal_defaults

Adding in variants from /opt/host-conda-bld/conda_build_config_0_-e_conda_build_config.yaml

INFO:conda_build.variants:Adding in variants from /opt/host-conda-bld/conda_build_config_0_-e_conda_build_config.yaml

Adding in variants from /opt/host-conda-bld/conda_build_config_1_-m_bioconda_utils-conda_build_config.yaml

INFO:conda_build.variants:Adding in variants from /opt/host-conda-bld/conda_build_config_1_-m_bioconda_utils-conda_build_config.yaml

Skipped: pb-assembly from /opt/recipe defines build/skip for this configuration ({}).

Renaming work directory,  /opt/conda/conda-bld/pb-assembly_1556954722982/work  to  /opt/conda/conda-bld/pb-assembly_1556954722982/work_moved_pb-assembly-0.0.6-py27_3_linux-64_main_build_loop

# Automatic uploading is disabled

# If you want to upload package(s) to anaconda.org later, type:





# To have conda build upload to anaconda.org automatically, use

# $ conda config --set anaconda_upload yes



anaconda_upload is not set.  Not uploading wheels: []

####################################################################################

Resource usage summary:



Total time: 0:00:00.1

CPU usage: sys=0:00:00.0, user=0:00:00.0

Maximum memory usage observed: 0B

Total disk usage observed (not including envs): 0B

cp: missing destination file operand after `/opt/host-conda-bld/linux-64'

Try `cp --help' for more information.



07:25:24 BIOCONDA ERROR BUILD FAILED recipes/pb-assembly
07:25:24 BIOCONDA ERROR BUILD SUMMARY: of 1 recipes, 1 failed and 0 were skipped. Details of recipes and environments follow.
07:25:24 BIOCONDA ERROR BUILD SUMMARY: FAILED recipe recipes/pb-assembly
Exited with code 1
```
That doesn't explain the failure. Any ideas?

Oddly, "Copying packages" and "Uploading artifacts" happened anyway. I'll try a new version, since there is a new Python supported...

**Comment by pb-cdunn** [comment]
I notice that **pb-assembly--0.6.0** is not showing up even though the previous merge succeeded:

* https://anaconda.org/bioconda/pb-assembly

**Comment by pb-cdunn** [comment]
Locally this builds fine:
```
06:11:43 BIOCONDA INFO BUILD START recipes/pb-assembly
06:11:43 BIOCONDA DEBUG build_args: ['--no-anaconda-upload']
06:11:43 BIOCONDA DEBUG channel_args: ['--channel', 'conda-forge', '--channel', 'bioconda', '--channel', 'defaults']
06:11:44 BIOCONDA DEBUG command: ['/scratch/cdunn/miniconda/miniconda/bin/conda', 'build', '--no-anaconda-upload', '--channel', 'conda-forge', '--channel', 'bioconda', '--channel', 'defaults', '-e', '/scratch/cdunn/miniconda/miniconda/conda_build_config.yaml', '-m', '/scratch/cdunn/miniconda/miniconda/lib/python3.6/site-packages/bioconda_utils/bioconda_utils-conda_build_config.yaml', 'recipes/pb-assembly/meta.yaml']
.
06:13:23 BIOCONDA INFO BUILD SUCCESS pb-assembly-0.0.7-py37_0.tar.bz2
06:13:24 BIOCONDA INFO BUILD SUMMARY: successfully built 1 of 1 recipes
```
I think the  error is this:
```
cp: missing destination file operand after `/opt/host-conda-bld/linux-64'

Try `cp --help' for more information.
```
This is a "meta-package" so it contains nothing. I guess I could try adding a dummy file somehow ...

**Comment by pb-cdunn** [comment]
I see something strange when I try to install locally:
```
The following packages will be SUPERSEDED by a higher-priority channel:

  networkx            conda-forge/noarch::networkx-2.3-py_0 --> conda-forge/linux-64::networkx-2.0-py27_0
```
That seems like a mistake in conda-forge, but I don't think it's a real problem since I already have **networkx-2.3** installed in my py3 conda environment.

**Comment by pb-cdunn** [comment]
Whoa! Success! I think py37 requires *something* inside the meta-package, as that was the only change I made in the last commit (in addition to dropping **numpy** since that's already required by **pb-falcon**).

**Comment by pb-cdunn** [comment]
**pb-assembly-0.0.6** still has not shown up in Anaconda:

* https://anaconda.org/bioconda/pb-assembly

**Comment by dpryan79** [comment]
Where is the source code coming from? It's not even in the recipe.

**Comment by epruesse** [comment]
@pb-cdunn Above, BiocondaBot said that no binaries were produced. If it says that, then no binaries will be uploaded. This is a valid scenario, so it cannot be 100% tested against. You can have `skip True # [osx or linux]` in the simplest case. So please, look at what the bot says. If it doesn't say anything, use `@biocondabot recheck` to have it scan again. 

Also, please do not self merge. We need to review the `pb-*` recipes.

**Comment by pb-cdunn** [comment]
> Where is the source code coming from? It's not even in the recipe.

@dpryan79 , This is a meta-package.

@epruesse, This meta-package has hardly changed, but suddenly it's not appearing in Anaconda. Do you think I am doing something contrary to documentation? By my reading, meta-packages are fully supported.

> We need to review the pb-* recipes.

Could you be more specific? What do you think is wrong? Everything was working with py27.

The problem for py37 is esoteric. The Bioconda "c" compiler needs to be upgraded so that it would have `execvp()`, which is used by the standard Python3.7 `Extension` builder. (AFAICT, Python3.6 does not need `execvp()`.) That is the reason **python-edlib** and **python-msgpack** were not building for py37. I've already fixed that (by requiring `cxx` instead), but feel free to review those pypi libraries.

> BiocondaBot said that no binaries were produced.

Right, because it's a "meta-package". This is not a new package, and meta-packages are described here:

* https://bioconda.github.io/guidelines.html#metapackages

If meta-packages are no longer supported, or if they are only intended to amalgamate binaries, let's amend the docs.

My question, since the merge succeeded is this: Why does the following do nothing, when it used to work fine?

    conda install pb-assembly==0.0.6

```
PackagesNotFoundError: The following packages are not available from current channels:

  - pb-assembly==0.0.6

Current channels:

  - https://conda.anaconda.org/bioconda/linux-64
  - https://conda.anaconda.org/bioconda/noarch
  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/linux-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch
```
Should I add a dummy binary to this meta-package?

**Pull request merged**
