### PR TITLE
Update epa-ng to 0.3.8

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`epa-ng`](https://bioconda.github.io/recipes/epa-ng/README.html): **0.3.6** &rarr; **0.3.8**

[install with bioconda](http://bioconda.github.io/recipes/epa-ng/README.html) [Conda](https://anaconda.org/bioconda/epa-ng/files)

Info | Link
-----|-----
Recipe | [`recipes/epa-ng`](https://github.com//bioconda/bioconda-recipes/tree/bump/epa_ng/recipes/epa-ng) (click to view/edit other files)
Releases |[https://github.com/Pbdas/epa-ng/tags](https://github.com/Pbdas/epa-ng/tags)
Author | `@Pbdas`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by Pbdas** [comment]
please close this PR, this version will most likely never compile with macOS

**Comment by Pbdas** [comment]
@bioconda-bot please merge

**Review by Pbdas — APPROVED** [review]

**Comment by Pbdas** [comment]
@BiocondaBot please add label

**Review by natir — APPROVED** [review]

**Comment by Pbdas** [comment]
@bioconda-bot please merge

**Pull request merged**
