### PR TITLE
Update vibrant to 1.2.0

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`vibrant`](https://bioconda.github.io/recipes/vibrant/README.html): **1.0.1** &rarr; **1.2.0**

[install with bioconda](http://bioconda.github.io/recipes/vibrant/README.html) [Conda](https://anaconda.org/bioconda/vibrant/files)

Info | Link
-----|-----
Recipe | [`recipes/vibrant`](https://github.com//bioconda/bioconda-recipes/tree/bump/vibrant/recipes/vibrant) (click to view/edit other files)
Releases |[https://github.com/AnantharamanLab/VIBRANT/tags](https://github.com/AnantharamanLab/VIBRANT/tags)
Author | `@AnantharamanLab`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by npavlovikj** [comment]
The patch needs to be updated.

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Comment by npavlovikj** [comment]
Thank you for fixing this, @dpryan79 !

**Comment by KrisKieft** [comment]
Sorry I'm not sure where to post this, but the VIBRANT package is now tagged as release v1.2.1 and has not been automatically updated (GitHub tagged yesterday). How should I go about specifying that the most up to date version is v1.2.1?

**Comment by npavlovikj** [comment]
The BiocondaBot automatically updates packages to new releases, so I would suggest you to check the open PRs for the new release. Looks there there is a PR from yesterday, https://github.com/bioconda/bioconda-recipes/pull/20921, that is failing and thus hasn't been merged.

**Comment by npavlovikj** [comment]
Looks like similarly as this PT, the issue is the updated patch file.

**Comment by KrisKieft** [comment]
Should I look into resolving the failed patch or will someone get to it eventually? I'm not sure what caused it to fail.

**Pull request merged**
