### PR TITLE
Add mgcod

### PR DESCRIPTION
**Pull request by AaronRuben**
Mgcod: Recognition of genetic codes (incl. multiple genetic codes in phage genomes) and genetic-code-informed annotation of coding regions in prokaryotic sequences

### CODE REVIEW

**Comment by AaronRuben** [comment]
@BiocondaBot please add label

**Comment by telatin** [comment]
Hi @AaronRuben, thanks for adding the recipe.
According to the [guidelines](https://bioconda.github.io/contributor/guidelines.html?highlight=license) the packages should have a "License allows redistribution and license is indicated in meta.yaml".
While your tool meets the request, it depends on GeneMark with its restrictive license. In practical terms the requirement for a key file makes it easy to enforce the user to have read/obtained a license, but I'm not sure if this is enough, so I'd like to have more comments from more expert contributors.

**Review by rpetit3 — APPROVED** [review]

**Comment by rpetit3** [comment]
@BiocondaBot please merge

**Comment by rpetit3** [comment]
@telatin there are a few programs which depend on USEARCH (https://www.drive5.com/usearch/) and have a similar setup. E.g "You can use my tool but you have to go here to accept and download a required tool"

I do agree though GeneMark with an open license would be preferred. Haha @AaronRuben see if you can persuade Mark!

**Comment by telatin** [comment]
Thanks, @rpetit3 !
I was aware of USEARCH but that requires downloading the binary altogether, but as I said the requirement for a licence key is basically the same but good to have a confirmation on this, thanks

**Comment by AaronRuben** [comment]
Thank you very much! I appreciate  it.

@rpetit3 I agree, but I fear this won't happen.

**Pull request merged**
