### PR TITLE
Add matchmsextras

### PR DESCRIPTION
**Pull request by niekdejonge**
Describe your pull request here

A package with additional functions for matchms (already on bioconda)

### CODE REVIEW

**Comment by hechth** [comment]
@niekdejonge is there no license file in the repo? normally it should be working fine if it is contained in there. You can have a look here: https://github.com/bioconda/bioconda-recipes/blob/f4897ca906e33396511fc4e049a16001654820d0/recipes/riassigner/meta.yaml#L4

**Comment by niekdejonge** [comment]
@hechth There is actually, I will make sure we directly use this licence for MS2Query in this way.

**Comment by niekdejonge** [comment]
@BiocondaBot pleas add label

**Comment by niekdejonge** [comment]
@BiocondaBot pleas add label

**Comment by niekdejonge** [comment]
@BiocondaBot please add label

**Review by dpryan79 — APPROVED** [review]

**Pull request merged**
