### PR TITLE
Add trtools to bioconda

### PR DESCRIPTION
**Pull request by LiterallyUniqueLogin**
Adding a new recipe and package to bioconda. Trtools is a tool that allows for analysis of genomic tandem repeat data regardless of which tandem repeat caller (HipSTR, PopSTR, GangSTR, AdVNTR or ExpansionHunter) generated the data.

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by npavlovikj** [comment]
@LiterallyUniqueLogin , I believe you should update your branch with master, the linting shows the error:
```
Your bioconda-recipes CI configuration is out of date.
Please update it to the latest version of the upstream master branch.
Have @BiocondaBot attempt to fix this by creating a comment on your PR:

   @BiocondaBot update

Once the update commit has been created, update your local copy of
your branch:

  git pull


You can also fix this manually, e.g., by running:
  git fetch https://github.com/bioconda/bioconda-recipes.git master
  git merge FETCH_HEAD

Exited with code exit status 1
```

**Comment by LiterallyUniqueLogin** [comment]
Thanks @npavlovikj

I've updated my branch and the tests are rerunning.

**Comment by LiterallyUniqueLogin** [comment]
I'm really confused.  The build fails because my test script `test_trtools.sh` fails. You can see where that starts in the [build log](https://app.circleci.com/pipelines/github/bioconda/bioconda-recipes/26719/workflows/eb09830c-a13b-436a-a08a-797eab5e3ef4/jobs/110058/steps) in these two lines
```
02:38:21 BIOCONDA INFO (OUT) + test_trtools.sh
02:38:21 BIOCONDA INFO (OUT) Downloading test data ...
 ```
However, I just modified the test_trtools.sh script to fix an error (this change is new to trtools 2.0.18). [The most recent version](https://github.com/gymreklab/TRTools/blob/master/trtools/testsupport/test_trtools.sh#L6) of test_trtools.sh prints "Running test_trtools.sh" as the first thing in the script. Why is the most recent version of my script not being used in the build system? It seems that the build system here is still using the script from trtools 2.0.17. How do I debug this? I've checked [pypi](https://pypi.org/project/trtools/2.0.18/#files) and the source distribution of trtools I've uploaded there has the up to date script that should be printing "Running test_trtools.sh"

Any advice appreciated. Thanks!

**Comment by LiterallyUniqueLogin** [comment]
I'm pretty positive this is a caching issue now - I noticed that CircleCI's checks are pulling trtools-2.0.17 even though the branch now says version = 2.0.18. Any ideas?

**Comment by LiterallyUniqueLogin** [comment]
Trying a new pull request [here](https://github.com/bioconda/bioconda-recipes/pull/22406) to see if that fixes the caching issue I'm seeing.

**Pull request closed without merging**
