### PR TITLE
Add virchip recipe

### PR DESCRIPTION
**Pull request by mehrankr**
I added the recipe of Virtual ChIP-seq python package (hosted at https://bitbucket.org/hoffmanlab/virchip) and tested the recipe locally.

Let me know if there are any issues.

### CODE REVIEW

**Comment by dpryan79** [comment]
We don't use submodules, please have a look at other recipes and add a meta.yaml and (if needed) a build.sh.

**Comment by mehrankr** [comment]
> We don't use submodules, please have a look at other recipes and add a meta.yaml and (if needed) a build.sh.

Hey Devon. Thanks for checking this. The recipes/virchip repository on the virchip branch of my fork already has a meta.yaml and build.sh and it works locally using conda-build. The linked repo (https://bitbucket.org/hoffmanlab/virchip), however, doesn't have that which I think it doesn't have to. Could you please elaborate if I'm missing something? Thanks

**Comment by dpryan79** [comment]
I don't see a meta.yaml in this PR, I just see a submodule.

image

**Comment by dpryan79** [comment]
@bioconda-bot please fetch artifacts

**Comment by mehrankr** [comment]
I think something strange is happening. I will delete and try again.

**Pull request closed without merging**
