### PR TITLE
R hash

### PR DESCRIPTION
**Pull request by wjurkowski**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by bgruening** [comment]
@wjurkowski it would be great if this package can be submitted to conda-forge.

**Comment by wjurkowski** [comment]
Not sure if it is not in conda-forge somewhere as I updated the content found in https://anaconda.org/mgoetze/r-hash

**Comment by daler** [comment]
@wjurkowski that appears to be a package in the `mgoetze` channel rather than conda-forge

**Comment by wjurkowski** [comment]
submitted to conda-forge staged-recipes

**Comment by daler** [comment]
Thanks @wjurkowski! Closing this for now; xref https://github.com/conda-forge/staged-recipes/pull/3437

**Pull request closed without merging**
