### PR TITLE
Update r-saige to v1.1.9

### PR DESCRIPTION
**Pull request by pettyalex**
SAIGE is releasing regularly, but not making git releases for releases. That means that Bioconda Bot won't keep it up to date, so I will.

This updates to 1.1.9.

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by dpryan79** [comment]
You'll need to merge in the CI changes from the master branch.

**Comment by pettyalex** [comment]
@BiocondaBot please update

**Comment by cbrueffer** [comment]
Could you clarify the license, e.g. `license: GNU GPL` -> `license: GPL-3.0-only` (as per SPDX vocabulary)?

**Comment by pettyalex** [comment]
@cbrueffer I believe "GPL-3.0-only" is the safest, and I've updated it. Technically, it looks to me like we've got a "GPL 2 or later" license to it, because that's what is explicitly in the package's Description file.

I can reach out to the author for clarification if you'd like, I noticed that older versions of the package were actually distributed under the LGPL 3: https://github.com/weizhouUMICH/SAIGE but this newer version is GPL 3. I find it possible that the license change was unintentional.

**Comment by pettyalex** [comment]
Is GPL 3.0 a problem? It's distributed with that.

**Comment by cbrueffer** [comment]
Bioconda is not very strict on license strings, so `GPL 3.0` would be fine for now as we can get this merged. It would still be good to clarify the license in the upstream project to spare others from the guesswork :-)

**Comment by pettyalex** [comment]
Oh, I marked it `GPL-3.0-only`, seemed like the safest option.

**Comment by cbrueffer** [comment]
No problem, should be fine for now!

**Pull request merged**
