### PR TITLE
proteinortho6.0.2

### PR DESCRIPTION
**Pull request by pmjklemm**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by pmjklemm** [comment]
CI fails on mac with:

```
12:46:48 BIOCONDA INFO (OUT) New link location is None
12:46:48 BIOCONDA INFO (OUT) install_name_tool failed with exit status 1
12:46:50 BIOCONDA ERROR COMMAND FAILED: /Users/distiller/project/miniconda/bin/conda build --no-anaconda-upload --channel conda-forge --channel bioconda --channel defaults -e /Users/distiller/project/miniconda/conda_build_config.yaml -m /Users/distiller/project/miniconda/lib/python3.6/site-packages/bioconda_utils/bioconda_utils-conda_build_config.yaml recipes/proteinortho/meta.yaml

12:46:50 BIOCONDA ERROR BUILD FAILED recipes/proteinortho
12:46:51 BIOCONDA ERROR BUILD SUMMARY: of 1 recipes, 1 failed and 0 were skipped. Details of recipes and environments follow.
12:46:51 BIOCONDA ERROR BUILD SUMMARY: FAILED recipe recipes/proteinortho
Exited with code 1
```

Any idea what this error tells me? (Users/distiller ?)

**Comment by npavlovikj** [comment]
The OSX error you are getting is:
12:46:48 BIOCONDA INFO (ERR) error: /Applications/Xcode-8.3.3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: changing install names or rpaths can't be redone for: /Users/distiller/project/miniconda/conda-bld/proteinortho_1558986241705/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/proteinortho_graphMinusRemovegraph (for architecture x86_64) because larger updated load commands do not fit (the program must be relinked, and you may need to use -headerpad or -headerpad_max_install_names)

**Comment by npavlovikj** [comment]
Is `proteinortho_graphMinusRemovegraph` newly added executable? I don't recall any OSX build issues with the previous version...

Anyhoo, can you maybe try the suggestions here, https://github.com/conda/conda-build/issues/2432, and see if that helps you or not? You should have something like:
```
if [ `uname` == Darwin ]; then
    export LDFLAGS="${LDFLAGS} -headerpad_max_install_names"
fi
```
in `build.sh`.

**Comment by pmjklemm** [comment]
@npavlovikj that is very strange since i added proteinorthoHelper.html and worked on proteinortho2html.pl but i did not touch `proteinortho_graphMinusRemovegraph` ... 
I am not sure where this error now comes from (also on brew and my local osx machine it compiles just fine). 
I will try the suggested LDFLAG tonight, thanks

**Pull request merged**
