### PR TITLE
updated learnMSA to version 1.1.1

### PR DESCRIPTION
**Pull request by felbecker**
Updated the package learnMSA to version 1.1.1

### CODE REVIEW

**Comment by felbecker** [comment]
@BiocondaBot please add label

**Comment by felbecker** [comment]
Please close #39115

**Comment by dpryan79** [comment]
@BiocondaBot please fetch artifacts

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@BiocondaBot please merge

**Comment by dpryan79** [comment]
Closes #39115

**Comment by felbecker** [comment]
Thanks!

**Pull request merged**
