### PR TITLE
nextflow 0.27.5

### PR DESCRIPTION
**Pull request by pditommaso**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by pditommaso** [comment]
Any idea why macos test is failing ?

**Comment by mbargull** [comment]
Probably that build was hit by a temporary outage on the CI service: https://status.circleci.com/incidents/px4cdpl4d10g

**Comment by bgruening** [comment]
Already restarted it ....

**Comment by mbargull** [comment]
That's how I noticed it 😉. (BTW: If you restart it by from the [workflow page](https://circleci.com/workflow-run/4362bf15-5740-44ea-acbe-153012163d8a) (to which you get from the `Workflow: bioconda-test` link on the job page) by clicking `Rerun` -> `Rerun failed jobs`, it will run without starting and keeping a SSH connection open.)

**Comment by pditommaso** [comment]
👍

**Pull request merged**
