### PR TITLE
adding in some perl recipes

### PR DESCRIPTION
**Pull request by jerowe**
* [ ] I have read the guidelines above.
* [x] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

Adding in some perl recipes.

### CODE REVIEW

**Comment by jerowe** [comment]
@bgruening , I know I'm late to the game, but I wanted to do some perl cleanup for the bioconda contribution fest.

I notice when I am building packages with perl-threaded it is pulling in perl from conda-forge. Is this desired behavior?

**Comment by jerowe** [comment]
@bgruening @daler 

```
Exception occurred:

  File "/anaconda/lib/python3.5/site-packages/conda_build/metadata.py", line 162, in ensure_valid_license_family

    (license_family, comma_join(sorted(allowed_license_families)))))

RuntimeError: about/license_family 'GPL' not allowed. Allowed families are AGPL,

Apache, BSD, GPL2, GPL3, LGPL, MIT, Other, PSF, Proprietary, and

Public-Domain.

The full traceback has been saved in /tmp/sphinx-err-xbxus4ay.log, if you want to report the issue to the developers.

Please also report this if it was a user error, so that a better error message can be provided next time.

A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!

Generating package READMEs...

/home/travis/build.sh: line 141:  3108 Terminated              travis_jigger $! $timeout $cmd

The command "travis_wait 75 scripts/travis-run.sh" exited with 1.
```

?

**Comment by daler** [comment]
It looks like this happens when the docs are built. My guess is that the requirements for the docs do not pin a conda version, and the latest conda version is being installed when building the docs which apparently doesn't like non-standardized licenses.

It's a good idea to standardize the license families, but since the docs build *everything* we will have to fix all recipes.  In the meantime, the solution will be to pin the conda version for docs building.

**Comment by bgruening** [comment]
@daler @jerowe I fixed the license issue and tried to kick travis for all failed build. Hopefully everything is now up to date.

We should lint our recipes, so that this does not happen.

**Comment by jerowe** [comment]
Thanks.  I will try that out

**Pull request merged**
