### PR TITLE
Added recipe for blast+-2.2.18 binaries

### PR DESCRIPTION
**Pull request by jlanga**
* [x] I have read the guidelines above.
* [x] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [x] This PR does something else (explain below).

An issue with a lib: some of the binaries require `libcpre.so.0`. `pcre` versions in conda generate `libpcre.so.1`. Therefore I linked `libpcre.so.1` to `libpcre.so.0` in the `lib` folder to make it work.

### CODE REVIEW

**Comment by bgruening** [comment]
@jlanga can you rebase this one please against latest master.

**Comment by jlanga** [comment]
Hi @bgruening . 

One of the binaries requires `lib/libbz2.so`, something very basic. It should be generated by the `bzip2` package, but it is not. 

I'm trying to do a PR to condaforge.

**Comment by bgruening** [comment]
Mh, it containers the `libbz2.a` file.
But the error is still different and should go away if you rebase against latest master.

**Comment by marcelm** [comment]
Please see also discussion at #3020. libbz2.so is now part of the bzip2 package, implemented in conda-forge/bzip2-feedstock#1. The current problem is that conda-forge does not have priority in the recommended channel list, so the default bzip2 package without libbz2.so takes precedence.

**Comment by johanneskoester** [comment]
We have migrated our build system from Travis CI to Circle CI. If you would like to continue working on this PR, please update with latest upstream master and reopen this PR.

**Pull request closed without merging**
