### PR TITLE
Update augur to 10.0.0

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`augur`](https://bioconda.github.io/recipes/augur/README.html): **9.0.0** &rarr; **10.0.0**

[install with bioconda](http://bioconda.github.io/recipes/augur/README.html) [Conda](https://anaconda.org/bioconda/augur/files)

Info | Link
-----|-----
Recipe | [`recipes/augur`](https://github.com//bioconda/bioconda-recipes/tree/bump/augur/recipes/augur) (click to view/edit other files)
Releases |[https://pypi.org/pypi/nextstrain-augur/json](https://pypi.org/pypi/nextstrain-augur/json)
Recipe Maintainer(s) | @huddlej

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by rpetit3** [comment]
@bioconda-bot please merge

**Comment by huddlej** [comment]
@rpetit3 It looks like the auto-bump set the build number to `0`, but [the linter expects that build number to be incremented](https://app.circleci.com/pipelines/github/bioconda/bioconda-recipes/31336/workflows/612bb865-bf3b-4ca0-be3e-41ea7287d5da/jobs/120437).

Does that make sense to you? Do you recommend that I submit a separate PR for this to address the linting error? I'm still quite new to this build system...

**Comment by rpetit3** [comment]
Auto bump setting the build number to 0. I probably messed it up due accepting without catching the minor typo. Now it's asking for the bump since the previous passed.

**Comment by huddlej** [comment]
Ah, I get it, thank you!

**Comment by rpetit3** [comment]
@bioconda-bot please merge

**Pull request merged**
