### PR TITLE
Revert blacklisting of BLAST+ package.

### PR DESCRIPTION
**Pull request by peterjc**
See today's discussion on #6073, starting at https://github.com/bioconda/bioconda-recipes/pull/6073#issuecomment-335876343

This appears to have been done as part of #6119 out of expediency to get a large set of builds done.

Cross reference #6282 for updating to BLAST+ 2.7.0 which was merged recently.

* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [X] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [X] This PR updates an existing recipe.
* [X] This PR does something else (explain below).

### CODE REVIEW

**Comment by epruesse** [comment]
The recipe for building BLAST+ from source is nearly finished. It passed on Linux and works fine on my Mac.

Changes:
 - built from source on both archs
 - uses dynamic libs, saving about 1/2 GB space
 - supports `-remote` with gnutls

Do we prefer the "safe" upstream binary release or the build-from-source version? If the latter, then it would be better if it had build number 0, as conda likes to prefer packages with less dependencies and can't be forced to use a newer build number.

I'm open to other ideas. Two packages if necessary.

**Comment by peterjc** [comment]
Right now the BLAST+ recipes use a hybrid approach, building for Linux 64, but using the NCBI binary for macOS since building was failing.

Personally I used to lean towards the NCBI provided binaries for BOTH macOS and Linux, for the principle of reproducibility - no chance of us introducing a compiler/library specific glitch, and simplicity - the build dependencies seem complex. However, if that prevents the use of ``-remote`` that is a major drawback.

I'm happy to defer to the BioConda experts - and if there is good reason to delay the BLAST+ 2.7.0 package so that build 0 of this is from source with the ``gnutls`` dependency, so be it.

**Comment by epruesse** [comment]
I see the benefits of both.

**Comment by nsoranzo** [comment]
I'd vote for merging #6073 when it is green and out of WIP. In Bioconda we try to build from source whenever possible and that's already the case for the Linux build of blast anyway, as mentioned above.

**Comment by Cashalow** [comment]
I'm all in for the built version obviously. Probably @bgruening has an opinion as he briefly commented on one of the PR ? However the osx build is still failing with the same error :(

**Comment by bgruening** [comment]
I prefer the self-build one. @peterjc has some point, but we could argument this way for every pre-compiled binary and scarify the HPC-compliance. An other argument is the pure size. We can not be wasteful. If we can save space we should.

**Comment by peterjc** [comment]
If #6073 gets finished, I'm happy for that to be merged instead of this pull request (i.e. update to build with ``gnutls`` and ``-remote`` working; and remove the blacklisting).

(I've run into a segmentation fault in BLAST+ 2.7.0 so am currently not in any rush to adopt it - see https://blastedbio.blogspot.com/2017/10/blast-270-segmentation-fault-with-html.html and https://github.com/peterjc/galaxy_blast/issues/93#issuecomment-336088066 for details)

**Comment by epruesse** [comment]
That's reproducible with my build :(

```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff3258491 in ncbi::IRegistry::ReadLock() () from /Users/elpr2080/miniconda3/envs/blast27/bin/../lib/libxncbi.so
(gdb) bt
#0  0x00007ffff3258491 in ncbi::IRegistry::ReadLock() () from /Users/elpr2080/miniconda3/envs/blast27/bin/../lib/libxncbi.so
#1  0x00007ffff32598bf in ncbi::IRegistry::Get(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int) const () from /Users/elpr2080/miniconda3/envs/blast27/bin/../lib/libxncbi.so
#2  0x00007ffff73d4d7e in ncbi::align_format::CAlignFormatUtil::GetIDUrlGen(ncbi::align_format::CAlignFormatUtil::SSeqURLInfo*, std::list<ncbi::CRef<ncbi::objects::CSeq_id, ncbi::CObjectCounterLocker>, std::allocator<ncbi::CRef<ncbi::objects::CSeq_id, ncbi::CObjectCounterLocker> > > const*) () from /Users/elpr2080/miniconda3/envs/blast27/bin/../lib/libalign_format.so
#3  0x00007ffff73da7e6 in ncbi::align_format::CAlignFormatUtil::GetIDUrl(ncbi::align_format::CAlignFormatUtil::SSeqURLInfo*, std::list<ncbi::CRef<ncbi::objects::CSeq_id, ncbi::CObjectCounterLocker>, std::allocator<ncbi::CRef<ncbi::objects::CSeq_id, ncbi::CObjectCounterLocker> > > const*) () from /Users/elpr2080/miniconda3/envs/blast27/bin/../lib/libalign_format.so
#4  0x00007ffff73e24f9 in ncbi::align_format::CAlignFormatUtil::GetIDUrl(ncbi::align_format::CAlignFormatUtil::SSeqURLInfo*, ncbi::objects::CSeq_id const&, ncbi::objects::CScope&) ()
   from /Users/elpr2080/miniconda3/envs/blast27/bin/../lib/libalign_format.so
#5  0x00007ffff73fd300 in ncbi::align_format::CShowBlastDefline::x_FillDeflineAndId(ncbi::objects::CBioseq_Handle const&, ncbi::objects::CSeq_id const&, std::list<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, ncbi::align_format::CShowBlastDefline::SDeflineInfo*, int) ()
   from /Users/elpr2080/miniconda3/envs/blast27/bin/../lib/libalign_format.so
#6  0x00007ffff73fdcdb in ncbi::align_format::CShowBlastDefline::x_GetDeflineInfo(ncbi::CConstRef<ncbi::objects::CSeq_id, ncbi::CObjectCounterLocker>, std::list<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, int) () from /Users/elpr2080/miniconda3/envs/blast27/bin/../lib/libalign_format.so
#7  0x00007ffff73fe4b5 in ncbi::align_format::CShowBlastDefline::x_DisplayDefline(std::basic_ostream<char, std::char_traits<char> >&) ()
   from /Users/elpr2080/miniconda3/envs/blast27/bin/../lib/libalign_format.so
#8  0x00007ffff73ffda4 in ncbi::align_format::CShowBlastDefline::DisplayBlastDefline(std::basic_ostream<char, std::char_traits<char> >&) ()
   from /Users/elpr2080/miniconda3/envs/blast27/bin/../lib/libalign_format.so
#9  0x00007ffff76cb328 in ncbi::CBlastFormat::x_DisplayDeflines(ncbi::CConstRef<ncbi::objects::CSeq_align_set, ncbi::CObjectCounterLocker>, unsigned int, std::set<ncbi::objects::CSeq_id_Handle, std::less<ncbi::objects::CSeq_id_Handle>, std::allocator<ncbi::objects::CSeq_id_Handle> >&, int, int, int) () from /Users/elpr2080/miniconda3/envs/blast27/bin/../lib/libxblastformat.so
#10 0x00007ffff76d39a8 in ncbi::CBlastFormat::PrintOneResultSet(ncbi::blast::CSearchResults const&, ncbi::CConstRef<ncbi::blast::CBlastQueryVector, ncbi::CObjectCounterLocker>, unsigned int, std::set<ncbi::objects::CSeq_id_Handle, std::less<ncbi::objects::CSeq_id_Handle>, std::allocator<ncbi::objects::CSeq_id_Handle> >, bool) () from /Users/elpr2080/miniconda3/envs/blast27/bin/../lib/libxblastformat.so
#11 0x00000000004132d7 in CTblastnApp::Run() ()
#12 0x00007ffff31b2073 in ncbi::CNcbiApplication::x_TryMain(ncbi::EAppDiagStream, char const*, int*, bool*) () from /Users/elpr2080/miniconda3/envs/blast27/bin/../lib/libxncbi.so
#13 0x00007ffff31b3c4d in ncbi::CNcbiApplication::AppMain(int, char const* const*, char const* const*, ncbi::EAppDiagStream, char const*, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from /Users/elpr2080/miniconda3/envs/blast27/bin/../lib/libxncbi.so
#14 0x0000000000416ecc in main ()
```

**Comment by peterjc** [comment]
The NCBI have replaced BLAST+ 2.7.0 with 2.7.1 to solve that seg-fault.

**Comment by peterjc** [comment]
No longer needed since #6073 was merged, closing.

**Pull request closed without merging**
