### PR TITLE
Aria2 1.23.0

### PR DESCRIPTION
**Pull request by acaprez**
* [X] I have read the guidelines above.
* [X] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

This adds the `aria2` package, and needed dependencies `libssh2` and `c-ares`.  

Question for @bioconda/core - is there a recommended way to do testing for library only packages?  The `libssh2` and `c-ares` packages are both library-only.  What I've done previously is just test to see if the main libs and header files exist, so I did that here as well.  Just wondering if there's an alternate way that's preferred?

### CODE REVIEW

**Comment by johanneskoester** [comment]
That sounds reasonable to me. I would do it the same way.

**Comment by acaprez** [comment]
Ok - thanks.  Good to merge this then?

**Comment by johanneskoester** [comment]
Yes, looks good! Thanks!

**Comment by bgruening** [comment]
I have seen very tiny files which you compile in the test to test the library.
On Jun 8, 2016 7:22 PM, Johannes Köster <notifications@github.com> wrote:That sounds reasonable to me. I would do it the same way.

**Pull request merged**
