### PR TITLE
Update sherpas to 1.0.2

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`sherpas`](https://bioconda.github.io/recipes/sherpas/README.html): **1.0.0** &rarr; **1.0.2**

[install with bioconda](http://bioconda.github.io/recipes/sherpas/README.html) [Conda](https://anaconda.org/bioconda/sherpas/files)

Info | Link
-----|-----
Recipe | [`recipes/sherpas`](https://github.com//bioconda/bioconda-recipes/tree/bump/sherpas/recipes/sherpas) (click to view/edit other files)
Releases |[https://github.com/phylo42/sherpas/releases](https://github.com/phylo42/sherpas/releases)
Author | `@phylo42`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by dpryan79** [comment]
This uses a submodule of xpas_dna that will either need to be added to conda or we need to switch to using a git checkout. I'm surprised the build doesn't fail.

**Comment by dpryan79** [comment]
Ah, it's built but not installed.

**Comment by blinard-BIOINFO** [comment]
There is indeed an issue on the xpas library side (currently not building on macos).
We are working on it.
I will relaunch the circle ci tests when it is solved.

**Comment by blinard-BIOINFO** [comment]
We have found the issue, which is a macos incompatibility due to novel compilation errors we introduced in this new version.
We will release a new version 1.0.2 soon and I will update the recipe with its version and sha when done.

**Review by blinard-BIOINFO — COMMENTED** [review]
ok

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Pull request merged**
