### PR TITLE
Added recipe for msmsEDA

### PR DESCRIPTION
**Pull request by ArneKr**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by ArneKr** [comment]
@bgruening Ever since i added my fork to circleci it seems that the check on the PR never completes. Any ideas? Making an empty commit seems to do the trick but that would not actually fix whats wrong.

**Comment by bgruening** [comment]
@ArneKr something very strange goes on here. It seems that all you local tests on your fork, gets counted into the BioConda quota.
Can you describe how you added your fork to Circle-CI. I guess we need to contact them.
In the meantime can you confirm that all your recent PRs do pass all 3 checks on your fork?

**Comment by ArneKr** [comment]
@bgruening I just added the fork under add projects on the circleci site. Didn't change anything in the .circleci folder. All my curent PRs passed all 3 tests on my fork.

**Comment by ArneKr** [comment]
@bgruening And by all PRs i only mean those that are still stuck at the first test. Some of the older PRs failed the tests, but there everything still worked as intended.

**Comment by bgruening** [comment]
So I used the superpower do merge them. Thanks for all of your work! We will contact Circle-CI to ask what is going wrong here.

**Pull request merged**
