### PR TITLE
Update nanomotif to 0.5.0

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`nanomotif`](https://bioconda.github.io/recipes/nanomotif/README.html): **0.4.17** &rarr; **0.5.0**

[install with bioconda](http://bioconda.github.io/recipes/nanomotif/README.html) [Conda](https://anaconda.org/bioconda/nanomotif/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/nanomotif`](https://github.com//bioconda/bioconda-recipes/tree/bump/nanomotif/recipes/nanomotif) (click to view/edit other files)
Summary | Identifying methlyation motifs in nanopore data
Home | [https://github.com/MicrobialDarkMatter/nanomotif](https://github.com/MicrobialDarkMatter/nanomotif)
Releases |[https://pypi.org/pypi/nanomotif/json](https://pypi.org/pypi/nanomotif/json)
Recipe Maintainer(s) | @SorenHeidelbach

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by SorenHeidelbach** [comment]
Add pymethyl_utils as dependency

**Comment by martin-g** [comment]
@SorenHeidelbach There is no such package - https://anaconda.org/search?q=pymethyl_utils

**Comment by SorenHeidelbach** [comment]
Sorry, it is 
pymethylation_utils

**Comment by martin-g** [comment]
https://anaconda.org/search?q=pymethylation_utils - same

**Comment by SorenHeidelbach** [comment]
It is only available on pypi, is it possible to include?

**Comment by martin-g** [comment]
Someone will have to create a recipe for it too

**Review by daler — APPROVED** [review]

**Pull request merged**
