### PR TITLE
PeptideShaker python

### PR DESCRIPTION
**Pull request by bgruening**
* [x] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by bgruening** [comment]
ping @dakl @chapmanb 
Thanks for enhancing and reviewing!

If you think this is ready to go I will patch a few more.

**Comment by chapmanb** [comment]
Nice one. Thanks for incorporating this. +1 from me.

**Comment by dakl** [comment]
Me too! 👍😀
lör 11 juni 2016 kl. 23:05 skrev Brad Chapman <notifications@github.com>:

**Comment by bgruening** [comment]
Thanks!

**Pull request merged**
