### PR TITLE
init new recipe with perl-crypt-ssleay

### PR DESCRIPTION
**Pull request by fgiacomoni**
* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [X] This PR adds a new recipe.
* [X] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by Chris-Lowe-Integrity** [comment]
I'm not seeing anything that is directly biologically relevant with this program.  THe data produced may be. I am going to attempt a recipe and push it through conda-forge.

**Comment by Chris-Lowe-Integrity** [comment]
I'm getting this error when attempting to build locally. 
The packages exist though I'm not sure why they arn't being found.
raise ResolvePackageNotFound(bad_deps)
conda.exceptions.ResolvePackageNotFound: 
  - perl-extutils-makemaker
  - perl-extutils-cbuilder
  - perl-getopt-long
  - perl-mime-base64
  - perl-try-tiny
  - perl-path-class
  - perl-lwp-protocol-https

**Comment by pcm32** [comment]
Working now on moving to conda-forge... will paste fork/branch (starting from scratch with skeleton).

**Comment by pcm32** [comment]
Is this package still need it @fgiacomoni? Building is not working well and advice on the package itself is that you might not needed given later advances in other packages: https://metacpan.org/pod/Crypt::SSLeay#DO-YOU-NEED-Crypt::SSLeay?

Let us now to otherwise close this and avoid moving to conda-forge.

**Pull request closed without merging**
