### PR TITLE
TIDDIT 2.7.1

### PR DESCRIPTION
**Pull request by J35P312**
Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it. Note that if you are not already a member of the bioconda project (meaning that you can't add this label), please ping `@bioconda/core` so that your PR can be reviewed and merged (please note if you'd like to be added to the bioconda project). Please see https://github.com/bioconda/bioconda-recipes/issues/15332 for more details.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by apeltzer** [comment]
I think it still needs the `cython` in the build section....

**Comment by apeltzer** [comment]
```
 File "setup.py", line 2, in <module>
13:21:47 BIOCONDA INFO (OUT)     from Cython.Build import cythonize
13:21:47 BIOCONDA INFO (OUT) ImportError: No module named Cython.Build
```

That means we still need `cython` in the build phase I guess. Should readd that I suppose and then see if linting still complains. I think the initial complaint was about not bumping the recipe number with +1...

**Comment by J35P312** [comment]
Thanks! This was a tricky error! I added Cython to the build phase. But now Lint is unhappy again, do you have any advice on how to fix this?

//JEsper

**Comment by apeltzer** [comment]
it's two things it complains about now:

a.) 13:49:48 BIOCONDA DEBUG Found: LintMessage(recipe=Recipe "tiddit", check=<class 'bioconda_utils.lint.check_build_help.cython_must_be_in_host'>, severity=<Severity.ERROR: 30>, title='Cython should be in the build section', body='\nMove cython to `host`:\n\n  requirements:\n    host:\n      - cython', start_line=0, end_line=0, fname='recipes/tiddit/meta.yaml', canfix=False)

This is not entirely clear to me unfortunately. The `bioconda_utils.lint.check_build_help.cython_must_be_in_host`suggests that it has to be in the `host`section, whereas the `Cython should be in the build section` suggests it should be in the build section and has a body of `Move cython to `host`. @bioconda/core  any idea what is correct now? 


b.) 
13:49:48 BIOCONDA DEBUG Found: LintMessage(recipe=Recipe "tiddit", check=<class 'bioconda_utils.lint.check_build_help.cython_needs_compiler'>, severity=<Severity.WARNING: 20>, title='Cython generates C code, which will need to be compiled', body="\nAdd the compiler to the recipe:\n\n  requirements:\n    build:\n      - {{ compiler('c') }}", start_line=0, end_line=0, fname='recipes/tiddit/meta.yaml', canfix=False)

=> add `- {{ compiler('c') }}` to the `build` section right under the `cxx` one and this should be fine again.

**Comment by dpryan79** [comment]
I see there's a typo in the linter message. Cython should be in the host section, for the sake of consistency with python being there. I've changed things so the linting should pass now and will try to ma e a PR to fix the typo in the linter output.

**Comment by apeltzer** [comment]
Thank you very much @dpryan79 !

**Comment by J35P312** [comment]
That's great, Thanks a lot every one!

**Pull request merged**
