### PR TITLE
add qtdt

### PR DESCRIPTION
**Pull request by MathiasHaudgaard**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by MathiasHaudgaard** [comment]
@ArneKr lav lige den her pakke :shipit:

**Comment by MathiasHaudgaard** [comment]
@bgruening I'm having trouble figuring out why this package is failing. It seems like it has something to do with zlib. I followed the troubleshooting guide on zlib but it didn't help.

**Comment by bgruening** [comment]
@MathiasHaudgaard I think you need to patch the Makefile. This line `CFLAGS=-O -I./libsrc -D__ZLIB_AVAILABLE__` to include the path to zlib.

**Comment by daler** [comment]
Closing due to inactivity, please re-open if needed.

**Pull request closed without merging**
