### PR TITLE
Add recipe for piranha-polio

### PR DESCRIPTION
**Pull request by rpetit3**
This PR adds a recipe for [Piranha](https://github.com/polio-nanopore/piranha) a tool for the analysis of Polio sequencing

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by rpetit3** [comment]
@aineniamh I pinned the versions to match yours. Can you foresee any issues if I relax the pinnings (e.g. `samtools >= 1.11`)?

**Comment by aineniamh** [comment]
We were having trouble with the environment solving because of medaka and snakemake- these were the versions that worked, so to prevent any unforseen issues I made it quite specific. I can't say for sure if they relaxed whether that would introduce any problems.

**Comment by rpetit3** [comment]
@BiocondaBot please fetch artifacts

**Comment by rpetit3** [comment]
# Create test env
```
mamba create -y -n test-piranha \
    -c conda-forge -c bioconda \
    'python<3.10' \
    'coreutils>=9.1' \
    gofasta \
    mafft \
    racon \
    'minimap2>=2.17' \
    'samtools>=1.11' \
    'bcftools>=1.11' \
    'tabix>=1.11' \
    snakemake-minimal \
    'mako>=1.2' \
    snipit \
    biopython \
    'medaka>=1.7.1'
conda activate test-piranha

wget -O LinuxArtifacts.zip https://artprodsu6weu.artifacts.visualstudio.com/A27bcc0f9-b22c-4418-83d8-514809b37fb2/25074ded-3133-43ca-af80-895ab87b53cb/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL2Jpb2NvbmRhL3Byb2plY3RJZC8yNTA3NGRlZC0zMTMzLTQzY2EtYWY4MC04OTVhYjg3YjUzY2IvYnVpbGRJZC8yMzk2NS9hcnRpZmFjdE5hbWUvTGludXhBcnRpZmFjdHM1/content?format=zip

unzip LinuxArtifacts.zip
conda install LinuxArtifacts/packages/noarch/piranha-polio-1.0.4-pyhdfd78af_0.tar.bz2
```

# Test Conda
```
piranha --help

                   __
                    ______ |__|_____ _____  |\____ |  |__ _____
                    \____ \|  |\  _ \\__  \ |     \|  |  \\__  \
                    |  |_| |  ||  |\/ / __ \|   |  \   |  \/ __ \
                    |   __/|__||__|  (____ / ___|__/___|___(____/
                    |__|

                     **** Poliovirus Investigation Resource ****
                   **** Automating Nanopore Haplotype Analysis ****
... TRUNCATED ...
  --verbose             Print lots of stuff to screen
  -v, --version         show program's version number and exit
  -h, --help


piranha --version
piranha 1.0.4

# Clone piranha and run test data
git clone git@github.com:polio-nanopore/piranha.git
cd piranha
piranha -i piranha/test/pak_run/demultiplexed --verbose -b piranha/test/pak_run/barcodes01.csv -t 2 2>&1 | tee piranha.log
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 2
Rules claiming more threads will be scaled down.
Job stats:
job                        count    min threads    max threads
-----------------------  -------  -------------  -------------
all                            1              1              1
assess_broad_diversity         2              1              1
filter_by_length               2              1              1
gather_diversity_report        1              1              1
map_reads                      2              2              2
write_hit_fastq                2              1              1
total                         10              1              2

Select jobs to execute...

... TRUNCATED ...

 - runid: 69f8170ea3dc8a7b70044edf12d68262fe0d5302
 - samples: ['negative', 'somemixed']
 - tempdir: /tmp/tmp2xnv2dtm
 - threads: 2
 - username:
 - verbose: True
Generating: /home/robert_petit/temp/test-piranha/piranha/analysis_2022-11-10/report.html


piranha -i piranha/test/pak_run/demultiplexed --verbose -b piranha/test/pak_run/barcodes.csv -t 2 2>&1 | tee piranha_all.log
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 2
Rules claiming more threads will be scaled down.
Job stats:
job                        count    min threads    max threads
-----------------------  -------  -------------  -------------
all                            1              1              1
assess_broad_diversity         7              1              1
filter_by_length               7              1              1
gather_diversity_report        1              1              1
map_reads                      7              2              2
write_hit_fastq                7              1              1
total                         30              1              2

Select jobs to execute...

... TRUNCATED ...
 - runid: 69f8170ea3dc8a7b70044edf12d68262fe0d5302
 - samples: ['MixedTest', 'PureTest', 'WTTest', 'VDPVTest', 'negative', 'positively', 'somemixed']
 - tempdir: /tmp/tmpy2udy8kl
 - threads: 2
 - username:
 - verbose: True
Generating: /home/robert_petit/temp/test-piranha/piranha/analysis_2022-11-10_1/report.html
```

Conda looks good. Let's try the Docker image.

# docker test
```
gzip -dc LinuxArtifacts/images/piranha-polio:1.0.4--pyhdfd78af_0.tar.gz | docker load

docker run --rm -u $(id -u):$(id -g) -v ${PWD}:/data quay.io/biocontainers/piranha-polio:1.0.4--pyhdfd78af_0 piranha --help


                            __                      __
                    ______ |__|_____ _____  |\____ |  |__ _____
                    \____ \|  |\  _ \\__  \ |     \|  |  \\__  \
                    |  |_| |  ||  |\/ / __ \|   |  \   |  \/ __ \
                    |   __/|__||__|  (____ / ___|__/___|___(____/
                    |__|

                     **** Poliovirus Investigation Resource ****
                   **** Automating Nanopore Haplotype Analysis ****

                                        1.0.4
                        ****************************************

                       Aine O'Toole, Rachel Colquhoun, Corey Ansley,
                                    Andrew Rambaut
                                 Edinburgh University


usage:
        piranha -c <config.yaml> [options]
        piranha -i input.csv [options]
...TRUNCATED...
  --verbose             Print lots of stuff to screen
  -v, --version         show program's version number and exit
  -h, --help

docker run --rm -u $(id -u):$(id -g) -v ${PWD}:/data quay.io/biocontainers/piranha-polio:1.0.4--pyhdfd78af_0 piranha --version

piranha 1.0.4

# Test data
docker run --rm -u $(id -u):$(id -g) -v ${PWD}:/data -v ${PWD}/.cache:/.cache -v ${PWD}/.medaka:/.medaka quay.io/biocontainers/piranha-polio:1.0.4--pyhdfd78af_0 piranha -i /data/piranha/test/pak_run/demultiplexed --verbose -b /data/piranha/test/pak_run/barcodes.csv -t 2 --outdir /data/test-docker 2>&1 | tee piranha_docker_all.log
Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 2
Rules claiming more threads will be scaled down.
Job stats:
job                        count    min threads    max threads
-----------------------  -------  -------------  -------------
all                            1              1              1
assess_broad_diversity         7              1              1
filter_by_length               7              1              1
gather_diversity_report        1              1              1
map_reads                      7              2              2
write_hit_fastq                7              1              1
total                         30              1              2

Select jobs to execute...
... TRUNCATED ...
 - runid: 69f8170ea3dc8a7b70044edf12d68262fe0d5302
 - samples: ['MixedTest', 'PureTest', 'WTTest', 'VDPVTest', 'negative', 'positively', 'somemixed']
 - tempdir: /data/test-docker_9
 - threads: 2
 - username:
 - verbose: True
Generating: /data/test-docker_9/report.html
```

had to mound `.cache` and `.medaka` to get it to work, but it does work.

**Comment by rpetit3** [comment]
@aineniamh I think we are good, if you like I can share the final HTML reports. I used the tests from your github action. 

Also take a look at the pinnings and let me know if that's going to be an issue.

**Comment by rpetit3** [comment]
@BiocondaBot please add label

**Comment by dpryan79** [comment]
@BiocondaBot please fetch artifacts

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@BiocondaBot please merge

**Comment by dpryan79** [comment]
@BiocondaBot please merge

**Pull request merged**
