### PR TITLE
Update meta.yaml

### PR DESCRIPTION
**Pull request by BaselAbujamous**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by npavlovikj** [comment]
You can make the recipe `noarch: python`, remove the `skip` section, and use `python <3` in the `requirements` part (please see https://github.com/bioconda/bioconda-recipes/blob/066c34a42b266ab2b00afc7c50d9e356de127b4a/recipes/nucleoatac/meta.yaml for an example). Also, you can remove `build.sh` and use `script` in `meta.yaml` (same as in the given example).

**Comment by BaselAbujamous** [comment]
@npavlovikj , I have updated the recipe as suggestion. Checks all have passed.

**Comment by npavlovikj** [comment]
@BaselAbujamous , is there a reason why the license type is different in your repo and pypi? If possible, I would suggest you to keep the same license type, and also package the license file in your pypi package.

**Comment by BaselAbujamous** [comment]
@npavlovikj  Done (with some extra fixes)

**Comment by npavlovikj** [comment]
Thanks @BaselAbujamous . So, one more thing now, and I will merge the recipe.
Since you have fixed the license, just to be uniform with the other bioconda recipes and syntax, please replace:
**license: GNU Lesser General Public License v3.0**
with
**license: LGPL-3.0**
**license_family: LGPL**

**Comment by BaselAbujamous** [comment]
Done @npavlovikj  :)

**Comment by npavlovikj** [comment]
Thanks for all the work here @BaselAbujamous , the recipe LGTM :)

**Comment by BaselAbujamous** [comment]
Thanks a lot @npavlovikj :)

**Pull request merged**
