### PR TITLE
bioconda utils perl test

### PR DESCRIPTION
**Pull request by bgruening**
* [x] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by johanneskoester** [comment]
Looks like a bug in conda build 1.21.11. Can you try upgrading to 1.21.12?

**Comment by bgruening** [comment]
I updated the version inside of the container, the error is still the same.

**Comment by johanneskoester** [comment]
Rebased to #2274.

**Comment by johanneskoester** [comment]
@bgruening I have discovered the next bug in conda build. This time it is the x.x code that needs to be fixed in order to work for us. I hope to be able to fix it fast.

**Comment by johanneskoester** [comment]
It is finally working!

**Comment by bgruening** [comment]
Yeah!!!!

**Pull request merged**
