### PR TITLE
MultiQC: v1.1 Release.

### PR DESCRIPTION
**Pull request by ewels**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by ewels** [comment]
Tests passing, so will merge 👍

**Comment by micknudsen** [comment]
Is there any particular reason why there no longer is a Python 3.6 version?

**Comment by ewels** [comment]
Hi @micknudsen,

Damn, no I hadn't noticed this sorry. We had problems with Python 3 in previous releases due to the `click` dependency (see #4803, #4811 and others). I had thought that @bgruening fixed it in the latter version (possibly with broken containers), but it looks like the `skip` was added again by @johanneskoester in [#4888](https://github.com/bioconda/bioconda-recipes/pull/4888/files#diff-b2ec8fee278f656d88d113e6dfee721a).

The TL;DR; is that the `click` author seems to really dislike python 3 for some reason (😞 ) and that it has difficulties picking up the encoding type in some environments. When this happens [the build fails](https://travis-ci.org/bioconda/bioconda-recipes/jobs/235927260#L677). Whenever I install it manually (`python setup.py install` or `pip install`) it works fine, presumably because I have defined a locale on my system:

```bash
export LC_ALL=C.UTF-8
export LANG=C.UTF-8
```

Further reading from the click author [here](http://click.pocoo.org/5/python3/#python-3-surrogate-handling).

This is obviously pretty frustrating. @johanneskoester / @bgruening - is this a fair description of the problem? Any new ideas of what we can do to fix this, other than waiting for the click author to change something in his package (which I suspect will never happen)..? Could we set a locale as above in the build environment or something?

Phil

**Comment by bgruening** [comment]
@ewels you can try to use:

```
extra:
    container:
         extended-base: true
```

Other than that, I think your summary is pretty complete. There is a change that Python3.7 will fix this to a degree that click developers are happy, but in the meantime it would be nice if they can just issue a warning and not an error.

**Comment by ewels** [comment]
Thanks @bgruening! Out of curiousity, do you know what is it that this container has that the busybox is missing?

**Comment by bgruening** [comment]
Busybox has no locales installed, it is really a tiny box :)

**Pull request merged**
