### PR TITLE
update falco release and build instructions

### PR DESCRIPTION
**Pull request by guilhermesena1**
Falco is having segfaults when downloaded through conda, I will use this PR to fetch artifacts until we are sure that it is behaving as expected. Apologies again for the constant PRs but I sincerely hope this is the last time in a while where we will need to ask bioconda for updates!

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by guilhermesena1** [comment]
@BiocondaBot please fetch artifacts

**Comment by guilhermesena1** [comment]
@BiocondaBot please fetch artifacts

**Comment by guilhermesena1** [comment]
@BiocondaBot please fetch artifacts

**Comment by guilhermesena1** [comment]
FINALLY!!!

**Comment by guilhermesena1** [comment]
@BiocondaBot please add label

**Comment by dpryan79** [comment]
I suspect that the `>=` is breaking the normal pinning mechanisms. Can you try removing the version restrictions to ensure that that also runs without segfaulting? The issue with strictly pinning zlib and htslib inside the recipe is that it quickly becomes impossible to install falco in environments with other packages.

**Comment by guilhermesena1** [comment]
Done. I was using `bioconda-utils` to test locally using the following command

```
bioconda-utils build --force recipes --keep-old-work --keep-image --packages falco
```

but whenever I kept the `>=` constraints it kept giving me errors. So far falco seems to work with any version of zlib and htslib, so I'll keep this out until we have evidence that this is not true.

**Comment by guilhermesena1** [comment]
@BiocondaBot please fetch artifacts

**Comment by guilhermesena1** [comment]
It works fine without the >= constraints :) definitely stable now as far as I can tell.
I'm not sure if I should type `please add label` again if it's ready to be merged?

**Comment by guilhermesena1** [comment]
@BiocondaBot please add label

**Review by cbrueffer — APPROVED** [review]

**Comment by cbrueffer** [comment]
@bioconda-bot please merge

**Pull request merged**
