### PR TITLE
Update easypqp to 0.1.5

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`easypqp`](https://bioconda.github.io/recipes/easypqp/README.html): **0.1.0** &rarr; **0.1.5**

[install with bioconda](http://bioconda.github.io/recipes/easypqp/README.html) [Conda](https://anaconda.org/bioconda/easypqp/files)

Info | Link
-----|-----
Recipe | [`recipes/easypqp`](https://github.com//bioconda/bioconda-recipes/tree/bump/easypqp/recipes/easypqp) (click to view/edit other files)
Releases |[https://pypi.org/pypi/easypqp/json](https://pypi.org/pypi/easypqp/json)

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by dpryan79** [comment]
@Leon-Bichmann As I recall you just added this, so can you double check the update?

**Comment by Leon-Bichmann** [comment]
ok yes looks good

**Comment by Leon-Bichmann** [comment]
@grosenberger easypqp is now on bioconda

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Pull request merged**
