### PR TITLE
Add TideHunter

### PR DESCRIPTION
**Pull request by yangao07**
**Add TideHunter: efficient and sensitive tandem repeat detection from noisy long reads using seed-and-chain**

----

> Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences**
      (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

> Everyone has access to the following BiocondaBot commands, which can be given in a comment:
>
>  * `@BiocondaBot please update` will cause the BiocondaBot to merge the master branch into a PR
>  * `@BiocondaBot please add label` will add the `please review & merge` label.
>  * `@BiocondaBot please fetch artifacts` will post links to packages and docker containers built by the CI system. You can use this to test packages locally before merging.
>
> For members of the Bioconda project, the following command is also available:
>
>  * `@BiocondaBot please merge` will cause packages/containers to be uploaded and a PR merged. Someone must approve a PR first! This has the benefit of not wasting CI build time required by manually merging PRs.
>
> If you have questions, please post them in gitter or ping `@bioconda/core` in a comment (if you are not able to directly ping `@bioconda/core` then the bot will repost your comment and enable pinging).

### CODE REVIEW

**Comment by yangao07** [comment]
@BiocondaBot please add label

**Comment by yangao07** [comment]
Hi @dpryan79 ,
I see you are making changes to the build.sh, is that necessary to make it approved?
The `build.sh` right now actually does something a little bit different from what it should do.

Yan

**Comment by dpryan79** [comment]
The changes are needed because the variables (CFLAGS, etc.) aren't being properly passed between the makefiles otherwise. Thus I'm forcing them to be handled properly.

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Comment by yangao07** [comment]
OK.
In the `build.sh` file, anthoer `make` is also needed:
```
pushd abPOA
make simd
make libabpoa INCLUDE="-I$PREFIX/include" CFLAGS="$CFLAGS -L$PREFIX/lib"
popd
```
@dpryan79 Can you help me update this?
Thansk!

**Comment by dpryan79** [comment]
You'd need to make another PR if that's really needed.

**Comment by yangao07** [comment]
OK. I will do that.

**Pull request merged**
