### PR TITLE
Update eukcc to 0.2

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`eukcc`](https://bioconda.github.io/recipes/eukcc/README.html): **0.1.5.1** &rarr; **0.2**

[install with bioconda](http://bioconda.github.io/recipes/eukcc/README.html) [Conda](https://anaconda.org/bioconda/eukcc/files)

Info | Link
-----|-----
Recipe | [`recipes/eukcc`](https://github.com//bioconda/bioconda-recipes/tree/bump/eukcc/recipes/eukcc) (click to view/edit other files)
Releases |[https://pypi.org/pypi/eukcc/json](https://pypi.org/pypi/eukcc/json)
Recipe Maintainer(s) | @openpaul

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by visze** [comment]
@BiocondaBot please merge

**Comment by openpaul** [comment]
Hello @visze,
I am the maintainer of this package and noticed commit https://github.com/bioconda/bioconda-recipes/pull/23732/commits/342c9428c911c08bc88bfe03688371810190b823 removes very important dependencies of the package.

There are no tests for it right now, maybe thats why they were called unnecessary, but they are indeed quite essential for the package to work.

How can I flag them as necessary?

Currently installation of a working package will have to be done by:

```
conda install -c bioconda pplacer hmmer eukcc
```
instead of the previous simple

```
conda install -c bioconda eukcc
```

**Comment by visze** [comment]
than you @openpaul for spotting this. I will add them to the recipe. They where not listed in the [setup.py](https://github.com/Finn-Lab/EukCC/blob/master/setup.py) so I thought they are removed. 

If someone approved my PR trhey will be back in: https://github.com/bioconda/bioconda-recipes/pull/23949

**Comment by openpaul** [comment]
Thank you, glad this could be resolved.

**Pull request merged**
