### PR TITLE
add recipe for samtools 0.1.18

### PR DESCRIPTION
**Pull request by pmenzel**
samtools 0.1.18 depends on ncurses5

adding this explicit version recipe, because samtools 0.1.18 is required by srst2

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by pmenzel** [comment]
Help please @dpryan79 @bgruening 

The macos test fails, I see this error message in the middle of the log:
```
07:12:26 BIOCONDA INFO (ERR) Undefined symbols for architecture x86_64:
07:12:26 BIOCONDA INFO (ERR)   "___ks_insertsort_heap", referenced from:
07:12:26 BIOCONDA INFO (ERR)       _ks_combsort_heap in libbam.a(bam_sort.o)
07:12:26 BIOCONDA INFO (ERR)       _ks_introsort_heap in libbam.a(bam_sort.o)
07:12:26 BIOCONDA INFO (ERR) ld: symbol(s) not found for architecture x86_64
07:12:26 BIOCONDA INFO (ERR) clang-9: error: linker command failed with exit code 1 (use -v to see invocation)
07:12:26 BIOCONDA INFO (ERR) make[1]: *** [samtools] Error 1
07:12:26 BIOCONDA INFO (ERR) make: *** [all-recur] Error 1
```
I don't know how it could be fixed.

Maybe we can have just the Linux package? The current package of samtools 0.1.18 is broken, because it misses the specific requirement for libncurses5. This means, that libncurses6 is going to be installed, and samtools cannot run.

**Comment by jmarshall** [comment]
Samtools-0.1.18 does not intrinsically depend on ncurses5; it's just that bioconda's samtools-0.1.18 package was built with that ncurses version. You could if you wished rebuild samtools-0.1.18 against conda-forge's current ncurses.

To build samtools-0.1.18 you would need to apply this fix from eight years ago: samtools/samtools@64275b4bd65b94ae426ba94768b19d198dcb7c97. Or you could likely use samtools-0.1.19 with srst2 — the two are very similar.

However nothing really needs to be rebuilt. You could create a srst2 environment using the existing samtools-0.1.18 package with

```
conda create -n tmpenv srst2 ncurses=5.9
```

**Comment by pmenzel** [comment]
Yes, that's what I did, but I thought it's not so obvious for other users, who wish to install srst2.

Anyway, maybe one could just update the srst2 recipe to require samtools 0.1.19 ?

**Comment by dpryan79** [comment]
I'd much prefer if the srst2 recipe could be updated to use samtools 0.1.19. That's painfully old, but at least not as painfully old as 0.1.18. We also still rebuild 0.1.19 from time to time since there are a number of packages that still depend on it (the joy of packages that are still used but not updated by their authors any more).

**Comment by andersgs** [comment]
Thank you @jmarshall for alerting me to this duplicate. I did not see it before I made my PR. Sorry!

I have fixed the compile issue on MacOSX (#25478). 

@dpryan79 I agree that we should retire srst2, it isn't being maintained.

At the moment, I am fighting technical debt in my public health lab, and need this working so I can continue reporting. I have plans of refactoring the pipeline to drop this dependency. 

Anyway, my PR is ready to go, passing all the checks. 

The issue with compiling on OSX was addressed in samtools (https://github.com/samtools/samtools/issues/22) --- but after the release of 0.1.18. I have added a small patch to the `build.sh` that addresses it. At this point, I don't think there is any harm in continuing to support 0.1.18 for a little while longer.

I would suggest closing this PR, and merging mine.

**Comment by pmenzel** [comment]
Thanks @andersgs for making a working PR for samtools 0.1.18. Then this one here could be closed.

But I don't think srst2 should be retired! I just started to use it (for E.coli OH-typing) and it is referenced by this [paper](https://www.microbiologyresearch.org/content/journal/mgen/10.1099/mgen.0.000064), which uses srst2 to serotype >1000 genomes. 

@andersgs: I am curious for what you use srst2 for?

**Comment by andersgs** [comment]
@jmarshall to power that exact use case. Danielle Ingle worked with us to develop it for our PHL. The main issue we have is with O157 drop-out in assembly-based methods (usually due to low coverage of the O157 allele due to its extreme GC bias). So, we dropped back to reads. 

But, the pipeline could be re-written to not include SRST2 (still on Py2 and dependent on old samtools, and seems to be largely ignored by maintainers at this stage). 

I have started that refactor about 3 times already. But something always comes up. 🥺

**Comment by pmenzel** [comment]
@andersgs I think it is one of the advantages of conda, that one could also easily install old packages (unless a recipe is removed).  

Thanks for the insight about the O157!

While we are it, could I ask you if you also have a tool in your pipeline for determining the E.coli capsule type? So far, I only got to looking for the neu* and kps* gene clusters and assume that I have K1 capsule type if they are present, based on this [paper](https://mbio.asm.org/content/8/5/e01558-17).

**Comment by andersgs** [comment]
I don't. But I would reach out to Danielle. She would know if there is a tool or if someone is developing one. Danielle is an awesome collaborator. You can't go wrong by reaching out to her. We haven't had a need for it yet for our public health response. Although, I suspect that will come.

**Comment by pmenzel** [comment]
Thanks, will do.

So far, the doctors at my lab only ask about K1, but we also have a PCR test for K1 in the lab. Right now, we just cross-validate the info from WGS with the other panel.

**Comment by andersgs** [comment]
@pmenzel I am closing this PR and leaving mine open. If you wish to re-open, please do so.

**Comment by pmenzel** [comment]
Sure, hope your PR gets merged soon.

**Pull request closed without merging**
