### PR TITLE
Add ctseq to bioconda

### PR DESCRIPTION
**Pull request by ryanhmiller**
I would like to add 'ctseq' to bioconda. ctseq is a package that analyzes methylation circulating tumor DNA sequencing data.

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by ryanhmiller** [comment]
@BiocondaBot please add label

**Comment by npavlovikj** [comment]
@BiocondaBot please fetch artifacts

**Comment by npavlovikj** [comment]
@ryanhmiller , do you want to add yourself as a maintainer? That way you will be notified when the bot detects and builds a new version of the package, which I think is useful especially because you are the developer of the package.
If you want to add yourself, please add the following lines at the end in the meta file:
```
extra:
  recipe-maintainers:
    - ryanhmiller
```

The recipe looks good to me, and I already approved it, so you can merge it after you decide if you want to added as a maintainer or not :)

**Comment by ryanhmiller** [comment]
@npavlovikj thank you so much! I didn't know that was even possible. I added myself as a maintainer and pushed the code. Is there anything else I need to do? Sorry, I'm new to all this! Thanks!

**Comment by ryanhmiller** [comment]
Also, I changed the name of the package to be all lowercase ('ctseq'). Hopefully that was okay! Thanks!

**Comment by npavlovikj** [comment]
@BiocondaBot please fetch artifacts

**Comment by npavlovikj** [comment]
@BiocondaBot please merge

**Comment by npavlovikj** [comment]
The recipe looks good @ryanhmiller  - thank you for contributing 🎉

**Pull request merged**
