### PR TITLE
adding vkmz recipe

### PR DESCRIPTION
**Pull request by eslerm**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

Since conda creates an env/info directory I added the README and LICENSE there. Is this compliant with guidelines?

### CODE REVIEW

**Comment by eslerm** [comment]
circleci lint failed with: 
```
recipes/vkmz	should_be_noarch	"{'should_be_noarch': True, 'fix': 'add ""build: noarch"" section'}"	"add ""build: noarch"" section"	True
```
But tool is python3 only and guidelines state: 
>> Update 7 Feb 2018: Previously we had recommended that if the recipe is a pure Python package, it should be marked as a “noarch” package (details). However due to technical incompatibilies we can’t do this – so please DO NOT use "noarch" for now.

**Comment by eslerm** [comment]
A big thanks to @bgruening for helping me write the recipe!

**Comment by bgruening** [comment]
Thanks!

**Comment by marcelotrevisani** [comment]
@bgruening , is it better to use in build section
```
skip: true  # [not py27]
```
or just let
```
python >=3
```
in requirements?

**Comment by bgruening** [comment]
I don't think `skip: true  # [not py27]` will work with noarch pkgs.

**Pull request merged**
