### PR TITLE
Update deepac to 0.10.1

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`deepac`](https://bioconda.github.io/recipes/deepac/README.html): **0.9.3** &rarr; **0.10.1**

[install with bioconda](http://bioconda.github.io/recipes/deepac/README.html) [Conda](https://anaconda.org/bioconda/deepac/files)

Info | Link
-----|-----
Recipe | [`recipes/deepac`](https://github.com//bioconda/bioconda-recipes/tree/bump/deepac/recipes/deepac) (click to view/edit other files)
Releases |[https://pypi.org/pypi/deepac/json](https://pypi.org/pypi/deepac/json)
Recipe Maintainer(s) | @JakubBartoszewicz

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by dpryan79** [comment]
sklearn isn't bringing in openmp for some reason, suggesting that the recipe in conda-forge is broken.

**Comment by JakubBartoszewicz** [comment]
Thanks for the comment! I found some more info about the issue here: https://github.com/scikit-learn/scikit-learn/issues/14485#issuecomment-522218682, here: https://github.com/pytorch/pytorch/issues/2575#issuecomment-523657178 and here: https://github.com/pytorch/pytorch/issues/2575#issuecomment-523667875. It sounds like either (1.) reordering the imports in the source code or (2.) updating linux could help. I'm wondering why standard tests pass and the mulled test fails. What is the OS used in the CI tests?

**Comment by dpryan79** [comment]
The mulled test is a minimal centos (I think) docker container.

**Comment by JakubBartoszewicz** [comment]
Thanks! importing scikit-learn as soon as possible (forcing it to bring openmp in) helped. New release passes the tests.

**Pull request merged**
