### PR TITLE
Update tbl2asn, current copy is expired

### PR DESCRIPTION
**Pull request by npavlovikj**
Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it. Note that if you are not already a member of the bioconda project (meaning that you can't add this label), please ping `@bioconda/core` so that your PR can be reviewed and merged (please note if you'd like to be added to the bioconda project). Please see https://github.com/bioconda/bioconda-recipes/issues/15332 for more details.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by npavlovikj** [comment]
@BiocondaBot recheck

**Comment by npavlovikj** [comment]
The linting fails with `should_be_noarch_generic` and `should_not_be_noarch_source`.

**Comment by npavlovikj** [comment]
Merged in https://github.com/bioconda/bioconda-recipes/pull/16131, closing this.

**Comment by epruesse** [comment]
(WIP - just trying to fix linter)

**Comment by EricDeveaud** [comment]
pactching and buidling tbl2aasn allows to remove the date expiration problem.

```
c6builder:ncbitools/ncbitools-20170106 > cat disable_peremption_date.patch 
--- tbl2asn.c.ori       2019-11-28 16:43:52.679495000 +0100
+++ tbl2asn.c   2019-11-28 16:44:14.523273000 +0100
@@ -8623,10 +8623,10 @@
     return 1;
   }
 
-  if (MoreThanYearOld ()) {
-    too_old = TRUE;
-    Message (MSG_POST, "This copy of tbl2asn is more than a year old.  Please download the current version.");
-  }
+//  if (MoreThanYearOld ()) {
+//    too_old = TRUE;
+//    Message (MSG_POST, "This copy of tbl2asn is more than a year old.  Please download the current version.");
+//  }
 
   /* process command line arguments */
 
@@ -9324,9 +9324,9 @@
     return 1;
   }
 
-  if (too_old) {
-    return 1;
-  }
+//  if (too_old) {
+//    return 1;
+//  }
 
   return 0;
 }
```

NB sequin uses the same mechanism, and ca be patched the same way

**Pull request closed without merging**
