### PR TITLE
plastid: pin pysam version

### LINKED ISSUE #12466: Install of pysamstats results in ValueError: pysam.libchtslib.HTSFile has the wrong size
`conda create -n pysamstats pysamstats`

```
Traceback (most recent call last):
  File "/Genomics/grid/users/lparsons/miniconda3/envs/pysamstats/bin/pysamstats", line 10, in <module>
    import pysamstats
  File "/Genomics/grid/users/lparsons/miniconda3/envs/pysamstats/lib/python3.6/site-packages/pysamstats/__init__.py", line 8, in <module>
    from .pileup import *
  File "/Genomics/grid/users/lparsons/miniconda3/envs/pysamstats/lib/python3.6/site-packages/pysamstats/pileup.py", line 6, in <module>
    import pysamstats.opt as opt
  File "libchtslib.pxd", line 2590, in init pysamstats.opt
ValueError: pysam.libchtslib.HTSFile has the wrong size, try recompiling. Expected 88, got 80
```

```
# packages in environment at /Genomics/grid/users/lparsons/miniconda3/envs/pysamstats:
#
# Name                    Version                   Build  Channel
bcftools                  1.9                  h4da6232_0    bioconda
blas                      1.1                    openblas    conda-forge
blosc                     1.14.4               hfc679d8_0    conda-forge
bzip2                     1.0.6                h470a237_2    conda-forge
ca-certificates           2018.11.29           ha4d7672_0    conda-forge
certifi                   2018.11.29            py36_1000    conda-forge
curl                      7.62.0               h74213dd_0    conda-forge
hdf5                      1.10.3               hc401514_2    conda-forge
htslib                    1.9                  hc238db4_4    bioconda
krb5                      1.16.2               hbb41f41_0    conda-forge
libcurl                   7.62.0               hbdb9355_0    conda-forge
libdeflate                1.0                  h470a237_0    bioconda
libedit                   3.1.20170329         haf1bffa_1    conda-forge
libffi                    3.2.1                hfc679d8_5    conda-forge
libgcc-ng                 7.2.0                hdf63c60_3    conda-forge
libgfortran               3.0.0                         1    conda-forge
libssh2                   1.8.0                h5b517e9_3    conda-forge
libstdcxx-ng              7.2.0                hdf63c60_3    conda-forge
lzo                       2.10                 h470a237_0    conda-forge
ncurses                   6.1                  hfc679d8_1    conda-forge
numexpr                   2.6.8            py36hf8a1672_0    conda-forge
numpy                     1.15.1          py36_blas_openblashd3ea46f_0    conda-forge
openblas                  0.2.20                        8    conda-forge
openssl                   1.0.2p               h470a237_1    conda-forge
pip                       18.1                  py36_1000    conda-forge
pysam                     0.15.1           py36h0380709_0    bioconda
pysamstats                1.0.1            py36ha92aebf_2    bioconda
pytables                  3.4.4            py36h2392372_1    conda-forge
python                    3.6.7                h5001a0f_1    conda-forge
readline                  7.0                  haf1bffa_1    conda-forge
samtools                  1.9                  h8ee4bcc_1    bioconda
setuptools                40.6.2                   py36_0    conda-forge
six                       1.11.0                py36_1001    conda-forge
sqlite                    3.26.0               hb1c47c0_0    conda-forge
tk                        8.6.9                ha92aebf_0    conda-forge
wheel                     0.32.3                   py36_0    conda-forge
xz                        5.2.4                h470a237_1    conda-forge
zlib                      1.2.11               h470a237_3    conda-forge
```

### LINKED ISSUE #12494: Plastid dependency pysam needs to be pinned
After installing `plastid`, I get the following error trying to run `counts_in_region -h`:
```
Traceback (most recent call last):
  File "/home/lparsons/miniconda3/envs/plastid/bin/counts_in_region", line 11, in <module>
    load_entry_point('plastid==0.4.8', 'console_scripts', 'counts_in_region')()
  File "/home/lparsons/miniconda3/envs/plastid/lib/python3.6/site-packages/pkg_resources/__init__.py", line 487, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/lparsons/miniconda3/envs/plastid/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2728, in load_entry_point
    return ep.load()
  File "/home/lparsons/miniconda3/envs/plastid/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2346, in load
    return self.resolve()
  File "/home/lparsons/miniconda3/envs/plastid/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2352, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/lparsons/miniconda3/envs/plastid/lib/python3.6/site-packages/plastid/__init__.py", line 44, in <module>
    from plastid.genomics.genome_array import (BAMGenomeArray,
  File "/home/lparsons/miniconda3/envs/plastid/lib/python3.6/site-packages/plastid/genomics/genome_array.py", line 215, in <module>
    from plastid.genomics.map_factories import *
  File "libchtslib.pxd", line 2590, in init plastid.genomics.map_factories
ValueError: pysam.libchtslib.HTSFile has the wrong size, try recompiling. Expected 88, got 80
```

Potentially need to pin `pysam` in the `run` block using ` - {{ pin_compatible('pysam') }}`. @bgruening Does this work for packages other than numpy? What determines the "compatible" versions?

### LINKED ISSUE #15774: Fresh Plastid install is incompatible with pysam version
It seems that the version of pysam isn't pinned when installing plastid. Since pysam isn't explicitly on this list: https://github.com/bioconda/bioconda-utils/blob/master/bioconda_utils/bioconda_utils-conda_build_config.yaml I'm guessing it won't get pinned automatically. I can think of two ways to handle this:
1. Add pysam to the list of automatically pinned packages
2. Add htslib directly to the dependency list of plastid (and really any other package that lists pysam).

Or perhaps I'm totally off. @bioconda/core any thoughts?

### PR DESCRIPTION
**Pull request by lparsons**
Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it. Note that if you are not already a member of the bioconda project (meaning that you can't add this label), please ping `@bioconda/core` so that your PR can be reviewed and merged (please note if you'd like to be added to the bioconda project). Please see https://github.com/bioconda/bioconda-recipes/issues/15332 for more details.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

Fixes #15774, fixes #12494

### CODE REVIEW

**Comment by dpryan79** [comment]
I built this locally. `counts_in_regions -h` uses 100% of a core without seemingly doing anything.

**Comment by lparsons** [comment]
Hmmm. Something didn't built correctly then, I suppose. A few questions:

1. How did you get it to build locally (it just would skip the build when I tried).
2. How were you able to test the resulting executable?
3. Any thoughts on what is going on? If I can manage the first two things, I can start digging into this a bit, but never hurts to ask...

**Comment by dpryan79** [comment]
If you try your PR locally it should build. That's all I did.

**Comment by lparsons** [comment]
@dpryan79 So, when I run `circleci build` I get this:
```
====>> Testing
  #!/bin/bash -eo pipefail
bioconda-utils build recipes config.yml \
--git-range master HEAD

20:54:53 BIOCONDA INFO Recipes modified according to git: recipes/plastid
20:54:53 BIOCONDA INFO Nothing to be done.
Success!
```
I get the same message using the "bootstrap" method, even when I specify the package.

Further, once that is done, where do I find the resulting install? I'd like to run `counts_in_region -h` and see if I can diagnose the issue.

**Comment by lparsons** [comment]
I've done all that, and no dice. It picks up plastid, but just skips the build. Even with `--force`.

**Comment by lparsons** [comment]
Ok, I still can't build locally, but I have one idea on what the issue might be. The extra long paths in the conda env seem to be causing this section of code to hang: https://github.com/joshuagryphon/plastid/blob/3177d33c3f5e409bebf9aeaaaadddda8c12b9f15/plastid/util/io/openers.py#L251-L255

Need to test further.

**Comment by lparsons** [comment]
Fairly sure this is the issue: https://github.com/joshuagryphon/plastid/issues/29. Replacing that code seems to stop things from hanging. Hopefully we can get a patch.

**Comment by lparsons** [comment]
@dpryan79 and @epruesse I have fixed the hanging tests with a patch (also submitted upstream). Can you take a look an approve if you think this is OK to push out?

**Comment by dpryan79** [comment]
Nicely done @lparsons! If you're sure the patch is doing what it should then :+1: from me!

**Comment by lparsons** [comment]
Fairly sure, it passes the tests in the docs. And the function is just used for pretty prints and debug according to the author. I submitted it upstream as well, so hopefully this can go away in the soon to be released next version.

**Comment by lparsons** [comment]
Given that the old build is basically broken and this seems to work so far, I'm going to merge. Feel free to comment further @epruesse, I don't mean to leave you out, but I have a user who could benefit from this right now.

**Comment by lparsons** [comment]
@dpryan79 or @epruesse It seems that a fresh install of plastid gives me numpy 1.16.4 which doesn't work (due to a bug in plastid). I guess this is because `pin_compatible` has decided 1.16.4 is compatible with the compiled 1.11.3. However, it doesn't actually run due to the fix for  https://github.com/joshuagryphon/plastid/issues/18 not being released... Is there any easy fix (besides adding `numpy<=1.11.3` in addtion to `plastid` when creating the environment?

**Comment by epruesse** [comment]
Nope, no easy fix. :(

This kind of problem is why I've had the bot make the "Packages available for inspection" post for every PR. Using the `conda install ....` line (or the `-c https://.....` part from it in an `env create`), you can check those things before we have a broken package in the repo. Very important to do for things where pinning can be a problem.

You can also look at the repodata.json linked to in the same post. For this package, it says: `numpy >=1.11.3,<2.0a0"`. You can have `pin_compatible` be more restrictive by adding `max_pin='x.x'` - that would have made it `>=1.13,<1.14a0`. Or you can add a pin manually.

Is this package broken then? @bgruening - do we think it's timely enough to just delete the broken package from the channel? (I really want a bioconda/canary label or channel for this reason...)

**Comment by lparsons** [comment]
@epruesse So sorry about this, I'm still sorting out the complexities of pinning. Perhaps I should set `numpy =1.11.3` in both `host` and `run`? Happy to do that, but not sure how to get rid of this build. It's not totally broken, but does require numpy 1.11.3 to work (at least I know that works, not certain if anything below that would, I know 1.12.0 and above has an issue).

**Comment by dpryan79** [comment]
@lparsons Can you try a new PR with a restricted `max_pin`? We need a test that will trigger the issue to ensure this whould work.

@epruesse I'd vote "just delete", since it's going to break for people anyway.

**Comment by lparsons** [comment]
@dpryan79 I'm happy to try using `max_pin`. Will have to look into how to include data files for a test... And will have to come up with some minimal test.

**Comment by lparsons** [comment]
@dpryan79 and @epruesse Testing using `max_pin` and added a test that should fail if incompatible numpy is used: #15861

**Comment by lparsons** [comment]
Getting a `deprecated_numpy_spec` error now... Should I try to skip this lint message? Will be much easier if an updated version is released without this restriction...

**Comment by lparsons** [comment]
OK, I added that `skip_lint` since it seemed appropriate. 

I still can only lint locally, tests are always skipped (for all packages, btw) so I'll have to wait for CircleCI to see if it works. Would love to resolve that, but no idea at the moment.

**Comment by lparsons** [comment]
Looks like everything is working, thanks for the help. Let me know if anything looks amiss to either of you.

**Pull request merged**
