### PR TITLE
Add hail

### LINKED ISSUE #20738: Package request: hail
https://hail.is/

> Hail is an open-source library for scalable data exploration and analysis, with a particular emphasis on genomics. See the overview for a high-level walkthrough of the library, the GWAS tutorial for a simple genomics example, and the installation page to get started using Hail.

### PR DESCRIPTION
**Pull request by raivivek**
Signed-off-by: Vivek Rai <mail@raivivek.in>

Closes #20738

----

> Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences**
      (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).

> Everyone has access to the following BiocondaBot commands, which can be given in a comment:
>
>  * `@BiocondaBot please update` will cause the BiocondaBot to merge the master branch into a PR
>  * `@BiocondaBot please add label` will add the `please review & merge` label.
>  * `@BiocondaBot please fetch artifacts` will post links to packages and docker containers built by the CI system. You can use this to test packages locally before merging.
>
> For members of the Bioconda project, the following command is also available:
>
>  * `@BiocondaBot please merge` will cause packages/containers to be uploaded and a PR merged. Someone must approve a PR first! This has the benefit of not wasting CI build time required by manually merging PRs.
>
> If you have questions, please post them in gitter or ping `@bioconda/core` in a comment (if you are not able to directly ping `@bioconda/core` then the bot will repost your comment and enable pinging).

### CODE REVIEW

**Comment by raivivek** [comment]
@dpryan79 This package's build process unfortunately relies on having `.git` directory inside. However, looks like tarballs do not contain `.git` directory and as a result the build fail. I am not sure what is the best way to proceed here.

**Comment by raivivek** [comment]
@dpryan79 Any idea how long does it take for the conda-forge package (for hurry.filesize that got merged a few days ago) to become installable?

**Comment by dpryan79** [comment]
As far as I can tell staged-recipes is broken.

**Comment by dpryan79** [comment]
This is building on linux now

**Comment by raivivek** [comment]
@dpryan79 Looks ready now!

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Pull request merged**
