### PR TITLE
Add rd-analyzer recipe 

### PR DESCRIPTION
**Pull request by abhi18av**
This PR adds the RD-Analyzer packages for the analysis for deletion regions.

https://github.com/xiaeryu/RD-Analyzer

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by abhi18av** [comment]
@BiocondaBot please fetch artifacts

**Comment by abhi18av** [comment]
@BiocondaBot please add label

**Comment by abhi18av** [comment]
I've tested this locally, with a manual version and the generated artifact.

```
(py2) root@e2e-85-134:~/projects/rdanalyzer_test# tree -f results/
results
├── results/rdAnalyzer
│   ├── results/rdAnalyzer/18HP14.depth
│   └── results/rdAnalyzer/18HP14.result
└── results/rdAnalyzer_old
    ├── results/rdAnalyzer_old/18HP14.depth
    └── results/rdAnalyzer_old/18HP14.result

2 directories, 4 files
(py2) root@e2e-85-134:~/projects/rdanalyzer_test# md5sum results/rdAnalyzer/18HP14.depth
d41d8cd98f00b204e9800998ecf8427e  results/rdAnalyzer/18HP14.depth

(py2) root@e2e-85-134:~/projects/rdanalyzer_test# md5sum results/rdAnalyzer_old/18HP14.depth
d41d8cd98f00b204e9800998ecf8427e  results/rdAnalyzer_old/18HP14.depth

(py2) root@e2e-85-134:~/projects/rdanalyzer_test# md5sum results/rdAnalyzer/18HP14.result
5a45eabaeb1f317cb6034607c54437b4  results/rdAnalyzer/18HP14.result

(py2) root@e2e-85-134:~/projects/rdanalyzer_test# md5sum results/rdAnalyzer_old/18HP14.result
5a45eabaeb1f317cb6034607c54437b4  results/rdAnalyzer_old/18HP14.result
```

**Review by rpetit3 — APPROVED** [review]

**Comment by rpetit3** [comment]
@biocondabot please merge

**Comment by abhi18av** [comment]
Thanks @rpetit3 🙏

**Pull request merged**
