### PR TITLE
R Ada recipe

### PR DESCRIPTION
**Pull request by tetianakh**
* [x] I have read the guidelines above.
* [x] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

This is a recipe for the [R Ada package ](https://cran.r-project.org/web/packages/ada/index.html) that is required by EricScript (the recipe for it is currently on the branch `ericscript_recipe`). There's a conda recipe for this package in a private channel: https://anaconda.org/dranew/r-ada, I've just added it to bioconda.

 @bioconda/core please review.

### CODE REVIEW

**Comment by johanneskoester** [comment]
Can you please clean up the comments? Apart from that, it looks fine.

**Comment by tetianakh** [comment]
@johanneskoester  the comments are cleaned up.

**Comment by johanneskoester** [comment]
Thanks, feel free to merge once the tests pass.

**Comment by johanneskoester** [comment]
@tetianakh did you mean to merge instead of closing?

**Comment by tetianakh** [comment]
Yes! Thank you @johanneskoester,  it's a long day.

**Comment by bgruening** [comment]
Thanks @tetianakh and have a nice evening!

**Pull request merged**
