### PR TITLE
Update recipes/viennarna to version 2.7.0

### PR DESCRIPTION
**Pull request by RaumZeit**
This updates the ViennaRNA Package to upstream release v2.7.0

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

### General instructions

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

### Instructions for avoiding API, ABI, and CLI breakage issues
Conda is able to record and lock (a.k.a. pin) dependency versions used at build time of other recipes.
This way, one can avoid that expectations of a downstream recipe with regards to API, ABI, or CLI are violated by later changes in the recipe.
If not already present in the meta.yaml, make sure to specify `run_exports` (see [here](https://bioconda.github.io/contributor/linting.html#missing-run-exports) for the rationale and comprehensive explanation).
Add a `run_exports` section like this:

```yaml
build:
  run_exports:
    - ...

```

with `...` being one of:

| Case                             | run_exports statement                                               |
| -------------------------------- | ------------------------------------------------------------------- |
| semantic versioning              | `{{ pin_subpackage("myrecipe", max_pin="x") }}`     |
| semantic versioning (0.x.x)      | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}`   |
| known breakage in minor versions | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| known breakage in patch versions | `{{ pin_subpackage("myrecipe", max_pin="x.x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| calendar versioning              | `{{ pin_subpackage("myrecipe", max_pin=None) }}`    |

while replacing `"myrecipe"` with either `name` if a `name|lower` variable is defined in your recipe or with the lowercase name of the package in quotes.

### Bot commands for PR management

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

Note that the <code>@BiocondaBot please merge</code> command is now depreciated. Please just squash and merge instead.

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Review by martin-raden — APPROVED** [review]
Thanks Ronny!

**Comment by martin-raden** [comment]
@RaumZeit seems there is an osx related issue still... 😬

**Comment by RaumZeit** [comment]
> @RaumZeit seems there is an osx related issue still... 😬

I'm aware of that and still try to debug the problem... Running builds for OSX x86_64 and arm64 using github ci didn't reveal any problems.. its only with the conda builds that fail for some Python module import error...

**Comment by RaumZeit** [comment]
> > @RaumZeit seems there is an osx related issue still... 😬
> 
> I'm aware of that and still try to debug the problem... Running builds for OSX x86_64 and arm64 using github ci didn't reveal any problems.. its only with the conda builds that fail for some Python module import error...

Seems the problem was in some strange code signing issue on Mac OS X. The Makefile for the Python interface would copy a shared library that is create by libtool and then use the copy to generate compiled Python modules (.pyc). However, the use of `cp` under Mac OS X destroyed the validity of the copy, thus Python was not able to load the shared library. The solution was to use the `ditto` tool instead of `cp`, which properly updates all required stuff for validating the file under Mac OS X. 
Seems strange to me, but does work. Interestingly, this problem doesn't occur with arm64 builds for Mac OS X, so it's probably a bug in macos-13.

Anyhow, as soon as the final checks went through, I'll request the merge...

**Comment by RaumZeit** [comment]
Dunno what is happening with circleCI all the time... The osx builds are failing at random stages and raw logs are unusable since error messages are all over the place, even in `./configure` output, but not at the places where the error actually occurred. The last run even shows no clue at all why the build did not went through. It went straight to the tests without any compilation output and then failed with missing executable programs... 

I'll force-push once again, just to trigger the build yet another time...

**Comment by mencian** [comment]
Many thanks for the heavy lifting @RaumZeit!

**Comment by martin-g** [comment]
> Dunno what is happening with circleCI all the time... The osx builds are failing at random stages and raw logs are unusable since error messages are all over the place, even in `./configure` output, but not at the places where the error actually occurred.

This is caused by 'make -j' (parallel build). 
The benefit of '-j' is speed.

**Pull request merged**
