### PR TITLE
Update malva to 1.3.0

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`malva`](https://bioconda.github.io/recipes/malva/README.html): **1.2.0** &rarr; **1.3.0**

[install with bioconda](http://bioconda.github.io/recipes/malva/README.html) [Conda](https://anaconda.org/bioconda/malva/files)

Info | Link
-----|-----
Recipe | [`recipes/malva`](https://github.com//bioconda/bioconda-recipes/tree/bump/malva/recipes/malva) (click to view/edit other files)
Releases |[https://github.com/AlgoLab/malva/tags](https://github.com/AlgoLab/malva/tags)
Author | `@AlgoLab`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by ldenti** [comment]
Hi @bioconda/core, since I changed one of the file, do I need to increase the build number?

**Comment by dpryan79** [comment]
No, the version has already been increased, so the build number should stay at 0, as it'll be the first build of that version.

**Comment by ldenti** [comment]
Ok, so can I review and merge? Or do I have to wait for someone else to review my changes?

**Comment by dpryan79** [comment]
You can review and merge yourself

**Pull request merged**
