### PR TITLE
Add r-netcomi

### PR DESCRIPTION
**Pull request by daydream-boost**
NetCoMi (Network Construction and Comparison for Microbiome Data) provides functionality for constructing, analyzing, and comparing networks suitable for the application on microbial compositional data. The R package implements the workflow proposed in

Stefanie Peschel, Christian L Müller, Erika von Mutius, Anne-Laure Boulesteix, Martin Depner (2020). [NetCoMi: network construction and comparison for microbiome data in R](https://academic.oup.com/bib/advance-article/doi/10.1093/bib/bbaa290/6017455). Briefings in Bioinformatics, bbaa290.

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by daydream-boost** [comment]
@BiocondaBot please add label

**Comment by daydream-boost** [comment]
@BiocondaBot please fetch artifacts

**Review by mfansler — COMMENTED** [review]
This looks good. However, testing the artifact on **osx-64** platform, I get a DLL error for `mixedCCA`:

```r
> library(NetCoMi)
Loading required package: SpiecEasi
Error: package or namespace load failed for ‘NetCoMi’ in library.dynam(lib, package, package.lib):
 shared object ‘mixedCCA.dylib’ not found
```

Examining the `mixedCCA` package (from bioconda) shows it was build with `noarch`, which doesn't seem correct, since it clearly uses `Rcpp` and compiles code. Consequently, the tarball delivers a Linux-specific `mixedCCA.so` dynamic library that is non-functional on **osx-64**.

I would suggest we hold off on approving this build recipe addition until the `mixedCCA` package is getting correctly built.

**Comment by dpryan79** [comment]
I've removed the faulty r-mixedcca and merged in proper platform-specific packages instead.

**Review by mfansler — APPROVED** [review]
@dpryan79 with the new `r-mixedcca` build, I can confirm the **noarch** artifact for this package is functional on **osx-64**. Seems good to go.

**Comment by dpryan79** [comment]
@BiocondaBot please merge

THanks for confirming @mfansler !

**Pull request merged**
