### PR TITLE
Update mosdepth to 0.2.6

### PR DESCRIPTION
**Pull request by epruesse**
Update [`mosdepth`](https://bioconda.github.io/recipes/mosdepth/README.html): **0.2.5** &rarr; **0.2.6**

[install with bioconda](http://bioconda.github.io/recipes/mosdepth/README.html) [Conda](https://anaconda.org/bioconda/mosdepth/files)

Info | Link
-----|-----
Recipe | [`recipes/mosdepth`](https://github.com//bioconda/bioconda-recipes/tree/bump/mosdepth/recipes/mosdepth) (click to view/edit other files)
Releases |[https://github.com/brentp/mosdepth/tags](https://github.com/brentp/mosdepth/tags)
Author | @brentp
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by dpryan79** [comment]
@brentp Any clue how to inject the `${CC}` compiler later in the build process where this is failing?

**Comment by brentp** [comment]
I had a look but I have no idea. You can see the recipe is the same except for the version, but now it fails. I would just get that static release and avoid the whole build process.

**Comment by dpryan79** [comment]
Path of least resistance it is then :)

**Comment by dpryan79** [comment]
@brentp FYI, when I get nim to compile I run into [the following problem](https://circleci.com/gh/bioconda/bioconda-recipes/58372):

    mosdepth.nim(366, 18) Error: type mismatch: got <coverage_t, uint32>

When I instead download the static binary it segfaults in the docker container (I'm not sure why, it works perfectly fine locally on ubuntu). Any clue what's going on with the type mismatch? That's probably easier to get around than an odd interaction with the docker container.

**Comment by epruesse** [comment]
@biocondabot lint

**Comment by brentp** [comment]
hi, sorry of the delay, i didn't get notification of this. could someone retry the recipe that gets the static binary? I updated it after some upstream changes.

**Comment by dpryan79** [comment]
@bioconda-bot update

**Comment by dpryan79** [comment]
dammit bot...

**Pull request closed without merging**
