### PR TITLE
Add recipe for HISAT2 2.2.0

### PR DESCRIPTION
**Pull request by npavlovikj**
**Replace this sentence with a detailed description of your pull request**

----

> Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences**
      (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

> Everyone has access to the following BiocondaBot commands, which can be given in a comment:
>
>  * `@BiocondaBot please update` will cause the BiocondaBot to merge the master branch into a PR
>  * `@BiocondaBot please add label` will add the `please review & merge` label.
>  * `@BiocondaBot please fetch artifacts` will post links to packages and docker containers built by the CI system. You can use this to test packages locally before merging.
>
> For members of the Bioconda project, the following command is also available:
>
>  * `@BiocondaBot please merge` will cause packages/containers to be uploaded and a PR merged. Someone must approve a PR first! This has the benefit of not wasting CI build time required by manually merging PRs.
>
> If you have questions, please post them in gitter or ping `@bioconda/core` in a comment (if you are not able to directly ping `@bioconda/core` then the bot will repost your comment and enable pinging).

### CODE REVIEW

**Comment by npavlovikj** [comment]
@bioconda/core, is Python 2.7 support removed from the build system? Using `skip: True  # [py3k]` results in not building the recipe (_Skipped: hisat2 from /home/fedora/bioconda-recipes/recipes/hisat2 defines build/skip for this configuration ({'c_compiler': 'gcc', 'cxx_compiler': 'gxx'})._).

HISAT2 has few Python scripts that are only 2.7 compatible. The previous recipe used 2to3, so should I use that instead too?

**Comment by dpryan79** [comment]
It should still be in there. We recently had to update the version of conda-build that we use since conda-forge changed how python packages work, but that's it.

**Comment by dpryan79** [comment]
Since python is neither in the `build` nor the `host` section, the `skip` is going to cause problems.

**Comment by npavlovikj** [comment]
@BiocondaBot please fetch artifacts

**Comment by npavlovikj** [comment]
@dpryan79 , thank you so much for looking into this recipe - I really appreciate your reply and modifications!

I slightly modified `build.sh` in order for the recipe to pass - does it look ok to you now?

**Comment by dpryan79** [comment]
@bioconda-bot please merge

Thanks @npavlovikj!

**Pull request merged**
