### PR TITLE
Fix MashMap v3.1.3 build.

### LINKED ISSUE #52321: MashMap 3.1.3 broken
I've had some issues installing verkko w/mamba due to it including mashmap w/out proper dependencies. When I run mashmap it reports a missing libblis. This was broken by the recent pull request here: https://github.com/bioconda/bioconda-recipes/pull/51161. So a released version was broken months after release by maintenance updates, this should not be allowed in the middle of a version.

Downloading mashmap v3.1.3 build1 from here: https://anaconda.org/bioconda/mashmap/files confirms it has been linked against the blis library.
```
        linux-vdso.so.1 (0x00007ffda41c5000)
        /usr/local/Anaconda/envs/py3.10/lib/libbz2.so.1 (0x00001549c865f000)
        libgsl.so.25 => not found
        libblis.so.4 => not found
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00001549c8289000)
        libz.so.1 => /lib64/libz.so.1 (0x00001549c8071000)
        libhts.so.3 => /usr/local/apps/samtools/1.21/lib/libhts.so.3 (0x00001549c854a000)
        libstdc++.so.6 => /usr/local/GCC/11.3.0/lib64/libstdc++.so.6 (0x00001549c7e59000)
        libm.so.6 => /lib64/libm.so.6 (0x00001549c7ad7000)
        libgcc_s.so.1 => /usr/local/GCC/11.3.0/lib64/libgcc_s.so.1 (0x00001549c8530000) 
        libc.so.6 => /lib64/libc.so.6 (0x00001549c7701000)
        /lib64/ld-linux-x86-64.so.2 (0x00001549c84a9000)
        liblzma.so.5 => /lib64/liblzma.so.5 (0x00001549c74da000)
        libbz2.so.1 => /lib64/libbz2.so.1 (0x00001549c72c9000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00001549c70c5000)
```

However, all the dependencies list libblas not libblis in the yaml: https://github.com/bioconda/bioconda-recipes/blob/acd1b4a72758b923229a1bd366f43ac5c0812a7f/recipes/mashmap/meta.yaml#L2. Version 3.1.3 build0 is also linked against libblas, as expected:
```
        linux-vdso.so.1 (0x00007ffd4b7ae000)
        /usr/local/Anaconda/envs/py3.10/lib/libbz2.so.1 (0x0000153e69ff9000)
        libgsl.so.25 => /usr/local/gsl/2.7/gcc-11.3.0/lib/libgsl.so.25 (0x0000153e69b75000)
        libopenblas.so.0 => /usr/local/OpenBLAS/0.3.20/gcc-11.3.0/lib/libopenblas.so.0 (0x0000153e68e6c000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x0000153e68c4c000)
        libz.so.1 => /lib64/libz.so.1 (0x0000153e68a34000)
        libhts.so.3 => /usr/local/apps/samtools/1.21/lib/libhts.so.3 (0x0000153e69ee4000)
        libstdc++.so.6 => /usr/local/GCC/11.3.0/lib64/libstdc++.so.6 (0x0000153e6881c000)
        libm.so.6 => /lib64/libm.so.6 (0x0000153e6849a000)
        libgcc_s.so.1 => /usr/local/GCC/11.3.0/lib64/libgcc_s.so.1 (0x0000153e69eca000)
        libc.so.6 => /lib64/libc.so.6 (0x0000153e680c4000)
        libgfortran.so.5 => /usr/local/GCC/11.3.0/lib64/libgfortran.so.5 (0x0000153e67e14000)
        /lib64/ld-linux-x86-64.so.2 (0x0000153e69e42000)
        liblzma.so.5 => /lib64/liblzma.so.5 (0x0000153e67bed000)
        libbz2.so.1 => /lib64/libbz2.so.1 (0x0000153e679dc000)
        libdl.so.2 => /lib64/libdl.so.2 (0x0000153e677d8000)
        libquadmath.so.0 => /usr/local/GCC/11.3.0/lib/../lib64/libquadmath.so.0 (0x0000153e69e7f000)
```

### PR DESCRIPTION
**Pull request by bkille**
The most recent build of MashMap v3.1.3 (PR #51161) is broken due to it being linked against BLIS instead of BLAS (issue #52321). It also appears that the GSL shared library is also missing according to the output in #52321, even though it is present in the recipe as a host and run dependency.

I don't know what caused this, but I'm going to rebuild and see if I run into the same issue.

Fixes #52321.

### CODE REVIEW

**Comment by bkille** [comment]
@mencian thanks for improving the `meta.yaml` and helping out with the OSX build. It seems that even though the OSX SDK is specified as 10.15 (or even 11.0), the CI container always [downloads the 10.13 version](https://github.com/bioconda/bioconda-recipes/actions/runs/12062066964/job/33635392250?pr=52373#step:7:28):
```
Downloading 10.13 sdk
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

100 25.2M  100 25.2M    0     0  [36](https://github.com/bioconda/bioconda-recipes/actions/runs/12062066964/job/33635392250?pr=52373#step:7:37).3M      0 --:--:-- --:--:-- --:--:-- 36.3M
MacOSX10.13.sdk.tar.xz: OK
Found CONDA_BUILD_SYSROOT: /Applications/Xcode_15.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk
``` 

Is there another way to specify which OSX SDK to use? Thanks again for your help!

**Comment by martin-g** [comment]
See https://github.com/bioconda/bioconda-recipes/blob/d237bfb190044196088deb0a543ef9966e95be6a/recipes/piscem/conda_build_config.yaml#L1-L4 for example

**Comment by mencian** [comment]
@BiocondaBot please fetch artifacts

**Comment by mencian** [comment]
@bkille I've bumped the OSX SDK to `10.15` and that seems to have done the trick. Please take a look at the built artifacts to see if `BLAS` is correctly linked.

**Review by mencian — APPROVED** [review]

**Pull request merged**
