### PR TITLE
Updated minimum Python version required

### PR DESCRIPTION
**Pull request by fbeghini**

### CODE REVIEW

**Comment by fbeghini** [comment]
@bioconda-bot rebuild

**Comment by fbeghini** [comment]
@bioconda-bot please rebuild

**Comment by fbeghini** [comment]
@bioconda-bot recheck

**Comment by fbeghini** [comment]
@bioconda-bot rebuild

**Comment by fbeghini** [comment]
@BiocondaBot rebuild

**Comment by fbeghini** [comment]
@biocondabot rebuild

**Comment by fbeghini** [comment]
@biocondabot please add label

**Comment by dpryan79** [comment]
@bioconda-bot please fetch artifacts

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Pull request merged**
