### PR TITLE
update build.sh for QuantWiz_IQ

### PR DESCRIPTION
**Pull request by pravs3683**
Adding escape "\" character to fix short wrapper part in recipe

**Replace this sentence with a detailed description of your pull request**

----

> Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it.

* [ X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [ ] This PR adds a new recipe.
* [ X] AFAIK, this recipe **is directly relevant to the biological sciences**
      (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

> Everyone has access to the following BiocondaBot commands, which can be given in a comment:
>
>  * `@BiocondaBot please update` will cause the BiocondaBot to merge the master branch into a PR
>  * `@BiocondaBot please add label` will add the `please review & merge` label.
>  * `@BiocondaBot please fetch artifacts` will post links to packages and docker containers built by the CI system. You can use this to test packages locally before merging.
>
> For members of the Bioconda project, the following command is also available:
>
>  * `@BiocondaBot please merge` will cause packages/containers to be uploaded and a PR merged. Someone must approve a PR first! This has the benefit of not wasting CI build time required by manually merging PRs.
>
> If you have questions, please post them in gitter or ping `@bioconda/core` in a comment (if you are not able to directly ping `@bioconda/core` then the bot will repost your comment and enable pinging).

### CODE REVIEW

**Comment by pravs3683** [comment]
@BiocondaBot please update

**Comment by mbargull** [comment]
> I encountered an error updating your PR branch. You can report this to bioconda/core if you'd like.
> -The Bot

Failed with: https://github.com/bioconda/bioconda-recipes/commit/7e49c223dbcf2737533de3518724e53632778d59/checks?check_suite_id=402686325#step:3:463
```
git push
To github.com:pravs3683/bioconda-recipes.git
 ! [remote rejected]     fix_quantwiq-iq -> fix_quantwiq-iq (permission denied)
error: failed to push some refs to 'git@github.com:pravs3683/bioconda-recipes.git'
the response code was 201
##[error]Node run failed with exit code 1
```
since the PR does not allow edit from maintainers.

**Comment by mbargull** [comment]
@BiocondaBot please fetch artifacts

**Comment by mbargull** [comment]
@BiocondaBot please merge

**Pull request merged**
