### PR TITLE
Update scallop to 0.10.5

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`scallop`](https://bioconda.github.io/recipes/scallop/README.html): **0.10.4** &rarr; **0.10.5**

[install with bioconda](http://bioconda.github.io/recipes/scallop/README.html) [Conda](https://anaconda.org/bioconda/scallop/files)

Info | Link
-----|-----
Recipe | [`recipes/scallop`](https://github.com//bioconda/bioconda-recipes/tree/bump/scallop/recipes/scallop) (click to view/edit other files)
Releases |[https://github.com/Kingsford-Group/scallop/releases](https://github.com/Kingsford-Group/scallop/releases)
Recipe Maintainer(s) | @shaomingfu
Author | `@Kingsford-Group`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by shaomingfu** [comment]
@BiocondaBot please add label

**Comment by shaomingfu** [comment]
@dpryan79 @bioconda/core 

Could you review? Thanks!

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Comment by shaomingfu** [comment]
Thanks @dpryan79 !

**Pull request merged**
