### PR TITLE
[FEATURE] Restructure Openms related recipes

### PR DESCRIPTION
**Pull request by jpfeuffer**
This splits openms related packages into subpackages including pyopenms which would then be superseded by this metarecipe.

While fixing this recipe I added the fixes to OpenMS' develop whenever possible, so after the next release it should be much easier to build OpenMS with conda. We still might need one or two patches for pyopenms, such that e.g. the sysroot is picked up (if I find time, I will implement something to pass on the additional CMake variables)

Things to do:
- I don't know why conda still complains about missing specification of dependencies. It seems like the subpackages do not really pick up the run_exports from libopenms
- the pyopenms pip wheel still packages all dependencies, since this is what we want to have in the wheel usually. Of course this is not optimal for conda, since it occupies additional space and it is hard to check which dependency is actually used by the python C++ extension. The same holds for the share and example data (which is duplicated).
-------------------

Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it.

* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [X] This PR adds a new recipe.
* [X] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [X] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

 * `@BiocondaBot please update` will cause the BiocondaBot to merge the master branch into a PR
 * `@BiocondaBot please add label` will add the `please review & merge` label.
 * `@BiocondaBot please fetch artifacts` will post links to packages and docker containers built by the CI system. You can use this to test packages locally before merging.

For members of the Bioconda project, the following command is also available:

 * `@BiocondaBot please merge` will cause packages/containers to be uploaded and a PR merged. Someone must approve a PR first! This has the benefit of not wasting CI build time required by manually merging PRs.

If you have questions, please post them in gitter or ping `@bioconda/core` in a comment (if you are not able to directly ping `@bioconda/core` then the bot will repost your comment and enable pinging).

### CODE REVIEW

**Comment by jpfeuffer** [comment]
Possible TODOs here or in future PRs:
- Activate multiple python versions
- Check if pyopenms uses the correct libraries and installs correctly
- Add GUI tools (we will probably need to work around [this](https://github.com/ContinuumIO/anaconda-issues/issues/8779) )
- Split lib to lib and lib-devel (headers)
- Add docu subpackage

**Comment by jpfeuffer** [comment]
supersedes #18776
related to #18701 
fixes #19200

**Comment by jpfeuffer** [comment]
What does conda do for so long after the build??

**Comment by jpfeuffer** [comment]
@BiocondaBot please add label

**Comment by dpryan79** [comment]
The explicit `run_exports` probably aren't needed, but they also won't hurt anything. I removed some excess `{{ python }}` (python is always pinned) and will merge once the CI is green.

**Comment by dpryan79** [comment]
@bioconda-bot please merge

@jpfeuffer Thanks for the huge amount of work that this must have taken!

**Comment by jpfeuffer** [comment]
Quick follow-up on the python version:
So bioconda always uses one specific version of python only?
I added the variable to be able to "quickly" generate multiple versions of pyopenms though the
recipe based conda_build_config.yaml

**Comment by dpryan79** [comment]
At the moment bioconda is building against 3 different python versions (2.7, 3.6 and 3.7). I hadn't noticed the conda_build_config, we can get rid of that and specify only building against python 3.6 in case pyopenms doesn't work with 3.7.

**Comment by jpfeuffer** [comment]
Okay, no I just wanted to leave the option open. It _should_ work with any. But it is also pretty heavy on the build time, that is why I did only one version for now.

**Comment by dpryan79** [comment]
Yeah, the build time is a very good thing to keep in mind. We're limited to ~5 hours at the moment, so we can probably still swing 2 python builds. I'll try to remember to do this once our current OSX CI issues are fixed.

**Pull request merged**
