### PR TITLE
Update planemo to 0.70.0

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`planemo`](https://bioconda.github.io/recipes/planemo/README.html): **0.62.1** &rarr; **0.70.0**

[install with bioconda](http://bioconda.github.io/recipes/planemo/README.html) [Conda](https://anaconda.org/bioconda/planemo/files)

Info | Link
-----|-----
Recipe | [`recipes/planemo`](https://github.com//bioconda/bioconda-recipes/tree/bump/planemo/recipes/planemo) (click to view/edit other files)
Releases |[https://pypi.org/pypi/planemo/json](https://pypi.org/pypi/planemo/json)

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by dfornika** [comment]
Build appears to be failing with this error:

```
file planemo/cwl/run.py
from galaxy.tool_util.cwl.cwltool_deps import (
ModuleNotFoundError: No module named 'galaxy.tool_util'
```

**Comment by dpryan79** [comment]
@bioconda-bot please update

**Comment by dpryan79** [comment]
Needs a bump of ephemeris

**Comment by dpryan79** [comment]
Xref: https://github.com/bioconda/bioconda-recipes/pull/16466

**Comment by dpryan79** [comment]
@bioconda-bot please fetch artifacts

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Pull request merged**
