### PR TITLE
Add Recontig version 1.1.1

### PR DESCRIPTION
**Pull request by charlesgregory**
Describe your pull request here

[recontig](https://github.com/blachlylab/recontig) is a D program and python package that provides fast conversion of contig names between naming conventions for GFF, VCF/BCF, SAM/BAM, and BED files. recontig is written in D and relies on the D package [dhtslib](https://github.com/blachlylab/dhtslib) - a collection of wrappers and bindings of [htslib](https://github.com/samtools/htslib) for the D language. recontig utilizes the power and speed of dhtslib/htslib to convert contig names for .vcf/.bcf, .bam/.sam, .gff2/.gff3, and .bed file types. Headers and records are modified properly to specification with support for files compressed with bgzip, gzip, or remote files via http(s) or amazon s3. Mapping files used for conversion can be created from two fasta files or automatically downloaded by recontig from @dpryan79 's [ChromosomeMappings](https://github.com/dpryan79/ChromosomeMappings) repo. We would like to make our program easily distributed via bioconda.

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by dpryan79** [comment]
FYI, I've made a couple small tweaks, though they won't fix the OSX build error (I don't know what's causing that). Please note that we compile against a single version of htslib (currently 1.12) and compiled code mixes poorly with specifying python restrictions. I've added an appropriate "skip" entry in the build section to avoid any future issues due to this. If you happen to be the developer of recontig, though, could you consider supporting python 3 in the future? Python 2 is unfortunately past its end-of-life and will get dropped completely at some point I expect.

As an aside, thanks for pointing out that dhtslib exists, I never knew of that project!

**Comment by charlesgregory** [comment]
I am the developer of recontig. It does support python 3, though I have had trouble getting it to build correctly due to the python extension/pyd relying on libpython2.7. Though I think I have that solved now (I will push some changes). As for the osx error, I have run across it before. I think it is due to python extension linking to the wrong python shared library. I will continue to work on that as we want osx support.

I am also a developer for dhtslib and we have used it for quite a few internal projects. We are currently trying to get it out there for other developers to use. D is an awesome language, though not very popular.

**Comment by charlesgregory** [comment]
@BiocondaBot please add label

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Pull request merged**
