### PR TITLE
Update quantms-utils to 0.0.4

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`quantms-utils`](https://bioconda.github.io/recipes/quantms-utils/README.html): **0.0.3** &rarr; **0.0.4**

[install with bioconda](http://bioconda.github.io/recipes/quantms-utils/README.html) [Conda](https://anaconda.org/bioconda/quantms-utils/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/quantms-utils`](https://github.com//bioconda/bioconda-recipes/tree/bump/quantms_utils/recipes/quantms-utils) (click to view/edit other files)
Summary | Python package with scripts and helpers for the quantms workflow
Home | [https://www.github.com/bigbio/quantms-utils](https://www.github.com/bigbio/quantms-utils)
Releases |[https://pypi.org/pypi/quantms_utils/json](https://pypi.org/pypi/quantms_utils/json)
Recipe Maintainer(s) | @ypriverol

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Review by ypriverol — APPROVED** [review]

**Comment by ypriverol** [comment]
@bgruening the singularity image din't build.

**Comment by bgruening** [comment]
[quantms-utils](https://depot.galaxyproject.org/singularity/quantms-utils%3A0.0.2--pyhdfd78af_0) is I guess what you mean?

**Comment by ypriverol** [comment]
done. Thanks @bgruening

**Comment by ypriverol** [comment]
@bgruening quick question, in the package's dependencies, I made the mistake of not forcing the versions (define the actual version of the dependencies). It is better that way (no defining it), but now the container fails :(. If I modified the recipe and try to build again the package and containers, it will override them in conda, biocontainers and singularity or do I need to update the version in the recipe.

**Pull request merged**
