### PR TITLE
bump unicycler

### PR DESCRIPTION
**Pull request by PertuyF**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

@bioconda/core could someone review this please?

### CODE REVIEW

**Comment by PertuyF** [comment]
Oups, missed that one, sorry!

**Comment by bgruening** [comment]
@PertuyF no problem. I'm sure @corburn welcomes some help with that :)

**Comment by corburn** [comment]
@bgruening yes, I haven't forgotten about all the pull request I still have open :)

**Comment by bgruening** [comment]
I can imagine. Thanks for your wonderful work! If you are in Germany at some point drop by for tons of beer or juice :)

**Comment by PertuyF** [comment]
And thanks for your work!
I'm willing to help here, so if you have something in mind I could do @corburn , just tell :)

**Comment by corburn** [comment]
@PertuyF I know:

- unicycler builds on my local machine outside the bioconda-utils environment
- from the errors unicycler needs gcc >4.9.1
- from the logs the conda_build_config.yaml I added it is now building with gcc 7.2.0

I'm familiar with the basics of C++, but not enough to glance at the error log and immediately know how to solve [these errors](https://circleci.com/gh/bioconda/bioconda-recipes/23026?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link):

```
unicycler/include/seqan/system/file_sync.h: In member function 'bool seqan::File<seqan::Sync<TSpec> >::openTemp(int)':
    unicycler/include/seqan/system/file_sync.h:337:25: error: call of overloaded 'empty(std::__cxx11::string&)' is ambiguous
             if (empty(tmpDir))
```

On my task list is to learn more about the error and follow the stack-trace to see if it can be resolved with a recipe patch or gcc flag.

**Pull request closed without merging**
