### PR TITLE
Openms no examples

### PR DESCRIPTION
**Pull request by jvolkening**
OpenMS packages ~ 120 MB of example files. These files roughly triple the installed size for the libopenms package and appear to conflict with the Bioconda [guidelines](https://bioconda.github.io/contributor/guidelines.html#tests). This PR prevents copying of the `examples` directory when the `share` directory is copied.

----

> Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences**
      (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

> Everyone has access to the following BiocondaBot commands, which can be given in a comment:
>
>  * `@BiocondaBot please update` will cause the BiocondaBot to merge the master branch into a PR
>  * `@BiocondaBot please add label` will add the `please review & merge` label.
>  * `@BiocondaBot please fetch artifacts` will post links to packages and docker containers built by the CI system. You can use this to test packages locally before merging.
>
> For members of the Bioconda project, the following command is also available:
>
>  * `@BiocondaBot please merge` will cause packages/containers to be uploaded and a PR merged. Someone must approve a PR first! This has the benefit of not wasting CI build time required by manually merging PRs.
>
> If you have questions, please post them in gitter or ping `@bioconda/core` in a comment (if you are not able to directly ping `@bioconda/core` then the bot will repost your comment and enable pinging).

### CODE REVIEW

**Comment by jvolkening** [comment]
Not sure what to do with the failed linting...
```
build_number_needs_reset: The recipe build number should be reset to 0.
```
Self-explanatory...except I didn't change anything with the package version, only a few lines of the packaging code and thus bumped the build number. Also get
```
cython_needs_compiler: Cython generates C code, which will need to be compiled
```
but the recipe already contained the build dependency `{{ compiler('cxx') }}` (I didn't touch this part).

**Comment by jvolkening** [comment]
@BiocondaBot please update

**Comment by jvolkening** [comment]
@bioconda/core ?

**Comment by bernt-matthias** [comment]
Good idea to remove the test data.

Btw. two of the java thirdparty packages have problems with java 11:

https://github.com/dfermin/lucXor/issues/4
https://github.com/MSGFPlus/msgfplus/issues/95

**Comment by jvolkening** [comment]
@bernt-matthias Any clue on the linting issues here?

**Comment by bernt-matthias** [comment]
No idea. Maybe you can ask on the bioconda gitter channel.

**Comment by bernt-matthias** [comment]
Maybe another papercut that might be solved within this PR: 

The text shown with `--help` is currently 

```
Version: 2.5.0-HEAD-HASH-NOTFOUND-HEAD-HASH-NOTFOUND Feb 24 2020, 19:18:56, Revision: HEAD-HASH-NOTFOUND
```

Maybe this should be fixed to just 2.5.0? Or add the missing hash?

Apart from this the PR looks good to me. Lets just make sure that the examples are really excluded from the package. 

@BiocondaBot please fetch artifacts

**Comment by bgruening** [comment]
> Maybe another papercut that might be solved within this PR:
> 
> The text shown with `--help` is currently
> 
> ```
> Version: 2.5.0-HEAD-HASH-NOTFOUND-HEAD-HASH-NOTFOUND Feb 24 2020, 19:18:56, Revision: HEAD-HASH-NOTFOUND
> ```
> 
> Maybe this should be fixed to just 2.5.0? Or add the missing hash?
> 
> Apart from this the PR looks good to me. Lets just make sure that the examples are really excluded from the package.
> 
> @BiocondaBot please fetch artifacts

@jpfeuffer I guess this need to be patched in the OpenMS codebase and should not block this pR?

**Comment by bgruening** [comment]
@BiocondaBot please fetch artifacts

**Comment by bernt-matthias** [comment]
Looks good 

- libopenms is 12MB
- openms is 5MB
- pyopenms is 7MB

Lets wait for feedback from @jvolkening or @jpfeuffer

**Comment by bgruening** [comment]
Feel free to merge as you like ...

Thanks all!
I can remove the build 0 is this is needed.

**Comment by jpfeuffer** [comment]
Hmm right, yes I need to look into this on the OpenMS side.
Explanation: The release tar.gz does not include the git directory.
Short solution is to disable -DGIT_TRACKING=OFF
But then it adds "-disabled". So this needs more time.

**Comment by bernt-matthias** [comment]
OK. So feel free to merge or tell us to do so.

**Comment by jpfeuffer** [comment]
@BiocondaBot please merge

**Comment by jvolkening** [comment]
Thanks for figuring out the details.

**Pull request merged**
