### PR TITLE
Fix Bioconductor data packages

### PR DESCRIPTION
**Pull request by jdblischak**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [ ] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

@bgruening As you [suggested](https://github.com/bioconda/bioconda-utils/issues/235#issuecomment-352267610), I've rebuilt all the Bioconductor data packages and submitted them to the bulk branch. I also merged in "master", so you'll want to focus on the most recent commits https://github.com/bioconda/bioconda-recipes/commit/80cf102de46af92a974b1cdabea9fde4d8661780 and https://github.com/bioconda/bioconda-recipes/pull/7116/commits/83b59374418d2371f1cca10ea37c43a587886e34

### CODE REVIEW

**Comment by bgruening** [comment]
Took me a while to read through it, looks good to me. Lets merge it.

**Comment by jdblischak** [comment]
Thanks @bgruening for taking care of this! It appears that all the packages have been built on the "bulk" branch. The macOS build passed and the Linux build failed due to non-Bioconductor packages:

https://travis-ci.org/bioconda/bioconda-recipes/jobs/318719223#L700

What's the next step? Are you now going to merge "bulk" into "master"?

**Comment by bgruening** [comment]
@jdblischak @daler I merged bulk into master. Everything should be updated now.

**Comment by jdblischak** [comment]
Awesome! Thanks so much @bgruening!

**Pull request merged**
