### PR TITLE
 Add trtools to bioconda

### PR DESCRIPTION
**Pull request by LiterallyUniqueLogin**
Adding a new recipe and package to bioconda. Trtools is a tool that allows for analysis of genomic tandem repeat data regardless of which tandem repeat caller (HipSTR, PopSTR, GangSTR, AdVNTR or ExpansionHunter) generated the data. Creating a new pull request instead of [this](https://github.com/bioconda/bioconda-recipes/pull/22387) old one, hopefully that fixes the caching issues I was having with the CircleCI build.

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by LiterallyUniqueLogin** [comment]
I need help debugging the issue that's causing the CircleCI tests to fail. Basically, my tests pass the first time on the the configured Docker container, but then the mulled-build fails.

The mulled-build fails because my script doesn't have access to git (it uses git to download files needed for a few of the tests). However, my recipe specifically declares a dependency on git in the test.requires section of meta.yaml. Is this a bug with mulled-build, or an issue with my meta.yaml?

Thanks for any help!

**Comment by LiterallyUniqueLogin** [comment]
Response from dpryan79 on the gitter: 
The mulled test ignores the requires: section since the point of it is to test that only the package and its run time dependencies are really needed. The normal way we handle this is to put tests with extra requirements in a run_test.sh file. Since that's not installed with the package it's then not run in the mulled test (only those tests still in the meta.yaml are run).

**Comment by LiterallyUniqueLogin** [comment]
@BiocondaBot please add label

**Comment by dpryan79** [comment]
@bioconda-bot please fetch artifacts

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Pull request merged**
