### PR TITLE
Add bioconda-utils recipe.

### PR DESCRIPTION
**Pull request by johanneskoester**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

This is necessary for the reproducibility of our Bioconda paper.

### CODE REVIEW

**Comment by bgruening** [comment]
Restarted the tests.

**Comment by johanneskoester** [comment]
@bgruening bioconda-utils won't install into the mulled container because it needs to be installed in the root environment. As we don't want a mechanism to disable mulled tests, I guess the solution is to provide a hardcoded exception in bioconda-utils itself (disable mulled testing if you build yourself), right?

**Comment by bgruening** [comment]
@johanneskoester You could in theory use run_test files that are currently ignored by mulled. Otherwise, I I can not think of a better way, currently.

**Comment by bgruening** [comment]
Restarted with latest changes from Ryan.

**Comment by daler** [comment]
I just added a new v0.11.1 release with the updates and updated this recipe, so that the built package can theoretically build itself.

**Comment by bgruening** [comment]
Super cool!

**Comment by johanneskoester** [comment]
Thanks @daler for taking care of this!

**Pull request merged**
