### PR TITLE
Adding flexbar v3.0.0

### PR DESCRIPTION
**Pull request by holtgrewe**
* [x] I have read the guidelines above.
* [x] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by holtgrewe** [comment]
@jtroehr :cake:

**Comment by holtgrewe** [comment]
This faces the same problem as #3020 *sigh*

**Comment by marcelm** [comment]
Can you build from sources instead? Then it would link against the static libbz2.a.

**Comment by holtgrewe** [comment]
Flexbar requires a too modern GCC.

**Comment by holtgrewe** [comment]
Except if @jtroer could build it statically against libbz2?

**Comment by bwlang** [comment]
@holtgrewe thanks for your work on this... would is be easier now in light of https://www.anaconda.com/blog/developer-blog/utilizing-the-new-compilers-in-anaconda-distribution-5/ ?

**Comment by bgruening** [comment]
@bwlang not yet, but we are getting there. conda-build-3 will happen soon in conda-forge and then we will adopt it :)

**Pull request closed without merging**
