### PR TITLE
Gsl

### PR DESCRIPTION
**Pull request by molpopgen**
* [ X] I have read the guidelines above.
* [ X] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

This recipe is for GSL 2.2.  The current conda recipe for 2.1 gives "incompatible library" errors for both Linux and OS X when you try linking.  I figure a consistently-compiled version for bioconda could be handy.

I have also gone ahead and checked that installing GSL 2.2 on OS X when compiled with clang results in a library that can be linked to when using Conda/GCC on OS X.

### CODE REVIEW

**Comment by bgruening** [comment]
I guess this should more into conda-forge. @johanneskoester @daler ?

**Comment by molpopgen** [comment]
@bgruening Argh--I didn't check there first.  They have 2.1.  I guess I need to figure out how to list a dependency from condo-forge in a yaml file for bioconda.  I've not been able to find an example of a dependency from another channel anywhere.

**Comment by bgruening** [comment]
@molpopgen bioconda now depends on conda-forge. Just add this channel to your global channel list as described in our Guidelines. Or simply `conda build ./foo -c conda-forge`

**Comment by bgruening** [comment]
I cancelled the builds, hope this is ok.

**Comment by molpopgen** [comment]
@bgruening No problem.  I'm checking that conda-forge/gsl does indeed work.

**Pull request closed without merging**
