### PR TITLE
Update cellsnake to 0.2.0.12

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`cellsnake`](https://bioconda.github.io/recipes/cellsnake/README.html): **0.2.0.11** &rarr; **0.2.0.12**

[install with bioconda](http://bioconda.github.io/recipes/cellsnake/README.html) [Conda](https://anaconda.org/bioconda/cellsnake/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/cellsnake`](https://github.com//bioconda/bioconda-recipes/tree/bump/cellsnake/recipes/cellsnake) (click to view/edit other files)
Summary | cellsnake, a user-friendly tool for single cell RNA sequencing analysis
Home | [https://github.com/sinanugur/cellsnake](https://github.com/sinanugur/cellsnake)
Releases |[https://pypi.org/pypi/cellsnake/json](https://pypi.org/pypi/cellsnake/json)
Recipe Maintainer(s) | @sinanugur

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by sinanugur** [comment]
@BiocondaBot rebuild

**Comment by sinanugur** [comment]
@BiocondaBot please update

**Comment by sinanugur** [comment]
@BiocondaBot rebuild

**Comment by daler** [comment]
Hmm, are there data copied in somehow? The build is [running out of space](https://dev.azure.com/bioconda/bioconda-recipes/_build/results?buildId=51566&view=logs&j=e14e69ff-a0ae-55c4-b71d-229b239cfb2f&t=4dddc55b-10bc-50fc-ac68-7ff899b7a030&l=2460) which is strange.

**Comment by sinanugur** [comment]
> Hmm, are there data copied in somehow? The build is [running out of space](https://dev.azure.com/bioconda/bioconda-recipes/_build/results?buildId=51566&view=logs&j=e14e69ff-a0ae-55c4-b71d-229b239cfb2f&t=4dddc55b-10bc-50fc-ac68-7ff899b7a030&l=2460) which is strange.

Hi. 

Well some of the dependencies might be inflated. The package itself it only 12MB so not much different from the previous version. I have to update the recipe as well for this version so I also tried to drop some of the dependencies to test if that works but nothing works for now.

Cheers

**Comment by sinanugur** [comment]
@BiocondaBot please add label

**Pull request merged**
