### PR TITLE
infernal: add linux-aarch64 build

### PR DESCRIPTION
**Pull request by martin-g**
Describe your pull request here

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

### General instructions

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

### Instructions for avoiding API, ABI, and CLI breakage issues
Conda is able to record and lock (a.k.a. pin) dependency versions used at build time of other recipes.
This way, one can avoid that expectations of a downstream recipe with regards to API, ABI, or CLI are violated by later changes in the recipe.
If not already present in the meta.yaml, make sure to specify `run_exports` (see [here](https://bioconda.github.io/contributor/linting.html#missing-run-exports) for the rationale and comprehensive explanation).
Add a `run_exports` section like this:

```yaml
build:
  run_exports:
    - ...

```

with `...` being one of:

| Case                             | run_exports statement                                               |
| -------------------------------- | ------------------------------------------------------------------- |
| semantic versioning              | `{{ pin_subpackage("myrecipe", max_pin="x") }}`     |
| semantic versioning (0.x.x)      | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}`   |
| known breakage in minor versions | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| known breakage in patch versions | `{{ pin_subpackage("myrecipe", max_pin="x.x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| calendar versioning              | `{{ pin_subpackage("myrecipe", max_pin=None) }}`    |

while replacing `"myrecipe"` with either `name` if a `name|lower` variable is defined in your recipe or with the lowercase name of the package in quotes.

### Bot commands for PR management

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

Note that the <code>@BiocondaBot please merge</code> command is now depreciated. Please just squash and merge instead.

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by martin-g** [comment]
The build error for Linux ARM64 is:
```
./configure --prefix=/opt/conda/conda-bld/infernal_1712151558751/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac ''[0m
13:41:21 [32mBIOCONDA INFO[0m (OUT) configure: WARNING: you should use --build, --host, --target[0m
13:41:21 [32mBIOCONDA INFO[0m (OUT) configure: Configuring Infernal for your system.[0m
13:41:21 [32mBIOCONDA INFO[0m (OUT) Invalid configuration `aarch64-conda-linux-gnu': machine `aarch64-conda' not recognized[0m
13:41:21 [32mBIOCONDA INFO[0m (OUT) configure: error: /bin/sh ./config.sub aarch64-conda-linux-gnu failed[0m
```
I don't quite understand it.
The build passes on my Linux ARM64 VM but there it detects `host:                 aarch64-unknown-linux-gnu`.

The Linux x86_64 build detects similar host but there it is OK:
```
./configure --prefix=/opt/conda/conda-bld/infernal_1712151893549/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac --enable-sse[0m
2024-04-03T13:49:07.3563011Z 13:49:05 [32mBIOCONDA INFO[0m (OUT) configure: Configuring Infernal for your system.[0m
2024-04-03T13:49:07.3563376Z 13:49:05 [32mBIOCONDA INFO[0m (OUT) checking build system type... x86_64-conda-linux-gnu[0m
2024-04-03T13:49:07.3563717Z 13:49:05 [32mBIOCONDA INFO[0m (OUT) checking host system type... x86_64-conda-linux-gnu[0m
2024-04-03T13:49:07.3564107Z 13:49:05 [32mBIOCONDA INFO[0m (OUT) checking whether to compile using MPI... no[0m
2024-04-03T13:49:07.3564621Z 13:49:05 [32mBIOCONDA INFO[0m (OUT) checking for x86_64-conda-linux-gnu-gcc... $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-cc
```

**Comment by martin-g** [comment]
@BiocondaBot please fetch artifacts

**Comment by martin-g** [comment]
```

mgrigorov in 🌐 euler-arm-22 in /tmp/infernal took 11s 
❯ tar jxvf infernal-1.1.5-pl5321h8a409c4_1.tar.bz2 
info/run_exports.json
info/test/run_test.sh
info/hash_input.json
info/index.json
info/files
info/recipe/build.sh
info/recipe/meta.yaml.template
info/recipe/meta.yaml
info/licenses/LICENSE
info/paths.json
info/recipe/conda_build_config.yaml
info/about.json
info/git
bin/cmpress
bin/cmconvert
bin/cmfetch
bin/cmemit
bin/cmstat
bin/cmalign
bin/cmcalibrate
bin/cmscan
bin/cmsearch
bin/cmbuild
share/man/man1/cmpress.1
share/man/man1/cmconvert.1
share/man/man1/cmfetch.1
share/man/man1/infernal.1
share/man/man1/cmstat.1
share/man/man1/cmemit.1
share/man/man1/cmcalibrate.1
share/man/man1/cmbuild.1
share/man/man1/cmalign.1
share/man/man1/cmsearch.1
share/man/man1/cmscan.1

mgrigorov in 🌐 euler-arm-22 in /tmp/infernal 
❯ file ./bin/*
./bin/cmalign:     ELF 64-bit LSB pie executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, not stripped
./bin/cmbuild:     ELF 64-bit LSB pie executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, not stripped
./bin/cmcalibrate: ELF 64-bit LSB pie executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, not stripped
./bin/cmconvert:   ELF 64-bit LSB pie executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, not stripped
./bin/cmemit:      ELF 64-bit LSB pie executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, not stripped
./bin/cmfetch:     ELF 64-bit LSB pie executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, not stripped
./bin/cmpress:     ELF 64-bit LSB pie executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, not stripped
./bin/cmscan:      ELF 64-bit LSB pie executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, not stripped
./bin/cmsearch:    ELF 64-bit LSB pie executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, not stripped
./bin/cmstat:      ELF 64-bit LSB pie executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, not stripped

mgrigorov in 🌐 euler-arm-22 in /tmp/infernal 
❯ ./bin/cmalign 
Incorrect number of command line arguments.
Usage: cmalign [-options] <cmfile> <seqfile>

where basic options are:
  -h     : show brief help on version and usage
  -o <f> : output the alignment to file <f>, not stdout
  -g     : configure CM for global alignment [default: local]

To see more help on available options, do ./bin/cmalign -h
```

LGTM!

**Comment by martin-g** [comment]
@BiocondaBot please add label

**Review by mencian — APPROVED** [review]

**Pull request merged**
