### PR TITLE
seapr update 1.1.11

### PR DESCRIPTION
**Pull request by tobiashofmann88**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by tobiashofmann88** [comment]
Not sure what is going wrong here, the linting exits witht the error "missing_tests", but I have a "test" section in my meta.yaml file, and it is the same I always had, which was sufficient for all previous updates (last one <1 month ago). Has something changed? What tests are required for this to function?
Any help is much appreciated!
Best,
Tobi

**Comment by tobiashofmann88** [comment]
am I reading it correctly in the linting report that the error actually occurs when linting the recipe for **short-read-connector** 
`18:50:39 BIOCONDA DEBUG lint recipes/short-read-connector`
?

Not sure where that is coming form, must be a dependency of one of my dependencies. I just saw that that recipe has been changed 8 days ago, so maybe some compatibility problem?

**Comment by tobiashofmann88** [comment]
@marcelm can you help with this? trying to release a new version of my secapr pipeline and haven't changed anything in the recipe except for the version number and the sha-key but now there are tons of errors with the linting of dependencies (see below). Has conda intorduced additional tests and do all of those 14 recipes need to be fixed by hand before I can release my new package?
Best,
Tobi

`	recipe	check	info	depends_on_java-jdk	fix	missing_hash	missing_home	no_tests	should_not_use_fn	should_use_compilers	uses_git_url
0	recipes/discovar-denovo	missing_tests	{'no_tests': True, 'fix': 'add basic tests'}		add basic tests			True			
1	recipes/discovar-denovo	missing_hash	"{'missing_hash': True, 'fix': 'add md5, sha1, or sha256 hash to ""source"" section'}"		"add md5, sha1, or sha256 hash to ""source"" section"	True					
2	recipes/fiji/20151222	uses_javajdk	"{'depends_on_java-jdk': True, 'fix': 'use ""openjdk"" instead of ""java-jdk""'}"	True	"use ""openjdk"" instead of ""java-jdk"""						
3	recipes/flexbar/3.3.0	should_not_use_fn	{'should_not_use_fn': True, 'fix': 'URL should specify path to file, which will be used as the filename'}		URL should specify path to file, which will be used as the filename				True		
4	recipes/flexbar/3.3.0	should_use_compilers	"{'should_use_compilers': True, 'fix': 'use {{ compiler(""c"") }} or other new-style compilers'}"		"use {{ compiler(""c"") }} or other new-style compilers"					True	
5	recipes/gfinisher	uses_javajdk	"{'depends_on_java-jdk': True, 'fix': 'use ""openjdk"" instead of ""java-jdk""'}"	True	"use ""openjdk"" instead of ""java-jdk"""						
6	recipes/hurry.filesize	missing_home	{'missing_home': True, 'fix': 'add about:home'}		add about:home		True				
7	recipes/icqsol	missing_hash	"{'missing_hash': True, 'fix': 'add md5, sha1, or sha256 hash to ""source"" section'}"		"add md5, sha1, or sha256 hash to ""source"" section"	True					
8	recipes/icqsol	uses_git_url	{'uses_git_url': True, 'fix': 'use tarballs whenever possible'}		use tarballs whenever possible						True
9	recipes/igblast/1.4.0	missing_hash	"{'missing_hash': True, 'fix': 'add md5, sha1, or sha256 hash to ""source"" section'}"		"add md5, sha1, or sha256 hash to ""source"" section"	True					
10	recipes/mapsplice	missing_home	{'missing_home': True, 'fix': 'add about:home'}		add about:home		True				
11	recipes/pbdagcon	missing_hash	"{'missing_hash': True, 'fix': 'add md5, sha1, or sha256 hash to ""source"" section'}"		"add md5, sha1, or sha256 hash to ""source"" section"	True					
12	recipes/pbdagcon	uses_git_url	{'uses_git_url': True, 'fix': 'use tarballs whenever possible'}		use tarballs whenever possible						True
13	recipes/perl-heap-simple-perl	missing_tests	{'no_tests': True, 'fix': 'add basic tests'}		add basic tests			True			
14	recipes/perl-readonly	missing_tests	{'no_tests': True, 'fix': 'add basic tests'}		add basic tests			True	`

**Comment by marcelm** [comment]
There was probably a problem in the master branch that you based this PR upon. Merge current master to fix. You can find instructions in #9873: `git fetch origin master:master && git merge master`.

**Comment by tobiashofmann88** [comment]
thanks for your help! So this means I should execute that git fetch command in my local copy of the bioconda recipe? If I do so it returns an error:
`Tobiass-MBP-2:bioconda-recipes tobias$ git fetch origin master:master && git merge master`

`fatal: Refusing to fetch into current branch refs/heads/master of non-bare repository`

I must say I dont totally understand what the purpose of this command is and hence where to execute it. Is it supposed to update my copy of the master branch of bioconda/bioconda-recipes?

**Comment by marcelm** [comment]
Yes, the idea of the `fetch` was to update your local copy of the master branch, then the `merge` would merge those changes into your branch. The command I gave doesn’t work because you don’t work in bioconda directly, but on a fork, which I forgot. I think the easiest thing is if you just open a completely new PR and close this one.

**Pull request closed without merging**
