### PR TITLE
Stacks 2 0

### PR DESCRIPTION
**Pull request by pbordron**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by pbordron** [comment]
ping @lecorguille @bioconda/core
The conda-build version of bioconda doesn't allow to use the jinja2 function {{ compiler('c') }} which solves the issue with gcc compiler. Is there some project to update to a new one?

https://conda.io/docs/user-guide/tasks/build-packages/define-metadata.html#host

**Comment by lecorguille** [comment]
ping @bioconda/core

**Comment by pbordron** [comment]
@bgruening @lecorguille the htslib library included with stacks didn't take in account the env. variables  like CC, CXX, etc.
Now it works.

**Comment by lecorguille** [comment]
Congrats @pbordron!

**Comment by chapmanb** [comment]
Philippe -- nice work and thanks for the examples about how to use the newer gcc compilers. This will really help me get unstuck on some recipes I'd been working on that require new versions.

**Comment by bgruening** [comment]
@pbordron nice work. Please note that these compiler where designed to work with conda-build-3. I'm not sure about the consequences. conda-forge has choose to stick to `gcc` until the transition to cb3.
I guess its ok to make an exception for those packages, just wanted to point this out.

ping @bioconda/core

**Comment by johanneskoester** [comment]
We should be careful using the new compiler packages for libraries, but otherwise, if it cannot be avoided, it should be fine.

**Pull request merged**
