### PR TITLE
Dash

### PR DESCRIPTION
**Pull request by SilasK**
Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it. Note that if you are not already a member of the bioconda project (meaning that you can't add this label), please ping `@bioconda/core` so that your PR can be reviewed and merged (please note if you'd like to be added to the bioconda project). Please see https://github.com/bioconda/bioconda-recipes/issues/15332 for more details.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by dpryan79** [comment]
Can you enable edits on this PR?

**Comment by SilasK** [comment]
This would mean tat @dnbaker you allow contribution on your fork, is n'it?

**Comment by SilasK** [comment]
This would mean tat @dnbaker you allow contribution on your fork, is n'it?

**Comment by dnbaker** [comment]
My guess is that you control it, @SilasK. (I'm not the owner of this PR. Maybe[this](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork) might help.)

**Comment by SilasK** [comment]
> My guess is that you control it, @SilasK. (I'm not the owner of this PR. Maybe this might help.)
Thank you @dnbaker, it seems I should have done this during the creation of the PR. 

I now copied your code to the first PR, #18692 which is from a branch. So @dpryan79 you should be able to contribute to it.

**Pull request closed without merging**
