### PR TITLE
Added svist4get to tobias package dependencies

### PR DESCRIPTION
**Pull request by msbentsen**
Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it. Note that if you are not already a member of the bioconda project (meaning that you can't add this label), please ping `@bioconda/core` so that your PR can be reviewed and merged (please note if you'd like to be added to the bioconda project). Please see https://github.com/bioconda/bioconda-recipes/issues/15332 for more details.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by dpryan79** [comment]
This was just added

**Comment by dpryan79** [comment]
Oops, wrong PR to close

**Comment by dpryan79** [comment]
@bioconda-bot please update

**Comment by dpryan79** [comment]
I'll try to fix svist4get, since argparse has been part of python for years.

**Comment by jenzopr** [comment]
Closed in favor of #18885

**Comment by jenzopr** [comment]
Sorry 🙈

**Comment by msbentsen** [comment]
Thanks for your help on this @dpryan79. Strange "requirement" for argparse - I never had that error installing svist4get directly from pypi as a dependency for TOBIAS.

**Comment by dpryan79** [comment]
Yeah, I'm not sure why that's happening, I guess for some reason it's looking for non-core modules or something.

**Comment by dpryan79** [comment]
@bioconda-bot please update

**Comment by dpryan79** [comment]
@bioconda-bot please fetch artifacts

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Comment by jenzopr** [comment]
Great! Thanks a bunch, @dpryan79 🎉

**Pull request merged**
