### PR TITLE
Update starfish to 0.2.1

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`starfish`](https://bioconda.github.io/recipes/starfish/README.html): **0.2.0** &rarr; **0.2.1**

[install with bioconda](http://bioconda.github.io/recipes/starfish/README.html) [Conda](https://anaconda.org/bioconda/starfish/files)

Info | Link
-----|-----
Recipe | [`recipes/starfish`](https://github.com//bioconda/bioconda-recipes/tree/bump/starfish/recipes/starfish) (click to view/edit other files)
Releases |[https://github.com/spacetx/starfish/tags](https://github.com/spacetx/starfish/tags)
Author | `@spacetx`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by aaronmussig** [comment]
@BiocondaBot update

**Comment by neuromusic** [comment]
any idea what's up with the tests failing @aaronmussig? looks like an error with your circleci config? 
image
 
cc @joshmoore

**Comment by aaronmussig** [comment]
@BiocondaBot update

**Comment by neuromusic** [comment]
thanks @aaronmussig! no dice, though. Any idea what's going on? I'm not familiar with Bioconda's build process

**Comment by aaronmussig** [comment]
Not sure exactly, @dpryan79 ?

**Comment by dpryan79** [comment]
@bioconda-bot please update

**Comment by dpryan79** [comment]
It's through linting now. Whatever read_roi is would need to be added to conda before this can get built.

**Pull request closed without merging**
