### PR TITLE
pin jpeg lib on gnuplot recipe

### LINKED ISSUE #2568: gnuplot is missing libjpeg
gnuplot: error while loading shared libraries: libjpeg.so.8: cannot open shared object file: No such file or directory

### PR DESCRIPTION
**Pull request by rvalieris**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

fixes #2568 and #4848 

I know gnuplot 5.0.5 is available on conda-forge but this should keep the latest bioconda version working, in case people are still using it.

### CODE REVIEW

**Comment by rvalieris** [comment]
@bioconda/core 
I think the test is failing here because the mulled builds don't support the `test::files` directive, is it possible to include these files in the test or should I workaround it ? I could generate the test data on-the-fly I guess.

**Comment by bgruening** [comment]
On the fly would be great. Supporting test files needs a little bit work and I'm a little bit busy currently.

**Comment by johanneskoester** [comment]
I guess you want the test file because a simple gnuplot -h would not discover a certain error?

**Comment by rvalieris** [comment]
ok, I will try to make the test file on-the-fly !
@johanneskoester , the test file was added by someone else, I just want to keep the tests as is, if possible.

**Comment by croth1** [comment]
FYI, we have a properly pinned gnuplot in conda-forge. We might want to move this recipe to bioconda-legacy to avoid double maintenance costs.

**Comment by johanneskoester** [comment]
Yes. Definitely. This is our policy for all non bio-related packages. Can you create a PR that removes the recipe?

**Comment by rvalieris** [comment]
I am aware that gnuplot was ported to conda-forge, however I though the policy was to not remove a package from bioconda unless a equivalent version exists on conda-forge, in this case conda-forge gnuplot have version 5.0.5, and bioconda have 5.0.4, this is why I decided make a new rebuild with the correct pinning.
the recipe itself can be removed now though, I will make a PR later.

**Comment by johanneskoester** [comment]
Yes, that's fine.

**Pull request merged**
