### PR TITLE
Update hifiasm to 0.16.1

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`hifiasm`](https://bioconda.github.io/recipes/hifiasm/README.html): **0.16.0** &rarr; **0.16.1**

[install with bioconda](http://bioconda.github.io/recipes/hifiasm/README.html) [Conda](https://anaconda.org/bioconda/hifiasm/files)

Info | Link
-----|-----
Recipe | [`recipes/hifiasm`](https://github.com//bioconda/bioconda-recipes/tree/bump/hifiasm/recipes/hifiasm) (click to view/edit other files)
Releases |[https://github.com/chhylp123/hifiasm/tags](https://github.com/chhylp123/hifiasm/tags)
Author | `@chhylp123`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by bgruening** [comment]
@chhylp123 we have a problem here with the newly introduced `mempcpy` which is not yet supported by CLANG as it seems. At least not the version we are using.

**Comment by chhylp123** [comment]
@bgruening Thanks. Let me check it with CLANG.

**Comment by chhylp123** [comment]
@bgruening I have renewed the release 0.16.1. Could you please try it again? Thank you so much.

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
@bioconda-bot please merge

**Comment by bgruening** [comment]
Looks great now!

**Comment by chhylp123** [comment]
Thanks all for the great help.

**Pull request merged**
