### PR TITLE
add reciper for clinker-py

### PR DESCRIPTION
**Pull request by rpetit3**
This PR adds a reciper for clinker-py. Clinker-py is a pipeline for easily generating publication-quality gene cluster comparison figures.

More details can be found here https://github.com/gamcil/clinker and https://github.com/gamcil/clinker/issues/29

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by rpetit3** [comment]
@BiocondaBot please fetch artifacts

**Comment by rpetit3** [comment]
Tests:

```
conda create -y -n clinker -c conda-forge -c bioconda -c https://136015-42372094-gh.circle-artifacts.com/0/tmp/artifacts/packages clinker-py
conda activate clinker

# Test help
clinker --help
usage: clinker [-h] [-na] [-i IDENTITY] [-j JOBS] [-s SESSION] [-ji JSON_INDENT] [-f] [-o OUTPUT] [-p [PLOT]] [-dl DELIMITER] [-dc DECIMALS] [-hl] [-ha] [-ufo] files [files ...]
... truncated ... 
Align clusters, plot results and print scores to screen:
  $ clinker files/*.gbk

Cameron Gilchrist, 2020

# Run example 
git clone git@github.com:gamcil/clinker.git
cd clinker
clinker examples/*gbk -p test.html
[23:59:09] INFO - Starting clinker
[23:59:09] INFO - Parsing GenBank files: ['examples/A. alliaceus CBS 536.65.gbk', 'examples/A. burnettii MST-FP2249.gbk', 'examples/A. mulundensis DSM 5745.gbk', 'examples/A. versicolor CBS 583.65.gbk', 'examples/P. vexata CBS 129021.gbk']
[23:59:09] INFO - Starting cluster alignments
[23:59:09] INFO - A. alliaceus CBS 536.65 vs A. burnettii MST-FP2249
[23:59:09] INFO - A. alliaceus CBS 536.65 vs A. mulundensis DSM 5745

... truncated ...

OJI99008.1  OJI99008.1  0.42      0.58
OJI99009.1  OJI99009.1  0.51      0.63
OJI99010.1  OJI99010.1  0.45      0.61
OJI99011.1  OJI99011.1  0.42      0.52
[23:59:11] INFO - Done!


```

Looks like everything worked fine, I've attached a screen shot from the output HTML file. 

Capture

**Comment by rpetit3** [comment]
@BiocondaBot please add label

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
Nice, I saw the tweet announcing this and thought it looked super cool!

**Comment by rpetit3** [comment]
Agreed, playing around with the example it was pretty straight forward.

**Comment by dpryan79** [comment]
Please have the bot merge this once the test is finished.

**Comment by rpetit3** [comment]
@BiocondaBot please merge

**Pull request merged**
