### PR TITLE
Updated ddRAGE to version 1.4.0

### PR DESCRIPTION
**Pull request by HenningTimm**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by HenningTimm** [comment]
I am not 100% sure why this created a conflict. I did nothing different than the last 3 times.

**Comment by eseiler** [comment]
You probably didn't merge the master into your local branch before updating? So there was 1.3.1 in the master and 1.3.0 in your branch according to the commits. Then you'll get the conflict when changing the version to 1.4.0 on your branch.

**Comment by HenningTimm** [comment]
Thanks, that is a very likely explanation for what happened.

**Comment by bgruening** [comment]
Thanks @HenningTimm!

**Comment by HenningTimm** [comment]
Thanks for merging @bgruening.

**Pull request merged**
