### PR TITLE
Add r-base as a dependency

### PR DESCRIPTION
**Pull request by rhpvorderman**
r-base is needed for picard CollectMultipleMetrics, CollectInsertSizeMetrics etc. (basically anything with metrics).

* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by bgruening** [comment]
https://github.com/bioconda/bioconda-recipes/issues/3859 :(

**Comment by rhpvorderman** [comment]
> #3859 :(

@bgruening. I posted my opinion on the issue.

**Comment by rhpvorderman** [comment]
@bgruening , given that there was no great backlash on the issue, I think that nobody strongly cares about this. Shall we go ahead and merge this?

**Comment by bgruening** [comment]
@dpryan79 any opinion?

**Comment by dpryan79** [comment]
I’m a very weak “no” on this. Picard is just so bloated as is and I have to say this is the first time I’d heard that Picard did any plotting on this.

**Comment by cbrueffer** [comment]
I tend to agree that things should work out of the box, although I have to admit I shared Devon's unawareness regarding the R dependency. Given the bloat having a `picard-lite` recipe and pointing to that in the `picard` install message would be good.

**Comment by rhpvorderman** [comment]
@bgruening @dpryan79 @cbrueffer 
The previous iteration of picard has been renamed to picard-slim. 
While copying the package I found that a bash wrapper script is used to run picard instead of a python wrapper script. So I removed the python dependency in both picard and picard-slim.

Is this compromise to your liking?

**Comment by dpryan79** [comment]
:+1: from me. @bgruening @cbrueffer thoughts?

**Comment by cbrueffer** [comment]
Looks good; a post-install message in each of the recipes pointing to the other one would be nice ("A package without the R dependency is available as `picard-slim` or similar); see e.g. `recipes/braker2/post-link.sh`.

**Comment by bgruening** [comment]
Fine with me ...

**Comment by rhpvorderman** [comment]
> Looks good; a post-install message in each of the recipes pointing to the other one would be nice ("A package without the R dependency is available as picard-slim or similar); see e.g. recipes/braker2/post-link.sh.

@cbrueffer  I do agree that users need to be notified. While working on the post-link script however, I felt that I had to write a really, really good message that would be worth it for the user to see every  time they install picard. This is IMO not possible. It is a very  annoying way to let users know.

I have added information about picard and picard-slim  to the package descriptions, so that users can make an informed decision on which package to install based on the information on bioconda.github.io.

**Comment by cbrueffer** [comment]
Thanks @rhpvorderman , I like the idea.

**Comment by alanhoyle** [comment]
Can this be added to the gatk4 as a dependency as well?

**Pull request merged**
