### PR TITLE
Update illumina/akt to 0.3.3

### PR DESCRIPTION
**Pull request by stephenturner**
Updates akt to 0.3.3 https://github.com/Illumina/akt/releases/tag/v0.3.3 

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by dpryan79** [comment]
I think the original issue about "not a git repository" is due to https://github.com/Illumina/akt/blob/master/Makefile#L40-L44 though given the ifneq stuff I assume that shouldn't have been an issue (N.B., we might need to patch the incorrect version in the Makefile).

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@stephenturner Looks like everything worked. If you're done with changes go ahead and post a comment that starts with "@bioconda-bot please merge" (without the quotes).

**Comment by stephenturner** [comment]
Thanks @dpryan79. I just submitted a PR at https://github.com/Illumina/akt/compare/master...stephenturner:patch-1 to fix the version number in the Makefile. What happens to this recipe if merged when the Makefile is updated in the akt repo?

**Comment by stephenturner** [comment]
@dpryan79 sorry for the dumb question here, should it be `@bioconda-bot please merge` as you suggest, or `@BiocondaBot please add label` as in the issue template ☝️

**Comment by dpryan79** [comment]
Either spelling of the bots name is fine :)

Regarding the patch, it depends on whether you want to add that here already or just wait for it to get merged in and a new release tagged upstream. Personally, I'd let them merge it upstream and tag a new release (there should then be a PR automatically generated here to update this recipe). It's not a big deal in my mind if the binary is printing the wrong version, since we can be sure that that's just a minor bug. But to each their own on that.

**Comment by stephenturner** [comment]
Thanks @dpryan79. I'll wait for them to merge upstream. So the PR is automatically triggered here? No need to modify the yaml with the new sha and build version?

**Comment by dpryan79** [comment]
Exactly, we have a cron job that looks for updates and (usually) generates an appropriate PR with the normal changes (version and sha256).

**Comment by dpryan79** [comment]
Closes #28311

**Comment by stephenturner** [comment]
@bioconda-bot please merge

**Comment by dpryan79** [comment]
Give the Anaconda CDN ~45 minutes to sync globally and then this should be available.

**Pull request merged**
