### PR TITLE
Update to plantcv v3.3.0

### PR DESCRIPTION
**Pull request by nfahlgren**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by npavlovikj** [comment]
@nfahlgren , your recipe is failing at the Liniting step, and not while building. The error is:
`NotImplementedError: overlap in comment [None, [CommentToken('# [linux]\n', line: 20)]] [None, [CommentToken('# [linux]\n', line: 21)]]`

I am not sure what the error exactly means, but I would try removing `noarch: python` - `noarch` packages are for architecture-independent packages, while yours need to use libGL on linux, and not osx, which is not independent. 

Regarding "libGL", I believe just using the extended-base should work, and you will see if that gives you any error during build afer the linting step is fixed.

**Comment by npavlovikj** [comment]
Ah, please ignore what I said earlier @nfahlgren  - I didn't notice that you were not using any compilers...
In that case, please keep `noarch: python`, and remove `# [linux]` from the `build` section, so you have something like in https://github.com/bioconda/bioconda-recipes/blob/0c10b43ca0b7acdba91527f8573e872507bb4d5c/recipes/bioconductor-rdrtoolbox/meta.yaml.

**Comment by nfahlgren** [comment]
Thanks @npavlovikj, the comments were definitely causing linting to fail. I updated the PR and the CircleCI log now shows the build error I was talking about.

**Comment by nfahlgren** [comment]
Awesome, thanks @npavlovikj!

**Comment by npavlovikj** [comment]
@BiocondaBot merge

**Pull request merged**
