### PR TITLE
Update anvio-minimal to v7

### PR DESCRIPTION
**Pull request by meren**
Updates the anvio-minimal recipe to match the latest release of [anvi'o](http://merenlab.org/software/anvio), a software platform directly relevant to the biological sciences.

### CODE REVIEW

**Comment by meren** [comment]
@BiocondaBot please fetch artifacts

**Comment by meren** [comment]
The artifact installs nicely in my local, and the command that freaks out the build system works beautifully :(

**Comment by meren** [comment]
@BiocondaBot please add label

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
This is the second package I've seen where importing openmp in python causes this error (I think the other was staden). I think there's something wrong with a conda-forge dependency.

**Comment by meren** [comment]
Thank you @dpryan79 and @druvus for looking into this. Is it still OK to merge this since the package is working as expected outside of the build environment?

Best wishes,

**Comment by druvus** [comment]
Seems downgrading scikit-learn solves the issue but I am not sure it is a long-term solution.

**Comment by meren** [comment]
> Seems downgrading scikit-learn solves the issue but I am not sure it is a long-term solution.

This is interesting and I have no idea why it solves the problem. I'm curious how did you even come up with this idea. It would have never occurred to me.

**Comment by druvus** [comment]
Started to read about the issue that seems to be quite common.  When I found an old closed issue at your github repo with the same error message (https://github.com/merenlab/anvio/issues/1489) I decided to give it a try.

**Review by druvus — APPROVED** [review]

**Comment by meren** [comment]
Ah, I see! I hadn't realized that using the extended image  solved the ASCII encoder issue but then there was another error!

Thank you very much for going after that one too, @druvus. You are the best.

**Comment by druvus** [comment]
@BiocondaBot please fetch artifacts

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Pull request merged**
