### PR TITLE
Copy bam.h in include/bam

### PR DESCRIPTION
**Pull request by npavlovikj**
:information_source:
Bioconda has finished the [GCC7 migration](https://github.com/bioconda/bioconda-recipes/issues/13578). If you are dealing with C/C++ or Python package it can be that you need to rebuild other dependent packages. [Bioconda utils - update-pinning](https://bioconda.github.io/updating.html#updating-recipes-for-a-pinning-change) will assist you with that. If you have any questions please use [issue 13578](https://github.com/bioconda/bioconda-recipes/issues/13578).

----------------

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by dpryan79** [comment]
Is there a reason for doing this?

**Comment by npavlovikj** [comment]
@dpryan79 , I was planning of picking your brain on this once the build passes...
I am working on a recipe for "braker2" (tested with "samtools/1.7"), that requires newer version of "augustus" than the one available in "bioconda". This version of "augustus" (3.3.2) has a dependency, https://github.com/Gaius-Augustus/Augustus/tree/master/auxprogs/bam2wig, that needs "bam.h" and "libbam.a" to compile.
As you know, "bam.h" and "libbam.a" are only available in "samtools/0.1.19", and not the newer recipes, so that is why I opened this PR. Is there a reason why the newer "samtools" packages don't contain these files?

**Comment by dpryan79** [comment]
I don't think copying the header files from newer samtools releases will work. The API from pre-htslib versions of samtools was somewhat different than what's available with current releases. The good news is that `bam.a` would be statically compiled into `bam2wig`, so you don't need to try and shoe-horn old file names into more modern samtools/htslib releases.

**Comment by npavlovikj** [comment]
I see... Does this mean I should use "samtools/0.1.19" for "augustus"?

**Comment by dpryan79** [comment]
Yes, that should work

**Comment by npavlovikj** [comment]
Many thanks Devon, I will try that next.

**Pull request closed without merging**
