### PR TITLE
Update busco to 4.1.1

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`busco`](https://bioconda.github.io/recipes/busco/README.html): **4.0.6** &rarr; **4.1.1**

[install with bioconda](http://bioconda.github.io/recipes/busco/README.html) [Conda](https://anaconda.org/bioconda/busco/files)

Info | Link
-----|-----
Recipe | [`recipes/busco`](https://github.com//bioconda/bioconda-recipes/tree/bump/busco/recipes/busco) (click to view/edit other files)
Releases |[https://gitlab.com/ezlab/busco/tags](https://gitlab.com/ezlab/busco/tags)
Recipe Maintainer(s) | @silask, @matsepp, @berkelem

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by SilasK** [comment]
Apparently dependency cannot be solved any longer, even when there is no change.

**Comment by berkelem** [comment]
I managed to get past the linux tests by removing the version constraint for Augustus. But there are still conflicts in the macos tests.
Bioconda appears to have been upgraded to version 1.77 within the past week, but specifying 1.76 does not fix the problem. Nor does specifying Python 3.7.

**Comment by SilasK** [comment]
Wasn't there a reason why we had to fix the Augustus version? Maybe removing the constraint creates some other problems

**Comment by berkelem** [comment]
The augustus version was previously fixed to 3.2.3 because of a perceived incompatibility that turned out to be an error in the BUSCO code. That is resolved now so there is no need to restrict augustus, except to keep the conda release dependencies as close to the Docker release dependencies as possible. The BUSCO Docker image still uses Augustus 3.2.3. But the Docker release also now uses BLAST 2.10.1+ which is not yet available on conda, so the conda/Docker releases will be divergent anyway.

**Comment by abretaud** [comment]
#23299 should fix the osx build problem
It's still red here though, maybe there is some cache on circleci that would explain that the new build of sepp is not used? What do you think @dpryan79?

**Comment by abretaud** [comment]
There seem to be a conflict between augustus 3.3.3 and r-base 4.0 on osx, looking into it

**Comment by berkelem** [comment]
Blast constraint is necessary. There is a multithreading problem for all BLAST versions between 2.4 and 2.10.0. This was fixed for BLAST 2.10.1 but that version is not yet available on conda.

**Comment by SilasK** [comment]
Can we make it available?

**Comment by abretaud** [comment]
There's https://github.com/bioconda/bioconda-recipes/pull/20874 for 2.10.0, looking at it atm

**Comment by abretaud** [comment]
Green now :)
I'm still working on #20874, so let's wait a little before merging this one

**Comment by berkelem** [comment]
Great! Thanks for your help.

**Comment by abretaud** [comment]
It should be ready now, with blast 2.10.1 :)
I'm leaving for a few days, feel free to add label/review/merge when you want

**Comment by abretaud** [comment]
@BiocondaBot please add label

**Comment by berkelem** [comment]
> It should be ready now, with blast 2.10.1 :)
> I'm leaving for a few days, feel free to add label/review/merge when you want

Excellent. Thanks for all your hard work.

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Pull request merged**
