### PR TITLE
feat: Prereqs for Bioconductor script

### PR DESCRIPTION
**Pull request by aliciaaevans**
This script originally output missing CRAN packages, but I've added an option to output conda-forge packages stuck in migration. Also added an option to output a checklist in markdown format, which includes the first couple of pertinent lines from the bot output. (Inspired by https://github.com/bioconda/bioconda-recipes/issues/49778)

Example output from `python ./scripts/bioconductor/missingCranPackages.py --format markdown --migration_id r-base44_and_m2w64-ucrt`
```
## Awaiting migration of 105 packages ##
### In PR (27 packages) ###
- [ ] `r-strawr`: In PR https://github.com/conda-forge/r-strawr-feedstock/pull/4
- [ ] `r-rttf2pt1`: In PR https://github.com/conda-forge/r-rttf2pt1-feedstock/pull/19
- [ ] `r-dplr`: In PR https://github.com/conda-forge/r-dplr-feedstock/pull/14
- [ ] `r-logistf`: In PR https://github.com/conda-forge/r-logistf-feedstock/pull/14
- [ ] `r-cairo`: In PR https://github.com/conda-forge/r-cairo-feedstock/pull/36
- [ ] `r-infotheo`: In PR https://github.com/conda-forge/r-infotheo-feedstock/pull/13
- [ ] `r-primme`: In PR https://github.com/conda-forge/r-primme-feedstock/pull/17
- [ ] `r-ckmeans.1d.dp`: In PR https://github.com/conda-forge/r-ckmeans.1d.dp-feedstock/pull/10
- [ ] `r-rcppalgos`: In PR https://github.com/conda-forge/r-rcppalgos-feedstock/pull/16
- [ ] `r-rmariadb`: In PR https://github.com/conda-forge/r-rmariadb-feedstock/pull/25
- [ ] `r-msqc`: In PR https://github.com/conda-forge/r-msqc-feedstock/pull/7
- [ ] `r-vim`: In PR https://github.com/conda-forge/r-vim-feedstock/pull/18
- [ ] `r-bayesm`: In PR https://github.com/conda-forge/r-bayesm-feedstock/pull/14
- [ ] `r-pdftools`: In PR https://github.com/conda-forge/r-pdftools-feedstock/pull/48
- [ ] `r-backbone`: In PR https://github.com/conda-forge/r-backbone-feedstock/pull/16
- [ ] `r-bold`: In PR https://github.com/conda-forge/r-bold-feedstock/pull/17
- [ ] `r-glmmtmb`: In PR https://github.com/conda-forge/r-glmmtmb-feedstock/pull/27
- [ ] `r-locfit`: In PR https://github.com/conda-forge/r-locfit-feedstock/pull/20
- [ ] `r-rcurl`: In PR https://github.com/conda-forge/r-rcurl-feedstock/pull/33
- [ ] `r-rmixmod`: In PR https://github.com/conda-forge/r-rmixmod-feedstock/pull/17
- [ ] `r-mixtools`: In PR https://github.com/conda-forge/r-mixtools-feedstock/pull/14
- [ ] `r-hdf5r`: In PR https://github.com/conda-forge/r-hdf5r-feedstock/pull/34
- [ ] `r-rcppparallel`: In PR https://github.com/conda-forge/r-rcppparallel-feedstock/pull/30
- [ ] `r-git2r`: In PR https://github.com/conda-forge/r-git2r-feedstock/pull/44
- [ ] `r-envstats`: In PR https://github.com/conda-forge/r-envstats-feedstock/pull/15
- [ ] `r-scs`: In PR https://github.com/conda-forge/r-scs-feedstock/pull/5
- [ ] `r-wrswor`: In PR https://github.com/conda-forge/r-wrswor-feedstock/pull/2
### Bot Error (12 packages) ###
- [ ] `r-rjsoncons`: bot error (<a href="https://github.com/regro/cf-scripts/actions/runs/10471726786">bot CI job</a>): main: Error running migrate-feedstock in container - JSON could not parse stdout:
- [ ] `r-nycflights13`: bot error (<a href="https://github.com/regro/cf-scripts/actions/runs/10471726786">bot CI job</a>): main: Error running migrate-feedstock in container - JSON could not parse stdout:
- [ ] `r-pspline`: bot error (<a href="https://github.com/regro/cf-scripts/actions/runs/10473752058">bot CI job</a>): main: Error running migrate-feedstock in container - JSON could not parse stdout:
- [ ] `r-sparsemvn`: bot error (<a href="https://github.com/regro/cf-scripts/actions/runs/10473752058">bot CI job</a>): main: Error running migrate-feedstock in container - JSON could not parse stdout:
- [ ] `r-magick`: bot error (<a href="https://github.com/regro/cf-scripts/actions/runs/10470019435">bot CI job</a>): main: Error running check-solvable in container - error ValueError raised:
- [ ] `r-rebus.base`: bot error (<a href="https://github.com/regro/cf-scripts/actions/runs/10470019435">bot CI job</a>): main: Error running migrate-feedstock in container - JSON could not parse stdout:
- [ ] `r-rtriangle`: bot error (<a href="https://github.com/regro/cf-scripts/actions/runs/10470019435">bot CI job</a>): main: Error running migrate-feedstock in container - JSON could not parse stdout:
- [ ] `r-maptree`: bot error (<a href="https://github.com/regro/cf-scripts/actions/runs/10468254743">bot CI job</a>): main: Error running migrate-feedstock in container - JSON could not parse stdout:
- [ ] `r-anylib`: bot error (<a href="https://github.com/regro/cf-scripts/actions/runs/10470019435">bot CI job</a>): main: Error running migrate-feedstock in container - JSON could not parse stdout:
- [ ] `r-common`: bot error (<a href="https://github.com/regro/cf-scripts/actions/runs/10471726786">bot CI job</a>): main: Error running migrate-feedstock in container - JSON could not parse stdout:
- [ ] `r-superheat`: bot error (<a href="https://github.com/regro/cf-scripts/actions/runs/10473752058">bot CI job</a>): main: Error running migrate-feedstock in container - JSON could not parse stdout:
- [ ] `r-isa2`: bot error (<a href="https://github.com/regro/cf-scripts/actions/runs/10463453441">bot CI job</a>): main: Error running migrate-feedstock in container - JSON could not parse stdout:
### Not Solvable (10 packages) ###
- [ ] `r-rmpi`: not solvable (<a href='https://github.com/regro/cf-scripts/actions/runs/10464511121'>bot CI job</a>) @ main  No candidates were found for openmpi 5.*.
- [ ] `r-tkrplot`: not solvable (<a href='https://github.com/regro/cf-scripts/actions/runs/10471726786'>bot CI job</a>) @ main  No candidates were found for tcl *.
- [ ] `r-harmony`: not solvable (<a href='https://github.com/regro/cf-scripts/actions/runs/10470019435'>bot CI job</a>) @ main  No candidates were found for libwinpthread-git *.
- [ ] `r-spdep`: not solvable (<a href='https://github.com/regro/cf-scripts/actions/runs/10473752058'>bot CI job</a>) @ main  r-sf * cannot be installed because there are no viable options
- [ ] `r-pmcmrplus`: not solvable (<a href='https://github.com/regro/cf-scripts/actions/runs/10461481144'>bot CI job</a>) @ main  r-ksamples >=1.2.7 cannot be installed because there are no viable options
- [ ] `r-transformr`: not solvable (<a href='https://github.com/regro/cf-scripts/actions/runs/10471726786'>bot CI job</a>) @ main  r-sf * cannot be installed because there are no viable options
- [ ] `r-protolite`: not solvable (<a href='https://github.com/regro/cf-scripts/actions/runs/10473752058'>bot CI job</a>) @ main  r-sf * cannot be installed because there are no viable options
- [ ] `r-gstat`: not solvable (<a href='https://github.com/regro/cf-scripts/actions/runs/10473752058'>bot CI job</a>) @ main  r-sf >=0.7_2 cannot be installed because there are no viable options
- [ ] `r-rjags`: not solvable (<a href='https://github.com/regro/cf-scripts/actions/runs/10470019435'>bot CI job</a>) @ main //conda.anaconda.org/conda-forge/linux-ppc64le/repodata.json.zst
- [ ] `r-gamlss`: not solvable (<a href='https://github.com/regro/cf-scripts/actions/runs/10473752058'>bot CI job</a>) @ main  r-gamlss.dist >=4.3.1 cannot be installed because there are no viable options
### Awaiting Parents (56 packages) ###
- [ ] `r-lambertw`: Awaiting parents ( r-lamw, r-rcppparallel )
- [ ] `r-ggrastr`: Awaiting parents ( r-cairo )
- [ ] `r-flatxml`: Awaiting parents ( r-rcurl )
- [ ] `r-stringfish`: Awaiting parents ( r-rcppparallel )
- [ ] `r-hrbrthemes`: Awaiting parents ( r-rttf2pt1, r-extrafont )
- [ ] `r-gprofiler2`: Awaiting parents ( r-rcurl )
- [ ] `r-fda`: Awaiting parents ( r-hdrcde, r-rainbow, r-locfit, r-rcurl, r-fds )
- [ ] `r-r2jags`: Awaiting parents ( r-rjags )
- [ ] `r-rebus.unicode`: Awaiting parents ( r-rebus.base )
- [ ] `r-smoothwin`: Awaiting parents ( r-rcppparallel, r-rfast )
- [ ] `r-densestbayes`: Awaiting parents ( r-rstantools, r-rstan, r-stanheaders, r-rcppparallel )
- [ ] `r-waffle`: Awaiting parents ( r-rttf2pt1, r-extrafont )
- [ ] `r-logr`: Awaiting parents ( r-common )
- [ ] `r-dicer`: Awaiting parents ( r-infotheo )
- [ ] `r-taxize`: Awaiting parents ( r-bold )
- [ ] `r-summarytools`: Awaiting parents ( r-magick )
- [ ] `r-rstantools`: Awaiting parents ( r-rcppparallel )
- [ ] `r-eva`: Awaiting parents ( r-envstats )
- [ ] `r-rstan`: Awaiting parents ( r-stanheaders, r-rcppparallel )
- [ ] `r-plsvarsel`: Awaiting parents ( r-msqc )
- [ ] `r-opencpu`: Awaiting parents ( r-protolite )
- [ ] `r-remacor`: Awaiting parents ( r-envstats )
- [ ] `r-tidytidbits`: Awaiting parents ( r-rttf2pt1, r-extrafont )
- [ ] `r-webchem`: Awaiting parents ( r-rcurl )
- [ ] `r-tiledb`: Awaiting parents ( r-nycflights13 )
- [ ] `r-qs`: Awaiting parents ( r-rcppparallel, r-stringfish )
- [ ] `r-compositions`: Awaiting parents ( r-bayesm )
- [ ] `r-textstem`: Awaiting parents ( r-rcppparallel, r-quanteda )
- [ ] `r-agricolae`: Awaiting parents ( r-spdep )
- [ ] `r-rebus`: Awaiting parents ( r-rebus.datetimes, r-rebus.base, r-rebus.numbers, r-rebus.unicode )
- [ ] `r-lamw`: Awaiting parents ( r-rcppparallel )
- [ ] `r-animation`: Awaiting parents ( r-magick )
- [ ] `r-stanheaders`: Awaiting parents ( r-rcppparallel )
- [ ] `r-qdaptools`: Awaiting parents ( r-rcurl )
- [ ] `r-bestnormalize`: Awaiting parents ( r-rcppparallel, r-lamw, r-lambertw )
- [ ] `r-ggalt`: Awaiting parents ( r-rttf2pt1, r-extrafont )
- [ ] `r-ggimage`: Awaiting parents ( r-magick )
- [ ] `r-extrafont`: Awaiting parents ( r-rttf2pt1 )
- [ ] `r-hdrcde`: Awaiting parents ( r-locfit )
- [ ] `r-rainbow`: Awaiting parents ( r-hdrcde, r-locfit )
- [ ] `r-xml2r`: Awaiting parents ( r-rcurl )
- [ ] `r-rebus.numbers`: Awaiting parents ( r-rebus.base )
- [ ] `r-robcompositions`: Awaiting parents ( r-vim, r-rcurl, r-hdrcde, r-fda, r-rainbow, r-fds, r-locfit )
- [ ] `r-gganimate`: Awaiting parents ( r-transformr )
- [ ] `r-gprofiler`: Awaiting parents ( r-rcurl )
- [ ] `r-varfrompdb`: Awaiting parents ( r-xml2r, r-rcurl )
- [ ] `r-fds`: Awaiting parents ( r-hdrcde, r-rainbow, r-locfit, r-rcurl )
- [ ] `r-reldist`: Awaiting parents ( r-rstantools, r-densestbayes, r-rstan, r-stanheaders, r-rcppparallel )
- [ ] `r-mvoutlier`: Awaiting parents ( r-vim, r-rcurl, r-hdrcde, r-fda, r-rainbow, r-fds, r-robcompositions, r-locfit )
- [ ] `r-quanteda`: Awaiting parents ( r-rcppparallel )
- [ ] `r-cvxr`: Awaiting parents ( r-scs )
- [ ] `r-rebus.datetimes`: Awaiting parents ( r-rebus.base )
- [ ] `r-paralleldist`: Awaiting parents ( r-rcppparallel )
- [ ] `r-survivalanalysis`: Awaiting parents ( r-rttf2pt1, r-tidytidbits, r-extrafont )
- [ ] `r-copula`: Awaiting parents ( r-pspline )
- [ ] `r-rfast`: Awaiting parents ( r-rcppparallel )
## Missing 8 packages ##
- [ ] r-tidydr
- [ ] r-mwcsr
- [ ] r-microbiomestat
- [ ] r-tca
- [ ] r-dashboardthemes
- [ ] r-mashr
- [ ] r-shinycyjs
- [ ] r-rbeta2009
```

### CODE REVIEW

**Comment by aliciaaevans** [comment]
Just realized somehow some not missing packages are getting added to "missing". I'll have to fix that

**Comment by mfansler** [comment]
So cool! Thanks @aliciaaevans 😎

I'm out of office now but will have a more detailed look tomorrow.

**Review by mfansler — APPROVED** [review]
Really excellent! I verified script with and without the migration argument - both work as expected. Code is straightforward to follow, well-commented.

**Review by bgruening — APPROVED** [review]
Oh that is great! Thanks a lot @aliciaaevans

**Pull request merged**
