### PR TITLE
add exomiser-cli recipe

### PR DESCRIPTION
**Pull request by matthdsm**
The PR add the `exomiser-cli` package for variant prioritisation.

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

### General instructions

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

### Instructions for avoiding API, ABI, and CLI breakage issues
Conda is able to record and lock (a.k.a. pin) dependency versions used at build time of other recipes.
This way, one can avoid that expectations of a downstream recipe with regards to API, ABI, or CLI are violated by later changes in the recipe.
If not already present in the meta.yaml, make sure to specify `run_exports` (see [here](https://bioconda.github.io/contributor/linting.html#missing-run-exports) for the rationale and comprehensive explanation).
Add a `run_exports` section like this:

```yaml
build:
  run_exports:
    - ...

```

with `...` being one of:

| Case                             | run_exports statement                                               |
| -------------------------------- | ------------------------------------------------------------------- |
| semantic versioning              | `{{ pin_subpackage("myrecipe", max_pin="x") }}`     |
| semantic versioning (0.x.x)      | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}`   |
| known breakage in minor versions | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| known breakage in patch versions | `{{ pin_subpackage("myrecipe", max_pin="x.x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| calendar versioning              | `{{ pin_subpackage("myrecipe", max_pin=None) }}`    |

while replacing `"myrecipe"` with either `name` if a `name|lower` variable is defined in your recipe or with the lowercase name of the package in quotes.

### Bot commands for PR management

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

Note that the <code>@BiocondaBot please merge</code> command is now depreciated. Please just squash and merge instead.

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by matthdsm** [comment]
ping @abhayr20, this is the PR I was talking about.

**Comment by matthdsm** [comment]
for reference; the contents of the downloaded package
```
exomiser-cli-13.2.1/CHANGELOG.md
exomiser-cli-13.2.1/LICENCE.txt
exomiser-cli-13.2.1/README.md
exomiser-cli-13.2.1/application.properties
exomiser-cli-13.2.1/exomiser-cli-13.2.1.jar
exomiser-cli-13.2.1/lib/commons-net-3.3.jar
exomiser-cli-13.2.1/lib/slf4j-api-1.7.36.jar
exomiser-cli-13.2.1/lib/javautil-0.0.1.jar
exomiser-cli-13.2.1/lib/snappy-java-1.1.7.3.jar
exomiser-cli-13.2.1/lib/commons-io-2.4.jar
exomiser-cli-13.2.1/lib/exomiser-spring-boot-autoconfigure-13.2.1.jar
exomiser-cli-13.2.1/lib/commons-compress-1.19.jar
exomiser-cli-13.2.1/lib/jannovar-hgvs-0.30.jar
exomiser-cli-13.2.1/lib/spring-boot-2.7.7.jar
exomiser-cli-13.2.1/lib/log4j-api-2.17.2.jar
exomiser-cli-13.2.1/lib/spring-context-support-5.3.24.jar
exomiser-cli-13.2.1/lib/guava-31.1-jre.jar
exomiser-cli-13.2.1/lib/exomiser-core-13.2.1.jar
exomiser-cli-13.2.1/lib/jackson-annotations-2.13.4.jar
exomiser-cli-13.2.1/lib/jackson-core-2.13.4.jar
exomiser-cli-13.2.1/lib/ini4j-0.5.1.jar
exomiser-cli-13.2.1/lib/unbescape-1.1.6.RELEASE.jar
exomiser-cli-13.2.1/lib/spring-tx-5.3.24.jar
exomiser-cli-13.2.1/lib/spring-aop-5.3.24.jar
exomiser-cli-13.2.1/lib/h2-1.4.200.jar
exomiser-cli-13.2.1/lib/htsjdk-2.24.1.jar
exomiser-cli-13.2.1/lib/javassist-3.20.0-GA.jar
exomiser-cli-13.2.1/lib/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar
exomiser-cli-13.2.1/lib/jblas-1.2.3.jar
exomiser-cli-13.2.1/lib/exomiser-spring-boot-starter-13.2.1.jar
exomiser-cli-13.2.1/lib/commons-jexl-2.1.1.jar
exomiser-cli-13.2.1/lib/spring-boot-dependencies-2.7.7.pom
exomiser-cli-13.2.1/lib/spring-beans-5.3.24.jar
exomiser-cli-13.2.1/lib/spring-expression-5.3.24.jar
exomiser-cli-13.2.1/lib/jakarta.annotation-api-1.3.5.jar
exomiser-cli-13.2.1/lib/j2objc-annotations-1.3.jar
exomiser-cli-13.2.1/lib/gson-2.9.1.jar
exomiser-cli-13.2.1/lib/spring-boot-starter-cache-2.7.7.jar
exomiser-cli-13.2.1/lib/antlr4-runtime-4.7.jar
exomiser-cli-13.2.1/lib/javax.annotation-api-1.3.2.jar
exomiser-cli-13.2.1/lib/logback-core-1.2.11.jar
exomiser-cli-13.2.1/lib/checker-qual-3.19.0.jar
exomiser-cli-13.2.1/lib/failureaccess-1.0.1.jar
exomiser-cli-13.2.1/lib/jackson-databind-2.13.4.2.jar
exomiser-cli-13.2.1/lib/svart-1.0.2.jar
exomiser-cli-13.2.1/lib/logback-classic-1.2.11.jar
exomiser-cli-13.2.1/lib/spring-jdbc-5.3.24.jar
exomiser-cli-13.2.1/lib/spring-boot-autoconfigure-2.7.7.jar
exomiser-cli-13.2.1/lib/protobuf-java-util-3.21.12.jar
exomiser-cli-13.2.1/lib/jackson-dataformat-yaml-2.13.4.jar
exomiser-cli-13.2.1/lib/ngs-java-2.9.0.jar
exomiser-cli-13.2.1/lib/jsr305-3.0.2.jar
exomiser-cli-13.2.1/lib/spring-context-5.3.24.jar
exomiser-cli-13.2.1/lib/spring-boot-starter-logging-2.7.7.jar
exomiser-cli-13.2.1/lib/spring-core-5.3.24.jar
exomiser-cli-13.2.1/lib/protobuf-java-3.21.12.jar
exomiser-cli-13.2.1/lib/mjson-1.4.1.jar
exomiser-cli-13.2.1/lib/attoparser-2.0.5.RELEASE.jar
exomiser-cli-13.2.1/lib/spring-jcl-5.3.24.jar
exomiser-cli-13.2.1/lib/thymeleaf-3.0.15.RELEASE.jar
exomiser-cli-13.2.1/lib/jul-to-slf4j-1.7.36.jar
exomiser-cli-13.2.1/lib/error_prone_annotations-2.10.0.jar
exomiser-cli-13.2.1/lib/ontologizer-0.0.1.jar
exomiser-cli-13.2.1/lib/jackson-dataformat-protobuf-2.13.4.jar
exomiser-cli-13.2.1/lib/commons-cli-1.5.0.jar
exomiser-cli-13.2.1/lib/phenopacket-schema-1.0.0.jar
exomiser-cli-13.2.1/lib/jackson-datatype-jdk7-2.6.7.jar
exomiser-cli-13.2.1/lib/snakeyaml-1.30.jar
exomiser-cli-13.2.1/lib/log4j-to-slf4j-2.17.2.jar
exomiser-cli-13.2.1/lib/protoparser-4.0.3.jar
exomiser-cli-13.2.1/lib/HikariCP-4.0.3.jar
exomiser-cli-13.2.1/lib/xz-1.8.jar
exomiser-cli-13.2.1/lib/ognl-3.1.26.jar
exomiser-cli-13.2.1/lib/jannovar-htsjdk-0.30.jar
exomiser-cli-13.2.1/lib/commons-csv-1.1.jar
exomiser-cli-13.2.1/lib/spring-boot-starter-2.7.7.jar
exomiser-cli-13.2.1/lib/thymeleaf-spring5-3.0.15.RELEASE.jar
exomiser-cli-13.2.1/lib/jannovar-core-0.30.jar
exomiser-cli-13.2.1/lib/caffeine-2.9.3.jar
```

**Comment by matthdsm** [comment]
@bioconda/core Who should I ask for help wrt to java libs? 
tests report:
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at org.monarchinitiative.exomiser.cli.Main.<clinit>(Main.java:40)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
```

**Comment by rpetit3** [comment]
Does this help any? https://stackoverflow.com/questions/12926899/java-lang-noclassdeffounderror-org-slf4j-loggerfactory

**Comment by matthdsm** [comment]
Hi @rpetit3 ,

Thanks for the suggestion. The thing is, all dependencies _should_ be there, but I'm having trouble getting the actual application to find the lib dir that's included.
Would you mind checking out the `build.sh` script and see if I'm not doing anything blatantly wrong?

Thanks
Matthias

**Pull request closed without merging**
