### PR TITLE
bedops: 2.4.20

### PR DESCRIPTION
**Pull request by saketkc**
* [x] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by saketkc** [comment]
@johanneskoester Have you seen this `libc/libm` issue before?
https://travis-ci.org/bioconda/bioconda-recipes/jobs/165199663#L885

**Comment by saketkc** [comment]
cc @bgruening

**Comment by bgruening** [comment]
Yes, is there anywhere a `-static` in your make step? Try to remove it.

**Comment by saketkc** [comment]
Thanks a lot @bgruening!

**Comment by alexpreynolds** [comment]
Thanks for patching the recipe!

**Pull request merged**
