### PR TITLE
Seacr

### PR DESCRIPTION
**Pull request by stephanflemming**
Previous update didn't work.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences**
      (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

@BiocondaBot please add label
@BiocondaBot please fetch artifacts

### CODE REVIEW

**Comment by stephanflemming** [comment]
Not sure what's not working here.

ping @simonbray @bgruening

**Comment by bgruening** [comment]
Please try something similar to `- SEACR_{{ version }}.R --help 2>&1 | grep <expected text>`.

I guess the test is writing to stderr and this terminates the testing.

**Comment by stephanflemming** [comment]
@BiocondaBot please add label
@BiocondaBot please fetch artifacts

**Comment by bgruening** [comment]
@BiocondaBot please merge

**Pull request merged**
