### PR TITLE
Add bioconductor package: genebreak

### PR DESCRIPTION
**Pull request by CicoZhang**
* [x] I have read the guidelines above.
* [x] This PR adds a new recipe. [Link](https://www.bioconductor.org/packages/release/bioc/html/GeneBreak.html)
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by CicoZhang** [comment]
@bgruening

**Comment by bgruening** [comment]
Thanks @CicoZhang!

**Comment by bgruening** [comment]
Hope you had a nice travel back home!

**Comment by CicoZhang** [comment]
@bgruening  You are welcome! Thank YOU for the nice training and knowledge sharing. I did have a nice travel back home and I hope you did as well.

**Pull request merged**
