### PR TITLE
Salmon 0.11.0 buildbump

### PR DESCRIPTION
**Pull request by rob-p**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by bgruening** [comment]
@rob-p what was the Docker build issue?
I think the correct way is to reset the build number to 0 if you release a complete new version. Sorry, have not spotted this in your last PR.

**Comment by rob-p** [comment]
@bgruening : The issue actually did't show up at all in bioconda's build (or on my local CI).  It showed up only when building the Docker image for salmon (on Ubuntu 18.04 stock).  It's complicated, but basically, on that system, the inclusion of boost_thread forced `-lpthread` into the linker flags, which breaks the build (because pthread should be linked statically by passing `-pthread` to the compiler and linker).  The solution was to simply stop linking against `boost_pthread`, since I wasn't using it anyway.

**Comment by rob-p** [comment]
The only reason I re-submitted the bioconda build is because I had to update the CMakeLists.txt file, which changed the md5sum.  Since I didn't tag the release on Docker or on our github releases page yet, I simply moved the 0.11.0 tag to this new version.  I wanted to make sure the md5sum for the bioconda build matched what we have tagged as 0.11.0, so I updated the build.

**Comment by bgruening** [comment]
Ok! Thanks for the explanation. Lets reset the build number to 0 for this new version. Feel free to merge, bedtime for me.

**Pull request merged**
