### PR TITLE
Enable r-sleuth installs on OSX.

### PR DESCRIPTION
**Pull request by roryk**
* [x] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

This enables sleuth installation on OSX.

### CODE REVIEW

**Comment by daler** [comment]
#476 has been bugging me on and off for months, I think that's the underlying issue here.

**Comment by roryk** [comment]
Thanks Ryan, dang didn't realize how deep this rabbit hole was going to go. Ouch.

**Comment by roryk** [comment]
Closing for now, thanks!

**Comment by druvus** [comment]
@roryk I just fixed r-sleuth for osx (#3692).

**Comment by roryk** [comment]
Whoa, thanks Andreas!

**Pull request closed without merging**
