### PR TITLE
megan

### PR DESCRIPTION
**Pull request by bernt-matthias**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

This adds a recipe for [megan](http://ab.inf.uni-tuebingen.de/software/megan6/).  I could only test successfully with the “Bootstrap” method. The automatic test for the actual MEGAN script (i.e. the graphical frontend) does not work but a manual test works.

Note that this is my first new recipe. 

circleci gives me:
```
Warning: Unrecognized source format. Source file will be copied to the SRC_DIR
source tree in: /opt/conda/conda-bld/megan_1537476167253/work
Traceback (most recent call last):
  File "/opt/conda/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 424, in main
    execute(sys.argv[1:])
  File "/opt/conda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 415, in execute
    verify=args.verify)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/api.py", line 201, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/build.py", line 2205, in build_tree
    notest=notest,
  File "/opt/conda/lib/python3.6/site-packages/conda_build/build.py", line 1445, in build
    utils.check_call_env(cmd, env=env, cwd=src_dir, stats=build_stats)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/utils.py", line 311, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/utils.py", line 291, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-e', '/opt/conda/conda-bld/megan_1537476167253/work/conda_build.sh']' returned non-zero exit status 83.
```

### CODE REVIEW

**Comment by bernt-matthias** [comment]
should anything else from the downloads http://ab.inf.uni-tuebingen.de/data/software/megan6/download/welcome.html be included?

**Comment by bernt-matthias** [comment]
I just read that jar files should go to `$PREFIX/share/$PKG_NAME-$PKG_VERSION-$PKG_BUILDNUM` which would add extra complications. Comments?

**Comment by daler** [comment]
thanks @bernt-matthias. Couple of comments:

- w.r.t. additional files, from that downloads page, if you want you could include a script that downloads the data files, but in general data shouldn't go in packages.

- you'll probably want to have a preprocess selector ` # [osx]` to use the `.dmg` file provided for Mac.

- I don't know enough about MEGAN to know whether it needs a wrapper to handle memory allocation configuration like `-Xmx`. If so, it would be nice to have it in the path recommended for jar files. This is primarily to keep the `/bin` dir clean though. Looking at the build script it seems like it'll be pretty annoying, but I'd say worth a shot to see if you can get it working.

**Comment by bernt-matthias** [comment]
Thanks for your comments. 

> w.r.t. additional files, from that downloads page, if you want you could include a script that downloads the data files, but in general data shouldn't go in packages.

agreed

> you'll probably want to have a preprocess selector # [osx] to use the .dmg file provided for Mac.

I added it. Is there anything that needs to be done in build.sh? Or is conda taking care. Since I have no idea on osx (apart from the fact that it exists).

> I don't know enough about MEGAN to know whether it needs a wrapper to handle memory allocation configuration like -Xmx. If so, it would be nice to have it in the path recommended for jar files. This is primarily to keep the /bin dir clean though. Looking at the build script it seems like it'll be pretty annoying, but I'd say worth a shot to see if you can get it working.

Each of the executables in MEGAN is a wrapper that calls java. 
- In the way they are called they all use the options specified in the file `MEGAN.vmoptions` that is included (and contains -Xmx2000M). 
- The ones in the tools directory (which are all command line tools) additionally add: `-server -Duser.language=en -Duser.region=US -Djava.awt.headless=true` and set the class paths.
- The main MEGAN executable (which starts a graphical frontend) adds some more parameters (most of which I do not understand). 

For the last latter the options `"$prg_dir/error.log" "$prg_dir/error.log"` could be problematic in multiuser environments .. as they try to write in the conda environment. I could change this to `cwd` which seems sensible.

The main megan wrapper is created by the installer and is really difficult to understand. There are some variables (local_classpath and bundled_jre_home) to which the contents of the jre folder are added (and other things, e.g. the contents of the installer jars in .install4j). 

So: its a mess and I would be very happy if I wouldn't need to touch it. 


$PREFIX/share/$PKG_NAME-$PKG_VERSION-$PKG_BUILDNUM.

**Comment by bernt-matthias** [comment]
Could someone restart the build, apparently the download failed.

**Comment by bgruening** [comment]
Done.

**Comment by bernt-matthias** [comment]
Anybody has an idea what the problem is here. I guess its with the mac version.

The only recipe for a dmg file in bioconda seems to be this one: https://github.com/bioconda/bioconda-recipes/blob/master/recipes/fiji/20151222/build.sh .. given that the recipe for linux was already quite complicated I would prefer to exclude the mac version for now.

**Comment by bgruening** [comment]
ping @bioconda/osx 
Feel free go for OSX only.

**Pull request merged**
