### PR TITLE
update krona recipe

### PR DESCRIPTION
**Pull request by maxibor**
This PR updates an existing recipe.
Fixing Krona taxonomy database creation

### CODE REVIEW

**Comment by bgruening** [comment]
@maxibor did you missed to bump the version number and the URL?

**Comment by maxibor** [comment]
No, the version remains the same. I've however fixed some krona scripts that were missing/broken before.

**Comment by bgruening** [comment]
I'm just wondering why the patch is not needed anymore if its not a new version and the patch is not applied upstream.

**Comment by maxibor** [comment]
Because the patch didn't seem to work:
**With patch**
```
(krona2) betsy:~ Maxime$ ktUpdateTaxonomy.sh ~/Desktop/taxo2/
Fetching taxdump.tar.gz...
   Fetching checksum...
   Checksum for taxdump.tar.gz matches server.
make: //anaconda/envs/krona2/bin/scripts/taxonomy.make: No such file or directory
make: *** No rule to make target `//anaconda/envs/krona2/bin/scripts/taxonomy.make'.  Stop.

Update failed.
   Building taxonomy table failed (see errors above). Issues can be tracked and reported at https://github.com/marbl/Krona/issues.
```

**Withouth the patch, and fixed symlinks** (this PR):
```
(krona) betsy:~ Maxime$ ktUpdateTaxonomy.sh ~/Desktop/taxo
Fetching taxdump.tar.gz...
   Fetching checksum...
   Checksum for taxdump.tar.gz matches server.
Extracting taxonomy...

Cleaning up...

Finished.
```

You can try it out on my anaconda channel:

```
conda install -c maxibor krona
ktUpdateTaxonomy.sh /path/to/some/directory/to/store/taxonomy
```

**Comment by bgruening** [comment]
Ok, thanks for the update!

**Pull request merged**
