### PR TITLE
Update FastTree(MP)

### PR DESCRIPTION
**Pull request by keuv-grvl**
* [x] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [x] This PR does something else (explain below).

My first goal was to make FastTreeMP (compiled with OpenMP) available through Bioconda.
I opted for updating the existing FastTree recipe to produce FastTree and FastTreeMP instead of a separate "FastTreeMP" recipe.

In the same time, I upgraded to from v2.1.8 to v2.1.9.

HTH

### CODE REVIEW

**Comment by bgruening** [comment]
Looks great! Thanks for using templates :)

**Comment by bgruening** [comment]
@keuv-grvl thanks for your contribution! A Docker container was also created for you `docker pull quay.io/mulled/fasttree:2.1.9--0`

**Comment by keuv-grvl** [comment]
I am happy to help :-)
Is the container creation automatic? Otherwise, do you have guidelines to do it?

**Comment by bgruening** [comment]
Yes, every 24h these are created via travis. Here is the repo https://github.com/mulled/auto-mulled

We will try to get this setup as part of bioconda to make it more transparent, but we have a lot to do at the infrastructure side of bioconda. Help is appreciated :)

**Pull request merged**
