### PR TITLE
Add recipe for scArches

### PR DESCRIPTION
**Pull request by jdblischak**
* Original recipe generated using `grayskull pypi scarches`
* Added `run_exports`
* Follow-up to https://github.com/bioconda/bioconda-recipes/pull/50613

https://github.com/theislab/scarches
https://pypi.org/project/scArches/

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

### General instructions

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

### Instructions for avoiding API, ABI, and CLI breakage issues
Conda is able to record and lock (a.k.a. pin) dependency versions used at build time of other recipes.
This way, one can avoid that expectations of a downstream recipe with regards to API, ABI, or CLI are violated by later changes in the recipe.
If not already present in the meta.yaml, make sure to specify `run_exports` (see [here](https://bioconda.github.io/contributor/linting.html#missing-run-exports) for the rationale and comprehensive explanation).
Add a `run_exports` section like this:

```yaml
build:
  run_exports:
    - ...

```

with `...` being one of:

| Case                             | run_exports statement                                               |
| -------------------------------- | ------------------------------------------------------------------- |
| semantic versioning              | `{{ pin_subpackage("myrecipe", max_pin="x") }}`     |
| semantic versioning (0.x.x)      | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}`   |
| known breakage in minor versions | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| known breakage in patch versions | `{{ pin_subpackage("myrecipe", max_pin="x.x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| calendar versioning              | `{{ pin_subpackage("myrecipe", max_pin=None) }}`    |

while replacing `"myrecipe"` with either `name` if a `name|lower` variable is defined in your recipe or with the lowercase name of the package in quotes.

### Bot commands for PR management

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

Note that the <code>@BiocondaBot please merge</code> command is now depreciated. Please just squash and merge instead.

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by jdblischak** [comment]
Main downside is that this package is quite large:

https://pypi.org/project/scArches/#files

image

**Comment by jdblischak** [comment]
The `pip check` test [failed](https://dev.azure.com/bioconda/bioconda-recipes/_build/results?buildId=68888&view=logs&j=e14e69ff-a0ae-55c4-b71d-229b239cfb2f&t=7df82132-b284-504b-53d6-7d3e63519572):

```
scvi-tools 1.1.6 has requirement lightning<2.2,>=2.0, but you have lightning 2.4.0.
```

**Comment by jdblischak** [comment]
Unclear where this upper bound is coming from

The upstream package dropped the upper bound 5 months ago

https://github.com/scverse/scvi-tools/commit/9b4277f413c7a8bcb639223fca79e46c22cc3e0e
https://github.com/scverse/scvi-tools/pull/2751

And the feedstock dropped the upper bound 2 weeks ago

https://github.com/conda-forge/scvi-tools-feedstock/pull/52

The bioconda build installed the latest scvi-tools 1.1.6-pyhd8ed1ab_1

https://anaconda.org/conda-forge/scvi-tools/files?version=1.1.6

Which has a correct recipe, but the `lightning<2.2` is still buried in the `METADATA`:

```sh
wget https://anaconda.org/conda-forge/scvi-tools/1.1.6/download/noarch/scvi-tools-1.1.6-pyhd8ed1ab_1.conda
cph extract scvi-tools-1.1.6-pyhd8ed1ab_1.conda
grep lightning scvi-tools-1.1.6-pyhd8ed1ab_1/info/recipe/meta.yaml
##     - lightning >=2.0
grep -R lightning scvi-tools-1.1.6-pyhd8ed1ab_1/site-packages/scvi_tools-1.1.6.dist-info/
## scvi-tools-1.1.6-pyhd8ed1ab_1/site-packages/scvi_tools-1.1.6.dist-info/METADATA:Requires-Dist: lightning<2.2,>=2.0
## scvi-tools-1.1.6-pyhd8ed1ab_1/site-packages/scvi_tools-1.1.6.dist-info/METADATA:Lightning](https://www.pytorclightning.ai/) and
```

**Comment by jdblischak** [comment]
@BiocondaBot please add label

**Comment by jdblischak** [comment]
I rebased my PR onto master. Here is the [passing Azure build from yesterday](https://dev.azure.com/bioconda/bioconda-recipes/_build/results?buildId=69503&view=results)

**Comment by jdblischak** [comment]
@bioconda/review @bioconda/python Python recipe ready for review

**Review by bgruening — APPROVED** [review]
Thanks @jdblischak

**Comment by jdblischak** [comment]
Quick follow-up. Some of the builds [failed](https://dev.azure.com/bioconda/bioconda-recipes/_build/results?buildId=69703&view=results) for the CI on the merged commit, https://github.com/bioconda/bioconda-recipes/commit/fb23832c60385badd476cf91b2e534b22b1365f3. Fortunately the [binary had already been uploaded to anaconda.org](https://anaconda.org/bioconda/scarches/files?version=0.6.1). I was able to [restart the failed jobs](https://github.com/bioconda/bioconda-recipes/runs/30400669872) using the GitHub UI, and they [passed](https://dev.azure.com/bioconda/bioconda-recipes/_build/results?buildId=69739&view=results).

**Pull request merged**
