### PR TITLE
matlock new recipe

### PR DESCRIPTION
**Pull request by mictadlo**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by mictadlo** [comment]
Hi @bioconda/core,
I do not know how to recursive clone htslib@af40c73 for it.

Thank you in advance,

Michal

**Comment by dpryan79** [comment]
The most common way this is done is to use `git_url` instead of the regular URL, then you can use the regular git commands to get submodules.

**Comment by mictadlo** [comment]
Hi,
I have got:
```
20:55:04 BIOCONDA DEBUG lint recipes/matlock
	recipe	check	info	fix	output	uses_git_url
0	recipes/matlock	uses_git_url	{'uses_git_url': True, 'fix': 'use tarballs whenever possible', 'output': 'matlock'}	use tarballs whenever possible	matlock	True
Exited with code 1
```
How is it possible to fix it?

Thank you in advance,

Michal

**Comment by dpryan79** [comment]
```
export C_INCLUDE_PATH=${PREFIX}/include
export LIBRARY_PATH=${PREFIX}/lib
```

**Pull request merged**
