### PR TITLE
Add snptools recipe

### PR DESCRIPTION
**Pull request by winni2k**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by dpryan79** [comment]
Does this really need such an ancient samtools? I think the OSX error is due to a random object file not being cleaned up before building.

**Comment by winni2k** [comment]
@dpryan79 Thanks for your input. The short answer is: I don't know. 

Do you happen to know if there is a newer samtools version that does not change behavior/API compared to 0.1.16?

Also, are you implying that the old version of samtools is the cause of the "random object" not being cleared up?

**Comment by dpryan79** [comment]
Do you know if snptools is just running samtools or if it actually tries to link against parts of it? I think 0.1.19 had the same syntax, but I've only been in bioinformatics since about samtools 0.1.18, so can't say with certainty.

**Comment by winni2k** [comment]
It's definitely linking to samtools and tabix: https://github.com/winni2k/snptools/blob/master/makefile#L4

I am very hesitant to bump any versions on this code because it does not come with any tests. However, I have manually tested this exact version extensively.

**Comment by dpryan79** [comment]
yikes

**Comment by winni2k** [comment]
Story of my PhD -,-

**Comment by daler** [comment]
Closing due to inactivity, please re-open if needed.

**Comment by daler** [comment]
Closing due to inactivity, please re-open if needed.

**Comment by daler** [comment]
Closing due to inactivity, please re-open if needed.

**Pull request closed without merging**
