### PR TITLE
Install v1.0.0 deepmicrobes

### PR DESCRIPTION
**Pull request by jayramr**
Describe your pull request here

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by jayramr** [comment]
help needed
"ModuleNotFoundError: No module named 'models'" How to specify this module name?

**Comment by jayramr** [comment]
@BiocondaBot help needed

**Comment by daler** [comment]
Tons of errors in the log about clobbering paths. E.g., 

```
ClobberWarning: This transaction has incompatible packages due to a shared path.
packages: defaults/linux-64::tensorflow-base-1.9.0-gpu_py36h6ecc378_0, conda-forge/linux-64::tensorflow-1.9.0-py36_0
path: 'lib/python3.6/site-packages/tensorflow/include/Eigen/src/Eigenvalues/ComplexSchur.h'
```
So it looks like the defaults channel tensorflow-base is already in the conda-forge package tensorflow. You probably only need the latter.

**Comment by dpryan79** [comment]
The issue is that this (deepmicrobes) isn't written like a python package. It's just a set of scripts and you need to execute it from within the source so the `models` directory is in the import path. Can you ask the authors to restructure this a bit into a normal package so something like `pip install` will work with it? They basically just need a setup.py.

**Comment by jayramr** [comment]
> The issue is that this (deepmicrobes) isn't written like a python package. It's just a set of scripts and you need to execute it from within the source so the `models` directory is in the import path. Can you ask the authors to restructure this a bit into a normal package so something like `pip install` will work with it? They basically just need a setup.py.
Thanks @dpryan79 i will request them.

**Pull request closed without merging**
