### PR TITLE
remove universal binaries for ViennaRNA

### PR DESCRIPTION
**Pull request by s22chan**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [ ] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by s22chan** [comment]
* the flag in configure causes a 1.33-2.00x slowdown (docs say it
interferes with some link-time optimizations)
* the flag is unnecessary since its intent was to bind with Apple's
stock python distribution (rather than conda)

```
echo 'GCGCUUCGCCGCGCGCC&GCGCUUCGCCGCGCGCA\nGCGCUUCGCCGCGCGCC&GCGCUUCGCCGCGCGCA\nGCGCUUCGCCGCGCGCC&GCGCUUCGCCGCGCGCA\nGCGCUUCGCCGCGCGCC&GCGCUUCGCCGCGCGCA\nGCGCUUCGCCGCGCGCC&GCGCUUCGCCGCGCGCA' | time RNAcofold --noPS -p
```

## before ##
RNAcofold --noPS -p  0.02s user 0.00s system 89% cpu 0.030 total

## after ##
RNAcofold --noPS -p  0.01s user 0.00s system 74% cpu 0.022 tota

**Comment by bgruening** [comment]
You need to bump the build/number if you want to trigger a new build and pkg.

**Comment by bgruening** [comment]
ping @s-will 
Thanks!

**Comment by s22chan** [comment]
@s-will Hi, that was a smaller repro string, but for 50k of dimers, we can see execution time drop from 2mins to 1min.

LTO is disabled, so I'm unsure why the generated code is faster (icache? other linker optimizations?)

**Comment by s-will** [comment]
Thanks for the quick response (and of course, many thanks for fixing this---apparently quite significant---issue).
It seems that LTO for ViennaRNA is still deactivated on Mac (due to some other problems) --- maybe @raumzeit has some idea what causes this speedup.

**Comment by s22chan** [comment]
FYI, enabling LTO (or OpenMP) doesn't seem to make RNAcofold or RNAplex run any faster; not sure about other utilities.

**Comment by bgruening** [comment]
Thanks all!

**Pull request merged**
