### PR TITLE
Add SACCHARIS software package

### PR DESCRIPTION
**Pull request by AlexSCFraser**
Adding SACCHARIS 2 software to bioconda.  SACCHARIS is a bioinformatics pipeline to automate phylogenetic analysis of CAZyme families in FASTA sequences, with CLI and GUI interfaces.

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by kbseah** [comment]
hello, i tried removing some of the commented-out lines and `not win` selectors and managed to get the build running locally, at least for Linux. see my fork here: https://github.com/kbseah/bioconda-recipes/tree/saccharis

the package could be built but then fails at the second test:
```
13:19:20 BIOCONDA INFO (OUT) + saccharis -v
13:19:21 BIOCONDA INFO (OUT) SACCHARIS 2.0.0.dev18
13:19:21 BIOCONDA INFO (OUT) + saccharis.make_family_files
13:19:21 BIOCONDA INFO (OUT) Writing default family files to default folder location...
13:19:21 BIOCONDA INFO (OUT) ERROR: 2
13:19:21 BIOCONDA INFO (OUT) Family files could not be written! Check that you have permissions to write to the path.
13:19:21 BIOCONDA INFO (OUT) + saccharis.show_family_categories
13:19:21 BIOCONDA INFO (OUT) Default family category config file not found, creating it...
13:19:21 BIOCONDA INFO (OUT) Writing default family files to default folder location...
13:19:21 BIOCONDA INFO (OUT) ERROR: 2
13:19:21 BIOCONDA INFO (OUT) ERROR: Cannot create default family_categories config file.
13:19:21 BIOCONDA INFO (OUT) Check that you have proper filesystem permissions.
13:19:21 BIOCONDA INFO (OUT) Tests failed for saccharis-2.0.0.dev18-pyh7cba7a3_0.tar.bz2 - moving package to /opt/conda/conda-bld/broken
```
i'm not sure if you're testing the recipes [locally](https://bioconda.github.io/contributor/building-locally.html). if not you could consider doing so for faster iteration on the troubleshooting. 

hope this helps!

**Comment by AlexSCFraser** [comment]
Thanks @kbseah, this helped me getting the tests passing. Looks like the main thing causing that error I was getting were the unneeded commented out lines. Kind of strange, but I'm glad it's solved. The other tests were failing because file system writes either aren't allowed at all or are only allowed in a specific temp folder during the validation pipeline. The docs don't mention how to do disk writes in the test harness so I just disabled those specific tests that write to disk. 

I tried installing the bioconda-utils package installed for local testing, but I can't install it with conda, even in a fresh environment, because it times out the dependency resolver. I saw that this is a known issue and that it's recommended to install mamba when this occurs, but I also failed to install mamba automatically through conda and I'm not sure if I can install mamba without uninstalling conda completely and having to recreate all my environments, which I would rather not set up again.

**Comment by AlexSCFraser** [comment]
@BiocondaBot please add label

**Comment by kbseah** [comment]
Yeah I don't know what's going on with the comment lines, but had a hunch.

Figuring out how to replace conda with mamba is a battle for another day...

Thanks for your contribution!

**Review by kbseah — APPROVED** [review]

**Pull request merged**
