### PR TITLE
Updating abismal to 3.0.0 and falco to 1.0.0

### PR DESCRIPTION
**Pull request by guilhermesena1**
Update abismal to 3.0.0
Update falco to 1.0.0

### CODE REVIEW

**Comment by guilhermesena1** [comment]
@BiocondaBot please update

**Comment by guilhermesena1** [comment]
Done! I also took the liberty to make minor updates on 0811c58 if that's ok.

**Comment by cbrueffer** [comment]
@bioconda-bot please merge

**Comment by cbrueffer** [comment]
Of course!

**Pull request merged**
