### PR TITLE
added bsddb runtime dependency to dudes

### PR DESCRIPTION
**Pull request by pirovc**
- [x] I have read the guidelines above.
- [ ] This PR adds a new recipe.
- [x] This PR updates an existing recipe.
- [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by pirovc** [comment]
I increased the build number. The error is happening in the middle of the run, so the tool was not working before this change in any situation. Should I still create an test to trigger the error? If yes where should I do it?

**Comment by bgruening** [comment]
I just wanted to catch such errors more efficiently, if you need test data or some advanced stuff I will not block this PR. Feel free to merge.

**Comment by pirovc** [comment]
@bgruening How can I merge it? Do I have write access to do it?

**Comment by bgruening** [comment]
In a few minutes you will have.

**Pull request merged**
