### PR TITLE
Update sequana version to 0.7.1

### PR DESCRIPTION
**Pull request by cokelaer**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by cokelaer** [comment]
@dpryan79 
I updated this recipe a few days ago and merged the pull request after the 3 chekcs passed successfully.
It looks like the new compiled version (v0.7.1) are not available on bioconda. When I do a 

    conda search sequana

only version 0.7.0 and below are available. Any ideas ? thanks

**Comment by dpryan79** [comment]
Hmm, odd, I'll have a look.

**Comment by dpryan79** [comment]
@cokelaer Sequana is currently in the blacklist, so remove it in a new PR and hopefully everything will pass.

**Comment by cokelaer** [comment]
? do you happen to know why it is blacklisted by any chance ?

**Comment by dpryan79** [comment]
I don't, there's no associated comment in the blacklist. I recall trying to get it out of the blacklist at some point and failing, but not the details of why. Just remove it from the blacklist in a PR and perhaps whatever the reason was for the old build failing is now resolved in the new version.

**Comment by cokelaer** [comment]
okay, I've created a new pull/build request https://github.com/bioconda/bioconda-recipes/pull/10886

**Pull request merged**
