### PR TITLE
Add recipe for version 1.9 of the affy2vcf bcftools plugin

### PR DESCRIPTION
**Pull request by gregvonkuster**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by dpryan79** [comment]
@gregvonkuster Try adding the following to `build.sh`:

    C_INCLUDE_PATH=${PREFIX}/include
    CPP_INCLUDE_PATH=${PREFIX}/include
    CXX_INCLUDE_PATH=${PREFIX}/include
    CPLUS_INCLUDE_PATH=${PREFIX}/include
    LIBRARY_PATH=${PREFIX}/lib

That should fix many of the issues.

**Comment by gregvonkuster** [comment]
Thanks very much for your help on this @dpryan79 - so much appreciated!

**Comment by gregvonkuster** [comment]
Not sure why tests are not running, can someone please trigger them?  I believe this recipe should now successfully pass tests.  Thanks!!

**Comment by dpryan79** [comment]
I wonder if we hit a github API rate limit or something. Maybe try closing and reopening?

**Comment by gregvonkuster** [comment]
@dpryan79 Do you mean the PR?

**Comment by dpryan79** [comment]
Yes, that at least used to work (no clue if it still does).

**Pull request closed without merging**
