### PR TITLE
Recipe for "Feht"

### PR DESCRIPTION
**Pull request by hellothisisMatt**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

Instead of using the source code, I used the pre-compiled binary executable. There seems to be a missing file in the source code that is causing errors when building it. The drawback of using the executable is that `feht` won't be usable on OSX.

### CODE REVIEW

**Comment by hellothisisMatt** [comment]
As mentioned above, this is using the precompiled executable as there is an issue with building from source. This will be fixed in the next release of `feht` where the recipe will be updated.

**Comment by bgruening** [comment]
@hellothisisMatt can you please report this issue upstream, so that they can fix it?

**Comment by hellothisisMatt** [comment]
@bgruening I've let the author know should be fixed in the next iteration.

**Comment by bgruening** [comment]
Thanks

**Pull request merged**
