### PR TITLE
Prevent blast from phoning home

### PR DESCRIPTION
**Pull request by dpryan79**
Apparently blast, by default, reports back many of its usage parameters. We need to (A) test if that actually happens and (B) prevent it from happening regardless.

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by dpryan79** [comment]
I want to do a little testing with the build artifact, thus the "OMGWTFBBQ"...

**Comment by pmenzel** [comment]
AFAIK, it does that from version 2.10 onward.

I only noticed, because the program took some time to terminate due to the timeout of the phone-home call, which was blocked by the firewall.

**Comment by dpryan79** [comment]
@pmenzel Thanks! I had read 2.11 online, good to know that 2.10 may have been affected as well. I've sent NCBI a not-so-happy email about this :)

**Comment by dpryan79** [comment]
@pmenzel According to the reply I got from NCBI 2.11 is the first release with this "feature".

**Comment by pmenzel** [comment]
ok, thanks for making trouble at NCBI! :-)

**Comment by dpryan79** [comment]
I am nothing if not a trouble maker :P

**Pull request merged**
