### PR TITLE
Update unifrac to 1.1.0

### PR DESCRIPTION
**Pull request by wasade**
Updates unifrac to 1.1.0, depends on #33956

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by dpryan79** [comment]
FYI, we don't build with pypy, so there's no need to explicitly skip it. If you see it mentioned in the logs then that means there was some resolution failure.

**Comment by dpryan79** [comment]
I think the issue here is a bioconda-utils bug and I think I've tracked down the cause. I'm pushing out a new bioconda-utils version to try and tackle this.

**Comment by wasade** [comment]
Thank you, @dpryan79!!

**Comment by dpryan79** [comment]
FYI, I've looked further into the original issue here. After packages are built in the docker container the outputs are copied out back to the file system. We get the list of files to copy out using `conda build ...stuff... --output` to get a list of the output files. It seems there's a bug in conda-build related to this and the `pin_compatible` stuff is screwing up the parsing. That obviously shouldn't happen, so I'll push this issue upstream to Anaconda. In the interim, I think we can replace all of this with a much simpler manner of getting the output package names.

**Comment by wasade** [comment]
@dpryan79, it sounds like this PR has really lead to quite the investigation -- thank you for the update, and for all of your help, I really appreciate it!

**Comment by wasade** [comment]
@dpryan79, the [failure](https://dev.azure.com/bioconda/bioconda-recipes/_build/results?buildId=14854&view=logs&j=e14e69ff-a0ae-55c4-b71d-229b239cfb2f&t=7df82132-b284-504b-53d6-7d3e63519572&l=2044) now looks like it's within unifrac. I'm examining it right now

**Comment by dpryan79** [comment]
At least we're past the previous issue now :)

**Comment by wasade** [comment]
Most definitely :) 

It seems our build matrix was not sufficiently comprehensive, and after adjusting, I'm able to recreate a similar issue. Unfortunately, it suggests there may be a need for dependency pinning, or updates to `unifrac-binaries`, unsure just yet. I will definitively resolve it within the project first before issuing further commits here. Thank you again for all the help!!

**Comment by dpryan79** [comment]
Awesome, thanks for the updates @wasade !

**Comment by wasade** [comment]
@dpryan79, these pins seem to [work](https://github.com/biocore/unifrac/runs/5998101868?check_suite_focus=true) upstream for python 3.6 - 3.10. I'm hoping to relax at least the `biom-format` pin but I want to get back to a position of green before fine tuning. I suspect right now that some problems are being introduced by `biom-format` coming from conda-forge, and having been built against its hdf5/h5py stack. `biom-format` should be in bioconda anyway so I might just get it added for good measure.

**Comment by wasade** [comment]
@dpryan79, I've so far been unsuccessful removing the pin on `biom-format`. I've been examining the dependencies between successful/unsuccessful builds and the differences are not yet illuminating. If this is alright with you, what I propose is that we merge this recipe so that `unifrac=1.1.0` is available, and at a later time once I sort out biom-format / unifrac issue, I will increment the build on this package to remove the pin. Does that sound reasonable?

**Comment by wasade** [comment]
Excellent!!! Looks like we're green! 

@BiocondaBot please add label

**Comment by wasade** [comment]
@BiocondaBot please add label

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@BiocondaBot please merge

**Comment by wasade** [comment]
This is one of those PRs that feels really good to see merged... thank you again @dpryan79!

**Pull request merged**
