### PR TITLE
Update mlst to 2.11

### PR DESCRIPTION
**Pull request by tseemann**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [x] This PR does something else (explain below).

Also removes it from blacklist.

### CODE REVIEW

**Comment by druvus** [comment]
@tseemann mlst is currently blacklisted. You need to remove it from the `build-fail-blacklist` file. Still some perl dependencies (i.e. bioperl and deps) that needs to be rebuilt before it will pass.

**Comment by tseemann** [comment]
@druvus i don't understand what any of that means. is there any documentation? i was surprised when it downgraded my Perl to 5.22 from 5.26.  Is this because of the modules it uses?  Some of those are core models and shouldn't be conda packages anyway.  @Slugger70 ?

**Comment by corburn** [comment]
@tseemann bioconda was updated recently updated to [use conda 3](https://github.com/bioconda/bioconda-recipes/issues/9404). To expedite the transition, some problematic recipes were put on a [blacklist](https://github.com/bioconda/bioconda-recipes/blob/8eae705b3740499ee67ffed3c3130be1d8426d83/build-fail-blacklist#L2134) until their particular issues were resolved. In your pull request, you will need to remove your recipe from the [blacklist](https://github.com/bioconda/bioconda-recipes/blob/8eae705b3740499ee67ffed3c3130be1d8426d83/build-fail-blacklist#L2134) so it will build. I do not know anything about the perl issue.

**Comment by tseemann** [comment]
Thanks @corburn - i'm guessing it was a perl dep that was the cause of the blacklist.

**Pull request merged**
