### PR TITLE
Try to fix sphingo build

### PR DESCRIPTION
**Pull request by kyleabeauchamp**
* [ ] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [ ] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by kyleabeauchamp** [comment]
Hmm, the program doesn't seem to read in the ENV variables in the makefile: https://github.com/GuyAllard/SPINGO/blob/master/source/makefile

**Comment by bgruening** [comment]
Have you tried if `boost-cpp` helps here?

**Comment by kyleabeauchamp** [comment]
still no dice, may want to add to blacklist :(

**Comment by kyleabeauchamp** [comment]
See https://github.com/bioconda/bioconda-recipes/pull/9481

**Pull request closed without merging**
