### PR TITLE
add plink v1

### PR DESCRIPTION
**Pull request by elilarson**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

Hi,
Can you add this plink recipe to the master branch please ?
All the travis-ci build tests pass when the master branch is correctly merged into my plink branch.
Thanks,
Elise

### CODE REVIEW

**Comment by bgruening** [comment]
@elilarson thanks for your contribution. It seems there are some problems with openblas. I tried to pin the version. Let's see if this helps.

**Comment by elilarson** [comment]
Thanks @bgruening 

But the big problem is the linux docker travis-ci build behaviour :

When we push a change into my git plink branch without merging the master branch into this plink branch before, then the travis-ci linux build (using docker) failed because it starts by running a 'FETCH', then the script build.sh (make) run before the installation of the dependencies from meta.yaml...
That's why there is a problem of lib (openblas) because it is not installed before the execution of the build.sh script (make).

To resolve this behaviour problem, we have to run the next commands (as suggested here : https://bioconda.github.io/contribute-a-recipe.html#push-changes-wait-for-tests-to-pass-submit-pull-request) :
$ git checkout <myrecipe>
$ git fetch upstream
$ git checkout master
$ git merge upstream/master
$ git checkout <myrecipe>
$ git merge master
$ git push origin <myrecipe>

Tomorrow, this procedure cause the travis-ci linux docker build to be successful into my plink branch https://travis-ci.org/elilarson/bioconda-recipes. The dependencies of the meta.yaml file were indeed installed before the build.sh (make) procedure of the recipe.
But unfortunately, the travis-ci build of the pull request failed because of a problem of travis VM initialization (not a problem due to the recipe)

**Comment by elilarson** [comment]
The merging of master branch into plink branch is again successfull : 
 https://travis-ci.org/elilarson/bioconda-recipes
@bgruening you can now try to restart the travis build of this pull request.

**Comment by elilarson** [comment]
@bgruening 
I fix the problem by removing the rpath specification in $LDFLAGS. 
It was not correctly interpreted inside the linux travis build.

**Comment by bgruening** [comment]
Cool! Thanks @elilarson!

**Pull request merged**
