### PR TITLE
Pcre

### PR DESCRIPTION
**Pull request by sebastian-luna-valero**
* [X] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

Please @bioconda/core review this recipe

The recipe on the [default channel](https://anaconda.org/anaconda/pcre) has not been compiled with the `--enable-utf` option.

### CODE REVIEW

**Comment by johanneskoester** [comment]
How urgent is this? If not that urgent, you could submit a PR to conda-recipes instead, so that the default package is updated... What do you think?

**Comment by sebastian-luna-valero** [comment]
Many thanks!

This is not urgent but I am happy to submit a PR to conda-recipes if that is the best option. However, neither:
https://github.com/ContinuumIO/anaconda-recipes  [package not there]

nor 
https://github.com/conda/conda-recipes [version do not match]

are the repositories you are referring to, am I right?

Could you please point me to the correct repository?

Best regards,
Sebastian.

**Comment by johanneskoester** [comment]
I would think its conda-recipes. As far as I know, this is the place to propose or update packages in the default channel. Even if the version does not match.

**Comment by sebastian-luna-valero** [comment]
Many thanks!

Here is the PR for our reference:
https://github.com/conda/conda-recipes/pull/674

**Comment by jakirkham** [comment]
@johanneskoester @sebastian-luna-valero, we have [`pcre`]( https://github.com/conda-forge/pcre-feedstock ) in [conda-forge]( http://conda-forge.github.io/ ). Would welcome PRs there. 😄

**Comment by bgruening** [comment]
PR against conda-forge would be great indeed. @jakirkham the problem for us is that we can not depend on conda-forge until we figured out the GCC issue. We would love to migrate a few repositories into the more general conda-forge repo.

Can we prioritise it? Google- hangout to discuss it further?

**Comment by jakirkham** [comment]
Basically, yes. Responded to you in this PR ( https://github.com/bioconda/bioconda-recipes/pull/1388#issuecomment-219223779 ) though.

**Comment by sebastian-luna-valero** [comment]
Many thanks All, happy to close this PR as there is a better recipe already at conda-forge for pcre. @jakirkham congratulations for your great work!

I will bear this in mind next time a submit a recipe for a general purpose package.

**Comment by marcelm** [comment]
As @sebastian-luna-valero said, this PR should be closed, right?

**Comment by johanneskoester** [comment]
Indeed :-)

**Pull request closed without merging**
