### PR TITLE
Update last to 847

### PR DESCRIPTION
**Pull request by mworkentine**
* [x] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

This updates last to version 847.  Required a new patch for python 2 to 3 conversion of maf-convert.

### CODE REVIEW

**Comment by mworkentine** [comment]
@bioconda/core As this is my first PR to bioconda a look over would be appreciated!

**Comment by bgruening** [comment]
Looks good to me! Do you know if we can get this patch upstream?

**Comment by mworkentine** [comment]
Do you mean for future version updates?

**Comment by bgruening** [comment]
Yes. Would be nice to get these great patches upstream. Feel free to merge.

**Comment by mworkentine** [comment]
It could be incorporated in the build script instead of as a patch.  I used `futurize` from the `future` package.

**Pull request merged**
