### PR TITLE
Update rust to version 1.18.0

### PR DESCRIPTION
**Pull request by jvhaarst**
* [*] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [*] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by jvhaarst** [comment]
The build fails on OSX with this error:
`error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: changing install names or rpaths can't be redone for: /anaconda/conda-bld/rust_1499161306531/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/rustlib/x86_64-apple-darwin/lib/libterm-95ba05952512bff3.dylib (for architecture x86_64) because larger updated load commands do not fit (the program must be relinked, and you may need to use -headerpad or -headerpad_max_install_names)
`

This doesn't look like something I can fix in the recipe, especially as the Linux version passed the tests.

**Comment by jerowe** [comment]
This looks really cool, but it would be better in the conda forge channel. Have you given it a try over there?

**Comment by dlaehnemann** [comment]
There is an attempt at this in the conda channel, now:
https://github.com/conda-forge/staged-recipes/pull/3254

Just in case you want to close this pull request.

**Comment by jvhaarst** [comment]
Taken over by https://github.com/conda-forge/staged-recipes/pull/3254

**Pull request closed without merging**
