### PR TITLE
Update Kaiju to 1.4.4, add OSX build.

### PR DESCRIPTION
**Pull request by acaprez**
* [X] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [X] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

ping @bioconda/core since this is a non-standard OS X build.

Building this with `clang` requires a minimum `MACOSX_DEPLOYMENT_TARGET` of 10.9, which I believe we don't want to do for compatibility reasons.  Building with GCC on OS X works fine, but I wanted to confirm that's ok to do.

### CODE REVIEW

**Comment by johanneskoester** [comment]
That's fine. But are you sure it really uses the gcc dependency for building? I ask because there is a gcc alias for clang on OSX and I have seen before that although gcc was specified as a dependency and should come first in the $PATH, clang was used.

**Comment by acaprez** [comment]
I can confirm it does on my local OSX VM.  If needed, I can tweak the build script to be more explicit.  Also, I edited my first comment - it will work with `MACOSX_DEPLOYMENT_TARGET=10.9`.  So I guess my question is which way is preferable - 1) use GCC -or- 2) use `clang` and set `MACOSX_DEPLOYMENT_TARGET=10.9`?

**Comment by bgruening** [comment]
GCC is completely fine with me.

**Comment by johanneskoester** [comment]
I agree. Use gcc.

**Pull request merged**
