### PR TITLE
Add mavis, a tool for post-processing of structural variant calls.

### PR DESCRIPTION
**Pull request by cbrueffer**
Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it. Note that if you are not already a member of the bioconda project (meaning that you can't add this label), please ping `@bioconda/core` so that your PR can be reviewed and merged (please note if you'd like to be added to the bioconda project). Please see https://github.com/bioconda/bioconda-recipes/issues/15332 for more details.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by cbrueffer** [comment]
I'll add the missing packages to conda-forge.

**Comment by cbrueffer** [comment]
Thanks; I think the conda errors/warnings about shadowed paths distracted me from the actual error...

**Comment by dpryan79** [comment]
It doesn't help that the setup.py for this is causing a problematic module to be installed :(

**Comment by dpryan79** [comment]
Eesh, this release is a mess.

**Comment by dpryan79** [comment]
I don't know why it's skipping the tools module. Regardless we should probably report the installation issues upstream, since the authors should really fix their package.

**Comment by cbrueffer** [comment]
There's a typo in your last commit, should be `__init__.py`, fixing...

**Comment by dpryan79** [comment]
Guess it's getting late :P

**Comment by cbrueffer** [comment]
Indeed! Works now, thanks for the help!

**Comment by cbrueffer** [comment]
I'll report the issues upstream.

**Comment by dpryan79** [comment]
Great, merge at your discretion :)

**Pull request merged**
