### PR TITLE
update salmon

### PR DESCRIPTION
**Pull request by rob-p**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by rob-p** [comment]
It looks like the issue is due to the usage of `thread_local` in the Fasta Parser on OSX.  Travis says this is "not supported on the current target".  However, `thread_local` is a simple C++11 feature.  What exactly is the config being used to do the CI testing on OSX?

**Comment by jerowe** [comment]
@bioconda/osx, any ideas?

**Comment by mbargull** [comment]
Looks like a newer version of `clang` is needed: https://stackoverflow.com/a/29929949.
Will a build dependency on `clangdev` let us use a newer one?

**Comment by rob-p** [comment]
A newer version of clang would be ideal.  I could remove the thread_local specifier for those variables all together, but that could have an adverse effect on performance.

**Comment by mbargull** [comment]
Without knowing the code (/performance critical paths), I'd also rather avoid the patch, yes. Maybe try adding `clangdev  # [osx]` as build requirement. Not sure if we'd need an additional
```bas
if [[ "$(uname)" == Darwin ]]; then
    CC=clang
    CXX=clang++
fi
```
or something in `build.sh` or if `CXX` is `clang++` anyway. Not sure though if there are any other implications by not using the default `clang`. (And I know next to nothing of macOS -- that's that fancy pear-logoed system, right?! :P)

**Comment by rob-p** [comment]
@mbargull ,

  Simply adding `clangdev # [osx]` doesn't seem to work.  Is there some other way to force a different clang version during the CI build?

**Comment by mbargull** [comment]
Maybe try adding 
```bash
if [[ "$(uname)" == Darwin ]]; then
    CC=clang
    CXX=clang++
fi
```
to the top of `build.sh`. Alternatively there are also some `cmake` parameters with which those can be set, but I don't them from the top of my head.

**Comment by rob-p** [comment]
But its building using clang, even without the llvmdev dependency.  The issue is that i need a newer version of clang (apple clang 8 or later).

**Comment by mbargull** [comment]
Yes, but it's picking up the default one, see: https://travis-ci.org/bioconda/bioconda-recipes/jobs/306930733#L325.
If you use `clangdev` as a build dependency AND set `CC`/`CCX` in `build.sh`, it should pick the newer `clang`/`clang++` from the build environment.

**Comment by rob-p** [comment]
Ok, ill give that a try. Thanks!

**Comment by rob-p** [comment]
Still doesnt seem to force the use of a newer clang.  Is there a specific path or env variable i can use to set clang as the new one instead of the ild one?

**Comment by mbargull** [comment]
Argh, I'm a dummy and forgot the `export`, sorry! Use the following instead:
```bash
if [[ "$(uname)" == Darwin ]]; then
    export CC=clang
    export CXX=clang++
fi
```

**Comment by rob-p** [comment]
Sighh, this seems to lead to quite a different error (now it dies due to failure to include a header in Jellyfish --- `<new>`).

**Comment by mbargull** [comment]
> Sighh

Indeed...
The error meant that it couldn't find the standard library header. I pushed a commit that added `libcxx` to the dependencies and uses the same version for `clangdev` to have them synchronized.

**Comment by rob-p** [comment]
W00t, the patch seems to work.  Awesome! Thanks for all the help!

**Comment by mbargull** [comment]
Nice, glad to hear that!

**Pull request merged**
