### PR TITLE
new recipe: (tf-)modisco

### PR DESCRIPTION
**Pull request by visze**
:information_source:
If this is your first pull request to Bioconda please ping `@bioconda/core` so it can be reviewed and to request being added as a member of the Bioconda team. Members of the Bioconda team are able to merge their own pull requests once tests and linting have passed.

----------------

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by jenzopr** [comment]
The setup is not allowed to download extra requirements, you'll need to add them to the `run:` section: `tensorflow>=1.7` and `tensorflow-gpu>=1.7`

**Comment by jenzopr** [comment]
Sorry @visze the CI configuration is out of date. Merge in master with `git merge master` and commit again ;-)

**Comment by daler** [comment]
Closing due to inactivity, please re-open if needed.

**Comment by daler** [comment]
Closing due to inactivity, please re-open if needed.

**Comment by daler** [comment]
Closing due to inactivity, please re-open if needed.

**Pull request closed without merging**
