### PR TITLE
install easel for hmmer

### PR DESCRIPTION
**Pull request by ola-t**
Following suggestions on https://github.com/BioContainers/containers/issues/250

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR updates an existing recipe.

cc: @mscheremetjew

### CODE REVIEW

**Comment by jpuritz** [comment]
https://github.com/ola-t/bioconda-recipes/blob/0cbc024d956a78a601890b6f0c4df1170a3f7ac4/build-fail-blacklist#L1682
https://github.com/ola-t/bioconda-recipes/blob/0cbc024d956a78a601890b6f0c4df1170a3f7ac4/build-fail-blacklist#L1731

**Comment by ola-t** [comment]
There seems to be an issue with linking in the build, how to fix that?

**Comment by ola-t** [comment]
Some updates were already done in https://github.com/bioconda/bioconda-recipes/pull/9711

**Comment by jpuritz** [comment]
Please increase the build numbers for both.

**Comment by bgruening** [comment]
Thanks!

**Comment by ola-t** [comment]
@bgruening could I check when we could start using docker container listed in https://bioconda.github.io/recipes/hmmer/README.html ?

**Comment by bgruening** [comment]
Give it a few minutes, as soon as the CI system has rebuild the pkgs the new containers should be published as well.
Monitor this site: https://quay.io/repository/biocontainers/hmmer?tab=tags

**Comment by mscheremetjew** [comment]
New containers are available and have been tested on our end. All works nicely. Many Thanks to all of you!

**Pull request merged**
