### PR TITLE
Py2app 0.10

### PR DESCRIPTION
**Pull request by acaprez**
* [X] I have read the guidelines above.
* [X] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

Add recipe for py2app and its dependencies.

### CODE REVIEW

**Comment by johanneskoester** [comment]
@acaprez the recipes summaries sound like they are not particularly Bioinformatics related. Am I right? If so, this is better suited for conda-forge. Since we depend on conda-forge now, we should try to put all general stuff into conda-forge.

**Comment by acaprez** [comment]
They're dependencies for the NCBI gdc-client package I've been working on.  I can add them to conda-forge instead, sure.  Do you happen to know - when you contribute a package there, are you required to list yourself as the maintainer?  That wasn't 100% clear to me from their docs.

**Comment by johanneskoester** [comment]
I am not sure either. You can try without and see what they say when they review it.

**Comment by acaprez** [comment]
Ok, I'll close this PR then and try to add them to conda-forge instead.

**Comment by johanneskoester** [comment]
Thank you! And sorry for the inconvenience.

**Pull request closed without merging**
