### PR TITLE
Added recipe for DNABarcodes

### PR DESCRIPTION
**Pull request by ArneKr**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by bgruening** [comment]
@ArneKr wait a little bit with merging, I'm concerned about our CI :)

**Comment by ArneKr** [comment]
@bgruening Sorry, I saw this a little bit late. I have stopped now.

**Comment by ArneKr** [comment]
@bgruening Did anything go wrong?

**Comment by ArneKr** [comment]
Should I slow down with the merging?

**Comment by bgruening** [comment]
A little bit, but it seems to scale well. Just follow https://anaconda.org/bioconda and see how you packages arrive. Feel free to merge as you like.

**Comment by mbargull** [comment]
You can also see the CI status on https://circleci.com/gh/bioconda (where you can also click on "My builds" on the top right to filter them). Linux builds keep up fine, with macOS there is less capacity/parallelism available, hence they take a little longer. But "keep 'em coming" once the queue is a little shorter.
(@bgruening: If you at some point think it doesn't scale enough anymore, a possibility would be to merge @ArneKr's branches into a new (arbitrarily named) branch from which you could then merge into `bulk`. But I guess, let's just see how it goes.)
@ArneKr: If you don't have time to check the build status, another possibility would be to just open the PRs which someone that monitors the status can merge then at some point.
And BTW, you have to be cautious about https://github.com/bioconda/bioconda-recipes/graphs/contributors?type=c -- otherwise you might become the top contributor/committer more quickly than you would've thought 😉

**Comment by mbargull** [comment]
The ones with the HTTP error will need to be fixed manually (they just updated the package on Bioconductor and removed the old version apparently...).
But don't worry about the other ones with `Unexpected environment preparation error: VM creation failed`. There is nightly job that will pick them up.

**Pull request merged**
