### PR TITLE
Update metagenome-atlas to 2.6a3

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`metagenome-atlas`](https://bioconda.github.io/recipes/metagenome-atlas/README.html): **2.6a2** &rarr; **2.6a3**

[install with bioconda](http://bioconda.github.io/recipes/metagenome-atlas/README.html) [Conda](https://anaconda.org/bioconda/metagenome-atlas/files)

Info | Link
-----|-----
Recipe | [`recipes/metagenome-atlas`](https://github.com//bioconda/bioconda-recipes/tree/bump/metagenome_atlas/recipes/metagenome-atlas) (click to view/edit other files)
Releases |[https://github.com/metagenome-atlas/atlas/tags](https://github.com/metagenome-atlas/atlas/tags)
Recipe Maintainer(s) | @silask
Author | `@metagenome-atlas`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Review by SilasK — APPROVED** [review]

**Comment by SilasK** [comment]
@bioconda/core This simple update fails because the build takes too long or uses too much memory. Is there anything I can do?

**Comment by dpryan79** [comment]
@SilasK Try restricting version ranges of some of the dependencies.

**Comment by SilasK** [comment]
Should I constrain more or less?

**Comment by SilasK** [comment]
Now I don't understand the log:

```
12:50:26 BIOCONDA INFO BUILD START recipes/metagenome-atlas
12:50:26 BIOCONDA INFO (COMMAND) docker run -t --net host --rm -v /tmp/tmp5123wnj2/build_script.bash:/opt/build_script.bash -v /home/circleci/project/miniconda/conda-bld/:/opt/host-conda-bld -v /home/circleci/project/recipes/metagenome-atlas:/opt/recipe -e LANG=en_US.UTF-8 -e HOST_USER_ID=1001 quay.io/bioconda/bioconda-utils-build-env-cos7:0.17.8 /bin/bash /opt/build_script.bash
12:50:26 BIOCONDA INFO (ERR) Unable to find image 'quay.io/bioconda/bioconda-utils-build-env-cos7:0.17.8' locally
12:50:26 BIOCONDA INFO (ERR) 0.17.8: Pulling from bioconda/bioconda-utils-build-env-cos7
12:50:26 BIOCONDA INFO (ERR) 2d473b07cdd5: Pulling fs layer
12:50:26 BIOCONDA INFO (ERR) 7d0d48906141: Pulling fs layer
12:50:26 BIOCONDA INFO (ERR) ec7726195138: Pulling fs layer
12:50:26 BIOCONDA INFO (ERR) 8e298249fa45: Pulling fs layer
12:50:26 BIOCONDA INFO (ERR) 8e298249fa45: Waiting
12:50:27 BIOCONDA INFO (ERR) ec7726195138: Verifying Checksum
12:50:27 BIOCONDA INFO (ERR) ec7726195138: Download complete
12:50:28 BIOCONDA INFO (ERR) 2d473b07cdd5: Verifying Checksum
12:50:28 BIOCONDA INFO (ERR) 2d473b07cdd5: Download complete
12:50:31 BIOCONDA INFO (ERR) 8e298249fa45: Verifying Checksum
12:50:31 BIOCONDA INFO (ERR) 8e298249fa45: Download complete
12:50:34 BIOCONDA INFO (ERR) 2d473b07cdd5: Pull complete
12:50:34 BIOCONDA INFO (ERR) 7d0d48906141: Download complete
12:50:56 BIOCONDA INFO (ERR) 7d0d48906141: Pull complete
12:50:57 BIOCONDA INFO (ERR) ec7726195138: Pull complete
12:51:10 BIOCONDA INFO (ERR) 8e298249fa45: Pull complete
12:51:10 BIOCONDA INFO (ERR) Digest: sha256:31a8c344497c1918620f55b61c2f3a58a771b9d8735bef4ab48b3328520658f6
12:51:10 BIOCONDA INFO (ERR) Status: Downloaded newer image for quay.io/bioconda/bioconda-utils-build-env-cos7:0.17.8
12:51:11 BIOCONDA INFO (OUT) /opt/conda/lib/python3.7/site-packages/conda_build/cli/main_build.py:383: UserWarning: RECIPE_PATH received is a file. File: /opt/recipe/meta.yaml
12:51:11 BIOCONDA INFO (OUT) It should be a path to a folder.
12:51:11 BIOCONDA INFO (OUT) Forcing conda-build to use the recipe file.
12:51:11 BIOCONDA INFO (OUT)   UserWarning
12:51:11 BIOCONDA INFO (OUT) No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.16
12:51:11 BIOCONDA INFO (OUT) WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.16
12:51:11 BIOCONDA INFO (OUT) Adding in variants from internal_defaults
12:51:11 BIOCONDA INFO (OUT) INFO:conda_build.variants:Adding in variants from internal_defaults
12:51:11 BIOCONDA INFO (OUT) Adding in variants from /opt/host-conda-bld/conda_build_config_0_-e_conda_build_config.yaml
12:51:11 BIOCONDA INFO (OUT) INFO:conda_build.variants:Adding in variants from /opt/host-conda-bld/conda_build_config_0_-e_conda_build_config.yaml
12:51:11 BIOCONDA INFO (OUT) Adding in variants from /opt/host-conda-bld/conda_build_config_1_-e_bioconda_utils-conda_build_config.yaml
12:51:11 BIOCONDA INFO (OUT) INFO:conda_build.variants:Adding in variants from /opt/host-conda-bld/conda_build_config_1_-e_bioconda_utils-conda_build_config.yaml
12:51:11 BIOCONDA INFO (OUT) Attempting to finalize metadata for metagenome-atlas
12:51:11 BIOCONDA INFO (OUT) INFO:conda_build.metadata:Attempting to finalize metadata for metagenome-atlas
.12:52:25 BIOCONDA INFO (OUT) Collecting package metadata (repodata.json): ...working... done
.12:52:29 BIOCONDA INFO (OUT) Solving environment: ...working... done
12:52:43 BIOCONDA INFO (OUT) Collecting package metadata (repodata.json): ...working... done
12:52:55 BIOCONDA INFO (OUT) Solving environment: ...working... done
12:52:55 BIOCONDA INFO (OUT) BUILD START: ['metagenome-atlas-2.6a3-pyhdfd78af_0.tar.bz2']
12:53:07 BIOCONDA INFO (OUT) Collecting package metadata (repodata.json): ...working... done
12:53:19 BIOCONDA INFO (OUT) Solving environment: ...working... done
12:53:19 BIOCONDA INFO (OUT) 
12:53:19 BIOCONDA INFO (OUT) ## Package Plan ##
12:53:19 BIOCONDA INFO (OUT) 
12:53:19 BIOCONDA INFO (OUT)   environment location: /opt/conda/conda-bld/metagenome-atlas_1629204671208/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh
12:53:19 BIOCONDA INFO (OUT) 
12:53:19 BIOCONDA INFO (OUT) 
12:53:19 BIOCONDA INFO (OUT) The following NEW packages will be INSTALLED:
12:53:19 BIOCONDA INFO (OUT) 
12:53:19 BIOCONDA INFO (OUT)     _libgcc_mutex:    0.1-conda_forge             conda-forge
12:53:19 BIOCONDA INFO (OUT)     _openmp_mutex:    4.5-1_gnu                   conda-forge
12:53:19 BIOCONDA INFO (OUT)     ca-certificates:  2021.5.30-ha878542_0        conda-forge
12:53:19 BIOCONDA INFO (OUT)     ld_impl_linux-64: 2.36.1-hea4e1c9_2           conda-forge
12:53:19 BIOCONDA INFO (OUT)     libffi:           3.3-h58526e2_2              conda-forge
12:53:19 BIOCONDA INFO (OUT)     libgcc-ng:        11.1.0-hc902ee8_8           conda-forge
12:53:19 BIOCONDA INFO (OUT)     libgomp:          11.1.0-hc902ee8_8           conda-forge
12:53:19 BIOCONDA INFO (OUT)     libstdcxx-ng:     11.1.0-h56837e0_8           conda-forge
12:53:19 BIOCONDA INFO (OUT)     ncurses:          6.2-h58526e2_4              conda-forge
12:53:19 BIOCONDA INFO (OUT)     openssl:          1.1.1k-h7f98852_1           conda-forge
12:53:19 BIOCONDA INFO (OUT)     pip:              21.2.4-pyhd8ed1ab_0         conda-forge
12:53:19 BIOCONDA INFO (OUT)     python:           3.7.10-hffdb5ce_100_cpython conda-forge
12:53:19 BIOCONDA INFO (OUT)     python_abi:       3.7-2_cp37m                 conda-forge
12:53:19 BIOCONDA INFO (OUT)     readline:         8.1-h46c0cb4_0              conda-forge
12:53:19 BIOCONDA INFO (OUT)     setuptools:       57.4.0-py37h89c1867_0       conda-forge
12:53:19 BIOCONDA INFO (OUT)     sqlite:           3.36.0-h9cd32fc_0           conda-forge
12:53:19 BIOCONDA INFO (OUT)     tk:               8.6.10-h21135ba_1           conda-forge
12:53:19 BIOCONDA INFO (OUT)     wheel:            0.37.0-pyhd8ed1ab_1         conda-forge
12:53:19 BIOCONDA INFO (OUT)     xz:               5.2.5-h516909a_1            conda-forge
12:53:19 BIOCONDA INFO (OUT)     zlib:             1.2.11-h516909a_1010        conda-forge
12:53:19 BIOCONDA INFO (OUT) 
.12:53:28 BIOCONDA INFO (OUT) Preparing transaction: ...working... done
12:53:29 BIOCONDA INFO (OUT) Verifying transaction: ...working... done
12:53:35 BIOCONDA INFO (OUT) Executing transaction: ...working... done
12:53:48 BIOCONDA INFO (OUT) Collecting package metadata (repodata.json): ...working... done

Exited with code exit status 1
CircleCI received exit code 1
```
Do I need to use pyhton 3.8? 

@bioconda/core This simple update fails because the build takes too long or uses too much memory. Is there anything I can do?

**Comment by SilasK** [comment]
@BiocondaBot update

**Review by SilasK — CHANGES_REQUESTED** [review]
I have to figure out a combination of version requirements that work and then these if my tool runs with this

**Comment by SilasK** [comment]
@BiocondaBot update

**Pull request closed without merging**
