### PR TITLE
Use sed from git

### PR DESCRIPTION
**Pull request by nsoranzo**
* [x] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

Sandboxing patch has been upstreamed.

### CODE REVIEW

**Comment by bgruening** [comment]
PR number 3000!!!!

**Comment by bgruening** [comment]
autoconf and rsync is missing? Why rsync, Oo.

**Comment by nsoranzo** [comment]
> autoconf and rsync is missing? Why rsync, Oo.

@bgruening I'm adding autoconf and automake to the build requirements. I'll try to remove rsync from sed's `bootstrap.conf`, then `./bootstrap` should fall back to wget.

**Comment by nsoranzo** [comment]
automake has the same shebang problem of texinfo: https://travis-ci.org/bioconda/bioconda-recipes/jobs/177031115#L534

**Comment by bgruening** [comment]
`gnu_wget` is missing and rsync is still missing :(

**Comment by nsoranzo** [comment]
rsync shouldn't be needed when I'll add gnu_wget (likely on Monday).

**Comment by nsoranzo** [comment]
gnu-wget added, now 3 builds out of 4 are green, no clue what's happening under OSX in https://travis-ci.org/bioconda/bioconda-recipes/jobs/177191097#L2870

**Comment by nsoranzo** [comment]
@bgruening I don't think the problem is the perl requirement, it should be installed anyway as it is a run requirement for texinfo. Actually it made fail the Linux build too!

**Comment by bgruening** [comment]
:( then I have no idea? Can we skip the man page generation?

**Comment by nsoranzo** [comment]
@bgruening I think man page creation is failing because it is trying to run `sed/sed` which is not properly compiled/linked.
I disabled man page creation and now I get https://travis-ci.org/bioconda/bioconda-recipes/jobs/177610710#L2967

**Comment by bgruening** [comment]
@nsoranzo can you try this: https://github.com/bioconda/bioconda-recipes/blob/f5eb63e30a76fd13c28663786d219c9f7750267c/recipes/python-bioext/build.sh#L4

**Comment by nsoranzo** [comment]
Green finally!

**Comment by bgruening** [comment]
Yeah! Thanks!

**Pull request merged**
