### PR TITLE
Update RepeatModeler to version 2

### PR DESCRIPTION
**Pull request by Juke34**
**Replace this sentence with a detailed description of your pull request**

----

> Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it.

* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [ ] This PR adds a new recipe.
* [X] AFAIK, this recipe **is directly relevant to the biological sciences**
      (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [X] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

> Everyone has access to the following BiocondaBot commands, which can be given in a comment:
>
>  * `@BiocondaBot please update` will cause the BiocondaBot to merge the master branch into a PR
>  * `@BiocondaBot please add label` will add the `please review & merge` label.
>  * `@BiocondaBot please fetch artifacts` will post links to packages and docker containers built by the CI system. You can use this to test packages locally before merging.
>
> For members of the Bioconda project, the following command is also available:
>
>  * `@BiocondaBot please merge` will cause packages/containers to be uploaded and a PR merged. Someone must approve a PR first! This has the benefit of not wasting CI build time required by manually merging PRs.
>
> If you have questions, please post them in gitter or ping `@bioconda/core` in a comment (if you are not able to directly ping `@bioconda/core` then the bot will repost your comment and enable pinging).

### CODE REVIEW

**Comment by Juke34** [comment]
@dpryan79 I don't get why it fails, could it be timeout related?

**Comment by dpryan79** [comment]
Could be some sort of networking error, just hit rerun on circleci (make sure to login with your github account so you can).

**Comment by Juke34** [comment]
@dpryan79 I cannot hit the rerun button 
Screenshot 2020-02-05 at 10 31 42
And I already re-run once, with a fake modification without success.

**Comment by dpryan79** [comment]
Someone will have to run this locally to construct the container and login to it to see exactly why it's failing then.

**Comment by Juke34** [comment]
IT worked well on CircleCI on my computer, but I don't know if it performs exactly the same tasks

**Comment by dpryan79** [comment]
`RepeatModeler -h` returns with a non-zero exit status, which is why the mulled test fails. I've updated that to something that succeeds locally.

**Comment by dpryan79** [comment]
@BiocondaBot please merge

**Comment by oushujun** [comment]
Not sure it's related to the failed test. Although the conda version of [RepeatModeler 2.0.1](https://anaconda.org/bioconda/repeatmodeler) is using the latest [RMBlast](https://anaconda.org/bioconda/rmblast), which is 2.9.0, but is not compatible:

>...RepeatModeler 2.0.1, which is compatible with both RMBlast 2.9.0-p2 and 2.10.0. ([source](http://repeatmasker.org/RMBlast.html))

RMBlast 2.9.0-p2 or 2.10.0 is not available on conda yet.

**Pull request merged**
