### PR TITLE
Remove nglview

### PR DESCRIPTION
**Pull request by corburn**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by bgruening** [comment]
Thanks a ton @corburn! For all your work here! Please feel free to also merge your PRs, they look really good.

Not sure who is paying you, but say thanks to them! :)

**Comment by hainm** [comment]
@corburn  why do you remove nglview?

**Comment by corburn** [comment]
@hainm It is packaged in the conda-forge channel. I missed verifying its relevance to bioconda.

**Comment by hainm** [comment]
We chose `bioconda` as our official distribution for `nglview` (https://www.ncbi.nlm.nih.gov/pubmed/29236954) since `is directly relevant to the biological sciences`. We can not prevent people to add `nglview` to `conda-forge` but I think the one in that channel should be removed. 

cc @arose

**Comment by corburn** [comment]
@hainm I am sorry I failed to check. The recipe is being updated in #9435.

**Pull request merged**
