### PR TITLE
linting fixes for bulk

### PR DESCRIPTION
**Pull request by karl616**
bam-readcount
- pinned ncurses

collectl
- switched to perl

dwgsim
- pinned ncurses

mothur
- pinned ncurses

mothur/1.36.1
- pinned ncurses

perl-bio-samtools
- switched to perl

plastid
- modified python install command

pysam
- removed linting exception missing_hash as a hash is present

pysam/0.10.0
- added linting exception htslib_not_pinned similar to the main version
- modified python install command (if this works it could be propagated to the main version
  (I didn't touch it now as I didn't want to break it))

pysam/0.9.1
- added linting exception htslib_not_pinned similar to the main version
- modified python install command (if this works it could be propagated to the main version
  (I didn't touch it now as I didn't want to break it))

pysam/0.8.3
- modified python install command

r-spp
- pinned bzip2

rnalien
- pinned gmp

selectsequencesfrommsa
- pinned gmp

stacks/1.40
- switched to perl

stacks/1.42
- switched to perl

stacks/1.43
- switched to perl

tepid
- modified python install command

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by bgruening** [comment]
@karl616 thats super cool, but I guess we need to bump the build number for those recipes to get a new package.

**Comment by karl616** [comment]
@bgruening It's not enough that I pushed the version? or should I reset this and bump the build number? The latter would keep the same version as before, wouldn't it?

**Comment by karl616** [comment]
@bgruening done! Thanks for pointing it out

**Comment by bgruening** [comment]
Thanks @karl616!

**Pull request merged**
