### PR TITLE
update bwa-0.7.17: enable linux-aarch64 build

### PR DESCRIPTION
**Pull request by guozhicong**
Describe your pull request here

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

### General instructions

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

### Instructions for avoiding API, ABI, and CLI breakage issues
Conda is able to record and lock (a.k.a. pin) dependency versions used at build time of other recipes.
This way, one can avoid that expectations of a downstream recipe with regards to API, ABI, or CLI are violated by later changes in the recipe.
If not already present in the meta.yaml, make sure to specify `run_exports` (see [here](https://bioconda.github.io/contributor/linting.html#missing-run-exports) for the rationale and comprehensive explanation).
Add a `run_exports` section like this:

```yaml
build:
  run_exports:
    - ...

```

with `...` being one of:

| Case                             | run_exports statement                                               |
| -------------------------------- | ------------------------------------------------------------------- |
| semantic versioning              | `{{ pin_subpackage("myrecipe", max_pin="x") }}`     |
| semantic versioning (0.x.x)      | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}`   |
| known breakage in minor versions | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| known breakage in patch versions | `{{ pin_subpackage("myrecipe", max_pin="x.x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| calendar versioning              | `{{ pin_subpackage("myrecipe", max_pin=None) }}`    |

while replacing `"myrecipe"` with either `name` if a `name|lower` variable is defined in your recipe or with the lowercase name of the package in quotes.

### Bot commands for PR management

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

Note that the <code>@BiocondaBot please merge</code> command is now depreciated. Please just squash and merge instead.

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by jmarshall** [comment]
BWA 0.7.17 contains X86 SIMD code, so does not compile on ARM:

```
07:40:22 BIOCONDA INFO (OUT) ksw.c:29:10: fatal error: emmintrin.h: No such file or directory
```

An ARM port of this code (lh3/bwa#359) was merged 18 months ago but has not yet appeared in a bwa release.

In order to feasibly produce a linux-aarch64 package of BWA, @bioconda/core must lobby upstream for a new release.

**Comment by martin-g** [comment]
Here is an issue asking for a new release - https://github.com/lh3/bwa/issues/401

I have seen some recipes using Git SHA as a version. A proper upstream release would be better but maybe this is an option too ?!

**Comment by guozhicong** [comment]
> BWA 0.7.17 contains x86 SIMD code, so does not compile on ARM:
> 
> ```
> 07:40:22 BIOCONDA INFO (OUT) ksw.c:29:10: fatal error: emmintrin.h: No such file or directory
> ```
> 
> An ARM port of this code ([lh3/bwa#359](https://github.com/lh3/bwa/pull/359)) was merged 18 months ago but has not yet appeared in a bwa release.
> 
> In order to feasibly produce a linux-aarch64 package of BWA, @bioconda/core must lobby upstream for a new release.



> BWA 0.7.17 包含 x86 SIMD 代码，因此无法在 ARM 上编译：
> 
> ```
> 07:40:22 BIOCONDA INFO (OUT) ksw.c:29:10: fatal error: emmintrin.h: No such file or directory
> ```
> 
> 此代码的 ARM 移植版 ( [lh3/bwa#359](https://github.com/lh3/bwa/pull/359) ) 已于 18 个月前合并，但尚未出现在 bwa 版本中。
> 
> 为了切实可行地生成 BWA 的 linux-aarch64 包，@bioconda/core 必须游说上游发布新版本。

**Comment by guozhicong** [comment]
@jmarshall @martin-g Can I fix this problem by replacing the header file _emmintrin.h_ with _sse2neon.h_ as this [README ](https://github.com/DLTcollab/sse2neon/) describes.

**Comment by martin-g** [comment]
From https://github.com/lh3/bwa/pull/359 :

| There are already BWA PRs https://github.com/lh3/bwa/pull/283 and https://github.com/lh3/bwa/pull/344, which port the SIMD code to other platforms using [SIMDe](https://github.com/simd-everywhere/simde) and [sse2neon](https://github.com/DLTcollab/sse2neon) respectively

You can read the PR descriptions for all the history.

**Comment by jmarshall** [comment]
No. It would not be appropriate for bioconda to take on the maintenance burden of porting bwa to sse2neon. Moreover the work has already been done; and PR lh3/bwa#359 explains why that PR's approach is superior to a naive sse2neon port.

The appropriate approach for bioconda is to lobby for a new upstream release, as that is of benefit to the wider community. The other (inferior) approach open to bioconda IMHO is to apply that PR as a patch. Any other approach is not a feasible burden for bioconda IMHO.

**Comment by jmarshall** [comment]
Whether to take on the burden of patching this is also a question for @bioconda/core. IMHO we should not, as this is an excellent opportunity to encourage a long-overdue new release.

**Comment by guozhicong** [comment]
@martin-g Sorry ... I mean to say "if it is impossible ..."

**Pull request closed without merging**
