### PR TITLE
Update samtools to 1.11

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`samtools`](https://bioconda.github.io/recipes/samtools/README.html): **1.10** &rarr; **1.11**

[install with bioconda](http://bioconda.github.io/recipes/samtools/README.html) [Conda](https://anaconda.org/bioconda/samtools/files)

Info | Link
-----|-----
Recipe | [`recipes/samtools`](https://github.com//bioconda/bioconda-recipes/tree/bump/samtools/recipes/samtools) (click to view/edit other files)
Releases |[https://github.com/samtools/samtools/releases](https://github.com/samtools/samtools/releases)
Author | `@samtools`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by nathanweeks** [comment]
I think the build failed because samtools attempted to build with htslib 1.10, which was apparently the latest version when this was auto-bumped. Since htslib 1.11 is out now, this should work. However, since samtools and htslib (and bcftools) are developed and released pretty much in lockstep, would it make sense to pin the version of htslib required by samtools to be the same as the samtools version? e.g.:
```
--- a/recipes/samtools/meta.yaml
+++ b/recipes/samtools/meta.yaml
@@ -15,11 +15,11 @@ requirements:
   build:
     - {{ compiler('c') }}
   host:
-    - htslib
+    - htslib =={{ version }}
     - ncurses
     - zlib
   run:
-    - htslib
+    - htslib =={{ version }}
     - ncurses
     - zlib
```

**Comment by jmarshall** [comment]
This is indeed the problem, though the solution is probably to update the pinning in _recipes/samtools/conda_build_config.yaml_. See also https://github.com/bioconda/bioconda-recipes/pull/24486#issuecomment-697064676.

**Review by cbrueffer — APPROVED** [review]

**Comment by cbrueffer** [comment]
@bioconda-bot please merge

**Comment by cbrueffer** [comment]
That did the trick, thanks everyone.

**Pull request merged**
