### PR TITLE
Update sourmash to 4.4.0

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`sourmash`](https://bioconda.github.io/recipes/sourmash/README.html): **4.3.0** &rarr; **4.4.0**

[install with bioconda](http://bioconda.github.io/recipes/sourmash/README.html) [Conda](https://anaconda.org/bioconda/sourmash/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/sourmash`](https://github.com//bioconda/bioconda-recipes/tree/bump/sourmash/recipes/sourmash) (click to view/edit other files)
Summary | Compute and compare MinHash signatures for DNA data sets.
Home | [https://github.com/dib-lab/sourmash](https://github.com/dib-lab/sourmash)
Releases |[https://pypi.org/pypi/sourmash/json](https://pypi.org/pypi/sourmash/json)
Recipe Maintainer(s) | @luizirber, @ctb, @bluegenes

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by ctb** [comment]
@BiocondaBot rebuild

**Comment by ctb** [comment]
@BiocondaBot hello

**Review by ctb — APPROVED** [review]

**Comment by bgruening** [comment]
@ctb please use the bot to merge :)

**Comment by ctb** [comment]
k - I'm having trouble finding the documentation for exactly what incantations to use with bioconda bot, tho.

hmm, maybe:

@biocondabot help

**Comment by ctb** [comment]
@bioconda-bot please merge

**Comment by bgruening** [comment]
We have this here:

grafik

Would be nice to add it to the bot here as well.

**Pull request merged**
