### PR TITLE
Update merqury to 1.3

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`merqury`](https://bioconda.github.io/recipes/merqury/README.html): **1.1** &rarr; **1.3**

[install with bioconda](http://bioconda.github.io/recipes/merqury/README.html) [Conda](https://anaconda.org/bioconda/merqury/files)

Info | Link
-----|-----
Recipe | [`recipes/merqury`](https://github.com//bioconda/bioconda-recipes/tree/bump/merqury/recipes/merqury) (click to view/edit other files)
Releases |[https://github.com/marbl/merqury/tags](https://github.com/marbl/merqury/tags)
Author | `@marbl`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by EdHarry** [comment]
I don't think this version of Merqury works with the current version of meryl (1.2), and the meryl recipe needs to be manually updated to the latest version.

**Comment by bgruening** [comment]
Would it work with meryl 1.3? We can pin specifc meryl releases here by adding `- meryl 1.3`

**Comment by EdHarry** [comment]
yeah, i've pushed a PR updating meryl to 1.3 https://github.com/bioconda/bioconda-recipes/pull/28005/checks
once that's working I can update meryl as well

**Comment by bgruening** [comment]
Thanks a lot @EdHarry!

**Pull request closed without merging**
