### PR TITLE
bowtie2 - fix tbb version

### PR DESCRIPTION
**Pull request by rpetit3**
This is related to https://github.com/bioconda/bioconda-recipes/issues/27173

Current version of `tbb` is causing the following error:
```
(bowtie2-latest) rpetit@staphopia:~$ bowtie2 --version
/local/home/rpetit/miniconda3/envs/bowtie2-latest/bin/bowtie2-align-s: error while loading shared libraries: libtbb.so.2: cannot open shared object file: No such file or directory
(ERR): Description of arguments failed!
Exiting now ...
```

Downgrading `tbb` fixes the problem.
```
(bowtie2-latest) rpetit@staphopia:~$ conda install -c conda-forge 'tbb=2020.2'
(bowtie2-latest) rpetit@staphopia:~$ bowtie2 --version
/local/home/rpetit/miniconda3/envs/bowtie2-latest/bin/bowtie2-align-s version 2.4.2
64-bit
Built on default-bf91a638-95fa-4b77-97c5-abccd9855c3e
Mon Nov  2 17:36:36 UTC 2020
Compiler: gcc version 7.5.0 (crosstool-NG 1.24.0.131_87df0e6_dirty)
Options: -O3 -msse2 -funroll-loops -g3 -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /local/home/rpetit/miniconda3/envs/bowtie2-latest/include -fdebug-prefix-map=/opt/conda/conda-bld/bowtie2_1604337828546/work=/usr/local/src/conda/bowtie2-2.4.2 -fdebug-prefix-map=/local/home/rpetit/miniconda3/envs/bowtie2-latest=/usr/local/src/conda-prefix -DPOPCNT_CAPABILITY -DWITH_TBB -std=c++11 -DNO_SPINLOCK -DWITH_QUEUELOCK=1
Sizeof {int, long, long long, void*, size_t, off_t}: {4, 8, 8, 8, 8, 8}
```

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by rpetit3** [comment]
@BiocondaBot please add label

**Comment by dpryan79** [comment]
I'm going to hold off a bit on this, since we're already in communication with Anaconda to enable metadata patching. Presuming it works like what conda-forge is doing I have a patch ready to go that will fix all of the affected packages.

BTW, the main issue with this sort of fix is that the conda solver will tend to prefer earlier builds with looser (broken) pinnings. This sort of this has caused us a LOT of headaches :(

**Comment by rpetit3** [comment]
Sounds good.

> BTW, the main issue with this sort of fix is that the conda solver will tend to prefer earlier builds with looser (broken) pinnings. This sort of this has caused us a LOT of headaches :(


Good to know thanks!

**Comment by rpetit3** [comment]
@dpryan79 I'm going to close this for now

**Comment by dpryan79** [comment]
Thanks @rpetit3, I have a PR on bioconda-utils to update this pinning globally, so this will be fixed soon either way :)

**Pull request closed without merging**
