### PR TITLE
Update snakesv to 0.6

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`snakesv`](https://bioconda.github.io/recipes/snakesv/README.html): **0.4** &rarr; **0.6**

[install with bioconda](http://bioconda.github.io/recipes/snakesv/README.html) [Conda](https://anaconda.org/bioconda/snakesv/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/snakesv`](https://github.com//bioconda/bioconda-recipes/tree/bump/snakesv/recipes/snakesv) (click to view/edit other files)
Summary | snakeSV: Flexible framework for large-scale SV discovery
Home | [https://github.com/RajLabMSSM/snakeSV/](https://github.com/RajLabMSSM/snakeSV/)
Releases |[https://github.com/RajLabMSSM/snakeSV/tags](https://github.com/RajLabMSSM/snakeSV/tags)
Author | `@RajLabMSSM`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Review by ricardovialle — APPROVED** [review]

**Review by ricardovialle — APPROVED** [review]

**Comment by ricardovialle** [comment]
@BiocondaBot please merge

**Comment by ricardovialle** [comment]
@BiocondaBot please fetch artifacts

**Review by alienzj — APPROVED** [review]

**Comment by alienzj** [comment]
@BiocondaBot please merge

**Comment by alienzj** [comment]
@BiocondaBot please update

**Pull request closed without merging**
