### PR TITLE
added Visceral-Project segmentation evaluation tool recipe

### PR DESCRIPTION
**Pull request by ThomasWollmann**
* [x] I have read the guidelines above.
* [x] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by ThomasWollmann** [comment]
waiting for https://github.com/bioconda/bioconda-recipes/pull/3439

**Comment by ThomasWollmann** [comment]
successor of https://github.com/bioconda/bioconda-recipes/pull/2902

**Comment by ThomasWollmann** [comment]
ping @bgruening

Finally we solved the dependencies!

**Comment by bgruening** [comment]
Oh sorry missed that one.

**Pull request merged**
