### PR TITLE
flowworkspace & ncdfflow

### PR DESCRIPTION
**Pull request by cristhomas**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by bgruening** [comment]
@cristhomas are you using the bioconductor skeleton generator? I can highly recommend this tool, it saves you a lot of work.

**Comment by cristhomas** [comment]
yes I am, but it doesn't always work for all recipe.

**Comment by cristhomas** [comment]
though the one it didn't work for was because the R package didn't have all the requirements specified.

**Comment by cristhomas** [comment]
@bgruening how long does it take again for packages to be posted and available in bioconda after a successful and merged PR?

**Comment by bgruening** [comment]
@cristhomas this really depends on how busy travis is. And travis was busy, a lot in the last days. Let me know if it is not online on Monday.

**Comment by cristhomas** [comment]
ok thank you!

**Pull request merged**
