### PR TITLE
bump salmon to version 0.14.0 build 1

### PR DESCRIPTION
**Pull request by k3yavi**
* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [X] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [X] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by k3yavi** [comment]
@epruesse It seems the previous PR got auto merge. We were waiting for some last minute changes before merging #15661 . Any idea on how do we make the two PR into one release ?

**Comment by epruesse** [comment]
We can't, not unless it's an utter emergency. I'm sorry - I merged that PR. It looked ready to me, and wasn't marked as "Draft" or with the WIP label. What is broken with it?

**Comment by rob-p** [comment]
Well, conda will default to the latest build number anyway, right?  So one would need to explicitly request the old version / build combo to get it.

**Comment by k3yavi** [comment]
No worries @epruesse . Thanks for the reply, it was my bad actually, I should have put a WIP tag or some sort. Nothing major is broken, we found a bug with an optional command line argument at the last minute. As @rob-p said, we will merge this PR then conda can take care of it.

**Comment by epruesse** [comment]
If you don't change any dependencies, yes. 

Conda has that annoying misfeature (IMO) to prefer a newer version in one package over a newer build in another. That is, if you update a package with stricter pinnings, it likes to use the old build without those pinnings if they require something else be installed with a lower version. Don't like it. Don't see why you'd ever want anything but the newest build,

**Comment by epruesse** [comment]
You changed the tag, didn't you? Technically, that's what `0.14.0post1` or `0.14.1` would be for.

**Pull request merged**
