### PR TITLE
Use 2to3 to make MEME 4.11.2 compatible with Python 3

### PR DESCRIPTION
**Pull request by apcamargo**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences**
      (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [x] This PR does something else (explain below).

I used 2to3 to make MEME 4.11.2 compatible with Python 3. This is necessary to use it with antiSMASH 5 (https://github.com/bioconda/bioconda-recipes/pull/20077).

### CODE REVIEW

**Comment by apcamargo** [comment]
@bgruening Here's the 2to3 conversion you suggested. What do you think?

**Comment by bgruening** [comment]
@BiocondaBot please fetch artifacts

**Comment by bgruening** [comment]
That looks good to me, can you test the artifacts, please?

**Comment by dpryan79** [comment]
You'll want to enable builds for python 3.

**Comment by marcelm** [comment]
Shouldn’t running `2to3` be done as a last resort only? This way, it essentially becomes a fork that needs to be maintained. Isn’t there a way to get upstream to update their package?

**Comment by marcelm** [comment]
At least run `2to3` during the build (so that the patch file isn’t needed).

**Comment by apcamargo** [comment]
@dpryan79 How do I do that? I thought that skipping py27 was enough.

@marcelm I agree with you that this solution is not ideal, but as this is an old MEME version, I don't think the developers will update it to Python 3.
Do you think that running `2to3` during the build is better? I chose to apply the patch to make the changes more explicit.

**Comment by dpryan79** [comment]
@bioconda-bot please fetch artifacts

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Pull request merged**
