### PR TITLE
Update mimseq to 1.2

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`mimseq`](https://bioconda.github.io/recipes/mimseq/README.html): **1.1.7** &rarr; **1.2**

[install with bioconda](http://bioconda.github.io/recipes/mimseq/README.html) [Conda](https://anaconda.org/bioconda/mimseq/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/mimseq`](https://github.com//bioconda/bioconda-recipes/tree/bump/mimseq/recipes/mimseq) (click to view/edit other files)
Summary | Modification-induced misincorporation tRNA sequencing.
Home | [https://github.com/nedialkova-lab/mim-tRNAseq](https://github.com/nedialkova-lab/mim-tRNAseq)
Releases |[https://pypi.org/pypi/mimseq/json](https://pypi.org/pypi/mimseq/json)

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by drewjbeh** [comment]
@daler this test seemed to fail in the linux test with `Bash exited with code 137`. Seems to be a [resource/OOM](https://support.circleci.com/hc/en-us/articles/115014359648-Exit-Code-137-Out-of-Memory) issue. I haven't changed anything in the recipe or dependencies since the previous version, so not sure what the problem is. Any help is appreciated

**Comment by drewjbeh** [comment]
@BiocondaBot rerun checks

**Comment by daler** [comment]
Not sure either, though this has been popping up in other recipes as well. Doesn't seem to be an obvious pattern, but we may have to do some more careful memory management in the build system to properly solve it.

In the meantime, let's try a rebuild to see if that magically solves anything...

**Comment by daler** [comment]
@BiocondaBot please update

**Comment by drewjbeh** [comment]
@daler Great thanks for the message. I have done some updates since, which I'm sure you see from the v1.2 bump. I also tried a local build of this and it worked fine, so hopefully Azure works fine this time too. Thanks!

**Pull request closed without merging**
