### PR TITLE
Update pyseer to 1.0.2

### PR DESCRIPTION
**Pull request by mgalardini**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.

### CODE REVIEW

**Comment by mgalardini** [comment]
Hi,

I'm not sure whether this PR lacks anything to be merged. The failing macos test is solely due to me missing the appropriate plan on circleci. Have I missed something?

Thanks,
Marco

**Comment by daler** [comment]
Hi @mgalardini - the solution is to disable CircleCI on your fork. We had previously recommended enabling it for forks, but turns out that causes the macOS plan problems.

See the updated docs for details:
- https://bioconda.github.io/contribute-a-recipe.html#push-changes-wait-for-tests-to-pass-submit-pull-request 
- https://bioconda.github.io/faqs.html#circlecimacos

**Comment by mgalardini** [comment]
Hi, thanks a lot for the heads up, I must have missed that bit of the instructions. I now stopped the circleci builds for my fork. Hope this can help with this PR, happy to do more if needed.

Marco

**Comment by daler** [comment]
@mgalardini now we have to retrigger circleci -- first thing to try is if you close and then re-open this PR. If that doesn't work, try making a small change (like whitepace in your recipe). If that doesn't work, you'll need to open another PR. Sorry for the trouble!

**Comment by mgalardini** [comment]
Neat, thanks for the pointers!

**Comment by mgalardini** [comment]
Hi,

sorry for being annoying, but I was wondering whether this PR lacks anything to be merged. The current recipe for pyseer points to an earlier version that doesn't match the publication and docs available online. I am happy to do some work on it if required.

Best,
Marco

**Comment by daler** [comment]
@mgalardini sorry for the late reply, looks good and thank you!

**Pull request merged**
