### PR TITLE
fix cffi dep version for sourmash

### PR DESCRIPTION
**Pull request by luizirber**
There is a bug in `cffi` which affects [sourmash](https://github.com/dib-lab/sourmash/pull/911), but it is fixed in `cffi == 1.14.0`.

----

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences**
      (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by luizirber** [comment]
@BiocondaBot update

**Comment by luizirber** [comment]
This is failing because `cffi 1.14.0` is coming from the `pkgs/main` channel, which doesn't have a py27 version. Asked in https://github.com/conda-forge/cffi-feedstock/pull/19 for the conda-forge version bump

**Comment by luizirber** [comment]
@BiocondaBot update

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Comment by dpryan79** [comment]
@bioconda-bot please fetch artifacts

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Pull request merged**
