### PR TITLE
Add biopython extensions developed by VEG.

### PR DESCRIPTION
**Pull request by davebx**
* [x] I have read the guidelines above.
* [x] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

Ping @bioconda/core

### CODE REVIEW

**Comment by bgruening** [comment]
@davebx any dependency missing?
```
BioExt/align/_align.c:306:23: fatal error: alignment.h: No such file or directory
 #include "alignment.h"
```

**Comment by bgruening** [comment]
Also seem that you compile something so you need gcc/llvm as dependency?

**Comment by davebx** [comment]
@bgruening Yes, there's an issue in the code upstream, we're looking into it now. I'll add a compiler dependency for building.

**Comment by johanneskoester** [comment]
We have migrated our build system from Travis CI to Circle CI. If you would like to continue working on this PR, please update with latest upstream master and reopen this PR.

**Pull request closed without merging**
