### PR TITLE
cmake modified to build with NDEBUG

### PR DESCRIPTION
**Pull request by erinijapranckeviciene**
* [ ] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [ ] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [X] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by erinijapranckeviciene** [comment]
Modified cmake build type to Release to build Seqan with NDEBUG.

**Comment by erinijapranckeviciene** [comment]
Hi @bgruening , I had to update the building principle of dnp-diprofile to remove Seqan DEBUG information from it, because I encountered several assertion failures (similar to  other users of Seqan)  , that seems like some unresolved problem of the library itself. I would like to ask to update dnp-diprofile recipe. Many thanks in advance.

**Comment by bgruening** [comment]
@erinijapranckeviciene if you change the recipe you need to increase the build version as I just did to trigger a new release.

**Comment by erinijapranckeviciene** [comment]
@bgruening I finished updating , I would like to keep the fasta test in the build if that is OK.

**Comment by erinijapranckeviciene** [comment]
Hi @bgruening , I believe you are well, maybe away. I would like to ask to review and finalise this pull request when you are back online. I am ready to submit the dnp-* tools to the Galaxy Tool Shed and for that it is important that the dnp-diprofile building in bio-conda is updated.  Thank you very much and with kind regards.

**Pull request merged**
