### PR TITLE
Update nglview v1.1.1

### PR DESCRIPTION
**Pull request by hainm**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by hainm** [comment]
hi, is there anyone know how to retrigger the `ci/circleci: test-macos — Waiting for status to be reported`?

**Comment by daler** [comment]
Hi @hainm, it looks like the linux job had an (unrelated) HTTP error on CircleCI, and somehow that was hanging up the reporting of the macos job.

In general you can try pushing a minor change (like a whitespace change) to trigger a fresh rebuild, but in this case I just restarted the linux job to see if that will do the trick.

**Comment by daler** [comment]
That worked, thanks for this update!

**Comment by hainm** [comment]
thanks @daler for your help.

**Pull request merged**
