### PR TITLE
Update vcflib to 1.0.2

### PR DESCRIPTION
**Pull request by jpuritz**
Update 
----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by jpuritz** [comment]
With Cmake, this build script is very out of date.  It's a bit beyond my comfort level.  I've made a `tabixpp` bioconda recipe and it's merged, but Cmake does not find it.  I'm hopeful we can get this to build without having to do a recursive git clone.  

Any help would be appreciated! Tagging a few here who might be able to: @pjotrp @mr-c @tseemann

**Comment by pjotrp** [comment]
That error is looking familiar by now. You'd think pkg-config would find the tabixpp include path.

**Comment by mr-c** [comment]
Here are the Debian patches, maybe some of them will help or inspire :-) https://sources.debian.org/src/libvcflib/1.0.2+dfsg-2/debian/patches/

**Comment by pjotrp** [comment]
hi @jpuritz. The build log looks like it was killed for running too long. Do you have a way to test conda locally? It probably will speed development up. If you are stuck with a specific dependency I can probably help in the coming period. tabixpp is kinda unresolved at this point if pkg-config is not helping (that does work on Debian!).

**Comment by jpuritz** [comment]
@pjotrp seems like the actual fail is now on `vcffirstheader`.  I think one of the last commits fixes the CMake install of the scripts.  That might finish this.

**Comment by pjotrp** [comment]
vcffirstheader is a script that lives in ./scripts. The installer will copy it to $bin. It has a Python3 dependency so that may be missing?

**Comment by jpuritz** [comment]
> vcffirstheader is a script that lives in ./scripts. The installer will copy it to $bin. It has a Python3 dependency so that may be missing?

The build here is dependent on the latest release of `vcflib` not the repo version.  I believe the scripts were just recently added to the cmake configuration (https://github.com/vcflib/vcflib/commit/a5995def667c0caabd5903672619f0ea54c4f159).

I added copying the scripts to the `build.sh` for now.  This thing is still incredibly ugly, but it works.

**Comment by jpuritz** [comment]
@BiocondaBot please add label

**Comment by pjotrp** [comment]
great job. I don't know the conda policies, but it looks good to me.

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
Looks good. I moved cmake and pkg-config to the build section, so once this passes I'll have the bot merge it (if those prove to be needed in the host section instead for some reason we can just revert and merge).

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Pull request merged**
