### PR TITLE
Update proteinortho to 6.0.24

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`proteinortho`](https://bioconda.github.io/recipes/proteinortho/README.html): **6.0.23** &rarr; **6.0.24**

[install with bioconda](http://bioconda.github.io/recipes/proteinortho/README.html) [Conda](https://anaconda.org/bioconda/proteinortho/files)

Info | Link
-----|-----
Recipe | [`recipes/proteinortho`](https://github.com//bioconda/bioconda-recipes/tree/bump/proteinortho/recipes/proteinortho) (click to view/edit other files)
Releases |[https://gitlab.com/paulklemm_PHD/proteinortho/tags](https://gitlab.com/paulklemm_PHD/proteinortho/tags)

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by pmjklemm** [comment]
Is there anyway of explicitly require -std=c++17 (this should correspond to g++8 but I am not sure) ?

There is an error with centOS, where -std=c++17 is not found by default:

https://gitlab.com/paulklemm_PHD/proteinortho/-/issues/39

(I thought the required c++ compiler this is automatically detected by conda)

**Comment by eseiler** [comment]
> Is there anyway of explicitly require -std=c++17 (this should correspond to g++8 but I am not sure) in the meta.yml? ( I searched for c++17 in other meta.yml but I did not find something related)

Not that I know of, the required standard correlates to some minimum compiler version (e.g., GCC7). conda-build currently provides GCC 7.5 for linux and some version of clang for macos; both support `-std=c++17`. 

> 
> There is an error with centOS, where -std=c++17 is not found by default:
> 
> https://gitlab.com/paulklemm_PHD/proteinortho/-/issues/39
> 
> (I thought the required c++ compiler this is automatically detected by conda)

The package seems to be built with `CXXFLAGS=-fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/proteinortho-6.0.24 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix` (see the CI logs for linux).

Could the `-mtune=haswell` cause the problem?

**Comment by pmjklemm** [comment]
thanks for the hints @eseiler. I will investigate this tomorrow

**Comment by pmjklemm** [comment]
I could not reproduce the error and the OP did not response so it can be closed for now

**Review by pmjklemm — APPROVED** [review]

**Pull request merged**
