### PR TITLE
Add variphyer

### PR DESCRIPTION
**Pull request by cl117**
Describe your pull request here

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by fanninpm** [comment]
Duplicate of #28435

**Comment by fanninpm** [comment]
@BiocondaBot please update

**Comment by fanninpm** [comment]
[7](https://commit.style/)

**Comment by fanninpm** [comment]
Do you have an account on CircleCI?

**Comment by cl117** [comment]
My account is cl117.

**Comment by fanninpm** [comment]
@BiocondaBot please fetch artifacts

**Comment by fanninpm** [comment]
What do you see when you follow [this link](https://app.circleci.com/pipelines/github/bioconda?filter=mine)?

**Comment by cl117** [comment]
[image: image.png]

**Comment by fanninpm** [comment]
> [image: image.png]

For some reason, emailing an attachment to GitHub doesn't work.

**Comment by cl117** [comment]
I saw nothing on that link page, it says "adding projects to see running
pipelines".  I thought I might need to synchronize the bioconda git repo.

**Comment by fanninpm** [comment]
Have you connected your GitHub account with your CircleCI account?

**Comment by cl117** [comment]
I think I did.

**Comment by fanninpm** [comment]
@BiocondaBot please add label

**Comment by dpryan79** [comment]
This appears to vendor beast and a Linux binary from mauve. Can it just directly use beast as a dependency instead? The Linux binary from mauve also means this can't be `noarch: generic` (you'll have to use a skip-lint https://bioconda.github.io/contributor/linting.html#skipping-a-lint-check ).

**Pull request closed without merging**
