### PR TITLE
forget bowtie and bowtie2 in CIRCexplorer2 run section

### PR DESCRIPTION
**Pull request by kepbod**
* [x] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by bgruening** [comment]
Is it possible to inlcude a test for thise deps?

**Comment by kepbod** [comment]
These depends are not essential. But it will be very convenient to include them.

**Comment by kepbod** [comment]
I did not know how to include a test for them.

**Comment by kepbod** [comment]
Do you have any good ideas? @bgruening

**Comment by bgruening** [comment]
Just check if bowtie is in the path. Just want to make sure this does not get lost anymore :)

**Comment by kepbod** [comment]
Thanks for your suggestions. When running the programs, they will check all the depends. In addition, all the essential depends will be checked during the installation. So I think it is not necessary to include some tests for the unessential depends. =)

**Pull request merged**
