### PR TITLE
New recipe: moca

### PR DESCRIPTION
**Pull request by saketkc**
* [x] I have read the guidelines above.
* [x] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by saketkc** [comment]
@johanneskoester I am not sure I understand the DAG 0 failure. Is somehow the recipe being bumped above its dependencies?

**Comment by johanneskoester** [comment]
Let's do it step by step. In the osx build, pycairo is missing, because it is not available for osx in the default channel. I guess there is a good reason for this. Hence, if this is a necessary dependency of moca, you should add a `skip: True # [osx]` to the build section.

**Comment by johanneskoester** [comment]
The error in subdag 0 is indeed weird, and I don't understand it at all. @bioconda/core, has anybody seen something like this in another PR? Is it just too late and I am missing something obvious?

**Comment by tomkinsc** [comment]
I may have encountered a similar strange error before on my local machine. If I remember right, the cause was that some of the requirements had their own requirements, some of which were incompatible (pinned to a specific version rather than an open range, and conda couldn't resolve the dependencies), and conda yielded that error rather than its usual message about incompatible dependencies. Does the recipe build on your local machine, @saketkc?

**Comment by saketkc** [comment]
Thanks @tomkinsc and @johanneskoester! It builds on my local machine, though only on py27. I need to check what's going on since I don't get any errors on travis: https://travis-ci.org/saketkc/moca for py3+. I have skipped building on `osx` though.

**Pull request closed without merging**
