### PR TITLE
Fix version conflict for scglue 0.3.0 update

### PR DESCRIPTION
**Pull request by Jeff1995**
Fix version conflict for scglue 0.3.0 update

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by Jeff1995** [comment]
@BiocondaBot please add label

**Comment by Jeff1995** [comment]
Hi maintainers!

I have created this PR to fix the `bump/scglue` branch automatically created by bot (since I don't have write access to this repo). Am I doing it right? Could you please merge this, or point me to the right way to update the bot-created branch?

Thanks!

**Comment by Jeff1995** [comment]
@BiocondaBot please merge

**Comment by Jeff1995** [comment]
@bgruening, @cbrueffer 

Could you help? Sorry to bother you. Thanks a lot!

**Comment by bgruening** [comment]
Hi @Jeff1995

You need to bump the version number and you need one approval before you can merge the PR.

**Comment by Jeff1995** [comment]
Thanks you!

The scglue version number has already been bumped (0.2.3 -> 0.3.0) in the bot-created PR (#36500), but the checks in that PR failed due to conflicting version of numba and numpy. Since I do not have write access to this repo, I cannot fix that PR (#36500) by adding new commits. So I created this PR (#36502) hoping to update the `bump/scglue` branch and fix the problem.

I'm I doing it right? Or what am I supposed to do to fix #36500.

**Comment by Jeff1995** [comment]
Hi @bgruening! Could you help me with these questions? I do wish to get through this update ASAP. Thanks!

**Pull request closed without merging**
