### PR TITLE
strainge: add aarch64/arm64 builds

### PR DESCRIPTION
**Pull request by martin-g**
Describe your pull request here

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

### General instructions

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

### Instructions for avoiding API, ABI, and CLI breakage issues
Conda is able to record and lock (a.k.a. pin) dependency versions used at build time of other recipes.
This way, one can avoid that expectations of a downstream recipe with regards to API, ABI, or CLI are violated by later changes in the recipe.
If not already present in the meta.yaml, make sure to specify `run_exports` (see [here](https://bioconda.github.io/contributor/linting.html#missing-run-exports) for the rationale and comprehensive explanation).
Add a `run_exports` section like this:

```yaml
build:
  run_exports:
    - ...

```

with `...` being one of:

| Case                             | run_exports statement                                               |
| -------------------------------- | ------------------------------------------------------------------- |
| semantic versioning              | `{{ pin_subpackage("myrecipe", max_pin="x") }}`     |
| semantic versioning (0.x.x)      | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}`   |
| known breakage in minor versions | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| known breakage in patch versions | `{{ pin_subpackage("myrecipe", max_pin="x.x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| calendar versioning              | `{{ pin_subpackage("myrecipe", max_pin=None) }}`    |

while replacing `"myrecipe"` with either `name` if a `name|lower` variable is defined in your recipe or with the lowercase name of the package in quotes.

### Bot commands for PR management

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

Note that the <code>@BiocondaBot please merge</code> command is now depreciated. Please just squash and merge instead.

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by bgruening** [comment]
Seems to work. This PR was using the new bioconda-utils package.

**Comment by martin-g** [comment]
@BiocondaBot please fetch artifacts

**Comment by martin-g** [comment]
```
mgrigorov in 🌐 euler-arm-22 in /tmp/strainge via 🅒 test123 took 5s 
❯ tar xvf strainge-1.3.9-py310hd637821_1.tar.bz2                                                                                                                                                           (test123) 
info/run_exports.json
info/test/run_test.sh
info/test/run_test.py
info/hash_input.json
info/index.json
info/licenses/LICENSE
info/recipe/meta.yaml.template
info/has_prefix
info/files
info/recipe/meta.yaml
info/recipe/conda_build_config.yaml
info/about.json
info/paths.json
info/git
bin/strainge
bin/straingr
bin/straingst
bin/pankmer
bin/kmerspectrum
bin/kmercoverage
bin/refseq-extract
bin/kmerseq
bin/refseq-download
bin/kmersimilarity
bin/kmertree
bin/treepath
lib/python3.10/site-packages/strainge-1.3.9.dist-info/direct_url.json
lib/python3.10/site-packages/strainge-1.3.9.dist-info/top_level.txt
lib/python3.10/site-packages/strainge-1.3.9.dist-info/entry_points.txt
lib/python3.10/site-packages/strainge/io/__pycache__/__init__.cpython-310.pyc
lib/python3.10/site-packages/strainge/cli/__pycache__/__init__.cpython-310.pyc
lib/python3.10/site-packages/strainge/__pycache__/_version.cpython-310.pyc
lib/python3.10/site-packages/strainge/__pycache__/__init__.cpython-310.pyc
lib/python3.10/site-packages/strainge/io/__pycache__/utils.cpython-310.pyc
lib/python3.10/site-packages/strainge/__pycache__/comparison.cpython-310.pyc
lib/python3.10/site-packages/strainge/cli/__pycache__/registry.cpython-310.pyc
lib/python3.10/site-packages/strainge/__pycache__/utils.cpython-310.pyc
lib/python3.10/site-packages/strainge/__pycache__/cluster.cpython-310.pyc
lib/python3.10/site-packages/strainge/io/__pycache__/comparisons.cpython-310.pyc
lib/python3.10/site-packages/strainge/cli/__pycache__/main.cpython-310.pyc
lib/python3.10/site-packages/strainge/cli/__pycache__/straingst.cpython-310.pyc
lib/python3.10/site-packages/strainge/__pycache__/sample_compare.cpython-310.pyc
lib/python3.10/site-packages/strainge/__pycache__/search_tool.cpython-310.pyc
lib/python3.10/site-packages/strainge/io/__pycache__/variants.cpython-310.pyc
lib/python3.10/site-packages/strainge/__pycache__/kmertools.cpython-310.pyc
lib/python3.10/site-packages/strainge/cli/__pycache__/kmersets.cpython-310.pyc
lib/python3.10/site-packages/strainge/cli/__pycache__/straingr.cpython-310.pyc
lib/python3.10/site-packages/strainge/__pycache__/variant_caller.cpython-310.pyc
lib/python3.10/site-packages/strainge-1.3.9.dist-info/INSTALLER
lib/python3.10/site-packages/strainge-1.3.9.dist-info/WHEEL
lib/python3.10/site-packages/strainge-1.3.9.dist-info/LICENSE
lib/python3.10/site-packages/strainge-1.3.9.dist-info/METADATA
lib/python3.10/site-packages/strainge-1.3.9.dist-info/RECORD
lib/python3.10/site-packages/strainge-1.3.9.dist-info/REQUESTED
lib/python3.10/site-packages/strainge/_version.py
lib/python3.10/site-packages/strainge/cli/__init__.py
lib/python3.10/site-packages/strainge/io/__init__.py
lib/python3.10/site-packages/strainge/__init__.py
lib/python3.10/site-packages/strainge/cli/registry.py
lib/python3.10/site-packages/strainge/comparison.py
lib/python3.10/site-packages/strainge/utils.py
lib/python3.10/site-packages/strainge/io/utils.py
lib/python3.10/site-packages/strainge/io/comparisons.py
lib/python3.10/site-packages/strainge/cluster.py
lib/python3.10/site-packages/strainge/cli/main.py
lib/python3.10/site-packages/strainge/cli/straingst.py
lib/python3.10/site-packages/strainge/sample_compare.py
lib/python3.10/site-packages/strainge/search_tool.py
lib/python3.10/site-packages/strainge/io/variants.py
lib/python3.10/site-packages/strainge/kmertools.py
lib/python3.10/site-packages/strainge/cli/kmersets.py
lib/python3.10/site-packages/strainge/cli/straingr.py
lib/python3.10/site-packages/strainge/variant_caller.py
lib/python3.10/site-packages/strainge/kmerizer.cpython-310-aarch64-linux-gnu.so

mgrigorov in 🌐 euler-arm-22 in /tmp/strainge via 🅒 test123 
❯ file bin/*                                                                                                                                                                                               (test123) 
bin/kmercoverage:    a /opt/conda/conda-bld/strainge_1732961709731/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh script, ASCII text executable
bin/kmerseq:         a /opt/conda/conda-bld/strainge_1732961709731/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh script, ASCII text executable
bin/kmersimilarity:  a /opt/conda/conda-bld/strainge_1732961709731/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh script, ASCII text executable
bin/kmerspectrum:    a /opt/conda/conda-bld/strainge_1732961709731/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh script, ASCII text executable
bin/kmertree:        a /opt/conda/conda-bld/strainge_1732961709731/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh script, ASCII text executable
bin/pankmer:         a /opt/conda/conda-bld/strainge_1732961709731/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh script, ASCII text executable
bin/refseq-download: a /opt/conda/conda-bld/strainge_1732961709731/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh script, ASCII text executable
bin/refseq-extract:  a /opt/conda/conda-bld/strainge_1732961709731/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh script, ASCII text executable
bin/strainge:        a /opt/conda/conda-bld/strainge_1732961709731/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh script, ASCII text executable
bin/straingr:        a /opt/conda/conda-bld/strainge_1732961709731/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh script, ASCII text executable
bin/straingst:       a /opt/conda/conda-bld/strainge_1732961709731/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh script, ASCII text executable
bin/treepath:        a /opt/conda/conda-bld/strainge_1732961709731/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh script, ASCII text executable

mgrigorov in 🌐 euler-arm-22 in /tmp/strainge via 🅒 test123 
❯                                                                                                                                                                                                          (test123) 

mgrigorov in 🌐 euler-arm-22 in /tmp/strainge via 🅒 test123 
❯ file lib/python3.10/site-packages/strainge/kmerizer.cpython-310-aarch64-linux-gnu.so                                                                                                                     (test123) 
lib/python3.10/site-packages/strainge/kmerizer.cpython-310-aarch64-linux-gnu.so: ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, with debug_info, not stripped
```
LGTM!

**Comment by martin-g** [comment]
@BiocondaBot please add label

**Pull request merged**
