### PR TITLE
Updated reference to SearchGUI version 3.2.24 and PeptideShaker 1.16.20

### PR DESCRIPTION
**Pull request by CarlosHorro**
* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [X] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by tomkinsc** [comment]
Thanks for the update. Is there a particular reason to preserve recipes for older versions of SearchGUI? (especially [patch-increment](https://semver.org/) versions) Just as an FYI, recipes can generally be updated in-place since built packages for the older versions will be retained on [anaconda.org](https://anaconda.org/bioconda/searchgui/files). It can be helpful to retain a copy of an older recipe with notes about what's different between versions if there are significant algorithmic differences (ex. [older trinity](https://github.com/bioconda/bioconda-recipes/tree/master/recipes/trinity/date.2011_11_26)), but otherwise making subdirectories for older versions is largely unnecessary. That said, there's minimal harm.

**Comment by CarlosHorro** [comment]
Hi tomkinsc,

Well, I though it could be useful for keeping some trace of the different versions here also, although of course you are right and it's completely optional. 

Greetings,
Carlos

**Comment by CarlosHorro** [comment]
Sorry for the last-minute commits, they were the last ones for this PR.

**Comment by bgruening** [comment]
Thanks @CarlosHorro!

**Pull request merged**
