### PR TITLE
Update r-basejump to 0.13.4

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`r-basejump`](https://bioconda.github.io/recipes/r-basejump/README.html): **0.13.2** &rarr; **0.13.4**

[install with bioconda](http://bioconda.github.io/recipes/r-basejump/README.html) [Conda](https://anaconda.org/bioconda/r-basejump/files)

Info | Link
-----|-----
Recipe | [`recipes/r-basejump`](https://github.com//bioconda/bioconda-recipes/tree/bump/r_basejump/recipes/r-basejump) (click to view/edit other files)
Releases |[https://github.com/acidgenomics/basejump/tags](https://github.com/acidgenomics/basejump/tags)
Recipe Maintainer(s) | @mjsteinbaugh
Author | `@acidgenomics`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by mjsteinbaugh** [comment]
Requires a bump in r-acidbase and r-acidgenerics...working on it

**Comment by mjsteinbaugh** [comment]
r-acidgenerics update in progress at https://github.com/bioconda/bioconda-recipes/pull/25629

**Comment by mjsteinbaugh** [comment]
r-acidbase update in progress at https://github.com/bioconda/bioconda-recipes/pull/25634 , then should be safe to merge

**Comment by mjsteinbaugh** [comment]
Looks safe to merge

**Comment by dpryan79** [comment]
@mjsteinbaugh You're welcome to merge this yourself, then you needn't wait for others.

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Comment by mjsteinbaugh** [comment]
@dpryan79 Sorry forgot this was an autobump one haha

**Pull request merged**
