### PR TITLE
nextflow 0.21.3 -> 0.23.4

### PR DESCRIPTION
**Pull request by odoublewen**
- [x] I have read the guidelines above.
- [ ] This PR adds a new recipe.
- [x] This PR updates an existing recipe.
- [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by jerowe** [comment]
It looks like you are overwriting the previous version of netflow. Instead, could you create a directory for the old recipe, and add the latest version to the top level directory?

**Comment by odoublewen** [comment]
I put the old recipe in its own dir and updated the top level recipe to reflect the latest nextflow version.

However, the Travis CI test fails with this message (and I am not sure what it means or how to fix it):

```
UnsatisfiableError: The following specifications were found to be in conflict:
  - conda-build ==2.0.0 -> python 2.7* -> openssl 1.0.1*
  - python 3.6*
```

**Comment by bgruening** [comment]
@odoublewen I just fixed your new recipe real quick, the indentation was wrong all over.

**Comment by bgruening** [comment]
I think we need a rebase or merge of master. This PR is quite old and many things have changed in our build infrastructure.
Thanks!

**Comment by odoublewen** [comment]
@bgruening Thanks for catching the indent problem.   I should know better than to paste into emacs from system clipboard :/

I made a fresh branch off of master just now, and so I will see if that passes the Travis CI part.

See PR #4158

(Locally, conda build works for me....)

**Pull request closed without merging**
