### PR TITLE
Add drop, wbuild, and r-tmae

### PR DESCRIPTION
**Pull request by c-mertes**
We developed a bioinformatic pipeline to detect outliers in RNA-seq data using snakemake. 

It requires 
* drop: the pipeline itself
* wbuild: a tool we wrote to create automated html reports based on r scripts
* r-tmae: a r package to detect mono allelic expression

all those packages are bundled within the PR.

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by c-mertes** [comment]
@BiocondaBot please fetch artifacts

**Comment by c-mertes** [comment]
@BiocondaBot please add label

BTW I debugged the recipes locally, but any clue why it is not running within this PR through circleci? Do I have to trigger something? Could I also run it on my personal fork? Also there it throws an error in the linting, which is caused how bioconda is using git to check for differences. 

If I should put this into an issue I'm happy to do so. Just let me know.

**Comment by c-mertes** [comment]
@BiocondaBot please fetch artifacts

**Comment by c-mertes** [comment]
I do not know why it is complaining that it does not find `wbuild`. Is it because of the fact that `wbuild` is not yet in bioconda? 

The interesting part is, that `drop` which depends on `wbuild` builds and tests without any problem, but just does not creates a package. It does build fine when I execute locally `circleci build` on my computer. 

Can someone look through this and help me out? 

Thanks in advance.

**Comment by dpryan79** [comment]
Please make PRs for the dependencies first.

**Comment by c-mertes** [comment]
@dpryan79  thanks for checking my dependency PR. 

In the meantime I figured out my problem. I used `noarch: generic` instead of `noarch: python` which threw the error in the end some how.  

I merged already your changed into this PR. So only the `drop` recipe has to be reviewed here before merging it into the master.

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Comment by c-mertes** [comment]
@dpryan79 thanks a lot for the help!

**Pull request merged**
