### PR TITLE
Update r-azimuth to 0.5.0

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`r-azimuth`](https://bioconda.github.io/recipes/r-azimuth/README.html): **0.4.6** &rarr; **0.5.0**

[install with bioconda](http://bioconda.github.io/recipes/r-azimuth/README.html) [Conda](https://anaconda.org/bioconda/r-azimuth/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/r-azimuth`](https://github.com//bioconda/bioconda-recipes/tree/bump/r_azimuth/recipes/r-azimuth) (click to view/edit other files)
Summary | Azimuth is a Shiny app demonstrating a query-reference mapping algorithm for single-cell data.
Home | [https://github.com/satijalab/azimuth](https://github.com/satijalab/azimuth)
Releases |[https://github.com/satijalab/azimuth/tags](https://github.com/satijalab/azimuth/tags)
Author | `@satijalab`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by cbrueffer** [comment]
Also added JASPAR2020 and TFBSTools to dependencies, not sure how critical those are (see https://github.com/satijalab/azimuth/compare/v0.4.6...v0.5.0)

**Comment by isuruf** [comment]
Thanks @cbrueffer

**Comment by cbrueffer** [comment]
```
21:38:07 BIOCONDA INFO (OUT) Downloading https://github.com/satijalab/azimuth/archive/refs/tags/v0.5.0.tar.gz
21:38:08 BIOCONDA INFO (OUT) Success
21:38:08 BIOCONDA INFO (ERR) INFO:conda_build.source:Success
21:38:19 BIOCONDA INFO (ERR) * installing to library ‘/opt/mambaforge/envs/bioconda/conda-bld/r-azimuth_1710538001485/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/R/library’
21:38:19 BIOCONDA INFO (ERR) * installing *source* package ‘Azimuth’ ...
21:38:19 BIOCONDA INFO (ERR) ** using staged installation
21:38:19 BIOCONDA INFO (ERR) ** libs
21:38:21 BIOCONDA INFO (ERR) using C++ compiler: ‘clang version 15.0.7’
21:38:21 BIOCONDA INFO (ERR) using C++11
21:38:21 BIOCONDA INFO (ERR) using SDK: ‘’
.21:38:40 BIOCONDA INFO (ERR) dyld[31796]: Library not loaded: '@rpath/libtapi.dylib'
21:38:40 BIOCONDA INFO (ERR)   Referenced from: '/opt/mambaforge/envs/bioconda/pkgs/ld64_osx-64-609-h0fd476b_15/bin/x86_64-apple-darwin13.4.0-ld'
21:38:40 BIOCONDA INFO (ERR)   Reason: tried: '/opt/mambaforge/envs/bioconda/pkgs/ld64_osx-64-609-h0fd476b_15/bin/../lib/libtapi.dylib' (no such file), '/opt/mambaforge/envs/bioconda/pkgs/ld64_osx-64-609-h0fd476b_15/bin/../lib/libtapi.dylib' (no such file), '/usr/local/lib/libtapi.dylib' (no such file), '/usr/lib/libtapi.dylib' (no such file)
21:38:40 BIOCONDA INFO (ERR) clang-15: error: unable to execute command: Abort trap: 6
21:38:40 BIOCONDA INFO (ERR) clang-15: error: linker command failed due to signal (use -v to see invocation)
21:38:40 BIOCONDA INFO (ERR) make: *** [/opt/mambaforge/envs/bioconda/conda-bld/r-azimuth_1710538001485/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/R/share/make/shlib.mk:10: Azimuth.dylib] Error 1
21:38:40 BIOCONDA INFO (ERR) ERROR: compilation failed for package ‘Azimuth’
```

**Comment by mencian** [comment]
Seems to be a transient error - thanks @cbrueffer!

**Review by mencian — APPROVED** [review]

**Comment by cbrueffer** [comment]
Excellent, thanks @mencian !

**Pull request merged**
