### PR TITLE
added recipe for itk

### PR DESCRIPTION
**Pull request by ThomasWollmann**
* [x] I have read the guidelines above.
* [x] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by ThomasWollmann** [comment]
Failed cause of too long compile log. What is the standard way of solving this?

**Comment by ThomasWollmann** [comment]
Maybe we can remove some libraries from the superbuild.

**Comment by ThomasWollmann** [comment]
Still "The log length has exceeded the limit of 4 MB"

**Comment by ThomasWollmann** [comment]
Seems like the build is using two versions of libgcc

**Comment by bgruening** [comment]
@bioconda/core any idea?

**Comment by johanneskoester** [comment]
I think this is the true error: https://travis-ci.org/bioconda/bioconda-recipes/jobs/191600859#L9862. Looks like it needs something from glibc 3.4*. However, we build on CentOS 6 with glibc 2.14*. If that is the case, I think the only solution would be a patch?

**Comment by bgruening** [comment]
@ThomasWollmann can you please this PR up, so I work on it if I have time?
Something goes wrong when you rebase? How do you do this?

**Comment by ThomasWollmann** [comment]
I'm using rebase in sourcetree

**Comment by ThomasWollmann** [comment]
This time I merged instead of rebase to avoid a malicious rebase

**Comment by ThomasWollmann** [comment]
Seems like the docker test is not evaluating "requires" of the test section correctly.

**Comment by bgruening** [comment]
Can you create a simple command?

**Comment by ThomasWollmann** [comment]
What kind of command do you prefer?

**Comment by bgruening** [comment]
I enhanced our testing a little bit to allow the PREFIX variable in test commands.

**Comment by ThomasWollmann** [comment]
Thanks a lot @bgruening !

**Comment by bgruening** [comment]
Conda and BioContainer just arrived! https://quay.io/repository/biocontainers/itk?tab=tags

**Pull request merged**
