### PR TITLE
Antismash

### PR DESCRIPTION
**Pull request by zachcp**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [X] This PR adds a new recipe.
* [X] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

This is the Antismash package for finding and classifying biosynthetic gene clusters.

### CODE REVIEW

**Comment by zachcp** [comment]
looks like linux now builds!!

but macOS is failing. DO you have any idea whats happening here? (thanks, BTW)

**Comment by bgruening** [comment]
Cool I will look into it as soon as I'm back. Can you create a activate.sh script that download all other databases after installation?

**Comment by bgruening** [comment]
Good news is that it should pass the error was just a download problem. So not our fault. For a proper activate/deactivate script you need to copy the scripts into the correct location and you need to add a deactivate script.

**Comment by zachcp** [comment]
Perhaps it is simpler for a user to download the databases prior to their first use?  I am not sure of the benefit of activate/deactivate

**Comment by bgruening** [comment]
@zachcp I think people expect from conda package that they work out of the box. An other usecase is that workflow management systems can simply install the package and everything works, without human invention. If you don't have time for this, I will try to get to it.

Thanks again!

**Comment by zachcp** [comment]
@bgruening ok, that seems like a reasonable answer.

I've changed the download script to be in the post-link.sh file as [per the instructions](https://bioconda.github.io/guidelines.html#link-and-unlink-scripts-pre-and-post-install-hooks).

Thanks again for your help

**Comment by zachcp** [comment]
looks like we're still running out of space  😢 

```
error: [Errno 28] No space left on device
```

**Comment by bgruening** [comment]
@zachcp please remove the post-link script again, I need to work more on space reduction until this will be possible :(
Sorry for taking your time :(

**Comment by zachcp** [comment]
@bgruening no prob. thanks for working on this.

**Comment by bgruening** [comment]
Thanks @zachcp!

**Comment by zachcp** [comment]
@bgruening  BOOM!

**Comment by bgruening** [comment]
!!! Now I need to update my Galaxy integration :)
Thanks @zachcp!

**Pull request merged**
