### PR TITLE
Update PureCLIP to v1.1.2

### PR DESCRIPTION
**Pull request by skrakau**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by bgruening** [comment]
Hi @skrakau!

If you add a new release, please always reset the build-number to 0. I have also added the DOI to the recipe.

Thanks for your contribution!

**Comment by skrakau** [comment]
Hi @bgruening,

Thanks! Fixed that.

**Comment by skrakau** [comment]
@bgruening sorry, overwrote your commit. Hadn't seen it ;)

**Comment by bgruening** [comment]
But now everything is gone again :)
You or me to create a new commit? :)

**Comment by skrakau** [comment]
@bgruening Would be great if you could add the DOI again, I'm not sure where that belongs :) Thanks!

**Comment by bgruening** [comment]
Done. Please check if this is ok and I got it right.

Thanks for your contribution!

**Comment by skrakau** [comment]
Looks good, thanks!

**Pull request merged**
