### PR TITLE
Circularmapper

### PR DESCRIPTION
**Pull request by apeltzer**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by apeltzer** [comment]
@bioconda/core

**Comment by daler** [comment]
@apeltzer I'm on the fence on whether or not the realign portion should be split out into a separate recipe. On one hand it has its own sha256 and version, and generally we try to avoid that, but these look like two tightly coupled tools that you're maintaining in the same repo so it's probably OK. Are the releases of the tools always synchronized?

**Comment by apeltzer** [comment]
Yes, they are built automatically using TravisCI based on a grade build script and are thus always in sync. Can’t figure out why building doesn’t work but I guess it’s just a minor thing I missed. I can split things but these actually belong quite tightly together.

**Comment by daler** [comment]
@apeltzer I think that's fine then. Looks like your issue here is that the sha256 doesn't match? (I'm getting b91e0a58761f9854a89c526c45e58f716ccb5bcb456d2e9707fc127865c74f79).

**Comment by apeltzer** [comment]
Hm, nope. Thats not it :/

**Comment by apeltzer** [comment]
This is weird - I can build this with `conda-build recipe/circularmapper` locally and the recipe works too

**Comment by apeltzer** [comment]
Since @daler already had a look and things build fine now - I guess its okay to merge this in?

**Comment by daler** [comment]
Yep, thanks!

**Pull request merged**
