### PR TITLE
Du Novo: Update to 2.0.8.

### PR DESCRIPTION
**Pull request by NickSto**
Update to install Du Novo 2.0.8 (a bugfix release).
Also, change networkx dependency to version 1.10 to allow compatibility with Galaxy Toolshed (which lacks a 1.11).

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by bgruening** [comment]
> Galaxy Toolshed (which lacks a 1.11)

Are you referring to `packages` here? Packages are depreacted and you should not rely on them. Use in your conda package what ever fits your application and Galaxy will use it.

**Comment by NickSto** [comment]
Oh, I'm not sure what you mean by `packages`. I think the issue was that my tool `<requirements>` originally included networkx 1.9, since there was no `package_networkx_1_11` in the Toolshed. Then later I changed the conda `meta.yaml` to say networkx 1.11, since it exists in conda. But I didn't realize that means Du Novo would be installed via conda with networkx 1.11, but the tool says it requires 1.9, so there was a conflict. 1.10 exists in both, so it resolves the conflict.

**Comment by bgruening** [comment]
> Oh, I'm not sure what you mean by packages

-> package_networkx_1_11 ;)

Completely, forget about those packages. They are not needed anymore and you don't need to care about them. What I'm saying don't change this recipe just because such a package is missing in the TS.

**Comment by NickSto** [comment]
Oh okay, that's what I thought.

But if I specify 1.11 in conda and 1.9 in the tool xml, I wasn't able to actually run the tool because of the version conflict. I installed via conda and told Galaxy to resolve all dependencies with conda. Was I doing something wrong?

**Comment by bgruening** [comment]
Do you have the error message?

**Comment by NickSto** [comment]
Oh, not on hand. Let me reproduce it.

Btw, for now, could I just remove the version number in `meta.yaml`? That's how it was when it was working and before I started messing with it.

Maybe later I can PR a working version with a version number specified.

**Comment by NickSto** [comment]
..and I'd really like to get this version out :D

**Comment by bgruening** [comment]
Just pinned it to <2.0.

**Comment by NickSto** [comment]
Ohh yeah that works!

**Pull request merged**
