### PR TITLE
Update build for freebayes to include scripts

### PR DESCRIPTION
**Pull request by jpuritz**
New build was missing some non-compiled scripts.
----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by jpuritz** [comment]
Not sure what the problem is.  It throws a build error on OS X, but I don't see one in the CI output.

**Comment by jts** [comment]
@jpuritz while you're working on the freebayes build could you look into the python dependency? The current 1.3.5 package depends on python >= 3.9 which causes conflicts with many other packages that use older versions of python.

**Comment by jpuritz** [comment]
> @jpuritz while you're working on the freebayes build could you look into the python dependency? The current 1.3.5 package depends on python >= 3.9 which causes conflicts with many other packages that use older versions of python.

I don't develop the actual package. I am just help maintain the bioconda build.  What requires python >=3.9?

**Comment by jts** [comment]
Sorry, I wasn't clear. As far as I can tell from meta.yaml it only depends on python >=3 but the built package depends on python 3.9:

https://bioconda.github.io/recipes/freebayes/README.html

I don't know why its been built against 3.9.

**Comment by jpuritz** [comment]
@bioconda-bot please add label

**Comment by jpuritz** [comment]
@dpryan79 Wouldn't normally tag you, but this got delayed by having to update multiple dependent libraries.  Wasn't sure anyone would actually see it anymore.

**Comment by jnumm** [comment]
You could run the tests, i.e. `meson test --timeout-multiplier 8 --print-errorlogs`. (Command options taken from https://github.com/freebayes/freebayes/blob/master/.travis.yml#L26.)

**Comment by jpuritz** [comment]
> Sorry, I wasn't clear. As far as I can tell from meta.yaml it only depends on python >=3 but the built package depends on python 3.9:
> 
> https://bioconda.github.io/recipes/freebayes/README.html
> 
> I don't know why its been built against 3.9.

I don't see what is requiring 3.9.  Anyone else have thoughts?

**Comment by jpuritz** [comment]
@BiocondaBot please fetch artifacts

**Review by dpryan79 — APPROVED** [review]

**Comment by jpuritz** [comment]
@BiocondaBot please fetch artifacts

**Comment by jpuritz** [comment]
@BiocondaBot please fetch artifacts

**Comment by jpuritz** [comment]
@BiocondaBot please merge

**Pull request merged**
