### PR TITLE
Bumping varfish-annotator-cli version to v0.7.

### PR DESCRIPTION
**Pull request by holtgrewe**
Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it. Note that if you are not already a member of the bioconda project (meaning that you can't add this label), please ping `@bioconda/core` so that your PR can be reviewed and merged (please note if you'd like to be added to the bioconda project). Please see https://github.com/bioconda/bioconda-recipes/issues/15332 for more details.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by holtgrewe** [comment]
ping @bioconda/core

**Comment by holtgrewe** [comment]
@bioconda/core could someone have a look VM assignment failed. I'm only bumping the version...

**Comment by dpryan79** [comment]
Random circleci bug, I hit rerun.

**Comment by dpryan79** [comment]
Sorry, hit the wrong button. That was a random circleci bug, I've hit rerun.

**Comment by holtgrewe** [comment]
@dpryan79 could you approve the change?

**Comment by dpryan79** [comment]
Yup! Looks like circleci is generally having issues with OSX builds at the moment. This might have to wait until they get things fixed to get merged.

**Comment by holtgrewe** [comment]
@dpryan79 Thanks, you're the best. How would I proceed now?

**Comment by dpryan79** [comment]
I can force merge this if it's urgent (it's a noarch: generic package, so the OSX test won't matter), otherwise just give circleci a few hours to get things working again.

**Comment by epruesse** [comment]
Looks like CircleCI is fixed.

@biocondabot merge

**Pull request merged**
