### PR TITLE
update Pangolins constellations requirement

### PR DESCRIPTION
**Pull request by rpetit3**
This should capture SC2 variant B.1.1.529 (Omicron)

Describe your pull request here

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by rpetit3** [comment]
Constellations 0.0.24 was just merged will retrigger shortly

**Comment by rpetit3** [comment]
```
19:23:15 BIOCONDA INFO (OUT) + pangolin --all-versions
19:23:15 BIOCONDA INFO (OUT) pangolin: 3.1.16
19:23:15 BIOCONDA INFO (OUT) pangolearn: 2021-11-18
19:23:15 BIOCONDA INFO (OUT) constellations: v0.0.24
19:23:15 BIOCONDA INFO (OUT) scorpio: 0.3.14
19:23:15 BIOCONDA INFO (OUT) pango-designation used by pangoLEARN/Usher: v1.2.97
19:23:15 BIOCONDA INFO (OUT) pango-designation aliases: 1.2.102
```

Omicron added to constellations 0.0.24 https://github.com/cov-lineages/constellations/releases/tag/v0.0.24

**Review by bgruening — APPROVED** [review]

**Comment by rpetit3** [comment]
```
docker run --rm -u $(id -u):$(id -g) -v ${PWD}:/data quay.io/biocontainers/pangolin:3.1.16--pyhdfd78af_2 pangolin -o /data /data/EPI_ISL_6810487.fasta
```

```
cat lineage_report.csv
taxon,lineage,conflict,ambiguity_score,scorpio_call,scorpio_support,scorpio_conflict,version,pangolin_version,pangoLEARN_version,pango_version,status,note
hCoV-19/South_Africa/CERI-KRISP-K032249/2021|EPI_ISL_6810487|2021-11-22,B.1.1.529,0.0,0.992115341293084,Omicron (B.1.1.529-like),0.893600,0.000000,PLEARN-v1.2.97,3.1.16,2021-11-18,v1.2.97,passed_qc,scorpio call: Alt alleles 42; Ref alleles 0; Amb alleles 5; Oth alleles 0; scorpio replaced lineage assignment AZ.2
```

**Comment by rpetit3** [comment]
@BiocondaBot please merge

**Comment by rpetit3** [comment]
Thank you @bgruening

**Pull request merged**
