### PR TITLE
Update piscem to 0.7.0

### PR DESCRIPTION
**Pull request by rob-p**
Bump piscem to v0.7.0

Describe your pull request here

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

### General instructions

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

### Instructions for avoiding API, ABI, and CLI breakage issues
Conda is able to record and lock (a.k.a. pin) dependency versions used at build time of other recipes.
This way, one can avoid that expectations of a downstream recipe with regards to API, ABI, or CLI are violated by later changes in the recipe.
If not already present in the meta.yaml, make sure to specify `run_exports` (see [here](https://bioconda.github.io/contributor/linting.html#missing-run-exports) for the rationale and comprehensive explanation).
Add a `run_exports` section like this:

```yaml
build:
  run_exports:
    - ...

```

with `...` being one of:

| Case                             | run_exports statement                                               |
| -------------------------------- | ------------------------------------------------------------------- |
| semantic versioning              | `{{ pin_subpackage("myrecipe", max_pin="x") }}`     |
| semantic versioning (0.x.x)      | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}`   |
| known breakage in minor versions | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| known breakage in patch versions | `{{ pin_subpackage("myrecipe", max_pin="x.x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| calendar versioning              | `{{ pin_subpackage("myrecipe", max_pin=None) }}`    |

while replacing `"myrecipe"` with either `name` if a `name|lower` variable is defined in your recipe or with the lowercase name of the package in quotes.

### Bot commands for PR management

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

Note that the <code>@BiocondaBot please merge</code> command is now depreciated. Please just squash and merge instead.

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by rob-p** [comment]
Is there any way to get access to a more useful log?  The build log on Azure shows no errors, and is probably just cut off before anything useful it output.

**Comment by rob-p** [comment]
Is it possible to bump the timeout? It is a heavy build because it compiles template heavy C++ under the hood. But it should hopefully be close to done at that point.

**Comment by mjsteinbaugh** [comment]
@rob-p That's a really good question -- I'm guessing the timeout is hard limited at 45 minutes currently, but I'll check with the bioconda team

**Comment by mjsteinbaugh** [comment]
See related question on bioconda gitter channel here: https://matrix.to/#/!MhHkICgthNLZeLiygG:gitter.im/$8pr-IaSAdbe8AWLwrphc_Nk0v-109TM-tcnb7FTMDuI?via=gitter.im&via=matrix.org&via=staffchat.ethz.ch

**Comment by mfansler** [comment]
> @ rob-p Looks like the build timed out after 45 minutes: "We stopped hearing from agent Hosted Agent."

Is there really a 45 min time limit? It's been run three times and the durations are all slightly different. What is consistent is the stopping point: `Compiling num_cpus v1.16.0` Is there code in there that could cause a crash?

**Comment by rob-p** [comment]
It could be other resource exhaustion maybe, but the compiler shouldn't crash ;P. I used cargo-dist to make pre-compiled executables for linux x86, apple x86 and apple arm without issue on 3 different machines.

**Comment by aliciaaevans** [comment]
I am pretty sure the timeout is something like 6 hours. It's likely you are running into some other limit or behavior Azure doesn't like.

>Anything that terminates an agent process, starves it for CPU, or blocks its network access can cause this error.

**Comment by rob-p** [comment]
Do you know what the RAM limits are on the Azure instances?  I'm really curious what could be going on here.  It's a resource intensive build for certain, but probably not even close to the most resource intensive in bioconda!

**Comment by aliciaaevans** [comment]
@rob-p 2 CPU cores, 7 GB RAM

https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#hardware

**Comment by mjsteinbaugh** [comment]
Seems like RAM could be a likely culprit here

**Comment by rob-p** [comment]
Indeed. The c++ compiler is generating a lot of template instantiations here; that's probably not helping out.

**Comment by rob-p** [comment]
@mjsteinbaugh / @aliciaaevans — is there any way to request a high-memory builder instance just to see if this is the issue?

**Comment by mjsteinbaugh** [comment]
Not that I'm aware of but I think that's a great idea

**Comment by aliciaaevans** [comment]
@rob-p As far as I know, I don't think we have that option. The other CI providers we use for other tasks have similar specs for their hosted workers. If I can find out anything from the core team, I will let you know.

**Comment by rob-p** [comment]
Thanks, Alicia!

**Comment by rob-p** [comment]
Hi @mjsteinbaugh and @aliciaaevans — happy new year!  Any update on this?  It's kind of blocking as we have several users who can't seem to build locally and are relying on bioconda for this executable.

**Comment by aliciaaevans** [comment]
@rob-p I'm trying this out on GitHub actions to see if it could be built with our `bulk` branch CI.

**Comment by aliciaaevans** [comment]
@rob-p the GitHub Action didn't succeed, but perhaps there is better logging than Azure? https://github.com/bioconda/bioconda-recipes/actions/runs/7424254340/job/20203474938

**Comment by rob-p** [comment]
Thanks @aliciaaevans! Is the setup the same there? There I get:

+-v3/src/c++11/chrono.cc:88: undefined reference to `clock_gettime'


But I notice it's using gcc 12.x rather than 11.x (ofc the problem comes from C++ and not rust).

**Comment by aliciaaevans** [comment]
@rob-p I reran it with your change so now it's using gcc 11.x. Unfortunately, it still has the same clock_gettime error. https://github.com/bioconda/bioconda-recipes/actions/runs/7452446233/job/20275728519 

As far as the Bioconda setup, there shouldn't be much difference between Azure Pipelines and GitHub Actions. Both are using `--docker` for bioconda-utils so the build takes place in a Docker container. The resources seem comparable also: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources

**Comment by rob-p** [comment]
Hi @aliciaaevans,

  Thanks.  I don't know why `-lrt` is necessary — it shouldn't be.  Anyway, I added it upstream and bumped the recipe.  Can I rerun the github action, or do you need to do that?

Thanks!
Rob

**Comment by aliciaaevans** [comment]
@rob-p I've been running this on a test branch I already had setup to test some unrelated changes for the bulk CI, so I copied over your change to that branch to rerun. (Just rerunning the job didn't pick up the latest from this branch.)  https://github.com/bioconda/bioconda-recipes/actions/runs/7467032061/job/20319675231

**Comment by rob-p** [comment]
> @rob-p I've been running this on a test branch I already had setup to test some unrelated changes for the bulk CI, so I copied over your change to that branch to rerun. (Just rerunning the job didn't pick up the latest from this branch.) https://github.com/bioconda/bioconda-recipes/actions/runs/7467032061/job/20319675231

Thanks! This one seems to have gotten further; it's still going!

**Comment by rob-p** [comment]
Hrmm... it's *still* going. I think the GitHub builder may just have run out of memory like the Azure builder, but the "killer" process just isn't as impatient.

**Comment by rob-p** [comment]
So, @mjsteinbaugh and @aliciaaevans — another update here. I don't know *why* the builders are dying.  The memory usage is still my leading hypothesis, but I tried to measure the memory usage locally. Compiling the rust components takes ~200MB, Cuttlefish takes ~1.6G and the C++ piscem part ~2G.  These are not (supposed to be) built simultaneously, but even if they were, we'd still be substantially below the 7G memory barrier.  I don't know if there's a way to better instrument resource usage at the time of killing a builder, but I am not sure where to go from here or what to try next.

**Comment by aliciaaevans** [comment]
Hi @rob-p,

I'm running that latest change on GitHub actions: https://github.com/bioconda/bioconda-recipes/actions/runs/7477679168/job/20350910772

I was able to discuss this with some more experienced core members today. @mbargull noted that some changes are in the works to make conda-build itself more efficient. conda-build can be memory intensive which may be what's pushing this over the 7GB limit. I'm not sure when those changes will be available, though.

Anything upstream you can think of to try would be helpful.

**Comment by rob-p** [comment]
@mjsteinbaugh @aliciaaevans — So the linux build *finally* succeeded, still waiting to see what happens with OSX.  That was a huge PITA, and I feel like the solutions are super brittle. Basically, I had to force a single build thread everywhere to ensure that the C++ compiler (memory hog) isn't running in parallel everywhere. Then I had to invoke some rather arcane parameters to g++ to change how aggressive it is at cleaning up it's own garbage.

While I was able to get this to work (on linux at least), I feel like future versions of this recipe, and probably others, are likely to run into similar issues.  It would be a huge boon if the available memory could be made greater (either by upping the allocation for the builders, or by requiring less for the host image before the compiler even gets going).  Apparently a peak RSS of 2.2G was too much for the image to handle.

**Comment by rob-p** [comment]
Hi @mjsteinbaugh and @aliciaaevans,

  The OSX build just worked — didn't need the strange parameters for clang, apparently.  Anyway, it builds on both platforms 🥳 .  I updated to the latest changes on the base branch. When the checks complete, can you please merge this PR?

Thanks again for all of your help, and I'd be happy to discuss these issues with anyone on the core team to figure out how to (1) convey to others having problems like this what they might do and (2) suggest what kind of changes might be necessary to the build configurations to avoid these kinds of issues in the future — or at least raise the bar a lot higher.

Thanks!
Rob

**Review by aliciaaevans — APPROVED** [review]

**Comment by rob-p** [comment]
Thank you @aliciaaevans!

**Comment by aliciaaevans** [comment]
@rob-p Glad you were able to figure out a solution! I'm not the most knowledgeable on the details of C++ to be honest, but I'd be interested in hearing your findings/suggestions.

If you have the time and want to write up and issue or add any tips in https://github.com/bioconda/bioconda-docs (maybe contributor guidelines?) that would be welcome, of course.

**Pull request merged**
