### PR TITLE
Update b2btools to 3.0.6

### PR DESCRIPTION
**Pull request by agdiaz**
Update b2bTools package to v3.0.6 published on 4th July 2023 on PyPi.
----

## Rationale

This PR includes the recipe changes to support the new version as well as new test scenarios to validate the installation and usage of this package.

## Main changes included in v3.0.6

- Improved dependency management: defining frozen versions of the libraries in use by the predictors. 
- New Command Line Interface: support output in JSON and tabular formats.  
- Metadata: New output file including statistics and timing metrics

## Tasks

- [x] Update meta.yml in order to update the references to v3.0.6
- [x] Add test scenarios to cover both available execution modes: Single sequence analysis and MSA analysis.

## Links

- [Package homepage on PyPi](https://pypi.org/project/b2bTools/)
- [New version 3.0.6 on PyPi](https://pypi.org/project/b2bTools/3.0.6/#files)

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by agdiaz** [comment]
@BiocondaBot please update

**Comment by agdiaz** [comment]
Dear @bioconda/core, how are you doing? 
I hope doing well. 

I would like to know if there is a particular problem with my PR when it is processed by Azure Pipelines. I have updated the recipe of the project and included more tests. However, all my attempts to run the checks failed when installing bioconda-utils. 

[Error example link](https://dev.azure.com/bioconda/bioconda-recipes/_build/results?buildId=36348&view=logs&j=eb1ca712-fec5-5d93-deb0-40983fe61f2f&t=8cb71ada-b7e7-54e5-39da-f5f7c855484f&l=744):

```console
2023-07-05T12:13:29.4920466Z critical libmamba Pathname can't be converted from UTF-8 to current locale.
2023-07-05T12:13:29.5016725Z error    libmamba Error opening for reading "/opt/mambaforge/pkgs/python-libarchive-c-5.0-py38h578d9bd_0/info/index.json": No such file or directory
2023-07-05T12:13:29.5017656Z error    libmamba Error when extracting package: [json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - unexpected end of input; expected '[', '{', or a literal
2023-07-05T12:13:29.5018150Z python-libarchive-c-5.0-py38h578d9bd_0.conda extraction failed
2023-07-05T12:13:42.0241053Z Found incorrect download: python-libarchive-c. Aborting
2023-07-05T12:13:42.0329182Z 
2023-07-05T12:13:42.0329694Z # >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<
2023-07-05T12:13:42.0329758Z 
2023-07-05T12:13:42.0330010Z     Traceback (most recent call last):
2023-07-05T12:13:42.0330521Z       File "/opt/mambaforge/lib/python3.10/site-packages/conda/exceptions.py", line 1124, in __call__
2023-07-05T12:13:42.0330727Z         return func(*args, **kwargs)
2023-07-05T12:13:42.0331039Z       File "/opt/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 941, in exception_converter
2023-07-05T12:13:42.0331233Z         raise e
2023-07-05T12:13:42.0331535Z       File "/opt/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 934, in exception_converter
2023-07-05T12:13:42.0331736Z         exit_code = _wrapped_main(*args, **kwargs)
2023-07-05T12:13:42.0332057Z       File "/opt/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 892, in _wrapped_main
2023-07-05T12:13:42.0332247Z         result = do_call(parsed_args, p)
2023-07-05T12:13:42.0332555Z       File "/opt/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 758, in do_call
2023-07-05T12:13:42.0332740Z         exit_code = create(args, parser)
2023-07-05T12:13:42.0333211Z       File "/opt/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 632, in create
2023-07-05T12:13:42.0333402Z         return install(args, parser, "create")
2023-07-05T12:13:42.0333705Z       File "/opt/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 588, in install
2023-07-05T12:13:42.0333896Z         transaction.fetch_extract_packages()
2023-07-05T12:13:42.0334608Z     RuntimeError: Found incorrect download: python-libarchive-c. Aborting
2023-07-05T12:13:42.0334704Z 
2023-07-05T12:13:42.0335092Z `$ /opt/mambaforge/bin/mamba create -n bioconda -y --file https://raw.githubusercontent.com/bioconda/bioconda-utils/v2.3.2/bioconda_utils/bioconda_utils-requirements.txt`
2023-07-05T12:13:42.0335274Z 
2023-07-05T12:13:42.0335387Z   environment variables:
2023-07-05T12:13:42.0335646Z BUILD_DEFINITIONFOLDERPATH=\
2023-07-05T12:13:42.0335802Z BUILD_REPOSITORY_LOCALPATH=/home/vsts/work/1/s
2023-07-05T12:13:42.0335949Z                  CIO_TEST=<not set>
2023-07-05T12:13:42.0336098Z                     CONDA=/usr/share/miniconda
2023-07-05T12:13:42.0336242Z                 CONDA_EXE=/opt/mambaforge/bin/conda
2023-07-05T12:13:42.0336413Z          CONDA_PYTHON_EXE=/opt/mambaforge/bin/python
2023-07-05T12:13:42.0336566Z                CONDA_ROOT=/opt/mambaforge
2023-07-05T12:13:42.0336709Z               CONDA_SHLVL=0
2023-07-05T12:13:42.0336837Z            CURL_CA_BUNDLE=<not set>
2023-07-05T12:13:42.0336984Z                LD_PRELOAD=<not set>
2023-07-05T12:13:42.0337157Z                      PATH=/opt/mambaforge/condabin:/opt/mambaforge/bin:/opt/mambaforge/bin:/home
2023-07-05T12:13:42.0337373Z                           /vsts/.local/bin:/opt/pipx_bin:/home/vsts/.cargo/bin:/home/vsts/.confi
2023-07-05T12:13:42.0337570Z                           g/composer/vendor/bin:/usr/local/.ghcup/bin:/home/vsts/.dotnet/tools:/
2023-07-05T12:13:42.0337781Z                           snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:
2023-07-05T12:13:42.0337954Z                           /usr/games:/usr/local/games:/snap/bin
2023-07-05T12:13:42.0338098Z        REQUESTS_CA_BUNDLE=<not set>
2023-07-05T12:13:42.0338343Z         SELENIUM_JAR_PATH=/usr/share/java/selenium-server.jar
2023-07-05T12:13:42.0338498Z             SSL_CERT_FILE=<not set>
2023-07-05T12:13:42.0338652Z                SWIFT_PATH=/usr/share/swift/usr/bin
2023-07-05T12:13:42.0338719Z 
2023-07-05T12:13:42.0338835Z      active environment : None
2023-07-05T12:13:42.0338972Z             shell level : 0
2023-07-05T12:13:42.0339106Z        user config file : /home/vsts/.condarc
2023-07-05T12:13:42.0339276Z  populated config files : /opt/mambaforge/.condarc
2023-07-05T12:13:42.0339421Z                           /home/vsts/.condarc
2023-07-05T12:13:42.0339558Z           conda version : 23.1.0
2023-07-05T12:13:42.0339764Z     conda-build version : not installed
2023-07-05T12:13:42.0339925Z          python version : 3.10.10.final.0
2023-07-05T12:13:42.0340074Z        virtual packages : __archspec=1=x86_64
2023-07-05T12:13:42.0340225Z                           __glibc=2.35=0
2023-07-05T12:13:42.0340348Z                           __linux=5.15.0=0
2023-07-05T12:13:42.0340467Z                           __unix=0=0
2023-07-05T12:13:42.0340616Z        base environment : /opt/mambaforge  (writable)
2023-07-05T12:13:42.0340777Z       conda av data dir : /opt/mambaforge/etc/conda
2023-07-05T12:13:42.0340934Z   conda av metadata url : None
2023-07-05T12:13:42.0341184Z            channel URLs : https://conda.anaconda.org/conda-forge/linux-64
2023-07-05T12:13:42.0341457Z                           https://conda.anaconda.org/conda-forge/noarch
2023-07-05T12:13:42.0341628Z                           https://conda.anaconda.org/bioconda/linux-64
2023-07-05T12:13:42.0341806Z                           https://conda.anaconda.org/bioconda/noarch
2023-07-05T12:13:42.0341973Z                           https://repo.anaconda.com/pkgs/main/linux-64
2023-07-05T12:13:42.0342146Z                           https://repo.anaconda.com/pkgs/main/noarch
2023-07-05T12:13:42.0342304Z                           https://repo.anaconda.com/pkgs/r/linux-64
2023-07-05T12:13:42.0342474Z                           https://repo.anaconda.com/pkgs/r/noarch
2023-07-05T12:13:42.0342625Z           package cache : /opt/mambaforge/pkgs
2023-07-05T12:13:42.0342775Z                           /home/vsts/.conda/pkgs
2023-07-05T12:13:42.0342915Z        envs directories : /opt/mambaforge/envs
2023-07-05T12:13:42.0343123Z                           /home/vsts/.conda/envs
2023-07-05T12:13:42.0343263Z                platform : linux-64
2023-07-05T12:13:42.0343592Z              user-agent : conda/23.1.0 requests/2.28.2 CPython/3.10.10 Linux/5.15.0-1040-azure ubuntu/22.04.2 glibc/2.35
2023-07-05T12:13:42.0343844Z                 UID:GID : 1001:123
2023-07-05T12:13:42.0343974Z              netrc file : None
2023-07-05T12:13:42.0344168Z            offline mode : False
2023-07-05T12:13:42.0344225Z 
2023-07-05T12:13:42.0344266Z 
2023-07-05T12:13:42.0344423Z An unexpected error has occurred. Conda has prepared the above report.
2023-07-05T12:13:42.0344515Z 
2023-07-05T12:13:42.0344555Z 
2023-07-05T12:13:42.0346284Z Looking for: ["python[version='>=3.7']", 'conda=23.3', 'boa=0.15', 'conda-build=3.24', 'conda-verify=3.1', 'argh=0.26', 'colorlog=4.8', "tqdm[version='>=4.26']", 'yaspin==2', 'ruamel_yaml=0.15', 'pyaml=17.12', 'networkx=2', 'pandas=1.4', 'numpy=1.19', 'libblas=[build=*openblas]', 'boltons=23', 'jsonschema=3.2', "pyopenssl[version='>=22.1']", 'conda-forge-pinning==2023.05.06.13.08.41', 'anaconda-client=1.6', 'involucro=1.1', 'skopeo=1.11', 'git=2', 'regex==2022.7.9', 'aiohttp=3.8', 'aiohttp-jinja2', 'aiohttp-session', 'aiohttp-security', 'aiofiles=0.8', 'aioftp=0.12', 'backoff=1.6', 'cachetools=3.0', "gitpython[version='>=3.0.8,3.0.*']", 'gidgethub=3.0', "pyjwt[version='>=2.4.0']", 'beautifulsoup4=4.8', "galaxy-lib[version='>=18.9.1']", "jinja2[version='>=2.10.1,<3']", "markupsafe[version='<2.1']", "sphinx[version='>=4.1']", 'celery', 'sphinx-autodoc-typehints', 'alabaster=0.7', 'docutils', 'markdown', 'graphviz', 'requests=2.22', 'pygithub', 'diskcache=5', 'appdirs=1', 'tabulate==0.9']
2023-07-05T12:13:42.0347234Z 
2023-07-05T12:13:42.1852421Z ##[error]Bash exited with code '1'.
2023-07-05T12:13:42.1865793Z ##[section]Finishing: Install bioconda-utils
```

I noticed that other pipelines are failing at the same step. Is there anything that I could do help to resolve this issue? 

Thanks in advance for your help and guidance.
Kind regards from Brussels,

**Comment by agdiaz** [comment]
@BiocondaBot please update

**Comment by agdiaz** [comment]
@BiocondaBot please fetch artifacts

**Comment by agdiaz** [comment]
@BiocondaBot please fetch artifacts

**Comment by agdiaz** [comment]
@BiocondaBot please add label

**Comment by agdiaz** [comment]
This PR replaces https://github.com/bioconda/bioconda-recipes/pull/41831 (automatically created a couple of days ago)

**Comment by dpryan79** [comment]
@BiocondaBot please fetch artifacts

**Review by dpryan79 — APPROVED** [review]

**Pull request merged**
