### PR TITLE
Create r-breakaway v.4.7.9 recipe

### PR DESCRIPTION
**Pull request by pschloss**
This is a PR to create a recipe for r-breakaway (v.4.7.9). There was a previous version (v.3.0) of this package on bioconda that was ported over to conda. Unfortunately, because `breakaway` has a bioconductor dependency (`bioconductor-phyloseq`) it is not possible to update the recipe on conda. 

See: https://github.com/conda-forge/r-breakaway-feedstock/pull/4#issuecomment-1112406403

please review & merge @bioconda/team

### CODE REVIEW

**Comment by pschloss** [comment]
I suspect that the linter failed because the package is also in conda-forge. Let me know if you want me to change the name of this version of the package to something like `r-breakaway-bio` or if there's another solution.

**Comment by cbrueffer** [comment]
Thanks @pschloss; could you trim the comments in the files? Ideally they should look similar to the ones in the conda-forge recipe.

As for the LINT check, you can skip the "already in conda-forge" one by adding `[lint skip in_other_channels for recipes/r-breakaway]` to the commit message.

**Comment by pschloss** [comment]
Sorry, I'm not sure what I'm doing wrong with the commit message. Ideas?

**Comment by pschloss** [comment]
Thank you @dpryan79! I'm still figuring the system out

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Pull request merged**
