### PR TITLE
Updated minimap2 and mappy to v2.11

### PR DESCRIPTION
**Pull request by lh3**
* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [X] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [X] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by lh3** [comment]
Error messages:
```txt
04:47:01 BIOCONDA ERROR COMMAND FAILED: docker run --net host --rm -v /tmp/tmpgbe3moyq/build_script.bash:/opt/build_script.bash -v /home/circleci/project/miniconda/conda-bld:/opt/host-conda-bld -v /home/circleci/project/recipes/minimap2:/opt/recipe -e LANG=en_US.UTF-8 -e CONDA_ROOT=/home/circleci/project/miniconda -e CONDA_ALLOW_SOFTLINKS=false -e HOST_USER_ID=1001 tmp-bioconda-builder /bin/bash /opt/build_script.bash
04:47:01 BIOCONDA ERROR STDOUT+STDERR:
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
```

**Comment by bgruening** [comment]
This is just a warning. The error is below: `bseq.c:1:18: fatal error: zlib.h: No such file or directory
 #include <zlib.h>`

**Comment by bgruening** [comment]
mappy needs to be compiled, right? so you probably need to add the build section with the compiler()

**Comment by lh3** [comment]
For minimap2, I am still getting the same error:
```
bseq.c:1:18: fatal error: zlib.h: No such file or directory
 #include <zlib.h>
                  ^
compilation terminated.
make: *** [bseq.o] Error 1
```
Could you have a look? Compiling mappy failed for a different reason. I will fix that later. Thanks.

**Comment by lh3** [comment]
The new build system doesn't set the include and library paths automatically. For C/C++ projects, this requires `build.sh` to explicitly set the two paths with something like:
```sh
export CPATH=$PREFIX/include
export LIBRARY_PATH=$PREFIX/lib
```
Otherwise, the compiler and the linker won't find relevant files. Ideally, the build system should set them up.

**Pull request merged**
