### PR TITLE
Updating nanosv 1.1.2

### PR DESCRIPTION
**Pull request by wdecoster**
* [x ] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [ ] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

[NanoSV](https://github.com/mroosmalen/nanosv) has been rewritten in Python. I used conda skeleton pypi to create the meta.yaml

### CODE REVIEW

**Comment by wdecoster** [comment]
I've just swapped out the "host" key by "build" and this solved an error, but now I have:

```
Can't build /opt/recipe due to unsatisfiable dependencies:
The following specifications were found to be in conflict:
  - configparser -> python 2.7*
  - python 3.5*
Use "conda info <package>" to see the dependencies for each package.

Typically if a conflict is with the Python or R
packages, the other package needs to be rebuilt
(e.g., a conflict with 'python 3.5*' and 'x' means
'x' isn't build for Python 3.5 and needs to be rebuilt.
```

**Comment by daler** [comment]
`configparser` is built-in module in py3; I think if you add a `# [py27]` to the respective dependency lines it should be OK.

**Comment by wdecoster** [comment]
Thanks for the suggestion, I'll try that. Makes me realize that `# [py27]` is not just a comment...

**Comment by wdecoster** [comment]
Okay looks like I need to change the test because NanoSV, when imported, starts checking arguments:

```
run_test.py: error: the following arguments are required: bam
import: 'nanosv'
```

**Pull request merged**
