### PR TITLE
Updated source_url for *PhlAn packages

### PR DESCRIPTION
**Pull request by fbeghini**

### CODE REVIEW

**Comment by fbeghini** [comment]
@BiocondaBot please add label

**Comment by fbeghini** [comment]
@bioconda/core `export2graphlan` is no more in the build blacklist.

**Comment by druvus** [comment]
@BiocondaBot please fetch artifacts

**Comment by druvus** [comment]
@BiocondaBot please merge

**Comment by druvus** [comment]
@BiocondaBot please merge

**Pull request merged**
