### PR TITLE
update metav recipes

### PR DESCRIPTION
**Pull request by ZhijianZhou01**
add two software dependencies (samtools >=1.14, salmon >=1.10.0) for metav to resolve the running bug when [Trinity](https://github.com/trinityrnaseq/trinityrnaseq) is called.

### CODE REVIEW

**Comment by ZhijianZhou01** [comment]
@BiocondaBot please add label

**Comment by ZhijianZhou01** [comment]
@bioconda/core please review & merge

**Comment by ZhijianZhou01** [comment]
@mencian Hi, could you help me merged my commit? Thank you very much.

**Review by martin-g — APPROVED** [review]

**Comment by ZhijianZhou01** [comment]
Thank you very much.

**Pull request merged**
