### PR TITLE
Require python2, json-collect-data-source does not work with python3

### PR DESCRIPTION
**Pull request by lparsons**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by cbrueffer** [comment]
I think this requires a bump of the build number.

**Comment by lparsons** [comment]
@cbrueffer Good call, done.

**Comment by cbrueffer** [comment]
Merged, thanks!

**Comment by lparsons** [comment]
@cbrueffer Looks like Travis failed for some reason on the merged commit (https://travis-ci.org/bioconda/bioconda-recipes/builds/333676465?utm_source=github_status&utm_medium=notification) Does this need attention?

**Comment by cbrueffer** [comment]
A few more packages failed to build; I'll trigger a rebuild using #7370

**Pull request merged**
