### PR TITLE
jemalloc: added tests

### PR DESCRIPTION
**Pull request by vodkatad**
* [x] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by bgruening** [comment]
I really :heart: this test!

**Comment by druvus** [comment]
I think jemalloc would build for osx using gcc. I was looking into it as a dependency for another recipe.

**Comment by vodkatad** [comment]
Sorry I've got no osx available for testing that locally :\

**Comment by bgruening** [comment]
You can simply remove the skip line and see what travis is saying :)

**Comment by druvus** [comment]
You need to update the test to look like this to handle different suffix between linux and osx.

<pre>
test:
  files:
      test.c
  commands:
    - test -e ${PREFIX}/lib/libjemalloc.dylib # [osx]
    - test -e ${PREFIX}/lib/libjemalloc.so # [not osx]
    - gcc -I${PREFIX}/include/ test.c -o test.o
</pre>

I also like this test. It should be included as an example in the documentation.

**Comment by bgruening** [comment]
Thanks @vodkatad @druvus! This looks great!

**Pull request merged**
