### PR TITLE
update riboseed,remove most pins

### PR DESCRIPTION
**Pull request by nickp60**
Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it. Note that if you are not already a member of the bioconda project (meaning that you can't add this label), please ping `@bioconda/core` so that your PR can be reviewed and merged (please note if you'd like to be added to the bioconda project). Please see https://github.com/bioconda/bioconda-recipes/issues/15332 for more details.

* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [X] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [X] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by nickp60** [comment]
Its been a while since I've updated a recipe, and I can't seem to figure out whats going with the build number missing.  Any guidance would be appreciated!

**Comment by epruesse** [comment]
We don't build for Python 3.5 any more - only 2.7, 3.6 and 3.7. Can you check with upstream whether the compatibility with 3.6/3.7 can be fixed?

**Comment by epruesse** [comment]
@nickp60 Can you use the command from above to test the package? I'm not sure the py35 requirement works.

```
conda install -c https://62932-42372094-gh.circle-artifacts.com/0/tmp/artifacts/packages ruboseed
```

And same for env create.

**Comment by nickp60** [comment]
Hi @epruesse , thanks so much for the help.  Unfortunately, I am still stuck with 3.5 because I need to run SPAdes 3.9.* (https://github.com/ablab/spades/issues/186) .  SPAdes 3.10 and on changed how they handled the assembly, and I haven't yet been able to figure out  a workaround.  Would adding SPAdes 3.9.0 as a submodule for for the riboSeed repo make the build process simpler, or would additional layer of complexity not be worth it?

**Comment by nickp60** [comment]
I am testing that install now...

**Comment by nickp60** [comment]
I tried the following, and it has hung there for several hours:
```
conda install -c https://62932-42372094-gh.circle-artifacts.com/0/tmp/artifacts/packages riboseed
Collecting package metadata (current_repodata.json): done
Solving environment: failed
Collecting package metadata (repodata.json): done
Solving environment: -/
```

**Comment by nickp60** [comment]
Update: build SPAdes 3.9.1 for osx and linux, added them in a branch of the riboSeed repo.  The `build.sh` script pull the platform-appropriate one and install it.

**Comment by epruesse** [comment]
Please don't vendor (adding copies of other software to another package/software). There are many many reasons for this. License/copyright issues, dependencies, co-installation/namespace, disk usage, multiplying work for patches/fixes, etc etc etc.

If you need spades 3.9, require it: `run: spades 3.9.*`. If we don't have spades 3.9, you can create a subfolder `recipes/spades/3.9` with the recipe packaging that version.

**Comment by nickp60** [comment]
Hi @epruesse,  I tried adding the 3.9.1 release last year, but got no help with the issue I raised: https://github.com/bioconda/bioconda-recipes/issues/11473.  Any advice would be appreciated!

**Comment by epruesse** [comment]
You self merged that PR... It did not do anything. Had you looked at the logs, you'd have noticed. Sorry about the issue having been missed. We have so many PRs to take care of that there is no-one to check into issues with little activity.

**Comment by dpryan79** [comment]
I'll see if I can get spades 3.9 built.

**Comment by dpryan79** [comment]
I've failed at getting that version of spades to build :(

**Comment by nickp60** [comment]
@dpryan79  Thanks for trying!  It looks like they still have old binaries on their site: http://spades.bioinf.spbau.ru/release3.9.1/ . Is there an issue will using those?

**Comment by dpryan79** [comment]
I think the problem is that they don't actually work in conda, due to differences in libraries. You can try making a new PR using them and we can see if they pass testing.

**Comment by nickp60** [comment]
I will try doing that again -- can you point me to where in the docs it explains how to get previous versions to build?  bioconda-utils doesn't seem to detect that anything has changed when I edit the 3.9.1 `meta.yml` or `build.sh`.

**Comment by dpryan79** [comment]
Just bump the build number

**Comment by nickp60** [comment]
Thanks @dpryan79 , it looks like it should be ready now; I just tagged SPAdes 3.9.1 as ready for review.   Once that has gone through, I will retrigger the build on this latest commit.

**Comment by dpryan79** [comment]
The CI testing can be rerun in an hour or so I hope.

**Comment by nickp60** [comment]
@dpryan79 @epruesse I think its ready for review now!  Thanks again for all your help getting this sorted!

**Comment by dpryan79** [comment]
@bioconda-bot merge

**Comment by dpryan79** [comment]
Thanks @nickp60 !

**Pull request merged**
