### PR TITLE
Update phyluce to 1.7.2

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`phyluce`](https://bioconda.github.io/recipes/phyluce/README.html): **1.6.8** &rarr; **1.7.2**

[install with bioconda](http://bioconda.github.io/recipes/phyluce/README.html) [Conda](https://anaconda.org/bioconda/phyluce/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/phyluce`](https://github.com//bioconda/bioconda-recipes/tree/bump/phyluce/recipes/phyluce) (click to view/edit other files)
Summary | Software for UCE (and general) phylogenomics.
Home | [https://github.com/faircloth-lab/phyluce](https://github.com/faircloth-lab/phyluce)
Releases |[https://github.com/faircloth-lab/phyluce/tags](https://github.com/faircloth-lab/phyluce/tags)
Author | `@faircloth-lab`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by daler** [comment]
@brantfaircloth, looks like phyluce is now [separately providing env yamls](https://github.com/faircloth-lab/phyluce/tree/main/distrib) and possibly [building a package already](https://github.com/faircloth-lab/phyluce/tree/main/conda/phyluce). Does it make sense to keep this in bioconda?

**Comment by brantfaircloth** [comment]
Correct! The only reason to retain would be to maintain backwards compatibility with older versions.

**Comment by dpryan79** [comment]
@bioconda-bot please update

**Comment by daler** [comment]
@brantfaircloth so just to clarify: remove the recipe here, but keep all package tarballs in the channel? The recipe (and all older versions) can always be found in the git history.

**Comment by daler** [comment]
OK, removed in #39682 39682

**Pull request closed without merging**
