### PR TITLE
Update selectsequencesfrommsa to 1.0.4

### PR DESCRIPTION
**Pull request by epruesse**
This PR was created automatically. See bioconda/bioconda-utils#348

### CODE REVIEW

**Comment by epruesse** [comment]
ping @eggzilla - could you have a look at this?

**Comment by epruesse** [comment]
Fails with `stack` dependency error.

**Comment by eggzilla** [comment]
Hi, sorry for the delay, I will look into it!

**Comment by epruesse** [comment]
@eggzilla Thanks!

Feel free to create a new PR or to commit to my branch as you prefer.

**Pull request closed without merging**
