### PR TITLE
[lint skip missing_hash for recipes/blasr] [lint skip uses_git_url for recipes/blasr] Add tools for blasr

### PR DESCRIPTION
**Pull request by bebatut**
* [X] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [X] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

As required in #4224

### CODE REVIEW

**Comment by bgruening** [comment]
You also need to skip: uses_git_url

**Comment by mictadlo** [comment]
@bgruening This package requires `submodules`. How is it possible to build the package without `uses_git_url`?

**Comment by bebatut** [comment]
I think @bgruening was mentioning to add `[lint skip uses_git_url for recipe/blasr]` (similar to `[lint skip missing_hash for recipe/blasr]`) to skip the linting. I will add it

**Comment by bgruening** [comment]
@mictadlo ideally we could convince the upstream author to create a release tarball. Until then we merge this one. Thanks all.

**Comment by lparsons** [comment]
It seems that conda install still prefers the older version `5.3.9c6f0a5-0` to this updated one. Perhaps we need to change the version spec to ensure the newest one is identified as "newer"?

**Comment by lparsons** [comment]
Unfortunately, I still have an issue (https://github.com/bioconda/bioconda-recipes/issues/4004) with this update, however, when I try to run `blasr` (`blasr --help` works):

```
[INFO] 2017-03-29T10:54:08 [blasr] started.
blasr: symbol lookup error: blasr: undefined symbol: _ZN15FileOfFileNames18ExpandFileNameListERSt6vectorISsSaISsEE
```

**Comment by lparsons** [comment]
Hmmm... another obstacle I've run into, it seems that this is not compiled with "bam support" and `--sam` has been deprecated, so I'm unable to get usable output. See https://github.com/PacificBiosciences/blasr/issues/270.

**Comment by mictadlo** [comment]
@lparsons I got the same problem like you with `blasr  5.3.f8bfa9c`
```
[INFO] 2017-04-27T08:52:59 [blasr] started.
blasr: symbol lookup error: blasr: undefined symbol: _ZN15FileOfFileNames18ExpandFileNameListERSt6vectorISsSaISsEE
```
Did you get it fix?

**Comment by mictadlo** [comment]
Maybe this will solve our problem https://github.com/PacificBiosciences/blasr/issues/95#issuecomment-129603860

**Comment by mictadlo** [comment]
[Here](https://github.com/PacificBiosciences/blasr/blob/master/doc/INSTALL_MAKE.md) I found:
```
If you have built and installed blasr_libcpp elsewhere, then drop --sub and do not run make build-submodule.
```

**Comment by fidelram** [comment]
Same problem here!

` undefined symbol: _ZN15FileOfFileNames18ExpandFileNameListERSt6vectorISsSaISsEE`

**Comment by bgruening** [comment]
@bebatut can we change the version number please?

**Comment by mictadlo** [comment]
any update on it?

**Pull request merged**
