### PR TITLE
add r-immunedeconv

### PR DESCRIPTION
**Pull request by grst**
Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it. Note that if you are not already a member of the bioconda project (meaning that you can't add this label), please ping `@bioconda/core` so that your PR can be reviewed and merged (please note if you'd like to be added to the bioconda project). Please see https://github.com/bioconda/bioconda-recipes/issues/15332 for more details.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

Adding [immunedeconv](https://github.com/grst/immunedeconv), a meta-package providing a unified interface to methods for estimating immune cell contents from gene expression samples.

### CODE REVIEW

**Comment by epruesse** [comment]
Ahh. It's the mulled tests - the run_test.sh is a trick to get the tests to not execute in the mulled container.

**Comment by grst** [comment]
Exactly -- I should have stated that somewhere.

The problem is that the test.R file is not available from within the mulled test. 
Or is there a way to do it properly?

**Comment by grst** [comment]
@epruesse, how to move on with this PR?

**Comment by dpryan79** [comment]
This needs a rebuild of r-xcell, which I'll handle in the bulk branch real quick.

**Comment by dpryan79** [comment]
r-xcell will be available in 20-30 minutes

**Comment by dpryan79** [comment]
Needs r-mcpcounter to be bumped.

**Comment by grst** [comment]
Thanks, @dpryan79 for fixing this!

I don't quite understand what has been going on here (the rebuilds...) but it seems to have worked :) 

Best, 
Gregor

**Pull request merged**
