### PR TITLE
Update graftm to 0.13.1

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`graftm`](https://bioconda.github.io/recipes/graftm/README.html): **0.12.2** &rarr; **0.13.1**

[install with bioconda](http://bioconda.github.io/recipes/graftm/README.html) [Conda](https://anaconda.org/bioconda/graftm/files)

Info | Link
-----|-----
Recipe | [`recipes/graftm`](https://github.com//bioconda/bioconda-recipes/tree/bump/graftm/recipes/graftm) (click to view/edit other files)
Releases |[https://pypi.org/pypi/graftm/json](https://pypi.org/pypi/graftm/json)

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by druvus** [comment]
extern needs to be updated and moved to conda-forge.

**Comment by dpryan79** [comment]
Xref: https://github.com/conda-forge/staged-recipes/pull/10280

**Comment by dpryan79** [comment]
A newer extern has been merged in, we just need it to get built and migrated across the CDN.

**Comment by dpryan79** [comment]
@bioconda-bot please update

**Comment by dpryan79** [comment]
Should probably remove `extern` from bioconda in this PR.

**Comment by druvus** [comment]
@dpryan79 I guess this should be reopened?

**Comment by dpryan79** [comment]
The bot just made a new PR. I don't know why the autobump command sometimes closes PRs.

**Pull request closed without merging**
