### PR TITLE
add recipe for SAM_Refiner

### PR DESCRIPTION
**Pull request by degregory**
Attempting to get SAM Refiner into bioconda

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by rpetit3** [comment]
Hi @degregory! Want help getting this into Bioconda?

**Comment by degregory** [comment]
Yes please.

**Comment by rpetit3** [comment]
Is only the SAM_refiner.py needed? Or should we run setup.py?

**Comment by degregory** [comment]
I've used pip to install based on the setup.py.  so I suspect it will be needed.

**Comment by rpetit3** [comment]
When running SAM Refiner, should it be `samrefiner` or `SAM_Refiner`? Please correct me if I'm wrong but looks like the setup.py will make SAM_Refiner (https://github.com/degregory/SAM_Refiner/blob/main/setup.py#L18)

**Review by rpetit3 — APPROVED** [review]

**Comment by rpetit3** [comment]
@degregory if everything looks goo to you I'm happy to merge it.

You can give it a test run with 

```
conda create -n test-samrefiner -c https://165600-42372094-gh.circle-artifacts.com/0/tmp/artifacts/packages -c conda-forge -c bioconda samrefiner
```

**Comment by degregory** [comment]
thank you so much

**Comment by degregory** [comment]
it tests ok for me locally
Thank you again.

**Comment by rpetit3** [comment]
@biocondabot please merge

**Pull request merged**
