### PR TITLE
Fix libgenome version

### PR DESCRIPTION
**Pull request by cjandrasits**
Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it. Note that if you are not already a member of the bioconda project (meaning that you can't add this label), please ping `@bioconda/core` so that your PR can be reviewed and merged (please note if you'd like to be added to the bioconda project). Please see https://github.com/bioconda/bioconda-recipes/issues/15332 for more details.

* [ x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [ x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by cjandrasits** [comment]
Hi,

I only changed the version of the libgenome dependency and I don't know why the recipe won't build now. I essentially did it the same way as in #15662 and this recipe was built, so I do not know what's wrong.
Please help :)

**Comment by jamesabbott** [comment]
Hi,

It looks like the build environment has been updated and is using a newer compiler which is using the C++17 standard by default:

warning: ISO C++1z does not allow 'register' storage class specifier [-Wregister]

Try modifying the compiler options to use an older C++ standard. I'd start with '-std=gnu++98'  to cope with the more old-fashioned code in mauvealigner.

James

**Comment by cjandrasits** [comment]
Thanks James!
I have been trying all kinds of flags for compiling mauveAligner but I could not get it to work...

@bioconda/core I think I need help here, please... 
Judging by the kind of errors I get (see below), I think the dependencies libgenome, libmems and libmuscle have to be rebuilt in the new environment (GCC7 ) so this package can be rebuilt as well. 
However, libmuscle is on the build-failed-blacklist - but I think it should not be, because I was able to build it locally. 
Or is there another way to fix this?
Thank you!

``` 
mauveAligner.cpp:(.text+0x54a): undefined reference to `mems::gnAlignedSequences::getSupportedFormats[abi:cxx11]()'
mauveAligner.o: In function `doAlignment(int, char**)':
mauveAligner.cpp:(.text+0x10d5): undefined reference to `mems::MuscleInterface::SetExtraMuscleArguments(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
mauveAligner.cpp:(.text+0x1167): undefined reference to `mems::FileSML::registerTempPath(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
```

**Comment by dpryan79** [comment]
@cjandrasits Go ahead and try to get libgenome rebuilt if you think that will help.

**Comment by daler** [comment]
Closing due to inactivity, please re-open if needed.

**Pull request closed without merging**
