### PR TITLE
Initial build for msprime and dependencies

### PR DESCRIPTION
**Pull request by jeromekelleher**
This includes:

GSL (C library)
pyparsing (Python)
svgwrite (Python)

This is my first conda package, so comments are very much welcome!

### CODE REVIEW

**Comment by johanneskoester** [comment]
I think we don't need a gsl recipe. There are already a couple of packages around that depend on gsl and they already work. There seems to be a gsl package in anaconda although it cannot be found via anaconda.org. Apart from that, can you add tests for all other recipes? For python recipes, import tests are sufficient. For command line apps, just test if ``mycommand --help`` works.

**Comment by jeromekelleher** [comment]
Great, thanks @johanneskoester! I'll make these changes and push a cleaned up version here ASAP.

**Comment by jeromekelleher** [comment]
OK, I've updated this @johanneskoester. There is a gsl package in the r channel, so installing, say, gfold (which depends on gsl) with 
```
conda install gfold --channel bioconda --channel r
```
works.

**Comment by johanneskoester** [comment]
You can also add both channels [permanently](http://bioconda.github.io/#step-3-install-packages-or-create-environments). Then you don't have to specify them upon installation.

**Comment by johanneskoester** [comment]
Now everything is fine, thanks!

**Comment by jeromekelleher** [comment]
Excellent, thanks @johanneskoester! What's the protocol for merging PRs around here? I.e., do I merge my own PRs, or are they reviewed by the team and someone else merges?

**Comment by johanneskoester** [comment]
We are right now thinking about a formalized procedure for the future. For now, you can just merge yourself. Whenever you have doubts, just ask and somebody will answer.

**Comment by jeromekelleher** [comment]
This sounds very sensible; thanks.

**Pull request merged**
