### PR TITLE
Remove OpenMPI recipe

### PR DESCRIPTION
**Pull request by bebatut**
* [X] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [X] This PR does something else (explain below).

This PR removes a recipe for OpenMPI as discussed in #3947, to use the one in `conda-forge`

### CODE REVIEW

**Comment by bgruening** [comment]
@johanneskoester is this an intended behavior? If so can we force-merge such PR?

**Comment by johanneskoester** [comment]
Not really. So, it correctly detects a change with openmpi. Then it tries to build it, but since the recipe is not there, it fails. Hence, it exists with status 1.
I guess it would be correct to check whether a change detected with git-range is a deletion. In that case, one should exit with 0. I could fix that now, but given the refactorings of @daler, it would cause conflicts. @daler do you want to build that into your PR (a quick `os.path.exists` on the results of `modified_recipes` should be enough)? Otherwise, I'd like to wait until you have merged it.

**Comment by daler** [comment]
Sure -- I'll add that in while addressing your other comments on that PR.

**Comment by johanneskoester** [comment]
Thanks, @daler!!

**Comment by bgruening** [comment]
Everything is normal, nothing to see here ... ;)
Sorry, I will force merge this as I was told this is blocking some packages.

**Pull request merged**
