### PR TITLE
update SPAdes to v3.15.0

### PR DESCRIPTION
**Pull request by alienzj**
Describe your pull request here

update SPAdes to v3.15.0

```
SPAdes 3.15.0

@asl asl released this 8 days ago

NEW: CoronaSPAdes pipeline for assembly of full-length coronaviridae genomes from the transcriptomic and metatranscriptomic data.
NEW: Meta-Viral and RNA-Viral pipelines for identifying viral genomes for metagenomic and metatranscriptomic data.
NEW: Novel algorithm for trusted contig usage.
NEW: Switched to mimalloc memory allocator.
NEW: PlasmidSPAdes and bgcSPAdes now support assembly graph as an input.
CHANGE: Significant improvements and fixes for metaplasmid pipeline.
CHANGE: Multiple performance improvements in simplification and repeat resolving procedures.
DEPRECATED: Support for Lucigen NxSeqВ® Long Mate Pair reads.
DEPRECATED: truSPAdes pipeline for TruSeq barcode assembly (still present in this release but no longer supported).
```

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by alienzj** [comment]
I have meet some problem, which was describled in here:
https://github.com/microsoft/mimalloc/issues/276

**Comment by alienzj** [comment]
Compile log from CI build:
```
04:56:55 BIOCONDA INFO (OUT) In file included from /opt/conda/conda-bld/spades_1611291094806/work/ext/src/mimalloc/src/alloc.c:15:0,
04:56:55 BIOCONDA INFO (OUT)                  from /opt/conda/conda-bld/spades_1611291094806/work/ext/src/mimalloc/src/static.c:32:
04:56:55 BIOCONDA INFO (OUT) /opt/conda/conda-bld/spades_1611291094806/work/ext/src/mimalloc/src/alloc-override.c: In function 'void* aligned_alloc(size_t, size_t)':
04:56:55 BIOCONDA INFO (OUT) /opt/conda/conda-bld/spades_1611291094806/work/ext/src/mimalloc/src/alloc-override.c:188:7: error: redefinition of 'void* aligned_alloc(size_t, size_t)'
04:56:55 BIOCONDA INFO (OUT)  void* aligned_alloc(size_t alignment, size_t size)   { return mi_aligned_alloc(alignment, size); }
04:56:55 BIOCONDA INFO (OUT)        ^~~~~~~~~~~~~
04:56:55 BIOCONDA INFO (OUT) In file included from /opt/conda/conda-bld/spades_1611291094806/_build_env/x86_64-conda-linux-gnu/include/c++/7.5.0/cstdlib:75:0,
04:56:55 BIOCONDA INFO (OUT)                  from /opt/conda/conda-bld/spades_1611291094806/_build_env/x86_64-conda-linux-gnu/include/c++/7.5.0/ext/string_conversions.h:41,
04:56:55 BIOCONDA INFO (OUT)                  from /opt/conda/conda-bld/spades_1611291094806/_build_env/x86_64-conda-linux-gnu/include/c++/7.5.0/bits/basic_string.h:6361,
04:56:55 BIOCONDA INFO (OUT)                  from /opt/conda/conda-bld/spades_1611291094806/_build_env/x86_64-conda-linux-gnu/include/c++/7.5.0/string:52,
04:56:55 BIOCONDA INFO (OUT)                  from /opt/conda/conda-bld/spades_1611291094806/_build_env/x86_64-conda-linux-gnu/include/c++/7.5.0/stdexcept:39,
04:56:55 BIOCONDA INFO (OUT)                  from /opt/conda/conda-bld/spades_1611291094806/_build_env/x86_64-conda-linux-gnu/include/c++/7.5.0/array:39,
04:56:55 BIOCONDA INFO (OUT)                  from /opt/conda/conda-bld/spades_1611291094806/_build_env/x86_64-conda-linux-gnu/include/c++/7.5.0/tuple:39,
04:56:55 BIOCONDA INFO (OUT)                  from /opt/conda/conda-bld/spades_1611291094806/_build_env/x86_64-conda-linux-gnu/include/c++/7.5.0/bits/unique_ptr.h:37,
04:56:55 BIOCONDA INFO (OUT)                  from /opt/conda/conda-bld/spades_1611291094806/_build_env/x86_64-conda-linux-gnu/include/c++/7.5.0/memory:80,
04:56:55 BIOCONDA INFO (OUT)                  from /opt/conda/conda-bld/spades_1611291094806/_build_env/x86_64-conda-linux-gnu/include/c++/7.5.0/thread:39,
04:56:55 BIOCONDA INFO (OUT)                  from /opt/conda/conda-bld/spades_1611291094806/work/ext/src/mimalloc/include/mimalloc-atomic.h:274,
04:56:55 BIOCONDA INFO (OUT)                  from /opt/conda/conda-bld/spades_1611291094806/work/ext/src/mimalloc/include/mimalloc-types.h:13,
04:56:55 BIOCONDA INFO (OUT)                  from /opt/conda/conda-bld/spades_1611291094806/work/ext/src/mimalloc/include/mimalloc-internal.h:11,
04:56:55 BIOCONDA INFO (OUT)                  from /opt/conda/conda-bld/spades_1611291094806/work/ext/src/mimalloc/src/static.c:17:
04:56:55 BIOCONDA INFO (OUT) /opt/conda/conda-bld/spades_1611291094806/_build_env/x86_64-conda-linux-gnu/sysroot/usr/include/stdlib.h:513:21: note: 'void* aligned_alloc(size_t, size_t)' previously defined here
04:56:55 BIOCONDA INFO (OUT)  static inline void* aligned_alloc (size_t al, size_t sz)
04:56:55 BIOCONDA INFO (OUT)                      ^~~~~~~~~~~~~
```

**Comment by alienzj** [comment]
https://github.com/ablab/spades/issues/648

**Comment by asl** [comment]
Looks like conda is using 11-year old glibc that implements some C11 features (including `aligned_alloc`) in a standard non-compliant way. One (and proper way) to resolve this issue is to upgrade the glibc.

**Comment by andersgs** [comment]
@bgruening or @dpryan79 essentially, this is running into a gcc-7 bug that causes an incompatibility with `mimmalloc` (https://github.com/microsoft/mimalloc/issues/219) and previously discussed in conda-forge (https://github.com/conda/conda-build/issues/3165), although the proposed fix would not work in this instance, I don't think.

I have tried adding a `conda_build_config.yaml` with the following:
```
cxx_compiler_version:          # [unix]
  - 9                          # [unix]
  ```
  
  But, I am running into dependency conflicts. 
  
  Any good suggestions on moving forward

**Comment by asl** [comment]
@andersgs gcc is completely unrelated here, the problem is in glibc, not in gcc.

**Comment by andersgs** [comment]
@asl I know. i was hoping forcing the updated compiler would also force an update to glibc.

but, conda depends on the system glibc and doesn't shit one of its own. currently, it looks like it is using version 2.12 of glibc --- the case image for linux testing is CentOS 6 still, which is probably why it is failing. but, the point is to ensure maximum compatibility.

i will look at trying a patch that will allow it to compile on an older version of glibc, but would skip if a newer version of glibc were available. 

do you know the minimum version of glibc that would work?

**Comment by asl** [comment]
> but, conda depends on the system glibc

No, it is not. conda uses sysroot with its own glibc (check x86_64-conda-linux-gnu/sysroot/usr/include/stdlib.h for example)

But I must admit, I was wrong.`aligned_alloc` was added only in glibc 2.16 and added correctly, so glibc itself is not guilty. conda uses glibc 2.11. And it seems to be conda's own incompatible patch to glibc (at least because the code uses C++ style comments which glibc will certainly not tolerate ;) ). Which certainly needs to be fixed at conda side.

**Comment by asl** [comment]
The bogus conda-specific patch to glibc is:
```
#ifdef __USE_XOPEN2K
/* Allocate memory of SIZE bytes with an alignment of ALIGNMENT.  */
extern int posix_memalign (void **__memptr, size_t __alignment, size_t __size)
     __THROW __nonnull ((1)) __wur;
#if defined __cplusplus
extern "C" { static inline void* aligned_alloc (size_t al, size_t sz); }
#endif
static inline void* aligned_alloc (size_t al, size_t sz)
{
  void *ptr = NULL;
  // The value of alignment shall be a power of two multiple of sizeof(void *).
  if (al < sizeof(void*))
    al = sizeof(void*);
  int ret = posix_memalign (&ptr, al, sz);
  if (ret == 0)
    return ptr;
  return NULL;
}
#endif
```

glibc will never add `aligned_alloc` this way, trust me. It's so broken in many ways :)

**Comment by asl** [comment]
So, I tried to dig further. The header in question is distributed in broken `sysroot_linux-64`. In particular, `sysroot_linux-64-2.12-h77966d4_13.tar.bz2` is broken and `sysroot_linux-64-2.17-h77966d4_10.tar.bz2` is not. For the record, here is proper declaration for `aligned_alloc` from 2.17 package:
```
#ifdef __USE_ISOC11
/* ISO C variant of aligned allocation.  */
extern void *aligned_alloc (size_t __alignment, size_t __size)
     __THROW __wur __attribute__ ((__malloc__, __alloc_size__ (2)));
#endif
```

Hope this helps

**Comment by andersgs** [comment]
> > but, conda depends on the system glibc
> 
> No, it is not. conda uses sysroot with its own glibc (check x86_64-conda-linux-gnu/sysroot/usr/include/stdlib.h for example)
> 
> But I must admit, I was wrong.`aligned_alloc` was added only in glibc 2.16 and added correctly, so glibc itself is not guilty. conda uses glibc 2.11. And it seems to be conda's own incompatible patch to glibc (at least because the code uses C++ style comments which glibc will certainly not tolerate ;) ). Which certainly needs to be fixed at conda side.

You are right. That has changed!! Thank you.

**Comment by andersgs** [comment]
> So, I tried to dig further. The header in question is distributed in broken `sysroot_linux-64` package. In particular, `sysroot_linux-64-2.12-h77966d4_13.tar.bz2` is broken and `sysroot_linux-64-2.17-h77966d4_10.tar.bz2` is not. For the record, here is proper declaration for `aligned_alloc` from 2.17 package:
> 
> ```
> #ifdef __USE_ISOC11
> /* ISO C variant of aligned allocation.  */
> extern void *aligned_alloc (size_t __alignment, size_t __size)
>      __THROW __wur __attribute__ ((__malloc__, __alloc_size__ (2)));
> #endif
> ```
> 
> Hope this helps

@asl this helps a lot. i now manage to get a complete compilation.

I am getting this error now:
```
19:06:15 BIOCONDA INFO (ERR) spades_compile.sh: line 232: /opt/conda/conda-bld/spades_1612465117741/work/build_spades/bin/include_test:
```

I am looking at `spades_compile.sh` and trying to understand what `BUILD_INTERNAL` might mean. Can you expand?

**Comment by asl** [comment]
This enabled compilation of our internal projects within codebase. Not for end-user consumption. They are disabled in spades_compile.sh unless you passed `-a` option :)

**Comment by andersgs** [comment]
Thank you @asl. Yes, I see that the build.sh script calls spades_compile.sh with the `-alrj8` --- I have changed that to remove the `a` now. Now I wait for the 20-30 minutes for it to run...

**Comment by andersgs** [comment]
PR##26595 closes this one.

**Pull request closed without merging**
