### PR TITLE
Update fgpyo to 0.2.0

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`fgpyo`](https://bioconda.github.io/recipes/fgpyo/README.html): **0.1.3** &rarr; **0.2.0**

[install with bioconda](http://bioconda.github.io/recipes/fgpyo/README.html) [Conda](https://anaconda.org/bioconda/fgpyo/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/fgpyo`](https://github.com//bioconda/bioconda-recipes/tree/bump/fgpyo/recipes/fgpyo) (click to view/edit other files)
Summary | Python bioinformatics and genomics library
Home | [https://pypi.org/project/fgpyo/](https://pypi.org/project/fgpyo/)
Releases |[https://github.com/fulcrumgenomics/fgpyo/tags](https://github.com/fulcrumgenomics/fgpyo/tags)
Recipe Maintainer(s) | @tfenne, @nh13, @NatPRoach
Author | `@fulcrumgenomics`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Review by jdidion — COMMENTED** [review]
In this version the python dependency is updated to `>=3.8`. We also drop the `typing_inspect` dependency and update pysam to `0.22.0`.

**Comment by bgruening** [comment]
Please feel free to change this here or add comments in suggestion mode.

**Comment by jdidion** [comment]
@bgruening thanks...it appears I do not have permission to push to this branch. How do I get permissions? Sorry, this is my first time having to modify a BioConda recipe.

**Comment by jdidion** [comment]
@bgruening @nh13 was able to make the change...ready to merge!

**Pull request merged**
