### PR TITLE
xpressplot

### PR DESCRIPTION
**Pull request by j-berg**
@bioconda/core

* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [X] This PR adds a new recipe.
* [X] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by j-berg** [comment]
I am having trouble decipher this error message from Circle CI. When I build xpressplot on my personal machine, there are no errors when importing any library.

```
18:01:39 BIOCONDA ERROR COMMAND FAILED: mulled-build build-and-test xpressplot=0.0.5b0--py_0 -n biocontainers --test curl -L https://sourceforge.net/projects/xpressplot/files/GPL570.txt/download -o tests/GPL570.txt && python tests/analyze_test.py && python tests/fetch_test.py && python tests/format_test.py && python tests/normalize_test.py && python tests/utils_test.py && python -c "import numpy" && python -c "import os" && python -c "import pandas" && python -c "import sys" && python -c "import xpressplot" --channels conda-forge,file:///home/circleci/project/miniconda/conda-bld,bioconda,defaults --involucro-path /home/circleci/project/miniconda/bin/involucro

18:01:39 BIOCONDA ERROR TEST FAILED: recipes/xpressplot
18:01:40 BIOCONDA ERROR BUILD SUMMARY: of 1 recipes, 1 failed and 0 were skipped. Details of recipes and environments follow.
18:01:40 BIOCONDA ERROR BUILD SUMMARY: FAILED recipe recipes/xpressplot
Exited with code 1
```


Full Circle build can be found here: https://circleci.com/gh/bioconda/bioconda-recipes/61415
The Lint build seems to be just fine though. This appears to just be a Linux build issue: https://circleci.com/gh/bioconda/bioconda-recipes/61407 for the successful Lint build.

**Comment by j-berg** [comment]
Hi @bioconda, any help on this would be appreciated. I'm not sure why the tests are working on the lint build but not on the Linux build

**Comment by dpryan79** [comment]
Ah, `test: requires` isn't respected in the mulled test.

**Comment by dpryan79** [comment]
@bioconda-bot merge

**Pull request merged**
