### PR TITLE
Maintain pysam 0.15.2 for medaka

### PR DESCRIPTION
**Pull request by dpryan79**
Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

 * `@BiocondaBot please update` will cause the BiocondaBot to merge the master branch into a PR
 * `@BiocondaBot please add label` will add the `please review & merge` label.
 * `@BiocondaBot please fetch artifacts` will post links to packages and docker containers built by the CI system. You can use this to test packages locally before merging.

For members of the Bioconda project, the following command is also available:

 * `@BiocondaBot please merge` will cause packages/containers to be uploaded and a PR merged. Someone must approve a PR first! This has the benefit of not wasting CI build time required by manually merging PRs.

If you have questions, please post them in gitter or ping `@bioconda/core` in a comment (if you are not able to directly ping `@bioconda/core` then the bot will repost your comment and enable pinging).

### CODE REVIEW

**Comment by dpryan79** [comment]
Xref: https://github.com/bioconda/bioconda-recipes/pull/19247

**Comment by dpryan79** [comment]
@bioconda-bot please fetch artifacts

**Comment by dpryan79** [comment]
@bioconda-bot please fetch artifacts

**Comment by dpryan79** [comment]
@bioconda-bot please add label

**Comment by dpryan79** [comment]
@bioconda-bot please fetch artifacts

**Comment by dpryan79** [comment]
@bioconda-bot please add label

**Comment by cjw85** [comment]
@dpryan79 We just patched medaka so it can use pysam 0.15.3 again. There was a API change which broke things. More background here:
https://github.com/nanoporetech/medaka/blob/master/medaka/medaka.py#L73

Still, having a pysam 0.15.2 in bioconda is a good idea to maintain a parity with pypi, where three is an ongoing lack of wheels.

**Comment by dpryan79** [comment]
OK, can you approve this PR anyway then?

**Comment by cjw85** [comment]
I tried the:

    conda install -c https://86867-42372094-gh.circle-artifacts.com/0/tmp/artifacts/packages pysam

from above in an otherwise empty environment and got:

```Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:



Package htslib conflicts for:
pysam -> htslib[version='>=1.9,<1.10.0a0']
Package python conflicts for:
pysam -> python[version='>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']
Package zlib conflicts for:
pysam -> zlib[version='>=1.2.11,<1.3.0a0']
Package libgcc-ng conflicts for:
pysam -> libgcc-ng[version='>=7.3.0']
Package samtools conflicts for:
pysam -> samtools=1.9
Package curl conflicts for:
pysam -> curl[version='>=7.64.1,<8.0a0']
Package bcftools conflicts for:
pysam -> bcftools=1.9
Package libdeflate conflicts for:
pysam -> libdeflate[version='>=1.3,<1.4.0a0']
```

I presume this isn't expected.

**Comment by dpryan79** [comment]
I can't reproduce that, perhaps your channel order is wrong.

**Comment by cjw85** [comment]
Ah, yes, I don't have any channels set up so needed `-c bioconda` after the artefacts URL.

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Pull request merged**
