### PR TITLE
Bump bioconductor-topgo build number

### PR DESCRIPTION
**Pull request by abretaud**
* [x] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

Bump the topgo build number as the 2.24.0 was not correctly pushed to bioconda channel

### CODE REVIEW

**Comment by lecorguille** [comment]
It is [blacklisted](https://github.com/bioconda/bioconda-recipes/blob/master/sorted-r-blacklist#L326)
See https://github.com/bioconda/bioconda-recipes/issues/2404

So until, you remove it from the list, it will not be builded

**Comment by abretaud** [comment]
Thanks! I hadn't seen it (and it explains why the 2.24.0 version was not built before)

**Comment by daler** [comment]
@lecorguille @abretaud dependencies need to be built for R3.3.1, too. `sorted-r-blacklist` is topologically sorted, so in general things at the top need to be built before things at the bottom. If you hit dependency issues, move up the list.

It looks like we're hitting that critical part in the DAG where s4vectors is built, so I think you'll be OK for this PR.

**Comment by abretaud** [comment]
Ok, we'll see if it goes green
Any idea why the travis job is still waiting? I tried cancelling/restarting it, but still waiting (and I'm still impatient :smile: )

**Comment by bgruening** [comment]
Only a few jobs can run at a time and currently Travis seems to be busy. Osx builds are taking very long at the moment. :-(

**Comment by daler** [comment]
https://www.traviscistatus.com/ says they're still working through the OSX backlog.  Recently it's been taking hours for jobs to start :/

**Pull request merged**
