### PR TITLE
Update rgi to 6.0.1

### PR DESCRIPTION
**Pull request by raphenya**
Updates RGI to version 6.0.1

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by apetkau** [comment]
Thanks @raphenya 

The error in the tests I am seeing is [version_constraints_missing_whitespace](https://bioconda.github.io/contributor/linting.html#version-constraints-missing-whitespace), which means that these packages:

https://github.com/bioconda/bioconda-recipes/blob/a06ef583fdcef9958e20301bade2138c3c0d5373/recipes/rgi/meta.yaml#L45-L48

Just need spaces between the package name and the `==` sign (same for the `run` section).

**Comment by raphenya** [comment]
@apetkau @rpetit3 Thanks, gents. Note to self dig through raw logs if builds fail.

**Comment by apetkau** [comment]
@BiocondaBot please merge

**Comment by apetkau** [comment]
@BiocondaBot please fetch artifacts

**Comment by apetkau** [comment]
@BiocondaBot please merge

**Comment by apetkau** [comment]
According to the error log, the build number now does need to be updated:

```
ERROR: recipes/rgi/meta.yaml:19: build_number_needs_bump: The recipe build number should be incremented
```

Now sure why I was getting the `I will attempt to upload artifacts and merge this PR. This may take some time, please have patience.` messages before.

**Comment by rpetit3** [comment]
Well, this is interesting. Looks like one of the "please merge" commands succeeded: https://anaconda.org/bioconda/rgi/files

v6.0.1 is currently available. @raphenya would mind testing to make sure its how it should be? I think if it is we can manually squash and merge.

@dpryan79 Do you think this is related to the bot acting up earlier?

**Comment by apetkau** [comment]
@rpetit3 huh, strange. Let me know if I should undo the build number update? Or maybe just merge this current build in as-is?

**Comment by dpryan79** [comment]
@rpetit3 Yes, looks like the bot was acting up. We can just merge.

**Comment by raphenya** [comment]
hehe, You can't trust these bots. Thanks, gents!

**Pull request merged**
