### PR TITLE
Update anvi'o meta package to 6.2

### PR DESCRIPTION
**Pull request by meren**
This is an update to the anvi'o meta package (anvi'o minimal recipe for 6.2 has been recently pushed, and is already merged and the package is available through bioconda).

### CODE REVIEW

**Comment by meren** [comment]
@BiocondaBot please fetch artifacts

**Comment by meren** [comment]
@BiocondaBot please fetch artifacts

**Comment by druvus** [comment]
@BiocondaBot please fetch artifacts

**Comment by druvus** [comment]
@BiocondaBot please merge

**Comment by meren** [comment]
Thank you very much, @druvus!

**Comment by meren** [comment]
Hi @druvus,

It turns out this package installs `anvio-minimal==6.2=py_0`  (from PR #21241) even though there is a newer one, `anvio-minimal==6.2=py_1` (from PR #21281).

This hacky solution fixes the issue,

```
conda remove --force anvio-minimal
conda install -y -c bioconda -c conda-forge anvio-minimal==6.2=py_1
```

And leaves conda upset, obviously:

```
The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistency:

  - bioconda/noarch::anvio==6.2=0
```

Is the best way to solve this is to send another PR for `anvio`?

If yes, should it look like this:

``` diff
diff --git a/recipes/anvio/meta.yaml b/recipes/anvio/meta.yaml
index f5f458cff..5990b003d 100644
--- a/recipes/anvio/meta.yaml
+++ b/recipes/anvio/meta.yaml
@@ -10,7 +10,7 @@ build:

 requirements:
   run:
-    - anvio-minimal =={{ version }}
+    - anvio-minimal =={{ version }}=py_1
     - prodigal
     - mcl
     - muscle
```

I'm also CC'ing @dpryan79 just in case.

Apologies for the inconvenience and thank you for your input.

**Pull request merged**
