### PR TITLE
 updated tbl2adn to version newer (and working) version

### PR DESCRIPTION
**Pull request by maarten-k**
* [x] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by maarten-k** [comment]
There went something wrong server sided while building for MacOS. What is the bioconda way to trigger another build?


`
CondaHTTPError: HTTP 502 BAD GATEWAY for url <https://conda.anaconda.org/bioconda/osx-64/repodata.json>

Elapsed: 00:30.281068

An remote server error occurred when trying to retrieve this URL.

A 500-type error (e.g. 500, 501, 502, 503, etc.) indicates the server failed to

fulfill a valid request.  The problem may be spurious, and will resolve itself if you

try your request again.  If the problem persists, consider notifying the maintainer

of the remote server.

Traceback (most recent call last):

  File "/Users/travis/build/bioconda/bioconda-recipes/scripts/../simulate-travis.py", line 112, in <module>

    ], check=True)

  File "/anaconda/lib/python3.6/subprocess.py", line 418, in run

    output=stdout, stderr=stderr)

subprocess.CalledProcessError: Command '['conda', 'install', '-y', '--file', 'https://raw.githubusercontent.com/bioconda/bioconda-utils/master/bioconda_utils/bioconda_utils-requirements.txt']' returned non-zero exit status 1.
`

`
CondaHTTPError: HTTP 502 BAD GATEWAY for url <https://conda.anaconda.org/bioconda/osx-64/repodata.json>

Elapsed: 00:30.281068

An remote server error occurred when trying to retrieve this URL.

A 500-type error (e.g. 500, 501, 502, 503, etc.) indicates the server failed to

fulfill a valid request.  The problem may be spurious, and will resolve itself if you

try your request again.  If the problem persists, consider notifying the maintainer

of the remote server.

Traceback (most recent call last):

  File "/Users/travis/build/bioconda/bioconda-recipes/scripts/../simulate-travis.py", line 112, in <module>

    ], check=True)

  File "/anaconda/lib/python3.6/subprocess.py", line 418, in run

    output=stdout, stderr=stderr)

subprocess.CalledProcessError: Command '['conda', 'install', '-y', '--file', 'https://raw.githubusercontent.com/bioconda/bioconda-utils/master/bioconda_utils/bioconda_utils-requirements.txt']' returned non-zero exit status 1.
`

**Comment by druvus** [comment]
@maarten-k I restarted the osx travis test so I hope it will work now.

**Comment by maarten-k** [comment]
Thanks @druvus , looks like that solved the problem

**Comment by bgruening** [comment]
Thanks all. Such hangs can open once in a while.

**Comment by tomkinsc** [comment]
Thanks! We just hit the same issue with the prior version. In case anyone is curious, the relevant sections of the [source code](https://www.ncbi.nlm.nih.gov/IEB/ToolBox/C_DOC/lxr/source/demo/tbl2asn.c#L9674) are amusing:
```
if (MoreThanYearOld()) {
    too_old = TRUE;
    Message (MSG_POST, "This copy of tbl2asn is more than a year old.  Please download the current version.");
}
if (too_old) {
    return 1;
}
```

**Comment by maarten-k** [comment]
So much for reproducibility...   :rage:

**Comment by bgruening** [comment]
We could patch this out ;)

**Pull request merged**
