### PR TITLE
Update perl-cpan-meta to 2.150010

### PR DESCRIPTION
**Pull request by corburn**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by corburn** [comment]
Thanks @jerowe for fixing the perl dependency.

**Comment by jerowe** [comment]
Hmm I thought that would fix the linting error.

**Comment by jerowe** [comment]
```
The following recipes failed linting. See https://bioconda.github.io/linting.html for details:

                           failed_tests
recipe                                 
recipes/perl-cpan-meta  [missing_tests]

Exited with code 1
```

It wants tests.

You could do a 
```
test:
   imports:
     Cpan::Meta
```

**Comment by jerowe** [comment]
I was actually getting this error on my local builds earlier this week, but then when I pushed them to bioconda it was working.

**Pull request closed without merging**
