### PR TITLE
Restores vsearch builds on OSX

### PR DESCRIPTION
**Pull request by colinbrislawn**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [x] This PR does something else (explain below).

Work in Progress!
Restores vsearch builds on OSX. Related to #9404

### CODE REVIEW

**Comment by dpryan79** [comment]
You can try setting `CFLAGS` to `-lm` and see if that helps.

**Comment by epruesse** [comment]
@torognes Can you provide any help here?

This looks almost like some kind of STL linking issue. Have you seen this before?

This came up in #12918 again as well.

**Comment by colinbrislawn** [comment]
Any updates? Who is getting builds working on OSX?

**Comment by torognes** [comment]
Sorry for the late reply.

It appears that the problem is related to linking to the C++ standard library. On macOS, VSEARCH is currently usually built using the older and depreciated `libstdc++` library and not the newer and recommended `libc++` library from Apple.

I have looked at the test build report on macOS and compared it to building it on my local mac (macOS Mojave 10.14.3). The test build is made using Xcode version 8.3.3 while I use the newer Xcode version 10.1.  The test build is using the compiler/linker command `clang++` instead of `c++`, but it seems like `c++` is just a softlink to `clang++` anyway, so it probably doesn't matter.

I get the same error messages as in the test build if I add the option `-stdlib=libc++` to the linker command line. It works well if I rather specify `-stdlib=libstdc++` on the command line (or nothing). (Except for the usual warning `clang: warning: libstdc++ is deprecated; move to libc++ [-Wdeprecated]`)

The default C++ standard library for clang++ may have changed at some point from `libstdc++` to `libc++`, probably from macOS 10.9.

The `configure.ac` file of VSEARCH specifies `MACOSX_DEPLOYMENT_TARGET="10.7"` that should indicate the use of the older C++ standard library, but perhaps this is not taken into account for some reason.

If possible, building with the `-stdlib=libstdc++` option to the linker could potentially solve the problem. I could alternatively add this option to the upstream vsearch Makefile.

The best solution may be to change MACOSX_DEPLOYMENT_TARGET to 10.9 (OSX Mavericks from October 2013) in VSEARCH, which may be about time, as extremely few users should be using something older.

See also issue #1314.

**Comment by dpryan79** [comment]
Xref #13931

**Comment by torognes** [comment]
It seems like the change to `MACOSX_DEPLOYMENT_TARGET="10.9"` did the trick. I'll make that change in the next VSEARCH version, coming soon.

**Comment by dpryan79** [comment]
This has since been done in another PR, so I'll close this.

**Pull request closed without merging**
