### PR TITLE
Update MALT to v0.5.0

### PR DESCRIPTION
**Pull request by jfy133**
Updates MALT v0.5.0. This includes a new update that uses a different type of database.

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by jfy133** [comment]
Appears to be due to a missing javafx library? Unfortunately I'm not familiar enough with Java to resolve :\.

```
18:18:16 BIOCONDA INFO (OUT) java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
18:18:16 BIOCONDA INFO (OUT) 	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:280)
18:18:16 BIOCONDA INFO (OUT) 	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:244)
18:18:16 BIOCONDA INFO (OUT) 	at javafx.graphics/com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:260)
18:18:16 BIOCONDA INFO (OUT) 	at javafx.graphics/javafx.scene.text.Font.font(Font.java:173)
18:18:16 BIOCONDA INFO (OUT) 	at javafx.graphics/javafx.scene.text.Font.font(Font.java:224)
18:18:16 BIOCONDA INFO (OUT) 	at jloda/jloda.util.ProgramProperties.<clinit>(ProgramProperties.java:88)
18:18:16 BIOCONDA INFO (OUT) 	at malt/malt.MaltRun.main(MaltRun.java:73)
18:18:16 BIOCONDA INFO (OUT) 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
18:18:16 BIOCONDA INFO (OUT) 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
18:18:16 BIOCONDA INFO (OUT) 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
18:18:16 BIOCONDA INFO (OUT) 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
18:18:16 BIOCONDA INFO (OUT) 	at com.install4j.runtime/com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:84)
18:18:16 BIOCONDA INFO (OUT) 	at com.install4j.runtime/com.install4j.runtime.launcher.UnixLauncher.start(UnixLauncher.java:66)
18:18:16 BIOCONDA INFO (OUT) 	at install4j.malt.MaltRun.main(Unknown Source)
18:18:16 BIOCONDA INFO (OUT) Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
18:18:16 BIOCONDA INFO (OUT) 	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:94)
18:18:16 BIOCONDA INFO (OUT) 	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
18:18:16 BIOCONDA INFO (OUT) 	at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by jfy133** [comment]
@BiocondaBot please add label

**Comment by jfy133** [comment]
@bioconda/core is there any issue with this PR which is why it hasn't been reviewed yet?

**Review by apeltzer — APPROVED** [review]
LGTM

**Comment by apeltzer** [comment]
@BiocondaBot please merge

**Pull request merged**
