### PR TITLE
Update mokapot to 0.8.0

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`mokapot`](https://bioconda.github.io/recipes/mokapot/README.html): **0.7.4** &rarr; **0.8.0**

[install with bioconda](http://bioconda.github.io/recipes/mokapot/README.html) [Conda](https://anaconda.org/bioconda/mokapot/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/mokapot`](https://github.com//bioconda/bioconda-recipes/tree/bump/mokapot/recipes/mokapot) (click to view/edit other files)
Summary | Fast and flexible semi-supervised learning for peptide detection
Home | [https://github.com/wfondrie/mokapot](https://github.com/wfondrie/mokapot)
Releases |[https://pypi.org/pypi/mokapot/json](https://pypi.org/pypi/mokapot/json)
Recipe Maintainer(s) | @wfondrie

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by wfondrie** [comment]
I need to update the dependencies in `meta.yaml`. Please merge PR #33658 into here before merging into master.

**Comment by marcelm** [comment]
If you become a member of the Bioconda organization, you can just edit the bot-generated PRs (and even approve and merge them yourself). If you are interested, @-mention dpryan79 and he will send you an invite.

**Comment by marcelm** [comment]
I have copied over the modification you did in #33658 (was easier than merging)

**Comment by marcelm** [comment]
Sorry, merging would have been easier (didn’t see you had bump/mokapot as the base branch). But now it’s done.

**Comment by wfondrie** [comment]
Thanks @marcelm. This one should pass once Triqler 0.6.2 from the recently merged PR #33515 is available.

@dpryan79 - can I become a Bioconda member? Thanks 🙏

**Pull request closed without merging**
