### PR TITLE
Beagle 4 0

### PR DESCRIPTION
**Pull request by dlaehnemann**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by dlaehnemann** [comment]
@core
Is there a way to remove the packages with the messed up version number I created earlier (<https://anaconda.org/bioconda/beagle/beagle_4.0_06Jun17/download/osx-64/beagle-beagle_4.0_06Jun17-0.tar.bz2> and <https://anaconda.org/bioconda/beagle/beagle_4.0_06Jun17/download/linux-64/beagle-beagle_4.0_06Jun17-0.tar.bz2>)? I guess once I merge this, a new version will be created and put alongside these old ones, but really it shouldn't be a separate version. I guess the version number is a bad place to mess up, sorry.

**Comment by bgruening** [comment]
I can remove them, if you give me a clean list, the one above is not really readable.

**Comment by dlaehnemann** [comment]
@bgruening Is this more readable? It's the osx-64 and the linux-64 file:

* https://anaconda.org/bioconda/beagle/beagle_4.0_06Jun17/download/osx-64/beagle-beagle_4.0_06Jun17-0.tar.bz2
* https://anaconda.org/bioconda/beagle/beagle_4.0_06Jun17/download/linux-64/beagle-beagle_4.0_06Jun17-0.tar.bz2

**Comment by dlaehnemann** [comment]
And thanks for merging!

**Comment by dlaehnemann** [comment]
@bgruening Not sure if the deleting of the files just isn't visible yet, but I can still see the above mentioned files on anaconda--and wanted to bump this up, before I also forget about it...

**Comment by bgruening** [comment]
Sorry, was busy. Done.

**Comment by dlaehnemann** [comment]
Perfect, they're not visible any more. Thanks again!

**Pull request merged**
