### PR TITLE
Update snakemake to 5.27.4

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`snakemake`](https://bioconda.github.io/recipes/snakemake/README.html): **5.26.1** &rarr; **5.27.4**

[install with bioconda](http://bioconda.github.io/recipes/snakemake/README.html) [Conda](https://anaconda.org/bioconda/snakemake/files)

Info | Link
-----|-----
Recipe | [`recipes/snakemake`](https://github.com//bioconda/bioconda-recipes/tree/bump/snakemake/recipes/snakemake) (click to view/edit other files)
Releases |[https://pypi.org/pypi/snakemake/json](https://pypi.org/pypi/snakemake/json)

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by epruesse** [comment]
```
error: package directory 'snakemake/unit_tests/templates' does not exist
```

**Comment by mbargull** [comment]
> @johanneskoester This happens to me with plain `pip install --upgrade snakemake` as well. Manifest?

Yep, internally I've suggested a small fix for that. I guess they'll address it tomorrow/Monday.

> Also - just seeing v1 to v2 conversion failing. Problem is that v1 hashes could contain `/`, which conversion apparently ignores.

What's this referring to?

**Comment by epruesse** [comment]
> What's this referring to?

Was meant for Johannes. Bug in 5.27.2. Went ahead and filed properly at https://github.com/snakemake/snakemake/issues/711

5.27.2 changes the format of the metadata "database" folder Snakemake keeps to be able to tell between jobs that produced files and jobs that actually completed (and a bunch of other things I imagine). With my 50,000 file workflow, the method doing the conversion from format v1 to v2 broke because some files are really directories. I think it's because it's breaking the long file names into paths `this_was_too_long_for_one/file`.

**Comment by Maarten-vd-Sande** [comment]
@epruesse & @mbargull is there a reason this is not (yet) merged?

**Comment by mbargull** [comment]
@maarten-k, we'll be merging this when this PR updates to the next bug fix release (which should be published soon).

**Comment by maarten-k** [comment]
> @maarten-k, we'll be merging this when this PR updates to the next bug fix release (which should be published soon).

@mbargull : You probably ment @Maarten-vd-Sande (all those guys called Maarten: highly confussing ;) )

**Comment by Maarten-vd-Sande** [comment]
> @maarten-k, we'll be merging this when this PR updates to the next bug fix release (which should be published soon).

Awesome!



> > @maarten-k, we'll be merging this when this PR updates to the next bug fix release (which should be published soon).
> 
> @mbargull : You probably ment @Maarten-vd-Sande (all those guys called Maarten: highly confussing ;) )

Should be a law against that ;)

**Comment by mbargull** [comment]
@maarten-k, oh, haha, sorry about that. Yes that was the `maa<TAB>` auto-completion and me not paying attention XD.
Well, but it's about to be sint-maartensfeest -- so, the more the merrier!

**Review by johanneskoester — APPROVED** [review]

**Comment by johanneskoester** [comment]
@bioconda-bot please merge

**Pull request merged**
