### PR TITLE
Fix transit pinning

### PR DESCRIPTION
**Pull request by mvdbeek**
Due to https://github.com/mad-lab/transit/blob/master/setup.py#L151 this
seems necessary.
Currently fails with
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 792, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (Pillow 7.0.0 (/usr/local/lib/python3.7/site-packages), Requirement.parse('pillow~=6.0'), {'tnseq-transit'})
```

**Replace this sentence with a detailed description of your pull request**

----

> Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it.

* [ ] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [ ] This PR adds a new recipe.
* [ ] AFAIK, this recipe **is directly relevant to the biological sciences**
      (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

> Everyone has access to the following BiocondaBot commands, which can be given in a comment:
>
>  * `@BiocondaBot please update` will cause the BiocondaBot to merge the master branch into a PR
>  * `@BiocondaBot please add label` will add the `please review & merge` label.
>  * `@BiocondaBot please fetch artifacts` will post links to packages and docker containers built by the CI system. You can use this to test packages locally before merging.
>
> For members of the Bioconda project, the following command is also available:
>
>  * `@BiocondaBot please merge` will cause packages/containers to be uploaded and a PR merged. Someone must approve a PR first! This has the benefit of not wasting CI build time required by manually merging PRs.
>
> If you have questions, please post them in gitter or ping `@bioconda/core` in a comment (if you are not able to directly ping `@bioconda/core` then the bot will repost your comment and enable pinging).

### CODE REVIEW

**Comment by mvdbeek** [comment]
@BiocondaBot please add label

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Comment by mvdbeek** [comment]
Hmm, despite the package being installable if you force the build number it doesn't get installed if you just do `conda install transit` ... . Is the conda solver selecting the older build because of the more liberal pinnings ? Is there a way to remove the old build to prevent broken installs ?

**Comment by dpryan79** [comment]
If you're using an existing environment then I think the solver will go with the build number requiring the fewest changes to the environment. If you create a new environment then it should go for the newest build.

**Comment by mvdbeek** [comment]
Hmm, let me try that .. I've seen this with mulled builds, which don't actually create environments, so that could be it

**Comment by mvdbeek** [comment]
Nope, same problem with
`conda create  -c conda-forge -c bioconda  transit=3.0.2 python=3.7 -p /usr/local --copy --yes --quiet`

**Comment by mvdbeek** [comment]
fwiw https://travis-ci.org/BioContainers/multi-package-containers/builds/641258741?utm_source=github_status&utm_medium=notification is passing with `conda install  -c conda-forge -c bioconda  transit=3.0.2=py_1 python=3.7 -p /usr/local --copy --yes --quiet]`

**Comment by dpryan79** [comment]
`conda create -n transit transit python=3.7` installs 3.0.2 build 1 for me.

**Comment by dpryan79** [comment]
In fact, `conda create -c conda-forge -c bioconda transit=3.0.2 python=3.7 -p /usr/local --copy --yes --quiet` also installs build 1 for me.

**Comment by mvdbeek** [comment]
That is so weird, both in docker and OSX I always get the py_0 build. Locally I have conda 4.8.0, and the conda in the miniconda image is 4.7.12

**Comment by dpryan79** [comment]
Maybe something is cached by conda.

**Comment by mvdbeek** [comment]
Aha, downgrading to 4.6.14 get's me the _1 build

**Comment by mvdbeek** [comment]
There shouldn't be any cache in the docker image ?!

**Comment by dpryan79** [comment]
I would presume not. I have no idea why different conda versions sometimes behave so differently. For reference I'm using 4.7.12 locally on my linux workstation.

**Comment by mvdbeek** [comment]
Then going back to 4.7.12 in the docker image gives me _0 again. Sounds like something is wrong on the conda side ? I'm gonna ignore this for now and hope someone merges https://github.com/BioContainers/multi-package-containers/pull/953 ;). Thanks for your help @dpryan79!

**Pull request merged**
