### PR TITLE
Update captus to 0.9.94

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`captus`](https://bioconda.github.io/recipes/captus/README.html): **0.9.93** &rarr; **0.9.94**

[install with bioconda](http://bioconda.github.io/recipes/captus/README.html) [Conda](https://anaconda.org/bioconda/captus/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/captus`](https://github.com//bioconda/bioconda-recipes/tree/bump/captus/recipes/captus) (click to view/edit other files)
Summary | Captus: Assembly of Phylogenomic Datasets from High-Throughput Sequencing data
Home | [https://github.com/edgardomortiz/Captus](https://github.com/edgardomortiz/Captus)
Releases |[https://github.com/edgardomortiz/Captus/tags](https://github.com/edgardomortiz/Captus/tags)
Author | `@edgardomortiz`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by edgardomortiz** [comment]
Could I get some help with this error? I didn't change the dependencies at all and now perl 5.26.2 can't be found:

```
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-64: {MatchSpec("perl[version='>=5.26.2,<5.26.3.0a0']"), MatchSpec("perl-bioperl-core==1.007002=pl526_0")}
```

**Comment by edgardomortiz** [comment]
@BiocondaBot recheck

**Comment by edgardomortiz** [comment]
@BiocondaBot rebuild

**Comment by edgardomortiz** [comment]
@BiocondaBot rebuild #42401

**Comment by edgardomortiz** [comment]
@BiocondaBot recheck #42401

**Comment by edgardomortiz** [comment]
@BiocondaBot add label

**Comment by edgardomortiz** [comment]
@BiocondaBot please add label

**Comment by edgardomortiz** [comment]
Could somebody cancel/close this Pull Request please? I will fix the recipe and make a new release I guess

**Comment by mencian** [comment]
Before you release a new version, can you try adding perl to the list of host and run dependencies?   @edgardomortiz

**Comment by edgardomortiz** [comment]
I solved it using different perl packages, please close this PR so I can update my recipe for v0.9.93

**Pull request closed without merging**
