### PR TITLE
vep_98: bump requirements, update build script, perl-bio-db-hts v2.11

### PR DESCRIPTION
**Pull request by matthdsm**
Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it. Note that if you are not already a member of the bioconda project (meaning that you can't add this label), please ping `@bioconda/core` so that your PR can be reviewed and merged (please note if you'd like to be added to the bioconda project). Please see https://github.com/bioconda/bioconda-recipes/issues/15332 for more details.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by matthdsm** [comment]
@bioconda/perl 
Hi guys,
The latest version of VEP requires perl-bio-hts-db >= 2.11. Looking at the [recipe](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/perl-bio-db-hts/meta.yaml) this should be the latest version available in bioconda, but the package can't seem to be found...

Any ideas?
Thanks
M

**Comment by matthdsm** [comment]
Hi @bioconda/lib, 
The bio-db-hts recipe won't build because `no compiler detected to compile 'lib/Bio/DB/HTS.c'`
Any idea why? The compiler section was set in the recipe.

**Comment by dpryan79** [comment]
As you noticed before, that package seems problematic: https://github.com/bioconda/bioconda-recipes/pull/16295

**Comment by matthdsm** [comment]
Hi Devon,
Problematic indeed.. Seems a pity for something that's widely used.
Any more ideas on how to fix it? I've made some attempts in my other PR, but this version is the minimum requirement for the latest VEP. I fear the recipe might be broken by the missing dependency, as build version 0 is already online due to an autobump.

Thanks
M

**Comment by dpryan79** [comment]
@matthdsm I think the other PR will be mergable soon.

**Comment by matthdsm** [comment]
Great! I'll close this PR then and open a new one with only the changes for the VEP.
Thanks for the help!

M

**Pull request closed without merging**
