### PR TITLE
Added somatic sniper recipe

### PR DESCRIPTION
**Pull request by kyleabeauchamp**
* [x] I have read the guidelines above.
* [x] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by kyleabeauchamp** [comment]
cc @bioconda/core new recipe

**Comment by chapmanb** [comment]
Thanks for porting this. +1 for merging

**Comment by johanneskoester** [comment]
@kyleabeauchamp you have added a lot of stuff already. Do you want to be part of the core team?

**Comment by kyleabeauchamp** [comment]
No thanks, I'm OK working from the sidelines :)

**Pull request merged**
