### PR TITLE
Add bioverbs recipe

### PR DESCRIPTION
**Pull request by pinin4fjords**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

This PR adds the bioverbs component of basejump. See discussion at https://github.com/steinbaugh/basejump/issues/141.

### CODE REVIEW

**Comment by mjsteinbaugh** [comment]
Thanks @pinin4fjords. Let's pin it to v0.1.6 instead, which includes an additional `plotCounts()` generic that is now in use in a few dependency packages, including basejump. I added a release for that update.

**Comment by mjsteinbaugh** [comment]
Perfect thanks that looks good

**Comment by pinin4fjords** [comment]
Thanks @mjsteinbaugh . There's a known CI issue right now which prevents merge, hopefully will be resolved soon.

ping @bioconda/core for review of new package

**Comment by dpryan79** [comment]
Is there a reason this is pinned to an out-dated R version?

**Comment by pinin4fjords** [comment]
Was at request of package author @mjsteinbaugh

**Comment by mjsteinbaugh** [comment]
A number of the Bioconductor packages on bioconda aren't updated to R 3.5/BioC 3.8 yet, so we have to maintain support for R 3.4. I'm not sure how we need to pin this in the recipe.

Here's the current approach for bcbioRNASeq, which depends on basejump:
https://github.com/bioconda/bioconda-recipes/tree/master/recipes/r-bcbiornaseq

Maybe @roryk has some advice on how to update the recipe?

**Comment by mjsteinbaugh** [comment]
Sorry about that -- yeah looking at the recipe, we shouldn't need to pin to R 3.4.

**Comment by dpryan79** [comment]
I've updated all of the CRAN and bioconductor packages already, a bunch of non-CRAN/bioconductor packages were blacklisted in the process, but you can feel free to unblacklist them as needed. In general we should remove the `r-` and `bioconductor-` prefixes from the names, though, as they're not CRAN/bioconductor packages.

**Comment by mjsteinbaugh** [comment]
@dpryan79 Is there a recommended prefix if the package is on GitHub? I'm in the process of getting these submitted to Bioconductor, but that takes a while to go through review.

**Comment by epruesse** [comment]
How long does it take? Package names are "forever", so if this will be pushed to bioconductor, it would be best if it does get that name.

**Comment by pinin4fjords** [comment]
Is okay to give it a Bioconductor prefix even if the source is temporarily coming from GitHub @epruesse ?

**Comment by epruesse** [comment]
Ideally, we'd wait for acceptance by bioconductor. That's why I was asking - how long will that take?

**Comment by epruesse** [comment]
You can use `r-bioverbs`.

**Comment by mjsteinbaugh** [comment]
@epruesse I'll try to submit these to Bioconductor ASAP. Apologies for the naming issue.

**Pull request merged**
