### PR TITLE
yahs update 1.1a.1

### PR DESCRIPTION
**Pull request by astrovsky01**
Describe your pull request here

Updates yahs to version 1.1a.1 pinned prerelease with permission from the author.
----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by bgruening** [comment]
@c-zhou can you maybe help here?

**Review by c-zhou — APPROVED** [review]

**Comment by c-zhou** [comment]
Hi all,

Thanks for including yahs. I approved the changes. Anything else I can help with?

Best,
Chenxi

**Comment by astrovsky01** [comment]
Hey Chenxi, we were actually asking about helping out with the wrapper itself. We're having difficulty getting the osx build to work at the moment.

Thanks!

**Comment by c-zhou** [comment]
Hi Alex, I had a commit https://github.com/c-zhou/yahs/commit/e19065aa429439fc8c829687cdb5109355bca159 checked in which should solve the OSX compatibility problem. Just let me know if you still see problems.

Chenxi

**Comment by astrovsky01** [comment]
Cenxi,

That's great, thanks! Bioconda prefers that it be tied to a release, though, so if you could possibly either overwrite 1.1a.1. or update to 1.1a.2, it would be more simple.

Thank you!

**Comment by c-zhou** [comment]
Hi Alex, I tagged a new release 1.1a.2. Chenxi

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
@bioconda-bot please merge

**Pull request merged**
