### PR TITLE
Updates pyteomics and pillow dependencies for matchms 0.19

### PR DESCRIPTION
**Pull request by hechth**
Describe your pull request here

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by hechth** [comment]
@BiocondaBot please add label

**Comment by cbrueffer** [comment]
Hi @hechth , please bump the build number. While here, could you also clarify the license to `APACHE-2.0`?

**Comment by cbrueffer** [comment]
Thanks @hechth and sorry, I meant `Apache-2.0` (as per SPDX), my fault!

**Comment by hechth** [comment]
Wasn't aware of SPDX, thanks, that helps a lot! :D

**Comment by hechth** [comment]
@cbrueffer why does the CI say I need to reset the build number? Also please note that version 0.19 is not yet on bioconda at all, hence I didn't bump the build number in the first place

**Comment by cbrueffer** [comment]
@hechth I missed that this is based on the `bump/matchms` branch, so the build number bump is unnecessary, my bad! I'm hesitant merging this as is, as merging into the bump branch resulted in some unwanted artifacts being uploaded last time I did this.

Could you either make the changes directly in the bot PR, or alternatively base your changes (including the version number and hash update) on the master branch instead?

**Comment by hechth** [comment]
@cbrueffer I can't make changes on the bump PR branch directly - if this would be possible I would also prefer that options, but I don't have write access on this branch. How can I get that?

**Comment by cbrueffer** [comment]
I've sent you an invite to the Bioconda org, that way you can make changes in the bot PR directly.

**Comment by hechth** [comment]
Done - I will then add the dependencies to the bump PR directly.

Are there additional responsibilities connected with being a member of the bioconda organization @cbrueffer and @bgruening ?

**Comment by cbrueffer** [comment]
Not really; try not to mess things up and if you have time, chip in with reviewing/merging PRs :-)

**Pull request closed without merging**
