### PR TITLE
add recipe for Titan-GC

### PR DESCRIPTION
**Pull request by rpetit3**
This PR adds a recipe for [Titan-GC](https://github.com/theiagen/public_health_viral_genomics) a workflow for genomic characterization of viral pathogens of concern, especially the SARS-CoV-2 virus.

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by rpetit3** [comment]
Testing 
```
mamba create -n titan-test -c https://165493-42372094-gh.circle-artifacts.com/0/tmp/artifacts/packages -c conda-forge -c
bioconda titan-gc
...TRUNCATED...
  titan-gc             1.5.0  hdfd78af_0          165493-42372094-gh.circle-artifacts.com/0/tmp/artifacts/packages/noarch      64 KB
...TRUNCATED...
conda activate titan-test
```

```
which titan-gc
/home/robert_petit/miniconda3/envs/titan-test/bin/titan-gc

titan-gc -h
usage: titan-gc [-h] [-i STR] [--inputs STR] [-o STR] [--outdir STR] [--options STR] [--quiet]

titan-gc - Run Titan GC on a set of samples.

required arguments:
  -i STR, --inputs STR  The JSON file to be used with Cromwell for inputs.
  -o STR, --outdir STR  Output directory to store the final results in.

optional arguments:
  -h, --help              Show this help message and exit
  -v, --version           Print the version
  --options STR           JSON file containing Cromwell options
  --profile STR           The backend profile to use [options: docker, singularity]
  --config STR            Custom backend profile to use
  --cromwell_jar STR      Path to cromwell.jar (Default use conda install)
  --quiet                 Silence all STDOUT from Cromwell and titan-gc-organize

titan-gc -v
titan-gc 1.5.0
```

```
titan-gc-prepare.py ../tests/fastq/ illumina_pe ../tests/artic-v3.primers.bed
{
    "titan_gc.samples": [
        {
            "sample": "test001",
            "titan_wf": "illumina_pe",
            "r1": "/home/robert_petit/repos/titan-nf/tests/fastq/test001_R1.fastq.gz",
            "r2": "/home/robert_petit/repos/titan-nf/tests/fastq/test001_R2.fastq.gz",
            "primers": "/home/robert_petit/repos/titan-nf/temp-test/../tests/artic-v3.primers.bed"
        },
        {
            "sample": "test002",
            "titan_wf": "illumina_pe",
            "r1": "/home/robert_petit/repos/titan-nf/tests/fastq/test002_R1.fastq.gz",
            "r2": "/home/robert_petit/repos/titan-nf/tests/fastq/test002_R2.fastq.gz",
            "primers": "/home/robert_petit/repos/titan-nf/temp-test/../tests/artic-v3.primers.bed"
        }
    ]
}
titan-gc-prepare.py ../tests/fastq/ illumina_pe ../tests/artic-v3.primers.bed > inputs.json
export SINGULARITY_CACHEDIR=/opt/singularity/cache/titan/
titan-gc -i inputs.json -o titan-conda-test --profile singularity
Running Titan GC (use --quiet to quiet things down a bit)
[2021-08-17 17:04:38,52] [info] Running with database db.url = jdbc:hsqldb:mem:c114a611-78ae-4d4c-a57a-0e2c8d155de7;shutdown=false;hsqldb.tx=mvcc
[2021-08-17 17:04:50,57] [info] Running migration RenameWorkflowOptionsInMetadata with a read batch size of 100000 and a write batch size of 100000
[2021-08-17 17:04:50,60] [info] [RenameWorkflowOptionsInMetadata] 100%
[2021-08-17 17:04:50,79] [info] Running with database db.url = jdbc:hsqldb:mem:1059cc3b-13d5-4e35-9217-17229e02272f;shutdown=false;hsqldb.tx=mvcc
[INFO] [08/17/2021 17:04:51.875] [cromwell-system-akka.dispatchers.engine-dispatcher-5] [akka://cromwell-system/user/SingleWorkflowRunnerActor] Workflow heartbeat configuration:
{
  "cromwellId" : "cromid-2640f26",
  "heartbeatInterval" : "2 minutes",
  "ttl" : "10 minutes",
  "failureShutdownDuration" : "5 minutes",
  "writeBatchSize" : 10000,
  "writeThreshold" : 10000
}
...TRUNCATED (cromwell is very verbose!)...
[2021-08-17 17:30:27,77] [info] Shutting down JobExecutionTokenDispenser - Timeout = 5 seconds
[2021-08-17 17:30:27,77] [info] WorkflowStoreActor stopped
[2021-08-17 17:30:27,77] [info] JobExecutionTokenDispenser stopped
[2021-08-17 17:30:27,78] [info] WorkflowLogCopyRouter stopped
[2021-08-17 17:30:28,10] [info] Connection pools shut down
[2021-08-17 17:30:28,16] [info] Database closed
[2021-08-17 17:30:28,16] [info] Stream materializer shut down
[2021-08-17 17:30:28,16] [info] WDL HTTP import resolver closed
Titan GC complete, organizing outputs
```

```
tree titan-conda-test/
titan-conda-test/
├── alignments
│   ├── test001.flagstat.txt
│   ├── test001.primertrim.sorted.bam
│   ├── test001.primertrim.sorted.bam.bai
│   ├── test001.stats.txt
│   ├── test001.variants.vcf
│   ├── test002.flagstat.txt
│   ├── test002.primertrim.sorted.bam
│   ├── test002.primertrim.sorted.bam.bai
│   ├── test002.stats.txt
│   └── test002.variants.vcf
├── assemblies
│   ├── test001.ivar.consensus.fasta
│   └── test002.ivar.consensus.fasta
├── cromwell-stderr.txt
├── cromwell-stdout.txt
├── dehosted_reads
│   ├── test001_R1_dehosted.fastq.gz
│   ├── test001_R2_dehosted.fastq.gz
│   ├── test002_R1_dehosted.fastq.gz
│   └── test002_R2_dehosted.fastq.gz
├── kraken2_reports
│   ├── test001_dehosted_kraken2_report.txt
│   ├── test001_kraken2_report.txt
│   ├── test002_dehosted_kraken2_report.txt
│   └── test002_kraken2_report.txt
├── nextclade
│   ├── test001.ivar.consensus.nextclade.auspice.json
│   ├── test001.ivar.consensus.nextclade.json
│   ├── test001.ivar.consensus.nextclade.tsv
│   ├── test002.ivar.consensus.nextclade.auspice.json
│   ├── test002.ivar.consensus.nextclade.json
│   └── test002.ivar.consensus.nextclade.tsv
├── pangolin_reports
│   ├── test001.pangolin_report.csv
│   └── test002.pangolin_report.csv
├── results
│   ├── test001.results.json
│   └── test002.results.json
├── titan-metadata.json
├── titan-results.json
├── titan-results.tsv
└── vadr_alerts
    ├── test001.ivar.consensus.vadr.alt.list
    └── test002.ivar.consensus.vadr.alt.list

8 directories, 37 files

head titan-conda-test/titan-results.tsv
sample  titan_workflow  titan_version   titan_analysis_date     seq_platform    primer_bed_name percent_reference_coverage      number_n        pangolin_lineage        pangolin_conflicts      pangolin_notes  pangolin_version pangolin_docker pangolin_usher_version  nextclade_clade nextclade_aa_subs       nextclade_aa_dels       vadr_num_alerts assembly_length_unambiguous     assembly_mean_coverage  assembly_method number_degenerate        number_total    meanbaseq_trim  meanmapq_trim   fastqc_clean1   fastqc_clean2   fastqc_clean_pairs      fastqc_raw1     fastqc_raw2     fastqc_raw_pairs        kraken_human    kraken_human_dehosted    kraken_sc2      kraken_sc2_dehosted     primer_trimmed_read_percent     artic_version   bbduk_docker    bwa_version     fastqc_version  ivar_variant_version    ivar_version_consensus  ivar_version_primtrim    kraken_version  nextclade_version       samtools_version        samtools_version_consensus      samtools_version_primtrim       samtools_version_stats  trimmomatic_version     vadr_docker
test001 titan_illumina_pe       PHVG v1.5.0     2021-08-17      Illumina paired-end     artic-v3.primers.bed    89.05   3234    B.1.2   0.0     Usher placements: B.1.2(2/2)    pangolin 3.1.3; PUSHER-v1.2.13  staphb/pangolin:3.1.3-pangolearn-2021-06-15      usher 0.3.1     20C     N:P67S,N:P199L,ORF1a:T265I,ORF1a:A1061T,ORF1a:L3352F,ORF1b:P314L,ORF1b:T1555I,ORF1b:N1653D,ORF3a:G11A,ORF3a:Q57H,ORF3a:G172V,ORF8:S24L,S:D614G   NA      0       26628   294.219 BWA Version: 0.7.17-r1188; iVar version 1.3.1   2       29864   38.5    60.0    35284   35284   35284   48907   48907   48907   15.08   0.97    80.03   80.12   29.09   staphb/bbtools:38.76     BWA Version: 0.7.17-r1188       FastQC v0.11.8  iVar version 1.3.1      iVar version 1.3.1      iVar version 1.3.1      Kraken version 2.0.8-beta       1.2.3   samtools 1.12   samtools 1.12    samtools 1.12   samtools 1.10   Trimmomatic 0.39        staphb/vadr:1.3
test002 titan_illumina_pe       PHVG v1.5.0     2021-08-17      Illumina paired-end     artic-v3.primers.bed    71.27   8530    B.1.2   0.0     Usher placements: B.1.2(1/1)    pangolin 3.1.3; PUSHER-v1.2.13  staphb/pangolin:3.1.3-pangolearn-2021-06-15      usher 0.3.1     20G     N:P67S,N:P199L,ORF1a:T265I,ORF1a:M2606I,ORF1a:L3352F,ORF1a:L3606F,ORF1b:P314L,ORF1b:E1242D,ORF1b:T1555I,ORF1b:N1653D,ORF3a:G11A,ORF3a:Q57H,S:D614G       NA      0       21311   230.842 BWA Version: 0.7.17-r1188; iVar version 1.3.1   1       29842   38.4    60.0    29998   29998   29998   40072   40072   40072   12.55   1.07    82.64   82.64   29.09            staphb/bbtools:38.76    BWA Version: 0.7.17-r1188       FastQC v0.11.8  iVar version 1.3.1      iVar version 1.3.1      iVar version 1.3.1      Kraken version 2.0.8-beta       1.2.3   samtools 1.12    samtools 1.12   samtools 1.12   samtools 1.10   Trimmomatic 0.39        staphb/vadr:1.3

```

Everything looks good

**Comment by rpetit3** [comment]
@biocondabot please add label

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Comment by rpetit3** [comment]
Thank you!

**Pull request merged**
