### PR TITLE
Schmutzi recipe

### PR DESCRIPTION
**Pull request by apeltzer**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

Implemented all the changes for 1.5.5.5 now, bamtools is still somewhat the issue. `make install` does something now as per the changes that @grenaud added in https://github.com/bioconda/bioconda-recipes/issues/9794

### CODE REVIEW

**Comment by apeltzer** [comment]
As `libgab` uses bamtools, I had to change the order of the build process there. However, there were missing dependencies to `jsoncpp` missing for the bamtools recipe. Probably also the case in the main bamtools recipe?

**Comment by dpryan79** [comment]
@apeltzer Regarding jsoncpp, that's distributed with bamtools I think. I don't know whether that's included in the compilation by default. If not presumably it just requires a configure option change.

**Comment by apeltzer** [comment]
Hi @dpryan79 , it looks like I found the missing bits and pieces. Had that issue in my local env when testing locally but on CircleCI thats gone. Just patching the last issue (some restructuring of the archive in 1.5.5.5, then things should pass and run through...)

**Comment by apeltzer** [comment]
Hm, tests fail because of missing `utils.h` for example:

```
Executing transaction: ...working... done
+ contDeam
utils.h getCWD failed on  c
Tests failed for schmutzi-1.5.5.5-pl526h1c23ad8_0.tar.bz2 - moving package to /opt/conda/conda-bld/broken
```

**Comment by apeltzer** [comment]
Same story as before @dpryan79 .... not a single step further :-(  Maybe @grenaud knows something about it too? 

```
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
+ contDeam
utils.h getCWD failed on  c
Tests failed for schmutzi-1.5.5.5-pl526h1c23ad8_0.tar.bz2 - moving package to /opt/conda/conda-bld/broken
WARNING:conda_build.build:Tests failed for schmutzi-1.5.5.5-pl526h1c23ad8_0.tar.bz2 - moving package to /opt/conda/conda-bld/broken
removing: schmutzi-1.5.5.5-pl526h1c23ad8_0.tar.bz2
TESTS FAILED: schmutzi-1.5.5.5-pl526h1c23ad8_0.tar.bz2
```

**Comment by apeltzer** [comment]
@grenaud looks like this line here is the "issue"... 

https://github.com/grenaud/libgab/blob/e55806c1f4df93fd516968ce70c9f10bf383f5e0/utils.h#L1357

**Comment by grenaud** [comment]
@apeltzer  I added an exception for a user who complained that under his MacOS, there was no PATH_MAX which is bizarre. Line 1357 should work, I redirect a char * to a stream, what is the specific problem?

**Comment by apeltzer** [comment]
Hi @grenaud, 

compilation of the recipe works fine and then we try to test it which fails unfortunately, with the error message mentioned above
```
utils.h getCWD failed on  c
```
Apparently, when we compile it the way its done here in the compile script, the individual binaries don't work.... even though that should be the case. Seems to look after `utils.h`...

**Comment by grenaud** [comment]
so can I replicate these tests someone?

**Comment by apeltzer** [comment]
Yeah! Just check out the branch, and install conda build in a conda environment and run something like:

`conda build meta.yaml` on the schmutzi recipe. That should run through till the test fails...

Or use one of the approaches described here: https://bioconda.github.io/contribute-a-recipe.html#test-locally

**Comment by grenaud** [comment]
@apeltzer  was a solution found, I still need to address this once my workload goes down a bit.

**Comment by apeltzer** [comment]
Not that I know of, but I'd rather re-open the PR once we have some time to figure out what's going on :-) (otherwise need to merge in `master` from time to time as this repository moves quite quickly ;-)

**Comment by grenaud** [comment]
I am increasingly thinking that I should just remove bamtools and put htslib instead, it would be more time efficient.

**Comment by apeltzer** [comment]
Would probably save you hours of work in the mid and long term...

**Pull request closed without merging**
