### PR TITLE
Update mimseq to 0.3.4.3

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`mimseq`](https://bioconda.github.io/recipes/mimseq/README.html): **0.3.4.1** &rarr; **0.3.4.3**

[install with bioconda](http://bioconda.github.io/recipes/mimseq/README.html) [Conda](https://anaconda.org/bioconda/mimseq/files)

Info | Link
-----|-----
Recipe | [`recipes/mimseq`](https://github.com//bioconda/bioconda-recipes/tree/bump/mimseq/recipes/mimseq) (click to view/edit other files)
Releases |[https://pypi.org/pypi/mimseq/json](https://pypi.org/pypi/mimseq/json)

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by drewjbeh** [comment]
@BiocondaBot please rerun checks

**Comment by drewjbeh** [comment]
@druvus @dpryan79 or anyone else able to help me with this? Seems like a classic case of conda taking really long to solve the environment for this package so that the CircleCI tests time out after 5 hours. 
I recommend users to use mamba to install the package which works fine. I'm not sure what has changed since the previous version of mimseq that now it times out (possibly some package dependencies have been updated?).

**Comment by dpryan79** [comment]
Oof, yeah 2 hours to solve is way over the top. I look forward to someday using mamba for this instead. In the interim, maybe we can tighten the dependency versions.

**Comment by drewjbeh** [comment]
Yeah totally crazy. Thanks for pushing. 

I'll work on being more specific with the versions. Issue is that the versions I use in my local testing environment work fine, but conda still finds conflicts during building. I'll work on it though!

**Pull request closed without merging**
