### PR TITLE
Build k8 on osx-arm64

### PR DESCRIPTION
**Pull request by peterjc**
Needed to build minimap2 #49945.

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

### General instructions

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

### Instructions for avoiding API, ABI, and CLI breakage issues
Conda is able to record and lock (a.k.a. pin) dependency versions used at build time of other recipes.
This way, one can avoid that expectations of a downstream recipe with regards to API, ABI, or CLI are violated by later changes in the recipe.
If not already present in the meta.yaml, make sure to specify `run_exports` (see [here](https://bioconda.github.io/contributor/linting.html#missing-run-exports) for the rationale and comprehensive explanation).
Add a `run_exports` section like this:

```yaml
build:
  run_exports:
    - ...

```

with `...` being one of:

| Case                             | run_exports statement                                               |
| -------------------------------- | ------------------------------------------------------------------- |
| semantic versioning              | `{{ pin_subpackage("myrecipe", max_pin="x") }}`     |
| semantic versioning (0.x.x)      | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}`   |
| known breakage in minor versions | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| known breakage in patch versions | `{{ pin_subpackage("myrecipe", max_pin="x.x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| calendar versioning              | `{{ pin_subpackage("myrecipe", max_pin=None) }}`    |

while replacing `"myrecipe"` with either `name` if a `name|lower` variable is defined in your recipe or with the lowercase name of the package in quotes.

### Bot commands for PR management

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

Note that the <code>@BiocondaBot please merge</code> command is now depreciated. Please just squash and merge instead.

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by peterjc** [comment]
Looks like a compilation error:

```
14:59:26 BIOCONDA INFO (OUT)   arm64-apple-darwin20.0.0-clang++ -o $SRC_DIR/node-v18.19.1/out/Release/obj.target/v8_compiler/deps/v8/src/compiler/access-info.o ../deps/v8/src/compiler/access-info.cc '-D_GLIBCXX_USE_CXX11_ABI=1' '-DNODE_OPENSSL_CONF_NAME=nodejs_conf' '-DNODE_OPENSSL_HAS_QUIC' '-DICU_NO_USER_DATA_OVERRIDE' '-DV8_GYP_BUILD' '-DV8_TYPED_ARRAY_MAX_SIZE_IN_HEAP=64' '-D_DARWIN_USE_64_BIT_INODE=1' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DV8_TARGET_ARCH_ARM64' '-DV8_HAVE_TARGET_OS' '-DV8_TARGET_OS_MACOS' '-DV8_EMBEDDER_STRING="-node.28"' '-DENABLE_DISASSEMBLER' '-DV8_PROMISE_INTERNAL_FIELD_COUNT=1' '-DOBJECT_PRINT' '-DV8_INTL_SUPPORT' '-DV8_ATOMIC_OBJECT_FIELD_WRITES' '-DV8_ENABLE_LAZY_SOURCE_POSITIONS' '-DV8_USE_SIPHASH' '-DV8_SHARED_RO_HEAP' '-DV8_WIN64_UNWINDING_INFO' '-DV8_ENABLE_REGEXP_INTERPRETER_THREADED_DISPATCH' '-DV8_ENABLE_SYSTEM_INSTRUMENTATION' '-DV8_ENABLE_WEBASSEMBLY' '-DV8_ENABLE_JAVASCRIPT_PROMISE_HOOKS' '-DV8_ALLOCATION_FOLDING' '-DV8_ALLOCATION_SITE_TRACKING' '-DV8_SCRIPTORMODULE_LEGACY_LIFETIME' '-DV8_ADVANCED_BIGINT_ALGORITHMS' '-DUCONFIG_NO_SERVICE=1' '-DU_ENABLE_DYLOAD=0' '-DU_STATIC_IMPLEMENTATION=1' '-DU_HAVE_STD_STRING=1' '-DUCONFIG_NO_BREAK_ITERATION=0' -I../deps/v8 -I../deps/v8/include -I$SRC_DIR/node-v18.19.1/out/Release/obj/gen/generate-bytecode-output-root -I$SRC_DIR/node-v18.19.1/out/Release/obj/gen -I../deps/icu-small/source/i18n -I../deps/icu-small/source/common  -O3 -gdwarf-2 -fstrict-aliasing -mmacosx-version-min=10.15 -arch arm64 -Wall -Wendif-labels -W -Wno-unused-parameter -std=gnu++17 -stdlib=libc++ -fno-rtti -fno-exceptions -fno-strict-aliasing -MMD -MF $SRC_DIR/node-v18.19.1/out/Release/.deps/$SRC_DIR/node-v18.19.1/out/Release/obj.target/v8_compiler/deps/v8/src/compiler/access-info.o.d.raw -D_FORTIFY_SOURCE=2 -isystem $PREFIX/include -mmacosx-version-min=11.0 -ftree-vectorize -fPIC -fstack-protector-strong -O2 -pipe -stdlib=libc++ -fvisibility-inlines-hidden -fmessage-length=0 -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/k8-1.2 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix -c
14:59:27 BIOCONDA INFO (ERR) In file included from ../deps/v8/src/compiler/backend/frame-elider.cc:5:
14:59:27 BIOCONDA INFO (ERR) In file included from ../deps/v8/src/compiler/backend/frame-elider.h:8:
14:59:27 BIOCONDA INFO (ERR) In file included from ../deps/v8/src/compiler/backend/instruction.h:13:
14:59:27 BIOCONDA INFO (ERR) In file included from ../deps/v8/src/codegen/external-reference.h:9:
14:59:27 BIOCONDA INFO (ERR) In file included from ../deps/v8/src/runtime/runtime.h:11:
14:59:27 BIOCONDA INFO (ERR) ../deps/v8/src/base/bit-field.h:43:29: error: integer value 31 is outside the valid range of values [0, 15] for this enumeration type [-Wenum-constexpr-conversion]
14:59:27 BIOCONDA INFO (ERR)   static constexpr T kMax = static_cast<T>(kNumValues - 1);
14:59:27 BIOCONDA INFO (ERR)                             ^
14:59:27 BIOCONDA INFO (ERR) In file included from ../deps/v8/src/compiler/backend/gap-resolver.cc:5:
14:59:27 BIOCONDA INFO (ERR) In file included from ../deps/v8/src/compiler/backend/gap-resolver.h:8:
14:59:27 BIOCONDA INFO (ERR) In file included from ../deps/v8/src/compiler/backend/instruction.h:13:
14:59:27 BIOCONDA INFO (ERR) In file included from ../deps/v8/src/codegen/external-reference.h:9:
14:59:27 BIOCONDA INFO (ERR) In file included from ../deps/v8/src/runtime/runtime.h:11:
14:59:27 BIOCONDA INFO (ERR) ../deps/v8/src/base/bit-field.h:43:29: error: integer value 31 is outside the valid range of values [0, 15] for this enumeration type [-Wenum-constexpr-conversion]
14:59:27 BIOCONDA INFO (ERR)   static constexpr T kMax = static_cast<T>(kNumValues - 1);
14:59:27 BIOCONDA INFO (ERR)                             ^
14:59:27 BIOCONDA INFO (ERR) In file included from ../deps/v8/src/compiler/backend/code-generator.cc:5:
14:59:27 BIOCONDA INFO (ERR) In file included from ../deps/v8/src/compiler/backend/code-generator.h:11:
14:59:27 BIOCONDA INFO (ERR) In file included from ../deps/v8/src/codegen/macro-assembler.h:8:
14:59:27 BIOCONDA INFO (ERR) In file included from ../deps/v8/src/codegen/turbo-assembler.h:12:
14:59:27 BIOCONDA INFO (ERR) In file included from ../deps/v8/src/codegen/assembler-arch.h:8:
14:59:27 BIOCONDA INFO (ERR) In file included from ../deps/v8/src/codegen/assembler.h:46:
14:59:27 BIOCONDA INFO (ERR) In file included from ../deps/v8/src/codegen/external-reference.h:9:
14:59:27 BIOCONDA INFO (ERR) In file included from ../deps/v8/src/runtime/runtime.h:11:
14:59:27 BIOCONDA INFO (ERR) ../deps/v8/src/base/bit-field.h:43:29: error: integer value 31 is outside the valid range of values [0, 15] for this enumeration type [-Wenum-constexpr-conversion]
14:59:27 BIOCONDA INFO (ERR)   static constexpr T kMax = static_cast<T>(kNumValues - 1);
14:59:27 BIOCONDA INFO (ERR)                             ^
.14:59:28 BIOCONDA INFO (ERR) 1 error generated.
14:59:28 BIOCONDA INFO (ERR) make[1]: *** [tools/v8_gypfiles/v8_compiler.target.mk:296: /opt/mambaforge/envs/bioconda/conda-bld/k8_1723215207846/work/node-v18.19.1/out/Release/obj.target/v8_compiler/deps/v8/src/compiler/backend/frame-elider.o] Error 1
14:59:28 BIOCONDA INFO (ERR) make[1]: *** Waiting for unfinished jobs....
```

i.e. Three cases of ``../deps/v8/src/base/bit-field.h:43:29: error: integer value 31 is outside the valid range of values [0, 15] for this enumeration type [-Wenum-constexpr-conversion]``

**Comment by attractivechaos** [comment]
Summarize the discussion in https://github.com/attractivechaos/k8/issues/14:
* k8 is only compatible with Node.js v18.x, not more recent node versions
* node-18.19.x can be compiled on CentOS 7 (this is how k8 bioconda builds currently work on Linux), but it can't be compiled on MacOS with clang due to a compiling error shown above
* node-18.20.x can be compiled on MacOS but not on CentOS 7 because it includes an updated c-ares library which is incompatible with glibc on CentOS 7

Conclusion:

* Use node-18.19.1 for CentOS 7
* Use node-18.20.4 for MacOS

**Comment by peterjc** [comment]
Thanks - that looks like enough clues to try a little further.

We can probably start by switching NODE_VERSION by platform here:
 
https://github.com/bioconda/bioconda-recipes/blob/master/recipes/k8/build.sh

**Comment by peterjc** [comment]
Explained - I was using node-18.20.4 on macOS and Linux, where it was expected to fail.

I naively used the platform-specific pragma support in ``meta.yaml`` in ``build.sh`` 🤦

**Comment by peterjc** [comment]
Now I see why Python gets involved - this is the node v18.20.4 configure script:

```python
#!/bin/sh

# Locate an acceptable Python interpreter and then re-execute the script.
# Note that the mix of single and double quotes is intentional,
# as is the fact that the ] goes on a new line.
_=[ 'exec' '/bin/sh' '-c' '''
command -v python3.12 >/dev/null && exec python3.12 "$0" "$@"
command -v python3.11 >/dev/null && exec python3.11 "$0" "$@"
command -v python3.10 >/dev/null && exec python3.10 "$0" "$@"
command -v python3.9 >/dev/null && exec python3.9 "$0" "$@"
command -v python3.8 >/dev/null && exec python3.8 "$0" "$@"
command -v python3.7 >/dev/null && exec python3.7 "$0" "$@"
command -v python3.6 >/dev/null && exec python3.6 "$0" "$@"
command -v python3 >/dev/null && exec python3 "$0" "$@"
exec python "$0" "$@"
''' "$0" "$@"
]
del _

import sys
try:
  from shutil import which
except ImportError:
  from distutils.spawn import find_executable as which

print('Node.js configure: Found Python {}.{}.{}...'.format(*sys.version_info))
acceptable_pythons = ((3, 12), (3, 11), (3, 10), (3, 9), (3, 8), (3, 7), (3, 6))
if sys.version_info[:2] in acceptable_pythons:
  import configure
else:
  python_cmds = ['python{}.{}'.format(*vers) for vers in acceptable_pythons]
  sys.stderr.write('Please use {}.\n'.format(' or '.join(python_cmds)))
  for python_cmd in python_cmds:
      python_cmd_path = which(python_cmd)
      if python_cmd_path and 'pyenv/shims' not in python_cmd_path:
        sys.stderr.write('\t{} {}\n'.format(python_cmd_path, ' '.join(sys.argv[:1])))
  sys.exit(1)
```

The version with node 18.19.1 is similar but does not consider Python 3.12 to be acceptable.

We should be safe with just:

```python
#!/usr/bin/env python3
import configure
```

Or rather than running ``./configure ...`` using ``python -c "import configure" ...`` seems best.

**Comment by peterjc** [comment]
Build timed out - I'll rebase the branch as an expedient way to rebuild.

**Comment by peterjc** [comment]
Timed out again, perhaps the explicit python build dependency is to blame?

**Comment by mencian** [comment]
@peterjc You may have to use the large `aarch64` machine - see [this comment](https://github.com/bioconda/bioconda-recipes/pull/46559/files#r1536582200) by @martin-g.

**Comment by peterjc** [comment]
It looks like BioConda is using the large ``aarach64`` machine on CircleCI as of #46735 (although if this should be reverted for most builds is worth considering).

Right now this is timing out on Azure, exactly as per [the follow-up comment](https://github.com/bioconda/bioconda-recipes/pull/46559/files#r1551652795) from @martin-g - I'm guessing since it did pass on #46559 that we were (and perhaps still are) right on the cusp of some time limit or other timeout?

Assuming https://docs.github.com/en/actions/administering-github-actions/usage-limits-billing-and-administration applies, there is a 6 hour limit - we're not hitting that I don't think, rather it looks like a different limit and losing contact:

``This job was abandoned. We have detected that logs from the agent may have not finished uploading. We have included our in-memory record of all log lines uploaded before we lost contact with the agent:`` (at about 2h35m on test_linux)

**Comment by martin-g** [comment]
> t looks like BioConda is using the large `aarach64` machine on CircleCI as of #46735 (although if this should be reverted for most builds is worth considering).

I also noticed this recently, but since the `large` VM is part of the free plan I decided not to revert it back to `medium`. Several other recipes also require a `large` VM at CircleCI.

> Assuming https://docs.github.com/en/actions/administering-github-actions/usage-limits-billing-and-administration applies, there is a 6 hour limit

Github Actions != Azure CI

I think the problem is memory related. The builds sometimes pass, sometimes fail. We just have to keep trying!

**Comment by attractivechaos** [comment]
Thank you all for the help through this complicated issue. Now I see from [Azure console](https://dev.azure.com/bioconda/bioconda-recipes/_build/results?buildId=67573&view=logs&j=e14e69ff-a0ae-55c4-b71d-229b239cfb2f&t=7df82132-b284-504b-53d6-7d3e63519572&l=4594):
```
##[warning]Free memory is lower than 5%; Currently used: 95.33%
```
How much memory does the VM have? Didn't realize compiling node uses this much memory.

**Comment by peterjc** [comment]
The good news is build-and-test (ARM) under CircleCI is working fine.

Can we mark this recipe as arm-only temporarily perhaps? e.g.

```
build:
   skip: true  # [x86_64]
```

**Comment by mencian** [comment]
LGTM for now, can push this PR out to get `minimap2` to build, then revisit to get the recipe to build on `x86_64`.

**Review by mencian — APPROVED** [review]

**Pull request merged**
