### PR TITLE
update andi to 0.13

### PR DESCRIPTION
**Pull request by pmenzel**
Describe your pull request here

update andi to 0.13
----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by pmenzel** [comment]
@bioconda/core: in this PR I intend to update andi to 0.13, and at the same time maybe fix a dependency issue, that I get with other packages. For example, I get
```
UnsatisfiableError: The following specifications were found to be incompatible with each other:

Package gsl conflicts for:
bioconda::mash=2.2.2 -> gsl[version='>=2.5,<2.6.0a0']
bioconda::andi=0.12 -> gsl[version='2.2.*|>=2.2.1,<2.3.0a0']
...
```
So it seems that andi 0.12 can have gsl not above 2.3.0. I am not sure where these version requirements for gsl are stored, I didn't see it in meta.yaml.

Now I added gsl >=2.2 as a dependency in the hopes that it will also accept higher versions, resolving the conflict.

**Comment by dpryan79** [comment]
@bioconda-bot please fetch artifacts

@pmenzel Thanks, the GSL restriction comes from a global pinning file. I'm surprised the old version didn't get rebuilt when we updated the GSL pinning.

**Comment by dpryan79** [comment]
Ah, I bet the recipe is blacklisted due to compilation issues. That'd explain things.

**Comment by pmenzel** [comment]
Thanks for looking into it, Devon.
The compiler error message is
```
17:34:49 BIOCONDA INFO (OUT) pfasta.c:39:10: fatal error: threads.h: No such file or directory
17:34:49 BIOCONDA INFO (OUT)  #include <threads.h>
```` 
Maybe the used gcc is too old not have C11 threads?

**Comment by dpryan79** [comment]
It's gcc 7. I'm guess that we need to pass `std=c11`.

**Comment by dpryan79** [comment]
Actually, glibc only added support in 2018 or so, so that'd be after the version we're using (HPCs don't exactly update frequently, we're building basically with centos 6).

**Comment by pmenzel** [comment]
would it be helpful to ask the author for statically linked binaries, that could instead be used?

**Comment by dpryan79** [comment]
That'd be one option

**Comment by kloetzl** [comment]
Hi all,

andi (or to be precise, its FASTA parser pasta) can be compiled without threads.h. Newer C version set __STDC_NO_THREADS__ to indicate it is not available. Apparently, the converse is not true. Can you try to build with `export CFLAGS="$CFLAGS -D__STDC_NO_THREADS__=1"`?

Hope this helps,
Fabian

**Comment by pmenzel** [comment]
hurray, it seems to have worked!

**Comment by kloetzl** [comment]
Thanks for your effort, I will look for a patch [upstream](https://github.com/kloetzl/pfasta) and integrate it in both andi and [phylonium](https://github.com/EvolBioInf/phylonium) (the successor to andi). So the next time things should be easier again. :smile:

**Comment by pmenzel** [comment]
Thanks for your fast fix! :)

quick question: Would you recommend to use phylonium (once it is available in bioconda) over andi when only having a handful of genomes? My understanding was that phylonium is "just" faster, but not more accurate.

**Comment by kloetzl** [comment]
One could say that phylonium is andi, but faster. As long as your genomes are closely related you should not see a big difference in the estimated substitution rates. Note that “faster” means 2× for small data sets and minutes instead of hours for thousands of bacterial genomes.

**Comment by pmenzel** [comment]
@BiocondaBot please merge

**Comment by dpryan79** [comment]
@bioconda-bot please fetch artifacts

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Comment by kloetzl** [comment]
Thanks everyone for your work!

**Pull request merged**
