### PR TITLE
Update adam to 0.26.0

### PR DESCRIPTION
**Pull request by heuermh**
:information_source:
Bioconda has finished the [GCC7 migration](https://github.com/bioconda/bioconda-recipes/issues/13578). If you are dealing with C/C++ or Python package it can be that you need to rebuild other dependent packages. [Bioconda utils - update-pinning](https://bioconda.github.io/updating.html#updating-recipes-for-a-pinning-change) will assist you with that. If you have any questions please use [issue 13578](https://github.com/bioconda/bioconda-recipes/issues/13578).

----------------

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by heuermh** [comment]
I don't understand the build failure in circleci, ADAM does not depend on any of `{ tabix, ucsc-bedtogenepred, ucsc-overlapselect, ucsc-pslcdnafilter, ucsc-pslmap }`.

```
19:48:17 BIOCONDA INFO Recipes to build: 
adam
tabix
ucsc-bedtogenepred
ucsc-overlapselect
ucsc-pslcdnafilter
ucsc-pslmap
19:48:17 BIOCONDA INFO Building and testing subdag 1 of 1 (7 recipes)
19:48:17 BIOCONDA INFO Determining expected packages
Setting build platform. This is only useful when pretending to be on another platform, such as for rendering necessary dependencies on a non-native platform. I trust that you know what you're doing.
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
Adding in variants from internal_defaults
Adding in variants from /home/circleci/project/miniconda/conda_build_config.yaml
Adding in variants from /home/circleci/project/miniconda/lib/python3.6/site-packages/bioconda_utils/bioconda_utils-conda_build_config.yaml
Attempting to finalize metadata for adam
19:48:27 BIOCONDA INFO BUILD START recipes/adam
..
19:51:05 BIOCONDA INFO BUILD SUCCESS adam-0.26.0-1.tar.bz2
19:51:05 BIOCONDA INFO TEST START via mulled-build recipes/adam
The update_index function has changed to index all subdirs at once.  You're pointing it at a single subdir.  Please update your code to point it at the channel root, rather than a subdir.
WARNING:conda_build.index:The update_index function has changed to index all subdirs at once.  You're pointing it at a single subdir.  Please update your code to point it at the channel root, rather than a subdir.
The update_index function has changed to index all subdirs at once.  You're pointing it at a single subdir.  Please update your code to point it at the channel root, rather than a subdir.
WARNING:conda_build.index:The update_index function has changed to index all subdirs at once.  You're pointing it at a single subdir.  Please update your code to point it at the channel root, rather than a subdir.
....
19:55:15 BIOCONDA INFO TEST SUCCESS recipes/adam
19:55:16 BIOCONDA INFO Determining expected packages
19:55:16 BIOCONDA INFO FILTER: not building recipe recipes/tabix/0.2.6 because the same number of builds are in channel(s) and it is not forced.
19:55:16 BIOCONDA INFO Nothing to be done for recipe recipes/tabix/0.2.6
19:55:16 BIOCONDA INFO Determining expected packages
19:55:16 BIOCONDA INFO FILTER: not building recipe recipes/tabix/0.2.5 because the same number of builds are in channel(s) and it is not forced.
19:55:16 BIOCONDA INFO Nothing to be done for recipe recipes/tabix/0.2.5
19:55:16 BIOCONDA INFO Determining expected packages
19:55:16 BIOCONDA INFO FILTER: not building recipe recipes/ucsc-bedtogenepred because the same number of builds are in channel(s) and it is not forced.
19:55:16 BIOCONDA INFO Nothing to be done for recipe recipes/ucsc-bedtogenepred
19:55:16 BIOCONDA INFO Determining expected packages
19:55:17 BIOCONDA INFO FILTER: not building recipe recipes/ucsc-overlapselect because the same number of builds are in channel(s) and it is not forced.
19:55:17 BIOCONDA INFO Nothing to be done for recipe recipes/ucsc-overlapselect
19:55:17 BIOCONDA INFO Determining expected packages
Attempting to finalize metadata for ucsc-pslcdnafilter
Solving environment: ...working... done
Solving environment: ...working... done
Solving environment: ...working... done
19:55:28 BIOCONDA ERROR BUILD ERROR: packages with divergent build strings in repository for recipe recipes/ucsc-pslcdnafilter. A build number bump is likely needed: ('ucsc-pslcdnafilter-366-h5eb252a_0', 'ucsc-pslcdnafilter-366-hdd26221_0')
19:55:28 BIOCONDA INFO Determining expected packages
Attempting to finalize metadata for ucsc-pslmap
19:55:28 BIOCONDA ERROR BUILD ERROR: packages with divergent build strings in repository for recipe recipes/ucsc-pslmap. A build number bump is likely needed: ('ucsc-pslmap-366-h5eb252a_0', 'ucsc-pslmap-366-hdd26221_0')
19:55:28 BIOCONDA ERROR BUILD SUMMARY: of 7 recipes, 2 failed and 0 were skipped. Details of recipes and environments follow.
19:55:28 BIOCONDA ERROR BUILD SUMMARY: while the entire build failed, the following recipes were built successfully:
recipes/adam
19:55:28 BIOCONDA ERROR BUILD SUMMARY: FAILED recipe recipes/ucsc-pslcdnafilter
19:55:28 BIOCONDA ERROR BUILD SUMMARY: FAILED recipe recipes/ucsc-pslmap
Exited with code 1
```

**Comment by druvus** [comment]
@heuermh please merge in the latest master into your branch to solve the issue.

**Comment by heuermh** [comment]
Thank you, @druvus.  Rebased and force-pushed.

**Comment by heuermh** [comment]
Thank you, @druvus!

**Pull request merged**
