### PR TITLE
Update vibrant to 1.2.1

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`vibrant`](https://bioconda.github.io/recipes/vibrant/README.html): **1.2.0** &rarr; **1.2.1**

[install with bioconda](http://bioconda.github.io/recipes/vibrant/README.html) [Conda](https://anaconda.org/bioconda/vibrant/files)

Info | Link
-----|-----
Recipe | [`recipes/vibrant`](https://github.com//bioconda/bioconda-recipes/tree/bump/vibrant/recipes/vibrant) (click to view/edit other files)
Releases |[https://github.com/AnantharamanLab/VIBRANT/tags](https://github.com/AnantharamanLab/VIBRANT/tags)
Author | `@AnantharamanLab`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by KrisKieft** [comment]
@bioconda-bot please merge

**Comment by KrisKieft** [comment]
@BiocondaBot please fetch artifacts

**Comment by KrisKieft** [comment]
@BiocondaBot please merge

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Pull request merged**
