### PR TITLE
2020.2

### PR DESCRIPTION
**Pull request by gbayarri**
Describe your pull request here

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Comment by dpryan79** [comment]
@bioconda-bot please fetch artifacts

**Comment by dpryan79** [comment]
I'm not sure why there were no build artifacts before.

**Comment by dpryan79** [comment]
@bioconda-bot please update

Maybe this will get things moving

**Comment by dpryan79** [comment]
I don't understand why this is getting ignored. @mbargull Do you have any clue?

**Comment by mbargull** [comment]
`.yml`

**Comment by mbargull** [comment]
We apparently have a linter check for that. I guess it isn't triggered because the folder isn't registered as a recipe at all.

**Comment by gbayarri** [comment]
Hi Marcel, how should I do that?

Best.

**Comment by mbargull** [comment]
Sorry, I was in a hurry. So, the recipe file is supposed to be named `meta.yaml` not `meta.yml`.
A PR with a `git mv recipes/biobb_ml/meta.{yml,yaml} && git commit` should do it.
I'll change our build system so that it will put out a linter error for this in the future.

**Comment by gbayarri** [comment]
But all the recipes I build for other packages were .yml and they worked
fine.

**Comment by mbargull** [comment]
`conda-build` is rather picky about that filename. I'm afraid you might be misremembering or someone else fixed the filenames then.

**Comment by gbayarri** [comment]
Ok, but for this package can you fix it or should I make another build?

Thanks for your help.

**Comment by mbargull** [comment]
Please open another pull request. (Feel free to ping me on that one if you have any other questions.)

**Comment by gbayarri** [comment]
Hi Marcel, just a last doubt: in a previous message you said the folder
isn’t registered as a recipe. There is something to do about that or I just
must rename the file to meta.yaml and change the build number?

Thanks.

**Comment by mbargull** [comment]
The folder wasn't picked up as a recipe since it is expected to have a `meta.yaml` file (see https://github.com/bioconda/bioconda-utils/pull/668/files#diff-3b688d85fb0c75729505ac1a43c8ab74L807 for the change in `bioconda-utils` that will make the CI not silently pass in the future).
If you just rename the file it should work. You can also reset the build number back to `0` since no builds of the recipes have happened anyway.

**Pull request merged**
