### PR TITLE
Add czlab_perl_lib

### PR DESCRIPTION
**Pull request by zhixingfeng**
Describe your pull request here

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by zhixingfeng** [comment]
@BiocondaBot please add label

**Comment by zhixingfeng** [comment]
@bioconda/core

**Comment by zhixingfeng** [comment]
ping @bioconda/core

**Comment by dpryan79** [comment]
Can you expand on the description? At the moment I have absolutely no clue what this could be used for.

**Comment by zhixingfeng** [comment]
> Can you expand on the description? At the moment I have absolutely no clue what this could be used for.

@dpryan79 . Failed to find a place to put the description. So add it here. Please let me know if this is not the right place.

czlab_per_lib is the core CLI and perl library used in mCross, which is a bioinformatic tool to identify RNA-protein cross-link sites. See details of the methods in 

Feng et al. (2019), Modeling the in vivo specificity of RNA-binding proteins by precisely registering protein-RNA crosslink sites. Mol Cell. 74:1189-1204.E6. | Feng et al. (2019), Modeling the in vivo specificity of RNA-binding proteins by precisely registering protein-RNA crosslink sites. Mol Cell. 74:1189-1204.E6.

**Comment by zhixingfeng** [comment]
Added description in meta.yaml @dpryan79

**Comment by dpryan79** [comment]
@BiocondaBot please fetch artifacts

**Comment by zhixingfeng** [comment]
Done. The description is good now. Thank you very much for your help. @dpryan79

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@BiocondaBot please merge

**Comment by zhixingfeng** [comment]
Tried "conda install -c bioconda czlab_perl_lib", but seems it can not be found in the channels yet. Should I do something or just wait for several days? @dpryan79

**Pull request merged**
