### PR TITLE
Feature/bioconductor cummerbund

### PR DESCRIPTION
**Pull request by jerowe**
* [x] I have read the guidelines above.
* [x] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

Bioconductor Cummerbund 

http://bioconductor.org/packages/release/bioc/html/cummeRbund.html

### CODE REVIEW

**Comment by bgruening** [comment]
ping @davebx, you might be interested in this work :)

**Comment by jerowe** [comment]
Is there a way to specify a version in the bioconductor skeleton script? Or should I just wait for R 3.3.0 to be merged?

**Comment by jerowe** [comment]
Just because I want to know, why am I getting an error that R 3.3.0 is not available?

https://anaconda.org/r/r-base

```
conda install -c r r-base=3.3.0 
```

Gets me

```
Error:  Package missing in current linux-64 channels: 
  - r-base 3.3|3.3.0*  
```

Why?

**Comment by bgruening** [comment]
I you can wait, please wait. We hope to have the release this week.

**Comment by jerowe** [comment]
I can wait.

**Comment by jerowe** [comment]
@bgruening , how goes the new R? If I could get these done this week I can go on vacation with a free spirit!

**Comment by bgruening** [comment]
@daler is working on it. It seems to be more complicated than expected :(

**Comment by jerowe** [comment]
@bgruening, do you know why this fails? I have the same travis ci setup on my repo as you guys do, and it passes:

[Bioconda Build](https://travis-ci.org/bioconda/bioconda-recipes/builds/148732467)
[My Build - same setup](https://travis-ci.org/jerowe/bioconda-recipes/builds/148732456)

**Comment by bgruening** [comment]
@jerowe the build system is currently broken. Should be fixed tomorrow, sorry for any inconvenience.

**Comment by jerowe** [comment]
Oh, alright. No problem. I was just starting to wonder if I'd missed some important update from the bioconda side. ;-)

**Pull request merged**
