### PR TITLE
satsuma a new recipes

### PR DESCRIPTION
**Pull request by mictadlo**
* [ ] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by mictadlo** [comment]
Hi @bioconda/core ,
This software needs at least gcc 5.2. How is it possible to select a newer version than GCC  4.8.5?

Thank you in advance.

Michal

**Comment by mictadlo** [comment]
@bioconda/core Why did ci/circleci test-linux failed?

**Comment by daler** [comment]
The log says:
```
The CI configuration is out of date.
Please merge in bioconda:master.
```

This is because there were recently some changes to the configuration, so you'll need to merge in the bioconda master branch to update your fork.

**Comment by mictadlo** [comment]
Thank you. I updated my fork the new recipe is here https://github.com/bioconda/bioconda-recipes/pull/8545

**Pull request closed without merging**
