### PR TITLE
Update fastobo to 0.8.2

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`fastobo`](https://bioconda.github.io/recipes/fastobo/README.html): **0.7.2** &rarr; **0.8.2**

[install with bioconda](http://bioconda.github.io/recipes/fastobo/README.html) [Conda](https://anaconda.org/bioconda/fastobo/files)

Info | Link
-----|-----
Recipe | [`recipes/fastobo`](https://github.com//bioconda/bioconda-recipes/tree/bump/fastobo/recipes/fastobo) (click to view/edit other files)
Releases |[https://pypi.org/pypi/fastobo/json](https://pypi.org/pypi/fastobo/json)
Recipe Maintainer(s) | @althonos

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by althonos** [comment]
Please wait before bumping manually; the latest Rust nightly compiler broke my build and I haven't been able to upload wheels for all the platforms I need to support.

**Comment by althonos** [comment]
@bioconda-bot please merge

**Comment by dpryan79** [comment]
@BiocondaBot please merge

**Comment by dpryan79** [comment]
@althonos Shall I add you to bioconda so you can merge these in the future?

**Comment by althonos** [comment]
@dpryan79 : would be happy to ! i have a few packages that I maintain or am willing to add to bioconda so I'd be really happy with write access.

**Pull request merged**
