### PR TITLE
Feature/perl blacklist

### PR DESCRIPTION
**Pull request by jerowe**
* [ ] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [ ] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [x] This PR does something else (explain below).
More!

### CODE REVIEW

**Comment by bgruening** [comment]
Do we need a stash::xs package? 
`! Installing the dependencies failed: Module 'Package::Stash::XS' is not installed`

**Comment by jerowe** [comment]
Maybe? Let me try and we will see!

**Comment by jerowe** [comment]
@bgruening  - do you know what is the deal with this error? It is only on osx, not linux.

```
Traceback (most recent call last):
  File "/Users/distiller/project/miniconda/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/Users/distiller/project/miniconda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 420, in main
    execute(sys.argv[1:])
  File "/Users/distiller/project/miniconda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 411, in execute
    verify=args.verify)
  File "/Users/distiller/project/miniconda/lib/python3.6/site-packages/conda_build/api.py", line 200, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/Users/distiller/project/miniconda/lib/python3.6/site-packages/conda_build/build.py", line 2177, in build_tree
    notest=notest,
  File "/Users/distiller/project/miniconda/lib/python3.6/site-packages/conda_build/build.py", line 1571, in build
    built_package = bundlers[output_d.get('type', 'conda')](output_d, m, env, stats)
  File "/Users/distiller/project/miniconda/lib/python3.6/site-packages/conda_build/build.py", line 938, in bundle_conda
    files = post_process_files(metadata, initial_files)
  File "/Users/distiller/project/miniconda/lib/python3.6/site-packages/conda_build/build.py", line 800, in post_process_files
    post_build(m, new_files, build_python=python)
  File "/Users/distiller/project/miniconda/lib/python3.6/site-packages/conda_build/post.py", line 646, in post_build
    osx_is_app=osx_is_app)
  File "/Users/distiller/project/miniconda/lib/python3.6/site-packages/conda_build/post.py", line 55, in fix_shebang
    with io.open(path, encoding=locale.getpreferredencoding(), mode='r+') as fi:
PermissionError: [Errno 13] Permission denied: '/Users/distiller/project/miniconda/conda-bld/perl-package-stash_1531933975322/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/package-stash-conflicts'
```

**Comment by bgruening** [comment]
No, but can you try to set `HOME=/tmp cpanm --installdeps .` as well for stash?
ping @bioconda/osx

**Comment by jerowe** [comment]
Ooo forgot that. its probably that.

**Comment by acaprez** [comment]
It's a permissions issue with that `package-stash-conflicts` file.  I've seen this before with a couple other Perl packages - for some reason some files get installed with no user write perms, which breaks `conda-build`.  I added `chmod 755 ${PREFIX}/bin/package-stash-conflicts` as the last line of the build script and it built ok in my OS X VM then.

**Comment by jerowe** [comment]
Thanks, @acaprez . I will try it!

**Comment by bgruening** [comment]
Is green @jerowe!

**Pull request merged**
