### PR TITLE
Update medaka to 0.12.0

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`medaka`](https://bioconda.github.io/recipes/medaka/README.html): **0.11.5** &rarr; **0.12.0**

[install with bioconda](http://bioconda.github.io/recipes/medaka/README.html) [Conda](https://anaconda.org/bioconda/medaka/files)

Info | Link
-----|-----
Recipe | [`recipes/medaka`](https://github.com//bioconda/bioconda-recipes/tree/bump/medaka/recipes/medaka) (click to view/edit other files)
Releases |[https://pypi.org/pypi/medaka/json](https://pypi.org/pypi/medaka/json)
Recipe Maintainer(s) | @cjw85

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by dfornika** [comment]
Build log is reporting: 

```
18:26:50 BIOCONDA INFO (OUT) ClobberWarning: This transaction has incompatible packages due to a shared path.
18:26:50 BIOCONDA INFO (OUT)   packages: defaults::libopenblas-0.3.6-h5a2b251_2, conda-forge::openblas-0.3.3-h9ac9557_1001, conda-forge::libblas-3.8.0-11_openblas
18:26:50 BIOCONDA INFO (OUT)   path: 'lib/libblas.so'
18:26:50 BIOCONDA INFO (OUT) 
18:26:50 BIOCONDA INFO (OUT) 
18:26:50 BIOCONDA INFO (OUT) ClobberWarning: This transaction has incompatible packages due to a shared path.
18:26:50 BIOCONDA INFO (OUT)   packages: defaults::libopenblas-0.3.6-h5a2b251_2, conda-forge::openblas-0.3.3-h9ac9557_1001, conda-forge::libcblas-3.8.0-11_openblas
18:26:50 BIOCONDA INFO (OUT)   path: 'lib/libcblas.so'
18:26:50 BIOCONDA INFO (OUT) 
18:26:50 BIOCONDA INFO (OUT) 
18:26:50 BIOCONDA INFO (OUT) ClobberWarning: This transaction has incompatible packages due to a shared path.
18:26:50 BIOCONDA INFO (OUT)   packages: defaults::libopenblas-0.3.6-h5a2b251_2, conda-forge::openblas-0.3.3-h9ac9557_1001
18:26:50 BIOCONDA INFO (OUT)   path: 'lib/liblapack.so'
18:26:50 BIOCONDA INFO (OUT) 
18:26:50 BIOCONDA INFO (OUT) 
18:26:50 BIOCONDA INFO (OUT) ClobberWarning: This transaction has incompatible packages due to a shared path.
18:26:50 BIOCONDA INFO (OUT)   packages: defaults::libopenblas-0.3.6-h5a2b251_2, conda-forge::openblas-0.3.3-h9ac9557_1001
18:26:50 BIOCONDA INFO (OUT)   path: 'lib/libopenblas.so'
18:26:50 BIOCONDA INFO (OUT) 
18:26:50 BIOCONDA INFO (OUT) 
18:26:50 BIOCONDA INFO (OUT) ClobberWarning: This transaction has incompatible packages due to a shared path.
18:26:50 BIOCONDA INFO (OUT)   packages: defaults::libopenblas-0.3.6-h5a2b251_2, conda-forge::openblas-0.3.3-h9ac9557_1001
18:26:50 BIOCONDA INFO (OUT)   path: 'lib/libopenblas.so.0'
```

**Comment by marcelm** [comment]
The package pulls in both libopenblas from the defaults channel and openblas from conda-forge. This is the only mention of blas in the run dependencies:
```
 - libopenblas ==0.3.3  # [osx]
```
I saw @dpryan79 has commented on openblas/libopenbla before, perhaps he knows more.

This appears not to be the reason the tests fail, however.

**Comment by cjw85** [comment]
I looks like something is going wrong running `medaka_version_report`, this should output something like:

```medaka_version_report
Program    Version    Required   Pass
bcftools   1.10.2     1.10       True
bgzip      1.9        1.9        True
minimap2   2.17       2.11       True
samtools   1.9        1.9        True
tabix      1.9        1.9        True```

and exit 0 or perhaps:

```medaka_version_report
Program    Version    Required   Pass
bcftools   1.10.2     1.10       True
bgzip      Not found  1.9        False
minimap2   2.17       2.11       True
samtools   1.9        1.9        True
tabix      1.9        1.9        True
```

and exit 1. However there's no output from the command in the build log.

@dpryan79 I agree the explicit inclusion of openblas doesn't make too much sense, however its only for MacOS and the reason it was added is noted in the meta file.

**Comment by cjw85** [comment]
We're going to make a new upstream release to set all the htslib echosystem tools to the same version

**Pull request closed without merging**
