### PR TITLE
ProPhyle 0.2.1.0

### PR DESCRIPTION
**Pull request by karel-brinda**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by karel-brinda** [comment]
@bioconda/core Please, could you help me to find what's the problem here? I cannot find out from the log what's the failing part. Thank you.

**Comment by daler** [comment]
@karel-brinda often this happens due to missing deps or incorrect shebang lines. Some hints for figuring it out with local testing: https://bioconda.github.io/troubleshooting.html#troubleshooting-failed-mulled-build-tests

**Comment by karel-brinda** [comment]
@daler  So there is basically no direct way how to clearly identify the error without local testing? This is just an update of a working recipe. There were no changes in package dependencies. The only big difference I am aware of is this line: https://github.com/bioconda/bioconda-recipes/blob/c2b0196f683cc73a081bf81235a11d5e7543af98/recipes/prophyle/build.sh#L7.

@bioconda/core Would it be possible to provide more details in the logs so that all error messages would be included in this case?

**Comment by daler** [comment]
@karel-brinda you can try in your PR setting BIOCONDA_UTILS_BUILD_ARGS to `--loglevel=debug` in `.travis.yml` for debugging on travis-ci. I can try this out locally later today or tomorrow if you'd like.

**Comment by karel-brinda** [comment]
@daler It seems that the problem was really caused by that line (`prophyle compile`). This would mean that  a program that is newly installed using `setup.py` cannot be immediately executed from `build.sh`.

**Pull request merged**
