### PR TITLE
Update bbknn to 1.4.1

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`bbknn`](https://bioconda.github.io/recipes/bbknn/README.html): **1.4.0** &rarr; **1.4.1**

[install with bioconda](http://bioconda.github.io/recipes/bbknn/README.html) [Conda](https://anaconda.org/bioconda/bbknn/files)

Info | Link
-----|-----
Recipe | [`recipes/bbknn`](https://github.com//bioconda/bioconda-recipes/tree/bump/bbknn/recipes/bbknn) (click to view/edit other files)
Releases |[https://pypi.org/pypi/bbknn/json](https://pypi.org/pypi/bbknn/json)
Recipe Maintainer(s) | @jenzopr

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Review by rpetit3 — APPROVED** [review]

**Comment by rpetit3** [comment]
@biocondabot please merge

**Comment by jenzopr** [comment]
@bgruening @daler How to proceed here? :-)

**Comment by rpetit3** [comment]
I've had success rerunning the tests to get the artifacts for BiocondaBot to merge.

But I'm not sure that's necessary, and am also interested on how to proceed.

**Comment by mirand863** [comment]
@bioconda-bot please fetch artifacts

**Comment by mirand863** [comment]
@bioconda-bot please merge

**Pull request merged**
