### PR TITLE
Update groot to 0.8.6

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`groot`](https://bioconda.github.io/recipes/groot/README.html): **0.8.5** &rarr; **0.8.6**

[install with bioconda](http://bioconda.github.io/recipes/groot/README.html) [Conda](https://anaconda.org/bioconda/groot/files)

Info | Link
-----|-----
Recipe | [`recipes/groot`](https://github.com//bioconda/bioconda-recipes/tree/bump/groot/recipes/groot) (click to view/edit other files)
Releases |[https://github.com/will-rowe/groot/tags](https://github.com/will-rowe/groot/tags)
Author | @will-rowe
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by dpryan79** [comment]
The lz4 dependency needs to be updated.

**Comment by will-rowe** [comment]
hi @dpryan79 - thanks for all your effort in trying to get this to work! Are saying this error is due to the incompatible tag on the lz4 library import in the Go mod? This is an indirect dependency which I don't think I have any control over, should I be engaging with the project that uses this dependency?

**Comment by dpryan79** [comment]
I don't know enough about go to say. The`+incompatible` tag seems correct since there's no go.mod, I just don't know why go is trying to install the non-existent v3 version.

**Comment by will-rowe** [comment]
I'm not sure I'm getting the issue here. Go is able to build this despite the +incompatible flags - it's passing the travis tests and the release builds are fine etc. Can you give me any pointers on how to access the Circle error message? All I can see is that the build script failed - sorry for the noob question, I'm struggling to work it out.

**Comment by dpryan79** [comment]
The log is available here: https://circleci.com/gh/bioconda/bioconda-recipes/95838?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link

The only obvious error that I see is that it can't install lz4 because it can't find it.

**Comment by will-rowe** [comment]
Thanks very much @dpryan79 . have just had a poke around and I think it's actually being caused by another dependency that is pulling the v3 lz3 lib. Issue [here](https://github.com/mholt/archiver/issues/211). I'll see if I can fix it

**Comment by will-rowe** [comment]
closing in favour of a new release - where I have removed these dependencies

**Pull request closed without merging**
