### PR TITLE
Adding MView v1.68

### PR DESCRIPTION
**Pull request by eunos-1128**
Adding MView that extracts and reformats the results of a sequence database search or multiple alignment.

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

### General instructions

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

### Instructions for avoiding API, ABI, and CLI breakage issues
Conda is able to record and lock (a.k.a. pin) dependency versions used at build time of other recipes.
This way, one can avoid that expectations of a downstream recipe with regards to API, ABI, or CLI are violated by later changes in the recipe.
If not already present in the meta.yaml, make sure to specify `run_exports` (see [here](https://bioconda.github.io/contributor/linting.html#missing-run-exports) for the rationale and comprehensive explanation).
Add a `run_exports` section like this:

```yaml
build:
  run_exports:
    - ...

```

with `...` being one of:

| Case                             | run_exports statement                                               |
| -------------------------------- | ------------------------------------------------------------------- |
| semantic versioning              | `{{ pin_subpackage("myrecipe", max_pin="x") }}`     |
| semantic versioning (0.x.x)      | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}`   |
| known breakage in minor versions | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| known breakage in patch versions | `{{ pin_subpackage("myrecipe", max_pin="x.x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| calendar versioning              | `{{ pin_subpackage("myrecipe", max_pin=None) }}`    |

while replacing `"myrecipe"` with either `name` if a `name|lower` variable is defined in your recipe or with the lowercase name of the package in quotes.

### Bot commands for PR management

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

Note that the <code>@BiocondaBot please merge</code> command is now depreciated. Please just squash and merge instead.

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by aliciaaevans** [comment]
@martin-g How were you able to trigger the CircleCI job on https://github.com/bioconda/bioconda-recipes/pull/50687? It doesn't seem to be an option for me unless the PR (`pull/50893`) shows up in the branch dropdown.

@eunos-1128 I'm not sure why CircleCI is not working for this PR. It might be worth trying again with a fresh PR.

**Comment by martin-g** [comment]
@aliciaaevans I went to https://app.circleci.com/pipelines/github/bioconda/bioconda-recipes?branch=pull%2F50700%2Fhead (this is for PR #50700) and replaced it with `50687`. Then I clicked on `Trigger Pipeline` button at the top-right corner.  I think it worked because the CI check was executed several times and then disappeared.

I was not able to do the same for https://github.com/bioconda/bioconda-recipes/pull/50820 though. CircleCI have never seen this PR before, so I was not able to `re-trigger` it.

**Comment by martin-g** [comment]
Not able to trigger it for https://app.circleci.com/pipelines/github/bioconda/bioconda-recipes?branch=pull%2F50893%2Fhead too ...

**Comment by aliciaaevans** [comment]
Looking more at it. It seems that CircleCI ran those jobs under @eunos-1128's repo instead of the PR. But I'm not sure why this is happening for a few repos and not others.

**Comment by eunos-1128** [comment]
@aliciaaevans @martin-g 

OK, Thanks for investigating the problem.

I deleted my fork once and then re-created bioconda-recipes' fork again.

It looks working.

**Pull request closed without merging**
