### PR TITLE
update flowcl

### PR DESCRIPTION
**Pull request by cristhomas**
* [ ] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by daler** [comment]
@bgruening looks like timeouts to bioaRchive: https://travis-ci.org/bioconda/bioconda-recipes/jobs/212105323#L600

I restarted the build, but the error was:
```
WARNING requests.packages.urllib3.connectionpool:urlopen(673): Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fd152851128>, 'Connection to bioarchive.galaxyproject.org timed out. (connect timeout=6.1)')': /flowCL_1.11.2.tar.gz
```

**Comment by bgruening** [comment]
Urgs, will ping people to get it up and running again. Sorry.

**Comment by cristhomas** [comment]
Actually if you want to avoid that, I can put in the bioconductor link to the 1.12.0 version.

**Comment by cristhomas** [comment]
unless the bioconductor.org/../../../*targ.gz are frowned upon?

**Pull request merged**
