### PR TITLE
Update bwa and samtools in bwakit recipe to newest versions

### PR DESCRIPTION
**Pull request by rhpvorderman**
The old bwa kit script has not received any upgrades since BWA 0.7.15. BWA however has received updates and is now on 07.17. Samtools has also received upgrades and is now on 1.10. There is a *huge* difference between 1.3 and 1.10 for samtools.
I am currently running some alignments piped through samtools sort and there seems to be a huge memory leak in 1.3, that is hopefully resolved in 1.10.

It would be great if this package would allow the newest version of BWA and samtools to be used.

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by rhpvorderman** [comment]
Pinging @stekaz . You poured a lot of work into making this recipe work. What do you think about this?

**Comment by stekaz** [comment]
Thanks @rhpvorderman , I would very much like to upgrade to use BWA 0.7.17 especially. My only concern is that the BWAKIT on source-forge bundles particular versions of the tools and it might be unexpected to get BWA 0.7.17 when installing BWAKIT 0.7.15. What do you think about creating a 'dev' version of this package? For example: `{% set version = "0.7.17-dev1" %}` similar to the [fermikit](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/fermikit/meta.yaml) recipe?

Please see also: https://github.com/bioconda/bioconda-recipes/pull/22771

**Comment by rhpvorderman** [comment]
Hi @stekaz . That's a great idea! I was feeling a bit uncomfortable making this change. Using a dev version would indeed solve the problem, presuming that 0.7.15 will be the default version installed still. 

I have raised the issue with the BWA developers, but so for no response: https://github.com/lh3/bwa/issues/268 .

Since 0.7.15 is the canonical version I will make a new pull request were I make sure that the 0.7.15 recipe is kept.

**Comment by rhpvorderman** [comment]
@stekaz

**Comment by stekaz** [comment]
@rhpvorderman I opted for `samtools >=1.3` so that it's incompatible with earlier versions. I think just setting 'samtools' will allow any version (including versions < 1.3) which would break the run-bwamem script. Setting >= 1.3 should (hopefully) use the latest samtools. I also changed the build script so that I could remove a couple of the patch files. It now just gets the 0.7.17 bwakit scripts from the BWA repo. Hope this is ok.

**Comment by rhpvorderman** [comment]
This is superseded.

**Pull request closed without merging**
