### PR TITLE
Bump PlantTribes recipes to version 0.6

### PR DESCRIPTION
**Pull request by gregvonkuster**
* [x] I have read the guidelines above.
* [x] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by gregvonkuster** [comment]
@bgruening Any idea what may be causing these errors?  Is this a travis timeout problem or something else?

**Comment by gregvonkuster** [comment]
Ping @bgruening Can you try resubmitting this PR for testing?  I think there may have been a travis timeout problem or something.  Or should I try submitting these recipe updates in separate PRs?

**Comment by bgruening** [comment]
Sorry, I had a terrible week. I restarted the testing. It seems there was a download problem of one of the packages. No timeout as far as I can see.

**Comment by gregvonkuster** [comment]
Thanks @bgruening It looks like 2 of the 3 recipes failed:
```
ERROR bioconda_utils.build:build_recipes(375): BIOCONDA BUILD SUMMARY: of 3 recipes, 2 failed and 0 were skipped. Details of recipes and environments follow.
ERROR bioconda_utils.build:build_recipes(381): BIOCONDA BUILD SUMMARY: while the entire build failed, the following recipes were built successfully:
recipes/plant_tribes_assembly_post_processor/0.6
```
I'll close this PR and submit the 3 recipes separately.

**Pull request closed without merging**
