### PR TITLE
Update htslib to 1.11

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`htslib`](https://bioconda.github.io/recipes/htslib/README.html): **1.10.2** &rarr; **1.11**

[install with bioconda](http://bioconda.github.io/recipes/htslib/README.html) [Conda](https://anaconda.org/bioconda/htslib/files)

Info | Link
-----|-----
Recipe | [`recipes/htslib`](https://github.com//bioconda/bioconda-recipes/tree/bump/htslib/recipes/htslib) (click to view/edit other files)
Releases |[https://github.com/samtools/htslib/releases](https://github.com/samtools/htslib/releases)
Author | `@samtools`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by jmarshall** [comment]
This has picked up a temporarily-attached incorrect asset. Please restart when there is a tarball with a sha256sum of d41399999de18609d0f58d6385d206f525e80f0d363a17f312a80b8d4f7e2fd6.

**Comment by jmarshall** [comment]
:x:

**Comment by bgruening** [comment]
I guess this looks correct now?

**Comment by jmarshall** [comment]
Yes.

And the samtools and bcftools companion PRs failed because they need their htslib pinnings updated to 1.11, of course.

**Review by rpetit3 — APPROVED** [review]

**Comment by rpetit3** [comment]
@bioconda-bot please merge

**Pull request merged**
