### PR TITLE
Rdkit with pillow; compilation with new build system

### PR DESCRIPTION
**Pull request by dmaticzka**
* [x] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

This recreates the reverted commits of pull request #2078 for debugging the build using the current build system.

### CODE REVIEW

**Comment by dmaticzka** [comment]
Make exits with error 2 without any error message, am I missing something here?

**Comment by johanneskoester** [comment]
The error occurs [here](https://travis-ci.org/bioconda/bioconda-recipes/jobs/149434091#L3602). I am currently not sure if it is maybe related to our new build system. We might need to revert to the old build system before we can sort this out.

**Comment by dmaticzka** [comment]
Okay. One more try without the patches, maybe the culprit is there.

**Comment by dmaticzka** [comment]
Thanx :)

**Comment by johanneskoester** [comment]
We have reverted to the old, stable build system. By updating this branch, you will get it as well.

**Pull request merged**
