### PR TITLE
Update sqlalchemy-datatables to 2.0.1

### PR DESCRIPTION
**Pull request by epruesse**
Update [`sqlalchemy-datatables`](https://bioconda.github.io/recipes/sqlalchemy-datatables/README.html): **0.3.0** &rarr; **2.0.1**

[install with bioconda](http://bioconda.github.io/recipes/sqlalchemy-datatables/README.html) [Conda](https://anaconda.org/bioconda/sqlalchemy-datatables/files)

Info | Link
-----|-----
Recipe | [`recipes/sqlalchemy-datatables`](https://github.com//bioconda/bioconda-recipes/tree/bump/sqlalchemy_datatables/recipes/sqlalchemy-datatables) (click to view/edit other files)
Releases |[https://pypi.org/pypi/sqlalchemy-datatables/json](https://pypi.org/pypi/sqlalchemy-datatables/json)

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/updating.html)).

### CODE REVIEW

**Comment by epruesse** [comment]
@BiocondaBot lint

**Comment by epruesse** [comment]
@biocondabot update

**Comment by epruesse** [comment]
upload and merge

**Comment by dpryan79** [comment]
@bioconda-bot merge

**Pull request merged**
