### PR TITLE
updates vsearch to 1.9.7

### PR DESCRIPTION
**Pull request by brwnj**

### CODE REVIEW

**Comment by tomkinsc** [comment]
Perhaps in addition to bumping the version of the main recipe, a [sub-recipe](https://github.com/bioconda/bioconda-recipes#managing-multiple-versions-of-a-package) should be added for the older version.

@johanneskoester @daler @brentp Do we have a general guideline on retaining old versions?

**Comment by brwnj** [comment]
It's discussed here: https://github.com/bioconda/bioconda-recipes/issues/232

All prior builds are maintained on Anaconda Cloud, but now I see they're recommending saving the current configuration by adding within the recipe dir:

    versions/<version>/meta.yaml

Someone would have to explain to me how that's practical because it's lost on me. Are we saying we need to keep them so that just in case it needs to be rebuilt? Why would a user use the bioconda channel or `conda` at that point and not just install from its source?

**Comment by tomkinsc** [comment]
Right, #232 addresses some of the rationale for having recipes with separate versions, but we have not yet had many "updates" submitted. Perhaps we should discuss how to (administratively) handle what should happen when a version is updated. I'd argue in favor of always adding a copy of the old version as a sub-recipe when version numbers are raised. Right now old versions are only present as needed. Perhaps there should be a guideline of "every time you update a working recipe, put a copy of the old one below it." Thoughts, team?

Users can come up with many reasons for why it is practical to keep old recipes, but a major one is that building from source is not always trivial, and sometimes the compilation process changes between versions. [The talk](https://www.youtube.com/watch?v=UaIvrDWrIWM) that sold me on conda couched it as a way to to smooth out the bumps of dependency resolution and compilation, particularly for packages that are otherwise tricky to build. Some of our recipes have patches or fixes as part of the build process. If one happens to need to build an old version of something (to take advantage of new/different CPU instructions and optimizations, for example), it would be helpful if the recipe works and is easy to find.

In the future perhaps conda will give an option to install from source as well, allowing for direct compilation and install of arbitrary versions.

**Comment by daler** [comment]
Disadvantages to keeping old recipes in this repo:
- administrative overhead
- keeping older recipe versions is redundant -- they're available in the git history and in older package version tarballs' `info` dir stored on anaconda.org.

Advantages:
- much easier to see what's changed over versions when it's laid out in dirs and text files
- very little storage overhead
- grepping the repo is sometimes easier than searching anaconda.org for what's available

Am I missing anything in these lists? Administrative overhead might not be too bad if our docs are clear on exactly what should happen for an update PR.

**Comment by brentp** [comment]
I thought the point of having the history was that it makes it possible to support the case when I have a package that depends on `other-package==0.16` but other-package is currently at 0.19.

Is that not the case?

**Comment by bgruening** [comment]
@daler I think we can get around of the administrative overhead by a little bit of scripting. As soon as you submit a version-numer change, we could automatically create a copy of the old one. So you need only to edit the most current file and we create the backup at merge-time automatically.

**Comment by daler** [comment]
@brentp: Right. But we have two different ways of having an older recipe. The first is creating a recipe for an older version even though we already have an updated one already (#232 is about this, seems mostly solved). The question here is about the second way: when I update a recipe, what should I do with the old one? Overwrite it or move it to a subdir? More of a policy decision I guess.

To clarify, this is just about what to do with the text files in the repo. Package tarballs of old versions should stay on anaconda.org unless we explicitly delete them for some reason. 

@bgruening sounds good, but how do we actually do that? Is that in a webhook triggered by a PR? Or something in the travis build?

**Comment by brentp** [comment]
@daler got it. thanks for the explanation.

**Comment by bgruening** [comment]
@daler I think we can do this with travis.
Idea would be something along these lines:
* ask if the branch is master
* ask for the changes
* look into the meta.yaml
* extract version information
* check if version version has changed between the first and last revision
* if so, create a folder and extract all files from the first revision into it

**Comment by brwnj** [comment]
If we're going to keep old versions, in addition to fully documenting how exactly we want that to look, we also need to document what's expected from a user if they need a previous version.

**Comment by johanneskoester** [comment]
Indeed. As the opinions on how important this is are quiet different and basically only affect us developers, it might be a good idea to have a poll among all members of the team.

**Comment by johanneskoester** [comment]
Apart from that I think it is safe to merge this recipe now, right? It complies with our current policy.

**Comment by tomkinsc** [comment]
Ok to merge! Sorry for delaying that, @brwnj

**Pull request merged**
