### PR TITLE
Remove abruijn; it was renamed Flye

### PR DESCRIPTION
**Pull request by corburn**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [x] This PR does something else (explain below).

The developer of Abruijin renamed it Flye.
https://github.com/fenderglass/Flye/blob/flye/README.md#flye-assembler-successor-of-abruijn

### CODE REVIEW

**Comment by peterjc** [comment]
Is there a new recipe for Flye planned on another pull request, or can we rename and update this recipe? Would that give a useful git history?

**Comment by corburn** [comment]
Flye was introduced in this commit:

```
commit b04050f19e3f5b3b5ba4fa5cbca21ee09dca8e1f
Author: Andreas Sjödin <andreas.sjodin@gmail.com>
Date:   Sat Jan 6 00:54:57 2018 +0100

    Add flye (#7207)

    * Add flye

    * Add back llvm
```

**Comment by peterjc** [comment]
Thanks - b04050f19e3f5b3b5ba4fa5cbca21ee09dca8e1f from #7207 - I should have searched.

It seems unlikely then that Abruijin v1.x will get any more updates; I'm unclear if that means BioConda should keep the recipe or not. I'm going to defer to the BioConda core team on this.

**Comment by kyleabeauchamp** [comment]
Yeah, I'm not sure if we need to delete the recipe in this case...

**Comment by druvus** [comment]
I added both packages and back then I decided to keep the abruijn recipe. However I don't have strong opinion so it fine to remove it for me. I think we should come up with some recommendation how to handle cases when software are renamed.

**Comment by mmiladi** [comment]
@druvus @kyleabeauchamp I am in the favor of renaming/removing the recipe. Since the original repository has been renamed, not cloned/forked, even the url within the recipe https://github.com/fenderglass/ABruijn/ does not exist and redirects to Flye, the old versions of tarball as well.

**Comment by corburn** [comment]
Rebased onto master.

**Pull request merged**
