### PR TITLE
Rcas 1

### PR DESCRIPTION
**Pull request by dyusuf**
* [x] I have read the guidelines above.
* [x] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by dyusuf** [comment]
@bgruening  the failure is "quadmath.h No such file or directory" 

two possible reasons: 
1. include path is wrong
2. libquadmath-devel is not installed in condaforge/linux-anvil

I looked at the docker file, it is likely the 2nd reason. 

I wanted to test out the 2nd reason with the docker container locally, but I could not connect to the network from the container, may be because of the firewall issue. 

could you help out?

**Comment by dyusuf** [comment]
@daler @bgruening 

I tried to run simulate-travis.py to test the recipe. 

when running ./simulate-travis.py --packages package_name --loglevel=debug

I got the error from scripts/travis-run.sh,

updating index in: /opt/conda/conda-bld/linux-64
updating index in: /opt/conda/conda-bld/noarch
**Could not find URL: file:///opt/host-conda-bld/linux-64/**

what could be the reason?

**Comment by bgruening** [comment]
Is this under OSX?
Is libquadmath not included in GCC?

**Comment by bgruening** [comment]
The error I can see is: https://travis-ci.org/bioconda/bioconda-recipes/jobs/173260716#L797
`Error : object ‘as_tibble’ is not exported by 'namespace:tibble'`

**Comment by dyusuf** [comment]
regarding error related to libquadmath, it seems have gone after I included gcc as dependency of r-purrr. 

I am now trying to find the solution for the error related to tibble.

before doing that, I trying to make simulate-travis.py work in my system. well, I got the error Could not find URL: file:///opt/host-conda-bld/linux-64/

I am using ubuntu 14.04

**Comment by bgruening** [comment]
Which Docker version? Seems to be Docker related, as if the mount-point is not correct.

**Comment by dyusuf** [comment]
Docker version 1.12.3, build 6b644ec

**Comment by bgruening** [comment]
Solved on chat.

**Pull request closed without merging**
