### PR TITLE
Update thapbi-pict to 0.6.3

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`thapbi-pict`](https://bioconda.github.io/recipes/thapbi-pict/README.html): **0.6.1** &rarr; **0.6.3**

[install with bioconda](http://bioconda.github.io/recipes/thapbi-pict/README.html) [Conda](https://anaconda.org/bioconda/thapbi-pict/files)

Info | Link
-----|-----
Recipe | [`recipes/thapbi-pict`](https://github.com//bioconda/bioconda-recipes/tree/bump/thapbi_pict/recipes/thapbi-pict) (click to view/edit other files)
Releases |[https://pypi.org/pypi/thapbi_pict/json](https://pypi.org/pypi/thapbi_pict/json)
Recipe Maintainer(s) | @peterjc

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by bgruening** [comment]
@peterjc please use

@BiocondaBot please merge

to merge  :)

**Comment by peterjc** [comment]
Rather than clicking the GitHub green merge button, or is that much the
same end result?

(I had been waiting for the continuous integration tests to finish)

**Comment by bgruening** [comment]
Same result, but the Bot is moving artefacts if possible so less burden on the CI.

@peterjc can I have your opinion on the tbl2asn PR ... we are have a serious problem with tbl2asn :(

**Comment by peterjc** [comment]
@BiocondaBot please merge

**Pull request merged**
