### PR TITLE
nextflow 0.25.1

### PR DESCRIPTION
**Pull request by pditommaso**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by bgruening** [comment]
look good, thanks @pditommaso

**Comment by pditommaso** [comment]
@bioconda/core I have problem with the biocontainer created by this recipe. The nextflow installer executed during the build process downloads some JAR libraries that are stored in the path `$HOME/.nextflow`. However in the resulting container none of those files exist thus the container is useless. Do you any idea what's the problem? is the home path (which I suppose is `/root`) stripped during the container build.

**Comment by bgruening** [comment]
@pditommaso everything what is not in $PRRFIX ist stripped away. This also holds true for Conda. Does the conda recipe work? PLease store the JAR file under $PREFIX.

**Comment by pditommaso** [comment]
I see. Yes the recipe works, but the container downloads the required deps each time is launched. To store the JARs under `$PREFIX` I need to define a custom env var. How can I do that? Thanks.

**Comment by bgruening** [comment]
Only during container startup with `-e` I guess. Need to leave, and will be back in the evening, Sorry.

**Comment by pditommaso** [comment]
No hurry. Anyhow I know `-e` but it's not a solution. I would require to add a env variable in a permanent way. Is that possible?

**Comment by pditommaso** [comment]
Just to close this, is there any way to define a custom variable in a Conda recipe / Biocontainer ?

**Pull request merged**
