### PR TITLE
R canopy

### PR DESCRIPTION
**Pull request by vinjana**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by jenzopr** [comment]
Looks good, but is there a specific reason to use version 1.2.0 instead of 1.3.0 that you currently get by default via CRAN? 
You could also use `conda skeleton cran canopy` to automatically create the recipe (see https://bioconda.github.io/guidelines.html#r-cran for guidelines).

Best,
Jens

**Comment by vinjana** [comment]
Yes. That's the version we need for our workflow publication. Getting the researchers to re-test their workflows with newer versions is a hard business.

Thanks for the r-cran tip!

**Comment by jenzopr** [comment]
Alright! I think we can merge it for now so that the version 1.2.0 is available for you.
However, once its build, we should update the recipe to 1.3.0 (with `conda skeleton cran canopy`).
Would that be fine for you?

**Comment by vinjana** [comment]
Great. Thanks. I guess I should leave the 1.2 in a versioned subdirectory, right?

**Comment by jenzopr** [comment]
No need for that. Once 1.2.0 is built successfully, the version will be persistent in the bioconda channel even if we update to 1.3.0 afterwards.

**Pull request merged**
