### PR TITLE
Added YAMDA recipe

### PR DESCRIPTION
**Pull request by simonvh**
* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [X] This PR adds a new recipe.
* [X] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by druvus** [comment]
@BiocondaBot please update

**Comment by raivivek** [comment]
@simonvh Wondering if you're still interested in getting this recipe to work. Thanks!

**Comment by simonvh** [comment]
It would be great to have it work (I would like [gimmemotifs](https://github.com/simonvh/gimmemotifs) to support it), but I don't have the time to work on it myself.

**Comment by raivivek** [comment]
@BiocondaBot update

**Comment by raivivek** [comment]
@simonvh I'll open a new PR to address this. Thanks!

**Comment by raivivek** [comment]
@simonvh The YAMDA recipe is now merged so feel free to use it with your tool.

**Pull request closed without merging**
