### PR TITLE
Update cgat-scripts package

### PR DESCRIPTION
**Pull request by sebastian-luna-valero**
* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [X] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [X] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by sebastian-luna-valero** [comment]
@bioconda/core please review

We have updated our code, so after releasing the `cgat-scripts` package on this PR, we'd like to get rid of the following meta-packages in `bioconda`:
* http://bioconda.github.io/recipes/cgat-pipelines-nosetests/README.html
* http://bioconda.github.io/recipes/cgat-scripts-nosetests/README.html
* http://bioconda.github.io/recipes/cgat-scripts-devel/README.html

I am deleting their recipes on this PR, could you please remove them from the bioconda repository?

Best regards,
Sebastian

**Comment by bgruening** [comment]
Hi @sebastian-luna-valero!

Are you really sure about this:
`I am deleting their recipes on this PR, could you please remove them from the bioconda repository?`

What about users that are using your packages? Should I mark them as deprecated? This means they are not installable with the normal `conda install` but if someone complains we can point them in the direction to install the old packages.

**Comment by sebastian-luna-valero** [comment]
Hi @bgruening!

Many thanks for double-checking before deletion. 

I confirm I am really sure about deleting those packages. They were only used for our continuous integration tests, internally to our group so nobody else is expecting to be using them. I have now moved those to conda environment files under version control so the are no longer needed.

Best regards,
Sebastian

**Comment by bgruening** [comment]
Ok, done!

**Comment by sebastian-luna-valero** [comment]
Thanks!

**Pull request merged**
