### PR TITLE
Update MA to version 1.1.3

### PR DESCRIPTION
**Pull request by ITBE-Lab**
Updating MA to version 1.1.3 - sorry for the rapid pull requests.

### CODE REVIEW

**Comment by ITBE-Lab** [comment]
@BiocondaBot please add label

**Comment by telatin** [comment]
Can we close the autobump then https://github.com/bioconda/bioconda-recipes/pull/26581?

**Comment by ITBE-Lab** [comment]
Hi,

yes, it's not needed.

Does the bot automatically create a pull request everytime i add a new tag to my repository or did i somehow trigger the autobump?

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
Thanks @ITBE-Lab. In the future you might just edit the autogenerated update PRs, since then you can approve and merge them immediately.

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Comment by ITBE-Lab** [comment]
okay, i will do that from now on!

**Comment by ITBE-Lab** [comment]
don't know what the error means, but ma 1.1.3 is now installable.

**Pull request merged**
