### PR TITLE
Update PacBio `pbcopper` version 2.0.0

### PR DESCRIPTION
**Pull request by armintoepfer**
Describe your pull request here

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by armintoepfer** [comment]
Why is the macos build enforcing c++14? @bioconda/osx 

```
 x86_64-apple-darwin13.4.0-clang++ -Isrc/libpbcopper.a.p -Isrc -I../src -Iinclude -I../include -Isrc/utility -fcolor-diagnostics -DNDEBUG -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -Wpedantic -std=c++20 -O3 -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -stdlib=libc++ -fvisibility-inlines-hidden -std=c++14 -fmessage-length=0 -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/pbcopper-2.0.0 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix -D_FORTIFY_SOURCE=2 -isystem $PREFIX/include -mmacosx-version-min=10.9 -isystem$PREFIX/include -DBOOST_ALL_NO_LIB -Wdouble-promotion -Wshadow -MD -MQ src/libpbcopper.a.p/align_SparseAlignment.cpp.o -MF src/libpbcopper.a.p/align_SparseAlignment.cpp.o.d -o src/libpbcopper.a.p/align_SparseAlignment.cpp.o -c ../src/align/SparseAlignment.cpp
```
https://dev.azure.com/bioconda/bioconda-recipes/_build/results?buildId=12526&view=logs&j=1b052f1d-4456-52f0-9d43-71c4c5bd734d&t=edc48dcd-1fc2-5e3b-7036-7be9cea00123&l=268

**Comment by pb-dseifert** [comment]
This is why building stuff within Bioconda is so painful - ancient toolchain and weird forced flags.

**Review by pb-dseifert — APPROVED** [review]

**Comment by armintoepfer** [comment]
Thanks for nothing.

**Comment by epruesse** [comment]
@armintoepfer The C++ standard version used to be set via the environment variables. 14 isn't exactly new any more, and the default in current versions of clang and GC anyway. The compiler settings come from conda forge, actually. I don't recall why it was decided to default to 14 originally. You can always override it though.

**Pull request closed without merging**
