### PR TITLE
Add biopython-convert

### PR DESCRIPTION
**Pull request by innovate-invent**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by innovate-invent** [comment]
@dpryan79 Maybe you can help. I am struggling with a error when running conda build myself:
```
Setuptools downloading is disabled in conda build. Be sure to add all dependencies in the meta.yaml
```

I can't find a clear solution for this, there is no way that I actually have to copy requirements.txt into meta.yml.

**Comment by dpryan79** [comment]
@innovate-invent I'll have a look. Usually this happens when there are `install_requires` or such in `setup.py`. The normal methods of `python -m pip --no-deps` doesn't skip those then. I sometimes just cut those out of setup.py with `sed` or a patch and then everything works.

**Comment by innovate-invent** [comment]
@dpryan79 Thanks. I use pbr and requirements.txt. I don't know how that affects things.

**Comment by dpryan79** [comment]
@innovate-invent This should be ready to go.

**Comment by innovate-invent** [comment]
Ah, so the answer is you do actually have to copy the requirements.txt into meta.yaml.
Is there a more robust way of doing this? I was hoping the requirements could be pulled from the pip package

**Comment by dpryan79** [comment]
The conda skeleton will pull that from pypi, but it has to all be specified in the standard way.

**Pull request merged**
