### PR TITLE
Update bwakit to 0.7.17.dev1

### PR DESCRIPTION
**Pull request by stekaz**
From https://github.com/bioconda/bioconda-recipes/pull/22785, this PR creates a development version of the BWAKIT recipe, which I have called '0.7.17.dev1'. Basically it just updates BWA to 0.7.17 and unpins samtools 1.3 so we can use a (much) newer samtools. We can look at unpinning the versions of the other dependencies as required.

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by stekaz** [comment]
@BiocondaBot please fetch artifacts

**Comment by stekaz** [comment]
@rhpvorderman looks like I was wrong... conda solver has given us samtools 1.9. I think this is ok though, because it should still allow a newer samtools in the environment. I can give it a bit more of a test tomorrow. If it checks out and you think it looks good, should we ask for this to be merged?

**Comment by rhpvorderman** [comment]
@stekaz Thanks for the amount of work you have put into this. It looks good to me!
As far as I am concerned we can merge this.

**Comment by rhpvorderman** [comment]
> @rhpvorderman looks like I was wrong... conda solver has given us samtools 1.9

```
Python 3.7.3 (default, Dec 20 2019, 18:57:59) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> "1.9" > "1.10"
True
```

Sigh :man_facepalming: . I hate conda!!!

**Comment by rhpvorderman** [comment]
Can we use `samtools >=1.10` as version requirement? That way the biocontainer that will build from this recipe will use the latest version.

**Comment by stekaz** [comment]
Thanks for your investigations into this @rhpvorderman! I'm happy to make that change if needed, but I also think it would be good to get some sort of resolution to #22824 first. Having `conda create -n samtools samtools` provide 1.9 when 1.10 is available does  feel a bit broken.

**Comment by rhpvorderman** [comment]
@stekaz Well then I suggest we merge this now. #22824 might take some time to get resolved. People can always manually update. Thanks to your work it is [very easy](https://github.com/biowdl/docker-bwakit/blob/master/Dockerfile) to build a custom container that includes samtools 1.10 already. In fact I already have made a [bwakit docker image](https://hub.docker.com/r/biowdl/bwakit) for testing.

**Comment by dpryan79** [comment]
Is it vital to merge in this development release? We normally want to avoid end users installing those.

**Comment by rhpvorderman** [comment]
@dpryan79 BWA 0.7.17 is very stable and not a development release.
It is just that upstream hasn't released a new BWA-KIT bundle that contains BWA 0.7.17. Raising an issue upstream did not help https://github.com/lh3/bwa/issues/268.

This is just a measure so people can use the BWA-kit scripts with BWA 0.7.17, which contains important bugfixes that aren't in BWA 0.7.15

**Comment by dpryan79** [comment]
@bioconda-bot please merge

@rhpvorderman That's good enough reason for me :)

**Comment by dpryan79** [comment]
BTW, regarding conda returning old versions, if it's important to have a biocontainer that will definitely contain 1.10 then I would say go ahead and create a new PR restricting the version in this recipe. Mamba, which would solve this issue, has made extremely rapid improvement but I expect it'll still take quite some time before it makes it's way into the internals of conda.

**Comment by rhpvorderman** [comment]
@dpryan79 Thanks for this, and thank you for your ongoing stewardship of bioconda. It is much appreciated!

@stekaz Thank you for all the work in making these bwa-kit recipes work in conda!

**Pull request merged**
