### PR TITLE
trying osx build for intarna v2.0.1

### PR DESCRIPTION
**Pull request by martin-mann**
* [x] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by yhoogstrate** [comment]
It looks like it gets `./configure` instead of `make`. Can you run `./configure ... --vebose`?

**Comment by acaprez** [comment]
Did a quick test in my OS X VM.  The single quotes on lines 11 and 12 of `build.sh` are causing the issue - the values of `$CXXFLAGS` and `$LDFLAGS` are not interpolated (the literal strings are passed instead).  Fixing that, the `LDFLAGS` line needed `-Wl,-rpath ${PREFIX}/lib` added to work around SIP, and boost needed to be added to the run requirements.  Making those changes, it built ok.

**Comment by bgruening** [comment]
@acaprez thanks a lot! Super helpful. I tried to get this in.

**Comment by acaprez** [comment]
@bgruening oops, sorry!  I should have been more specific.  The quotes still need to be there, but as double instead of single.

**Comment by bgruening** [comment]
It looked suspicious to me as well, but who knows how OSX works :)

**Comment by yhoogstrate** [comment]
Thanks all. I see you do very well with os x, maybe time to purchase one?

**Comment by bgruening** [comment]
image

**Comment by martin-mann** [comment]
Finally: many thanks to all of you for getting this done!

@bebatut could you please test if you can run `IntaRNA --help` on you OSX system? thanks in advance!

**Comment by bebatut** [comment]
@martin-mann It works!

**Pull request merged**
