### PR TITLE
see https://github.com/bioconda/bioconda-recipes/commit/1c13cf3197afb…

### PR DESCRIPTION
**Pull request by dpryan79**
…9be56808c72348dcabb199cabba#commitcomment-36723002

Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it.

* [ ] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [ ] This PR adds a new recipe.
* [ ] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

 * `@BiocondaBot please update` will cause the BiocondaBot to merge the master branch into a PR
 * `@BiocondaBot please add label` will add the `please review & merge` label.
 * `@BiocondaBot please fetch artifacts` will post links to packages and docker containers built by the CI system. You can use this to test packages locally before merging.

For members of the Bioconda project, the following command is also available:

 * `@BiocondaBot please merge` will cause packages/containers to be uploaded and a PR merged. Someone must approve a PR first! This has the benefit of not wasting CI build time required by manually merging PRs.

If you have questions, please post them in gitter or ping `@bioconda/core` in a comment (if you are not able to directly ping `@bioconda/core` then the bot will repost your comment and enable pinging).

### CODE REVIEW

**Comment by dpryan79** [comment]
Ping @Avsecz

**Comment by dpryan79** [comment]
This will fail linting, since I'm not rebuilding the package, so I'll forcibly merge as an admin and then remove the 0.1.5 builds from the conda cloud.

**Comment by dpryan79** [comment]
Actually, I'll bump the build number so we get python 3.6 and 3.7 builds :)

**Comment by dpryan79** [comment]
Oh, build 2 was never actually uploaded, so this should produce a package already.

**Comment by dpryan79** [comment]
Ah, the c code needs to be deleted to cython reruns.

**Comment by dpryan79** [comment]
@bioconda-bot please update

**Comment by dpryan79** [comment]
Hopefully https://github.com/bioconda/bioconda-recipes/pull/19612 will fix this

**Comment by dpryan79** [comment]
@bioconda-bot please update

**Comment by mbargull** [comment]
@bioconda-bot please update

**Comment by dpryan79** [comment]
@bioconda-bot please fetch artifacts

**Comment by dpryan79** [comment]
@Avsecz I've marked the 0.1.5 release as broken so it can't be installed by anyone without jumping over some very high hurdles.

**Comment by Avsecz** [comment]
Perfect! Thanks!

If someone types in `conda install genonelake -c bioconda`, then 0.1.4 version will be installed, or?

**Comment by dpryan79** [comment]
Unless something in their environment conflicts with that version then yes.

**Pull request merged**
