### PR TITLE
Pin ncurses version with our new pinning mechanism.

### PR DESCRIPTION
**Pull request by johanneskoester**
* [x] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

Define an ncurses version to use and update recipes by pinning ncurses to that version.
@bioconda/core I am unsure if we need to do something like this for all shared library dependencies...
Any comments?

### CODE REVIEW

**Comment by bgruening** [comment]
:+1:

**Comment by bgruening** [comment]
Thanks Johannes!

**Comment by daler** [comment]
Seems like it's easy enough to add a new env var and `sed` recipes if/when any other dependencies become problematic rather than preemptively changing them all over now.

Probably a dumb question, but what are some examples of other shared lib dependencies?

**Comment by bgruening** [comment]
zlib, libxml?, libpng?

**Pull request merged**
