### PR TITLE
Update samtools to 1.16.1

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`samtools`](https://bioconda.github.io/recipes/samtools/README.html): **1.15.1** &rarr; **1.16.1**

[install with bioconda](http://bioconda.github.io/recipes/samtools/README.html) [Conda](https://anaconda.org/bioconda/samtools/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/samtools`](https://github.com//bioconda/bioconda-recipes/tree/bump/samtools/recipes/samtools) (click to view/edit other files)
Summary | Tools for dealing with SAM, BAM and CRAM files
Home | [https://github.com/samtools/samtools](https://github.com/samtools/samtools)
Releases |[https://github.com/samtools/samtools/releases](https://github.com/samtools/samtools/releases)
Author | `@samtools`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by jmarshall** [comment]
This will need to wait for a **bioconda-utils** update that pins htslib at 1.16.

**Comment by jmarshall** [comment]
Note that this pinning migration is still in progress, so the options for samtools 1.16.1 are still to wait for **bulk** to land, or perhaps to apply this PR's changes on the **bulk** branch so as to deploy a 1.16.1 package now.

**Comment by jmarshall** [comment]
@BiocondaBot please fetch artifacts

**Review by jmarshall — APPROVED** [review]

**Comment by jmarshall** [comment]
@BiocondaBot please merge

**Comment by dpryan79** [comment]
@BiocondaBot please merge or I shall have to alter your code

**Comment by dpryan79** [comment]
Ah, for some reason the source code sometimes gets picked up as a package. I've never figured out why that randomly happens. We can just merge and have the regular uploader handle this.

**Pull request merged**
