### PR TITLE
simka-1.5.0

### PR DESCRIPTION
**Pull request by lecorguille**
Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it. Note that if you are not already a member of the bioconda project (meaning that you can't add this label), please ping `@bioconda/core` so that your PR can be reviewed and merged (please note if you'd like to be added to the bioconda project). Please see https://github.com/bioconda/bioconda-recipes/issues/15332 for more details.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by lecorguille** [comment]
@bioconda/osx 
Is any body have an idea?
Thanks by advance

**Comment by dpryan79** [comment]
@lecorguille simka isn't written using standard C++, but instead uses the TR1 draft spec. The easiest resolution is to change `tr1/unordered_map` to `unordered_map`, since this is now included in C++11 (or so I've read).

**Comment by lecorguille** [comment]
Hum, I'm really a good novice in C*

[Graph.hpp](https://github.com/GATB/gatb-core/blob/d9cc541e2be352dab5d5382eb87738510474fdec/gatb-core/src/gatb/debruijn/impl/Graph.hpp#L33-L39)
```
#ifdef USE_NEW_CXX
#include <unordered_map>
#define NS_TR1_PREFIX std
#else
#include <tr1/unordered_map>
#define NS_TR1_PREFIX std::tr1
#endif
```

What I see is that to enable USE_NEW_CXX, you need at least CXX > 4.3 or we are using a 4.0.1.
[CMakeLists.txt](https://github.com/GATB/gatb-core/blob/d9cc541e2be352dab5d5382eb87738510474fdec/gatb-core/CMakeLists.txt#L79-L97)
```
elseif (CMAKE_CXX_COMPILER_ID STREQUAL "Clang")

   IF(CMAKE_SYSTEM_NAME MATCHES "(Darwin)") # different clang versions number between linux and mac
        if (CMAKE_CXX_COMPILER_VERSION  VERSION_LESS 4.3) 
            set (use_mphf 0)
        else()
            set (use_mphf 1)
            set (use_new_cxx 1)
        endif()

    else()
        if (CMAKE_CXX_COMPILER_VERSION  VERSION_LESS 3.2) 
            set (use_mphf 0)
        else()
            set (use_new_cxx 1)
            set (use_mphf 1)
        endif()

    endif()
```

**Comment by dpryan79** [comment]
I think we're using 4.0.1 at the moment, since that's what conda-forge has been using.

**Comment by dpryan79** [comment]
I'm not entirely sure the python scripts will actually work since they're not installed as actual python packages and don't seem to use relative imports.

**Comment by dpryan79** [comment]
@lecorguille Anyway, this recipe is probably ready for further attention now. It compiles everywhere and someone should probably test that the python scripts actually work.

**Comment by lecorguille** [comment]
@dpryan79 
I have a user here who wait for this package.
She will test that soon.
As usual, thanks a bunch for your time and your precious expertise!

**Pull request merged**
