### PR TITLE
Add recipe for trimal version 1.4.1

### PR DESCRIPTION
**Pull request by gregvonkuster**
* [x] I have read the guidelines above.
* [x] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by gregvonkuster** [comment]
@bgruening I guess I'm still learning to read travis errors logs - I'm not quite sure why this is failing the tests.  :(  This https://travis-ci.org/bioconda/bioconda-recipes/builds/173943934 shows 1 build failing, but I'm not quite sure how to deal with the following error.  Or perhaps I'm not seeing the actual error in the log?  Can you advise when you get a chance?
```
ERROR bioconda_utils.build:build(112): COMMAND: ['docker', 'run', '--net', 'host', '-v', '/tmp/tmp70xa56v5/build_script.bash:/opt/build_script.bash', '-v', '/anaconda/conda-bld:/opt/host-conda-bld', '-v', '/home/travis/build/bioconda/bioconda-recipes/recipes/vsearch:/opt/recipe', '-e', 'CONDA_NPY=110', '-e', 'CONDA_GSL=1.16', '-e', 'CONDA_PERL=5.22.0', '-e', 'CONDA_R=3.3.1', '-e', 'CONDA_BOOST=1.60', '-e', 'CONDA_GMP=5.1', '-e', 'CONDA_NCURSES=5.9', '-e', 'CONDA_PY=27', 'tmp-bioconda-builder', '/bin/bash', '/opt/build_script.bash']

ERROR bioconda_utils.build:build(113): STDOUT+STDERR: bash: cannot set terminal process group (-1): Inappropriate ioctl for device

bash: no job control in this shell
```

**Comment by bgruening** [comment]
You can ignore this one, it is from the container, not your package. The error is here:
https://travis-ci.org/bioconda/bioconda-recipes/jobs/173943937#L522

And this is a known one which we fixed last week.
@johanneskoester @daler the channel priorities are again mixed up. At least bioconda is not getting priority during install of autoconf.

**Comment by gregvonkuster** [comment]
ok, thanks @bgruening !!

**Comment by daler** [comment]
According to https://travis-ci.org/bioconda/bioconda-recipes/jobs/173943937#L426, the channels are what we intended. Maybe there's some dependency resolution that only can be solved by using conda-forge?

**Comment by gregvonkuster** [comment]
Is there something I need to change in the recipe to get the travis build to work on this one?

**Comment by johanneskoester** [comment]
Can you sync with master? I think the mysql problem was fixed in the master branch (by blacklisting for now).

**Comment by gregvonkuster** [comment]
Will open a new PR, thanks.

**Pull request closed without merging**
