### PR TITLE
Update Pandaseq to 2.11 and enable linux build

### PR DESCRIPTION
**Pull request by mdehollander**
* [x] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by mdehollander** [comment]
The travis build from my own fork works: https://travis-ci.org/mdehollander/bioconda-recipes/builds/208279196 but the bioconda one failes. Has this something to do with linting? How to proceed?

**Comment by daler** [comment]
Looks like there's a hard-coded path for perl that needs to be fixed. @druvus I think you had run into this a while ago, any suggestions?

**Comment by mdehollander** [comment]
I noticed that as well and added perl to the build requirements, so basically renamed perl-threaded to perl as suggested on the linting page. But now perl still cannot be found. It looks like the perl package is going to be installed after autogen.sh is run?
This is the relevant output:
```
`./autogen.sh: /opt/conda/conda-`.../bin/autoreconf: /usr/bin/perl: bad interpreter: No such file or directory

WARNING: conda-build appears to be out of date. You have version 2.0.7 but the
latest version is 2.1.5. Run

conda update -n root conda-build

to get the latest version.

BUILD START: pandaseq-2.11-0
updating index in: /opt/conda/conda-bld/linux-64
updating index in: /opt/conda/conda-bld/noarch

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    gmp-6.1.0                  |                0         593 KB  defaults
    libtool-2.4.2              |                0         547 KB  defaults
    m4-1.4.17                  |                0         294 KB  bioconda
    perl-5.22.0.1              |                0        15.1 MB  conda-forge
    zlib-1.2.8                 |                3         101 KB  defaults
    autoconf-2.69              |                0         641 KB  defaults
    isl-0.12.2                 |                0         1.1 MB  defaults
    mpfr-3.1.5                 |                0         419 KB  defaults
    pkg-config-0.28            |                1         227 KB  defaults
    automake-1.15              |                0         572 KB  defaults
    cloog-0.18.0               |                0         617 KB  defaults
    mpc-1.0.3                  |                0          61 KB  defaults
    gcc-4.8.5                  |                7        66.6 MB  defaults
    ------------------------------------------------------------
                                           Total:        86.8 MB

The following NEW packages will be INSTALLED:

    autoconf:   2.69-0     defaults   
    automake:   1.15-0     defaults   
    cloog:      0.18.0-0   defaults   
    gcc:        4.8.5-7    defaults   
    gmp:        6.1.0-0    defaults   
    isl:        0.12.2-0   defaults   
    libtool:    2.4.2-0    defaults   
    m4:         1.4.17-0   bioconda   
    mpc:        1.0.3-0    defaults   
    mpfr:       3.1.5-0    defaults   
    perl:       5.22.0.1-0 conda-forge
    pkg-config: 0.28-1     defaults   
    zlib:       1.2.8-3    defaults   
```

**Comment by acaprez** [comment]
The issue is that the perl programs in the `autoconf` and `automake` packages from `defaults` have `/usr/bin/perl` hardcoded in them.  There are patched versions in `conda-forge` that use `/usr/bin/env perl` instead, but you have to include the version specifier in the `meta.yaml` to use them instead.  See for example [the meta.yaml here](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/beagle-lib/meta.yaml).

**Comment by druvus** [comment]
You could also use the ´sed´ solution that is used in ´exparna´ and some other recipes. 

I could look into this recipe again if the suggestions doesn't fix the issues.

**Comment by mdehollander** [comment]
I am now several steps further (automake is working, bzip2 is added, libtools was needed for running), but now I have a failing test where the package seems to be build ok. The error I get is:
```
+ /bin/bash -x -e /opt/conda/conda-bld/test_tmp/run_test.sh
+ pandaseq -v
pandaseq 2.11 <andre@masella.name>

....
The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    libgcc-5.2.0               |                0         1.1 MB  defaults
    pandaseq-2.11              |                1         680 KB  local
    ------------------------------------------------------------
                                           Total:         1.7 MB

The following NEW packages will be INSTALLED:

    libgcc:   5.2.0-0 defaults
    libtool:  2.4.2-0 defaults
    pandaseq: 2.11-1  local   

TESTS FAILED: pandaseq-2.11-1
```

So pandaseq runs well, only the test is not checked well. I thought this was because the output was send to stderr, but even when I correct for that it doesn't work. Although I don't see `2>&1 > /dev/null` in the travis log. Seems I am almost there, who has an idea for the final test command?

**Comment by daler** [comment]
So close! :)

A lot of tools give nonzero exit codes, so you probably need something like this for the test (if pandaseq -v exits 127):

```bash
pandaseq -v || [ "$?" == 127 ]
```

**Comment by druvus** [comment]
Great work! 

Just remember next time to not bump build number for new versions.

**Comment by mdehollander** [comment]
Indeed, I forgot the put the build number back to zero. I did this because it was advised to trigger the build process related to the linting issues. I will remember this next time.

**Pull request merged**
