### PR TITLE
Recipe for Jaffa v1.08

### PR DESCRIPTION
**Pull request by holtgrewe**
* [x] I have read the guidelines above.
* [x] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by holtgrewe** [comment]
This v1.08 appears to only work in direct mode. Assembly and hybrid appear to be broken. I'll ask the JAFFA authors about this.

**Comment by holtgrewe** [comment]
cf. Oshlack/JAFFA#27

**Comment by bgruening** [comment]
Is this still WIP?

**Comment by holtgrewe** [comment]
Yup, this is pending on Oshlack/JAFFA#27

**Comment by holtgrewe** [comment]
@bgruening master broken after merging because of

```
Runtime error: Could not open '/anaconda/pkgs/openjdk-8.0.112-zulu8.19.0.1_2.tar.bz2.part' for writing (HTTPSConnectionPool(host='binstar-cio-packages-prod.s3.amazonaws.com', port=443): Read timed out.).
```

What's up with that?

**Pull request merged**
