### PR TITLE
update nanopolish to v0.12.2

### PR DESCRIPTION
**Pull request by jts**
This PR updates nanopolish to v0.12.2, the latest release
----

> Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it.

* [ ] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [ ] This PR adds a new recipe.
* [ ] AFAIK, this recipe **is directly relevant to the biological sciences**
      (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

> Everyone has access to the following BiocondaBot commands, which can be given in a comment:
>
>  * `@BiocondaBot please update` will cause the BiocondaBot to merge the master branch into a PR
>  * `@BiocondaBot please add label` will add the `please review & merge` label.
>  * `@BiocondaBot please fetch artifacts` will post links to packages and docker containers built by the CI system. You can use this to test packages locally before merging.
>
> For members of the Bioconda project, the following command is also available:
>
>  * `@BiocondaBot please merge` will cause packages/containers to be uploaded and a PR merged. Someone must approve a PR first! This has the benefit of not wasting CI build time required by manually merging PRs.
>
> If you have questions, please post them in gitter or ping `@bioconda/core` in a comment (if you are not able to directly ping `@bioconda/core` then the bot will repost your comment and enable pinging).

### CODE REVIEW

**Comment by jts** [comment]
Hi @dpryan79,

Can we get your help with this? I tried to bump the version but it doesn't pass the tests and I'm not sure why. Since you updated the yaml for 0.12.0 I thought you might be able to quickly diagnose what is wrong.

Jared

**Comment by dpryan79** [comment]
I get the feeling that something has happened recently on circleci and that we now have a lot less memory available. We can try to skip the testing and test this locally.

**Comment by dpryan79** [comment]
@bioconda-bot please fetch artifacts

**Comment by dpryan79** [comment]
OK, this segfaults locally for me too.

**Comment by jts** [comment]
Damn. Can you grab a stacktrace? It works from source from me but its not impossible I've badly messed something up.

**Comment by dpryan79** [comment]
```Program received signal SIGSEGV, Segmentation fault.
0x000000000000e660 in ?? ()
(gdb) bt
#0  0x000000000000e660 in ?? ()
#1  0x0000555555674c7d in __libc_csu_init ()
#2  0x00007ffff6bdbb28 in __libc_start_main (main=0x5555555620b0 <main>, argc=2, argv=0x7fffffffdd18, init=0x555555674c30 <__libc_csu_init>, 
    fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffdd08) at ../csu/libc-start.c:266
#3  0x0000555555564597 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_S_copy (__n=0, 
    __s=0x7fffffffdd18 "\333\340\377\377\377\177", __d=0x7900000000 <error: Cannot access memory at address 0x7900000000>)
#4  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_S_copy_chars (__k2=<optimized out>, 
    __k1=0x7fffffffdd18 "\333\340\377\377\377\177", __p=0x7900000000 <error: Cannot access memory at address 0x7900000000>)
    at src/nanopolish_call_methylation.cpp:387
#5  _start () at src/nanopolish_call_methylation.cpp:225
#6  0x00007fffffffdd08 in ?? ()
#7  0x000000000000001c in ?? ()
#8  0x0000000000000002 in ?? ()
#9  0x00007fffffffe0db in ?? ()
#10 0x00007fffffffe112 in ?? ()
#11 0x0000000000000000 in ?? ()

**Comment by dpryan79** [comment]
```
Program received signal SIGSEGV, Segmentation fault.
0x000000000000e660 in ?? ()
(gdb) bt
#0  0x000000000000e660 in ?? ()
#1  0x0000555555674c7d in __libc_csu_init ()
#2  0x00007ffff6bdbb28 in __libc_start_main (main=0x5555555620b0 <main>, argc=2, argv=0x7fffffffdd18, init=0x555555674c30 <__libc_csu_init>, 
    fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffdd08) at ../csu/libc-start.c:266
#3  0x0000555555564597 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_S_copy (__n=0, 
    __s=0x7fffffffdd18 "\333\340\377\377\377\177", __d=0x7900000000 <error: Cannot access memory at address 0x7900000000>)
#4  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_S_copy_chars (__k2=<optimized out>, 
    __k1=0x7fffffffdd18 "\333\340\377\377\377\177", __p=0x7900000000 <error: Cannot access memory at address 0x7900000000>)
    at src/nanopolish_call_methylation.cpp:387
#5  _start () at src/nanopolish_call_methylation.cpp:225
#6  0x00007fffffffdd08 in ?? ()
#7  0x000000000000001c in ?? ()
#8  0x0000000000000002 in ?? ()
#9  0x00007fffffffe0db in ?? ()
#10 0x00007fffffffe112 in ?? ()
#11 0x0000000000000000 in ?? ()
```

**Comment by jts** [comment]
Hmm, what is going on there. `nanopolish --help` shouldn't be in that function...

**Comment by dpryan79** [comment]
Unfortunately I'm more of a C person than a C++ person :(

**Comment by dpryan79** [comment]
If it helps, `gdb --args nanopolish --version` produces the same stack trace.

**Comment by jts** [comment]
Can you just run `nanopolish` without arguments? Does it still segfault?

All it should do is print a usage message then exit:

https://github.com/jts/nanopolish/blob/master/src/main/nanopolish.cpp#L67

**Comment by dpryan79** [comment]
Without arguments I get a segfault with the same stack trace. BTW, you can `conda create -n wtf -c https://99093-42372094-gh.circle-artifacts.com/0/tmp/artifacts/packages -c conda-corge -c bioconda nanopolish` to create an env with this package in it. I disabled the tests specifically so we could see what's going on in the resulting binary.

Could it be that someone a different `main()` is getting used?

**Comment by jts** [comment]
Thanks for the tip, trying that now.

**Comment by jts** [comment]
I'm able to reproduce this locally now too. I don't know if this is the problem but I think this should be `MINIMAP2=noinstall` instead of `MINIMAP=noinstall`:

https://github.com/bioconda/bioconda-recipes/blob/master/recipes/nanopolish/build.sh#L16

**Comment by dpryan79** [comment]
certainly worth a shot. If you change that then maybe also inject `-g` everywhere as a compiler flag.

**Comment by jts** [comment]
Ah, minimap2 needs to be compiled as a submodule, since we use a private header (`bseq.h`)

**Comment by jts** [comment]
When I tried to build the package using `conda debug` I got link errors because the unpinned htslib was too recent. After I pinned the version it works in `conda debug`, still not working here though.

**Comment by jts** [comment]
Latest attempt tries to clean up how minimap2 is built

**Comment by jts** [comment]
I inserted a call to `./nanopolish` into build.sh and on the build server it runs without a segfault:

```
00:12:30 BIOCONDA INFO (OUT) error: no command provided
00:12:30 BIOCONDA INFO (OUT) usage: nanopolish [command] [options]
00:12:30 BIOCONDA INFO (OUT)   valid commands:
00:12:30 BIOCONDA INFO (OUT)     --help
00:12:30 BIOCONDA INFO (OUT)     --version
00:12:30 BIOCONDA INFO (OUT)     call-methylation
00:12:30 BIOCONDA INFO (OUT)     eventalign
00:12:30 BIOCONDA INFO (OUT)     extract
00:12:30 BIOCONDA INFO (OUT)     getmodel
00:12:30 BIOCONDA INFO (OUT)     help
00:12:30 BIOCONDA INFO (OUT)     index
00:12:30 BIOCONDA INFO (OUT)     methyltrain
00:12:30 BIOCONDA INFO (OUT)     phase-reads
00:12:30 BIOCONDA INFO (OUT)     polya
00:12:30 BIOCONDA INFO (OUT)     scorereads
00:12:30 BIOCONDA INFO (OUT)     variants
00:12:30 BIOCONDA INFO (OUT)     vcf2fasta
00:12:30 BIOCONDA INFO (OUT)   for help on given command, type nanopolish command --help
```

I don't know exactly what this means - architecture mismatch or does the binary get changed somehow during packaging?

**Comment by dpryan79** [comment]
It looks like it's somehow linking against the htslib submodule rather than the package you install.

**Comment by jts** [comment]
Fixed. Re-submitted as clean PR

**Pull request closed without merging**
