### PR TITLE
Update MMseqs2 release to 9-d36de

### PR DESCRIPTION
**Pull request by martin-steinegger**
:information_source:
If this is your first pull request to Bioconda please ping `@bioconda/core` so it can be reviewed and to request being added as a member of the Bioconda team. Members of the Bioconda team are able to merge their own pull requests once tests and linting have passed.

----------------

* [ x ] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ x ] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ x ] This PR updates an existing recipe.

### CODE REVIEW

**Comment by npavlovikj** [comment]
This is not the reason for the error, but the build number should be 0 since it is new version.

**Comment by martin-steinegger** [comment]
@npavlovikj thank you for checking the release. I have adjusted the build number.

**Comment by npavlovikj** [comment]
Glad to see you have fixed the recipe @martin-steinegger . Do you have permissions to merge it, or want me to do it?

**Comment by epruesse** [comment]
I'll do it.

@biocondabot merge

**Pull request merged**
