### PR TITLE
Import smallgenomeutilities 0.1

### PR DESCRIPTION
**Pull request by SoapZA**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by SoapZA** [comment]
@bgruening @johanneskoester 
Any ideas what this conflict is about? I'm not explicitly requesting py3.6. What's the plan with enabling 3.6 for bioconda anyways?
```
The following specifications were found to be in conflict:
  - numpy 1.10*
  - python 3.6*
```

**Comment by bgruening** [comment]
@SoapZA 3.6 is enabled and this just happens because we build against 3.6 already. The error message is confusing but this is a known bug of conda-build there is one other dependency that is not yet available for 3.6 in your dependencies ...
@johanneskoester has done the migration to 3.6. for all packages soon, so either you wait a little bit or try to find this one dependency which is not yet available for 3.6.

**Comment by johanneskoester** [comment]
Python 3.6 migration is almost finished (one or two packages missing). The problem you see here is cause by the numpy pinning in master, which is still 1.10 (and numpy 1.10 is not available for python 3.6). I plan to merge the migration branch into master today. This should solve your problem.

**Comment by SoapZA** [comment]
Thanks guys for the dedicated effort 👍 , I will just wait and fix my other PRs in the mean time

**Comment by johanneskoester** [comment]
You're welcome ;-)! You should be able to go on after PR #4888 is merged.

**Pull request merged**
