### PR TITLE
samtools 0.1.19 requires ncurses

### PR DESCRIPTION
**Pull request by necrolyte2**
This was on Arch Linux
```
samtools: error while loading shared libraries: libncurses.so.5: cannot open shared object file: No such file or directory
```

Manually installing ncurses fixed the issue

### CODE REVIEW

**Comment by johanneskoester** [comment]
Thanks! Can you also add zlib (also as build dependency)?

**Comment by bgruening** [comment]
Great!

**Comment by johanneskoester** [comment]
Looks like the build number has not been increased, such that the package is not being rebuild.

**Comment by necrolyte2** [comment]
Ahh, yes. I'll fix that Monday

**Pull request merged**
