### PR TITLE
Fix version support for Python2.7

### PR DESCRIPTION
**Pull request by prihoda**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

Fix for #14007

@dpryan79 Can you please take a look at this fix for the DeepBGC module? It turns out the original python version specification was correct, specifying `python >=2.7, >3` will only accept version `>3`. 

Is it possible to fix this for version 0.1.3 or do we have to do a new version? 

Thanks!

### CODE REVIEW

**Comment by dpryan79** [comment]
It was `>=3`, I assume you just wanted python 3. We don't build for 3.1 through 3.5, so there's no need to specify that.

**Comment by dpryan79** [comment]
BTW, if you need to allow python2 as well, just don't specify any versions and increment the build number by one.

**Comment by prihoda** [comment]
AFAIK Before I specified "python>=2.7,>=3". Could it have been automatically changed to ">=3"? Since ">=2.7,>=3" apparently applies both conditions which just translates to ">=3".

**Comment by dpryan79** [comment]
That would have been my guess, yes.

**Pull request merged**
