### PR TITLE
Update to TIDDIT 2.12.2

### PR DESCRIPTION
**Pull request by J35P312**
Update to TIDDIT 2.12.2
----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by dpryan79** [comment]
@bioconda-bot please fetch artifacts

**Comment by dpryan79** [comment]
I've added the missing compiler. Please have a look at the compilation error.

**Comment by J35P312** [comment]
Hello!
And thanks for helping!
I have had a look at the compile error message, there seems to be some issue with compiling the bamtools library:

08:21:49 BIOCONDA INFO (OUT) /opt/conda/conda-bld/tiddit_1648369137305/work/lib/bamtools/src/api/internal/bam/BamMultiMerger_p.h:130:18:   required from 'void BamTools::Internal::MultiMerger<Compare>::Add(BamTools::Internal::MergeItem) [with Compare = BamTools::Algorithms::Sort::ByName]'
08:21:49 BIOCONDA INFO (OUT) /opt/conda/conda-bld/tiddit_1648369137305/work/lib/bamtools/src/api/internal/bam/BamMultiMerger_p.h:123:13:   required from here
08:21:49 BIOCONDA INFO (OUT) /opt/conda/conda-bld/tiddit_1648369137305/_build_env/x86_64-conda-linux-gnu/include/c++/10.3.0/bits/stl_tree.h:780:8: error: static assertion failed: comparison object must be invocable as const

This could be fixed by using an older GCC compiler (https://github.com/pezmaster31/bamtools/issues/213).
locally, I use 8. something, then it works nicely.
Would it be possible to specify an older compiler? 
Alternatively I could do some quick fix to the bamtools api, or maybe skip compiling the BamMultiMerger, TIDDIT does not use it anyway.

**Comment by dpryan79** [comment]
We can't use older compilers since the binaries can require different stdc++ versions then and they're incompatible with everything else we build currently. Please try to either patch around the API or skip that part of bamtools.

**Comment by J35P312** [comment]
Hello!
Sorry for not replying! I have recently updated tiddit to use pysam instead of bamtools api!
I will come back with a pull request for version 3.0.0 later!

**Pull request closed without merging**
