### PR TITLE
Update cptac to 1.1.1

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`cptac`](https://bioconda.github.io/recipes/cptac/README.html): **1.1.0** &rarr; **1.1.1**

[install with bioconda](http://bioconda.github.io/recipes/cptac/README.html) [Conda](https://anaconda.org/bioconda/cptac/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/cptac`](https://github.com//bioconda/bioconda-recipes/tree/bump/cptac/recipes/cptac) (click to view/edit other files)
Summary | Python packaging for CPTAC data
Home | [https://pypi.org/project/cptac/](https://pypi.org/project/cptac/)
Releases |[https://pypi.org/pypi/cptac/json](https://pypi.org/pypi/cptac/json)
Recipe Maintainer(s) | @old-rob

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by old-rob** [comment]
It's awesome that the recipe now automatically updates
I will no longer be maintaining this package and would like to know how to transfer responsibility.
@andrewbonnett will be taking over, is there an easy way to edit the recipe maintainer?

**Comment by cbrueffer** [comment]
You can edit the `meta.yaml` file directly in Github by going to the Files Changed tab, `...` in the right-hand corner and `edit file`.

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
@BiocondaBot please merge

@old-rob please create a PR to change your maintainership

**Comment by alienzj** [comment]
@BiocondaBot please update

**Comment by alienzj** [comment]
@BiocondaBot please merge

**Pull request merged**
