### PR TITLE
Added wigToBigWig as dependency to CrossMap

### PR DESCRIPTION
**Pull request by yhoogstrate**
Hi guys,

I am new to the bioconda community so I hope I am not doing something wrong. When I was testing some of the sub programs of CrossMap I ran a few times into the following error:

`Could not find wigToBigWig executable. Try to download it from "http://hgdownload.cse.ucsc.edu/admin/exe/" and convert wig to bigwig by yourself.`

I figured out that this tool can be installed with bioconda package:
```
ucsc-wigtobigwig          .  324                           0  bioconda  
```

However, I saw that the recipes of the ucsc tools has been removed (https://github.com/bioconda/bioconda-recipes/pull/904/commits/7b6e7801704f10f1cc614f4b737efad9f3c8beec). I don't know all details of the conda system but in case this means the package is not being maintained anymore I think we shouldn't accept this.

All best,

Youri

### CODE REVIEW

**Comment by bgruening** [comment]
@johanneskoester any reason the ucsc-tool was removed?
@yhoogstrate can you increase the version number? And merge the default branch in yours?

Also please have a look at: https://github.com/bioconda/bioconda-recipes/issues/1

**Comment by johanneskoester** [comment]
I once tried to add a lot of them at once, and it exceeded the build time limit. Then, I started to add them piece by piece. However, I did not have the time to finish this so far. It might be that I accidentally deleted a recipe of an already uploaded ucsc package.

**Comment by yhoogstrate** [comment]
@johanneskoester if i add the one for wigToBigwig and the test passes, we're ok?

**Comment by johanneskoester** [comment]
Sure. There is a script to generate ucsc recipes in the scripts directory.

**Comment by yhoogstrate** [comment]
In case you want some more ucsc tools, I scripted them into separate branches: https://github.com/bioconda/bioconda-recipes/compare/master...yhoogstrate:ucsc_bigwigaverageoverbed?expand=1

**Comment by johanneskoester** [comment]
Nice! Feel free to create pull requests for them! We will be happy to merge them gradually!

**Pull request merged**
