### PR TITLE
Update/fix kb (remove kallisto and bustools dependencies)

### PR DESCRIPTION
**Pull request by gennadyFauna**
My [previous PR](https://github.com/bioconda/bioconda-recipes/pull/45808) was incorrect. `kb` typically fails `pip install` with new Python versions, so I expected that this might be a version issue. But there is a more immediate issue: by default, `kb` calls `kallisto` and `bustools` binaries. I traced the binary calls, and they request the `/usr/local/bin/` versions, which are incorrect – instead, the pre-packaged binaries at `/usr/local/lib/python3.10/site-packages/kb_python/bins/linux/` should be used. therefore, I removed these tools from requirements.

For reference, see the [kb_python GitHub repo](https://github.com/pachterlab/kb_python?tab=readme-ov-file#installation) and the list of [requirements](https://github.com/pachterlab/kb_python/blob/master/requirements.txt). 

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

### General instructions

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

### Instructions for avoiding API, ABI, and CLI breakage issues
Conda is able to record and lock (a.k.a. pin) dependency versions used at build time of other recipes.
This way, one can avoid that expectations of a downstream recipe with regards to API, ABI, or CLI are violated by later changes in the recipe.
If not already present in the meta.yaml, make sure to specify `run_exports` (see [here](https://bioconda.github.io/contributor/linting.html#missing-run-exports) for the rationale and comprehensive explanation).
Add a `run_exports` section like this:

```yaml
build:
  run_exports:
    - ...

```

with `...` being one of:

| Case                             | run_exports statement                                               |
| -------------------------------- | ------------------------------------------------------------------- |
| semantic versioning              | `{{ pin_subpackage("myrecipe", max_pin="x") }}`     |
| semantic versioning (0.x.x)      | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}`   |
| known breakage in minor versions | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| known breakage in patch versions | `{{ pin_subpackage("myrecipe", max_pin="x.x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| calendar versioning              | `{{ pin_subpackage("myrecipe", max_pin=None) }}`    |

while replacing `"myrecipe"` with either `name` if a `name|lower` variable is defined in your recipe or with the lowercase name of the package in quotes.

### Bot commands for PR management

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

Note that the <code>@BiocondaBot please merge</code> command is now depreciated. Please just squash and merge instead.

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by Maarten-vd-Sande** [comment]
It's been a while since I made this recipe, and I am not a developer of kb-python so I don't remember the details anymore. But I don't understand the current solution. Why would removing the dependencies fix anything? Note that the recipe has a config.py.patch, which fixes the path stuff.

Also you've fixed the python version: `python >=3.7, <3.9`, fine by me. However, then you specify: `the pre-packaged binaries at /usr/local/lib/python3.10/site-packages/kb_python/bins/linux/ should be used`. That's python 3.10. 

Anyways, as I don't recall the details anymore, and I have other obligations now, feel free to continue without my consent :smile:

**Comment by gennadyFauna** [comment]
Thank you for following up!

> It's been a while since I made this recipe, and I am not a developer of kb-python so I don't remember the details anymore. But I don't understand the current solution. Why would removing the dependencies fix anything? Note that the recipe has a config.py.patch, which fixes the path stuff.

The standalone kallisto binary is slightly different from the precompiled kallisto binary. Using kb with the former does not work; using kb with the latter does. Kallisto and bustools are not kb dependencies (see the [kb_python GitHub repo](https://github.com/pachterlab/kb_python/blob/master/requirements.txt)).
 
> Also you've fixed the python version: `python >=3.7, <3.9`, fine by me. However, then you specify: `the pre-packaged binaries at /usr/local/lib/python3.10/site-packages/kb_python/bins/linux/ should be used`. That's python 3.10.

I have reverted the Python requirement. Please see more recent commit https://github.com/bioconda/bioconda-recipes/pull/45846/commits/af6ff924420d1e9b52612dcc33aa0556103f1e02. This precise line depends on the environment. I tested it on the vanilla Docker image `0.28.2--pyhdfd78af_0` on Quay, which has Python 3.10. kb-python does work with 3.10. So it seems to be a binary issue instead.

**Comment by gennadyFauna** [comment]
@Maarten-vd-Sande, thank you for bringing my attention to the patch. I have tested `kb ref` and `kb count` with the patch effectively stripped out (i.e., removing the lines injected into `config.py`), and both work fine. `get_provided_kallisto_binary()` works. With the patch, `kb ref` breaks because it calls an unsupported binary.

However, it would be helpful to understand what problem the patch was solving before stripping it out.

**Comment by Maarten-vd-Sande** [comment]
The patchfile and the specification of kallisto and bustools is so that users can install whichever versions they want. It's un-conda-like (if that's a word :P ) to ship binaries of package A while installing package B. What if in an conda environment you specify kb-python, kallisto, and bustools. It's then quite unexpected that kb-python uses a different version of bustools and kallisto then your other tools.

As such I think your current approach of just removing the conda dependencies of kallisto and bustools is not the way forward..  Perhaps a more senior bioconda developer can chip in? tagging @bgruening

**Comment by gennadyFauna** [comment]
@BiocondaBot please fetch artifacts

**Comment by gennadyFauna** [comment]
The preliminary build of version `pyhdfd78af_2` works: `kb ref` and `count` work, using the `standard`, `nac`, and obsolete `lamanno` workflows.

**Comment by bgruening** [comment]
Puh, this all looks very messy. Packages should not ship their own binaries. And its also not good to do path wrangling during runtime. :cry: 

That said, if adding external deps do not work, I guess we need to ship this mess.
@gennadyFauna do you see any hope that this could be improved upstream at any point of time?

I'm not a fan, but would be okay to merge this PR. @Maarten-vd-Sande is that ok for you as well?

**Comment by gennadyFauna** [comment]
Thank you; I appreciate the follow-up. I am not a kb developer, but kb has never had a kallisto dependency (since 2019), so I do not think it will get one any time soon.

**Review by Maarten-vd-Sande — APPROVED** [review]
Ok let's ship it then :smile:

**Comment by gennadyFauna** [comment]
@BiocondaBot please update

**Pull request merged**
