### PR TITLE
Advntr-1.3.1

### PR DESCRIPTION
**Pull request by mehrdadbakhtiari**
Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it. Note that if you are not already a member of the bioconda project (meaning that you can't add this label), please ping `@bioconda/core` so that your PR can be reviewed and merged (please note if you'd like to be added to the bioconda project). Please see https://github.com/bioconda/bioconda-recipes/issues/15332 for more details.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by mehrdadbakhtiari** [comment]
@bioconda/core 
I have included `{{ compiler('cxx') }}` in the build section and it was working for previous versions of the software (I haven't changed this section). This time I get the error `make: g++: Command not found` and my build fails.
I would appreciate any help.

**Comment by dpryan79** [comment]
You've hard-coded the compiler, which isn't named `g++`. I've made a change that should probably resolve that.

**Comment by epruesse** [comment]
Why does this one need cython in `run`?

**Comment by dpryan79** [comment]
It uses a cython import function. I was surprised too.

**Pull request merged**
