### PR TITLE
add tests to Curves+ recipe

### PR DESCRIPTION
**Pull request by svletana**
This PR add some simple tests to the Curves+ recipe

### CODE REVIEW

**Comment by marcelm** [comment]
If you don’t mind, I’ll add a couple of changes. The most important thing is that the upstream source needs to be used directly.

**Comment by marcelm** [comment]
It passes! Is this ready to be merged?

**Review by marcelm — APPROVED** [review]

**Comment by svletana** [comment]
@marcelm yes! thanks for your help with this PR :)

**Comment by svletana** [comment]
@BiocondaBot please merge

**Pull request merged**
