### PR TITLE
trinity: restore missing semicolon

### PR DESCRIPTION
**Pull request by bernt-matthias**
Corrects an error of my previous commit. See
https://github.com/bioconda/bioconda-recipes/pull/16852#issuecomment-520946660

Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it. Note that if you are not already a member of the bioconda project (meaning that you can't add this label), please ping `@bioconda/core` so that your PR can be reviewed and merged (please note if you'd like to be added to the bioconda project). Please see https://github.com/bioconda/bioconda-recipes/issues/15332 for more details.

* [ ] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [ ] This PR adds a new recipe.
* [ ] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by bernt-matthias** [comment]
ping @micknudsen this should fix it. semicolons are now not removed. 

should we increase build version?

A working test would be nice. `--cite` seems not to do the trick.

**Comment by micknudsen** [comment]
Thanks. I definitely think that we should increase build number, otherwise no new package will be uploaded to the bioconda channel, right?

**Comment by micknudsen** [comment]
Catching this kind of error with a test look rather difficult to me. I think you'll need to have some input data and reference data to run STAR-Fusion on.

**Comment by dpryan79** [comment]
I bumped the build number and will merge.

**Comment by bernt-matthias** [comment]
@dpryan79 Thanks. I just manually checked what happens if I remove the semicolons. For me `Trinity --cite` fails then. So I wonder why the tests were successful. Might it be, because there is also a `run_tests.sh`?

**Comment by dpryan79** [comment]
My understanding is that `run_tests.sh` will be run in addition to everything specified, but perhaps that understanding is incorrect :(

**Comment by bernt-matthias** [comment]
Hmm the build (https://circleci.com/gh/bioconda/bioconda-recipes/68741?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link) contains exactly the error message reported by @micknudsen 

```
15:37:54 BIOCONDA INFO (ERR) [Aug 12 15:37:54] SERR Scalar found where operator expected at /usr/local/bin/Trinity line 49, near "$ENV"
15:37:54 BIOCONDA INFO (ERR) [Aug 12 15:37:54] SERR (Missing semicolon on previous line?)
15:37:54 BIOCONDA INFO (ERR) [Aug 12 15:37:54] SERR syntax error at /usr/local/bin/Trinity line 47, near "my "
15:37:54 BIOCONDA INFO (ERR) [Aug 12 15:37:54] SERR Global symbol "$TRIMMOMATIC_DIR" requires explicit package name (did you forget to declare "my $TRIMMOMATIC_DIR"?) at /usr/local/bin/Trinity line 47.
15:37:54 BIOCONDA INFO (ERR) [Aug 12 15:37:54] SERR Global symbol "$TRIMMOMATIC_DIR" requires explicit package name (did you forget to declare "my $TRIMMOMATIC_DIR"?) at /usr/local/bin/Trinity line 190.
15:37:54 BIOCONDA INFO (ERR) [Aug 12 15:37:54] SERR Execution of /usr/local/bin/Trinity aborted due to compilation errors.
```

so there should be an error.

I guess its because how the tests are chained together in a bash

```
15:37:54 BIOCONDA INFO (ERR) [Aug 12 15:37:54] STEP Run image [quay.io/biocontainers/trinity:2.8.5--h8b12597_1] with command [[Trinity --cite && align_and_estimate_abundance.pl --help || [[ "$?" == 255 ]] && abundance_estimates_to_matrix.pl --help || [[ "$?" == 255 ]] && run_DE_analysis.pl -h || [[ "$?" == 255 ]] && analyze_diff_expr.pl -h || [[ "$?" == 255 ]] && PtR --help || [[ "$?" == 255 ]] && TrinityStats.pl 2>&1 | grep "usage:" && define_clusters_by_cutting_tree.pl 2>&1 | grep "define K clusters via k-means algorithm" && Trinity_gene_splice_modeler.py --help]]
```

`Trinity --cite && align_and_estimate_abundance.pl --help || [[ "$?" == 255 ]` is successful even if `Trinity --cite` fails, essentially because `false && false || true ` evaluates to `true` (as well as `false && true || true`, `true && false || true`, `true && true || true`). 

I guess tests need some grouping? Maybe `{...}`? Should this be done automatically by conda or on recipe level?

**Comment by dpryan79** [comment]
I would argue that conda shouldn't `&&` these to prevent this sort of thing. I'll open an issue on conda-build (there's likely a version of this issue reported already, but I can't find it).

**Comment by dpryan79** [comment]
Xref: https://github.com/conda/conda-build/issues/3672

**Pull request merged**
