### PR TITLE
Update rdptools from release 2.0.2 to 2.0.3

### PR DESCRIPTION
**Pull request by mariabernard**
update rdptool from release 2.0.2 to 2.0.3
see : https://github.com/rdpstaff/RDPTools

### CODE REVIEW

**Comment by mariabernard** [comment]
Hello everyone,

This seemed to be a simple update of the recipe rdptools. 
I changed to commit to number that correspond to the release 2.0.3, and update the version.
But the linux tests failed with error that is solved in this release (see : https://github.com/rdpstaff/RDPTools/issues/31 ).
As posted in the rdptools issue, I fixe the java version to 8, but I am not sure it works and I don't how to check.

@bioconda/core, I am out of ideas... could you help?

**Comment by mariabernard** [comment]
@BiocondaBot please add label

**Comment by dpryan79** [comment]
@bioconda-bot please fetch artifacts

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Pull request merged**
