### PR TITLE
Create ntjoin recipe

### PR DESCRIPTION
**Pull request by warrenlr**
**Replace this sentence with a detailed description of your pull request**

----

> Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences**
      (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

> Everyone has access to the following BiocondaBot commands, which can be given in a comment:
>
>  * `@BiocondaBot please update` will cause the BiocondaBot to merge the master branch into a PR
>  * `@BiocondaBot please add label` will add the `please review & merge` label.
>  * `@BiocondaBot please fetch artifacts` will post links to packages and docker containers built by the CI system. You can use this to test packages locally before merging.
>
> For members of the Bioconda project, the following command is also available:
>
>  * `@BiocondaBot please merge` will cause packages/containers to be uploaded and a PR merged. Someone must approve a PR first! This has the benefit of not wasting CI build time required by manually merging PRs.
>
> If you have questions, please post them in gitter or ping `@bioconda/core` in a comment (if you are not able to directly ping `@bioconda/core` then the bot will repost your comment and enable pinging).

### CODE REVIEW

**Comment by dpryan79** [comment]
pymannkendall will need to be added to conda-forge

**Comment by dpryan79** [comment]
pyMannKendall should appear in the next half hour or so.

**Comment by dpryan79** [comment]
@bioconda-bot please fetch artifacts

**Comment by dpryan79** [comment]
Oh, installing this will be weird. We need to `cd src && make` and then presumably copy a binary or two somewhere (maybe $PREFIX/bin, no clue if the location is hard-coded).

**Comment by lcoombe** [comment]
Hi @dpryan79,
If it helps -- the tool is run by launching the Makefile `ntJoin`, which in turn will launch the various steps including the C++ `src/indexlr` and python `bin/ntjoin_assemble.py` code.
So this command prints the help page:
```
ntJoin help
```
It will look for those binaries/scripts relative to where the Makefile is located. It will expect the C++ binaries in `src` and the python scripts in `bin`
Ie. if the Makefile is in `/PREFIX`, then it will look in `/PREFIX/bin` for the python script `ntjoin_assemble.py`.

Thank you for your help in getting ntJoin in bioconda!

**Comment by warrenlr** [comment]
hello @dpryan79, we were wondering if you needed else from us? Let @lcoombe or I know, we appreciate your help with this!
Thank you,
Rene

**Comment by dpryan79** [comment]
If the package as is works properly then we can merge it in, I was just under the impression that it wouldn't.

**Comment by lcoombe** [comment]
@bioconda-bot please fetch artifacts

**Comment by lcoombe** [comment]
@BiocondaBot please add label

**Comment by lcoombe** [comment]
@dpryan79 - I updated the `meta.yaml` file and added a `build.sh` file to get everything installed and in the right places. 
I ended up making a wrapper script in `bin` which will call the Makefile, etc. located in `bin/share/ntjoin-1.0.1-0`.

**Comment by dpryan79** [comment]
@bioconda-bot please merge

Nice work @warrenlr!

**Comment by warrenlr** [comment]
> @bioconda-bot please merge
> 
> Nice work @warrenlr!

it's @lcoombe who deserves all the credit! kudos Lauren!

**Pull request merged**
