### PR TITLE
Update mashtree to 1.0

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`mashtree`](https://bioconda.github.io/recipes/mashtree/README.html): **0.57** &rarr; **1.0**

[install with bioconda](http://bioconda.github.io/recipes/mashtree/README.html) [Conda](https://anaconda.org/bioconda/mashtree/files)

Info | Link
-----|-----
Recipe | [`recipes/mashtree`](https://github.com//bioconda/bioconda-recipes/tree/bump/mashtree/recipes/mashtree) (click to view/edit other files)
Releases |[https://github.com/lskatz/mashtree/tags](https://github.com/lskatz/mashtree/tags)
Author | `@lskatz`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Comment by bgruening** [comment]
@dpryan79 seems that the bot is not tracking review comments.

**Comment by dpryan79** [comment]
Correct, review comments are not regular comments and don't trigger any github actions.

**Comment by dpryan79** [comment]
@bioconda-bot please fetch artifacts

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Pull request merged**
