### PR TITLE
Update genotyphi to 1.8.0

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`genotyphi`](https://bioconda.github.io/recipes/genotyphi/README.html): **1.7.1** &rarr; **1.8.0**

[install with bioconda](http://bioconda.github.io/recipes/genotyphi/README.html) [Conda](https://anaconda.org/bioconda/genotyphi/files)

Info | Link
-----|-----
Recipe | [`recipes/genotyphi`](https://github.com//bioconda/bioconda-recipes/tree/bump/genotyphi/recipes/genotyphi) (click to view/edit other files)
Releases |[https://github.com/katholt/genotyphi/tags](https://github.com/katholt/genotyphi/tags)
Author | `@katholt`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Review by rpetit3 — APPROVED** [review]

**Comment by rpetit3** [comment]
@biocondabot please merge

**Comment by rpetit3** [comment]
@BiocondaBot please merge

**Comment by druvus** [comment]
@BiocondaBot please update

**Comment by druvus** [comment]
@BiocondaBot please fetch artifacts

**Comment by druvus** [comment]
@BiocondaBot please merge

**Pull request closed without merging**
