### PR TITLE
Add scikit-learn dependency to macrel

### PR DESCRIPTION
**Pull request by luispedro**
New version uses scikit-learn instead of r-randomForest, so update to
that.

* [x] This PR updates an existing recipe.

> Everyone has access to the following BiocondaBot commands, which can be given in a comment:
>
>  * `@BiocondaBot please update` will cause the BiocondaBot to merge the master branch into a PR
>  * `@BiocondaBot please add label` will add the `please review & merge` label.
>  * `@BiocondaBot please fetch artifacts` will post links to packages and docker containers built by the CI system. You can use this to test packages locally before merging.
>
> For members of the Bioconda project, the following command is also available:
>

### CODE REVIEW

**Comment by luispedro** [comment]
Original bug report: https://github.com/BigDataBiology/macrel/issues/17

**Comment by luispedro** [comment]
@BiocondaBot please add label

**Comment by dpryan79** [comment]
@bioconda-bot please fetch artifacts

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Pull request merged**
