### PR TITLE
Update crispresso2 to 2.0.28

### PR DESCRIPTION
**Pull request by epruesse**
Update [`crispresso2`](https://bioconda.github.io/recipes/crispresso2/README.html): **2.0.27** &rarr; **2.0.28**

[install with bioconda](http://bioconda.github.io/recipes/crispresso2/README.html) [Conda](https://anaconda.org/bioconda/crispresso2/files)

Info | Link
-----|-----
Recipe | [`recipes/crispresso2`](https://github.com//bioconda/bioconda-recipes/tree/bump/crispresso2/recipes/crispresso2) (click to view/edit other files)
Releases |[https://github.com/pinellolab/CRISPResso2/tags](https://github.com/pinellolab/CRISPResso2/tags)
Author | `@pinellolab`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/updating.html)).

### CODE REVIEW

**Comment by druvus** [comment]
@bioconda-bot rescheck

**Comment by druvus** [comment]
@bioconda-bot recheck

**Comment by epruesse** [comment]
@biocondabot recheck

**Comment by epruesse** [comment]
Curious. Nothing getting build?

**Comment by epruesse** [comment]
@biocondabot merge

**Pull request merged**
