### PR TITLE
Update Gromacs package.

### PR DESCRIPTION
**Pull request by leobiscassi**
* [x] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

This PR adjust gromacs package following the build instructions: [https://github.com/bioconda/bioconda-recipes#managing-multiple-versions-of-a-package](https://github.com/bioconda/bioconda-recipes#managing-multiple-versions-of-a-package)

### CODE REVIEW

**Comment by leobiscassi** [comment]
Hi @bioconda/core, I made only changes in directory structure which the tests in development branch passed, but the tests in master branch not passed in one job, can you trigger the job again? please.

**Comment by leobiscassi** [comment]
Build link: [https://travis-ci.org/bioconda/bioconda-recipes/builds/142949937](https://travis-ci.org/bioconda/bioconda-recipes/builds/142949937)

**Comment by bgruening** [comment]
Triggered :)

**Comment by leobiscassi** [comment]
@bgruening thanks!

**Pull request merged**
