### PR TITLE
Add PICRUSt2

### PR DESCRIPTION
**Pull request by apcamargo**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by apcamargo** [comment]
@gavinmdouglas Are you ok with this recipe?

**Comment by gavinmdouglas** [comment]
Thanks for writing this recipe @apcamargo ! 

Could you please change the test section to be:

```
test:
  source_files:
    - test
  commands:
    - picrust2_pipeline.py -h
    - pytest
```

Thanks again and I'm pretty amazed that this was recipe was produced so quickly after GAPPA was added to bioconda...

**Comment by apcamargo** [comment]
You're welcome!

It seems `mp_pred_out.tsv` and `test_predicted_func.tsv` are not being found. Do you know what's going on?

**Comment by gavinmdouglas** [comment]
Ah I see now - the test scripts were identifying the path to the testfiles based on where the code was located. I can fix this to be compatible with conda with a future release. For now it would be easiest to remove that extra test.

**Comment by apcamargo** [comment]
Ok. I'll revert the test section and merge the recipe. Thanks!

**Comment by gavinmdouglas** [comment]
Hey @apcamargo , after testing the conda install it seems none of the database files or accompanying Rscripts were installed in ```lib/python3.6/site-packages/picrust2``` as I expected. Is there an easy way to specify that certain directories need to be kept as well? Based on my googling it seems like a manifest file could be used.

**Comment by apcamargo** [comment]
I guess there is, but I'm unsure if the database files should be included in the recipe. I'd prefer to include them (and the R scripts) to make it easier for the user to install, but this may be against bioconda's practices.

@bioconda/core what should be done in this situation?

**Comment by dpryan79** [comment]
How big are the files in question? For larger R packages (think all of the big bioconductor annotation packages) we use a trick where the database is installed as a post-link script, that way it's doesn't make a 100+MB tarball that we have to host on anaconda.org. See the following for an example: https://github.com/bioconda/bioconda-recipes/blob/bulk/recipes/bioconductor-txdb.mmusculus.ucsc.mm10.ensgene/post-link.sh

**Comment by gavinmdouglas** [comment]
The additional files are ~150 MB. Ok that's good to know about, thanks.

**Comment by apcamargo** [comment]
@gavinmdouglas I'll be unable to create this PR in the next few weeks (lots of deadlines approaching). How do you think we should proceed? Can you create the PR?

**Pull request merged**
