### PR TITLE
Update hesslab-gambit to 0.5.1

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`hesslab-gambit`](https://bioconda.github.io/recipes/hesslab-gambit/README.html): **0.5.0** &rarr; **0.5.1**

[install with bioconda](http://bioconda.github.io/recipes/hesslab-gambit/README.html) [Conda](https://anaconda.org/bioconda/hesslab-gambit/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/hesslab-gambit`](https://github.com//bioconda/bioconda-recipes/tree/bump/hesslab_gambit/recipes/hesslab-gambit) (click to view/edit other files)
Summary | IMPORTANT: This recipe is out of date. Use "gambit" instead: http://bioconda.github.io/recipes/gambit/README.html
Home | [https://github.com/jlumpe/gambit](https://github.com/jlumpe/gambit)
Releases |[https://github.com/jlumpe/gambit/tags](https://github.com/jlumpe/gambit/tags)
Recipe Maintainer(s) | @jlumpe
Author | `@jlumpe`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by rpetit3** [comment]
_IMPORTANT: This recipe is out of date. Use "gambit" instead:_

Addressing this in https://github.com/bioconda/bioconda-recipes/pull/36569

**Comment by jlumpe** [comment]
@rpetit3 Is this going to be merged? This version was intended to make one last update to the project README and metadata of the `hesslab-gambit` recipe as well.

**Comment by rpetit3** [comment]
Do you want it merged, then ignored for future releases? Otherwise I can close this PR and have it ignored in the future

**Comment by jlumpe** [comment]
Yes, I would like this to be the final release of the `hesslab-gambit` recipe.

**Review by rpetit3 — APPROVED** [review]

**Comment by rpetit3** [comment]
@BiocondaBot please merge

**Pull request merged**
