### PR TITLE
DFAST recipe updated

### PR DESCRIPTION
**Pull request by nigyta**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by dpryan79** [comment]
@nigyta Is it possible to get the source code for the modified last binaries? This recipe would be more portable if we could just compile them.

**Comment by nigyta** [comment]
Dear @dpryan79,

I really appreciate all of your help.
I am sorry, but I am out of my lab for several days, it may take time until I will prepare the files.
I will ask for your help when the files are ready.

I would like to include 2 custom binaries (last and rpsbproc).
rpsbproc is a utility program to parse the result of RPSBlast, but it is not included in the standard Blast package.

I am thinking about two more options.
One is to download required binaries using the "post-link.sh" script after building the software package. Is that possible?
The other option is to give up MacOS package. I confirmed that Linux testing was successful although testing for MacOS failed.

**Comment by dpryan79** [comment]
I don't think we could permit downloading the binaries afterward, since we couldn't ensure they'd work on all systems. Can you make the source code available? We could just compile them then. Otherwise yes, we should just skip OSX.

**Comment by nigyta** [comment]
@dpryan79 Thank you for the quick response.
I see. I'm going to prepare the source codes.

One more question.
Is it possible to download souce codes and modify them to create customized binaries during the build step?

**Comment by dpryan79** [comment]
Yes, generally we just ship patch files for the source code.

**Comment by nigyta** [comment]
@dpryan79 

Could you review and merge this?
After setting binary_relocation option to False, build testing for MacOS succeeded.

* As you recommended, I tried to compile the binary from the source code, but I couldn't do that due to some unexpected errors during compilation.

Thank you again for all your help.

**Comment by dpryan79** [comment]
Thanks  @nigyta

**Pull request merged**
