### PR TITLE
add PHATE recipe

### PR DESCRIPTION
**Pull request by scottgigante**
* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [X] This PR adds a new recipe.
* [X] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).

### CODE REVIEW

**Comment by dpryan79** [comment]
Looks like graphtools will either needed to be added or updated.

**Comment by scottgigante** [comment]
ah, graphtools is on conda-forge. what's best practice here? https://anaconda.org/conda-forge/graphtools

**Comment by npavlovikj** [comment]
Looks like the error is `ModuleNotFoundError: No module named 'matplotlib'`, so I believe `matplotlib` should be added to the `host`/`run` sections.

@scottgigante , as long as you are using packages/dependencies that are in the `conda-forge`, `bioconda` and `defaults` channels, that will work here.

**Comment by dpryan79** [comment]
graphtools was just updated in conda-forge so that should work now.

**Comment by scottgigante** [comment]
Oops! Matplotlib is in now, show be fixed.

**Comment by scottgigante** [comment]
Thanks!

**Pull request merged**
