### PR TITLE
add gsearch v0.0.12

### PR DESCRIPTION
**Pull request by jianshu93**
Describe your pull request here

This PR add the genome search tool called GSearch v0.0.12, which is written in Rust. It is an ultra-fast and scalable microbial genome search program based on MinHash metric and graph-based approximate nearest neighbor search, for microbial search and classification purposes. 

See publication here: Jianshu Zhao, Jean Pierre Both, Luis M. Rodriguez-R and Konstantinos T. Konstantinidis, 2022. GSearch: Ultra-Fast and Scalable Microbial Genome Search by combining Kmer Hashing with Hierarchical Navigable Small World Graphs. bioRxiv 2022:2022.2010.2021.513218. [biorxiv](https://www.biorxiv.org/content/10.1101/2022.10.21.513218v2).

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by jianshu93** [comment]
@BiocondaBot please add label

**Comment by jianshu93** [comment]
@BiocondaBot please fetch artifacts

**Comment by jianshu93** [comment]
Hello Bioconda team,

Everything seems fine after building using the artifacts.

Thanks,

Jianshu

**Comment by jianshu93** [comment]
gsearch has already been added to crate.io (https://crates.io/crates/gsearch) and I also want to add it to the bioconda channel so that there is no need to compile from source, which takes sometime. Please receiver it and allow for merge as soon as possible.

Many Thanks,
Jianshu

**Review by druvus — APPROVED** [review]

**Comment by druvus** [comment]
@BiocondaBot please merge

**Comment by jianshu93** [comment]
Many Thanks！


Jianshu

**Comment by jianshu93** [comment]
Hello Bioconda team,

How long does it take before I can use conda install search -c bioconda?

Thanks,
Jianshu

**Pull request merged**
