### PR TITLE
Update medaka to 1.0.0

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`medaka`](https://bioconda.github.io/recipes/medaka/README.html): **0.12.1** &rarr; **1.0.0**

[install with bioconda](http://bioconda.github.io/recipes/medaka/README.html) [Conda](https://anaconda.org/bioconda/medaka/files)

Info | Link
-----|-----
Recipe | [`recipes/medaka`](https://github.com//bioconda/bioconda-recipes/tree/bump/medaka/recipes/medaka) (click to view/edit other files)
Releases |[https://pypi.org/pypi/medaka/json](https://pypi.org/pypi/medaka/json)
Recipe Maintainer(s) | @cjw85

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by cjw85** [comment]
CI is claiming:
```
18:26:03 BIOCONDA INFO (OUT) Processing $SRC_DIR
18:26:03 BIOCONDA INFO (OUT)   Added file://$SRC_DIR to build tracker '/tmp/pip-req-tracker-a8btj28n'
18:26:03 BIOCONDA INFO (OUT)     Running setup.py (path:$SRC_DIR/setup.py) egg_info for package from file://$SRC_DIR
18:26:03 BIOCONDA INFO (OUT)     Created temporary directory: /tmp/pip-pip-egg-info-lqyl9t1d
18:26:03 BIOCONDA INFO (OUT)     Running command python setup.py egg_info
18:26:03 BIOCONDA INFO (OUT)     Traceback (most recent call last):
18:26:03 BIOCONDA INFO (OUT)       File "<string>", line 1, in <module>
18:26:03 BIOCONDA INFO (OUT)       File "/opt/conda/conda-bld/medaka_1588616520229/work/setup.py", line 99
18:26:03 BIOCONDA INFO (OUT)         def run(self):
18:26:03 BIOCONDA INFO (OUT)         ^
18:26:03 BIOCONDA INFO (OUT)     IndentationError: unexpected indent
18:26:03 BIOCONDA INFO (OUT) ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
which seems to relate to [setup.py](https://github.com/nanoporetech/medaka/blob/master/setup.py#L99), which doesn't obviously contain an indentation error. All our internal CI builds are running fine, so I'm at a loss.

**Comment by bgruening** [comment]
@cjw85 have a look at the build.sh script https://github.com/bioconda/bioconda-recipes/blob/bump/medaka/recipes/medaka/build.sh

You need to revert those hacks if they are not needed anymore.

**Comment by cjw85** [comment]
Interesting, I can see the problem but I can't fathom why this ever worked!

**Comment by cjw85** [comment]
@BiocondaBot please merge

**Pull request merged**
