### PR TITLE
Add gcta v1.93.2beta

### PR DESCRIPTION
**Pull request by simojoe**
Adding gcta v1.93.2beta.

The software is precompiled and distributed as an executable. 
I have include sources for linux and osx.

### CODE REVIEW

**Comment by simojoe** [comment]
@BiocondaBot please add label

**Comment by dpryan79** [comment]
Do you really want to distribute a beta version? By definition those aren't meant for end-users.

**Comment by simojoe** [comment]
All versions of the software since 2017 are [labelled as beta ](https://cnsgenomics.com/software/gcta/#Download). The latest non-beta version is from June 2016. The software was actively developed since then and has seen some major changes. Even thought this is a beta version, I believe it is more suitable than the last non-beta.

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Pull request merged**
