### PR TITLE
Update cd-hit-auxtools

### PR DESCRIPTION
**Pull request by stephanflemming**
Update cd-hit-auxtools to the current version 4.8.1

Project repository can be found here https://github.com/weizhongli/cdhit

### CODE REVIEW

**Comment by stephanflemming** [comment]
@BiocondaBot please add label

**Review by bgruening — APPROVED** [review]

**Comment by stephanflemming** [comment]
@BiocondaBot please merge

**Comment by bgruening** [comment]
@BiocondaBot please add label

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Pull request merged**
