### PR TITLE
GNU licenses like GPL, AGPL, LGPL are not public domain

### PR DESCRIPTION
**Pull request by peterjc**
* [x] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

I've not found any BioConda documentation defining the ``license_family:`` field (see also #1581), but none of the GNU licenses (i.e. any versions of the GPL and LGPL) can be considered as public domain.

It makes sense to me to class any version of the GPL as ``license_family: GPL`` as in this LGPL example:

```
about:
  home: https://pypi.python.org/pypi/xmlbuilder/1.0
  license: LGPL v3
  summary: 'pythonic way to crate xml/(x)html files'
  license_family: LGPL
```

### CODE REVIEW

**Comment by peterjc** [comment]
Does this also need the build number bumped?

**Comment by daler** [comment]
Thanks @peterjc. These need a build number bump in order to trigger a rebuild and re-upload to anaconda.org. The bioconda homepage for each will be updated at least nightly with the master branch of bioconda-recipes, so no build number bump needed for that.

Since these are more than just cosmetic changes to the recipes, build number bump is probably best.

**Comment by peterjc** [comment]
Given the builds fail (and from getting to know BioConda it is not unusual for a previously working recipe to bit-rot due to external changes), is it worth committing this without the build-number bump?

That way the license will be clearer next time someone updates the recipes concerned, but it does not push an update to the Anaconda package right now.

**Comment by daler** [comment]
I agree with your point about the next time it needs to be updated. I rarely confirm the existing license in a recipe is correct when updating it, so these updates are valuable to have. I'd be OK with only changing the licences and not the build numbers.

**Comment by peterjc** [comment]
Travis skipped everything on Linux, but decided to test ``biomaj`` on the Mac, and failed - something unreleated to my change:

```
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1781: ordinal not in range(128)
```

I can reproduce this locally,

```
$ LC_ALL=C python3 -c "print(len(open('README.md').read()))"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1781: ordinal not in range(128)
```

This is due to an ellipse ``…`` on line 52 of their ``README.md`` file, issue logged https://github.com/genouest/biomaj/issues/86

Can I merge this pull request anyway (updating the license metadata)?

**Comment by peterjc** [comment]
The little locale/unicode issue in ``biomaj`` has been fixed upstream, and is not relevant to this pull request anyway.

Can I merge this as it is to update the license metadata ready for next time any of these recipes are worked on?

**Comment by bgruening** [comment]
Thanks Peter!

**Pull request merged**
