### PR TITLE
Added perl-bio-viennangs to bioconda recipes, installs via cpanm

### PR DESCRIPTION
**Pull request by jfallmann**
* [x] I have read the guidelines above.
* [x] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by bgruening** [comment]
`Statistics::R` seems to be missing.

**Comment by jfallmann** [comment]
Finally managed to get simulate-travis.py running,
while building locally works just fine, the travis run ends with:

sudo ./simulate-travis.py --packages recipes/perl-text-wrap --loglevel=debug
+ bioconda-utils build recipes config.yml --docker --loglevel=info --mulled-test --packages recipes/perl-text-wrap --loglevel=debug
INFO bioconda_utils.docker_utils:_pull_image(308): BIOCONDA DOCKER: Pulling docker image condaforge/linux-anvil
DEBUG bioconda_utils.docker_utils:_pull_image(310): BIOCONDA DOCKER: stdout+stderr: Using default tag: latest
Trying to pull repository docker.io/condaforge/linux-anvil ... 
latest: Pulling from docker.io/condaforge/linux-anvil
Digest: sha256:cb49695706568453d2b76eb6160eaec9b65832c49a261b8a0d6c6a800c4e7692
Status: Image is up to date for docker.io/condaforge/linux-anvil:latest

INFO bioconda_utils.docker_utils:_pull_image(314): BIOCONDA DOCKER: Done pulling image
DEBUG bioconda_utils.docker_utils:_build_image(325): BIOCONDA DOCKER: Building image "tmp-bioconda-builder" from /tmp/tmp5tw4c46l
DEBUG bioconda_utils.docker_utils:_build_image(338): Dockerfile:

FROM condaforge/linux-anvil
COPY requirements.txt /tmp/requirements.txt
RUN /opt/conda/bin/conda install --file /tmp/requirements.txt

INFO bioconda_utils.docker_utils:_build_image(354): BIOCONDA DOCKER: Built docker image tag=tmp-bioconda-builder
INFO bioconda_utils.build:build_recipes(213): blacklist: bioconductor-bubbletree, bioconductor-cexor, bioconductor-csaw, bioconductor-dada2, bioconductor-deseq2/1.10.1, bioconductor-dexseq, bioconductor-diffbind, bioconductor-ebseq, bioconductor-genelendatabase/1.6.0, bioconductor-iranges/2.4.6, bioconductor-iranges/2.4.7, bioconductor-limma/3.26.7, bioconductor-limma/3.28.2, bioconductor-limma/3.28.6, bioconductor-minfi, bioconductor-mmdiff, bioconductor-qdnaseq, bioconductor-s4vectors/0.8.7, bioconductor-shortread, bioconductor-summarizedexperiment/1.0.2, bioconductor-systempiper, cap-mirseq, mgkit, mysqlclient, poretools/0.5.0, poretools/0.5.1, r-batchjobs, r-gsalib, r-hdrcde, r-knitr, r-ks, r-mixomics, r-mutoss, r-phonr, r-rainbow, r-readr, r-sartools/1.2.0, r-spp, rsem, triform2, vsearch
DEBUG bioconda_utils.utils:get_recipes(245): get_recipes(recipes, package='['recipes/perl-text-wrap']'): recipes/perl-text-wrap
INFO bioconda_utils.build:build_recipes(226): Nothing to be done.
Traceback (most recent call last):
  File "./simulate-travis.py", line 150, in <module>
    sp.run(['scripts/travis-run.sh'], env=env, universal_newlines=True, check=True)
  File "/homes/biertruck/fall/anaconda3/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['scripts/travis-run.sh']' returned non-zero exit status 1

Any Idea what the problem can be here? The ouptut is not really helping

**Comment by daler** [comment]
We had some build issues now fixed in #3080, can you please rebase and retry?

**Comment by jfallmann** [comment]
@daler rebased commits, what do I have to do that simulate-travis does not end with the AttributeError: 'FileNotFoundError' object has no attribute 'read' Error when testing locally?
Or does this mean the fix did not work?

**Comment by daler** [comment]
Hmm, that's the error we were getting on travis-ci that is now fixed. It seems to have been related to unpinned versions. 

Can you try `./simulate-travis.py --install-requirements` to see if that helps?

(more details at http://bioconda.github.io/bioconda-utils/contributing.html#update-repo-and-requirements)

**Comment by jfallmann** [comment]
It did downgrade some packages I updated with conda update --all,
but the error remains, I'll wait for Travis to finish the build to see whether this is a local problem or
a general one. Thanks for your help so far!

**Comment by daler** [comment]
That's exactly what the underlying issue was: the `linux-anvil` container had been updated with `conda update --all`, and parts of the build system weren't expecting that. The solution was to pin everything that was used. Honestly I don't know exactly what package was the issue (well, it was probably requests but unclear which package changed it) and it was kind of a quick fix. The better fix will be to update the entire build system but that's not as quick.

I agree, waiting for the travis tests will be the easiest way forward for now.

**Comment by jfallmann** [comment]
@bgruening Please close PR, a new one will come

**Pull request closed without merging**
