### PR TITLE
updated for package update

### PR DESCRIPTION
**Pull request by oena**
* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [X] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [X] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by oena** [comment]
Thanks for the helpful review @mbargull. Just wondering, I thought gcc & llvm were needed because of bioconda not working with Windows... did this change or am I misunderstanding? Happy to update the requirements otherwise.

**Comment by mbargull** [comment]
You just need `gcc`/`llvm` for packages that use them to compile things. But since you don't compile any C-Extensions, you just need `python` itself (and `setuptools` because that's used by `setup.py`).
As for Windows, yes, Bioconda still only supports Linux and macOS. On Windows you'd just have other compilers/runtimes to (possibly) depend on, but likewise only if you were to compile extensions.
Pure Python packages just need their `python` to be happy :smile:.

**Comment by oena** [comment]
Hmm @mbargull I implemented the changes you suggested and now the CircleCI tests are failing. Thoughts?

**Comment by mbargull** [comment]
Hi @oena, that's a good test failure! I mean, annoying for you, but it surfaced an issue in a very popular package, `pandas`. I opened a PR on the `pandas` feedstock to fix this: https://github.com/conda-forge/pandas-feedstock/pull/40.
Do you need the `cmappy` update urgently or would it be fine for you to wait a bit on the fix to be applied upstream?
Also, acc. to `setup.py`, `six` is also a run dependency, right?

**Comment by oena** [comment]
Aha, thanks for filing that. I'm willing to wait for a little, but obviously would also like this update to occur sooner rather than later since it fixes a bug that potentially could cause people some problems. I guess we'll see. 

And `six` isn't a requirement anymore for the time being; you are correct that the setup.py file is inconsistent about that though (will update). Basically a contributor added some changes to implement some Python 3 compatibility (but not all the way), and it ultimately ended up causing more problems than we had the bandwidth to address so we removed py3 compatibility for the time being.

**Comment by mbargull** [comment]
> I'm willing to wait for a little, but obviously would also like this update to occur sooner rather than later since it fixes a bug that potentially could cause people some problems.

Let's "fix" this here then for now :wink:

**Comment by oena** [comment]
Works for me. Thanks!

**Pull request merged**
