### PR TITLE
Remove env matrix

### PR DESCRIPTION
**Pull request by kyleabeauchamp**
* [ ] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [ ] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [x] This PR does something else (explain below).

I *think* this is deprecated after the CB3 migration.

### CODE REVIEW

**Comment by bgruening** [comment]
Can you fix one random recipe and we see if this is working :)
Thanks @kyleabeauchamp!

**Comment by acaprez** [comment]
The `config.yml` file still has the line `env_matrix: "scripts/env_matrix.yml"`.  Guessing that line should be removed as well?

**Comment by kyleabeauchamp** [comment]
OK I removed that line.

**Comment by dpryan79** [comment]
@bioconda-bot update

**Pull request merged**
