### PR TITLE
adds xcftools recipe

### PR DESCRIPTION
**Pull request by kostrykin**
Adds recipe for xcftools (https://github.com/j-jorge/xcftools).

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by kostrykin** [comment]
@ThomasWollmann ping

**Comment by bgruening** [comment]
Not the master.zip, but you can get to every single commit a tarball :-)

**Comment by ThomasWollmann** [comment]
@bgruening do you know why this fails with this strange error?

**Comment by bgruening** [comment]
Can you paste me the error, I'm in a train....

**Comment by kostrykin** [comment]
@bgruening 

Here is the error:

```
source tree in: /opt/conda/conda-bld/xcftools_1500393969251/work/xcftools-196f51790bbaff594525935adeab1247bb798946
Traceback (most recent call last):
  File "/opt/conda/bin/conda-build", line 6, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "/opt/conda/lib/python3.5/site-packages/conda_build/cli/main_build.py", line 342, in main
    execute(sys.argv[1:])
  File "/opt/conda/lib/python3.5/site-packages/conda_build/cli/main_build.py", line 333, in execute
    noverify=args.no_verify)
  File "/opt/conda/lib/python3.5/site-packages/conda_build/api.py", line 97, in build
    need_source_download=need_source_download, config=config)
  File "/opt/conda/lib/python3.5/site-packages/conda_build/build.py", line 1522, in build_tree
    config=config)
  File "/opt/conda/lib/python3.5/site-packages/conda_build/build.py", line 1145, in build
    utils.check_call_env(cmd, env=env, cwd=src_dir)
  File "/opt/conda/lib/python3.5/site-packages/conda_build/utils.py", line 628, in check_call_env
    return _func_defaulting_env_to_os_environ(subprocess.check_call, *popenargs, **kwargs)
  File "/opt/conda/lib/python3.5/site-packages/conda_build/utils.py", line 624, in _func_defaulting_env_to_os_environ
    return func(_args, **kwargs)
  File "/opt/conda/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/bin/bash', '-x', '-e', '/opt/conda/conda-bld/xcftools_1500393969251/work/xcftools-196f51790bbaff594525935adeab1247bb798946/conda_build.sh']' returned non-zero exit status 2

16:06:59 BIOCONDA ERROR BUILD SUMMARY: of 1 recipes, 1 failed and 0 were skipped. Details of recipes and environments follow.
16:06:59 BIOCONDA ERROR BUILD SUMMARY: FAILED recipe xcftools-1.0.7-1.tar.bz2, environment CONDA_R=3.3.2;CONDA_NPY=112;CONDA_NCURSES=5.9;MACOSX_DEPLOYMENT_TARGET=10.9;CONDA_GSL=1.16;CONDA_BOOST=1.61;CONDA_HTSLIB=1.5;CONDA_PY=27;CONDA_PERL=5.22.0;CONDA_GMP=5.1;CONDA_HDF5=1.8.17
```

And here is the full log as raw text: https://api.travis-ci.org/jobs/254918963/log.txt?deansi=true

**Comment by bgruening** [comment]
@kostrykin the error was above:
```
xgettext -o po/xcftools.pot.tmp -C -k_ -kN_ \
	--foreign-user --msgid-bugs-address=henning@makholm.net \
	--flag=FatalGeneric:2:c-format \
	--flag=FatalUnexpected:1:c-format \
	--flag=FatalBadXCF:1:c-format \
	--flag=FatalUnsupportedXCF:1:c-format \
	xcfinfo.oi xcf2pnm.oi xcf2png.oi xcfview.oi options.i enums.c flatten.c xcf2png.c flatspec.c io-unix.c scaletab.c xcf-general.c xcfinfo.c palette.c pixels.c xcf2pnm.c utils.c
make: xgettext: Command not found
make: *** [Makefile:145: po/xcftools.pot] Error 127
```

**Comment by kostrykin** [comment]
@bgruening Thanks a lot, and just in case something similar happens again in the future: Is it possible to see that error you posted for non-privileged users like me?

**Comment by bgruening** [comment]
Sure. I do not see more then you. This error was above yours. Reading the logs requires a little bit of training :-) sorry for that.

**Comment by bgruening** [comment]
You don't need to ship a license file inside this repository.

**Comment by bgruening** [comment]
@kostrykin this is wired, if you look above the commit where you have removed the license file, this one worked on OSX isn't it?

**Comment by kostrykin** [comment]
Yes it is weird. The commit right (!) before removing the OSX build passed, but your previous commit #854598d with exactly the same configuration already didn't work earlier. So to put it more precisely, one should say that the build doesn't pass *reproducibly* for OSX.

**Comment by kostrykin** [comment]
Well, not it's not even starting to process the OSX build anymore. Can you maybe just accept my last commit for the merge, which passed earlier?

**Pull request merged**
