### PR TITLE
Update newick utils

### PR DESCRIPTION
**Pull request by Cashalow**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

The latest stable version is too old (2011) and lacks many features

### CODE REVIEW

**Comment by Cashalow** [comment]
Do you think this is okay to be merged @bgruening (one check failed on osx) ? Thanks a lot.

**Comment by bgruening** [comment]
Where do you see a failing test?

**Comment by Cashalow** [comment]
In the previous commit, during the `make check` https://travis-ci.org/bioconda/bioconda-recipes/jobs/275882367

**Comment by bgruening** [comment]
Oh I see, mh not sure it means that something with the OSX stuff if wrong. "FAIL: test_nw_gen.sh" ... not sure why. But I would skip the OSX builds for this or try to fix the error :(

**Comment by Cashalow** [comment]
I tried a little bit but I did not manage. However I don't even know whether the previous version passed these particular tests because I did not run the `make check` before. So you prefer to make this update Linux specific only ?

**Comment by bgruening** [comment]
Can you fill an issue upstream and ask if this is known?

**Pull request merged**
