### PR TITLE
	modified:   perl-bio-viennangs/meta.yaml

### PR DESCRIPTION
**Pull request by mtw**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [ ] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by bgruening** [comment]
```
The CI configuration is out of date.
Please merge in bioconda:master.
```
:)

**Comment by mtw** [comment]
@bgruening can you tell me where/why linting fails?

**Comment by bgruening** [comment]
@mtw if you follow the CI system you will see a description here: https://circleci.com/gh/bioconda/bioconda-recipes/2547?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

This should bring you to https://bioconda.github.io/linting.html#uses-perl-threaded. So please replace perl-threded by `perl` :)

Welcome to bioconda!

**Comment by bgruening** [comment]
```
Building PerlIO-gzip-0.20 ... ! Installing PerlIO::gzip failed. See /root/.cpanm/work/1518709601.209/build.log for details. Retry with --force to force install it.
! Installing the dependencies failed: Module 'Moose::Util::TypeConstraints' is not installed, Module 'Moose' is not installed, Module 'PerlIO::gzip' is not installed, Module 'MooseX::Clone' is not installed, Module 'namespace::autoclean' is not installed, Module 'Tie::Hash::Indexed' is not installed
```
It seems you are missing some dependencies.

**Pull request closed without merging**
