### PR TITLE
Update meta.yaml

### PR DESCRIPTION
**Pull request by therealgenna**
lint error says there's no need for that and these lines give an error.

(based on https://github.com/bioconda/bioconda-recipes/pull/37539)

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by therealgenna** [comment]
@DReichLab Hi, trying to build eigensoft 8.0.0 get an error:
```
cp: cannot stat ‘smshrink’: No such file or directory
```
This results from a line in our `build.sh`:
```
cp {baseprog,convertf,mergeit,pca,smshrink} $PREFIX/bin/
```
I see a comment `// was smshrink.c` https://github.com/DReichLab/EIG/blob/09ed563fdec05648a66c206ba1fc37a198395cd7/src/eigensrc/smartpca.c#L125
so something apparently has been renamed. Should I replace `smshrink` in the `cp` above with something else or just remove it? Thanks!

**Comment by MatthewMah** [comment]
In the EIG project, the `make install` target simply copies the compiled binary to a local bin directory. There's nothing important about the `install` target; if the smshrink builds correctly it will be in the src directory and you can use the binary there directly.

**Comment by therealgenna** [comment]
@MatthewMah Thank you for replying, but I don't see `smshrink` as one of the targets in your repo - I don't see a `smshrink.c` file, for example. I guess our recipe was created manually a while ago and it seems to expect `smshrink` to be built; it wants to copy it and fails when it does not find it. So my guess was that it existed in some prior versions, based on the comment on line 125 of smartpca.c, but was either incorporated as part of `smartpca` or removed altogether.

Since we are building a conda package I am trying to make sure we copy all necessary commands to $PREFIX/bin/ in conda distribution, but I don't have the list of all the commands. And what worked before fails. What we have is:
```
# Install (makefile install has hard-coded destination, so have to do this manually)
mkdir -p $PREFIX/bin
cp {baseprog,convertf,mergeit,pca,smshrink} $PREFIX/bin/
cp {eigensrc/pcatoy,eigensrc/smartrel,eigensrc/smarteigenstrat,eigensrc/twstats} $PREFIX/bin/
cp {eigensrc/eigenstrat,eigensrc/eigenstratQTL,eigensrc/smartpca} $PREFIX/bin/
```
I want to know how to modify this part. Do I need to include all (and only) names under https://github.com/DReichLab/EIG/tree/master/src and https://github.com/DReichLab/EIG/tree/master/src/eigensrc or some subset of these?

**Comment by therealgenna** [comment]
@MatthewMah I found an answer: from https://github.com/DReichLab/EIG/blob/master/src/Makefile I see:
```
ED=eigensrc
```
```
EXE = baseprog convertf mergeit pca \
	$(ED)/pcatoy $(ED)/smartrel $(ED)/smarteigenstrat \
	$(ED)/twstats $(ED)/eigenstrat $(ED)/eigenstratQTL $(ED)/smartpca

all:    $(EXE)

install:  all
	mv $(EXE) ../bin
```
So I should use
```
# Install (makefile install has hard-coded destination, so have to do this manually)
mkdir -p $PREFIX/bin
cp {baseprog,convertf,mergeit,pca} $PREFIX/bin/
cp {eigensrc/pcatoy,eigensrc/smartrel,eigensrc/smarteigenstrat,eigensrc/twstats} $PREFIX/bin/
cp {eigensrc/eigenstrat,eigensrc/eigenstratQTL,eigensrc/smartpca} $PREFIX/bin/
```
Basically, the answer is to remove `smshrink`.

**Comment by therealgenna** [comment]
@BiocondaBot please add label

**Comment by MatthewMah** [comment]
Yes, this looks good. 

Sorry for the confusion. I am not actually the primary developer (Nick Patterson) of this project but help out with git publishing, so I'm not familiar with all of Nick's changes.

**Comment by dpryan79** [comment]
@BiocondaBot please fetch artifacts

**Comment by dpryan79** [comment]
@BiocondaBot please merge

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@BiocondaBot please merge

**Pull request merged**
