### PR TITLE
Rebuild more r packages

### PR DESCRIPTION
**Pull request by bgruening**
* [x] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by bgruening** [comment]
@daler not sure but it seems that we have a `loop` forever candidate here. Do you own a Mac or how have you figure out which package is the bad guy?

**Comment by daler** [comment]
Won't have access to a mac until Tuesday. I had figured out which was looping by running locally and watching the log, but there was nothing about the recipe that caused it. Must be something in the R package tarball.

**Comment by bgruening** [comment]
This one is also interesting.
```
The following specifications were found to be in conflict:
  - llvm
  - r 3.3.1*
Use "conda info <package>" to see the dependencies for each package.
```

**Comment by bgruening** [comment]
Finally! OSX is such a time sink.

**Pull request merged**
