### PR TITLE
[BULK] update 271018

### PR DESCRIPTION
**Pull request by dpryan79**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [x] This PR does something else (explain below).

Fixes various recipes in bulk.

### CODE REVIEW

**Comment by apcamargo** [comment]
Are we free to update recipes to Bioconductor 3.7 already?

**Comment by bgruening** [comment]
@apcamargo Devon currently does this only on the bulk branch. So if you can wait some more time or helping fixing the bulk branch this would be great.

**Comment by apcamargo** [comment]
@bgruening Sure, I can try helping you on the bulk branch (even tough I'm unsure I'll be of any help). Are all users free to commit to the branch, or do I need some kind of permission?

**Comment by bgruening** [comment]
`bulk` is as `master`as a protected branch, so please ping an admin to get a merge. Thanks for helping!

**Comment by dpryan79** [comment]
At this point the biggest help would be to ensure there's a Linux build of the bulk branch going on at all times. Anyone can rerun the most recent one, you don't need any special privileges. There's no need to do that for OSX. At the moment I'm doing maybe one update to bulk a day and otherwise just trying to ensure that it's building.

**Pull request merged**
