### PR TITLE
Update bwa to 0.7.18

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`bwa`](https://bioconda.github.io/recipes/bwa/README.html): **0.7.17** &rarr; **0.7.18**

[install with bioconda](http://bioconda.github.io/recipes/bwa/README.html) [Conda](https://anaconda.org/bioconda/bwa/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/bwa`](https://github.com//bioconda/bioconda-recipes/tree/bump/bwa/recipes/bwa) (click to view/edit other files)
Summary | The BWA read mapper.
Home | [https://github.com/lh3/bwa](https://github.com/lh3/bwa)
Releases |[https://github.com/lh3/bwa/tags](https://github.com/lh3/bwa/tags)
Author | @lh3
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by jmarshall** [comment]
```
$ file ./bwa
./bwa: ELF 64-bit LSB pie executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, with debug_info, not stripped
$ ./bwa

Program: bwa (alignment via Burrows-Wheeler transformation)
Version: 0.7.18-r1243-dirty
Contact: Heng Li <hli@ds.dfci.harvard.edu>

Usage:   bwa <command> [options]
```

Upstream forgot to remove `-dirty` from their PACKAGE_VERSION, but oh well… 🤷

**Comment by jmarshall** [comment]
@BiocondaBot please fetch artifacts

**Comment by jmarshall** [comment]
@BiocondaBot please fetch artifacts

**Review by martin-g — APPROVED** [review]
LGTM!

**Comment by bgruening** [comment]
Should we patch the dirty out?

**Review by bgruening — APPROVED** [review]

**Pull request merged**
