### PR TITLE
rust-bio-tools & starcode: add linux-aarch64 build

### PR DESCRIPTION
**Pull request by martin-g**
Describe your pull request here

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

### General instructions

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

### Instructions for avoiding API, ABI, and CLI breakage issues
Conda is able to record and lock (a.k.a. pin) dependency versions used at build time of other recipes.
This way, one can avoid that expectations of a downstream recipe with regards to API, ABI, or CLI are violated by later changes in the recipe.
If not already present in the meta.yaml, make sure to specify `run_exports` (see [here](https://bioconda.github.io/contributor/linting.html#missing-run-exports) for the rationale and comprehensive explanation).
Add a `run_exports` section like this:

```yaml
build:
  run_exports:
    - ...

```

with `...` being one of:

| Case                             | run_exports statement                                               |
| -------------------------------- | ------------------------------------------------------------------- |
| semantic versioning              | `{{ pin_subpackage("myrecipe", max_pin="x") }}`     |
| semantic versioning (0.x.x)      | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}`   |
| known breakage in minor versions | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| known breakage in patch versions | `{{ pin_subpackage("myrecipe", max_pin="x.x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| calendar versioning              | `{{ pin_subpackage("myrecipe", max_pin=None) }}`    |

while replacing `"myrecipe"` with either `name` if a `name|lower` variable is defined in your recipe or with the lowercase name of the package in quotes.

### Bot commands for PR management

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

Note that the <code>@BiocondaBot please merge</code> command is now depreciated. Please just squash and merge instead.

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by martin-g** [comment]
Depends on a new release upstream
- https://github.com/rust-bio/rust-bio-tools/commit/0ffaf4d29776b373c0a0187ec4496d2f51e2f8cf#commitcomment-140597552

**Comment by martin-g** [comment]
@BiocondaBot please fetch artifacts

**Comment by martin-g** [comment]
starcode:
```

mgrigorov in 🌐 euler-arm-22 in /tmp/starcode took 4s 
❯ tar jxvf starcode-1.4-h8a409c4_5.tar.bz2 
info/files
info/test/run_test.sh
info/run_exports.json
info/recipe/build.sh
info/hash_input.json
info/paths.json
info/index.json
info/recipe/meta.yaml.template
info/recipe/meta.yaml
info/recipe/conda_build_config.yaml
info/about.json
info/git
bin/starcode

mgrigorov in 🌐 euler-arm-22 in /tmp/starcode 
❯ file bin/*
bin/starcode: ELF 64-bit LSB pie executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, not stripped

mgrigorov in 🌐 euler-arm-22 in /tmp/starcode 
❯ ./bin/starcode 

Usage:  starcode [options]

  general options:
    -d --dist: maximum Levenshtein distance (default auto)
    -t --threads: number of concurrent threads (default 1)
    -q --quiet: quiet output (default verbose)
    -v --version: display version and exit

  cluster options: (default algorithm: message passing)
    -r --cluster-ratio: min size ratio for merging clusters in
               message passing (default 5.0)
    -s --sphere: use sphere clustering algorithm
    -c --connected-comp: cluster connected components

  input/output options (single file, default)
    -i --input: input file (default stdin)
    -o --output: output file (default stdout)

  input options (paired-end fastq files)
    -1 --input1: input file 1
    -2 --input2: input file 2

  output options (paired-end fastq files, --non-redundant only)
       --output1: output file1 (default input1-starcode.fastq)
       --output2: output file2 (default input2-starcode.fastq)

  output format options
       --non-redundant: remove redundant sequences from input file(s)
       --print-clusters: outputs cluster compositions
       --seq-id: print sequence id numbers (1-based)
```

**Comment by martin-g** [comment]
rbt:
```
mgrigorov in 🌐 euler-arm-22 in /tmp/rust-bio-tools via 🅒 font-ubuntu 
❯ file bin/*                                                                                                                                                                                           (font-ubuntu) 
bin/rbt: ELF 64-bit LSB pie executable, ARM aarch64, version 1 (GNU/Linux), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, not stripped

mgrigorov in 🌐 euler-arm-22 in /tmp/rust-bio-tools via 🅒 font-ubuntu 
❯ ./bin/rbt                                                                                                                                                                                            (font-ubuntu) 
Rust-Bio-Tools 0.42.1
Johannes Köster <johannes.koester@tu-dortmund.de>
A set of ultra-fast command line utilities for bioinformatics tasks based on Rust-Bio.

USAGE:
    rbt [FLAGS] <SUBCOMMAND>

FLAGS:
    -h, --help       Prints help information
    -V, --version    Prints version information
    -v, --verbose    Verbose output.

SUBCOMMANDS:
    bam-anonymize                  Tool to build artifical reads from real BAM files with identical properties
    bam-depth                      Print depth of BAM or CRAM file at given positions from STDIN (tab separated:
                                   chrom, pos)
    collapse-reads-to-fragments    Tool to predict maximum likelihood fragment sequence from FASTQ or BAM files
    csv-report                     Creates report from a given csv file containing a table with the given data
                                   Examples: With current directory as default ouput path: rbt csv-report
                                   path/to/table.csv --rows-per-page 100 --sort-column "p-value" --sort-order
                                   ascending
    fastq-filter                   Remove records from a FASTQ file (from STDIN), output to STDOUT
    fastq-split                    Split FASTQ file from STDIN into N chunks
    help                           Prints this message or the help of the given subcommand(s)
    plot-bam                       Creates a html file with a vega visualization of the given bam region that is
                                   then written to stdout.
    sequence-stats                 Tool to compute stats on sequence file (from STDIN), output is in YAML with
                                   fields: - min: length of shortest sequence - max: length of longest sequence -
                                   average: average length of sequence - median: median length of sequence -
                                   nb_reads: number of reads - nb_bases: number of bases - n50: N50 of sequences
    vcf-annotate-dgidb             Looks for interacting drugs in DGIdb and annotates them for every gene in every
                                   record
    vcf-baf                        Annotate b-allele frequency for each single nucleotide variant and sample
    vcf-fix-iupac-alleles          Convert any IUPAC codes in alleles into Ns (in order to comply with VCF 4 specs).
                                   Reads VCF/BCF from STDIN and writes BCF to STDOUT
    vcf-match                      Annotate for each variant in a VCF/BCF at STDIN whether it is contained in a
                                   given second VCF/BCF. The matching is fuzzy for indels and exact for SNVs.
                                   Results are printed as BCF to STDOUT, with an additional INFO tag MATCHING. The
                                   two vcfs do not have to be sorted
    vcf-report                     Creates report from a given VCF file including a visual plot for every variant
                                   with the given BAM and FASTA file. The VCF file has to be annotated with VEP,
                                   using the options --hgvs and --hgvsg
    vcf-split                      Split a given VCF/BCF file into N chunks of approximately the same size.
                                   Breakends are kept together. Output type is always BCF
    vcf-to-txt                     Convert VCF/BCF file from STDIN to tab-separated TXT file at STDOUT. INFO and
                                   FORMAT tags have to be selected explicitly
```

LGTM!

**Comment by martin-g** [comment]
Converted to Draft PR because of:
- https://github.com/rust-bio/rust-bio-tools/pull/259#issuecomment-2039175667

**Comment by martin-g** [comment]
@BiocondaBot please add label

**Comment by martin-g** [comment]
@BiocondaBot please add label

**Review by mencian — APPROVED** [review]

**Pull request merged**
