### PR TITLE
xxmotif: add linux-aarch64 build

### PR DESCRIPTION
**Pull request by martin-g**
Describe your pull request here

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

### General instructions

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

### Instructions for avoiding API, ABI, and CLI breakage issues
Conda is able to record and lock (a.k.a. pin) dependency versions used at build time of other recipes.
This way, one can avoid that expectations of a downstream recipe with regards to API, ABI, or CLI are violated by later changes in the recipe.
If not already present in the meta.yaml, make sure to specify `run_exports` (see [here](https://bioconda.github.io/contributor/linting.html#missing-run-exports) for the rationale and comprehensive explanation).
Add a `run_exports` section like this:

```yaml
build:
  run_exports:
    - ...

```

with `...` being one of:

| Case                             | run_exports statement                                               |
| -------------------------------- | ------------------------------------------------------------------- |
| semantic versioning              | `{{ pin_subpackage("myrecipe", max_pin="x") }}`     |
| semantic versioning (0.x.x)      | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}`   |
| known breakage in minor versions | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| known breakage in patch versions | `{{ pin_subpackage("myrecipe", max_pin="x.x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| calendar versioning              | `{{ pin_subpackage("myrecipe", max_pin=None) }}`    |

while replacing `"myrecipe"` with either `name` if a `name|lower` variable is defined in your recipe or with the lowercase name of the package in quotes.

### Bot commands for PR management

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

Note that the <code>@BiocondaBot please merge</code> command is now depreciated. Please just squash and merge instead.

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by martin-g** [comment]
@BiocondaBot please fetch artifacts

**Comment by martin-g** [comment]
```

mgrigorov in 🌐 euler-arm-22 in /tmp/xxmotif via 🅒 font-ubuntu took 11s 
❯ tar jxvf xxmotif-1.6-hd82cc20_4.tar.bz2                                                                                                                                                              (font-ubuntu) 
info/files
info/run_exports.json
info/test/run_test.sh
info/recipe/build.sh
info/hash_input.json
info/paths.json
info/index.json
info/recipe/meta.yaml.template
info/recipe/fix-build.patch
info/recipe/meta.yaml
info/recipe/conda_build_config.yaml
info/about.json
info/licenses/LICENSE
info/git
bin/XXmotif

mgrigorov in 🌐 euler-arm-22 in /tmp/xxmotif via 🅒 font-ubuntu 
❯ file bin/XXmotif                                                                                                                                                                                     (font-ubuntu) 
bin/XXmotif: ELF 64-bit LSB pie executable, ARM aarch64, version 1 (GNU/Linux), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, with debug_info, not stripped

mgrigorov in 🌐 euler-arm-22 in /tmp/xxmotif via 🅒 font-ubuntu 
❯ ./bin/XXmotif                                                                                                                                                                                        (font-ubuntu) 

================
=   XX MOTIF   =
================

==============================================================================================================================
== XXmotif version 1.6
==============================================================================================================================

Usage: XXmotif OUTDIR SEQFILE [options] 

	OUTDIR:  output directory for all results
	SEQFILE: file name with sequences from positive set in FASTA format

Options:
	--negSet <FILE>				sequence set which has to be used as a reference set
	--zoops					use zero-or-one occurrence per sequence model (DEFAULT)
	--mops					use multiple occurrence per sequence model
	--oops					use one occurrence per sequence model
	--revcomp				search in reverse complement of sequences as well (DEFAULT: NO)
	--background-model-order <NUMBER>	order of background distribution (DEFAULT: 2, 8(--negset) )
	--pseudo <NUMBER>			percentage of pseudocounts used (DEFAULT: 10)
	-g|--gaps <NUMBER>			maximum number of gaps used for start seeds [0-3] (DEFAULT: 0)
	--type <TYPE>				defines what kind of start seeds are used (DEFAULT: ALL)
						 - possible types: ALL, FIVEMERS, PALINDROME, TANDEM, NOPALINDROME, NOTANDEM
	--merge-motif-threshold <MODE>		defines the similarity threshold for merging motifs (DEFAULT: HIGH)
						 - possible modes: LOW, MEDIUM, HIGH
	--no-pwm-length-optimization		do not optimize length during iterations (runtime advantages)
	--max-match-positions <INT>		max number of positions per motif (DEFAULT: 17, higher values will lead to very long runtimes)

	--batch					suppress progress bars (reduce output size for batch jobs)
	--maxPosSetSize <NUMBER>		maximum number of sequences from the positive set used [DEFAULT: all]
	-h|--help				print this help page
	--trackedMotif <SEED>			inspect extensions and refinement of a given seed (DEFAULT: not used)

Using conservation information
	--format FASTA|MFASTA			defines what kind of format the input sequences have (DEFAULT: FASTA)
	--maxMultipleSequences <NUMBER>		maximum number of sequences used in an alignment [DEFAULT: all]

Using localization information
	--localization				use localization information to calculate combined P-values 
						(sequences should have all the same length)
	--downstream <NUMBER>			number of residues in positive set downstream of anchor point (DEFAULT: 0)

Start with self defined motif:
	-m|--startMotif <MOTIF>			Start motif (IUPAC characters)
	-p|--profileFile <FILE>			profile file
	--startRegion <NUMBER>			expected start position for motif occurrences relative to anchor point (--localization)
	--endRegion <NUMBER>			expected end position for motif occurrences relative to anchor point (--localization)


==============================================================================================================================

Expectation Maximization (EM) options.

	--em	EM mode.


	Options to initialize models from file.

	--bindingSiteFile <FILE>
		Binding sites file name to initialize a single Markov model. Sequence lengths must not differ and be provided line-by-line.

	--bindingSiteLength <INTEGER>
		Specify the length of binding sites provided by --bindingSiteFile (not mandatory).

	--markovModelFile <FILE>
		Markov model file name (without ending) to initialize a single Markov model. Files <FILE>.conds and <FILE>.probs need to be available.


	Options to initialize models from XXmotif results. Options --bindingSiteFile and --markovModelFile must not be provided simultaneously.

	--nrModels <INTEGER> [<INTEGER>...]
		Number of one or more XXmotif models in the ranking used to initialize Markov models. The remaining parameters available to choose models from XXmotif results are ignored.

	--minModels <INTEGER>
		Min. number of XXmotif models used to initialize Markov models. Independent on options --maxPvalue and --minOccurrence. <INTEGER> > 0 (default: 1).

	--maxModels <INTEGER>
		Max. number of XXmotif models used to initialize Markov models. <INTEGER> > 0 (default: max. integer).

	--maxPvalue <FLOAT>
		Max. p-value of XXmotif models used to initialize Markov models. Not applied to min. number of models. (default: 1).

	--minOccurrence <FLOAT>
		Min. percentage of sequences containing a binding site instance. Not applied to min. number of models. (default: 0).

	--msq	Use model-specific specificity factors by considering the percentage of positive sequences containing a corresponding binding site instance.


	Options to initialize models from XXmotif results or a binding site file. Option --markovModelFile must not be provided simultaneously.

	--msq	Use model-specific specificity factors by considering the percentage of positive sequences containing a corresponding binding site instance.


	Options to initialize models.

	--addColumns <INTEGER>{1,2}
		Add columns to the left and/or right of models. <INTEGER> >= 0 (default: 0 0).


	Markov model options.

	-k <INTEGER>
		Markov model order. <INTEGER> >= 0 (default: 0).

	-a, --alpha <FLOAT> [<FLOAT>...]
		Markov model pseudo-counts factor(s). Markov model order k fixes vector size to k+1. <FLOAT> >= 0 (default: 10).

	--eta <FLOAT> [<FLOAT>...]
		Markov model pseudo-counts factor(s) defined by --alpha and -q. Markov model order k fixes vector size to k+1. Specify either --eta or --alpha. <FLOAT> >= 0 (default: 10).

	--interpolate
		Interpolate between higher- and lower-order probabilities.


	Interpolated Markov background model options.

	-K <INTEGER>
		Background model order. <INTEGER> >= 0. (default: 0).

	-A, --Alpha <FLOAT>
		Background model pseudo-counts factor. <FLOAT> >= 0 (default: 10).


	EM options.

	--noExpectationMaximizationPhase
		Initialize Markov model but skip EM phase.

	-q <FLOAT>
		Specificity factor approximates the percentage of sequences contributing to the Markov model. 0 < <FLOAT> < 1 (default: 0.1).

	--epsilon <FLOAT>
		EM convergence parameter. <FLOAT> > 0 (default: 0.001).

	--maxEMIterations <INTEGER>
		Max. number of EM iterations (default: max. integer).


	Weighting options.

	--sequenceIntsFile <FILE>
		Intensity or significance values for positive sequences. The higher the values the higher the weights.

	--initInts
		Parameter to initialize models from XXmotif results by weighting instances with corresponding sequence weigths. Option --sequenceIntsFile must be provided simultaneously. Options --bindingSiteFile and --markovModelFile must not be provided simultaneously.

	--rankWeighting
		Rank-based weighting (default: intensity-based weighting).

	--backgroundQuantile <FLOAT>
		Quantile to estimate the background intensity value (or rank). Sequences having their intensity value (rank) below (above) the background intensity value (rank) get assigned to weight zero. 0 <= <FLOAT> <= 1 (default: 0).

	--backgroundIntensity <FLOAT>
		Background intensity value. Sequences having their intensity value below the background intensity value get assigned to weight zero. Option --rankWeighting must not be provided simultaneously (default: min. intensity value).

	--backgroundRank <INTEGER>
		Background intensity rank. Sequences having their intensity rank above the background intensity rank get assigned to weight zero. Option --rankWeighting must be provided simultaneously (default: max. rank).


	Binding site weighting options.

	--bindingSiteIntsFile <FILE>
		Intensity or significance values for binding site sequences. The higher the values the higher the weights. Option --bindingSiteFile must be provided simultaneously.

	--bindingSiteRankWeighting
		Binding site rank-based weighting (default: intensity-based weighting).

	--bindingSiteBackgroundQuantile <FLOAT>
		Quantile to estimate the background intensity value (or rank). Binding sites having their intensity value (rank) below (below) the background intensity value (rank) get assigned to weight zero. 0 <= <FLOAT> <= 1 (default: 0).

	--bindingSiteBackgroundIntensity <FLOAT>
		Background intensity value. Binding sites having their intensity value below the background intensity value get assigned to weight zero. Option --bindingSiteRankWeighting must not be provided simultaneously (default: min. intensity value).

	--bindingSiteBackgroundRank <INTEGER>
		Background intensity rank. Binding sites having their intensity rank above the background intensity rank get assigned to weight zero. Option --bindingSiteRankWeighting must be provided simultaneously (default: max. rank).


	Scoring options.

	--testPosSet
		Evaluate model(s) on training sequences.

	--testNegSet
		Evaluate model(s) on background sequences.

	--testSet <FILE>
		Evaluate model(s) on sequences in FASTA format. Specify one or more files. Sequence lengths may differ.

	--evaluatePWMs
		Evaluate PWM model(s) used to initialize Markov model(s) on test sequences.

	--logProbs
		Calculate log probabilities instead of log likelihood ratios.


	Output options.

	--saveInitModels
		Save Markov models after initialization to file.

	--saveModels
		Save Markov models after EM phase to file.

	--saveExpectationMaximizationLikelihoods
		Save EM iteration's sequence likelihoods and positional odds to file.

	--saveExpectationMaximizationModels
		Save EM iteration's Markov models to file.

	--verbose
		Verbose printouts.
```

LGTM!

**Comment by martin-g** [comment]
@BiocondaBot please add label

**Review by bgruening — APPROVED** [review]
Oh cool, thanks for resurrecting....

**Pull request merged**
