### PR TITLE
Update percolator

### PR DESCRIPTION
**Pull request by bgruening**
Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it. Note that if you are not already a member of the bioconda project (meaning that you can't add this label), please ping `@bioconda/core` so that your PR can be reviewed and merged (please note if you'd like to be added to the bioconda project). Please see https://github.com/bioconda/bioconda-recipes/issues/15332 for more details.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [ ] This PR adds a new recipe.
* [ ] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by dpryan79** [comment]
LGTM, though it'd be good to know the reason behind the boost pinning before.

**Comment by bgruening** [comment]
I only have this to offer: https://github.com/bioconda/bioconda-recipes/pull/13425/files

ping @apeltzer

**Comment by apeltzer** [comment]
We tried making some pipelines using percolator and OpenMS inside the same conda environment. This failed unless one pinned the required boost version to the same version for both OpenMS and the percolator recipe -  otherwise, we observed weird crashes. 

That was the main reason - if there is another way to keep these both running fine together, I'm happy to see that too 👍

**Comment by bgruening** [comment]
@apeltzer we are nowadays pinning all package against one single boost version. If we change this boost version we rebuild all packages that are dependent on boost ... this will make sure that those environments are working. So next time we need to rebuild openms instead. Thanks!

**Comment by apeltzer** [comment]
Thank you for making this happen 👍

**Comment by bgruening** [comment]
Unfortunately it was blacklisted ... :-( see the other open PR ...

**Pull request merged**
