### PR TITLE
Add freeman-lab/regional

### PR DESCRIPTION
**Pull request by joshmoore**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

A prerequisite of gh-10457

### CODE REVIEW

**Comment by corburn** [comment]
@joshmoore what is wrong with the existing setup.py?

**Comment by joshmoore** [comment]
Sorry, @corburn, I don't follow.

**Comment by joshmoore** [comment]
@corburn : Ah, I understand. Seems I've copied a bad habit from one of the first recipes I was involved in (`python-omero` which itself likely has bad habits). I'll revert across the multiple recipes and get everything green before moving forward.

**Comment by joshmoore** [comment]
Green. Merging along with showit and slicedimage.

**Pull request merged**
