### PR TITLE
fix repdenovo

### PR DESCRIPTION
**Pull request by dpryan79**
Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it. Note that if you are not already a member of the bioconda project (meaning that you can't add this label), please ping `@bioconda/core` so that your PR can be reviewed and merged (please note if you'd like to be added to the bioconda project). Please see https://github.com/bioconda/bioconda-recipes/issues/15332 for more details.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by dpryan79** [comment]
@jerowe This should get repdenovo built once merged (I might have to bump the build number to make the linter happy). It turns out that you can't use python version selectors (` - python=2.7`) in non-noarch recipes. When that happens, the entire recipe gets skipped. I consider that a conda bug and I think we have an issue open on bioconda-utils to add a lint for this.

**Comment by jerowe** [comment]
Aaaah sorry. I thought I got rid of those - python=2.7.  I don't know why I can never remember that python is a build variant and not just a regular dependency!

**Comment by dpryan79** [comment]
@jerowe If you could approve this PR I'll get it merged in once it passes testing.

**Comment by dpryan79** [comment]
@jerowe This can be merged whenever someone can approve it.

**Pull request merged**
