### PR TITLE
Add PubChemPy 1.0.4

### PR DESCRIPTION
**Pull request by drc007**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by bgruening** [comment]
Thanks!

**Comment by drc007** [comment]
Hi,

Would you mind having a look at this for me. I thought I’d write up a simple example and hopefully encourage the introduction of other chemistry packages.

https://www.macinchem.org/reviews/bioconda/bioconda.php <https://www.macinchem.org/reviews/bioconda/bioconda.php>

Any comments or suggestions would be much appreciated.

I hope to publish next week

Cheers,

Chris

**Comment by bgruening** [comment]
Sure, I will do in 12h in more detail. There are a few more Cheminformatics packages, more or less all from the ChemicalToolBox. E.g. osra, openmg, align-it, strip-it, shape-it, np-likeness-scorer, autodock-vina ... Also the example recipe looks broken in your blog.

**Comment by bgruening** [comment]
Here my small comments:

A few more ChemInfo tools:
  * openmg
  * align-it
  * strip-it
  * shape-it
  * np-likeness-scorer

* > 3100 software tools
* > 330 contributors 

* I would add a sentence about the `conda skeleton pypi/cran/cpan` generators, to ease the build.
* consider adding a link to https://bioconda.github.io at the beginning of this section

> Now, when doing "conda install ...", packages will be searched for first in bioconda, then conda-forge, then the defaults channel.

Its not about searching, its about the dependency priority. So if a dependency is in multiple channels, from where to get it. It helps the resolver.

* If you want, you can add a sentence that for all packages we are mirroring the tarballs and create Linux Containers for it (Docker, rkt ...)

**Pull request merged**
