### PR TITLE
Add openssl requirement to old samtools recipes

### PR DESCRIPTION
**Pull request by nsoranzo**
After the latest rebuilds in bulk, some samtools packages for older versions have also been rebuilt and are now linked against openssl-3.0.0 .
Unfortunately this openssl dependency is not declared in the old recipes, so it is now possible to install this newer builds in the same environment with packages linked against openssl-1.1 (e.g. `conda create -n test ucsc-bedgraphtobigwig samtools=1.6` ). This results in a broken environment where samtools is linked against openssl-3.0.0 but openssl-1.1 is installed, and running `samtools` fails with `samtools: error while loading shared libraries: libcrypto.so.3: cannot open shared object file: No such file or
directory` .

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by jmarshall** [comment]
These are legacy recipes, so IMHO there's no need to make incidental maintainability changes like reordering the dependency entries. Doing so makes seeing what's changed harder.

These `openssl` requirements should probably be `# [not osx]`.

**Comment by nsoranzo** [comment]
Thanks for the review!

> These are legacy recipes, so IMHO there's no need to make incidental maintainability changes like reordering the dependency entries. Doing so makes seeing what's changed harder.

Maintainability was actually the goal of these changes, since I like to do `diff -u recipes/samtools/1.3.1/meta.yaml recipes/samtools/1.6/meta.yaml` and showing only the real differences between versions is a long term benefit.

> These `openssl` requirements should probably be `# [not osx]`.

Added.

**Comment by jmarshall** [comment]
A long term benefit would be getting rid of the need for these outdated trash recipes :smile:

**Comment by nsoranzo** [comment]
@BiocondaBot please add label

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
Ugh, I hate these old recipes. In the unlikely event that I ever have some spare time, I'd like to look into whether they're actually in fact needed.

**Pull request merged**
