### PR TITLE
travis: use xcode7.3 for now

### PR DESCRIPTION
**Pull request by mbargull**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [ ] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [x] This PR does something else (explain below).

Until #6950 is resolved, we can use Travis' previous default image for OSX.

### CODE REVIEW

**Comment by mbargull** [comment]
BTW: looks like `conda-forge` is using `xcode6.4`:
https://github.com/conda-forge/conda-smithy/blob/9eae6b9be6b3236766eb866b5571d7bbc16d1529/conda_smithy/templates/travis.yml.tmpl#L12

**Comment by johanneskoester** [comment]
But we used 7.3 so far? Then we should stick with that.

**Comment by mbargull** [comment]
Yes, of course.
I guess 7.3 has been used since October 2016:
https://blog.travis-ci.com/2016-10-04-osx-73-default-image-live/
https://blog.travis-ci.com/2017-11-21-xcode8-3-default-image-announce

**Comment by mbargull** [comment]
Apparently there is something broken with Travis' OSX workers. I'll restart the build later.

**Comment by mbargull** [comment]
All good, ready for merge.
For the following commits the OSX builds have to be redone:
https://github.com/bioconda/bioconda-recipes/commit/b273e3be8e868162f1bcd44173fb2220617c5863
https://github.com/bioconda/bioconda-recipes/commit/0d0b215a5c3099b8d058c02b97959622bd1a1ff5

**Comment by cbrueffer** [comment]
Looks good to me!

**Pull request merged**
