### PR TITLE
Update bioconda-utils

### PR DESCRIPTION
**Pull request by johanneskoester**
* [x] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [x] This PR does something else (explain below).

Update to a new bioconda-utils version that should fix the issues seen in #2957 and #2973.

### CODE REVIEW

**Comment by bgruening** [comment]
What do you think about fixing this to master? This saves us from these additional PR and our contributors from potential rebases.

Is there a use-case where master of utils should not be used here?

Ping @daler

**Comment by johanneskoester** [comment]
Yes, we could do that. I would activate branch protection first.

**Comment by daler** [comment]
Yeah, probably a good idea to minimize travis builds whenever we can. I just turned on branch protection on bioconda-utils master branch. I'm making a small change in bioconda-utils to address #2982, so I'll test out the branch protection and then point recipes to bioconda-utils master branch.

**Comment by johanneskoester** [comment]
Thanks!

**Pull request merged**
