### PR TITLE
added medpy recipe

### PR DESCRIPTION
**Pull request by ThomasWollmann**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by ThomasWollmann** [comment]
@bgruening do you know a quick fix for the source issue?

**Comment by bgruening** [comment]
@ThomasWollmann fixed your error. Now it looks like a python2/3 issue.

**Comment by ThomasWollmann** [comment]
It seems like the package just works with python 2

**Comment by ThomasWollmann** [comment]
Now it got stuck at: "The medpy.graphcut.maxflow external C++ package could not be compiled, all graphcut functionality will be disabled. You might be missing Boost.Python or some build essentials like g++"

**Comment by ThomasWollmann** [comment]
> Now it got stuck at: "The medpy.graphcut.maxflow external C++ package could not be compiled, all graphcut functionality will be disabled. You might be missing Boost.Python or some build essentials like g++"

I don't need this functionality right now, but propably it's worth trying to get all packages running or others.

**Comment by bgruening** [comment]
What is `ImportError: No module named maxflow`?

**Comment by ThomasWollmann** [comment]
@bgruening awsome. Thanks a lot!

**Pull request merged**
