### PR TITLE
Add cuttlefish recipe

### PR DESCRIPTION
**Pull request by jamshed**
Add new recipe for the tool Cuttlefish (https://github.com/COMBINE-lab/cuttlefish/).

### CODE REVIEW

**Comment by jamshed** [comment]
@BiocondaBot: please add label.

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Comment by jamshed** [comment]
Hello @dpryan79: do I get to join the team now? :)

**Comment by dpryan79** [comment]
@jamshed Of course, I'll send you an invite

**Comment by jamshed** [comment]
Thank you Devon!

**Pull request merged**
