### PR TITLE
Add Cas recipe

### PR DESCRIPTION
**Pull request by Krannich479**
This is an initial PR for the package description of CAS.

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by Krannich479** [comment]
Dear @bioconda/core team, 
I am attempting to build my first ever bioconda package here and I am running out of hints why the recipe is failing. I cannot identify a clear hint in the log (at Azure Cloud) about what exactly is breaking. Any hint much appreciated!

Best

**Comment by dpryan79** [comment]
There's a small issue with how the Makefile is structured. Since things like CXXFLAGS aren't defined before appending to them with +=  the appending is getting skipped. I could patch around that, but ideally you'd change this upstream instead.

**Comment by Krannich479** [comment]
Hello @dpryan79 ,
first and foremost, thanks a million times for helping me out with this issue. Just to get this right: I'll fix the assignment of `DATE` and `VERSION` in my [Makefile](https://github.com/rki-mf1/CoverageAnomalyScanner/blob/main/Makefile) as well as the first appearances of `CXXFLAGS` and `LDLIBS` and make these variables assigned via `=`. Is that what you have in mind?

---
Just out of curiosity (because I am quiet baffled with the virtual environment of the bioconda's CI): the current Azure log of commit f135693 is complaining about `VERSION :=` but not (yet) about `CXXFLAGS +=`. My Makefile resembles the [Makefile of Popdel](https://github.com/kehrlab/PopDel/blob/master/Makefile) where `CXXFLAGS +=` is also never assigned with `=` and there exists no apparent fix to its [build.sh](https://github.com/bioconda/bioconda-recipes/blob/eab7bef9114cd40e0a6791f7b60f53afb893070b/recipes/popdel/build.sh) from what I can tell. Am I overlooking something?

**Comment by Krannich479** [comment]
Linux CI succeeds now
---
For future reference: adding command line parameters when calling a Makefile will overwrite internal variables entirely irrespective whether they are defined or appended. Hence, when attempting to patch a variable _v_ within a Makefile with some system variables of the Bioconda CI container then _v_ must have the keyword `override` prepend in order to preserve its values defined within the Makefile. E.g. commit 7bf407b entirely erased my internal values of CXXFLAGS before the fix.

**Comment by Krannich479** [comment]
@BiocondaBot please add label

**Comment by dpryan79** [comment]
@BiocondaBot please fetch artifacts

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@BiocondaBot please merge

**Pull request merged**
