### PR TITLE
Update mehari to 0.26.0

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`mehari`](https://bioconda.github.io/recipes/mehari/README.html): **0.25.5** &rarr; **0.26.0**

[install with bioconda](http://bioconda.github.io/recipes/mehari/README.html) [Conda](https://anaconda.org/bioconda/mehari/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/mehari`](https://github.com//bioconda/bioconda-recipes/tree/bump/mehari/recipes/mehari) (click to view/edit other files)
Summary | VEP-like tool for sequence ontology and HGVS annotation of VCF files written in Rust.
Home | [https://github.com/varfish-org/mehari](https://github.com/varfish-org/mehari)
Releases |[https://github.com/varfish-org/mehari/tags](https://github.com/varfish-org/mehari/tags)
Author | `@varfish-org`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Review by tedil — APPROVED** [review]

**Comment by tedil** [comment]
@martin-g if this keeps failing, we could try a different release profile with fewer optimizations (no lto / more codegen units) (if that is an issue)

**Comment by martin-g** [comment]
> @martin-g if this keeps failing, we could try a different release profile with fewer optimizations (no lto / more codegen units) (if that is an issue)

@tedil It seems something like this will be needed. Azure CI cannot compile all the dependencies for 1 hour and the CI job is killed. 
CircleCI builds everything in 19-20 mins, but the VM there is more powerful!

**Comment by tedil** [comment]
> > @martin-g if this keeps failing, we could try a different release profile with fewer optimizations (no lto / more codegen units) (if that is an issue)
> 
> @tedil It seems something like this will be needed. Azure CI cannot compile all the dependencies for 1 hour and the CI job is killed. CircleCI builds everything in 19-20 mins, but the VM there is more powerful!

That is unfortunate, since the performance gains from the optimizations are quite relevant. Nevertheless, that's how it is ;)
Is there an easy way to provide a different profile for cargo to use from within the recipe?

**Comment by martin-g** [comment]
https://stackoverflow.com/a/70221348/497381
You could either 
1. update mehari itself
2.  or add the profile with a .patch in the recipe.

Let me know if you need help with 2!

**Pull request merged**
