### PR TITLE
Update nanovar to 1.7.0

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`nanovar`](https://bioconda.github.io/recipes/nanovar/README.html): **1.5.1** &rarr; **1.7.0**

[install with bioconda](http://bioconda.github.io/recipes/nanovar/README.html) [Conda](https://anaconda.org/bioconda/nanovar/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/nanovar`](https://github.com//bioconda/bioconda-recipes/tree/bump/nanovar/recipes/nanovar) (click to view/edit other files)
Summary | Structural variant caller using low-depth long reads
Home | [https://github.com/cytham/nanovar](https://github.com/cytham/nanovar)
Releases |[https://pypi.org/pypi/nanovar/json](https://pypi.org/pypi/nanovar/json)
Recipe Maintainer(s) | @cytham

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by cbrueffer** [comment]
Needs new recipe `nanoinsight`.

**Comment by druvus** [comment]
Also needs [htmlark](https://pypi.org/project/HTMLArk/) to be added to conda-forge

**Comment by druvus** [comment]
I have opened a PR for [htmlark ](conda-forge/staged-recipes/pull/25593) at conda-forge

**Comment by druvus** [comment]
@BiocondaBot please update

**Comment by druvus** [comment]
Getting different errors. Changing between "No space on device" and permission denied.

**Comment by cbrueffer** [comment]
Seems to be a systemic issue, similar errors in https://github.com/bioconda/bioconda-recipes/pull/46108

**Pull request closed without merging**
