### PR TITLE
Add recipe for bambamc 0.0.50.

### PR DESCRIPTION
**Pull request by acaprez**
* [X] I have read the guidelines above.
* [X] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by acaprez** [comment]
Oops, looks like this is a duplicate of #1839.  Package name is `bambamc` here vs. `libbambamc` there.  @bioconda/core is there a convention to prefix `lib` for library-only packages?  I usually try to stick with using the repo/package name directly whenever possible.

**Comment by johanneskoester** [comment]
Indeed, there is no such convention. We try to use the name that the author has chosen.

**Comment by johanneskoester** [comment]
@bioconda/core  and preference about how to proceed? Deprecate the old package and use this one, or stick with the old name?

**Comment by bgruening** [comment]
+1 to deprecate the old one.

**Pull request merged**
