### PR TITLE
Update drop to 1.1.1

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`drop`](https://bioconda.github.io/recipes/drop/README.html): **1.1.0** &rarr; **1.1.1**

[install with bioconda](http://bioconda.github.io/recipes/drop/README.html) [Conda](https://anaconda.org/bioconda/drop/files)

Info | Link
-----|-----
Recipe | [`recipes/drop`](https://github.com//bioconda/bioconda-recipes/tree/bump/drop/recipes/drop) (click to view/edit other files)
Releases |[https://github.com/gagneurlab/drop/tags](https://github.com/gagneurlab/drop/tags)
Recipe Maintainer(s) | @c-mertes, @mumichae
Author | `@gagneurlab`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by c-mertes** [comment]
@BiocondaBot please add label

**Comment by c-mertes** [comment]
please first merge this #31668 into the autobump branch and then you can merge this one here into master

**Review by simonbray — APPROVED** [review]

**Comment by simonbray** [comment]
@BiocondaBot please merge

**Comment by c-mertes** [comment]
@simonbray thanks a lot.

**Pull request merged**
