### PR TITLE
Update numpy version for Clippy recipe

### PR DESCRIPTION
**Pull request by marc-jones**
The old recipe didn't specify the version for Numpy, which resulted in the automated Biocontainer which was made having an old Numpy version which caused Clippy to fail.

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by marc-jones** [comment]
@BiocondaBot please add label

**Comment by raivivek** [comment]
@marc-jones If the build was failing due to an old numpy version, does having something like `numpy >= XX` helps? That'd be better than a specific version pinning.

**Comment by marc-jones** [comment]
@raivivek Thanks for reviewing. I thought the same, but when I used:
```
    - numpy>=1.19.0
    - numpy-base>=1.19.0
```
in the recipe and did a local build of the package the tests would fail due to this numpy import error:
```
23:04:05 BIOCONDA INFO (ERR) Traceback (most recent call last):
23:04:05 BIOCONDA INFO (ERR)   File "/opt/conda/conda-bld/clippy_1638572062334/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.9/site-packages/numpy/core/__init__.py", line 22, in <module>
23:04:05 BIOCONDA INFO (ERR)     from . import multiarray
23:04:05 BIOCONDA INFO (ERR)   File "/opt/conda/conda-bld/clippy_1638572062334/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.9/site-packages/numpy/core/multiarray.py", line 12, in <module>
23:04:05 BIOCONDA INFO (ERR)     from . import overrides
23:04:05 BIOCONDA INFO (ERR)   File "/opt/conda/conda-bld/clippy_1638572062334/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.9/site-packages/numpy/core/overrides.py", line 7, in <module>
23:04:05 BIOCONDA INFO (ERR)     from numpy.core._multiarray_umath import (
23:04:05 BIOCONDA INFO (ERR) ImportError: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /opt/conda/conda-bld/clippy_1638572062334/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.9/site-packages/numpy/core/_multiarray_umath.cpython-39-x86_64-linux-gnu.so)
23:04:05 BIOCONDA INFO (ERR) 
23:04:05 BIOCONDA INFO (ERR) During handling of the above exception, another exception occurred:
23:04:05 BIOCONDA INFO (ERR) 
23:04:05 BIOCONDA INFO (ERR) Traceback (most recent call last):
23:04:05 BIOCONDA INFO (ERR)   File "/opt/conda/conda-bld/clippy_1638572062334/test_tmp/run_test.py", line 2, in <module>
23:04:05 BIOCONDA INFO (ERR)     import clip
23:04:05 BIOCONDA INFO (ERR)   File "/opt/conda/conda-bld/clippy_1638572062334/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.9/site-packages/clip/__init__.py", line 1, in <module>
23:04:05 BIOCONDA INFO (ERR)     import numpy as np
23:04:05 BIOCONDA INFO (ERR)   File "/opt/conda/conda-bld/clippy_1638572062334/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.9/site-packages/numpy/__init__.py", line 150, in <module>
23:04:05 BIOCONDA INFO (ERR)     from . import core
23:04:05 BIOCONDA INFO (ERR)   File "/opt/conda/conda-bld/clippy_1638572062334/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.9/site-packages/numpy/core/__init__.py", line 48, in <module>
23:04:05 BIOCONDA INFO (ERR)     raise ImportError(msg)
```
It seems the C library isn't linked or something and the numpy import fails as a result. This error appears with the following numpy versions:
```
23:00:39 BIOCONDA INFO (OUT)     numpy:                         1.21.2-py39hd8d4704_0      defaults
23:00:39 BIOCONDA INFO (OUT)     numpy-base:                    1.21.2-py39h2b8c604_0      defaults
```
But rolling back to an earlier version, this error doesn't occur.

**Comment by raivivek** [comment]
Oh great debugging. If you know that a particular version is problematic, you can include that too in the version specification along with `>=`. For example, see here. https://stackoverflow.com/questions/8795617/how-to-pip-install-a-package-with-min-and-max-version-range

**Review by raivivek — APPROVED** [review]

**Comment by raivivek** [comment]
@BiocondaBot please merge

**Pull request merged**
