### PR TITLE
samtools - pinned bzip2 to 1.0.* and zlib to 1.2.8

### PR DESCRIPTION
**Pull request by notestaff**
* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [X] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by bgruening** [comment]
Thanks!

**Comment by notestaff** [comment]
@bgruening Maybe, when a recipe gets updated, recipes that depend on it and were not pinned to earlier versions could be automatically re-tested?

**Comment by johanneskoester** [comment]
Yes, this should definitely be done in some form. We can even periodically scan updates in conda-forge and defaults. If the latest version is newer than one of our recipes, we should trigger a test. I'll think about it.

**Comment by notestaff** [comment]
@johanneskoester thanks!  the samtools issue here resulted from a bzip2 update on the defaults channel.

if any test fails, could automatically pin it to the "last good" version.

**Comment by bgruening** [comment]
I don't think this is practically possible with our open-, priceless infrastructure we are currently using. And even if we could do this with our university clouds this would waste a lot of CPU cycles and power - save the environment! :)

I think we are pretty bad at pinning and we need to pin way more libraries and align more with conda-forge here. This would have prevented your issue in the first place.
Luckily this will get much easier in the end of the year with conda-build-3. Until then we should try to pin more things directly, even zlib.

**Comment by johanneskoester** [comment]
You might be right. I'll nevertheless think about it. I still have the feeling that this can be done efficiently when we are careful

**Pull request merged**
