### PR TITLE
Rebuild sga with bamtools

### PR DESCRIPTION
**Pull request by npavlovikj**
:information_source:
If this is your first pull request to Bioconda please ping `@bioconda/core` so it can be reviewed and to request being added as a member of the Bioconda team. Members of the Bioconda team are able to merge their own pull requests once tests and linting have passed.

----------------

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by npavlovikj** [comment]
When `sparsehash` is not pinned (in that case `sparsehash=2.0.3=hf484d3e_1000` is used):
checking google/sparse_hash_set usability... no
configure: WARNING: google/sparse_hash_set: present but cannot be compiled
checking google/sparse_hash_set presence... yes
configure: WARNING: google/sparse_hash_set:     check for missing prerequisite headers?
configure: WARNING: google/sparse_hash_set: see the Autoconf documentation
configure: WARNING: google/sparse_hash_set:     section "Present But Cannot Be Compiled"
configure: WARNING: google/sparse_hash_set: proceeding with the compiler's result
configure: WARNING:     ## -------------------------------- ##
configure: WARNING:     ## Report this to js18@sanger.ac.uk ##
configure: WARNING:     ## -------------------------------- ##
checking for google/sparse_hash_set... no
configure: error: google sparse hash library is required: http://code.google.com/p/google-sparsehash/

`sparsehash=2.0.3=hf484d3e_1000` is built with the new compilers, so I don't know why it is not being recognized.

**Comment by dpryan79** [comment]
Ugh, yeah, I was struggling with this yesterday and eventually gave up. I see no reason why this shouldn't work, but would need to get inside the docker container to really debug it, which I'm not terribly motivated to do at the moment.

**Comment by npavlovikj** [comment]
Yeah, I don't understand why it is not working with the newest `sparsehash` either. 

Looks like the linux build was successful with `google-sparsehash` too. Both `google-sparsehash` and `sparsehash=2.0.2` are using the old compilers, so maybe `sga` needs to be modified to work with the new compilers?

**Comment by dpryan79** [comment]
Yeah, my guess is that it’s an incorrect configure test.

**Comment by npavlovikj** [comment]
I may have some time over the weekend to play with the recipe, If you have any ideas that may work, please feel free to update the branch :)

**Comment by npavlovikj** [comment]
You were right @dpryan79 , the configure file needed update with the new C++11 flags. The recipe is getting closer to be done, so I would appreciate your feedback and review when you have a chance.

**Comment by epruesse** [comment]
Don't set `-std=c++XY` anywhere if you don't have to. It should come from `CXXFLAGS` from the conda environment. That sets it to `c++17` currently. If that ever changes, we need to rebuild. Plenty of things are not ABI compatible for different c++XY.

I need to write a bit of docs somewhere on how to mess with `make` and `configure`. And hopefully someone else has something for `cmake`.

**Comment by npavlovikj** [comment]
I tried adding
**export CXXFLAGS="${CXXFLAGS} -std=c++11 -O3"**
**export CFLAGS="${CFLAGS} -std=gnu++11 -O3"**
in `build.sh`, but the configure file kept overriding them, and I was getting the `configure: error: google sparse hash library is required: http://code.google.com/p/google-sparsehash/` error from above.

Patching `configure` directly was the only combination that worked for me, but if there is better way of using the conda flags, please let me know @epruesse .

**Comment by epruesse** [comment]
Try overriding during make. 

Make CXXFLAGS=“$CXXFLAGS”

I’ll look at the recipe tomorrow morning. 

Elmar

--
message sent from mobile device

**Comment by npavlovikj** [comment]
Tried with `make CC=${CC} CXX=${CXX} CXXFLAGS=$CXXFLAGS CFLAGS=$CFLAGS` and the same "sparsehash" error persists :/

**Comment by epruesse** [comment]
That exact line?

**Comment by dpryan79** [comment]
Looks like that did the trick. I think it was setting `-std=c++11` internally, which needed to be overridden.

**Comment by epruesse** [comment]
> Tried with make CC=$CC CXX=$CXX CXXFLAGS=$CXXFLAGS CFLAGS=$CFLAGS and the same "sparsehash" error persists :/

Surprised that worked at all. You need to quote: `CXXFLAGS="$CXXFLAGS"`. If it worked without (no crazy make errors), then you had empty `CXXFLAGS`.

**Comment by npavlovikj** [comment]
I need a "sad panda" emoji here :/

And regarding "make" - I did try with set and empty flags, with `CXXFLAGS="$CXXFLAGS"` and `CXXFLAGS=$CXXFLAGS` - I just copied the latter one here. And it is good to know that no error with that syntax means empty flags...

**Comment by epruesse** [comment]
Ah. I see. The checks in configure fail. Ok. I’ll patch that. Gimme an hour.

**Comment by npavlovikj** [comment]
No problem at all @epruesse ,please take your time. I will check your update for this, but didn't the initial commit patched `configure` for this?

**Comment by epruesse** [comment]
I'll patch it so it will accept outside C(XX)FLAGS. Makes it simpler.

**Comment by epruesse** [comment]
@BiocondaBot merge

**Comment by npavlovikj** [comment]
Looks like everything is working properly now - many thanks for the cleanup and feedback @epruesse !

**Comment by epruesse** [comment]
You're welcome :) Thanks for helping Bioconda!

**Pull request merged**
