### PR TITLE
bumped vep version

### PR DESCRIPTION
**Pull request by matthdsm**
* [x] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by matthdsm** [comment]
Hi @bioconda/core 

Sorry for bothering you guys again, but I've no idea what goes wrong here. During the install , the vep installer tries to download and install the ensembl API. It seems there's an issue with curl during that step. I don't have a clue what could be the issue, since all that's changed in the installer script is the version number.. Any ideas?

**Comment by johanneskoester** [comment]
Here is the error: https://travis-ci.org/bioconda/bioconda-recipes/jobs/183197781#L596
unzip is missing in the conda-forge container that we use now. However, it is available via conda, so you can add it as a build dependency.

**Comment by matthdsm** [comment]
Well I'll be damned, I thought there was an issue with the curl request or something. adding unzip fixed it in a local build. I'll be pushing the changes shortly.

Thanks fot the help @johanneskoester!!

M

**Comment by matthdsm** [comment]
I seems the build still fails, due to the broken bioperl package. What is the best way to force use of build version 4? When I try `conda install -c bioconda perl-bioperl=1.6.924-4`, I get a `PackageNotFoundError`.

Thanks
M

**Comment by johanneskoester** [comment]
I think you need to use an underscore for the build version. So, build version 6 is broken? In what sense?

**Comment by matthdsm** [comment]
There are a bunch of modules missing. There's been already several bug reports about this:
#3131 and #2917

**Comment by johanneskoester** [comment]
@bgruening can you comment on the status of bioperl? How far are we away from fixing this?

**Comment by bgruening** [comment]
bioperl-1.7 has still some wired bugs and dependency issues. Maybe I find time over christmas it seems to be problematic and I'm not a perl expert.

**Comment by matthdsm** [comment]
Then what's the best way to pin the bioperl dependency on a previous build? This is something that needs to be done, since the current vep recipe is also broken because of the bioperl issue.

**Comment by bgruening** [comment]
@johanneskoester do we want to remove the latest 2 bioperl 1.6 builds?

**Comment by matthdsm** [comment]
👍 please do!

**Comment by matthdsm** [comment]
I think everything should work now, but if I understand the travis logs correctly, there's something going wrong during the download from Ensembl. Can the travis build be retriggered? Or do you guys think there's another issue?

Thanks
M

**Comment by rvalieris** [comment]
you can re-trigger the build my logging into the travis page(with github acc), I just triggered it now.

**Comment by matthdsm** [comment]
didn't know that, thanks!

**Comment by matthdsm** [comment]
ok, the local build works fine, and travis seems to be OK with the changes.
There's still one last issue left. During testing I noticed that the bio-db-hts library can't be found by vep (previous versions had this issue too)
Any perl masters around that have experience with this?
@bioconda/perl ?

**Comment by rvalieris** [comment]
it seems bio-db-hts is installed in the ```x86_64-linux-thread-multi``` directory, but perl doesn't have that directory on ```@INC```, perl-threaded does.

I think one of the dependencies(or the dependencies of the dependencies) is pulling perl instead of perl-threaded.

**Comment by bgruening** [comment]
To add more complexity it would be nice to deprecate perl-threaded and just stick to `perl`.
https://github.com/bioconda/bioconda-recipes/issues/3167#issuecomment-266816990

**Comment by johanneskoester** [comment]
@bgruening if the bioperl builds are broken, I agree with removing them.

**Comment by matthdsm** [comment]
Hi @bgruening ,

How do you propose I proceed from here? Should I stick with perl-threaded for the sake of continuity until you guys begin with the migration over to perl? Or do I pick the regular Perl? I don't mind changing it, as long as it doesn't screw up all the libraries and stuff. Is there already a mechanism in place to use the 'forged' version instead of the bioconda one?

M

**Comment by matthdsm** [comment]
@bioconda/core 
If there aren't any objections, I'm going to merge this with perl-threaded intact. We can always update the vep version in a second build if we're sure it won't screw up library discovery.
Awaiting confirmation!
M

**Pull request merged**
