### PR TITLE
Add MiModD package recipe

### PR DESCRIPTION
**Pull request by wm75**
* [x] I have read the guidelines above.
* [x] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by bgruening** [comment]
Thanks Wolfgang!

**Comment by bgruening** [comment]
@johanneskoester do you have time to have a look at this package? It was not uploaded but everything seems to be fine: https://travis-ci.org/bioconda/bioconda-recipes/builds/170022968
I'm busy today, sorry.

**Comment by johanneskoester** [comment]
@wm75 @bgruening the recipe has been put into the root folder of our repo. Not in the recipe folder. Please create a new PR that moves the recipe into the recipes folder as soon as possible. Otherwise, it will be ignored by the build system.

**Comment by wm75** [comment]
@johanneskoester @bgruening oops, sorry about this (it's my first PR here). I will create the new PR, of course.

**Comment by johanneskoester** [comment]
No problem, thanks!

**Pull request merged**
