### PR TITLE
Bump build

### PR DESCRIPTION
**Pull request by PertuyF**
Update pinning python

:information_source:
Bioconda has finished the [GCC7 migration](https://github.com/bioconda/bioconda-recipes/issues/13578). If you are dealing with C/C++ or Python package it can be that you need to rebuild other dependent packages. [Bioconda utils - update-pinning](https://bioconda.github.io/updating.html#updating-recipes-for-a-pinning-change) will assist you with that. If you have any questions please use [issue 13578](https://github.com/bioconda/bioconda-recipes/issues/13578).

----------------

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

Update pinning for python 3.7

### CODE REVIEW

**Comment by PertuyF** [comment]
@johanneskoester what do you think is better:

- simply remove the `numpy` pinning
- use another a version available for python3.7 (from 1.14 for conda-forge)
- use `pin_compatible('numpy')`

Likely there was a reason if you used `conda_build_config.yaml` when creating the recipe, and I am not sure I understand.

**Comment by PertuyF** [comment]
Build succeeds but CI fails with `cp: missing destination file operand after '/opt/host-conda-bld/linux-64'` error.

Any idea @bioconda/core ?

Details:

```
# Build steps...

done

# Test steps...

+ exit 0



Resource usage statistics from testing deepbinner:

   Process count: 1

   CPU time: unavailable

   Memory: 2.4M

   Disk usage: 12B

   Time elapsed: 0:00:02.0



TEST END: /opt/conda/conda-bld/linux-64/deepbinner-0.2.0-py35h24bf2e0_1.tar.bz2

Renaming work directory,  /opt/conda/conda-bld/deepbinner_1552489186551/work  to  /opt/conda/conda-bld/deepbinner_1552489186551/work_moved_deepbinner-0.2.0-py>=35h24bf2e0_1_linux-64_main_build_loop

# Automatic uploading is disabled

# If you want to upload package(s) to anaconda.org later, type:



anaconda upload /opt/conda/conda-bld/linux-64/deepbinner-0.2.0-py35h24bf2e0_1.tar.bz2



# To have conda build upload to anaconda.org automatically, use

# $ conda config --set anaconda_upload yes



anaconda_upload is not set.  Not uploading wheels: []

####################################################################################

Resource usage summary:



Total time: 0:21:56.4

CPU usage: sys=0:00:00.2, user=0:00:01.3

Maximum memory usage observed: 66.6M

Total disk usage observed (not including envs): 5.4K

cp: missing destination file operand after `/opt/host-conda-bld/linux-64'

Try `cp --help' for more information.



15:21:48 BIOCONDA ERROR BUILD FAILED recipes/deepbinner
15:21:49 BIOCONDA ERROR BUILD SUMMARY: of 2 recipes, 1 failed and 0 were skipped. Details of recipes and environments follow.
15:21:49 BIOCONDA ERROR BUILD SUMMARY: FAILED recipe recipes/deepbinner
Exited with code 1
```

**Comment by dpryan79** [comment]
I wonder why it's trying to build for python 3.5.

**Comment by dpryan79** [comment]
Ah, `python >=3.5` was likely the issue, I've changed that to `>3` and made it `noarch: python`. That should work better.

**Comment by PertuyF** [comment]
Oups, my fault! I didn't though it would affect the python pinning during the build process.
Thanks @dpryan79 !

**Pull request merged**
