### PR TITLE
add recipe for RFPlasmid

### PR DESCRIPTION
**Pull request by rpetit3**
This is a new recipe for [RFPlasmid](https://github.com/aldertzomer/RFPlasmid). It uses a wheel from PyPi to install and adds a helper script (`rfplasmid`) to the PATH. The helper script downloads a database then executes `rfplasmid.py`. To skip the database download, I also added `rfplasmid.py` to the PATH. This way `rfplasmid.py` could be used for tests.

I used these recipes as a reference [python-consensuscore2](https://github.com/bioconda/bioconda-recipes/tree/master/recipes/python-consensuscore2) & [plasflow](https://github.com/bioconda/bioconda-recipes/tree/master/recipes/plasflow) (installing from whl) and [abitamr](https://github.com/bioconda/bioconda-recipes/blob/80cee2612b9ceedf3b87d10adb84f36504efdf75/recipes/abritamr/meta.yaml#L10) (dealing with BLAKE2-SHA256)

Please let me know if there are any changes that should be made.

Thank you!
----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by rpetit3** [comment]
@bioconda-bot please fetch artifacts

**Comment by rpetit3** [comment]
Here's my testing:

```
(base) rpetit@staphopia:~/bactopia-dev/test-rfplasmid$ conda create -y -n test-rfplasmid -c https://134452-42372094-gh.circle-artifacts.com/0/tmp/artifacts/packages -c conda-forge -c bioconda rfplasmid
(base) rpetit@staphopia:~/bactopia-dev/test-rfplasmid$ conda activate test-rfplasmid
(test-rfplasmid) rpetit@staphopia:~/bactopia-dev/test-rfplasmid$ rfplasmid
Error; no arguments. Required to specificy --input and --species
usage: rfplasmid.py [-h] [--species SPECIES] [--input INPUT] [--specieslist]
                    [--jelly] [--out OUT] [--debug] [--training]
                    [--threads THREADS] [--version]

optional arguments:
  -h, --help         show this help message and exit
  --species SPECIES  define species (required)
  --input INPUT      directory with input fasta files (required)
  --specieslist      list of available species models
  --jelly            run jellyfish as kmer-count (faster)
  --out OUT          specify output directory
  --debug            no cleanup of intermediate files
  --training         trainings mode Random Forest
  --threads THREADS  specify number of threads to be used, default is max
                     available threads up to 16 threads
  --version          print version number
(test-rfplasmid) rpetit@staphopia:~/bactopia-dev/test-rfplasmid$ rfplasmid --specieslist


Available species models:
Bacillus
Borrelia
Burkholderia
Campylobacter
Clostridium
Corynebacterium
Cyanothece
Enterococcus
Francisella
Lactobacillus
Lactococcus
Legionella
Listeria
Pseudomonas
Rhizobium
Staphylococcus
Streptomyces
Vibrio
Xanthomonas
Enterobacteriaceae
Bacteria

(test-rfplasmid) rpetit@staphopia:~/bactopia-dev/test-rfplasmid$ checkm data setRoot /local/home/rpetit/miniconda3/envs/test-rfplasmid/checkm_data
[2020-12-17 16:01:40] INFO: CheckM v1.1.3
[2020-12-17 16:01:40] INFO: checkm data setRoot /local/home/rpetit/miniconda3/envs/test-rfplasmid/checkm_data
[2020-12-17 16:01:40] INFO: [CheckM - data] Check for database updates. [setRoot]

Path [/local/home/rpetit/miniconda3/envs/test-rfplasmid/checkm_data] exists and you have permission to write to this folder.
(re) creating manifest file (please be patient).

Path [/local/home/rpetit/miniconda3/envs/test-rfplasmid/checkm_data] exists and you have permission to write to this folder.
(re) creating manifest file (please be patient).

(test-rfplasmid) rpetit@staphopia:~/bactopia-dev/test-rfplasmid$ rfplasmid --species Staphylococcus --input ../test-20-samples/ERX514151/assembly/ --jelly --out ./test --threads 10


Start RFPlasmid, version 0.0.15
./test
copy original contig names
cleanup contig names
start Checkm
    Finished processing 1 of 1 (100.00%) bins.
    Finished parsing hits for 1 of 1 (100.00%) bins.
    Finished processing 1 of 1 (100.00%) bins.
    Finished processing 1 of 1 (100.00%) bins.
    Finished parsing hits for 1 of 1 (100.00%) bins.
Checkm done
start blast plasmiddb
/local/home/rpetit/miniconda3/envs/test-rfplasmid/lib/python3.6/site-packages/RFPlasmid/rfplasmid.py:149: FutureWarning: Columnar iteration over characters will be deprecated in future releases.
  df1['contig'], df1['gene'] = df1['contig_gene'].str.split('_', 1).str
blast plasmid genes done
start blast cge
blast cge genes done
count genes per contig done
/local/home/rpetit/miniconda3/envs/test-rfplasmid/lib/python3.6/site-packages/RFPlasmid/rfplasmid.py:208: FutureWarning: Columnar iteration over characters will be deprecated in future releases.
  df['contig'], df['gene'] = df['contig_gene'].str.split('_', 1).str
count SCMs per contig done
Start kmer count
You have selected kmer-counting with jellyfish
Jellyfish kmer-count done
Count contig length
count contig length ; done
Start merging contig files
Create df_files ; done
Start to add blast output to dataframe
/local/home/rpetit/miniconda3/envs/test-rfplasmid/lib/python3.6/site-packages/RFPlasmid/rfplasmid.py:362: FutureWarning: Columnar iteration over characters will be deprecated in future releases.
  df4['genome'], df4['contig'] = df4['source'].str.rsplit('_', 1).str
CSV file from dataframe ready in file outputdataframe.csv
Cleaning-up intermediate files
Start R
prediction mode

R version 4.0.3 (2020-10-10) -- "Bunny-Wunnies Freak Out"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-conda-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> #classifying
> Args <- commandArgs(TRUE)
> library(randomForest)
randomForest 4.6-14
Type rfNews() to see new features/changes/bug fixes.
> model<-paste(Args[2],"/",Args[1],".rfo",sep="")
> load(model)
> df<-read.table("outputdataframe.csv", sep=",", header=T, row.names=1)
> featurematrix <-df
> featurematrix$contigID <- NULL
> #notice the missing featurevector generation and the use of predict
> rf.classifications <- predict(rf,featurematrix)
> rf.votes <- predict(rf,featurematrix, type="vote")
> combined1 <- merge(rf.classifications,rf.votes,by="row.names")
> row.names(combined1)<-combined1$Row.names
> combined1$Row.names <-NULL
> colnames(combined1) <- c("prediction", "votes chromosomal", "votes plasmid")
> output <- merge(combined1,df,by="row.names")
> row.names(output)<-output$Row.names
> output$Row.names <-NULL
> write.csv(output[1:4], file="prediction.csv")
> write.csv(output, file="prediction_full.csv")
> save.image("classification.RData")
>
Prediction done

(test-rfplasmid) rpetit@staphopia:~/bactopia-dev/test-rfplasmid$ tree
.
└── test
    ├── classification.RData
    ├── outputdataframe.csv
    ├── prediction.csv
    └── prediction_full.csv

1 directory, 4 files

(test-rfplasmid) rpetit@staphopia:~/bactopia-dev/test-rfplasmid$ head test/prediction.csv
"","prediction","votes chromosomal","votes plasmid","contigID"
"skesa_1","c",0.5646,0.4354,"Contig_1_76.4286_pilon"
"skesa_10","c",0.9966,0.0034,"Contig_10_84.8202_pilon"
"skesa_11","c",0.991,0.009,"Contig_11_90.3372_pilon"
"skesa_12","c",0.8784,0.1216,"Contig_12_72.4541_pilon"
"skesa_13","c",0.5758,0.4242,"Contig_13_168.632_pilon"
"skesa_14","c",0.8032,0.1968,"Contig_14_69.0697_pilon"
"skesa_15","p",0.4884,0.5116,"Contig_15_88.4139_pilon"
"skesa_16","c",0.998,0.002,"Contig_16_80.1801_pilon"
"skesa_17","c",0.9374,0.0626,"Contig_17_63.9443_pilon"
```

I think everything runs as expected. The only thing thing to keep in mind is this command was required:
```
checkm data setRoot /local/home/rpetit/miniconda3/envs/test-rfplasmid/checkm_data
```

 I also had to update pysam due to a known issue with broken pinnings(https://github.com/bioconda/bioconda-recipes/issues/17212)

Otherwise I think everything is good to go.

**Comment by rpetit3** [comment]
@bioconda-bot  please fetch artifacts

**Comment by rpetit3** [comment]
Latest build with fixed pysam, works fine,
```
(base) rpetit@staphopia:~/bactopia-dev/test-rfplasmid$ conda create -n test-rfplasmid -c https://134459-42372094-gh.circle-artifacts.com/0/tmp/artifacts/packages -c conda-forge -c bioconda rfplasmid
(base) rpetit@staphopia:~/bactopia-dev/test-rfplasmid$ conda activate test-rfplasmid
(test-rfplasmid) rpetit@staphopia:~/bactopia-dev/test-rfplasmid$ checkm data setRoot /local/home/rpetit/miniconda3/envs/test-rfplasmid/checkm_data
[2020-12-17 17:12:46] INFO: CheckM v1.1.3
[2020-12-17 17:12:46] INFO: checkm data setRoot /local/home/rpetit/miniconda3/envs/test-rfplasmid/checkm_data
[2020-12-17 17:12:46] INFO: [CheckM - data] Check for database updates. [setRoot]

Path [/local/home/rpetit/miniconda3/envs/test-rfplasmid/checkm_data] exists and you have permission to write to this folder.
(re) creating manifest file (please be patient).

Path [/local/home/rpetit/miniconda3/envs/test-rfplasmid/checkm_data] exists and you have permission to write to this folder.
(re) creating manifest file (please be patient).
```

**Comment by rpetit3** [comment]
@BiocondaBot please add label

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Comment by dpryan79** [comment]
@bioconda-bot please merge and stop throwing errors

**Comment by rpetit3** [comment]
Thank you very much!

**Pull request merged**
