### PR TITLE
Update gromacswrapper to 0.8.2

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`gromacswrapper`](https://bioconda.github.io/recipes/gromacswrapper/README.html): **0.8.1** &rarr; **0.8.2**

[install with bioconda](http://bioconda.github.io/recipes/gromacswrapper/README.html) [Conda](https://anaconda.org/bioconda/gromacswrapper/files)

Info | Link
-----|-----
Recipe | [`recipes/gromacswrapper`](https://github.com//bioconda/bioconda-recipes/tree/bump/gromacswrapper/recipes/gromacswrapper) (click to view/edit other files)
Releases |[https://github.com/Becksteinlab/GromacsWrapper/tags](https://github.com/Becksteinlab/GromacsWrapper/tags)
Recipe Maintainer(s) | @simonbray
Author | `@Becksteinlab`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Review by simonbray — APPROVED** [review]

**Comment by simonbray** [comment]
@orbeckst please go ahead and merge if you are happy with the changes. If you like, you can also test the package locally before merging using: `conda install -c https://168080-42372094-gh.circle-artifacts.com/0/tmp/artifacts/packages gromacswrapper`

**Review by orbeckst — APPROVED** [review]
lgtm

**Comment by orbeckst** [comment]
I don't have write access so I can't merge.

**Comment by simonbray** [comment]
@bioconda-bot please merge

**Pull request merged**
