### PR TITLE
Added taxonlist.tsv

### PR DESCRIPTION
**Pull request by rasmusagren**
* [x] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by bgruening** [comment]
Thanks!

**Comment by rasmusagren** [comment]
@bgruening I have a question regarding how to do if a package depends on standard command line tools such as wget, git or gzip. Should they be explicitly added? For example, some functionality of this tool requires wget > 1.16 but it's not required for installing. Should it then be added?

**Comment by bgruening** [comment]
Yes. Everything needs to be added. Don't assume anything in the runtime and build time environment.

**Comment by rasmusagren** [comment]
Ok, thanks. Maybe it could be good to remove wget/bzip2/git/unzip from the bioconda docker image to make it more transparent when you're missing a dependency like this?

**Pull request merged**
