### PR TITLE
Add sequana_pipetools recipe

### PR DESCRIPTION
**Pull request by cokelaer**
This is a new recipe for the sequana_pipetools package linked to the Sequana project (NGS snakemake pipelines) already in bioconda.

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by rhpvorderman** [comment]
I don't see any bioinformatics algorithms here. 
Shouldn't this be in conda forge?

**Review by rhpvorderman — APPROVED** [review]
Looks good to me. 

This package is generalized so it might be better in conda-forge. On the other hand it is tightly coupled to sequana. Take your pick.

**Comment by cokelaer** [comment]
@rhpvorderman it is indeed tightly coupled to Sequana (NGS pipelines); It is also meant to be couple with incoming NGS pipelines. I'd rather keep it in bioconda for consistency. I'll wait for another reviewer comments.

**Comment by cokelaer** [comment]
@rhpvorderman  shall I do the merge myself. Not sure about the procedure to follow here ? cheers

**Comment by rhpvorderman** [comment]
You can do the merge yourself. No problem!
Please wait for another opinion on the conda-forge thing. I think it is okay, but I do not feel authorative enough to make the decision on my own.

**Pull request merged**
