### PR TITLE
Update braker2 to 2.1.5

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`braker2`](https://bioconda.github.io/recipes/braker2/README.html): **2.1.4** &rarr; **2.1.5**

[install with bioconda](http://bioconda.github.io/recipes/braker2/README.html) [Conda](https://anaconda.org/bioconda/braker2/files)

Info | Link
-----|-----
Recipe | [`recipes/braker2`](https://github.com//bioconda/bioconda-recipes/tree/bump/braker2/recipes/braker2) (click to view/edit other files)
Releases |[https://github.com/Gaius-Augustus/BRAKER/tags](https://github.com/Gaius-Augustus/BRAKER/tags)
Author | `@Gaius-Augustus`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by npavlovikj** [comment]
Please **DO NOT** merge. There have been few major changes and dependencies added in the new version, https://github.com/Gaius-Augustus/BRAKER/issues/22#issuecomment-589241610.

**Comment by npavlovikj** [comment]
So, the new version of BRAKER2 has "ProtHint" as a dependency. The license for "ProtHint" says:
```
Licensee may not:
a) transfer, distribute, lease or sub-license the Product."
```
so I can not create a conda package for it, right @dpryan79 ?

**Comment by marcelm** [comment]
In my unqualified opinion, the license quite clearly prohibits re-distribution, so this can indeed not be packaged up. In a similar case, I’ve contacted the authors and asked for permission.

**Comment by dpryan79** [comment]
Correct, that can’t be put in conda.

**Comment by npavlovikj** [comment]
@BiocondaBot please fetch artifacts

**Comment by npavlovikj** [comment]
Thank you for the clarification @marcelm and @dpryan79 , I really appreciate it! I will go ahead and merge this recipe as it is then.

**Comment by npavlovikj** [comment]
@BiocondaBot please merge

**Pull request merged**
