### PR TITLE
Update graphicsmagick

### PR DESCRIPTION
**Pull request by mmiladi**
* [ ] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by mmiladi** [comment]
@bgruening The test doesn't fail on condaforge/linux-anvil docker. Do u have an idea why?

**Comment by bgruening** [comment]
This seems to be the error :(
```
/bin/grep: /opt/conda/conda-bld/recipe_1496683832579/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/libXau.la: No such file or directory
/bin/sed: can't read /opt/conda/conda-bld/recipe_1496683832579/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/libXau.la: No such file or directory
libtool:   error: '/opt/conda/conda-bld/recipe_1496683832579/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/libXau.la' is not a valid libtool archive
```

**Comment by mmiladi** [comment]
@bgruening looks good now?

**Comment by bgruening** [comment]
Seems, so. I'm just wondering if this is a good approach. Should we skip this x11 stuff via some compile flag? Your decision. Not sure if the X11 features are useful.

**Comment by mmiladi** [comment]
In fact the test passed before adding X11. I added it because of this paragraph :  http://www.graphicsmagick.org/README.html
```
GraphicsMagick requires an X server for the 'display', 'animate', and 'import' functions to work properly. Unix systems usually provide an X server as part of their standard installation. For MacOS-X, X11 is a system install time option.
```

**Comment by mmiladi** [comment]
So idk, but if you think it's overkill we can skip x11 dependency.

**Comment by bgruening** [comment]
ok!

**Comment by mmiladi** [comment]
Thanks @bgruening !

**Pull request merged**
