### PR TITLE
Remove salmon from the blacklist

### PR DESCRIPTION
**Pull request by lparsons**
* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [X] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [X] This PR does something else (explain below).
Remove salmon from the blacklist

### CODE REVIEW

**Comment by lparsons** [comment]
Hmmm, for some reason the CircleCI checks didn't seem to realize that `salmon` was removed from the blacklist. Am I missing something or is something broken?

**Comment by bgruening** [comment]
See here: https://github.com/bioconda/bioconda-recipes/pull/9943

**Comment by lparsons** [comment]
Thanks for the reference @bgruening, I was looking for that... I really just wanted to see why it was blacklisted to see if I could help. I suppose I can just leave that all to you guys. I'm working on some updates to the galaxy wrapper, so I guess I'll target 0.10.2 for now and hold off on 0.11 unless #9943 gets resolved.

**Comment by bgruening** [comment]
I'm not sure I can help @rob-p much with the OSX error. Maybe we skip OSX for now?

**Comment by lparsons** [comment]
I'm fine with skipping OSX for now, it would be useful to have 0.11 on Linux at least. I'm not really sure where the limitation is, but it seems maybe bioconda's build system isn't quite able to be flexible enough atm to meet the specific needs of salmon?

**Comment by rob-p** [comment]
I agree it would be useful to have a linux build for 0.11.0, since it's a non-trivial upgrade from 0.10.2.  I'm not quite sure what the issue with building on OSX is.  Previously (before the migration to cb3), there was an OSX related issue that was resolved by telling the build it needed llvm >= 4.0, which resolved the issue.  However, it seems that in the midst of the migration, such a specification isn't quite possible?

**Pull request closed without merging**
