### PR TITLE
Add Recipe smctc

### PR DESCRIPTION
**Pull request by dfornika**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

This is a dependency for [sts](https://github.com/bioconda/bioconda-recipes/pull/5855). I'm submitting it here (not conda-forge) because it's a non-standard fork of the [canonical library](https://www2.warwick.ac.uk/fac/sci/statistics/staff/academic-research/johansen/smctc/)

### CODE REVIEW

**Comment by cbrueffer** [comment]
Hi Dan, this looks non-biology specific and may be more appropriate for conda-forge? Even the summary says it's "very general" :-) What do you think?

**Comment by cbrueffer** [comment]
Sorry, missed the text in the PR where you actually mention why you submit it here.

**Comment by bgruening** [comment]
Can you add the info about the non-standard fork as extras/notes or somewhere in the code as comments?

**Comment by cbrueffer** [comment]
I think it would be good to at least rename the package so it doesn't block the smctc name for the canonical package (maybe sts-smctc or similar?), and also give the homepage of the fork and not the original package. Otherwise it's very easy to confuse the two.

**Comment by dfornika** [comment]
Thanks for the feedback. I'm going to have to prepare a similar package for `lcfit` which is also used in `sts`.

https://github.com/OnlinePhylo/sts/tree/master/lib
https://github.com/matsengrp/lcfit

**Comment by johanneskoester** [comment]
Thanks!

**Pull request merged**
