### PR TITLE
Recipe inconsistent due to matplotlib-base. Back to matplotlib

### PR DESCRIPTION
**Pull request by david-castillo**
I've just tried to conda install my new recipe but I got plenty of inconsistencies.
Installing each dependency individually matplotlib-base failed ... could it be that matplotlib-base is only for py3? My package is py2k only (for the moment)

Regards

----

> Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences**
      (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

> Everyone has access to the following BiocondaBot commands, which can be given in a comment:
>
>  * `@BiocondaBot please update` will cause the BiocondaBot to merge the master branch into a PR
>  * `@BiocondaBot please add label` will add the `please review & merge` label.
>  * `@BiocondaBot please fetch artifacts` will post links to packages and docker containers built by the CI system. You can use this to test packages locally before merging.
>
> For members of the Bioconda project, the following command is also available:
>
>  * `@BiocondaBot please merge` will cause packages/containers to be uploaded and a PR merged. Someone must approve a PR first! This has the benefit of not wasting CI build time required by manually merging PRs.
>
> If you have questions, please post them in gitter or ping `@bioconda/core` in a comment (if you are not able to directly ping `@bioconda/core` then the bot will repost your comment and enable pinging).

### CODE REVIEW

**Comment by david-castillo** [comment]
@BiocondaBot please fetch artifacts

**Comment by david-castillo** [comment]
@BiocondaBot please add label

**Comment by marcelm** [comment]
What inconsistencies do you get exactly? I could run `conda create -n tadbit tadbit` and also `conda create -n tadbit tadbit python=2.7` without any problems, and the tests that were run during the inital PR obviously also did not find any problems.

We need to figure this out because I would like to replace `matplotlib` with `matplotlib-base` by default in all recipes.

**Comment by david-castillo** [comment]
`conda create --name conda_tadbit`
`conda install tadbit`

`Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                               
                                                                                                                                     
UnsatisfiableError: The following specifications were found                                                                          
to be incompatible with the existing python installation in your environment:

Specifications:

  - pysam -> python[version='>=3.8,<3.9.0a0']

Your python: python[version='>=2.7,<2.8.0a0']

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

The following specifications were found to be incompatible with each other:



Package wheel conflicts for:
pysam -> python[version='>=3.6,<3.7.0a0'] -> pip -> wheel
matplotlib-base -> python[version='>=3.8,<3.9.0a0'] -> pip -> wheel
numpy -> python[version='>=2.7,<2.8.0a0'] -> pip -> wheel
h5py -> python[version='>=3.6,<3.7.0a0'] -> pip -> wheel
scipy -> python[version='>=2.7,<2.8.0a0'] -> pip -> wheel
python[version='>=2.7,<2.8.0a0'] -> pip -> wheel
mcl -> blast -> boost -> python[version='>=3.8,<3.9.0a0'] -> pip -> wheel
Package python-dateutil conflicts for:
pysam -> bcftools=1.9 -> matplotlib -> python-dateutil
matplotlib-base -> python-dateutil
Package ca-certificates conflicts for:
numpy -> python[version='>=2.7,<2.8.0a0'] -> ca-certificates
pysam -> python[version='>=3.6,<3.7.0a0'] -> ca-certificates
h5py -> python[version='>=3.6,<3.7.0a0'] -> ca-certificates
matplotlib-base -> python[version='>=3.8,<3.9.0a0'] -> openssl[version='>=1.0.2o,<1.0.3a'] -> ca-certificates
python[version='>=2.7,<2.8.0a0'] -> ca-certificates
scipy -> python[version='>=2.7,<2.8.0a0'] -> ca-certificates
mcl -> blast -> boost -> python[version='>=3.8,<3.9.0a0'] -> ca-certificates
Package setuptools conflicts for:
scipy -> python[version='>=2.7,<2.8.0a0'] -> pip -> setuptools
mcl -> blast -> boost -> python[version='>=3.8,<3.9.0a0'] -> pip -> setuptools
python[version='>=2.7,<2.8.0a0'] -> pip -> setuptools
numpy -> python[version='>=2.7,<2.8.0a0'] -> pip -> setuptools
h5py -> python[version='>=3.6,<3.7.0a0'] -> pip -> setuptools
matplotlib-base -> setuptools
pysam -> bcftools=1.9 -> matplotlib -> setuptools
Package pip conflicts for:
matplotlib-base -> python[version='>=3.8,<3.9.0a0'] -> pip
pysam -> python[version='>=3.6,<3.7.0a0'] -> pip
scipy -> python[version='>=2.7,<2.8.0a0'] -> pip
mcl -> blast -> boost -> python[version='>=3.8,<3.9.0a0'] -> pip
h5py -> python[version='>=3.6,<3.7.0a0'] -> pip
python[version='>=2.7,<2.8.0a0'] -> pip
numpy -> python[version='>=2.7,<2.8.0a0'] -> pip
Package certifi conflicts for:
pysam -> bcftools=1.9 -> matplotlib -> setuptools -> certifi[version='>=2016.09|>=2016.9.26']
scipy -> python[version='>=2.7,<2.8.0a0'] -> pip -> setuptools -> certifi[version='>=2016.09|>=2016.9.26']
numpy -> python[version='>=2.7,<2.8.0a0'] -> pip -> setuptools -> certifi[version='>=2016.09|>=2016.9.26']
h5py -> python[version='>=3.6,<3.7.0a0'] -> pip -> setuptools -> certifi[version='>=2016.09|>=2016.9.26']
python[version='>=2.7,<2.8.0a0'] -> pip -> setuptools -> certifi[version='>=2016.09|>=2016.9.26']
matplotlib-base -> setuptools -> certifi[version='>=2016.09|>=2016.9.26']
mcl -> blast -> boost -> python[version='>=3.8,<3.9.0a0'] -> pip -> setuptools -> certifi[version='>=2016.09|>=2016.9.26']
`

**Comment by david-castillo** [comment]
`conda create -n conda_tadbit python=2.7
conda activate conda_tadbit`

Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                               

UnsatisfiableError: The following specifications were found to be incompatible with each other:



Package sqlite conflicts for:
python=2.7 -> sqlite[version='>=3.20.1,<4.0a0|>=3.22.0,<4.0a0|>=3.23.1,<4.0a0|>=3.25.2,<4.0a0|>=3.25.3,<4.0a0|>=3.27.2,<4.0a0|>=3.29.0,<4.0a0|>=3.30.0,<4.0a0']
Package pysam conflicts for:
tadbit -> pysam
Package ncurses conflicts for:
python=2.7 -> ncurses[version='6.0.*|>=6.0,<7.0a0|>=6.1,<7.0a0']
Package mcl conflicts for:
tadbit -> mcl
Package zlib conflicts for:
python=2.7 -> zlib[version='>=1.2.11,<1.3.0a0']
Package openssl conflicts for:
python=2.7 -> openssl[version='1.0.*|1.0.*,>=1.0.2l,<1.0.3a|>=1.0.2m,<1.0.3a|>=1.0.2n,<1.0.3a|>=1.0.2o,<1.0.3a|>=1.0.2p,<1.0.3a|>=1.1.1a,<1.1.2a|>=1.1.1b,<1.1.2a|>=1.1.1c,<1.1.2a|>=1.1.1d,<1.1.2a']
Package libffi conflicts for:
python=2.7 -> libffi[version='3.2.*|>=3.2.1,<4.0a0']
Package pip conflicts for:
python=2.7 -> pip
Package libgcc-ng conflicts for:
tadbit -> libgcc-ng[version='>=7.3.0']
python=2.7 -> libgcc-ng[version='>=7.2.0|>=7.3.0']
Package ca-certificates conflicts for:
python=2.7 -> ca-certificates
Package matplotlib-base conflicts for:
tadbit -> matplotlib-base
Package scipy conflicts for:
tadbit -> scipy
Package h5py conflicts for:
tadbit -> h5py
Package libstdcxx-ng conflicts for:
python=2.7 -> libstdcxx-ng[version='>=7.2.0|>=7.3.0']
tadbit -> libstdcxx-ng[version='>=7.3.0']
Package readline conflicts for:
python=2.7 -> readline[version='7.*|>=7.0,<8.0a0']
Package numpy conflicts for:
tadbit -> numpy
Package gem3-mapper conflicts for:
tadbit -> gem3-mapper
Package tk conflicts for:
python=2.7 -> tk[version='8.6.*|>=8.6.7,<8.7.0a0|>=8.6.8,<8.7.0a0']

**Comment by marcelm** [comment]
So the first command you gave tries to install `tadbit` into the base environment. If you actually did use that command, it is somewhat expected that it fails because you’ll likely have other things installed in there already. Generally, it’s a good idea not to “pollute” the base environment and to create new environments for everything. Then it’s easy to delete the environment and start from scratch if necessary.

The second command actually works for me. What is in your channels list? Have you tried updating Conda? (`conda update -n base conda`)

Whatever the problem is, it shouldn’t be to `matplotlib-base` because `matplotlib` is just a meta-package that depends on `matplotlib-base` and `pyqt`. So because there are fewer dependencies than before, there should be less potential for conflicts.

Can you try the command that I gave above (but of course change the environment name if necessary):
```
conda create -n tadbit tadbit python=2.7
```

**Comment by david-castillo** [comment]
Yes, sorry. There's a missing line in the first case to activate the new environment. 
I tried always with a clean environment, even in another computer.

For the command you gave me:

`conda update -n base conda`
`conda create -n new_tadbit tadbit python=2.7`

Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                               

UnsatisfiableError: The following specifications were found to be incompatible with each other:



Package pysam conflicts for:
tadbit -> pysam
Package sqlite conflicts for:
python=2.7 -> sqlite[version='>=3.20.1,<4.0a0|>=3.22.0,<4.0a0|>=3.23.1,<4.0a0|>=3.25.2,<4.0a0|>=3.25.3,<4.0a0|>=3.27.2,<4.0a0|>=3.29.0,<4.0a0|>=3.30.0,<4.0a0']
Package mcl conflicts for:
tadbit -> mcl
Package pip conflicts for:
python=2.7 -> pip
Package python conflicts for:
tadbit -> python[version='>=2.7,<2.8.0a0']
Package zlib conflicts for:
python=2.7 -> zlib[version='>=1.2.11,<1.3.0a0']
Package openssl conflicts for:
python=2.7 -> openssl[version='1.0.*|1.0.*,>=1.0.2l,<1.0.3a|>=1.0.2m,<1.0.3a|>=1.0.2n,<1.0.3a|>=1.0.2o,<1.0.3a|>=1.0.2p,<1.0.3a|>=1.1.1a,<1.1.2a|>=1.1.1b,<1.1.2a|>=1.1.1c,<1.1.2a|>=1.1.1d,<1.1.2a']
Package ncurses conflicts for:
python=2.7 -> ncurses[version='6.0.*|>=6.0,<7.0a0|>=6.1,<7.0a0']
Package ca-certificates conflicts for:
python=2.7 -> ca-certificates
Package libgcc-ng conflicts for:
python=2.7 -> libgcc-ng[version='>=7.2.0|>=7.3.0']
tadbit -> libgcc-ng[version='>=7.3.0']
Package libffi conflicts for:
python=2.7 -> libffi[version='3.2.*|>=3.2.1,<4.0a0']
Package tk conflicts for:
python=2.7 -> tk[version='8.6.*|>=8.6.7,<8.7.0a0|>=8.6.8,<8.7.0a0']
Package scipy conflicts for:
tadbit -> scipy
Package h5py conflicts for:
tadbit -> h5py
Package libstdcxx-ng conflicts for:
tadbit -> libstdcxx-ng[version='>=7.3.0']
python=2.7 -> libstdcxx-ng[version='>=7.2.0|>=7.3.0']
Package readline conflicts for:
python=2.7 -> readline[version='7.*|>=7.0,<8.0a0']
Package numpy conflicts for:
tadbit -> numpy
Package gem3-mapper conflicts for:
tadbit -> gem3-mapper
Package matplotlib-base conflicts for:
tadbit -> matplotlib-base

**Comment by david-castillo** [comment]
Ok. I got it.
conda-forge was missing in my channel list. I added and worked.

Sorry!

**Comment by marcelm** [comment]
Oh great, that explains it :-)

(Do you want to close this PR?)

**Comment by david-castillo** [comment]
Thanks for the help.
Yes, please, this can be closed.

El 2 feb. 2020 23:26, Marcel Martin <notifications@github.com> escribió:

Oh great, that explains it :-)

(Do you want to close this PR?)

**Pull request closed without merging**
