### PR TITLE
Update dinf to 0.4.0

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`dinf`](https://bioconda.github.io/recipes/dinf/README.html): **0.3.0** &rarr; **0.4.0**

[install with bioconda](http://bioconda.github.io/recipes/dinf/README.html) [Conda](https://anaconda.org/bioconda/dinf/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/dinf`](https://github.com//bioconda/bioconda-recipes/tree/bump/dinf/recipes/dinf) (click to view/edit other files)
Summary | discriminator-based inference for population genetics
Home | [https://github.com/RacimoLab/dinf](https://github.com/RacimoLab/dinf)
Releases |[https://pypi.org/pypi/dinf/json](https://pypi.org/pypi/dinf/json)
Recipe Maintainer(s) | @grahamgower

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Review by grahamgower — APPROVED** [review]

**Comment by grahamgower** [comment]
@BiocondaBot please merge

**Comment by grahamgower** [comment]
> Sorry, this PR cannot be merged at this time.

But I'm shown as the recipe maintainer, and I approved the pr. Bad bot!

**Review by grahamgower — APPROVED** [review]

**Comment by grahamgower** [comment]
@BiocondaBot please add label

**Review by esteinig — APPROVED** [review]

**Comment by esteinig** [comment]
@BiocondaBot please merge

**Comment by esteinig** [comment]
Apologies, might need an explanation from one of the core people - new to this, so not quite sure what' going on

**Review by mjsteinbaugh — APPROVED** [review]

**Pull request merged**
