### PR TITLE
Add metacoag v1.1

### PR DESCRIPTION
**Pull request by Vini2**
Describe your pull request here

This PR adds [`metacoag`](https://github.com/metagentools/MetaCoAG) (MetaCoAG: Binning Metagenomic Contigs via Composition, Coverage and Assembly Graphs) to bioconda. MetaCoAG is a metagenomic contig binning tool and is implemented in python.

Mallawaarachchi, V., Lin, Y., 2022. MetaCoAG: Binning Metagenomic Contigs via Composition, Coverage and Assembly Graphs. In: Pe’er, I. (Ed.), [Research in Computational Molecular Biology. RECOMB 2022. Lecture Notes in Computer Science](https://doi.org/10.1007/978-3-031-04749-7_5), 13278. Springer, Cham.

---

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by Vini2** [comment]
@BiocondaBot please add label

**Comment by Vini2** [comment]
@BiocondaBot please fetch artifacts

**Comment by Vini2** [comment]
@BiocondaBot please fetch artifacts

**Comment by Vini2** [comment]
# Testing

## Conda
```
conda install -c packages metacoag-1.1-pyhfa5458b_0.tar.bz2

which metacoag
/Users/vijinimallawaarachchi/anaconda3/envs/metacoagpy_test/bin/metacoag

metacoag --version
metacoag 1.1

metacoag --help 
usage: metacoag [-h] --assembler ASSEMBLER --graph GRAPH --contigs CONTIGS --abundance ABUNDANCE [--paths PATHS] --output OUTPUT [--hmm HMM] [--prefix PREFIX]
                [--min_length MIN_LENGTH] [--p_intra P_INTRA] [--p_inter P_INTER] [--d_limit D_LIMIT] [--depth DEPTH] [--mg_threshold MG_THRESHOLD]
                [--bin_mg_threshold BIN_MG_THRESHOLD] [--min_bin_size MIN_BIN_SIZE] [--delimiter DELIMITER] [--nthreads NTHREADS] [-v]

MetaCoAG is a metagenomic contig binning tool that makes use of the connectivity information found in assembly graphs, apart from the composition and coverage
information. MetaCoAG makes use of single-copy marker genes along with a graph matching technique and a label propagation technique to bin contigs.

optional arguments:
  -h, --help            show this help message and exit
  --assembler ASSEMBLER
                        name of the assembler used. (Supports SPAdes, MEGAHIT and Flye)
  --graph GRAPH         path to the assembly graph file
  --contigs CONTIGS     path to the contigs file
  --abundance ABUNDANCE
                        path to the abundance file
  --paths PATHS         path to the contigs.paths (metaSPAdes) or assembly.info (metaFlye) file
  --output OUTPUT       path to the output folder
  --hmm HMM             path to marker.hmm file. [default: auxiliary/marker.hmm]
  --prefix PREFIX       prefix for the output file
  --min_length MIN_LENGTH
                        minimum length of contigs to consider for binning. [default: 1000]
  --p_intra P_INTRA     minimum probability of an edge matching to assign to the same bin. [default: 0.1]
  --p_inter P_INTER     maximum probability of an edge matching to create a new bin. [default: 0.01]
  --d_limit D_LIMIT     distance limit for contig matching. [default: 20]
  --depth DEPTH         depth to consider for label propagation. [default: 10]
  --mg_threshold MG_THRESHOLD
                        length threshold to consider marker genes. [default: 0.5]
  --bin_mg_threshold BIN_MG_THRESHOLD
                        minimum fraction of marker genes that should be present in a bin. [default: 0.33333]
  --min_bin_size MIN_BIN_SIZE
                        minimum size of a bin to output in base pairs. [default: 200000]
  --delimiter DELIMITER
                        delimiter for output results. Supports a comma (,), a semicolon (;), a tab ($'\t'), a space (" ") and a pipe (|) [default: , (comma)]
  --nthreads NTHREADS   number of threads to use. [default: 8]
  -v, --version         show program's version number and exit
```

**Comment by Vini2** [comment]
# Testing

## Conda
```
conda install -c packages metacoag-1.1-pyhfa5458b_0.tar.bz2

which metacoag
/Users/vijinimallawaarachchi/anaconda3/envs/metacoagpy_test/bin/metacoag

metacoag --version
metacoag 1.1

metacoag --help 
usage: metacoag [-h] --assembler ASSEMBLER --graph GRAPH --contigs CONTIGS --abundance ABUNDANCE [--paths PATHS] --output OUTPUT [--hmm HMM] [--prefix PREFIX]
                [--min_length MIN_LENGTH] [--p_intra P_INTRA] [--p_inter P_INTER] [--d_limit D_LIMIT] [--depth DEPTH] [--mg_threshold MG_THRESHOLD]
                [--bin_mg_threshold BIN_MG_THRESHOLD] [--min_bin_size MIN_BIN_SIZE] [--delimiter DELIMITER] [--nthreads NTHREADS] [-v]

MetaCoAG is a metagenomic contig binning tool that makes use of the connectivity information found in assembly graphs, apart from the composition and coverage
information. MetaCoAG makes use of single-copy marker genes along with a graph matching technique and a label propagation technique to bin contigs.

optional arguments:
  -h, --help            show this help message and exit
  --assembler ASSEMBLER
                        name of the assembler used. (Supports SPAdes, MEGAHIT and Flye)
  --graph GRAPH         path to the assembly graph file
  --contigs CONTIGS     path to the contigs file
  --abundance ABUNDANCE
                        path to the abundance file
  --paths PATHS         path to the contigs.paths (metaSPAdes) or assembly.info (metaFlye) file
  --output OUTPUT       path to the output folder
  --hmm HMM             path to marker.hmm file. [default: auxiliary/marker.hmm]
  --prefix PREFIX       prefix for the output file
  --min_length MIN_LENGTH
                        minimum length of contigs to consider for binning. [default: 1000]
  --p_intra P_INTRA     minimum probability of an edge matching to assign to the same bin. [default: 0.1]
  --p_inter P_INTER     maximum probability of an edge matching to create a new bin. [default: 0.01]
  --d_limit D_LIMIT     distance limit for contig matching. [default: 20]
  --depth DEPTH         depth to consider for label propagation. [default: 10]
  --mg_threshold MG_THRESHOLD
                        length threshold to consider marker genes. [default: 0.5]
  --bin_mg_threshold BIN_MG_THRESHOLD
                        minimum fraction of marker genes that should be present in a bin. [default: 0.33333]
  --min_bin_size MIN_BIN_SIZE
                        minimum size of a bin to output in base pairs. [default: 200000]
  --delimiter DELIMITER
                        delimiter for output results. Supports a comma (,), a semicolon (;), a tab ($'\t'), a space (" ") and a pipe (|) [default: , (comma)]
  --nthreads NTHREADS   number of threads to use. [default: 8]
  -v, --version         show program's version number and exit
```

### Test run

Testing on test data.

Command:
```
metacoag --assembler spades --graph assembly_graph_with_scaffolds.gfa --contigs contigs.fasta --paths contigs.paths --abundance coverm_mean_coverage.tsv --output ./
```
Output:
```
2022-08-05 12:52:22,082 - INFO - Welcome to MetaCoAG: Binning Metagenomic Contigs via Composition, Coverage and Assembly Graphs.
2022-08-05 12:52:22,083 - INFO - Input arguments: 
2022-08-05 12:52:22,083 - INFO - Assembler used: spades
2022-08-05 12:52:22,083 - INFO - Contigs file: contigs.fasta
2022-08-05 12:52:22,083 - INFO - Assembly graph file: assembly_graph_with_scaffolds.gfa
2022-08-05 12:52:22,083 - INFO - Contig paths file: contigs.paths
2022-08-05 12:52:22,083 - INFO - Abundance file: coverm_mean_coverage.tsv
2022-08-05 12:52:22,083 - INFO - Final binning output file: ./
2022-08-05 12:52:22,083 - INFO - Minimum length of contigs to consider: 1000
2022-08-05 12:52:22,083 - INFO - Depth to consider for label propagation: 10
2022-08-05 12:52:22,083 - INFO - p_intra: 0.1
2022-08-05 12:52:22,084 - INFO - p_inter: 0.01
2022-08-05 12:52:22,084 - INFO - mg_threshold: 0.5
2022-08-05 12:52:22,084 - INFO - bin_mg_threshold: 0.33333
2022-08-05 12:52:22,084 - INFO - min_bin_size: 200000 base pairs
2022-08-05 12:52:22,084 - INFO - d_limit: 20
2022-08-05 12:52:22,084 - INFO - Number of threads: 8
2022-08-05 12:52:22,084 - INFO - MetaCoAG started
2022-08-05 12:52:22,096 - INFO - Total number of contigs available: 519
2022-08-05 12:52:22,143 - INFO - Total number of edges in the assembly graph: 1065
2022-08-05 12:52:22,144 - INFO - Total isolated contigs in the assembly graph: 1
2022-08-05 12:52:22,144 - INFO - Obtaining lengths and coverage values of contigs
2022-08-05 12:52:22,355 - INFO - Total long contigs: 251
2022-08-05 12:52:22,355 - INFO - Total isolated long contigs in the assembly graph: 1
2022-08-05 12:52:22,355 - INFO - Obtaining tetranucleotide frequencies of contigs
2022-08-05 12:52:40,633 - INFO - Scanning for single-copy marker genes
2022-08-05 12:52:40,633 - INFO - .hmmout file already exists
2022-08-05 12:52:40,633 - INFO - Obtaining contigs with single-copy marker genes
2022-08-05 12:52:40,639 - INFO - Number of contigs containing single-copy marker genes: 87
2022-08-05 12:52:40,639 - INFO - Determining contig counts for each single-copy marker gene
2022-08-05 12:52:40,640 - INFO - Initialising bins
2022-08-05 12:52:40,640 - INFO - Matching and assigning contigs with single-copy marker genes to bins
2022-08-05 12:52:40,933 - INFO - Further assigning contigs with single-copy marker genes
2022-08-05 12:52:40,975 - INFO - Propagating labels to connected vertices of unlabelled long contigs
2022-08-05 12:52:45,743 - INFO - Further propagating labels to vertices of unlabelled long contigs
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 101/101 [00:00<00:00, 333300.32it/s]
2022-08-05 12:52:45,772 - INFO - Further propagating labels to connected vertices of unlabelled long contigs
2022-08-05 12:52:47,180 - INFO - Elapsed time: 25.09567618370056 seconds
2022-08-05 12:52:47,198 - INFO - Writing the Final Binning result to file
Splitting contigs into bins: 519it [00:00, 2886.62it/s]
2022-08-05 12:52:47,452 - INFO - Producing 5 bins...
2022-08-05 12:52:47,453 - INFO - Final binning results can be found in ./bins/
2022-08-05 12:52:47,453 - INFO - Thank you for using MetaCoAG!
```

**Comment by Vini2** [comment]
# Testing

## Conda
```
conda install -c packages metacoag-1.1-pyhfa5458b_0.tar.bz2

which metacoag
/Users/vijinimallawaarachchi/anaconda3/envs/metacoagpy_test/bin/metacoag

metacoag --version
metacoag 1.1

metacoag --help 
usage: metacoag [-h] --assembler ASSEMBLER --graph GRAPH --contigs CONTIGS --abundance ABUNDANCE [--paths PATHS] --output OUTPUT [--hmm HMM] [--prefix PREFIX]
                [--min_length MIN_LENGTH] [--p_intra P_INTRA] [--p_inter P_INTER] [--d_limit D_LIMIT] [--depth DEPTH] [--mg_threshold MG_THRESHOLD]
                [--bin_mg_threshold BIN_MG_THRESHOLD] [--min_bin_size MIN_BIN_SIZE] [--delimiter DELIMITER] [--nthreads NTHREADS] [-v]

MetaCoAG is a metagenomic contig binning tool that makes use of the connectivity information found in assembly graphs, apart from the composition and coverage
information. MetaCoAG makes use of single-copy marker genes along with a graph matching technique and a label propagation technique to bin contigs.

optional arguments:
  -h, --help            show this help message and exit
  --assembler ASSEMBLER
                        name of the assembler used. (Supports SPAdes, MEGAHIT and Flye)
  --graph GRAPH         path to the assembly graph file
  --contigs CONTIGS     path to the contigs file
  --abundance ABUNDANCE
                        path to the abundance file
  --paths PATHS         path to the contigs.paths (metaSPAdes) or assembly.info (metaFlye) file
  --output OUTPUT       path to the output folder
  --hmm HMM             path to marker.hmm file. [default: auxiliary/marker.hmm]
  --prefix PREFIX       prefix for the output file
  --min_length MIN_LENGTH
                        minimum length of contigs to consider for binning. [default: 1000]
  --p_intra P_INTRA     minimum probability of an edge matching to assign to the same bin. [default: 0.1]
  --p_inter P_INTER     maximum probability of an edge matching to create a new bin. [default: 0.01]
  --d_limit D_LIMIT     distance limit for contig matching. [default: 20]
  --depth DEPTH         depth to consider for label propagation. [default: 10]
  --mg_threshold MG_THRESHOLD
                        length threshold to consider marker genes. [default: 0.5]
  --bin_mg_threshold BIN_MG_THRESHOLD
                        minimum fraction of marker genes that should be present in a bin. [default: 0.33333]
  --min_bin_size MIN_BIN_SIZE
                        minimum size of a bin to output in base pairs. [default: 200000]
  --delimiter DELIMITER
                        delimiter for output results. Supports a comma (,), a semicolon (;), a tab ($'\t'), a space (" ") and a pipe (|) [default: , (comma)]
  --nthreads NTHREADS   number of threads to use. [default: 8]
  -v, --version         show program's version number and exit
```

### Test run

Testing on test data.

Command:
```
metacoag --assembler spades --graph assembly_graph_with_scaffolds.gfa --contigs contigs.fasta --paths contigs.paths --abundance coverm_mean_coverage.tsv --output ./
```
Output:
```
2022-08-05 12:52:22,082 - INFO - Welcome to MetaCoAG: Binning Metagenomic Contigs via Composition, Coverage and Assembly Graphs.
2022-08-05 12:52:22,083 - INFO - Input arguments: 
2022-08-05 12:52:22,083 - INFO - Assembler used: spades
2022-08-05 12:52:22,083 - INFO - Contigs file: contigs.fasta
2022-08-05 12:52:22,083 - INFO - Assembly graph file: assembly_graph_with_scaffolds.gfa
2022-08-05 12:52:22,083 - INFO - Contig paths file: contigs.paths
2022-08-05 12:52:22,083 - INFO - Abundance file: coverm_mean_coverage.tsv
2022-08-05 12:52:22,083 - INFO - Final binning output file: ./
2022-08-05 12:52:22,083 - INFO - Minimum length of contigs to consider: 1000
2022-08-05 12:52:22,083 - INFO - Depth to consider for label propagation: 10
2022-08-05 12:52:22,083 - INFO - p_intra: 0.1
2022-08-05 12:52:22,084 - INFO - p_inter: 0.01
2022-08-05 12:52:22,084 - INFO - mg_threshold: 0.5
2022-08-05 12:52:22,084 - INFO - bin_mg_threshold: 0.33333
2022-08-05 12:52:22,084 - INFO - min_bin_size: 200000 base pairs
2022-08-05 12:52:22,084 - INFO - d_limit: 20
2022-08-05 12:52:22,084 - INFO - Number of threads: 8
2022-08-05 12:52:22,084 - INFO - MetaCoAG started
2022-08-05 12:52:22,096 - INFO - Total number of contigs available: 519
2022-08-05 12:52:22,143 - INFO - Total number of edges in the assembly graph: 1065
2022-08-05 12:52:22,144 - INFO - Total isolated contigs in the assembly graph: 1
2022-08-05 12:52:22,144 - INFO - Obtaining lengths and coverage values of contigs
2022-08-05 12:52:22,355 - INFO - Total long contigs: 251
2022-08-05 12:52:22,355 - INFO - Total isolated long contigs in the assembly graph: 1
2022-08-05 12:52:22,355 - INFO - Obtaining tetranucleotide frequencies of contigs
2022-08-05 12:52:40,633 - INFO - Scanning for single-copy marker genes
2022-08-05 12:52:40,633 - INFO - .hmmout file already exists
2022-08-05 12:52:40,633 - INFO - Obtaining contigs with single-copy marker genes
2022-08-05 12:52:40,639 - INFO - Number of contigs containing single-copy marker genes: 87
2022-08-05 12:52:40,639 - INFO - Determining contig counts for each single-copy marker gene
2022-08-05 12:52:40,640 - INFO - Initialising bins
2022-08-05 12:52:40,640 - INFO - Matching and assigning contigs with single-copy marker genes to bins
2022-08-05 12:52:40,933 - INFO - Further assigning contigs with single-copy marker genes
2022-08-05 12:52:40,975 - INFO - Propagating labels to connected vertices of unlabelled long contigs
2022-08-05 12:52:45,743 - INFO - Further propagating labels to vertices of unlabelled long contigs
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 101/101 [00:00<00:00, 333300.32it/s]
2022-08-05 12:52:45,772 - INFO - Further propagating labels to connected vertices of unlabelled long contigs
2022-08-05 12:52:47,180 - INFO - Elapsed time: 25.09567618370056 seconds
2022-08-05 12:52:47,198 - INFO - Writing the Final Binning result to file
Splitting contigs into bins: 519it [00:00, 2886.62it/s]
2022-08-05 12:52:47,452 - INFO - Producing 5 bins...
2022-08-05 12:52:47,453 - INFO - Final binning results can be found in ./bins/
2022-08-05 12:52:47,453 - INFO - Thank you for using MetaCoAG!
```

Output files fron `ls -lh`:

```
total 106648
-rwxr-xr-x  1 vijinimallawaarachchi  staff    25M  5 Aug 09:47 assembly_graph_with_scaffolds.gfa
drwxr-xr-x  7 vijinimallawaarachchi  staff   224B  5 Aug 12:52 bins
-rw-r--r--  1 vijinimallawaarachchi  staff   9.5K  5 Aug 12:52 contig_to_bin.tsv
-rwxr-xr-x  1 vijinimallawaarachchi  staff    26M  5 Aug 09:47 contigs.fasta
-rwxr-xr-x  1 vijinimallawaarachchi  staff   114K  5 Aug 09:47 contigs.fasta.hmmout
-rw-r--r--  1 vijinimallawaarachchi  staff   568K  5 Aug 12:52 contigs.fasta.normalized_contig_tetramers.pickle
-rwxr-xr-x  1 vijinimallawaarachchi  staff    73K  5 Aug 09:47 contigs.paths
-rwxr-xr-x  1 vijinimallawaarachchi  staff    21K  5 Aug 09:47 coverm_mean_coverage.tsv
drwxr-xr-x  3 vijinimallawaarachchi  staff    96B  5 Aug 12:52 low_quality_bins
-rw-r--r--  1 vijinimallawaarachchi  staff    29K  5 Aug 12:52 metacoag.log
```

Everything looks good!

**Comment by Vini2** [comment]
# Testing

## Conda
```
conda install -c packages metacoag-1.1-pyhfa5458b_0.tar.bz2

which metacoag
/Users/vijinimallawaarachchi/anaconda3/envs/metacoag_test/bin/metacoag

metacoag --version
metacoag 1.1

metacoag --help 
usage: metacoag [-h] --assembler ASSEMBLER --graph GRAPH --contigs CONTIGS --abundance ABUNDANCE [--paths PATHS] --output OUTPUT [--hmm HMM] [--prefix PREFIX]
                [--min_length MIN_LENGTH] [--p_intra P_INTRA] [--p_inter P_INTER] [--d_limit D_LIMIT] [--depth DEPTH] [--mg_threshold MG_THRESHOLD]
                [--bin_mg_threshold BIN_MG_THRESHOLD] [--min_bin_size MIN_BIN_SIZE] [--delimiter DELIMITER] [--nthreads NTHREADS] [-v]

MetaCoAG is a metagenomic contig binning tool that makes use of the connectivity information found in assembly graphs, apart from the composition and coverage
information. MetaCoAG makes use of single-copy marker genes along with a graph matching technique and a label propagation technique to bin contigs.

optional arguments:
  -h, --help            show this help message and exit
  --assembler ASSEMBLER
                        name of the assembler used. (Supports SPAdes, MEGAHIT and Flye)
  --graph GRAPH         path to the assembly graph file
  --contigs CONTIGS     path to the contigs file
  --abundance ABUNDANCE
                        path to the abundance file
  --paths PATHS         path to the contigs.paths (metaSPAdes) or assembly.info (metaFlye) file
  --output OUTPUT       path to the output folder
  --hmm HMM             path to marker.hmm file. [default: auxiliary/marker.hmm]
  --prefix PREFIX       prefix for the output file
  --min_length MIN_LENGTH
                        minimum length of contigs to consider for binning. [default: 1000]
  --p_intra P_INTRA     minimum probability of an edge matching to assign to the same bin. [default: 0.1]
  --p_inter P_INTER     maximum probability of an edge matching to create a new bin. [default: 0.01]
  --d_limit D_LIMIT     distance limit for contig matching. [default: 20]
  --depth DEPTH         depth to consider for label propagation. [default: 10]
  --mg_threshold MG_THRESHOLD
                        length threshold to consider marker genes. [default: 0.5]
  --bin_mg_threshold BIN_MG_THRESHOLD
                        minimum fraction of marker genes that should be present in a bin. [default: 0.33333]
  --min_bin_size MIN_BIN_SIZE
                        minimum size of a bin to output in base pairs. [default: 200000]
  --delimiter DELIMITER
                        delimiter for output results. Supports a comma (,), a semicolon (;), a tab ($'\t'), a space (" ") and a pipe (|) [default: , (comma)]
  --nthreads NTHREADS   number of threads to use. [default: 8]
  -v, --version         show program's version number and exit
```

### Test run

Testing on test data.

Command:
```
metacoag --assembler spades --graph assembly_graph_with_scaffolds.gfa --contigs contigs.fasta --paths contigs.paths --abundance coverm_mean_coverage.tsv --output ./
```
Output:
```
2022-08-05 13:19:34,756 - INFO - Welcome to MetaCoAG: Binning Metagenomic Contigs via Composition, Coverage and Assembly Graphs.
2022-08-05 13:19:34,756 - INFO - Input arguments: 
2022-08-05 13:19:34,757 - INFO - Assembler used: spades
2022-08-05 13:19:34,757 - INFO - Contigs file: contigs.fasta
2022-08-05 13:19:34,757 - INFO - Assembly graph file: assembly_graph_with_scaffolds.gfa
2022-08-05 13:19:34,757 - INFO - Contig paths file: contigs.paths
2022-08-05 13:19:34,757 - INFO - Abundance file: coverm_mean_coverage.tsv
2022-08-05 13:19:34,757 - INFO - Final binning output file: ./
2022-08-05 13:19:34,757 - INFO - Minimum length of contigs to consider: 1000
2022-08-05 13:19:34,758 - INFO - Depth to consider for label propagation: 10
2022-08-05 13:19:34,758 - INFO - p_intra: 0.1
2022-08-05 13:19:34,758 - INFO - p_inter: 0.01
2022-08-05 13:19:34,758 - INFO - mg_threshold: 0.5
2022-08-05 13:19:34,758 - INFO - bin_mg_threshold: 0.33333
2022-08-05 13:19:34,758 - INFO - min_bin_size: 200000 base pairs
2022-08-05 13:19:34,758 - INFO - d_limit: 20
2022-08-05 13:19:34,759 - INFO - Number of threads: 8
2022-08-05 13:19:34,759 - INFO - MetaCoAG started
2022-08-05 13:19:34,773 - INFO - Total number of contigs available: 519
2022-08-05 13:19:34,839 - INFO - Total number of edges in the assembly graph: 1065
2022-08-05 13:19:34,840 - INFO - Total isolated contigs in the assembly graph: 1
2022-08-05 13:19:34,840 - INFO - Obtaining lengths and coverage values of contigs
2022-08-05 13:19:35,044 - INFO - Total long contigs: 251
2022-08-05 13:19:35,044 - INFO - Total isolated long contigs in the assembly graph: 1
2022-08-05 13:19:35,044 - INFO - Obtaining tetranucleotide frequencies of contigs
2022-08-05 13:19:52,286 - INFO - Scanning for single-copy marker genes
2022-08-05 13:19:52,286 - INFO - .hmmout file already exists
2022-08-05 13:19:52,286 - INFO - Obtaining contigs with single-copy marker genes
2022-08-05 13:19:52,293 - INFO - Number of contigs containing single-copy marker genes: 87
2022-08-05 13:19:52,293 - INFO - Determining contig counts for each single-copy marker gene
2022-08-05 13:19:52,293 - INFO - Initialising bins
2022-08-05 13:19:52,294 - INFO - Matching and assigning contigs with single-copy marker genes to bins
2022-08-05 13:19:57,795 - INFO - Further assigning contigs with single-copy marker genes
2022-08-05 13:19:57,838 - INFO - Propagating labels to connected vertices of unlabelled long contigs
2022-08-05 13:20:02,106 - INFO - Further propagating labels to vertices of unlabelled long contigs
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 101/101 [00:00<00:00, 350682.70it/s]
2022-08-05 13:20:02,650 - INFO - Further propagating labels to connected vertices of unlabelled long contigs
2022-08-05 13:20:04,383 - INFO - Elapsed time: 29.624009132385254 seconds
2022-08-05 13:20:04,440 - INFO - Writing the Final Binning result to file
Splitting contigs into bins: 519it [00:00, 2134.92it/s]
2022-08-05 13:20:04,744 - INFO - Producing 5 bins...
2022-08-05 13:20:04,744 - INFO - Final binning results can be found in ./bins/
2022-08-05 13:20:04,745 - INFO - Thank you for using MetaCoAG!
```

Output files from `ls -lh`:

```
total 106648
-rwxr-xr-x  1 vijinimallawaarachchi  staff    25M  5 Aug 09:47 assembly_graph_with_scaffolds.gfa
drwxr-xr-x  7 vijinimallawaarachchi  staff   224B  5 Aug 13:20 bins
-rw-r--r--  1 vijinimallawaarachchi  staff   9.5K  5 Aug 13:20 contig_to_bin.tsv
-rwxr-xr-x  1 vijinimallawaarachchi  staff    26M  5 Aug 09:47 contigs.fasta
-rwxr-xr-x  1 vijinimallawaarachchi  staff   114K  5 Aug 09:47 contigs.fasta.hmmout
-rw-r--r--  1 vijinimallawaarachchi  staff   568K  5 Aug 13:19 contigs.fasta.normalized_contig_tetramers.pickle
-rwxr-xr-x  1 vijinimallawaarachchi  staff    73K  5 Aug 09:47 contigs.paths
-rwxr-xr-x  1 vijinimallawaarachchi  staff    21K  5 Aug 09:47 coverm_mean_coverage.tsv
drwxr-xr-x  3 vijinimallawaarachchi  staff    96B  5 Aug 13:20 low_quality_bins
-rw-r--r--  1 vijinimallawaarachchi  staff    29K  5 Aug 13:20 metacoag.log
```

Everything looks good!

**Comment by Vini2** [comment]
@BiocondaBot please add label

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@BiocondaBot please merge

@Vini2 I really appreciate your thorough testing and documentation of this PR. Keep up the great work!

**Comment by Vini2** [comment]
Thank you very much!

**Pull request merged**
