### PR TITLE
Add pyseq-align

### PR DESCRIPTION
**Pull request by Maarten-vd-Sande**
Describe your pull request here

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by Maarten-vd-Sande** [comment]
@BiocondaBot please add label

**Comment by dpryan79** [comment]
FYI, there's an annoying conda-build oddity, wherein if you don't have a "noarch: python" package and restrict the conda version using >= that you only get a package built for the latest python version available.

**Comment by Maarten-vd-Sande** [comment]
@dpryan79 thanks. I got some python2.7 related error (I think) so I just made it python 3.6+

Error:
```
10:30:39 BIOCONDA INFO (OUT)   File "$PREFIX/lib/python2.7/site-packages/pip/_internal/cli/base_command.py", line 188, in _main
10:30:39 BIOCONDA INFO (OUT)     status = self.run(options, args)
10:30:39 BIOCONDA INFO (OUT)   File "$PREFIX/lib/python2.7/site-packages/pip/_internal/cli/req_command.py", line 185, in wrapper
10:30:39 BIOCONDA INFO (OUT)     return func(self, options, args)
10:30:39 BIOCONDA INFO (OUT)   File "$PREFIX/lib/python2.7/site-packages/pip/_internal/commands/install.py", line 333, in run
10:30:39 BIOCONDA INFO (OUT)     reqs, check_supported_wheels=not options.target_dir
10:30:39 BIOCONDA INFO (OUT)   File "$PREFIX/lib/python2.7/site-packages/pip/_internal/resolution/legacy/resolver.py", line 179, in resolve
10:30:39 BIOCONDA INFO (OUT)     discovered_reqs.extend(self._resolve_one(requirement_set, req))
10:30:39 BIOCONDA INFO (OUT)   File "$PREFIX/lib/python2.7/site-packages/pip/_internal/resolution/legacy/resolver.py", line 370, in _resolve_one
10:30:39 BIOCONDA INFO (OUT)     ignore_requires_python=self.ignore_requires_python,
10:30:39 BIOCONDA INFO (OUT)   File "$PREFIX/lib/python2.7/site-packages/pip/_internal/resolution/legacy/resolver.py", line 102, in _check_dist_requires_python
10:30:39 BIOCONDA INFO (OUT)     dist.project_name, version, requires_python,
10:30:39 BIOCONDA INFO (OUT) UnsupportedPythonVersion: Package u'pyseq-align' requires a different Python: 2.7.15 not in '>=3.6'
```

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Pull request merged**
