### PR TITLE
Update to FALCON 2.1.4

### PR DESCRIPTION
**Pull request by peterjc**
This is a work in progress, blocked by #8945 on version labelling.

* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [X] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [X] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

Rather than working directly from FALCON-integrate (which bundles specific versions of the dependencies daligner, damasker, dazz_db, dextractor and pypeflow), still working from the FALCON repository and declaring dependencies via conda.

Previous version of the recipe targeted the tag funzip_052016 (May 2016) which seems to have been between v0.2 and v0.2.2, at least chronologically.

### CODE REVIEW

**Comment by peterjc** [comment]
TODO: Should we pin the exact version of each dependency to match those specified implicitly via the ``FALCON-integrate`` repository? Or perhaps set them as minimum versions?

**Comment by peterjc** [comment]
Well the automated tests have passed... other than the version numbering issue (#8945) this seems to have been pleasantly straightforward to update. Could you review this please @bebatut ?

**Comment by peterjc** [comment]
Trying this locally, it wanted a more recent version of pypeFLOW than we have in BioConda, which is why I am working on https://github.com/bioconda/bioconda-recipes/pull/8950 and the planned follow up updates.

**Comment by peterjc** [comment]
I can now build FALCON locally using dependencies from (Bio)Conda. However, a test assembly failed.

It took a bit of debugging to find a useful error message, but running the last command from ``0-rawreads/tash.sh`` was instructive:

```
$ time python2.7 -m pypeflow.do_task  /mnt/shared/scratch/xxx/falcon_test/0-rawreads/task.json
...
INFO:root:$('bash -vex build_rdb.sh')
#!/bin/bash
set -vex
+ set -vex
echo "PBFALCON_ERRFILE=$PBFALCON_ERRFILE"
+ echo PBFALCON_ERRFILE=
PBFALCON_ERRFILE=
set -o pipefail
+ set -o pipefail
rm -f raw_reads.db .raw_reads.* # in case of re-run
+ rm -f raw_reads.db '.raw_reads.*'
#fc_fasta2fasta < my.input.fofn >| fc.fofn
while read fn; do  cat  $fn | fasta2DB -v raw_reads -i${fn##*/}; done < my.input.fofn
+ read fn
+ cat /mnt/shared/scratch/pc40583/falcon_test/ecoli.1.fasta
+ fasta2DB -v raw_reads -iecoli.1.fasta
fasta2DB: -i is an illegal option
cat: write error: Broken pipe
WARNING:root:Call 'bash -vex build_rdb.sh' returned 256.
...
```

Notice that this is calling ``fast2DB`` with the ``-i`` option, a change made in FALCON on 2016-11-02

https://github.com/PacificBiosciences/FALCON/commit/478ec3f783936cace8f32716a0fe722a3673116b#diff-692525db8fdb84df2833651e0c9533e0L182

This ``-i`` functionality was added to ``DAZZ_DB`` on  2016-05-21,

https://github.com/thegenemyers/DAZZ_DB/commit/d1cf08025c73ce1caaa357f927ba0f89485b33b2

i.e. This was after DAZZ_DB v1.0 was tagged, see https://github.com/thegenemyers/DAZZ_DB/blob/V1.0/fasta2DB.c

Currently BioConda has only got DAZZ_DB v1.0, https://anaconda.org/bioconda/dazz_db - but that is too old for the recent versions of FALCON.

I've logged an issue to try to clarify the DAZZ_DB versioning, but using yyyymmdd date based versioning ought to work: https://github.com/thegenemyers/DAZZ_DB/issues/34

**Comment by peterjc** [comment]
The next hurdle is very similar, BioConda only has DALIGNER v1.0 and that lacks the ``HPC.daligner`` binary which was created by this commit on 2016-04-12,

https://github.com/thegenemyers/DALIGNER/commit/e5ccfb896a0c95ef9707c76ce090ee7ea35c3cc7#diff-b67911656ef5d18c4ae36cb6741b7965

See https://github.com/thegenemyers/DALIGNER/issues/83 for my DALIGNER versioning question.

**Comment by dpryan79** [comment]
Should this still get moved to `bioconda-legacy`? If so I'll do that and then close https://github.com/bioconda/bioconda-recipes/issues/8945

**Comment by daler** [comment]
Closing due to inactivity, please re-open if needed.

**Pull request closed without merging**
