### PR TITLE
add recipe for cellpose

### PR DESCRIPTION
**Pull request by sunyi000**
Add new recipe for cellpose. this requires #27698

### CODE REVIEW

**Comment by asp8200** [comment]
@sunyi000 : Why was this never merged? It would be nice to have a bioconda-recipe for cellpose.

**Comment by asp8200** [comment]
nf-core would like to have a bioconda-recipe for cellpose. @sunyi000 : Could you perhaps reopen this PR and update it to the newest version of cellpose? I'll try to push for reviewer.

**Comment by sunyi000** [comment]
> nf-core would like to have a bioconda-recipe for cellpose. @sunyi000 : Could you perhaps reopen this PR and update it to the newest version of cellpose? I'll try to push for reviewer.

sure I will try to update it to the new version
thanks

**Comment by asp8200** [comment]
Somewhat related question, this [docker-image](https://hub.docker.com/layers/biocontainers/cellpose/2.1.1_cv2/images/sha256-cfe36943a49590da85c64bb8006330397193de2732faad06f41260296e35978c?context=explore) for cellpose is pretty large (3.1GB) and that is causing some failing [test](https://github.com/nf-core/modules/actions/runs/5724857236/job/15513341041?pr=3686) ("no space left on device") over in nf-core world. 

As you may be aware, the new bioconda-recipe will result in a corresponding docker-image at https://quay.io/repository/biocontainers. Any chance that docker-image might be smaller?

**Pull request closed without merging**
