### PR TITLE
Update Prokka to use non-expired version of tbl2asn

### PR DESCRIPTION
**Pull request by rpetit3**
Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it. Note that if you are not already a member of the bioconda project (meaning that you can't add this label), please ping `@bioconda/core` so that your PR can be reviewed and merged (please note if you'd like to be added to the bioconda project). Please see https://github.com/bioconda/bioconda-recipes/issues/15332 for more details.

* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [X] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [X] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

Current recipe allows for an expired version of tbl2asn to be used. I'm changing the requirements to be >= to the most recent version of tbl2asn.

### CODE REVIEW

**Comment by npavlovikj** [comment]
@rpetit3 , tbl2asn needs to be updated first - I am doing that in https://github.com/bioconda/bioconda-recipes/pull/16140.

**Comment by npavlovikj** [comment]
Ah, please ignore my previous comment, I just saw that you have merged `tbl2asn` earlier today.

**Comment by rpetit3** [comment]
Hi @bgruening,

Looks like the tests are failing with version 1.12. Any recommendations on fixing this? I was hoping to bump the tbl2asn version, nothing else should have changed.

Thank you very much for your help!

**Comment by rpetit3** [comment]
Haha I just saw your comment @npavlovikj! Good call on the new version being automatically picked up.

@bgruening, I'm going to close this PR and let conda do its job.

**Pull request closed without merging**
