### PR TITLE
update pantools to v4.0.0

### PR DESCRIPTION
**Pull request by dirkjanvw**
PanTools received a major API change and therefore we updated the major version of PanTools (to 4.0.0).

### CODE REVIEW

**Comment by dirkjanvw** [comment]
hmm not sure why test only takes 20 seconds for `test_osx` but more than 20 minutes for `test_linux`?

**Comment by dirkjanvw** [comment]
@BiocondaBot please add label

**Comment by dpryan79** [comment]
@BiocondaBot please fetch artifacts

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@BiocondaBot please merge

**Pull request merged**
