### PR TITLE
Add r-exomedepth

### PR DESCRIPTION
**Pull request by druvus**
* [x] I have read the guidelines above.
* [x] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by bgruening** [comment]
@druvus is rocking all issues!

**Comment by druvus** [comment]
@bgruening just digging through some old PRs :)

**Comment by bgruening** [comment]
Keep going Andreas! Keep going! :)

**Comment by micknudsen** [comment]
There appears to be a problem with this package. 

```
> conda create -n test r-exomedepth
> source activate test
> R

> library(ExomeDepth)
Error : Function found when exporting methods from the namespace 'Biostrings' which is not S4 generic: 'setequal'
In addition: Warning message:
no function found corresponding to methods exports from 'Biostrings' for: 'pcompare'
Error: package or namespace load failed for 'ExomeDepth'
```

**Pull request merged**
