### PR TITLE
Update group_humann2_uniref_abundances_to_GO to v1.2.1

### PR DESCRIPTION
**Pull request by jraysajulga**
:information_source:
If this is your first pull request to Bioconda please ping `@bioconda/core` so it can be reviewed and to request being added as a member of the Bioconda team. Members of the Bioconda team are able to merge their own pull requests once tests and linting have passed.

----------------

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by jraysajulga** [comment]
> If this is your first pull request to Bioconda please ping @bioconda/core so it can be reviewed and to request being added as a member of the Bioconda team. Members of the Bioconda team are able to merge their own pull requests once tests and linting have passed.

@bioconda/core Hello. This is my first pull request; looking to have it reviewed. Also hoping for consideration for Bioconda membership. Thanks!

**Comment by bgruening** [comment]
Thanks @jraysajulga! There was something wrong with your branch, so I merged master into it.

**Comment by jraysajulga** [comment]
@bgruening Thank you!

**Comment by jraysajulga** [comment]
@bgruening It seems like CircleCI has not yet uploaded the files to anaconda.org. Looking at other packages, it seems like it does this approximately 5 hours after a change is committed. For this package, 9 hours have elapsed.

> There was something wrong with your branch, so I merged master into it.

Did this error interrupt the building and uploading process?

**Pull request merged**
