### PR TITLE
Add ExpansionHunterDeNovo

### PR DESCRIPTION
**Pull request by christopher-schroeder**
Add ExpansionHunterDeNovo, a modified advanced version of ExpansionHunter.

### CODE REVIEW

**Comment by christopher-schroeder** [comment]
All modifications are made to compile EHDN by using environment packages instead of downloading and compiling them by itself.

**Comment by christopher-schroeder** [comment]
@BiocondaBot please fetch artifacts

**Comment by christopher-schroeder** [comment]
@BiocondaBot please update

**Comment by christopher-schroeder** [comment]
@BiocondaBot please add label

**Comment by dpryan79** [comment]
@bioconda-bot please fetch artifacts

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Pull request merged**
