### PR TITLE
Add recipe shorttracks

### PR DESCRIPTION
**Pull request by MikeAxtell**
Adding recipe for shorttracks. The installed python script `ShortTracks` generates useful wiggle coverage files from BAM alignments of small RNA-seq data, based on alignment length, read-group, and strandedness. <http://github.com/MikeAxtell/ShortTracks>

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by MikeAxtell** [comment]
@BiocondaBot please add label

**Review by shenwei356 — APPROVED** [review]

**Comment by shenwei356** [comment]
@BiocondaBot please merge

**Comment by shenwei356** [comment]
@BiocondaBot please merge

**Comment by shenwei356** [comment]
@BiocondaBot please merge

**Comment by MikeAxtell** [comment]
@bioconda/core Looks like this merge had problems. Is there anything I can change on my end to fix it?

**Comment by shenwei356** [comment]
@BiocondaBot please merge

**Comment by shenwei356** [comment]
The error happened frequently these days, but It could be solved by merging again, except for this PR.

**Comment by rpetit3** [comment]
@BiocondaBot please update

**Comment by rpetit3** [comment]
@BiocondaBot please fetch artifacts

**Comment by rpetit3** [comment]
hmmm, looks like the CI isn't picking up the change: https://dev.azure.com/bioconda/bioconda-recipes/_build/results?buildId=25925&view=logs&j=e14e69ff-a0ae-55c4-b71d-229b239cfb2f&t=7df82132-b284-504b-53d6-7d3e63519572&l=36

**Comment by rpetit3** [comment]
@MikeAxtell you will need to move the `shorttracks` folder into the `recipes` folder. Then I think we'll be able to get this finished up

**Comment by MikeAxtell** [comment]
Oh wow, that was a silly mistake by me. The `shorttracks/` directory is now in `recipes/` and checks are all green.

**Comment by MikeAxtell** [comment]
@bioconda/core I think this issue should be fixed, can you try and merge again?

**Comment by shenwei356** [comment]
My bad, I didn't find out the wrong path in the review process.

Could you please recreate a new branch with the final version of the files, so it would be a fresh and clean pull request? I mean, there are 10+ commits now. A single commit with a meaningful message would be better, like "Add shorttracks".

**Comment by MikeAxtell** [comment]
OK, new pull request on clean branch submitted. See #38584

**Pull request closed without merging**
