### PR TITLE
Update trinotate to 3.1.0 and 3.1.1

### PR DESCRIPTION
**Pull request by biocyberman**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by peterjc** [comment]
I believe that you need to do this as two pull request, first the 3.1.0 update, then once that is merged, built, and uploaded to anaconda.org you can do the 3.1.1 update.

If we just merge this as is, I believe the 3.1.0 update will never be processed.

**Comment by biocyberman** [comment]
@peterjc Thanks for the explanation. I was not clear about this.  Will do a reset

**Comment by peterjc** [comment]
Great - merging now for the 3.1.0 update...

**Comment by peterjc** [comment]
You can prepare the new pull request now (I assume you kept the changes locally so that ought to be quick). Thanks.

**Pull request merged**
