### PR TITLE
Update ldsc recipe: Relax version requirement for dependency nose.

### PR DESCRIPTION
**Pull request by jdblischak**
Describe your pull request here

I can't install the recipe for ldsc because it requires `nose ==1.3`. This is too strict. Both conda-forge and main only have nose 1.3.7. This PR relaxes the requirement to `nose =1.3`.

https://github.com/bioconda/bioconda-recipes/blob/e1ae0d3d928326bdad8443d5faa2bdd331c2f10e/recipes/ldsc/meta.yaml#L25

More details:

* This relaxed pinning for nose matches the `environment.yml` file in the source repo at the pinned commit:

https://github.com/bulik/ldsc/blob/12e2687ec9bba39da2139d14f6d1944a23d5774a/environment.yml#L7

* Here are the available node packages on Anaconda Cloud:

https://anaconda.org/conda-forge/nose/files?version=1.3.7
https://anaconda.org/anaconda/nose/files?version=1.3.7
https://anaconda.org/main/nose/files?version=1.3.7

* And here is what I observe when I try to install ldsc:

```
% conda --version
conda 4.10.0

# nose from conda-forge
% conda create --dry-run -n test-ldsc -c conda-forge -c bioconda --override-channels ldsc
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: /
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

PackagesNotFoundError: The following packages are not available from current channels:

  - nose==1.3

Current channels:

  - https://conda.anaconda.org/conda-forge/osx-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://conda.anaconda.org/bioconda/osx-64
  - https://conda.anaconda.org/bioconda/noarch

To search for alternate channels that may provide the conda package you\'re
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

# nose from main
% conda create --dry-run -n test-ldsc -c conda-forge -c bioconda --override-channels ldsc main::nose
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: |
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package nose conflicts for:
ldsc -> nose==1.3
main::nose
```

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by jdblischak** [comment]
This is a follow-up to the original PR #18704 by @hmenager

**Comment by jdblischak** [comment]
Looking at the [build log](https://app.circleci.com/pipelines/github/bioconda/bioconda-recipes/14979/workflows/b9b36674-5cde-42c2-8f87-70e27407249a/jobs/82750) from the original PR, the recipe was built with nose 1.3.0 from main:

```
nose:            1.3.0-py27_0               defaults
```

I don't understand what happened to that package. The only version of nose for Python 2.7 I see on Anaconda Cloud is 1.3.7: https://anaconda.org/main/nose/files Was it deleted, or am I looking in the wrong place?

**Comment by jdblischak** [comment]
@BiocondaBot please add label

**Comment by dpryan79** [comment]
This doesn't actually need nose to run, I really hate it when packages incorrectly list nose as a dependency when it's only used for automated tests.

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Comment by jdblischak** [comment]
Thanks @dpryan79! I agree that nose is not a required dependency, so that makes sense to simply remove it entirely. I confirmed that I can now install ldsc.

Note that this recipe vendors a `setup.py` file which includes nose in its `install_requires`. I assume this didn't cause any issue because `pip install` is run with `--no-deps`:

https://github.com/bioconda/bioconda-recipes/blob/693d73b9411d6bc859cab529064eb3f516641686/recipes/ldsc/setup.py#L12

**Pull request merged**
