### PR TITLE
Ac trnanalysis

### PR DESCRIPTION
**Pull request by Acribbs**
:information_source:
If this is your first pull request to Bioconda please ping `@bioconda/core` so it can be reviewed and to request being added as a member of the Bioconda team. Members of the Bioconda team are able to merge their own pull requests once tests and linting have passed.

----------------

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by epruesse** [comment]
@biocondabot recheck

**Comment by npavlovikj** [comment]
The license is not in the pypi package, but in the repo, https://github.com/Acribbs/tRNAnalysis/blob/master/LICENSE.

**Comment by npavlovikj** [comment]
@Acribbs , you should have the license information in `meta.yaml` - you just need to copy the license file from the repo to the recipe directory, and use `license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'` in `meta.yaml` instead.

**Comment by npavlovikj** [comment]
Thanks for adding and updating the recicpe @Acribbs ! 

Do you know if `setuptools` is really needed as a `run` dependency? It usually is not, and if that is the case, then it is enough to only keep it in the `host` section (and not `run`).

And just for aesthetic purposes - you should leave one line between the main secions in `meta.yaml` such as "package", "source", "build", "requirements", "test", "about", but not between the subsections. In your recipe, the lines between "run", "host", "imports", "commands" shouldn't be there.

**Comment by Acribbs** [comment]
Hi @npavlovikj thanks for your help! 

I think you might be correct about `setuptools`. I can remove from `host` section.

Ok, thanks I can remove the extra lines.

My build seems to be failing with the following error:
```
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-64: {"python[version='>=3.5,<3.6.0a0']", 'python=3.7'}
```

Just wondered if you had any advice, previously I had the python version `python >=3.6` and I didn't see any failures

**Comment by npavlovikj** [comment]
Please remove `setuptools` from `run`, and leave it in `host` :)

So, the error is:
06:33:07 BIOCONDA INFO (OUT) conda.exceptions.UnsatisfiableError: The following specifications were found to be in conflict:
**06:33:07 BIOCONDA INFO (OUT)   - cgat-apps -> python[version='>=3.5,<3.6.0a0']**
**06:33:07 BIOCONDA INFO (OUT)   - python=3.7**
Looks like `cgat-apps` is built against Python 3.5 and Python 3.6 (https://anaconda.org/bioconda/cgat-apps/files), and in the recipe Python 3.7 is used as well. I think `cgat-apps` just needs to be rebuilt again to pick up Python 3.7. The Python 3.7 build should have failed earlier as well, I don't know why that worked...

**Comment by Acribbs** [comment]
hi @npavlovikj sorry thats what I meant, I will make the changes and wait for cgat-apps to be rebuilt.

@sebastian-luna-valero is it possible to rebuild cgat-apps? I am happy to give this a go if you don't have time

**Comment by npavlovikj** [comment]
I am testing "cgat-apps" with Python 3.7 now, but if you want to try it, please go ahead (sorry, should have mentioned that in my previous comment). Technically, only the build number should be increased to 1 in the current "cgat-apps" recipe if Python 3.7 is supported.

**Comment by Acribbs** [comment]
Hi @npavlovikj, no worries, thanks thats great!

**Comment by npavlovikj** [comment]
Looks like `quicksect`, one of the dependencies for `cgat-apps` needs to be rebuilt with Python 3.7 as well :/ That one is throwing some Cython errors though, so @Acribbs , if this it hard to fix, it might be easier if you skip Pyhon 3.7 for now, and add it later.

**Comment by npavlovikj** [comment]
Looks like the issue with `quicksect` is reported here, https://github.com/bioconda/bioconda-recipes/pull/14770.

**Comment by Acribbs** [comment]
Hi @npavlovikj, thanks for your help, I have built the package on python 3.6 only and will bump the build number when `quicksect` and `cgat-apps` python 3.7 version is available.

A novice question, why was the linting test cancelled after 5s? Does this mean tests on the recipe failed and if not what cases the cancellation.

**Comment by npavlovikj** [comment]
@Acribbs , the bot is still in an experimental phase, and it gets stuck sometimes. In that case, you can just type `@BiocondaBot recheck`, and the linting should restart. Although preferable, this step is not required to have/pass for your recipe to be merged (as long as the bioconda-test is green). On the other hand, the first step of `bioconda-test` is linting, and this is the one that matters for your recipe - if this linting fails, it will print a message of what is wrong, and you will need to fix your recipe.

**Comment by npavlovikj** [comment]
@BiocondaBot recheck

**Comment by npavlovikj** [comment]
The recipe looks good to me, but since it is your first recipe, please ping `@bioconda/core` - they will give you feedback on the recipe and add you to the bioconda team.

**Comment by dpryan79** [comment]
@bioconda-bot merge

**Comment by dpryan79** [comment]
Thanks @Acribbs and @npavlovikj!

**Pull request merged**
