### PR TITLE
Add karyoploteR

### PR DESCRIPTION
**Pull request by brainstorm**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).

### CODE REVIEW

**Comment by brainstorm** [comment]
Thanks and cheers to @bladedancer-256.

**Comment by brainstorm** [comment]
depends on https://github.com/conda-forge/staged-recipes/pull/7342 getting merged in first.

**Comment by brainstorm** [comment]
Thanks for checking my PR @dpryan79!

I had no idea about that `bulk` branch, any idea on when it'll be merged? It does need https://github.com/conda-forge/staged-recipes/pull/7342 so I guess it'll be blocked until that gets merged in conda-forge?

There was an attempt in the past as well, should have searched better first: https://github.com/bioconda/bioconda-recipes/pull/6770

**Comment by dpryan79** [comment]
It's a special branch, so everything in it gets published once built. We're going through all of the bioconductor 3.8 packages, which will take a few weeks to process through still I expect. You can use them by adding `conda-forge/label/gcc7` and `bioconda/label/gcc7` to your channels (the karyoplotr package hasn't gotten built yet).

BTW, please be aware that your current PR will end up using bioconductor 3.7 packages for dependency resolution, which may or may not actually work (this is one of the things we've fixed for the bioconductor 3.8 packages getting built in `bulk`, they're all narrowly pinned to dependencies within the same bioconductor release).

**Comment by brainstorm** [comment]
Awesome, didn't know all this... what do you reckon is the best course of action then? Should I close this PR?

Also, I still wonder how `r-bezier` (dependency not found in either bioconda or conda-forge, currently) will be brought in?

**Comment by dpryan79** [comment]
It's really up to you whether you want to close this or not. If this package isn't too picky about its dependency versions then it shouldn't be an issue. Ideally one would wait for the dependencies within bioconductor to be built, but sometimes you need to get stuff done sooner rather than later.

Regarding `r-bezier`, we have a [growing list of CRAN packages to add](https://github.com/bioconda/bioconda-recipes/issues/12586). Definitely get it added to conda-forge regardless of what you end up doing with this PR :)

**Comment by brainstorm** [comment]
@dpryan79 Firstly, merry xmas! So r-bezier made it into conda-forge... since I'm no bioconductor dependencies pro, I'm not familiar with the implications of merging this recipe as-is right now, so what would you change to make it just right? Thanks in advance!

**Comment by bgruening** [comment]
@brainstorm it would be cool if you can retarget the bulk branch. Then we can keep care about the rest. Please also change the directory name to keep everything lower case.

Merry Christmas to you too.

**Comment by brainstorm** [comment]
Closing this PR in favor of https://github.com/bioconda/bioconda-recipes/pull/12800, thanks both!

**Comment by dpryan79** [comment]
@brainstorm bioconductor-karyoploter just got built and uploaded

**Comment by brainstorm** [comment]
Thanks @dpryan79, much appreciated & happy new year! :)

**Comment by brainstorm** [comment]
@dpryan79 Today `conda install bioconductor-karyoploter -c bioconda -c conda-forge` yields:

```
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - bioconductor-karyoploter

Current channels:

  - https://conda.anaconda.org/bioconda/osx-64
  - https://conda.anaconda.org/bioconda/noarch
  - https://conda.anaconda.org/conda-forge/osx-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://conda.anaconda.org/r/osx-64
  - https://conda.anaconda.org/r/noarch
  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/osx-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/pro/osx-64
  - https://repo.anaconda.com/pkgs/pro/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

I had to go with this command I found [listed for the package](https://anaconda.org/bioconda/bioconductor-karyoploter) on anaconda cloud instead:

`conda install -c bioconda/label/gcc7 bioconductor-karyoploter`

 I this `label/gcc7` something I have to define on my `.condarc` or somewhere else from now on?

Thanks in any case!

**Pull request closed without merging**
