### PR TITLE
Update r-liger recipe to specify java and other dependencies

### PR DESCRIPTION
**Pull request by raivivek**
Signed-off-by: Vivek Rai <mail@raivivek.in>

Add Java dependency
Add umap (Python) dependency and required r packages

----

> Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [x] AFAIK, this recipe **is directly relevant to the biological sciences**
      (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.

> Everyone has access to the following BiocondaBot commands, which can be given in a comment:
>
>  * `@BiocondaBot please update` will cause the BiocondaBot to merge the master branch into a PR
>  * `@BiocondaBot please add label` will add the `please review & merge` label.
>  * `@BiocondaBot please fetch artifacts` will post links to packages and docker containers built by the CI system. You can use this to test packages locally before merging.
>
> For members of the Bioconda project, the following command is also available:
>
>  * `@BiocondaBot please merge` will cause packages/containers to be uploaded and a PR merged. Someone must approve a PR first! This has the benefit of not wasting CI build time required by manually merging PRs.
>
> If you have questions, please post them in gitter or ping `@bioconda/core` in a comment (if you are not able to directly ping `@bioconda/core` then the bot will repost your comment and enable pinging).

### CODE REVIEW

**Comment by raivivek** [comment]
@dpryan79 I'd also like to build for R-3.5.1 version. Would you know how to do that?

**Comment by dpryan79** [comment]
You can add a conda_build_config.yaml file listing both versions if you absolutely need to support R 3.5 for some reason.

**Comment by raivivek** [comment]
@BiocondaBot update

**Comment by raivivek** [comment]
@dpryan79 I'm not sure why the macos build is failing -- looks like it's unable to find a shared library.. but I'm not sure why. Sorry to bother.

**Comment by raivivek** [comment]
Thanks for the `blas` change. However, looks like the build is still failing. Very weird.

**Comment by dpryan79** [comment]
There's an underlying issue with r-matrix that we need to address and then this should "just work".

**Comment by raivivek** [comment]
Thanks for the note -- looking forward to the r-matrix issue being resolved soon.

**Comment by raivivek** [comment]
@dpryan79 The reason I removed 3.5.1 from the build config is because I was under the impression that the build was failing only for R-3.5.1 version. Is that understanding correct?

**Comment by dpryan79** [comment]
I didn't look honestly.

**Comment by dpryan79** [comment]
I'll fix r-rtsne now. https://github.com/conda-forge/r-rtsne-feedstock/pull/6

**Comment by dpryan79** [comment]
The merged in fixes are currently being blocked by an unknown r-rann.l1 issue. I'll try to track that down today still.

**Comment by dpryan79** [comment]
@bioconda-bot please fetch artifacts

**Comment by dpryan79** [comment]
@bioconda-bot please merge

Well I had to use a bit of a hack job to get a fixed r-mclust, but it works.

**Comment by raivivek** [comment]
Thanks for debugging!

**Pull request merged**
