### PR TITLE
Update chisel to 1.1

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`chisel`](https://bioconda.github.io/recipes/chisel/README.html): **1.0.0** &rarr; **1.1**

[install with bioconda](http://bioconda.github.io/recipes/chisel/README.html) [Conda](https://anaconda.org/bioconda/chisel/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/chisel`](https://github.com//bioconda/bioconda-recipes/tree/bump/chisel/recipes/chisel) (click to view/edit other files)
Summary | Copy-number Haplotype Inference in Single-cell by Evolutionary Links
Home | [https://github.com/raphael-group/chisel](https://github.com/raphael-group/chisel)
Releases |[https://github.com/raphael-group/chisel/tags](https://github.com/raphael-group/chisel/tags)
Author | `@raphael-group`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by simozacca** [comment]
This is an automatic bump of CHISEL to version 1.1; however, we will need to apply few minor changes to the recipe (one new dependency). @bioconda/core could you please tell me how we can do that within this PR? Thank you

**Comment by rpetit3** [comment]
What's the new dependency? I can add it for you

**Comment by dpryan79** [comment]
@simozacca Sorry, just now saw this. I'll send you an invite to join Bioconda, then you can directly edit this PR.

**Comment by simozacca** [comment]
Thank you so much @rpetit3 and @dpryan79 ! I have accepted the invitation and I was able to add the new dependencies. Everything worked out well and test has successfully passed. Could you please approve the merging? Thank you!

**Comment by dpryan79** [comment]
@simozacca Sure, though you can also approve and merge these now that you're part of bioconda :)

**Review by dpryan79 — APPROVED** [review]

**Pull request merged**
