### PR TITLE
Update bedtools to 2.28.0

### PR DESCRIPTION
**Pull request by cbrueffer**
:information_source:
Bioconda has finished the [GCC7 migration](https://github.com/bioconda/bioconda-recipes/issues/13578). If you are dealing with C/C++ or Python package it can be that you need to rebuild other dependent packages. [Bioconda utils - update-pinning](https://bioconda.github.io/updating.html#updating-recipes-for-a-pinning-change) will assist you with that. If you have any questions please use [issue 13578](https://github.com/bioconda/bioconda-recipes/issues/13578).

----------------

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by bgruening** [comment]
Mh, this seems like a larger problem.

@cbrueffer I have just merged the run_exports feature into htslib, if this is working could you try maybe removing htslib from the run-deps and see if this still works?

**Comment by bgruening** [comment]
Blocked by an upstream issue: https://github.com/arq5x/bedtools2/pull/713

**Comment by dpryan79** [comment]
I'm working on this here: https://github.com/bioconda/bioconda-recipes/pull/14282

**Comment by dpryan79** [comment]
I've just modified the source code to avoid the upstream issue. This is no longer a sub-recipe. I'm not really sure why that was being done before, but of course if there was a particular reason for doing so then please feel free to move the current recipe to a subdirectory.

**Comment by cbrueffer** [comment]
Thanks for having a look at this; sorry I dropped the ball.

**Comment by dpryan79** [comment]
> sorry I dropped the ball.

We're a team, you just passed the ball :)

**Pull request closed without merging**
