### PR TITLE
Update r-sigminer to 2.0.1

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`r-sigminer`](https://bioconda.github.io/recipes/r-sigminer/README.html): **2.0.0** &rarr; **2.0.1**

[install with bioconda](http://bioconda.github.io/recipes/r-sigminer/README.html) [Conda](https://anaconda.org/bioconda/r-sigminer/files)

Info | Link
-----|-----
Recipe | [`recipes/r-sigminer`](https://github.com//bioconda/bioconda-recipes/tree/bump/r_sigminer/recipes/r-sigminer) (click to view/edit other files)
Releases |[https://crandb.r-pkg.org/sigminer/all](https://crandb.r-pkg.org/sigminer/all)

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by dlaehnemann** [comment]
@ShixiangWang Does the new version `2.0.1` add `bioconductor-ranges` as a new dependency?

See:
https://github.com/ShixiangWang/sigminer/compare/v2.0.0...v2.0.1#diff-6e92fbe097ad857e05d16dbdfc754ddbd45c050e6761c66b3a99440b6960c828R192

**Comment by ShixiangWang** [comment]
@dlaehnemann I did not see anything from your link. I checked and compared the DESCRIPTION file between v2.0.0 and v2.0.1 and did not see any dependency change.

https://github.com/ShixiangWang/sigminer/blob/d955d732ed58672ce83a3dcfa94affc9658d8f34/DESCRIPTION#L45-L100

https://github.com/ShixiangWang/sigminer/blob/8b0b4f88b657240b99769cfc049a6e11baebbe7e/DESCRIPTION#L45-L100

I also tried your approach and found the following diff from v2.0.0 to v2.0.1 in DESCRIPTION file.

image

**Comment by dlaehnemann** [comment]
Ah, sorry that the link is somehow broken. I was referring to this newly added line:

https://github.com/ShixiangWang/sigminer/blob/d955d732ed58672ce83a3dcfa94affc9658d8f34/data-raw/mouse_genome.R#L75

And I think this requires `bioconductor-iranges` as a dependency, which is not currently in the meta.yaml.

**Comment by ShixiangWang** [comment]
@dlaehnemann Thanks. The script above is used to generate some raw data, not for user. And I think the `iranges` has been installed based on current meta file, as it is the dependency of `bioconductor-bsgenome.hsapiens.ucsc.hg19`, which has been included in meta file. https://www.bioconductor.org/packages/release/bioc/html/BSgenome.html

**Review by dlaehnemann — APPROVED** [review]
LGTM, thanks for the clarifications @ShixiangWang!

**Comment by dlaehnemann** [comment]
@BiocondaBot please merge

**Pull request merged**
