### PR TITLE
Update bcftools to 1.10

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`bcftools`](https://bioconda.github.io/recipes/bcftools/README.html): **1.9** &rarr; **1.10**

[install with bioconda](http://bioconda.github.io/recipes/bcftools/README.html) [Conda](https://anaconda.org/bioconda/bcftools/files)

Info | Link
-----|-----
Recipe | [`recipes/bcftools`](https://github.com//bioconda/bioconda-recipes/tree/bump/bcftools/recipes/bcftools) (click to view/edit other files)
Releases |[https://github.com/samtools/bcftools/releases](https://github.com/samtools/bcftools/releases)
Author | `@samtools`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by jmarshall** [comment]
Also needs to remove the now-downgrading of _misc/plot-vcfstats_, and should remove the patching of _misc/vcfutils.pl_ which is now unneeded (and ineffective).

**Comment by dpryan79** [comment]
@bioconda-bot please fetch artifacts

**Comment by dpryan79** [comment]
@bioconda-bot please fetch artifacts

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Pull request merged**
