### PR TITLE
Move PyVCF to conda-forge

### PR DESCRIPTION
**Pull request by sodre**
cf: conda-forge/staged-recipes#6303

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.

### CODE REVIEW

**Comment by kyleabeauchamp** [comment]
Any particular reason for the move?

**Comment by pvanheus** [comment]
I would like to echo @kyleabeauchamp - PyVCF seems to clearly fit the bioconda collectiion so why the move?

**Comment by PertuyF** [comment]
I disagree with this PR, this recipe belongs to Bioconda.

**Comment by sodre** [comment]
I am packaging apache-beam into conda-forge and it requires pyvcf. I can't build that package without having it there or in defaults. 

I am obviously happy to add bioconda developers as maintainers to the recipe in conda-forge. This might also be a good time to ask Anaconda to have it available in defaults.

**Comment by kyleabeauchamp** [comment]
Is it really a requirement or just an optional dependency?  VCF parsing is a pretty biology specific task, and it makes a lot of sense to keep the pyvcf package here.  If apache-beam can do a conditional import of pyvcf at run-time, then users can just install the library as needed from bioconda.

**Comment by kyleabeauchamp** [comment]
One more thought: moving recipes back and forth between bioconda and conda-forge is a major time sink (and source of bugs) for everyone in both projects.

**Comment by sodre** [comment]
It is required when you pip install apache-beam. On my side I am only following what I was told to do before when an equivalent package needed to be added to conda-forge.

**Comment by bgruening** [comment]
From the setup.py file:

```
REQUIRED_PACKAGES = [
    'avro>=1.8.1,<2.0.0',
    'crcmod>=1.7,<2.0',
    'dill==0.2.6',
    'grpcio>=1.8,<2',
    'hdfs>=2.1.0,<3.0.0',
    'httplib2>=0.8,<0.10',
    'mock>=1.0.1,<3.0.0',
    'oauth2client>=2.0.1,<5',
    # grpcio 1.8.1 and above requires protobuf 3.5.0.post1.
    'protobuf>=3.5.0.post1,<4',
    'pytz>=2018.3',
    'pyyaml>=3.12,<4.0.0',
    'pyvcf>=0.6.8,<0.7.0',
    'six>=1.9,<1.12',
    'typing>=3.6.0,<3.7.0',
    'futures>=3.1.1,<4.0.0',
    'future>=0.16.0,<1.0.0',
    ]

REQUIRED_TEST_PACKAGES = [
    'nose>=1.3.7',
    'pyhamcrest>=1.9,<2.0',
    ]

GCP_REQUIREMENTS = [
    # oauth2client >=4 only works with google-apitools>=0.5.18.
    'google-apitools>=0.5.18,<=0.5.20',
    'proto-google-cloud-datastore-v1>=0.90.0,<=0.90.4',
    'googledatastore==7.0.1',
    'google-cloud-pubsub==0.26.0',
    'proto-google-cloud-pubsub-v1==0.15.4',
    # GCP packages required by tests
    'google-cloud-bigquery==0.25.0',
]
```

ping @acaprez and @chapmanb you have both contributed to it.

From a technical site we can not do much if we don't want to maintain the apacha-beam pkg and I would be fine for an exception if we add all people that are interested in as maintainer of the conda-forge pkg.

**Comment by chapmanb** [comment]
It looks like apache-beam can stream VCF, hence the pyVCF dependency. That is cool functionality I hadn't realized it had. On the conda-forge/bioconda discussion, it would be easier to maintain in bioconda but understand the need for the move and would echo Björn's suggestion to add a lot of maintainers to make the conda-forge pyVCF support easier.

**Comment by sodre** [comment]
I am happy to add as many bioconda maintainers to the conda-forge package as needed.

**Comment by sodre** [comment]
@chapmanb friendly nudge...

**Comment by chapmanb** [comment]
Patrick -- sorry, I hadn't realized I was on the hook for anything to do. It looks like your conda-forge PR to create a pyvcf-feedstock still needs to get merged and then we can remove from bioconda. I unfortunately don't have any special conda-forge permissions to be able to do that. Maybe Björn can help here?

**Comment by bgruening** [comment]
@sodre can you add all people from this thread as maintainer :) Thanks.

**Comment by sodre** [comment]
@bgruening, the package is now available in conda-forge. so this should be ready to merge.

**Comment by chapmanb** [comment]
Patrick -- thanks so much for all the work porting this over to conda-forge and following up here. Much appreciated.

**Pull request merged**
