### PR TITLE
Update web.py

### PR DESCRIPTION
**Pull request by sebastian-luna-valero**
* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [X] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by daler** [comment]
@sebastian-luna-valero we should probably move this to conda-forge as it's not bioinformatics-specific

**Comment by sebastian-luna-valero** [comment]
Thanks @daler, will do.

**Comment by sebastian-luna-valero** [comment]
Reference:
https://github.com/conda-forge/staged-recipes/pull/3390

**Comment by daler** [comment]
Thanks!

**Pull request closed without merging**
