### PR TITLE
Update gff3toddbj to 0.2.3

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`gff3toddbj`](https://bioconda.github.io/recipes/gff3toddbj/README.html): **0.2.1** &rarr; **0.2.3**

[install with bioconda](http://bioconda.github.io/recipes/gff3toddbj/README.html) [Conda](https://anaconda.org/bioconda/gff3toddbj/files)

Info | Link
-----|-----
Recipe | [`recipes/gff3toddbj`](https://github.com//bioconda/bioconda-recipes/tree/bump/gff3toddbj/recipes/gff3toddbj) (click to view/edit other files)
Releases |[https://pypi.org/pypi/gff3toddbj/json](https://pypi.org/pypi/gff3toddbj/json)

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by yamaton** [comment]
Please close the PR (again) if someone notices this. I won't use bioconda-utils til I understand it...

**Comment by rpetit3** [comment]
@yamaton are you saying you no longer want `gff3toddbj` to be on bioconda? 

The failed test looks like a super easy fix (add `pysam` dependency))

**Comment by yamaton** [comment]
@rpetit3 Thank you for taking care of PRs. 

I meant not to use BiocondaBot, but I'll keep updating `gff3toddbj` in bioconda-recipes by submitting PRs without using `bioconda-utils`.

The fix for this patch is easy, but I just don't know how to update the BiocondaBot's PRs; I really appreciate if there is any reference.

**Comment by rpetit3** [comment]
Ah! We'll need to get you added to the bioconda group. Unfortunately I cannot do that.

Once added you will be able to edit the BiocondaBot PRs

**Comment by rpetit3** [comment]
Is there a particular samtools version you want me to pin to the recipe?

**Comment by yamaton** [comment]
Thank you for the clarification; I'll try to become a member by keeping contributions.
No particular version of `samtools` is needed for `gff3toddbj`. So please add `samtools` as is.

**Comment by rpetit3** [comment]
Got it, in the future please feel free to ping me if you need to make a change to the recipe!

**Comment by rpetit3** [comment]
@yamaton  If this looks good to you I'll go ahead and merge

**Comment by yamaton** [comment]
@rpetit3 Looks great. Thank you so much for your help!

**Review by rpetit3 — APPROVED** [review]

**Comment by rpetit3** [comment]
@biocondabot please merge

**Pull request merged**
