### PR TITLE
Add EzAAI 1.2.2

### PR DESCRIPTION
**Pull request by aaronmussig**
Add the package EzAAI: https://github.com/endixk/ezaai

### CODE REVIEW

**Comment by aaronmussig** [comment]
@BiocondaBot fetch artifacts

**Comment by aaronmussig** [comment]
How rude of me, @BiocondaBot please fetch artifacts

**Comment by aaronmussig** [comment]
@BiocondaBot please fetch artifacts

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@BiocondaBot please merge

**Comment by dpryan79** [comment]
Should be mergable once the CI finishes.

**Comment by dpryan79** [comment]
@BiocondaBot please merge

**Comment by aaronmussig** [comment]
Thanks @dpryan79 !

**Pull request merged**
