### PR TITLE
Stacks 2 0

### PR DESCRIPTION
**Pull request by lecorguille**
* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [X] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [X] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

Continue of this PR: https://github.com/bioconda/bioconda-recipes/pull/6406

### CODE REVIEW

**Comment by lecorguille** [comment]
@bgruening 
This packages needs to be build locally

Many thanks!

**Comment by lecorguille** [comment]
@pbordron may have a better solution
So you can postpone the local build.

**Comment by pbordron** [comment]
I did a pull request here https://github.com/bioconda/bioconda-recipes/pull/7438

**Comment by johanneskoester** [comment]
The other PR has been merged.

**Pull request closed without merging**
