### PR TITLE
Update r-bcbiosinglecell to 0.4.16

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`r-bcbiosinglecell`](https://bioconda.github.io/recipes/r-bcbiosinglecell/README.html): **0.4.13** &rarr; **0.4.16**

[install with bioconda](http://bioconda.github.io/recipes/r-bcbiosinglecell/README.html) [Conda](https://anaconda.org/bioconda/r-bcbiosinglecell/files)

Info | Link
-----|-----
Recipe | [`recipes/r-bcbiosinglecell`](https://github.com//bioconda/bioconda-recipes/tree/bump/r_bcbiosinglecell/recipes/r-bcbiosinglecell) (click to view/edit other files)
Releases |[https://github.com/hbc/bcbioSingleCell/tags](https://github.com/hbc/bcbioSingleCell/tags)
Recipe Maintainer(s) | @mjsteinbaugh
Author | `@hbc`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by mjsteinbaugh** [comment]
Working on this. The recipe requires some updates to dependencies first.

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
Needs an unrelease bcbiobase

**Comment by mjsteinbaugh** [comment]
I'm working on this and will update soon

**Comment by mjsteinbaugh** [comment]
Work on updating required dependencies

**Comment by mjsteinbaugh** [comment]
Working on adding dependency recipes:

- https://github.com/bioconda/bioconda-recipes/pull/27418

**Pull request closed without merging**
