### PR TITLE
Add multicore-tsne

### PR DESCRIPTION
**Pull request by grst**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

Adds a recipe for [multicore-TSNE](https://github.com/DmitryUlyanov/Multicore-TSNE/), which is an accelerated TSNE implementation for single cell analysis.

### CODE REVIEW

**Comment by bgruening** [comment]
@grst I think this package should go to conda-forge as it is not strictly bio* related, isn't it?

**Comment by grst** [comment]
I believe it's only used for single cell RNA-seq and is a (optional) dependency of e.g. [scanpy](https://github.com/theislab/scanpy/) or [scanorama](https://github.com/brianhie/scanorama)

**Comment by bgruening** [comment]
TSNE is a very general algorithm and other implementations are already on conda-forge as fasttsne for example.

**Comment by grst** [comment]
of, fair enough.

**Pull request closed without merging**
