### PR TITLE
Update meta.yaml

### PR DESCRIPTION
**Pull request by davidliwei**
* [x] I have read the guidelines above.
* [x] This PR dates an existing recipe.

Update mageck to version 0.5.4.

### CODE REVIEW

**Comment by bgruening** [comment]
Thanks!

**Comment by johanneskoester** [comment]
This is weird. I can't see mageck-0.5.4 in the channel: https://anaconda.org/bioconda/mageck/files.
Any idea what's going on here?

**Comment by johanneskoester** [comment]
Ah, I guess travis is slow again... Seems that the master build is not yet finished.

**Comment by bgruening** [comment]
@johanneskoester I think the test-repository that runs every 24h slows testing here down as well. I saw some cases where no test is started until the large tests are finished.

**Comment by johanneskoester** [comment]
Yes, it could be that quotas are per account (makes also a lot more sense than per repository. I will try to find a way to increase the testing intervals.

**Comment by johanneskoester** [comment]
Perfect: travis now has a cron job feature (see [here](https://docs.travis-ci.com/user/cron-jobs/)). I will play around with it later today.

**Comment by bgruening** [comment]
Great! We could create a separate account specifically for testing that is independent of the organisation, isn't it?

**Comment by johanneskoester** [comment]
Sure, but that would be cheating somehow. Let's try weekly intervals first.

**Comment by bgruening** [comment]
Let me know if this works, otherwise I will ask them again, they are really open for such kind of issues for open community projects like bioconda.

**Comment by johanneskoester** [comment]
We should have a weekly cron job now.

**Comment by bgruening** [comment]
Great thanks!

**Pull request merged**
