### PR TITLE
Add flye

### PR DESCRIPTION
**Pull request by druvus**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by kyleabeauchamp** [comment]
Cool!

**Comment by kyleabeauchamp** [comment]
Would be good to double check that installing this doesn't clobber an existing installation of minimap2 and/or mappy.

**Comment by druvus** [comment]
Good catch. I missed that it was incorporated since the last abruijn version in bioconda. I will double check it.

**Comment by druvus** [comment]
Flye will install the incorporated minimap2 as flye-minimap2 and mappy is not installed so it should be ok.

**Comment by kyleabeauchamp** [comment]
Looks like there were some very recent bugfixes (https://github.com/fenderglass/Flye/issues/26) that some folks have experienced (e.g., missing config files in the installer).  This definitely impacted your recipe :(

**Comment by druvus** [comment]
@kyleabeauchamp The flye issues should be fixed with #7270

**Pull request merged**
