### PR TITLE
Chicago

### PR DESCRIPTION
**Pull request by daler**
* [ ] I have read the guidelines above.
* [x] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

CHiCAGO bioconductor package plus dependency and example data package

### CODE REVIEW

**Comment by bgruening** [comment]
ping @joachimwolff :)

**Comment by daler** [comment]
@bgruening @joachimwolff I'd like to do chicagoTools as well, but it has no releases. Figured I'd give it a test on some real data first to see if it's useful before writing a recipe.

**Comment by joachimwolff** [comment]
I have created a chicagoTools recipe: https://github.com/joachimwolff/bioconda-recipes/tree/chicagotools/recipes/chicagotools

**Comment by joachimwolff** [comment]
The example data available is incomplete e.g. to run bam2chicago.sh a bam file is missing. I wrote to the authors of chicago and they send me one file. The only issue is that this file is 14 GB large and I do not know if it should be in the example data package or not.

**Comment by daler** [comment]
Do you mean the chicagoTools-specific example data or the PCHiC data bioconductor package?  And is that 14GB file hosted somewhere? We can include a download script to get that data and put it in the right place that can be run by the user after installing the package.

**Comment by joachimwolff** [comment]
It is not hosted anymore but I have it on my hard drive. I have to ask the authors if it is ok to make the file public available. 
The issue is the following: If you want to run bam2chicago.sh and you are looking in the PCHiC data dir at inst/extdata/hg19TestDesign all files that are needed are there, except a bam file. I asked the authors of chicago if they can send me a file bam file that can be used together with the provided files and they sent me that 14 GB bam file. 
@bgruening Are we having somewhere space to host it?

**Comment by daler** [comment]
So the current solution is to manually send that file to anyone who realizes there's missing data (and then asks for it)? This should be resolved by the authors, not bioconda. In any case, I don't think this should block your chicagoTools recipe since we don't run functional tests on bioconda anyway. But it is good for potential users to know.

**Pull request merged**
