### PR TITLE
Update freebayes to 1.3.7

### PR DESCRIPTION
**Pull request by lightning-auriga**
Updates freebayes to 1.3.7.

Upstream changes break conda package detection by meson that was working for the 1.3.6 build. I wasn't able to find any version of the build that detected tabixpp with meson, as tabixpp's package doesn't seem to install the required pc file for pkg-config. There is a version of the build that allows meson to detect vcflib, but it seems to require vcflib in build instead of host. As such, I've just disabled meson's detection for the two packages and overridden them with the relevant compile and linking flags. Open to suggestions on this if someone has something cleaner in mind.

The second patch adjusts a hard coded relative include path that doesn't work with system IntervalTree.

The build script change suppresses a deprecated usage warning from meson. The license file is added for completeness.

There have been an assortment of PRs related to 1.3.6 interacting with vcflib; hopefully this doesn't interfere.

If this PR is merged, it would address #43518 

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

### General instructions

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

### Instructions for avoiding API, ABI, and CLI breakage issues
Conda is able to record and lock (a.k.a. pin) dependency versions used at build time of other recipes.
This way, one can avoid that expectations of a downstream recipe with regards to API, ABI, or CLI are violated by later changes in the recipe.
If not already present in the meta.yaml, make sure to specify `run_exports` (see [here](https://bioconda.github.io/contributor/linting.html#missing-run-exports) for the rationale and comprehensive explanation).
Add a `run_exports` section like this:

```yaml
build:
  run_exports:
    - ...

```

with `...` being one of:

| Case                             | run_exports statement                                               |
| -------------------------------- | ------------------------------------------------------------------- |
| semantic versioning              | `{{ pin_subpackage("myrecipe", max_pin="x") }}`     |
| semantic versioning (0.x.x)      | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}`   |
| known breakage in minor versions | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| known breakage in patch versions | `{{ pin_subpackage("myrecipe", max_pin="x.x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| calendar versioning              | `{{ pin_subpackage("myrecipe", max_pin=None) }}`    |

while replacing `"myrecipe"` with either `name` if a `name|lower` variable is defined in your recipe or with the lowercase name of the package in quotes.

### Bot commands for PR management

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

Note that the <code>@BiocondaBot please merge</code> command is now depreciated. Please just squash and merge instead.

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by lightning-auriga** [comment]
@BiocondaBot please add label

**Comment by bgruening** [comment]
ping @pjotrp - does this look ok for you?

**Comment by pjotrp** [comment]
> ping @pjotrp - does this look ok for you?

looks good to me. Not sure why tabixpp is failing, but no matter, it'll pick up the git submodules.

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
Thanks!

**Comment by lightning-auriga** [comment]
Thank you both! @bgruening @pjotrp

**Pull request merged**
