### PR TITLE
Update Bumbershoot to 3.0.20163.6147e44

### PR DESCRIPTION
**Pull request by chambm**
Describe your pull request here

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by chambm** [comment]
I can't tell what CircleCI is doing. Is there a log to view?

**Comment by druvus** [comment]
@BiocondaBot please fetch artifac

**Comment by dpryan79** [comment]
@bioconda-bot please fetch artifacts

**Comment by dpryan79** [comment]
There have been a few cases where circleci seems to kill a job and still report it as having succeeded.

**Comment by druvus** [comment]
@chambm could you please remove Bumbershoot from the build-fail-blacklist? It will then be built and tested.

**Comment by chambm** [comment]
@bioconda/core What's this about?
```
/opt/conda/conda-bld/bumbershoot_1591633025369/work/libraries/boost-build/src/engine/bin/Linux/b2: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.17' not found (required by /opt/conda/conda-bld/bumbershoot_1591633025369/work/libraries/boost-build/src/engine/bin/Linux/b2)
/opt/conda/conda-bld/bumbershoot_1591633025369/work/libraries/boost-build/src/engine/bin/Linux/b2: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /opt/conda/conda-bld/bumbershoot_1591633025369/work/libraries/boost-build/src/engine/bin/Linux/b2)
/opt/conda/conda-bld/bumbershoot_1591633025369/work/libraries/boost-build/src/engine/bin/Linux/b2: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by /opt/conda/conda-bld/bumbershoot_1591633025369/work/libraries/boost-build/src/engine/bin/Linux/b2)
```

The recipe is building Boost.Build from C sources, so how can it be missing GLIBC to run the executable it just built?

**Comment by chambm** [comment]
But `libraries/boost-build/src/engine/bin/Linux/b2` is built by the build process! The environment can compile the binary but not run it?!

**Comment by bgruening** [comment]
@chambm no, `libraries/boost-build/src/engine/bin/Linux/b2` is shipped in your source tarball.

**Comment by chambm** [comment]
Ah, well spotted! I wondered why I wasn't seeing the build output from building b2, I just figured it was something funky about CircleCI. Thanks for checking!

**Comment by chambm** [comment]
@bioconda-bot please fetch artifacts

**Comment by chambm** [comment]
@bioconda-bot please fetch artifacts

**Comment by chambm** [comment]
@bioconda/core I tested locally and it works. Please review/merge (or who else should I ask to review).

**Comment by bgruening** [comment]
@bioconda-bot please merge

**Pull request merged**
