### PR TITLE
Update: antiSMASH updated allowed versions of hmmer3 and diamond

### PR DESCRIPTION
**Pull request by alexweisberg**
The dependency requirements for antismash were updated to allow more recent versions of hmmer3 and diamond. 

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by alexweisberg** [comment]
Thanks @bgruening for the tip.

It looks like only including antismash and not antismash-lite still gives the same out of space error:

`ERRO Task processing failed: API error (500): {"message":"ApplyLayer exit status 1 stdout:  stderr: write /usr/local/lib/python3.8/site-packages/antismash/databases/clusterblast/proteins.fasta: no space left on device"}`

**Comment by alexweisberg** [comment]
@bgruening I was able to build this recipe locally using 

'bioconda-utils build recipes config.yml --packages antismash' 

and it worked correctly using the new recipe:

`BIOCONDA INFO BUILD SUCCESS antismash-6.1.1-pyhdfd78af_1.tar.bz2`

so it sounds like an issue with the test environment not having enough space allocated.

**Comment by alexweisberg** [comment]
@BiocondaBot please add label

**Comment by alexweisberg** [comment]
@BiocondaBot please fetch artifacts

**Comment by bgruening** [comment]
Just removing this post-link is not a good option isn't it?

I guess I will build this recipe locally and push it when I get some time.

**Comment by alexweisberg** [comment]
That is a good point. I realized that the antismash-lite version is the same as this one, but lacks the database download. So I will update that recipe instead and this one probably shouldn't remove the database downloading post-link. presumably the lite version will build correctly as well.

**Comment by hechth** [comment]
@alexweisberg can this be closed?

**Comment by alexweisberg** [comment]
sure, it can be closed.

**Pull request closed without merging**
