### PR TITLE
pylibseq

### PR DESCRIPTION
**Pull request by molpopgen**
* [X ] I have read the guidelines above.
* [ X] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

OS X builds w/GCC intentionally.

### CODE REVIEW

**Comment by bgruening** [comment]
Thanks!

**Comment by molpopgen** [comment]
Did the OS X build work out?  The logs on Travis were showing up empty to
me, which seemed odd.  I'll try a "conda install" tomorrow and test out the
package on my iMac.

**Comment by bgruening** [comment]
@molpopgen the emtpy travis logs are due to an Travis problem. They try to fix the problem, let's hope the best for tomorrow.

**Comment by molpopgen** [comment]
Yeah, I was noticing it w/several things I was doing today.  Kinda makes debugging tricky.

**Comment by bgruening** [comment]
Indeed, time to investigate other CI solutions ;)

**Pull request merged**
