### PR TITLE
add sracat (take 2)

### PR DESCRIPTION
**Pull request by luizirber**
Add sracat, a program for downloading unordered .sra files.

Overlaps with #30574, trying a different approach to package it.

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by luizirber** [comment]
Tested locally with the BiocondaBot instructions, it works! (doesn't even need to have bioconda in the channel list :wink:)

@wwood I added you as a recipe maintainer, is that OK?

@jgans I also added you as author, and hopefully you don't mind we are packaging it for bioconda

**Comment by wwood** [comment]
Great, thanks @luizirber - I've been working with @jgans to get this project together and packaged for some time now (doing none of the hard work coding) so know he is on board.

**Comment by wwood** [comment]
Did you try sans sra-tools? That would simplify the recipe considerably since the post-link stuff wouldn't be required, I think, and prevent duplication with sra-tools.

Also, can try testing by downloading a .sra file and then extracting that, maybe that works in mulled?

Also, maybe take the `--help` test command from #30574 so that the version is checked?

Appreciate the time you've put into this already, perhaps some of the above is optional, but since we are here..

**Comment by luizirber** [comment]
> Did you try sans sra-tools? That would simplify the recipe considerably since the post-link stuff wouldn't be required, I think, and prevent duplication with sra-tools.

Indeed, I used `ncbi-ngs-sdk` instead and it worked (it was working before with `sra-tools` because it pulled `ncbi-ngs-sdk`, needed for one of the headers).

I was assuming that the post-link stuff was necessary anytime VDB is used, but it worked fine without it (no GUID definition and so on). Removed.

> Also, can try testing by downloading a .sra file and then extracting that, maybe that works in mulled?

I will try, perhaps with a smaller dataset (`SRR000001` is used in `sra-tools`, but it is a 300MB download...)
 
> Also, maybe take the `--help` test command from #30574 so that the version is checked?

Done!

> Appreciate the time you've put into this already, perhaps some of the above is optional, but since we are here..

This is all great feedback, thanks for pointing it out!

**Comment by luizirber** [comment]
>> Also, can try testing by downloading a .sra file and then extracting that, maybe that works in mulled?
>
> I will try, perhaps with a smaller dataset (`SRR000001` is used in `sra-tools`, but it is a 300MB download...)

Hmm, it is not the dataset size that fails in mulled tests. Even running on `SRR5142144` (270kb) never finishes. I can reproduce it using the generated Docker container too, so there is some runtime dependency (probably network related?) missing in the final container that I'm not sure how to debug (how to I put `strace` into the mulled container? =P) // maybe @bioconda/lib or @bioconda/core has any ideas to suggest here?

That said, the package is built and works on Linux and MacOS, so maybe punt the mulled container fixes to another PR?

**Comment by wwood** [comment]
Yeh that could take a while to debug as the answer might lie buried in the SRA API. Thanks for responding to the feedback.

**Comment by wwood** [comment]
@BiocondaBot please merge

**Review by wwood — APPROVED** [review]

**Comment by luizirber** [comment]
@BiocondaBot please merge

**Pull request merged**
