### PR TITLE
MultiQC: v1.8 release

### PR DESCRIPTION
**Pull request by ewels**
Manual version of https://github.com/bioconda/bioconda-recipes/pull/18778 - some extra new dependencies.

It looks like you guys have removed the funky version pinning for matplotlib and stuff that is required elsewhere, so if you're happy that this works, then I'm happy 😄 

Phil

----

Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it. Note that if you are not already a member of the bioconda project (meaning that you can't add this label), please ping `@bioconda/core` so that your PR can be reviewed and merged (please note if you'd like to be added to the bioconda project). Please see https://github.com/bioconda/bioconda-recipes/issues/15332 for more details.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by dpryan79** [comment]
Regarding matplotlib, it's mostly a question of whether your code can really handle <3 and 3.*. I'm assuming not given your change, but I don't know how much longer conda-forge will keep rebuilding matplotlib 2.2.4, since python 2 hits end of life really soon.

**Comment by ewels** [comment]
In my (not very rigorous) tests, everything that wasn’t a release candidate was fine for python 3. But it’s entirely possible that I missed problematic combinations as I didn’t try _that_ hard..

I plan to drop Python 2 support in the next release or so, depending on exactly when that is. I added a warning log message to this release that displays to python 2 users on every run.

**Comment by dpryan79** [comment]
Maybe we relax the matplotlib requirement then.

**Comment by dpryan79** [comment]
Do you have circleci enabled on your fork? If so, please disable it.

**Comment by ewels** [comment]
Yes apparently I did.. Now disabled 👍

**Comment by dpryan79** [comment]
Oh, you explicitly request matplotlib <3, good to know :)

**Comment by ewels** [comment]
Only for Python 2, as mpl > 3 simply blocks python 2 otherwise for setuptools / pip installation. We get around that with dynamic requirements based on python version: https://github.com/ewels/MultiQC/blob/50d1af172a30f8cc8dd331656f4b10f579acb850/setup.py#L36-L42

I used to have something similar here with `[py2k]` etc but others seem to have removed that.

Phil

**Comment by dpryan79** [comment]
Ah, I just made the version restriction incorrectly! I'll fix that in a new PR :)

**Pull request merged**
