### PR TITLE
r-histonehmm cleanup

### PR DESCRIPTION
**Pull request by druvus**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by bgruening** [comment]
Thanks a lot for working on this, I'm banging my head against my desk already ;)

**Comment by druvus** [comment]
@bgruening r-histonehmm passes the test here so you check if the problems remains in the bulk branch.

**Comment by bgruening** [comment]
Done, but I have less hope :(
I changed the gcc already and this was not helping :(

**Comment by bgruening** [comment]
Anyway thanks!

**Pull request merged**
