### PR TITLE
[WIP] Try adding bcftools to OSX whitelist?

### PR DESCRIPTION
**Pull request by kyleabeauchamp**
Not sure if this will work or not, but worth a try.

### CODE REVIEW

**Comment by kyleabeauchamp** [comment]
@brentp 
Are you sure the plugins are working as expected?  I'm finding that on OSX, there are linker failures that only appear when building the extra plugins.  It seems like the plugins are expecting shared object files, but the build process only builds static files by default.  

When I (locally) revert the plugin build, things seem to build OK on OSX.

I imagine this may be as simple as an extra compiler flag, I'll try to dig around for hints.

**Comment by kyleabeauchamp** [comment]
@brentp If you look at the plugin SO files that are included in the lib directory, you will notice that they are all looking for libhts but can't find it because it isn't included in the package:

```
ldd ldd *.so
tag2tag.so:
	libhts.so.1 => not found
```

**Comment by brentp** [comment]
I wasn't sure it was working but seemed fine on my machine (last words, I know). Shall we just make htslib a dependency of bcftools?

And/or any ideas on how to fix it?

**Comment by brentp** [comment]
btw, it'd be good if this was available on mac. I can revert that commit.

**Comment by kyleabeauchamp** [comment]
No worries, my pull #432 comments out the plugin install and adds some comments to the build script about this issue.  I'll merge that and we can work from there.

**Comment by kyleabeauchamp** [comment]
Regarding how to fix plugins, I think it boils down to:

1.  bcftools *does* appear to create a libhts shared object file during make.  We would have to copy that in to the $PREFIX/lib directory during the conda recipe.
2.  The issue I see is that this will lead to version conflicts between the copy of libhts that comes from from an HTSLib install.  We would have to put this file in a special location or something to avoid conflicts.  
3.  The build failure on OSX is presumably because the linker can't find the SO file during the actual build of the plugin objects.  Ways to fix this include either making the base library and plugins in two separate make steps or adjusting the library paths appropriately.

**Comment by kyleabeauchamp** [comment]
Oh and if we do fix the plugins, I suggest that we add an extra `test` command that runs `bcftools plugins -l` and checks that the bcftools executable can actually find the plugins.  E.g. grep for one of the known plugins.

**Pull request closed without merging**
