### PR TITLE
Update blast to 2.13.0

### PR DESCRIPTION
**Pull request by ebete**
Update NCBI-BLAST+ from 2.12.0 to 2.13.0.

Regarding the [phonehome.patch](https://github.com/bioconda/bioconda-recipes/pull/35897/files#diff-a3516561304cb715e7683c966c9a715889eb651aff6341288960d4b237b375f6), it looks like not `#define`ing `NCBI_USAGE_REPORT_SUPPORTED` also disables reporting (see #32791 for more on this).
Besides stopping the phoning home, the preprocessor skips a lot of extra bloat as well.

An example showing that it also stops the usage reporting,
 `ncbi-blast-2.13.0+-src/c++/src/connect/ncbi_usage_report.cpp`, from line 106 onwards:
```c++
bool CUsageReportAPI::IsEnabled(void)
{
#if defined(NCBI_USAGE_REPORT_SUPPORTED)
    return gs_IsEnabled;
#else
    return false;
#endif
}
```

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by ebete** [comment]
@BiocondaBot please fetch artifacts

**Comment by ebete** [comment]
@BiocondaBot please add label

**Comment by daler** [comment]
@dpryan79 I think you had originally raised the phonehome issue (and patch), can you review this one?

**Comment by dpryan79** [comment]
As long as it's not actually phoning home I'm good with a simplification :)

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@BiocondaBot please merge

**Pull request merged**
