### PR TITLE
Add bioconductor-derfinderplot.

### PR DESCRIPTION
**Pull request by cbrueffer**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by cbrueffer** [comment]
The bioconductor-derfinder package hasn't been uploaded to anaconda cloud yet, I'll restart this when it's there.

**Comment by bgruening** [comment]
@cbrueffer thanks a lot for you flow of new packages. What about the following. Please create a giant PR with all packages that you need and target bulk. Please kill the CI jobs on this PR. I will merge this into bulk and care about the rebuilds. Bulk is rebuilding currently for R and Bioc and you will be way faster this way.

Just a suggestion.
Thanks again!

**Comment by cbrueffer** [comment]
Hi Björn, sounds good; I'll take a look at this tomorrow.

**Comment by cbrueffer** [comment]
@bgruening is this still the recommended course of action now that bulk has been merged? Otherwise I can just bunch a few recipes in one PR.

**Pull request merged**
