### PR TITLE
Add recipe for Perl package IO::Pager

### PR DESCRIPTION
**Pull request by xileF1337**
Add recipe for Perl package IO::Pager. I need it as a dependency for another recipe in preparation.

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by rpetit3** [comment]
Hi @xileF1337, I wonder if conda-forge would be a better fit for this package. A quick glance at it seemed to suggest it wasn't necessarily bio-specific.

Curious to get your thoughts

**Comment by xileF1337** [comment]
> Hi @xileF1337, I wonder if conda-forge would be a better fit for this package. A quick glance at it seemed to suggest it wasn't necessarily bio-specific.
> 
> Curious to get your thoughts

@rpetit3 Hi and thanks for your input on this recipe. It is true that the IO::Pager is not by itself a bio-specific package, apart from the fact that I need it for another bio-specific recpie which I am prepairing. The major issue here is that there are so many `perl-*` packages that are on Bioconda already, but not on Conda Forge. To satisfy the dependencies of this recipe (`perl-termreadkey` and `perl-file-which`) and my other ones, I need these packages. As far as I know, Conda Forge does not allow dependencies to Bioconda packages (for obvious reasons). I simply cannot spend so much time and port all dependencies, their dependencies etc. etc. to Conda Forge first.

Just to give an impressive example of the required work: in my upcoming package I use the Moose object system. It is present on Bioconda as `perl-moose`, but not on conda forge. Installing `perl-moose` installs the following dependencies:
```
...
  + perl-apache-test                     1.40  pl526_1           bioconda/linux-64        115 KB
  + perl-app-cpanminus                 1.7044  pl526_1           bioconda/linux-64        Cached
  + perl-base                            2.23  pl526_1           bioconda/linux-64        Cached
  + perl-carp                            1.38  pl526_3           bioconda/linux-64        Cached
  + perl-class-load                      0.25  pl526_0           bioconda/linux-64         12 KB
  + perl-class-load-xs                   0.10  pl526h6bb024c_2   bioconda/linux-64         13 KB
  + perl-constant                        1.33  pl526_1           bioconda/linux-64        Cached
  + perl-data-optlist                   0.110  pl526_2           bioconda/linux-64         10 KB
  + perl-devel-globaldestruction         0.14  pl526_0           bioconda/linux-64          7 KB
  + perl-devel-overloadinfo             0.005  pl526_0           bioconda/linux-64          8 KB
  + perl-devel-stacktrace                2.04  pl526_0           bioconda/noarch          Cached
  + perl-dist-checkconflicts             0.11  pl526_2           bioconda/linux-64         10 KB
  + perl-eval-closure                    0.14  pl526h6bb024c_4   bioconda/linux-64         11 KB
  + perl-exporter                        5.72  pl526_1           bioconda/linux-64        Cached
  + perl-extutils-makemaker              7.36  pl526_1           bioconda/linux-64        Cached
  + perl-getopt-long                     2.50  pl526_1           bioconda/linux-64        Cached
  + perl-module-implementation           0.09  pl526_2           bioconda/linux-64          9 KB
  + perl-module-runtime                 0.016  pl526_1           bioconda/linux-64         15 KB
  + perl-module-runtime-conflicts       0.003  pl526_0           bioconda/linux-64          7 KB
  + perl-mro-compat                      0.13  pl526_0           bioconda/linux-64         10 KB
  + perl-package-deprecationmanager      0.17  pl526_0           bioconda/linux-64         10 KB
  + perl-package-stash                   0.38  pl526hf484d3e_1   bioconda/linux-64         66 KB
  + perl-package-stash-xs                0.28  pl526hf484d3e_1   bioconda/linux-64         21 KB
  + perl-params-util                     1.07  pl526h6bb024c_4   bioconda/linux-64         14 KB
  + perl-parent                         0.236  pl526_1           bioconda/linux-64        Cached
  + perl-pathtools                       3.75  pl526h14c3975_1   bioconda/linux-64         41 KB
  + perl-scalar-list-utils               1.52  pl526h516909a_0   bioconda/linux-64        Cached
  + perl-sub-exporter                   0.987  pl526_2           bioconda/linux-64         30 KB
  + perl-sub-exporter-progressive    0.001013  pl526_0           bioconda/linux-64          8 KB
  + perl-sub-identify                    0.14  pl526h14c3975_0   bioconda/linux-64         12 KB
  + perl-sub-install                    0.928  pl526_2           bioconda/linux-64         10 KB
  + perl-sub-name                        0.21  pl526_1           bioconda/linux-64         13 KB
  + perl-try-tiny                        0.30  pl526_1           bioconda/linux-64         17 KB
  + perl-xsloader                        0.24  pl526_0           bioconda/linux-64        Cached
...
```
Using `conda search` on each dep, I found that `perl-app-cpanminus` is the only one of these packages that is already available on Conda Forge. All other packages need a port to Conda Forge first, and I bet that their own dependencies will multiply the length of this list ...

I understand that the situation is unfortunate and that it would be a good thing to have the Perl packages in Conda Forge. But unless there is some effective solution to this problem, I don't really see any other option but keep submitting my Perl recipes to Bioconda. I hope for your understanding.

**Comment by rpetit3** [comment]
Hi @xileF1337,

I know the feeling all to well when it comes to putting dependencies on conda-forge or here. I've submitted my fair share to both channels. So totally understand your reservations, ultimately not my call though. 

@dpryan79 @bgruening for future reference, how should I deal with perl packages that aren't bio-specific?

**Comment by dpryan79** [comment]
@rpetit3 Submit what you reasonably can to conda-forge, but I know this can be a giant PITA if the dependency stack is here, so I won't personally be strictly enforcing the "bio- packages only on bioconda" rule when it comes to perl stuff. I guess this goes back to my personal philosophy of "don't let the perfect get in the way of getting things done."

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@BiocondaBot please merge

I really wish it were easier to move the perl stack to conda-forge. Volunteers to help would be very welcome.

**Comment by rpetit3** [comment]
Sounds good @dpryan79 thank you!

**Pull request merged**
