### PR TITLE
Update bbmap to 38.91

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`bbmap`](https://bioconda.github.io/recipes/bbmap/README.html): **38.90** &rarr; **38.91**

[install with bioconda](http://bioconda.github.io/recipes/bbmap/README.html) [Conda](https://anaconda.org/bioconda/bbmap/files)

Info | Link
-----|-----
Recipe | [`recipes/bbmap`](https://github.com//bioconda/bioconda-recipes/tree/bump/bbmap/recipes/bbmap) (click to view/edit other files)
Releases |[https://sourceforge.net/projects/bbmap/files/](https://sourceforge.net/projects/bbmap/files/)

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by rpetit3** [comment]
Doesn't look like the tests were run

**Comment by bgruening** [comment]
https://app.circleci.com/pipelines/github/bioconda/bioconda-recipes/50201/workflows/307713c3-cdeb-4cb4-8203-e75f1f8fe918/jobs/162893?invite=true#step-106-931 looks ok to me.

**Comment by rpetit3** [comment]
@bgruening your right! didn't realize the tests get sent to `/dev/null`

```
    - bbmap.sh -V 2>&1 | grep "BBMap" > /dev/null
    - bbmerge.sh -V 2>&1 | grep "BBMerge" > /dev/null
    - bbduk.sh -V 2>&1 | grep "BBDuk" > /dev/null
    - bbmask.sh -V 2>&1 | grep "BBMask" > /dev/null
    - bbnorm.sh --help 2>&1 | grep "BBNorm" > /dev/null
```

**Review by rpetit3 — APPROVED** [review]

**Comment by rpetit3** [comment]
@biocondabot please merge

**Pull request merged**
