### PR TITLE
Build MapSplice on macOS

### PR DESCRIPTION
**Pull request by ccwang002**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by ccwang002** [comment]
C++ compilation failed on macOS due to the following error:

```
g++ -fpermissive -O3 -o bin/FilterFusionAlignmentsByFilteredFusions src/FilterFusionAlignmentsByFilteredFusions/FilterFusionAlignmentsByFilteredFusions.cpp:77:11: error: use of undeclared identifier '__stl_hash_string'
                        return __stl_hash_string(__s.c_str());
```

**Comment by ccwang002** [comment]
It seems that `__stl_hash_string` is missing on macOS. Adding this function will compile. But I am not sure how to do it for many cpp source files.

```cpp
namespace __gnu_cxx
{
	template<typename Traits, typename Allocator>
	struct hash<std::basic_string<char, Traits, Allocator> >
	{
		size_t operator()(const std::basic_string<char, Traits, Allocator>& __s) const
		{
			return __stl_hash_string(__s.c_str());
		}
	};
}
```

to

```cpp
namespace __gnu_cxx
{
    inline size_t __stl_hash_string(const char* __s)
    {
        unsigned long __h = 0;
        for ( ; *__s; ++__s)
            __h = 5 * __h + *__s;
        return size_t(__h);
    }
	template<typename Traits, typename Allocator>
	struct hash<std::basic_string<char, Traits, Allocator> >
	{
		size_t operator()(const std::basic_string<char, Traits, Allocator>& __s) const
		{
			return __stl_hash_string(__s.c_str());
		}
	};
}
```

**Comment by epruesse** [comment]
That looks like you'd have to layer yet another patch on top of the ones we already have here.

Assuming you've got a macos box handy, you'd

```
unzip MapSplice-v2.2.1.zip 
cp -a MapSplice-v2.2.1 MapSplice-v2.2.1.orig
# make edits
diff -rNu MapSplice-v2.2.1.orig  MapSplice-v2.2.1 > fix_hash_string.patch
# copy patch file to recipe and add to meta.yaml
```

**Comment by ccwang002** [comment]
I don't need this tool to work on macOS at the moment. Will create a new PR in future if necessary.

**Pull request closed without merging**
