### PR TITLE
vcflib 1.0.0-rc3

### PR DESCRIPTION
**Pull request by tseemann**
Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it. Note that if you are not already a member of the bioconda project (meaning that you can't add this label), please ping `@bioconda/core` so that your PR can be reviewed and merged (please note if you'd like to be added to the bioconda project). Please see https://github.com/bioconda/bioconda-recipes/issues/15332 for more details.

* [ ] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by tseemann** [comment]
```
09:15:08 BIOCONDA ERROR Skipping unknown check uses_git_url
09:15:16 BIOCONDA DEBUG Found: LintMessage(recipe=Recipe "vcflib", check=<class 'bioconda_utils.lint.check_policy.uses_vcs_url'>, severity=<Severity.ERROR: 30>, title='The recipe downloads source from a VCS', body="\nPlease build from source archives and don't use the `git_url`,\n`svn_url` or `hg_url` feature of conda.", start_line=7, end_line=8, fname='recipes/vcflib/meta.yaml', canfix=False)
The following problems have been found:

ERROR: recipes/vcflib/meta.yaml:8: uses_vcs_url: The recipe downloads source from a VCS
Errors were found
Exited with code 1
```

**Comment by dpryan79** [comment]
@tseemann This is good to merge once you're happy with it.

**Comment by dpryan79** [comment]
Currently this can use any python version. If it's really python 3 only then we can just add >=3 to the python line and merge.

**Comment by tseemann** [comment]
@dpryan79 "Currently this can use any python version" --- how is this true?

**Comment by dpryan79** [comment]
By not specifying a version restriction in the run section the recipe is saying, "any version will do". Normally people will get python3, unless they create a python2 env.

**Comment by tseemann** [comment]
@dpryan79 the reason this new release was made was because it has scripts in it written in py2. It also has `#!/usr/bin/env python` lines, which on conda default to py3 (which i thought violated PEP?) so they would not work.  This release saw the scripts fixed to use `#!/usr/bin/env python3` _and_ the syntax changed to py3. Based on what you say, the recipe shoule be changed to `python >=3` to ensure the tool works as expected?

**Comment by dpryan79** [comment]
Yeah, just change `python` to `python >=3` and it's good to go then.

**Comment by tseemann** [comment]
```
22:40:19 BIOCONDA INFO (OUT) g++ multichoose.cpp -o multichoose
22:40:19 BIOCONDA INFO (OUT) make[1]: g++: Command not found
22:40:19 BIOCONDA INFO (OUT) make[1]: *** [multichoose] Error 127
22:40:19 BIOCONDA INFO (OUT) make[1]: Leaving directory `$SRC_DIR/multichoose'
22:40:19 BIOCONDA INFO (OUT) make: *** [multichoose] Error 2
22:40:21 BIOCONDA INFO (OUT) Traceback (most recent call last):
22:40:21 BIOCONDA INFO (OUT)   File "/opt/conda/bin/conda-build", line 11, in <module>
22:40:21 BIOCONDA INFO (OUT)     sys.exit(main())
```

**Comment by tseemann** [comment]
```
23:09:03 BIOCONDA INFO (OUT) /opt/conda/conda-bld/vcflib_1566688019479/_build_env/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: multichoose.cpp:(.text.startup+0x613): undefined reference to `std::ios_base::Init::~Init()'
```

**Pull request merged**
