### PR TITLE
Update bioconductor flowtype flowmerge flowmeans

### PR DESCRIPTION
**Pull request by PertuyF**
:information_source:
Bioconda has finished the [GCC7 migration](https://github.com/bioconda/bioconda-recipes/issues/13578). If you are dealing with C/C++ or Python package it can be that you need to rebuild other dependent packages. [Bioconda utils - update-pinning](https://bioconda.github.io/updating.html#updating-recipes-for-a-pinning-change) will assist you with that. If you have any questions please use [issue 13578](https://github.com/bioconda/bioconda-recipes/issues/13578).

----------------

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [x] This PR does something else (explain below).

Update recipes and remove from blacklist.

### CODE REVIEW

**Comment by PertuyF** [comment]
@conda-forge-admin, please rerender

**Comment by bgruening** [comment]
@PertuyF that does not work in Bioconda (yet).

**Comment by PertuyF** [comment]
@bgruening thanks for the info. I would like to understand why, could you point me to somewhere I could find more details ? Or just tell me if you prefer :smile:

**Comment by bgruening** [comment]
This is not conda-forge, this is Sparta ... I mean Bioconda :)

@epruesse is working on a bot that will assist you to some degree but we do not need to rerender a feedstock here as we have a global repo with global build-configs.

**Comment by PertuyF** [comment]
The problem with `bioconductor-flowmerge` and `bioconductor-flowmeans` is not not that `r-feature` is missing, but rather it is an `rgl` issue:
```
[Feb 21 14:03:54] SERR Loading required package: feature
[Feb 21 14:03:55] SERR Error in dyn.load(file, DLLpath = DLLpath, ...) :
[Feb 21 14:03:55] SERR unable to load shared object '/usr/local/lib/R/library/rgl/libs/rgl.so':
[Feb 21 14:03:55] SERR libgfortran.so.3: cannot open shared object file: No such file or directory
[Feb 21 14:03:55] SERR Error: package or namespace load failed for 'feature':
[Feb 21 14:03:55] SERR .onLoad failed in loadNamespace() for 'rgl', details:
[Feb 21 14:03:55] SERR call: NULL
[Feb 21 14:03:55] SERR error: 	Loading rgl's DLL failed.
[Feb 21 14:03:55] SERR Error: package 'feature' could not be loaded
```

Last `r-rgl` build is a few months old, may it be linked against a wrong version of `libgfortran`?
Trying to [rebuild](https://github.com/conda-forge/r-rgl-feedstock/pull/9) on conda-forge

**Comment by PertuyF** [comment]
Waiting for PR https://github.com/conda-forge/r-feature-feedstock/pull/4 to complete.

**Comment by PertuyF** [comment]
Replaced by #14081 , closing. Thanks @dbast and @dpryan79 for fixing these 👍

**Pull request closed without merging**
