### PR TITLE
Update docking_py to 0.3.0

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`docking_py`](https://bioconda.github.io/recipes/docking_py/README.html): **0.2.3** &rarr; **0.3.0**

[install with bioconda](http://bioconda.github.io/recipes/docking_py/README.html) [Conda](https://anaconda.org/bioconda/docking_py/files)

Info | Link
-----|-----
Recipe | [`recipes/docking_py`](https://github.com//bioconda/bioconda-recipes/tree/bump/docking_py/recipes/docking_py) (click to view/edit other files)
Releases |[https://pypi.org/pypi/docking_py/json](https://pypi.org/pypi/docking_py/json)
Recipe Maintainer(s) | @samuelmurail

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by samuelmurail** [comment]
Yes , I have added support to autodock which package has been deposit on hcc channel, not on bioconda (https://anaconda.org/HCC/autodock).
So I guess, as a new dependencie is not in conda-forge or bioconda, it cannot be any more on bioconda.

Too bad,
Cheers

**Comment by dpryan79** [comment]
We can just add autodock to bioconda I presume.

**Comment by dpryan79** [comment]
Autodock is in Bioconda now. I'll give the CDN a hour or so to update and then update this PR to include it.

**Comment by dpryan79** [comment]
I should have added autogrid while I was at it...

**Comment by dpryan79** [comment]
Yup, I'll add autogrid too :P

**Comment by dpryan79** [comment]
Crap, I didn't mean to merge this yet!

**Comment by dpryan79** [comment]
Well, I merged in autogrid, so I'll fix this in about an hour when it's available.

**Pull request merged**
