### PR TITLE
Update perl-set-intervaltree and fix build requirements

### PR DESCRIPTION
**Pull request by jmarshall**
Update to upstream Set-IntervalTree-0.12.

Listing the build compiler requirements fixes the build on macOS, so remove from the blacklist "OSX related errors" section.

ExtUtils::CppGuess is needed only when building Set::IntervalTree; at run-time all that is needed is the libcxx runtime.

----

Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it. Note that if you are not already a member of the bioconda project (meaning that you can't add this label), please ping `@bioconda/core` so that your PR can be reviewed and merged (please note if you'd like to be added to the bioconda project). Please see `#15332` for more details.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [ ] This PR adds a new recipe.
* [ ] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by jmarshall** [comment]
@bioconda/core: This is passing tests and appears to be ready to be merged.
(I do not wish to join Bioconda.)

**Comment by bgruening** [comment]
Thanks @jmarshall!

**Comment by jmarshall** [comment]
Any ideas why the macOS package has not been rebuilt at <https://anaconda.org/bioconda/perl-set-intervaltree/files>?

**Comment by bgruening** [comment]
The upload was failing ... I restarted it, keep an eye on: https://circleci.com/workflow-run/fd588188-0af1-4e77-80b4-a68e4f6cbf77

**Comment by dpryan79** [comment]
There's a bug in bioconda-utils that causes this to happen if the OSX worker lags behind the linux workers too much. This would have gotten built by the nightly cron job, but I've merged the master branch into the special bulk branch to hopefully get it there a bit quicker.

**Comment by mbargull** [comment]
Ugh, we fixed the issue but didn't release a new `bioconda-utils` version... whoops! I'll tag a new one momentarily

**Pull request merged**
