### PR TITLE
Update krakenuniq (fix path to jellyfix)

### PR DESCRIPTION
**Pull request by jfy133**
A path to `jellyfish` appears to be hardcoded within the krakenuniq build script.

This replaces it to the location as installed via dependencies.

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by jfy133** [comment]
@apeltzer @rpetit3 any idea?

**Comment by jfy133** [comment]
Macs :shakesfist: sorry @rpetit3 I always forget about that :facepalm:

**Comment by rpetit3** [comment]
you and me both

**Comment by rpetit3** [comment]
@biocondabot please fetch artifacts

**Comment by jfy133** [comment]
@rpetit3 I can also try the docker image tomorrow to make sure it's working (hotel wifi is saying no to downloading anything atm...)

**Comment by jfy133** [comment]
@rpetit3 I can also try the docker image tomorrow to make sure it's working (hotel wifi is saying no to downloading anything atm...)

**Comment by jfy133** [comment]
@rpetit3 I can also try the docker image tomorrow to make sure it's working (hotel wifi is saying no to downloading anything atm...)

**Comment by jfy133** [comment]
@rpetit3 I think this is working now, I run with teh local docker image and it starts running jellyfish correctly (but dies in my test because I run out of memory)

```
         Command output:                                                                                                                                                                           
           Kraken build set to minimize disk writes.                                                                                                                                               
           Finding all library files                                                                                                                                                               
           Found 1 sequence files (*.{fna,fa,ffn,fasta,fsa}) in the library directory.                                                                                                             
           Creating k-mer set (step 1 of 6)...                                                                                                                                                     
           Using jellyfish                                                                                                                                                                         
           Hash size not specified, using '29588'                                                                                                                                                  
           K-mer set created. [0.000s]                                                                                                                                                             
           Skipping step 2, no database reduction requested.                                                                                                                                       
           Sorting k-mer set (step 3 of 6)...         
```

**Review by rpetit3 — APPROVED** [review]

**Comment by rpetit3** [comment]
@BiocondaBot please merge

**Pull request merged**
