### PR TITLE
Build htslib for linux-aarch64

### PR DESCRIPTION
**Pull request by jmarshall**
Add `additional-platforms` entry.

----

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

Note that the <code>@BiocondaBot please merge</code> command is now depreciated. Please just squash and merge instead.

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by jmarshall** [comment]
@BiocondaBot please fetch artifacts

**Review by rpetit3 — DISMISSED** [review]

**Comment by rpetit3** [comment]
Given this is the first (of many!), are we going to assume if the test passes, we are ok to merge?

**Comment by jmarshall** [comment]
Please don't merge this yet, I'm investigating its failure to use the ARM-specific htscodecs code.

**Comment by jmarshall** [comment]
@BiocondaBot please fetch artifacts

**Comment by jmarshall** [comment]
@BiocondaBot please add label

**Review by rpetit3 — APPROVED** [review]

**Pull request merged**
