### PR TITLE
Update lusstr to 0.10

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`lusstr`](https://bioconda.github.io/recipes/lusstr/README.html): **0.9** &rarr; **0.10**

[install with bioconda](http://bioconda.github.io/recipes/lusstr/README.html) [Conda](https://anaconda.org/bioconda/lusstr/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/lusstr`](https://github.com//bioconda/bioconda-recipes/tree/bump/lusstr/recipes/lusstr) (click to view/edit other files)
Summary | Tool for converting NGS sequence data of forensic STR loci to various annotation styles
Home | [https://www.github.com/bioforensics/lusSTR](https://www.github.com/bioforensics/lusSTR)
Releases |[https://github.com/bioforensics/lusSTR/tags](https://github.com/bioforensics/lusSTR/tags)
Recipe Maintainer(s) | @rnmitchell, @standage
Author | `@bioforensics`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by standage** [comment]
Is there a way to install pip packages in the Bioconda build? The streamlit_option_menu package is available from PyPI but not any conda repo.

**Comment by standage** [comment]
Added a new recipe to conda-forge, waiting for them to approve and merge. https://github.com/conda-forge/staged-recipes/pull/27093

**Comment by standage** [comment]
@bioconda/core @bioconda/python Can I please get some help relaunching a failed CI build?

**Review by standage — APPROVED** [review]

**Comment by standage** [comment]
@bioconda/core @bioconda/python This PR had two failed builds yesterday. No apparent issues with the recipe, it looks like it might be intermittent infrastructure issues, but I'm not sure. Assistance please?

**Comment by aliciaaevans** [comment]
@standage Unfortunately, if Azure runners run out of memory, CPU, etc. they tend to just get killed without returning the final logs. Have you tried building this recipe locally with bioconda-utils? If not, I can hopefully try it later today when I have time.

**Comment by standage** [comment]
> Have you tried building this recipe locally with bioconda-utils?

I haven't. I may have known at some point that this was possible, but if so I had forgotten. I will also see if I can set this up locally at some point today.

**Pull request merged**
