### PR TITLE
Update gdsctools to 1.0.1 (rebase of #12219)

### PR DESCRIPTION
**Pull request by martin-raden**
* [ ] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [ ] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

replaces Update gdsctools to 1.0.1 #12219

### CODE REVIEW

**Comment by martin-raden** [comment]
this package is currently blacklisted (for linting?)...

**Comment by bgruening** [comment]
@martin-raden if its blacklisted it normally do not build anymore. Just remove it from the blacklist in this PR.

**Comment by martin-raden** [comment]
@bgruening done..

**Comment by martin-raden** [comment]
seems there are some dependency issues:
```
conda.exceptions.UnsatisfiableError: The following specifications were found to be in conflict:

  - python=3.7

  - scikit-learn==0.18.2 -> python=2.7 -> readline=6.2

  - scikit-learn==0.18.2 -> python=2.7 -> sqlite=3.13

  - scikit-learn==0.18.2 -> python=2.7 -> tk=8.5

conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-64: {'tk=8.5', 'python=3.7', 'readline=6.2', 'sqlite=3.13'}
```

**Comment by martin-raden** [comment]
ping @cokelaer

**Comment by dpryan79** [comment]
No longer needed, closing.

**Pull request closed without merging**
