### PR TITLE
Correct pbcore 1.2.7 version constraint

### PR DESCRIPTION
**Pull request by 0xaf1f**
https://github.com/bioconda/bioconda-recipes/pull/30679 had an issue in that it wasn't running the built-in test suite, so the dependency constraints couldn't be checked. However, the maximum pysam version specified in the meta.yaml was set lower than the minimum version in the requirements.txt. This PR fixes the version constraint and also runs the test suite as part of the build. Cc @bishemma1 

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by 0xaf1f** [comment]
@BiocondaBot please add label

**Comment by raivivek** [comment]
@0xaf1f Is there a particular reason for not using the package version requirements as specified in the original package. I see the following listed requirements:
```
numpy >= 1.7.1
h5py >= 2.0.1
pysam >= 0.9.0
```
Having a flexible version requirement (greater or less) will be better than hard `==` version pinning.

**Comment by 0xaf1f** [comment]
Oh, this is just for version 1.2.7 of the package, which has [this requirements.txt](https://github.com/PacificBiosciences/pbcore/blob/1.2.7/requirements.txt)
```
cython
numpy >= 1.7.1
h5py >= 2.0.1
pysam >= 0.8.4
```

the unit tests only all pass with pysam 0.8.4. 2 out of the 227 tests fail with 0.9.0 and it goes downhill from there

**Review by raivivek — APPROVED** [review]

**Comment by raivivek** [comment]
@BiocondaBot please merge

**Pull request merged**
