### PR TITLE
Update for thermorawfileparser v1.4.1

### PR DESCRIPTION
**Pull request by wholtz**

### CODE REVIEW

**Comment by wholtz** [comment]
@BiocondaBot please add label

**Comment by hechth** [comment]
@wholtz you can add me to the list of maintainers - github doesn't send notifications to organizations unfortunately

Then I'll know if there are some problems.

**Comment by wholtz** [comment]
@hechth - you have been added to the recipe-maintainers

**Comment by hechth** [comment]
@wholtz  Thanks!

**Comment by dpryan79** [comment]
@BiocondaBot please fetch artifacts

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@BiocondaBot please merge

**Pull request merged**
