### PR TITLE
Update metagenome-atlas to 2.6a4

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`metagenome-atlas`](https://bioconda.github.io/recipes/metagenome-atlas/README.html): **2.6a2** &rarr; **2.6a4**

[install with bioconda](http://bioconda.github.io/recipes/metagenome-atlas/README.html) [Conda](https://anaconda.org/bioconda/metagenome-atlas/files)

Info | Link
-----|-----
Recipe | [`recipes/metagenome-atlas`](https://github.com//bioconda/bioconda-recipes/tree/bump/metagenome_atlas/recipes/metagenome-atlas) (click to view/edit other files)
Releases |[https://github.com/metagenome-atlas/atlas/tags](https://github.com/metagenome-atlas/atlas/tags)
Recipe Maintainer(s) | @silask
Author | `@metagenome-atlas`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by SilasK** [comment]
If I understand the [log](https://app.circleci.com/pipelines/github/bioconda/bioconda-recipes/51984/workflows/f829d274-65f8-4daf-b498-f727a1cf909a/jobs/166921) correctly the error is not even with my recipe. conda cannot install python+pip to install the package.

**Comment by SilasK** [comment]
Did anybody in @bioconda/all had a similar problem and could help, please?

**Comment by dpryan79** [comment]
For some reason conda is sucking up all of the memory on the CI node. That usually happens during environment resolution, rather than while installing the dependencies.

**Comment by Maarten-vd-Sande** [comment]
Seems to be a memoryerror of conda itself. The only thing I could find is that it seems to be related to resolving the dependencies:
https://github.com/bioconda/bioconda-recipes/pull/21761#issuecomment-619937367

In the next PR it was solved, perhaps you could get some inspiration from that:
https://github.com/bioconda/bioconda-recipes/pull/21761

**Comment by SilasK** [comment]
Thank you for your answers @dpryan79 and  @Maarten-vd-Sande . I feel less lonly. 

Any Idea how to find a solvable combination of dependencies? I already tried to constrain and enlarge the dependencies' version ranges. Should I try to install the env with mamba and then see what it gives me?

**Comment by dpryan79** [comment]
Yeah, using mamba to partially pre-solve things is the route I end up taking when stuff like this happens.

**Comment by SilasK** [comment]
Ok, thank you very much. It seems that there are dependencies incompatibilities. I figured out a solution by using mamba.

**Review by SilasK — APPROVED** [review]

**Comment by dpryan79** [comment]
Ugh, the conda solver is so memory inefficient :(

**Comment by jamie-arcc** [comment]
> Ugh, the conda solver is so memory inefficient :(

Pretty much everything about conda is inefficient.  Even just running a conda search on my system takes a minute or so, and that's with a 28 core Xeon, 128GB of RAM, and a 10Gbps internet connection

**Comment by SilasK** [comment]
I solved all the dependencies incompatibilities
I use only snakemake-minimal. 
I don't know what to do more 

Yesterday there was no memory problem but conda didn't manage to solve after 4h.

**Comment by jmarshall** [comment]
> I use only snakemake-minimal.

Your run prerequisites still list both `snakemake=6.7` and `snakemake-minimal=6.7`.

**Review by SilasK — CHANGES_REQUESTED** [review]
Need to find a solutin that passees on bioconda

**Review by dpryan79 — APPROVED** [review]

**Comment by lucventurini** [comment]
@SilasK , given my experience in #30342, would you be able to try and *remove* the pinning of python?

I think that for both our packages, it was the presence of `snakemake` rather than `snakemake-minimal` that was making Conda go out of memory. If my suspicion is correct, then pinning your package to `python==3.8` is unnecessary.

**Review by SilasK — APPROVED** [review]

**Comment by SilasK** [comment]
Thank you all for your help. 
the simplification to snakemake-minimal was the thing. 

@ lucventurini I see that pinning the python version is unnecessary but is there a problem with that?

**Comment by lucventurini** [comment]
@SilasK pinning to python 3.8 won't be a real problem for the time being (end of support for the version is 3 years from now, after all). However it may become a hassle for users if they want to install your program within an existing environment with a different python version, forcing them to create a separate environment.

I think it's discouraged for this reason - it makes the installation a bit too rigid.

That said, it's not unheard of.

**Pull request merged**
