### PR TITLE
Updated build-fail-blacklist for packages moved to conda-forge

### PR DESCRIPTION
**Pull request by simonvh**
* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [X] This PR does something else (explain below).

See #13964, these recipes have been migrated to conda-forge.

### CODE REVIEW

**Comment by dpryan79** [comment]
Good catch, thanks @simonvh!

**Comment by epruesse** [comment]
Should the ones for which the migration is complete be listed in `build-fail-blacklist`? Or should they just be removed? Including the `recipes/package-name` folder?

**Comment by epruesse** [comment]
Since we have facility for multiple blacklist, it could be a `migrated-to-conda-forge` blacklist, actually.

**Comment by druvus** [comment]
I believe that also the actual `recipes/package-name` folders should be deleted for migrated packages.

**Comment by dpryan79** [comment]
I'm also fully supportive of deleting the folders and would also suggest removing deprecated versions of bioconductor packages and things like that were the source tarballs vanish with time.

**Comment by dpryan79** [comment]
I'll merge this for now and add this topic to the core meeting agenda.

**Comment by epruesse** [comment]
+1 - just what I was going to suggest. We need a policy on that and consensus on it. But I see no reason to keep the recipes. We might still keep a list of those packages somewhere, perhaps with the hash of the last commit at which they were present, so that they can be resurrected should there be a need at some point. I don't really see a situation for that though.

**Pull request merged**
