### PR TITLE
added cityhash recipe

### PR DESCRIPTION
**Pull request by simonvh**
* [X] I have read the guidelines above.
* [X] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by bgruening** [comment]
:+1:

**Comment by bgruening** [comment]
Thanks @simonvh!

**Comment by johanneskoester** [comment]
This won't work. The cityhash recipe has been added to the root folder instead of the recipes directory. Hence, it wasn't even tested. @simonvh, can you please move it to the recipes subfolder in a new PR? Then, we can see if it works and merge again.

Thanks!

**Comment by bgruening** [comment]
Upps! Sorry!

**Comment by johanneskoester** [comment]
No problem ;-).

**Comment by simonvh** [comment]
That was stupid... will do.

**Pull request merged**
