### PR TITLE
bump build number for prinseq++ to debug #36561

### PR DESCRIPTION
**Pull request by daler**
PR to debug #36561 -- first just try bumping the build number to see if build fails.

### CODE REVIEW

**Comment by daler** [comment]
@bioconda-bot please add label

**Comment by daler** [comment]
@BiocondaBot please fetch artifacts

**Comment by daler** [comment]
Looks like this now comes in with `boost-cpp=1.80.0`, in contrast to the previous versions documented in https://github.com/bioconda/bioconda-recipes/issues/36561. It's working here according to the test.

**Review by cbrueffer — APPROVED** [review]

**Comment by cbrueffer** [comment]
@bioconda-bot please merge

**Pull request merged**
