### PR TITLE
Create new recipe for rebar

### PR DESCRIPTION
**Pull request by ktmeaton**
This pull request creates a new recipe for the program [`rebar`](https://github.com/phac-nml/rebar). `rebar` is a **RE**combination **BAR**code detector, that _detects_ and _visualizes_ recombination between genomic sequences. It was designed primarily with SARS-CoV-2 in mind but has been generalized for other organisms.

`rebar` is written in Rust and I've used the [`nextclade`](https://github.com/nextstrain/bioconda-recipes/blob/f7b372627ae2f65862c03e555fd593f641633889/recipes/nextclade/meta.yaml) recipe as a template. The binaries are pre-compiled for `linux-64`, `osx-64`, and `win-64`. This is my first bioconda PR for a Rust program, so please bear with me as I update the recipe according to the CI results.

### CODE REVIEW

**Comment by ktmeaton** [comment]
The current error I'm troubleshooting is: `rebar: command not found`.

```text
21:12:28 BIOCONDA INFO (OUT) ## Package Plan ##
21:12:28 BIOCONDA INFO (OUT) 
21:12:28 BIOCONDA INFO (OUT)   environment location: /opt/conda/conda-bld/rebar_1701724131855/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl
21:12:28 BIOCONDA INFO (OUT) 
21:12:28 BIOCONDA INFO (OUT) 
21:12:28 BIOCONDA INFO (OUT) The following NEW packages will be INSTALLED:
21:12:28 BIOCONDA INFO (OUT) 
21:12:28 BIOCONDA INFO (OUT)     rebar: 0.2.0-h9ee0642_0 local
21:12:28 BIOCONDA INFO (OUT) 
21:12:28 BIOCONDA INFO (OUT) Preparing transaction: ...working... done
21:12:28 BIOCONDA INFO (OUT) Verifying transaction: ...working... done
21:12:28 BIOCONDA INFO (OUT) Executing transaction: ...working... done
21:12:28 BIOCONDA INFO (OUT) export PREFIX=/opt/conda/conda-bld/rebar_1701724131855/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl
21:12:28 BIOCONDA INFO (OUT) export SRC_DIR=/opt/conda/conda-bld/rebar_1701724131855/test_tmp
21:12:29 BIOCONDA INFO (OUT) + rebar --help
21:12:29 BIOCONDA INFO (OUT) /opt/conda/conda-bld/rebar_1701724131855/test_tmp/run_test.sh: line 7: rebar: command not found
```

 I wonder if it's because I had the flag `relocated_binary: false` set. I don't yet understand what that flag does, so I've removed it.

**Comment by ktmeaton** [comment]
Ah, I need to write a custom script to handle binary relocation myself!

I'm using `nextclade`'s [`build.sh`](https://github.com/bioconda/bioconda-recipes/blob/c20aa93b2f346df36d26f9c00bd059ae0c1a5dda/recipes/nextclade/build.sh) as a template for binary renaming and relocation.

**Comment by ktmeaton** [comment]
@BiocondaBot please add label

**Review by peterpru — APPROVED** [review]
Looks good to me! 💯

**Pull request merged**
