### PR TITLE
adding iSEE (and one of its dependencies, scRNAseq) from R/Bioconductor

### PR DESCRIPTION
**Pull request by federicomarini**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by federicomarini** [comment]
... guessing the first step to be taken is wait for r 3.5.0 to become available on conda-forge

**Comment by bgruening** [comment]
Jupp, and then we need to rebuild the entire R stack ... :(

**Comment by federicomarini** [comment]
Ok, I'll sit tight then 👍 
In the meanwhile, I prepared the backbone for the things that will come 😉 

Keep up the good work guys! (should I/you label this PR as WIP in the meanwhile)
F

**Comment by bgruening** [comment]
Yes, best is to look at the bulk branch and how we do the bioconductor packages there ...

**Comment by federicomarini** [comment]
It looks good now, just added the specific requirement, yay!

Yet before merging it is probably best to wait for the 1.2.0 release version to come out (should be today).

**Comment by bgruening** [comment]
Ok, lets wait :)

**Comment by federicomarini** [comment]
> best to wait for the 1.2.0 release version

I'm not just changing my mind right away, but wouldn't it be better to also have the legacy 1.0.1 version built (a.k.a. I'd merge now, then tomorrow update the recipe for the 1.2.0)?

**Pull request merged**
