### PR TITLE
Bump RNAsamba to 0.2.0

### PR DESCRIPTION
**Pull request by apcamargo**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by apcamargo** [comment]
@bioconda/osx It seems that the root user doesn't have a home directory so the compiler can't be found during the installation. What is the recommendation here?

**Comment by dpryan79** [comment]
@johanneskoester This is the second rust issue on OSX I've seen this week (the other is #18185), do you have any suggestions?

**Comment by acaprez** [comment]
Yeah, I’ve seen the missing HOME on OSX cause issues on a few other things. The workaround I usually use is to set HOME to a temp directory at the beginning of the build script, i.e.

if [ `uname` == Darwin ]; then 
  export HOME=`mktemp -d`
fi

Not sure if that will work here though.

**Comment by apcamargo** [comment]
It worked! Thank you @acaprez!

**Comment by dpryan79** [comment]
Nice tip @acaprez!

**Comment by acaprez** [comment]
Great - glad it worked.

**Pull request merged**
