### PR TITLE
add missing openssl dep to htslib packages that depend on it

### PR DESCRIPTION
**Pull request by lkeegan**
This PR would add a missing dependency on openssl to htslib packages that have been compiled against openssl without openssl in their listed dependencies.

See #39356

(this PR complements #39812 which adds missing openssl version pins to packages that have openssl listed as a dependency without pinning the version)

./show_diff.py output:

```
linux-64::htslib-1.3-1.tar.bz2
-    "curl"
+    "curl",
+    "openssl >=1.1.0,<=1.1.1"
linux-64::htslib-1.3.1-0.tar.bz2
-    "curl"
+    "curl",
+    "openssl >=1.1.0,<=1.1.1"
linux-64::htslib-1.3.1-1.tar.bz2
-    "curl"
+    "curl",
+    "openssl >=1.1.0,<=1.1.1"
linux-64::htslib-1.3.2-0.tar.bz2
-    "curl"
+    "curl",
+    "openssl >=1.1.0,<=1.1.1"
linux-64::htslib-1.4-0.tar.bz2
-    "xz"
+    "xz",
+    "openssl >=1.1.0,<=1.1.1"
linux-64::htslib-1.4.1-0.tar.bz2
-    "xz"
+    "xz",
+    "openssl >=1.1.0,<=1.1.1"
linux-64::htslib-1.5-0.tar.bz2
-    "xz"
+    "xz",
+    "openssl >=1.1.0,<=1.1.1"
linux-64::htslib-1.6-0.tar.bz2
-    "xz"
+    "xz",
+    "openssl >=1.1.0,<=1.1.1"
linux-64::htslib-1.7-0.tar.bz2
-    "xz 5.2*"
+    "xz 5.2*",
+    "openssl >=1.1.0,<=1.1.1"
linux-64::htslib-1.8-0.tar.bz2
-    "xz 5.2*"
+    "xz 5.2*",
+    "openssl >=1.1.0,<=1.1.1"
linux-64::htslib-1.8-1.tar.bz2
-    "xz 5.2*"
+    "xz 5.2*",
+    "openssl >=1.1.0,<=1.1.1"
linux-64::r-cssam-1.4-r42h9f5acd7_4.tar.bz2
-    "r-base >=4.0.5",
+    "r-base >=4.0,<4.1",
linux-64::r-scdc-0-r42h9f5acd7_5.tar.bz2
-    "r-base >=4.0.5",
+    "r-base >=4.0,<4.1",
Downloading: https://conda.anaconda.org/bioconda/osx-64/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/bioconda/osx-64/repodata.json.bz2
osx-64::r-cssam-1.4-r42hb3ea9af_4.tar.bz2
-    "r-base >=4.0.5",
+    "r-base >=4.0,<4.1",
osx-64::r-scdc-0-r42hb3ea9af_5.tar.bz2
-    "r-base >=4.0.5",
+    "r-base >=4.0,<4.1",

```

I'm not sure if the openssl version pinning is correct, as some of these packages appear to be linked against both openssl1 and openssl3?:

```
mamba install -y "htslib==1.3=1" && ldd /home/lkeegan/mambaforge/envs/t1/lib/libhts.so | grep "libcrypto"

        libcrypto.so.1.0.0 => not found
        libcrypto.so.3 => /home/lkeegan/mambaforge/envs/t1/lib/././libcrypto.so.3 (0x00007fb892a00000)
```

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by johanneskoester** [comment]
To me this looks good. What do you say @jmarshall?

**Comment by johanneskoester** [comment]
> I'm not sure if the openssl version pinning is correct, as some of these packages appear to be linked against both openssl1 and openssl3?:

```
mamba install -y "htslib==1.3=1" && ldd /home/lkeegan/mambaforge/envs/t1/lib/libhts.so | grep "libcrypto"

        libcrypto.so.1.0.0 => not found
        libcrypto.so.3 => /home/lkeegan/mambaforge/envs/t1/lib/././libcrypto.so.3 (0x00007fb892a00000)
```

mhm, this is really weird. This very old htslib build can't have been linked against openssl v3. v3 was not released at that time wasn't it?

**Review by johanneskoester — CHANGES_REQUESTED** [review]
In any case, please also bump the version, otherwise the changes won't be deployed.

**Comment by lkeegan** [comment]
> 



> > I'm not sure if the openssl version pinning is correct, as some of these packages appear to be linked against both openssl1 and openssl3?:
> 
> ```
> mamba install -y "htslib==1.3=1" && ldd /home/lkeegan/mambaforge/envs/t1/lib/libhts.so | grep "libcrypto"
> 
>         libcrypto.so.1.0.0 => not found
>         libcrypto.so.3 => /home/lkeegan/mambaforge/envs/t1/lib/././libcrypto.so.3 (0x00007fb892a00000)
> ```
> 
> mhm, this is really weird. This very old htslib build can't have been linked against openssl v3. v3 was not released at that time wasn't it?

Turns out `ldd` also includes [transitive/indirect dependencies](https://stackoverflow.com/questions/15064685/does-ldd-also-show-dependencies-of-dependencies/15064784#15064784), so this is just saying that something htslib is linked against itself depends on openssl3.

`readelf -d` gives only the direct dependencies, which is then just openssl1 as expected:

```
readelf -d  /home/lkeegan/mambaforge/envs/t1/lib/libhts.so | grep "NEEDED"
 0x0000000000000001 (NEEDED)             Shared library: [libz.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libcurl.so.4]
 0x0000000000000001 (NEEDED)             Shared library: [libcrypto.so.1.0.0]
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
```

**Review by johanneskoester — APPROVED** [review]

**Pull request merged**
