### PR TITLE
Update mysqlclient

### PR DESCRIPTION
**Pull request by sebastian-luna-valero**
* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [X] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by sebastian-luna-valero** [comment]
Hi @bioconda/core could you please have a look and let me know why I get `BIOCONDA INFO Nothing to be done.` with this updated recipe?

**Comment by sebastian-luna-valero** [comment]
I can see now. It's been blacklisted, could you please let me know why?

**Comment by sebastian-luna-valero** [comment]
Running `bioconda-utils` locally to find out.

**Comment by sebastian-luna-valero** [comment]
I think this is looking good locally (see below). Will push to check travis.
```
$ git diff
diff --git a/build-fail-blacklist b/build-fail-blacklist
index e4e6774a8..c74c7c976 100644
--- a/build-fail-blacklist
+++ b/build-fail-blacklist
@@ -1,3 +1,2 @@
-recipes/mysqlclient
 recipes/blast/2.2.21
 recipes/mothur/1.36.1

$ bioconda-utils build recipes config.yml --docker --loglevel=info --packages mysqlclient
INFO bioconda_utils.docker_utils:_pull_image(317): BIOCONDA DOCKER: Pulling docker image condaforge/linux-anvil
INFO bioconda_utils.docker_utils:_pull_image(323): BIOCONDA DOCKER: Done pulling image
INFO bioconda_utils.docker_utils:_build_image(363): BIOCONDA DOCKER: Built docker image tag=tmp-bioconda-builder
INFO bioconda_utils.build:build_recipes(233): blacklist: bioconductor-motifbreakr, bioconductor-motifstack, bioconductor-motiv, blast/2.2.21, cap-mirseq, denovogear, detonate, mgkit, mothur/1.36.1, perl-font-afm, r-histonehmm, r-spp
INFO bioconda_utils.build:build_recipes(268): Filtering recipes

Filtering 1 of 1 (100.0%) recipes/mysqlclient
INFO bioconda_utils.build:build_recipes(285): Building and testing 1 recipes in total
INFO bioconda_utils.build:build_recipes(286): Recipes to build:
mysqlclient
INFO bioconda_utils.build:build_recipes(323): Building and testing subdag 0 of 1 (1 recipes)
INFO bioconda_utils.build:build(64): BIOCONDA BUILD START recipes/mysqlclient, env: CONDA_BOOST=1.61;CONDA_GMP=5.1;CONDA_GSL=1.16;CONDA_HDF5=1.8.17;CONDA_HTSLIB=1.4;CONDA_NCURSES=5.9;CONDA_NPY=112;CONDA_PERL=5.22.0;CONDA_PY=36;CONDA_R=3.3.2
INFO bioconda_utils.build:build(122): BIOCONDA BUILD SUCCESS /conda/sebastian/py3/conda-bld/linux-64/mysqlclient-1.3.10-py36_0.tar.bz2, CONDA_BOOST=1.61;CONDA_GMP=5.1;CONDA_GSL=1.16;CONDA_HDF5=1.8.17;CONDA_HTSLIB=1.4;CONDA_NCURSES=5.9;CONDA_NPY=112;CONDA_PERL=5.22.0;CONDA_PY=36;CONDA_R=3.3.2
INFO bioconda_utils.build:build(64): BIOCONDA BUILD START recipes/mysqlclient, env: CONDA_BOOST=1.61;CONDA_GMP=5.1;CONDA_GSL=1.16;CONDA_HDF5=1.8.17;CONDA_HTSLIB=1.4;CONDA_NCURSES=5.9;CONDA_NPY=112;CONDA_PERL=5.22.0;CONDA_PY=27;CONDA_R=3.3.2
INFO bioconda_utils.build:build(122): BIOCONDA BUILD SUCCESS /conda/sebastian/py3/conda-bld/linux-64/mysqlclient-1.3.10-py27_0.tar.bz2, CONDA_BOOST=1.61;CONDA_GMP=5.1;CONDA_GSL=1.16;CONDA_HDF5=1.8.17;CONDA_HTSLIB=1.4;CONDA_NCURSES=5.9;CONDA_NPY=112;CONDA_PERL=5.22.0;CONDA_PY=27;CONDA_R=3.3.2
INFO bioconda_utils.build:build(64): BIOCONDA BUILD START recipes/mysqlclient, env: CONDA_BOOST=1.61;CONDA_GMP=5.1;CONDA_GSL=1.16;CONDA_HDF5=1.8.17;CONDA_HTSLIB=1.4;CONDA_NCURSES=5.9;CONDA_NPY=112;CONDA_PERL=5.22.0;CONDA_PY=35;CONDA_R=3.3.2
INFO bioconda_utils.build:build(122): BIOCONDA BUILD SUCCESS /conda/sebastian/py3/conda-bld/linux-64/mysqlclient-1.3.10-py35_0.tar.bz2, CONDA_BOOST=1.61;CONDA_GMP=5.1;CONDA_GSL=1.16;CONDA_HDF5=1.8.17;CONDA_HTSLIB=1.4;CONDA_NCURSES=5.9;CONDA_NPY=112;CONDA_PERL=5.22.0;CONDA_PY=35;CONDA_R=3.3.2
INFO bioconda_utils.build:build_recipes(396): BIOCONDA BUILD SUMMARY: successfully built 1 of 1 recipes
```

**Comment by bgruening** [comment]
Thanks @sebastian-luna-valero! This should probably also be migrated to conda-forge.

**Comment by sebastian-luna-valero** [comment]
Thanks @bgruening !

Just another question, should the status `BIOCONDA INFO Nothing to be done.` be considered as an error? IMHO it's prone to introduce faulty recipes in the master branch.

**Pull request merged**
