### PR TITLE
Add mixcr recipe

### PR DESCRIPTION
**Pull request by riederd**
Add mixcr
recipe for mixcr: https://github.com/milaboratory/mixcr

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by grst** [comment]
@BiocondaBot please add label

**Comment by dpryan79** [comment]
@bioconda/core Weren't we asked to remove this by the authors last year?

**Comment by mbargull** [comment]
You may want to ask what the status of https://github.com/bioconda/bioconda-recipes/pull/19668#issuecomment-656300115 is.

**Comment by dpryan79** [comment]
Let's close this for now until the authors can update regarding whether they want to now allow redistribution.

**Comment by riederd** [comment]
Strange, according to the license statement at the project page it should be possible to provide the tool as conda package, I thought:

[...]
"Permission to use, copy, modify and distribute any part of this program for educational, research and non-profit purposes, by non-profit institutions only, without fee, and without a written agreement is hereby granted, provided that the above copyright notice, this paragraph and the following three paragraphs appear in all copies."

**Comment by riederd** [comment]
> Let's close this for now until the authors can update regarding whether they want to now allow redistribution.

If I check the license on the project pag, I do not see any issue with providing a conda package.
What do you think?

**Comment by dpryan79** [comment]
I also didn't see an issue when I last added this a few years back, but the authors believed otherwise. Let's wait for their feedback so we don't have to delete the uploaded packages again.

**Pull request closed without merging**
