### PR TITLE
Update strling 0.2.1

### PR DESCRIPTION
**Pull request by christopher-schroeder**
Describe your pull request here
strling update to 0.2.1

### CODE REVIEW

**Comment by christopher-schroeder** [comment]
@BiocondaBot please fetch artifacts

**Comment by christopher-schroeder** [comment]
@BiocondaBot please add label

**Comment by marcelm** [comment]
@Biocondabot please merge

**Comment by christopher-schroeder** [comment]
@BiocondaBot please merge

**Pull request merged**
