### PR TITLE
Update scelvis to 0.8.7

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`scelvis`](https://bioconda.github.io/recipes/scelvis/README.html): **0.8.4** &rarr; **0.8.7**

[install with bioconda](http://bioconda.github.io/recipes/scelvis/README.html) [Conda](https://anaconda.org/bioconda/scelvis/files)

Info | Link
-----|-----
Recipe | [`recipes/scelvis`](https://github.com//bioconda/bioconda-recipes/tree/bump/scelvis/recipes/scelvis) (click to view/edit other files)
Releases |[https://pypi.org/pypi/scelvis/json](https://pypi.org/pypi/scelvis/json)

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Review by holtgrewe — APPROVED** [review]
LGTM

**Comment by marcelm** [comment]
Running `conda mambabuild` locally, I get this:
```
   Encountered problems while solving:
     - package dash-bootstrap-components-1.0.0-pyhd8ed1ab_0 requires dash >=2.0.0, but none of the providers can be installed
```

**Comment by marcelm** [comment]
I got it to work locally by removing the version constraints from `dash` and `dash-bootstrap-components`.

**Comment by holtgrewe** [comment]
@marcelm thanks

**Comment by holtgrewe** [comment]
@BiocondaBot please merge

**Pull request merged**
