### PR TITLE
Update annosine2 to 1.0.5

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`annosine2`](https://bioconda.github.io/recipes/annosine2/README.html): **1.0.4** &rarr; **1.0.5**

[install with bioconda](http://bioconda.github.io/recipes/annosine2/README.html) [Conda](https://anaconda.org/bioconda/annosine2/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/annosine2`](https://github.com//bioconda/bioconda-recipes/tree/bump/annosine2/recipes/annosine2) (click to view/edit other files)
Summary | AnnoSINE_v2 - SINE Annotation Tool for Plant and Animal Genomes
Home | [https://github.com/liaoherui/AnnoSINE_v2](https://github.com/liaoherui/AnnoSINE_v2)
Releases |[https://pypi.org/pypi/annosine2/json](https://pypi.org/pypi/annosine2/json)
Recipe Maintainer(s) | @liaoherui

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by liaoherui** [comment]
@BiocondaBot please add label

**Comment by peterpru** [comment]
Hi, I merged your other PR, could you update this one to add the changes from master, once the other one is done with the merge queue? https://github.com/bioconda/bioconda-recipes/pull/45174

**Comment by liaoherui** [comment]
> Hi, I merged your other PR, could you update this one to add the changes from master, once the other one is done with the merge queue? #45174

Ok，thanks！

**Review by liaoherui — APPROVED** [review]

**Review by liaoherui — APPROVED** [review]
no problem.

**Review by peterpru — APPROVED** [review]

**Pull request merged**
