### PR TITLE
Update bcbiogff to 0.6.6

### PR DESCRIPTION
**Pull request by epruesse**
Update [`bcbiogff`](https://bioconda.github.io/recipes/bcbiogff/README.html): **0.6.4** &rarr; **0.6.6**

[install with bioconda](http://bioconda.github.io/recipes/bcbiogff/README.html) [Conda](https://anaconda.org/bioconda/bcbiogff/files)

Info | Link
-----|-----
Recipe | [`recipes/bcbiogff`](https://github.com//bioconda/bioconda-recipes/tree/bump/bcbiogff/recipes/bcbiogff) (click to view/edit other files)
Releases |[https://pypi.org/pypi/bcbio-gff/json](https://pypi.org/pypi/bcbio-gff/json)

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/updating.html)).

### CODE REVIEW

**Comment by druvus** [comment]
@epruesse seems we got both bcbio-gff and bcbiogff. The pypi name is bcbio-gff  so I guess this should go away after we update the 6 recipes that depends on it.

**Comment by epruesse** [comment]
@druvus Should I close this then? Do you have an issue to track the problem?

**Comment by druvus** [comment]
Added a new issued here:  #14758

**Comment by epruesse** [comment]
Thanks @druvus. Closing this.

Don't delete the branch. That way it won't be bumped again.

**Pull request closed without merging**
