### PR TITLE
Added a new recipe for Tablet.

### PR DESCRIPTION
**Pull request by imilne**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by peterjc** [comment]
Ideally I would include a copy of the licence in the zip file (as a text file, e.g. ``LICENSE.txt``), and then reference this in the ``meta.yaml`` file via the ``license_file`` key.

(I am not merging this new recipe due to the potential conflict of interest as a colleague of Iain).

**Comment by peterjc** [comment]
Or you could use this -  from the filename I didn't initially spot this is the license file:

```
license_file: docs/tablet.html
```

**Comment by imilne** [comment]
Thanks, Peter, that makes sense. I wouldn't merge anything yet, as I still don't know if this builds properly - I couldn't get Travis to play nice with my fork at all. I have a feeling it's going to die on the version-check test as Tablet may spool up a gui-event thread even before that happens, so some kind of "java.awt.AWTError: Can't connect to X11 window" might happen. It didn't show up with local testing as both my linux and mac laptops aren't headless. Flapjack (#6419) doesn't use that so may be ok.

**Comment by peterjc** [comment]
Personally I would use something like ``tablet --version | grep '^Tablet`` for the version check (so that a human can inspect the log), given making an automatic exact regular expression will be tricky (escaping dots etc).

Anyway, that's minor polish - fingers crossed the build checks pass, and we can merge this.

**Comment by imilne** [comment]
We had that, Peter, but it failed every time on Linux - passed fine on macOS though.

**Comment by imilne** [comment]
And build number is 0 again - that was a just a random change to try and get things working in frustration late last night.

**Comment by peterjc** [comment]
Merging given tests now passing and @bgruening's earlier approval.

**Comment by peterjc** [comment]
@imilne the package ought to make its way to the public repository automatically now, check back tomorrow.

**Comment by peterjc** [comment]
I was being too pessimistic on the deployment times, it is live now: https://anaconda.org/bioconda/tablet

**Comment by bgruening** [comment]
Thanks all, nice work!

**Pull request merged**
