### PR TITLE
add older Trinity

### PR DESCRIPTION
**Pull request by tomkinsc**
This adds a recipe for an older version of Trinity (2011-11-26) that
uses an older assembly algorithm that works better with highly diverse
viral genomes. It also restructures the regular trinity build script a
bit to have the Trinity files in a subdir of $BIN to reduce likelihood
of conflicts

### CODE REVIEW

**Comment by johanneskoester** [comment]
Mhm, I don't think putting directories into bin/ is the right way to deal with this. What kind of conflicts are we talking about?

**Comment by tomkinsc** [comment]
I will change the recipe. Where should they go?

**Comment by johanneskoester** [comment]
Good question. According to the [FHS](https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard), The whole thing could go to opt/ and we could put symlinks to the scripts into bin/.

What do you think?

**Comment by tomkinsc** [comment]
`opt/` makes sense. Revisions are in PR #466

**Pull request merged**
