### PR TITLE
Add gff2bed recipe

### PR DESCRIPTION
**Pull request by anthony-aylward**
Add a `gff2bed` recipe to `bioconda-recipes`.

`gff2bed` is a python-only package containing two helper functions for converting GFF3-formated data to BED format.

It is found on PyPI here: https://pypi.org/project/gff2bed/

Source code is on GitLab here: https://gitlab.com/salk-tm/gff2bed/

Overview text from the readme:

# gff2bed

## Overview

[GFF3](https://github.com/The-Sequence-Ontology/Specifications/blob/master/gff3.md) and [BED](https://bedtools.readthedocs.io/en/latest/content/general-usage.html) are common formats for storing the coordinates of genomic features such as genes. GFF3 format is more versatile, but BED format is simpler and enjoys a rich ecosystem of utilities such as [bedtools](https://bedtools.readthedocs.io/en/latest/index.html). For this reason, it is often convenient to store genomic features in GFF3 format and convert them to BED format for genome arithmetic.

This module provides two convenience functions to streamline converting data from GFF3 to BED format for bioinformatics analysis: `parse()`, which reads data from a GFF3 file, and `convert()`, which converts GFF3-formatted data to BED-formatted data that can be passed on e.g. to [pybedtools](https://daler.github.io/pybedtools/).

## Documentation

See full online documentation at [http://salk-tm.gitlab.io/gff2bed](http://salk-tm.gitlab.io/gff2bed)

### CODE REVIEW

**Comment by anthony-aylward** [comment]
@BiocondaBot please add label

**Comment by holtgrewe** [comment]
@anthony-aylward could you have a look at other python package's meta.yaml file and adjust section order and use of variables. One example of a simple package is my currently under review:

- https://github.com/bioconda/bioconda-recipes/pull/38515

**Comment by anthony-aylward** [comment]
> @anthony-aylward could you have a look at other python package's meta.yaml file and adjust section order and use of variables. One example of a simple package is my currently under review:
> 
>     * [Adding ngs-chew v0.6.0 #38515](https://github.com/bioconda/bioconda-recipes/pull/38515)

Thanks for the advice, I revised my meta.yaml and I think it now conforms with the one you linked to.

**Comment by dpryan79** [comment]
@BiocondaBot please fetch artifacts

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@BiocondaBot please merge

**Pull request merged**
