### PR TITLE
Moabs v1.3.7.9

### PR DESCRIPTION
**Pull request by lijinbio**
Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

 * `@BiocondaBot please update` will cause the BiocondaBot to merge the master branch into a PR
 * `@BiocondaBot please add label` will add the `please review & merge` label.
 * `@BiocondaBot please fetch artifacts` will post links to packages and docker containers built by the CI system. You can use this to test packages locally before merging.

For members of the Bioconda project, the following command is also available:

 * `@BiocondaBot please merge` will cause packages/containers to be uploaded and a PR merged. Someone must approve a PR first! This has the benefit of not wasting CI build time required by manually merging PRs.

If you have questions, please post them in gitter or ping `@bioconda/core` in a comment (if you are not able to directly ping `@bioconda/core` then the bot will repost your comment and enable pinging).

### CODE REVIEW

**Comment by bgruening** [comment]
@BiocondaBot please fetch artifacts

**Comment by npavlovikj** [comment]
Merged in https://github.com/bioconda/bioconda-recipes/pull/19491.

**Comment by lijinbio** [comment]
> Merged in #19491.

Hi @npavlovikj, thank you for your merge of my PR. in fact, you are supposed to merge the PR #19490, instead of #19491. There are two files changed in #19490, where the post-link.sh is also updated for the existing file check. Can you help suggest how could I submit the PR for this post-link.sh only? Thank you.

**Comment by npavlovikj** [comment]
@lijinbio , sorry about that - I didn't check this PR until after I merged the other one... Please submit another PR, increase the build number to 1 and modify post-link.sh accordingly. If you need any help, please let me know.

**Comment by lijinbio** [comment]
> @lijinbio , sorry about that - I didn't check this PR until after I merged the other one... Please submit another PR, increase the build number to 1 and modify post-link.sh accordingly. If you need any help, please let me know.

Yes, I can submit a new PR with an increased build number to 1. I have a question with respect to the build number. When the MOABS has a new release, Bioconda will build the new version automatically. However, will the build number be reduced to 0 for an update? If I understand correctly, the `meta.yaml` will only change the version number and its checksum, but not the build number, right? If so, how could I make sure the build number back to 0 for an update? Thank you.

**Comment by lijinbio** [comment]
> @lijinbio , sorry about that - I didn't check this PR until after I merged the other one... Please submit another PR, increase the build number to 1 and modify post-link.sh accordingly. If you need any help, please let me know.

@npavlovikj Yes, I can submit a new PR with an increased build number to 1. I have a question with respect to the build number. When the MOABS has a new release, Bioconda will build the new version automatically. However, will the build number be reduced to 0 for an update? If I understand correctly, the `meta.yaml` will only change the version number and its checksum, but not the build number, right? If so, how could I make sure the build number back to 0 for an update? Thank you.

**Comment by npavlovikj** [comment]
When a new version of a package is released, the build number should be 0. When modifications are done to the recipe, but the version remains the same, then the build number is being increased. The Bioconda bot detects a new version only, thus the build number is set to 0 and the version and checksum are updated accordingly. 

In this specific case, the newer 1.3.7.9 version of MOABS with build number 0 is already added with my previous merge. Since you need to update the current recipe with the same version, you will need to increase the build number to 1. For any modification of already existing version, the build number is increased, and can not be reset to 0. This is ok, since one doesn't use the build number to install package usually, and when installing a package the newest build is always installed.

Does this make sense?

**Comment by lijinbio** [comment]
> When a new version of a package is released, the build number should be 0. When modifications are done to the recipe, but the version remains the same, then the build number is being increased. The Bioconda bot detects a new version only, thus the build number is set to 0 and the version and checksum are updated accordingly.
> 
> In this specific case, the newer 1.3.7.9 version of MOABS with build number 0 is already added with my previous merge. Since you need to update the current recipe with the same version, you will need to increase the build number to 1. For any modification of already existing version, the build number is increased, and can not be reset to 0. This is ok, since one doesn't use the build number to install package usually, and when installing a package the newest build is always installed.
> 
> Does this make sense?

Hi @npavlovikj , yes, many thanks for your detailed explanation. I understand now that the build number will be 0 when I release a new version of MOABS. And I don't need to worry about the meta.yaml to reset the build number by myself. I have just submitted a PR (https://github.com/bioconda/bioconda-recipes/pull/19496) to update the post-link.sh only, and the build number is 1. This PR is currently under the Circle CI check. Please help review this PR when the check passes. Thank you.

**Comment by npavlovikj** [comment]
That sounds good @lijinbio ! The new PR looks good to me, so I will go ahead and merge it once the tests pass.

**Pull request closed without merging**
