### PR TITLE
added build files for pathogist

### PR DESCRIPTION
**Pull request by realseanla**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

Please and thank you!

### CODE REVIEW

**Comment by druvus** [comment]
cplex is a missing dependency

**Comment by realseanla** [comment]
I think the reason is that cplex is taken from the conda channel `ibmdecisionoptimization`, and the build tests might not have access to that channel, so it's throwing a dependency error.
@druvus do you think this could be the issue?

**Comment by bgruening** [comment]
@realseanla yes. You need to add cplex to conda-forge at first.

**Comment by realseanla** [comment]
@bgruening I don't own cplex, IBM does. I'm not sure whether I have the legal right to add a private organization's proprietary software to conda-forge. Is there a way to link the `ibmdecisionoptimization` to the circleci tests?

**Pull request closed without merging**
