### PR TITLE
Update pantools to v4.1.1

### PR DESCRIPTION
**Pull request by dirkjanvw**
This pull request updates the PanTools recipe to v4.1.1 (needed because v4.1.0 seemed disfunctional via bioconda and this updated version fixes that).

### CODE REVIEW

**Comment by dirkjanvw** [comment]
@BiocondaBot please add label

**Review by johanneskoester — APPROVED** [review]

**Comment by johanneskoester** [comment]
@BiocondaBot please merge

**Comment by dirkjanvw** [comment]
@johanneskoester do you know why the merge failed? (is there something I need to change to the recipe?)

**Comment by dirkjanvw** [comment]
@BiocondaBot please merge

**Pull request merged**
