### PR TITLE
Recipes for GhostScript 9.07 and 9.10

### PR DESCRIPTION
**Pull request by peterjc**
* [X] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [X] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

In order to facilitate Galaxy Admins transitioning from Galaxy's old packaging system to Conda, this pull request adds recipes for old versions of GhostScript available as packages on the Galaxy Tool Shed,

* https://toolshed.g2.bx.psu.edu/view/iuc/package_ghostscript_9_07/
* https://toolshed.g2.bx.psu.edu/view/devteam/package_ghostscript_9_10/

See also https://github.com/galaxyproject/tools-iuc/issues/1001

### CODE REVIEW

**Comment by bgruening** [comment]
Thats great! Can you please follow these guidelines? https://bioconda.github.io/guidelines.html#c-c

**Comment by peterjc** [comment]
I just re-worked the existing recipe.

Are you saying rather than just:

```
requirements:
  build:
    - gcc
```

you'd like this added to them all?

```
requirements:
  build:
    - gcc   # [not osx]
    - llvm  # [osx]

  run:
    - libgcc    # [not osx]
```

**Comment by peterjc** [comment]
@bgruening is this OK to merge now?

**Comment by bgruening** [comment]
Yes perfect!

**Comment by peterjc** [comment]
Thank you

**Pull request merged**
