### PR TITLE
Update matchtigs to 1.5.0

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`matchtigs`](https://bioconda.github.io/recipes/matchtigs/README.html): **1.3.1** &rarr; **1.5.0**

[install with bioconda](http://bioconda.github.io/recipes/matchtigs/README.html) [Conda](https://anaconda.org/bioconda/matchtigs/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/matchtigs`](https://github.com//bioconda/bioconda-recipes/tree/bump/matchtigs/recipes/matchtigs) (click to view/edit other files)
Summary | Different algorithms for computing small and minimum plain text representations of kmer sets.

Home | [https://github.com/algbio/matchtigs.git](https://github.com/algbio/matchtigs.git)
Releases |[https://github.com/algbio/matchtigs/tags](https://github.com/algbio/matchtigs/tags)
Recipe Maintainer(s) | @sebschmi
Author | `@algbio`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by sebschmi** [comment]
Please also merge #37549, since as of now, this recipe is actually wrong.

**Comment by dpryan79** [comment]
@sebschmi I've sent you an invite to join Bioconda so you can more easily maintain this recipe.

**Comment by dpryan79** [comment]
@BiocondaBot please fetch artifacts

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@BiocondaBot please merge

**Comment by sebschmi** [comment]
Great, thanks!

**Pull request merged**
