### PR TITLE
Add refgenie

### PR DESCRIPTION
**Pull request by apeltzer**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by dpryan79** [comment]
Much better, thanks :)

**Comment by apeltzer** [comment]
This needs all of the dependencies to be bundled first - all of them on Pypi but I'll see when I find the time for that 😓

**Comment by johanneskoester** [comment]
@nsheff can you help us here? Would be great for being able to adopt refgenie in pipelines! All of the missing dependencies need to go into conda-forge.
Also, there seems to be a name clash. Here in bioconda, we have a recipe called pypiper. The homepage of that seems to point to your framework. However, on pypi, there is piper and pypiper, which seem to be from different authors...

**Comment by nsheff** [comment]
Yes. @michalstolarczyk can you handle wrapping up the dependencies into conda-forge?


> Also, there seems to be a name clash. Here in bioconda, we have a recipe called pypiper. The homepage of that seems to point to your framework. However, on pypi, there is piper and pypiper, which seem to be from different authors...

The package is named `pypiper`, but the pypi name is `piper` ... I started the project years before the other one, and went I went to get the `pypiper` name on pypi, they had just a few weeks earlier claimed in for a new project. I requested if they would let me use the pypi name to avoid name clashes, since I had been developing pypiper for years, but they were unwilling to give up the name and have continued their project.

What do you want us to do in this situation? The conda name is pypiper, which is correct, but I was unable to secure that name from pypi.

**Comment by michalstolarczyk** [comment]
I've wrapped up all the project dependencies info `conda-forge`. The only ones missing are:
- `refgenconf` -- PR opened here https://github.com/bioconda/bioconda-recipes/pull/18500
- `pypiper`, which we are not sure what to do with

**Comment by michalstolarczyk** [comment]
Also, the `refgenie` recipe  here is outdated, which this [PR](https://github.com/bioconda/bioconda-recipes/pull/18502) fixes

**Comment by nsheff** [comment]
@johanneskoester I've asked again if we can use pypiper on pypi, but if the current author is not willing to grant it, is another option to switch the conda name to using `piper` to match the pypi package name? Please let us know what you'd like us to do.

**Comment by nsheff** [comment]
@michalstolarczyk can you just re-package up pypiper as 'piper' in bioconda? will that solve the problem?

**Comment by michalstolarczyk** [comment]
[PR](https://github.com/bioconda/bioconda-recipes/pull/18504) for `piper` recipe

**Comment by dpryan79** [comment]
Piper was just merged in, so hopefully this can move forward now :)

**Comment by apeltzer** [comment]
Thanks for letting me know - will work on this today once everything is available on conda-forge/bioconda 👍

**Comment by dpryan79** [comment]
Given that python 2 is going away we should rebuild piper (or pypiper and remove one of the recipes) to use python 3 only (it needs to be run through 2to3 it seems).

**Comment by dpryan79** [comment]
I made a new piper build that runs `2to3` on everything so hopefully it will work better with python 3.

**Comment by dpryan79** [comment]
This is good to go I think.

**Pull request merged**
