### PR TITLE
Fix cesm 2.1.3 problem with netcdf-fortran

### PR DESCRIPTION
**Pull request by annefou**
Our users are now migrating to cesm 2.1.3 and it does not work because of libnetcdff (netcdf-fortran:
```
-rw-rw-r--. 3 centos centos 2573860 Aug 31  2019 libnetcdff.a
-rwxrwxr-x. 3 centos centos 1617728 Aug 31  2019 libnetcdff.so.6.2.1
lrwxrwxrwx. 1 centos centos      19 May 19 20:22 libnetcdff.so -> libnetcdff.so.6.2.1
lrwxrwxrwx. 1 centos centos      19 May 19 20:22 libnetcdff.so.6 -> libnetcdff.so.6.2.1
```

when using `ldd` on `libnetcdff.so`:

```
ldd libnetcdff.so
        linux-vdso.so.1 =>  (0x00007fffec099000)
        libnetcdf.so.15 => not found
        libgfortran.so.4 => /home/centos/miniconda2/envs/__cesm@2.1.3/lib/././libgfortran.so.4 (0x00007f61f616a000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f61f5d3e000)
        libquadmath.so.0 => /home/centos/miniconda2/envs/__cesm@2.1.3/lib/././libquadmath.so.0 (0x00007f61f612f000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f61f5a3c000)
        libgcc_s.so.1 => /home/centos/miniconda2/envs/__cesm@2.1.3/lib/././libgcc_s.so.1 (0x00007f61f5a28000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f61f610c000)
```

So `libnetcdf.so.15` is not found because we have:

```
 ls -lrt libnetcdf.so*
-rwxrwxr-x. 3 centos centos 1505488 Mar 30 12:12 libnetcdf.so.18
lrwxrwxrwx. 1 centos centos      15 May 19 20:22 libnetcdf.so -> libnetcdf.so.18
```

So I am trying to upgrade netcdf-fortran in cesm recipe; I hope it will take a newer version of netcdf.

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by annefou** [comment]
@bgruening Yes, I was also wondering if rebuilding would be enough. 
How can we check we don't have dependencies with the "wrong" netCDF C library for netcdf Fortran?
Thanks!

**Comment by bgruening** [comment]
@BiocondaBot please fetch artifacts

**Comment by bgruening** [comment]
@annefou above you see links and instructions how you can test it.

I think netcdf-fortran should also get run_exports to fix this properly.

**Comment by annefou** [comment]
Great! Now it works. Thanks!

**Comment by bgruening** [comment]
@BiocondaBot please merge

**Pull request merged**
