### PR TITLE
Update seqsero2 to 1.1.0

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`seqsero2`](https://bioconda.github.io/recipes/seqsero2/README.html): **1.0.2** &rarr; **1.1.0**

[install with bioconda](http://bioconda.github.io/recipes/seqsero2/README.html) [Conda](https://anaconda.org/bioconda/seqsero2/files)

Info | Link
-----|-----
Recipe | [`recipes/seqsero2`](https://github.com//bioconda/bioconda-recipes/tree/bump/seqsero2/recipes/seqsero2) (click to view/edit other files)
Releases |[https://github.com/denglab/SeqSero2/tags](https://github.com/denglab/SeqSero2/tags)
Recipe Maintainer(s) | @LSTUGA
Author | `@denglab`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by npavlovikj** [comment]
@BiocondaBot please fetch artifacts

**Comment by npavlovikj** [comment]
@BiocondaBot please merge

**Comment by LSTUGA** [comment]
@npavlovikj I have an installaion issue. When I run "conda install -c bioconda seqsero2", it didn't installed the latest version v1.1.0. Instead, a old version v1.0.1 was installed. Could you please help me have a look at this issue?
Thanks in advance!

**Comment by npavlovikj** [comment]
@LSTUGA , I would suggest you to use `conda create -n seqsero2 seqsero2=1.1.0` instead. This command will create a new environment with the correct version. When you do `conda install`, the package is being installed in an already existing environment. Sometimes, the packages in this environment are not compatible with the packages used in the newest version of `seqsero2`, so whatever version is compatible will be installed, which looks like it is 1.0.1 in your case.
I hope this helps.

**Comment by LSTUGA** [comment]
@npavlovikj Thank you very much for your quick reply and explanation. There is another issue. When I run conda create -n seqsero2 seqsero2=1.1.0, it goes to install v1.0.1 incorrectly (seqsero2           bioconda/noarch::seqsero2-1.01-py_0). Howover, this command works without any probelm with a previous version 1.0.2. Is there anything worong with the packaging of v1.1.0? Thanks!

**Comment by npavlovikj** [comment]
Now that is a good question :) Looks like there is `seqsero2` 1.0.1, 1.01, 1.0.2 and 1.1.0, but the default version is **1.01**, https://anaconda.org/bioconda/seqsero2:
```
# Name                       Version           Build  Channel             
seqsero2                       1.0.1            py_0  bioconda            
seqsero2                       1.0.2            py_0  bioconda            
seqsero2                        1.01            py_0  bioconda            
seqsero2                       1.1.0            py_0  bioconda
```

When I try to install `seqsero2=1.1.0`, actually `seqsero2-1.01` is being installed. I don't know if this happens because of the order or `1.1.0` vs `1.01`, or due to some dependencies. Maybe @bioconda/core has any suggestions?

**Comment by dpryan79** [comment]
I wonder if bumping the build number here fixes this. The extra 0 in 1.01 is likely messing up the comparison.

**Comment by npavlovikj** [comment]
Thanks Devon, that is a good idea. Looks like there is newer 1.1.1 version of the package (https://github.com/bioconda/bioconda-recipes/pull/21846). Let's see if that works, otherwise we can try bumping the build number next.

**Pull request merged**
