### PR TITLE
Build entrez-direct from source code instead of using prebuilt binaries

### PR DESCRIPTION
**Pull request by jmarshall**
Rewrite the recipe to build the Go executables from _edirect.tar.gz_ rather than using prebuilt executables. Add Linux-aarch64 support by patching the various scripts that switch on architecture and building the executables as `<tool>.ARM64` on this platform. Update to the current 21.6.

----

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

Note that the <code>@BiocondaBot please merge</code> command is now depreciated. Please just squash and merge instead.

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by jmarshall** [comment]
@BiocondaBot please fetch artifacts

**Comment by jmarshall** [comment]
@BiocondaBot please fetch artifacts

**Comment by jmarshall** [comment]
@BiocondaBot please fetch artifacts

**Comment by jmarshall** [comment]
@BiocondaBot please fetch artifacts

**Comment by jmarshall** [comment]
@BiocondaBot please add label

**Review by rpetit3 — APPROVED** [review]

**Comment by rpetit3** [comment]
@jmarshall if you are good with it feel free to merge

**Pull request merged**
