### PR TITLE
Add recipe perl-uri-query

### PR DESCRIPTION
**Pull request by fgiacomoni**
Describe your pull request here

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Review by Lain-inrae — APPROVED** [review]

**Comment by fgiacomoni** [comment]
@BiocondaBot please add label

**Comment by daler** [comment]
@fgiacomoni as per the PR template:

> New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.

There are a lot of perl packages in bioconda for historical reasons, but would you please submit this to conda-forge instead since it's not directly related to biomedical research?

**Comment by fgiacomoni** [comment]
@daler Thank you for your message. I'm gonna move on conda-forge this recipe... Time is precious...

**Comment by fgiacomoni** [comment]
Close and moved on conda-forge...

**Comment by fgiacomoni** [comment]
@daler, after spend a whole morning to understand how conda-forge working and push my PR, I just discover that all dependancies of a conda recipe must be hosted under conda-forge... and for me, Perl-uri and Perl-clone, ... are only available under bioconda which is not considered as a channel under conda-forge during build... Do you have any idea of dealing with such tricky things... because I afraid I can't create all perl recipe available under bioconda for conda-forge.

**Comment by bgruening** [comment]
@fgiacomoni in this case feel free to move the bioconda recipes to conda-forge.

**Comment by fgiacomoni** [comment]
I noted 579 perl recipes into bioconda. As mentioned in 2019 [issue](https://github.com/bioconda/bioconda-recipes/issues/13964), perl migration will be for sure tricky ;-). Perl is a bioinformatics programming language and I didn't understand why some package are accepted (example: [perl-uri update](https://github.com/bioconda/bioconda-recipes/pull/35766)) and some other are labelled as "Move to Conda-Forge" (ex: [perl-test-simple](https://github.com/bioconda/bioconda-recipes/pull/35760)). On conda-forge, the lint process detected if the new added recipe already existing on Bioconda... and make comment on this... Recipe with the same name exists in bioconda: please discuss with @conda-forge/bioconda-recipes...

**Comment by daler** [comment]
@fgiacomoni some historical context:

Originally, conda-forge did not accept Perl packages at all. Since many bioinformatics tools used Perl, we needed to add all those dependencies to bioconda. This incurred a large technical debt that we are still digging out from.

Now, conda-forge supports Perl and supports general packages. So we are slowly Perl migrating packages as they pop up over to conda-forge. @cbrueffer for example has been doing a lot of this recently.

Yes, it is a big job, and it is complicated and there are a lot of moving parts. We're all trying to do what we can (in between meetings and trying to run our own research programs). If you are at all familiar with Perl we could use your help.

Here is a pair of PRs you can use as an example/template:

1. Adding `perl-memoize` to conda-forge: https://github.com/conda-forge/staged-recipes/pull/20017
2. The corresponding one deleting it in bioconda:  https://github.com/bioconda/bioconda-recipes/pull/36382

The tricky part is figuring out which Perl packages should be migrated first. Like the early days of bioconda, the most straightforward way is to start with a package you want, and then observe how it fails and which dependencies are missing, and incrementally (and recursively) add those to conda-forge as well.

**Comment by cbrueffer** [comment]
The `perl-clone` and `perl-uri` dependencies of this package have quite a few sub-dependencies; I've started on adding those to conda-forge. I think early next week everything is in place to add this recipe to conda-forge as well.

**Comment by fgiacomoni** [comment]
I have a couple of days to try to prepare a new recipe version of metabolomics::Fragment::Annotation with perl-uri-query deps ! Thank you @cbrueffer for help and @daler for the (hi)story.

**Pull request closed without merging**
