### PR TITLE
Update netreg to 1.8.0

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`netreg`](https://bioconda.github.io/recipes/netreg/README.html): **1.6.0** &rarr; **1.8.0**

[install with bioconda](http://bioconda.github.io/recipes/netreg/README.html) [Conda](https://anaconda.org/bioconda/netreg/files)

Info | Link
-----|-----
Recipe | [`recipes/netreg`](https://github.com//bioconda/bioconda-recipes/tree/bump/netreg/recipes/netreg) (click to view/edit other files)
Releases |[https://github.com/dirmeier/netReg/tags](https://github.com/dirmeier/netReg/tags)
Author | @dirmeier
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by dirmeier** [comment]
This should not be merged right away (even with succeeding CI) as I am trying out if I can drop the C++ tool entirely and replace it with [tensorflow](https://tensorflow.rstudio.com/).

**Comment by dpryan79** [comment]
@dirmeier I've fixed this PR, should we still hold off on merging?

**Comment by dirmeier** [comment]
Hey @dpryan79, yes, sorry for wasting your time, but I think we can actually remove the recipe entirely.

`netReg` was originally developed for Bioconductor and has a separate bioconda recipe for that anyways (https://anaconda.org/bioconda/bioconductor-netreg). Since most of the code was in C++ I thought it made sense to have a command line version, too, for people who don't like `R`. However, since there's TensorFlow for R (or quite some time now,  I could replace the C++ code base.

So should we remove this recipe and leave it with the Bioconductor version?

**Comment by dpryan79** [comment]
That's up to you since it's your package :)

**Comment by dpryan79** [comment]
We might as well merge this in now in case someone needs it.

**Comment by dpryan79** [comment]
@bioconda-bot merge

**Comment by dirmeier** [comment]
Oh, I'm so sorry, I didn't see it in time. 
Alright, sounds good. So we leave this version in and starting from the next, I'll remove it.

To remove it, would I just delete the recipe folder and do a PR?

**Comment by dpryan79** [comment]
Yup, exactly.

**Pull request merged**
