### PR TITLE
add r-fsa

### PR DESCRIPTION
**Pull request by nick-youngblut**
Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it.

* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [X] This PR adds a new recipe.
* [X] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

 * `@BiocondaBot please update` will cause the BiocondaBot to merge the master branch into a PR
 * `@BiocondaBot please add label` will add the `please review & merge` label.
 * `@BiocondaBot please fetch artifacts` will post links to packages and docker containers built by the CI system. You can use this to test packages locally before merging.

For members of the Bioconda project, the following command is also available:

 * `@BiocondaBot please merge` will cause packages/containers to be uploaded and a PR merged. Someone must approve a PR first! This has the benefit of not wasting CI build time required by manually merging PRs.

If you have questions, please post them in gitter or ping `@bioconda/core` in a comment (if you are not able to directly ping `@bioconda/core` then the bot will repost your comment and enable pinging).

### CODE REVIEW

**Comment by nick-youngblut** [comment]
@BiocondaBot please add label

**Comment by dpryan79** [comment]
Please put this in conda-forge (it will need r-epitools as well).

**Comment by nick-youngblut** [comment]
@dpryan79 `r-fsa` & `r-qgraph` (& `r-epitools`) are just dependencies for the actual package that I want to add: `r-hilldiv`. I've given up on trying to add `r-hilldiv` to bioconda (see https://github.com/conda-forge/staged-recipes/pull/10521 for the details). Mainly, I've realized that it's much work to get R packages on conda, given that it should be very straight-forward for highly standardized packages on CRAN, but it can often take days, weeks, or months to get all of the dependency R packages on conda-forge + bioconda (eg., getting `future.batchtools` on conda-forge took me >2 months with all the dependences). Given that one can just run `install.packages()` in Rstudio instead of trying to use conda (and in my case Jupyter, with I much prefer to Rstudio), the time required for using such R packages in conda isn't worth it for me.

I'm going to close this PR unless you'd like me to keep it open.

**Comment by dpryan79** [comment]
Go ahead and close, thanks.

**Pull request closed without merging**
