### PR TITLE
Add MAnormFast

### PR DESCRIPTION
**Pull request by zfrenchee**
* [x] I have read the guidelines above.
* [x] This PR adds a new recipe.

Add MAnormFast from the Shao Lab. 
Project page: http://139.224.227.24:2013/
Github repo: https://github.com/semal/MAnormFast
My fork: https://github.com/zfrenchee/MAnormFast
On Pypi: https://pypi.python.org/pypi/MAnormFast/0.1.2
Anaconda package: https://anaconda.org/zfrenchee/manormfast

### CODE REVIEW

**Comment by zfrenchee** [comment]
@bgruening done. 
One question: In order to run this package, you need numpy, scipy.misc, and statsmodels, but in the meta.yaml file that was generated, it only lists python as a requirement under `run`. Do I not have to worry about this?

**Comment by bgruening** [comment]
Oh you have to!
This needs to specified. Two things: Your test does not seem to require these packages, so you should enhance your test. Second, the upstream setup.py does not specify these requirements and should be fixed upstream as well.

**Comment by zfrenchee** [comment]
1. `install_requires` or requirements.txt? 
2. `import random` => do I need to have random in `install_requires`?
3. `from scipy.misc import something` => `install_requires` scipy or scipy.misc?

**Comment by bgruening** [comment]
> 1. install_requires or requirements.txt?

both is possible

> 2. import random => do I need to have random in install_requires?

Not needed, it's in stdlib: https://docs.python.org/2.7/library/random.html

> from scipy.misc import something => install_requires scipy or scipy.misc?

scipy

**Comment by zfrenchee** [comment]
New issue now: 
```
~ » conda skeleton pypi MAnormFast 
Error: Could not parse url for MAnormFast: unknown
```

**Comment by bgruening** [comment]
You could for example add a `command` test, similar to `MAnormFast --help`, or more imports where you are sure that the numpy module is also used.

**Comment by zfrenchee** [comment]
@bgruening I merged master back into my branch. I think master was broken perhaps?

**Comment by bgruening** [comment]
Thanks Alex!

**Comment by zfrenchee** [comment]
Thanks Bjoern!

**Comment by zfrenchee** [comment]
Should I delete my copy? @bgruening

```
~/Documents/manormfast(branch:master*) »     anaconda search -t conda manormfast                                                                                                                                                                                       Alex@192
Using Anaconda API: https://api.anaconda.org
Run 'anaconda show <USER/PACKAGE>' to get more details:
Packages:
     Name                      |  Version | Package Types   | Platforms
     ------------------------- |   ------ | --------------- | ---------------
     bioconda/manormfast       |    0.1.2 | conda           | linux-64
     zfrenchee/manormfast      |    0.1.2 | conda           | osx-64
Found 2 packages
```

**Comment by zfrenchee** [comment]
I deleted mine, but I'd like to change the description on https://anaconda.org/bioconda/manormfast. Can I have admin priviledges, or send you the markdown? @bgruening

**Comment by bgruening** [comment]
Send me the markdown if you dare!

**Comment by zfrenchee** [comment]
```
## Command

**Input:**
There are five input arguments needed, 2 peaks files and 2 reads files, and ouptut folder name:

    python MAnorm.py --p1 peak1 --r1 read1 --p2 peak2 --r2 read1 -o ouput_folder_name

**Note:** peak file support bed format and macs output xls format. The first three columns
should be ‘chr start end’ , if there are summit column, should put it in fourth cloumn.

**Other Options:**
> **Note:** Using --help for seeing details.

Good luck.

> if you has any question, you could contact us by email: gzhsss2@gmail.com

semal
```

**Pull request merged**
