### PR TITLE
sartools1.6.3

### PR DESCRIPTION
**Pull request by hvaret**
* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [X] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [X] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by marcelotrevisani** [comment]
Why the build number is commented ?

**Comment by hvaret** [comment]
Hi,
I do not know why it is commented. Today I just changed the version of SARTools and the sha256 field. Should I modify the build section?
Thanks for you help.,
Hugo

**Comment by marcelotrevisani** [comment]
I think would be better if you undo the comment on this line regarding the build number.

**Comment by mbargull** [comment]
> I think would be better if you undo the comment on this line regarding the build number.

Indeed :smile: , xref: https://gitter.im/bioconda/Lobby?at=5b11330293dc78791ca1de41

**Comment by mbargull** [comment]
Thanks @hvaret!

**Pull request merged**
