### PR TITLE
Bump cutadapt to 1.14

### PR DESCRIPTION
**Pull request by marcelm**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by marcelm** [comment]
@bioconda/core I’m getting `$MACOSX_DEPLOYMENT_TARGET mismatch: now "10.7" but "10.9" during configure` for the macOS builds on this version bump. #4592 seems related. Is this going to be fixed soon? I’m a bit reluctant to just set the variable to 10.9 in the build script as some other recipes seem to do. I’d prefer if this were fixed for all recipes.

**Comment by rvalieris** [comment]
yes its the same issue but we (bioconda) haven't discussed it yet.

the gist of it is that the defaults channel and the conda-build tools use 10.7 by default, but conda-forge have decided (https://github.com/conda-forge/toolchain-feedstock/issues/7, https://github.com/conda-forge/toolchain-feedstock/pull/9) to use 10.9.

since we now give priority to the conda-forge channel over the defaults we should also be using 10.9 I think.

@bioconda/core, @bioconda/osx comments please.

**Comment by bgruening** [comment]
@rvalieris I don't think we have much choice, aren't we.
Could you please outline how we should do the migration? Should we simply export `MACOSX_VERSION_MIN="10.9"` during our build on travis or should we also depend on toolchain?

**Comment by rvalieris** [comment]
the variable `MACOSX_DEPLOYMENT_TARGET` should be enough, but maybe we also need to change something it the travis config, from what I understood they made the change because of travis.

**Comment by rvalieris** [comment]
macosx env target has been fixed here https://github.com/bioconda/bioconda-recipes/pull/5039.

**Comment by marcelm** [comment]
Perfect, thanks!

**Pull request merged**
