### PR TITLE
Update drop to 1.0.0

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`drop`](https://bioconda.github.io/recipes/drop/README.html): **0.9.2** &rarr; **1.0.0**

[install with bioconda](http://bioconda.github.io/recipes/drop/README.html) [Conda](https://anaconda.org/bioconda/drop/files)

Info | Link
-----|-----
Recipe | [`recipes/drop`](https://github.com//bioconda/bioconda-recipes/tree/bump/drop/recipes/drop) (click to view/edit other files)
Releases |[https://github.com/gagneurlab/drop/tags](https://github.com/gagneurlab/drop/tags)
Recipe Maintainer(s) | @c-mertes, @mumichae
Author | `@gagneurlab`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by c-mertes** [comment]
@BiocondaBot please add label

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Comment by dpryan79** [comment]
@bioconda-bot please fetch artifacts

**Comment by dpryan79** [comment]
Ah, I somehow uploaded this without merging it. I'll merge it now.

**Comment by c-mertes** [comment]
@dpryan79 thanks for fixing this!

**Pull request merged**
