### PR TITLE
Update rpbp to 3.0.4

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`rpbp`](https://bioconda.github.io/recipes/rpbp/README.html): **3.0.2** &rarr; **3.0.4**

[install with bioconda](http://bioconda.github.io/recipes/rpbp/README.html) [Conda](https://anaconda.org/bioconda/rpbp/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/rpbp`](https://github.com//bioconda/bioconda-recipes/tree/bump/rpbp/recipes/rpbp) (click to view/edit other files)
Summary | Ribosome profiling with Bayesian predictions (Rp-Bp)
Home | [https://github.com/dieterich-lab/rp-bp](https://github.com/dieterich-lab/rp-bp)
Releases |[https://github.com/dieterich-lab/rp-bp/tags](https://github.com/dieterich-lab/rp-bp/tags)
Author | `@dieterich-lab`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by eboileau** [comment]
Thanks @mencian 

Pipeline is running out of space (but not every time)? All checks pass up to a certain point, where 
we hit `00:05:48 BIOCONDA INFO (ERR) [Mar 15 00:05:48] SERR [Errno 28] No space left on device`.
Have you seen this before? What can we do?

**Comment by eboileau** [comment]
`--ignore-installed` has been replaced by `--no-build-isolation`...

**Comment by mencian** [comment]
@eboileau I am using `grayskull` pypi recipe templates, which have recently updated the recommended `pip install` command to use `--no-build-isolation` instead of `--ignore-installed` as per current package building standards.

**Comment by mencian** [comment]
@eboileau Fortunately, the MacOS build error was temporary. The build now now passes CI tests!

**Comment by eboileau** [comment]
Thanks!

**Pull request merged**
