### PR TITLE
add recipe for phirbo

### PR DESCRIPTION
**Pull request by rpetit3**
This PR adds a recipe for [Phirbo](https://github.com/aziele/phirbo) a tool to predict prokaryotic hosts for phage (meta) genomic sequences

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by rpetit3** [comment]
@BiocondaBot please fetch artifacts

**Comment by rpetit3** [comment]
My testing
```
# create environment
conda create -y -n phirbo-bioconda -c conda-forge -c bioconda -c https://136668-42372094-gh.circle-artifacts.com/0/tmp/artifacts/packages phirbo
conda activate phirbo-bioconda

# Test commands
phirbo --version
Phirbo v1.0

phirbo --help
usage: phirbo [-h] [--p P] [--k K] [--t NUM_THREADS] [--version] virus_dir host_dir output_file

Phirbo (v1.0) predicts hosts from phage (meta)genomic data

positional arguments:
  virus_dir        Input directory w/ ranked lists for viruses
  host_dir         Input directory w/ ranked lists for hosts
  output_file      Output file name

optional arguments:
  -h, --help       show this help message and exit
  --p P            RBO parameter in range (0, 1) determines the degree of top-weightedness of RBO measure. High p implies strong emphasis on top ranked items [default = 0.75]
  --k K            Truncate all ranked lists to the first `k` rankings to calculate RBO. To disable the truncation use --k 0 [default = 30]
  --t NUM_THREADS  Number of threads (CPUs) [default = 72]
  --version        Show tool's version number and exit
  
  
# Download example data
git clone git@github.com:aziele/phirbo.git
cd phirbo

# Run test on example data
phirbo example/virus/ example/host/ phirbo-test.csv

ls -lh phirbo-test*
-rw-r--r-- 1 rpetit users  520 Jan 11 08:21 phirbo-test.csv
-rw-r--r-- 1 rpetit users 324K Jan 11 08:21 phirbo-test.csv.matrix.csv

head phirbo-test.csv
phage,host,score
NC_000866,NC_010473,0.6309193558985526
NC_000866,NC_012759,0.6309193558985526
NC_019548,NC_017574,0.6851869982277052
NC_020883,NC_017195,0.7728150206342536
NC_022758,NC_017343,0.6951936946453905
NC_023500,NC_017763,0.8145822605789867
NC_023599,NC_008600,0.867561158015346
NC_023599,NC_017200,0.867561158015346
NC_024137,NC_012472,0.908730280580957

head phirbo-test.csv.matrix.csv
,NC_000866,NC_019548,NC_020883,NC_022758,NC_023500,NC_023599,NC_024137,NC_024330,NC_024388,NC_024392
NC_000117,0.0,1.992547728535729e-06,0.0002850725182770918,3.15721431124631e-05,0.00016991189416467857,1.6617483571044197e-05,0.0005488606976819275,4.400081579083277e-05,0.0003193982785375784,0.00017670388965103115
NC_000853,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.977420355324719e-06,4.520295574486506e-06
NC_000907,0.0007761689336318042,0.00036485917319445865,0.0,0.0,0.0,9.549893124029871e-06,0.0,0.0004909036655004953,0.0020564355408994118,0.0
NC_000908,0.0,0.0,0.0,7.326444724923681e-06,6.9017232915947715e-06,0.0,0.0,0.0,0.0015576688728221183,8.177375916716235e-05
NC_000911,0.0,1.1195127742122363e-05,0.0,0.0,0.0,0.0,0.0,0.0,2.931430896412654e-05,6.753755437618573e-05
NC_000912,0.0,0.0,6.349585428267191e-06,1.300180729690078e-05,2.8976577917910865e-05,9.306869287150526e-06,8.791255754401247e-06,0.0,0.001611022130955511,7.338089594814276e-05
NC_000913,0.6300959189558194,0.0009352385142353449,0.0,0.0,0.0,0.0,0.0,0.00011565400644602414,0.0,0.0
NC_000915,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0017575921893884876,0.0002400682906246348
NC_000918,0.0,2.0351235347010225e-06,0.0011032213878673755,0.00012571276470094928,0.0011247799535258477,0.0011381663911386563,1.6646306053244362e-05,0.0009807666057555563,0.0,0.0005832250903890089
```

Looks like its working like its supposed to.

**Comment by rpetit3** [comment]
@BiocondaBot please add label

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Comment by rpetit3** [comment]
Thank you @dpryan79 !

**Pull request merged**
