### PR TITLE
Add recipe for Neofox python package

### PR DESCRIPTION
**Pull request by priesgo**
This recipe adds the Neofox package for annotation of neoantigens to bioconda.

### CODE REVIEW

**Comment by priesgo** [comment]
There are two pending checks for 8 days now: bioconda.bioconda-recipes (test_linux test_linux)  and bioconda.bioconda-recipes (test_osx test_osx). These are on `Waiting for status to be reported`, is this something that someone has to do or maybe something went wrong and I need to amend it?

All help is appreciated!

**Comment by priesgo** [comment]
OK, I forced a re-execution of the actions with a blank line commit and it finished this time.

**Comment by priesgo** [comment]
Hi, could someone, please, review this pull request?

**Review by alienzj — APPROVED** [review]

**Comment by alienzj** [comment]
@BiocondaBot please merge

**Comment by alienzj** [comment]
@bgruening Hello, how to do when BiocondaBot can't upload the build artifacts ?

**Comment by alienzj** [comment]
@BiocondaBot please fetch artifacts

**Comment by alienzj** [comment]
@BiocondaBot please update

**Comment by alienzj** [comment]
@BiocondaBot please update

**Comment by alienzj** [comment]
@bioconda/core Need help !

**Comment by priesgo** [comment]
Thanks @alienzj for your effort ! Are there any logs that I can look at in case I spot something familiar?

**Comment by franla23** [comment]
Thanks a lot @alienzj and @priesgo for your efforts to add NeoFox! Is there anything else from our side that we can provide to solve the error reported  by the bot?

**Comment by alienzj** [comment]
@BiocondaBot please merge

**Comment by franla23** [comment]
Thanks again @alienzj ! Is there a way to see the error log received by the bot?

**Comment by priesgo** [comment]
Just updated the branch in case it helps...

**Comment by alienzj** [comment]
@BiocondaBot please fetch artifacts

**Comment by alienzj** [comment]
@BiocondaBot please update

**Pull request merged**
