### PR TITLE
Add skDER to bioconda

### PR DESCRIPTION
**Pull request by raufs**
Introduce initial recipe for skDER, the main github repo can be found here: https://github.com/raufs/skDER/

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by raufs** [comment]
@BiocondaBot please fetch artifacts
--


<br class="Apple-interchange-newline">

**Comment by raufs** [comment]
@BiocondaBot please fetch artifacts

**Comment by raufs** [comment]
@BiocondaBot please fetch artifacts

**Comment by raufs** [comment]
@BiocondaBot please add label

**Comment by raufs** [comment]
@BiocondaBot please fetch artifacts

**Comment by raufs** [comment]
@BiocondaBot please fetch artifacts

**Comment by raufs** [comment]
@BiocondaBot please add label

**Comment by raufs** [comment]
Docker testing seems to work - please approve 

```


        This program will perform dereplication of genomes using skani ANI and AF estimates and a dynamic programming based
        approach. It assesses pairwise ANI estimates and chooses which genomes to keep if they are deemed redundant to each
        other based on assembly N50 (keeping the more contiguous assembly) and connectedness (favoring genomes deemed similar
        to a greater number of alternate genomes).

        Compared to dRep by Olm et al. 2017 it does not use a greedy approach based on primary clustering using MASH and
        is more so designed for selecting distinct genomes for a taxonomic group for comparative genomics rather than for
        metagenomic application. However, it can be used for metagenomic application if users are cautious and filter out
        MAGs which have high levels of contamination, which can be assessed using CheckM for instance, and appropriately
        setting the max alignment fraction difference parameter, for the smaller genome to automatically be disregarded as a
        potential representative genome.

        If you find the program useful please cite:
        - "Fast and robust metagenomic sequence comparison through sparse chaining with skani" by Shaw & Yu
             - https://www.biorxiv.org/content/10.1101/2023.01.18.524587v2
        - "Evolutionary investigations of the biosynthetic diversity in the skin microbiome using lsaBGC" by Salamzade et al. 2023
             - https://www.microbiologyresearch.org/content/journal/mgen/10.1099/mgen.0.000988#tab2
             - This paper introduced a more cursory and less optimized version of the dynamic dereplication process.



options:
  -h, --help            show this help message and exit
  -g GENOMES [GENOMES ...], --genomes GENOMES [GENOMES ...]
                        Genome assembly files in FASTA format (each file should end with either *.fasta, *.fa, or *.fna) [Optional].
  -t TAXA_NAME, --taxa_name TAXA_NAME
                        Genus or species identifier from GTDB (currently R214) for which to download genomes for [Optional].
  -o OUTPUT_DIRECTORY, --output_directory OUTPUT_DIRECTORY
                        Output directory.
  -i PERCENT_IDENTITY_CUTOFF, --percent_identity_cutoff PERCENT_IDENTITY_CUTOFF
                        ANI cutoff for dereplication [Default is 99.0].
  -f ALIGNED_FRACTION_CUTOFF, --aligned_fraction_cutoff ALIGNED_FRACTION_CUTOFF
                        Aligned cutoff threshold for dereplication - only needed by one genome [Default is 90.0].
  -m MAX_AF_DISTANCE_CUTOFF, --max_af_distance_cutoff MAX_AF_DISTANCE_CUTOFF
                        Maximum difference for aligned fraction between a pair to automatically disqualify the genome with a higher AF from being a representative.
  -p SKANI_TRIANGLE_PARAMETERS, --skani_triangle_parameters SKANI_TRIANGLE_PARAMETERS
                        Options for skani triangle. Note ANI and AF cutoffs
                        are specified separately and the -E parameter is always
                        requested. [Default is ""].
  -c CPUS, --cpus CPUS  Number of CPUs to use.
```

**Review by mencian — APPROVED** [review]

**Pull request merged**
