### PR TITLE
Bulk arm builds

### PR DESCRIPTION
**Pull request by aliciaaevans**
Port .github/workflows/bulk.yml to Circle CI for ARM builds.

To Do:

- [x] determine what's needed to commit as bioconda-bot
- [x] test

*Edited by @daler 2023-11-26*. **Note to future readers:**  this PR has become a sort of sandbox for all things ARM. There is no intention that this should ever be merged. Instead, working parts should be cherry-picked or manually ported over to the `arm-builds` branch, https://github.com/bioconda/bioconda-recipes/pull/40550

### CODE REVIEW

**Comment by martin-g** [comment]
@aliciaaevans Is there any way to help you with this PR and further work ?
At https://app.circleci.com/pipelines/github/bioconda/bioconda-recipes/102894/workflows/ef156282-952a-41c8-b0b2-f66e25c8a5a8/jobs/180426 I see that the reason for `mmseqs2`'s failure is a missing dependency (`aria2`) for `linux-aarch64`.
I am not fully clear how the `bulk` build works but I expect that there will be many such problematic dependencies. What would be the best way to help you to resolve them ?

**Comment by aliciaaevans** [comment]
Thanks, @martin-g . In this branch, I am was mostly just testing the process of the bulk build on CircleCI and how it handles errors, not trying to actually build or resolve problems with individual recipes. This branch is pretty cluttered, so I'm probably going to move the CircleCI yaml changes to a new PR and close this one. I'm going to check in with @bioconda/core team to see what the next steps are.

**Comment by aliciaaevans** [comment]
Closing in favor of https://github.com/bioconda/bioconda-recipes/pull/44245

**Comment by aliciaaevans** [comment]
Reopen to test bot update

**Comment by aliciaaevans** [comment]
reopening for additional testing

**Comment by daler** [comment]
Looks like circleci thrashes for 7+ mins on the cache restore, apparently spending most of its time reporting out that `/opt/mambaforge` can't be written to! Then bioconda-utils installed in <1 min afterwards. I'm first trying to see if ensuring directory permissions up front fixes the cache restore. But I'm curious to see if it is actually faster to build the env fresh each time.

**Comment by daler** [comment]
Actually, reading the circleci docs, I don't think there is a mechanism for detecting if there is a cache hit like how it's done in [here in the azure config](https://github.com/bioconda/bioconda-recipes/blob/master/azure-pipeline.yml#L39). Trying to remove the cache completely...

**Comment by daler** [comment]
I also noticed that if there is a lint failure on azure, then circleci will still run.

Looks like it's [possible to trigger circleci from GH Actions](https://circleci.com/blog/trigger-circleci-pipeline-github-action/), but I haven't been able to figure out how to do it from Azure DevOps. And I don't think it's worth it to orchestrate *everything* (azure and circleci) through GH Actions.

In terms of resource conservation, I think it's either:

1. run linting separately on ARM.  The cost is linting time x N recipes built.
2. let ARM run even when linting fails on Azure. The cost is build time x N lint failures

Will next run a test to see what linting time is like. I suspect pretty short, but we'll see.

**Comment by daler** [comment]
OK, once everything is up and running and installed, linting took like 1s. So circleci should include linting.

Next up, I installed bioconda-utils from https://github.com/bioconda/bioconda-utils/pull/939 to verify that the mulled-build live logging is working. Since it's pretty verbose, it would be good to put this behind some sort of config option. E.g., if `[live log]` is in the commit message or something.

**Comment by daler** [comment]
Looks like the ANACONDA_TOKEN is expired? Just added the current one to the circleci settings, let's try again...

**Comment by daler** [comment]
@bgruening, I'm stumped as to why [these lines](https://app.circleci.com/pipelines/github/bioconda/bioconda-recipes/103695/workflows/d3d42324-a7b6-4d5f-a8a6-701b8cfff9fc/jobs/180569?invite=true#step-111-126684_257) are causing `mulled-build push` to fail. This might the last piece to get aarch64 containers uploaded.

Any ideas?

(As a reminder, to get this to run again you probably need to bump the build number in `recipes/test/meta.yaml` and make sure the commit message contains `[ci run]`)

**Comment by bgruening** [comment]
@bgruening the `Exec format error` looks like a mismatch between the architectures. I try to look at this, but you normally see that if you use a ARM container on a intel system.

**Comment by bgruening** [comment]
>   + involucro                                    1.1.3  h652cbe9_0                conda-forge/linux-aarch64        2MB

looks good. I have just updated this version yesterday. Maybe its busted? Do you have an ARM Mac to check the binary?

**Comment by bgruening** [comment]
Ok, I think I have it. The real involucro is `/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/bioconda_utils/involucro` that is also the one that seems to work.

During push CI wants to use `/home/circleci/project/involucro` and this is probably not an ARM version.

**Comment by daler** [comment]
Oh interesting (and wow, thanks for the fast response). So the fix is to explicitly tell mulled-build which involucro to use?

**Comment by bgruening** [comment]
I think so. I'm just confused why it works for build-test and not for push. I couldn't see anything special in the CI YAML.
But yes, we need to use the specific ARM builds from involucro.

**Comment by daler** [comment]
OK, I'll do some digging. That was the clue I needed, thanks

**Comment by daler** [comment]
@bgruening got it working, see https://github.com/bioconda/bioconda-utils/pull/941.

That allowed the container to upload, BUT it was set to private. I figured out I needed to run the [change visibility](https://github.com/bioconda/bioconda-utils/actions/runs/6993069162) GitHub Action workflow over on bioconda-utils to get it public. After that, I was able to successfully run 

```bash
docker run --platform linux/arm64 -it quay.io/biocontainers/test:0.1--h73052cd_7
```

🎉 

Only thing I can think of that would cause it to stay private is that the CircleCI token needs to be updated. I don't have access to biocontainers on quay.io though.

Can you verify that the env vars in the [CircleCI settings for bioconda-recipes](https://app.circleci.com/settings/project/github/bioconda/bioconda-recipes/environment-variables) are up to date?

**Comment by daler** [comment]
@biocondabot please fetch artifacts

**Comment by daler** [comment]
So that fetching failed; looking more closely, the bot will need quite a bit more work to support circleci artifacts. However this is implemented in bioconda-utils with handle-merged-pr, so I'll try using the test recipe in a separate PR to see if everything *but* the bot's artifact fetching works.

**Comment by aliciaaevans** [comment]
Now that https://github.com/bioconda/bioconda-recipes/pull/40550 has been merged, closing this.

**Pull request closed without merging**
