### PR TITLE
Update Beav to version 0.5.1

### PR DESCRIPTION
**Pull request by alexweisberg**
This is a new build for Beav that updates it to version 0.5.1 and adjusts the build script.

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

Note that the <code>@BiocondaBot please merge</code> command is now depreciated. Please just squash and merge instead.

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by alexweisberg** [comment]
@BiocondaBot please fetch artifacts

**Comment by alexweisberg** [comment]
fixing a bug, please do not merge this yet. thank you

**Comment by alexweisberg** [comment]
Ok, this one is tested and good to go!

**Comment by alexweisberg** [comment]
@BiocondaBot please add label

**Comment by kbseah** [comment]
Thanks a lot for the update, @alexweisberg ! Just to clarify: is there a reason why TIGER is still downloaded via the build.sh script? is it because of the files that are excluded in the untar step?

**Comment by alexweisberg** [comment]
Hi Brandon,Yes, the tar release of Tiger includes some Linux binaries and a broken soft link that caused the build to fail if I didn’t exclude them. AlexOn Aug 21, 2023, at 1:00 AM, Brandon Seah ***@***.***> wrote:﻿
Thanks a lot for the update, @alexweisberg ! Just to clarify: is there a reason why TIGER is still downloaded via the build.sh script? is it because of the files that are excluded in the untar step?

**Comment by kbseah** [comment]
I see, that's not ideal but can only be fixed upstream. Could you please leave a comment in the build script to document the problem with the TIGER tarball? Else I think it looks ok to me

**Comment by alexweisberg** [comment]
Hi @kbseah,

Done! I've added in the comments to the build.sh script.

Thanks,
Alex

**Review by kbseah — APPROVED** [review]
thanks for your contribution!

**Review by bgruening — APPROVED** [review]

**Comment by alexweisberg** [comment]
Thanks!

**Pull request merged**
