### PR TITLE
upagrade cesm to 2.1.3

### PR DESCRIPTION
**Pull request by annefou**
Update cesm recipe to build for new available version 2.1.3

----

> Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it.

* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [ ] This PR adds a new recipe.
* [ ] AFAIK, this recipe **is directly relevant to the biological sciences**
      (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [X] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

> Everyone has access to the following BiocondaBot commands, which can be given in a comment:
>
>  * `@BiocondaBot please update` will cause the BiocondaBot to merge the master branch into a PR
>  * `@BiocondaBot please add label` will add the `please review & merge` label.
>  * `@BiocondaBot please fetch artifacts` will post links to packages and docker containers built by the CI system. You can use this to test packages locally before merging.
>
> For members of the Bioconda project, the following command is also available:
>
>  * `@BiocondaBot please merge` will cause packages/containers to be uploaded and a PR merged. Someone must approve a PR first! This has the benefit of not wasting CI build time required by manually merging PRs.
>
> If you have questions, please post them in gitter or ping `@bioconda/core` in a comment (if you are not able to directly ping `@bioconda/core` then the bot will repost your comment and enable pinging).

### CODE REVIEW

**Comment by npavlovikj** [comment]
`sha256` should be 27b7919fd30ce8570bd54666c58a6d7c1cc50fe71493ff406552e5fdaf3aee3c.

**Comment by annefou** [comment]
> `sha256` should be 27b7919fd30ce8570bd54666c58a6d7c1cc50fe71493ff406552e5fdaf3aee3c.

@npavlovikj  Thanks a lot!

**Comment by npavlovikj** [comment]
My bad, the sha256 should be 6adae8b9cc74afdf002582fcb66a53942dcfcac94601fe5d1356d355851eb479. I was looking at version 2.1.2 instead of 2.1.3.

**Comment by annefou** [comment]
Ok. Where do you find it? (Just to know for next time). Many thanks.

**Comment by npavlovikj** [comment]
The best way is to download the tarball and run `sha256sum` on it, e.g.:
```
$ wget https://github.com/ESCOMP/CESM/archive/release-cesm2.1.3.tar.gz
$ sha256sum release-cesm2.1.3.tar.gz
6adae8b9cc74afdf002582fcb66a53942dcfcac94601fe5d1356d355851eb479  release-cesm2.1.3.tar.gz
```

**Comment by npavlovikj** [comment]
@BiocondaBot please fetch artifacts

**Comment by npavlovikj** [comment]
@BIocondaBot please merge

On a side note - this package probably should go to conda-forge once the perl packages are migrated there.

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Pull request merged**
