### PR TITLE
Update dsh-bio to 1.1

### PR DESCRIPTION
**Pull request by heuermh**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by heuermh** [comment]
Is this the actual cause of the test-linux circleci failure?
```
[Feb 11 23:21:26] SERR /usr/local/bin/java: error while loading shared libraries: libz.so.1: cannot open shared object file: No such file or directory
[Feb 11 23:21:26] ERRO Task processing failed: Unexpected exit code [127] of container [e3834ff9a2e3 step-dc2eb4f500], container preserved
```
I'm not sure that would be an issue with this recipe, rather one with the openjdk container.

**Comment by heuermh** [comment]
Ping @bioconda/core for advice

**Comment by dpryan79** [comment]
It just needed zlib as a runtime dependency, I've updated the PR.

**Comment by bgruening** [comment]
If zlib is needed, this means there are some binaries in this package? Should they be compiled instead?

**Comment by dpryan79** [comment]
Probably, it's a jar file.

**Comment by heuermh** [comment]
There are no binaries in this package, it is java-only.  Previous versions of this recipe built fine, perhaps the zlib dependency needs to be added to the java container used in the ci build?

**Comment by heuermh** [comment]
Meanwhile, could this pull request be merged with the additional commit?

**Comment by dpryan79** [comment]
I assume so. @bgruening ?

**Comment by heuermh** [comment]
Based on feedback in another pull request, I've rebased against master and force-pushed.  If that fails, I'll re-include the zlib dependency and rebase and squash.

**Comment by heuermh** [comment]
Rebased and squashed

**Comment by dpryan79** [comment]
LGTM, thanks @heuermh

**Comment by dpryan79** [comment]
@bioconda-bot rebuild

**Comment by heuermh** [comment]
Thank you, @dpryan79

**Pull request merged**
