### PR TITLE
Add bioconductor-fabia.

### PR DESCRIPTION
**Pull request by cbrueffer**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by johanneskoester** [comment]
We  have made changes to our build system (migrated from Travis CI to  Circle CI). If you would like to continue working on this PR, please  reopen this PR and update with latest upstream/master.

**Comment by mbargull** [comment]
Did some closer investigation so we can better understand what happens with R packages that are troublesome when compiled with Clang and output ambiguous messages like
```
configure: error: cannot run C compiled programs.
```
. Turns out, this package's `configure.ac` adds
```bash
LDFLAGS=`"${R_HOME}/bin/R" CMD config LDFLAGS`
```
in which `R CMD config LDFLAGS`'s output includes `-lgfortran`. And since it assigns to `LDFLAGS`, it overwrites any previous flags. That includes `-Wl,-rpath,$PREFIX/lib` and thus the compiled binaries are linked to `libgfortran` but can't find it:
```
dyld: Library not loaded: @rpath/./libgfortran.3.dylib
```
Since those compiler/linker flag assignments are [given in the R documentation](https://cran.r-project.org/doc/manuals/r-devel/R-exts.html#Configure-and-cleanup-1), this might be a common idiom.
There might be another/better way than the fix I added here. Maybe someone who's more familiar with R and https://svn.r-project.org/R/trunk/src/scripts/config would know.
In the last commit I added
```diff
-$R CMD INSTALL --build .
+$R CMD INSTALL --build . || (echo "error code: $?" ; cat config.log ; exit 1)
```
. Maybe, going forward, we should add something like this to R recipes to make debugging faster?

**Comment by cbrueffer** [comment]
Great investigation @mbargull ! I agree, adding some more debug output would make this a lot easier. Please commit if you think this is ready now.

**Comment by cbrueffer** [comment]
I've merged this since the recipe looks good now. Thanks a lot @mbargull !

**Pull request merged**
