### PR TITLE
Update ariba to 2.13.2

### PR DESCRIPTION
**Pull request by epruesse**
Update `ariba`: **2.12.1** &rarr; **2.13.2**

***

[Package Info](https://bioconda.github.io/recipes/ariba/README.html) | [Recipe Folder](https://github.com/bioconda/bioconda-recipes/tree/bump/ariba/recipes/ariba) | [Upstream Home](https://github.com/sanger-pathogens/ariba) | [Upstream Releases](https://pypi.org/pypi/ariba/json)

***

This pull request was automatically generated by [bioconda-utils](https://github.com/bioconda/bioconda-utils).

### CODE REVIEW

**Comment by epruesse** [comment]
``
Unsatisfiable dependencies for platform linux-64: {'xz=5.0', 'tk=8.5', 'sqlite=3.9', 'readline=6.2', "python[version='>=3.7,<3.8.0a0']"}
```

**Comment by epruesse** [comment]
It appears it's `xz 5.0` that can't be satisfied with `python 3.7` because it was compiled with `xz 5.2`.

**Comment by epruesse** [comment]
I don't get where the `xz 5.0` comes from. For the build it actually uses 5.2, so it really should require 5.2. 

Added zlib and xz to host deps, let's see if this fixes whatever is going wrong.

**Comment by thanhleviet** [comment]
It seems work with python <= 3.6 . I made a new PR and it passed the test.

**Pull request closed without merging**
