### PR TITLE
remove all bat files

### PR DESCRIPTION
**Pull request by bgruening**
* [ ] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

We do not support Windows, so let's remove these files and don't confuse new contributors.

### CODE REVIEW

**Comment by bgruening** [comment]
ping @johanneskoester @daler

**Comment by colinbrislawn** [comment]
Do we state that windows is not supported? I we should do that...

(I know that these recipes are built by Travis-CI and Travis-CI only builds on Linux and OSX. However, python and conda are cross-platform so defining our scope is helpful, especially for new users.)

**Comment by bgruening** [comment]
@colinbrislawn Oh good point! Do you mind updating the readme accordingly?

**Comment by johanneskoester** [comment]
Never mind, I'll do that now!

**Comment by johanneskoester** [comment]
See PR #2790.

**Pull request merged**
