### PR TITLE
Netcdf metadata info

### PR DESCRIPTION
**Pull request by Alanamosse**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

Second try

The recipe for netcdf-metadata-info is designed to extract and summarize metadata informations about a netcdf file. This tool is for Galaxy use.
Source code : https://github.com/Alanamosse/Netcdf-Metadata-Info/
Galaxy tool preliminary version : https://github.com/65MO/Galaxy-E/tree/master/tools/read_netcdf

### CODE REVIEW

**Comment by mbargull** [comment]
You'll need to compare `bioconda:netcdf-metadata-info` with `bioconda:master` as the base branch:
https://github.com/bioconda/bioconda-recipes/compare/master...netcdf-metadata-info

**Comment by mbargull** [comment]
That means you have to create another PR, because you need to change the branch from which you want to merge from `Alanamosse:netcdf-metadata-info` to `bioconda:netcdf-metadata-info`

**Comment by mbargull** [comment]
PS: click on this link https://github.com/bioconda/bioconda-recipes/compare/master...netcdf-metadata-info 😉

**Comment by Alanamosse** [comment]
Yes damn me ..

**Pull request closed without merging**
