### PR TITLE
Re-enable Spades OSX build

### PR DESCRIPTION
**Pull request by epruesse**
This got turned off in bulk update. Let's see if it's hard to turn back on...

### CODE REVIEW

**Comment by epruesse** [comment]
Failing with `include/c++/v1/wchar.h:141:77: error: use of undeclared identifier 'wcschr'` ... this is some build system *****

**Comment by epruesse** [comment]
@dpryan79 Do you recognize the error here? The undeclared `wcschr` identifier seems to usually be XCode related, so it's less spades and more something with the build system.

**Comment by dpryan79** [comment]
OSX is weird, I have no clue

**Comment by epruesse** [comment]
> OSX is weird, I have no clue

Sigh. I had all this hope.

@bioconda/osx anyone else on this team have a clue?

**Comment by mencian** [comment]
Closing in favor of #50006, where Spades was built on OSX.

**Pull request closed without merging**
