### PR TITLE
Update ymp to 0.2.1

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`ymp`](https://bioconda.github.io/recipes/ymp/README.html): **0.1.0** &rarr; **0.2.1**

[install with bioconda](http://bioconda.github.io/recipes/ymp/README.html) [Conda](https://anaconda.org/bioconda/ymp/files)

Info | Link
-----|-----
Recipe | [`recipes/ymp`](https://github.com//bioconda/bioconda-recipes/tree/bump/ymp/recipes/ymp) (click to view/edit other files)
Releases |[https://pypi.org/pypi/ymp/json](https://pypi.org/pypi/ymp/json)
Recipe Maintainer(s) | @epruesse

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by epruesse** [comment]
missing `fastentrypoints` package

**Comment by epruesse** [comment]
@BiocondaBot please help

**Comment by epruesse** [comment]
@biocondabot please fetch artifacts

**Comment by epruesse** [comment]
@BiocondaBot please make YMP compatible with Python 3.8

**Comment by rpetit3** [comment]
@bioconda-bot please merge

**Comment by epruesse** [comment]
Hey @rpetit3,

the recipe hadn't been quite ready yet. There was still some debug code left in the `test:` section from me trying to figure out what was going on. It's doesn't affect the package itself, just should have been removed before merging. Your help with taking care of the PRs and reviews here is very much appreciated! Just take a closer look at the recipe and be open and critical about what you find. (Also, perhaps don't rush ahead and merge as soon as a build passes - not all that passes is ready. E.g. I could have just disabled the tests temporarily to get an artifact for local testing). 

That said - Thank you! :-)

**Comment by rpetit3** [comment]
Apologies, understood!

**Pull request merged**
