### PR TITLE
Update bactopia-assembler to 1.0.3

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`bactopia-assembler`](https://bioconda.github.io/recipes/bactopia-assembler/README.html): **1.0.2** &rarr; **1.0.3**

[install with bioconda](http://bioconda.github.io/recipes/bactopia-assembler/README.html) [Conda](https://anaconda.org/bioconda/bactopia-assembler/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/bactopia-assembler`](https://github.com//bioconda/bioconda-recipes/tree/bump/bactopia_assembler/recipes/bactopia-assembler) (click to view/edit other files)
Summary | The assembly process used by Bactopia.
Home | [https://bactopia.github.io/](https://bactopia.github.io/)
Releases |[https://github.com/bactopia/bactopia-assembler/tags](https://github.com/bactopia/bactopia-assembler/tags)
Recipe Maintainer(s) | @rpetit3
Author | `@bactopia`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by mencian** [comment]
@rpetit3 Did you mean keras-_pre_processing?

**Comment by rpetit3** [comment]
was testing, likely going to wait for medaka 1.9.1 to be merged first before coming back to this one

**Comment by rpetit3** [comment]
@BiocondaBot please fetch artifacts

**Comment by rpetit3** [comment]
Used bactopia testing locally, only differences were version logs which are expected. 

Finally good to go!

**Review by rpetit3 — APPROVED** [review]

**Pull request merged**
