### PR TITLE
Update synapseclient to 1.9.3

### PR DESCRIPTION
**Pull request by epruesse**
Update [`synapseclient`](https://bioconda.github.io/recipes/synapseclient/README.html): **1.7.5** &rarr; **1.9.3**

[install with bioconda](http://bioconda.github.io/recipes/synapseclient/README.html) [Conda](https://anaconda.org/bioconda/synapseclient/files)

Info | Link
-----|-----
Recipe | [`recipes/synapseclient`](https://github.com//bioconda/bioconda-recipes/tree/bump/synapseclient/recipes/synapseclient) (click to view/edit other files)
Releases |[https://pypi.org/pypi/synapseclient/json](https://pypi.org/pypi/synapseclient/json)

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/updating.html)).

### CODE REVIEW

**Comment by epruesse** [comment]
@BiocondaBot lint

**Comment by epruesse** [comment]
@biocondabot rebuild

**Comment by epruesse** [comment]
@biocondabot update

**Comment by dpryan79** [comment]
@bioconda-bot merge

**Pull request merged**
