### PR TITLE
Update ganon to 1.5.1

### PR DESCRIPTION
**Pull request by pirovc**
Update ganon to 1.5.1

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by pirovc** [comment]
Local tests run just fine, can't see a reason for this failure. In the beginning of the tests, lots of warning like:

```
The reported errors are:
- Encountered problems while solving:
-   - nothing provides requested multitax >=1.3.1
-   - nothing provides requested seqan3 3.1.0.*
-   - nothing provides requested python 3.6.* *_cpython
-   - nothing provides requested diffutils
-   - nothing provides requested catch2 2.*
-   - nothing provides requested cxxopts >=2.2.0
-   - nothing provides requested genome_updater >=0.6.1
-   - nothing provides requested grep
```
am I missing something?

**Comment by jfy133** [comment]
Could it be because you've hard-pinned some of the versions?

```
    - seqan3 ==3.1.0
    - catch2 ==2.*
```

**Comment by jfy133** [comment]
According to the current errors:

```
17:05:33 BIOCONDA INFO (OUT) ganon build with --organism-group archaea bacteria and update "adding" viral with --output-db-prefix ... ERROR
17:05:33 BIOCONDA INFO (OUT) 
17:05:33 BIOCONDA INFO (OUT) ======================================================================
17:05:33 BIOCONDA INFO (OUT) ERROR: test_og_arc_bac_vir (test_build.TestBuild)
17:05:33 BIOCONDA INFO (OUT) ganon build with --organism-group "archaea" "bacteria" "viral"
17:05:33 BIOCONDA INFO (OUT) ----------------------------------------------------------------------
17:05:33 BIOCONDA INFO (OUT) Traceback (most recent call last):
17:05:33 BIOCONDA INFO (OUT)   File "/opt/conda/conda-bld/ganon_1682701074339/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.8/site-packages/ganon/util.py", line 29, in run
17:05:33 BIOCONDA INFO (OUT)     raise Exception()
17:05:33 BIOCONDA INFO (OUT) Exception
17:05:33 BIOCONDA INFO (OUT) 
17:05:33 BIOCONDA INFO (OUT) During handling of the above exception, another exception occurred:
17:05:33 BIOCONDA INFO (OUT) 
17:05:33 BIOCONDA INFO (OUT) Traceback (most recent call last):
17:05:33 BIOCONDA INFO (OUT)   File "/opt/conda/conda-bld/ganon_1682701074339/work/ganon/tests/ganon/integration/test_build.py", line 50, in test_og_arc_bac_vir
17:05:33 BIOCONDA INFO (OUT)     self.assertTrue(run_ganon(cfg, params["db_prefix"]), "ganon build run failed")
17:05:33 BIOCONDA INFO (OUT)   File "/opt/conda/conda-bld/ganon_1682701074339/work/ganon/tests/ganon/utils.py", line 20, in run_ganon
17:05:33 BIOCONDA INFO (OUT)     return ganon.main(cfg=cfg)
17:05:33 BIOCONDA INFO (OUT)   File "/opt/conda/conda-bld/ganon_1682701074339/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.8/site-packages/ganon/ganon.py", line 32, in main
17:05:33 BIOCONDA INFO (OUT)     ret = build(cfg)
17:05:33 BIOCONDA INFO (OUT)   File "/opt/conda/conda-bld/ganon_1682701074339/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.8/site-packages/ganon/build_update.py", line 67, in build
17:05:33 BIOCONDA INFO (OUT)     run(run_genome_updater_cmd, quiet=cfg.quiet)
17:05:33 BIOCONDA INFO (OUT)   File "/opt/conda/conda-bld/ganon_1682701074339/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.8/site-packages/ganon/util.py", line 35, in run
17:05:33 BIOCONDA INFO (OUT)     sys.exit(errcode)
17:05:33 BIOCONDA INFO (OUT) SystemExit: 1
```

It seems like it's failing on some additional tests that I don't see in `meta.yml`, are you running additional tests in your `build.sh` script? And from my (basic) knowledge of ganon, `ganon build` includes download steps right? Could it be some download interuption or something similar?

**Comment by jfy133** [comment]
Context: https://dev.azure.com/bioconda/bioconda-recipes/_build/results?buildId=32424&view=logs&j=e577f919-6e7b-5a3c-181d-e0e9649815b7&t=c4889595-042b-52f2-8068-66691db79f95&l=1303

**Comment by jfy133** [comment]
@BiocondaBot please fetch artifacts

**Review by jfy133 — APPROVED** [review]

**Comment by jfy133** [comment]
Can confirm container now works for `build-custom` with downloading the NCBI taxonomy related files, now the `curl` dependency is inbuilt!

Note for future that within the container there is repeated warnings of something like `egrep is now deprecated, using grep -E` instead. But this doesn't stop anything from working.

**Pull request merged**
