### PR TITLE
REL: microversion release of biom-format

### PR DESCRIPTION
**Pull request by wasade**
* [X] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [X] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

This PR adds an entry for a new microversion release of BIOM-Format. `build.sh` and `meta.yaml` were copied from the `2.1.5` recipe and updated as necessary.

### CODE REVIEW

**Comment by wasade** [comment]
I'm not sure how to resolve the build issue encountered. One of the dependencies, `click`, is attempting to execute `locale` through a subprocess and failing. The issue I'm seeing appears to be the same as in this [thread](https://github.com/garbas/pypi2nix/issues/110), and it looks like the [resolution](https://github.com/garbas/pypi2nix/issues/110#issuecomment-290660209) is to pass in arguments to docker on run. I'm not sure how to modify what arguments are passed to docker in this build system. Any recommendations?

**Comment by bgruening** [comment]
Hi @wasade! I think we have this package already. Can you please look at: https://github.com/bioconda/bioconda-recipes/tree/master/recipes/biom-format

**Comment by wasade** [comment]
@bgruening, this is for a microversion release pushed out last week. `2.1.6` is not presently represented in bioconda

**Comment by bgruening** [comment]
I see, than please start the build-number with 0.

**Comment by bgruening** [comment]
@wasade can you try removing the `python -c "import biom.cli"` if this works. It really unfortunate that click is using the `locale` binary.

**Comment by wasade** [comment]
Done, I think :)

**Comment by wasade** [comment]
`locale` issue persists. Is there a work around for bioconda? Any idea why this doesn't impact other packages which use click (like biom-format 2.1.5)?

**Comment by bgruening** [comment]
@wasade how urgent is this? The problem is that click now depends on the `locale` binary on python3, which is not in our busybox Docker container. I assume that the old version of biom-format had an old click version without this problem. I'm not sure how to solve this yet. We can deploy the Conda package, but will not have a Docker container in the worst case.

**Comment by bgruening** [comment]
Reading this: http://click.pocoo.org/5/python3/
Makes me think we should maybe drop python3?

**Comment by wasade** [comment]
@bgruening, it's not critical in that biom-format 2.1.6 is available from pypi and the biocore channel. We did not explicitly change a minimum click requirement for this release, so I'm guessing it's just sourcing whatever is the latest. Py3 is a hard requirement for biom-format as many of the packages which depend on it are py3 only.

**Comment by bgruening** [comment]
Hi @wasade!
Look at this one: https://github.com/bioconda/bioconda-recipes/pull/4612
It passed and has click defined? It is something special with biom-format?

**Comment by ewels** [comment]
To weigh in on this - MultiQC is also suffering from the same problem. See the change from @chapmanb [here](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/multiqc/meta.yaml#L13-L16) and the [associated travis failure](https://travis-ci.org/bioconda/bioconda-recipes/jobs/191266605).

**Comment by ewels** [comment]
Also, see one of the files in the PR that you mentioned @bgruening - [`run_test.sh`](https://github.com/bioconda/bioconda-recipes/pull/4612/files#diff-e1e5114a3d9e1895b8a937e348a8361e):

```bash
#!/bin/bash

# Click tests for python3 unicode handling using the `locale`
# executable, which does not seem to be present in busybox.
# The workaround is to bypass the `locale` test by setting the
# LANG env variable directly (from looking at Click's source).
LANG=en_US.UTF-8 fsnviz --help
```

So I guess this is why their tests are not failing..

**Comment by bgruening** [comment]
Ha! Interesting! Also I'm not a fan of this we try to offer the possibility to specify a bigger test container - say CentOS, Ubuntu - to prevent this error. Ideally we should probably fix click.

**Comment by wasade** [comment]
Thanks, @ewels. Do you guys advise adding in the same `skip` that's in place with MultiQC?

**Comment by ewels** [comment]
Well, it's not ideal as it skips the python 3 build, so your package won't be available to Python3 users. But it does at least mean that the build succeeds so that the package is available to _some_ users.. :)

You can see this if you do `conda search multiqc`. Before this error started appearing and the `skip` was added, MultiQC version 0.9 was available in several versions:
```
0.9                      py35_0  bioconda
0.9                      py27_0  bioconda
0.9                      py34_0  bioconda
```

But the new v1.0 is only available for py2.7:
```
1.0                      py27_0  bioconda
```

Note that v0.9 had exactly the same `click` code as v1.0, so something has changed elsewhere between these two releases. Now that v1.0 is released for py2.7 users, I will prepare a second PR to play around without the `skip` to see if I can get it working for everyone.

Phil

**Comment by wasade** [comment]
Ah, that is prohibitive for our users as many consumers are Py3 only. 

From what I can tell, its the build system with bioconda which changed seeing as biom 2.1.5 is in and works (with the same click dependency)?

**Comment by druvus** [comment]
Added in #6400 so I am closing this.

**Comment by wasade** [comment]
Fantastic, thank you!

**Pull request closed without merging**
