### PR TITLE
Add initial Bakta v0.3

### PR DESCRIPTION
**Pull request by oschwengers**
This PR adds Bakta (https://github.com/oschwengers/bakta), a new tool for the rapid & standardized annotation of bacterial genomes & plasmids. Bakta addresses the niche between Prokka on the one side and PGAP on the other side providing rapid local annotations on consumer hardware while providing Dbxref-rich annotations includind sORFs.

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by oschwengers** [comment]
@bioconda-bot update

**Comment by andersgs** [comment]
@oschwengers it looks good. 

could you squash the commits: https://github.com/wprig/wprig/wiki/How-to-squash-commits

it will tidy up the PR, and is considered best practices.

thank you!

**Review by andersgs — COMMENTED** [review]
Is prodigal pinned 2.6.3 for a reason?

**Comment by oschwengers** [comment]
@andersgs thanks for the hint! I just overlooked the prodigal version; it's fixed, now.

Is there a description of these best practices regarding the commit squashing? Due to https://bioconda.github.io/contributor/workflow.html it should be OK and  many PRs seem to keep the commits unsquashed.

Isn't it OK to `squash merge` this PR at the end?

**Review by andersgs — APPROVED** [review]
Thank you @oschwengers

**Comment by andersgs** [comment]
@oschwengers I can do the `squash merge`, that is true. But, ideally you would do that before submitting and add your own information to the final commit. It is generally considered good etiquette (https://gist.github.com/mikepea/863f63d6e37281e329f8 --- I like this description).

That said Bakta looks very good! Thank you. I look forward to trying it out, and seeing it develop.

**Comment by oschwengers** [comment]
@andersgs thanks a lot for the nice description - will consider it for upcoming PRs. 

Bakta is still in a rather early stage and considered beta - so I'm really looking forward to your feedback ;-)
Also, ideas, feature requests and bug reports are highly welcome!

**Pull request merged**
