### PR TITLE
Update busco to 4.0.4

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`busco`](https://bioconda.github.io/recipes/busco/README.html): **4.0.2** &rarr; **4.0.4**

[install with bioconda](http://bioconda.github.io/recipes/busco/README.html) [Conda](https://anaconda.org/bioconda/busco/files)

Info | Link
-----|-----
Recipe | [`recipes/busco`](https://github.com//bioconda/bioconda-recipes/tree/bump/busco/recipes/busco) (click to view/edit other files)
Releases |[https://gitlab.com/ezlab/busco/tags](https://gitlab.com/ezlab/busco/tags)
Recipe Maintainer(s) | @silask, @matsepp, @berkelem

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by marcelm** [comment]
The `build.sh` adds activation and deactivation scripts with a comment that "This shold not be necessary in v4.0.1". Before this gets merged, I suggest that one of the maintainers has a look and determines whether this comment is correct.

**Comment by SilasK** [comment]
this scripts set the `BUSCO_CONFIG_FILE` env variable. Is this still needed @berkelem ?

**Comment by berkelem** [comment]
Yes the BUSCO_CONFIG_FILE env variable is still used. There is a command line alternative --config /path/to/config.ini.




On Feb 11, 2020, at 9:44 PM, Silas Kieser <notifications@github.com<mailto:notifications@github.com>> wrote:


this scripts set the BUSCO_CONFIG_FILE env variable. Is this still needed @berkelem<https://github.com/berkelem> ?

**Comment by mat43672** [comment]
Hi,
I think the comment should be removed indeed.
But @SilasK  can we block this automated release, we have some detail to fix before it goes further?

**Comment by marcelm** [comment]
I recently learned that simply closing an autobump PR isn’t helpful because the bot will simply open a new one the next time it runs. This happened now in #20257 . Not sure what the correct way to deal with this is.

**Comment by npavlovikj** [comment]
Sorry for the noise, I was cleaning the recipe a bit, and updated the license type accordingly. The issues discussed earlier have not been addressed in my updates.

**Comment by dpryan79** [comment]
We never added a way to prevent the bot from making automatic PR to update packages.

@mat43672 I'll add a label on this PR that will hopefully dissuade others from mistakenly merging it before you're happy with the release.

**Comment by berkelem** [comment]
I submitted a new merge request #20487 
Once that is cleared this can be closed.
@SilasK

**Comment by SilasK** [comment]
I compared your PR  #20487 with this one (#20236), 

It seems you have just removed, the comment. 
I suggest to accept this PR (#20236), which contain some cleaning up from dpryan79 .

At the end we have busco 4.0.4.

I wait for your confirmation @berkelem

**Comment by SilasK** [comment]
@BiocondaBot please update

**Comment by berkelem** [comment]
Yes, proceed with #20236 in that case.

**Comment by SilasK** [comment]
@BiocondaBot update

**Comment by SilasK** [comment]
@BiocondaBot please add label

**Comment by SilasK** [comment]
@BiocondaBot please merge

**Comment by SilasK** [comment]
@dpryan79 Could you add @berkelem to the bioconda team? 
So he can accept and modify the automatic PR of the bot for Busco.

**Comment by dpryan79** [comment]
Sorry for the delay @SilasK, I'll add @berkelem now

**Pull request closed without merging**
