### PR TITLE
Update metawrap

### PR DESCRIPTION
**Pull request by ursky**
- Updated distrubution to metawrap v=1.3
- New version comes with numerous bug fixes and database updates

### CODE REVIEW

**Comment by ursky** [comment]
Dear Bioconda team,

It looks like the tests are failing due to the name "metawrap" existing in the conda-forge channel. This was not previously an issue. The other package has nothing to do with this one and is no longer maintained, so switching over to conda-forge is not an option. Is there really no way to make this simple update without re-making a new repository with a new name? This has been a pretty well-used package for the last couple of years, and it would not make sense for me to change the name at this point. 

Please advise.

**Comment by marcelm** [comment]
Hi  @ursky, I’m trying to revive this PR, mainly due to a request by @AriBad in #31168. As I describe over there, the package needs to be renamed. Since you chose the name `metawrap-mg` in your own channel, that’s what I’m using here as well. Let me know if you think another name would be more appropriate.

**Comment by marcelm** [comment]
The `config-metawrap` script is marked as executable and installed into the environment’s `bin/` directory, but apparently it is actually a configuration file meant to be edited by the user if necessary (according to https://github.com/bxlab/metaWRAP/#databases). Conda actually stores checksums for all files it installs and will complain if any of the files it has installed were modified, so this method is probably not the best.

**Comment by AriBad** [comment]
Clémence Frioux
09:00
I tested some steps of metawrap through an installation of metawrap-mg with channel ````https://174818-42372094-gh.circle-artifacts.com/0/tmp/artifacts/packages````  (I used the command line ````conda create -n metawrap_mg_test -c https://174818-42372094-gh.circle-artifacts.com/0/tmp/artifacts/packages -c bioconda -c conda-forge metawrap-mg````). Metawrap works correctly. I tested a step that needs to change some paths in config-metawrap and there is no problem by the modification of this config file.

**Comment by marcelm** [comment]
Ok, then let’s accept it the way it is and get this merged. We can change the name (again) if needed.

**Comment by marcelm** [comment]
@biocondabot please merge

**Comment by marcelm** [comment]
@biocondabot please update

**Comment by telatin** [comment]
> Ok, then let’s accept it the way it is and get this merged. We can change the name (again) if needed.

Thanks @marcelm , the name will be probably fine, I just hope no problems with checksums will arise but we will see :)

**Comment by marcelm** [comment]
@telatin Alright! I’ll let you merge this as I need to do something else now. Please remember to use the "BiocondaBot please merge" command instead of merging directly. The bot will then upload the artifacts that were created during the test and skip CI. Merging by clicking the merge button will re-run CI, which is slower and also uses more CI minutes.

**Comment by telatin** [comment]
@BiocondaBot please merge

**Pull request merged**
