### PR TITLE
Update spatyper 

### PR DESCRIPTION
**Pull request by rpetit3**
I thought I had it figured out in https://github.com/bioconda/bioconda-recipes/pull/30622 but it fails when `--entrypoint` is used due to loss of ENV variables.

This PR adds default DB location to spaTyper script

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by rpetit3** [comment]
# Docker run (with entry point)
```
docker run --rm -u $(id -u):$(id -g) --entrypoint /bin/bash -v ${PWD}:/data quay.io/biocontainers/spatyper:0.3.3--pyhdfd78af_3 -c "spaTyper -f /data/genome.fasta"
Start the identification of repeats in Spa protein:
+ Repeats fasta file provided:  /usr/local/share/spatyper-0.3.3/sparepeats.fasta
+ Repeat types file provided:  /usr/local/share/spatyper-0.3.3/spatypes.txt

-----------------
Results:
Sequence name   Repeats Type
NC_002745.2 Staphylococcus aureus subsp. aureus N315, complete sequence 26-23-17-34-17-20-17-12-17-16   t002
-----------------
```

# Docker run (without entry point)
```
docker run --rm -u $(id -u):$(id -g) -v ${PWD}:/data quay.io/biocontainers/spatyper:0.3.3--pyhdfd78af_3 spaTyper -f /data/genome.fasta
Start the identification of repeats in Spa protein:
+ Repeats fasta file provided:  /usr/local/share/spatyper-0.3.3/sparepeats.fasta
+ Repeat types file provided:  /usr/local/share/spatyper-0.3.3/spatypes.txt

-----------------
Results:
Sequence name   Repeats Type
NC_002745.2 Staphylococcus aureus subsp. aureus N315, complete sequence 26-23-17-34-17-20-17-12-17-16   t002
-----------------
```

# Conda 
```
spaTyper -f genome.fasta
Start the identification of repeats in Spa protein:
+ Repeats fasta file provided:  /home/robert_petit/miniconda3/envs/temp-spatyper/share/spatyper-0.3.3/sparepeats.fasta
+ Repeat types file provided:  /home/robert_petit/miniconda3/envs/temp-spatyper/share/spatyper-0.3.3/spatypes.txt

-----------------
Results:
Sequence name   Repeats Type
NC_002745.2 Staphylococcus aureus subsp. aureus N315, complete sequence 26-23-17-34-17-20-17-12-17-16   t002
-----------------
```

Ok think I got it for real this time!

**Comment by rpetit3** [comment]
@biocondabot please add label

**Review by thanhleviet — APPROVED** [review]

**Comment by thanhleviet** [comment]
@BiocondaBot please merge

**Comment by rpetit3** [comment]
Thank you!

**Pull request merged**
