### PR TITLE
Update bioconductor-go.db post-link.sh

### PR DESCRIPTION
**Pull request by amizeranschi**
Fixes a similar issue as in https://github.com/bioconda/bioconda-recipes/issues/31349

### CODE REVIEW

**Comment by mfansler** [comment]
@amizeranschi thanks for the PR. Please be sure to also bump the build in the `meta.yaml` for updates like this. Otherwise, the CI will run but won't detect anything to do and will even pass with false positive.

**Comment by amizeranschi** [comment]
Alright, thanks for the heads-up. Will keep this in mind for the future.

**Comment by amizeranschi** [comment]
@mfansler please also see https://github.com/bioconda/bioconda-recipes/pull/36555

I created that at the same time as this PR and it has the same issue, with the lack of version bumping in  `meta.yaml`

**Review by mfansler — APPROVED** [review]

**Comment by mfansler** [comment]
@daler is it fine to merge this? or does it complicate the eventual merge of [the `bulk-bioconductor-data` migration](https://github.com/bioconda/bioconda-recipes/tree/bulk-bioconductor-data)?

**Comment by mfansler** [comment]
@bioconda-bot please fetch artifacts

**Pull request closed without merging**
