### PR TITLE
bump samtools build after switch to conda-forge

### PR DESCRIPTION
**Pull request by tomkinsc**
* [x] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

I seem to be having trouble with the OSX build of samtools (`dyld: Symbol not found: _stdscr`) after depending on conda-forge. Triggering Travis to rebuild to see if it is just me...

### CODE REVIEW

**Comment by kyleabeauchamp** [comment]
Any resaon not to do pysam and htslib at the same time?  They all have a lot in common.

**Comment by kyleabeauchamp** [comment]
I guess particularly pysam, which builds a vendored samtools

**Comment by tomkinsc** [comment]
Great point. Pysam and htslib are now also represented in this PR.

**Comment by bgruening** [comment]
Thanks!!

**Pull request merged**
