### PR TITLE
Behst7

### PR DESCRIPTION
**Pull request by davidechicco**
* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [X] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by davidechicco** [comment]
@daler @bgruening How can I update the link on this current 1.4 version on Anaconda.org?
[https://anaconda.org/davidechicco/behst](https://anaconda.org/davidechicco/behst)

**Comment by daler** [comment]
@davidechicco after merging, tests are run on the master branch and when they pass again on the master branch, the package is uploaded. So keep an eye on https://travis-ci.org/bioconda/bioconda-recipes/builds/265604347

**Comment by davidechicco** [comment]
Thanks @daler 
I noticed the tests passed on Travis CI ([ https://travis-ci.org/bioconda/bioconda-recipes/builds/265604347]( https://travis-ci.org/bioconda/bioconda-recipes/builds/265604347)); will the system update the package on Anaconda.org automatically?

Thanks

**Comment by daler** [comment]
@davidechicco packages are uploaded to the bioconda channel automatically: https://anaconda.org/bioconda/behst. The anaconda link you referred to previously is your own conda channel which is not affected by anything in bioconda-recipes.

**Comment by davidechicco** [comment]
Thanks @daler, I confused the links.

**Pull request merged**
