### PR TITLE
Update scnic to 0.6.0

### PR DESCRIPTION
**Pull request by epruesse**
Update `scnic`: **0.5.3** &rarr; **0.6.0**

***

[Package Info](https://bioconda.github.io/recipes/scnic/README.html) | [Recipe Folder](https://github.com/bioconda/bioconda-recipes/tree/master/recipes/scnic) | [Upstream Home](https://github.com/shafferm/SCNIC) | [Upstream Releases](https://github.com/shafferm/SCNIC/tags)  

***

This pull request was automatically generated by [bioconda-utils](https://github.com/bioconda/bioconda-utils).

### CODE REVIEW

**Comment by epruesse** [comment]
ping @shafferm - can you check the dependencies?

**Comment by shafferm** [comment]
@epruesse 

Changes needed are [here](https://github.com/shafferm/bioconda-recipes/blob/73f7ecc1a18f09276995b1cefe55c20477e91288/recipes/scnic/meta.yaml)

**Comment by epruesse** [comment]
ping @shafferm - like this?

I put you as maintainer in the recipe - that ok?

**Comment by shafferm** [comment]
@epruesse 
Perfect as long as tests pass.

**Pull request merged**
