### PR TITLE
Update phylofisher to 1.2.0

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`phylofisher`](https://bioconda.github.io/recipes/phylofisher/README.html): **1.1.2** &rarr; **1.2.0**

[install with bioconda](http://bioconda.github.io/recipes/phylofisher/README.html) [Conda](https://anaconda.org/bioconda/phylofisher/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/phylofisher`](https://github.com//bioconda/bioconda-recipes/tree/bump/phylofisher/recipes/phylofisher) (click to view/edit other files)
Summary | A package for the creation, analysis, and visualization of eukaryotic phylogenomic datasets.
Home | [https://github.com/TheBrownLab/PhyloFisher](https://github.com/TheBrownLab/PhyloFisher)
Releases |[https://github.com/TheBrownLab/PhyloFisher/tags](https://github.com/TheBrownLab/PhyloFisher/tags)
Author | `@TheBrownLab`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by daler** [comment]
@robert-ervin-jones this one looks like an out-of-memory error, which has been popping up recently. Don't have a fix for it yet, but if you or anyone you know has experience debugging Azure pipeline memory that would be helpful.

**Comment by robert-ervin-jones** [comment]
@daler thanks for the quick response. I do not. I can't think of anyone I know that does, but I'll ask around. Thanks again!

**Comment by robert-ervin-jones** [comment]
@daler Should I open another PR to update phylofisher now? Or wait until this Azure memory issue is resolved? Any suggestions on how to proceed are greatly appreciated.

**Comment by daler** [comment]
If the build system can't build it, then opening another PR wouldn't fix it. Unsure why this recipe in particular happens to be using a lot of memory (if in fact that is the case). Looks like there's 8 GB available on the VM which theoretically seems like plenty.

**Pull request closed without merging**
