### PR TITLE
Update trinity to 2.8.5

### PR DESCRIPTION
**Pull request by epruesse**
Update [`trinity`](https://bioconda.github.io/recipes/trinity/README.html): **2.8.4** &rarr; **2.8.5**

[install with bioconda](http://bioconda.github.io/recipes/trinity/README.html) [Conda](https://anaconda.org/bioconda/trinity/files)

Info | Link
-----|-----
Recipe | [`recipes/trinity`](https://github.com//bioconda/bioconda-recipes/tree/bump/trinity/recipes/trinity) (click to view/edit other files)
Releases |[https://github.com/trinityrnaseq/trinityrnaseq/tags](https://github.com/trinityrnaseq/trinityrnaseq/tags)
Author | `@trinityrnaseq`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/updating.html)).

### CODE REVIEW

**Comment by epruesse** [comment]
@biocondabot recheck

**Comment by epruesse** [comment]
@dpryan79 Any chance to get this to build for osx as well?

**Comment by dpryan79** [comment]
Trying that now actually, it's just a matter of getting the openmp stuff working.

**Comment by dpryan79** [comment]
Xref: https://github.com/bioconda/bioconda-recipes/pull/15577

**Comment by dpryan79** [comment]
I also removed the perl and python pinnings in my PR.

**Comment by epruesse** [comment]
Ok. Closing this in favor of #15577 then

**Pull request closed without merging**
