### PR TITLE
bzip2 - added recipe for bzip2 and libbzip2

### PR DESCRIPTION
**Pull request by notestaff**
* [X ] I have read the guidelines above.
* [X] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

Adding this to enable compiling the kmc k-mer counter from source, but of course many other things also have libbzip2 as a dependency.

@bioconda/core

### CODE REVIEW

**Comment by kyleabeauchamp** [comment]
Isn't this already in the default channel?

**Comment by notestaff** [comment]
Couldn't find it in
https://github.com/conda/conda-recipes
Is that the full list of the default channel recipes?

**Comment by kyleabeauchamp** [comment]
I think that list is incomplete.  Look at anaconda.org.

**Comment by tomkinsc** [comment]
I usually check for packages in the default channel via `conda search  <packagename>`. So, `conda search bzip2` shows it in the `defaults` channel (and `conda info` shows more).

**Pull request closed without merging**
