### PR TITLE
Update krakenuniq to 1.0.3

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`krakenuniq`](https://bioconda.github.io/recipes/krakenuniq/README.html): **1.0.2** &rarr; **1.0.3**

[install with bioconda](http://bioconda.github.io/recipes/krakenuniq/README.html) [Conda](https://anaconda.org/bioconda/krakenuniq/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/krakenuniq`](https://github.com//bioconda/bioconda-recipes/tree/bump/krakenuniq/recipes/krakenuniq) (click to view/edit other files)
Summary | Metagenomics classifier with unique k-mer counting for more specific results
Home | [https://github.com/fbreitwieser/krakenuniq](https://github.com/fbreitwieser/krakenuniq)
Releases |[https://github.com/fbreitwieser/krakenuniq/tags](https://github.com/fbreitwieser/krakenuniq/tags)
Author | @fbreitwieser
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by kdm9** [comment]
The name of the license file has [changed to `LICENSE`](https://github.com/fbreitwieser/krakenuniq/commit/5d6393abd72e1271de7fc0b02a96cef2c6279cdf), so needs updating in `meta.yml`. @bioconda/core I don't have commit access yet, so can't make this change. Could I be added as a team member so that I can update these autobump PRs when I spot an issue like this or #38401, or is that not how things work? If not, how should one add fixes to autobump PRs?

**Comment by rpetit3** [comment]
@kdm9 you should have an invite to join the `all` group. This will allow you to make changes to the auto PRs

Thank you very much for you help!

**Review by kdm9 — APPROVED** [review]
LGTM

**Comment by rpetit3** [comment]
@BiocondaBot please merge

**Pull request merged**
