### PR TITLE
Finish boost 1.61 migration

### PR DESCRIPTION
**Pull request by johanneskoester**
* [x] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

Denovogear does not work with boost 1.61. Hence, we pin to 1.60. Detonate ships its own boost, hence we remove the dependency.

### CODE REVIEW

**Comment by johanneskoester** [comment]
@bgruening this should be it. @chapmanb, once this succeeds, we can increase the numpy version.

**Comment by johanneskoester** [comment]
@bioconda/core is it only me, or is travis broken today? I always get the message "There was an error while loading data.".

**Comment by tomkinsc** [comment]
Travis is having issues today: https://www.traviscistatus.com/
"Our ongoing database connection issues are due to emergency maintenance following the recent AWS outage. We are working with our upstream provider to rectify a kernel bug and are currently waiting for a new database failover to be provisioned. We expect this to take some time, and will continue to post updates as we have them. "

**Comment by johanneskoester** [comment]
Thanks, Chris!

**Comment by tomkinsc** [comment]
The Travis API seems to be back up now, and I restarted the build, however the test seems to be failing: https://travis-ci.org/bioconda/bioconda-recipes/jobs/206605299

**Comment by johanneskoester** [comment]
@jerowe can you have a look what's going on with detonate (I think it is your recipe)? Ideally, I'd like it to use conda boost, but I could not convince it to use that. So I accepted that it wants to build its own. However, not it cannot see ncurses although it is specified as a dependency and includes are also defined in the build script.

**Comment by jerowe** [comment]
@johanneskoester , sure. I will open a branch and do some testing locally. I'm off to scoop up my little ones soon, but I will take a look at it today or tomorrow.

**Comment by johanneskoester** [comment]
Awesome, thanks @jerowe!

**Comment by jerowe** [comment]
It doesn't look like transcomb is on the blacklist. Has this been solved already?

**Comment by johanneskoester** [comment]
@jerowe well, we have a boost 1.61 build of transcomb online, so I assume it worked: https://anaconda.org/bioconda/transcomb/files

**Comment by jerowe** [comment]
I saw that, but it doesn't build for me locally, so I was wondering.

**Comment by johanneskoester** [comment]
Ah, ok.

**Pull request closed without merging**
