### PR TITLE
Update tobias to 0.11.0

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`tobias`](https://bioconda.github.io/recipes/tobias/README.html): **0.9.0** &rarr; **0.11.0**

[install with bioconda](http://bioconda.github.io/recipes/tobias/README.html) [Conda](https://anaconda.org/bioconda/tobias/files)

Info | Link
-----|-----
Recipe | [`recipes/tobias`](https://github.com//bioconda/bioconda-recipes/tree/bump/tobias/recipes/tobias) (click to view/edit other files)
Releases |[https://pypi.org/pypi/tobias/json](https://pypi.org/pypi/tobias/json)
Recipe Maintainer(s) | @msbentsen, @jenzopr

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by dpryan79** [comment]
Somehow this is using gobs of memory, it even causes my laptop to swap to death.

**Comment by dpryan79** [comment]
I'm not sure why gimmemotifs can't find xgboost when it's installed.

**Comment by msbentsen** [comment]
This issue was discussed in #20014 - seems to be a problem with xgboost not being known by Python after install (even though it is there). It works from the defaults channel though, but since it is not possible to pin packages to a specific channel in recipes, I have not been able to solve the issue yet...

**Comment by dpryan79** [comment]
Ah, thanks @msbentsen

**Comment by dpryan79** [comment]
You've even reported the issue (https://github.com/conda-forge/xgboost-feedstock/issues/46 ), good on you! I'll have a look at the default channel recipe and compare it to that from conda-forge to see if I can make a PR to fix this.

**Comment by dpryan79** [comment]
This should be fixed by https://github.com/conda-forge/xgboost-feedstock/pull/47

**Comment by msbentsen** [comment]
Ah great, thank you so much @dpryan79!

**Comment by jenzopr** [comment]
@BiocondaBot please merge

**Pull request merged**
