### PR TITLE
Add `fastobo` recipe

### PR DESCRIPTION
**Pull request by althonos**
This PR adds a bioconda recipe for the [`fastobo`](https://pypi.org/project/fastobo) Python package, a library to parse Open Biomedical Ontologies.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by althonos** [comment]
@bioconda/python: Hi! I am trying to compile a Python extension written in Rust but the Rust nightly compiler found on Anaconda is outdated. However, I already provide pre-built wheels on PyPI, is it possible to build the conda package from them instead of the source distribution?

**Comment by althonos** [comment]
Other question to @bioconda/rust : is it possible to use the latest nightly compiler to build a package?

**Comment by althonos** [comment]
Thanks for the heads-up @dpryan79

**Comment by dpryan79** [comment]
Would it help if the rust package were updated to 1.40.0? The issue with nightly versions of rust or other packages is that they tend to randomly break things.

**Comment by althonos** [comment]
@dpryan79 : I mean I'm fine downloading the latest nightly to build against it, the issue now seems to be with `libiconv` in MacOSX. Since the stack is almost stable (`pyo3` uses only one nightly feature) I don't think a lot of things could break between the moment I push a release and the moment it is build for `conda`.

**Comment by dpryan79** [comment]
Ah, gotcha. For the moment I'd suggest just skipping OSX.

**Comment by dpryan79** [comment]
Thanks @althonos!

**Pull request merged**
