### PR TITLE
upgrade checkmate and test new bioconda-utils for r-* packages

### PR DESCRIPTION
**Pull request by bgruening**
- [x] I have read the guidelines above.
- [ ] This PR adds a new recipe.
- [x] This PR updates an existing recipe.
- [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by bgruening** [comment]
ping @johanneskoester 
I also rebuild the image and pushed it with a new conda version.

```
[root@5fa4d3d79c72 bioconda-recipes]# conda --version
conda 4.1.11
root@5fa4d3d79c72 bioconda-recipes]# conda build --version
conda-build 1.21.14+0.g4dfebe9.dirty
```

**Comment by bgruening** [comment]
@johanneskoester any idea here?
Again bad luck with this package, I think the build environment works but this package does not compile :(

**Comment by kyleabeauchamp** [comment]
Saw a similar thing here that suggested adjusting the C99 settings in the makefile perhaps?

https://github.com/vsbuffalo/scythe/issues/7

**Comment by bgruening** [comment]
@kyleabeauchamp any idea how to squeeze this into the R compilation?
Thanks for the pointer!

**Comment by johanneskoester** [comment]
The right way would be to add a patch to the meta.yaml. If this is a common issue, the patch can even be re-used for other R recipes as well.

**Comment by bgruening** [comment]
I even don't know what to patch ;)

**Comment by johanneskoester** [comment]
According to the bug report, all occurrences of -std=gnu99 into -std=c99 in the Makefile. But maybe it is better to just wait for an upstream fix and mark the recipe as skip->true.

**Comment by bgruening** [comment]
There is no classical Makefile, I have checked this. I'm not familiar with R setups, so I will skip this recipe for now.

**Comment by johanneskoester** [comment]
I agree. I also don't think it is up to us to fix this.

**Comment by johanneskoester** [comment]
According to that bug report, this also seems to be a very rare problem that is system specific. Maybe something is wrong with the anaconda gcc package? Should we ping Mike?

**Comment by bgruening** [comment]
I have just increased the build-number, let's see if this works. @johanneskoester in this PR there is a new package that seems to work.
Before we ask Mike do we have an R expert? @daler maybe?

**Comment by bgruening** [comment]
Mh, it seems that we can not rebuild the old package. This will be fun if we need to rebuild all packages, Oo.

**Comment by bgruening** [comment]
Anyone know if the gcc package has changes recently?

**Comment by johanneskoester** [comment]
There is 4.8.5 since about 1 month. Before, there was 4.8.2. Maybe check if 4.8.2 works? It could also be that we used the system gcc before. I just tried locally and it works with conda build 1.21.14. So it is either the conda version or something with the container...

**Comment by bgruening** [comment]
I was about to remove GCC from the container, but don't wanted to change so many things at once. Are you ok with removing it finally?

```
conda-build 1.21.14+0.g4dfebe9.dirty
```
is part of the new container, so this is not the problem.

**Comment by bgruening** [comment]
@johanneskoester here we go! Older GCC version and it works.

**Comment by johanneskoester** [comment]
But weirdly, the new GCC version works nicely on my fedora 24 system. It might be a side-effect with the underlying system libraries in CentOS 5, see [this bug report](http://lists.mcs.anl.gov/pipermail/mpich-discuss/2011-April/009800.html).

**Comment by johanneskoester** [comment]
If we pin gcc to an older version to proceed here, I would say we shouldn't hardcode that into the recipe but rather pin the gcc version globally, see [here](http://conda.pydata.org/docs/faq.html#pinning-packages).

**Comment by bgruening** [comment]
Oh yes, suer if we pin it, we should do it globally. I'm just not sure this is the correct way to fix it. Should we try to other container from continuum?

**Comment by johanneskoester** [comment]
You are right, we should probably try another CentOS based container, ideally Mikes official one. Maybe the bug is introduced by one of our manual devtoolset installations. A clean CentOS5 container would work as well I guess.

**Comment by johanneskoester** [comment]
I just checked with continuumio/conda_builder_linux and it fails with the same error. Hence, it seems to be a CentOS problem.

@msarahan, sorry to disturb you. Please let me know if we should not mention you directly. I know you must be incredibly busy. But maybe you can help here. We get the following compilation error when using the most recent gcc 4.8.5 package to build r-checkmate. 
It seems to be a problem occurring in combination with CentOS 5. At least on Fedora 24 it works. Also, with the older gcc 4.8.2 package it works. Are you aware of this problem?

```
gcc -std=gnu99 -I/home/dev/miniconda3/envs/_build_placehold_placehold_placehold_placehold_placeho/lib/R/include -DNDEBUG  -I/home/dev/miniconda3/envs/_build_placehold_placehold_placehold_placehold_placeho/include    -fpic  -I/home/dev/miniconda3/envs/_build_placehold_placehold_placehold_placehold_placeho/include  -c all_missing.c -o all_missing.o
gcc -std=gnu99 -I/home/dev/miniconda3/envs/_build_placehold_placehold_placehold_placehold_placeho/lib/R/include -DNDEBUG  -I/home/dev/miniconda3/envs/_build_placehold_placehold_placehold_placehold_placeho/include    -fpic  -I/home/dev/miniconda3/envs/_build_placehold_placehold_placehold_placehold_placeho/include  -c all_nchar.c -o all_nchar.o
gcc -std=gnu99 -I/home/dev/miniconda3/envs/_build_placehold_placehold_placehold_placehold_placeho/lib/R/include -DNDEBUG  -I/home/dev/miniconda3/envs/_build_placehold_placehold_placehold_placehold_placeho/include    -fpic  -I/home/dev/miniconda3/envs/_build_placehold_placehold_placehold_placehold_placeho/include  -c any_infinite.c -o any_infinite.o
gcc -std=gnu99 -I/home/dev/miniconda3/envs/_build_placehold_placehold_placehold_placehold_placeho/lib/R/include -DNDEBUG  -I/home/dev/miniconda3/envs/_build_placehold_placehold_placehold_placehold_placeho/include    -fpic  -I/home/dev/miniconda3/envs/_build_placehold_placehold_placehold_placehold_placeho/include  -c any_missing.c -o any_missing.o
gcc -std=gnu99 -I/home/dev/miniconda3/envs/_build_placehold_placehold_placehold_placehold_placeho/lib/R/include -DNDEBUG  -I/home/dev/miniconda3/envs/_build_placehold_placehold_placehold_placehold_placeho/include    -fpic  -I/home/dev/miniconda3/envs/_build_placehold_placehold_placehold_placehold_placeho/include  -c any_nan.c -o any_nan.o
gcc -std=gnu99 -I/home/dev/miniconda3/envs/_build_placehold_placehold_placehold_placehold_placeho/lib/R/include -DNDEBUG  -I/home/dev/miniconda3/envs/_build_placehold_placehold_placehold_placehold_placeho/include    -fpic  -I/home/dev/miniconda3/envs/_build_placehold_placehold_placehold_placehold_placeho/include  -c checks.c -o checks.o
gcc -std=gnu99 -I/home/dev/miniconda3/envs/_build_placehold_placehold_placehold_placehold_placeho/lib/R/include -DNDEBUG  -I/home/dev/miniconda3/envs/_build_placehold_placehold_placehold_placehold_placeho/include    -fpic  -I/home/dev/miniconda3/envs/_build_placehold_placehold_placehold_placehold_placeho/include  -c cmessages.c -o cmessages.o
gcc -std=gnu99 -I/home/dev/miniconda3/envs/_build_placehold_placehold_placehold_placehold_placeho/lib/R/include -DNDEBUG  -I/home/dev/miniconda3/envs/_build_placehold_placehold_placehold_placehold_placeho/include    -fpic  -I/home/dev/miniconda3/envs/_build_placehold_placehold_placehold_placehold_placeho/include  -c helper.c -o helper.o
gcc -std=gnu99 -I/home/dev/miniconda3/envs/_build_placehold_placehold_placehold_placehold_placeho/lib/R/include -DNDEBUG  -I/home/dev/miniconda3/envs/_build_placehold_placehold_placehold_placehold_placeho/include    -fpic  -I/home/dev/miniconda3/envs/_build_placehold_placehold_placehold_placehold_placeho/include  -c is_integerish.c -o is_integerish.o
gcc -std=gnu99 -I/home/dev/miniconda3/envs/_build_placehold_placehold_placehold_placehold_placeho/lib/R/include -DNDEBUG  -I/home/dev/miniconda3/envs/_build_placehold_placehold_placehold_placehold_placeho/include    -fpic  -I/home/dev/miniconda3/envs/_build_placehold_placehold_placehold_placehold_placeho/include  -c qassert.c -o qassert.o
gcc -std=gnu99 -I/home/dev/miniconda3/envs/_build_placehold_placehold_placehold_placehold_placeho/lib/R/include -DNDEBUG  -I/home/dev/miniconda3/envs/_build_placehold_placehold_placehold_placehold_placeho/include    -fpic  -I/home/dev/miniconda3/envs/_build_placehold_placehold_placehold_placehold_placeho/include  -c which_first.c -o which_first.o
gcc -std=gnu99 -shared -L/home/dev/miniconda3/envs/_build_placehold_placehold_placehold_placehold_placeho/lib/R/lib -L/home/dev/miniconda3/envs/_build_placehold_placehold_placehold_placehold_placeho/lib -lgfortran -o checkmate.so all_missing.o all_nchar.o any_infinite.o any_missing.o any_nan.o checks.o cmessages.o helper.o is_integerish.o qassert.o which_first.o -L/home/dev/miniconda3/envs/_build_placehold_placehold_placehold_placehold_placeho/lib/R/lib -lR
all_nchar.o: In function `gnu_dev_major':
all_nchar.c:(.text+0x0): multiple definition of `gnu_dev_major'
all_missing.o:all_missing.c:(.text+0x0): first defined here
all_nchar.o: In function `gnu_dev_minor':
all_nchar.c:(.text+0x28): multiple definition of `gnu_dev_minor'
all_missing.o:all_missing.c:(.text+0x28): first defined here
all_nchar.o: In function `gnu_dev_makedev':
all_nchar.c:(.text+0x45): multiple definition of `gnu_dev_makedev'
all_missing.o:all_missing.c:(.text+0x45): first defined here
any_infinite.o: In function `gnu_dev_major':
any_infinite.c:(.text+0x0): multiple definition of `gnu_dev_major'
all_missing.o:all_missing.c:(.text+0x0): first defined here
any_infinite.o: In function `gnu_dev_minor':
any_infinite.c:(.text+0x28): multiple definition of `gnu_dev_minor'
all_missing.o:all_missing.c:(.text+0x28): first defined here
any_infinite.o: In function `gnu_dev_makedev':
any_infinite.c:(.text+0x45): multiple definition of `gnu_dev_makedev'
all_missing.o:all_missing.c:(.text+0x45): first defined here
any_missing.o: In function `gnu_dev_major':
any_missing.c:(.text+0x0): multiple definition of `gnu_dev_major'
all_missing.o:all_missing.c:(.text+0x0): first defined here
any_missing.o: In function `gnu_dev_minor':
any_missing.c:(.text+0x28): multiple definition of `gnu_dev_minor'
all_missing.o:all_missing.c:(.text+0x28): first defined here
any_missing.o: In function `gnu_dev_makedev':
any_missing.c:(.text+0x45): multiple definition of `gnu_dev_makedev'
all_missing.o:all_missing.c:(.text+0x45): first defined here
any_nan.o: In function `gnu_dev_major':
any_nan.c:(.text+0x0): multiple definition of `gnu_dev_major'
all_missing.o:all_missing.c:(.text+0x0): first defined here
any_nan.o: In function `gnu_dev_minor':
any_nan.c:(.text+0x28): multiple definition of `gnu_dev_minor'
all_missing.o:all_missing.c:(.text+0x28): first defined here
any_nan.o: In function `gnu_dev_makedev':
any_nan.c:(.text+0x45): multiple definition of `gnu_dev_makedev'
all_missing.o:all_missing.c:(.text+0x45): first defined here
checks.o: In function `gnu_dev_major':
checks.c:(.text+0x0): multiple definition of `gnu_dev_major'
all_missing.o:all_missing.c:(.text+0x0): first defined here
checks.o: In function `gnu_dev_minor':
checks.c:(.text+0x28): multiple definition of `gnu_dev_minor'
all_missing.o:all_missing.c:(.text+0x28): first defined here
checks.o: In function `gnu_dev_makedev':
checks.c:(.text+0x45): multiple definition of `gnu_dev_makedev'
all_missing.o:all_missing.c:(.text+0x45): first defined here
cmessages.o: In function `gnu_dev_major':
cmessages.c:(.text+0x0): multiple definition of `gnu_dev_major'
all_missing.o:all_missing.c:(.text+0x0): first defined here
cmessages.o: In function `gnu_dev_minor':
cmessages.c:(.text+0x28): multiple definition of `gnu_dev_minor'
all_missing.o:all_missing.c:(.text+0x28): first defined here
cmessages.o: In function `gnu_dev_makedev':
cmessages.c:(.text+0x45): multiple definition of `gnu_dev_makedev'
all_missing.o:all_missing.c:(.text+0x45): first defined here
helper.o: In function `gnu_dev_major':
helper.c:(.text+0x0): multiple definition of `gnu_dev_major'
all_missing.o:all_missing.c:(.text+0x0): first defined here
helper.o: In function `gnu_dev_minor':
helper.c:(.text+0x28): multiple definition of `gnu_dev_minor'
all_missing.o:all_missing.c:(.text+0x28): first defined here
helper.o: In function `gnu_dev_makedev':
helper.c:(.text+0x45): multiple definition of `gnu_dev_makedev'
all_missing.o:all_missing.c:(.text+0x45): first defined here
is_integerish.o: In function `gnu_dev_major':
is_integerish.c:(.text+0x0): multiple definition of `gnu_dev_major'
all_missing.o:all_missing.c:(.text+0x0): first defined here
is_integerish.o: In function `gnu_dev_minor':
is_integerish.c:(.text+0x28): multiple definition of `gnu_dev_minor'
all_missing.o:all_missing.c:(.text+0x28): first defined here
is_integerish.o: In function `gnu_dev_makedev':
is_integerish.c:(.text+0x45): multiple definition of `gnu_dev_makedev'
all_missing.o:all_missing.c:(.text+0x45): first defined here
qassert.o: In function `gnu_dev_major':
qassert.c:(.text+0x0): multiple definition of `gnu_dev_major'
all_missing.o:all_missing.c:(.text+0x0): first defined here
qassert.o: In function `gnu_dev_minor':
qassert.c:(.text+0x28): multiple definition of `gnu_dev_minor'
all_missing.o:all_missing.c:(.text+0x28): first defined here
qassert.o: In function `gnu_dev_makedev':
qassert.c:(.text+0x45): multiple definition of `gnu_dev_makedev'
all_missing.o:all_missing.c:(.text+0x45): first defined here
which_first.o: In function `gnu_dev_major':
which_first.c:(.text+0x0): multiple definition of `gnu_dev_major'
all_missing.o:all_missing.c:(.text+0x0): first defined here
which_first.o: In function `gnu_dev_minor':
which_first.c:(.text+0x28): multiple definition of `gnu_dev_minor'
all_missing.o:all_missing.c:(.text+0x28): first defined here
which_first.o: In function `gnu_dev_makedev':
which_first.c:(.text+0x45): multiple definition of `gnu_dev_makedev'
all_missing.o:all_missing.c:(.text+0x45): first defined here
collect2: error: ld returned 1 exit status
make: *** [checkmate.so] Error 1
```

**Comment by msarahan** [comment]
Seems like it may be a problem with glibc and C99: https://lists.gnu.org/archive/html/bug-freedink/2009-09/msg00015.html

Have you tried with CentOS 6?

**Comment by msarahan** [comment]
One other link: https://www.experts-exchange.com/questions/26599699/Compiler-error-multiple-definition-of-gnu-dev-makedev'.html

you may be able to add -std=c99 to your CFLAGS to make it work.

**Comment by johanneskoester** [comment]
Yes, this was our conclusion too, but since continuum is using centOS 5 as well, we wanted to know if you have seen this as well and if there is a plan to fix it, since it was clearly caused by the version change in gcc. If not, we would for now pin to the older gcc version.

**Comment by msarahan** [comment]
I have not run into this at all.  If you are able to narrow it down to a fix in GCC, I'd be happy to apply it.  Otherwise, I'm afraid this is the first issue I've seen that may force an update to CentOS 6.

**Comment by johanneskoester** [comment]
Thanks Mike. So @bgruening can you try adding c99 to CFLAGS in the build script? If that does not work, we should pin globally to the old gcc.

**Comment by bgruening** [comment]
@johanneskoester I removed the pinning in one commit and it fails again, I added some `exports` and it still fails. But yet again I'm not sure this is enough to convince R to use the exports.

**Comment by johanneskoester** [comment]
Ok, let's pin to the old gcc globally.

**Pull request closed without merging**
