### PR TITLE
Add sdust recipe

### PR DESCRIPTION
**Pull request by maxibor**
Add [sdust](https://github.com/lh3/sdust) recipe.

> Sdust is a reimplementation of the symmetric DUST algorithm for finding low-complexity regions in DNA sequences.

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by mfansler** [comment]
Should probably just start a fresh PR at this point. I'd also recommend using a non-master branch for each recipe you submit - keep your master synced to upstream and base new branches on that. Individual PRs usually should not need to merge upstream changes in the interim.

As for getting this building, likely need to use a patch to circumvent the hardcoded gcc settings which seem to be masking the Conda environment's shell variables. I could possibly assist later in the week.

**Comment by mfansler** [comment]
@maxibor I was checking on this today and noted Heng Li's comment that `minimap` and `minimap2` include copies of `sdust`. It might be easiest to recommend installing `mimimap2` for users that want `sdust`. Otherwise, a new `sdust` package will clobber with `minimap*`, which means having to rework all these recipes.

Is it sufficient for you to use `minimap2` to get `sdust`? It's lightweight (< 1MB).

**Comment by maxibor** [comment]
Hey @mfansler ,
I added sdust to the minimap2 recipe a while ago with #23278 , but I thought it would be nice to have it separately.

**Comment by mfansler** [comment]
Ah, I see. Do you know if minimap actually depends on sdust. Another option would be to have the minimap2 recipe generate a separate sdust package. Either way, we'd want to remove the sdust from future minimap2 builds, but still keep it as a dependency, if needed.

**Pull request closed without merging**
