### PR TITLE
Maker a new recipe

### PR DESCRIPTION
**Pull request by mictadlo**
* [x] I have read the guidelines above.
* [x] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by mictadlo** [comment]
@bgruening @chapmanb @martin-mann

I have got [`Bio::Root::Version is not installed`](https://travis-ci.org/bioconda/bioconda-recipes/jobs/200134117#L1158), but I used `perl-bioperl`(https://github.com/bioconda/bioconda-recipes/pull/3758) in my `meta.yaml`.

Is `Bio::Root::Version` part of `perl-bioperl`?

Thank you in advance

Michal

**Comment by chapmanb** [comment]
Michal;
It looks like the latest `perl-bioperl` package (perl-bioperl-1.6.924-6) is empty which likely causes the problem here. perl-bioperl-1.6.924-4 appears okay. I haven't kept up with all the latest perl changes to this package, but a quick fix might be to remove the problematic recent versions. Björn and Martin, what do you think?

**Comment by mictadlo** [comment]
@chapmanb I have got

```
Package missing in current linux-64 channels: 
  - perl-bioperl ==1.6.924-4
```

[here](https://travis-ci.org/bioconda/bioconda-recipes/jobs/201338436#L592).

What did I miss?

**Comment by chapmanb** [comment]
Michal -- the syntax for this is a little strange, I think you want:
```
- perl-bioperl ==1.6.924=4
```
with an `=` instead of the last `-`. Hope this helps pin it to a working version. I'd still like to visit removing the broken packages as well if Björn and Martin have permissions to do so.

**Comment by mictadlo** [comment]
I have got `conda.exceptions.CondaValueError: Value error: Malformed version string 'perl-bioperl-1.6.924=4': invalid character(s).`

**Comment by mictadlo** [comment]
With `perl-bioperl-1.6.924` I got `Bio::Root::Version is not installed`. How could we fix it?

**Comment by chapmanb** [comment]
Michal;
You want to have `- perl-bioperl ==1.6.924=4` in both the build and run requirements. I don't believe the `==perl-bioperl-1.6.924` syntax is valid but conda must skip it until you stuck in the extra `=4`. Hope that fixes it for you.

**Comment by mictadlo** [comment]
I used `- perl-bioperl ==1.6.924=4`, but I got the this [error](https://travis-ci.org/bioconda/bioconda-recipes/jobs/202066750#L552) `Value error: Malformed version string '1.6.924=4': invalid character(s).`

**Comment by chapmanb** [comment]
Michal -- gah sorry about all the retries. I'm not sure what is going on. @bgruening could we remove the empty broken -5 and -6 versions of perl-bioperl to try and sort out this problem? I'm not sure why pinning to sub-versions isn't working but getting rid of those seems to be the best approach at this point.

**Comment by rvalieris** [comment]
I believe this should work for pinning the version:
 ```
requirements:
  build:
   - perl-bioperl 1.6.924 4
```

**Comment by mictadlo** [comment]
Thank you. Perl problems have been solved. Unfortunately, there it failed to build, but I do not why. Any ideas?

**Comment by rvalieris** [comment]
add a line like this:
`perl -i.bak -wpe 's[^#!.+][#!/usr/bin/env perl]' Build`
 right after the `perl Build.PL` line.

but even with that I get this error later:
```
cc: error: unrecognized command line option ‘-fstack-protector-strong’
make: *** [MPI.o] Error 1
```

have you tried building this package locally ? use this command from the bioconda-recipes directory:
`CONDA_PERL="5.22.0" conda build recipes/maker`

that way you can see the errors faster than waiting for travis to build.

**Comment by mictadlo** [comment]
Thank you. @rvalieris I got `OSError: [Errno 28] No space left on device` on travis ci. I am using MacOS and I didn't get the docker container running.

**Comment by nsoranzo** [comment]
@rvalieris I have the same problem with `-fstack-protector-strong` in https://github.com/bioconda/bioconda-recipes/pull/3839#issuecomment-281176326 .

**Comment by mictadlo** [comment]
still not luck. Any ideas?

**Comment by mictadlo** [comment]
@jerowe @druvus  by any chance, do you know how to fix it?

**Comment by jerowe** [comment]
@mictadlo, all things perl are pretty broken right now.

You could try to do something hacky where instead of using the conda gcc you are using the conda-forge gcc, but that is all I can think of. I'm not even sure where conda-forge is keeping its gcc, since I can't just run a `which gcc`.

Its unfortunate because it means perl has very minimal support in all machines that don't have gcc >4.9, which is probably most centos6 machines.

**Comment by mictadlo** [comment]
Why does conda-forge not switch to centos7?

**Comment by mictadlo** [comment]
Anything new on gcc >4.9 front?

**Comment by bgruening** [comment]
Nothing new, but there is hope ;)
An other question regarding maker, the license is not ideal, have you checked if you are allowed to distribute the package?

**Comment by mictadlo** [comment]
I thought it would be fine because of https://raw.githubusercontent.com/Homebrew/homebrew-science/master/maker.rb

**Comment by cbrueffer** [comment]
maker 2.31.9 was added in f2a7aef3c74bbd066f945aaeb81a75db1c608368, I think this PR can be closed?

**Pull request closed without merging**
