### PR TITLE
Add mvp

### PR DESCRIPTION
**Pull request by 0xaf1f**
* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [X] This PR adds a new recipe.
* [X] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

@bioconda/core, this is my first recipe.

### CODE REVIEW

**Comment by 0xaf1f** [comment]
Thanks. I was testing locally, but the last change I made after testing and before sending this was

```
- noarch: generic
+ noarch: python
```
and that looks like what broke it (the build succeeds if I change this back). I was just following https://bioconda.github.io/guidelines.html#id3. Should I just go ahead and change it back to generic?

**Comment by 0xaf1f** [comment]
> Should I just go ahead and change it back to generic?

I went ahead and did it--this is just a standalone command line tool and doesn't do anything with Python's module installation directory. Let me know if it's an issue.

**Comment by 0xaf1f** [comment]
I've just removed the `noarch` declaration to be in accordance with today's change to the guidelines, and the circleci build here still passes. @bioconda/core, it should be ready to go as far as I can tell.

**Comment by daler** [comment]
Thanks @0xaf1f!

**Pull request merged**
