### PR TITLE
adding mantis_pfa recipe;

### PR DESCRIPTION
**Pull request by PedroMTQ**
Describe your pull request here

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by PedroMTQ** [comment]
@bioconda/core this package requires cython but I'm not sure how to add the compilers to the recipe.
Could someone help me?

**Comment by PedroMTQ** [comment]
@BiocondaBot Can someone please review?

**Comment by PedroMTQ** [comment]
@BiocondaBot please add label

**Comment by dpryan79** [comment]
This needs cython to run rather than for installation?

**Comment by PedroMTQ** [comment]
> This needs cython to run rather than for installation?

Yes,  cython only runs when the program runs. but is not required for install.

**Comment by PedroMTQ** [comment]
@dpryan79 
Did you remove skip windows?
This program can't run on windows since it requires packages not available on windows

**Comment by dpryan79** [comment]
There are no windows builds for any bioconda packages.

**Comment by PedroMTQ** [comment]
@dpryan79 
Ah ok.
It seems all checks have passed again. Will the package now be added to bioconda?
Let me know if you need anything else from my side

Regards,
Pedro

**Review by dpryan79 — APPROVED** [review]

**Comment by PedroMTQ** [comment]
When will this be available for install?

**Pull request merged**
