### PR TITLE
Update r-immunedeconv to 2.1.1

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`r-immunedeconv`](https://bioconda.github.io/recipes/r-immunedeconv/README.html): **2.1.0** &rarr; **2.1.1**

[install with bioconda](http://bioconda.github.io/recipes/r-immunedeconv/README.html) [Conda](https://anaconda.org/bioconda/r-immunedeconv/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/r-immunedeconv`](https://github.com//bioconda/bioconda-recipes/tree/bump/r_immunedeconv/recipes/r-immunedeconv) (click to view/edit other files)
Summary | collection of methods for immune cell deconvolution of bulk RNA-seq samples.
Home | [https://github.com/omnideconv/immunedeconv](https://github.com/omnideconv/immunedeconv)
Releases |[https://github.com/omnideconv/immunedeconv/tags](https://github.com/omnideconv/immunedeconv/tags)
Recipe Maintainer(s) | @LorenzoMerotto
Author | `@omnideconv`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by grst** [comment]
@LorenzoMerotto, can you please add the new dependencies in this PR? 

It also includes the necessary updated of the version number, sha hash and build number.

**Comment by LorenzoMerotto** [comment]
@grst I added them and tagged you in the PR from my fork

**Comment by grst** [comment]
ah, sorry now I get it. 
I thought yours was a separate PR against the master branch. 

In theory, you should be able to directly push to this branch? If not you can ask on bioconda gitter to be added to the bioconda org.

**Comment by LorenzoMerotto** [comment]
I don't know if I am allowed to push directly here since on the bioconda documentation they advise to work on personal forks instead. But I'll check that out

**Comment by LorenzoMerotto** [comment]
@grst It's all good here

**Comment by grst** [comment]
@BiocondaBot, please merge

**Pull request merged**
