### PR TITLE
Add tgsgapcloser recipes

### PR DESCRIPTION
**Pull request by cchd0001**
Describe your pull request here

Add tgsgapcloser ;

tgsgapcloser is a gap-closing software tool that uses error-prone long reads generated by third-generation-sequence techniques (Pacbio, Oxford Nanopore, etc.) or preassembled contigs to fill N-gap in the genome assembly.

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by cchd0001** [comment]
@BiocondaBot please add label

**Comment by dpryan79** [comment]
@bioconda-bot please fetch artifacts

**Comment by dpryan79** [comment]
I think we can simplify the conda_build_config.yaml a bit to ease long-term maintenance. If my changes break it we can revert and merge it as it was.

**Comment by dpryan79** [comment]
Does this have to ship its own copy of minimap2?

**Comment by cchd0001** [comment]
> Does this have to ship its own copy of minimap2?

The reason to  ship a copy of minimap2 is that I not only use minimap2 as a tool but also use the API of libminimap2 from c++ code . And the APIs I used  not exist in old version of minimap2 . 


Thanks for all changes you have done . I am a noice of bioconda , what should I do next ?

**Comment by cchd0001** [comment]
> Does this have to ship its own copy of minimap2?

I have remove minimap2 from this package and use bioconda default minimap2 ;

Is there any other things to do ？

@BiocondaBot please add label

**Comment by cchd0001** [comment]
@BiocondaBot please fetch artifacts

**Comment by cchd0001** [comment]
@BiocondaBot please update

**Comment by cchd0001** [comment]
@BiocondaBot please update

**Comment by cchd0001** [comment]
@bioconda/core : 

I readlly need help ....
 
I  don't why but the build filed after I commend @BiocondaBot please update . 

The build is succ before the update .

Could anyone please help me solve this ?

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Comment by cchd0001** [comment]
@dpryan79  Thanks a lot !!!

**Pull request merged**
