### PR TITLE
FLightR

### PR DESCRIPTION
**Pull request by tiagoantao**

### CODE REVIEW

**Comment by johanneskoester** [comment]
Looks good, can we merge this?

**Comment by tiagoantao** [comment]
I am currently traveling, I promise I will have a look this week and make
the necessary changes. I am not totally convinced that it is fully
functional

**Comment by tiagoantao** [comment]
This one did not pass: The travis-ci machine rebooted and that was reported as a pass :(

**Comment by bgruening** [comment]
I restarted testing!

**Pull request closed without merging**
