### PR TITLE
Update drop to 1.0.2

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`drop`](https://bioconda.github.io/recipes/drop/README.html): **1.0.1** &rarr; **1.0.2**

[install with bioconda](http://bioconda.github.io/recipes/drop/README.html) [Conda](https://anaconda.org/bioconda/drop/files)

Info | Link
-----|-----
Recipe | [`recipes/drop`](https://github.com//bioconda/bioconda-recipes/tree/bump/drop/recipes/drop) (click to view/edit other files)
Releases |[https://github.com/gagneurlab/drop/tags](https://github.com/gagneurlab/drop/tags)
Recipe Maintainer(s) | @c-mertes, @mumichae
Author | `@gagneurlab`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by mumichae** [comment]
@BiocondaBot please label

**Comment by mumichae** [comment]
@BiocondaBot please add label

**Comment by dpryan79** [comment]
Closed by #25418

**Comment by dpryan79** [comment]
Oh, that PR was into this one rather than the master branch! Crap, sorry about that!

**Comment by dpryan79** [comment]
The 1.0.2 package got uploaded when the bot merged #25418, so I'll make a new PR to replicate that and just merge it into the master branch.

**Pull request closed without merging**
