### PR TITLE
Enable Python 3 build in sompy

### PR DESCRIPTION
**Pull request by apcamargo**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [x] This PR does something else (explain below).

This PR enables Python 3 build in the sompy recipe

### CODE REVIEW

**Comment by npavlovikj** [comment]
@apcamargo , according to the documentation, sompy supports only python2. If you want to add support for python3, you will need to modify the sompy code itself.

**Comment by apcamargo** [comment]
@npavlovikj I talked with the developer and he said the current version is compatible with both py2 and py3

**Comment by apcamargo** [comment]
@bioconda/core I couln't get this package to build in python 3, even tough the author said it would be compatible. At any rate, I cleaned the recipe and removed unnecessary files. Should this be merged? In this case, should the build number be increased?

**Comment by npavlovikj** [comment]
@apcamargo , since you haven't changed anything in the current recipe, and there is already a py27 sompy package available for the current version, you can just go ahead and close this request.

**Pull request closed without merging**
