### PR TITLE
Update quast to version 4.3

### PR DESCRIPTION
**Pull request by lparsons**
* [X] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [X] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by lparsons** [comment]
I don't think I understand the error on this test:
```
ERROR bioconda_utils.build:build(114): STDOUT+STDERR: bash: cannot set terminal process group (-1): Inappropriate ioctl for device
```

Maybe a problem with travis, docker, or bioconda-utils somehow?

**Comment by daler** [comment]
That's expected and is a side effect of how the container is run, see https://bioconda.github.io/troubleshooting.html#reading-bioconda-utils-logs-on-travis-ci for details.

**Comment by lparsons** [comment]
Thanks @daler. @nsoranzo pointed that out as well. Looks like the real issue causing the failure was some problem with a SourceForge mirror.

**Comment by daler** [comment]
Ok. Looks good, and I just added you to the team so you can merge when you're ready.

**Comment by lparsons** [comment]
Thanks @daler. Doesn't look like it will let me merge yet, perhaps there is a delay...

**Comment by daler** [comment]
@lparsons you should have gotten an email from github, you'll need to follow the link in it to be added.

**Pull request merged**
