### PR TITLE
ucsc utility scripts:

### PR DESCRIPTION
**Pull request by karl616**
- updated templating to build for osx as well
- pinned zlib

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [x] This PR does something else (explain below).

### CODE REVIEW

**Comment by karl616** [comment]
This PR updates the ucsc utility scripts with new templates. Two main changes:
- pinned ZLIB
- activated the build process for osx, based on tests for bedgraphtobigwig

@daler I reverted the switch to github after seeing create-ucsc-packages.py. I stumbled on replacing the footer file. I'm also not sure on how to use the bulk branch.

**Comment by bgruening** [comment]
@karl616 can we merge this into bulk. I have already updated the pinning in bulk.

**Comment by karl616** [comment]
@bgruening sure I have no problem with that. I closed the other thread as it was redundant with this.

**Comment by bgruening** [comment]
Yes that would be nice.

**Pull request closed without merging**
