### PR TITLE
vispr 0.4.14

### PR DESCRIPTION
**Pull request by johanneskoester**
* [x] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by johanneskoester** [comment]
@bgruening, please see this error from the container test: https://travis-ci.org/bioconda/bioconda-recipes/jobs/201869330#L1898.
Would you say there is an error with the pandas package from continuum not depending on libgcc?

**Comment by bgruening** [comment]
Oh, sorry I missed this. Yes, somewhere in this stack libgcc is missing. Honestly, I'm not sure it is pandas, I have seen this with matplotlib as well.

**Comment by johanneskoester** [comment]
Any idea who at continuum should be pinged, or where to report the issue?

**Comment by bgruening** [comment]
No idea, the conda-forge people would be my bet.

**Pull request merged**
