### PR TITLE
Update gappa to 0.4.0

### PR DESCRIPTION
**Pull request by epruesse**
Update [`gappa`](https://bioconda.github.io/recipes/gappa/README.html): **0.2.0** &rarr; **0.4.0**

[install with bioconda](http://bioconda.github.io/recipes/gappa/README.html) [Conda](https://anaconda.org/bioconda/gappa/files)

Info | Link
-----|-----
Recipe | [`recipes/gappa`](https://github.com//bioconda/bioconda-recipes/tree/bump/gappa/recipes/gappa) (click to view/edit other files)
Releases |[https://github.com/lczech/gappa/tags](https://github.com/lczech/gappa/tags)
Author | `@lczech`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/updating.html)).

### CODE REVIEW

**Comment by gavinmdouglas** [comment]
@lczech it looks like there are some errors picked up by the bioconda test in the latest version of gappa. Here is the start of the errors, but you can see the full log above.

```
/opt/conda/conda-bld/gappa_1556459532761/work/src/commands/prepare/random_tree.cpp: In function 'void run_random_tree(const RandomTreeOptions&)':

/opt/conda/conda-bld/gappa_1556459532761/work/src/commands/prepare/random_tree.cpp:112:17: error: 'minimal_tree' was not declared in this scope

     auto tree = minimal_tree();

                 ^~~~~~~~~~~~

/opt/conda/conda-bld/gappa_1556459532761/work/src/commands/prepare/random_tree.cpp:112:17: note: suggested alternative: 'uintmax_t'

     auto tree = minimal_tree();

                 ^~~~~~~~~~~~

                 uintmax_t

/opt/conda/conda-bld/gappa_1556459532761/work/src/commands/prepare/random_tree.cpp:132:37: error: expected primary-expression before '>' token

             node.data<CommonNodeData>().name = random_indexed_name( leaf_node_cnt, options.num_leaves );
```

**Comment by epruesse** [comment]
@lczech This does look like a problem with the release. Can you have a look?

**Comment by epruesse** [comment]
```


-- CLI11 not found

-- Downloading CLI11 from https://github.com/CLIUtils/CLI11/archive/bd890e24a1f081d6db1a59a0cc372eccc64e9e52.zip
```

This isn't good. That thing should have been packaged separately. 

Same:

```
-- Downloading genesis from https://github.com/lczech/genesis/archive/79c8be3ab0f7b01f8b51d24e42b5fdec64d48474.zip
-- Downloading sparsepp from https://github.com/greg7mdp/sparsepp/archive/6bfe3b4bdb364993e612d6bb729d680cf4c77649.zip
```

**Comment by epruesse** [comment]
@gavinmdouglas Can you have a look at those three dependencies? They need to be in separate recipes, each with a proper `url`. 

Gappa is under GPLv3, so we **must** provide the ability to build the tool to everyone to whom we give the binaries. That requires those downloaded libraries. Since we don't have them in `url`, we don't generate a backup of the sources. :-(

Technically, we would need to take the existing binaries down. This should have been noticed when the recipe was created...

**Comment by gavinmdouglas** [comment]
@eprusse could we alternatively just give instructions for how to download the source code from a different server (i.e. the gappa github page)? This section of the GPLv3 FAQ seems highly related: https://www.gnu.org/licenses/gpl-faq.en.html#AnonFTPAndSendSources

**Comment by lczech** [comment]
Hi @gavinmdouglas,

thanks for reporting that issue! It was caused because I forgot to update the commit hash of genesis for the CMake script that automatically downloads it if needed. It's now fixed in the new release (https://github.com/lczech/gappa/releases/tag/v0.4.0). Also, I have now added a script that I will use to check this in the future, and added travis support, so that this issue should not occur again.

The dependency issue that @epruesse mentions is also related to the CMake setup: Whenever one of the three depencencies (genesis, CLI11, sparsepp) is not found, I set up CMake to automatically download them as a convenience for the users. Internally however, these dependencies are simply git submodules, so alternatively `git clone --recursive` works in order to get gappa and all dependencies. The CMake based download is just for those users who either do a normal `git clone` or use the GitHub download button instead.

I don't know about the bioconda policy towards such things - this is something you have to figure out. From my side, I'm quite happy that you guys put in effort in order to make gappa available via bioconda. Thanks for that! So, whatever works for you in terms of code distribution, works for me, too.

Let me know if I can further help.
Lucas

**Comment by epruesse** [comment]
- sparsepp is header only (deprecated by author, by the way, unless you're stuck on c++98). That one can just come in via an extral `url` parameter in the meta.yaml. 
- genesis should be a separate package here
- CLI11 is a generic C++ library, so it should go into conda-forge

**Comment by gavinmdouglas** [comment]
Thanks for your help @epruesse - I'll start making recipes for these tools.

For future reference, is the alternative approach I suggested above against bioconda policy or against GPLv3 in general?

**Comment by lczech** [comment]
Okay, sounds good to me. 

If you think creating a conda/bioconda recipe for genesis is needed, go ahead. I'm happy if you guys want to put in the effort! How does it work concerning commits vs releases? As far as I am aware, the bioconda package is updated for releases, right? For gappa, I usually pull certain genesis commits that do not necessarily correspond to a genesis release. Is that a problem?

Is there anything for me to do right now? Let me know if you need further input from my side, for example concerning genesis. Also, thanks again for all the good work!

**Comment by gavinmdouglas** [comment]
Thanks a lot @lczech! Bioconda recipes need to point to releases since that they are thought to be more stable. Do you anticipate any problems if a point to the latest release (or the release nearest to the specified commit)?

Thanks for offering to help - I may ping you as things come up.

**Comment by lczech** [comment]
Do you mean that bioconda will pull a release version of genesis in order to build gappa? That will probably not work, at least not the way I currently develop these tools. Whenever some function is needed in gappa that I think should be in genesis, I quickly iterate between the two: write and commit the new function to genesis, pull the commit in gappa, use it there. If I now create a release of genesis every time that happens, we'll end up with a lot of releases. Which would defy the whole idea of stability...

Is there any way you could have the bioconda gappa package pull certain commits of genesis, but still comply with your requirements of code distribution etc? Maybe some mirror of gappa that pulls genesis as a whole instead of a git submodule?

**Comment by gavinmdouglas** [comment]
Yes that's right @lczech. I'm not sure if your suggestion is allowed by bioconda or not - could you clarify @epruesse?

**Comment by lczech** [comment]
Addendum: As a side note: Why exactly do you need genesis and the other dependencies to be (bio)conda recipies? As @epruesse pointed out, GPL requires to make the source available. But I'm not aware of any requirement for you to keep backups of these sources. If you ask me, simply add links to the respective repositories of the dependencies ;-)

**Comment by gavinmdouglas** [comment]
That's what I thought too after reading the GPLv3 FAQ @lczech. Would you mind clarifying @epruesse ?

**Comment by epruesse** [comment]
https://www.gnu.org/licenses/gpl-faq.html#AnonFTPAndSendSources

> The sources you provide must correspond exactly to the binaries. In particular, you must make sure they are for the same version of the program—not an older version and not a newer version.

**Comment by lczech** [comment]
Yes, simply link to the GitHub release, for example https://github.com/lczech/gappa/releases/tag/v0.3.0 in our case here. Should do the job.

**Comment by epruesse** [comment]
More re GPL:

So, the others in /core feel less strictly about this than me. I tend to go by the letter. IMO there are good reasons as to why the GPL was written that way. If you don't want those things, there are less restrictive licenses.

GPL was created to allow enforcing that a software work remain "free". Free in the GPL sense means that you are free to improve on it, fix it, rather than be stuck with the frustration of a broken piece of proprietary software. To enforce that this freedom remain available in perpetuity, the GPL mandates that everyone given a binary copy, must also have access to all sources and build systems required to build it. So that you can fix and improve.

So per the license we have to be able to hand out all code used to build a binary package exactly as of that version. Even if you delete you remove a release, force push delete a commit, delete the repo or if Github dies.

**Comment by lczech** [comment]
From [the page that you cited](https://www.gnu.org/licenses/gpl-faq.html#AnonFTPAndSendSources):
> [...] if you'd like, you can alternatively provide instructions for getting the source from another server, or even a version control system.

So, this seems to be meant in a "best effort" way. Make sure that getting the source of the binary is easy. Which it *is* if you provide a link to the respective GitHub release page of the binary. But

> Even if you delete you remove a release, force push delete a commit, delete the repo or if Github dies.

is probably over the top. That is a very strict interpretation of the GPL. If any of this ever happens, it's not your fault, and not the fault of bioconda. So no one will blame you if the source for a particular release is not available any longer ;-)

By the way, does that mean that bioconda keeps source copies of **all** software it packages? Because this is basically what you suggest here, or do I misunderstand? If it doesn't, I don't see a reason why you'd suddenly need to do this for gappa/genesis. Let's keep things simple.

I have chosen GPLv3 for genesis and gappa in order to make it "easy". It's a well known license, and I basically wanted to ensure that the software stays open. I did not intend to make it difficult for other to use it - on the contrary. So I am happy with you just linking to release pages.

If this does not work for you, please suggest a solution.

**Comment by epruesse** [comment]
I will happily advise on library design - building a lib is quite different from building a tool, because you have to worry about ABI stability. The way things are structured now, you have libgenesis 0.21.0 and gappa 0.4.0, with the former being intended as the foundation for more than just gappa.

From a packaging standpoint, the most sensible is to have packages for both. A single recipe can only have one version, and the two pieces of software have distinct versions and genesis is supposed to be used by other tools as well. Since you say that genesis is a moving target at this point, I would advise using `pin_compatible('libgenesis', exact=True)` in the `run` requirements to ensure that `gappa` always installs with exactly the version/build of `libgenesis` that was used during build time.

To build both from one recipe, I would suggest merging the two projects into one. It is not uncommon for libraries to also provide tools. The classic naming scheme might be `genesis-tools` containing the tools and `libgenesis` the `libgenesis.so.X` and `libgenesis-dev` the headers and static libs. If it's all one project with one version, it should be built from one recipe using `outputs` to generate multiple packages. All packages will get that same version number automatically and can be pinned to match exactly with `pin_compatible` as well. See e.g. `arb-bio` for an example (I assume working in Phylogenetics you know ARB. I split the library components and the non-X11 tools into separate packages so that SINA didn't have to require all of X11 to be installed and a hypothetic python-arb package could just pull in the libs to read/write arb files).

**Comment by epruesse** [comment]
If we have both libs, the release cycle would be like this: You have come to another point, you tag a new genesis version and a new gappa version. We then first build the updated genesis lib, then we update the pinnings on gappa and build the new release there. A bit involved, but no other way with to separately versioned things that depend on each other tightly.

If we just "vendor" as you are currently doing, then we would have to make sure libgenesis ends up in a folder where it won't conflict with a second tool also vendoring libgenesis or a full libgenesis package. So install it to `lib/gappa/lib/libgenesis.so` or just use static linking.

**Comment by epruesse** [comment]
> By the way, does that mean that bioconda keeps source copies of **all** software it packages?

Yep. See https://depot.galaxyproject.org/software/gappa/

Just like Debian and other distros distributing binaries, we keep a copy of the source. We are contractually obliged to by the license you gave us. Simple as that.

**Comment by epruesse** [comment]
GPL isn't an easy license. If you want that, use BSD-3-clause. That gives people the right to do (almost) whatever the hell they want. While GPL says "do whatever you want but make sure that the next person is able to do so, too". BSD software can get integrated into commercial closed source things and then that's it, you've given it away. It's a gift that comes without a price. GPL OTOH comes with the price of maintaining openness. You get to mess with it, but you don't get to lock it away. That can be difficult at times, but I personally think it's worth it.

**Comment by bgruening** [comment]
> By the way, does that mean that bioconda keeps source copies of all software it packages?

Yes, at least this is our aim. As long as this bot is running we backing up all artefacts :)

**Comment by epruesse** [comment]
A little off topic, but I remember a master student asking for a 5 1/4" drive at some point, because he was trying to build on another masters thesis and was hoping that it would contain the matlab code. Alas, it only contained a copy of the PDF. Still made it a little easier than retyping the copy of the code from the appendix.

**Comment by lczech** [comment]
Wow, thanks for the effort and clarifications! Let me try to answer all of it:

 - > From a packaging standpoint, the most sensible is to have packages for both.
 
   Agreed. I think this is the solution we should aim for.
 - > To build both from one recipe, I would suggest merging the two projects into one.
 
   I do not fully understand what you mean here. You mean, move the gappa code over to the genesis repository, and put it in some `genesis-tools` subdirectory there? While this would indeed make things easier in terms of packaging and versioning, gappa is not simply meant to be a suite of tools for genesis. It's meant as a standalone tool, and might also pull in more libraries in the future that I would not want    to be part of genesis. So I'll keep it as a separate project/repository.    Sorry for the trouble this to cause!
 - > If we have both libs, the release cycle would be like this: You have come to another point, you tag a new genesis version and a new gappa version.
 
   This would require to make a new genesis release prior to each gappa release, wouldn't it?   Hm, might be a solution, but certainly not the best in my opinion. It would pollute    the release history of genesis, with releases that might only add a single little    function or the like.
 - > If we just "vendor" as you are currently doing, then we would have to make sure libgenesis ends up in a folder where it won't conflict with a second tool also vendoring libgenesis or a full libgenesis package. So install it to lib/gappa/lib/libgenesis.so or just use static linking.
 
   Currently, gappa does use static linking, partly for exaclty that reasons, but also   in order to ensure that one gets a single binary that can be moved around with   no dependencies. So, this is already solved. Also, this idea goes in the direction   I have in mind for a solution. See below for details.
 - > Just like Debian and other distros distributing binaries, we keep a copy of the source.
 
   Oh, okay, I see. Good to know! Also, I didn't know that bioconda and galaxy are entangled.   Something new every day ;-)
 - > GPL isn't an easy license. [...]
 
   Yes, that is also true. Still, for the time being, I'll keep it at GPL, for the reasons   you outlined.
   
So, following up on your suggestions above, how about the following:
Instead of downloading the gappa files for your backup, do a full `git clone --recursive`. This way, the source of all dependencies is also included. This also solves the issue of the other dependencies (sparsepp and CLI11), for which the same problems arise: gappa uses a particular commit of CLI11 instead of a release version, so even if CLI11 makes it into conda, we'd have the same problem there... I could switch to a release, but won't have time for that in the next few weeks.

Would that work for you?

**Comment by lecorguille** [comment]
Hum, linux pass, macox not.
Choice:
 - skip osx (the easy way)
 - test with libiomp-dev
 - skip openmp as suggested by the build report `-DGENESIS_USE_OPENMP=OFF`

**Comment by lczech** [comment]
Thanks @lecorguille for the report. Yes, I've had issues with Clang and OpenMP before... It seems that one needs to install `libiomp-dev` first - blame Clang for not supporting it out of the box. If possible, I'd hence suggest to add this as a dependency for the Mac build, so that it is installed beforehand. If that's not possible, deactivation as you suggested should also work. But that would limit computations to one core, which is not optimal.

**Comment by epruesse** [comment]
If in doubt, disable openmp on OSX. Safest. Or try to get it to work. OMP on OSX doesn't support everything GCC does. E.g. `reduction ... initializer (omp_priv(omp_orig))` works on GCC, but OSX implementation doesn't like it.

**Comment by bgruening** [comment]
Thanks all!

**Comment by lecorguille** [comment]
Indeed, thanks @epruesse and @lczech

**Comment by gavinmdouglas** [comment]
Hey @epruesse, I realized that the source code distribution issue was never resolved. Could you clarify whether @lczech 's suggestion on May 8th above would work? I would be happy to add further details to the conda recipe itself or in a separate markdown file that describes how users can 
run `git clone --recursive` to get the appropriate source code (and how to determine what commit to use based on the gappa version number).

Thanks

**Comment by lczech** [comment]
Thanks, @gavinmdouglas!

So, to re-iterate: In my opinion, a simple `git clone --recursive` on the gappa repo sounds to me like the easiest, licence-fulfilling way of achieving an exact source copy for each release. Is that something that conda/bioconda can do automatically?

**Pull request merged**
