### PR TITLE
add indra

### PR DESCRIPTION
**Pull request by dpryan79**
Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it. Note that if you are not already a member of the bioconda project (meaning that you can't add this label), please ping `@bioconda/core` so that your PR can be reviewed and merged (please note if you'd like to be added to the bioconda project). Please see https://github.com/bioconda/bioconda-recipes/issues/15332 for more details.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by dpryan79** [comment]
Needed for #17469

**Comment by dpryan79** [comment]
Looks like this needs some dependencies still

**Comment by bgyori** [comment]
In terms of PySB, it is available at https://anaconda.org/alubbock/pysb - is that somehow accessible to BioConda or should I add a new recipe for it?

**Comment by dpryan79** [comment]
The recipe for that will need to be added to bioconda (or conda-forge), since otherwise we can't ensure it'll be compatible.

**Pull request closed without merging**
