### PR TITLE
Package WoLF PSORT v0.2

### PR DESCRIPTION
**Pull request by peterjc**
* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [X] This PR adds a new recipe.
* [X] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

The tool is under a custom license, free for non-profit academic use. The recipe fetches the package from an authorised mirror on GitHub as the original domain lapsed.

The tool has several binaries used internally for which the source code is not available, https://github.com/fmaguire/WoLFPSort/issues/3 - currently only for i386 Linux and SPARC, so no Mac OS X support.

### CODE REVIEW

**Comment by peterjc** [comment]
Cross reference https://github.com/fmaguire/WoLFPSort/issues/1 - either I have missed something, or as written WoLF PSORT expects to be run from its own directory, thus a wrapper script is desirable for BioConda.

Sadly, despite ample debugging sanity checks, my wrapper script fails via TravisCI:

```python
#!/usr/bin/env python                                                                                                        
#Wrapper script to call WoLF PSORT from its own directory.                                                                   
import os
import sys
import subprocess
saved_dir = os.path.abspath(os.curdir)

# This wrapper will be in ${PREFIX}/bin/                                                                                     
# and we want to chage to ${PREFIX}/opt/bin/                                                                                 

tool_name = os.path.basename(sys.argv[0])
tool_path = os.path.join(os.path.dirname(os.path.realpath(sys.argv[0])), "../opt/bin")
if not os.path.isdir(tool_path):
    sys.exit("Could not find wrapped tool directory: %s" % tool_path)
if not os.path.isfile(os.path.join(tool_path, tool_name)):
    sys.exit("Could not find wrapped tool at path: %s" % os.path.join(tool_path, tool_name))

os.chdir(tool_path)
if not os.path.isfile(tool_name):
    os.chdir(saved_dir)
    sys.exit("Could not find wrapped tool %s in %s" % (tool_name, tool_path))
if not os.access("./" + tool_name, os.X_OK):
    os.chdir(saved_dir)
    sys.exit("Wrapped tool %s in %s not executable" % (tool_name, tool_path))
args = ["./" + tool_name] + sys.argv[1:]
return_code = subprocess.call(args)
os.chdir(saved_dir)
sys.exit(return_code)
```

The TravisCI failure:

```
runWolfPsortSummary --help
Traceback (most recent call last):
  File "/opt/conda/conda-bld/wolfpsort_1504623671093/_t_env/bin/runWolfPsortSummary", line 26, in <module>
    return_code = subprocess.call(args)
  File "/opt/conda/conda-bld/wolfpsort_1504623671093/_t_env/lib/python2.7/subprocess.py", line 168, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/opt/conda/conda-bld/wolfpsort_1504623671093/_t_env/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/opt/conda/conda-bld/wolfpsort_1504623671093/_t_env/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

This is line 25 and 26, where subprocess fails:

```python
args = ["./" + tool_name] + sys.argv[1:]
return_code = subprocess.call(args)
```

The strange thing is we have changed to the containing folder, and checked the binary exists and can be executed.

**Comment by daler** [comment]
@peterjc I don't know if it would help, but https://github.com/bioconda/bioconda-recipes/blob/07aa987a0c9ebe7975bd66afd783026431b86883/recipes/busco/generate-busco-config.py is a case where a config file is expected to be in the same dir as the executable. And the wrapper we use for java tools is https://github.com/bioconda/bioconda-recipes/blob/4bea0bd16b9416e8c4997bd6c9aca97f0362ff23/recipes/peptide-shaker/peptide-shaker.py which does something similar.

**Comment by peterjc** [comment]
The BUSCO example looks interesting, thanks - but I don't really want to delve into the Perl scripts of WoLF PSORT to work out exactly where things would need adjusting. It might be the best way to fix the tool itself though.

I'm using the same core idea of the Java wrapper script to get the location of the wrapper script, and from that I infer the location of the conda installed files.

This works locally in testing, e.g.

```
$ cd /tmp && rm -rf /tmp/target && rm -rf /tmp/WoLFPSort-905486837d2ff18df16b3449cd03f5a4ed1425e8/ && tar -zxvf wolfpsort-v0.2.tar.gz && cd WoLFPSort-905486837d2ff18df16b3449cd03f5a4ed1425e8 && RECIPE_DIR=~/repositories/bioconda-recipes/recipes/wolfpsort/ PREFIX=/tmp/target bash -x -e ~/repositories/bioconda-recipes/recipes/wolfpsort/build.sh && PATH=/tmp/target/bin/:$PATH runWolfPsortHtmlTables --help
```

**Comment by tseemann** [comment]
is wolf-psort a lost cause @peterjc >

**Comment by peterjc** [comment]
I gave up - a Perl expert might have more joy, but with the limited pre-compiled binaries (for older platforms) this is only of historical interest now 🙁

**Pull request closed without merging**
