### PR TITLE
Update chisel version with correction on setup

### PR DESCRIPTION
**Pull request by simozacca**
Describe your pull request here

CHISEL has been just added to bioconda, unfortunately when executing the standard installation `conda install -c bioconda chisel` (using the latest 2.7 version of Minoconda) the installation failed with conflicts found! My guess is that this is due to an [error](https://github.com/raphael-group/chisel/commit/baa405b323db22c188385aec8cb30d69a41bb4e9) in `setup.py` which I have now fixed and this PR will link to the new corrected version.

Thank you!
----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by simozacca** [comment]
@BiocondaBot please add label

**Comment by dpryan79** [comment]
Make sure to include the conda-forge channel, it's needed for dependency resolution by Bioconda: https://bioconda.github.io/user/install.html#set-up-channels

**Comment by simozacca** [comment]
@dpryan79 Thank you so much! I indeed used the wrong priority order of channels, and using the right order solved the issue! I have also fixed the wrong version of `setup.py` that you mentioned; could we proceed to merging?

Thanks

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Pull request merged**
