### PR TITLE
update: nextclade version bump to v1.4.4

### PR DESCRIPTION
**Pull request by corneliusroemer**
Nextclade CLI 1.4.4 (2021-11-02)

### CODE REVIEW

**Comment by corneliusroemer** [comment]
@pvanheus could you have a look what's wrong here? There's a new version of nextclade and I've tried to get it to update here in bioconda, but it doesn't work.

**Comment by corneliusroemer** [comment]
@BiocondaBot please add label

**Comment by corneliusroemer** [comment]
@BiocondaBot please update

**Review by rpetit3 — APPROVED** [review]

**Comment by rpetit3** [comment]
@BiocondaBot please merge

**Pull request merged**
