### PR TITLE
Add RapGreen

### PR DESCRIPTION
**Pull request by SalihaZ**
This PR adds rap-green to bioconda. RAP-Green is a new implementation and an improvment of the RAP software (http://pbil.univ-lyon1.fr/software/RAP/RAP.htm). It's a phylogenetic tree analysis package to compare gene and species trees, infers duplication events, and provide confidence score in function conservation between genes. which permits to compare gene and species trees, infers duplication events, and provide confidence score in function conservation between genes. 

Jean-François Dufayard, Laurent Duret, Simon Penel, Manolo Gouy, François Rechenmann, Guy Perrière

Tree pattern matching in phylogenetic trees: automatic search for orthologs or paralogs in homologous gene sequence databases
Bioinformatics, Volume 21, Issue 11, June 2005.
https://doi.org/10.1093/bioinformatics/bti325

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by SalihaZ** [comment]
@Juke34

**Comment by SalihaZ** [comment]
@Juke34  Le conda build a fonctionné. Merci pour tes corrections

**Comment by Juke34** [comment]
Here are the current lint errors: 
```
ERROR: recipes/rapgreen/meta.yaml:38: extra_identifiers_not_string: Each item in the extra/identifiers section must be a string
ERROR: recipes/rapgreen/meta.yaml:2: folder_and_package_name_must_match: The recipe folder and package name do not match.
ERROR: recipes/rapgreen/meta.yaml:11: should_be_noarch_generic: The recipe should be build as `noarch`
```

I will try to look at it tomorrow

**Comment by dpryan79** [comment]
You'll have to replace the shebang to use python3 instead (also make sure to mention python >=3 in the recipe if that hasn't already been done).

**Comment by Juke34** [comment]
Thank you I will try that

**Comment by dpryan79** [comment]
OK, that's super strange, it's almost as if there's somehow a ":" being added to the shebang at some point.

**Comment by Juke34** [comment]
I agree, this is super weird. looking forward to find a way to debug that.

**Comment by Juke34** [comment]
@dpryan79 any clues?

**Review by Juke34 — APPROVED** [review]

**Pull request merged**
