### PR TITLE
Add recipe for halla

### PR DESCRIPTION
**Pull request by npavlovikj**
:information_source:
Bioconda has finished the [GCC7 migration](https://github.com/bioconda/bioconda-recipes/issues/13578). If you are dealing with C/C++ or Python package it can be that you need to rebuild other dependent packages. [Bioconda utils - update-pinning](https://bioconda.github.io/updating.html#updating-recipes-for-a-pinning-change) will assist you with that. If you have any questions please use [issue 13578](https://github.com/bioconda/bioconda-recipes/issues/13578).

----------------

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by npavlovikj** [comment]
@bioconda/core , I would like your feedback on this recipe if possible. 
I have hard time understanding why the OSX build is sometimes successful, and sometimes it is not. As you can see, the second commit built ok, I tried few other things, and reverted to the successful one, which then failed... I was encountering the same for the Linux builds in my previous PR, but that is working ok now ¯\_(ツ)_/¯ To me, it looks like the "_2to3_" changes are something accepted, sometimes not, and I don't know what causes that. 
If you have any idea, or notice something in my recipe is not compatible, I would appreciate you letting me know.

**Comment by dpryan79** [comment]
It looks like `2to3` isn't running all of the time for some reason. Do you mind if I play around with this PR to try and diagnose things?

**Comment by dpryan79** [comment]
At the moment this is only building for python 3.6 (presumably due to a dependency being absent for python 2), is that what you really want?

**Comment by npavlovikj** [comment]
@dpryan79 , many thanks for looking into this! 
Do you know what dependencies for Python 2.7 are missing (if that is the reason for not being built with Python 2.7)? I checked them all, and installed them locally in a Python 2.7 environment, and they all were available.
Since this is Python 2/3 package I would like to try to have both builds available, unless you recommend otherwise.

**Comment by dpryan79** [comment]
I'm not really sure, I'll play around with the recipe a bit and see if I can figure out what's going on with python 2.7. Is there a reason you're not building for python 3.7?

**Comment by npavlovikj** [comment]
Thanks @dpryan79 , please go ahead and play with the recipe. For Pyhon 3.7 some of the dependencies were missing. In the meantime, I can check and see is it feasible to have those dependencies for Python 3.7 available.

**Comment by dpryan79** [comment]
I'm already bumping minepy :) https://github.com/bioconda/bioconda-recipes/pull/14043

**Comment by dpryan79** [comment]
The `2to3` changes turn out to not be needed, it's already python3 (though it's pretty hacky how they did it). Now that minepy is built for python 3.7 we should be able to make this `noarch: python`.

**Comment by dpryan79** [comment]
I spoke too soon, there were a couple things I missed and `2to3` is still needed. I don't want to patch the source, so I'll revert to the previous commit that was working on all python builds.

**Comment by npavlovikj** [comment]
Thanks for all the updates @dpryan79  - you are few time zones ahead of me ;)
Fingers crossed the build passes 🤞

**Comment by npavlovikj** [comment]
Many thanks for all the help @dpryan79 ! 
So, allowing Python 3.7 fixed the issue? And what was the reason for it?

**Comment by dpryan79** [comment]
I don't know why it wasn't building for python 2.7 before, but it is now so I'm happy :)

**Comment by npavlovikj** [comment]
That makes two of us :)

**Pull request merged**
