### PR TITLE
Update recipe VerifyBamID2 - cmdline parsing logic to accept default usage on github page

### PR DESCRIPTION
**Pull request by Griffan**
Describe your pull request here

The original recipe broke the default usage described at verifybamid2's GitHub page: https://github.com/Griffan/VerifyBamID
This commit provides additional cmdline parsing rule to accept both of the two ways of handling the parsing task.

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by Griffan** [comment]
@BiocondaBot please add label

**Comment by dpryan79** [comment]
Can you bump the build number? Otherwise no package will be produced

**Comment by Griffan** [comment]
> Can you bump the build number? Otherwise no package will be produced

What is the build number? Do you refer to the vb2 version number?

**Comment by Griffan** [comment]
> Can you bump the build number? Otherwise no package will be produced

Could you take a look at this PR, whenever I bump build number, the lint test would fail? @dpryan79

**Comment by Griffan** [comment]
@BiocondaBot please add label

**Comment by dpryan79** [comment]
Guess you figured it out while I was in a meeting :)

**Comment by Griffan** [comment]
@BiocondaBot please add label

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Comment by Griffan** [comment]
@dpryan79 Hi, Ryan 
This is the first time I contribute to the recipe, now that the branch has been merged, it should be able to be installed. However, I can not "conda install -c bioconda verifybamid2". Does it take some time to populate the updated version?

**Comment by dpryan79** [comment]
It'll take about 30 minutes after upload for the global CDN to update. Please remember to use conda-forge too: `conda install -c conda-forge -c bioconda verifybamid2`

**Comment by Griffan** [comment]
@dpryan79 I still cannot install the updated recipe:
```
conda install -c conda-forge -c bioconda verifybamid2
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - verifybamid2

Current channels:

  - https://conda.anaconda.org/conda-forge/osx-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://conda.anaconda.org/bioconda/osx-64
  - https://conda.anaconda.org/bioconda/noarch
  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```
Do you have any idea what's wrong with this?

**Pull request merged**
