### PR TITLE
add blast for osx

### PR DESCRIPTION
**Pull request by tomkinsc**

### CODE REVIEW

**Comment by tomkinsc** [comment]
This is failing because it seems blast may have been added to bioconda before we gained the CentOS 5 test environment. CentOS 5 lacks GLIBC_2.7, which is required for the blast binaries distributed by the NCBI. It seems we will need to compile it from source.

**Comment by tomkinsc** [comment]
It now builds locally for me within the docker container, but the test times out on travis because the compile step takes so long.

**Comment by tomkinsc** [comment]
I'm not sure how to get around the long build times. Any ideas?

**Comment by daler** [comment]
I think the timeouts on travis are from lack of log output rather than amount of CPU time spent. Maybe passing `-v` to `build-packages.py` would spit enough out to the log to keep travis-ci happy? This may need a one-off change to `scripts/travis-run.sh` just for this recipe.

A shot in the dark, but would it be possible to break the recipe into pieces somehow and create intermediate recipes that depend on each other? I just checked the source to see how that might be done and saw the complexity of the build system . . . wow. It would take some work to do this even if possible.

**Comment by tomkinsc** [comment]
Yeah, you're [completely correct](https://docs.travis-ci.com/user/customizing-the-build/#Build-Timeouts); ten minutes without log output is enough for Travis to kill the test. Changing scripts/travis-run.sh for only this recipe does not seem ideal--what if there are future projects with long build times? 

@johanneskoester, what do you think?

**Comment by johanneskoester** [comment]
Actually this should already have been solved already by adding ``travis_wait`` (see [here](https://docs.travis-ci.com/user/build-timeouts#Build-times-out-because-no-output-was-received)). In principle, there shouldn't be any timeouts now, because travis_wait will print a log message every 20 minutes. If that does not work, we should contact the travis guys.

**Comment by daler** [comment]
[This docs section](https://docs.travis-ci.com/user/build-timeouts) says `travis_wait` prints every minute for up to 20 mins (rather than every 20 mins, as I originally thought). [This line](https://travis-ci.org/bioconda/bioconda-recipes/jobs/94499888#L135) in the blast build log implies the same.

Also after reading the travis docs more carefully, there's a difference between *jobs* (e.g. one job for each version of Python) and *builds* (e.g., one PR). One build can have many jobs. Builds can take as long as they need, but one job has a 120 min limit regardless of log output. Given that you mention compiling locally took 82 mins, you might be close to hitting that limit here.

Ideally we'd want something like `travis_wait` that prints every 5 mins for up to 120 mins.

**Comment by tomkinsc** [comment]
It's not documented, but it [looks like](https://github.com/travis-ci/travis-build/blob/7f4f6ca6ad82bd08da746b2f951a660c84fbde32/lib/travis/build/templates/header.sh#L113) `travis_wait()` does allow the timeout to be specified, if the first argument is an integer. Can we give it 119 (just shy of the hard 120-minute cutoff), as in PR #349?

**Comment by johanneskoester** [comment]
That's good, I merged the PR.

**Pull request merged**
