### PR TITLE
Update ENA upload CLI to 0.7.3

### PR DESCRIPTION
**Pull request by bedroesb**
Describe your pull request here

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

### General instructions

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

### Instructions for avoiding API, ABI, and CLI breakage issues
Conda is able to record and lock (a.k.a. pin) dependency versions used at build time of other recipes.
This way, one can avoid that expectations of a downstream recipe with regards to API, ABI, or CLI are violated by later changes in the recipe.
If not already present in the meta.yaml, make sure to specify `run_exports` (see [here](https://bioconda.github.io/contributor/linting.html#missing-run-exports) for the rationale and comprehensive explanation).
Add a `run_exports` section like this:

```yaml
build:
  run_exports:
    - ...

```

with `...` being one of:

| Case                             | run_exports statement                                               |
| -------------------------------- | ------------------------------------------------------------------- |
| semantic versioning              | `{{ pin_subpackage("myrecipe", max_pin="x") }}`     |
| semantic versioning (0.x.x)      | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}`   |
| known breakage in minor versions | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| known breakage in patch versions | `{{ pin_subpackage("myrecipe", max_pin="x.x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| calendar versioning              | `{{ pin_subpackage("myrecipe", max_pin=None) }}`    |

while replacing `"myrecipe"` with either `name` if a `name|lower` variable is defined in your recipe or with the lowercase name of the package in quotes.

### Bot commands for PR management

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

Note that the <code>@BiocondaBot please merge</code> command is now depreciated. Please just squash and merge instead.

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by bedroesb** [comment]
@bgruening Something weird happened, a new pypi version got created: https://pypi.org/project/ena-upload-cli/0.7.2/ but it did not trigger bioconda autobump, and when I manually try to update the tool it fails because it can not find https://files.pythonhosted.org/packages/source/e/ena-upload-cli/ena-upload-cli-0.7.2.tar.gz, which indeed does not exist. How would you go further?

**Comment by martin-g** [comment]
Could you use the sources tarball from https://github.com/usegalaxy-eu/ena-upload-cli/releases/tag/0.7.2 ?

**Comment by bedroesb** [comment]
@martin-g That could be an option, but now I have to confess something: Upon creation of the release, I forgot to bump the version inside my python package, making the push to pip fail. I fixed this and redid the push, and everything appeared to be normal, until now. Maybe the easiest is to bump the version again, correctly this time?

**Comment by martin-g** [comment]
Versions are cheap! :-) Just release a new (patch) version!

**Comment by bedroesb** [comment]
ok Thanks! @martin-g

**Comment by bedroesb** [comment]
@martin-g sadly the problem stays: https://github.com/usegalaxy-eu/ena-upload-cli/actions/runs/9369107316/job/25792761004 worked fine, but I still cannot curl 

```
curl -L https://files.pythonhosted.org/packages/source/e/ena-upload-cli/ena-upload-cli-0.7.3.tar.gz
```

**Comment by bgruening** [comment]
Maybe pypi needs to update the index or the CDN? Lets wait a bit, the tarball is on pypi at least.

**Comment by martin-g** [comment]
I meant to use the tar.gz from the GitHub release page.

**Comment by bedroesb** [comment]
But is that feels like not solving the underlying issue here? I really liked the automatic triggering from BioConda ...

**Comment by martin-g** [comment]
The autobump functionality would still work with the Github url. Many other recipes (Python and non-Python) use it.
It seems pypi.org made some changes in their infrastructure ... At https://pypi.org/project/ena-upload-cli/0.7.2/#files you can see that the source tarball is at https://files.pythonhosted.org/packages/23/87/f7b4436d950bdb74e0f9062a57108c67453ccfa33e6d0756a1ed9e89305d/ena_upload_cli-0.7.2.tar.gz, i.e. they use hash in the url path.

Let's try with https://github.com/usegalaxy-eu/ena-upload-cli/archive/refs/tags/0.7.2.tar.gz and see how it goes!

**Review by martin-g — APPROVED** [review]

**Comment by bedroesb** [comment]
Thanks for the help!

**Pull request merged**
