### PR TITLE
Add recipe for gffcompare 0.9.8

### PR DESCRIPTION
**Pull request by davebx**
* [x] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by davebx** [comment]
@bgruening The failing build is (partly) because I didn't push #4371

**Comment by bgruening** [comment]
Btw. you can also put multiple recipes in one PR. BioConda is smart enough to figure out the buid-chain.

**Comment by davebx** [comment]
Oh. I must have been misremembering, or confusing bioconda and some other project that does restrict pull requests to one package.

**Comment by bgruening** [comment]
Can this help: https://bioconda.github.io/guidelines.html#c-c

**Comment by davebx** [comment]
It looks like travis is trying to use build 2 of gclib, but build 3 (included here) would finish successfully

**Comment by bgruening** [comment]
Can you try a rebase, the second package is not build at all locally :(

**Comment by davebx** [comment]
Oh dear, I think I rebased wrong.

**Pull request merged**
