### PR TITLE
Add perl-ensembl-core

### PR DESCRIPTION
**Pull request by abretaud**
Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it. Note that if you are not already a member of the bioconda project (meaning that you can't add this label), please ping `@bioconda/core` so that your PR can be reviewed and merged (please note if you'd like to be added to the bioconda project). Please see https://github.com/bioconda/bioconda-recipes/issues/15332 for more details.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

A new dep for RSAT: perl-ensembl-core
There are no release archives on the github repo + no way to create issues...

### CODE REVIEW

**Comment by abretaud** [comment]
We'll need this dep too: https://github.com/bioconda/bioconda-recipes/pull/18392

**Comment by vladsaveliev** [comment]
Thanks @abretaud for starting this work! It would be so fantastic if you could figure out what's wrong with the BigFile recipe. I feel desperate.

Vlad

**Comment by abretaud** [comment]
@BiocondaBot please fetch artifacts

**Comment by abretaud** [comment]
@BiocondaBot please add label

**Comment by dpryan79** [comment]
@BiocondaBot please merge

**Pull request merged**
