### PR TITLE
Update meta.yaml

### PR DESCRIPTION
**Pull request by rob-p**
Describe your pull request here

Bump piscem to v 0.4.0

### CODE REVIEW

**Comment by rob-p** [comment]
@bioconda-bot please merge. (Not sure if I can do this)

**Comment by rob-p** [comment]
@bioconda-bot please request a review for this PR.

**Comment by dpryan79** [comment]
@BiocondaBot please fetch artifacts

**Comment by dpryan79** [comment]
@BiocondaBot please merge

**Comment by dpryan79** [comment]
@BiocondaBot please merge

**Comment by dpryan79** [comment]
"Rate limit exceeded" in an API call. Oh well, the old fashioned way it is then.

**Pull request merged**
