### PR TITLE
Feature/popscle

### PR DESCRIPTION
**Pull request by jerowe**
Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it. Note that if you are not already a member of the bioconda project (meaning that you can't add this label), please ping `@bioconda/core` so that your PR can be reviewed and merged (please note if you'd like to be added to the bioconda project). Please see https://github.com/bioconda/bioconda-recipes/issues/15332 for more details.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by dpryan79** [comment]
I'll approve this and ask upstream to tag an actual release (that would also give is a proper version).

**Comment by dpryan79** [comment]
Xref: https://github.com/statgen/popscle/issues/13

**Comment by dpryan79** [comment]
Merge when you're happy with things (and you expect the version number is correct).

**Comment by jerowe** [comment]
I suspect the build got stuck somewhere.

As of now there are no version numbers. I'll wait a bit and see if the dev comes back with a version number.

**Comment by dpryan79** [comment]
They've tagged a release now :)

**Comment by jerowe** [comment]
Awesome! I'll update the recipe with the version number. ;-)

**Pull request merged**
