### PR TITLE
Add exomedepth R package

### PR DESCRIPTION
**Pull request by drramki-chop**

### CODE REVIEW

**Comment by johanneskoester** [comment]
Looks good, but somehow denovogear is also in a different PR...

**Comment by drramki-chop** [comment]
somebody else had an existing recipe and it got approved. My PR should be closed.

**Comment by johanneskoester** [comment]
Ok!

**Comment by drramki-chop** [comment]
Can you reopen this?

The comment about existing recipe was for denovogear. not for exomedepth.

**Comment by johanneskoester** [comment]
Oh sorry, sure ;-).

**Pull request closed without merging**
