### PR TITLE
Update megalodon to 2.1.0

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`megalodon`](https://bioconda.github.io/recipes/megalodon/README.html): **2.0.0** &rarr; **2.1.0**

[install with bioconda](http://bioconda.github.io/recipes/megalodon/README.html) [Conda](https://anaconda.org/bioconda/megalodon/files)

Info | Link
-----|-----
Recipe | [`recipes/megalodon`](https://github.com//bioconda/bioconda-recipes/tree/bump/megalodon/recipes/megalodon) (click to view/edit other files)
Releases |[https://github.com/nanoporetech/megalodon/tags](https://github.com/nanoporetech/megalodon/tags)
Recipe Maintainer(s) | @marcus1487
Author | `@nanoporetech`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by marcus1487** [comment]
@BiocondaBot autobump [megalodon]

**Comment by marcus1487** [comment]
I mistakenly thought there was an issue with the megalodon code and pushed a 2.1.1 release. I have since deleted this release as the issue was with the bioconda recipe. This PR should be reverted to the 2.1.0 release.

**Comment by marcus1487** [comment]
PR #22762 submitted with fixes to this PR.

**Comment by cjw85** [comment]
@marcus1487 Can you check this is now correct?

**Comment by marcus1487** [comment]
@cjw85 It was correct before the bot got it's hands on the PR again. Not sure how to turn the bot off of this release as github does not actually remove the release artifacts.

**Comment by cjw85** [comment]
@bioconda-bot please merge

**Pull request merged**
