### PR TITLE
Unpin HMMER in pasta and sepp

### PR DESCRIPTION
**Pull request by Sann5**
HMMER is pinned in both the pasta and sepp recipes. This PR explores unpinning it in both.

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

### General instructions

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

### Instructions for avoiding API, ABI, and CLI breakage issues
Conda is able to record and lock (a.k.a. pin) dependency versions used at build time of other recipes.
This way, one can avoid that expectations of a downstream recipe with regards to API, ABI, or CLI are violated by later changes in the recipe.
If not already present in the meta.yaml, make sure to specify `run_exports` (see [here](https://bioconda.github.io/contributor/linting.html#missing-run-exports) for the rationale and comprehensive explanation).
Add a `run_exports` section like this:

```yaml
build:
  run_exports:
    - ...

```

with `...` being one of:

| Case                             | run_exports statement                                               |
| -------------------------------- | ------------------------------------------------------------------- |
| semantic versioning              | `{{ pin_subpackage("myrecipe", max_pin="x") }}`     |
| semantic versioning (0.x.x)      | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}`   |
| known breakage in minor versions | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| known breakage in patch versions | `{{ pin_subpackage("myrecipe", max_pin="x.x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| calendar versioning              | `{{ pin_subpackage("myrecipe", max_pin=None) }}`    |

while replacing `"myrecipe"` with either `name` if a `name|lower` variable is defined in your recipe or with the lowercase name of the package in quotes.

### Bot commands for PR management

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

Note that the <code>@BiocondaBot please merge</code> command is now depreciated. Please just squash and merge instead.

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Review by sjanssen2 — CHANGES_REQUESTED** [review]
Would be grate if we can lift this restriction, however we don't know to what degree this effects the program's output. Within the bioconda setup, there is no test for result regression. You would need to run a set of identical inputs on SEPP / pasta and compare current with your version.

**Comment by Sann5** [comment]
@sjanssen2 will do so :). Ill let you know what comes out.

**Comment by sjanssen2** [comment]
Hi @Sann5 , sorry for the late reply, I was traveling. When I created the bioconda recipe for SEPP, I had one specific application in mind, which is inserting ASVs from 16S rRNA data into the GreenGenes13.8 phylogeny: https://doi.org/10.1128/msystems.00021-18 This package also made it into docs.Qiime2.org and qiita.ucsd.edu

Therefore, I am about to perform another test, namely compute an insertion tree for some 16S data and compare results in terms of e.g. robinson fooulds distance https://scikit.bio/docs/dev/generated/skbio.tree.TreeNode.compare_rfd.html#skbio.tree.TreeNode.compare_rfd for this specific use case. I will give you an update, once I have results.

I'd furthermore love to wait for @smirarab input, as he is the main developer of SEPP, but a bit unresponsive over the last month :-/

**Comment by sjanssen2** [comment]
Hi @Sann5,
SEPP operates in two phases: 1) a placement per query sequence is determined (via e.g. hmmer) 2) from all placements `guppy` constructs a phylogenetic tree from the reference tree and placements computed in phase 1.

I am focusing on phase 1 for now. Here are my input sequences (16S rRNA 150nt from a real microbiome experiment https://www.biorxiv.org/content/10.1101/2024.03.14.584950v1): [sequences1.mfa.gz](https://github.com/user-attachments/files/15977636/sequences1.mfa.gz)

Let me lure @antgonza (developer of Qiita) and @gregcaporaso (developer of Qiime2) into this discussion as changes might effect their software. I am comparing against SEPP as shipped with qiime2-2023.5.

1) both versions have approx the same runtime
2) the number of placements is different, there are 10 missing in the new version :-( 
2b) however, if we reorder the placement json such that we use the sequences as keys and placements as values, both versions cover all 16581 ASVs from the input :-)
3) comparing all 16581 placements results in 342 that are different between both versions :-(
3b) be reminded that SEPP often returns co-optimale placement positions. Of the 342, 183 differ with all alternatives with regards to the node of the reference where the ASV would be inserted :-( The other 159 have at least some overlap, i.e. hit the same node (beside others)

More results will follow, but I do think that we also need @smirarab opinion on the severity of the differences

**Comment by sjanssen2** [comment]
computing tip to tip distance on the full phylogenetic trees was computationally too demanding. Therefore I sheared the trees to the inserted 16581 ASV tips and pruned them and could then compute the tip to tip distance with skbio, which is `0.0007949320329700971`, i.e. rather small.

As a reference, we might use Figure 5 of the above publication, in which I found the mean tip to tip distance of all members of a species in the reference pyhlogenetic tree (GG13.8) is approx `0.05`:
image

My conclusion is that the switch to another hmmer version DOES result in different results HOWEVER these differences are presumably very small, i.e. could be ignored in downstream analysis. For reproducibility you should increase the version number of the conda recipe to better indicate the changes. @antgonza we need to think about how to handle the ASV placement database in Qiita!

**Comment by smirarab** [comment]
We need to increase the major since the results will change from the previous version. It seems @sjanssen2 has done a thorough test and therefore I feel comfortable moving ahead with this as long as we do increase the major version number too. 

Also, sorry all for being unresponsive. I am dealing with a lot of personal stuff that will make me less responsive for a while.

**Comment by sjanssen2** [comment]
please have a look at my alternative PR #47895

**Comment by aliciaaevans** [comment]
Closing in favor of https://github.com/bioconda/bioconda-recipes/pull/47895

**Pull request closed without merging**
