### PR TITLE
breseq: add aarch64/arm64 support

### PR DESCRIPTION
**Pull request by martin-g**
Describe your pull request here

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

### General instructions

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

### Instructions for avoiding API, ABI, and CLI breakage issues
Conda is able to record and lock (a.k.a. pin) dependency versions used at build time of other recipes.
This way, one can avoid that expectations of a downstream recipe with regards to API, ABI, or CLI are violated by later changes in the recipe.
If not already present in the meta.yaml, make sure to specify `run_exports` (see [here](https://bioconda.github.io/contributor/linting.html#missing-run-exports) for the rationale and comprehensive explanation).
Add a `run_exports` section like this:

```yaml
build:
  run_exports:
    - ...

```

with `...` being one of:

| Case                             | run_exports statement                                               |
| -------------------------------- | ------------------------------------------------------------------- |
| semantic versioning              | `{{ pin_subpackage("myrecipe", max_pin="x") }}`     |
| semantic versioning (0.x.x)      | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}`   |
| known breakage in minor versions | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| known breakage in patch versions | `{{ pin_subpackage("myrecipe", max_pin="x.x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| calendar versioning              | `{{ pin_subpackage("myrecipe", max_pin=None) }}`    |

while replacing `"myrecipe"` with either `name` if a `name|lower` variable is defined in your recipe or with the lowercase name of the package in quotes.

### Bot commands for PR management

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

Note that the <code>@BiocondaBot please merge</code> command is now depreciated. Please just squash and merge instead.

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by martin-g** [comment]
@BiocondaBot please fetch artifacts

**Review by druvus — APPROVED** [review]

**Comment by martin-g** [comment]
@aliciaaevans I don't understand why `bowtie2` has been built for `osx-arm64` here. Any idea ?

**Comment by martin-g** [comment]
```
mgrigorov in 🌐 euler-arm-22 in /tmp/breseq via 🅒 test123 took 4s 
❯ tar xvf breseq-0.39.0-hf1d9491_1.tar.bz2                                                                                                                                                                 (test123) 
info/run_exports.json
info/recipe/build.sh
info/test/run_test.sh
info/hash_input.json
info/files
info/index.json
info/recipe/meta.yaml.template
info/recipe/meta.yaml
info/paths.json
info/recipe/conda_build_config.yaml
info/about.json
info/licenses/COPYING
info/git
share/breseq/plot_jc_scores.r
share/breseq/plot_coverage.r
share/breseq/plot_error_rate.r
share/breseq/polymorphism_statistics.r
share/breseq/coverage_distribution.r
share/breseq/breseq_small.png
share/breseq/breseq.png
share/breseq/indels.conf
share/breseq/mobs.conf
share/breseq/mutations.conf
share/breseq/combined_circos.conf
share/breseq/run_circos.sh
bin/gdtools
bin/breseq

mgrigorov in 🌐 euler-arm-22 in /tmp/breseq via 🅒 test123 
❯ file bin/*                                                                                                                                                                                               (test123) 
bin/breseq:  ELF 64-bit LSB pie executable, ARM aarch64, version 1 (GNU/Linux), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, with debug_info, not stripped
bin/gdtools: ELF 64-bit LSB pie executable, ARM aarch64, version 1 (GNU/Linux), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, with debug_info, not stripped

mgrigorov in 🌐 euler-arm-22 in /tmp/breseq via 🅒 test123 
❯ ./bin/breseq                                                                                                                                                                                             (test123) 
================================================================================
breseq 0.39.0     http://barricklab.org/breseq

Active Developers: Barrick JE, Deatherage DE
Contact:           <jeffrey.e.barrick@gmail.com>

breseq is free software; you can redistribute it and/or modify it under the
terms the GNU General Public License as published by the Free Software 
Foundation; either version 2, or (at your option) any later version.

Copyright (c) 2008-2010 Michigan State University
Copyright (c) 2011-2022 The University of Texas at Austin

If you use breseq in your research, please cite:

  Deatherage, D.E., Barrick, J.E. (2014) Identification of mutations
  in laboratory-evolved microbes from next-generation sequencing
  data using breseq. Methods Mol. Biol. 1151: 165–188.

If you use structural variation (junction) predictions, please cite:

  Barrick, J.E., Colburn, G., Deatherage D.E., Traverse, C.C.,
  Strand, M.D., Borges, J.J., Knoester, D.B., Reba, A., Meyer, A.G. 
  (2014) Identifying structural variation in haploid microbial genomes 
  from short-read resequencing data using breseq. BMC Genomics 15:1039.
================================================================================

Usage: breseq -r reference.gbk [-r reference2.gbk ...] reads1.fastq [reads2.fastq.gz ...]

Run the breseq pipeline for predicting mutations from haploid microbial re-sequencing data.

FASTQ read files (which may be gzipped) are input as the last unnamed argument(s).

Allowed Options
  -h,--help                        Produce help message showing advanced options
  -r,--reference <arg>             File containing reference sequences in GenBank, GFF3, or FASTA format. Option may be provided multiple times for multiple files (REQUIRED)
  -n,--name <arg>                  Human-readable name of the analysis run for output (DEFAULT=<none>)
  -j,--num-processors <arg>        Number of processors to use in multithreaded steps (DEFAULT=1)
  -o,--output <arg>                Path to breseq output (DEFAULT=.)
  -p,--polymorphism-prediction     The sample is not clonal. Predict polymorphic (mixed) mutations. Setting this flag changes from CONSENSUS MODE (the default) to POLYMORPHISM MODE
  -x,--nanopore                    Set options for nanopore data. Equivalent to --consensus-reject-indel-homopolymer-length 4 --polymorphism-reject-indel-homopolymer-length 4 consensus/polymorphism
                                   --polymorphism-no-indel --bowtie2-stage1 "--local -i S,1,0.25 --score-min L,6,0.2 -k 2000" --bowtie2-stage2 "". If you provide any of these options on their own, then they will
                                   override these preset options.
  --no-junction-prediction         Do not predict new sequence junctions

Utility Command Usage: breseq [command] options ...
  Sequence Utility Commands: CONVERT-FASTQ, CONVERT-REFERENCE, GET-SEQUENCE
  Breseq Post-Run Commands: BAM2ALN, BAM2COV, CL-TABULATE
  Other Commands: SOFT-CLIPPING

For help using a utility command, type: breseq [command] 

================================================================================

No read sequence files provided.
```
LGTM!

**Comment by martin-g** [comment]
@BiocondaBot please add label

**Comment by aliciaaevans** [comment]
> @aliciaaevans I don't understand why `bowtie2` has been built for `osx-arm64` here. Any idea ?

Not sure, but it seems like conda-build took it upon itself to do that, not something in bioconda-utils. Since it apparently built successfully, let's get bowtie2 for OSX arm uploaded properly and then rebuild this once it's available in the channel.  https://github.com/bioconda/bioconda-recipes/pull/49150

**Review by aliciaaevans — CHANGES_REQUESTED** [review]
Merge master back to this to rebuild after bowtie2 osx-arm64 is available in the channel.

**Review by aliciaaevans — APPROVED** [review]

**Comment by bgruening** [comment]
Thanks everyone.

**Pull request merged**
