### PR TITLE
PBSuite a new recipe

### PR DESCRIPTION
**Pull request by mictadlo**
* [x] I have read the guidelines above.
* [x] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by mictadlo** [comment]
Hi @druvus @bgruening,
How do I add the code out of this directory`pbsuite`?

Thank you in advance.

Michal

**Comment by bgruening** [comment]
@mictadlo what do you mean with `adding code out`?

**Comment by mictadlo** [comment]
`pbsuite` directory contains code which is required to the code in the `bin` folder.

**Comment by mictadlo** [comment]
Any idea why I got [TESTS FAILED: pbsuite-15.8.24-py27_0](https://travis-ci.org/bioconda/bioconda-recipes/jobs/214082536#L749)?

**Comment by johanneskoester** [comment]
In zour test case, please remove the pipe to `/dev/null`. I guess the error is hidden there.

**Comment by johanneskoester** [comment]
We have migrated our build system from Travis CI to Circle CI. If you would like to continue working on this PR, please update with latest upstream master and reopen this PR.

**Pull request closed without merging**
