### PR TITLE
Update quatradis to 0.6.1

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`quatradis`](https://bioconda.github.io/recipes/quatradis/README.html): **0.5.4** &rarr; **0.6.1**

[install with bioconda](http://bioconda.github.io/recipes/quatradis/README.html) [Conda](https://anaconda.org/bioconda/quatradis/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/quatradis`](https://github.com//bioconda/bioconda-recipes/tree/bump/quatradis/recipes/quatradis) (click to view/edit other files)
Summary | A set of tools to analyse the output from TraDIS analyses
Home | [https://github.com/quadram-institute-bioscience/QuaTradis](https://github.com/quadram-institute-bioscience/QuaTradis)
Releases |[https://github.com/quadram-institute-bioscience/QuaTradis/tags](https://github.com/quadram-institute-bioscience/QuaTradis/tags)
Recipe Maintainer(s) | @sbastkowski, @maplesond, @thanhleviet
Author | `@quadram-institute-bioscience`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by marcelm** [comment]
Please do not merge until @maplesond has told us what to do with #33337 and #33385. It seems the tool doesn’t work even though the tests pass.

**Comment by marcelm** [comment]
The test command suceeded because it searched for the string `tradis` in the output of `tradis --help` and also the error message contains that string.

**Comment by maplesond** [comment]
Not sure I understand the previous comment.  It looks like the test failed because bgzip isn't present.  I guess the question is how do we install that using conda?  Possibly htslib handles this after the other PR is merged?

**Comment by marcelm** [comment]
This is what it says in the log [error message](https://dev.azure.com/bioconda/bioconda-recipes/_build/results?buildId=12955&view=logs&j=e14e69ff-a0ae-55c4-b71d-229b239cfb2f&t=7df82132-b284-504b-53d6-7d3e63519572&l=521):
```
15:24:08 BIOCONDA INFO (OUT) + tradis --help
15:24:09 BIOCONDA INFO (OUT) Traceback (most recent call last):
15:24:09 BIOCONDA INFO (OUT)   File "/opt/conda/conda-bld/quatradis_1646493135260/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/bin/tradis", line 16, in <module>
15:24:09 BIOCONDA INFO (OUT)     version = pkg_resources.require("quatradis")[0].version
15:24:09 BIOCONDA INFO (OUT)   File "/opt/conda/conda-bld/quatradis_1646493135260/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.7/site-packages/pkg_resources/__init__.py", line 891, in require
15:24:09 BIOCONDA INFO (OUT)     needed = self.resolve(parse_requirements(requirements))
15:24:09 BIOCONDA INFO (OUT)   File "/opt/conda/conda-bld/quatradis_1646493135260/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.7/site-packages/pkg_resources/__init__.py", line 777, in resolve
15:24:09 BIOCONDA INFO (OUT)     raise DistributionNotFound(req, requirers)
15:24:09 BIOCONDA INFO (OUT) pkg_resources.DistributionNotFound: The 'bgzip' distribution was not found and is required by quatradis
```
Previously, the test was written as `tradis --help 2>&1 | grep tradis`. Since the message contains the string "tradis" ("... not found and is required by quatradis"), the test would incorrectly pass.

I cannot access the Azure build log for the tests that ran before I made commit [4888585](https://github.com/bioconda/bioconda-recipes/pull/33531/commits/48885852f0e675f6f6c0b03b5c618f353d0799b0), but you can see that the Linux test passes although it shouldn’t.

Regarding `bzgip`, is it correct that you want to have a dependency on the [Python package called "bgzip"](https://pypi.org/project/bgzip/)? I think that one is available as `py-bgzip` on conda-forge. If you actually want the command-line `bgzip` program, then you need to add a dependency on the Conda package `tabix`, which contains that binary.

I strongly recommend that you also fix your `requirements.txt` file to not include the development-only dependencies pytest-cov and semantic-version. If you don’t, the Bioconda recipe will need to patch the `requirements.txt` file, which is just annoying extra work.

**Comment by maplesond** [comment]
Hi @marcelm, ok I'll create a new release shortly with "semantic-version" and "pytest-cov" as extra dependencies handled separately as you suggest.  So I don't need bgzip as a python package necessarily as it should come with BioPython, but I think the dependencies require it installed as an executable on the system to work correctly.  This will be the case if htslib is installed (at least from source).  Here's an [example](https://github.com/quadram-institute-bioscience/QuaTradis/blob/master/quatradis/isp_create.py#L9) of how I'm using it.  Also in case it helps to figure out what I'm trying to achieve here'e the [Dockerfile](https://github.com/quadram-institute-bioscience/QuaTradis/blob/master/Dockerfile) which works just fine.

**Comment by marcelm** [comment]
> So I don't need bgzip as a python package necessarily as it should come with BioPython, but I think the dependencies require it installed as an executable on the system to work correctly.

I think Biopython doesn’t need the executable. They appear to have their own implementation of the bgzip format.

In https://github.com/quadram-institute-bioscience/QuaTradis/blob/fc601e07e144e8edb9a8b7d25ddcccb5f06c9a22/quatradis/isp_combine.py#L141, you call `bgzip`, however, so your script needs the bgzip executable.

> This will be the case if htslib is installed

Yes, my mistake: bgzip was previously in the tabix package, but that one was merged into htslib.

**Pull request closed without merging**
