### PR TITLE
Update minimap2 to 2.25

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`minimap2`](https://bioconda.github.io/recipes/minimap2/README.html): **2.24** &rarr; **2.25**

[install with bioconda](http://bioconda.github.io/recipes/minimap2/README.html) [Conda](https://anaconda.org/bioconda/minimap2/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/minimap2`](https://github.com//bioconda/bioconda-recipes/tree/bump/minimap2/recipes/minimap2) (click to view/edit other files)
Summary | A versatile pairwise aligner for genomic and spliced nucleotide sequences.
Home | [https://github.com/lh3/minimap2](https://github.com/lh3/minimap2)
Releases |[https://github.com/lh3/minimap2/tags](https://github.com/lh3/minimap2/tags)
Author | @lh3
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Review by lh3 — APPROVED** [review]

**Comment by lh3** [comment]
@BiocondaBot please merge

**Comment by lh3** [comment]
@BiocondaBot please add label

**Comment by lh3** [comment]
@BiocondaBot please merge

**Comment by lh3** [comment]
The Bot is [reporting errors](https://github.com/bioconda/bioconda-recipes/actions/runs/4802690857). Could I manually merge? CC @bgruening.

**Comment by lh3** [comment]
@BiocondaBot please merge

**Comment by bgruening** [comment]
Yes, from now on pleae click the merge button. All the magic from the bot was moved to the merge step

**Comment by lh3** [comment]
Thanks for the confirmation!

**Pull request merged**
