### PR TITLE
Revert "rdkit: add pillow as runtime dependency"

### PR DESCRIPTION
**Pull request by bgruening**
Reverts bioconda/bioconda-recipes#2078

### CODE REVIEW

**Comment by bgruening** [comment]
@johanneskoester @daler this worries me a little bit. I think all the other PR are not build and are working. This one isn't with the new Docker container. With the old one it worked as it seems. Any ideas? I tried to add gcc as dependency in https://github.com/bioconda/bioconda-recipes/pull/2084 because I thought it's the build-in gcc version from the Container, but is was also not working.

Ideas welcome. I will revert this PR for the time being.
ping @dmaticzka

**Comment by johanneskoester** [comment]
Sorry, I don't get the problem yet (maybe it is still too early for me). The resulting package is not working?

**Comment by bgruening** [comment]
The PR of this package was working with the old build-system, merging into the new build-system broke it as it seems.

**Comment by johanneskoester** [comment]
Ok. Looks like it can't link to some boost stuff (see [here](https://travis-ci.org/bioconda/bioconda-recipes/jobs/149254778#L4211)). Maybe that error did not occur in our own container because lib was leaked in from CentOS.

**Comment by johanneskoester** [comment]
Ok. Looks like it can't link to some boost stuff (see [here](https://travis-ci.org/bioconda/bioconda-recipes/jobs/149254778#L4211)). Maybe that error did not occur in our own container because lib was leaked in from CentOS.

**Pull request merged**
