### PR TITLE
Add vartrix

### PR DESCRIPTION
**Pull request by raivivek**
Add vartrix -- 10X Single-cell genotyping lib

----

> Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences**
      (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

> Everyone has access to the following BiocondaBot commands, which can be given in a comment:
>
>  * `@BiocondaBot please update` will cause the BiocondaBot to merge the master branch into a PR
>  * `@BiocondaBot please add label` will add the `please review & merge` label.
>  * `@BiocondaBot please fetch artifacts` will post links to packages and docker containers built by the CI system. You can use this to test packages locally before merging.
>
> For members of the Bioconda project, the following command is also available:
>
>  * `@BiocondaBot please merge` will cause packages/containers to be uploaded and a PR merged. Someone must approve a PR first! This has the benefit of not wasting CI build time required by manually merging PRs.
>
> If you have questions, please post them in gitter or ping `@bioconda/core` in a comment (if you are not able to directly ping `@bioconda/core` then the bot will repost your comment and enable pinging).

### CODE REVIEW

**Comment by raivivek** [comment]
@dpryan79 This built fine locally but not sure what happens on CircleCI.. any help would be appreciated.

**Comment by dpryan79** [comment]
I don't know why it's expecting clang on Linux.

**Comment by dpryan79** [comment]
Make sure to test in the docker container locally. Most likely there's some sort of environment variable that needs to be set to tell rust where the clang library can be found.

**Comment by raivivek** [comment]
Hi @johanneskoester Since this package involves use of rust-htslib, wondering if you've have quick minute or two to take a look. That's a package that I'm not too familiar with. Thanks!

**Comment by raivivek** [comment]
@BiocondaBot please update

**Comment by raivivek** [comment]
Closing this. Will reopen a new one when I've fixed it.

**Pull request closed without merging**
