### PR TITLE
Correct version 2.1.2

### PR DESCRIPTION
**Pull request by ozagordi**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.

Please ignore the wrong **branch** name. The recipe uses variables and it actually adds version 2.1.2 of MinVar.

### CODE REVIEW

**Comment by bgruening** [comment]
@ozagordi what about the old version. This is now wrong right? Do you plan to build the 2.1.1 version again? Should we remove this package?

**Comment by ozagordi** [comment]
There is a PR (#7347) for 2.1.1. It's a new build correcting the tarball link.

**Comment by johanneskoester** [comment]
We have made changes to our build system. Please update your fork with the latest upstream/master

**Comment by ozagordi** [comment]
Ok. Closing here and switching to dir/subdir structure.

**Pull request closed without merging**
