### PR TITLE
Bump khmer to 3.0.0a3

### PR DESCRIPTION
**Pull request by luizirber**
:information_source:
Bioconda has finished the [GCC7 migration](https://github.com/bioconda/bioconda-recipes/issues/13578). If you are dealing with C/C++ or Python package it can be that you need to rebuild other dependent packages. [Bioconda utils - update-pinning](https://bioconda.github.io/updating.html#updating-recipes-for-a-pinning-change) will assist you with that. If you have any questions please use [issue 13578](https://github.com/bioconda/bioconda-recipes/issues/13578).

----------------

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [x] This PR does something else (explain below).

Removes dependency on pytest-runner

### CODE REVIEW

**Comment by npavlovikj** [comment]
Do you know why the recipe has `python >=3`? "khmer" supports both Python 2.7 and Python 3.*, so it should just be `python`.

**Comment by luizirber** [comment]
khmer 3 dropped python 2 support. sourmash still works on 2.7 with khmer 2.1

On March 22, 2019 3:16:24 AM UTC, Natasha Pavlovikj <notifications@github.com> wrote:
>Do you know why the recipe has `python >=3`? "khmer" supports both
>Python 2.7 and Python 3.*, so it should just be `python`.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/bioconda/bioconda-recipes/pull/14142#issuecomment-475479894

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by npavlovikj** [comment]
Good to know, thanks for the update.

**Comment by npavlovikj** [comment]
Looks like "khmer" is still being build for Python 3.6, probably because of `pytest-runner >=2.0,<3dev`.

**Comment by luizirber** [comment]
`pytest-runner` was dropped in latest master, so I tagged 3.0.0a3 and removed it here.

**Pull request merged**
