### PR TITLE
Feature/fix augustus

### PR DESCRIPTION
**Pull request by jerowe**
* [ ] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

I'm refactoring this PR a bit.

https://github.com/bioconda/bioconda-recipes/pull/3283

### CODE REVIEW

**Comment by jerowe** [comment]
@bgruening 

I can't get this compiled for OSX.

https://travis-ci.org/jerowe/bioconda-recipes/jobs/192932444#L448

```
filterBam.cc:31:10: fatal error: 'unordered_map' file not found
```

I'll do a few more, but if no one has objections I will just rebuild.

**Comment by bgruening** [comment]
Rebuild? Just skip OSX for now.

**Comment by jerowe** [comment]
Its rebuilding now. I have to do one more where I clean up my patches.

**Comment by jerowe** [comment]
I've given up on the osx build for now. Merging.

**Pull request merged**
