### PR TITLE
Update r-seurat to 3.0.2

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`r-seurat`](https://bioconda.github.io/recipes/r-seurat/README.html): **3.0.1** &rarr; **3.0.2**

[install with bioconda](http://bioconda.github.io/recipes/r-seurat/README.html) [Conda](https://anaconda.org/bioconda/r-seurat/files)

Info | Link
-----|-----
Recipe | [`recipes/r-seurat`](https://github.com//bioconda/bioconda-recipes/tree/bump/r_seurat/recipes/r-seurat) (click to view/edit other files)
Releases |[https://crandb.r-pkg.org/Seurat/all](https://crandb.r-pkg.org/Seurat/all)

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/updating.html)).

### CODE REVIEW

**Comment by PertuyF** [comment]
Hi @epruesse !
I just saw you added a flag to move this recipe to conda-forge. Did the Bioconda policy changed? Because `seurat` is really very specific to Bioinformatics, so I don't see the rational to move it.

Maybe @bioconda/r can provide input here as well?

**Comment by dlaehnemann** [comment]
Not that I would have any inside knowledge here, but the [R section of the Guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html#r-cran) make the following distinction now:

> Note:
> 
> Most R packages on CRAN should be submitted at Conda-Forge. Specifically, if the CRAN package has a Bioconductor package dependency, it belongs in Bioconda. If the CRAN package does not have a Bioconductor package dependency, it belongs in Conda-Forge.

Thus while seurat is very bioinformatics-specific, it seems like it doesn't have any bioconductor dependencies and thus would belong into conda-forge. To me, that sounds like something that will make dependency-handling within channels easier in the long term...?!

But a more informed @bioconda/r opinion would be useful...

**Comment by PertuyF** [comment]
I guess having a segmentation purely based on dependencies could be defended for the sake of maintenance. But IMO moving a package like `seurat` to conda-forge would really break the spirit of having a conda channel dedicated to Bioinformatics.
Moreover, dependencies can change with every new releases, so will it move back to Bioconda if next version relies on any bioconductor package?

**Comment by bgruening** [comment]
> But IMO moving a package like seurat to conda-forge would really break the spirit of having a conda channel dedicated to Bioinformatics.

We understand this and we agreed actually. But "bioinformatics" is not very well defined and we had problems with this every now and then. In addition entire cran is soon living in conda-forge and Bioconductor is living here. At least for the R world, we think this is a very pragmatic decision and both teams (on conda-forge and bioconductor) are really cool and fast.

**Comment by jdblischak** [comment]
I agree from a maintenance standpoint that it is easier to keep all the CRAN packages on conda-forge. However, I could see how that could easily confuse users. For example, if a newcomer searches the bioconda [Recipe Index](https://bioconda.github.io/conda-recipe_index.html) for some bioinformatics-related R package, they may think it is unavailable (or in the case of Seurat, that it is outdated). Would it be possible to include the conda-forge R packages in the index?

Note that I don't have a strong opinion on this. I just wanted to point out the potential confusion for new users and suggest a solution (and my apologies if this was already discussed elsewhere).

**Comment by bgruening** [comment]
I'm not sure we should advertise the package index for searching and finding :( Multiple packages, like perl-*, biopython or several older ones (more or less all packages that we ever migrated) have the same problem that you described. For findability, we are working on a bigger picture here --> [bio.tools](https://bio.tools/). I hope we have this done by end of this year, so please all annotate your recipes with DOI and/or bio.tools IDs and we can fix the F in FAIR hopefully soon :)

**Comment by bgruening** [comment]
I will merge now to not be a blocker here, but please consider meving this to conda-forge.

**Pull request merged**
