### PR TITLE
unicycler udated version

### PR DESCRIPTION
**Pull request by mictadlo**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by mictadlo** [comment]
Hi @bioconda/core , any idea what I missed?

**Comment by ar0ch** [comment]
Looks like GCC is still being dumb.  Seems like docker container is pulling the correct GCC version (Compiler: unknown 7.2.0) but something else is going wrong

**Comment by mictadlo** [comment]
Hi, has anyone an idea?

**Comment by PertuyF** [comment]
Superseded by #10510

**Pull request closed without merging**
