### PR TITLE
Update phizz to 0.2.3

### PR DESCRIPTION
**Pull request by epruesse**
Update [`phizz`](https://bioconda.github.io/recipes/phizz/README.html): **0.0.1** &rarr; **0.2.3**

[install with bioconda](http://bioconda.github.io/recipes/phizz/README.html) [Conda](https://anaconda.org/bioconda/phizz/files)

Info | Link
-----|-----
Recipe | [`recipes/phizz`](https://github.com//bioconda/bioconda-recipes/tree/bump/phizz/recipes/phizz) (click to view/edit other files)
Releases |[https://pypi.org/pypi/phizz/json](https://pypi.org/pypi/phizz/json)

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/updating.html)).

### CODE REVIEW

**Comment by epruesse** [comment]
@BiocondaBot lint

**Comment by epruesse** [comment]
@biocondabot update

**Comment by dpryan79** [comment]
This requires `interval_tree`.

**Comment by dpryan79** [comment]
https://github.com/conda-forge/staged-recipes/pull/9134

**Pull request merged**
