### PR TITLE
vsnp

### PR DESCRIPTION
**Pull request by stuber**
Changed License in repo.  sha256 updated in meta.yaml.  Builds failing, not sure if missing something in yaml, build script is needed, *.py need to be placed into a bin folder, or my complete packaging scheme needs a overhaul.  Looking for quickest resolution.  Any advice appreciated.

----

> Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences**
      (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

> Everyone has access to the following BiocondaBot commands, which can be given in a comment:
>
>  * `@BiocondaBot please update` will cause the BiocondaBot to merge the master branch into a PR
>  * `@BiocondaBot please add label` will add the `please review & merge` label.
>  * `@BiocondaBot please fetch artifacts` will post links to packages and docker containers built by the CI system. You can use this to test packages locally before merging.
>
> For members of the Bioconda project, the following command is also available:
>
>  * `@BiocondaBot please merge` will cause packages/containers to be uploaded and a PR merged. Someone must approve a PR first! This has the benefit of not wasting CI build time required by manually merging PRs.
>
> If you have questions, please post them in gitter or ping `@bioconda/core` in a comment (if you are not able to directly ping `@bioconda/core` then the bot will repost your comment and enable pinging).

### CODE REVIEW

**Comment by stuber** [comment]
As mentioned above... Builds failing, not sure if missing something in yaml, build script is needed, *.py need to be placed into a bin folder, or my complete packaging scheme needs a overhaul. Looking for quickest resolution. Any advice appreciated.

**Comment by stuber** [comment]
Organized *.py into bin directory, and added a build.sh.  Build still failing.

**Comment by dpryan79** [comment]
You still have a remnant submodule in there. This should be `noarch: generic` and you're not currently installing anything. Adding a `build.sh` with the following will solve that:

````
#!/bin/bash
mkdir -p $PREFIX/bin
mv bin/*.py $PREFIX/bin
```

Note that since you have hardcoded paths to a dependencies file and some sort of oligo database that you'll have to patch around that in the code. I suggest just assuming dependencies are in your path, since on any sanely configured system (e.g., with environment modules or conda) they would be.

**Comment by stuber** [comment]
Will "conda install vsnp" make files in the dependencies directory available to users when vsnp is downloaded from conda with the current build.sh?  vsnp finds supporting files by taking the location of script + ../dependencies/spoligotype_db.txt.  If possible please point me to documentation on how I can rectify this.  Thanks!

**Comment by dpryan79** [comment]
The current install script doesn't installed the `dependencies` directory, so no. If you add `mv dependencies $PREFIX` to the script then it'll be there.

**Comment by stuber** [comment]
Added `mv dependencies $PREFIX`.  Will using (location of script) + ../dependencies/spoligotype_db.txt in vsnp to find spoligotype_db.txt work as a conda install?

**Comment by dpryan79** [comment]
Yes, since you're putting the scripts in `$PREFIX/bin` and the dependencies in `$PREFIX/dependencies`.

**Comment by dpryan79** [comment]
BTW, can you allow edits on your PR? I would have just made the changes for you then.

**Comment by stuber** [comment]
thanks for this.  Help docs say, check "Allow edits from maintainers", but I'm not seeing the option.  When I find it, I'll allow edits.

**Comment by dpryan79** [comment]
It seems to be checked now. I'm currently trying to figure out how to get rid of the submodule remnants, then it can be merged.

**Comment by dpryan79** [comment]
The "Allow edits from maintainers" checkbox should be to the right, around where it says "2 participants".

**Comment by stuber** [comment]
I mostly sure I'm in the right place, but missing option.  I'll keep looking...  thanks,

Screen Shot 2020-01-15 at 9 27 21 AM

**Comment by stuber** [comment]
@BiocondaBot please fetch artifacts

**Comment by stuber** [comment]
@BiocondaBot please fetch artifacts

**Comment by dpryan79** [comment]
If you can run `git rm --cached recipes/vSNP` then this can be merged once the CI tests pass.

**Comment by stuber** [comment]
@BiocondaBot please fetch artifacts

**Comment by stuber** [comment]
Running this fails 
`conda install -c https://90579-42372094-gh.circle-artifacts.com/0/tmp/artifacts/packages vsnp`
"ResolvePackageNotFound".  First raxml was cause, removed it, then pysam came back with same error.  Am I right to think I should be able to sucessfully test with `conda install -c https://90579-42372094-gh.circle-artifacts.com/0/tmp/artifacts/packages vsnp`, and shouldn't attempt a merge before this works?

**Comment by dpryan79** [comment]
Did you already add bioconda and conda-forge to your channel list?

**Comment by stuber** [comment]
I tried adding a channel list to meta.yaml.  Didn’t work, but can this be done?

-from phone
________________________________

**Comment by stuber** [comment]
In past conda thread there was this, but not clear if it worked.
meta.yaml-->
requirements:
  build:
    - python
    - conda-forge::conda_build_test_requirement

This requires specifying the package for each requirement, but if can be added as in .condarc, with a channel priority list, better option.  Any suggestions?

**Comment by dpryan79** [comment]
Channel lists in recipes will be ignored by conda, you need to add them either in your own settings or on the command line. Please see https://bioconda.github.io/user/install.html#set-up-channels

**Comment by stuber** [comment]
@BiocondaBot please fetch artifacts

**Comment by stuber** [comment]
@BiocondaBot please fetch artifacts

**Comment by stuber** [comment]
`git rm --cached recipes/vSNP` has been ran.  Please review and merge.  thanks,

**Comment by dpryan79** [comment]
@bioconda-bot please merge

Thanks @stuber, shall I add you to the bioconda team?

**Comment by stuber** [comment]
> @bioconda-bot please merge
> 
> Thanks @stuber, shall I add you to the bioconda team?

That would be great

**Pull request merged**
