### PR TITLE
add recipe for bio easel

### PR DESCRIPTION
**Pull request by rpetit3**
This PR adds a Perl module for [Bio-Easel](https://github.com/nawrockie/Bio-Easel). I went with `perl-bio-easel` since there is a `Makefile.PL`, although it is not available on CPAN.

I didn't use "imports" (e.g. `Bio::Easel::MSA`) to test because the release version does not match the version in the Perl module file. I've submitted a issue (https://github.com/nawrockie/Bio-Easel/issues/3). The current test scripts import `Bio::Easel::MSA`, but they themselves to not have a help or version feature, and output exit code 1 when printing the usage. To get around that I went with `esl-alidepair.pl 2>&1 | grep "Bio-Easel"`.

If the version mismatch is corrected, I will update future releases to go the `imports` route instead.

This is another one in the path to getting [VADR](https://github.com/ncbi/vadr) into Bioconda

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by rpetit3** [comment]
Successfully tested locally using conda build, haha working through things that pop here

**Comment by rpetit3** [comment]
Testing
```
# Install
mamba create -n test-bio-easel -c https://163562-42372094-gh.circle-artifacts.com/0/tmp/artifacts/packages -c conda-forge -c bioconda pe
rl-bio-easel
... TRUNCATED ...
perl-bio-easel                  0.14  h779adbc_0       163562-42372094-gh.circle-artifacts.com/0/tmp/artifacts/packages/linux-64     533 KB
... TRUNCATED ...
conda activate test-bio-easel

echo $PATH
/home/robert_petit/.local/bin:/home/robert_petit/miniconda3/envs/test-bio-easel/bin:/home/robert_petit/miniconda3/condabin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
```

```
esl-ssplit.pl
Use of uninitialized value in subroutine entry at /home/robert_petit/miniconda3/envs/test-bio-easel/lib/site_perl/5.26.2/x86_64-linux-thread-multi/Bio/Easel/SqFile.pm line 61.
Use of uninitialized value in subroutine entry at /home/robert_petit/miniconda3/envs/test-bio-easel/lib/site_perl/5.26.2/x86_64-linux-thread-multi/Bio/Easel/Random.pm line 59.
# esl-ssplit.pl :: split up an input sequence file into smaller files
# Bio-Easel 0.14 (March 2021)
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Usage: esl-ssplit.pl [OPTIONS] <seqfile to split> <# seqs for each new file (or # new files if -n)>
        OPTIONS:
                -n        : 2nd cmd line arg specifies number of output files, not sequences per output file
                -r        : requires -n, split sequences so roughly same number of residues are in each output file
                -z        : requires -r and -n, randomize sequence order when outputting
                -s <n>    : requires -z, -r and -n, seed random number generator with <n> [1801]
                -v        : be verbose with output to stdout, default is to output nothing to stdout
                -d        : dirty mode: leave temporary files on disk (e.g. .ssi index file)
                -oroot <s>: name output files <s> with integer suffix, default is to use input seq file name
                -odir  <s>: output files go into dir <s>, default is pwd

        EXAMPLES:
                'esl-ssplit.pl input.fa 10':
                        split input.fa into M files with 10 sequences; creates files input.fa.1 .. input.fa.N

                'esl-ssplit.pl -n input.fa 10':
                        split input.fa into 10 files with N sequences; creates files input.fa.1 .. input.fa.10

                'esl-ssplit.pl -n -r input.fa 10':
                        split input.fa into 10 files with roughly same number of residues/nucleotides
                        per file; creates files input.fa.1 .. input.fa.10

                'esl-ssplit.pl -n -r -z input.fa 10':
                        *randomize order of sequences* and split input.fa into 10 files with roughly same
                        number of residues/nucleotides per file; creates files: input.fa.1 .. input.fa.10

        NOTE: unless -z is used, sequences will be output in the order they appear in the input file


esl-ssplit.pl GCF_000292685.faa 200
Use of uninitialized value in subroutine entry at /home/robert_petit/miniconda3/envs/test-bio-easel/lib/site_perl/5.26.2/x86_64-linux-thread-multi/Bio/Easel/SqFile.pm line 61.
Use of uninitialized value in subroutine entry at /home/robert_petit/miniconda3/envs/test-bio-easel/lib/site_perl/5.26.2/x86_64-linux-thread-multi/Bio/Easel/Random.pm line 59.
ls -lha
total 216K
drwxr-xr-x  2 robert_petit robert_petit 4.0K Jul 29 01:28 .
drwxr-xr-x 10 robert_petit robert_petit 4.0K Jul 29 01:25 ..
-rw-r--r--  1 robert_petit robert_petit 102K Jul 29 01:27 GCF_000292685.faa
-rw-r--r--  1 robert_petit robert_petit  82K Jul 29 01:28 GCF_000292685.faa.1
-rw-r--r--  1 robert_petit robert_petit  20K Jul 29 01:28 GCF_000292685.faa.2
```

```
esl-alidepair.pl
Use of uninitialized value in subroutine entry at /home/robert_petit/miniconda3/envs/test-bio-easel/lib/site_perl/5.26.2/x86_64-linux-thread-multi/Bio/Easel/MSA.pm line 62.
# esl-alidpair.pl :: remove consensus basepairs based on alignment posterior probabilities
# Bio-Easel 0.14 (March 2021)
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Usage: esl-alidepair.pl [OPTIONS] <alignment file to work on> <name of output alignment file>
        OPTIONS:
                -a <f>   : change minimum average posterior probability to keep to <f> [df: 0.9]
                -w       : use sequence weights in the alignment file to weight counts [df: do not]
                --nc <f> : ignore PPs, remove consensus basepairs for which > <f> fraction are non-canonical
                --dg <f> : ignore PPs, remove consensus basepairs for which > <f> fraction of seqs are double gaps
```

```
# Test module
perldoc -l Bio::Easel
/home/robert_petit/miniconda3/envs/test-bio-easel/lib/site_perl/5.26.2/x86_64-linux-thread-multi/Bio/Easel.pm

perl -MBio::Easel -e 'use Bio::Easel::MSA; print Bio::Easel::MSA->VERSION;'
Use of uninitialized value in subroutine entry at /home/robert_petit/miniconda3/envs/test-bio-easel/lib/site_perl/5.26.2/x86_64-linux-thread-multi/Bio/Easel/MSA.pm line 62.
``

It's not ready, there's a semi-hard coded path that I'll need to patch.

**Comment by rpetit3** [comment]
Round 2!
```
mamba create -n test-bio-easel2 -c https://163575-42372094-gh.circle-artifacts.com/0/tmp/artifacts/packages -c conda-forge -c bioconda perl-bio-easel
... TRUNCATED ...
perl-bio-easel                  0.14  h779adbc_0       163575-42372094-gh.circle-artifacts.com/0/tmp/artifacts/packages/linux-64       6 MB
... TRUNCATED ...

conda activate test-bio-easel2

env | grep EASEL
BIO_EASEL_SHARE_DIR=/home/robert_petit/miniconda3/envs/test-bio-easel2/share/perl-bio-easel-0.14

echo $PATH
/home/robert_petit/.local/bin:/home/robert_petit/miniconda3/envs/test-bio-easel2/bin:/home/robert_petit/miniconda3/condabin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
```

No Longer have `Use of uninitialized value` warnings
```
esl-ssplit.pl
# esl-ssplit.pl :: split up an input sequence file into smaller files
# Bio-Easel 0.14 (March 2021)
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Usage: esl-ssplit.pl [OPTIONS] <seqfile to split> <# seqs for each new file (or # new files if -n)>
        OPTIONS:
                -n        : 2nd cmd line arg specifies number of output files, not sequences per output file
                -r        : requires -n, split sequences so roughly same number of residues are in each output file
                -z        : requires -r and -n, randomize sequence order when outputting
                -s <n>    : requires -z, -r and -n, seed random number generator with <n> [1801]
                -v        : be verbose with output to stdout, default is to output nothing to stdout
                -d        : dirty mode: leave temporary files on disk (e.g. .ssi index file)
                -oroot <s>: name output files <s> with integer suffix, default is to use input seq file name
                -odir  <s>: output files go into dir <s>, default is pwd

        EXAMPLES:
                'esl-ssplit.pl input.fa 10':
                        split input.fa into M files with 10 sequences; creates files input.fa.1 .. input.fa.N

                'esl-ssplit.pl -n input.fa 10':
                        split input.fa into 10 files with N sequences; creates files input.fa.1 .. input.fa.10

                'esl-ssplit.pl -n -r input.fa 10':
                        split input.fa into 10 files with roughly same number of residues/nucleotides
                        per file; creates files input.fa.1 .. input.fa.10

                'esl-ssplit.pl -n -r -z input.fa 10':
                        *randomize order of sequences* and split input.fa into 10 files with roughly same
                        number of residues/nucleotides per file; creates files: input.fa.1 .. input.fa.10

        NOTE: unless -z is used, sequences will be output in the order they appear in the input file
```

```
esl-alidepair.pl
# esl-alidpair.pl :: remove consensus basepairs based on alignment posterior probabilities
# Bio-Easel 0.14 (March 2021)
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Usage: esl-alidepair.pl [OPTIONS] <alignment file to work on> <name of output alignment file>
        OPTIONS:
                -a <f>   : change minimum average posterior probability to keep to <f> [df: 0.9]
                -w       : use sequence weights in the alignment file to weight counts [df: do not]
                --nc <f> : ignore PPs, remove consensus basepairs for which > <f> fraction are non-canonical
                --dg <f> : ignore PPs, remove consensus basepairs for which > <f> fraction of seqs are double gaps
```

```
# Test module
perldoc -l Bio::Easel
/home/robert_petit/miniconda3/envs/test-bio-easel2/lib/site_perl/5.26.2/x86_64-linux-thread-multi/Bio/Easel.pm

perl -MBio::Easel -e 'use Bio::Easel::MSA; print Bio::Easel::MSA->VERSION . "\n";'
0.01

perl -MBio::Easel -e 'use Bio::Easel::Random; print Bio::Easel::Random->VERSION . "\n";'
0.01

perl -MBio::Easel -e 'use Bio::Easel::SqFile; print Bio::Easel::SqFile->VERSION . "\n";'
0.01
```

I think we are good, although I would like opinions on the `build.sh` and `meta.yml`

**Comment by rpetit3** [comment]
@biocondabot please add label

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Comment by rpetit3** [comment]
Thank you!

**Pull request merged**
