### PR TITLE
change version to 3.6

### PR DESCRIPTION
**Pull request by mgalland**
Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it. Note that if you are not already a member of the bioconda project (meaning that you can't add this label), please ping `@bioconda/core` so that your PR can be reviewed and merged (please note if you'd like to be added to the bioconda project). Please see https://github.com/bioconda/bioconda-recipes/issues/15332 for more details.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by dpryan79** [comment]
Is there a reason you want to roll-back the version?

**Comment by sebastian-luna-valero** [comment]
Hi,

I am trying to help @mgalland 

Reason for getting ShortStack version 3.6 into bioconda:

> I wanted to have a recipe that installs Shortstack 3.6 that has a different way of calculating a phased score for phasiRNA. In the final pipeline I would run both Shortstack 3.6 and 3.8.5 together

I have now pushed changes to fix linting issues.

Best regards,
Sebastian

**Comment by sebastian-luna-valero** [comment]
@BiocondaBot update

**Comment by dpryan79** [comment]
@bioconda-bot please update

**Comment by dpryan79** [comment]
Please make a `3.6` subdirectory and put the 3.6 recipe there.

**Comment by sebastian-luna-valero** [comment]
@bioconda-bot please update

**Comment by sebastian-luna-valero** [comment]
@dpryan79 please review and merge if you think it's ready

**Comment by dpryan79** [comment]
@bioconda-bot please fetch artifacts

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Comment by sebastian-luna-valero** [comment]
Great, many thanks!

**Comment by mgalland** [comment]
Just run `conda search shortstack` and found the two versions! A huge thanks to you @sebastian-luna-valero for this!
All the best
Marc

**Pull request merged**
