### PR TITLE
snpEff-4.1: Switch to openjdk

### PR DESCRIPTION
**Pull request by dfornika**
Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it. Note that if you are not already a member of the bioconda project (meaning that you can't add this label), please ping `@bioconda/core` so that your PR can be reviewed and merged (please note if you'd like to be added to the bioconda project). Please see https://github.com/bioconda/bioconda-recipes/issues/15332 for more details.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [x] This PR does something else (explain below).

Switch from java-jdk to openjdk

### CODE REVIEW

**Comment by dfornika** [comment]
@bioconda-bot rebuild

**Comment by dfornika** [comment]
I noticed that the build for `uvp-2.7.0` tries to pull in both `java-jdk` and `openjdk`, and gives several 'ClobberWarnings' during the build. I think this is the reason it's pulling `java-jdk`.

**Comment by bgruening** [comment]
Thanks @dfornika. It's a little bit surprising that this is still in ... if you have time please feel free to remove all java-jdks from our recipes.

**Comment by dfornika** [comment]
There are just a couple others. I'll do that.

**Pull request merged**
