### PR TITLE
update strling: htslib req

### PR DESCRIPTION
**Pull request by brentp**
expands the htslib version in strling

### CODE REVIEW

**Comment by dpryan79** [comment]
@bioconda-bot please fetch artifacts

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
htslib is a "pinned dependency", meaning packages end up getting built against specific versions of it. At the moment we're building everything against htslib 1.10. A quirk of conda's meta.yaml is that if you specify >=1.10 for htslib, you end up pinning it to 1.11 at the moment, which will then conflict with other packages. I've adjusted the current PR to make it more broadly compatible. When we update the htslib pinning next then there will be a new build of strling for htslib 1.11.

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Comment by brentp** [comment]
Thanks @dpryan79

**Pull request merged**
