### PR TITLE
add cargoport url to bioconductor recipes

### PR DESCRIPTION
**Pull request by daler**
* [ ] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [x] This PR does something else (explain below).

xref #3638 

Newly-created or updated bioconductor recipes will now have up to 3 URLs -- bioconductor, bioaRchive, and galaxy cargo-port.

Still need to add ability to retrofit older packages with cargo-port urls and migrate this to bioconda-utils. But it's working for new recipes.

### CODE REVIEW

**Comment by bgruening** [comment]
@daler thanks for working on it! What do you think about adding this URL no matter what as second or third URL. As soon as we merge this package we will create this tarball on cargo-port and it will be available if we need to rebuild this package.

**Comment by daler** [comment]
Good point, it should always be included.

**Comment by johanneskoester** [comment]
Is this ready for merging?

**Comment by bgruening** [comment]
@daler are you planning to work on this further? I have started the R rebuilds and this would come in handy I guess.

**Comment by daler** [comment]
Sorry, this dropped off the radar. If I remember this was almost ready to go, will look at it tomorrow and merge in recent changes in master.

**Comment by daler** [comment]
@bgruening @johanneskoester this should be a much-improved script. It probably belongs in bioconda-utils though, right?

Anyway, the newest changes are:

- cargoport url is added no matter what, as discussed above
- urls now explicitly include the bioconductor version. This should be WAY more stable.
- can specify a package version and bioconductor version at the command line. I'm now scraping the bioconductor release page to get a list of versions, and added some autodetection which tries older and older bioc versions until the package version is identified. For example the following now works nicely, identifying the most recent bioc release for `tximport==1.0.3` as 3.3 and adjusts the url accordingly: `scripts/bioconductor/bioconductor_skeleton.py tximport --force --pkg-version 1.0.3`

- an option for building the recipe in a versioned subdirectory for easer archiving of older recipes
- copied over the nice colored log output Johannes had added to bioconda-utils

**Comment by bgruening** [comment]
Awesome! Thanks a lot! This will make migrations so much easier in a long run!

**Pull request merged**
