### PR TITLE
Adding new recipe for Wise2

### PR DESCRIPTION
**Pull request by r78v10a07**
Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it. Note that if you are not already a member of the bioconda project (meaning that you can't add this label), please ping `@bioconda/core` so that your PR can be reviewed and merged (please note if you'd like to be added to the bioconda project). Please see https://github.com/bioconda/bioconda-recipes/issues/15332 for more details.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by r78v10a07** [comment]
The test in OS is not working.

/bin/sh: pkg-config: command not found

and

fatal error: ar: can't find or exec: /Users/distiller/project/miniconda/conda-bld/wise2_1568747353805/work/_buildchain/x86_64-apple-darwin13.4.0-ranlib (No such file or directory)

Can anyone help, please?

**Comment by r78v10a07** [comment]
The new error in OS is related to `ar` and `ranlib`:

```
12:41:59 BIOCONDA INFO (ERR) fatal error: ar: can't find or exec: /Users/distiller/project/miniconda/conda-bld/wise2_1568749168528/work/_buildchain/x86_64-apple-darwin13.4.0-ranlib (No such file or directory)
12:41:59 BIOCONDA INFO (ERR) ar: internal ranlib command failed
```

Any suggestion?

**Comment by dpryan79** [comment]
I have a feeling the `ar` command is simply missing an option on OSX.

**Comment by r78v10a07** [comment]
I've tested in my Mac. If I remove the link to ar then the test success.

[wise_with_bioconda_ar.log](https://github.com/bioconda/bioconda-recipes/files/3637519/wise_with_bioconda_ar.log)
[wise.log](https://github.com/bioconda/bioconda-recipes/files/3637520/wise.log)

**Comment by r78v10a07** [comment]
Wow! It just passed removing the AR symlink.

**Pull request merged**
