### PR TITLE
Update edd to 1.1.19

### PR DESCRIPTION
**Pull request by epruesse**
Update [`edd`](https://bioconda.github.io/recipes/edd/README.html): **1.1.18** &rarr; **1.1.19**

[install with bioconda](http://bioconda.github.io/recipes/edd/README.html) [Conda](https://anaconda.org/bioconda/edd/files)

Info | Link
-----|-----
Recipe | [`recipes/edd`](https://github.com//bioconda/bioconda-recipes/tree/bump/edd/recipes/edd) (click to view/edit other files)
Releases |[https://pypi.org/pypi/edd/json](https://pypi.org/pypi/edd/json)

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by epruesse** [comment]
`pysam versions from 0.10.0 up to and including 0.11.2.2.`

**Comment by epruesse** [comment]
@biocpndabot lint

**Comment by epruesse** [comment]
@biocondabot lint

**Comment by epruesse** [comment]
@biocondabot update

**Comment by dpryan79** [comment]
We need to rebuild some old pysam versions, which require old samtools/htslib versions.

**Pull request closed without merging**
