### PR TITLE
Update negative_training_sampler to 0.3.1

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`negative_training_sampler`](https://bioconda.github.io/recipes/negative_training_sampler/README.html): **0.3.0** &rarr; **0.3.1**

[install with bioconda](http://bioconda.github.io/recipes/negative_training_sampler/README.html) [Conda](https://anaconda.org/bioconda/negative_training_sampler/files)

Info | Link
-----|-----
Recipe | [`recipes/negative_training_sampler`](https://github.com//bioconda/bioconda-recipes/tree/bump/negative_training_sampler/recipes/negative_training_sampler) (click to view/edit other files)
Releases |[https://github.com/kircherlab/negative_training_sampler/tags](https://github.com/kircherlab/negative_training_sampler/tags)
Author | `@kircherlab`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by standage** [comment]
@bioconda-bot please fetch artifacts

**Comment by standage** [comment]
I get the following message when I try to print the usage statement.

```
(TEST1) $ negative_training_sampler --help
Traceback (most recent call last):
  File "/home/standage/anaconda3/envs/TEST1/bin/negative_training_sampler", line 7, in <module>
    from negative_training_sampler.__main__ import main
  File "/home/standage/anaconda3/envs/TEST1/lib/python3.6/site-packages/negative_training_sampler/__main__.py", line 5, in <module>
    from negative_training_sampler  import cli
  File "/home/standage/anaconda3/envs/TEST1/lib/python3.6/site-packages/negative_training_sampler/cli.py", line 5, in <module>
    from negative_training_sampler.negative_training_balancer import balance_trainingdata
  File "/home/standage/anaconda3/envs/TEST1/lib/python3.6/site-packages/negative_training_sampler/negative_training_balancer.py", line 9, in <module>
    from negative_training_sampler.bed_gc_calculator import get_gc
  File "/home/standage/anaconda3/envs/TEST1/lib/python3.6/site-packages/negative_training_sampler/bed_gc_calculator.py", line 6, in <module>
    import pybedtools
  File "/home/standage/anaconda3/envs/TEST1/lib/python3.6/site-packages/pybedtools/__init__.py", line 18, in <module>
    from . import contrib
  File "/home/standage/anaconda3/envs/TEST1/lib/python3.6/site-packages/pybedtools/contrib/__init__.py", line 3, in <module>
    from . import venn_maker
  File "/home/standage/anaconda3/envs/TEST1/lib/python3.6/site-packages/pybedtools/contrib/venn_maker.py", line 12, in <module>
    from pybedtools import helpers
  File "/home/standage/anaconda3/envs/TEST1/lib/python3.6/site-packages/pybedtools/helpers.py", line 13, in <module>
    import pysam
  File "/home/standage/anaconda3/envs/TEST1/lib/python3.6/site-packages/pysam/__init__.py", line 5, in <module>
    from pysam.libchtslib import *
ImportError: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
```

I installed the package in a clean environment using the command suggested above.

**Comment by dpryan79** [comment]
@standage The conda solver is probably giving you an old pysam version, we can just restrict the version in the recipe to prevent that.

**Comment by standage** [comment]
@bioconda-bot please fetch artifacts

**Comment by standage** [comment]
@dpryan79 Pinning to `pysam >= 0.15` seems to have worked!

**Comment by standage** [comment]
@bioconda-bot please merge

**Pull request merged**
