### PR TITLE
Update beav to v1.3.0

### PR DESCRIPTION
**Pull request by acarafat**
This is a major updated version of beav.

Change log:

- New wrapper program, beav_circos, which can be independently used to generate a Circos plot from a GenBank file without running the beav pipeline.
- Automated integration test pipeline, beav_test, which runs beav on a test file and check if expected output are generated.
- We have added a failure check following the Bakta analysis such that the pipeline will report an error and not continue if this step fails to produce the correct output.
- We have also added additional checks in the beav and beav_db programs to ensure that environment variables (BEAV_DIR) are correctly set.
- Beav now can be run with a pre-existing GenBank format annotated genome as input rather than a fasta file. In this case, Beav will skip the Bakta step and will run the other stages of the pipeline to add annotations to this input file.
- We also added the detection of dif/KOPS/MatS sites to the beav script.
- Few other bugs regarding running perl scripts and Circos plot generation have been fixed.

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

### General instructions

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

### Instructions for avoiding API, ABI, and CLI breakage issues
Conda is able to record and lock (a.k.a. pin) dependency versions used at build time of other recipes.
This way, one can avoid that expectations of a downstream recipe with regards to API, ABI, or CLI are violated by later changes in the recipe.
If not already present in the meta.yaml, make sure to specify `run_exports` (see [here](https://bioconda.github.io/contributor/linting.html#missing-run-exports) for the rationale and comprehensive explanation).
Add a `run_exports` section like this:

```yaml
build:
  run_exports:
    - ...

```

with `...` being one of:

| Case                             | run_exports statement                                               |
| -------------------------------- | ------------------------------------------------------------------- |
| semantic versioning              | `{{ pin_subpackage("myrecipe", max_pin="x") }}`     |
| semantic versioning (0.x.x)      | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}`   |
| known breakage in minor versions | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| known breakage in patch versions | `{{ pin_subpackage("myrecipe", max_pin="x.x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| calendar versioning              | `{{ pin_subpackage("myrecipe", max_pin=None) }}`    |

while replacing `"myrecipe"` with either `name` if a `name|lower` variable is defined in your recipe or with the lowercase name of the package in quotes.

### Bot commands for PR management

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

Note that the <code>@BiocondaBot please merge</code> command is now depreciated. Please just squash and merge instead.

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by acarafat** [comment]
For some reason, the automatic CI test fails all the time due to a connection timeout issue. However, we have tested the build locally, and it works fine. Thereby we are requesting to merge it.

@BiocondaBot please add label

**Comment by acarafat** [comment]
@BiocondaBot please update

**Comment by alexweisberg** [comment]
@BiocondaBot please add label

**Comment by alexweisberg** [comment]
We've test built this package locally and it works, this seems to be an issue with the Azure CI build system.

**Review by mencian — APPROVED** [review]

**Comment by mbargull** [comment]
> We've test built this package locally and it works, this seems to be an issue with the Azure CI build system.

FYI, I can't certainly say what changed -- I've updated multiple bits and pieces.
The most likely component that made it stall previously might've been the the outdated `conda` version in `quay.io/bioconda/create-env:3.0` that didn't use `conda-libmamba-solver` by default -- I simply missed to update that container image when changing everything else to use `conda`+`conda-libmamba-solver` instead of `mamba` last month...

**Comment by alexweisberg** [comment]
Excellent, thank you for fixing it!

From: Marcel Bargull ***@***.***>
Date: Monday, June 3, 2024 at 1:09 AM
To: bioconda/bioconda-recipes ***@***.***>
Cc: Alexandra Weisberg ***@***.***>, Comment ***@***.***>
Subject: Re: [bioconda/bioconda-recipes] Update beav to v1.3.0 (PR #47999)

We've test built this package locally and it works, this seems to be an issue with the Azure CI build system.

FYI, I can't certainly say what changed -- I've updated multiple bits and pieces.
The most likely component that made it stall previously might've been the the outdated conda version in quay.io/bioconda/create-env:3.0 that didn't use conda-libmamba-solver by default -- I simply missed to update that container image when changing everything else to use conda+conda-libmamba-solver instead of mamba last month...

**Pull request merged**
