### PR TITLE
Update segway recipe to version 2.0.5

### PR DESCRIPTION
**Pull request by EricR86**
Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it. Note that if you are not already a member of the bioconda project (meaning that you can't add this label), please ping `@bioconda/core` so that your PR can be reviewed and merged (please note if you'd like to be added to the bioconda project). Please see https://github.com/bioconda/bioconda-recipes/issues/15332 for more details.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [ ] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by epruesse** [comment]
Could you have a look at the `about:` section and fix the missing license file?

**Comment by peterjc** [comment]
I've not checked the tar-ball from PyPI, but at least in the source repository they do not seem to include a copy of the GPL v2 license:

https://bitbucket.org/hoffmanlab/segway/src/default/

I've logged an issue for that:

https://bitbucket.org/hoffmanlab/segway/issues/135/missing-copy-of-gpl-v2-license

I can't recall if it is BioConda or conda-forge which recommend bundling a copy via the receipe repository when it is missing upstream...

**Comment by peterjc** [comment]
My mistake, the file is there - called ``LICENSE`` (no extension), so all you need is to add ``license_file: LICENSE`` under the ``about:`` section.

**Comment by EricR86** [comment]
Done. Thanks!

**Pull request merged**
