### PR TITLE
Dashing

### PR DESCRIPTION
**Pull request by SilasK**
Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it. Note that if you are not already a member of the bioconda project (meaning that you can't add this label), please ping `@bioconda/core` so that your PR can be reviewed and merged (please note if you'd like to be added to the bioconda project). Please see https://github.com/bioconda/bioconda-recipes/issues/15332 for more details.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by SilasK** [comment]
@dnbaker here we go, probably it won't pass the checks in the first time

**Comment by dnbaker** [comment]
Thanks! I don't full understand how bioconda works, but I'll try installing via conda on my personal machine in the interim.

**Comment by dnbaker** [comment]
https://github.com/dnbaker/bioconda-recipes/tree/dash

I have some changes, including requiring libomp. But it breaks when I try to install it, for what seems to be a fundamental compiler issue:

```
ld: warning: ignoring file /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib/libSystem.tbd, file was built for unsupported file format ( 0x2D 0x2D 0x2D 0x20 0x21 0x74 0x61 0x70 0x69 0x2D 0x74 0x62 0x64 0x2D 0x76 0x33 ) which is not the architecture being linked (x86_64): /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib/libSystem.tbd
Undefined symbols for architecture x86_64:
  "___bzero", referenced from:
      _deflateReset in libz.a(deflate.o)
      _deflateSetDictionary in libz.a(deflate.o)
      _fill_window in libz.a(deflate.o)
      _deflateParams in libz.a(deflate.o)
      _deflate in libz.a(deflate.o)
      _gz_write in libz.a(gzwrite.o)
      _gzputc in libz.a(gzwrite.o)
      ...
  "___sprintf_chk", referenced from:
      _gzdopen in libz.a(gzlib.o)
  "___stack_chk_fail", referenced from:
      _test_compress in example.o
      _test_gzio in example.o
      _test_deflate in example.o
      _test_inflate in example.o
      _test_large_deflate in example.o
      _test_large_inflate in example.o
      _test_flush in example.o
      ...
  "___stack_chk_guard", referenced from:
      _test_compress in example.o
      _test_gzio in example.o
      _test_deflate in example.o
      _test_inflate in example.o
      _test_large_deflate in example.o
      _test_large_inflate in example.o
      _test_flush in example.o
      ...
  "___stderrp", referenced from:
      _test_compress in example.o
      _test_gzio in example.o
      _test_deflate in example.o
      _test_inflate in example.o
      _test_large_deflate in example.o
      _test_large_inflate in example.o
      _test_flush in example.o
      ...
  "___strcat_chk", referenced from:
      _gz_error in libz.a(gzlib.o)
  "___vsprintf_chk", referenced from:
      _gzvprintf in libz.a(gzwrite.o)
  "_calloc", referenced from:
      _main in example.o
  "_close", referenced from:
      _gzclose_r in libz.a(gzread.o)
      _gzclose_w in libz.a(gzwrite.o)
  "_exit", referenced from:
      _test_compress in example.o
      _test_gzio in example.o
      _test_deflate in example.o
      _test_inflate in example.o
      _test_large_deflate in example.o
      _test_large_inflate in example.o
      _test_flush in example.o
      ...
  "_fprintf", referenced from:
      _test_compress in example.o
      _test_gzio in example.o
      _test_deflate in example.o
      _test_inflate in example.o
      _test_large_deflate in example.o
      _test_large_inflate in example.o
      _test_flush in example.o
      ...
  "_free", referenced from:
      _main in example.o
      _gz_open in libz.a(gzlib.o)
      _gzdopen in libz.a(gzlib.o)
      _gzrewind in libz.a(gzlib.o)
      _gzseek64 in libz.a(gzlib.o)
      _gz_error in libz.a(gzlib.o)
      _gzclearerr in libz.a(gzlib.o)
      ...
  "_fwrite", referenced from:
      _test_compress in example.o
      _test_gzio in example.o
      _test_inflate in example.o
      _test_large_deflate in example.o
      _test_sync in example.o
      _test_dict_deflate in example.o
      _test_dict_inflate in example.o
      ...
  "_lseek", referenced from:
      _gz_open in libz.a(gzlib.o)
      _gzrewind in libz.a(gzlib.o)
      _gzseek64 in libz.a(gzlib.o)
      _gzoffset64 in libz.a(gzlib.o)
      _gzoffset in libz.a(gzlib.o)
  "_malloc", referenced from:
      _gz_open in libz.a(gzlib.o)
      _gzdopen in libz.a(gzlib.o)
      _gz_error in libz.a(gzlib.o)
      _gz_look in libz.a(gzread.o)
      _gz_init in libz.a(gzwrite.o)
      _zcalloc in libz.a(zutil.o)
  "_memchr", referenced from:
      _gzgets in libz.a(gzread.o)
  "_memcpy", referenced from:
      _fill_window in libz.a(deflate.o)
      _deflateGetDictionary in libz.a(deflate.o)
      _deflate in libz.a(deflate.o)
      _deflate_stored in libz.a(deflate.o)
      _deflateCopy in libz.a(deflate.o)
      _deflate_fast in libz.a(deflate.o)
      _deflate_slow in libz.a(deflate.o)
      ...
  "_open", referenced from:
      _gz_open in libz.a(gzlib.o)
  "_printf", referenced from:
      _test_compress in example.o
      _test_gzio in example.o
      _test_inflate in example.o
      _test_sync in example.o
      _test_dict_inflate in example.o
      _main in example.o
  "_puts", referenced from:
      _test_large_inflate in example.o
      _main in example.o
  "_read", referenced from:
      _gz_read in libz.a(gzread.o)
      _gz_fetch in libz.a(gzread.o)
      _gz_look in libz.a(gzread.o)
      _gz_decomp in libz.a(gzread.o)
  "_strcmp", referenced from:
      _test_compress in example.o
      _test_gzio in example.o
      _test_inflate in example.o
      _test_dict_inflate in example.o
      _main in example.o
  "_strcpy", referenced from:
      _gz_open in libz.a(gzlib.o)
      _gz_error in libz.a(gzlib.o)
  "_strlen", referenced from:
      _test_compress in example.o
      _test_gzio in example.o
      _test_deflate in example.o
      _test_flush in example.o
      _test_dict_deflate in example.o
      _gz_open in libz.a(gzlib.o)
      _gz_error in libz.a(gzlib.o)
      ...
  "_write", referenced from:
      _gz_comp in libz.a(gzwrite.o)

```

Maybe my libSystem is too new or too old?

**Comment by SilasK** [comment]
@dnbaker Sorry I didn't used your fork. I'm working from https://github.com/bioconda/bioconda-recipes/tree/dash 

Do you want to call the tool 'dash' or 'dashing' ? 
There iexist already a plotly/dash .

**Comment by SilasK** [comment]
Do you have a list of requirements for the building process? 
- You were talking about omplib and  libSystem?
- They should have new compilers, as I understand it.

**Comment by SilasK** [comment]
Relevant section from the docs: https://bioconda.github.io/contributor/guidelines.html#c-c

**Comment by dnbaker** [comment]
The biggest issue here is that bioconda seems to want to use clang on OSX, but it doesn't come with omp baked in. (In the README, I recommend building with g++.) But I'm hoping that requiring libomp somehow helps.

There may have been an issue with clang compatibility in 0.3.6, so I've patched that and bumped to 0.4.0. I'll work on this today, but that's what I've been trying to figure out.

**Comment by dnbaker** [comment]
https://github.com/dnbaker/bioconda-recipes/commit/696c9ebbf97b5a776c503e69df30e326340df52b

I've made changes; a number of these dependencies only exist on github. I've used git as a package manager previously. I believe this will cause it to build, unless the omp problem remains. (I would definitely have preferred a recursive clone, as all modules would be loaded with correct versions already), but I've added releases to a variety of these. I'll test later, but I wanted to report on these changes.

**Comment by dnbaker** [comment]
The current bug I'm experiencing is here: https://github.com/ContinuumIO/anaconda-issues/issues/9096

But perhaps I should be testing on linux instead.

**Comment by SilasK** [comment]
# release instead of git

Ideally the submodules should be included in the release, but this is not yet the [case on github](https://github.community/t5/How-to-use-Git-and-GitHub/Create-Release-that-contains-submodule/m-p/12073#M3934).

# build on linux
We can always skip the osx build for now and get it out on linux. 

I merged your commits #18856 

They are tested automatically on linux. 
see 
https://app.circleci.com/jobs/github/bioconda/bioconda-recipes/83603

**Comment by SilasK** [comment]
Head over to #18857

**Comment by SilasK** [comment]
circle ci fails on linux with `gcc: Command not found`

**Comment by dnbaker** [comment]
Maybe try adding ` {{ compiler('c') }}`? gcc is needed for zlib, whereas the rest of the codebase needs g++.

**Comment by dpryan79** [comment]
This build on Linux now.

**Comment by SilasK** [comment]
Do you know a way to get the g++ 5 on macOS ? 

Should we just skip the osx build ?

**Comment by dpryan79** [comment]
GCC isn't used on OSX, so if you require that rather than clang you'll need to skip OSX.

**Comment by SilasK** [comment]
If I [see](https://app.circleci.com/jobs/github/bioconda/bioconda-recipes/84452) it correctly it passes the compilation macOS. But then the tests `dashing --help` doesn't work.

**Comment by dpryan79** [comment]
@bioconda-bot please fetch artifacts

**Comment by dpryan79** [comment]
I think the problem is that it both compiles in libzstd.a but also links to it with -lzstd. GCC seems to ignore libzstd.so, but clang appears not to.

**Comment by dpryan79** [comment]
That fixed it

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Pull request merged**
