### PR TITLE
Maker 3.01.03 update

### PR DESCRIPTION
**Pull request by nathanweeks**
(NOTE: resubmitting https://github.com/bioconda/bioconda-recipes/pull/26414 to attempt to work around CircleCI glitch)

This PR updates MAKER to 3.01.03. Includes new evidencemodeler and repsearch dependencies.

Note that I attempted to trim the meta.yaml "host" section per my understanding of the minimum of what's needed to be there for build.sh to work; please fix if incorrect or unconventional.

### CODE REVIEW

**Comment by nathanweeks** [comment]
@BiocondaBot please fetch artifacts

**Review by bgruening — APPROVED** [review]
Pretty cool @nathanweeks!

**Comment by nathanweeks** [comment]
There appears to be a race condition when multiple MAKER instances (e.g., using MPI) execute  with repeat masking enabled; specifically, when RepeatMasker 4.1.1 builds the general and species library caches. I've identified a potential workaround, and may push an additional commit. I have contacted the MAKER developer for advice/feedback.

**Comment by nathanweeks** [comment]
@BiocondaBot please fetch artifacts

**Comment by nathanweeks** [comment]
@bernt-matthias : would you care to review this for compatibility with Galaxy? There are some minor differences in the existing control files, as well as an additional control file for EVidenceModeler (maker_evm.ctl)

**Review by bernt-matthias — APPROVED** [review]
> review this for compatibility with Galaxy?

Actually I do not have any experience with this tool. So its hard to say something about this.

But if you like you can also create and test a Galaxy tool for this version: https://planemo.readthedocs.io/en/latest/writing_how_do_i.html#test-tools-against-a-package-or-container-in-a-bioconda-pull-request

But we can also merge and test later. However you prefer. I will just agree with @bgruening and approve this PR. Then you can merge whenever you like.

> There are some minor differences in the existing control files, as well as an additional control file for EVidenceModeler (maker_evm.ctl)

This sound like it can be handled in the Galaxy tool.

**Comment by nathanweeks** [comment]
@bernt-matthias: I unfortunatley don't have experience creating Galaxy tools. As I've done some cursory testing on an HPC cluster, I'll go ahead an merge now. As long as the MAKER Galaxy tool is pinned to a compatible MAKER version, someone can update this recipe later for Galaxy compatibility if need be when updating the Galaxy tool.

**Comment by nathanweeks** [comment]
@BiocondaBot merge

**Comment by nathanweeks** [comment]
@bioconda-bot please merge

**Comment by nathanweeks** [comment]
Hmm, the PR comment responder didn't like something:

https://github.com/bioconda/bioconda-recipes/runs/1864590244

I'll try again in a few.

**Comment by nathanweeks** [comment]
@bioconda-bot please merge

**Pull request merged**
