### PR TITLE
Update sepp build.sh to fix config file

### PR DESCRIPTION
**Pull request by dpear**
instead of generating a config file with certain paths, copy the default config file then change all paths.

Describe your pull request here

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

### General instructions

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

### Instructions for avoiding API, ABI, and CLI breakage issues
Conda is able to record and lock (a.k.a. pin) dependency versions used at build time of other recipes.
This way, one can avoid that expectations of a downstream recipe with regards to API, ABI, or CLI are violated by later changes in the recipe.
If not already present in the meta.yaml, make sure to specify `run_exports` (see [here](https://bioconda.github.io/contributor/linting.html#missing-run-exports) for the rationale and comprehensive explanation).
Add a `run_exports` section like this:

```yaml
build:
  run_exports:
    - ...

```

with `...` being one of:

| Case                             | run_exports statement                                               |
| -------------------------------- | ------------------------------------------------------------------- |
| semantic versioning              | `{{ pin_subpackage("myrecipe", max_pin="x") }}`     |
| semantic versioning (0.x.x)      | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}`   |
| known breakage in minor versions | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| known breakage in patch versions | `{{ pin_subpackage("myrecipe", max_pin="x.x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| calendar versioning              | `{{ pin_subpackage("myrecipe", max_pin=None) }}`    |

while replacing `"myrecipe"` with either `name` if a `name|lower` variable is defined in your recipe or with the lowercase name of the package in quotes.

### Bot commands for PR management

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

Note that the <code>@BiocondaBot please merge</code> command is now depreciated. Please just squash and merge instead.

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by wasade** [comment]
Hi @sjanssen2, when you have a moment, could you review this? Briefly: the UPP config is coming out empty (at least in our Q2 environments)

**Comment by sjanssen2** [comment]
Hi @wasade and @dpear 
not sure if I understand your problem correctly. When I came up with this recipe, I "only" intended to build SEPP properly, i.e. never tested UPP execution. Could you therefore provide a minimal test case?
What exactly do you mean by "empty"? Downloading https://anaconda.org/bioconda/sepp/4.5.1/download/linux-64/sepp-4.5.1-py37h9ee0642_3.tar.bz2 lists a `main.config` and a `upp.config` with non zero byte size in subdir `/share/sepp/sepp`:
image

However, the contained paths don't look correct
image

**Comment by sjanssen2** [comment]
aha, the latest qiime2-amplicon pins SEPP to version 4.3.10: https://raw.githubusercontent.com/qiime2/distributions/dev/2023.9/amplicon/released/qiime2-amplicon-ubuntu-latest-conda.yml (line 625: `- sepp=4.3.10`) and in fact, this older package https://anaconda.org/bioconda/sepp/4.3.10/download/linux-64/sepp-4.3.10-py38h3252c3a_2.tar.bz2 does not contain the `upp.config`

**Comment by sjanssen2** [comment]
I am trying to come up with a "subrecipe" which might update the outdated 4.3.10, see #44540

**Comment by wasade** [comment]
Thanks!

**Comment by sjanssen2** [comment]
I think we can close this PR now, as two others have already been merged. Please double check, if upp.config is distributed as expected

**Pull request closed without merging**
