### PR TITLE
Update macrel to v.1.2.0

### PR DESCRIPTION
**Pull request by celiosantosjr**
Update the macrel recipe to meet the v.1.2.0.

Changes:
    - Eliminate prodigal compilation
    - Add pyrodigal to software dependencies

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by celiosantosjr** [comment]
Reviewer: @luispedro

**Comment by luispedro** [comment]
I think you don't need `make` and `c-compiler` anymore

What is the standard to install python packages on bioconda? You might not need a separate `build.sh` either

**Comment by celiosantosjr** [comment]
@BiocondaBot please fetch artifacts

**Comment by celiosantosjr** [comment]
@BiocondaBot please review & merge

**Comment by luispedro** [comment]
@BiocondaBot please fetch artifacts

**Comment by luispedro** [comment]
@celiosantosjr can you test the new packages locally once the bot puts them up and report here whether they work for you

**Comment by celiosantosjr** [comment]
@luispedro the package instalation is working well, we can merge it

**Pull request merged**
