### PR TITLE
Update bedtools to 2.31.0

### PR DESCRIPTION
**Pull request by jmarshall**
Update checksum (again) to reflect the re-released upstream tarball. Remove `run` dependencies, which will be detected automatically.

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by jmarshall** [comment]
Ugh, this time the upstream tarball is full of AppleDouble files, which have again foiled the tarball content hoisting:

```
2023-05-04T23:54:48.2071461Z 23:54:37 [32mBIOCONDA INFO[0m (OUT) .
2023-05-04T23:54:48.2072063Z 23:54:37 [32mBIOCONDA INFO[0m (OUT) ..
2023-05-04T23:54:48.2072381Z 23:54:37 [32mBIOCONDA INFO[0m (OUT) ._bedtools2    # <--
2023-05-04T23:54:48.2072613Z 23:54:37 [32mBIOCONDA INFO[0m (OUT) bedtools2
```

So it may need to be regenerated once again.

**Comment by jmarshall** [comment]
@BiocondaBot please fetch artifacts

**Comment by jmarshall** [comment]
Not only might the AppleDouble droppings issue be fixed in future bedtools release tarballs, but it has different effects on Linux and macOS: on macOS the extra files do not prevent conda-build's hoisting behaviour. Thus the `Hoisting prevented` message appears in the Linux build log but not the macOS build log.

Hence with the current upstream tarball (which upstream has not yet regenerated again, so we may wish to work around the problem), the `cd bedtools2` is required on Linux and required not to be done on macOS — so the `if` condition is required.

**Comment by jmarshall** [comment]
What is the @bioconda/core policy on stripping executables?

Bedtools is a C++ executable. In the macOS build, `bedtools` is 2.2 MB and after stripping is 1.6 MB. In the Linux build, `bedtools` is 50 MB and after stripping drops to 2 MB.

This has been the case for a while: see the [Anaconda bedtools file listing](https://anaconda.org/bioconda/bedtools/files) in which Linux packages are ~15 MB while macOS ones are ~1 MB. So Linux downloads and installations are arguably unnecessarily bloated.

In fact, it appears to have started with bedtools 2.28 — so perhaps there is a _Makefile_ setting that changed then that we can change back.

**Comment by jmarshall** [comment]
@BiocondaBot please fetch artifacts

**Review by bgruening — APPROVED** [review]
Thanks @jmarshall!

**Comment by dpryan79** [comment]
Regarding stripping executables, there's no real policy there. We kind of assume there's a good reason that debug information is included if it's in there so we generally don't strip it out.

**Pull request merged**
