### PR TITLE
add pggb (PanGenome Graph Builder)

### PR DESCRIPTION
**Pull request by AndreaGuarracino**

### CODE REVIEW

**Comment by rpetit3** [comment]
@AndreaGuarracino did you mean to add changes to the `GFAffix` recipe as well?

**Comment by AndreaGuarracino** [comment]
Hi @rpetit3, thanks for asking.
No, I am not a developer of `GFAffix`, but we need that tool in `pggb`. The `GFAffix` recipe has been updated automatically (https://github.com/bioconda/bioconda-recipes/pull/30941), so it's strange to see that it doesn't work. But I could also update it if needed, should I?

**Comment by AndreaGuarracino** [comment]
I tried, but it is still failing. @danydoerr, it is again the problem with the `clap` crate. Would you please release a new version, so we can update the `GFAffix` conda package?

**Comment by rpetit3** [comment]
I think it might be best to create a new PR without any changes to `recipes/gfaffix/meta.yaml`

The recipe for `pggb` looked fine to me.

If you create a new PR ping me and I'll keep an eye on it.

**Comment by AndreaGuarracino** [comment]
Okay, sorry if I mixed things up. As soon as `GFAffix` is ready, I will open another PR. Thank you for the support.

**Comment by rpetit3** [comment]
GFFAffix should be good to go, go ahead and make a new PR with your recipe (I'm excited to get this one into Bioconda! thanks for submitting this!)

**Pull request closed without merging**
