### PR TITLE
Removal of MiXCR due to License conflict

### PR DESCRIPTION
**Pull request by PoslavskySV**
MiLaboratory LLC develops MiXCR software and holds exclusive rights on its distribution. Anaconda Inc is a for-profit entity and its distribution policies of MiXCR are in conflict with MiXCR License, for two reasons.
 
First, the МiXCR License prohibits any redistribution of MiXCR except for non-commercial and non-profit use. Anaconda Inc stores MiXCR on its Amazon S3 account and has no control over the intent of end use.
 
Second, Anaconda Inc does not enforce the MiXCR users to agreeing with MiXCR License terms on Anaconda platform. Moreover, MiXCR License agreement is not accessible from https://anaconda.org/bioconda/mixcr. 

Please accept this PR as soon as possible. Please remove all previously stored binary files with MiXCR distribution from Anaconda Inc S3 cloud.

Thank you for your understanding.
 
Sincerely,
Stanislav Poslavsky

On behalf of MiLaboratory LLC and MiXCR development team

### CODE REVIEW

**Comment by dpryan79** [comment]
I can certainly fix the license inclusion, which was an oversight. Please note that this isn't distributed by Anaconda Inc., but rather by Bioconda, which isn't for profit (we're academics), so strictly speaking this isn't violating the license. So while we can certainly delete all of the packages, you might consider whether this is something you really want to do, since you likely have more users via Bioconda than anything else.

**Comment by PoslavskySV** [comment]
Hi Devon,

thank you for prompt reply! We of course understand that Bioconda is an academic community. However, Bioconda artifacts, including MiXCR, are uploaded to Anaconda owned artifact repository, stored in Anaconda Inc S3 bucket. This way MiXCR is redistributed from a third party entrerprise servers. There is no control who will use it. Moreover, Anaconda repostory is not open sourced, and we can't deploy our own repo, hosted on our servers. In contrast, Homebrew, for example, allows this, and there is an official Homebrew formula for MiXCR (`milaboratory/all/mixcr`).

We already faced a situation, when a commercial company was using MiXCR without licensing, just because they thought that what is available in Bioconda is free.

We kindly ask you to remove already uploaded binaries from Anaconda's repository at https://anaconda.org/bioconda/mixcr. 

MiXCR is and always will be free for academic users.

With best wishes,
Stanislav

**Comment by dpryan79** [comment]
Very well, I've deleted all mixcr packages from the conda cloud.

**Comment by bgruening** [comment]
> Moreover, Anaconda repostory is not open sourced, and we can't deploy our own repo, hosted on our servers. In contrast, Homebrew, for example, allows this, and there is an official Homebrew formula for MiXCR (milaboratory/all/mixcr).

This is not true, you can host your own conda channel if you like.

> MiXCR is and always will be free for academic users.

Which does not help academic users at all! We (academic users) are obviously not allowed to distribute it and make it accessible to other academic users. Keep in mind that Bioconda is just the first step in an entire chain. What you are saying is that we should stop distributing workflows, wrappers, containers that bundle this software, is that correct?

This hurts reproducibility and tracebility :(

**Comment by PoslavskySV** [comment]
Hi, thank you for your feedback!

We absolutely agree on the importance of reproducibility and traceability. And we know how hard it is to make really reproducible pipelines (from raw data to final results) for scientific publications (see e.g. our efforts in this paper https://www.nature.com/articles/nbt.3979, where we provide Docker image to reproduce the results).

We invest a lot of efforts to make this possible. For that, we provide official optimized Docker image for MiXCR, available directly from Docker Hub (https://hub.docker.com/r/milaboratory/mixcr), an installation links available from GitHub (https://github.com/milaboratory/mixcr/releases), and an official Homebrew formula (milaboratory/all/mixcr). With these instruments, there is no need to redistribute MiXCR binaries to create reproducible pipelines.

Anyway, we also understand the importance of simplicity, and that each user has own preferrable package manager. We are currently working with our legals under a solution, which will allow redistribution of  MiXCR by third-party entities. Once we finish this, it will be possible to redistribute MiXCR binaries through packet managers like conda.

**Comment by bgruening** [comment]
@PoslavskySV is there any update on this issue?

We just had another user which complains about broken pipelines.

(Docker is not a solution to many users and HPC environments)

**Comment by PoslavskySV** [comment]
Hi,

Yes, we have agreed with our legals how it will be possible to re-distribute our software. We are now on road with implementing licensing infrastructure which allows painless re-distribution of MiXCR, including free version for academics. This will take additional time: we plan to finish this before July.

**Comment by bgruening** [comment]
@PoslavskySV thanks. Would this allow bioconda and others to redistribute the package?

**Comment by PoslavskySV** [comment]
Yes, exactly, it will allow to put MiXCR back in bioconda.

**Comment by bgruening** [comment]
Cool, thanks.

**Comment by PoslavskySV** [comment]
Just an update: we are on road on finishing licensing infrastructure that will allow to redistribute MiXCR in package managers including bioconda. We plan to finish in late July - we'll let you know as soon as we finish.

**Comment by PoslavskySV** [comment]
@dpryan79 @bgruening 

Dear colleagues, 

we have updated our license terms and implemented licensing infrastructure. We will be happy to add MiXCR back to Bioconda. MiXCR is free for academic users with no commercial funding. We are committed to support academic community and provide our software free of charge for scientists doing non-profit research.

Note that to run MiXCR one need to enter a license key. Academic users can automatically and quickly get a free license at https://licensing.milaboratories.com/. Here are [the instructions](https://github.com/milaboratory/mixcr/wiki/Using-license) how to activate the license. For users running MiXCR with Docker the easiest way will be to specify the license with env 
```
docker run --env MI_LICENSE_FILE="..."
```

Do you think the best way to add MiXCR back is to reopen https://github.com/bioconda/bioconda-recipes/pull/25138  ?

Best,
Stan

**Comment by bernt-matthias** [comment]
@PoslavskySV 

> Do you think the best way to add MiXCR back is to reopen https://github.com/bioconda/bioconda-recipes/pull/25138 ?

As far as I know bioconda only accepts software that has a proper open source license (GPL, MIT, Apache, ...). 

Please note that I also suggested to deprecate the tool in the IUC Galaxy tools repo. Feel free to join the discussion there https://github.com/galaxyproject/tools-iuc/pull/4756.

**Comment by bgruening** [comment]
Just as information: The lawyers behind that software tried to sue people that distributed the software and contacted the university legal departments.

**Pull request merged**
