### PR TITLE
Preserve the original JAR filename: clinod-1.3.jar

### PR DESCRIPTION
**Pull request by peterjc**
* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [X] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

The original recipe accidentally used the Galaxy cache's filename ``clinod_1.3_src_all.jar`` rather than the original filename, ``clinod-1.3.jar``.

This restores the original JAR filename.

### CODE REVIEW

**Comment by bgruening** [comment]
But the old was also working? Do we need a new package for that or is this is cosmetic?

**Comment by peterjc** [comment]
This broke my first attempt at updating my Galaxy wrapper to use clinod when installed via BioConda, so I figure it might break other wrapper code which looks for the JAR by name.

**Comment by bgruening** [comment]
fair enough, also I think accessing the jar file dynamically is quite hard :)

**Comment by peterjc** [comment]
Yes - this is one reason why I quite like the BioConda policy to provide a wrapper for Java tools which are released just as a JAR file.

**Pull request merged**
