### PR TITLE
quast 5.0.0

### PR DESCRIPTION
**Pull request by alexeigurevich**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by tseemann** [comment]
```
WARNING (quast,lib/python2.7/site-packages/quast_libs/sambamba/sambamba_osx): did not find - or even know where to look for: /usr/lib/libSystem.B.dylib
WARNING (quast,lib/python2.7/site-packages/quast_libs/glimmer/glimmerhmm): Needed DSO lib/libstdc++.so.6 found in ['libstdcxx-ng']
WARNING (quast,lib/python2.7/site-packages/quast_libs/glimmer/glimmerhmm): .. but ['libstdcxx-ng'] not in reqs/run, i.e. it is overlinked (likely) or a missing dependency (less likely)
   INFO (quast,lib/python2.7/site-packages/quast_libs/glimmer/glimmerhmm): Needed DSO lib/libgcc_s.so.1 found in defaults::libgcc-ng-7.2.0-hdf63c60_3
WARNING (quast,lib/python2.7/site-packages/quast_libs/glimmer/glimmerhmm): did not find - or even know where to look for: /lib64/libc.so.6
WARNING (quast,lib/python2.7/site-packages/quast_libs/glimmer/glimmerhmm): did not find - or even know where to look for: /lib64/libm.so.6
WARNING (quast,lib/python2.7/site-packages/quast_libs/barrnap/binaries/darwin/nhmmer): did not find - or even know where to look for: /usr/lib/libSystem.B.dylib
   INFO (quast,lib/python2.7/site-packages/quast_libs/busco/hmmsearch): Needed DSO lib/libgcc_s.so.1 found in defaults::libgcc-ng-7.2.0-hdf63c60_3
WARNING (quast,lib/python2.7/site-packages/quast_libs/busco/hmmsearch): did not find - or even know where to look for: /lib64/libdl.so.2
WARNING (quast,lib/python2.7/site-packages/quast_libs/busco/hmmsearch): did not find - or even know where to look for: /lib64/libpthread.so.0
WARNING (quast,lib/python2.7/site-packages/quast_libs/busco/hmmsearch): did not find - or even know where to look for: /lib64/libc.so.6
WARNING (quast,lib/python2.7/site-packages/quast_libs/busco/hmmsearch): did not find - or even know where to look for: /lib64/libm.so.6
WARNING (quast,lib/python2.7/site-packages/quast_libs/sambamba/sambamba_linux): did not find - or even know where to look for: /lib64/libpthread.so.0
WARNING (quast,lib/python2.7/site-packages/quast_libs/sambamba/sambamba_linux): did not find - or even know where to look for: /lib64/libc.so.6
WARNING (quast,lib/python2.7/site-packages/quast_libs/sambamba/sambamba_linux): did not find - or even know where to look for: /lib64/libm.so.6
WARNING (quast,lib/python2.7/site-packages/quast_libs/sambamba/sambamba_linux): did not find - or even know where to look for: /lib64/ld-linux-x86-64.so.2
   INFO (quast,lib/python2.7/site-packages/quast_libs/sambamba/sambamba_linux): Needed DSO lib/libgcc_s.so.1 found in defaults::libgcc-ng-7.2.0-hdf63c60_3
WARNING (quast,lib/python2.7/site-packages/quast_libs/sambamba/sambamba_linux): did not find - or even know where to look for: /lib64/librt.so.1
WARNING (quast,lib/python2.7/site-packages/quast_libs/barrnap/binaries/linux/nhmmer): did not find - or even know where to look for: /lib64/libdl.so.2
WARNING (quast,lib/python2.7/site-packages/quast_libs/barrnap/binaries/linux/nhmmer): did not find - or even know where to look for: /lib64/libpthread.so.0
WARNING (quast,lib/python2.7/site-packages/quast_libs/barrnap/binaries/linux/nhmmer): did not find - or even know where to look for: /lib64/libc.so.6
WARNING (quast,lib/python2.7/site-packages/quast_libs/barrnap/binaries/linux/nhmmer): did not find - or even know where to look for: /lib64/libm.so.6
   INFO (quast,lib/python2.7/site-packages/quast_libs/barrnap/binaries/linux/nhmmer): Needed DSO lib/libgcc_s.so.1 found in defaults::libgcc-ng-7.2.0-hdf63c60_3
```

**Comment by alexeigurevich** [comment]
Thanks @tseemann! The most critical one is  `ERROR! Compilation of contig aligner software was unsuccessful!`, we will try to figure out what is wrong. I suppose that I failed to properly specify either `zlib` dependency or a proper C compiler which are needed for `minimap2` compilation.

**Comment by alexeigurevich** [comment]
Hi! 
Almost everything is fine except for GlimmerHMM running time failure on MacOS. I suggest that the issue is probably in:
> WARNING (quast,lib/python2.7/site-packages/quast_libs/glimmer/glimmerhmm): Needed DSO /usr/lib/libc++.1.dylib not found in any CDT/compiler package, nor the whitelist?!
But I don't know how to fix it. Glimmer is compiled during the package installation and there is no error messages, so it seems that it was properly compiled.

It would be great if I can connect to https://circleci.com/gh/bioconda/bioconda-recipes/22211 via SSH and debug there. Is it possible? Currently `Rerun job with SSH` button is disabled for me since I don't have write permission to trigger builds.

**Comment by alexeigurevich** [comment]
Finally, we applied a few patches to disable embedded glimmer and use glimmerHMM from bioconda recipes. Now everything seems working, so I will merge the recipe.

**Comment by almahmoud** [comment]
Really interested to know if you figured out what exactly was causing the `Minimap2` compilation error @alexeigurevich, cause it's back...
It started passing after this commit: https://github.com/bioconda/bioconda-recipes/pull/10357/commits/3277bab07f264ab5e4e7bd655c18efe3c923cb00 but the only thing I could think of making it work in there is `export C_INCLUDE_PATH=$PREFIX/include` which is still in the recipe... Any leads would be appreciated

**Comment by mbargull** [comment]
@almahmoud: I believe the issue is that Minimap2's does not use `LDFLAGS`. However, we could circumvent that issue in gh-23218 by depending on `minimap2` instead of using the included one.

**Pull request merged**
