### PR TITLE
Rebuild perl-inline-c

### PR DESCRIPTION
**Pull request by druvus**
:information_source:
Bioconda has finished the [GCC7 migration](https://github.com/bioconda/bioconda-recipes/issues/13578). If you are dealing with C/C++ or Python package it can be that you need to rebuild other dependent packages. [Bioconda utils - update-pinning](https://bioconda.github.io/updating.html#updating-recipes-for-a-pinning-change) will assist you with that. If you have any questions please use [issue 13578](https://github.com/bioconda/bioconda-recipes/issues/13578).

----------------

* [ ] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [ ] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by druvus** [comment]
Similar issue as in #13166

**Comment by npavlovikj** [comment]
Any updates on this? I tried the suggestions from Devon and Elmar (https://github.com/bioconda/bioconda-recipes/issues/12755 and https://github.com/conda-forge/perl-feedstock/issues/29), but the issue with this package still persists...

**Comment by abretaud** [comment]
@druvus I took the liberty to rebase this PR to see if the perl update fixed the problem
There's still this error that I don't (yet) understand, does it evoke anything to you? Maybe playing with the CC env var could fix it

`Error: bin/gcc is a symlink to a path that may not exist after the build is completed (/opt/conda/conda-bld/perl-inline-c_1555503777870/_build_env/bin/x86_64-conda_cos6-linux-gnu-gcc)`

**Comment by druvus** [comment]
thanks @abretaud for fixing it!

**Pull request merged**
