### PR TITLE
Homer, Software for motif discovery and next-gen sequencing analysis

### PR DESCRIPTION
**Pull request by BioNinja**
* [x] I have read the guidelines above.
* [x] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

add Homer,
Software for motif discovery and next-gen sequencing analysis

### CODE REVIEW

**Comment by percyfal** [comment]
@BioNinja @bioconda/core This pull request looks very similar to the one I submitted a year ago and that we then decided to leave out due to issues with the build script; see PR #344, in particular the comments. I just wanted to point this out as I think the current build script should be improved. I don't recall all the details right now as this was some time ago.

**Comment by daler** [comment]
@BioNinja @percyfal agreed, I think this recipe at least needs tests to see if `findMotifs.pl` works after running `configureHomer.pl`.

Did you ever work out whether using `sed` on all the scripts after they're processed by `configureHomer.pl`?

**Comment by BioNinja** [comment]
It's the same recipe with @percyfal，I've test findMotifs.pl,it looks find for me on oxs, if this does not work for others, I think we should remove for now，sorry for the mistakes，@daler

**Comment by BioNinja** [comment]
I don't know why conda build works for homer now

**Comment by percyfal** [comment]
It's not that it didn't work - it's that the build doesn't actually include the scripts, just the install script, which then is called the first time any homer program is called. Alternatively, one could run the install script during the build, use sed to modify the paths and only include the homer scripts themselves (if I recall correctly, homer downloads large database files which would make the package prohibitively large).

**Comment by percyfal** [comment]
@BioNinja no worries, I had a look at your recipe as I was curious as to how you solved my initial issues :-D

**Comment by daler** [comment]
No worries @BioNinja. When you say findMotifs.pl works on OSX, do you mean before or after running configureHomer.pl?

@percyfal do you know if the databases required for all tools? And is there an alternative method to download them?  If databases are not required, then one option would be to, in `build.sh`,

- allow configureHomer.pl to do its thing
- fix the paths when it's done
- delete the databases it downloaded
- provide an extra script, say, download_homer_database.pl, for downloading them later to the installed path or ideally to some user-defined path

This latter part might not be directly supported by Homer, but perhaps you could fix the scripts to use an environment variable like HOMER_DATABASES that is set by download_homer_database.pl.

**Comment by BioNinja** [comment]
I've test findMotifs.pl after running configureHomer.pl. And it will copy all homer scripts to .../mininconda/bin directory. But I have to download homer database mannally. for example configureHomer.pl -install hg19. @daler

**Comment by daler** [comment]
OK that's good to know. Can you try running configureHomer.pl within the build.sh script and see how it goes? Ideally a user should be able to download a package and start using it immediately rather than do a separate install step.

**Pull request merged**
