### PR TITLE
mob_suite version update to 3.1.2. Numpy version restriction 

### PR DESCRIPTION
**Pull request by kbessonov1984**
Update the mob_suite tool to version 3.1.2. Restricted the upper bound for the numpy version <1.23.5 to avoid the 'bool' data type warning as a temporary fix

### CODE REVIEW

**Comment by apetkau** [comment]
@kbessonov1984 this looks great to me. I was helping out @jrober84 with this as well, but looks like you beat us to it 😛 . If this looks good to both of you I can review/approve it.

**Comment by kbessonov1984** [comment]
@apetkau  yes, it looks good to me and passes the CI tests. The PR is fully based on the James' edits of the `meta.yaml` to restrict the numpy version (numpy >=1.11.1,<1.23.5) and match to pandas version restriction <=1.0.5. Looks like newer numpy versions >=1.24.0 completely got rid of `np.bool` type and replaced it with `bool` (see https://stackoverflow.com/questions/74893742/how-to-solve-attributeerror-module-numpy-has-no-attribute-bool). I think it is a good solution for the time being and in the future will need to restrict both `pandas` and `numpy` version ranges. I vote for approval, no issues on my end.

**Review by apetkau — APPROVED** [review]
Awesome. Looks great to me.

**Comment by apetkau** [comment]
@BiocondaBot please merge

**Comment by apetkau** [comment]
@BiocondaBot fetch artifacts

**Comment by apetkau** [comment]
@BiocondaBot please fetch artifacts

**Comment by rpetit3** [comment]
@BiocondaBot please fetch artifacts

**Comment by apetkau** [comment]
Thanks so much @rpetit3 :)

**Pull request merged**
