### PR TITLE
bump sourmash

### PR DESCRIPTION
**Pull request by luizirber**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by luizirber** [comment]
Hello,

any recommendations on how to debug the `failed_tests` error during linting? https://travis-ci.org/bioconda/bioconda-recipes/jobs/289613773#L801

**Comment by bgruening** [comment]
@luizirber next to the error is a link to our documentation. Please look here for more information: https://bioconda.github.io/linting.html#setup-py-install-args

**Comment by luizirber** [comment]
@bgruening cool, I think that fixed the problem! Thanks!

**Comment by bgruening** [comment]
Thanks @luizirber and @druvus!

**Pull request merged**
