### PR TITLE
Kat 2.3.4

### PR DESCRIPTION
**Pull request by jerowe**
* [ ] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

New version of kat - 2.3.4

### CODE REVIEW

**Comment by jerowe** [comment]
@bioconda/core - 

I keep getting an error about an unbound 'GITHUB_TOKEN' var.

https://travis-ci.org/bioconda/bioconda-recipes/jobs/236846388#L514

I haven't been keeping up with the cool new build system as I clearly should be. ;-)

**Comment by jerowe** [comment]
@bioconda/core - I am trying to update kat and I am having trouble.

It all seems to build fine - but when I run `kat --version` 

```
kat: error while loading shared libraries: libpython3.5m.so.1.0: cannot open shared object file: No such file or directory
```
But I can run ldd on the kat executable and it looks fine.

**Comment by jerowe** [comment]
Now its complaining about python2.

```
_placehold_placehold_placehold_placehold_placeh/bin/python
configure: Found python version: 2.7.13
checking for a version of Python >= '3.1.0'... no
configure: error: in `/opt/conda/conda-bld/recipe_1496069129196/work/KAT-Release-2.3.4':
```

According to the github page it should build with python2, but has a preference towards python 3.

**Comment by bgruening** [comment]
I feel your pain, let me know if you need help.

**Comment by jerowe** [comment]
Thanks. ;-) I can get it to build locally, so at this point its just button pushing.

How can I skip both python and osx ?

skip: True # [osx] [py26] ?

**Comment by bgruening** [comment]
`skip: True # [osx or py2k] ` should do the trick

**Comment by jerowe** [comment]
Thanks. ;-) I will give it one more try for the osx build, and then I will give up.

**Comment by bgruening** [comment]
@jerowe it's green!

**Comment by jerowe** [comment]
YAY!

**Pull request merged**
