### PR TITLE
Added perl-statistics-r

### PR DESCRIPTION
**Pull request by jfallmann**
* [x] I have read the guidelines above.
* [x] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by jfallmann** [comment]
@bgruening This was not supposed to happen, freshly forked master, new branch, added only perl-statistics-r recipe but travis is still building 9 recipes with the same failing than before?
ensembl-vep seems to be the problem, but this comes from the bioconda-recipes/master branch
What have I done .....

**Comment by bgruening** [comment]
Restarted :)

**Comment by jfallmann** [comment]
@bgruening  Linux done, osx is skipped for now, but returns error with other package

iltering 1047 of 2020 (51.8%) recipes/perl-sanger-cgp-vagrent                         ----------------------------------------------------------------------

Unable to parse meta.yaml file

Error Message:

--> while parsing a block mapping

-->   in "<unicode string>", line 20, column 5

--> did not find expected key

-->   in "<unicode string>", line 21, column 5

/Users/travis/build.sh: line 151:  2551 Terminated: 15

**Comment by bgruening** [comment]
The skip command was in the wrong section, and because this command is only valid on OSX, only OSX was failing. I corrected it. Let's see what happens.

**Pull request merged**
