### PR TITLE
add ramclustr package

### PR DESCRIPTION
**Pull request by martenson**
This PR depends on https://github.com/bioconda/bioconda-recipes/pull/25267.

Generated using CRAN skeleton with `--allow-archived`.

The original cran repo was removed and only an archive is available: https://cran.r-project.org/web/packages/RAMClustR/index.html. I asked the ramclustr authors about their future intentions with CRAN here: https://github.com/cbroeckl/RAMClustR/issues/16

For now this packages version 1.0.9 - the last one available on cran. In github 1.1.0 already exists.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by martenson** [comment]
@BiocondaBot please rebuild

**Comment by martenson** [comment]
@BiocondaBot please update

**Comment by dpryan79** [comment]
I suspect someone would need to rebuild an old version of r-ff on conda-forge for this to work. The error message (and probably why it got pulled from CRAN) is due to the package not supporting either of the recent versions of `ff`.

**Comment by dpryan79** [comment]
Guess someone rebuilt r-ff <4 for R 4.0 already. That's convenient.

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Comment by martenson** [comment]
Thanks @dpryan79! Was that you with the `ff` package? :D

**Pull request merged**
