### PR TITLE
Pin tqdm to recent version

### PR DESCRIPTION
**Pull request by pinin4fjords**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

I had issues with the EGA client installed via Bioconda due to outdated tqdm (error very much like https://github.com/pypa/twine/issues/385).

Suggesting this PR as a fix, requiring recent tqdm- pinging recipe author @AlexanderVi for approval.

### CODE REVIEW

**Comment by pinin4fjords** [comment]
Thanks @bgruening

**Comment by AlexanderVi** [comment]
@pinin4fjords - please update version number ( the latest is 3.0.28 )

**Comment by pinin4fjords** [comment]
@AlexanderVi that might be something for a separate PR. This is a bugfix to the current recipe's dependencies so that the Bioconda package works as it should. 

I need to deal with the linting issue, but are you okay in principle with the tqdm tweak?

**Comment by AlexanderVi** [comment]
> I need to deal with the linting issue, but are you okay in principle with the tqdm tweak?
@pinin4fjords - I'm fine with tqdm tweak (assuming you have tested it and it does not break anything)
Will approve once the linting issue is gone

**Comment by pinin4fjords** [comment]
@AlexanderVi for some reason I can't request your review. But I'm taking your above comments as approval and will merge. The package didn't work _without_ upgrading this dependency, so be assured that this PR doesn't break anything - in my environment at least.

**Pull request merged**
