### PR TITLE
build files

### PR DESCRIPTION
**Pull request by stuber**
Describe your pull request here

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Review by stuber — COMMENTED** [review]
newline added to end of file

**Comment by stuber** [comment]
Need 1 approving review.  Please review and comment.

**Comment by stuber** [comment]
@BiocondaBot please add label

**Comment by dpryan79** [comment]
Looks like the conda solver is blowing up the memory usage when solving the run-time environment. To debug why, start commenting things in the "run:" section out until it starts solving the environment correctly and then start restricting the verions of the dependencies so it has a smaller number of possible environment solutions to consider.

**Review by stuber — COMMENTED** [review]
trying requirement with >=3.7

**Comment by stuber** [comment]
Changing python requirement from >=3.6 to >=3.7 was enough to pass.  If you see fit, please approve.

Question on channel priority.  Can I specify priority in meta.yml, or does one have to specify when doing the `conda install`?  What is recommended?

**Comment by stuber** [comment]
@BiocondaBot please add label

**Comment by stuber** [comment]
Making a small change to repo.  Need to update sha256.  Will be ready again shortly.

**Comment by stuber** [comment]
Making a small change to repo.  Need to update sha256.  Will be ready again shortly.

**Comment by stuber** [comment]
Making a small change to repo.  Need to update sha256.  Will be ready again shortly.

**Review by stuber — COMMENTED** [review]
updated sha256

**Review by stuber — COMMENTED** [review]
specified channels

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@stuber Looks good, merge at your leisure

**Pull request merged**
