### PR TITLE
add getopt

### PR DESCRIPTION
**Pull request by bgruening**
* [ ] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by notestaff** [comment]
@bgruening 
What does it mean that the CRON job failed, even after the normal travis-ci tests passed and the pull request was successfully merged?  I'm seeing the same thing with my last commit, and it also seems to have happened with other commits.  Is it ok to ignore the CRON error?

**Comment by bgruening** [comment]
Which cron error? Can you give me a link?

**Comment by notestaff** [comment]
I'm re-running it now,  at
https://travis-ci.org/bioconda/bioconda-recipes/builds/232734919
but it already seems to take more time than normal.  The CRON error was that it timed out, not that the tests failed.  The pull request I merged is
https://github.com/bioconda/bioconda-recipes/pull/4701

**Comment by bgruening** [comment]
but I see your package here: https://anaconda.org/bioconda/gap2seq and here https://quay.io/repository/biocontainers/gap2seq?tab=tags so everything seems to be fine. The cron job just runs to pick up packages that we missed for some reason and is just a safeguard atm. Do you miss any packages?

**Comment by notestaff** [comment]
No, I'm able to install them and they work, I just wanted to understand if
the CRON error indicates there's some problem.  Sounds like it doesn't.

**Pull request merged**
