### PR TITLE
add `wgatools`

### PR DESCRIPTION
**Pull request by AndreaGuarracino**

### CODE REVIEW

**Comment by AndreaGuarracino** [comment]
@BiocondaBot please fetch artifacts

**Review by mencian — APPROVED** [review]

**Comment by aliciaaevans** [comment]
@BiocondaBot please fetch artifacts

**Comment by aliciaaevans** [comment]
(I'm trying to figure out why the nightly build thinks this should be rebuilt.)

**Comment by aliciaaevans** [comment]
For some reason, the files from before and after @mencian's changes both ended up in OSXArtifacts.zip and both got uploaded when this PR was merged. Now the nightly build is complaining because the older one exists. I opened https://github.com/bioconda/bioconda-recipes/pull/47711 to bump build number to resolve it for this recipe. Maybe I can come up with a test PR to illustrate the problem.

**Pull request merged**
