### PR TITLE
Fix up htslib package's prerequisites

### PR DESCRIPTION
**Pull request by jmarshall**
The htslib package depends on just _libcurl_ rather than all of _curl_; and the package's _hfile_s3.so/.bundle_ plugin is the sole part of the entire htslib/samtools/bcftools conglomerate that uses libcrypto/openssl (and it does so on Linux only).

Also move the tests to _meta.yaml_ and delete _run_test.sh_. At least on my bioconda-utils / conda-build local installation, the presence of _run_test.sh_ means that any tests within _meta.yaml_ (namely the is-libdeflate-actually-there check) are skipped.

The maintainers might consider not merging this until _bioconda_utils/bioconda_utils-conda_build_config.yaml_'s libdeflate pinning has been updated from 1.0 to 1.3…

----

Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it. Note that if you are not already a member of the bioconda project (meaning that you can't add this label), please ping `@bioconda/core` so that your PR can be reviewed and merged (please note if you'd like to be added to the bioconda project). Please see https://github.com/bioconda/bioconda-recipes/issues/15332 for more details.

* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [ ] This PR adds a new recipe.
* [X] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [X] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by jmarshall** [comment]
The mulled build has failed on CircleCI:

    SERR [bgzip] No such file or directory: test1.bed

It would appear that the data file listed in _meta.yaml_ (`test: files: - test1.bed`) has not been copied into the docker image in the right place. @bioconda/core: Any advice?

**Comment by dpryan79** [comment]
@jmarshall Thanks, I'll hold off a bit on merging this until the libdeflate pinning is updated (I'll be back in the office in about a week and will see to that then). You're correct that `run_test.sh` masks the tests in the meta.yaml, though since neither it nor anything from the recipe environment are copied into the container (the cause of the error in your last message) for the "mulled test" the tests in the meta.yaml end up getting run there (I would really like to change this).

**Comment by jmarshall** [comment]
Is there a reason why this (and seemingly libdeflate pinning) is still languishing?

It seems a shame to ship htslib-1.10 with a bumped soversion but still with the janky libdeflate.so on macOS…

**Comment by dpryan79** [comment]
libdeflate was already taken care of for recent 1.9 builds (and thus also 1.10). The remainder fell off my radar.

**Comment by dpryan79** [comment]
@bioconda-bot please update

**Comment by dpryan79** [comment]
Thanks @jmarshall

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Pull request merged**
