### PR TITLE
caper: update to v0.8.2.1 and add dependencies

### PR DESCRIPTION
**Pull request by leepc12**
Describe your pull request here

Update dependencies for Caper.

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by leepc12** [comment]
How can I re-run failed tests?
https://app.circleci.com/pipelines/github/bioconda/bioconda-recipes/24088/workflows/dc96305c-a31a-44e7-9668-64e77810ed14/jobs/103995

This looks like a temporary network problem on Conda repo?
```
20:34:04 BIOCONDA INFO (OUT) The following NEW packages will be INSTALLED:
20:34:04 BIOCONDA INFO (OUT) 
20:34:04 BIOCONDA INFO (OUT)     _libgcc_mutex:    0.1-conda_forge           conda-forge
20:34:04 BIOCONDA INFO (OUT)     _openmp_mutex:    4.5-0_gnu                 conda-forge
20:34:04 BIOCONDA INFO (OUT)     ca-certificates:  2020.4.5.1-hecc5488_0     conda-forge
20:34:04 BIOCONDA INFO (OUT)     certifi:          2020.4.5.1-py38h32f6830_0 conda-forge
20:34:04 BIOCONDA INFO (OUT)     ld_impl_linux-64: 2.34-h53a641e_0           conda-forge
20:34:04 BIOCONDA INFO (OUT)     libffi:           3.2.1-he1b5a44_1007       conda-forge
20:34:04 BIOCONDA INFO (OUT)     libgcc-ng:        9.2.0-h24d8f2e_2          conda-forge
20:34:04 BIOCONDA INFO (OUT)     libgomp:          9.2.0-h24d8f2e_2          conda-forge
20:34:04 BIOCONDA INFO (OUT)     libstdcxx-ng:     9.2.0-hdf63c60_2          conda-forge
20:34:04 BIOCONDA INFO (OUT)     ncurses:          6.1-hf484d3e_1002         conda-forge
20:34:04 BIOCONDA INFO (OUT)     openssl:          1.1.1f-h516909a_0         conda-forge
20:34:04 BIOCONDA INFO (OUT)     pip:              20.0.2-py_2               conda-forge
20:34:04 BIOCONDA INFO (OUT)     python:           3.8.2-h8356626_5_cpython  conda-forge
20:34:04 BIOCONDA INFO (OUT)     python_abi:       3.8-1_cp38                conda-forge
20:34:04 BIOCONDA INFO (OUT)     readline:         8.0-hf8c457e_0            conda-forge
20:34:04 BIOCONDA INFO (OUT)     setuptools:       46.1.3-py38h32f6830_0     conda-forge
20:34:04 BIOCONDA INFO (OUT)     sqlite:           3.30.1-hcee41ef_0         conda-forge
20:34:04 BIOCONDA INFO (OUT)     tk:               8.6.10-hed695b0_0         conda-forge
20:34:04 BIOCONDA INFO (OUT)     wheel:            0.34.2-py_1               conda-forge
20:34:04 BIOCONDA INFO (OUT)     xz:               5.2.5-h516909a_0          conda-forge
20:34:04 BIOCONDA INFO (OUT)     zlib:             1.2.11-h516909a_1006      conda-forge
20:34:04 BIOCONDA INFO (OUT) 
20:34:09 BIOCONDA INFO (OUT) Traceback (most recent call last):
20:34:09 BIOCONDA INFO (OUT)   File "/opt/conda/bin/conda-build", line 11, in <module>
20:34:09 BIOCONDA INFO (OUT)     sys.exit(main())
20:34:09 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 474, in main
20:34:09 BIOCONDA INFO (OUT)     execute(sys.argv[1:])
20:34:09 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 465, in execute
20:34:09 BIOCONDA INFO (OUT)     verify=args.verify, variants=args.variants)
20:34:09 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.7/site-packages/conda_build/api.py", line 209, in build
20:34:09 BIOCONDA INFO (OUT)     notest=notest, need_source_download=need_source_download, variants=variants)
20:34:09 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.7/site-packages/conda_build/build.py", line 2863, in build_tree
20:34:09 BIOCONDA INFO (OUT)     notest=notest,
20:34:09 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.7/site-packages/conda_build/build.py", line 1910, in build
20:34:09 BIOCONDA INFO (OUT)     create_build_envs(top_level_pkg, notest)
20:34:09 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.7/site-packages/conda_build/build.py", line 1750, in create_build_envs
20:34:09 BIOCONDA INFO (OUT)     is_conda=m.name() == 'conda')
20:34:09 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.7/site-packages/conda_build/environ.py", line 875, in create_env
20:34:09 BIOCONDA INFO (OUT)     execute_actions(actions, index)
20:34:09 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
20:34:09 BIOCONDA INFO (OUT)     return f(*args, **kwds)
20:34:09 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.7/site-packages/conda/plan.py", line 320, in execute_actions
20:34:09 BIOCONDA INFO (OUT)     execute_instructions(plan, index, verbose)
20:34:09 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.7/site-packages/conda/plan.py", line 532, in execute_instructions
20:34:09 BIOCONDA INFO (OUT)     cmd(state, arg)
20:34:09 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.7/site-packages/conda/instructions.py", line 67, in PROGRESSIVEFETCHEXTRACT_CMD
20:34:09 BIOCONDA INFO (OUT)     progressive_fetch_extract.execute()
20:34:09 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.7/site-packages/conda/core/package_cache_data.py", line 620, in execute
20:34:09 BIOCONDA INFO (OUT)     raise CondaMultiError(exceptions)
20:34:09 BIOCONDA INFO (OUT) conda.CondaMultiError: ('Connection broken: OSError("(104, \'ECONNRESET\')")', OSError("(104, 'ECONNRESET')"))
20:34:09 BIOCONDA INFO (OUT) 
20:34:11 BIOCONDA ERROR COMMAND FAILED (exited with 1): docker run -t --net host --rm -v /tmp/tmp3l0a8pq7/build_script.bash:/opt/build_script.bash -v /home/circleci/project/miniconda/conda-bld/:/opt/host-conda-bld -v /home/circleci/project/recipes/caper:/opt/recipe -e LANG=en_US.UTF-8 -e HOST_USER_ID=1001 bioconda/bioconda-utils-build-env:latest /bin/bash /opt/build_script.bash
```

**Comment by leepc12** [comment]
I got this error.
```
19:05:50 BIOCONDA INFO (OUT) conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-64: {"autouri[version='>=0.1.2.1']", "pyhocon[version='>=0.3.53']"}
19:05:53 BIOCONDA ERROR COMMAND FAILED (exited with 1): docker run -t --net host --rm -v /tmp/tmpi5ew6em5/build_script.bash:/opt/build_script.bash -v /home/circleci/project/miniconda/conda-bld/:/opt/host-conda-bld -v /home/circleci/project/recipes/caper:/opt/recipe -e LANG=en_US.UTF-8 -e HOST_USER_ID=1001 bioconda/bioconda-utils-build-env:latest /bin/bash /opt/build_script.bash
```

It seems like `pyhocon`>=0.3.53 does not exist on `bioconda` or `conda-forge`. There was a critical bug fix for this package in 0.3.53.
```
$ conda search pyhocon -c conda-forge -c bioconda
Loading channels: done
# Name                       Version           Build  Channel
pyhocon                       0.3.30          py27_0  conda-forge
pyhocon                       0.3.30          py34_0  conda-forge
pyhocon                       0.3.30          py35_0  conda-forge
pyhocon                       0.3.35            py_0  conda-forge
pyhocon                       0.3.38            py_0  conda-forge
pyhocon                       0.3.42            py_0  conda-forge
pyhocon                       0.3.43            py_0  conda-forge
pyhocon                       0.3.44            py_0  conda-forge
pyhocon                       0.3.45            py_0  conda-forge
pyhocon                       0.3.46            py_0  conda-forge
pyhocon                       0.3.47            py_0  conda-forge
pyhocon                       0.3.48            py_0  conda-forge
pyhocon                       0.3.49            py_0  conda-forge
pyhocon                       0.3.50            py_0  conda-forge
pyhocon                       0.3.51            py_0  conda-forge
```

Also, `autouri` was not registered to `conda-forge` repo yet. I wrote it and thought that it was already registered. I will get back after registering `autouri` to it.

**Comment by leepc12** [comment]
Two problematic dependencies (`pyhocon` and `autouri`) are now updated on `conda-forge`.

**Comment by leepc12** [comment]
@dfornika Sorry about bothering you. I think it's now ready for a code review.

**Comment by dfornika** [comment]
@leepc12 no problem. Next time, if you think a recipe is ready and needs a review, leave the following comment:

```
@BiocondaBot please add label
```
...and the pull-request will be labeled for review.

**Comment by dfornika** [comment]
@BiocondaBot please merge

**Comment by bgruening** [comment]
@bioconda-bot please merge

**Pull request merged**
