### PR TITLE
Add python requirement for levenshtein

### PR DESCRIPTION
**Pull request by kyleabeauchamp**
Has some C extensions, so should have explicit python dependency.

### CODE REVIEW

**Comment by kyleabeauchamp** [comment]
Can anyone comment on the failing tests?  I can't merge this pull request because of unrelated failures:

```
.F.................................
======================================================================
FAIL: __main__.test_recipes('/bioconda-recipes/recipes/bioconductor-degreport',)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/anaconda/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/bioconda-recipes/scripts/build-packages.py", line 91, in build_recipe
    assert False, "All builds of recipe {} failed.".format(recipe)
AssertionError: All builds of recipe /bioconda-recipes/recipes/bioconductor-degreport failed.
-------------------- >> begin captured stdout << ---------------------


...



Error: HTTPError: 404 Client Error: Not Found for url: https://conda.anaconda.org/r/linux-64/r-colorspace-1.2_6-r3.2.2_0.tar.bz2: https://conda.anaconda.org/r/linux-64/r-colorspace-1.2_6-r3.2.2_0.tar.bz2
--------------------- >> end captured stdout << ----------------------
----------------------------------------------------------------------
Ran 35 tests in 511.857s
FAILED (failures=1)
/home/travis/build.sh: line 112:  3108 Terminated              travis_jigger $! $timeout $cmd
The command "travis_wait 119 scripts/travis-run.sh" exited with 1.
Done. Your build exited with 1.

```

**Comment by kyleabeauchamp** [comment]
Actually, you can see that the travis build for MASTER is also failing.

**Comment by kyleabeauchamp** [comment]
AFAIK this pull is fine to merge, it's the other recipes that are the issue.

**Comment by daler** [comment]
Maybe trigger a re-test in the travis interface? That's solved flaky network issues for me in the past.

**Pull request merged**
