### PR TITLE
merge in bulk

### PR DESCRIPTION
**Pull request by daler**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

This merges in the changes we've been working on in the `bulk` branch, mostly related to updating bioconductor packages to the latest version (in Bioconductor 3.6).

There are still a couple of recipes not successfully building, see `build-fail-blacklist`.

### CODE REVIEW

**Comment by cbrueffer** [comment]
Massive; thanks for the work!

**Comment by daler** [comment]
closing for now while we build missing packages on `bulk`; will reopen once bulk is clean again.

**Comment by mbargull** [comment]
@daler: Looks like #6811 did the trick. Wanna give this one a try?

**Comment by daler** [comment]
I merged #6811 into bulk, and it seems to be working: https://travis-ci.org/bioconda/bioconda-recipes/builds/302678841

Once bulk is done (i.e. no more packages to build) I'll re-open this to avoid using too many travis-ci resources. I'm about to head out, so if you see bulk finish, feel free to reopen this.

**Comment by bgruening** [comment]
The last conda-forge packages took a long time.
Great work all!

**Pull request merged**
