### PR TITLE
Update pbmm2 to 1.1.0

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`pbmm2`](https://bioconda.github.io/recipes/pbmm2/README.html): **1.0.0** &rarr; **1.1.0**

[install with bioconda](http://bioconda.github.io/recipes/pbmm2/README.html) [Conda](https://anaconda.org/bioconda/pbmm2/files)

Info | Link
-----|-----
Recipe | [`recipes/pbmm2`](https://github.com//bioconda/bioconda-recipes/tree/bump/pbmm2/recipes/pbmm2) (click to view/edit other files)
Releases |[https://github.com/PacificBiosciences/pbmm2/tags](https://github.com/PacificBiosciences/pbmm2/tags)
Recipe Maintainer(s) | @armintoepfer, @pb-dseifert, @mhsieh
Author | `@PacificBiosciences`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/updating.html)).

### CODE REVIEW

**Comment by armintoepfer** [comment]
This is blocked by pbbam and pbcopper not being updated yet. Please hold off merging!

**Comment by dpryan79** [comment]
It appears that the OSX build is getting an old htslib version for some reason.

**Comment by dpryan79** [comment]
Ah, we should be pinning libdeflate to 1.0 at the moment but for some reason 1.2 is getting pulled in on OSX.

**Comment by dpryan79** [comment]
htslib doesn't use boost at all.

**Comment by dpryan79** [comment]
Gah, sorry about that.

**Comment by dpryan79** [comment]
I'm going to relabel earlier OSX htslib builds as broken so they no longer get used.

**Comment by dpryan79** [comment]
Marking the old htslib builds as broken solved the issue :)

**Comment by armintoepfer** [comment]
Thanks for fixing the broken build!

**Pull request merged**
