### PR TITLE
Update array-as-vcf to 1.1.0

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`array-as-vcf`](https://bioconda.github.io/recipes/array-as-vcf/README.html): **1.0.1** &rarr; **1.1.0**

[install with bioconda](http://bioconda.github.io/recipes/array-as-vcf/README.html) [Conda](https://anaconda.org/bioconda/array-as-vcf/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/array-as-vcf`](https://github.com//bioconda/bioconda-recipes/tree/bump/array_as_vcf/recipes/array-as-vcf) (click to view/edit other files)
Summary | Convert SNP array to VCF
Home | [https://github.com/LUMC/array-as-vcf](https://github.com/LUMC/array-as-vcf)
Releases |[https://pypi.org/pypi/array-as-vcf/json](https://pypi.org/pypi/array-as-vcf/json)
Recipe Maintainer(s) | @Redmar_van_den_Berg, @rhpvorderman

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by cbrueffer** [comment]
@rhpvorderman is this good to go now?

**Comment by rhpvorderman** [comment]
@BiocondaBot please merge

**Comment by rhpvorderman** [comment]
@cbrueffer yes. Sorry, forgot about this PR.

**Review by rhpvorderman — APPROVED** [review]

**Comment by rhpvorderman** [comment]
@BiocondaBot please merge

**Pull request merged**
