### PR TITLE
Update sdrf-pipelines to 0.0.19

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`sdrf-pipelines`](https://bioconda.github.io/recipes/sdrf-pipelines/README.html): **0.0.18** &rarr; **0.0.19**

[install with bioconda](http://bioconda.github.io/recipes/sdrf-pipelines/README.html) [Conda](https://anaconda.org/bioconda/sdrf-pipelines/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/sdrf-pipelines`](https://github.com//bioconda/bioconda-recipes/tree/bump/sdrf_pipelines/recipes/sdrf-pipelines) (click to view/edit other files)
Summary | Translate, convert SDRF to configuration pipelines
Home | [https://github.com/bigbio/sdrf-pipelines](https://github.com/bigbio/sdrf-pipelines)
Releases |[https://pypi.org/pypi/sdrf-pipelines/json](https://pypi.org/pypi/sdrf-pipelines/json)

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by ypriverol** [comment]
@BiocondaBot please merge

**Review by ypriverol — APPROVED** [review]

**Comment by ypriverol** [comment]
@BiocondaBot please merge

**Comment by ypriverol** [comment]
@BiocondaBot please merge

**Comment by ypriverol** [comment]
ping @bgruening. The automatic PR is giving me an strange error.

**Comment by ypriverol** [comment]
@BiocondaBot please merge

**Comment by ypriverol** [comment]
@BiocondaBot please merge

**Comment by ypriverol** [comment]
@bioconda/all does anyone knows what is happening with the boot.

**Comment by dpryan79** [comment]
The bot is currently unable to upload and merge since it hasn't yet been rewritten since the CI migration to azure.

**Pull request merged**
