### PR TITLE
 update dependencies for bohra to reflect modificationf to workflow

### PR DESCRIPTION
**Pull request by kristyhoran**
This pull request is to update the conda recipe for bohra - making it easier to install. The nextflow workflow now uses individual conda envs for each process, meaning that the complex dependencies (with increased clashes) required in previous versions are no longer needed - hopefully simplifying installation.

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by rpetit3** [comment]
@kristyhoran is it ok to loosen the numpy version pinning? If not, you will need to adjust the python pinning (`>=3.9`)

```
16:32:07 BIOCONDA INFO (OUT) The reported errors are:
16:32:07 BIOCONDA INFO (OUT) - Encountered problems while solving:
16:32:07 BIOCONDA INFO (OUT) -   - package numpy-1.23.1-py38h3a7f9d9_0 requires python >=3.8,<3.9.0a0, but none of the providers can be installed
```

**Comment by kristyhoran** [comment]
Hi Robert,
thank you!! I have downgraded python to 3.8 .. the numpy version is
important it seems to fall over if i let it default to the most recent
version
Cheers
Kristy

**Review by rpetit3 — APPROVED** [review]

**Comment by rpetit3** [comment]
@kristyhoran If you are all good, we can get this merged

**Comment by kristyhoran** [comment]
All good now @rpetit3 Thank you!!

**Comment by tseemann** [comment]
Thanks @rpetit3 !

**Comment by rpetit3** [comment]
No problem!

**Pull request merged**
