### PR TITLE
new recipe for RAPPAS

### PR DESCRIPTION
**Pull request by blinard-BIOINFO**
Dear @bioconda/core,

This is a new recipe for the software RAPPAS, doing phylogenetic placement of metagenomic reads. It got published in january 2019.

I also would like to be added to the bioconda project.

* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [X] This PR adds a new recipe.
* [X] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).

### CODE REVIEW

**Comment by blinard-BIOINFO** [comment]
I think I need some help from members of @bioconda/core  on this one.

The program RAPPAS for which I'm building a recipe is based on java and it seems some fonts libraries required by java 11 are absent from the docker loaded in the CI.
I tried to put the "freetype" and "fontconfig" conda library as a dependancy, but this did not solve the problem.

More search made me find this post, which described something similar my situation :
https://stackoverflow.com/questions/51307075/docker-and-java-fontconfiguration-issue

When using conda-utils locally, I confirm the application builds and runs the test without errors.
However, the CI pipeline seems to miss systems fonts and fails to run java correctly...
As a side note, I did not set any special font in the code, it is the default fonts required by the java virtual machine that are searched and not found.

The post linked concluded the issue came from Jenkins where Alpine Linux does nto come with system fonts. 

Do we have the same situation in the bioconda-test workflow ?

**Comment by blinard-BIOINFO** [comment]
More comments. 
When testing the package locally with bioconda-utils, I am not able to run the test with a docker environement. 
E.g.
`bioconda-utils build --git-range master
`
 --> compile and run tests successfully.
`bioconda-utils build --docker --git-range master
`
--> Fails with the following error:
```

17:16:08 BIOCONDA INFO (OUT) # Automatic uploading is disabled
17:16:08 BIOCONDA INFO (OUT) # If you want to upload package(s) to anaconda.org later, type:
17:16:08 BIOCONDA INFO (OUT) 
17:16:08 BIOCONDA INFO (OUT) anaconda upload /tmp/miniconda/miniconda/conda-bld/noarch/rappas-1.12-0.tar.bz2
17:16:08 BIOCONDA INFO (OUT) 
17:16:08 BIOCONDA INFO (OUT) # To have conda build upload to anaconda.org automatically, use
17:16:08 BIOCONDA INFO (OUT) # $ conda config --set anaconda_upload yes
17:16:08 BIOCONDA INFO (OUT) 
17:16:08 BIOCONDA INFO (OUT) anaconda_upload is not set.  Not uploading wheels: []
17:16:08 BIOCONDA INFO (OUT) ####################################################################################
17:16:08 BIOCONDA INFO (OUT) Resource usage summary:
17:16:08 BIOCONDA INFO (OUT) 
17:16:08 BIOCONDA INFO (OUT) Total time: 0:02:27.7
17:16:08 BIOCONDA INFO (OUT) CPU usage: sys=0:00:05.5, user=0:01:35.6
17:16:08 BIOCONDA INFO (OUT) Maximum memory usage observed: 709.6M
17:16:08 BIOCONDA INFO (OUT) Total disk usage observed (not including envs): 145.9K

17:16:09 BIOCONDA INFO BUILD SUCCESS rappas-1.12-0.tar.bz2
17:16:09 BIOCONDA INFO (COMMAND) conda build purge
17:16:09 BIOCONDA INFO BUILD SUMMARY: successfully built 1 of 1 recipes
(base) ben@ben-Precision-Tower-3420:~/bioconda-recipes$ bioconda-utils build --docker --git-range master
17:16:24 BIOCONDA INFO Considering total of 6881 recipes.
17:16:24 BIOCONDA INFO Constraining to 1 git modified recipes (appas).
17:16:24 BIOCONDA INFO Processing 1 recipes (appas).
17:16:24 BIOCONDA INFO Generating DAG
Loading Recipes: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 114.62it/s]
17:16:25 BIOCONDA INFO Building and testing 1 recipes in total
17:16:25 BIOCONDA INFO Recipes to build: 
rappas
17:16:25 BIOCONDA INFO Building and testing subdag 1 of 1
17:16:25 BIOCONDA INFO Determining expected packages for recipes/rappas
Setting build platform. This is only useful when pretending to be on another platform, such as for rendering necessary dependencies on a non-native platform. I trust that you know what you're doing.
17:16:25 CONDA_BUILD WARNING Setting build platform. This is only useful when pretending to be on another platform, such as for rendering necessary dependencies on a non-native platform. I trust that you know what you're doing.
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
17:16:25 CONDA_BUILD WARNING No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
Adding in variants from internal_defaults
17:16:25 CONDA_BUILD INFO Adding in variants from internal_defaults
Adding in variants from /tmp/miniconda/miniconda/conda_build_config.yaml
17:16:25 CONDA_BUILD INFO Adding in variants from /tmp/miniconda/miniconda/conda_build_config.yaml
Adding in variants from /tmp/miniconda/miniconda/lib/python3.6/site-packages/bioconda_utils/bioconda_utils-conda_build_config.yaml
17:16:25 CONDA_BUILD INFO Adding in variants from /tmp/miniconda/miniconda/lib/python3.6/site-packages/bioconda_utils/bioconda_utils-conda_build_config.yaml
defaults/noarch: 398kB [00:00, 19.7MB/s]                                                                                                                      | 0/9 [00:00<?, ?files/s]
conda-forge/noarch: 9.50MB [00:00, 15.7MB/s]                                                                                                          | 1/9 [00:00<00:01,  5.38files/s]
defaults/osx: 15.0MB [00:01, 15.2MB/s]█████████▎                                                                                                      | 2/9 [00:01<00:02,  2.45files/s]
defaults/linux: 16.6MB [00:01, 13.4MB/s]██████████████████████                                                                                        | 3/9 [00:01<00:02,  2.65files/s]
bioconda/linux: 15.2MB [00:01, 10.1MB/s]]
bioconda/osx: 12.6MB [00:00, 16.0MB/s]██████████████████████████████████████▋                                                                         | 4/9 [00:02<00:02,  2.12files/s]
bioconda/noarch: 5.41MB [00:00, 11.2MB/s]█████████████████████████████████████████████████████████████████                                            | 6/9 [00:02<00:01,  2.46files/s]
conda-forge/osx: 40.7MB [00:02, 15.9MB/s]███████████████████████████████████████████████████████████████████████████████▋                             | 7/9 [00:02<00:00,  3.02files/s]
conda-forge/linux: 41.6MB [00:04, 10.8MB/s]
Downloading: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 9/9 [00:05<00:00,  1.65files/s]
17:16:31 BIOCONDA INFO BUILD START recipes/rappas
17:16:31 BIOCONDA INFO (COMMAND) docker run -t --net host --rm -v /tmp/tmpr9ln7cw5/build_script.bash:/opt/build_script.bash -v /tmp/miniconda/miniconda/conda-bld/:/opt/host-conda-bld -v /home/ben/bioconda-recipes/recipes/rappas:/opt/recipe -e LC_MEASUREMENT=fr_FR.UTF-8 -e LC_PAPER=fr_FR.UTF-8 -e LC_MONETARY=fr_FR.UTF-8 -e LANG=en_GB.UTF-8 -e LC_NAME=fr_FR.UTF-8 -e LC_ADDRESS=fr_FR.UTF-8 -e LC_NUMERIC=fr_FR.UTF-8 -e LC_TELEPHONE=fr_FR.UTF-8 -e LC_IDENTIFICATION=fr_FR.UTF-8 -e LC_TIME=fr_FR.UTF-8 -e HOST_USER_ID=1000 bioconda/bioconda-utils-build-env:latest /bin/bash /opt/build_script.bash
17:16:32 BIOCONDA INFO (OUT) /opt/build_script.bash: /opt/build_script.bash: is a directory
17:16:32 BIOCONDA ERROR COMMAND FAILED (exited with 126): docker run -t --net host --rm -v /tmp/tmpr9ln7cw5/build_script.bash:/opt/build_script.bash -v /tmp/miniconda/miniconda/conda-bld/:/opt/host-conda-bld -v /home/ben/bioconda-recipes/recipes/rappas:/opt/recipe -e LC_MEASUREMENT=fr_FR.UTF-8 -e LC_PAPER=fr_FR.UTF-8 -e LC_MONETARY=fr_FR.UTF-8 -e LANG=en_GB.UTF-8 -e LC_NAME=fr_FR.UTF-8 -e LC_ADDRESS=fr_FR.UTF-8 -e LC_NUMERIC=fr_FR.UTF-8 -e LC_TELEPHONE=fr_FR.UTF-8 -e LC_IDENTIFICATION=fr_FR.UTF-8 -e LC_TIME=fr_FR.UTF-8 -e HOST_USER_ID=1000 bioconda/bioconda-utils-build-env:latest /bin/bash /opt/build_script.bash

17:16:32 BIOCONDA ERROR BUILD FAILED recipes/rappas
17:16:32 BIOCONDA INFO (COMMAND) conda build purge
17:16:32 BIOCONDA ERROR BUILD SUMMARY: of 1 recipes, 1 failed and 0 were skipped. Details of recipes and environments follow.
17:16:32 BIOCONDA ERROR BUILD SUMMARY: FAILED recipe recipes/rappas
```

**Comment by blinard-BIOINFO** [comment]
It definitely seems to be an issue between java jre >8 and apline minimal environement... 
https://stackoverflow.com/questions/45315251/could-not-initialize-class-sun-awt-x11fontmanager-using-openjdk-8-on-alpine-linu

Ongoing: testing which library are necessary to run java correclty in the test environment.

**Comment by blinard-BIOINFO** [comment]
Solution found.
The minimal docker image image to run tests is based on CentOS. 
Java version >=8 will work fine after explicitely installing this package: 
`sudo yum install dejavu-sans-fonts`

What helped me a lot:
https://wiki.jenkins.io/display/JENKINS/Jenkins+got+java.awt.headless+problem

Finding required that I understand: 
1) where and how to run an interactive prompt in the docker image launched by conda-utils , e.g.
`docker run --entrypoint "/bin/sh" -it --net host -v /tmp/tmpluo5v4hi/build_script.bash:/opt/build_script.bash -v /tmp/miniconda/miniconda/conda-bld/:/opt/host-conda-bld -v /home/ben/bioconda-recipes/recipes/rappas:/opt/recipe -e LC_MEASUREMENT=fr_FR.UTF-8 -e LC_PAPER=fr_FR.UTF-8 -e LC_MONETARY=fr_FR.UTF-8 -e LANG=en_GB.UTF-8 -e LC_NAME=fr_FR.UTF-8 -e LC_ADDRESS=fr_FR.UTF-8 -e LC_NUMERIC=fr_FR.UTF-8 -e LC_TELEPHONE=fr_FR.UTF-8 -e LC_IDENTIFICATION=fr_FR.UTF-8 -e LC_TIME=fr_FR.UTF-8 -e HOST_USER_ID=1000 bioconda/bioconda-utils-build-env:latest`
2) than running it interactively on a minimal linux image REQUIRES to change the prefix to:
`docker run --entrypoint "/bin/sh" -it
`
3) which conda environment is used for tests in this docker
`conda activate /opt/conda/conda-bld/rappas_1568911290112/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p`
4) on which system is based this docker generated by conda-utils:
`cat /etc/system-release
`

I may be wrong, but none of this is documented in conda tutorials for helping to debug packages. 
Adding these information somewhere in the tutorial can very helpful !

Next step (tomorrow it's late), testing if the conda package font-ttf-dejavu-sans-mono is equivalent to the centOS package and can solve the issue directly from the meta.yaml file.

**Comment by dpryan79** [comment]
We've had some similar problems with docker containers for R packages where they need fonts for the plots to actually work, so I guess this doesn't surprise me. For them adding `mscorefonts` seems to fix things.

**Comment by dpryan79** [comment]
@blinard-BIOINFO I'll send you an invite to join bioconda.

**Comment by dpryan79** [comment]
@bioconda-bot merge

**Pull request merged**
