### PR TITLE
Update treesapp to 0.9.7

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`treesapp`](https://bioconda.github.io/recipes/treesapp/README.html): **0.9.6** &rarr; **0.9.7**

[install with bioconda](http://bioconda.github.io/recipes/treesapp/README.html) [Conda](https://anaconda.org/bioconda/treesapp/files)

Info | Link
-----|-----
Recipe | [`recipes/treesapp`](https://github.com//bioconda/bioconda-recipes/tree/bump/treesapp/recipes/treesapp) (click to view/edit other files)
Releases |[https://pypi.org/pypi/treesapp/json](https://pypi.org/pypi/treesapp/json)
Recipe Maintainer(s) | @cmorganl

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by cmorganl** [comment]
@BiocondaBot please add label

**Comment by druvus** [comment]
@bioconda-bot please fetch artifacts

**Review by druvus — APPROVED** [review]

**Comment by cmorganl** [comment]
@druvus is there something holding up merging of this update? Let me know if there is.

Thanks!

**Comment by druvus** [comment]
@BiocondaBot please merge

**Pull request merged**
