### PR TITLE
Transposcope recipe

### PR DESCRIPTION
**Pull request by MarkGrivainis**
:information_source:
Bioconda has finished the [GCC7 migration](https://github.com/bioconda/bioconda-recipes/issues/13578). If you are dealing with C/C++ or Python package it can be that you need to rebuild other dependent packages. [Bioconda utils - update-pinning](https://bioconda.github.io/updating.html#updating-recipes-for-a-pinning-change) will assist you with that. If you have any questions please use [issue 13578](https://github.com/bioconda/bioconda-recipes/issues/13578).

----------------

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by npavlovikj** [comment]
Since this is python package, you can completely remove "build.sh" and add `script: "{{ PYTHON }} -m pip install . --no-deps -vv"` under `build` in meta.yaml, and `pip` in the run section (something like https://github.com/bioconda/bioconda-recipes/blob/033d2455e2ba31a19e37ed635d7bcc60273c47f1/recipes/peddy/meta.yaml). Also you can add information about `license_family` and `license_file`.

**Comment by npavlovikj** [comment]
Please set the build number to 0 - you only increment it if the PR has been merged and you are modifying the same recipe (https://bioconda.github.io/guidelines.html#buildnum). Since the PR hasn't been merged yet, please use `number: 0`.

**Comment by npavlovikj** [comment]
LGTM, thanks for adding the recipe @MarkGrivainis !

**Comment by MarkGrivainis** [comment]
Thank you for the assistance.

**Pull request merged**
