### PR TITLE
Update plastedma to 0.2.0

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`plastedma`](https://bioconda.github.io/recipes/plastedma/README.html): **0.1.2** &rarr; **0.2.0**

[install with bioconda](http://bioconda.github.io/recipes/plastedma/README.html) [Conda](https://anaconda.org/bioconda/plastedma/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/plastedma`](https://github.com//bioconda/bioconda-recipes/tree/bump/plastedma/recipes/plastedma) (click to view/edit other files)
Summary | Plastic Enzymes Degrading in Metagenomic databases Analysis
Home | [https://github.com/ozefreitas/PlastEDMA](https://github.com/ozefreitas/PlastEDMA)
Releases |[https://github.com/ozefreitas/PlastEDMA/tags](https://github.com/ozefreitas/PlastEDMA/tags)
Recipe Maintainer(s) | @ozefreitas
Author | @ozefreitas
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by ozefreitas** [comment]
@dpryan79 could you please add me as a member of bioconda teams so I can edit my tool recipes? My build.sh has changed and  I need to commit here

**Comment by ozefreitas** [comment]
Can I please be added as a member of bioconda teams so I can edit my tool recipes? My build.sh has changed and I need to commit here

**Comment by iquasere** [comment]
@bioconda/core

**Comment by dpryan79** [comment]
@ozefreitas You should receive an invitation shortly.

**Pull request closed without merging**
