### PR TITLE
Update r-freerange to 0.2.1

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`r-freerange`](https://bioconda.github.io/recipes/r-freerange/README.html): **0.1.6** &rarr; **0.2.1**

[install with bioconda](http://bioconda.github.io/recipes/r-freerange/README.html) [Conda](https://anaconda.org/bioconda/r-freerange/files)

Info | Link
-----|-----
Recipe | [`recipes/r-freerange`](https://github.com//bioconda/bioconda-recipes/tree/bump/r_freerange/recipes/r-freerange) (click to view/edit other files)
Releases |[https://github.com/acidgenomics/freerange/tags](https://github.com/acidgenomics/freerange/tags)
Recipe Maintainer(s) | @mjsteinbaugh
Author | `@acidgenomics`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/updating.html)).

### CODE REVIEW

**Comment by dpryan79** [comment]
This is waiting on bioconductor-ensembldb to get built.

**Comment by dpryan79** [comment]
Requires an update to r-syntactic

**Comment by dpryan79** [comment]
Apparently this is requesting a version of r-syntactic that has yet to be tagged.

**Comment by mjsteinbaugh** [comment]
Thanks I forgot to tag the latest version of syntactic. I'm fixing the bioconda recipe for that one.

**Pull request merged**
