### PR TITLE
Update staramr to 0.7.2

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`staramr`](https://bioconda.github.io/recipes/staramr/README.html): **0.7.1** &rarr; **0.7.2**

[install with bioconda](http://bioconda.github.io/recipes/staramr/README.html) [Conda](https://anaconda.org/bioconda/staramr/files)

Info | Link
-----|-----
Recipe | [`recipes/staramr`](https://github.com//bioconda/bioconda-recipes/tree/bump/staramr/recipes/staramr) (click to view/edit other files)
Releases |[https://pypi.org/pypi/staramr/json](https://pypi.org/pypi/staramr/json)

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by apetkau** [comment]
I need to make a small change to the dependencies for this PR.

**Comment by apetkau** [comment]
It's been updated to remove the restriction on newer versions of pandas (caused by this issue https://github.com/phac-nml/staramr/issues/115).

@bioconda-bot please fetch artifacts

**Comment by apetkau** [comment]
@BiocondaBot please fetch artifacts

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@bioconda-bot please merge

@apetkau You're welcome to merge these too :)

**Comment by apetkau** [comment]
@dpryan79 awesome, thanks. And thanks for letting me know that I could have merged it. I'm sometimes uncertain what I can or cannot do 😄

**Pull request merged**
