### PR TITLE
Update ariba dependencies

### PR DESCRIPTION
**Pull request by rpetit3**
The most recent version of bcftools and pysam cause Ariba to fail
```
mpileup: invalid option -- 't'
Failed cluster: cluster
Traceback (most recent call last):
  File "/home/robert_petit/miniconda3/envs/test-seroba/lib/python3.9/site-packages/ariba/clusters.py", line 612, in run
    self._run()
  File "/home/robert_petit/miniconda3/envs/test-seroba/lib/python3.9/site-packages/ariba/clusters.py", line 646, in _run
    raise Error('At least one cluster failed! Stopping...')
ariba.clusters.Error: At least one cluster failed! Stopping...
```

Downgrading is hte fix
```
mamba install -c conda-forge -c bioconda 'bcftools<=1.14' 'pysam<=0.18.0'
```

This PR pins the dependencies. Ariba no longer has the resources for active maintenance, so this PR helps keep Ariba working as the dependencies get updated

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by rpetit3** [comment]
@BiocondaBot please add label

**Review by simonbray — APPROVED** [review]

**Comment by simonbray** [comment]
@BiocondaBot please upload artifacts

**Comment by rpetit3** [comment]
Thank you! This should hopefully complete the Seroba PR!

**Comment by rpetit3** [comment]
@BiocondaBot please merge

**Pull request merged**
