### PR TITLE
Update deepac to 0.14.1

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`deepac`](https://bioconda.github.io/recipes/deepac/README.html): **0.14.0** &rarr; **0.14.1**

[install with bioconda](http://bioconda.github.io/recipes/deepac/README.html) [Conda](https://anaconda.org/bioconda/deepac/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/deepac`](https://github.com//bioconda/bioconda-recipes/tree/bump/deepac/recipes/deepac) (click to view/edit other files)
Summary | Predicting pathogenic potentials of novel DNA with reverse-complement neural networks.
Home | [https://gitlab.com/dacs-hpi/deepac](https://gitlab.com/dacs-hpi/deepac)
Releases |[https://pypi.org/pypi/deepac/json](https://pypi.org/pypi/deepac/json)
Recipe Maintainer(s) | @JakubBartoszewicz

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by priesgo** [comment]
I could not find the release 0.14.1 in https://gitlab.com/dacs-hpi/deepac. Am I looking in the wrong place?

**Comment by priesgo** [comment]
> I could not find the release 0.14.1 in https://gitlab.com/dacs-hpi/deepac. Am I looking in the wrong place?

I see, this came from pypi... Would be nice to have it tagged in the repo, but I'm approving it.

**Review by priesgo — APPROVED** [review]
LGTM

**Comment by priesgo** [comment]
@BiocondaBot please merge

**Comment by JakubBartoszewicz** [comment]
@BiocondaBot please merge

**Comment by JakubBartoszewicz** [comment]
> > I could not find the release 0.14.1 in https://gitlab.com/dacs-hpi/deepac. Am I looking in the wrong place?
> 
> I see, this came from pypi... Would be nice to have it tagged in the repo, but I'm approving it.

Haha, yeah, I didn't manage to create the tag yet when you had a look. Already done ;) Thx!

**Pull request merged**
