### PR TITLE
mpa: fix missing xml files

### PR DESCRIPTION
**Pull request by bernt-matthias**
- add comet and xtandem requirements
- outline workaround to use the package
- add fontconfig explicitly (seems not to come reliably with java>=11)

follow up to #25508

- the precompiled comet and xtandem binaries did not work in a
  container due to missing libraries. hence I replace (link)
  them at build time with the ones from the corresponding conda packages
  (unfortunately I could not find out how to configure the paths
  to the binaries in MPA .. see
  compomics/meta-proteome-analyzer#31)

- MPA still complained about:
  `java.io.FileNotFoundException: /usr/local/share/mpa-portable-1.4.1-2/built/X!Tandem/linux/linux_64bit/taxonomy.xml (Permission denied)`

  the point is that MPA tries to write the input xml files for xtandem
  into this directory which does not work in a container and is a bad
  idea also for conda environments.

  a possible workaround is to copy the whole mpa dir into a temporary
  dir outside of the container and to replace the copies of the xtandem
  and comet binaries with links (I could not find out how to copy the
  links correctly). this is documented in the build script.

  I asked upstream for a possibility to configure the input paths to
  xtandem: compomics/meta-proteome-analyzer#31

Edit: the workaround is now implemented in the python wrapper. 

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by bernt-matthias** [comment]
@BiocondaBot please add label

**Comment by bernt-matthias** [comment]
@BiocondaBot please fetch artifacts

**Comment by bernt-matthias** [comment]
@BiocondaBot please fetch artifacts

**Comment by bernt-matthias** [comment]
@BiocondaBot please fetch artifacts

**Comment by bernt-matthias** [comment]
@BiocondaBot please fetch artifacts

**Comment by bernt-matthias** [comment]
@BiocondaBot please fetch artifacts

**Comment by bernt-matthias** [comment]
@BiocondaBot please fetch artifacts

**Comment by bernt-matthias** [comment]
@BiocondaBot please fetch artifacts

**Comment by bernt-matthias** [comment]
@BiocondaBot please fetch artifacts

**Comment by bernt-matthias** [comment]
@BiocondaBot please fetch artifacts

**Comment by bernt-matthias** [comment]
@BiocondaBot please fetch artifacts

**Comment by bernt-matthias** [comment]
@BiocondaBot please fetch artifacts

**Comment by bernt-matthias** [comment]
@BiocondaBot please fetch artifacts

**Comment by bernt-matthias** [comment]
@BiocondaBot please add label

**Comment by bernt-matthias** [comment]
@BiocondaBot please fetch artifacts

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
@bioconda-bot please merge

**Comment by bernt-matthias** [comment]
Seems that the package and container has been uploaded. Can we ignore the bot message?

**Comment by bgruening** [comment]
Äh, ok. Strange. I will try again and then I can merge manually if you are happy.

**Comment by bgruening** [comment]
@bioconda-bot please merge

**Pull request merged**
