### PR TITLE
Add somalier

### PR DESCRIPTION
**Pull request by jfy133**
Attempt to adds [somalier](https://github.com/brentp/somalier)

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by jfy133** [comment]
Skipping OSX as slivar is used within this package and also is not buildable on OSX (according slivar recipe: https://github.com/bioconda/bioconda-recipes/blob/73a14544ca8ef7926797b39259cb58b83732b7da/recipes/slivar/meta.yaml)

Failed test on OSX recipe:

```
19:36:33 BIOCONDA INFO (OUT)      Error: Build failed for package: slivar
19:36:33 BIOCONDA INFO (OUT)         ... Execution failed with exit code 256
19:36:33 BIOCONDA INFO (OUT)         ... Command: $BUILD_PREFIX/nim/bin/nim c --colors:on --noNimblePath -d:release -d:NimblePkgVersion=0.2.8 --path:$SRC_DIR/somalier-0.2.15/nimbledeps/pkgs/hts-0.3.23 --path:$SRC_DIR/somalier-0.2.15/nimbledeps/pkgs/lapper-0.1.7 --path:$SRC_DIR/somalier-0.2.15/nimbledeps/pkgs/c2nim-0.9.18 --path:$SRC_DIR/somalier-0.2.15/nimbledeps/pkgs/unicodedb-0.10.0 --path:$SRC_DIR/somalier-0.2.15/nimbledeps/pkgs/regex-0.19.0 --path:$SRC_DIR/somalier-0.2.15/nimbledeps/pkgs/nimgen-0.5.1 --path:'$SRC_DIR/somalier-0.2.15/nimbledeps/pkgs/duktape-#dev' --path:$SRC_DIR/somalier-0.2.15/nimbledeps/pkgs/pedfile-0.0.4 --path:$SRC_DIR/somalier-0.2.15/nimbledeps/pkgs/minizip-0.0.8 --path:$SRC_DIR/somalier-0.2.15/nimbledeps/pkgs/argparse-0.10.1 -o:'/tmp/nimble_28687/githubcom_brentpslivar_#head/slivar' '/tmp/nimble_28687/githubcom_brentpslivar_#head/src/slivar.nim'
19:36:42 BIOCONDA ERROR COMMAND FAILED (exited with 1): /usr/local/miniconda/envs/bioconda/bin/conda mambabuild --override-channels --no-anaconda-upload -c conda-forge -c bioconda -c defaults -e /usr/local/miniconda/envs/bioconda/conda_build_config.yaml -e /usr/local/miniconda/envs/bioconda/lib/python3.7/site-packages/bioconda_utils/bioconda_utils-conda_build_config.yaml recipes/somalier/meta.yaml

19:36:42 BIOCONDA ERROR BUILD FAILED recipes/somalier
```

**Comment by jfy133** [comment]
@BiocondaBot please add label

**Comment by jfy133** [comment]
@BiocondaBot please fetch artifacts

**Review by brentp — APPROVED** [review]

**Comment by daler** [comment]
@BiocondaBot please merge

**Pull request merged**
