### PR TITLE
Update epic to 0.1.24

### PR DESCRIPTION
**Pull request by endrebak**
* [*] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [*] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by jerowe** [comment]
@endrebak, are you overwriting an existing recipe?

If you are, could you instead create a new directory for the old recipe, and a new meta.yaml file?

epic/
    - old_version/
          meta.yaml
          build.sh
    - meta.yaml #New version
    - build.sh #New version

**Comment by endrebak** [comment]
Thanks for the tip. But the tests failed due to timing out so I guess the same thing will happen if I try again?

**Comment by jerowe** [comment]
Possibly. Sometimes travis just times out. How large is your software?

**Comment by endrebak** [comment]
It is just a dinky Python-script: https://github.com/endrebak/epic

Several users have requested a bioconda version so I'll try again if that
is OK.

Endre

**Comment by jerowe** [comment]
I should have been clearer. ;-)

Of course try again. Sometimes time out errors are due to Travis, which is the testing platform. Push a new commit, and if it was Travis you should be fine.

**Comment by bgruening** [comment]
@endrebak the testing wasn't timing out. We have a 2h timeout so this is enough for most of the packaes. The error is here: https://travis-ci.org/bioconda/bioconda-recipes/jobs/191260777#L955

**Comment by endrebak** [comment]
Thanks for your patient replies :) I had forgotten to add a package to my
conda requirements. Strange that the tests passed on my travis, but oh well.

**Comment by endrebak** [comment]
From now on, I'll create a folder for old versions. The software is still in beta :)

**Pull request merged**
