### PR TITLE
Added msprime to osx-whitelist.

### PR DESCRIPTION
**Pull request by jeromekelleher**

### CODE REVIEW

**Comment by jeromekelleher** [comment]
Would it be possible for an OSX expert to have a quick look at this please? I've been going through the Travis logs and I can't figure out what the problem is. I have limited access to an OSX machine, so testing out the full Travis script is hard, but the packages seem to build locally fine. The salient bit of the log is
```
Traceback (most recent call last):
  File "/anaconda/conda-bld/test-tmp_dir/run_test.py", line 25, in <module>
    import msprime
  File "build/bdist.macosx-10.5-x86_64/egg/msprime/__init__.py", line 26, in <module>
  File "build/bdist.macosx-10.5-x86_64/egg/_msprime.py", line 7, in <module>
  File "build/bdist.macosx-10.5-x86_64/egg/_msprime.py", line 6, in __bootstrap__
ImportError: dlopen(/Users/travis/.python-eggs/msprime-0.1.7-py2.7-macosx-10.5-x86_64.egg-tmp/_msprime.so, 2): Library not loaded: @rpath/./libgsl.0.dylib
  Referenced from: /Users/travis/.python-eggs/msprime-0.1.7-py2.7-macosx-10.5-x86_64.egg-tmp/_msprime.so
  Reason: image not found
```
So, it seems that the package is building and testing fine initially, but when an install is attempted OSX can't find the GSL library? I've been looking through lots of other recipes and I can't see why the msprime one is failing particularly.

Any pointers would be much appreciated!

**Comment by kyleabeauchamp** [comment]
1.  It looks strange to me that GSL is listed in the runtime requirements but not the build requirements.  For a C library, I imagine it would need to be in both places.
2.  I don't think GSL is available on the OSX platform.

**Comment by jeromekelleher** [comment]
Thanks for taking a look @kyleabeauchamp! 

1. I think GSL is listed on both the 'build' and 'run' parts of the requirements section;

2. I just tried installing GSL using conda on the OSX system I have (non-root) access to, and it worked fine.

The odd thing is that the package builds fine using ``conda build`` on this machine, it just won't build on Travis.

**Comment by johanneskoester** [comment]
I think I had the same problems on osx in PR #680. There, also libraries are not found although they are present. Something with RPATH or LD_LIBRARY_PATH?

**Comment by kyleabeauchamp** [comment]
On my machine I get this:

```
Error: No packages found in current osx-64 channels matching: gsl
```

What channel are you sourcing?

**Comment by johanneskoester** [comment]
The R channel contains the GSL for osx.

**Comment by kyleabeauchamp** [comment]
got it.  Well, ignore my comments then.

**Comment by jeromekelleher** [comment]
Thanks @johanneskoester, this is very helpful. Perhaps linking against libraries on OSX is a more general problem? It seems that setting LD_LIBRARY_PATH is [problematic](http://conda.pydata.org/docs/building/shared-libraries.html), and I can't find any recipes using RPATH.

**Comment by johanneskoester** [comment]
Right. Maybe it's time to ask the conda staff about this. Do you want to file an issue?

**Comment by jeromekelleher** [comment]
I'd like to be able to reproduce the problem locally before I file a bug upstream, but my OSX setup isn't quite what the scripts expect. I'll see if I can get root access to the machine and follow it up tomorrow.

**Comment by jeromekelleher** [comment]
Closing this PR as it is out-of-date.

**Pull request closed without merging**
