### PR TITLE
Added ABRA2 recipe

### PR DESCRIPTION
**Pull request by micknudsen**
Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it. Note that if you are not already a member of the bioconda project (meaning that you can't add this label), please ping `@bioconda/core` so that your PR can be reviewed and merged (please note if you'd like to be added to the bioconda project). Please see https://github.com/bioconda/bioconda-recipes/issues/15332 for more details.

* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [X] This PR adds a new recipe.
* [X] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by micknudsen** [comment]
It appears that somehow the test has a non-zero return code. That is not the case when I run the command locally.

**Comment by dpryan79** [comment]
I think I've identified the issue. Firstly, `JAVA_HOME` isn't set, so the wrapper script in the docker container was trying to use `java` in a place it didn't exist. Secondly there was a `jar_path` where there should have been a `java_path` and that issue was exposed by `JAVA_HOME` not being set.

**Comment by dpryan79** [comment]
Thanks @micknudsen !

**Comment by micknudsen** [comment]
@dpryan79 Thanks for assisting in getting the last bits right – and thanks to @dansondergaard for allowing me to submit his recipe 👍

**Pull request merged**
