### PR TITLE
Package Heinz

### PR DESCRIPTION
**Pull request by CicoZhang**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by CicoZhang** [comment]
It seems that build has succeeded, but the test failed. How should I fix this? :sos: 
```
The following NEW packages will be INSTALLED:

    heinz:        2.0-0            local   
    libgcc:       7.2.0-h69d50b8_2 defaults
    libgcc-ng:    7.2.0-hdf63c60_3 defaults
    libstdcxx-ng: 7.2.0-hdf63c60_3 defaults

TESTS FAILED: heinz-2.0-0.tar.bz2


18:06:24 BIOCONDA ERROR BUILD FAILED recipes/heinz, CONDA_ALLOW_SOFTLINKS=false;CONDA_BAMTOOLS=2.4.1;CONDA_BOOST=1.64;CONDA_BZIP2=1.0;CONDA_GMP=5.1;CONDA_GSL=1.16;CONDA_HDF5=1.8.17;CONDA_HTSLIB=1.7;CONDA_NCURSES=5.9;CONDA_NPY=112;CONDA_PERL=5.22.0;CONDA_PY=27;CONDA_R=3.4.1;CONDA_ROOT=/home/circleci/project/miniconda;CONDA_XZ=5.2;CONDA_ZLIB=1.2.11;LANG=en_US.UTF-8;MACOSX_DEPLOYMENT_TARGET=10.9
18:06:25 BIOCONDA ERROR BUILD SUMMARY: of 1 recipes, 1 failed and 0 were skipped. Details of recipes and environments follow.
18:06:25 BIOCONDA ERROR BUILD SUMMARY: FAILED recipe heinz-2.0-0.tar.bz2, environment CONDA_PY=27;CONDA_HTSLIB=1.7;CONDA_BOOST=1.64;CONDA_R=3.4.1;CONDA_PERL=5.22.0;CONDA_NPY=112;CONDA_NCURSES=5.9;CONDA_GSL=1.16;CONDA_GMP=5.1;CONDA_HDF5=1.8.17;MACOSX_DEPLOYMENT_TARGET=10.9;CONDA_ZLIB=1.2.11;CONDA_BZIP2=1.0;CONDA_XZ=5.2;CONDA_BAMTOOLS=2.4.1
Exited with code 1
```

**Comment by CicoZhang** [comment]
Fail to pass the final test. @daler How should I fix it? 
```
..11:54:22 BIOCONDA ERROR COMMAND FAILED: /Users/distiller/project/miniconda/bin/conda build --no-anaconda-upload --channel bioconda --channel conda-forge --channel defaults recipes/heinz/meta.yaml
11:54:22 BIOCONDA ERROR STDOUT+STDERR:
INFO:filelock:Lock 4569741128 acquired on /Users/distiller/project/miniconda/locks/L1VzZXJzL2Rpc3RpbGxl
INFO:filelock:Lock 4569741128 released on /Users/distiller/project/miniconda/locks/L1VzZXJzL2Rpc3RpbGxl
```
```
BUILD START (revised): heinz-2.0-0
Package: heinz-2.0-0
source tree in: /Users/distiller/project/miniconda/conda-bld/heinz_1526323934129/work/conda-heinz-v2.0
Traceback (most recent call last):
  File "/Users/distiller/project/miniconda/bin/conda-build", line 6, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "/Users/distiller/project/miniconda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 342, in main
    execute(sys.argv[1:])
  File "/Users/distiller/project/miniconda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 333, in execute
    noverify=args.no_verify)
  File "/Users/distiller/project/miniconda/lib/python3.6/site-packages/conda_build/api.py", line 97, in build
    need_source_download=need_source_download, config=config)
  File "/Users/distiller/project/miniconda/lib/python3.6/site-packages/conda_build/build.py", line 1524, in build_tree
    config=config)
  File "/Users/distiller/project/miniconda/lib/python3.6/site-packages/conda_build/build.py", line 1147, in build
    utils.check_call_env(cmd, env=env, cwd=src_dir)
  File "/Users/distiller/project/miniconda/lib/python3.6/site-packages/conda_build/utils.py", line 628, in check_call_env
    return _func_defaulting_env_to_os_environ(subprocess.check_call, *popenargs, **kwargs)
  File "/Users/distiller/project/miniconda/lib/python3.6/site-packages/conda_build/utils.py", line 624, in _func_defaulting_env_to_os_environ
    return func(_args, **kwargs)
  File "/Users/distiller/project/miniconda/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/bin/bash', '-x', '-e', '/Users/distiller/project/miniconda/conda-bld/heinz_1526323934129/work/conda-heinz-v2.0/conda_build.sh']' returned non-zero exit status 64.


11:55:12 BIOCONDA ERROR BUILD FAILED recipes/heinz, CONDA_ALLOW_SOFTLINKS=false;CONDA_BAMTOOLS=2.4.1;CONDA_BOOST=1.64;CONDA_BZIP2=1.0;CONDA_GMP=5.1;CONDA_GSL=1.16;CONDA_HDF5=1.8.17;CONDA_HTSLIB=1.7;CONDA_NCURSES=5.9;CONDA_NPY=112;CONDA_PERL=5.22.0;CONDA_PY=27;CONDA_R=3.4.1;CONDA_ROOT=/Users/distiller/project/miniconda;CONDA_XZ=5.2;CONDA_ZLIB=1.2.11;LANG=en_US.UTF-8;LC_ALL=en_US.UTF-8;LC_CTYPE=en_US.UTF-8;MACOSX_DEPLOYMENT_TARGET=10.9;PATH=/Users/distiller/project/miniconda/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
11:55:17 BIOCONDA ERROR BUILD SUMMARY: of 1 recipes, 1 failed and 0 were skipped. Details of recipes and environments follow.
11:55:17 BIOCONDA ERROR BUILD SUMMARY: FAILED recipe heinz-2.0-0.tar.bz2, environment CONDA_PY=27;CONDA_HTSLIB=1.7;CONDA_BOOST=1.64;CONDA_R=3.4.1;CONDA_PERL=5.22.0;CONDA_NPY=112;CONDA_NCURSES=5.9;CONDA_GSL=1.16;CONDA_GMP=5.1;CONDA_HDF5=1.8.17;MACOSX_DEPLOYMENT_TARGET=10.9;CONDA_ZLIB=1.2.11;CONDA_BZIP2=1.0;CONDA_XZ=5.2;CONDA_BAMTOOLS=2.4.1
Exited with code 1
```

**Comment by daler** [comment]
What is the exit code of running `heinz --help`?

**Comment by CicoZhang** [comment]
@daler At first I use the test command `heinz --help`, the exit code of which is 1; which failed test-linux. 
Then I changed the test command to `heinz -version`, the exit code of which is 0; which passed text-linux, but failed test-macos.

**Comment by daler** [comment]
@CicoZhang couple things here:
- for future reference you can explicitly test for exit code 1 with `heinz --help || [ "$?" == 1 ]`, but since `heinz -version` works too that's good
- the line failing on macOS is the [`cp -r` line](https://github.com/bioconda/bioconda-recipes/pull/8926/files#diff-f081f21e5a8d285780d3c3c466b35db0R1). I didn't realize macOS's `cp` didn't do recursive, but [this SO answer](https://superuser.com/questions/33268/cp-r-l-in-macos-recursive-copy-preserving-hard-links) has some things to try. You could also try `mv` to see if that works.

**Comment by CicoZhang** [comment]
@daler Thank you for the advice. This problem has been solved by using `mv` command instead of `cp`. Now I am hindered by `ld: symbol(s) not found for architecture x86_64` on Mac OS. I am looking into it.

**Comment by CicoZhang** [comment]
@daler I don't have a Mac OS to try actually, and I don't know how to fix it after a few rounds of trial and error in vain. I will appreciate if some assistance is provided. :smiley: 
```
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [print] Error 1
make[1]: *** [CMakeFiles/print.dir/all] Error 2
make: *** [all] Error 2
BUILD START: heinz-2.0-0
```

**Comment by daler** [comment]
@CicoZhang this is where we call in @bioconda/osx for backup!

**Comment by CicoZhang** [comment]
@daler @bioconda/osx What can I do to help?  :smiley:

**Comment by bgruening** [comment]
You could try using gcc also on OSX.

**Comment by CicoZhang** [comment]
@bgruening @daler @bioconda/osx 
Just tried 'gcc', still failed with the error message
```
Scanning dependencies of target print
[  8%] Building CXX object CMakeFiles/print.dir/src/printgraph.cpp.o
c++: error: unrecognized command line option ‘-stdlib=libstdc++’
make[2]: *** [CMakeFiles/print.dir/src/printgraph.cpp.o] Error 1
make[1]: *** [CMakeFiles/print.dir/all] Error 2
make: *** [all] Error 2
```

**Pull request closed without merging**
