### PR TITLE
Update msmetaenhancer: Remove dependency boundaries

### PR DESCRIPTION
**Pull request by xtrojak**
Simplified dependencies of `MSMetaEnhancer`.

### CODE REVIEW

**Comment by xtrojak** [comment]
@BiocondaBot please add label

**Comment by bgruening** [comment]
Can you explain why this is needed, or better do you know why this was added in the first place?

**Comment by xtrojak** [comment]
> Can you explain why this is needed, or better do you know why this was added in the first place?

@bgruening That is an excellent question! In the early stages of the package development, we decided to limit allowed python versions. However, it became unclear why this was needed (I think some issues with `matchms` requirement), so we decided to mitigate these restrictions. Also, it seems to be causing extensive memory consumption during the installation process, which we want to [eliminate](https://github.com/RECETOX/MSMetaEnhancer/issues/106).

**Comment by martenson** [comment]
I suspect making the version req something like `python >=3.9` will limit the search space for dependencies and help the performance of `conda create/install` commands. We probably do not want to support Python 3.6 and such anyways.

**Comment by bgruening** [comment]
Does msmetaenhancer-0.2.3-pyh5e36f6f_1.tar.bz2 work with all python version you would like to support?

**Review by bgruening — APPROVED** [review]

**Comment by xtrojak** [comment]
I actually double-checked it locally, and it seems like there are some issues due to some matchms dependencies with python under `3.8`, so I reintroduced the lower bound and changed it to `>=3.8`.

**Comment by bgruening** [comment]
@BiocondaBot please merge

thanks for checking

**Comment by xtrojak** [comment]
@bgruening thank you for your time!

**Comment by bgruening** [comment]
Your welcome!

**Pull request merged**
