### PR TITLE
Update phate to 1.0.2

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`phate`](https://bioconda.github.io/recipes/phate/README.html): **0.4.5** &rarr; **1.0.2**

[install with bioconda](http://bioconda.github.io/recipes/phate/README.html) [Conda](https://anaconda.org/bioconda/phate/files)

Info | Link
-----|-----
Recipe | [`recipes/phate`](https://github.com//bioconda/bioconda-recipes/tree/bump/phate/recipes/phate) (click to view/edit other files)
Releases |[https://pypi.org/pypi/phate/json](https://pypi.org/pypi/phate/json)

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by dpryan79** [comment]
sgdpy needs to be added to conda-forge

**Comment by npavlovikj** [comment]
@BiocondaBot please fetch artifacts

**Comment by npavlovikj** [comment]
@BiocondaBot please merge

**Comment by npavlovikj** [comment]
@cbrueffer , I can not "approve" your requested changes for some reason, so if you can approve them and/or merge the recipe, that would be great.
Happy Holidays!

**Comment by dpryan79** [comment]
@bioconda-bot please merge

Thanks @npavlovikj!

**Comment by npavlovikj** [comment]
Anytime @dpryan79  :)

**Pull request merged**
