### PR TITLE
Updated msstitch version 2.2 to 2.3

### PR DESCRIPTION
**Pull request by glormph**
* [X] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [X] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by nsoranzo** [comment]
@glormph Can you please submit pull requests from your fork of https://github.com/bioconda/bioconda-recipes/ instead of a branch? This will save a Travis build (the one named continuous-integration/travis-ci/push above). Thanks a lot!

**Comment by glormph** [comment]
Sorry Nicola, will do (next time I assume).

**Comment by nsoranzo** [comment]
@glormph Sure, next time is fine! Thanks.

**Comment by bgruening** [comment]
Great thanks! @nsoranzo feel free to merge.

**Pull request merged**
