### PR TITLE
Move older bcbiogff versions to bcbio-gff

### PR DESCRIPTION
**Pull request by npavlovikj**
:information_source:
If this is your first pull request to Bioconda please ping `@bioconda/core` so it can be reviewed and to request being added as a member of the Bioconda team. Members of the Bioconda team are able to merge their own pull requests once tests and linting have passed.

----------------

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

The "bcbiogff" package is renamed to "bcbio-gff" according to https://github.com/bioconda/bioconda-recipes/issues/14758. Some of the recipes that need to be updated are using older "bcbio-gff" versions, and thus this PR.

### CODE REVIEW

**Comment by npavlovikj** [comment]
@druvus , since you are working on renaming "bcbiogff", is this PR ok with you? 
This way, all "bcbiogff" versions will be switched to "bcbio-gff", and after the recipes you have listed in your issue are updated, "bcbiogff" can be removed as a package, and from the nightly uploads (https://github.com/bioconda/bioconda-recipes/issues/15196) as well.

**Comment by druvus** [comment]
@npavlovikj thanks, it will speed up the process! Looks good to me. Just reset build numbers to 0 for both recipes.

**Comment by npavlovikj** [comment]
Thanks for the feedback @druvus !

**Comment by npavlovikj** [comment]
@BiocondaBot merge

**Pull request merged**
