### PR TITLE
Update r-dartr to 1.1.11

### PR DESCRIPTION
**Pull request by epruesse**
Update [`r-dartr`](https://bioconda.github.io/recipes/r-dartr/README.html): **1.0.5** &rarr; **1.1.11**

[install with bioconda](http://bioconda.github.io/recipes/r-dartr/README.html) [Conda](https://anaconda.org/bioconda/r-dartr/files)

Info | Link
-----|-----
Recipe | [`recipes/r-dartr`](https://github.com//bioconda/bioconda-recipes/tree/bump/r_dartr/recipes/r-dartr) (click to view/edit other files)
Releases |[https://crandb.r-pkg.org/dartR/all](https://crandb.r-pkg.org/dartR/all)

***

**Note:** Upstream dependencies appear to have changed

```diff
  host:
-   - r-dbi 
-   - r-demerelate 
+   - r-gdistance 
+   - r-hierfstat 
+   - r-igraph 
+   - r-leaflet 
-   - r-misc3d 
+   - r-mmod 
-   - r-plotly 
+   - r-popgenreport 
-   - r-quadprog 
-   - r-rgl 
+   - r-rrblup 
  run:
-   - r-dbi 
-   - r-demerelate 
+   - r-gdistance 
+   - r-hierfstat 
+   - r-igraph 
+   - r-leaflet 
-   - r-misc3d 
+   - r-mmod 
-   - r-plotly 
+   - r-popgenreport 
-   - r-quadprog 
-   - r-rgl 
+   - r-rrblup 

```
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/updating.html)).

### CODE REVIEW

**Comment by jenzopr** [comment]
ERROR: dependencies ‘rrBLUP’, ‘leaflet’, ‘mmod’, ‘PopGenReport’, ‘gdistance’, ‘hierfstat’ are not available for package ‘dartR’

**Comment by jenzopr** [comment]
Missing packages in Conda:
 
- r-gdistance
- r-rrblup
- r-mmod
- r-popgenreport
- r-hierfstat

**Comment by epruesse** [comment]
This one goes on the blacklist then.

**Comment by epruesse** [comment]
Hmm. Or not. It builds as it is. It's just that the update won't build. Guess we leave this open for now.

**Comment by jenzopr** [comment]
My plan is to bring the missing packages in conda-forge (`r-gdistance`, `r-hierfstat`) or bioconda (`r-rrblup`, `r-mmod`, `r-popgenreport`) then.

**Comment by epruesse** [comment]
Nice! Ok then, leaving this open. You can have multiple recipes in a single PR against staged-recipes if that helps. You can also mention this PR and ping bgruening - that should speed the merge up.

**Comment by jenzopr** [comment]
Reminder for @dpryan79 to look into libGL ;-)

**Comment by dpryan79** [comment]
I'll have to figure out why the linter is throwing up later, it shouldn't (this is similar to the conda-forge recipes like r-pca3d). At the moment this is still missing `libXfixes.so`, which I don't recall being missing before.

**Comment by dpryan79** [comment]
When we get this working I really need to add stuff about `libGL` to the documentation. This is missing on conda-forge too, so unless people stumble upon the r-rgl package recipe or (better) something like r-pca3d then they have no chance of figuring this out.

**Comment by dpryan79** [comment]
All but the mulled test works now.

**Comment by jenzopr** [comment]
Hurray! :tada:
Thank you very much @dpryan79

**Pull request merged**
