### PR TITLE
ViennaRNA 2.4.1

### PR DESCRIPTION
**Pull request by martin-mann**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [ ] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by martin-mann** [comment]
@bgruening Hi Björn, do you have an idea? The Travis linting crashes about the old (to be replaced) version 2.3.5 ...

**Comment by dmaticzka** [comment]
i think the summary tag has to be indented once

**Comment by martin-mann** [comment]
@dmaticzka thanks again!

**Comment by martin-mann** [comment]
@s-will maybe interesting for locarna due to extended constraint interface

**Comment by mmiladi** [comment]
@martin-mann Thanks. @s-will prepared a patch for fixing RNAlocmin. I'll continue adding the patch.

**Comment by martin-mann** [comment]
@mmiladi not sure if needed and worth the effort. I guess Ronny will come up with a patch release at some time.. ;) and RNAlocmin is a newly added gimmick anyway, so Ronny should/will be eager to get it public.

**Comment by mmiladi** [comment]
Alright ;)

**Comment by mmiladi** [comment]
Also If you were curious this is the fix :) 

```
diff --git a/src/RNAlocmin/main.cpp b/src/RNAlocmin/main.cpp
index 455af03c..43e2722a 100644
--- a/src/RNAlocmin/main.cpp
+++ b/src/RNAlocmin/main.cpp
@@ -10,6 +10,7 @@
 #include <map>
 #include <vector>
 #include <algorithm>
+#include <memory>
 
 extern "C" {
   #include "fold.h"
@@ -363,7 +364,7 @@ int main(int argc, char **argv)
       threshold = (thr<0 ? 0 : tmp[thr]);
 
       // nodes
-      nodeT nodes[num];
+      std::unique_ptr<nodeT []> nodes(new nodeT[num]);
       energy_barr = (float*) malloc(num*num*sizeof(float));
       for (int i=0; i<num*num; i++) energy_barr[i]=1e10;
       findpath_barr = (bool*) malloc(num*num*sizeof(bool));
@@ -504,10 +505,10 @@ int main(int argc, char **argv)
         //PS_tree_plot(nodes, num, "tst.ps");
 
         // make tree (fill missing nodes)
-        make_tree(num, energy_barr, findpath_barr, nodes);
+        make_tree(num, energy_barr, findpath_barr, nodes.get());
 
         // plot it!
-        PS_tree_plot(nodes, num, args_info.barr_name_arg);
+        PS_tree_plot(nodes.get(), num, args_info.barr_name_arg);
       }
 
       // time?
```

**Comment by s-will** [comment]
Hi @mmiladi / @martin-mann , why are you not just adding my patch (and activate locmin) again --- it is not hard to do this, so why wait for the next release?

**Comment by martin-mann** [comment]
@s-will just laziness... ;)

**Comment by mmiladi** [comment]
:laughing: I'll do it

**Comment by mmiladi** [comment]
@martin-mann @s-will Could u please have a look this PR then merge? Merc

https://github.com/bioconda/bioconda-recipes/pull/5994

**Pull request merged**
