### PR TITLE
Update Sambamba to 0.6.9

### PR DESCRIPTION
**Pull request by cbrueffer**
:information_source:
If this is your first pull request to Bioconda please ping `@bioconda/core` so it can be reviewed and to request being added as a member of the Bioconda team. Members of the Bioconda team are able to merge their own pull requests once tests and linting have passed.

----------------

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by cbrueffer** [comment]
@dpryan79 I saw you already had a Sambamba 0.6.9 update PR (https://github.com/bioconda/bioconda-recipes/pull/14070) but closed it. Did you have the same problem with excessive build times as I do here?

**Comment by dpryan79** [comment]
I think the issue had to do with ldc actually, but I’d have to look when I’m back in the office later in the week.

**Comment by dpryan79** [comment]
Update: yes, I had the exact same issue with the long build time. I'll have a look at this locally today.

**Comment by dpryan79** [comment]
The `git clone` step never finishes :(

**Comment by dpryan79** [comment]
It's a hack, but my last changes get around the endless `git clone`.

**Comment by cbrueffer** [comment]
Thanks Devon!

**Pull request merged**
