### PR TITLE
Add rdkit 2012.12.1

### PR DESCRIPTION
**Pull request by leobiscassi**
* [x] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

Add rdkit version 2012.12.1

### CODE REVIEW

**Comment by bgruening** [comment]
@leobiscassi let's just update the wrappers and skip this build. It's too old. What do you think?

**Comment by leobiscassi** [comment]
I think it's great! In fact, I have add this recipe because of this wrapper [1], but if I can update will be better. Can I update to rdkit 2016.03.3?

[1][https://github.com/bgruening/galaxytools/blob/master/chemicaltoolbox/chemfp/chemfp_mol2fps/mol2fps.xml](https://github.com/bgruening/galaxytools/blob/master/chemicaltoolbox/chemfp/chemfp_mol2fps/mol2fps.xml#L6)

**Comment by bgruening** [comment]
Yes please!

**Comment by leobiscassi** [comment]
Ok, thanks!

**Pull request closed without merging**
