### PR TITLE
Add Quicksnp 1.0.1

### PR DESCRIPTION
**Pull request by cjjossart**
Description:
This pull request adds the quicksnp package. This tool consists of a python script that builds a neighbor joining tree using only a SNP distance matrix (https://github.com/k-florek/QuickSNP). The goal is to package this script and use in a nextflow workflow.

Requirements:
pandas==1.4.3 
numpy==1.22.4
scikit-bio==0.5.7
scipy==1.8.0

Test build:
I was able to build this package successfully using:
bioconda-utils build --docker --mulled-test --git-range master

this is my first build so please reach out if there are any issues, concerns, and/or area for improvement. I did my best to follow other examples and bioconda documentation. Thanks!
----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by cjjossart** [comment]
requesting @rpetit3  for review

**Comment by cjjossart** [comment]
@rpetit3 Thanks for reviewing this!
I was able to loosen up pandas an numpy version, but the scipy package needed for the script to run properly is 1.8.0 or 1.10.1 (1.9.0 causes an issue with the code). For the scipy version 1.10.1, there is an issue with the build when running:
`bioconda-utils build --docker --mulled-test --git-range master`
This may be due to the version being a few days old.

The most recent version of scikit-bio requires scipy 1.9.0 or 1.10.1, thus scikit-bio 0.5.7.

**Comment by rpetit3** [comment]
@cjjossart I apologize I missed this one. Please ping me when the latest push passes

**Comment by cjjossart** [comment]
@rpetit3 No worries! All checks have passed. Thanks and reach out with any comments, questions or concerns.

**Review by rpetit3 — APPROVED** [review]

**Comment by rpetit3** [comment]
@BiocondaBot please merge

**Pull request merged**
