### PR TITLE
add cesm recipe

### PR DESCRIPTION
**Pull request by bgruening**
:information_source:
If this is your first pull request to Bioconda please ping `@bioconda/core` so it can be reviewed and to request being added as a member of the Bioconda team. Members of the Bioconda team are able to merge their own pull requests once tests and linting have passed.

----------------

* [ ] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [ ] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by bgruening** [comment]
ping @annefou

**Comment by annefou** [comment]
I am not sure how to test this one. I tested the one in your conda channel:

- mpich, gnu compiler and netcdf-fortran libraries need to be available when running/using the package too. The model is compiled by every single user when calling ./case.build for a given experiment.
- There are additional configuration files required for compiling a case but I guess galaxy will take care of them.

**Comment by bgruening** [comment]
@annefou I added a few more dependencies to the runtime environment, like the compiler etc....

I also changed the name ;)

We can include more config files in the package by copying them into the PREFIX location and if you want to have more binaries in your path we need to symlink it back to PREFIX/bin as we do here: https://github.com/bioconda/bioconda-recipes/pull/14530/files#diff-5dd3fa943324cba0d1328c7db80b25c7R12

**Comment by bgruening** [comment]
@annefou if the build succeeds, please have a look at the bot comment. It will offer you a URL how you can test this package :)

**Comment by bgruening** [comment]
@annefou `conda install -c https://51648-42372094-gh.circle-artifacts.com/0/tmp/artifacts/packages cesm`

**Comment by annefou** [comment]
Thanks. I have managed to install the new cesm package but gfortran is still not available:
/usit/abel/u1/annefou/python/anaconda3/envs/cesm_env/bin/mpif90: line 369: x86_64-conda_cos6-linux-gnu-gfortran: command not found

Do we need to add explicitely gfortran in the "run" section?

**Comment by bgruening** [comment]
> Do we need to add explicitely gfortran in the "run" section?

Yes :) Just did it.

**Comment by annefou** [comment]
Thanks!

**Comment by annefou** [comment]
To start compiling; I added:

conda install -c anaconda libxml2
conda install -c bioconda perl-xml-libxml
conda install -c conda-forge libiconv

Then I have another error related to ar command, but I did not manage to fix it yet!

**Comment by annefou** [comment]
And 
conda install -c anaconda make

**Comment by bgruening** [comment]
@annefou added :)

**Comment by annefou** [comment]
And two more for a successful build (however , I had to manually change a Makefile.conf file for ar to include rv; I am sure it can be fixed in a better way...).

~~~`bash`
conda install cmake
conda install -c conda-forge lapack
~~~

**Comment by bgruening** [comment]
@annefou how does your changes look like? Or what was the error? `ar` is part of the binutils packages that are coming with the compilers I think.

**Comment by bgruening** [comment]
Also if you have some more "programs" that we should include in the test section let me know or feel free to add them.

**Comment by epruesse** [comment]
The new conda compiler packages do come with `ar`, as usual as `$AR` not just in the `PATH`. You do need to call `$AR rv somelib.a someobj.o` - IIRC there are older versions of `ar` that can do without the options, but the modern GNU AR wants them.

**Comment by annefou** [comment]
with conda AR environment variable is defined so with cime/src/externals/mct/configure AR is not defined to "ar cq"

To fix it (maybe not very nice but it works), we can change cime/src/external/mct/configure (line 5267) from:

~~~`bash`
# ARCHIVE COMMAND SIMILAR ACROSS ALL PLATFORMS
if test -z "$AR"; then
   AR="ar cq"
fi
~~~

to:

~~~`bash`
# ARCHIVE COMMAND SIMILAR ACROSS ALL PLATFORMS
if test -z "$AR"; then
   AR="ar cq"
else
   AR="$AR cq"
fi
~~~

Or maybe you have a better idea?

**Comment by epruesse** [comment]
You could try if `AR="$AR rv"` suffices. Usually, `libtool` handles this kind of stuff if you build with `autotools` or `cmake`.

**Comment by annefou** [comment]
It works perfectly now! Thanks.

**Pull request merged**
