### PR TITLE
Update noise2read to 0.3.0

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`noise2read`](https://bioconda.github.io/recipes/noise2read/README.html): **0.2.10** &rarr; **0.3.0**

[install with bioconda](http://bioconda.github.io/recipes/noise2read/README.html) [Conda](https://anaconda.org/bioconda/noise2read/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/noise2read`](https://github.com//bioconda/bioconda-recipes/tree/bump/noise2read/recipes/noise2read) (click to view/edit other files)
Summary | Turn noise to read
Home | [https://github.com/Jappy0/noise2read](https://github.com/Jappy0/noise2read)
Releases |[https://pypi.org/pypi/noise2read/json](https://pypi.org/pypi/noise2read/json)
Recipe Maintainer(s) | @Jappy0

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Review by Jappy0 — CHANGES_REQUESTED** [review]
change the dependencies version and maintainer

**Review by Jappy0 — COMMENTED** [review]
change the maintainer

**Review by Jappy0 — APPROVED** [review]

**Comment by Jappy0** [comment]
@BiocondaBot hello

**Comment by Jappy0** [comment]
@BiocondaBot how to close this request

**Review by Jappy0 — APPROVED** [review]

**Review by Jappy0 — APPROVED** [review]
approve

**Comment by Jappy0** [comment]
The Recipe Maintainer(s) above is not correct. And I also modified the dependencies. I have tried here #43541. Thanks

**Review by mencian — APPROVED** [review]

**Pull request merged**
