### PR TITLE
Add kcounter

### PR DESCRIPTION
**Pull request by apcamargo**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences**
      (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by apcamargo** [comment]
@bioconda-bot please re-render

**Comment by apcamargo** [comment]
@BiocondaBot update

**Comment by apcamargo** [comment]
@bioconda-bot update

**Comment by apcamargo** [comment]
@BiocondaBot please update

**Comment by apcamargo** [comment]
@BiocondaBot rebuild

**Comment by apcamargo** [comment]
@bioconda-bot rebuild

**Comment by apcamargo** [comment]
@bioconda/core It took me some time to get the requirements into conda-forge, but the recipe builds fine now and the PR is ready for a merge.

**Comment by raivivek** [comment]
@bioconda-bot please fetch artifacts

**Comment by raivivek** [comment]
@bioconda-bot please merge

**Comment by raivivek** [comment]
Thanks @apcamargo

**Comment by apcamargo** [comment]
Thank you @raivivek!

**Pull request merged**
