### PR TITLE
Update goalign and gotree recipes: update go + build number

### PR DESCRIPTION
**Pull request by fredericlemoine**
Updates go for goalign and gotree recipes.

### CODE REVIEW

**Comment by fredericlemoine** [comment]
@BiocondaBot please add label

**Review by corneliusroemer — APPROVED** [review]
Sorry, I misunderstood what this commit does, reset build number to 1

**Comment by corneliusroemer** [comment]
@BiocondaBot please merge

**Comment by corneliusroemer** [comment]
@BiocondaBot please merge

**Comment by fredericlemoine** [comment]
Thank you!

**Pull request merged**
