### PR TITLE
Update protgraph to 0.3.1

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`protgraph`](https://bioconda.github.io/recipes/protgraph/README.html): **0.3.0** &rarr; **0.3.1**

[install with bioconda](http://bioconda.github.io/recipes/protgraph/README.html) [Conda](https://anaconda.org/bioconda/protgraph/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/protgraph`](https://github.com//bioconda/bioconda-recipes/tree/bump/protgraph/recipes/protgraph) (click to view/edit other files)
Summary | ProtGraph, a graph generator for proteins.
Home | [https://github.com/mpc-bioinformatics/ProtGraph](https://github.com/mpc-bioinformatics/ProtGraph)
Releases |[https://pypi.org/pypi/protgraph/json](https://pypi.org/pypi/protgraph/json)
Recipe Maintainer(s) | @Luxxii

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Review by Luxxii — APPROVED** [review]

**Comment by Luxxii** [comment]
@BiocondaBot please add label

**Review by cbrueffer — APPROVED** [review]

**Comment by cbrueffer** [comment]
@bioconda-bot please merge

**Comment by cbrueffer** [comment]
@Luxxii you can merge these bot-raised update PR yourself as well after you've reviewed them.

**Comment by Luxxii** [comment]
@cbrueffer oh i did not know. Thanks for the info!

**Pull request merged**
