### PR TITLE
Update blast adding rpsbproc among blast tools

### PR DESCRIPTION
**Pull request by Juke34**
Update blast, to add rpsbproc among blast exes

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by Juke34** [comment]
I remove what I have added to check if it is the osx env that has changed (and fails) or if it is really what I have added

**Comment by npavlovikj** [comment]
I think that is because of the change of macOS SDK. https://github.com/bioconda/bioconda-recipes/pull/20874 may have more details.

**Comment by Juke34** [comment]
Using Clang9 compile for me locally.

**Comment by Juke34** [comment]
@BiocondaBot update

**Comment by Juke34** [comment]
PR replaced by #22777

**Comment by mbargull** [comment]
@Juke34, I pushed to your `blast` branch but that didn't update this PR since it shows (unknown repository)[https://github.com/bioconda/bioconda-recipes/tree/rpsbproc] as the source.

**Comment by mbargull** [comment]
ah nvm

**Comment by Juke34** [comment]
Yes I don't know what I did to end in this state... so I decided to start cleanly with PR 22777

**Pull request closed without merging**
