### PR TITLE
Update nanoplot to 1.35.4

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`nanoplot`](https://bioconda.github.io/recipes/nanoplot/README.html): **1.32.1** &rarr; **1.35.4**

[install with bioconda](http://bioconda.github.io/recipes/nanoplot/README.html) [Conda](https://anaconda.org/bioconda/nanoplot/files)

Info | Link
-----|-----
Recipe | [`recipes/nanoplot`](https://github.com//bioconda/bioconda-recipes/tree/bump/nanoplot/recipes/nanoplot) (click to view/edit other files)
Releases |[https://pypi.org/pypi/NanoPlot/json](https://pypi.org/pypi/NanoPlot/json)

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by cbrueffer** [comment]
Needs a recipe for https://pypi.org/project/kaleido/ in conda-forge.

**Comment by wdecoster** [comment]
Related: https://github.com/conda-forge/staged-recipes/pull/12093

**Review by wdecoster — APPROVED** [review]

**Comment by dpryan79** [comment]
@mbargull Do we have any hope of fixing things when there are conflicting glibc requirements? Is this maybe related to the older miniconda version we have or is this CI infrastructure related?

**Comment by mbargull** [comment]
I need to update our build container to use a CentOS 7 base (we'll still be building against the CentOS 6 sysroot) for this to not fail during the build.

**Comment by wdecoster** [comment]
Does anyone have a suggestion on how to fix this?

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Comment by wdecoster** [comment]
wooooohooo :-D

**Pull request merged**
