### PR TITLE
Add script analyze_diff_expr.pl. Increase build. Add tests.

### PR DESCRIPTION
**Pull request by loraine-gueguen**
* [x] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

Make trinity script analyze_diff_expr.pl available.

### CODE REVIEW

**Comment by loraine-gueguen** [comment]
@lecorguille Travis tests failing ...

**Comment by loraine-gueguen** [comment]
The travis test on linux platform has failed. I am not really understanding the error logs:
`/home/travis/build.sh:` line 112:  3216 Terminated              travis_jigger $! $timeout $cmd'

Has someone any clue what is happening?
Thanks

**Comment by daler** [comment]
That line you're referring to is our kind of hacky way of increasing the timeout on travis-ci -- all builds have that.  The actual error is at https://travis-ci.org/bioconda/bioconda-recipes/jobs/166777501#L387. And I don't know why we're getting that error, that's part of the build system and according to this log it looks like it's not being set.

But for example this travis-ci build https://travis-ci.org/bioconda/bioconda-recipes/jobs/168914732#L244 has bioconda-utils set correctly.

For now you can try merging in changes from master and restarting the build. Unfortunately travis-ci is very slow recently, might take a while.

**Comment by loraine-gueguen** [comment]
@daler Ok, thanks I try again with a merge from upstream

**Comment by loraine-gueguen** [comment]
@daler passed!

**Comment by lecorguille** [comment]
@loraine-gueguen Heu ... green but I guess you should have this kind of line
`2016-10-20 09:42:45,171:INFO:bioconda_utils.utils:Successfully built recipes/trinity/`

**Comment by loraine-gueguen** [comment]
@lecorguille Yes indeed. Do you see what is wrong? I can't figure out what's happening.

**Comment by daler** [comment]
@bgruening @johanneskoester do you understand what's going on here? Looking at the logs there are build errors, but in the end the script still has exit code 0 so travis-ci says OK. But it's not.

Looking at previous PRs' logs, gvcftools keeps coming up as an error, e.g., https://github.com/bioconda/bioconda-recipes/pull/2646. So I bet gvcftools was merged in incorrectly due to this false positive issue. gvcftools was merged Oct 12, so we may have been having issues since then.

**Comment by daler** [comment]
@loraine-gueguen can you rebase with master and try again please?

**Comment by loraine-gueguen** [comment]
There is an issue with the build of dependance parafly. Waiting for merge: #2693

**Comment by loraine-gueguen** [comment]
Switch to cleaner pull request #2711

**Pull request closed without merging**
