### PR TITLE
nanopolish out of blacklist

### PR DESCRIPTION
**Pull request by mmiladi**
* [ ] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [ ] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by bgruening** [comment]
You should probably use `https://anaconda.org/conda-forge/toolchain_c_linux-64` and `toolschain_cxx_linux-64` on OSX as well.

**Comment by bgruening** [comment]
For that add https://github.com/bioconda/bioconda-recipes/blob/master/recipes/mawk/conda_build_config.yaml into the repo and specify `toolchain_c_linux-64` and  `toolchain_cxx_linux-64`. Not sure if this will work :(

**Comment by mmiladi** [comment]
Thanks for the hints@bgruening. So do you mean to not use clang?

`https://anaconda.org/conda-forge/toolchain_c_linux-64` has files only for linux. How can they be deployed on OSX? :-|

**Comment by rob-p** [comment]
I was seeing the same thing [here](https://github.com/bioconda/bioconda-recipes/pull/10344).  I'd love to use GCC/G++ on OSX if it is possible.  The clang is from the OSX 10.9 SDK, so it's pretty old and a bit quirky.

**Comment by bgruening** [comment]
@rob-p I don't love it. But can you do as I did here for salmon as well?

**Comment by rob-p** [comment]
@bgruening : So is there a way to use the new gcc on linux and 4.8.5 on OSX?  If not, I guess we can temporarily revert and force to use 4.8.5 on both platforms.

**Comment by bgruening** [comment]
Oh yes, sorry. This is using old GCC on Linux and OSX. Old not new, sorry.

**Comment by mmiladi** [comment]
@bgruening Thanks a bunch!

**Pull request merged**
