### PR TITLE
Add recipe for blast-legacy 2.2.22

### PR DESCRIPTION
**Pull request by acaprez**

### CODE REVIEW

**Comment by johanneskoester** [comment]
Hi,
what do you mean with legacy here? Is it just an old version of blast? Then, you can use a subdirectory of the current blast recipe. It also seems to be conflicting with the blast recipe. So a different version of the same package really seems to be the better way here.

**Comment by bgruening** [comment]
Afaik, BLAST legacy is a used common name for the old/original C based BLAST tools. The newer ones are called BLAST+ and are written in C++.

**Comment by johanneskoester** [comment]
Ok, that makes sense.

**Comment by acaprez** [comment]
Hi,
Yes - `blast-legacy` is the original BLAST.  The `blast` that's in the repo is the newer BLAST+ package.  Unfortunately, they overlapped the version numbers between the two, so having different names is needed.  Where's the conflict with the blast recipe?  I'm afraid I don't see that.

**Comment by johanneskoester** [comment]
Me neither, I accidentally looked at the same recipe two times ;-). I'm fine with your choice, sorry for the noise.

**Comment by acaprez** [comment]
Sure - no problem.

**Pull request merged**
