### PR TITLE
mixer update to version 3.0.5

### PR DESCRIPTION
**Pull request by jj-umn**
:information_source:
Bioconda has finished the [GCC7 migration](https://github.com/bioconda/bioconda-recipes/issues/13578). If you are dealing with C/C++ or Python package it can be that you need to rebuild other dependent packages. [Bioconda utils - update-pinning](https://bioconda.github.io/updating.html#updating-recipes-for-a-pinning-change) will assist you with that. If you have any questions please use [issue 13578](https://github.com/bioconda/bioconda-recipes/issues/13578).

----------------

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by jj-umn** [comment]
@bgruening   This is failing in the mulled build test.   The mixcr bash script checks for the version of java, which must be 9.0 or greater.   When invoking the mulled container, the script exits because the java version is less than 9.   I presume that there must be a java executable in the PATH before the openjdk one when invoking this.   I am not sure how to verify this or correct it.   
A secondary problem might arise in that the mixcr script is checking for free memory to set the _Xmx var for java.  The mixcr script presumes there will more than 100 Mb of free space.  This might not be the case in the test container.  
Let me know if there is somebody else that I should ask about this.

**Comment by dpryan79** [comment]
It's pulling in openjdk 11, I wonder if the shell script from mixcr is just wrong.

**Comment by bgruening** [comment]
@jj-umn I know what is and trying to fix it.

**Comment by jj-umn** [comment]
@bgruening   Excellent.   Were there issues with openjdk 9 & 10?

**Comment by bgruening** [comment]
No, the error was the conda-forge package there was a missing zlib dependency. I fixed that upstream.

**Comment by bgruening** [comment]
Thanks JJ!!! Hope you are well again and plan your trip to Europe in summer! :)

**Comment by jj-umn** [comment]
@bgruening  Thanks.  I  am getting better.  I finally have an appetite again, and some whiskers are starting to grow.   I'm hoping that means the neurons are recovering as well.   I have a full set of tests on April 17, and should get some recommendations for the future in the following week.

**Comment by bgruening** [comment]
All the very very best JJ!

**Pull request merged**
