### PR TITLE
Salmon v0.12.0 --- version bump and fix OSX build

### PR DESCRIPTION
**Pull request by rob-p**
* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [X] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [X] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by rob-p** [comment]
Well, that failure in TBB is new ...

**Comment by dpryan79** [comment]
You probably want to ping /lib rather than /all next time :)

**Comment by rob-p** [comment]
Good call (fixed, but too bad I already pinged too many ppl).  Are there other packages using libtbb?  Seemingly, they should all suffer from this problem if using the new compilers.

**Comment by dpryan79** [comment]
There are only 8 bioconda packages (including salmon and sailfish) using tbb. I think flexbar is using new compilers with tbb too, but I'm not overly familiar with it.

**Comment by epruesse** [comment]
You should only need `tbb-devel` in `requirements/build`. It `run_exports` the `tbb` package, so like zlib, it'll be included and pinned automatically.

**Comment by rob-p** [comment]
Is there a way to skip linting?

**Comment by epruesse** [comment]
No ... I wonder what's going on.

**Comment by dpryan79** [comment]
It passed this time at least

**Comment by rob-p** [comment]
man, this linter is really a PITA.

**Comment by PertuyF** [comment]
Looks like it is possible to [skip linting](https://bioconda.github.io/linting.html#skipping-persistently-on-a-per-recipe-basis), at least part of it.
Requires some investigation on how to use it though.

**Comment by PertuyF** [comment]
Error comes from [there](https://github.com/bioconda/bioconda-utils/blob/7cbde1cd8bdb61b0f4d7beff4b3cbe999d31a29e/bioconda_utils/linting.py#L123), and `bioconda-utils.linting.channel_dataframe()` is used by `[bioconda-utils.cli.lint()](https://github.com/bioconda/bioconda-utils/blob/d54a6d8bbd9f23e2bc7967030170c4e12369dc58/bioconda_utils/cli.py#L228)`. So I guess there is no specific linter function we can skip here.
There may be some problem in JSON objects returned from `bioconda-utils.utils.get_channel_repodata()`?

Could it be a global problem from `bioconda-utils`?

**Comment by apcamargo** [comment]
https://github.com/bioconda/bioconda-utils/pull/362

This PR should fix the linter problems.

**Comment by daler** [comment]
Thanks to @dpryan79 in bioconda/bioconda-utils#362 the lint is now passing!

**Comment by rob-p** [comment]
The linting (and linux build) succeed now.  However, I noticed the following warnings after a successful build:

```
The update_index function has changed to index all subdirs at once.  You're pointing it at a single subdir.  Please update your code to point it at the channel root, rather than a subdir.
WARNING:conda_build.index:The update_index function has changed to index all subdirs at once.  You're pointing it at a single subdir.  Please update your code to point it at the channel root, rather than a subdir.
The update_index function has changed to index all subdirs at once.  You're pointing it at a single subdir.  Please update your code to point it at the channel root, rather than a subdir.
WARNING:conda_build.index:The update_index function has changed to index all subdirs at once.  You're pointing it at a single subdir.  Please update your code to point it at the channel root, rather than a subdir.
..
```

should we be concerned about these?

**Comment by dpryan79** [comment]
The warning can be ignored, it’s just due to the directory passed to conda index.

**Pull request merged**
