### PR TITLE
Update Du Novo: Initial version of 3.0 support.

### PR DESCRIPTION
**Pull request by NickSto**
I'm trying to make a package for Du Novo 3.0. The new tool version has a new dependency: BioPython.

I've also added a few other dependencies which it always depended on but weren't specified before, like samtools, bash, and a number of unix utilities.

I've had a lot of trouble getting this to build and run. I logged one problem in #32718. Based on @bgruening's suggestion, I pinned `tbb`, but even then, it still doesn't run properly unless I first manually install an old version of `tbb` in the conda environment (so far I've only tried 2018.0.3). But it sounds like this might just be my machine?

### CODE REVIEW

**Comment by dpryan79** [comment]
Do you strictly require bowtie 1.2.* or would 1.3 also work? The metadata for 1.2 requires patching and Anaconda has yet to enable that for our channel.

**Comment by NickSto** [comment]
Du Novo works with 1.0.0 up to 1.3.1, as far as I know. The version restriction for `bowtie` is simply what I could get to build and run. If anyone wants to take a crack at changing it, be my guest. I couldn't get anything else to work.

**Comment by NickSto** [comment]
Oh, FYI there's also Makefiles in the `bfx` and `kalign` subdirectories that get executed.

I can also alter those Makefiles. What's the best practice here, to allow setting the `$(CC)` from outside? Is there a way to let it get set from an environment variable?

**Comment by bgruening** [comment]
Yes, $CC should be configurable, also it would help you I think if you release complete tarballs with submodules included.

**Comment by NickSto** [comment]
> Yes, $CC should be configurable, also it would help you I think if you release complete tarballs with submodules included.

I agree! Is there a Github feature or would I have to manually make and host the tarball?

**Comment by bgruening** [comment]
https://github.community/t/create-release-that-contains-submodule/1329 You have to do this manually or on CI I think.

https://github.blog/2013-07-02-release-your-software/

**Comment by NickSto** [comment]
Okay, `$(CC)` is configurable and the submodules are bundled now. And it looks like it's passing the checks.

**Review by dpryan79 — APPROVED** [review]

**Pull request merged**
