### PR TITLE
update ruby with more pinning

### PR DESCRIPTION
**Pull request by bgruening**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by bgruening** [comment]
@notestaff if you have time, this recipe need to be migrated to conda-forge.

**Comment by notestaff** [comment]
Thanks for the fast fix!
I don't know ruby, so not sure I'd be the right conda-forge maintainer for
this recipe...

**Comment by bgruening** [comment]
I think I have programmed in ruby in 2008 the last time ;)

**Comment by notestaff** [comment]
@bgruening could the current error on Linux be the same as https://github.com/bioconda/bioconda-recipes/pull/4799 i.e. not specific to this recipe?

**Pull request merged**
