### PR TITLE
bioconductor-s4vectors/meta.yaml: update to 0.12.0

### PR DESCRIPTION
**Pull request by dyusuf**
* [x] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by dyusuf** [comment]
@bgruening Travis testing failed not because of my recipe but due to "FAILED recipe r-ahocorasicktrie-0.1.0-r3.3.1_0.tar.bz2" which is not part of my pull request. And it is not a required dependency of my recipe.

**Comment by bgruening** [comment]
We will fix this!

**Comment by dyusuf** [comment]
@bgruening thanks! :)

**Comment by bgruening** [comment]
@dyusuf we are still working on getting all R-packages from the r-blacklist.

**Comment by dyusuf** [comment]
@bgruening how the packages were selected for the black list?

**Comment by daler** [comment]
We needed to put *all* R packages on the blacklist to build for R 3.3.1 to avoid timing out on travis-ci. The list is in topologically sorted order so the top recipes do not depend on anything and the bottom recipes have lots of other R package dependencies and need to be built later. We have been systematically removing packages from the blacklist and rebuilding for R 3.3.1. It takes a long time, especially with fixing problems on osx . . .

**Comment by dyusuf** [comment]
ok.... if you guys need any help, I could contribute as well.

**Comment by bgruening** [comment]
@dyusuf please do so. For example all blacklisted packages needs to be checked of the URL still exists and if not the URL needs to be updated

**Comment by daler** [comment]
Thanks @dyusuf. Also see #2799 for some places to start.

**Comment by dyusuf** [comment]
sure, I am building the package for a tool which we have developed. Some of the dependencies are blacklisted. I could start with them first. then to see if we could help out #2799  cheers.

**Pull request merged**
