### PR TITLE
De-blacklist bioconductor-kegggraph

### PR DESCRIPTION
**Pull request by vodkatad**
* [x] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [x] This PR does something else (explain below).

Removes bioconductor-kegggraph from the blacklist and bump its build version.

### CODE REVIEW

**Comment by daler** [comment]
@vodkatad as part of the ongoing migration to R3.3 this is already in #2710 (along with some other related recipes), so if you want you can wait until that PR builds.

**Comment by vodkatad** [comment]
Woops, sorry, I'm fairly new to the whole bioconda thing and wanted to try out a single package to start with to know how everything (well...something) works before the contribution fest but forgot to check other pull requests, sorry. I can definitely wait.

**Comment by bgruening** [comment]
@vodkatad thanks for testing around with bioconda! And glad you are joining next week. For the hackathon it might be very useful if you could use your own branch for testing. As many people will submit PR during the hackathon (hopefully) and then travis will take hours.

Nevertheless, this PR looks good. Can you set the build number back to 0? Because we will build this package against a new R version the build-version will change to something like `r3.3.1_0` and we do no need to increase the version extra.

**Comment by vodkatad** [comment]
Yep, I'll fix the build-version tomorrow - thanks for the explanation, I need a learn conda in x minutes :) I have my fork and I am testing everything locally with conda-utils and I wanted to check what happened here before the hackathon frenzy on the real travis because, I have to admit, I looked online and I am not sure how to set up a local travis or link an indipendent one to my fork on github - if I link a new travis CI to my fork will it work? It seemed too free as in beer and I did not believe it but right now that I linked it this seems to be the case.

**Comment by bgruening** [comment]
@vodkatad thanks a lot!

**Pull request merged**
