### PR TITLE
added recipe for tbl2asn-forever

### PR DESCRIPTION
**Pull request by rpetit3**
The most recent version of tbl2asn (v25.8) is not compatible at the moment (See: https://github.com/bioconda/bioconda-recipes/pull/19790)

This recipe implements [tbl2asn-forever](https://github.com/audy/tbl2asn-forever) (thanks @audy and @milot-mirdita!) and is meant as a drop in replacement to tbl2asn. Using libfaketime (thanks @pvanheus!) a wrapper is created to trick tbl2asn (v25.7) into thinking it is always 2019-01-01. 

A consequence of this approach is, the files created by tbl2asn-forever will have the date set to 01-JAN-2019 instead of the actual date. 

----

> Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it.

* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [X] This PR adds a new recipe.
* [X] AFAIK, this recipe **is directly relevant to the biological sciences**
      (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

> Everyone has access to the following BiocondaBot commands, which can be given in a comment:
>
>  * `@BiocondaBot please update` will cause the BiocondaBot to merge the master branch into a PR
>  * `@BiocondaBot please add label` will add the `please review & merge` label.
>  * `@BiocondaBot please fetch artifacts` will post links to packages and docker containers built by the CI system. You can use this to test packages locally before merging.
>
> For members of the Bioconda project, the following command is also available:
>
>  * `@BiocondaBot please merge` will cause packages/containers to be uploaded and a PR merged. Someone must approve a PR first! This has the benefit of not wasting CI build time required by manually merging PRs.
>
> If you have questions, please post them in gitter or ping `@bioconda/core` in a comment (if you are not able to directly ping `@bioconda/core` then the bot will repost your comment and enable pinging).

### CODE REVIEW

**Comment by rpetit3** [comment]
@BiocondaBot please add label

**Comment by rpetit3** [comment]
@BiocondaBot please fetch artifacts

**Comment by dpryan79** [comment]
@bioconda-bot please merge

I hope mucking with the time doesn't have unforeseen consequences.

**Comment by rpetit3** [comment]
@dpryan79 Agreed, it "should" only affect the tbl2asn execution. I only know of it with regards to Prokka and that should be an easy thing to test to make sure there is no weird time issues.

**Pull request merged**
