### PR TITLE
Update seqsero2 to 1.1.1

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`seqsero2`](https://bioconda.github.io/recipes/seqsero2/README.html): **1.1.0** &rarr; **1.1.1**

[install with bioconda](http://bioconda.github.io/recipes/seqsero2/README.html) [Conda](https://anaconda.org/bioconda/seqsero2/files)

Info | Link
-----|-----
Recipe | [`recipes/seqsero2`](https://github.com//bioconda/bioconda-recipes/tree/bump/seqsero2/recipes/seqsero2) (click to view/edit other files)
Releases |[https://github.com/denglab/SeqSero2/tags](https://github.com/denglab/SeqSero2/tags)
Recipe Maintainer(s) | @LSTUGA
Author | `@denglab`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by npavlovikj** [comment]
@BiocondaBot please fetch artifacts

**Comment by npavlovikj** [comment]
@BiocondaBot please merge

**Comment by npavlovikj** [comment]
@LSTUGA , I hope this version precedes 1.01. If there are still issues, the next thing you can try is to open another PR with the same version, but bump the build number to 1.

**Comment by LSTUGA** [comment]
@npavlovikj, Thanks! I give give it a try if the version 1.1.1 doesn't work.

**Comment by LSTUGA** [comment]
@npavlovikj, The version 1.1.1 did precede 1.01. Now the installaion of new version works. Thank you @npavlovikj @dpryan79 very much for your help!

**Comment by npavlovikj** [comment]
I am glad to hear that @LSTUGA 🎉

**Comment by dpryan79** [comment]
Great! I'm a bit surprised that worked so easily :)

**Comment by LSTUGA** [comment]
Thank you both! It's really a surprise...

**Pull request merged**
