### PR TITLE
added cudamat recipe [WIP]

### PR DESCRIPTION
**Pull request by ThomasWollmann**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [ ] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by bgruening** [comment]
```
nvcc -I/opt/conda/conda-bld/cudamat_1509612481190/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/include/python3.6m -c cudamat/cudamat.cu -o build/temp.linux-x86_64-3.6/cudamat/cudamat.o -O --ptxas-options=-v --compiler-options=-fPIC
error: command 'nvcc' failed with exit status 1
```

**Comment by ThomasWollmann** [comment]
@bgruening how can we get nvcc on our buildserver? Thought maybe cudatoolkit does the job.

**Comment by bgruening** [comment]
nvcc needs to have an NVIDIA at the host?

**Comment by ThomasWollmann** [comment]
At least the compiler.

**Comment by johanneskoester** [comment]
We  have made changes to our build system (migrated from Travis CI to  Circle CI). If you would like to continue working on this PR, please  reopen this PR and update with latest upstream/master.

**Pull request closed without merging**
