### PR TITLE
fix rnaquast

### PR DESCRIPTION
**Pull request by bernt-matthias**
currently broken container because of a bug in gmap (see https://github.com/bioconda/bioconda-recipes/pull/27820).

- https://github.com/bioconda/bioconda-recipes/pull/27840/commits/50b33144ac753e802bc2ec04b99dd497734d2920 adds a test (which failed as expected for `fa_coords` because the gmap PR was not merged yet https://app.circleci.com/pipelines/github/bioconda/bioconda-recipes/44050/workflows/96b3b47b-1c7f-488b-b679-d29190ae19e4/jobs/148905)

Describe your pull request here

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by bernt-matthias** [comment]
@BiocondaBot please fetch artifacts

**Review by dpryan79 — APPROVED** [review]

**Comment by bernt-matthias** [comment]
Hmm. I get a segfault. Asked upstream for help: https://github.com/ablab/rnaquast/issues/7

**Comment by bernt-matthias** [comment]
Actually the test also fails here. But this is somehow not recognized.

```
13:43:31 BIOCONDA INFO (ERR) [Apr  6 13:43:31] SOUT Aligning idba to Saccharomyces_cerevisiae.R64-1-1.75.dna.toplevel.upper...
13:43:32 BIOCONDA INFO (ERR) [Apr  6 13:43:32] SERR /bin/sh: line 1:    56 Segmentation fault      (core dumped) gmap -D /usr/local/bin/rnaQUAST_test_output/tmp -d Saccharomyces_cerevisiae.R64-1-1.75.dna.toplevel.upper /usr/local/share/rnaquast-2.2.0-2/test_data/idba.fasta --format=1 -t 1 -O > /usr/local/bin/rnaQUAST_test_output/tmp/idba.psl 2>> /usr/local/bin/rnaQUAST_test_output/logs/gmap.idba.err.log
13:43:32 BIOCONDA INFO (ERR) [Apr  6 13:43:32] SOUT log can be found in /usr/local/bin/rnaQUAST_test_output/logs/gmap.idba.err.log.
13:43:32 BIOCONDA INFO (ERR) [Apr  6 13:43:32] SERR ERROR! gmap failed for idba!
```

**Comment by dpryan79** [comment]
I'm not sure how it could have not thrown an error when there's a segfault, that's very odd.

**Comment by bernt-matthias** [comment]
> I'm not sure how it could have not thrown an error when there's a segfault, that's very odd.

seems to be an upstream bug .. I'm at it :)

**Comment by bernt-matthias** [comment]
Test seems to work with the previous gmap version. Is there a better way to restrict the version? I guess a comment at the sources would be nice, or?

**Comment by bernt-matthias** [comment]
@BiocondaBot please fetch artifacts

**Comment by bernt-matthias** [comment]
Is is expected that the macos build is so fast? I guess its because its python.

**Comment by bernt-matthias** [comment]
I verified with the Galaxy wrapper that the new conda package works.

**Comment by bernt-matthias** [comment]
@BiocondaBot please add label

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Pull request merged**
