### PR TITLE
Update dependencies for bioconductor-purecn

### PR DESCRIPTION
**Pull request by lbeltrame**
As discussed on the nf-core Slack, the current dependencies do not allow running PureCN with the complete functionality, in particular segmentation algorithms are missing and the command line scripts won't work.

This PR adds all optional dependencies, and adds tests so that at least the command line utilities can run without spewing out errors.

CC @rpetit3 @aldosr

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by lbeltrame** [comment]
@BiocondaBot please update

**Comment by rpetit3** [comment]
small typo `r-rjsonlite` -> `r-jsonlite`

For some reason I can't edit the file myself

**Comment by lbeltrame** [comment]
Fixed, sorry about that.

**Comment by lbeltrame** [comment]
@BiocondaBot please add label

**Comment by rpetit3** [comment]
@BiocondaBot please fetch artifacts

**Comment by rpetit3** [comment]
@lbeltrame if you want to, you can test the docker container here

**Comment by lbeltrame** [comment]
I'll give it a shot tomorrow. I have no doubts it will work, since I built my own from biocontainers with that exact package selection, but won't hurt to test it again.

**Comment by lbeltrame** [comment]
Manual tests with Docker (on our own data) are OK. @rpetit3 if you're good with it, I think this can be merged.

**Review by rpetit3 — APPROVED** [review]

**Comment by lbeltrame** [comment]
What's the next step after approval? Mostly because this PR is blocking a bunch of stuff elsewhere, like  https://github.com/nf-core/modules/pull/3132

**Review by rpetit3 — APPROVED** [review]

**Comment by rpetit3** [comment]
@BiocondaBot please merge

**Pull request merged**
