### PR TITLE
Bump GATK4 gcnvkernel

### PR DESCRIPTION
**Pull request by matthdsm**
Attempt to  gatk in gcnvkernel

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

### General instructions

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

### Instructions for avoiding API, ABI, and CLI breakage issues
Conda is able to record and lock (a.k.a. pin) dependency versions used at build time of other recipes.
This way, one can avoid that expectations of a downstream recipe with regards to API, ABI, or CLI are violated by later changes in the recipe.
If not already present in the meta.yaml, make sure to specify `run_exports` (see [here](https://bioconda.github.io/contributor/linting.html#missing-run-exports) for the rationale and comprehensive explanation).
Add a `run_exports` section like this:

```yaml
build:
  run_exports:
    - ...

```

with `...` being one of:

| Case                             | run_exports statement                                               |
| -------------------------------- | ------------------------------------------------------------------- |
| semantic versioning              | `{{ pin_subpackage("myrecipe", max_pin="x") }}`     |
| semantic versioning (0.x.x)      | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}`   |
| known breakage in minor versions | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| known breakage in patch versions | `{{ pin_subpackage("myrecipe", max_pin="x.x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| calendar versioning              | `{{ pin_subpackage("myrecipe", max_pin=None) }}`    |

while replacing `"myrecipe"` with either `name` if a `name|lower` variable is defined in your recipe or with the lowercase name of the package in quotes.

### Bot commands for PR management

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

Note that the <code>@BiocondaBot please merge</code> command is now depreciated. Please just squash and merge instead.

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Review by maxulysse — APPROVED** [review]
LGTM

**Comment by matthdsm** [comment]
`gcnvkernel` build fails with
```2024-02-12T09:14:53.2750265Z .09:14:53 [32mBIOCONDA INFO[0m (OUT) [?25hMamba failed to solve:[0m
2024-02-12T09:14:53.2752615Z 09:14:53 [32mBIOCONDA INFO[0m (OUT)  - matplotlib 3.2.1.*[0m
2024-02-12T09:14:53.2753856Z 09:14:53 [32mBIOCONDA INFO[0m (OUT)  - scipy 1.0.0.*[0m
2024-02-12T09:14:53.2754150Z 09:14:53 [32mBIOCONDA INFO[0m (OUT)  - h5py 2.10.0.*[0m
2024-02-12T09:14:53.2754430Z 09:14:53 [32mBIOCONDA INFO[0m (OUT)  - r-ggplot2 3.3.0.*[0m
2024-02-12T09:14:53.2755403Z 09:14:53 [32mBIOCONDA INFO[0m (OUT)  - python 3.6.10.*[0m
2024-02-12T09:14:53.2755694Z 09:14:53 [32mBIOCONDA INFO[0m (OUT)  - mkl-service 2.3.0.*[0m
2024-02-12T09:14:53.2755962Z 09:14:53 [32mBIOCONDA INFO[0m (OUT)  - r-optparse 1.6.4.*[0m
2024-02-12T09:14:53.2756360Z 09:14:53 [32mBIOCONDA INFO[0m (OUT)  - pandas 1.0.3.*[0m
2024-02-12T09:14:53.2756616Z 09:14:53 [32mBIOCONDA INFO[0m (OUT)  - r-data.table 1.12.8.*[0m
2024-02-12T09:14:53.2757015Z 09:14:53 [32mBIOCONDA INFO[0m (OUT)  - r-backports 1.1.10.*[0m
2024-02-12T09:14:53.2757297Z 09:14:53 [32mBIOCONDA INFO[0m (OUT)  - scikit-learn 0.23.1.*[0m
2024-02-12T09:14:53.2757659Z 09:14:53 [32mBIOCONDA INFO[0m (OUT)  - r-getopt 1.20.3.*[0m
2024-02-12T09:14:53.2757970Z 09:14:53 [32mBIOCONDA INFO[0m (OUT)  - biopython 1.76.*[0m
2024-02-12T09:14:53.2758226Z 09:14:53 [32mBIOCONDA INFO[0m (OUT)  - pysam 0.15.3.*[0m
2024-02-12T09:14:53.2758596Z 09:14:53 [32mBIOCONDA INFO[0m (OUT)  - pymc3 3.1.*[0m
2024-02-12T09:14:53.2758869Z 09:14:53 [32mBIOCONDA INFO[0m (OUT)  - pyvcf 0.6.8.*[0m
2024-02-12T09:14:53.2759231Z 09:14:53 [32mBIOCONDA INFO[0m (OUT)  - r-base 3.6.2.*[0m
2024-02-12T09:14:53.2759495Z 09:14:53 [32mBIOCONDA INFO[0m (OUT)  - theano 1.0.4.*[0m
2024-02-12T09:14:53.2759768Z 09:14:53 [32mBIOCONDA INFO[0m (OUT)  - r-gsalib 2.1.*[0m
2024-02-12T09:14:53.2760156Z 09:14:53 [32mBIOCONDA INFO[0m (OUT)  - r-dplyr 0.8.5.*[0m
2024-02-12T09:14:53.2760417Z 09:14:53 [32mBIOCONDA INFO[0m (OUT)  - typing_extensions 4.1.1.*[0m
2024-02-12T09:14:53.2760809Z 09:14:53 [32mBIOCONDA INFO[0m (OUT)  - tensorflow 1.15.0.*[0m
2024-02-12T09:14:53.2761097Z 09:14:53 [32mBIOCONDA INFO[0m (OUT)  - mkl 2019.5.*[0m
2024-02-12T09:14:53.2761334Z 09:14:53 [32mBIOCONDA INFO[0m (OUT)  - pip 21.3.1.*[0m
2024-02-12T09:14:53.2761747Z 09:14:53 [32mBIOCONDA INFO[0m (OUT)  - numpy 1.17.5.*[0m
2024-02-12T09:14:53.2761985Z 09:14:53 [32mBIOCONDA INFO[0m (OUT)  - dill 0.3.4.*[0m
2024-02-12T09:14:53.2762364Z 09:14:53 [32mBIOCONDA INFO[0m (OUT)  - keras 2.2.4.*[0m
2024-02-12T09:14:53.2762639Z 09:14:53 [32mBIOCONDA INFO[0m (OUT)  - intel-openmp 2019.4.*[0m
2024-02-12T09:14:53.2763077Z 09:14:53 [32mBIOCONDA INFO[0m (OUT)  - r-gplots 3.0.3.*[0m
2024-02-12T09:14:53.2763463Z 09:14:53 [32mBIOCONDA INFO[0m (OUT) [0m
2024-02-12T09:14:53.2763705Z 09:14:53 [32mBIOCONDA INFO[0m (OUT) with channels:[0m
2024-02-12T09:14:53.2763957Z 09:14:53 [32mBIOCONDA INFO[0m (OUT)  - file:///opt/host-conda-bld[0m
2024-02-12T09:14:53.2764210Z 09:14:53 [32mBIOCONDA INFO[0m (OUT)  - conda-forge[0m
2024-02-12T09:14:53.2764477Z 09:14:53 [32mBIOCONDA INFO[0m (OUT)  - bioconda[0m
2024-02-12T09:14:53.2764846Z 09:14:53 [32mBIOCONDA INFO[0m (OUT)  - defaults[0m
2024-02-12T09:14:53.2765074Z 09:14:53 [32mBIOCONDA INFO[0m (OUT) [0m
2024-02-12T09:14:53.2765321Z 09:14:53 [32mBIOCONDA INFO[0m (OUT) The reported errors are:[0m
2024-02-12T09:14:53.2765687Z 09:14:53 [32mBIOCONDA INFO[0m (OUT) - Encountered problems while solving:[0m
2024-02-12T09:14:53.2766046Z 09:14:53 [32mBIOCONDA INFO[0m (OUT) -   - package tensorflow-1.15.0-mkl_py37h28c19af_0 is excluded by strict repo priority[0m
```

**Comment by matthdsm** [comment]
ugh... 🙄 
```
10:49:38 BIOCONDA INFO (OUT) OSError: [Errno 28] No space left on device
```

**Comment by matthdsm** [comment]
Reverted all commits for the gatk recipe to fix the `no space left` issue

**Pull request merged**
