### PR TITLE
Add phytest 1.4.0

### PR DESCRIPTION
**Pull request by vinisalazar**

### CODE REVIEW

**Comment by rbturnbull** [comment]
I confirm that I am a maintainer.

**Comment by vinisalazar** [comment]
@bioconda-bot ready for review

**Comment by vinisalazar** [comment]
@bioconda-bot please add label

**Comment by Wytamma** [comment]
I confirm that I am a maintainer.

**Comment by smutch** [comment]
I confirm that I am a maintainer.

**Comment by mencian** [comment]
Looks good to me! Thanks! @vinisalazar

**Review by mencian — APPROVED** [review]

**Pull request merged**
