### PR TITLE
Update graphbin to v1.6.1

### PR DESCRIPTION
**Pull request by Vini2**
Describe your pull request here

This PR updates [`graphbin`](https://github.com/metagentools/GraphBin) to version 1.6.1.

Vijini Mallawaarachchi, Anuradha Wickramarachchi, Yu Lin, GraphBin: refined binning of metagenomic contigs using assembly graphs, Bioinformatics, Volume 36, Issue 11, June 2020, Pages 3307–3313, https://doi.org/10.1093/bioinformatics/btaa180

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by Vini2** [comment]
@BiocondaBot please add label

**Comment by Vini2** [comment]
@BiocondaBot please fetch artifacts

**Comment by Vini2** [comment]
@BiocondaBot please fetch artifacts

**Comment by Vini2** [comment]
@BiocondaBot please fetch artifacts

**Comment by Vini2** [comment]
# Testing

## Conda

```
conda install -c ./packages graphbin-1.6.1-pyhdfd78af_0.tar.bz2

which graphbin
~/miniconda3/bin/graphbin

graphbin --version
GraphBin version 1.6.1

graphbin --help
usage: graphbin [-h] [--version] [--graph GRAPH] [--binned BINNED] [--output OUTPUT] [--prefix PREFIX] [--max_iteration MAX_ITERATION]
                [--diff_threshold DIFF_THRESHOLD] [--assembler ASSEMBLER] [--paths PATHS] [--contigs CONTIGS] [--delimiter DELIMITER]

GraphBin Help. GraphBin is a metagenomic contig binning tool that makes use of the contig connectivity information from the assembly graph to bin contigs.
It utilizes the binning result of an existing binning tool and a label propagation algorithm to correct mis-binned contigs and predict the labels of contigs
which are discarded due to short length.

options:
  -h, --help            show this help message and exit
  --version
  --graph GRAPH         path to the assembly graph file
  --binned BINNED       path to the .csv file with the initial binning output from an existing tool
  --output OUTPUT       path to the output folder
  --prefix PREFIX       prefix for the output file
  --max_iteration MAX_ITERATION
                        maximum number of iterations for label propagation algorithm. [default: 100]
  --diff_threshold DIFF_THRESHOLD
                        difference threshold for label propagation algorithm. [default: 0.1]
  --assembler ASSEMBLER
                        name of the assembler used (SPAdes, SGA or MEGAHIT). GraphBin supports Flye, Canu and Miniasm long-read assemblies as well.
  --paths PATHS         path to the contigs.paths file, only needed for SPAdes
  --contigs CONTIGS     path to the contigs.fa file.
  --delimiter DELIMITER
                        delimiter for input/output results. Supports a comma (,), a semicolon (;), a tab ($'\t'), a space (" ") and a pipe (|) [default: ,
                        (comma)]
```

## Pytest run

Testing using test cases in [test_graphbin.py](https://github.com/metagentools/GraphBin/blob/develop/tests/test_graphbin.py) and testing data.

Command:

```
pytest test_graphbin.py
```

Output:

```
============================= test session starts =============================
platform linux -- Python 3.11.0, pytest-7.2.1, pluggy-1.0.0
rootdir: /home/mall0133/software/GraphBin, configfile: pyproject.toml
plugins: cov-4.0.0
collected 7 items                                                             

test_graphbin.py .......                                                [100%]

============================= 7 passed in 11.53s ==============================
```

## Example test run

Example graphbin run using testing data in [ESC_metaSPAdes](https://github.com/metagentools/GraphBin/tree/develop/tests/data/ESC_metaSPAdes).

Command:

```
graphbin --assembler spades --graph assembly_graph_with_scaffolds.gfa --contigs contigs.fasta --paths contigs.paths --binned initial_binning_res.csv --output ./
```

Output:

```
2023-01-26 17:57:12,343 - INFO - Welcome to GraphBin: Refined Binning of Metagenomic Contigs using Assembly Graphs.
2023-01-26 17:57:12,343 - INFO - This version of GraphBin makes use of the assembly graph produced by SPAdes which is based on the de Bruijn graph approach.
2023-01-26 17:57:12,343 - INFO - Input arguments:
2023-01-26 17:57:12,343 - INFO - Assembly graph file: assembly_graph_with_scaffolds.gfa
2023-01-26 17:57:12,343 - INFO - Contig paths file: contigs.paths
2023-01-26 17:57:12,343 - INFO - Existing binning output file: initial_binning_res.csv
2023-01-26 17:57:12,343 - INFO - Final binning output file: ./
2023-01-26 17:57:12,343 - INFO - Maximum number of iterations: 100
2023-01-26 17:57:12,343 - INFO - Difference threshold: 0.1
2023-01-26 17:57:12,343 - INFO - GraphBin started
2023-01-26 17:57:12,344 - INFO - Number of bins available in the initial binning result: 3
2023-01-26 17:57:12,344 - INFO - Constructing the assembly graph
2023-01-26 17:57:12,347 - INFO - Total number of contigs available: 189
2023-01-26 17:57:12,365 - INFO - Total number of edges in the assembly graph: 879
2023-01-26 17:57:12,365 - INFO - Obtaining the initial binning result
2023-01-26 17:57:12,366 - INFO - Determining ambiguous vertices
2023-01-26 17:57:12,366 - INFO - Removing labels of ambiguous vertices
2023-01-26 17:57:12,366 - INFO - Obtaining the refined binning result
2023-01-26 17:57:12,366 - INFO - Deteremining vertices which are not isolated and not in components without any labels
2023-01-26 17:57:12,368 - INFO - Number of non-isolated contigs: 188
2023-01-26 17:57:12,369 - INFO - Creating an instance of LabelProp
2023-01-26 17:57:12,370 - INFO - Starting label propagation with eps=0.1 and max_iteration=100
2023-01-26 17:57:12,383 - INFO - Total number of vertices:		188
2023-01-26 17:57:12,383 - INFO - Number of class labels:		3
2023-01-26 17:57:12,383 - INFO - Previous number of unlabeled vertices:	125
2023-01-26 17:57:12,383 - INFO - Previous numebr of labeled vertices:	63
2023-01-26 17:57:12,383 - INFO - Value of eps parameter:		0.1
2023-01-26 17:57:12,383 - INFO - Value of max_iteration parameter:	100
2023-01-26 17:57:12,383 - INFO - Final values:
2023-01-26 17:57:12,383 - INFO - iter = 52, diff = 0.09590983535859193
2023-01-26 17:57:12,384 - INFO - Obtaining Label Propagation result
2023-01-26 17:57:12,384 - INFO - Determining ambiguous vertices
2023-01-26 17:57:12,385 - INFO - Removing labels of ambiguous vertices
2023-01-26 17:57:12,385 - INFO - Obtaining the Final Refined Binning result
2023-01-26 17:57:12,385 - INFO - Elapsed time: 0.043416500091552734 seconds
2023-01-26 17:57:12,385 - INFO - Writing the Final Binning result to file
Splitting contigs into bins: 189it [00:00, 4330.90it/s]
2023-01-26 17:57:12,495 - INFO - Final binning results can be found in ./bins/
2023-01-26 17:57:12,498 - INFO - Unbinned contigs can be found at ./graphbin_unbinned.csv
2023-01-26 17:57:12,498 - INFO - Thank you for using GraphBin! Bye...!
```

Output files from `ls -lh`:

```
-rw-r--r-- 1 mall0133 staff 8.1M Jan 26 17:48 assembly_graph_with_scaffolds.gfa
drwxr-xr-x 2 mall0133 staff   79 Jan 26 17:51 bins
-rw-r--r-- 1 mall0133 staff 8.1M Jan 26 17:48 contigs.fasta
-rw-r--r-- 1 mall0133 staff  39K Jan 26 17:48 contigs.paths
-rw-r--r-- 1 mall0133 staff 5.3K Jan 26 17:57 graphbin.log
-rw-r--r-- 1 mall0133 staff 6.5K Jan 26 17:57 graphbin_output.csv
-rw-r--r-- 1 mall0133 staff  469 Jan 26 17:57 graphbin_unbinned.csv
-rw-r--r-- 1 mall0133 staff 2.8K Jan 26 17:48 initial_binning_res.csv
```

Everything looks good!

**Review by nh13 — APPROVED** [review]

**Comment by nh13** [comment]
@BiocondaBot please merge

**Pull request merged**
