### PR TITLE
Berokka -- Copy db under PREFIX/db

### PR DESCRIPTION
**Pull request by Kurt-Hanel**
:information_source:
Bioconda has finished the [GCC7 migration](https://github.com/bioconda/bioconda-recipes/issues/13578). If you are dealing with C/C++ or Python package it can be that you need to rebuild other dependent packages. [Bioconda utils - update-pinning](https://bioconda.github.io/updating.html#updating-recipes-for-a-pinning-change) will assist you with that. If you have any questions please use [issue 13578](https://github.com/bioconda/bioconda-recipes/issues/13578).

----------------

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

In order to run, berokka requires a db with controls.fna and dnaA.fna. This pull request will make sure that that database is set when berokka is installed.

### CODE REVIEW

**Comment by bgruening** [comment]
@Kurt-Hanel how big are they? Usually, we use post-link script to download DB's after installation ...

**Comment by bgruening** [comment]
For example here: https://github.com/bioconda/bioconda-recipes/blob/ccbaa13b33826851ab5012b6c72b7388eb6e4090/recipes/bioconductor-lrbase.rno.eg.db/post-link.sh

**Comment by Kurt-Hanel** [comment]
controls.fna is 2 KB and dnaA.fna is 5 MB

**Comment by bgruening** [comment]
@Kurt-Hanel I think we should us this post-link and post-unlink tricks here. 5MB seems to be too large imho.

**Comment by Kurt-Hanel** [comment]
@bgruening Since the db is already included in berokka's [latest release](https://github.com/tseemann/berokka/releases), is the post-link script necessary? Wouldn't using a post-link script mean downloading the tar release twice?

**Comment by Kurt-Hanel** [comment]
Hi @bgruening, please let me know what your thoughts are on my last question.

**Comment by bgruening** [comment]
The post-link script only makes sense when the DB is not copied into the PREFIX.
You need to increase the build number to get a new package.

**Comment by Kurt-Hanel** [comment]
Thanks @bgruening !

**Pull request merged**
