### PR TITLE
Added RNAlien recipe

### PR DESCRIPTION
**Pull request by eggzilla**
* [x] I have read the guidelines above.
* [x] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by bgruening** [comment]
Was doing the exact same thing as you last commit on the train ... hopefully this will solve it.

**Comment by eggzilla** [comment]
I have the feeling this could be the last missing piece :-)

**Comment by eggzilla** [comment]
Looks good now

**Comment by bgruening** [comment]
Wuhu! But please don't merge, this rebase went wrong. I will be next to you in a few minutes ;)

**Pull request closed without merging**
