### PR TITLE
Update chisel to 1.0.0

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`chisel`](https://bioconda.github.io/recipes/chisel/README.html): **0.0.5** &rarr; **1.0.0**

[install with bioconda](http://bioconda.github.io/recipes/chisel/README.html) [Conda](https://anaconda.org/bioconda/chisel/files)

Info | Link
-----|-----
Recipe | [`recipes/chisel`](https://github.com//bioconda/bioconda-recipes/tree/bump/chisel/recipes/chisel) (click to view/edit other files)
Releases |[https://github.com/raphael-group/chisel/tags](https://github.com/raphael-group/chisel/tags)
Author | `@raphael-group`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by simozacca** [comment]
@BiocondaBot please add label

**Review by simozacca — APPROVED** [review]

**Comment by simozacca** [comment]
@BiocondaBot please merge

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Comment by dpryan79** [comment]
@bioconda-bot please fetch artifacts

Maybe I was too slow on this

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Pull request merged**
