### PR TITLE
perl-moosex-app: move 1.35 to subfolder, trigger build

### PR DESCRIPTION
**Pull request by mbargull**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

Re #7396. @jerowe, maybe you can help here. In https://github.com/bioconda/bioconda-recipes/pull/7004 you added `1.39` of `perl-moosex-app` in a subfolder and left `1.35` in-place as the main recipe. Now `1.35` failed on a scheduled build with:
```
+ make test
PERL_DL_NONLAZY=1 "/opt/conda/conda-bld/perl-moosex-app_1517184441596/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/bin/perl" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'inc', 'blib/lib', 'blib/arch')" t/*.t
t/00_load.t ............... ok
t/01_basic.t .............. ok
t/02_meta.t ............... ok
t/03_utils.t .............. ok
t/04_plugin_config.t ...... ok
t/05_extended.t ........... ok
t/06_env.t ................ ok
t/07_single.t ............. ok
t/08_plugin_various.t ..... ok

    #   Failed test 'Only callable as class method'
    #   at t/09_classes.t line 23.
    # expecting: Regexp ((?^:new_with_command is a class method))
    # found: Devel::StackTrace version 2.03 required--this is only version 2.02 at /opt/conda/conda-bld/perl-moosex-app_1517184441596/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/perl5/site_perl/5.22.0/x86_64-linux-thread-multi/Moose/Exception.pm line 5.
    # BEGIN failed--compilation aborted at /opt/conda/conda-bld/perl-moosex-app_1517184441596/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/perl5/site_perl/5.22.0/x86_64-linux-thread-multi/Moose/Exception.pm line 5.
    # Compilation failed in require at /opt/conda/conda-bld/perl-moosex-app_1517184441596/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/perl5/site_perl/5.22.0/Module/Runtime.pm line 317.
    # Compilation failed in require at /opt/conda/conda-bld/perl-moosex-app_1517184441596/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/perl5/site_perl/5.22.0/Module/Runtime.pm line 317.

    #   Failed test 'new_with_command may only be called from the application base package'
    #   at t/09_classes.t line 25.
    # expecting: Regexp ((?^:new_with_command may only be called from the application base package))
    # found: Attempt to reload Moose/Exception/Legacy.pm aborted.
    # Compilation failed in require at /opt/conda/conda-bld/perl-moosex-app_1517184441596/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/perl5/site_perl/5.22.0/Module/Runtime.pm line 317.

    #   Failed test 'Wrong default args'
    #   at t/09_classes.t line 26.
    # expecting: Regexp ((?^:new_with_command got invalid extra arguments))
    # found: Attempt to reload Moose/Exception/Legacy.pm aborted.
    # Compilation failed in require at /opt/conda/conda-bld/perl-moosex-app_1517184441596/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/perl5/site_perl/5.22.0/Module/Runtime.pm line 317.
    # Looks like you failed 3 tests of 3.

#   Failed test 'Wrong usage'
#   at t/09_classes.t line 28.

    #   Failed test 'Conflict detected'
    #   at t/09_classes.t line 34.
    # expecting: Regexp ((?^:Command line option conflict))
    # found: Attempt to reload Moose/Exception/Legacy.pm aborted.
    # Compilation failed in require at /opt/conda/conda-bld/perl-moosex-app_1517184441596/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/perl5/site_perl/5.22.0/Module/Runtime.pm line 317.
    # Looks like you failed 1 test of 1.

#   Failed test 'Conflicts'
#   at t/09_classes.t line 35.
```
. I have absolutely no knowledge of Perl, so I can't make much sense of those failures...
Since you added `1.39` do you think we still need `1.35` or could we just deleted the older one? That's exactly what this PR does 😉

### CODE REVIEW

**Comment by johanneskoester** [comment]
+1 for deleting the old recipe.

**Comment by jerowe** [comment]
I wouldn't go crazy with removing things until the conda-forge gcc VS conda
gcc question gets resolved.

Any and all scheduled builds of all perl modules will break, because we
went from sourcing the conda forge build chain to not. Perl was compiled on
conda forge with their build chain, and we can't just swap in the conda gcc
package.

**Comment by jerowe** [comment]
Also a personal - 1 for deleting because I have production packages that
depend upon moosex-app 1.35

**Comment by mbargull** [comment]
> I have production packages that
depend upon moosex-app 1.35

Okay.

> we went from sourcing the conda forge build chain to not

I don't really understand. AFAIK, there was no such change. The change from Travis CI to CircleCI might've caused some differences (e.g., other pre-installed compiler and such -- haven't had the chance to test this, yet).
But, to the best of my knowledge, we never generally "sourced conda-forge's toolchain" -- there are very few packages in Bioconda that use `toolchain`.
(Although, I think it would likely be beneficial to make use of `toolchain` (and `toolchain3` in the future) as often as possible -- that's something we should talk about/coordinate! pinging @bioconda/core )

----

But all that aside: I don't think `perl-moosex-app 1.35` failed due to anything `gcc`-related. The failures above rather look only Perl-related. Do we need to update or constrain any dependencies, e.g., on Moose or Devel::StackTrace. Me no speak Perl ☹️

**Comment by johanneskoester** [comment]
@jerowe keeping 1.35 is fine, but then we need somebody to fix the errors. It is currently not building at all on linux.

**Comment by jerowe** [comment]
I can handle that. Just not today. ;)

**Comment by johanneskoester** [comment]
Ok, bioconda-utils now uses devtoolset-2 as a fallback in docker builds. @jerowe, does that presumably fix the observed perl issues?

**Comment by jerowe** [comment]
It should. I have tested it on a local docker image and it works.

Thanks!

**Comment by johanneskoester** [comment]
Ok, I guess that means that this PR can be closed, because the original state in the master branch should build tonight, right?

**Comment by mbargull** [comment]
I'll update this PR so that `recipes/perl-moosex-app` points to `1.39` and move `1.35` to a subfolder. I think that'd conform better to the expected directory structure, right?

**Comment by mbargull** [comment]
Well, it failed with the exact same errors as before, i.e.,
```
...
    # found: Devel::StackTrace version 2.03 required--this is only version 2.02 at /opt/conda/conda-bld/perl-moosex-app_1517489795529/_b_env_placehold_placehold_placehold_
...
```
. So, out of ignorance, I just copied the `build.sh` from `1.39` to `1.35` which seems to do the trick.
Though I'm a little confused why the `build.sh` contains
```bash
    HOME=/tmp cpanm --installdeps .
    HOME=/tmp cpanm  Text::WagnerFischer
    HOME=/tmp cpanm  Devel::StackTrace
```
. Wouldn't we want to update and include those build deps in the Conda/Bioconda context? It feels a bit strange to pull those in that way...
(But again, non-Perl-knowing person speaking here.)

**Comment by mbargull** [comment]
@bioconda/perl: Does anyone want to review, comment or merge?

**Comment by rvalieris** [comment]
>  HOME=/tmp cpanm --installdeps .
>  HOME=/tmp cpanm  Text::WagnerFischer
>  HOME=/tmp cpanm  Devel::StackTrace

I definitely don't like the idea of bundling dependencies like that, but I think this can be fixed on another PR, because it will require including recipes for these missing packages.

also, these packages are not really bioinfo related, we should start thinking about migrating these to conda-forge.

**Comment by mbargull** [comment]
> also, these packages are not really bioinfo related, we should start thinking about migrating these to conda-forge.

That was what I was thinking, too. But then I saw
```bash
$ curl -sL https://conda.anaconda.org/conda-forge/linux-64/repodata.json.bz2 | bzip2 -dc | python -c '
from json import load
from sys import stdin
print({
    pkg["name"] for pkg in load(stdin)["packages"].values()
    if any(dep.split()[0] == "perl" for dep in pkg["depends"])
})'
{'perl-xml-parser', 'texlive-core', 'python-eccodes', 'lua-luaposix', 'pari', 'mosh', 'imagemagick', 'parallel', 'help2man', 'eccodes', 'automake', 'autoconf', 'texinfo'}
$ curl -sL https://conda.anaconda.org/bioconda/linux-64/repodata.json.bz2 | bzip2 -dc | python -c '
from json import load
from sys import stdin
print(len({
    pkg["name"] for pkg in load(stdin)["packages"].values()
    if any(dep.split()[0] == "perl" for dep in pkg["depends"])
}))'
376
```
. So nearly all packages that directly depend on `perl` are on `bioconda`...

**Comment by rvalieris** [comment]
> . So nearly all packages that directly depend on perl are on bioconda...

yes, I understand its a lot of packages, mostly dependencies from bioconda stuff, but not really related to biological sciences.
its the same case as the R packages, basically all R packages on conda-forge now came from bioconda contributors (https://github.com/conda-forge/staged-recipes/issues/2009)
granted, we first need to solve this compiler differences between bioconda and conda-forge, and perhaps wait for conda-build 3, but eventually they should be migrated.

but nevermind all this, this shouldn't stop us from fixing stuff on bioconda today.

**Comment by jerowe** [comment]
I started to try to migrate perl packages over to conda-forge, but I kept
hitting a wall because the perl-app-cpanminus package was broken on either
Linux or osx. I will try to have another go at it. I would very much like
to get these moved!

**Comment by mbargull** [comment]
> granted, we first need to solve this compiler differences between bioconda and conda-forge

That should be fixed now.

> and perhaps wait for conda-build 3, but eventually they should be migrated.

Yeah, pretty sure this would reduce the required effort, i.e., have one move-and-update-to-cb3 instead of two separate move + update-to-cb3 steps.

**Pull request closed without merging**
