### PR TITLE
Rename to scater-scripts, bump version to 0.0.5

### PR DESCRIPTION
**Pull request by nh3**
:information_source:
Bioconda has finished the [GCC7 migration](https://github.com/bioconda/bioconda-recipes/issues/13578). If you are dealing with C/C++ or Python package it can be that you need to rebuild other dependent packages. [Bioconda utils - update-pinning](https://bioconda.github.io/updating.html#updating-recipes-for-a-pinning-change) will assist you with that. If you have any questions please use [issue 13578](https://github.com/bioconda/bioconda-recipes/issues/13578).

----------------

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by nh3** [comment]
Thanks!

**Comment by pinin4fjords** [comment]
@nh3 - I didn't spot this, but you had a bad base branch- you should have been branching off develop and merging there. Please make sure develop is updated. Usual procedure is to merge features to develop, create a release branches from develop which are merged to both master and develop.

**Comment by pinin4fjords** [comment]
Sorry @nh3 - got confused with in-house repos ;-)

**Comment by bgruening** [comment]
@nh3 and @pinin4fjords should I mark bioconductor-scater-scripts as deprecated/broken so it does not appear in a normal conda search call?

**Comment by nh3** [comment]
Hi @bgruening, yes, that would be ideal. Many thanks!

**Comment by bgruening** [comment]
Done! Thanks for your contributions!

**Comment by nh3** [comment]
@bgruening, CI bioconda-upload-master/upload-linux failed (https://circleci.com/gh/bioconda/bioconda-recipes/47680) due to HTTP error during dependencies retrieval:

> conda.CondaMultiError: HTTP 500 INTERNAL SERVER ERROR for url <https://conda.anaconda.org/bioconda/linux-64/bioconductor-xvector-0.22.0-r351h14c3975_0.tar.bz2>
> 
> Elapsed: 00:00.119756
> 
> CF-RAY: 4b7e33ff8bf3ba90-ATL
> 
> An HTTP error occurred when trying to retrieve this URL.
> 
> HTTP errors are often intermittent, and a simple retry will get you on your way.

while upload-macos succeeded. I restarted the job (47727 & 47728) given the suggestion, but again macos succeeded and linux failed for the same HTTP error (a different dependency). I re-started this morning (47802 & 47803), but this time I am getting error during "Setup bioconda-utils":

> From ssh://github.com/bioconda/bioconda-recipes
>  \* [new branch]          master     -> __upstream__VETbshR9cc/master
> Your bioconda-recipes CI configuration is out of date.
> Please update it to the latest version of the upstream master branch.
> You can do this, e.g., by running:
>   git fetch https://github.com/bioconda/bioconda-recipes.git master
>   git merge FETCH_HEAD
> Exited with code 1

Currently, `scater-scripts` can't be found by `conda search`. Do you think that is related to the above CI errors?

**Comment by nh3** [comment]
scater-scripts is available now. Seems the above circle CI errors are not related.

**Comment by bgruening** [comment]
Oh great!

**Pull request merged**
