### PR TITLE
Add Alohomora recipe

### PR DESCRIPTION
**Pull request by mtekman**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by bgruening** [comment]
dos2unix needs either to be defined as dependency or you can patch this file.

**Comment by mtekman** [comment]
Hey thanks

It looks like it's still failing on the `Can't locate Tk.pm in @INC` due to the missing `perl-tk` package which needs to be built first (https://github.com/bioconda/bioconda-recipes/pull/6293)

**Comment by pcm32** [comment]
@bioconda-bot update

**Comment by mtekman** [comment]
@BiocondaBot update

**Comment by mtekman** [comment]
@bioconda-bot update

**Comment by simonbray** [comment]
@BiocondaBot please update

**Comment by mtekman** [comment]
> Can't locate Tk.pm in @INC 

I believe this was the same error as before

**Comment by daler** [comment]
Closing, no activity in several years

**Comment by mtekman** [comment]
:cry: 

Thanks for cleaning this up

**Pull request closed without merging**
