### PR TITLE
gffcompare: unblacklist and update (plus remove gclib)

### PR DESCRIPTION
**Pull request by bernt-matthias**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

this unblacklists gffcompare

### CODE REVIEW

**Comment by bernt-matthias** [comment]
I guess this is the way to go and we can close https://github.com/bioconda/bioconda-recipes/pull/12416 ..

**Comment by bernt-matthias** [comment]
Q: should we blacklist older versions?

**Comment by bgruening** [comment]
>Q: should we blacklist older versions?

Remove them :)

>Q: should we delete the gclib recipe?

Yes please.

**Comment by bernt-matthias** [comment]
Removed gclib. 

Currently I would only remove 0.10.1 since 0.9.8 is used in a galaxy tool. Question is how? :)

**Comment by bernt-matthias** [comment]
Also there seems to be an issue with bioconda linting at the moment. I also observed this for other recipes

**Comment by bernt-matthias** [comment]
@jfallmann could you have a look ... maybe you also know an answer for the question from above:

> how to blacklist old versions

but, maybe this is not necessary anyway?

**Comment by jfallmann** [comment]
@bernt-matthias No I'm not sure what to do for deleting only a specific version, could we just blacklist that specific version and keep the older version unblacklisted?

**Comment by bgruening** [comment]
Which version do you need to be blacklisted?

**Comment by jfallmann** [comment]
@bgruening 
> Currently I would only remove 0.10.1 since 0.9.8 is used in a galaxy tool. Question is how? :)
So 0.10.1 remove and keep 0.9.8

**Comment by bgruening** [comment]
done

**Comment by bernt-matthias** [comment]
> Which version do you need to be marked as broken?

Unsure. According to https://anaconda.org/bioconda/gffcompare/files there were only 0.9.8  and 0.10.1. Both have been downloaded often and I guess they are functional. 

My idea was just born from the fact that gffcompare was blacklisted (from here https://github.com/bioconda/bioconda-recipes/commit/7f2d1f0bf092e68c15fee5fd7b6fe3262d0e188a .. this was seemingly during 0.10.1 - but I don't know why it was blacklisted). Version 0.10.5 which came later apparently never went online. 

So I guess it's fine now?

**Pull request merged**
