### PR TITLE
Bumped cnvkit version

### PR DESCRIPTION
**Pull request by micknudsen**
* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [X] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [X] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by corburn** [comment]
The pull request needs to remove the recipe from the blacklist for it to build.

https://github.com/bioconda/bioconda-recipes/blob/d0e582629e3f8af5932880c2088b65ab3bfdea2d/build-fail-blacklist#L1486

**Comment by micknudsen** [comment]
@corburn I am unfamiliar with the `build-fail-blacklist`. Does this mean that the `cnvkit` recipe can't be updated, until the software has been updated to work with newer `R` versions?

**Comment by corburn** [comment]
@micknudsen the `build-fail-blacklist` was created to expedite the process of transitioning the bioconda build system to conda3 by effectively skipping problematic recipes until someone gets around to fixing them. I am not familiar with the specific issue encountered with `cnvkit`, but among the ways you could find out is to remove it from the blacklist and see what errors are returned by the build server, search the conda-forge and bioconda issues for the current status of the R recipe, or checkout the cnvkit github page to learn more about its requirements.

**Comment by micknudsen** [comment]
@corburn Thanks for the information. I'll dig into the issue.

**Comment by micknudsen** [comment]
@corburn Problem solved by requiring a newer R version. Do you think the PR can be merged now?

**Comment by micknudsen** [comment]
@johanneskoester I have noticed that after the update, there is only one build (called `py_0`). The usual suspects `py_36`, `py_35`, etc, are missing. Now `cnvkit` will not install with Python 3

Any clue what could have caused that? Only one thing (besides the version) has changed in the recipe: I have added the requirement `r-base>=3.4.1` to fix the blacklist issue.

Pinging @etal

**Pull request merged**
