### PR TITLE
Add new recipe from bioc 3.6 FlowSorted.Blood.450k data package

### PR DESCRIPTION
**Pull request by mrlmachado**
* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [X] This PR adds a new recipe.
* [X] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by mrlmachado** [comment]
@daler @bgruening @bioconda/core what I did wrong? Can you help me pls

**Comment by daler** [comment]
The error message is

```
The CI configuration is out of date.
Please merge in bioconda:master.
```

You need to merge in bioconda:master into your fork to update the CI configuration.

**Comment by mrlmachado** [comment]
I think I did exactly that

image

What is wrong?

**Comment by daler** [comment]
Try following https://help.github.com/articles/merging-an-upstream-repository-into-your-fork/

**Comment by mrlmachado** [comment]
Sorry for the noobish but I tryed the tutorial and PR in https://github.com/bioconda/bioconda-recipes/pull/8965 but again same error. @daler Help me pls

**Comment by daler** [comment]
easiest thing to do would be to re-clone your fork and make sure it's up-to-date with master, then copy over the files you want to add. Step-by-step:

```bash
# Clone a new version of your fork into a new directory
git clone <url-to-your-fork> my-fork

# Change to that directory
cd my-fork

# Make sure you're on the master branch of your fork
git checkout master

# Merge in any changes that were in the upstream master with your master.
# This is the important step.
git pull https://github.com/bioconda/bioconda-recipes.git master

# Create a new branch and switch to it
git checkout -b my-branch

# copy over the files you want to add
cp ../my-previous-checkout-of-my-fork/recipes/bioconductor-flowsorted.blood.450k recipes/bioconductor-flowsorted.blood.450k

# add the new files
git add recipes/bioconductor-flowsorted.blood.450k

# commit to this branch
git commit

# push this branch to github
git push origin my-branch
```

Then open another PR (and close this one).

**Comment by mrlmachado** [comment]
Thanks @daler  @bgruening , I followed the instructions and it worked out. Sorry for my noobish and thanks again. The new PR is https://github.com/bioconda/bioconda-recipes/pull/8986 . I'm closing this one.

**Pull request closed without merging**
