### PR TITLE
Parafly. Skipping binary relocation to prevent build error.

### PR DESCRIPTION
**Pull request by loraine-gueguen**
* [x] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

Add `binary_relocation: False` like in #2686

### CODE REVIEW

**Comment by loraine-gueguen** [comment]
It is green, but the build has not be done: for each 4 jobs I have `INFO:bioconda_utils.utils:Nothing to be done.`
I don't understand why..
Could someone help me please ?
Thanks

**Comment by bgruening** [comment]
You need to increase the build number.

**Comment by loraine-gueguen** [comment]
Thanks. Ok now, except for osx
Should I had `skip: True # [osx]` ?

**Comment by loraine-gueguen** [comment]
Not needed anymore: build ok with conda-forge channel.

**Pull request closed without merging**
