### PR TITLE
Add phylofisher

### PR DESCRIPTION
**Pull request by robert-ervin-jones**
Add phylofisher

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by robert-ervin-jones** [comment]
@BiocondaBot rebuild

**Comment by robert-ervin-jones** [comment]
@rpetit3 Do you think you can help me with this when you have some time? I'm at a loss. Thanks in advance!

**Comment by robert-ervin-jones** [comment]
Thank you! I would like to, but will probably need to speak to some of the co-authors on this project before doing so.

**Comment by robert-ervin-jones** [comment]
Still getting this error `Passing program arguments as a string may be a security hazard if combined with untrusted input`.  So, you think it might have something to do with the strict dependencies?

**Comment by rpetit3** [comment]
We'll call in the pros for this one.

@dpryan79 @bgruening  - Everything works fine until the building the container step. @robert-ervin-jones both agree the dependencies can probably be loosened, but were curious to get your thoughts on what the issue might be here? Thank you!

**Comment by robert-ervin-jones** [comment]
Thanks for your help thus far, @rpetit3

**Comment by robert-ervin-jones** [comment]
@BiocondaBot please fetch artifacts

**Comment by dpryan79** [comment]
Snakemake itself has a surprising number of dependencies, so you probably want snakemake-minimal. I've made that change. I'll go ahead and approve this PR, so you can loosen dependencies appropriately and then merge.

**Review by dpryan79 — APPROVED** [review]

**Comment by robert-ervin-jones** [comment]
@BiocondaBot please add label

**Comment by robert-ervin-jones** [comment]
@BiocondaBot please merge

**Pull request merged**
