### PR TITLE
viennarna 2.4.9

### PR DESCRIPTION
**Pull request by martin-mann**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by martin-mann** [comment]
want to ensure that pkgconfig lib information is present/installed for downstream configure checks (intarna). we got intarna travis build issues without enforcing pkgconfig to be installed, so i put it here.

no good?

**Comment by martin-mann** [comment]
i guess pkgconfig came so far with some other dependency but havent tested/checked yet

**Comment by s-will** [comment]
did it fail without pkgconfig? If you want to use pkgconfig downstream, there should be no need to specify it as build requirement here. Pkgconfig would then be needed only when building the downstream packages.

**Comment by martin-mann** [comment]
not sure, since afaik pkgconfig is used to install the according subfolder with the lib information... !?!

**Comment by martin-mann** [comment]
the vrna build most likely does not fail without pkgconfig but not sure whether or not the needed lib information is available if build without...

**Comment by s-will** [comment]
nope, one does not need pkgconfig to build a package that defines its dependencies via pkgconfig (like the vienna rna package). Concretely, this works based on the file
RNAlib2.pc.in
which is translated by the usual autotools mechanism to some RNAlib2.pc, which is then installed to the correct directory. All of this works without having pkgconfig installed

**Comment by martin-mann** [comment]
ok, thanks for this... will remove the pkgconfig dependency

**Comment by martin-mann** [comment]
macos build pending anyway...

**Pull request merged**
