### PR TITLE
Coinfinder recipe

### PR DESCRIPTION
**Pull request by fwhelan**
Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

 * `@BiocondaBot please update` will cause the BiocondaBot to merge the master branch into a PR
 * `@BiocondaBot please add label` will add the `please review & merge` label.
 * `@BiocondaBot please fetch artifacts` will post links to packages and docker containers built by the CI system. You can use this to test packages locally before merging.

For members of the Bioconda project, the following command is also available:

 * `@BiocondaBot please merge` will cause packages/containers to be uploaded and a PR merged. Someone must approve a PR first! This has the benefit of not wasting CI build time required by manually merging PRs.

If you have questions, please post them in gitter or ping `@bioconda/core` in a comment (if you are not able to directly ping `@bioconda/core` then the bot will repost your comment and enable pinging).

### CODE REVIEW

**Comment by fwhelan** [comment]
@dpryan79 I have a few auxiliary scripts that the coinfinder executable calls. They’re in /coinfinder-code/ and I’m trying to move them into the /bin so that the executable can see them. Am I on the right track?

**Comment by dpryan79** [comment]
You have the right idea, we'll see if my last change helps that along.

**Comment by dpryan79** [comment]
BTW, you can now just create branches on this repo, so you don't need to keep using your fork.

**Comment by dpryan79** [comment]
Gah, github just reverted the build.sh changes when it resolved the merge conflict. I'll fix that real quick, sorry about that.

**Comment by dpryan79** [comment]
Hmm, actually, maybe the web interface just isn't showing it, we'll see if the auxiliary scripts make it into the build artifacts.

**Comment by dpryan79** [comment]
@BiocondaBot please fetch artifacts

**Comment by dpryan79** [comment]
@bioconda-bot please merge

Looks like the scripts did indeed make it in. The container may be too large for the bot to upload in time, but we'll see.

**Comment by fwhelan** [comment]
That did it! I missed one helper script, but I should be able to fix that now..

It would have taken me a long time to parse some of the nuances of this without a helpful bioconda community. Thank you so very much for your help!

**Pull request merged**
