### PR TITLE
Update imctools to 2.1.8

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`imctools`](https://bioconda.github.io/recipes/imctools/README.html): **1.0.8** &rarr; **2.1.8**

[install with bioconda](http://bioconda.github.io/recipes/imctools/README.html) [Conda](https://anaconda.org/bioconda/imctools/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/imctools`](https://github.com//bioconda/bioconda-recipes/tree/bump/imctools/recipes/imctools) (click to view/edit other files)
Summary | An Image Mass Cytometry (IMC) file conversion tool that aims to convert IMC rawfiles (.mcd, .txt) into an intermediary ome.tiff, containing all the relevant metadata. Further it contains tools to generate simpler tiff files that can be directly be used as input files for e.g. CellProfiller, Ilastik, Fiji etc
Home | [https://github.com/BodenmillerGroup/imctools](https://github.com/BodenmillerGroup/imctools)
Releases |[https://github.com/BodenmillerGroup/imctools/tags](https://github.com/BodenmillerGroup/imctools/tags)
Author | `@BodenmillerGroup`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by esnaultc** [comment]
@BiocondaBot update

**Comment by therealgenna** [comment]
@bioconda-bot please update

**Comment by therealgenna** [comment]
@bioconda-bot please fetch artifacts

**Review by therealgenna — APPROVED** [review]
Looks good

**Comment by therealgenna** [comment]
@bioconda-bot please merge

**Pull request merged**
