### PR TITLE
Update dsk to 2.3.1 version

### PR DESCRIPTION
**Pull request by natir**
Update dsk to 2.3.1

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by natir** [comment]
@BiocondaBot update

**Comment by natir** [comment]
@BiocondaBot please add label

**Comment by dpryan79** [comment]
@bioconda-bot please fetch artifacts

**Comment by natir** [comment]
@dpryan79 After some check I see this recipes (and bcalm recipes) use a specific version of GATB-core.

In bcalm recipes [build.sh](https://github.com/bioconda/bioconda-recipes/blob/52861eeec66c85cb06b5857f6a37ef0d87dd1ea7/recipes/bcalm/build.sh) I perform a clone of gatb-core.

Shouldn't another method be used?

**Comment by dpryan79** [comment]
@natir If possible yes. Ideally gatb-core should be placed as a dependency in the host: section. However since this is using cmake that may prove incredibly difficult to get to actually work. Odds are good that gatb-core ends up getting statically compiled into the binaries, so it wouldn't affect anything except build time anyway.

**Comment by natir** [comment]
In fact a majority of GATB tools use GATB-core in static link. Besides dsk and bcalm uses a specific not release version of GATB-core.

It's why I prefer download gatb-core source code for the moment.

I will discuss with upstream maintainer to:
- replace static link by dynamic link
- avoid the usage of not release version of GATB-core
but I didn't know how many time it will take.

**Comment by natir** [comment]
@BiocondaBot please fetch artifacts

**Comment by natir** [comment]
@dpryan79 Could you merge this and #21488 ?

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Comment by natir** [comment]
Thanks !

**Pull request merged**
