### PR TITLE
Update abritamr to 1.0.12

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`abritamr`](https://bioconda.github.io/recipes/abritamr/README.html): **1.0.11** &rarr; **1.0.12**

[install with bioconda](http://bioconda.github.io/recipes/abritamr/README.html) [Conda](https://anaconda.org/bioconda/abritamr/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/abritamr`](https://github.com//bioconda/bioconda-recipes/tree/bump/abritamr/recipes/abritamr) (click to view/edit other files)
Summary | Running AMRFinderPlus for MDU
Home | [https://github.com/MDU-PHL/abritamr](https://github.com/MDU-PHL/abritamr)
Releases |[https://pypi.org/pypi/abritamr/json](https://pypi.org/pypi/abritamr/json)
Recipe Maintainer(s) | @kristyhoran, @andergs

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by andersgs** [comment]
@kristyhoran what is the difference between this PR and #36578?

**Comment by andersgs** [comment]
@kristyhoran the checks are failing because you have pinned 3.7 version of python in the conda recipe, but in the abritamr setup.py, you have pinned '<4,>=3.9' for python_requires:
```
    python_requires=">=3.9, <4",
```

**Comment by kristyhoran** [comment]
Thanks @andersgs I will fix now

**Comment by kristyhoran** [comment]
@andersgs I think I fixed it!! Thanks for patience - always learning.

**Comment by rpetit3** [comment]
closing in favor of https://github.com/bioconda/bioconda-recipes/pull/36616

**Pull request closed without merging**
