### PR TITLE
Update edta to 1.9.5

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`edta`](https://bioconda.github.io/recipes/edta/README.html): **1.9.4** &rarr; **1.9.5**

[install with bioconda](http://bioconda.github.io/recipes/edta/README.html) [Conda](https://anaconda.org/bioconda/edta/files)

Info | Link
-----|-----
Recipe | [`recipes/edta`](https://github.com//bioconda/bioconda-recipes/tree/bump/edta/recipes/edta) (click to view/edit other files)
Releases |[https://github.com/oushujun/EDTA/tags](https://github.com/oushujun/EDTA/tags)
Author | `@oushujun`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
@bioconda-bot please merge

**Comment by oushujun** [comment]
@Juke34 the `h5py` bug won't be fixed: https://github.com/tensorflow/tensorflow/issues/44467
Can you add `h5py<3.0.0` to the recipe (https://github.com/oushujun/EDTA/issues/137)? Thanks!
- Shujun

**Comment by Juke34** [comment]
@oushujun is it still needed h5py<3.0.0 to the EDTA recipe?

**Comment by oushujun** [comment]
@Juke34 Yes, and I managed to put that in the recipe: https://github.com/bioconda/bioconda-recipes/pull/26317. Some dependencies seem not compatible with python3.8, so I add another line to require python<3.7. I am not sure if this is the right way to do it, please let me know if it doesn't.

**Comment by Juke34** [comment]
It’s fine, it sounds good. Good to see that you get how the recipe works.

**Pull request merged**
