### PR TITLE
MicroHapDB: fix build number, add test invocation

### PR DESCRIPTION
**Pull request by standage**
I updated MicroHapDB from version 0.2 to 0.3 in #15037, but failed to increment the build number. This PR fixes the build number and adds a test invocation.

----------------

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [x] This PR does something else (explain below).

### CODE REVIEW

**Comment by dpryan79** [comment]
Please hold off on bumping the build number of this. There's a nightly job that looks for recipes that should have been uploaded but weren't for some reason and it should have found this. I suspect this package was lost during the transition to the conda CDN, since it appears to have been uploaded originally https://circleci.com/gh/bioconda/bioconda-recipes/54804

**Comment by standage** [comment]
> Please hold off on bumping the build number of this.

Ok. Just to be clear, do you mean "don't merge this until things are fixed" or "stop pushing to this branch until things are fixed"? Looks like I need to troubleshoot the build, but I'll halt if needed until things are settled.

**Comment by dpryan79** [comment]
I mean, “I’ll take care of this, it’s an infrastructure issue”.

**Comment by dpryan79** [comment]
Version 0.3 is up now. I suspect the package was lost in the transition to the CDN. The trick was to just hit rerun on the upload job.

**Pull request closed without merging**
