### PR TITLE
Add r-nanostringnorm and supporting recipes

### PR DESCRIPTION
**Pull request by xguse**
This PR contains changes needed to properly build the `r-nanostringnorm` R package.

### It __adds__ the following recipes:

1. bioconductor-vsn
2. r-googlevis
3. r-nanostringnorm
4. r-runit

### It __updates__ the following recipes:

1. bioconductor-limma: 
    - updates from version 3.26.3 to 3.26.7

### CODE REVIEW

**Comment by daler** [comment]
Looks good!

See #1 if you want to join the bioconda group -- once you're added you can merge PRs yourself as needed.

**Comment by xguse** [comment]
I actually am on the list.  I actually forgot that that gave me the power to do that though!  Thanks for the heads up.

Thanks a lot for the docker help again as well!

**Comment by daler** [comment]
Hmm, I don't see your username in the bioconda group (https://github.com/orgs/bioconda/people), but it looks like you've been invited. Ah well, if you end up not able to merge the next PR, let Johannes know.

**Comment by xguse** [comment]
Augustine (Gus) Dunn

Sent by MailWise<http://www.mail-wise.com/installation/2> – See your emails as clean, short chats.


-------- Original Message --------

**Comment by xguse** [comment]
Ahhh your right. I am on the longer list that is on the website I suppose. I will quirk on that tomorrow.

Sent by MailWise<http://www.mail-wise.com/installation/2> – See your emails as clean, short chats.


-------- Original Message --------

**Pull request merged**
