### PR TITLE
Update lexmapr to 0.1.3

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`lexmapr`](https://bioconda.github.io/recipes/lexmapr/README.html): **0.1.2** &rarr; **0.1.3**

[install with bioconda](http://bioconda.github.io/recipes/lexmapr/README.html) [Conda](https://anaconda.org/bioconda/lexmapr/files)

Info | Link
-----|-----
Recipe | [`recipes/lexmapr`](https://github.com//bioconda/bioconda-recipes/tree/bump/lexmapr/recipes/lexmapr) (click to view/edit other files)
Releases |[https://github.com/Public-Health-Bioinformatics/LexMapr/tags](https://github.com/Public-Health-Bioinformatics/LexMapr/tags)
Author | `@Public-Health-Bioinformatics`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/updating.html)).

### CODE REVIEW

**Comment by dfornika** [comment]
@BiocondaBot rebuild

**Comment by mbargull** [comment]
@BiocondaBot rebuild

**Comment by mbargull** [comment]
The build didn't finish because `conda`'s solver had a hard time with the choices for `nltk`. Likely caused by
https://github.com/conda-forge/nltk-feedstock/pull/6/commits/e400e09fbde3d0064bc5bb326c06fd506d00b982
https://github.com/conda-forge/nltk-feedstock/issues/7
https://github.com/nltk/nltk/blob/3.2.5/setup.py#L33-L53
https://github.com/AnacondaRecipes/nltk-feedstock/commit/b36d65e424f28fa078502b295319da31aa113b3c
. (The stall is ultimately a short-coming of `conda`.)
Pinning to `nltk 3.2.5` might make it a little easier for `conda`. The pinning is necessary anyway, see the commit message in https://github.com/bioconda/bioconda-recipes/pull/16166/commits/2e463521a970f62589f251c05248d90ea6760cf5 .

@dfornika, do you know whether the other pinned down dependencies from https://github.com/Public-Health-Bioinformatics/LexMapr/blob/v0.1.3/setup.py#L28-L32 are accurate? If some are, feel free to add/adjust them accordingly.

**Comment by dfornika** [comment]
@mbargull Thanks for taking the time to look at this and offer these suggestions.

**Comment by dfornika** [comment]
@mbargull  Success! Would you like to try adding `noarch: python` back into the recipe to see if it will build?

**Comment by mbargull** [comment]
> to try adding `noarch: python` back into the recipe to see if it will build?

Nah, that one is sadly part of the workaround to get it to build. I added an additional comment in the recipe.

The reinstate `noarch: python`, we have to do one of the following:
1. Fix `conda` to better handle those bad cases (some doofus (i.e., yours truly) was going to do that last year, but couldn't finish that work...).
2. Address https://github.com/conda-forge/nltk-feedstock/issues/7 and build a new package for `nltk` without the deps that were added in https://github.com/conda-forge/nltk-feedstock/commit/e400e09fbde3d0064bc5bb326c06fd506d00b982.
   To do that: Merge the changes from https://github.com/AnacondaRecipes/nltk-feedstock (though, for `lexmapr` to benefit from this, you need to do that for `3.2.5` before updating to the latest version.)

Feel free to tackle 2. ;). (Looks like the `nltk` feedstock maintainer is inactive, so you might need to ping `conda-forge/core` on a PR instead.)

----
Regarding the pinned dependencies from gh-16217:
Feel free to add them to this branch if they are accurate. If they can be loosened, use reasonably loose ones. Generally: As loose as possible, but as tight as needed. (I just saw that you are one of the LexMapr devs -> you may also want to apply that strategy to your upstream https://github.com/Public-Health-Bioinformatics/LexMapr/blob/v0.1.3/setup.py#L27-L33 :wink: ).

When you are finished/happy with the dependency version constrains, feel free to merge!

**Comment by dfornika** [comment]
Thanks again for all of this advice. We haven't had a chance to assess version compatibility for those libraries, so we've used tight pinning for simplicity & reproducibility. But I expect that they can probably be loosened to `major.minor.*`

I don't have commit rights on this repo, so I'm not able to merge. Would you be able to do that?

**Comment by mbargull** [comment]
> I don't have commit rights on this repo, so I'm not able to merge.

Oh, my bad! I just assumed you've been part of the `bioconda/all` team since I know I've seen you contribute a good amount; thus I somehow overlooked it saying "Contributor" instead of "Member" xD.
I've sent you an invite to `bioconda/all`, if you want to become a member.

> But I expect that they can probably be loosened to `major.minor.*`

So, for this PR, do you want
1. unpinned (current state of this PR)
   (might leave userto get broken installs if incompatible versions get chosen/installed)
2. pinned exactly (adhering to upstream `setup.py`
   (might cause trouble (insatisfiable package combinations/version constraints) if user wants to install other packages into the same environment as `lexmapr`)
3. pin to `major.minor.*`
    (some packages, e.g., `nltk` need more exact pins; it needs atleast `>=3.2.2,<3.3.0a0`, see https://github.com/nltk/nltk/blob/3.4.3/ChangeLog#L125 and https://github.com/nltk/nltk/blob/3.4.3/ChangeLog#L63)

**Pull request merged**
