### PR TITLE
Build DWGsim for OS X

### PR DESCRIPTION
**Pull request by karel-brinda**
* [x] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by bgruening** [comment]
Are the patches still needed in this package?
ping @jerowe

**Comment by karel-brinda** [comment]
I think it would be better to make the formula work without any patches because they are version-specific. I will experiment a little bit with it. I think we can pass different parameters to Make directly from the command line.

I am also wondering what is better to use for compilation: either the Samtools conda package (currently used), or the original git submodule. I think that it would be better to use the submodule as the author of the program did all the testing against that specific version. As far as I remember, conda does not clone repositories recursively; therefore, the submodule cloning step would have to be added to `build.sh`.

@bgruening @jerowe What's your opinion?

**Comment by bgruening** [comment]
If you don't need this, which your changes here indicate, I'm all in for removing the complicated patches. Maybe you can extend the tests a little bit to make sure it works reliably.

You can use submodules with conda - you just need to use `git_url:`, which we recommend and the linter will complain, but your can deactivate this linting step. However, we try to build against shared htslib or sametools libraries, as this enables us to share environments with other packages. 
For example if you use build-in htslib and ship this with your package, other packages depending on htslib will overwrite it - so this is probably not going to work. This is also the reason we pin such libraries, so that all (most?) of the bioconda packages are using one library version.

**Comment by karel-brinda** [comment]
I solved it here:
https://github.com/bioconda/bioconda-recipes/pull/4424

**Pull request closed without merging**
