### PR TITLE
Update "Update editdistance to 0.4. (#6904)"

### PR DESCRIPTION
**Pull request by mbargull**
This ~reverts~ updates commit 4c74bea06b5c3f42468d47a88202bb81ec731e9a.
~GitHub archive does not contain compiled Cython extensions.~

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by mbargull** [comment]
@cbrueffer: Was there any reason you did not use the `sdist` from PyPi in #6904 ?

**Comment by cbrueffer** [comment]
Mostly habit; good point about Cython, I'll be more careful next time.

**Comment by mbargull** [comment]
No worries! I'll fix it right now ;).

**Comment by cbrueffer** [comment]
Thanks!

**Comment by mbargull** [comment]
Huh, they apparently have their Cythonized files in their repository as well. I'll never understand those habits... So hey, your change wouldn't have mattered at all xD. Oh well..

**Pull request merged**
