### PR TITLE
debug Libmaus2 build

### PR DESCRIPTION
**Pull request by matthdsm**
----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by matthdsm** [comment]
@gt1, here's the libmaus config.log
[libmaus_config.log.txt](https://github.com/bioconda/bioconda-recipes/files/6139904/libmaus_config.log.txt)

Hope this helps
M

**Comment by matthdsm** [comment]
Hi @gt1,

I've updated the libmaus build with the latest io_lib. Could you review the config.log file to make sure everything was built correctly?

Thanks
Matthias

[libmaus2_config.log](https://github.com/bioconda/bioconda-recipes/files/6177209/libmaus2_config.log)

**Comment by gt1** [comment]
Hi Matthias,

apologies for the delay. The config.log says you are using version 2.0.772 of libmaus2, which has a broken io_lib detection routine. Please update to version 2.0.774.

German

**Comment by matthdsm** [comment]
Hi German!

Thanks for the tip. I did forget to update the version.
Having done that, everything seems to link great!
[libmaus2_config.log](https://github.com/bioconda/bioconda-recipes/files/6187879/libmaus2_config.log)

However, now I'm getting the following error during the `make` step.
```
07:44:56 BIOCONDA INFO (OUT) make[1]: Entering directory `$SRC_DIR'
07:44:56 BIOCONDA INFO (OUT) Making all in src
07:44:56 BIOCONDA INFO (OUT) make[2]: Entering directory `$SRC_DIR/src'
07:44:56 BIOCONDA INFO (OUT) $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-c++ -DHAVE_CONFIG_H -I. -I..   -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem $PREFIX/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem $PREFIX/include   -W -Wall -Wnon-virtual-dtor -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/libmaus2-2.0.774 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix  -std=c++17 -pthread -fopenmp -MT test/testThreadPool-testThreadPool.o -MD -MP -MF test/.deps/testThreadPool-testThreadPool.Tpo -c -o test/testThreadPool-testThreadPool.o `test -f 'test/testThreadPool.cpp' || echo './'`test/testThreadPool.cpp
07:44:57 BIOCONDA INFO (OUT) mv -f test/.deps/testThreadPool-testThreadPool.Tpo test/.deps/testThreadPool-testThreadPool.Po
07:44:57 BIOCONDA INFO (OUT) /bin/sh ../libtool  --tag=CXX   --mode=compile $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-c++ -DHAVE_CONFIG_H -I. -I..   -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem $PREFIX/include  -I$PREFIX/include        -I$PREFIX/include    -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem $PREFIX/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem $PREFIX/include -std=c++17 -pthread -fopenmp   -W -Wall -Wnon-virtual-dtor -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/libmaus2-2.0.774 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix  -std=c++17 -pthread -fopenmp -MT libmaus2/la-StaticInitialization.lo -MD -MP -MF libmaus2/.deps/la-StaticInitialization.Tpo -c -o libmaus2/la-StaticInitialization.lo `test -f 'libmaus2/StaticInitialization.cpp' || echo './'`libmaus2/StaticInitialization.cpp
07:44:57 BIOCONDA INFO (OUT) libtool: compile:  $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-c++ -DHAVE_CONFIG_H -I. -I.. -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem $PREFIX/include -I$PREFIX/include -I$PREFIX/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem $PREFIX/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem $PREFIX/include -std=c++17 -pthread -fopenmp -W -Wall -Wnon-virtual-dtor -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/libmaus2-2.0.774 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix -std=c++17 -pthread -fopenmp -MT libmaus2/la-StaticInitialization.lo -MD -MP -MF libmaus2/.deps/la-StaticInitialization.Tpo -c libmaus2/StaticInitialization.cpp  -fPIC -DPIC -o libmaus2/.libs/la-StaticInitialization.o
07:44:58 BIOCONDA INFO (OUT) In file included from libmaus2/StaticInitialization.cpp:218:0:
07:44:58 BIOCONDA INFO (OUT) ./libmaus2/aio/OutputStreamFactoryContainer.hpp: In static member function 'static void libmaus2::aio::OutputStreamFactoryContainer::mkdirp(const string&, uint64_t, char)':
07:44:58 BIOCONDA INFO (OUT) ./libmaus2/aio/OutputStreamFactoryContainer.hpp:285:18: error: 'std::filesystem' has not been declared
07:44:58 BIOCONDA INFO (OUT)       if ( ! std::filesystem::exists(V[i]) )
07:44:58 BIOCONDA INFO (OUT)                   ^~~~~~~~~~
07:45:02 BIOCONDA INFO (OUT) In file included from ./libmaus2/util/MemoryStatistics.hpp:24:0,
07:45:02 BIOCONDA INFO (OUT)                  from ./libmaus2/autoarray/AutoArray.hpp:48,
07:45:02 BIOCONDA INFO (OUT)                  from libmaus2/StaticInitialization.cpp:90:
07:45:02 BIOCONDA INFO (OUT) ./libmaus2/posix/PosixFunctions.hpp: In instantiation of 'static void libmaus2::posix::PosixFunctions::encodeSigned(number_type, unsigned char*, unsigned int) [with number_type = long int]':
07:45:02 BIOCONDA INFO (OUT) ./libmaus2/aio/PosixFdOutputStreamBuffer.hpp:57:94:   required from here
07:45:02 BIOCONDA INFO (OUT) ./libmaus2/posix/PosixFunctions.hpp:155:17: warning: unused variable 'ok' [-Wunused-variable]
07:45:02 BIOCONDA INFO (OUT)       bool const ok = (decodeSigned<number_type>(p,size) == num);
07:45:02 BIOCONDA INFO (OUT)                  ^~
.07:45:06 BIOCONDA INFO (OUT) make[2]: *** [libmaus2/la-StaticInitialization.lo] Error 1
07:45:06 BIOCONDA INFO (OUT) make[2]: Leaving directory `$SRC_DIR/src'
07:45:06 BIOCONDA INFO (OUT) make[1]: *** [all-recursive] Error 1
07:45:06 BIOCONDA INFO (OUT) make[1]: Leaving directory `$SRC_DIR'
07:45:06 BIOCONDA INFO (OUT) make: *** [all] Error 2
```

Is there a dependency missing or something?

Thanks for all the help
Matthias

**Comment by gt1** [comment]
Hi Matthias,

I think you need

https://github.com/bioconda/bioconda-recipes/blob/0f32dcb11fa58d19cb3f66beb6090d83cfd56b31/recipes/libmaus2/patch

when building libmaus2 using gcc 7. It uses some C++17 library features which were only experimentally implemented in gcc 7.

Hope this helps
German

**Comment by matthdsm** [comment]
Hi German,

Thanks for the input, but the patch should still be there. It's defined in the `meta.yaml` and available.

Thanks
Matthias

**Comment by gt1** [comment]
Hi Matthias,

I think you need to patch

if ( ! std::filesystem::exists(V[i]) )

to

if ( ! std::experimental::filesystem::exists(V[i]) )

This is one of the things changed between .772 and .774 due to https://gitlab.com/german.tischler/biobambam2/-/issues/95 .

**Comment by matthdsm** [comment]
@bioconda-bot please add label

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@bioconda-bot please merge

Nice work @matthdsm !

**Comment by gt1** [comment]
Thanks for all the work making this compile. Note that libmaus2 is in some parts header only, i.e. the updates do not really show until you recompile the programs using the library.

________________________________________
Von: Bioconda Bot ***@***.***>
Gesendet: Dienstag, 23. März 2021 14:46
An: bioconda/bioconda-recipes
Cc: German Tischler-Höhle; Mention
Betreff: [EXTERNAL]Re: [bioconda/bioconda-recipes] debug Libmaus2 build (#27366)

WARNING: This email was sent from an address outside the company. Do not click on any links or open any file attachments unless you recognize the sender and are confident the content is safe.

Merged #27366<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbioconda%2Fbioconda-recipes%2Fpull%2F27366&data=04%7C01%7C%7C298030d0c7284d8b87ed08d8ee021b9a%7Cf54d3069b76d43d9b2f14a23ea2ca7ce%7C0%7C0%7C637521040130699931%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ec5MHxAXb%2BtxqzQvFbYk1gUAYvl%2BRee%2BAT%2FRCuN2KA0%3D&reserved=0> into master.

**Comment by matthdsm** [comment]
Hi @gt1,

Thank you for helping us making this work.
On a related note, is it possible the last patch is something that also should be fixed in de libmaus2 code? Seems like a missing import, unrelated to building witg gcc7.
Just trying to make sense of the code, I've got zero experience with C++.

Matthias

**Pull request merged**
