### PR TITLE
add nucdiff recipe

### PR DESCRIPTION
**Pull request by zachcp**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

This PR provides a recipe for the  [nucdiff](https://github.com/uio-cels/NucDiff) program that analyzes the differences between two similar nucleotide sequences.

### CODE REVIEW

**Comment by mbargull** [comment]
Why is the strict pinning to `biopython ==1.69` needed?
Why is the packages version (also on PyPi) `0.1.1` although the contained software has version `2.0.2`?

**Comment by zachcp** [comment]
good eyes @mbargull 

the biopython ==1.69 is hack to get around a dependency issue with numpy112.  I intended to revisit.

you are completely right about the version.  This software was distributed as a set of scripts. I first packaged it for pypi but the version was not in a standard location (setup.py , __version__.py.) so I chose an arbitrary version.  You've spotted the version in the cli code. I will update the package to reflect this.

**Comment by zachcp** [comment]
Updated PR in #7477

**Comment by mbargull** [comment]
> good eyes @mbargull

good `grep` 😉
```
$ grep -rho '\<version\>.*' NucDiff-0.1.1|sort -u
version
version]
version]
version 1.1 or earlier of the License, but not also under the
version 3\n')
version=about['__version__'],
version', action='version', version='NucDiff version 2.0.2')
version number.
version of the License, the
version of this
version of this License if you rename the license and remove
version published by the license
version** - show program's version number and exit
version** - show program's version number and exit
version will be given a
```

Can you elaborate on that dependency issue?

**Pull request merged**
