### PR TITLE
Update pybel to 0.13.2

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`pybel`](https://bioconda.github.io/recipes/pybel/README.html): **0.9.3** &rarr; **0.13.2**

[install with bioconda](http://bioconda.github.io/recipes/pybel/README.html) [Conda](https://anaconda.org/bioconda/pybel/files)

Info | Link
-----|-----
Recipe | [`recipes/pybel`](https://github.com//bioconda/bioconda-recipes/tree/bump/pybel/recipes/pybel) (click to view/edit other files)
Releases |[https://pypi.org/pypi/pybel/json](https://pypi.org/pypi/pybel/json)

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by druvus** [comment]
New version seems to be py3. Also need to add `bel_resources` as dependency

**Comment by npavlovikj** [comment]
FYI, https://github.com/bioconda/bioconda-recipes/pull/17345.

**Comment by druvus** [comment]
thanks @npavlovikj

**Comment by npavlovikj** [comment]
@druvus , does the updated recipe look ok to you?

**Comment by npavlovikj** [comment]
Thanks @dpryan79 !

You have probably seen this, but the last merges to master have been failing with:
```
#!/bin/sh -eo pipefail
# Blocked due to free-plan-executor-unavailable
# Blocked due to free-plan-executor-unavailable
# Blocked due to free-plan-executor-unavailable
# Blocked due to free-plan-executor-unavailable
# 
# -------
# Warning: This configuration was auto-generated to show you the message above.
# Don't rerun this job. Rerunning will have no effect.
false
Exited with code 1
```

**Comment by dpryan79** [comment]
Oh, nope, that's new to me. I wonder if they took away our unlimited number of hours.

**Comment by npavlovikj** [comment]
Yeah, looks like the CircleCI plan and/or hours are exhausted :(

**Comment by dpryan79** [comment]
That happens within the first week of every month, so I suspect that's not the root of the problem.

**Pull request merged**
