### PR TITLE
bump hifiasm

### PR DESCRIPTION
**Pull request by kdm9**
The autobumper seems to choke given hifiasm's mixed tag schemes (see https://github.com/bioconda/bioconda-utils/issues/834), so this manually bumps it to the latest version.

### CODE REVIEW

**Comment by kdm9** [comment]
@BiocondaBot please update

**Comment by kdm9** [comment]
@BiocondaBot please add label

**Comment by kdm9** [comment]
@BiocondaBot please fetch artifacts

**Review by rpetit3 — APPROVED** [review]

**Comment by rpetit3** [comment]
@BiocondaBot please merge

**Pull request merged**
