### PR TITLE
Update galaxy-ml to 0.7.7

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`galaxy-ml`](https://bioconda.github.io/recipes/galaxy-ml/README.html): **0.7.5** &rarr; **0.7.7**

[install with bioconda](http://bioconda.github.io/recipes/galaxy-ml/README.html) [Conda](https://anaconda.org/bioconda/galaxy-ml/files)

Info | Link
-----|-----
Recipe | [`recipes/galaxy-ml`](https://github.com//bioconda/bioconda-recipes/tree/bump/galaxy_ml/recipes/galaxy-ml) (click to view/edit other files)
Releases |[https://pypi.org/pypi/Galaxy-ML/json](https://pypi.org/pypi/Galaxy-ML/json)
Recipe Maintainer(s) | @qiagu

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/updating.html)).

### CODE REVIEW

**Comment by qiagu** [comment]
@bioconda/core The test took so long, but there is no sign of errors. Could someone have a look? Thanks.

**Comment by bgruening** [comment]
The error was: `pip._internal.exceptions.InstallationError`
I restarted the build, let's see.

**Comment by qiagu** [comment]
@bgruening  Thanks a lot!

**Comment by qiagu** [comment]
@bgruening I really want `tensorflow-gpu` instead of `tensorflow` in the environment, but my concern is that `tensorflow-gpu` doesn't support macos. For configuring galaxy tools, we probably have to do manual replacement.

**Comment by bgruening** [comment]
@qiagu we can skip OSX, this is an option if we want to deal with GPUs.

**Comment by qiagu** [comment]
@bgruening I like the idea of skipping macos. Let's do that. Do I need to make a new PR?

**Comment by qiagu** [comment]
@bgruening Please update the `tensorflow` dependency to `tensorflow-gpu`. Thanks

**Comment by qiagu** [comment]
@bgruening Looks great now. Much much appreciated!

**Pull request merged**
