### PR TITLE
Update r-bcbiornaseq to 0.3.26

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`r-bcbiornaseq`](https://bioconda.github.io/recipes/r-bcbiornaseq/README.html): **0.2.9** &rarr; **0.3.26**

[install with bioconda](http://bioconda.github.io/recipes/r-bcbiornaseq/README.html) [Conda](https://anaconda.org/bioconda/r-bcbiornaseq/files)

Info | Link
-----|-----
Recipe | [`recipes/r-bcbiornaseq`](https://github.com//bioconda/bioconda-recipes/tree/bump/r_bcbiornaseq/recipes/r-bcbiornaseq) (click to view/edit other files)
Releases |[https://github.com/hbc/bcbioRNASeq/tags](https://github.com/hbc/bcbioRNASeq/tags)
Author | `@hbc`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by dpryan79** [comment]
This needs r-basejump to be updated.

**Comment by mjsteinbaugh** [comment]
@dpryan79 I'll work on the r-basejump recipe update today

**Comment by dpryan79** [comment]
This needs r-acidplots and r-deseqanalysis to be added.

**Comment by mjsteinbaugh** [comment]
Working on it!

**Comment by mjsteinbaugh** [comment]
This needs `r-bcbiobase` to update to v0.6.10, then it should be safe to merge.

**Comment by dpryan79** [comment]
Some days I really hate you @bioconda-bot

**Comment by mjsteinbaugh** [comment]
@dpryan79 I started a new pull request

**Pull request closed without merging**
