### PR TITLE
Create recipe for igphyml

### PR DESCRIPTION
**Pull request by PertuyF**
Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it. Note that if you are not already a member of the bioconda project (meaning that you can't add this label), please ping `@bioconda/core` so that your PR can be reviewed and merged (please note if you'd like to be added to the bioconda project). Please see https://github.com/bioconda/bioconda-recipes/issues/15332 for more details.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by dpryan79** [comment]
I have no clue why automake is constructing a borked Makefile on OSX.

**Comment by PertuyF** [comment]
Hi @dpryan79 ,
Thanks for your efforts with OSX build! there are [specific instructions](https://igphyml.readthedocs.io/en/latest/install.html#mac-os-x) for this in the doc.

Likely `CC` is already defined in the docker image at build time, but `MACLLVM` might be missing?

**Comment by dpryan79** [comment]
Yeah, `CC` is set, but `MACLLVM` not. This package is quite the mess though, I wonder if it's easier to not use its build script.

**Comment by PertuyF** [comment]
As you see fit, you have much more experience than me in this domain.
If you can help with what to do, I can find some time to test.

**Comment by PertuyF** [comment]
Closing as replaced by #18945

**Pull request closed without merging**
