### PR TITLE
Update geno2phenotb to 1.0.1

### PR DESCRIPTION
**Pull request by msmdev**
Add missing dependencies (requests, tqdm) to recipe.

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by msmdev** [comment]
@not-a-feature, the version changes didn't solve the problem. I assume that the issue isn't caused by the run requirements but by the host requirements. This is somehow strange, since they didn't change since the last successful build, but maybe there were changes of the bioconda-build utils, which are causing this.

**Comment by msmdev** [comment]
@not-a-feature, have you tried to build locally with `bioconda-utils build --docker --mulled-test --git-range master --packages geno2phenotb`?

**Comment by msmdev** [comment]
@not-a-feature, the error during test_linux didn't change at all by your changes. Maybe you could revert all changes to the last successfully building recipe (missing requests and tqdm) and check if it is still building... If not, the problem is with bioconda-utils...

**Comment by msmdev** [comment]
@not-a-feature, this is still not a full revert of the recipe, since the changes in the description persist... This shouldn't have an effect but as you know you never know...
To be sure, really revert to 548ec0e6c569e984922a082bd86828e373f8062f
Thx!

**Comment by not-a-feature** [comment]
> @not-a-feature, this is still not a full revert of the recipe, since the changes in the description persist... This shouldn't have an effect but as you know you never know... To be sure, really revert to [548ec0e](https://github.com/bioconda/bioconda-recipes/commit/548ec0e6c569e984922a082bd86828e373f8062f) Thx!

Im slowly reverting each step to figure out at which point the changes broke the building pipeline.  
- Unfortunately neither a partial revert:
    - removing the request / tqdm requirements
    - keeping the rest (`commands / extra / summary`)  
- a almost full revert (reverting everything except the build number and summary)
- nor a complete revert (except the build number)

worked.

The pipeline continues to fail with `package python-3.7.15-haa1d7c7_0 is excluded by strict repo priority` as error.

**Comment by msmdev** [comment]
@not-a-feature, yep - I'm not surprised, since this error shouldn't result from the made changes.
So there must be a change in the bioconda-utils or I don't know.
The increment in the build number shouldn't cause problems, right?

**Comment by msmdev** [comment]
> @not-a-feature, yep - I'm not surprised, since this error shouldn't result from the changes made. So there must be a change in the bioconda-utils or I don't know. The increment in the build number shouldn't cause problems, right?

Or mb. a change in pip? Since this was the only unpinned host requirement? XD

**Comment by not-a-feature** [comment]
Well, there is a version conflict with the current version of pip (23.1.2, released 2023-04-26) and our setuptools version.
Pip requires 67.7.2, but setuptools is pinned to 65.5.0.*
As this pip version is already so old, it shouldn't be the reason of the error.

Nevertheless i suggest to remove the seutptools pinning and set pip to the current version.

**Comment by msmdev** [comment]
Nope, didn't help... still the same error exactly... -.-

**Comment by not-a-feature** [comment]
With the EOL of python 3.7 on the 27 June 2023 the version 3.7.15 was kicked out of conda-forge.

**Comment by msmdev** [comment]
Now the tests fail with conflicts again - despite all the updates.
The reported errors are:
- Encountered problems while solving:
-   - package pandas-0.25.3-py38hb3f55d8_0 requires setuptools <60.0.0, but none of the providers can be installed
-   - package numpy-base-1.21.5-py37hf524024_1 has constraint numpy 1.21.5 py37he7a7128_1 conflicting with numpy-1.21.5-py310h45f3432_1

**Comment by bgruening** [comment]
This is unfortunately expected. Your pins are way too strict. Please use realistic pins that can work together to resolve this problem.

**Comment by msmdev** [comment]
> This is unfortunately expected. Your pins are way too strict. Please use realistic pins that can work together to resolve this problem.

Our pins are well tested and worked together very well so far (e.g. in conda environments, with pip...). They originate from the fact that we are using trained ML models and can only guarantee that they function correctly using the pinned versions.

**Comment by msmdev** [comment]
Anyway, we will try if we can relax some pins a bit - but we need to be cautious here...

**Comment by msmdev** [comment]
@bgruening could you please merge this, close PR #42265, and mark geno2phenoTB 1.0.0 as broken?

**Comment by msmdev** [comment]
@BiocondaBot please add label

**Comment by dpryan79** [comment]
@BiocondaBot please fetch artifacts

**Review by dpryan79 — APPROVED** [review]

**Pull request merged**
