### PR TITLE
Update UCSC CellBrowser to 1.2.2

### PR DESCRIPTION
**Pull request by pcm32**
Updates UCSC CellBrowser to 1.2.2

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by pcm32** [comment]
@maximilianh does the current version require any extras here? Thanks!

**Comment by dpryan79** [comment]
@pcm32 For an individual package that shouldn't be needed. The templates for this are under the `scripts` directory and need updating every year or two as UCSC changes things up. It's kind of a mess and as long as you only need the updated cellbrowser you should be good to go :)

**Comment by dpryan79** [comment]
Oh, this accidentally got grouped together with the UCSC kent's tools! Ignore the reason it was blacklisted, that was a complete mistake!

**Comment by maximilianh** [comment]
Hu? Sorry don't understand. But same for the kent tools: should we ping
someone if we change the kent tools? We try to never change the default
arguments and just add more options and never change existing options.

**Comment by dpryan79** [comment]
@maximilianh It's not needed. We have a script that generates all of the recipes for Kent's tools. This is kind of hacky on our part and prone to breaking (I think currently things aren't compiling because of some sort of SQL error because we're often missing a dependency). So, this is more of an "it's us, not you" sort of thing :)

**Review by dpryan79 — APPROVED** [review]

**Comment by maximilianh** [comment]
I recently made this, in the hope that his makes life easier for
re-packagers like you:
https://github.com/ucscGenomeBrowser/kent-core

I could get rid of the libpng dependency, but probably not the
mysql-client-dev dependency, as some tools need mysql. other than that, I
think it only needs libz and openssl...

**Comment by pcm32** [comment]
@maximilianh could you check the meta.yml on this PR and advice on whether there is any change in dependencies or scripts to tell from the previous version to this one? If you are happy with the state of this, we can merge.

**Comment by maximilianh** [comment]
looked at meta.yml and better understand: you want to know if I require any
other python dependencies. No, I don't and I hope I never will. :-) Good to
know that you need to know about these. I'll try to think of this package
if I ever add one, hopefully never.

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
Thanks, everyone!

**Pull request merged**
