### PR TITLE
Update brooklyn_plot to 0.0.4

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`brooklyn_plot`](https://bioconda.github.io/recipes/brooklyn_plot/README.html): **0.0.3** &rarr; **0.0.4**

[install with bioconda](http://bioconda.github.io/recipes/brooklyn_plot/README.html) [Conda](https://anaconda.org/bioconda/brooklyn_plot/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/brooklyn_plot`](https://github.com//bioconda/bioconda-recipes/tree/bump/brooklyn_plot/recipes/brooklyn_plot) (click to view/edit other files)
Summary | Gene co-expression and transcriptional bursting pattern recognition tool in single cell/nucleus RNA-sequencing data
Home | [https://github.com/arunhpatil/brooklyn/](https://github.com/arunhpatil/brooklyn/)
Releases |[https://pypi.org/pypi/brooklyn_plot/json](https://pypi.org/pypi/brooklyn_plot/json)
Recipe Maintainer(s) | @arunhpatil, @mhalushka

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Review by arunhpatil — APPROVED** [review]

**Comment by arunhpatil** [comment]
@BiocondaBot please add label

**Comment by arunhpatil** [comment]
@BiocondaBot please fetch artifacts

**Comment by arunhpatil** [comment]
@BiocondaBot please merge

**Comment by arunhpatil** [comment]
@BiocondaBot please merge

**Comment by arunhpatil** [comment]
@mencian, thank you for your help. The conda bot is merging the changes, should I quash and merge?

**Comment by mencian** [comment]
No problem, @arunhpatil! And yes, please press the 'Squash and Merge' button if the recipe looks good to you.

**Pull request merged**
