### PR TITLE
Update gambit to 1.1.0

### PR DESCRIPTION
**Pull request by jlumpe**
Update gambit to 1.1.0

### CODE REVIEW

**Comment by jlumpe** [comment]
@BiocondaBot please add label

**Comment by jlumpe** [comment]
Small question for someone more experienced than me with Conda recipes: I added dependencies for OpenMP shared libraries (`libomp` / `llvm-openmp`) (not sure why the recipe was working for previous versions without them, probably it was the update to Cython 3). I followed [this section](https://conda-forge.org/docs/maintainer/knowledge_base/#openmp) of conda-forge's maintainer documentation.

I added the dependencies under the `host` section, but then realized that the linked source says to add them under the `build` section. I'm not very clear about the difference between the two. Could someone tell me if it's good as-is or should be changed?

**Comment by johanneskoester** [comment]
From the conda docs (about the host section, see https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#host):

> This section was added in conda-build 3.0. It represents packages that need to be specific to the target platform when the target platform is not necessarily the same as the native build platform.

The conda-forge docs suggest to me that openmp will be just needed at compile time. Hence, it belongs into build since it cannot really be specific to the target platform then.

**Review by johanneskoester — APPROVED** [review]

**Comment by martin-g** [comment]
> I added the dependencies under the `host` section, but then realized that the linked source says to add them under the `build` section. I'm not very clear about the difference between the two. Could someone tell me if it's good as-is or should be changed?

My understanding is that those should be in `host`. Only build `tools` should be in `build`. All library dependencies should be in `host`.
I have seen other recipes with both ways.
IMO this is not a stopper to merge the PR!

**Comment by jlumpe** [comment]
@johanneskoester @martin-g Hoping you can help with something else. I'm seeing 1.1.0 as available now but only builds for Python 3.12. The package's [page](https://bioconda.github.io/recipes/gambit/README.html) on the Bioconda website lists the minimum Python version as 3.12, when it should be 3.9. Any ideas about why this might be?

I was able to create an environment with Python 3.9 and the rest of the dependencies copied from the recipe, so I don't think it's a dependency restricting the minimum version.

**Comment by martin-g** [comment]
I also don't have an idea why it selected just 3.12 here.

**Comment by jlumpe** [comment]
I realized for 1.0.1 I didn't have version constraints on the `python` dependency directly and instead used:

```
build:
  skip: True  # [py < 37]
```

(when the minimum supported version was 3.7). This line got removed in #48485, which I don't really understand the reason for.

The current recipe has the Python version range in `host`, but no range in `run`. I'm having a hard time telling from the documentation what's the correct way to do it, and it seems like there is a lot of variation in existing recipes.

**Comment by jlumpe** [comment]
Actually seems like I [asked](#30370) this exact question years ago when I first submitted the question and forgot about it... It seems the correct way to do it is indeed with the `skip: True`, the recipes doing it the other way might all be `noarch` packages.

Submitted a new PR #52571.

**Pull request merged**
