### PR TITLE
add r-virfinder pkg

### PR DESCRIPTION
**Pull request by wclose**
Adding new R based package for detecting viral contigs in metagenomic sequencing data.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by dpryan79** [comment]
Can you ask the author to tag a 1.1 release? We can just build this then.

**Comment by wclose** [comment]
@dpryan79 I just emailed them so I will wait to hear back. It appears they've left their previous institution though so I'm not sure response time. Are there alternative approaches? I saw another recipe that used `git_url` in bioconda, is that something that's supported? I saw conda-forge apparently doesn't allow it.

**Comment by dpryan79** [comment]
@wclose Go ahead and merge this when you're ready :)

**Comment by wclose** [comment]
Thanks for helping out again @dpryan79!

**Pull request merged**
