### PR TITLE
Remove Hail from bioconda

### PR DESCRIPTION
**Pull request by danking**
Hello!

This PR removes Hail from bioconda. The Hail team gets a steady stream of support requests due to the very out of date version of Hail in bioconda. Hail's current version is 0.2.100 but this package is 0.2.61. Users can easily install the latest version of Hail through pip: `pip install hail`.

Removing Hail from bioconda saves precious developer time on a  small & open source project.

Thanks for your understanding.

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by danking** [comment]
@BiocondaBot please add label

**Comment by rpetit3** [comment]
@danking If you are interested. we could update the recipe so that the bot automatically creates PRs for new releases.

The current recipe is not setup to work with the bot

**Comment by danking** [comment]
Forgive my bluntness. I'm not quite interested. AFAICT, we would still need to maintain the copy of our requirements.txt file in the meta.yaml file. I don't see any benefits to us or our users given that we distribute wheel files through PyPI.

**Comment by bgruening** [comment]
Removing this recipe will not remove the package. If there are people interested to host this package here is should stay and being updated. Please feel free to communicate to your users that conda is not officially supported and close the issues. But I guess the simple fact that your users searching in conda for your tool says something about the usefulness and the benefits conda brings :-)

**Comment by danking** [comment]
Do conda channels have a notion of yanking like PyPI? These old versions have known bugs and should not be used for scientific research. If this conda package is not being maintained, we should yank the old versions so that no one accidentally installs bad versions of Hail.

**Comment by bgruening** [comment]
Sure, we can mark them as broken, if they are broken. But this is also counterproductive for reproducibility. For some use-cases you want to have old version, or recover your virtual env for the paper that you published last year.

**Comment by dpryan79** [comment]
I'm going through our recipe blacklist at the moment and can probably update hail to the most recent release (that way it'll be updated more-or-less automatically when you pin new releases).

**Pull request closed without merging**
