### PR TITLE
Add bwread 0.0.3

### PR DESCRIPTION
**Pull request by endrebak**
----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title
* New recipes not directly relevant to the biological sciences need to be submitted to [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please add the `please review & merge` label.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>BiocondaBot commands</summary>
      
Everyone has access to the following BiocondaBot commands, which can be given in a comment:

  * `@BiocondaBot please update` will cause the BiocondaBot to merge the master branch into a PR
  * `@BiocondaBot please add label` will add the `please review & merge` label.
  * `@BiocondaBot please fetch artifacts` will post links to packages and docker containers built by the CI system. You can use this to test packages locally before merging.

For members of the Bioconda project, the following command is also available:

 * `@BiocondaBot please merge` will cause packages/containers to be uploaded and a PR merged. Someone must approve a PR first! This has the benefit of not wasting CI build time required by manually merging PRs.
</details>

### CODE REVIEW

**Comment by druvus** [comment]
Fails with the following error

```
06:38:26 BIOCONDA INFO (OUT) conda.exceptions.UnsatisfiableError: The following specifications were found to be in conflict:
06:38:26 BIOCONDA INFO (OUT)   - pyranges -> ncls[version='>=0.0.50'] -> python[version='>=3.7,<3.8.0a0'] -> python_abi[version='3.7.*,*',build=*_cp37m] -> pypy[version='<0a0']
06:38:26 BIOCONDA INFO (OUT)   - python[version='>=3.8,<3.9.0a0']```

**Comment by dpryan79** [comment]
This installs now but some of the tests are failing. Perhaps you can look into why.

**Comment by druvus** [comment]
thanks @dpryan79 !

@endrebak could you as original submitter and upstream author take a look at the failed test?

**Comment by endrebak** [comment]
I will look into it. Thanks for the comments :)

**Comment by endrebak** [comment]
It failed the tests on macOS because pkg_utils was missing. It is a part of setuptools. Added it to the meta.yaml.

**Comment by dpryan79** [comment]
Glad the fix was relatively easy, thanks @endrebak!

**Comment by dpryan79** [comment]
@bioconda-bot please fetch artifacts

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Pull request merged**
