### PR TITLE
Update QualiMap to most up2date version with bed support

### PR DESCRIPTION
**Pull request by apeltzer**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by corburn** [comment]
The build number should start from zero. The 2.2.2a directory is not required. I'm not sure if this is a beta release or date versioning.

**Comment by apeltzer** [comment]
Hey! Will take care of that - the previous release was also from such a date release and used 2.2.2a, so I followed that guideline in here as well.

**Comment by apeltzer** [comment]
That building takes ages - is that normal?

**Comment by corburn** [comment]
@apeltzer probably, yes.

**Comment by apeltzer** [comment]
Build Timeout after 5hours.... hmm...

**Comment by chapmanb** [comment]
Thanks for the his update. I don't appear to have permissions to re-try builds but given nothing changed in the build.sh and it doesn't look too complex, I'm hoping that a restart will build cleanly. Johannes, any chance of re-kicking the build?

**Comment by apeltzer** [comment]
I can also bump it by simply adding a newline somewhere in the build, thus retriggering it. Its a bit weird, that this timed out after 5 hours ?

**Comment by apeltzer** [comment]
Same issue again @chapmanb / @johanneskoester .... will run into a timeout...

**Comment by chapmanb** [comment]
Thanks for re-kicking this. I've been testing locally and it looks like the issue is that the bioconductor dependencies for qualimap are pretty heavyweight. I know you added these as well so probably have strong feelings about them but I commented out `bioconductor-repitools`, which is the worst offender and brings in a whole load of packages. This will at least tell us if it can finish in reasonable time without this and then decide how best to proceed.

**Comment by apeltzer** [comment]
Its a bit weird though, as we'll need these for some steps in qualimap. As I'm building my containers using a conda environment, I can add that as external dependencies but some people might not know whats the problem here - though it seems that helped resolve the issues!

**Pull request merged**
