### PR TITLE
Update segzoo to 1.0.11

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`segzoo`](https://bioconda.github.io/recipes/segzoo/README.html): **1.0.7** &rarr; **1.0.11**

[install with bioconda](http://bioconda.github.io/recipes/segzoo/README.html) [Conda](https://anaconda.org/bioconda/segzoo/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/segzoo`](https://github.com//bioconda/bioconda-recipes/tree/bump/segzoo/recipes/segzoo) (click to view/edit other files)
Summary | System for turnkey analysis of semi-automated genome annotations
Home | [https://github.com/hoffmangroup/segzoo](https://github.com/hoffmangroup/segzoo)
Releases |[https://pypi.org/pypi/segzoo/json](https://pypi.org/pypi/segzoo/json)
Recipe Maintainer(s) | @mmendez12

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by charlesreid1** [comment]
Looks like segzoo pins the python version to 3.8, causing the failure:

```
2022-09-22T09:36:45.5895236Z 09:36:45 BIOCONDA INFO (OUT) ERROR: Package 'segzoo' requires a different Python: 3.10.6 not in '==3.8.*'
```

**Comment by charlesreid1** [comment]
@mmendez12  Looks like segzoo pins the python version to 3.8, causing the failure:

```
2022-09-22T09:36:45.5895236Z 09:36:45 BIOCONDA INFO (OUT) ERROR: Package 'segzoo' requires a different Python: 3.10.6 not in '==3.8.*'
```

https://github.com/hoffmangroup/segzoo/commit/65614d213fc61feb419fc9d1a3b2f9570fa5bf98

**Comment by mmendez12** [comment]
@charlesreid1 I set python run version to 3.8.* in the segzoo recipe. Do you know why the test installs python 3.10?

**Comment by dpryan79** [comment]
This doesn't work under any python version other than 3.8?

**Comment by mmendez12** [comment]
@dpryan79 It should work on any python version >= 3.7.
How should I proceed to update the meta.yaml file?

I pulled the changes from this PR (bump/segzoo) to my fork (https://github.com/mmendez12/bioconda-recipes/tree/segzoo) and updated the requirements for the python version.
However, the PR was not updated.

**Comment by dpryan79** [comment]
@BiocondaBot please fetch artifacts

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@BiocondaBot please merge

**Pull request merged**
