### PR TITLE
Update to gromacs 2018

### PR DESCRIPTION
**Pull request by stain**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

Note that this updates to the latest gromacs 2018.

It might be that this can be optimized better, enabling openmp, gpu and hwloc.

```
GROMACS version:    2018
Precision:          single
Memory model:       64 bit
MPI library:        thread_mpi
OpenMP support:     disabled
GPU support:        disabled
SIMD instructions:  AVX_256
FFT library:        fftw-3.3.5-fma-sse2-avx-avx2-avx2_128
RDTSCP usage:       enabled
TNG support:        enabled
Hwloc support:      disabled
Tracing support:    disabled
Built on:           2018-02-06 15:38:42
Built by:           stain@biggie [CMAKE]
Build OS/arch:      Linux 4.13.0-26-generic x86_64
Build CPU vendor:   Intel
Build CPU brand:    Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz
Build CPU family:   6   Model: 58   Stepping: 9
Build CPU features: aes apic avx clfsh cmov cx8 cx16 f16c htt intel lahf
mmx msr nonstop_tsc pcid pclmuldq pdcm popcnt pse rdrnd rdtscp sse2 sse3
sse4.1 sse4.2 ssse3 tdt x2apic
C compiler:
/tmp/miniconda/conda-bld/gromacs_1517931402329/_t_env/bin/cc GNU 4.8.5
C compiler flags:    -mavx    -Wno-unknown-pragmas  -O3 -DNDEBUG
-funroll-all-loops -fexcess-precision=fast
C++ compiler:
/tmp/miniconda/conda-bld/gromacs_1517931402329/_t_env/bin/c++ GNU 4.8.5
C++ compiler flags:  -mavx    -std=c++11  -Wno-unknown-pragmas  -O3
-DNDEBUG -funroll-all-loops -fexcess-precision=fast
```

### CODE REVIEW

**Comment by kyleabeauchamp** [comment]
Are we OK with AVX 256?  What happens on older machines?

**Comment by stain** [comment]
I guess AVX_256 detection and similar would depend on the build node.

BTW, I don't think many would be running Gromacs on older hardware as it's computationally heavy - I was actually hoping rather to get a more optimized binary. :)

It turns out that using `cudatoolkit` is pointless to add GPU support, as Anaconda's cudatoolkit does not include the header files and so we can't compile against it. I can add the OpenCL instead, but then the local installation would need the correct binding depending on their GPU type.

openmpi support was easy enough to add and works, so I can enable that.

I wondered if it would be a good idea to make sub-versions like 2016.0.openmpi etc. similar to how Debian builds [multiple variants of Gromacs](https://packages.debian.org/source/sid/gromacs)

**Comment by stain** [comment]
With my commit 82d502e this now improved to include OpenMP and OpenCL:

```
GROMACS version:    2018
Precision:          single
Memory model:       64 bit
MPI library:        thread_mpi
OpenMP support:     enabled (GMX_OPENMP_MAX_THREADS = 64)
GPU support:        OpenCL
SIMD instructions:  AVX_256
FFT library:        fftw-3.3.7-sse2-avx
RDTSCP usage:       enabled
TNG support:        enabled
Hwloc support:      hwloc-1.11.0
Tracing support:    disabled
Built on:           2018-02-07 13:55:47
Built by:           root@biggie [CMAKE]
Build OS/arch:      Linux 4.13.0-26-generic x86_64
Build CPU vendor:   Intel
Build CPU brand:    Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz
Build CPU family:   6   Model: 58   Stepping: 9
Build CPU features: aes apic avx clfsh cmov cx8 cx16 f16c htt intel lahf mmx msr nonstop_tsc pcid pclmuldq pdcm popcnt pse rdrnd rdtscp sse2 sse3 sse4.1 sse4.2 ssse3 tdt x2apic
C compiler:         /opt/conda/conda-bld/gromacs_1518011525016/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/cc GNU 4.8.5
C compiler flags:    -mavx     -O3 -DNDEBUG -funroll-all-loops -fexcess-precision=fast  
C++ compiler:       /opt/conda/conda-bld/gromacs_1518011525016/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/c++ GNU 4.8.5
C++ compiler flags:  -mavx    -std=c++11   -O3 -DNDEBUG -funroll-all-loops -fexcess-precision=fast  
OpenCL include dir: /opt/conda/conda-bld/gromacs_1518011525016/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/include
OpenCL library:     /opt/conda/conda-bld/gromacs_1518011525016/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/libOpenCL.so
OpenCL version:     2.0

(root) stain@biggie://tmp/anaconda$ ldd bin/gmx
	linux-vdso.so.1 =>  (0x00007fffccb74000)
	libhwloc.so.5 => /tmp/anaconda/bin/../lib/libhwloc.so.5 (0x00007f5bb24df000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f5bb22d7000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f5bb20ba000)
	libOpenCL.so.1 => /usr/lib/x86_64-linux-gnu/libOpenCL.so.1 (0x00007f5bb1eaf000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f5bb1b2d000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f5bb1824000)
	libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1 (0x00007f5bb1602000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f5bb13ec000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f5bb1022000)
	libxml2.so.2 => /tmp/anaconda/bin/../lib/./libxml2.so.2 (0x00007f5bb0cbc000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f5bb0ab8000)
	libicui18n.so.58 => /tmp/anaconda/bin/../lib/./libicui18n.so.58 (0x00007f5bb05b8000)
	libicuuc.so.58 => /tmp/anaconda/bin/../lib/./libicuuc.so.58 (0x00007f5bb01b9000)
	libicudata.so.58 => /tmp/anaconda/bin/../lib/./libicudata.so.58 (0x00007f5bae6b9000)
	libz.so.1 => /tmp/anaconda/bin/../lib/./libz.so.1 (0x00007f5bae49c000)
	liblzma.so.5 => /tmp/anaconda/bin/../lib/./liblzma.so.5 (0x00007f5bae277000)
	libiconv.so.2 => /tmp/anaconda/bin/../lib/./libiconv.so.2 (0x00007f5badf88000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f5bb2719000)
```

I did not enable MPI as several tests where failing in the automatic build with mpirun.

**Comment by bgruening** [comment]
> I did not enable MPI as several tests where failing in the automatic build with mpirun.

@stain do you remember if these tests failed in the Docker container tests? If so you need to use the extended base image, which has openssh/ssl installed.

**Comment by bgruening** [comment]
@kyleabeauchamp are you ok with merging this? Imho @stain did a great job here and this is a great first version to collect feedback from our cheminformatics community.

**Comment by kyleabeauchamp** [comment]
LGTM

**Comment by stain** [comment]
@bgruening the test failing has to do with Gromacs test system, really, their OpenMPI tests assume you are running on an existing OpenMPI infrastructure that you want to test (which would make sense if you are installing Gromacs there :) ).  

The issues came up that it needed like [`--allow-run-as-root`](https://www.open-mpi.org/doc/v2.0/man1/mpirun.1.php#sect22) to `mpirun` because the BioConda Docker test runs as root (I believe for both images). 

This can be done in Gromacs install by modifying `"-DMPIEXEC_PREFLAGS=--allow-run-as-root"`.

Then the MPI tests of Gromacs failed due to number of cores available (they would reasonably assume you have at least 4 cores if you have an MPI cluster) - this would of course vary depending on build slave as well, which would only have localhost. However adding also `-npernode` to the same `-DMPIEXEC_PREFLAGS` blew up somewhere in CMAKE as it merged it to a single arg..

So while this could be monkey-patched in (e.g. skip that test) I am not sure if many BioConda users will be using it to with an OpenMPI cluster. We think it's more likely that people will use Gromacs locally with BioConda to do the data prep stages, and then submit jobs to their cluster which has Gromacs compiled locally for their particular hardware configuration (e.g. Nvidia Cuda toolkit).

**Comment by kyleabeauchamp** [comment]
I agree that most MPI users will have their own builds.

**Comment by stain** [comment]
Thanks! Yes, @bgruening I would also hope that we could get those, as BioConda is perhaps the best tool for maintaining bioinformatics software installed on clusters. 

I am thinking to do sub-directory versions like 2016.0.openmpi.cuda (so only one of those could be installed at a time) -- would those build automatically or would they each need to be initially at the top-level directly under `gromacs/`?

**Comment by bgruening** [comment]
Subdirectories are completely fine in BioConda. Have a look at samtools for example.

**Comment by mbargull** [comment]
@bioconda/core: Can somebody label `gromacs-2018` as `broken`?
One thing is that this shouldn't have been merged as the CI only showed it as `passed` since the branch was very outdated and thus just hadn't any CircleCI config.
Another thing is that a dependency `ocl-id` is missing.
But what got me deeply confused is as to why the Linux build succeeded: https://circleci.com/gh/bioconda/bioconda-recipes/2082.
Straight from the package's tarball:
* `info/recipe/meta.yaml.template`:
```yaml
about:
  home: http://www.gromacs.org/
  license: GNU Lesser General Public License (LGPL)
  summary: GROMACS is a versatile package to perform molecular dynamics.

package:
  name: gromacs
  version: 2018

build:
  number: 0

# See http://manual.gromacs.org/documentation/
# for latest release. Note that version scheme changed from 
# 5.1 to 2016.x and 2018.x
source:
  fn: gromacs-2018.tar.gz
  url: https://ftp.gromacs.org/pub/gromacs/gromacs-2018.tar.gz
  md5: 6467ffb1575b8271548a13abfba6374c
  sha256: deb5d0b749a52a0c6083367b5f50a99e08003208d81954fb49e7009e1b1fd0e9

requirements:
  build:
    - openmp # [linux]
    - ocl-icd
    - libhwloc
    - fftw
    - gcc  # [linux]
    - llvm  # [osx]
    - cmake
    - perl 
    - python >=2.7,<3
  run:
    - ocl-icd
    - openmp # [linux]
    - fftw
    - libgcc  # [linux]
    - libhwloc

test:
  commands:
    - gmx -version

```
* `info/recipe/meta.yaml`:
```yaml
# This file created by conda-build 2.1.18
# meta.yaml template originally from:
# /opt/recipe, last modified Sun Feb 11 09:12:45 2018
# ------------------------------------------------

package:
    name: gromacs
    version: '2018'
source:
    fn: gromacs-2018.tar.gz
    md5: 6467ffb1575b8271548a13abfba6374c
    sha256: deb5d0b749a52a0c6083367b5f50a99e08003208d81954fb49e7009e1b1fd0e9
    url: https://ftp.gromacs.org/pub/gromacs/gromacs-2018.tar.gz
build:
    noarch: ''
    noarch_python: false
    number: '0'
    string: '0'
requirements:
    build:
        - openmp 5.0.0 0
        - mpfr 3.1.5 0
        - xz 5.2.3 0
        - cloog 0.18.0 0
        - isl 0.12.2 0
        - pip 9.0.1 py27_1
        - openssl 1.0.2n 0
        - wheel 0.30.0 py27_2
        - mpc 1.0.3 4
        - readline 7.0 0
        - bzip2 1.0.6 1
        - rhash 1.3.4 0
        - zlib 1.2.11 0
        - cmake 3.10.0 4
        - fftw 3.3.7 0
        - libiconv 1.15 0
        - certifi 2018.1.18 py27_0
        - tk 8.6.7 0
        - expat 2.2.5 0
        - gmp 6.1.2 0
        - clangdev 5.0.0 default_0
        - python 2.7.14 4
        - libssh2 1.8.0 2
        - llvmdev 5.0.0 default_0
        - libuv 1.11.0 0
        - gcc 4.8.5 7
        - icu 58.2 0
        - krb5 1.14.2 0
        - ca-certificates 2018.1.18 0
        - setuptools 38.4.0 py27_0
        - system 5.8 2
        - ncurses 5.9 10
        - perl 5.22.0.1 0
        - curl 7.55.1 0
        - libxml2 2.9.7 0
        - ocl-icd 2.2.9 4
        - sqlite 3.20.1 2
        - libhwloc 1.11.5 0
    run:
        - ocl-icd
        - openmp
        - fftw
        - libgcc
        - libhwloc
test:
    commands:
        - gmx -version
about:
    home: http://www.gromacs.org/
    license: GNU Lesser General Public License (LGPL)
    summary: GROMACS is a versatile package to perform molecular dynamics.
extra:
    final: true
```

WTH is going on with the build section in the rendered `meta.yaml`???

**Comment by bgruening** [comment]
@mbargull are you under OSX?
This package works for me:

```
(gromacs) bag@bag:~/projects/code/galaxytools/tools/sklearn$ gmx -version
                          :-) GROMACS - gmx, 2018 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov  Herman J.C. Berendsen    Par Bjelkmar   
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra    Gerrit Groenhof  
 Christoph Junghans   Anca Hamuraru    Vincent Hindriksen Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson    
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg   Pieter Meulenhoff 
   Erik Marklund      Teemu Murtola       Szilard Pall       Sander Pronk   
   Roland Schulz     Alexey Shvetsov     Michael Shirts     Alfons Sijbers  
   Peter Tieleman    Teemu Virolainen  Christian Wennberg    Maarten Wolf   
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2017, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx, version 2018
Executable:   /home/bag/miniconda3/envs/gromacs/bin/gmx
Data prefix:  /home/bag/miniconda3/envs/gromacs
Working dir:  /home/bag/projects/code/galaxytools/tools/sklearn
Command line:
  gmx -version

GROMACS version:    2018
Precision:          single
Memory model:       64 bit
MPI library:        thread_mpi
OpenMP support:     enabled (GMX_OPENMP_MAX_THREADS = 64)
GPU support:        OpenCL
SIMD instructions:  AVX2_256
FFT library:        fftw-3.3.7-sse2-avx
RDTSCP usage:       enabled
TNG support:        enabled
Hwloc support:      hwloc-1.11.0
Tracing support:    disabled
Built on:           2018-02-11 09:16:43
Built by:           root@prealloc-bwcms7lf-4e53d87d-eec9-494f-8a45-abc0a48dc5c8 [CMAKE]
Build OS/arch:      Linux 4.4.0-96-generic x86_64
Build CPU vendor:   Intel
Build CPU brand:    Intel(R) Xeon(R) CPU @ 2.30GHz
Build CPU family:   6   Model: 63   Stepping: 0
Build CPU features: aes apic avx avx2 clfsh cmov cx8 cx16 f16c fma htt intel lahf mmx msr nonstop_tsc pcid pclmuldq pdpe1gb popcnt pse rdrnd rdtscp sse2 sse3 sse4.1 sse4.2 ssse3 x2apic
C compiler:         /home/bag/miniconda3/envs/gromacs/bin/cc GNU 4.8.5
C compiler flags:    -march=core-avx2     -O3 -DNDEBUG -funroll-all-loops -fexcess-precision=fast  
C++ compiler:       /home/bag/miniconda3/envs/gromacs/bin/c++ GNU 4.8.5
C++ compiler flags:  -march=core-avx2    -std=c++11   -O3 -DNDEBUG -funroll-all-loops -fexcess-precision=fast  
OpenCL include dir: /home/bag/miniconda3/envs/gromacs/include
OpenCL library:     /home/bag/miniconda3/envs/gromacs/lib/libOpenCL.so
OpenCL version:     2.
```

`ocl-icd` is also a conda-forge package?

**Comment by mbargull** [comment]
> Another thing is that a dependency ocl-id is missing.

> @mbargull are you under OSX?

> ocl-icd is also a conda-forge package?

Ah, my bad, I had a typo (`ocl-icd` vs `ocl-id`) that I copy pasted. And no, I'm on Linux, but didn't actually run `conda create gromacs`, which I guess I should've...
Ok, so it works, just needs a `skip: True  # [osx]` to make the macOS CI jobs pass.

It just had me puzzled as I also didn't see `- ocl-icd 2.2.9 4` in the rendered `meta.yaml` -- and I, apparently, wrongly remembered that only `conda-build 3` recorded the actually used build requirements.

Must've not gotten enough sleep -- sorry for the noise.

**Comment by bgruening** [comment]
@mbargull all good happens me too often :)

**Comment by stain** [comment]
I wonder if there is an issue also with cpu flags on Linux, the x64 linux binary fails to run here:

```
stain@biggie:~$ gmx -version
Illegal instruction (core dumped)
```

```cat /proc/cpuinfo
..
processor	: 3
vendor_id	: GenuineIntel
cpu family	: 6
model		: 58
model name	: Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz
stepping	: 9
microcode	: 0x1c
cpu MHz		: 2890.680
cache size	: 4096 KB
physical id	: 0
siblings	: 4
core id		: 1
cpu cores	: 2
apicid		: 3
initial apicid	: 3
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm cpuid_fault epb pti tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm ida arat pln pts
bugs		: cpu_insecure
bogomips	: 5781.36
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:
```

gdb says

```
Program terminated with signal SIGILL, Illegal instruction.
#0  0x00000000004c479f in gmx::erfinv(double) ()
#1  0x0000000000ae6ca3 in gmx::TabulatedNormalDistribution<float, 14u>::makeTable() ()
#2  0x000000000040d17e in _GLOBAL__sub_I__ZN3gmx27TabulatedNormalDistributionIfLj14EE8c_table_E ()
#3  0x00000000015e2aad in __libc_csu_init ()
#4  0x00007f260edf67bf in __libc_start_main (main=0x40caf0 <main>, argc=1, 
    argv=0x7ffdd08c7c68, init=0x15e2a50 <__libc_csu_init>, fini=<optimised out>, 
    rtld_fini=<optimised out>, stack_end=0x7ffdd08c7c58) at ../csu/libc-start.c:247
#5  0x000000000040e3f1 in _start ()
```

What's the output of `gmx -version` test on the build system?

**Comment by mbargull** [comment]
Am running on old hardware currently, which doesn't have AVX, so of course I get an expected `Illegal instruction` for `vmovsd`:
```
|(gdb) file gmx
Reading symbols from gmx...(no debugging symbols found)...done.
|(gdb) run -version
Starting program: /home/maba/code/conda/bioconda/envs/gromacs/bin/gmx -version
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".

Program received signal SIGILL, Illegal instruction.
0x0000000000ae6c8a in gmx::TabulatedNormalDistribution<float, 14u>::makeTable() ()
|(gdb) disas 0x0000000000ae6c8a,+8
Dump of assembler code from 0xae6c8a to 0xae6c92:
=> 0x0000000000ae6c8a <_ZN3gmx27TabulatedNormalDistributionIfLj14EE9makeTableEv+90>:	vmovsd 0xb017de(%rip),%xmm4        # 0x15e8470
End of assembler dump.
```
Can you show the output of `disas THE_ADDRESS_SIGILL_WAS_ENCOUNTERED,+8` in `gdb`?

**Comment by mbargull** [comment]
Ah, overlooked that you already posted that address. So that is:
```
|(gdb) disas 0x00000000004c479f,+8
Dump of assembler code from 0x4c479f to 0x4c47a7:
   0x00000000004c479f <_ZN3gmx6erfinvEd+111>:	vfmadd213sd 0x1130fd0(%rip),%xmm4,%xmm3        # 0x15f5778
End of assembler dump.
```
which means not only AVX but also FMA instructions are used.

**Pull request merged**
