### PR TITLE
Update r-brio to 0.3.2

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`r-brio`](https://bioconda.github.io/recipes/r-brio/README.html): **0.2.2** &rarr; **0.3.2**

[install with bioconda](http://bioconda.github.io/recipes/r-brio/README.html) [Conda](https://anaconda.org/bioconda/r-brio/files)

Info | Link
-----|-----
Recipe | [`recipes/r-brio`](https://github.com//bioconda/bioconda-recipes/tree/bump/r_brio/recipes/r-brio) (click to view/edit other files)
Releases |[https://github.com/acidgenomics/brio/tags](https://github.com/acidgenomics/brio/tags)
Recipe Maintainer(s) | @mjsteinbaugh
Author | `@acidgenomics`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/updating.html)).

### CODE REVIEW

**Comment by mjsteinbaugh** [comment]
Seeing this error pop up, and I'm not entirely sure how to fix the issue:

```
Error: package ‘rtracklayer’ was installed by an R version with different internals; it needs to be reinstalled for use with this R version
```

```
r-base:                            3.6.1-h6e652e1_3           conda-forge
bioconductor-rtracklayer:          1.36.6-0                   bioconda
```

**Comment by mjsteinbaugh** [comment]
Some related posts:

- https://github.com/conda-forge/r-upsetr-feedstock/issues/5
- https://github.com/davidaknowles/leafcutter/issues/87

**Comment by mjsteinbaugh** [comment]
rtracklayer recipe needs to be updated to v1.44.0 or v1.44.2 for r36 build.

**Comment by mjsteinbaugh** [comment]
@dpryan79 The recipe solver is attempting to pick a very old version of rtracklayer (1.36.6), instead of using the recommended Bioconductor 3.9 release (1.44.0). I'm having trouble getting the recipe to build with this dependency. Here's the current rtracklayer version list, for reference:

```sh
conda search bioconductor-rtracklayer
```

```
# Name                       Version           Build  Channel
bioconductor-rtracklayer          1.30.1               0  bioconda
bioconductor-rtracklayer          1.32.2        r3.3.1_1  bioconda
bioconductor-rtracklayer          1.34.1        r3.3.1_0  bioconda
bioconductor-rtracklayer          1.34.2        r3.3.1_1  bioconda
bioconductor-rtracklayer          1.34.2        r3.3.2_1  bioconda
bioconductor-rtracklayer          1.34.2        r3.4.1_1  bioconda
bioconductor-rtracklayer          1.36.6               0  bioconda
bioconductor-rtracklayer          1.38.0        r3.4.1_0  bioconda
bioconductor-rtracklayer          1.38.3        r3.4.1_0  bioconda
bioconductor-rtracklayer          1.40.6  r341h470a237_0  bioconda
bioconductor-rtracklayer          1.40.6  r351h470a237_0  bioconda
bioconductor-rtracklayer          1.42.1  r351h1de35cc_0  bioconda
bioconductor-rtracklayer          1.42.1  r351hc2b1221_1  bioconda
bioconductor-rtracklayer          1.44.0   r36h01d97ff_1  bioconda
```

**Comment by mjsteinbaugh** [comment]
```
12:13:02 BIOCONDA INFO (OUT) conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-64: {"bioconductor-rtracklayer[version='>=1.44.0']"}
```

**Comment by dpryan79** [comment]
You'll need patience on this. The bulk branch is slowly churning through all of the bioconductor packages at the moment, it will get to rtracklayer in the next few days.

**Comment by mjsteinbaugh** [comment]
Awesome thanks @dpryan79

**Pull request merged**
