### PR TITLE
Update Segway

### PR DESCRIPTION
**Pull request by rcwchan**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

Note: I also ran into #4553

### CODE REVIEW

**Comment by rcwchan** [comment]
Not sure why the Mac OSX test passes, but the Linux one doesn't...

**Comment by rcwchan** [comment]
Not sure why this is failing when the requirements for Segway have not changed between 1.4 and 1.4.3

**Comment by rcwchan** [comment]
So I had to change `$PYTHON$ to `python` to get `setup.py` to run, not sure why. Now I get this error:

```
Traceback (most recent call last):
  File "setup.py", line 9, in <module>
    from segway import __version__
  File "/opt/conda/conda-bld/recipe_1495815468344/work/segway-1.4.3/segway/__init__.py", line 2, in <module>
    from version import __version__
ImportError: No module named 'version'

```

**Comment by rcwchan** [comment]
@ericr86 The build worked correctly using my modified temporary segway build, so version.py is indeed the issue. I just gave it permissions 755 so that it was the same as the other py files. Could you please update the pypi host?

Thanks!

**Comment by EricR86** [comment]
The permissions have been updated on the latest commit.

**Comment by rcwchan** [comment]
Segway bitbucket commit though, not pypi host?

**Comment by rcwchan** [comment]
`version.py`'s permissions have been updated (triggering a new Segway release on pypi--thanks @EricR86), but the Travis CI build is still failing with the same error. @bgruening I'm stumped as to why, would you mind please taking a look at this?

**Comment by simonvh** [comment]
Have you tried changing:

```
from version import __version__
```

to

```
from segway.version import __version__
```
?

**Comment by EricR86** [comment]
the segway/__init__.py module file does the import of version. In that directory (segway) you can import version and anything from it no problem. Is there a way to check what is currently on the python path? Like say printing out sys.path?

Also why do we have to use the "python" command explicitly for this to work and we seemingly cannot use the $PYTHON environment variable set by the build machine? What is the difference? Does one set up a different python path?

**Comment by simonvh** [comment]
In Python 3 you can't do this and you get exactly this error. However, given that you run python explicitly, might that be Python 3 by any chance?

**Comment by rcwchan** [comment]
@simonvh This is possible (I am not sure exactly how the build machine works), though the build/test is run only for py27 according to the `meta.yaml` file? Is there a way to force the build machine to invoke python2.7 instead?

Perhaps this is related to not being able to run python through `$PYTHON`?

Thanks so much for all the help!

**Comment by simonvh** [comment]
Why can't you use the $PYTHON variable? What's the error there?

**Comment by rcwchan** [comment]
@simonvh The build machine gives the following message when using $PYTHON:

`/opt/conda/conda-bld/recipe_1495747542684/work/segway-1.4.3/conda_build.sh: line 5: /opt/conda/conda-bld/recipe_1495747542684/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/python: No such file or directory`

(Changeset d5489cb: https://travis-ci.org/bioconda/bioconda-recipes/jobs/236165216)

**Comment by simonvh** [comment]
So I have tried to look into this, but I don't have any clues. To me it looks like a conda issue. It might be worth posting an issue [over there](https://github.com/conda/conda/issues). @bioconda/core any other ideas?

**Comment by johanneskoester** [comment]
We are using an old version of conda/conda-build because of other unsolved bugs that occurred in a later version (see bioconda/bioconda-utils#123). Until we use the latest version, we cannot really report bugs there. Or did you try with the latest conda-version locally?

**Comment by johanneskoester** [comment]
Actually, our conda has been updated since you last tried. Let me restart your build...

**Comment by rcwchan** [comment]
Thanks so much for all the help, @simonvh and @johanneskoester!!

**Pull request merged**
