### PR TITLE
Adding description metadata to THAPBI PICT

### PR DESCRIPTION
**Pull request by peterjc**
* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [X] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [X] This PR updates an existing recipe.
* [X] This PR does something else (explain below).

This is in a sense a test case for #4420, to confirm that this all we need to do to have the description appear on the Anaconda website https://anaconda.org/bioconda/thapbi-pict and the Anaconda Navigator graphical tool

### CODE REVIEW

**Comment by bgruening** [comment]
@peterjc I don't think you need to bump the build number here. We do not want a new package, isn't it?

**Comment by peterjc** [comment]
If we can update the metadata (on Anaconda) without a new package, sure. I'll do that now...

**Comment by dpryan79** [comment]
@bioconda-bot update

**Comment by dpryan79** [comment]
@bioconda-bot please update

**Pull request merged**
