### PR TITLE
Refactor dependency version pinning, include boost.

### PR DESCRIPTION
**Pull request by johanneskoester**
This allows to pin the boost version in recipes using jinja2 templating. E.g., you can write

```
package:
  name: mypackage
  version: 0.1

build:
  number: 0
  string: boost{{CONDA_BOOST}}_{{PKG_BUILDNUM}}

requirements:
  build:
    - boost >=1.55,{{CONDA_BOOST}}*

  run:
    - boost {{CONDA_BOOST}}*
```

### CODE REVIEW

**Comment by bgruening** [comment]
Like it! Is there any standard we can follow? Wondering what other projects are doing.

**Comment by johanneskoester** [comment]
The way I posted above is what the Continuum guys favor. It mimics the way Python and Numpy pinning with x.x is hardcoded. At some point, we need to decide which other libs should be pinned.

**Comment by bgruening** [comment]
Great! Thanks a lot!

**Comment by acaprez** [comment]
Hmm, so the Travis build for `master` I started a few minutes ago failed with `NameError: name 'CONDA_NPY' is not defined`.  I wonder if that's related to the changes here in `build-packages.py`?

**Comment by johanneskoester** [comment]
Yes it is. I hope to fix it with PR #1211. Sorry for that :-)!

**Comment by acaprez** [comment]
No problem - thanks!

**Pull request merged**
