### PR TITLE
Update nextstrain-cli to 5.0.0

### PR DESCRIPTION
**Pull request by tsibley**
Supersedes <https://github.com/bioconda/bioconda-recipes/pull/37627>.

### CODE REVIEW

**Comment by tsibley** [comment]
Repushed after rebasing on latest `master`.

**Comment by tsibley** [comment]
@BiocondaBot please add label

**Comment by tsibley** [comment]
@BiocondaBot please fetch artifacts

**Comment by tsibley** [comment]
Built packages work well for me locally with some spot testing.

**Review by corneliusroemer — APPROVED** [review]

**Comment by corneliusroemer** [comment]
@BiocondaBot please merge

**Pull request merged**
