### PR TITLE
Add bioconductor-alpine recipe

### PR DESCRIPTION
**Pull request by upendrak**
* [y ] I have read the guidelines above.
* [y ] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by bgruening** [comment]
@upendrak we only need the meta.yaml file and the build.sh file from you. You commited more then 1000 files :)
Can you create a new PR with only these recipe files?

**Comment by bgruening** [comment]
I killed the tests, you still have too many files in this PR :(

**Comment by bgruening** [comment]
I think it was this commit: https://github.com/bioconda/bioconda-recipes/pull/2950/commits/b9ef9e2c323865cea5648bceb80ee3d95dc3c32f

**Comment by upendrak** [comment]
Going to fix the PR's

**Pull request closed without merging**
