### PR TITLE
VirMet

### PR DESCRIPTION
**Pull request by ozagordi**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by ozagordi** [comment]
The osx build was successful. The linux build failed with the error message
`conda.exceptions.CondaOSError: OS error: failed to link (src='/opt/conda/pkgs/mkl-2017.0.1-0/lib/libmkl_vml_avx512_mic.so', dst='/opt/conda/conda-bld/recipe_1495467973262/_t_env/lib/libmkl_vml_avx512_mic.so', type=1, error=OSError(28, 'No space left on device'))`

It doesn't seem to depend on the recipe.

**Comment by daler** [comment]
@bgruening this has been showing up recently (e.g. https://github.com/bioconda/bioconda-recipes/pull/4703#issuecomment-303092799). Do you think this could somehow be related to recent mulled-build changes? I don't see anything in the mulled-build code that would have changed this, and locally containers aren't accumulating.

**Comment by bgruening** [comment]
@daler this is because we still build all packages 3 times I think.

**Comment by ozagordi** [comment]
Is there anything I should do here? I don't think I can even restart the build in Travis.

**Comment by daler** [comment]
@bgruening so conda package cache is the issue rather than docker? The mulled-build images are only like 1MB, so I can't imagine that would be causing the space limitation. Maybe we have something piling up in `/tmp` when building?

**Comment by daler** [comment]
@ozagordi the recent build system fixes worked; I restarted the build and everything looks fine so I'll merge it.

**Comment by ozagordi** [comment]
Thanks!

**Pull request merged**
