### PR TITLE
Mikado

### PR DESCRIPTION
**Pull request by lucventurini**
* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [X] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [X] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

Hi @daler, as discussed, here is the updated version 1.1.1 for Mikado. I have tested it on my machine with conda build, and I hope it will compile without errors on Bioconda as well.
I have also removed the version requests for libmagic and python-magic, as requested, so we can test whether now bioconda behaves appropriately i.e. it prefers the conda-forge versions.
Best

### CODE REVIEW

**Comment by daler** [comment]
@lucventurini great! See https://github.com/bioconda/bioconda-recipes/issues/8408, I'd like to get some feedback there before making the changes to labels. Your choice: you can wait till that's resolved (a day or two?) or if you want to get v1.1 in quickly, then you can use the same libmagic and python-magic version pinning you used before to get the tests to pass.

**Comment by lucventurini** [comment]
Hi @daler , unfortunately, bioconda still prefers its own broken versions of libmagic and python-magic over the functional versions in conda-forge, that's the reason of the build failures :-(

**Comment by lucventurini** [comment]
@daler, sorry, I had not seen your comment! I will leave this build here until the "broken" tags are officially passed onto the bioconda channel.

Thanks!

**Comment by daler** [comment]
@lucventurini I marked `python-magic` as "deprecated" and `libmagic` as "broken" and restarted the tests. Let's see how they go . . .

**Comment by lucventurini** [comment]
@daler it looks like they passed :-) Thank you for your support! Would you be able to release this into the wild?

**Comment by daler** [comment]
Great! If you'd like to be part of the team, let me know (or post to #1) and then you can merge your own updates in the future. But for now I'll merge this one.

**Pull request merged**
