### PR TITLE
Update smoothxg to 0.7.1

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`smoothxg`](https://bioconda.github.io/recipes/smoothxg/README.html): **0.7.0** &rarr; **0.7.1**

[install with bioconda](http://bioconda.github.io/recipes/smoothxg/README.html) [Conda](https://anaconda.org/bioconda/smoothxg/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/smoothxg`](https://github.com//bioconda/bioconda-recipes/tree/bump/smoothxg/recipes/smoothxg) (click to view/edit other files)
Summary | Local reconstruction of variation graphs using partial order alignment
Home | [https://github.com/pangenome/smoothxg](https://github.com/pangenome/smoothxg)
Releases |[https://github.com/pangenome/smoothxg/releases](https://github.com/pangenome/smoothxg/releases)
Recipe Maintainer(s) | @AndreaGuarracino
Author | `@pangenome`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by subwaystation** [comment]
@AndreaGuarracino Maybe you need to follow https://stackoverflow.com/questions/26128144/cmake-android-toolchain-error-running-link-command-no-such-file-or-director?
Or what could be the problem? Wrong linker version?

**Comment by subwaystation** [comment]
Maybe the problem is `CMAKE_EXE_LINKER_FLAGS` ?

**Comment by subwaystation** [comment]
Or the `cmake` version is too old?

**Comment by subwaystation** [comment]
Maybe it has to do with @pjotrp changes in https://github.com/pangenome/smoothxg/pull/198/files where he now requires gcc-multilib?

**Comment by AndreaGuarracino** [comment]
No static binary, but to fix the issue I had to remove @pjotrp's changes!

**Comment by AndreaGuarracino** [comment]
@BiocondaBot please merge

**Review by AndreaGuarracino — APPROVED** [review]

**Pull request merged**
