### PR TITLE
Update watchdog-wms to make JARs and helper scripts better accessible

### PR DESCRIPTION
**Pull request by klugem**
Make JARs and helper scripts better accessible by creating additional soft links.

### CODE REVIEW

**Comment by klugem** [comment]
WIP - please do not merge.

**Comment by klugem** [comment]
Looks that it tries to verify that the build process is running on macOS while it is executed on linux.
I have no idea what causes the problem....

Can anyone give me a hint ?

=======================
14:04:28 BIOCONDA INFO (OUT) Traceback (most recent call last):
14:04:28 BIOCONDA INFO (OUT)   File "/opt/conda/bin/conda-build", line 11, in <module>
14:04:28 BIOCONDA INFO (OUT)     sys.exit(main())
14:04:28 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 474, in main
14:04:28 BIOCONDA INFO (OUT)     execute(sys.argv[1:])
14:04:28 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 465, in execute
14:04:28 BIOCONDA INFO (OUT)     verify=args.verify, variants=args.variants)
14:04:28 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.7/site-packages/conda_build/api.py", line 209, in build
14:04:28 BIOCONDA INFO (OUT)     notest=notest, need_source_download=need_source_download, variants=variants)
14:04:28 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.7/site-packages/conda_build/build.py", line 2863, in build_tree
14:04:28 BIOCONDA INFO (OUT)     notest=notest,
14:04:28 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.7/site-packages/conda_build/build.py", line 2150, in build
14:04:28 BIOCONDA INFO (OUT)     newly_built_packages = bundlers[pkg_type](output_d, m, env, stats)
14:04:28 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.7/site-packages/conda_build/build.py", line 1504, in bundle_conda
14:04:28 BIOCONDA INFO (OUT)     files = post_process_files(metadata, initial_files)
14:04:28 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.7/site-packages/conda_build/build.py", line 1363, in post_process_files
14:04:28 BIOCONDA INFO (OUT)     post_build(m, new_files, build_python=python)
14:04:28 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.7/site-packages/conda_build/post.py", line 1174, in post_build
14:04:28 BIOCONDA INFO (OUT)     post_process_shared_lib(m, f, prefix_files, host_prefix)
14:04:28 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.7/site-packages/conda_build/post.py", line 1122, in post_process_shared_lib
14:04:28 BIOCONDA INFO (OUT)     mk_relative_osx(path, host_prefix, m.config.build_prefix, files=files, rpaths=rpaths)
14:04:28 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.7/site-packages/conda_build/post.py", line 399, in mk_relative_osx
14:04:28 BIOCONDA INFO (OUT)     assert sys.platform == 'darwin'
14:04:28 BIOCONDA INFO (OUT) AssertionError

**Comment by klugem** [comment]
Seems that also the previous working version fails now.

**Comment by klugem** [comment]
> Can anyone give me a hint ?

It seems to be caused by _core_lib/external/getopt_mac_

**Comment by klugem** [comment]
-.-

**Comment by dpryan79** [comment]
@bioconda-bot please merge

Good detective work @klugem !

**Comment by klugem** [comment]
@dpryan79 thx! :)

**Pull request merged**
