### PR TITLE
Reinstate python-bioext build

### PR DESCRIPTION
**Pull request by jmarshall**
Our _build.sh_ removes the Cython-generated `*.c` files, but _setup.py_ lists only __tn93.pyx_ as a Cython extension. So the build now fails due to a missing *BioExt/align/_align.c* because that file has been removed by _build.sh_ but not rebuilt from *BioExt/align/_align.pyx*. It is hard to understand how this has ever worked!

This PR fixes the build by correcting _build.sh_ to avoid removing non-Cython C and C++ source files, and patching _setup.py_ to `cythonize()` all the _*.pyx_-containing extensions so that the _.c_ files are rebuilt.

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by jmarshall** [comment]
> It is hard to understand how this has ever worked!

The answer to that is that removing these files in _build.sh_ was a recent change (4d4b87ca5997884264a58ce24ac71e5b7666176b) that caused the **bulk** branch breakage observed for this package. Properly cythonizing them completes the change — and causing them to be rebuilt with a recent Cython is indeed a good thing.

**Comment by jmarshall** [comment]
@BiocondaBot please add label

**Review by daler — APPROVED** [review]

**Comment by daler** [comment]
@BiocondaBot please fetch artifacts

**Comment by daler** [comment]
@BiocondaBot please merge

**Comment by jmarshall** [comment]
This has not been built for Python 3.10. Has the relevant build infrastructure update been deployed to the **master** branch?

**Pull request merged**
