### PR TITLE
Update r-tmae to 1.0.3

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`r-tmae`](https://bioconda.github.io/recipes/r-tmae/README.html): **1.0.2** &rarr; **1.0.3**

[install with bioconda](http://bioconda.github.io/recipes/r-tmae/README.html) [Conda](https://anaconda.org/bioconda/r-tmae/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/r-tmae`](https://github.com//bioconda/bioconda-recipes/tree/bump/r_tmae/recipes/r-tmae) (click to view/edit other files)
Summary | Tests and visualizations for mono-allelicly expressed variants.
Home | [https://github.com/gagneurlab/tMAE](https://github.com/gagneurlab/tMAE)
Releases |[https://github.com/gagneurlab/tMAE/tags](https://github.com/gagneurlab/tMAE/tags)
Recipe Maintainer(s) | @c-mertes, @mumichae
Author | `@gagneurlab`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Review by JakeLehle — APPROVED** [review]
Love me some R packages. These changes look fine to bump r-tmae to version 1.0.3

**Comment by nickhsmith** [comment]
So there was a mistake in this original version push. We removed the release, but have since fixed the problem, and recreated the new release (1.0.3) today. Does that affect the version bump?

**Comment by nickhsmith** [comment]
@BiocondaBot autobump

**Comment by nickhsmith** [comment]
@BiocondaBot please add label

**Comment by c-mertes** [comment]
@nickhsmith please bump the version to 1.0.4. As I understand it, it does not work to update an existing release as this could potentially end up in inconsistencies.

**Pull request merged**
