### PR TITLE
Update neofox to 1.1.0

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`neofox`](https://bioconda.github.io/recipes/neofox/README.html): **1.0.2** &rarr; **1.1.0**

[install with bioconda](http://bioconda.github.io/recipes/neofox/README.html) [Conda](https://anaconda.org/bioconda/neofox/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/neofox`](https://github.com//bioconda/bioconda-recipes/tree/bump/neofox/recipes/neofox) (click to view/edit other files)
Summary | Annotation of mutated peptide sequences (mps) with published or novel potential neo-epitope descriptors
Home | [https://github.com/tron-bioinformatics/neofox](https://github.com/tron-bioinformatics/neofox)
Releases |[https://pypi.org/pypi/neofox/json](https://pypi.org/pypi/neofox/json)
Recipe Maintainer(s) | @priesgo, @franla23

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by priesgo** [comment]
The dependencies have been updated in this release of NeoFox they needed to be updated in the recipe too. Let's see if it passes tests now, but I am checking with some colleagues if we still need R as a dependency, it may be the case that we can remove this dependency, do not merge just yet.

**Comment by priesgo** [comment]
The linter keeps saying that it needs cython in the host requirements, but it is there. Not sure where this comes from, I am leaving this for a while, if anyone has any hint it will be welcomed.

**Comment by mencian** [comment]
I have added the `skip_lints` subsection to skip the `cython_must_be_in_host` lint. Now there is a new error while solving the build environment related to `pysam` and `blast`:
```
- package pysam-0.19.1-py27hc2126ed_0 requires libdeflate >=1.10,<1.11.0a0, but none of the providers can be installed
- package blast-2.10.1-pl526he19e7b1_0 requires perl-json, but none of the providers can be installed
```
Is it absolutely necessary to have such strict pins for `pysam` and `blast`?

**Comment by priesgo** [comment]
Thanks for your help @mencian and apologies for late answer. I am now looking into rerunnning to see the latest error after loosening dependencies versions. The reason to fix dependencies was to ensure reproducibility, but if it does not work...

**Comment by mencian** [comment]
@priesgo Removing the R packages from `host` seems to have done the trick. Thanks for following up!

**Comment by priesgo** [comment]
Many thanks @mencian !

**Pull request merged**
