### PR TITLE
 add r-inline recipe

### PR DESCRIPTION
**Pull request by sebastian-luna-valero**
* [X] I have read the guidelines above.
* [X] This PR adds a new recipe.
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

Add recipe for:
https://cran.r-project.org/web/packages/inline/index.html

@bioconda/core please review

### CODE REVIEW

**Comment by johanneskoester** [comment]
Looks good. Btw., you can also create a PR for more than one recipe. As long as it won't build longer than an hour, it should be fine.

**Comment by sebastian-luna-valero** [comment]
Thanks! 

I was doing one by one due to dependencies between them. The docker image was complaining when testing locally. Is this not a problem on Travis?

**Comment by bgruening** [comment]
@sebastian-luna-valero the bioconda build environment should create a DAG of your dependencies and build one after the other in the correct order. Everything else is a bug. We are currently working heavily on the build-environment, so it can be that we introduced a bug. Let us know if this is the case.

**Comment by sebastian-luna-valero** [comment]
Great, many thanks for your hard work!

**Pull request merged**
