### PR TITLE
ci: remove workarounds

### PR DESCRIPTION
**Pull request by mbargull**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [ ] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [x] This PR does something else (explain below).

@bioconda/core
This does:
1. reenable CircleCI cache
2. reinstate the separate lint job for branches other than `master`/`bulk` (i.e., PRs)
3. remove some temporary workarounds
4. improve the error message for outdated CI config
5. update to a newer Miniconda version, because why not :)

### CODE REVIEW

**Comment by mbargull** [comment]
This is ready for merge. It can be merged before CI finishes because the second to last commit passed. The last commit (linting on `upload-*`/`nightly-*` jobs) is just to retain current behavior.
So, the most important changes are: reenable cache, reenable lint job for PRs.

**Comment by mbargull** [comment]
Thanks @bgruening for the review.
The build just failed because `bioconda-utils:cb3-migration` requires Python `>=3.6` and `3.5` was picked up (see https://github.com/bioconda/bioconda-utils/pull/311#discussion_r197338510). I just now cherry picked and pushed the commit for `python>=3.6`.

**Comment by bgruening** [comment]
i.o.!

**Comment by colinbrislawn** [comment]
@mbargull 

>Please update it to the latest version of the upstream master branch.
You can do this, e.g., by running...

Most helpful error message I've even seen. I want to give you this small trophy: 🏆

**Pull request merged**
