### PR TITLE
Update Mothur to 1.38.1.1.

### PR DESCRIPTION
**Pull request by acaprez**
* [X] I have read the guidelines above.
* [ ] This PR adds a new recipe.
* [X] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

This updates the `Makefile` patching for the new version of Mothur. xref #2997 

ping @bgruening, @mdehollander - went ahead and did this as a new PR, since I don't think I can push to the branch in #2997.  Hope that's ok - let me know if there's a better way.

### CODE REVIEW

**Comment by mdehollander** [comment]
I am fine with a new PR. Currently I don't have time to have a look at it myself. I see that this build is also failing. I compiled it by hand on our system and then everything was fine.

**Comment by acaprez** [comment]
Ok, great.  Yeah it's failing with the same error a lot of the build are failing with.  See #3080 and #3075.  It builds fine for me via `simulate_travis.py` locally.

**Comment by daler** [comment]
@acaprez @mdehollander #3080 should now be fixed, please rebase and try it out.

**Comment by acaprez** [comment]
@daler - looks good.  Thanks!

**Pull request merged**
