### PR TITLE
Fix old builds of viennarna

### PR DESCRIPTION
**Pull request by dpryan79**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by dpryan79** [comment]
@s-will This should fix building of the older versions of viennarna. Please note, however, that you don't need to keep every version around on github unless you expect to need to tweak them in the future. The packages will still be available via `conda install` regardless.

**Comment by s-will** [comment]
Hey @dpryan79, thanks a lot for fixing the recipes!
Also thanks for the comment about the older recipes; you are right that most of them are likely not needed anymore.

**Comment by dpryan79** [comment]
@bioconda/core Do we need to fix the `packages with divergent build strings` errors for `bulk` and `master`? In this case it was only the Linux build that was a problem, but of course fixing that is changing the build string on OSX too.

**Comment by s-will** [comment]
If it helps / saves time, feel free to remove the failing older recipes

**Comment by dpryan79** [comment]
@s-will Will do, that should make things easier :)

**Pull request merged**
