### PR TITLE
Update bcftools to 1.17

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`bcftools`](https://bioconda.github.io/recipes/bcftools/README.html): **1.16** &rarr; **1.17**

[install with bioconda](http://bioconda.github.io/recipes/bcftools/README.html) [Conda](https://anaconda.org/bioconda/bcftools/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/bcftools`](https://github.com//bioconda/bioconda-recipes/tree/bump/bcftools/recipes/bcftools) (click to view/edit other files)
Summary | BCFtools is a set of utilities that manipulate variant calls in the Variant Call Format (VCF) and its binary counterpart BCF. All commands work transparently with both VCFs and BCFs, both uncompressed and BGZF-compressed.  Most commands accept VCF, bgzipped VCF and BCF with filetype detected automatically even when streaming from a pipe. Indexed VCF and BCF will work in all situations. Un-indexed VCF and BCF and streams will work in most, but not all situations.
Home | [https://github.com/samtools/bcftools](https://github.com/samtools/bcftools)
Releases |[https://github.com/samtools/bcftools/releases](https://github.com/samtools/bcftools/releases)
Author | `@samtools`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by jmarshall** [comment]
As usual, this should wait for a **bioconda-utils** update that pins htslib at 1.17.

**Review by matthdsm — APPROVED** [review]

**Comment by matthdsm** [comment]
@BiocondaBot please merge

**Comment by jmarshall** [comment]
As noted in https://github.com/bioconda/bioconda-recipes/pull/39499#issuecomment-1439169106, this PR has built bcftools 1.17 against htslib 1.16. We normally wait for htslib so that the new bcftools can be built against the new htslib, which is what users and the bcftools maintainers are expecting and hence is less of a maintenance burden for bioconda.

@matthdsm: Before telling the bot to merge this, please explain why you think the htslib pinning bump should be ignored.

**Review by mjsteinbaugh — APPROVED** [review]

**Comment by mjsteinbaugh** [comment]
@BiocondaBot please merge

**Comment by mjsteinbaugh** [comment]
@BiocondaBot please merge

**Comment by 0xaf1f** [comment]
any news about this?

**Comment by mjsteinbaugh** [comment]
@0xaf1f BiocondaBot is having issues merging this, just like with samtools

**Pull request merged**
