### PR TITLE
Porechop

### PR DESCRIPTION
**Pull request by jvolkening**
* [X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [X] This PR adds a new recipe.
* [X] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by daler** [comment]
@jvolkening looks like this package needs compiling, so you'll need to add `gcc`, `libgcc`, and `llvm` as dependencies. Please see https://bioconda.github.io/guidelines.html#c-c for details.

**Comment by jvolkening** [comment]
@daler Thanks, I was just making those changes and testing locally. Porechop has a minimum requirement of GCC >= 4.9.1, and I'm trying to figure out if that's available in conda/bioconda.

**Comment by daler** [comment]
Not yet unfortunately. gcc 4.9 has been in the works for a while at either conda-forge or defaults, I forget. @bgruening do you know what the status of gcc 4.9 is?

**Comment by bgruening** [comment]
There are repos which we can test for a new GCC, but until there are in defaults in can take some time :-(.
@jvolkening can you try removing the GCC as dependency and use the container one?

@daler sorry only available via mobile the next 3 days.

**Comment by jvolkening** [comment]
> can you try removing the GCC as dependency and use the container one?

The above build didn't have the GCC dependency and failed with the error (among others):

`g++: error: unrecognized command line option ‘-std=c++14’`

I believe this is due to not having a recent-enough compiler. GCC 4.9 is available in Trusty but maybe not installed in the docker container being used? I'm new to bioconda development and pretty new to Docker so I'm not quite sure how to approach this.

Incidentally, there were some other errors in the linux build above (lines 797-800) that I have no idea how to deal with:

```
.00:55:58 BIOCONDA ERROR COMMAND FAILED: docker run --net host --rm -v /tmp/tmprgjyu4de/build_script.bash:/opt/build_script.bash -v /anaconda/conda-bld:/opt/host-conda-bld -v /home/travis/build/bioconda/bioconda-recipes/recipes/porechop:/opt/recipe -e CONDA_R=3.3.2 -e CONDA_HTSLIB=1.5 -e LANG=en_US.UTF-8 -e LC_CTYPE=en_US.UTF-8 -e CONDA_GSL=1.16 -e CONDA_NCURSES=5.9 -e CONDA_ROOT=/anaconda -e CONDA_HDF5=1.8.17 -e CONDA_GMP=5.1 -e LC_ALL=en_US.UTF-8 -e CONDA_PY=27 -e MACOSX_DEPLOYMENT_TARGET=10.9 -e CONDA_NPY=112 -e CONDA_ALLOW_SOFTLINKS=false -e CONDA_PERL=5.22.0 -e CONDA_BOOST=1.64 tmp-bioconda-builder /bin/bash /opt/build_script.bash
00:55:58 BIOCONDA ERROR STDOUT+STDERR:
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
```

**Comment by bgruening** [comment]
Sorry I missed that. I have an idea but can only try it Monday. We could add Mikes test GCC channel to our channel list with lowest prio, but we should label all packages compiled with this as experimental.

Our last errors are not real errors just artefact from Docker you can ignore those.

**Comment by jvolkening** [comment]
I'm going to set this aside for now and remove the binary dependency from my Galaxy wrapper so I can test/use it locally. I'll revisit this PR when GCC >= 4.9 works its way into conda.

**Pull request closed without merging**
