### PR TITLE
Update ppanggolin to 2.0.1

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`ppanggolin`](https://bioconda.github.io/recipes/ppanggolin/README.html): **1.2.105** &rarr; **2.0.1**

[install with bioconda](http://bioconda.github.io/recipes/ppanggolin/README.html) [Conda](https://anaconda.org/bioconda/ppanggolin/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/ppanggolin`](https://github.com//bioconda/bioconda-recipes/tree/bump/ppanggolin/recipes/ppanggolin) (click to view/edit other files)
Summary | PPanGGOLiN: Depicting microbial species diversity via a Partitioned PanGenome Graph
Home | [https://github.com/labgem/PPanGGOLiN](https://github.com/labgem/PPanGGOLiN)
Releases |[https://github.com/labgem/PPanGGOLiN/tags](https://github.com/labgem/PPanGGOLiN/tags)
Recipe Maintainer(s) | @axbazin, @jpjarnoux
Author | `@labgem`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by JeanMainguy** [comment]
The v2.0.0 recipe failed to compile on macOS due to an error during Clang's compilation of the C code. To address this issue, we released a patch for v2.0.0, which includes an additional flag in the PPanGGOLiN setup.py. The current recipe has been updated to build this patch release aka the v2.0.1.

**Comment by JeanMainguy** [comment]
@BiocondaBot please fetch artifacts

**Comment by JeanMainguy** [comment]
I have tested the package with the [test suites](https://github.com/labgem/PPanGGOLiN/tree/master/testingDataset) of PPanGGOLiN, and everything works smoothly!

**Comment by JeanMainguy** [comment]
@BiocondaBot please add label

**Review by jfallmann — APPROVED** [review]

**Pull request merged**
