### PR TITLE
fix osra recipe by pinning poppler to v0.52

### PR DESCRIPTION
**Pull request by simonbray**
:information_source:
Bioconda has finished the [GCC7 migration](https://github.com/bioconda/bioconda-recipes/issues/13578). If you are dealing with C/C++ or Python package it can be that you need to rebuild other dependent packages. [Bioconda utils - update-pinning](https://bioconda.github.io/updating.html#updating-recipes-for-a-pinning-change) will assist you with that. If you have any questions please use [issue 13578](https://github.com/bioconda/bioconda-recipes/issues/13578).

----------------

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by bgruening** [comment]
@simonbray is poppler 0.67 not working? https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/conda_build_config.yaml#L537

**Comment by simonbray** [comment]
@bgruening can we merge this, do you think?

**Comment by simonbray** [comment]
Ah no, it hasn't actually built it...

**Comment by bgruening** [comment]
Jupp :(, I couldn't add a commit to your branch. Maybe you can to this to trigger re-rebuild of the yml file.

**Comment by epruesse** [comment]
@simonbray - did you delete your fork?

**Pull request closed without merging**
