### PR TITLE
Update pxblat to 0.3.1

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`pxblat`](https://bioconda.github.io/recipes/pxblat/README.html): **0.3.0** &rarr; **0.3.1**

[install with bioconda](http://bioconda.github.io/recipes/pxblat/README.html) [Conda](https://anaconda.org/bioconda/pxblat/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/pxblat`](https://github.com//bioconda/bioconda-recipes/tree/bump/pxblat/recipes/pxblat) (click to view/edit other files)
Summary | PxBLAT: An Efficient and Ergonomics Python Binding Library for BLAT.
Home | [https://github.com/cauliyang/pxblat](https://github.com/cauliyang/pxblat)
Releases |[https://pypi.org/pypi/pxblat/json](https://pypi.org/pypi/pxblat/json)
Recipe Maintainer(s) | @yangyangli

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by cauliyang** [comment]
Hi! 

I find we can only install pxblat with python=3.11; however, the python version I require is python>=3.9. I try to fix that via manual pr, but I do not know what the reason is.

**Comment by mencian** [comment]
@BiocondaBot please fetch artifacts

**Comment by mencian** [comment]
Attempting to edit the recipe to have separate builds for each python version >=3.9 in PR #42616.

**Comment by cauliyang** [comment]
Hi @mencian, I truly appreciate your great help!

**Pull request closed without merging**
