### PR TITLE
Update to gnuplot v5.0.5

### PR DESCRIPTION
**Pull request by peterjc**
* [ ] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [X] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

Assuming this works, next is gnuplot 5.0.6.

I am also hoping to confirm the recipe's PNG support still works to help resolve this for gnuplot 4.6.0, see https://github.com/bioconda/bioconda-recipes/pull/4655

### CODE REVIEW

**Comment by peterjc** [comment]
Linux and Mac failed with:

```
The following recipes failed linting. See https://bioconda.github.io/linting.html for details:
                        failed_tests
recipe                              
recipes/gnuplot  [in_other_channels]
```

**Comment by bgruening** [comment]
If you want to have an older version, you can skip this linting step by using something like `[lint skip missing_hash for recipes/blasr] [lint skip uses_git_url for recipes/blasr]`

**Comment by peterjc** [comment]
So here ``[lint in_other_channels for recipes/gnuplot]`` in the comment out to work...

**Comment by bgruening** [comment]
`[lint skip in_other_channels for recipes/gnuplot]`

**Comment by peterjc** [comment]
Thanks, let's see if that works...

**Comment by peterjc** [comment]
Mac builds but without PNG support, echoing issue seen in #4655:

```
** Configuration summary for gnuplot 5.0.5:
gnuplot will be compiled with the following terminals:
...
  libgd-based png, jpeg, and gif terminals: no (see config.log)
```

Linux fails with linking to ``libiconv_open``,

```
c++  -g -O2   -o gnuplot alloc.o axis.o breaders.o boundary.o color.o command.o contour.o datablock.o datafile.o dynarray.o eval.o external.o fit.o gadgets.o getcolor.o graph3d.o graphics.o help.o hidden3d.o history.o internal.o interpol.o libcerf.o matrix.o misc.o mouse.o multiplot.o parse.o plot.o plot2d.o plot3d.o pm3d.o readline.o save.o scanner.o set.o show.o specfun.o standard.o stats.o stdfn.o tables.o tabulate.o term.o time.o unset.o util.o util3d.o variable.o version.o     -lz -lgd -lgd -lm -L/opt/conda/conda-bld/recipe_1495108392457/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib -lz -L/opt/conda/conda-bld/recipe_1495108392457/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib -lpng16 -L/opt/conda/conda-bld/recipe_1495108392457/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib -lfreetype -L/opt/conda/conda-bld/recipe_1495108392457/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib -lfontconfig -lfreetype -ljpeg -L/opt/conda/conda-bld/recipe_1495108392457/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib -ltiff -lwebp    -ldl -lm 
/opt/rh/devtoolset-2/root/usr/bin/ld: set.o: undefined reference to symbol 'libiconv_open'
/opt/rh/devtoolset-2/root/usr/bin/ld: note: 'libiconv_open' is defined in DSO /opt/conda/conda-bld/recipe_1495108392457/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/libiconv.so.2 so try adding it to the linker command line
/opt/conda/conda-bld/recipe_1495108392457/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/libiconv.so.2: could not read symbols: Invalid operation
collect2: error: ld returned 1 exit status
```

**Comment by peterjc** [comment]
Linking still failed, it looks like we might have to poke the configuration to point at ``.../lib/libiconv.so.2`` explicitly?

```
c++  -g -O2   -o gnuplot alloc.o axis.o breaders.o boundary.o color.o command.o contour.o datablock.o datafile.o dynarray.o eval.o external.o fit.o gadgets.o getcolor.o graph3d.o graphics.o help.o hidden3d.o history.o internal.o interpol.o libcerf.o matrix.o misc.o mouse.o multiplot.o parse.o plot.o plot2d.o plot3d.o pm3d.o readline.o save.o scanner.o set.o show.o specfun.o standard.o stats.o stdfn.o tables.o tabulate.o term.o time.o unset.o util.o util3d.o variable.o version.o     -lz -lgd -lgd -lm -L/opt/conda/conda-bld/recipe_1495108392457/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib -lz -L/opt/conda/conda-bld/recipe_1495108392457/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib -lpng16 -L/opt/conda/conda-bld/recipe_1495108392457/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib -lfreetype -L/opt/conda/conda-bld/recipe_1495108392457/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib -lfontconfig -lfreetype -ljpeg -L/opt/conda/conda-bld/recipe_1495108392457/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib -ltiff -lwebp    -ldl -lm 
/opt/rh/devtoolset-2/root/usr/bin/ld: set.o: undefined reference to symbol 'libiconv_open'
/opt/rh/devtoolset-2/root/usr/bin/ld: note: 'libiconv_open' is defined in DSO /opt/conda/conda-bld/recipe_1495108392457/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/libiconv.so.2 so try adding it to the linker command line
/opt/conda/conda-bld/recipe_1495108392457/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/libiconv.so.2: could not read symbols: Invalid operation
collect2: error: ld returned 1 exit status
```

For now I will focus on #4738 which will establish if the current recipe works (before attempting to update gnuplot on this pull request).

**Comment by peterjc** [comment]
Confirmed in #4738 that even the current recipe for gnuplot 5.0.4 fails to build with PNG support now.

**Comment by peterjc** [comment]
I'm going to give up on this, as recommended by @croth1 it would be better for focus on the conda-forge gnuplot over the bioconda version.

See also https://github.com/conda-forge/gnuplot-feedstock/pull/1 for updating  conda-forge from gnuplot 5.0.5 to gnuplot 5.0.6

**Pull request closed without merging**
