### PR TITLE
fixes #6661 - pass version, conda build-num and conda distributio…

### LINKED ISSUE #6661: jalview-2.10.2b2 build reports "DEVELOPMENT" as jalview version on startup
tiny hiccup in the conda build - Jalview ought to report its version when built. All it needs is to pass the correct version string via -DJALVIEW_VERSION="" rather than jalview.version.

### PR DESCRIPTION
**Pull request by foreveremain**
fixes #6661 …n type to annotate jalview build - pinging @martin-mann to verify

* [x ] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [ ] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by martin-mann** [comment]
looks good to me, but you are the master of your ant tweaks.. ;) I put my trust in you.. *grin*

**Comment by foreveremain** [comment]
Lets hope I got it right this time!  We are going to refresh the build
system next year so things will be a bit cleaner after 2.10.3 is released
next week.

**Comment by bgruening** [comment]
Sorry I mean build number.

**Comment by bgruening** [comment]
Great thank a bunch Jim. Great to have you here!

**Pull request merged**
