### PR TITLE
Adding new recipe for variant_tools

### PR DESCRIPTION
**Pull request by foellmelanie**
Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it. Note that if you are not already a member of the bioconda project (meaning that you can't add this label), please ping `@bioconda/core` so that your PR can be reviewed and merged (please note if you'd like to be added to the bioconda project). Please see https://github.com/bioconda/bioconda-recipes/issues/15332 for more details.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [x] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by BoPeng** [comment]
@foellmelanie  Could you add me as one of the maintainers of the package? I plan to add variant tools 2.7.2 as a bioconda package (followed by 3.0.2) and realized that you are working on this recipe.

**Comment by BoPeng** [comment]
I see that you are trying to patch variant tools in the recipe. I am working on a 3.0.3 release so let us address the problems upstream.

**Comment by BoPeng** [comment]
I have just released variant tools 3.0.4.

**Comment by BoPeng** [comment]
@jfallmann @dpryan79 @bgruening  I have released variant tools 3.0.6 with two more bug fixes. Please add me to the maintainer list so that I can help you guys finalize this recipe. Thanks.

**Comment by dpryan79** [comment]
@BoPeng Can you create a new PR? That would clean things up a bit. We can add you once that's merged then.

**Comment by BoPeng** [comment]
I can but as far as I can tell this PR blocks the creation of a PR with directory `recipe/variant_tools`...

**Comment by BoPeng** [comment]
Sorry,  I am conceptually wrong here. PRs should not conflict. Let me try to create a new PR.

**Comment by BoPeng** [comment]
https://github.com/bioconda/bioconda-recipes/pull/18309 

There is no test etc, but let us first make it compile...

Right now I do not know how to add you guys as maintainers (in conda-forge we add maintainers in the recipe directly).

**Comment by dpryan79** [comment]
You don't need to add us as maintainers, every bioconda member can update any recipe.

**Comment by dpryan79** [comment]
Closed in lieu of #18309

**Pull request closed without merging**
