### PR TITLE
Update varlociraptor to 2.0.0

### PR DESCRIPTION
**Pull request by BiocondaBot**
Update [`varlociraptor`](https://bioconda.github.io/recipes/varlociraptor/README.html): **1.8.0** &rarr; **2.0.0**

[install with bioconda](http://bioconda.github.io/recipes/varlociraptor/README.html) [Conda](https://anaconda.org/bioconda/varlociraptor/files)

Info | Link
-----|-----
Recipe | [`recipes/varlociraptor`](https://github.com//bioconda/bioconda-recipes/tree/bump/varlociraptor/recipes/varlociraptor) (click to view/edit other files)
Releases |[https://github.com/varlociraptor/varlociraptor/tags](https://github.com/varlociraptor/varlociraptor/tags)
Author | `@varlociraptor`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

### CODE REVIEW

**Comment by mbargull** [comment]
@BiocondaBot, please fetch artifacts

**Comment by mbargull** [comment]
Looks like
```yaml
    - openblas
    - zlib
    - bzip2
    - xz
    - blis
```
could potentially be removed from `requirements/run` (not dyn-linked, apparently):

```
09:41:30 BIOCONDA INFO (OUT)    INFO (varlociraptor,bin/varlociraptor): Needed DSO lib/libgcc_s.so.1 found in conda-forge::libgcc-ng-9.2.0-h24d8f2e_2
09:41:30 BIOCONDA INFO (OUT)    INFO (varlociraptor,bin/varlociraptor): Needed DSO x86_64-conda_cos6-linux-gnu/sysroot/lib/libm.so.6 found in CDT/compiler package conda-forge::gcc_impl_linux-64-7.5.0-hd420e75_6
09:41:30 BIOCONDA INFO (OUT)    INFO (varlociraptor,bin/varlociraptor): Needed DSO x86_64-conda_cos6-linux-gnu/sysroot/lib/libpthread.so.0 found in CDT/compiler package conda-forge::gcc_impl_linux-64-7.5.0-hd420e75_6
09:41:30 BIOCONDA INFO (OUT)    INFO (varlociraptor,bin/varlociraptor): Needed DSO x86_64-conda_cos6-linux-gnu/sysroot/lib/libc.so.6 found in CDT/compiler package conda-forge::gcc_impl_linux-64-7.5.0-hd420e75_6
09:41:30 BIOCONDA INFO (OUT)    INFO (varlociraptor,bin/varlociraptor): Needed DSO x86_64-conda_cos6-linux-gnu/sysroot/lib/libdl.so.2 found in CDT/compiler package conda-forge::gcc_impl_linux-64-7.5.0-hd420e75_6
09:41:30 BIOCONDA INFO (OUT)    INFO (varlociraptor,bin/varlociraptor): Needed DSO x86_64-conda_cos6-linux-gnu/sysroot/lib/ld-linux-x86-64.so.2 found in CDT/compiler package conda-forge::gcc_impl_linux-64-7.5.0-hd420e75_6
09:41:30 BIOCONDA INFO (OUT)    INFO (varlociraptor,bin/varlociraptor): Needed DSO x86_64-conda_cos6-linux-gnu/sysroot/lib/librt.so.1 found in CDT/compiler package conda-forge::gcc_impl_linux-64-7.5.0-hd420e75_6
09:41:30 BIOCONDA INFO (OUT)    INFO (varlociraptor,bin/varlociraptor): Needed DSO lib/libgsl.so.25 found in conda-forge::gsl-2.6-h294904e_0
09:41:30 BIOCONDA INFO (OUT) WARNING (varlociraptor): run-exports library package conda-forge::zlib-1.2.11-h516909a_1006 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
09:41:30 BIOCONDA INFO (OUT) WARNING (varlociraptor): dso library package conda-forge::blis-0.7.0-h516909a_1 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
09:41:30 BIOCONDA INFO (OUT) WARNING (varlociraptor): run-exports library package conda-forge::xz-5.2.5-h516909a_0 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
09:41:30 BIOCONDA INFO (OUT) WARNING (varlociraptor): dso library package conda-forge::libstdcxx-ng-9.2.0-hdf63c60_2 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
09:41:30 BIOCONDA INFO (OUT) WARNING (varlociraptor): run-exports library package conda-forge::libcblas-3.8.0-8_h6e990d7_netlib in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
09:41:30 BIOCONDA INFO (OUT) WARNING (varlociraptor): run-exports library package conda-forge::bzip2-1.0.8-h516909a_2 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
```
```
03:00:49 BIOCONDA INFO (OUT)    INFO (varlociraptor,bin/varlociraptor): Needed DSO lib/libcblas.3.dylib found in conda-forge::libcblas-3.8.0-8_h1ddc27c_netlib
03:00:49 BIOCONDA INFO (OUT)    INFO (varlociraptor,bin/varlociraptor): Needed DSO /System/Library/Frameworks/Security.framework/Versions/A/Security found in the whitelist
03:00:49 BIOCONDA INFO (OUT)    INFO (varlociraptor,bin/varlociraptor): Needed DSO /usr/lib/libSystem.B.dylib found in the whitelist
03:00:49 BIOCONDA INFO (OUT)    INFO (varlociraptor,bin/varlociraptor): Needed DSO lib/libgsl.25.dylib found in conda-forge::gsl-2.6-ha2d443c_0
03:00:49 BIOCONDA INFO (OUT) WARNING (varlociraptor,bin/varlociraptor): /usr/lib/libresolv.9.dylib not found in sysroot, is this binary repackaging? .. do you need to use install_name_tool/patchelf?
03:00:49 BIOCONDA INFO (OUT)    INFO (varlociraptor,bin/varlociraptor): Needed DSO /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation found in the whitelist
03:00:49 BIOCONDA INFO (OUT) WARNING (varlociraptor): dso library package conda-forge::blis-0.7.0-h0b31af3_1 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
03:00:49 BIOCONDA INFO (OUT) WARNING (varlociraptor): run-exports library package conda-forge::bzip2-1.0.8-h0b31af3_2 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
03:00:49 BIOCONDA INFO (OUT) WARNING (varlociraptor): run-exports library package conda-forge::openssl-1.1.1g-h0b31af3_0 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
03:00:49 BIOCONDA INFO (OUT) WARNING (varlociraptor): run-exports library package conda-forge::xz-5.2.5-h0b31af3_0 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
03:00:49 BIOCONDA INFO (OUT) WARNING (varlociraptor): run-exports library package conda-forge::zlib-1.2.11-h0b31af3_1006 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
```

Otherwise, LGTM, feel free to `@BiocondaBot, please merge`

**Comment by johanneskoester** [comment]
Thanks! I've created an issue for that.

**Comment by johanneskoester** [comment]
@bioconda-bot please merge

**Comment by mbargull** [comment]
Oh, I never noticed that "Reference in new issue" functionality. Nice!

**Pull request merged**
