### PR TITLE
rseqc: add linux-aarch64 build

### PR DESCRIPTION
**Pull request by martin-g**
Describe your pull request here

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

### General instructions

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

### Instructions for avoiding API, ABI, and CLI breakage issues
Conda is able to record and lock (a.k.a. pin) dependency versions used at build time of other recipes.
This way, one can avoid that expectations of a downstream recipe with regards to API, ABI, or CLI are violated by later changes in the recipe.
If not already present in the meta.yaml, make sure to specify `run_exports` (see [here](https://bioconda.github.io/contributor/linting.html#missing-run-exports) for the rationale and comprehensive explanation).
Add a `run_exports` section like this:

```yaml
build:
  run_exports:
    - ...

```

with `...` being one of:

| Case                             | run_exports statement                                               |
| -------------------------------- | ------------------------------------------------------------------- |
| semantic versioning              | `{{ pin_subpackage("myrecipe", max_pin="x") }}`     |
| semantic versioning (0.x.x)      | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}`   |
| known breakage in minor versions | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| known breakage in patch versions | `{{ pin_subpackage("myrecipe", max_pin="x.x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| calendar versioning              | `{{ pin_subpackage("myrecipe", max_pin=None) }}`    |

while replacing `"myrecipe"` with either `name` if a `name|lower` variable is defined in your recipe or with the lowercase name of the package in quotes.

### Bot commands for PR management

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

Note that the <code>@BiocondaBot please merge</code> command is now depreciated. Please just squash and merge instead.

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by martin-g** [comment]
The Linux ARM64 build fails with the same reason as:
- #46177

**Comment by martin-g** [comment]
@BiocondaBot please fetch artifacts

**Comment by martin-g** [comment]
```

mgrigorov in 🌐 euler-arm-22 in /tmp/rseqc via 🅒 test123 took 3s 
❯ tar xvf rseqc-5.0.3-py310h0e3f8be_1.tar.bz2                                                                                                                                                              (test123) 
info/run_exports.json
info/test/run_test.py
info/test/run_test.sh
info/hash_input.json
info/index.json
info/recipe/meta.yaml.template
info/recipe/meta.yaml
info/files
info/recipe/conda_build_config.yaml
info/has_prefix
info/about.json
info/paths.json
info/git
lib/python3.10/site-packages/RSeQC-5.0.3.dist-info/INSTALLER
lib/python3.10/site-packages/RSeQC-5.0.3.dist-info/WHEEL
lib/python3.10/site-packages/RSeQC-5.0.3.dist-info/METADATA
lib/python3.10/site-packages/RSeQC-5.0.3.dist-info/RECORD
lib/python3.10/site-packages/RSeQC-5.0.3.dist-info/REQUESTED
lib/python3.10/site-packages/psyco_full.py
lib/python3.10/site-packages/qcmodule/ireader.py
lib/python3.10/site-packages/qcmodule/changePoint.py
bin/bam_stat.py
lib/python3.10/site-packages/qcmodule/quantile.py
lib/python3.10/site-packages/qcmodule/dotProduct.py
lib/python3.10/site-packages/qcmodule/getBamFiles.py
lib/python3.10/site-packages/qcmodule/twoList.py
bin/read_GC.py
bin/read_duplication.py
bin/insertion_profile.py
bin/divide_bam.py
bin/bam2fq.py
bin/read_NVC.py
bin/clipping_profile.py
bin/read_quality.py
bin/deletion_profile.py
lib/python3.10/site-packages/qcmodule/heatmap.py
bin/mismatch_profile.py
bin/sc_bamStat.py
bin/read_hexamer.py
bin/overlay_bigwig.py
bin/inner_distance.py
lib/python3.10/site-packages/qcmodule/FrameKmer.py
bin/sc_seqQual.py
bin/junction_saturation.py
bin/RNA_fragment_size.py
bin/sc_editMatrix.py
bin/split_paired_bam.py
bin/infer_experiment.py
bin/bam2wig.py
lib/python3.10/site-packages/qcmodule/cigar.py
lib/python3.10/site-packages/qcmodule/mystat.py
bin/sc_seqLogo.py
bin/split_bam.py
bin/normalize_bigwig.py
bin/junction_annotation.py
lib/python3.10/site-packages/qcmodule/fastq.py
bin/geneBody_coverage2.py
lib/python3.10/site-packages/qcmodule/orf.py
bin/RPKM_saturation.py
lib/python3.10/site-packages/qcmodule/bam_cigar.py
bin/FPKM-UQ.py
lib/python3.10/site-packages/qcmodule/wiggle.py
lib/python3.10/site-packages/qcmodule/fasta.py
lib/python3.10/site-packages/qcmodule/annoGene.py
bin/geneBody_coverage.py
bin/tin.py
bin/read_distribution.py
bin/FPKM_count.py
lib/python3.10/site-packages/qcmodule/scbam.py
lib/python3.10/site-packages/qcmodule/__init__.py
lib/python3.10/site-packages/qcmodule/BED.py
lib/python3.10/site-packages/qcmodule/SAM.py
lib/python3.10/site-packages/RSeQC-5.0.3.dist-info/direct_url.json
lib/python3.10/site-packages/qcmodule/__pycache__/__init__.cpython-310.pyc
lib/python3.10/site-packages/__pycache__/psyco_full.cpython-310.pyc
lib/python3.10/site-packages/qcmodule/__pycache__/ireader.cpython-310.pyc
lib/python3.10/site-packages/qcmodule/__pycache__/changePoint.cpython-310.pyc
lib/python3.10/site-packages/qcmodule/__pycache__/quantile.cpython-310.pyc
lib/python3.10/site-packages/qcmodule/__pycache__/getBamFiles.cpython-310.pyc
lib/python3.10/site-packages/qcmodule/__pycache__/twoList.cpython-310.pyc
lib/python3.10/site-packages/qcmodule/__pycache__/dotProduct.cpython-310.pyc
lib/python3.10/site-packages/qcmodule/__pycache__/FrameKmer.cpython-310.pyc
lib/python3.10/site-packages/qcmodule/__pycache__/heatmap.cpython-310.pyc
lib/python3.10/site-packages/qcmodule/__pycache__/orf.cpython-310.pyc
lib/python3.10/site-packages/qcmodule/__pycache__/cigar.cpython-310.pyc
lib/python3.10/site-packages/qcmodule/__pycache__/bam_cigar.cpython-310.pyc
lib/python3.10/site-packages/qcmodule/__pycache__/mystat.cpython-310.pyc
lib/python3.10/site-packages/qcmodule/__pycache__/fastq.cpython-310.pyc
lib/python3.10/site-packages/qcmodule/__pycache__/fasta.cpython-310.pyc
lib/python3.10/site-packages/qcmodule/__pycache__/annoGene.cpython-310.pyc
lib/python3.10/site-packages/qcmodule/__pycache__/wiggle.cpython-310.pyc
lib/python3.10/site-packages/qcmodule/__pycache__/scbam.cpython-310.pyc
lib/python3.10/site-packages/qcmodule/__pycache__/BED.cpython-310.pyc
lib/python3.10/site-packages/qcmodule/__pycache__/SAM.cpython-310.pyc
lib/python3.10/site-packages/RSeQC-5.0.3.dist-info/top_level.txt

mgrigorov in 🌐 euler-arm-22 in /tmp/rseqc via 🅒 test123 
❯ file ./bin/*                                                                                                                                                                                             (test123) 
./bin/bam2fq.py:              Objective-C source, ASCII text
./bin/bam2wig.py:             Objective-C source, ASCII text, with very long lines (579)
./bin/bam_stat.py:            Objective-C source, ASCII text
./bin/clipping_profile.py:    Objective-C source, ASCII text
./bin/deletion_profile.py:    Objective-C source, ASCII text, with very long lines (313)
./bin/divide_bam.py:          Objective-C source, ASCII text
./bin/FPKM-UQ.py:             a /opt/conda/conda-bld/rseqc_1714499589781/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold script, ASCII text executable, with very long lines (325)
./bin/FPKM_count.py:          Objective-C source, ASCII text, with very long lines (573)
./bin/geneBody_coverage.py:   Objective-C source, ASCII text, with very long lines (399)
./bin/geneBody_coverage2.py:  a /opt/conda/conda-bld/rseqc_1714499589781/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold script, ASCII text executable
./bin/infer_experiment.py:    Objective-C source, ASCII text
./bin/inner_distance.py:      Objective-C source, ASCII text
./bin/insertion_profile.py:   Objective-C source, ASCII text
./bin/junction_annotation.py: Objective-C source, ASCII text
./bin/junction_saturation.py: Objective-C source, ASCII text, with very long lines (302)
./bin/mismatch_profile.py:    Objective-C source, ASCII text, with very long lines (313)
./bin/normalize_bigwig.py:    a /opt/conda/conda-bld/rseqc_1714499589781/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold script, ASCII text executable
./bin/overlay_bigwig.py:      a /opt/conda/conda-bld/rseqc_1714499589781/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold script, ASCII text executable, with very long lines (557)
./bin/read_distribution.py:   Objective-C source, ASCII text
./bin/read_duplication.py:    Objective-C source, ASCII text
./bin/read_GC.py:             Objective-C source, ASCII text
./bin/read_hexamer.py:        a /opt/conda/conda-bld/rseqc_1714499589781/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold script, ASCII text executable
./bin/read_NVC.py:            Objective-C source, ASCII text
./bin/read_quality.py:        Objective-C source, ASCII text, with very long lines (420)
./bin/RNA_fragment_size.py:   a /opt/conda/conda-bld/rseqc_1714499589781/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold script, ASCII text executable
./bin/RPKM_saturation.py:     Objective-C source, ASCII text, with very long lines (573)
./bin/sc_bamStat.py:          a /opt/conda/conda-bld/rseqc_1714499589781/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold script, ASCII text executable
./bin/sc_editMatrix.py:       a /opt/conda/conda-bld/rseqc_1714499589781/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold script, ASCII text executable
./bin/sc_seqLogo.py:          a /opt/conda/conda-bld/rseqc_1714499589781/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold script, ASCII text executable, with very long lines (345)
./bin/sc_seqQual.py:          a /opt/conda/conda-bld/rseqc_1714499589781/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold script, ASCII text executable, with very long lines (336)
./bin/split_bam.py:           Objective-C source, ASCII text, with very long lines (330)
./bin/split_paired_bam.py:    Objective-C source, ASCII text
./bin/tin.py:                 a /opt/conda/conda-bld/rseqc_1714499589781/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold script, ASCII text executable, with very long lines (414)

mgrigorov in 🌐 euler-arm-22 in /tmp/rseqc via 🅒 test123 
❯ conda install ./rseqc-5.0.3-py310h0e3f8be_1.tar.bz2                                                                                                                                                      (test123) 

Downloading and Extracting Packages:
                                                                                                                                                                                                                     

Downloading and Extracting Packages:

Preparing transaction: done
Verifying transaction: done
Executing transaction: done


mgrigorov in 🌐 euler-arm-22 in /tmp/rseqc via 🅒 test123 took 45s 
❯ tin.py                                                                                                                                                                                                   (test123) 
Usage: tin.py [options]
-------------------------------------------------------------------------------------------------
This program calculates transcript integrity number (TIN) for each transcript (or gene) in
BED file. TIN is conceptually similar to RIN (RNA integrity number) but provides transcript
level measurement of RNA quality and is more sensitive to measure low quality RNA samples:

1) TIN score of a transcript is used to measure the RNA integrity of the transcript.
2) Median TIN score across all transcripts can be used to measure RNA integrity  of that
   "RNA sample".
3) TIN ranges from 0 (the worst) to 100 (the best). TIN = 60 means: 60% of the transcript
   has been covered if the reads coverage were uniform.
4) TIN will be assigned to 0 if the transcript has no coverage or covered reads is fewer than
   cutoff.
-------------------------------------------------------------------------------------------------


Options:
  --version             show program's version number and exit
  -h, --help            show this help message and exit
  -i INPUT_FILES, --input=INPUT_FILES
                        Input BAM file(s). "-i" takes these input: 1) a single
                        BAM file. 2) "," separated BAM files (no spaces
                        allowed). 3) directory containing one or more bam
                        files. 4) plain text file containing the path of one
                        or more bam files (Each row is a BAM file path). All
                        BAM files should be sorted and indexed using samtools.
                        [required]
  -r REF_GENE_MODEL, --refgene=REF_GENE_MODEL
                        Reference gene model in BED format. Must be strandard
                        12-column BED file. [required]
  -c MINIMUM_COVERAGE, --minCov=MINIMUM_COVERAGE
                        Minimum number of read mapped to a transcript.
                        default=10
  -n SAMPLE_SIZE, --sample-size=SAMPLE_SIZE
                        Number of equal-spaced nucleotide positions picked
                        from mRNA. Note: if this number is larger than the
                        length of mRNA (L), it will be halved until it's
                        smaller than L. default=100
  -s, --subtract-background
                        Subtract background noise (estimated from intronic
                        reads). Only use this option if there are substantial
                        intronic reads.
```
LGTM!

**Comment by martin-g** [comment]
@BiocondaBot please add label

**Review by rpetit3 — APPROVED** [review]

**Pull request merged**
