### PR TITLE
Update BASIC to v1.4.0

### PR DESCRIPTION
**Pull request by dcroote**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by dcroote** [comment]
I am a bit confused by the lint failure. I can add `noarch: python` and linting will pass, but from the [linting document](https://bioconda.github.io/linting.html#should-be-noarch-currently-disabled) and the [recipe checklist](https://bioconda.github.io/guidelines.html#bioconda-recipe-checklist) I thought this was disabled / not desired.

**Comment by bgruening** [comment]
Sorry @dcroote! We are lacking behind here. We are currently in a complete rebuild of the bioconda channel and migrate to conda-build-3. noarch is now possible, please enable it :)

**Comment by bgruening** [comment]
Thanks!

**Comment by dcroote** [comment]
Thank you @bgruening !

**Pull request merged**
