### PR TITLE
Julia 0.5.2

### PR DESCRIPTION
**Pull request by dfornika**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by dfornika** [comment]
This is identical to #5489, except the build number has been bumped. The last pull request didn't trigger the build to be sent to the bioconda channel on anaconda.org because the build number hadn't been incremented.

**Comment by dfornika** [comment]
This recipe has been merged into conda-forge.

https://github.com/conda-forge/staged-recipes/pull/3503

**Comment by bgruening** [comment]
@dfornika thanks a lot for doing this and the entire review process over there!
If you like you can now remove the recipe from here.

**Comment by dfornika** [comment]
I've removed the `julia` directory from my branch, but it looks like there's a conflict that has to be resolved before it can be merged.

**Comment by bgruening** [comment]
@dfornika I can not resolve this conflict for you, either we merge master into your branch or rebase. You can also start a new branch from a fresh master and just remove the recipe.

Thanks!

**Pull request closed without merging**
