### PR TITLE
[BULK] Update for 291018

### PR DESCRIPTION
**Pull request by dpryan79**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [x] This PR does something else (explain below).

This blacklists a bunch of packages so building proceeds a bit faster. The packages are mostly dependent upon `bioconductor-mzr`, which has an odd compilation error. Others are dependent on pages stuck in conda-forge's `staged-recipes repository.

By the end of today ~90% of the bioconductor packages that can be built will have been. My hope is that at some point tomorrow we can merge `master` in and finish this.

### CODE REVIEW

**Comment by bgruening** [comment]
ping @sneumann 
@dpryan79 I will try to get to conda-forge.

**Comment by dpryan79** [comment]
Thanks Björn!

**Comment by sneumann** [comment]
Hi, happy to help out, but need some guidance on what exactly the issue is. 
Björn and I already tried to reproduce the mzR build issue on my laptop, 
and we got 1) one link error about a missing `libgfortran.so.3` and 2) a link error due to 
```
Error: package or namespace load failed for ‘mzR’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '.../placehold_p/lib/R/library/mzR/libs/mzR.so':
undefined symbol: _ZNK2H510H5Location15getObjnameByIdxB5cxx11Ey
```
also happy to meet on some gitter for the next hour or so. Yours, Steffen

**Comment by dpryan79** [comment]
We get a similar link error when we build in the docker container (either locally or on circleci). The exact error seems to depend on the version of gcc used. If you know exactly what's causing that then we'd at least have decent starting point for resolving this.

**Comment by sneumann** [comment]
Any command line for me to reproduce ? Or link to the error message ?

**Comment by sneumann** [comment]
The undefined symbol is `H5::H5Location::openDataSet(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const` which might indicate that either 1) there are two libhdf5.so and two sets of `hdf5.h` headers are around, and things get mixed up. mzR is supposed to compile and link against the hdf5 within the bioconductor-rhdf5 package. https://github.com/sneumann/mzR/blob/master/DESCRIPTION#L23 so there should not be other hdf5's around. 

P.S.: How to install `bioconda-utils` ? I am building via `conda build -c conda-forge -c bioconda recipes/bioconductor-mzr/`

**Comment by dpryan79** [comment]
`conda install -c conda-forge -c bioconda bioconda-utils`.

**Comment by dpryan79** [comment]
BTW, I suspect your suspicion is correct, perhaps there are indeed multiple hdf5 instances hanging around (I wouldn't have expected rhdf5 to come with its own).

**Comment by sneumann** [comment]
and indeed there are two copies of hdf5. Can you get rid of one of them ?
```
sneumann@msbi-corei:~/miniconda2/conda-bld/bioconductor-mzr_1540848921993/...
$ find . -name "hdf5.h"
./include/hdf5.h
./lib/R/library/Rhdf5lib/include/hdf5.h
sneumann@msbi-corei:~/miniconda2/conda-bld/bioconductor-mzr_1540848921993/...
$ find . -name "libhdf5*"
./lib/libhdf5.a
./lib/libhdf5.so
...
./lib/R/library/Rhdf5lib/lib/libhdf5.a
./lib/R/library/Rhdf5lib/lib/libhdf5_cpp.a
```

**Comment by dpryan79** [comment]
I bet we can delete the wrong static libhdf5 during the build, it's getting brought in by netcdf, which requires libhdf5.so.

**Comment by sneumann** [comment]
Ah, moment, maybe we can get rid of netcdf itself!

**Comment by dpryan79** [comment]
That would make life easier if possible.

**Pull request merged**
