### PR TITLE
Update racon, and move to new repo

### PR DESCRIPTION
**Pull request by cgjosephlee**
Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it. Note that if you are not already a member of the bioconda project (meaning that you can't add this label), please ping `@bioconda/core` so that your PR can be reviewed and merged (please note if you'd like to be added to the bioconda project). Please see https://github.com/bioconda/bioconda-recipes/issues/15332 for more details.

* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

---

Racon moved to new repo url (https://github.com/lbcb-sci/racon) since 1.4.4, and it's now 1.4.7.

### CODE REVIEW

**Comment by cgjosephlee** [comment]
@bioconda/core

**Comment by dpryan79** [comment]
Thanks @cgjosephlee!

**Comment by cgjosephlee** [comment]
Thank you.
Is this merged as single commit, so conda cannot find versions between 1.4.4 and 1.4.6?
I did push several commits for each version.

```
$ conda search racon
Loading channels: done
# Name                       Version           Build  Channel
racon                          0.5.0               1  bioconda
racon                          0.5.0               2  bioconda
racon                          0.5.0          py27_0  bioconda
racon                          1.0.0               0  bioconda
racon                          1.0.0               1  bioconda
racon                          1.0.1               0  bioconda
racon                          1.1.0               0  bioconda
racon                          1.2.0               0  bioconda
racon                          1.2.0          py27_1  bioconda
racon                          1.2.0          py35_1  bioconda
racon                          1.2.0          py36_1  bioconda
racon                          1.2.1          py27_1  bioconda
racon                          1.2.1          py35_1  bioconda
racon                          1.2.1          py36_1  bioconda
racon                          1.3.0          py27_1  bioconda
racon                          1.3.0          py35_1  bioconda
racon                          1.3.0          py36_1  bioconda
racon                          1.3.1      he941832_4  bioconda
racon                          1.3.1      he941832_5  bioconda
racon                          1.3.1          py27_0  bioconda
racon                          1.3.1          py27_1  bioconda
racon                          1.3.1          py35_0  bioconda
racon                          1.3.1          py35_1  bioconda
racon                          1.3.1          py36_0  bioconda
racon                          1.3.1          py36_1  bioconda
racon                          1.3.2      he860b03_1  bioconda
racon                          1.3.2      he941832_0  bioconda
racon                          1.3.3      he860b03_1  bioconda
racon                          1.4.0      he860b03_0  bioconda
racon                          1.4.2      he513fc3_0  bioconda
racon                          1.4.3      he513fc3_0  bioconda
racon                          1.4.7      he513fc3_0  bioconda
```

**Comment by dpryan79** [comment]
The upload machinery just sees a branch, so the various intermediate versions won't be built.

**Pull request merged**
