### PR TITLE
Update parallel-fastq-dump

### PR DESCRIPTION
**Pull request by Maarten-vd-Sande**
parallel-fastq-dump uses setuptools to install, however is not in the host requirements. 

https://github.com/rvalieris/parallel-fastq-dump/blob/master/setup.py#L2
----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by Maarten-vd-Sande** [comment]
`ERROR: build.sh:1: setup_py_install_args: The recipe uses setuptools without required arguments`

https://bioconda.github.io/contributor/linting.html?highlight=setup_py_install_args#setup-py-install-args
I changed the call to `$PYTHON setup.py install --single-version-externally-managed --record=record.txt`, but that does not seem to solve my issues.

**Comment by dpryan79** [comment]
Ah, build.sh is superfluous

**Comment by Maarten-vd-Sande** [comment]
Ah oops :facepalm:

**Comment by dpryan79** [comment]
@Maarten-vd-Sande Was the lack of an explicit setuptools causing an issue? If so then it's likely needed during runtime as well.

**Comment by Maarten-vd-Sande** [comment]
@dpryan79 yes you are right. After further inspectation this only happens when we install with mamba, and it seems to happen with khmer as well:
```
(get_fastq) sande@ocimum:~$ parallel-fastq-dump --sra-id SRR1219899 --threads 4 --outdir out/ --split-files --gzip
SRR ids: ['SRR1219899']
extra args: ['--split-files', '--gzip']
tempdir: /tmp/pfd_z2eq3huz
2020-06-12T11:10:33 sra-stat.2.10.7 err: query unauthorized while resolving query within virtual file system module - failed to resolve accession 'SRR1219899' - Access denied - please request permission to access phs000710/UR in dbGaP ( 403 )
2020-06-12T11:10:33 sra-stat.2.10.7 err: query unauthorized while resolving query within virtual file system module - failed to resolve accession 'SRR1219899' - Access denied - please request permission to access phs000710/UR in dbGaP ( 403 )
2020-06-12T11:10:33 sra-stat.2.10.7 int: directory not found while opening manager within virtual file system module - 'SRR1219899'
Traceback (most recent call last):
  File "/home/sande/anaconda3/envs/get_fastq/bin/parallel-fastq-dump", line 4, in <module>
    __import__('pkg_resources').run_script('parallel-fastq-dump==0.6.6', 'parallel-fastq-dump')
  File "/home/sande/anaconda3/envs/get_fastq/lib/python3.8/site-packages/pkg_resources/__init__.py", line 667, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/sande/anaconda3/envs/get_fastq/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1471, in run_script
    exec(script_code, namespace, namespace)
  File "/home/sande/anaconda3/envs/get_fastq/lib/python3.8/site-packages/parallel_fastq_dump-0.6.6-py3.8.egg/EGG-INFO/scripts/parallel-fastq-dump", line 119, in <module>
  File "/home/sande/anaconda3/envs/get_fastq/lib/python3.8/site-packages/parallel_fastq_dump-0.6.6-py3.8.egg/EGG-INFO/scripts/parallel-fastq-dump", line 112, in main
  File "/home/sande/anaconda3/envs/get_fastq/lib/python3.8/site-packages/parallel_fastq_dump-0.6.6-py3.8.egg/EGG-INFO/scripts/parallel-fastq-dump", line 15, in pfd
  File "/home/sande/anaconda3/envs/get_fastq/lib/python3.8/site-packages/parallel_fastq_dump-0.6.6-py3.8.egg/EGG-INFO/scripts/parallel-fastq-dump", line 65, in get_spot_count
IndexError: list index out of range
```
I am actually wondering now if this is a mamba or conda issue

**Comment by dpryan79** [comment]
That looks like an authentication problem, not something due to setuptools.

**Comment by Maarten-vd-Sande** [comment]
Hmm I guess you are correct. A colleague of mine reported this problem like this and he said that installing setuptools solved the problem. And when I looked at the recipe indeed setuptools was missing but the program requires setuptools, so I kinda assumed that was the issue. 

Should we still keep these changes, or should I just close the PR?

**Comment by dpryan79** [comment]
The recipe is tidied up now, so we might as well keep it.

**Comment by dpryan79** [comment]
@bioconda-bot please merge

**Pull request merged**
