### PR TITLE
Build bedtools for linux-aarch64

### PR DESCRIPTION
**Pull request by jmarshall**
Add additional-platforms sections.

----

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

Note that the <code>@BiocondaBot please merge</code> command is now depreciated. Please just squash and merge instead.

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by jmarshall** [comment]
@BiocondaBot please add label

**Comment by jmarshall** [comment]
I've checked the new ARM package and it passes basic execution tests.

**Review by rpetit3 — APPROVED** [review]

**Comment by rpetit3** [comment]
@jmarshall curious how you are doing the testing. I'm tempted to set up a raspberry pi for local tests

**Comment by jmarshall** [comment]
I have an oldish Raspberry Pi 3 with RPi OS on it with miniforge installed (miniconda borked during installation in a fairly known way). However actually doing a `conda create …` spins forever and I haven't yet looked into why — I suspect my SD card or perhaps some package updating needed.

So instead I have Debian bookworm running under UTM on my Apple Silicon Mac, again with miniforge. This is a good test environment though I'd vaguely prefer not to have to deal with the VM.

**Pull request merged**
